Repository demisto/content, pull requests merged in 2018-08, with the labels that each got.

#1719 Virus Total - Enhancements and private API integration
  Integrations/integration-VirusTotal-Private_API.yml
  Integrations/integration-VirusTotal.yml
  TestPlaybooks/playbook-virusTotalPrivateAPI-test.yml
  Tests/conf.json
Labels: ReadyForPlaybook

#1562 Palo Alto Appframework integration
  Integrations/integration-Palo_Alto_AppFramework.yml
  TestPlaybooks/playbook-pan-appframework-test.yml
Labels: ReadyForPlaybook

#1873 SEPM Quarantine error due to mishandled response #12709
  Integrations/integration-SymantecEndpointProtection.yml
Labels: bug

#1923 Fix no email address while running Account enrichment playbook
  Playbooks/playbook-Account_Enrichment.yml
Labels: bug

#1982 Crowdstrike falcon intel pdf download - 504 error
  TestPlaybooks/playbook-CrowdStrike_Intel_Test.yml
Labels: bug

#2004 Common server python
  Scripts/script-CommonServerPython.yml
Labels: enhancement
