Repository demisto/content, pull requests merged in 2018-12, with the labels that each got.

#2543 QRadar enhancements
  Integrations/integration-QRadar.yml
  Scripts/script-QRadarGetCorrelationLogs.yml
  Scripts/script-QRadarGetOffenseCorrelations.yml
Labels: enhancement

#2651 Threat Grid - Expand contents
  Integrations/integration-Threat_Grid.yml
Labels: bug

#2689 AbuseIPDB integration
  Integrations/integration-AbuseDB.yml
  TestPlaybooks/playbook-AbuseIPDB-test.yml
  Tests/conf.json
Labels: inprogress

#2670 Trustar enhancement
  Integrations/integration-TruSTAR.yml
  TestPlaybooks/playbook-TruSTAR_Test.yml
Labels: enhancement, inprogress
