Repository demisto/content, pull requests merged in 2018-09, with the labels that each got.

#1816 Python3 Docker for TextFromHTML
  Scripts/script-TextFromHTML.yml
Labels: bug, enhancement

#1930 Cybereason integration
  Integrations/integration-Cybereason.yml
  TestPlaybooks/playbook-Cybereason_Test.yml
Labels: ReadyForPlaybook

#2090 IsIpInRanges enhancement
  Scripts/script-IsIPInRanges.yml
Labels: enhancement

#2162 re-write mcafee atd in python
  Integrations/integration-McAfee-ATD.yml
Labels: bug, enhancement
