Repository demisto/content, pull requests merged in 2019-02, with the labels that each got.

#2932 Gmail get_user function fix
  Integrations/integration-Gmail.yml
Labels: bug

#2966 Restore the pcap extractor test script
  TestPlaybooks/playbook-PcapHTTPExtractor-test.yml
Labels: bug

#2928 Phishme fix
  Integrations/integration-PhishMe.yml
  TestPlaybooks/playbook-PhishMe_test.yml
  Tests/id_set.json
  Tests/secrets_white_list.json
Labels: bug, enhancement

#3008 Fixed pdf outputs while maintaining 4.1 extractIndicators functionality
  Scripts/script-ReadPDFFile.yml
  TestPlaybooks/playbook-Extract_Indicators_From_File_-_test.yml
Labels: content

#2963 Rewriting Arcsight ESM in python
  Integrations/ArcSightESM/ArcSightESM.py
  Integrations/ArcSightESM/ArcSightESM.yml
  Integrations/ArcSightESM/ArcSightESM_image.png
  Integrations/integration-ArcSightESM.yml
  Playbooks/playbook-Arcsight_-_Get_events_related_to_the_Case.yml
  TestPlaybooks/playbook-ArcSight_Test.yml
  TestPlaybooks/playbook-Arcsight_-_Get_events_test.yml
  Tests/conf.json
  Tests/id_set.json
  Tests/secrets_white_list.json
Labels: content

#3029 fixed dbot score
  Integrations/integration-McAfee-TIE.yml
  Playbooks/playbook-Hunt_for_bad_IOCs.yml
  Playbooks/playbook-Rapid_IOC_Hunting_Playbook.yml
  Playbooks/playbook-TIE_-_IOC_Hunt.yml
  TestPlaybooks/playbook-McAfee-TIE_Test.yml
  Tests/conf.json
  Tests/id_set.json
Labels: bug, content

#3042 Fixed gmail-add-filter from argument not working properly
  Integrations/integration-Gmail.yml
Labels: bug, content

#3047 Fixed sandblast
  Integrations/integration-Sandblast.yml
Labels: bug, content

#3053 better incidents information
  Integrations/ArcSightESM/ArcSightESM.py
Labels: content

#3052 PhishMe test fix
  TestPlaybooks/playbook-PhishMe_test.yml
  TestPlaybooks/playbook-virusTotalPrivateAPI-test.yml
  Tests/secrets_white_list.json
Labels: content

#3057 dupes fix
  Integrations/ArcSightESMv2/ArcSightESMv2.py
  Integrations/ArcSightESMv2/ArcSightESMv2.yml
  Integrations/ArcSightESMv2/ArcSightESMv2_image.png
  Integrations/integration-ArcSightESM.yml
  Playbooks/playbook-Arcsight_-_Get_events_related_to_the_Case.yml
  TestPlaybooks/playbook-ArcSight_Test.yml
  Tests/conf.json
  Tests/id_set.json
Labels: content
