Repository demisto/content, pull requests merged in 2019-12, with the labels that each got.

#5025 Packagified ProofPointDecodeURL
  Scripts/ProofpointDecodeURL/CHANGELOG.md
  Scripts/ProofpointDecodeURL/Pipfile
  Scripts/ProofpointDecodeURL/Pipfile.lock
  Scripts/ProofpointDecodeURL/ProofpointDecodeURL.py
  Scripts/ProofpointDecodeURL/ProofpointDecodeURL.yml
  Scripts/script-ProofpointDecodeURL.yml
  Tests/scripts/hook_validations/integration.py
  Tests/scripts/hook_validations/script.py
  Tests/scripts/hook_validations/tests/integration_test.py
  Tests/scripts/hook_validations/tests/script_test.py
Labels: docs-approved

#5018 Anomali 500 fix
  Integrations/Anomali_ThreatStream_v2/Anomali_ThreatStream_v2.py
  Integrations/Anomali_ThreatStream_v2/Anomali_ThreatStream_v2.yml
  Integrations/Anomali_ThreatStream_v2/Anomali_ThreatStream_v2_test.py
  Integrations/Anomali_ThreatStream_v2/CHANGELOG.md
Labels: bug, docs-approved

#5023 Fixed issue with Qradar scripts
  Scripts/QRadarGetCorrelationLogs/CHANGELOG.md
  Scripts/QRadarGetCorrelationLogs/QRadarGetCorrelationLogs.py
  Scripts/QRadarGetCorrelationLogs/QRadarGetCorrelationLogs.yml
  Scripts/QRadarGetCorrelationLogs/QRadarGetCorrelationLogs_test.py
  Scripts/QRadarGetOffenseCorrelations/CHANGELOG.md
  Scripts/QRadarGetOffenseCorrelations/QRadarGetOffenseCorrelations.py
  Scripts/QRadarGetOffenseCorrelations/QRadarGetOffenseCorrelations.yml
  Scripts/QRadarGetOffenseCorrelations/QRadarGetOffenseCorrelations_test.py
Labels: bug, docs-approved

#5035 Fixing slack
  Tests/scripts/slack_notifier.py
Labels: docs-approved

#5017 fix playbook
  Playbooks/playbook-PhishingDemo-Onboarding.yml
  Playbooks/playbook-PhishingDemo-Onboarding_CHANGELOG.md
Labels: bug, docs-approved

#5028 Misp - added data filtering
  Integrations/MISP_V2/CHANGELOG.md
  Integrations/MISP_V2/MISP_V2.py
  Integrations/MISP_V2/MISP_V2.yml
  Integrations/MISP_V2/MISP_V2_test.py
  Integrations/MISP_V2/test_data/test_constants.py
  TestPlaybooks/playbook-MISP_V2-Test.yml
Labels: bug, docs-approved

#5038 Removed input value from NIST Lessons learned playbook
  Playbooks/playbook-NIST_-_Lessons_Learned.yml
  Playbooks/playbook-NIST_-_Lessons_Learned_CHANGELOG.md
Labels: docs-approved

#5024 add secrets to pre-commit hooks
  .hooks/pre-commit
  Tests/scripts/hook_validations/secrets.py
Labels: docs-approved

#5041 Raised number of retries for closing tasks
  TestPlaybooks/playbook-Endpoint_Malware_Investigation_-_Generic_-_Test.yml
Labels: docs-approved

#5037 Docker image latest tag - user msgs changes
  Tests/scripts/hook_validations/docker.py
  Tests/scripts/hook_validations/tests/docker_test.py
  Tests/secrets_white_list.json
Labels: docs-approved

#5040 Skipped tests
  Tests/conf.json
Labels: docs-approved

#5054 Fixing test and removing from skipped
  TestPlaybooks/playbook-AlphaSOC_Wisdom_Response_Test.yml
  Tests/conf.json
Labels: docs-approved

#5053 Safe breach test failure
  Tests/conf.json
Labels: docs-approved

#4926 Exabeam new commands
  Integrations/Exabeam/CHANGELOG.md
  Integrations/Exabeam/Exabeam.py
  Integrations/Exabeam/Exabeam.yml
  Integrations/Exabeam/Exabeam_test.py
  Integrations/Exabeam/Pipfile
  Integrations/Exabeam/Pipfile.lock
  Integrations/Exabeam/test_data/__init__.py
  Integrations/Exabeam/test_data/response_constants.py
  Integrations/Exabeam/test_data/result_constants.py
  TestPlaybooks/playbook-Exabeam-test.yml
  Tests/secrets_white_list.json
Labels: docs-approved

#4989 Symantec bluecoat malware analysis - Beta
  Beta_Integrations/SymantecBlueCoatMalwareAnalysis/SymantecBlueCoatMalwareAnalysis.py
  Beta_Integrations/SymantecBlueCoatMalwareAnalysis/SymantecBlueCoatMalwareAnalysis.yml
  Beta_Integrations/SymantecBlueCoatMalwareAnalysis/SymantecBlueCoatMalwareAnalysis_description.md
  Beta_Integrations/SymantecBlueCoatMalwareAnalysis/SymantecBlueCoatMalwareAnalysis_image.png
  Beta_Integrations/playbook-SymantecBlueCoatMalwareAnalysis_DetonateFile.yml
  Beta_Integrations/playbook-SymantecBlueCoatMalwareAnalysis_DetonateURL.yml
Labels: docs-approved

#5056 Exabeam - add readme
  Integrations/Exabeam/README.md
Labels: docs-approved

#4864 PAN-OS 8.1 vs 9.0 custom url category default behavior changes
  Integrations/Panorama/CHANGELOG.md
  Integrations/Panorama/Panorama.py
  Integrations/Panorama/Panorama.yml
  TestPlaybooks/playbook-palo_alto_panorama_test_pb.yml
Labels: docs-approved

#4696 PAN-OS EDL enhancements
  Integrations/PaloAltoNetworks_PAN_OS_EDL_Management/CHANGELOG.md
  Integrations/PaloAltoNetworks_PAN_OS_EDL_Management/PaloAltoNetworks_PAN_OS_EDL_Management.py
  Integrations/PaloAltoNetworks_PAN_OS_EDL_Management/PaloAltoNetworks_PAN_OS_EDL_Management.yml
  Integrations/PaloAltoNetworks_PAN_OS_EDL_Management/PaloAltoNetworks_PAN_OS_EDL_Management_description.md
  TestPlaybooks/playbook-PAN_OS_EDL_Management-Test.yml
Labels: docs-approved

#5063 return cybereason to unskipped
  Tests/conf.json
Labels: docs-approved

#5066 remove qualys from skipped
  TestPlaybooks/playbook-Qualys-Test.yml
  Tests/conf.json
Labels: docs-approved

#4797 MSGraphGroups - New Integration
  Integrations/MicrosoftGraphGroups/MicrosoftGraphGroups.py
  Integrations/MicrosoftGraphGroups/MicrosoftGraphGroups.yml
  Integrations/MicrosoftGraphGroups/MicrosoftGraphGroups_description.md
  Integrations/MicrosoftGraphGroups/MicrosoftGraphGroups_image.png
  Integrations/MicrosoftGraphGroups/MicrosoftGraphGroups_test.py
  Integrations/MicrosoftGraphGroups/Pipfile
  Integrations/MicrosoftGraphGroups/Pipfile.lock
  Integrations/MicrosoftGraphGroups/__init__.py
  Integrations/MicrosoftGraphGroups/test_data/response_constants.py
  Integrations/MicrosoftGraphGroups/test_data/result_constants.py
  Integrations/__init__.py
  TestPlaybooks/playbook-MicrosoftGraphGroups-Test.yml
  Tests/conf.json
  Tests/secrets_white_list.json
Labels: docs-approved

#5069 Build shift
  Tests/conf.json
Labels: docs-approved

#5065 Unskip ssdeepreputation
  TestPlaybooks/script-SsdeepReputationTest.yml
  Tests/conf.json
Labels: docs-approved

#5074 Cisco align image fix
  Integrations/integration-IronPort.yml
  Integrations/integration-IronPort_CHANGELOG.md
Labels: docs-approved

#5076 Fix schemas required field
  Tests/schemas/canvas-context-connections.yml
  Tests/schemas/dashboard.yml
  Tests/schemas/incidentfields.yml
  Tests/schemas/playbook.yml
  Tests/schemas/report.yml
  Tests/schemas/widget.yml
Labels: docs-approved

#5067 AWS Access Analyzer
  Integrations/AWS-AccessAnalyzer/AWS-AccessAnalyzer.py
  Integrations/AWS-AccessAnalyzer/AWS-AccessAnalyzer.yml
  Integrations/AWS-AccessAnalyzer/AWS-AccessAnalyzer_description.md
  Integrations/AWS-AccessAnalyzer/AWS-AccessAnalyzer_image.png
Labels: Contribution, docs-approved

#5068 CommonServer - comment about DBot Score object
  Scripts/CommonServerPython/CHANGELOG.md
  Scripts/CommonServerPython/CommonServerPython.py
  Scripts/script-CommonServer.yml
  Scripts/script-CommonServer_CHANGELOG.md
Labels: docs-approved

#4979 Ml models import export
  Scripts/ExportMLModel/ExportMLModel.py
  Scripts/ExportMLModel/ExportMLModel.yml
  Scripts/ExportMLModel/ExportMLModel_test.py
  Scripts/ExportMLModel/TestData/input_json_file_test
  Scripts/ImportMLModel/ImportMLModel.py
  Scripts/ImportMLModel/ImportMLModel.yml
  Scripts/ImportMLModel/ImportMLModel_test.py
  Scripts/ImportMLModel/TestData/entry_file
Labels: docs-approved

#5080 remove Get File Sample By Hash - Generic - Test
  Tests/conf.json
Labels: docs-approved

#5087 remove carbon black tests
  Tests/conf.json
Labels: docs-approved

#5075 changed categories
  Integrations/GitHub/GitHub.yml
  Integrations/Gmail/CHANGELOG.md
  Integrations/Gmail/Gmail.yml
  Integrations/Netcraft/CHANGELOG.md
  Integrations/Netcraft/Netcraft.yml
Labels: docs-approved

#5081 remove Get File Sample From Hash - Generic - Test
  Tests/conf.json
Labels: docs-approved

#5089 Fix generic polling documentation link
  README.md
Labels: docs-approved

#5077 Slack - Better Handling of user invites in mirroring
  Integrations/Slack/CHANGELOG.md
  Integrations/Slack/Slack.py
  Integrations/Slack/Slack.yml
  Integrations/Slack/Slack_test.py
Labels: docs-approved

#5072 cylance-protect-v2-unskip
  Tests/conf.json
Labels: docs-approved

#4928 PAN-OS urlfiltering enhancements
  Integrations/Panorama/CHANGELOG.md
  Integrations/Panorama/Panorama.py
  Integrations/Panorama/Panorama.yml
  TestPlaybooks/playbook-palo_alto_firewall_test_pb.yml
Labels: docs-approved

#5004 Packs changelog support
  Tests/scripts/constants.py
  Tests/scripts/hook_validations/tests/tests_data/fake_pack/Integrations/fake_changelog/fake_chanelog.py
  Tests/scripts/hook_validations/tests/tests_data/fake_pack/Integrations/fake_changelog/fake_changelog.yml
  release_notes.py
Labels: docs-approved

#5088 Fixed description for ir-get-alarm command - LogRhythm
  Integrations/integration-LogRhythm.yml
Labels: docs-approved

#5086 Whatismybrowser fix
  Integrations/WhatIsMyBrowser/CHANGELOG.md
  Integrations/WhatIsMyBrowser/WhatIsMyBrowser.py
  Integrations/WhatIsMyBrowser/WhatIsMyBrowser.yml
  TestPlaybooks/playbook-WhatIsMyBrowser-test.yml
Labels: docs-approved

#5071 Bluecat - added a description, category and fix display name
  Integrations/BluecatAddressManager/BluecatAddressManager.py
  Integrations/BluecatAddressManager/BluecatAddressManager.yml
  Integrations/BluecatAddressManager/CHANGELOG.md
Labels: docs-approved

#5092 Removed sentinel from skipped
  Tests/conf.json
Labels: docs-approved

#5097 Added Quinc integration (#3711)
  Integrations/Accessdata/Accessdata.py
  Integrations/Accessdata/Accessdata.yml
  Integrations/Accessdata/Accessdata_description.md
  Integrations/Accessdata/Accessdata_image.png
  Integrations/Accessdata/Accessdata_test.py
  Integrations/Accessdata/Pipfile
  Integrations/Accessdata/Pipfile.lock
  Integrations/Accessdata/README.md
  Integrations/Accessdata/test_data/constants.py
  Playbooks/playbook-Accessdata__Dump_memory_for_malicious_process.yml
  Scripts/AccessdataCheckProcessExistsInSnapshot/AccessdataCheckProcessExistsInSnapshot.py
  Scripts/AccessdataCheckProcessExistsInSnapshot/AccessdataCheckProcessExistsInSnapshot.yml
Labels: docs-approved

#5093 Change tags field to tags field type
  IndicatorFields/incidentfield-tagsMultiSelectType.json
  IndicatorFields/incidentfield-tagsTagsType.json
  Tests/scripts/hook_validations/structure.py
Labels: docs-approved

#5082 fixed **crowdstrike-submit-sample** on v2
  Integrations/integration-CrowdStrikeFalconSandbox.yml
  Integrations/integration-CrowdStrikeFalconSandbox_CHANGELOG.md
  TestPlaybooks/playbook-VxStream_Test.yml
  Tests/conf.json
Labels: docs-approved, release-notes-only

#4904 Microsoft Graph Mail - additional commands
  Integrations/MicrosoftGraphMail/CHANGELOG.md
  Integrations/MicrosoftGraphMail/MicrosoftGraphMail.py
  Integrations/MicrosoftGraphMail/MicrosoftGraphMail.yml
Labels: docs-approved

#5057 New transformer script - Convert all except & Prisma Cloud classifier enhancement
  Classifiers/classifier-Prisma_Cloud.json
  Classifiers/classifier-Prisma_Cloud_CHANGELOG.md
  Classifiers/classifier-prismaCloud_app.json
  Classifiers/classifier-prismaCloud_app_CHANGELOG.md
  Scripts/ConvertAllExcept/ConvertAllExcept.py
  Scripts/ConvertAllExcept/ConvertAllExcept.yml
Labels: docs-approved

#5094 Slack - Add incident labels
  Integrations/Slack/CHANGELOG.md
  Integrations/Slack/Slack.py
  Integrations/Slack/Slack_test.py
Labels: docs-approved

#5101 Delete tests for deprecated integrations
  TestPlaybooks/NonCircleTests/playbook-Get_File_Sample_By_Hash_-_Carbon_Black_Enterprise_Response_-_Test.yml
  TestPlaybooks/NonCircleTests/playbook-Get_File_Sample_By_Hash_-_Generic_Test.yml
  TestPlaybooks/NonCircleTests/playbook-Get_File_Sample_From_Hash_-_Generic_Test.yml
  TestPlaybooks/NonCircleTests/playbook-Search_Endpoints_By_Hash_-_Carbon_Black_Response_-_Test.yml
  TestPlaybooks/NonCircleTests/playbook-TestGetDuplicatesIncidentsByMl.yml
  Tests/conf.json
Labels: docs-approved

#5102 Increase devo_test_playbook timeout
  Tests/conf.json
Labels: docs-approved

#4969 Add Bandit to pkd_dev_tasks
  .hooks/pre-commit
  Beta_Integrations/PaloAlto_TrapsESM_Beta/PaloAlto_TrapsESM_Beta.py
  Tests/scripts/pkg_dev_test_tasks.py
  Tests/secrets_white_list.json
  dev-requirements-py2.txt
  dev-requirements-py3.txt
  docs/linting/README.md
Labels: docs-approved

#5105 Build shift
  Tests/conf.json
Labels: docs-approved

#5058 Exabeam - publish docs
  Integrations/Exabeam/README.md
Labels: docs-approved

#5103 MicrosoftGraphUser - fix
  Integrations/MicrosoftGraphUser/CHANGELOG.md
  Integrations/MicrosoftGraphUser/MicrosoftGraphUser.py
  TestPlaybooks/playbook-Microsoft_Graph_User_test.yml
Labels: docs-approved

#5113 entity_enrichment_generic_test removed from conf.json
  TestPlaybooks/NonCircleTests/playbook-Entity_Enrichment_-_Generic_-_Test.yml
  Tests/conf.json
Labels: docs-approved

#5114 Pep 8 and secrets fixes
  Tests/conf.json
Labels: docs-approved

#5115 Test Fix SentinelOne V2
  TestPlaybooks/playbook-SentinelOne-Beta-Test.yml
Labels: docs-approved

#5070 PAN-OS - logs update status for query with no logs matched
  Integrations/Panorama/CHANGELOG.md
  Integrations/Panorama/Panorama.py
Labels: bug, docs-approved, release-notes-only

#5111 Packagify unzipfile
  Playbooks/playbook-Get_File_Sample_By_Hash_-_Generic.yml
  Playbooks/playbook-Get_File_Sample_By_Hash_-_Generic_CHANGELOG.md
  Scripts/UnzipFile/CHANGELOG.md
  Scripts/UnzipFile/UnzipFile.py
  Scripts/UnzipFile/UnzipFile.yml
  Scripts/script-UnzipFile.yml
Labels: docs-approved

#5118 Formatting performance test fix
  TestPlaybooks/playbook-FormattingPerformance_-_Test.yml
  Tests/conf.json
Labels: docs-approved

#4608 Debugging
  README.md
  docs/Debugging/README.MD
  docs/integration_design/README.MD
  docs/integration_design/usecases/Analytics_SIEM_usecase/README.MD
  docs/integration_design/usecases/Authentication_usecase/README.MD
  docs/integration_design/usecases/Case_Management_usecase/README.MD
  docs/integration_design/usecases/Data_Enrichment_Threat_Intelligence_usecase/README.MD
  docs/integration_design/usecases/Email_Gateway_usecase/README.MD
  docs/integration_design/usecases/Endpoint_usecase/README.MD
  docs/integration_design/usecases/forensics_malware_usecase/README.MD
  docs/integration_design/usecases/network_security_IDS_IPS_usecase/README.MD
  docs/integration_design/usecases/network_security_firewall_usecase/README.MD
  docs/integration_design/usecases/vulnerability_management_usecase/README.MD
  docs/long_running_containers/README.MD
  docs/playbook_conventions/README.MD
  docs/test_playbook/README.MD
Labels: docs-approved

#5120 Added password protected zip
  TestData/pass-is-123.zip
Labels: docs-approved

#5116 Fix not killing threads ewsmailsender
  Integrations/EWSMailSender/CHANGELOG.md
  Integrations/EWSMailSender/EWSMailSender.py
  Integrations/EWSMailSender/EWSMailSender_test.py
Labels: docs-approved, release-notes-only

#4674 Playbook for searching panorama all logs
  Playbooks/playbook-PAN-OS_Query_Logs_For_Indicators.yml
  Playbooks/playbook-PAN-OS_Query_Logs_For_Indicators_CHANGELOG.md
  TestPlaybooks/playbook-PAN-OS_Query_Logs_For_Indicators_Test.yml
  Tests/conf.json
Labels: docs-approved

#5123 fixed output paths in ZipFile
  Scripts/ZipFile/CHANGELOG.md
  Scripts/ZipFile/ZipFile.py
Labels: docs-approved, release-notes-only

#4934 Adding GetEWSFolder
  Playbooks/playbook-Get_Mails_By_Folder_Pathes.yml
  Playbooks/playbook-Get_Mails_By_Folder_Pathes_CHANGELOG.md
  Scripts/GetEWSFolder/CHANGELOG.md
  Scripts/GetEWSFolder/GetEWSFolder.py
  Scripts/GetEWSFolder/GetEWSFolder.yml
  Scripts/GetEWSFolder/GetWESFolder_test.py
  TestPlaybooks/playbook-GetEWSFolder-Test.yml
  Tests/conf.json
Labels: docs-approved

#5122 Unzip fix wrong password supplied
  Scripts/UnzipFile/CHANGELOG.md
  Scripts/UnzipFile/UnzipFile.py
  TestPlaybooks/playbook-ZipFile-Test.yml
Labels: docs-approved, release-notes-only

#5128 Fix proxy param in MSGroups
  Integrations/MicrosoftGraphGroups/CHANGELOG.md
  Integrations/MicrosoftGraphGroups/MicrosoftGraphGroups.py
Labels: docs-approved

#5098 Pan os commit configuration bugfix
  Playbooks/playbook-Pan-OS_Commit_Configuration.yml
  Playbooks/playbook-Pan-OS_Commit_Configuration_CHANGELOG.md
Labels: bug, content, docs-approved

#5106 Slack - polling incremental backoff
  Integrations/Slack/Slack.py
  Integrations/Slack/Slack_test.py
Labels: docs-approved

#5050 add requests-mock package
  .hooks/pre-commit
  dev-requirements-py2.txt
  dev-requirements-py3.txt
Labels: docs-approved

#5090 change phishlabsioc to phishlabsioc_eir
  Integrations/PhishLabsIOC/CHANGELOG.md
  Integrations/PhishLabsIOC/PhishLabsIOC.yml
  Tests/secrets_white_list.json
Labels: docs-approved, release-notes-only

#5091 change phishlabs_ioc_eir to phishlabs_ioc_eir_v2
  Integrations/PhishLabsIOC_EIR/CHANGELOG.md
  Integrations/PhishLabsIOC_EIR/PhishLabsIOC_EIR.yml
Labels: docs-approved, release-notes-only

#5096 Build refactoring
  .circleci/config.yml
  Tests/instance_notifier.py
  Tests/scripts/instance_test.sh
  Utils/trigger_content_nightly_instance_tests.sh
Labels: docs-approved

#5109 Google oauth2 desktop app
  Beta_Integrations/GmailSingleUser/GmailSingleUser.py
  Beta_Integrations/GmailSingleUser/GmailSingleUser.yml
  Beta_Integrations/GmailSingleUser/GmailSingleUser_description.md
  Beta_Integrations/GmailSingleUser/GmailSingleUser_image.png
  Beta_Integrations/GmailSingleUser/GmailSingleUser_test.py
  Beta_Integrations/GmailSingleUser/Pipfile
  Beta_Integrations/GmailSingleUser/Pipfile.lock
  Classifiers/classifier-gmail-single-user.json
  Classifiers/classifier-gmail-single-user_CHANGELOG.md
  TestPlaybooks/playbook-Gmail_Single_user_-_Test.yml
  Tests/conf.json
  Tests/test_content.py
  Tests/test_integration.py
Labels: docs-approved

#5079 MS Graph Groups - publish docs - readme
  Integrations/MicrosoftGraphGroups/README.md
Labels: docs-approved

#5125 Archer - fix users specification error
  Integrations/integration-ArcherRSA.yml
  Integrations/integration-ArcherRSA_CHANGELOG.md
Labels: docs-approved

#5130 Deprecate integration
  Integrations/integration-PhishMe.yml
  Integrations/integration-PhishMe_CHANGELOG.md
Labels: docs-approved

#5129 Updating image - Cofence Intelligence
  Integrations/integration-Cofense-Intelligence.yml
  Integrations/integration-Cofense-Intelligence_CHANGELOG.md
Labels: docs-approved

#5136 Move Mcafee MAR from skipped integrations
  Tests/conf.json
Labels: docs-approved

#5019 Content version check
  .circleci/config.yml
  Scripts/CommonServerPython/CommonServerPython.py
  Tests/scripts/infrastructure_tests/content_creator_test.py
  content_creator.py
Labels: docs-approved

#5119 Fix opening threads ewsv2
  Integrations/EWSv2/CHANGELOG.md
  Integrations/EWSv2/EWSv2.py
Labels: docs-approved

#5046 Tanium V2 integration - publish docs
  Integrations/Tanium_v2/README.md
Labels: docs-approved

#5138 Slack - Add more info to oproxy headers
  Integrations/Slack/Slack.py
  Integrations/Slack/Slack.yml
Labels: docs-approved

#5078 Improve fetch incidents docs
  docs/fetching_incidents/README.md
Labels: docs-approved

#5141 Fixed Fidelis test and removed from conf.json
  TestPlaybooks/playbook-Fidelis-Test.yml
  Tests/conf.json
Labels: docs-approved

#5143 - Fixed calculate-severity test
  TestPlaybooks/playbook-Calculate_Severity_-_Critical_assets_-_Test.yml
  Tests/conf.json
Labels: docs-approved

#5149 fix tags field version
  IndicatorFields/incidentfield-tagsMultiSelectType.json
  IndicatorFields/incidentfield-tagsMultiSelectType_CHANGELOG.md
Labels: docs-approved

#5134 Deprecated Intezer v1 and fixed Intezer v2 test
  Integrations/integration-Intezer.yml
  Integrations/integration-Intezer_CHANGELOG.md
  Playbooks/playbook-Intezer_-_Analyze_Uploaded_file.yml
  Playbooks/playbook-Intezer_-_Analyze_Uploaded_file_CHANGELOG.md
  Playbooks/playbook-Intezer_-_Analyze_by_hash.yml
  Playbooks/playbook-Intezer_-_Analyze_by_hash_CHANGELOG.md
  TestPlaybooks/playbook-Intezer_Test.yml
  TestPlaybooks/playbook-Intezer_Test_v2.yml
  Tests/conf.json
Labels: docs-approved, release-notes-only

#4788 New transformer RegexExtractAll
  Scripts/RegexExtractAll/Pipfile
  Scripts/RegexExtractAll/Pipfile.lock
  Scripts/RegexExtractAll/RegexExtractAll.py
  Scripts/RegexExtractAll/RegexExtractAll.yml
  Scripts/RegexExtractAll/RegexExtractAll_test.py
  Scripts/RegexExtractAll/TestData/data.txt
  Tests/secrets_white_list.json
Labels: Contribution, docs-approved

#5152 Instance tests script - creating the client in every iteration to prevent it from dying
  Tests/instance_notifier.py
Labels: docs-approved

#4871 Mcafee Test Fail
  Tests/conf.json
  Tests/test_integration.py
Labels: docs-approved

#5154 unskip LogRhythmRest integration
  Tests/conf.json
Labels: docs-approved

#5156 unmock gmail integrations
  Tests/conf.json
Labels: docs-approved

#4999 CB Live Response - possible fix for cb-memdump command.
  Integrations/integration-Carbon_Black_Enterprise_Live_Response.yml
  Integrations/integration-Carbon_Black_Enterprise_Live_Response_CHANGELOG.md
Labels: bug, docs-approved

#5159 Stability fix for phishing tests
  TestData/Inline_malicious_url.eml
  TestPlaybooks/NonCircleTests/playbook-Extract_Indicators_From_File_-_test.yml
  TestPlaybooks/NonCircleTests/playbook-Phishing_test_-_Inline.yml
  TestPlaybooks/NonCircleTests/playbook-Phishing_test_-_attachment.yml
  TestPlaybooks/playbook-Extract_Indicators_From_File_-_Generic_v2_-_Test.yml
  TestPlaybooks/playbook-Extract_Indicators_From_File_-_Generic_v2_-_Test_4_5.yml
  TestPlaybooks/playbook-Phishing_v2_Test_-_Attachment.yml
  TestPlaybooks/playbook-Phishing_v2_Test_-_Inline.yml
Labels: docs-approved

#5022 Fixed TruSTAR test
  TestPlaybooks/playbook-TruSTAR_Test.yml
Labels: docs-approved

#5150 Fixed the upload-file issue - Archer
  Integrations/integration-ArcherRSA.yml
  Integrations/integration-ArcherRSA_CHANGELOG.md
Labels: bug, docs-approved, release-notes-only

#5142 Fixed issue JoeSecurity
  Integrations/JoeSecurity/CHANGELOG.md
  Integrations/JoeSecurity/JoeSecurity.py
Labels: bug, docs-approved, release-notes-only

#5160 Bug fix: GetTime js script
  Scripts/script-GetTime.yml
  Scripts/script-GetTime_CHANGELOG.md
  TestPlaybooks/playbook-GetTime-ObjectVsStringTest.yml
  Tests/conf.json
Labels: docs-approved

#5163 changed handle proxy spot to be after the get token operation
  Integrations/RSANetWitness_v11_1/CHANGELOG.md
  Integrations/RSANetWitness_v11_1/RSANetWitness_v11_1.py
Labels: docs-approved, release-notes-only

#5166 IntSights close-alert handle arguments prorperly
  Integrations/IntSight/CHANGELOG.md
  Integrations/IntSight/IntSight.py
  Integrations/IntSight/IntSight.yml
Labels: docs-approved

#5167 Cortex fix
  Integrations/PaloAltoNetworksCortex/CHANGELOG.md
  Integrations/PaloAltoNetworksCortex/PaloAltoNetworksCortex.py
Labels: docs-approved, release-notes-only

#5146 lr soap - fix query body
  Integrations/integration-LogRhythm.yml
  Integrations/integration-LogRhythm_CHANGELOG.md
  Tests/conf.json
Labels: docs-approved, release-notes-only

#5171 Cloaken test failure fix
  Integrations/Cloaken/CHANGELOG.md
  Integrations/Cloaken/Cloaken.py
  Tests/conf.json
Labels: docs-approved

#5042 Dedupe Content Repo
  .circleci/config.yml
  .hooks/pre-commit
  IncidentFields/incidentfield-XDR_Alert_Count.json
  IncidentFields/incidentfield-XDR_Alerts.json
  IncidentFields/incidentfield-XDR_Assigned_User_Email.json
  IncidentFields/incidentfield-XDR_Assigned_User_Pretty_Name.json
  IncidentFields/incidentfield-XDR_Description.json
  IncidentFields/incidentfield-XDR_Detection_Time.json
  IncidentFields/incidentfield-XDR_File_Artifacts.json
  IncidentFields/incidentfield-XDR_High_Severity_Alert_Count.json
  IncidentFields/incidentfield-XDR_Incident_ID.json
  IncidentFields/incidentfield-XDR_Low_Severity_Alert_Count.json
  IncidentFields/incidentfield-XDR_Medium_Severity_Alert_Count.json
  IncidentFields/incidentfield-XDR_Network_Artifacts.json
  IncidentFields/incidentfield-XDR_Notes.json
  IncidentFields/incidentfield-XDR_Resolve_Comment.json
  IncidentFields/incidentfield-XDR_Status.json
  IncidentFields/incidentfield-XDR_URL.json
  IncidentFields/incidentfield-XDR_User_Count.json
  IncidentTypes/incidenttype-Cortex_XDR_Incident.json
  Integrations/PaloAltoNetworks_XDR/CHANGELOG.md
  Integrations/PaloAltoNetworks_XDR/PaloAltoNetworks_XDR.py
  Integrations/PaloAltoNetworks_XDR/PaloAltoNetworks_XDR.yml
  Integrations/PaloAltoNetworks_XDR/PaloAltoNetworks_XDR_description.md
  Integrations/PaloAltoNetworks_XDR/PaloAltoNetworks_XDR_image.png
  Scripts/EntryWidgetNumberHostsXDR/CHANGELOG.md
  Scripts/EntryWidgetNumberHostsXDR/EntryWidgetNumberHostsXDR.py
  Scripts/EntryWidgetNumberHostsXDR/EntryWidgetNumberHostsXDR.yml
  Scripts/EntryWidgetNumberHostsXDR/Pipfile
  Scripts/EntryWidgetNumberHostsXDR/Pipfile.lock
  Scripts/EntryWidgetNumberUsersXDR/CHANGELOG.md
  Scripts/EntryWidgetNumberUsersXDR/EntryWidgetNumberUsersXDR.py
  Scripts/EntryWidgetNumberUsersXDR/EntryWidgetNumberUsersXDR.yml
  Scripts/EntryWidgetNumberUsersXDR/Pipfile
  Scripts/EntryWidgetNumberUsersXDR/Pipfile.lock
  Scripts/EntryWidgetPieAlertsXDR/CHANGELOG.md
  Scripts/EntryWidgetPieAlertsXDR/EntryWidgetPieAlertsXDR.py
  Scripts/EntryWidgetPieAlertsXDR/EntryWidgetPieAlertsXDR.yml
  Scripts/EntryWidgetPieAlertsXDR/Pipfile
  Scripts/EntryWidgetPieAlertsXDR/Pipfile.lock
  Scripts/XDRSyncScript/CHANGELOG.md
  Scripts/XDRSyncScript/Pipfile
  Scripts/XDRSyncScript/Pipfile.lock
  Scripts/XDRSyncScript/XDRSyncScript.py
  Scripts/XDRSyncScript/XDRSyncScript.yml
  Scripts/XDRSyncScript/XDRSyncScript_test.py
  Tests/scripts/copy_content_data.sh
  Tests/scripts/pkg_dev_test_tasks.py
  Tests/scripts/run_dev_tasks.sh
  Tests/scripts/run_mypy.sh
  Tests/scripts/run_parallel_pkg_dev_tasks.py
  Tests/scripts/update_id_set.py
  Tests/scripts/validate_files.py
  dev-requirements-py3.txt
  package_creator.py
  package_extractor.py
Labels: docs-approved

#5132 UnitTestFilters
  Tests/scripts/configure_tests.py
  Tests/scripts/constants.py
  Tests/scripts/update_id_set.py
Labels: docs-approved

#5055 Autofocus add ip, url, domain and file commands
  Integrations/AutofocusV2/AutofocusV2.py
  Integrations/AutofocusV2/AutofocusV2.yml
  Integrations/AutofocusV2/AutofocusV2_test.py
  Integrations/AutofocusV2/CHANGELOG.md
  TestPlaybooks/playbook-AutoFocus_V2_test.yml
  Tests/conf.json
Labels: docs-approved

#5173 Update playbook - NIST - Lessons Learned input & ID
  Playbooks/playbook-NIST_-_Lessons_Learned.yml
  Playbooks/playbook-NIST_-_Lessons_Learned_CHANGELOG.md
Labels: docs-approved

#5016 Playbook panw hunting and threat detection by indicator type
  Playbooks/playbook-PANW_-_Hunting_and_threat_detection_by_indicator_type.yml
  TestPlaybooks/playbook-PANW_-_Hunting_and_threat_detection_by_indicator_type_Test.yml
  Tests/conf.json
  Tests/secrets_white_list.json
Labels: docs-approved

#5108 CrowdStrike Falcon - RTR API
  Integrations/CrowdStrikeFalcon/CHANGELOG.md
  Integrations/CrowdStrikeFalcon/CrowdStrikeFalcon.py
  Integrations/CrowdStrikeFalcon/CrowdStrikeFalcon.yml
  Integrations/CrowdStrikeFalcon/CrowdStrikeFalcon_test.py
  Integrations/CrowdStrikeFalcon/Pipfile.lock
  Integrations/CrowdStrikeFalcon/test_data/HelloWorld.ps1
  Tests/secrets_white_list.json
Labels: docs-approved

#5172 change name phishlabs ioc from eir
  Integrations/PhishLabsIOC/CHANGELOG.md
  Integrations/PhishLabsIOC/PhishLabsIOC.yml
Labels: docs-approved

#5169 Unskipped RSA packets and logs
  TestPlaybooks/playbook-Test_RSA_PacketsAndLogs.yml
  Tests/conf.json
Labels: docs-approved

#5181 remove cortex xdr from skipped
  Tests/conf.json
Labels: docs-approved

#5161 unskipped qradar test
  Tests/conf.json
Labels: docs-approved

#5184 fixing dev-requirements-py3 demisto-sdk download
  dev-requirements-py3.txt
Labels: docs-approved

#4784 Added SecBI integration
  Integrations/SecBI/README.md
  Integrations/SecBI/SecBI.py
  Integrations/SecBI/SecBI.yml
  Integrations/SecBI/SecBI_description.md
  Integrations/SecBI/SecBI_image.png
  TestPlaybooks/playbook-SecBI-Test.yml
  Tests/conf.json
Labels: Contribution, docs-approved

#5177 Update sane doc reports automation
  Scripts/SaneDocReport/SaneDocReport.yml
Labels: bug, docs-approved

#5185 Access Investigation - NIST enhancements
  Playbooks/playbook-NIST_-_Access_Investigation_-_Generic.yml
  Playbooks/playbook-NIST_-_Access_Investigation_-_Generic_CHANGELOG.md
Labels: docs-approved

#5155 PAN-OS Bug fixed (EDL, Custom URL Category)
  Playbooks/playbook-PAN-OS_-_Block_Domain_-_External_Dynamic_List.yml
  Playbooks/playbook-PAN-OS_-_Block_Domain_-_External_Dynamic_List_CHANGELOG.md
  Playbooks/playbook-PAN-OS_-_Block_IP_and_URL_-_External_Dynamic_List.yml
  Playbooks/playbook-PAN-OS_-_Block_IP_and_URL_-_External_Dynamic_List_CHANGELOG.md
  Playbooks/playbook-PAN-OS_-_Block_URL_-_Custom_URL_Category.yml
  Playbooks/playbook-PAN-OS_-_Block_URL_-_Custom_URL_Category_CHANGELOG.md
Labels: docs-approved

#5187 Revert "CrowdStrike Falcon - RTR API (#5108)"
  Integrations/CrowdStrikeFalcon/CHANGELOG.md
  Integrations/CrowdStrikeFalcon/CrowdStrikeFalcon.py
  Integrations/CrowdStrikeFalcon/CrowdStrikeFalcon.yml
  Integrations/CrowdStrikeFalcon/CrowdStrikeFalcon_test.py
  Integrations/CrowdStrikeFalcon/Pipfile.lock
  Integrations/CrowdStrikeFalcon/test_data/HelloWorld.ps1
  Tests/secrets_white_list.json
Labels: docs-approved

#5061 Symantec blue Coat Malware Analysis - publish docs
  Beta_Integrations/SymantecBlueCoatMalwareAnalysis/README.md
  Tests/secrets_white_list.json
Labels: docs-approved

#4922 Add Updating of Content to the Build Process
  .circleci/config.yml
  Tests/configure_and_test_integration_instances.py
  Tests/lastest_server_build_scripts/run_installer_on_instance.sh
  Tests/scripts/copy_content_data.sh
  Tests/scripts/run_installer_on_instance.sh
  Tests/scripts/run_tests.sh
  Tests/test_content.py
  Tests/test_integration.py
  Tests/test_utils.py
  Tests/update_content_data.py
Labels: docs-approved

#5186 Update README.MD
  docs/context_standards/README.MD
Labels: docs-approved

#5190 Revert "Revert "CrowdStrike Falcon - RTR API (#5108)""
  Integrations/CrowdStrikeFalcon/CHANGELOG.md
  Integrations/CrowdStrikeFalcon/CrowdStrikeFalcon.py
  Integrations/CrowdStrikeFalcon/CrowdStrikeFalcon.yml
  Integrations/CrowdStrikeFalcon/CrowdStrikeFalcon_test.py
  Integrations/CrowdStrikeFalcon/Pipfile.lock
  Integrations/CrowdStrikeFalcon/test_data/HelloWorld.ps1
  Tests/secrets_white_list.json
Labels: docs-approved

#5162 New PrettyPrint Automation
  Scripts/PrettyPrint/CHANGELOG.md
  Scripts/PrettyPrint/Pipfile
  Scripts/PrettyPrint/Pipfile.lock
  Scripts/PrettyPrint/PrettyPrint.py
  Scripts/PrettyPrint/PrettyPrint.yml
  Scripts/PrettyPrint/PrettyPrint_test.py
Labels: Contribution, docs-approved

#5157 New playbook - CVE Enrichment - Generic v2
  Playbooks/playbook-CVE_Enrichment_-_Generic_v2.yml
Labels: docs-approved

#5191 Update conf.json
  Tests/conf.json
Labels: docs-approved

#5201 Configure and test fix
  Tests/configure_and_test_integration_instances.py
  Tests/scripts/run_tests.sh
Labels: docs-approved

#4776 Added new script TransformerTemplateProcessor.
  Scripts/TransformerTemplateProcessor/Pipfile
  Scripts/TransformerTemplateProcessor/Pipfile.lock
  Scripts/TransformerTemplateProcessor/TestData/SecondsToString.py
  Scripts/TransformerTemplateProcessor/TestData/context.json
  Scripts/TransformerTemplateProcessor/TestData/incident.json
  Scripts/TransformerTemplateProcessor/TransformerTemplateProcessor.py
  Scripts/TransformerTemplateProcessor/TransformerTemplateProcessor.yml
  Scripts/TransformerTemplateProcessor/TransformerTemplateProcessor_test.py
Labels: Contribution, docs-approved

#5189 Tanium v2 Fix tn-get-question-result command
  Integrations/Tanium_v2/CHANGELOG.md
  Integrations/Tanium_v2/Tanium_v2.py
  Integrations/Tanium_v2/Tanium_v2_test.py
Labels: docs-approved, release-notes-only

#5198 Qradar bug fix
  Integrations/QRadar/CHANGELOG.md
  Integrations/QRadar/QRadar.py
  TestPlaybooks/playbook-TestQradar.yml
Labels: bug, docs-approved, release-notes-only

#5183 Block IP - Generic v2 - new playbook inputs to establish PAN-OS remediation path.
  Playbooks/playbook-Block_IP_-_Generic_v2.yml
  Playbooks/playbook-Block_IP_-_Generic_v2_CHANGELOG.md
Labels: docs-approved

#4986 QRadar indicator hunting
  Playbooks/playbook-QRadar_Indicator_Hunting.yml
  TestPlaybooks/playbook-QRadar_Indicator_Hunting_Test.yml
  Tests/conf.json
  Tests/secrets_white_list.json
Labels: docs-approved

#5205 fixed slack notifier false positives
  Tests/scripts/slack_notifier.py
Labels: docs-approved

#5178 Defunct processes
  Integrations/rasterize/CHANGELOG.md
  Integrations/rasterize/rasterize.py
  Integrations/rasterize/rasterize.yml
  Integrations/rasterize/rasterize_test.py
Labels: docs-approved, release-notes-only

#4836 Phishlabs drp
  Integrations/PhishLabsIOC_DRP/PhishLabsIOC_DRP.py
  Integrations/PhishLabsIOC_DRP/PhishLabsIOC_DRP.yml
  Integrations/PhishLabsIOC_DRP/PhishLabsIOC_DRP_description.md
  Integrations/PhishLabsIOC_DRP/PhishLabsIOC_DRP_image.png
  Integrations/PhishLabsIOC_DRP/PhishLabsIOC_DRP_test.py
  Integrations/PhishLabsIOC_DRP/README.md
  Integrations/PhishLabsIOC_DRP/pytest.ini
  Integrations/PhishLabsIOC_DRP/test_data/client_methods/get_cases/begin_date_filter/output_1.json
  Integrations/PhishLabsIOC_DRP/test_data/client_methods/get_cases/begin_date_filter/output_2.json
  Integrations/PhishLabsIOC_DRP/test_data/client_methods/get_cases/begin_date_filter/output_3.json
  Integrations/PhishLabsIOC_DRP/test_data/client_methods/get_cases/combined_filters/output_1.json
  Integrations/PhishLabsIOC_DRP/test_data/client_methods/get_cases/combined_filters/output_2.json
  Integrations/PhishLabsIOC_DRP/test_data/client_methods/get_cases/combined_filters/output_3.json
  Integrations/PhishLabsIOC_DRP/test_data/client_methods/get_cases/end_date_filter/output_1.json
  Integrations/PhishLabsIOC_DRP/test_data/client_methods/get_cases/end_date_filter/output_2.json
  Integrations/PhishLabsIOC_DRP/test_data/client_methods/get_cases/end_date_filter/output_3.json
  Integrations/PhishLabsIOC_DRP/test_data/client_methods/get_cases/limit_filter/output_1.json
  Integrations/PhishLabsIOC_DRP/test_data/client_methods/get_cases/limit_filter/output_2.json
  Integrations/PhishLabsIOC_DRP/test_data/commands/fetch_incidents/output_1.json
  Integrations/PhishLabsIOC_DRP/test_data/commands/fetch_incidents/output_2.json
  Integrations/PhishLabsIOC_DRP/test_data/helper_functions/raw_response_to_context_input.json
  Integrations/PhishLabsIOC_DRP/test_data/helper_functions/raw_response_to_context_output.json
  Integrations/PhishLabsIOC_DRP/test_data/raw_response_1.json
  Integrations/PhishLabsIOC_DRP/test_data/raw_response_2.json
  Integrations/PhishLabsIOC_DRP/test_data/raw_response_3.json
  TestPlaybooks/playbook-PhishlabsIOC_DRP-Test.yml
  Tests/conf.json
  Tests/scripts/dev_envs/default_python3/Pipfile
  Tests/scripts/dev_envs/default_python3/Pipfile.lock
  Tests/secrets_white_list.json
Labels: docs-approved

#5127 [New Integration] MSGraph Calendar
  Integrations/MicrosoftGraphCalendar/MicrosoftGraphCalendar.md
  Integrations/MicrosoftGraphCalendar/MicrosoftGraphCalendar.py
  Integrations/MicrosoftGraphCalendar/MicrosoftGraphCalendar.yml
  Integrations/MicrosoftGraphCalendar/MicrosoftGraphCalendar_description.md
  Integrations/MicrosoftGraphCalendar/MicrosoftGraphCalendar_image.png
  Integrations/MicrosoftGraphCalendar/MicrosoftGraphCalendar_test.py
  TestPlaybooks/playbook-Microsoft-Graph-Calendar-Test.yml
  Tests/conf.json
Labels: docs-approved

#5176 making the rule position in PAN-OS create/edit rule non mandatory
  Playbooks/playbook-PAN-OS_-_Create_Or_Edit_Rule.yml
  Playbooks/playbook-PAN-OS_-_Create_Or_Edit_Rule_CHANGELOG.md
  Playbooks/playbook-PAN-OS_DAG_Configuration.yml
  Playbooks/playbook-PAN-OS_DAG_Configuration_CHANGELOG.md
  Playbooks/playbook-PAN-OS_EDL_Setup.yml
  Playbooks/playbook-PAN-OS_EDL_Setup_CHANGELOG.md
Labels: content, docs-approved

#5200 added missing outputs to get-user command - Gmail
  Integrations/Gmail/Gmail.yml
Labels: bug, docs-approved

#5213 Build updating fixes
  .circleci/config.yml
  Tests/configure_and_test_integration_instances.py
  Tests/scripts/copy_content_data.sh
  Tests/scripts/run_tests.sh
Labels: docs-approved

#5212 fix indentation
  Tests/conf.json
Labels: docs-approved

#5180 PhishLabs EIR - Fixes after demo
  Integrations/PhishLabsIOC_EIR/CHANGELOG.md
  Integrations/PhishLabsIOC_EIR/PhishLabsIOC_EIR.py
  Integrations/PhishLabsIOC_EIR/PhishLabsIOC_EIR.yml
  Integrations/PhishLabsIOC_EIR/PhishLabsIOC_EIR_description.md
  Integrations/PhishLabsIOC_EIR/README.md
  Tests/secrets_white_list.json
Labels: docs-approved, release-notes-only

#5175 graph permissions
  Integrations/MicrosoftGraphUser/CHANGELOG.md
  Integrations/MicrosoftGraphUser/MicrosoftGraphUser.yml
Labels: docs-approved

#5144 fix Cofense Test func and fetch and outputs in yml
  Integrations/CofenseTriage/CHANGELOG.md
  Integrations/CofenseTriage/CofenseTriage.py
  Integrations/CofenseTriage/CofenseTriage.yml
Labels: docs-approved

#5139 McAfee DXL
  Integrations/McAfee_DXL/McAfee_DXL.py
  Integrations/McAfee_DXL/McAfee_DXL.yml
  Integrations/McAfee_DXL/McAfee_DXL_description.md
  Integrations/McAfee_DXL/McAfee_DXL_image.png
  Integrations/McAfee_DXL/McAfee_DXL_test.py
  TestPlaybooks/playbook-McAfee_DXL_-_Test.yml
  Tests/conf.json
Labels: docs-approved

#5014 Create integration-Flashpoint.yml
  Integrations/Flashpoint/Flashpoint.py
  Integrations/Flashpoint/Flashpoint.yml
  Integrations/Flashpoint/Flashpoint_description.md
  Integrations/Flashpoint/Flashpoint_image.png
  Integrations/Flashpoint/Flashpoint_test.py
  Integrations/Flashpoint/Pipfile
  Integrations/Flashpoint/Pipfile.lock
  Integrations/Flashpoint/README.md
  Integrations/Flashpoint/TestData/domain_ec.json
  Integrations/Flashpoint/TestData/domain_response.json
  Integrations/Flashpoint/TestData/email_ec.json
  Integrations/Flashpoint/TestData/email_response.json
  Integrations/Flashpoint/TestData/event_search_by_id_ec.json
  Integrations/Flashpoint/TestData/event_search_by_id_response.json
  Integrations/Flashpoint/TestData/events_search_response.json
  Integrations/Flashpoint/TestData/file_ec.json
  Integrations/Flashpoint/TestData/file_response.json
  Integrations/Flashpoint/TestData/filename_ec.json
  Integrations/Flashpoint/TestData/filename_response.json
  Integrations/Flashpoint/TestData/forum_post_search_by_id_ec.json
  Integrations/Flashpoint/TestData/forum_post_search_by_id_response.json
  Integrations/Flashpoint/TestData/forum_post_search_response.json
  Integrations/Flashpoint/TestData/forum_room_search_by_id_ec.json
  Integrations/Flashpoint/TestData/forum_room_search_by_id_response.json
  Integrations/Flashpoint/TestData/forum_search_by_id_ec.json
  Integrations/Flashpoint/TestData/forum_search_by_id_response.json
  Integrations/Flashpoint/TestData/forum_site_search_response.json
  Integrations/Flashpoint/TestData/forum_user_search_by_id_ec.json
  Integrations/Flashpoint/TestData/forum_user_search_by_id_response.json
  Integrations/Flashpoint/TestData/ip_ec.json
  Integrations/Flashpoint/TestData/ip_response.json
  Integrations/Flashpoint/TestData/report_search_by_id_ec.json
  Integrations/Flashpoint/TestData/report_search_by_id_response.json
  Integrations/Flashpoint/TestData/report_search_by_keyword_response.json
  Integrations/Flashpoint/TestData/url_ec.json
  Integrations/Flashpoint/TestData/url_response.json
  TestPlaybooks/playbook-Flashpoint_event_Test.yml
  TestPlaybooks/playbook-Flashpoint_forum_Test.yml
  TestPlaybooks/playbook-Flashpoint_report_Test.yml
  TestPlaybooks/playbook-Flashpoint_reputation_Test.yml
  Tests/conf.json
  Tests/secrets_white_list.json
Labels: Contribution, docs-approved

#5217 unzipped test_content not in artifacts folder
  .circleci/config.yml
Labels: docs-approved

#5215 Update CHANGELOG.md
  Integrations/Active_Directory_Query/Active_Directory_Query.py
  Integrations/Active_Directory_Query/CHANGELOG.md
Labels: Contribution, docs-approved, release-notes-only

#5052 Infoblox
  Integrations/Infoblox/Infoblox.py
  Integrations/Infoblox/Infoblox.yml
  Integrations/Infoblox/Infoblox_description.md
  Integrations/Infoblox/Infoblox_image.png
  Integrations/Infoblox/Infoblox_test.py
  Integrations/Infoblox/Pipfile
  Integrations/Infoblox/Pipfile.lock
  TestPlaybooks/playbook-Infoblox_Test.yml
  Tests/conf.json
  Tests/secrets_white_list.json
Labels: docs-approved

#5192 Akamai WAF SIEM Integration
  Integrations/Akamai_SIEM/Akamai_SIEM.py
  Integrations/Akamai_SIEM/Akamai_SIEM.yml
  Integrations/Akamai_SIEM/Akamai_SIEM_description.md
  Integrations/Akamai_SIEM/Akamai_SIEM_image.png
  Integrations/Akamai_SIEM/Akamai_SIEM_test.py
  Integrations/Akamai_SIEM/README.md
  Integrations/Akamai_SIEM/pytest.ini
  Integrations/Akamai_SIEM/test_Akamai_SIEM/TestCommandsFunctions/expected_fetch.json
  Integrations/Akamai_SIEM/test_Akamai_SIEM/TestCommandsFunctions/get_events_expected_ec_2.json
  Integrations/Akamai_SIEM/test_Akamai_SIEM/TestCommandsFunctions/sec_events.txt
  Integrations/Akamai_SIEM/test_Akamai_SIEM/TestCommandsFunctions/sec_events_empty.txt
  TestPlaybooks/playbook-Akamai_WAF_SIEM-Test.yml
  Tests/conf.json
  Tests/secrets_white_list.json
Labels: docs-approved
