Repository demisto/content, pull requests merged in 2019-11, with the labels that each got.

#4729 Build shift
  Tests/conf.json
Labels: docs-approved

#4741 updated integration category
  Integrations/GoogleDocs/CHANGELOG.md
  Integrations/GoogleDocs/GoogleDocs.yml
Labels: docs-approved

#4742 Updated GA build number to latest
  Tests/ami_builds.json
Labels: docs-approved

#4747 Build shift
  Tests/conf.json
Labels: docs-approved

#3804 CopyContentToField support list value
  Scripts/CopyContextToField/CHANGELOG.md
  Scripts/CopyContextToField/CopyContextToField.py
  Scripts/CopyContextToField/CopyContextToField.yml
  Scripts/script-CopyContextToField.yml
Labels: docs-approved

#4755 Check if image is not default image - Hooks
  Tests/scripts/constants.py
  Tests/scripts/hook_validations/image.py
  Tests/scripts/hook_validations/tests/image_test.py
  Tests/scripts/hook_validations/tests/tests_data/default_image.png
  Tests/scripts/hook_validations/tests/tests_data/fake_integration.yml
  Tests/secrets_white_list.json
Labels: docs-approved

#4753 Circle build: use virtual env
  .circleci/build-requirements.txt
  .circleci/config.yml
  Integrations/Active_Directory_Query/Active_Directory_Query.py
  Integrations/Active_Directory_Query/CHANGELOG.md
  Integrations/Exchange2016_Compliance/CHANGELOG.md
  Integrations/Exchange2016_Compliance/Exchange2016_Compliance.py
  Integrations/Exchange2016_Compliance/Exchange2016_Compliance.yml
  Integrations/Looker/CHANGELOG.md
  Integrations/Looker/Looker.py
  Integrations/Netcraft/CHANGELOG.md
  Integrations/Netcraft/Netcraft.py
  dev-requirements-py2.txt
  dev-requirements-py3.txt
Labels: docs-approved

#4619 Change Script from Python 2.7 to Python3 to support ASCII Characters
  Scripts/RegexGroups/CHANGELOG.md
  Scripts/RegexGroups/Pipfile
  Scripts/RegexGroups/Pipfile.lock
  Scripts/RegexGroups/RegexGroups.py
  Scripts/RegexGroups/RegexGroups.yml
  Scripts/script-RegexGroups.yml
Labels: Contribution, docs-approved

#4381 EWSv2
  Integrations/EWSv2/CHANGELOG.md
  Integrations/EWSv2/EWSv2.py
Labels: docs-approved

#4725 Cortex XDR content pack
  Packs/CortexXDR/.pack-ignore
  Packs/CortexXDR/.secrets-ignore
  Packs/CortexXDR/CHANGELOG.md
  Packs/CortexXDR/IncidentFields/XDR_Alert_Count.json
  Packs/CortexXDR/IncidentFields/XDR_Alerts.json
  Packs/CortexXDR/IncidentFields/XDR_Assigned_User_Email.json
  Packs/CortexXDR/IncidentFields/XDR_Assigned_User_Pretty_Name.json
  Packs/CortexXDR/IncidentFields/XDR_Description.json
  Packs/CortexXDR/IncidentFields/XDR_Detection_Time.json
  Packs/CortexXDR/IncidentFields/XDR_File_Artifacts.json
  Packs/CortexXDR/IncidentFields/XDR_High_Severity_Alert_Count.json
  Packs/CortexXDR/IncidentFields/XDR_Incident_ID.json
  Packs/CortexXDR/IncidentFields/XDR_Low_Severity_Alert_Count.json
  Packs/CortexXDR/IncidentFields/XDR_Medium_Severity_Alert_Count.json
  Packs/CortexXDR/IncidentFields/XDR_Network_Artifacts.json
  Packs/CortexXDR/IncidentFields/XDR_Notes.json
  Packs/CortexXDR/IncidentFields/XDR_Resolve_Comment.json
  Packs/CortexXDR/IncidentFields/XDR_Status.json
  Packs/CortexXDR/IncidentFields/XDR_URL.json
  Packs/CortexXDR/IncidentFields/XDR_User_Count.json
  Packs/CortexXDR/IncidentTypes/Cortex_XDR_Incident.json
  Packs/CortexXDR/Integrations/PaloAltoNetworks_XDR/PaloAltoNetworks_XDR.py
  Packs/CortexXDR/Integrations/PaloAltoNetworks_XDR/PaloAltoNetworks_XDR.yml
  Packs/CortexXDR/Integrations/PaloAltoNetworks_XDR/PaloAltoNetworks_XDR_description.md
  Packs/CortexXDR/Integrations/PaloAltoNetworks_XDR/PaloAltoNetworks_XDR_image.png
  Packs/CortexXDR/Layouts/details-Cortex_XDR_Incident.json
  Packs/CortexXDR/Playbooks/Cortex_XDR_Incident_Handling.yml
  Packs/CortexXDR/Playbooks/PaloAltoNetworks_Cortex_XDR_Incident_Sync.yml
  Packs/CortexXDR/README.md
  Packs/CortexXDR/Scripts/EntryWidgetNumberHostsXDR/EntryWidgetNumberHostsXDR.py
  Packs/CortexXDR/Scripts/EntryWidgetNumberHostsXDR/EntryWidgetNumberHostsXDR.yml
  Packs/CortexXDR/Scripts/EntryWidgetNumberHostsXDR/Pipfile
  Packs/CortexXDR/Scripts/EntryWidgetNumberHostsXDR/Pipfile.lock
  Packs/CortexXDR/Scripts/EntryWidgetNumberUsersXDR/EntryWidgetNumberUsersXDR.py
  Packs/CortexXDR/Scripts/EntryWidgetNumberUsersXDR/EntryWidgetNumberUsersXDR.yml
  Packs/CortexXDR/Scripts/EntryWidgetNumberUsersXDR/Pipfile
  Packs/CortexXDR/Scripts/EntryWidgetNumberUsersXDR/Pipfile.lock
  Packs/CortexXDR/Scripts/EntryWidgetPieAlertsXDR/EntryWidgetPieAlertsXDR.py
  Packs/CortexXDR/Scripts/EntryWidgetPieAlertsXDR/EntryWidgetPieAlertsXDR.yml
  Packs/CortexXDR/Scripts/EntryWidgetPieAlertsXDR/Pipfile
  Packs/CortexXDR/Scripts/EntryWidgetPieAlertsXDR/Pipfile.lock
  Packs/CortexXDR/Scripts/XDRSyncScript/Pipfile
  Packs/CortexXDR/Scripts/XDRSyncScript/Pipfile.lock
  Packs/CortexXDR/Scripts/XDRSyncScript/XDRSyncScript.py
  Packs/CortexXDR/Scripts/XDRSyncScript/XDRSyncScript.yml
  Packs/CortexXDR/Scripts/XDRSyncScript/XDRSyncScript_test.py
  Packs/CortexXDR/TestPlaybooks/Cortex_XDR.yml
  Packs/CortexXDR/pack-metadata.json
Labels: docs-approved

#4756 Build shift
  Tests/conf.json
Labels: docs-approved

#4765 fixed test SentinelOne
  TestPlaybooks/playbook-SentinelOne-Beta-Test.yml
Labels: docs-approved

#4762 fix default image validation
  Tests/scripts/hook_validations/image.py
Labels: docs-approved

#4767 RSA test fix
  TestPlaybooks/playbook-Test_RSA_PacketsAndLogs.yml
  Tests/conf.json
Labels: docs-approved

#4760 Change Script from Python 2.7 to Python3 to support ASCII Characters
  Scripts/RegexGroups/CHANGELOG.md
  Scripts/RegexGroups/Pipfile
  Scripts/RegexGroups/Pipfile.lock
  Scripts/RegexGroups/RegexGroups.py
  Scripts/RegexGroups/RegexGroups.yml
  Scripts/script-RegexGroups.yml
Labels: docs-approved

#4758 fix links in content documentation pages
  CONTRIBUTING.md
  README.md
  docs/README.md
  docs/code_conventions/README.MD
  docs/dbot/README.md
  docs/genericpolling/README.md
  docs/getting_started/README.MD
  docs/package_directory_structure/README.MD
Labels: docs-approved

#4234 Added function read chart data in ArcSight Logger Integration (#3246)
  Integrations/integration-ArcSightLogger.yml
  Integrations/integration-ArcSightLogger_CHANGELOG.md
Labels: docs-approved

#4770 unskip ePO
  Tests/conf.json
Labels: docs-approved

#4707 CommonServerPython IntegrationLogger auto replace fix
  Scripts/CommonServerPython/CHANGELOG.md
  Scripts/CommonServerPython/CommonServerPython.py
  Scripts/CommonServerPython/CommonServerPython_test.py
Labels: docs-approved, release-notes-only

#4682 Delete context auto option
  Scripts/script-DeleteConext.yml
  Scripts/script-DeleteConext_CHANGELOG.md
  TestPlaybooks/playbook-DeleteContext-auto-subplaybook-test.yml
  TestPlaybooks/playbook-DeleteContext-auto-test.yml
  Tests/conf.json
  Tests/scripts/configure_tests.py
Labels: docs-approved

#4766 Build shift
  TestPlaybooks/playbook-SentinelOne-Beta-Test.yml
  Tests/conf.json
Labels: docs-approved

#4777 Retry for unit testing when docker communication fails
  Tests/scripts/pkg_dev_test_tasks.py
Labels: docs-approved

#3677 Fix typo in SendMessageToOnlineUsers Script
  Scripts/script-SendMessageToOnlineUsers.yml
  Scripts/script-SendMessageToOnlineUsers_CHANGELOG.md
Labels: docs-approved

#4521 Netskope - Ability to fetch alerts as incidents
  Integrations/integration-Netskope.yml
  Integrations/integration-Netskope_CHANGELOG.md
Labels: docs-approved

#4748 Spearmin10 edl management quote args scp execute base
  Integrations/PaloAltoNetworks_PAN_OS_EDL_Management/CHANGELOG.md
  Integrations/PaloAltoNetworks_PAN_OS_EDL_Management/PaloAltoNetworks_PAN_OS_EDL_Management.py
  Integrations/PaloAltoNetworks_PAN_OS_EDL_Management/PaloAltoNetworks_PAN_OS_EDL_Management.yml
Labels: Contribution, docs-approved, release-notes-only

#4749 Proofpoint TAP V2 docs
  Integrations/ProofpointTAP_v2/readme.md
Labels: docs-approved

#4773 Cortex new
  Integrations/PaloAltoNetworksCortex/CHANGELOG.md
  Integrations/PaloAltoNetworksCortex/PaloAltoNetworksCortex.py
Labels: docs-approved, release-notes-only

#4659 Elasticsearch v2 timestamp support
  Integrations/Elasticsearch_v2/CHANGELOG.md
  Integrations/Elasticsearch_v2/Elasticsearch_v2.py
  Integrations/Elasticsearch_v2/Elasticsearch_v2.yml
  Integrations/Elasticsearch_v2/Elasticsearch_v2_description.md
  Integrations/Elasticsearch_v2/Elasticsearch_v2_test.py
  Tests/secrets_white_list.json
Labels: docs-approved

#4554 HTMLDocumenation commands fix
  Scripts/HTMLDocsAutomation/CHANGELOG.md
  Scripts/HTMLDocsAutomation/HTMLDocsAutomation.py
  Scripts/HTMLDocsAutomation/HTMLDocsAutomation_test.py
Labels: docs-approved

#4781 Skipped carbonblack-v2
  Tests/conf.json
Labels: docs-approved

#4782 Elasticsearch v2 fixchangelog format
  Integrations/Elasticsearch_v2/CHANGELOG.md
Labels: docs-approved

#4574 Bug fixes for set_asset_tag command and adding ancestor_list parameter to parent-child process lineage commands
  Integrations/Uptycs/CHANGELOG.md
  Integrations/Uptycs/Uptycs.py
  Integrations/Uptycs/Uptycs.yml
Labels: Contribution, docs-approved

#4786 remove logrhythm tests from skipped
  Tests/conf.json
Labels: docs-approved

#4522 ProtectWise - Fixed lastRun to store last event timestamp
  Integrations/integration-ProtectWise.yml
  Integrations/integration-ProtectWise_CHANGELOG.md
Labels: docs-approved

#4759 Validate_files should run on python2
  Tests/scripts/update_id_set.py
Labels: docs-approved

#4761 Update sane doc reports automation
  Scripts/SaneDocReport/CHANGELOG.md
  Scripts/SaneDocReport/SaneDocReport.yml
Labels: bug, docs-approved, release-notes-only

#4170 Alienvault otx v2
  Integrations/AlienVault_OTX_v2/AlienVault_OTX_v2.py
  Integrations/AlienVault_OTX_v2/AlienVault_OTX_v2.yml
  Integrations/AlienVault_OTX_v2/AlienVault_OTX_v2_description.md
  Integrations/AlienVault_OTX_v2/AlienVault_OTX_v2_image.png
  Integrations/AlienVault_OTX_v2/AlienVault_OTX_v2_test.py
  Integrations/AlienVault_OTX_v2/README.md
  TestPlaybooks/playbook-Alienvault_OTX_v2-test.yml
  Tests/conf.json
  Tests/secrets_white_list.json
Labels: docs-approved

#4789 RedCanary fix index out of range
  Integrations/RedCanary/CHANGELOG.md
  Integrations/RedCanary/RedCanary.py
  Integrations/RedCanary/RedCanary.yml
Labels: docs-approved, release-notes-only

#4516 Add unittests configuration for test filter
  Tests/scripts/configure_tests.py
  Tests/scripts/update_id_set.py
Labels: docs-approved

#4715 fixed problem when one-object only STIX2 file supplied
  Scripts/StixParser/CHANGELOG.md
  Scripts/StixParser/StixParser.py
  Scripts/StixParser/StixParser_test.py
  Scripts/StixParser/TestData/stix2_single.json
Labels: docs-approved, release-notes-only

#4733 Archer - Improved errors and added debug logs
  Integrations/integration-ArcherRSA.yml
  Integrations/integration-ArcherRSA_CHANGELOG.md
Labels: docs-approved, release-notes-only

#4606 Vectra v2
  Integrations/Vectra_v2/CHANGELOG.md
  Integrations/Vectra_v2/README.md
  Integrations/Vectra_v2/Vectra_v2.py
  Integrations/Vectra_v2/Vectra_v2.yml
  Integrations/Vectra_v2/Vectra_v2_description.md
  Integrations/Vectra_v2/Vectra_v2_image.png
  Integrations/Vectra_v2/Vectra_v2_test.py
Labels: docs-approved

#4798 Added tests results to artifacts
  .circleci/config.yml
Labels: docs-approved

#4698 Added description key to tag details
  Integrations/AutofocusV2/AutofocusV2.py
  Integrations/AutofocusV2/AutofocusV2.yml
  Integrations/AutofocusV2/CHANGELOG.md
  TestPlaybooks/playbook-AutoFocus_V2_test.yml
Labels: docs-approved, release-notes-only

#4476 RSA Netwitness Bug Fixes
  Integrations/RSANetWitness_v11_1/CHANGELOG.md
  Integrations/RSANetWitness_v11_1/RSANetWitness_v11_1.py
  Integrations/RSANetWitness_v11_1/RSANetWitness_v11_1.yml
Labels: docs-approved, release-notes-only

#4713 TruSTAR - no license
  Tests/conf.json
Labels: docs-approved

#4792 Uptycs - format changelog
  Integrations/Uptycs/CHANGELOG.md
Labels: docs-approved

#4445 Domain Tools Iris - First Release
  Integrations/DomainTools_Iris/DomainTools_Iris.py
  Integrations/DomainTools_Iris/DomainTools_Iris.yml
  Integrations/DomainTools_Iris/DomainTools_Iris_description.md
  Integrations/DomainTools_Iris/DomainTools_Iris_image.png
  Integrations/DomainTools_Iris/README.md
  Playbooks/playbook-Indicator_Pivoting-DomainTools_Iris.yml
  TestPlaybooks/playbook-DomainTools_Iris_Test.yml
  Tests/conf.json
Labels: Contribution, docs-approved

#4714 Carbon Black cb-binary-get fix
  Integrations/integration-Carbon_Black_Enterprise_Response.yml
  Integrations/integration-Carbon_Black_Enterprise_Response_CHANGELOG.md
  TestPlaybooks/playbook-Carbon_Black_Response_Test.yml
Labels: docs-approved, release-notes-only

#4686 Kenna integration - search-fixes command inputs and outputs improvement
  Integrations/integration-Kenna.yml
  Integrations/integration-Kenna_CHANGELOG.md
  TestPlaybooks/playbook-Kenna_Test.yml
  Tests/conf.json
Labels: docs-approved, release-notes-only

#3675 Added scanner name to qualys-pc-scan-launch & qualys-vm-scan-launch
  Integrations/integration-qualys.yml
  Releases/LatestRelease/integration-qualys.md
  Releases/LatestRelease/playbook-Vulnerability_Management__-_Qualys_(Job).md
Labels: docs-approved

#4802 Revert "fixed problem when one-object only STIX2 file supplied"
  Scripts/StixParser/CHANGELOG.md
  Scripts/StixParser/StixParser.py
  Scripts/StixParser/StixParser_test.py
  Scripts/StixParser/TestData/stix2_single.json
Labels: docs-approved

#4661 new prisma IAM remediation runbooks
  Playbooks/playbook-Prisma_Cloud_Remediation_-_AWS_IAM_Password_Policy_Allows_Password_Reuse.yml
  Playbooks/playbook-Prisma_Cloud_Remediation_-_AWS_IAM_Password_Policy_Does_Not_Expire_In_90_Days.yml
  Playbooks/playbook-Prisma_Cloud_Remediation_-_AWS_IAM_Password_Policy_Does_Not_Have_A_Lowercase_Character.yml
  Playbooks/playbook-Prisma_Cloud_Remediation_-_AWS_IAM_Password_Policy_Does_Not_Have_A_Minimum_Of_14_Characters.yml
  Playbooks/playbook-Prisma_Cloud_Remediation_-_AWS_IAM_Password_Policy_Does_Not_Have_A_Number.yml
  Playbooks/playbook-Prisma_Cloud_Remediation_-_AWS_IAM_Password_Policy_Does_Not_Have_A_Symbol.yml
  Playbooks/playbook-Prisma_Cloud_Remediation_-_AWS_IAM_Password_Policy_Does_Not_Have_An_Uppercase_Character.yml
  Playbooks/playbook-Prisma_Cloud_Remediation_-_AWS_IAM_Password_Policy_Does_Not_Have_Password_Expiration_Period.yml
  Playbooks/playbook-Prisma_Cloud_Remediation_-_AWS_IAM_Password_Policy_Is_Not_Secure.yml
Labels: Contribution, docs-approved

#4684 PAN-OS - move-rule improved descs
  Integrations/Panorama/CHANGELOG.md
  Integrations/Panorama/Panorama.yml
Labels: docs-approved, release-notes-only

#4485 ArcSight Logger:
  Integrations/integration-ArcSightLogger.yml
  Integrations/integration-ArcSightLogger_CHANGELOG.md
Labels: docs-approved

#4731 'px' suffix
  Integrations/rasterize/CHANGELOG.md
  Integrations/rasterize/rasterize.py
Labels: docs-approved, release-notes-only

#4706 Support newer smtplib (one without exposed stderr)
  Integrations/MailSenderNew/CHANGELOG.md
  Integrations/MailSenderNew/MailSenderNew.py
Labels: Contribution, docs-approved, release-notes-only

#4800 Archer - fix details concat bug + offset bug
  Integrations/integration-ArcherRSA.yml
  Integrations/integration-ArcherRSA_CHANGELOG.md
Labels: docs-approved, release-notes-only

#4579 SecurityAdvisor1.0
  Integrations/SecurityAdvisor/CHANGELOG.md
  Integrations/SecurityAdvisor/Pipfile
  Integrations/SecurityAdvisor/Pipfile.lock
  Integrations/SecurityAdvisor/README.md
  Integrations/SecurityAdvisor/SecurityAdvisor.py
  Integrations/SecurityAdvisor/SecurityAdvisor.yml
  Integrations/SecurityAdvisor/SecurityAdvisor_description.md
  Integrations/SecurityAdvisor/SecurityAdvisor_image.png
  Integrations/SecurityAdvisor/SecurityAdvisor_test.py
  TestPlaybooks/playbook-SecurityAdvisor-Test.yml
  Tests/conf.json
  Tests/secrets_white_list.json
  requirements.txt
Labels: Contribution, docs-approved

#4672 [Enhancement] Palo Alto Networks Cortex - Documentation
  Integrations/PaloAltoNetworksCortex/README.md
  Tests/secrets_white_list.json
Labels: docs-approved

#4708 Regex and Formatting - url domain forwardslash
  Misc/reputation-domain.json
  Misc/reputation-domain_CHANGELOG.md
  Misc/reputation-url.json
  Misc/reputation-url_CHANGELOG.md
  Misc/reputations.json
  Misc/reputations_CHANGELOG.md
  Scripts/ExtractDomainFromUrlFormat/CHANGELOG.md
  Scripts/ExtractDomainFromUrlFormat/ExtractDomainFromUrlFormat.py
  Scripts/ExtractDomainFromUrlFormat/ExtractDomainFromUrlFormat_test.py
  Scripts/script-UnEscapeURLs.yml
  Scripts/script-UnEscapeURLs_CHANGELOG.md
  TestPlaybooks/playbook-UnEscapeURLs-Test.yml
  TestPlaybooks/playbook-reputation.json-Test.yml
  Tests/scripts/configure_tests.py
  Tests/secrets_white_list.json
Labels: docs-approved, release-notes-only

#4814 unskip intsights test
  Tests/conf.json
Labels: docs-approved

#4675 guid change by by readable format
  Scripts/PhishLabsPopulateIndicators/CHANGELOG.md
  Scripts/PhishLabsPopulateIndicators/PhishLabsPopulateIndicators.yml
  Scripts/script-ChangeRemediationSLAOnSevChange.yml
  Scripts/script-ChangeRemediationSLAOnSevChange_CHANGELOG.md
  Scripts/script-CheckpointFWCreateBackup.yml
  Scripts/script-CheckpointFWCreateBackup_CHANGELOG.md
  Scripts/script-CveReputation.yml
  Scripts/script-CveReputation_CHANGELOG.md
  Scripts/script-DisplayHTML.yml
  Scripts/script-DisplayHTML_CHANGELOG.md
  Scripts/script-IPToHost.yml
  Scripts/script-IPToHost_CHANGELOG.md
  Scripts/script-NetwitnessQuery.yml
  Scripts/script-NetwitnessQuery_CHNAGELOG.md
  Scripts/script-NetwitnessSAListIncidents.yml
  Scripts/script-NetwitnessSAListIncidents_CHANGELOG.md
  Scripts/script-NetwitnessSearch.yml
  Scripts/script-NetwitnessSearch_CHANGELOG.md
  Scripts/script-NexposeCreateIncidentsFromAssets.yml
  Scripts/script-NexposeCreateIncidentsFromAssets_CHANGELOG.md
  Scripts/script-SetByIncidentId.yml
  Scripts/script-SetByIncidentId_CHANGELOG.md
  Scripts/script-SetTime.yml
  Scripts/script-SetTime_CHANGELOG.md
  Scripts/script-StopTimeToAssignOnOwnerChange.yml
  Scripts/script-StopTimeToAssignOnOwnerChange_CHANGELOG.md
Labels: docs-approved

#4811 Palo Alto Networks test PB fail - Fix
  TestPlaybooks/playbook-Palo_Alto_Networks_Cortex_Test.yml
  Tests/conf.json
Labels: docs-approved

#4818 Revert "new prisma IAM remediation runbooks"
  Playbooks/playbook-Prisma_Cloud_Remediation_-_AWS_IAM_Password_Policy_Allows_Password_Reuse.yml
  Playbooks/playbook-Prisma_Cloud_Remediation_-_AWS_IAM_Password_Policy_Does_Not_Expire_In_90_Days.yml
  Playbooks/playbook-Prisma_Cloud_Remediation_-_AWS_IAM_Password_Policy_Does_Not_Have_A_Lowercase_Character.yml
  Playbooks/playbook-Prisma_Cloud_Remediation_-_AWS_IAM_Password_Policy_Does_Not_Have_A_Minimum_Of_14_Characters.yml
  Playbooks/playbook-Prisma_Cloud_Remediation_-_AWS_IAM_Password_Policy_Does_Not_Have_A_Number.yml
  Playbooks/playbook-Prisma_Cloud_Remediation_-_AWS_IAM_Password_Policy_Does_Not_Have_A_Symbol.yml
  Playbooks/playbook-Prisma_Cloud_Remediation_-_AWS_IAM_Password_Policy_Does_Not_Have_An_Uppercase_Character.yml
  Playbooks/playbook-Prisma_Cloud_Remediation_-_AWS_IAM_Password_Policy_Does_Not_Have_Password_Expiration_Period.yml
  Playbooks/playbook-Prisma_Cloud_Remediation_-_AWS_IAM_Password_Policy_Is_Not_Secure.yml
Labels: docs-approved

#4820 SumoLogic - unskip
  Tests/conf.json
Labels: docs-approved

#4778 UrlScan.io fixed typo
  Integrations/UrlScan/CHANGELOG.md
  Integrations/UrlScan/UrlScan.py
  Integrations/UrlScan/UrlScan.yml
  Integrations/UrlScan/UrlScan_Image.png
  Integrations/UrlScan/UrlScan_description.md
Labels: docs-approved, release-notes-only

#4819 Added a store artifact step straight after test server
  .circleci/config.yml
Labels: docs-approved

#4829 VxStream test PB fails - Fix
  TestPlaybooks/playbook-VxStream_Test.yml
  Tests/conf.json
  Tests/secrets_white_list.json
Labels: docs-approved

#4764 Check that base branch isn't master in external PR
  .circleci/build-requirements.txt
  .circleci/config.yml
  Tests/scripts/constants.py
  Tests/scripts/infrastructure_tests/verify_base_branch_for_contribution_test.py
  Tests/scripts/verify_base_branch_for_contribution.py
Labels: docs-approved

#4840 Fix MailListener-POP3 - Test
  TestPlaybooks/playbook-MailListener-POP3_-_Test.yml
  Tests/conf.json
Labels: docs-approved

#4837 unskip Intezer Testing
  Integrations/integration-Intezer.yml
  Integrations/integration-Intezer_CHANGELOG.md
  Tests/conf.json
Labels: docs-approved

#4827 Add results to artifacts
  .circleci/config.yml
Labels: docs-approved

#4843 Revert "Regex and Formatting - url domain forwardslash"
  Misc/reputation-domain.json
  Misc/reputation-domain_CHANGELOG.md
  Misc/reputation-url.json
  Misc/reputation-url_CHANGELOG.md
  Misc/reputations.json
  Misc/reputations_CHANGELOG.md
  Scripts/ExtractDomainFromUrlFormat/CHANGELOG.md
  Scripts/ExtractDomainFromUrlFormat/ExtractDomainFromUrlFormat.py
  Scripts/ExtractDomainFromUrlFormat/ExtractDomainFromUrlFormat_test.py
  Scripts/script-UnEscapeURLs.yml
  Scripts/script-UnEscapeURLs_CHANGELOG.md
  TestPlaybooks/playbook-UnEscapeURLs-Test.yml
  TestPlaybooks/playbook-reputation.json-Test.yml
  Tests/scripts/configure_tests.py
  Tests/secrets_white_list.json
Labels: docs-approved

#4830 Fix cloaken
  TestPlaybooks/playbook-Cloaken-Test.yml
  Tests/conf.json
Labels: docs-approved

#4673 Change Created Credential Names to be Unique
  Integrations/BeyondTrust_Password_Safe/BeyondTrust_Password_Safe.py
  Integrations/BeyondTrust_Password_Safe/BeyondTrust_Password_Safe.yml
  Integrations/BeyondTrust_Password_Safe/CHANGELOG.md
Labels: docs-approved, release-notes-only

#4723 UnEscapeURLs Proofpoint V3 Fix
  Scripts/script-UnEscapeURLs.yml
  Scripts/script-UnEscapeURLs_CHANGELOG.md
  TestPlaybooks/playbook-UnEscapeURLs-Test.yml
Labels: docs-approved, release-notes-only

#4552 PowerShell content support
  Documentation/commonServerConstants.json
  Documentation/common_server_docs.py
  Scripts/CommonServerPowerShell/CommonServerPowerShell.ps1
  Scripts/CommonServerPowerShell/CommonServerPowerShell.yml
  Scripts/script-CommonServerUserPowerShell.yml
  Tests/schemas/integration.yml
  Tests/schemas/script.yml
  Tests/scripts/constants.py
  Tests/scripts/hook_validations/structure.py
  Tests/scripts/pkg_dev_test_tasks.py
  package_creator.py
Labels: docs-approved

#4803 separate dockerimage for 4.5 and 5.0+
  Integrations/Kafka_V2/CHANGELOG.md
  Integrations/Kafka_V2/Kafka_V2.py
  Integrations/Kafka_V2/Kafka_V2.yml
  Integrations/Kafka_V2/Kafka_V2_test.py
  Integrations/integration-Exchange2016_Compliance.yml
  Scripts/RegexGroups/CHANGELOG.md
  Scripts/RegexGroups/RegexGroups.yml
  Scripts/script-DecodeMimeHeader.yml
  Tests/schemas/integration.yml
  Tests/schemas/script.yml
  Tests/scripts/constants.py
  Tests/scripts/hook_validations/integration.py
  Tests/scripts/hook_validations/script.py
  Tests/scripts/pkg_dev_test_tasks.py
  Tests/scripts/validate_files.py
  Tests/test_utils.py
  content_creator.py
  docs/docker/README.MD
  docs/yaml-file-integration/README.MD
  package_creator.py
Labels: docs-approved, release-notes-only

#4816 EWS - Exposed the mail body to the war room
  Integrations/EWSv2/CHANGELOG.md
  Integrations/EWSv2/EWSv2.py
  TestPlaybooks/playbook-pyEWS_Test.yml
Labels: docs-approved, release-notes-only

#4821 Increased maximal fetch limit
  Integrations/SplunkPy/CHANGELOG.md
  Integrations/SplunkPy/SplunkPy.py
  Integrations/SplunkPy/SplunkPy.yml
Labels: docs-approved

#4771 - Changed the description of commands with wrong examples
  Scripts/script-SearchIncidents.yml
  Scripts/script-SearchIncidents_CHANGELOG.md
Labels: docs-approved

#4828 Add Page break widget
  Widgets/widget-Pagebreak.json
Labels: docs-approved, release-notes-only

#4807 PAN-OS: url arg in query-logs: eq -> contains and cutom-block-rule fix
  Integrations/Panorama/CHANGELOG.md
  Integrations/Panorama/Panorama.py
Labels: docs-approved, release-notes-only

#4481 Update ExtraHop Integration
  IncidentFields/incidentfield-ExtraHop_Appliance_ID.json
  IncidentFields/incidentfield-ExtraHop_Detection_End_Time.json
  IncidentFields/incidentfield-ExtraHop_Detection_ID.json
  IncidentFields/incidentfield-ExtraHop_Detection_Participants.json
  IncidentFields/incidentfield-ExtraHop_Detection_Raw_Participants.json
  IncidentFields/incidentfield-ExtraHop_Detection_Risk_Score.json
  IncidentFields/incidentfield-ExtraHop_Detection_Ticketed.json
  IncidentFields/incidentfield-ExtraHop_Detection_URL.json
  IncidentFields/incidentfield-ExtraHop_Detection_Update_Time.json
  IncidentFields/incidentfield-ExtraHop_Hostname.json
  IncidentTypes/incidenttype-ExtraHop_Detection.json
  Integrations/ExtraHop_v2/ExtraHop_v2.py
  Integrations/ExtraHop_v2/ExtraHop_v2.yml
  Integrations/ExtraHop_v2/ExtraHop_v2_description.md
  Integrations/ExtraHop_v2/ExtraHop_v2_image.png
  Integrations/ExtraHop_v2/Pipfile
  Integrations/ExtraHop_v2/Pipfile.lock
  Integrations/ExtraHop_v2/README.md
  Layouts/layout-close-ExtraHop_Detection.json
  Layouts/layout-close-ExtraHop_Detection_CHANGELOG.md
  Layouts/layout-details-ExtraHop_Detection.json
  Layouts/layout-details-ExtraHop_Detection_CHANGELOG.md
  Layouts/layout-edit-ExtraHop_Detection.json
  Layouts/layout-edit-ExtraHop_Detection_CHANGELOG.md
  Layouts/layout-mobile-ExtraHop_Detection.json
  Layouts/layout-mobile-ExtraHop_Detection_CHANGELOG.md
  Layouts/layout-quickView-ExtraHop_Detection.json
  Layouts/layout-quickView-ExtraHop_Detection_CHANGELOG.md
  Playbooks/playbook-Endpoint_Enrichment_-_Generic_v2.1.yml
  Playbooks/playbook-Endpoint_Enrichment_-_Generic_v2.1_CHANGELOG.md
  Playbooks/playbook-ExtraHop_-_CVE-2019-0708_(BlueKeep).yml
  Playbooks/playbook-ExtraHop_-_Default.yml
  Playbooks/playbook-ExtraHop_-_Get_Peers_by_Host.yml
  Playbooks/playbook-ExtraHop_-_Ticket_Tracking.yml
  Scripts/ExtraHopTrackIncidents/ExtraHopTrackIncidents.py
  Scripts/ExtraHopTrackIncidents/ExtraHopTrackIncidents.yml
  TestPlaybooks/playbook-ExtraHop_v2-Test.yml
  Tests/conf.json
  Tests/secrets_white_list.json
  release_notes.py
Labels: Contribution, docs-approved

#4500 Google KMS integration
  Integrations/GoogleKeyManagementService/GoogleKeyManagementService.py
  Integrations/GoogleKeyManagementService/GoogleKeyManagementService.yml
  Integrations/GoogleKeyManagementService/GoogleKeyManagementService_description.md
  Integrations/GoogleKeyManagementService/GoogleKeyManagementService_image.png
  Integrations/GoogleKeyManagementService/GoogleKeyManagementService_test.py
  Integrations/GoogleKeyManagementService/Pipfile
  Integrations/GoogleKeyManagementService/Pipfile.lock
  TestPlaybooks/playbook-Google-KMS-test.yml
  Tests/conf.json
Labels: docs-approved

#4641 New playbook - Isolate Endpoint - Generic
  Playbooks/playbook-Isolate_Endpoint_-_Generic.yml
Labels: docs-approved

#4790 fix - xdr-update-incident should not execute with empty arguments
  Scripts/XDRSyncScript/CHANGELOG.md
  Scripts/XDRSyncScript/XDRSyncScript.py
Labels: docs-approved, release-notes-only

#4640 New Block File playbooks & Block File - Generic v2
  Playbooks/playbook-Block_File_-_Cybereason.yml
  Playbooks/playbook-Block_File_-_Cylance_Protect_v2.yml
  Playbooks/playbook-Block_File_-_Generic_CHANGELOG.md
  Playbooks/playbook-Block_File_-_Generic_v2.yml
  Playbooks/playbook-Block_Indicators_-_Generic_v2.yml
Labels: docs-approved

#4848 Fixed output descriptions based on Block Indicators - Generic v2
  Playbooks/playbook-Block_IP_-_Generic_v2.yml
  Playbooks/playbook-Block_IP_-_Generic_v2_CHANGELOG.md
Labels: docs-approved

#4850 ThreatQ TPB - fixed test failure
  TestPlaybooks/playbook-ThreatQ-Test.yml
  Tests/conf.json
Labels: docs-approved

#4854 CB Enterprise - correcting bug in non decompress get-binary command
  Integrations/integration-Carbon_Black_Enterprise_Response.yml
Labels: docs-approved

#4853 wait param placement fix
  Integrations/rasterize/rasterize.yml
Labels: docs-approved

#4763 Fixed phishing acknowledgment DT, fixed disconnected task
  Playbooks/playbook-Phishing_Investigation_-_Generic_v2.yml
  Playbooks/playbook-Phishing_Investigation_-_Generic_v2_CHANGELOG.md
Labels: docs-approved, release-notes-only

#4769 added regexes for Packs
  Tests/scripts/constants.py
  Tests/scripts/infrastructure_tests/constants_regex_test.py
Labels: docs-approved

#4844 Mail sender hmac fix
  Integrations/MailSenderNew/CHANGELOG.md
  Integrations/MailSenderNew/MailSenderNew.py
  Integrations/MailSenderNew/MailSenderNew_test.py
Labels: docs-approved, release-notes-only

#4817 - Impossible Traveller playbook, type, fields, layout, scripts, test
  IncidentFields/incidentfield-Coordinates.json
  IncidentFields/incidentfield-Destination_IP.json
  IncidentFields/incidentfield-Previous_Coordinates.json
  IncidentFields/incidentfield-Previous_Sign_In_Date_Time.json
  IncidentFields/incidentfield-Previous_Source_IP.json
  IncidentFields/incidentfield-Sign_In_Date_Time.json
  IncidentFields/incidentfield-Source_IP.json
  IncidentFields/incidentfield-Travel_Map_Link.json
  IncidentFields/incidentfield-Username.json
  IncidentTypes/incidenttype-Impossible_Traveller.json
  Layouts/layout-details-Impossible_Traveller.json
  Layouts/layout-details-Impossible_Traveller_CHANGELOG.md
  Playbooks/playbook-Impossible_Traveller.yml
  Scripts/CalculateGeoDistance/CHANGELOG.md
  Scripts/CalculateGeoDistance/CalculateGeoDistance.py
  Scripts/CalculateGeoDistance/CalculateGeoDistance.yml
  Scripts/CalculateTimeDifference/CNAGELOG.md
  Scripts/CalculateTimeDifference/CalculateTimeDifference.py
  Scripts/CalculateTimeDifference/CalculateTimeDifference.yml
  TestPlaybooks/playbook-Impossible_Traveller_-_Test.yml
  TestPlaybooks/script-CompleteManualTask.yml
  Tests/conf.json
  Tests/secrets_white_list.json
Labels: docs-approved

#4847 Changed playbook task
  TestPlaybooks/playbook-Cloaken-Test.yml
Labels: docs-approved

#4845 Intezer - add empty release notes
  Integrations/integration-Intezer_CHANGELOG.md
Labels: docs-approved

#4822 Limit content entities file path length in content.zip
  .circleci/config.yml
  Playbooks/playbook-PrismaCloudRemediation_-_AWSCloudTrailIsNotEnabledOnTheAccount.yml
  Playbooks/playbook-PrismaCloudRemediation_-_AWSCloudTrailIsNotEnabledOnTheAccount_CHANGELOG.md
  Playbooks/playbook-PrismaCloudRemediation_-_AWSInactiveUsersForMoreThan30Days.yml
  Playbooks/playbook-PrismaCloudRemediation_-_AWSInactiveUsersForMoreThan30Days_CHANGELOG.md
  Playbooks/playbook-PrismaCloudRemediation_-_AWSSecurityGroupsAllowInternetTrafficToTCPPort.yml
  Playbooks/playbook-PrismaCloudRemediation_-_AWSSecurityGroupsAllowInternetTrafficToTCPPort_CHANGELOG.md
  Playbooks/playbook-VulnerabilityHandling_-_Qualys_-_AddCustomFieldsToDefaultLayout.yml
  Playbooks/playbook-VulnerabilityHandling_-_Qualys_-_AddCustomFieldsToDefaultLayout_CHANGELOG.md
  Tests/scripts/constants.py
  Tests/scripts/pkg_dev_test_tasks.py
  content_creator.py
  package_creator.py
  release_notes.py
Labels: docs-approved

#4601 Build phishing classifier
  Playbooks/playbook-DBot_Create_Phishing_Classifier_V2.yml
  Playbooks/playbook-DBot_Create_Phishing_Classifier_V2_Job.yml
  Scripts/DBotBuildPhishingClassifier/DBotBuildPhishingClassifier.py
  Scripts/DBotBuildPhishingClassifier/DBotBuildPhishingClassifier.yml
  Scripts/DBotPredictPhishingWords/CHANGELOG.md
  Scripts/DBotPredictPhishingWords/DBotPredictPhishingWords.yml
  Scripts/DBotPreprocessTextData/DBotPreprocessTextData.py
  Scripts/DBotPreprocessTextData/DBotPreprocessTextData.yml
  Scripts/DBotPreprocessTextData/TestData/input_json_file_test
  Scripts/DBotPreprocessTextData/dbot_preprocess_text_data_test.py
  Scripts/DBotTrainTextClassifierV2/DBotTrainTextClassifierV2.py
  Scripts/DBotTrainTextClassifierV2/DBotTrainTextClassifierV2.yml
  Scripts/DBotTrainTextClassifierV2/TestData/input_json_file_test
  Scripts/DBotTrainTextClassifierV2/dbot_train_text_classifier_test.py
  Scripts/GetIncidentsByQuery/GetIncidentsByQuery.py
  Scripts/GetIncidentsByQuery/GetIncidentsByQuery.yml
  Scripts/GetIncidentsByQuery/get_incidents_by_query_test.py
  TestPlaybooks/playbook-Create_Phishing_Classifier_V2_ML_Test.yml
  TestPlaybooks/script-TestCreateIncidentsForPhishingClassifier.yml
  Tests/conf.json
Labels: docs-approved

#4815 update script.py and integration.py to get_remote_file
  Tests/scripts/hook_validations/integration.py
  Tests/scripts/hook_validations/script.py
  Tests/scripts/hook_validations/tests/test_utils_test.py
  Tests/test_utils.py
Labels: docs-approved

#4710 Docs for S/MIME Messaging integration
  Integrations/SMIME_Messaging/README.md
  Tests/secrets_white_list.json
Labels: docs-approved

#3915 Fix for unhandled FireEye ETP exception
  Integrations/FireEyeETP/CHANGELOG.md
  Integrations/FireEyeETP/FireEyeETP.py
  Integrations/FireEyeETP/FireEyeETP.yml
Labels: Contribution, docs-approved

#4812 Pylint enable string checker
  Integrations/AWS-EC2/AWS-EC2.py
  Integrations/AWS-EC2/AWS-EC2.yml
  Integrations/AWS-EC2/CHANGELOG.md
  Integrations/Active_Directory_Query/Active_Directory_Query.py
  Integrations/Active_Directory_Query/CHANGELOG.md
  Integrations/GitHub/CHANGELOG.md
  Integrations/GitHub/GitHub.py
  Integrations/PolySwarm/CHANGELOG.md
  Integrations/PolySwarm/PolySwarm.py
  Integrations/Whois/CHANGELOG.md
  Integrations/Whois/Whois.py
  Integrations/cisco-ise/CHANGELOG.md
  Integrations/cisco-ise/cisco-ise.py
  Integrations/cisco-ise/cisco-ise.yml
  Integrations/cisco-ise/cisco-ise_CHANGELOG.md
  Tests/scripts/run_dev_tasks.sh
Labels: docs-approved

#4734 [Fix] War room outputs ^^^ - JS
  Scripts/script-CommonServer.yml
  Scripts/script-CommonServer_CHANGELOG.md
  TestPlaybooks/script-VerifyTableToMarkDown.yml
Labels: docs-approved, release-notes-only

#4856 Changed fromversion to string
  IncidentTypes/incidenttype-Prisma_Cloud.json
  IncidentTypes/incidenttype-Prisma_Cloud_CHANGELOG.md
Labels: docs-approved

#4859 Phishing classifier
  Playbooks/playbook-DBot_Create_Phishing_Classifier_V2.yml
  Playbooks/playbook-DBot_Create_Phishing_Classifier_V2_Job.yml
  Scripts/DBotBuildPhishingClassifier/DBotBuildPhishingClassifier.py
  Scripts/DBotBuildPhishingClassifier/DBotBuildPhishingClassifier.yml
  Scripts/DBotPredictPhishingWords/CHANGELOG.md
  Scripts/DBotPredictPhishingWords/DBotPredictPhishingWords.yml
  Scripts/DBotPreprocessTextData/DBotPreprocessTextData.py
  Scripts/DBotPreprocessTextData/DBotPreprocessTextData.yml
  Scripts/DBotPreprocessTextData/TestData/input_json_file_test
  Scripts/DBotPreprocessTextData/dbot_preprocess_text_data_test.py
  Scripts/DBotTrainTextClassifierV2/DBotTrainTextClassifierV2.py
  Scripts/DBotTrainTextClassifierV2/DBotTrainTextClassifierV2.yml
  Scripts/DBotTrainTextClassifierV2/TestData/input_json_file_test
  Scripts/DBotTrainTextClassifierV2/dbot_train_text_classifier_test.py
  Scripts/GetIncidentsByQuery/GetIncidentsByQuery.py
  Scripts/GetIncidentsByQuery/GetIncidentsByQuery.yml
  Scripts/GetIncidentsByQuery/get_incidents_by_query_test.py
  TestPlaybooks/playbook-Create_Phishing_Classifier_V2_ML_Test.yml
  TestPlaybooks/script-TestCreateIncidentsForPhishingClassifier.yml
  Tests/conf.json
Labels: docs-approved

#4857 add fromversion to test playbook
  TestPlaybooks/playbook-SecurityAdvisor-Test.yml
  Tests/conf.json
Labels: docs-approved

#4855 lgtm config: define test files
  .lgtm.yaml
Labels: docs-approved

#4779 Add session to baseClient
  Scripts/CommonServerPython/CHANGELOG.md
  Scripts/CommonServerPython/CommonServerPython.py
Labels: docs-approved

#4831 Build shift
  Tests/conf.json
Labels: docs-approved

#4078 Jsonwhois integration
  Integrations/JsonWhoIs/JsonWhoIs.py
  Integrations/JsonWhoIs/JsonWhoIs.yml
  Integrations/JsonWhoIs/JsonWhoIs_description.md
  Integrations/JsonWhoIs/JsonWhoIs_image.png
  Integrations/JsonWhoIs/README.md
  TestPlaybooks/playbook-jsonwhois_test.yml
  Tests/conf.json
  Tests/secrets_white_list.json
Labels: content, docs-approved, inprogress

#4867 unskipped PAN-OS Create Or Edit Rule Test
  Tests/conf.json
Labels: docs-approved

#4861 Phishing - Core - playbok + test fix
  Playbooks/playbook-Phishing_-_Core.yml
  Playbooks/playbook-Phishing_-_Core_CHANGELOG.md
  TestPlaybooks/playbook-Phishing_-_Core_-_Test.yml
  Tests/conf.json
Labels: docs-approved

#4846 Regex url domain forwardslash
  Misc/reputation-domain.json
  Misc/reputation-domain_CHANGELOG.md
  Misc/reputation-url.json
  Misc/reputation-url_CHANGELOG.md
  Misc/reputations.json
  Misc/reputations_CHANGELOG.md
  Scripts/ExtractDomainFromUrlFormat/CHANGELOG.md
  Scripts/ExtractDomainFromUrlFormat/ExtractDomainFromUrlFormat.py
  Scripts/ExtractDomainFromUrlFormat/ExtractDomainFromUrlFormat_test.py
  Scripts/script-UnEscapeURLs.yml
  Scripts/script-UnEscapeURLs_CHANGELOG.md
  TestPlaybooks/playbook-UnEscapeURLs-Test.yml
  TestPlaybooks/playbook-reputation.json-Test.yml
  Tests/scripts/configure_tests.py
  Tests/secrets_white_list.json
Labels: docs-approved

#4869 Fixes issue where insecure would throw warnings
  Integrations/AWS-ACM/AWS-ACM.py
  Integrations/AWS-ACM/AWS-ACM.yml
Labels: docs-approved

#4825 Fix STIX2 1 object.
  Scripts/StixParser/CHANGELOG.md
  Scripts/StixParser/StixParser.py
  Scripts/StixParser/StixParser_test.py
Labels: docs-approved

#4501 Added delete-group and create-group commands
  Integrations/Active_Directory_Query/Active_Directory_Query.py
  Integrations/Active_Directory_Query/Active_Directory_Query.yml
  Integrations/Active_Directory_Query/CHANGELOG.md
Labels: Contribution, docs-approved

#4775 New transformer: SecondsToString.
  Scripts/SecondsToString/Pipfile
  Scripts/SecondsToString/Pipfile.lock
  Scripts/SecondsToString/SecondsToString.py
  Scripts/SecondsToString/SecondsToString.yml
  Scripts/SecondsToString/SecondsToString_test.py
Labels: Contribution, docs-approved

#4858 Update id_set to support packs
  .circleci/config.yml
  Tests/scripts/constants.py
  Tests/scripts/infrastructure_tests/update_id_set_test.py
  Tests/scripts/update_id_set.py
Labels: docs-approved

#4879 Removing Microsoft Graph from skipped
  Tests/conf.json
Labels: docs-approved

#4870 Skipped tests
  Tests/conf.json
Labels: docs-approved

#4882 Fix test error response.
  Integrations/SplunkPy/CHANGELOG.md
  Tests/conf.json
  Tests/test_integration.py
Labels: docs-approved

#4884 Id set fix script
  Tests/scripts/update_id_set.py
Labels: docs-approved

#4889 extend retries in wait for server to be ready
  Tests/scripts/wait_until_server_ready.py
Labels: docs-approved

#4849 Modified test_module + changelog
  Integrations/CofenseTriage/CHANGELOG.md
  Integrations/CofenseTriage/CofenseTriage.py
  Integrations/CofenseTriage/CofenseTriage.yml
Labels: docs-approved, release-notes-only

#4862 SentinelOne V2 - Fixed an issue in the Fetch incidents function.
  Integrations/SentinelOne-V2/CHANGELOG.md
  Integrations/SentinelOne-V2/SentinelOne-V2.py
Labels: docs-approved, release-notes-only

#4883 Secrets - clean some code
  Tests/conf.json
  Tests/scripts/hook_validations/secrets.py
Labels: docs-approved

#4851 Modified script to handle zero as value and not as None
  Scripts/PositiveDetectionsVSDetectionEngines/CHANGELOG.md
  Scripts/PositiveDetectionsVSDetectionEngines/PositiveDetectionsVSDetectionEngines.py
  Scripts/PositiveDetectionsVSDetectionEngines/Test_PositiveDetectionsVSDetectionEngines.py
Labels: docs-approved, release-notes-only

#4841 Fixed display name
  Integrations/integration-ArcherRSA.yml
  Integrations/integration-ArcherRSA_CHANGELOG.md
Labels: docs-approved, release-notes-only

#4834 added -sn flag support
  Integrations/Nmap/CHANGELOG.md
  Integrations/Nmap/Nmap.py
  TestPlaybooks/playbook-Nmap-Test.yml
  Tests/conf.json
Labels: docs-approved, release-notes-only

#4796 Tenable.io bug
  Integrations/Tenable_io/CHANGELOG.md
  Integrations/Tenable_io/Tenable_io.py
  Integrations/Tenable_io/Tenable_io_test.py
Labels: docs-approved, release-notes-only

#4865 fixed pagebreak widget to the correct pagebreak usage
  Widgets/widget-Pagebreak.json
  Widgets/widget-Pagebreak_CHANGELOG.md
Labels: docs-approved, release-notes-only

#4886 Modified query builder and playbook to test it
  Integrations/integration-RsaNetWitnessPacketsAndLogs.yml
  Integrations/integration-RsaNetWitnessPacketsAndLogs_CHANGELOG.md
  TestPlaybooks/playbook-Test_RSA_PacketsAndLogs.yml
Labels: docs-approved, release-notes-only

#4890 Telegram - Replaced image
  Beta_Integrations/Telegram/Telegram_CHANGELOG.md
  Beta_Integrations/Telegram/Telegram_image.png
Labels: docs-approved, release-notes-only

#4432 Limit the number of emails ingested per fetch
  Integrations/EWSv2/CHANGELOG.md
  Integrations/EWSv2/EWSv2.py
  Integrations/EWSv2/EWSv2.yml
Labels: content, docs-approved, enhancement

#4892 Update integration-ArcherRSA_CHANGELOG.md
  Integrations/integration-ArcherRSA_CHANGELOG.md
Labels: docs-approved

#4804 Fix proofpoint fetch incidents
  Integrations/ProofpointTAP_v2/CHANGELOG.md
  Integrations/ProofpointTAP_v2/ProofpointTAP_v2.py
  Integrations/ProofpointTAP_v2/ProofpointTAP_v2_test.py
Labels: docs-approved

#4893 deprecated old integrations
  Integrations/ExtraHop/CHANGELOG.md
  Integrations/ExtraHop/ExtraHop.yml
  Integrations/integration-AlienVaultOTX.yml
  Integrations/integration-AlienVaultOTX_CHANGELOG.md
Labels: docs-approved

#4903 Extract Indicators From File - Generic v2 out from skipped
  Tests/conf.json
Labels: docs-approved

#4898 Move secrets into it's own step in circle
  .circleci/config.yml
  Tests/scripts/hook_validations/secrets.py
  Tests/scripts/validate_files.py
Labels: docs-approved

#4899 Joe security output fix
  Integrations/JoeSecurity/CHANGELOG.md
  Integrations/JoeSecurity/JoeSecurity.yml
  Playbooks/playbook-Calculate_Severity_-_Generic_3_1.yml
  Playbooks/playbook-Calculate_Severity_-_Generic_3_1_CHANGELOG.md
  Playbooks/playbook-Detonate_File_-_Cuckoo.yml
  Playbooks/playbook-Detonate_File_-_Cuckoo_CHANGELOG.md
  Playbooks/playbook-Detonate_File_-_JoeSecurity.yml
  Playbooks/playbook-Detonate_File_-_JoeSecurity_CHANGELOG.md
  Playbooks/playbook-Detonate_File_From_URL_-_JoeSecurity.yml
  Playbooks/playbook-Detonate_File_From_URL_-_JoeSecurity_CHANGELOG.md
  Playbooks/playbook-Detonate_URL_-_Cuckoo.yml
  Playbooks/playbook-Detonate_URL_-_Cuckoo_CHANGELOG.md
  Playbooks/playbook-Detonate_URL_-_JoeSecurity.yml
  Playbooks/playbook-Detonate_URL_-_JoeSecurity_CHANGELOG.md
Labels: docs-approved

#4901 Unskipping PAN-OS
  Tests/conf.json
Labels: docs-approved

#4910 Changed unit test file name
  Scripts/PositiveDetectionsVSDetectionEngines/PositiveDetectionsVSDetectionEngines_test.py
Labels: bug, docs-approved

#4911 Try catch for unprotected request in build tests
  Tests/scripts/destroy_instances.py
  Tests/test_content.py
  Tests/test_integration.py
Labels: docs-approved

#4900 EWS - disabled logging exceptions
  Integrations/EWSv2/CHANGELOG.md
  Integrations/EWSv2/EWSv2.py
Labels: bug, docs-approved, release-notes-only

#4912 unify functions get yaml and get json
  Tests/scripts/hook_validations/tests/test_utils_test.py
  Tests/scripts/hook_validations/tests/tests_data/fake_json.json
  Tests/test_utils.py
Labels: docs-approved

#4917 Packagify
  Integrations/SymantecMSS/CHANGELOG.md
  Integrations/SymantecMSS/SymantecMSS.py
  Integrations/SymantecMSS/SymantecMSS.yml
  Integrations/SymantecMSS/SymantecMSS_description.md
  Integrations/SymantecMSS/SymantecMSS_image.png
  Integrations/integration-SymantecMSS.yml
Labels: docs-approved

#4923 Fixes unbound error when server is ready, but not really ready
  Tests/scripts/wait_until_server_ready.py
Labels: docs-approved
