Repository demisto/content, pull requests merged in 2019-08, with the labels that each got.

#4067 QRadar support 7.3.2 patch 3
  Integrations/QRadar/CHANGELOG.md
  Integrations/QRadar/QRadar.py
  Integrations/QRadar/QRadar.yml
  TestData/Hashes_list.csv
Labels: inprogress

#4114 Update sane doc reports automation
  Releases/LatestRelease/SaneDocReport.md
  Scripts/SaneDocReport/CHANGELOG.md
  Scripts/SaneDocReport/SaneDocReport.py
  Scripts/SaneDocReport/SaneDocReport.yml
Labels: bug

#4018 Add additional arguments to authorize_security_group_ingress command AWS EC2
  Integrations/AWS-EC2/AWS-EC2.py
  Integrations/AWS-EC2/AWS-EC2.yml
  Integrations/AWS-EC2/CHANGELOG.md
  Releases/LatestRelease/AWS-EC2.md
Labels: docs-approved

#4243 Microsoft Teams - improve error handling
  Integrations/MicrosoftTeams/CHANGELOG.md
  Integrations/MicrosoftTeams/MicrosoftTeams.py
  Integrations/MicrosoftTeams/MicrosoftTeams_test.py
Labels: docs-approved

#4190 Fixed UnicodeDecodeError in qradar-get-search-results
  Integrations/QRadar/CHANGELOG.md
  Integrations/QRadar/QRadar.py
Labels: docs-approved

#4231 fix upload-file command when the file is summary report
  Integrations/ServiceNow/CHANGELOG.md
  Integrations/ServiceNow/ServiceNow.py
  Integrations/ServiceNow/ServiceNow.yml
Labels: docs-approved

#4182 - Added dbot score to ip+domain commands
  Integrations/integration-Threat_Crowd.yml
  Integrations/integration-Threat_Crowd_CHANGELOG.md
  TestPlaybooks/playbook-ThreatCrowd-Test.yml
  Tests/conf.json
Labels: docs-approved

#4215 Pan os panorama shared and device-group args and outputs addition
  Integrations/Panorama/CHANGELOG.md
  Integrations/Panorama/Panorama.py
  Integrations/Panorama/Panorama.yml
  Integrations/Panorama/Panorama_description.md
  TestPlaybooks/playbook-Panorama_Query_Logs_-_Test.yml
  TestPlaybooks/playbook-palo_alto_panorama_test_pb.yml
Labels: docs-approved

#4248 [Fix] QRadar missing SEC header when trying to get offense types
  Integrations/QRadar/CHANGELOG.md
  Integrations/QRadar/QRadar.py
Labels: docs-approved

#4246 netskope-alerts raw response fix
  Integrations/integration-Netskope.yml
  Integrations/integration-Netskope_CHANGELOG.md
Labels: docs-approved

#3793 SendMailToManager bug fix
  Scripts/SendEmailToManager/CHANGELOG.md
  Scripts/SendEmailToManager/SendEmailToManager.py
  Scripts/SendEmailToManager/SendEmailToManager.yml
  Scripts/script-SendEmailToManager.yml
Labels: docs-approved
