Repository demisto/content, pull requests merged in 2020-12, with the labels that each got.

#10164 killing prints manager
  Documentation/common_server_docs.py
  Tests/Marketplace/configure_and_install_packs.py
  Tests/Marketplace/copy_and_upload_packs.py
  Tests/Marketplace/normalize_gcs_paths.py
  Tests/Marketplace/packs_dependencies.py
  Tests/Marketplace/private_build_prepare_for_testing.py
  Tests/Marketplace/upload_packs.py
  Tests/Marketplace/zip_packs.py
  Tests/configure_and_test_integration_instances.py
  Tests/instance_notifier.py
  Tests/mock_server.py
  Tests/private_build/configure_and_test_integration_instances_private.py
  Tests/private_build/run_content_tests_private.py
  Tests/private_build/tests/test_configure_and_test_integration_instances_private.py
  Tests/scripts/collect_tests_and_content_packs.py
  Tests/scripts/slack_notifier.py
  Tests/scripts/update_conf_json.py
  Tests/scripts/utils/log_util.py
  Tests/scripts/wait_until_server_ready.py
  Tests/test_content.py
  Tests/test_integration.py
  Tests/tests/test_integration_test.py
  Tests/tools.py
  Utils/release_notes_generator.py
Labels: docs-approved

#10193 Mohan/pack readme
  Packs/WootCloud/README.md
Labels: Contribution, docs-approved

#10201 Fixing mimecast test
  Packs/Mimecast/TestPlaybooks/playbook-Mimecast_Test.yml
Labels: docs-approved

#10170 Add json loads in case literal_eval fails
  Tests/timestamp_replacer.py
Labels: docs-approved

#10197 Increasing timeout for tests
  Tests/conf.json
Labels: docs-approved

#9250 Azure sentinel enhancement - `azure-sentinel-get-entity-by-id`
  Packs/AzureSentinel/.secrets-ignore
  Packs/AzureSentinel/Integrations/AzureSentinel/AzureSentinel.py
  Packs/AzureSentinel/Integrations/AzureSentinel/AzureSentinel.yml
  Packs/AzureSentinel/ReleaseNotes/1_0_5.md
  Packs/AzureSentinel/pack_metadata.json
Labels: docs-approved, release-notes-only

#10147 Content build fails for long Install Content step - reconnecting client on each instance
  Tests/configure_and_test_integration_instances.py
Labels: docs-approved

#10199 GetFailedTasks - handle demisto rest api executeCommand error
  Packs/IntegrationsAndIncidentsHealthCheck/ReleaseNotes/1_1_8.md
  Packs/IntegrationsAndIncidentsHealthCheck/Scripts/GetFailedTasks/GetFailedTasks.py
  Packs/IntegrationsAndIncidentsHealthCheck/pack_metadata.json
Labels: bug, docs-approved, release-notes-only

#10194 Akamai WAF - add extended and include_elements args to networks list
  Packs/Akamai_WAF/Integrations/Akamai_WAF/Akamai_WAF.py
  Packs/Akamai_WAF/Integrations/Akamai_WAF/Akamai_WAF.yml
  Packs/Akamai_WAF/Integrations/Akamai_WAF/README.md
  Packs/Akamai_WAF/ReleaseNotes/1_0_2.md
  Packs/Akamai_WAF/pack_metadata.json
Labels: bug, docs-approved, release-notes-only

#10187 Replace !crowdstrike-get-environments command API url to new one
  Packs/CrowdStrikeFalconSandbox/Integrations/integration-CrowdStrikeFalconSandbox.yml
  Packs/CrowdStrikeFalconSandbox/Integrations/integration-CrowdStrikeFalconSandbox_README.md
  Packs/CrowdStrikeFalconSandbox/ReleaseNotes/1_0_3.md
  Packs/CrowdStrikeFalconSandbox/pack_metadata.json
Labels: docs-approved, release-notes-only

#10198 In case content-test-data is already exist - reset it and pull from m…
  Tests/scripts/clone_mocks.sh
Labels: docs-approved

#10203 removing .Dockerfile from SetAndHandleEmpty
  Packs/CommonScripts/Scripts/SetAndHandleEmpty/.Dockerfile
Labels: docs-approved

#10206 RSA key is in the server from the AMI
  Tests/mock_server.py
Labels: docs-approved

#10180 Optimize build for readme changes only
  .circleci/config.yml
  Tests/scripts/collect_tests_and_content_packs.py
  Tests/scripts/infrastructure_tests/test_collect_tests_and_content_packs.py
Labels: docs-approved

#10209 jira - Fixed an issue where the following parameters: projectKey and issueTypeId were marked as mandatory which caused backwards compatibility issue.
  Packs/Jira/Integrations/JiraV2/JiraV2.py
  Packs/Jira/Integrations/JiraV2/JiraV2.yml
  Packs/Jira/Integrations/JiraV2/JiraV2_test.py
  Packs/Jira/Integrations/JiraV2/README.md
  Packs/Jira/ReleaseNotes/1_2_5.md
  Packs/Jira/pack_metadata.json
Labels: bug, docs-approved, release-notes-only

#10211 set INSTANCE_WAS_CREATED to true in nightly
  .circleci/config.yml
Labels: docs-approved

#10191 Checkpoint Firewall v2 - pass the host id to the request properly in the delete-host cmd
  Packs/CheckpointFirewall/Integrations/CheckPointFirewall_v2/CheckPointFirewall_v2.py
  Packs/CheckpointFirewall/Integrations/CheckPointFirewall_v2/CheckPointFirewall_v2_test.py
  Packs/CheckpointFirewall/ReleaseNotes/2_0_4.md
  Packs/CheckpointFirewall/pack_metadata.json
Labels: docs-approved, release-notes-only

#9912 ServiceNow IAM
  Packs/ServiceNow/Classifiers/classifier-mapper-incoming-User-Profile-ServiceNow.json
  Packs/ServiceNow/Classifiers/classifier-mapper-outgoing-ServiceNow-User-Profile.json
  Packs/ServiceNow/Integrations/ServiceNow_IAM/README.md
  Packs/ServiceNow/Integrations/ServiceNow_IAM/ServiceNow_IAM.py
  Packs/ServiceNow/Integrations/ServiceNow_IAM/ServiceNow_IAM.yml
  Packs/ServiceNow/Integrations/ServiceNow_IAM/ServiceNow_IAM_description.md
  Packs/ServiceNow/Integrations/ServiceNow_IAM/ServiceNow_IAM_image.png
  Packs/ServiceNow/Integrations/ServiceNow_IAM/ServiceNow_IAM_test.py
  Packs/ServiceNow/ReleaseNotes/2_0_0.md
  Packs/ServiceNow/pack_metadata.json
Labels: docs-approved

#9918 Okta IAM - phase 2
  Packs/Okta/.secrets-ignore
  Packs/Okta/Classifiers/classifier-Okta_IAM.json
  Packs/Okta/Classifiers/classifier-mapper-Okta_IAM.json
  Packs/Okta/Integrations/Okta_IAM/Okta_IAM.py
  Packs/Okta/Integrations/Okta_IAM/Okta_IAM.yml
  Packs/Okta/Integrations/Okta_IAM/Okta_IAM_description.md
  Packs/Okta/Integrations/Okta_IAM/Okta_IAM_test.py
  Packs/Okta/Integrations/Okta_IAM/README.md
  Packs/Okta/ReleaseNotes/2_1_0.md
  Packs/Okta/pack_metadata.json
Labels: docs-approved

#10127 VMware Carbon Black EDR - update display name
  Packs/Carbon_Black_Enterprise_Response/Integrations/integration-Carbon_Black_Enterprise_Response.yml
  Packs/Carbon_Black_Enterprise_Response/ReleaseNotes/1_1_2.md
  Packs/Carbon_Black_Enterprise_Response/pack_metadata.json
Labels: docs-approved, release-notes-only

#10205 FireEye HX - cast version to int
  Packs/FireEyeHX/Integrations/FireEyeHX/FireEyeHX.py
  Packs/FireEyeHX/ReleaseNotes/1_0_7.md
  Packs/FireEyeHX/pack_metadata.json
Labels: docs-approved, release-notes-only

#10168 Updated email body when sending update to the reporting user in Phishing - Core
  Packs/Phishing/Playbooks/Phishing_-_Core.yml
  Packs/Phishing/ReleaseNotes/1_11_0.md
  Packs/Phishing/pack_metadata.json
Labels: docs-approved, release-notes-only

#9749 X matters
  Packs/XMatters/.pack-ignore
  Packs/XMatters/.secrets-ignore
  Packs/XMatters/Integrations/xMatters/Pipfile
  Packs/XMatters/Integrations/xMatters/Pipfile.lock
  Packs/XMatters/Integrations/xMatters/README.md
  Packs/XMatters/Integrations/xMatters/command_examples.txt
  Packs/XMatters/Integrations/xMatters/xMatters.py
  Packs/XMatters/Integrations/xMatters/xMatters.yml
  Packs/XMatters/Integrations/xMatters/xMatters_description.md
  Packs/XMatters/Integrations/xMatters/xMatters_image.png
  Packs/XMatters/Integrations/xMatters/xMatters_test.py
  Packs/XMatters/Playbooks/xMatters_-_Example_Conditional_Actions.png
  Packs/XMatters/Playbooks/xMatters_-_Example_Conditional_Actions.yml
  Packs/XMatters/Playbooks/xMatters_-_Example_Conditional_Actions_README.md
  Packs/XMatters/Playbooks/xMatters_-_Wait_for_Response.png
  Packs/XMatters/Playbooks/xMatters_-_Wait_for_Response.yml
  Packs/XMatters/Playbooks/xMatters_-_Wait_for_Response_README.md
  Packs/XMatters/README.md
  Packs/XMatters/Scripts/CloseTaskSetContext/CloseTaskSetContext.py
  Packs/XMatters/Scripts/CloseTaskSetContext/CloseTaskSetContext.yml
  Packs/XMatters/Scripts/CloseTaskSetContext/CloseTaskSetContext_test.py
  Packs/XMatters/Scripts/CloseTaskSetContext/Pipfile
  Packs/XMatters/Scripts/CloseTaskSetContext/Pipfile.lock
  Packs/XMatters/Scripts/CloseTaskSetContext/README.md
  Packs/XMatters/Scripts/WaitForKey/Pipfile
  Packs/XMatters/Scripts/WaitForKey/Pipfile.lock
  Packs/XMatters/Scripts/WaitForKey/README.md
  Packs/XMatters/Scripts/WaitForKey/WaitForKey.py
  Packs/XMatters/Scripts/WaitForKey/WaitForKey.yml
  Packs/XMatters/Scripts/WaitForKey/WaitForKey_test.py
  Packs/XMatters/TestPlaybooks/xMatters-Test.yml
  Packs/XMatters/pack_metadata.json
Labels: Contribution, Partner

#9700 ServiceNow V2 OAuth
  Packs/ApiModules/ReleaseNotes/2_1_0.md
  Packs/ApiModules/Scripts/ServiceNowApiModule/README.md
  Packs/ApiModules/Scripts/ServiceNowApiModule/ServiceNowApiModule.py
  Packs/ApiModules/Scripts/ServiceNowApiModule/ServiceNowApiModule.yml
  Packs/ApiModules/Scripts/ServiceNowApiModule/ServiceNowApiModule_test.py
  Packs/ApiModules/pack_metadata.json
  Packs/ServiceNow/Integrations/ServiceNowv2/README.md
  Packs/ServiceNow/Integrations/ServiceNowv2/ServiceNowv2.py
  Packs/ServiceNow/Integrations/ServiceNowv2/ServiceNowv2.yml
  Packs/ServiceNow/Integrations/ServiceNowv2/ServiceNowv2_description.md
  Packs/ServiceNow/Integrations/ServiceNowv2/ServiceNowv2_test.py
  Packs/ServiceNow/Integrations/ServiceNowv2/test_data/response_constants.py
  Packs/ServiceNow/ReleaseNotes/2_0_1.md
  Packs/ServiceNow/TestPlaybooks/playbook-ServiceNow_OAuth_Test.yml
  Packs/ServiceNow/pack_metadata.json
  Tests/conf.json
Labels: docs-approved

#9996 Splunk playbook fix
  Packs/SplunkPy/Playbooks/playbook-Splunk_Indicator_Hunting.yml
  Packs/SplunkPy/ReleaseNotes/1_2_5.md
  Packs/SplunkPy/pack_metadata.json
Labels: docs-approved

#10035 Archer v2: Fixed fetch incident time + upload file to record
  Packs/ArcherRSA/Integrations/ArcherV2/ArcherV2.py
  Packs/ArcherRSA/Integrations/ArcherV2/ArcherV2.yml
  Packs/ArcherRSA/Integrations/ArcherV2/ArcherV2_test.py
  Packs/ArcherRSA/Integrations/ArcherV2/README.md
  Packs/ArcherRSA/ReleaseNotes/1_1_5.md
  Packs/ArcherRSA/TestPlaybooks/playbook-Archer_v2_-_Test.yml
  Packs/ArcherRSA/pack_metadata.json
Labels: bug, docs-approved, release-notes-only

#10137 CheckPointFirewall_v2 - update output prefix
  Packs/CheckpointFirewall/Integrations/CheckPointFirewall_v2/CheckPointFirewall_v2.py
  Packs/CheckpointFirewall/Integrations/CheckPointFirewall_v2/CheckPointFirewall_v2.yml
  Packs/CheckpointFirewall/Integrations/CheckPointFirewall_v2/README.md
  Packs/CheckpointFirewall/ReleaseNotes/2_0_5.md
  Packs/CheckpointFirewall/pack_metadata.json
Labels: docs-approved, release-notes-only

#10229 Added no_output_timeout: 5h to missing steps
  .circleci/config.yml
Labels: docs-approved

#10226 adding back BC check in build
  .circleci/config.yml
Labels: docs-approved

#10057 Support mitmdump service
  .circleci/config.yml
  Tests/mock_server.py
  Tests/test_content.py
Labels: docs-approved

#10227 Certificate Classes for Common.Certificate
  Packs/Base/ReleaseNotes/1_3_42.md
  Packs/Base/Scripts/CommonServerPython/CommonServerPython.py
  Packs/Base/Scripts/CommonServerPython/CommonServerPython_test.py
  Packs/Base/pack_metadata.json
Labels: Contribution, docs-approved

#10018 Some build refractoring
  Tests/Marketplace/search_and_install_packs.py
  Tests/configure_and_test_integration_instances.py
  Tests/private_build/configure_and_test_integration_instances_private.py
  Tests/private_build/run_content_tests_private.py
  Tests/test_content.py
  Tests/tests/configure_and_test_integration_instances_test.py
Labels: docs-approved

#10016 CrowdStrike Falcon Streaming v2 - improve handling for no resources were discovered
  Packs/CrowdStrikeFalconStreamingV2/Integrations/CrowdStrikeFalconStreamingV2/CrowdStrikeFalconStreamingV2.py
  Packs/CrowdStrikeFalconStreamingV2/Integrations/CrowdStrikeFalconStreamingV2/CrowdStrikeFalconStreamingV2.yml
  Packs/CrowdStrikeFalconStreamingV2/ReleaseNotes/1_0_13.md
  Packs/CrowdStrikeFalconStreamingV2/pack_metadata.json
Labels: docs-approved, release-notes-only

#10241 Okta IAM fix
  Packs/Okta/Integrations/Okta_IAM/Okta_IAM.yml
  Packs/Okta/ReleaseNotes/2_1_1.md
  Packs/Okta/pack_metadata.json
Labels: docs-approved

#10106 SumoLogic - handle aggregate records fetch time
  Packs/SumoLogic/Integrations/integration-SumoLogic.yml
  Packs/SumoLogic/ReleaseNotes/1_0_3.md
  Packs/SumoLogic/pack_metadata.json
Labels: bug, docs-approved, release-notes-only

#10244 safely decode raw content in the timestamp replacer
  Tests/timestamp_replacer.py
Labels: docs-approved

#10104 IAM integrations - GitHub
  Packs/GitHub/Integrations/GitHub_IAM/GitHub_IAM.py
  Packs/GitHub/Integrations/GitHub_IAM/GitHub_IAM.yml
  Packs/GitHub/Integrations/GitHub_IAM/GitHub_IAM_description.md
  Packs/GitHub/Integrations/GitHub_IAM/GitHub_IAM_image.png
  Packs/GitHub/Integrations/GitHub_IAM/GitHub_IAM_test.py
  Packs/GitHub/Integrations/GitHub_IAM/Pipfile
  Packs/GitHub/Integrations/GitHub_IAM/Pipfile.lock
  Packs/GitHub/Integrations/GitHub_IAM/README.md
  Packs/GitHub/Integrations/GitHub_IAM/commands_examples.txt
  Packs/GitHub/ReleaseNotes/1_1_2.md
  Packs/GitHub/pack_metadata.json
  Packs/IAM-SCIM/.pack-ignore
  Packs/IAM-SCIM/.secrets-ignore
  Packs/IAM-SCIM/Classifiers/classifier-User_Profile_-_SCIM_(Incoming).json
  Packs/IAM-SCIM/Classifiers/classifier-User_Profile_-_SCIM_(Outgoing).json
  Packs/IAM-SCIM/README.md
  Packs/IAM-SCIM/pack_metadata.json
Labels: IAM, docs-approved

#10246 AlphaSOC NBA - Pass minSeverity parameter to API
  Packs/AlphaSOC_Network_Behavior_Analytics/Integrations/integration-AlphaSOC_Network_Behavior_Analytics.yml
  Packs/AlphaSOC_Network_Behavior_Analytics/ReleaseNotes/1_0_2.md
  Packs/AlphaSOC_Network_Behavior_Analytics/pack_metadata.json
Labels: Contribution, docs-approved

#10183 luminate: upgrade to demisto docker image + split-yml
  Packs/Luminate/Integrations/Luminate/Luminate.py
  Packs/Luminate/Integrations/Luminate/Luminate.yml
  Packs/Luminate/Integrations/Luminate/Luminate_description.md
  Packs/Luminate/Integrations/Luminate/Luminate_image.png
  Packs/Luminate/Integrations/Luminate/Pipfile
  Packs/Luminate/Integrations/Luminate/Pipfile.lock
  Packs/Luminate/Integrations/Luminate/README.md
  Packs/Luminate/Integrations/integration-Luminate.yml
  Packs/Luminate/ReleaseNotes/1_0_2.md
  Packs/Luminate/pack_metadata.json
Labels: docs-approved, release-notes-only

#10260 Bump image tag for #10114
  Packs/CortexDataLake/Integrations/CortexDataLake/CortexDataLake.yml
Labels: Contribution

#9919 move helper functions to common
  Documentation/common_server_docs.py
  Packs/Base/ReleaseNotes/1_4_0.md
  Packs/Base/Scripts/CommonServerPython/CommonServerPython.py
  Packs/Base/Scripts/CommonServerPython/CommonServerPython_test.py
  Packs/Base/pack_metadata.json
  Packs/HelloWorld/Integrations/HelloWorld/HelloWorld.py
  Packs/HelloWorld/Integrations/HelloWorld/HelloWorld.yml
  Packs/HelloWorld/ReleaseNotes/1_1_13.md
  Packs/HelloWorld/pack_metadata.json
  Packs/Jira/Integrations/JiraV2/JiraV2.py
  Packs/Jira/ReleaseNotes/1_2_6.md
  Packs/Jira/pack_metadata.json
Labels: docs-approved

#10263 CommonServerPython improvements
  Packs/Base/ReleaseNotes/1_3_43.md
  Packs/Base/Scripts/CommonServerPython/CommonServerPython.py
  Packs/Base/Scripts/CommonServerPython/CommonServerPython_test.py
  Packs/Base/pack_metadata.json
Labels: Contribution, docs-approved

#10258 One measly dot. .
  Packs/XMatters/README.md
Labels: Contribution, docs-approved

#10245 Removing non bc build trigger
  .circleci/config.yml
  Tests/scripts/validate.sh
  Utils/trigger_content_build_with_no_backward_check.sh
Labels: docs-approved

#10271 removed problematic call to timezone
  Packs/Base/ReleaseNotes/1_4_2.md
  Packs/Base/Scripts/CommonServerPython/CommonServerPython.py
  Packs/Base/Scripts/CommonServerPython/CommonServerPython_test.py
  Packs/Base/pack_metadata.json
Labels: docs-approved

#10272 XMCyber Pack URL and Email change
  Packs/XMCyber/pack_metadata.json
Labels: docs-approved

#10249 Fixed force argument bug
  Packs/Box/Integrations/integration-Box.yml
  Packs/Box/ReleaseNotes/1_0_1.md
  Packs/Box/pack_metadata.json
Labels: bug, docs-approved, release-notes-only

#10261 ThreatGrid Detonate URL - add ThreatGrid prefix to the integration outputs
  Packs/ThreatGrid/Playbooks/playbook-Detonate_File_-_ThreatGrid.yml
  Packs/ThreatGrid/Playbooks/playbook-Detonate_URL_-_ThreatGrid.yml
  Packs/ThreatGrid/ReleaseNotes/1_1_3.md
  Packs/ThreatGrid/pack_metadata.json
Labels: bug, docs-approved, release-notes-only

#10213 replace key access with get method for safe extraction
  Packs/Cybereason/Integrations/Cybereason/Cybereason.py
  Packs/Cybereason/ReleaseNotes/1_0_6.md
  Packs/Cybereason/pack_metadata.json
Labels: bug, docs-approved, release-notes-only

#10233 Jira v2 - fix upload file to work properly with oauth1
  Packs/Jira/Integrations/JiraV2/JiraV2.py
  Packs/Jira/ReleaseNotes/1_2_7.md
  Packs/Jira/pack_metadata.json
Labels: bug, docs-approved, release-notes-only

#10253 Cleaning config.yml from unecessery stuff
  .circleci/config.yml
Labels: docs-approved

#10276 Unmock integrations with files and increase timeout
  Tests/conf.json
Labels: docs-approved

#10210 Fields for IAM / ILM pack
  Packs/CommonTypes/IncidentFields/incidentfield-errorcode.json
  Packs/CommonTypes/IncidentFields/incidentfield-errormessage.json
  Packs/CommonTypes/IncidentFields/incidentfield-userid.json
  Packs/CommonTypes/ReleaseNotes/2_4_0.md
  Packs/CommonTypes/pack_metadata.json
Labels: docs-approved, release-notes-only

#10247 archer v2: fixed fetch times and timzone
  Packs/ArcherRSA/Integrations/ArcherV2/ArcherV2.py
  Packs/ArcherRSA/Integrations/ArcherV2/ArcherV2_test.py
  Packs/ArcherRSA/Integrations/ArcherV2/README.md
  Packs/ArcherRSA/ReleaseNotes/1_1_6.md
  Packs/ArcherRSA/pack_metadata.json
Labels: bug, docs-approved, release-notes-only

#10277 removed bambenek threshold
  Tests/conf.json
Labels: docs-approved

#10207 Adding 2 new fields - primary motivation, malware types
  Packs/CommonTypes/IndicatorFields/indicatorfield-malware_types.json
  Packs/CommonTypes/IndicatorFields/indicatorfield-primary_motivation.json
  Packs/CommonTypes/ReleaseNotes/2_5_0.md
  Packs/CommonTypes/pack_metadata.json
Labels: docs-approved, release-notes-only

#10061 XSOAR [CSPi184] Aria packet intelligence update with latest REST API
  Packs/ARIAPacketIntelligence/Integrations/ARIAPacketIntelligence/ARIAPacketIntelligence.py
  Packs/ARIAPacketIntelligence/Integrations/ARIAPacketIntelligence/ARIAPacketIntelligence.yml
  Packs/ARIAPacketIntelligence/Integrations/ARIAPacketIntelligence/ARIAPacketIntelligence_test.py
  Packs/ARIAPacketIntelligence/Integrations/ARIAPacketIntelligence/README.md
  Packs/ARIAPacketIntelligence/ReleaseNotes/2_0_0.md
  Packs/ARIAPacketIntelligence/TestPlaybooks/playbook-Aria-Packet-Intelligence-Test.yml
  Packs/ARIAPacketIntelligence/pack_metadata.json
Labels: Contribution, Partner

#10279 ConvertDateToUTC Script for ILM pack
  Packs/CommonScripts/ReleaseNotes/1_3_0.md
  Packs/CommonScripts/Scripts/ConvertDateToUTC/ConvertDateToUTC.py
  Packs/CommonScripts/Scripts/ConvertDateToUTC/ConvertDateToUTC.yml
  Packs/CommonScripts/Scripts/ConvertDateToUTC/README.md
  Packs/CommonScripts/pack_metadata.json
Labels: docs-approved, release-notes-only

#10280 skipped alienvault OTX
  Tests/conf.json
Labels: docs-approved

#10286 App-sync playbook image for ILM pack
  Images/IAM_-_App_Sync.png
Labels: docs-approved

#10292 Unmocking integrations that uses files
  Tests/conf.json
Labels: docs-approved

#10287 Making playbooks a single branch
  Packs/FireEyeHX/TestPlaybooks/playbook-FireEyeHX_Test.yml
  Packs/RsaNetWitnessPacketsAndLogs/TestPlaybooks/playbook-Test_RSA_PacketsAndLogs.yml
Labels: docs-approved

#10299 Github IAM - fixed an issue where disabling a user caused an error
  Packs/GitHub/Integrations/GitHub_IAM/GitHub_IAM.py
  Packs/GitHub/ReleaseNotes/1_1_3.md
  Packs/GitHub/pack_metadata.json
Labels: IAM, docs-approved

#10285 Application fields for ILM (IAM) pack
  Packs/CommonTypes/IncidentFields/incidentfield-applicationid.json
  Packs/CommonTypes/IncidentFields/incidentfield-applicationname.json
  Packs/CommonTypes/ReleaseNotes/2_6_0.md
  Packs/CommonTypes/pack_metadata.json
Labels: docs-approved, release-notes-only

#10150 Encoding for gp
  Packs/CommonPlaybooks/TestPlaybooks/playbook-GenericPollingTest.yml
  Packs/CommonPlaybooks/TestPlaybooks/script-GenericPollingDummyCommand.yml
  Packs/CommonScripts/ReleaseNotes/1_3_1.md
  Packs/CommonScripts/Scripts/ScheduleGenericPolling/Pipfile
  Packs/CommonScripts/Scripts/ScheduleGenericPolling/Pipfile.lock
  Packs/CommonScripts/Scripts/ScheduleGenericPolling/README.md
  Packs/CommonScripts/Scripts/ScheduleGenericPolling/ScheduleGenericPolling.py
  Packs/CommonScripts/Scripts/ScheduleGenericPolling/ScheduleGenericPolling.yml
  Packs/CommonScripts/Scripts/ScheduleGenericPolling/script-ScheduleGenericPolling_README.md
  Packs/CommonScripts/Scripts/script-ScheduleGenericPolling.yml
  Packs/CommonScripts/pack_metadata.json
  Tests/conf.json
  Tests/scripts/collect_tests_and_content_packs.py
Labels: bug, docs-approved, release-notes-only

#10146 Sophos Central
  Packs/SophosCentral/.pack-ignore
  Packs/SophosCentral/.secrets-ignore
  Packs/SophosCentral/Classifiers/classifier-SophosCentral.json
  Packs/SophosCentral/Classifiers/classifier-mapper-incoming-SophosCentral.json
  Packs/SophosCentral/IncidentTypes/incidenttype-SophosCentral_Incident.json
  Packs/SophosCentral/Integrations/SophosCentral/README.md
  Packs/SophosCentral/Integrations/SophosCentral/SophosCentral.py
  Packs/SophosCentral/Integrations/SophosCentral/SophosCentral.yml
  Packs/SophosCentral/Integrations/SophosCentral/SophosCentral_description.md
  Packs/SophosCentral/Integrations/SophosCentral/SophosCentral_image.png
  Packs/SophosCentral/Integrations/SophosCentral/SophosCentral_test.py
  Packs/SophosCentral/Integrations/SophosCentral/command_examples.txt
  Packs/SophosCentral/Integrations/SophosCentral/test_data/alert_action.json
  Packs/SophosCentral/Integrations/SophosCentral/test_data/alert_list.json
  Packs/SophosCentral/Integrations/SophosCentral/test_data/alert_single.json
  Packs/SophosCentral/Integrations/SophosCentral/test_data/allowed_item_list.json
  Packs/SophosCentral/Integrations/SophosCentral/test_data/allowed_item_single.json
  Packs/SophosCentral/Integrations/SophosCentral/test_data/auth_token.json
  Packs/SophosCentral/Integrations/SophosCentral/test_data/blocked_item_list.json
  Packs/SophosCentral/Integrations/SophosCentral/test_data/blocked_item_single.json
  Packs/SophosCentral/Integrations/SophosCentral/test_data/client_data.json
  Packs/SophosCentral/Integrations/SophosCentral/test_data/deleted.json
  Packs/SophosCentral/Integrations/SophosCentral/test_data/detected_exploit_list.json
  Packs/SophosCentral/Integrations/SophosCentral/test_data/detected_exploit_single.json
  Packs/SophosCentral/Integrations/SophosCentral/test_data/empty.json
  Packs/SophosCentral/Integrations/SophosCentral/test_data/endpoint_list.json
  Packs/SophosCentral/Integrations/SophosCentral/test_data/endpoint_scan.json
  Packs/SophosCentral/Integrations/SophosCentral/test_data/endpoint_tamper.json
  Packs/SophosCentral/Integrations/SophosCentral/test_data/exploit_mitigation_list.json
  Packs/SophosCentral/Integrations/SophosCentral/test_data/exploit_mitigation_single.json
  Packs/SophosCentral/Integrations/SophosCentral/test_data/scan_exclusion_list.json
  Packs/SophosCentral/Integrations/SophosCentral/test_data/scan_exclusion_single.json
  Packs/SophosCentral/Layouts/layoutscontainer-Sophos_Central_Event.json
  Packs/SophosCentral/README.md
  Packs/SophosCentral/TestPlaybooks/playbook-SophosCentral_Test.yml
  Packs/SophosCentral/pack_metadata.json
  Tests/conf.json
Labels: Contribution, docs-approved

#10300 SentinelOne v2 - use f-strings instead of concat in error processing
  Packs/SentinelOne/Integrations/SentinelOne-V2/SentinelOne-V2.py
  Packs/SentinelOne/Integrations/SentinelOne-V2/SentinelOne-V2.yml
  Packs/SentinelOne/ReleaseNotes/1_0_5.md
  Packs/SentinelOne/pack_metadata.json
Labels: docs-approved, release-notes-only

#10305 Feed azure
  Packs/FeedAzure/.secrets-ignore
  Packs/FeedAzure/Integrations/FeedAzure/FeedAzure.py
  Packs/FeedAzure/Integrations/FeedAzure/FeedAzure.yml
  Packs/FeedAzure/Integrations/FeedAzure/FeedAzure_test.py
  Packs/FeedAzure/Integrations/FeedAzure/README.md
  Packs/FeedAzure/ReleaseNotes/1_0_4.md
  Packs/FeedAzure/pack_metadata.json
Labels: bug, docs-approved

#10264 Adding file permissions for ConcentricAI integration.
  Packs/ConcentricAI/Integrations/ConcentricAI/ConcentricAI.py
  Packs/ConcentricAI/Integrations/ConcentricAI/ConcentricAI.yml
  Packs/ConcentricAI/Integrations/ConcentricAI/ConcentricAi_test.py
  Packs/ConcentricAI/Integrations/ConcentricAI/test_data/mock_file_permissions.json
  Packs/ConcentricAI/Playbooks/ConcentricAI_Demo.yml
  Packs/ConcentricAI/ReleaseNotes/1_1_0.md
  Packs/ConcentricAI/TestPlaybooks/ConcentricAI_Demo.yml
  Packs/ConcentricAI/pack_metadata.json
  Tests/conf.json
Labels: Contribution, Partner

#10293 Removing the use of basic_config to support python3.7
  Tests/scripts/utils/log_util.py
Labels: docs-approved

#9809 CloudConvert Integration
  Packs/Base/ReleaseNotes/1_4_3.md
  Packs/Base/Scripts/CommonServerPython/CommonServerPython.py
  Packs/Base/pack_metadata.json
  Packs/CloudConvert/.pack-ignore
  Packs/CloudConvert/.secrets-ignore
  Packs/CloudConvert/Integrations/CloudConvert/CloudConvert.py
  Packs/CloudConvert/Integrations/CloudConvert/CloudConvert.yml
  Packs/CloudConvert/Integrations/CloudConvert/CloudConvert_description.md
  Packs/CloudConvert/Integrations/CloudConvert/CloudConvert_image.png
  Packs/CloudConvert/Integrations/CloudConvert/CloudConvert_test.py
  Packs/CloudConvert/Integrations/CloudConvert/Pipfile
  Packs/CloudConvert/Integrations/CloudConvert/Pipfile.lock
  Packs/CloudConvert/Integrations/CloudConvert/README.md
  Packs/CloudConvert/Integrations/CloudConvert/test_data/check_status_bad_id_response.json
  Packs/CloudConvert/Integrations/CloudConvert/test_data/check_status_download_response.json
  Packs/CloudConvert/Integrations/CloudConvert/test_data/check_status_non_download_response.json
  Packs/CloudConvert/Integrations/CloudConvert/test_data/convert_invalid_format_or_id_response.json
  Packs/CloudConvert/Integrations/CloudConvert/test_data/convert_valid_format_and_id_response.json
  Packs/CloudConvert/Integrations/CloudConvert/test_data/download_invalid_id_response.json
  Packs/CloudConvert/Integrations/CloudConvert/test_data/download_valid_id_response.json
  Packs/CloudConvert/Integrations/CloudConvert/test_data/upload_entry_response.json
  Packs/CloudConvert/Integrations/CloudConvert/test_data/upload_url_bad_url_response.json
  Packs/CloudConvert/Integrations/CloudConvert/test_data/upload_url_response.json
  Packs/CloudConvert/Playbooks/CloudConvertConvertFile.yml
  Packs/CloudConvert/Playbooks/CloudConvertConvertFile_README.md
  Packs/CloudConvert/README.md
  Packs/CloudConvert/TestPlaybooks/CloudConvert-test.yml
  Packs/CloudConvert/pack_metadata.json
  Tests/conf.json
Labels: docs-approved

#10318 Hatching Triage - support info update
  Packs/HatchingTriage/pack_metadata.json
Labels: docs-approved

#10307 DateStringToISOFormat - handle no tz
  Packs/CommonScripts/ReleaseNotes/1_3_2.md
  Packs/CommonScripts/Scripts/DateStringToISOFormat/DateStringToISOFormat.py
  Packs/CommonScripts/Scripts/DateStringToISOFormat/DateStringToISOFormat.yml
  Packs/CommonScripts/Scripts/DateStringToISOFormat/DateStringToISOFormat_test.py
  Packs/CommonScripts/pack_metadata.json
Labels: bug, docs-approved, release-notes-only

#10321 bump 20.12.0
  .circleci/config.yml
Labels: docs-approved

#10319 marketplace services order
  Tests/Marketplace/copy_and_upload_packs.py
  Tests/Marketplace/marketplace_services.py
  Tests/Marketplace/upload_packs.py
  Tests/private_build/upload_packs_private.py
Labels: docs-approved

#8757 Cryptocurrency Formatting and Reputation Scripts
  Packs/Base/ReleaseNotes/1_4_4.md
  Packs/Base/Scripts/CommonServerPython/CommonServerPython.py
  Packs/Base/pack_metadata.json
  Packs/Cryptocurrency/.pack-ignore
  Packs/Cryptocurrency/.secrets-ignore
  Packs/Cryptocurrency/IndicatorFields/indicatorfield-Cryptocurrency_Address_Type.json
  Packs/Cryptocurrency/IndicatorTypes/reputation-cryptocurrency.json
  Packs/Cryptocurrency/Integrations/Cryptocurrency/Cryptocurrency.py
  Packs/Cryptocurrency/Integrations/Cryptocurrency/Cryptocurrency.yml
  Packs/Cryptocurrency/Integrations/Cryptocurrency/Cryptocurrency_description.md
  Packs/Cryptocurrency/Integrations/Cryptocurrency/Cryptocurrency_image.png
  Packs/Cryptocurrency/Integrations/Cryptocurrency/Cryptocurrency_test.py
  Packs/Cryptocurrency/Integrations/Cryptocurrency/Pipfile
  Packs/Cryptocurrency/Integrations/Cryptocurrency/Pipfile.lock
  Packs/Cryptocurrency/Integrations/Cryptocurrency/README.md
  Packs/Cryptocurrency/Integrations/Cryptocurrency/example.txt
  Packs/Cryptocurrency/Layouts/layout-indicatorsDetails-Cryptocurrency_Address-V2.json
  Packs/Cryptocurrency/Layouts/layoutscontainer-Cryptocurrency.json
  Packs/Cryptocurrency/README.md
  Packs/Cryptocurrency/Scripts/CryptoCurrenciesFormat/CryptoCurrenciesFormat.py
  Packs/Cryptocurrency/Scripts/CryptoCurrenciesFormat/CryptoCurrenciesFormat.yml
  Packs/Cryptocurrency/Scripts/CryptoCurrenciesFormat/CryptoCurrenciesFormat_test.py
  Packs/Cryptocurrency/Scripts/CryptoCurrenciesFormat/README.md
  Packs/Cryptocurrency/TestPlaybooks/Cryptocurrency_Test.yml
  Packs/Cryptocurrency/pack_metadata.json
  Tests/conf.json
Labels: docs-approved

#10228 Anomali match rebrand and DGA tag addition
  Packs/Anomali_Enterprise/Integrations/Anomali_Enterprise/Anomali_Enterprise.py
  Packs/Anomali_Enterprise/Integrations/Anomali_Enterprise/Anomali_Enterprise.yml
  Packs/Anomali_Enterprise/Integrations/Anomali_Enterprise/Anomali_Enterprise_image.png
  Packs/Anomali_Enterprise/Integrations/Anomali_Enterprise/Anomali_Enterprise_test.py
  Packs/Anomali_Enterprise/Integrations/Anomali_Enterprise/README.md
  Packs/Anomali_Enterprise/Playbooks/playbook-Anomali_Enterprise-Retro_Forensic_Search.yml
  Packs/Anomali_Enterprise/Playbooks/playbook-Anomali_Enterprise-Retro_Forensic_Search_README.md
  Packs/Anomali_Enterprise/ReleaseNotes/1_0_1.md
  Packs/Anomali_Enterprise/TestPlaybooks/playbook-Anomali_Match-Retro_Forensic_Search-test.yml
  Packs/Anomali_Enterprise/pack_metadata.json
  Packs/Base/ReleaseNotes/1_4_5.md
  Packs/Base/Scripts/CommonServerPython/CommonServerPython.py
  Packs/Base/pack_metadata.json
  Tests/conf.json
Labels: docs-approved, release-notes-only

#10323 Fixed a typo in tpb id in conf.json
  Tests/conf.json
Labels: docs-approved

#10327 Collect tests only in relevant files
  Tests/scripts/collect_tests_and_content_packs.py
Labels: docs-approved

#10240 Slack - add filtered_tags parameter
  Packs/Slack/Integrations/Slack/Slack.py
  Packs/Slack/Integrations/Slack/Slack.yml
  Packs/Slack/Integrations/Slack/Slack_test.py
  Packs/Slack/ReleaseNotes/1_3_8.md
  Packs/Slack/pack_metadata.json
Labels: docs-approved

#10248 New Script GetInstances
  Packs/ModulesManagement/.pack-ignore
  Packs/ModulesManagement/.secrets-ignore
  Packs/ModulesManagement/README.md
  Packs/ModulesManagement/Scripts/GetInstances/GetInstances.py
  Packs/ModulesManagement/Scripts/GetInstances/GetInstances.yml
  Packs/ModulesManagement/Scripts/GetInstances/GetInstances_test.py
  Packs/ModulesManagement/Scripts/GetInstances/README.md
  Packs/ModulesManagement/Scripts/GetInstances/test_data/modules_with_all_filters.json
  Packs/ModulesManagement/Scripts/GetInstances/test_data/modules_with_brand_filter.json
  Packs/ModulesManagement/Scripts/GetInstances/test_data/modules_with_is_enabled_filter.json
  Packs/ModulesManagement/Scripts/GetInstances/test_data/modules_with_system_filter.json
  Packs/ModulesManagement/Scripts/GetInstances/test_data/raw_modules.json
  Packs/ModulesManagement/pack_metadata.json
Labels: docs-approved

#10328 Added error handling to get email command response parsing
  Packs/ProofpointServerProtection/Integrations/ProofpointServerProtection/ProofpointServerProtection.py
  Packs/ProofpointServerProtection/ReleaseNotes/1_0_4.md
  Packs/ProofpointServerProtection/pack_metadata.json
Labels: docs-approved, release-notes-only

#10329 Contrib/aburt demisto aburt winrm integration
  Packs/WinRM/.pack-ignore
  Packs/WinRM/.secrets-ignore
  Packs/WinRM/Integrations/WindowsRemoteManagement/Pipfile
  Packs/WinRM/Integrations/WindowsRemoteManagement/Pipfile.lock
  Packs/WinRM/Integrations/WindowsRemoteManagement/README.md
  Packs/WinRM/Integrations/WindowsRemoteManagement/WindowsRemoteManagement.py
  Packs/WinRM/Integrations/WindowsRemoteManagement/WindowsRemoteManagement.yml
  Packs/WinRM/Integrations/WindowsRemoteManagement/WindowsRemoteManagement_image.png
  Packs/WinRM/README.md
  Packs/WinRM/pack_metadata.json
Labels: docs-approved

#10153 ciscofp fixed an issue in deploy-to-devices
  Packs/CiscoFirepower/Integrations/CiscoFirepower/CiscoFirepower.py
  Packs/CiscoFirepower/Integrations/CiscoFirepower/CiscoFirepower.yml
  Packs/CiscoFirepower/ReleaseNotes/1_0_1.md
  Packs/CiscoFirepower/pack_metadata.json
Labels: bug, docs-approved, release-notes-only

#8907 PrismaCloud (Redlock) Additional Commands
  Packs/PrismaCloud/Integrations/RedLock/README.md
  Packs/PrismaCloud/Integrations/RedLock/RedLock.py
  Packs/PrismaCloud/Integrations/RedLock/RedLock.yml
  Packs/PrismaCloud/Integrations/RedLock/command_examples.txt
  Packs/PrismaCloud/ReleaseNotes/1_5_0.md
  Packs/PrismaCloud/TestPlaybooks/playbook-RedLockTest.yml
  Packs/PrismaCloud/pack_metadata.json
Labels: Contribution, docs-approved

#10335 Output fix in GetDNSDomainDetails
  Packs/CommonScripts/ReleaseNotes/1_3_3.md
  Packs/CommonScripts/Scripts/GetDomainDNSDetails/GetDomainDNSDetails.yml
  Packs/CommonScripts/Scripts/GetDomainDNSDetails/README.md
  Packs/CommonScripts/pack_metadata.json
Labels: Contribution

#10326 CrowdstrikeFalcon - Fixed 404 error message for IOC's
  Packs/CrowdStrikeFalcon/Integrations/CrowdStrikeFalcon/CrowdStrikeFalcon.py
  Packs/CrowdStrikeFalcon/Integrations/CrowdStrikeFalcon/CrowdStrikeFalcon_test.py
  Packs/CrowdStrikeFalcon/ReleaseNotes/1_2_9.md
  Packs/CrowdStrikeFalcon/pack_metadata.json
Labels: bug, docs-approved, release-notes-only

#10336 Updated placeholder text
  Packs/StarterPack/Scripts/BaseScript/BaseScript.yml
Labels: docs-approved

#10344 Changed content to reference
  CONTRIBUTING.md
Labels: docs-approved

#10341 fixed from version boundaries using pack metadata
  Tests/scripts/collect_tests_and_content_packs.py
  Tests/scripts/infrastructure_tests/test_collect_tests_and_content_packs.py
Labels: docs-approved

#10162 Clean contribution from conf
  Tests/conf.json
Labels: docs-approved

#9576 Cortex xdr enhancement
  Packs/CortexXDR/.pack-ignore
  Packs/CortexXDR/Integrations/CortexXDRIR/CortexXDRIR.py
  Packs/CortexXDR/Integrations/CortexXDRIR/CortexXDRIR.yml
  Packs/CortexXDR/Integrations/CortexXDRIR/CortexXDRIR_description.md
  Packs/CortexXDR/Integrations/CortexXDRIR/CortexXDRIR_image.png
  Packs/CortexXDR/Integrations/CortexXDRIR/CortexXDRIR_test.py
  Packs/CortexXDR/Integrations/CortexXDRIR/README.md
  Packs/CortexXDR/Integrations/CortexXDRIR/command_examples
  Packs/CortexXDR/Integrations/CortexXDRIR/test_data/action_status_get.json
  Packs/CortexXDR/Integrations/CortexXDRIR/test_data/blacklist_files_failure.json
  Packs/CortexXDR/Integrations/CortexXDRIR/test_data/blacklist_whitelist_files_success.json
  Packs/CortexXDR/Integrations/CortexXDRIR/test_data/create_alerts.json
  Packs/CortexXDR/Integrations/CortexXDRIR/test_data/create_distribution.json
  Packs/CortexXDR/Integrations/CortexXDRIR/test_data/get_all_endpoints.json
  Packs/CortexXDR/Integrations/CortexXDRIR/test_data/get_audit_agent_report.json
  Packs/CortexXDR/Integrations/CortexXDRIR/test_data/get_audit_management_logs.json
  Packs/CortexXDR/Integrations/CortexXDRIR/test_data/get_distribution_status.json
  Packs/CortexXDR/Integrations/CortexXDRIR/test_data/get_distribution_url.json
  Packs/CortexXDR/Integrations/CortexXDRIR/test_data/get_distribution_versions.json
  Packs/CortexXDR/Integrations/CortexXDRIR/test_data/get_endpoint_violations.json
  Packs/CortexXDR/Integrations/CortexXDRIR/test_data/get_endpoints.json
  Packs/CortexXDR/Integrations/CortexXDRIR/test_data/get_incident_extra_data.json
  Packs/CortexXDR/Integrations/CortexXDRIR/test_data/get_incident_extra_data_host_id_array.json
  Packs/CortexXDR/Integrations/CortexXDRIR/test_data/get_incidents_list.json
  Packs/CortexXDR/Integrations/CortexXDRIR/test_data/get_quarantine_status.json
  Packs/CortexXDR/Integrations/CortexXDRIR/test_data/get_script_code.json
  Packs/CortexXDR/Integrations/CortexXDRIR/test_data/get_script_metadata.json
  Packs/CortexXDR/Integrations/CortexXDRIR/test_data/get_scripts.json
  Packs/CortexXDR/Integrations/CortexXDRIR/test_data/incident_example_from_extra_data_command.json
  Packs/CortexXDR/Integrations/CortexXDRIR/test_data/insert_cef_alerts.json
  Packs/CortexXDR/Integrations/CortexXDRIR/test_data/isolate_endpoint.json
  Packs/CortexXDR/Integrations/CortexXDRIR/test_data/quarantine_files.json
  Packs/CortexXDR/Integrations/CortexXDRIR/test_data/raw_fetched_incident.json
  Packs/CortexXDR/Integrations/CortexXDRIR/test_data/retrieve_file_details.json
  Packs/CortexXDR/Integrations/CortexXDRIR/test_data/scan_endpoints.json
  Packs/CortexXDR/Integrations/CortexXDRIR/test_data/unisolate_endpoint.json
  Packs/CortexXDR/Integrations/CortexXDRIR/test_data/update_incident.json
  Packs/CortexXDR/Playbooks/Cortex_XDR_-_Check_Action_Status.yml
  Packs/CortexXDR/Playbooks/Cortex_XDR_-_Check_Action_Status_README.md
  Packs/CortexXDR/Playbooks/Cortex_XDR_-_Retrieve_File_Playbook.yml
  Packs/CortexXDR/Playbooks/Cortex_XDR_-_Retrieve_File_Playbook_README.md
  Packs/CortexXDR/ReleaseNotes/2_5_0.md
  Packs/CortexXDR/TestPlaybooks/Test_XDR_Playbook.yml
  Packs/CortexXDR/doc_files/Cortex XDR - Check Action Status.png
  Packs/CortexXDR/doc_files/Cortex XDR - Retrieve File Playbook.png
  Packs/CortexXDR/pack_metadata.json
  Tests/conf.json
  package-lock.json
Labels: docs-approved

#10347 Added debug
  Tests/scripts/collect_tests_and_content_packs.py
  Tests/test_content.py
Labels: docs-approved

#10353 Splunk - handle notable raw fields where key equals value
  Packs/SplunkPy/Integrations/SplunkPy/SplunkPy.py
  Packs/SplunkPy/ReleaseNotes/1_2_6.md
  Packs/SplunkPy/pack_metadata.json
Labels: bug, docs-approved, release-notes-only

#10359 Add missing incident types for CrowdStrike Falcon and MCAS
  Packs/CrowdStrikeFalcon/IncidentTypes/incidenttype-CrowdStrikeFalconDetection.json
  Packs/CrowdStrikeFalcon/IncidentTypes/incidenttype-CrowdStrikeFalconIncident.json
  Packs/CrowdStrikeFalcon/ReleaseNotes/1_2_10.md
  Packs/CrowdStrikeFalcon/pack_metadata.json
  Packs/MicrosoftCloudAppSecurity/IncidentTypes/incidenttype-MicrosoftCASAlert.json
  Packs/MicrosoftCloudAppSecurity/ReleaseNotes/1_0_12.md
  Packs/MicrosoftCloudAppSecurity/pack_metadata.json
Labels: docs-approved

#10121 Lastline v2 - Added support for the account based authentication
  Packs/Lastline/Integrations/Lastline_v2/Lastline_v2.py
  Packs/Lastline/Integrations/Lastline_v2/Lastline_v2.yml
  Packs/Lastline/ReleaseNotes/1_0_3.md
  Packs/Lastline/pack_metadata.json
Labels: docs-approved, release-notes-only

#10331 skip the hooks while git rebase is running
  .hooks/pre-commit
Labels: docs-approved

#10267 PagerDuty - handle non ascii chars
  Packs/PagerDuty/Integrations/PagerDuty/PageDuty_test.py
  Packs/PagerDuty/Integrations/PagerDuty/PagerDuty.py
  Packs/PagerDuty/Integrations/PagerDuty/Pipfile
  Packs/PagerDuty/Integrations/PagerDuty/Pipfile.lock
  Packs/PagerDuty/ReleaseNotes/1_0_1.md
  Packs/PagerDuty/pack_metadata.json
Labels: bug, docs-approved, release-notes-only

#10358 CSV Feed API Module - improve condition for credentials provided
  Packs/ApiModules/Scripts/CSVFeedApiModule/CSVFeedApiModule.py
  Packs/FeedAlienVault/ReleaseNotes/1_0_8.md
  Packs/FeedAlienVault/pack_metadata.json
  Packs/FeedBambenekConsulting/ReleaseNotes/1_0_5.md
  Packs/FeedBambenekConsulting/pack_metadata.json
  Packs/FeedCSV/ReleaseNotes/1_0_6.md
  Packs/FeedCSV/pack_metadata.json
  Packs/FeedMajesticMillion/ReleaseNotes/1_0_1.md
  Packs/FeedMajesticMillion/pack_metadata.json
  Packs/Feedsslabusech/ReleaseNotes/1_0_5.md
  Packs/Feedsslabusech/pack_metadata.json
Labels: bug, docs-approved, release-notes-only

#10268 Symantec Blue Coat - open file by path in the upload-file command
  Packs/SymantecBlueCoatMalwareAnalysis/Integrations/SymantecBlueCoatMalwareAnalysis/SymantecBlueCoatMalwareAnalysis.py
  Packs/SymantecBlueCoatMalwareAnalysis/ReleaseNotes/1_0_1.md
  Packs/SymantecBlueCoatMalwareAnalysis/pack_metadata.json
Labels: bug, docs-approved, release-notes-only

#10255 Prisma Compute - fix camel_case_transformer failure for non string input
  Packs/PrismaCloudCompute/Integrations/PaloAltoNetworks_PrismaCloudCompute/PaloAltoNetworks_PrismaCloudCompute.py
  Packs/PrismaCloudCompute/Integrations/PaloAltoNetworks_PrismaCloudCompute/PaloAltoNetworks_PrismaCloudCompute.yml
  Packs/PrismaCloudCompute/Integrations/PaloAltoNetworks_PrismaCloudCompute/PaloAltoNetworks_PrismaCloudCompute_test.py
  Packs/PrismaCloudCompute/ReleaseNotes/1_0_5.md
  Packs/PrismaCloudCompute/pack_metadata.json
Labels: bug, docs-approved, release-notes-only

#10354 Export Indicators - pop instead of del indicator value
  Packs/ExportIndicators/Integrations/ExportIndicators/ExportIndicators.py
  Packs/ExportIndicators/Integrations/ExportIndicators/ExportIndicators.yml
  Packs/ExportIndicators/ReleaseNotes/1_0_1.md
  Packs/ExportIndicators/pack_metadata.json
Labels: bug, docs-approved, release-notes-only

#10250 back off strategy implementation
  Packs/CortexDataLake/Integrations/CortexDataLake/CortexDataLake.py
  Packs/CortexDataLake/Integrations/CortexDataLake/CortexDataLake.yml
  Packs/CortexDataLake/Integrations/CortexDataLake/CortexDataLake_description.md
  Packs/CortexDataLake/Integrations/CortexDataLake/CortexDataLake_test.py
  Packs/CortexDataLake/Integrations/CortexDataLake/README.md
  Packs/CortexDataLake/Integrations/CortexDataLake/command_examples
  Packs/CortexDataLake/ReleaseNotes/1_3_0.md
  Packs/CortexDataLake/pack_metadata.json
Labels: bug, docs-approved, release-notes-only

#10006 Threatstream md5 bug
  Packs/Anomali_ThreatStream/.secrets-ignore
  Packs/Anomali_ThreatStream/Integrations/Anomali_ThreatStream_v2/Anomali_ThreatStream_v2.py
  Packs/Anomali_ThreatStream/Integrations/Anomali_ThreatStream_v2/Anomali_ThreatStream_v2.yml
  Packs/Anomali_ThreatStream/Integrations/Anomali_ThreatStream_v2/Anomali_ThreatStream_v2_test.py
  Packs/Anomali_ThreatStream/Integrations/Anomali_ThreatStream_v2/README.md
  Packs/Anomali_ThreatStream/Integrations/Anomali_ThreatStream_v2/test_data/file_256_context.json
  Packs/Anomali_ThreatStream/Integrations/Anomali_ThreatStream_v2/test_data/file_256_response.json
  Packs/Anomali_ThreatStream/Integrations/Anomali_ThreatStream_v2/test_data/file_512_context.json
  Packs/Anomali_ThreatStream/Integrations/Anomali_ThreatStream_v2/test_data/file_512_response.json
  Packs/Anomali_ThreatStream/ReleaseNotes/1_1_0.md
  Packs/Anomali_ThreatStream/pack_metadata.json
Labels: bug, docs-approved, release-notes-only

#9431 ServiceNow CMDB
  Packs/ServiceNow/Integrations/ServiceNow_CMDB/Pipfile
  Packs/ServiceNow/Integrations/ServiceNow_CMDB/Pipfile.lock
  Packs/ServiceNow/Integrations/ServiceNow_CMDB/README.md
  Packs/ServiceNow/Integrations/ServiceNow_CMDB/ServiceNow_CMDB.py
  Packs/ServiceNow/Integrations/ServiceNow_CMDB/ServiceNow_CMDB.yml
  Packs/ServiceNow/Integrations/ServiceNow_CMDB/ServiceNow_CMDB_description.md
  Packs/ServiceNow/Integrations/ServiceNow_CMDB/ServiceNow_CMDB_image.png
  Packs/ServiceNow/Integrations/ServiceNow_CMDB/ServiceNow_CMDB_test.py
  Packs/ServiceNow/Integrations/ServiceNow_CMDB/command_examples.txt
  Packs/ServiceNow/Integrations/ServiceNow_CMDB/test_data/response_constants.py
  Packs/ServiceNow/Integrations/ServiceNow_CMDB/test_data/result_constants.py
  Packs/ServiceNow/ReleaseNotes/2_1_0.md
  Packs/ServiceNow/TestPlaybooks/playbook-ServiceNow_CMDB_OAuth_Test.yml
  Packs/ServiceNow/TestPlaybooks/playbook-ServiceNow_CMDB_Test.yml
  Packs/ServiceNow/pack_metadata.json
  Tests/conf.json
Labels: docs-approved

#10138 Upload Flow - Improve Slack Data
  Tests/Marketplace/Tests/copy_and_upload_packs_test.py
  Tests/Marketplace/Tests/marketplace_services_test.py
  Tests/Marketplace/copy_and_upload_packs.py
  Tests/Marketplace/marketplace_services.py
  Tests/Marketplace/upload_packs.py
  Tests/scripts/slack_notifier.py
Labels: docs-approved

#10360 rm mirror error fields from the close form
  Packs/CommonTypes/IncidentFields/incidentfield-IncomingMirrorError.json
  Packs/CommonTypes/IncidentFields/incidentfield-OutgoingMirrorError.json
  Packs/CommonTypes/ReleaseNotes/2_6_1.md
  Packs/CommonTypes/pack_metadata.json
Labels: docs-approved, release-notes-only

#10311 Making infoblox playbook a single branch to support proxy
  Packs/Infoblox/TestPlaybooks/playbook-Infoblox_Test.yml
Labels: docs-approved

#10310 Unmocking integrations that uses files
  Tests/conf.json
Labels: docs-approved

#10298 Validating requirements files are updated
  .circleci/config.yml
  Tests/scripts/is_file_up_to_date.sh
Labels: docs-approved

#10361 updating npm
  package-lock.json
  package.json
Labels: docs-approved

#10098 Xdr ratelimit 2
  Packs/CortexXDR/Classifiers/classifier-PaloAltoNetworks_CortexXDR_5_9_9.json
  Packs/CortexXDR/Classifiers/classifier-mapper-incoming-PaloAltoNetworks_CortexXDR.json
  Packs/CortexXDR/IncidentFields/XDR_Last_Mirrored_In_Time.json
  Packs/CortexXDR/IncidentFields/XDR_Manual_Severity.json
  Packs/CortexXDR/IncidentFields/XDR_Modification_time.json
  Packs/CortexXDR/Integrations/CortexXDRIR/CortexXDRIR.py
  Packs/CortexXDR/Integrations/CortexXDRIR/CortexXDRIR.yml
  Packs/CortexXDR/Integrations/CortexXDRIR/CortexXDRIR_test.py
  Packs/CortexXDR/ReleaseNotes/2_6_0.md
  Packs/CortexXDR/Scripts/XDRSyncScript/XDRSyncScript.py
  Packs/CortexXDR/Scripts/XDRSyncScript/XDRSyncScript.yml
  Packs/CortexXDR/Scripts/XDRSyncScript/XDRSyncScript_test.py
  Packs/CortexXDR/Scripts/XDRSyncScript_5_9_9/XDRSyncScript_5_9_9.py
  Packs/CortexXDR/Scripts/XDRSyncScript_5_9_9/XDRSyncScript_5_9_9.yml
  Packs/CortexXDR/Scripts/XDRSyncScript_5_9_9/XDRSyncScript_5_9_9_test.py
  Packs/CortexXDR/pack_metadata.json
  Tests/demistomock/demistomock.py
Labels: docs-approved

#10350 Emptied the empty tags
  Packs/CommonTypes/IndicatorFields/incidentfield-tagsTagsType.json
  Packs/CommonTypes/ReleaseNotes/2_6_2.md
  Packs/CommonTypes/pack_metadata.json
Labels: docs-approved

#10017 Added fetch incidents capability for Symantec advanced threat protection
  Packs/Symantec_Advanced_Threat_Protection/Integrations/integration-Symantec_Advanced_Threat_Protection.yml
  Packs/Symantec_Advanced_Threat_Protection/ReleaseNotes/1_1_0.md
  Packs/Symantec_Advanced_Threat_Protection/pack_metadata.json
Labels: Contribution, docs-approved

#10060 fixed type error with demisto args passed in
  Packs/Logzio/Integrations/Logzio/Logzio.py
  Packs/Logzio/ReleaseNotes/1_1_2.md
  Packs/Logzio/ReleaseNotes/1_1_3.md
  Packs/Logzio/pack_metadata.json
Labels: Contribution

#10362 Prepare private ID set for merge - script
  Tests/Marketplace/Tests/prepare_private_id_set_for_merge_test.py
  Tests/Marketplace/prepare_private_id_set_for_merge.py
Labels: docs-approved

#10315 Add Use Case tag to pack metadata
  Tests/Marketplace/Tests/marketplace_services_test.py
  Tests/Marketplace/marketplace_services.py
Labels: docs-approved

#10373 Remedy On Demand README
  Packs/Remedy-On-Demand/Integrations/integration-Remedy-On-Demand_README.md
Labels: docs-approved

#10369 Single branch playbook
  Packs/EWS/TestPlaybooks/playbook-EWS_Public_Folders_Test.yml
  Packs/cisco-ise/TestPlaybooks/playbook-cisco-ise-test-playbook.yml
Labels: docs-approved

#10324 Replacing server names with numeric values
  .circleci/config.yml
  Tests/Marketplace/configure_and_install_packs.py
  Tests/configure_and_test_integration_instances.py
  Tests/instance_notifier.py
  Tests/scripts/collect_tests_and_content_packs.py
  Tests/scripts/infrastructure_tests/test_collect_tests_and_content_packs.py
  Tests/scripts/infrastructure_tests/tests_data/mock_id_set.json
Labels: docs-approved

#10374 update schema for XDR_Modification_time.json
  Packs/CortexXDR/IncidentFields/XDR_Modification_time.json
  Packs/CortexXDR/ReleaseNotes/2_6_2.md
  Packs/CortexXDR/pack_metadata.json
Labels: docs-approved

#10379 Rasterize test failure fix
  Packs/rasterize/TestPlaybooks/playbook-Rasterize_Test.yml
  Tests/conf.json
Labels: docs-approved

#10389 TrendMicro Apex - update trend micro apex central version
  Packs/TrendMicroApex/Integrations/TrendMicroApex/README.md
Labels: docs-approved

#9892 Security and compliance
  Packs/Base/ReleaseNotes/1_5_0.md
  Packs/Base/Scripts/CommonServerPowerShell/CommonServerPowerShell.ps1
  Packs/Base/pack_metadata.json
  Packs/EWS/Integrations/SecurityAndCompliance/README.md
  Packs/EWS/Integrations/SecurityAndCompliance/SecurityAndCompliance.Tests.ps1
  Packs/EWS/Integrations/SecurityAndCompliance/SecurityAndCompliance.ps1
  Packs/EWS/Integrations/SecurityAndCompliance/SecurityAndCompliance.yml
  Packs/EWS/Integrations/SecurityAndCompliance/SecurityAndCompliance_description.md
  Packs/EWS/Integrations/SecurityAndCompliance/SecurityAndCompliance_image.png
  Packs/EWS/Playbooks/playbook-O365-SecurityAndCompliance-Search.yml
  Packs/EWS/Playbooks/playbook-O365-SecurityAndCompliance-SearchAction-Delete.yml
  Packs/EWS/Playbooks/playbook-O365-SecurityAndCompliance-SearchAction-Delete_README.md
  Packs/EWS/Playbooks/playbook-O365-SecurityAndCompliance-SearchAction-Preview.yml
  Packs/EWS/Playbooks/playbook-O365-SecurityAndCompliance-SearchAction-Preview_README.md
  Packs/EWS/Playbooks/playbook-O365-SecurityAndCompliance-SearchAndDelete.yml
  Packs/EWS/Playbooks/playbook-O365-SecurityAndCompliance-SearchAndDelete_README.md
  Packs/EWS/Playbooks/playbook-O365-SecurityAndCompliance-Search_README.md
  Packs/EWS/ReleaseNotes/1_5_0.md
  Packs/EWS/TestPlaybooks/playbook-O365-SecurityAndCompliance-Test.yml
  Packs/EWS/doc_imgs/O365-SecurityAndCompliance-Search.png
  Packs/EWS/doc_imgs/O365-SecurityAndCompliance-SearchAction-Delete.png
  Packs/EWS/doc_imgs/O365-SecurityAndCompliance-SearchAction-Preview.png
  Packs/EWS/doc_imgs/O365-SecurityAndCompliance-SearchAndDelete.png
  Packs/EWS/doc_imgs/security-and-compliance-edit-1.png
  Packs/EWS/doc_imgs/security-and-compliance-edit-2.png
  Packs/EWS/doc_imgs/security-and-compliance-edit-3.png
  Packs/EWS/doc_imgs/security-and-compliance-roles.png
  Packs/EWS/doc_imgs/security-and-compliance-side-menu.png
  Packs/EWS/pack_metadata.json
  Tests/conf.json
Labels: docs-approved

#10382 Dependencies step - Raise exception after logging
  Tests/Marketplace/packs_dependencies.py
Labels: docs-approved

#10387 Proofpoint TAP - add proofpoint tap version
  Packs/ProofpointTAP/Integrations/ProofpointTAP_v2/README.md
Labels: docs-approved

#10054 iDefense Feed
  Packs/ApiModules/Scripts/JSONFeedApiModule/JSONFeedApiModule.py
  Packs/ApiModules/Scripts/JSONFeedApiModule/JSONFeedApiModule.yml
  Packs/FeedAWS/ReleaseNotes/1_1_0.md
  Packs/FeedAWS/pack_metadata.json
  Packs/FeedFastly/ReleaseNotes/1_1_0.md
  Packs/FeedFastly/pack_metadata.json
  Packs/FeedJSON/Integrations/FeedJSON/FeedJSON.py
  Packs/FeedJSON/Integrations/FeedJSON/FeedJSON.yml
  Packs/FeedJSON/ReleaseNotes/1_1_0.md
  Packs/FeedJSON/pack_metadata.json
  Packs/iDefense/Integrations/FeediDefense/FeediDefense.py
  Packs/iDefense/Integrations/FeediDefense/FeediDefense.yml
  Packs/iDefense/Integrations/FeediDefense/FeediDefense_description.md
  Packs/iDefense/Integrations/FeediDefense/FeediDefense_image.png
  Packs/iDefense/Integrations/FeediDefense/FeediDefense_test.py
  Packs/iDefense/Integrations/FeediDefense/README.md
  Packs/iDefense/Integrations/iDefense_v2/iDefense_v2.yml
  Packs/iDefense/ReleaseNotes/3_0_0.md
  Packs/iDefense/TestPlaybooks/Feed_iDefense_Test.yml
  Packs/iDefense/pack_metadata.json
  Tests/conf.json
Labels: docs-approved

#10372 Unmocking integration with random uuid
  Tests/conf.json
Labels: docs-approved

#10398 In case of non nightly build - logs can be executed in real time
  Tests/scripts/utils/log_util.py
  Tests/test_content.py
Labels: docs-approved

#10392 LogRhythmRest - safe get of content type header
  Packs/LogRhythmRest/Integrations/LogRhythmRest/LogRhythmRest.py
  Packs/LogRhythmRest/ReleaseNotes/1_0_2.md
  Packs/LogRhythmRest/pack_metadata.json
Labels: docs-approved, release-notes-only

#10375 Slack: fixed loads of non-strict json in blocks
  Packs/Slack/Integrations/Slack/Slack.py
  Packs/Slack/Integrations/Slack/Slack_test.py
  Packs/Slack/ReleaseNotes/1_3_9.md
  Packs/Slack/pack_metadata.json
Labels: bug, docs-approved, release-notes-only

#10400 sdk release
  dev-requirements-py3.txt
Labels: docs-approved

#10401 Trend Micro Apex - add hotfix to version
  Packs/TrendMicroApex/Integrations/TrendMicroApex/README.md
Labels: docs-approved

#10273 Add usernames field to QRadar layout
  Packs/QRadar/Layouts/layoutscontainer-Qradar_Generic.json
  Packs/QRadar/ReleaseNotes/1_2_3.md
  Packs/QRadar/pack_metadata.json
Labels: docs-approved

#9992 Add index test
  .circleci/config.yml
  Tests/Marketplace/mandatory_premium_packs.json
  Tests/scripts/validate_index.py
  Tests/scripts/validate_premium_packs.py
  Tests/scripts/validate_premium_packs.sh
Labels: docs-approved

#10399 Adding proxy context manager
  Tests/mock_server.py
  Tests/test_content.py
Labels: docs-approved

#10274 Fixing XDR dependencies
  Packs/CortexXDR/Playbooks/Cortex_XDR_Alerts_Handling.yml
  Packs/CortexXDR/Playbooks/Cortex_XDR_incident_handling_v2.yml
  Packs/CortexXDR/Playbooks/Cortex_XDR_incident_handling_v3.yml
  Packs/CortexXDR/ReleaseNotes/2_6_3.md
  Packs/CortexXDR/pack_metadata.json
Labels: docs-approved

#10103 Tripwire
  Packs/CommonTypes/IncidentFields/incidentfield-Device_Id.json
  Packs/CommonTypes/IncidentFields/incidentfield-Policy_Description.json
  Packs/CommonTypes/IncidentFields/incidentfield-Policy_ID.json
  Packs/CommonTypes/IncidentFields/incidentfield-SHA1.json
  Packs/CommonTypes/IncidentFields/incidentfield-SHA512.json
  Packs/CommonTypes/ReleaseNotes/2_7_0.md
  Packs/CommonTypes/pack_metadata.json
  Packs/Tripwire/.pack-ignore
  Packs/Tripwire/.secrets-ignore
  Packs/Tripwire/Classifiers/classifier-Tripwire.json
  Packs/Tripwire/Classifiers/classifier-Tripwire_5_9_9.json
  Packs/Tripwire/Classifiers/classifier-mapper-incoming-Tripwire.json
  Packs/Tripwire/IncidentTypes/incidenttype-Tripwire_File_Change.json
  Packs/Tripwire/Integrations/Tripwire/Pipfile
  Packs/Tripwire/Integrations/Tripwire/Pipfile.lock
  Packs/Tripwire/Integrations/Tripwire/README.md
  Packs/Tripwire/Integrations/Tripwire/Tripwire.py
  Packs/Tripwire/Integrations/Tripwire/Tripwire.yml
  Packs/Tripwire/Integrations/Tripwire/Tripwire_description.md
  Packs/Tripwire/Integrations/Tripwire/Tripwire_image.png
  Packs/Tripwire/Integrations/Tripwire/Tripwire_test.py
  Packs/Tripwire/Integrations/Tripwire/test_data/raw_response.py
  Packs/Tripwire/Layouts/layout-details-Tripwire_incident.json
  Packs/Tripwire/Layouts/layoutscontainer-Tripwire_incident.json
  Packs/Tripwire/Playbooks/playbook-Tripwire_Incident_IP_Enrichment.yml
  Packs/Tripwire/README.md
  Packs/Tripwire/TestPlaybooks/TestplaybookTripwire.yml
  Packs/Tripwire/pack_metadata.json
  Tests/conf.json
Labels: docs-approved

#10408 Nozomi - set support level to partner and certify
  Packs/NozomiNetworks/pack_metadata.json
Labels: docs-approved

#10411 xMatters Marketplace update
  Packs/XMatters/README.md
  Packs/XMatters/pack_metadata.json
Labels: Contribution, ready-for-instance-test

#10417 Barracude indicator
  Packs/Barracuda/Integrations/BarracudaReputationBlockListBRBL/BarracudaReputationBlockListBRBL.py
  Packs/Barracuda/Integrations/BarracudaReputationBlockListBRBL/BarracudaReputationBlockListBRBL.yml
  Packs/Barracuda/ReleaseNotes/1_0_1.md
  Packs/Barracuda/pack_metadata.json
Labels: docs-approved

#10420 spamcop ip cmd, indicaotr and outputs
  Packs/Spamcop/Integrations/Spamcop/Spamcop.py
  Packs/Spamcop/Integrations/Spamcop/Spamcop.yml
  Packs/Spamcop/ReleaseNotes/1_0_1.md
  Packs/Spamcop/pack_metadata.json
Labels: docs-approved

#9929 Replace hunting sub-playbook in "Cortex XDR - Incident Handling" playbooks (v2+v3)
  Packs/CortexXDR/Playbooks/Cortex_XDR_incident_handling_v2.yml
  Packs/CortexXDR/Playbooks/Cortex_XDR_incident_handling_v2_README.md
  Packs/CortexXDR/Playbooks/Cortex_XDR_incident_handling_v3.yml
  Packs/CortexXDR/Playbooks/Cortex_XDR_incident_handling_v3_README.md
  Packs/CortexXDR/ReleaseNotes/2_6_4.md
  Packs/CortexXDR/doc_files/Cortex_XDR_incident_handling_v2.png
  Packs/CortexXDR/doc_files/Cortex_XDR_incident_handling_v3.png
  Packs/CortexXDR/pack_metadata.json
Labels: docs-approved

#10421 Synapse - Breaking Change ip, url, domain and file commands multiple indicator and outputs
  Packs/Synapse/Integrations/Synapse/Synapse.py
  Packs/Synapse/Integrations/Synapse/Synapse.yml
  Packs/Synapse/ReleaseNotes/1_0_1.md
  Packs/Synapse/pack_metadata.json
Labels: docs-approved

#10352 Public DNS Feed
  Packs/FeedPublicDNS/.pack-ignore
  Packs/FeedPublicDNS/.secrets-ignore
  Packs/FeedPublicDNS/Integrations/FeedPublicDNS/FeedPublicDNS.py
  Packs/FeedPublicDNS/Integrations/FeedPublicDNS/FeedPublicDNS.yml
  Packs/FeedPublicDNS/Integrations/FeedPublicDNS/FeedPublicDNS_image.png
  Packs/FeedPublicDNS/Integrations/FeedPublicDNS/README.md
  Packs/FeedPublicDNS/TestPlaybooks/playbook-Public_DNS_Feed-Test.yml
  Packs/FeedPublicDNS/pack_metadata.json
  Tests/conf.json
Labels: docs-approved

#10422 Pulsedive - **Breaking Change** ip, url and domain commands changed t…
  Packs/Pulsedive/Integrations/Pulsedive/Pulsedive.py
  Packs/Pulsedive/Integrations/Pulsedive/Pulsedive.yml
  Packs/Pulsedive/ReleaseNotes/1_0_1.md
  Packs/Pulsedive/pack_metadata.json
Labels: docs-approved

#10418 PhishTank v2 url cmd multiple commandresults
  Packs/PhishTank/Integrations/PhishTankV2/PhishTankV2.py
  Packs/PhishTank/Integrations/PhishTankV2/PhishTankV2_test.py
  Packs/PhishTank/ReleaseNotes/2_0_2.md
  Packs/PhishTank/pack_metadata.json
Labels: docs-approved

#10413 Created failing ut
  Packs/Base/ReleaseNotes/1_5_1.md
  Packs/Base/Scripts/CommonServerPython/CommonServerPython.py
  Packs/Base/Scripts/CommonServerPython/CommonServerPython_test.py
  Packs/Base/pack_metadata.json
Labels: bug, docs-approved, release-notes-only

#9916 Dedup generic v3
  Packs/CommonPlaybooks/Playbooks/playbook-Dedup_-_Generic_v2.yml
  Packs/CommonPlaybooks/Playbooks/playbook-Dedup_-_Generic_v2_README.md
  Packs/CommonPlaybooks/Playbooks/playbook-Dedup_-_Generic_v3.yml
  Packs/CommonPlaybooks/Playbooks/playbook-Dedup_-_Generic_v3_README.md
  Packs/CommonPlaybooks/ReleaseNotes/1_8_6.md
  Packs/CommonPlaybooks/doc_files/Dedup_-_Generic_v3.png
  Packs/CommonPlaybooks/pack_metadata.json
  Packs/CommonScripts/ReleaseNotes/1_3_4.md
  Packs/CommonScripts/Scripts/GetDuplicatesMlv2/GetDuplicatesMlv2.yml
  Packs/CommonScripts/pack_metadata.json
Labels: docs-approved

#10436 XMCyber Integration - return multiple entries (entry per indicator) instead of a single entry
  Packs/XMCyber/Integrations/XMCyberIntegration/XMCyberIntegration.py
  Packs/XMCyber/Integrations/XMCyberIntegration/XMCyberIntegration_test.py
  Packs/XMCyber/ReleaseNotes/1_0_2.md
  Packs/XMCyber/pack_metadata.json
Labels: docs-approved, release-notes-only
