Repository demisto/content, pull requests merged in 2020-08, with the labels that each got.

#8219 Pcap additions
  Packs/PcapAnalysis/.pack-ignore
  Packs/PcapAnalysis/.secrets-ignore
  Packs/PcapAnalysis/Playbooks/playbook-PCAP_Analysis.yml
  Packs/PcapAnalysis/Playbooks/playbook-PCAP_Analysis_README.md
  Packs/PcapAnalysis/Playbooks/playbook-PCAP_File_Carving.yml
  Packs/PcapAnalysis/Playbooks/playbook-PCAP_File_Carving_README.md
  Packs/PcapAnalysis/Playbooks/playbook-PCAP_Parsing_And_Indicator_Enrichment.yml
  Packs/PcapAnalysis/Playbooks/playbook-PCAP_Parsing_And_Indicator_Enrichment_README.md
  Packs/PcapAnalysis/ReleaseNotes/2_3_0.md
  Packs/PcapAnalysis/Scripts/PcapMinerV2/TestData/pcap_smb_http.pcapng
  Packs/PcapAnalysis/TestPlaybooks/PCAP_Analysis_Test.yml
  Packs/PcapAnalysis/doc_files/PCAP_Analysis.png
  Packs/PcapAnalysis/doc_files/PCAP_File_Carving.png
  Packs/PcapAnalysis/doc_files/PCAP_Parsing_And_Indicator_Enrichment.png
  Packs/PcapAnalysis/pack_metadata.json
  Tests/conf.json
Labels: docs-approved

#8310 Process Email Generic+Core - continueonerror for SetGridField
  Packs/Phishing/Playbooks/Process_Email_-_Core.yml
  Packs/Phishing/Playbooks/Process_Email_-_Generic.yml
  Packs/Phishing/ReleaseNotes/1_8_0.md
  Packs/Phishing/pack_metadata.json
Labels: docs-approved

#8308 Safe breach feed tags
  Packs/SafeBreach/Integrations/SafeBreach_v2/SafeBreach_v2.py
  Packs/SafeBreach/Integrations/SafeBreach_v2/SafeBreach_v2.yml
  Packs/SafeBreach/Integrations/SafeBreach_v2/SafeBreach_v2_test.py
  Packs/SafeBreach/ReleaseNotes/1_0_4.md
  Packs/SafeBreach/pack_metadata.json
Labels: docs-approved

#8311 unifiedFileRep - Fixed an issue where long hashes where extracted as …
  Packs/Base/TestPlaybooks/playbook-Indicators-reputation-.json-Test.yml
  Packs/Base/TestPlaybooks/playbook-reputation.json-Test.yml
  Packs/CommonTypes/IndicatorTypes/reputation-file.json
  Packs/CommonTypes/ReleaseNotes/1_7_2.md
  Packs/CommonTypes/pack_metadata.json
  Packs/NonSupported/IndicatorTypes/reputation-file_5_4_9.json
  Packs/NonSupported/pack_metadata.json
Labels: docs-approved

#8315 demistomock - convert docstring to google style
  Tests/demistomock/demistomock.py
Labels: docs-approved

#8205 ServiceNow v2 - add sysparm_display_value to update/create commands
  Packs/ServiceNow/Integrations/ServiceNowv2/README.md
  Packs/ServiceNow/Integrations/ServiceNowv2/ServiceNowv2.py
  Packs/ServiceNow/Integrations/ServiceNowv2/ServiceNowv2.yml
  Packs/ServiceNow/Integrations/ServiceNowv2/ServiceNowv2_test.py
  Packs/ServiceNow/ReleaseNotes/1_1_7.md
  Packs/ServiceNow/pack_metadata.json
Labels: docs-approved

#8107 Initial PR for MapValuesTransformer
  Packs/CommonScripts/Scripts/MapValuesTransformer/MapValuesTransformer.py
  Packs/CommonScripts/Scripts/MapValuesTransformer/MapValuesTransformer.yml
  Packs/CommonScripts/Scripts/MapValuesTransformer/MapValuesTransformer_test.py
  Packs/CommonScripts/Scripts/MapValuesTransformer/README.md
Labels: Contribution, docs-approved

#8319 deleted sixgill darkfeed pack
  Packs/Sixgill-DeepInsights/.pack-ignore
  Packs/Sixgill-DeepInsights/.secrets-ignore
  Packs/Sixgill-DeepInsights/CHANGELOG.md
  Packs/Sixgill-DeepInsights/Classifiers/classifier-Sixgill-DeepInsights.json
  Packs/Sixgill-DeepInsights/Classifiers/classifier-Sixgill-DeepInsights_5_9_9.json
  Packs/Sixgill-DeepInsights/Classifiers/classifier-Sixgill-DeepInsights_5_9_9_CHANGELOG.md
  Packs/Sixgill-DeepInsights/Classifiers/classifier-mapper-incoming-Sixgill-DeepInsights.json
  Packs/Sixgill-DeepInsights/IncidentFields/Sixgill_Alert_ID.json
  Packs/Sixgill-DeepInsights/IncidentFields/Sixgill_Alert_ID_CHANGELOG.md
  Packs/Sixgill-DeepInsights/IncidentFields/Sixgill_Content.json
  Packs/Sixgill-DeepInsights/IncidentFields/Sixgill_Content_CHANGELOG.md
  Packs/Sixgill-DeepInsights/IncidentFields/Sixgill_Threat_Level.json
  Packs/Sixgill-DeepInsights/IncidentFields/Sixgill_Threat_Level_CHANGELOG.md
  Packs/Sixgill-DeepInsights/IncidentFields/Sixgill_Threat_Type.json
  Packs/Sixgill-DeepInsights/IncidentFields/Sixgill_Threat_Type_CHANGELOG.md
  Packs/Sixgill-DeepInsights/IncidentTypes/Sixgill_Threat.json
  Packs/Sixgill-DeepInsights/Integrations/Sixgill/CHANGELOG.md
  Packs/Sixgill-DeepInsights/Integrations/Sixgill/README.md
  Packs/Sixgill-DeepInsights/Integrations/Sixgill/Sixgill.py
  Packs/Sixgill-DeepInsights/Integrations/Sixgill/Sixgill.yml
  Packs/Sixgill-DeepInsights/Integrations/Sixgill/Sixgill_description.md
  Packs/Sixgill-DeepInsights/Integrations/Sixgill/Sixgill_image.png
  Packs/Sixgill-DeepInsights/Integrations/Sixgill/Sixgill_test.py
  Packs/Sixgill-DeepInsights/Layouts/CHANGELOG.md
  Packs/Sixgill-DeepInsights/Layouts/layout-details-Sixgill_Threat-V2.json
  Packs/Sixgill-DeepInsights/Layouts/layout-details-Sixgill_Threat-V2_CHANGELOG.md
  Packs/Sixgill-DeepInsights/Layouts/layoutscontainer-Sixgill_Threat.json
  Packs/Sixgill-DeepInsights/README.md
  Packs/Sixgill-DeepInsights/ReleaseNotes/1_0_1.md
  Packs/Sixgill-DeepInsights/ReleaseNotes/1_0_2.md
  Packs/Sixgill-DeepInsights/ReleaseNotes/1_0_3.md
  Packs/Sixgill-DeepInsights/ReleaseNotes/1_0_4.md
  Packs/Sixgill-DeepInsights/TestPlaybooks/playbook-Sixgill-Test.yml
  Packs/Sixgill-DeepInsights/pack_metadata.json
  Tests/conf.json
Labels: docs-approved

#8294 Calculate entropy fix
  Packs/CommonScripts/ReleaseNotes/1_2_21.md
  Packs/CommonScripts/Scripts/CalculateEntropy/CalculateEntropy.yml
  Packs/CommonScripts/Scripts/CalculateEntropy/CalculateEntropy_description.md
  Packs/CommonScripts/Scripts/CalculateEntropy/README.md
  Packs/CommonScripts/pack_metadata.json
  Utils/tests/id_set.json
Labels: docs-approved

#8296 MSGraph Mail - Update Message ID
  Packs/MicrosoftGraphMail/Integrations/MicrosoftGraphMail/MicrosoftGraphMail.yml
  Packs/MicrosoftGraphMail/ReleaseNotes/1_0_3.md
  Packs/MicrosoftGraphMail/pack_metadata.json
Labels: docs-approved

#8274 Encourage migrating to GenericSQL
  Packs/GenericSQL/Integrations/GenericSQL/GenericSQL.py
  Packs/GenericSQL/Integrations/GenericSQL/GenericSQL.yml
  Packs/GenericSQL/ReleaseNotes/1_0_5.md
  Packs/GenericSQL/pack_metadata.json
Labels: docs-approved

#8309 xdr_iocs - updated tags param
  Packs/CortexXDR/Integrations/XDR_iocs/XDR_iocs.py
  Packs/CortexXDR/Integrations/XDR_iocs/XDR_iocs.yml
  Packs/CortexXDR/Integrations/XDR_iocs/XDR_iocs_test.py
  Packs/CortexXDR/ReleaseNotes/2_3_1.md
  Packs/CortexXDR/pack_metadata.json
Labels: docs-approved, release-notes-only

#8091 Add Imperva WAF integration
  Packs/Imperva_WAF/.pack-ignore
  Packs/Imperva_WAF/.secrets-ignore
  Packs/Imperva_WAF/Integrations/ImpervaWAF/ImpervaWAF.py
  Packs/Imperva_WAF/Integrations/ImpervaWAF/ImpervaWAF.yml
  Packs/Imperva_WAF/Integrations/ImpervaWAF/ImpervaWAF_image.png
  Packs/Imperva_WAF/Integrations/ImpervaWAF/example.txt
  Packs/Imperva_WAF/README.md
  Packs/Imperva_WAF/TestPlaybooks/playbook-Imperva_WAF_-_Test.yml
  Packs/Imperva_WAF/pack_metadata.json
  Tests/conf.json
Labels: docs-approved

#8250 MSGraph Mail - OData fix
  Packs/MicrosoftGraphMail/Integrations/MicrosoftGraphMail/MicrosoftGraphMail.py
  Packs/MicrosoftGraphMail/Integrations/MicrosoftGraphMail/MicrosoftGraphMail.yml
  Packs/MicrosoftGraphMail/Integrations/MicrosoftGraphMail/README.md
  Packs/MicrosoftGraphMail/ReleaseNotes/1_0_4.md
  Packs/MicrosoftGraphMail/TestPlaybooks/playbook-MicrosoftGraphMail-Test.yml
  Packs/MicrosoftGraphMail/pack_metadata.json
Labels: docs-approved

#8303 [sixgill-195] darkfeed pack 13 7 2020 (#7988)
  Packs/Sixgill-Darkfeed/.pack-ignore
  Packs/Sixgill-Darkfeed/.secrets-ignore
  Packs/Sixgill-Darkfeed/Dashboards/dashboard-Sixgill_Darkfeed.json
  Packs/Sixgill-Darkfeed/IndicatorFields/indicatorfield-sixgillactor.json
  Packs/Sixgill-Darkfeed/IndicatorFields/indicatorfield-sixgilldescription.json
  Packs/Sixgill-Darkfeed/IndicatorFields/indicatorfield-sixgillfeedid.json
  Packs/Sixgill-Darkfeed/IndicatorFields/indicatorfield-sixgillfeedname.json
  Packs/Sixgill-Darkfeed/IndicatorFields/indicatorfield-sixgillindicatorid.json
  Packs/Sixgill-Darkfeed/IndicatorFields/indicatorfield-sixgilllanguage.json
  Packs/Sixgill-Darkfeed/IndicatorFields/indicatorfield-sixgillmitreattcktactic.json
  Packs/Sixgill-Darkfeed/IndicatorFields/indicatorfield-sixgillmitreattcktechnique.json
  Packs/Sixgill-Darkfeed/IndicatorFields/indicatorfield-sixgillpostreference.json
  Packs/Sixgill-Darkfeed/IndicatorFields/indicatorfield-sixgillposttitle.json
  Packs/Sixgill-Darkfeed/IndicatorFields/indicatorfield-sixgillsource.json
  Packs/Sixgill-Darkfeed/IndicatorFields/indicatorfield-sixgillvirustotaldetectionrate.json
  Packs/Sixgill-Darkfeed/IndicatorFields/indicatorfield-sixgillvirustotalurl.json
  Packs/Sixgill-Darkfeed/Integrations/Sixgill_Darkfeed/CHANGELOG.md
  Packs/Sixgill-Darkfeed/Integrations/Sixgill_Darkfeed/README.md
  Packs/Sixgill-Darkfeed/Integrations/Sixgill_Darkfeed/Sixgill_Darkfeed.py
  Packs/Sixgill-Darkfeed/Integrations/Sixgill_Darkfeed/Sixgill_Darkfeed.yml
  Packs/Sixgill-Darkfeed/Integrations/Sixgill_Darkfeed/Sixgill_Darkfeed_test.py
  Packs/Sixgill-Darkfeed/Playbooks/Darkfeed_-_malware_download_from_feed.yml
  Packs/Sixgill-Darkfeed/Playbooks/Darkfeed_-_malware_download_from_feed_README.md
  Packs/Sixgill-Darkfeed/Playbooks/Darkfeed_IOC_detonation_and_proactive_blocking.yml
  Packs/Sixgill-Darkfeed/Playbooks/Darkfeed_IOC_detonation_and_proactive_blocking_README.md
  Packs/Sixgill-Darkfeed/Playbooks/Darkfeed_Threat_hunting_research.yml
  Packs/Sixgill-Darkfeed/Playbooks/Darkfeed_Threat_hunting_research_README.md
  Packs/Sixgill-Darkfeed/README.md
  Packs/Sixgill-Darkfeed/ReleaseNotes/1_1_0.md
  Packs/Sixgill-Darkfeed/Scripts/SearchIndicators/Pipfile
  Packs/Sixgill-Darkfeed/Scripts/SearchIndicators/Pipfile.lock
  Packs/Sixgill-Darkfeed/Scripts/SearchIndicators/README.md
  Packs/Sixgill-Darkfeed/Scripts/SearchIndicators/SearchIndicators.py
  Packs/Sixgill-Darkfeed/Scripts/SearchIndicators/SearchIndicators.yml
  Packs/Sixgill-Darkfeed/Scripts/SearchIndicators/SearchIndicators_test.py
  Packs/Sixgill-Darkfeed/TestPlaybooks/playbook-Sixgill-Darkfeed_Test.yml
  Packs/Sixgill-Darkfeed/Widgets/widget-SixgillDarkfeedCollectedIOCs.json
  Packs/Sixgill-Darkfeed/Widgets/widget-SixgillDarkfeedIOCDetectionRateByVirusTotal.json
  Packs/Sixgill-Darkfeed/Widgets/widget-SixgillDarkfeedIndicatorsByType.json
  Packs/Sixgill-Darkfeed/Widgets/widget-SixgillDarkfeedMitreAttackTactics.json
  Packs/Sixgill-Darkfeed/Widgets/widget-SixgillDarkfeedSubfeedComposition.json
  Packs/Sixgill-Darkfeed/Widgets/widget-SixgillDarkfeedThreadsFromTheUnderground.json
  Packs/Sixgill-Darkfeed/Widgets/widget-SixgillDarkfeedTopThreatActors.json
  Packs/Sixgill-Darkfeed/Widgets/widget-SixgillMitreAttackTechniques.json
  Packs/Sixgill-Darkfeed/doc_files/Darkfeed_-_malware_download_from_feed.png
  Packs/Sixgill-Darkfeed/doc_files/Darkfeed_IOC_detonation_and_proactive_blocking.png
  Packs/Sixgill-Darkfeed/doc_files/Darkfeed_Threat_hunting_research.png
  Packs/Sixgill-Darkfeed/pack_metadata.json
  Tests/conf.json
Labels: docs-approved

#8318 Failed Instance destruction bug
  Tests/scripts/run_tests.sh
  Tests/test_content.py
Labels: docs-approved

#8273 adding new proxy param and remove the old
  Packs/ThreatConnect/Integrations/ThreatConnect_v2/README.md
  Packs/ThreatConnect/Integrations/ThreatConnect_v2/ThreatConnect_v2.py
  Packs/ThreatConnect/Integrations/ThreatConnect_v2/ThreatConnect_v2.yml
  Packs/ThreatConnect/ReleaseNotes/2_0_3.md
  Packs/ThreatConnect/pack_metadata.json
Labels: docs-approved, release-notes-only

#8325 Sigxill feed tags new
  Packs/Sixgill-Darkfeed/Integrations/Sixgill_Darkfeed/Sixgill_Darkfeed.py
  Packs/Sixgill-Darkfeed/Integrations/Sixgill_Darkfeed/Sixgill_Darkfeed.yml
  Packs/Sixgill-Darkfeed/Integrations/Sixgill_Darkfeed/Sixgill_Darkfeed_test.py
  Packs/Sixgill-Darkfeed/ReleaseNotes/1_1_1.md
  Packs/Sixgill-Darkfeed/pack_metadata.json
Labels: docs-approved

#8209 Parse EML attachment not found in ParseEmailFiles
  Packs/CommonScripts/.secrets-ignore
  Packs/CommonScripts/ReleaseNotes/1_2_23.md
  Packs/CommonScripts/Scripts/ParseEmailFiles/ParseEmailFiles.py
  Packs/CommonScripts/Scripts/ParseEmailFiles/parse_email_files_test.py
  Packs/CommonScripts/Scripts/ParseEmailFiles/test_data/eml_contains_emptytxt_htm_file.eml
  Packs/CommonScripts/pack_metadata.json
Labels: docs-approved

#8331 fixed dependencies script
  Tests/Marketplace/packs_dependencies.py
Labels: docs-approved

#8330 URL indicator layout
  Packs/CommonTypes/Layouts/layoutscontainer-url.json
  Packs/CommonTypes/ReleaseNotes/1_7_3.md
  Packs/CommonTypes/pack_metadata.json
Labels: docs-approved, release-notes-only

#8346 url indicator layout
  Packs/CommonTypes/Layouts/layoutscontainer-url.json
Labels: docs-approved

#8281 Feed tags update
  Packs/AutoFocus/Integrations/FeedAutofocus/FeedAutofocus.yml
  Packs/AutoFocus/Integrations/FeedAutofocusDaily/FeedAutofocusDaily.yml
  Packs/AutoFocus/ReleaseNotes/1_1_1.md
  Packs/AutoFocus/pack_metadata.json
  Packs/FeedAlienVault/Integrations/FeedAlienVaultReputation/FeedAlienVaultReputation.yml
  Packs/FeedAlienVault/ReleaseNotes/1_0_2.md
  Packs/FeedAlienVault/pack_metadata.json
  Packs/FeedFastly/Integrations/FeedFastly/FeedFastly.yml
  Packs/FeedFastly/ReleaseNotes/1_0_1.md
  Packs/FeedFastly/pack_metadata.json
  Packs/FeedGCPWhitelist/Integrations/FeedGCPWhitelist/FeedGCPWhitelist.yml
  Packs/FeedGCPWhitelist/ReleaseNotes/1_0_1.md
  Packs/FeedGCPWhitelist/pack_metadata.json
  Packs/FeedJSON/Integrations/FeedJSON/FeedJSON.yml
  Packs/FeedJSON/ReleaseNotes/1_0_2.md
  Packs/FeedJSON/pack_metadata.json
  Packs/FeedTAXII/Integrations/FeedTAXII2/FeedTAXII2.yml
  Packs/FeedTAXII/ReleaseNotes/1_0_3.md
  Packs/FeedTAXII/pack_metadata.json
  Packs/FeedTorExitAddresses/Integrations/FeedTorExitAddresses/FeedTorExitAddresses.yml
  Packs/FeedTorExitAddresses/ReleaseNotes/1_0_1.md
  Packs/FeedTorExitAddresses/pack_metadata.json
  Packs/FeedUnit42/Integrations/FeedUnit42/FeedUnit42.yml
  Packs/FeedUnit42/ReleaseNotes/1_0_2.md
  Packs/FeedUnit42/pack_metadata.json
  Packs/Feedsslabusech/Integrations/Feedsslabusech/Feedsslabusech.yml
  Packs/Feedsslabusech/ReleaseNotes/1_0_1.md
  Packs/Feedsslabusech/pack_metadata.json
Labels: docs-approved

#8336 SearchIncidentsV2 - Fixed the *query* argument to not support input a…
  Packs/CommonScripts/ReleaseNotes/1_2_24.md
  Packs/CommonScripts/Scripts/SearchIncidentsV2/SearchIncidentsV2.yml
  Packs/CommonScripts/pack_metadata.json
Labels: bug, docs-approved, release-notes-only

#7747 [druva-1202] Druva Integration
  Packs/Druva/.pack-ignore
  Packs/Druva/.secrets-ignore
  Packs/Druva/Integrations/Druva/Druva.py
  Packs/Druva/Integrations/Druva/Druva.yml
  Packs/Druva/Integrations/Druva/Druva_description.md
  Packs/Druva/Integrations/Druva/Druva_image.png
  Packs/Druva/Integrations/Druva/Druva_test.py
  Packs/Druva/Integrations/Druva/Pipfile
  Packs/Druva/Integrations/Druva/Pipfile.lock
  Packs/Druva/Integrations/Druva/README.md
  Packs/Druva/Integrations/Druva/command_examples
  Packs/Druva/README.md
  Packs/Druva/TestPlaybooks/playbook-Druva-Test.yml
  Packs/Druva/pack_metadata.json
  Tests/conf.json
Labels: Contribution, docs-approved

#8329 Generic SQL: small update to descriptions
  Packs/GenericSQL/Integrations/GenericSQL/GenericSQL.yml
  Packs/GenericSQL/ReleaseNotes/1_0_6.md
  Packs/GenericSQL/pack_metadata.json
Labels: docs-approved

#8332 ArcSight ESM v2 - Fixed an issue where long *eventId* were not proces…
  Packs/ArcSightESM/Integrations/ArcSightESMv2/ArcSightESMv2.py
  Packs/ArcSightESM/Integrations/ArcSightESMv2/ArcSightESMv2.yml
  Packs/ArcSightESM/Integrations/ArcSightESMv2/ArcSightESMv2_test.py
  Packs/ArcSightESM/ReleaseNotes/1_0_4.md
  Packs/ArcSightESM/pack_metadata.json
Labels: bug, docs-approved, release-notes-only

#8351 removed polygon usecases
  Packs/Polygon/pack_metadata.json
Labels: docs-approved

#8350 LogRhythm Test - add conditional task to check if alert got events
  Packs/LogRhythm/TestPlaybooks/playbook-LogRhythm_Test_Playbook.yml
Labels: docs-approved

#8352 Mitre attack feed tags
  Packs/FeedMitreAttack/Integrations/FeedMitreAttack/FeedMitreAttack.py
  Packs/FeedMitreAttack/Integrations/FeedMitreAttack/FeedMitreAttack.yml
  Packs/FeedMitreAttack/ReleaseNotes/1_0_9.md
  Packs/FeedMitreAttack/pack_metadata.json
Labels: docs-approved

#8353 Digital defense frontline vm test failure
  Tests/conf.json
Labels: docs-approved

#8335 Use unrar for unzipping .rar files
  Packs/CommonScripts/ReleaseNotes/1_2_25.md
  Packs/CommonScripts/Scripts/UnzipFile/UnzipFile.py
  Packs/CommonScripts/Scripts/UnzipFile/UnzipFile.yml
  Packs/CommonScripts/Scripts/UnzipFile/UnzipFile_test.py
  Packs/CommonScripts/Scripts/UnzipFile/data_test/Untitled_document.pdf
  Packs/CommonScripts/Scripts/UnzipFile/data_test/Untitled_document.pdf.rar
  Packs/CommonScripts/pack_metadata.json
Labels: docs-approved

#8361 readme fixes
  Packs/IllusiveNetworks/Integrations/IllusiveNetworks/README.md
  Packs/IllusiveNetworks/README.md
Labels: Contribution, docs-approved

#8362 20.8.0 - update sha1
  .circleci/config.yml
Labels: docs-approved

#8317 Microsoft Teams README - update checkboxes to select in bot setup
  Packs/MicrosoftTeams/Integrations/MicrosoftTeams/README.md
Labels: docs-approved

#7826 Adding API key ID and API key secret
  Packs/IBMResilientSystems/Integrations/IBMResilientSystems/IBMResilientSystems.py
  Packs/IBMResilientSystems/Integrations/IBMResilientSystems/IBMResilientSystems.yml
  Packs/IBMResilientSystems/Integrations/IBMResilientSystems/IBMResilientSystems_description.md
  Packs/IBMResilientSystems/Integrations/IBMResilientSystems/README.md
  Packs/IBMResilientSystems/ReleaseNotes/1_0_2.md
  Packs/IBMResilientSystems/pack_metadata.json
Labels: docs-approved

#8372 ArcSight ESM v2 - Fixed an issue where the *entry_filter* argument in…
  Packs/ArcSightESM/Integrations/ArcSightESMv2/ArcSightESMv2.py
  Packs/ArcSightESM/Integrations/ArcSightESMv2/ArcSightESMv2_test.py
  Packs/ArcSightESM/Integrations/ArcSightESMv2/README.md
  Packs/ArcSightESM/ReleaseNotes/1_0_5.md
  Packs/ArcSightESM/pack_metadata.json
Labels: bug, docs-approved, release-notes-only

#7646 Keylight - Improve Login error message.
  Packs/Lokpath_Keylight/Integrations/Lockpath_KeyLight_v2/Lockpath_KeyLight_v2.py
  Packs/Lokpath_Keylight/Integrations/Lockpath_KeyLight_v2/Lockpath_KeyLight_v2.yml
  Packs/Lokpath_Keylight/ReleaseNotes/1_1_0.md
  Packs/Lokpath_Keylight/TestPlaybooks/playbook-Keylightv2-test.yml
  Packs/Lokpath_Keylight/pack_metadata.json
  Tests/conf.json
Labels: docs-approved, release-notes-only

#8368 added url arg to cdl-query-url-logs
  Packs/CortexDataLake/Integrations/CortexDataLake/CortexDataLake.yml
  Packs/CortexDataLake/ReleaseNotes/1_1_1.md
  Packs/CortexDataLake/pack_metadata.json
Labels: docs-approved

#8341 fix RN to explain the change in proxy config
  Packs/ThreatConnect/ReleaseNotes/2_0_3.md
Labels: docs-approved, release-notes-only

#8024 Crowdstrike apimodule
  Packs/ApiModules/.secrets-ignore
  Packs/ApiModules/ReleaseNotes/1_0_5.md
  Packs/ApiModules/Scripts/CrowdStrikeApiModule/CrowdStrikeApiModule.py
  Packs/ApiModules/Scripts/CrowdStrikeApiModule/CrowdStrikeApiModule.yml
  Packs/ApiModules/Scripts/CrowdStrikeApiModule/CrowdStrikeApiModule_test.py
  Packs/ApiModules/Scripts/CrowdStrikeApiModule/README.md
  Packs/ApiModules/Scripts/CrowdStrikeApiModule/TestsInput/context.py
  Packs/ApiModules/Scripts/CrowdStrikeApiModule/TestsInput/http_responses.py
  Packs/ApiModules/pack_metadata.json
  Packs/Base/ReleaseNotes/1_1_8.md
  Packs/Base/Scripts/CommonServerPython/CommonServerPython.py
  Packs/Base/pack_metadata.json
Labels: docs-approved

#8367 All feeds - updated fetch default param to true
  Packs/AutoFocus/Integrations/FeedAutofocus/FeedAutofocus.yml
  Packs/AutoFocus/Integrations/FeedAutofocusDaily/FeedAutofocusDaily.yml
  Packs/AutoFocus/ReleaseNotes/1_1_2.md
  Packs/AutoFocus/pack_metadata.json
  Packs/FeedAWS/Integrations/FeedAWS/FeedAWS.yml
  Packs/FeedAWS/ReleaseNotes/1_0_4.md
  Packs/FeedAWS/pack_metadata.json
  Packs/FeedAlienVault/Integrations/FeedAlienVaultReputation/FeedAlienVaultReputation.yml
  Packs/FeedAlienVault/ReleaseNotes/1_0_3.md
  Packs/FeedAlienVault/pack_metadata.json
  Packs/FeedBambenekConsulting/Integrations/FeedBambenekConsulting/FeedBambenekConsulting.yml
  Packs/FeedBambenekConsulting/ReleaseNotes/1_0_2.md
  Packs/FeedBambenekConsulting/pack_metadata.json
  Packs/FeedCSV/Integrations/FeedCSV/FeedCSV.yml
  Packs/FeedCSV/ReleaseNotes/1_0_3.md
  Packs/FeedCSV/pack_metadata.json
  Packs/FeedCofense/Integrations/FeedCofense/FeedCofense.yml
  Packs/FeedCofense/ReleaseNotes/1_0_5.md
  Packs/FeedCofense/pack_metadata.json
  Packs/FeedElasticsearch/Integrations/FeedElasticsearch/FeedElasticsearch.yml
  Packs/FeedElasticsearch/ReleaseNotes/1_0_5.md
  Packs/FeedElasticsearch/pack_metadata.json
  Packs/FeedMitreAttack/Integrations/FeedMitreAttack/FeedMitreAttack.yml
  Packs/FeedMitreAttack/ReleaseNotes/1_0_10.md
  Packs/FeedMitreAttack/pack_metadata.json
  Packs/FeedOffice365/Integrations/FeedOffice365/FeedOffice365.yml
  Packs/FeedOffice365/ReleaseNotes/1_1_4.md
  Packs/FeedOffice365/pack_metadata.json
  Packs/FeedProofpoint/Integrations/FeedProofpoint/FeedProofpoint.yml
  Packs/FeedProofpoint/ReleaseNotes/1_0_2.md
  Packs/FeedProofpoint/pack_metadata.json
  Packs/FeedRecordedFuture/Integrations/FeedRecordedFuture/FeedRecordedFuture.yml
  Packs/FeedRecordedFuture/ReleaseNotes/1_0_3.md
  Packs/FeedRecordedFuture/pack_metadata.json
  Packs/FeedUnit42/Integrations/FeedUnit42/FeedUnit42.yml
  Packs/FeedUnit42/ReleaseNotes/1_0_3.md
  Packs/FeedUnit42/pack_metadata.json
  Packs/Feedsslabusech/Integrations/Feedsslabusech/Feedsslabusech.yml
  Packs/Feedsslabusech/ReleaseNotes/1_0_2.md
  Packs/Feedsslabusech/pack_metadata.json
  Packs/SafeBreach/Integrations/SafeBreach_v2/SafeBreach_v2.yml
  Packs/SafeBreach/ReleaseNotes/1_0_5.md
  Packs/SafeBreach/pack_metadata.json
  Packs/Sixgill-Darkfeed/Integrations/Sixgill_Darkfeed/Sixgill_Darkfeed.yml
  Packs/Sixgill-Darkfeed/ReleaseNotes/1_1_2.md
  Packs/Sixgill-Darkfeed/pack_metadata.json
Labels: docs-approved

#8333 Rasterize fix image to pdf
  Packs/rasterize/.secrets-ignore
  Packs/rasterize/Integrations/rasterize/Pipfile
  Packs/rasterize/Integrations/rasterize/Pipfile.lock
  Packs/rasterize/Integrations/rasterize/rasterize.py
  Packs/rasterize/Integrations/rasterize/rasterize.yml
  Packs/rasterize/Integrations/rasterize/rasterize_test.py
  Packs/rasterize/Integrations/rasterize/test_data/image.png
  Packs/rasterize/ReleaseNotes/1_0_4.md
  Packs/rasterize/pack_metadata.json
Labels: docs-approved, release-notes-only

#8050 CrowdStrike Falcon Streaming v2 - enhancements
  Packs/CrowdStrikeFalconStreamingV2/Integrations/CrowdStrikeFalconStreamingV2/CrowdStrikeFalconStreamingV2.py
  Packs/CrowdStrikeFalconStreamingV2/Integrations/CrowdStrikeFalconStreamingV2/CrowdStrikeFalconStreamingV2.yml
  Packs/CrowdStrikeFalconStreamingV2/Integrations/CrowdStrikeFalconStreamingV2/README.md
  Packs/CrowdStrikeFalconStreamingV2/ReleaseNotes/1_0_4.md
  Packs/CrowdStrikeFalconStreamingV2/pack_metadata.json
Labels: docs-approved, release-notes-only

#8259 support multiple keys
  Documentation/common_server_docs.py
  Packs/Base/Scripts/CommonServerPython/CommonServerPython.py
  Packs/Base/Scripts/CommonServerPython/CommonServerPython_test.py
  Packs/Polygon/Integrations/Polygon/test_data/results.json
Labels: docs-approved

#8383 Mocks Logging
  .circleci/config.yml
  Tests/mock_server.py
  Tests/test_content.py
Labels: docs-approved

#8194 AWS Access Analyzer Fetch
  Packs/AWS-AccessAnalyzer/Integrations/AWS-AccessAnalyzer/AWS-AccessAnalyzer.py
  Packs/AWS-AccessAnalyzer/Integrations/AWS-AccessAnalyzer/AWS-AccessAnalyzer.yml
  Packs/AWS-AccessAnalyzer/Integrations/AWS-AccessAnalyzer/README.md
  Packs/AWS-AccessAnalyzer/ReleaseNotes/1_0_1.md
  Packs/AWS-AccessAnalyzer/pack_metadata.json
Labels: Contribution, docs-approved

#8386 update desc
  Packs/CortexXDR/Integrations/XDR_iocs/README.md
  Packs/CortexXDR/Integrations/XDR_iocs/XDR_iocs_description.md
Labels: docs-approved

#7899 Aburt ModifyDateTime transformer
  Packs/CommonScripts/ReleaseNotes/1_2_21.md
  Packs/CommonScripts/Scripts/ModifyDateTime/ModifyDateTime.py
  Packs/CommonScripts/Scripts/ModifyDateTime/ModifyDateTime.yml
  Packs/CommonScripts/Scripts/ModifyDateTime/ModifyDateTime_test.py
  Packs/CommonScripts/Scripts/ModifyDateTime/README.md
  Packs/CommonScripts/pack_metadata.json
Labels: Contribution, docs-approved

#8378 Small bug fix at DbotPreprocessTextData
  Packs/Base/Scripts/DBotPreprocessTextData/DBotPreprocessTextData.py
Labels: docs-approved

#8391 Revert "Mocks Logging"
  .circleci/config.yml
  Tests/mock_server.py
  Tests/test_content.py
Labels: docs-approved

#8387 Hod/mimecast
  Packs/Mimecast/Integrations/MimecastV2/MimecastV2.py
  Packs/Mimecast/ReleaseNotes/1_1_1.md
  Packs/Mimecast/TestPlaybooks/playbook-Mimecast_Test.yml
  Packs/Mimecast/pack_metadata.json
  Tests/conf.json
Labels: docs-approved, release-notes-only

#8188 Fetch ML data
  Packs/Base/.secrets-ignore
  Packs/Base/Scripts/DBotMLFetchData/DBotMLFetchData.py
  Packs/Base/Scripts/DBotMLFetchData/DBotMLFetchData.yml
  Packs/Base/Scripts/DBotMLFetchData/DBotMLFetchData_test.py
  Packs/Base/Scripts/DBotMLFetchData/glove_top_20.p
  Packs/Base/Scripts/DBotMLFetchData/test_data.p
  Packs/Base/Scripts/DBotMLFetchData/test_data/50_incidents.p
  Packs/Base/Scripts/DBotMLFetchData/test_data/domain_to_rank_top_5.p
  Packs/Base/Scripts/DBotMLFetchData/test_data/fasttext_top_10.p
  Packs/Base/Scripts/DBotMLFetchData/test_data/glove_100_top_10.p
  Packs/Base/Scripts/DBotMLFetchData/test_data/glove_50_top_10.p
  Packs/Base/Scripts/DBotMLFetchData/test_data/word_to_ngram.p
  Packs/Base/Scripts/DBotMLFetchData/test_data/word_to_regex.p
Labels: docs-approved

#8343 Script enhancement - FailedInstances
  Packs/CommonScripts/ReleaseNotes/1_2_26.md
  Packs/CommonScripts/Scripts/script-FailedInstances.yml
  Packs/CommonScripts/Scripts/script-FailedInstances_README.md
  Packs/CommonScripts/TestPlaybooks/playbook-FailedInstances_-_Test.yml
  Packs/CommonScripts/pack_metadata.json
  Tests/conf.json
Labels: docs-approved

#8363 Set default values for a couple SplunkPy Params
  Packs/SplunkPy/.secrets-ignore
  Packs/SplunkPy/Integrations/SplunkPy/SplunkPy.py
  Packs/SplunkPy/Integrations/SplunkPy/SplunkPy.yml
  Packs/SplunkPy/Integrations/SplunkPy/SplunkPy_test.py
  Packs/SplunkPy/ReleaseNotes/1_1_1.md
  Packs/SplunkPy/pack_metadata.json
Labels: docs-approved

#8369 ZScaler bug - missing argument in context
  Packs/Zscaler/Integrations/Zscaler/Zscaler.py
  Packs/Zscaler/Integrations/Zscaler/Zscaler_test.py
  Packs/Zscaler/Integrations/Zscaler/test_data/responses/url_with_urlClassificationsWithSecurityAlert.json
  Packs/Zscaler/Integrations/Zscaler/test_data/results/url_with_urlClassificationsWithSecurityAlert.json
  Packs/Zscaler/ReleaseNotes/1_0_3.md
  Packs/Zscaler/pack_metadata.json
Labels: bug, content, release-notes-only

#8249 Update MailSenderNew.yml
  Packs/MailSenderNew/.secrets-ignore
  Packs/MailSenderNew/Integrations/MailSenderNew/MailSenderNew.yml
  Packs/MailSenderNew/ReleaseNotes/1_0_1.md
  Packs/MailSenderNew/pack_metadata.json
Labels: docs-approved

#8381 File Validator Clean
  release_notes.py
  release_notes_clear.py
Labels: docs-approved

#8278 MSGraph Mail - Pages Puller Fix
  Packs/MicrosoftGraphMail/Integrations/MicrosoftGraphMail/MicrosoftGraphMail.py
  Packs/MicrosoftGraphMail/Integrations/MicrosoftGraphMail/MicrosoftGraphMail.yml
  Packs/MicrosoftGraphMail/Integrations/MicrosoftGraphMail/MicrosoftGraphMail_test.py
  Packs/MicrosoftGraphMail/Integrations/MicrosoftGraphMail/test_data/mails
  Packs/MicrosoftGraphMail/Integrations/MicrosoftGraphMail/test_data/no_mails
  Packs/MicrosoftGraphMail/ReleaseNotes/1_0_5.md
  Packs/MicrosoftGraphMail/pack_metadata.json
Labels: docs-approved

#8399 fix commandresults when provided only outputs_prefix
  Packs/Base/ReleaseNotes/1_1_9.md
  Packs/Base/Scripts/CommonServerPython/CommonServerPython.py
  Packs/Base/Scripts/CommonServerPython/CommonServerPython_test.py
  Packs/Base/pack_metadata.json
Labels: docs-approved

#8407 Update pack_metadata.json
  Packs/CofenseTriage/ReleaseNotes/1_1_2.md
  Packs/CofenseTriage/pack_metadata.json
Labels: Contribution, docs-approved

#8412 LogRhythm-Test - set tested alert to be ID 80
  Packs/LogRhythm/TestPlaybooks/playbook-LogRhythm_Test_Playbook.yml
Labels: docs-approved

#8299 New transformer script to allow using jmespath in transformations.
  Packs/CommonScripts/ReleaseNotes/1_2_27.md
  Packs/CommonScripts/Scripts/Jmespath/README.md
  Packs/CommonScripts/Scripts/Jmespath/jmespath.yml
  Packs/CommonScripts/Scripts/Jmespath/jmespath_test.py
  Packs/CommonScripts/Scripts/Jmespath/jmespath_transformer.py
  Packs/CommonScripts/pack_metadata.json
Labels: Contribution, docs-approved

#8398 Release notes improvements
  Tests/scripts/infrastructure_tests/release_notes_generator_test.py
  Tests/scripts/infrastructure_tests/tests_data/RN_tests_data/FakePack5/Classifiers/fake_classifier.json
  Tests/scripts/infrastructure_tests/tests_data/RN_tests_data/FakePack5/Integrations/fake_integration.yml
  Tests/scripts/infrastructure_tests/tests_data/RN_tests_data/FakePack5/Layouts/fake_layout.json
  Utils/release_notes_generator.py
Labels: docs-approved

#8423 Feed Related Indicators- Set the description column values to be clic…
  Packs/CommonTypes/IndicatorFields/incidentfield-feedrelatedindicators.json
  Packs/CommonTypes/ReleaseNotes/1_7_4.md
  Packs/CommonTypes/pack_metadata.json
Labels: bug, docs-approved, release-notes-only

#8031 Add ootb indicators types for stix2
  Packs/CommonTypes/IndicatorFields/indicatorfield-STIX_Aliases.json
  Packs/CommonTypes/IndicatorFields/indicatorfield-STIX_Description.json
  Packs/CommonTypes/IndicatorFields/indicatorfield-STIX_Goals.json
  Packs/CommonTypes/IndicatorFields/indicatorfield-STIX_ID.json
  Packs/CommonTypes/IndicatorFields/indicatorfield-STIX_Is_Malware_Family.json
  Packs/CommonTypes/IndicatorFields/indicatorfield-STIX_Kill_Chain_Phases.json
  Packs/CommonTypes/IndicatorFields/indicatorfield-STIX_Malware_Types.json
  Packs/CommonTypes/IndicatorFields/indicatorfield-STIX_Primary_Motivation.json
  Packs/CommonTypes/IndicatorFields/indicatorfield-STIX_Resource_Level.json
  Packs/CommonTypes/IndicatorFields/indicatorfield-STIX_Roles.json
  Packs/CommonTypes/IndicatorFields/indicatorfield-STIX_Secondary_Motivations.json
  Packs/CommonTypes/IndicatorFields/indicatorfield-STIX_Sophistication.json
  Packs/CommonTypes/IndicatorFields/indicatorfield-STIX_Threat_Actor_Types.json
  Packs/CommonTypes/IndicatorFields/indicatorfield-STIX_Tool_Types.json
  Packs/CommonTypes/IndicatorFields/indicatorfield-STIX_Tool_Version.json
  Packs/CommonTypes/IndicatorTypes/reputation-STIX_Attack_Pattern.json
  Packs/CommonTypes/IndicatorTypes/reputation-STIX_Malware.json
  Packs/CommonTypes/IndicatorTypes/reputation-STIX_Report.json
  Packs/CommonTypes/IndicatorTypes/reputation-STIX_Threat_Actor.json
  Packs/CommonTypes/IndicatorTypes/reputation-STIX_Tool.json
  Packs/CommonTypes/Layouts/layout-indicatorsDetails-STIX_Attack_Pattern.json
  Packs/CommonTypes/Layouts/layout-indicatorsDetails-STIX_Malware.json
  Packs/CommonTypes/Layouts/layout-indicatorsDetails-STIX_Report.json
  Packs/CommonTypes/Layouts/layout-indicatorsDetails-STIX_Threat_Actor.json
  Packs/CommonTypes/Layouts/layout-indicatorsDetails-STIX_Tool.json
  Packs/CommonTypes/Layouts/layoutscontainer-STIX_Attack_Pattern.json
  Packs/CommonTypes/Layouts/layoutscontainer-STIX_Malware.json
  Packs/CommonTypes/Layouts/layoutscontainer-STIX_Report.json
  Packs/CommonTypes/Layouts/layoutscontainer-STIX_Threat_Actor.json
  Packs/CommonTypes/Layouts/layoutscontainer-STIX_Tool.json
  Packs/CommonTypes/ReleaseNotes/1_8_0.md
  Packs/CommonTypes/pack_metadata.json
Labels: docs-approved, release-notes-only

#8425 Fixed Images urls
  Packs/Polygon/Playbooks/playbook-Detonate_File_-_Group-IB_TDS_Polygon_README.md
  Packs/Polygon/Playbooks/playbook-Detonate_URL_-_Group-IB_TDS_Polygon_README.md
  Packs/Tufin/Playbooks/playbook-Tufin_-_Get_Application_Information_from_SecureApp_README.md
  Packs/Tufin/Playbooks/playbook-Tufin_-_Get_Network_Device_Info_by_IP_Address_README.md
Labels: docs-approved

#8424 Alien vault bug
  Packs/FeedAlienVault/Integrations/FeedAlienVaultOTXTaxii/FeedAlienVaultOTXTaxii.py
  Packs/FeedAlienVault/Integrations/FeedAlienVaultOTXTaxii/FeedAlienVaultOTXTaxii.yml
  Packs/FeedAlienVault/Integrations/FeedAlienVaultOTXTaxii/FeedAlienVaultOTXTaxii_description.md
  Packs/FeedAlienVault/ReleaseNotes/1_0_4.md
  Packs/FeedAlienVault/pack_metadata.json
Labels: bug, docs-approved, release-notes-only

#8422 Update fromVersion for Sixgill Darkfeed dashboard
  Packs/Sixgill-Darkfeed/Dashboards/dashboard-Sixgill_Darkfeed.json
  Packs/Sixgill-Darkfeed/ReleaseNotes/1_1_3.md
  Packs/Sixgill-Darkfeed/pack_metadata.json
Labels: docs-approved

#8354 bumped ArcherRSA version
  Packs/ArcherRSA/ReleaseNotes/1_1_0.md
  Packs/ArcherRSA/pack_metadata.json
  Tests/conf.json
Labels: docs-approved

#8395 CrowdStrike Streaming v2 - add a note about one client can connect to a stream at a time
  Packs/CrowdStrikeFalconStreamingV2/Integrations/CrowdStrikeFalconStreamingV2/README.md
Labels: docs-approved

#8426 unskipping cdl
  Tests/conf.json
Labels: docs-approved

#8438 Zimperium - improved desc, fix layout id
  Packs/Zimperium/Classifiers/classifier-Zimperium.json
  Packs/Zimperium/Classifiers/classifier-Zimperium_5_9_9.json
  Packs/Zimperium/IncidentTypes/incidenttype-Zimperium_event.json
  Packs/Zimperium/Integrations/Zimperium/Zimperium.yml
  Packs/Zimperium/Layouts/layoutscontainer-Zimperium_event.json
  Packs/Zimperium/ReleaseNotes/1_0_4.md
  Packs/Zimperium/pack_metadata.json
Labels: bug, docs-approved, release-notes-only

#8312 Gmailbug
  Packs/Gmail/Integrations/Gmail/Gmail.py
  Packs/Gmail/Integrations/Gmail/Gmail.yml
  Packs/Gmail/ReleaseNotes/1_0_3.md
  Packs/Gmail/pack_metadata.json
Labels: docs-approved, release-notes-only

#8440 ParseEmailFiles empty attachment bug fix
  Packs/CommonScripts/ReleaseNotes/1_2_28.md
  Packs/CommonScripts/Scripts/ParseEmailFiles/ParseEmailFiles.py
  Packs/CommonScripts/pack_metadata.json
Labels: docs-approved

#8374 Fixed bug with MITRE ATT&CK dashboard
  Packs/FeedMitreAttack/ReleaseNotes/1_1_0.md
  Packs/FeedMitreAttack/Scripts/MITREIndicatorsByOpenIncidents/MITREIndicatorsByOpenIncidents.py
  Packs/FeedMitreAttack/Scripts/MITREIndicatorsByOpenIncidents/MITREIndicatorsByOpenIncidents.yml
  Packs/FeedMitreAttack/pack_metadata.json
Labels: docs-approved

#8429 Auto map custom fields
  Packs/Base/ReleaseNotes/1_1_10.md
  Packs/Base/Scripts/DBotSuggestClassifierMapping/DBotSuggestClassifierMapping.py
  Packs/Base/Scripts/DBotSuggestClassifierMapping/dbot_suggest_classifier_mapping_test.py
  Packs/Base/pack_metadata.json
Labels: docs-approved

#8143 Smartsheet IT Admin
  Packs/SmartSheetITAdmin/.pack-ignore
  Packs/SmartSheetITAdmin/.secrets-ignore
  Packs/SmartSheetITAdmin/Integrations/.secrets-ignore
  Packs/SmartSheetITAdmin/Integrations/Smartsheet_IT_Admin/Pipfile
  Packs/SmartSheetITAdmin/Integrations/Smartsheet_IT_Admin/Pipfile.lock
  Packs/SmartSheetITAdmin/Integrations/Smartsheet_IT_Admin/README.md
  Packs/SmartSheetITAdmin/Integrations/Smartsheet_IT_Admin/Smartsheet_IT_Admin.py
  Packs/SmartSheetITAdmin/Integrations/Smartsheet_IT_Admin/Smartsheet_IT_Admin.yml
  Packs/SmartSheetITAdmin/Integrations/Smartsheet_IT_Admin/Smartsheet_IT_Admin_description.md
  Packs/SmartSheetITAdmin/Integrations/Smartsheet_IT_Admin/Smartsheet_IT_Admin_image.png
  Packs/SmartSheetITAdmin/Integrations/Smartsheet_IT_Admin/Smartsheet_IT_Admin_test.py
  Packs/SmartSheetITAdmin/Integrations/Smartsheet_IT_Admin/cd
  Packs/SmartSheetITAdmin/Integrations/Smartsheet_IT_Admin/command-example.txt
  Packs/SmartSheetITAdmin/README.md
  Packs/SmartSheetITAdmin/TestPlaybooks/playbook-SmartsheetITAdmin-Test.yml
  Packs/SmartSheetITAdmin/pack_metadata.json
Labels: Contribution, docs-approved

#8397 add TIM tag to feed integrations
  Tests/Marketplace/Tests/marketplace_services_test.py
  Tests/Marketplace/marketplace_services.py
Labels: docs-approved

#8433 Added download count to pack metadata
  .circleci/build-requirements.txt
  Tests/Marketplace/Tests/marketplace_services_test.py
  Tests/Marketplace/marketplace_services.py
  Tests/Marketplace/upload_packs.py
  dev-requirements-py3.txt
Labels: docs-approved

#8245 [Fix] Cortex XDR Sync Script - Constantly unassigning/updating Incidents in XDR
  Packs/CortexXDR/ReleaseNotes/2_3_2.md
  Packs/CortexXDR/Scripts/XDRSyncScript/XDRSyncScript.yml
  Packs/CortexXDR/pack_metadata.json
Labels: docs-approved, release-notes-only

#8202 Old style exceptions --> new style for Python 3
  Packs/BigFix/Integrations/BigFix/BigFix.py
  Packs/BigFix/ReleaseNotes/1_0_2.md
  Packs/BigFix/pack_metadata.json
  Packs/IBMResilientSystems/Integrations/IBMResilientSystems/IBMResilientSystems.py
  Packs/IBMResilientSystems/ReleaseNotes/1_0_3.md
  Packs/IBMResilientSystems/pack_metadata.json
  Packs/Ipstack/Integrations/Ipstack/Ipstack.py
  Packs/Ipstack/ReleaseNotes/1_0_1.md
  Packs/Ipstack/pack_metadata.json
  Packs/MailSenderNew/Integrations/MailSenderNew/MailSenderNew_test.py
  Packs/McAfee_Advanced_Threat_Defense/Integrations/McAfee_Advanced_Threat_Defense/McAfee_Advanced_Threat_Defense.py
  Packs/McAfee_Advanced_Threat_Defense/ReleaseNotes/1_0_1.md
  Packs/McAfee_Advanced_Threat_Defense/pack_metadata.json
  Packs/ProofpointServerProtection/Integrations/ProofpointServerProtection/ProofpointServerProtection.py
  Packs/ProofpointServerProtection/ReleaseNotes/1_0_3.md
  Packs/ProofpointServerProtection/pack_metadata.json
  Packs/RTIR/Integrations/RTIR/RTIR.py
  Packs/RTIR/ReleaseNotes/1_0_4.md
  Packs/RTIR/pack_metadata.json
  Packs/Recorded_Future/Integrations/Recorded_Future/Recorded_Future.py
  Packs/Recorded_Future/ReleaseNotes/1_0_2.md
  Packs/Recorded_Future/pack_metadata.json
  Packs/Stealthwatch_Cloud/Integrations/Stealthwatch_Cloud/Stealthwatch_Cloud.py
  Packs/Stealthwatch_Cloud/ReleaseNotes/1_0_2.md
  Packs/Stealthwatch_Cloud/pack_metadata.json
  Packs/SymantecEndpointProtection/Integrations/SymantecEndpointProtection_V2/SymantecEndpointProtection_V2.py
  Packs/SymantecEndpointProtection/ReleaseNotes/1_0_1.md
  Packs/SymantecEndpointProtection/pack_metadata.json
  Packs/ThreatMiner/Integrations/ThreatMiner/ThreatMiner.py
  Packs/ThreatMiner/ReleaseNotes/1_0_2.md
  Packs/ThreatMiner/pack_metadata.json
  Utils/add_playbook_descriptions.py
Labels: Contribution, docs-approved

#8400 Changed regex of indicator to include Mitre ATT&CK sub-types.
  Packs/FeedMitreAttack/IndicatorTypes/reputation-mitreAttck.json
  Packs/FeedMitreAttack/ReleaseNotes/1_1_1.md
  Packs/FeedMitreAttack/pack_metadata.json
Labels: Contribution, docs-approved, release-notes-only

#8434 Google safe browsing bug
  Packs/GoogleSafeBrowsing/Integrations/README.md
  Packs/GoogleSafeBrowsing/Integrations/integration-GoogleSafeBrowsing.yml
  Packs/GoogleSafeBrowsing/ReleaseNotes/1_0_1.md
  Packs/GoogleSafeBrowsing/TestPlaybooks/playbook-Google_Safe_Browsing_Test.yml
  Packs/GoogleSafeBrowsing/pack_metadata.json
Labels: bug, docs-approved, release-notes-only

#8221 CyberArk PAS - new integration
  Packs/CyberArkPAS/.pack-ignore
  Packs/CyberArkPAS/.secrets-ignore
  Packs/CyberArkPAS/Integrations/CyberArkPAS/CyberArkPAS.py
  Packs/CyberArkPAS/Integrations/CyberArkPAS/CyberArkPAS.yml
  Packs/CyberArkPAS/Integrations/CyberArkPAS/CyberArkPAS_description.md
  Packs/CyberArkPAS/Integrations/CyberArkPAS/CyberArkPAS_image.png
  Packs/CyberArkPAS/Integrations/CyberArkPAS/CyberArkPAS_test.py
  Packs/CyberArkPAS/Integrations/CyberArkPAS/Pipfile
  Packs/CyberArkPAS/Integrations/CyberArkPAS/Pipfile.lock
  Packs/CyberArkPAS/Integrations/CyberArkPAS/README.md
  Packs/CyberArkPAS/Integrations/CyberArkPAS/examples.txt
  Packs/CyberArkPAS/Integrations/CyberArkPAS/test_data/context.py
  Packs/CyberArkPAS/Integrations/CyberArkPAS/test_data/http_resonses.py
  Packs/CyberArkPAS/README.md
  Packs/CyberArkPAS/pack_metadata.json
Labels: content, docs-approved

#8453 Fixed bug in adding and removing tags
  Packs/CommonTypes/Layouts/layout-indicatorsDetails-Account.json
  Packs/CommonTypes/Layouts/layout-indicatorsDetails-STIX_Attack_Pattern.json
  Packs/CommonTypes/Layouts/layout-indicatorsDetails-STIX_Malware.json
  Packs/CommonTypes/Layouts/layout-indicatorsDetails-STIX_Report.json
  Packs/CommonTypes/Layouts/layout-indicatorsDetails-STIX_Threat_Actor.json
  Packs/CommonTypes/Layouts/layout-indicatorsDetails-STIX_Tool.json
  Packs/CommonTypes/Layouts/layout-indicatorsDetails-domain.json
  Packs/CommonTypes/Layouts/layout-indicatorsDetails-ip.json
  Packs/CommonTypes/Layouts/layoutscontainer-Account.json
  Packs/CommonTypes/Layouts/layoutscontainer-STIX_Attack_Pattern.json
  Packs/CommonTypes/Layouts/layoutscontainer-STIX_Malware.json
  Packs/CommonTypes/Layouts/layoutscontainer-STIX_Report.json
  Packs/CommonTypes/Layouts/layoutscontainer-STIX_Threat_Actor.json
  Packs/CommonTypes/Layouts/layoutscontainer-STIX_Tool.json
  Packs/CommonTypes/Layouts/layoutscontainer-domain.json
  Packs/CommonTypes/Layouts/layoutscontainer-ip.json
  Packs/CommonTypes/Layouts/layoutscontainer-url.json
  Packs/CommonTypes/ReleaseNotes/1_8_1.md
  Packs/CommonTypes/pack_metadata.json
Labels: bug, docs-approved, release-notes-only

#8447 Assign analyst to script bug
  Packs/CommonScripts/Scripts/script-AssignAnalystToIncident_README.md
Labels: docs-approved

#8334 Active Directory Query v2 - limit ad-get-user command
  Packs/Active_Directory_Query/Integrations/Active_Directory_Query/Active_Directory_Query.py
  Packs/Active_Directory_Query/Integrations/Active_Directory_Query/Active_Directory_Query.yml
  Packs/Active_Directory_Query/ReleaseNotes/1_0_4.md
  Packs/Active_Directory_Query/TestPlaybooks/playbook-Active_Directory_-_ad-get-user_limit_check.yml
  Packs/Active_Directory_Query/pack_metadata.json
  Tests/conf.json
Labels: bug, content, docs-approved

#8450 Microsoft Graph User - Added the ***msgraph-user-change-password*** command
  Packs/MicrosoftGraphUser/Integrations/MicrosoftGraphUser/MicrosoftGraphUser.py
  Packs/MicrosoftGraphUser/Integrations/MicrosoftGraphUser/MicrosoftGraphUser.yml
  Packs/MicrosoftGraphUser/Integrations/MicrosoftGraphUser/README.md
  Packs/MicrosoftGraphUser/ReleaseNotes/1_1_0.md
  Packs/MicrosoftGraphUser/pack_metadata.json
Labels: docs-approved

#8459 Check mitmdump Process is Listening
  Tests/mock_server.py
Labels: docs-approved

#8437 New widget script for feedRelatedIndicators field
  Packs/CommonScripts/ReleaseNotes/1_2_30.md
  Packs/CommonScripts/Scripts/FeedRelatedIndicatorsWidget/FeedRelatedIndicatorsWidget.py
  Packs/CommonScripts/Scripts/FeedRelatedIndicatorsWidget/FeedRelatedIndicatorsWidget.yml
  Packs/CommonScripts/Scripts/FeedRelatedIndicatorsWidget/FeedRelatedIndicatorsWidget_test.py
  Packs/CommonScripts/Scripts/FeedRelatedIndicatorsWidget/README.md
  Packs/CommonScripts/pack_metadata.json
Labels: docs-approved

#8468 HIPAA + US Breach Notification Layout change + Bug fix in HIPAA layout
  Packs/BreachNotification-US/Layouts/layout-details-US_Breach_Notification-V2.json
  Packs/BreachNotification-US/Layouts/layout-details-US_Breach_Notification-V2_CHANGELOG.md
  Packs/BreachNotification-US/Layouts/layoutscontainer-US_Breach_Notification.json
  Packs/BreachNotification-US/ReleaseNotes/1_0_7.md
  Packs/BreachNotification-US/pack_metadata.json
  Packs/HIPAA-BreachNotification/Layouts/layout-details-HIPAA_Breach_Notification-V2.json
  Packs/HIPAA-BreachNotification/Layouts/layout-details-HIPAA_Breach_Notification-V2_CHANGELOG.md
  Packs/HIPAA-BreachNotification/Layouts/layoutscontainer-HIPAA_Breach_Notification.json
  Packs/HIPAA-BreachNotification/ReleaseNotes/1_0_7.md
  Packs/HIPAA-BreachNotification/pack_metadata.json
Labels: docs-approved

#8472 unskip cisco asa
  Tests/conf.json
Labels: docs-approved

#8469 claroty unskip
  Tests/conf.json
Labels: docs-approved

#8467 Minimum version of Demisto update
  .github/pull_request_template.md
Labels: docs-approved

#8371 mcafee esm - Bug fix of commands
  Packs/McAfee_ESM-v10/Integrations/McAfee_ESM-v10/McAfee_ESM-v10.py
  Packs/McAfee_ESM-v10/Integrations/McAfee_ESM-v10/McAfee_ESM-v10_test.py
  Packs/McAfee_ESM-v10/ReleaseNotes/1_0_1.md
  Packs/McAfee_ESM-v10/pack_metadata.json
Labels: docs-approved, release-notes-only

#8476 remock TghreatConnect v2
  Tests/conf.json
Labels: docs-approved

#8443 Add release notes and update sane-doc-reports
  Packs/Base/ReleaseNotes/1_1_11.md
  Packs/Base/Scripts/SaneDocReportV2/SaneDocReportV2.yml
  Packs/Base/pack_metadata.json
Labels: bug, docs-approved, release-notes-only

#8477 Eli/cortex xdr ioc test failure
  Packs/CortexXDR/TestPlaybooks/XDR_iocs_-_Test.yml
  Tests/conf.json
Labels: docs-approved

#8448 Scripts description to readme
  Packs/CommonScripts/ReleaseNotes/1_2_31.md
  Packs/CommonScripts/Scripts/TimeStampCompare/README.md
  Packs/CommonScripts/Scripts/TimeStampCompare/TimeStampCompare_description.md
  Packs/CommonScripts/Scripts/VerifyJSON/README.md
  Packs/CommonScripts/Scripts/VerifyJSON/VerifyJSON_description.md
  Packs/CommonScripts/pack_metadata.json
Labels: docs-approved, release-notes-only

#8297 FeedTAXII Added sleep before get-indicators task in tpb
  Packs/FeedTAXII/TestPlaybooks/playbook-TAXII_Feed_Test.yml
  Tests/conf.json
Labels: docs-approved

#8457 Added layout field to all STIX indicator types
  Packs/CommonTypes/.pack-ignore
  Packs/CommonTypes/IndicatorTypes/reputation-STIX_Attack_Pattern.json
  Packs/CommonTypes/IndicatorTypes/reputation-STIX_Malware.json
  Packs/CommonTypes/IndicatorTypes/reputation-STIX_Report.json
  Packs/CommonTypes/IndicatorTypes/reputation-STIX_Threat_Actor.json
  Packs/CommonTypes/IndicatorTypes/reputation-STIX_Tool.json
  Packs/CommonTypes/ReleaseNotes/1_8_2.md
  Packs/CommonTypes/pack_metadata.json
Labels: docs-approved

#8454 S/MIME Messaging README - improve usage section
  Packs/SMIME_Messaging/.secrets-ignore
  Packs/SMIME_Messaging/Integrations/SMIME_Messaging/README.md
Labels: docs-approved

#8446 Base64Encoder v2
  Packs/CommonScripts/Scripts/Base64EncodeV2/Base64EncodeV2.py
  Packs/CommonScripts/Scripts/Base64EncodeV2/Base64EncodeV2.yml
  Packs/CommonScripts/Scripts/Base64EncodeV2/Base64EncodeV2_test.py
  Packs/CommonScripts/Scripts/Base64EncodeV2/README.md
Labels: bug, docs-approved

#8474 reopening PR for Microsoft CAS
  Packs/CommonTypes/IncidentFields/incidentfield-Account_Name.json
  Packs/CommonTypes/IncidentFields/incidentfield-Cloud_Service.json
  Packs/CommonTypes/IncidentFields/incidentfield-Policy_Description.json
  Packs/CommonTypes/IncidentFields/incidentfield-Policy_Type.json
  Packs/CommonTypes/IncidentFields/incidentfield-Risk_Score.json
  Packs/CommonTypes/IncidentFields/incidentfield-Username.json
  Packs/CommonTypes/IncidentFields/incidentfield-country.json
  Packs/CommonTypes/ReleaseNotes/1_8_4.md
  Packs/CommonTypes/pack_metadata.json
  Packs/MicrosoftCloudAppSecurity/.pack-ignore
  Packs/MicrosoftCloudAppSecurity/.secrets-ignore
  Packs/MicrosoftCloudAppSecurity/Classifiers/classifier-MicrosoftCloudAppSecurity.json
  Packs/MicrosoftCloudAppSecurity/Classifiers/classifier-MicrosoftCloudAppSecurity_5_9_9.json
  Packs/MicrosoftCloudAppSecurity/Classifiers/classifier-mapper-incoming-MicrosoftCloudAppSecurity.json
  Packs/MicrosoftCloudAppSecurity/Integrations/MicrosoftCloudAppSecurity/MicrosoftCloudAppSecurity.py
  Packs/MicrosoftCloudAppSecurity/Integrations/MicrosoftCloudAppSecurity/MicrosoftCloudAppSecurity.yml
  Packs/MicrosoftCloudAppSecurity/Integrations/MicrosoftCloudAppSecurity/MicrosoftCloudAppSecurity_description.md
  Packs/MicrosoftCloudAppSecurity/Integrations/MicrosoftCloudAppSecurity/MicrosoftCloudAppSecurity_image.png
  Packs/MicrosoftCloudAppSecurity/Integrations/MicrosoftCloudAppSecurity/MicrosoftCloudAppSecurity_test.py
  Packs/MicrosoftCloudAppSecurity/Integrations/MicrosoftCloudAppSecurity/Pipfile
  Packs/MicrosoftCloudAppSecurity/Integrations/MicrosoftCloudAppSecurity/Pipfile.lock
  Packs/MicrosoftCloudAppSecurity/Integrations/MicrosoftCloudAppSecurity/README.md
  Packs/MicrosoftCloudAppSecurity/Integrations/MicrosoftCloudAppSecurity/test_data.json
  Packs/MicrosoftCloudAppSecurity/Layouts/layout-details-MicrosoftCloudAppSecurity.json
  Packs/MicrosoftCloudAppSecurity/README.md
  Packs/MicrosoftCloudAppSecurity/TestPlaybooks/MicrosoftCloudAppSecurity-Test.yml
  Packs/MicrosoftCloudAppSecurity/pack_metadata.json
  Tests/conf.json
Labels: docs-approved

#8482 Taxii feed sleep
  Packs/FeedTAXII/TestPlaybooks/playbook-TAXII_Feed_Test.yml
Labels: docs-approved

#8471 Private VirusTotal return clickable links
  Packs/VirusTotal-Private_API/Integrations/VirusTotal-Private_API/VirusTotal-Private_API.py
  Packs/VirusTotal-Private_API/ReleaseNotes/1_0_2.md
  Packs/VirusTotal-Private_API/pack_metadata.json
Labels: bug, docs-approved, release-notes-only

#8184 Maltiverse remove skipped
  Packs/Maltiverse/TestPlaybooks/playbook-Maltiverse_Test.yml
  Tests/conf.json
Labels: docs-approved

#8479 Slack README - fix link to oproxy
  Packs/Slack/Integrations/Slack/README.md
Labels: docs-approved

#8463 Added the new section - Feed Related Indicators
  Packs/CommonTypes/Layouts/layout-indicatorsDetails-Account.json
  Packs/CommonTypes/Layouts/layout-indicatorsDetails-Host.json
  Packs/CommonTypes/Layouts/layout-indicatorsDetails-cve.json
  Packs/CommonTypes/Layouts/layout-indicatorsDetails-domain.json
  Packs/CommonTypes/Layouts/layout-indicatorsDetails-email.json
  Packs/CommonTypes/Layouts/layout-indicatorsDetails-ip.json
  Packs/CommonTypes/Layouts/layout-indicatorsDetails-registryKey.json
  Packs/CommonTypes/Layouts/layout-indicatorsDetails-unifiedFile.json
  Packs/CommonTypes/Layouts/layout-indicatorsDetails-url.json
  Packs/CommonTypes/Layouts/layoutscontainer-Account.json
  Packs/CommonTypes/Layouts/layoutscontainer-Host.json
  Packs/CommonTypes/Layouts/layoutscontainer-STIX_Attack_Pattern.json
  Packs/CommonTypes/Layouts/layoutscontainer-STIX_Malware.json
  Packs/CommonTypes/Layouts/layoutscontainer-STIX_Report.json
  Packs/CommonTypes/Layouts/layoutscontainer-STIX_Threat_Actor.json
  Packs/CommonTypes/Layouts/layoutscontainer-STIX_Tool.json
  Packs/CommonTypes/Layouts/layoutscontainer-cve.json
  Packs/CommonTypes/Layouts/layoutscontainer-domain.json
  Packs/CommonTypes/Layouts/layoutscontainer-email.json
  Packs/CommonTypes/Layouts/layoutscontainer-ip.json
  Packs/CommonTypes/Layouts/layoutscontainer-registryKey.json
  Packs/CommonTypes/Layouts/layoutscontainer-unifiedFile.json
  Packs/CommonTypes/Layouts/layoutscontainer-url.json
  Packs/CommonTypes/ReleaseNotes/1_8_3.md
  Packs/CommonTypes/pack_metadata.json
Labels: docs-approved, release-notes-only

#8488 [Documentation] EWSO365 required permissions for self deployed app
  Packs/EWS/Integrations/EWSO365/README.md
Labels: docs-approved

#8481 Update sdk version to 1.1.9
  dev-requirements-py3.txt
Labels: docs-approved

#8157 move print statement to actual name of the instance being configured …
  Tests/mock_server.py
  Tests/test_integration.py
Labels: docs-approved

#8305 [code42-636] Improve documentation examples
  Packs/Code42/Integrations/Code42/Code42.yml
  Packs/Code42/Integrations/Code42/README.md
Labels: Contribution

#8491 Pcap fix
  Packs/PcapAnalysis/Playbooks/playbook-PCAP_Analysis.yml
  Packs/PcapAnalysis/Playbooks/playbook-PCAP_File_Carving.yml
  Packs/PcapAnalysis/Playbooks/playbook-PCAP_Parsing_And_Indicator_Enrichment.yml
  Packs/PcapAnalysis/Playbooks/playbook-PCAP_Parsing_And_Indicator_Enrichment_README.md
  Packs/PcapAnalysis/ReleaseNotes/2_3_1.md
  Packs/PcapAnalysis/doc_files/PCAP_Parsing_And_Indicator_Enrichment.png
  Packs/PcapAnalysis/pack_metadata.json
Labels: docs-approved

#8492 Evaluate ml docker version bump
  Packs/ML/ReleaseNotes/1_1_1.md
  Packs/ML/Scripts/EvaluateMLModllAtProduction/EvaluateMLModllAtProduction.yml
  Packs/ML/TestPlaybooks/script-CreateIncidentsForEvaluateMLModllAtProduction.yml
  Packs/ML/pack_metadata.json
  Tests/conf.json
Labels: docs-approved

#8480 Cdl bug
  Packs/CortexDataLake/Integrations/CortexDataLake/CortexDataLake.py
  Packs/CortexDataLake/Integrations/CortexDataLake/CortexDataLake.yml
  Packs/CortexDataLake/Integrations/CortexDataLake/CortexDataLake_test.py
  Packs/CortexDataLake/ReleaseNotes/1_2_0.md
  Packs/CortexDataLake/pack_metadata.json
Labels: bug, docs-approved, release-notes-only

#8500 Mispfailure
  Tests/conf.json
Labels: docs-approved, release-notes-only

#8512 LogRhythm Test - change tested alarm ID
  Packs/LogRhythm/TestPlaybooks/playbook-LogRhythm_Test_Playbook.yml
Labels: docs-approved

#8411 [Fix] Error when pulling emails from O365
  Packs/EWS/Integrations/EWSO365/EWSO365.py
  Packs/EWS/Integrations/EWSO365/EWSO365.yml
  Packs/EWS/Integrations/EWSO365/EWSO365_test.py
  Packs/EWS/ReleaseNotes/1_2_1.md
  Packs/EWS/pack_metadata.json
Labels: bug, docs-approved, release-notes-only

#8495 updated stix prefixes to all related indicator fields
  Packs/CommonTypes/IndicatorFields/indicatorfield-STIX_Aliases.json
  Packs/CommonTypes/IndicatorFields/indicatorfield-STIX_Description.json
  Packs/CommonTypes/IndicatorFields/indicatorfield-STIX_Goals.json
  Packs/CommonTypes/IndicatorFields/indicatorfield-STIX_ID.json
  Packs/CommonTypes/IndicatorFields/indicatorfield-STIX_Is_Malware_Family.json
  Packs/CommonTypes/IndicatorFields/indicatorfield-STIX_Kill_Chain_Phases.json
  Packs/CommonTypes/IndicatorFields/indicatorfield-STIX_Malware_Types.json
  Packs/CommonTypes/IndicatorFields/indicatorfield-STIX_Primary_Motivation.json
  Packs/CommonTypes/IndicatorFields/indicatorfield-STIX_Resource_Level.json
  Packs/CommonTypes/IndicatorFields/indicatorfield-STIX_Roles.json
  Packs/CommonTypes/IndicatorFields/indicatorfield-STIX_Secondary_Motivations.json
  Packs/CommonTypes/IndicatorFields/indicatorfield-STIX_Sophistication.json
  Packs/CommonTypes/IndicatorFields/indicatorfield-STIX_Threat_Actor_Types.json
  Packs/CommonTypes/IndicatorFields/indicatorfield-STIX_Tool_Types.json
  Packs/CommonTypes/IndicatorFields/indicatorfield-STIX_Tool_Version.json
  Packs/CommonTypes/ReleaseNotes/1_8_4.md
  Packs/CommonTypes/pack_metadata.json
Labels: docs-approved, release-notes-only

#8324 Create MailListener v2
  Packs/MailListener/.pack-ignore
  Packs/MailListener/.secrets-ignore
  Packs/MailListener/Integrations/MailListenerV2/MailListenerV2.py
  Packs/MailListener/Integrations/MailListenerV2/MailListenerV2.yml
  Packs/MailListener/Integrations/MailListenerV2/MailListenerV2_description.md
  Packs/MailListener/Integrations/MailListenerV2/MailListenerV2_image.png
  Packs/MailListener/Integrations/MailListenerV2/MailListenerV2_test.py
  Packs/MailListener/Integrations/MailListenerV2/Pipfile
  Packs/MailListener/Integrations/MailListenerV2/Pipfile.lock
  Packs/MailListener/Integrations/MailListenerV2/README.md
  Packs/MailListener/Integrations/MailListenerV2/commands.txt
  Packs/MailListener/README.md
  Packs/MailListener/TestPlaybooks/playbook-MailListener_Test.yml
  Packs/MailListener/pack_metadata.json
  Tests/conf.json
Labels: docs-approved

#8497 Remove playbooks that don't work with EWSO365 integration from Docs
  Packs/EWS/Integrations/EWSO365/README.md
Labels: Contribution, docs-approved

#8496 CDL - Added 2 new outputs and field args
  Packs/CortexDataLake/Integrations/CortexDataLake/CortexDataLake.py
  Packs/CortexDataLake/Integrations/CortexDataLake/CortexDataLake.yml
  Packs/CortexDataLake/Integrations/CortexDataLake/README.md
  Packs/CortexDataLake/ReleaseNotes/1_2_1.md
  Packs/CortexDataLake/pack_metadata.json
Labels: docs-approved

#8494 Contrib/code42 master
  Packs/Code42/Integrations/Code42/Code42.yml
  Packs/Code42/Integrations/Code42/README.md
  Packs/Code42/ReleaseNotes/2_0_2.md
  Packs/Code42/pack_metadata.json
Labels: docs-approved

#8514 pcap file carving - readme inputs fix
  Packs/PcapAnalysis/Playbooks/playbook-PCAP_File_Carving_README.md
Labels: docs-approved

#8466 added mirroring functionality as part of CommonServerPython.py
  Documentation/common_server_docs.py
  Packs/Base/ReleaseNotes/1_1_12.md
  Packs/Base/Scripts/CommonServerPython/CommonServerPython.py
  Packs/Base/Scripts/CommonServerPython/CommonServerPython_test.py
  Packs/Base/pack_metadata.json
Labels: docs-approved, release-notes-only

#8342 Added tasks that save email attachment information +renewed images
  Packs/Phishing/Playbooks/Process_Email_-_Core.yml
  Packs/Phishing/Playbooks/Process_Email_-_Core_README.md
  Packs/Phishing/Playbooks/Process_Email_-_Generic.yml
  Packs/Phishing/Playbooks/Process_Email_-_Generic_README.md
  Packs/Phishing/ReleaseNotes/1_9_0.md
  Packs/Phishing/doc_files/Process_Email_-_Core.png
  Packs/Phishing/doc_files/Process_Email_-_Generic.png
  Packs/Phishing/pack_metadata.json
  Tests/conf.json
Labels: docs-approved

#8493 adding report download command to ThreatConnect v2
  Packs/ThreatConnect/Integrations/ThreatConnect_v2/ThreatConnect_v2.py
  Packs/ThreatConnect/Integrations/ThreatConnect_v2/ThreatConnect_v2.yml
  Packs/ThreatConnect/ReleaseNotes/2_0_4.md
  Packs/ThreatConnect/TestPlaybooks/ThreatConnect_v2_-_Test.yml
  Packs/ThreatConnect/pack_metadata.json
Labels: docs-approved, enhancement

#8521 McAfee - Edit case issue
  Packs/McAfee_ESM-v10/Integrations/McAfee_ESM-v10/McAfee_ESM-v10.py
  Packs/McAfee_ESM-v10/ReleaseNotes/1_0_2.md
  Packs/McAfee_ESM-v10/pack_metadata.json
Labels: bug, docs-approved, release-notes-only

#8519 Gmail bugfix send mail
  Packs/Gmail/Integrations/Gmail/Gmail.py
  Packs/Gmail/Integrations/Gmail/Gmail.yml
  Packs/Gmail/ReleaseNotes/1_0_4.md
  Packs/Gmail/pack_metadata.json
Labels: docs-approved

#8503 Fixed context outputs - FailedInstances Script
  Packs/CommonScripts/ReleaseNotes/1_2_32.md
  Packs/CommonScripts/Scripts/script-FailedInstances.yml
  Packs/CommonScripts/Scripts/script-FailedInstances_README.md
  Packs/CommonScripts/TestPlaybooks/playbook-FailedInstances_-_Test.yml
  Packs/CommonScripts/pack_metadata.json
Labels: docs-approved

#8410 SetMultipleValues_README: add example
  Packs/CommonScripts/Scripts/script-SetMultipleValues_README.md
Labels: docs-approved

#8475 PassiveTotal - limit MD of enrichment cmds
  Packs/PassiveTotal/Integrations/integration-PassiveTotal.yml
  Packs/PassiveTotal/ReleaseNotes/1_0_1.md
  Packs/PassiveTotal/pack_metadata.json
Labels: bug, docs-approved, release-notes-only

#8401 Fetch data fixes
  Packs/Base/Scripts/DBotMLFetchData/DBotMLFetchData.py
  Packs/Base/Scripts/DBotMLFetchData/DBotMLFetchData.yml
Labels: docs-approved

#8505 Updated tests that use Minemeld
  Packs/CommonPlaybooks/TestPlaybooks/playbook-Calculate_Severity_-_Generic_v2_-_Test.yml
  TestPlaybooks/NonCircleTests/Deprecated/playbook-Block_Indicators_-_Generic_-_Test.yml
  TestPlaybooks/NonCircleTests/Deprecated/playbook-Block_Indicators_-_Generic_-_Test_CHANGELOG.md
Labels: docs-approved

#8532 skipping Cortex XDR - IOC - Test
  Tests/conf.json
Labels: docs-approved

#8522 Microsoft Graph User - fixed list users paging
  Packs/MicrosoftGraphUser/Integrations/MicrosoftGraphUser/MicrosoftGraphUser.py
  Packs/MicrosoftGraphUser/Integrations/MicrosoftGraphUser/MicrosoftGraphUser.yml
  Packs/MicrosoftGraphUser/ReleaseNotes/1_2_0.md
  Packs/MicrosoftGraphUser/pack_metadata.json
Labels: bug, docs-approved, release-notes-only

#8439 Zip marketplace-dist instead of marketplace-ci-build
  .circleci/config.yml
  Tests/Marketplace/zip_packs.py
Labels: docs-approved

#8238 GitHub IT Admin
  Packs/GitHubITAdmin/.pack-ignore
  Packs/GitHubITAdmin/.secrets-ignore
  Packs/GitHubITAdmin/Integrations/GitHub_IT_Admin/GitHub_IT_Admin.py
  Packs/GitHubITAdmin/Integrations/GitHub_IT_Admin/GitHub_IT_Admin.yml
  Packs/GitHubITAdmin/Integrations/GitHub_IT_Admin/GitHub_IT_Admin_image.png
  Packs/GitHubITAdmin/Integrations/GitHub_IT_Admin/GitHub_IT_Admin_test.py
  Packs/GitHubITAdmin/Integrations/GitHub_IT_Admin/Pipfile
  Packs/GitHubITAdmin/Integrations/GitHub_IT_Admin/Pipfile.lock
  Packs/GitHubITAdmin/Integrations/GitHub_IT_Admin/README.md
  Packs/GitHubITAdmin/Integrations/GitHub_IT_Admin/commands_examples.txt
  Packs/GitHubITAdmin/README.md
  Packs/GitHubITAdmin/TestPlaybooks/playbook-GitHubITAdmin-Test.yml
  Packs/GitHubITAdmin/pack_metadata.json
Labels: Contribution, docs-approved

#8548 bump 20.8.1
  .circleci/config.yml
Labels: docs-approved

#8530 Updated CheckPhish
  Packs/CheckPhish/Integrations/CheckPhish/CheckPhish.py
  Packs/CheckPhish/Integrations/CheckPhish/CheckPhish.yml
  Packs/CheckPhish/ReleaseNotes/1_0_1.md
  Packs/CheckPhish/TestPlaybooks/playbook-CheckPhish-Test.yml
  Packs/CheckPhish/pack_metadata.json
  Tests/conf.json
Labels: docs-approved, release-notes-only

#8536 sync base branch with master
  .github/workflows/sync-contribution-base-branch.yml
  Utils/contribution_sync/Pipfile
  Utils/contribution_sync/Pipfile.lock
  Utils/contribution_sync/sync_contrib_base.py
Labels: docs-approved

#8550 Update pull_request_template.md
  .github/pull_request_template.md
Labels: docs-approved

#8563 removed schemas from content repo
  Tests/schemas/canvas-context-connections.yml
  Tests/schemas/canvas-context-connections_CHANGELOG.md
  Tests/schemas/classifier.yml
  Tests/schemas/dashboard.yml
  Tests/schemas/dashboard_CHANGELOG.md
  Tests/schemas/incidentfield.yml
  Tests/schemas/incidentfields.yml
  Tests/schemas/incidentfields_CHANGELOG.md
  Tests/schemas/integration.yml
  Tests/schemas/integration_CHANGELOG.md
  Tests/schemas/layout.yml
  Tests/schemas/playbook.yml
  Tests/schemas/playbook_CHANGELOG.md
  Tests/schemas/report.yml
  Tests/schemas/report_CHANGELOG.md
  Tests/schemas/script.yml
  Tests/schemas/script_CHANGELOG.md
  Tests/schemas/widget.yml
  Tests/schemas/widget_CHANGELOG.md
Labels: docs-approved

#8552 Crowdstrike Falcon X - emphasising the file identifiers change in the readme
  Packs/CrowdStrikeFalconX/Integrations/CrowdStrikeFalconX/README.md
Labels: content, docs-approved, release-notes-only

#8540 Adding raw json parser for SplunkPy raw parser
  Packs/SplunkPy/Integrations/SplunkPy/SplunkPy.py
  Packs/SplunkPy/Integrations/SplunkPy/SplunkPy.yml
  Packs/SplunkPy/Integrations/SplunkPy/SplunkPy_test.py
  Packs/SplunkPy/ReleaseNotes/1_1_2.md
  Packs/SplunkPy/TestPlaybooks/SplunkPy_KV_commands.yml
  Packs/SplunkPy/TestPlaybooks/playbook-SplunkPy_parse-raw_-_Test.yml
  Packs/SplunkPy/pack_metadata.json
  Tests/conf.json
Labels: bug, docs-approved, release-notes-only

#7812 Initial commit for NTT Ltd. Cyber Threat Sensor integration
  Packs/NTT_Cyber_Threat_Sensor/.pack-ignore
  Packs/NTT_Cyber_Threat_Sensor/.secrets-ignore
  Packs/NTT_Cyber_Threat_Sensor/Classifiers/classifier-NTT_Cyber_Threat_Sensor.json
  Packs/NTT_Cyber_Threat_Sensor/Classifiers/classifier-NTT_Cyber_Threat_Sensor_5_9_9.json
  Packs/NTT_Cyber_Threat_Sensor/Classifiers/classifier-mapper-incoming-NTT_Cyber_Threat_Sensor.json
  Packs/NTT_Cyber_Threat_Sensor/IncidentFields/incidentfield-faeredesc.json
  Packs/NTT_Cyber_Threat_Sensor/IncidentFields/incidentfield-graphplot.json
  Packs/NTT_Cyber_Threat_Sensor/IncidentTypes/NTT_TD_Incident.json
  Packs/NTT_Cyber_Threat_Sensor/Integrations/NTT_Cyber_Threat_Sensor/NTT_Cyber_Threat_Sensor.py
  Packs/NTT_Cyber_Threat_Sensor/Integrations/NTT_Cyber_Threat_Sensor/NTT_Cyber_Threat_Sensor.yml
  Packs/NTT_Cyber_Threat_Sensor/Integrations/NTT_Cyber_Threat_Sensor/NTT_Cyber_Threat_Sensor_description.md
  Packs/NTT_Cyber_Threat_Sensor/Integrations/NTT_Cyber_Threat_Sensor/NTT_Cyber_Threat_Sensor_image.png
  Packs/NTT_Cyber_Threat_Sensor/Integrations/NTT_Cyber_Threat_Sensor/README.md
  Packs/NTT_Cyber_Threat_Sensor/Integrations/NTT_Cyber_Threat_Sensor/command_examples.txt
  Packs/NTT_Cyber_Threat_Sensor/Layouts/layout-details-TD_Incident.json
  Packs/NTT_Cyber_Threat_Sensor/Layouts/layoutscontainer-TD_Incident.json
  Packs/NTT_Cyber_Threat_Sensor/Playbooks/Handle_TD_events.yml
  Packs/NTT_Cyber_Threat_Sensor/Playbooks/Handle_TD_events_README.md
  Packs/NTT_Cyber_Threat_Sensor/README.md
  Packs/NTT_Cyber_Threat_Sensor/doc_files/Handle_TD_events.png
  Packs/NTT_Cyber_Threat_Sensor/pack_metadata.json
Labels: Contribution, docs-approved

#8568 Fix Contribution Base Branch Sync Workflow
  Utils/contribution_sync/sync_contrib_base.py
Labels: docs-approved

#8528 fix WhereFieldEquals returns string instead of list
  Packs/CommonScripts/ReleaseNotes/1_2_33.md
  Packs/CommonScripts/Scripts/WhereFieldEquals/WhereFieldEquals.py
  Packs/CommonScripts/Scripts/WhereFieldEquals/WhereFieldEquals.yml
  Packs/CommonScripts/pack_metadata.json
Labels: docs-approved
