Repository demisto/content, pull requests merged in 2020-09, with the labels that each got.

#7198 Initial Bonusly Package Content
  Packs/Bonusly/.pack-ignore
  Packs/Bonusly/.secrets-ignore
  Packs/Bonusly/Integrations/Bonusly/Bonusly.py
  Packs/Bonusly/Integrations/Bonusly/Bonusly.yml
  Packs/Bonusly/Integrations/Bonusly/Bonusly_description.md
  Packs/Bonusly/Integrations/Bonusly/Bonusly_image.png
  Packs/Bonusly/Integrations/Bonusly/Bonusly_test.py
  Packs/Bonusly/Integrations/Bonusly/CHANGELOG.md
  Packs/Bonusly/Integrations/Bonusly/Pipfile
  Packs/Bonusly/Integrations/Bonusly/Pipfile.lock
  Packs/Bonusly/Integrations/Bonusly/README.md
  Packs/Bonusly/Integrations/Bonusly/command_examples.txt
  Packs/Bonusly/Playbooks/Bonusly_-_AutoGratitude.yml
  Packs/Bonusly/Playbooks/Bonusly_-_AutoGratitude_README.md
  Packs/Bonusly/README.md
  Packs/Bonusly/Scripts/IncOwnerToBonuslyUser/CHANGELOG.md
  Packs/Bonusly/Scripts/IncOwnerToBonuslyUser/IncOwnerToBonuslyUser.py
  Packs/Bonusly/Scripts/IncOwnerToBonuslyUser/IncOwnerToBonuslyUser.yml
  Packs/Bonusly/Scripts/IncOwnerToBonuslyUser/Pipfile
  Packs/Bonusly/Scripts/IncOwnerToBonuslyUser/Pipfile.lock
  Packs/Bonusly/Scripts/IncOwnerToBonuslyUser/README.md
  Packs/Bonusly/TestPlaybooks/Bonusly-Test.yml
  Packs/Bonusly/doc_files/Bonusly_-_AutoGratitude.png
  Packs/Bonusly/pack_metadata.json
  Tests/conf.json
Labels: Contribution, docs-approved

#8755 Changed pack display name and layout image
  Packs/EmailCommunication/Layouts/layoutscontainer-Email_Communication.json
  Packs/EmailCommunication/README.md
  Packs/EmailCommunication/ReleaseNotes/1_2_1.md
  Packs/EmailCommunication/doc_files/Email_Communication_layout.png
  Packs/EmailCommunication/pack_metadata.json
Labels: docs-approved

#8732 [sixgill-195] darkfeed new feeds
  Packs/Sixgill-Darkfeed/Integrations/Sixgill_Darkfeed/README.md
  Packs/Sixgill-Darkfeed/Integrations/Sixgill_Darkfeed/Sixgill_Darkfeed.py
  Packs/Sixgill-Darkfeed/Integrations/Sixgill_Darkfeed/Sixgill_Darkfeed.yml
  Packs/Sixgill-Darkfeed/README.md
  Packs/Sixgill-Darkfeed/ReleaseNotes/1_1_4.md
  Packs/Sixgill-Darkfeed/Scripts/SearchIndicators/SearchIndicators.yml
  Packs/Sixgill-Darkfeed/pack_metadata.json
Labels: Contribution, docs-approved, release-notes-only

#8761 skip intsight as 401
  Tests/conf.json
Labels: docs-approved

#8738 ArcSight ESM v2 - Changed the hard limit of each fetch to be 300 instead of 50. Recommended limit is 50
  Packs/ArcSightESM/Integrations/ArcSightESMv2/ArcSightESMv2.py
  Packs/ArcSightESM/Integrations/ArcSightESMv2/ArcSightESMv2.yml
  Packs/ArcSightESM/Integrations/ArcSightESMv2/README.md
  Packs/ArcSightESM/ReleaseNotes/1_0_6.md
  Packs/ArcSightESM/pack_metadata.json
Labels: docs-approved

#8712 query-ai-3526: Updated QueryAI timeout
  Packs/QueryAI/Integrations/QueryAI/QueryAI.py
  Packs/QueryAI/Integrations/QueryAI/QueryAI.yml
  Packs/QueryAI/ReleaseNotes/1_0_1.md
  Packs/QueryAI/pack_metadata.json
Labels: Contribution, docs-approved

#8529 update master branch script (and minor fixes to old branch script)
  Utils/old_content_branch.py
  Utils/update_branch_from_version.py
Labels: docs-approved

#8730 RedCanary - redcanary-get-detection is causing timeout
  Packs/RedCanary/Integrations/RedCanary/RedCanary.py
  Packs/RedCanary/Integrations/RedCanary/RedCanary_test.py
  Packs/RedCanary/Integrations/RedCanary/TestData/get_full_timeline_raw1.json
  Packs/RedCanary/Integrations/RedCanary/TestData/get_full_timeline_raw2.json
  Packs/RedCanary/ReleaseNotes/1_0_4.md
  Packs/RedCanary/pack_metadata.json
Labels: bug, content, docs-approved, release-notes-only

#8764 adding splunk kv store commands to readme
  Packs/SplunkPy/Integrations/SplunkPy/README.md
  Packs/SplunkPy/Integrations/SplunkPy/commands.txt
Labels: bug, docs-approved

#8766 update docker version for sane-doc-report
  Packs/Base/ReleaseNotes/1_1_19.md
  Packs/Base/Scripts/SaneDocReportV2/SaneDocReportV2.yml
  Packs/Base/pack_metadata.json
Labels: docs-approved

#8666 Server logs internal
  Packs/ServerLogs/.pack-ignore
  Packs/ServerLogs/.secrets-ignore
  Packs/ServerLogs/Dashboards/dashboard-serverlogs.json
  Packs/ServerLogs/README.md
  Packs/ServerLogs/Scripts/ServerLogs/CHANGELOG.md
  Packs/ServerLogs/Scripts/ServerLogs/Pipfile
  Packs/ServerLogs/Scripts/ServerLogs/Pipfile.lock
  Packs/ServerLogs/Scripts/ServerLogs/README.md
  Packs/ServerLogs/Scripts/ServerLogs/ServerLogs.py
  Packs/ServerLogs/Scripts/ServerLogs/ServerLogs.yml
  Packs/ServerLogs/Scripts/ServerLogsDocker/CHANGELOG.md
  Packs/ServerLogs/Scripts/ServerLogsDocker/Pipfile
  Packs/ServerLogs/Scripts/ServerLogsDocker/Pipfile.lock
  Packs/ServerLogs/Scripts/ServerLogsDocker/README.md
  Packs/ServerLogs/Scripts/ServerLogsDocker/ServerLogsDocker.py
  Packs/ServerLogs/Scripts/ServerLogsDocker/ServerLogsDocker.yml
  Packs/ServerLogs/pack_metadata.json
Labels: Contribution, docs-approved

#8772 Bump 20.9.0
  .circleci/config.yml
Labels: docs-approved

#8773 updated release sdk
  dev-requirements-py3.txt
Labels: docs-approved

#8746 Get indicators by query
  Packs/Base/ReleaseNotes/1_1_20.md
  Packs/Base/Scripts/GetIndicatorsByQuery/GetIndicatorsByQuery.py
  Packs/Base/Scripts/GetIndicatorsByQuery/GetIndicatorsByQuery.yml
  Packs/Base/Scripts/GetIndicatorsByQuery/get_indicators_by_query_test.py
  Packs/Base/pack_metadata.json
Labels: docs-approved

#8662 addind list support ews o365
  Packs/EWS/Integrations/EWSO365/EWSO365.py
  Packs/EWS/ReleaseNotes/1_2_3.md
  Packs/EWS/pack_metadata.json
Labels: bug, docs-approved, release-notes-only

#8726 SNOW - mirroring default params
  Packs/ServiceNow/Integrations/ServiceNowv2/ServiceNowv2.yml
  Packs/ServiceNow/ReleaseNotes/1_2_2.md
  Packs/ServiceNow/pack_metadata.json
Labels: docs-approved

#8680 Hash incidents fields improve
  Packs/ML/ReleaseNotes/1_1_2.md
  Packs/ML/Scripts/HashIncidentsFields/HashIncidentFields_test.py
  Packs/ML/Scripts/HashIncidentsFields/HashIncidentsFields.py
  Packs/ML/Scripts/HashIncidentsFields/HashIncidentsFields.yml
  Packs/ML/pack_metadata.json
Labels: docs-approved

#8449 Adding widgets for largest incidents and largest inputs and outputs
  Packs/CommonWidgets/Scripts/GetLargestInputsAndOuputsInIncidents/GetLargestInputsAndOuputsInIncidents.py
  Packs/CommonWidgets/Scripts/GetLargestInputsAndOuputsInIncidents/GetLargestInputsAndOuputsInIncidents.yml
  Packs/CommonWidgets/Scripts/GetLargestInputsAndOuputsInIncidents/GetLargestInputsAndOuputsInIncidents_test.py
  Packs/CommonWidgets/Scripts/GetLargestInvestigations/GetLargestInvestigations.py
  Packs/CommonWidgets/Scripts/GetLargestInvestigations/GetLargestInvestigations.yml
  Packs/CommonWidgets/Scripts/GetLargestInvestigations/GetLargestInvestigations_test.py
  Packs/CommonWidgets/Widgets/widget-LargestInputsAndOuputsInIncidentsWidget.json
  Packs/CommonWidgets/Widgets/widget-LargestInvestigationsWidget.json
Labels: docs-approved

#8510 Atlassian cloud it admin
  Packs/AtlassianCloudITAdmin/.pack-ignore
  Packs/AtlassianCloudITAdmin/.secrets-ignore
  Packs/AtlassianCloudITAdmin/Integrations/Atlassian_Cloud_IT_Admin/Atlassian_Cloud_IT_Admin.py
  Packs/AtlassianCloudITAdmin/Integrations/Atlassian_Cloud_IT_Admin/Atlassian_Cloud_IT_Admin.yml
  Packs/AtlassianCloudITAdmin/Integrations/Atlassian_Cloud_IT_Admin/Atlassian_Cloud_IT_Admin_description.md
  Packs/AtlassianCloudITAdmin/Integrations/Atlassian_Cloud_IT_Admin/Atlassian_Cloud_IT_Admin_image.png
  Packs/AtlassianCloudITAdmin/Integrations/Atlassian_Cloud_IT_Admin/Atlassian_Cloud_IT_Admin_test.py
  Packs/AtlassianCloudITAdmin/Integrations/Atlassian_Cloud_IT_Admin/Pipfile
  Packs/AtlassianCloudITAdmin/Integrations/Atlassian_Cloud_IT_Admin/Pipfile.lock
  Packs/AtlassianCloudITAdmin/Integrations/Atlassian_Cloud_IT_Admin/README.md
  Packs/AtlassianCloudITAdmin/Integrations/Atlassian_Cloud_IT_Admin/command-example.txt
  Packs/AtlassianCloudITAdmin/README.md
  Packs/AtlassianCloudITAdmin/TestPlaybooks/NonCircleTests/playbook-Atlassian_Cloud_IT_Admin.yml
  Packs/AtlassianCloudITAdmin/pack_metadata.json
Labels: Contribution, IAM, docs-approved

#8484 Salesforce IT Admin
  Packs/SalesforceITAdmin/.pack-ignore
  Packs/SalesforceITAdmin/.secrets-ignore
  Packs/SalesforceITAdmin/Integrations/Salesforce_IT_Admin/.secrets-ignore
  Packs/SalesforceITAdmin/Integrations/Salesforce_IT_Admin/Pipfile
  Packs/SalesforceITAdmin/Integrations/Salesforce_IT_Admin/Pipfile.lock
  Packs/SalesforceITAdmin/Integrations/Salesforce_IT_Admin/README.md
  Packs/SalesforceITAdmin/Integrations/Salesforce_IT_Admin/Salesforce_IT_Admin.py
  Packs/SalesforceITAdmin/Integrations/Salesforce_IT_Admin/Salesforce_IT_Admin.yml
  Packs/SalesforceITAdmin/Integrations/Salesforce_IT_Admin/Salesforce_IT_Admin_description.md
  Packs/SalesforceITAdmin/Integrations/Salesforce_IT_Admin/Salesforce_IT_Admin_image.png
  Packs/SalesforceITAdmin/Integrations/Salesforce_IT_Admin/Salesforce_IT_Admin_test.py
  Packs/SalesforceITAdmin/Integrations/Salesforce_IT_Admin/command-examples.txt
  Packs/SalesforceITAdmin/README.md
  Packs/SalesforceITAdmin/TestPlaybooks/NonCircleTests/playbook-SalesforceITAdmin-Test.yml
  Packs/SalesforceITAdmin/pack_metadata.json
Labels: Contribution, IAM, docs-approved

#8504 ServiceNowITAdmin:Added new integration
  Packs/ServiceNowITAdmin/.pack-ignore
  Packs/ServiceNowITAdmin/.secrets-ignore
  Packs/ServiceNowITAdmin/Integrations/ServiceNow_IT_Admin/Pipfile
  Packs/ServiceNowITAdmin/Integrations/ServiceNow_IT_Admin/Pipfile.lock
  Packs/ServiceNowITAdmin/Integrations/ServiceNow_IT_Admin/README.md
  Packs/ServiceNowITAdmin/Integrations/ServiceNow_IT_Admin/ServiceNow_IT_Admin.py
  Packs/ServiceNowITAdmin/Integrations/ServiceNow_IT_Admin/ServiceNow_IT_Admin.yml
  Packs/ServiceNowITAdmin/Integrations/ServiceNow_IT_Admin/ServiceNow_IT_Admin_image.png
  Packs/ServiceNowITAdmin/Integrations/ServiceNow_IT_Admin/ServiceNow_IT_Admin_test.py
  Packs/ServiceNowITAdmin/Integrations/ServiceNow_IT_Admin/commands_examples.txt
  Packs/ServiceNowITAdmin/README.md
  Packs/ServiceNowITAdmin/TestPlaybooks/NonCircleTests/playbook-ServiceNowITAdmin-Test.yml
  Packs/ServiceNowITAdmin/pack_metadata.json
Labels: Contribution, IAM

#8511 Zoom it admin
  Packs/ZoomITAdmin/.pack-ignore
  Packs/ZoomITAdmin/.secrets-ignore
  Packs/ZoomITAdmin/Integrations/Zoom_IT_Admin/Pipfile
  Packs/ZoomITAdmin/Integrations/Zoom_IT_Admin/Pipfile.lock
  Packs/ZoomITAdmin/Integrations/Zoom_IT_Admin/README.md
  Packs/ZoomITAdmin/Integrations/Zoom_IT_Admin/Zoom_IT_Admin.py
  Packs/ZoomITAdmin/Integrations/Zoom_IT_Admin/Zoom_IT_Admin.yml
  Packs/ZoomITAdmin/Integrations/Zoom_IT_Admin/Zoom_IT_Admin_description.md
  Packs/ZoomITAdmin/Integrations/Zoom_IT_Admin/Zoom_IT_Admin_image.png
  Packs/ZoomITAdmin/Integrations/Zoom_IT_Admin/Zoom_IT_Admin_test.py
  Packs/ZoomITAdmin/Integrations/Zoom_IT_Admin/common-example.txt
  Packs/ZoomITAdmin/README.md
  Packs/ZoomITAdmin/TestPlaybooks/NonCircleTests/playbook-Zoom_IT_Admin.yml
  Packs/ZoomITAdmin/pack_metadata.json
Labels: Contribution, IAM

#8771 Checkout contrib remote branch exists fix
  Utils/checkout_contribution.sh
Labels: docs-approved

#8774 Manage credentials article link
  Packs/HashiCorp-Vault/Integrations/integration-HashiCorp-Vault_README.md
  Packs/cyberark_AIM/Integrations/integration-cyberark_AIM_README.md
Labels: docs-approved

#8702 adding created datetime to collected data
  Packs/Base/ReleaseNotes/1_1_21.md
  Packs/Base/Scripts/DBotMLFetchData/DBotMLFetchData.py
  Packs/Base/pack_metadata.json
Labels: docs-approved, release-notes-only

#8800 memory threshold increase
  Tests/conf.json
Labels: docs-approved

#8756 Palo Alto Networks IoT Security Automation Pack
  .circleci/config.yml
  Packs/PaloAltoNetworks_IoT/.pack-ignore
  Packs/PaloAltoNetworks_IoT/.secrets-ignore
  Packs/PaloAltoNetworks_IoT/IncidentFields/iot_incident_url.json
  Packs/PaloAltoNetworks_IoT/IncidentFields/servicenow_record_id.json
  Packs/PaloAltoNetworks_IoT/IncidentFields/servicenow_table_name.json
  Packs/PaloAltoNetworks_IoT/IncidentTypes/IoT_Alert.json
  Packs/PaloAltoNetworks_IoT/IncidentTypes/IoT_Vulnerability.json
  Packs/PaloAltoNetworks_IoT/Integrations/PaloAltoNetworks_IoT/PaloAltoNetworks_IoT.py
  Packs/PaloAltoNetworks_IoT/Integrations/PaloAltoNetworks_IoT/PaloAltoNetworks_IoT.yml
  Packs/PaloAltoNetworks_IoT/Integrations/PaloAltoNetworks_IoT/PaloAltoNetworks_IoT_description.md
  Packs/PaloAltoNetworks_IoT/Integrations/PaloAltoNetworks_IoT/PaloAltoNetworks_IoT_image.png
  Packs/PaloAltoNetworks_IoT/Integrations/PaloAltoNetworks_IoT/PaloAltoNetworks_IoT_test.py
  Packs/PaloAltoNetworks_IoT/Integrations/PaloAltoNetworks_IoT/Pipfile
  Packs/PaloAltoNetworks_IoT/Integrations/PaloAltoNetworks_IoT/Pipfile.lock
  Packs/PaloAltoNetworks_IoT/Integrations/PaloAltoNetworks_IoT/README.md
  Packs/PaloAltoNetworks_IoT/Playbooks/playbook-iot-check-servicenow.yml
  Packs/PaloAltoNetworks_IoT/Playbooks/playbook-iot-check-servicenow_README.md
  Packs/PaloAltoNetworks_IoT/Playbooks/playbook-iot-with-servicenow-playbook.yml
  Packs/PaloAltoNetworks_IoT/Playbooks/playbook-iot-with-servicenow-playbook_README.md
  Packs/PaloAltoNetworks_IoT/README.md
  Packs/PaloAltoNetworks_IoT/Scripts/iot_alert_post_processing/Pipfile
  Packs/PaloAltoNetworks_IoT/Scripts/iot_alert_post_processing/Pipfile.lock
  Packs/PaloAltoNetworks_IoT/Scripts/iot_alert_post_processing/README.md
  Packs/PaloAltoNetworks_IoT/Scripts/iot_alert_post_processing/iot_alert_post_processing.py
  Packs/PaloAltoNetworks_IoT/Scripts/iot_alert_post_processing/iot_alert_post_processing.yml
  Packs/PaloAltoNetworks_IoT/Scripts/iot_alert_post_processing/iot_alert_post_processing_description.md
  Packs/PaloAltoNetworks_IoT/Scripts/iot_alert_post_processing/iot_alert_post_processing_test.py
  Packs/PaloAltoNetworks_IoT/Scripts/iot_check_servicenow/Pipfile
  Packs/PaloAltoNetworks_IoT/Scripts/iot_check_servicenow/Pipfile.lock
  Packs/PaloAltoNetworks_IoT/Scripts/iot_check_servicenow/README.md
  Packs/PaloAltoNetworks_IoT/Scripts/iot_check_servicenow/iot_check_servicenow.py
  Packs/PaloAltoNetworks_IoT/Scripts/iot_check_servicenow/iot_check_servicenow.yml
  Packs/PaloAltoNetworks_IoT/Scripts/iot_check_servicenow/iot_check_servicenow_description.md
  Packs/PaloAltoNetworks_IoT/Scripts/iot_check_servicenow/iot_check_servicenow_test.py
  Packs/PaloAltoNetworks_IoT/Scripts/iot_get_raci/Pipfile
  Packs/PaloAltoNetworks_IoT/Scripts/iot_get_raci/Pipfile.lock
  Packs/PaloAltoNetworks_IoT/Scripts/iot_get_raci/README.md
  Packs/PaloAltoNetworks_IoT/Scripts/iot_get_raci/iot_get_raci.py
  Packs/PaloAltoNetworks_IoT/Scripts/iot_get_raci/iot_get_raci.yml
  Packs/PaloAltoNetworks_IoT/Scripts/iot_get_raci/iot_get_raci_description.md
  Packs/PaloAltoNetworks_IoT/Scripts/iot_get_raci/iot_get_raci_test.py
  Packs/PaloAltoNetworks_IoT/Scripts/iot_vuln_post_processing/Pipfile
  Packs/PaloAltoNetworks_IoT/Scripts/iot_vuln_post_processing/Pipfile.lock
  Packs/PaloAltoNetworks_IoT/Scripts/iot_vuln_post_processing/README.md
  Packs/PaloAltoNetworks_IoT/Scripts/iot_vuln_post_processing/iot_vuln_post_processing.py
  Packs/PaloAltoNetworks_IoT/Scripts/iot_vuln_post_processing/iot_vuln_post_processing.yml
  Packs/PaloAltoNetworks_IoT/Scripts/iot_vuln_post_processing/iot_vuln_post_processing_description.md
  Packs/PaloAltoNetworks_IoT/Scripts/iot_vuln_post_processing/iot_vuln_post_processing_test.py
  Packs/PaloAltoNetworks_IoT/TestPlaybooks/playbook-PaloAltoNetworks_IoT-Test.yml
  Packs/PaloAltoNetworks_IoT/pack_metadata.json
  docs/images/playbooks/Palo_Alto_Neworks_IoT_Security_Playbook.png
  docs/images/playbooks/Palo_Alto_Neworks_IoT_Security_ServiceNow_Check.png
Labels: Contribution, docs-approved

#8699 ThreatConnect v2 - Support multiple owners in fetching indicators
  Packs/ThreatConnect/Integrations/ThreatConnect_v2/ThreatConnect_v2.py
  Packs/ThreatConnect/Integrations/ThreatConnect_v2/ThreatConnect_v2_test.py
  Packs/ThreatConnect/ReleaseNotes/2_0_6.md
  Packs/ThreatConnect/pack_metadata.json
Labels: bug, docs-approved, release-notes-only

#8721 Update script-AssignAnalystToIncident_README.md
  Packs/CommonScripts/Scripts/script-AssignAnalystToIncident_README.md
Labels: docs-approved

#8485 Microsoft cloud app security integration
  Packs/CommonTypes/IncidentFields/incidentfield-Account_Name.json
  Packs/CommonTypes/IncidentFields/incidentfield-Cloud_Service.json
  Packs/CommonTypes/IncidentFields/incidentfield-Policy_Description.json
  Packs/CommonTypes/IncidentFields/incidentfield-Policy_Type.json
  Packs/CommonTypes/IncidentFields/incidentfield-Risk_Score.json
  Packs/CommonTypes/IncidentFields/incidentfield-Username.json
  Packs/CommonTypes/IncidentFields/incidentfield-country.json
  Packs/CommonTypes/ReleaseNotes/1_9_0.md
  Packs/CommonTypes/pack_metadata.json
  Packs/MicrosoftCloudAppSecurity/.pack-ignore
  Packs/MicrosoftCloudAppSecurity/.secrets-ignore
  Packs/MicrosoftCloudAppSecurity/Classifiers/classifier-MicrosoftCloudAppSecurity.json
  Packs/MicrosoftCloudAppSecurity/Classifiers/classifier-MicrosoftCloudAppSecurity_5_9_9.json
  Packs/MicrosoftCloudAppSecurity/Classifiers/classifier-mapper-incoming-MicrosoftCloudAppSecurity.json
  Packs/MicrosoftCloudAppSecurity/Integrations/MicrosoftCloudAppSecurity/MicrosoftCloudAppSecurity.py
  Packs/MicrosoftCloudAppSecurity/Integrations/MicrosoftCloudAppSecurity/MicrosoftCloudAppSecurity.yml
  Packs/MicrosoftCloudAppSecurity/Integrations/MicrosoftCloudAppSecurity/MicrosoftCloudAppSecurity_description.md
  Packs/MicrosoftCloudAppSecurity/Integrations/MicrosoftCloudAppSecurity/MicrosoftCloudAppSecurity_image.png
  Packs/MicrosoftCloudAppSecurity/Integrations/MicrosoftCloudAppSecurity/MicrosoftCloudAppSecurity_test.py
  Packs/MicrosoftCloudAppSecurity/Integrations/MicrosoftCloudAppSecurity/Pipfile
  Packs/MicrosoftCloudAppSecurity/Integrations/MicrosoftCloudAppSecurity/Pipfile.lock
  Packs/MicrosoftCloudAppSecurity/Integrations/MicrosoftCloudAppSecurity/README.md
  Packs/MicrosoftCloudAppSecurity/Integrations/MicrosoftCloudAppSecurity/test_data.json
  Packs/MicrosoftCloudAppSecurity/Layouts/layout-details-MicrosoftCloudAppSecurity.json
  Packs/MicrosoftCloudAppSecurity/README.md
  Packs/MicrosoftCloudAppSecurity/TestPlaybooks/MicrosoftCloudAppSecurity-Test.yml
  Packs/MicrosoftCloudAppSecurity/pack_metadata.json
  Tests/conf.json
Labels: docs-approved

#8241 Fix failure to parse p7m files by ParseEmailFiles
  Packs/CommonScripts/ReleaseNotes/1_2_35.md
  Packs/CommonScripts/Scripts/ParseEmailFiles/ParseEmailFiles.py
  Packs/CommonScripts/pack_metadata.json
Labels: bug, docs-approved, release-notes-only

#8777 Added to incidenttype the Layout to Email Communication
  Packs/EmailCommunication/IncidentTypes/incidenttype-Email_Communication.json
  Packs/EmailCommunication/ReleaseNotes/1_2_2.md
  Packs/EmailCommunication/pack_metadata.json
Labels: docs-approved

#8612 WorkdayITAdmin Initial checkin
  Packs/WorkdayITAdmin/.pack-ignore
  Packs/WorkdayITAdmin/.secrets-ignore
  Packs/WorkdayITAdmin/Integrations/Workday_IT_Admin/.secrets-ignore
  Packs/WorkdayITAdmin/Integrations/Workday_IT_Admin/Pipfile
  Packs/WorkdayITAdmin/Integrations/Workday_IT_Admin/Pipfile.lock
  Packs/WorkdayITAdmin/Integrations/Workday_IT_Admin/README.md
  Packs/WorkdayITAdmin/Integrations/Workday_IT_Admin/Workday_IT_Admin.py
  Packs/WorkdayITAdmin/Integrations/Workday_IT_Admin/Workday_IT_Admin.yml
  Packs/WorkdayITAdmin/Integrations/Workday_IT_Admin/Workday_IT_Admin_image.png
  Packs/WorkdayITAdmin/Integrations/Workday_IT_Admin/Workday_IT_Admin_test.py
  Packs/WorkdayITAdmin/Integrations/Workday_IT_Admin/command_examples.txt
  Packs/WorkdayITAdmin/README.md
  Packs/WorkdayITAdmin/TestPlaybooks/NonCircleTests/playbook-WorkdayITAdmin-Test.yml
  Packs/WorkdayITAdmin/pack_metadata.json
Labels: Contribution, IAM

#8642 Okta IT Admin
  Packs/OktaITAdmin/.pack-ignore
  Packs/OktaITAdmin/.secrets-ignore
  Packs/OktaITAdmin/Integrations/Okta_IT_Admin/Okta_IT_Admin.py
  Packs/OktaITAdmin/Integrations/Okta_IT_Admin/Okta_IT_Admin.yml
  Packs/OktaITAdmin/Integrations/Okta_IT_Admin/Okta_IT_Admin_description.md
  Packs/OktaITAdmin/Integrations/Okta_IT_Admin/Okta_IT_Admin_image.png
  Packs/OktaITAdmin/Integrations/Okta_IT_Admin/Okta_IT_Admin_test.py
  Packs/OktaITAdmin/Integrations/Okta_IT_Admin/Pipfile
  Packs/OktaITAdmin/Integrations/Okta_IT_Admin/Pipfile.lock
  Packs/OktaITAdmin/Integrations/Okta_IT_Admin/README.md
  Packs/OktaITAdmin/Integrations/Okta_IT_Admin/command-example.txt
  Packs/OktaITAdmin/README.md
  Packs/OktaITAdmin/TestPlaybooks/playbook-OktaITAdmin-Test.yml
  Packs/OktaITAdmin/pack_metadata.json
Labels: Contribution, IAM

#8754 ADPITAdmin Initial checkin
  Packs/ADPITAdmin/.pack-ignore
  Packs/ADPITAdmin/.secrets-ignore
  Packs/ADPITAdmin/Integrations/ADP_IT_Admin/ADP_IT_Admin.py
  Packs/ADPITAdmin/Integrations/ADP_IT_Admin/ADP_IT_Admin.yml
  Packs/ADPITAdmin/Integrations/ADP_IT_Admin/ADP_IT_Admin_image.png
  Packs/ADPITAdmin/Integrations/ADP_IT_Admin/ADP_IT_Admin_test.py
  Packs/ADPITAdmin/Integrations/ADP_IT_Admin/Pipfile
  Packs/ADPITAdmin/Integrations/ADP_IT_Admin/Pipfile.lock
  Packs/ADPITAdmin/Integrations/ADP_IT_Admin/README.md
  Packs/ADPITAdmin/Integrations/ADP_IT_Admin/command-examples.txt
  Packs/ADPITAdmin/README.md
  Packs/ADPITAdmin/TestPlaybooks/NonCircleTests/playbook-ADPITAdmin-Test.yml
  Packs/ADPITAdmin/pack_metadata.json
Labels: Contribution

#8821 Added the return_results function and the CommandResults class to the…
  Documentation/common_server_docs.py
  Packs/Base/ReleaseNotes/1_1_22.md
  Packs/Base/Scripts/CommonServerPython/CommonServerPython.py
  Packs/Base/pack_metadata.json
Labels: docs-approved, release-notes-only

#8823 update splunkpy tested version
  Packs/SplunkPy/Integrations/SplunkPy/README.md
Labels: docs-approved

#8822 MS Graph Security - fixed missing alerts
  Packs/MicrosoftGraphSecurity/Integrations/MicrosoftGraphSecurity/MicrosoftGraphSecurity.py
  Packs/MicrosoftGraphSecurity/Integrations/MicrosoftGraphSecurity/MicrosoftGraphSecurity.yml
  Packs/MicrosoftGraphSecurity/ReleaseNotes/2_0_1.md
  Packs/MicrosoftGraphSecurity/pack_metadata.json
Labels: bug, docs-approved, release-notes-only

#8769 OTRS Attachments Bug
  Packs/OTRS/Integrations/OTRS/OTRS.py
  Packs/OTRS/Integrations/OTRS/OTRS.yml
  Packs/OTRS/ReleaseNotes/1_0_1.md
  Packs/OTRS/pack_metadata.json
Labels: bug, docs-approved, release-notes-only

#8752 Zscaler Remove Protocol from url
  Packs/Zscaler/Integrations/Zscaler/Zscaler.py
  Packs/Zscaler/Integrations/Zscaler/Zscaler_test.py
  Packs/Zscaler/ReleaseNotes/1_0_4.md
  Packs/Zscaler/pack_metadata.json
Labels: bug, docs-approved, release-notes-only

#8722 test HEC url in test function
  Packs/SplunkPy/Integrations/SplunkPy/SplunkPy.py
  Packs/SplunkPy/ReleaseNotes/1_2_0.md
  Packs/SplunkPy/pack_metadata.json
Labels: docs-approved, release-notes-only

#8776 Moved update_tests_step to be before validation
  .circleci/config.yml
Labels: docs-approved

#8733 Urlscan.io
  Packs/UrlScan/Integrations/UrlScan/UrlScan.py
  Packs/UrlScan/ReleaseNotes/1_0_1.md
  Packs/UrlScan/pack_metadata.json
Labels: bug, docs-approved, release-notes-only

#8725 Servicenow v2 - fix in get_template function
  Packs/ServiceNow/Integrations/ServiceNowv2/ServiceNowv2.py
  Packs/ServiceNow/ReleaseNotes/1_2_3.md
  Packs/ServiceNow/pack_metadata.json
Labels: bug, docs-approved, release-notes-only

#8833 Skipping fidelis due to lack of creds
  Tests/conf.json
Labels: docs-approved

#8735 Graph Mail Single User README improvements
  Packs/MicrosoftGraphListener/Integrations/MicrosoftGraphListener/README.md
Labels: docs-approved

#8856 skip index check when force uploading a pack
  Tests/Marketplace/upload_packs.py
Labels: docs-approved

#8765 new commit flow for pack installation
  Tests/conf.json
  Tests/configure_and_test_integration_instances.py
Labels: docs-approved

#8775 Cybereason bugs
  Packs/Base/ReleaseNotes/1_2_0.md
  Packs/Base/Scripts/CommonServerPython/CommonServerPython.py
  Packs/Base/Scripts/CommonServerPython/CommonServerPython_test.py
  Packs/Base/pack_metadata.json
  Packs/Cybereason/Integrations/Cybereason/Cybereason.py
  Packs/Cybereason/ReleaseNotes/1_0_2.md
  Packs/Cybereason/TestPlaybooks/playbook-Cybereason_Test.yml
  Packs/Cybereason/pack_metadata.json
  Tests/conf.json
Labels: docs-approved

#8177 Tanium ask question fix
  Packs/Tanium/Integrations/Tanium_v2/Tanium_v2.py
  Packs/Tanium/ReleaseNotes/1_0_3.md
  Packs/Tanium/pack_metadata.json
Labels: docs-approved, release-notes-only

#8487 [trustar-150] Trustar v2 enhancements
  Packs/TruSTAR/Integrations/TruSTAR_V2/README.md
  Packs/TruSTAR/Integrations/TruSTAR_V2/TruSTAR_V2.py
  Packs/TruSTAR/Integrations/TruSTAR_V2/TruSTAR_V2.yml
  Packs/TruSTAR/ReleaseNotes/2_0_1.md
  Packs/TruSTAR/pack_metadata.json
Labels: Contribution, docs-approved

#8780 Alien Vault OTX V2 Bug
  Packs/AlienVault_OTX/Integrations/AlienVault_OTX_v2/AlienVault_OTX_v2.py
  Packs/AlienVault_OTX/Integrations/AlienVault_OTX_v2/AlienVault_OTX_v2.yml
  Packs/AlienVault_OTX/Integrations/AlienVault_OTX_v2/AlienVault_OTX_v2_test.py
  Packs/AlienVault_OTX/ReleaseNotes/1_0_2.md
  Packs/AlienVault_OTX/pack_metadata.json
Labels: bug, docs-approved, release-notes-only

#8845 Mimecast - bug in mimecast-get-group-members
  Packs/Mimecast/Integrations/MimecastV2/MimecastV2.py
  Packs/Mimecast/Integrations/MimecastV2/mimecastV2_test.py
  Packs/Mimecast/ReleaseNotes/1_1_2.md
  Packs/Mimecast/pack_metadata.json
Labels: bug, docs-approved, release-notes-only

#8860 RN for Widgets and scripts release
  Packs/CommonWidgets/ReleaseNotes/1_0_1.md
  Packs/CommonWidgets/pack_metadata.json
Labels: docs-approved, release-notes-only

#8836 fix double period issue
  Packs/CommonScripts/ReleaseNotes/1_2_37.md
  Packs/CommonScripts/Scripts/ParseEmailFiles/ParseEmailFiles.py
  Packs/CommonScripts/Scripts/ParseEmailFiles/parse_email_files_test.py
  Packs/CommonScripts/Scripts/ParseEmailFiles/test_data/multiple_to_cc.eml
  Packs/CommonScripts/pack_metadata.json
Labels: bug, docs-approved, release-notes-only

#8865 Unskipped DAG Configuration test playbook
  Tests/conf.json
Labels: docs-approved

#8724 Versioned integration context - add 5.5 build
  Packs/Base/ReleaseNotes/1_2_1.md
  Packs/Base/Scripts/CommonServerPython/CommonServerPython.py
  Packs/Base/Scripts/CommonServerPython/CommonServerPython_test.py
  Packs/Base/pack_metadata.json
Labels: docs-approved, release-notes-only

#8859 CVE Enrichment - Generic Test - Move to NonCircle
  TestPlaybooks/NonCircleTests/playbook-CVE_Enrichment_-_Generic_-_Test.yml
  Tests/conf.json
Labels: docs-approved

#8858 query-ai-3526: Updated QueryAI README
  Packs/QueryAI/Integrations/QueryAI/QueryAI_description.md
  Packs/QueryAI/Integrations/QueryAI/README.md
  Packs/QueryAI/README.md
  Packs/QueryAI/ReleaseNotes/1_0_2.md
  Packs/QueryAI/pack_metadata.json
Labels: Contribution, docs-approved

#8717 fix SetAndHandleEmpty script
  Packs/CommonScripts/ReleaseNotes/1_2_38.md
  Packs/CommonScripts/Scripts/SetAndHandleEmpty/.Dockerfile
  Packs/CommonScripts/Scripts/SetAndHandleEmpty/SetAndHandleEmpty.py
  Packs/CommonScripts/Scripts/SetAndHandleEmpty/SetAndHandleEmpty.yml
  Packs/CommonScripts/Scripts/SetAndHandleEmpty/SetAndHandleEmpty_test.py
  Packs/CommonScripts/pack_metadata.json
  Pipfile
  Pipfile.lock
Labels: bug, docs-approved, release-notes-only

#8869 Trustar dbot fix
  Packs/TruSTAR/Integrations/TruSTAR_V2/README.md
  Packs/TruSTAR/Integrations/TruSTAR_V2/TruSTAR_V2.py
  Packs/TruSTAR/Integrations/TruSTAR_V2/TruSTAR_V2.yml
  Packs/TruSTAR/ReleaseNotes/2_0_1.md
  Packs/TruSTAR/pack_metadata.json
Labels: docs-approved

#8832 Fix partner packs metadata
  Packs/DomainTools_Iris/Integrations/DomainTools_Iris/DomainTools_Iris.yml
  Packs/DomainTools_Iris/ReleaseNotes/1_0_3.md
  Packs/DomainTools_Iris/pack_metadata.json
  Packs/IronDefense/ReleaseNotes/1_1_2.md
  Packs/IronDefense/pack_metadata.json
  Packs/illuminate/ReleaseNotes/1_0_2.md
  Packs/illuminate/pack_metadata.json
  TestPlaybooks/NonCircleTests/playbook-DomainTools_Iris_Test.yml
  Tests/conf.json
Labels: docs-approved

#8763 ServiceNow Mirror Updates
  Packs/ServiceNow/Classifiers/classifier-mapper-incoming-ServiceNow.json
  Packs/ServiceNow/Integrations/ServiceNowv2/README.md
  Packs/ServiceNow/Integrations/ServiceNowv2/ServiceNowv2.py
  Packs/ServiceNow/Integrations/ServiceNowv2/ServiceNowv2.yml
  Packs/ServiceNow/Integrations/ServiceNowv2/ServiceNowv2_test.py
  Packs/ServiceNow/Integrations/ServiceNowv2/doc_files/closing-params.png
  Packs/ServiceNow/Integrations/ServiceNowv2/test_data/response_constants.py
  Packs/ServiceNow/ReleaseNotes/1_2_4.md
  Packs/ServiceNow/pack_metadata.json
Labels: docs-approved

#8861 PCAP Parsing And Indicator Enrichment Typo Fix
  Packs/PcapAnalysis/Playbooks/playbook-PCAP_Parsing_And_Indicator_Enrichment.yml
  Packs/PcapAnalysis/ReleaseNotes/2_3_2.md
  Packs/PcapAnalysis/pack_metadata.json
Labels: bug, docs-approved, release-notes-only

#8807 LookupCSV - Added support for comma separator inside CSV files
  Packs/CommonScripts/ReleaseNotes/1_2_39.md
  Packs/CommonScripts/Scripts/LookupCSV/LookupCSV.py
  Packs/CommonScripts/Scripts/LookupCSV/LookupCSV.yml
  Packs/CommonScripts/Scripts/LookupCSV/LookupCSV_test.py
  Packs/CommonScripts/Scripts/LookupCSV/TestData/comma_separator.csv
  Packs/CommonScripts/Scripts/LookupCSV/TestData/comma_separator_results.json
  Packs/CommonScripts/pack_metadata.json
Labels: bug, docs-approved, release-notes-only

#8878 Moved BPA to unmockable integrations.
  Tests/conf.json
Labels: docs-approved

#8711 SlackITAdmin
  Packs/SlackITAdmin/.pack-ignore
  Packs/SlackITAdmin/.secrets-ignore
  Packs/SlackITAdmin/Integrations/Slack_IT_Admin/Pipfile
  Packs/SlackITAdmin/Integrations/Slack_IT_Admin/Pipfile.lock
  Packs/SlackITAdmin/Integrations/Slack_IT_Admin/README.md
  Packs/SlackITAdmin/Integrations/Slack_IT_Admin/Slack_IT_Admin.py
  Packs/SlackITAdmin/Integrations/Slack_IT_Admin/Slack_IT_Admin.yml
  Packs/SlackITAdmin/Integrations/Slack_IT_Admin/Slack_IT_Admin_image.png
  Packs/SlackITAdmin/Integrations/Slack_IT_Admin/Slack_IT_Admin_test.py
  Packs/SlackITAdmin/Integrations/Slack_IT_Admin/command-examples.txt
  Packs/SlackITAdmin/README.md
  Packs/SlackITAdmin/TestPlaybooks/playbook-SlackITAdmin-Test.yml
  Packs/SlackITAdmin/pack_metadata.json
Labels: Contribution

#8873 query-ai-3526: Updated QueryAI README (#8858)
  Packs/QueryAI/Integrations/QueryAI/QueryAI_description.md
  Packs/QueryAI/Integrations/QueryAI/README.md
  Packs/QueryAI/README.md
  Packs/QueryAI/ReleaseNotes/1_0_2.md
  Packs/QueryAI/pack_metadata.json
Labels: docs-approved

#8875 Infinipoint rn fix
  Packs/Infinipoint/Integrations/Infinipoint/Infinipoint.py
  Packs/Infinipoint/Integrations/Infinipoint/Infinipoint.yml
  Packs/Infinipoint/Integrations/Infinipoint/Infinipoint_test.py
  Packs/Infinipoint/Integrations/Infinipoint/README.md
  Packs/Infinipoint/Integrations/Infinipoint/command_examples.txt
  Packs/Infinipoint/ReleaseNotes/1_0_2.md
  Packs/Infinipoint/TestPlaybooks/Infinipoint-Test.yml
  Packs/Infinipoint/pack_metadata.json
Labels: docs-approved

#8867 Corrected layout file paths
  Packs/CortexXDR/Layouts/layout-details-Cortex_XDR_Incident.json
  Packs/CortexXDR/Layouts/layout-details-Cortex_XDR_Port_Scan.json
  Packs/CortexXDR/ReleaseNotes/2_3_4.md
  Packs/CortexXDR/pack_metadata.json
  Packs/MicrosoftCloudAppSecurity/Layouts/layoutscontainer-details-MicrosoftCloudAppSecurity.json
  Packs/MicrosoftCloudAppSecurity/ReleaseNotes/1_0_1.md
  Packs/MicrosoftCloudAppSecurity/pack_metadata.json
  Packs/Pcysys/Layouts/layout-details-Pentera_Insight.json
  Packs/Pcysys/ReleaseNotes/1_0_2.md
  Packs/Pcysys/pack_metadata.json
Labels: docs-approved, release-notes-only

#8671 Ewso365 send mail
  Packs/EWS/.secrets-ignore
  Packs/EWS/Integrations/EWSO365/EWSO365.py
  Packs/EWS/Integrations/EWSO365/EWSO365.yml
  Packs/EWS/Integrations/EWSO365/EWSO365_test.py
  Packs/EWS/Integrations/EWSO365/README.md
  Packs/EWS/ReleaseNotes/1_3_0.md
  Packs/EWS/TestPlaybooks/playbook-EWS_O365_send_mail_test.yml
  Packs/EWS/TestPlaybooks/playbook-EWS_O365_test.yml
  Packs/EWS/pack_metadata.json
  Packs/Gmail/TestPlaybooks/playbook-GmailTest.yml
  Tests/conf.json
Labels: docs-approved

#8855 Support contribution instance build trigger
  .circleci/config.yml
  Utils/comment_on_pr.py
  Utils/tests/comment_on_pr_test.py
  Utils/tests/update_contribution_pack_in_base_branch_test.py
  Utils/update_contribution_pack_in_base_branch.py
Labels: docs-approved

#8872 fix
  Tests/conf.json
Labels: docs-approved

#8894 Gmail test - Reverted change to context ID
  Packs/Gmail/TestPlaybooks/playbook-GmailTest.yml
Labels: docs-approved

#8871 Elasticsearch v2 - add support for schema mapping
  Packs/Elasticsearch/Integrations/Elasticsearch_v2/Elasticsearch_v2.yml
  Packs/Elasticsearch/Integrations/Elasticsearch_v2/README.md
  Packs/Elasticsearch/ReleaseNotes/1_1_1.md
  Packs/Elasticsearch/pack_metadata.json
Labels: docs-approved

#8747 Add sort and fix where on _id field
  Packs/MongoDB/Integrations/MongoDB/MongoDB.py
  Packs/MongoDB/Integrations/MongoDB/MongoDB.yml
  Packs/MongoDB/Integrations/MongoDB/MongoDB_test.py
  Packs/MongoDB/Integrations/MongoDB/README.md
  Packs/MongoDB/ReleaseNotes/1_1_0.md
  Packs/MongoDB/pack_metadata.json
Labels: bug, docs-approved

#8863 fix Qradar broken link
  Packs/QRadar/Integrations/QRadar/QRadar_description.md
Labels: docs-approved

#8646 Artifacts circle config.yml change
  .circleci/config.yml
  dev-requirements-py3.txt
Labels: docs-approved

#8901 contrib pack flow - do not delete non existing pack
  Utils/update_contribution_pack_in_base_branch.py
Labels: docs-approved

#8906 Skip PyEWS
  Tests/conf.json
Labels: docs-approved

#8436 Azure Log Analytics
  Packs/ApiModules/ReleaseNotes/1_0_6.md
  Packs/ApiModules/Scripts/MicrosoftApiModule/MicrosoftApiModule.py
  Packs/ApiModules/Scripts/MicrosoftApiModule/MicrosoftApiModule.yml
  Packs/ApiModules/pack_metadata.json
  Packs/AzureLogAnalytics/.pack-ignore
  Packs/AzureLogAnalytics/.secrets-ignore
  Packs/AzureLogAnalytics/Integrations/AzureLogAnalytics/AzureLogAnalytics.py
  Packs/AzureLogAnalytics/Integrations/AzureLogAnalytics/AzureLogAnalytics.yml
  Packs/AzureLogAnalytics/Integrations/AzureLogAnalytics/AzureLogAnalytics_description.md
  Packs/AzureLogAnalytics/Integrations/AzureLogAnalytics/AzureLogAnalytics_image.png
  Packs/AzureLogAnalytics/Integrations/AzureLogAnalytics/AzureLogAnalytics_test.py
  Packs/AzureLogAnalytics/Integrations/AzureLogAnalytics/Pipfile
  Packs/AzureLogAnalytics/Integrations/AzureLogAnalytics/Pipfile.lock
  Packs/AzureLogAnalytics/Integrations/AzureLogAnalytics/README.md
  Packs/AzureLogAnalytics/Playbooks/AzureLogAnalytics_QuerySavedSearch.yml
  Packs/AzureLogAnalytics/README.md
  Packs/AzureLogAnalytics/TestPlaybooks/NonCircleTests/AzureLogAnalyticsTest.yml
  Packs/AzureLogAnalytics/pack_metadata.json
Labels: docs-approved

#8904 Contrib flow - do not destroy the instance
  .circleci/config.yml
Labels: docs-approved

#8831 Mindmeld changes
  Packs/DeprecatedContent/Integrations/PaloAlto_MineMeld/PaloAlto_MineMeld.py
  Packs/DeprecatedContent/Integrations/PaloAlto_MineMeld/PaloAlto_MineMeld.yml
  Packs/DeprecatedContent/ReleaseNotes/1_6_0.md
  Packs/DeprecatedContent/pack_metadata.json
Labels: docs-approved

#8892 fixed xsoar linter
  Packs/Base/ReleaseNotes/1_2_2.md
  Packs/Base/Scripts/DBotPredictPhishingWords/DBotPredictPhishingWords.py
  Packs/Base/pack_metadata.json
  Packs/CommonScripts/ReleaseNotes/1_2_40.md
  Packs/CommonScripts/Scripts/JSONtoCSV/JSONtoCSV.py
  Packs/CommonScripts/pack_metadata.json
  Packs/CortexXDR/Integrations/PaloAltoNetworks_XDR/PaloAltoNetworks_XDR.py
  Packs/CortexXDR/ReleaseNotes/2_3_5.md
  Packs/CortexXDR/pack_metadata.json
  Packs/CrowdStrikeFalconX/Integrations/CrowdStrikeFalconX/CrowdStrikeFalconX.py
  Packs/CrowdStrikeFalconX/Integrations/CrowdStrikeFalconX/CrowdStrikeFalconX.yml
  Packs/CrowdStrikeFalconX/ReleaseNotes/1_0_2.md
  Packs/CrowdStrikeFalconX/pack_metadata.json
  Packs/SafeBreach/Integrations/SafeBreach_v2/SafeBreach_v2.py
  Packs/SafeBreach/Integrations/SafeBreach_v2/SafeBreach_v2.yml
  Packs/SafeBreach/ReleaseNotes/1_0_6.md
  Packs/SafeBreach/pack_metadata.json
  Packs/Whois/Integrations/Whois/Whois.py
  Packs/Whois/ReleaseNotes/1_1_5.md
  Packs/Whois/pack_metadata.json
Labels: docs-approved

#8830 fixing error in parsing oproxy response
  Packs/CortexDataLake/Integrations/CortexDataLake/CortexDataLake.py
  Packs/CortexDataLake/Integrations/CortexDataLake/CortexDataLake.yml
  Packs/CortexDataLake/ReleaseNotes/1_2_2.md
  Packs/CortexDataLake/pack_metadata.json
Labels: docs-approved, release-notes-only

#8908 Url Scan - rate limit
  Packs/UrlScan/Integrations/UrlScan/UrlScan.py
  Packs/UrlScan/ReleaseNotes/1_0_2.md
  Packs/UrlScan/pack_metadata.json
Labels: docs-approved

#8905 Cortex XDR - add HTTP timeout param
  Packs/CortexXDR/Integrations/PaloAltoNetworks_XDR/PaloAltoNetworks_XDR.py
  Packs/CortexXDR/Integrations/PaloAltoNetworks_XDR/PaloAltoNetworks_XDR.yml
  Packs/CortexXDR/Integrations/PaloAltoNetworks_XDR/PaloAltoNetworks_XDR_test.py
  Packs/CortexXDR/Integrations/PaloAltoNetworks_XDR/README.md
  Packs/CortexXDR/ReleaseNotes/2_3_6.md
  Packs/CortexXDR/pack_metadata.json
Labels: bug, docs-approved

#8784 Wildfire file type
  Packs/Palo_Alto_Networks_WildFire/Playbooks/playbook-Detonate_File_-_WildFire.yml
  Packs/Palo_Alto_Networks_WildFire/ReleaseNotes/1_2_0.md
  Packs/Palo_Alto_Networks_WildFire/pack_metadata.json
Labels: docs-approved

#8630 try to add back google-vault
  Packs/GoogleVault/Integrations/GoogleVault/GoogleVault.py
  Packs/GoogleVault/Integrations/GoogleVault/GoogleVault.yml
  Packs/GoogleVault/ReleaseNotes/1_0_2.md
  Packs/GoogleVault/TestPlaybooks/playbook-Google_Vault_-_Search_And_Display_Results_test.yml
  Packs/GoogleVault/pack_metadata.json
  Tests/conf.json
Labels: docs-approved, release-notes-only

#8876 Revert playbook_to_run argument to XDRSyncScript
  Packs/CortexXDR/ReleaseNotes/2_3_7.md
  Packs/CortexXDR/Scripts/XDRSyncScript/XDRSyncScript.py
  Packs/CortexXDR/Scripts/XDRSyncScript/XDRSyncScript.yml
  Packs/CortexXDR/pack_metadata.json
Labels: docs-approved, release-notes-only

#8706 Added ConvertTo-Markdown method
  Packs/Base/ReleaseNotes/1_2_3.md
  Packs/Base/Scripts/CommonServerPowerShell/CommonServerPowerShell.Tests.ps1
  Packs/Base/Scripts/CommonServerPowerShell/CommonServerPowerShell.ps1
  Packs/Base/Scripts/CommonServerPowerShell/CommonServerPowerShell.yml
  Packs/Base/pack_metadata.json
Labels: docs-approved, release-notes-only

#8900 AWS Auth article link
  Packs/AWS-ACM/Integrations/AWS-ACM/AWS-ACM_description.md
  Packs/AWS-ACM/ReleaseNotes/1_0_1.md
  Packs/AWS-ACM/pack_metadata.json
  Packs/AWS-AccessAnalyzer/Integrations/AWS-AccessAnalyzer/AWS-AccessAnalyzer_description.md
  Packs/AWS-AccessAnalyzer/ReleaseNotes/1_0_2.md
  Packs/AWS-AccessAnalyzer/pack_metadata.json
  Packs/AWS-Athena/Integrations/AWS-Athena/AWS-Athena_description.md
  Packs/AWS-Athena/ReleaseNotes/1_0_1.md
  Packs/AWS-Athena/pack_metadata.json
  Packs/AWS-CloudTrail/Integrations/AWS-CloudTrail/AWS-CloudTrail_description.md
  Packs/AWS-CloudTrail/ReleaseNotes/1_0_1.md
  Packs/AWS-CloudTrail/pack_metadata.json
  Packs/AWS-EC2/Integrations/AWS-EC2/AWS-EC2_description.md
  Packs/AWS-EC2/ReleaseNotes/1_1_2.md
  Packs/AWS-EC2/pack_metadata.json
  Packs/AWS-GuardDuty/Integrations/integration-AWS-GuardDuty_README.md
  Packs/AWS-IAM/Integrations/AWS-IAM/README.md
  Packs/AWS-Lambda/Integrations/AWS-Lambda/AWS-Lambda_description.md
  Packs/AWS-Lambda/ReleaseNotes/1_0_1.md
  Packs/AWS-Lambda/pack_metadata.json
  Packs/AWS-Route53/Integrations/integration-AWS-Route53_README.md
  Packs/AWS-S3/Integrations/AWS-S3/AWS-S3_description.md
  Packs/AWS-S3/Integrations/AWS-S3/README.md
  Packs/AWS-S3/ReleaseNotes/1_0_1.md
  Packs/AWS-S3/pack_metadata.json
  Packs/AWS-SQS/Integrations/integration-AWS-SQS_README.md
  Packs/AWS_DynamoDB/Integrations/AWS_DynamoDB/AWS_DynamoDB_description.md
  Packs/AWS_DynamoDB/ReleaseNotes/1_0_1.md
  Packs/AWS_DynamoDB/pack_metadata.json
Labels: docs-approved

#8553 [axonious-237] Initial Commit
  Packs/Axonius/.pack-ignore
  Packs/Axonius/.secrets-ignore
  Packs/Axonius/Integrations/Axonius/Axonius.py
  Packs/Axonius/Integrations/Axonius/Axonius.yml
  Packs/Axonius/Integrations/Axonius/Axonius_description.md
  Packs/Axonius/Integrations/Axonius/Axonius_image.png
  Packs/Axonius/Integrations/Axonius/Axonius_test.py
  Packs/Axonius/Integrations/Axonius/Pipfile
  Packs/Axonius/Integrations/Axonius/Pipfile.lock
  Packs/Axonius/Integrations/Axonius/README.md
  Packs/Axonius/Integrations/Axonius/command_examples.txt
  Packs/Axonius/README.md
  Packs/Axonius/pack_metadata.json
Labels: Contribution, Partner, docs-approved

#8803 Phishing classifier Ui improvements
  Packs/Base/ReleaseNotes/1_2_4.md
  Packs/Base/Scripts/DBotPredictPhishingWords/DBotPredictPhishingWords.py
  Packs/Base/Scripts/DBotPredictPhishingWords/DBotPredictPhishingWords.yml
  Packs/Base/pack_metadata.json
  Packs/ML/ReleaseNotes/1_2_0.md
  Packs/ML/Scripts/DBotPredictOutOfTheBox/DBotPredictOutOfTheBox.yml
  Packs/ML/pack_metadata.json
Labels: docs-approved

#8723 Phishing pre-processing rule script
  Packs/Phishing/.secrets-ignore
  Packs/Phishing/ReleaseNotes/1_10_3.md
  Packs/Phishing/Scripts/PhishingDedupPreprocessingRule/PhishingDedupPreprocessingRule.py
  Packs/Phishing/Scripts/PhishingDedupPreprocessingRule/PhishingDedupPreprocessingRule.yml
  Packs/Phishing/Scripts/PhishingDedupPreprocessingRule/PhishingDedupPreprocessingRule_test.py
  Packs/Phishing/pack_metadata.json
Labels: docs-approved

#8544 New commands for PAN-OS
  Packs/PAN-OS/Integrations/Panorama/Panorama.py
  Packs/PAN-OS/Integrations/Panorama/Panorama.yml
  Packs/PAN-OS/Integrations/Panorama/README.md
  Packs/PAN-OS/ReleaseNotes/1_6_0.md
  Packs/PAN-OS/TestPlaybooks/playbook-palo_alto_panorama_test_best_practice.yml
  Packs/PAN-OS/pack_metadata.json
  Tests/conf.json
Labels: docs-approved

#8920 MicrosoftCloudAppSecurity adding defaultValue to max_fetch
  Packs/MicrosoftCloudAppSecurity/.pack-ignore
  Packs/MicrosoftCloudAppSecurity/Integrations/MicrosoftCloudAppSecurity/MicrosoftCloudAppSecurity.yml
  Packs/MicrosoftCloudAppSecurity/ReleaseNotes/1_0_2.md
  Packs/MicrosoftCloudAppSecurity/pack_metadata.json
Labels: docs-approved

#8868 CommonServerPython - Added the timeline object to the **CommandResult…
  Packs/Base/ReleaseNotes/1_2_5.md
  Packs/Base/Scripts/CommonServerPython/CommonServerPython.py
  Packs/Base/Scripts/CommonServerPython/CommonServerPython_test.py
  Packs/Base/pack_metadata.json
  Packs/Polygon/Integrations/Polygon/test_data/results.json
Labels: docs-approved, release-notes-only

#8919 ServiceNow layouts - fix typo
  Packs/ServiceNow/Layouts/layout-details-ServiceNow_Ticket.json
  Packs/ServiceNow/Layouts/layoutscontainer-ServiceNow_Ticket.json
  Packs/ServiceNow/ReleaseNotes/1_2_5.md
  Packs/ServiceNow/pack_metadata.json
Labels: docs-approved

#8768 fetch change using offset
  Packs/CrowdStrikeFalcon/Integrations/CrowdStrikeFalcon/CrowdStrikeFalcon.py
  Packs/CrowdStrikeFalcon/Integrations/CrowdStrikeFalcon/CrowdStrikeFalcon.yml
  Packs/CrowdStrikeFalcon/Integrations/CrowdStrikeFalcon/CrowdStrikeFalcon_test.py
  Packs/CrowdStrikeFalcon/ReleaseNotes/1_2_0.md
  Packs/CrowdStrikeFalcon/pack_metadata.json
Labels: bug, docs-approved, release-notes-only

#8926 Zimperium: test playbook - fixed task ids
  Packs/Zimperium/TestPlaybooks/Zimperium_Test.yml
Labels: docs-approved

#8586 Fixed input bug in Detonate File - ThreatGrid under Detonate File - Generic
  Packs/CommonPlaybooks/Playbooks/playbook-Detonate_File_-_Generic.yml
  Packs/CommonPlaybooks/ReleaseNotes/1_8_0.md
  Packs/CommonPlaybooks/pack_metadata.json
  Packs/ThreatGrid/Playbooks/playbook-Detonate_File_-_ThreatGrid.yml
  Packs/ThreatGrid/ReleaseNotes/1_1_0.md
  Packs/ThreatGrid/pack_metadata.json
Labels: bug, docs-approved

#8909 change elastic default Feed Type
  Packs/FeedElasticsearch/Integrations/FeedElasticsearch/FeedElasticsearch.yml
  Packs/FeedElasticsearch/ReleaseNotes/1_0_6.md
  Packs/FeedElasticsearch/pack_metadata.json
Labels: bug, content, docs-approved, release-notes-only

#8897 Eli/safe breach v2 bugfix
  Packs/SafeBreach/Integrations/SafeBreach_v2/SafeBreach_v2.py
  Packs/SafeBreach/ReleaseNotes/1_0_7.md
  Packs/SafeBreach/pack_metadata.json
Labels: bug, content, docs-approved, release-notes-only

#8889 PcapMinerV2 - fix extract_smtp method
  Packs/PcapAnalysis/ReleaseNotes/2_3_3.md
  Packs/PcapAnalysis/Scripts/PcapMinerV2/PcapMinerV2.py
  Packs/PcapAnalysis/Scripts/PcapMinerV2/PcapMinerV2.yml
  Packs/PcapAnalysis/pack_metadata.json
Labels: bug, docs-approved, release-notes-only

#8899 Threat connect v2 - update dbot score calculation logic
  Packs/ThreatConnect/Integrations/ThreatConnect_v2/ThreatConnect_v2.py
  Packs/ThreatConnect/Integrations/ThreatConnect_v2/ThreatConnect_v2_test.py
  Packs/ThreatConnect/ReleaseNotes/2_0_7.md
  Packs/ThreatConnect/pack_metadata.json
Labels: bug, docs-approved, release-notes-only

#8902 XFE_v2 Bug
  Packs/XForceExchange/Integrations/XFE_v2/XFE_v2.py
  Packs/XForceExchange/Integrations/XFE_v2/XFE_v2.yml
  Packs/XForceExchange/ReleaseNotes/1_0_1.md
  Packs/XForceExchange/pack_metadata.json
Labels: bug, docs-approved, release-notes-only

#8912 Cortex XDR - add max fetch param
  Packs/CortexXDR/Integrations/PaloAltoNetworks_XDR/PaloAltoNetworks_XDR.py
  Packs/CortexXDR/Integrations/PaloAltoNetworks_XDR/PaloAltoNetworks_XDR.yml
  Packs/CortexXDR/Integrations/PaloAltoNetworks_XDR/README.md
  Packs/CortexXDR/ReleaseNotes/2_3_8.md
  Packs/CortexXDR/pack_metadata.json
Labels: bug, docs-approved, release-notes-only

#8925 ThreatQ: added Content-Type to request headers
  Packs/ThreatQ/Integrations/ThreatQ_v2/ThreatQ_v2.py
  Packs/ThreatQ/Integrations/ThreatQ_v2/ThreatQ_v2.yml
  Packs/ThreatQ/ReleaseNotes/1_0_5.md
  Packs/ThreatQ/pack_metadata.json
Labels: bug, docs-approved, release-notes-only

#8675 New playbook - Palo Alto Networks - Endpoint Malware Investigation v3
  Packs/PANWComprehensiveInvestigation/Playbooks/Palo_Alto_Networks_-_Endpoint_Malware_Investigation_v3.yml
  Packs/PANWComprehensiveInvestigation/ReleaseNotes/1_3_2.md
  Packs/PANWComprehensiveInvestigation/pack_metadata.json
Labels: docs-approved

#8922 Set delete context to d bot role
  Packs/CommonScripts/ReleaseNotes/1_2_41.md
  Packs/CommonScripts/Scripts/script-DeleteConext.yml
  Packs/CommonScripts/pack_metadata.json
Labels: bug, docs-approved, release-notes-only

#8930 Circl TPB Fix
  Packs/CIRCL/TestPlaybooks/playbook-CIRCL.yml
  Tests/conf.json
Labels: docs-approved

#8881 Prisma Cloud Redlock add context
  Packs/PrismaCloud/Integrations/RedLock/RedLock.py
  Packs/PrismaCloud/Integrations/RedLock/RedLock.yml
  Packs/PrismaCloud/ReleaseNotes/1_2_4.md
  Packs/PrismaCloud/pack_metadata.json
Labels: docs-approved

#8932 XDR playbook enhancements
  Packs/CortexXDR/Playbooks/Cortex_XDR_-_Malware_Investigation.yml
  Packs/CortexXDR/ReleaseNotes/2_3_9.md
  Packs/CortexXDR/pack_metadata.json
Labels: docs-approved

#8924 Improve parse date range function
  Packs/Base/ReleaseNotes/1_3_1.md
  Packs/Base/Scripts/CommonServerPython/CommonServerPython.py
  Packs/Base/Scripts/CommonServerPython/CommonServerPython_test.py
  Packs/Base/pack_metadata.json
Labels: bug, docs-approved, release-notes-only

#8931 Removed redundant mail from Okta pack
  Packs/Okta/.secrets-ignore
Labels: docs-approved

#8837 Test-Failure Carbon Black Enterprise Protection V2
  Packs/CarbonBlackProtect/TestPlaybooks/Carbon_Black_Enterprise_Protection_V2_Test.yml
Labels: docs-approved

#8933 fix deprecated format
  Packs/McAfee_ESM-v10/Integrations/McAfee_ESM-v10/McAfee_ESM-v10.yml
  Packs/McAfee_ESM-v10/ReleaseNotes/1_0_4.md
  Packs/McAfee_ESM-v10/pack_metadata.json
  Packs/PassiveTotal/Integrations/integration-PassiveTotal.yml
  Packs/PassiveTotal/ReleaseNotes/2_0_1.md
  Packs/PassiveTotal/Scripts/script-PTEnrich.yml
  Packs/PassiveTotal/pack_metadata.json
Labels: docs-approved

#8938 Remove print
  Packs/URLHaus/Integrations/URLHaus/URLHaus.py
  Packs/URLHaus/Integrations/URLHaus/URLHaus.yml
  Packs/URLHaus/ReleaseNotes/1_0_1.md
  Packs/URLHaus/pack_metadata.json
Labels: docs-approved

#8940 checkout contribution bugfix
  Utils/checkout_contribution.sh
Labels: docs-approved

#8937 Moved Init_McAfee_ESM_v2_Test to NonCircleTests directory
  Packs/McAfee_ESM/TestPlaybooks/NonCircleTests/Init_McAfee_ESM_v2_Test.yml
  Tests/conf.json
Labels: docs-approved

#8945 Remove Welcome Bot Message
  .github/config.yml
Labels: docs-approved

#8672 Atp enhancments - Indicators
  Packs/ApiModules/ReleaseNotes/1_1_0.md
  Packs/ApiModules/Scripts/MicrosoftApiModule/MicrosoftApiModule.py
  Packs/ApiModules/Scripts/MicrosoftApiModule/MicrosoftApiModule.yml
  Packs/ApiModules/Scripts/MicrosoftApiModule/MicrosoftApiModule_test.py
  Packs/ApiModules/pack_metadata.json
  Packs/MicrosoftDefenderAdvancedThreatProtection/Integrations/MicrosoftDefenderAdvancedThreatProtection/MicrosoftDefenderAdvancedThreatProtection.py
  Packs/MicrosoftDefenderAdvancedThreatProtection/Integrations/MicrosoftDefenderAdvancedThreatProtection/MicrosoftDefenderAdvancedThreatProtection.yml
  Packs/MicrosoftDefenderAdvancedThreatProtection/Integrations/MicrosoftDefenderAdvancedThreatProtection/MicrosoftDefenderAdvancedThreatProtection_test.py
  Packs/MicrosoftDefenderAdvancedThreatProtection/Integrations/MicrosoftDefenderAdvancedThreatProtection/Pipfile
  Packs/MicrosoftDefenderAdvancedThreatProtection/Integrations/MicrosoftDefenderAdvancedThreatProtection/Pipfile.lock
  Packs/MicrosoftDefenderAdvancedThreatProtection/ReleaseNotes/1_2_0.md
  Packs/MicrosoftDefenderAdvancedThreatProtection/TestPlaybooks/playbook-Microsoft_ATP_indicators_Test.yml
  Packs/MicrosoftDefenderAdvancedThreatProtection/pack_metadata.json
  Tests/conf.json
Labels: docs-approved

#8686 Microsoft ATP - Docs for Indicator commands
  Packs/MicrosoftDefenderAdvancedThreatProtection/Integrations/MicrosoftDefenderAdvancedThreatProtection/README.md
Labels: docs-approved

#8688 uptycs-185 bug fixes for integration, change playbook inputs and add gatherEvidence Tasks, slight clarification added to parameters section of documentation, uptycs support info added
  Packs/Uptycs/Integrations/Uptycs/README.md
  Packs/Uptycs/Integrations/Uptycs/Uptycs.py
  Packs/Uptycs/Integrations/Uptycs/Uptycs.yml
  Packs/Uptycs/Playbooks/playbook-Uptycs_-_Outbound_Connection_to_Threat_IOC_Incident.yml
  Packs/Uptycs/ReleaseNotes/1_0_2.md
  Packs/Uptycs/pack_metadata.json
Labels: Contribution, Partner, docs-approved, ready-for-instance-test

#8950 added self deployed test to ATP
  Tests/conf.json
Labels: docs-approved

#8286 Feed crowdstrike falcon intel integration
  Packs/CommonTypes/IndicatorFields/incidentfield-creationdate.json
  Packs/CommonTypes/IndicatorFields/incidentfield-geocountry.json
  Packs/CommonTypes/IndicatorFields/incidentfield-region.json
  Packs/CommonTypes/IndicatorFields/incidentfield-updateddate.json
  Packs/CommonTypes/ReleaseNotes/1_9_5.md
  Packs/CommonTypes/pack_metadata.json
  Packs/FeedCrowdstrikeFalconIntel/.pack-ignore
  Packs/FeedCrowdstrikeFalconIntel/.secrets-ignore
  Packs/FeedCrowdstrikeFalconIntel/Integrations/FeedCrowdstrikeFalconIntel/CHANGELOG.md
  Packs/FeedCrowdstrikeFalconIntel/Integrations/FeedCrowdstrikeFalconIntel/FeedCrowdstrikeFalconIntel.py
  Packs/FeedCrowdstrikeFalconIntel/Integrations/FeedCrowdstrikeFalconIntel/FeedCrowdstrikeFalconIntel.yml
  Packs/FeedCrowdstrikeFalconIntel/Integrations/FeedCrowdstrikeFalconIntel/FeedCrowdstrikeFalconIntel_description.md
  Packs/FeedCrowdstrikeFalconIntel/Integrations/FeedCrowdstrikeFalconIntel/FeedCrowdstrikeFalconIntel_test.py
  Packs/FeedCrowdstrikeFalconIntel/Integrations/FeedCrowdstrikeFalconIntel/FeedcrowdstrikeFalconIntel_image.png
  Packs/FeedCrowdstrikeFalconIntel/Integrations/FeedCrowdstrikeFalconIntel/Pipfile
  Packs/FeedCrowdstrikeFalconIntel/Integrations/FeedCrowdstrikeFalconIntel/Pipfile.lock
  Packs/FeedCrowdstrikeFalconIntel/Integrations/FeedCrowdstrikeFalconIntel/README.md
  Packs/FeedCrowdstrikeFalconIntel/Integrations/FeedCrowdstrikeFalconIntel/test_data.json
  Packs/FeedCrowdstrikeFalconIntel/README.md
  Packs/FeedCrowdstrikeFalconIntel/pack_metadata.json
Labels: docs-approved

#8110 Trend Micro enhancement
  Packs/TrendMicroApex/.secrets-ignore
  Packs/TrendMicroApex/Integrations/TrendMicroApex/README.md
  Packs/TrendMicroApex/Integrations/TrendMicroApex/TrendMicroApex.py
  Packs/TrendMicroApex/Integrations/TrendMicroApex/TrendMicroApex.yml
  Packs/TrendMicroApex/Integrations/TrendMicroApex/TrendMicroApex_description.md
  Packs/TrendMicroApex/Integrations/TrendMicroApex/TrendMicroApex_test.py
  Packs/TrendMicroApex/Integrations/TrendMicroApex/commands.txt
  Packs/TrendMicroApex/Integrations/TrendMicroApex/test_data/add_file_command_mock.json
  Packs/TrendMicroApex/Integrations/TrendMicroApex/test_data/agent_list_command_mock.json
  Packs/TrendMicroApex/Integrations/TrendMicroApex/test_data/file_example.txt
  Packs/TrendMicroApex/Integrations/TrendMicroApex/test_data/historical_investigation_command_mock.json
  Packs/TrendMicroApex/Integrations/TrendMicroApex/test_data/logs_list_command_mock.json
  Packs/TrendMicroApex/Integrations/TrendMicroApex/test_data/result_list_command_mock.json
  Packs/TrendMicroApex/Integrations/TrendMicroApex/test_data/sensors_list_command_mock.json
  Packs/TrendMicroApex/Integrations/TrendMicroApex/test_data/servers_list_command_mock.json
  Packs/TrendMicroApex/ReleaseNotes/2_0_0.md
  Packs/TrendMicroApex/TestPlaybooks/playbook-TrendMicroApexTest.yml
  Packs/TrendMicroApex/pack_metadata.json
  Tests/conf.json
Labels: docs-approved

#8827 Gophish Integration
  Packs/Gophish/.pack-ignore
  Packs/Gophish/.secrets-ignore
  Packs/Gophish/Integrations/Gophish/Gophish.py
  Packs/Gophish/Integrations/Gophish/Gophish.yml
  Packs/Gophish/Integrations/Gophish/Gophish_description.md
  Packs/Gophish/Integrations/Gophish/Gophish_image.png
  Packs/Gophish/Integrations/Gophish/README.md
  Packs/Gophish/Integrations/Gophish/command_examples.txt
  Packs/Gophish/README.md
  Packs/Gophish/pack_metadata.json
  TestPlaybooks/NonCircleTests/playbook-Gophish-Test.yml
Labels: Contribution, docs-approved

#8394 Explained need to re-run auth. flow
  Packs/MicrosoftDefenderAdvancedThreatProtection/Integrations/MicrosoftDefenderAdvancedThreatProtection/README.md
Labels: docs-approved

#8954 BMCHelixRemedyforce - changes for demisto-sdk validate
  Packs/BmcHelixRemedyForce/Integrations/BmcHelixRemedyForce/BMCHelixRemedyforce.py
  Packs/BmcHelixRemedyForce/Integrations/BmcHelixRemedyForce/BMCHelixRemedyforce.yml
  Packs/BmcHelixRemedyForce/Integrations/BmcHelixRemedyForce/BMCHelixRemedyforce_test.py
  Packs/BmcHelixRemedyForce/ReleaseNotes/1_0_1.md
  Packs/BmcHelixRemedyForce/pack_metadata.json
Labels: docs-approved

#8956 Fixing the logic for find none added packs
  Tests/configure_and_test_integration_instances.py
Labels: bug, docs-approved

#8269 Updated product name to Cortex XSOAR
  Packs/CortexDataLake/Integrations/CortexDataLake/README.md
Labels: docs-approved

#8355 Update playbook-TIM_-_Indicators_Exclusion_By_Related_Incidents_READM…
  Packs/TIM_Processing/Playbooks/playbook-TIM_-_Indicators_Exclusion_By_Related_Incidents_README.md
Labels: docs-approved

#8456 Minor update to device-group argument desc.
  Packs/PAN-OS/Playbooks/playbook-PAN-OS_DAG_Configuration_README.md
Labels: docs-approved

#8576 Infinipoint - Unskip integration after getting new creds from the partner
  Tests/conf.json
Labels: docs-approved

#8957 revert DeleteContext role change
  Packs/CommonScripts/ReleaseNotes/1_2_42.md
  Packs/CommonScripts/Scripts/script-DeleteConext.yml
  Packs/CommonScripts/pack_metadata.json
Labels: docs-approved

#8115 farsight-security-57 DNSDB Pack 2.0
  .hooks/pre-commit
  Packs/DNSDB/.secrets-ignore
  Packs/DNSDB/Integrations/DNSDB_v2/DNSDB_v2.py
  Packs/DNSDB/Integrations/DNSDB_v2/DNSDB_v2.yml
  Packs/DNSDB/Integrations/DNSDB_v2/DNSDB_v2_description.md
  Packs/DNSDB/Integrations/DNSDB_v2/DNSDB_v2_image.png
  Packs/DNSDB/Integrations/DNSDB_v2/DNSDB_v2_test.py
  Packs/DNSDB/Integrations/DNSDB_v2/README.md
  Packs/DNSDB/Integrations/DNSDB_v2/command_examples
  Packs/DNSDB/Integrations/integration-DNSDB.yml
  Packs/DNSDB/Playbooks/playbook-DNSDB-Hostname_from_IP.yml
  Packs/DNSDB/Playbooks/playbook-DNSDB-IPs_from_Hostname.yml
  Packs/DNSDB/Playbooks/playbook-DNSDB-Related_Hostnames_From_Hostname.yml
  Packs/DNSDB/ReleaseNotes/2_0_0.md
  Packs/DNSDB/TestPlaybooks/playbook-DNSDB-Test.yml
  Packs/DNSDB/pack_metadata.json
  Tests/conf.json
  Tests/secrets_white_list.json
Labels: Contribution, docs-approved, ready-for-instance-test

#8959 remove testplaybook - Unsupported version 4.0.9
  Packs/CarbonBlackProtect/TestPlaybooks/playbook-CarbonBlackProtectV2-test_4_0.yml
Labels: docs-approved

#8961 Update description for DeepInstinct.yml
  Packs/DeepInstinct/Integrations/DeepInstinct/DeepInstinct.yml
  Packs/DeepInstinct/ReleaseNotes/1_0_2.md
  Packs/DeepInstinct/pack_metadata.json
Labels: docs-approved

#8935 unskip urlscan.io and add description file to the http error prints
  Packs/UrlScan/.secrets-ignore
  Packs/UrlScan/Integrations/UrlScan/UrlScan.py
  Packs/UrlScan/ReleaseNotes/1_0_3.md
  Packs/UrlScan/TestPlaybooks/playbook-Urlscan_malicious_Test.yml
  Packs/UrlScan/pack_metadata.json
  Tests/conf.json
Labels: docs-approved, release-notes-only

#8814 [code42-363] Add Else to Download File playbook and upgrade docker file
  Packs/Code42/Integrations/Code42/Code42.py
  Packs/Code42/Integrations/Code42/Code42.yml
  Packs/Code42/Integrations/Code42/Code42_test.py
  Packs/Code42/Playbooks/playbook-Code42_File_Download.yml
  Packs/Code42/ReleaseNotes/2_0_4.md
  Packs/Code42/pack_metadata.json
Labels: Contribution, docs-approved, ready-for-instance-test

#8971 unskip AlphaSOC Wisdom test
  Tests/conf.json
Labels: docs-approved

#8973 unskip URL Enrichment - Generic v2 - Test
  Tests/conf.json
Labels: docs-approved

#8970 bump release version
  .circleci/config.yml
Labels: docs-approved

#8964 service now readme: fix bullet formatting
  Packs/ServiceNow/Integrations/ServiceNowv2/README.md
Labels: docs-approved

#8979 WhereFieldsEquals - fixed a KeyError bug
  Packs/CommonScripts/ReleaseNotes/1_2_43.md
  Packs/CommonScripts/Scripts/WhereFieldEquals/WhereFieldEquals.py
  Packs/CommonScripts/Scripts/WhereFieldEquals/WhereFieldEquals.yml
  Packs/CommonScripts/Scripts/WhereFieldEquals/WhereFieldEquals_test.py
  Packs/CommonScripts/pack_metadata.json
Labels: bug, docs-approved, release-notes-only

#8984 TLP indicator field default chagne
  Packs/CommonTypes/IndicatorFields/incidentfield-tlp.json
  Packs/CommonTypes/ReleaseNotes/1_9_6.md
  Packs/CommonTypes/pack_metadata.json
Labels: docs-approved, release-notes-only

#8943 Securonix - Added the *Set default incident severity* parameter to th…
  Packs/Securonix/Integrations/Securonix/README.md
  Packs/Securonix/Integrations/Securonix/Securonix.py
  Packs/Securonix/Integrations/Securonix/Securonix.yml
  Packs/Securonix/Integrations/Securonix/Securonix_test.py
  Packs/Securonix/ReleaseNotes/1_1_3.md
  Packs/Securonix/pack_metadata.json
Labels: docs-approved

#8910 Ms user self deployed
  Packs/ApiModules/ReleaseNotes/1_1_1.md
  Packs/ApiModules/Scripts/MicrosoftApiModule/MicrosoftApiModule.py
  Packs/ApiModules/Scripts/MicrosoftApiModule/MicrosoftApiModule.yml
  Packs/ApiModules/pack_metadata.json
  Packs/MicrosoftGraphUser/Integrations/MicrosoftGraphUser/MicrosoftGraphUser.py
  Packs/MicrosoftGraphUser/Integrations/MicrosoftGraphUser/MicrosoftGraphUser.yml
  Packs/MicrosoftGraphUser/Integrations/MicrosoftGraphUser/MicrosoftGraphUser_description.md
  Packs/MicrosoftGraphUser/Integrations/MicrosoftGraphUser/README.md
  Packs/MicrosoftGraphUser/ReleaseNotes/1_3_0.md
  Packs/MicrosoftGraphUser/TestPlaybooks/Microsoft_Graph_User_test.yml
  Packs/MicrosoftGraphUser/pack_metadata.json
  Tests/conf.json
Labels: bug, docs-approved
