Repository demisto/content, pull requests merged in 2020-11, with the labels that each got.

#9753 Removing duplicated test configuration
  Tests/conf.json
Labels: docs-approved

#9715 Anomali Threatstream v2 domain reputation overwrite bug
  Packs/Anomali_ThreatStream/Integrations/Anomali_ThreatStream_v2/Anomali_ThreatStream_v2.py
  Packs/Anomali_ThreatStream/Integrations/Anomali_ThreatStream_v2/Anomali_ThreatStream_v2.yml
  Packs/Anomali_ThreatStream/ReleaseNotes/1_0_5.md
  Packs/Anomali_ThreatStream/pack_metadata.json
Labels: docs-approved, release-notes-only

#9654 Integrationsand incidents fixes
  Packs/IntegrationsAndIncidentsHealthCheck/Playbooks/playbook-JOB_-_Integrations_and_Playbooks_Health_Check.yml
  Packs/IntegrationsAndIncidentsHealthCheck/ReleaseNotes/1_1_5.md
  Packs/IntegrationsAndIncidentsHealthCheck/Scripts/GetFailedTasks/GetFailedTasks.py
  Packs/IntegrationsAndIncidentsHealthCheck/Scripts/GetFailedTasks/GetFailedTasks.yml
  Packs/IntegrationsAndIncidentsHealthCheck/Scripts/GetFailedTasks/GetFailedTasks_test.py
  Packs/IntegrationsAndIncidentsHealthCheck/pack_metadata.json
Labels: docs-approved

#9656 "update_contribution_pack_in_base_branch" script - support multiple packs
  Utils/tests/update_contribution_pack_in_base_branch_test.py
  Utils/update_contribution_pack_in_base_branch.py
Labels: docs-approved

#9752 added bulitin
  Packs/CommonScripts/ReleaseNotes/1_2_70.md
  Packs/CommonScripts/Scripts/AfterRelativeDate/AfterRelativeDate.py
  Packs/CommonScripts/pack_metadata.json
Labels: bug, docs-approved, release-notes-only

#9734 MS graph mail - skipped referenceAttachment
  Packs/MicrosoftGraphMail/Integrations/MicrosoftGraphMail/MicrosoftGraphMail.py
  Packs/MicrosoftGraphMail/Integrations/MicrosoftGraphMail/MicrosoftGraphMail.yml
  Packs/MicrosoftGraphMail/ReleaseNotes/1_0_10.md
  Packs/MicrosoftGraphMail/pack_metadata.json
Labels: docs-approved, release-notes-only

#9759 Aws cloudtrail datetime object handling
  Packs/AWS-CloudTrail/Integrations/AWS-CloudTrail/AWS-CloudTrail.py
  Packs/AWS-CloudTrail/Integrations/AWS-CloudTrail/AWS-CloudTrail.yml
  Packs/AWS-CloudTrail/ReleaseNotes/1_0_2.md
  Packs/AWS-CloudTrail/pack_metadata.json
Labels: bug, docs-approved, release-notes-only

#9718 Servicenow bug fix
  Packs/ServiceNow/Integrations/ServiceNowv2/ServiceNowv2.py
  Packs/ServiceNow/Integrations/ServiceNowv2/ServiceNowv2_test.py
  Packs/ServiceNow/Integrations/ServiceNowv2/test_data/response_constants.py
  Packs/ServiceNow/ReleaseNotes/1_3_8.md
  Packs/ServiceNow/pack_metadata.json
Labels: docs-approved, release-notes-only

#9568 Emailrepio
  Packs/Base/ReleaseNotes/1_3_26.md
  Packs/Base/Scripts/CommonServerPython/CommonServerPython.py
  Packs/Base/pack_metadata.json
  Packs/EmailRepIO/.pack-ignore
  Packs/EmailRepIO/.secrets-ignore
  Packs/EmailRepIO/Integrations/EmailRepIO/EmailRepIO.py
  Packs/EmailRepIO/Integrations/EmailRepIO/EmailRepIO.yml
  Packs/EmailRepIO/Integrations/EmailRepIO/EmailRepIO_description.md
  Packs/EmailRepIO/Integrations/EmailRepIO/EmailRepIO_image.png
  Packs/EmailRepIO/Integrations/EmailRepIO/EmailRepIO_test.py
  Packs/EmailRepIO/Integrations/EmailRepIO/Pipfile
  Packs/EmailRepIO/Integrations/EmailRepIO/Pipfile.lock
  Packs/EmailRepIO/Integrations/EmailRepIO/test_data/reputation_get_results.json
  Packs/EmailRepIO/README.md
  Packs/EmailRepIO/TestPlaybooks/TestEmailRepIOPlaybook.yml
  Packs/EmailRepIO/pack_metadata.json
  Tests/conf.json
  package-lock.json
  package.json
Labels: docs-approved

#9761 [Community Contribution] ExtFilter (#9522)
  Packs/ExtFilter/.pack-ignore
  Packs/ExtFilter/.secrets-ignore
  Packs/ExtFilter/Playbooks/Test_-_ExtFilter.yml
  Packs/ExtFilter/Playbooks/Test_-_ExtFilter_Main.yml
  Packs/ExtFilter/README.md
  Packs/ExtFilter/Scripts/ExtFilter/ExtFilter.py
  Packs/ExtFilter/Scripts/ExtFilter/ExtFilter.yml
  Packs/ExtFilter/Scripts/ExtFilter/Pipfile
  Packs/ExtFilter/Scripts/ExtFilter/Pipfile.lock
  Packs/ExtFilter/Scripts/ExtFilter/README.md
  Packs/ExtFilter/pack_metadata.json
Labels: docs-approved

#9742 MS Graph Mail - Headers Missing Bug
  Packs/MicrosoftGraphMail/Integrations/MicrosoftGraphMail/MicrosoftGraphMail.py
  Packs/MicrosoftGraphMail/ReleaseNotes/1_0_11.md
  Packs/MicrosoftGraphMail/pack_metadata.json
Labels: docs-approved, release-notes-only

#9498 Add show policy package command for Checkpoint automation
  Packs/CheckpointFirewall/Integrations/CheckPointFirewall_v2/CheckPointFirewall_v2.py
  Packs/CheckpointFirewall/Integrations/CheckPointFirewall_v2/CheckPointFirewall_v2.yml
  Packs/CheckpointFirewall/Integrations/CheckPointFirewall_v2/README.md
  Packs/CheckpointFirewall/ReleaseNotes/2_0_3.md
  Packs/CheckpointFirewall/pack_metadata.json
Labels: Contribution, docs-approved

#9766 ExtractIndicatorsFromTextFile - added a file that will switch textwithniticators.txt file (testing file)
  TestData/portuguesetextwithindicators.txt
Labels: docs-approved

#9771 [Prisma Cloud Compute] Update compute integration endpoint (with backward compatibility)
  Packs/PrismaCloudCompute/Integrations/PaloAltoNetworks_PrismaCloudCompute/PaloAltoNetworks_PrismaCloudCompute.py
  Packs/PrismaCloudCompute/Integrations/PaloAltoNetworks_PrismaCloudCompute/PaloAltoNetworks_PrismaCloudCompute.yml
  Packs/PrismaCloudCompute/Integrations/PaloAltoNetworks_PrismaCloudCompute/PaloAltoNetworks_PrismaCloudCompute_test.py
  Packs/PrismaCloudCompute/ReleaseNotes/1_0_4.md
  Packs/PrismaCloudCompute/pack_metadata.json
Labels: Contribution

#9719 [Enhancement] CrowdStrikeIntelV2 - reputation commands to return a list of results
  Packs/CrowdStrikeIntel/Integrations/CrowdStrikeFalconIntel_v2/CrowdStrikeFalconIntel_v2.py
  Packs/CrowdStrikeIntel/ReleaseNotes/2_0_6.md
  Packs/CrowdStrikeIntel/pack_metadata.json
Labels: docs-approved, release-notes-only

#9415 [TBD] G Suite Admin Integration
  Packs/ApiModules/ReleaseNotes/2_0_0.md
  Packs/ApiModules/Scripts/GSuiteApiModule/GSuiteApiModule.py
  Packs/ApiModules/Scripts/GSuiteApiModule/GSuiteApiModule.yml
  Packs/ApiModules/Scripts/GSuiteApiModule/GSuiteApiModule_test.py
  Packs/ApiModules/Scripts/GSuiteApiModule/README.md
  Packs/ApiModules/Scripts/GSuiteApiModule/test_data/service_account_json.txt
  Packs/GSuiteAdmin/.pack-ignore
  Packs/GSuiteAdmin/.secrets-ignore
  Packs/GSuiteAdmin/Integrations/GSuiteAdmin/GSuiteAdmin.py
  Packs/GSuiteAdmin/Integrations/GSuiteAdmin/GSuiteAdmin.yml
  Packs/GSuiteAdmin/Integrations/GSuiteAdmin/GSuiteAdmin_description.md
  Packs/GSuiteAdmin/Integrations/GSuiteAdmin/GSuiteAdmin_image.png
  Packs/GSuiteAdmin/Integrations/GSuiteAdmin/GSuiteAdmin_test.py
  Packs/GSuiteAdmin/Integrations/GSuiteAdmin/Pipfile
  Packs/GSuiteAdmin/Integrations/GSuiteAdmin/Pipfile.lock
  Packs/GSuiteAdmin/Integrations/GSuiteAdmin/README.md
  Packs/GSuiteAdmin/Integrations/GSuiteAdmin/test_data/custom_user_schema_create_entry_context.json
  Packs/GSuiteAdmin/Integrations/GSuiteAdmin/test_data/custom_user_schema_response.json
  Packs/GSuiteAdmin/Integrations/GSuiteAdmin/test_data/custom_user_schema_update_entry_context.json
  Packs/GSuiteAdmin/Integrations/GSuiteAdmin/test_data/data_transfer_request_create_test_data.json
  Packs/GSuiteAdmin/Integrations/GSuiteAdmin/test_data/datatransfer_list_entry_context.json
  Packs/GSuiteAdmin/Integrations/GSuiteAdmin/test_data/datatransfer_list_response.json
  Packs/GSuiteAdmin/Integrations/GSuiteAdmin/test_data/group_create_test_data.json
  Packs/GSuiteAdmin/Integrations/GSuiteAdmin/test_data/role_assignment_create_entry_context.json
  Packs/GSuiteAdmin/Integrations/GSuiteAdmin/test_data/role_assignment_create_response.json
  Packs/GSuiteAdmin/Integrations/GSuiteAdmin/test_data/role_assignment_list_entry_context.json
  Packs/GSuiteAdmin/Integrations/GSuiteAdmin/test_data/role_assignment_list_response.json
  Packs/GSuiteAdmin/Integrations/GSuiteAdmin/test_data/role_create_test_data.json
  Packs/GSuiteAdmin/Integrations/GSuiteAdmin/test_data/service_account_json.txt
  Packs/GSuiteAdmin/Integrations/GSuiteAdmin/test_data/user_alias_add.json
  Packs/GSuiteAdmin/Integrations/GSuiteAdmin/test_data/user_create_args.json
  Packs/GSuiteAdmin/Integrations/GSuiteAdmin/test_data/user_create_entry_context.json
  Packs/GSuiteAdmin/Integrations/GSuiteAdmin/test_data/user_create_response.json
  Packs/GSuiteAdmin/Integrations/GSuiteAdmin/test_data/user_update_entry_context.json
  Packs/GSuiteAdmin/Integrations/GSuiteAdmin/test_data/user_update_response.json
  Packs/GSuiteAdmin/README.md
  Packs/GSuiteAdmin/TestPlaybooks/playbook-GSuiteAdmin-Test.yml
  Packs/GSuiteAdmin/doc_files/add-scope-admin-1.png
  Packs/GSuiteAdmin/doc_files/add-scope-admin-2.png
  Packs/GSuiteAdmin/doc_files/add-scope-admin-3.png
  Packs/GSuiteAdmin/doc_files/create-project-1.png
  Packs/GSuiteAdmin/doc_files/enable-api.jpg
  Packs/GSuiteAdmin/doc_files/enable-gke-api-enable-2.png
  Packs/GSuiteAdmin/doc_files/google-api-menu.png
  Packs/GSuiteAdmin/doc_files/service-account-create-1.png
  Packs/GSuiteAdmin/doc_files/service-account-create-3.png
  Packs/GSuiteAdmin/doc_files/service-account-create-4.png
  Packs/GSuiteAdmin/doc_files/service-acount-menu.png
  Packs/GSuiteAdmin/pack_metadata.json
  Tests/conf.json
Labels: Contribution

#9738 Fix extract domain bug
  Packs/CommonScripts/.secrets-ignore
  Packs/CommonScripts/ReleaseNotes/1_2_71.md
  Packs/CommonScripts/Scripts/ExtractDomainAndFQDNFromUrlAndEmail/ExtractDomainAndFQDNFromUrlAndEmail.py
  Packs/CommonScripts/Scripts/ExtractDomainAndFQDNFromUrlAndEmail/ExtractDomainAndFQDNFromUrlAndEmail.yml
  Packs/CommonScripts/Scripts/ExtractDomainAndFQDNFromUrlAndEmail/ExtractDomainAndFQDNFromUrlAndEmail_test.py
  Packs/CommonScripts/pack_metadata.json
Labels: docs-approved, release-notes-only

#9762 implemented additional logging
  Tests/Marketplace/Tests/marketplace_services_test.py
  Tests/Marketplace/marketplace_services.py
  Tests/Marketplace/normalize_gcs_paths.py
  Tests/Marketplace/prepare_public_index_for_private_testing.py
  Tests/Marketplace/private_build_prepare_for_testing.py
  Tests/Marketplace/upload_git_snapshot.py
  Tests/Marketplace/upload_packs_private.py
  Tests/scripts/prepare_content_packs_for_testing.sh
Labels: docs-approved

#9750 CrowdStrike Falcon Streaming v2 - migrate integration context to be in the expected type
  Packs/CrowdStrikeFalconStreamingV2/Integrations/CrowdStrikeFalconStreamingV2/CrowdStrikeFalconStreamingV2.py
  Packs/CrowdStrikeFalconStreamingV2/Integrations/CrowdStrikeFalconStreamingV2/CrowdStrikeFalconStreamingV2.yml
  Packs/CrowdStrikeFalconStreamingV2/Integrations/CrowdStrikeFalconStreamingV2/CrowdStrikeFalconStreamingV2_test.py
  Packs/CrowdStrikeFalconStreamingV2/ReleaseNotes/1_0_10.md
  Packs/CrowdStrikeFalconStreamingV2/pack_metadata.json
Labels: docs-approved, release-notes-only

#9775 extFilter playbook fix
  Packs/ExtFilter/Playbooks/Test_-_ExtFilter_Main.yml
  Packs/ExtFilter/ReleaseNotes/1_0_1.md
  Packs/ExtFilter/pack_metadata.json
Labels: docs-approved

#9703 Nightly Packs Install
  Tests/Marketplace/Tests/search_and_install_packs_test.py
  Tests/Marketplace/search_and_install_packs.py
Labels: docs-approved

#9779 update docker version for sane-pdf-report
  Packs/Base/ReleaseNotes/1_3_27.md
  Packs/Base/Scripts/SanePdfReport/SanePdfReport.yml
  Packs/Base/pack_metadata.json
Labels: docs-approved

#9754 [Enhancement] OpenPhish v2 - reputation command to return a list of results
  Packs/OpenPhish/Integrations/OpenPhish_v2/OpenPhish_v2.py
  Packs/OpenPhish/Integrations/OpenPhish_v2/OpenPhish_v2.yml
  Packs/OpenPhish/Integrations/OpenPhish_v2/OpenPhish_v2_test.py
  Packs/OpenPhish/ReleaseNotes/2_0_1.md
  Packs/OpenPhish/pack_metadata.json
Labels: docs-approved, release-notes-only

#9788 Wildfire test failure fix
  Packs/Palo_Alto_Networks_WildFire/TestPlaybooks/playbook-Wildfire_Test.yml
  Tests/conf.json
Labels: docs-approved

#9684 EDL - searchIndicators handling
  Packs/EDL/Integrations/EDL/EDL.py
  Packs/EDL/Integrations/EDL/EDL.yml
  Packs/EDL/ReleaseNotes/1_0_4.md
  Packs/EDL/pack_metadata.json
Labels: docs-approved, release-notes-only

#9653 Hash incidents fix
  Packs/ML/ReleaseNotes/1_2_1.md
  Packs/ML/Scripts/HashIncidentsFields/HashIncidentsFields.py
  Packs/ML/Scripts/HashIncidentsFields/HashIncidentsFields.yml
  Packs/ML/pack_metadata.json
Labels: docs-approved

#9735 Box - created docs
  Packs/Box/Integrations/README.md
  Packs/Box/Integrations/command_examples
Labels: docs-approved

#9776 ExtractIndicatorsFromTextFile - fixed an issue where txt file with P…
  Packs/CommonPlaybooks/TestPlaybooks/playbook-Extract_Indicators_From_File_-_Generic_v2_-_Test_4_5.yml
  Packs/CommonScripts/ReleaseNotes/1_2_72.md
  Packs/CommonScripts/Scripts/ExtractIndicatorsFromTextFile/ExtractIndicatorsFromTextFile.py
  Packs/CommonScripts/Scripts/ExtractIndicatorsFromTextFile/ExtractIndicatorsFromTextFile.yml
  Packs/CommonScripts/pack_metadata.json
  Tests/scripts/infrastructure_tests/test_collect_tests_and_content_packs.py
Labels: docs-approved, release-notes-only

#9756 Rasterize - generated docs
  Packs/rasterize/.secrets-ignore
  Packs/rasterize/Integrations/rasterize/README.md
  Packs/rasterize/Integrations/rasterize/command_examples.txt
  Packs/rasterize/Integrations/rasterize/doc_files/rasterize_email_command_output.png
  Packs/rasterize/Integrations/rasterize/doc_files/rasterize_url_command_output.png
  Packs/rasterize/ReleaseNotes/1_0_5.md
  Packs/rasterize/pack_metadata.json
Labels: docs-approved

#9660 Threat connect v2 - fix get_indicators method
  Packs/ThreatConnect/Integrations/ThreatConnect_v2/ThreatConnect_v2.py
  Packs/ThreatConnect/Integrations/ThreatConnect_v2/ThreatConnect_v2.yml
  Packs/ThreatConnect/ReleaseNotes/2_0_9.md
  Packs/ThreatConnect/pack_metadata.json
Labels: docs-approved, release-notes-only

#9332 use stringUnEscape in add_replace_strs method
  Packs/Base/ReleaseNotes/1_3_28.md
  Packs/Base/Scripts/CommonServerPython/CommonServerPython.py
  Packs/Base/Scripts/CommonServerPython/CommonServerPython_test.py
  Packs/Base/pack_metadata.json
Labels: docs-approved, release-notes-only

#9727 fixed test playbooks
  Packs/Active_Directory_Query/TestPlaybooks/playbook-Active_Directory_Test.yml
  Packs/Gmail/TestPlaybooks/playbook-GmailTest.yml
  Packs/MicrosoftGraphUser/TestPlaybooks/Microsoft_Graph_User_test.yml
  Packs/Okta/TestPlaybooks/OktaV2-Test.yml
  Tests/test_integration.py
  Tests/tests/test_integration_test.py
Labels: docs-approved

#9757 [Enhancement] VirusTotal - reputation command to return a list of results
  Packs/VirusTotal/Integrations/integration-VirusTotal_5.5.yml
  Packs/VirusTotal/ReleaseNotes/1_0_2.md
  Packs/VirusTotal/TestPlaybooks/playbook-virusTotal-test.yml
  Packs/VirusTotal/pack_metadata.json
Labels: docs-approved, release-notes-only

#9503 Added the customFields argument to the hpsm-create-incident command
  Packs/HPE_Service_Manager/Integrations/integration-HPE_Service_Manager.yml
  Packs/HPE_Service_Manager/ReleaseNotes/1_0_2.md
  Packs/HPE_Service_Manager/pack_metadata.json
Labels: docs-approved, release-notes-only

#9645 Cortex XDR rate limit phase1
  Packs/CortexXDR/Integrations/PaloAltoNetworks_XDR/PaloAltoNetworks_XDR.py
  Packs/CortexXDR/Integrations/PaloAltoNetworks_XDR/PaloAltoNetworks_XDR.yml
  Packs/CortexXDR/Integrations/PaloAltoNetworks_XDR/PaloAltoNetworks_XDR_test.py
  Packs/CortexXDR/Integrations/PaloAltoNetworks_XDR/README.md
  Packs/CortexXDR/Integrations/PaloAltoNetworks_XDR/test_data/incident_example_from_extra_data_command.json
  Packs/CortexXDR/ReleaseNotes/2_4_8.md
  Packs/CortexXDR/pack_metadata.json
Labels: docs-approved

#9794 update docker version for sane-doc-report
  Packs/Base/ReleaseNotes/1_3_29.md
  Packs/Base/Scripts/SaneDocReportV2/SaneDocReportV2.yml
  Packs/Base/pack_metadata.json
Labels: docs-approved

#9792 Feed Mitre Attack - date fields values fix
  Packs/FeedMitreAttack/Integrations/FeedMitreAttack/FeedMitreAttack.py
  Packs/FeedMitreAttack/Integrations/FeedMitreAttack/FeedMitreAttack.yml
  Packs/FeedMitreAttack/Integrations/FeedMitreAttack/FeedMitreAttack_test.py
  Packs/FeedMitreAttack/ReleaseNotes/1_1_6.md
  Packs/FeedMitreAttack/pack_metadata.json
Labels: docs-approved, release-notes-only

#9736 Ewsv2 protected mail skipping
  Packs/EWS/Integrations/EWSv2/EWSv2.py
  Packs/EWS/ReleaseNotes/1_3_9.md
  Packs/EWS/pack_metadata.json
Labels: docs-approved, release-notes-only

#9571 Fixed an issue that it doesn't decode the content with charset
  Packs/CommonScripts/ReleaseNotes/1_2_73.md
  Packs/CommonScripts/Scripts/ParseEmailFiles/ParseEmailFiles.py
  Packs/CommonScripts/pack_metadata.json
  Packs/EWS/Integrations/EWSv2/EWSv2.py
  Packs/EWS/ReleaseNotes/1_3_9.md
  Packs/EWS/pack_metadata.json
  Packs/FeedMitreAttack/Integrations/FeedMitreAttack/FeedMitreAttack.py
  Packs/FeedMitreAttack/Integrations/FeedMitreAttack/FeedMitreAttack.yml
  Packs/FeedMitreAttack/Integrations/FeedMitreAttack/FeedMitreAttack_test.py
  Packs/FeedMitreAttack/ReleaseNotes/1_1_6.md
  Packs/FeedMitreAttack/pack_metadata.json
  Tests/conf.json
  Tests/scripts/update_conf_json.py
  Tests/scripts/utils/log_util.py
Labels: Contribution, docs-approved, release-notes-only

#9795 Archer v2 - Values List fixes
  Packs/ArcherRSA/Integrations/ArcherV2/ArcherV2.py
  Packs/ArcherRSA/Integrations/ArcherV2/ArcherV2_test.py
  Packs/ArcherRSA/ReleaseNotes/1_1_3.md
  Packs/ArcherRSA/pack_metadata.json
Labels: docs-approved, release-notes-only

#9621 Stop all chromium zombie processes when SanePDFReports script finished
  Packs/Base/ReleaseNotes/1_3_30.md
  Packs/Base/Scripts/SanePdfReport/SanePdfReport.py
  Packs/Base/Scripts/SanePdfReport/SanePdfReport.yml
  Packs/Base/Scripts/SanePdfReport/SanePdfReport_test.py
  Packs/Base/pack_metadata.json
Labels: docs-approved, release-notes-only

#9802 Zimperium- Updated the **file** command, to return a different result for each indicator
  Packs/Zimperium/Integrations/Zimperium/Zimperium.py
  Packs/Zimperium/Integrations/Zimperium/Zimperium.yml
  Packs/Zimperium/Integrations/Zimperium/Zimperium_test.py
  Packs/Zimperium/ReleaseNotes/1_0_5.md
  Packs/Zimperium/pack_metadata.json
Labels: docs-approved

#9778 Vt bug fix
  Packs/VirusTotal-Private_API/Integrations/VirusTotal-Private_API/README.md
  Packs/VirusTotal-Private_API/Integrations/VirusTotal-Private_API/VirusTotal-Private_API.py
  Packs/VirusTotal-Private_API/Integrations/VirusTotal-Private_API/VirusTotal-Private_API.yml
  Packs/VirusTotal-Private_API/Integrations/VirusTotal-Private_API/VirusTotal-Private_API_test.py
  Packs/VirusTotal-Private_API/Integrations/VirusTotal-Private_API/VirusTotal_test.py
  Packs/VirusTotal-Private_API/Integrations/VirusTotal-Private_API/test_data/get_url_report_demisto.json
  Packs/VirusTotal-Private_API/ReleaseNotes/1_0_5.md
  Packs/VirusTotal-Private_API/pack_metadata.json
Labels: bug, docs-approved

#9784 Aws - setup bug fix
  Packs/AWS-ACM/Integrations/AWS-ACM/AWS-ACM.py
  Packs/AWS-ACM/Integrations/AWS-ACM/AWS-ACM.yml
  Packs/AWS-ACM/ReleaseNotes/1_0_2.md
  Packs/AWS-ACM/pack_metadata.json
  Packs/AWS-AccessAnalyzer/Integrations/AWS-AccessAnalyzer/AWS-AccessAnalyzer.py
  Packs/AWS-AccessAnalyzer/ReleaseNotes/1_0_3.md
  Packs/AWS-AccessAnalyzer/pack_metadata.json
  Packs/AWS-Athena/Integrations/AWS-Athena/AWS-Athena.py
  Packs/AWS-Athena/ReleaseNotes/1_0_2.md
  Packs/AWS-Athena/pack_metadata.json
  Packs/AWS-CloudTrail/Integrations/AWS-CloudTrail/AWS-CloudTrail.py
  Packs/AWS-CloudTrail/Integrations/AWS-CloudTrail/AWS-CloudTrail.yml
  Packs/AWS-CloudTrail/ReleaseNotes/1_0_3.md
  Packs/AWS-CloudTrail/pack_metadata.json
  Packs/AWS-EC2/Integrations/AWS-EC2/AWS-EC2.py
  Packs/AWS-EC2/Integrations/AWS-EC2/AWS-EC2.yml
  Packs/AWS-EC2/ReleaseNotes/1_1_4.md
  Packs/AWS-EC2/pack_metadata.json
  Packs/AWS-IAM/Integrations/AWS-IAM/AWS-IAM.py
  Packs/AWS-IAM/Integrations/AWS-IAM/AWS-IAM.yml
  Packs/AWS-IAM/ReleaseNotes/1_0_1.md
  Packs/AWS-IAM/pack_metadata.json
  Packs/AWS-Lambda/Integrations/AWS-Lambda/AWS-Lambda.py
  Packs/AWS-Lambda/Integrations/AWS-Lambda/AWS-Lambda.yml
  Packs/AWS-Lambda/ReleaseNotes/1_0_2.md
  Packs/AWS-Lambda/pack_metadata.json
  Packs/AWS-S3/Integrations/AWS-S3/AWS-S3.py
  Packs/AWS-S3/Integrations/AWS-S3/AWS-S3.yml
  Packs/AWS-S3/ReleaseNotes/1_0_3.md
  Packs/AWS-S3/pack_metadata.json
  Packs/AWS-SecurityHub/Integrations/AWS_SecurityHub/AWS_SecurityHub.py
  Packs/AWS-SecurityHub/Integrations/AWS_SecurityHub/AWS_SecurityHub.yml
  Packs/AWS-SecurityHub/ReleaseNotes/1_0_3.md
  Packs/AWS-SecurityHub/pack_metadata.json
  Packs/AWS_DynamoDB/Integrations/AWS_DynamoDB/AWS_DynamoDB.py
  Packs/AWS_DynamoDB/Integrations/AWS_DynamoDB/AWS_DynamoDB.yml
  Packs/AWS_DynamoDB/ReleaseNotes/1_0_3.md
  Packs/AWS_DynamoDB/pack_metadata.json
  Tests/conf.json
Labels: bug, docs-approved, release-notes-only

#9770 Hod/version mismatch
  Tests/Marketplace/Tests/marketplace_services_test.py
  Tests/Marketplace/marketplace_services.py
Labels: docs-approved

#9559 Carbonblack edr add commands
  Packs/CarbonBlackEnterpriseEDR/Integrations/CarbonBlackEnterpriseEDR/CarbonBlackEnterpriseEDR.py
  Packs/CarbonBlackEnterpriseEDR/Integrations/CarbonBlackEnterpriseEDR/CarbonBlackEnterpriseEDR.yml
  Packs/CarbonBlackEnterpriseEDR/Integrations/CarbonBlackEnterpriseEDR/CarbonBlackEnterpriseEDR_description.md
  Packs/CarbonBlackEnterpriseEDR/Integrations/CarbonBlackEnterpriseEDR/CarbonBlackEnterpriseEDR_test.py
  Packs/CarbonBlackEnterpriseEDR/Integrations/CarbonBlackEnterpriseEDR/README.md
  Packs/CarbonBlackEnterpriseEDR/Integrations/CarbonBlackEnterpriseEDR/command_examples.txt
  Packs/CarbonBlackEnterpriseEDR/Integrations/CarbonBlackEnterpriseEDR/test_data/raw_data.py
  Packs/CarbonBlackEnterpriseEDR/Playbooks/Carbon_Black_EDR_Search_Process.yml
  Packs/CarbonBlackEnterpriseEDR/Playbooks/Carbon_Black_EDR_Search_Process_README.md
  Packs/CarbonBlackEnterpriseEDR/ReleaseNotes/1_1_0.md
  Packs/CarbonBlackEnterpriseEDR/TestPlaybooks/Carbon_Black_Enterprise_EDR_Process_Search_Test.yml
  Packs/CarbonBlackEnterpriseEDR/TestPlaybooks/Carbon_Black_Enterprise_EDR_Test.yml
  Packs/CarbonBlackEnterpriseEDR/pack_metadata.json
Labels: docs-approved

#9542 Fe feed incremental
  Packs/FeedFireEye/Integrations/FeedFireEye/FeedFireEye.py
  Packs/FeedFireEye/Integrations/FeedFireEye/FeedFireEye.yml
  Packs/FeedFireEye/Integrations/FeedFireEye/FeedFireEye_test.py
  Packs/FeedFireEye/Integrations/FeedFireEye/README.md
  Packs/FeedFireEye/ReleaseNotes/2_0_0.md
  Packs/FeedFireEye/pack_metadata.json
  Tests/conf.json
Labels: docs-approved

#9740 SNOWv2 - request type argument change
  Packs/ServiceNow/Integrations/ServiceNowv2/ServiceNowv2.py
  Packs/ServiceNow/ReleaseNotes/1_3_9.md
  Packs/ServiceNow/TestPlaybooks/playbook-ServiceNow_Test_New.yml
  Packs/ServiceNow/pack_metadata.json
Labels: docs-approved, release-notes-only

#9799 MicrosoftGraphListener - Add self deployed microsoft graph listener
  Packs/ApiModules/ReleaseNotes/1_1_6.md
  Packs/ApiModules/Scripts/MicrosoftApiModule/MicrosoftApiModule.py
  Packs/ApiModules/Scripts/MicrosoftApiModule/MicrosoftApiModule.yml
  Packs/ApiModules/pack_metadata.json
  Packs/AzureCompute/ReleaseNotes/1_0_2.md
  Packs/AzureCompute/pack_metadata.json
  Packs/AzureLogAnalytics/ReleaseNotes/1_0_1.md
  Packs/AzureLogAnalytics/pack_metadata.json
  Packs/AzureSecurityCenter/ReleaseNotes/1_1_3.md
  Packs/AzureSecurityCenter/pack_metadata.json
  Packs/AzureSentinel/ReleaseNotes/1_0_3.md
  Packs/AzureSentinel/pack_metadata.json
  Packs/EWS/ReleaseNotes/1_4_0.md
  Packs/EWS/pack_metadata.json
  Packs/MicrosoftDefenderAdvancedThreatProtection/ReleaseNotes/1_2_4.md
  Packs/MicrosoftDefenderAdvancedThreatProtection/pack_metadata.json
  Packs/MicrosoftGraphCalendar/ReleaseNotes/1_0_3.md
  Packs/MicrosoftGraphCalendar/pack_metadata.json
  Packs/MicrosoftGraphDeviceManagement/ReleaseNotes/1_0_3.md
  Packs/MicrosoftGraphDeviceManagement/pack_metadata.json
  Packs/MicrosoftGraphFiles/ReleaseNotes/1_0_2.md
  Packs/MicrosoftGraphFiles/pack_metadata.json
  Packs/MicrosoftGraphGroups/ReleaseNotes/1_0_2.md
  Packs/MicrosoftGraphGroups/pack_metadata.json
  Packs/MicrosoftGraphListener/Integrations/MicrosoftGraphListener/MicrosoftGraphListener.py
  Packs/MicrosoftGraphListener/Integrations/MicrosoftGraphListener/MicrosoftGraphListener.yml
  Packs/MicrosoftGraphListener/Integrations/MicrosoftGraphListener/MicrosoftGraphListener_description.md
  Packs/MicrosoftGraphListener/Integrations/MicrosoftGraphListener/MicrosoftGraphListener_test.py
  Packs/MicrosoftGraphListener/Integrations/MicrosoftGraphListener/README.md
  Packs/MicrosoftGraphListener/ReleaseNotes/1_0_8.md
  Packs/MicrosoftGraphListener/pack_metadata.json
  Packs/MicrosoftGraphMail/ReleaseNotes/1_0_12.md
  Packs/MicrosoftGraphMail/pack_metadata.json
  Packs/MicrosoftGraphSecurity/ReleaseNotes/2_0_4.md
  Packs/MicrosoftGraphSecurity/pack_metadata.json
  Packs/MicrosoftGraphUser/ReleaseNotes/1_3_4.md
  Packs/MicrosoftGraphUser/pack_metadata.json
  Packs/MicrosoftManagementActivity/ReleaseNotes/1_1_2.md
  Packs/MicrosoftManagementActivity/pack_metadata.json
Labels: docs-approved

#9805 Demisto-sdk release 1.2.8
  dev-requirements-py3.txt
Labels: docs-approved

#9793 Speed up pack dependencies calculations
  Tests/Marketplace/Tests/test_pack_dependencies.py
  Tests/Marketplace/packs_dependencies.py
Labels: docs-approved

#9682 New images for demonstrating the IAM content pack (incident, indicator, dashboard)
  Images/dashboard_page1.png
  Images/incident_page1.PNG
  Images/indicator_page1.png
Labels: IAM, docs-approved

#9768 Debug mode: additional logging
  Packs/Base/ReleaseNotes/1_3_31.md
  Packs/Base/Scripts/CommonServerPython/CommonServerPython.py
  Packs/Base/pack_metadata.json
Labels: docs-approved, release-notes-only

#9810 [Enhancement] MicrosoftCloudAppSecurity - reputation commands to return a list of results
  Packs/MicrosoftCloudAppSecurity/Integrations/MicrosoftCloudAppSecurity/MicrosoftCloudAppSecurity.py
  Packs/MicrosoftCloudAppSecurity/Integrations/MicrosoftCloudAppSecurity/MicrosoftCloudAppSecurity_test.py
  Packs/MicrosoftCloudAppSecurity/ReleaseNotes/1_0_9.md
  Packs/MicrosoftCloudAppSecurity/pack_metadata.json
Labels: docs-approved

#9808 [Enhancement] HelloWorld - reputation commands to return a list of results
  Packs/HelloWorld/Integrations/HelloWorld/HelloWorld.py
  Packs/HelloWorld/Integrations/HelloWorld/HelloWorld_test.py
  Packs/HelloWorld/Integrations/HelloWorld/README.md
  Packs/HelloWorld/ReleaseNotes/1_1_12.md
  Packs/HelloWorld/pack_metadata.json
Labels: docs-approved, release-notes-only

#9639 Refactor get_modified_files_for_testing
  Tests/scripts/collect_tests_and_content_packs.py
  Tests/scripts/infrastructure_tests/test_collect_tests_and_content_packs.py
  Tests/scripts/utils/collect_helpers.py
  Tests/scripts/utils/get_modified_files_for_testing.py
  Tests/scripts/utils/tests/__init__.py
  Tests/scripts/utils/tests/test_get_modified_files_for_testing.py
Labels: docs-approved

#9797 fix ParseEmailFiles bug
  Packs/CommonScripts/.secrets-ignore
  Packs/CommonScripts/ReleaseNotes/1_2_73.md
  Packs/CommonScripts/Scripts/ParseEmailFiles/ParseEmailFiles.py
  Packs/CommonScripts/Scripts/ParseEmailFiles/parse_email_files_test.py
  Packs/CommonScripts/pack_metadata.json
Labels: docs-approved, release-notes-only

#9819 Bucket Version Assertion Fix
  Tests/Marketplace/marketplace_services.py
Labels: docs-approved

#9812 Crowdstrike falcon intel v2 bang commands - csv values
  Packs/CrowdStrikeIntel/Integrations/CrowdStrikeFalconIntel_v2/CrowdStrikeFalconIntel_v2.py
  Packs/CrowdStrikeIntel/Integrations/CrowdStrikeFalconIntel_v2/CrowdStrikeFalconIntel_v2.yml
  Packs/CrowdStrikeIntel/Integrations/CrowdStrikeFalconIntel_v2/CrowdStrikeFalconIntel_v2_test.py
  Packs/CrowdStrikeIntel/Integrations/CrowdStrikeFalconIntel_v2/README.md
  Packs/CrowdStrikeIntel/ReleaseNotes/2_0_7.md
  Packs/CrowdStrikeIntel/TestPlaybooks/playbook-CrowdStrikeFalconIntel_v2_Test.yml
  Packs/CrowdStrikeIntel/pack_metadata.json
Labels: docs-approved

#9588 Added values for incident status
  Packs/ExtraHop/Integrations/ExtraHop_v2/README.md
Labels: docs-approved

#9767 Removed extra space in Active Directory description
  Packs/Active_Directory_Query/Integrations/Active_Directory_Query/Active_Directory_Query.yml
  Packs/Active_Directory_Query/ReleaseNotes/1_1_0.md
  Packs/Active_Directory_Query/pack_metadata.json
Labels: IAM, docs-approved, release-notes-only

#9619 ExtraHop Reveal(x) - Use new v2 Ticket Tracking Playbook and Update new style incident layout
  Packs/ExtraHop/Layouts/layoutscontainer-ExtraHop_Detection.json
  Packs/ExtraHop/Playbooks/playbook-ExtraHop_-_Default.yml
  Packs/ExtraHop/Playbooks/playbook-ExtraHop_-_Default_README.md
  Packs/ExtraHop/ReleaseNotes/1_0_5.md
  Packs/ExtraHop/pack_metadata.json
Labels: Contribution, ready-for-instance-test

#9804 update py dependencies
  .circleci/build-requirements.txt
  .circleci/config.yml
  Tests/scripts/collect_tests_and_content_packs.py
  Tests/test_integration.py
  dev-requirements-py2.txt
  dev-requirements-py3.txt
Labels: docs-approved

#9717 Microsoft Graph Mail - store receivedDateTime instead of lastModifiedDateTime in last fetch
  Packs/MicrosoftGraphListener/Integrations/MicrosoftGraphListener/MicrosoftGraphListener.py
  Packs/MicrosoftGraphListener/ReleaseNotes/1_0_9.md
  Packs/MicrosoftGraphListener/pack_metadata.json
  Packs/MicrosoftGraphMail/Integrations/MicrosoftGraphMail/MicrosoftGraphMail.py
  Packs/MicrosoftGraphMail/ReleaseNotes/1_0_13.md
  Packs/MicrosoftGraphMail/pack_metadata.json
Labels: docs-approved, release-notes-only

#9823 SentinelOne v2 - deprecated the sentinelone-expire-site command
  Packs/SentinelOne/Integrations/SentinelOne-V2/SentinelOne-V2.yml
  Packs/SentinelOne/ReleaseNotes/1_0_3.md
  Packs/SentinelOne/pack_metadata.json
Labels: docs-approved, release-notes-only

#9824 GetOnCallHoursPerUser - Changed to bar chart
  Packs/ShiftManagement/ReleaseNotes/1_1_3.md
  Packs/ShiftManagement/Scripts/GetOnCallHoursPerUser/GetOnCallHoursPerUser.py
  Packs/ShiftManagement/Scripts/GetOnCallHoursPerUser/GetOnCallHoursPerUser.yml
  Packs/ShiftManagement/Scripts/GetOnCallHoursPerUser/GetOnCallHoursPerUser_test.py
  Packs/ShiftManagement/pack_metadata.json
Labels: docs-approved, release-notes-only

#9785 Added AD incoming & outgoing mapper configuration documentation
  Packs/Active_Directory_Query/Integrations/Active_Directory_Query/README.md
Labels: IAM, docs-approved

#9427 [TBD] New commands in Gmail Integration
  Packs/Gmail/.secrets-ignore
  Packs/Gmail/Integrations/Gmail/Gmail.py
  Packs/Gmail/Integrations/Gmail/Gmail.yml
  Packs/Gmail/Integrations/Gmail/Gmail_description.md
  Packs/Gmail/Integrations/Gmail/Gmail_test.py
  Packs/Gmail/Integrations/Gmail/README.md
  Packs/Gmail/ReleaseNotes/1_1_0.md
  Packs/Gmail/pack_metadata.json
Labels: Contribution

#9786 Added Okta incoming & outgoing mapper configuration documentation
  Packs/Okta/Integrations/Okta_IAM/README.md
Labels: IAM, docs-approved

#9747 SMB - add note about smb2
  Packs/SMB/Integrations/SMB/README.md
Labels: docs-approved

#9806 removed random tests
  Packs/Gmail/TestPlaybooks/Sanity_Test_-_Playbook_with_Unmockable_Integrationyml
  Packs/HelloWorld/TestPlaybooks/Sanity_Test_-No_Integration.yml
  Packs/HelloWorld/TestPlaybooks/Sanity_Test_-_Playbook_with_integration.yml
  Packs/HelloWorld/TestPlaybooks/Sanity_Test_-_Playbook_with_mocked_integration.yml
  Tests/scripts/collect_tests_and_content_packs.py
  Tests/scripts/infrastructure_tests/test_collect_tests_and_content_packs.py
Labels: docs-approved

#9831 CSP - Added pipe character to MD escape chars
  Packs/Base/ReleaseNotes/1_3_32.md
  Packs/Base/Scripts/CommonServerPython/CommonServerPython.py
  Packs/Base/Scripts/CommonServerPython/CommonServerPython_test.py
  Packs/Base/pack_metadata.json
Labels: docs-approved, release-notes-only

#9814 Workday IAM fetch-incidents fix
  Packs/Workday/Integrations/Workday_IAM/Workday_IAM.py
  Packs/Workday/ReleaseNotes/1_0_4.md
  Packs/Workday/pack_metadata.json
  Tests/demistomock/demistomock.py
Labels: docs-approved

#9830 remove duplicate incident fields
  Packs/Compliance/IncidentFields/DPONotificationstatus.json
  Packs/Compliance/IncidentFields/IndividualsNotifictionStatus.json
  Packs/Compliance/IncidentFields/ManagementNotificationStatus.json
  Packs/Compliance/IncidentFields/SecretaryNotificationStatus.json
  Packs/Compliance/IncidentFields/incidentfield-Management_Notification.json
  Packs/Compliance/ReleaseNotes/1_0_6.md
  Packs/Compliance/pack_metadata.json
Labels: docs-approved

#9659 Idefense v2
  Packs/Expanse/TestPlaybooks/playbook-Expanse-Test.yml
  Packs/iDefense/.secrets-ignore
  Packs/iDefense/Integrations/iDefense_v2/Pipfile
  Packs/iDefense/Integrations/iDefense_v2/Pipfile.lock
  Packs/iDefense/Integrations/iDefense_v2/README.md
  Packs/iDefense/Integrations/iDefense_v2/iDefense_v2.py
  Packs/iDefense/Integrations/iDefense_v2/iDefense_v2.yml
  Packs/iDefense/Integrations/iDefense_v2/iDefense_v2_description.md
  Packs/iDefense/Integrations/iDefense_v2/iDefense_v2_image.png
  Packs/iDefense/Integrations/iDefense_v2/iDefense_v2_test.py
  Packs/iDefense/Integrations/iDefense_v2/test_data/response_constants.py
  Packs/iDefense/Integrations/integration-iDefense.yml
  Packs/iDefense/ReleaseNotes/2_0_0.md
  Packs/iDefense/TestPlaybooks/iDefense_v2-Test.yml
  Packs/iDefense/pack_metadata.json
  Tests/conf.json
Labels: docs-approved

#9357 GCP kubernetes playbooks
  Packs/PrismaCloud/Classifiers/classifier-Prisma_Cloud.json
  Packs/PrismaCloud/Classifiers/classifier-Prisma_Cloud_5_9_9.json
  Packs/PrismaCloud/Classifiers/classifier-mapper-incoming-Prisma_Cloud.json
  Packs/PrismaCloud/Classifiers/classifier-mapper-incoming-prismaCloud_app.json
  Packs/PrismaCloud/Classifiers/classifier-prismaCloud_app.json
  Packs/PrismaCloud/Classifiers/classifier-prismaCloud_app_5_9_9.json
  Packs/PrismaCloud/IncidentFields/incidentfield-Prisma_Cloud_ID.json
  Packs/PrismaCloud/IncidentFields/incidentfield-Prisma_Cloud_Reason.json
  Packs/PrismaCloud/IncidentFields/incidentfield-Prisma_Cloud_Rules.json
  Packs/PrismaCloud/IncidentFields/incidentfield-Prisma_Cloud_Status.json
  Packs/PrismaCloud/IncidentFields/incidentfield-Prisma_Cloud_Time.json
  Packs/PrismaCloud/IncidentFields/incidentfield-RRN.json
  Packs/PrismaCloud/IncidentFields/incidentfield-Resource_API_Name.json
  Packs/PrismaCloud/IncidentFields/incidentfield-Resource_Cloud_Type.json
  Packs/PrismaCloud/IncidentFields/incidentfield-Subscription_Assigned_By.json
  Packs/PrismaCloud/IncidentFields/incidentfield-Subscription_Created_By.json
  Packs/PrismaCloud/IncidentFields/incidentfield-Subscription_Created_On.json
  Packs/PrismaCloud/IncidentFields/incidentfield-Subscription_Description.json
  Packs/PrismaCloud/IncidentFields/incidentfield-Subscription_ID.json
  Packs/PrismaCloud/IncidentFields/incidentfield-Subscription_Name.json
  Packs/PrismaCloud/IncidentFields/incidentfield-Subscription_Type.json
  Packs/PrismaCloud/IncidentFields/incidentfield-Subscription_Updated_By.json
  Packs/PrismaCloud/IncidentFields/incidentfield-Subscription_Updated_On.json
  Packs/PrismaCloud/IncidentFields/incidentfield-System_Default.json
  Packs/PrismaCloud/IncidentFields/incidentfield-VPC_ID.json
  Packs/PrismaCloud/IncidentTypes/incidenttype-GCP_Kubernetes_Engine_Misconfiguration.json
  Packs/PrismaCloud/Layouts/layout-detailsV2-GCP_Kubernetes_Engine_Misconfiguration.json
  Packs/PrismaCloud/Layouts/layoutscontainer-GCP_Kubernetes_Engine_Misconfiguration.json
  Packs/PrismaCloud/Playbooks/playbook-PCR_-_GCP_Kub_Engine_Cluster_Misconfig.yml
  Packs/PrismaCloud/Playbooks/playbook-PCR_-_GCP_Kub_Engine_Cluster_Misconfig_README.md
  Packs/PrismaCloud/Playbooks/playbook-PCR_-_GCP_Kub_Engine_Misconfig.yml
  Packs/PrismaCloud/Playbooks/playbook-PCR_-_GCP_Kub_Engine_Misconfig_README.md
  Packs/PrismaCloud/ReleaseNotes/1_3_0.md
  Packs/PrismaCloud/doc_files/PCR_-_GCP_Kub_Engine_Cluster_Misconfig.png
  Packs/PrismaCloud/doc_files/PCR_-_GCP_Kub_Engine_Misconfig.png
  Packs/PrismaCloud/pack_metadata.json
Labels: Contribution, docs-approved

#9714 add custom attributes to user filter
  Packs/OpenLDAP/Integrations/OpenLDAP/OpenLDAP.py
  Packs/OpenLDAP/Integrations/OpenLDAP/OpenLDAP.yml
  Packs/OpenLDAP/ReleaseNotes/1_0_2.md
  Packs/OpenLDAP/pack_metadata.json
Labels: docs-approved

#9848 added sanity tests
  Tests/conf.json
Labels: docs-approved

#9850 added point
  Packs/Gmail/TestPlaybooks/Sanity_Test_-_Playbook_with_Unmockable_Integration.yml
Labels: docs-approved

#9490 Panorama docs revamp and bug fix
  Packs/PAN-OS/.secrets-ignore
  Packs/PAN-OS/Integrations/Panorama/Panorama.py
  Packs/PAN-OS/Integrations/Panorama/Panorama.yml
  Packs/PAN-OS/Integrations/Panorama/README.md
  Packs/PAN-OS/Integrations/Panorama/command_examples.txt
  Packs/PAN-OS/ReleaseNotes/1_6_4.md
  Packs/PAN-OS/pack_metadata.json
Labels: bug, docs-approved

#9851 unskip mail sender
  Tests/conf.json
Labels: docs-approved

#9834 Fixed two issues with TableToMarkdown
  Packs/Base/ReleaseNotes/1_3_33.md
  Packs/Base/Scripts/CommonServerPowerShell/CommonServerPowerShell.Tests.ps1
  Packs/Base/Scripts/CommonServerPowerShell/CommonServerPowerShell.ps1
  Packs/Base/pack_metadata.json
Labels: docs-approved, release-notes-only

#9849 Update pre-commit
  .hooks/pre-commit
Labels: docs-approved

#9860 Fix carbon test playbook
  Packs/CarbonBlackEnterpriseEDR/TestPlaybooks/Carbon_Black_Enterprise_EDR_Test.yml
  Tests/conf.json
Labels: docs-approved

#9859 GCP kubernetes playbooks (#9357)
  Packs/PrismaCloud/Classifiers/classifier-Prisma_Cloud.json
  Packs/PrismaCloud/Classifiers/classifier-Prisma_Cloud_5_9_9.json
  Packs/PrismaCloud/Classifiers/classifier-mapper-incoming-Prisma_Cloud.json
  Packs/PrismaCloud/Classifiers/classifier-mapper-incoming-prismaCloud_app.json
  Packs/PrismaCloud/Classifiers/classifier-prismaCloud_app.json
  Packs/PrismaCloud/Classifiers/classifier-prismaCloud_app_5_9_9.json
  Packs/PrismaCloud/IncidentFields/incidentfield-Prisma_Cloud_ID.json
  Packs/PrismaCloud/IncidentFields/incidentfield-Prisma_Cloud_Reason.json
  Packs/PrismaCloud/IncidentFields/incidentfield-Prisma_Cloud_Rules.json
  Packs/PrismaCloud/IncidentFields/incidentfield-Prisma_Cloud_Status.json
  Packs/PrismaCloud/IncidentFields/incidentfield-Prisma_Cloud_Time.json
  Packs/PrismaCloud/IncidentFields/incidentfield-RRN.json
  Packs/PrismaCloud/IncidentFields/incidentfield-Resource_API_Name.json
  Packs/PrismaCloud/IncidentFields/incidentfield-Resource_Cloud_Type.json
  Packs/PrismaCloud/IncidentFields/incidentfield-Subscription_Assigned_By.json
  Packs/PrismaCloud/IncidentFields/incidentfield-Subscription_Created_By.json
  Packs/PrismaCloud/IncidentFields/incidentfield-Subscription_Created_On.json
  Packs/PrismaCloud/IncidentFields/incidentfield-Subscription_Description.json
  Packs/PrismaCloud/IncidentFields/incidentfield-Subscription_ID.json
  Packs/PrismaCloud/IncidentFields/incidentfield-Subscription_Name.json
  Packs/PrismaCloud/IncidentFields/incidentfield-Subscription_Type.json
  Packs/PrismaCloud/IncidentFields/incidentfield-Subscription_Updated_By.json
  Packs/PrismaCloud/IncidentFields/incidentfield-Subscription_Updated_On.json
  Packs/PrismaCloud/IncidentFields/incidentfield-System_Default.json
  Packs/PrismaCloud/IncidentFields/incidentfield-VPC_ID.json
  Packs/PrismaCloud/IncidentTypes/incidenttype-GCP_Kubernetes_Engine_Misconfiguration.json
  Packs/PrismaCloud/Layouts/layout-detailsV2-GCP_Kubernetes_Engine_Misconfiguration.json
  Packs/PrismaCloud/Layouts/layoutscontainer-GCP_Kubernetes_Engine_Misconfiguration.json
  Packs/PrismaCloud/Playbooks/playbook-PCR_-_GCP_Kub_Engine_Cluster_Misconfig.yml
  Packs/PrismaCloud/Playbooks/playbook-PCR_-_GCP_Kub_Engine_Cluster_Misconfig_README.md
  Packs/PrismaCloud/Playbooks/playbook-PCR_-_GCP_Kub_Engine_Misconfig.yml
  Packs/PrismaCloud/Playbooks/playbook-PCR_-_GCP_Kub_Engine_Misconfig_README.md
  Packs/PrismaCloud/ReleaseNotes/1_3_0.md
  Packs/PrismaCloud/doc_files/PCR_-_GCP_Kub_Engine_Cluster_Misconfig.png
  Packs/PrismaCloud/doc_files/PCR_-_GCP_Kub_Engine_Misconfig.png
  Packs/PrismaCloud/pack_metadata.json
Labels: docs-approved

#9781 [TBD] G Suite Admin Integration (#9415)
  Packs/ApiModules/.secrets-ignore
  Packs/ApiModules/ReleaseNotes/2_0_0.md
  Packs/ApiModules/Scripts/GSuiteApiModule/GSuiteApiModule.py
  Packs/ApiModules/Scripts/GSuiteApiModule/GSuiteApiModule.yml
  Packs/ApiModules/Scripts/GSuiteApiModule/GSuiteApiModule_test.py
  Packs/ApiModules/Scripts/GSuiteApiModule/README.md
  Packs/ApiModules/Scripts/GSuiteApiModule/test_data/service_account_json.txt
  Packs/GSuiteAdmin/.pack-ignore
  Packs/GSuiteAdmin/.secrets-ignore
  Packs/GSuiteAdmin/Integrations/GSuiteAdmin/GSuiteAdmin.py
  Packs/GSuiteAdmin/Integrations/GSuiteAdmin/GSuiteAdmin.yml
  Packs/GSuiteAdmin/Integrations/GSuiteAdmin/GSuiteAdmin_description.md
  Packs/GSuiteAdmin/Integrations/GSuiteAdmin/GSuiteAdmin_image.png
  Packs/GSuiteAdmin/Integrations/GSuiteAdmin/GSuiteAdmin_test.py
  Packs/GSuiteAdmin/Integrations/GSuiteAdmin/Pipfile
  Packs/GSuiteAdmin/Integrations/GSuiteAdmin/Pipfile.lock
  Packs/GSuiteAdmin/Integrations/GSuiteAdmin/README.md
  Packs/GSuiteAdmin/Integrations/GSuiteAdmin/test_data/custom_user_schema_create_entry_context.json
  Packs/GSuiteAdmin/Integrations/GSuiteAdmin/test_data/custom_user_schema_response.json
  Packs/GSuiteAdmin/Integrations/GSuiteAdmin/test_data/custom_user_schema_update_entry_context.json
  Packs/GSuiteAdmin/Integrations/GSuiteAdmin/test_data/data_transfer_request_create_test_data.json
  Packs/GSuiteAdmin/Integrations/GSuiteAdmin/test_data/datatransfer_list_entry_context.json
  Packs/GSuiteAdmin/Integrations/GSuiteAdmin/test_data/datatransfer_list_response.json
  Packs/GSuiteAdmin/Integrations/GSuiteAdmin/test_data/group_create_test_data.json
  Packs/GSuiteAdmin/Integrations/GSuiteAdmin/test_data/role_assignment_create_entry_context.json
  Packs/GSuiteAdmin/Integrations/GSuiteAdmin/test_data/role_assignment_create_response.json
  Packs/GSuiteAdmin/Integrations/GSuiteAdmin/test_data/role_assignment_list_entry_context.json
  Packs/GSuiteAdmin/Integrations/GSuiteAdmin/test_data/role_assignment_list_response.json
  Packs/GSuiteAdmin/Integrations/GSuiteAdmin/test_data/role_create_test_data.json
  Packs/GSuiteAdmin/Integrations/GSuiteAdmin/test_data/service_account_json.txt
  Packs/GSuiteAdmin/Integrations/GSuiteAdmin/test_data/user_alias_add.json
  Packs/GSuiteAdmin/Integrations/GSuiteAdmin/test_data/user_create_args.json
  Packs/GSuiteAdmin/Integrations/GSuiteAdmin/test_data/user_create_entry_context.json
  Packs/GSuiteAdmin/Integrations/GSuiteAdmin/test_data/user_create_response.json
  Packs/GSuiteAdmin/Integrations/GSuiteAdmin/test_data/user_update_entry_context.json
  Packs/GSuiteAdmin/Integrations/GSuiteAdmin/test_data/user_update_response.json
  Packs/GSuiteAdmin/README.md
  Packs/GSuiteAdmin/TestPlaybooks/playbook-GSuiteAdmin-Test.yml
  Packs/GSuiteAdmin/doc_files/add-scope-admin-1.png
  Packs/GSuiteAdmin/doc_files/add-scope-admin-2.png
  Packs/GSuiteAdmin/doc_files/add-scope-admin-3.png
  Packs/GSuiteAdmin/doc_files/create-project-1.png
  Packs/GSuiteAdmin/doc_files/enable-api.jpg
  Packs/GSuiteAdmin/doc_files/enable-gke-api-enable-2.png
  Packs/GSuiteAdmin/doc_files/google-api-menu.png
  Packs/GSuiteAdmin/doc_files/service-account-create-1.png
  Packs/GSuiteAdmin/doc_files/service-account-create-3.png
  Packs/GSuiteAdmin/doc_files/service-account-create-4.png
  Packs/GSuiteAdmin/doc_files/service-acount-menu.png
  Packs/GSuiteAdmin/pack_metadata.json
  Tests/conf.json
Labels: docs-approved

#9865 SentinelOne SHA1 hash description
  Packs/SentinelOne/Integrations/SentinelOne-V2/README.md
  Packs/SentinelOne/Integrations/SentinelOne-V2/SentinelOne-V2.yml
  Packs/SentinelOne/ReleaseNotes/1_0_4.md
  Packs/SentinelOne/pack_metadata.json
Labels: docs-approved

#9868 removed fetch from test-module
  Packs/Gmail/Integrations/Gmail/Gmail.py
  Packs/Gmail/ReleaseNotes/1_1_1.md
  Packs/Gmail/pack_metadata.json
Labels: bug, docs-approved, release-notes-only

#9842 CrowdStrike Falcon Streaming v2 - update client headers with auth header and add log prints
  Packs/CrowdStrikeFalconStreamingV2/Integrations/CrowdStrikeFalconStreamingV2/CrowdStrikeFalconStreamingV2.py
  Packs/CrowdStrikeFalconStreamingV2/ReleaseNotes/1_0_11.md
  Packs/CrowdStrikeFalconStreamingV2/pack_metadata.json
Labels: docs-approved, release-notes-only

#9818 McAfee Advanced Threat defense - fixed an issue !atd-file-upload submitType 2 and 3 were not supported
  Packs/McAfee_Advanced_Threat_Defense/Integrations/McAfee_Advanced_Threat_Defense/McAfee_Advanced_Threat_Defense.py
  Packs/McAfee_Advanced_Threat_Defense/Integrations/McAfee_Advanced_Threat_Defense/McAfee_Advanced_Threat_Defense.yml
  Packs/McAfee_Advanced_Threat_Defense/Integrations/McAfee_Advanced_Threat_Defense/McAfee_Advanced_Threat_Defense_test.py
  Packs/McAfee_Advanced_Threat_Defense/Playbooks/playbook-Detonate_Remote_File_from_URL_-_McAfee_ATD.yml
  Packs/McAfee_Advanced_Threat_Defense/Playbooks/playbook-Detonate_Remote_File_from_URL_-_McAfee_ATD_README.md
  Packs/McAfee_Advanced_Threat_Defense/ReleaseNotes/1_0_2.md
  Packs/McAfee_Advanced_Threat_Defense/TestPlaybooks/Detonate_Remote_File_From_URL_-McAfee-ATD_-_Test.yml
  Packs/McAfee_Advanced_Threat_Defense/pack_metadata.json
  Tests/conf.json
Labels: docs-approved, release-notes-only

#9876 removed from skipped
  Tests/conf.json
Labels: docs-approved

#9077 MongoDB - fields argument for query command
  Packs/MongoDB/Integrations/MongoDB/MongoDB.py
  Packs/MongoDB/Integrations/MongoDB/MongoDB.yml
  Packs/MongoDB/ReleaseNotes/1_2_0.md
  Packs/MongoDB/TestPlaybooks/playbook-MongoDBTest.yml
  Packs/MongoDB/pack_metadata.json
Labels: docs-approved

#9877 McAfee-ATD removed from skipped tests
  Tests/conf.json
Labels: docs-approved

#9480 Onion URL Reputation Script
  Packs/CommonScripts/.secrets-ignore
  Packs/CommonScripts/ReleaseNotes/1_2_75.md
  Packs/CommonScripts/Scripts/OnionURLReputation/OnionURLReputation.py
  Packs/CommonScripts/Scripts/OnionURLReputation/OnionURLReputation.yml
  Packs/CommonScripts/Scripts/OnionURLReputation/OnionURLReputation_test.py
  Packs/CommonScripts/Scripts/OnionURLReputation/README.md
  Packs/CommonScripts/pack_metadata.json
Labels: docs-approved

#9875 fixed gmail fetch
  Packs/Gmail/Integrations/Gmail/Gmail.py
  Packs/Gmail/ReleaseNotes/1_1_1.md
  Packs/Gmail/pack_metadata.json
Labels: docs-approved

#9698 [Enhancement] CVESearchV2 - reputation commands to return a list of results
  Packs/CVESearch/Integrations/CVESearchV2/CVESearchV2.py
  Packs/CVESearch/Integrations/CVESearchV2/CVESearchV2.yml
  Packs/CVESearch/ReleaseNotes/1_0_3.md
  Packs/CVESearch/Scripts/script-CveReputation.yml
  Packs/CVESearch/TestPlaybooks/playbook-CVE-Search-Test.yml
  Packs/CVESearch/pack_metadata.json
  Tests/conf.json
Labels: docs-approved, release-notes-only

#9879 VT private - empty behaviour report
  Packs/VirusTotal-Private_API/Integrations/VirusTotal-Private_API/VirusTotal-Private_API.py
  Packs/VirusTotal-Private_API/Integrations/VirusTotal-Private_API/VirusTotal-Private_API_test.py
  Packs/VirusTotal-Private_API/ReleaseNotes/1_0_6.md
  Packs/VirusTotal-Private_API/pack_metadata.json
Labels: docs-approved, release-notes-only

#9870 Jira V2 - Fixed an issue where command reporter field in *jira-create-issue* was wrong
  Packs/Jira/Integrations/JiraV2/JiraV2.py
  Packs/Jira/Integrations/JiraV2/JiraV2.yml
  Packs/Jira/Integrations/JiraV2/README.md
  Packs/Jira/ReleaseNotes/1_2_1.md
  Packs/Jira/TestPlaybooks/playbook-Jira-v2-Test.yml
  Packs/Jira/pack_metadata.json
Labels: docs-approved, release-notes-only

#9880 Fix for private packs not added to index
  Tests/Marketplace/upload_packs.py
Labels: docs-approved

#9813 domain tools iris support for https
  Packs/DomainTools_Iris/Integrations/DomainTools_Iris/DomainTools_Iris.py
  Packs/DomainTools_Iris/Integrations/DomainTools_Iris/DomainTools_Iris.yml
  Packs/DomainTools_Iris/ReleaseNotes/1_0_4.md
  Packs/DomainTools_Iris/pack_metadata.json
Labels: docs-approved, release-notes-only

#9669 Anomali ThreatStream v2 get-indicators limitation bug
  Packs/Anomali_ThreatStream/Integrations/Anomali_ThreatStream_v2/Anomali_ThreatStream_v2.py
  Packs/Anomali_ThreatStream/ReleaseNotes/1_0_7.md
  Packs/Anomali_ThreatStream/pack_metadata.json
Labels: docs-approved, release-notes-only

#9866 [Enhancement] PassiveTotalV2 - reputation command to return a list of results
  Packs/PassiveTotal/Integrations/PassiveTotal_v2/PassiveTotal_v2.py
  Packs/PassiveTotal/Integrations/PassiveTotal_v2/PassiveTotal_v2.yml
  Packs/PassiveTotal/Integrations/PassiveTotal_v2/PassiveTotal_v2_test.py
  Packs/PassiveTotal/Integrations/PassiveTotal_v2/test_data/HostAttribute/Component/component_domain_hr.md
  Packs/PassiveTotal/Integrations/PassiveTotal_v2/test_data/HostAttribute/Component/component_ec.json
  Packs/PassiveTotal/Integrations/PassiveTotal_v2/test_data/HostAttribute/Component/component_ip_hr.md
  Packs/PassiveTotal/Integrations/PassiveTotal_v2/test_data/HostAttribute/Component/component_resp.json
  Packs/PassiveTotal/Integrations/PassiveTotal_v2/test_data/HostAttribute/Host_Pair/host_pair_ec.json
  Packs/PassiveTotal/Integrations/PassiveTotal_v2/test_data/HostAttribute/Host_Pair/host_pair_hr.md
  Packs/PassiveTotal/Integrations/PassiveTotal_v2/test_data/HostAttribute/Host_Pair/host_pair_resp.json
  Packs/PassiveTotal/Integrations/PassiveTotal_v2/test_data/HostAttribute/Tracker/tracker_domain_hr.md
  Packs/PassiveTotal/Integrations/PassiveTotal_v2/test_data/HostAttribute/Tracker/tracker_ec.json
  Packs/PassiveTotal/Integrations/PassiveTotal_v2/test_data/HostAttribute/Tracker/tracker_ip_hr.md
  Packs/PassiveTotal/Integrations/PassiveTotal_v2/test_data/HostAttribute/Tracker/tracker_resp.json
  Packs/PassiveTotal/Integrations/PassiveTotal_v2/test_data/PDNS/get_pdns_ec.json
  Packs/PassiveTotal/Integrations/PassiveTotal_v2/test_data/PDNS/get_pdns_hr.md
  Packs/PassiveTotal/Integrations/PassiveTotal_v2/test_data/PDNS/get_pdns_resp.json
  Packs/PassiveTotal/Integrations/PassiveTotal_v2/test_data/SSL/ssl_cert_ec.json
  Packs/PassiveTotal/Integrations/PassiveTotal_v2/test_data/SSL/ssl_cert_hr.md
  Packs/PassiveTotal/Integrations/PassiveTotal_v2/test_data/SSL/ssl_cert_resp.json
  Packs/PassiveTotal/Integrations/PassiveTotal_v2/test_data/domain_reputatoin/domain_reputatoin_command_readable_output.md
  Packs/PassiveTotal/Integrations/PassiveTotal_v2/test_data/domain_reputatoin/domain_reputatoin_context.json
  Packs/PassiveTotal/Integrations/PassiveTotal_v2/test_data/domain_reputatoin/domain_reputatoin_response.json
  Packs/PassiveTotal/Integrations/PassiveTotal_v2/test_data/whois_command/whois_command_readable_output.md
  Packs/PassiveTotal/Integrations/PassiveTotal_v2/test_data/whois_command/whois_command_response.json
  Packs/PassiveTotal/Integrations/PassiveTotal_v2/test_data/whois_command/whois_command_standard_domain_readable_output.md
  Packs/PassiveTotal/Integrations/PassiveTotal_v2/test_data/whois_command/whois_custom_context.json
  Packs/PassiveTotal/ReleaseNotes/2_0_5.md
  Packs/PassiveTotal/pack_metadata.json
Labels: docs-approved, release-notes-only

#9601 Update cisco-ise.py
  Packs/cisco-ise/Integrations/cisco-ise/cisco-ise.py
  Packs/cisco-ise/Integrations/cisco-ise/cisco-ise.yml
  Packs/cisco-ise/ReleaseNotes/1_0_1.md
  Packs/cisco-ise/pack_metadata.json
Labels: Contribution, ready-for-instance-test

#9893 autofocus doc: fix formatting (missing new line)
  Packs/AutoFocus/Integrations/FeedAutofocus/README.md
Labels: docs-approved

#9881 IBM X-Force Exchange v2 file 404 and isarray fixes
  Packs/XForceExchange/Integrations/XFE_v2/XFE_v2.py
  Packs/XForceExchange/ReleaseNotes/1_0_5.md
  Packs/XForceExchange/TestPlaybooks/playbook-Test_XFE_v2.yml
  Packs/XForceExchange/pack_metadata.json
Labels: docs-approved, release-notes-only

#8396 F5 Firewall v2
  Packs/F5/Integrations/f5_ASM/README.md
  Packs/F5/Integrations/f5_ASM/command_example.txt
  Packs/F5/Integrations/f5_ASM/f5_ASM.py
  Packs/F5/Integrations/f5_ASM/f5_ASM.yml
  Packs/F5/Integrations/f5_ASM/f5_ASM_description.md
  Packs/F5/Integrations/f5_ASM/f5_ASM_image.png
  Packs/F5/Integrations/f5_ASM/f5_ASM_test.py
  Packs/F5/Integrations/f5_ASM/test_data/CUD_GWT.json
  Packs/F5/Integrations/f5_ASM/test_data/CUD_json_profile.json
  Packs/F5/Integrations/f5_ASM/test_data/CUD_parameters.json
  Packs/F5/Integrations/f5_ASM/test_data/CUD_whitelist.json
  Packs/F5/Integrations/f5_ASM/test_data/CUD_xml_profile.json
  Packs/F5/Integrations/f5_ASM/test_data/add_cookie.json
  Packs/F5/Integrations/f5_ASM/test_data/add_delete_server_technology.json
  Packs/F5/Integrations/f5_ASM/test_data/add_file_type.json
  Packs/F5/Integrations/f5_ASM/test_data/add_hostname.json
  Packs/F5/Integrations/f5_ASM/test_data/add_methods.json
  Packs/F5/Integrations/f5_ASM/test_data/add_url.json
  Packs/F5/Integrations/f5_ASM/test_data/apply_policy.json
  Packs/F5/Integrations/f5_ASM/test_data/create_policy.json
  Packs/F5/Integrations/f5_ASM/test_data/delete_cookie.json
  Packs/F5/Integrations/f5_ASM/test_data/delete_file_type.json
  Packs/F5/Integrations/f5_ASM/test_data/delete_hostname.json
  Packs/F5/Integrations/f5_ASM/test_data/delete_methods.json
  Packs/F5/Integrations/f5_ASM/test_data/delete_policy.json
  Packs/F5/Integrations/f5_ASM/test_data/delete_url.json
  Packs/F5/Integrations/f5_ASM/test_data/export_policy.json
  Packs/F5/Integrations/f5_ASM/test_data/get_md5.json
  Packs/F5/Integrations/f5_ASM/test_data/list_GWT.json
  Packs/F5/Integrations/f5_ASM/test_data/list_cookies.json
  Packs/F5/Integrations/f5_ASM/test_data/list_file_types.json
  Packs/F5/Integrations/f5_ASM/test_data/list_hostname.json
  Packs/F5/Integrations/f5_ASM/test_data/list_json_profiles.json
  Packs/F5/Integrations/f5_ASM/test_data/list_methods.json
  Packs/F5/Integrations/f5_ASM/test_data/list_parameters.json
  Packs/F5/Integrations/f5_ASM/test_data/list_policies.json
  Packs/F5/Integrations/f5_ASM/test_data/list_server_technologies.json
  Packs/F5/Integrations/f5_ASM/test_data/list_urls.json
  Packs/F5/Integrations/f5_ASM/test_data/list_whitelist.json
  Packs/F5/Integrations/f5_ASM/test_data/list_xml_profile.json
  Packs/F5/Integrations/f5_ASM/test_data/update_cookie.json
  Packs/F5/Integrations/f5_ASM/test_data/update_file_type.json
  Packs/F5/Integrations/f5_ASM/test_data/update_hostname.json
  Packs/F5/Integrations/f5_ASM/test_data/update_methods.json
  Packs/F5/Integrations/f5_ASM/test_data/update_url.json
  Packs/F5/ReleaseNotes/1_2_0.md
  Packs/F5/TestPlaybooks/playbook-F5_ASM-Test.yml
  Packs/F5/pack_metadata.json
  Tests/conf.json
Labels: Contribution, ready-for-instance-test

#9897 [Test] Fix CVE search test check
  Packs/CVESearch/TestPlaybooks/playbook-CVE-Search-Test.yml
Labels: docs-approved

#9898 Crowdstrike Falcon Intel Feed - Fixed a visual issue in the instance …
  Packs/FeedCrowdstrikeFalconIntel/Integrations/FeedCrowdstrikeFalconIntel/FeedCrowdstrikeFalconIntel.yml
  Packs/FeedCrowdstrikeFalconIntel/ReleaseNotes/1_0_3.md
  Packs/FeedCrowdstrikeFalconIntel/pack_metadata.json
Labels: docs-approved, release-notes-only

#9838 MCAS issue fixes
  Packs/MicrosoftCloudAppSecurity/Integrations/MicrosoftCloudAppSecurity/MicrosoftCloudAppSecurity.py
  Packs/MicrosoftCloudAppSecurity/Integrations/MicrosoftCloudAppSecurity/MicrosoftCloudAppSecurity_test.py
  Packs/MicrosoftCloudAppSecurity/ReleaseNotes/1_0_10.md
  Packs/MicrosoftCloudAppSecurity/pack_metadata.json
Labels: docs-approved, release-notes-only

#9862 Add support for ServiceNow query with multiple args
  Packs/ServiceNow/Integrations/ServiceNowv2/ServiceNowv2.py
  Packs/ServiceNow/Integrations/ServiceNowv2/ServiceNowv2_test.py
  Packs/ServiceNow/Integrations/ServiceNowv2/test_data/response_constants.py
  Packs/ServiceNow/ReleaseNotes/1_3_10.md
  Packs/ServiceNow/pack_metadata.json
Labels: bug, docs-approved, release-notes-only

#9867 added support for custom url address - crowdstrike
  Packs/ApiModules/ReleaseNotes/1_1_7.md
  Packs/ApiModules/Scripts/CrowdStrikeApiModule/CrowdStrikeApiModule.py
  Packs/ApiModules/Scripts/CrowdStrikeApiModule/CrowdStrikeApiModule.yml
  Packs/ApiModules/pack_metadata.json
  Packs/CrowdStrikeIntel/Integrations/CrowdStrikeFalconIntel_v2/CrowdStrikeFalconIntel_v2.yml
  Packs/CrowdStrikeIntel/Integrations/CrowdStrikeFalconIntel_v2/README.md
  Packs/CrowdStrikeIntel/ReleaseNotes/2_0_8.md
  Packs/CrowdStrikeIntel/pack_metadata.json
Labels: bug, docs-approved, release-notes-only

#9791 fix bug in parsing all file types in word files
  Packs/CommonScripts/ReleaseNotes/1_2_76.md
  Packs/CommonScripts/Scripts/ExtractIndicatorsFromWordFile/ExtractIndicatorsFromWordFile.py
  Packs/CommonScripts/Scripts/ExtractIndicatorsFromWordFile/ExtractIndicatorsFromWordFile.yml
  Packs/CommonScripts/pack_metadata.json
Labels: docs-approved, release-notes-only

#9884 Domain Email Bug
  Packs/Base/.secrets-ignore
  Packs/Base/TestPlaybooks/playbook-Indicators-reputation-.json-Test.yml
  Packs/CommonScripts/ReleaseNotes/1_2_77.md
  Packs/CommonScripts/Scripts/ExtractDomainAndFQDNFromUrlAndEmail/ExtractDomainAndFQDNFromUrlAndEmail.py
  Packs/CommonScripts/Scripts/ExtractDomainAndFQDNFromUrlAndEmail/ExtractDomainAndFQDNFromUrlAndEmail_test.py
  Packs/CommonScripts/pack_metadata.json
  Tests/conf.json
Labels: docs-approved, release-notes-only

#9783 Azure Sentinel doc
  Packs/AzureSentinel/Integrations/AzureSentinel/README.md
Labels: docs-approved

#9882 combined port scan + port scan Adjusted
  Packs/CortexXDR/Playbooks/Cortex_XDR_-_Port_Scan.yml
  Packs/CortexXDR/Playbooks/Cortex_XDR_-_Port_Scan_-_Adjusted.yml
  Packs/CortexXDR/Playbooks/Cortex_XDR_-_Port_Scan_-_Adjusted_README.md
  Packs/CortexXDR/ReleaseNotes/2_4_9.md
  Packs/CortexXDR/pack_metadata.json
Labels: docs-approved

#9871 IAM - CSP & Okta IAM return_error
  Packs/Base/ReleaseNotes/1_3_34.md
  Packs/Base/Scripts/CommonServerPython/CommonServerPython.py
  Packs/Base/pack_metadata.json
  Packs/Okta/Integrations/Okta_IAM/Okta_IAM.py
  Packs/Okta/Integrations/Okta_IAM/Okta_IAM_test.py
  Packs/Okta/ReleaseNotes/2_0_1.md
  Packs/Okta/pack_metadata.json
Labels: docs-approved

#9913 PANW is enabled task
  Packs/PANWComprehensiveInvestigation/Playbooks/Palo_Alto_Networks_-_Hunting_And_Threat_Detection.yml
  Packs/PANWComprehensiveInvestigation/ReleaseNotes/1_3_3.md
  Packs/PANWComprehensiveInvestigation/pack_metadata.json
Labels: docs-approved

#9917 bump content version
  .circleci/config.yml
Labels: docs-approved

#9901 Fix for collecting dependencies in private build
  Tests/Marketplace/search_and_install_packs.py
  Tests/private_build/configure_and_test_integration_instances_private.py
Labels: docs-approved

#9902 destroy instances - server logs
  Tests/scripts/destroy_instances.py
Labels: docs-approved

#9755 IPv6 highlight issue
  Packs/CommonScripts/.secrets-ignore
  Packs/CommonScripts/ReleaseNotes/1_2_78.md
  Packs/CommonScripts/Scripts/VerifyIPv6Indicator/VerifyIPv6Indicator.py
  Packs/CommonScripts/Scripts/VerifyIPv6Indicator/VerifyIPv6Indicator.yml
  Packs/CommonScripts/Scripts/VerifyIPv6Indicator/VerifyIPv6Indicator_test.py
  Packs/CommonScripts/Scripts/script-UnEscapeIndicatorIPv6.yml
  Packs/CommonScripts/pack_metadata.json
  Packs/CommonTypes/IndicatorTypes/reputation-ipv6.json
  Packs/CommonTypes/ReleaseNotes/2_2_2.md
  Packs/CommonTypes/pack_metadata.json
Labels: docs-approved

#9921 Prepare content packs for testing - Fail
  Tests/Marketplace/upload_packs.py
Labels: docs-approved

#9910 update token retrieval logic CS falcon
  Packs/CrowdStrikeFalcon/Integrations/CrowdStrikeFalcon/CrowdStrikeFalcon.py
  Packs/CrowdStrikeFalcon/ReleaseNotes/1_2_7.md
  Packs/CrowdStrikeFalcon/pack_metadata.json
Labels: bug, docs-approved, release-notes-only

#9924 [Test-Fix] Test - CrowdStrike Falcon
  Packs/CrowdStrikeFalcon/TestPlaybooks/playbook-CrowdStrikeFalcon-Test.yml
Labels: docs-approved

#9815 filter compliance search results
  Packs/EWS/Integrations/EWSv2/EWSv2.py
  Packs/EWS/Integrations/EWSv2/EWSv2.yml
  Packs/EWS/ReleaseNotes/1_4_1.md
  Packs/EWS/pack_metadata.json
Labels: docs-approved

#9887 Support both uploads
  .circleci/config.yml
  Tests/Marketplace/marketplace_services.py
  Tests/Marketplace/upload_packs.py
  Tests/scripts/prepare_content_packs_for_testing.sh
  Utils/trigger_force_upload_pack_to_production.sh
Labels: docs-approved

#9903 [Enhancement] Panorama - reputation command to return a list of results
  Packs/PAN-OS/Integrations/Panorama/Panorama.py
  Packs/PAN-OS/Integrations/Panorama/Panorama_test.py
  Packs/PAN-OS/ReleaseNotes/1_6_5.md
  Packs/PAN-OS/pack_metadata.json
Labels: docs-approved, release-notes-only

#9722 [Enhancement] CrowdStrikeMalquery - reputation command to return a list of results
  Packs/CrowdStrikeMalquery/Integrations/CrowdStrikeMalquery/CrowdStrikeMalquery.py
  Packs/CrowdStrikeMalquery/Integrations/CrowdStrikeMalquery/CrowdStrikeMalquery.yml
  Packs/CrowdStrikeMalquery/Integrations/CrowdStrikeMalquery/CrowdStrikeMalquery_test.py
  Packs/CrowdStrikeMalquery/ReleaseNotes/1_0_1.md
  Packs/CrowdStrikeMalquery/pack_metadata.json
  Tests/conf.json
Labels: docs-approved, release-notes-only

#9566 upload to production bucket build flow
  .circleci/build-requirements.txt
  .circleci/config.yml
  Tests/Marketplace/Tests/copy_and_upload_packs_test.py
  Tests/Marketplace/Tests/marketplace_services_test.py
  Tests/Marketplace/Tests/upload_packs_test.py
  Tests/Marketplace/configure_and_install_packs.py
  Tests/Marketplace/copy_and_upload_packs.py
  Tests/Marketplace/install_packs.sh
  Tests/Marketplace/marketplace_services.py
  Tests/Marketplace/normalize_gcs_paths.py
  Tests/Marketplace/upload_packs.py
  Tests/private_build/upload_packs_private.py
  Tests/scripts/infrastructure_tests/release_notes_generator_test.py
  Tests/scripts/prepare_content_packs_for_testing.sh
  Tests/scripts/should_lint_all.sh
  Tests/scripts/slack_notifier.py
  Tests/scripts/slack_notifier.sh
  Tests/scripts/validate.sh
  Utils/release_notes_generator.py
  Utils/trigger_upload_packs_to_production.sh
Labels: docs-approved

#9900 CommonServerPython - remove context log
  Packs/Base/ReleaseNotes/1_3_35.md
  Packs/Base/Scripts/CommonServerPython/CommonServerPython.py
  Packs/Base/pack_metadata.json
Labels: docs-approved, release-notes-only

#9765 PALO ALTO NETWORKS threat vault
  Packs/PaloAltoNetworks_Threat_Vault/.pack-ignore
  Packs/PaloAltoNetworks_Threat_Vault/.secrets-ignore
  Packs/PaloAltoNetworks_Threat_Vault/Integrations/Threat_Vault/Pipfile
  Packs/PaloAltoNetworks_Threat_Vault/Integrations/Threat_Vault/Pipfile.lock
  Packs/PaloAltoNetworks_Threat_Vault/Integrations/Threat_Vault/README.md
  Packs/PaloAltoNetworks_Threat_Vault/Integrations/Threat_Vault/Threat_Vault.py
  Packs/PaloAltoNetworks_Threat_Vault/Integrations/Threat_Vault/Threat_Vault.yml
  Packs/PaloAltoNetworks_Threat_Vault/Integrations/Threat_Vault/Threat_Vault_description.md
  Packs/PaloAltoNetworks_Threat_Vault/Integrations/Threat_Vault/Threat_Vault_image.png
  Packs/PaloAltoNetworks_Threat_Vault/Integrations/Threat_Vault/Threat_Vault_test.py
  Packs/PaloAltoNetworks_Threat_Vault/Integrations/Threat_Vault/examples.txt
  Packs/PaloAltoNetworks_Threat_Vault/Playbooks/Threat_Vault_-_Signature_Search.yml
  Packs/PaloAltoNetworks_Threat_Vault/Playbooks/Threat_Vault_-_Signature_Search_README.md
  Packs/PaloAltoNetworks_Threat_Vault/README.md
  Packs/PaloAltoNetworks_Threat_Vault/TestPlaybooks/Threat_Vault_-_Signature_Search-Test.yml
  Packs/PaloAltoNetworks_Threat_Vault/pack_metadata.json
  Tests/conf.json
Labels: docs-approved

#9906 Vxstream (Crowdstrike Falcon Sandbox) - fixed an issue where crowdstrike-results was not work with only jobID
  Packs/CrowdStrikeFalconSandbox/Integrations/integration-CrowdStrikeFalconSandbox.yml
  Packs/CrowdStrikeFalconSandbox/ReleaseNotes/1_0_2.md
  Packs/CrowdStrikeFalconSandbox/TestPlaybooks/playbook-VxStream_Test.yml
  Packs/CrowdStrikeFalconSandbox/pack_metadata.json
Labels: docs-approved, release-notes-only

#9935 CrowdStrike Falcon Streaming v2 - add note about turning off events storage after mapping to tooltip
  Packs/CrowdStrikeFalconStreamingV2/Integrations/CrowdStrikeFalconStreamingV2/CrowdStrikeFalconStreamingV2.yml
  Packs/CrowdStrikeFalconStreamingV2/ReleaseNotes/1_0_12.md
  Packs/CrowdStrikeFalconStreamingV2/pack_metadata.json
Labels: docs-approved

#9940 nightly-fix
  .circleci/config.yml
  Tests/scripts/prepare_content_packs_for_testing.sh
Labels: docs-approved

#9942 bucket upload flow schedule change
  .circleci/config.yml
Labels: docs-approved

#9922 Separated the installation step from the playbook tests step
  .circleci/config.yml
  Tests/scripts/install_content_and_test_integrations.sh
  Tests/scripts/run_tests.sh
Labels: docs-approved

#9941 release 1-2-9
  dev-requirements-py3.txt
Labels: docs-approved

#9894 Searchincidentsv2fix
  Packs/CommonScripts/ReleaseNotes/1_2_79.md
  Packs/CommonScripts/Scripts/SearchIncidentsV2/SearchIncidentsV2.py
  Packs/CommonScripts/Scripts/SearchIncidentsV2/SearchIncidentsV2.yml
  Packs/CommonScripts/TestPlaybooks/playbook-SearchIncidentsV2InsideGenericPollng-Test.yml
  Packs/CommonScripts/pack_metadata.json
  Packs/Syslog/TestPlaybooks/playbook-Syslog_Test.yml
  Packs/Syslog/TestPlaybooks/script-GetServerURL_syslog.yml
Labels: bug, docs-approved, release-notes-only

#9947 Return once finished installing nightly packs
  Tests/Marketplace/search_and_install_packs.py
Labels: docs-approved

#9928 Symantec DLP - skip last fetched ID
  Packs/SymantecDLP/Integrations/SymantecDLP/SymantecDLP.py
  Packs/SymantecDLP/ReleaseNotes/1_1_1.md
  Packs/SymantecDLP/pack_metadata.json
Labels: docs-approved, release-notes-only

#9931 fix layout for 6.0.1 sdk nightly
  .circleci/config.yml
  Tests/sdknightly/create_entities_for_nightly_sdk.py
Labels: docs-approved

#9936 Microsoft Management Activity - Fixed bug with audit.general usage
  Packs/MicrosoftManagementActivity/Integrations/MicrosoftManagementActivity/MicrosoftManagementActivity.yml
  Packs/MicrosoftManagementActivity/ReleaseNotes/1_1_3.md
  Packs/MicrosoftManagementActivity/pack_metadata.json
Labels: docs-approved, release-notes-only

#9833 fixed cdl fetch duplicate incidents
  Packs/CortexDataLake/Integrations/CortexDataLake/CortexDataLake.py
  Packs/CortexDataLake/Integrations/CortexDataLake/CortexDataLake.yml
  Packs/CortexDataLake/Integrations/CortexDataLake/CortexDataLake_test.py
  Packs/CortexDataLake/ReleaseNotes/1_2_8.md
  Packs/CortexDataLake/pack_metadata.json
Labels: bug, docs-approved, release-notes-only

#9915 GetFailedTasks-add account arg
  Packs/IntegrationsAndIncidentsHealthCheck/ReleaseNotes/1_1_6.md
  Packs/IntegrationsAndIncidentsHealthCheck/Scripts/GetFailedTasks/GetFailedTasks.py
  Packs/IntegrationsAndIncidentsHealthCheck/Scripts/GetFailedTasks/GetFailedTasks.yml
  Packs/IntegrationsAndIncidentsHealthCheck/Scripts/GetFailedTasks/GetFailedTasks_test.py
  Packs/IntegrationsAndIncidentsHealthCheck/Scripts/GetFailedTasks/README.md
  Packs/IntegrationsAndIncidentsHealthCheck/Scripts/GetFailedTasks/test_data/constants.py
  Packs/IntegrationsAndIncidentsHealthCheck/pack_metadata.json
  Tests/demistomock/demistomock.py
Labels: bug, docs-approved, release-notes-only

#9958 Contrib/fvigo add ignoreautoextract to commandresults
  Packs/Base/ReleaseNotes/1_3_36.md
  Packs/Base/Scripts/CommonServerPython/CommonServerPython.py
  Packs/Base/Scripts/CommonServerPython/CommonServerPython_test.py
  Packs/Base/pack_metadata.json
  Packs/BmcHelixRemedyForce/Integrations/BmcHelixRemedyForce/TestData/get_queue_details_return_entry.json
  Packs/BmcHelixRemedyForce/Integrations/BmcHelixRemedyForce/TestData/get_user_details_return_entry.json
  Packs/Polygon/Integrations/Polygon/test_data/results.json
  Packs/SecurityIntelligenceServicesFeed/Integrations/SecurityIntelligenceServicesFeed/SecurityIntelligenceServicesFeed_test.py
Labels: docs-approved

#9780 Approved tags and usecases and clean up existing metadata
  .github/CODEOWNERS
  Packs/BastilleNetworks/ReleaseNotes/1_0_2.md
  Packs/BastilleNetworks/pack_metadata.json
  Packs/Bonusly/ReleaseNotes/1_0_1.md
  Packs/Bonusly/pack_metadata.json
  Packs/CaseManagement-Generic/ReleaseNotes/1_1_1.md
  Packs/CaseManagement-Generic/pack_metadata.json
  Packs/CiscoASA/ReleaseNotes/1_0_2.md
  Packs/CiscoASA/pack_metadata.json
  Packs/Code42/ReleaseNotes/2_0_7.md
  Packs/Code42/pack_metadata.json
  Packs/Coralogix/ReleaseNotes/1_0_2.md
  Packs/Coralogix/pack_metadata.json
  Packs/CortexXDR/ReleaseNotes/2_4_10.md
  Packs/CortexXDR/pack_metadata.json
  Packs/CyberTotal/ReleaseNotes/1_0_3.md
  Packs/CyberTotal/pack_metadata.json
  Packs/DNSDB/ReleaseNotes/2_1_1.md
  Packs/DNSDB/pack_metadata.json
  Packs/Humio/ReleaseNotes/1_0_2.md
  Packs/Humio/pack_metadata.json
  Packs/IntegrationsAndIncidentsHealthCheck/ReleaseNotes/1_1_7.md
  Packs/IntegrationsAndIncidentsHealthCheck/pack_metadata.json
  Packs/Jira/ReleaseNotes/1_2_2.md
  Packs/Jira/pack_metadata.json
  Packs/Logzio/ReleaseNotes/1_1_1.md
  Packs/Logzio/pack_metadata.json
  Packs/NTT_Cyber_Threat_Sensor/ReleaseNotes/1_0_1.md
  Packs/NTT_Cyber_Threat_Sensor/pack_metadata.json
  Packs/NozomiNetworks/ReleaseNotes/1_0_1.md
  Packs/NozomiNetworks/pack_metadata.json
  Packs/PaloAltoNetworks_IoT/ReleaseNotes/1_0_1.md
  Packs/PaloAltoNetworks_IoT/pack_metadata.json
  Packs/QueryAI/ReleaseNotes/1_0_3.md
  Packs/QueryAI/pack_metadata.json
  Packs/SafeBreach/ReleaseNotes/1_1_2.md
  Packs/SafeBreach/pack_metadata.json
  Packs/ServiceNow/ReleaseNotes/1_3_11.md
  Packs/ServiceNow/pack_metadata.json
  Packs/XSOARmirroring/ReleaseNotes/1_0_1.md
  Packs/XSOARmirroring/pack_metadata.json
  Tests/Marketplace/approved_tags.json
  Tests/Marketplace/approved_usecases.json
Labels: docs-approved

#9961 skip Forcepoint integration
  Tests/conf.json
Labels: docs-approved

#9923 changing bucket name
  Tests/private_build/upload_packs_private.py
Labels: docs-approved

#9828 Added incremental fetch to AlienVaultOTX feed
  Packs/FeedAlienVault/Integrations/FeedAlienVaultOTXTaxii/FeedAlienVaultOTXTaxii.py
  Packs/FeedAlienVault/Integrations/FeedAlienVaultOTXTaxii/FeedAlienVaultOTXTaxii.yml
  Packs/FeedAlienVault/Integrations/FeedAlienVaultOTXTaxii/FeedAlienVaultOTXTaxii_test.py
  Packs/FeedAlienVault/ReleaseNotes/1_0_7.md
  Packs/FeedAlienVault/TestPlaybooks/playbook-feedalienvaultotx_test.yml
  Packs/FeedAlienVault/pack_metadata.json
Labels: bug, docs-approved

#9959 Microsoft Teams - modify API query to filter user by given entity
  Packs/MicrosoftTeams/Integrations/MicrosoftTeams/MicrosoftTeams.py
  Packs/MicrosoftTeams/Integrations/MicrosoftTeams/MicrosoftTeams.yml
  Packs/MicrosoftTeams/ReleaseNotes/1_0_5.md
  Packs/MicrosoftTeams/pack_metadata.json
Labels: bug, docs-approved, release-notes-only
