Repository demisto/content, pull requests merged in 2020-10, with the labels that each got.

#9025 Fix xfe test playbook v2
  Packs/XFE/.pack-ignore
  Packs/XFE/.secrets-ignore
  Packs/XFE/README.md
  Packs/XFE/TestPlaybooks/playbook-XFE_Playbook_Test.yml
  Packs/XFE/pack_metadata.json
  Packs/XForceExchange/Integrations/integration-XFE.yml
  Packs/XForceExchange/ReleaseNotes/1_0_2.md
  Packs/XForceExchange/TestPlaybooks/playbook-Test_XFE_v2.yml
  Packs/XForceExchange/pack_metadata.json
  Tests/conf.json
Labels: docs-approved, release-notes-only

#9149 Microsoft CAS - Fix bug in fetch incidents
  Packs/MicrosoftCloudAppSecurity/Integrations/MicrosoftCloudAppSecurity/MicrosoftCloudAppSecurity.py
  Packs/MicrosoftCloudAppSecurity/Integrations/MicrosoftCloudAppSecurity/MicrosoftCloudAppSecurity.yml
  Packs/MicrosoftCloudAppSecurity/ReleaseNotes/1_0_4.md
  Packs/MicrosoftCloudAppSecurity/pack_metadata.json
Labels: bug, docs-approved, release-notes-only

#9136 Fix several minor typos
  Packs/Active_Directory_Query/Integrations/Active_Directory_Query/Active_Directory_Query.py
  Packs/Active_Directory_Query/Integrations/Active_Directory_Query/Active_Directory_Query.yml
  Packs/Active_Directory_Query/ReleaseNotes/1_0_5.md
  Packs/Active_Directory_Query/pack_metadata.json
  Packs/Twilio/Integrations/integration-Twilio.yml
  Packs/Twilio/ReleaseNotes/1_0_1.md
  Packs/Twilio/pack_metadata.json
  Tests/timestamp_replacer.py
  Tests/update_content_data.py
Labels: Contribution, docs-approved

#9242 bump release version
  .circleci/config.yml
Labels: docs-approved

#9064 Microsoft cas bug
  Packs/MicrosoftCloudAppSecurity/Integrations/MicrosoftCloudAppSecurity/MicrosoftCloudAppSecurity.py
  Packs/MicrosoftCloudAppSecurity/Integrations/MicrosoftCloudAppSecurity/MicrosoftCloudAppSecurity_test.py
  Packs/MicrosoftCloudAppSecurity/ReleaseNotes/1_0_5.md
  Packs/MicrosoftCloudAppSecurity/pack_metadata.json
Labels: docs-approved, release-notes-only

#8999 Field polling - new PR
  Packs/CommonPlaybooks/Playbooks/playbook-Field_Polling.yml
  Packs/CommonPlaybooks/Playbooks/playbook-Field_Polling_README.md
  Packs/CommonPlaybooks/ReleaseNotes/1_8_2.md
  Packs/CommonPlaybooks/TestPlaybooks/playbook-fieldpolling-test.yml
  Packs/CommonPlaybooks/doc_files/playbook-Field_Polling.png
  Packs/CommonPlaybooks/pack_metadata.json
  Packs/CommonScripts/ReleaseNotes/1_2_50.md
  Packs/CommonScripts/Scripts/CheckFieldValue/CheckFieldValue.py
  Packs/CommonScripts/Scripts/CheckFieldValue/CheckFieldValue.yml
  Packs/CommonScripts/Scripts/CheckFieldValue/CheckFieldValue_test.py
  Packs/CommonScripts/Scripts/CheckFieldValue/Pipfile
  Packs/CommonScripts/Scripts/CheckFieldValue/Pipfile.lock
  Packs/CommonScripts/Scripts/CheckFieldValue/README.md
  Packs/CommonScripts/pack_metadata.json
  Tests/conf.json
Labels: docs-approved

#9247 Fixing call to proxy.stop without thread_index and prints_manager
  Tests/mock_server.py
Labels: docs-approved

#8917 Microsoft SCCM integration
  Packs/MicrosoftECM/.pack-ignore
  Packs/MicrosoftECM/.secrets-ignore
  Packs/MicrosoftECM/Integrations/MicrosoftECM/MicrosoftECM.Tests.ps1
  Packs/MicrosoftECM/Integrations/MicrosoftECM/MicrosoftECM.ps1
  Packs/MicrosoftECM/Integrations/MicrosoftECM/MicrosoftECM.yml
  Packs/MicrosoftECM/Integrations/MicrosoftECM/MicrosoftECM_description.md
  Packs/MicrosoftECM/Integrations/MicrosoftECM/MicrosoftECM_image.png
  Packs/MicrosoftECM/Integrations/MicrosoftECM/README.md
  Packs/MicrosoftECM/README.md
  Packs/MicrosoftECM/TestPlaybooks/MicrosoftECM_Test.yml
  Packs/MicrosoftECM/commands.txt
  Packs/MicrosoftECM/pack_metadata.json
  Tests/conf.json
Labels: docs-approved

#9241 add remote docker to nightly run
  .circleci/config.yml
Labels: docs-approved, release-notes-only

#9252 add release notes
  Packs/XForceExchange/Integrations/integration-XFE.yml
  Packs/XForceExchange/ReleaseNotes/1_0_3.md
  Packs/XForceExchange/pack_metadata.json
Labels: docs-approved

#9224 Form in template
  .github/pull_request_template.md
  Tests/secrets_white_list.json
Labels: docs-approved

#9067 Long sleep xsoar fix
  Packs/AutoFocus/Integrations/FeedAutofocus/FeedAutofocus.py
  Packs/AutoFocus/Integrations/FeedAutofocus/FeedAutofocus.yml
  Packs/AutoFocus/ReleaseNotes/1_1_4.md
  Packs/AutoFocus/pack_metadata.json
  Packs/FireEyeHX/Integrations/FireEyeHX/FireEyeHX.py
  Packs/FireEyeHX/ReleaseNotes/1_0_4.md
  Packs/FireEyeHX/pack_metadata.json
  Packs/McAfee_ESM-v10/Integrations/McAfee_ESM-v10/McAfee_ESM-v10.py
  Packs/McAfee_ESM-v10/ReleaseNotes/1_0_5.md
  Packs/McAfee_ESM-v10/pack_metadata.json
  Packs/McAfee_ESM/Integrations/McAfee_ESM_v2/McAfee_ESM_v2.py
  Packs/McAfee_ESM/Integrations/McAfee_ESM_v2/McAfee_ESM_v2.yml
  Packs/McAfee_ESM/ReleaseNotes/1_1_1.md
  Packs/McAfee_ESM/pack_metadata.json
  Packs/PolySwarm/Integrations/PolySwarm/PolySwarm.py
  Packs/PolySwarm/ReleaseNotes/1_0_1.md
  Packs/PolySwarm/pack_metadata.json
  Packs/RiskIQDigitalFootprint/Integrations/RiskIQDigitalFootprint/RiskIQDigitalFootprint.py
  Packs/RiskIQDigitalFootprint/ReleaseNotes/1_0_2.md
  Packs/RiskIQDigitalFootprint/pack_metadata.json
  Packs/UrlScan/Integrations/UrlScan/UrlScan.py
  Packs/UrlScan/ReleaseNotes/1_0_4.md
  Packs/UrlScan/pack_metadata.json
  Packs/VirusTotal-Private_API/Integrations/VirusTotal-Private_API/VirusTotal-Private_API.py
  Packs/VirusTotal-Private_API/ReleaseNotes/1_0_4.md
  Packs/VirusTotal-Private_API/pack_metadata.json
  Packs/Zscaler/Integrations/Zscaler/Zscaler.py
  Packs/Zscaler/ReleaseNotes/1_0_5.md
  Packs/Zscaler/pack_metadata.json
  dev-requirements-py3.txt
Labels: docs-approved, release-notes-only

#9095 SlashNext: Added EC for 'slashnext-api-quota' command.
  Packs/SlashNextPhishingIncidentResponse/Integrations/SlashNextPhishingIncidentResponse/README.md
  Packs/SlashNextPhishingIncidentResponse/Integrations/SlashNextPhishingIncidentResponse/SlashNextPhishingIncidentResponse.py
  Packs/SlashNextPhishingIncidentResponse/Integrations/SlashNextPhishingIncidentResponse/SlashNextPhishingIncidentResponse.yml
  Packs/SlashNextPhishingIncidentResponse/ReleaseNotes/1_1_0.md
  Packs/SlashNextPhishingIncidentResponse/pack_metadata.json
Labels: Contribution, docs-approved, ready-for-instance-test

#9264 Updated fromversion to 5.0.0
  Packs/CommonPlaybooks/TestPlaybooks/playbook-fieldpolling-test.yml
Labels: docs-approved

#9221 anomali: update readme
  Packs/Anomali_ThreatStream/Integrations/Anomali_ThreatStream_v2/README.md
Labels: docs-approved

#9259 riskiq readme images fixes
  Packs/RiskIQDigitalFootprint/Playbooks/playbook-Enrich_Incident_With_Asset_Details_-_RiskIQ_Digital_Footprint_README.md
  Packs/RiskIQDigitalFootprint/Playbooks/playbook-Update_Or_Remove_Assets_-_RiskIQ_Digital_Footprint_README.md
  Packs/RiskIQDigitalFootprint/README.md
Labels: docs-approved

#8903 Certify packs
  Packs/Code42/ReleaseNotes/2_0_5.md
  Packs/Code42/pack_metadata.json
  Packs/Expanse/ReleaseNotes/1_1_2.md
  Packs/Expanse/pack_metadata.json
  Packs/GoogleChronicleBackstory/ReleaseNotes/1_1_2.md
  Packs/GoogleChronicleBackstory/pack_metadata.json
  Packs/IllusiveNetworks/ReleaseNotes/1_0_5.md
  Packs/IllusiveNetworks/pack_metadata.json
  Packs/PassiveTotal/ReleaseNotes/2_0_2.md
  Packs/PassiveTotal/pack_metadata.json
  Packs/RecordedFuture/ReleaseNotes/1_0_1.md
  Packs/RecordedFuture/pack_metadata.json
  Packs/SafeBreach/ReleaseNotes/1_1_1.md
  Packs/SafeBreach/pack_metadata.json
  Packs/Sixgill-Darkfeed/ReleaseNotes/1_2_0.md
  Packs/Sixgill-Darkfeed/pack_metadata.json
  Packs/Tufin/ReleaseNotes/1_2_0.md
  Packs/Tufin/pack_metadata.json
Labels: docs-approved, release-notes-only

#9206 QRadar - Update versions support
  Packs/QRadar/Integrations/QRadar/README.md
Labels: bug, docs-approved, release-notes-only

#9262 SlashNext: Added EC for 'slashnext-api-quota' command. (#9095)
  Packs/SlashNextPhishingIncidentResponse/Integrations/SlashNextPhishingIncidentResponse/README.md
  Packs/SlashNextPhishingIncidentResponse/Integrations/SlashNextPhishingIncidentResponse/SlashNextPhishingIncidentResponse.py
  Packs/SlashNextPhishingIncidentResponse/Integrations/SlashNextPhishingIncidentResponse/SlashNextPhishingIncidentResponse.yml
  Packs/SlashNextPhishingIncidentResponse/ReleaseNotes/1_1_0.md
  Packs/SlashNextPhishingIncidentResponse/pack_metadata.json
Labels: docs-approved

#9273 GetIncidentById: updated script Role
  Packs/CommonScripts/ReleaseNotes/1_2_51.md
  Packs/CommonScripts/Scripts/script-SetByIncidentId.yml
  Packs/CommonScripts/pack_metadata.json
Labels: bug, docs-approved

#9258 Update content pipenv
  dev-requirements-py3.txt
Labels: docs-approved

#9270 change the name status in McAfee ESM v2 test playbook for v 11.3
  Packs/McAfee_ESM/TestPlaybooks/McAfee_ESM_v2_(v11.3)_-_Test.yml
Labels: docs-approved

#9267 adding fromversion to test playbooks
  Packs/GoogleChronicleBackstory/TestPlaybooks/playbook-GoogleChronicleBackstoryListIOCs-Test.yml
  Packs/XForceExchange/TestPlaybooks/playbook-Test_XFE_v2.yml
Labels: docs-approved

#9246 Tokenization runtime performance issuee fix
  Packs/Base/ReleaseNotes/1_3_11.md
  Packs/Base/Scripts/WordTokenizerV2/WordTokenizerV2.py
  Packs/Base/pack_metadata.json
Labels: docs-approved

#9276 RegexReplace - new pr
  Packs/RegexReplace/.pack-ignore
  Packs/RegexReplace/.secrets-ignore
  Packs/RegexReplace/README.md
  Packs/RegexReplace/Scripts/RegexReplace/Pipfile
  Packs/RegexReplace/Scripts/RegexReplace/Pipfile.lock
  Packs/RegexReplace/Scripts/RegexReplace/README.md
  Packs/RegexReplace/Scripts/RegexReplace/RegexReplace.py
  Packs/RegexReplace/Scripts/RegexReplace/RegexReplace.yml
  Packs/RegexReplace/pack_metadata.json
Labels: docs-approved

#9074 Fixing incident widgets
  Packs/CommonWidgets/ReleaseNotes/1_0_2.md
  Packs/CommonWidgets/Scripts/GetLargestInputsAndOuputsInIncidents/GetLargestInputsAndOuputsInIncidents.py
  Packs/CommonWidgets/Scripts/GetLargestInputsAndOuputsInIncidents/GetLargestInputsAndOuputsInIncidents.yml
  Packs/CommonWidgets/Scripts/GetLargestInputsAndOuputsInIncidents/GetLargestInputsAndOuputsInIncidents_test.py
  Packs/CommonWidgets/Scripts/GetLargestInvestigations/GetLargestInvestigations.py
  Packs/CommonWidgets/Scripts/GetLargestInvestigations/GetLargestInvestigations.yml
  Packs/CommonWidgets/Scripts/GetLargestInvestigations/GetLargestInvestigations_test.py
  Packs/CommonWidgets/Widgets/widget-LargestInputsAndOuputsInIncidentsWidget.json
  Packs/CommonWidgets/Widgets/widget-LargestInvestigationsWidget.json
  Packs/CommonWidgets/pack_metadata.json
Labels: bug, docs-approved, release-notes-only

#9124 Added option to provide string as input and convert to JSON in the code.
  Packs/CommonScripts/ReleaseNotes/1_2_52.md
  Packs/CommonScripts/Scripts/Jmespath/jmespath_test.py
  Packs/CommonScripts/Scripts/Jmespath/jmespath_transformer.py
  Packs/CommonScripts/pack_metadata.json
Labels: Contribution, docs-approved

#9216 Qradar get custom fields command
  Packs/QRadar/Integrations/QRadar_v2/QRadar_v2.py
  Packs/QRadar/Integrations/QRadar_v2/QRadar_v2.yml
  Packs/QRadar/Integrations/QRadar_v2/QRadar_v2_test.py
  Packs/QRadar/Integrations/QRadar_v2/README.md
  Packs/QRadar/ReleaseNotes/1_1_1.md
  Packs/QRadar/TestPlaybooks/playbook-TestQradarV2.yml
  Packs/QRadar/pack_metadata.json
Labels: docs-approved

#8951 Proofpoint Server Protection - Update README
  Packs/ProofpointServerProtection/Integrations/ProofpointServerProtection/README.md
Labels: docs-approved

#9215 CS Falcon small fix in fetch incidents
  Packs/CrowdStrikeFalcon/Integrations/CrowdStrikeFalcon/CrowdStrikeFalcon.py
  Packs/CrowdStrikeFalcon/ReleaseNotes/1_2_4.md
  Packs/CrowdStrikeFalcon/pack_metadata.json
Labels: bug, docs-approved, release-notes-only

#9113 Training phishing classifier - added validation
  Packs/Base/ReleaseNotes/1_3_12.md
  Packs/Base/Scripts/DBotTrainTextClassifierV2/DBotTrainTextClassifierV2.py
  Packs/Base/pack_metadata.json
Labels: docs-approved

#9287 Add fromversion qradar
  Packs/QRadar/TestPlaybooks/playbook-TestQradarV2.yml
Labels: docs-approved

#8720 changed comma delimiter to semicolon for tn-ask-question
  Packs/Tanium/Integrations/Tanium_v2/README.md
Labels: docs-approved

#9283 Adding usage of handle_proxy + enhancing the submit-event-hec command
  Packs/SplunkPy/Integrations/SplunkPy/SplunkPy.py
  Packs/SplunkPy/Integrations/SplunkPy/SplunkPy.yml
  Packs/SplunkPy/ReleaseNotes/1_2_3.md
  Packs/SplunkPy/pack_metadata.json
Labels: docs-approved

#9278 Release SDK 1-2-3
  dev-requirements-py3.txt
Labels: docs-approved

#9285 Health check improvements
  Packs/IntegrationsAndIncidentsHealthCheck/Dashboards/dashboard-Incidents_Health.json
  Packs/IntegrationsAndIncidentsHealthCheck/Dashboards/dashboard-Integrations_Health.json
  Packs/IntegrationsAndIncidentsHealthCheck/ReleaseNotes/1_1_0.md
  Packs/IntegrationsAndIncidentsHealthCheck/Scripts/IncidentsCheck-Widget-IncidentsErrorsInfo/IncidentsCheck_Widget_IncidentsErrorsInfo.py
  Packs/IntegrationsAndIncidentsHealthCheck/Scripts/IncidentsCheck-Widget-IncidentsErrorsInfo/IncidentsCheck_Widget_IncidentsErrorsInfo_test.py
  Packs/IntegrationsAndIncidentsHealthCheck/pack_metadata.json
Labels: docs-approved

#9079 Dummy index locking mechanism
  Tests/Marketplace/prepare_public_index_for_private_testing.py
  Tests/scripts/prepare_private_content_packs_for_testing.sh
Labels: docs-approved

#9272 MISP V2 - Remove from nightly failure
  Tests/conf.json
Labels: docs-approved

#9280 Added option to provide string as input and convert to JSON in the co…
  Packs/CommonScripts/ReleaseNotes/1_2_52.md
  Packs/CommonScripts/Scripts/Jmespath/Jmespath.py
  Packs/CommonScripts/Scripts/Jmespath/Jmespath.yml
  Packs/CommonScripts/Scripts/Jmespath/Jmespath_test.py
  Packs/CommonScripts/Scripts/Jmespath/jmespath_test.py
  Packs/CommonScripts/pack_metadata.json
Labels: docs-approved

#9289 Fixing lexical sorting in script
  Packs/CommonWidgets/ReleaseNotes/1_0_3.md
  Packs/CommonWidgets/Scripts/GetLargestInvestigations/GetLargestInvestigations.py
  Packs/CommonWidgets/pack_metadata.json
Labels: bug, docs-approved, release-notes-only

#9188 Microsoft Graph Mail - fetch by receivedDateTime
  Packs/MicrosoftGraphListener/Integrations/MicrosoftGraphListener/MicrosoftGraphListener.py
  Packs/MicrosoftGraphListener/Integrations/MicrosoftGraphListener/MicrosoftGraphListener.yml
  Packs/MicrosoftGraphListener/ReleaseNotes/1_0_7.md
  Packs/MicrosoftGraphListener/pack_metadata.json
  Packs/MicrosoftGraphMail/Integrations/MicrosoftGraphMail/MicrosoftGraphMail.py
  Packs/MicrosoftGraphMail/ReleaseNotes/1_0_8.md
  Packs/MicrosoftGraphMail/pack_metadata.json
Labels: docs-approved, release-notes-only

#8942 OpenCTI Feed
  Packs/FeedOpenCTI/.pack-ignore
  Packs/FeedOpenCTI/.secrets-ignore
  Packs/FeedOpenCTI/Integrations/FeedOpenCTI/FeedOpenCTI.py
  Packs/FeedOpenCTI/Integrations/FeedOpenCTI/FeedOpenCTI.yml
  Packs/FeedOpenCTI/Integrations/FeedOpenCTI/FeedOpenCTI_description.md
  Packs/FeedOpenCTI/Integrations/FeedOpenCTI/FeedOpenCTI_test.py
  Packs/FeedOpenCTI/Integrations/FeedOpenCTI/FeedOpenCti_image.png
  Packs/FeedOpenCTI/Integrations/FeedOpenCTI/Pipfile
  Packs/FeedOpenCTI/Integrations/FeedOpenCTI/Pipfile.lock
  Packs/FeedOpenCTI/Integrations/FeedOpenCTI/README.md
  Packs/FeedOpenCTI/Integrations/FeedOpenCTI/test_data/feed_data.py
  Packs/FeedOpenCTI/README.md
  Packs/FeedOpenCTI/TestPlaybooks/playbook-OpenCTI_Feed_Test.yml
  Packs/FeedOpenCTI/pack_metadata.json
  Tests/conf.json
Labels: docs-approved

#9279 [sixgill-195] Sixgill new pack name
  Packs/Sixgill-Darkfeed/ReleaseNotes/1_2_1.md
  Packs/Sixgill-Darkfeed/pack_metadata.json
Labels: Contribution, docs-approved, release-notes-only

#9263 Fix for Private Repo Pack Installation
  Tests/Marketplace/search_and_install_packs.py
Labels: docs-approved

#9298 Changed memory threshold for bruteforceblocker tpb
  Tests/conf.json
Labels: docs-approved

#9160 Added URLEncode transformer
  Packs/CommonScripts/ReleaseNotes/1_2_53.md
  Packs/CommonScripts/Scripts/URLEncode/URLEncode.py
  Packs/CommonScripts/Scripts/URLEncode/URLEncode.yml
  Packs/CommonScripts/Scripts/URLEncode/URLEncode_test.py
  Packs/CommonScripts/TestPlaybooks/playbook-URLEncode-Test.yml
  Packs/CommonScripts/pack_metadata.json
Labels: bug, docs-approved

#8862 [malwarebytes-254] Fix for events to show up in Classification Mapping
  Packs/Malwarebytes/Integrations/Malwarebytes/Malwarebytes.py
  Packs/Malwarebytes/Integrations/Malwarebytes/Malwarebytes.yml
  Packs/Malwarebytes/Integrations/Malwarebytes/README.md
  Packs/Malwarebytes/ReleaseNotes/1_1_0.md
  Packs/Malwarebytes/pack_metadata.json
Labels: Contribution, docs-approved

#9303 OpenCTI added fromversion
  Packs/FeedOpenCTI/TestPlaybooks/playbook-OpenCTI_Feed_Test.yml
Labels: docs-approved

#9304 Malwarebytes internal
  Packs/Malwarebytes/Integrations/Malwarebytes/Malwarebytes.py
  Packs/Malwarebytes/Integrations/Malwarebytes/Malwarebytes.yml
  Packs/Malwarebytes/Integrations/Malwarebytes/README.md
  Packs/Malwarebytes/ReleaseNotes/1_1_0.md
  Packs/Malwarebytes/pack_metadata.json
Labels: docs-approved

#9223 PAN-OS - Added the *deviceName*, *sessionID* arguments to the ***panorama-get-pcap*** command
  Packs/PAN-OS/Integrations/Panorama/Panorama.py
  Packs/PAN-OS/Integrations/Panorama/Panorama.yml
  Packs/PAN-OS/Integrations/Panorama/README.md
  Packs/PAN-OS/ReleaseNotes/1_6_2.md
  Packs/PAN-OS/TestPlaybooks/playbook-palo_alto_firewall_test_pb.yml
  Packs/PAN-OS/pack_metadata.json
  Tests/conf.json
Labels: docs-approved

#9220 SplunkPy - add get-mapping-fields command (#8691)
  Packs/SplunkPy/Integrations/SplunkPy/README.md
  Packs/SplunkPy/Integrations/SplunkPy/SplunkPy.py
  Packs/SplunkPy/Integrations/SplunkPy/SplunkPy.yml
  Packs/SplunkPy/Integrations/SplunkPy/SplunkPy_test.py
  Packs/SplunkPy/ReleaseNotes/1_2_4.md
  Packs/SplunkPy/pack_metadata.json
Labels: docs-approved

#9310 [4.5.0] Changed Microsoft Graph User test name to reflect changes in 5.0.0+
  Packs/MicrosoftGraphUser/TestPlaybooks/Microsoft_Graph_User_test.yml
  Tests/conf.json
Labels: docs-approved

#9268 PAN-OS - Added the *edl_type*, *location*, and *vsys* arguments to the ***panorama-refresh-edl***
  Packs/PAN-OS/Integrations/Panorama/Panorama.py
  Packs/PAN-OS/Integrations/Panorama/Panorama.yml
  Packs/PAN-OS/Integrations/Panorama/README.md
  Packs/PAN-OS/ReleaseNotes/1_6_3.md
  Packs/PAN-OS/TestPlaybooks/playbook-palo_alto_firewall_test_pb.yml
  Packs/PAN-OS/pack_metadata.json
Labels: docs-approved

#7928 [wootcloud-1178] WooCloud app integration
  Packs/WootCloud/.pack-ignore
  Packs/WootCloud/.secrets-ignore
  Packs/WootCloud/Integrations/WootCloud/Pipfile
  Packs/WootCloud/Integrations/WootCloud/Pipfile.lock
  Packs/WootCloud/Integrations/WootCloud/README.md
  Packs/WootCloud/Integrations/WootCloud/WootCloud.py
  Packs/WootCloud/Integrations/WootCloud/WootCloud.yml
  Packs/WootCloud/Integrations/WootCloud/WootCloud_description.md
  Packs/WootCloud/Integrations/WootCloud/WootCloud_image.png
  Packs/WootCloud/Integrations/WootCloud/WootCloud_test.py
  Packs/WootCloud/Integrations/WootCloud/commands.txt
  Packs/WootCloud/README.md
  Packs/WootCloud/TestPlaybooks/TestWootCloudPlaybook.yml
  Packs/WootCloud/pack_metadata.json
  Tests/conf.json
Labels: Contribution, docs-approved

#9163 Common Server Python - import errors not caught in python 2
  Packs/Base/ReleaseNotes/1_3_13.md
  Packs/Base/Scripts/CommonServerPython/CommonServerPython.py
  Packs/Base/pack_metadata.json
Labels: docs-approved, release-notes-only

#7773 XSOAR mirroring
  Packs/XSOARmirroring/.pack-ignore
  Packs/XSOARmirroring/.secrets-ignore
  Packs/XSOARmirroring/CHANGELOG.md
  Packs/XSOARmirroring/Classifiers/classifier-XSOAR_Mirror.json
  Packs/XSOARmirroring/Classifiers/classifier-XSOAR_Mirror_In.json
  Packs/XSOARmirroring/Classifiers/classifier-XSOAR_Mirror_Out.json
  Packs/XSOARmirroring/IncidentFields/incidentfield-from-pong.json
  Packs/XSOARmirroring/IncidentTypes/incidenttype-xsoar-mirroring-ping.json
  Packs/XSOARmirroring/IncidentTypes/incidenttype-xsoar-mirroring-pong.json
  Packs/XSOARmirroring/Integrations/XSOARmirroring/Pipfile
  Packs/XSOARmirroring/Integrations/XSOARmirroring/Pipfile.lock
  Packs/XSOARmirroring/Integrations/XSOARmirroring/README.md
  Packs/XSOARmirroring/Integrations/XSOARmirroring/XSOARmirroring.py
  Packs/XSOARmirroring/Integrations/XSOARmirroring/XSOARmirroring.yml
  Packs/XSOARmirroring/Integrations/XSOARmirroring/XSOARmirroring_description.md
  Packs/XSOARmirroring/Integrations/XSOARmirroring/XSOARmirroring_image.png
  Packs/XSOARmirroring/Integrations/XSOARmirroring/XSOARmirroring_test.py
  Packs/XSOARmirroring/README.md
  Packs/XSOARmirroring/pack_metadata.json
Labels: docs-approved

#9260 Openphishv2
  Packs/OpenPhish/.secrets-ignore
  Packs/OpenPhish/Integrations/OpenPhish_v2/OpenPhish_v2.py
  Packs/OpenPhish/Integrations/OpenPhish_v2/OpenPhish_v2.yml
  Packs/OpenPhish/Integrations/OpenPhish_v2/OpenPhish_v2_description.md
  Packs/OpenPhish/Integrations/OpenPhish_v2/OpenPhish_v2_image.png
  Packs/OpenPhish/Integrations/OpenPhish_v2/OpenPhish_v2_test.py
  Packs/OpenPhish/Integrations/OpenPhish_v2/README.md
  Packs/OpenPhish/Integrations/OpenPhish_v2/command_examples.txt
  Packs/OpenPhish/Integrations/OpenPhish_v2/test_data/api_raw.py
  Packs/OpenPhish/Integrations/integration-OpenPhish.yml
  Packs/OpenPhish/ReleaseNotes/2_0_0.md
  Packs/OpenPhish/pack_metadata.json
Labels: docs-approved

#9306 update merge_zip script and fixed collect_test unitest
  Tests/scripts/infrastructure_tests/test_collect_tests_and_content_packs.py
  Utils/merge_content_new_zip.py
Labels: docs-approved

#9116 Case Management Pack - Fixes for Incident Action Buttons on Layout, Case Report, Widgets
  Packs/CaseManagement-Generic/Dashboards/dashboard-Incidents_Overview.json
  Packs/CaseManagement-Generic/Layouts/layout-close-Case_layout-Case.json
  Packs/CaseManagement-Generic/Layouts/layout-detailsV2-Case_layout-Case.json
  Packs/CaseManagement-Generic/Layouts/layout-edit-Case_layout-Case.json
  Packs/CaseManagement-Generic/Layouts/layout-mobile-Case_layout-Case.json
  Packs/CaseManagement-Generic/Layouts/layout-quickView-Case_layout-Case.json
  Packs/CaseManagement-Generic/Layouts/layoutscontainer-Case_layout.json
  Packs/CaseManagement-Generic/ReleaseNotes/1_1_0.md
  Packs/CaseManagement-Generic/Reports/report-CaseReport.json
  Packs/CaseManagement-Generic/Scripts/AssignToMeButton/AssignToMeButton.yml
  Packs/CaseManagement-Generic/Scripts/GenerateSummaryReportButton/GenerateSummaryReportButton.yml
  Packs/CaseManagement-Generic/Scripts/LinkIncidentsButton/LinkIncidentsButton.yml
  Packs/CaseManagement-Generic/Scripts/TimersOnOwnerChange/TimersOnOwnerChange.yml
  Packs/CaseManagement-Generic/Widgets/widget-Mean_Time_To_Remediation_SLA.json
  Packs/CaseManagement-Generic/Widgets/widget-My_Incidents_by_Type.json
  Packs/CaseManagement-Generic/Widgets/widget-My_Mean_Time_To_Remediation_SLA.json
  Packs/CaseManagement-Generic/Widgets/widget-Participating_Incidents.json
  Packs/CaseManagement-Generic/Widgets/widget-Participating_Incidents_Count.json
  Packs/CaseManagement-Generic/Widgets/widget-Time_To_Assignment.json
  Packs/CaseManagement-Generic/pack_metadata.json
Labels: Contribution, docs-approved, ready-for-instance-test

#9314 falcon intel v2: disable links
  Packs/CrowdStrikeIntel/Integrations/CrowdStrikeFalconIntel_v2/README.md
Labels: docs-approved

#9320 fixing validation
  Tests/scripts/validate.sh
  dev-requirements-py3.txt
Labels: docs-approved

#9316 Update layoutscontainer-Case_layout.json
  Packs/CaseManagement-Generic/IncidentTypes/incidenttype-Case.json
  Packs/CaseManagement-Generic/Layouts/layout-close-Case_layout-Case.json
  Packs/CaseManagement-Generic/Layouts/layout-detailsV2-Case_layout-Case.json
  Packs/CaseManagement-Generic/Layouts/layout-edit-Case_layout-Case.json
  Packs/CaseManagement-Generic/Layouts/layout-mobile-Case_layout-Case.json
  Packs/CaseManagement-Generic/Layouts/layout-quickView-Case_layout-Case.json
  Packs/CaseManagement-Generic/Layouts/layoutscontainer-Case_layout.json
  Packs/CaseManagement-Generic/ReleaseNotes/1_0_1.md
  Packs/CaseManagement-Generic/pack_metadata.json
Labels: docs-approved, release-notes-only

#8990 GKE - Updated documentations
  Packs/GoogleKubernetesEngine/Integrations/GoogleKubernetesEngine/README.md
  Packs/GoogleKubernetesEngine/doc_files/create-project-1.png
  Packs/GoogleKubernetesEngine/doc_files/enable-gke-api-enable-1.png
  Packs/GoogleKubernetesEngine/doc_files/enable-gke-api-enable-2.png
  Packs/GoogleKubernetesEngine/doc_files/enable-gke-api-menu.png
  Packs/GoogleKubernetesEngine/doc_files/enable-gke-api-search.png
  Packs/GoogleKubernetesEngine/doc_files/service-account-create-1.png
  Packs/GoogleKubernetesEngine/doc_files/service-account-create-2.png
  Packs/GoogleKubernetesEngine/doc_files/service-account-create-3.png
  Packs/GoogleKubernetesEngine/doc_files/service-account-create-4.png
  Packs/GoogleKubernetesEngine/doc_files/service-acount-menu.png
  Packs/GoogleKubernetesEngine/pack_metadata.json
Labels: bug, docs-approved

#9308 SNow v2 fix empty credentials error
  Packs/ServiceNow/Integrations/ServiceNowv2/ServiceNowv2.py
  Packs/ServiceNow/Integrations/ServiceNowv2/ServiceNowv2.yml
  Packs/ServiceNow/ReleaseNotes/1_3_3.md
  Packs/ServiceNow/TestPlaybooks/playbook-ServiceNow_Test_New.yml
  Packs/ServiceNow/pack_metadata.json
  TestPlaybooks/NonCircleTests/playbook-ServiceNow_Test.yml
  Tests/conf.json
Labels: docs-approved, release-notes-only

#9323 Wootcloud internal
  Packs/WootCloud/.pack-ignore
  Packs/WootCloud/.secrets-ignore
  Packs/WootCloud/Integrations/WootCloud/Pipfile
  Packs/WootCloud/Integrations/WootCloud/Pipfile.lock
  Packs/WootCloud/Integrations/WootCloud/README.md
  Packs/WootCloud/Integrations/WootCloud/WootCloud.py
  Packs/WootCloud/Integrations/WootCloud/WootCloud.yml
  Packs/WootCloud/Integrations/WootCloud/WootCloud_description.md
  Packs/WootCloud/Integrations/WootCloud/WootCloud_image.png
  Packs/WootCloud/Integrations/WootCloud/WootCloud_test.py
  Packs/WootCloud/Integrations/WootCloud/commands.txt
  Packs/WootCloud/README.md
  Packs/WootCloud/TestPlaybooks/TestWootCloudPlaybook.yml
  Packs/WootCloud/pack_metadata.json
  Tests/conf.json
Labels: docs-approved

#9325 Change debug logs color
  Tests/scripts/collect_tests_and_content_packs.py
Labels: docs-approved

#9281 Fix duoadmin bug
  Packs/DuoAdminApi/Integrations/DuoAdminApi/DuoAdminApi.py
  Packs/DuoAdminApi/Integrations/DuoAdminApi/DuoAdminApi.yml
  Packs/DuoAdminApi/ReleaseNotes/2_0_3.md
  Packs/DuoAdminApi/pack_metadata.json
Labels: bug, docs-approved

#9326 pan-os rn reindexing
  Packs/PAN-OS/ReleaseNotes/1_6_2.md
  Packs/PAN-OS/ReleaseNotes/1_6_3.md
Labels: docs-approved

#9327 Demisto Mock - fix createIncidents docstring
  Tests/demistomock/demistomock.py
Labels: docs-approved

#9311 Fixing the printed "bucket link" message for private builds + dummy index update
  Tests/Marketplace/prepare_public_index_for_private_testing.py
  Tests/scripts/prepare_private_content_packs_for_testing.sh
Labels: docs-approved

#9244 Get incidents by query paging
  Packs/Base/ReleaseNotes/1_3_14.md
  Packs/Base/Scripts/GetIncidentsByQuery/GetIncidentsByQuery.py
  Packs/Base/Scripts/GetIncidentsByQuery/GetIncidentsByQuery.yml
  Packs/Base/Scripts/GetIncidentsByQuery/get_incidents_by_query_test.py
  Packs/Base/pack_metadata.json
Labels: docs-approved

#9284 [Enhancement] QRadar v2 changed fetched asset properties format
  Packs/QRadar/Integrations/QRadar_v2/QRadar_v2.py
  Packs/QRadar/Integrations/QRadar_v2/QRadar_v2_test.py
  Packs/QRadar/ReleaseNotes/1_1_2.md
  Packs/QRadar/pack_metadata.json
Labels: docs-approved, release-notes-only

#9231 Service now create ticket, mirroring and state polling playbooks
  Packs/ServiceNow/Classifiers/classifier-mapper-ServiceNow_Create_Ticket_-_Incoming_Mapper.json
  Packs/ServiceNow/Classifiers/classifier-mapper-ServiceNow_Create_Ticket_-_Outgoing_Mapper.json
  Packs/ServiceNow/IncidentFields/incidentfield-ServiceNow_Assigned_To.json
  Packs/ServiceNow/IncidentFields/incidentfield-ServiceNow_Assignment_Group.json
  Packs/ServiceNow/IncidentFields/incidentfield-ServiceNow_Caller.json
  Packs/ServiceNow/IncidentFields/incidentfield-ServiceNow_Caller_ID.json
  Packs/ServiceNow/IncidentFields/incidentfield-ServiceNow_Category.json
  Packs/ServiceNow/IncidentFields/incidentfield-ServiceNow_Closed_By.json
  Packs/ServiceNow/IncidentFields/incidentfield-ServiceNow_Closed_Date.json
  Packs/ServiceNow/IncidentFields/incidentfield-ServiceNow_Description.json
  Packs/ServiceNow/IncidentFields/incidentfield-ServiceNow_Due_Date.json
  Packs/ServiceNow/IncidentFields/incidentfield-ServiceNow_Escalation.json
  Packs/ServiceNow/IncidentFields/incidentfield-ServiceNow_Impact.json
  Packs/ServiceNow/IncidentFields/incidentfield-ServiceNow_Notify.json
  Packs/ServiceNow/IncidentFields/incidentfield-ServiceNow_Opened_Date.json
  Packs/ServiceNow/IncidentFields/incidentfield-ServiceNow_Priority.json
  Packs/ServiceNow/IncidentFields/incidentfield-ServiceNow_Resolution_Code.json
  Packs/ServiceNow/IncidentFields/incidentfield-ServiceNow_Resolution_Notes.json
  Packs/ServiceNow/IncidentFields/incidentfield-ServiceNow_Resolved_Time.json
  Packs/ServiceNow/IncidentFields/incidentfield-ServiceNow_Severity.json
  Packs/ServiceNow/IncidentFields/incidentfield-ServiceNow_State.json
  Packs/ServiceNow/IncidentFields/incidentfield-ServiceNow_Ticket_Number.json
  Packs/ServiceNow/IncidentFields/incidentfield-ServiceNow_Urgency.json
  Packs/ServiceNow/IncidentTypes/incidenttype-ServiceNow_Create_Ticket_and_Mirror.json
  Packs/ServiceNow/Integrations/ServiceNowv2/ServiceNowv2.yml
  Packs/ServiceNow/Layouts/layoutscontainer-ServiceNow_Create_Ticket_and_Mirror.json
  Packs/ServiceNow/Layouts/layoutscontainer-ServiceNow_Ticket.json
  Packs/ServiceNow/Playbooks/playbook-Create_ServiceNow_Ticket.yml
  Packs/ServiceNow/Playbooks/playbook-Create_ServiceNow_Ticket_README.md
  Packs/ServiceNow/Playbooks/playbook-Mirror_ServiceNow_Ticket.yml
  Packs/ServiceNow/Playbooks/playbook-Mirror_ServiceNow_Ticket_README.md
  Packs/ServiceNow/Playbooks/playbook-ServiceNow_Ticket_State_Polling.yml
  Packs/ServiceNow/Playbooks/playbook-ServiceNow_Ticket_State_Polling_README.md
  Packs/ServiceNow/ReleaseNotes/1_3_4.md
  Packs/ServiceNow/Scripts/ServiceNowIncidentStatus/README.md
  Packs/ServiceNow/Scripts/ServiceNowIncidentStatus/ServiceNowIncidentStatus.py
  Packs/ServiceNow/Scripts/ServiceNowIncidentStatus/ServiceNowIncidentStatus.yml
  Packs/ServiceNow/TestPlaybooks/playbook-Create_ServiceNow_Ticket_and_Mirror_Test.yml
  Packs/ServiceNow/TestPlaybooks/playbook-Create_ServiceNow_Ticket_and_State_Polling_Test.yml
  Packs/ServiceNow/doc_files/Create_ServiceNow_Ticket.png
  Packs/ServiceNow/doc_files/Mirror_ServiceNow_Ticket.png
  Packs/ServiceNow/doc_files/ServiceNow_Ticket_State_Polling.png
  Packs/ServiceNow/pack_metadata.json
  Tests/conf.json
Labels: docs-approved

#9333 Servcie now ticket layout id fix & New playbooks screen shots
  Packs/ServiceNow/IncidentTypes/incidenttype-ServiceNowTicket.json
  Packs/ServiceNow/Playbooks/playbook-Create_ServiceNow_Ticket_README.md
  Packs/ServiceNow/Playbooks/playbook-Mirror_ServiceNow_Ticket_README.md
  Packs/ServiceNow/Playbooks/playbook-ServiceNow_Ticket_State_Polling_README.md
  Packs/ServiceNow/ReleaseNotes/1_3_5.md
  Packs/ServiceNow/pack_metadata.json
Labels: docs-approved

#9339 GCP Kubernetes: remove zoom:40% style tag
  Packs/GoogleKubernetesEngine/Integrations/GoogleKubernetesEngine/README.md
Labels: docs-approved

#9334 release 1.2.4
  dev-requirements-py3.txt
Labels: docs-approved

#9225 Anomali ThreatStream v2 - import with approval bug
  Packs/Anomali_ThreatStream/Integrations/Anomali_ThreatStream_v2/Anomali_ThreatStream_v2.py
  Packs/Anomali_ThreatStream/Integrations/Anomali_ThreatStream_v2/Anomali_ThreatStream_v2.yml
  Packs/Anomali_ThreatStream/Integrations/Anomali_ThreatStream_v2/Anomali_ThreatStream_v2_test.py
  Packs/Anomali_ThreatStream/ReleaseNotes/1_0_4.md
  Packs/Anomali_ThreatStream/pack_metadata.json
Labels: bug, docs-approved

#9347 Kubernetes: another fix to remove style tag
  Packs/GoogleKubernetesEngine/Integrations/GoogleKubernetesEngine/README.md
Labels: docs-approved

#9346 Conf fixes
  Tests/conf.json
Labels: docs-approved

#9315 Add docker authentication to avoid docker rate limits
  .circleci/config.yml
Labels: docs-approved

#9337 Build env miss calculation fix
  Tests/scripts/collect_tests_and_content_packs.py
  Tests/scripts/infrastructure_tests/test_collect_tests_and_content_packs.py
  Tests/scripts/infrastructure_tests/tests_data/mock_conf.json
  Tests/scripts/infrastructure_tests/tests_data/mock_id_set.json
  Tests/scripts/infrastructure_tests/tests_data/mock_integrations/test_fake_integration.yml
  Tests/scripts/infrastructure_tests/tests_data/mock_playbooks/test_fake_playbook.yml
  Tests/scripts/infrastructure_tests/tests_data/mock_test_playbooks/playbook-fake_test_playbook_to_version.yml
Labels: docs-approved

#8995 DuoAdmin TPB - Changed condition logic
  Packs/DuoAdminApi/TestPlaybooks/playbook-DuoAdminaAPITest.yml
  Tests/conf.json
Labels: docs-approved

#9338 send proxy metrics to GCP object
  Tests/mock_server.py
  Tests/test_content.py
Labels: docs-approved

#9226 ExtraHop - Add incorrectly deprecated playbook back into ExtraHop Pack
  Packs/ExtraHop/Playbooks/playbook-ExtraHop_-_Ticket_Tracking_README.md
  Packs/ExtraHop/Playbooks/playbook-ExtraHop_-_Ticket_Tracking_v2.yml
  Packs/ExtraHop/README.md
  Packs/ExtraHop/ReleaseNotes/1_0_3.md
  Packs/ExtraHop/doc_files/ExtraHop_CVE-2019-0708_BlueKeep.png
  Packs/ExtraHop/doc_files/ExtraHop_Default.png
  Packs/ExtraHop/doc_files/ExtraHop_Demisto_Incident_CVE-2019-0708_BlueKeep.png
  Packs/ExtraHop/doc_files/ExtraHop_Detection_CVE-2019-0708_BlueKeep.png
  Packs/ExtraHop/pack_metadata.json
Labels: Contribution, docs-approved, ready-for-instance-test, release-notes-only

#9359 test playbook fix
  Packs/IllusiveNetworks/TestPlaybooks/playbook-IllusiveNetworks-Test.yml
Labels: Contribution, docs-approved, ready-for-instance-test, release-notes-only

#9376 skip zerofox
  Tests/conf.json
Labels: docs-approved

#9349 Service now ticket layout fix
  Packs/ServiceNow/Layouts/layoutscontainer-ServiceNow_Ticket.json
  Packs/ServiceNow/ReleaseNotes/1_3_6.md
  Packs/ServiceNow/pack_metadata.json
Labels: docs-approved

#9090 [Cofense] Add support for `inbox_reports` endpoint
  Packs/CofenseTriage/Integrations/CofenseTriagev2/CofenseTriagev2.py
  Packs/CofenseTriage/Integrations/CofenseTriagev2/CofenseTriagev2.yml
  Packs/CofenseTriage/Integrations/CofenseTriagev2/CofenseTriagev2_description.md
  Packs/CofenseTriage/Integrations/CofenseTriagev2/CofenseTriagev2_test.py
  Packs/CofenseTriage/Integrations/CofenseTriagev2/README.md
  Packs/CofenseTriage/Integrations/CofenseTriagev2/command_examples.txt
  Packs/CofenseTriage/Integrations/CofenseTriagev2/test/fixtures/inbox_reports.json
  Packs/CofenseTriage/Integrations/CofenseTriagev2/test/fixtures/reporters_by_email_reporter2.json
  Packs/CofenseTriage/ReleaseNotes/1_1_6.md
  Packs/CofenseTriage/TestPlaybooks/playbook-Cofense_Triage_v2-Test.yml
  Packs/CofenseTriage/pack_metadata.json
Labels: Contribution, docs-approved

#8915 FireEye HX - remove body from containment request if version greater than 3
  Packs/FireEyeHX/Integrations/FireEyeHX/FireEyeHX.py
  Packs/FireEyeHX/ReleaseNotes/1_0_5.md
  Packs/FireEyeHX/pack_metadata.json
Labels: bug, docs-approved

#9369 Updated TLP handling TAXII feed
  Packs/FeedTAXII/Integrations/FeedTAXII/FeedTAXII.py
  Packs/FeedTAXII/Integrations/FeedTAXII/FeedTAXII_test/TestCommands/indicators_results.json
  Packs/FeedTAXII/ReleaseNotes/1_0_5.md
  Packs/FeedTAXII/pack_metadata.json
Labels: docs-approved

#9208 Sumo logic Fetch Bug
  Packs/SumoLogic/Integrations/integration-SumoLogic.yml
  Packs/SumoLogic/ReleaseNotes/1_0_2.md
  Packs/SumoLogic/pack_metadata.json
Labels: bug, docs-approved, release-notes-only

#9352 Deprecate Old Build Files
  Tests/lastest_server_build_scripts/create_instance.sh
  Tests/lastest_server_build_scripts/run_installer_on_instance.sh
  Tests/scripts/create_instance.sh
  Tests/scripts/create_instances.py
  Tests/scripts/get_instance_ip.sh
  Tests/scripts/run_content_installation.py
  Tests/scripts/wait_until_server_ready.py
  Tests/test_content.py
Labels: docs-approved

#9290 [Infrastructure] Add handling for .pack-ignore skipped tests
  Tests/scripts/collect_tests_and_content_packs.py
  Tests/scripts/infrastructure_tests/test_collect_tests_and_content_packs.py
Labels: docs-approved

#8578 Cisco email security integration
  Packs/CiscoEmailSecurity/.pack-ignore
  Packs/CiscoEmailSecurity/.secrets-ignore
  Packs/CiscoEmailSecurity/Integrations/CiscoEmailSecurity/CiscoEmailSecurity.py
  Packs/CiscoEmailSecurity/Integrations/CiscoEmailSecurity/CiscoEmailSecurity.yml
  Packs/CiscoEmailSecurity/Integrations/CiscoEmailSecurity/CiscoEmailSecurity_description.md
  Packs/CiscoEmailSecurity/Integrations/CiscoEmailSecurity/CiscoEmailSecurity_image.png
  Packs/CiscoEmailSecurity/Integrations/CiscoEmailSecurity/CiscoEmailSecurity_test.py
  Packs/CiscoEmailSecurity/Integrations/CiscoEmailSecurity/Pipfile
  Packs/CiscoEmailSecurity/Integrations/CiscoEmailSecurity/Pipfile.lock
  Packs/CiscoEmailSecurity/Integrations/CiscoEmailSecurity/README.md
  Packs/CiscoEmailSecurity/Integrations/CiscoEmailSecurity/test_data.json
  Packs/CiscoEmailSecurity/README.md
  Packs/CiscoEmailSecurity/pack_metadata.json
Labels: docs-approved

#9384 Increased test timeout for service now polling playbook
  Tests/conf.json
Labels: docs-approved

#9383 Fix Typo in MS-Defender ATP
  Packs/MicrosoftDefenderAdvancedThreatProtection/Integrations/MicrosoftDefenderAdvancedThreatProtection/MicrosoftDefenderAdvancedThreatProtection.py
  Packs/MicrosoftDefenderAdvancedThreatProtection/Integrations/MicrosoftDefenderAdvancedThreatProtection/MicrosoftDefenderAdvancedThreatProtection.yml
  Packs/MicrosoftDefenderAdvancedThreatProtection/ReleaseNotes/1_2_2.md
  Packs/MicrosoftDefenderAdvancedThreatProtection/pack_metadata.json
Labels: docs-approved, release-notes-only

#9377 cs falcon intel v2 -support displaypassword param
  Packs/CrowdStrikeIntel/Integrations/CrowdStrikeFalconIntel_v2/CrowdStrikeFalconIntel_v2.py
  Packs/CrowdStrikeIntel/Integrations/CrowdStrikeFalconIntel_v2/CrowdStrikeFalconIntel_v2.yml
  Packs/CrowdStrikeIntel/Integrations/CrowdStrikeFalconIntel_v2/CrowdStrikeFalconIntel_v2_description.md
  Packs/CrowdStrikeIntel/ReleaseNotes/2_0_1.md
  Packs/CrowdStrikeIntel/pack_metadata.json
Labels: docs-approved, release-notes-only

#9365 converting GetIncidentsByQuersy script to python3
  Packs/Base/ReleaseNotes/1_3_15.md
  Packs/Base/Scripts/GetIncidentsByQuery/GetIncidentsByQuery.py
  Packs/Base/Scripts/GetIncidentsByQuery/GetIncidentsByQuery.yml
  Packs/Base/pack_metadata.json
Labels: docs-approved

#9385 Updated WootCloud Pack metadata
  Packs/WootCloud/ReleaseNotes/1_0_1.md
  Packs/WootCloud/pack_metadata.json
  Tests/conf.json
Labels: docs-approved

#9370 Slack proxy - Update docker image
  Packs/Slack/Integrations/Slack/Slack.yml
  Packs/Slack/ReleaseNotes/1_3_6.md
  Packs/Slack/pack_metadata.json
Labels: docs-approved

#9386 Cofense triage v2 internal
  Packs/CofenseTriage/.secrets-ignore
  Packs/CofenseTriage/Integrations/CofenseTriagev2/CofenseTriagev2.py
  Packs/CofenseTriage/Integrations/CofenseTriagev2/CofenseTriagev2.yml
  Packs/CofenseTriage/Integrations/CofenseTriagev2/CofenseTriagev2_description.md
  Packs/CofenseTriage/Integrations/CofenseTriagev2/CofenseTriagev2_test.py
  Packs/CofenseTriage/Integrations/CofenseTriagev2/README.md
  Packs/CofenseTriage/Integrations/CofenseTriagev2/command_examples.txt
  Packs/CofenseTriage/Integrations/CofenseTriagev2/test/fixtures/inbox_reports.json
  Packs/CofenseTriage/Integrations/CofenseTriagev2/test/fixtures/reporters_by_email_reporter2.json
  Packs/CofenseTriage/ReleaseNotes/1_1_6.md
  Packs/CofenseTriage/TestPlaybooks/playbook-Cofense_Triage_v2-Test.yml
  Packs/CofenseTriage/pack_metadata.json
Labels: docs-approved

#8928 Deprecate archer v1
  Packs/ArcherRSA/Integrations/integration-ArcherRSA.yml
  Packs/ArcherRSA/ReleaseNotes/1_1_1.md
  Packs/ArcherRSA/pack_metadata.json
Labels: docs-approved

#9167 adding docs for SearchIncidentsV2
  Packs/CommonScripts/ReleaseNotes/1_2_54.md
  Packs/CommonScripts/Scripts/SearchIncidentsV2/README.md
  Packs/CommonScripts/Scripts/SearchIncidentsV2/SearchIncidentsV2.yml
  Packs/CommonScripts/pack_metadata.json
Labels: docs-approved

#9081 SSL - troubleshout
  Packs/Troubleshoot/.pack-ignore
  Packs/Troubleshoot/.secrets-ignore
  Packs/Troubleshoot/README.md
  Packs/Troubleshoot/Scripts/CertificatesTroubleshoot/CertificatesTroubleshoot.py
  Packs/Troubleshoot/Scripts/CertificatesTroubleshoot/CertificatesTroubleshoot.yml
  Packs/Troubleshoot/Scripts/CertificatesTroubleshoot/CertificatesTroubleshoot_test.py
  Packs/Troubleshoot/Scripts/CertificatesTroubleshoot/README.md
  Packs/Troubleshoot/Scripts/CertificatesTroubleshoot/data/CA.pem
  Packs/Troubleshoot/Scripts/CertificatesTroubleshoot/data/output.json
  Packs/Troubleshoot/pack_metadata.json
Labels: bug, docs-approved

#9394 add is html doc to phshlabs ioc readme
  Packs/PhishLabs/Integrations/PhishLabsIOC_DRP/README.md
Labels: docs-approved

#9396 Fixed wootcloud test Playbook
  Packs/WootCloud/TestPlaybooks/TestWootCloudPlaybook.yml
Labels: docs-approved

#9366 [Enhancement] Large incidents widgets - usability changes
  Packs/CommonWidgets/ReleaseNotes/1_0_4.md
  Packs/CommonWidgets/Scripts/GetLargestInputsAndOuputsInIncidents/GetLargestInputsAndOuputsInIncidents.py
  Packs/CommonWidgets/Scripts/GetLargestInputsAndOuputsInIncidents/GetLargestInputsAndOuputsInIncidents.yml
  Packs/CommonWidgets/Scripts/GetLargestInputsAndOuputsInIncidents/GetLargestInputsAndOuputsInIncidents_test.py
  Packs/CommonWidgets/Scripts/GetLargestInvestigations/GetLargestInvestigations.py
  Packs/CommonWidgets/Scripts/GetLargestInvestigations/GetLargestInvestigations.yml
  Packs/CommonWidgets/Scripts/GetLargestInvestigations/GetLargestInvestigations_test.py
  Packs/CommonWidgets/Widgets/widget-LargestInputsAndOuputsInIncidentsWidget.json
  Packs/CommonWidgets/Widgets/widget-LargestInvestigationsWidget.json
  Packs/CommonWidgets/pack_metadata.json
Labels: docs-approved

#9342 Fixed sorting issue in XDR
  Packs/CortexXDR/Integrations/PaloAltoNetworks_XDR/PaloAltoNetworks_XDR.py
  Packs/CortexXDR/Integrations/PaloAltoNetworks_XDR/PaloAltoNetworks_XDR.yml
  Packs/CortexXDR/Integrations/PaloAltoNetworks_XDR/PaloAltoNetworks_XDR_test.py
  Packs/CortexXDR/ReleaseNotes/2_4_1.md
  Packs/CortexXDR/pack_metadata.json
Labels: bug, docs-approved, release-notes-only

#9345 Update contributors packs data
  Packs/Aella_StarLight/ReleaseNotes/1_0_1.md
  Packs/Aella_StarLight/pack_metadata.json
  Packs/Cymulate/ReleaseNotes/1_0_6.md
  Packs/Cymulate/pack_metadata.json
  Packs/Genians/ReleaseNotes/1_0_1.md
  Packs/Genians/pack_metadata.json
  Packs/Indeni/ReleaseNotes/1_0_6.md
  Packs/Indeni/pack_metadata.json
  Packs/Luminate/ReleaseNotes/1_0_1.md
  Packs/Luminate/pack_metadata.json
  Packs/MinervaLabsAntiEvasionPlatform/ReleaseNotes/1_0_1.md
  Packs/MinervaLabsAntiEvasionPlatform/pack_metadata.json
  Packs/PassiveTotal/ReleaseNotes/2_0_3.md
  Packs/PassiveTotal/pack_metadata.json
  Packs/PolySwarm/ReleaseNotes/1_0_2.md
  Packs/PolySwarm/pack_metadata.json
  Packs/RiskIQDigitalFootprint/ReleaseNotes/1_0_3.md
  Packs/RiskIQDigitalFootprint/pack_metadata.json
  Packs/RiskSense/ReleaseNotes/1_0_3.md
  Packs/RiskSense/pack_metadata.json
  Packs/SecurityIntelligenceServicesFeed/ReleaseNotes/1_0_2.md
  Packs/SecurityIntelligenceServicesFeed/pack_metadata.json
  Packs/Sepio/ReleaseNotes/1_0_1.md
  Packs/Sepio/pack_metadata.json
  Packs/Silverfort/ReleaseNotes/1_0_3.md
  Packs/Silverfort/pack_metadata.json
  Packs/illuminate/ReleaseNotes/1_0_3.md
  Packs/illuminate/pack_metadata.json
  Tests/conf.json
Labels: docs-approved

#8222 MicrosoftGraphUser add manager information
  Packs/MicrosoftGraphUser/Integrations/MicrosoftGraphUser/MicrosoftGraphUser.py
  Packs/MicrosoftGraphUser/Integrations/MicrosoftGraphUser/MicrosoftGraphUser.yml
  Packs/MicrosoftGraphUser/Integrations/MicrosoftGraphUser/README.md
  Packs/MicrosoftGraphUser/ReleaseNotes/1_3_3.md
  Packs/MicrosoftGraphUser/TestPlaybooks/Microsoft_Graph_User_test.yml
  Packs/MicrosoftGraphUser/pack_metadata.json
Labels: Contribution, docs-approved

#9362 Find Similar Incidents - bug
  Packs/CommonScripts/ReleaseNotes/1_2_55.md
  Packs/CommonScripts/Scripts/FindSimilarIncidentsV2/FindSimilarIncidentsV2.py
  Packs/CommonScripts/Scripts/FindSimilarIncidentsV2/find_similar_incidents_test.py
  Packs/CommonScripts/pack_metadata.json
Labels: docs-approved, release-notes-only

#9335 Fix EWS O365 get-items and get-items-as-eml command will fail on target mailbox
  Packs/EWS/Integrations/EWSO365/EWSO365.py
  Packs/EWS/ReleaseNotes/1_3_3.md
  Packs/EWS/pack_metadata.json
Labels: bug, docs-approved, release-notes-only

#9379 update dev requirements
  dev-requirements-py2.txt
  dev-requirements-py3.txt
Labels: docs-approved

#9341 Dbot train text classfier bug fix - support case insensative labels mapping
  Packs/Base/ReleaseNotes/1_3_16.md
  Packs/Base/Scripts/DBotTrainTextClassifierV2/DBotTrainTextClassifierV2.py
  Packs/Base/Scripts/DBotTrainTextClassifierV2/dbot_train_text_classifier_test.py
  Packs/Base/pack_metadata.json
Labels: docs-approved

#9344 Case management new pr
  Packs/CaseManagement-Generic/Dashboards/dashboard-Incidents_Overview.json
  Packs/CaseManagement-Generic/Layouts/layout-close-Case_layout-Case.json
  Packs/CaseManagement-Generic/Layouts/layout-detailsV2-Case_layout-Case.json
  Packs/CaseManagement-Generic/Layouts/layout-edit-Case_layout-Case.json
  Packs/CaseManagement-Generic/Layouts/layout-mobile-Case_layout-Case.json
  Packs/CaseManagement-Generic/Layouts/layout-quickView-Case_layout-Case.json
  Packs/CaseManagement-Generic/Layouts/layoutscontainer-Case_layout.json
  Packs/CaseManagement-Generic/ReleaseNotes/1_1_0.md
  Packs/CaseManagement-Generic/Reports/report-CaseReport.json
  Packs/CaseManagement-Generic/Scripts/AssignToMeButton/AssignToMeButton.yml
  Packs/CaseManagement-Generic/Scripts/GenerateSummaryReportButton/GenerateSummaryReportButton.yml
  Packs/CaseManagement-Generic/Scripts/LinkIncidentsButton/LinkIncidentsButton.yml
  Packs/CaseManagement-Generic/Scripts/TimersOnOwnerChange/TimersOnOwnerChange.yml
  Packs/CaseManagement-Generic/Widgets/widget-Mean_Time_To_Remediation_SLA.json
  Packs/CaseManagement-Generic/Widgets/widget-My_Incidents_by_Type.json
  Packs/CaseManagement-Generic/Widgets/widget-My_Mean_Time_To_Remediation_SLA.json
  Packs/CaseManagement-Generic/Widgets/widget-Participating_Incidents.json
  Packs/CaseManagement-Generic/Widgets/widget-Participating_Incidents_Count.json
  Packs/CaseManagement-Generic/Widgets/widget-Time_To_Assignment.json
  Packs/CaseManagement-Generic/pack_metadata.json
Labels: docs-approved

#9330 [code42-363] remove-using-statements-from-test-playbook
  Packs/Code42/Integrations/Code42/Code42.yml
  Packs/Code42/ReleaseNotes/2_0_6.md
  Packs/Code42/TestPlaybooks/playbook-Code42-Test.yml
  Packs/Code42/pack_metadata.json
Labels: Contribution

#9430 defaultValue is changed to default = false
  Packs/CommonScripts/ReleaseNotes/1_2_56.md
  Packs/CommonScripts/Scripts/SetIfEmpty/SetIfEmpty.yml
  Packs/CommonScripts/pack_metadata.json
Labels: docs-approved

#9424 changing *DBotPreProcessTextData* to python3
  Packs/Base/ReleaseNotes/1_3_17.md
  Packs/Base/Scripts/DBotPreprocessTextData/DBotPreprocessTextData.py
  Packs/Base/Scripts/DBotPreprocessTextData/DBotPreprocessTextData.yml
  Packs/Base/Scripts/DBotPreprocessTextData/dbot_preprocess_text_data_test.py
  Packs/Base/pack_metadata.json
Labels: docs-approved

#9429 [RiskIQ-127] RiskIQ PassiveTotal Enhancement Script README change
  Packs/PassiveTotal/ReleaseNotes/2_0_4.md
  Packs/PassiveTotal/Scripts/RiskIQPassiveTotalSSLScript/README.md
  Packs/PassiveTotal/Scripts/RiskIQPassiveTotalSSLScript/RiskIQPassiveTotalSSLScript.yml
  Packs/PassiveTotal/pack_metadata.json
Labels: Contribution, docs-approved

#9421 add node modules setup to .bootstrap
  .hooks/bootstrap
Labels: docs-approved

#9438 removed code42
  Tests/conf.json
Labels: docs-approved

#9400 FireEye feed token timeout fix
  Packs/FeedFireEye/Integrations/FeedFireEye/FeedFireEye.py
  Packs/FeedFireEye/Integrations/FeedFireEye/FeedFireEye.yml
  Packs/FeedFireEye/ReleaseNotes/1_0_2.md
  Packs/FeedFireEye/pack_metadata.json
Labels: docs-approved

#9404 added : except ValueError in the right place in order to show a relev…
  Packs/SentinelOne/Integrations/SentinelOne-V2/SentinelOne-V2.py
  Packs/SentinelOne/Integrations/SentinelOne-V2/SentinelOne-V2.yml
  Packs/SentinelOne/ReleaseNotes/1_0_2.md
  Packs/SentinelOne/pack_metadata.json
Labels: docs-approved, release-notes-only

#9350 Proof point threat response
  Packs/ProofpointThreatResponse/Integrations/ProofpointThreatResponse/ProofpointThreatResponse.py
  Packs/ProofpointThreatResponse/ReleaseNotes/1_0_2.md
  Packs/ProofpointThreatResponse/pack_metadata.json
Labels: docs-approved, release-notes-only

#9340 IsInternalDomain - added new script
  Packs/CommonScripts/ReleaseNotes/1_2_57.md
  Packs/CommonScripts/Scripts/IsInternalDomainName/IsInternalDomainName.py
  Packs/CommonScripts/Scripts/IsInternalDomainName/IsInternalDomainName.yml
  Packs/CommonScripts/Scripts/IsInternalDomainName/IsInternalDomainName_test.py
  Packs/CommonScripts/pack_metadata.json
Labels: docs-approved

#9408 Add Alexa Benign Parameter for Good Domains
  Packs/Alexa/Integrations/Alexa/Alexa.py
  Packs/Alexa/Integrations/Alexa/Alexa.yml
  Packs/Alexa/ReleaseNotes/1_1_0.md
  Packs/Alexa/pack_metadata.json
Labels: Contribution, docs-approved

#9440 VxStream Test - remove check for totals VMs
  Packs/CrowdStrikeFalconSandbox/TestPlaybooks/playbook-VxStream_Test.yml
Labels: docs-approved

#9462 bump content version
  .circleci/config.yml
Labels: docs-approved

#9460 cyberark: readme update (link to creds article)
  Packs/cyberark_AIM/Integrations/CyberArkAIM_v2/README.md
Labels: docs-approved

#9409 Vertex Synapse Integration
  Packs/Synapse/.pack-ignore
  Packs/Synapse/.secrets-ignore
  Packs/Synapse/Integrations/Synapse/Pipfile
  Packs/Synapse/Integrations/Synapse/Pipfile.lock
  Packs/Synapse/Integrations/Synapse/README.md
  Packs/Synapse/Integrations/Synapse/Synapse.py
  Packs/Synapse/Integrations/Synapse/Synapse.yml
  Packs/Synapse/Integrations/Synapse/Synapse_description.md
  Packs/Synapse/Integrations/Synapse/Synapse_image.png
  Packs/Synapse/Integrations/Synapse/Synapse_test.py
  Packs/Synapse/Integrations/Synapse/command_examples.txt
  Packs/Synapse/Integrations/Synapse/test_data/add_role.json
  Packs/Synapse/Integrations/Synapse/test_data/add_user.json
  Packs/Synapse/Integrations/Synapse/test_data/grant_role.json
  Packs/Synapse/Integrations/Synapse/test_data/list_roles.json
  Packs/Synapse/Integrations/Synapse/test_data/list_users.json
  Packs/Synapse/Integrations/Synapse/test_data/query_model.json
  Packs/Synapse/README.md
  Packs/Synapse/pack_metadata.json
Labels: Contribution, docs-approved

#9455 release notes generator - add white spaces between entities of 2 words
  Tests/scripts/infrastructure_tests/release_notes_generator_test.py
  Utils/release_notes_generator.py
Labels: docs-approved

#9356 Improved file handling in mirror command
  Packs/ServiceNow/Integrations/ServiceNowv2/ServiceNowv2.py
  Packs/ServiceNow/Integrations/ServiceNowv2/ServiceNowv2.yml
  Packs/ServiceNow/Integrations/ServiceNowv2/ServiceNowv2_test.py
  Packs/ServiceNow/Integrations/ServiceNowv2/test_data/response_constants.py
  Packs/ServiceNow/ReleaseNotes/1_3_7.md
  Packs/ServiceNow/pack_metadata.json
Labels: docs-approved, release-notes-only

#8659 Hatching Triage Integration
  Packs/HatchingTriage/.gitignore
  Packs/HatchingTriage/.pack-ignore
  Packs/HatchingTriage/.secrets-ignore
  Packs/HatchingTriage/Integrations/HatchingTriage/HatchingTriage.py
  Packs/HatchingTriage/Integrations/HatchingTriage/HatchingTriage.yml
  Packs/HatchingTriage/Integrations/HatchingTriage/HatchingTriage_description.md
  Packs/HatchingTriage/Integrations/HatchingTriage/HatchingTriage_image.png
  Packs/HatchingTriage/Integrations/HatchingTriage/README.md
  Packs/HatchingTriage/README.md
  Packs/HatchingTriage/TestPlaybooks/Hatching_Triage_-_Detonate_File.yml
  Packs/HatchingTriage/pack_metadata.json
  Tests/conf.json
Labels: Contribution, docs-approved, ready-for-instance-test

#9475 Hatching Triage Integration (#8659)
  Packs/HatchingTriage/.gitignore
  Packs/HatchingTriage/.pack-ignore
  Packs/HatchingTriage/.secrets-ignore
  Packs/HatchingTriage/Integrations/HatchingTriage/HatchingTriage.py
  Packs/HatchingTriage/Integrations/HatchingTriage/HatchingTriage.yml
  Packs/HatchingTriage/Integrations/HatchingTriage/HatchingTriage_description.md
  Packs/HatchingTriage/Integrations/HatchingTriage/HatchingTriage_image.png
  Packs/HatchingTriage/Integrations/HatchingTriage/README.md
  Packs/HatchingTriage/README.md
  Packs/HatchingTriage/TestPlaybooks/Hatching_Triage_-_Detonate_File.yml
  Packs/HatchingTriage/pack_metadata.json
  Tests/conf.json
Labels: docs-approved

#9470 Microsoft Graph Device Management - add required permissions and improve params display name
  Packs/MicrosoftGraphDeviceManagement/Integrations/MicrosoftGraphDeviceManagement/MicrosoftGraphDeviceManagement.yml
  Packs/MicrosoftGraphDeviceManagement/Integrations/MicrosoftGraphDeviceManagement/README.md
  Packs/MicrosoftGraphDeviceManagement/ReleaseNotes/1_0_2.md
  Packs/MicrosoftGraphDeviceManagement/pack_metadata.json
Labels: docs-approved

#9418 Update support info for packs
  Packs/BastilleNetworks/Integrations/BastilleNetworks/BastilleNetworks.yml
  Packs/BastilleNetworks/ReleaseNotes/1_0_1.md
  Packs/BastilleNetworks/pack_metadata.json
  Packs/BitDam/ReleaseNotes/1_0_1.md
  Packs/BitDam/pack_metadata.json
  Packs/Claroty/ReleaseNotes/1_0_6.md
  Packs/Claroty/pack_metadata.json
  Packs/CyberTotal/ReleaseNotes/1_0_1.md
  Packs/CyberTotal/pack_metadata.json
  Packs/Polygon/ReleaseNotes/1_0_1.md
  Packs/Polygon/pack_metadata.json
  Packs/SCADAfence_CNM/ReleaseNotes/1_0_2.md
  Packs/SCADAfence_CNM/pack_metadata.json
  Packs/Sixgill-Darkfeed/ReleaseNotes/1_2_1.md
  Packs/Sixgill-Darkfeed/pack_metadata.json
  Packs/Smokescreen_IllusionBLACK/ReleaseNotes/1_0_5.md
  Packs/Smokescreen_IllusionBLACK/pack_metadata.json
Labels: docs-approved

#9479 [Community Contribution] Cisco WebEx Feed
  Packs/CiscoWebExFeed/.pack-ignore
  Packs/CiscoWebExFeed/.secrets-ignore
  Packs/CiscoWebExFeed/Integrations/CiscoWebExFeed/CiscoWebExFeed.py
  Packs/CiscoWebExFeed/Integrations/CiscoWebExFeed/CiscoWebExFeed.yml
  Packs/CiscoWebExFeed/Integrations/CiscoWebExFeed/CiscoWebExFeed_image.png
  Packs/CiscoWebExFeed/Integrations/CiscoWebExFeed/Pipfile
  Packs/CiscoWebExFeed/Integrations/CiscoWebExFeed/Pipfile.lock
  Packs/CiscoWebExFeed/Integrations/CiscoWebExFeed/README.md
  Packs/CiscoWebExFeed/README.md
  Packs/CiscoWebExFeed/pack_metadata.json
Labels: docs-approved

#9459 Google cloud functions
  Packs/GoogleCloudFunctions/.secrets-ignore
  Packs/GoogleCloudFunctions/Integrations/GoogleCloudFunctions/GoogleCloudFunctions.py
  Packs/GoogleCloudFunctions/Integrations/GoogleCloudFunctions/GoogleCloudFunctions.yml
  Packs/GoogleCloudFunctions/Integrations/GoogleCloudFunctions/GoogleCloudFunctions_test.py
  Packs/GoogleCloudFunctions/ReleaseNotes/1_0_1.md
  Packs/GoogleCloudFunctions/pack_metadata.json
Labels: docs-approved, release-notes-only

#9476 sdk release version 1.2.5
  dev-requirements-py3.txt
Labels: docs-approved

#9482 Fixing type error
  Tests/configure_and_test_integration_instances.py
Labels: docs-approved

#9493 deprecate feed
  Packs/FeedFeodoTracker/.pack-ignore
  Packs/FeedFeodoTracker/Integrations/FeedFeodoTrackerHashes/FeedFeodoTrackerHashes.yml
  Packs/FeedFeodoTracker/ReleaseNotes/1_0_2.md
  Packs/FeedFeodoTracker/pack_metadata.json
  Tests/conf.json
Labels: docs-approved

#9472 add illuminate to skipped integrations
  Tests/conf.json
Labels: docs-approved

#9496 Added from version to DNSDB test conf to match the integrations fromv…
  Tests/conf.json
Labels: docs-approved

#9485 Gmail send-mail - Fixed the issue for reports
  Packs/Gmail/Integrations/Gmail/Gmail.py
  Packs/Gmail/Integrations/Gmail/Gmail.yml
  Packs/Gmail/ReleaseNotes/1_0_7.md
  Packs/Gmail/pack_metadata.json
  Tests/conf.json
Labels: docs-approved, release-notes-only

#9497 Fix noncircle test
  Packs/MicrosoftDefenderAdvancedThreatProtection/TestPlaybooks/playbook-Microsoft_Defender_Advanced_Threat_Protection-Test.yml
  dev-requirements-py3.txt
Labels: docs-approved

#9331 CrowdStrike Falcon Streaming v2 - rm 1 min condition for integration context set
  Packs/CrowdStrikeFalconStreamingV2/Integrations/CrowdStrikeFalconStreamingV2/CrowdStrikeFalconStreamingV2.py
  Packs/CrowdStrikeFalconStreamingV2/Integrations/CrowdStrikeFalconStreamingV2/CrowdStrikeFalconStreamingV2.yml
  Packs/CrowdStrikeFalconStreamingV2/ReleaseNotes/1_0_9.md
  Packs/CrowdStrikeFalconStreamingV2/pack_metadata.json
Labels: docs-approved, release-notes-only

#9402 Fix IPv6 regex
  Packs/Base/.secrets-ignore
  Packs/Base/TestPlaybooks/playbook-Indicators-reputation-.json-Test.yml
  Packs/CommonScripts/ReleaseNotes/1_2_60.md
  Packs/CommonScripts/Scripts/script-UnEscapeIndicatorIPv6.yml
  Packs/CommonScripts/pack_metadata.json
  Packs/CommonTypes/IndicatorTypes/reputation-ipv6.json
  Packs/CommonTypes/ReleaseNotes/2_0_2.md
  Packs/CommonTypes/pack_metadata.json
Labels: bug, docs-approved

#9355 [expanse-272] Domain command fix
  Packs/Expanse/Integrations/Expanse/Expanse.py
  Packs/Expanse/Integrations/Expanse/Expanse.yml
  Packs/Expanse/Integrations/Expanse/Expanse_test.py
  Packs/Expanse/ReleaseNotes/1_1_3.md
  Packs/Expanse/pack_metadata.json
Labels: Contribution

#9474 Phishing preprocessing rule
  Packs/Phishing/ReleaseNotes/1_10_5.md
  Packs/Phishing/Scripts/PhishingDedupPreprocessingRule/PhishingDedupPreprocessingRule.py
  Packs/Phishing/Scripts/PhishingDedupPreprocessingRule/PhishingDedupPreprocessingRule.yml
  Packs/Phishing/Scripts/PhishingDedupPreprocessingRule/PhishingDedupPreprocessingRule_test.py
  Packs/Phishing/pack_metadata.json
Labels: docs-approved

#9489 Boilerplate Content Pack
  Packs/StarterPack/.pack-ignore
  Packs/StarterPack/.secrets-ignore
  Packs/StarterPack/Integrations/BaseIntegration/.Dockerfile
  Packs/StarterPack/Integrations/BaseIntegration/BaseIntegration.py
  Packs/StarterPack/Integrations/BaseIntegration/BaseIntegration.yml
  Packs/StarterPack/Integrations/BaseIntegration/BaseIntegration_description.md
  Packs/StarterPack/Integrations/BaseIntegration/BaseIntegration_image.png
  Packs/StarterPack/Integrations/BaseIntegration/BaseIntegration_test.py
  Packs/StarterPack/Integrations/BaseIntegration/Pipfile
  Packs/StarterPack/Integrations/BaseIntegration/Pipfile.lock
  Packs/StarterPack/Integrations/BaseIntegration/README.md
  Packs/StarterPack/Integrations/BaseIntegration/command_examples
  Packs/StarterPack/Integrations/BaseIntegration/test_data/baseintegration-dummy.json
  Packs/StarterPack/README.md
  Packs/StarterPack/Scripts/BaseScript/BaseScript.py
  Packs/StarterPack/Scripts/BaseScript/BaseScript.yml
  Packs/StarterPack/Scripts/BaseScript/BaseScript_test.py
  Packs/StarterPack/Scripts/BaseScript/test_data/basescript-dummy.json
  Packs/StarterPack/Scripts/README.md
  Packs/StarterPack/pack_metadata.json
Labels: Contribution
