Repository demisto/content, pull requests merged in 2020-03, with the labels that each got.

#5829 updated deviceName as optional graph
  IncidentFields/incidentfield-Device_Name.json
  IncidentFields/incidentfield-Device_Name_CHANGELOG.md
Labels: docs-approved, release-notes-only

#5678 QRadar hunting V2 fix
  Playbooks/playbook-QRadar_Indicator_Hunting_V2.yml
  Playbooks/playbook-QRadar_Indicator_Hunting_V2_CHANGELOG.md
Labels: docs-approved

#5892 Cyberark fetch creds display
  Integrations/integration-cyberark_AIM.yml
  Integrations/integration-cyberark_AIM_CHANGELOG.md
Labels: docs-approved, release-notes-only

#5860 AbuseIPDB fixed ip reputation command
  Integrations/AbuseDB/AbuseDB.py
  Integrations/AbuseDB/CHANGELOG.md
Labels: docs-approved

#5562 Added rewrite and !cve command for CVE-Search
  Integrations/integration-CveInfo.yml
  Packs/CVESearchV2/.pack-ignore
  Packs/CVESearchV2/.secrets-ignore
  Packs/CVESearchV2/Integrations/CVESearchV2/CVESearchV2.py
  Packs/CVESearchV2/Integrations/CVESearchV2/CVESearchV2.yml
  Packs/CVESearchV2/Integrations/CVESearchV2/CVESearchV2_description.md
  Packs/CVESearchV2/Integrations/CVESearchV2/CVESearchV2_image.png
  Packs/CVESearchV2/Integrations/CVESearchV2/CVESearchV2_test.py
  Packs/CVESearchV2/Integrations/CVESearchV2/Pipfile
  Packs/CVESearchV2/Integrations/CVESearchV2/Pipfile.lock
  Packs/CVESearchV2/README.md
  Packs/CVESearchV2/TestPlaybooks/playbook-CVE-Search-Test.yml
  Packs/CVESearchV2/metadata.json
  Tests/conf.json
Labels: docs-approved

#5898 Fix GetDuplicatesMLv2 script
  Scripts/GetDuplicatesMlv2/CHANGELOG.md
  Scripts/GetDuplicatesMlv2/GetDuplicatesMlv2.py
  Scripts/GetDuplicatesMlv2/GetDuplicatesMlv2.yml
Labels: docs-approved

#5896 TAXII Server - apply fixes for outbound feeds
  Packs/TAXIIServer/Integrations/TAXIIServer/CHANGELOG.md
  Packs/TAXIIServer/Integrations/TAXIIServer/TAXIIServer.py
  Packs/TAXIIServer/Integrations/TAXIIServer/TAXIIServer.yml
  Packs/TAXIIServer/Integrations/TAXIIServer/TAXIIServer_description.md
Labels: docs-approved

#5756 New playbook - Kenna vulnerability handling
  Playbooks/playbook-Kenna_-_Vulnerability_Handling.yml
Labels: docs-approved

#5822 fix proxy ignore. fix chrome driver log file. add debug-mode option
  Integrations/rasterize/CHANGELOG.md
  Integrations/rasterize/rasterize.py
  Integrations/rasterize/rasterize_description.md
  Tests/conf.json
  Tests/test_integration.py
  Tests/test_utils.py
Labels: docs-approved

#5811 Added new Default playbook starting in 5.0
  Playbooks/playbook-Default_5.0.yml
  Playbooks/playbook-Default_5.0_CHANGELOG.md
  Playbooks/playbook-default.yml
  Playbooks/playbook-default_CHANGELOG.md
  TestPlaybooks/playbook-Default_5.0_-_Test.yml
  Tests/conf.json
  Tests/secrets_white_list.json
Labels: docs-approved

#5564 Changed ML field associations to be associated with Phishing
  IncidentFields/incidentfield-dbotprediction.json
  IncidentFields/incidentfield-dbotprediction_CHANGELOG.md
  IncidentFields/incidentfield-dbotpredictionprobability.json
  IncidentFields/incidentfield-dbotpredictionprobability_CHANGELOG.md
Labels: docs-approved, release-notes-only

#5902 Remove duplicate Key from TrendMicroDSM integration yml
  Integrations/integration-trendMicroDsm.yml
  Integrations/integration-trendMicroDsm_CHANGELOG.md
Labels: docs-approved

#5868 Added a check that prevents empty email addresses from being enriched.
  Playbooks/playbook-Email_Address_Enrichment_-_Generic_v2.1.yml
  Playbooks/playbook-Email_Address_Enrichment_-_Generic_v2.1_CHANGELOG.md
Labels: docs-approved, release-notes-only

#5909 Microsoft Graph User - Test fix
  TestPlaybooks/playbook-Microsoft_Graph_User_test.yml
Labels: docs-approved

#5910 update lgtm to exclude polluting import
  .lgtm.yaml
Labels: docs-approved

#5793 Get incidents by query enhancement
  Scripts/GetIncidentsByQuery/CHANGELOG.md
  Scripts/GetIncidentsByQuery/GetIncidentsByQuery.py
  Scripts/GetIncidentsByQuery/GetIncidentsByQuery.yml
  Scripts/GetIncidentsByQuery/get_incidents_by_query_test.py
Labels: docs-approved

#5817 Fix netwitness-get-incident for NetWitness 11.4
  Integrations/RSANetWitness_v11_1/CHANGELOG.md
  Integrations/RSANetWitness_v11_1/RSANetWitness_v11_1.py
  Integrations/RSANetWitness_v11_1/RSANetWitness_v11_1_test.py
Labels: Contribution, docs-approved, release-notes-only

#5841 Package CloudTrail plus standardisation and Auto Remediation Playbooks
  Integrations/AWS-CloudTrail/AWS-CloudTrail.py
  Integrations/AWS-CloudTrail/AWS-CloudTrail.yml
  Integrations/AWS-CloudTrail/AWS-CloudTrail_description.md
  Integrations/AWS-CloudTrail/AWS-CloudTrail_image.png
  Integrations/AWS-CloudTrail/CHANGELOG.md
  Integrations/integration-AWS-CloudTrail.yml
  Playbooks/playbook-PCR_-_AWS_CloudTrail_Integrated_CloudWatchLogs.yml
  Playbooks/playbook-PCR_-_AWS_CloudTrail_Misconfig.yml
  Playbooks/playbook-PCR_-_AWS_CloudTrail_Trail_Misconfig.yml
Labels: docs-approved

#5833 Lastline fix
  Integrations/Lastline_v2/CHANGELOG.md
  Integrations/Lastline_v2/Lastline_v2.py
  Integrations/Lastline_v2/Lastline_v2.yml
  Integrations/Lastline_v2/Lastline_v2_description.md
  Integrations/Lastline_v2/README.md
  Integrations/integration-Lastline.yml
  Integrations/integration-Lastline_CHANGELOG.md
  Tests/secrets_white_list.json
Labels: docs-approved

#5915 Skipping failing tests
  Tests/conf.json
Labels: docs-approved

#5916 unskipped vulnDB test
  Tests/conf.json
Labels: docs-approved

#5895 sub_service_to_feed_service
  IndicatorFields/incidentfield-subfeed.json
  IndicatorFields/incidentfield-subfeed_CHANGELOG.md
Labels: docs-approved

#5925 apdate the date of start
  TestPlaybooks/playbook-SplunkPy-Test-V2.yml
Labels: docs-approved

#5927 Skiping SecBI
  Tests/conf.json
Labels: docs-approved

#5900 Added relevant indicator types to indicator fields
  IndicatorFields/incidentfield-adminemail.json
  IndicatorFields/incidentfield-adminemail_CHANGELOG.md
  IndicatorFields/incidentfield-asn.json
  IndicatorFields/incidentfield-asn_CHANGELOG.md
  IndicatorFields/incidentfield-geocountry.json
  IndicatorFields/incidentfield-geocountry_CHANGELOG.md
  IndicatorFields/incidentfield-geolocation.json
  IndicatorFields/incidentfield-geolocation_CHANGELOG.md
  IndicatorFields/incidentfield-internal.json
  IndicatorFields/incidentfield-internal_CHANGELOG.md
  IndicatorFields/incidentfield-registrantcountry.json
  IndicatorFields/incidentfield-registrantcountry_CHANGELOG.md
  IndicatorFields/incidentfield-registrantemail.json
  IndicatorFields/incidentfield-registrantemail_CHANGELOG.md
  IndicatorFields/incidentfield-registrantname.json
  IndicatorFields/incidentfield-registrantname_CHANGELOG.md
  IndicatorFields/incidentfield-registrantphone.json
  IndicatorFields/incidentfield-registrantphone_CHANGELOG.md
  IndicatorFields/incidentfield-registrarabuseemail.json
  IndicatorFields/incidentfield-registrarabuseemail_CHANGELOG.md
  IndicatorFields/incidentfield-registrarabusephone.json
  IndicatorFields/incidentfield-registrarabusephone_CHANGELOG.md
  IndicatorFields/incidentfield-registrarname.json
  IndicatorFields/incidentfield-registrarname_CHANGELOG.md
Labels: docs-approved, release-notes-only

#5849 add encodeing
  Scripts/CommonServerPython/CHANGELOG.md
  Scripts/CommonServerPython/CommonServerPython.py
  Scripts/CommonServerPython/CommonServerPython_test.py
Labels: docs-approved, release-notes-only

#5907 Collect beta release notes
  .circleci/config.yml
  Misc/reputation-account_CHANGELOG.md
  Misc/reputation-host_CHANGELOG.md
  Misc/reputation-registryKey_CHANGELOG.md
  Packs/FeedAlienVault/Integrations/FeedAlienVaultReputation/CHANGELOG.md
  Packs/FeedAzure/Integrations/FeedAzure/CHANGELOG.md
  Packs/FeedCSV/Integrations/FeedCSV/CHANGELOG.md
  Packs/FeedOffice365/Integrations/FeedOffice365/CHANGELOG.md
  copy_beta.py
  release_notes.py
Labels: docs-approved

#5924 Fixed failed test
  TestPlaybooks/playbook-DuoAdminaAPITest.yml
  Tests/conf.json
Labels: docs-approved

#5914 add prints for succeeded instances, refactor to use prints_manager only
  Tests/configure_and_test_integration_instances.py
Labels: docs-approved

#5904 supporting bool variable for training phishing classifier
  Scripts/DBotTrainTextClassifierV2/CHANGELOG.md
  Scripts/DBotTrainTextClassifierV2/DBotTrainTextClassifierV2.py
Labels: docs-approved, release-notes-only

#5934 cortex out of skipped
  Tests/conf.json
Labels: docs-approved

#5704 Djmasters tm apex
  Integrations/TrendMicroApex/TrendMicroApex.py
  Integrations/TrendMicroApex/TrendMicroApex.yml
  Integrations/TrendMicroApex/TrendMicroApex_image.png
Labels: Contribution, docs-approved

#5204 Upgrade specific v1 API calls to v2
  Integrations/integration-Carbon_Black_Enterprise_Response.yml
  Integrations/integration-Carbon_Black_Enterprise_Response_CHANGELOG.md
Labels: Contribution

#5901 Added recorded future evidence details indicator field
  Packs/FeedRecordedFuture/IndicatorFields/incidentfield-recordedfutureevidencedetails.json
Labels: docs-approved

#5783 Fix Whois Test
  Integrations/Whois/Whois.py
  TestPlaybooks/playbook-Whois-Test.yml
  Tests/conf.json
Labels: docs-approved

#5933 [expanse-272] Expanse Expander bugfix in auth
  Packs/Expanse/Integrations/Expanse/CHANGELOG.md
  Packs/Expanse/Integrations/Expanse/Expanse.py
  Packs/Expanse/Integrations/Expanse/Expanse.yml
  Packs/Expanse/metadata.json
Labels: Contribution, docs-approved, release-notes-only

#5951 Removed test_module from cvesearch unittesting
  Packs/CVESearchV2/Integrations/CVESearchV2/CVESearchV2_test.py
Labels: docs-approved

#5939 Added getLicenseID script
  Packs/GetLicenseID/.pack-ignore
  Packs/GetLicenseID/.secrets-ignore
  Packs/GetLicenseID/README.md
  Packs/GetLicenseID/Scripts/GetLicenseID/GetLicenseID.py
  Packs/GetLicenseID/Scripts/GetLicenseID/GetLicenseID.yml
  Packs/GetLicenseID/Scripts/GetLicenseID/GetLicenseID_test.py
  Packs/GetLicenseID/metadata.json
  Tests/demistomock/demistomock.py
Labels: docs-approved

#5883 Fixing splunk test module
  Integrations/SplunkPy/CHANGELOG.md
  Integrations/SplunkPy/SplunkPy.py
Labels: docs-approved, release-notes-only

#5946 Update aws-table-to-markdown
  Scripts/CommonServerPython/CommonServerPython.py
Labels: docs-approved

#5949 cortex integration & hunting pb to skipped
  Tests/conf.json
Labels: docs-approved

#5752 Packgify MAR
  Packs/McAfee-MAR/.secrets-ignore
  Packs/McAfee-MAR/CHANGELOG.md
  Packs/McAfee-MAR/McAfee-MAR.py
  Packs/McAfee-MAR/McAfee-MAR.yml
  Packs/McAfee-MAR/McAfee-MAR_description.md
  Packs/McAfee-MAR/McAfee-MAR_image.png
  Packs/McAfee-MAR/Pipfile
  Packs/McAfee-MAR/Pipfile.lock
  Tests/conf.json
Labels: docs-approved

#5908 fix-xdr-playbook
  Packs/CortexXDR/TestPlaybooks/playbook-Cortex_XDR.yml
Labels: docs-approved

#5950 update hardening cpu check
  Scripts/DockerHardeningCheck/CHANGELOG.md
  Scripts/DockerHardeningCheck/DockerHardeningCheck.py
  Scripts/DockerHardeningCheck/DockerHardeningCheck.yml
Labels: docs-approved, release-notes-only

#5965 Nightly failures
  Tests/conf.json
Labels: docs-approved

#5952 Fix find similar incidents
  Scripts/FindSimilarIncidentsV2/CHANGELOG.md
  Scripts/FindSimilarIncidentsV2/FindSimilarIncidentsV2.py
Labels: docs-approved, release-notes-only

#5911 run tests on server version only if content update was successfull
  .circleci/config.yml
  Tests/configure_and_test_integration_instances.py
  Tests/scripts/copy_content_data.sh
  Tests/scripts/run_tests.sh
  Tests/scripts/wait_until_server_ready.py
Labels: docs-approved

#5913 PANOS EDL Enhancements
  Integrations/EDL/CHANGELOG.md
  Integrations/EDL/EDL.py
  Integrations/EDL/EDL.yml
  Integrations/EDL/EDL_test.py
  Integrations/EDL/EDL_test/TestHelperFunctions/demisto_iocs.json
  Integrations/EDL/EDL_test/TestHelperFunctions/iocs_cache_values_text.json
Labels: docs-approved

#5653 Add comment to pr about skipped integrations
  Tests/test_content.py
Labels: docs-approved

#5253 DynamoDB AWS Codegen Pilot
  Integrations/AWS_DynamoDB/AWS_DynamoDB.py
  Integrations/AWS_DynamoDB/AWS_DynamoDB.yml
  Integrations/AWS_DynamoDB/AWS_DynamoDB_description.md
  Integrations/AWS_DynamoDB/AWS_DynamoDB_image.png
  Integrations/AWS_DynamoDB/AWS_DynamoDB_test.py
  Integrations/AWS_DynamoDB/CHANGELOG.md
  Integrations/AWS_DynamoDB/README.md
  TestPlaybooks/playbook-AWS-DynamoDB-Test.yml
  Tests/conf.json
Labels: docs-approved

#5966 Vulture
  Beta_Integrations/GmailSingleUser/.vulture_whitelist.py
  Beta_Integrations/GmailSingleUser/GmailSingleUser.py
  Beta_Integrations/GmailSingleUser/GmailSingleUser.yml
  Beta_Integrations/GmailSingleUser/GmailSingleUser_CHANGELOG.md
  Integrations/Digital_Defense_FrontlineVM/.vulture_whitelist.py
  Integrations/Digital_Defense_FrontlineVM/CHANGELOG.md
  Integrations/Digital_Defense_FrontlineVM/Digital_Defense_FrontlineVM.yml
  dev-requirements-py2.txt
  dev-requirements-py3.txt
Labels: docs-approved

#5867 adding url params support and offset to Export Indicators
  Packs/ExportIndicators/.secrets-ignore
  Packs/ExportIndicators/Integrations/ExportIndicators/CHANGELOG.md
  Packs/ExportIndicators/Integrations/ExportIndicators/ExportIndicators.py
  Packs/ExportIndicators/Integrations/ExportIndicators/ExportIndicators.yml
  Packs/ExportIndicators/Integrations/ExportIndicators/ExportIndicators_description.md
  Packs/ExportIndicators/Integrations/ExportIndicators/ExportIndicators_test.py
  Packs/ExportIndicators/Integrations/ExportIndicators/README.md
Labels: docs-approved

#5788 alien vault otx taxii feed
  Packs/FeedAlienVault/.secrets-ignore
  Packs/FeedAlienVault/Integrations/FeedAlienVaultOTXTaxii/FeedAlienVaultOTXTaxii.py
  Packs/FeedAlienVault/Integrations/FeedAlienVaultOTXTaxii/FeedAlienVaultOTXTaxii.yml
  Packs/FeedAlienVault/Integrations/FeedAlienVaultOTXTaxii/FeedAlienVaultOTXTaxii_description.md
  Packs/FeedAlienVault/Integrations/FeedAlienVaultOTXTaxii/FeedAlienVaultOTXTaxii_image.png
  Packs/FeedAlienVault/Integrations/FeedAlienVaultOTXTaxii/FeedAlienVaultOTXTaxii_test.py
  Packs/FeedAlienVault/TestPlaybooks/playbook-feedalienvaultotx_test.yml
  Tests/conf.json
Labels: docs-approved

#5969 [Test Failure Fix] Carbon Black Enterprise Protection V2
  TestPlaybooks/playbook-CarbonBlackProtectV2-test.yml
  Tests/conf.json
  Tests/secrets_white_list.json
Labels: docs-approved

#5708 [Documentation] FireEye Helix
  Integrations/FireEyeHelix/README.md
  Tests/secrets_white_list.json
Labels: docs-approved

#5972 Refactored metadata.json in content pack
  Packs/GetLicenseID/metadata.json
  Packs/GetLicenseID/pack_metadata.json
Labels: docs-approved

#5944 Plain text generic feed integration
  Integrations/EDL/EDL.yml
  Packs/ApiModules/.secrets-ignore
  Packs/ApiModules/Scripts/HTTPFeedApiModule/CHANGELOG.md
  Packs/ApiModules/Scripts/HTTPFeedApiModule/HTTPFeedApiModule.py
  Packs/ApiModules/Scripts/HTTPFeedApiModule/HTTPFeedApiModule_test.py
  Packs/ApiModules/metadata.json
  Packs/FeedPlainText/.pack-ignore
  Packs/FeedPlainText/.secrets-ignore
  Packs/FeedPlainText/Integrations/FeedPlainText/FeedPlainText.py
  Packs/FeedPlainText/Integrations/FeedPlainText/FeedPlainText.yml
  Packs/FeedPlainText/Integrations/FeedPlainText/FeedPlainText_description.md
  Packs/FeedPlainText/Integrations/FeedPlainText/FeedPlainText_image.png
  Packs/FeedPlainText/Integrations/FeedPlainText/Pipfile
  Packs/FeedPlainText/Integrations/FeedPlainText/Pipfile.lock
  Packs/FeedPlainText/Integrations/FeedPlainText/README.md
  Packs/FeedPlainText/README.md
  Packs/FeedPlainText/TestPlaybooks/playbook-PlainText_Feed_Test.yml
  Packs/FeedPlainText/metadata.json
  Tests/conf.json
Labels: docs-approved

#5973 Fix Vulture reports in integrations
  Integrations/FireEyeHelix/FireEyeHelix.py
  Integrations/FireEyeHelix/FireEyeHelix.yml
  Integrations/GoogleCloudCompute/CHANGELOG.md
  Integrations/GoogleCloudCompute/GoogleCloudCompute.py
  Integrations/GoogleCloudCompute/GoogleCloudCompute.yml
  Integrations/MISP_V2/CHANGELOG.md
  Integrations/MISP_V2/MISP_V2.py
  Integrations/MISP_V2/MISP_V2.yml
  Integrations/Palo_Alto_Networks_WildFire_v2/CHANGELOG.md
  Integrations/Palo_Alto_Networks_WildFire_v2/Palo_Alto_Networks_WildFire_v2.py
  Integrations/Panorama/CHANGELOG.md
  Integrations/Panorama/Panorama.py
  Integrations/RedCanary/CHANGELOG.md
  Integrations/RedCanary/RedCanary.py
  Integrations/RedCanary/RedCanary.yml
  Integrations/Stealthwatch_Cloud/CHANGELOG.md
  Integrations/Stealthwatch_Cloud/Stealthwatch_Cloud.py
  Integrations/TruSTAR/CHANGELOG.md
  Integrations/TruSTAR/TruSTAR.py
  Integrations/TruSTAR/TruSTAR.yml
  Integrations/cisco-ise/CHANGELOG.md
  Integrations/cisco-ise/cisco-ise.py
  Scripts/DBotPredictOutOfTheBox/CHANGELOG.md
  Scripts/DBotPredictOutOfTheBox/DBotPredictOutOfTheBox.py
Labels: docs-approved

#5974 Fix Whois Test Playbook
  TestPlaybooks/playbook-Whois-Test.yml
Labels: docs-approved

#5968 Skip Ipstack
  Tests/conf.json
Labels: docs-approved

#5981 HTTP feed - Fix test module
  Packs/ApiModules/Scripts/HTTPFeedApiModule/HTTPFeedApiModule.py
Labels: docs-approved

#5978 recorded future feed - vulture - rm kwargs
  Packs/FeedRecordedFuture/Integrations/FeedRecordedFuture/CHANGELOG.md
  Packs/FeedRecordedFuture/Integrations/FeedRecordedFuture/FeedRecordedFuture.py
  Packs/FeedRecordedFuture/Integrations/FeedRecordedFuture/FeedRecordedFuture.yml
  Tests/conf.json
Labels: docs-approved

#5967 Fix read pdf file v2
  Scripts/ReadPDFFileV2/CHANGELOG.md
  Scripts/ReadPDFFileV2/ReadPDFFileV2.py
  Scripts/ReadPDFFileV2/ReadPDFFileV2_test.py
Labels: bug, docs-approved, release-notes-only

#5980 added name argument for CompleteManualTask script
  TestPlaybooks/playbook-Endpoint_Malware_Investigation_-_Generic_-_Test.yml
  TestPlaybooks/script-CompleteManualTask.yml
Labels: docs-approved

#5985 Archer - fix test
  Tests/conf.json
Labels: docs-approved

#5971 Prevent packs general files collect sample tests
  Tests/scripts/configure_tests.py
  Tests/scripts/constants.py
  Tests/scripts/hook_validations/tests/tests_data/fake_pack/pack_metadata.json
Labels: docs-approved

#5979 [pcysys-771] Bugfix: Date in Full action report was changed, caused a parsing exce…
  Packs/Pcysys/Integrations/Pcysys/CHANGELOG.md
  Packs/Pcysys/Integrations/Pcysys/Pcysys.py
  Packs/Pcysys/Integrations/Pcysys/TestData/mock_csv_file
Labels: Contribution

#5982 Fix alien vault otx context
  Integrations/AlienVault_OTX_v2/AlienVault_OTX_v2.py
  Integrations/AlienVault_OTX_v2/AlienVault_OTX_v2.yml
  Integrations/AlienVault_OTX_v2/CHANGELOG.md
Labels: bug, docs-approved, release-notes-only

#5987 Sdk v0.4.2
  Packs/ApiModules/pack_metadata.json
  Packs/FeedPlainText/pack_metadata.json
  Packs/McAfee-MAR/.pack-ignore
  Packs/McAfee-MAR/.secrets-ignore
  Packs/McAfee-MAR/Integrations/CHANGELOG.md
  Packs/McAfee-MAR/Integrations/McAfee-MAR.py
  Packs/McAfee-MAR/Integrations/McAfee-MAR.yml
  Packs/McAfee-MAR/Integrations/McAfee-MAR_description.md
  Packs/McAfee-MAR/Integrations/McAfee-MAR_image.png
  Packs/McAfee-MAR/Integrations/__init__.py
  Packs/McAfee-MAR/__init__.py
  Packs/McAfee-MAR/pack_metadat.json
  dev-requirements-py3.txt
Labels: docs-approved

#5782 [New Integration] Elasticsearch Feed
  Integrations/Elasticsearch_v2/CHANGELOG.md
  Integrations/Elasticsearch_v2/Elasticsearch_v2.py
  Integrations/Elasticsearch_v2/Elasticsearch_v2.yml
  Integrations/Elasticsearch_v2/Elasticsearch_v2_description.md
  Integrations/Elasticsearch_v2/Elasticsearch_v2_test.py
  Integrations/Elasticsearch_v2_5_5/CHANGELOG.md
  Integrations/Elasticsearch_v2_5_5/Elasticsearch_v2_5_5.py
  Integrations/Elasticsearch_v2_5_5/Elasticsearch_v2_5_5.yml
  Integrations/Elasticsearch_v2_5_5/Elasticsearch_v2_5_5_description.md
  Integrations/Elasticsearch_v2_5_5/Elasticsearch_v2_5_5_test.py
  Packs/FeedElasticsearch/.pack-ignore
  Packs/FeedElasticsearch/.secrets-ignore
  Packs/FeedElasticsearch/Integrations/FeedElasticsearch/CHANGELOG.md
  Packs/FeedElasticsearch/Integrations/FeedElasticsearch/FeedElasticsearch.py
  Packs/FeedElasticsearch/Integrations/FeedElasticsearch/FeedElasticsearch.yml
  Packs/FeedElasticsearch/Integrations/FeedElasticsearch/FeedElasticsearch_description.md
  Packs/FeedElasticsearch/Integrations/FeedElasticsearch/FeedElasticsearch_image.png
  Packs/FeedElasticsearch/Integrations/FeedElasticsearch/FeedElasticsearch_test.py
  Packs/FeedElasticsearch/Integrations/FeedElasticsearch/Pipfile
  Packs/FeedElasticsearch/Integrations/FeedElasticsearch/Pipfile.lock
  Packs/FeedElasticsearch/Integrations/FeedElasticsearch/README.md
  Packs/FeedElasticsearch/README.md
  Packs/FeedElasticsearch/metadata.json
  TestPlaybooks/playbook-Elasticsearch_Fetch_Custom_Indicators_Test.yml
  TestPlaybooks/playbook-Elasticsearch_Fetch_Demisto_Indicators_Test.yml
  Tests/conf.json
Labels: docs-approved

#5994 Fixed typo in pack_metadata.json
  Packs/McAfee-MAR/pack_metadata.json
Labels: docs-approved

#5995 Renamed metadata
  Packs/FeedElasticsearch/pack_metadata.json
Labels: docs-approved

#5424 Content Packs Cloud Storage
  .circleci/config.yml
  Tests/scripts/infrastructure_tests/store_packs_test.py
  Tests/store_packs.py
  Tests/test_utils.py
  dev-requirements-py3.txt
Labels: docs-approved

#5846 Akamai SIEM playbook fix
  TestPlaybooks/playbook-Akamai_WAF_SIEM-Test.yml
  Tests/conf.json
Labels: docs-approved

#5996 [Test Fix] CrowdStrike Falcon
  TestPlaybooks/playbook-CrowdStrikeFalcon-Test-4.0.0.yml
  TestPlaybooks/playbook-CrowdStrikeFalcon-Test.yml
  Tests/conf.json
Labels: docs-approved

#5926 Add example configuration steps to TAXII Feed Documentation
  Integrations/FeedTAXII/FeedTAXII_description.md
  Integrations/FeedTAXII/README.md
Labels: docs-approved

#5998 Fixed an issue with url indicator score
  Integrations/AlienVault_OTX_v2/AlienVault_OTX_v2.py
  Integrations/AlienVault_OTX_v2/CHANGELOG.md
Labels: docs-approved

#5955 Panorama fix
  Integrations/Panorama/CHANGELOG.md
  Integrations/Panorama/Panorama.py
Labels: docs-approved, release-notes-only

#5986 Packify SNOW
  Packs/ServiceNow/.pack-ignore
  Packs/ServiceNow/.secrets-ignore
  Packs/ServiceNow/Integrations/ServiceNow/CHANGELOG.md
  Packs/ServiceNow/Integrations/ServiceNow/ServiceNow.py
  Packs/ServiceNow/Integrations/ServiceNow/ServiceNow.yml
  Packs/ServiceNow/Integrations/ServiceNow/ServiceNow_description.md
  Packs/ServiceNow/Integrations/ServiceNow/ServiceNow_image.png
  Packs/ServiceNow/README.md
  Packs/ServiceNow/pack_metadata.json
Labels: docs-approved

#5859 Fixed Critical Assets v2 structural issue that caused wrong field population
  Playbooks/playbook-Calculate_Severity_-_Critical_Assets_v2.yml
  Playbooks/playbook-Calculate_Severity_-_Critical_Assets_v2_CHANGELOG.md
Labels: docs-approved, release-notes-only

#6001 Impossible traveler pack - fix prices
  Packs/Active_Directory_Query/pack_metadata.json
  Packs/CalculateGeoDistance/pack_metadata.json
  Packs/CalculateTimeDifference/pack_metadata.json
  Packs/ImpossibleTraveler/pack_metadata.json
  Packs/Ipstack/pack_metadata.json
  Packs/ipinfo/pack_metadata.json
  Packs/rasterize/pack_metadata.json
  TestPlaybooks/playbook-DocumentationTest.yml
Labels: docs-approved

#5977 Nightly failures
  Tests/conf.json
Labels: docs-approved

#5593 aws iam user playbooks
  Playbooks/playbook-PCR_-_AWS_IAM_Policy_Misconfig.yml
  Playbooks/playbook-PCR_-_AWS_IAM_Policy_Misconfig_CHANGELOG.md
  Playbooks/playbook-PCR_-_AWS_IAM_User_Policy_Misconfig.yml
Labels: Contribution, docs-approved

#6006 Pack metadata cleanup
  Packs/ActiveMQ/pack_metadata.json
  Packs/Claroty/pack_metadata.json
  Packs/CortexXDR/pack_metadata.json
  Packs/GetLicenseID/pack_metadata.json
  Packs/HelloWorld/pack_metadata.json
  Packs/Indeni/pack_metadata.json
  Packs/McAfee-MAR/pack_metadata.json
  Packs/Pcysys/pack_metadata.json
  Packs/PrismaCloudCompute/pack_metadata.json
  Packs/Sixgill/pack_metadata.json
  Packs/TAXIIServer/pack_metadata.json
  Packs/ThreatIntelligenceManagement/pack_metadata.json
  Packs/XForceExchange/pack_metadata.json
  Packs/Zscaler/pack_metadata.json
Labels: docs-approved

#6002 Metadata parsing fixes
  Tests/scripts/infrastructure_tests/store_packs_test.py
  Tests/store_packs.py
Labels: docs-approved

#6009 bump to 20.3.2
  .circleci/config.yml
Labels: docs-approved

#5541 powershell common
  .gitignore
  Packs/Base/.secrets-ignore
  Packs/Base/Scripts/CommonServerPowerShell/CHANGELOG.md
  Packs/Base/Scripts/CommonServerPowerShell/CommonServerPowerShell.Tests.ps1
  Packs/Base/Scripts/CommonServerPowerShell/CommonServerPowerShell.ps1
  Packs/Base/Scripts/CommonServerPowerShell/CommonServerPowerShell.yml
  Packs/Base/TestPlaybooks/playbook-PowerShellCommon-Test.yml
  Scripts/VerifyJSON/CHANGELOG.md
  Scripts/VerifyJSON/VerifyJSON.Tests.ps1
  Scripts/VerifyJSON/VerifyJSON.ps1
  Scripts/VerifyJSON/VerifyJSON.yml
  Scripts/VerifyJSON/VerifyJSON_description.md
  TestPlaybooks/playbook-VerifyJSON_-_Test.yml
  TestPlaybooks/script-PwshInvokeExpression.yml
  Tests/conf.json
  Tests/demistomock/demistomock.ps1
  Tests/secrets_white_list.json
  dev-requirements-py3.txt
Labels: docs-approved

#6008 Update integration logos
  Beta_Integrations/MailListener_-_POP3/CHANGELOG.md
  Beta_Integrations/MailListener_-_POP3/MailListener_-_POP3_image.png
  Beta_Integrations/PaloAlto_TrapsESM_Beta/PaloAlto_TrapsESM_Beta.png
  Integrations/AutofocusV2/AutofocusV2_image.png
  Integrations/BPA/BPA_image.png
  Integrations/BPA/CHANGELOG.md
  Integrations/EDL/EDL_image.png
  Integrations/ImageOCR/CHANGELOG.md
  Integrations/ImageOCR/ImageOCR_image.png
  Integrations/MailSenderNew/CHANGELOG.md
  Integrations/MailSenderNew/MailSenderNew_image.png
  Integrations/OnboardingIntegration/CHANGELOG.md
  Integrations/OnboardingIntegration/OnboardingIntegration_image.png
  Integrations/PaloAltoNetworks_PAN_OS_EDL_Management/CHANGELOG.md
  Integrations/PaloAltoNetworks_PAN_OS_EDL_Management/PaloAltoNetworks_PAN_OS_EDL_Management_image.png
  Integrations/PaloAltoNetworks_Traps/CHANGELOG.md
  Integrations/PaloAltoNetworks_Traps/PaloAltoNetworks_Traps_image.png
  Integrations/Palo_Alto_Networks_WildFire_v2/Palo_Alto_Networks_WildFire_v2_image.png
  Integrations/Panorama/Panorama_image.png
  Integrations/SMB/CHANGELOG.md
  Integrations/SMB/SMB_image.png
  Integrations/SMIME_Messaging/CHANGELOG.md
  Integrations/SMIME_Messaging/SMIME_Messaging_image.png
  Integrations/Whois/Whois_image.png
  Integrations/integration-DemistoLocking.yml
  Integrations/integration-DemistoLocking_CHANGELOG.md
  Integrations/integration-DemistoRESTAPI.yml
  Integrations/integration-DemistoRESTAPI_CHANGELOG.md
  Integrations/integration-LightCyberMagna.yml
  Integrations/integration-LightCyberMagna_CHANGELOG.md
  Integrations/integration-WhereIsTheEgg.yml
  Integrations/integration-WhereIsTheEgg_CHANGELOG.md
  Integrations/integration-sampleSiem.yml
  Integrations/rasterize_old/CHANGELOG.md
  Integrations/rasterize_old/rasterize_image.png
  Packs/ExportIndicators/Integrations/ExportIndicators/ExportIndicators_image.png
  Packs/FeedPlainText/Integrations/FeedPlainText/FeedPlainText_image.png
  Packs/ipinfo/Integrations/integration-Ipinfo.yml
  Packs/rasterize/Integrations/rasterize/rasterize_image.png
Labels: docs-approved

#5989 Update sane doc reports automation
  Scripts/SaneDocReport/CHANGELOG.md
  Scripts/SaneDocReportV2/CHANGELOG.md
  Scripts/SaneDocReportV2/SaneDocReportV2.yml
Labels: docs-approved, enhancement

#6015 adding encoding
  Integrations/FireEyeHX/CHANGELOG.md
  Integrations/FireEyeHX/FireEyeHX.py
  Integrations/FireEyeHX/FireEyeHX.yml
Labels: bug, docs-approved, release-notes-only

#6010 Add CommonServer JS to base pack
  Documentation/extract_common_server_js.py
  Packs/Base/.secrets-ignore
  Packs/Base/Scripts/script-CommonServer.yml
  Packs/Base/Scripts/script-CommonServer_CHANGELOG.md
  Packs/Base/TestPlaybooks/playbook-Test_CommonServer.yml
  Tests/scripts/configure_tests.py
Labels: docs-approved

#6012 Pack Cleanup Stage 2
  Packs/ActiveMQ/pack_metadata.json
  Packs/Active_Directory_Query/pack_metadata.json
  Packs/Base/pack_metadata.json
  Packs/CVESearchV2/pack_metadata.json
  Packs/CalculateGeoDistance/pack_metadata.json
  Packs/CalculateTimeDifference/pack_metadata.json
  Packs/CortexXDR/pack_metadata.json
  Packs/Expanse/pack_metadata.json
  Packs/ExportIndicators/pack_metadata.json
  Packs/FeedAWS/pack_metadata.json
  Packs/FeedAlienVault/pack_metadata.json
  Packs/FeedAutofocus/pack_metadata.json
  Packs/FeedAzure/pack_metadata.json
  Packs/FeedBambenekConsulting/pack_metadata.json
  Packs/FeedBlocklist_de/pack_metadata.json
  Packs/FeedBruteForceBlocker/pack_metadata.json
  Packs/FeedCSV/pack_metadata.json
  Packs/FeedCloudflare/pack_metadata.json
  Packs/FeedCofense/pack_metadata.json
  Packs/FeedDShield/pack_metadata.json
  Packs/FeedElasticsearch/pack_metadata.json
  Packs/FeedFastly/pack_metadata.json
  Packs/FeedFeodoTracker/pack_metadata.json
  Packs/FeedMalwareDomainList/pack_metadata.json
  Packs/FeedOffice365/pack_metadata.json
  Packs/FeedPlainText/pack_metadata.json
  Packs/FeedProofpoint/pack_metadata.json
  Packs/FeedRecordedFuture/pack_metadata.json
  Packs/FeedSpamhaus/pack_metadata.json
  Packs/FeedTorExitAddresses/pack_metadata.json
  Packs/Feedsslabusech/pack_metadata.json
  Packs/FetchIndicatorsFromFile/pack_metadata.json
  Packs/GetLicenseID/pack_metadata.json
  Packs/HelloWorld/pack_metadata.json
  Packs/Indeni/pack_metadata.json
  Packs/Ipstack/pack_metadata.json
  Packs/McAfee-MAR/pack_metadata.json
  Packs/Pcysys/pack_metadata.json
  Packs/PrismaCloudCompute/pack_metadata.json
  Packs/ServiceNow/pack_metadata.json
  Packs/TAXIIServer/pack_metadata.json
  Packs/ThreatIntelligenceManagement/pack_metadata.json
  Packs/XForceExchange/pack_metadata.json
  Packs/Zscaler/pack_metadata.json
  Packs/ipinfo/pack_metadata.json
  Packs/rasterize/pack_metadata.json
Labels: docs-approved

#6019 taking out Custom Feed Details field in layout
  Layouts/layout-indicatorsDetails-domain.json
  Layouts/layout-indicatorsDetails-domain_CHANGELOG.md
  Layouts/layout-indicatorsDetails-ip.json
  Layouts/layout-indicatorsDetails-ip_CHANGELOG.md
  Layouts/layout-indicatorsDetails-unifiedFile.json
  Layouts/layout-indicatorsDetails-unifiedFile_CHANGELOG.md
  Layouts/layout-indicatorsDetails-url.json
  Layouts/layout-indicatorsDetails-url_CHANGELOG.md
Labels: docs-approved

#5866 Add domain glob to feeds
  Packs/ApiModules/Scripts/CSVFeedApiModule/CHANGELOG.md
  Packs/ApiModules/Scripts/CSVFeedApiModule/CSVFeedApiModule.py
  Packs/Base/Scripts/CommonServerPython/CommonServerPython.py
  Packs/FeedCofense/Integrations/FeedCofense/CHANGELOG.md
  Packs/FeedCofense/Integrations/FeedCofense/FeedCofense.py
  Packs/FeedCofense/Integrations/FeedCofense/FeedCofense.yml
  Packs/FeedCofense/Integrations/FeedCofense/FeedCofense_test.py
  Packs/FeedCofense/Integrations/FeedCofense/TestData/search_output.json
  Packs/FeedOffice365/Integrations/FeedOffice365/CHANGELOG.md
  Packs/FeedOffice365/Integrations/FeedOffice365/FeedOffice365.py
  Packs/FeedOffice365/Integrations/FeedOffice365/FeedOffice365.yml
  Packs/FeedOffice365/Integrations/FeedOffice365/FeedOffice365_test.py
  Packs/FeedOffice365/TestPlaybooks/playbook-Feed_Office365-Test.yml
  Packs/FeedProofpoint/Integrations/FeedProofpoint/CHANGELOG.md
  Packs/FeedProofpoint/Integrations/FeedProofpoint/FeedProofpoint.py
  Packs/FeedProofpoint/Integrations/FeedProofpoint/FeedProofpoint.yml
  Packs/FeedProofpoint/Integrations/FeedProofpoint/FeedProofpoint_test.py
  Packs/FeedProofpoint/Integrations/FeedProofpoint/TestData/detalied-domainrepdata.txt
  Packs/FeedRecordedFuture/Integrations/FeedRecordedFuture/CHANGELOG.md
  Packs/FeedRecordedFuture/Integrations/FeedRecordedFuture/FeedRecordedFuture.py
  Packs/FeedRecordedFuture/Integrations/FeedRecordedFuture/FeedRecordedFuture_test.py
Labels: docs-approved

#6020 skip xfe
  Tests/conf.json
Labels: docs-approved

#6021 support for skipping py2 setup in bootstrap
  .circleci/config.yml
  .hooks/bootstrap
Labels: docs-approved

#6016 unskipping autofocus
  Integrations/AutofocusV2/AutofocusV2.py
  TestPlaybooks/playbook-AutoFocus_V2_test.yml
  Tests/conf.json
Labels: docs-approved

#5947 EclecticIQ - 2fa update
  Integrations/EclecticIQ/CHANGELOG.md
  Integrations/EclecticIQ/EclecticIQ.py
  Integrations/EclecticIQ/EclecticIQ.yml
  Integrations/EclecticIQ/EclecticIQ_description.md
Labels: Contribution, docs-approved

#6018 Moved google client library to build requirements
  .circleci/build-requirements.txt
  dev-requirements-py3.txt
Labels: docs-approved

#6024 Rename CommonServer references
  Tests/scripts/pkg_dev_test_tasks.py
  Tests/scripts/run_all_pkg_dev_tasks.sh
  Tests/scripts/run_parallel_pkg_dev_tasks.py
  content_creator.py
Labels: docs-approved

#5873 RSA NetWitness Packets and Logs - fix
  Integrations/integration-RsaNetWitnessPacketsAndLogs.yml
  Integrations/integration-RsaNetWitnessPacketsAndLogs_CHANGELOG.md
Labels: docs-approved, release-notes-only

#6029 Pack metadata fixes
  Packs/Active_Directory_Query/pack_metadata.json
  Packs/Base/pack_metadata.json
  Packs/CVESearchV2/pack_metadata.json
  Packs/CalculateGeoDistance/pack_metadata.json
  Packs/CalculateTimeDifference/pack_metadata.json
  Packs/Expanse/pack_metadata.json
  Packs/ExportIndicators/pack_metadata.json
  Packs/FeedAWS/pack_metadata.json
  Packs/FeedAlienVault/pack_metadata.json
  Packs/FeedAutofocus/pack_metadata.json
  Packs/FeedAzure/pack_metadata.json
  Packs/FeedBambenekConsulting/pack_metadata.json
  Packs/FeedBlocklist_de/pack_metadata.json
  Packs/FeedBruteForceBlocker/pack_metadata.json
  Packs/FeedCSV/pack_metadata.json
  Packs/FeedCloudflare/pack_metadata.json
  Packs/FeedCofense/pack_metadata.json
  Packs/FeedDShield/pack_metadata.json
  Packs/FeedElasticsearch/pack_metadata.json
  Packs/FeedFastly/pack_metadata.json
  Packs/FeedFeodoTracker/pack_metadata.json
  Packs/FeedMalwareDomainList/pack_metadata.json
  Packs/FeedOffice365/pack_metadata.json
  Packs/FeedPlainText/pack_metadata.json
  Packs/FeedProofpoint/pack_metadata.json
  Packs/FeedRecordedFuture/pack_metadata.json
  Packs/FeedSpamhaus/pack_metadata.json
  Packs/FeedTorExitAddresses/pack_metadata.json
  Packs/Feedsslabusech/pack_metadata.json
  Packs/FetchIndicatorsFromFile/pack_metadata.json
  Packs/ImpossibleTraveler/pack_metadata.json
  Packs/Ipstack/pack_metadata.json
  Packs/ipinfo/pack_metadata.json
  Packs/rasterize/pack_metadata.json
Labels: docs-approved

#6028 Marketplace - Packs integration images upload
  .circleci/build-requirements.txt
  Tests/scripts/infrastructure_tests/store_packs_test.py
  Tests/store_packs.py
  Tests/test_utils.py
Labels: docs-approved

#5953 Adding context mapping: REF
  Integrations/integration-qualys.yml
  Integrations/integration-qualys_CHANGELOG.md
Labels: bug, docs-approved

#6031 CommonServerPowerShell accept inner context as an object
  Packs/Base/Scripts/CommonServerPowerShell/CommonServerPowerShell.ps1
Labels: docs-approved

#6034 [Build Fix] Fix CircleCI build
  Tests/scripts/wait_until_server_ready.py
Labels: docs-approved

#6026 C2Sec irisk: fixed test button and key error bugs
  Integrations/C2sec/C2sec.py
  Integrations/C2sec/C2sec.yml
  Integrations/C2sec/CHANGELOG.md
Labels: docs-approved, release-notes-only

#6004 Adding url decode
  Integrations/integration-HybridAnalysis.yml
  Integrations/integration-HybridAnalysis_CHANGELOG.md
  TestPlaybooks/playbook-HybridAnalysis-Test.yml
Labels: bug, docs-approved, release-notes-only

#6032 Skipping nightlies failures
  Tests/conf.json
Labels: docs-approved

#5930 Remove port parameter from BPA
  Integrations/BPA/BPA.py
  Integrations/BPA/BPA.yml
  Integrations/BPA/CHANGELOG.md
  Integrations/integration-Incapsula.yml
  Integrations/integration-Incapsula_CHANGELOG.md
  TestPlaybooks/playbook-BPA-test.yml
Labels: docs-approved

#6033 WF TPB - now extraction checks md5 or sha256 due to ioc merging
  TestPlaybooks/playbook-Wildfire_Test.yml
Labels: docs-approved

#5938 Changed Ip fields
  IndicatorFields/incidentfield-adminemail.json
  IndicatorFields/incidentfield-adminemail_CHANGELOG.md
  IndicatorFields/incidentfield-asn.json
  IndicatorFields/incidentfield-asn_CHANGELOG.md
  IndicatorFields/incidentfield-geocountry.json
  IndicatorFields/incidentfield-geocountry_CHANGELOG.md
  IndicatorFields/incidentfield-geolocation.json
  IndicatorFields/incidentfield-geolocation_CHANGELOG.md
  IndicatorFields/incidentfield-internal.json
  IndicatorFields/incidentfield-internal_CHANGELOG.md
  IndicatorFields/incidentfield-registrantcountry.json
  IndicatorFields/incidentfield-registrantcountry_CHANGELOG.md
  IndicatorFields/incidentfield-registrantemail.json
  IndicatorFields/incidentfield-registrantemail_CHANGELOG.md
  IndicatorFields/incidentfield-registrantname.json
  IndicatorFields/incidentfield-registrantname_CHANGELOG.md
  IndicatorFields/incidentfield-registrantphone.json
  IndicatorFields/incidentfield-registrantphone_CHANGELOG.md
  IndicatorFields/incidentfield-registrarabuseemail.json
  IndicatorFields/incidentfield-registrarabuseemail_CHANGELOG.md
  IndicatorFields/incidentfield-registrarabusephone.json
  IndicatorFields/incidentfield-registrarabusephone_CHANGELOG.md
  IndicatorFields/incidentfield-registrarname.json
  IndicatorFields/incidentfield-registrarname_CHANGELOG.md
  Tests/conf.json
Labels: docs-approved, release-notes-only

#5921 [code42-636] Code42 Integration
  Packs/Code42/.pack-ignore
  Packs/Code42/.secrets-ignore
  Packs/Code42/CHANGELOG.md
  Packs/Code42/IncidentFields/incidentfield-Code42_Alert_Type.json
  Packs/Code42/IncidentFields/incidentfield-Code42_File_Events.json
  Packs/Code42/IncidentFields/incidentfield-Exfiltrated_Files.json
  Packs/Code42/IncidentTypes/incidenttype-Code42_Security_Alert.json
  Packs/Code42/Integrations/Code42/Code42.py
  Packs/Code42/Integrations/Code42/Code42.yml
  Packs/Code42/Integrations/Code42/Code42_description.md
  Packs/Code42/Integrations/Code42/Code42_image.png
  Packs/Code42/Integrations/Code42/Code42_test.py
  Packs/Code42/Integrations/Code42/Pipfile
  Packs/Code42/Integrations/Code42/Pipfile.lock
  Packs/Code42/Integrations/Code42/README.md
  Packs/Code42/Integrations/Code42/__init__.py
  Packs/Code42/Layouts/layout-details-Code42_Security_Alert-V2.json
  Packs/Code42/Layouts/layout-details-Code42_Security_Alert-V2_CHANGELOG.md
  Packs/Code42/Playbooks/playbook-Code42_Exfiltration_Playbook.yml
  Packs/Code42/Playbooks/playbook-Code42_File_Search.yml
  Packs/Code42/README.md
  Packs/Code42/Scripts/Pipfile
  Packs/Code42/Scripts/Pipfile.lock
  Packs/Code42/TestPlaybooks/playbook-Code42-File-Search-Test.yml
  Packs/Code42/TestPlaybooks/playbook-Code42-Test.yml
  Packs/Code42/metadata.json
  Tests/conf.json
Labels: Contribution, docs-approved

#5897 Update indicator field names
  IndicatorFields/incidentfield-feedoriginalseverity.json
  IndicatorFields/incidentfield-feedoriginalseverity_CHANGELOG.md
  IndicatorFields/incidentfield-firstseenbyfeed.json
  IndicatorFields/incidentfield-firstseenbyfeed_CHANGELOG.md
  IndicatorFields/incidentfield-lastseenbyfeed.json
  IndicatorFields/incidentfield-lastseenbyfeed_CHANGELOG.md
  IndicatorFields/incidentfield-threattypes.json
  IndicatorFields/incidentfield-threattypes_CHANGELOG.md
Labels: docs-approved

#5903 Anomali ThreatStream v2 - reputation command with isArray fix
  Integrations/Anomali_ThreatStream_v2/Anomali_ThreatStream_v2.py
  Integrations/Anomali_ThreatStream_v2/CHANGELOG.md
Labels: bug, docs-approved, release-notes-only

#5993 Added base documentation for F5 Firewall integration
  Integrations/integration-F5.yml
  Integrations/integration-F5_CHANGELOG.md
  Integrations/integration-F5_README.md
Labels: bug, docs-approved

#6036 VirusTotal fixed indicator score calculation
  Integrations/integration-VirusTotal.yml
  Integrations/integration-VirusTotal_5.5.yml
  Integrations/integration-VirusTotal_5.5_CHANGELOG.md
  Integrations/integration-VirusTotal_CHANGELOG.md
Labels: bug, docs-approved, release-notes-only

#5929 Changed Arguments to match the notation
  Integrations/FeedTAXII/CHANGELOG.md
  Integrations/FeedTAXII/FeedTAXII.py
  Integrations/FeedTAXII/FeedTAXII.yml
  Integrations/FeedTAXII/FeedTAXII_description.md
Labels: docs-approved

#5816 [risksense-835] RiskSense Integration
  Integrations/RiskSense/Pipfile
  Integrations/RiskSense/Pipfile.lock
  Integrations/RiskSense/README.md
  Integrations/RiskSense/RiskSense.py
  Integrations/RiskSense/RiskSense.yml
  Integrations/RiskSense/RiskSense_description.md
  Integrations/RiskSense/RiskSense_image.png
  Integrations/RiskSense/RiskSense_test.py
  Integrations/RiskSense/TestData/apps_ec.json
  Integrations/RiskSense/TestData/apps_resp.json
  Integrations/RiskSense/TestData/host_finding_details_ec.json
  Integrations/RiskSense/TestData/host_finding_details_resp.json
  Integrations/RiskSense/TestData/host_finding_ec.json
  Integrations/RiskSense/TestData/host_finding_resp.json
  Integrations/RiskSense/TestData/hosts_ec.json
  Integrations/RiskSense/TestData/hosts_res.json
  Integrations/RiskSense/TestData/unique_cves_ec.json
  Integrations/RiskSense/TestData/unique_cves_resp.json
  Integrations/RiskSense/TestData/unique_open_findings_ec.json
  Integrations/RiskSense/TestData/unique_open_findings_resp.json
  TestPlaybooks/playbook-RiskSenseGetApps-Test.yml
  TestPlaybooks/playbook-RiskSenseGetAppsDetail-Test.yml
  TestPlaybooks/playbook-RiskSenseGetHostDetail-Test.yml
  TestPlaybooks/playbook-RiskSenseGetHostFindingDetail-Test.yml
  TestPlaybooks/playbook-RiskSenseGetHostFindings-Test.yml
  TestPlaybooks/playbook-RiskSenseGetHosts-Test.yml
  TestPlaybooks/playbook-RiskSenseGetUniqueCves-Test.yml
  TestPlaybooks/playbook-RiskSenseGetUniqueOpenFindings-Test.yml
  Tests/conf.json
  Tests/secrets_white_list.json
Labels: Contribution, docs-approved

#6003 Added O365 fields and mapping
  IndicatorFields/incidentfield-office365category.json
  IndicatorFields/incidentfield-office365expressroute.json
  IndicatorFields/incidentfield-office365required.json
  Packs/FeedOffice365/.secrets-ignore
  Packs/FeedOffice365/Integrations/FeedOffice365/CHANGELOG.md
  Packs/FeedOffice365/Integrations/FeedOffice365/FeedOffice365.py
  Packs/FeedOffice365/Integrations/FeedOffice365/FeedOffice365.yml
Labels: docs-approved, release-notes-only

#6017 Add tim to descriptions
  Playbooks/playbook-ArcSight_Add_Domain_Indicators.yml
  Playbooks/playbook-ArcSight_Add_Domain_Indicators_CHANGELOG.md
  Playbooks/playbook-ArcSight_Add_Hash_Indicators.yml
  Playbooks/playbook-ArcSight_Add_Hash_Indicators_CHANGELOG.md
  Playbooks/playbook-ArcSight_Add_IP_Indicators.yml
  Playbooks/playbook-ArcSight_Add_IP_Indicators_CHANGELOG.md
  Playbooks/playbook-PANW_-_Hunting_and_threat_detection_by_indicator_type_V2.yml
  Playbooks/playbook-PANW_-_Hunting_and_threat_detection_by_indicator_type_V2_CHANGELOG.md
  Playbooks/playbook-Process_Hash_Indicators.yml
  Playbooks/playbook-Process_Hash_Indicators_CHANGELOG.md
  Playbooks/playbook-Process_IP_Indicators.yml
  Playbooks/playbook-Process_IP_Indicators_CHANGELOG.md
  Playbooks/playbook-Process_Url_Indicators.yml
  Playbooks/playbook-Process_Url_Indicators_CHANGELOG.md
  Playbooks/playbook-QRadar_Add_Domain_Indicators.yml
  Playbooks/playbook-QRadar_Add_Domain_Indicators_CHANGELOG.md
  Playbooks/playbook-QRadar_Add_IP_Indicators.yml
  Playbooks/playbook-QRadar_Add_IP_Indicators_CHANGELOG.md
  Playbooks/playbook-QRadar_Add_Url_Indicators.yml
  Playbooks/playbook-QRadar_Add_Url_Indicators_CHANGELOG.md
  Playbooks/playbook-QRadar_Add_hash_Indicators.yml
  Playbooks/playbook-QRadar_Add_hash_Indicators_CHANGELOG.md
Labels: docs-approved

#5755 PAN-OS commit configuration playbook - fixes commit fail but playbook succeeds bug
  Playbooks/playbook-PAN-OS_EDL_Setup_v2.yml
  Playbooks/playbook-PAN-OS_EDL_Setup_v2_CHANGELOG.md
  Playbooks/playbook-Pan-OS_Commit_Configuration.yml
  Playbooks/playbook-Pan-OS_Commit_Configuration_CHANGELOG.md
Labels: bug, content, docs-approved

#6027 improved error message
  TestPlaybooks/playbook-EmailReputationTest.yml
  Tests/conf.json
Labels: docs-approved

#5999 Converting the incidentID received by the user to string
  Integrations/integration-ArcherRSA.yml
  Integrations/integration-ArcherRSA_CHANGELOG.md
Labels: bug, docs-approved, release-notes-only

#6037 Fix typos in AlienVault
  Packs/FeedAlienVault/Integrations/FeedAlienVaultOTXTaxii/CHANGELOG.md
  Packs/FeedAlienVault/Integrations/FeedAlienVaultOTXTaxii/FeedAlienVaultOTXTaxii.yml
  Packs/FeedAlienVault/Integrations/FeedAlienVaultReputation/README.md
  Packs/FeedAlienVault/pack_metadata.json
Labels: docs-approved

#6030 fix internal field of IP
  Packs/Base/.secrets-ignore
  Packs/Base/Misc/reputation-ip.json
  Packs/Base/Misc/reputation-ip_5.4.9.json
  Packs/Base/Misc/reputation-ip_5.4.9_CHANGELOG.md
  Packs/Base/Misc/reputation-ip_CHANGELOG.md
Labels: docs-approved, release-notes-only

#6038 Added default author image to base pack
  Packs/Base/Author_image.png
  Packs/Base/pack_metadata.json
Labels: docs-approved

#6048 Packify Slack
  Packs/Slack/.pack-ignore
  Packs/Slack/.secrets-ignore
  Packs/Slack/Integrations/Slack/CHANGELOG.md
  Packs/Slack/Integrations/Slack/README.md
  Packs/Slack/Integrations/Slack/Slack.py
  Packs/Slack/Integrations/Slack/Slack.yml
  Packs/Slack/Integrations/Slack/Slack_description.md
  Packs/Slack/Integrations/Slack/Slack_image.png
  Packs/Slack/Integrations/Slack/Slack_test.py
  Packs/Slack/Playbooks/playbook-FailedLogin_SlackV2.yml
  Packs/Slack/Playbooks/playbook-FailedLogin_SlackV2_CHANGELOG.md
  Packs/Slack/README.md
  Packs/Slack/Scripts/SlackAsk/CHANGELOG.md
  Packs/Slack/Scripts/SlackAsk/README.md
  Packs/Slack/Scripts/SlackAsk/SlackAsk.py
  Packs/Slack/Scripts/SlackAsk/SlackAsk.yml
  Packs/Slack/Scripts/SlackAsk/SlackAsk_test.py
  Packs/Slack/TestPlaybooks/playbook-Slack_TestPlaybook.yml
  Packs/Slack/pack_metadata.json
Labels: docs-approved

#5419 Ms graph files
  Integrations/MicrosoftGraphFiles/MicrosoftGraphFiles.py
  Integrations/MicrosoftGraphFiles/MicrosoftGraphFiles.yml
  Integrations/MicrosoftGraphFiles/MicrosoftGraphFiles_description.md
  Integrations/MicrosoftGraphFiles/MicrosoftGraphFiles_image.png
  Integrations/MicrosoftGraphFiles/MicrosoftGraphFiles_test.py
  Integrations/MicrosoftGraphFiles/Pipfile
  Integrations/MicrosoftGraphFiles/Pipfile.lock
  Integrations/MicrosoftGraphFiles/README.md
  Integrations/MicrosoftGraphFiles/test_data/expected_results.json
  Integrations/MicrosoftGraphFiles/test_data/response.json
  Integrations/MicrosoftGraphFiles/test_data/test_inputs.json
  TestPlaybooks/playbook-MS_Graph_Files_-_Test.yml
  Tests/conf.json
  Tests/secrets_white_list.json
Labels: docs-approved

#5922 EDL - improve test module functionality
  Integrations/EDL/CHANGELOG.md
  Integrations/EDL/EDL.py
  Integrations/EDL/EDL.yml
  Packs/Active_Directory_Query/Playbooks/playbook-Active_Directory_-_Get_User_Manager_Email.yml
  Packs/CalculateGeoDistance/Scripts/CalculateGeoDistance/CHANGELOG.md
  Packs/ExportIndicators/Integrations/ExportIndicators/CHANGELOG.md
  Packs/ExportIndicators/Integrations/ExportIndicators/ExportIndicators.py
  Packs/ExportIndicators/Integrations/ExportIndicators/ExportIndicators.yml
  Packs/ImpossibleTraveler/Layouts/layout-details-Impossible_Traveller_CHANGELOG.md
  Packs/TAXIIServer/Integrations/TAXIIServer/CHANGELOG.md
  Packs/TAXIIServer/Integrations/TAXIIServer/TAXIIServer.py
  Packs/TAXIIServer/Integrations/TAXIIServer/TAXIIServer.yml
Labels: docs-approved

#6049 update docs to point to xsoar.pan.dev
  CONTRIBUTING.md
  README.md
  Tests/secrets_white_list.json
  docs/DT/README.MD
  docs/Debugging/README.MD
  docs/code_conventions/README.MD
  docs/context_and_ouputs/README.MD
  docs/context_standards/README.MD
  docs/creating_playbooks/README.MD
  docs/dbot/README.md
  docs/docker/README.MD
  docs/fetching_credentials/README.md
  docs/fetching_incidents/README.md
  docs/genericpolling/README.md
  docs/getting_started/README.MD
  docs/integration_documentation/README.MD
  docs/integration_documentation/integration_documentation_structure.md
  docs/linting/README.md
  docs/long_running_containers/README.MD
  docs/package_directory_structure/README.MD
  docs/parameter_types/README.md
  docs/playbook_conventions/README.MD
  docs/release_notes/README.md
  docs/test_playbook/README.MD
  docs/tests/README.md
  docs/tests/circleci/README.md
  docs/tests/mocks/README.md
  docs/tests/unit-testing/README.md
  docs/tutorial-video/README.md
  docs/yaml-file-integration/README.MD
Labels: docs-approved

#5834 VT queued files
  Integrations/VirusTotal-Private_API/CHANGELOG.md
  Integrations/VirusTotal-Private_API/VirusTotal-Private_API.py
  Integrations/VirusTotal-Private_API/VirusTotal-Private_API.yml
  Integrations/VirusTotal-Private_API/VirusTotal_test.py
  Playbooks/plabook-Detonate_File-VirusTotal.yml
  TestPlaybooks/playbook-VirusTotal_detonate_file.yml
  TestPlaybooks/playbook-virusTotalPrivateAPI-test.yml
  Tests/conf.json
Labels: docs-approved, release-notes-only

#6052 msgraph files - test direct access to oproxy
  Tests/conf.json
Labels: docs-approved

#6050 Marketplace - Skipped zipping of old format reputation files
  Tests/store_packs.py
Labels: docs-approved

#6051 Update conf.json
  Tests/conf.json
Labels: docs-approved

#6060 applied bug fix and enhancement to Qradar <5.5
  Integrations/QRadar/CHANGELOG.md
  Integrations/QRadar/QRadar.py
  Integrations/QRadar_5_4_9/CHANGELOG.md
  Integrations/QRadar_5_4_9/QRadar_5_4_9.py
  Integrations/QRadar_5_4_9/QRadar_5_4_9.yml
  TestPlaybooks/playbook-TestQradar.yml
  TestPlaybooks/playbook-TestQradar_5_4_9.yml
Labels: bug, docs-approved

#6063 remove init files and ignore in gitignore
  .gitignore
  Integrations/Exabeam/test_data/__init__.py
  Integrations/Securonix/test_data/__init__.py
  Integrations/__init__.py
  Packs/Code42/Integrations/Code42/__init__.py
  Packs/FeedDShield/Integrations/FeedDShield/__init__.py
  Packs/FeedOffice365/Integrations/FeedOffice365/__init__.py
  Packs/FeedOffice365/Integrations/FeedOffice365/test_data/__init__.py
  Packs/FeedTorExitAddresses/Integrations/FeedTorExitAddresses/__init__.py
  Packs/McAfee-MAR/Integrations/__init__.py
  Packs/McAfee-MAR/__init__.py
  Packs/__init__.py
Labels: docs-approved

#6057 Remove `hidden` fields from AWS Feed YAML file
  Packs/FeedAWS/Integrations/FeedAWS/CHANGELOG.md
  Packs/FeedAWS/Integrations/FeedAWS/FeedAWS.yml
Labels: docs-approved

#5983 intsights tpb refactor
  TestPlaybooks/playbook-IntSights_Test.yml
  Tests/conf.json
Labels: docs-approved

#6064 Replaced DomainTools logos on both integrations
  Integrations/DomainTools_Iris/DomainTools_Iris_image.png
  Integrations/integration-DomainTools.yml
  Integrations/integration-DomainTools_CHANGELOG.md
Labels: Contribution, docs-approved

#6065 Skiping palo_alto_panorama_test_pb
  Tests/conf.json
Labels: docs-approved

#6062 Marketplace - author image support
  Tests/scripts/infrastructure_tests/store_packs_test.py
  Tests/store_packs.py
Labels: docs-approved

#6041 Indicators regexes improvements
  Packs/Base/Misc/reputation-ipv6.json
  Packs/Base/Misc/reputation-ipv6_CHANGELOG.md
  Scripts/script-UnEscapeURLs.yml
  Scripts/script-UnEscapeURLs_CHANGELOG.md
  TestPlaybooks/playbook-Indicators-reputation-.json-Test.yml
  TestPlaybooks/script-FormattingPerformance.yml
  Tests/secrets_white_list.json
Labels: docs-approved, release-notes-only

#6073 skipped tests
  Tests/conf.json
Labels: docs-approved

#6077 rm office365 from unmockable
  Tests/conf.json
Labels: docs-approved

#6076 indicator feed test - fix
  TestPlaybooks/playbook-Indicator_Feed_-_Test.yml
  Tests/conf.json
Labels: docs-approved

#6082 EDL edl-update Command Description Typo Fix
  Integrations/EDL/EDL.yml
Labels: docs-approved

#6083 remove duplicate description PTEnrich
  Scripts/script-PTEnrich.yml
  Scripts/script-PTEnrich_CHANGELOG.md
Labels: docs-approved

#6085 Setting npm packages and chache
  .circleci/config.yml
  .gitignore
  Tests/secrets_white_list.json
  package-lock.json
  package.json
Labels: docs-approved

#6061 Fixed aws-ec2-describe-vpcs command when the command returns empty list
  Integrations/AWS-EC2/AWS-EC2.py
  Integrations/AWS-EC2/CHANGELOG.md
  Tests/conf.json
Labels: docs-approved
