Repository demisto/content, pull requests merged in 2020-04, with the labels that each got.

#6337 Typo fix: changed Costumer to Customer
  Packs/CortexDataLake/Integrations/CortexDataLake/CortexDataLake_description.md
  Packs/CortexDataLake/README.md
Labels: docs-approved

#6331 Fix file command in IBM X-Force Exchange (v2)
  Packs/XForceExchange/Integrations/XFE_v2/CHANGELOG.md
  Packs/XForceExchange/Integrations/XFE_v2/README.md
  Packs/XForceExchange/Integrations/XFE_v2/XFE_v2.py
  Packs/XForceExchange/Integrations/XFE_v2/XFE_v2.yml
Labels: docs-approved, release-notes-only

#6348 Add fromversion to test playbooks
  Packs/HelloWorld/TestPlaybooks/playbook-TestHelloWorld.yml
  Packs/HelloWorld/TestPlaybooks/playbook-TestHelloWorldPlaybook.yml
  Tests/conf.json
Labels: docs-approved

#6338 checks if circleci's config is up to date.
  .circleci/config.yml
Labels: docs-approved

#6279 Fix Alienvault USM fetch incidents
  Integrations/AlienVault_USM_Anywhere/AlienVault_USM_Anywhere.py
  Integrations/AlienVault_USM_Anywhere/AlienVault_USM_Anywhere_test.py
  Integrations/AlienVault_USM_Anywhere/CHANGELOG.md
Labels: docs-approved, release-notes-only

#6358 Fixed Tenable.io TPB + removed from skipped
  TestPlaybooks/playbook-Tenable.io_test.yml
  Tests/conf.json
Labels: docs-approved

#6227 Cisco ASA second time
  Packs/CiscoASA/.pack-ignore
  Packs/CiscoASA/.secrets-ignore
  Packs/CiscoASA/CHANGELOG.md
  Packs/CiscoASA/Integrations/CiscoASA/CHANGELOG.md
  Packs/CiscoASA/Integrations/CiscoASA/CiscoASA.py
  Packs/CiscoASA/Integrations/CiscoASA/CiscoASA.yml
  Packs/CiscoASA/Integrations/CiscoASA/CiscoASA_description.md
  Packs/CiscoASA/Integrations/CiscoASA/CiscoASA_image.png
  Packs/CiscoASA/Integrations/CiscoASA/CiscoASA_test.py
  Packs/CiscoASA/README.md
  Packs/CiscoASA/TestPlaybooks/playbook-CiscoASA.yml
  Packs/CiscoASA/pack_metadata.json
  Tests/conf.json
Labels: docs-approved

#6349 Auto focus v2 to pack
  Packs/AutoFocus/.pack-ignore
  Packs/AutoFocus/.secrets-ignore
  Packs/AutoFocus/CHANGELOG.md
  Packs/AutoFocus/Integrations/AutofocusV2/AutofocusV2.py
  Packs/AutoFocus/Integrations/AutofocusV2/AutofocusV2.yml
  Packs/AutoFocus/Integrations/AutofocusV2/AutofocusV2_description.md
  Packs/AutoFocus/Integrations/AutofocusV2/AutofocusV2_image.png
  Packs/AutoFocus/Integrations/AutofocusV2/AutofocusV2_test.py
  Packs/AutoFocus/Integrations/AutofocusV2/CHANGELOG.md
  Packs/AutoFocus/Integrations/AutofocusV2/Pipfile
  Packs/AutoFocus/Integrations/AutofocusV2/Pipfile.lock
  Packs/AutoFocus/Integrations/AutofocusV2/README.md
  Packs/AutoFocus/Playbooks/playbook-AutoFocusPolling.yml
  Packs/AutoFocus/Playbooks/playbook-AutoFocusPolling_CHANGELOG.md
  Packs/AutoFocus/Playbooks/playbook-Autofocus_Query_Samples_and_Sessions.yml
  Packs/AutoFocus/Playbooks/playbook-Autofocus_Query_Samples_and_Sessions_CHANGELOG.md
  Packs/AutoFocus/README.md
  Packs/AutoFocus/TestPlaybooks/playbook-AutoFocus_V2_test.yml
  Packs/AutoFocus/TestPlaybooks/playbook-Autofocus_Query_Samples_and_Sessions_and_Tags_Test_Playbook.yml
  Packs/AutoFocus/pack_metadata.json
Labels: docs-approved

#6323 Stabilizing ML test
  Scripts/DBotPredictOutOfTheBox/CHANGELOG.md
  Scripts/DBotPredictOutOfTheBox/DBotPredictOutOfTheBox.yml
  TestPlaybooks/playbook-Create_Phishing_Classifier_V2_ML_Test.yml
  TestPlaybooks/playbook-DBotPredictOutOfTheBox-test.yml
  TestPlaybooks/playbook-GetEWSFolder-Test.yml
  Tests/conf.json
Labels: docs-approved

#6269 Added a `Palo Alto Networks` prefix to the integration's name.
  Integrations/BPA/BPA.yml
  Integrations/BPA/CHANGELOG.md
Labels: bug, docs-approved, release-notes-only

#6317 Handling conversion of date with time zone to epoch time.
  Scripts/FormattedDateToEpoch/CHANGELOG.md
  Scripts/FormattedDateToEpoch/FormattedDateToEpoch.py
  Scripts/FormattedDateToEpoch/FormattedDateToEpoch.yml
  Scripts/FormattedDateToEpoch/FormattedDateToEpoch_test.py
Labels: bug, docs-approved, release-notes-only

#6287 New TLP Field
  IndicatorFields/incidentfield-tlp.json
  IndicatorFields/incidentfield-tlp_CHANGELOG.md
  Misc/reputation-account.json
  Misc/reputation-cidr.json
  Misc/reputation-cve.json
  Misc/reputation-domain.json
  Misc/reputation-file.json
  Misc/reputation-host.json
  Misc/reputation-ip.json
  Misc/reputation-ipv6.json
  Misc/reputation-ipv6_cidr.json
  Misc/reputation-registryKey.json
  Misc/reputation-url.json
  Packs/TAXIIServer/Integrations/TAXIIServer/CHANGELOG.md
  Packs/TAXIIServer/Integrations/TAXIIServer/TAXIIServer.py
Labels: docs-approved, release-notes-only

#6242 Add Default Category Value when Not Provided in Timeline Data
  Packs/Base/Scripts/CommonServerPython/CHANGELOG.md
  Packs/Base/Scripts/CommonServerPython/CommonServerPython.py
  Packs/Base/Scripts/CommonServerPython/CommonServerPython_test.py
Labels: docs-approved

#6357 Fixed ThreatQ TPB + removed from skipped
  TestPlaybooks/playbook-ThreatQ-Test.yml
  Tests/conf.json
Labels: docs-approved

#6346 Carbon black - updating deprecated command descriptions to point to the correct repl…
  Integrations/integration-Carbon_Black_Enterprise_Live_Response.yml
  Integrations/integration-Carbon_Black_Enterprise_Live_Response_CHANGELOG.md
Labels: bug, docs-approved

#6361 Delete Windows-ATP entries from conf.json and add the test playbook t…
  TestPlaybooks/NonCircleTests/playbook-Windows_Defender_Advanced_Threat_Protection_Test.yml
  Tests/conf.json
Labels: docs-approved

#6239 Fixed an issue with handling htm attachments
  Scripts/ParseEmailFiles/CHANGELOG.md
  Scripts/ParseEmailFiles/ParseEmailFiles.py
  Scripts/ParseEmailFiles/parse_email_files_test.py
  Scripts/ParseEmailFiles/test_data/eml_contains_htm_attachment.eml
Labels: docs-approved, release-notes-only

#6289 Proofpoint Protection Server README
  Beta_Integrations/ProofpointServerProtection/CHANGELOG.md
  Beta_Integrations/ProofpointServerProtection/ProofpointServerProtection.py
  Beta_Integrations/ProofpointServerProtection/ProofpointServerProtection.yml
  Beta_Integrations/ProofpointServerProtection/ProofpointServerProtection_description.md
  Beta_Integrations/ProofpointServerProtection/README.md
  Tests/secrets_white_list.json
Labels: docs-approved

#6362 Revert "Revert "Delete Old TLP Indicator Field""
  IndicatorFields/incidentfield-trafficlightprotocol.json
  IndicatorFields/incidentfield-trafficlightprotocol_CHANGELOG.md
Labels: docs-approved

#6303 Tanium Threat - added description
  Integrations/TaniumThreatResponse/TaniumThreatResponse_description.md
Labels: docs-approved

#6367 fix indicator expiration
  Misc/reputation-account.json
  Misc/reputation-account_5.4.9.json
  Misc/reputation-cve.json
  Misc/reputation-file.json
  Misc/reputation-host.json
  Misc/reputation-registryKey.json
Labels: docs-approved

#6353 Microsoft Teams integration fixes
  Integrations/MicrosoftTeams/CHANGELOG.md
  Integrations/MicrosoftTeams/MicrosoftTeams.py
  Integrations/MicrosoftTeams/MicrosoftTeams_test.py
  Integrations/MicrosoftTeams/Pipfile
  Integrations/MicrosoftTeams/Pipfile.lock
Labels: docs-approved, release-notes-only

#6364 Demisto-sdk new version - v0.5.0
  Layouts/layout-details-Cortex_XDR_Incident.json
  Layouts/layout-details-Cortex_XDR_Incident_CHANGELOG.md
  dev-requirements-py3.txt
Labels: docs-approved

#6273 Pwned v2
  Packs/Pwned-V2/.secrets-ignore
  Packs/Pwned-V2/Integrations/Pwned-V2/Pwned-V2_description.md
  Packs/Pwned-V2/README.md
  Packs/Pwned-V2/pack_metadata.json
  Packs/PwnedV2/.pack-ignore
  Packs/PwnedV2/.secrets-ignore
  Packs/PwnedV2/CHANGELOG.md
  Packs/PwnedV2/Integrations/PwnedV2/CHANGELOG.md
  Packs/PwnedV2/Integrations/PwnedV2/PwnedV2.py
  Packs/PwnedV2/Integrations/PwnedV2/PwnedV2.yml
  Packs/PwnedV2/Integrations/PwnedV2/PwnedV2_image.png
  Packs/PwnedV2/Integrations/PwnedV2/PwnedV2_test.py
  Packs/PwnedV2/Integrations/PwnedV2/README.md
  Packs/PwnedV2/Integrations/PwnedV2/example.txt
  Packs/PwnedV2/README.md
  Packs/PwnedV2/TestPlaybooks/playbook-PwnedV2_test.yml
  Packs/PwnedV2/pack_metadata.json
  TestPlaybooks/playbook-Pwned-test.yml
Labels: docs-approved

#6369 intsights-get-alert-activities - None err when missing some alert data
  Integrations/IntSight/CHANGELOG.md
  Integrations/IntSight/IntSight.py
Labels: docs-approved

#6379 Update slack_notifier.sh
  Tests/scripts/slack_notifier.sh
Labels: docs-approved

#6377 Update conf.json
  Tests/conf.json
Labels: docs-approved

#6380 JSON Feed - update image
  Packs/FeedJSON/Integrations/FeedJSON/CHANGELOG.md
  Packs/FeedJSON/Integrations/FeedJSON/FeedJSON_image.png
Labels: docs-approved

#6345 Train Phishing classifier from file(2)
  Playbooks/playbook-DBot_Create_Phishing_Classifier_V2_From_File.yml
  TestPlaybooks/playbook-DBot_Create_Phishing_Classifier_V2_From_File-_Test.yml
  TestPlaybooks/script-TestCreateIncidentsFile.yml
  Tests/conf.json
Labels: docs-approved

#6381 Fixed CDL documentation
  Packs/CortexDataLake/Integrations/CortexDataLake/CortexDataLake_description.md
Labels: docs-approved

#6388 Fixed timestanps - SentinelOne test
  TestPlaybooks/playbook-SentinelOne-Beta-Test.yml
Labels: docs-approved

#6375 Added the argument *ignore_auto_extract* to the ***return_outputs*** …
  Integrations/AttackIQFireDrill/test_data/constants.py
  Packs/Base/Scripts/CommonServerPython/CHANGELOG.md
  Packs/Base/Scripts/CommonServerPython/CommonServerPython.py
  Packs/Base/Scripts/CommonServerPython/CommonServerPython_test.py
  Packs/GetServerURL/Scripts/GetServerURL/GetServerURL_test.py
Labels: docs-approved

#6383 Changed type of memory threshold string to int
  Tests/conf.json
Labels: docs-approved

#6241 Fix ms graph files playbook
  TestPlaybooks/playbook-MS_Graph_Files_-_Test.yml
Labels: docs-approved

#6374 Intsights - get-alert-activities fix
  Integrations/IntSight/IntSight.py
Labels: docs-approved

#6247 Cisco firepower
  Packs/CiscoFirepower/.pack-ignore
  Packs/CiscoFirepower/.secrets-ignore
  Packs/CiscoFirepower/Integrations/CiscoFirepower/CHANGELOG.md
  Packs/CiscoFirepower/Integrations/CiscoFirepower/CiscoFirepower.py
  Packs/CiscoFirepower/Integrations/CiscoFirepower/CiscoFirepower.yml
  Packs/CiscoFirepower/Integrations/CiscoFirepower/CiscoFirepower_description.md
  Packs/CiscoFirepower/Integrations/CiscoFirepower/CiscoFirepower_image.png
  Packs/CiscoFirepower/Integrations/CiscoFirepower/CiscoFirepower_test.py
  Packs/CiscoFirepower/Integrations/CiscoFirepower/Pipfile
  Packs/CiscoFirepower/Integrations/CiscoFirepower/Pipfile.lock
  Packs/CiscoFirepower/Integrations/CiscoFirepower/README.md
  Packs/CiscoFirepower/README.md
  Packs/CiscoFirepower/TestPlaybooks/playbook-CiscoFirepowerTest.yml
  Packs/CiscoFirepower/pack_metadata.json
  Tests/conf.json
Labels: docs-approved

#6397 Skipped tests
  Tests/conf.json
Labels: docs-approved

#6396 Increased git doff timeout
  .circleci/config.yml
Labels: docs-approved

#6398 removed copy_beta.py
  .circleci/config.yml
  copy_beta.py
Labels: docs-approved

#6399 fixed false positive result of release_notes.py
  release_notes.py
Labels: docs-approved

#6390 Marketplace uploader split
  .circleci/config.yml
  Tests/Marketplace/Tests/marketplace_services_test.py
  Tests/Marketplace/Tests/upload_packs_test.py
  Tests/Marketplace/marketplace_services.py
  Tests/Marketplace/upload_packs.py
Labels: docs-approved

#6235 Okta v2
  Packs/Okta_v2/.pack-ignore
  Packs/Okta_v2/.secrets-ignore
  Packs/Okta_v2/Integrations/Okta_v2/CHANGELOG.md
  Packs/Okta_v2/Integrations/Okta_v2/Okta_v2.py
  Packs/Okta_v2/Integrations/Okta_v2/Okta_v2.yml
  Packs/Okta_v2/Integrations/Okta_v2/Okta_v2_description.md
  Packs/Okta_v2/Integrations/Okta_v2/Okta_v2_image.png
  Packs/Okta_v2/Integrations/Okta_v2/Okta_v2_test.py
  Packs/Okta_v2/Integrations/Okta_v2/README.md
  Packs/Okta_v2/Integrations/Okta_v2/example.txt
  Packs/Okta_v2/README.md
  Packs/Okta_v2/TestPlaybooks/playbook-OktaV2-Test.yml
  Packs/Okta_v2/pack_metadata.json
  Tests/conf.json
Labels: docs-approved

#6384 Deprecate postgreSQL - using GenericSQL instead
  Integrations/integration-PostgreSQL.yml
  Integrations/integration-PostgreSQL_CHANGELOG.md
Labels: docs-approved

#6404 added_timeout_panorama
  Playbooks/playbook-Panorama_Query_Logs.yml
  Playbooks/playbook-Panorama_Query_Logs_CHANGELOG.md
  Tests/conf.json
Labels: docs-approved

#6276 MISP - Entry context overload - bug fix
  Integrations/MISP_V2/CHANGELOG.md
  Integrations/MISP_V2/MISP_V2.py
  Integrations/MISP_V2/MISP_V2.yml
  Integrations/MISP_V2/MISP_V2_test.py
  TestPlaybooks/playbook-MISP_V2-Test.yml
  TestPlaybooks/playbook-illuminate_Test.yml
Labels: docs-approved

#6296 fixed connection error without proxy
  Integrations/Exabeam/CHANGELOG.md
  Integrations/Exabeam/Exabeam.py
Labels: bug, release-notes-only

#6409 CommonServerPython - restore default values
  Packs/Base/Scripts/CommonServerPython/CommonServerPython.py
Labels: docs-approved

#6232 Azure sentinel
  Packs/ApiModules/.secrets-ignore
  Packs/ApiModules/Scripts/MicrosoftApiModule/CHANGELOG.md
  Packs/ApiModules/Scripts/MicrosoftApiModule/MicrosoftApiModule.py
  Packs/ApiModules/Scripts/MicrosoftApiModule/MicrosoftApiModule_test.py
  Packs/AzureSentinel/.pack-ignore
  Packs/AzureSentinel/.secrets-ignore
  Packs/AzureSentinel/Integrations/AzureSentinel/AzureSentinel.py
  Packs/AzureSentinel/Integrations/AzureSentinel/AzureSentinel.yml
  Packs/AzureSentinel/Integrations/AzureSentinel/AzureSentinel_description.md
  Packs/AzureSentinel/Integrations/AzureSentinel/AzureSentinel_image.png
  Packs/AzureSentinel/Integrations/AzureSentinel/AzureSentinel_test.py
  Packs/AzureSentinel/Integrations/AzureSentinel/CHANGELOG.md
  Packs/AzureSentinel/Integrations/AzureSentinel/Pipfile
  Packs/AzureSentinel/Integrations/AzureSentinel/Pipfile.lock
  Packs/AzureSentinel/Integrations/AzureSentinel/README.md
  Packs/AzureSentinel/README.md
  Packs/AzureSentinel/TestPlaybooks/NonCircleTests/playbook-TestAzureSentinelPlaybook.yml
  Packs/AzureSentinel/pack_metadata.json
Labels: docs-approved

#6359 Added mapping, changed the behavior in CSVFeedApiModule.py
  Packs/ApiModules/Scripts/CSVFeedApiModule/CHANGELOG.md
  Packs/ApiModules/Scripts/CSVFeedApiModule/CSVFeedApiModule.py
  Packs/ApiModules/Scripts/CSVFeedApiModule/CSVFeedApiModule_test.py
  Packs/FeedBambenekConsulting/.secrets-ignore
  Packs/FeedBambenekConsulting/Integrations/FeedBambenekConsulting/CHANGELOG.md
  Packs/FeedBambenekConsulting/Integrations/FeedBambenekConsulting/FeedBambenekConsulting.py
Labels: docs-approved, release-notes-only

#6408 Marketplace images upload fix
  Tests/Marketplace/marketplace_services.py
Labels: docs-approved

#6209 added proper error prining for panorama commit and push
  Packs/Legacy/Integrations/PaloAltoNetworks_PAN_OS_EDL_Management/CHANGELOG.md
  Packs/Legacy/Integrations/PaloAltoNetworks_PAN_OS_EDL_Management/PaloAltoNetworks_PAN_OS_EDL_Management.py
  Packs/Legacy/Playbooks/playbook-PAN-OS_EDL_Setup.yml
  Packs/Legacy/Playbooks/playbook-PAN-OS_EDL_Setup_CHANGELOG.md
  Packs/Legacy/Playbooks/playbook-PAN-OS_EDL_Setup_v2.yml
  Packs/Legacy/Playbooks/playbook-PAN-OS_EDL_Setup_v2_CHANGELOG.md
  Packs/Legacy/Playbooks/playbook-Pan-OS_Commit_Configuration.yml
  Packs/Legacy/Playbooks/playbook-Pan-OS_Commit_Configuration_CHANGELOG.md
  TestPlaybooks/playbook-PAN_OS_EDL_SETUP-V2-Test.yml
  Tests/conf.json
Labels: docs-approved

#6376 ExtraHop: Update alert rule command names
  Integrations/ExtraHop_v2/CHANGELOG.md
  Integrations/ExtraHop_v2/ExtraHop_v2.py
  Integrations/ExtraHop_v2/ExtraHop_v2.yml
  Integrations/ExtraHop_v2/README.md
  TestPlaybooks/playbook-ExtraHop_v2-Test.yml
Labels: Contribution, docs-approved, release-notes-only

#6288 Adding option to get the model full predictions on the test set
  Packs/Legacy/Scripts/DBotPreprocessTextData/DBotPreprocessTextData.py
  Packs/Legacy/Scripts/DBotPreprocessTextData/DBotPreprocessTextData.yml
  Packs/Legacy/Scripts/DBotTrainTextClassifierV2/CHANGELOG.md
  Packs/Legacy/Scripts/DBotTrainTextClassifierV2/DBotTrainTextClassifierV2.py
  Packs/Legacy/Scripts/DBotTrainTextClassifierV2/DBotTrainTextClassifierV2.yml
Labels: docs-approved

#6422 Fix mail sender conf
  Tests/conf.json
Labels: docs-approved

#6360 Tim playbooks fixes
  Packs/Legacy/Playbooks/playbook-TIM_-_Process_Indicators_-_Fully_Automated.yml
  Packs/Legacy/Playbooks/playbook-TIM_-_Process_Indicators_-_Fully_Automated_CHANGELOG.md
  Packs/Legacy/Playbooks/playbook-TIM_-_Process_Indicators_Against_Business_Partners_IP_List.yml
  Packs/Legacy/Playbooks/playbook-TIM_-_Process_Indicators_Against_Business_Partners_IP_List_CHANGELOG.md
  Packs/Legacy/Playbooks/playbook-TIM_-_Process_Indicators_Against_Organizations_External_IP_List.yml
  Packs/Legacy/Playbooks/playbook-TIM_-_Process_Indicators_Against_Organizations_External_IP_List_CHANGELOG.md
  Packs/Legacy/Playbooks/playbook-TIM_-_Process_Indicators_Manual_Review.yml
  Packs/Legacy/Playbooks/playbook-TIM_-_Process_Indicators_Manual_Review_CHANGELOG.md
  Packs/Legacy/Playbooks/playbook-TIM_-_Run_Enrichment_For_Domain_Indicators.yml
  Packs/Legacy/Playbooks/playbook-TIM_-_Run_Enrichment_For_Domain_Indicators_CHANGELOG.md
  Packs/Legacy/Playbooks/playbook-TIM_-_Run_Enrichment_For_Hash_Indicators.yml
  Packs/Legacy/Playbooks/playbook-TIM_-_Run_Enrichment_For_Hash_Indicators_CHANGELOG.md
  Packs/Legacy/Playbooks/playbook-TIM_-_Run_Enrichment_For_IP_Indicators.yml
  Packs/Legacy/Playbooks/playbook-TIM_-_Run_Enrichment_For_IP_Indicators_CHANGELOG.md
  Packs/Legacy/Playbooks/playbook-TIM_-_Run_Enrichment_For_Url_Indicators.yml
  Packs/Legacy/Playbooks/playbook-TIM_-_Run_Enrichment_For_Url_Indicators_CHANGELOG.md
Labels: docs-approved

#6429 unskip wf
  Tests/conf.json
Labels: docs-approved

#6431 fix download links in test playbooks of test data
  TestPlaybooks/NonCircleTests/playbook-TestParseEmailHeaders.yml
  TestPlaybooks/playbook-CreateIndicatorFromSTIXTest.yml
  TestPlaybooks/playbook-UnzipFile-Test.yml
Labels: docs-approved

#6434 fix verify json from version
  Packs/Legacy/Scripts/VerifyJSON/CHANGELOG.md
  Packs/Legacy/Scripts/VerifyJSON/VerifyJSON.yml
Labels: docs-approved

#5943 ProtectWise added token parameter
  Integrations/integration-ProtectWise.yml
  Integrations/integration-ProtectWise_CHANGELOG.md
Labels: Contribution, docs-approved

#6435 delete empty readme files
  Packs/FeedBlocklist_de/Integrations/FeedBlocklist_de/README.md
  Packs/FeedBruteForceBlocker/Integrations/FeedBruteForceBlocker/README.md
  Packs/FeedFastly/Integrations/FeedFastly/README.md
  Packs/FeedFeodoTracker/Integrations/FeedFeodoTrackerHashes/README.md
  Packs/FeedFeodoTracker/Integrations/FeedFeodoTrackerIPBlocklist/README.md
  Packs/FeedMalwareDomainList/Integrations/FeedMalwareDomainList/README.md
  Packs/FeedRecordedFuture/Integrations/FeedRecordedFuture/README.md
  Packs/FeedTorExitAddresses/Integrations/FeedTorExitAddresses/README.md
Labels: docs-approved

#6304 Added tags param feeds
  Packs/ApiModules/.secrets-ignore
  Packs/ApiModules/Scripts/HTTPFeedApiModule/CHANGELOG.md
  Packs/ApiModules/Scripts/HTTPFeedApiModule/HTTPFeedApiModule.py
  Packs/ApiModules/Scripts/JSONFeedApiModule/JSONFeedApiModule.py
  Packs/ApiModules/Scripts/JSONFeedApiModule/JSONFeedApiModule_test.py
  Packs/FeedAzure/Integrations/FeedAzure/CHANGELOG.md
  Packs/FeedAzure/Integrations/FeedAzure/FeedAzure.py
  Packs/FeedAzure/Integrations/FeedAzure/FeedAzure.yml
  Packs/FeedBlocklist_de/Integrations/FeedBlocklist_de/CHANGELOG.md
  Packs/FeedBlocklist_de/Integrations/FeedBlocklist_de/FeedBlocklist_de.yml
  Packs/FeedBruteForceBlocker/Integrations/FeedBruteForceBlocker/CHANGELOG.md
  Packs/FeedBruteForceBlocker/Integrations/FeedBruteForceBlocker/FeedBruteForceBlocker.yml
  Packs/FeedCloudflare/Integrations/FeedCloudflare/CHANGELOG.md
  Packs/FeedCloudflare/Integrations/FeedCloudflare/FeedCloudflare.yml
  Packs/FeedDShield/Integrations/FeedDShield/CHANGELOG.md
  Packs/FeedDShield/Integrations/FeedDShield/FeedDShield.yml
  Packs/FeedFastly/Integrations/FeedFastly/CHANGELOG.md
  Packs/FeedFastly/Integrations/FeedFastly/FeedFastly.yml
  Packs/FeedFeodoTracker/Integrations/FeedFeodoTrackerHashes/CHANGELOG.md
  Packs/FeedFeodoTracker/Integrations/FeedFeodoTrackerHashes/FeedFeodoTrackerHashes.yml
  Packs/FeedFeodoTracker/Integrations/FeedFeodoTrackerIPBlocklist/CHANGELOG.md
  Packs/FeedFeodoTracker/Integrations/FeedFeodoTrackerIPBlocklist/FeedFeodoTrackerIPBlocklist.yml
  Packs/FeedJSON/Integrations/FeedJSON/CHANGELOG.md
  Packs/FeedJSON/Integrations/FeedJSON/FeedJSON.yml
  Packs/FeedMalwareDomainList/Integrations/FeedMalwareDomainList/CHANGELOG.md
  Packs/FeedMalwareDomainList/Integrations/FeedMalwareDomainList/FeedMalwareDomainList.yml
  Packs/FeedPlainText/Integrations/FeedPlainText/CHANGELOG.md
  Packs/FeedPlainText/Integrations/FeedPlainText/FeedPlainText.yml
  Packs/FeedSpamhaus/Integrations/FeedSpamhaus/CHANGELOG.md
  Packs/FeedSpamhaus/Integrations/FeedSpamhaus/FeedSpamhaus.yml
  Packs/FeedTorExitAddresses/Integrations/FeedTorExitAddresses/CHANGELOG.md
  Packs/FeedTorExitAddresses/Integrations/FeedTorExitAddresses/FeedTorExitAddresses.py
  Packs/FeedTorExitAddresses/Integrations/FeedTorExitAddresses/FeedTorExitAddresses.yml
  Tests/secrets_white_list.json
Labels: docs-approved, release-notes-only

#6318 Qradar Query fix
  Packs/Legacy/Playbooks/playbook-QRadar_Indicator_Hunting_V2.yml
  Packs/Legacy/Playbooks/playbook-QRadar_Indicator_Hunting_V2_CHANGELOG.md
Labels: docs-approved

#6301 Splunk hunting playbook bug
  Packs/Legacy/Playbooks/playbook-Splunk_Indicator_Hunting.yml
  Packs/Legacy/Playbooks/playbook-Splunk_Indicator_Hunting_CHANGELOG.md
Labels: docs-approved

#6372 [sixgill-195] sixgill darkfeed integration
  Packs/Sixgill-Darkfeed/.pack-ignore
  Packs/Sixgill-Darkfeed/.secrets-ignore
  Packs/Sixgill-Darkfeed/CHANGELOG.md
  Packs/Sixgill-Darkfeed/Integrations/Sixgill_Darkfeed/CHANGELOG.md
  Packs/Sixgill-Darkfeed/Integrations/Sixgill_Darkfeed/README.md
  Packs/Sixgill-Darkfeed/Integrations/Sixgill_Darkfeed/Sixgill_Darkfeed.py
  Packs/Sixgill-Darkfeed/Integrations/Sixgill_Darkfeed/Sixgill_Darkfeed.yml
  Packs/Sixgill-Darkfeed/Integrations/Sixgill_Darkfeed/Sixgill_Darkfeed_description.md
  Packs/Sixgill-Darkfeed/Integrations/Sixgill_Darkfeed/Sixgill_Darkfeed_image.png
  Packs/Sixgill-Darkfeed/Integrations/Sixgill_Darkfeed/Sixgill_Darkfeed_test.py
  Packs/Sixgill-Darkfeed/README.md
  Packs/Sixgill-Darkfeed/pack_metadata.json
  Packs/Sixgill-DeepInsights/.pack-ignore
  Packs/Sixgill-DeepInsights/.secrets-ignore
  Packs/Sixgill-DeepInsights/CHANGELOG.md
  Packs/Sixgill-DeepInsights/Classifiers/classifier-eb70e27d-b3d6-4066-86dd-f70526d4ad85.json
  Packs/Sixgill-DeepInsights/IncidentFields/Sixgill_Alert_ID.json
  Packs/Sixgill-DeepInsights/IncidentFields/Sixgill_Content.json
  Packs/Sixgill-DeepInsights/IncidentFields/Sixgill_Threat_Level.json
  Packs/Sixgill-DeepInsights/IncidentFields/Sixgill_Threat_Type.json
  Packs/Sixgill-DeepInsights/IncidentTypes/Sixgill_Threat.json
  Packs/Sixgill-DeepInsights/Integrations/Sixgill/CHANGELOG.md
  Packs/Sixgill-DeepInsights/Integrations/Sixgill/README.md
  Packs/Sixgill-DeepInsights/Integrations/Sixgill/Sixgill.py
  Packs/Sixgill-DeepInsights/Integrations/Sixgill/Sixgill.yml
  Packs/Sixgill-DeepInsights/Integrations/Sixgill/Sixgill_description.md
  Packs/Sixgill-DeepInsights/Integrations/Sixgill/Sixgill_image.png
  Packs/Sixgill-DeepInsights/Integrations/Sixgill/Sixgill_test.py
  Packs/Sixgill-DeepInsights/Layouts/layout-details-Sixgill_Threat-V2.json
  Packs/Sixgill-DeepInsights/Layouts/layout-details-Sixgill_Threat-V2_CHANGELOG.md
  Packs/Sixgill-DeepInsights/README.md
  Packs/Sixgill-DeepInsights/TestPlaybooks/playbook-Sixgill-Test.yml
  Packs/Sixgill-DeepInsights/pack_metadata.json
  Packs/Sixgill/Integrations/Sixgill/CHANGELOG.md
  Packs/Sixgill/Integrations/Sixgill/README.md
  Packs/Sixgill/Integrations/Sixgill/Sixgill.yml
  Packs/Sixgill/Integrations/Sixgill/Sixgill_image.png
  Packs/Sixgill/Layouts/layout-details-Sixgill_Threat-V2_CHANGELOG.md
  Packs/Sixgill/Playbooks/playbook-Sixgill_-_DarkFeed_-_Indicators.yml
  Packs/Sixgill/Playbooks/playbook-Sixgill_-_DarkFeed_-_Indicators_CHANGELOG.md
  Packs/Sixgill/TestPlaybooks/playbook-Sixgill_-_Darkfeed_-_Indicators-Test.yml
  Packs/Sixgill/pack_metadata.json
Labels: Contribution, docs-approved

#6237 [expanse-272] Expanse Expander - Behavior/certificate API support
  Packs/Expanse/IncidentFields/incidentfield-ExpanseRawJSONEvent.json
  Packs/Expanse/IncidentFields/incidentfield-Expanse_Exposure_Type.json
  Packs/Expanse/IncidentFields/incidentfield-Expanse_Severity.json
  Packs/Expanse/IncidentTypes/incidenttype-Expanse_Behavior.json
  Packs/Expanse/Integrations/Expanse/CHANGELOG.md
  Packs/Expanse/Integrations/Expanse/Expanse.py
  Packs/Expanse/Integrations/Expanse/Expanse.yml
  Packs/Expanse/Integrations/Expanse/Expanse_test.py
  Packs/Expanse/Integrations/Expanse/README.md
  Packs/Expanse/pack_metadata.json
Labels: Contribution, docs-approved

#6428 [slashnext-251] SlashNext: Updating as per Cortex XSOAR name change.
  Packs/Legacy/Integrations/SlashNextPhishingIncidentResponse/CHANGELOG.md
  Packs/Legacy/Integrations/SlashNextPhishingIncidentResponse/README.md
  Packs/Legacy/Integrations/SlashNextPhishingIncidentResponse/SlashNextPhishingIncidentResponse.py
  Packs/Legacy/Integrations/SlashNextPhishingIncidentResponse/SlashNextPhishingIncidentResponse.yml
  Packs/Legacy/Integrations/SlashNextPhishingIncidentResponse/SlashNextPhishingIncidentResponse_description.md
Labels: Contribution, docs-approved

#6402 - Added 'using-brand: SlackV2' to the args of the 'send-notification' command
  Packs/Slack/Scripts/SlackAsk/CHANGELOG.md
  Packs/Slack/Scripts/SlackAsk/SlackAsk.py
  Packs/Slack/Scripts/SlackAsk/SlackAsk.yml
  Packs/Slack/Scripts/SlackAsk/SlackAsk_test.py
Labels: bug, docs-approved, release-notes-only

#6440 Artifacts gcs upload
  .circleci/config.yml
  .nvmrc
  Tests/scripts/upload_artifacts.sh
  Tests/scripts/validate_docker_images.sh
Labels: docs-approved

#6443 Docker hardening: improve memory check
  Packs/Legacy/Scripts/DockerHardeningCheck/CHANGELOG.md
  Packs/Legacy/Scripts/DockerHardeningCheck/DockerHardeningCheck.py
  Packs/Legacy/Scripts/DockerHardeningCheck/DockerHardeningCheck.yml
  Packs/Legacy/Scripts/DockerHardeningCheck/DockerHardeningCheck_test.py
  Packs/Legacy/Scripts/DockerHardeningCheck/README.md
Labels: docs-approved

#6272 Added commands created for POC to EC2
  Packs/Legacy/Integrations/AWS-EC2/AWS-EC2.py
  Packs/Legacy/Integrations/AWS-EC2/AWS-EC2.yml
  Packs/Legacy/Integrations/AWS-EC2/CHANGELOG.md
  Packs/Legacy/Integrations/AWS-EC2/README.md
Labels: docs-approved

#6419 README.md for slack failed logins playbook
  Packs/Slack/Playbooks/playbook-Slack_-_General_Failed_Logins_v2.1_README.md
  docs/images/playbooks/Slack_-_General_Failed_Logins_v2.1.png
Labels: docs-approved

#6334 Cortex xdr bug fix
  Packs/CortexXDR/.secrets-ignore
  Packs/CortexXDR/Integrations/PaloAltoNetworks_XDR/CHANGELOG.md
  Packs/CortexXDR/Integrations/PaloAltoNetworks_XDR/PaloAltoNetworks_XDR.py
  Packs/CortexXDR/Integrations/PaloAltoNetworks_XDR/PaloAltoNetworks_XDR.yml
  Packs/CortexXDR/Integrations/PaloAltoNetworks_XDR/PaloAltoNetworks_XDR_test.py
Labels: bug, docs-approved, release-notes-only

#6370 demisto/etc#23148: Wrapped vulnDB integration in base client
  Packs/Legacy/Integrations/VulnDB/CHANGELOG.md
  Packs/Legacy/Integrations/VulnDB/VulnDB.py
  Packs/Legacy/Integrations/VulnDB/VulnDB_test.py
  TestPlaybooks/playbook-VulnDB-Test.yml
  Tests/conf.json
Labels: docs-approved, release-notes-only

#6290 Fidelis - minor bug fixes, commands and readme files
  Packs/Legacy/Integrations/FidelisElevateNetwork/CHANGELOG.md
  Packs/Legacy/Integrations/FidelisElevateNetwork/FidelisElevateNetwork.py
  Packs/Legacy/Integrations/FidelisElevateNetwork/FidelisElevateNetwork.yml
  Packs/Legacy/Integrations/FidelisElevateNetwork/FidelisElevateNetwork_commands.txt
  Packs/Legacy/Integrations/FidelisElevateNetwork/README.md
  Tests/secrets_white_list.json
Labels: docs-approved

#6448 changed server version to 5.5.0
  .circleci/config.yml
Labels: docs-approved

#6283 Add default value when reading keys from data dictionary
  Packs/Legacy/Scripts/script-SandboxDetonateFile.yml
  Packs/Legacy/Scripts/script-SandboxDetonateFile_CHANGELOG.md
Labels: docs-approved, release-notes-only

#6327 add deprecated msg
  Packs/Legacy/Integrations/WindowsDefenderAdvancedThreatProtection/WindowsDefenderAdvancedThreatProtection.yml
  Packs/MicrosoftDefenderAdvancedThreatProtection/Integrations/MicrosoftDefenderAdvancedThreatProtection/CHANGELOG.md
  Packs/MicrosoftDefenderAdvancedThreatProtection/Integrations/MicrosoftDefenderAdvancedThreatProtection/MicrosoftDefenderAdvancedThreatProtection.py
Labels: docs-approved

#6123 Improved base client exception parsing
  Packs/Base/Scripts/CommonServerPython/CHANGELOG.md
  Packs/Base/Scripts/CommonServerPython/CommonServerPython.py
  Packs/Base/Scripts/CommonServerPython/CommonServerPython_test.py
Labels: docs-approved, release-notes-only

#6460 postgre - name fix
  Packs/Legacy/Integrations/integration-PostgreSQL.yml
Labels: docs-approved

#6394 [safebreach-129] SafeBreach Integration v2
  Packs/SafeBreach/.pack-ignore
  Packs/SafeBreach/.secrets-ignore
  Packs/SafeBreach/IncidentTypes/incidenttype-SafeBreach_Simulation.json
  Packs/SafeBreach/IndicatorFields/incidentfield-SafeBreach_Simulation_Id.json
  Packs/SafeBreach/Integrations/SafeBreach_v2/CHANGELOG.md
  Packs/SafeBreach/Integrations/SafeBreach_v2/README.md
  Packs/SafeBreach/Integrations/SafeBreach_v2/SafeBreach_v2.py
  Packs/SafeBreach/Integrations/SafeBreach_v2/SafeBreach_v2.yml
  Packs/SafeBreach/Integrations/SafeBreach_v2/SafeBreach_v2_description.md
  Packs/SafeBreach/Integrations/SafeBreach_v2/SafeBreach_v2_image.png
  Packs/SafeBreach/Integrations/SafeBreach_v2/SafeBreach_v2_test.py
  Packs/SafeBreach/Integrations/SafeBreach_v2/test_data/insights.json
  Packs/SafeBreach/Integrations/SafeBreach_v2/test_data/remediation_data.json
  Packs/SafeBreach/Integrations/SafeBreach_v2/test_data/simulation.json
  Packs/SafeBreach/Playbooks/SafeBreach_Insights_Feed_Playbook.yml
  Packs/SafeBreach/Playbooks/SafeBreach_Insights_Feed_Playbook_README.md
  Packs/SafeBreach/Playbooks/SafeBreach_Rerun_Insights.yml
  Packs/SafeBreach/Playbooks/SafeBreach_Rerun_Insights_README.md
  Packs/SafeBreach/README.md
  Packs/SafeBreach/TestPlaybooks/playbook-SafeBreach-Test.yml
  Packs/SafeBreach/pack_metadata.json
  Tests/conf.json
Labels: Contribution, docs-approved

#6427 Delete beta tim playbooks
  Packs/Legacy/Playbooks/playbook-ArcSight_Add_Domain_Indicators.yml
  Packs/Legacy/Playbooks/playbook-ArcSight_Add_Domain_Indicators_CHANGELOG.md
  Packs/Legacy/Playbooks/playbook-ArcSight_Add_Hash_Indicators.yml
  Packs/Legacy/Playbooks/playbook-ArcSight_Add_Hash_Indicators_CHANGELOG.md
  Packs/Legacy/Playbooks/playbook-ArcSight_Add_IP_Indicators.yml
  Packs/Legacy/Playbooks/playbook-ArcSight_Add_IP_Indicators_CHANGELOG.md
  Packs/Legacy/Playbooks/playbook-Process_Domain_Indicators.yml
  Packs/Legacy/Playbooks/playbook-Process_Domain_Indicators_CHANGELOG.md
  Packs/Legacy/Playbooks/playbook-Process_Hash_Indicators.yml
  Packs/Legacy/Playbooks/playbook-Process_Hash_Indicators_CHANGELOG.md
  Packs/Legacy/Playbooks/playbook-Process_IP_Indicators.yml
  Packs/Legacy/Playbooks/playbook-Process_IP_Indicators_CHANGELOG.md
  Packs/Legacy/Playbooks/playbook-Process_Url_Indicators.yml
  Packs/Legacy/Playbooks/playbook-Process_Url_Indicators_CHANGELOG.md
  Packs/Legacy/Playbooks/playbook-QRadar_Add_Domain_Indicators.yml
  Packs/Legacy/Playbooks/playbook-QRadar_Add_Domain_Indicators_CHANGELOG.md
  Packs/Legacy/Playbooks/playbook-QRadar_Add_IP_Indicators.yml
  Packs/Legacy/Playbooks/playbook-QRadar_Add_IP_Indicators_CHANGELOG.md
  Packs/Legacy/Playbooks/playbook-QRadar_Add_Url_Indicators.yml
  Packs/Legacy/Playbooks/playbook-QRadar_Add_Url_Indicators_CHANGELOG.md
  Packs/Legacy/Playbooks/playbook-QRadar_Add_hash_Indicators.yml
  Packs/Legacy/Playbooks/playbook-QRadar_Add_hash_Indicators_CHANGELOG.md
Labels: docs-approved

#6462 remove duplicate script - TTA
  Packs/Legacy/Scripts/StopTimeToAssignOnOwnerChange/CHANGELOG.md
  Packs/Legacy/Scripts/StopTimeToAssignOnOwnerChange/Pipfile
  Packs/Legacy/Scripts/StopTimeToAssignOnOwnerChange/Pipfile.lock
  Packs/Legacy/Scripts/StopTimeToAssignOnOwnerChange/StopTimeToAssignOnOwnerChange.py
  Packs/Legacy/Scripts/StopTimeToAssignOnOwnerChange/StopTimeToAssignOnOwnerChange.yml
  Packs/Legacy/Scripts/script-StopTimeToAssignOnOwnerChange.yml
  Packs/Legacy/Scripts/script-StopTimeToAssignOnOwnerChange_CHANGELOG.md
  Packs/Legacy/Scripts/script-StopTimeToAssignOnOwnerChange_README.md
Labels: docs-approved

#6469 Update secrets_white_list.json
  Tests/secrets_white_list.json
Labels: docs-approved

#6411 Slack: set max workers for default loop executor
  Packs/Slack/Integrations/Slack/CHANGELOG.md
  Packs/Slack/Integrations/Slack/Pipfile
  Packs/Slack/Integrations/Slack/Pipfile.lock
  Packs/Slack/Integrations/Slack/Slack.py
  Packs/Slack/Integrations/Slack/Slack.yml
  Packs/Slack/Integrations/Slack/Slack_test.py
Labels: docs-approved, release-notes-only

#6387 [smokescreen-technologies-pvt-ltd-573]: New Integration IllusionBLACK
  Packs/Smokescreen_IllusionBLACK/.pack-ignore
  Packs/Smokescreen_IllusionBLACK/.secrets-ignore
  Packs/Smokescreen_IllusionBLACK/CHANGELOG.md
  Packs/Smokescreen_IllusionBLACK/Classifiers/classifier-Smokescreen_IllusionBLACK.json
  Packs/Smokescreen_IllusionBLACK/IncidentFields/incidentfield-IllusionBLACK_Attack_Type.json
  Packs/Smokescreen_IllusionBLACK/IncidentFields/incidentfield-IllusionBLACK_Attacker_ID.json
  Packs/Smokescreen_IllusionBLACK/IncidentFields/incidentfield-IllusionBLACK_Decoy_ID.json
  Packs/Smokescreen_IllusionBLACK/IncidentFields/incidentfield-IllusionBLACK_Events.json
  Packs/Smokescreen_IllusionBLACK/IncidentFields/incidentfield-IllusionBLACK_Threat_Parse.json
  Packs/Smokescreen_IllusionBLACK/IncidentTypes/incidenttype-IllusionBLACK.json
  Packs/Smokescreen_IllusionBLACK/Integrations/Smokescreen_IllusionBLACK/CHANGELOG.md
  Packs/Smokescreen_IllusionBLACK/Integrations/Smokescreen_IllusionBLACK/Pipfile
  Packs/Smokescreen_IllusionBLACK/Integrations/Smokescreen_IllusionBLACK/Pipfile.lock
  Packs/Smokescreen_IllusionBLACK/Integrations/Smokescreen_IllusionBLACK/README.md
  Packs/Smokescreen_IllusionBLACK/Integrations/Smokescreen_IllusionBLACK/Smokescreen_IllusionBLACK.py
  Packs/Smokescreen_IllusionBLACK/Integrations/Smokescreen_IllusionBLACK/Smokescreen_IllusionBLACK.yml
  Packs/Smokescreen_IllusionBLACK/Integrations/Smokescreen_IllusionBLACK/Smokescreen_IllusionBLACK_description.md
  Packs/Smokescreen_IllusionBLACK/Integrations/Smokescreen_IllusionBLACK/Smokescreen_IllusionBLACK_image.png
  Packs/Smokescreen_IllusionBLACK/Integrations/Smokescreen_IllusionBLACK/Smokescreen_IllusionBLACK_test.py
  Packs/Smokescreen_IllusionBLACK/Layouts/layout-details-IllusionBLACK-V2.json
  Packs/Smokescreen_IllusionBLACK/Layouts/layout-details-IllusionBLACK-V2_CHANGELOG.md
  Packs/Smokescreen_IllusionBLACK/Playbooks/Smokescreen_IllusionBLACK_Default.yml
  Packs/Smokescreen_IllusionBLACK/README.md
  Packs/Smokescreen_IllusionBLACK/TestPlaybooks/Smokescreen_IllusionBLACK-Test.yml
  Packs/Smokescreen_IllusionBLACK/pack_metadata.json
  Tests/conf.json
Labels: Contribution, docs-approved

#6321 MongoDB 3 Contribution
  Packs/MongoDB/Integrations/MongoDBKeyValueStore/CHANGELOG.md
  Packs/MongoDB/Integrations/MongoDBKeyValueStore/MongoDBKeyValueStore-commands
  Packs/MongoDB/Integrations/MongoDBKeyValueStore/MongoDBKeyValueStore.png
  Packs/MongoDB/Integrations/MongoDBKeyValueStore/MongoDBKeyValueStore.py
  Packs/MongoDB/Integrations/MongoDBKeyValueStore/MongoDBKeyValueStore.yml
  Packs/MongoDB/Integrations/MongoDBKeyValueStore/MongoDBKeyValueStore_description.md
  Packs/MongoDB/Integrations/MongoDBKeyValueStore/Pipfile
  Packs/MongoDB/Integrations/MongoDBKeyValueStore/Pipfile.lock
  Packs/MongoDB/Integrations/MongoDBKeyValueStore/README.md
  Packs/MongoDB/Integrations/MongoDBLog/CHANGELOG.md
  Packs/MongoDB/Integrations/MongoDBLog/MongoDBLog-Commands
  Packs/MongoDB/Integrations/MongoDBLog/MongoDBLog.png
  Packs/MongoDB/Integrations/MongoDBLog/MongoDBLog.py
  Packs/MongoDB/Integrations/MongoDBLog/MongoDBLog.yml
  Packs/MongoDB/Integrations/MongoDBLog/MongoDBLog_description.md
  Packs/MongoDB/Integrations/MongoDBLog/Pipfile
  Packs/MongoDB/Integrations/MongoDBLog/Pipfile.lock
  Packs/MongoDB/Integrations/MongoDBLog/README.md
  Packs/MongoDB/TestPlaybooks/playbook-MongoDBLog_-_Test.yml
  Packs/MongoDB/TestPlaybooks/playbook-MongoDB_KeyValueStore_-_Test.yml
  Tests/conf.json
Labels: Contribution, docs-approved

#6352 Export indicators - on-demand error messages and csv to text functionality
  Packs/ExportIndicators/.secrets-ignore
  Packs/ExportIndicators/Integrations/ExportIndicators/CHANGELOG.md
  Packs/ExportIndicators/Integrations/ExportIndicators/ExportIndicators.py
  Packs/ExportIndicators/Integrations/ExportIndicators/ExportIndicators.yml
  Packs/ExportIndicators/Integrations/ExportIndicators/ExportIndicators_description.md
  Packs/ExportIndicators/Integrations/ExportIndicators/ExportIndicators_test.py
  Packs/ExportIndicators/Integrations/ExportIndicators/README.md
  Packs/Legacy/.secrets-ignore
  Packs/Legacy/Integrations/EDL/EDL_description.md
  Packs/Legacy/Integrations/EDL/README.md
  Tests/secrets_white_list.json
Labels: bug, docs-approved

#6424 added md files check
  release_notes.py
Labels: docs-approved

#6467 Marketplace - excluded properly test playbooks folder
  Tests/Marketplace/marketplace_services.py
Labels: docs-approved

#6474 [Test Fix] CBP v2 test playbook
  TestPlaybooks/playbook-CarbonBlackProtectV2-test.yml
Labels: docs-approved

#6471 fix bug in release_notes_clear.py
  release_notes_clear.py
Labels: docs-approved

#6450 Skip panorama query logs
  Tests/conf.json
Labels: docs-approved

#6481 Update release_notes.py
  release_notes.py
Labels: docs-approved

#6351 Polyswarm bug fix
  Packs/Legacy/Integrations/PolySwarm/CHANGELOG.md
  Packs/Legacy/Integrations/PolySwarm/PolySwarm.py
  Packs/Legacy/Integrations/PolySwarm/PolySwarm.yml
  Packs/Legacy/Integrations/PolySwarm/PolySwarm_test.py
Labels: bug, docs-approved

#6426 Packs uploader - Update index with private packs
  .circleci/config.yml
  Tests/Marketplace/Tests/test_data/metadata.json
  Tests/Marketplace/Tests/upload_packs_test.py
  Tests/Marketplace/upload_packs.py
Labels: docs-approved

#6466 Proofpoint TRAP - minor fixes
  Beta_Integrations/ProofpointThreatResponse/ProofpointThreatResponse.py
Labels: docs-approved

#6483 SafeBreach - fix fromversion
  Packs/SafeBreach/IncidentFields/incidentfield-SafeBreach_Simulation_Id.json
  Packs/SafeBreach/IncidentTypes/incidenttype-SafeBreach_Simulation.json
  Packs/SafeBreach/Playbooks/SafeBreach_Insights_Feed_Playbook.yml
Labels: docs-approved

#6436 Added the *action_parameters* argument and improved incident name in fetch
  Packs/Legacy/Integrations/Securonix/README.md
  Packs/Securonix/.pack-ignore
  Packs/Securonix/.secrets-ignore
  Packs/Securonix/CHANGELOG.md
  Packs/Securonix/Integrations/Securonix/CHANGELOG.md
  Packs/Securonix/Integrations/Securonix/Pipfile
  Packs/Securonix/Integrations/Securonix/Pipfile.lock
  Packs/Securonix/Integrations/Securonix/README.md
  Packs/Securonix/Integrations/Securonix/Securonix.py
  Packs/Securonix/Integrations/Securonix/Securonix.yml
  Packs/Securonix/Integrations/Securonix/Securonix_image.png
  Packs/Securonix/Integrations/Securonix/Securonix_test.py
  Packs/Securonix/Integrations/Securonix/examples.txt
  Packs/Securonix/Integrations/Securonix/test_data/response_constants.py
  Packs/Securonix/Integrations/Securonix/test_data/result_constants.py
  Packs/Securonix/README.md
  Packs/Securonix/pack_metadata.json
Labels: docs-approved

#6491 Secure private packs
  Tests/Marketplace/upload_packs.py
Labels: docs-approved

#6444 rename files so playbook docs are generated properly
  Packs/AutoFocus/.secrets-ignore
  Packs/AutoFocus/Playbooks/playbook-AutoFocusPolling_README.md
  Packs/AutoFocus/Playbooks/playbook-Autofocus_Query_Samples_and_Sessions_README.md
  Packs/AutoFocus/doc_files/AutoFocusPolling.png
  Packs/AutoFocus/doc_files/Autofocus_Query_Samples__Sessions_and_Tags.png
  Packs/Legacy/Playbooks/playbook-Default.yml
  Packs/Legacy/Playbooks/playbook-Default_CHANGELOG.md
  Packs/Legacy/Playbooks/playbook-Default_README.md
  Packs/Legacy/Playbooks/playbook-Traps_Retrieve_And_Download_Files.yml
  Packs/Legacy/Playbooks/playbook-Traps_Retrieve_And_Download_Files_CHANGELOG.md
Labels: docs-approved

#6309 Json generic readme
  .gitattributes
  Packs/FeedJSON/.secrets-ignore
  Packs/FeedJSON/Integrations/FeedJSON/README.md
  Packs/FeedJSON/Integrations/FeedJSON/demo_video/Json_generic_feed_demo.mp4
Labels: docs-approved

#6458 HelloWorld pack - added temporary changelog.json file
  Packs/HelloWorld/changelog.json
  Packs/HelloWorld/pack_metadata.json
Labels: docs-approved

#6497 Marketplace - uploader changes
  .circleci/config.yml
  Tests/Marketplace/Tests/marketplace_services_test.py
  Tests/Marketplace/marketplace_services.py
  Tests/Marketplace/upload_packs.py
Labels: docs-approved

#6432 Fix panorama query logs test
  TestPlaybooks/playbook-Panorama_Query_Logs_-_Test.yml
  Tests/secrets_white_list.json
Labels: docs-approved

#6405 update demisto mock to enforce at least one arg on info/error/debug
  Tests/demistomock/demistomock.py
Labels: docs-approved

#6452 Changed custom fields mapping to retrieve data from Whois context.
  Packs/Legacy/Misc/reputation-domain.json
  Packs/Legacy/Misc/reputation-domain_CHANGELOG.md
Labels: docs-approved, release-notes-only

#6281 Replaced the deprecated command cve-search to cve
  Packs/CVESearchV2/Integrations/CVESearchV2/CHANGELOG.md
  Packs/CVESearchV2/Integrations/CVESearchV2/CVESearchV2.py
  Packs/Legacy/Playbooks/playbook-CVE_Enrichment_-_Generic.yml
  Packs/Legacy/Playbooks/playbook-CVE_Enrichment_-_Generic_CHANGELOG.md
  Packs/Legacy/Scripts/script-CveReputation.yml
  Scripts/script-CveReputation_CHANGELOG.md
  Tests/conf.json
Labels: bug, docs-approved, release-notes-only

#6229 VT playbook move 2
  Packs/Legacy/Playbooks/playbook-Detonate_File-VirusTotal.yml
  Packs/Legacy/Playbooks/playbook-Detonate_File-VirusTotal_CHANGELOG.md
  TestPlaybooks/playbook-VirusTotal_detonate_file.yml
Labels: bug, docs-approved

#6386 Adding Readme for autofocus feed
  Packs/FeedAutofocus/.secrets-ignore
  Packs/FeedAutofocus/Integrations/FeedAutofocus/CHANGELOG.md
  Packs/FeedAutofocus/Integrations/FeedAutofocus/FeedAutofocus.yml
  Packs/FeedAutofocus/Integrations/FeedAutofocus/FeedAutofocus_commands
  Packs/FeedAutofocus/Integrations/FeedAutofocus/README.md
Labels: docs-approved

#6451 Tim playbooks images
  docs/images/playbooks/TIM_-_Add_All_Indicator_Types_To_SIEM.png
  docs/images/playbooks/TIM_-_Add_Bad_Hash_Indicators_To_SIEM.png
  docs/images/playbooks/TIM_-_Add_Domain_Indicators_To_SIEM.png
  docs/images/playbooks/TIM_-_Add_IP_Indicators_To_SIEM.png
  docs/images/playbooks/TIM_-_Add_Url_Indicators_To_SIEM.png
  docs/images/playbooks/TIM_-_ArcSight_Add_Bad_Hash_Indicators.png
  docs/images/playbooks/TIM_-_ArcSight_Add_Domain_Indicators.png
  docs/images/playbooks/TIM_-_ArcSight_Add_IP_Indicators.png
  docs/images/playbooks/TIM_-_ArcSight_Add_Url_Indicators.png
  docs/images/playbooks/TIM_-_Indicator_Auto_Processing.png
  docs/images/playbooks/TIM_-_Process_File_Indicators_With_File_Hash_Type.png
  docs/images/playbooks/TIM_-_Process_Indicators_-_Fully_Automated.png
  docs/images/playbooks/TIM_-_Process_Indicators_-_Manual_Review.png
  docs/images/playbooks/TIM_-_Process_Indicators_Against_Approved_Hash_List.png
  docs/images/playbooks/TIM_-_Process_Indicators_Against_Business_Partners_Domains.png
  docs/images/playbooks/TIM_-_Process_Indicators_Against_Business_Partners_IP_List.png
  docs/images/playbooks/TIM_-_Process_Indicators_Against_Business_Partners_URL_List.png
  docs/images/playbooks/TIM_-_Process_Indicators_Against_Organizations_External_IP_List.png
  docs/images/playbooks/TIM_-_QRadar_Add_Bad_Hash_Indicators.png
  docs/images/playbooks/TIM_-_QRadar_Add_Domain_Indicators.png
  docs/images/playbooks/TIM_-_QRadar_Add_IP_Indicators.png
  docs/images/playbooks/TIM_-_QRadar_Add_Url_Indicators.png
  docs/images/playbooks/TIM_-_Review_Indicators_Manually.png
  docs/images/playbooks/TIM_-_Run_Enrichment_For_All_Indicator_Types.png
  docs/images/playbooks/TIM_-_Run_Enrichment_For_Domain_Indicators.png
  docs/images/playbooks/TIM_-_Run_Enrichment_For_Hash_Indicators.png
  docs/images/playbooks/TIM_-_Run_Enrichment_For_IP_Indicators.png
  docs/images/playbooks/TIM_-_Run_Enrichment_For_Url_Indicators.png
Labels: docs-approved

#6510 fixed typo in X-Force
  Packs/XForceExchange/Integrations/XFE_v2/CHANGELOG.md
  Packs/XForceExchange/Integrations/XFE_v2/XFE_v2.yml
Labels: bug, docs-approved

#6506 remove sixgill darkfeed test playbook - the old playbook was deleted
  Tests/conf.json
Labels: docs-approved

#6356 Demisto-sdk lint conf change
  .circleci/config.yml
  .hooks/pre-commit
  dev-requirements-py3.txt
Labels: docs-approved

#6324 introduce reputation classes in CommonServerPython
  Documentation/common_server_docs.py
  Packs/AutoFocus/Integrations/AutofocusV2/AutofocusV2.py
  Packs/AutoFocus/Integrations/AutofocusV2/AutofocusV2_test.py
  Packs/AutoFocus/Integrations/AutofocusV2/CHANGELOG.md
  Packs/Base/.secrets-ignore
  Packs/Base/Scripts/CommonServerPython/CHANGELOG.md
  Packs/Base/Scripts/CommonServerPython/CommonServerPython.py
  Packs/Base/Scripts/CommonServerPython/CommonServerPython_test.py
  Packs/Legacy/Integrations/AlienVault_OTX_v2/AlienVault_OTX_v2.py
  Packs/Legacy/Integrations/AlienVault_OTX_v2/CHANGELOG.md
  Packs/Legacy/Integrations/CounterCraft/CHANGELOG.md
  Packs/Legacy/Integrations/CounterCraft/CounterCraft.py
  Packs/Legacy/Integrations/CounterCraft/CounterCraft.yml
  Packs/Legacy/Integrations/PhishLabsIOC_EIR/CHANGELOG.md
  Packs/Legacy/Integrations/PhishLabsIOC_EIR/PhishLabsIOC_EIR.py
  Packs/Legacy/Integrations/PhishLabsIOC_EIR/PhishLabsIOC_EIR.yml
  Tests/demistomock/demistomock.py
Labels: docs-approved

#6414 Filters - num of availble addresses in CIDR IPv6 / IPv4
  Packs/Legacy/Scripts/GreaterCidrNumAddresses/.secrets-ignore
  Packs/Legacy/Scripts/GreaterCidrNumAddresses/CHANGELOG.md
  Packs/Legacy/Scripts/GreaterCidrNumAddresses/GreaterCidrNumAddresses.py
  Packs/Legacy/Scripts/GreaterCidrNumAddresses/GreaterCidrNumAddresses.yml
  Packs/Legacy/Scripts/GreaterCidrNumAddresses/GreaterCidrNumAddresses_test.py
  Packs/Legacy/Scripts/IPNetwork/.secrets-ignore
  Packs/Legacy/Scripts/IPNetwork/CHANGELOG.md
  Packs/Legacy/Scripts/IPNetwork/IPNetwork.py
  Packs/Legacy/Scripts/IPNetwork/IPNetwork.yml
  Packs/Legacy/Scripts/IPNetwork/IPNetwork_test.py
  Packs/Legacy/Scripts/IPNetwork/IPNetwork_test/.secrets-ignore
  Packs/Legacy/Scripts/IPNetwork/IPNetwork_test/ipv4_cidr.json
  Packs/Legacy/Scripts/IPNetwork/IPNetwork_test/ipv6_cidr.json
  Packs/Legacy/Scripts/IPNetwork/Pipfile
  Packs/Legacy/Scripts/IPNetwork/Pipfile.lock
  Packs/Legacy/Scripts/LowerCidrNumAddresses/.secrets-ignore
  Packs/Legacy/Scripts/LowerCidrNumAddresses/CHANGELOG.md
  Packs/Legacy/Scripts/LowerCidrNumAddresses/LowerCidrNumAddresses.py
  Packs/Legacy/Scripts/LowerCidrNumAddresses/LowerCidrNumAddresses.yml
  Packs/Legacy/Scripts/LowerCidrNumAddresses/LowerCidrNumAddresses_test.py
Labels: docs-approved

#6507 Securonix fetch bug - incident_status not taken into account
  Packs/Securonix/Integrations/Securonix/CHANGELOG.md
  Packs/Securonix/Integrations/Securonix/README.md
  Packs/Securonix/Integrations/Securonix/Securonix.py
  Packs/Securonix/Integrations/Securonix/Securonix.yml
  Packs/Securonix/Integrations/Securonix/commands_examples.txt
Labels: bug, docs-approved, release-notes-only

#6473 ProtectWise added token parameter
  Packs/Legacy/Integrations/integration-ProtectWise.yml
  Packs/Legacy/Integrations/integration-ProtectWise_CHANGELOG.md
Labels: docs-approved

#6418 Teams - adding readme and related files
  Packs/Legacy/Integrations/MicrosoftTeams/MicrosoftTeams_commands.txt
  Packs/Legacy/Integrations/MicrosoftTeams/README.md
  Packs/Legacy/Integrations/MicrosoftTeams/doc_files/DemistoBot.zip
  Packs/Legacy/Integrations/MicrosoftTeams/doc_files/MSTeams-BotID.png
  Packs/Legacy/Integrations/MicrosoftTeams/doc_files/MicrosoftTeamsProtocalDiagram.png
Labels: docs-approved

#6412 BigQuery - Convert date to string
  Packs/Legacy/Integrations/GoogleBigQuery/CHANGELOG.md
  Packs/Legacy/Integrations/GoogleBigQuery/GoogleBigQuery.py
  Packs/Legacy/Integrations/GoogleBigQuery/GoogleBigQuery_test.py
Labels: docs-approved, release-notes-only

#6439 dont fail on skipped integrations
  Tests/scripts/configure_tests.py
  Tests/scripts/infrastructure_tests/test_configure_tests.py
  Tests/scripts/infrastructure_tests/tests_data/mock_integrations/fake_integration.yml
  Tests/scripts/infrastructure_tests/tests_data/mock_integrations/future_integration_2.yml
  Tests/scripts/infrastructure_tests/tests_data/mock_integrations/past_integration_1.yml
  Tests/scripts/infrastructure_tests/tests_data/mock_test_playbooks/past_test_playbook_1.yml
Labels: docs-approved

#6293 Created README file for MS graph mail
  Packs/Legacy/.secrets-ignore
  Packs/Legacy/Integrations/MicrosoftGraphMail/CHANGELOG.md
  Packs/Legacy/Integrations/MicrosoftGraphMail/MicrosoftGraphMail.py
  Packs/Legacy/Integrations/MicrosoftGraphMail/README.md
  Packs/Legacy/Integrations/MicrosoftGraphMail/commands.txt
Labels: docs-approved

#6516 Skipped Trend Micro Apex
  Tests/conf.json
Labels: docs-approved

#6198 CrowdStrike Falcon Streaming v2
  Beta_Integrations/CrowdStrikeFalconStreamingV2/CHANGELOG.md
  Beta_Integrations/CrowdStrikeFalconStreamingV2/CrowdStrikeFalconStreamingV2.py
  Beta_Integrations/CrowdStrikeFalconStreamingV2/CrowdStrikeFalconStreamingV2.yml
  Beta_Integrations/CrowdStrikeFalconStreamingV2/CrowdStrikeFalconStreamingV2_description.md
  Beta_Integrations/CrowdStrikeFalconStreamingV2/CrowdStrikeFalconStreamingV2_image.png
  Beta_Integrations/CrowdStrikeFalconStreamingV2/Pipfile
  Beta_Integrations/CrowdStrikeFalconStreamingV2/Pipfile.lock
  Beta_Integrations/CrowdStrikeFalconStreamingV2/README.md
Labels: docs-approved

#6518 Fixed an issue in which the *job_id* argument in the ***panorama-down…
  Packs/Legacy/Integrations/Panorama/CHANGELOG.md
  Packs/Legacy/Integrations/Panorama/Panorama.py
Labels: bug, docs-approved, release-notes-only

#6332 SNOW v2
  Packs/ServiceNow/.secrets-ignore
  Packs/ServiceNow/Integrations/ServiceNow/CHANGELOG.md
  Packs/ServiceNow/Integrations/ServiceNow/commands.txt
  Packs/ServiceNow/Integrations/ServiceNowv2/CHANGELOG.md
  Packs/ServiceNow/Integrations/ServiceNowv2/ServiceNowv2.py
  Packs/ServiceNow/Integrations/ServiceNowv2/ServiceNowv2.yml
  Packs/ServiceNow/Integrations/ServiceNowv2/ServiceNowv2_description.md
  Packs/ServiceNow/Integrations/ServiceNowv2/ServiceNowv2_image.png
  Packs/ServiceNow/Integrations/ServiceNowv2/ServiceNowv2_test.py
  Packs/ServiceNow/Integrations/ServiceNowv2/test_data/response_constants.py
  Packs/ServiceNow/Integrations/ServiceNowv2/test_data/result_constants.py
  TestPlaybooks/NonCircleTests/playbook-ServiceNow_Test_New.yml
Labels: docs-approved

#6534 fix configure tests
  Tests/conf.json
  Tests/scripts/configure_tests.py
  Tests/scripts/infrastructure_tests/test_configure_tests.py
Labels: docs-approved

#6529 AwsGetInstanceInfo - deprecate the script
  Packs/Legacy/Scripts/script-AwsGetInstanceInfo.yml
  Packs/Legacy/Scripts/script-AwsGetInstanceInfo_CHANGELOG.md
Labels: bug, docs-approved, release-notes-only

#6540 chamge the group
  TestPlaybooks/playbook-ThreatConnect_Test.yml
Labels: docs-approved

#6447 AutoFocus v2 - added support for upper case hash
  Packs/AutoFocus/Integrations/AutofocusV2/AutofocusV2.py
  Packs/AutoFocus/Integrations/AutofocusV2/CHANGELOG.md
  Packs/AutoFocus/TestPlaybooks/playbook-AutoFocus_V2_test.yml
Labels: bug, docs-approved, release-notes-only

#6521 Packs - Keep metadata files in index
  Tests/Marketplace/Tests/upload_packs_test.py
  Tests/Marketplace/upload_packs.py
Labels: docs-approved

#6371 possible fix using emoji
  Packs/Legacy/.secrets-ignore
  Packs/Legacy/Integrations/Anomali_ThreatStream_v2/Anomali_ThreatStream_v2.py
  Packs/Legacy/Integrations/Anomali_ThreatStream_v2/Anomali_ThreatStream_v2.yml
  Packs/Legacy/Integrations/Anomali_ThreatStream_v2/Anomali_ThreatStream_v2_test.py
  Packs/Legacy/Integrations/Anomali_ThreatStream_v2/CHANGELOG.md
Labels: bug, docs-approved, release-notes-only

#6535 abuse.ch SSL Blacklist Feed - switching creationdate to firstseenbyfeed - reopened
  Packs/ApiModules/.secrets-ignore
  Packs/ApiModules/Scripts/CSVFeedApiModule/CHANGELOG.md
  Packs/ApiModules/Scripts/CSVFeedApiModule/CSVFeedApiModule.py
  Packs/ApiModules/Scripts/CSVFeedApiModule/CSVFeedApiModule_test.py
  Packs/Feedsslabusech/Integrations/Feedsslabusech/CHANGELOG.md
  Packs/Feedsslabusech/Integrations/Feedsslabusech/Feedsslabusech.py
Labels: bug, docs-approved, release-notes-only

#6532 unskipped rf feed
  Tests/conf.json
Labels: docs-approved

#6541 SNOWv2. - Ignore auto-extract for war-room entries of the CRUD tickets, records…
  Packs/ServiceNow/.secrets-ignore
  Packs/ServiceNow/Integrations/ServiceNowv2/CHANGELOG.md
  Packs/ServiceNow/Integrations/ServiceNowv2/ServiceNowv2.py
  Packs/ServiceNow/Integrations/ServiceNowv2/ServiceNowv2_test.py
Labels: docs-approved

#6277 Disabled resilient.co3 warnings logs
  Packs/Legacy/Integrations/integration-IBM_Resilient_Systems.yml
  Packs/Legacy/Integrations/integration-IBM_Resilient_Systems_CHANGELOG.md
  Tests/conf.json
Labels: bug, docs-approved, release-notes-only

#6546 Added mapping to service field
  Packs/FeedAWS/.secrets-ignore
  Packs/FeedAWS/Integrations/FeedAWS/CHANGELOG.md
  Packs/FeedAWS/Integrations/FeedAWS/FeedAWS.py
  Packs/Legacy/IndicatorFields/incidentfield-service.json
  Packs/Legacy/IndicatorFields/incidentfield-service_CHANGELOG.md
Labels: bug, docs-approved, release-notes-only

#6406 Tim playbooks documentation
  Packs/Legacy/Playbooks/playbook-TIM_-_Add_All_Indicator_Types_To_SIEM_README.md
  Packs/Legacy/Playbooks/playbook-TIM_-_Add_Bad_Hash_Indicators_To_SIEM_README.md
  Packs/Legacy/Playbooks/playbook-TIM_-_Add_Domain_Indicators_To_SIEM_README.md
  Packs/Legacy/Playbooks/playbook-TIM_-_Add_IP_Indicators_To_SIEM_README.md
  Packs/Legacy/Playbooks/playbook-TIM_-_Add_Url_Indicators_To_SIEM_README.md
  Packs/Legacy/Playbooks/playbook-TIM_-_ArcSight_Add_Bad_Hash_Indicators_README.md
  Packs/Legacy/Playbooks/playbook-TIM_-_ArcSight_Add_Domain_Indicators_README.md
  Packs/Legacy/Playbooks/playbook-TIM_-_ArcSight_Add_IP_Indicators_README.md
  Packs/Legacy/Playbooks/playbook-TIM_-_ArcSight_Add_Url_Indicators_README.md
  Packs/Legacy/Playbooks/playbook-TIM_-_Indicator_Auto_Processing_README.md
  Packs/Legacy/Playbooks/playbook-TIM_-_Process_File_Indicators_With_File_Hash_Type_README.md
  Packs/Legacy/Playbooks/playbook-TIM_-_Process_Indicators_-_Fully_Automated_README.md
  Packs/Legacy/Playbooks/playbook-TIM_-_Process_Indicators_Against_Approved_Hash_List_README.md
  Packs/Legacy/Playbooks/playbook-TIM_-_Process_Indicators_Against_Business_Partners_Domains_List_README.md
  Packs/Legacy/Playbooks/playbook-TIM_-_Process_Indicators_Against_Business_Partners_IP_List_README.md
  Packs/Legacy/Playbooks/playbook-TIM_-_Process_Indicators_Against_Business_Partners_URL_List_README.md
  Packs/Legacy/Playbooks/playbook-TIM_-_Process_Indicators_Against_Organizations_External_IP_List_README.md
  Packs/Legacy/Playbooks/playbook-TIM_-_Process_Indicators_Manual_Review_README.md
  Packs/Legacy/Playbooks/playbook-TIM_-_QRadar_Add_Bad_Hash_Indicators_README.md
  Packs/Legacy/Playbooks/playbook-TIM_-_QRadar_Add_Domain_Indicators_README.md
  Packs/Legacy/Playbooks/playbook-TIM_-_QRadar_Add_IP_Indicators_README.md
  Packs/Legacy/Playbooks/playbook-TIM_-_QRadar_Add_Url_Indicators_README.md
  Packs/Legacy/Playbooks/playbook-TIM_-_Review_Indicators_Manually_README.md
  Packs/Legacy/Playbooks/playbook-TIM_-_Run_Enrichment_For_All__Indicator_Types_README.md
  Packs/Legacy/Playbooks/playbook-TIM_-_Run_Enrichment_For_Domain_Indicators_README.md
  Packs/Legacy/Playbooks/playbook-TIM_-_Run_Enrichment_For_Hash_Indicators_README.md
  Packs/Legacy/Playbooks/playbook-TIM_-_Run_Enrichment_For_IP_Indicators_README.md
  Packs/Legacy/Playbooks/playbook-TIM_-_Run_Enrichment_For_Url_Indicators_README.md
  Tests/secrets_white_list.json
Labels: docs-approved

#6549 Remove slack threshold
  Tests/conf.json
Labels: docs-approved

#6509 Genericsql bugs: mysql.user table is available and context fixed
  Packs/GenericSQL/Integrations/GenericSQL/CHANGELOG.md
  Packs/GenericSQL/Integrations/GenericSQL/GenericSQL.py
  Packs/GenericSQL/Integrations/GenericSQL/GenericSQL.yml
  Packs/GenericSQL/Integrations/GenericSQL/GenericSQL_test.py
Labels: bug, content, docs-approved, release-notes-only

#6537 adding readme and video demo to AlienVaultOTXFeed
  Packs/FeedAlienVault/.secrets-ignore
  Packs/FeedAlienVault/Integrations/FeedAlienVaultOTXTaxii/FeedAlienVaultOTXTaxii_commands.txt
  Packs/FeedAlienVault/Integrations/FeedAlienVaultOTXTaxii/README.md
  Packs/FeedAlienVault/Integrations/FeedAlienVaultOTXTaxii/doc_files/AlienVault_OTX_Feed_Demo.mp4
Labels: docs-approved

#6559 update hello world image
  Packs/HelloWorld/Integrations/HelloWorld/HelloWorld_image.png
Labels: docs-approved

#6508 detect if artifacts directory does not exist
  Tests/scripts/upload_artifacts.sh
Labels: docs-approved

#6416 Bug fix find similiar incidents
  Packs/Legacy/Scripts/FindSimilarIncidentsV2/CHANGELOG.md
  Packs/Legacy/Scripts/FindSimilarIncidentsV2/FindSimilarIncidentsV2.py
  Packs/Legacy/Scripts/FindSimilarIncidentsV2/FindSimilarIncidentsV2.yml
  Packs/Legacy/Scripts/FindSimilarIncidentsV2/find_similar_incidents_test.py
Labels: bug, docs-approved, release-notes-only

#6530 Zipfile escape illegal chars in file name
  Packs/Legacy/Scripts/ZipFile/CHANGELOG.md
  Packs/Legacy/Scripts/ZipFile/ZipFile.py
  Packs/Legacy/Scripts/ZipFile/ZipFile.yml
  Packs/Legacy/Scripts/ZipFile/ZipFile_test.py
Labels: bug, docs-approved, release-notes-only

#6552 Fix instance test
  Tests/scripts/instance_test.sh
Labels: docs-approved

#6564 added memory threshold to recorded future feed on build
  Tests/conf.json
Labels: docs-approved

#6285 Get User Manager Details - Fixed input check + error handling
  Packs/Active_Directory_Query/Playbooks/Active_Directory_-_Get_User_Manager_Email.yml
  Packs/Active_Directory_Query/Playbooks/Active_Directory_-_Get_User_Manager_Email_CHANGELOG.md
  Tests/conf.json
Labels: docs-approved, release-notes-only

#6567 Increase Slack PID threshold
  Packs/Slack/Integrations/Slack/CHANGELOG.md
  Packs/Slack/Integrations/Slack/Slack.py
  Tests/conf.json
Labels: docs-approved

#6571 Added support for the *sc_req_item* table - CRUD ticket commands
  Packs/ServiceNow/Integrations/ServiceNowv2/CHANGELOG.md
  Packs/ServiceNow/Integrations/ServiceNowv2/ServiceNowv2.py
  Packs/ServiceNow/Integrations/ServiceNowv2/ServiceNowv2.yml
  Packs/ServiceNow/Integrations/ServiceNowv2/ServiceNowv2_test.py
  Packs/ServiceNow/Integrations/ServiceNowv2/test_data/response_constants.py
  Packs/ServiceNow/Integrations/ServiceNowv2/test_data/result_constants.py
Labels: docs-approved

#6562 [expanse-272] Expanse Expander - Fixing incident polling bug
  Packs/Expanse/Integrations/Expanse/CHANGELOG.md
  Packs/Expanse/Integrations/Expanse/Expanse.py
  Packs/Expanse/pack_metadata.json
Labels: Contribution, docs-approved, release-notes-only
