Repository demisto/content, pull requests merged in 2020-07, with the labels that each got.

#7787 ParseEmailFiles - add support for message/rfc822 eml type
  Packs/CommonScripts/ReleaseNotes/1_1_14.md
  Packs/CommonScripts/Scripts/ParseEmailFiles/ParseEmailFiles.py
  Packs/CommonScripts/Scripts/ParseEmailFiles/parse_email_files_test.py
  Packs/CommonScripts/pack_metadata.json
Labels: docs-approved, release-notes-only

#7785 Checking if workflow holding a lock is still running
  Tests/test_content.py
Labels: docs-approved

#7761 TIM packs descriptions
  Packs/TIM_Processing/README.md
  Packs/TIM_Processing/ReleaseNotes/1_1_2.md
  Packs/TIM_Processing/pack_metadata.json
  Packs/TIM_SIEM/README.md
  Packs/TIM_SIEM/ReleaseNotes/1_0_1.md
  Packs/TIM_SIEM/pack_metadata.json
Labels: docs-approved

#7789 base64 test fix
  Packs/CommonScripts/TestPlaybooks/playbook-Base64_File_in_List_Test.yml
Labels: docs-approved

#7685 [Enhancement] US Breach Notification - New layout
  Packs/BreachNotification-US/Layouts/layout-details-US_Breach_Notification-V2.json
  Packs/BreachNotification-US/Layouts/layout-details-US_Breach_Notification-V2_CHANGELOG.md
  Packs/BreachNotification-US/Playbooks/playbook-California_-_Breach_Notification.yml
  Packs/BreachNotification-US/Playbooks/playbook-California_-_Breach_Notification_CHANGELOG.md
  Packs/BreachNotification-US/Playbooks/playbook-Illinois_-_Breach_Notification.yml
  Packs/BreachNotification-US/Playbooks/playbook-Illinois_-_Breach_Notification_README.md
  Packs/BreachNotification-US/Playbooks/playbook-New_York_-_Breach_Notification.yml
  Packs/BreachNotification-US/Playbooks/playbook-New_York_-_Breach_Notification_CHANGELOG.md
  Packs/BreachNotification-US/Playbooks/playbook-Residents_Notification_-_Breach_Notification.yml
  Packs/BreachNotification-US/Playbooks/playbook-Residents_Notification_-_Breach_Notification_CHANGELOG.md
  Packs/BreachNotification-US/README.md
  Packs/BreachNotification-US/ReleaseNotes/1_0_3.md
  Packs/BreachNotification-US/pack_metadata.json
  Packs/Compliance/IncidentFields/incidentfield-Attorney_General_Notification.json
  Packs/Compliance/IncidentFields/incidentfield-Attorney_General_Notification_CHANGELOG.md
  Packs/Compliance/IncidentFields/incidentfield-Breach_Confirmation.json
  Packs/Compliance/IncidentFields/incidentfield-Breach_Confirmation_CHANGELOG.md
  Packs/Compliance/IncidentFields/incidentfield-Consumer_Reporting_Agencies_Notification.json
  Packs/Compliance/IncidentFields/incidentfield-Consumer_Reporting_Agencies_Notification_CHANGELOG.md
  Packs/Compliance/IncidentFields/incidentfield-DPO_Notification.json
  Packs/Compliance/IncidentFields/incidentfield-DPO_Notification_CHANGELOG.md
  Packs/Compliance/IncidentFields/incidentfield-Individuals_Notification.json
  Packs/Compliance/IncidentFields/incidentfield-Individuals_Notification_CHANGELOG.md
  Packs/Compliance/IncidentFields/incidentfield-Management_Notification.json
  Packs/Compliance/IncidentFields/incidentfield-Management_Notification_CHANGELOG.md
  Packs/Compliance/IncidentFields/incidentfield-Media_Notification.json
  Packs/Compliance/IncidentFields/incidentfield-Media_Notification_CHANGELOG.md
  Packs/Compliance/IncidentFields/incidentfield-Secretary_Notification.json
  Packs/Compliance/IncidentFields/incidentfield-Secretary_Notification_CHANGELOG.md
  Packs/Compliance/IncidentFields/incidentfield-State_CISO_Notification.json
  Packs/Compliance/IncidentFields/incidentfield-State_CISO_Notification_CHANGELOG.md
  Packs/Compliance/ReleaseNotes/1_0_2.md
  Packs/Compliance/Scripts/automation-BreachConfirmationHTML.yml
  Packs/Compliance/pack_metadata.json
Labels: docs-approved, release-notes-only

#7760 Added pack description to Malware README.
  Packs/Malware/README.md
  Packs/Malware/ReleaseNotes/1_2_0.md
  Packs/Malware/pack_metadata.json
Labels: docs-approved

#7742 Search and install updates
  Tests/Marketplace/Tests/search_and_install_packs_test.py
  Tests/Marketplace/search_and_install_packs.py
  Tests/configure_and_test_integration_instances.py
  Tests/scripts/collect_tests_and_content_packs.py
Labels: docs-approved

#7466 adding script to create old content branch
  Utils/old_content_branch.py
  Utils/tests/old_content_branch_test.py
Labels: docs-approved

#7731 Add layout for BPA pack
  Packs/BPA/IncidentTypes/incidenttype-Panorama_Best_Practice_Assessment.json
  Packs/BPA/Layouts/layout-Panorama_Best_Practice_Assessment.json
  Packs/BPA/Playbooks/playbook-BPA.yml
  Packs/BPA/Playbooks/playbook-Comprehensive_PAN-OS_Best_Practice_Assessment.yml
  Packs/BPA/ReleaseNotes/1_2_0.md
  Packs/BPA/doc_files/Comprehensive_PAN-OS_Best_Practice_Assessment.png
  Packs/BPA/pack_metadata.json
Labels: docs-approved

#7796 Breach confirmation fix
  Packs/Compliance/Scripts/script-BreachConfirmationHTML.yml
Labels: docs-approved

#7697 [infocyte-604] fix error message on no new incidents
  Packs/Infocyte/Integrations/Infocyte/Infocyte.ps1
  Packs/Infocyte/ReleaseNotes/1_0_1.md
  Packs/Infocyte/pack_metadata.json
Labels: Contribution, docs-approved

#7795 Adding SNDBOX to parallel integrations list
  Tests/conf.json
Labels: docs-approved

#7721 New phishing tests on 6.0, old tests removed
  Packs/CommonScripts/ReleaseNotes/1_2_0.md
  Packs/CommonScripts/Scripts/IdentifyAttachedEmail/IdentifyAttachedEmail.yml
  Packs/CommonScripts/pack_metadata.json
  Packs/DeveloperTools/TestPlaybooks/Process_Email_-_Generic_-_Test_-_Actual_Incident.yml
  Packs/DeveloperTools/TestPlaybooks/Process_Email_-_Generic_-_Test_-_Incident_Starter.yml
  Packs/Phishing/Playbooks/Phishing_-_Core.yml
  Packs/Phishing/Playbooks/Phishing_Investigation_-_Generic_v2.yml
  Packs/Phishing/Playbooks/Process_Email_-_Core.yml
  Packs/Phishing/Playbooks/Process_Email_-_Generic.yml
  Packs/Phishing/ReleaseNotes/1_7_0.md
  Packs/Phishing/TestPlaybooks/Phishing_-_Core_-_Test_-_Actual_Incident.yml
  Packs/Phishing/TestPlaybooks/Phishing_-_Core_-_Test_-_Incident_Starter.yml
  Packs/Phishing/TestPlaybooks/Phishing_v2_-_Test_-_Actual_Incident.yml
  Packs/Phishing/TestPlaybooks/Phishing_v2_-_Test_-_Incident_Starter.yml
  Packs/Phishing/pack_metadata.json
  TestPlaybooks/NonCircleTests/playbook-Phishing_-_Core_-_Test.yml
  TestPlaybooks/NonCircleTests/playbook-Phishing_v2_Test_-_Attachment.yml
  TestPlaybooks/NonCircleTests/playbook-Phishing_v2_Test_-_Inline.yml
  TestPlaybooks/NonCircleTests/playbook-Process_Email_-_Generic_-_Test.yml
  TestPlaybooks/NonCircleTests/script-PhishingIncident.yml
  Tests/conf.json
Labels: docs-approved

#7781 Crisis Management readme
  Packs/CrisisManagement/README.md
  Packs/CrisisManagement/ReleaseNotes/1_1_2.md
  Packs/CrisisManagement/pack_metadata.json
Labels: docs-approved

#7766 Impossible Traveler - New Pack Readme
  Packs/ImpossibleTraveler/README.md
  Packs/ImpossibleTraveler/ReleaseNotes/1_1_1.md
  Packs/ImpossibleTraveler/pack_metadata.json
Labels: docs-approved

#7770 Symantec Management Center - add support for LOCAL_CATEGORY_DB content type
  Packs/SymantecManagementCenter/Integrations/SymantecManagementCenter/Pipfile
  Packs/SymantecManagementCenter/Integrations/SymantecManagementCenter/Pipfile.lock
  Packs/SymantecManagementCenter/Integrations/SymantecManagementCenter/README.md
  Packs/SymantecManagementCenter/Integrations/SymantecManagementCenter/SymantecManagementCenter.py
  Packs/SymantecManagementCenter/Integrations/SymantecManagementCenter/SymantecManagementCenter.yml
  Packs/SymantecManagementCenter/Integrations/SymantecManagementCenter/SymantecManagementCenter_test.py
  Packs/SymantecManagementCenter/ReleaseNotes/1_0_1.md
  Packs/SymantecManagementCenter/pack_metadata.json
  Tests/conf.json
Labels: docs-approved

#7738 Pcap playbooks incident
  Packs/CommonTypes/IncidentFields/incidentfield-External_Addresses.json
  Packs/CommonTypes/IncidentFields/incidentfield-Internal_Addresses.json
  Packs/CommonTypes/IncidentFields/incidentfield-Protocols.json
  Packs/CommonTypes/IncidentFields/incidentfields-Unique_Ports.json
  Packs/CommonTypes/ReleaseNotes/1_2_4.md
  Packs/PcapAnalysis/.secrets-ignore
  Packs/PcapAnalysis/IncidentFields/incidentfield-PCAP_Encryption_Key.json
  Packs/PcapAnalysis/IncidentFields/incidentfield-PCAP_End_Time.json
  Packs/PcapAnalysis/IncidentFields/incidentfield-PCAP_File.json
  Packs/PcapAnalysis/IncidentFields/incidentfield-PCAP_File_Name.json
  Packs/PcapAnalysis/IncidentFields/incidentfield-PCAP_File_Size.json
  Packs/PcapAnalysis/IncidentFields/incidentfield-PCAP_Flows.json
  Packs/PcapAnalysis/IncidentFields/incidentfield-PCAP_Number_Of_Packets.json
  Packs/PcapAnalysis/IncidentFields/incidentfield-PCAP_Number_Of_Streams.json
  Packs/PcapAnalysis/IncidentFields/incidentfield-PCAP_Start_Time.json
  Packs/PcapAnalysis/IncidentTypes/incidenttype-PCAP_Analysis.json
  Packs/PcapAnalysis/Layouts/layout-details-PCAP_Analysis.json
  Packs/PcapAnalysis/Layouts/layout-edit-PCAP_Analysis.json
  Packs/PcapAnalysis/Playbooks/playbook-PCAP_Search.yml
  Packs/PcapAnalysis/Playbooks/playbook-PCAP_Search_README.md
  Packs/PcapAnalysis/README.md
  Packs/PcapAnalysis/ReleaseNotes/2_0_0.md
  Packs/PcapAnalysis/TestPlaybooks/PCAP_Search_test.yml
  Packs/PcapAnalysis/doc_files/PCAP_Search.png
  Packs/PcapAnalysis/pack_metadata.json
  Tests/conf.json
Labels: docs-approved

#7802 Updated the pack readme
  Packs/HIPAA-BreachNotification/README.md
  Packs/HIPAA-BreachNotification/ReleaseNotes/1_0_2.md
  Packs/HIPAA-BreachNotification/pack_metadata.json
Labels: docs-approved

#7803 Default Pack Readme
  Packs/DefaultPlaybook/README.md
  Packs/DefaultPlaybook/ReleaseNotes/1_0_1.md
  Packs/DefaultPlaybook/pack_metadata.json
Labels: docs-approved

#7692 Employee Offboarding - New Pack Readme
  Packs/EmployeeOffboarding/README.md
  Packs/EmployeeOffboarding/ReleaseNotes/1_0_1.md
  Packs/EmployeeOffboarding/pack_metadata.json
Labels: docs-approved

#7807 Adding Lastline v2 and McAfee DXL to parallel_integrations in conf.json
  Tests/conf.json
Labels: docs-approved

#7564 New playbook - PANW endpoint malware investigation v2
  Packs/CommonTypes/IncidentFields/incidentfield-Detected_External_Hosts.json
  Packs/CommonTypes/IncidentFields/incidentfield-Detected_External_IPs.json
  Packs/CommonTypes/IncidentFields/incidentfield-Detected_Internal_Hosts.json
  Packs/CommonTypes/IncidentFields/incidentfield-Detected_Internal_IPs.json
  Packs/CommonTypes/IncidentFields/incidentfield-Detected_Users.json
  Packs/PANWComprehensiveInvestigation/Layouts/layout-details-PANW_Endpoint_Malware-V2.json
  Packs/PANWComprehensiveInvestigation/Playbooks/Palo_Alto_Networks_-_Endpoint_Malware_Investigation_v2.yml
  Packs/PANWComprehensiveInvestigation/Playbooks/Palo_Alto_Networks_-_Endpoint_Malware_Investigation_v2_README.md
  Packs/PANWComprehensiveInvestigation/ReleaseNotes/1_2_0.md
  Packs/PANWComprehensiveInvestigation/doc_files/Palo_Alto_Networks_-_Endpoint_Malware_Investigation_v2.png
  Packs/PANWComprehensiveInvestigation/pack_metadata.json
Labels: docs-approved

#7801 Upload pack - skipped not updated hash commit
  Tests/Marketplace/upload_packs.py
Labels: docs-approved

#7799 Set grid fix
  Packs/CommonScripts/ReleaseNotes/1_2_1.md
  Packs/CommonScripts/Scripts/SetGridField/SetGridField.py
  Packs/CommonScripts/pack_metadata.json
Labels: docs-approved, release-notes-only

#7814 Nightly failures
  Tests/conf.json
Labels: docs-approved

#7736 De hashed integration
  Packs/DeHashed/.pack-ignore
  Packs/DeHashed/.secrets-ignore
  Packs/DeHashed/Integrations/DeHashed/DeHashed.py
  Packs/DeHashed/Integrations/DeHashed/DeHashed.yml
  Packs/DeHashed/Integrations/DeHashed/DeHashed_description.md
  Packs/DeHashed/Integrations/DeHashed/DeHashed_image.png
  Packs/DeHashed/Integrations/DeHashed/DeHashed_test.py
  Packs/DeHashed/Integrations/DeHashed/Pipfile
  Packs/DeHashed/Integrations/DeHashed/Pipfile.lock
  Packs/DeHashed/Integrations/DeHashed/README.md
  Packs/DeHashed/Integrations/DeHashed/command_examples
  Packs/DeHashed/Integrations/DeHashed/test_data/search.json
  Packs/DeHashed/README.md
  Packs/DeHashed/pack_metadata.json
  Tests/secrets_white_list.json
Labels: docs-approved

#7024 unit42 feed - taxii2.0
  Packs/CommonTypes/IndicatorFields/incidentfield-feedrelatedindicators.json
  Packs/CommonTypes/Layouts/layout-indicatorsDetails-domain.json
  Packs/CommonTypes/Layouts/layout-indicatorsDetails-ip.json
  Packs/CommonTypes/Layouts/layout-indicatorsDetails-unifiedFile.json
  Packs/CommonTypes/Layouts/layout-indicatorsDetails-url.json
  Packs/CommonTypes/ReleaseNotes/1_4_0.md
  Packs/CommonTypes/pack_metadata.json
  Packs/FeedMitreAttack/IndicatorFields/incidentfield-mitreexternalreferences.json
  Packs/FeedUnit42/.pack-ignore
  Packs/FeedUnit42/.secrets-ignore
  Packs/FeedUnit42/Integrations/FeedUnit42/FeedUnit42.py
  Packs/FeedUnit42/Integrations/FeedUnit42/FeedUnit42.yml
  Packs/FeedUnit42/Integrations/FeedUnit42/FeedUnit42_description.md
  Packs/FeedUnit42/Integrations/FeedUnit42/FeedUnit42_image.png
  Packs/FeedUnit42/Integrations/FeedUnit42/FeedUnit42_test.py
  Packs/FeedUnit42/Integrations/FeedUnit42/README.md
  Packs/FeedUnit42/Integrations/FeedUnit42/commands_examples.txt
  Packs/FeedUnit42/Integrations/FeedUnit42/test_data/feed_data.py
  Packs/FeedUnit42/README.md
  Packs/FeedUnit42/TestPlaybooks/Unit42_Feed_test.yml
  Packs/FeedUnit42/pack_metadata.json
  Tests/conf.json
Labels: docs-approved

#7825 alienvault reputation feed test pb update
  Packs/FeedAlienVault/TestPlaybooks/playbook-AlienVaultReputationFeed_Test.yml
  Tests/conf.json
Labels: docs-approved

#7822 Fix urllib3 helloworld
  Packs/HelloWorld/Integrations/HelloWorld/HelloWorld.py
  Packs/HelloWorld/Integrations/HelloWorld/HelloWorld.yml
  Packs/HelloWorld/ReleaseNotes/1_1_7.md
  Packs/HelloWorld/pack_metadata.json
Labels: docs-approved

#7765 Port Scan - Pack Readme
  Packs/PortScan/README.md
  Packs/PortScan/ReleaseNotes/1_0_1.md
  Packs/PortScan/pack_metadata.json
Labels: docs-approved

#7637 [New Integration] TAXII 2 Feed
  Packs/ApiModules/.secrets-ignore
  Packs/ApiModules/Scripts/TAXII2ApiModule/README.md
  Packs/ApiModules/Scripts/TAXII2ApiModule/TAXII2ApiModule.py
  Packs/ApiModules/Scripts/TAXII2ApiModule/TAXII2ApiModule.yml
  Packs/ApiModules/Scripts/TAXII2ApiModule/TAXII2ApiModule_test.py
  Packs/ApiModules/Scripts/TAXII2ApiModule/test_data/cortex_parsed_indicators_17|19.json
  Packs/ApiModules/Scripts/TAXII2ApiModule/test_data/cortex_parsed_indicators_complex_20|19.json
  Packs/ApiModules/Scripts/TAXII2ApiModule/test_data/cortex_parsed_indicators_complex_skipped_14|19.json
  Packs/ApiModules/Scripts/TAXII2ApiModule/test_data/stix_envelope_17|19.json
  Packs/ApiModules/Scripts/TAXII2ApiModule/test_data/stix_envelope_complex_20|19.json
  Packs/ApiModules/Scripts/TAXII2ApiModule/test_data/stix_envelope_no_indicators.json
  Packs/FeedTAXII/.secrets-ignore
  Packs/FeedTAXII/Integrations/FeedTAXII2/FeedTAXII2.py
  Packs/FeedTAXII/Integrations/FeedTAXII2/FeedTAXII2.yml
  Packs/FeedTAXII/Integrations/FeedTAXII2/FeedTAXII2_description.md
  Packs/FeedTAXII/Integrations/FeedTAXII2/FeedTAXII2_image.png
  Packs/FeedTAXII/Integrations/FeedTAXII2/FeedTAXII2_test.py
  Packs/FeedTAXII/Integrations/FeedTAXII2/Pipfile
  Packs/FeedTAXII/Integrations/FeedTAXII2/Pipfile.lock
  Packs/FeedTAXII/Integrations/FeedTAXII2/README.md
  Packs/FeedTAXII/Integrations/FeedTAXII2/test_data/cortex_indicators_1.json
  Packs/FeedTAXII/Integrations/FeedTAXII2/test_data/cortex_indicators_2.json
  Packs/FeedTAXII/Integrations/FeedTAXII2/test_data/results.json
  Packs/FeedTAXII/TestPlaybooks/playbook-TAXII2_Feed_Test.yml
  Tests/conf.json
Labels: docs-approved

#7829 unskip alienvault rep feed
  Tests/conf.json
Labels: docs-approved

#7632 Crowd-Strike Falcon X sandbox
  Packs/CrowdStrikeFalconX/.pack-ignore
  Packs/CrowdStrikeFalconX/.secrets-ignore
  Packs/CrowdStrikeFalconX/CHANGELOG.md
  Packs/CrowdStrikeFalconX/Integrations/CrowdStrikeFalconX/CHANGELOG.md
  Packs/CrowdStrikeFalconX/Integrations/CrowdStrikeFalconX/CrowdStrikeFalconX.py
  Packs/CrowdStrikeFalconX/Integrations/CrowdStrikeFalconX/CrowdStrikeFalconX.yml
  Packs/CrowdStrikeFalconX/Integrations/CrowdStrikeFalconX/CrowdStrikeFalconX_description.md
  Packs/CrowdStrikeFalconX/Integrations/CrowdStrikeFalconX/CrowdStrikeFalconX_image.png
  Packs/CrowdStrikeFalconX/Integrations/CrowdStrikeFalconX/CrowdStrikeFalconX_test.py
  Packs/CrowdStrikeFalconX/Integrations/CrowdStrikeFalconX/Pipfile
  Packs/CrowdStrikeFalconX/Integrations/CrowdStrikeFalconX/Pipfile.lock
  Packs/CrowdStrikeFalconX/Integrations/CrowdStrikeFalconX/README.md
  Packs/CrowdStrikeFalconX/Integrations/CrowdStrikeFalconX/TestsInput/context.py
  Packs/CrowdStrikeFalconX/Integrations/CrowdStrikeFalconX/TestsInput/http_responses.py
  Packs/CrowdStrikeFalconX/Integrations/CrowdStrikeFalconX/example.txt
  Packs/CrowdStrikeFalconX/Playbooks/Detonate_File_-_CrowdStrike_Falcon_X.yml
  Packs/CrowdStrikeFalconX/Playbooks/Detonate_URL_-_CrowdStrike_Falcon_X.yml
  Packs/CrowdStrikeFalconX/README.md
  Packs/CrowdStrikeFalconX/TestPlaybooks/CrowdStrike_Falcon_X_-Test-Detonate_File.yml
  Packs/CrowdStrikeFalconX/TestPlaybooks/CrowdStrike_Falcon_X_-Test-Detonate_URL.yml
  Packs/CrowdStrikeFalconX/pack_metadata.json
  Tests/conf.json
Labels: content, docs-approved

#7753 Documentation link fixes
  Packs/CortexXDR/Integrations/PaloAltoNetworks_XDR/README.md
  Packs/Cylance_Protect/Integrations/Cylance_Protect_v2/README.md
  Packs/EDL/Integrations/EDL/README.md
  Packs/EclecticIQ/Integrations/EclecticIQ/README.md
  Packs/Infocyte/Integrations/Infocyte/README.md
  Packs/Lokpath_Keylight/Integrations/Lockpath_KeyLight_v2/README.md
  Packs/Mimecast/Integrations/MimecastV2/README.md
  Packs/Mimecast/Integrations/MimecastV2/doc_files/mimecast-update-policy.jpg
  Packs/OpsGenie/Integrations/integration-OpsGenie_README.md
  Packs/QuestKace/Integrations/QuestKace/README.md
  Packs/ServiceNow/Integrations/ServiceNowv2/README.md
Labels: docs-approved

#7830 symantec dlp: add info about AD users
  Packs/SymantecDLP/Integrations/SymantecDLP/README.md
Labels: docs-approved

#7832 Feed Related Indicators - set to be fromversion 5.5
  Packs/CommonTypes/IndicatorFields/incidentfield-feedrelatedindicators.json
  Packs/CommonTypes/ReleaseNotes/1_4_1.md
  Packs/CommonTypes/pack_metadata.json
Labels: docs-approved

#7793 CrowdStrike Host - add support for ip indicator type and deprecate commands
  Packs/CrowdStrikeHost/.secrets-ignore
  Packs/CrowdStrikeHost/Integrations/integration-CrowdStrikeHost.yml
  Packs/CrowdStrikeHost/Integrations/integration-CrowdStrikeHost_README.md
  Packs/CrowdStrikeHost/ReleaseNotes/1_1_2.md
  Packs/CrowdStrikeHost/TestPlaybooks/playbook-CrowdStrike_FalconHost_test.yml
  Packs/CrowdStrikeHost/pack_metadata.json
  Packs/NonSupported/TestPlaybooks/playbook-Search_Endpoints_By_Hash_-_Generic_-_Test.yml
Labels: docs-approved

#7834 CS FalconX - README change
  Packs/CrowdStrikeFalconX/Integrations/CrowdStrikeFalconX/README.md
Labels: docs-approved

#7818 Add error message when passed non-iterable dictionary to JSONtoCSV script
  Packs/CommonScripts/ReleaseNotes/1_2_2.md
  Packs/CommonScripts/Scripts/JSONtoCSV/JSONtoCSV.py
  Packs/CommonScripts/Scripts/JSONtoCSV/JSONtoCSV.yml
  Packs/CommonScripts/Scripts/JSONtoCSV/JSONtoCSV_test.py
  Packs/CommonScripts/Scripts/JSONtoCSV/README.md
  Packs/CommonScripts/Scripts/script-JSONtoCSV.yml
  Packs/CommonScripts/Scripts/script-JSONtoCSV_CHANGELOG.md
  Packs/CommonScripts/pack_metadata.json
Labels: bug, docs-approved

#7537 [trustar-150]: TruSTAR v2
  Packs/TruSTAR/.secrets-ignore
  Packs/TruSTAR/Integrations/TruSTAR/TruSTAR.yml
  Packs/TruSTAR/Integrations/TruSTAR_V2/Pipfile
  Packs/TruSTAR/Integrations/TruSTAR_V2/Pipfile.lock
  Packs/TruSTAR/Integrations/TruSTAR_V2/README.md
  Packs/TruSTAR/Integrations/TruSTAR_V2/TruSTAR_V2.py
  Packs/TruSTAR/Integrations/TruSTAR_V2/TruSTAR_V2.yml
  Packs/TruSTAR/Integrations/TruSTAR_V2/TruSTAR_V2_description.md
  Packs/TruSTAR/Integrations/TruSTAR_V2/TruSTAR_V2_image.png
  Packs/TruSTAR/Integrations/TruSTAR_V2/TruSTAR_V2_test.py
  Packs/TruSTAR/Integrations/TruSTAR_V2/command_examples.txt
  Packs/TruSTAR/ReleaseNotes/2_0_0.md
  Packs/TruSTAR/TestPlaybooks/playbook-TruSTAR_V2_Test.yml
  Pipfile
  Tests/conf.json
Labels: Contribution, docs-approved

#7774 Block IP Generic v2 - FortiGate Ban IP Enhancement
  Packs/CommonPlaybooks/Playbooks/playbook-Block_IP_-_Generic_v2.yml
  Packs/CommonPlaybooks/Playbooks/playbook-Block_IP_-_Generic_v2_README.md
  Packs/CommonPlaybooks/ReleaseNotes/1_5_1.md
  Packs/CommonPlaybooks/pack_metadata.json
Labels: docs-approved

#7841 Carbon black Protection Rapid IOC Hunting - use Carbon Black Protection v2 integration
  Packs/CarbonBlackProtect/Playbooks/playbook-Carbon_black_Protection_Rapid_IOC_Hunting.yml
  Packs/CarbonBlackProtect/ReleaseNotes/1_0_2.md
  Packs/CarbonBlackProtect/pack_metadata.json
Labels: docs-approved, release-notes-only

#7836 Cortex Data Lake - escape backticks in query logs example in README
  Packs/CortexDataLake/Integrations/CortexDataLake/README.md
Labels: docs-approved

#7811 mimecast v2 - Fixed an issue where added users by domains showed an er…
  Packs/Mimecast/Integrations/MimecastV2/MimecastV2.py
  Packs/Mimecast/Integrations/MimecastV2/mimecast_test.py
  Packs/Mimecast/ReleaseNotes/1_1_0.md
  Packs/Mimecast/pack_metadata.json
Labels: bug, docs-approved

#7831 fix table class
  Packs/FeedZoom/.secrets-ignore
  Packs/FeedZoom/Integrations/FeedZoom/FeedZoom.py
  Packs/FeedZoom/Integrations/FeedZoom/test_data/zoom_endpoint_mock.html
  Packs/FeedZoom/ReleaseNotes/1_1_0.md
  Packs/FeedZoom/pack_metadata.json
Labels: Contribution, docs-approved, release-notes-only

#7764 Lost/Stolen device pack description
  Packs/Lost_Stolen_Device/README.md
  Packs/Lost_Stolen_Device/ReleaseNotes/1_0_3.md
  Packs/Lost_Stolen_Device/pack_metadata.json
Labels: docs-approved

#7817 Feed office365: added the tags parameter
  Packs/FeedOffice365/Integrations/FeedOffice365/FeedOffice365.py
  Packs/FeedOffice365/Integrations/FeedOffice365/FeedOffice365.yml
  Packs/FeedOffice365/Integrations/FeedOffice365/FeedOffice365_test.py
  Packs/FeedOffice365/ReleaseNotes/1_1_2.md
  Packs/FeedOffice365/pack_metadata.json
Labels: docs-approved

#7816 Feed ProofPoint: added the tags parameter
  Packs/FeedProofpoint/Integrations/FeedProofpoint/FeedProofpoint.py
  Packs/FeedProofpoint/Integrations/FeedProofpoint/FeedProofpoint.yml
  Packs/FeedProofpoint/Integrations/FeedProofpoint/FeedProofpoint_test.py
  Packs/FeedProofpoint/ReleaseNotes/1_0_1.md
  Packs/FeedProofpoint/pack_metadata.json
Labels: docs-approved

#7847 Replaced files containing "|" character with "-"
  Packs/ApiModules/Scripts/TAXII2ApiModule/TAXII2ApiModule_test.py
  Packs/ApiModules/Scripts/TAXII2ApiModule/test_data/cortex_parsed_indicators_17-19.json
  Packs/ApiModules/Scripts/TAXII2ApiModule/test_data/cortex_parsed_indicators_complex_20-19.json
  Packs/ApiModules/Scripts/TAXII2ApiModule/test_data/cortex_parsed_indicators_complex_skipped_14-19.json
  Packs/ApiModules/Scripts/TAXII2ApiModule/test_data/stix_envelope_17-19.json
  Packs/ApiModules/Scripts/TAXII2ApiModule/test_data/stix_envelope_complex_20-19.json
Labels: docs-approved

#7844 Lastline v2 - Fixed the detailed description
  Packs/Lastline/Integrations/Lastline_v2/Lastline_v2_description.md
  Packs/Lastline/ReleaseNotes/1_0_2.md
  Packs/Lastline/pack_metadata.json
Labels: docs-approved

#7828 Add tags feed taxii
  Packs/FeedTAXII/Integrations/FeedTAXII/FeedTAXII.py
  Packs/FeedTAXII/Integrations/FeedTAXII/FeedTAXII.yml
  Packs/FeedTAXII/Integrations/FeedTAXII/FeedTAXII_test.py
  Packs/FeedTAXII/Integrations/FeedTAXII/FeedTAXII_test/TestCommands/indicators_results.json
  Packs/FeedTAXII/ReleaseNotes/1_0_1.md
  Packs/FeedTAXII/pack_metadata.json
Labels: docs-approved

#7821 Feed Recorded Future: added the tags parameter
  Packs/FeedRecordedFuture/Integrations/FeedRecordedFuture/FeedRecordedFuture.py
  Packs/FeedRecordedFuture/Integrations/FeedRecordedFuture/FeedRecordedFuture.yml
  Packs/FeedRecordedFuture/Integrations/FeedRecordedFuture/FeedRecordedFuture_test.py
  Packs/FeedRecordedFuture/ReleaseNotes/1_0_2.md
  Packs/FeedRecordedFuture/pack_metadata.json
Labels: docs-approved

#7810 APIModules: added the tags parameter
  Packs/ApiModules/ReleaseNotes/1_0_3.md
  Packs/ApiModules/Scripts/CSVFeedApiModule/CSVFeedApiModule.py
  Packs/ApiModules/Scripts/CSVFeedApiModule/CSVFeedApiModule.yml
  Packs/ApiModules/Scripts/CSVFeedApiModule/CSVFeedApiModule_test.py
  Packs/ApiModules/pack_metadata.json
Labels: docs-approved

#7808 FeedCSV: added the tags parameter
  Packs/FeedCSV/Integrations/FeedCSV/FeedCSV.yml
  Packs/FeedCSV/ReleaseNotes/1_0_2.md
  Packs/FeedCSV/pack_metadata.json
Labels: docs-approved

#7813 Bambenek Consulting Feed: added the tags parameter
  Packs/FeedBambenekConsulting/Integrations/FeedBambenekConsulting/FeedBambenekConsulting.yml
  Packs/FeedBambenekConsulting/ReleaseNotes/1_0_1.md
  Packs/FeedBambenekConsulting/pack_metadata.json
  Tests/conf.json
Labels: docs-approved

#7788 Update metadata dependencies
  Tests/Marketplace/Tests/marketplace_services_test.py
  Tests/Marketplace/marketplace_services.py
Labels: docs-approved

#7845 OTRS - added prerequisite to README
  Packs/OTRS/Integrations/OTRS/README.md
Labels: docs-approved

#7848 CrowdStrike FalconX - added an issue number to conf.json
  Tests/conf.json
Labels: docs-approved

#7809 Deprecate old Okta integration
  Packs/Okta/Integrations/integration-Okta.yml
  Packs/Okta/Integrations/integration-Okta_CHANGELOG.md
  Packs/Okta/ReleaseNotes/1_0_3.md
  Packs/Okta/pack_metadata.json
Labels: docs-approved, release-notes-only

#7838 PCAP Update README.md
  Packs/PcapAnalysis/Playbooks/playbook-PCAP_Search_README.md
  Packs/PcapAnalysis/README.md
Labels: docs-approved

#7310 ME_Service_Desk_Plus_integration
  Packs/ServiceDeskPlus/.pack-ignore
  Packs/ServiceDeskPlus/.secrets-ignore
  Packs/ServiceDeskPlus/Integrations/ServiceDeskPlus/README.md
  Packs/ServiceDeskPlus/Integrations/ServiceDeskPlus/ServiceDeskPlus.py
  Packs/ServiceDeskPlus/Integrations/ServiceDeskPlus/ServiceDeskPlus.yml
  Packs/ServiceDeskPlus/Integrations/ServiceDeskPlus/ServiceDeskPlus_description.md
  Packs/ServiceDeskPlus/Integrations/ServiceDeskPlus/ServiceDeskPlus_image.png
  Packs/ServiceDeskPlus/Integrations/ServiceDeskPlus/ServiceDeskPlus_test.py
  Packs/ServiceDeskPlus/Integrations/ServiceDeskPlus/command_examples.txt
  Packs/ServiceDeskPlus/Integrations/ServiceDeskPlus/test_data/response_constants.py
  Packs/ServiceDeskPlus/Integrations/ServiceDeskPlus/test_data/result_constants.py
  Packs/ServiceDeskPlus/README.md
  Packs/ServiceDeskPlus/TestPlaybooks/playbook-Service_Desk_Plus.yml
  Packs/ServiceDeskPlus/pack_metadata.json
  Tests/conf.json
Labels: docs-approved

#7839 Updated Compliance pack readme
  Packs/BreachNotification-US/README.md
  Packs/BreachNotification-US/ReleaseNotes/1_0_4.md
  Packs/BreachNotification-US/pack_metadata.json
  Packs/Compliance/README.md
  Packs/Compliance/ReleaseNotes/1_0_3.md
  Packs/Compliance/pack_metadata.json
  Packs/HIPAA-BreachNotification/README.md
  Packs/HIPAA-BreachNotification/ReleaseNotes/1_0_3.md
  Packs/HIPAA-BreachNotification/pack_metadata.json
Labels: docs-approved

#7835 [Documentation] EWS O365 new integration description
  Packs/EWS/Integrations/EWSO365/EWSO365.yml
  Packs/EWS/Integrations/EWSO365/README.md
  Packs/EWS/ReleaseNotes/1_1_3.md
  Packs/EWS/pack_metadata.json
Labels: docs-approved

#7856 Nightly failures
  Tests/conf.json
Labels: docs-approved

#7849 Genericsql pooling support
  Packs/GenericSQL/Integrations/GenericSQL/GenericSQL.py
  Packs/GenericSQL/Integrations/GenericSQL/GenericSQL.yml
  Packs/GenericSQL/Integrations/GenericSQL/GenericSQL_description.md
  Packs/GenericSQL/Integrations/GenericSQL/GenericSQL_test.py
  Packs/GenericSQL/Integrations/GenericSQL/Pipfile
  Packs/GenericSQL/Integrations/GenericSQL/Pipfile.lock
  Packs/GenericSQL/Integrations/GenericSQL/README.md
  Packs/GenericSQL/ReleaseNotes/1_0_3.md
  Packs/GenericSQL/TestPlaybooks/generic-sql-mssql-encrypted-connection.yml
  Packs/GenericSQL/TestPlaybooks/generic-sql.yml
  Packs/GenericSQL/pack_metadata.json
Labels: docs-approved

#7827 MicrosoftManagementActivity: update readme
  Packs/MicrosoftManagementActivity/Integrations/MicrosoftManagementActivity/README.md
Labels: docs-approved

#7860 remove Duo Admin test from skipped tests
  Tests/conf.json
Labels: docs-approved

#7859 Fix rn
  Packs/CommonScripts/ReleaseNotes/1_1_13.md
Labels: docs-approved

#7862 enable hardening test for versions 5.5+
  Tests/conf.json
Labels: docs-approved

#7857 demisto -> xsoar packmetadata PCAP analysis
  Packs/PcapAnalysis/ReleaseNotes/2_1_1.md
  Packs/PcapAnalysis/pack_metadata.json
Labels: docs-approved

#7846 Adding tags to AlienVault otx, Elasticsearch, cofense & AWS feeds
  Packs/FeedAWS/Integrations/FeedAWS/FeedAWS.yml
  Packs/FeedAWS/ReleaseNotes/1_0_2.md
  Packs/FeedAWS/pack_metadata.json
  Packs/FeedAlienVault/Integrations/FeedAlienVaultOTXTaxii/FeedAlienVaultOTXTaxii.py
  Packs/FeedAlienVault/Integrations/FeedAlienVaultOTXTaxii/FeedAlienVaultOTXTaxii.yml
  Packs/FeedAlienVault/Integrations/FeedAlienVaultOTXTaxii/FeedAlienVaultOTXTaxii_test.py
  Packs/FeedAlienVault/ReleaseNotes/1_0_1.md
  Packs/FeedAlienVault/pack_metadata.json
  Packs/FeedCofense/Integrations/FeedCofense/FeedCofense.py
  Packs/FeedCofense/Integrations/FeedCofense/FeedCofense.yml
  Packs/FeedCofense/Integrations/FeedCofense/FeedCofense_test.py
  Packs/FeedCofense/ReleaseNotes/1_0_4.md
  Packs/FeedCofense/pack_metadata.json
  Packs/FeedElasticsearch/Integrations/FeedElasticsearch/FeedElasticsearch.py
  Packs/FeedElasticsearch/Integrations/FeedElasticsearch/FeedElasticsearch.yml
  Packs/FeedElasticsearch/Integrations/FeedElasticsearch/FeedElasticsearch_test.py
  Packs/FeedElasticsearch/ReleaseNotes/1_0_3.md
  Packs/FeedElasticsearch/pack_metadata.json
Labels: docs-approved, release-notes-only

#7043 Microsoft Management Activity API - Fixed authentication logic
  Packs/MicrosoftManagementActivity/Integrations/MicrosoftManagementActivity/CHANGELOG.md
  Packs/MicrosoftManagementActivity/Integrations/MicrosoftManagementActivity/MicrosoftManagementActivity.py
  Packs/MicrosoftManagementActivity/Integrations/MicrosoftManagementActivity/MicrosoftManagementActivity.yml
  Packs/MicrosoftManagementActivity/ReleaseNotes/1_0_1.md
  Packs/MicrosoftManagementActivity/pack_metadata.json
Labels: docs-approved

#7746 Panos threat
  Packs/PAN-OS/Integrations/Panorama/Panorama.py
  Packs/PAN-OS/Integrations/Panorama/Panorama.yml
  Packs/PAN-OS/Integrations/Panorama/Panorama_test.py
  Packs/PAN-OS/ReleaseNotes/1_1_1.md
  Packs/PAN-OS/pack_metadata.json
Labels: Contribution, docs-approved

#7797 New script - PcapFileExtractor
  Packs/PcapAnalysis/Scripts/PcapFileExtractor/PcapFileExtractor.py
  Packs/PcapAnalysis/Scripts/PcapFileExtractor/PcapFileExtractor.yml
  Packs/PcapAnalysis/Scripts/PcapFileExtractor/PcapFileExtractor_test.py
  Packs/PcapAnalysis/Scripts/PcapFileExtractor/README.md
  Packs/PcapAnalysis/Scripts/PcapFileExtractor/TestData/tftp_rrq.pcap
Labels: docs-approved

#7638 [blueliv-177] [717938] New Blueliv ThreatContext integration
  Packs/BluelivThreatContext/.pack-ignore
  Packs/BluelivThreatContext/.secrets-ignore
  Packs/BluelivThreatContext/CHANGELOG.md
  Packs/BluelivThreatContext/Integrations/BluelivThreatContext/BluelivThreatContext.py
  Packs/BluelivThreatContext/Integrations/BluelivThreatContext/BluelivThreatContext.yml
  Packs/BluelivThreatContext/Integrations/BluelivThreatContext/BluelivThreatContext_description.md
  Packs/BluelivThreatContext/Integrations/BluelivThreatContext/BluelivThreatContext_image.png
  Packs/BluelivThreatContext/Integrations/BluelivThreatContext/BluelivThreatContext_test.py
  Packs/BluelivThreatContext/Integrations/BluelivThreatContext/CHANGELOG.md
  Packs/BluelivThreatContext/Integrations/BluelivThreatContext/Pipfile
  Packs/BluelivThreatContext/Integrations/BluelivThreatContext/Pipfile.lock
  Packs/BluelivThreatContext/Integrations/BluelivThreatContext/README.md
  Packs/BluelivThreatContext/README.md
  Packs/BluelivThreatContext/TestPlaybooks/Blueliv_ThreatContext_test.yml
  Packs/BluelivThreatContext/pack_metadata.json
  Tests/conf.json
  Tests/secrets_white_list.json
Labels: Contribution, docs-approved

#7872 Add description to ServiceDeskPlus.yml
  Packs/ServiceDeskPlus/Integrations/ServiceDeskPlus/ServiceDeskPlus.yml
  Packs/ServiceDeskPlus/ReleaseNotes/1_1_0.md
  Packs/ServiceDeskPlus/pack_metadata.json
Labels: docs-approved

#7870 Fix mandatory dependencies
  Packs/CommonTypes/pack_metadata.json
  Packs/Malware/pack_metadata.json
  Tests/Marketplace/Tests/marketplace_services_test.py
  Tests/Marketplace/marketplace_services.py
Labels: docs-approved

#7877 Microsoft Teams - add instance execute external to rerouting setup example
  Packs/MicrosoftTeams/Integrations/MicrosoftTeams/README.md
Labels: docs-approved

#7880 Nightly failures
  Packs/ThreatConnect/Integrations/ThreatConnect/ThreatConnect.yml
  TestPlaybooks/NonCircleTests/playbook-ThreatConnect_Test.yml
  Tests/conf.json
Labels: docs-approved

#7884 Generic-SQL adding Oracle sql db to test playbook
  Packs/GenericSQL/TestPlaybooks/generic-sql.yml
  Tests/conf.json
Labels: content, docs-approved

#7871 pwned v2 - Fixed an issue where the *test* button was not validating …
  Packs/Pwned/Integrations/PwnedV2/PwnedV2.py
  Packs/Pwned/Integrations/PwnedV2/PwnedV2_test.py
  Packs/Pwned/Integrations/PwnedV2/README.md
  Packs/Pwned/ReleaseNotes/1_0_1.md
  Packs/Pwned/pack_metadata.json
Labels: bug, docs-approved, release-notes-only

#7891 Improve tim siem query
  Packs/TIM_SIEM/Playbooks/playbook-TIM_-_Add_All_Indicator_Types_To_SIEM.yml
  Packs/TIM_SIEM/ReleaseNotes/1_0_2.md
  Packs/TIM_SIEM/pack_metadata.json
Labels: docs-approved

#7881 unskip jsonwhois
  Packs/JsonWhoIs/Integrations/JsonWhoIs/JsonWhoIs.py
  Packs/JsonWhoIs/Integrations/JsonWhoIs/JsonWhoIs.yml
  Packs/JsonWhoIs/ReleaseNotes/1_0_3.md
  Packs/JsonWhoIs/pack_metadata.json
  Tests/conf.json
Labels: docs-approved

#7806 Improving log prints
  Tests/test_content.py
Labels: docs-approved

#7702 updating images
  Packs/FeedFeodoTracker/Integrations/FeedFeodoTrackerHashes/FeedFeodoTrackerHashes_image.png
  Packs/FeedFeodoTracker/Integrations/FeedFeodoTrackerIPBlocklist/FeedFeodoTrackerIPBlocklist_image.png
  Packs/Feedsslabusech/Integrations/Feedsslabusech/Feedsslabusech_image.png
  Packs/Gmail/Integrations/Gmail/Gmail_image.png
  Packs/GmailSingleUser/Integrations/GmailSingleUser/GmailSingleUser_image.png
  Packs/MicrosoftGraphListener/Integrations/MicrosoftGraphListener/MicrosoftGraphListener_image.png
  Packs/MicrosoftGraphMail/Integrations/MicrosoftGraphMail/MicrosoftGraphMail_image.png
  Packs/MongoDB/Integrations/MongoDB/MongoDB_image.png
  Packs/MongoDB/Integrations/MongoDBKeyValueStore/MongoDBKeyValueStore.png
  Packs/MongoDB/Integrations/MongoDBKeyValueStore/MongoDBKeyValueStore_image.png
  Packs/MongoDB/Integrations/MongoDBLog/MongoDBLog.png
  Packs/MongoDB/Integrations/MongoDBLog/MongoDBLog_image.png
  Packs/NonSupported/Integrations/integration-SandBlastAppliance_3_1_0.yml
  Packs/PhishLabs/Integrations/PhishLabsIOC/PhishLabsIOC_image.png
  Packs/PhishLabs/Integrations/PhishLabsIOC_DRP/PhishLabsIOC_DRP_image.png
  Packs/PhishLabs/Integrations/PhishLabsIOC_EIR/PhishLabsIOC_EIR_image.png
  Packs/PrismaAccess/Integrations/PrismaAccess/PrismaAccess_image.png
  Packs/PrismaAccess/Integrations/PrismaAccessEgressIPFeed/PrismaAccessEgressIPFeed_image.png
  Packs/Sandblast/Integrations/integration-Sandblast.yml
  Packs/Sandblast/ReleaseNotes/1_0_1.md
  Packs/Sandblast/pack_metadata.json
  Packs/ThreatQ/Integrations/ThreatQ_v2/ThreatQ_v2_image.png
  Packs/ThreatQ/Integrations/integration-ThreatQ.yml
Labels: docs-approved

#7876 Panos threat (#7746)
  Packs/PAN-OS/Integrations/Panorama/Panorama.py
  Packs/PAN-OS/Integrations/Panorama/Panorama.yml
  Packs/PAN-OS/Integrations/Panorama/Panorama_test.py
  Packs/PAN-OS/ReleaseNotes/1_3_0.md
  Packs/PAN-OS/pack_metadata.json
Labels: Contribution, docs-approved

#7896 quest kace, snow v2 - added descs
  Packs/QuestKace/Integrations/QuestKace/QuestKace.yml
  Packs/QuestKace/ReleaseNotes/1_0_2.md
  Packs/QuestKace/pack_metadata.json
  Packs/ServiceNow/Integrations/ServiceNowv2/ServiceNowv2.yml
  Packs/ServiceNow/ReleaseNotes/1_1_6.md
  Packs/ServiceNow/pack_metadata.json
Labels: docs-approved

#7893 Adding LogRhythm REST doc from zendesk
  Packs/LogRhythmRest/Integrations/LogRhythmRest/README.md
Labels: docs-approved

#6983 Azure Security With Common API
  Packs/AzureSecurityCenter/Integrations/AzureSecurityCenter_v2/AzureSecurityCenter_v2.py
  Packs/AzureSecurityCenter/Integrations/AzureSecurityCenter_v2/AzureSecurityCenter_v2.yml
  Packs/AzureSecurityCenter/Integrations/AzureSecurityCenter_v2/AzureSecurityCenter_v2_test.py
  Packs/AzureSecurityCenter/Integrations/AzureSecurityCenter_v2/CHANGELOG.md
  Packs/AzureSecurityCenter/Integrations/AzureSecurityCenter_v2/README.md
  Packs/AzureSecurityCenter/ReleaseNotes/1_0_1.md
  Packs/AzureSecurityCenter/TestPlaybooks/playbook-AzureSCTestPlaybook.yml
  Packs/AzureSecurityCenter/pack_metadata.json
  Tests/conf.json
Labels: docs-approved

#7905 Unskip rf
  Tests/conf.json
Labels: docs-approved

#7907 bump content version
  .circleci/config.yml
Labels: docs-approved

#7887 Microsoft Teams - refer to integration doc troubleshooting
  Packs/MicrosoftTeams/Integrations/MicrosoftTeams/MicrosoftTeams.py
  Packs/MicrosoftTeams/Integrations/MicrosoftTeams/MicrosoftTeams.yml
  Packs/MicrosoftTeams/ReleaseNotes/1_0_3.md
  Packs/MicrosoftTeams/pack_metadata.json
Labels: docs-approved

#7901 MITRE Feed - Fixed an issue where a non existing indicator query usin…
  Packs/FeedMitreAttack/Integrations/FeedMitreAttack/FeedMitreAttack.py
  Packs/FeedMitreAttack/ReleaseNotes/1_0_5.md
  Packs/FeedMitreAttack/TestPlaybooks/playbook-Mitre_Attack_List_2_Indicators_Feed_Test.yml
  Packs/FeedMitreAttack/pack_metadata.json
Labels: bug, docs-approved, release-notes-only

#7897 Small Tweaks to Mocking Process
  Tests/mock_server.py
  Tests/test_content.py
Labels: docs-approved

#7890 vt private api - fix TPB, add missing path in context
  Packs/VirusTotal-Private_API/Integrations/VirusTotal-Private_API/README.md
  Packs/VirusTotal-Private_API/Integrations/VirusTotal-Private_API/VirusTotal-Private_API.yml
  Packs/VirusTotal-Private_API/ReleaseNotes/1_0_1.md
  Packs/VirusTotal-Private_API/TestPlaybooks/playbook-virusTotalPrivateAPI-test.yml
  Packs/VirusTotal-Private_API/pack_metadata.json
  Packs/VirusTotal/TestPlaybooks/playbook-VirusTotal_detonate_file-test.yml
  Tests/conf.json
Labels: bug, docs-approved

#7352 Fix VMWare TLS bug
  Packs/VMware/Integrations/integration-VMware.yml
Labels: Contribution

#7895 Lockpath Keylight - add version to README
  Packs/Lokpath_Keylight/.secrets-ignore
  Packs/Lokpath_Keylight/Integrations/Lockpath_KeyLight_v2/README.md
Labels: docs-approved

#7916 Add server url to nightly
  Tests/scripts/slack_notifier.py
  Tests/test_integration.py
Labels: docs-approved

#7892 Phishing v2 - Test - Incident Starter - race condition fix
  Packs/Phishing/TestPlaybooks/Phishing_v2_-_Test_-_Incident_Starter.yml
Labels: docs-approved

#7913 docker hardening fix
  Tests/configure_and_test_integration_instances.py
Labels: docs-approved

#7929 Fix Non-Existent Method Invocation
  Tests/mock_server.py
Labels: docs-approved

#7850 Pack descriptions for README
  Packs/AccessInvestigation/README.md
  Packs/AccessInvestigation/ReleaseNotes/1_1_3.md
  Packs/AccessInvestigation/pack_metadata.json
  Packs/BruteForce/README.md
  Packs/BruteForce/ReleaseNotes/1_1_1.md
  Packs/BruteForce/pack_metadata.json
  Packs/GDPR/README.md
  Packs/GDPR/ReleaseNotes/1_0_2.md
  Packs/GDPR/doc_files/GDPR_Breach_Notification.png
  Packs/GDPR/pack_metadata.json
  Packs/NIST/README.md
  Packs/NIST/ReleaseNotes/1_0_1.md
  Packs/NIST/doc_files/NIST_-_Handling_an_Incident_Template.png
  Packs/NIST/pack_metadata.json
  Packs/SANS/README.md
  Packs/SANS/ReleaseNotes/1_0_1.md
  Packs/SANS/doc_files/SANS_-_Incident_Handler's_Handbook_Template.png
  Packs/SANS/pack_metadata.json
Labels: docs-approved

#7855 test duoAdmin
  Packs/DuoAdminApi/Integrations/DuoAdminApi/DuoAdminApi.py
  Packs/DuoAdminApi/Integrations/DuoAdminApi/DuoAdminApi.yml
  Packs/DuoAdminApi/ReleaseNotes/2_0_0.md
  Packs/DuoAdminApi/pack_metadata.json
Labels: docs-approved

#7917 PAN-OS - panorama-show-location-ip - Get the location of an IP address.
  Packs/PAN-OS/Integrations/Panorama/Panorama.py
  Packs/PAN-OS/Integrations/Panorama/Panorama.yml
  Packs/PAN-OS/ReleaseNotes/1_4_0.md
  Packs/PAN-OS/TestPlaybooks/playbook-palo_alto_firewall_test_pb.yml
  Packs/PAN-OS/pack_metadata.json
Labels: docs-approved

#7909 Fixed DT syntax error
  Packs/PAN-OS/Playbooks/playbook-NetOps_-_Firewall_Upgrade_CHANGELOG.md
  Packs/PAN-OS/Playbooks/playbook-NetOps_-_Firewall_Version_Content_Upgrade.yml
Labels: Contribution

#7293 Migrating circleci build to using workflow
  .circleci/config.yml
  Documentation/docs_site_update.sh
  Tests/configure_and_test_integration_instances.py
  Tests/scripts/destroy_instances.py
  Tests/scripts/run_tests.sh
  Tests/scripts/server_get_artifact.sh
  Tests/scripts/slack_notifier.py
  Tests/scripts/slack_notifier.sh
  Tests/scripts/wait_until_server_ready.py
  Utils/trigger_content_build_with_no_backward_check.sh
  Utils/trigger_content_build_with_time_to_live.sh
  Utils/trigger_content_nightly_build.sh
  Utils/trigger_content_nightly_build_with_memory.sh
  Utils/trigger_content_nightly_instance_tests.sh
  Utils/trigger_content_non_ami_build.sh
  Utils/trigger_content_non_ami_build_by_number.sh
  Utils/trigger_nightly_sdk_build.sh
Labels: docs-approved

#7837 Update sane doc
  Packs/Base/ReleaseNotes/1_1_4.md
  Packs/Base/Scripts/SaneDocReportV2/SaneDocReportV2.py
  Packs/Base/Scripts/SaneDocReportV2/SaneDocReportV2.yml
  Packs/Base/Scripts/SanePdfReport/SanePdfReport.yml
  Packs/Base/pack_metadata.json
Labels: bug, content, docs-approved, enhancement

#7934 Enable MS Graph Listener/Mail to use htmlBody arg
  Packs/MicrosoftGraphListener/Integrations/MicrosoftGraphListener/MicrosoftGraphListener.py
  Packs/MicrosoftGraphListener/ReleaseNotes/1_0_4.md
  Packs/MicrosoftGraphListener/pack_metadata.json
  Packs/MicrosoftGraphMail/Integrations/MicrosoftGraphMail/MicrosoftGraphMail.py
  Packs/MicrosoftGraphMail/ReleaseNotes/1_0_2.md
  Packs/MicrosoftGraphMail/pack_metadata.json
Labels: docs-approved

#7938 Fixed DT syntax error
  Packs/PAN-OS/Playbooks/playbook-NetOps_-_Firewall_Upgrade.yml
  Packs/PAN-OS/Playbooks/playbook-NetOps_-_Firewall_Upgrade_CHANGELOG.md
  Packs/PAN-OS/Playbooks/playbook-NetOps_-_Firewall_Version_Content_Upgrade.yml
  Packs/PAN-OS/ReleaseNotes/1_4_1.md
  Packs/PAN-OS/pack_metadata.json
Labels: docs-approved, release-notes-only

#7945 fix slack notifications for nightly
  .circleci/config.yml
Labels: docs-approved

#7061 SplunkPy - correct the usage of fields for hec submit event command
  Packs/SplunkPy/Integrations/SplunkPy/SplunkPy.py
  Packs/SplunkPy/Integrations/SplunkPy/SplunkPy.yml
  Packs/SplunkPy/ReleaseNotes/1_0_1.md
  Packs/SplunkPy/pack_metadata.json
Labels: Contribution

#7052 Use handle_proxy() in all requests in SplunkPy integration.
  Packs/SplunkPy/Integrations/SplunkPy/SplunkPy.py
  Packs/SplunkPy/ReleaseNotes/1_0_1.md
  Packs/SplunkPy/pack_metadata.json
Labels: Contribution

#7947 CDL is a read only integration, adding it to parallel integrations
  Tests/conf.json
Labels: docs-approved

#7948 Not failing instance creation when a test-conf branch exists
  .circleci/config.yml
  Tests/scripts/download_demisto_conf.sh
Labels: docs-approved

#7954 don't overwrite time_to_live env variable from context
  .circleci/config.yml
Labels: docs-approved

#7955 Update contrib base branch
  .circleci/config.yml
  Tests/scripts/download_demisto_conf.sh
Labels: docs-approved

#7943 Adding CrowdStrike FalconX to generic detonate test playbooks
  Packs/CommonPlaybooks/Playbooks/playbook-Detonate_File_-_Generic.yml
  Packs/CommonPlaybooks/Playbooks/playbook-Detonate_File_-_Generic_CHANGELOG.md
  Packs/CommonPlaybooks/Playbooks/playbook-Detonate_URL_-_Generic.yml
  Packs/CommonPlaybooks/Playbooks/playbook-Detonate_URL_-_Generic_CHANGELOG.md
  Packs/CommonPlaybooks/ReleaseNotes/1_6_0.md
  Packs/CommonPlaybooks/pack_metadata.json
Labels: content, docs-approved

#7957 emailreputation refactor tpb
  Packs/Pwned/TestPlaybooks/playbook-EmailReputationTest.yml
Labels: docs-approved

#7958 increase SNDBOX test playbook timeout
  Tests/conf.json
Labels: docs-approved

#7965 No need to test integrations for the third time before running test p…
  Tests/test_integration.py
Labels: docs-approved

#7961 af feed - daily deprecated update
  Packs/FeedAutofocus/Integrations/FeedAutofocus/README.md
Labels: docs-approved

#7984 Unskip Trend Micro Apex test
  Tests/conf.json
Labels: docs-approved

#7979 Jirav2 - Fixed an issue where an error was raised when no issues mat…
  Packs/Jira/Integrations/JiraV2/JiraV2.py
  Packs/Jira/Integrations/JiraV2/JiraV2.yml
  Packs/Jira/Integrations/JiraV2/JiraV2_test.py
  Packs/Jira/Integrations/JiraV2/test_data/expected_results.py
  Packs/Jira/Integrations/JiraV2/test_data/raw_response.py
  Packs/Jira/ReleaseNotes/1_0_2.md
  Packs/Jira/pack_metadata.json
  TestPlaybooks/NonCircleTests/Deprecated/playbook-Jira-Test.yml
  Tests/conf.json
Labels: bug, docs-approved, release-notes-only

#7932 Workday New Instance
  Packs/Workday/Integrations/Workday/Workday.py
  Packs/Workday/ReleaseNotes/1_0_2.md
  Packs/Workday/TestPlaybooks/Workday_-_Test.yml
  Packs/Workday/pack_metadata.json
  Tests/conf.json
Labels: docs-approved, release-notes-only

#7883 Old branch script reputations add on
  Utils/old_content_branch.py
Labels: docs-approved

#7442 Zimperium mobile
  Packs/CommonPlaybooks/TestPlaybooks/playbook-ConvertFileHashToCorrespondingHashes-Test.yml
  Packs/CommonPlaybooks/pack_metadata.json
  Packs/CommonTypes/IncidentFields/incidentfield-App.json
  Packs/CommonTypes/IncidentFields/incidentfield-Device_Hash.json
  Packs/CommonTypes/IncidentFields/incidentfield-First_Name.json
  Packs/CommonTypes/IncidentFields/incidentfield-Last_Name.json
  Packs/CommonTypes/IncidentFields/incidentfield-Mobile_Device_Model.json
  Packs/CommonTypes/IncidentFields/incidentfield-OS_Version.json
  Packs/CommonTypes/IncidentFields/incidentfield-PhoneNumber.json
  Packs/CommonTypes/ReleaseNotes/1_3_0.md
  Packs/CommonTypes/ReleaseNotes/1_4_0.md
  Packs/CommonTypes/ReleaseNotes/1_5_0.md
  Packs/CommonTypes/pack_metadata.json
  Packs/Zimperium/.pack-ignore
  Packs/Zimperium/.secrets-ignore
  Packs/Zimperium/Classifiers/classifier-Zimperium.json
  Packs/Zimperium/Classifiers/classifier-Zimperium_5_9_9.json
  Packs/Zimperium/Classifiers/classifier-mapper-incoming-Zimperium.json
  Packs/Zimperium/IncidentTypes/incidenttype-Zimperium_event.json
  Packs/Zimperium/Integrations/Zimperium/Pipfile
  Packs/Zimperium/Integrations/Zimperium/Pipfile.lock
  Packs/Zimperium/Integrations/Zimperium/README.md
  Packs/Zimperium/Integrations/Zimperium/Zimperium.py
  Packs/Zimperium/Integrations/Zimperium/Zimperium.yml
  Packs/Zimperium/Integrations/Zimperium/Zimperium_description.md
  Packs/Zimperium/Integrations/Zimperium/Zimperium_image.png
  Packs/Zimperium/Integrations/Zimperium/Zimperium_test.py
  Packs/Zimperium/Integrations/Zimperium/command_examples.txt
  Packs/Zimperium/Integrations/Zimperium/test_data/response_constants.py
  Packs/Zimperium/Integrations/Zimperium/test_data/result_constants.py
  Packs/Zimperium/Layouts/layout-details-Zimperium_event.json
  Packs/Zimperium/Playbooks/playbook-Zimperium_Incident_Enrichment.yml
  Packs/Zimperium/README.md
  Packs/Zimperium/TestPlaybooks/Zimperium_Test.yml
  Packs/Zimperium/pack_metadata.json
  Tests/conf.json
Labels: docs-approved

#7991 [Fix] tenable-io-launch-scan ignores scanTargets argument
  Packs/Tenable_io/Integrations/Tenable_io/Tenable_io.py
  Packs/Tenable_io/ReleaseNotes/1_0_1.md
  Packs/Tenable_io/pack_metadata.json
Labels: bug, docs-approved, release-notes-only

#7993 added no-tests to integration
  Packs/NonSupported/Integrations/integration-jira_2.5.yml
Labels: docs-approved

#7995 trustar v1 - mv to non circle tests
  TestPlaybooks/NonCircleTests/playbook-TruSTAR_Test.yml
  Tests/conf.json
  Tests/test_integration.py
Labels: docs-approved

#7989 update display names
  Packs/Remedy_AR/Integrations/integration-Remedy_AR.yml
  Packs/Remedy_AR/ReleaseNotes/1_0_1.md
  Packs/Remedy_AR/pack_metadata.json
  Packs/remedy_SR/Integrations/remedy_SR/remedy_SR.py
  Packs/remedy_SR/Integrations/remedy_SR/remedy_SR.yml
  Packs/remedy_SR/ReleaseNotes/1_0_1.md
  Packs/remedy_SR/pack_metadata.json
Labels: docs-approved, release-notes-only

#7946 [717938] New Blueliv ThreatCompass integration
  Packs/BluelivThreatCompass/.pack-ignore
  Packs/BluelivThreatCompass/.secrets-ignore
  Packs/BluelivThreatCompass/Integrations/BluelivThreatCompass/BluelivThreatCompass.py
  Packs/BluelivThreatCompass/Integrations/BluelivThreatCompass/BluelivThreatCompass.yml
  Packs/BluelivThreatCompass/Integrations/BluelivThreatCompass/BluelivThreatCompass_description.md
  Packs/BluelivThreatCompass/Integrations/BluelivThreatCompass/BluelivThreatCompass_image.png
  Packs/BluelivThreatCompass/Integrations/BluelivThreatCompass/BluelivThreatCompass_test.py
  Packs/BluelivThreatCompass/Integrations/BluelivThreatCompass/Pipfile
  Packs/BluelivThreatCompass/Integrations/BluelivThreatCompass/Pipfile.lock
  Packs/BluelivThreatCompass/Integrations/BluelivThreatCompass/README.md
  Packs/BluelivThreatCompass/README.md
  Packs/BluelivThreatCompass/TestPlaybooks/Blueliv_ThreatCompass_test.yml
  Packs/BluelivThreatCompass/pack_metadata.json
  Tests/conf.json
Labels: Contribution, docs-approved

#7952 Test filter for metadata
  Tests/scripts/collect_tests_and_content_packs.py
  Tests/scripts/infrastructure_tests/test_collect_tests_and_content_packs.py
Labels: docs-approved

#7915 Fix TLS bug (#7352)
  Packs/VMware/Integrations/integration-VMware.yml
  Packs/VMware/ReleaseNotes/1_0_1.md
  Packs/VMware/pack_metadata.json
Labels: docs-approved, release-notes-only

#8006 Updated docstring in ApiModule
  Packs/ApiModules/ReleaseNotes/1_0_4.md
  Packs/ApiModules/Scripts/MicrosoftApiModule/MicrosoftApiModule.py
  Packs/ApiModules/Scripts/MicrosoftApiModule/MicrosoftApiModule.yml
  Packs/ApiModules/pack_metadata.json
Labels: docs-approved

#7374 New dashboard for MITRE ATTACK indicators
  Packs/FeedMitreAttack/Dashboards/MITRE_ATT&CK.json
  Packs/FeedMitreAttack/Dashboards/MITRE_ATT&CK_CHANGELOG.md
  Packs/FeedMitreAttack/ReleaseNotes/1_0_6.md
  Packs/FeedMitreAttack/Scripts/MITREIndicatorsByOpenIncidents/CHANGELOG.md
  Packs/FeedMitreAttack/Scripts/MITREIndicatorsByOpenIncidents/MITREIndicatorsByOpenIncidents.py
  Packs/FeedMitreAttack/Scripts/MITREIndicatorsByOpenIncidents/MITREIndicatorsByOpenIncidents.yml
  Packs/FeedMitreAttack/Scripts/MITREIndicatorsByOpenIncidents/README.md
  Packs/FeedMitreAttack/pack_metadata.json
Labels: docs-approved

#8008 zimperium - get-report filter HR
  Packs/Zimperium/Integrations/Zimperium/README.md
  Packs/Zimperium/Integrations/Zimperium/Zimperium.py
  Tests/scripts/validate.sh
Labels: bug, docs-approved, release-notes-only

#8004 [Test Fix] - Bluecat Address Manager
  Packs/BluecatAddressManager/.secrets-ignore
  Packs/BluecatAddressManager/TestPlaybooks/playbook-Bluecat_Address_Manager_test.yml
  Tests/conf.json
Labels: docs-approved

#7925 PhishingDemo - remove reference to walkme from README
  Packs/OnboardingIntegration/Playbooks/playbook-PhishingDemo-Onboarding_README.md
Labels: docs-approved

#8013 Doc improvements
  Packs/AWS-IAM/Integrations/AWS-IAM/README.md
  Packs/BluelivThreatContext/Integrations/BluelivThreatContext/README.md
  Packs/CrowdStrikeFalcon/Integrations/CrowdStrikeFalcon/README.md
  Packs/DeprecatedContent/Playbooks/Access_Investigation_-_Generic_README.md
  Packs/GoogleChronicleBackstory/Integrations/GoogleChronicleBackstory/README.md
  Packs/Kenna/Integrations/KennaV2/README.md
  Packs/MinervaLabsAntiEvasionPlatform/Integrations/integration-MinervaLabsAntiEvasionPlatform_README.md
  Packs/NonSupported/Playbooks/playbook-Detonate_File_-_Generic_4_9_9_README.md
  Packs/NonSupported/Playbooks/playbook-Detonate_URL_-_Generic_4_9_9_README.md
  Packs/QRadar/Playbooks/playbook-QRadar-GetOffenseCorrelationV2_README.md
  Packs/ThreatMiner/Integrations/ThreatMiner/README.md
Labels: docs-approved

#7763 converting unicode response to string
  Packs/QRadar/Integrations/QRadar/QRadar.py
  Packs/QRadar/ReleaseNotes/1_0_5.md
  Packs/QRadar/pack_metadata.json
Labels: docs-approved, release-notes-only

#8000 Demistouploadfilev2
  Packs/DemistoRESTAPI/ReleaseNotes/1_1_0.md
  Packs/DemistoRESTAPI/Scripts/DemistoUploadFileV2/DemistoUploadFileV2.py
  Packs/DemistoRESTAPI/Scripts/DemistoUploadFileV2/DemistoUploadFileV2.yml
  Packs/DemistoRESTAPI/Scripts/DemistoUploadFileV2/DemistoUploadFileV2_test.py
  Packs/DemistoRESTAPI/Scripts/DemistoUploadFileV2/Pipfile
  Packs/DemistoRESTAPI/Scripts/DemistoUploadFileV2/Pipfile.lock
  Packs/DemistoRESTAPI/Scripts/DemistoUploadFileV2/README.md
  Packs/DemistoRESTAPI/Scripts/script-DemistoUploadFile.yml
  Packs/DemistoRESTAPI/pack_metadata.json
Labels: docs-approved

#8014 prisma access ip feed - Fixed an issue where the ***Location*** param…
  Packs/PrismaAccess/Integrations/PrismaAccessEgressIPFeed/PrismaAccessEgressIPFeed.py
  Packs/PrismaAccess/Integrations/PrismaAccessEgressIPFeed/PrismaAccessEgressIPFeed.yml
  Packs/PrismaAccess/ReleaseNotes/1_0_2.md
  Packs/PrismaAccess/pack_metadata.json
Labels: docs-approved

#7858 [Fix] Active Directory group lookup timing out
  Packs/Active_Directory_Query/Integrations/Active_Directory_Query/Active_Directory_Query.py
  Packs/Active_Directory_Query/Integrations/Active_Directory_Query/Active_Directory_Query.yml
  Packs/Active_Directory_Query/Integrations/Active_Directory_Query/README.md
  Packs/Active_Directory_Query/ReleaseNotes/1_0_2.md
  Packs/Active_Directory_Query/pack_metadata.json
Labels: bug, docs-approved

#8017 Build Fixes & Tweaks
  .circleci/config.yml
  Tests/scripts/prepare_content_packs_for_testing.sh
Labels: docs-approved

#8022 Infocyte test - set to run from version 5.5
  Tests/conf.json
Labels: docs-approved

#8019 fixed test playbook tasks
  Packs/Jira/TestPlaybooks/playbook-Jira-v2-Test_4_5_9.yml
  Packs/JoeSecurity/TestPlaybooks/playbook-JoeSecurityTest.yml
  Packs/OpenPhish/TestPlaybooks/playbook-OpenPhish-Test.yml
  Packs/Zscaler/TestPlaybooks/playbook-Zscaler_Test.yml
Labels: docs-approved

#7875 New scripts: isUrlPartOfDomain
  Packs/CommonScripts/Scripts/IsUrlPartOfDomain/IsUrlPartOfDomain.py
  Packs/CommonScripts/Scripts/IsUrlPartOfDomain/IsUrlPartOfDomain.yml
  Packs/CommonScripts/TestPlaybooks/playbook-IsUrlPartOfDomain.yml
Labels: docs-approved

#8021 Symatec ATP - fix get file test
  Packs/Symantec_Advanced_Threat_Protection/TestPlaybooks/playbook-Symantec_ATP_Test.yml
Labels: docs-approved

#8026 Un-skip Cisco Umbrella/fix test
  Packs/Cisco-umbrella/TestPlaybooks/playbook-Cisco-Umbrella-Python-Test.yml
  Packs/CommonPlaybooks/TestPlaybooks/playbook-Domain_Enrichment_-_Generic_v2_-_Test.yml
  Tests/conf.json
Labels: docs-approved

#8030 Blueliv fix for docs
  .circleci/config.yml
  Packs/BluelivThreatContext/Integrations/BluelivThreatContext/README.md
  Tests/scripts/validate.sh
  package-lock.json
  package.json
Labels: docs-approved
