Repository demisto/content, pull requests merged in 2021-08, with the labels that each got.

#13488 Misp v3
  Packs/MISP/.secrets-ignore
  Packs/MISP/Integrations/MISPV3/MISPV3.py
  Packs/MISP/Integrations/MISPV3/MISPV3.yml
  Packs/MISP/Integrations/MISPV3/MISPV3_description.md
  Packs/MISP/Integrations/MISPV3/MISPV3_image.png
  Packs/MISP/Integrations/MISPV3/MISPV3_test.py
  Packs/MISP/Integrations/MISPV3/Pipfile
  Packs/MISP/Integrations/MISPV3/Pipfile.lock
  Packs/MISP/Integrations/MISPV3/README.md
  Packs/MISP/Integrations/MISPV3/command_examples
  Packs/MISP/Integrations/MISPV3/test_data/Attribute_Tags.json
  Packs/MISP/Integrations/MISPV3/test_data/attribute_response_to_md.json
  Packs/MISP/Integrations/MISPV3/test_data/event_response_to_md.json
  Packs/MISP/Integrations/MISPV3/test_data/reputation_command_outputs.json
  Packs/MISP/Integrations/MISPV3/test_data/reputation_command_response.json
  Packs/MISP/Integrations/MISPV3/test_data/search_attribute_by_type.json
  Packs/MISP/Integrations/MISPV3/test_data/search_attribute_by_type_outputs.json
  Packs/MISP/Integrations/MISPV3/test_data/search_event_by_tag.json
  Packs/MISP/Integrations/MISPV3/test_data/search_event_by_tag_outputs.json
  Packs/MISP/ReleaseNotes/2_0_0.md
  Packs/MISP/TestPlaybooks/playbook-MISPV3-Test.yml
  Packs/MISP/pack_metadata.json
  Tests/conf.json
Labels: docs-approved

#13893 update Readme
  Packs/Arcanna/.secrets-ignore
  Packs/Arcanna/README.md
Labels: Contribution, Contribution Form Filled, Partner, docs-approved

#13909 Update tld docker
  Packs/CommonScripts/ReleaseNotes/1_4_12.md
  Packs/CommonScripts/Scripts/ExtractDomainAndFQDNFromUrlAndEmail/ExtractDomainAndFQDNFromUrlAndEmail.yml
  Packs/CommonScripts/Scripts/ExtractDomainFromUrlFormat/ExtractDomainFromUrlFormat.py
  Packs/CommonScripts/Scripts/ExtractDomainFromUrlFormat/ExtractDomainFromUrlFormat.yml
  Packs/CommonScripts/Scripts/ExtractDomainFromUrlFormat/ExtractDomainFromUrlFormat_test.py
  Packs/CommonScripts/Scripts/ExtractFQDNFromUrlAndEmail/ExtractFQDNFromUrlAndEmail.py
  Packs/CommonScripts/Scripts/ExtractFQDNFromUrlAndEmail/ExtractFQDNFromUrlAndEmail.yml
  Packs/CommonScripts/Scripts/ExtractFQDNFromUrlAndEmail/ExtractFQDNFromUrlAndEmail_test.py
  Packs/CommonScripts/pack_metadata.json
Labels: bug, docs-approved

#13743 Azure AD Identity Protection
  Packs/AzureActiveDirectory/.pack-ignore
  Packs/AzureActiveDirectory/.secrets-ignore
  Packs/AzureActiveDirectory/Integrations/AzureADIdentityProtection/AzureADIdentityProtection.py
  Packs/AzureActiveDirectory/Integrations/AzureADIdentityProtection/AzureADIdentityProtection.yml
  Packs/AzureActiveDirectory/Integrations/AzureADIdentityProtection/AzureADIdentityProtection_description.md
  Packs/AzureActiveDirectory/Integrations/AzureADIdentityProtection/AzureADIdentityProtection_image.png
  Packs/AzureActiveDirectory/Integrations/AzureADIdentityProtection/AzureADIdentityProtection_test.py
  Packs/AzureActiveDirectory/Integrations/AzureADIdentityProtection/README.md
  Packs/AzureActiveDirectory/Integrations/AzureADIdentityProtection/example_commands
  Packs/AzureActiveDirectory/Integrations/AzureADIdentityProtection/test_data/risk_detections_response.json
  Packs/AzureActiveDirectory/Integrations/AzureADIdentityProtection/test_data/risky_user_history_response.json
  Packs/AzureActiveDirectory/Integrations/AzureADIdentityProtection/test_data/risky_users_response.json
  Packs/AzureActiveDirectory/README.md
  Packs/AzureActiveDirectory/TestPlaybooks/playbook-AzureADIdentityProtection_Test.yml
  Packs/AzureActiveDirectory/pack_metadata.json
  Tests/conf.json
Labels: docs-approved

#13915 SetGridField sort fixes
  Packs/CommonScripts/ReleaseNotes/1_4_13.md
  Packs/CommonScripts/Scripts/SetGridField/README.md
  Packs/CommonScripts/Scripts/SetGridField/SetGridField.py
  Packs/CommonScripts/Scripts/SetGridField/SetGridField.yml
  Packs/CommonScripts/Scripts/SetGridField/SetGridField_test.py
  Packs/CommonScripts/Scripts/SetGridField/SetGridField_test/context_entry_list_of_dicts_non_sorted.json
  Packs/CommonScripts/Scripts/SetGridField/SetGridField_test/context_entry_list_of_dicts_non_sorted_multi.json
  Packs/CommonScripts/Scripts/SetGridField/SetGridField_test/expected_entry_list_of_dicts_sorted.json
  Packs/CommonScripts/Scripts/SetGridField/SetGridField_test/expected_entry_list_of_dicts_sorted_multi.json
  Packs/CommonScripts/pack_metadata.json
Labels: bug, docs-approved, release-notes-only

#13921 Urlscanio score fix
  Packs/UrlScan/Integrations/UrlScan/UrlScan.py
  Packs/UrlScan/Integrations/UrlScan/UrlScan.yml
  Packs/UrlScan/ReleaseNotes/1_1_9.md
  Packs/UrlScan/pack_metadata.json
Labels: docs-approved

#13896 MicrosoftApiModule - added resource usage to _oproxy_authorize
  Packs/ApiModules/Scripts/MicrosoftApiModule/MicrosoftApiModule.py
  Packs/ApiModules/Scripts/MicrosoftApiModule/MicrosoftApiModule.yml
  Packs/ApiModules/Scripts/MicrosoftApiModule/MicrosoftApiModule_test.py
  Packs/AzureCompute/ReleaseNotes/1_0_8.md
  Packs/AzureCompute/pack_metadata.json
  Packs/AzureKubernetesServices/ReleaseNotes/1_0_4.md
  Packs/AzureKubernetesServices/pack_metadata.json
  Packs/AzureLogAnalytics/ReleaseNotes/1_0_10.md
  Packs/AzureLogAnalytics/pack_metadata.json
  Packs/AzureNetworkSecurityGroups/ReleaseNotes/1_0_4.md
  Packs/AzureNetworkSecurityGroups/pack_metadata.json
  Packs/AzureSQLManagement/ReleaseNotes/1_0_5.md
  Packs/AzureSQLManagement/pack_metadata.json
  Packs/AzureSecurityCenter/ReleaseNotes/1_1_10.md
  Packs/AzureSecurityCenter/pack_metadata.json
  Packs/AzureSentinel/ReleaseNotes/1_0_12.md
  Packs/AzureSentinel/pack_metadata.json
  Packs/AzureStorage/ReleaseNotes/1_0_1.md
  Packs/AzureStorage/pack_metadata.json
  Packs/AzureWAF/ReleaseNotes/1_0_5.md
  Packs/AzureWAF/pack_metadata.json
  Packs/EWS/ReleaseNotes/1_8_31.md
  Packs/EWS/pack_metadata.json
  Packs/Microsoft365Defender/ReleaseNotes/1_1_1.md
  Packs/Microsoft365Defender/pack_metadata.json
  Packs/MicrosoftDefenderAdvancedThreatProtection/ReleaseNotes/1_2_15.md
  Packs/MicrosoftDefenderAdvancedThreatProtection/pack_metadata.json
  Packs/MicrosoftGraphAPI/ReleaseNotes/1_0_4.md
  Packs/MicrosoftGraphAPI/pack_metadata.json
  Packs/MicrosoftGraphApplications/ReleaseNotes/1_0_4.md
  Packs/MicrosoftGraphApplications/pack_metadata.json
  Packs/MicrosoftGraphCalendar/ReleaseNotes/1_0_8.md
  Packs/MicrosoftGraphCalendar/pack_metadata.json
  Packs/MicrosoftGraphDeviceManagement/ReleaseNotes/1_0_9.md
  Packs/MicrosoftGraphDeviceManagement/pack_metadata.json
  Packs/MicrosoftGraphFiles/ReleaseNotes/1_0_8.md
  Packs/MicrosoftGraphFiles/pack_metadata.json
  Packs/MicrosoftGraphGroups/ReleaseNotes/1_0_8.md
  Packs/MicrosoftGraphGroups/pack_metadata.json
  Packs/MicrosoftGraphIdentityandAccess/ReleaseNotes/1_0_4.md
  Packs/MicrosoftGraphIdentityandAccess/pack_metadata.json
  Packs/MicrosoftGraphListener/ReleaseNotes/1_0_18.md
  Packs/MicrosoftGraphListener/pack_metadata.json
  Packs/MicrosoftGraphMail/ReleaseNotes/1_0_21.md
  Packs/MicrosoftGraphMail/pack_metadata.json
  Packs/MicrosoftGraphSecurity/ReleaseNotes/2_0_10.md
  Packs/MicrosoftGraphSecurity/pack_metadata.json
  Packs/MicrosoftGraphUser/ReleaseNotes/1_3_10.md
  Packs/MicrosoftGraphUser/pack_metadata.json
  Packs/MicrosoftManagementActivity/ReleaseNotes/1_2_1.md
  Packs/MicrosoftManagementActivity/pack_metadata.json
  Packs/MicrosoftTeams/ReleaseNotes/1_1_13.md
  Packs/MicrosoftTeams/pack_metadata.json
Labels: bug, docs-approved, release-notes-only

#13936 SMIME Messaging - change chardet to charset-normalize
  Packs/SMIME_Messaging/Integrations/SMIME_Messaging/SMIME_Messaging.py
  Packs/SMIME_Messaging/Integrations/SMIME_Messaging/SMIME_Messaging_test.py
  Packs/SMIME_Messaging/ReleaseNotes/1_0_4.md
  Packs/SMIME_Messaging/pack_metadata.json
Labels: bug, docs-approved, release-notes-only

#13919 Handle Proofpoint rewrite URLs v3
  Packs/CommonScripts/ReleaseNotes/1_4_14.md
  Packs/CommonScripts/Scripts/ExtractDomainAndFQDNFromUrlAndEmail/ExtractDomainAndFQDNFromUrlAndEmail.py
  Packs/CommonScripts/Scripts/ExtractDomainAndFQDNFromUrlAndEmail/ExtractDomainAndFQDNFromUrlAndEmail_test.py
  Packs/CommonScripts/pack_metadata.json
Labels: bug, docs-approved, release-notes-only

#13942 Change listing category from Utilities to Data Enrichment & Threat Intelligence in yml file
  Packs/CofenseIntelligenceV2/Integrations/CofenseIntelligenceV2/CofenseIntelligenceV2.yml
  Packs/CofenseIntelligenceV2/ReleaseNotes/1_0_1.md
  Packs/CofenseIntelligenceV2/pack_metadata.json
Labels: Contribution, Contribution Form Filled, docs-approved

#13943 Update README.md
  Packs/GoogleChronicleBackstory/README.md
Labels: Contribution, Contribution Form Filled, Partner, docs-approved

#13944 Update pack_metadata.json
  Packs/GoogleChronicleBackstory/pack_metadata.json
Labels: Contribution, Contribution Form Filled, Partner, docs-approved

#13934 Change product name and update pack information
  Packs/Polygon/Integrations/Polygon/Polygon.py
  Packs/Polygon/Integrations/Polygon/Polygon.yml
  Packs/Polygon/Integrations/Polygon/Polygon_description.md
  Packs/Polygon/Integrations/Polygon/README.md
  Packs/Polygon/Integrations/Polygon/test_data/results.json
  Packs/Polygon/Playbooks/playbook-Detonate_File_-_Group-IB_TDS_Polygon.yml
  Packs/Polygon/Playbooks/playbook-Detonate_File_-_Group-IB_TDS_Polygon_README.md
  Packs/Polygon/Playbooks/playbook-Detonate_URL_-_Group-IB_TDS_Polygon.yml
  Packs/Polygon/Playbooks/playbook-Detonate_URL_-_Group-IB_TDS_Polygon_README.md
  Packs/Polygon/README.md
  Packs/Polygon/ReleaseNotes/1_0_5.md
  Packs/Polygon/TestPlaybooks/playbook-Polygon-Test.yml
  Packs/Polygon/pack_metadata.json
Labels: Contribution, Contribution Form Filled, Partner, docs-approved

#13897 [QRadar v2] Add Requests timeout advanced parameter
  Packs/QRadar/Integrations/QRadar_v2/QRadar_v2.py
  Packs/QRadar/Integrations/QRadar_v2/QRadar_v2.yml
  Packs/QRadar/Integrations/QRadar_v2/QRadar_v2_description.md
  Packs/QRadar/ReleaseNotes/2_0_18.md
  Packs/QRadar/pack_metadata.json
Labels: docs-approved

#13894 skip non string headers
  Packs/EWS/Integrations/EWSO365/EWSO365.py
  Packs/EWS/Integrations/EWSO365/EWSO365_test.py
  Packs/EWS/ReleaseNotes/1_8_30.md
  Packs/EWS/ReleaseNotes/1_8_32.md
  Packs/EWS/pack_metadata.json
Labels: docs-approved

#13950 Fix GitLab Job Failures
  .gitlab/ci/.gitlab-ci.yml
  .gitlab/ci/global.yml
  Tests/secrets_white_list.json
Labels: docs-approved

#13923 Atlassian confluence fix
  Packs/Confluence/Integrations/Confluence/Confluence.py
  Packs/Confluence/Integrations/Confluence/Confluence.yml
  Packs/Confluence/ReleaseNotes/1_0_2.md
  Packs/Confluence/pack_metadata.json
Labels: bug, docs-approved, release-notes-only

#13914 Smbv2 revert patch
  Packs/SMB/Integrations/SMB_v2/SMB_v2.py
  Packs/SMB/Integrations/SMB_v2/SMB_v2.yml
  Packs/SMB/ReleaseNotes/2_0_4.md
  Packs/SMB/pack_metadata.json
  Packs/VMRay/TestPlaybooks/playbook-VMRay-test-File.yml
  Packs/VMRay/TestPlaybooks/playbook-VMRay-test-URL.yml
  Tests/conf.json
Labels: docs-approved

#13945 Slack notifier coverage URL
  Tests/scripts/slack_notifier.py
Labels: docs-approved

#13473 New Azure Storage Playbooks
  Packs/PrismaCloud/Classifiers/classifier-Prisma_Cloud.json
  Packs/PrismaCloud/Classifiers/classifier-Prisma_Cloud_5_9_9.json
  Packs/PrismaCloud/Classifiers/classifier-prismaCloud_app.json
  Packs/PrismaCloud/Classifiers/classifier-prismaCloud_app_5_9_9.json
  Packs/PrismaCloud/IncidentFields/incidentfield-Prisma_Cloud_ID.json
  Packs/PrismaCloud/IncidentFields/incidentfield-Prisma_Cloud_Reason.json
  Packs/PrismaCloud/IncidentFields/incidentfield-Prisma_Cloud_Rules.json
  Packs/PrismaCloud/IncidentFields/incidentfield-Prisma_Cloud_Status.json
  Packs/PrismaCloud/IncidentFields/incidentfield-Prisma_Cloud_Time.json
  Packs/PrismaCloud/IncidentFields/incidentfield-RRN.json
  Packs/PrismaCloud/IncidentFields/incidentfield-Resource_API_Name.json
  Packs/PrismaCloud/IncidentFields/incidentfield-Resource_Cloud_Type.json
  Packs/PrismaCloud/IncidentFields/incidentfield-Subscription_Assigned_By.json
  Packs/PrismaCloud/IncidentFields/incidentfield-Subscription_Created_By.json
  Packs/PrismaCloud/IncidentFields/incidentfield-Subscription_Created_On.json
  Packs/PrismaCloud/IncidentFields/incidentfield-Subscription_Description.json
  Packs/PrismaCloud/IncidentFields/incidentfield-Subscription_ID.json
  Packs/PrismaCloud/IncidentFields/incidentfield-Subscription_Name.json
  Packs/PrismaCloud/IncidentFields/incidentfield-Subscription_Type.json
  Packs/PrismaCloud/IncidentFields/incidentfield-Subscription_Updated_By.json
  Packs/PrismaCloud/IncidentFields/incidentfield-Subscription_Updated_On.json
  Packs/PrismaCloud/IncidentFields/incidentfield-System_Default.json
  Packs/PrismaCloud/IncidentFields/incidentfield-VPC_ID.json
  Packs/PrismaCloud/IncidentTypes/incidenttype-Azure_Storage_Misconfiguration.json
  Packs/PrismaCloud/Layouts/layout-detailsV2-Azure_Storage_Misconfiguration.json
  Packs/PrismaCloud/Layouts/layoutscontainer-Azure_Storage_Misconfiguration.json
  Packs/PrismaCloud/Playbooks/playbook-PCR_-_Azure_Storage_Blob_Misconfig.yml
  Packs/PrismaCloud/Playbooks/playbook-PCR_-_Azure_Storage_Blob_Misconfig_README.md
  Packs/PrismaCloud/Playbooks/playbook-PCR_-_Azure_Storage_Misconfig.yml
  Packs/PrismaCloud/Playbooks/playbook-PCR_-_Azure_Storage_Misconfig_README.md
  Packs/PrismaCloud/ReleaseNotes/1_8_0.md
  Packs/PrismaCloud/doc_files/PCR_-_Azure_Storage_Blob_Misconfig.png
  Packs/PrismaCloud/doc_files/PCR_-_Azure_Storage_Misconfig.png
  Packs/PrismaCloud/pack_metadata.json
  Tests/scripts/slack_notifier.py
Labels: Contribution, docs-approved

#13962 add ignore to author image cortex911
  Packs/Cortex911/.pack-ignore
Labels: docs-approved

#13884 QRadar enrich closing reason with note of a mirrored incident
  Packs/QRadar/Integrations/QRadar_v3/QRadar_v3.py
  Packs/QRadar/Integrations/QRadar_v3/QRadar_v3.yml
  Packs/QRadar/Integrations/QRadar_v3/QRadar_v3_test.py
  Packs/QRadar/ReleaseNotes/2_0_19.md
  Packs/QRadar/pack_metadata.json
Labels: docs-approved, release-notes-only

#13933 Azure Sentinel doc fix
  Packs/AzureSentinel/Integrations/AzureSentinel/README.md
Labels: docs-approved

#13927 IAM - added support in identifier change
  Packs/Active_Directory_Query/ReleaseNotes/1_2_2.md
  Packs/Active_Directory_Query/pack_metadata.json
  Packs/ApiModules/Scripts/IAMApiModule/IAMApiModule.py
  Packs/ApiModules/Scripts/IAMApiModule/IAMApiModule.yml
  Packs/Attlasian/ReleaseNotes/1_1_1.md
  Packs/Attlasian/pack_metadata.json
  Packs/GitHub/ReleaseNotes/1_3_3.md
  Packs/GitHub/pack_metadata.json
  Packs/HelloIAMWorld/ReleaseNotes/1_1_1.md
  Packs/HelloIAMWorld/pack_metadata.json
  Packs/Okta/Integrations/Okta_IAM/Okta_IAM.py
  Packs/Okta/ReleaseNotes/2_2_2.md
  Packs/Okta/pack_metadata.json
  Packs/Salesforce/ReleaseNotes/1_1_1.md
  Packs/Salesforce/pack_metadata.json
  Packs/ServiceNow/ReleaseNotes/2_2_2.md
  Packs/ServiceNow/pack_metadata.json
  Packs/Slack/ReleaseNotes/2_1_2.md
  Packs/Slack/pack_metadata.json
  Packs/Workday/Integrations/Workday_IAM/Workday_IAM.py
  Packs/Workday/Integrations/Workday_IAM/test_data/fetch_incidents_email_change_mock_data.py
  Packs/Workday/Integrations/Workday_IAM/test_data/fetch_incidents_employee_id_change_mock_data.py
  Packs/Workday/ReleaseNotes/1_2_2.md
  Packs/Workday/pack_metadata.json
Labels: docs-approved

#13917 Ssdeep similarity
  Packs/CommonScripts/ReleaseNotes/1_4_15.md
  Packs/CommonScripts/Scripts/SSDeepSimilarity/README.md
  Packs/CommonScripts/Scripts/SSDeepSimilarity/SSDeepSimilarity.py
  Packs/CommonScripts/Scripts/SSDeepSimilarity/SSDeepSimilarity.yml
  Packs/CommonScripts/Scripts/SSDeepSimilarity/SSDeepSimilarity_test.py
  Packs/CommonScripts/pack_metadata.json
Labels: docs-approved

#13966 Net to com
  Packs/SumoLogic_Cloud_SIEM/Integrations/SumoLogicCloudSIEM/README.md
  Packs/SumoLogic_Cloud_SIEM/Integrations/SumoLogicCloudSIEM/SumoLogicCloudSIEM_description.md
  Packs/SumoLogic_Cloud_SIEM/ReleaseNotes/1_1_1.md
  Packs/SumoLogic_Cloud_SIEM/pack_metadata.json
Labels: Contribution, Contribution Form Filled, Partner, docs-approved

#13825 ParseEmailFiles - verify email data is not None
  Packs/CommonScripts/.secrets-ignore
  Packs/CommonScripts/ReleaseNotes/1_4_16.md
  Packs/CommonScripts/Scripts/ParseEmailFiles/ParseEmailFiles.py
  Packs/CommonScripts/Scripts/ParseEmailFiles/ParseEmailFiles_test.py
  Packs/CommonScripts/Scripts/ParseEmailFiles/test_data/email_with_signed_attachment.eml
  Packs/CommonScripts/pack_metadata.json
Labels: bug, docs-approved, release-notes-only

#13939 [malwarebytes-254] Update README.md
  Packs/Malwarebytes/README.md
Labels: Contribution, Contribution Form Filled, Partner, docs-approved

#13885 Unskip Azure Security Center in nightly
  Tests/conf.json
Labels: docs-approved

#13992 BitcoinAbuse Tags & TLP bug
  Packs/BitcoinAbuse/Integrations/BitcoinAbuse/BitcoinAbuse.py
  Packs/BitcoinAbuse/Integrations/BitcoinAbuse/BitcoinAbuse_test.py
  Packs/BitcoinAbuse/Integrations/BitcoinAbuse/test_data/get_indicators_command.json
  Packs/BitcoinAbuse/ReleaseNotes/1_0_9.md
  Packs/BitcoinAbuse/pack_metadata.json
Labels: bug, docs-approved, release-notes-only

#13973 Fix a git diff cmd
  .gitlab/ci/global.yml
  Tests/scripts/collect_tests_and_content_packs.py
  Utils/gitlab_triggers/trigger_content_nightly_build.sh
Labels: docs-approved

#13991 Add Default Value for IndicatorsSearcher iocs
  Packs/Base/ReleaseNotes/1_13_11.md
  Packs/Base/Scripts/CommonServerPython/CommonServerPython.py
  Packs/Base/pack_metadata.json
Labels: docs-approved

#13320 reworded and moved indicator score calculation
  Packs/NonSupported/Integrations/integration-VirusTotal_README.md
Labels: docs-approved

#13972 Added support for multipart/related
  Packs/CommonScripts/ReleaseNotes/1_4_17.md
  Packs/CommonScripts/Scripts/ParseEmailFiles/ParseEmailFiles.py
  Packs/CommonScripts/Scripts/ParseEmailFiles/ParseEmailFiles_test.py
  Packs/CommonScripts/Scripts/ParseEmailFiles/test_data/multipart_related_format.p7m
  Packs/CommonScripts/Scripts/ParseEmailFiles/test_data/multipart_related_format_old.p7m
  Packs/CommonScripts/pack_metadata.json
Labels: bug, docs-approved, release-notes-only

#13997 changing sdk to branch to check pwsh lint fix
  dev-requirements-py3.txt
Labels: docs-approved

#13516 Phishing Campaign Pack Additions (playbook, inc type+layout, scripts)
  Packs/Campaign/IncidentFields/incidentfield-Select_Campaign_Incidents.json
  Packs/Campaign/IncidentTypes/PhishingCampaign.json
  Packs/Campaign/Layouts/layoutscontainer-Phishing_Campaign.json
  Packs/Campaign/Playbooks/Detect_&_Manage_Phishing_Campaigns.yml
  Packs/Campaign/Playbooks/Detect_&_Manage_Phishing_Campaigns_README.md
  Packs/Campaign/README.md
  Packs/Campaign/ReleaseNotes/3_0_0.md
  Packs/Campaign/Scripts/ShowCampaignHighestSeverity.yml
  Packs/Campaign/Scripts/ShowCampaignUniqueRecipients.yml
  Packs/Campaign/Scripts/ShowCampaignUniqueSenders.yml
  Packs/Campaign/Scripts/ShowNumberOfCampaignIncidents.yml
  Packs/Campaign/doc_files/Detect_&_Manage_Phishing_Campaigns.png
  Packs/Campaign/pack_metadata.json
Labels: docs-approved

#13990 Fix NTLM hash parse and TGT expired issue
  Packs/Pcysys/Integrations/Pcysys/Pcysys.py
  Packs/Pcysys/Integrations/Pcysys/Pcysys.yml
  Packs/Pcysys/Integrations/Pcysys/Pcysys_test.py
  Packs/Pcysys/ReleaseNotes/1_3_0.md
  Packs/Pcysys/pack_metadata.json
Labels: Contribution, Contribution Form Filled, Partner, docs-approved

#14014 Fix rawJSON for indicators
  Packs/GroupIB_ThreatIntelligenceAttribution/Integrations/GroupIB_TIA_Feed/GroupIB_TIA_Feed.py
  Packs/GroupIB_ThreatIntelligenceAttribution/Integrations/GroupIB_TIA_Feed/GroupIB_TIA_Feed.yml
  Packs/GroupIB_ThreatIntelligenceAttribution/Integrations/GroupIB_TIA_Feed/test_data/results.json
  Packs/GroupIB_ThreatIntelligenceAttribution/ReleaseNotes/1_1_1.md
  Packs/GroupIB_ThreatIntelligenceAttribution/pack_metadata.json
Labels: Contribution, Contribution Form Filled, docs-approved

#14017 hotfix - changing sdk version
  dev-requirements-py3.txt
Labels: docs-approved

#14021 [malwarebytes-254] Fix for Suspicious activities incident creation.
  Packs/Malwarebytes/Integrations/Malwarebytes/Malwarebytes.py
  Packs/Malwarebytes/Integrations/Malwarebytes/Malwarebytes.yml
  Packs/Malwarebytes/ReleaseNotes/1_1_2.md
  Packs/Malwarebytes/pack_metadata.json
Labels: Contribution, docs-approved, Contribution Form Filled

#14015 Update jamf docs
  Packs/jamf/Integrations/jamfV2/README.md
Labels: docs-approved

#14026 Phishing Campaign Pack Additions (playbook, inc type+layout, scripts) - again
  Packs/Campaign/IncidentFields/incidentfield-Select_Campaign_Incidents.json
  Packs/Campaign/IncidentTypes/PhishingCampaign.json
  Packs/Campaign/Layouts/layoutscontainer-Phishing_Campaign.json
  Packs/Campaign/Playbooks/Detect_&_Manage_Phishing_Campaigns.yml
  Packs/Campaign/Playbooks/Detect_&_Manage_Phishing_Campaigns_README.md
  Packs/Campaign/README.md
  Packs/Campaign/ReleaseNotes/3_0_0.md
  Packs/Campaign/Scripts/ShowCampaignHighestSeverity.yml
  Packs/Campaign/Scripts/ShowCampaignUniqueRecipients.yml
  Packs/Campaign/Scripts/ShowCampaignUniqueSenders.yml
  Packs/Campaign/Scripts/ShowNumberOfCampaignIncidents.yml
  Packs/Campaign/doc_files/Detect_&_Manage_Phishing_Campaigns.png
  Packs/Campaign/pack_metadata.json
Labels: docs-approved

#14013 Increase fetch depth
  .gitlab/ci/global.yml
Labels: docs-approved

#14032 fixed script names
  Packs/Campaign/Scripts/script-ShowCampaignHighestSeverity.yml
  Packs/Campaign/Scripts/script-ShowCampaignUniqueRecipients.yml
  Packs/Campaign/Scripts/script-ShowCampaignUniqueSenders.yml
  Packs/Campaign/Scripts/script-ShowNumberOfCampaignIncidents.yml
Labels: docs-approved

#14012 [EDL] Add CIDR to Collpased IPs
  Packs/EDL/.secrets-ignore
  Packs/EDL/Integrations/EDL/EDL.py
  Packs/EDL/Integrations/EDL/EDL.yml
  Packs/EDL/Integrations/EDL/EDL_test.py
  Packs/EDL/ReleaseNotes/2_1_2.md
  Packs/EDL/pack_metadata.json
Labels: bug, docs-approved, release-notes-only

#13974 Crowdstrike feed bugs
  Packs/FeedCrowdstrikeFalconIntel/Integrations/CrowdStrikeIndicatorFeed/CrowdStrikeIndicatorFeed.py
  Packs/FeedCrowdstrikeFalconIntel/Integrations/CrowdStrikeIndicatorFeed/CrowdStrikeIndicatorFeed.yml
  Packs/FeedCrowdstrikeFalconIntel/Integrations/CrowdStrikeIndicatorFeed/CrowdStrikeIndicatorFeed_test.py
  Packs/FeedCrowdstrikeFalconIntel/Integrations/CrowdStrikeIndicatorFeed/test_data/create_indicators_from_response.json
  Packs/FeedCrowdstrikeFalconIntel/Integrations/CrowdStrikeIndicatorFeed/test_data/crowdstrike_indicators_list_command.json
  Packs/FeedCrowdstrikeFalconIntel/ReleaseNotes/2_0_3.md
  Packs/FeedCrowdstrikeFalconIntel/pack_metadata.json
Labels: bug, docs-approved

#14037 Update Slack App Manifest to add new scopes
  Packs/Slack/doc_files/SlackV3_app_manifest.yml
Labels: docs-approved

#13904 Pan os url filter
  Packs/PAN-OS/.pack-ignore
  Packs/PAN-OS/Integrations/Panorama/Panorama.py
  Packs/PAN-OS/Integrations/Panorama/Panorama.yml
  Packs/PAN-OS/Playbooks/playbook-PAN-OS_-_Create_Or_Edit_Rule.yml
  Packs/PAN-OS/ReleaseNotes/1_6_23.md
  Packs/PAN-OS/TestPlaybooks/playbook-PAN-OS_-_Block_IP_-_Custom_Block_Rule_Test.yml
  Packs/PAN-OS/TestPlaybooks/playbook-PAN-OS_-_Block_IP_-_Static_Address_Group_Test.yml
  Packs/PAN-OS/TestPlaybooks/playbook-PAN-OS_-_Block_IP_and_URL_-_External_Dynamic_List_v2_Test.yml
  Packs/PAN-OS/TestPlaybooks/playbook-PAN-OS_-_Block_URL_-_Custom_URL_Category_Test.yml
  Packs/PAN-OS/TestPlaybooks/playbook-PAN-OS_-_URL_FIltering_Enrichment-Test.yml
  Packs/PAN-OS/TestPlaybooks/playbook-PAN-OS_Create_Or_Edit_Rule_Test.yml
  Packs/PAN-OS/TestPlaybooks/playbook-PAN-OS_DAG_Configuration_Test.yml
  Packs/PAN-OS/TestPlaybooks/playbook-PAN-OS_EDL_Setup_v3_Test.yml
  Packs/PAN-OS/TestPlaybooks/playbook-PAN-OS_Query_Logs_For_Indicators_Test.yml
  Packs/PAN-OS/TestPlaybooks/playbook-Panorama_Query_Logs_-_Test.yml
  Packs/PAN-OS/TestPlaybooks/playbook-palo_alto_firewall_test_pb.yml
  Packs/PAN-OS/TestPlaybooks/playbook-palo_alto_panorama_test_best_practice.yml
  Packs/PAN-OS/TestPlaybooks/playbook-palo_alto_panorama_test_pb.yml
  Packs/PAN-OS/pack_metadata.json
  Tests/conf.json
Labels: bug, docs-approved, release-notes-only

#14039 reverted git diff command
  .circleci/content_release_vars.sh
  Tests/configure_and_test_integration_instances.py
  Tests/scripts/collect_tests_and_content_packs.py
Labels: docs-approved

#13881 [Export Indicators Service] Use IndicatorsSearcher iterator when looking for Indicators
  Packs/Base/ReleaseNotes/1_13_12.md
  Packs/Base/Scripts/CommonServerPython/CommonServerPython.py
  Packs/Base/pack_metadata.json
  Packs/EDL/Integrations/EDL/EDL.py
  Packs/EDL/ReleaseNotes/2_1_3.md
  Packs/EDL/pack_metadata.json
  Packs/ExportIndicators/Integrations/ExportIndicators/ExportIndicators.py
  Packs/ExportIndicators/Integrations/ExportIndicators/ExportIndicators.yml
  Packs/ExportIndicators/Integrations/ExportIndicators/ExportIndicators_description.md
  Packs/ExportIndicators/Integrations/ExportIndicators/ExportIndicators_test.py
  Packs/ExportIndicators/ReleaseNotes/1_0_11.md
  Packs/ExportIndicators/pack_metadata.json
  Packs/Hey/TestPlaybooks/platbook-ExportIndicators_Performance_test.yml
  Tests/conf.json
Labels: docs-approved, release-notes-only

#14029 Mcas timeout
  Packs/MicrosoftCloudAppSecurity/Integrations/MicrosoftCloudAppSecurity/MicrosoftCloudAppSecurity.py
  Packs/MicrosoftCloudAppSecurity/Integrations/MicrosoftCloudAppSecurity/MicrosoftCloudAppSecurity.yml
  Packs/MicrosoftCloudAppSecurity/Integrations/MicrosoftCloudAppSecurity/README.md
  Packs/MicrosoftCloudAppSecurity/ReleaseNotes/1_0_21.md
  Packs/MicrosoftCloudAppSecurity/pack_metadata.json
Labels: bug, docs-approved, release-notes-only

#14042 GitLab CI - set git depth level to 0
  .gitlab/ci/.gitlab-ci.yml
Labels: docs-approved

#13995 Document Limitation for the anyrun-get-report command
  Packs/ANYRUN/Integrations/ANYRUN/README.md
Labels: docs-approved

#14006 [Marketplace Contribution] Common Scripts - Content Pack Update
  Packs/CommonScripts/ReleaseNotes/1_4_18.md
  Packs/CommonScripts/Scripts/script-ConvertTableToHTML.yml
  Packs/CommonScripts/pack_metadata.json
Labels: docs-approved

#14022 Parseemailfile bug fix
  Packs/CommonScripts/ReleaseNotes/1_4_19.md
  Packs/CommonScripts/Scripts/ParseEmailFiles/ParseEmailFiles.py
  Packs/CommonScripts/pack_metadata.json
Labels: docs-approved

#13959 RestartFailedTasks - removed sleep time check
  Packs/IntegrationsAndIncidentsHealthCheck/ReleaseNotes/1_2_3.md
  Packs/IntegrationsAndIncidentsHealthCheck/Scripts/RestartFailedTasks/RestartFailedTasks.py
  Packs/IntegrationsAndIncidentsHealthCheck/Scripts/RestartFailedTasks/RestartFailedTasks.yml
  Packs/IntegrationsAndIncidentsHealthCheck/pack_metadata.json
Labels: docs-approved, release-notes-only

#14043 kenna - fix tpb
  Packs/Kenna/TestPlaybooks/playbook-Kenna_Test.yml
  Tests/conf.json
Labels: docs-approved

#14045 Update dependencies in O365 Search/Delete Docs.
  Packs/EWS/Playbooks/playbook-Office_365_Search_and_Delete_README.md
Labels: docs-approved

#13993 Rasterize - return output as JSON
  Packs/rasterize/Integrations/rasterize/rasterize.py
  Packs/rasterize/Integrations/rasterize/rasterize.yml
  Packs/rasterize/ReleaseNotes/1_0_9.md
  Packs/rasterize/pack_metadata.json
Labels: docs-approved

#14046 Clarify Docs for Generic Webhook Endpoints
  Packs/GenericWebhook/Integrations/GenericWebhook/README.md
Labels: docs-approved

#14047 Thycotic defintion typo
  Packs/Thycotic/pack_metadata.json
Labels: docs-approved

#13886 CircleCI - Add trigger workflow command
  Packs/CircleCI/Integrations/CircleCI/CircleCI.py
  Packs/CircleCI/Integrations/CircleCI/CircleCI.yml
  Packs/CircleCI/Integrations/CircleCI/README.md
  Packs/CircleCI/Integrations/CircleCI/command_examples
  Packs/CircleCI/ReleaseNotes/1_0_2.md
  Packs/CircleCI/pack_metadata.json
Labels: docs-approved

#14018 changing timeout in FindDuplicatesEmailIncidents
  Packs/Phishing/ReleaseNotes/2_2_8.md
  Packs/Phishing/Scripts/FindDuplicateEmailIncidents/FindDuplicateEmailIncidents.yml
  Packs/Phishing/pack_metadata.json
Labels: docs-approved

#14050 Update Docs for Symantec Endpoint Protection.
  Packs/SymantecEndpointProtection/Integrations/SymantecEndpointProtection_V2/README.md
Labels: docs-approved

#14051 unskipped zscaler TPB
  Tests/conf.json
Labels: docs-approved

#14053 Update global.yml
  .gitlab/ci/global.yml
Labels: docs-approved

#14054 Update Upload-Flow Codeowners
  .github/CODEOWNERS
Labels: docs-approved

#13501 Phishing Campaign And Compliance
  Packs/Phishing/Layouts/layoutscontainer-Phishing.json
  Packs/Phishing/Playbooks/Phishing_Investigation_-_Generic_v2.yml
  Packs/Phishing/Playbooks/Phishing_Investigation_-_Generic_v2_-_6_0.yml
  Packs/Phishing/Playbooks/Phishing_Investigation_-_Generic_v2_README.md
  Packs/Phishing/README.md
  Packs/Phishing/ReleaseNotes/2_3_0.md
  Packs/Phishing/Scripts/LinkToPhishingCampaign/LinkToPhishingCampaign.py
  Packs/Phishing/Scripts/LinkToPhishingCampaign/LinkToPhishingCampaign.yml
  Packs/Phishing/doc_files/Phishing_Investigation_-_Generic_v2_-_6_0.png
  Packs/Phishing/pack_metadata.json
Labels: docs-approved

#13961 GitHub get file content add organization and repository args
  Packs/GitHub/Integrations/GitHub/GitHub.py
  Packs/GitHub/Integrations/GitHub/GitHub.yml
  Packs/GitHub/Integrations/GitHub/README.md
  Packs/GitHub/ReleaseNotes/1_3_4.md
  Packs/GitHub/pack_metadata.json
Labels: docs-approved

#13870 Active Directory Query v2 Enhancements
  Packs/Active_Directory_Query/Integrations/Active_Directory_Query/Active_Directory_Query.py
  Packs/Active_Directory_Query/Integrations/Active_Directory_Query/Active_Directory_Query.yml
  Packs/Active_Directory_Query/Integrations/Active_Directory_Query/README.md
  Packs/Active_Directory_Query/Integrations/Active_Directory_Query/connection_test.py
  Packs/Active_Directory_Query/ReleaseNotes/1_3_0.md
  Packs/Active_Directory_Query/pack_metadata.json
Labels: docs-approved, release-notes-only

#14048 SecurityAndCompliance: Moved to GA
  Packs/EWS/Integrations/SecurityAndCompliance/README.md
  Packs/EWS/Integrations/SecurityAndCompliance/SecurityAndCompliance.yml
  Packs/EWS/ReleaseNotes/1_9_0.md
  Packs/EWS/pack_metadata.json
Labels: docs-approved

#14059 panorama - increase timeout
  Tests/conf.json
Labels: docs-approved

#14060 Zscaler skip TPB
  Tests/conf.json
Labels: docs-approved

#14049 Add CompareIndicators Script
  Packs/DeveloperTools/.secrets-ignore
  Packs/DeveloperTools/ReleaseNotes/1_2_0.md
  Packs/DeveloperTools/Scripts/CompareIndicators/CompareIndicators.py
  Packs/DeveloperTools/Scripts/CompareIndicators/CompareIndicators.yml
  Packs/DeveloperTools/Scripts/CompareIndicators/CompareIndicators_test.py
  Packs/DeveloperTools/Scripts/CompareIndicators/Pipfile
  Packs/DeveloperTools/Scripts/CompareIndicators/Pipfile.lock
  Packs/DeveloperTools/Scripts/CompareIndicators/README.md
  Packs/DeveloperTools/Scripts/CompareIndicators/test_files/ips.txt
  Packs/DeveloperTools/pack_metadata.json
Labels: docs-approved

#12381 Phishing playbook readme update for campaign
  Packs/Phishing/Playbooks/Phishing_Investigation_-_Generic_v2_README.md
  Packs/Phishing/README.md
Labels: docs-approved

#13693 Preprocess languages
  Packs/Base/ReleaseNotes/1_13_13.md
  Packs/Base/Scripts/DBotBuildPhishingClassifier/DBotBuildPhishingClassifier.yml
  Packs/Base/Scripts/DBotPredictPhishingWords/DBotPredictPhishingWords.yml
  Packs/Base/Scripts/DBotPreprocessTextData/DBotPreprocessTextData.py
  Packs/Base/Scripts/DBotPreprocessTextData/DBotPreprocessTextData.yml
  Packs/Base/Scripts/DBotPreprocessTextData/dbot_preprocess_text_data_test.py
  Packs/Base/TestPlaybooks/playbook-Create_Phishing_Classifier_V2_ML_Test.yml
  Packs/Base/TestPlaybooks/playbook-DBot_Build_Phishing_Classifier_Test_-_Multiple_Algorithms.yml
  Packs/Base/TestPlaybooks/playbook-DBot_Create_Phishing_Classifier_V2_From_File-_Test.yml
  Packs/Base/pack_metadata.json
  Packs/ML/TestPlaybooks/playbook-VerifyOOBV2Predictions.yml
Labels: docs-approved

#13920 Update MicrosoftTeams_description.md
  Packs/MicrosoftTeams/Integrations/MicrosoftTeams/MicrosoftTeams_description.md
  Packs/MicrosoftTeams/Integrations/MicrosoftTeams/README.md
  Packs/MicrosoftTeams/ReleaseNotes/1_1_14.md
  Packs/MicrosoftTeams/pack_metadata.json
Labels: docs-approved

#14056 GitHub get path data command
  Packs/GitHub/Integrations/GitHub/GitHub.py
  Packs/GitHub/Integrations/GitHub/GitHub.yml
  Packs/GitHub/Integrations/GitHub/GitHub_test.py
  Packs/GitHub/Integrations/GitHub/README.md
  Packs/GitHub/Integrations/GitHub/command_examples
  Packs/GitHub/Integrations/GitHub/test_data/get_path_data_response.json
  Packs/GitHub/ReleaseNotes/1_3_5.md
  Packs/GitHub/TestPlaybooks/Git_Integration-Test.yml
  Packs/GitHub/pack_metadata.json
Labels: docs-approved

#14055 Add word tokenizer clustering
  Packs/Base/ReleaseNotes/1_13_14.md
  Packs/Base/Scripts/DBotTrainClustering/DBotTrainClustering.py
  Packs/Base/Scripts/DBotTrainClustering/DBotTrainClustering.yml
  Packs/Base/Scripts/DBotTrainClustering/dbottrainclustering_test.py
  Packs/Base/pack_metadata.json
Labels: docs-approved

#14073 Fixed validation for microsoftTeams
  Packs/MicrosoftTeams/.pack-ignore
  Packs/MicrosoftTeams/Integrations/MicrosoftTeams/MicrosoftTeams.yml
  Packs/MicrosoftTeams/ReleaseNotes/1_1_15.md
  Packs/MicrosoftTeams/pack_metadata.json
Labels: docs-approved

#13941 Un-skip `Gmail Single User`
  Tests/conf.json
Labels: docs-approved

#14083 Zscaler - skip TPB
  Tests/conf.json
Labels: docs-approved

#14031 Expanse v2 mirroring improvements
  Packs/ExpanseV2/Integrations/ExpanseV2/ExpanseV2.py
  Packs/ExpanseV2/Integrations/ExpanseV2/ExpanseV2.yml
  Packs/ExpanseV2/Integrations/ExpanseV2/ExpanseV2_test.py
  Packs/ExpanseV2/Integrations/ExpanseV2/test_data/get_remote_data_updated_entries_incident_closure.json
  Packs/ExpanseV2/Integrations/ExpanseV2/test_data/get_remote_data_updated_entries_incident_reopening.json
  Packs/ExpanseV2/ReleaseNotes/1_8_0.md
  Packs/ExpanseV2/pack_metadata.json
Labels: docs-approved, release-notes-only

#14068 Update README.md
  Packs/Logzio/.secrets-ignore
  Packs/Logzio/README.md
Labels: Contribution, docs-approved, Partner, Contribution Form Filled

#13854 Carbon black EDR fix endpoint isArray
  Packs/Carbon_Black_Enterprise_Response/.secrets-ignore
  Packs/Carbon_Black_Enterprise_Response/Integrations/CarbonBlackResponseV2/CarbonBlackResponseV2.py
  Packs/Carbon_Black_Enterprise_Response/Integrations/CarbonBlackResponseV2/CarbonBlackResponseV2.yml
  Packs/Carbon_Black_Enterprise_Response/ReleaseNotes/2_1_2.md
  Packs/Carbon_Black_Enterprise_Response/TestPlaybooks/CarbonBlackEdr_Test.yml
  Packs/Carbon_Black_Enterprise_Response/pack_metadata.json
Labels: docs-approved

#14023 Changes API call for incident for recursive fetch from Gurucul
  Packs/Gurucul/Integrations/GuruculGRA/GuruculGRA.py
  Packs/Gurucul/Integrations/GuruculGRA/GuruculGRA.yml
  Packs/Gurucul/ReleaseNotes/1_1_2.md
  Packs/Gurucul/pack_metadata.json
Labels: Contribution, docs-approved, Partner, Contribution Form Filled

#14081 netutils - Update dockers
  Packs/CommonScripts/ReleaseNotes/1_4_20.md
  Packs/CommonScripts/Scripts/IPv4Blacklist/IPv4Blacklist.yml
  Packs/CommonScripts/Scripts/IPv4Whitelist/IPv4Whitelist.yml
  Packs/CommonScripts/Scripts/IsInCidrRanges/IsInCidrRanges.yml
  Packs/CommonScripts/Scripts/IsNotInCidrRanges/IsNotInCidrRanges.yml
  Packs/CommonScripts/pack_metadata.json
Labels: docs-approved, release-notes-only

#14089 Mcafee tie file fix
  Packs/McAfee-TIE/Integrations/McAfee-TIE/McAfee-TIE.py
  Packs/McAfee-TIE/Integrations/McAfee-TIE/McAfee-TIE.yml
  Packs/McAfee-TIE/ReleaseNotes/1_0_1.md
  Packs/McAfee-TIE/TestPlaybooks/playbook-McAfee-TIE_Test.yml
  Packs/McAfee-TIE/pack_metadata.json
Labels: docs-approved

#14082 [Contribution Fix] Added headers to tableToHTML func
  Packs/CommonScripts/ReleaseNotes/1_4_20.md
  Packs/CommonScripts/ReleaseNotes/1_4_21.md
  Packs/CommonScripts/Scripts/script-ConvertTableToHTML.yml
  Packs/CommonScripts/pack_metadata.json
Labels: docs-approved

#14122 fixing pack image size - cortex 911
  Packs/Cortex911/Author_image.png
Labels: docs-approved

#14132 Fixing description file name and demisto appearances
  Packs/AWS-AccessAnalyzer/Integrations/AWS-AccessAnalyzer/AWS-AccessAnalyzer_description.md
  Packs/AWS-AccessAnalyzer/ReleaseNotes/1_0_5.md
  Packs/AWS-AccessAnalyzer/pack_metadata.json
  Packs/AWS-Athena/Integrations/AWS-Athena/AWS-Athena_description.md
  Packs/AWS-Athena/ReleaseNotes/1_0_4.md
  Packs/AWS-Athena/pack_metadata.json
  Packs/DeprecatedContent/Integrations/PaloAltoNetworksCortex/PaloAltoNetworksCortex_description.md
  Packs/DeprecatedContent/ReleaseNotes/1_6_13.md
  Packs/DeprecatedContent/pack_metadata.json
Labels: docs-approved

#14052 Fixing context readmes - extra spaces, tabs and formatting
  Packs/AWS-IAM/Integrations/AWS-IAM/AWS-IAM.yml
  Packs/AWS-IAM/Integrations/AWS-IAM/README.md
  Packs/AWS-IAM/ReleaseNotes/1_1_1.md
  Packs/AWS-IAM/pack_metadata.json
  Packs/AWS-Lambda/Integrations/AWS-Lambda/AWS-Lambda.yml
  Packs/AWS-Lambda/Integrations/AWS-Lambda/README.md
  Packs/AWS-Lambda/ReleaseNotes/1_2_2.md
  Packs/AWS-Lambda/pack_metadata.json
  Packs/CiscoStealthwatch/Integrations/CiscoStealthwatch/CiscoStealthwatch.py
  Packs/CiscoStealthwatch/Integrations/CiscoStealthwatch/CiscoStealthwatch.yml
  Packs/CiscoStealthwatch/Integrations/CiscoStealthwatch/CiscoStealthwatch_description.md
  Packs/CiscoStealthwatch/Integrations/CiscoStealthwatch/CiscoStealthwatch_image.png
  Packs/CiscoStealthwatch/Integrations/CiscoStealthwatch/CiscoStealthwatch_test.py
  Packs/CiscoStealthwatch/Integrations/CiscoStealthwatch/README.md
  Packs/CiscoStealthwatch/ReleaseNotes/1_0_2.md
  Packs/CiscoStealthwatch/pack_metadata.json
  Packs/CrowdStrikeFalconX/Integrations/CrowdStrikeFalconX/CrowdStrikeFalconX.yml
  Packs/CrowdStrikeFalconX/Integrations/CrowdStrikeFalconX/README.md
  Packs/CrowdStrikeFalconX/ReleaseNotes/1_1_4.md
  Packs/CrowdStrikeFalconX/pack_metadata.json
  Packs/EWS/Integrations/EWSO365/README.md
  Packs/GoogleChronicleBackstory/Integrations/GoogleChronicleBackstory/README.md
  Packs/Infinipoint/Integrations/Infinipoint/Infinipoint.yml
  Packs/Infinipoint/Integrations/Infinipoint/README.md
  Packs/Infinipoint/ReleaseNotes/1_0_7.md
  Packs/Infinipoint/pack_metadata.json
  Packs/Smokescreen_IllusionBLACK/Integrations/Smokescreen_IllusionBLACK/README.md
  Packs/Smokescreen_IllusionBLACK/Integrations/Smokescreen_IllusionBLACK/Smokescreen_IllusionBLACK.yml
  Packs/Smokescreen_IllusionBLACK/ReleaseNotes/1_0_9.md
  Packs/Smokescreen_IllusionBLACK/pack_metadata.json
Labels: docs-approved, release-notes-only

#14137 Changed contribution team
  Utils/github_workflow_scripts/handle_external_pr.py
Labels: docs-approved

#14117 Added link to new Prisma Cloud article in the pack's readme
  Packs/PrismaCloud/README.md
Labels: docs-approved

#14062 Added a link in the campaign pack readme to the article
  Packs/Campaign/README.md
Labels: docs-approved

#14057 update docker images of ML scripts
  Packs/Base/ReleaseNotes/1_13_15.md
  Packs/Base/Scripts/DBotFindSimilarIncidents/DBotFindSimilarIncidents.yml
  Packs/Base/Scripts/DBotFindSimilarIncidentsByIndicators/DBotFindSimilarIncidentsByIndicators.yml
  Packs/Base/pack_metadata.json
  Packs/ML/ReleaseNotes/1_3_2.md
  Packs/ML/Scripts/DBotPredictIncidentsBatch/DBotPredictIncidentsBatch.yml
  Packs/ML/Scripts/EvaluateMLModllAtProduction/EvaluateMLModllAtProduction.yml
  Packs/ML/pack_metadata.json
Labels: docs-approved

#14087 Redlock add firsttimefetch
  Packs/PrismaCloud/Integrations/RedLock/README.md
  Packs/PrismaCloud/Integrations/RedLock/RedLock.py
  Packs/PrismaCloud/Integrations/RedLock/RedLock.yml
  Packs/PrismaCloud/Integrations/RedLock/RedLock_test.py
  Packs/PrismaCloud/ReleaseNotes/1_8_1.md
  Packs/PrismaCloud/pack_metadata.json
Labels: bug, docs-approved

#14075 Add gke runner tag for non-dind related jobs
  .gitlab/ci/bucket-upload.yml
  .gitlab/ci/global.yml
  .gitlab/ci/instance-test.yml
  .gitlab/ci/on-push.yml
  .gitlab/ci/sdk-nightly.yml
  .gitlab/ci/slack-notify.yml
Labels: docs-approved

#14133 Phishing Investigation - Generic v2 to use updated Search And Delete - Generic v2
  Packs/Phishing/Playbooks/Phishing_Investigation_-_Generic_v2_-_6_0.yml
  Packs/Phishing/ReleaseNotes/2_3_1.md
  Packs/Phishing/pack_metadata.json
Labels: docs-approved

#14120 Mitre attack dashboard
  Packs/FeedMitreAttack/Dashboards/MITRE_ATT&CK.json
  Packs/FeedMitreAttack/ReleaseNotes/1_1_14.md
  Packs/FeedMitreAttack/Scripts/MITREIndicatorsByOpenIncidents/MITREIndicatorsByOpenIncidents.py
  Packs/FeedMitreAttack/Scripts/MITREIndicatorsByOpenIncidents/MITREIndicatorsByOpenIncidents.yml
  Packs/FeedMitreAttack/pack_metadata.json
  Packs/FeedMitreAttackv2/Dashboards/MITRE_ATT&CK_v2.json
  Packs/FeedMitreAttackv2/ReleaseNotes/1_0_4.md
  Packs/FeedMitreAttackv2/Scripts/MITREIndicatorsByOpenIncidentsv2/MITREIndicatorsByOpenIncidentsv2.py
  Packs/FeedMitreAttackv2/Scripts/MITREIndicatorsByOpenIncidentsv2/MITREIndicatorsByOpenIncidentsv2.yml
  Packs/FeedMitreAttackv2/pack_metadata.json
Labels: docs-approved

#14143 Carbon Black- change parameters transfer.
  Packs/Carbon_Black_Enterprise_Response/Integrations/CarbonBlackResponseV2/CarbonBlackResponseV2.py
  Packs/Carbon_Black_Enterprise_Response/ReleaseNotes/2_1_3.md
  Packs/Carbon_Black_Enterprise_Response/pack_metadata.json
Labels: docs-approved

#14168 Zscaler Test - skip
  Tests/conf.json
Labels: docs-approved

#14142 sane pdf reports content release
  Packs/Base/ReleaseNotes/1_13_16.md
  Packs/Base/Scripts/SanePdfReport/SanePdfReport.yml
  Packs/Base/pack_metadata.json
Labels: docs-approved, release-notes-only

#14092 Fix bugs scripts
  Packs/Base/ReleaseNotes/1_13_17.md
  Packs/Base/Scripts/DBotFindSimilarIncidents/DBotFindSimilarIncidents.py
  Packs/Base/Scripts/DBotFindSimilarIncidentsByIndicators/DBotFindSimilarIncidentsByIndicators.py
  Packs/Base/Scripts/DBotTrainClustering/DBotTrainClustering.py
  Packs/Base/pack_metadata.json
Labels: docs-approved

#13956 Add CIDR to URL Indicator
  Packs/Base/.secrets-ignore
  Packs/Base/TestPlaybooks/playbook-reputation.json-Test.yml
  Packs/CommonTypes/IndicatorTypes/reputation-url.json
  Packs/CommonTypes/ReleaseNotes/3_1_11.md
  Packs/CommonTypes/pack_metadata.json
  Packs/NonSupported/IndicatorTypes/reputation-url_5_4_9.json
Labels: bug, docs-approved, release-notes-only

#14167 1.4.7 sdk release
  dev-requirements-py3.txt
Labels: docs-approved

#14064 [AWS Feed] Add Regions
  Packs/FeedAWS/Integrations/FeedAWS/FeedAWS.yml
  Packs/FeedAWS/ReleaseNotes/1_1_5.md
  Packs/FeedAWS/pack_metadata.json
Labels: docs-approved, release-notes-only

#14066 [QRadar v2] Improve Handling for Empty Fetch Windows
  Packs/QRadar/Integrations/QRadar_v2/QRadar_v2.py
  Packs/QRadar/ReleaseNotes/2_0_20.md
  Packs/QRadar/pack_metadata.json
Labels: docs-approved

#14136 Microsoft Teams improvements
  Packs/MicrosoftTeams/Integrations/MicrosoftTeams/MicrosoftTeams.py
  Packs/MicrosoftTeams/Integrations/MicrosoftTeams/MicrosoftTeams.yml
  Packs/MicrosoftTeams/Integrations/MicrosoftTeams/MicrosoftTeams_description.md
  Packs/MicrosoftTeams/Integrations/MicrosoftTeams/README.md
  Packs/MicrosoftTeams/ReleaseNotes/1_1_16.md
  Packs/MicrosoftTeams/pack_metadata.json
Labels: Contribution, docs-approved

#14174 removed the gke tag from run-validations job
  .gitlab/ci/global.yml
Labels: docs-approved

#13911 adding http prefix to proxy when missing
  Packs/Base/ReleaseNotes/1_13_12.md
  Packs/Base/ReleaseNotes/1_13_15.md
  Packs/Base/ReleaseNotes/1_13_16.md
  Packs/Base/ReleaseNotes/1_13_18.md
  Packs/Base/Scripts/CommonServerPython/CommonServerPython.py
  Packs/Base/Scripts/CommonServerPython/CommonServerPython_test.py
  Packs/Base/pack_metadata.json
Labels: bug, docs-approved, release-notes-only

#14145 Updated Microsoft integration display names
  Packs/CommonScripts/Scripts/script-EmailAskUser_README.md
  Packs/CrisisManagement/Playbooks/Employee_Status_Survey_README.md
  Packs/MicrosoftGraphApplications/Integrations/MicrosoftGraphApplications/MicrosoftGraphApplications.yml
  Packs/MicrosoftGraphApplications/Integrations/MicrosoftGraphApplications/README.md
  Packs/MicrosoftGraphApplications/README.md
  Packs/MicrosoftGraphApplications/ReleaseNotes/1_0_5.md
  Packs/MicrosoftGraphApplications/pack_metadata.json
  Packs/MicrosoftGraphCalendar/Integrations/MicrosoftGraphCalendar/MicrosoftGraphCalendar.yml
  Packs/MicrosoftGraphCalendar/Integrations/MicrosoftGraphCalendar/MicrosoftGraphCalendar_description.md
  Packs/MicrosoftGraphCalendar/Integrations/MicrosoftGraphCalendar/README.md
  Packs/MicrosoftGraphCalendar/ReleaseNotes/1_0_9.md
  Packs/MicrosoftGraphCalendar/pack_metadata.json
  Packs/MicrosoftGraphDeviceManagement/Integrations/MicrosoftGraphDeviceManagement/MicrosoftGraphDeviceManagement.yml
  Packs/MicrosoftGraphDeviceManagement/Integrations/MicrosoftGraphDeviceManagement/MicrosoftGraphDeviceManagement_description.md
  Packs/MicrosoftGraphDeviceManagement/Integrations/MicrosoftGraphDeviceManagement/README.md
  Packs/MicrosoftGraphDeviceManagement/ReleaseNotes/1_0_10.md
  Packs/MicrosoftGraphDeviceManagement/pack_metadata.json
  Packs/MicrosoftGraphFiles/Integrations/MicrosoftGraphFiles/MicrosoftGraphFiles.yml
  Packs/MicrosoftGraphFiles/Integrations/MicrosoftGraphFiles/MicrosoftGraphFiles_description.md
  Packs/MicrosoftGraphFiles/Integrations/MicrosoftGraphFiles/README.md
  Packs/MicrosoftGraphFiles/ReleaseNotes/1_0_9.md
  Packs/MicrosoftGraphFiles/pack_metadata.json
  Packs/MicrosoftGraphGroups/Integrations/MicrosoftGraphGroups/MicrosoftGraphGroups.yml
  Packs/MicrosoftGraphGroups/Integrations/MicrosoftGraphGroups/MicrosoftGraphGroups_description.md
  Packs/MicrosoftGraphGroups/Integrations/MicrosoftGraphGroups/README.md
  Packs/MicrosoftGraphGroups/ReleaseNotes/1_0_9.md
  Packs/MicrosoftGraphGroups/pack_metadata.json
  Packs/MicrosoftGraphIdentityandAccess/Integrations/MicrosoftGraphIdentityandAccess/MicrosoftGraphIdentityandAccess.yml
  Packs/MicrosoftGraphIdentityandAccess/Integrations/MicrosoftGraphIdentityandAccess/README.md
  Packs/MicrosoftGraphIdentityandAccess/README.md
  Packs/MicrosoftGraphIdentityandAccess/ReleaseNotes/1_0_5.md
  Packs/MicrosoftGraphIdentityandAccess/pack_metadata.json
  Packs/MicrosoftGraphListener/Integrations/MicrosoftGraphListener/MicrosoftGraphListener.yml
  Packs/MicrosoftGraphListener/Integrations/MicrosoftGraphListener/MicrosoftGraphListener_description.md
  Packs/MicrosoftGraphListener/Integrations/MicrosoftGraphListener/README.md
  Packs/MicrosoftGraphListener/ReleaseNotes/1_0_19.md
  Packs/MicrosoftGraphListener/pack_metadata.json
  Packs/MicrosoftGraphMail/Integrations/MicrosoftGraphMail/MicrosoftGraphMail.yml
  Packs/MicrosoftGraphMail/Integrations/MicrosoftGraphMail/MicrosoftGraphMail_description.md
  Packs/MicrosoftGraphMail/Integrations/MicrosoftGraphMail/README.md
  Packs/MicrosoftGraphMail/README.md
  Packs/MicrosoftGraphMail/ReleaseNotes/1_0_22.md
  Packs/MicrosoftGraphMail/pack_metadata.json
  Packs/MicrosoftGraphSecurity/Integrations/MicrosoftGraphSecurity/MicrosoftGraphSecurity.yml
  Packs/MicrosoftGraphSecurity/Integrations/MicrosoftGraphSecurity/README.md
  Packs/MicrosoftGraphSecurity/ReleaseNotes/2_0_11.md
  Packs/MicrosoftGraphSecurity/pack_metadata.json
  Packs/MicrosoftGraphUser/Integrations/MicrosoftGraphUser/MicrosoftGraphUser.yml
  Packs/MicrosoftGraphUser/Integrations/MicrosoftGraphUser/MicrosoftGraphUser_description.md
  Packs/MicrosoftGraphUser/Integrations/MicrosoftGraphUser/README.md
  Packs/MicrosoftGraphUser/ReleaseNotes/1_3_11.md
  Packs/MicrosoftGraphUser/pack_metadata.json
Labels: docs-approved

#14171 Splunk - handle commas in raw event values
  Packs/SplunkPy/Integrations/SplunkPy/SplunkPy.py
  Packs/SplunkPy/Integrations/SplunkPy/SplunkPy_test.py
  Packs/SplunkPy/ReleaseNotes/2_1_9.md
  Packs/SplunkPy/pack_metadata.json
Labels: bug, docs-approved, release-notes-only

#14296 new-contrib-team
  Utils/github_workflow_scripts/handle_external_pr.py
Labels: docs-approved

#13744 Content mgmt update
  Packs/ContentManagement/Playbooks/playbook-Configuration_Setup.yml
  Packs/ContentManagement/ReleaseNotes/1_0_2.md
  Packs/ContentManagement/Scripts/ConfigurationSetup/ConfigurationSetup.py
  Packs/ContentManagement/Scripts/ConfigurationSetup/ConfigurationSetup.yml
  Packs/ContentManagement/Scripts/CustomPackInstaller/CustomPackInstaller.py
  Packs/ContentManagement/Scripts/CustomPackInstaller/CustomPackInstaller.yml
  Packs/ContentManagement/Scripts/JobCreator/JobCreator.py
  Packs/ContentManagement/Scripts/JobCreator/JobCreator.yml
  Packs/ContentManagement/Scripts/MarketplacePackInstaller/MarketplacePackInstaller.py
  Packs/ContentManagement/Scripts/MarketplacePackInstaller/MarketplacePackInstaller.yml
  Packs/ContentManagement/docs-files/ci-cd.yml
  Packs/ContentManagement/pack_metadata.json
Labels: docs-approved

#14170 expose gh base url
  Packs/GitHub/Integrations/GitHub/GitHub.py
  Packs/GitHub/Integrations/GitHub/GitHub.yml
  Packs/GitHub/Integrations/GitHub/GitHub_test.py
  Packs/GitHub/ReleaseNotes/1_3_6.md
  Packs/GitHub/pack_metadata.json
Labels: docs-approved

#13889 Add `aws-iam-list-role-policies` command to AWS IAM
  Packs/AWS-IAM/Integrations/AWS-IAM/AWS-IAM.py
  Packs/AWS-IAM/Integrations/AWS-IAM/AWS-IAM.yml
  Packs/AWS-IAM/Integrations/AWS-IAM/README.md
  Packs/AWS-IAM/ReleaseNotes/1_1_2.md
  Packs/AWS-IAM/TestPlaybooks/playbook-AWS-IAM-Test.yml
  Packs/AWS-IAM/pack_metadata.json
  Tests/conf.json
Labels: docs-approved

#14070 Palo Alto Networks PAN-OS- Fixed an issue where the creation of URL Filtering object was not successful in 8.X PAN-OS versions
  Packs/PAN-OS/Integrations/Panorama/Panorama.py
  Packs/PAN-OS/Integrations/Panorama/Panorama_test.py
  Packs/PAN-OS/Playbooks/playbook-PAN-OS_-_Create_Or_Edit_Rule.yml
  Packs/PAN-OS/ReleaseNotes/1_6_24.md
  Packs/PAN-OS/TestPlaybooks/playbook-palo_alto_firewall_test_pb.yml
  Packs/PAN-OS/pack_metadata.json
  Tests/conf.json
Labels: bug, docs-approved

#13940 Support "noUpdate" signal in Feeds
  Packs/ApiModules/ReleaseNotes/2_2_2.md
  Packs/ApiModules/Scripts/HTTPFeedApiModule/HTTPFeedApiModule.py
  Packs/ApiModules/Scripts/HTTPFeedApiModule/HTTPFeedApiModule.yml
  Packs/ApiModules/Scripts/HTTPFeedApiModule/HTTPFeedApiModule_test.py
  Packs/ApiModules/Scripts/JSONFeedApiModule/JSONFeedApiModule.py
  Packs/ApiModules/Scripts/JSONFeedApiModule/JSONFeedApiModule_test.py
  Packs/ApiModules/pack_metadata.json
  Packs/FeedAWS/ReleaseNotes/1_1_6.md
  Packs/FeedAWS/pack_metadata.json
  Packs/FeedBlocklist_de/ReleaseNotes/1_1_5.md
  Packs/FeedBlocklist_de/pack_metadata.json
  Packs/FeedBruteForceBlocker/ReleaseNotes/1_1_5.md
  Packs/FeedBruteForceBlocker/pack_metadata.json
  Packs/FeedCloudflare/ReleaseNotes/1_1_5.md
  Packs/FeedCloudflare/pack_metadata.json
  Packs/FeedDShield/ReleaseNotes/1_1_5.md
  Packs/FeedDShield/pack_metadata.json
  Packs/FeedFastly/ReleaseNotes/1_1_5.md
  Packs/FeedFastly/pack_metadata.json
  Packs/FeedFeodoTracker/ReleaseNotes/1_1_6.md
  Packs/FeedFeodoTracker/pack_metadata.json
  Packs/FeedIntel471/ReleaseNotes/2_0_2.md
  Packs/FeedIntel471/pack_metadata.json
  Packs/FeedJSON/ReleaseNotes/1_1_5.md
  Packs/FeedJSON/pack_metadata.json
  Packs/FeedMalwareDomainList/ReleaseNotes/1_1_3.md
  Packs/FeedMalwareDomainList/pack_metadata.json
  Packs/FeedPlainText/ReleaseNotes/1_1_3.md
  Packs/FeedPlainText/pack_metadata.json
  Packs/FeedSpamhaus/ReleaseNotes/1_1_5.md
  Packs/FeedSpamhaus/pack_metadata.json
  Packs/iDefense/ReleaseNotes/3_0_9.md
  Packs/iDefense/pack_metadata.json
  Tests/demistomock/demistomock.py
Labels: docs-approved, release-notes-only

#14299 LogRhythm - handle number_of_days arg
  Packs/LogRhythmRest/Integrations/LogRhythmRest/LogRhythmRest.py
  Packs/LogRhythmRest/ReleaseNotes/1_0_6.md
  Packs/LogRhythmRest/pack_metadata.json
Labels: bug, docs-approved

#14038 Update README.md
  Packs/Indeni/.secrets-ignore
  Packs/Indeni/README.md
Labels: Contribution, docs-approved

#14119 BaseClient _http_req: `response` resp_type, assign res to DemistoException
  Packs/Base/ReleaseNotes/1_13_19.md
  Packs/Base/Scripts/CommonServerPython/CommonServerPython.py
  Packs/Base/Scripts/CommonServerPython/CommonServerPython_test.py
  Packs/Base/pack_metadata.json
Labels: docs-approved, release-notes-only

#13643 Google drive enhancement permissions
  Packs/ApiModules/Scripts/GSuiteApiModule/GSuiteApiModule.py
  Packs/GoogleDrive/Integrations/GoogleDrive/.pylintrc
  Packs/GoogleDrive/Integrations/GoogleDrive/GoogleDrive.py
  Packs/GoogleDrive/Integrations/GoogleDrive/GoogleDrive.yml
  Packs/GoogleDrive/Integrations/GoogleDrive/GoogleDrive_test.py
  Packs/GoogleDrive/Integrations/GoogleDrive/Pipfile
  Packs/GoogleDrive/Integrations/GoogleDrive/Pipfile.lock
  Packs/GoogleDrive/Integrations/GoogleDrive/README.md
  Packs/GoogleDrive/Integrations/GoogleDrive/test_data/drive_get_response.json
  Packs/GoogleDrive/Integrations/GoogleDrive/test_data/drives_list_response.json
  Packs/GoogleDrive/Integrations/GoogleDrive/test_data/file_get_response.json
  Packs/GoogleDrive/Integrations/GoogleDrive/test_data/file_permission_create_response.json
  Packs/GoogleDrive/Integrations/GoogleDrive/test_data/file_permission_list_response.json
  Packs/GoogleDrive/Integrations/GoogleDrive/test_data/files_list_response.json
  Packs/GoogleDrive/ReleaseNotes/1_1_0.md
  Packs/GoogleDrive/TestPlaybooks/playbook-GoogleDrive-Permissions-Test.yml
  Packs/GoogleDrive/pack_metadata.json
Labels: docs-approved

#14297 Devo - add port param and improve writer json creds param doc
  Packs/Devo/Integrations/Devo_v2/Devo_v2.py
  Packs/Devo/Integrations/Devo_v2/Devo_v2.yml
  Packs/Devo/Integrations/Devo_v2/README.md
  Packs/Devo/ReleaseNotes/1_1_3.md
  Packs/Devo/pack_metadata.json
Labels: docs-approved

#12044 Anomali threat stream v2 - Added Reliability
  Packs/Anomali_ThreatStream/Integrations/Anomali_ThreatStream_v2/Anomali_ThreatStream_v2.py
  Packs/Anomali_ThreatStream/Integrations/Anomali_ThreatStream_v2/Anomali_ThreatStream_v2.yml
  Packs/Anomali_ThreatStream/Integrations/Anomali_ThreatStream_v2/Anomali_ThreatStream_v2_test.py
  Packs/Anomali_ThreatStream/Integrations/Anomali_ThreatStream_v2/README.md
  Packs/Anomali_ThreatStream/Integrations/Anomali_ThreatStream_v2/test_data/file_256_context.json
  Packs/Anomali_ThreatStream/Integrations/Anomali_ThreatStream_v2/test_data/file_512_context.json
  Packs/Anomali_ThreatStream/ReleaseNotes/1_1_2.md
  Packs/Anomali_ThreatStream/pack_metadata.json
Labels: docs-approved

#14308 SecurityAndCompliance: o365-sc-list-search bug fix
  Packs/EWS/Integrations/SecurityAndCompliance/README.md
  Packs/EWS/Integrations/SecurityAndCompliance/SecurityAndCompliance.ps1
  Packs/EWS/ReleaseNotes/1_9_1.md
  Packs/EWS/pack_metadata.json
Labels: docs-approved

#14041 skipped problematic McAfee ESM tests
  Packs/McAfee_ESM/TestPlaybooks/McAfee_ESM_Watchlists_-_Test_v10.2.0.yml
  Packs/McAfee_ESM/TestPlaybooks/McAfee_ESM_Watchlists_-_Test_v10.3.0.yml
  Packs/McAfee_ESM/TestPlaybooks/McAfee_ESM_Watchlists_-_Test_v11.1.3.yml
  Packs/McAfee_ESM/TestPlaybooks/McAfee_ESM_v2_-_Test.yml
  Packs/McAfee_ESM/TestPlaybooks/McAfee_ESM_v2_-_Test_v11.1.3.yml
  Tests/conf.json
Labels: docs-approved

#14309 Update Microsoft READMEs
  Packs/MicrosoftGraphIdentityandAccess/Integrations/MicrosoftGraphIdentityandAccess/README.md
  Packs/MicrosoftGraphUser/Integrations/MicrosoftGraphUser/README.md
Labels: docs-approved

#14316 Upload-Flow - fix verification statement
  Tests/Marketplace/copy_and_upload_packs.py
Labels: docs-approved

#14325 Prisma Cloud (RedLock) - Improved logging in case of an error.
  Packs/PrismaCloud/Integrations/RedLock/RedLock.py
  Packs/PrismaCloud/Integrations/RedLock/RedLock.yml
  Packs/PrismaCloud/ReleaseNotes/1_8_2.md
  Packs/PrismaCloud/pack_metadata.json
Labels: docs-approved

#13708 Hash incident fields test remove from skip
  Packs/ML/ReleaseNotes/1_3_3.md
  Packs/ML/Scripts/HashIncidentsFields/HashIncidentsFields.py
  Packs/ML/Scripts/HashIncidentsFields/HashIncidentsFields.yml
  Packs/ML/TestPlaybooks/script-CreateIncidentsForEvaluateMLModllAtProduction.yml
  Packs/ML/pack_metadata.json
  Tests/conf.json
Labels: docs-approved, release-notes-only

#14294 QRadar IPs commands enhancement
  Packs/QRadar/.secrets-ignore
  Packs/QRadar/Integrations/QRadar_v3/QRadar_v3.py
  Packs/QRadar/Integrations/QRadar_v3/QRadar_v3.yml
  Packs/QRadar/Integrations/QRadar_v3/QRadar_v3_test.py
  Packs/QRadar/Integrations/QRadar_v3/README.md
  Packs/QRadar/Integrations/QRadar_v3/command_examples.txt
  Packs/QRadar/Integrations/QRadar_v3/test_data/ips_commands_data.json
  Packs/QRadar/ReleaseNotes/2_0_21.md
  Packs/QRadar/TestPlaybooks/QRadar_v3-test.yml
  Packs/QRadar/pack_metadata.json
Labels: docs-approved, release-notes-only

#14329 New photo for the NIST pack README
  Packs/NIST/README.md
  Packs/NIST/doc_files/NIST_-_Handling_an_Incident_Template_2.png
Labels: docs-approved

#14326 add searchIndicators docs in demistomock
  Tests/demistomock/demistomock.py
Labels: docs-approved

#14342 Extract attack pattern fix
  Packs/CommonScripts/ReleaseNotes/1_4_22.md
  Packs/CommonScripts/Scripts/ExtractAttackPattern/ExtractAttackPattern.py
  Packs/CommonScripts/Scripts/ExtractAttackPattern/ExtractAttackPattern_test.py
  Packs/CommonScripts/pack_metadata.json
Labels: docs-approved

#13763 XDR iocs bug
  Packs/CortexXDR/Integrations/XDR_iocs/XDR_iocs.py
  Packs/CortexXDR/Integrations/XDR_iocs/XDR_iocs_test.py
  Packs/CortexXDR/Integrations/XDR_iocs/test_data/Domain_sync_file.txt
  Packs/CortexXDR/Integrations/XDR_iocs/test_data/File_sync_file.txt
  Packs/CortexXDR/Integrations/XDR_iocs/test_data/IP_iocs.json
  Packs/CortexXDR/Integrations/XDR_iocs/test_data/IP_iocs_to_keep_file.txt
  Packs/CortexXDR/Integrations/XDR_iocs/test_data/IP_sync_file.txt
  Packs/CortexXDR/ReleaseNotes/3_0_23.md
  Packs/CortexXDR/pack_metadata.json
Labels: bug, docs-approved, release-notes-only

#14343 Deprecate malware domain
  Packs/FeedMalwareDomainList/Integrations/FeedMalwareDomainList/FeedMalwareDomainList.yml
  Packs/FeedMalwareDomainList/ReleaseNotes/1_1_4.md
  Packs/FeedMalwareDomainList/pack_metadata.json
Labels: docs-approved, release-notes-only

#14328 Microsoft Teams - add setup video
  Packs/MicrosoftTeams/Integrations/MicrosoftTeams/README.md
Labels: docs-approved

#14310 [Bug] CrowdStrike Falcon - we are not passing incident type to the classifier into raw json
  Packs/CrowdStrikeFalcon/Classifiers/classifier-CrowdStrike_Falcon_Incident_Classifier.json
  Packs/CrowdStrikeFalcon/Integrations/CrowdStrikeFalcon/CrowdStrikeFalcon.py
  Packs/CrowdStrikeFalcon/Integrations/CrowdStrikeFalcon/CrowdStrikeFalcon_test.py
  Packs/CrowdStrikeFalcon/ReleaseNotes/1_2_20.md
  Packs/CrowdStrikeFalcon/pack_metadata.json
Labels: docs-approved, release-notes-only

#14140 XSOAR RF 2.2 release
  Packs/RecordedFuture/.secrets-ignore
  Packs/RecordedFuture/Integrations/RecordedFuture/Pipfile
  Packs/RecordedFuture/Integrations/RecordedFuture/Pipfile.lock
  Packs/RecordedFuture/Integrations/RecordedFuture/README.md
  Packs/RecordedFuture/Integrations/RecordedFuture/RecordedFuture.py
  Packs/RecordedFuture/Integrations/RecordedFuture/RecordedFuture.yml
  Packs/RecordedFuture/Integrations/RecordedFuture/RecordedFuture_test.py
  Packs/RecordedFuture/Integrations/RecordedFuture/cassettes/test_get_links_command
  Packs/RecordedFuture/Integrations/RecordedFuture/cassettes/test_intelligence
  Packs/RecordedFuture/Integrations/RecordedFuture/cassettes/test_intelligence_profile
  Packs/RecordedFuture/Playbooks/playbook-Recorded_Future_CVE_Intelligence.yml
  Packs/RecordedFuture/Playbooks/playbook-Recorded_Future_CVE_Reputation.yml
  Packs/RecordedFuture/Playbooks/playbook-Recorded_Future_Domain_Intelligence.yml
  Packs/RecordedFuture/Playbooks/playbook-Recorded_Future_Domain_Reputation.yml
  Packs/RecordedFuture/Playbooks/playbook-Recorded_Future_File_Intelligence.yml
  Packs/RecordedFuture/Playbooks/playbook-Recorded_Future_File_Reputation.yml
  Packs/RecordedFuture/Playbooks/playbook-Recorded_Future_IP_Intelligence.yml
  Packs/RecordedFuture/Playbooks/playbook-Recorded_Future_IP_Reputation.yml
  Packs/RecordedFuture/Playbooks/playbook-Recorded_Future_Threat_Assessment.yml
  Packs/RecordedFuture/Playbooks/playbook-Recorded_Future_URL_Intelligence.yml
  Packs/RecordedFuture/Playbooks/playbook-Recorded_Future_URL_Reputation.yml
  Packs/RecordedFuture/ReleaseNotes/2_2_0.md
  Packs/RecordedFuture/pack_metadata.json
Labels: Contribution, docs-approved, Partner, Contribution Form Filled

#14332 panorama-8-1-unskip
  Packs/PAN-OS/Integrations/Panorama/Panorama.py
  Packs/PAN-OS/ReleaseNotes/1_6_26.md
  Packs/PAN-OS/pack_metadata.json
  Tests/conf.json
Labels: docs-approved

#14344 added popularity ranks description + markdown formatting
  Packs/VirusTotal/Integrations/VirusTotalV3/README.md
Labels: docs-approved

#14348 bump to 21.8.1
  .circleci/content_release_vars.sh
Labels: docs-approved

#14349 MS Teams Video - replace blob with raw in video link
  Packs/MicrosoftTeams/Integrations/MicrosoftTeams/README.md
Labels: docs-approved

#13658 Created custom indicator and added tests
  Packs/Base/ReleaseNotes/1_13_20.md
  Packs/Base/Scripts/CommonServerPython/CommonServerPython.py
  Packs/Base/Scripts/CommonServerPython/CommonServerPython_test.py
  Packs/Base/pack_metadata.json
Labels: docs-approved

#13970 Atp - added new indicators commands
  Packs/ApiModules/Scripts/MicrosoftApiModule/MicrosoftApiModule.py
  Packs/MicrosoftDefenderAdvancedThreatProtection/.secrets-ignore
  Packs/MicrosoftDefenderAdvancedThreatProtection/Integrations/MicrosoftDefenderAdvancedThreatProtection/MicrosoftDefenderAdvancedThreatProtection.py
  Packs/MicrosoftDefenderAdvancedThreatProtection/Integrations/MicrosoftDefenderAdvancedThreatProtection/MicrosoftDefenderAdvancedThreatProtection.yml
  Packs/MicrosoftDefenderAdvancedThreatProtection/Integrations/MicrosoftDefenderAdvancedThreatProtection/README.md
  Packs/MicrosoftDefenderAdvancedThreatProtection/Integrations/MicrosoftDefenderAdvancedThreatProtection/examples.txt
  Packs/MicrosoftDefenderAdvancedThreatProtection/ReleaseNotes/1_3_0.md
  Packs/MicrosoftDefenderAdvancedThreatProtection/TestPlaybooks/playbook-Microsoft_ATP_indicators_SC_Test.yml
  Packs/MicrosoftDefenderAdvancedThreatProtection/pack_metadata.json
  Tests/conf.json
Labels: docs-approved

#14128 Checkpoint playbooks bug
  Packs/CheckpointFirewall/Playbooks/Checkpoint_-_Block_IP_-_Custom_Block_Rule.yml
  Packs/CheckpointFirewall/Playbooks/Checkpoint_-_Block_URL.yml
  Packs/CheckpointFirewall/Playbooks/Checkpoint_-_Publish&Install_configuration.yml
  Packs/CheckpointFirewall/ReleaseNotes/2_0_12.md
  Packs/CheckpointFirewall/pack_metadata.json
Labels: docs-approved

#14363 Update Readme.md
  Packs/Linkshadow/README.md
Labels: Contribution, docs-approved, Partner, Contribution Form Filled

#13735 IronPort get-report documentation
  Packs/IronPort/Integrations/command_examples.txt
  Packs/IronPort/Integrations/integration-IronPort.yml
  Packs/IronPort/Integrations/integration-IronPort_README.md
  Packs/IronPort/ReleaseNotes/1_0_1.md
  Packs/IronPort/pack_metadata.json
Labels: docs-approved

#14129 Trendmicro apex test
  Packs/TrendMicroApex/Integrations/TrendMicroApex/TrendMicroApex.py
  Packs/TrendMicroApex/Integrations/TrendMicroApex/TrendMicroApex.yml
  Packs/TrendMicroApex/ReleaseNotes/2_0_2.md
  Packs/TrendMicroApex/pack_metadata.json
Labels: docs-approved
