Repository demisto/content, pull requests merged in 2021-10, with the labels that each got.

#14984 Exclude protected branches
  Utils/github_workflow_scripts/delete_stale_non_contrib_branches.py
Labels: docs-approved

#15127 Only sync contrib base branch with master at night
  .github/workflows/sync-contribution-base-branch.yml
Labels: docs-approved

#14803 QRadar race conditions
  Packs/QRadar/Integrations/QRadar_v3/QRadar_v3.py
  Packs/QRadar/ReleaseNotes/2_0_27.md
  Packs/QRadar/pack_metadata.json
Labels: docs-approved, release-notes-only

#15134 Update handle_external_pr.py
  Utils/github_workflow_scripts/handle_external_pr.py
Labels: docs-approved

#15125 [Fix] TAXII Feed does not add tags
  Packs/FeedTAXII/Integrations/FeedTAXII/FeedTAXII.py
  Packs/FeedTAXII/Integrations/FeedTAXII/FeedTAXII_test.py
  Packs/FeedTAXII/ReleaseNotes/1_0_12.md
  Packs/FeedTAXII/pack_metadata.json
Labels: docs-approved

#15141 updated pack-ignore files
  Packs/GuardiCore/.pack-ignore
  Packs/SANS/.pack-ignore
Labels: docs-approved

#15109 XDR XQL documentation update
  Packs/CortexXDR/Integrations/XQLQueryingEngine/README.md
  Packs/CortexXDR/Integrations/XQLQueryingEngine/XQLQueryingEngine.yml
  Packs/CortexXDR/ReleaseNotes/4_1_3.md
  Packs/CortexXDR/pack_metadata.json
Labels: docs-approved

#15142 digital shadows - rename readme file
  Packs/DigitalShadows/Integrations/integration-DigitalShadows_README.md
Labels: bug, docs-approved

#14955 UrlScan: Update pack metadata and README
  Packs/UrlScan/Author_image.png
  Packs/UrlScan/README.md
  Packs/UrlScan/ReleaseNotes/1_1_12.md
  Packs/UrlScan/pack_metadata.json
Labels: Contribution, docs-approved, Partner, Contribution Form Filled

#15087 Update XDR readme with link
  Packs/CortexXDR/README.md
Labels: docs-approved

#15150 bump up SplunkPy to use demisto/splunksdk:1.0.0.24033
  Packs/SplunkPy/Integrations/SplunkPy/SplunkPy.yml
  Packs/SplunkPy/ReleaseNotes/2_2_1.md
  Packs/SplunkPy/pack_metadata.json
Labels: docs-approved

#15042 CSP dbot integration name-5.0.0
  Packs/Base/ReleaseNotes/1_13_36.md
  Packs/Base/Scripts/CommonServerPython/CommonServerPython.py
  Packs/Base/pack_metadata.json
Labels: bug, docs-approved, release-notes-only

#15154 threat vault unskip
  Tests/conf.json
Labels: docs-approved

#15147 Un skip Carbon Black Enterprise Protection V2 Test
  Tests/conf.json
Labels: docs-approved

#15131 Replaced Author_image to fit the 120x50 required size
  Packs/PingIdentity/Author_image.png
Labels: Contribution, docs-approved, Contribution Form Filled

#15133 [malwarebytes-254] fixes for !malwarebytes-list-endpoint-info command
  Packs/Malwarebytes/Integrations/Malwarebytes/Malwarebytes.py
  Packs/Malwarebytes/ReleaseNotes/1_1_3.md
  Packs/Malwarebytes/pack_metadata.json
Labels: Contribution, docs-approved, Partner, Contribution Form Filled

#15036 AzureAD auth docs & default Application ID
  Packs/AzureActiveDirectory/Integrations/AzureADIdentityProtection/AzureADIdentityProtection.yml
  Packs/AzureActiveDirectory/Integrations/AzureADIdentityProtection/AzureADIdentityProtection_description.md
  Packs/AzureActiveDirectory/Integrations/AzureADIdentityProtection/README.md
  Packs/AzureActiveDirectory/Integrations/AzureADIdentityProtection/example_commands
  Packs/AzureActiveDirectory/ReleaseNotes/1_1_1.md
  Packs/AzureActiveDirectory/pack_metadata.json
Labels: docs-approved

#15121 Add input to create service now ticket playbook
  Packs/ServiceNow/Playbooks/playbook-Create_ServiceNow_Ticket.yml
  Packs/ServiceNow/Playbooks/playbook-Create_ServiceNow_Ticket_README.md
  Packs/ServiceNow/ReleaseNotes/2_2_7.md
  Packs/ServiceNow/pack_metadata.json
Labels: docs-approved, release-notes-only

#15129 Improved Gmail parameters documentation
  Packs/Gmail/Integrations/Gmail/Gmail.yml
  Packs/Gmail/Integrations/Gmail/README.md
  Packs/Gmail/ReleaseNotes/1_1_9.md
  Packs/Gmail/pack_metadata.json
  Tests/conf.json
Labels: docs-approved

#14506 Azure sentinel update
  Packs/ApiModules/ReleaseNotes/2_2_4.md
  Packs/ApiModules/Scripts/MicrosoftApiModule/MicrosoftApiModule.py
  Packs/ApiModules/pack_metadata.json
  Packs/AzureSentinel/Integrations/AzureSentinel/AzureSentinel.py
  Packs/AzureSentinel/Integrations/AzureSentinel/AzureSentinel.yml
  Packs/AzureSentinel/Integrations/AzureSentinel/AzureSentinel_description.md
  Packs/AzureSentinel/Integrations/AzureSentinel/AzureSentinel_test.py
  Packs/AzureSentinel/Integrations/AzureSentinel/README.md
  Packs/AzureSentinel/Integrations/AzureSentinel/TestData/expected_alerts.json
  Packs/AzureSentinel/Integrations/AzureSentinel/TestData/expected_entities.json
  Packs/AzureSentinel/Integrations/AzureSentinel/TestData/expected_watchlist_items.json
  Packs/AzureSentinel/Integrations/AzureSentinel/TestData/expected_watchlists.json
  Packs/AzureSentinel/ReleaseNotes/1_1_0.md
  Packs/AzureSentinel/TestPlaybooks/TestAzureSentinelPlaybookV2.yml
  Packs/AzureSentinel/pack_metadata.json
  Tests/conf.json
Labels: docs-approved

#15118 Elasticsearch v2 - update Server URL description
  Packs/Elasticsearch/Integrations/Elasticsearch_v2/Elasticsearch_v2.yml
  Packs/Elasticsearch/Integrations/Elasticsearch_v2/README.md
  Packs/Elasticsearch/ReleaseNotes/1_1_8.md
  Packs/Elasticsearch/pack_metadata.json
Labels: docs-approved

#15122 Change Microsoft Graph User Terminate Command Description
  Packs/MicrosoftGraphUser/Integrations/MicrosoftGraphUser/MicrosoftGraphUser.yml
  Packs/MicrosoftGraphUser/Integrations/MicrosoftGraphUser/README.md
  Packs/MicrosoftGraphUser/ReleaseNotes/1_3_13.md
  Packs/MicrosoftGraphUser/pack_metadata.json
Labels: docs-approved

#15164 collect_tests: added missing import
  Tests/scripts/collect_tests_and_content_packs.py
Labels: docs-approved

#15166 Flashpoint - fix UT
  Packs/Flashpoint/Integrations/Flashpoint/Flashpoint_test.py
  Packs/Flashpoint/ReleaseNotes/1_2_1.md
  Packs/Flashpoint/pack_metadata.json
Labels: docs-approved

#14829 URLSSLVerification added an argument
  Packs/CommonScripts/ReleaseNotes/1_4_41.md
  Packs/CommonScripts/Scripts/URLSSLVerification/URLSSLVerification.py
  Packs/CommonScripts/Scripts/URLSSLVerification/URLSSLVerification.yml
  Packs/CommonScripts/Scripts/URLSSLVerification/URLSSLVerification_test.py
  Packs/CommonScripts/TestPlaybooks/playbook-URLSSLVerification_test.yml
  Packs/CommonScripts/pack_metadata.json
Labels: docs-approved

#15158 Remove "indicators query" from test modules
  Packs/EDL/Integrations/EDL/EDL.py
  Packs/EDL/ReleaseNotes/2_1_4.md
  Packs/EDL/pack_metadata.json
  Packs/ExportIndicators/Integrations/ExportIndicators/ExportIndicators.py
  Packs/ExportIndicators/ReleaseNotes/1_0_12.md
  Packs/ExportIndicators/pack_metadata.json
Labels: docs-approved

#15171 remove confusing command param from AzureSentinel
  Packs/AzureSentinel/Integrations/AzureSentinel/AzureSentinel.py
  Packs/AzureSentinel/Integrations/AzureSentinel/AzureSentinel.yml
Labels: docs-approved

#15175 add import
  Tests/scripts/collect_tests_and_content_packs.py
Labels: docs-approved

#15173 Infocye lint fix
  Packs/Infocyte/Integrations/Infocyte/Infocyte.Tests.ps1
  Packs/Infocyte/Integrations/Infocyte/Infocyte.ps1
  Packs/Infocyte/Integrations/Infocyte/Infocyte.yml
  Packs/Infocyte/ReleaseNotes/1_0_4.md
  Packs/Infocyte/pack_metadata.json
Labels: docs-approved

#15174 change sdk to release
  dev-requirements-py3.txt
Labels: docs-approved

#15012 Add fullstop and grammar fixes + pack metadata bumps
  Packs/XForceExchange/Integrations/XFE_v2/README.md
  Packs/XForceExchange/Integrations/XFE_v2/XFE_v2.yml
  Packs/XForceExchange/ReleaseNotes/1_1_9.md
  Packs/XForceExchange/pack_metadata.json
  Packs/jamf/Integrations/jamfV2/README.md
  Packs/jamf/Integrations/jamfV2/jamfV2.yml
  Packs/jamf/ReleaseNotes/2_0_2.md
  Packs/jamf/pack_metadata.json
  Packs/qualys/Integrations/Qualysv2/Qualysv2.yml
  Packs/qualys/Integrations/Qualysv2/README.md
  Packs/qualys/ReleaseNotes/1_0_11.md
  Packs/qualys/pack_metadata.json
Labels: enhancement, docs-approved

#15182 Reporter address typo
  Packs/Phishing/Playbooks/Phishing_Investigation_-_Generic_v2_-_6_0.yml
  Packs/Phishing/ReleaseNotes/2_4_4.md
  Packs/Phishing/pack_metadata.json
Labels: docs-approved, release-notes-only

#14987 Adding date fields param to tableToMarkdown
  Packs/Base/ReleaseNotes/1_13_37.md
  Packs/Base/Scripts/CommonServerPython/CommonServerPython.py
  Packs/Base/Scripts/CommonServerPython/CommonServerPython_test.py
  Packs/Base/pack_metadata.json
  Packs/Cisco-umbrella/Integrations/Cisco-umbrella-investigate/Cisco-umbrella-investigate.py
  Packs/Cisco-umbrella/ReleaseNotes/1_0_8.md
  Packs/Cisco-umbrella/pack_metadata.json
Labels: docs-approved

#15183 Fix kenna proxy
  Packs/Kenna/Integrations/KennaV2/KennaV2.py
  Packs/Kenna/ReleaseNotes/1_1_5.md
  Packs/Kenna/pack_metadata.json
Labels: bug, docs-approved, release-notes-only

#14899 Storage base path
  .circleci/config.yml
  .gitlab/ci/.gitlab-ci.yml
  .gitlab/ci/bucket-upload.yml
  .gitlab/ci/global.yml
  .gitlab/ci/on-push.yml
  Tests/Marketplace/Tests/marketplace_services_test.py
  Tests/Marketplace/Tests/search_and_install_packs_test.py
  Tests/Marketplace/Tests/upload_packs_test.py
  Tests/Marketplace/copy_and_upload_packs.py
  Tests/Marketplace/marketplace_constants.py
  Tests/Marketplace/marketplace_services.py
  Tests/Marketplace/prepare_public_index_for_private_testing.py
  Tests/Marketplace/private_build_prepare_for_testing.py
  Tests/Marketplace/search_and_install_packs.py
  Tests/Marketplace/upload_packs.py
  Tests/private_build/upload_packs_private.py
  Tests/scripts/prepare_content_packs_for_testing.sh
  Tests/scripts/validate_index.py
  Tests/scripts/validate_premium_packs.sh
  Utils/trigger_test_upload_flow.sh
Labels: docs-approved

#14619 Fixed docs for GenericWebhook
  Packs/GenericWebhook/Integrations/GenericWebhook/README.md
Labels: Contribution, docs-approved, Contribution Form Filled, Community

#14832 Azure ad graph test playbook
  Packs/AzureActiveDirectory/Integrations/AzureADIdentityProtection/AzureADIdentityProtection.py
  Packs/AzureActiveDirectory/Integrations/AzureADIdentityProtection/AzureADIdentityProtection.yml
  Packs/AzureActiveDirectory/Integrations/AzureADIdentityProtection/AzureADIdentityProtection_test.py
  Packs/AzureActiveDirectory/ReleaseNotes/1_1_2.md
  Packs/AzureActiveDirectory/TestPlaybooks/playbook-AzureADIdentityProtection_Test.yml
  Packs/AzureActiveDirectory/pack_metadata.json
  Tests/conf.json
Labels: docs-approved

#15203 Fix docs links
  Packs/ArcSightLogger/Integrations/integration-ArcSightLogger_README.md
  Packs/CarbonBlackProtect/Integrations/CarbonBlackProtect/README.md
  Packs/DNSDB/Integrations/integration-DNSDB_README.md
  Packs/EWSMailSender/Integrations/EWSMailSender/README.md
  Packs/Forcepoint/Integrations/integration-Forcepoint_README.md
  Packs/ICEBRG/Integrations/integration-ICEBRG_README.md
  Packs/OpsGenie/Integrations/integration-OpsGenie_README.md
  Packs/ProtectWise/Integrations/integration-ProtectWise_README.md
  Packs/ServiceNow/Integrations/ServiceNow/README.md
  Packs/Snowflake/Integrations/Snowflake/README.md
  Packs/Vectra/Integrations/integration-Vectra_README.md
Labels: bug, docs-approved

#15192 QRadar Bug Due To Failed Casting To Number
  Packs/QRadar/Integrations/QRadar_v3/QRadar_v3.py
  Packs/QRadar/ReleaseNotes/2_0_28.md
  Packs/QRadar/pack_metadata.json
Labels: docs-approved, release-notes-only

#15208 fixed subtypes according to docker images
  Packs/GoogleVault/Integrations/GoogleVault/GoogleVault.yml
  Packs/GoogleVault/ReleaseNotes/1_0_5.md
  Packs/GoogleVault/pack_metadata.json
  Packs/IBMResilientSystems/Integrations/IBMResilientSystems/IBMResilientSystems.yml
  Packs/IBMResilientSystems/ReleaseNotes/1_0_8.md
  Packs/IBMResilientSystems/pack_metadata.json
Labels: docs-approved

#15000 Added Missing Permission
  Packs/MicrosoftGraphMail/Integrations/MicrosoftGraphMail/README.md
Labels: docs-approved

#15196 Update README.md
  Packs/Druva/CortexXsoar.png
  Packs/Druva/README.md
Labels: Contribution, docs-approved, Partner, Contribution Form Filled

#15197 Update pack_metadata.json
  Packs/Druva/pack_metadata.json
Labels: Contribution, docs-approved, Partner, Contribution Form Filled

#15214 core packs build number fix 2
  Tests/scripts/prepare_content_packs_for_testing.sh
Labels: docs-approved

#15227 Remove Problematic Echoing of Shell Version
  .gitlab/ci/global.yml
Labels: docs-approved

#15213 JsonToTable: added the headers argument
  Packs/CommonScripts/ReleaseNotes/1_4_42.md
  Packs/CommonScripts/Scripts/JsonToTable/JsonToTable.py
  Packs/CommonScripts/Scripts/JsonToTable/JsonToTable.yml
  Packs/CommonScripts/pack_metadata.json
Labels: docs-approved

#15014 Adding Classifiers, Mappers, Incident Type, Incident Fields
  Packs/Lacework/Classifiers/classifier-Lacework.json
  Packs/Lacework/Classifiers/classifier-Lacework_5_9_9.json
  Packs/Lacework/Classifiers/classifier-mapper-incoming-Lacework.json
  Packs/Lacework/IncidentFields/incidentfield-Lacework_Event_Actor.json
  Packs/Lacework/IncidentFields/incidentfield-Lacework_Event_Id.json
  Packs/Lacework/IncidentFields/incidentfield-Lacework_Event_Model.json
  Packs/Lacework/IncidentFields/incidentfield-Lacework_Event_Type.json
  Packs/Lacework/IncidentFields/incidentfield-Lacework_Recommendation_Account_Alias.json
  Packs/Lacework/IncidentFields/incidentfield-Lacework_Recommendation_Account_Id.json
  Packs/Lacework/IncidentFields/incidentfield-Lacework_Recommendation_Id.json
  Packs/Lacework/IncidentFields/incidentfield-Lacework_Recommendation_Title.json
  Packs/Lacework/IncidentTypes/incidenttype-Lacework_Event.json
  Packs/Lacework/Integrations/Lacework/Lacework.py
  Packs/Lacework/Integrations/Lacework/Lacework.yml
  Packs/Lacework/README.md
  Packs/Lacework/ReleaseNotes/1_1_0.md
  Packs/Lacework/pack_metadata.json
Labels: Contribution, docs-approved, Contribution Form Filled, Community

#15218 Update SecurityAdvisor README.md
  Packs/SecurityAdvisor/README.md
Labels: Contribution, docs-approved, Partner, Contribution Form Filled

#15011 Fix mock of time
  Packs/GuardiCore/Integrations/GuardiCoreV2/GuardiCoreV2_test.py
  Packs/GuardiCore/Integrations/GuardiCoreV2/Pipfile
  Packs/GuardiCore/Integrations/GuardiCoreV2/Pipfile.lock
Labels: bug, docs-approved

#15124 Added control over which core packs are upgraded.
  Tests/Marketplace/copy_and_upload_packs.py
  Tests/Marketplace/marketplace_constants.py
  Tests/Marketplace/upgrade_core_packs_list.json
  Tests/Marketplace/upload_packs.py
Labels: docs-approved

#15088 Add support for Sites to SentinelOne threat commands
  Packs/SentinelOne/Integrations/SentinelOne-V2/README.md
  Packs/SentinelOne/Integrations/SentinelOne-V2/SentinelOne-V2.py
  Packs/SentinelOne/Integrations/SentinelOne-V2/SentinelOne-V2.yml
  Packs/SentinelOne/ReleaseNotes/2_0_5.md
  Packs/SentinelOne/pack_metadata.json
Labels: Contribution, docs-approved, Contribution Form Filled, Community

#15245 Threat Intel Report - add RBAC support
  Packs/ThreatIntel/GenericDefinitions/genericdefinition-ThreatIntelReport.json
  Packs/ThreatIntel/ReleaseNotes/1_0_5.md
  Packs/ThreatIntel/pack_metadata.json
Labels: docs-approved

#15079 Reducing memory usage for DBotBuildPhishingClassifier
  Packs/Base/ReleaseNotes/1_13_38.md
  Packs/Base/Scripts/DBotBuildPhishingClassifier/DBotBuildPhishingClassifier.py
  Packs/Base/pack_metadata.json
  Packs/ML/TestPlaybooks/playbook-Create_Phishing_Classifier_V2_ML_Test.yml
  Packs/ML/TestPlaybooks/playbook-DBot_Create_Phishing_Classifier_V2_From_File-_Test.yml
Labels: docs-approved

#15153 crowdstrike falcon generate status fix
  Packs/CrowdStrikeFalcon/Integrations/CrowdStrikeFalcon/CrowdStrikeFalcon.py
  Packs/CrowdStrikeFalcon/Integrations/CrowdStrikeFalcon/CrowdStrikeFalcon.yml
  Packs/CrowdStrikeFalcon/Integrations/CrowdStrikeFalcon/CrowdStrikeFalcon_test.py
  Packs/CrowdStrikeFalcon/ReleaseNotes/1_3_2.md
  Packs/CrowdStrikeFalcon/pack_metadata.json
Labels: bug, docs-approved, release-notes-only

#15258 deprecate Devo integration
  Packs/Devo/Integrations/Devo/Devo.yml
  Packs/Devo/Integrations/Devo/README.md
  Packs/Devo/ReleaseNotes/1_1_6.md
  Packs/Devo/pack_metadata.json
  Tests/conf.json
Labels: docs-approved

#15146 update reputations command - is array 2
  Packs/CofenseIntelligenceV2/Integrations/CofenseIntelligenceV2/CofenseIntelligenceV2.yml
  Packs/CofenseIntelligenceV2/ReleaseNotes/1_0_3.md
  Packs/CofenseIntelligenceV2/pack_metadata.json
  Packs/CortexXDR/Integrations/CortexXDRIR/CortexXDRIR.yml
  Packs/CortexXDR/ReleaseNotes/4_1_5.md
  Packs/CortexXDR/pack_metadata.json
  Packs/CrowdStrikeFalcon/.pack-ignore
  Packs/DeHashed/Integrations/DeHashed/DeHashed.yml
  Packs/DeHashed/ReleaseNotes/1_1_4.md
  Packs/DeHashed/pack_metadata.json
  Packs/DomainTools/.pack-ignore
  Packs/DomainTools_Iris/.pack-ignore
  Packs/EclecticIQ/.pack-ignore
  Packs/EmailRepIO/.pack-ignore
Labels: docs-approved, release-notes-only

#15148 update reputations command - is array 3
  Packs/GoogleSafeBrowsing/Integrations/GoogleSafeBrowsingV2/GoogleSafeBrowsingV2.yml
  Packs/GoogleSafeBrowsing/ReleaseNotes/2_0_7.md
  Packs/GoogleSafeBrowsing/pack_metadata.json
  Packs/Ipstack/.pack-ignore
  Packs/IsItPhishing/.pack-ignore
  Packs/Maltiverse/Integrations/Maltiverse/Maltiverse.yml
  Packs/Maltiverse/ReleaseNotes/1_0_9.md
  Packs/Maltiverse/pack_metadata.json
  Packs/MaxMind_GeoIP2/.pack-ignore
  Packs/OpenPhish/Integrations/OpenPhish_v2/OpenPhish_v2.yml
  Packs/OpenPhish/ReleaseNotes/2_0_7.md
  Packs/OpenPhish/pack_metadata.json
  Packs/PaloAltoNetworks_Threat_Vault/Integrations/Threat_Vault/Threat_Vault.yml
  Packs/PaloAltoNetworks_Threat_Vault/ReleaseNotes/1_0_9.md
  Packs/PaloAltoNetworks_Threat_Vault/pack_metadata.json
  Packs/Pipl/.pack-ignore
  Packs/PolySwarm/.pack-ignore
  Packs/Shodan/.pack-ignore
  Packs/SlashNextPhishingIncidentResponse/.pack-ignore
  Packs/Symantec_Deepsight/.pack-ignore
  Packs/ThreatConnect/.pack-ignore
  Packs/ThreatMiner/.pack-ignore
  Packs/URLHaus/.pack-ignore
  Packs/VirusTotal/.pack-ignore
  Packs/VulnDB/.pack-ignore
Labels: docs-approved, release-notes-only

#15265 fix bug when running using playbook
  Packs/ShiftManagement/.pack-ignore
  Packs/ShiftManagement/ReleaseNotes/1_2_7.md
  Packs/ShiftManagement/Scripts/ManageOOOusers/ManageOOOusers.py
  Packs/ShiftManagement/Scripts/ManageOOOusers/ManageOOOusers.yml
  Packs/ShiftManagement/Scripts/ManageOOOusers/README.md
  Packs/ShiftManagement/TestPlaybooks/test_manageOOOUsers.yml
  Packs/ShiftManagement/pack_metadata.json
  Tests/conf.json
Labels: docs-approved

#15298 bump version to 21.10.0
  .circleci/content_release_vars.sh
Labels: docs-approved

#15297 PAN-OS - Documentation and metadata improvements around push
  Packs/PAN-OS/Integrations/Panorama/Panorama.yml
  Packs/PAN-OS/Integrations/Panorama/README.md
  Packs/PAN-OS/ReleaseNotes/1_7_2.md
  Packs/PAN-OS/pack_metadata.json
Labels: docs-approved, release-notes-only

#15302 Disable sdk_nightly
  .circleci/config.yml
Labels: docs-approved

#15072 Axonius regex hostname action
  Packs/Axonius/Integrations/Axonius/Axonius.py
  Packs/Axonius/Integrations/Axonius/Axonius.yml
  Packs/Axonius/Integrations/Axonius/README.md
  Packs/Axonius/ReleaseNotes/1_0_4.md
  Packs/Axonius/pack_metadata.json
Labels: Contribution, docs-approved, Partner, Contribution Form Filled

#15285 [Fix] Tenable: The "alt_targets" parameter is not used in a scan
  Packs/Tenable_io/Integrations/Tenable_io/Tenable_io.py
  Packs/Tenable_io/ReleaseNotes/1_1_5.md
  Packs/Tenable_io/pack_metadata.json
Labels: bug, docs-approved, release-notes-only

#15312 Unskip G suite security center
  Packs/GSuiteSecurityAlertCenter/TestPlaybooks/playbook-GSuiteSecurityAlertCenter-test.yml
  Tests/conf.json
Labels: docs-approved

#15311 Dashboard widgets to use selected time range
  Packs/CommonDashboards/Dashboards/dashboard-Home.json
  Packs/CommonDashboards/ReleaseNotes/1_1_2.md
  Packs/CommonDashboards/pack_metadata.json
Labels: docs-approved, release-notes-only

#15211 New Webscraper Automation Script
  Packs/WebScraper/.pack-ignore
  Packs/WebScraper/.secrets-ignore
  Packs/WebScraper/README.md
  Packs/WebScraper/Scripts/WebScraper/README.md
  Packs/WebScraper/Scripts/WebScraper/WebScraper.py
  Packs/WebScraper/Scripts/WebScraper/WebScraper.yml
  Packs/WebScraper/pack_metadata.json
Labels: Contribution, docs-approved, Contribution Form Filled, Community

#13866 The hive project
  Packs/TheHiveProject/.secrets-ignore
  Packs/TheHiveProject/Integrations/TheHiveProject/README.md
  Packs/TheHiveProject/Integrations/TheHiveProject/TheHiveProject.py
  Packs/TheHiveProject/Integrations/TheHiveProject/TheHiveProject.yml
  Packs/TheHiveProject/Integrations/TheHiveProject/TheHiveProject_test.py
  Packs/TheHiveProject/Integrations/TheHiveProject/command_examples.txt
  Packs/TheHiveProject/Integrations/TheHiveProject/test_data/added_user.json
  Packs/TheHiveProject/Integrations/TheHiveProject/test_data/cases_list.json
  Packs/TheHiveProject/Integrations/TheHiveProject/test_data/merged_cases.json
  Packs/TheHiveProject/Integrations/TheHiveProject/test_data/users_list.json
  Packs/TheHiveProject/README.md
  Packs/TheHiveProject/ReleaseNotes/1_1_2.md
  Packs/TheHiveProject/ReleaseNotes/1_1_3.md
  Packs/TheHiveProject/TestPlaybooks/Playbook_TheHiveProject_Test.yml
  Packs/TheHiveProject/pack_metadata.json
  Tests/conf.json
Labels: docs-approved

#15332 Threat Intel Report - fixed tab name to be in plural
  Packs/ThreatIntel/GenericModules/genericmodule-ThreatIntel.json
  Packs/ThreatIntel/ReleaseNotes/1_0_7.md
  Packs/ThreatIntel/pack_metadata.json
Labels: docs-approved

#15217 Claroty Readme Update
  Packs/Claroty/.secrets-ignore
  Packs/Claroty/README.md
Labels: Contribution, docs-approved, Partner, Contribution Form Filled

#15344 Threat Intel Report - fix widgets sizes
  Packs/ThreatIntel/GenericModules/genericmodule-ThreatIntel.json
  Packs/ThreatIntel/ReleaseNotes/1_0_8.md
  Packs/ThreatIntel/pack_metadata.json
Labels: docs-approved

#15348 Updated Email Communication readme with pack article
  Packs/EmailCommunication/README.md
Labels: docs-approved

#15350 improved docs
  Packs/FeedCSV/Integrations/FeedCSV/FeedCSV.yml
  Packs/FeedCSV/ReleaseNotes/1_1_5.md
  Packs/FeedCSV/pack_metadata.json
Labels: docs-approved

#15355 Common fields for IAM 1.7.0
  Packs/CommonTypes/IncidentFields/incidentfield-Acquisition_Hire.json
  Packs/CommonTypes/IndicatorFields/indicatorfield-Acquisition_Hire.json
  Packs/CommonTypes/IndicatorFields/indicatorfield-Force_Sync.json
  Packs/CommonTypes/ReleaseNotes/3_1_19.md
  Packs/CommonTypes/pack_metadata.json
Labels: docs-approved

#14019 G suite auditor
  Packs/ApiModules/Scripts/GSuiteApiModule/GSuiteApiModule.py
  Packs/GSuiteAdmin/ReleaseNotes/1_1_0.md
  Packs/GSuiteAdmin/pack_metadata.json
  Packs/GSuiteSecurityAlertCenter/ReleaseNotes/1_1_0.md
  Packs/GSuiteSecurityAlertCenter/pack_metadata.json
  Packs/GoogleCalendar/ReleaseNotes/1_1_0.md
  Packs/GoogleCalendar/pack_metadata.json
  Packs/GoogleDrive/ReleaseNotes/1_2_0.md
  Packs/GoogleDrive/pack_metadata.json
  Packs/GsuiteAuditor/.pack-ignore
  Packs/GsuiteAuditor/.secrets-ignore
  Packs/GsuiteAuditor/Integrations/GsuiteAuditor/GSuiteAuditor_image.png
  Packs/GsuiteAuditor/Integrations/GsuiteAuditor/GsuiteAuditor.py
  Packs/GsuiteAuditor/Integrations/GsuiteAuditor/GsuiteAuditor.yml
  Packs/GsuiteAuditor/Integrations/GsuiteAuditor/GsuiteAuditor_description.md
  Packs/GsuiteAuditor/Integrations/GsuiteAuditor/GsuiteAuditor_test.py
  Packs/GsuiteAuditor/Integrations/GsuiteAuditor/Pipfile
  Packs/GsuiteAuditor/Integrations/GsuiteAuditor/Pipfile.lock
  Packs/GsuiteAuditor/Integrations/GsuiteAuditor/README.md
  Packs/GsuiteAuditor/Integrations/GsuiteAuditor/command_examples
  Packs/GsuiteAuditor/Integrations/GsuiteAuditor/test_data/activities_list_entry_context.json
  Packs/GsuiteAuditor/Integrations/GsuiteAuditor/test_data/activities_list_response.json
  Packs/GsuiteAuditor/Integrations/GsuiteAuditor/test_data/service_account_json.txt
  Packs/GsuiteAuditor/README.md
  Packs/GsuiteAuditor/TestPlaybooks/GSuiteAuditor-Test.yml
  Packs/GsuiteAuditor/doc_files/add-scope-admin-1.png
  Packs/GsuiteAuditor/doc_files/add-scope-admin-2.png
  Packs/GsuiteAuditor/doc_files/add-scope-admin-3.png
  Packs/GsuiteAuditor/doc_files/create-project-1.png
  Packs/GsuiteAuditor/doc_files/enable-api.jpg
  Packs/GsuiteAuditor/doc_files/enable-gke-api-enable-2.png
  Packs/GsuiteAuditor/doc_files/google-api-menu.png
  Packs/GsuiteAuditor/doc_files/service-account-create-1.png
  Packs/GsuiteAuditor/doc_files/service-account-create-3.png
  Packs/GsuiteAuditor/doc_files/service-account-create-4.png
  Packs/GsuiteAuditor/doc_files/service-acount-menu.png
  Packs/GsuiteAuditor/pack_metadata.json
  Tests/conf.json
Labels: docs-approved

#13971 Clarizen IAM
  Packs/Clarizen/.pack-ignore
  Packs/Clarizen/.secrets-ignore
  Packs/Clarizen/Classifiers/classifier-User_Profile_-_Clarizen_(Incoming).json
  Packs/Clarizen/Classifiers/classifier-User_Profile_-_Clarizen_(Outgoing).json
  Packs/Clarizen/Integrations/ClarizenIAM/ClarizenIAM.py
  Packs/Clarizen/Integrations/ClarizenIAM/ClarizenIAM.yml
  Packs/Clarizen/Integrations/ClarizenIAM/ClarizenIAM_description.md
  Packs/Clarizen/Integrations/ClarizenIAM/ClarizenIAM_image.png
  Packs/Clarizen/Integrations/ClarizenIAM/ClarizenIAM_test.py
  Packs/Clarizen/Integrations/ClarizenIAM/Pipfile
  Packs/Clarizen/Integrations/ClarizenIAM/Pipfile.lock
  Packs/Clarizen/Integrations/ClarizenIAM/README.md
  Packs/Clarizen/Integrations/ClarizenIAM/command_examples
  Packs/Clarizen/README.md
  Packs/Clarizen/pack_metadata.json
Labels: docs-approved, IAM

#15365 Unzip password protected rar files would timeout.
  Packs/CommonScripts/ReleaseNotes/1_4_48.md
  Packs/CommonScripts/Scripts/UnzipFile/UnzipFile.py
  Packs/CommonScripts/Scripts/UnzipFile/UnzipFile.yml
  Packs/CommonScripts/pack_metadata.json
Labels: docs-approved

#15235 AWS GuardDuty support authentication via tokens support
  Packs/AWS-GuardDuty/Integrations/AWSGuardDuty/AWSGuardDuty.py
  Packs/AWS-GuardDuty/Integrations/AWSGuardDuty/AWSGuardDuty.yml
  Packs/AWS-GuardDuty/Integrations/AWSGuardDuty/AWSGuardDuty_test.py
  Packs/AWS-GuardDuty/Integrations/AWSGuardDuty/README.md
  Packs/AWS-GuardDuty/ReleaseNotes/1_2_0.md
  Packs/AWS-GuardDuty/pack_metadata.json
Labels: docs-approved

#15289 add fromDate arg to IndicatorMaliciousRatioCalculation script
  Packs/CommonScripts/ReleaseNotes/1_4_50.md
  Packs/CommonScripts/Scripts/IndicatorMaliciousRatioCalculation/IndicatorMaliciousRatioCalculation.py
  Packs/CommonScripts/Scripts/IndicatorMaliciousRatioCalculation/IndicatorMaliciousRatioCalculation.yml
  Packs/CommonScripts/Scripts/IndicatorMaliciousRatioCalculation/Pipfile
  Packs/CommonScripts/Scripts/IndicatorMaliciousRatioCalculation/Pipfile.lock
  Packs/CommonScripts/Scripts/IndicatorMaliciousRatioCalculation/README.md
  Packs/CommonScripts/Scripts/script-IndicatorMaliciousRatioCalculation.yml
  Packs/CommonScripts/TestPlaybooks/playbook-IndicatorMaliciousRatioCalculation_Test.yml
  Packs/CommonScripts/pack_metadata.json
  Tests/conf.json
Labels: docs-approved, release-notes-only

#15389 secrets ignore
  Packs/Clarizen/.secrets-ignore
Labels: docs-approved

#15063 Aburt demisto panorama update - polling commands
  Packs/PAN-OS/Integrations/Panorama/Panorama.py
  Packs/PAN-OS/Integrations/Panorama/Panorama.yml
  Packs/PAN-OS/ReleaseNotes/1_8_0.md
  Packs/PAN-OS/pack_metadata.json
Labels: Contribution, Contribution Form Filled, Community

#15377 Update exifread
  Packs/ExifRead/ReleaseNotes/1_0_1.md
  Packs/ExifRead/Scripts/ExifRead/ExifRead.py
  Packs/ExifRead/Scripts/ExifRead/ExifRead.yml
  Packs/ExifRead/Scripts/ExifRead/ExifRead_test.py
  Packs/ExifRead/Scripts/ExifRead/Pipfile
  Packs/ExifRead/Scripts/ExifRead/Pipfile.lock
  Packs/ExifRead/Scripts/ExifRead/README.md
  Packs/ExifRead/Scripts/ExifRead/TestData/example_result.json
  Packs/ExifRead/Scripts/ExifRead/TestData/image
  Packs/ExifRead/Scripts/script-ExifRead.yml
  Packs/ExifRead/pack_metadata.json
Labels: docs-approved

#15379 fixed hXXps not being recognized
  Packs/CommonScripts/.secrets-ignore
  Packs/CommonScripts/ReleaseNotes/1_4_51.md
  Packs/CommonScripts/Scripts/script-UnEscapeURLs.yml
  Packs/CommonScripts/TestPlaybooks/playbook-UnEscapeURLs-Test.yml
  Packs/CommonScripts/pack_metadata.json
Labels: docs-approved

#15381 AutoFocusV2 Fixed IPv6 recognized as IPv4
  Packs/AutoFocus/Integrations/AutofocusV2/AutofocusV2.py
  Packs/AutoFocus/ReleaseNotes/1_3_11.md
  Packs/AutoFocus/pack_metadata.json
Labels: docs-approved

#15316 Validating no Nan precision before storing a model
  Packs/Base/ReleaseNotes/1_13_41.md
  Packs/Base/Scripts/DBotTrainTextClassifierV2/DBotTrainTextClassifierV2.py
  Packs/Base/pack_metadata.json
Labels: docs-approved

#14810 Bitsight/adds guard against no status code
  Packs/BitSight/Integrations/BitSightForSecurityPerformanceManagement/BitSightForSecurityPerformanceManagement.py
  Packs/BitSight/ReleaseNotes/1_0_8.md
  Packs/BitSight/pack_metadata.json
Labels: Contribution, docs-approved, Partner, Contribution Form Filled

#15397 Fix mapObject demistomock
  Tests/demistomock/demistomock.py
Labels: docs-approved

#15299 Update README.md
  Packs/GreatHorn/README.md
Labels: Contribution, docs-approved, Partner, Contribution Form Filled

#15422 Add files via upload
  TestData/file-sample.docx
  TestData/sample-test.pdf
Labels: docs-approved

#15085 Aburt demisto xdr xql improve
  Packs/CortexXDR/Integrations/XQLQueryingEngine/README.md
  Packs/CortexXDR/Integrations/XQLQueryingEngine/XQLQueryingEngine.py
  Packs/CortexXDR/Integrations/XQLQueryingEngine/XQLQueryingEngine.yml
  Packs/CortexXDR/ReleaseNotes/4_1_8.md
  Packs/CortexXDR/pack_metadata.json
Labels: Contribution, docs-approved

#15444 Update docker image for readpdf
  Packs/CommonScripts/ReleaseNotes/1_4_54.md
  Packs/CommonScripts/Scripts/ReadPDFFileV2/ReadPDFFileV2.yml
  Packs/CommonScripts/pack_metadata.json
Labels: docs-approved

#15555 Updated Pack rasterize to use the latest release for demisto/chromium docker image 1.0.0.24317
  Packs/rasterize/Integrations/rasterize/rasterize.yml
  Packs/rasterize/ReleaseNotes/1_0_14.md
  Packs/rasterize/pack_metadata.json
Labels: content, docs-approved, release-notes-only, docker

#15435 CrowdStrike Falcon - Custom IOCs
  Packs/CrowdStrikeFalcon/Integrations/CrowdStrikeFalcon/CrowdStrikeFalcon.py
  Packs/CrowdStrikeFalcon/Integrations/CrowdStrikeFalcon/CrowdStrikeFalcon.yml
  Packs/CrowdStrikeFalcon/Integrations/CrowdStrikeFalcon/CrowdStrikeFalcon_test.py
  Packs/CrowdStrikeFalcon/Integrations/CrowdStrikeFalcon/README.md
  Packs/CrowdStrikeFalcon/ReleaseNotes/1_4_0.json
  Packs/CrowdStrikeFalcon/ReleaseNotes/1_4_0.md
  Packs/CrowdStrikeFalcon/pack_metadata.json
Labels: docs-approved

#15231 AutoFocus Tags Feed
  Packs/AutoFocus/Integrations/AutoFocusTagsFeed/AutoFocusTagsFeed.py
  Packs/AutoFocus/Integrations/AutoFocusTagsFeed/AutoFocusTagsFeed.yml
  Packs/AutoFocus/Integrations/AutoFocusTagsFeed/AutoFocusTagsFeed_description.md
  Packs/AutoFocus/Integrations/AutoFocusTagsFeed/AutoFocusTagsFeed_image.png
  Packs/AutoFocus/Integrations/AutoFocusTagsFeed/AutoFocusTagsFeed_test.py
  Packs/AutoFocus/Integrations/AutoFocusTagsFeed/Pipfile
  Packs/AutoFocus/Integrations/AutoFocusTagsFeed/Pipfile.lock
  Packs/AutoFocus/Integrations/AutoFocusTagsFeed/README.md
  Packs/AutoFocus/Integrations/AutoFocusTagsFeed/command_examples
  Packs/AutoFocus/Integrations/AutoFocusTagsFeed/test_data/all_tags_result.json
  Packs/AutoFocus/Integrations/AutoFocusTagsFeed/test_data/build_iterator_results.json
  Packs/AutoFocus/Integrations/AutoFocusTagsFeed/test_data/fetch_indicators_results.json
  Packs/AutoFocus/Integrations/AutoFocusTagsFeed/test_data/tag_details_result.json
  Packs/AutoFocus/ReleaseNotes/2_0_0.md
  Packs/AutoFocus/TestPlaybooks/playbook-AutoFocusTagsFeed_test.yml
  Packs/AutoFocus/pack_metadata.json
  Tests/conf.json
Labels: docs-approved

#15557 Threat Intel Report Core Pack
  Tests/Marketplace/core_packs_list.json
Labels: docs-approved

#15560 Update README.md
  Packs/PrismaSaasSecurity/Integrations/SaasSecurity/README.md
Labels: docs-approved

#15561 Update SaasSecurity.yml
  Packs/PrismaSaasSecurity/Integrations/SaasSecurity/SaasSecurity.yml
Labels: docs-approved

#15562 Update SaasSecurity_description.md
  Packs/PrismaSaasSecurity/Integrations/SaasSecurity/SaasSecurity_description.md
Labels: docs-approved

#15558 Improve SaaS Security mirroring docs
  Packs/PrismaSaasSecurity/Integrations/SaasSecurity/README.md
  Packs/PrismaSaasSecurity/Integrations/SaasSecurity/SaasSecurity.yml
  Packs/PrismaSaasSecurity/Integrations/SaasSecurity/SaasSecurity_description.md
  Packs/PrismaSaasSecurity/ReleaseNotes/1_1_1.md
  Packs/PrismaSaasSecurity/pack_metadata.json
Labels: docs-approved

#15574 Update README.md
  Packs/EDL/Integrations/EDL/README.md
Labels: docs-approved
