Repository demisto/content, pull requests merged in 2021-12, with the labels that each got.

#15674 fix sane reports
  Packs/Base/ReleaseNotes/1_14_1.md
  Packs/Base/ReleaseNotes/1_16_1.md
  Packs/Base/Scripts/SanePdfReport/SanePdfReport.py
  Packs/Base/pack_metadata.json
Labels: docs-approved

#16034 Create my ToDo tasks widget
  Packs/CommonWidgets/ReleaseNotes/1_2_2.md
  Packs/CommonWidgets/Scripts/MyToDoTasksWidget/MyToDoTasksWidget.py
  Packs/CommonWidgets/Scripts/MyToDoTasksWidget/MyToDoTasksWidget.yml
  Packs/CommonWidgets/Scripts/MyToDoTasksWidget/MyToDoTasksWidget_test.py
  Packs/CommonWidgets/Widgets/widget-MyTodoTasks.json
  Packs/CommonWidgets/pack_metadata.json
Labels: docs-approved

#16037 Azure sentinel incident url
  Packs/AzureSentinel/Integrations/AzureSentinel/AzureSentinel.py
  Packs/AzureSentinel/Integrations/AzureSentinel/AzureSentinel.yml
  Packs/AzureSentinel/Integrations/AzureSentinel/README.md
  Packs/AzureSentinel/ReleaseNotes/1_2_3.md
  Packs/AzureSentinel/pack_metadata.json
Labels: docs-approved

#15923 [Cofense-32] Cofense Feed Enhancement
  Packs/FeedCofense/.secrets-ignore
  Packs/FeedCofense/IndicatorFields/incidentfield-Cofense-ASN-Organization.json
  Packs/FeedCofense/IndicatorFields/incidentfield-Cofense-Continent-Code.json
  Packs/FeedCofense/IndicatorFields/incidentfield-Cofense-Continent-Name.json
  Packs/FeedCofense/IndicatorFields/incidentfield-Cofense-Entered-Date.json
  Packs/FeedCofense/IndicatorFields/incidentfield-Cofense-File-Name.json
  Packs/FeedCofense/IndicatorFields/incidentfield-Cofense-ISP.json
  Packs/FeedCofense/IndicatorFields/incidentfield-Cofense-Infrastructure-Type-Description.json
  Packs/FeedCofense/IndicatorFields/incidentfield-Cofense-Lookup-On.json
  Packs/FeedCofense/IndicatorFields/incidentfield-Cofense-Postal-Code.json
  Packs/FeedCofense/IndicatorFields/incidentfield-Cofense-Role-Description.json
  Packs/FeedCofense/IndicatorFields/incidentfield-Cofense-SHA224.json
  Packs/FeedCofense/IndicatorFields/incidentfield-Cofense-SHA384.json
  Packs/FeedCofense/IndicatorFields/incidentfield-Cofense-Subdivision-Iso-Code.json
  Packs/FeedCofense/IndicatorFields/incidentfield-Cofense-Subdivision-Name.json
  Packs/FeedCofense/IndicatorFields/incidentfield-Cofense-Threat-ID.json
  Packs/FeedCofense/IndicatorFields/incidentfield-Cofense-Time-Zone.json
  Packs/FeedCofense/Integrations/FeedCofense/FeedCofense.py
  Packs/FeedCofense/Integrations/FeedCofense/FeedCofense.yml
  Packs/FeedCofense/Integrations/FeedCofense/FeedCofense_test.py
  Packs/FeedCofense/Integrations/FeedCofense/README.md
  Packs/FeedCofense/Integrations/FeedCofense/TestData/fetch_indicators.json
  Packs/FeedCofense/Integrations/FeedCofense/TestData/search_output.json
  Packs/FeedCofense/README.md
  Packs/FeedCofense/ReleaseNotes/1_1_0.md
  Packs/FeedCofense/pack_metadata.json
Labels: Contribution, docs-approved, Partner, Contribution Form Filled

#15920 [Cofense-32] Cofense Intelligence V2 Enhancement
  Packs/CofenseIntelligenceV2/.secrets-ignore
  Packs/CofenseIntelligenceV2/Integrations/CofenseIntelligenceV2/CofenseIntelligenceV2.py
  Packs/CofenseIntelligenceV2/Integrations/CofenseIntelligenceV2/CofenseIntelligenceV2.yml
  Packs/CofenseIntelligenceV2/Integrations/CofenseIntelligenceV2/CofenseIntelligenceV2_test.py
  Packs/CofenseIntelligenceV2/Integrations/CofenseIntelligenceV2/README.md
  Packs/CofenseIntelligenceV2/Integrations/CofenseIntelligenceV2/command_examples.txt
  Packs/CofenseIntelligenceV2/Integrations/CofenseIntelligenceV2/test_data/test_extracted_string.json
  Packs/CofenseIntelligenceV2/Integrations/CofenseIntelligenceV2/test_data/test_search_domain.json
  Packs/CofenseIntelligenceV2/Integrations/CofenseIntelligenceV2/test_data/test_search_email.json
  Packs/CofenseIntelligenceV2/Integrations/CofenseIntelligenceV2/test_data/test_search_file.json
  Packs/CofenseIntelligenceV2/Integrations/CofenseIntelligenceV2/test_data/test_search_ip.json
  Packs/CofenseIntelligenceV2/Integrations/CofenseIntelligenceV2/test_data/test_search_url.json
  Packs/CofenseIntelligenceV2/Integrations/CofenseIntelligenceV2/test_data/test_threats.json
  Packs/CofenseIntelligenceV2/README.md
  Packs/CofenseIntelligenceV2/ReleaseNotes/1_1_0.md
  Packs/CofenseIntelligenceV2/TestPlaybooks/CofenseIntelligenceV2-Test.yml
  Packs/CofenseIntelligenceV2/pack_metadata.json
Labels: Contribution, docs-approved, Partner, Contribution Form Filled

#16058 HashiCorp Vault - add concat username to cred param
  Packs/HashiCorp-Vault/Integrations/HashiCorpVault/HashiCorpVault.py
  Packs/HashiCorp-Vault/Integrations/HashiCorpVault/HashiCorpVault.yml
  Packs/HashiCorp-Vault/Integrations/HashiCorpVault/README.md
  Packs/HashiCorp-Vault/ReleaseNotes/1_0_4.md
  Packs/HashiCorp-Vault/pack_metadata.json
Labels: docs-approved

#16029 [TIR] add roles fields and set correct columns in Relationships table
  Packs/ThreatIntelReports/Layouts/layoutscontainer-ThreatIntelReport-CampaignReport.json
  Packs/ThreatIntelReports/Layouts/layoutscontainer-ThreatIntelReport-ExecutiveBriefReport.json
  Packs/ThreatIntelReports/Layouts/layoutscontainer-ThreatIntelReport-MalwareReport.json
  Packs/ThreatIntelReports/Layouts/layoutscontainer-ThreatIntelReport-ThreatActorReport.json
  Packs/ThreatIntelReports/Layouts/layoutscontainer-ThreatIntelReport-VulnerabilityReport.json
  Packs/ThreatIntelReports/ReleaseNotes/1_0_3.md
  Packs/ThreatIntelReports/pack_metadata.json
Labels: docs-approved

#16052 Fixed an issue where an incorrect name (inputs.IP addresses) is given…
  Packs/PANWComprehensiveInvestigation/Playbooks/Palo_Alto_Networks_-_Hunting_And_Threat_Detection.yml
  Packs/PANWComprehensiveInvestigation/ReleaseNotes/1_3_10.md
  Packs/PANWComprehensiveInvestigation/pack_metadata.json
Labels: Contribution, docs-approved, Contribution Form Filled, Community

#15649 cyberark- fix test
  Packs/cyberark_AIM/Integrations/CyberArkAIM_v2/CyberArkAIM_v2.py
  Packs/cyberark_AIM/Integrations/CyberArkAIM_v2/CyberArkAIM_v2.yml
  Packs/cyberark_AIM/Integrations/CyberArkAIM_v2/CyberArkAIM_v2_test.py
  Packs/cyberark_AIM/Integrations/CyberArkAIM_v2/README.md
  Packs/cyberark_AIM/ReleaseNotes/1_0_10.md
  Packs/cyberark_AIM/pack_metadata.json
Labels: docs-approved

#15976 Symantec DLP - troubleshooting kerberos/form auth
  Packs/SymantecDLP/Integrations/SymantecDLP/README.md
Labels: docs-approved

#15988 SplunkPy - convert value of labels to string
  Packs/SplunkPy/Integrations/SplunkPy/SplunkPy.py
  Packs/SplunkPy/Integrations/SplunkPy/SplunkPy_test.py
  Packs/SplunkPy/ReleaseNotes/2_2_7.md
  Packs/SplunkPy/pack_metadata.json
Labels: docs-approved, release-notes-only

#16070 fixed feed Cofense indicator field type
  Packs/FeedCofense/IndicatorFields/incidentfield-Cofense-Threat-ID.json
Labels: docs-approved

#16062 Forescout: fixed an issue where the integration failed on an HTTP timeout.
  Packs/Forescout/Integrations/Forescout/Forescout.py
  Packs/Forescout/Integrations/Forescout/Forescout.yml
  Packs/Forescout/Integrations/Forescout/README.md
  Packs/Forescout/ReleaseNotes/1_0_6.md
  Packs/Forescout/pack_metadata.json
Labels: bug, docs-approved, release-notes-only

#16072 update sane report docker image
  Packs/Base/ReleaseNotes/1_16_3.md
  Packs/Base/Scripts/SanePdfReport/SanePdfReport.yml
  Packs/Base/pack_metadata.json
Labels: docs-approved

#16075 removed server 6.0 from the upload flow
  .gitlab/ci/bucket-upload.yml
Labels: docs-approved

#16002 Zscaler - add the filter and query args to get-blacklist
  Packs/Zscaler/Integrations/Zscaler/README.md
  Packs/Zscaler/Integrations/Zscaler/Zscaler.py
  Packs/Zscaler/Integrations/Zscaler/Zscaler.yml
  Packs/Zscaler/Integrations/Zscaler/Zscaler_test.py
  Packs/Zscaler/ReleaseNotes/1_1_14.md
  Packs/Zscaler/pack_metadata.json
  Tests/conf.json
Labels: docs-approved

#15897 CrowdStrike Falcon Intel Feed - map also non-STIX fields
  Packs/FeedCrowdstrikeFalconIntel/Integrations/FeedCrowdstrikeFalconIntel/FeedCrowdstrikeFalconIntel.py
  Packs/FeedCrowdstrikeFalconIntel/Integrations/FeedCrowdstrikeFalconIntel/FeedCrowdstrikeFalconIntel.yml
  Packs/FeedCrowdstrikeFalconIntel/Integrations/FeedCrowdstrikeFalconIntel/FeedCrowdstrikeFalconIntel_test.py
  Packs/FeedCrowdstrikeFalconIntel/Integrations/FeedCrowdstrikeFalconIntel/test_data.json
  Packs/FeedCrowdstrikeFalconIntel/ReleaseNotes/2_0_7.md
  Packs/FeedCrowdstrikeFalconIntel/pack_metadata.json
Labels: bug, docs-approved, release-notes-only

#15996 Darktrace - set token params to be creds
  Packs/Darktrace/Integrations/Darktrace/Darktrace.py
  Packs/Darktrace/Integrations/Darktrace/Darktrace.yml
  Packs/Darktrace/ReleaseNotes/1_0_8.md
  Packs/Darktrace/pack_metadata.json
Labels: docs-approved

#15997 Jira v2 - set api token to be creds
  Packs/Jira/Integrations/JiraV2/JiraV2.py
  Packs/Jira/Integrations/JiraV2/JiraV2.yml
  Packs/Jira/ReleaseNotes/1_4_2.md
  Packs/Jira/pack_metadata.json
Labels: docs-approved

#15998 VMRay - set api key to be creds
  Packs/VMRay/Integrations/VMRay/VMRay.py
  Packs/VMRay/Integrations/VMRay/VMRay.yml
  Packs/VMRay/ReleaseNotes/1_1_4.md
  Packs/VMRay/pack_metadata.json
Labels: docs-approved

#16074 Fix bad pack ignore
  Packs/Arduino/.pack-ignore
  Packs/CaseManagement-Generic/.pack-ignore
  Packs/CommonPlaybooks/.pack-ignore
  Packs/CommonScripts/.pack-ignore
  Packs/CommonTypes/.pack-ignore
  Packs/ContentManagement/.pack-ignore
  Packs/ConvertTimezoneFromUTC/.pack-ignore
  Packs/CreatePlbkDoc/.pack-ignore
  Packs/EmailCommunication/.pack-ignore
  Packs/ExportToXLSX/.pack-ignore
  Packs/ExtFilter/.pack-ignore
  Packs/FetchIndicatorsFromFile/.pack-ignore
  Packs/GetLicenseID/.pack-ignore
  Packs/IntegrationsAndIncidentsHealthCheck/.pack-ignore
  Packs/InvertEveryTwoItems/.pack-ignore
  Packs/JsonUnescape/.pack-ignore
  Packs/MajorBreachesInvestigationandResponse/.pack-ignore
  Packs/MapPattern/.pack-ignore
  Packs/MapRegex/.pack-ignore
  Packs/MergeDictArray/.pack-ignore
  Packs/ModulesManagement/.pack-ignore
  Packs/PaloAltoNetworksAutomaticSLR_Community/.pack-ignore
  Packs/ParseHTMLTables/.pack-ignore
  Packs/ParseYAML/.pack-ignore
  Packs/PowershellPayloadResponse/.pack-ignore
  Packs/PublishList/.pack-ignore
  Packs/QRCodeReader/.pack-ignore
  Packs/RandomImages_VideosAndAudio/.pack-ignore
  Packs/Redact_DefangIndicators_URLs_IPs_Email/.pack-ignore
  Packs/RegexReplace/.pack-ignore
  Packs/RemoveEmpty/.pack-ignore
  Packs/ServerLogs/.pack-ignore
  Packs/ShiftManagement-AssignToNextShift/.pack-ignore
  Packs/StringifyArray/.pack-ignore
  Packs/StripAccentMarksFromString/.pack-ignore
  Packs/TeamManagement/.pack-ignore
  Packs/UnifiVideoNVR/.pack-ignore
Labels: docs-approved

#16081 skip autofocus in nightly
  Tests/conf.json
Labels: docs-approved

#16044 Add text/xml in Vulnerability_Management_-_Qualys PB for Quslys report
  Packs/qualys/Playbooks/playbook-Vulnerability_Management_-_Qualys_(Job)_-_V2.yml
  Packs/qualys/ReleaseNotes/1_0_13.md
  Packs/qualys/pack_metadata.json
Labels: bug, docs-approved, release-notes-only

#16084 Removed user that does not exist
  Packs/DeepInstinct/pack_metadata.json
Labels: docs-approved

#16065 Content Build: Removed redundant files and fixed a few pylint errors
  .circleci/config.yml
  .pylintrc
  Tests/Marketplace/configure_and_install_packs.py
  Tests/configure_and_test_integration_instances.py
  Tests/scripts/destroy_instances.py
  Tests/scripts/infrastructure_tests/release_notes_test.py
  Tests/scripts/linters_runner.sh
  Tests/scripts/pylint.sh
  Tests/tests/configure_and_test_integration_instances_test.py
  Utils/_script_docker_python_loop_example.py
  dev-requirements-py3.txt
  release_notes.py
  release_notes_clear.py
Labels: docs-approved

#16071 [TIR] New permission section and disclaimer
  Packs/ThreatIntelReports/Layouts/layoutscontainer-ThreatIntelReport-CampaignReport.json
  Packs/ThreatIntelReports/Layouts/layoutscontainer-ThreatIntelReport-ExecutiveBriefReport.json
  Packs/ThreatIntelReports/Layouts/layoutscontainer-ThreatIntelReport-MalwareReport.json
  Packs/ThreatIntelReports/Layouts/layoutscontainer-ThreatIntelReport-ThreatActorReport.json
  Packs/ThreatIntelReports/Layouts/layoutscontainer-ThreatIntelReport-VulnerabilityReport.json
  Packs/ThreatIntelReports/ReleaseNotes/1_0_4.md
  Packs/ThreatIntelReports/pack_metadata.json
Labels: docs-approved

#14990 carbon black vmware edr v2 id in quarantine request fix
  Packs/Carbon_Black_Enterprise_Response/Integrations/CarbonBlackResponseV2/CarbonBlackResponseV2.py
  Packs/Carbon_Black_Enterprise_Response/Integrations/CarbonBlackResponseV2/CarbonBlackResponseV2_test.py
  Packs/Carbon_Black_Enterprise_Response/ReleaseNotes/2_1_10.md
  Packs/Carbon_Black_Enterprise_Response/pack_metadata.json
  Tests/conf.json
Labels: docs-approved

#16073 Validate runas
  Packs/CommonScripts/.pack-ignore
  Packs/DemistoRESTAPI/.pack-ignore
  Packs/EmailCommunication/.pack-ignore
  Packs/PaloAltoNetworks_IoT/.pack-ignore
Labels: docs-approved

#15866 Splunk - Adding polling to search command
  Packs/SplunkPy/Integrations/SplunkPy/README.md
  Packs/SplunkPy/Integrations/SplunkPy/SplunkPy.py
  Packs/SplunkPy/Integrations/SplunkPy/SplunkPy.yml
  Packs/SplunkPy/Integrations/SplunkPy/SplunkPy_test.py
  Packs/SplunkPy/ReleaseNotes/2_2_7.md
  Packs/SplunkPy/ReleaseNotes/2_2_8.md
  Packs/SplunkPy/pack_metadata.json
Labels: docs-approved

#16083 added reference to pack article
  Packs/QRadar/README.md
Labels: docs-approved

#15985 xdr iocs manual sync commands
  Packs/CortexXDR/Integrations/XDR_iocs/XDR_iocs.py
  Packs/CortexXDR/Integrations/XDR_iocs/XDR_iocs.yml
  Packs/CortexXDR/Integrations/XDR_iocs/XDR_iocs_test.py
  Packs/CortexXDR/ReleaseNotes/4_2_8.md
  Packs/CortexXDR/pack_metadata.json
Labels: docs-approved

#16107 ScheduleTaskAndPoll: Update .pack-ignore
  Packs/ScheduleTaskAndPoll/.pack-ignore
Labels: docs-approved

#16108 WildFire Reports: added the agent parameter to the HTTP request
  Packs/Palo_Alto_Networks_WildFire/Integrations/WildFireReports/WildFireReports.py
  Packs/Palo_Alto_Networks_WildFire/Integrations/WildFireReports/WildFireReports.yml
  Packs/Palo_Alto_Networks_WildFire/ReleaseNotes/2_0_2.md
  Packs/Palo_Alto_Networks_WildFire/pack_metadata.json
Labels: docs-approved

#16109 Fixed an issue where it parses DT syntax.
  Packs/ExtFilter/ReleaseNotes/1_1_8.md
  Packs/ExtFilter/Scripts/ExtFilter/ExtFilter.py
  Packs/ExtFilter/Scripts/ExtFilter/ExtFilter.yml
  Packs/ExtFilter/Scripts/ExtFilter/ExtFilter_test.py
  Packs/ExtFilter/Scripts/ExtFilter/test_data/test-1.json
  Packs/ExtFilter/pack_metadata.json
Labels: Contribution, docs-approved, Contribution Form Filled, Community

#15961 Email communication reply and notes bug
  Packs/EmailCommunication/ReleaseNotes/1_4_3.md
  Packs/EmailCommunication/Scripts/SendEmailReply/SendEmailReply.py
  Packs/EmailCommunication/Scripts/SendEmailReply/SendEmailReply_test.py
  Packs/EmailCommunication/pack_metadata.json
  Packs/MicrosoftGraphListener/Integrations/MicrosoftGraphListener/MicrosoftGraphListener.py
  Packs/MicrosoftGraphListener/Integrations/MicrosoftGraphListener/MicrosoftGraphListener.yml
  Packs/MicrosoftGraphListener/Integrations/MicrosoftGraphListener/test_data/expected_incident
  Packs/MicrosoftGraphListener/ReleaseNotes/1_0_20.md
  Packs/MicrosoftGraphListener/pack_metadata.json
  Packs/MicrosoftGraphMail/Integrations/MicrosoftGraphMail/MicrosoftGraphMail.py
  Packs/MicrosoftGraphMail/Integrations/MicrosoftGraphMail/test_data/expected_incident
  Packs/MicrosoftGraphMail/ReleaseNotes/1_1_3.md
  Packs/MicrosoftGraphMail/pack_metadata.json
Labels: bug, docs-approved, release-notes-only

#16106 Added a feature to match patterns for different values of nodes.
  Packs/MapPattern/ReleaseNotes/1_0_3.md
  Packs/MapPattern/Scripts/MapPattern/MapPattern.py
  Packs/MapPattern/Scripts/MapPattern/MapPattern.yml
  Packs/MapPattern/Scripts/MapPattern/MapPattern_test.py
  Packs/MapPattern/Scripts/MapPattern/README.md
  Packs/MapPattern/Scripts/MapPattern/test_data/test-1.json
  Packs/MapPattern/pack_metadata.json
Labels: Contribution, docs-approved, Contribution Form Filled, Community

#16133 Zscaler Test - skip tpb
  Tests/conf.json
Labels: docs-approved

#16033 phishing show campaign highest severity script will show the updated highest severity
  Packs/Campaign/ReleaseNotes/3_1_4.md
  Packs/Campaign/Scripts/ShowCampaignHighestSeverity/ShowCampaignHighestSeverity.py
  Packs/Campaign/Scripts/ShowCampaignHighestSeverity/ShowCampaignHighestSeverity.yml
  Packs/Campaign/Scripts/ShowCampaignHighestSeverity/ShowCampaignHighestSeverity_test.py
  Packs/Campaign/Scripts/ShowCampaignHighestSeverity/data_test/demisto_context.json
  Packs/Campaign/Scripts/ShowCampaignHighestSeverity/data_test/get_incident.json
  Packs/Campaign/Scripts/script-ShowCampaignHighestSeverity.yml
  Packs/Campaign/pack_metadata.json
Labels: docs-approved, release-notes-only

#15911 SentinelOne V2: Changed the os_type query param to osTypes.
  Packs/SentinelOne/Integrations/SentinelOne-V2/SentinelOne-V2.py
  Packs/SentinelOne/ReleaseNotes/2_0_8.md
  Packs/SentinelOne/pack_metadata.json
Labels: docs-approved

#16090 Gib new logos
  Packs/GroupIB_ThreatIntelligenceAttribution/Integrations/GroupIBTIA/GroupIBTIA_image.png
  Packs/GroupIB_ThreatIntelligenceAttribution/Integrations/GroupIB_TIA_Feed/GroupIB_TIA_Feed_image.png
  Packs/GroupIB_ThreatIntelligenceAttribution/ReleaseNotes/1_3_3.md
  Packs/GroupIB_ThreatIntelligenceAttribution/pack_metadata.json
Labels: Contribution, Partner, Contribution Form Filled

#15838 Recorded Future Feed - Add the option to have comma-separated risk rules
  Packs/FeedRecordedFuture/Integrations/FeedRecordedFuture/FeedRecordedFuture.py
  Packs/FeedRecordedFuture/Integrations/FeedRecordedFuture/FeedRecordedFuture.yml
  Packs/FeedRecordedFuture/Integrations/FeedRecordedFuture/FeedRecordedFuture_test.py
  Packs/FeedRecordedFuture/Integrations/FeedRecordedFuture/README.md
  Packs/FeedRecordedFuture/ReleaseNotes/1_0_17.md
  Packs/FeedRecordedFuture/pack_metadata.json
  Tests/conf.json
Labels: docs-approved

#16150 Changed the fields comparison feature.
  Packs/MapPattern/ReleaseNotes/1_0_4.md
  Packs/MapPattern/Scripts/MapPattern/MapPattern.py
  Packs/MapPattern/Scripts/MapPattern/MapPattern.yml
  Packs/MapPattern/Scripts/MapPattern/MapPattern_test.py
  Packs/MapPattern/Scripts/MapPattern/README.md
  Packs/MapPattern/Scripts/MapPattern/test_data/test-1.json
  Packs/MapPattern/pack_metadata.json
Labels: Contribution, docs-approved, Contribution Form Filled, Community

#16156 Skip auto focus
  Tests/conf.json
Labels: docs-approved

#16170 Remove MITRE TPB as deprecated.
  Packs/FeedMitreAttack/.pack-ignore
  Tests/conf.json
Labels: docs-approved

#16159 demisto sdk 1.5.4
  dev-requirements-py3.txt
Labels: docs-approved

#16134 Fix ExtractIndicatorsFromWordFile - get context from incident
  Packs/CommonScripts/ReleaseNotes/1_6_4.md
  Packs/CommonScripts/Scripts/ExtractIndicatorsFromWordFile/ExtractIndicatorsFromWordFile.py
  Packs/CommonScripts/Scripts/ExtractIndicatorsFromWordFile/ExtractIndicatorsFromWordFile_test.py
  Packs/CommonScripts/Scripts/ExtractIndicatorsFromWordFile/Pipfile
  Packs/CommonScripts/Scripts/ExtractIndicatorsFromWordFile/Pipfile.lock
  Packs/CommonScripts/pack_metadata.json
Labels: bug, docs-approved, release-notes-only

#15873 Armorblox Cortex Integration
  Packs/Armorblox/.pack-ignore
  Packs/Armorblox/.secrets-ignore
  Packs/Armorblox/Author_image.png
  Packs/Armorblox/Classifiers/classifier-Armorblox_-_Classifier.json
  Packs/Armorblox/Classifiers/classifier-Armorblox_-_Mapper.json
  Packs/Armorblox/IncidentFields/incidentfield-Armorblox_Incident_Id.json
  Packs/Armorblox/IncidentFields/incidentfield-Armorblox_Policy_Names.json
  Packs/Armorblox/IncidentFields/incidentfield-Armorblox_Remediation_Actions.json
  Packs/Armorblox/IncidentFields/incidentfield-Armorblox_Resolution_State.json
  Packs/Armorblox/IncidentFields/incidentfield-Armorblox_Subject.json
  Packs/Armorblox/IncidentTypes/incidenttype-Armorblox.json
  Packs/Armorblox/IncidentTypes/incidenttype-Armorblox_Abuse_Mailbox_Report.json
  Packs/Armorblox/IncidentTypes/incidenttype-Armorblox_Inbound_Threat.json
  Packs/Armorblox/IncidentTypes/incidenttype-Armorblox_Outbound_Threat.json
  Packs/Armorblox/Integrations/Armorblox/Armorblox.py
  Packs/Armorblox/Integrations/Armorblox/Armorblox.yml
  Packs/Armorblox/Integrations/Armorblox/Armorblox_description.md
  Packs/Armorblox/Integrations/Armorblox/Armorblox_image.png
  Packs/Armorblox/Integrations/Armorblox/Armorblox_test.py
  Packs/Armorblox/Integrations/Armorblox/README.md
  Packs/Armorblox/Integrations/Armorblox/command_examples
  Packs/Armorblox/Integrations/Armorblox/test_data/test_get_incident_message_ids.json
  Packs/Armorblox/Integrations/Armorblox/test_data/test_get_incidents_list.json
  Packs/Armorblox/Integrations/Armorblox/test_data/test_get_remediation_action.json
  Packs/Armorblox/Integrations/Armorblox/test_data/test_response_fetch_incidents_command.json
  Packs/Armorblox/Integrations/Armorblox/test_data/test_response_for_6484.json
  Packs/Armorblox/Integrations/Armorblox/test_data/test_response_for_get_incidents_list.json
  Packs/Armorblox/Playbooks/Armorblox_Needs_Review.yml
  Packs/Armorblox/Playbooks/Armorblox_Needs_Review_README.md
  Packs/Armorblox/Playbooks/doc_files/Armorblox_Needs_Review.png
  Packs/Armorblox/README.md
  Packs/Armorblox/pack_metadata.json
Labels: Contribution, docs-approved, Partner, post-demo, Contribution Form Filled

#16169 PB name change in the Block IP Generic V3 playbook
  Packs/CommonPlaybooks/Playbooks/playbook-Block_IP_-_Generic_v3.yml
  Packs/CommonPlaybooks/ReleaseNotes/2_1_4.md
  Packs/CommonPlaybooks/pack_metadata.json
Labels: docs-approved

#16184 secrets detection - minor fix to url in gold
  Utils/github_workflow_scripts/run_secrets_detection_get_playbook_status.py
Labels: docs-approved

#16183 fix test-playbook command
  Packs/NetscoutAED/TestPlaybooks/NetscoutAED-Test.yml
Labels: docs-approved

#16031 Handled getting only some valid domains
  Packs/Cisco-umbrella/Integrations/Cisco-umbrella-investigate/Cisco-umbrella-investigate.py
  Packs/Cisco-umbrella/Integrations/Cisco-umbrella-investigate/Cisco-umbrella-investigate_test.py
  Packs/Cisco-umbrella/ReleaseNotes/1_0_10.md
  Packs/Cisco-umbrella/pack_metadata.json
Labels: bug, docs-approved, release-notes-only

#16079 QRadar V3 Don't continue parsing after an exception
  Packs/QRadar/Integrations/QRadar_v3/QRadar_v3.py
  Packs/QRadar/ReleaseNotes/2_1_18.md
  Packs/QRadar/pack_metadata.json
Labels: docs-approved

#16025 Add Relationships to CrowdStrike indicators
  Packs/FeedCrowdstrikeFalconIntel/Integrations/CrowdStrikeIndicatorFeed/CrowdStrikeIndicatorFeed.py
  Packs/FeedCrowdstrikeFalconIntel/Integrations/CrowdStrikeIndicatorFeed/CrowdStrikeIndicatorFeed.yml
  Packs/FeedCrowdstrikeFalconIntel/Integrations/CrowdStrikeIndicatorFeed/CrowdStrikeIndicatorFeed_test.py
  Packs/FeedCrowdstrikeFalconIntel/Integrations/CrowdStrikeIndicatorFeed/test_data/create_indicators_from_response.json
  Packs/FeedCrowdstrikeFalconIntel/ReleaseNotes/2_0_9.md
  Packs/FeedCrowdstrikeFalconIntel/pack_metadata.json
  Tests/conf.json
Labels: docs-approved

#16138 Ms 365 defender bug
  Packs/Microsoft365Defender/Integrations/Microsoft365Defender/Microsoft365Defender.py
  Packs/Microsoft365Defender/Integrations/Microsoft365Defender/test_data/raw_incident.json
  Packs/Microsoft365Defender/ReleaseNotes/2_0_3.md
  Packs/Microsoft365Defender/pack_metadata.json
Labels: bug, docs-approved, release-notes-only

#16200 remove NetscoutAED-test playbook from skipped
  Tests/conf.json
Labels: docs-approved

#16171 Xsoar playbook fixes
  Packs/FireMonSecurityManager/IncidentTypes/incidenttype-FireMonSecurityManager-FireMon_Policy_Planner.json
  Packs/FireMonSecurityManager/IncidentTypes/incidenttype-FireMonSecurityManager-FireMon_Pre_Change_Assessment.json
  Packs/FireMonSecurityManager/ReleaseNotes/1_0_2.md
  Packs/FireMonSecurityManager/pack_metadata.json
Labels: Contribution, docs-approved, Partner, Contribution Form Filled

#16204 Skip auto focus
  Tests/conf.json
Labels: docs-approved

#16207 Update GmailSingleUser README.md
  Packs/GmailSingleUser/Integrations/GmailSingleUser/README.md
Labels: docs-approved

#15907 Mail listener filters fix
  Packs/MailListener/Integrations/MailListenerV2/MailListenerV2.py
  Packs/MailListener/Integrations/MailListenerV2/MailListenerV2.yml
  Packs/MailListener/Integrations/MailListenerV2/MailListenerV2_test.py
  Packs/MailListener/ReleaseNotes/1_0_7.md
  Packs/MailListener/pack_metadata.json
Labels: bug, docs-approved, release-notes-only

#16213 updated the demistomock module
  Tests/demistomock/demistomock.py
Labels: docs-approved

#16206 Fix test playbook- Tanium TR v2
  Packs/TaniumThreatResponse/TestPlaybooks/playbook-Tanium_Threat_Response_V2_Test.yml
  Tests/conf.json
Labels: docs-approved

#15603 Azure DevOps integration
  Packs/AzureDevOps/.pack-ignore
  Packs/AzureDevOps/.secrets-ignore
  Packs/AzureDevOps/Classifiers/classifier-AzureDevOps.json
  Packs/AzureDevOps/Classifiers/classifier-mapper-incoming-AzureDevOps.json
  Packs/AzureDevOps/Classifiers/classifier-mapper-outgoing-AzureDevOps.json
  Packs/AzureDevOps/IncidentFields/incident-AzureDevOps_Project_ID.json
  Packs/AzureDevOps/IncidentFields/incident-AzureDevOps_Project_Name.json
  Packs/AzureDevOps/IncidentFields/incident-AzureDevOps_Pull_Request_ID.json
  Packs/AzureDevOps/IncidentFields/incident-AzureDevOps_Repository_ID.json
  Packs/AzureDevOps/IncidentFields/incident-AzureDevOps_Repository_Name.json
  Packs/AzureDevOps/IncidentFields/incident-AzureDevOps_Status.json
  Packs/AzureDevOps/IncidentTypes/incidenttype-AzureDevOps_Incident.json
  Packs/AzureDevOps/Integrations/AzureDevOps/AzureDevOps.py
  Packs/AzureDevOps/Integrations/AzureDevOps/AzureDevOps.yml
  Packs/AzureDevOps/Integrations/AzureDevOps/AzureDevOps_description.md
  Packs/AzureDevOps/Integrations/AzureDevOps/AzureDevOps_image.png
  Packs/AzureDevOps/Integrations/AzureDevOps/AzureDevOps_test.py
  Packs/AzureDevOps/Integrations/AzureDevOps/README.md
  Packs/AzureDevOps/Integrations/AzureDevOps/test_data/add_user.json
  Packs/AzureDevOps/Integrations/AzureDevOps/test_data/add_user_error.json
  Packs/AzureDevOps/Integrations/AzureDevOps/test_data/branch_list.json
  Packs/AzureDevOps/Integrations/AzureDevOps/test_data/get_pipeline_run.json
  Packs/AzureDevOps/Integrations/AzureDevOps/test_data/list_project.json
  Packs/AzureDevOps/Integrations/AzureDevOps/test_data/list_pull_request.json
  Packs/AzureDevOps/Integrations/AzureDevOps/test_data/list_repositories.json
  Packs/AzureDevOps/Integrations/AzureDevOps/test_data/pipeline_list.json
  Packs/AzureDevOps/Integrations/AzureDevOps/test_data/pipeline_run_list.json
  Packs/AzureDevOps/Integrations/AzureDevOps/test_data/pull_request.json
  Packs/AzureDevOps/Integrations/AzureDevOps/test_data/query_user.json
  Packs/AzureDevOps/Integrations/AzureDevOps/test_data/run_pipeline.json
  Packs/AzureDevOps/Layouts/layoutscontainer-AzureDevOps_Layout.json
  Packs/AzureDevOps/Playbooks/Azure-DevOps-Pipeline-Run.yml
  Packs/AzureDevOps/README.md
  Packs/AzureDevOps/TestPlaybooks/playbook-AzureDevOps-Test.yml
  Packs/AzureDevOps/pack_metadata.json
  Tests/conf.json
Labels: Contribution, docs-approved, Contribution Form Filled

#15626 Init Azure Data Explorer PR
  Packs/AzureDataExplorer/.pack-ignore
  Packs/AzureDataExplorer/.secrets-ignore
  Packs/AzureDataExplorer/Integrations/AzureDataExplorer/AzureDataExplorer.py
  Packs/AzureDataExplorer/Integrations/AzureDataExplorer/AzureDataExplorer.yml
  Packs/AzureDataExplorer/Integrations/AzureDataExplorer/AzureDataExplorer_description.md
  Packs/AzureDataExplorer/Integrations/AzureDataExplorer/AzureDataExplorer_image.png
  Packs/AzureDataExplorer/Integrations/AzureDataExplorer/AzureDataExplorer_test.py
  Packs/AzureDataExplorer/Integrations/AzureDataExplorer/README.md
  Packs/AzureDataExplorer/Integrations/AzureDataExplorer/test_data/cancel_query.json
  Packs/AzureDataExplorer/Integrations/AzureDataExplorer/test_data/cancel_query_reason.json
  Packs/AzureDataExplorer/Integrations/AzureDataExplorer/test_data/execute_query.json
  Packs/AzureDataExplorer/Integrations/AzureDataExplorer/test_data/list_completed_queries.json
  Packs/AzureDataExplorer/Integrations/AzureDataExplorer/test_data/list_running_queries.json
  Packs/AzureDataExplorer/Pipfile
  Packs/AzureDataExplorer/README.md
  Packs/AzureDataExplorer/TestPlaybooks/playbook-AzureDataExplorer-Test.yml
  Packs/AzureDataExplorer/pack_metadata.json
  Tests/conf.json
Labels: Contribution

#16141 Add FormattedDateToEpoch work without foramtter argument
  Packs/CommonScripts/ReleaseNotes/1_6_5.md
  Packs/CommonScripts/Scripts/FormattedDateToEpoch/FormattedDateToEpoch.py
  Packs/CommonScripts/Scripts/FormattedDateToEpoch/FormattedDateToEpoch.yml
  Packs/CommonScripts/Scripts/FormattedDateToEpoch/FormattedDateToEpoch_test.py
  Packs/CommonScripts/TestPlaybooks/playbook-FormattedDateToEpochTest.yml
  Packs/CommonScripts/pack_metadata.json
Labels: docs-approved

#16191 Msgraph list attachments - handle attachment without a name
  Packs/MicrosoftGraphMail/Integrations/MicrosoftGraphMail/MicrosoftGraphMail.py
  Packs/MicrosoftGraphMail/Integrations/MicrosoftGraphMail/MicrosoftGraphMail_test.py
  Packs/MicrosoftGraphMail/Integrations/MicrosoftGraphMail/test_data/list_attachment_result.json
  Packs/MicrosoftGraphMail/Integrations/MicrosoftGraphMail/test_data/list_attachment_result_no_name.json
  Packs/MicrosoftGraphMail/ReleaseNotes/1_1_4.md
  Packs/MicrosoftGraphMail/pack_metadata.json
Labels: docs-approved

#15956 added new script QRadarCreateAQLQuery
  Packs/QRadar/ReleaseNotes/2_1_19.md
  Packs/QRadar/Scripts/QRadarCreateAQLQuery/QRadarCreateAQLQuery.py
  Packs/QRadar/Scripts/QRadarCreateAQLQuery/QRadarCreateAQLQuery.yml
  Packs/QRadar/Scripts/QRadarCreateAQLQuery/QRadarCreateAQLQuery_test.py
  Packs/QRadar/Scripts/QRadarCreateAQLQuery/README.md
  Packs/QRadar/pack_metadata.json
Labels: docs-approved

#15836 Campaign set incident with elevated permissions
  Packs/Campaign/ReleaseNotes/3_1_5.md
  Packs/Campaign/Scripts/SetPhishingCampaignDetails/SetPhishingCampaignDetails.py
  Packs/Campaign/Scripts/SetPhishingCampaignDetails/SetPhishingCampaignDetails.yml
  Packs/Campaign/Scripts/SetPhishingCampaignDetails/SetPhishingCampaignDetails_test.py
  Packs/Campaign/Scripts/SetPhishingCampaignDetails/test_data/campaign_data.py
  Packs/Campaign/pack_metadata.json
Labels: docs-approved

#15963 parseEmailFiles_ownership
  .github/CODEOWNERS
Labels: docs-approved

#16235 Added the request a private offer button
  Images/request_private_offer_button.png
Labels: docs-approved

#16233 Micro Focus Service Manager - Added documentation
  Packs/HPE_Service_Manager/Integrations/README.md
Labels: docs-approved

#16238 add ignore of dbotRole in SetCampaignDetails
  Packs/Campaign/.pack-ignore
Labels: docs-approved

#16205 [greynoise-266] Fix bug that broke compatibility with pre-6.1 versions
  Packs/GreyNoise/Integrations/GreyNoise/GreyNoise.py
  Packs/GreyNoise/Integrations/GreyNoise_Community/GreyNoise_Community.py
  Packs/GreyNoise/ReleaseNotes/1_1_1.md
  Packs/GreyNoise/pack_metadata.json
Labels: Contribution, Partner, Contribution Form Filled

#16212 ValidateContent: updated script for latest sdk version (1.5.4)
  Packs/Base/ReleaseNotes/1_16_5.md
  Packs/Base/Scripts/ValidateContent/ValidateContent.py
  Packs/Base/Scripts/ValidateContent/ValidateContent.yml
  Packs/Base/Scripts/ValidateContent/ValidateContent_test.py
  Packs/Base/pack_metadata.json
Labels: bug, docs-approved

#16045 Email communication image bug
  Packs/EmailCommunication/ReleaseNotes/1_4_4.md
  Packs/EmailCommunication/Scripts/DisplayEmailHtml/DisplayEmailHtml.py
  Packs/EmailCommunication/Scripts/DisplayEmailHtml/DisplayEmailHtml.yml
  Packs/EmailCommunication/Scripts/DisplayEmailHtml/DisplayEmailHtml_test.py
  Packs/EmailCommunication/Scripts/PreprocessEmail/PreprocessEmail.py
  Packs/EmailCommunication/Scripts/PreprocessEmail/PreprocessEmail_test.py
  Packs/EmailCommunication/pack_metadata.json
  Packs/MicrosoftGraphListener/Integrations/MicrosoftGraphListener/MicrosoftGraphListener.py
  Packs/MicrosoftGraphListener/ReleaseNotes/1_0_21.md
  Packs/MicrosoftGraphListener/pack_metadata.json
  Packs/MicrosoftGraphMail/Integrations/MicrosoftGraphMail/MicrosoftGraphMail.py
  Packs/MicrosoftGraphMail/ReleaseNotes/1_1_5.md
  Packs/MicrosoftGraphMail/pack_metadata.json
Labels: bug, docs-approved, release-notes-only

#15804 OpsGenie
  Packs/CommonTypes/.pack-ignore
  Packs/CommonTypes/IncidentFields/incidentfield-Alert_Acknowledgement.json
  Packs/CommonTypes/IncidentFields/incidentfield-Alert_Source.json
  Packs/CommonTypes/IncidentFields/incidentfield-Last_Seen.json
  Packs/CommonTypes/IncidentFields/incidentfield-Last_Update_Time.json
  Packs/CommonTypes/IncidentFields/incidentfield-Source_Priority.json
  Packs/CommonTypes/IncidentFields/incidentfield-Source_Status.json
  Packs/CommonTypes/IncidentFields/incidentfield-Title.json
  Packs/CommonTypes/ReleaseNotes/3_1_28.md
  Packs/CommonTypes/pack_metadata.json
  Packs/OpsGenie/.secrets-ignore
  Packs/OpsGenie/Classifiers/classifier-OpsGenie_-_Classifier.json
  Packs/OpsGenie/Classifiers/classifier-OpsGenie_-_Mapper.json
  Packs/OpsGenie/IncidentFields/incidentfield-OpsGenie_Alias.json
  Packs/OpsGenie/IncidentFields/incidentfield-OpsGenie_Count_Linked_Alerts.json
  Packs/OpsGenie/IncidentFields/incidentfield-OpsGenie_Responder.json
  Packs/OpsGenie/IncidentFields/incidentfield-OpsGenie_TinyId.json
  Packs/OpsGenie/IncidentTypes/incidenttype-OpsGenie_Alert.json
  Packs/OpsGenie/IncidentTypes/incidenttype-OpsGenie_Incident.json
  Packs/OpsGenie/Integrations/OpsGenieV3/OpsGenieV3.py
  Packs/OpsGenie/Integrations/OpsGenieV3/OpsGenieV3.yml
  Packs/OpsGenie/Integrations/OpsGenieV3/OpsGenieV3_description.md
  Packs/OpsGenie/Integrations/OpsGenieV3/OpsGenieV3_image.png
  Packs/OpsGenie/Integrations/OpsGenieV3/OpsGenieV3_test.py
  Packs/OpsGenie/Integrations/OpsGenieV3/Pipfile
  Packs/OpsGenie/Integrations/OpsGenieV3/Pipfile.lock
  Packs/OpsGenie/Integrations/OpsGenieV3/README.md
  Packs/OpsGenie/Integrations/OpsGenieV3/command_examples.txt
  Packs/OpsGenie/Integrations/OpsGenieV3/test_data/ack_alert.json
  Packs/OpsGenie/Integrations/OpsGenieV3/test_data/add_alert_tag.json
  Packs/OpsGenie/Integrations/OpsGenieV3/test_data/add_responder_alert.json
  Packs/OpsGenie/Integrations/OpsGenieV3/test_data/add_responder_incident.json
  Packs/OpsGenie/Integrations/OpsGenieV3/test_data/add_tag_incident.json
  Packs/OpsGenie/Integrations/OpsGenieV3/test_data/assign_alert.json
  Packs/OpsGenie/Integrations/OpsGenieV3/test_data/close_alert.json
  Packs/OpsGenie/Integrations/OpsGenieV3/test_data/close_incident.json
  Packs/OpsGenie/Integrations/OpsGenieV3/test_data/create_alert.json
  Packs/OpsGenie/Integrations/OpsGenieV3/test_data/create_incident.json
  Packs/OpsGenie/Integrations/OpsGenieV3/test_data/delete_alert.json
  Packs/OpsGenie/Integrations/OpsGenieV3/test_data/delete_incident.json
  Packs/OpsGenie/Integrations/OpsGenieV3/test_data/empty_response.json
  Packs/OpsGenie/Integrations/OpsGenieV3/test_data/escalate_alert.json
  Packs/OpsGenie/Integrations/OpsGenieV3/test_data/get_alert_attachments.json
  Packs/OpsGenie/Integrations/OpsGenieV3/test_data/get_alerts.json
  Packs/OpsGenie/Integrations/OpsGenieV3/test_data/get_alerts_without_next.json
  Packs/OpsGenie/Integrations/OpsGenieV3/test_data/get_escalations.json
  Packs/OpsGenie/Integrations/OpsGenieV3/test_data/get_incidents.json
  Packs/OpsGenie/Integrations/OpsGenieV3/test_data/get_incidents_without_next.json
  Packs/OpsGenie/Integrations/OpsGenieV3/test_data/get_request.json
  Packs/OpsGenie/Integrations/OpsGenieV3/test_data/get_teams.json
  Packs/OpsGenie/Integrations/OpsGenieV3/test_data/remove_alert_tag.json
  Packs/OpsGenie/Integrations/OpsGenieV3/test_data/remove_tag_incident.json
  Packs/OpsGenie/Integrations/OpsGenieV3/test_data/request.json
  Packs/OpsGenie/Integrations/OpsGenieV3/test_data/resolve_incident.json
  Packs/OpsGenie/Integrations/integration-OpsGenie.yml
  Packs/OpsGenie/README.md
  Packs/OpsGenie/ReleaseNotes/2_0_0.md
  Packs/OpsGenie/TestPlaybooks/playbook-OpsGenieV3-Test.yml
  Packs/OpsGenie/pack_metadata.json
  Tests/conf.json
Labels: docs-approved

#16068 Ms graph list members bug fix
  Packs/MicrosoftGraphGroups/Integrations/MicrosoftGraphGroups/MicrosoftGraphGroups.py
  Packs/MicrosoftGraphGroups/Integrations/MicrosoftGraphGroups/MicrosoftGraphGroups.yml
  Packs/MicrosoftGraphGroups/Integrations/MicrosoftGraphGroups/MicrosoftGraphGroups_test.py
  Packs/MicrosoftGraphGroups/Integrations/MicrosoftGraphGroups/test_data/response_constants.py
  Packs/MicrosoftGraphGroups/Integrations/MicrosoftGraphGroups/test_data/result_constants.py
  Packs/MicrosoftGraphGroups/ReleaseNotes/1_0_12.md
  Packs/MicrosoftGraphGroups/pack_metadata.json
Labels: bug, content, docs-approved, release-notes-only

#16201 update base pack sane reports
  Packs/Base/ReleaseNotes/1_16_6.md
  Packs/Base/Scripts/SanePdfReport/SanePdfReport.yml
  Packs/Base/pack_metadata.json
Labels: docs-approved

#16253 SDK update in requirements
  dev-requirements-py3.txt
Labels: docs-approved

#15864 AzureSC - Securescore Command
  Packs/AzureSecurityCenter/Integrations/AzureSecurityCenter_v2/AzureSecurityCenter_v2.py
  Packs/AzureSecurityCenter/Integrations/AzureSecurityCenter_v2/AzureSecurityCenter_v2.yml
  Packs/AzureSecurityCenter/Integrations/AzureSecurityCenter_v2/AzureSecurityCenter_v2_test.py
  Packs/AzureSecurityCenter/Integrations/AzureSecurityCenter_v2/README.md
  Packs/AzureSecurityCenter/ReleaseNotes/1_2_0.md
  Packs/AzureSecurityCenter/TestPlaybooks/playbook-AzureSCTestPlaybook.yml
  Packs/AzureSecurityCenter/pack_metadata.json
Labels: Contribution, docs-approved

#16232 [195-sixgill] update names and images
  Packs/Cybersixgill-DVE/Author_image.png
  Packs/Cybersixgill-DVE/Integrations/CybersixgillDVEEnrichment/CybersixgillDVEEnrichment_image.png
  Packs/Cybersixgill-DVE/Integrations/CybersixgillDVEFeed/CybersixgillDVEFeed_image.png
  Packs/Cybersixgill-DVE/ReleaseNotes/1_0_2.md
  Packs/Cybersixgill-DVE/pack_metadata.json
  Packs/Sixgill-Darkfeed/Author_image.png
  Packs/Sixgill-Darkfeed/Integrations/SixgillDVEFeed/SixgillDVEFeed_image.png
  Packs/Sixgill-Darkfeed/Integrations/Sixgill_Darkfeed/Sixgill_Darkfeed_image.png
  Packs/Sixgill-Darkfeed/Integrations/Sixgill_Darkfeed_Enrichment/Sixgill_Darkfeed_Enrichment_image.png
  Packs/Sixgill-Darkfeed/ReleaseNotes/2_0_7.md
  Packs/Sixgill-Darkfeed/pack_metadata.json
Labels: Contribution, docs-approved, Partner, Contribution Form Filled

#16221 [Cofense-32] Fixed issue of indicator field type
  Packs/FeedCofense/IndicatorFields/incidentfield-Cofense-Threat-ID.json
  Packs/FeedCofense/Integrations/FeedCofense/FeedCofense.py
  Packs/FeedCofense/Integrations/FeedCofense/FeedCofense_test.py
  Packs/FeedCofense/Integrations/FeedCofense/test_data/fetch_indicators.json
  Packs/FeedCofense/Integrations/FeedCofense/test_data/search_output.json
  Packs/FeedCofense/ReleaseNotes/1_1_1.md
  Packs/FeedCofense/pack_metadata.json
Labels: Contribution, Partner, Contribution Form Filled

#16219 Unit42 ATOMs fix get-indicators command
  Packs/FeedUnit42v2/Integrations/FeedUnit42v2/FeedUnit42v2.py
  Packs/FeedUnit42v2/ReleaseNotes/1_0_6.md
  Packs/FeedUnit42v2/pack_metadata.json
Labels: docs-approved

#16277 update demisto-sdk
  dev-requirements-py3.txt
Labels: docs-approved

#13263 O365 - support GCC High Endpoint
  Packs/ApiModules/Scripts/MicrosoftApiModule/MicrosoftApiModule.py
  Packs/ApiModules/Scripts/MicrosoftApiModule/MicrosoftApiModule_test.py
  Packs/MicrosoftGraphMail/Integrations/MicrosoftGraphMail/MicrosoftGraphMail.py
  Packs/MicrosoftGraphMail/Integrations/MicrosoftGraphMail/MicrosoftGraphMail_description.md
  Packs/MicrosoftGraphMail/Integrations/MicrosoftGraphMail/MicrosoftGraphMail_test.py
  Packs/MicrosoftGraphMail/Integrations/MicrosoftGraphMail/README.md
  Packs/MicrosoftGraphMail/ReleaseNotes/1_1_6.md
  Packs/MicrosoftGraphMail/pack_metadata.json
Labels: docs-approved

#16276 Remove Redundant File
  Packs/CiscoWSA/Integrations/CiscoWSA/Test/id_set.json
Labels: docs-approved

#16239 HashiCorp Vault - add the folder arg to the configure-engine cmd
  Packs/HashiCorp-Vault/Integrations/HashiCorpVault/HashiCorpVault.py
  Packs/HashiCorp-Vault/Integrations/HashiCorpVault/HashiCorpVault.yml
  Packs/HashiCorp-Vault/Integrations/HashiCorpVault/README.md
  Packs/HashiCorp-Vault/ReleaseNotes/1_0_6.md
  Packs/HashiCorp-Vault/pack_metadata.json
Labels: docs-approved

#16274 Fixed README file name
  Packs/HPE_Service_Manager/Integrations/integration-HPE_Service_Manager_README.md
Labels: docs-approved

#16286 Tanium - change http method to post on login
  Packs/Tanium/Integrations/Tanium_v2/Tanium_v2.py
  Packs/Tanium/Integrations/Tanium_v2/Tanium_v2_test.py
  Packs/Tanium/ReleaseNotes/1_0_13.md
  Packs/Tanium/pack_metadata.json
  Packs/TaniumThreatResponse/Integrations/TaniumThreatResponse/TaniumThreatResponse.py
  Packs/TaniumThreatResponse/Integrations/TaniumThreatResponseV2/TaniumThreatResponseV2.py
  Packs/TaniumThreatResponse/Integrations/TaniumThreatResponseV2/TaniumThreatResponseV2_test.py
  Packs/TaniumThreatResponse/ReleaseNotes/2_0_5.md
  Packs/TaniumThreatResponse/pack_metadata.json
Labels: docs-approved

#16288 Rapid breach response log4j pack
  Packs/CVE_2021_44228/.pack-ignore
  Packs/CVE_2021_44228/.secrets-ignore
  Packs/CVE_2021_44228/Playbooks/playbook-CVE-2021-44228_-_Log4j_RCE.yml
  Packs/CVE_2021_44228/Playbooks/playbook-CVE-2021-44228_-_Log4j_RCE_README.md
  Packs/CVE_2021_44228/README.md
  Packs/CVE_2021_44228/doc_files/CVE-2021-44228_-_Log4j_RCE.png
  Packs/CVE_2021_44228/pack_metadata.json
  Packs/MajorBreachesInvestigationandResponse/Playbooks/playbook-Rapid_Breach_Response_-_Set_Incident_Info.yml
  Packs/MajorBreachesInvestigationandResponse/ReleaseNotes/1_6_21.md
  Packs/MajorBreachesInvestigationandResponse/pack_metadata.json
Labels: docs-approved

#16299 CVE-2021-44228 enhancement
  Packs/CVE_2021_44228/Playbooks/playbook-CVE-2021-44228_-_Log4j_RCE.yml
  Packs/CVE_2021_44228/Playbooks/playbook-CVE-2021-44228_-_Log4j_RCE_README.md
  Packs/CVE_2021_44228/README.md
  Packs/CVE_2021_44228/ReleaseNotes/1_0_1.md
  Packs/CVE_2021_44228/doc_files/CVE-2021-44228_-_Log4j_RCE.png
  Packs/CVE_2021_44228/pack_metadata.json
Labels: docs-approved

#16131 GetStringDistance
  Packs/CommonScripts/ReleaseNotes/1_6_6.md
  Packs/CommonScripts/Scripts/GetStringsDistance/GetStringsDistance.py
  Packs/CommonScripts/Scripts/GetStringsDistance/GetStringsDistance.yml
  Packs/CommonScripts/Scripts/GetStringsDistance/README.md
  Packs/CommonScripts/Scripts/script-GetStringsDistance.yml
  Packs/CommonScripts/TestPlaybooks/playbook-GetStringsDistance_Test.yml
  Packs/CommonScripts/pack_metadata.json
  Tests/conf.json
Labels: docs-approved

#16325 Update README.md
  Packs/SplunkPy/Integrations/SplunkPy/README.md
Labels: docs-approved

#16186 Parse email files time out
  Packs/CommonScripts/ReleaseNotes/1_6_7.md
  Packs/CommonScripts/Scripts/ParseEmailFiles/ParseEmailFiles.py
  Packs/CommonScripts/Scripts/ParseEmailFiles/ParseEmailFiles_test.py
  Packs/CommonScripts/Scripts/ParseEmailFiles/test_data/Unknown_encode_attachment_name.eml
  Packs/CommonScripts/pack_metadata.json
Labels: bug, docs-approved, release-notes-only

#16151 Added associateIndicatorsToIncident ecxecution to GetCampaignIndicatorsByIncidentId script
  Packs/Campaign/ReleaseNotes/3_1_6.md
  Packs/Campaign/Scripts/GetCampaignIndicatorsByIncidentId/GetCampaignIndicatorsByIncidentId.py
  Packs/Campaign/Scripts/GetCampaignIndicatorsByIncidentId/GetCampaignIndicatorsByIncidentId.yml
  Packs/Campaign/Scripts/GetCampaignIndicatorsByIncidentId/GetCampaignIndicatorsByIncidentId_test.py
  Packs/Campaign/pack_metadata.json
Labels: docs-approved, release-notes-only

#16262 Update services list options in Azure feed
  Packs/FeedAzure/Integrations/FeedAzure/FeedAzure.yml
  Packs/FeedAzure/ReleaseNotes/1_0_11.md
  Packs/FeedAzure/pack_metadata.json
Labels: docs-approved

#16333 Incident field 'TotalIndicatorsCount' fromversion fix
  Packs/MajorBreachesInvestigationandResponse/IncidentFields/incidentfield-Total_Indicator_Count.json
  Packs/MajorBreachesInvestigationandResponse/ReleaseNotes/1_6_22.md
  Packs/MajorBreachesInvestigationandResponse/pack_metadata.json
Labels: docs-approved

#16326 Log4j pack enhancements
  Packs/CVE_2021_44228/Playbooks/playbook-CVE-2021-44228_-_Log4j_RCE.yml
  Packs/CVE_2021_44228/Playbooks/playbook-CVE-2021-44228_-_Log4j_RCE_README.md
  Packs/CVE_2021_44228/README.md
  Packs/CVE_2021_44228/ReleaseNotes/1_0_2.md
  Packs/CVE_2021_44228/doc_files/CVE-2021-44228_-_Log4j_RCE.png
  Packs/CVE_2021_44228/pack_metadata.json
Labels: docs-approved

#15716 Syslog rewrite
  Packs/Syslog/Integrations/Syslogv2/README.md
  Packs/Syslog/Integrations/Syslogv2/Syslogv2.py
  Packs/Syslog/Integrations/Syslogv2/Syslogv2.yml
  Packs/Syslog/Integrations/Syslogv2/Syslogv2_description.md
  Packs/Syslog/Integrations/Syslogv2/Syslogv2_image.png
  Packs/Syslog/Integrations/Syslogv2/Syslogv2_test.py
  Packs/Syslog/Integrations/Syslogv2/test_data/long_running_loop_data.json
  Packs/Syslog/Integrations/Syslogv2/test_data/rfc_test_data.json
  Packs/Syslog/ReleaseNotes/2_0_0.md
  Packs/Syslog/pack_metadata.json
Labels: docs-approved

#16202 Handled feed tags and added timeout parameter
  Packs/FeedMISP/Integrations/FeedMISP/FeedMISP.py
  Packs/FeedMISP/Integrations/FeedMISP/FeedMISP.yml
  Packs/FeedMISP/Integrations/FeedMISP/README.md
  Packs/FeedMISP/ReleaseNotes/1_0_3.md
  Packs/FeedMISP/pack_metadata.json
Labels: docs-approved

#16341 Update demisto sdk
  dev-requirements-py3.txt
Labels: docs-approved

#16242 Deprecate Xpanse Behavior commands
  Packs/ExpanseV2/Integrations/ExpanseV2/ExpanseV2.py
  Packs/ExpanseV2/Integrations/ExpanseV2/ExpanseV2.yml
  Packs/ExpanseV2/Integrations/ExpanseV2/ExpanseV2_test.py
  Packs/ExpanseV2/Integrations/ExpanseV2/README.md
  Packs/ExpanseV2/Integrations/ExpanseV2/test_data/expanse_get_risky_flows.json
  Packs/ExpanseV2/Integrations/ExpanseV2/test_data/expanse_list_risk_rules.json
  Packs/ExpanseV2/Playbooks/playbook-Handle_Expanse_Incident.yml
  Packs/ExpanseV2/Playbooks/playbook-Handle_Expanse_Incident_-_Attribution_Only.yml
  Packs/ExpanseV2/Playbooks/playbook-Handle_Expanse_Incident_-_Attribution_Only_README.md
  Packs/ExpanseV2/Playbooks/playbook-Handle_Expanse_Incident_README.md
  Packs/ExpanseV2/ReleaseNotes/1_10_0.json
  Packs/ExpanseV2/ReleaseNotes/1_10_0.md
  Packs/ExpanseV2/pack_metadata.json
Labels: docs-approved, release-notes-only

#16344 Phishing Campaign - reverting changes from 3.1.7
  Packs/Campaign/Layouts/layoutscontainer-Phishing_Campaign.json
  Packs/Campaign/Playbooks/Detect_&_Manage_Phishing_Campaigns.yml
  Packs/Campaign/Playbooks/Detect_&_Manage_Phishing_Campaigns_README.md
  Packs/Campaign/ReleaseNotes/3_1_8.md
  Packs/Campaign/doc_files/Detect_&_Manage_Phishing_Campaigns.png
  Packs/Campaign/pack_metadata.json
Labels: docs-approved

#15632 Update README.md
  Packs/GuardiCore/.secrets-ignore
  Packs/GuardiCore/README.md
Labels: Contribution, docs-approved, Partner, Contribution Form Filled

#16338 Update README.md
  Packs/Humio/README.md
Labels: Contribution, docs-approved, Contribution Form Filled

#16355 PositiveDetectionsVSDetectionEngines: Fix console issue
  Packs/CommonScripts/ReleaseNotes/1_6_8.md
  Packs/CommonScripts/Scripts/PositiveDetectionsVSDetectionEngines/PositiveDetectionsVSDetectionEngines.py
  Packs/CommonScripts/Scripts/PositiveDetectionsVSDetectionEngines/PositiveDetectionsVSDetectionEngines.yml
  Packs/CommonScripts/pack_metadata.json
Labels: docs-approved

#16357 Update on-push.yml
  .gitlab/ci/on-push.yml
Labels: docs-approved

#16001 add array support to several blacklist ip commands
  Packs/F5Silverline/Integrations/F5Silverline/F5Silverline.py
  Packs/F5Silverline/Integrations/F5Silverline/F5Silverline.yml
  Packs/F5Silverline/Integrations/F5Silverline/F5Silverline_test.py
  Packs/F5Silverline/Integrations/F5Silverline/README.md
  Packs/F5Silverline/ReleaseNotes/1_0_6.md
  Packs/F5Silverline/pack_metadata.json
  Packs/SignalSciences/Integrations/SignalSciences/README.md
  Packs/SignalSciences/Integrations/SignalSciences/SignalSciences.py
  Packs/SignalSciences/Integrations/SignalSciences/SignalSciences.yml
  Packs/SignalSciences/ReleaseNotes/1_0_7.md
  Packs/SignalSciences/TestPlaybooks/playbook-SignalSciencesTest.yml
  Packs/SignalSciences/pack_metadata.json
  Packs/ThreatX/Integrations/ThreatX/README.md
  Packs/ThreatX/Integrations/ThreatX/ThreatX.py
  Packs/ThreatX/Integrations/ThreatX/ThreatX.yml
  Packs/ThreatX/Integrations/ThreatX/ThreatX_test.py
  Packs/ThreatX/ReleaseNotes/1_0_6.md
  Packs/ThreatX/pack_metadata.json
Labels: docs-approved, release-notes-only

#16257 Update display name and readme's to Unit 42
  Packs/CommonWidgets/ReleaseNotes/1_2_3.md
  Packs/CommonWidgets/Widgets/widget-Unit42_Blog_Feed.json
  Packs/CommonWidgets/pack_metadata.json
  Packs/FeedUnit42v2/Integrations/FeedUnit42v2/FeedUnit42v2.yml
  Packs/FeedUnit42v2/Integrations/FeedUnit42v2/FeedUnit42v2_description.md
  Packs/FeedUnit42v2/Integrations/FeedUnit42v2/README.md
  Packs/FeedUnit42v2/README.md
  Packs/FeedUnit42v2/ReleaseNotes/1_0_7.md
  Packs/FeedUnit42v2/pack_metadata.json
Labels: docs-approved

#16196 Allow clear fields in ServiceNow tickets/records
  Packs/ServiceNow/Integrations/ServiceNowv2/README.md
  Packs/ServiceNow/Integrations/ServiceNowv2/ServiceNowv2.py
  Packs/ServiceNow/Integrations/ServiceNowv2/ServiceNowv2.yml
  Packs/ServiceNow/Integrations/ServiceNowv2/ServiceNowv2_test.py
  Packs/ServiceNow/ReleaseNotes/2_2_16.md
  Packs/ServiceNow/pack_metadata.json
Labels: docs-approved

#16363 Tanium tr test failure
  Packs/TaniumThreatResponse/TestPlaybooks/playbook-Tanium_Threat_Response_V2_Test.yml
Labels: docs-approved

#16230 Added outputs to jira-get-issue command
  Packs/Jira/Integrations/JiraV2/JiraV2.py
  Packs/Jira/Integrations/JiraV2/JiraV2.yml
  Packs/Jira/Integrations/JiraV2/JiraV2_test.py
  Packs/Jira/Integrations/JiraV2/README.md
  Packs/Jira/Integrations/JiraV2/test_data/expected_results.py
  Packs/Jira/Integrations/JiraV2/test_data/raw_response.py
  Packs/Jira/ReleaseNotes/1_4_3.md
  Packs/Jira/pack_metadata.json
Labels: docs-approved

#16211 Deprecate PANW Traps
  Packs/Traps/Integrations/PaloAltoNetworks_Traps/PaloAltoNetworks_Traps.yml
  Packs/Traps/Integrations/PaloAltoNetworks_Traps/PaloAltoNetworks_Traps_description.md
  Packs/Traps/Integrations/PaloAltoNetworks_Traps/README.md
  Packs/Traps/ReleaseNotes/1_0_7.md
  Packs/Traps/pack_metadata.json
  Tests/conf.json
Labels: docs-approved

#16278 Mail listener - fixed escaping
  Packs/MailListener/Integrations/MailListenerV2/MailListenerV2.py
  Packs/MailListener/Integrations/MailListenerV2/MailListenerV2.yml
  Packs/MailListener/Integrations/MailListenerV2/MailListenerV2_test.py
  Packs/MailListener/ReleaseNotes/1_0_8.md
  Packs/MailListener/pack_metadata.json
Labels: docs-approved

#16345 Fix set phisihing details
  Packs/Campaign/ReleaseNotes/3_1_9.md
  Packs/Campaign/Scripts/SetPhishingCampaignDetails/SetPhishingCampaignDetails.py
  Packs/Campaign/Scripts/SetPhishingCampaignDetails/SetPhishingCampaignDetails_test.py
  Packs/Campaign/pack_metadata.json
Labels: docs-approved

#16385 RSSWidget: fix entries order
  Packs/CommonWidgets/ReleaseNotes/1_2_4.md
  Packs/CommonWidgets/Scripts/RSSWidget/RSSWidget.py
  Packs/CommonWidgets/Scripts/RSSWidget/RSSWidget.yml
  Packs/CommonWidgets/Scripts/RSSWidget/RSSWidget_test.py
  Packs/CommonWidgets/Scripts/RSSWidget/test_data/test_variables.py
  Packs/CommonWidgets/pack_metadata.json
Labels: bug, docs-approved, release-notes-only

#16383 Log4j v3 enhancement
  Packs/CVE_2021_44228/Playbooks/playbook-CVE-2021-44228_-_Log4j_RCE.yml
  Packs/CVE_2021_44228/Playbooks/playbook-CVE-2021-44228_-_Log4j_RCE_README.md
  Packs/CVE_2021_44228/README.md
  Packs/CVE_2021_44228/ReleaseNotes/1_0_3.md
  Packs/CVE_2021_44228/doc_files/CVE-2021-44228_-_Log4j_RCE.png
  Packs/CVE_2021_44228/pack_metadata.json
Labels: docs-approved

#16370 Added "Rapid Breach Response" as a use case for marketplace
  Packs/CVE_2021_40444/pack_metadata.json
  Packs/CVE_2021_44228/pack_metadata.json
  Packs/MajorBreachesInvestigationandResponse/pack_metadata.json
  Tests/Marketplace/approved_usecases.json
  Tests/Marketplace/landingPage_sections.json
Labels: docs-approved

#16399 Freeze lazy-object-proxy pip package to 1.4.0
  dev-requirements-py2.txt
Labels: docs-approved

#16397 Removed integration image
  Packs/HackerOne/Integrations/HackerOne/HackerOne_image.png
Labels: docs-approved

#16410 CI/CD Pack Code Owner
  .github/CODEOWNERS
Labels: docs-approved

#14953 [Marketplace Contribution] Picus Content Pack
  Packs/PicusAutomation/.pack-ignore
  Packs/PicusAutomation/.secrets-ignore
  Packs/PicusAutomation/Author_image.png
  Packs/PicusAutomation/Integrations/Picus/Picus.py
  Packs/PicusAutomation/Integrations/Picus/Picus.yml
  Packs/PicusAutomation/Integrations/Picus/Picus_description.md
  Packs/PicusAutomation/Integrations/Picus/Picus_image.png
  Packs/PicusAutomation/Integrations/Picus/Picus_test.py
  Packs/PicusAutomation/Integrations/Picus/Pipfile
  Packs/PicusAutomation/Integrations/Picus/Pipfile.lock
  Packs/PicusAutomation/Integrations/Picus/README.md
  Packs/PicusAutomation/Integrations/Picus/command_examples
  Packs/PicusAutomation/Integrations/Picus/test_data/get_insecureAttackResults.json
  Packs/PicusAutomation/Integrations/Picus/test_data/get_mitigations.json
  Packs/PicusAutomation/Integrations/Picus/test_data/get_peerList.json
  Packs/PicusAutomation/Integrations/Picus/test_data/get_secureAttackResults.json
  Packs/PicusAutomation/Integrations/Picus/test_data/get_threatResults.json
  Packs/PicusAutomation/Integrations/Picus/test_data/get_vectorCompare.json
  Packs/PicusAutomation/Integrations/Picus/test_data/get_vectorList.json
  Packs/PicusAutomation/Integrations/Picus/test_data/get_versionInfo.json
  Packs/PicusAutomation/Integrations/Picus/test_data/runAttacks.json
  Packs/PicusAutomation/Integrations/Picus/test_data/triggerUpdate.json
  Packs/PicusAutomation/Playbooks/Picus.yml
  Packs/PicusAutomation/Playbooks/Picus_README.md
  Packs/PicusAutomation/README.md
  Packs/PicusAutomation/doc_files/Picus.png
  Packs/PicusAutomation/doc_files/Picus_Diagram_v1.png
  Packs/PicusAutomation/doc_files/peer_page.png
  Packs/PicusAutomation/doc_files/search_integration.png
  Packs/PicusAutomation/doc_files/test_integration.png
  Packs/PicusAutomation/pack_metadata.json
  package-lock.json
Labels: Contribution, docs-approved, Partner, Contribution Form Filled

#16409 Update http artifact method to GET request and change naming assumptions
  Packs/ContentManagement/Playbooks/playbook-Configuration_Setup.yml
  Packs/ContentManagement/ReleaseNotes/1_1_0.md
  Packs/ContentManagement/pack_metadata.json
Labels: Contribution, docs-approved, Contribution Form Filled, Community

#16398 XDR - changed incidents names in the fetch incidents command
  Packs/CortexXDR/Integrations/CortexXDRIR/CortexXDRIR.py
  Packs/CortexXDR/Integrations/CortexXDRIR/CortexXDRIR_test.py
  Packs/CortexXDR/ReleaseNotes/4_2_10.md
  Packs/CortexXDR/pack_metadata.json
Labels: bug, docs-approved, release-notes-only

#16334 Qradar v3 memory dump
  Packs/Base/ReleaseNotes/1_17_1.md
  Packs/Base/Scripts/CommonServerPython/CommonServerPython.py
  Packs/Base/Scripts/CommonServerPython/CommonServerPython_test.py
  Packs/Base/pack_metadata.json
  Packs/QRadar/Integrations/QRadar_v3/QRadar_v3.py
  Packs/QRadar/ReleaseNotes/2_1_21.md
  Packs/QRadar/pack_metadata.json
Labels: docs-approved

#16240 Update layouts description sections for non IOC indicators
  Packs/CommonTypes/Layouts/layoutscontainer-Campaign.json
  Packs/CommonTypes/Layouts/layoutscontainer-Course_of_Action.json
  Packs/CommonTypes/Layouts/layoutscontainer-Infrastructure.json
  Packs/CommonTypes/Layouts/layoutscontainer-Intrusion_Set.json
  Packs/CommonTypes/Layouts/layoutscontainer-STIX_Attack_Pattern.json
  Packs/CommonTypes/Layouts/layoutscontainer-STIX_Malware.json
  Packs/CommonTypes/Layouts/layoutscontainer-STIX_Report.json
  Packs/CommonTypes/Layouts/layoutscontainer-STIX_Threat_Actor.json
  Packs/CommonTypes/Layouts/layoutscontainer-STIX_Tool.json
  Packs/CommonTypes/ReleaseNotes/3_1_29.md
  Packs/CommonTypes/pack_metadata.json
Labels: docs-approved

#16368 SumoLogic: allow disabling url escape
  Packs/SumoLogic/Integrations/integration-SumoLogic.yml
  Packs/SumoLogic/Integrations/integration-SumoLogic_README.md
  Packs/SumoLogic/ReleaseNotes/1_1_0.json
  Packs/SumoLogic/ReleaseNotes/1_1_0.md
  Packs/SumoLogic/pack_metadata.json
Labels: docs-approved, release-notes-only

#16408 Improve integration configuration instructions
  Packs/CortexDataLake/Integrations/CortexDataLake/CortexDataLake_description.md
  Packs/CortexDataLake/ReleaseNotes/1_3_5.md
  Packs/CortexDataLake/pack_metadata.json
Labels: docs-approved

#16199 Update ParseEmailFiles
  Packs/CommonScripts/ReleaseNotes/1_6_9.md
  Packs/CommonScripts/Scripts/ParseEmailFiles/ParseEmailFiles.py
  Packs/CommonScripts/Scripts/ParseEmailFiles/ParseEmailFiles.yml
  Packs/CommonScripts/Scripts/ParseEmailFiles/ParseEmailFiles_README.md
  Packs/CommonScripts/Scripts/ParseEmailFiles/ParseEmailFiles_test.py
  Packs/CommonScripts/Scripts/ParseEmailFiles/README.md
  Packs/CommonScripts/pack_metadata.json
  Packs/HPE_Service_Manager/Integrations/README.md
Labels: Contribution, docs-approved, post-demo, Contribution Form Filled, Community

#16384 SearchIncidentsv2: workaround - fixed name & type filters
  Packs/CommonScripts/ReleaseNotes/1_6_9.md
  Packs/CommonScripts/Scripts/SearchIncidentsV2/SearchIncidentsV2.py
  Packs/CommonScripts/Scripts/SearchIncidentsV2/SearchIncidentsV2_test.py
  Packs/CommonScripts/pack_metadata.json
Labels: bug, docs-approved, release-notes-only

#16422 Log4j v4
  Packs/CVE_2021_44228/Playbooks/playbook-CVE-2021-44228_-_Log4j_RCE.yml
  Packs/CVE_2021_44228/Playbooks/playbook-CVE-2021-44228_-_Log4j_RCE_README.md
  Packs/CVE_2021_44228/README.md
  Packs/CVE_2021_44228/ReleaseNotes/1_0_4.md
  Packs/CVE_2021_44228/doc_files/CVE-2021-44228_-_Log4j_RCE.png
  Packs/CVE_2021_44228/pack_metadata.json
Labels: docs-approved

#16417 Fixed race condition in phishing campaigns and layout overhaul
  Packs/Campaign/Layouts/layoutscontainer-Phishing_Campaign.json
  Packs/Campaign/Playbooks/Detect_&_Manage_Phishing_Campaigns.yml
  Packs/Campaign/Playbooks/Detect_&_Manage_Phishing_Campaigns_README.md
  Packs/Campaign/ReleaseNotes/3_2_0.md
  Packs/Campaign/TestPlaybooks/Phishing_Investigation_-_Generic_v2_-_Campaign_Test.yml
  Packs/Campaign/doc_files/Detect_&_Manage_Phishing_Campaigns.png
  Packs/Campaign/pack_metadata.json
  Tests/conf.json
Labels: docs-approved

#16454 Fix xql note bug
  Packs/CortexXDR/Integrations/XQLQueryingEngine/XQLQueryingEngine.py
  Packs/CortexXDR/Integrations/XQLQueryingEngine/XQLQueryingEngine_test.py
  Packs/CortexXDR/ReleaseNotes/4_2_11.md
  Packs/CortexXDR/pack_metadata.json
Labels: docs-approved

#16451 Updated playbook readme file
  Packs/CVE_2021_44228/Playbooks/playbook-CVE-2021-44228_-_Log4j_RCE.yml
  Packs/CVE_2021_44228/Playbooks/playbook-CVE-2021-44228_-_Log4j_RCE_README.md
  Packs/CVE_2021_44228/README.md
  Packs/CVE_2021_44228/ReleaseNotes/1_0_5.md
  Packs/CVE_2021_44228/doc_files/CVE-2021-44228_-_Log4j_RCE.png
  Packs/CVE_2021_44228/pack_metadata.json
Labels: docs-approved

#16455 Fix CommonServerPython Mypy errors
  .circleci/config.yml
  Packs/Base/ReleaseNotes/1_17_2.md
  Packs/Base/Scripts/CommonServerPython/CommonServerPython.py
  Packs/Base/Scripts/CommonServerPython/CommonServerPython_test.py
  Packs/Base/pack_metadata.json
  Packs/ProofpointServerProtection/.pack-ignore
  Packs/TIM_Processing/.pack-ignore
Labels: docs-approved

#16400 Aws feed
  Packs/FeedAWS/Integrations/FeedAWS/FeedAWS.yml
  Packs/FeedAWS/ReleaseNotes/1_1_11.md
  Packs/FeedAWS/pack_metadata.json
Labels: docs-approved, release-notes-only

#16466 Use signal profiling dump only on non-Windows OS
  Packs/Base/ReleaseNotes/1_17_3.md
  Packs/Base/Scripts/CommonServerPython/CommonServerPython.py
  Packs/Base/pack_metadata.json
  Packs/QRadar/Integrations/QRadar_v3/QRadar_v3.py
  Packs/QRadar/ReleaseNotes/2_1_22.md
  Packs/QRadar/pack_metadata.json
Labels: docs-approved

#16467 - Added the `wildcards` argument for matching to any values.
  Packs/MapPattern/ReleaseNotes/1_0_5.md
  Packs/MapPattern/Scripts/MapPattern/MapPattern.py
  Packs/MapPattern/Scripts/MapPattern/MapPattern.yml
  Packs/MapPattern/Scripts/MapPattern/MapPattern_test.py
  Packs/MapPattern/Scripts/MapPattern/README.md
  Packs/MapPattern/Scripts/MapPattern/test_data/test-1.json
  Packs/MapPattern/pack_metadata.json
Labels: Contribution, docs-approved, Contribution Form Filled, Community

#16418 upload flow: add item IDs to metadata files in the index.zip
  Packs/CommonScripts/.pack-ignore
  Tests/Marketplace/marketplace_services.py
Labels: docs-approved

#16046 Prisma cloud compute enhancement
  Packs/PrismaCloudCompute/Integrations/PaloAltoNetworks_PrismaCloudCompute/PaloAltoNetworks_PrismaCloudCompute.py
  Packs/PrismaCloudCompute/Integrations/PaloAltoNetworks_PrismaCloudCompute/PaloAltoNetworks_PrismaCloudCompute.yml
  Packs/PrismaCloudCompute/Integrations/PaloAltoNetworks_PrismaCloudCompute/PaloAltoNetworks_PrismaCloudCompute_test.py
  Packs/PrismaCloudCompute/Integrations/PaloAltoNetworks_PrismaCloudCompute/Pipfile
  Packs/PrismaCloudCompute/Integrations/PaloAltoNetworks_PrismaCloudCompute/Pipfile.lock
  Packs/PrismaCloudCompute/Integrations/PaloAltoNetworks_PrismaCloudCompute/README.md
  Packs/PrismaCloudCompute/Integrations/PaloAltoNetworks_PrismaCloudCompute/commands.txt
  Packs/PrismaCloudCompute/ReleaseNotes/1_1_0.md
  Packs/PrismaCloudCompute/TestPlaybooks/playbook-PaloAltoNetworks_PrismaCloudCompute-Test.yml
  Packs/PrismaCloudCompute/pack_metadata.json
  Tests/conf.json
Labels: docs-approved

#16485 Fix typo
  Packs/Base/ReleaseNotes/1_17_4.md
  Packs/Base/Scripts/CommonServerPython/CommonServerPython.py
  Packs/Base/pack_metadata.json
Labels: docs-approved

#16016 Social Engineering Domain Analysis
  Packs/SocialEngineeringDomainAnalysis/.pack-ignore
  Packs/SocialEngineeringDomainAnalysis/.secrets-ignore
  Packs/SocialEngineeringDomainAnalysis/IncidentFields/incidentfield-Social_Engineering_Domain_Analysis_Registered_Domain.json
  Packs/SocialEngineeringDomainAnalysis/IncidentFields/incidentfield-Social_Engineering_Domain_CSV.json
  Packs/SocialEngineeringDomainAnalysis/IncidentFields/incidentfield-Social_Engineering_Domain_List.json
  Packs/SocialEngineeringDomainAnalysis/IncidentFields/incidentfield-Social_Engineering_Domain_Summary.json
  Packs/SocialEngineeringDomainAnalysis/IncidentTypes/incidenttype-Social_Engineering_Domain_Investigation.json
  Packs/SocialEngineeringDomainAnalysis/Layouts/layoutscontainer-Social_Engineering_Domain_Investigation_Layout.json
  Packs/SocialEngineeringDomainAnalysis/Playbooks/Social_Engineering_Domain_Enrichment.yml
  Packs/SocialEngineeringDomainAnalysis/Playbooks/Social_Engineering_Domain_Investigation.yml
  Packs/SocialEngineeringDomainAnalysis/README.md
  Packs/SocialEngineeringDomainAnalysis/doc_files/Social_Engineering_Domain_Investigation_Thu_Dec_16_2021.png
  Packs/SocialEngineeringDomainAnalysis/pack_metadata.json
Labels: Contribution, docs-approved, ready-for-instance-test, post-demo, Contribution Form Filled, Community

#16416 Cymulatev2 creds
  Packs/Cymulate/.pack-ignore
  Packs/Cymulate/Integrations/Cymulate_v2/Cymulate_v2.py
  Packs/Cymulate/Integrations/Cymulate_v2/Cymulate_v2.yml
  Packs/Cymulate/ReleaseNotes/2_0_9.md
  Packs/Cymulate/pack_metadata.json
Labels: docs-approved

#16480 Panorama: Fix edit-rule argument options
  Packs/PAN-OS/Integrations/Panorama/Panorama.py
  Packs/PAN-OS/Integrations/Panorama/Panorama.yml
  Packs/PAN-OS/Integrations/Panorama/README.md
  Packs/PAN-OS/ReleaseNotes/1_7_6.md
  Packs/PAN-OS/pack_metadata.json
  Tests/conf.json
Labels: docs-approved

#16430 Adopt Process For Devo
  Packs/Devo/README.md
  Packs/Devo/ReleaseNotes/1_1_7.md
  Packs/Devo/pack_metadata.json
Labels: Contribution, docs-approved, Partner, Contribution Form Filled

#16469 - Fixed an issue where it didn't parse DT syntax correctly.
  Packs/ExtFilter/ReleaseNotes/1_1_9.md
  Packs/ExtFilter/Scripts/ExtFilter/ExtFilter.py
  Packs/ExtFilter/Scripts/ExtFilter/ExtFilter_test.py
  Packs/ExtFilter/pack_metadata.json
Labels: Contribution, docs-approved, Contribution Form Filled, Community

#16496 LogRhythmRest - unskip test
  Tests/conf.json
Labels: docs-approved

#16495 fix lr test playbook
  Packs/LogRhythm/TestPlaybooks/playbook-LogRhythm_Test_Playbook.yml
  Tests/conf.json
Labels: docs-approved

#16056 Ad identity fetch fix
  Packs/AzureActiveDirectory/Integrations/AzureADIdentityProtection/AzureADIdentityProtection.py
  Packs/AzureActiveDirectory/Integrations/AzureADIdentityProtection/AzureADIdentityProtection_test.py
  Packs/AzureActiveDirectory/Integrations/AzureADIdentityProtection/test_data/incidents.json
  Packs/AzureActiveDirectory/ReleaseNotes/1_2_0.md
  Packs/AzureActiveDirectory/pack_metadata.json
Labels: docs-approved

#16010 Cuckoo Sendbox Authentication
  Packs/CuckooSandbox/Integrations/integration-CuckooSandbox.yml
  Packs/CuckooSandbox/Integrations/integration-CuckooSandbox_README.md
  Packs/CuckooSandbox/ReleaseNotes/1_1_0.md
  Packs/CuckooSandbox/pack_metadata.json
Labels: docs-approved

#16470 Nextpose - added default value to the limit argument
  Packs/Rapid7_Nexpose/Integrations/Rapid7_Nexpose/Rapid7_Nexpose.yml
  Packs/Rapid7_Nexpose/ReleaseNotes/1_1_5.md
  Packs/Rapid7_Nexpose/TestPlaybooks/playbook-Nexpose_test.yml
  Packs/Rapid7_Nexpose/pack_metadata.json
Labels: bug, docs-approved, release-notes-only
