Repository demisto/content, pull requests merged in 2021-11, with the labels that each got.

#14460 Feed no update tag
  Packs/ApiModules/ReleaseNotes/2_2_5.md
  Packs/ApiModules/Scripts/CSVFeedApiModule/CSVFeedApiModule.py
  Packs/ApiModules/Scripts/CSVFeedApiModule/CSVFeedApiModule_test.py
  Packs/ApiModules/Scripts/HTTPFeedApiModule/HTTPFeedApiModule.py
  Packs/ApiModules/Scripts/HTTPFeedApiModule/HTTPFeedApiModule_test.py
  Packs/ApiModules/Scripts/JSONFeedApiModule/JSONFeedApiModule.py
  Packs/ApiModules/Scripts/JSONFeedApiModule/JSONFeedApiModule_test.py
  Packs/ApiModules/pack_metadata.json
  Packs/BitcoinAbuse/ReleaseNotes/1_0_12.md
  Packs/BitcoinAbuse/pack_metadata.json
  Packs/FeedAWS/ReleaseNotes/1_1_9.md
  Packs/FeedAWS/pack_metadata.json
  Packs/FeedAlienVault/ReleaseNotes/1_1_8.md
  Packs/FeedAlienVault/pack_metadata.json
  Packs/FeedBambenekConsulting/ReleaseNotes/1_1_8.md
  Packs/FeedBambenekConsulting/pack_metadata.json
  Packs/FeedBlocklist_de/ReleaseNotes/1_1_8.md
  Packs/FeedBlocklist_de/pack_metadata.json
  Packs/FeedBruteForceBlocker/ReleaseNotes/1_1_8.md
  Packs/FeedBruteForceBlocker/pack_metadata.json
  Packs/FeedCSV/ReleaseNotes/1_1_6.md
  Packs/FeedCSV/pack_metadata.json
  Packs/FeedCloudflare/ReleaseNotes/1_1_8.md
  Packs/FeedCloudflare/pack_metadata.json
  Packs/FeedDShield/ReleaseNotes/1_1_8.md
  Packs/FeedDShield/pack_metadata.json
  Packs/FeedFastly/ReleaseNotes/1_1_8.md
  Packs/FeedFastly/pack_metadata.json
  Packs/FeedFeodoTracker/ReleaseNotes/1_1_9.md
  Packs/FeedFeodoTracker/pack_metadata.json
  Packs/FeedIntel471/ReleaseNotes/2_0_5.md
  Packs/FeedIntel471/pack_metadata.json
  Packs/FeedJSON/ReleaseNotes/1_1_8.md
  Packs/FeedJSON/pack_metadata.json
  Packs/FeedMajesticMillion/ReleaseNotes/1_1_6.md
  Packs/FeedMajesticMillion/pack_metadata.json
  Packs/FeedMalwareDomainList/ReleaseNotes/1_1_6.md
  Packs/FeedMalwareDomainList/pack_metadata.json
  Packs/FeedPlainText/ReleaseNotes/1_1_7.md
  Packs/FeedPlainText/pack_metadata.json
  Packs/FeedSpamhaus/ReleaseNotes/1_1_8.md
  Packs/FeedSpamhaus/pack_metadata.json
  Packs/Feedsslabusech/ReleaseNotes/1_1_8.md
  Packs/Feedsslabusech/pack_metadata.json
  Packs/iDefense/ReleaseNotes/3_1_2.md
  Packs/iDefense/pack_metadata.json
Labels: docs-approved, release-notes-only

#15559 fixed typo in an error message when trying to create an indicator wit…
  Packs/Base/ReleaseNotes/1_13_44.md
  Packs/Base/Scripts/CommonServerPython/CommonServerPython.py
  Packs/Base/pack_metadata.json
Labels: docs-approved

#15506 Make GetLargestInvestigations deprecation optional
  Packs/CommonWidgets/ReleaseNotes/1_1_10.md
  Packs/CommonWidgets/Scripts/GetLargestInputsAndOuputsInIncidents/GetLargestInputsAndOuputsInIncidents.py
  Packs/CommonWidgets/Scripts/GetLargestInputsAndOuputsInIncidents/GetLargestInputsAndOuputsInIncidents.yml
  Packs/CommonWidgets/Scripts/GetLargestInvestigations/GetLargestInvestigations.py
  Packs/CommonWidgets/Scripts/GetLargestInvestigations/GetLargestInvestigations.yml
  Packs/CommonWidgets/pack_metadata.json
Labels: docs-approved

#15577 Remove unnecessary divider from MitreAttack description.
  Packs/FeedMitreAttack/Integrations/FeedMitreAttack/FeedMitreAttack_description.md
  Packs/FeedMitreAttack/ReleaseNotes/1_1_17.md
  Packs/FeedMitreAttack/pack_metadata.json
Labels: docs-approved

#15578 Remove dbotrole linter requirements
  dev-requirements-py3.txt
Labels: docs-approved

#15288 Adding scripts for incident response tasks tracking
  Packs/DemistoRESTAPI/ReleaseNotes/1_2_0.md
  Packs/DemistoRESTAPI/Scripts/GetTasksWithSections/GetTasksWithSections.py
  Packs/DemistoRESTAPI/Scripts/GetTasksWithSections/GetTasksWithSections.yml
  Packs/DemistoRESTAPI/Scripts/GetTasksWithSections/GetTasksWithSections_test.py
  Packs/DemistoRESTAPI/Scripts/GetTasksWithSections/test_data/tasks_example.json
  Packs/DemistoRESTAPI/Scripts/SetIRProceduresMarkdown/SetIRProceduresMarkdown.py
  Packs/DemistoRESTAPI/Scripts/SetIRProceduresMarkdown/SetIRProceduresMarkdown.yml
  Packs/DemistoRESTAPI/Scripts/SetIRProceduresMarkdown/SetIRProceduresMarkdown_test.py
  Packs/DemistoRESTAPI/Scripts/SetIRProceduresMarkdown/test_data/ir_tasks_after_traverse.json
  Packs/DemistoRESTAPI/TestPlaybooks/playbook-GetTasksWithSections.yml
  Packs/DemistoRESTAPI/pack_metadata.json
  Tests/conf.json
Labels: docs-approved

#15514 Zoom feed - using txt files
  Packs/FeedZoom/Integrations/FeedZoom/FeedZoom.py
  Packs/FeedZoom/Integrations/FeedZoom/FeedZoom.yml
  Packs/FeedZoom/Integrations/FeedZoom/FeedZoom_description.md
  Packs/FeedZoom/Integrations/FeedZoom/FeedZoom_test.py
  Packs/FeedZoom/Integrations/FeedZoom/test_data/zoom_endpoint.txt
  Packs/FeedZoom/ReleaseNotes/1_1_5.md
  Packs/FeedZoom/pack_metadata.json
Labels: bug, docs-approved

#15446 Remove DBotRole 2
  Packs/Base/ReleaseNotes/1_14_0.md
  Packs/Base/Scripts/FindSimilarIncidentsByText/FindSimilarIncidentsByText.yml
  Packs/Base/Scripts/GetIncidentsByQuery/GetIncidentsByQuery.yml
  Packs/Base/pack_metadata.json
Labels: docs-approved

#15455 Remove DbotRole 3
  Packs/CrowdStrikeFalconStreamingV2/ReleaseNotes/1_1_0.md
  Packs/CrowdStrikeFalconStreamingV2/Scripts/CrowdStrikeStreamingPreProcessing/CrowdStrikeStreamingPreProcessing.py
  Packs/CrowdStrikeFalconStreamingV2/Scripts/CrowdStrikeStreamingPreProcessing/CrowdStrikeStreamingPreProcessing.yml
  Packs/CrowdStrikeFalconStreamingV2/Scripts/CrowdStrikeStreamingPreProcessing/Pipfile
  Packs/CrowdStrikeFalconStreamingV2/Scripts/CrowdStrikeStreamingPreProcessing/Pipfile.lock
  Packs/CrowdStrikeFalconStreamingV2/Scripts/CrowdStrikeStreamingPreProcessing/README.md
  Packs/CrowdStrikeFalconStreamingV2/Scripts/script-CrowdStrikeStreamingPreProcessing.yml
  Packs/CrowdStrikeFalconStreamingV2/pack_metadata.json
  Packs/CyrenInboxSecurity/ReleaseNotes/1_1_0.md
  Packs/CyrenInboxSecurity/Scripts/CyrenFindSimilarIncidents/CyrenFindSimilarIncidents.yml
  Packs/CyrenInboxSecurity/Scripts/CyrenShowThreatIndicators/CyrenShowThreatIndicators.yml
  Packs/CyrenInboxSecurity/pack_metadata.json
  Packs/ExpanseV2/ReleaseNotes/1_9_0.md
  Packs/ExpanseV2/Scripts/ExpanseGenerateIssueMapWidgetScript/ExpanseGenerateIssueMapWidgetScript.yml
  Packs/ExpanseV2/pack_metadata.json
  Packs/GroupIB_ThreatIntelligenceAttribution/ReleaseNotes/1_3_0.md
  Packs/GroupIB_ThreatIntelligenceAttribution/Scripts/GIBIncidentUpdate/GIBIncidentUpdate.yml
  Packs/GroupIB_ThreatIntelligenceAttribution/Scripts/GIBIncidentUpdateIncludingClosed/GIBIncidentUpdateIncludingClosed.yml
  Packs/GroupIB_ThreatIntelligenceAttribution/pack_metadata.json
  Packs/IntegrationsAndIncidentsHealthCheck/ReleaseNotes/1_3_0.md
  Packs/IntegrationsAndIncidentsHealthCheck/Scripts/CopyLinkedAnalystNotes/CopyLinkedAnalystNotes.yml
  Packs/IntegrationsAndIncidentsHealthCheck/Scripts/GetFailedTasks/GetFailedTasks.yml
  Packs/IntegrationsAndIncidentsHealthCheck/pack_metadata.json
  Packs/OnboardingIntegration/ReleaseNotes/1_1_0.md
  Packs/OnboardingIntegration/Scripts/OnboardingCleanup/OnboardingCleanup.yml
  Packs/OnboardingIntegration/pack_metadata.json
  Packs/PhishLabs/ReleaseNotes/1_1_0.md
  Packs/PhishLabs/Scripts/PhishLabsPopulateIndicators/PhishLabsPopulateIndicators.yml
  Packs/PhishLabs/pack_metadata.json
  Packs/ThreatIntelligenceManagement/ReleaseNotes/1_1_0.md
  Packs/ThreatIntelligenceManagement/Scripts/ThreatIntelligenceManagementGetIncidentsPerFeed/ThreatIntelligenceManagementGetIncidentsPerFeed.yml
  Packs/ThreatIntelligenceManagement/pack_metadata.json
Labels: docs-approved

#15291 XDR incident handling v3 - update resolved true positive status
  Packs/CortexXDR/Playbooks/Cortex_XDR_incident_handling_v3.yml
  Packs/CortexXDR/Playbooks/Cortex_XDR_incident_handling_v3_README.md
  Packs/CortexXDR/ReleaseNotes/4_1_10.md
  Packs/CortexXDR/pack_metadata.json
Labels: docs-approved

#15583 BitcoinAbuse - fix indicators creation
  Packs/BitcoinAbuse/Integrations/BitcoinAbuse/BitcoinAbuse.py
  Packs/BitcoinAbuse/ReleaseNotes/1_0_13.md
  Packs/BitcoinAbuse/pack_metadata.json
Labels: docs-approved, release-notes-only

#13582 added securityscorecard partner pack
  Packs/SecurityScorecard/.pack-ignore
  Packs/SecurityScorecard/.secrets-ignore
  Packs/SecurityScorecard/Author_image.png
  Packs/SecurityScorecard/Classifiers/classifier-SecurityScorecard_Alert_Mapper.json
  Packs/SecurityScorecard/IncidentFields/SecurityScorecard_company_name.json
  Packs/SecurityScorecard/IncidentFields/SecurityScorecard_domain.json
  Packs/SecurityScorecard/IncidentFields/SecurityScorecard_factor.json
  Packs/SecurityScorecard/IncidentFields/SecurityScorecard_grade.json
  Packs/SecurityScorecard/IncidentFields/SecurityScorecard_score.json
  Packs/SecurityScorecard/IncidentFields/SecurityScorecard_score_impact.json
  Packs/SecurityScorecard/IncidentFields/SecurityScorecard_username.json
  Packs/SecurityScorecard/IncidentTypes/SecurityScorecard-Alert.json
  Packs/SecurityScorecard/Integrations/SecurityScorecard/Pipfile
  Packs/SecurityScorecard/Integrations/SecurityScorecard/Pipfile.lock
  Packs/SecurityScorecard/Integrations/SecurityScorecard/README.md
  Packs/SecurityScorecard/Integrations/SecurityScorecard/SecurityScorecard.py
  Packs/SecurityScorecard/Integrations/SecurityScorecard/SecurityScorecard.yml
  Packs/SecurityScorecard/Integrations/SecurityScorecard/SecurityScorecard_description.md
  Packs/SecurityScorecard/Integrations/SecurityScorecard/SecurityScorecard_image.png
  Packs/SecurityScorecard/Integrations/SecurityScorecard/SecurityScorecard_test.py
  Packs/SecurityScorecard/Integrations/SecurityScorecard/command_examples
  Packs/SecurityScorecard/Integrations/SecurityScorecard/test_data/data.json
  Packs/SecurityScorecard/Layouts/layoutscontainer-SecurityScorecard_Alert_Layout.json
  Packs/SecurityScorecard/README.md
  Packs/SecurityScorecard/pack_metadata.json
Labels: docs-approved

#15587 QRadar Maintenance Enhancement
  Packs/QRadar/Integrations/QRadar_v3/QRadar_v3.py
  Packs/QRadar/ReleaseNotes/2_1_5.md
  Packs/QRadar/pack_metadata.json
Labels: docs-approved

#15483 Bug dbot remove
  Packs/CommonScripts/ReleaseNotes/1_5_0.json
  Packs/CommonScripts/ReleaseNotes/1_5_0.md
  Packs/CommonScripts/Scripts/CompareIncidentsLabels/CompareIncidentsLabels.yml
  Packs/CommonScripts/Scripts/CopyContextToField/CopyContextToField.yml
  Packs/CommonScripts/Scripts/ExtractIndicatorsFromTextFile/ExtractIndicatorsFromTextFile.yml
  Packs/CommonScripts/Scripts/ExtractIndicatorsFromWordFile/ExtractIndicatorsFromWordFile.yml
  Packs/CommonScripts/Scripts/FindSimilarIncidentsV2/FindSimilarIncidentsV2.yml
  Packs/CommonScripts/Scripts/GetDuplicatesMlv2/GetDuplicatesMlv2.yml
  Packs/CommonScripts/Scripts/IndicatorMaliciousRatioCalculation/IndicatorMaliciousRatioCalculation.yml
  Packs/CommonScripts/Scripts/NumberOfPhishingAttemptPerUser/NumberOfPhishingAttemptPerUser.yml
  Packs/CommonScripts/Scripts/ReadPDFFileV2/ReadPDFFileV2.yml
  Packs/CommonScripts/Scripts/SearchIncidentsV2/SearchIncidentsV2.yml
  Packs/CommonScripts/Scripts/SetAndHandleEmpty/SetAndHandleEmpty.yml
  Packs/CommonScripts/Scripts/SetByIncidentId/SetByIncidentId.yml
  Packs/CommonScripts/Scripts/script-DeleteConext.yml
  Packs/CommonScripts/Scripts/script-MarkRelatedIncidents.yml
  Packs/CommonScripts/Scripts/script-findIncidentsWithIndicator.yml
  Packs/CommonScripts/pack_metadata.json
Labels: docs-approved

#15585 changed test to include actual access to api.
  Packs/CrowdStrikeMalquery/Integrations/CrowdStrikeMalquery/CrowdStrikeMalquery.py
  Packs/CrowdStrikeMalquery/ReleaseNotes/1_0_8.md
  Packs/CrowdStrikeMalquery/pack_metadata.json
Labels: docs-approved

#15537 Saas security: add playbooks, fields, and mapping.
  Packs/PrismaSaasSecurity/Classifiers/classifier-Saas_Security_-_Incoming_Mapper.json
  Packs/PrismaSaasSecurity/IncidentFields/incidentfield-Saas_Security_Asset_Name.json
  Packs/PrismaSaasSecurity/IncidentFields/incidentfield-Saas_Security_Incident_Id.json
  Packs/PrismaSaasSecurity/IncidentFields/incidentfield-Saas_Security_Incident_Severity_Level.json
  Packs/PrismaSaasSecurity/IncidentTypes/incidenttype-Saas_Security.json
  Packs/PrismaSaasSecurity/Playbooks/Saas_Security_-_Incident_Processor.yml
  Packs/PrismaSaasSecurity/Playbooks/Saas_Security_-_Incident_Processor_README.md
  Packs/PrismaSaasSecurity/Playbooks/Saas_Security_-_Take_Action_on_the_Incident.yml
  Packs/PrismaSaasSecurity/Playbooks/Saas_Security_-_Take_Action_on_the_Incident_README.md
  Packs/PrismaSaasSecurity/ReleaseNotes/1_2_0.md
  Packs/PrismaSaasSecurity/doc_files/Incident_Processor_Playbook.png
  Packs/PrismaSaasSecurity/doc_files/Take_Action_on_the_Incident_Playbook.png
  Packs/PrismaSaasSecurity/pack_metadata.json
Labels: Contribution, docs-approved, Contribution Form Filled

#15586 [Microsoft Graph User] Handle User Queries with Unsupported Characters
  Packs/MicrosoftGraphUser/Integrations/MicrosoftGraphUser/MicrosoftGraphUser.py
  Packs/MicrosoftGraphUser/Integrations/MicrosoftGraphUser/MicrosoftGraphUser_test.py
  Packs/MicrosoftGraphUser/ReleaseNotes/1_3_15.md
  Packs/MicrosoftGraphUser/pack_metadata.json
Labels: docs-approved, release-notes-only

#15601 Remove TIR from core packs
  Tests/Marketplace/core_packs_list.json
Labels: docs-approved

#15598 new PR
  Packs/AzureRiskyUsers/.pack-ignore
  Packs/AzureRiskyUsers/.secrets-ignore
  Packs/AzureRiskyUsers/Integrations/AzureRiskyUsers/AzureRiskyUsers.py
  Packs/AzureRiskyUsers/Integrations/AzureRiskyUsers/AzureRiskyUsers.yml
  Packs/AzureRiskyUsers/Integrations/AzureRiskyUsers/AzureRiskyUsers_description.md
  Packs/AzureRiskyUsers/Integrations/AzureRiskyUsers/AzureRiskyUsers_image.png
  Packs/AzureRiskyUsers/Integrations/AzureRiskyUsers/AzureRiskyUsers_test.py
  Packs/AzureRiskyUsers/Integrations/AzureRiskyUsers/README.md
  Packs/AzureRiskyUsers/Integrations/AzureRiskyUsers/command_examples.txt
  Packs/AzureRiskyUsers/Integrations/AzureRiskyUsers/test_data/get_risk_detection.json
  Packs/AzureRiskyUsers/Integrations/AzureRiskyUsers/test_data/get_risky_user.json
  Packs/AzureRiskyUsers/Integrations/AzureRiskyUsers/test_data/list_risk_detections.json
  Packs/AzureRiskyUsers/Integrations/AzureRiskyUsers/test_data/list_risky_users.json
  Packs/AzureRiskyUsers/README.md
  Packs/AzureRiskyUsers/TestPlaybooks/playbook-AzureRiskyUsers-Test.yml
  Packs/AzureRiskyUsers/pack_metadata.json
  Tests/conf.json
Labels: Contribution, docs-approved

#15366 coverage enforcemnt activation
  .circleci/config.yml
  .gitlab/ci/global.yml
  .gitlab/ci/on-push.yml
  .hooks/pre-commit
  Utils/tests/upload_code_coverage_report_test.py
  Utils/upload_code_coverage_report.py
Labels: docs-approved

#15602 cyberArk fix test
  Packs/cyberark_AIM/Integrations/CyberArkAIM_v2/CyberArkAIM_v2.py
  Packs/cyberark_AIM/ReleaseNotes/1_0_9.md
  Packs/cyberark_AIM/pack_metadata.json
Labels: docs-approved

#15180 Taxii 2 enhancement to fetch stix objects other than indicators
  Packs/ApiModules/Scripts/TAXII2ApiModule/TAXII2ApiModule.py
  Packs/ApiModules/Scripts/TAXII2ApiModule/TAXII2ApiModule.yml
  Packs/ApiModules/Scripts/TAXII2ApiModule/TAXII2ApiModule_test.py
  Packs/ApiModules/Scripts/TAXII2ApiModule/test_data/id_to_object_test.json
  Packs/ApiModules/Scripts/TAXII2ApiModule/test_data/objects_envelopes.json
  Packs/ApiModules/Scripts/TAXII2ApiModule/test_data/parsed_stix_objects.json
  Packs/FeedTAXII/Integrations/FeedTAXII2/FeedTAXII2.py
  Packs/FeedTAXII/Integrations/FeedTAXII2/FeedTAXII2.yml
  Packs/FeedTAXII/Integrations/FeedTAXII2/FeedTAXII2_test.py
  Packs/FeedTAXII/ReleaseNotes/1_1_0.md
  Packs/FeedTAXII/pack_metadata.json
Labels: docs-approved

#15616 fix coverage anforcment failure on sdk nightly
  .gitlab/ci/global.yml
Labels: docs-approved

#15582 Added AzureKeyVault integration for new PR.
  Packs/ApiModules/Scripts/MicrosoftApiModule/MicrosoftApiModule.py
  Packs/AzureKeyVault/.pack-ignore
  Packs/AzureKeyVault/.secrets-ignore
  Packs/AzureKeyVault/Integrations/AzureKeyVault/AzureKeyVault.py
  Packs/AzureKeyVault/Integrations/AzureKeyVault/AzureKeyVault.yml
  Packs/AzureKeyVault/Integrations/AzureKeyVault/AzureKeyVault_description.md
  Packs/AzureKeyVault/Integrations/AzureKeyVault/AzureKeyVault_image.png
  Packs/AzureKeyVault/Integrations/AzureKeyVault/AzureKeyVault_test.py
  Packs/AzureKeyVault/Integrations/AzureKeyVault/README.md
  Packs/AzureKeyVault/Integrations/AzureKeyVault/test_data/create_or_update_key_vault.json
  Packs/AzureKeyVault/Integrations/AzureKeyVault/test_data/delete_key.json
  Packs/AzureKeyVault/Integrations/AzureKeyVault/test_data/delete_key_vault.json
  Packs/AzureKeyVault/Integrations/AzureKeyVault/test_data/delete_secret.json
  Packs/AzureKeyVault/Integrations/AzureKeyVault/test_data/get_certificate.json
  Packs/AzureKeyVault/Integrations/AzureKeyVault/test_data/get_certificate_policy.json
  Packs/AzureKeyVault/Integrations/AzureKeyVault/test_data/get_key.json
  Packs/AzureKeyVault/Integrations/AzureKeyVault/test_data/get_key_vault.json
  Packs/AzureKeyVault/Integrations/AzureKeyVault/test_data/get_secret.json
  Packs/AzureKeyVault/Integrations/AzureKeyVault/test_data/get_secret_2.json
  Packs/AzureKeyVault/Integrations/AzureKeyVault/test_data/list_certificate.json
  Packs/AzureKeyVault/Integrations/AzureKeyVault/test_data/list_key_vaults.json
  Packs/AzureKeyVault/Integrations/AzureKeyVault/test_data/list_keys.json
  Packs/AzureKeyVault/Integrations/AzureKeyVault/test_data/list_secrets.json
  Packs/AzureKeyVault/Integrations/AzureKeyVault/test_data/update_access_policy.json
  Packs/AzureKeyVault/README.md
  Packs/AzureKeyVault/TestPlaybooks/playbook-AzureKeyVault-Test.yml
  Packs/AzureKeyVault/pack_metadata.json
  Tests/conf.json
Labels: Contribution

#15622 fix coverage anforcment failure on sdk nightly
  .gitlab/ci/global.yml
Labels: docs-approved

#15623 fix coverage anforcment failure on sdk nightly
  .gitlab/ci/global.yml
Labels: docs-approved

#15605 Mail Listener Fetch fails on unicode issue
  Packs/MailListener/Integrations/MailListenerV2/MailListenerV2.py
  Packs/MailListener/Integrations/MailListenerV2/MailListenerV2_test.py
  Packs/MailListener/ReleaseNotes/1_0_6.md
  Packs/MailListener/pack_metadata.json
Labels: docs-approved

#15614 improve visualisation in case no results are returned in splunk show enrichment scripts
  Packs/SplunkPy/ReleaseNotes/2_2_2.md
  Packs/SplunkPy/Scripts/SplunkShowAsset/SplunkShowAsset.py
  Packs/SplunkPy/Scripts/SplunkShowAsset/SplunkShowAsset.yml
  Packs/SplunkPy/Scripts/SplunkShowDrilldown/SplunkShowDrilldown.py
  Packs/SplunkPy/Scripts/SplunkShowDrilldown/SplunkShowDrilldown.yml
  Packs/SplunkPy/Scripts/SplunkShowIdentity/SplunkShowIdentity.py
  Packs/SplunkPy/Scripts/SplunkShowIdentity/SplunkShowIdentity.yml
  Packs/SplunkPy/TestPlaybooks/playbook-SplunkShowEnrichment.yml
  Packs/SplunkPy/pack_metadata.json
  Tests/conf.json
Labels: docs-approved, release-notes-only

#15625 fix typo in Anomali
  Packs/Anomali_ThreatStream/Integrations/integration-AnomaliThreatStream_README.md
Labels: docs-approved

#15637 wf-readme-add-spacw
  Packs/Palo_Alto_Networks_WildFire/Integrations/Palo_Alto_Networks_WildFire_v2/README.md
Labels: docs-approved

#15438 indicator field added, layouts changed, mapper changed
  Packs/ServiceNow/Classifiers/classifier-mapper-incoming-ServiceNow.json
  Packs/ServiceNow/IncidentFields/incidentfield-ServiceNow_Ticket_ID.json
  Packs/ServiceNow/Layouts/layoutscontainer-ServiceNow_Create_Ticket_and_Mirror.json
  Packs/ServiceNow/Layouts/layoutscontainer-ServiceNow_Ticket.json
  Packs/ServiceNow/ReleaseNotes/2_2_11.md
  Packs/ServiceNow/pack_metadata.json
Labels: docs-approved

#15517 SlackV3 Promote to GA and fixed issue with bot identification
  Packs/Slack/Integrations/SlackV3/SlackV3.py
  Packs/Slack/Integrations/SlackV3/SlackV3.yml
  Packs/Slack/Integrations/SlackV3/SlackV3_description.md
  Packs/Slack/ReleaseNotes/2_2_0.md
  Packs/Slack/pack_metadata.json
Labels: docs-approved

#13385 Added fail-duplicates flag to config
  .circleci/config.yml
Labels: docs-approved

#15636 AF Tags Feed defaultEnabled field
  Packs/AutoFocus/Integrations/AutoFocusTagsFeed/AutoFocusTagsFeed.yml
  Packs/AutoFocus/ReleaseNotes/2_0_1.md
  Packs/AutoFocus/pack_metadata.json
  Tests/conf.json
Labels: docs-approved

#15478 Defender-Safelinks: New integration
  Packs/Microsoft365Defender/.secrets-ignore
  Packs/Microsoft365Defender/Integrations/O365DefenderSafeLinks/O365DefenderSafeLinks.Tests.ps1
  Packs/Microsoft365Defender/Integrations/O365DefenderSafeLinks/O365DefenderSafeLinks.ps1
  Packs/Microsoft365Defender/Integrations/O365DefenderSafeLinks/O365DefenderSafeLinks.yml
  Packs/Microsoft365Defender/Integrations/O365DefenderSafeLinks/O365DefenderSafeLinks_description.md
  Packs/Microsoft365Defender/Integrations/O365DefenderSafeLinks/O365DefenderSafeLinks_image.png
  Packs/Microsoft365Defender/Integrations/O365DefenderSafeLinks/README.md
  Packs/Microsoft365Defender/Integrations/O365DefenderSafeLinks/test_data/create-policy.json
  Packs/Microsoft365Defender/Integrations/O365DefenderSafeLinks/test_data/list-policy.json
  Packs/Microsoft365Defender/Integrations/O365DefenderSafeLinks/test_data/list-rule.json
  Packs/Microsoft365Defender/ReleaseNotes/2_0_0.md
  Packs/Microsoft365Defender/pack_metadata.json
Labels: docs-approved

#15519 MicroFocus SMAX Integration
  Packs/MicroFocusSMAX/.pack-ignore
  Packs/MicroFocusSMAX/.secrets-ignore
  Packs/MicroFocusSMAX/Classifiers/classifier-Microfocus_SMAX_v1.json
  Packs/MicroFocusSMAX/Classifiers/classifier-mapper-incoming-MicroFocus_SMAX_v1.json
  Packs/MicroFocusSMAX/IncidentTypes/MicroFocus_SMAX_Incident.json
  Packs/MicroFocusSMAX/IncidentTypes/MicroFocus_SMAX_Request.json
  Packs/MicroFocusSMAX/Integrations/MicroFocusSMAX/MicroFocusSMAX.py
  Packs/MicroFocusSMAX/Integrations/MicroFocusSMAX/MicroFocusSMAX.yml
  Packs/MicroFocusSMAX/Integrations/MicroFocusSMAX/MicroFocusSMAX_description.md
  Packs/MicroFocusSMAX/Integrations/MicroFocusSMAX/MicroFocusSMAX_image.png
  Packs/MicroFocusSMAX/Integrations/MicroFocusSMAX/Pipfile
  Packs/MicroFocusSMAX/Integrations/MicroFocusSMAX/Pipfile.lock
  Packs/MicroFocusSMAX/Integrations/MicroFocusSMAX/README.md
  Packs/MicroFocusSMAX/Integrations/MicroFocusSMAX/command_examples
  Packs/MicroFocusSMAX/README.md
  Packs/MicroFocusSMAX/pack_metadata.json
Labels: Contribution, docs-approved, Contribution Form Filled, Community

#14802 MalwareBazaar Feed
  Packs/MalwareBazaar/.pack-ignore
  Packs/MalwareBazaar/.secrets-ignore
  Packs/MalwareBazaar/Integrations/MalwareBazaarFeed/MalwareBazaarFeed.py
  Packs/MalwareBazaar/Integrations/MalwareBazaarFeed/MalwareBazaarFeed.yml
  Packs/MalwareBazaar/Integrations/MalwareBazaarFeed/MalwareBazaarFeed_description.md
  Packs/MalwareBazaar/Integrations/MalwareBazaarFeed/MalwareBazaarFeed_image.png
  Packs/MalwareBazaar/Integrations/MalwareBazaarFeed/Pipfile
  Packs/MalwareBazaar/Integrations/MalwareBazaarFeed/Pipfile.lock
  Packs/MalwareBazaar/Integrations/MalwareBazaarFeed/README.md
  Packs/MalwareBazaar/Integrations/MalwareBazaarFeed/command_examples.txt
  Packs/MalwareBazaar/README.md
  Packs/MalwareBazaar/pack_metadata.json
  Tests/conf.json
Labels: docs-approved

#15645 Don't authenticate to GCS Market
  .circleci/config.yml
Labels: docs-approved

#14936 Anomali threat stream v3
  Packs/Anomali_ThreatStream/.secrets-ignore
  Packs/Anomali_ThreatStream/Integrations/AnomaliThreatStreamv3/AnomaliThreatStreamv3.py
  Packs/Anomali_ThreatStream/Integrations/AnomaliThreatStreamv3/AnomaliThreatStreamv3.yml
  Packs/Anomali_ThreatStream/Integrations/AnomaliThreatStreamv3/AnomaliThreatStreamv3_description.md
  Packs/Anomali_ThreatStream/Integrations/AnomaliThreatStreamv3/AnomaliThreatStreamv3_image.png
  Packs/Anomali_ThreatStream/Integrations/AnomaliThreatStreamv3/AnomaliThreatStreamv3_test.py
  Packs/Anomali_ThreatStream/Integrations/AnomaliThreatStreamv3/README.md
  Packs/Anomali_ThreatStream/Integrations/AnomaliThreatStreamv3/test_data/mocked_domain_response.json
  Packs/Anomali_ThreatStream/Integrations/AnomaliThreatStreamv3/test_data/mocked_file_response.json
  Packs/Anomali_ThreatStream/Integrations/AnomaliThreatStreamv3/test_data/mocked_get_commands_response.json
  Packs/Anomali_ThreatStream/Integrations/AnomaliThreatStreamv3/test_data/mocked_ip_response.json
  Packs/Anomali_ThreatStream/Integrations/AnomaliThreatStreamv3/test_data/mocked_url_response.json
  Packs/Anomali_ThreatStream/ReleaseNotes/2_0_0.md
  Packs/Anomali_ThreatStream/TestPlaybooks/playbook-ThreatStream-Test.yml
  Packs/Anomali_ThreatStream/pack_metadata.json
  Tests/conf.json
Labels: docs-approved

#15642 CVE description accessor fix
  Packs/CommonTypes/IndicatorTypes/reputation-cve.json
  Packs/CommonTypes/ReleaseNotes/3_1_21.md
  Packs/CommonTypes/pack_metadata.json
  Packs/NonSupported/IndicatorTypes/reputation-cve_5_4_9.json
Labels: docs-approved

#15651 update timeout for secrets run
  Utils/github_workflow_scripts/run_secrets_detection_get_playbook_status.py
Labels: docs-approved

#15650 directory name changed
  Packs/FeedMalwareBazaar/.pack-ignore
  Packs/FeedMalwareBazaar/.secrets-ignore
  Packs/FeedMalwareBazaar/Integrations/MalwareBazaarFeed/MalwareBazaarFeed.py
  Packs/FeedMalwareBazaar/Integrations/MalwareBazaarFeed/MalwareBazaarFeed.yml
  Packs/FeedMalwareBazaar/Integrations/MalwareBazaarFeed/MalwareBazaarFeed_description.md
  Packs/FeedMalwareBazaar/Integrations/MalwareBazaarFeed/MalwareBazaarFeed_image.png
  Packs/FeedMalwareBazaar/Integrations/MalwareBazaarFeed/Pipfile
  Packs/FeedMalwareBazaar/Integrations/MalwareBazaarFeed/Pipfile.lock
  Packs/FeedMalwareBazaar/Integrations/MalwareBazaarFeed/README.md
  Packs/FeedMalwareBazaar/Integrations/MalwareBazaarFeed/command_examples.txt
  Packs/FeedMalwareBazaar/README.md
  Packs/FeedMalwareBazaar/pack_metadata.json
Labels: docs-approved

#15641 Fix Failing GitHub Actions
  .github/workflows/check-contribution-form-filled.yml
  .github/workflows/create-internal-pr-from-external.yml
  .github/workflows/handle-new-external-pr.yml
  .github/workflows/handle-stale-branches.yml
  .github/workflows/sync-contribution-base-branch.yml
  Utils/github_workflow_scripts/Pipfile
  Utils/github_workflow_scripts/Pipfile.lock
Labels: docs-approved

#15485 Microsoft Teams - dev portal setup doc
  Packs/MicrosoftTeams/Integrations/MicrosoftTeams/README.md
  Packs/MicrosoftTeams/Integrations/MicrosoftTeams/doc_files/DemistoBot.zip
  Packs/MicrosoftTeams/Integrations/MicrosoftTeams/doc_files/appentry.png
Labels: docs-approved

#15647 Threat Intel - fix types ids
  Packs/ThreatIntel/GenericTypes/ThreatIntelReport/generictype-Campaign.json
  Packs/ThreatIntel/GenericTypes/ThreatIntelReport/generictype-ExecutiveBrief.json
  Packs/ThreatIntel/GenericTypes/ThreatIntelReport/generictype-Malware.json
  Packs/ThreatIntel/GenericTypes/ThreatIntelReport/generictype-ThreatActor.json
  Packs/ThreatIntel/GenericTypes/ThreatIntelReport/generictype-Vulnerability.json
  Packs/ThreatIntel/ReleaseNotes/1_0_11.md
  Packs/ThreatIntel/pack_metadata.json
Labels: docs-approved

#15640 Marketplace Services - populate generic field type
  Tests/Marketplace/marketplace_services.py
Labels: docs-approved

#15266 Add non indicator stix objects and add Relationships between Indicators
  Packs/CommonTypes/IndicatorFields/incidentfield-shortdescription.json
  Packs/CommonTypes/ReleaseNotes/3_1_22.md
  Packs/CommonTypes/pack_metadata.json
  Packs/FeedTAXII/.secrets-ignore
  Packs/FeedTAXII/IndicatorFields/indicatorfield-StixIndicatorDescription.json
  Packs/FeedTAXII/IndicatorFields/indicatorfield-StixIndicatorName.json
  Packs/FeedTAXII/IndicatorFields/indicatorfield-StixTTPTitle.json
  Packs/FeedTAXII/Integrations/FeedTAXII/FeedTAXII.py
  Packs/FeedTAXII/Integrations/FeedTAXII/FeedTAXII.yml
  Packs/FeedTAXII/Integrations/FeedTAXII/FeedTAXII_test.py
  Packs/FeedTAXII/Integrations/FeedTAXII/FeedTAXII_test/StixDecodeTest/domain-stix-ioc-result.json
  Packs/FeedTAXII/Integrations/FeedTAXII/FeedTAXII_test/StixDecodeTest/email-stix-ioc-result.json
  Packs/FeedTAXII/Integrations/FeedTAXII/FeedTAXII_test/StixDecodeTest/file-stix-ioc-result.json
  Packs/FeedTAXII/Integrations/FeedTAXII/FeedTAXII_test/StixDecodeTest/ip-stix-ioc-result.json
  Packs/FeedTAXII/Integrations/FeedTAXII/FeedTAXII_test/StixDecodeTest/ip-stix-ioc.xml
  Packs/FeedTAXII/Integrations/FeedTAXII/FeedTAXII_test/StixDecodeTest/ipv6-stix-ioc-result.json
  Packs/FeedTAXII/Integrations/FeedTAXII/FeedTAXII_test/StixDecodeTest/url-stix-ioc-result.json
  Packs/FeedTAXII/Integrations/FeedTAXII/FeedTAXII_test/TestCommands/collection_example.xml
  Packs/FeedTAXII/Integrations/FeedTAXII/FeedTAXII_test/TestCommands/indicators_example.json
  Packs/FeedTAXII/Integrations/FeedTAXII/FeedTAXII_test/TestCommands/indicators_results.json
  Packs/FeedTAXII/Integrations/FeedTAXII/README.md
  Packs/FeedTAXII/Integrations/FeedTAXII/command_example.txt
  Packs/FeedTAXII/ReleaseNotes/1_1_1.md
  Packs/FeedTAXII/pack_metadata.json
Labels: docs-approved, release-notes-only

#15465 Pre phishing alerts
  Packs/EWS/Classifiers/classifier-mapper-incoming-EWS_v2.json
  Packs/EWS/Playbooks/playbook-Get_Original_Email_-_EWS_v2.yml
  Packs/EWS/Playbooks/playbook-Get_Original_Email_-_EWS_v2_README.md
  Packs/EWS/ReleaseNotes/1_10_0.md
  Packs/EWS/TestPlaybooks/playbook-Get_Original_Email_-_EWS_v2_-_test.yml
  Packs/EWS/doc_imgs/Get_Original_Email_-_EWS_v2.png
  Packs/EWS/pack_metadata.json
  Packs/Gmail/.pack-ignore
  Packs/Gmail/.secrets-ignore
  Packs/Gmail/Classifiers/classifier-mapper-incoming-Gsuite-gmail.json
  Packs/Gmail/Playbooks/playbook-Get_Original_Email_-_Gmail_v2.yml
  Packs/Gmail/Playbooks/playbook-Get_Original_Email_-_Gmail_v2_README.md
  Packs/Gmail/ReleaseNotes/1_1_10.md
  Packs/Gmail/TestPlaybooks/playbook-Get_Original_Email_-_Gmail_v2_-_test.yml
  Packs/Gmail/doc_files/Get_Original_Email_-_Gmail_v2.png
  Packs/Gmail/pack_metadata.json
  Packs/MicrosoftGraphMail/.secrets-ignore
  Packs/MicrosoftGraphMail/Classifiers/classifier-Microsoft_Graph_Mail_Mapper.json
  Packs/MicrosoftGraphMail/Playbooks/playbook-Get_Original_Email_-_Microsoft_Graph_Mail.yml
  Packs/MicrosoftGraphMail/Playbooks/playbook-Get_Original_Email_-_Microsoft_Graph_Mail_README.md
  Packs/MicrosoftGraphMail/ReleaseNotes/1_1_0.md
  Packs/MicrosoftGraphMail/TestPlaybooks/playbook-Get_Original_Email_-_Microsoft_Graph_Mail_-_test.yml
  Packs/MicrosoftGraphMail/doc_files/Get_Original_Email_-_Microsoft_Graph_Mail.png
  Packs/MicrosoftGraphMail/pack_metadata.json
  Packs/Phishing/IncidentFields/incidentfield-Phishing_Reporter_Email_Headers.json
  Packs/Phishing/IncidentTypes/New_6_1/incidenttype-Phishing_6.1.json
  Packs/Phishing/Playbooks/Phishing_Investigation_-_Generic_v2_-_6_0.yml
  Packs/Phishing/Playbooks/Phishing_Investigation_-_Generic_v2_README.md
  Packs/Phishing/Playbooks/Process_Email_-_Generic_v2.yml
  Packs/Phishing/Playbooks/Process_Email_-_Generic_v2_README.md
  Packs/Phishing/Playbooks/playbook-Get_Original_Email_-_Generic_v2.yml
  Packs/Phishing/Playbooks/playbook-Get_Original_Email_-_Generic_v2_README.md
  Packs/Phishing/ReleaseNotes/2_5_0.md
  Packs/Phishing/doc_files/Get_Original_Email_-_Generic_v2.png
  Packs/Phishing/doc_files/Get_Original_Email_Gmail.png
  Packs/Phishing/doc_files/Phishing_Investigation_-_Generic_v2_-_6_0.png
  Packs/Phishing/doc_files/Process_Email_-_Generic_v2.png
  Packs/Phishing/pack_metadata.json
  Tests/conf.json
Labels: docs-approved, use-case

#15658 Re-add Anomali old test playbooks
  Tests/conf.json
Labels: docs-approved

#15659 [Zscaler] Changed Credentials to Username
  Packs/Zscaler/Integrations/Zscaler/README.md
  Packs/Zscaler/Integrations/Zscaler/Zscaler.yml
  Packs/Zscaler/ReleaseNotes/1_1_12.md
  Packs/Zscaler/pack_metadata.json
Labels: docs-approved

#15653 restrict coverage stats upload to master nightly only
  .gitlab/ci/global.yml
Labels: docs-approved

#15620 [QRadar] Add Default Timeout for Events Fetch and support_multithreading
  Packs/QRadar/Integrations/QRadar_v2/QRadar_v2.py
  Packs/QRadar/Integrations/QRadar_v2/QRadar_v2_test.py
  Packs/QRadar/Integrations/QRadar_v2/README.md
  Packs/QRadar/Integrations/QRadar_v3/QRadar_v3.py
  Packs/QRadar/Integrations/QRadar_v3/QRadar_v3_test.py
  Packs/QRadar/Integrations/QRadar_v3/README.md
  Packs/QRadar/ReleaseNotes/2_1_6.md
  Packs/QRadar/pack_metadata.json
Labels: docs-approved

#15656 GraphFiles and Mail Sender (New): Tpb update
  Packs/MailSenderNew/TestPlaybooks/playbook-Email_Sender_Python.yml
  Packs/MicrosoftGraphFiles/TestPlaybooks/MS_Graph_Files_-_Test.yml
Labels: docs-approved

#15655 [Marketplace Contribution] DNS-over-https (#15408)
  Packs/DNSOverHttps/.pack-ignore
  Packs/DNSOverHttps/.secrets-ignore
  Packs/DNSOverHttps/Integrations/DNSOverHttps/DNSOverHttps.py
  Packs/DNSOverHttps/Integrations/DNSOverHttps/DNSOverHttps.yml
  Packs/DNSOverHttps/Integrations/DNSOverHttps/DNSOverHttps_description.md
  Packs/DNSOverHttps/Integrations/DNSOverHttps/DNSOverHttps_image.png
  Packs/DNSOverHttps/Integrations/DNSOverHttps/Pipfile
  Packs/DNSOverHttps/Integrations/DNSOverHttps/Pipfile.lock
  Packs/DNSOverHttps/Integrations/DNSOverHttps/README.md
  Packs/DNSOverHttps/Integrations/DNSOverHttps/command_examples
  Packs/DNSOverHttps/README.md
  Packs/DNSOverHttps/pack_metadata.json
Labels: docs-approved

#15588 BaseClient class - fixed a bug when choosing xml as resp_type
  Packs/Base/ReleaseNotes/1_14_1.md
  Packs/Base/Scripts/CommonServerPython/CommonServerPython.py
  Packs/Base/pack_metadata.json
Labels: Contribution, docs-approved, Partner, Contribution Form Filled

#15573 EWS O365 Add Delegate Access Type
  Packs/EWS/Integrations/EWSO365/EWSO365.py
  Packs/EWS/Integrations/EWSO365/EWSO365.yml
  Packs/EWS/Integrations/EWSO365/README.md
  Packs/EWS/ReleaseNotes/1_10_1.md
  Packs/EWS/pack_metadata.json
Labels: docs-approved

#15613 update IPinfo vendor name to match context
  Packs/ipinfo/Integrations/ipinfo_v2/ipinfo_v2.py
  Packs/ipinfo/Integrations/ipinfo_v2/ipinfo_v2_test.py
  Packs/ipinfo/Integrations/ipinfo_v2/test_data/ip_1.1.1.1_command_results.json
  Packs/ipinfo/ReleaseNotes/2_1_0.md
  Packs/ipinfo/pack_metadata.json
Labels: docs-approved

#15178 remove PB110 ignore from several packs
  Packs/BruteForce/.pack-ignore
  Packs/CommonPlaybooks/.pack-ignore
  Packs/Malware/.pack-ignore
  Packs/Phishing/.pack-ignore
  Packs/SANS/.pack-ignore
  Packs/SANS/.secrets-ignore
Labels: docs-approved

#15482 removed server versions 5.0 & 5.5
  .circleci/config.yml
  .gitlab/ci/on-push.yml
  Tests/configure_and_test_integration_instances.py
  Tests/scripts/collect_tests_and_content_packs.py
  Tests/scripts/infrastructure_tests/test_collect_tests_and_content_packs.py
  Tests/scripts/wait_until_server_ready.py
Labels: docs-approved

#15666 Giphy detailed description
  Packs/Giphy/Integrations/integration-Giphy.yml
  Packs/Giphy/ReleaseNotes/1_0_1.md
  Packs/Giphy/pack_metadata.json
Labels: docs-approved

#15661 MicroFocus SMAX Integration (#15519)
  Packs/MicroFocusSMAX/.pack-ignore
  Packs/MicroFocusSMAX/.secrets-ignore
  Packs/MicroFocusSMAX/Classifiers/classifier-Microfocus_SMAX_v1.json
  Packs/MicroFocusSMAX/Classifiers/classifier-mapper-incoming-MicroFocus_SMAX_v1.json
  Packs/MicroFocusSMAX/IncidentTypes/MicroFocus_SMAX_Incident.json
  Packs/MicroFocusSMAX/IncidentTypes/MicroFocus_SMAX_Request.json
  Packs/MicroFocusSMAX/Integrations/MicroFocusSMAX/MicroFocusSMAX.py
  Packs/MicroFocusSMAX/Integrations/MicroFocusSMAX/MicroFocusSMAX.yml
  Packs/MicroFocusSMAX/Integrations/MicroFocusSMAX/MicroFocusSMAX_description.md
  Packs/MicroFocusSMAX/Integrations/MicroFocusSMAX/MicroFocusSMAX_image.png
  Packs/MicroFocusSMAX/Integrations/MicroFocusSMAX/Pipfile
  Packs/MicroFocusSMAX/Integrations/MicroFocusSMAX/Pipfile.lock
  Packs/MicroFocusSMAX/Integrations/MicroFocusSMAX/README.md
  Packs/MicroFocusSMAX/Integrations/MicroFocusSMAX/command_examples
  Packs/MicroFocusSMAX/README.md
  Packs/MicroFocusSMAX/pack_metadata.json
Labels: docs-approved

#15550 Update README.md
  Packs/knowbe4Phisher/Integrations/knowbe4Phisher/README.md
  Packs/knowbe4Phisher/pack_metadata.json
Labels: Contribution, docs-approved, Contribution Form Filled, Community

#15362 Archer bug with api endpoint param
  Packs/ArcherRSA/Integrations/ArcherV2/ArcherV2.py
  Packs/ArcherRSA/Integrations/ArcherV2/ArcherV2.yml
  Packs/ArcherRSA/ReleaseNotes/1_1_26.md
  Packs/ArcherRSA/pack_metadata.json
Labels: bug, docs-approved, release-notes-only

#15671 added timeout
  Tests/conf.json
Labels: docs-approved

#15648 Knowbe4 auth fix1
  Packs/knowbe4Phisher/Integrations/knowbe4Phisher/knowbe4Phisher.yml
  Packs/knowbe4Phisher/ReleaseNotes/1_0_2.md
  Packs/knowbe4Phisher/pack_metadata.json
Labels: docs-approved

#15673 Microsoft Teams - update zip link in README
  Packs/MicrosoftTeams/Integrations/MicrosoftTeams/README.md
Labels: docs-approved

#15668 add toVersion for mention widget
  Packs/CommonWidgets/ReleaseNotes/1_2_0.json
  Packs/CommonWidgets/ReleaseNotes/1_2_0.md
  Packs/CommonWidgets/Widgets/widget-MyMentions.json
  Packs/CommonWidgets/pack_metadata.json
Labels: docs-approved

#15551 Update README.md
  Packs/Jira/Integrations/JiraV2/README.md
Labels: Contribution, docs-approved

#15676 Fix Microsoft ATP test playbook
  Packs/MicrosoftDefenderAdvancedThreatProtection/TestPlaybooks/playbook-Microsoft_Defender_Advanced_Threat_Protection-Test.yml
Labels: docs-approved

#15652 Fix service now v2 escape
  Packs/ServiceNow/Integrations/ServiceNowv2/ServiceNowv2.py
  Packs/ServiceNow/Integrations/ServiceNowv2/ServiceNowv2_test.py
  Packs/ServiceNow/ReleaseNotes/2_2_12.md
  Packs/ServiceNow/pack_metadata.json
Labels: docs-approved

#15630 Fix custom handle indicator function def
  Packs/FeedIntel471/Integrations/Intel471Actors/Intel471Actors.py
  Packs/FeedIntel471/Integrations/Intel471Malware/Intel471Malware.py
  Packs/FeedIntel471/Integrations/Intel471MalwareIndicator/Intel471MalwareIndicator.py
  Packs/FeedIntel471/Integrations/Intel471WatcherAlerts/Intel471WatcherAlerts.py
  Packs/FeedIntel471/ReleaseNotes/2_0_6.md
  Packs/FeedIntel471/pack_metadata.json
Labels: Contribution, docs-approved, Partner, Contribution Form Filled

#15675 add packs to ignore
  Packs/FeedTAXII/.pack-ignore
  Packs/Palo_Alto_Networks_WildFire/.pack-ignore
  Packs/SalesforceFusion/.pack-ignore
  Tests/configure_and_test_integration_instances.py
Labels: docs-approved

#15390 Add integration for ZeroTrustAnalyticsPlatform
  Packs/ZeroTrustAnalyticsPlatform/.pack-ignore
  Packs/ZeroTrustAnalyticsPlatform/.secrets-ignore
  Packs/ZeroTrustAnalyticsPlatform/Author_image.png
  Packs/ZeroTrustAnalyticsPlatform/Classifiers/classifier-mapper-incoming-ZTAP_Alert.json
  Packs/ZeroTrustAnalyticsPlatform/Classifiers/classifier-mapper-outgoing-ZeroTrustAnalyticsPlatform.json
  Packs/ZeroTrustAnalyticsPlatform/IncidentFields/ZTAP_Alert_ID.json
  Packs/ZeroTrustAnalyticsPlatform/IncidentFields/ZTAP_Assigned_Organization.json
  Packs/ZeroTrustAnalyticsPlatform/IncidentFields/ZTAP_Input_Tag.json
  Packs/ZeroTrustAnalyticsPlatform/IncidentFields/ZTAP_Priority.json
  Packs/ZeroTrustAnalyticsPlatform/IncidentFields/ZTAP_Product_Status.json
  Packs/ZeroTrustAnalyticsPlatform/IncidentFields/ZTAP_Source_Organization.json
  Packs/ZeroTrustAnalyticsPlatform/IncidentFields/ZTAP_Status.json
  Packs/ZeroTrustAnalyticsPlatform/IncidentFields/ZTAP_Trigger_Count.json
  Packs/ZeroTrustAnalyticsPlatform/IncidentFields/ZTAP_Triggers.json
  Packs/ZeroTrustAnalyticsPlatform/IncidentTypes/ZTAP_Alert.json
  Packs/ZeroTrustAnalyticsPlatform/Integrations/ZeroTrustAnalyticsPlatform/Pipfile
  Packs/ZeroTrustAnalyticsPlatform/Integrations/ZeroTrustAnalyticsPlatform/Pipfile.lock
  Packs/ZeroTrustAnalyticsPlatform/Integrations/ZeroTrustAnalyticsPlatform/README.md
  Packs/ZeroTrustAnalyticsPlatform/Integrations/ZeroTrustAnalyticsPlatform/ZeroTrustAnalyticsPlatform.py
  Packs/ZeroTrustAnalyticsPlatform/Integrations/ZeroTrustAnalyticsPlatform/ZeroTrustAnalyticsPlatform.yml
  Packs/ZeroTrustAnalyticsPlatform/Integrations/ZeroTrustAnalyticsPlatform/ZeroTrustAnalyticsPlatform_description.md
  Packs/ZeroTrustAnalyticsPlatform/Integrations/ZeroTrustAnalyticsPlatform/ZeroTrustAnalyticsPlatform_image.png
  Packs/ZeroTrustAnalyticsPlatform/Integrations/ZeroTrustAnalyticsPlatform/ZeroTrustAnalyticsPlatform_test.py
  Packs/ZeroTrustAnalyticsPlatform/Integrations/ZeroTrustAnalyticsPlatform/command_examples
  Packs/ZeroTrustAnalyticsPlatform/Integrations/ZeroTrustAnalyticsPlatform/test_data/api_data.py
  Packs/ZeroTrustAnalyticsPlatform/Integrations/ZeroTrustAnalyticsPlatform/test_data/xsoar_data.py
  Packs/ZeroTrustAnalyticsPlatform/Layouts/layoutscontainer-ZTAP_Alert.json
  Packs/ZeroTrustAnalyticsPlatform/Playbooks/playbook-ZTAP_Alert.yml
  Packs/ZeroTrustAnalyticsPlatform/Playbooks/playbook-ZTAP_Alert_README.md
  Packs/ZeroTrustAnalyticsPlatform/README.md
  Packs/ZeroTrustAnalyticsPlatform/Scripts/ZTAPBuildTimeline/README.md
  Packs/ZeroTrustAnalyticsPlatform/Scripts/ZTAPBuildTimeline/ZTAPBuildTimeline.py
  Packs/ZeroTrustAnalyticsPlatform/Scripts/ZTAPBuildTimeline/ZTAPBuildTimeline.yml
  Packs/ZeroTrustAnalyticsPlatform/Scripts/ZTAPBuildTimeline/ZTAPBuildTimeline_test.py
  Packs/ZeroTrustAnalyticsPlatform/Scripts/ZTAPBuildTimeline/test_data/entries.json
  Packs/ZeroTrustAnalyticsPlatform/Scripts/ZTAPBuildTimeline/test_data/output.json
  Packs/ZeroTrustAnalyticsPlatform/Scripts/ZTAPExtractFields/README.md
  Packs/ZeroTrustAnalyticsPlatform/Scripts/ZTAPExtractFields/ZTAPExtractFields.py
  Packs/ZeroTrustAnalyticsPlatform/Scripts/ZTAPExtractFields/ZTAPExtractFields.yml
  Packs/ZeroTrustAnalyticsPlatform/Scripts/ZTAPExtractFields/ZTAPExtractFields_test.py
  Packs/ZeroTrustAnalyticsPlatform/Scripts/ZTAPExtractFields/test_data/event.json
  Packs/ZeroTrustAnalyticsPlatform/Scripts/ZTAPExtractFields/test_data/output.json
  Packs/ZeroTrustAnalyticsPlatform/Scripts/ZTAPParseFields/README.md
  Packs/ZeroTrustAnalyticsPlatform/Scripts/ZTAPParseFields/ZTAPParseFields.py
  Packs/ZeroTrustAnalyticsPlatform/Scripts/ZTAPParseFields/ZTAPParseFields.yml
  Packs/ZeroTrustAnalyticsPlatform/Scripts/ZTAPParseFields/ZTAPParseFields_test.py
  Packs/ZeroTrustAnalyticsPlatform/Scripts/ZTAPParseFields/test_data/event.json
  Packs/ZeroTrustAnalyticsPlatform/Scripts/ZTAPParseFields/test_data/output-full.md
  Packs/ZeroTrustAnalyticsPlatform/Scripts/ZTAPParseFields/test_data/output-truncated.md
  Packs/ZeroTrustAnalyticsPlatform/Scripts/ZTAPParseLinks/README.md
  Packs/ZeroTrustAnalyticsPlatform/Scripts/ZTAPParseLinks/ZTAPParseLinks.py
  Packs/ZeroTrustAnalyticsPlatform/Scripts/ZTAPParseLinks/ZTAPParseLinks.yml
  Packs/ZeroTrustAnalyticsPlatform/Scripts/ZTAPParseLinks/ZTAPParseLinks_test.py
  Packs/ZeroTrustAnalyticsPlatform/Scripts/ZTAPParseLinks/test_data/events.json
  Packs/ZeroTrustAnalyticsPlatform/Scripts/ZTAPParseLinks/test_data/output.md
  Packs/ZeroTrustAnalyticsPlatform/doc_files/playbook-ZTAP_Alert.png
  Packs/ZeroTrustAnalyticsPlatform/pack_metadata.json
Labels: Contribution, docs-approved, Partner, Contribution Form Filled

#15681 [QRadar v2] Stabilize Unit Tests
  Packs/QRadar/Integrations/QRadar_v2/QRadar_v2_test.py
Labels: docs-approved

#15283 Ansible Integrations Test Playbooks
  Packs/AnsibleAlibabaCloud/Integrations/AnsibleAlibabaCloud/AnsibleAlibabaCloud.yml
  Packs/AnsibleAlibabaCloud/ReleaseNotes/1_0_1.md
  Packs/AnsibleAlibabaCloud/pack_metadata.json
  Packs/AnsibleAzure/Integrations/AnsibleAzure/AnsibleAzure.yml
  Packs/AnsibleAzure/ReleaseNotes/1_0_1.md
  Packs/AnsibleAzure/TestPlaybooks/Test-AnsibleAzure.yml
  Packs/AnsibleAzure/pack_metadata.json
  Packs/AnsibleCiscoIOS/Integrations/AnsibleCiscoIOS/AnsibleCiscoIOS.yml
  Packs/AnsibleCiscoIOS/Integrations/AnsibleCiscoIOS/AnsibleCiscoIOS_description.md
  Packs/AnsibleCiscoIOS/Integrations/AnsibleCiscoIOS/README.md
  Packs/AnsibleCiscoIOS/ReleaseNotes/1_0_1.md
  Packs/AnsibleCiscoIOS/TestPlaybooks/Test-AnsibleCiscoIOS.yml
  Packs/AnsibleCiscoIOS/pack_metadata.json
  Packs/AnsibleCiscoNXOS/Integrations/AnsibleCiscoNXOS/AnsibleCiscoNXOS.yml
  Packs/AnsibleCiscoNXOS/Integrations/AnsibleCiscoNXOS/README.md
  Packs/AnsibleCiscoNXOS/ReleaseNotes/1_0_1.md
  Packs/AnsibleCiscoNXOS/TestPlaybooks/Test-AnsibleCiscoNXOS.yml
  Packs/AnsibleCiscoNXOS/pack_metadata.json
  Packs/AnsibleHetznerCloud/Integrations/AnsibleHCloud/AnsibleHCloud.yml
  Packs/AnsibleHetznerCloud/ReleaseNotes/1_0_1.md
  Packs/AnsibleHetznerCloud/pack_metadata.json
  Packs/AnsibleKubernetes/Integrations/AnsibleKubernetes/AnsibleKubernetes.yml
  Packs/AnsibleKubernetes/Integrations/AnsibleKubernetes/AnsibleKubernetes_description.md
  Packs/AnsibleKubernetes/Integrations/AnsibleKubernetes/README.md
  Packs/AnsibleKubernetes/ReleaseNotes/1_0_1.md
  Packs/AnsibleKubernetes/TestPlaybooks/Test-AnsibleKubernetes.yml
  Packs/AnsibleKubernetes/pack_metadata.json
  Packs/AnsibleLinux/Integrations/AnsibleACME/AnsibleACME.yml
  Packs/AnsibleLinux/Integrations/AnsibleDNS/AnsibleDNS.yml
  Packs/AnsibleLinux/Integrations/AnsibleLinux/AnsibleLinux.yml
  Packs/AnsibleLinux/Integrations/AnsibleLinux/README.md
  Packs/AnsibleLinux/Integrations/AnsibleOpenSSL/AnsibleOpenSSL.yml
  Packs/AnsibleLinux/ReleaseNotes/1_0_1.md
  Packs/AnsibleLinux/TestPlaybooks/Test-AnsibleLinux.yml
  Packs/AnsibleLinux/pack_metadata.json
  Packs/AnsibleMicrosoftWindows/Integrations/AnsibleMicrosoftWindows/AnsibleMicrosoftWindows.yml
  Packs/AnsibleMicrosoftWindows/Integrations/AnsibleMicrosoftWindows/README.md
  Packs/AnsibleMicrosoftWindows/ReleaseNotes/1_0_1.md
  Packs/AnsibleMicrosoftWindows/TestPlaybooks/Test-AnsibleWindows.yml
  Packs/AnsibleMicrosoftWindows/pack_metadata.json
  Packs/AnsibleVMware/Integrations/AnsibleVMware/AnsibleVMware.yml
  Packs/AnsibleVMware/Integrations/AnsibleVMware/README.md
  Packs/AnsibleVMware/ReleaseNotes/1_0_1.md
  Packs/AnsibleVMware/TestPlaybooks/Test-AnsibleVMware.yml
  Packs/AnsibleVMware/pack_metadata.json
  Tests/conf.json
Labels: Contribution, docs-approved, Contribution Form Filled

#15224 upload MalwareBazaar
  Packs/MalwareBazaar/.pack-ignore
  Packs/MalwareBazaar/.secrets-ignore
  Packs/MalwareBazaar/Integrations/MalwareBazaar/MalwareBazaar.py
  Packs/MalwareBazaar/Integrations/MalwareBazaar/MalwareBazaar.yml
  Packs/MalwareBazaar/Integrations/MalwareBazaar/MalwareBazaar_description.md
  Packs/MalwareBazaar/Integrations/MalwareBazaar/MalwareBazaar_image.png
  Packs/MalwareBazaar/Integrations/MalwareBazaar/MalwareBazaar_test.py
  Packs/MalwareBazaar/Integrations/MalwareBazaar/Pipfile
  Packs/MalwareBazaar/Integrations/MalwareBazaar/Pipfile.lock
  Packs/MalwareBazaar/Integrations/MalwareBazaar/README.md
  Packs/MalwareBazaar/Integrations/MalwareBazaar/command_examples
  Packs/MalwareBazaar/Integrations/MalwareBazaar/test_data/response_data_dbot_score.json
  Packs/MalwareBazaar/Integrations/MalwareBazaar/test_data/samples_list_results.json
  Packs/MalwareBazaar/Integrations/MalwareBazaar/test_data/scan_file_results.json
  Packs/MalwareBazaar/README.md
  Packs/MalwareBazaar/TestPlaybooks/MalwareBazaar_Test.yml
  Packs/MalwareBazaar/pack_metadata.json
  Tests/conf.json
Labels: docs-approved

#15343 Updated descriptions for Prisma Cloud classifiers and mappers
  Packs/PrismaCloud/Classifiers/classifier-Prisma_Cloud.json
  Packs/PrismaCloud/Classifiers/classifier-mapper-incoming-Prisma_Cloud.json
  Packs/PrismaCloud/Classifiers/classifier-mapper-incoming-prismaCloud_app.json
  Packs/PrismaCloud/Classifiers/classifier-prismaCloud_app.json
  Packs/PrismaCloud/ReleaseNotes/2_0_2.md
  Packs/PrismaCloud/pack_metadata.json
Labels: docs-approved

#15685 Fixing test failures for PAN-OS playbooks
  Tests/conf.json
Labels: docs-approved

#15686 Unsearchable field hello world
  Packs/HelloWorld/IncidentFields/incidentfield-Hello_World_ID.json
  Packs/HelloWorld/ReleaseNotes/1_2_9.md
  Packs/HelloWorld/pack_metadata.json
Labels: docs-approved

#15354 XDR mirroring bug fix
  Packs/CortexXDR/Integrations/CortexXDRIR/CortexXDRIR.py
  Packs/CortexXDR/ReleaseNotes/4_1_11.md
  Packs/CortexXDR/pack_metadata.json
Labels: bug, docs-approved, release-notes-only

#15692 Case MGMT - rm fin from readme
  Packs/CaseManagement-Generic/README.md
Labels: docs-approved

#15481 Added C2 Attribution Commands
  Packs/HYASInsight/.secrets-ignore
  Packs/HYASInsight/Integrations/HYASInsight/HYASInsight.py
  Packs/HYASInsight/Integrations/HYASInsight/HYASInsight.yml
  Packs/HYASInsight/Integrations/HYASInsight/HYASInsight_description.md
  Packs/HYASInsight/Integrations/HYASInsight/HYASInsight_test.py
  Packs/HYASInsight/Integrations/HYASInsight/README.md
  Packs/HYASInsight/Integrations/HYASInsight/command_examples
  Packs/HYASInsight/Integrations/HYASInsight/test_data/c2_attribution_response.json
  Packs/HYASInsight/README.md
  Packs/HYASInsight/ReleaseNotes/1_0_3.md
  Packs/HYASInsight/TestPlaybooks/Playbook-HYASInsight-Test.yml
  Packs/HYASInsight/pack_metadata.json
Labels: Contribution, docs-approved, Partner, post-demo, Contribution Form Filled

#15684 fix coverage url
  .circleci/config.yml
  .gitlab/ci/global.yml
  .hooks/pre-commit
  Utils/upload_code_coverage_report.py
Labels: docs-approved

#15662 XDR IOC Catch 404
  Packs/CortexXDR/Integrations/XDR_iocs/XDR_iocs.py
  Packs/CortexXDR/Integrations/XDR_iocs/XDR_iocs_test.py
  Packs/CortexXDR/ReleaseNotes/4_1_12.md
  Packs/CortexXDR/pack_metadata.json
Labels: docs-approved

#15638 ParseHTMLIndicators enhancement
  Packs/CommonScripts/ReleaseNotes/1_5_1.md
  Packs/CommonScripts/Scripts/ParseHTMLIndicators/ParseHTMLIndicators.py
  Packs/CommonScripts/Scripts/ParseHTMLIndicators/ParseHTMLIndicators.yml
  Packs/CommonScripts/Scripts/ParseHTMLIndicators/Pipfile
  Packs/CommonScripts/Scripts/ParseHTMLIndicators/Pipfile.lock
  Packs/CommonScripts/Scripts/ParseHTMLIndicators/README.md
  Packs/CommonScripts/TestPlaybooks/ParseHTMLIndicators-Test.yml
  Packs/CommonScripts/pack_metadata.json
  Tests/conf.json
Labels: docs-approved, release-notes-only

#15415 updated indicator field to support open ended
  Packs/CommonTypes/IndicatorFields/incidentfield-associatedfilenames.json
  Packs/CommonTypes/ReleaseNotes/3_1_21.md
  Packs/CommonTypes/ReleaseNotes/3_1_23.md
  Packs/CommonTypes/pack_metadata.json
Labels: docs-approved, release-notes-only

#15667 Twitter Integration | fixed issue where `created_at` param includes spaces
  Packs/Twitter/Integrations/Twitter/Twitter.py
  Packs/Twitter/ReleaseNotes/1_1_0.md
  Packs/Twitter/pack_metadata.json
Labels: docs-approved

#15700 remove centreon from skipped
  Tests/conf.json
Labels: docs-approved

#15627 feature: add Qintel pack
  Packs/Qintel/.pack-ignore
  Packs/Qintel/.secrets-ignore
  Packs/Qintel/Author_image.png
  Packs/Qintel/IncidentFields/incidentfield-QWatch_Exposures.json
  Packs/Qintel/IncidentTypes/incidenttype-Qintel_-_QWatch_Alert.json
  Packs/Qintel/Integrations/QintelPMI/Pipfile
  Packs/Qintel/Integrations/QintelPMI/Pipfile.lock
  Packs/Qintel/Integrations/QintelPMI/QintelPMI.py
  Packs/Qintel/Integrations/QintelPMI/QintelPMI.yml
  Packs/Qintel/Integrations/QintelPMI/QintelPMI_description.md
  Packs/Qintel/Integrations/QintelPMI/QintelPMI_image.png
  Packs/Qintel/Integrations/QintelPMI/QintelPMI_test.py
  Packs/Qintel/Integrations/QintelPMI/README.md
  Packs/Qintel/Integrations/QintelPMI/test_data/cve_command.json
  Packs/Qintel/Integrations/QintelPMI/test_data/cve_command_empty.json
  Packs/Qintel/Integrations/QintelPMI/test_data/test_module.json
  Packs/Qintel/Integrations/QintelQSentry/Pipfile
  Packs/Qintel/Integrations/QintelQSentry/Pipfile.lock
  Packs/Qintel/Integrations/QintelQSentry/QintelQSentry.py
  Packs/Qintel/Integrations/QintelQSentry/QintelQSentry.yml
  Packs/Qintel/Integrations/QintelQSentry/QintelQSentry_description.md
  Packs/Qintel/Integrations/QintelQSentry/QintelQSentry_image.png
  Packs/Qintel/Integrations/QintelQSentry/QintelQSentry_test.py
  Packs/Qintel/Integrations/QintelQSentry/README.md
  Packs/Qintel/Integrations/QintelQSentry/test_data/ip_command.json
  Packs/Qintel/Integrations/QintelQSentry/test_data/test_module.json
  Packs/Qintel/Integrations/QintelQWatch/Pipfile
  Packs/Qintel/Integrations/QintelQWatch/Pipfile.lock
  Packs/Qintel/Integrations/QintelQWatch/QintelQWatch.py
  Packs/Qintel/Integrations/QintelQWatch/QintelQWatch.yml
  Packs/Qintel/Integrations/QintelQWatch/QintelQWatch_description.md
  Packs/Qintel/Integrations/QintelQWatch/QintelQWatch_image.png
  Packs/Qintel/Integrations/QintelQWatch/QintelQWatch_test.py
  Packs/Qintel/Integrations/QintelQWatch/README.md
  Packs/Qintel/Integrations/QintelQWatch/test_data/qwatch_data.json
  Packs/Qintel/Integrations/QintelQWatch/test_data/qwatch_data_empty.json
  Packs/Qintel/Integrations/QintelQWatch/test_data/test_module.json
  Packs/Qintel/Layouts/layoutscontainer-Qintel_-_QWatch_Alert.json
  Packs/Qintel/Playbooks/playbook-Indicator_Enrichment_-_Qintel.yml
  Packs/Qintel/Playbooks/playbook-Indicator_Enrichment_-_Qintel_README.md
  Packs/Qintel/Playbooks/playbook-Process_QWatch_Alert_-_Qintel.yml
  Packs/Qintel/Playbooks/playbook-Process_QWatch_Alert_-_Qintel_README.md
  Packs/Qintel/README.md
  Packs/Qintel/TestPlaybooks/QintelPMI-Test.yml
  Packs/Qintel/TestPlaybooks/QintelQSentry-Test.yml
  Packs/Qintel/TestPlaybooks/QintelQWatch-Test.yml
  Packs/Qintel/doc_files/Indicator_Enrichment_-_Qintel.png
  Packs/Qintel/doc_files/Process_QWatch_Alert_-_Qintel.png
  Packs/Qintel/pack_metadata.json
Labels: Contribution, docs-approved, Partner, Contribution Form Filled

#15706 [Fix] QRadar v2 2.1.6 fetch duplicates
  Packs/QRadar/Integrations/QRadar_v2/QRadar_v2.py
  Packs/QRadar/ReleaseNotes/2_1_7.md
  Packs/QRadar/pack_metadata.json
Labels: bug, docs-approved

#15618 Jira Add Authentication
  Packs/Jira/Integrations/JiraV2/JiraV2.py
  Packs/Jira/Integrations/JiraV2/JiraV2.yml
  Packs/Jira/Integrations/JiraV2/JiraV2_description.md
  Packs/Jira/Integrations/JiraV2/JiraV2_test.py
  Packs/Jira/Integrations/JiraV2/README.md
  Packs/Jira/ReleaseNotes/1_3_9.md
  Packs/Jira/pack_metadata.json
Labels: docs-approved

#15709 [Deprecate] MITRE ATT&CK Feed + Unit42 Feed
  Packs/FeedMitreAttack/Integrations/FeedMitreAttack/FeedMitreAttack.yml
  Packs/FeedMitreAttack/Integrations/FeedMitreAttack/README.md
  Packs/FeedMitreAttack/ReleaseNotes/1_2_0.md
  Packs/FeedMitreAttack/pack_metadata.json
  Packs/FeedUnit42/Integrations/FeedUnit42/FeedUnit42.yml
  Packs/FeedUnit42/Integrations/FeedUnit42/README.md
  Packs/FeedUnit42/ReleaseNotes/1_2_0.md
  Packs/FeedUnit42/pack_metadata.json
Labels: docs-approved

#15696 DefenderSafeLinks: Add note about cred object
  Packs/Microsoft365Defender/Integrations/O365DefenderSafeLinks/O365DefenderSafeLinks_description.md
  Packs/Microsoft365Defender/ReleaseNotes/2_0_1.md
  Packs/Microsoft365Defender/doc_files/credentials_example.png
  Packs/Microsoft365Defender/pack_metadata.json
Labels: bug, docs-approved

#15710 add egg to requirements-py3 for demisto-sdk
  dev-requirements-py3.txt
Labels: docs-approved

#15584 Xsoar firemon sm
  Packs/FireMonSecurityManager/.pack-ignore
  Packs/FireMonSecurityManager/.secrets-ignore
  Packs/FireMonSecurityManager/Author_image.png
  Packs/FireMonSecurityManager/IncidentFields/incidentfield-FireMonSecurityManager-Action.json
  Packs/FireMonSecurityManager/IncidentFields/incidentfield-FireMonSecurityManager-Destination.json
  Packs/FireMonSecurityManager/IncidentFields/incidentfield-FireMonSecurityManager-Device_Group_Id.json
  Packs/FireMonSecurityManager/IncidentFields/incidentfield-FireMonSecurityManager-Domain_Id.json
  Packs/FireMonSecurityManager/IncidentFields/incidentfield-FireMonSecurityManager-PP_Ticket_Due_Date.json
  Packs/FireMonSecurityManager/IncidentFields/incidentfield-FireMonSecurityManager-Priority.json
  Packs/FireMonSecurityManager/IncidentFields/incidentfield-FireMonSecurityManager-Requirements.json
  Packs/FireMonSecurityManager/IncidentFields/incidentfield-FireMonSecurityManager-Service.json
  Packs/FireMonSecurityManager/IncidentFields/incidentfield-FireMonSecurityManager-Source.json
  Packs/FireMonSecurityManager/IncidentFields/incidentfield-FireMonSecurityManager-Workflow_Name.json
  Packs/FireMonSecurityManager/IncidentTypes/incidenttype-FireMonSecurityManager-FireMon_Policy_Planner.json
  Packs/FireMonSecurityManager/IncidentTypes/incidenttype-FireMonSecurityManager-FireMon_Pre_Change_Assessment.json
  Packs/FireMonSecurityManager/Integrations/FireMonSecurityManager/FireMonSecurityManager.py
  Packs/FireMonSecurityManager/Integrations/FireMonSecurityManager/FireMonSecurityManager.yml
  Packs/FireMonSecurityManager/Integrations/FireMonSecurityManager/FireMonSecurityManager_description.md
  Packs/FireMonSecurityManager/Integrations/FireMonSecurityManager/FireMonSecurityManager_image.png
  Packs/FireMonSecurityManager/Integrations/FireMonSecurityManager/FireMonSecurityManager_test.py
  Packs/FireMonSecurityManager/Integrations/FireMonSecurityManager/test_data/get_authentication.json
  Packs/FireMonSecurityManager/Integrations/FireMonSecurityManager/test_data/get_pca.json
  Packs/FireMonSecurityManager/Integrations/FireMonSecurityManager/test_data/get_pp_ticket.json
  Packs/FireMonSecurityManager/Integrations/FireMonSecurityManager/test_data/get_rule_rec.json
  Packs/FireMonSecurityManager/Integrations/FireMonSecurityManager/test_data/get_workflows.json
  Packs/FireMonSecurityManager/Layouts/layoutscontainer-FireMon_Incident_Policy_Planner.json
  Packs/FireMonSecurityManager/Layouts/layoutscontainer-FireMon_Incident_Pre_Change_Assessment.json
  Packs/FireMonSecurityManager/Playbooks/playbook-FireMon_Create_Policy_Planner_Ticket.png
  Packs/FireMonSecurityManager/Playbooks/playbook-FireMon_Create_Policy_Planner_Ticket.yml
  Packs/FireMonSecurityManager/Playbooks/playbook-FireMon_Create_Policy_Planner_Ticket_README.md
  Packs/FireMonSecurityManager/Playbooks/playbook-FireMon_Pre_Change_Assessment.png
  Packs/FireMonSecurityManager/Playbooks/playbook-FireMon_Pre_Change_Assessment.yml
  Packs/FireMonSecurityManager/Playbooks/playbook-FireMon_Pre_Change_Assessment_README.md
  Packs/FireMonSecurityManager/README.md
  Packs/FireMonSecurityManager/pack_metadata.json
  Packs/FireMonSecurityManager/secrets_white_list.json
Labels: Contribution, docs-approved, Contribution Form Filled

#15490 Block ip v3 pb
  Packs/CiscoFirepower/Playbooks/Cisco_FirePower-_Append_network_group_object.yml
  Packs/CiscoFirepower/Playbooks/Cisco_FirePower-_Append_network_group_object_README.md
  Packs/CiscoFirepower/README.md
  Packs/CiscoFirepower/ReleaseNotes/1_1_0.md
  Packs/CiscoFirepower/doc_files/Cisco_FirePower-_Append_network_group_object.png
  Packs/CiscoFirepower/pack_metadata.json
  Packs/CommonPlaybooks/.secrets-ignore
  Packs/CommonPlaybooks/Playbooks/playbook-Block_IP_-_Generic_v3.yml
  Packs/CommonPlaybooks/Playbooks/playbook-Block_IP_-_Generic_v3_README.md
  Packs/CommonPlaybooks/ReleaseNotes/2_1_0.md
  Packs/CommonPlaybooks/TestPlaybooks/playbook-Block_IP_-_Generic_V3_Test.yml
  Packs/CommonPlaybooks/doc_files/Block_IP_-_Generic_v3.png
  Packs/CommonPlaybooks/pack_metadata.json
  Tests/conf.json
Labels: docs-approved

#15689 Added an argument (flags) to support some pattern matching options
  Packs/MapPattern/ReleaseNotes/1_0_2.md
  Packs/MapPattern/Scripts/MapPattern/MapPattern.py
  Packs/MapPattern/Scripts/MapPattern/MapPattern.yml
  Packs/MapPattern/Scripts/MapPattern/Pipfile
  Packs/MapPattern/Scripts/MapPattern/Pipfile.lock
  Packs/MapPattern/Scripts/MapPattern/README.md
  Packs/MapPattern/pack_metadata.json
Labels: Contribution, docs-approved, Contribution Form Filled, Community

#15691 Added an argument (flags) to support some pattern matching options
  Packs/CommonScripts/ReleaseNotes/1_5_2.md
  Packs/CommonScripts/Scripts/RegexGroups/Pipfile
  Packs/CommonScripts/Scripts/RegexGroups/Pipfile.lock
  Packs/CommonScripts/Scripts/RegexGroups/README.md
  Packs/CommonScripts/Scripts/RegexGroups/RegexGroups.py
  Packs/CommonScripts/Scripts/RegexGroups/RegexGroups.yml
  Packs/CommonScripts/pack_metadata.json
Labels: Contribution, docs-approved, Contribution Form Filled, Community

#15646 Incident layout widget scripts
  Packs/Base/ReleaseNotes/1_15_0.md
  Packs/Base/Scripts/CommonServerPython/CommonServerPython.py
  Packs/Base/Scripts/CommonServerPython/CommonServerPython_test.py
  Packs/Base/pack_metadata.json
  Packs/CortexXDR/ReleaseNotes/4_2_0.md
  Packs/CortexXDR/Scripts/CortexXDRAdditionalAlertInformationWidget/CortexXDRAdditionalAlertInformationWidget.py
  Packs/CortexXDR/Scripts/CortexXDRAdditionalAlertInformationWidget/CortexXDRAdditionalAlertInformationWidget.yml
  Packs/CortexXDR/Scripts/CortexXDRAdditionalAlertInformationWidget/CortexXDRAdditionalAlertInformationWidget_test.py
  Packs/CortexXDR/Scripts/CortexXDRAdditionalAlertInformationWidget/README.md
  Packs/CortexXDR/Scripts/CortexXDRAdditionalAlertInformationWidget/test_data/context_data1.json
  Packs/CortexXDR/Scripts/CortexXDRAdditionalAlertInformationWidget/test_data/context_data2.json
  Packs/CortexXDR/Scripts/CortexXDRAdditionalAlertInformationWidget/test_data/expected_results1.json
  Packs/CortexXDR/Scripts/CortexXDRAdditionalAlertInformationWidget/test_data/expected_results2.json
  Packs/CortexXDR/Scripts/CortexXDRCloudProviderWidget/CortexXDRCloudProviderWidget.py
  Packs/CortexXDR/Scripts/CortexXDRCloudProviderWidget/CortexXDRCloudProviderWidget.yml
  Packs/CortexXDR/Scripts/CortexXDRCloudProviderWidget/CortexXDRCloudProviderWidget_test.py
  Packs/CortexXDR/Scripts/CortexXDRCloudProviderWidget/README.md
  Packs/CortexXDR/Scripts/CortexXDRCloudProviderWidget/test_data/incident_data.json
  Packs/CortexXDR/Scripts/CortexXDRCloudProviderWidget/test_data/multi_clouds_incident_data.json
  Packs/CortexXDR/Scripts/CortexXDRIdentityInformationWidget/CortexXDRIdentityInformationWidget.py
  Packs/CortexXDR/Scripts/CortexXDRIdentityInformationWidget/CortexXDRIdentityInformationWidget.yml
  Packs/CortexXDR/Scripts/CortexXDRIdentityInformationWidget/CortexXDRIdentityInformationWidget_test.py
  Packs/CortexXDR/Scripts/CortexXDRIdentityInformationWidget/README.md
  Packs/CortexXDR/Scripts/CortexXDRIdentityInformationWidget/test_data/context_data1.json
  Packs/CortexXDR/Scripts/CortexXDRIdentityInformationWidget/test_data/context_data2.json
  Packs/CortexXDR/Scripts/CortexXDRIdentityInformationWidget/test_data/expected_results1.json
  Packs/CortexXDR/Scripts/CortexXDRIdentityInformationWidget/test_data/expected_results2.json
  Packs/CortexXDR/Scripts/CortexXDRRemediationActionsWidget/CortexXDRRemediationActionsWidget.py
  Packs/CortexXDR/Scripts/CortexXDRRemediationActionsWidget/CortexXDRRemediationActionsWidget.yml
  Packs/CortexXDR/Scripts/CortexXDRRemediationActionsWidget/CortexXDRRemediationActionsWidget_test.py
  Packs/CortexXDR/Scripts/CortexXDRRemediationActionsWidget/README.md
  Packs/CortexXDR/Scripts/CortexXDRRemediationActionsWidget/test_data/context_data1.json
  Packs/CortexXDR/Scripts/CortexXDRRemediationActionsWidget/test_data/context_data2.json
  Packs/CortexXDR/Scripts/CortexXDRRemediationActionsWidget/test_data/expected_results1.json
  Packs/CortexXDR/Scripts/CortexXDRRemediationActionsWidget/test_data/expected_results2.json
  Packs/CortexXDR/pack_metadata.json
Labels: docs-approved

#15699 [malwarebytes-254] Updated code for Usage Analytics
  Packs/Malwarebytes/Integrations/Malwarebytes/Malwarebytes.py
  Packs/Malwarebytes/ReleaseNotes/1_1_6.md
  Packs/Malwarebytes/pack_metadata.json
Labels: Contribution, docs-approved, Partner, pending-demo, post-demo, Contribution Form Filled

#15748 [Fix] JSON feed api module fetch only the first feed
  Packs/ApiModules/Scripts/JSONFeedApiModule/JSONFeedApiModule.py
  Packs/ApiModules/Scripts/JSONFeedApiModule/JSONFeedApiModule_test.py
  Packs/ApiModules/pack_metadata.json
  Packs/FeedAWS/ReleaseNotes/1_1_10.md
  Packs/FeedAWS/pack_metadata.json
  Packs/FeedFastly/ReleaseNotes/1_1_9.md
  Packs/FeedFastly/pack_metadata.json
  Packs/FeedIntel471/ReleaseNotes/2_0_7.md
  Packs/FeedIntel471/pack_metadata.json
  Packs/FeedJSON/ReleaseNotes/1_1_9.md
  Packs/FeedJSON/pack_metadata.json
  Packs/FeedMalwareBazaar/ReleaseNotes/1_0_1.md
  Packs/FeedMalwareBazaar/pack_metadata.json
  Packs/iDefense/ReleaseNotes/3_1_3.md
  Packs/iDefense/pack_metadata.json
Labels: docs-approved

#15726 Added Google IP Ranges Feed
  Packs/FeedGCPWhitelist/Integrations/FeedGoogleIPRanges/FeedGoogleIPRanges.py
  Packs/FeedGCPWhitelist/Integrations/FeedGoogleIPRanges/FeedGoogleIPRanges.yml
  Packs/FeedGCPWhitelist/Integrations/FeedGoogleIPRanges/FeedGoogleIPRanges_description.md
  Packs/FeedGCPWhitelist/Integrations/FeedGoogleIPRanges/FeedGoogleIPRanges_image.png
  Packs/FeedGCPWhitelist/Integrations/FeedGoogleIPRanges/README.md
  Packs/FeedGCPWhitelist/ReleaseNotes/2_0_0.md
  Packs/FeedGCPWhitelist/pack_metadata.json
  Tests/conf.json
Labels: docs-approved

#15757 fix lint common server python
  Packs/Base/ReleaseNotes/1_15_1.md
  Packs/Base/Scripts/CommonServerPython/CommonServerPython.py
  Packs/Base/pack_metadata.json
Labels: docs-approved

#15440 New Dashboards fot TIM
  Packs/CommonDashboards/Dashboards/dashboard-My_Threat_Landscape.json
  Packs/CommonDashboards/Dashboards/dashboard-Threat_Intelligence_Feeds.json
  Packs/CommonDashboards/ReleaseNotes/1_1_3.md
  Packs/CommonDashboards/pack_metadata.json
  Packs/CommonWidgets/ReleaseNotes/1_2_1.md
  Packs/CommonWidgets/Widgets/widget-Active_Indicators_Volumes_by_Feed.json
  Packs/CommonWidgets/Widgets/widget-Active_Indicators_by_Verdict.json
  Packs/CommonWidgets/Widgets/widget-Active_vs_Expired_Indicators.json
  Packs/CommonWidgets/Widgets/widget-Feeds_Errors.json
  Packs/CommonWidgets/Widgets/widget-Indicators_in_Related_Incidents.json
  Packs/CommonWidgets/Widgets/widget-Malicious_Suspicious_Indicators_in_Incidents.json
  Packs/CommonWidgets/Widgets/widget-Relationship_Generating_Integrations-Relationship_Generating_Integrations.json
  Packs/CommonWidgets/Widgets/widget-Top_10_Attack_Pattern_Indicators_in_Related_Incidents.json
  Packs/CommonWidgets/Widgets/widget-Top_10_File_Indicators_in_Related_Incidents.json
  Packs/CommonWidgets/Widgets/widget-Unit42_Blog_Feed.json
  Packs/CommonWidgets/pack_metadata.json
Labels: docs-approved

#15761 remove clickable links from threat vault README
  Packs/PaloAltoNetworks_Threat_Vault/Integrations/Threat_Vault/README.md
Labels: docs-approved

#15743 DomainTools + FortiSandbox - added readme files
  Packs/DomainTools/Integrations/integration-DomainTools_README.md
  Packs/FortiSandbox/Integrations/FortiSandbox/README.md
  Packs/FortiSandbox/Playbooks/playbook-FortiSandbox_-_Loop_For_Job_Verdict_README.md
  Packs/FortiSandbox/Playbooks/playbook-FortiSandbox_-_Loop_for_Job_Submissions_README.md
  Packs/FortiSandbox/Playbooks/playbook-FortiSandbox_-_Upload_Multiple_Files_README.md
Labels: docs-approved

#15634 enhance username param description
  Packs/Jira/Integrations/JiraV2/README.md
Labels: docs-approved

#15416 Microsoft Graph API - add no_content arg
  Packs/MicrosoftGraphAPI/.secrets-ignore
  Packs/MicrosoftGraphAPI/Integrations/MicrosoftGraphAPI/MicrosoftGraphAPI.py
  Packs/MicrosoftGraphAPI/Integrations/MicrosoftGraphAPI/MicrosoftGraphAPI.yml
  Packs/MicrosoftGraphAPI/Integrations/MicrosoftGraphAPI/MicrosoftGraphAPI_test.py
  Packs/MicrosoftGraphAPI/Integrations/MicrosoftGraphAPI/README.md
  Packs/MicrosoftGraphAPI/Integrations/MicrosoftGraphAPI/test_data/applications.json
  Packs/MicrosoftGraphAPI/ReleaseNotes/1_0_6.md
  Packs/MicrosoftGraphAPI/pack_metadata.json
Labels: docs-approved

#15740 CommonServerPython: fixed an issue in the integration logger obfuscation
  Packs/Base/ReleaseNotes/1_15_2.md
  Packs/Base/Scripts/CommonServerPython/CommonServerPython.py
  Packs/Base/Scripts/CommonServerPython/CommonServerPython_test.py
  Packs/Base/pack_metadata.json
Labels: docs-approved, release-notes-only

#15745 Added / to base url if necessary
  Packs/FeedMISP/Integrations/FeedMISP/FeedMISP.py
  Packs/FeedMISP/Integrations/FeedMISP/FeedMISP_description.md
  Packs/FeedMISP/ReleaseNotes/1_0_1.md
  Packs/FeedMISP/pack_metadata.json
Labels: docs-approved

#15729 release-sane-pdf docker image
  Packs/Base/ReleaseNotes/1_15_3.md
  Packs/Base/Scripts/SanePdfReport/SanePdfReport.yml
  Packs/Base/pack_metadata.json
Labels: docs-approved, release-notes-only

#15762 Detonate File - Generic: added VMRay outputs
  Packs/CommonPlaybooks/Playbooks/playbook-Detonate_File_-_Generic.yml
  Packs/CommonPlaybooks/Playbooks/playbook-Detonate_File_-_Generic_README.md
  Packs/CommonPlaybooks/ReleaseNotes/2_1_1.md
  Packs/CommonPlaybooks/pack_metadata.json
Labels: docs-approved

#15767 unskip redcanary
  Tests/conf.json
Labels: docs-approved

#15714 Added a feature to unpack tuple values of matches
  Packs/CommonScripts/ReleaseNotes/1_5_3.md
  Packs/CommonScripts/Scripts/RegexExtractAll/RegexExtractAll.py
  Packs/CommonScripts/Scripts/RegexExtractAll/RegexExtractAll.yml
  Packs/CommonScripts/Scripts/RegexExtractAll/RegexExtractAll_test.py
  Packs/CommonScripts/pack_metadata.json
Labels: Contribution, docs-approved, Contribution Form Filled, Community

#15654 ThreatConnect DBotScore fix
  Packs/ThreatConnect/Integrations/ThreatConnect_v2/README.md
  Packs/ThreatConnect/Integrations/ThreatConnect_v2/ThreatConnect_v2.py
  Packs/ThreatConnect/Integrations/ThreatConnect_v2/ThreatConnect_v2.yml
  Packs/ThreatConnect/Integrations/ThreatConnect_v2/ThreatConnect_v2_test.py
  Packs/ThreatConnect/ReleaseNotes/2_0_17.md
  Packs/ThreatConnect/pack_metadata.json
Labels: docs-approved

#15719 Add security notes to the rasterize integration
  Packs/rasterize/Integrations/rasterize/README.md
  Packs/rasterize/Integrations/rasterize/rasterize_description.md
  Packs/rasterize/ReleaseNotes/1_0_15.md
  Packs/rasterize/pack_metadata.json
Labels: content, docs-approved

#15665 support_multithreading - verify lock is locked before release
  Packs/Base/ReleaseNotes/1_15_4.md
  Packs/Base/Scripts/CommonServerPython/CommonServerPython.py
  Packs/Base/pack_metadata.json
Labels: docs-approved

#15356 XDR - XCLOUD
  Packs/AWS-IAM/Playbooks/playbook-AWS_IAM_-_User_enrichment.yml
  Packs/AWS-IAM/Playbooks/playbook-AWS_IAM_-_User_enrichment_README.md
  Packs/AWS-IAM/ReleaseNotes/1_1_5.md
  Packs/AWS-IAM/doc_files/AWS_IAM_user_enrichment.png
  Packs/AWS-IAM/pack_metadata.json
  Packs/CortexXDR/IncidentTypes/incidenttype-Cortex_XDR_-_XCLOUD.json
  Packs/CortexXDR/Layouts/layoutscontainer-Cortex_XDR_-_XCLOUD.json
  Packs/CortexXDR/Playbooks/playbook-Cortex_XDR_-_AWS_IAM_user_access_investigation.yml
  Packs/CortexXDR/Playbooks/playbook-Cortex_XDR_-_AWS_IAM_user_access_investigation_README.md
  Packs/CortexXDR/ReleaseNotes/4_2_1.md
  Packs/CortexXDR/doc_files/Cortex_XDR_-_AWS_IAM_user_access_investigation.png
  Packs/CortexXDR/pack_metadata.json
Labels: docs-approved

#15487 support for setting custom User Agent added
  Packs/UrlScan/Integrations/UrlScan/README.md
  Packs/UrlScan/Integrations/UrlScan/UrlScan.py
  Packs/UrlScan/Integrations/UrlScan/UrlScan.yml
  Packs/UrlScan/ReleaseNotes/1_1_13.md
  Packs/UrlScan/pack_metadata.json
Labels: Contribution, docs-approved, Contribution Form Filled, Community

#15713 Tim whois delimiter fix
  Packs/Whois/Playbooks/playbook-TIM_-_Process_Domain_Registrant_With_Whois.yml
  Packs/Whois/Playbooks/playbook-TIM_-_Process_Domain_Registrant_With_Whois_README.md
  Packs/Whois/ReleaseNotes/1_2_7.md
  Packs/Whois/pack_metadata.json
Labels: docs-approved, release-notes-only

#15712 Tim file processing fix
  Packs/TIM_Processing/Playbooks/playbook-TIM_-_Process_File_Indicators_With_File_Hash_Type.yml
  Packs/TIM_Processing/ReleaseNotes/1_1_9.md
  Packs/TIM_Processing/pack_metadata.json
Labels: docs-approved

#15576 QRadar TIM V3 and integration test
  Packs/QRadar/Playbooks/playbook-TIM_-_QRadar_Add_Bad_Hash_Indicators.yml
  Packs/QRadar/Playbooks/playbook-TIM_-_QRadar_Add_Domain_Indicators.yml
  Packs/QRadar/Playbooks/playbook-TIM_-_QRadar_Add_IP_Indicators.yml
  Packs/QRadar/Playbooks/playbook-TIM_-_QRadar_Add_Url_Indicators.yml
  Packs/QRadar/ReleaseNotes/2_1_5.md
  Packs/QRadar/ReleaseNotes/2_1_8.md
  Packs/QRadar/pack_metadata.json
  Packs/TIM_SIEM/Playbooks/playbook-TIM_-_Add_Bad_Hash_Indicators_To_SIEM.yml
  Packs/TIM_SIEM/Playbooks/playbook-TIM_-_Add_Domain_Indicators_To_SIEM.yml
  Packs/TIM_SIEM/Playbooks/playbook-TIM_-_Add_IP_Indicators_To_SIEM.yml
  Packs/TIM_SIEM/Playbooks/playbook-TIM_-_Add_Url_Indicators_To_SIEM.yml
  Packs/TIM_SIEM/ReleaseNotes/1_1_0.md
  Packs/TIM_SIEM/pack_metadata.json
Labels: docs-approved, release-notes-only

#15749 Enhance unzip script
  Packs/CommonScripts/ReleaseNotes/1_5_4.md
  Packs/CommonScripts/Scripts/UnPackFile/UnPackFile.yml
  Packs/CommonScripts/Scripts/UnzipFile/UnzipFile.py
  Packs/CommonScripts/Scripts/UnzipFile/UnzipFile_test.py
  Packs/CommonScripts/Scripts/UnzipFile/data_test/test_file.txt
  Packs/CommonScripts/Scripts/UnzipFile/data_test/test_file.txt.tar.gz
  Packs/CommonScripts/pack_metadata.json
Labels: docs-approved

#15789 Changed file extraction scripts to use DBot role
  Packs/CommonScripts/ReleaseNotes/1_5_5.md
  Packs/CommonScripts/Scripts/ExtractIndicatorsFromTextFile/ExtractIndicatorsFromTextFile.yml
  Packs/CommonScripts/Scripts/ExtractIndicatorsFromWordFile/ExtractIndicatorsFromWordFile.yml
  Packs/CommonScripts/Scripts/ReadPDFFileV2/ReadPDFFileV2.yml
  Packs/CommonScripts/pack_metadata.json
Labels: docs-approved, release-notes-only

#15787 set defaultEnabled to True
  Packs/AutoFocus/Integrations/AutoFocusTagsFeed/AutoFocusTagsFeed.yml
  Packs/AutoFocus/ReleaseNotes/2_0_2.md
  Packs/AutoFocus/pack_metadata.json
Labels: docs-approved

#15575 New Integration - Ipcalc
  Packs/NetCalc/.pack-ignore
  Packs/NetCalc/.secrets-ignore
  Packs/NetCalc/README.md
  Packs/NetCalc/Scripts/IPCalcCheckSubnetCollision/IPCalcCheckSubnetCollision.py
  Packs/NetCalc/Scripts/IPCalcCheckSubnetCollision/IPCalcCheckSubnetCollision.yml
  Packs/NetCalc/Scripts/IPCalcCheckSubnetCollision/README.md
  Packs/NetCalc/Scripts/IPCalcReturnAddressBinary/IPCalcReturnAddressBinary.py
  Packs/NetCalc/Scripts/IPCalcReturnAddressBinary/IPCalcReturnAddressBinary.yml
  Packs/NetCalc/Scripts/IPCalcReturnAddressBinary/README.md
  Packs/NetCalc/Scripts/IPCalcReturnAddressIANAAllocation/IPCalcReturnAddressIANAAllocation.py
  Packs/NetCalc/Scripts/IPCalcReturnAddressIANAAllocation/IPCalcReturnAddressIANAAllocation.yml
  Packs/NetCalc/Scripts/IPCalcReturnAddressIANAAllocation/README.md
  Packs/NetCalc/Scripts/IPCalcReturnSubnetAddresses/IPCalcReturnSubnetAddresses.py
  Packs/NetCalc/Scripts/IPCalcReturnSubnetAddresses/IPCalcReturnSubnetAddresses.yml
  Packs/NetCalc/Scripts/IPCalcReturnSubnetAddresses/README.md
  Packs/NetCalc/Scripts/IPCalcReturnSubnetBroadcastAddress/IPCalcReturnSubnetBroadcastAddress.py
  Packs/NetCalc/Scripts/IPCalcReturnSubnetBroadcastAddress/IPCalcReturnSubnetBroadcastAddress.yml
  Packs/NetCalc/Scripts/IPCalcReturnSubnetBroadcastAddress/README.md
  Packs/NetCalc/Scripts/IPCalcReturnSubnetNetwork/IPCalcReturnSubnetNetwork.py
  Packs/NetCalc/Scripts/IPCalcReturnSubnetNetwork/IPCalcReturnSubnetNetwork.yml
  Packs/NetCalc/Scripts/IPCalcReturnSubnetNetwork/README.md
  Packs/NetCalc/pack_metadata.json
Labels: Contribution, docs-approved, Contribution Form Filled, Community

#15633 Cisco wsa
  Packs/CiscoWSA/.pack-ignore
  Packs/CiscoWSA/.secrets-ignore
  Packs/CiscoWSA/Integrations/CiscoWSA/CiscoWSA.py
  Packs/CiscoWSA/Integrations/CiscoWSA/CiscoWSA.yml
  Packs/CiscoWSA/Integrations/CiscoWSA/CiscoWSA_description.md
  Packs/CiscoWSA/Integrations/CiscoWSA/CiscoWSA_image.png
  Packs/CiscoWSA/Integrations/CiscoWSA/Pipfile
  Packs/CiscoWSA/Integrations/CiscoWSA/Pipfile.lock
  Packs/CiscoWSA/Integrations/CiscoWSA/README.md
  Packs/CiscoWSA/Integrations/CiscoWSA/Test/id_set.json
  Packs/CiscoWSA/Integrations/CiscoWSA/command_examples
  Packs/CiscoWSA/README.md
  Packs/CiscoWSA/pack_metadata.json
Labels: Contribution, docs-approved, Contribution Form Filled, Community

#15792 Deprecate GCP Whitelist Feed and update pack name
  Packs/FeedGCPWhitelist/Integrations/FeedGCPWhitelist/FeedGCPWhitelist.yml
  Packs/FeedGCPWhitelist/Integrations/FeedGCPWhitelist/FeedGCPWhitelist_description.md
  Packs/FeedGCPWhitelist/ReleaseNotes/2_0_1.md
  Packs/FeedGCPWhitelist/TestPlaybooks/playbook-Feed_GCPWhitelist-Test.yml
  Packs/FeedGCPWhitelist/pack_metadata.json
  Tests/conf.json
Labels: docs-approved

#15798 Added Empty Readme Error Msg To Pack Ignore AWS-IAM
  Packs/AWS-IAM/.pack-ignore
  Packs/CommonPlaybooks/.pack-ignore
Labels: docs-approved

#15772 CSP: TableToMarkdown escape ` fix
  Packs/Base/ReleaseNotes/1_15_5.md
  Packs/Base/Scripts/CommonServerPython/CommonServerPython.py
  Packs/Base/Scripts/CommonServerPython/CommonServerPython.yml
  Packs/Base/Scripts/CommonServerPython/CommonServerPython_test.py
  Packs/Base/pack_metadata.json
Labels: bug, docs-approved, release-notes-only

#15628 feature: add Qintel feeds pack
  Packs/QintelFeed/.pack-ignore
  Packs/QintelFeed/.secrets-ignore
  Packs/QintelFeed/Author_image.png
  Packs/QintelFeed/Integrations/QintelQSentryFeed/Pipfile
  Packs/QintelFeed/Integrations/QintelQSentryFeed/Pipfile.lock
  Packs/QintelFeed/Integrations/QintelQSentryFeed/QintelQSentryFeed.py
  Packs/QintelFeed/Integrations/QintelQSentryFeed/QintelQSentryFeed.yml
  Packs/QintelFeed/Integrations/QintelQSentryFeed/QintelQSentryFeed_description.md
  Packs/QintelFeed/Integrations/QintelQSentryFeed/QintelQSentryFeed_image.png
  Packs/QintelFeed/Integrations/QintelQSentryFeed/QintelQSentryFeed_test.py
  Packs/QintelFeed/Integrations/QintelQSentryFeed/README.md
  Packs/QintelFeed/Integrations/QintelQSentryFeed/test_data/anon_feed.json
  Packs/QintelFeed/Integrations/QintelQSentryFeed/test_data/mal_hosting.json
  Packs/QintelFeed/Integrations/QintelQSentryFeed/test_data/test_module.json
  Packs/QintelFeed/README.md
  Packs/QintelFeed/pack_metadata.json
Labels: Contribution, docs-approved, Partner, Contribution Form Filled

#15802 default enabled false
  Packs/AutoFocus/Integrations/AutoFocusTagsFeed/AutoFocusTagsFeed.yml
  Packs/AutoFocus/ReleaseNotes/2_0_3.md
  Packs/AutoFocus/pack_metadata.json
Labels: docs-approved

#15782 Change reviewers
  Utils/github_workflow_scripts/handle_external_pr.py
Labels: docs-approved

#15718 HashiCorp Vault - AppRole auth method
  Packs/HashiCorp-Vault/Integrations/HashiCorpVault/HashiCorpVault.py
  Packs/HashiCorp-Vault/Integrations/HashiCorpVault/HashiCorpVault.yml
  Packs/HashiCorp-Vault/Integrations/HashiCorpVault/HashiCorpVault_description.md
  Packs/HashiCorp-Vault/Integrations/HashiCorpVault/README.md
  Packs/HashiCorp-Vault/ReleaseNotes/1_0_3.md
  Packs/HashiCorp-Vault/pack_metadata.json
Labels: docs-approved

#15814 [Test Fix] AutoFocus V2
  Tests/conf.json
Labels: docs-approved

#15724 fix Similar incidents tab
  Packs/CortexXDR/Layouts/layoutscontainer-Cortex_XDR_Incident.json
  Packs/CortexXDR/ReleaseNotes/4_2_3.md
  Packs/CortexXDR/pack_metadata.json
Labels: docs-approved

#15721 add README to symantec advanced threat protection
  Packs/Symantec_Advanced_Threat_Protection/README.md
Labels: docs-approved

#15768 Attack Pattern Extraction
  Packs/CommonScripts/ReleaseNotes/1_5_6.md
  Packs/CommonScripts/Scripts/ExtractAttackPattern/ExtractAttackPattern.py
  Packs/CommonScripts/Scripts/ExtractAttackPattern/ExtractAttackPattern.yml
  Packs/CommonScripts/Scripts/ExtractAttackPattern/ExtractAttackPattern_test.py
  Packs/CommonScripts/TestPlaybooks/ExtractAttackPattern-Test.yml
  Packs/CommonScripts/pack_metadata.json
  Packs/FeedMitreAttackv2/Integrations/FeedMitreAttackv2/FeedMitreAttackv2.py
  Packs/FeedMitreAttackv2/ReleaseNotes/1_0_8.md
  Packs/FeedMitreAttackv2/pack_metadata.json
  Tests/conf.json
Labels: docs-approved, release-notes-only

#15759 fix: transformed severity to match XSOAR
  Packs/Lacework/Classifiers/classifier-Lacework_5_9_9.json
  Packs/Lacework/Classifiers/classifier-mapper-incoming-Lacework.json
  Packs/Lacework/Integrations/Lacework/Lacework.py
  Packs/Lacework/ReleaseNotes/1_1_1.md
  Packs/Lacework/pack_metadata.json
Labels: Contribution, docs-approved, Contribution Form Filled, Community

#15825 Add Jira Incident Layout V2
  Packs/Jira/Layouts/layoutscontainer-Jira_Incident_Layout.json
  Packs/Jira/ReleaseNotes/1_4_1.md
  Packs/Jira/pack_metadata.json
Labels: docs-approved

#15821 [Test Fail] Unskip FireEye NX Test
  Tests/conf.json
Labels: docs-approved

#14432 Logrhythm V2 pack
  Packs/CommonTypes/IncidentFields/incidentfield-Last_Update_Time.json
  Packs/CommonTypes/ReleaseNotes/3_1_25.md
  Packs/CommonTypes/pack_metadata.json
  Packs/LogRhythmRest/.pack-ignore
  Packs/LogRhythmRest/Classifiers/classifier-LogRhythm.json
  Packs/LogRhythmRest/Classifiers/classifier-LogRhythm_5_9_9.json
  Packs/LogRhythmRest/Classifiers/classifier-mapper-incoming-LogRhythm.json
  Packs/LogRhythmRest/IncidentFields/incidentfield-LogRhythm_Associated_Cases.json
  Packs/LogRhythmRest/IncidentFields/incidentfield-LogRhythm_CaseUpdatedUser.json
  Packs/LogRhythmRest/IncidentFields/incidentfield-LogRhythm_Collaborators.json
  Packs/LogRhythmRest/IncidentFields/incidentfield-LogRhythm_Entity.json
  Packs/LogRhythmRest/IncidentFields/incidentfield-LogRhythm_Priority.json
  Packs/LogRhythmRest/IncidentFields/incidentfield-LogRhythm_Status.json
  Packs/LogRhythmRest/IncidentFields/incidentfield-LogRhythm_TicketDueDate.json
  Packs/LogRhythmRest/IncidentTypes/incidenttype-LogrhythmAlarm.json
  Packs/LogRhythmRest/IncidentTypes/incidenttype-LogrhythmCase.json
  Packs/LogRhythmRest/Integrations/LogRhythmRest/LogRhythmRest.yml
  Packs/LogRhythmRest/Integrations/LogRhythmRestV2/LogRhythmRestV2.py
  Packs/LogRhythmRest/Integrations/LogRhythmRestV2/LogRhythmRestV2.yml
  Packs/LogRhythmRest/Integrations/LogRhythmRestV2/LogRhythmRestV2_description.md
  Packs/LogRhythmRest/Integrations/LogRhythmRestV2/LogRhythmRestV2_image.png
  Packs/LogRhythmRest/Integrations/LogRhythmRestV2/LogRhythmRestV2_test.py
  Packs/LogRhythmRest/Integrations/LogRhythmRestV2/Pipfile
  Packs/LogRhythmRest/Integrations/LogRhythmRestV2/Pipfile.lock
  Packs/LogRhythmRest/Integrations/LogRhythmRestV2/README.md
  Packs/LogRhythmRest/Integrations/LogRhythmRestV2/command_examples
  Packs/LogRhythmRest/Integrations/LogRhythmRestV2/test_data/test.txt
  Packs/LogRhythmRest/Layouts/layout-detailsV2-Logrhythm_Alarm.json
  Packs/LogRhythmRest/Layouts/layout-detailsV2-Logrhythm_Case.json
  Packs/LogRhythmRest/Layouts/layoutscontainer-LogRhythm_Alarm_Incident.json
  Packs/LogRhythmRest/Layouts/layoutscontainer-LogRhythm_Case_Incident.json
  Packs/LogRhythmRest/Playbooks/playbook-LogRhythmRestV2-_Search_query.yml
  Packs/LogRhythmRest/Playbooks/playbook-Logrhythm_Alarm_Handling.yml
  Packs/LogRhythmRest/README.md
  Packs/LogRhythmRest/ReleaseNotes/2_0_0.md
  Packs/LogRhythmRest/TestPlaybooks/playbook-LogRhythmRestV2-test.yml
  Packs/LogRhythmRest/pack_metadata.json
  Tests/conf.json
Labels: docs-approved

#15643 Q radar additional tests
  Packs/QRadar/Integrations/QRadar_v2/QRadar_v2.py
  Packs/QRadar/Integrations/QRadar_v2/QRadar_v2.yml
  Packs/QRadar/Integrations/QRadar_v2/QRadar_v2_test.py
  Packs/QRadar/Integrations/QRadar_v3/QRadar_v3.py
  Packs/QRadar/Integrations/QRadar_v3/QRadar_v3.yml
  Packs/QRadar/Integrations/QRadar_v3/QRadar_v3_test.py
  Packs/QRadar/Integrations/QRadar_v3/README.md
  Packs/QRadar/Integrations/QRadar_v3/test_data/integration_context_tests.json
  Packs/QRadar/ReleaseNotes/2_1_10.md
  Packs/QRadar/pack_metadata.json
Labels: docs-approved

#15843 add myself as code owner QRadar V3
  .github/CODEOWNERS
Labels: docs-approved

#15812 Comma as email separator
  Packs/CommonScripts/ReleaseNotes/1_5_6.md
  Packs/CommonScripts/ReleaseNotes/1_5_7.md
  Packs/CommonScripts/Scripts/ParseEmailFiles/ParseEmailFiles.py
  Packs/CommonScripts/Scripts/ParseEmailFiles/ParseEmailFiles.yml
  Packs/CommonScripts/Scripts/ParseEmailFiles/ParseEmailFiles_test.py
  Packs/CommonScripts/Scripts/ParseEmailFiles/test_data/from_multiple_lines_CRLF.eml
  Packs/CommonScripts/Scripts/ParseEmailFiles/test_data/from_multiple_lines_LF.eml
  Packs/CommonScripts/Scripts/ParseEmailFiles/test_data/from_one_line_CRLF.eml
  Packs/CommonScripts/Scripts/ParseEmailFiles/test_data/from_one_line_LF.eml
  Packs/CommonScripts/Scripts/ParseEmailFiles/test_data/from_one_line_no_comma_LF.eml
  Packs/CommonScripts/pack_metadata.json
Labels: docs-approved

#15058 [PAN] HackerOne Integration
  Packs/HackerOne/.pack-ignore
  Packs/HackerOne/.secrets-ignore
  Packs/HackerOne/Author_image.png
  Packs/HackerOne/Classifiers/classifier-mapper-incoming-HackerOne.json
  Packs/HackerOne/IncidentFields/incidentfield-HackerOne-Report-Assignee-Disabled.json
  Packs/HackerOne/IncidentFields/incidentfield-HackerOne-Report-Assignee-HackerOne-Triager.json
  Packs/HackerOne/IncidentFields/incidentfield-HackerOne-Report-Assignee-ID.json
  Packs/HackerOne/IncidentFields/incidentfield-HackerOne-Report-Assignee-Location.json
  Packs/HackerOne/IncidentFields/incidentfield-HackerOne-Report-Assignee-Name.json
  Packs/HackerOne/IncidentFields/incidentfield-HackerOne-Report-Assignee-Reputation.json
  Packs/HackerOne/IncidentFields/incidentfield-HackerOne-Report-Assignee-Username.json
  Packs/HackerOne/IncidentFields/incidentfield-HackerOne-Report-Assignee-Website.json
  Packs/HackerOne/IncidentFields/incidentfield-HackerOne-Report-Attack-Complexity.json
  Packs/HackerOne/IncidentFields/incidentfield-HackerOne-Report-Attack-Vector.json
  Packs/HackerOne/IncidentFields/incidentfield-HackerOne-Report-Disclosed-At.json
  Packs/HackerOne/IncidentFields/incidentfield-HackerOne-Report-ID.json
  Packs/HackerOne/IncidentFields/incidentfield-HackerOne-Report-Program-Handle.json
  Packs/HackerOne/IncidentFields/incidentfield-HackerOne-Report-Reporter-Disabled.json
  Packs/HackerOne/IncidentFields/incidentfield-HackerOne-Report-Reporter-HackerOne-Triager.json
  Packs/HackerOne/IncidentFields/incidentfield-HackerOne-Report-Reporter-ID.json
  Packs/HackerOne/IncidentFields/incidentfield-HackerOne-Report-Reporter-Location.json
  Packs/HackerOne/IncidentFields/incidentfield-HackerOne-Report-Reporter-Name.json
  Packs/HackerOne/IncidentFields/incidentfield-HackerOne-Report-Reporter-Reputation.json
  Packs/HackerOne/IncidentFields/incidentfield-HackerOne-Report-Reporter-Username.json
  Packs/HackerOne/IncidentFields/incidentfield-HackerOne-Report-Reporter-Website.json
  Packs/HackerOne/IncidentFields/incidentfield-HackerOne-Report-Severity-ID.json
  Packs/HackerOne/IncidentFields/incidentfield-HackerOne-Report-Vulnerability-Information.json
  Packs/HackerOne/IncidentFields/incidentfield-HackerOne-Report-Vulnerable-Component-Scope.json
  Packs/HackerOne/IncidentFields/incidentfield-HackerOne-Report-Weakness-External-ID.json
  Packs/HackerOne/IncidentFields/incidentfield-HackerOne-Report-Weakness-ID.json
  Packs/HackerOne/IncidentFields/incidentfield-HackerOne-Report-Weakness-Name.json
  Packs/HackerOne/IncidentTypes/IncidentType-Report.json
  Packs/HackerOne/Integrations/HackerOne/HackerOne.py
  Packs/HackerOne/Integrations/HackerOne/HackerOne.yml
  Packs/HackerOne/Integrations/HackerOne/HackerOne_description.md
  Packs/HackerOne/Integrations/HackerOne/HackerOne_image.png
  Packs/HackerOne/Integrations/HackerOne/HackerOne_test.py
  Packs/HackerOne/Integrations/HackerOne/Pipfile
  Packs/HackerOne/Integrations/HackerOne/Pipfile.lock
  Packs/HackerOne/Integrations/HackerOne/README.md
  Packs/HackerOne/Integrations/HackerOne/test_data/incident/raw_response.json
  Packs/HackerOne/Integrations/HackerOne/test_data/input_data.py
  Packs/HackerOne/Integrations/HackerOne/test_data/program/program_command_context.json
  Packs/HackerOne/Integrations/HackerOne/test_data/program/program_command_readable_output.md
  Packs/HackerOne/Integrations/HackerOne/test_data/program/program_command_response.json
  Packs/HackerOne/Integrations/HackerOne/test_data/report/report_command_context.json
  Packs/HackerOne/Integrations/HackerOne/test_data/report/report_command_readable_output.md
  Packs/HackerOne/Integrations/HackerOne/test_data/report/report_command_response.json
  Packs/HackerOne/Layouts/layoutscontainer-HackerOne_Report.json
  Packs/HackerOne/README.md
  Packs/HackerOne/TestPlaybooks/HackerOne-Test.yml
  Packs/HackerOne/pack_metadata.json
Labels: Contribution, docs-approved, Partner, Contribution Form Filled

#15844 change release note in order to trigger release note update in upload…
  Packs/Base/ReleaseNotes/1_14_0.md
Labels: docs-approved

#15815 EwsExtension: Added the proxy integration patameter
  Packs/EWS/Integrations/EwsExtension/EwsExtension.ps1
  Packs/EWS/Integrations/EwsExtension/EwsExtension.yml
  Packs/EWS/ReleaseNotes/1_10_2.md
  Packs/EWS/pack_metadata.json
  Tests/conf.json
Labels: docs-approved

#15568 [MS Graph API] Expand API support
  Packs/MicrosoftGraphAPI/Integrations/MicrosoftGraphAPI/MicrosoftGraphAPI.py
  Packs/MicrosoftGraphAPI/Integrations/MicrosoftGraphAPI/MicrosoftGraphAPI_test.py
  Packs/MicrosoftGraphAPI/ReleaseNotes/1_0_7.md
  Packs/MicrosoftGraphAPI/pack_metadata.json
Labels: docs-approved

#15846 LogRhythmRest V2 - change params type to short text
  Packs/LogRhythmRest/Integrations/LogRhythmRestV2/LogRhythmRestV2.yml
  Packs/LogRhythmRest/Integrations/LogRhythmRestV2/README.md
  Packs/LogRhythmRest/ReleaseNotes/2_0_1.md
  Packs/LogRhythmRest/pack_metadata.json
Labels: docs-approved
