Repository demisto/content, pull requests merged in 2021-07, with the labels that each got.

#13490 [Community Contribution] PingCastle - Content Pack
  Packs/PingCastle/.pack-ignore
  Packs/PingCastle/.secrets-ignore
  Packs/PingCastle/Classifiers/classifier-PingCastle-Report-Classifier.json
  Packs/PingCastle/Classifiers/classifier-PingCastle-Report-Mapper.json
  Packs/PingCastle/Classifiers/classifier-PingCastle-Report_5_9_9.json
  Packs/PingCastle/IncidentFields/incidentfield-PingCastle_XML_Report.json
  Packs/PingCastle/IncidentTypes/incidenttype-PingCastle.json
  Packs/PingCastle/Integrations/PingCastle/PingCastle.py
  Packs/PingCastle/Integrations/PingCastle/PingCastle.yml
  Packs/PingCastle/Integrations/PingCastle/PingCastle_description.md
  Packs/PingCastle/Integrations/PingCastle/PingCastle_image.png
  Packs/PingCastle/Integrations/PingCastle/PingCastle_test.py
  Packs/PingCastle/Integrations/PingCastle/Pipfile
  Packs/PingCastle/Integrations/PingCastle/Pipfile.lock
  Packs/PingCastle/Integrations/PingCastle/README.md
  Packs/PingCastle/Integrations/PingCastle/command_examples.txt
  Packs/PingCastle/Playbooks/SX_-_PC_-_PingCastle_Report.png
  Packs/PingCastle/Playbooks/SX_-_PC_-_PingCastle_Report.yml
  Packs/PingCastle/Playbooks/SX_-_PC_-_PingCastle_Report_README.md
  Packs/PingCastle/README.md
  Packs/PingCastle/TestPlaybooks/SX_-_PC_-_Test_Playbook.yml
  Packs/PingCastle/pack_metadata.json
Labels: Contribution, Contribution Form Filled, Partner, docs-approved

#13317 Github Add Get Issue Events Command
  Packs/GitHub/Integrations/GitHub/GitHub.py
  Packs/GitHub/Integrations/GitHub/GitHub.yml
  Packs/GitHub/Integrations/GitHub/GitHub_test.py
  Packs/GitHub/Integrations/GitHub/README.md
  Packs/GitHub/Integrations/GitHub/test_data/search_issue_events_response.json
  Packs/GitHub/ReleaseNotes/1_2_11.md
  Packs/GitHub/TestPlaybooks/Git_Integration-Test.yml
  Packs/GitHub/pack_metadata.json
  Tests/conf.json
Labels: docs-approved

#13494 Rapid breach response | printnightmare
  Packs/MajorBreachesInvestigationandResponse/Playbooks/playbook-CVE-2021-1675_-_PrintNightmare.yml
  Packs/MajorBreachesInvestigationandResponse/Playbooks/playbook-CVE-2021-1675_-_PrintNightmare_README.md
  Packs/MajorBreachesInvestigationandResponse/README.md
  Packs/MajorBreachesInvestigationandResponse/ReleaseNotes/1_6_8.md
  Packs/MajorBreachesInvestigationandResponse/doc_files/CVE-2021-1675_-_PrintNightmare.png
  Packs/MajorBreachesInvestigationandResponse/pack_metadata.json
Labels: docs-approved

#13498 Add to ServerLogs dependency of RemoteAccess
  Packs/ServerLogs/ReleaseNotes/1_0_1.md
  Packs/ServerLogs/Scripts/ServerLogs/ServerLogs.py
  Packs/ServerLogs/Scripts/ServerLogs/ServerLogs.yml
  Packs/ServerLogs/pack_metadata.json
Labels: docs-approved, release-notes-only

#13497 Updating docker image
  Packs/Tidy/Integrations/Tidy/Tidy.yml
  Packs/Tidy/ReleaseNotes/1_0_6.md
  Packs/Tidy/pack_metadata.json
Labels: docs-approved

#13485 pytest warnings
  Packs/ARIAPacketIntelligence/Integrations/ARIAPacketIntelligence/ARIAPacketIntelligence.py
  Packs/ARIAPacketIntelligence/ReleaseNotes/2_0_4.md
  Packs/ARIAPacketIntelligence/pack_metadata.json
  Packs/CarbonBlackDefense/Integrations/CarbonBlackLiveResponseCloud/CarbonBlackLiveResponseCloud.py
  Packs/CarbonBlackDefense/ReleaseNotes/3_0_2.md
  Packs/CarbonBlackDefense/pack_metadata.json
  Packs/F5Silverline/Integrations/F5Silverline/F5Silverline.py
  Packs/F5Silverline/ReleaseNotes/1_0_1.md
  Packs/F5Silverline/pack_metadata.json
  Packs/FeedAzureADConnectHealth/Integrations/AzureADConnectHealthFeed/AzureADConnectHealthFeed.py
  Packs/FeedAzureADConnectHealth/Integrations/AzureADConnectHealthFeed/AzureADConnectHealthFeed.yml
  Packs/FeedAzureADConnectHealth/ReleaseNotes/1_0_2.md
  Packs/FeedAzureADConnectHealth/pack_metadata.json
  Packs/FeedThreatConnect/Integrations/FeedThreatConnect/FeedThreatConnect_test.py
  Packs/GoogleKeyManagementService/Integrations/GoogleKeyManagementService/GoogleKeyManagementService.yml
  Packs/GoogleKeyManagementService/ReleaseNotes/1_0_3.md
  Packs/GoogleKeyManagementService/pack_metadata.json
  Packs/GoogleKubernetesEngine/Integrations/GoogleKubernetesEngine/GoogleKubernetesEngine_test.py
  Packs/Phishing/ReleaseNotes/2_2_6.md
  Packs/Phishing/Scripts/PhishingDedupPreprocessingRule/PhishingDedupPreprocessingRule.py
  Packs/Phishing/pack_metadata.json
  Packs/ReplaceMatchGroup/Scripts/ReplaceMatchGroup/ReplaceMatchGroup_test.py
  Packs/Tanium/Integrations/Tanium_v2/Tanium_v2_test.py
  Packs/Troubleshoot/Scripts/CertificatesTroubleshoot/CertificatesTroubleshoot_test.py
Labels: docs-approved

#13489 Gurucul Update README.md
  Packs/Gurucul/.secrets-ignore
  Packs/Gurucul/Integrations/GuruculGRA/README.md
Labels: docs-approved

#13467 Checkout commit sha instead of branch (whose head could change)
  .gitlab/ci/global.yml
Labels: docs-approved

#13491 CommonServerPython: added the execute_command function
  Packs/Base/ReleaseNotes/1_12_17.md
  Packs/Base/Scripts/CommonServerPython/CommonServerPython.py
  Packs/Base/Scripts/CommonServerPython/CommonServerPython_test.py
  Packs/Base/pack_metadata.json
  Packs/Troubleshoot/ReleaseNotes/2_0_2.md
  Packs/Troubleshoot/Scripts/TroubleshootExecuteCommand/TroubleshootExecuteCommand.py
  Packs/Troubleshoot/Scripts/TroubleshootExecuteCommand/TroubleshootExecuteCommand.yml
  Packs/Troubleshoot/pack_metadata.json
Labels: docs-approved, release-notes-only

#13507 Rapid print nightmare enhancement
  Packs/MajorBreachesInvestigationandResponse/Playbooks/playbook-CVE-2021-1675_-_PrintNightmare.yml
  Packs/MajorBreachesInvestigationandResponse/Playbooks/playbook-CVE-2021-1675_-_PrintNightmare_README.md
  Packs/MajorBreachesInvestigationandResponse/ReleaseNotes/1_6_9.md
  Packs/MajorBreachesInvestigationandResponse/doc_files/CVE-2021-1675_-_PrintNightmare.png
  Packs/MajorBreachesInvestigationandResponse/pack_metadata.json
Labels: docs-approved

#13508 Cortex XDR - Improved error message for the test-module
  Packs/CortexXDR/Integrations/CortexXDRIR/CortexXDRIR.py
  Packs/CortexXDR/ReleaseNotes/3_0_17.md
  Packs/CortexXDR/pack_metadata.json
Labels: bug, docs-approved, release-notes-only

#13493 added envs to ignore
  .gitignore
Labels: docs-approved

#13505 Adopt Process for Securonix
  Packs/Securonix/README.md
  Packs/Securonix/ReleaseNotes/1_1_6.md
  Packs/Securonix/pack_metadata.json
Labels: Contribution, Partner, docs-approved

#13440 Deprecate the CVE Enrichment - Generic & sets a playback task as "skipunavailable: true"
  Packs/CVESearch/Playbooks/playbook-CVE_Enrichment_-_Generic.yml
  Packs/CVESearch/Playbooks/playbook-CVE_Enrichment_-_Generic_README.md
  Packs/CVESearch/ReleaseNotes/1_0_6.md
  Packs/CVESearch/pack_metadata.json
  Packs/CommonPlaybooks/Playbooks/playbook-CVE_Enrichment_-_Generic_v2.yml
  Packs/CommonPlaybooks/ReleaseNotes/1_9_9.md
  Packs/CommonPlaybooks/pack_metadata.json
Labels: docs-approved

#13303 Marketplace services - Add filter/transformer tags
  Tests/Marketplace/marketplace_constants.py
  Tests/Marketplace/marketplace_services.py
Labels: docs-approved

#11915 Changed required role to Data Investigator
  Packs/EWS/Integrations/SecurityAndCompliance/README.md
Labels: docs-approved

#13502 SearchRelationships script handle STIX objects
  Packs/Base/ReleaseNotes/1_12_18.md
  Packs/Base/Scripts/SearchIndicatorRelationships/SearchIndicatorRelationships.py
  Packs/Base/Scripts/SearchIndicatorRelationships/SearchIndicatorRelationships.yml
  Packs/Base/Scripts/SearchIndicatorRelationships/SearchIndicatorRelationships_test.py
  Packs/Base/pack_metadata.json
Labels: bug, docs-approved, release-notes-only

#13437 Fix timestamp conversion error
  Packs/ApiModules/ReleaseNotes/2_2_1.md
  Packs/ApiModules/Scripts/CSVFeedApiModule/CSVFeedApiModule.py
  Packs/ApiModules/Scripts/CSVFeedApiModule/CSVFeedApiModule_test.py
  Packs/ApiModules/pack_metadata.json
  Packs/BitcoinAbuse/ReleaseNotes/1_0_7.md
  Packs/BitcoinAbuse/pack_metadata.json
  Packs/FeedAlienVault/ReleaseNotes/1_1_4.md
  Packs/FeedAlienVault/pack_metadata.json
  Packs/FeedBambenekConsulting/ReleaseNotes/1_1_4.md
  Packs/FeedBambenekConsulting/pack_metadata.json
  Packs/FeedCSV/ReleaseNotes/1_1_3.md
  Packs/FeedCSV/pack_metadata.json
  Packs/FeedMajesticMillion/ReleaseNotes/1_1_3.md
  Packs/FeedMajesticMillion/pack_metadata.json
  Packs/Feedsslabusech/ReleaseNotes/1_1_4.md
  Packs/Feedsslabusech/pack_metadata.json
Labels: docs-approved

#13504 EDL: support ETag
  .gitignore
  Packs/EDL/Integrations/EDL/EDL.py
  Packs/EDL/ReleaseNotes/2_0_7.md
  Packs/EDL/pack_metadata.json
Labels: docs-approved, release-notes-only

#13018 Trend Micro Deep Security Integration
  Packs/TrendMicroDeepSecurity/.pack-ignore
  Packs/TrendMicroDeepSecurity/.secrets-ignore
  Packs/TrendMicroDeepSecurity/Integrations/TrendMicroDeepSecurity/Pipfile
  Packs/TrendMicroDeepSecurity/Integrations/TrendMicroDeepSecurity/Pipfile.lock
  Packs/TrendMicroDeepSecurity/Integrations/TrendMicroDeepSecurity/README.md
  Packs/TrendMicroDeepSecurity/Integrations/TrendMicroDeepSecurity/TrendMicroDeepSecurity.py
  Packs/TrendMicroDeepSecurity/Integrations/TrendMicroDeepSecurity/TrendMicroDeepSecurity.yml
  Packs/TrendMicroDeepSecurity/Integrations/TrendMicroDeepSecurity/TrendMicroDeepSecurity_description.md
  Packs/TrendMicroDeepSecurity/Integrations/TrendMicroDeepSecurity/TrendMicroDeepSecurity_image.png
  Packs/TrendMicroDeepSecurity/Integrations/TrendMicroDeepSecurity/TrendMicroDeepSecurity_test.py
  Packs/TrendMicroDeepSecurity/Integrations/TrendMicroDeepSecurity/command_examples
  Packs/TrendMicroDeepSecurity/Integrations/TrendMicroDeepSecurity/test_data/computer.json
  Packs/TrendMicroDeepSecurity/Integrations/TrendMicroDeepSecurity/test_data/computer_group.json
  Packs/TrendMicroDeepSecurity/Integrations/TrendMicroDeepSecurity/test_data/computer_setting.json
  Packs/TrendMicroDeepSecurity/Integrations/TrendMicroDeepSecurity/test_data/default_policy_setting.json
  Packs/TrendMicroDeepSecurity/Integrations/TrendMicroDeepSecurity/test_data/firewall_rule.json
  Packs/TrendMicroDeepSecurity/Integrations/TrendMicroDeepSecurity/test_data/firewall_rule_ids.json
  Packs/TrendMicroDeepSecurity/Integrations/TrendMicroDeepSecurity/test_data/policy.json
  Packs/TrendMicroDeepSecurity/Integrations/TrendMicroDeepSecurity/test_data/policy_setting.json
  Packs/TrendMicroDeepSecurity/README.md
  Packs/TrendMicroDeepSecurity/TestPlaybooks/playbook-TrendMicroDeepSecurity-Test.yml
  Packs/TrendMicroDeepSecurity/pack_metadata.json
  Tests/conf.json
Labels: Contribution, docs-approved, pending-demo, ready-for-instance-test

#13216 Restructured Splunk content
  Packs/SplunkPy/Integrations/SplunkPy/README.md
  Packs/SplunkPy/Integrations/SplunkPy/SplunkPy.yml
  Packs/SplunkPy/ReleaseNotes/2_1_4.md
  Packs/SplunkPy/pack_metadata.json
Labels: docs-approved

#13521 Updated README printnightmare link
  Packs/MajorBreachesInvestigationandResponse/README.md
Labels: docs-approved

#13465 Google Cloud SCC Integration Enhancement
  Packs/GoogleCloudSCC/.secrets-ignore
  Packs/GoogleCloudSCC/Integrations/GoogleCloudSCC/GoogleCloudSCC.py
  Packs/GoogleCloudSCC/Integrations/GoogleCloudSCC/GoogleCloudSCC.yml
  Packs/GoogleCloudSCC/Integrations/GoogleCloudSCC/GoogleCloudSCC_test.py
  Packs/GoogleCloudSCC/Integrations/GoogleCloudSCC/Pipfile
  Packs/GoogleCloudSCC/Integrations/GoogleCloudSCC/README.md
  Packs/GoogleCloudSCC/Integrations/GoogleCloudSCC/TestData/cloud_assets_list_ec.json
  Packs/GoogleCloudSCC/Integrations/GoogleCloudSCC/TestData/cloud_assets_list_response.json
  Packs/GoogleCloudSCC/Integrations/GoogleCloudSCC/TestData/cloud_assets_owners_get_assets.json
  Packs/GoogleCloudSCC/Integrations/GoogleCloudSCC/TestData/cloud_assets_owners_get_ec.json
  Packs/GoogleCloudSCC/Integrations/GoogleCloudSCC/TestData/cloud_assets_owners_get_response.json
  Packs/GoogleCloudSCC/Integrations/GoogleCloudSCC/TestData/list_asset_ec.json
  Packs/GoogleCloudSCC/Integrations/GoogleCloudSCC/TestData/list_finding_ec.json
  Packs/GoogleCloudSCC/Integrations/GoogleCloudSCC/TestData/update_finding_ec.json
  Packs/GoogleCloudSCC/ReleaseNotes/1_1_0.md
  Packs/GoogleCloudSCC/TestPlaybooks/GoogleCloudSCC-Test.yml
  Packs/GoogleCloudSCC/pack_metadata.json
Labels: Contribution, docs-approved, ready-for-instance-test

#13524 github readme: format HR and esacape broken url
  Packs/GitHub/Integrations/GitHub/README.md
Labels: docs-approved

#13515 Export indicators- Symantec ProxySG format bug
  Packs/ExportIndicators/Integrations/ExportIndicators/ExportIndicators.py
  Packs/ExportIndicators/Integrations/ExportIndicators/ExportIndicators_test.py
  Packs/ExportIndicators/ReleaseNotes/1_0_10.md
  Packs/ExportIndicators/pack_metadata.json
Labels: bug, docs-approved

#13513 Xforce ip command crashing for some ips bug fix
  Packs/XForceExchange/Integrations/XFE_v2/XFE_v2.py
  Packs/XForceExchange/Integrations/XFE_v2/XFE_v2_test.py
  Packs/XForceExchange/ReleaseNotes/1_1_5.md
  Packs/XForceExchange/pack_metadata.json
  Tests/conf.json
Labels: bug, docs-approved, release-notes-only

#13435 ExtractIndicatorsFromTextFile - changed to be used by DBot
  Packs/CommonScripts/ReleaseNotes/1_3_67.md
  Packs/CommonScripts/Scripts/ExtractIndicatorsFromTextFile/ExtractIndicatorsFromTextFile.yml
  Packs/CommonScripts/pack_metadata.json
Labels: docs-approved

#13525 Fix links to new graphics in SplunkPy README
  Packs/SplunkPy/Integrations/SplunkPy/README.md
Labels: docs-approved

#13052 Add Hey pack and EDL performance test
  Packs/DeveloperTools/.pack-ignore
  Packs/DeveloperTools/Integrations/CreateMockFeed/CreateMockFeed.py
  Packs/DeveloperTools/Integrations/CreateMockFeed/CreateMockFeed.yml
  Packs/DeveloperTools/Integrations/CreateMockFeed/CreateMockFeed_image.png
  Packs/DeveloperTools/Integrations/CreateMockFeed/Pipfile
  Packs/DeveloperTools/Integrations/CreateMockFeed/Pipfile.lock
  Packs/DeveloperTools/Integrations/CreateMockFeed/README.md
  Packs/DeveloperTools/ReleaseNotes/1_1_4.md
  Packs/DeveloperTools/Scripts/VerifyEnoughIndicators/Pipfile
  Packs/DeveloperTools/Scripts/VerifyEnoughIndicators/Pipfile.lock
  Packs/DeveloperTools/Scripts/VerifyEnoughIndicators/README.md
  Packs/DeveloperTools/Scripts/VerifyEnoughIndicators/VerifyEnoughIndicators.py
  Packs/DeveloperTools/Scripts/VerifyEnoughIndicators/VerifyEnoughIndicators.yml
  Packs/DeveloperTools/pack_metadata.json
  Packs/EDL/Integrations/EDL/EDL.yml
  Packs/EDL/Integrations/EDL/EDL_description.md
  Packs/EDL/ReleaseNotes/2_0_8.md
  Packs/EDL/TestPlaybooks/playbook-EDL_Indicator_Performance_Test.yml
  Packs/EDL/TestPlaybooks/playbook-EDL_Performance_Test.yml
  Packs/EDL/TestPlaybooks/playbook-EDL_Performance_Test_-_Concurrency.yml
  Packs/EDL/pack_metadata.json
  Packs/Hey/.pack-ignore
  Packs/Hey/.secrets-ignore
  Packs/Hey/README.md
  Packs/Hey/Scripts/Hey/Hey.py
  Packs/Hey/Scripts/Hey/Hey.yml
  Packs/Hey/Scripts/Hey/Hey_test.py
  Packs/Hey/Scripts/Hey/Pipfile
  Packs/Hey/Scripts/Hey/Pipfile.lock
  Packs/Hey/Scripts/Hey/README.md
  Packs/Hey/pack_metadata.json
  Tests/conf.json
Labels: docs-approved

#13511 Microsoft ECM - add ssh to prerequisite
  Packs/MicrosoftECM/Integrations/MicrosoftECM/README.md
Labels: docs-approved

#13522 Cofence Feed - Remove `name` field from mapping.
  Packs/FeedCofense/Integrations/FeedCofense/FeedCofense.py
  Packs/FeedCofense/ReleaseNotes/1_0_10.md
  Packs/FeedCofense/pack_metadata.json
Labels: bug, docs-approved, release-notes-only

#13499 Palo Alto Networks PAN-OS - commit/push enhancements
  Packs/PAN-OS/Integrations/Panorama/Panorama.py
  Packs/PAN-OS/Integrations/Panorama/Panorama.yml
  Packs/PAN-OS/Integrations/Panorama/README.md
  Packs/PAN-OS/ReleaseNotes/1_6_20.md
  Packs/PAN-OS/pack_metadata.json
Labels: docs-approved, release-notes-only

#13531 autofocus feed: update description
  Packs/AutoFocus/Integrations/FeedAutofocus/FeedAutofocus_description.md
  Packs/AutoFocus/ReleaseNotes/1_3_4.md
  Packs/AutoFocus/pack_metadata.json
Labels: docs-approved

#13432 Parse html indicators
  Packs/CommonScripts/ReleaseNotes/1_3_68.md
  Packs/CommonScripts/Scripts/ParseHTMLIndicators/ParseHTMLIndicators.py
  Packs/CommonScripts/Scripts/ParseHTMLIndicators/ParseHTMLIndicators.yml
  Packs/CommonScripts/Scripts/ParseHTMLIndicators/Pipfile
  Packs/CommonScripts/Scripts/ParseHTMLIndicators/Pipfile.lock
  Packs/CommonScripts/Scripts/ParseHTMLIndicators/README.md
  Packs/CommonScripts/pack_metadata.json
  Packs/MajorBreachesInvestigationandResponse/ReleaseNotes/1_6_10.md
  Packs/MajorBreachesInvestigationandResponse/Scripts/RapidBreachResponseParseBlog/RapidBreachResponseParseBlog.yml
  Packs/MajorBreachesInvestigationandResponse/pack_metadata.json
Labels: docs-approved

#13534 Unskip TAXII test
  Tests/conf.json
Labels: docs-approved

#13537 fix contrib checkout
  Utils/update_contribution_pack_in_base_branch.py
Labels: docs-approved

#13274 Arcanna pack
  Packs/Arcanna/.pack-ignore
  Packs/Arcanna/.secrets-ignore
  Packs/Arcanna/Integrations/ArcannaAI/ArcannaAI.py
  Packs/Arcanna/Integrations/ArcannaAI/ArcannaAI.yml
  Packs/Arcanna/Integrations/ArcannaAI/ArcannaAI_description.md
  Packs/Arcanna/Integrations/ArcannaAI/ArcannaAI_image.png
  Packs/Arcanna/Integrations/ArcannaAI/ArcannaAI_test.py
  Packs/Arcanna/Integrations/ArcannaAI/Pipfile
  Packs/Arcanna/Integrations/ArcannaAI/Pipfile.lock
  Packs/Arcanna/Integrations/ArcannaAI/README.md
  Packs/Arcanna/Integrations/ArcannaAI/command_examples
  Packs/Arcanna/Integrations/ArcannaAI/test_data/baseintegration-dummy.json
  Packs/Arcanna/Playbooks/playbook-Arcanna-Generic-Investigation.yml
  Packs/Arcanna/Playbooks/playbook-Arcanna-Generic-Investigation_README.md
  Packs/Arcanna/README.md
  Packs/Arcanna/Scripts/PrepareArcannaRawJson/PrepareArcannaRawJson.py
  Packs/Arcanna/Scripts/PrepareArcannaRawJson/PrepareArcannaRawJson.yml
  Packs/Arcanna/Scripts/PrepareArcannaRawJson/README.md
  Packs/Arcanna/pack_metadata.json
Labels: Contribution, Contribution Form Filled, Partner, docs-approved

#13478 ParseEmailFiles - handle mime encoded words
  Packs/CommonScripts/ReleaseNotes/1_3_69.md
  Packs/CommonScripts/Scripts/ParseEmailFiles/ParseEmailFiles.py
  Packs/CommonScripts/Scripts/ParseEmailFiles/ParseEmailFiles_test.py
  Packs/CommonScripts/pack_metadata.json
Labels: docs-approved, release-notes-only

#13535 Majestic Million Feed - Fixed an issue where *HTTPS* connection to th…
  Packs/FeedMajesticMillion/Integrations/MajesticMillion/MajesticMillion.py
  Packs/FeedMajesticMillion/Integrations/MajesticMillion/MajesticMillion.yml
  Packs/FeedMajesticMillion/Integrations/MajesticMillion/README.md
  Packs/FeedMajesticMillion/ReleaseNotes/1_1_4.md
  Packs/FeedMajesticMillion/pack_metadata.json
  Tests/conf.json
Labels: bug, docs-approved, release-notes-only

#13546 PDF reports content release
  Packs/Base/ReleaseNotes/1_12_19.md
  Packs/Base/Scripts/SanePdfReport/SanePdfReport.yml
  Packs/Base/pack_metadata.json
Labels: docs-approved

#13540 Create Indicator relationships- change indicator type to File
  Packs/Base/ReleaseNotes/1_12_20.md
  Packs/Base/Scripts/CreateIndicatorRelationship/CreateIndicatorRelationship.yml
  Packs/Base/pack_metadata.json
Labels: bug, docs-approved, release-notes-only

#13551 VerifyJSON docker image update
  Packs/CommonScripts/ReleaseNotes/1_3_70.md
  Packs/CommonScripts/Scripts/VerifyJSON/VerifyJSON.yml
  Packs/CommonScripts/pack_metadata.json
Labels: docs-approved

#13552 Developer Tools docker image update
  Packs/DeveloperTools/Integrations/XsoarPowershellTesting/XsoarPowershellTesting.yml
  Packs/DeveloperTools/ReleaseNotes/1_1_5.md
  Packs/DeveloperTools/TestPlaybooks/script-PwshInvokeExpression.yml
  Packs/DeveloperTools/pack_metadata.json
Labels: docs-approved

#13555 InfoCyte docker image update
  Packs/Infocyte/Integrations/Infocyte/Infocyte.yml
  Packs/Infocyte/ReleaseNotes/1_0_3.md
  Packs/Infocyte/pack_metadata.json
Labels: docs-approved

#13561 CS PWSH docker image update
  Packs/Base/ReleaseNotes/1_12_21.md
  Packs/Base/Scripts/CommonServerPowerShell/CommonServerPowerShell.yml
  Packs/Base/pack_metadata.json
Labels: docs-approved

#13560 pwsh remoting docker image update
  Packs/PowershellRemoting/Integrations/PowerShellRemoting/PowerShellRemoting.yml
  Packs/PowershellRemoting/ReleaseNotes/1_0_1.md
  Packs/PowershellRemoting/pack_metadata.json
Labels: docs-approved

#13553 unskip redlock/prisma cloud
  Packs/PrismaCloud/TestPlaybooks/playbook-RedLockTest.yml
  Tests/conf.json
Labels: docs-approved

#13564 Teams docker image update
  Packs/MicrosoftTeams/ReleaseNotes/1_1_12.md
  Packs/MicrosoftTeams/Scripts/ConfigureAzureApplicationAccessPolicy/ConfigureAzureApplicationAccessPolicy.yml
  Packs/MicrosoftTeams/pack_metadata.json
Labels: docs-approved

#13549 Kaseya VSA 0-day - REvil Supply Chain Attack playbook
  Packs/MajorBreachesInvestigationandResponse/.pack-ignore
  Packs/MajorBreachesInvestigationandResponse/.secrets-ignore
  Packs/MajorBreachesInvestigationandResponse/Playbooks/playbook-Kaseya_VSA__0-day_-_REvil_Ransomware_Supply_Chain_Attack.yml
  Packs/MajorBreachesInvestigationandResponse/Playbooks/playbook-Kaseya_VSA__0-day_-_REvil_Ransomware_Supply_Chain_Attack_README.md
  Packs/MajorBreachesInvestigationandResponse/README.md
  Packs/MajorBreachesInvestigationandResponse/ReleaseNotes/1_6_11.md
  Packs/MajorBreachesInvestigationandResponse/doc_files/Kaseya_VSA__0-day_-_REvil_Ransomware_Supply_Chain_Attack.png
  Packs/MajorBreachesInvestigationandResponse/pack_metadata.json
Labels: docs-approved

#13496 Fix number of cluster
  Packs/Base/ReleaseNotes/1_12_22.md
  Packs/Base/Scripts/DBotTrainClustering/DBotTrainClustering.py
  Packs/Base/pack_metadata.json
Labels: docs-approved

#13536 Added `session.close()` to the `BaseClient` in common server python
  Packs/Base/ReleaseNotes/1_12_23.md
  Packs/Base/Scripts/CommonServerPython/CommonServerPython.py
  Packs/Base/pack_metadata.json
Labels: docs-approved

#13568 bump version to 21.7.0
  .circleci/content_release_vars.sh
Labels: docs-approved

#13547 AWS Security Hub - add test playbook to parallel integrations
  Tests/conf.json
Labels: docs-approved

#13469 Circle CI integration
  Packs/CircleCI/.pack-ignore
  Packs/CircleCI/.secrets-ignore
  Packs/CircleCI/Integrations/CircleCI/CircleCI.py
  Packs/CircleCI/Integrations/CircleCI/CircleCI.yml
  Packs/CircleCI/Integrations/CircleCI/CircleCI_description.md
  Packs/CircleCI/Integrations/CircleCI/CircleCI_image.png
  Packs/CircleCI/Integrations/CircleCI/CircleCI_test.py
  Packs/CircleCI/Integrations/CircleCI/Pipfile
  Packs/CircleCI/Integrations/CircleCI/Pipfile.lock
  Packs/CircleCI/Integrations/CircleCI/README.md
  Packs/CircleCI/Integrations/CircleCI/command_examples
  Packs/CircleCI/Integrations/CircleCI/test_data/circle_ci_commands_test_data.json
  Packs/CircleCI/README.md
  Packs/CircleCI/TestPlaybooks/CircleCI-Test.yml
  Packs/CircleCI/pack_metadata.json
Labels: docs-approved

#13542 pytest warnings fix
  Packs/Base/ReleaseNotes/1_12_24.md
  Packs/Base/Scripts/DBotFindSimilarIncidents/DBotFindSimilarIncidents.py
  Packs/Base/Scripts/DBotFindSimilarIncidents/DBotFindSimilarIncidents.yml
  Packs/Base/Scripts/DBotFindSimilarIncidents/dbot_find_similar_incidents_test.py
  Packs/Base/Scripts/DBotTrainClustering/DBotTrainClustering.py
  Packs/Base/pack_metadata.json
  Packs/CiscoWebExFeed/Integrations/CiscoWebExFeed/CiscoWebExFeed.py
  Packs/CiscoWebExFeed/Integrations/CiscoWebExFeed/CiscoWebExFeed.yml
  Packs/CiscoWebExFeed/ReleaseNotes/1_1_3.md
  Packs/CiscoWebExFeed/pack_metadata.json
  Packs/Cyberint/Integrations/Cyberint/Cyberint_test.py
  Packs/DeHashed/Integrations/DeHashed/DeHashed_test.py
  Packs/EWS/Integrations/EWSO365/EWSO365.py
  Packs/EWS/ReleaseNotes/1_8_23.md
  Packs/EWS/pack_metadata.json
  Packs/Elasticsearch/Integrations/Elasticsearch_v2/Elasticsearch_v2_test.py
  Packs/FetchIndicatorsFromFile/ReleaseNotes/1_0_4.md
  Packs/FetchIndicatorsFromFile/Scripts/FetchIndicatorsFromFile/FetchIndicatorsFromFile.py
  Packs/FetchIndicatorsFromFile/pack_metadata.json
  Packs/IntSight/Integrations/IntSight/IntSight_test.py
  Packs/MailListener/Integrations/MailListenerV2/MailListenerV2_test.py
  Packs/McAfee_ESM/Integrations/McAfee_ESM_v2/McAfee_ESM_v2_test.py
  Packs/Opsgeniev2/Integrations/Opsgeniev2/Opsgeniev2_test.py
  Packs/ProofpointServerProtection/Integrations/ProofpointProtectionServerV2/ProofpointProtectionServerV2_test.py
  Packs/SymantecManagementCenter/Integrations/SymantecManagementCenter/SymantecManagementCenter_test.py
  Packs/Trello/Integrations/Trello/Trello_test.py
  Packs/VirusTotal/Integrations/VirusTotalV3/VirusTotalV3_test.py
Labels: docs-approved

#13541 IOCs layouts bug
  Packs/CommonTypes/Layouts/layoutscontainer-domain.json
  Packs/CommonTypes/Layouts/layoutscontainer-email.json
  Packs/CommonTypes/Layouts/layoutscontainer-ip.json
  Packs/CommonTypes/Layouts/layoutscontainer-unifiedFile.json
  Packs/CommonTypes/Layouts/layoutscontainer-url.json
  Packs/CommonTypes/ReleaseNotes/3_1_4.md
  Packs/CommonTypes/pack_metadata.json
Labels: bug, docs-approved, release-notes-only

#13583 Kaseya breach enhancement
  Packs/MajorBreachesInvestigationandResponse/Playbooks/playbook-Kaseya_VSA__0-day_-_REvil_Ransomware_Supply_Chain_Attack.yml
  Packs/MajorBreachesInvestigationandResponse/Playbooks/playbook-Kaseya_VSA__0-day_-_REvil_Ransomware_Supply_Chain_Attack_README.md
  Packs/MajorBreachesInvestigationandResponse/README.md
  Packs/MajorBreachesInvestigationandResponse/ReleaseNotes/1_6_12.md
  Packs/MajorBreachesInvestigationandResponse/pack_metadata.json
Labels: docs-approved

#13556 MS ECM docker update
  Packs/MicrosoftECM/Integrations/MicrosoftECM/MicrosoftECM.yml
  Packs/MicrosoftECM/ReleaseNotes/1_0_2.md
  Packs/MicrosoftECM/pack_metadata.json
Labels: docs-approved

#13558 MS PCAL docker image update
  Packs/Office365AndAzureAuditLog/Integrations/MicrosoftPolicyAndComplianceAuditLog/MicrosoftPolicyAndComplianceAuditLog.yml
  Packs/Office365AndAzureAuditLog/ReleaseNotes/1_0_1.md
  Packs/Office365AndAzureAuditLog/pack_metadata.json
Labels: docs-approved

#13586 Start partner adoption process for the Virustotal Private API pack
  Packs/VirusTotal-Private_API/README.md
  Packs/VirusTotal-Private_API/ReleaseNotes/1_0_9.md
  Packs/VirusTotal-Private_API/pack_metadata.json
Labels: Contribution, Contribution Form Filled, Partner, docs-approved

#13455 Updated scripts to execute using the DBot role
  .circleci/content_release_vars.sh
  Packs/Campaign/ReleaseNotes/2_0_7.md
  Packs/Campaign/Scripts/CollectCampaignRecipients/CollectCampaignRecipients.yml
  Packs/Campaign/Scripts/GetCampaignIncidentsInfo/GetCampaignIncidentsInfo.yml
  Packs/Campaign/Scripts/IsIncidentPartOfCampaign/IsIncidentPartOfCampaign.yml
  Packs/Campaign/pack_metadata.json
  Packs/CommonScripts/ReleaseNotes/1_3_71.md
  Packs/CommonScripts/Scripts/ExtractIndicatorsFromWordFile/ExtractIndicatorsFromWordFile.yml
  Packs/CommonScripts/Scripts/NumberOfPhishingAttemptPerUser/NumberOfPhishingAttemptPerUser.yml
  Packs/CommonScripts/Scripts/ReadPDFFileV2/ReadPDFFileV2.yml
  Packs/CommonScripts/Scripts/SetAndHandleEmpty/SetAndHandleEmpty.yml
  Packs/CommonScripts/pack_metadata.json
  Packs/DeveloperTools/TestPlaybooks/script-DeleteIndicators.yml
  Packs/DeveloperTools/TestPlaybooks/script-FormattingPerformance.yml
  Packs/EmailCommunication/ReleaseNotes/1_3_10.md
  Packs/EmailCommunication/Scripts/SendEmailReply/SendEmailReply.yml
  Packs/EmailCommunication/pack_metadata.json
  Packs/ExpanseV2/ReleaseNotes/1_7_1.md
  Packs/ExpanseV2/Scripts/ExpanseGenerateIssueMapWidgetScript/ExpanseGenerateIssueMapWidgetScript.yml
  Packs/ExpanseV2/pack_metadata.json
  Packs/GroupIB_ThreatIntelligenceAttribution/ReleaseNotes/1_0_3.md
  Packs/GroupIB_ThreatIntelligenceAttribution/Scripts/GIBIncidentUpdate/GIBIncidentUpdate.yml
  Packs/GroupIB_ThreatIntelligenceAttribution/pack_metadata.json
  Packs/IntegrationsAndIncidentsHealthCheck/ReleaseNotes/1_2_1.md
  Packs/IntegrationsAndIncidentsHealthCheck/Scripts/CopyLinkedAnalystNotes/CopyLinkedAnalystNotes.yml
  Packs/IntegrationsAndIncidentsHealthCheck/Scripts/GetFailedTasks/GetFailedTasks.yml
  Packs/IntegrationsAndIncidentsHealthCheck/pack_metadata.json
  Packs/NCSCCyberAsssessmentFramework/ReleaseNotes/1_0_1.md
  Packs/NCSCCyberAsssessmentFramework/Scripts/NCSCReportDetails/NCSCReportDetails.yml
  Packs/NCSCCyberAsssessmentFramework/Scripts/NCSCReportDetailsA/NCSCReportDetailsA.yml
  Packs/NCSCCyberAsssessmentFramework/Scripts/NCSCReportDetailsB/NCSCReportDetailsB.yml
  Packs/NCSCCyberAsssessmentFramework/Scripts/NCSCReportDetailsC/NCSCReportDetailsC.yml
  Packs/NCSCCyberAsssessmentFramework/Scripts/NCSCReportDetailsD/NCSCReportDetailsD.yml
  Packs/NCSCCyberAsssessmentFramework/Scripts/NCSCReportOverview/NCSCReportOverview.yml
  Packs/NCSCCyberAsssessmentFramework/pack_metadata.json
  Packs/OnboardingIntegration/ReleaseNotes/1_0_3.md
  Packs/OnboardingIntegration/Scripts/script-OnboardingCleanup.yml
  Packs/OnboardingIntegration/pack_metadata.json
  Packs/PaloAltoNetworks_IoT/ReleaseNotes/1_0_5.md
  Packs/PaloAltoNetworks_IoT/Scripts/iot_check_servicenow/iot_check_servicenow.yml
  Packs/PaloAltoNetworks_IoT/pack_metadata.json
  Packs/PhishLabs/ReleaseNotes/1_0_4.md
  Packs/PhishLabs/Scripts/PhishLabsPopulateIndicators/PhishLabsPopulateIndicators.yml
  Packs/PhishLabs/pack_metadata.json
  Packs/ThreatIntelligenceManagement/ReleaseNotes/1_0_5.md
  Packs/ThreatIntelligenceManagement/Scripts/ThreatIntelligenceManagementGetIncidentsPerFeed/ThreatIntelligenceManagementGetIncidentsPerFeed.yml
  Packs/ThreatIntelligenceManagement/pack_metadata.json
Labels: docs-approved

#13581 sdk release
  dev-requirements-py3.txt
Labels: docs-approved

#13593 Alienvault_OTX_v2 bug fixed- support for multiple ips
  Packs/AlienVault_OTX/Integrations/AlienVault_OTX_v2/AlienVault_OTX_v2.py
  Packs/AlienVault_OTX/Integrations/AlienVault_OTX_v2/AlienVault_OTX_v2.yml
  Packs/AlienVault_OTX/Integrations/AlienVault_OTX_v2/AlienVault_OTX_v2_test.py
  Packs/AlienVault_OTX/ReleaseNotes/1_1_4.md
  Packs/AlienVault_OTX/pack_metadata.json
Labels: docs-approved

#13500 Adding BERT features to DBotMLFetchData
  Packs/Base/ReleaseNotes/1_13_0.md
  Packs/Base/Scripts/DBotMLFetchData/DBotMLFetchData.py
  Packs/Base/Scripts/DBotMLFetchData/DBotMLFetchData.yml
  Packs/Base/Scripts/DBotMLFetchData/DBotMLFetchData_test.py
  Packs/Base/pack_metadata.json
Labels: docs-approved

#13584 Readme image paths repair
  Packs/BreachNotification-US/Playbooks/playbook-Illinois_-_Breach_Notification_README.md
  Packs/Carbon_Black_Enterprise_Response/Playbooks/playbook-Search_Endpoints_By_Hash_-_Carbon_Black_Response_V2_README.md
  Packs/CheckpointFirewall/Playbooks/README.md
  Packs/CommonPlaybooks/Playbooks/playbook-Block_IP_-_Generic_v2_README.md
  Packs/CommonPlaybooks/Playbooks/playbook-Detonate_File_-_Generic_README.md
  Packs/CommonPlaybooks/Playbooks/playbook-Detonate_URL_-_Generic_README.md
  Packs/CommonPlaybooks/Playbooks/playbook-Search_Endpoints_By_Hash_-_Generic_V2_README.md
  Packs/CortexXDR/Playbooks/Cortex_XDR_-_Check_Action_Status_README.md
  Packs/CortexXDR/Playbooks/Cortex_XDR_-_Port_Scan_README.md
  Packs/CrowdStrikeHost/Playbooks/playbook-CrowdStrike_Rapid_IOC_Hunting_v2_README.md
  Packs/DeprecatedContent/Playbooks/playbook-Account_Enrichment_README.md
  Packs/DeprecatedContent/Playbooks/playbook-ExtraHop_-_Ticket_Tracking_README.md
  Packs/Gurucul/Playbooks/playbook-GraCase-README.md
  Packs/Gurucul/Playbooks/playbook-GraHighRiskUser-README.md
  Packs/Hunting/Playbooks/playbook-Hunt_Extracted_Hashes_V2_README.md
  Packs/MailSenderNew/Integrations/MailSenderNew/README.md
  Packs/Malware/Playbooks/playbook-Malware_Investigation_-_Manual_README.md
  Packs/McAfee_DXL/Playbooks/playbook-Enrich_DXL_with_ATD_verdict_v2_README.md
  Packs/McAfee_DXL/Playbooks/playbook-Enrich_McAfee_DXL_using_3rd_party_sandbox_v2_README.md
  Packs/PANOStoCDLMonitoring/Playbooks/PANOStoCDLMonitoring-cron_job_README.md
  Packs/PopularCybersecurityNews/Playbooks/playbook-JOB_-_Popular_News_README.md
  Packs/ProofpointTAP/Playbooks/playbook-Event_Enrichment_README.md
  Packs/RiskIQDigitalFootprint/Playbooks/playbook-Add_Unknown_Indicators_To_Inventory_-_RiskIQ_Digital_Footprint_README.md
  Packs/RiskIQDigitalFootprint/Playbooks/playbook-Auto_Add_Assets_-_RiskIQ_Digital_Footprint_README.md
  Packs/RiskIQDigitalFootprint/Playbooks/playbook-Auto_Update_Or_Remove_Assets_-_RiskIQ_Digital_Footprint_README.md
  Packs/RiskIQDigitalFootprint/Playbooks/playbook-Check_IP_Address_For_Whitelisting_-_RiskIQ_Digital_Footprint_README.md
  Packs/RiskIQDigitalFootprint/Playbooks/playbook-Check_Indicators_For_Unkown_Assets_-_RiskIQ_Digital_Footprint_README.md
  Packs/RiskIQDigitalFootprint/Playbooks/playbook-IP_Whitelist_And_Exclusion_-_RiskIQ_Digital_Footprint_README.md
  Packs/RiskIQDigitalFootprint/Playbooks/playbook-RiskIQAsset_Basic_Information_Enrichment-RiskIQ_Digital_Footprint_README.md
  Packs/RiskIQDigitalFootprint/Playbooks/playbook-RiskIQAsset_Enrichment_-_RiskIQ_Digital_Footprint_README.md
  Packs/RiskIQDigitalFootprint/Playbooks/playbook-Vulnerability_Scan_-_RiskIQ_Digital_Footprint_-_Tenable.io_README.md
  Packs/XSOARContentUpdateNotifications/Playbooks/playbook-Check_For_Content_Installation_README.md
  Packs/XSOARContentUpdateNotifications/Playbooks/playbook-Content_Update_Check_README.md
  Packs/epo/Playbooks/playbook-McAfee_ePO_Endpoint_Compliance_v2_README.md
  Packs/epo/Playbooks/playbook-McAfee_ePO_Endpoint_Connectivity_Diagnostics_v2_README.md
  Packs/epo/Playbooks/playbook-McAfee_ePO_Repository_Compliance_v2_README.md
Labels: docs-approved

#13601 Alien vault malformed handle
  Packs/AlienVault_OTX/Integrations/AlienVault_OTX_v2/AlienVault_OTX_v2.py
  Packs/AlienVault_OTX/ReleaseNotes/1_1_5.md
  Packs/AlienVault_OTX/pack_metadata.json
Labels: docs-approved

#12332 Hatching Triage 1.0.1
  Packs/HatchingTriage/Integrations/HatchingTriage/HatchingTriage.py
  Packs/HatchingTriage/Integrations/HatchingTriage/HatchingTriage.yml
  Packs/HatchingTriage/README.md
  Packs/HatchingTriage/ReleaseNotes/1_0_1.md
  Packs/HatchingTriage/pack_metadata.json
Labels: Contribution, Contribution Form Filled, Partner, docs-approved, pending-partner

#13597 Print nightmare | Microsoft patch
  Packs/MajorBreachesInvestigationandResponse/Playbooks/playbook-CVE-2021-1675_-_PrintNightmare.yml
  Packs/MajorBreachesInvestigationandResponse/Playbooks/playbook-CVE-2021-1675_-_PrintNightmare_README.md
  Packs/MajorBreachesInvestigationandResponse/ReleaseNotes/1_6_13.md
  Packs/MajorBreachesInvestigationandResponse/pack_metadata.json
Labels: docs-approved

#13603 Unmock oproxy prod microsoft tests
  Tests/conf.json
Labels: docs-approved

#13554 EWS docker image update
  Packs/EWS/Integrations/EwsExtension/EwsExtension.yml
  Packs/EWS/Integrations/EwsExtensionEXOPowershellV2/EwsExtensionEXOPowershellV2.yml
  Packs/EWS/Integrations/SecurityAndCompliance/SecurityAndCompliance.yml
  Packs/EWS/ReleaseNotes/1_8_24.md
  Packs/EWS/Scripts/CreateCertificate/CreateCertificate.yml
  Packs/EWS/TestPlaybooks/playbook-O365-SecurityAndCompliance-Test.yml
  Packs/EWS/pack_metadata.json
  Tests/conf.json
Labels: docs-approved

#13596 VirusTotal: fixed dependencies issue
  Packs/VirusTotal/Playbooks/Detonate_File-VirusTotal.yml
  Packs/VirusTotal/ReleaseNotes/2_1_3.md
  Packs/VirusTotal/pack_metadata.json
Labels: docs-approved

#13610 Kaseya playbook enhancement
  Packs/MajorBreachesInvestigationandResponse/Playbooks/playbook-Kaseya_VSA__0-day_-_REvil_Ransomware_Supply_Chain_Attack.yml
  Packs/MajorBreachesInvestigationandResponse/Playbooks/playbook-Kaseya_VSA__0-day_-_REvil_Ransomware_Supply_Chain_Attack_README.md
  Packs/MajorBreachesInvestigationandResponse/ReleaseNotes/1_6_14.md
  Packs/MajorBreachesInvestigationandResponse/doc_files/Kaseya_VSA__0-day_-_REvil_Ransomware_Supply_Chain_Attack.png
  Packs/MajorBreachesInvestigationandResponse/pack_metadata.json
Labels: docs-approved

#13615 stabilizing fetch data testa
  Packs/Base/Scripts/DBotMLFetchData/DBotMLFetchData_test.py
Labels: docs-approved

#13068 Rss feed
  Packs/CommonTypes/IndicatorFields/indicatorfield-Publications.json
  Packs/CommonTypes/ReleaseNotes/3_1_5.md
  Packs/CommonTypes/pack_metadata.json
  Packs/FeedRSS/.pack-ignore
  Packs/FeedRSS/.secrets-ignore
  Packs/FeedRSS/IndicatorFields/indicatorfield-rawcontent.json
  Packs/FeedRSS/Integrations/FeedRSS/FeedRSS.py
  Packs/FeedRSS/Integrations/FeedRSS/FeedRSS.yml
  Packs/FeedRSS/Integrations/FeedRSS/FeedRSS_description.md
  Packs/FeedRSS/Integrations/FeedRSS/FeedRSS_image.png
  Packs/FeedRSS/Integrations/FeedRSS/FeedRSS_test.py
  Packs/FeedRSS/Integrations/FeedRSS/Pipfile
  Packs/FeedRSS/Integrations/FeedRSS/Pipfile.lock
  Packs/FeedRSS/Integrations/FeedRSS/README.md
  Packs/FeedRSS/Integrations/FeedRSS/test_data/test_variables.py
  Packs/FeedRSS/Playbooks/Extract_and_Create_Relationships.yml
  Packs/FeedRSS/Playbooks/Extract_and_Create_Relationships_README.md
  Packs/FeedRSS/Playbooks/RSS_Create_Indicators_From_Report.yml
  Packs/FeedRSS/Playbooks/RSS_Create_Indicators_From_Report_README.md
  Packs/FeedRSS/README.md
  Packs/FeedRSS/doc_files/Extract_and_create_relationships_playbook_image.png
  Packs/FeedRSS/doc_files/Rss_create_indicators_playbook_image.png
  Packs/FeedRSS/pack_metadata.json
Labels: docs-approved

#13602 QRadar pack documentation
  Packs/QRadar/README.md
Labels: docs-approved

#13613 Ext filter
  Packs/ExtFilter/ReleaseNotes/1_1_5.md
  Packs/ExtFilter/Scripts/ExtFilter/ExtFilter.py
  Packs/ExtFilter/pack_metadata.json
Labels: Community, Contribution, Contribution Form Filled, docs-approved

#13595 Changed handling of params
  Packs/MicrosoftECM/Integrations/MicrosoftECM/MicrosoftECM.ps1
  Packs/MicrosoftECM/ReleaseNotes/1_0_3.md
  Packs/MicrosoftECM/pack_metadata.json
Labels: docs-approved

#13600 Deprecate qualys v1
  Packs/qualys/Integrations/integration-qualys.yml
  Packs/qualys/ReleaseNotes/1_0_5.md
  Packs/qualys/pack_metadata.json
Labels: docs-approved, release-notes-only

#13459 edl management - Added the *retries* argument, sort lists, refactor for mypy and UT
  Packs/PaloAltoNetworks_PAN_OS_EDL_Management/Integrations/PaloAltoNetworks_PAN_OS_EDL_Management/PaloAltoNetworks_PAN_OS_EDL_Management.py
  Packs/PaloAltoNetworks_PAN_OS_EDL_Management/Integrations/PaloAltoNetworks_PAN_OS_EDL_Management/PaloAltoNetworks_PAN_OS_EDL_Management.yml
  Packs/PaloAltoNetworks_PAN_OS_EDL_Management/Integrations/PaloAltoNetworks_PAN_OS_EDL_Management/PaloAltoNetworks_PAN_OS_EDL_Management_test.py
  Packs/PaloAltoNetworks_PAN_OS_EDL_Management/Integrations/PaloAltoNetworks_PAN_OS_EDL_Management/README.md
  Packs/PaloAltoNetworks_PAN_OS_EDL_Management/Integrations/PaloAltoNetworks_PAN_OS_EDL_Management/command_examples.txt
  Packs/PaloAltoNetworks_PAN_OS_EDL_Management/ReleaseNotes/1_1_0.md
  Packs/PaloAltoNetworks_PAN_OS_EDL_Management/pack_metadata.json
  Tests/conf.json
Labels: docs-approved

#13577 Covalence (git username solved)
  Packs/CovalenceForSecurityProviders/.pack-ignore
  Packs/CovalenceForSecurityProviders/.secrets-ignore
  Packs/CovalenceForSecurityProviders/Integrations/CovalenceForSecurityProviders/CovalenceForSecurityProviders.py
  Packs/CovalenceForSecurityProviders/Integrations/CovalenceForSecurityProviders/CovalenceForSecurityProviders.yml
  Packs/CovalenceForSecurityProviders/Integrations/CovalenceForSecurityProviders/CovalenceForSecurityProviders_description.md
  Packs/CovalenceForSecurityProviders/Integrations/CovalenceForSecurityProviders/CovalenceForSecurityProviders_image.png
  Packs/CovalenceForSecurityProviders/Integrations/CovalenceForSecurityProviders/CovalenceForSecurityProviders_test.py
  Packs/CovalenceForSecurityProviders/Integrations/CovalenceForSecurityProviders/Pipfile
  Packs/CovalenceForSecurityProviders/Integrations/CovalenceForSecurityProviders/Pipfile.lock
  Packs/CovalenceForSecurityProviders/Integrations/CovalenceForSecurityProviders/README.md
  Packs/CovalenceForSecurityProviders/Integrations/CovalenceForSecurityProviders/command_examples
  Packs/CovalenceForSecurityProviders/Integrations/CovalenceForSecurityProviders/test_data/connections_summary_by_ip.json
  Packs/CovalenceForSecurityProviders/Integrations/CovalenceForSecurityProviders/test_data/connections_summary_by_port.json
  Packs/CovalenceForSecurityProviders/Integrations/CovalenceForSecurityProviders/test_data/get_sensor.json
  Packs/CovalenceForSecurityProviders/Integrations/CovalenceForSecurityProviders/test_data/list_alerts.json
  Packs/CovalenceForSecurityProviders/Integrations/CovalenceForSecurityProviders/test_data/list_dns_resolutions.json
  Packs/CovalenceForSecurityProviders/Integrations/CovalenceForSecurityProviders/test_data/list_endpoint_agents.json
  Packs/CovalenceForSecurityProviders/Integrations/CovalenceForSecurityProviders/test_data/list_internal_networks.json
  Packs/CovalenceForSecurityProviders/Integrations/CovalenceForSecurityProviders/test_data/list_sensor.json
  Packs/CovalenceForSecurityProviders/Integrations/CovalenceForSecurityProviders/test_data/search_endpoint_installed_software.json
  Packs/CovalenceForSecurityProviders/Integrations/CovalenceForSecurityProviders/test_data/search_endpoint_process.json
  Packs/CovalenceForSecurityProviders/README.md
  Packs/CovalenceForSecurityProviders/pack_metadata.json
  Packs/CovalenceManagedSecurity/.pack-ignore
  Packs/CovalenceManagedSecurity/.secrets-ignore
  Packs/CovalenceManagedSecurity/Integrations/CovalenceManagedSecurity/CovalenceManagedSecurity.py
  Packs/CovalenceManagedSecurity/Integrations/CovalenceManagedSecurity/CovalenceManagedSecurity.yml
  Packs/CovalenceManagedSecurity/Integrations/CovalenceManagedSecurity/CovalenceManagedSecurity_description.md
  Packs/CovalenceManagedSecurity/Integrations/CovalenceManagedSecurity/CovalenceManagedSecurity_image.png
  Packs/CovalenceManagedSecurity/Integrations/CovalenceManagedSecurity/CovalenceManagedSecurity_test.py
  Packs/CovalenceManagedSecurity/Integrations/CovalenceManagedSecurity/Pipfile
  Packs/CovalenceManagedSecurity/Integrations/CovalenceManagedSecurity/Pipfile.lock
  Packs/CovalenceManagedSecurity/Integrations/CovalenceManagedSecurity/README.md
  Packs/CovalenceManagedSecurity/Integrations/CovalenceManagedSecurity/command_examples
  Packs/CovalenceManagedSecurity/Integrations/CovalenceManagedSecurity/test_data/get_aros.json
  Packs/CovalenceManagedSecurity/Integrations/CovalenceManagedSecurity/test_data/get_org.json
  Packs/CovalenceManagedSecurity/README.md
  Packs/CovalenceManagedSecurity/pack_metadata.json
Labels: Contribution, Contribution Form Filled, Partner, docs-approved

#13336 Abnormal security
  Packs/AbnormalSecurity/.pack-ignore
  Packs/AbnormalSecurity/.secrets-ignore
  Packs/AbnormalSecurity/Integrations/AbnormalSecurity/AbnormalSecurity.py
  Packs/AbnormalSecurity/Integrations/AbnormalSecurity/AbnormalSecurity.yml
  Packs/AbnormalSecurity/Integrations/AbnormalSecurity/AbnormalSecurity_description.md
  Packs/AbnormalSecurity/Integrations/AbnormalSecurity/AbnormalSecurity_image.png
  Packs/AbnormalSecurity/Integrations/AbnormalSecurity/AbnormalSecurity_test.py
  Packs/AbnormalSecurity/Integrations/AbnormalSecurity/Pipfile
  Packs/AbnormalSecurity/Integrations/AbnormalSecurity/Pipfile.lock
  Packs/AbnormalSecurity/Integrations/AbnormalSecurity/README.md
  Packs/AbnormalSecurity/Integrations/AbnormalSecurity/command_examples
  Packs/AbnormalSecurity/Integrations/AbnormalSecurity/test_data/fixtures.py
  Packs/AbnormalSecurity/Integrations/AbnormalSecurity/test_data/test_check_status_of_action_requested_on_case.json
  Packs/AbnormalSecurity/Integrations/AbnormalSecurity/test_data/test_check_status_of_action_requested_on_threat.json
  Packs/AbnormalSecurity/Integrations/AbnormalSecurity/test_data/test_get_details_of_an_abnormal_case.json
  Packs/AbnormalSecurity/Integrations/AbnormalSecurity/test_data/test_get_list_of_abnormal_cases.json
  Packs/AbnormalSecurity/Integrations/AbnormalSecurity/test_data/test_get_list_of_abnormal_threats.json
  Packs/AbnormalSecurity/Integrations/AbnormalSecurity/test_data/test_get_threat_intel_feed.json
  Packs/AbnormalSecurity/Integrations/AbnormalSecurity/test_data/test_manage_case.json
  Packs/AbnormalSecurity/Integrations/AbnormalSecurity/test_data/test_manage_threat.json
  Packs/AbnormalSecurity/README.md
  Packs/AbnormalSecurity/pack_metadata.json
  Packs/AbnormalSecurity/secrets_white_list.json
Labels: Contribution, Contribution Form Filled, Partner, docs-approved, post-demo

#13624 Stabilizing fetch data tests (round 2)
  Packs/Base/Scripts/DBotMLFetchData/DBotMLFetchData_test.py
  Packs/Base/Scripts/DBotMLFetchData/test_data/100_incidents.p
  Packs/Base/Scripts/DBotMLFetchData/test_data/30_incidents.p
Labels: docs-approved

#13628 Contribution Form - MP contributions bugfix
  .github/workflows/check-contribution-form-filled.yml
Labels: docs-approved

#13160 ILM - Adding the option to change samaccountname in AD
  Packs/Active_Directory_Query/Classifiers/classifier-User_Profile_-_Active_Directory_(Outgoing).json
  Packs/Active_Directory_Query/Integrations/Active_Directory_Query/Active_Directory_Query.py
  Packs/Active_Directory_Query/Integrations/Active_Directory_Query/Active_Directory_Query.yml
  Packs/Active_Directory_Query/Integrations/Active_Directory_Query/README.md
  Packs/Active_Directory_Query/Integrations/Active_Directory_Query/connection_test.py
  Packs/Active_Directory_Query/ReleaseNotes/1_1_13.md
  Packs/Active_Directory_Query/pack_metadata.json
Labels: IAM, docs-approved, release-notes-only

#13623 Deprecate Carbon Black EDR v1
  Packs/Carbon_Black_Enterprise_Response/Integrations/CarbonBlackResponseV2/README.md
  Packs/Carbon_Black_Enterprise_Response/Integrations/README.md
  Packs/Carbon_Black_Enterprise_Response/Integrations/integration-Carbon_Black_Enterprise_Response.yml
  Packs/Carbon_Black_Enterprise_Response/README.md
  Packs/Carbon_Black_Enterprise_Response/ReleaseNotes/2_1_0.md
  Packs/Carbon_Black_Enterprise_Response/pack_metadata.json
Labels: docs-approved, release-notes-only

#13632 CM - PB inputs removal
  Packs/ContentManagement/Playbooks/playbook-Configuration_Setup.yml
  Packs/ContentManagement/ReleaseNotes/1_0_1.md
  Packs/ContentManagement/pack_metadata.json
Labels: docs-approved, release-notes-only

#13627 Removed insert links comments
  Packs/Akamai_SIEM/Integrations/Akamai_SIEM/README.md
  Packs/CloudShark/Integrations/CloudShark/README.md
  Packs/DeprecatedContent/Integrations/PaloAltoNetworksCortex/README.md
  Packs/GoogleCloudTranslate/Integrations/GoogleCloudTranslate/README.md
  Packs/Infoblox/Integrations/Infoblox/README.md
  Packs/IronDefense/Integrations/IronDefense/README.md
  Packs/MicrosoftGraphCalendar/Integrations/MicrosoftGraphCalendar/README.md
  Packs/MicrosoftGraphGroups/Integrations/MicrosoftGraphGroups/README.md
  Packs/MicrosoftGraphListener/Integrations/MicrosoftGraphListener/README.md
  Packs/Mimecast/Integrations/MimecastV2/README.md
  Packs/PhishLabs/Integrations/PhishLabsIOC_DRP/README.md
  Packs/PhishLabs/Integrations/PhishLabsIOC_EIR/README.md
  Packs/SMIME_Messaging/Integrations/SMIME_Messaging/README.md
  Packs/SlashNextPhishingIncidentResponse/Integrations/SlashNextPhishingIncidentResponse/README.md
  Packs/SymantecBlueCoatMalwareAnalysis/Integrations/SymantecBlueCoatMalwareAnalysis/README.md
  Packs/SymantecDLP/Integrations/SymantecDLP/README.md
  Packs/Tanium/Integrations/Tanium_v2/README.md
  Packs/ThreatConnect/Integrations/ThreatConnect/README.md
  Packs/Traps/Integrations/PaloAltoNetworks_Traps/README.md
  Packs/Vectra/Integrations/Vectra_v2/README.md
Labels: docs-approved

#13625 ParseEmailFiles - added multipart/alternative format
  Packs/CommonScripts/ReleaseNotes/1_3_72.md
  Packs/CommonScripts/Scripts/ParseEmailFiles/ParseEmailFiles.py
  Packs/CommonScripts/Scripts/ParseEmailFiles/ParseEmailFiles_test.py
  Packs/CommonScripts/Scripts/ParseEmailFiles/test_data/multipart_alternative_format.p7m
  Packs/CommonScripts/pack_metadata.json
Labels: bug, docs-approved, release-notes-only

#13635 upgraded docker image for pwsh ubuntu
  Packs/DeveloperTools/Integrations/XsoarPowershellTesting/XsoarPowershellTesting.yml
  Packs/DeveloperTools/ReleaseNotes/1_1_6.md
  Packs/DeveloperTools/pack_metadata.json
  Packs/PowershellRemoting/Integrations/PowerShellRemoting/PowerShellRemoting.yml
  Packs/PowershellRemoting/ReleaseNotes/1_0_2.md
  Packs/PowershellRemoting/pack_metadata.json
Labels: docs-approved

#13563 [Test Fix] Extract Indicators From File - Generic v2
  Packs/CommonPlaybooks/Playbooks/playbook-Extract_Indicators_From_File_-_Generic_v2_4_5.yml
  Packs/CommonPlaybooks/ReleaseNotes/1_9_10.md
  Packs/CommonPlaybooks/TestPlaybooks/playbook-Extract_Indicators_From_File_-_Generic_v2_-_Test_4_5.yml
  Packs/CommonPlaybooks/pack_metadata.json
  Tests/conf.json
Labels: docs-approved

#13293 QRadar v3 enhance docs
  Packs/QRadar/Integrations/QRadar_v3/README.md
Labels: docs-approved

#13633 added xsoar extension
  .vscode/extensions.json
Labels: docs-approved

#13634 Move LogRhythm to unmockable_integrations
  Tests/conf.json
Labels: docs-approved

#13631 edited the ignore error for some files
  Packs/AWS-EC2/.pack-ignore
  Packs/DNSDB/.pack-ignore
  Packs/EDL/.pack-ignore
  Packs/FeedAWS/.pack-ignore
  Packs/FeedAzure/.pack-ignore
  Packs/FeedOffice365/.pack-ignore
  Packs/GoogleChronicleBackstory/.pack-ignore
  Packs/GoogleCloudCompute/.pack-ignore
  Packs/Okta/.pack-ignore
  Packs/PingCastle/.pack-ignore
  Packs/PrismaAccess/.pack-ignore
  Packs/RiskIQDigitalFootprint/.pack-ignore
  Packs/TIM_Processing/.pack-ignore
  Packs/mnemonicMDR/.pack-ignore
Labels: docs-approved

#13241 added some fixes for when the post update tests fail
  Tests/configure_and_test_integration_instances.py
  Tests/private_build/configure_and_test_integration_instances_private.py
  Tests/private_build/run_content_tests_private.py
  Tests/scripts/destroy_instances.py
Labels: docs-approved

#13637 remove empty test files
  Packs/ContentManagement/Scripts/ConfigurationSetup/ConfigurationSetup_test.py
  Packs/ContentManagement/Scripts/CustomPackInstaller/CustomPackInstaller_test.py
  Packs/ContentManagement/Scripts/JobCreator/JobCreator_test.py
  Packs/ContentManagement/Scripts/ListCreator/ListCreator_test.py
  Packs/ContentManagement/Scripts/MarketplacePackInstaller/MarketplacePackInstaller_test.py
  Packs/FeedBlocklist_de/Integrations/FeedBlocklist_de/FeedBlocklist_de_test.py
Labels: docs-approved

#13566 Move SplunkPy images to content repository
  Packs/SplunkPy/doc_files/build-query.png
  Packs/SplunkPy/doc_files/classify.png
  Packs/SplunkPy/doc_files/http-event-collector.png
  Packs/SplunkPy/doc_files/http-port-number.png
  Packs/SplunkPy/doc_files/identify-fields-list.png
  Packs/SplunkPy/doc_files/incident_type.png
  Packs/SplunkPy/doc_files/macro.png
  Packs/SplunkPy/doc_files/mapping.png
  Packs/SplunkPy/doc_files/micro-name.png
  Packs/SplunkPy/doc_files/scheduled-search.png
  Packs/SplunkPy/doc_files/summary-index.png
Labels: docs-approved

#13636 PAN-OS - Added the target argument to the panorama-security-policy-ma…
  Packs/PAN-OS/Integrations/Panorama/Panorama.py
  Packs/PAN-OS/Integrations/Panorama/Panorama.yml
  Packs/PAN-OS/Integrations/Panorama/Panorama_test.py
  Packs/PAN-OS/Integrations/Panorama/README.md
  Packs/PAN-OS/ReleaseNotes/1_6_21.md
  Packs/PAN-OS/pack_metadata.json
Labels: docs-approved, release-notes-only

#13557 Update links to images in Splunk README
  Packs/SplunkPy/Integrations/SplunkPy/README.md
  Packs/SplunkPy/doc_files/Splunk_Generic.png
Labels: docs-approved

#13620 Eli/pytest warnings
  Packs/Active_Directory_Query/Integrations/Active_Directory_Query/connection_test.py
  Packs/Akamai_SIEM/Integrations/Akamai_SIEM/Akamai_SIEM_test.py
  Packs/Box/Integrations/BoxV2/BoxV2.py
  Packs/Box/Integrations/BoxV2/BoxV2.yml
  Packs/Box/Integrations/BoxV2/BoxV2_test.py
  Packs/Box/ReleaseNotes/2_1_3.md
  Packs/Box/pack_metadata.json
  Packs/Exabeam/Integrations/Exabeam/Exabeam.py
  Packs/Exabeam/ReleaseNotes/2_1_3.md
  Packs/Exabeam/pack_metadata.json
  Packs/GoogleBigQuery/Integrations/GoogleBigQuery/GoogleBigQuery.yml
  Packs/GoogleBigQuery/ReleaseNotes/1_0_1.md
  Packs/GoogleBigQuery/pack_metadata.json
  Packs/McAfee_ESM/Integrations/McAfee_ESM_v2/McAfee_ESM_v2.py
  Packs/McAfee_ESM/ReleaseNotes/1_1_10.md
  Packs/McAfee_ESM/pack_metadata.json
  Packs/SMIME_Messaging/Integrations/SMIME_Messaging/SMIME_Messaging.yml
  Packs/SMIME_Messaging/ReleaseNotes/1_0_2.md
  Packs/SMIME_Messaging/pack_metadata.json
  Packs/rasterize/Integrations/rasterize/rasterize_test.py
Labels: docs-approved

#13591 EWSv2 new docker image
  Packs/EWS/Integrations/EWSv2/EWSv2.yml
  Packs/EWS/ReleaseNotes/1_8_25.md
  Packs/EWS/pack_metadata.json
Labels: docs-approved

#13640 improve tim lic message clarity
  Packs/AutoFocus/Integrations/AutofocusV2/AutofocusV2.yml
  Packs/AutoFocus/Integrations/AutofocusV2/README.md
  Packs/AutoFocus/Integrations/FeedAutofocus/FeedAutofocus.yml
  Packs/AutoFocus/Integrations/FeedAutofocus/README.md
  Packs/AutoFocus/Integrations/FeedAutofocusDaily/FeedAutofocusDaily.yml
  Packs/AutoFocus/Integrations/FeedAutofocusDaily/README.md
  Packs/AutoFocus/ReleaseNotes/1_3_5.md
  Packs/AutoFocus/pack_metadata.json
  Packs/PaloAltoNetworks_Threat_Vault/Integrations/Threat_Vault/README.md
  Packs/PaloAltoNetworks_Threat_Vault/Integrations/Threat_Vault/Threat_Vault.yml
  Packs/PaloAltoNetworks_Threat_Vault/ReleaseNotes/1_0_6.md
  Packs/PaloAltoNetworks_Threat_Vault/pack_metadata.json
Labels: bug, docs-approved, release-notes-only

#13646 [Test] FireEyeNX-Test remove from skipped
  Tests/conf.json
Labels: docs-approved

#13647 update secrets ignore
  Packs/LogRhythmRest/.secrets-ignore
Labels: docs-approved

#13648 added error
  Packs/Sixgill-Darkfeed/.pack-ignore
Labels: docs-approved

#13650 Add badge to open the repo in vs code
  README.md
  Tests/secrets_white_list.json
Labels: docs-approved

#13420 Refactor EDL
  Packs/Base/ReleaseNotes/1_13_1.md
  Packs/Base/Scripts/CommonServerPython/CommonServerPython.py
  Packs/Base/Scripts/CommonServerPython/CommonServerPython_test.py
  Packs/Base/Scripts/GetIndicatorsByQuery/get_indicators_by_query_test.py
  Packs/Base/pack_metadata.json
  Packs/EDL/.pack-ignore
  Packs/EDL/.secrets-ignore
  Packs/EDL/Integrations/EDL/EDL.py
  Packs/EDL/Integrations/EDL/EDL.yml
  Packs/EDL/Integrations/EDL/EDL_test.py
  Packs/EDL/Integrations/EDL/EDL_test/TestHelperFunctions/iocs_cache_values_text.txt
  Packs/EDL/Integrations/EDL/EDL_test/TestHelperFunctions/simplified_demisto_ip_iocs.json
  Packs/EDL/Integrations/EDL/EDL_test/TestHelperFunctions/simplified_demisto_ip_v6_iocs.json
  Packs/EDL/Integrations/EDL/README.md
  Packs/EDL/ReleaseNotes/2_1_0.md
  Packs/EDL/pack_metadata.json
  Packs/Hey/.pack-ignore
  Packs/Hey/TestPlaybooks/playbook-EDL_Indicator_Performance_Test.yml
  Packs/Hey/TestPlaybooks/playbook-EDL_Performance_Test.yml
  Packs/Hey/TestPlaybooks/playbook-EDL_Performance_Test_-_Concurrency.yml
Labels: docs-approved

#13649 Copy notes to incident bug
  Packs/CommonScripts/ReleaseNotes/1_3_73.md
  Packs/CommonScripts/Scripts/CopyNotesToIncident/CopyNotesToIncident.py
  Packs/CommonScripts/Scripts/CopyNotesToIncident/CopyNotesToIncident.yml
  Packs/CommonScripts/Scripts/CopyNotesToIncident/test_data/entries.json
  Packs/CommonScripts/pack_metadata.json
Labels: bug, docs-approved, release-notes-only

#13655 [Test] Unskip EmailRepIO-Test
  Tests/conf.json
Labels: docs-approved

#13394 Updates to the Devo_v2 plugin
  Packs/Devo/Integrations/Devo_v2/Devo_v2.py
  Packs/Devo/Integrations/Devo_v2/Devo_v2.yml
  Packs/Devo/Integrations/Devo_v2/Devo_v2_description.md
  Packs/Devo/Integrations/Devo_v2/Devo_v2_test.py
  Packs/Devo/Integrations/Devo_v2/README.md
  Packs/Devo/README.md
  Packs/Devo/ReleaseNotes/1_1_0.md
  Packs/Devo/pack_metadata.json
Labels: Contribution, Contribution Form Filled, Partner

#12793 Safewalk initial pack
  Packs/Safewalk/.pack-ignore
  Packs/Safewalk/.secrets-ignore
  Packs/Safewalk/Integrations/SafewalkManagement/Pipfile
  Packs/Safewalk/Integrations/SafewalkManagement/Pipfile.lock
  Packs/Safewalk/Integrations/SafewalkManagement/README.md
  Packs/Safewalk/Integrations/SafewalkManagement/SafewalkManagement.py
  Packs/Safewalk/Integrations/SafewalkManagement/SafewalkManagement.yml
  Packs/Safewalk/Integrations/SafewalkManagement/SafewalkManagement_description.md
  Packs/Safewalk/Integrations/SafewalkManagement/SafewalkManagement_image.png
  Packs/Safewalk/Integrations/SafewalkManagement/SafewalkManagement_test.py
  Packs/Safewalk/Integrations/SafewalkManagement/command_examples
  Packs/Safewalk/Integrations/SafewalkManagement/test_data/baseintegration-dummy.json
  Packs/Safewalk/Integrations/SafewalkReports/Pipfile
  Packs/Safewalk/Integrations/SafewalkReports/Pipfile.lock
  Packs/Safewalk/Integrations/SafewalkReports/README.md
  Packs/Safewalk/Integrations/SafewalkReports/SafewalkReports.py
  Packs/Safewalk/Integrations/SafewalkReports/SafewalkReports.yml
  Packs/Safewalk/Integrations/SafewalkReports/SafewalkReports_description.md
  Packs/Safewalk/Integrations/SafewalkReports/SafewalkReports_image.png
  Packs/Safewalk/Integrations/SafewalkReports/SafewalkReports_test.py
  Packs/Safewalk/Integrations/SafewalkReports/command_examples
  Packs/Safewalk/Integrations/SafewalkReports/test_data/baseintegration-dummy.json
  Packs/Safewalk/README.md
  Packs/Safewalk/pack_metadata.json
Labels: Contribution, Contribution Form Filled, Partner, docs-approved, pending-demo

#13661 Copy the updated conf to Tests/conf.json before running tests
  .gitlab/ci/on-push.yml
Labels: docs-approved

#12671 Cofense intelligence v2 integration
  Packs/Cofense-Intelligence/Integrations/README.md
  Packs/Cofense-Intelligence/Integrations/integration-Cofense-Intelligence.yml
  Packs/Cofense-Intelligence/ReleaseNotes/1_0_2.md
  Packs/Cofense-Intelligence/pack_metadata.json
  Packs/CofenseIntelligenceV2/.pack-ignore
  Packs/CofenseIntelligenceV2/.secrets-ignore
  Packs/CofenseIntelligenceV2/Integrations/CofenseIntelligenceV2/CofenseIntelligenceV2.py
  Packs/CofenseIntelligenceV2/Integrations/CofenseIntelligenceV2/CofenseIntelligenceV2.yml
  Packs/CofenseIntelligenceV2/Integrations/CofenseIntelligenceV2/CofenseIntelligenceV2_description.md
  Packs/CofenseIntelligenceV2/Integrations/CofenseIntelligenceV2/CofenseIntelligenceV2_image.png
  Packs/CofenseIntelligenceV2/Integrations/CofenseIntelligenceV2/CofenseIntelligenceV2_test.py
  Packs/CofenseIntelligenceV2/Integrations/CofenseIntelligenceV2/Pipfile
  Packs/CofenseIntelligenceV2/Integrations/CofenseIntelligenceV2/Pipfile.lock
  Packs/CofenseIntelligenceV2/Integrations/CofenseIntelligenceV2/README.md
  Packs/CofenseIntelligenceV2/Integrations/CofenseIntelligenceV2/command_examples.txt
  Packs/CofenseIntelligenceV2/Integrations/CofenseIntelligenceV2/test_data/test_extracted_string.json
  Packs/CofenseIntelligenceV2/Integrations/CofenseIntelligenceV2/test_data/test_search_email.json
  Packs/CofenseIntelligenceV2/Integrations/CofenseIntelligenceV2/test_data/test_search_file.json
  Packs/CofenseIntelligenceV2/Integrations/CofenseIntelligenceV2/test_data/test_search_ip.json
  Packs/CofenseIntelligenceV2/Integrations/CofenseIntelligenceV2/test_data/test_search_url.json
  Packs/CofenseIntelligenceV2/Integrations/CofenseIntelligenceV2/test_data/test_threats.json
  Packs/CofenseIntelligenceV2/README.md
  Packs/CofenseIntelligenceV2/TestPlaybooks/CofenseIntelligenceV2Test.yml
  Packs/CofenseIntelligenceV2/pack_metadata.json
Labels: docs-approved

#13503 Incident blank & duplicate issue resolved
  Packs/Gurucul/Classifiers/classifier-GraCase_5_9_9.json
  Packs/Gurucul/Classifiers/classifier-mapper-Gurucul-GRACases.json
  Packs/Gurucul/IncidentFields/incidentfield-Gra_Anomalies.json
  Packs/Gurucul/IncidentFields/incidentfield-Gra_Anomaly_Name.json
  Packs/Gurucul/IncidentFields/incidentfield-Gra_Anomaly_Resource_Name.json
  Packs/Gurucul/IncidentFields/incidentfield-Gra_Anomaly_Risk_Score.json
  Packs/Gurucul/IncidentFields/incidentfield-Gra_Anomaly_Status.json
  Packs/Gurucul/IncidentFields/incidentfield-Gra_Assignee.json
  Packs/Gurucul/IncidentFields/incidentfield-Gra_Assignee_Type.json
  Packs/Gurucul/IncidentFields/incidentfield-Gra_Case_Status.json
  Packs/Gurucul/IncidentFields/incidentfield-Gra_Risk_Accepted_Date.json
  Packs/Gurucul/Integrations/GuruculGRA/GuruculGRA.py
  Packs/Gurucul/Integrations/GuruculGRA/GuruculGRA.yml
  Packs/Gurucul/Integrations/GuruculGRA/README.md
  Packs/Gurucul/Integrations/GuruculGRA/test_data/gra-cases.json
  Packs/Gurucul/Playbooks/playbook-GraCase.yml
  Packs/Gurucul/ReleaseNotes/1_0_1.md
  Packs/Gurucul/ReleaseNotes/1_1_1.md
  Packs/Gurucul/doc_files/GraCases.png
  Packs/Gurucul/pack_metadata.json
Labels: Contribution, Contribution Form Filled, Partner, docs-approved

#13664 added install sdk from ref
  .circleci/config.yml
Labels: docs-approved

#13638 filter out away users when picking random user
  Packs/CommonScripts/ReleaseNotes/1_4_0.md
  Packs/CommonScripts/Scripts/script-AssignAnalystToIncident.yml
  Packs/CommonScripts/pack_metadata.json
Labels: docs-approved, release-notes-only

#13604 change the skipunavailable to true
  Packs/Phishing/Playbooks/Phishing_-_Core.yml
  Packs/Phishing/ReleaseNotes/2_2_7.md
  Packs/Phishing/pack_metadata.json
Labels: docs-approved, release-notes-only

#13665 removing unnecessary section in test data
  Packs/CofenseIntelligenceV2/Integrations/CofenseIntelligenceV2/test_data/test_threats.json
Labels: docs-approved

#13651 Upload-Flow installation bug fix
  Tests/Marketplace/configure_and_install_packs.py
  Tests/Marketplace/install_packs.sh
  Tests/Marketplace/marketplace_constants.py
  Tests/Marketplace/marketplace_services.py
  Tests/Marketplace/search_and_install_packs.py
  Tests/configure_and_test_integration_instances.py
  Utils/gitlab_triggers/trigger_upload_flow_build.sh
Labels: docs-approved

#13669 Revert "added to commands http GitHub error message when applicable"
  Packs/GitHub/Integrations/GitHub/GitHub.py
  Packs/GitHub/ReleaseNotes/1_3_1.md
  Packs/GitHub/pack_metadata.json
Labels: docs-approved

#13666 fixed xsoar linter errors
  Packs/CommonScripts/ReleaseNotes/1_4_1.md
  Packs/CommonScripts/Scripts/CompareIncidentsLabels/CompareIncidentsLabels.yml
  Packs/CommonScripts/Scripts/CopyContextToField/CopyContextToField.yml
  Packs/CommonScripts/Scripts/GetDuplicatesMlv2/GetDuplicatesMlv2.yml
  Packs/CommonScripts/TestPlaybooks/playbook-ComapreIncidentsLabels.yml
  Packs/CommonScripts/pack_metadata.json
Labels: docs-approved

#12851 Slack V3 Phase 1
  Packs/Slack/.secrets-ignore
  Packs/Slack/Integrations/SlackV3/Pipfile
  Packs/Slack/Integrations/SlackV3/Pipfile.lock
  Packs/Slack/Integrations/SlackV3/README.md
  Packs/Slack/Integrations/SlackV3/SlackV3.py
  Packs/Slack/Integrations/SlackV3/SlackV3.yml
  Packs/Slack/Integrations/SlackV3/SlackV3_description.md
  Packs/Slack/Integrations/SlackV3/SlackV3_image.png
  Packs/Slack/Integrations/SlackV3/SlackV3_test.py
  Packs/Slack/Integrations/SlackV3/command_example.txt
  Packs/Slack/Integrations/SlackV3/test_data/conversations.txt
  Packs/Slack/Integrations/SlackV3/test_data/payload.txt
  Packs/Slack/Integrations/SlackV3/test_data/users.txt
  Packs/Slack/ReleaseNotes/2_0_0.md
  Packs/Slack/TestPlaybooks/playbook-SlackV3_TestPlaybook.yml
  Packs/Slack/pack_metadata.json
  Tests/conf.json
Labels: docs-approved

#13672 [Test] Fix AWS - EC2 credentials
  Tests/conf.json
Labels: docs-approved

#13671 [Bug] Expand GitHub error message
  Packs/GitHub/Integrations/GitHub/GitHub.py
  Packs/GitHub/ReleaseNotes/1_3_1.md
  Packs/GitHub/pack_metadata.json
Labels: bug, docs-approved, release-notes-only

#13675 added to ignore
  Packs/LogRhythmRest/.secrets-ignore
Labels: docs-approved

#13419 Phishing campaign ux fix
  Packs/Campaign/ReleaseNotes/2_0_8.md
  Packs/Campaign/Scripts/FindEmailCampaign/FindEmailCampaign.py
  Packs/Campaign/Scripts/FindEmailCampaign/FindEmailCampaign.yml
  Packs/Campaign/Scripts/GetCampaignDuration/GetCampaignDuration.py
  Packs/Campaign/Scripts/GetCampaignDuration/GetCampaignDuration.yml
  Packs/Campaign/Scripts/GetCampaignDuration/GetCampaignDuration_test.py
  Packs/Campaign/pack_metadata.json
  Packs/CommonTypes/IncidentFields/incidentfield-EmailCampaignSnippets.json
  Packs/CommonTypes/ReleaseNotes/3_1_3.md
  Packs/CommonTypes/ReleaseNotes/3_1_6.md
  Packs/CommonTypes/pack_metadata.json
Labels: docs-approved

#13195 Add microsoft cas new command
  Packs/MicrosoftCloudAppSecurity/.secrets-ignore
  Packs/MicrosoftCloudAppSecurity/Integrations/MicrosoftCloudAppSecurity/MicrosoftCloudAppSecurity.py
  Packs/MicrosoftCloudAppSecurity/Integrations/MicrosoftCloudAppSecurity/MicrosoftCloudAppSecurity.yml
  Packs/MicrosoftCloudAppSecurity/Integrations/MicrosoftCloudAppSecurity/MicrosoftCloudAppSecurity_test.py
  Packs/MicrosoftCloudAppSecurity/Integrations/MicrosoftCloudAppSecurity/README.md
  Packs/MicrosoftCloudAppSecurity/Integrations/MicrosoftCloudAppSecurity/commands.txt
  Packs/MicrosoftCloudAppSecurity/Integrations/MicrosoftCloudAppSecurity/test_data.json
  Packs/MicrosoftCloudAppSecurity/Integrations/MicrosoftCloudAppSecurity/test_data/test_data.json
  Packs/MicrosoftCloudAppSecurity/ReleaseNotes/1_0_20.md
  Packs/MicrosoftCloudAppSecurity/TestPlaybooks/MicrosoftCloudAppSecurity-Test.yml
  Packs/MicrosoftCloudAppSecurity/pack_metadata.json
Labels: docs-approved

#13680 Xpanse fix playbook doc
  Packs/ExpanseV2/Playbooks/playbook-Xpanse_Incident_Handling_-_Generic_README.md
  Packs/ExpanseV2/ReleaseNotes/1_7_2.md
  Packs/ExpanseV2/pack_metadata.json
Labels: docs-approved

#13684 update AD Query docs
  Packs/Active_Directory_Query/Integrations/Active_Directory_Query/README.md
Labels: docs-approved

#13670 Image OCR - add languages, update DO, refactor code, add UT
  Packs/ImageOCR/Integrations/ImageOCR/ImageOCR.py
  Packs/ImageOCR/Integrations/ImageOCR/ImageOCR.yml
  Packs/ImageOCR/Integrations/ImageOCR/ImageOCR_test.py
  Packs/ImageOCR/README.md
  Packs/ImageOCR/ReleaseNotes/1_1_0.md
  Packs/ImageOCR/pack_metadata.json
Labels: docs-approved

#13562 Add dockerimage7
  Packs/CommonScripts/ReleaseNotes/1_4_2.md
  Packs/CommonScripts/Scripts/CalculateTimeDifference/CalculateTimeDifference.yml
  Packs/CommonScripts/Scripts/CompareIncidentsLabels/CompareIncidentsLabels.yml
  Packs/CommonScripts/Scripts/ConvertToSingleElementArray/ConvertToSingleElementArray.yml
  Packs/CommonScripts/Scripts/CopyContextToField/CopyContextToField.yml
  Packs/CommonScripts/Scripts/DT/DT.yml
  Packs/CommonScripts/Scripts/DumpJSON/DumpJSON.yml
  Packs/CommonScripts/Scripts/ExtractIndicatorsFromTextFile/ExtractIndicatorsFromTextFile.yml
  Packs/CommonScripts/Scripts/FileToBase64List/FileToBase64List.yml
  Packs/CommonScripts/Scripts/GetDockerImageLatestTag/GetDockerImageLatestTag.yml
  Packs/CommonScripts/Scripts/GetIndicatorDBotScore/GetIndicatorDBotScore.yml
  Packs/CommonScripts/Scripts/HTTPListRedirects/HTTPListRedirects.yml
  Packs/CommonScripts/Scripts/InRange/InRange.yml
  Packs/CommonScripts/Scripts/PortListenCheck/PortListenCheck.yml
  Packs/CommonScripts/Scripts/ProductJoin/ProductJoin.yml
  Packs/CommonScripts/Scripts/ReadFile/ReadFile.yml
  Packs/CommonScripts/Scripts/RepopulateFiles/RepopulateFiles.yml
  Packs/CommonScripts/Scripts/script-GetStringsDistance.yml
  Packs/CommonScripts/pack_metadata.json
Labels: docs-approved

#13687 Add dockerimage5
  Packs/qualys/Playbooks/playbook-Launch_And_Fetch_Compliance_Policy_Report_-_Qualys.yml
  Packs/qualys/Playbooks/playbook-Launch_And_Fetch_Compliance_Report_-_Qualys.yml
  Packs/qualys/Playbooks/playbook-Launch_And_Fetch_Host_Based_Findings_Report_-_Qualys.yml
  Packs/qualys/Playbooks/playbook-Launch_And_Fetch_Map_Report_-_Qualys.yml
  Packs/qualys/Playbooks/playbook-Launch_And_Fetch_PC_Scan_-_Qualys.yml
  Packs/qualys/Playbooks/playbook-Launch_And_Fetch_Patch_Report_-_Qualys.yml
  Packs/qualys/Playbooks/playbook-Launch_And_Fetch_Remediation_Report_-_Qualys.yml
  Packs/qualys/Playbooks/playbook-Launch_And_Fetch_Scan_Based_Findings_Report_-_Qualys.yml
  Packs/qualys/Playbooks/playbook-Launch_And_Fetch_Scheduled_Report_-_Qualys.yml
  Packs/qualys/Playbooks/playbook-Launch_And_Fetch_VM_Scan_-_Qualys.yml
  Packs/qualys/Playbooks/playbook-Vulnerability_Management_-_Qualys_(Job)_-_V2.yml
  Packs/qualys/ReleaseNotes/1_0_7.md
  Packs/qualys/pack_metadata.json
  TestPlaybooks/NonCircleTests/Deprecated/playbook-Qualys-Test.yml
  Tests/conf.json
Labels: docs-approved

#13677 add docker image8
  Packs/CommonScripts/ReleaseNotes/1_4_3.md
  Packs/CommonScripts/Scripts/FilterByList/FilterByList.yml
  Packs/CommonScripts/Scripts/IdentifyAttachedEmail/IdentifyAttachedEmail.yml
  Packs/CommonScripts/Scripts/JSONtoCSV/JSONtoCSV.yml
  Packs/CommonScripts/Scripts/ParseCSV/ParseCSV.yml
  Packs/CommonScripts/Scripts/script-Cut.yml
  Packs/CommonScripts/Scripts/script-EncodeToAscii.yml
  Packs/CommonScripts/Scripts/script-ResolveShortenedURL.yml
  Packs/CommonScripts/Scripts/script-ReverseList.yml
  Packs/CommonScripts/pack_metadata.json
Labels: docs-approved

#13690 Print Nightmare Enhancement
  Packs/MajorBreachesInvestigationandResponse/.pack-ignore
  Packs/MajorBreachesInvestigationandResponse/Playbooks/playbook-CVE-2021-1675_-_PrintNightmare.yml
  Packs/MajorBreachesInvestigationandResponse/Playbooks/playbook-CVE-2021-1675_-_PrintNightmare_README.md
  Packs/MajorBreachesInvestigationandResponse/README.md
  Packs/MajorBreachesInvestigationandResponse/ReleaseNotes/1_6_15.md
  Packs/MajorBreachesInvestigationandResponse/doc_files/CVE-2021-1675_-_PrintNightmare.png
  Packs/MajorBreachesInvestigationandResponse/pack_metadata.json
Labels: docs-approved

#13619 Add new command cylance-protect-get-device-by-hostname
  Packs/Cylance_Protect/Integrations/Cylance_Protect_v2/Cylance_Protect_v2.py
  Packs/Cylance_Protect/Integrations/Cylance_Protect_v2/Cylance_Protect_v2.yml
  Packs/Cylance_Protect/Integrations/Cylance_Protect_v2/README.md
  Packs/Cylance_Protect/ReleaseNotes/1_0_7.md
  Packs/Cylance_Protect/TestPlaybooks/Cylance_Protect_v2_Test.yml
  Packs/Cylance_Protect/pack_metadata.json
Labels: Contribution, docs-approved

#13271 Modifying old RN changes the release time of latest version
  Tests/Marketplace/Tests/marketplace_services_test.py
  Tests/Marketplace/marketplace_constants.py
  Tests/Marketplace/marketplace_services.py
Labels: docs-approved

#13674 Update Circle Nightly to only Run Validations and Lint & Unit Tests
  .circleci/config.yml
  Utils/trigger_content_nightly_build.sh
  Utils/trigger_nightly_sdk_build.sh
Labels: docs-approved

#13701 circleci/config.yml - Fix condition
  .circleci/config.yml
Labels: docs-approved

#13694 Add dockerimage11
  Packs/CommonScripts/ReleaseNotes/1_4_4.md
  Packs/CommonScripts/Scripts/IsInternalHostName/IsInternalHostName.yml
  Packs/CommonScripts/Scripts/PopulateCriticalAssets/PopulateCriticalAssets.yml
  Packs/CommonScripts/Scripts/PortListenCheck/PortListenCheck.yml
  Packs/CommonScripts/Scripts/ProductJoin/ProductJoin.yml
  Packs/CommonScripts/Scripts/ReadFile/ReadFile.yml
  Packs/CommonScripts/Scripts/RepopulateFiles/RepopulateFiles.yml
  Packs/CommonScripts/Scripts/SetByIncidentId/SetByIncidentId.yml
  Packs/CommonScripts/Scripts/SetIfEmpty/SetIfEmpty.yml
  Packs/CommonScripts/Scripts/StopTimeToAssignOnOwnerChange/StopTimeToAssignOnOwnerChange.yml
  Packs/CommonScripts/Scripts/StripChar/StripChar.yml
  Packs/CommonScripts/pack_metadata.json
Labels: docs-approved

#13706 [Test] Google PubSub increase test timeout
  Tests/conf.json
Labels: docs-approved

#13686 Add dockerimage9
  Packs/CommonScripts/ReleaseNotes/1_4_5.md
  Packs/CommonScripts/Scripts/ParseEmailFiles/ParseEmailFiles.yml
  Packs/CommonScripts/Scripts/URLSSLVerification/URLSSLVerification.yml
  Packs/CommonScripts/pack_metadata.json
Labels: docs-approved

#13707 Palo Alto Networks PAN-OS - Fixed an issue where object with tag *None*
  Packs/PAN-OS/Integrations/Panorama/Panorama.py
  Packs/PAN-OS/Integrations/Panorama/Panorama.yml
  Packs/PAN-OS/Integrations/Panorama/Panorama_test.py
  Packs/PAN-OS/ReleaseNotes/1_6_22.md
  Packs/PAN-OS/pack_metadata.json
Labels: bug, docs-approved, release-notes-only

#13711 Print nightmare enhancement3
  Packs/CortexXDR/Playbooks/playbook-Cortex_XDR_-_PrintNightmare_Detection_and_Response.yml
  Packs/CortexXDR/Playbooks/playbook-Cortex_XDR_-_PrintNightmare_Detection_and_Response_README.md
  Packs/CortexXDR/ReleaseNotes/3_0_19.md
  Packs/CortexXDR/doc_files/Cortex_XDR_-_PrintNightmare_Detection_and_Response.png
  Packs/CortexXDR/pack_metadata.json
  Packs/MajorBreachesInvestigationandResponse/Playbooks/playbook-CVE-2021-1675_-_PrintNightmare.yml
  Packs/MajorBreachesInvestigationandResponse/Playbooks/playbook-CVE-2021-1675_-_PrintNightmare_README.md
  Packs/MajorBreachesInvestigationandResponse/ReleaseNotes/1_6_16.md
  Packs/MajorBreachesInvestigationandResponse/doc_files/CVE-2021-1675_-_PrintNightmare.png
  Packs/MajorBreachesInvestigationandResponse/pack_metadata.json
Labels: docs-approved

#13718 fixing sdk nightly
  .circleci/config.yml
  Tests/scripts/sdk_nightly_change_json_file_fields.py
Labels: docs-approved

#13719 ParseEmailFiles - added multipart/mixed format
  Packs/CommonScripts/ReleaseNotes/1_4_6.md
  Packs/CommonScripts/Scripts/ParseEmailFiles/ParseEmailFiles.py
  Packs/CommonScripts/Scripts/ParseEmailFiles/ParseEmailFiles.yml
  Packs/CommonScripts/Scripts/ParseEmailFiles/ParseEmailFiles_test.py
  Packs/CommonScripts/Scripts/ParseEmailFiles/test_data/multipart_mixed_format.p7m
  Packs/CommonScripts/pack_metadata.json
Labels: bug, docs-approved, release-notes-only

#13716 fix json chars obfuscation in debug-mode
  Packs/Base/ReleaseNotes/1_13_3.md
  Packs/Base/Scripts/CommonServerPython/CommonServerPython.py
  Packs/Base/Scripts/CommonServerPython/CommonServerPython_test.py
  Packs/Base/pack_metadata.json
Labels: docs-approved

#13724 EWSv2: timezone fix
  Packs/EWS/Integrations/EWSv2/EWSv2.yml
  Packs/EWS/Integrations/EWSv2/EWSv2_test.py
  Packs/EWS/ReleaseNotes/1_8_27.md
  Packs/EWS/pack_metadata.json
Labels: docs-approved

#13725 changing support to partner
  Packs/CovalenceForSecurityProviders/pack_metadata.json
  Packs/CovalenceManagedSecurity/pack_metadata.json
Labels: docs-approved

#13695 Remove typo in version
  Packs/Cofense-Intelligence/Integrations/integration-Cofense-Intelligence.yml
  Packs/Cofense-Intelligence/pack_metadata.json
  Packs/CofenseIntelligenceV2/README.md
Labels: docs-approved

#13726 fixing sdk nightly on gitlab
  .gitlab/ci/sdk-nightly.yml
Labels: docs-approved
