Repository demisto/content, pull requests merged in 2021-06, with the labels that each got.

#12926 Thinkst canary test faliure fix
  Packs/ThinkstCanary/Integrations/ThinkstCanary/ThinkstCanary.py
  Packs/ThinkstCanary/Integrations/ThinkstCanary/ThinkstCanary_test.py
  Packs/ThinkstCanary/ReleaseNotes/1_0_3.md
  Packs/ThinkstCanary/pack_metadata.json
  Tests/conf.json
Labels: docs-approved, release-notes-only

#12919 Slack notify as child pipeline
  .gitlab/ci/bucket-upload.yml
  .gitlab/ci/global.yml
  .gitlab/ci/instance-test.yml
  .gitlab/ci/on-push.yml
  .gitlab/ci/sdk-nightly.yml
  .gitlab/ci/slack-notify.yml
  Tests/scripts/gitlab_slack_notifier.py
Labels: docs-approved

#12933 Fixed naming to correspond to convention
  Packs/Base/Scripts/CommonServerPython/CommonServerPython.py
Labels: docs-approved

#12944 Popular News - Improved parsing for Krebs on Security
  Packs/PopularCybersecurityNews/Integrations/PopularNews/PopularNews.py
  Packs/PopularCybersecurityNews/ReleaseNotes/1_0_2.md
  Packs/PopularCybersecurityNews/pack_metadata.json
Labels: docs-approved

#12790 Logpoint search api
  Packs/LogPoint_SIEM_Integration/Integrations/LogPoint_SIEM_Integration/LogPoint_SIEM_Integration.py
  Packs/LogPoint_SIEM_Integration/Integrations/LogPoint_SIEM_Integration/LogPoint_SIEM_Integration.yml
  Packs/LogPoint_SIEM_Integration/Integrations/LogPoint_SIEM_Integration/LogPoint_SIEM_Integration_test.py
  Packs/LogPoint_SIEM_Integration/Integrations/LogPoint_SIEM_Integration/README.md
  Packs/LogPoint_SIEM_Integration/Integrations/LogPoint_SIEM_Integration/command_examples.txt
  Packs/LogPoint_SIEM_Integration/Integrations/LogPoint_SIEM_Integration/test_data/sample_get_devices_response.json
  Packs/LogPoint_SIEM_Integration/Integrations/LogPoint_SIEM_Integration/test_data/sample_get_livesearches_response.json
  Packs/LogPoint_SIEM_Integration/Integrations/LogPoint_SIEM_Integration/test_data/sample_get_logpoints_response.json
  Packs/LogPoint_SIEM_Integration/Integrations/LogPoint_SIEM_Integration/test_data/sample_get_repos_response.json
  Packs/LogPoint_SIEM_Integration/Integrations/LogPoint_SIEM_Integration/test_data/sample_get_searchid_response.json
  Packs/LogPoint_SIEM_Integration/Integrations/LogPoint_SIEM_Integration/test_data/sample_get_users_preference_response.json
  Packs/LogPoint_SIEM_Integration/Integrations/LogPoint_SIEM_Integration/test_data/sample_search_logs_response.json
  Packs/LogPoint_SIEM_Integration/README.md
  Packs/LogPoint_SIEM_Integration/ReleaseNotes/1_2_0.md
  Packs/LogPoint_SIEM_Integration/TestPlaybooks/LogPoint_SIEM_Integration-Test_Playbook_3.yml
  Packs/LogPoint_SIEM_Integration/pack_metadata.json
Labels: Contribution, Contribution Form Filled, Partner

#11492 first version of hostio integration
  Packs/HostIo/.pack-ignore
  Packs/HostIo/.secrets-ignore
  Packs/HostIo/Integrations/HostIo/HostIo.py
  Packs/HostIo/Integrations/HostIo/HostIo.yml
  Packs/HostIo/Integrations/HostIo/HostIo_description.md
  Packs/HostIo/Integrations/HostIo/HostIo_image.png
  Packs/HostIo/Integrations/HostIo/HostIo_test.py
  Packs/HostIo/Integrations/HostIo/Pipfile
  Packs/HostIo/Integrations/HostIo/Pipfile.lock
  Packs/HostIo/Integrations/HostIo/README.md
  Packs/HostIo/Integrations/HostIo/command_examples
  Packs/HostIo/Integrations/HostIo/test_data/domain.json
  Packs/HostIo/Integrations/HostIo/test_data/search.json
  Packs/HostIo/README.md
  Packs/HostIo/TestPlaybooks/Playbook_Hostio_Test.yml
  Packs/HostIo/doc_files/README.md
  Packs/HostIo/pack_metadata.json
  Tests/conf.json
Labels: docs-approved

#12962 Removing space from field name
  Packs/CommonTypes/IncidentFields/incidentfield-Similar_incidents_Dbot.json
  Packs/CommonTypes/ReleaseNotes/3_0_0.md
  Packs/CommonTypes/ReleaseNotes/3_0_1.md
  Packs/CommonTypes/pack_metadata.json
Labels: docs-approved

#12958 Phishtank v2 TPB - into skipped
  Tests/conf.json
Labels: docs-approved

#12488 Qradar v2 add try except
  Packs/QRadar/Integrations/QRadar_v2/QRadar_v2.py
  Packs/QRadar/Integrations/QRadar_v2/QRadar_v2.yml
  Packs/QRadar/ReleaseNotes/2_0_9.md
  Packs/QRadar/Scripts/QRadarFetchedEventsSum/QRadarFetchedEventsSum.yml
  Packs/QRadar/Scripts/QRadarMagnitude/QRadarMagnitude.yml
  Packs/QRadar/Scripts/QRadarPrintAssets/QRadarPrintAssets.yml
  Packs/QRadar/Scripts/QRadarPrintEvents/QRadarPrintEvents.yml
  Packs/QRadar/pack_metadata.json
Labels: bug, docs-approved, release-notes-only

#12957 Fix date format
  Packs/Cymulate/Integrations/Cymulate_v2/Cymulate_v2.py
  Packs/Cymulate/Integrations/Cymulate_v2/Cymulate_v2.yml
  Packs/Cymulate/ReleaseNotes/2_0_3.md
  Packs/Cymulate/pack_metadata.json
Labels: Contribution, Contribution Form Filled, docs-approved

#12752 AWS- IAM add aws api module
  Packs/AWS-IAM/Integrations/AWS-IAM/AWS-IAM.py
  Packs/AWS-IAM/Integrations/AWS-IAM/AWS-IAM.yml
  Packs/AWS-IAM/Integrations/AWS-IAM/README.md
  Packs/AWS-IAM/ReleaseNotes/1_1_0.md
  Packs/AWS-IAM/pack_metadata.json
Labels: docs-approved, release-notes-only

#12972 fix rn - threat crowd
  Packs/Threat_Crowd/ReleaseNotes/2_0_1.md
Labels: docs-approved

#12968 Added the devEmail addresses and tags
  Packs/ReversingLabs_A1000/pack_metadata.json
  Packs/ReversingLabs_Titanium_Cloud/pack_metadata.json
Labels: Contribution, Contribution Form Filled, docs-approved

#12971 Replace Demisto to Cortex XSOAR
  Packs/AWS-EC2/.pack-ignore
  Packs/AWS_DynamoDB/.pack-ignore
  Packs/Active_Directory_Query/.pack-ignore
  Packs/ApiModules/.pack-ignore
  Packs/Attlasian/.pack-ignore
  Packs/AzureCompute/.pack-ignore
  Packs/AzureSecurityCenter/.pack-ignore
  Packs/Base/.pack-ignore
  Packs/BluecatAddressManager/.pack-ignore
  Packs/BruteForce/.pack-ignore
  Packs/Code42/.pack-ignore
  Packs/CommonPlaybooks/.pack-ignore
  Packs/CommonScripts/.pack-ignore
  Packs/CommonScripts/Scripts/AddDBotScoreToContext/README.md
  Packs/CommonScripts/Scripts/ExtractEmailFormatting/README.md
  Packs/CommonScripts/Scripts/GetIndicatorDBotScoreFromCache/README.md
  Packs/Confluera/Scripts/ConflueraDetectionsCount/README.md
  Packs/Confluera/Scripts/ConflueraDetectionsData/README.md
  Packs/Confluera/Scripts/ConflueraDetectionsDataWarroom/README.md
  Packs/Confluera/Scripts/ConflueraDetectionsSummary/README.md
  Packs/Confluera/Scripts/ConflueraDetectionsSummaryWarroom/README.md
  Packs/Confluera/Scripts/ConflueraProgressionsCount/README.md
  Packs/Confluera/Scripts/ConflueraProgressionsData/README.md
  Packs/Confluera/Scripts/ConflueraProgressionsDataWarroom/README.md
  Packs/Confluera/Scripts/IqHubLog/README.md
  Packs/Coralogix/.pack-ignore
  Packs/CortexDataLake/.pack-ignore
  Packs/DemistoLocking/.pack-ignore
  Packs/DeprecatedContent/.pack-ignore
  Packs/DevSecOps/Integrations/GitLab/README.md
  Packs/Devo/.pack-ignore
  Packs/EDL/.pack-ignore
  Packs/ExtFilter/.pack-ignore
  Packs/FeedMitreAttackv2/Scripts/MITREIndicatorsByOpenIncidentsv2/README.md
  Packs/FeedUnit42v2/Integrations/FeedUnit42v2/README.md
  Packs/Gmail/.pack-ignore
  Packs/GmailSingleUser/.pack-ignore
  Packs/Lokpath_Keylight/.pack-ignore
  Packs/MajorBreachesInvestigationandResponse/Scripts/RapidBreachResponseParseBlog/README.md
  Packs/Malware/.pack-ignore
  Packs/MicrosoftAdvancedThreatAnalytics/Integrations/MicrosoftAdvancedThreatAnalytics/README.md
  Packs/NetscoutArborSightline/.pack-ignore
  Packs/OpenCTI/.pack-ignore
  Packs/PagerDuty/.pack-ignore
  Packs/SplunkPy/.pack-ignore
  Packs/ThreatGrid/.pack-ignore
  Packs/XSOAR-SimpleDevToProd/.pack-ignore
Labels: docs-approved

#12011 Create incident field for cve list
  Packs/FindCVE/.pack-ignore
  Packs/FindCVE/.secrets-ignore
  Packs/FindCVE/CHANGELOG.md
  Packs/FindCVE/IncidentFields/incidentfield-cvelist.json
  Packs/FindCVE/IncidentFields/incidentfield-incident_target.json
  Packs/FindCVE/IncidentTypes/customIncidentTypes.json
  Packs/FindCVE/Layouts/layout-details-Panorama_Threat_Coverage.json
  Packs/FindCVE/Playbooks/NetOps_Panorama_coverage_by_CVE.yml
  Packs/FindCVE/README.md
  Packs/FindCVE/Scripts/PanoramaCVECoverage/CHANGELOG.md
  Packs/FindCVE/Scripts/PanoramaCVECoverage/PanoramaCVECoverage.py
  Packs/FindCVE/Scripts/PanoramaCVECoverage/PanoramaCVECoverage.yml
  Packs/FindCVE/Scripts/PanoramaCVECoverage/Pipfile
  Packs/FindCVE/Scripts/PanoramaCVECoverage/Pipfile.lock
  Packs/FindCVE/Scripts/PanoramaCVECoverage/README.md
  Packs/FindCVE/TestPlaybooks/PanoramaCVECoverage.yml
  Packs/FindCVE/pack_metadata.json
  Tests/conf.json
  package-lock.json
Labels: Contribution

#12932 fix get similar incidents query bug
  Packs/Base/ReleaseNotes/1_11_9.md
  Packs/Base/Scripts/FindSimilarIncidentsByText/FindSimilarIncidentsByText.py
  Packs/Base/Scripts/FindSimilarIncidentsByText/FindSimilarIncidentsByText.yml
  Packs/Base/Scripts/FindSimilarIncidentsByText/FindSimilarIncidentsByText_test.py
  Packs/Base/pack_metadata.json
Labels: bug, docs-approved, release-notes-only

#12965 Replace Demisto to Cortex XSOAR
  Packs/MinervaLabsAntiEvasionPlatform/Integrations/integration-MinervaLabsAntiEvasionPlatform.yml
  Packs/MinervaLabsAntiEvasionPlatform/Integrations/integration-MinervaLabsAntiEvasionPlatform_README.md
  Packs/MinervaLabsAntiEvasionPlatform/ReleaseNotes/1_0_2.md
  Packs/MinervaLabsAntiEvasionPlatform/pack_metadata.json
Labels: docs-approved, release-notes-only

#12964 Replace Demisto to Cortex XSOAR in Packetsled integration docs
  Packs/Packetsled/Integrations/integration-Packetsled.yml
  Packs/Packetsled/Integrations/integration-Packetsled_README.md
  Packs/Packetsled/ReleaseNotes/1_0_1.md
  Packs/Packetsled/pack_metadata.json
Labels: docs-approved, release-notes-only

#12982 Expanse v2 - fix expansecloudmanagementstatus field
  Packs/ExpanseV2/IncidentFields/incidentfield-Expanse_Cloud_Management_Status.json
Labels: docs-approved

#12985 Reorg and Tweaks for on-push GitLab Config File
  .gitlab/ci/on-push.yml
Labels: docs-approved

#12302 Freshdesk fetch incident bug fix
  Packs/FreshDesk/.secrets-ignore
  Packs/FreshDesk/Integrations/FreshDesk/FreshDesk.py
  Packs/FreshDesk/Integrations/FreshDesk/FreshDesk.yml
  Packs/FreshDesk/Integrations/FreshDesk/FreshDesk_test.py
  Packs/FreshDesk/Integrations/FreshDesk/test_data/first_page_incindents_respone.json
  Packs/FreshDesk/Integrations/FreshDesk/test_data/second_page_incidents_response.json
  Packs/FreshDesk/ReleaseNotes/1_0_3.md
  Packs/FreshDesk/pack_metadata.json
Labels: bug, docs-approved, release-notes-only

#12959 Skip TAXII test
  Tests/conf.json
Labels: docs-approved

#12980 Edl: ipv6 remove
  Packs/EDL/Integrations/EDL/EDL.py
  Packs/EDL/ReleaseNotes/2_0_3.md
  Packs/EDL/pack_metadata.json
Labels: docs-approved

#12993 checking if there email_api_key global var
  .github/workflows/check-contributor-pack.yml
Labels: docs-approved

#12928 threat exchange v2: readme fix broken links
  Packs/ThreatExchange/Integrations/ThreatExchangeV2/README.md
Labels: docs-approved

#12987 Content README: fix link
  README.md
Labels: docs-approved

#12986 sdk-release-1.3.9
  dev-requirements-py3.txt
Labels: docs-approved

#13002 unskip TPB
  Tests/conf.json
Labels: docs-approved

#12699 Update IOC layouts
  Packs/CommonTypes/Layouts/layoutscontainer-domain.json
  Packs/CommonTypes/Layouts/layoutscontainer-email.json
  Packs/CommonTypes/Layouts/layoutscontainer-ip.json
  Packs/CommonTypes/Layouts/layoutscontainer-unifiedFile.json
  Packs/CommonTypes/Layouts/layoutscontainer-url.json
  Packs/CommonTypes/ReleaseNotes/3_0_2.md
  Packs/CommonTypes/pack_metadata.json
Labels: docs-approved

#12272 Zscaler bug
  Packs/Zscaler/Integrations/Zscaler/Zscaler.py
  Packs/Zscaler/Integrations/Zscaler/test_data/results/get_categories_no_urls.json
  Packs/Zscaler/Integrations/Zscaler/test_data/results/remove_url.json
  Packs/Zscaler/ReleaseNotes/1_1_5.md
  Packs/Zscaler/pack_metadata.json
Labels: bug, docs-approved, release-notes-only

#12720 Linkshadow
  Packs/Linkshadow/.pack-ignore
  Packs/Linkshadow/.secrets-ignore
  Packs/Linkshadow/Integrations/Linkshadow/Linkshadow.py
  Packs/Linkshadow/Integrations/Linkshadow/Linkshadow.yml
  Packs/Linkshadow/Integrations/Linkshadow/Linkshadow_description.md
  Packs/Linkshadow/Integrations/Linkshadow/Linkshadow_image.png
  Packs/Linkshadow/Integrations/Linkshadow/Linkshadow_test.py
  Packs/Linkshadow/Integrations/Linkshadow/README.md
  Packs/Linkshadow/Integrations/Linkshadow/command_examples.txt
  Packs/Linkshadow/Integrations/Linkshadow/test_data/fetch_anomaly.json
  Packs/Linkshadow/Integrations/Linkshadow/test_data/fetch_incident.json
  Packs/Linkshadow/Integrations/Linkshadow/test_data/formatted_fetch_anomaly.json
  Packs/Linkshadow/Integrations/Linkshadow/test_data/formatted_fetch_incident.json
  Packs/Linkshadow/README.md
  Packs/Linkshadow/pack_metadata.json
Labels: Contribution, Contribution Form Filled, Partner, docs-approved, ready-for-instance-test

#13005 Fix rapid breach dependencies
  Packs/MajorBreachesInvestigationandResponse/Playbooks/playbook-CVE-2021-22893_-_Pulse_Connect_Secure_RCE.yml
  Packs/MajorBreachesInvestigationandResponse/Playbooks/playbook-Codecov_Breach_-_Bash_Uploader.yml
  Packs/MajorBreachesInvestigationandResponse/Playbooks/playbook-HAFNIUM_-_Exchange_0-day_exploits_5_5.yml
  Packs/MajorBreachesInvestigationandResponse/Playbooks/playbook-HAFNIUM_-_Exchange_0-day_exploits_6.yml
  Packs/MajorBreachesInvestigationandResponse/Playbooks/playbook-NOBELIUM_-_wide_scale_APT29_spear-phishing.yml
  Packs/MajorBreachesInvestigationandResponse/Playbooks/playbook-SolarStorm_and_SUNBURST_Hunting_and_Response_Playbook_5_9_9.yml
  Packs/MajorBreachesInvestigationandResponse/Playbooks/playbook-SolarStorm_and_SUNBURST_Hunting_and_Response_Playbook_6.yml
  Packs/MajorBreachesInvestigationandResponse/ReleaseNotes/1_6_6.md
  Packs/MajorBreachesInvestigationandResponse/pack_metadata.json
Labels: docs-approved

#12998 Updating OOB V2 version + stabilizing batch predictions
  Packs/Base/ReleaseNotes/1_12_0.md
  Packs/Base/Scripts/DBotPredictPhishingWords/DBotPredictPhishingWords.py
  Packs/Base/Scripts/DBotPredictPhishingWords/DBotPredictPhishingWords.yml
  Packs/Base/Scripts/DBotPreprocessTextData/DBotPreprocessTextData.py
  Packs/Base/Scripts/DBotPreprocessTextData/DBotPreprocessTextData.yml
  Packs/Base/Scripts/DBotPreprocessTextData/dbot_preprocess_text_data_test.py
  Packs/Base/pack_metadata.json
  Packs/ML/.secrets-ignore
  Packs/ML/ReleaseNotes/1_3_0.md
  Packs/ML/Scripts/DBotPredictIncidentsBatch/DBotPredictIncidentsBatch.py
  Packs/ML/Scripts/DBotPredictIncidentsBatch/DBotPredictIncidentsBatch.yml
  Packs/ML/Scripts/DBotPredictOutOfTheBoxV2/DBotPredictOutOfTheBoxV2.py
  Packs/ML/Scripts/DBotPredictOutOfTheBoxV2/DBotPredictOutOfTheBoxV2.yml
  Packs/ML/TestPlaybooks/playbook-VerifyOOBV2Predictions.yml
  Packs/ML/TestPlaybooks/script-CompareEnvPredictionsToExpectedPredictions.yml
  Packs/ML/TestPlaybooks/script-CreateIncidentsForEvaluateMLModllAtProduction.yml
  Packs/ML/TestPlaybooks/script-CreateIncidentsOutOfTheBoxV2.yml
  Packs/ML/pack_metadata.json
Labels: docs-approved

#12878 Add prepend/append to export-indicators service.
  Packs/ExportIndicators/Integrations/ExportIndicators/ExportIndicators.py
  Packs/ExportIndicators/Integrations/ExportIndicators/ExportIndicators.yml
  Packs/ExportIndicators/ReleaseNotes/1_0_7.md
  Packs/ExportIndicators/pack_metadata.json
Labels: Contribution, docs-approved

#12207 CommonServerPowerShell: Add usage of versioned Integration context
  Packs/Base/ReleaseNotes/1_12_1.md
  Packs/Base/Scripts/CommonServerPowerShell/CommonServerPowerShell.ps1
  Packs/Base/Scripts/CommonServerPowerShell/CommonServerPowerShell.yml
  Packs/Base/pack_metadata.json
  Packs/DeveloperTools/Integrations/XsoarPowershellTesting/XsoarPowershellTesting.ps1
  Packs/DeveloperTools/Integrations/XsoarPowershellTesting/XsoarPowershellTesting.yml
  Packs/DeveloperTools/ReleaseNotes/1_1_2.md
  Packs/DeveloperTools/TestPlaybooks/playbook-XsoarPowershellTesting-Test.yml
  Packs/DeveloperTools/pack_metadata.json
  Packs/EWS/Integrations/SecurityAndCompliance/SecurityAndCompliance.ps1
  Packs/EWS/ReleaseNotes/1_8_20.md
  Packs/EWS/pack_metadata.json
Labels: docs-approved, release-notes-only

#13021 CommonServerPython - added service_account to sensitive params
  Packs/Base/ReleaseNotes/1_12_2.md
  Packs/Base/Scripts/CommonServerPython/CommonServerPython.py
  Packs/Base/pack_metadata.json
Labels: docs-approved, release-notes-only

#12733 Bug/VMRay/Fixed: viewing all threat-indicators for a sampleID
  Packs/VMRay/Integrations/VMRay/VMRay.py
  Packs/VMRay/Integrations/VMRay/VMRay.yml
  Packs/VMRay/ReleaseNotes/1_0_2.md
  Packs/VMRay/pack_metadata.json
Labels: bug, docs-approved, release-notes-only

#13020 Proofpoint Threat Response - set first fetch param default value by or operator
  Packs/ProofpointThreatResponse/Integrations/ProofpointThreatResponse/ProofpointThreatResponse.py
  Packs/ProofpointThreatResponse/ReleaseNotes/1_0_4.md
  Packs/ProofpointThreatResponse/pack_metadata.json
Labels: docs-approved, release-notes-only

#12861 Fixed an issue that fetching incidents fails when the format of the t…
  Packs/McAfee_ESM/Integrations/McAfee_ESM_v2/McAfee_ESM_v2.py
  Packs/McAfee_ESM/Integrations/McAfee_ESM_v2/McAfee_ESM_v2.yml
  Packs/McAfee_ESM/Integrations/McAfee_ESM_v2/McAfee_ESM_v2_description.md
  Packs/McAfee_ESM/Integrations/McAfee_ESM_v2/Pipfile
  Packs/McAfee_ESM/Integrations/McAfee_ESM_v2/Pipfile.lock
  Packs/McAfee_ESM/ReleaseNotes/1_1_6.md
  Packs/McAfee_ESM/pack_metadata.json
Labels: Contribution, docs-approved, release-notes-only

#13000 VirusTotal - fix vt links for ip and domain
  Packs/VirusTotal/Integrations/integration-VirusTotal_5.5.yml
  Packs/VirusTotal/ReleaseNotes/2_1_1.md
  Packs/VirusTotal/pack_metadata.json
Labels: docs-approved, release-notes-only

#12950 Deprecate Original IPinfo
  Packs/ipinfo/Integrations/ipinfo/ipinfo.yml
  Packs/ipinfo/ReleaseNotes/2_0_3.md
  Packs/ipinfo/pack_metadata.json
Labels: docs-approved

#13026 Fixed unit test for release build
  Tests/scripts/infrastructure_tests/test_collect_tests_and_content_packs.py
Labels: docs-approved

#12940 Relationships table in quick view longer
  Packs/CommonTypes/Layouts/layoutscontainer-Campaign.json
  Packs/CommonTypes/Layouts/layoutscontainer-Course_of_Action.json
  Packs/CommonTypes/Layouts/layoutscontainer-Infrastructure.json
  Packs/CommonTypes/Layouts/layoutscontainer-Intrusion_Set.json
  Packs/CommonTypes/Layouts/layoutscontainer-STIX_Attack_Pattern.json
  Packs/CommonTypes/Layouts/layoutscontainer-STIX_Malware.json
  Packs/CommonTypes/Layouts/layoutscontainer-STIX_Report.json
  Packs/CommonTypes/Layouts/layoutscontainer-STIX_Threat_Actor.json
  Packs/CommonTypes/Layouts/layoutscontainer-STIX_Tool.json
  Packs/CommonTypes/ReleaseNotes/3_0_3.md
  Packs/CommonTypes/pack_metadata.json
Labels: docs-approved, release-notes-only

#12983 Find email campaign fields
  Packs/Campaign/ReleaseNotes/2_0_3.md
  Packs/Campaign/Scripts/FindEmailCampaign/FindEmailCampaign.py
  Packs/Campaign/Scripts/PerformActionOnCampaignIncidents/PerformActionOnCampaignIncidents.py
  Packs/Campaign/Scripts/PerformActionOnCampaignIncidents/PerformActionOnCampaignIncidents_test.py
  Packs/Campaign/pack_metadata.json
Labels: docs-approved

#12917 IPinfo (v1,v2) README files
  Packs/ipinfo/Integrations/ipinfo/README.md
  Packs/ipinfo/Integrations/ipinfo_v2/README.md
Labels: docs-approved

#13032 Change the names of some of the widgets we have in reports.
  Packs/CommonWidgets/ReleaseNotes/1_0_10.md
  Packs/CommonWidgets/Widgets/widget-IndicatorBadActivity.json
  Packs/CommonWidgets/Widgets/widget-IndicatorBadActivityType.json
  Packs/CommonWidgets/Widgets/widget-IndicatorManualNumber.json
  Packs/CommonWidgets/Widgets/widget-IndicatorManualUsers.json
  Packs/CommonWidgets/pack_metadata.json
Labels: docs-approved, release-notes-only

#12756 remock testplaybooks of wildfire integration
  Tests/conf.json
Labels: docs-approved

#12890 Bit sight adoption
  Packs/BitSight/Integrations/BitSightForSecurityPerformanceManagement/BitSightForSecurityPerformanceManagement_description.md
  Packs/BitSight/README.md
  Packs/BitSight/ReleaseNotes/1_0_3.md
  Packs/BitSight/pack_metadata.json
Labels: Contribution, Partner, docs-approved

#12966 Q radar none type from events limit error
  Packs/QRadar/Integrations/QRadar_v3/QRadar_v3.py
  Packs/QRadar/Integrations/QRadar_v3/QRadar_v3_test.py
  Packs/QRadar/ReleaseNotes/2_0_10.md
  Packs/QRadar/pack_metadata.json
Labels: docs-approved, release-notes-only

#13035 Replace Demisto to Cortex XSOAR
  Packs/RubrikPolaris/Scripts/RubrikCDMClusterConnectionState/README.md
  Packs/RubrikPolaris/Scripts/RubrikRadarFilesAdded/README.md
  Packs/RubrikPolaris/Scripts/RubrikRadarFilesDeleted/README.md
  Packs/RubrikPolaris/Scripts/RubrikRadarFilesModified/README.md
  Packs/RubrikPolaris/Scripts/RubrikSonarOpenAccessFiles/README.md
  Packs/RubrikPolaris/Scripts/RubrikSonarTotalHits/README.md
Labels: docs-approved

#13036 Falcon Intel - remove test
  Tests/conf.json
Labels: docs-approved

#13013 Improve Error handling and messaging of longRunning integrations
  Packs/EDL/Integrations/EDL/EDL.py
  Packs/EDL/ReleaseNotes/2_0_4.md
  Packs/EDL/pack_metadata.json
  Packs/ExportIndicators/Integrations/ExportIndicators/ExportIndicators.py
  Packs/ExportIndicators/ReleaseNotes/1_0_8.md
  Packs/ExportIndicators/pack_metadata.json
  Packs/TAXIIServer/Integrations/TAXIIServer/TAXIIServer.py
  Packs/TAXIIServer/Integrations/TAXIIServer/TAXIIServer.yml
  Packs/TAXIIServer/Integrations/TAXIIServer/TAXIIServer_description.md
  Packs/TAXIIServer/ReleaseNotes/1_0_7.md
  Packs/TAXIIServer/pack_metadata.json
Labels: docs-approved, release-notes-only

#12956 coverage changes
  .gitignore
Labels: docs-approved

#13017 Xpanse - Cloud resource fixes
  Packs/ExpanseV2/Integrations/ExpanseV2/ExpanseV2.py
  Packs/ExpanseV2/Integrations/ExpanseV2/ExpanseV2.yml
  Packs/ExpanseV2/Integrations/ExpanseV2/README.md
  Packs/ExpanseV2/ReleaseNotes/1_5_1.md
  Packs/ExpanseV2/Scripts/ExpanseRefreshIssueAssets/ExpanseRefreshIssueAssets.py
  Packs/ExpanseV2/Scripts/ExpanseRefreshIssueAssets/ExpanseRefreshIssueAssets.yml
  Packs/ExpanseV2/pack_metadata.json
Labels: Contribution, docs-approved

#12687 modified and new playbooks for TIM processing
  Packs/TIM_Processing/Playbooks/playbook-TIM_-_Process_Indicators_Against_Organizations_External_IP.yml
  Packs/TIM_Processing/Playbooks/playbook-TIM_-_Process_Indicators_Against_Organizations_External_IP_README.md
  Packs/TIM_Processing/Playbooks/playbook-TIM_-_Update_Indicators_Organizational_External_IP_Tag.yml
  Packs/TIM_Processing/Playbooks/playbook-TIM_-_Update_Indicators_Organizational_External_IP_Tag_README.md
  Packs/TIM_Processing/ReleaseNotes/1_1_7.md
  Packs/TIM_Processing/ReleaseNotes/1_1_8.md
  Packs/TIM_Processing/doc_files/TIM_-_Process_Indicators_Against_Organizations_External_IP_List.png
  Packs/TIM_Processing/doc_files/TIM_-_Update_Indicators_Organizational_External_IP_Tag.png
  Packs/TIM_Processing/pack_metadata.json
Labels: docs-approved

#13015 Update sane doc reports
  Packs/Base/ReleaseNotes/1_12_3.md
  Packs/Base/Scripts/SaneDocReportV2/SaneDocReportV2.yml
  Packs/Base/pack_metadata.json
Labels: docs-approved, release-notes-only

#12920 Compress Json Files - Public Repo
  Tests/Marketplace/upload_packs.py
  Tests/private_build/upload_packs_private.py
  Tests/scripts/prepare_content_packs_for_testing.sh
Labels: docs-approved

#12575 Deprecate Recorded Future v1
  Packs/Recorded_Future/Integrations/Recorded_Future/README.md
  Packs/Recorded_Future/Integrations/Recorded_Future/Recorded_Future.yml
  Packs/Recorded_Future/README.md
  Packs/Recorded_Future/ReleaseNotes/1_1_0.md
  Packs/Recorded_Future/pack_metadata.json
Labels: docs-approved

#11964 Netscout AED Integration
  Packs/NetscoutAED/.pack-ignore
  Packs/NetscoutAED/.secrets-ignore
  Packs/NetscoutAED/Integrations/NetscoutAED/NetscoutAED.py
  Packs/NetscoutAED/Integrations/NetscoutAED/NetscoutAED.yml
  Packs/NetscoutAED/Integrations/NetscoutAED/NetscoutAED_description.md
  Packs/NetscoutAED/Integrations/NetscoutAED/NetscoutAED_test.py
  Packs/NetscoutAED/Integrations/NetscoutAED/NetscoutArborEdgeDefence_image.png
  Packs/NetscoutAED/Integrations/NetscoutAED/Pipfile
  Packs/NetscoutAED/Integrations/NetscoutAED/Pipfile.lock
  Packs/NetscoutAED/Integrations/NetscoutAED/README.md
  Packs/NetscoutAED/Integrations/NetscoutAED/command_examples.txt
  Packs/NetscoutAED/Integrations/NetscoutAED/test_data/countries/added_inbound_blacklisted_countries_raw.json
  Packs/NetscoutAED/Integrations/NetscoutAED/test_data/countries/added_outbound_blacklisted_countries_raw.json
  Packs/NetscoutAED/Integrations/NetscoutAED/test_data/countries/inbound_blacklisted_countries_raw.json
  Packs/NetscoutAED/Integrations/NetscoutAED/test_data/countries/outbound_blacklisted_countries_raw.json
  Packs/NetscoutAED/Integrations/NetscoutAED/test_data/countries_codes/countries_code_raw.json
  Packs/NetscoutAED/Integrations/NetscoutAED/test_data/domains/added_inbound_blacklisted_domains_raw.json
  Packs/NetscoutAED/Integrations/NetscoutAED/test_data/domains/inbound_blacklisted_domains_raw.json
  Packs/NetscoutAED/Integrations/NetscoutAED/test_data/hosts/added_or_updated_inbound_blacklisted_hosts_raw.json
  Packs/NetscoutAED/Integrations/NetscoutAED/test_data/hosts/added_or_updated_inbound_whitelisted_hosts_raw.json
  Packs/NetscoutAED/Integrations/NetscoutAED/test_data/hosts/added_or_updated_outbound_blacklisted_hosts_raw.json
  Packs/NetscoutAED/Integrations/NetscoutAED/test_data/hosts/added_or_updated_outbound_whitelisted_hosts_raw.json
  Packs/NetscoutAED/Integrations/NetscoutAED/test_data/hosts/inbound_blacklisted_hosts_list_raw.json
  Packs/NetscoutAED/Integrations/NetscoutAED/test_data/hosts/inbound_whitelisted_hosts_list_raw.json
  Packs/NetscoutAED/Integrations/NetscoutAED/test_data/hosts/outbound_blacklisted_hosts_list_raw.json
  Packs/NetscoutAED/Integrations/NetscoutAED/test_data/hosts/outbound_whitelisted_hosts_list_raw.json
  Packs/NetscoutAED/Integrations/NetscoutAED/test_data/protection_groups/protection_groups_list_raw.json
  Packs/NetscoutAED/Integrations/NetscoutAED/test_data/protection_groups/protection_groups_update_raw.json
  Packs/NetscoutAED/Integrations/NetscoutAED/test_data/urls/added_inbound_blacklisted_urls_raw.json
  Packs/NetscoutAED/Integrations/NetscoutAED/test_data/urls/inbound_blacklisted_urls_raw.json
  Packs/NetscoutAED/README.md
  Packs/NetscoutAED/TestPlaybooks/NetscoutAED-Test.yml
  Packs/NetscoutAED/pack_metadata.json
  Tests/conf.json
Labels: docs-approved

#13022 AWS Security Hub - increase fetch time by 1 ms in case findings were fetched
  Packs/AWS-SecurityHub/Integrations/AWS_SecurityHub/AWS_SecurityHub.py
  Packs/AWS-SecurityHub/Integrations/AWS_SecurityHub/AWS_SecurityHub.yml
  Packs/AWS-SecurityHub/Integrations/AWS_SecurityHub/AWS_SecurityHub_test.py
  Packs/AWS-SecurityHub/ReleaseNotes/1_1_2.md
  Packs/AWS-SecurityHub/pack_metadata.json
Labels: docs-approved, release-notes-only

#13040 Change STIX layouts names
  Packs/CommonTypes/.pack-ignore
  Packs/CommonTypes/Layouts/layoutscontainer-STIX_Attack_Pattern.json
  Packs/CommonTypes/Layouts/layoutscontainer-STIX_Malware.json
  Packs/CommonTypes/Layouts/layoutscontainer-STIX_Report.json
  Packs/CommonTypes/Layouts/layoutscontainer-STIX_Threat_Actor.json
  Packs/CommonTypes/Layouts/layoutscontainer-STIX_Tool.json
  Packs/CommonTypes/ReleaseNotes/3_0_4.md
  Packs/CommonTypes/pack_metadata.json
Labels: docs-approved, release-notes-only

#13045 Removed id_set from private
  Tests/Marketplace/upload_packs.py
  Tests/private_build/upload_packs_private.py
  Tests/scripts/prepare_private_content_packs_for_testing.sh
Labels: docs-approved

#13049 Linkshadow: Image update
  Packs/Linkshadow/Integrations/Linkshadow/Linkshadow_image.png
  Packs/Linkshadow/ReleaseNotes/1_0_1.md
  Packs/Linkshadow/pack_metadata.json
Labels: docs-approved

#12901 ignored an error (pb110) for some files
  Packs/CortexXDR/.pack-ignore
Labels: docs-approved

#13047 Added the escapeColon argument
  Packs/EWS/ReleaseNotes/1_8_21.md
  Packs/EWS/Scripts/BuildEWSQuery/BuildEWSQuery.py
  Packs/EWS/Scripts/BuildEWSQuery/BuildEWSQuery.yml
  Packs/EWS/Scripts/BuildEWSQuery/Pipfile
  Packs/EWS/Scripts/BuildEWSQuery/Pipfile.lock
  Packs/EWS/Scripts/BuildEWSQuery/README.md
  Packs/EWS/Scripts/script-BuildEWSQuery.yml
  Packs/EWS/TestPlaybooks/playbook-BuildEWSQuery_Test.yml
  Packs/EWS/pack_metadata.json
Labels: docs-approved, release-notes-only

#12954 fix rundeck test playbook
  Packs/Rundeck/ReleaseNotes/1_0_3.md
  Packs/Rundeck/TestPlaybooks/Rundeck_test.yml
  Packs/Rundeck/pack_metadata.json
  Tests/conf.json
Labels: docs-approved

#13030 ArcSight Logger change status code in logout
  Packs/ArcSightLogger/Integrations/integration-ArcSightLogger.yml
  Packs/ArcSightLogger/ReleaseNotes/1_0_3.md
  Packs/ArcSightLogger/pack_metadata.json
Labels: docs-approved

#13038 add packs to core packs 6.2
  Tests/Marketplace/core_packs_list.json
Labels: docs-approved

#13074 Deprecated playbooks and scripts - fix spelling mistake
  Packs/CommonScripts/ReleaseNotes/1_3_55.md
  Packs/CommonScripts/Scripts/GetDuplicatesMlv2/GetDuplicatesMlv2.yml
  Packs/CommonScripts/pack_metadata.json
Labels: docs-approved

#13048 Netscout description fix
  Packs/NetscoutAED/Integrations/NetscoutAED/NetscoutAED.yml
  Packs/NetscoutAED/ReleaseNotes/1_0_2.md
  Packs/NetscoutAED/pack_metadata.json
Labels: docs-approved

#12953 Add current id to incidents list emailcampaign
  Packs/Campaign/ReleaseNotes/2_0_3.md
  Packs/Campaign/ReleaseNotes/2_0_4.md
  Packs/Campaign/Scripts/FindEmailCampaign/FindEmailCampaign.py
  Packs/Campaign/Scripts/FindEmailCampaign/FindEmailCampaign.yml
  Packs/Campaign/Scripts/FindEmailCampaign/FindEmailCampaign_test.py
  Packs/Campaign/pack_metadata.json
Labels: docs-approved, release-notes-only

#13066 update device code flow link
  Packs/Microsoft365Defender/Integrations/Microsoft365Defender/Microsoft365Defender_description.md
  Packs/Microsoft365Defender/ReleaseNotes/1_0_1.md
  Packs/Microsoft365Defender/pack_metadata.json
Labels: docs-approved

#13076 misp v2 - fix TPB
  Packs/MISP/TestPlaybooks/playbook-MISP_V2-Test.yml
Labels: docs-approved

#13037 Adding new widgets and dashboards
  Packs/CommonDashboards/Dashboards/dashboard-CostOptimizationInstances.json
  Packs/CommonDashboards/Dashboards/dashboard-CostOptimizationPlaybooks.json
  Packs/CommonDashboards/Dashboards/dashboard-TroubleshootingInstances.json
  Packs/CommonDashboards/Dashboards/dashboard-TroubleshootingPlaybooks.json
  Packs/CommonDashboards/ReleaseNotes/1_1_0.md
  Packs/CommonDashboards/pack_metadata.json
  Packs/CommonWidgets/ReleaseNotes/1_1_0.md
  Packs/CommonWidgets/Widgets/widget-AverageRuntimeByIncidentTypePerPlaybookTop5.json
  Packs/CommonWidgets/Widgets/widget-AverageRuntimeByInstancePerCommandTop5.json
  Packs/CommonWidgets/Widgets/widget-AverageRuntimeForPlaybooks.json
  Packs/CommonWidgets/Widgets/widget-AverageRuntimePerAutomationTop5.json
  Packs/CommonWidgets/Widgets/widget-AverageRuntimePerPlaybookTop5.json
  Packs/CommonWidgets/Widgets/widget-CommandAverageRuntimePerInstanceTop5.json
  Packs/CommonWidgets/Widgets/widget-CommandExecutionErrors.json
  Packs/CommonWidgets/Widgets/widget-CommandExecutionErrorsPerInstance.json
  Packs/CommonWidgets/Widgets/widget-CommandExecutionErrorsPerIntegrationCategory.json
  Packs/CommonWidgets/Widgets/widget-CommandExecutionType.json
  Packs/CommonWidgets/Widgets/widget-CommandExecutionsErrors.json
  Packs/CommonWidgets/Widgets/widget-CommandExecutionsPerIncidentType.json
  Packs/CommonWidgets/Widgets/widget-CommandExecutionsPerIntegrationCategory.json
  Packs/CommonWidgets/Widgets/widget-CommandsExecuted.json
  Packs/CommonWidgets/Widgets/widget-ErrorsByIncidentTypePerCommandTop5.json
  Packs/CommonWidgets/Widgets/widget-ExecutionsByStatusPerAutomatedTasksTop5.json
  Packs/CommonWidgets/Widgets/widget-ExecutionsByStatusPerManualTasksTop5.json
  Packs/CommonWidgets/Widgets/widget-FailedAutomationExecutionsPerIncidentTypesTop5.json
  Packs/CommonWidgets/Widgets/widget-FailedManualTasks.json
  Packs/CommonWidgets/Widgets/widget-FailedPlaybooksRuns.json
  Packs/CommonWidgets/Widgets/widget-LeastExecutedCommands.json
  Packs/CommonWidgets/Widgets/widget-LeastExecutedCommandsPerInstance.json
  Packs/CommonWidgets/Widgets/widget-ManualCommandExecutionErrorsTop5.json
  Packs/CommonWidgets/Widgets/widget-PlaybookRunErrors.json
  Packs/CommonWidgets/Widgets/widget-PlaybookRuns.json
  Packs/CommonWidgets/Widgets/widget-TaskExecutionErrors.json
  Packs/CommonWidgets/Widgets/widget-TaskExecutions.json
  Packs/CommonWidgets/Widgets/widget-TopExecutedCommands.json
  Packs/CommonWidgets/Widgets/widget-TopUsersClosedManualTasks.json
  Packs/CommonWidgets/pack_metadata.json
Labels: docs-approved, release-notes-only

#13004 Updated TIM_Processing Pack README
  Packs/TIM_Processing/README.md
Labels: docs-approved

#12893 Create Sandblast content pack README
  Packs/Sandblast/README.md
Labels: docs-approved

#12931 ignored error BA101 for some files
  Packs/Active_Directory_Query/.pack-ignore
  Packs/BmcHelixRemedyForce/.pack-ignore
  Packs/Box/.pack-ignore
  Packs/CarbonBlackDefense/.pack-ignore
  Packs/Claroty/.pack-ignore
  Packs/CommonTypes/.pack-ignore
  Packs/CortexXDR/.pack-ignore
  Packs/CrowdStrikeFalcon/.pack-ignore
  Packs/CrowdStrikeFalconStreamingV2/.pack-ignore
  Packs/Cyberint/.pack-ignore
  Packs/Cymulate/.pack-ignore
  Packs/Darktrace/.pack-ignore
  Packs/EWS/.pack-ignore
  Packs/EmailCommunication/.pack-ignore
  Packs/ExpanseV2/.pack-ignore
  Packs/FeedAWS/.pack-ignore
  Packs/FireEyeNX/.pack-ignore
  Packs/FraudWatch/.pack-ignore
  Packs/Gmail/.pack-ignore
  Packs/GmailSingleUser/.pack-ignore
  Packs/GoogleChronicleBackstory/.pack-ignore
  Packs/GoogleCloudSCC/.pack-ignore
  Packs/GoogleDrive/.pack-ignore
  Packs/GroupIB_ThreatIntelligenceAttribution/.pack-ignore
  Packs/Gurucul/.pack-ignore
  Packs/Gurucul/pack_metadata.json
  Packs/HelloWorld/.pack-ignore
  Packs/IllusiveNetworks/.pack-ignore
  Packs/Indeni/.pack-ignore
  Packs/Infinipoint/.pack-ignore
  Packs/IronDefense/.pack-ignore
  Packs/Jira/.pack-ignore
  Packs/Logzio/.pack-ignore
  Packs/MicrosoftAdvancedThreatAnalytics/.pack-ignore
  Packs/MicrosoftCloudAppSecurity/.pack-ignore
  Packs/MicrosoftGraphListener/.pack-ignore
  Packs/NTT_Cyber_Threat_Sensor/.pack-ignore
  Packs/NutanixHypervisor/.pack-ignore
  Packs/OnboardingIntegration/.pack-ignore
  Packs/PrismaCloud/.pack-ignore
  Packs/PrismaCloudCompute/.pack-ignore
  Packs/QRadar/.pack-ignore
  Packs/QualysFIM/.pack-ignore
  Packs/RubrikPolaris/.pack-ignore
  Packs/ServiceNow/.pack-ignore
  Packs/Smokescreen_IllusionBLACK/.pack-ignore
  Packs/SplunkPy/.pack-ignore
  Packs/TOPdesk/.pack-ignore
  Packs/TrendMicroCAS/.pack-ignore
  Packs/Tripwire/.pack-ignore
  Packs/UnifiVideoNVR/.pack-ignore
  Packs/XSOARmirroring/.pack-ignore
  Packs/Zimperium/.pack-ignore
  Packs/mnemonicMDR/.pack-ignore
Labels: docs-approved

#13084 Update conf.json
  Tests/conf.json
Labels: docs-approved

#13023 DevSecOps: pack readme: images to absolute links
  Packs/DevSecOps/Integrations/GitLab/README.md
  Packs/DevSecOps/README.md
Labels: docs-approved

#13071 lost stollen device: fix link
  Packs/Lost_Stolen_Device/README.md
Labels: docs-approved

#13093 ignoring DS107 in EWSO365 description
  Packs/EWS/.pack-ignore
Labels: docs-approved

#12881 URLScan.io Adoption
  Packs/UrlScan/README.md
  Packs/UrlScan/ReleaseNotes/1_1_7.md
  Packs/UrlScan/pack_metadata.json
Labels: Contribution, Contribution Form Filled, Partner, docs-approved

#13087 Arcsight login fix
  Packs/ArcSightLogger/Integrations/integration-ArcSightLogger.yml
  Packs/ArcSightLogger/ReleaseNotes/1_0_4.md
  Packs/ArcSightLogger/pack_metadata.json
Labels: docs-approved

#13090 added IF100 to relevant .pack-ignore files
  Packs/AgariPhishingDefense/.pack-ignore
  Packs/Armis/.pack-ignore
  Packs/Campaign/.pack-ignore
  Packs/CarbonBlackDefense/.pack-ignore
  Packs/CommonTypes/.pack-ignore
  Packs/CortexXDR/.pack-ignore
  Packs/Cyberint/.pack-ignore
  Packs/Cymulate/.pack-ignore
  Packs/DevSecOps/.pack-ignore
  Packs/ExpanseV2/.pack-ignore
  Packs/GSuiteSecurityAlertCenter/.pack-ignore
  Packs/GoogleChronicleBackstory/.pack-ignore
  Packs/GoogleCloudSCC/.pack-ignore
  Packs/Gurucul/.pack-ignore
  Packs/IllusiveNetworks/.pack-ignore
  Packs/IntegrationsAndIncidentsHealthCheck/.pack-ignore
  Packs/IronDefense/.pack-ignore
  Packs/Logzio/.pack-ignore
  Packs/NIST/.pack-ignore
  Packs/NetscoutArborSightline/.pack-ignore
  Packs/NutanixHypervisor/.pack-ignore
  Packs/Orca/.pack-ignore
  Packs/PaloAltoNetworks_IoT/.pack-ignore
  Packs/PrismaCloudCompute/.pack-ignore
  Packs/QRadar/.pack-ignore
  Packs/QSS/.pack-ignore
  Packs/QualysFIM/.pack-ignore
  Packs/RubrikPolaris/.pack-ignore
  Packs/SANS/.pack-ignore
  Packs/ServiceNow/.pack-ignore
  Packs/ShiftManagement/.pack-ignore
  Packs/Smokescreen_IllusionBLACK/.pack-ignore
  Packs/TheHiveProject/.pack-ignore
  Packs/mnemonicMDR/.pack-ignore
Labels: docs-approved

#13025 McAfee fix-bug in edit case and add test
  Packs/McAfee_ESM/Integrations/McAfee_ESM_v2/McAfee_ESM_v2.py
  Packs/McAfee_ESM/Integrations/McAfee_ESM_v2/McAfee_ESM_v2.yml
  Packs/McAfee_ESM/Integrations/McAfee_ESM_v2/McAfee_ESM_v2_test.py
  Packs/McAfee_ESM/ReleaseNotes/1_1_7.md
  Packs/McAfee_ESM/pack_metadata.json
Labels: bug, docs-approved, release-notes-only

#13078 ExtractEmailV2: fixed local-part detection
  Packs/CommonScripts/.secrets-ignore
  Packs/CommonScripts/ReleaseNotes/1_3_56.md
  Packs/CommonScripts/Scripts/ExtractEmailFormatting/ExtractEmailFormatting.py
  Packs/CommonScripts/Scripts/ExtractEmailFormatting/ExtractEmailFormatting.yml
  Packs/CommonScripts/Scripts/ExtractEmailFormatting/ExtractEmailFormatting_test.py
  Packs/CommonScripts/pack_metadata.json
  Packs/CommonTypes/IndicatorTypes/reputation-email.json
  Packs/CommonTypes/ReleaseNotes/3_0_6.md
  Packs/CommonTypes/pack_metadata.json
Labels: bug, docs-approved, release-notes-only

#13101 Fix pack ignore files
  Packs/FireEyeNX/.pack-ignore
  Packs/Respond/.pack-ignore
  Packs/SolarWinds/.pack-ignore
Labels: docs-approved

#13104 misp v2 fix tpb
  Packs/MISP/TestPlaybooks/playbook-MISP_V2-Test.yml
Labels: docs-approved

#13096 Remove the instance testing from the commit circle workflow
  .circleci/config.yml
  .gitlab/ci/global.yml
Labels: docs-approved

#13070 changed name from "Prepare Content Packs For Testing.log" to "Prepare Content Packs For Testing gsutil.log
  Tests/scripts/prepare_content_packs_for_testing.sh
Labels: docs-approved

#13092 bump version
  .circleci/content_release_vars.sh
Labels: docs-approved

#13109 Linkshadow: First fetch fix
  Packs/Linkshadow/Integrations/Linkshadow/Linkshadow.py
  Packs/Linkshadow/Integrations/Linkshadow/Linkshadow.yml
  Packs/Linkshadow/Integrations/Linkshadow/Linkshadow_test.py
  Packs/Linkshadow/ReleaseNotes/1_0_2.md
  Packs/Linkshadow/pack_metadata.json
Labels: Contribution, Contribution Form Filled, docs-approved

#13126 Nightly SDK fix
  Tests/sdknightly/create_entities_for_nightly_sdk.py
Labels: docs-approved

#13103 removed "Pwned v2 test" from skipped tests
  Tests/conf.json
Labels: docs-approved

#12981 Armis Bug Fix
  Packs/Armis/Integrations/Armis/Armis.py
  Packs/Armis/Integrations/Armis/Armis_test.py
  Packs/Armis/ReleaseNotes/1_0_2.md
  Packs/Armis/pack_metadata.json
Labels: docs-approved, release-notes-only

#12173 Updated campaign pack readme, fixed typo in EWS pack readme
  Packs/Campaign/README.md
  Packs/Campaign/pack_metadata.json
  Packs/EWS/README.md
Labels: docs-approved

#12540 HPE Aruba clearpass v1
  Packs/HPEArubaClearPass/.pack-ignore
  Packs/HPEArubaClearPass/.secrets-ignore
  Packs/HPEArubaClearPass/Integrations/HPEArubaClearPass/HPEArubaClearPass.py
  Packs/HPEArubaClearPass/Integrations/HPEArubaClearPass/HPEArubaClearPass.yml
  Packs/HPEArubaClearPass/Integrations/HPEArubaClearPass/HPEArubaClearPass_description.md
  Packs/HPEArubaClearPass/Integrations/HPEArubaClearPass/HPEArubaClearPass_image.png
  Packs/HPEArubaClearPass/Integrations/HPEArubaClearPass/HPEArubaClearPass_test.py
  Packs/HPEArubaClearPass/Integrations/HPEArubaClearPass/Pipfile
  Packs/HPEArubaClearPass/Integrations/HPEArubaClearPass/Pipfile.lock
  Packs/HPEArubaClearPass/Integrations/HPEArubaClearPass/README.md
  Packs/HPEArubaClearPass/Integrations/HPEArubaClearPass/command_examples
  Packs/HPEArubaClearPass/Integrations/HPEArubaClearPass/test_data/active_sessions_list_response.json
  Packs/HPEArubaClearPass/Integrations/HPEArubaClearPass/test_data/attributes_list_response.json
  Packs/HPEArubaClearPass/Integrations/HPEArubaClearPass/test_data/create_attribute_response.json
  Packs/HPEArubaClearPass/Integrations/HPEArubaClearPass/test_data/disconnect_active_session_response.json
  Packs/HPEArubaClearPass/Integrations/HPEArubaClearPass/test_data/endpoints_list_response.json
  Packs/HPEArubaClearPass/Integrations/HPEArubaClearPass/test_data/update_endpoint_response.json
  Packs/HPEArubaClearPass/README.md
  Packs/HPEArubaClearPass/TestPlaybooks/playbook-HPEArubaClearPass-Test.yml
  Packs/HPEArubaClearPass/pack_metadata.json
  Tests/conf.json
Labels: docs-approved, post-demo

#13133 config.yml fix for nightly SDK
  .circleci/config.yml
  .gitlab/ci/sdk-nightly.yml
Labels: docs-approved

#13079 new test for Cortex XDR - IOC integration
  Packs/CortexXDR/TestPlaybooks/Coretx_XDR_-_IOC_-_Test_without_fetch.yml
  Tests/conf.json
Labels: docs-approved

#13121 fix broken api
  Packs/XMCyber/Integrations/XMCyberIntegration/XMCyberIntegration.py
  Packs/XMCyber/Integrations/XMCyberIntegration/XMCyberIntegration.yml
  Packs/XMCyber/Integrations/XMCyberIntegration/XMCyberIntegration_test.py
  Packs/XMCyber/ReleaseNotes/1_0_8.md
  Packs/XMCyber/pack_metadata.json
Labels: Contribution, Contribution Form Filled, Partner, docs-approved

#13141 SDK nightly - Download files change, validation on download
  .circleci/config.yml
  .gitlab/ci/sdk-nightly.yml
Labels: docs-approved

#12745 Smbv2: Possible bug fix. changes auth_protocol
  Packs/SMB/Integrations/SMB_v2/SMB_v2.py
  Packs/SMB/Integrations/SMB_v2/SMB_v2.yml
  Packs/SMB/ReleaseNotes/2_0_2.md
  Packs/SMB/pack_metadata.json
Labels: bug, docs-approved, release-notes-only

#13056 support tldextract versions
  Packs/Base/ReleaseNotes/1_12_5.md
  Packs/Base/Scripts/CommonServerPython/CommonServerPython.py
  Packs/Base/Scripts/CommonServerPython/CommonServerPython.yml
  Packs/Base/Scripts/CommonServerPython/CommonServerPython_test.py
  Packs/Base/pack_metadata.json
Labels: docs-approved, release-notes-only

#13158 remove demisto from README.md
  Packs/HPEArubaClearPass/Integrations/HPEArubaClearPass/README.md
Labels: docs-approved

#12206 Carbon black cloud integration
  Packs/CarbonBlackDefense/.secrets-ignore
  Packs/CarbonBlackDefense/Integrations/CarbonBlackEndpointStandard/CarbonBlackEndpointStandard_description.md
  Packs/CarbonBlackDefense/Integrations/CarbonBlackLiveResponseCloud/CarbonBlackLiveResponseCloud.py
  Packs/CarbonBlackDefense/Integrations/CarbonBlackLiveResponseCloud/CarbonBlackLiveResponseCloud.yml
  Packs/CarbonBlackDefense/Integrations/CarbonBlackLiveResponseCloud/CarbonBlackLiveResponseCloud_description.md
  Packs/CarbonBlackDefense/Integrations/CarbonBlackLiveResponseCloud/CarbonBlackLiveResponseCloud_image.png
  Packs/CarbonBlackDefense/Integrations/CarbonBlackLiveResponseCloud/CarbonBlackLiveResponseCloud_test.py
  Packs/CarbonBlackDefense/Integrations/CarbonBlackLiveResponseCloud/README.md
  Packs/CarbonBlackDefense/Integrations/CarbonBlackLiveResponseCloud/command_examples.txt
  Packs/CarbonBlackDefense/Integrations/CarbonBlackLiveResponseCloud/test_data/test.txt
  Packs/CarbonBlackDefense/ReleaseNotes/3_0_0.md
  Packs/CarbonBlackDefense/TestPlaybooks/CarbonBlackLiveResponseCloud-Test.yml
  Packs/CarbonBlackDefense/pack_metadata.json
  Tests/conf.json
Labels: docs-approved

#13157 unskip Active Directory - Get User Manager Details - Test
  Tests/conf.json
Labels: docs-approved

#13100 service account files: clarify testing
  Packs/ApiModules/Scripts/GSuiteApiModule/test_data/service_account_json.txt
  Packs/GSuiteAdmin/Integrations/GSuiteAdmin/test_data/service_account_json.txt
  Packs/GSuiteSecurityAlertCenter/Integrations/GSuiteSecurityAlertCenter/test_data/service_account_json.json
  Packs/GoogleCalendar/Integrations/GoogleCalendar/test_data/service_account_json.txt
  Packs/GoogleCloudSCC/Integrations/GoogleCloudSCC/TestData/service_account_json.txt
  Packs/GoogleDrive/Integrations/GoogleDrive/test_data/service_account_json.txt
Labels: docs-approved

#13116 Adding nginx support for export indicators
  Packs/ApiModules/Scripts/NGINXApiModule/NGINXApiModule.py
  Packs/ApiModules/Scripts/NGINXApiModule/NGINXApiModule.yml
  Packs/ApiModules/Scripts/NGINXApiModule/NGINXApiModule_test.py
  Packs/EDL/Integrations/EDL/EDL.py
  Packs/EDL/Integrations/EDL/EDL_test.py
  Packs/EDL/ReleaseNotes/2_0_5.md
  Packs/EDL/pack_metadata.json
  Packs/ExportIndicators/Integrations/ExportIndicators/ExportIndicators.py
  Packs/ExportIndicators/Integrations/ExportIndicators/ExportIndicators.yml
  Packs/ExportIndicators/Integrations/ExportIndicators/ExportIndicators_description.md
  Packs/ExportIndicators/Integrations/ExportIndicators/ExportIndicators_test.py
  Packs/ExportIndicators/ReleaseNotes/1_0_9.md
  Packs/ExportIndicators/pack_metadata.json
  Tests/conf.json
Labels: docs-approved

#13165 MS Graph Mail Single User - set the contentId attribute in the attachment object
  Packs/MicrosoftGraphListener/Integrations/MicrosoftGraphListener/MicrosoftGraphListener.py
  Packs/MicrosoftGraphListener/Integrations/MicrosoftGraphListener/MicrosoftGraphListener.yml
  Packs/MicrosoftGraphListener/Integrations/MicrosoftGraphListener/MicrosoftGraphListener_test.py
  Packs/MicrosoftGraphListener/Integrations/MicrosoftGraphListener/README.md
  Packs/MicrosoftGraphListener/ReleaseNotes/1_0_16.md
  Packs/MicrosoftGraphListener/pack_metadata.json
Labels: bug, docs-approved, release-notes-only

#12977 GitHub - add release command
  Packs/GitHub/Integrations/GitHub/GitHub.py
  Packs/GitHub/Integrations/GitHub/GitHub.yml
  Packs/GitHub/Integrations/GitHub/README.md
  Packs/GitHub/ReleaseNotes/1_2_10.md
  Packs/GitHub/TestPlaybooks/playbook-Git_Integration-Test.yml
  Packs/GitHub/pack_metadata.json
Labels: docs-approved

#13166 CommonServer - handle zero ip address subnet
  Packs/Base/ReleaseNotes/1_12_6.md
  Packs/Base/Scripts/script-CommonServer.yml
  Packs/Base/pack_metadata.json
  Packs/CommonScripts/TestPlaybooks/IsIPInRanges_-_Test.yml
Labels: docs-approved, release-notes-only

#12979 Symantec mss bug
  Packs/SymantecMSS/Integrations/SymantecMSS/SymantecMSS.py
  Packs/SymantecMSS/ReleaseNotes/1_0_3.md
  Packs/SymantecMSS/pack_metadata.json
Labels: docs-approved

#13053 Joe security test failure
  Packs/JoeSecurity/Integrations/JoeSecurity/JoeSecurity.py
  Packs/JoeSecurity/Integrations/JoeSecurity/JoeSecurity_test.py
  Packs/JoeSecurity/ReleaseNotes/1_0_5.md
  Packs/JoeSecurity/pack_metadata.json
Labels: docs-approved, release-notes-only

#13073 Tia duplication bugfix
  Packs/GroupIB_ThreatIntelligenceAttribution/Integrations/GroupIBTIA/GroupIBTIA.py
  Packs/GroupIB_ThreatIntelligenceAttribution/Integrations/GroupIBTIA/GroupIBTIA.yml
  Packs/GroupIB_ThreatIntelligenceAttribution/Integrations/GroupIBTIA/GroupIBTIA_description.md
  Packs/GroupIB_ThreatIntelligenceAttribution/Integrations/GroupIBTIA/GroupIBTIA_image.png
  Packs/GroupIB_ThreatIntelligenceAttribution/Integrations/GroupIBTIA/GroupIBTIA_test.py
  Packs/GroupIB_ThreatIntelligenceAttribution/Integrations/GroupIBTIA/Pipfile
  Packs/GroupIB_ThreatIntelligenceAttribution/Integrations/GroupIBTIA/Pipfile.lock
  Packs/GroupIB_ThreatIntelligenceAttribution/Integrations/GroupIBTIA/README.md
  Packs/GroupIB_ThreatIntelligenceAttribution/Integrations/GroupIBTIA/command_examples.txt
  Packs/GroupIB_ThreatIntelligenceAttribution/Integrations/GroupIBTIA/test_data/example.json
  Packs/GroupIB_ThreatIntelligenceAttribution/Integrations/GroupIBTIA/test_data/results.json
  Packs/GroupIB_ThreatIntelligenceAttribution/ReleaseNotes/1_0_2.md
  Packs/GroupIB_ThreatIntelligenceAttribution/Scripts/GIBIncidentUpdate/GIBIncidentUpdate.py
  Packs/GroupIB_ThreatIntelligenceAttribution/Scripts/GIBIncidentUpdate/GIBIncidentUpdate.yml
  Packs/GroupIB_ThreatIntelligenceAttribution/Scripts/GIBIncidentUpdate/GIBIncidentUpdate_test.py
  Packs/GroupIB_ThreatIntelligenceAttribution/Scripts/GIBIncidentUpdate/Pipfile
  Packs/GroupIB_ThreatIntelligenceAttribution/Scripts/GIBIncidentUpdate/Pipfile.lock
  Packs/GroupIB_ThreatIntelligenceAttribution/Scripts/GIBIncidentUpdate/README.md
  Packs/GroupIB_ThreatIntelligenceAttribution/pack_metadata.json
Labels: Contribution, Contribution Form Filled, docs-approved

#13169 SDK nightly fix: added IF100 to relevant .pack-ignore files
  Packs/CommonTypes/.pack-ignore
  Packs/FireEyeCommonFields/.pack-ignore
Labels: docs-approved

#13132 ThreatCrowd NoneType IP Command BugFix
  Packs/Threat_Crowd/Integrations/ThreatCrowd_v2/ThreatCrowd_v2.py
  Packs/Threat_Crowd/Integrations/ThreatCrowd_v2/ThreatCrowd_v2.yml
  Packs/Threat_Crowd/Integrations/ThreatCrowd_v2/ThreatCrowd_v2_test.py
  Packs/Threat_Crowd/Integrations/ThreatCrowd_v2/test_data/response_mocks.json
  Packs/Threat_Crowd/ReleaseNotes/2_0_3.md
  Packs/Threat_Crowd/pack_metadata.json
Labels: docs-approved, release-notes-only

#13136 Match regex v2 docs fix
  Packs/CommonScripts/ReleaseNotes/1_3_57.md
  Packs/CommonScripts/Scripts/MatchRegexV2/MatchRegexV2.yml
  Packs/CommonScripts/Scripts/MatchRegexV2/README.md
  Packs/CommonScripts/pack_metadata.json
Labels: docs-approved, release-notes-only

#13091 Elasticsearch Monitoring Pack
  Packs/ElasticsearchMonitoring/.pack-ignore
  Packs/ElasticsearchMonitoring/.secrets-ignore
  Packs/ElasticsearchMonitoring/Dashboards/elasticsearch_monitoring.json
  Packs/ElasticsearchMonitoring/README.md
  Packs/ElasticsearchMonitoring/Widgets/widget-ElasticSearchActiveNodes.json
  Packs/ElasticsearchMonitoring/Widgets/widget-ElasticSearchActiveNodesPercentage.json
  Packs/ElasticsearchMonitoring/Widgets/widget-ElasticSearchActiveShards.json
  Packs/ElasticsearchMonitoring/Widgets/widget-ElasticSearchActiveShardsPercentage.json
  Packs/ElasticsearchMonitoring/Widgets/widget-ElasticSearchCPUCurrentUsage.json
  Packs/ElasticsearchMonitoring/Widgets/widget-ElasticSearchDiskCurrentUsage.json
  Packs/ElasticsearchMonitoring/Widgets/widget-ElasticSearchDiskFree.json
  Packs/ElasticsearchMonitoring/Widgets/widget-ElasticSearchDiskTotal.json
  Packs/ElasticsearchMonitoring/Widgets/widget-ElasticSearchDiskUsed.json
  Packs/ElasticsearchMonitoring/Widgets/widget-ElasticSearchDocumentTotal.json
  Packs/ElasticsearchMonitoring/Widgets/widget-ElasticSearchDocumentTotalTrend.json
  Packs/ElasticsearchMonitoring/Widgets/widget-ElasticSearchFailedNodes.json
  Packs/ElasticsearchMonitoring/Widgets/widget-ElasticSearchFailedShards.json
  Packs/ElasticsearchMonitoring/Widgets/widget-ElasticSearchIndices.json
  Packs/ElasticsearchMonitoring/Widgets/widget-ElasticSearchJVMCurrentUsage.json
  Packs/ElasticsearchMonitoring/Widgets/widget-ElasticSearchMemoryTotal.json
  Packs/ElasticsearchMonitoring/Widgets/widget-ElasticSearchShardsDistribution.json
  Packs/ElasticsearchMonitoring/Widgets/widget-ElasticSearchStatus.json
  Packs/ElasticsearchMonitoring/pack_metadata.json
Labels: docs-approved

#13031 Update sane-pdf-report script with new docker image
  Packs/Base/ReleaseNotes/1_12_7.md
  Packs/Base/Scripts/SanePdfReport/SanePdfReport.yml
  Packs/Base/pack_metadata.json
Labels: docs-approved, release-notes-only

#13137 GitLab Flows Tweaks and Fixes
  .gitlab/ci/bucket-upload.yml
  .gitlab/ci/on-push.yml
  .gitlab/ci/sdk-nightly.yml
  .gitlab/ci/slack-notify.yml
Labels: docs-approved

#13140 Tidy updates
  Packs/Tidy/Integrations/Tidy/Tidy.py
  Packs/Tidy/Integrations/Tidy/Tidy.yml
  Packs/Tidy/Playbooks/playbook-Content_developer_setup.yml
  Packs/Tidy/ReleaseNotes/1_0_4.md
  Packs/Tidy/pack_metadata.json
Labels: docs-approved

#13173 Upload index fix
  Tests/scripts/prepare_content_packs_for_testing.sh
Labels: docs-approved

#13095 unskip ipstack integration and improved impossible traveler playbook
  Packs/ImpossibleTraveler/Playbooks/Impossible_Traveler.yml
  Packs/ImpossibleTraveler/ReleaseNotes/1_2_3.md
  Packs/ImpossibleTraveler/pack_metadata.json
  Tests/conf.json
Labels: docs-approved, release-notes-only

#12877 JWT New Integration
  Packs/JWT/.pack-ignore
  Packs/JWT/.secrets-ignore
  Packs/JWT/Integrations/JWT/JWT.py
  Packs/JWT/Integrations/JWT/JWT.yml
  Packs/JWT/Integrations/JWT/JWT_description.md
  Packs/JWT/Integrations/JWT/JWT_image.png
  Packs/JWT/Integrations/JWT/Pipfile
  Packs/JWT/Integrations/JWT/Pipfile.lock
  Packs/JWT/Integrations/JWT/README.md
  Packs/JWT/Integrations/JWT/command_examples
  Packs/JWT/README.md
  Packs/JWT/pack_metadata.json
  package-lock.json
Labels: Contribution

#13164 Update playbook-Isolate_Endpoint_-_Cybereason_README.md
  Packs/Cybereason/Playbooks/playbook-Isolate_Endpoint_-_Cybereason_README.md
Labels: docs-approved

#13138 Added case related commands
  Packs/Gurucul/Classifiers/classifier-GraCase_5_9_9.json
  Packs/Gurucul/Classifiers/classifier-GraHighRiskUser_5_9_9.json
  Packs/Gurucul/Classifiers/classifier-Gurucul-GRACase.json
  Packs/Gurucul/Classifiers/classifier-Gurucul-HighRiskUsers.json
  Packs/Gurucul/Classifiers/classifier-mapper-Gurucul-GRACases.json
  Packs/Gurucul/Classifiers/classifier-mapper-Gurucul-HighRiskUsers.json
  Packs/Gurucul/Integrations/GuruculGRA/GuruculGRA.py
  Packs/Gurucul/Integrations/GuruculGRA/GuruculGRA.yml
  Packs/Gurucul/Integrations/GuruculGRA/GuruculGRA_description.md
  Packs/Gurucul/Integrations/GuruculGRA/GuruculGRA_test.py
  Packs/Gurucul/Integrations/GuruculGRA/README.md
  Packs/Gurucul/Integrations/GuruculGRA/command_examples
  Packs/Gurucul/Integrations/GuruculGRA/test_data/gra-case-action-anomaly.json
  Packs/Gurucul/Integrations/GuruculGRA/test_data/gra-case-action.json
  Packs/Gurucul/Integrations/GuruculGRA/test_data/gra-cases.json
  Packs/Gurucul/Integrations/GuruculGRA/test_data/gra-fetch-resource-hpa.json
  Packs/Gurucul/Integrations/GuruculGRA/test_data/gra-investigate-anomaly-summary.json
  Packs/Gurucul/ReleaseNotes/1_0_1.md
  Packs/Gurucul/TestPlaybooks/TestGraPlayBook.yml
Labels: Contribution, Contribution Form Filled, docs-approved, ready-for-instance-test

#13178 unskip ews unmockable tests
  Tests/conf.json
Labels: docs-approved

#13086 remove private tests from nightly
  Tests/conf.json
  Tests/scripts/collect_tests_and_content_packs.py
Labels: docs-approved

#13065 New transformer converting json to a table
  Packs/CommonScripts/ReleaseNotes/1_3_58.md
  Packs/CommonScripts/Scripts/JsonToTable/JsonToTable.py
  Packs/CommonScripts/Scripts/JsonToTable/JsonToTable.yml
  Packs/CommonScripts/pack_metadata.json
Labels: docs-approved

#13175 Malicious Indicators Activity by Type - add time resolution
  Packs/CommonWidgets/ReleaseNotes/1_1_1.md
  Packs/CommonWidgets/Widgets/widget-IndicatorBadActivityType.json
  Packs/CommonWidgets/pack_metadata.json
Labels: docs-approved, release-notes-only

#13193 changed tested ip to one with a hostname
  Packs/ipinfo/TestPlaybooks/playbook-IPinfo_v2_Test.yml
Labels: docs-approved

#13012 Change Taxii V2 and Crowdstrike Falcon Intel Feed to work with lastRun
  Packs/Base/ReleaseNotes/1_12_8.md
  Packs/Base/Scripts/CommonServerPython/CommonServerPython.py
  Packs/Base/Scripts/CommonServerPython/CommonServerPython_test.py
  Packs/Base/pack_metadata.json
  Packs/FeedCrowdstrikeFalconIntel/Integrations/FeedCrowdstrikeFalconIntel/FeedCrowdstrikeFalconIntel.py
  Packs/FeedCrowdstrikeFalconIntel/Integrations/FeedCrowdstrikeFalconIntel/FeedCrowdstrikeFalconIntel.yml
  Packs/FeedCrowdstrikeFalconIntel/ReleaseNotes/2_0_1.md
  Packs/FeedCrowdstrikeFalconIntel/ReleaseNotes/2_0_2.md
  Packs/FeedCrowdstrikeFalconIntel/pack_metadata.json
  Packs/FeedTAXII/Integrations/FeedTAXII2/FeedTAXII2.py
  Packs/FeedTAXII/Integrations/FeedTAXII2/FeedTAXII2.yml
  Packs/FeedTAXII/ReleaseNotes/1_0_9.md
  Packs/FeedTAXII/pack_metadata.json
Labels: docs-approved

#13128 added error BA101 to some packs' pack ignore file
  Packs/AzureSecurityCenter/.pack-ignore
  Packs/CrowdStrikeFalcon/.pack-ignore
  Packs/SolarWinds/.pack-ignore
Labels: docs-approved

#13198 SailPoint IdentityIQ correct yaml outputs
  Packs/SailPointIdentityIQ/Integrations/SailPointIdentityIQ/README.md
  Packs/SailPointIdentityIQ/Integrations/SailPointIdentityIQ/SailPointIdentityIQ.py
  Packs/SailPointIdentityIQ/Integrations/SailPointIdentityIQ/SailPointIdentityIQ.yml
  Packs/SailPointIdentityIQ/ReleaseNotes/1_0_2.md
  Packs/SailPointIdentityIQ/pack_metadata.json
Labels: docs-approved

#12439 Cyberpion integration
  Packs/Cyberpion/.pack-ignore
  Packs/Cyberpion/.secrets-ignore
  Packs/Cyberpion/Classifiers/classifier-Cyberpion_-_Classifier.json
  Packs/Cyberpion/Classifiers/classifier-Cyberpion_-_Mapper.json
  Packs/Cyberpion/IncidentFields/incidentfield-Cyberpion_Action_item_ID.json
  Packs/Cyberpion/IncidentFields/incidentfield-Cyberpion_Category.json
  Packs/Cyberpion/IncidentFields/incidentfield-Cyberpion_Domain.json
  Packs/Cyberpion/IncidentFields/incidentfield-Cyberpion_Impact.json
  Packs/Cyberpion/IncidentFields/incidentfield-Cyberpion_Solution.json
  Packs/Cyberpion/IncidentFields/incidentfield-Cyberpion_Summary.json
  Packs/Cyberpion/IncidentFields/incidentfield-Cyberpion_Technical_Details.json
  Packs/Cyberpion/IncidentFields/incidentfield-Cyberpion_Title.json
  Packs/Cyberpion/IncidentFields/incidentfield-Cyberpion_Vulnerability_Description.json
  Packs/Cyberpion/IncidentFields/incidentfield-Cyberpion_portal_link.json
  Packs/Cyberpion/IncidentTypes/incidenttype-Cyberpion_Security_Alert.json
  Packs/Cyberpion/Integrations/Cyberpion/Cyberpion.py
  Packs/Cyberpion/Integrations/Cyberpion/Cyberpion.yml
  Packs/Cyberpion/Integrations/Cyberpion/Cyberpion_description.md
  Packs/Cyberpion/Integrations/Cyberpion/Cyberpion_image.png
  Packs/Cyberpion/Integrations/Cyberpion/Cyberpion_test.py
  Packs/Cyberpion/Integrations/Cyberpion/Pipfile
  Packs/Cyberpion/Integrations/Cyberpion/Pipfile.lock
  Packs/Cyberpion/Integrations/Cyberpion/README.md
  Packs/Cyberpion/Integrations/Cyberpion/command_examples
  Packs/Cyberpion/Integrations/Cyberpion/test_data/domain_state.json
  Packs/Cyberpion/Integrations/Cyberpion/test_data/new_incidents.json
  Packs/Cyberpion/Layouts/layoutscontainer-Cyberpion_-_Action_Item.json
  Packs/Cyberpion/Playbooks/Cyberpion_Domain_State.yml
  Packs/Cyberpion/Playbooks/Cyberpion_Domain_State_README.md
  Packs/Cyberpion/README.md
  Packs/Cyberpion/TestPlaybooks/Cyberpion-Test.yml
  Packs/Cyberpion/doc_files/Cyberpion Domain State.png
  Packs/Cyberpion/pack_metadata.json
Labels: Contribution, Contribution Form Filled, Partner, docs-approved, post-demo

#13131 Changed README
  Packs/Recorded_Future/README.md
Labels: docs-approved

#12869 Xdr support v2.9 and array support
  Packs/CortexXDR/Integrations/CortexXDRIR/CortexXDRIR.py
  Packs/CortexXDR/Integrations/CortexXDRIR/CortexXDRIR.yml
  Packs/CortexXDR/Integrations/CortexXDRIR/CortexXDRIR_test.py
  Packs/CortexXDR/Integrations/CortexXDRIR/README.md
  Packs/CortexXDR/Integrations/CortexXDRIR/test_data/run_script_multiple_inputs_and_endpoints.json
  Packs/CortexXDR/ReleaseNotes/3_0_15.md
  Packs/CortexXDR/pack_metadata.json
Labels: docs-approved

#13019 Update SentinelOne-V2.py
  Packs/SentinelOne/Integrations/SentinelOne-V2/SentinelOne-V2.py
  Packs/SentinelOne/Integrations/SentinelOne-V2/SentinelOne-V2.yml
  Packs/SentinelOne/ReleaseNotes/2_0_2.md
  Packs/SentinelOne/pack_metadata.json
Labels: Contribution, Contribution Form Filled, docs-approved, ready-for-instance-test

#13205 Google pylintrc
  Packs/GmailSingleUser/Integrations/GmailSingleUser/.pylintrc
  Packs/GoogleCloudFunctions/Integrations/GoogleCloudFunctions/.pylintrc
  Packs/GooglePubSub/Integrations/GooglePubSub/.pylintrc
  Packs/GoogleVisionAPI/Integrations/GoogleVisionAPI/.pylintrc
Labels: docs-approved

#13206 rm old falcon intel test playbook
  Packs/CrowdStrikeIntel/TestPlaybooks/playbook-CrowdStrike_Intel_Test.yml
  Tests/conf.json
Labels: docs-approved

#13211 unskip Create ServiceNow Ticket and Mirror Test
  Tests/conf.json
Labels: docs-approved

#13210 renamed layouts folder in Tidy pack
  Packs/Tidy/Layouts/layoutscontainer-Tidy.json
  Packs/Tidy/ReleaseNotes/1_0_5.md
  Packs/Tidy/layoutscontainer/layoutscontainer-Tidy.json
  Packs/Tidy/pack_metadata.json
Labels: docs-approved, release-notes-only

#13185 unskip GSuiteAdmin TPB
  Packs/GSuiteAdmin/TestPlaybooks/playbook-GSuiteAdmin-Test.yml
  Tests/conf.json
Labels: docs-approved

#13183 Phishing campaign duration
  Packs/Campaign/ReleaseNotes/2_0_5.md
  Packs/Campaign/Scripts/FindEmailCampaign/FindEmailCampaign.py
  Packs/Campaign/Scripts/GetCampaignDuration/GetCampaignDuration.py
  Packs/Campaign/Scripts/GetCampaignDuration/GetCampaignDuration.yml
  Packs/Campaign/Scripts/GetCampaignDuration/GetCampaignDuration_test.py
  Packs/Campaign/pack_metadata.json
Labels: docs-approved

#13159 Fixing Signal Sciences - test playbook + code changes
  Packs/SignalSciences/Integrations/SignalSciences/SignalSciences.py
  Packs/SignalSciences/Integrations/SignalSciences/SignalSciences.yml
  Packs/SignalSciences/ReleaseNotes/1_0_2.md
  Packs/SignalSciences/TestPlaybooks/playbook-SignalSciencesTest.yml
  Packs/SignalSciences/pack_metadata.json
Labels: docs-approved

#13106 Update integration-Symantec_Messaging_Gateway_README.md
  Packs/Symantec_Messaging_Gateway/Integrations/integration-Symantec_Messaging_Gateway_README.md
Labels: docs-approved

#13199 fix widget duplicate id in Elasticsearch Monitoring
  Packs/ElasticsearchMonitoring/Dashboards/elasticsearch_monitoring.json
  Packs/ElasticsearchMonitoring/Widgets/widget-ElasticSearchCPUCurrentUsage.json
  Packs/ElasticsearchMonitoring/Widgets/widget-ElasticSearchDiskCurrentUsage.json
  Packs/ElasticsearchMonitoring/Widgets/widget-ElasticSearchJVMCurrentUsage.json
Labels: docs-approved

#13051 AWS - IAM remove integration from skipped
  Packs/AWS-IAM/TestPlaybooks/playbook-AWS-IAM-Test.yml
  Tests/conf.json
Labels: docs-approved

#13219 IF100 + pylint ignores
  Packs/Base/ReleaseNotes/1_12_9.md
  Packs/Base/Scripts/DBotTrainClustering/DBotTrainClustering.py
  Packs/Base/pack_metadata.json
  Packs/F5Silverline/.pack-ignore
Labels: docs-approved

#13220 O365 SC limitations
  Packs/EWS/Integrations/SecurityAndCompliance/README.md
  Packs/EWS/Playbooks/playbook-O365-SecurityAndCompliance-SearchAction-Delete_README.md
  Packs/EWS/Playbooks/playbook-O365-SecurityAndCompliance-SearchAction-Preview_README.md
  Packs/EWS/Playbooks/playbook-O365-SecurityAndCompliance-SearchAndDelete_README.md
  Packs/EWS/Playbooks/playbook-O365-SecurityAndCompliance-Search_README.md
  Packs/EWS/Playbooks/playbook-Office_365_Search_and_Delete_README.md
Labels: docs-approved
