Repository demisto/content, pull requests merged in 2021-09, with the labels that each got.

#13924 Bc support content side
  Tests/Marketplace/Tests/marketplace_services_test.py
  Tests/Marketplace/marketplace_services.py
  Tests/Marketplace/upload_packs.py
Labels: docs-approved

#14352 Azure ad graph fetch
  Packs/AzureActiveDirectory/Classifiers/classifier-Azure_Active_Directory_Identity_Protection_Classifier.json
  Packs/AzureActiveDirectory/Classifiers/classifier-mapping-incoming-Azure_Active_Directory_Identity_Protection-Incoming_Mapper.json
  Packs/AzureActiveDirectory/IncidentFields/incidentfield-Activity.json
  Packs/AzureActiveDirectory/IncidentFields/incidentfield-Alert_Type.json
  Packs/AzureActiveDirectory/IncidentFields/incidentfield-DetectedDateTime.json
  Packs/AzureActiveDirectory/IncidentFields/incidentfield-DetectionTimingType.json
  Packs/AzureActiveDirectory/IncidentFields/incidentfield-TokenIssuerType.json
  Packs/AzureActiveDirectory/IncidentTypes/incidenttype-AADIdentityProtectionRiskDetection.json
  Packs/AzureActiveDirectory/Integrations/AzureADIdentityProtection/AzureADIdentityProtection.py
  Packs/AzureActiveDirectory/Integrations/AzureADIdentityProtection/AzureADIdentityProtection.yml
  Packs/AzureActiveDirectory/Integrations/AzureADIdentityProtection/AzureADIdentityProtection_test.py
  Packs/AzureActiveDirectory/Integrations/AzureADIdentityProtection/test_data/incidents.json
  Packs/AzureActiveDirectory/Layouts/layoutscontainer-Azure_Active_Directory_Identity_Protection_Layout.json
  Packs/AzureActiveDirectory/ReleaseNotes/1_1_0.md
  Packs/AzureActiveDirectory/pack_metadata.json
  Packs/CommonTypes/IncidentFields/incidentfield-Last_Update_Time.json
  Packs/CommonTypes/IncidentFields/incidentfield-Location.json
  Packs/CommonTypes/IncidentFields/incidentfield-Location_Region.json
  Packs/CommonTypes/IncidentFields/incidentfield-Risk_Rating.json
  Packs/CommonTypes/IncidentFields/incidentfield-Subtype.json
  Packs/CommonTypes/IncidentFields/incidentfield-Username.json
  Packs/CommonTypes/ReleaseNotes/3_1_12.md
  Packs/CommonTypes/pack_metadata.json
Labels: docs-approved

#14622 Fireeye ETP - handle unicode chars
  Packs/FireEyeETP/Integrations/FireEyeETP/FireEyeETP.py
  Packs/FireEyeETP/Integrations/FireEyeETP/FireEyeETP_test.py
  Packs/FireEyeETP/ReleaseNotes/1_0_4.md
  Packs/FireEyeETP/pack_metadata.json
Labels: docs-approved, release-notes-only

#14625 Coverage enforce 2
  Utils/upload_code_coverage_report.py
Labels: docs-approved

#14431 SentinelOne V2
  Packs/SentinelOne/Integrations/SentinelOne-V2/SentinelOne-V2.py
  Packs/SentinelOne/Integrations/SentinelOne-V2/SentinelOne-V2.yml
  Packs/SentinelOne/ReleaseNotes/2_0_3.md
  Packs/SentinelOne/pack_metadata.json
Labels: Contribution, Partner, pending-demo, Contribution Form Filled

#14636 Improve stale branch deletion script
  Utils/github_workflow_scripts/delete_stale_non_contrib_branches.py
Labels: docs-approved

#14598 AlienVault OTX v2 - handle non lower-case URLs and insecure err msg
  Packs/AlienVault_OTX/Integrations/AlienVault_OTX_v2/AlienVault_OTX_v2.py
  Packs/AlienVault_OTX/Integrations/AlienVault_OTX_v2/AlienVault_OTX_v2_test.py
  Packs/AlienVault_OTX/Integrations/AlienVault_OTX_v2/README.md
  Packs/AlienVault_OTX/ReleaseNotes/1_1_8.md
  Packs/AlienVault_OTX/TestPlaybooks/playbook-Alienvault_OTX_v2-test.yml
  Packs/AlienVault_OTX/pack_metadata.json
Labels: docs-approved

#14381 Exabeam enhance
  Packs/Exabeam/Integrations/Exabeam/Exabeam.py
  Packs/Exabeam/Integrations/Exabeam/Exabeam.yml
  Packs/Exabeam/Integrations/Exabeam/Exabeam_test.py
  Packs/Exabeam/Integrations/Exabeam/test_data/response_constants.py
  Packs/Exabeam/Integrations/Exabeam/test_data/result_constants.py
  Packs/Exabeam/ReleaseNotes/2_1_4.md
  Packs/Exabeam/pack_metadata.json
Labels: docs-approved

#14624 Sophos Central - update RN
  Packs/SophosCentral/ReleaseNotes/1_0_6.md
Labels: docs-approved

#14643 Description Indicator Field - associated with missing types
  Packs/CommonTypes/IndicatorFields/incidentfield-description.json
  Packs/CommonTypes/ReleaseNotes/3_1_13.md
  Packs/CommonTypes/pack_metadata.json
Labels: docs-approved

#14642 Pop3 fix ssl default value
  Packs/MailListener_-_POP3/Integrations/MailListener_POP3/MailListener_POP3.yml
  Packs/MailListener_-_POP3/ReleaseNotes/1_0_5.md
  Packs/MailListener_-_POP3/pack_metadata.json
Labels: docs-approved

#14462 Autofocus url support and error suppression
  Packs/AutoFocus/Integrations/AutofocusV2/AutofocusV2.py
  Packs/AutoFocus/Integrations/AutofocusV2/AutofocusV2.yml
  Packs/AutoFocus/Integrations/AutofocusV2/AutofocusV2_test.py
  Packs/AutoFocus/Integrations/AutofocusV2/README.md
  Packs/AutoFocus/ReleaseNotes/1_3_7.md
  Packs/AutoFocus/ReleaseNotes/1_3_8.md
  Packs/AutoFocus/pack_metadata.json
  Tests/conf.json
Labels: docs-approved, release-notes-only

#14472 Campaign incident owners section
  Packs/Campaign/IncidentFields/incidentfield-Actions_On_Campaign_Incidents.json
  Packs/Campaign/ReleaseNotes/3_0_1.md
  Packs/Campaign/Scripts/PerformActionOnCampaignIncidents/PerformActionOnCampaignIncidents.py
  Packs/Campaign/Scripts/PerformActionOnCampaignIncidents/PerformActionOnCampaignIncidents.yml
  Packs/Campaign/Scripts/PerformActionOnCampaignIncidents/PerformActionOnCampaignIncidents_test.py
  Packs/Campaign/Scripts/ShowCampaignIncidentsOwners/ShowCampaignIncidentsOwners.py
  Packs/Campaign/Scripts/ShowCampaignIncidentsOwners/ShowCampaignIncidentsOwners.yml
  Packs/Campaign/Scripts/ShowCampaignIncidentsOwners/ShowCampaignIncidentsOwners_test.py
  Packs/Campaign/pack_metadata.json
Labels: docs-approved

#14617 Prisma Saas Security
  Packs/CommonTypes/IncidentFields/incidentfield-Close_Time.json
  Packs/CommonTypes/IncidentFields/incidentfield-Exposure_Level.json
  Packs/CommonTypes/IncidentFields/incidentfield-Item_Owner.json
  Packs/CommonTypes/IncidentFields/incidentfield-Item_Owner_Email.json
  Packs/CommonTypes/IncidentFields/incidentfield-Last_Update_Time.json
  Packs/CommonTypes/IncidentFields/incidentfield-Policy_Details.json
  Packs/CommonTypes/IncidentFields/incidentfield-Policy_ID.json
  Packs/CommonTypes/IncidentFields/incidentfield-Policy_URI.json
  Packs/CommonTypes/ReleaseNotes/3_1_15.md
  Packs/CommonTypes/pack_metadata.json
  Packs/PrismaSaasSecurity/.pack-ignore
  Packs/PrismaSaasSecurity/.secrets-ignore
  Packs/PrismaSaasSecurity/Classifiers/classifier-Saas_Security_-_Incoming_Mapper.json
  Packs/PrismaSaasSecurity/IncidentTypes/incidenttype-Saas_Security.json
  Packs/PrismaSaasSecurity/Integrations/SaasSecurity/Pipfile
  Packs/PrismaSaasSecurity/Integrations/SaasSecurity/Pipfile.lock
  Packs/PrismaSaasSecurity/Integrations/SaasSecurity/README.md
  Packs/PrismaSaasSecurity/Integrations/SaasSecurity/SaasSecurity.py
  Packs/PrismaSaasSecurity/Integrations/SaasSecurity/SaasSecurity.yml
  Packs/PrismaSaasSecurity/Integrations/SaasSecurity/SaasSecurity_description.md
  Packs/PrismaSaasSecurity/Integrations/SaasSecurity/SaasSecurity_image.png
  Packs/PrismaSaasSecurity/Integrations/SaasSecurity/SaasSecurity_test.py
  Packs/PrismaSaasSecurity/Integrations/SaasSecurity/command_examples
  Packs/PrismaSaasSecurity/Integrations/SaasSecurity/test_data/fech_incident_data.json
  Packs/PrismaSaasSecurity/Integrations/SaasSecurity/test_data/get-apps.json
  Packs/PrismaSaasSecurity/Integrations/SaasSecurity/test_data/get-asset-remediation-status.json
  Packs/PrismaSaasSecurity/Integrations/SaasSecurity/test_data/get-incident-by-id.json
  Packs/PrismaSaasSecurity/Integrations/SaasSecurity/test_data/get-incidents.json
  Packs/PrismaSaasSecurity/Integrations/SaasSecurity/test_data/update-incident-status.json
  Packs/PrismaSaasSecurity/Layouts/layoutscontainer-Saas_Security_Layout.json
  Packs/PrismaSaasSecurity/Playbooks/Saas_Security_-_Remediate_an_asset.yml
  Packs/PrismaSaasSecurity/Playbooks/Saas_Security_-_Remediate_an_asset_README.md
  Packs/PrismaSaasSecurity/README.md
  Packs/PrismaSaasSecurity/TestPlaybooks/SaasSecurity-Test.yml
  Packs/PrismaSaasSecurity/doc_files/Saas_Security_-_Remediate_an_asset.png
  Packs/PrismaSaasSecurity/doc_files/Sass_Security_layout.png
  Packs/PrismaSaasSecurity/pack_metadata.json
  Tests/conf.json
Labels: docs-approved

#14138 Adding table border in the tableToHTML func
  Packs/Base/ReleaseNotes/1_13_18.md
  Packs/Base/ReleaseNotes/1_13_29.md
  Packs/Base/Scripts/script-CommonServer.yml
  Packs/Base/pack_metadata.json
Labels: docs-approved

#14621 bump 21.8.2
  .circleci/content_release_vars.sh
Labels: docs-approved

#14641 Cdl args fix
  Packs/CortexDataLake/Integrations/CortexDataLake/CortexDataLake.yml
  Packs/CortexDataLake/ReleaseNotes/1_3_4.md
  Packs/CortexDataLake/pack_metadata.json
Labels: docs-approved

#14584 Remove redundant private packs log from upload flow
  Tests/Marketplace/upload_packs.py
Labels: docs-approved

#14654 Deprecate MISP V2
  Packs/MISP/.pack-ignore
  Packs/MISP/Integrations/MISP_V2/MISP_V2.yml
  Packs/MISP/ReleaseNotes/2_0_1.md
  Packs/MISP/pack_metadata.json
  Tests/conf.json
Labels: docs-approved

#14655 XFE - handle file with no family
  Packs/XForceExchange/Integrations/XFE_v2/XFE_v2.py
  Packs/XForceExchange/Integrations/XFE_v2/XFE_v2.yml
  Packs/XForceExchange/Integrations/XFE_v2/XFE_v2_test.py
  Packs/XForceExchange/ReleaseNotes/1_1_7.md
  Packs/XForceExchange/pack_metadata.json
Labels: docs-approved, release-notes-only

#14567 ParseEmailFiles: Do not decode attachments
  Packs/CommonScripts/ReleaseNotes/1_4_30.md
  Packs/CommonScripts/Scripts/ParseEmailFiles/ParseEmailFiles.py
  Packs/CommonScripts/Scripts/ParseEmailFiles/ParseEmailFiles.yml
  Packs/CommonScripts/Scripts/ParseEmailFiles/ParseEmailFiles_test.py
  Packs/CommonScripts/pack_metadata.json
Labels: docs-approved, release-notes-only

#14653 Loadjson strict
  Packs/CommonScripts/ReleaseNotes/1_4_31.md
  Packs/CommonScripts/Scripts/LoadJSON/LoadJSON.py
  Packs/CommonScripts/Scripts/LoadJSON/LoadJSON.yml
  Packs/CommonScripts/Scripts/LoadJSON/LoadJSON_test.py
  Packs/CommonScripts/Scripts/LoadJSON/Pipfile
  Packs/CommonScripts/Scripts/LoadJSON/Pipfile.lock
  Packs/CommonScripts/Scripts/LoadJSON/README.md
  Packs/CommonScripts/pack_metadata.json
Labels: docs-approved, release-notes-only

#14315 XDR fixes - Port scan alerts
  Packs/CortexXDR/Playbooks/Cortex_XDR_Alerts_Handling.yml
  Packs/CortexXDR/Playbooks/Cortex_XDR_Alerts_Handling_README.md
  Packs/CortexXDR/ReleaseNotes/3_0_27.md
  Packs/CortexXDR/pack_metadata.json
Labels: docs-approved

#14709 Tor Feed Delete Name Indicator Field
  Packs/FeedTorExitAddresses/Integrations/FeedTorExitAddresses/FeedTorExitAddresses.py
  Packs/FeedTorExitAddresses/Integrations/FeedTorExitAddresses/FeedTorExitAddresses.yml
  Packs/FeedTorExitAddresses/ReleaseNotes/1_0_4.md
  Packs/FeedTorExitAddresses/pack_metadata.json
Labels: docs-approved, release-notes-only

#14640 fixed a litle bug in Fetch Incidents test playbook
  Packs/DeveloperTools/TestPlaybooks/playbook-Fetch_Incidents_Test.yml
Labels: docs-approved

#14577 Workday IAM - TUFE and AD Deactivation
  Packs/Workday/Classifiers/classifier-IAM_Sync_User_-_Workday.json
  Packs/Workday/Integrations/Workday_IAM/Workday_IAM.py
  Packs/Workday/Integrations/Workday_IAM/Workday_IAM.yml
  Packs/Workday/Integrations/Workday_IAM/Workday_IAM_test.py
  Packs/Workday/ReleaseNotes/1_2_3.md
  Packs/Workday/pack_metadata.json
Labels: docs-approved

#14647 AD IAM fixes
  Packs/Active_Directory_Query/Integrations/Active_Directory_Query/Active_Directory_Query.py
  Packs/Active_Directory_Query/ReleaseNotes/1_3_2.md
  Packs/Active_Directory_Query/pack_metadata.json
Labels: docs-approved

#14639 Checkpoint FWv2: Improved login mechanism
  Packs/CheckpointFirewall/Integrations/CheckPointFirewallV2/CheckPointFirewallV2.py
  Packs/CheckpointFirewall/Integrations/CheckPointFirewallV2/CheckPointFirewallV2.yml
  Packs/CheckpointFirewall/Integrations/CheckPointFirewallV2/CheckPointFirewallV2_test.py
  Packs/CheckpointFirewall/ReleaseNotes/2_1_1.md
  Packs/CheckpointFirewall/pack_metadata.json
Labels: docs-approved

#14723 TrendMicro DDA - replace risklevel direct key access with get
  Packs/TrendMicroDDA/Integrations/integration-TrendMicroDDA.yml
  Packs/TrendMicroDDA/ReleaseNotes/1_0_3.md
  Packs/TrendMicroDDA/pack_metadata.json
Labels: bug, docs-approved

#14593 Attivo Pack adoption
  Packs/AttivoBotsink/README.md
  Packs/AttivoBotsink/ReleaseNotes/1_0_3.md
  Packs/AttivoBotsink/pack_metadata.json
Labels: Contribution, docs-approved, Partner, Contribution Form Filled

#14518 Rss widget updates
  Packs/CommonWidgets/ReleaseNotes/1_1_3.md
  Packs/CommonWidgets/Scripts/RSSWidget/README.md
  Packs/CommonWidgets/Scripts/RSSWidget/RSSWidget.py
  Packs/CommonWidgets/Scripts/RSSWidget/RSSWidget.yml
  Packs/CommonWidgets/Scripts/RSSWidget/RSSWidget_test.py
  Packs/CommonWidgets/Scripts/RSSWidget/test_data/test_variables.py
  Packs/CommonWidgets/pack_metadata.json
Labels: docs-approved

#14535 Unescape urls extract email v2
  Packs/Base/TestPlaybooks/playbook-Indicators-reputation-.json-Test.yml
  Packs/CommonScripts/ReleaseNotes/1_4_32.md
  Packs/CommonScripts/Scripts/ExtractEmailFormatting/ExtractEmailFormatting.py
  Packs/CommonScripts/Scripts/ExtractEmailFormatting/ExtractEmailFormatting.yml
  Packs/CommonScripts/Scripts/ExtractEmailFormatting/ExtractEmailFormatting_test.py
  Packs/CommonScripts/Scripts/script-UnEscapeURLs.yml
  Packs/CommonScripts/TestPlaybooks/playbook-UnEscapeURLs-Test.yml
  Packs/CommonScripts/pack_metadata.json
  Packs/CommonTypes/IndicatorTypes/reputation-email.json
  Packs/CommonTypes/ReleaseNotes/3_1_16.md
  Packs/CommonTypes/pack_metadata.json
Labels: docs-approved

#14708 MISP V3 - add TPB
  Packs/MISP/Integrations/MISPV3/MISPV3.yml
  Packs/MISP/ReleaseNotes/2_0_2.md
  Packs/MISP/pack_metadata.json
  Tests/conf.json
Labels: docs-approved

#14656 Autofocus param
  Packs/AutoFocus/Integrations/AutofocusV2/AutofocusV2.yml
  Packs/AutoFocus/ReleaseNotes/1_3_9.md
  Packs/AutoFocus/pack_metadata.json
Labels: docs-approved

#14176 GitLab Job to Delete Branches Already Deleted from Github
  .gitlab/ci/.gitlab-ci.yml
  .gitlab/ci/miscellaneous.yml
  Utils/delete_mismatched_branches.py
Labels: docs-approved

#14750 QRadar v3 Add More Log Msgs
  Packs/QRadar/Integrations/QRadar_v3/QRadar_v3.py
  Packs/QRadar/Integrations/QRadar_v3/QRadar_v3.yml
  Packs/QRadar/ReleaseNotes/2_0_23.md
  Packs/QRadar/pack_metadata.json
Labels: docs-approved

#14710 Sixgill name field Move To Tags
  Packs/Sixgill-Darkfeed/Integrations/Sixgill_Darkfeed/Sixgill_Darkfeed.py
  Packs/Sixgill-Darkfeed/Integrations/Sixgill_Darkfeed/Sixgill_Darkfeed_test.py
  Packs/Sixgill-Darkfeed/ReleaseNotes/2_0_5.md
  Packs/Sixgill-Darkfeed/pack_metadata.json
Labels: docs-approved

#14486 Archer v2 - edited adding an api endpoint
  Packs/ArcherRSA/Integrations/ArcherV2/ArcherV2.py
  Packs/ArcherRSA/Integrations/ArcherV2/ArcherV2.yml
  Packs/ArcherRSA/Integrations/ArcherV2/README.md
  Packs/ArcherRSA/ReleaseNotes/1_1_22.md
  Packs/ArcherRSA/pack_metadata.json
Labels: bug, docs-approved, release-notes-only

#14575 Set dockerimage carbon black
  Packs/CarbonBlackProtect/ReleaseNotes/1_0_9.md
  Packs/CarbonBlackProtect/Scripts/script-CBPApproveHash.yml
  Packs/CarbonBlackProtect/Scripts/script-CBPBanHash.yml
  Packs/CarbonBlackProtect/Scripts/script-CBPCatalogFindHash.yml
  Packs/CarbonBlackProtect/Scripts/script-CBPFindComputer.yml
  Packs/CarbonBlackProtect/Scripts/script-CBPFindRule.yml
  Packs/CarbonBlackProtect/pack_metadata.json
Labels: docs-approved

#14573 Recommendation to use v2 Feeds
  Packs/FeedMitreAttack/README.md
  Packs/FeedUnit42/README.md
  Packs/FeedUnit42v2/Integrations/FeedUnit42v2/FeedUnit42v2.yml
  Packs/FeedUnit42v2/Integrations/FeedUnit42v2/README.md
  Packs/FeedUnit42v2/ReleaseNotes/1_0_3.md
  Packs/FeedUnit42v2/pack_metadata.json
Labels: docs-approved

#14754 ParseEmailFiles fails on demisto.debug line
  Packs/CommonScripts/.secrets-ignore
  Packs/CommonScripts/ReleaseNotes/1_4_33.md
  Packs/CommonScripts/Scripts/ParseEmailFiles/ParseEmailFiles.py
  Packs/CommonScripts/Scripts/ParseEmailFiles/ParseEmailFiles.yml
  Packs/CommonScripts/Scripts/ParseEmailFiles/ParseEmailFiles_test.py
  Packs/CommonScripts/Scripts/ParseEmailFiles/test_data/test-subject-raised-error-on-log.eml
  Packs/CommonScripts/TestPlaybooks/playbook-ParseEmailFiles-test.yml
  Packs/CommonScripts/pack_metadata.json
Labels: bug, docs-approved, release-notes-only

#14711 CrowdStrike API Module - extract server_url from the params obj
  Packs/ApiModules/Scripts/CrowdStrikeApiModule/CrowdStrikeApiModule.py
  Packs/ApiModules/Scripts/CrowdStrikeApiModule/CrowdStrikeApiModule.yml
  Packs/CrowdStrikeIntel/ReleaseNotes/2_0_11.md
  Packs/CrowdStrikeIntel/pack_metadata.json
  Packs/CrowdStrikeOpenAPI/ReleaseNotes/1_0_2.md
  Packs/CrowdStrikeOpenAPI/pack_metadata.json
  Packs/FeedCrowdstrikeFalconIntel/Integrations/CrowdStrikeIndicatorFeed/CrowdStrikeIndicatorFeed.yml
  Packs/FeedCrowdstrikeFalconIntel/ReleaseNotes/2_0_5.md
  Packs/FeedCrowdstrikeFalconIntel/pack_metadata.json
Labels: docs-approved, release-notes-only

#14443 AWS GuardDuty - handle datetime in finding obj serialization
  Packs/AWS-GuardDuty/Integrations/AWSGuardDuty/AWSGuardDuty.py
  Packs/AWS-GuardDuty/Integrations/AWSGuardDuty/AWSGuardDuty_test.py
  Packs/AWS-GuardDuty/ReleaseNotes/1_1_4.md
  Packs/AWS-GuardDuty/pack_metadata.json
Labels: docs-approved

#14782 Cisco Umbrella Investigate - fix isarray for domain arg
  Packs/Cisco-umbrella/Integrations/Cisco-umbrella-investigate/Cisco-umbrella-investigate.yml
  Packs/Cisco-umbrella/ReleaseNotes/1_0_7.md
  Packs/Cisco-umbrella/pack_metadata.json
  Tests/conf.json
Labels: docs-approved

#14783 AWS Access Analyzer Documentation
  Packs/AWS-AccessAnalyzer/.secrets-ignore
  Packs/AWS-AccessAnalyzer/Integrations/AWS-AccessAnalyzer/README.md
Labels: docs-approved

#14175 Contributing Thales (SafeNet Trusted Access) Pack
  Packs/SafeNet_Trusted_Access/.pack-ignore
  Packs/SafeNet_Trusted_Access/.secrets-ignore
  Packs/SafeNet_Trusted_Access/Author_image.png
  Packs/SafeNet_Trusted_Access/Classifiers/classifier-SafeNet_Trusted_Access_–_Push_Reject_Alert_Classifier.json
  Packs/SafeNet_Trusted_Access/Classifiers/classifier-SafeNet_Trusted_Access_–_Push_Reject_Alert_Mapper.json
  Packs/SafeNet_Trusted_Access/IncidentFields/incidentfield-SafeNet_Trusted_Access_-_Instance_Name.json
  Packs/SafeNet_Trusted_Access/IncidentFields/incidentfield-SafeNet_Trusted_Access_-_Remove_User_from_Unusual_Activity_Group.json
  Packs/SafeNet_Trusted_Access/IncidentFields/incidentfield-SafeNet_Trusted_Access_-_Unusual_Activity_Group.json
  Packs/SafeNet_Trusted_Access/IncidentFields/incidentfield-SafeNet_Trusted_Access_-_User_in_Unusual_Activity_Group_Hours.json
  Packs/SafeNet_Trusted_Access/IncidentFields/incidentfield-SafeNet_Trusted_Access_-_Username.json
  Packs/SafeNet_Trusted_Access/IncidentTypes/incidenttype-SafeNet_Trusted_Access_Alert.json
  Packs/SafeNet_Trusted_Access/Integrations/SafeNetTrustedAccess/README.md
  Packs/SafeNet_Trusted_Access/Integrations/SafeNetTrustedAccess/SafeNetTrustedAccess.py
  Packs/SafeNet_Trusted_Access/Integrations/SafeNetTrustedAccess/SafeNetTrustedAccess.yml
  Packs/SafeNet_Trusted_Access/Integrations/SafeNetTrustedAccess/SafeNetTrustedAccess_description.md
  Packs/SafeNet_Trusted_Access/Integrations/SafeNetTrustedAccess/SafeNetTrustedAccess_image.png
  Packs/SafeNet_Trusted_Access/Integrations/SafeNetTrustedAccess/SafeNetTrustedAccess_test.py
  Packs/SafeNet_Trusted_Access/Integrations/SafeNetTrustedAccess/command_examples.txt
  Packs/SafeNet_Trusted_Access/Layouts/layoutscontainer-SafeNet_Trusted_Access_-_Incident_Layout.json
  Packs/SafeNet_Trusted_Access/Playbooks/SafeNet_Trusted_Access_Add_to_Unusual_Activity_Group_README.md
  Packs/SafeNet_Trusted_Access/Playbooks/SafeNet_Trusted_Access_–_Add_to_Unusual_Activity_Group.yml
  Packs/SafeNet_Trusted_Access/Playbooks/doc_files/SafeNet_Trusted_Access_Add_to_Unusual_Activity_Group.png
  Packs/SafeNet_Trusted_Access/README.md
  Packs/SafeNet_Trusted_Access/Scripts/STAFetchListContent/README.md
  Packs/SafeNet_Trusted_Access/Scripts/STAFetchListContent/STAFetchListContent.py
  Packs/SafeNet_Trusted_Access/Scripts/STAFetchListContent/STAFetchListContent.yml
  Packs/SafeNet_Trusted_Access/Scripts/STAFetchListContent/STAFetchListContent_test.py
  Packs/SafeNet_Trusted_Access/Scripts/STAPostProcessing/README.md
  Packs/SafeNet_Trusted_Access/Scripts/STAPostProcessing/STAPostProcessing.py
  Packs/SafeNet_Trusted_Access/Scripts/STAPostProcessing/STAPostProcessing.yml
  Packs/SafeNet_Trusted_Access/Scripts/STAPostProcessing/STAPostProcessing_test.py
  Packs/SafeNet_Trusted_Access/TestPlaybooks/Test_Playbook_STA.yml
  Packs/SafeNet_Trusted_Access/pack_metadata.json
  Tests/conf.json
Labels: Contribution, docs-approved, Partner, post-demo, Contribution Form Filled

#14787 SDKNightlyFailureSkipTest
  Tests/scripts/infrastructure_tests/test_collect_tests_and_content_packs.py
Labels: docs-approved

#14778 Fixed an issue where proxy settings haven't been given in BasicClient.
  Packs/FeedUnit42/Integrations/FeedUnit42/FeedUnit42.py
  Packs/FeedUnit42/ReleaseNotes/1_1_3.md
  Packs/FeedUnit42/pack_metadata.json
Labels: Contribution, docs-approved, Contribution Form Filled, Community

#14788 RedLock fetch-incidents using Policy Name filter
  Packs/PrismaCloud/Integrations/RedLock/README.md
  Packs/PrismaCloud/Integrations/RedLock/RedLock.py
  Packs/PrismaCloud/Integrations/RedLock/RedLock.yml
  Packs/PrismaCloud/ReleaseNotes/1_9_1.md
  Packs/PrismaCloud/pack_metadata.json
Labels: docs-approved

#14458 Add shodan v2 documentation
  Packs/Shodan/Integrations/Shodan_v2/README.md
  Packs/Shodan/Integrations/Shodan_v2/commands.txt
Labels: docs-approved

#14067 Campaign script docker update
  Packs/Campaign/ReleaseNotes/3_0_2.md
  Packs/Campaign/Scripts/FindEmailCampaign/FindEmailCampaign.yml
  Packs/Campaign/Scripts/FindEmailCampaign/README.md
  Packs/Campaign/pack_metadata.json
Labels: docs-approved

#14652 PAN-OS - Added support for multiple services in the ***panorama-creat…
  Packs/PAN-OS/Integrations/Panorama/Panorama.py
  Packs/PAN-OS/Integrations/Panorama/Panorama.yml
  Packs/PAN-OS/Integrations/Panorama/README.md
  Packs/PAN-OS/ReleaseNotes/1_6_28.md
  Packs/PAN-OS/TestPlaybooks/playbook-palo_alto_firewall_test_pb.yml
  Packs/PAN-OS/pack_metadata.json
Labels: docs-approved

#14794 Remove Log Statement From BC Version
  Tests/Marketplace/marketplace_services.py
Labels: docs-approved

#14752 Graph Security - handle status update limited providers
  Packs/MicrosoftGraphSecurity/Integrations/MicrosoftGraphSecurity/MicrosoftGraphSecurity.py
  Packs/MicrosoftGraphSecurity/Integrations/MicrosoftGraphSecurity/README.md
  Packs/MicrosoftGraphSecurity/ReleaseNotes/2_0_13.md
  Packs/MicrosoftGraphSecurity/pack_metadata.json
Labels: docs-approved

#14800 SafeNet - add secret ignore
  Packs/SafeNet_Trusted_Access/.secrets-ignore
Labels: docs-approved

#14457 Qradar full search v3
  Packs/QRadar/Playbooks/playbook-QRadarFullSearch.yml
  Packs/QRadar/Playbooks/playbook-QRadarFullSearch_README.md
  Packs/QRadar/ReleaseNotes/2_0_24.md
  Packs/QRadar/doc_files/QRadarFullSearch.png
  Packs/QRadar/pack_metadata.json
Labels: docs-approved

#14539 Freshdesk - handle unicode in subject
  Packs/FreshDesk/Integrations/FreshDesk/FreshDesk.py
  Packs/FreshDesk/Integrations/FreshDesk/FreshDesk.yml
  Packs/FreshDesk/Integrations/FreshDesk/FreshDesk_test.py
  Packs/FreshDesk/ReleaseNotes/1_0_5.md
  Packs/FreshDesk/pack_metadata.json
Labels: docs-approved, release-notes-only

#14804 updated Shodan v2 README
  Packs/Shodan/Integrations/Shodan_v2/README.md
Labels: docs-approved

#14793 A slight improvement in memory consumption while training a phishing classifier
  Packs/Base/ReleaseNotes/1_13_30.md
  Packs/Base/Scripts/DBotTrainTextClassifierV2/DBotTrainTextClassifierV2.py
  Packs/Base/pack_metadata.json
Labels: docs-approved

#14812 AD - iam-update-user fix
  Packs/Active_Directory_Query/Integrations/Active_Directory_Query/Active_Directory_Query.py
  Packs/Active_Directory_Query/ReleaseNotes/1_3_4.md
  Packs/Active_Directory_Query/pack_metadata.json
Labels: docs-approved

#14816 Update RSS Widget readme example links
  Packs/CommonWidgets/Scripts/RSSWidget/README.md
Labels: Contribution, docs-approved, Contribution Form Filled, Community

#14497 Oracle oci iam
  Packs/IAM-SCIM/Classifiers/classifier-User_Profile_-_SCIM_(Outgoing).json
  Packs/IAM-SCIM/ReleaseNotes/1_1_1.md
  Packs/IAM-SCIM/pack_metadata.json
  Packs/Oracle_IAM/.pack-ignore
  Packs/Oracle_IAM/.secrets-ignore
  Packs/Oracle_IAM/Integrations/OracleIAM/OracleIAM.py
  Packs/Oracle_IAM/Integrations/OracleIAM/OracleIAM.yml
  Packs/Oracle_IAM/Integrations/OracleIAM/OracleIAM_description.md
  Packs/Oracle_IAM/Integrations/OracleIAM/OracleIAM_image.png
  Packs/Oracle_IAM/Integrations/OracleIAM/OracleIAM_test.py
  Packs/Oracle_IAM/Integrations/OracleIAM/Pipfile
  Packs/Oracle_IAM/Integrations/OracleIAM/Pipfile.lock
  Packs/Oracle_IAM/Integrations/OracleIAM/README.md
  Packs/Oracle_IAM/Integrations/OracleIAM/command_examples
  Packs/Oracle_IAM/README.md
  Packs/Oracle_IAM/pack_metadata.json
Labels: docs-approved, IAM

#14797 Close Gold job
  Packs/ContentManagement/Playbooks/playbook-Configuration_Setup.yml
  Packs/ContentManagement/ReleaseNotes/1_0_4.md
  Packs/ContentManagement/pack_metadata.json
Labels: docs-approved, release-notes-only

#14786 Fixed an issue where proxy settings haven't been given in BasicClient.
  Packs/FeedUnit42v2/Integrations/FeedUnit42v2/FeedUnit42v2.py
  Packs/FeedUnit42v2/ReleaseNotes/1_0_4.md
  Packs/FeedUnit42v2/pack_metadata.json
Labels: Contribution, Contribution Form Filled, Community

#14791 RF Feed Bug
  Packs/FeedRecordedFuture/Integrations/FeedRecordedFuture/FeedRecordedFuture.py
  Packs/FeedRecordedFuture/Integrations/FeedRecordedFuture/FeedRecordedFuture.yml
  Packs/FeedRecordedFuture/Integrations/FeedRecordedFuture/FeedRecordedFuture_description.md
  Packs/FeedRecordedFuture/Integrations/FeedRecordedFuture/FeedRecordedFuture_test.py
  Packs/FeedRecordedFuture/Integrations/FeedRecordedFuture/README.md
  Packs/FeedRecordedFuture/Integrations/FeedRecordedFuture/test_data/response.txt
  Packs/FeedRecordedFuture/ReleaseNotes/1_0_14.md
  Packs/FeedRecordedFuture/pack_metadata.json
Labels: docs-approved, release-notes-only

#14833 Increase Log Level Of Skipped Tests Via Pack Ignore
  Tests/scripts/collect_tests_and_content_packs.py
  Tests/scripts/infrastructure_tests/test_collect_tests_and_content_packs.py
Labels: docs-approved

#13823 add arcusteam pack
  Packs/ArcusTeam/.pack-ignore
  Packs/ArcusTeam/.secrets-ignore
  Packs/ArcusTeam/Integrations/ArcusTeam/ArcusTeam.py
  Packs/ArcusTeam/Integrations/ArcusTeam/ArcusTeam.yml
  Packs/ArcusTeam/Integrations/ArcusTeam/ArcusTeam_description.md
  Packs/ArcusTeam/Integrations/ArcusTeam/ArcusTeam_image.png
  Packs/ArcusTeam/Integrations/ArcusTeam/Pipfile
  Packs/ArcusTeam/Integrations/ArcusTeam/Pipfile.lock
  Packs/ArcusTeam/Integrations/ArcusTeam/README.md
  Packs/ArcusTeam/Integrations/ArcusTeam/command_examples
  Packs/ArcusTeam/README.md
  Packs/ArcusTeam/pack_metadata.json
Labels: Contribution, docs-approved, Partner, Contribution Form Filled

#14822 BaseClient - improve if session exist check in del
  Packs/Base/ReleaseNotes/1_13_31.md
  Packs/Base/Scripts/CommonServerPython/CommonServerPython.py
  Packs/Base/Scripts/CommonServerPython/CommonServerPython.yml
  Packs/Base/pack_metadata.json
  Packs/DeveloperTools/TestPlaybooks/playbook-TestCommonPython.yml
  Packs/DeveloperTools/TestPlaybooks/script-TestPyCommonServer.yml
Labels: docs-approved

#14851 New pack for CVE-2021-40444 - MSHTML RCE
  Packs/CVE_2021_40444/.pack-ignore
  Packs/CVE_2021_40444/.secrets-ignore
  Packs/CVE_2021_40444/Playbooks/playbook-CVE-2021-40444_-_MSHTML_RCE.yml
  Packs/CVE_2021_40444/Playbooks/playbook-CVE-2021-40444_-_MSHTML_RCE_README.md
  Packs/CVE_2021_40444/README.md
  Packs/CVE_2021_40444/doc_files/CVE-2021-40444_-_MSHTML_RCE.png
  Packs/CVE_2021_40444/pack_metadata.json
Labels: docs-approved

#14852 add to ignore
  Packs/CVE_2021_40444/.secrets-ignore
Labels: docs-approved

#14836 [Test Fix] EWS O365
  Packs/EWS/TestPlaybooks/playbook-EWS_O365_test.yml
Labels: docs-approved

#14861 Added memory_threshold to MITRE v2
  Tests/conf.json
Labels: docs-approved

#14688 Pa wildfire enhancement
  Packs/Palo_Alto_Networks_WildFire/Playbooks/playbook-Detonate_File_-_WildFire.yml
  Packs/Palo_Alto_Networks_WildFire/Playbooks/playbook-Detonate_File_-_WildFire_README.md
  Packs/Palo_Alto_Networks_WildFire/ReleaseNotes/1_4_1.md
  Packs/Palo_Alto_Networks_WildFire/pack_metadata.json
Labels: docs-approved

#14809 O365 Outlook Mail - add timeout param
  Packs/ApiModules/Scripts/MicrosoftApiModule/MicrosoftApiModule.py
  Packs/MicrosoftGraphMail/Integrations/MicrosoftGraphMail/MicrosoftGraphMail.py
  Packs/MicrosoftGraphMail/Integrations/MicrosoftGraphMail/MicrosoftGraphMail.yml
  Packs/MicrosoftGraphMail/Integrations/MicrosoftGraphMail/README.md
  Packs/MicrosoftGraphMail/ReleaseNotes/1_0_24.md
  Packs/MicrosoftGraphMail/pack_metadata.json
Labels: docs-approved

#14805 Update content repository to correlate scripts ids new validation
  Packs/Campaign/IncidentFields/incidentfield-Incidents_Info.json
  Packs/Campaign/ReleaseNotes/3_0_3.md
  Packs/Campaign/pack_metadata.json
  Packs/Confluera/Layouts/layoutscontainer-Confluera_Layout.json
  Packs/Confluera/ReleaseNotes/1_0_4.md
  Packs/Confluera/pack_metadata.json
  Packs/NCSCCyberAsssessmentFramework/Layouts/layoutscontainer-NCSC_CAF_Assessment.json
  Packs/NCSCCyberAsssessmentFramework/ReleaseNotes/1_0_2.md
  Packs/NCSCCyberAsssessmentFramework/pack_metadata.json
  Packs/Pcysys/Layouts/layout-details-Pentera_Insight.json
  Packs/Pcysys/Layouts/layoutscontainer-Pentera_Insight.json
  Packs/Pcysys/ReleaseNotes/1_3_1.md
  Packs/Pcysys/pack_metadata.json
  Packs/Ransomware/IncidentFields/incidentfield-Ransomware_Approximate_Number_Of_Encrypted_Endpoints.json
  Packs/Ransomware/ReleaseNotes/1_0_5.md
  Packs/Ransomware/pack_metadata.json
Labels: docs-approved, release-notes-only

#14874 bump(docker): bump docker version
  Packs/Intezer/Integrations/IntezerV2/IntezerV2.yml
  Packs/Intezer/ReleaseNotes/1_2_3.md
  Packs/Intezer/pack_metadata.json
Labels: Contribution, docs-approved, Partner, Contribution Form Filled

#14846 Delete wrong script id from ironscales's incident field to correalte scripts ids new validation
  Packs/Ironscales/IncidentFields/incidentfield-Ironscales-Resolver-email-address.json
  Packs/Ironscales/ReleaseNotes/1_0_2.md
  Packs/Ironscales/pack_metadata.json
Labels: docs-approved

#14570 Allow ignoring test playbooks for different packs
  Tests/scripts/collect_tests_and_content_packs.py
  Tests/scripts/infrastructure_tests/test_collect_tests_and_content_packs.py
  dev-requirements-py3.txt
Labels: docs-approved

#14712 Auto update docker image false for taxi
  Packs/FeedMitreAttack/Integrations/FeedMitreAttack/FeedMitreAttack.yml
  Packs/FeedMitreAttack/ReleaseNotes/1_1_15.md
  Packs/FeedMitreAttack/pack_metadata.json
  Packs/FeedTAXII/Integrations/FeedTAXII2/FeedTAXII2.yml
  Packs/FeedTAXII/ReleaseNotes/1_0_11.md
  Packs/FeedTAXII/pack_metadata.json
Labels: docs-approved

#14879 Thales-SafeNet_Trusted_Access(STA)
  Packs/SafeNet_Trusted_Access/Integrations/SafeNetTrustedAccess/README.md
  Packs/SafeNet_Trusted_Access/Layouts/layoutscontainer-SafeNet_Trusted_Access_-_Incident_Layout.json
  Packs/SafeNet_Trusted_Access/Playbooks/SafeNet_Trusted_Access_–_Add_to_Unusual_Activity_Group.yml
  Packs/SafeNet_Trusted_Access/ReleaseNotes/1_0_1.md
  Packs/SafeNet_Trusted_Access/pack_metadata.json
Labels: Contribution, docs-approved, Partner, Contribution Form Filled

#14887 Update SetGridField CODEOWNERS
  .github/CODEOWNERS
Labels: docs-approved

#14886 Fix Recorded Feed Description Recommended Interval Fetch Grid
  Packs/FeedRecordedFuture/Integrations/FeedRecordedFuture/FeedRecordedFuture_description.md
  Packs/FeedRecordedFuture/ReleaseNotes/1_0_15.md
  Packs/FeedRecordedFuture/pack_metadata.json
Labels: docs-approved

#14436 Added File Enrichment - VMRay playbook
  Packs/VMRay/Integrations/VMRay/README.md
  Packs/VMRay/Integrations/VMRay/VMRay.py
  Packs/VMRay/Integrations/VMRay/VMRay.yml
  Packs/VMRay/Playbooks/playbook-VMRay-File-Enrichment.yml
  Packs/VMRay/Playbooks/playbook-VMRay-File-Enrichment_README.md
  Packs/VMRay/ReleaseNotes/1_1_1.md
  Packs/VMRay/ReleaseNotes/1_1_2.md
  Packs/VMRay/TestPlaybooks/playbook-VMRay-test-File-Enrichment.yml
  Packs/VMRay/pack_metadata.json
  docs/images/playbooks/File_Enrichment_VMRay.png
Labels: Contribution, Partner, Contribution Form Filled

#13397 VerifyIPv6Indicator - add hypothesis valid ipv6 test
  .gitignore
  Packs/CommonScripts/Scripts/VerifyIPv6Indicator/Pipfile
  Packs/CommonScripts/Scripts/VerifyIPv6Indicator/Pipfile.lock
  Packs/CommonScripts/Scripts/VerifyIPv6Indicator/VerifyIPv6Indicator_test.py
Labels: docs-approved

#14892 Auto Update Docker False Mitre V2
  Packs/FeedMitreAttackv2/Integrations/FeedMitreAttackv2/FeedMitreAttackv2.yml
  Packs/FeedMitreAttackv2/ReleaseNotes/1_0_6.md
  Packs/FeedMitreAttackv2/pack_metadata.json
Labels: docs-approved

#14494 XDR XQL Query Engine Integration
  Packs/CortexXDR/Integrations/XQLQueryingEngine/README.md
  Packs/CortexXDR/Integrations/XQLQueryingEngine/XQLQueryingEngine.py
  Packs/CortexXDR/Integrations/XQLQueryingEngine/XQLQueryingEngine.yml
  Packs/CortexXDR/Integrations/XQLQueryingEngine/XQLQueryingEngine_description.md
  Packs/CortexXDR/Integrations/XQLQueryingEngine/XQLQueryingEngine_image.png
  Packs/CortexXDR/Integrations/XQLQueryingEngine/XQLQueryingEngine_test.py
  Packs/CortexXDR/Integrations/XQLQueryingEngine/command_examples
  Packs/CortexXDR/ReleaseNotes/4_0_0.md
  Packs/CortexXDR/TestPlaybooks/CortexXDR-XQL_Query_TestPlaybook.yml
  Packs/CortexXDR/pack_metadata.json
  Tests/conf.json
Labels: docs-approved

#14897 Update python3 docker
  Packs/Active_Directory_Query/ReleaseNotes/1_3_5.md
  Packs/Active_Directory_Query/Scripts/IAMInitADUser/IAMInitADUser.yml
  Packs/Active_Directory_Query/pack_metadata.json
  Packs/Base/ReleaseNotes/1_13_32.md
  Packs/Base/Scripts/DeleteIndicatorRelationships/DeleteIndicatorRelationships.yml
  Packs/Base/Scripts/GetIndicatorsByQuery/GetIndicatorsByQuery.yml
  Packs/Base/pack_metadata.json
  Packs/CVSS/ReleaseNotes/1_0_1.md
  Packs/CVSS/Scripts/CVSSCalculator/CVSSCalculator.yml
  Packs/CVSS/pack_metadata.json
  Packs/EmailCommunication/ReleaseNotes/1_3_11.md
  Packs/EmailCommunication/Scripts/DisplayEmailHtml/DisplayEmailHtml.yml
  Packs/EmailCommunication/pack_metadata.json
  Packs/PassiveTotal/ReleaseNotes/2_0_13.md
  Packs/PassiveTotal/Scripts/RiskIQPassiveTotalComponentsScript/RiskIQPassiveTotalComponentsScript.yml
  Packs/PassiveTotal/Scripts/RiskIQPassiveTotalHostPairChildrenScript/RiskIQPassiveTotalHostPairChildrenScript.yml
  Packs/PassiveTotal/Scripts/RiskIQPassiveTotalHostPairParentsScript/RiskIQPassiveTotalHostPairParentsScript.yml
  Packs/PassiveTotal/pack_metadata.json
Labels: docs-approved, docker

#14895 Fix Filter Tests Not Sending Modified Packs
  Tests/scripts/collect_tests_and_content_packs.py
Labels: docs-approved

#14900 Docker update netutils
  Packs/CommonScripts/ReleaseNotes/1_4_37.md
  Packs/CommonScripts/Scripts/IPv4Blacklist/IPv4Blacklist.yml
  Packs/CommonScripts/Scripts/IPv4Whitelist/IPv4Whitelist.yml
  Packs/CommonScripts/Scripts/IsInCidrRanges/IsInCidrRanges.yml
  Packs/CommonScripts/Scripts/IsNotInCidrRanges/IsNotInCidrRanges.yml
  Packs/CommonScripts/pack_metadata.json
  Packs/DeveloperTools/ReleaseNotes/1_2_3.md
  Packs/DeveloperTools/Scripts/CompareIndicators/CompareIndicators.yml
  Packs/DeveloperTools/pack_metadata.json
Labels: docs-approved, docker

#14910 change sdk version to hash with fix
  dev-requirements-py3.txt
Labels: docs-approved

#14837 Retrive more information in the context for Graph Mail (#14546)
  Packs/MicrosoftGraphMail/Integrations/MicrosoftGraphMail/MicrosoftGraphMail.py
  Packs/MicrosoftGraphMail/Integrations/MicrosoftGraphMail/MicrosoftGraphMail.yml
  Packs/MicrosoftGraphMail/Integrations/MicrosoftGraphMail/MicrosoftGraphMail_description.md
  Packs/MicrosoftGraphMail/Integrations/MicrosoftGraphMail/README.md
  Packs/MicrosoftGraphMail/ReleaseNotes/1_0_25.md
  Packs/MicrosoftGraphMail/TestPlaybooks/MicrosoftGraphMail-Test_dev.yml
  Packs/MicrosoftGraphMail/TestPlaybooks/MicrosoftGraphMail-Test_dev_no_oproxy.yml
  Packs/MicrosoftGraphMail/TestPlaybooks/MicrosoftGraphMail-Test_prod.yml
  Packs/MicrosoftGraphMail/TestPlaybooks/playbook-MicrosoftGraphMail-Test.yml
  Packs/MicrosoftGraphMail/pack_metadata.json
Labels: docs-approved

#14853 introduce ListUsedDockersImages - New script that list all used docke…
  Packs/CommonScripts/ReleaseNotes/1_4_38.md
  Packs/CommonScripts/Scripts/ListUsedDockerImages/ListUsedDockerImages.py
  Packs/CommonScripts/Scripts/ListUsedDockerImages/ListUsedDockerImages.yml
  Packs/CommonScripts/Scripts/ListUsedDockerImages/ListUsedDockerImages_test.py
  Packs/CommonScripts/Scripts/ListUsedDockerImages/README.md
  Packs/CommonScripts/Scripts/ListUsedDockerImages/test_data/automation_search_response.json
  Packs/CommonScripts/Scripts/ListUsedDockerImages/test_data/integration_search_response.json
  Packs/CommonScripts/TestPlaybooks/playbook-ListUsedDockerImages_Test.yml
  Packs/CommonScripts/pack_metadata.json
  Tests/conf.json
Labels: content, docs-approved

#14554 Updated Arcanna
  Packs/Arcanna/Integrations/ArcannaAI/ArcannaAI.py
  Packs/Arcanna/Integrations/ArcannaAI/ArcannaAI.yml
  Packs/Arcanna/Integrations/ArcannaAI/ArcannaAI_test.py
  Packs/Arcanna/Integrations/ArcannaAI/README.md
  Packs/Arcanna/Integrations/ArcannaAI/command_examples
  Packs/Arcanna/Playbooks/ArcannaGenericInvestigation/playbook-Arcanna-Generic-Investigation.yml
  Packs/Arcanna/Playbooks/ArcannaGenericInvestigation/playbook-Arcanna-Generic-Investigation_README.md
  Packs/Arcanna/Playbooks/ArcannaGenericInvestigationV2WithFeedback/playbook-Arcanna-Generic-Investigation-V2-With-Feedback.yml
  Packs/Arcanna/Playbooks/ArcannaGenericInvestigationV2WithFeedback/playbook-Arcanna-Generic-Investigation-V2-With-Feedback_README.md
  Packs/Arcanna/ReleaseNotes/1_1_0.md
  Packs/Arcanna/Scripts/ArcannaFeedbackPostProcessingScript/ArcannaFeedbackPostProcessingScript.py
  Packs/Arcanna/Scripts/ArcannaFeedbackPostProcessingScript/ArcannaFeedbackPostProcessingScript.yml
  Packs/Arcanna/Scripts/ArcannaFeedbackPostProcessingScript/README.md
  Packs/Arcanna/Scripts/PrepareArcannaRawJson/PrepareArcannaRawJson.yml
  Packs/Arcanna/pack_metadata.json
Labels: Contribution, Partner, post-demo, Contribution Form Filled

#14893 bump to 21.9.0
  .circleci/content_release_vars.sh
Labels: docs-approved

#14775 Fixed user not displaying in ServiceNow Comments/Work Notes
  Packs/ServiceNow/Integrations/ServiceNowv2/ServiceNowv2.py
  Packs/ServiceNow/Integrations/ServiceNowv2/ServiceNowv2.yml
  Packs/ServiceNow/Integrations/ServiceNowv2/ServiceNowv2_test.py
  Packs/ServiceNow/Integrations/ServiceNowv2/test_data/response_constants.py
  Packs/ServiceNow/ReleaseNotes/2_2_4.md
  Packs/ServiceNow/pack_metadata.json
Labels: Contribution, docs-approved, Contribution Form Filled, Community

#14929 Update docker python3 to latest
  Packs/PassiveTotal/ReleaseNotes/2_0_14.md
  Packs/PassiveTotal/Scripts/RiskIQPassiveTotalComponentsWidgetScript/RiskIQPassiveTotalComponentsWidgetScript.yml
  Packs/PassiveTotal/Scripts/RiskIQPassiveTotalHostPairsChildrenWidgetScript/RiskIQPassiveTotalHostPairsChildrenWidgetScript.yml
  Packs/PassiveTotal/Scripts/RiskIQPassiveTotalHostPairsParentsWidgetScript/RiskIQPassiveTotalHostPairsParentsWidgetScript.yml
  Packs/PassiveTotal/Scripts/RiskIQPassiveTotalPDNSScript/RiskIQPassiveTotalPDNSScript.yml
  Packs/PassiveTotal/Scripts/RiskIQPassiveTotalPDNSWidgetScript/RiskIQPassiveTotalPDNSWidgetScript.yml
  Packs/PassiveTotal/Scripts/RiskIQPassiveTotalSSLForIssuerEmailWidgetScript/RiskIQPassiveTotalSSLForIssuerEmailWidgetScript.yml
  Packs/PassiveTotal/Scripts/RiskIQPassiveTotalSSLForSubjectEmailWidgetScript/RiskIQPassiveTotalSSLForSubjectEmailWidgetScript.yml
  Packs/PassiveTotal/Scripts/RiskIQPassiveTotalSSLWidgetScript/RiskIQPassiveTotalSSLWidgetScript.yml
  Packs/PassiveTotal/Scripts/RiskIQPassiveTotalTrackersScript/RiskIQPassiveTotalTrackersScript.yml
  Packs/PassiveTotal/Scripts/RiskIQPassiveTotalTrackersWidgetScript/RiskIQPassiveTotalTrackersWidgetScript.yml
  Packs/PassiveTotal/Scripts/RiskIQPassiveTotalWhoisWidgetScript/RiskIQPassiveTotalWhoisWidgetScript.yml
  Packs/PassiveTotal/pack_metadata.json
  Packs/SplunkPy/ReleaseNotes/2_2_0.md
  Packs/SplunkPy/Scripts/SplunkShowAsset/SplunkShowAsset.yml
  Packs/SplunkPy/Scripts/SplunkShowDrilldown/SplunkShowDrilldown.yml
  Packs/SplunkPy/Scripts/SplunkShowIdentity/SplunkShowIdentity.yml
  Packs/SplunkPy/Scripts/script-SplunkPySearch.yml
  Packs/SplunkPy/pack_metadata.json
Labels: docs-approved, docker

#14940 IntSightUnitTestsFix
  Packs/IntSight/Integrations/IntSight/IntSight_test.py
Labels: docs-approved

#14571 Okta IAM
  Packs/Okta/Classifiers/classifier-Okta_IAM.json
  Packs/Okta/Classifiers/classifier-mapper-Okta_IAM.json
  Packs/Okta/Integrations/Okta_IAM/Okta_IAM.py
  Packs/Okta/Integrations/Okta_IAM/Okta_IAM_test.py
  Packs/Okta/ReleaseNotes/2_2_3.md
  Packs/Okta/ReleaseNotes/2_2_5.md
  Packs/Okta/TestPlaybooks/Okta_IAM_-_Test_Playbook.yml
  Packs/Okta/pack_metadata.json
Labels: docs-approved

#13244 Add Cloud IDS Pack 2
  Packs/CloudIDS/.pack-ignore
  Packs/CloudIDS/.secrets-ignore
  Packs/CloudIDS/IncidentTypes/CloudIDS.json
  Packs/CloudIDS/Playbooks/Cloud_IDS-IP_Blacklist-GCP_Firewall_Append.png
  Packs/CloudIDS/Playbooks/Cloud_IDS-IP_Blacklist-GCP_Firewall_Append.yml
  Packs/CloudIDS/Playbooks/Cloud_IDS-IP_Blacklist-GCP_Firewall_Append_README.md
  Packs/CloudIDS/Playbooks/Cloud_IDS-IP_Blacklist-GCP_Firewall_Combine.png
  Packs/CloudIDS/Playbooks/Cloud_IDS-IP_Blacklist-GCP_Firewall_Combine.yml
  Packs/CloudIDS/Playbooks/Cloud_IDS-IP_Blacklist-GCP_Firewall_Combine_README.md
  Packs/CloudIDS/Playbooks/Cloud_IDS-IP_Blacklist-GCP_Firewall_Extract.png
  Packs/CloudIDS/Playbooks/Cloud_IDS-IP_Blacklist-GCP_Firewall_Extract.yml
  Packs/CloudIDS/Playbooks/Cloud_IDS-IP_Blacklist-GCP_Firewall_Extract_README.md
  Packs/CloudIDS/README.md
  Packs/CloudIDS/pack_metadata.json
Labels: Contribution, docs-approved, Contribution Form Filled, Community

#14839 TPB Not Listed In Conf JSON Partner Not Fail Build
  Tests/scripts/collect_tests_and_content_packs.py
  Tests/scripts/infrastructure_tests/test_collect_tests_and_content_packs.py
  Tests/scripts/utils/content_packs_util.py
  Tests/scripts/utils/tests/content_packs_util_test.py
Labels: docs-approved

#14916 [BugFix] StixParser Custom Fields
  Packs/Base/Scripts/StixParser/StixParser.py
  Packs/CommonScripts/Scripts/CreateIndicatorsFromSTIX/CreateIndicatorsFromSTIX.py
Labels: Contribution, Contribution Form Filled, Community

#14844 Duplicates removal
  Packs/Compliance/IncidentFields/MediaNotificationStatus.json
  Packs/Compliance/IncidentFields/incidentfield-Media_Notification.json
  Packs/Compliance/ReleaseNotes/1_0_7.md
  Packs/Compliance/pack_metadata.json
  Packs/Cymulate/Playbooks/playbook-Cymulate_Immediate_Threats.yml
  Packs/Cymulate/ReleaseNotes/2_0_6.md
  Packs/Cymulate/TestPlaybooks/playbook-CymulateTest.yml
  Packs/Cymulate/pack_metadata.json
  Packs/FeedCyrenThreatInDepth/IndicatorFields/indicatorfield-Cyren_City_Name.json
  Packs/XMCyber/IncidentFields/incidentfield-#_Critical_Assets_at_Risk.json
  Packs/XMCyber/IncidentFields/incidentfield-Critical_Assets_At_Risk.json
  Packs/XMCyber/ReleaseNotes/1_0_9.md
  Packs/XMCyber/pack_metadata.json
  Tests/conf.json
Labels: docs-approved

#14983 Change widget command execution type
  Packs/CommonDashboards/Dashboards/dashboard-CostOptimizationInstances.json
  Packs/CommonDashboards/ReleaseNotes/1_1_1.md
  Packs/CommonDashboards/pack_metadata.json
  Packs/CommonWidgets/ReleaseNotes/1_1_4.md
  Packs/CommonWidgets/Widgets/widget-CommandExecutionType.json
  Packs/CommonWidgets/pack_metadata.json
Labels: docs-approved

#14544 SlackV3 - Add Notification Customization
  Packs/Slack/Integrations/SlackV3/README.md
  Packs/Slack/Integrations/SlackV3/SlackV3.py
  Packs/Slack/Integrations/SlackV3/SlackV3.yml
  Packs/Slack/Integrations/SlackV3/SlackV3_test.py
  Packs/Slack/ReleaseNotes/2_1_7.md
  Packs/Slack/pack_metadata.json
Labels: docs-approved

#14951 Dynamic section reports
  Packs/DynamicSectionReports/.pack-ignore
  Packs/DynamicSectionReports/.secrets-ignore
  Packs/DynamicSectionReports/README.md
  Packs/DynamicSectionReports/Scripts/DisplayIndicatorReputationContent/DisplayIndicatorReputationContent.py
  Packs/DynamicSectionReports/Scripts/DisplayIndicatorReputationContent/DisplayIndicatorReputationContent.yml
  Packs/DynamicSectionReports/Scripts/DisplayIndicatorReputationContent/README.md
  Packs/DynamicSectionReports/Scripts/DisplayTaggedWarroomEntries/DisplayTaggedWarroomEntries.py
  Packs/DynamicSectionReports/Scripts/DisplayTaggedWarroomEntries/DisplayTaggedWarroomEntries.yml
  Packs/DynamicSectionReports/Scripts/DisplayTaggedWarroomEntries/README.md
  Packs/DynamicSectionReports/doc_files/incident_report.png
  Packs/DynamicSectionReports/doc_files/indicator_report.png
  Packs/DynamicSectionReports/doc_files/tag-playbook.png
  Packs/DynamicSectionReports/doc_files/tag-warroom.png
  Packs/DynamicSectionReports/pack_metadata.json
Labels: Contribution, docs-approved, Contribution Form Filled, Community

#14941 Fixed issue with backslash
  Packs/AttackIQFireDrill/Integrations/AttackIQFireDrill/AttackIQFireDrill.py
  Packs/AttackIQFireDrill/ReleaseNotes/1_0_7.md
  Packs/AttackIQFireDrill/pack_metadata.json
Labels: docs-approved

#14988 Palo Alto Networks PAN-OS - Fixed an issue where running the ***panor…
  Packs/PAN-OS/Integrations/Panorama/Panorama.py
  Packs/PAN-OS/Integrations/Panorama/Panorama_test.py
  Packs/PAN-OS/ReleaseNotes/1_6_29.md
  Packs/PAN-OS/pack_metadata.json
Labels: bug, docs-approved, release-notes-only

#14141 Custom indicator developer example
  Packs/DeveloperTools/IndicatorFields/indicatorfield-DeveloperTools_Param1.json
  Packs/DeveloperTools/IndicatorFields/indicatorfield-DeveloperTools_Param2.json
  Packs/DeveloperTools/IndicatorTypes/mycustomindicator.json
  Packs/DeveloperTools/Integrations/CustomIndicatorDemo/CustomIndicatorDemo.py
  Packs/DeveloperTools/Integrations/CustomIndicatorDemo/CustomIndicatorDemo.yml
  Packs/DeveloperTools/Integrations/CustomIndicatorDemo/CustomIndicatorDemo_image.png
  Packs/DeveloperTools/Integrations/CustomIndicatorDemo/CustomIndicatorDemo_test.py
  Packs/DeveloperTools/Integrations/CustomIndicatorDemo/Pipfile
  Packs/DeveloperTools/Integrations/CustomIndicatorDemo/Pipfile.lock
  Packs/DeveloperTools/Integrations/CustomIndicatorDemo/README.md
  Packs/DeveloperTools/Integrations/CustomIndicatorDemo/command_examples
  Packs/DeveloperTools/ReleaseNotes/1_2_4.md
  Packs/DeveloperTools/TestPlaybooks/playbook-CustomIndicatorDemo-test.yml
  Packs/DeveloperTools/pack_metadata.json
  Tests/conf.json
Labels: docs-approved

#15004 Python3 HealthCheck
  Packs/HealthCheck/ReleaseNotes/1_0_3.md
  Packs/HealthCheck/Scripts/HealthCheckAnalyzeLargeInvestigations/HealthCheckAnalyzeLargeInvestigations.yml
  Packs/HealthCheck/Scripts/HealthCheckCPU/HealthCheckCPU.yml
  Packs/HealthCheck/Scripts/HealthCheckCommonIndicators/HealthCheckCommonIndicators.yml
  Packs/HealthCheck/Scripts/HealthCheckContainersStatus/HealthCheckContainersStatus.yml
  Packs/HealthCheck/Scripts/HealthCheckDiskUsage/HealthCheckDiskUsage.yml
  Packs/HealthCheck/Scripts/HealthCheckDiskUsageLine/HealthCheckDiskUsageLine.yml
  Packs/HealthCheck/Scripts/HealthCheckDockerLog/HealthCheckDockerLog.yml
  Packs/HealthCheck/Scripts/HealthCheckFileSystem/HealthCheckFileSystem.yml
  Packs/HealthCheck/Scripts/HealthCheckGetLargestInputsAndOutputsInIncidents/HealthCheckGetLargestInputsAndOutputsInIncidents.yml
  Packs/HealthCheck/Scripts/HealthCheckIncidentsCreatedDaily/HealthCheckIncidentsCreatedDaily.yml
  Packs/HealthCheck/Scripts/HealthCheckIncidentsCreatedMonthly/HealthCheckIncidentsCreatedMonthly.yml
  Packs/HealthCheck/Scripts/HealthCheckIncidentsCreatedWeekly/HealthCheckIncidentsCreatedWeekly.yml
  Packs/HealthCheck/Scripts/HealthCheckInstalledPacks/HealthCheckInstalledPacks.yml
  Packs/HealthCheck/Scripts/HealthCheckIntegrations/HealthCheckIntegrations.yml
  Packs/HealthCheck/Scripts/HealthCheckLicenseData/HealthCheckLicenseData.yml
  Packs/HealthCheck/Scripts/HealthCheckMemory/HealthCheckMemory.yml
  Packs/HealthCheck/Scripts/HealthCheckNumberOfDroppedIncidents/HealthCheckNumberOfDroppedIncidents.yml
  Packs/HealthCheck/Scripts/HealthCheckNumberOfEngines/HealthCheckNumberOfEngines.yml
  Packs/HealthCheck/Scripts/HealthCheckOutdatedPacks/HealthCheckOutdatedPacks.yml
  Packs/HealthCheck/Scripts/HealthCheckPacksInstalled/HealthCheckPacksInstalled.yml
  Packs/HealthCheck/Scripts/HealthCheckPlaybookAnalysis/HealthCheckPlaybookAnalysis.yml
  Packs/HealthCheck/Scripts/HealthCheckReadConf/HealthCheckReadConf.yml
  Packs/HealthCheck/Scripts/HealthCheckReadTemeletryLog/HealthCheckReadTemeletryLog.yml
  Packs/HealthCheck/Scripts/HealthCheckReadVC/HealthCheckReadVC.yml
  Packs/HealthCheck/Scripts/HealthCheckServerConfiguration/HealthCheckServerConfiguration.yml
  Packs/HealthCheck/Scripts/HealthCheckServerLog/HealthCheckServerLog.yml
  Packs/HealthCheck/Scripts/HealthCheckUnpack/HealthCheckUnpack.yml
  Packs/HealthCheck/Scripts/HealthCheckWorkers/HealthCheckWorkers.yml
  Packs/HealthCheck/pack_metadata.json
Labels: docs-approved, docker

#14864 Enrichment for extract indicators playbook v2
  Packs/CommonPlaybooks/Playbooks/playbook-Extract_Indicators_From_File_-_Generic_v2_4_5.yml
  Packs/CommonPlaybooks/Playbooks/playbook-Extract_Indicators_From_File_-_Generic_v2_4_5_README.md
  Packs/CommonPlaybooks/ReleaseNotes/2_0_6.md
  Packs/CommonPlaybooks/doc_files/Extract_Indicators_From_File_-_Generic_v2.png
  Packs/CommonPlaybooks/pack_metadata.json
  Tests/conf.json
Labels: docs-approved

#14863 ironscales - add defaults
  Packs/Ironscales/IncidentFields/incidentfield-Ironscales-Choose-Classification.json
  Packs/Ironscales/IncidentTypes/incidenttype-Ironscales.json
  Packs/Ironscales/Integrations/Ironscales/Ironscales.yml
  Packs/Ironscales/Integrations/Ironscales/README.md
  Packs/Ironscales/ReleaseNotes/1_1_0.md
  Packs/Ironscales/Scripts/IronscalesEmailFieldTrigger/IronscalesEmailFieldTrigger.py
  Packs/Ironscales/Scripts/IronscalesEmailFieldTrigger/IronscalesEmailFieldTrigger.yml
  Packs/Ironscales/Scripts/IronscalesEmailFieldTrigger/IronscalesEmailFieldTrigger_test.py
  Packs/Ironscales/Scripts/IronscalesEmailFieldTrigger/README.md
  Packs/Ironscales/pack_metadata.json
Labels: Contribution, docs-approved, Partner, Contribution Form Filled

#15015 Update README
  Packs/DynamicSectionReports/README.md
  Packs/DynamicSectionReports/ReleaseNotes/1_0_1.md
  Packs/DynamicSectionReports/pack_metadata.json
Labels: Contribution

#15021 DeveloperTools - fixed indicator fields IDs
  Packs/DeveloperTools/IndicatorFields/indicatorfield-DeveloperTools_Param1.json
  Packs/DeveloperTools/IndicatorFields/indicatorfield-DeveloperTools_Param2.json
  Packs/DeveloperTools/ReleaseNotes/1_2_6.md
  Packs/DeveloperTools/pack_metadata.json
Labels: docs-approved

#15023 Fix RM 108 Broken Image In README
  Packs/CommonPlaybooks/Playbooks/playbook-Extract_Indicators_From_File_-_Generic_v2_4_5_README.md
Labels: docs-approved

#15024 ignore PB110 on some playbooks
  Packs/BruteForce/.pack-ignore
  Packs/CommonPlaybooks/.pack-ignore
  Packs/Malware/.pack-ignore
  Packs/Phishing/.pack-ignore
  Packs/SANS/.secrets-ignore
Labels: docs-approved

#15025 [Chronicle-246] Google Chronicle - FAQ - Fetch Detection
  Packs/GoogleChronicleBackstory/Integrations/GoogleChronicleBackstory/README.md
  Packs/GoogleChronicleBackstory/ReleaseNotes/2_0_8.md
  Packs/GoogleChronicleBackstory/pack_metadata.json
Labels: Contribution, Partner, Contribution Form Filled

#15031 VerifyIPv6Indicator - skipped flaky unit test
  Packs/CommonScripts/Scripts/VerifyIPv6Indicator/VerifyIPv6Indicator_test.py
Labels: docs-approved

#14755 updated docker image for gitlab
  .gitlab/ci/.gitlab-ci.yml
  .gitlab/ci/global.yml
  .gitlab/ci/instance-test.yml
  .gitlab/ci/slack-notify.yml
  .hooks/bootstrap
Labels: docs-approved

#14942 xdr xql bug fix
  Packs/CortexXDR/Integrations/XQLQueryingEngine/XQLQueryingEngine.py
  Packs/CortexXDR/Integrations/XQLQueryingEngine/XQLQueryingEngine_test.py
  Packs/CortexXDR/ReleaseNotes/4_0_3.md
  Packs/CortexXDR/pack_metadata.json
Labels: bug, docs-approved, release-notes-only

#14939 MS Graph Mail - Allow attaching files that do not have an explicit file name
  Packs/MicrosoftGraphMail/Integrations/MicrosoftGraphMail/MicrosoftGraphMail.py
  Packs/MicrosoftGraphMail/ReleaseNotes/1_0_26.md
  Packs/MicrosoftGraphMail/pack_metadata.json
Labels: docs-approved

#15038 update the allowed upload user list
  .gitlab/ci/bucket-upload.yml
Labels: docs-approved

#14992 Added unit test
  Packs/Jira/Integrations/JiraV2/JiraV2.py
  Packs/Jira/Integrations/JiraV2/JiraV2.yml
  Packs/Jira/Integrations/JiraV2/JiraV2_test.py
  Packs/Jira/Integrations/JiraV2/test_data/raw_response.py
  Packs/Jira/ReleaseNotes/1_3_8.md
  Packs/Jira/pack_metadata.json
Labels: docs-approved

#14817 PAN-OS - edit-url-filter
  Packs/PAN-OS/Integrations/Panorama/Panorama.py
  Packs/PAN-OS/Integrations/Panorama/Panorama.yml
  Packs/PAN-OS/Integrations/Panorama/Panorama_test.py
  Packs/PAN-OS/Integrations/Panorama/README.md
  Packs/PAN-OS/ReleaseNotes/1_7_0.md
  Packs/PAN-OS/TestPlaybooks/playbook-palo_alto_firewall_test_pb.yml
  Packs/PAN-OS/pack_metadata.json
Labels: bug, docs-approved, release-notes-only

#15037 bump up demisto/netutils:24101 over the missing Integration and Autom…
  Packs/CommonScripts/ReleaseNotes/1_4_40.md
  Packs/CommonScripts/Scripts/IsRFC1918Address/IsRFC1918Address.yml
  Packs/CommonScripts/pack_metadata.json
  Packs/Dig/ReleaseNotes/1_0_1.md
  Packs/Dig/Scripts/Dig/Dig.yml
  Packs/Dig/Scripts/Dig/README.md
  Packs/Dig/pack_metadata.json
  Packs/Tufin/Integrations/Tufin/Tufin.yml
  Packs/Tufin/ReleaseNotes/1_2_1.md
  Packs/Tufin/pack_metadata.json
Labels: docs-approved, docker

#14527 Cortex XDR IR - add xdr-get-endpoints-by-status command
  Packs/CortexXDR/Integrations/CortexXDRIR/CortexXDRIR.py
  Packs/CortexXDR/Integrations/CortexXDRIR/CortexXDRIR.yml
  Packs/CortexXDR/Integrations/CortexXDRIR/README.md
  Packs/CortexXDR/Integrations/CortexXDRIR/command_examples
  Packs/CortexXDR/ReleaseNotes/4_1_0.md
  Packs/CortexXDR/Scripts/XDRConnectedEndpoints/XDRConnectedEndpoints.py
  Packs/CortexXDR/Scripts/XDRDisconnectedEndpoints/XDRDisconnectedEndpoints.py
  Packs/CortexXDR/TestPlaybooks/Test_XDR_Playbook.yml
  Packs/CortexXDR/pack_metadata.json
Labels: docs-approved

#15061 Updated guide link. Created new branch.
  Packs/SafeNet_Trusted_Access/.secrets-ignore
  Packs/SafeNet_Trusted_Access/Integrations/SafeNetTrustedAccess/README.md
  Packs/SafeNet_Trusted_Access/Integrations/SafeNetTrustedAccess/SafeNetTrustedAccess.py
  Packs/SafeNet_Trusted_Access/Integrations/SafeNetTrustedAccess/SafeNetTrustedAccess_description.md
  Packs/SafeNet_Trusted_Access/README.md
  Packs/SafeNet_Trusted_Access/ReleaseNotes/1_0_2.md
  Packs/SafeNet_Trusted_Access/pack_metadata.json
Labels: Contribution, Partner, Contribution Form Filled

#15065 VirusTotal packs: Update support to VT team
  Packs/VirusTotal-Private_API/Author_image.png
  Packs/VirusTotal-Private_API/README.md
  Packs/VirusTotal-Private_API/pack_metadata.json
  Packs/VirusTotal/Author_image.png
  Packs/VirusTotal/README.md
  Packs/VirusTotal/pack_metadata.json
Labels: Contribution, Partner, Contribution Form Filled

#14956 add all regions to default config in O365 feed
  Packs/FeedOffice365/Integrations/FeedOffice365/FeedOffice365.py
  Packs/FeedOffice365/Integrations/FeedOffice365/FeedOffice365.yml
  Packs/FeedOffice365/Integrations/FeedOffice365/FeedOffice365_test.py
  Packs/FeedOffice365/ReleaseNotes/1_1_11.md
  Packs/FeedOffice365/pack_metadata.json
Labels: bug, docs-approved, release-notes-only

#14491 [flashpoint-163] Flashpoint Feed Integration
  Packs/FlashpointFeed/.pack-ignore
  Packs/FlashpointFeed/.secrets-ignore
  Packs/FlashpointFeed/Author_image.png
  Packs/FlashpointFeed/IndicatorFields/incidentfield-Flashpoint-Attribute-ID.json
  Packs/FlashpointFeed/IndicatorFields/incidentfield-Flashpoint-Attribute-UUID.json
  Packs/FlashpointFeed/IndicatorFields/incidentfield-Flashpoint-Category.json
  Packs/FlashpointFeed/IndicatorFields/incidentfield-Flashpoint-Event-Creator-Email.json
  Packs/FlashpointFeed/IndicatorFields/incidentfield-Flashpoint-Event-Href.json
  Packs/FlashpointFeed/IndicatorFields/incidentfield-Flashpoint-Event-Information.json
  Packs/FlashpointFeed/IndicatorFields/incidentfield-Flashpoint-Event-UUID.json
  Packs/FlashpointFeed/IndicatorFields/incidentfield-Flashpoint-Indicator-Type.json
  Packs/FlashpointFeed/IndicatorFields/incidentfield-Flashpoint-Malware-Description.json
  Packs/FlashpointFeed/IndicatorFields/incidentfield-Flashpoint-Report.json
  Packs/FlashpointFeed/IndicatorFields/incidentfield-Flashpoint-Timestamp.json
  Packs/FlashpointFeed/IndicatorTypes/reputation-Flashpoint_Indicator.json
  Packs/FlashpointFeed/Integrations/FlashpointFeed/FlashpointFeed.py
  Packs/FlashpointFeed/Integrations/FlashpointFeed/FlashpointFeed.yml
  Packs/FlashpointFeed/Integrations/FlashpointFeed/FlashpointFeed_description.md
  Packs/FlashpointFeed/Integrations/FlashpointFeed/FlashpointFeed_image.png
  Packs/FlashpointFeed/Integrations/FlashpointFeed/FlashpointFeed_test.py
  Packs/FlashpointFeed/Integrations/FlashpointFeed/Pipfile
  Packs/FlashpointFeed/Integrations/FlashpointFeed/Pipfile.lock
  Packs/FlashpointFeed/Integrations/FlashpointFeed/README.md
  Packs/FlashpointFeed/Integrations/FlashpointFeed/test_data/fetch_indicators.json
  Packs/FlashpointFeed/Integrations/FlashpointFeed/test_data/fetch_indicators_response.json
  Packs/FlashpointFeed/Integrations/FlashpointFeed/test_data/get_indicators.md
  Packs/FlashpointFeed/Integrations/FlashpointFeed/test_data/input_data.py
  Packs/FlashpointFeed/Layouts/layoutscontainer-Flashpoint_Indicator.json
  Packs/FlashpointFeed/README.md
  Packs/FlashpointFeed/pack_metadata.json
Labels: Contribution, docs-approved, Partner, Contribution Form Filled

#14798 Pack adoption process second stage with minor updates
  Packs/SophosCentral/.pack-ignore
  Packs/SophosCentral/Author_image.png
  Packs/SophosCentral/Integrations/SophosCentral/README.md
  Packs/SophosCentral/Integrations/SophosCentral/SophosCentral.py
  Packs/SophosCentral/Integrations/SophosCentral/SophosCentral.yml
  Packs/SophosCentral/Integrations/SophosCentral/SophosCentral_description.md
  Packs/SophosCentral/Integrations/SophosCentral/SophosCentral_test.py
  Packs/SophosCentral/Integrations/SophosCentral/test_data/deisolate_endpoint.json
  Packs/SophosCentral/Integrations/SophosCentral/test_data/isolate_endpoint.json
  Packs/SophosCentral/Integrations/SophosCentral/test_data/person.json
  Packs/SophosCentral/Integrations/SophosCentral/test_data/tenant_search.json
  Packs/SophosCentral/Integrations/SophosCentral/test_data/whoami_organization.json
  Packs/SophosCentral/Integrations/SophosCentral/test_data/whoami_partner.json
  Packs/SophosCentral/Integrations/SophosCentral/test_data/whoami_tenant.json
  Packs/SophosCentral/README.md
  Packs/SophosCentral/ReleaseNotes/1_1_0.md
  Packs/SophosCentral/pack_metadata.json
Labels: Contribution, Partner, pending-demo, Contribution Form Filled

#14618 KELARaDark v1.0.0
  Packs/KELARaDark/.pack-ignore
  Packs/KELARaDark/.secrets-ignore
  Packs/KELARaDark/Author_image.png
  Packs/KELARaDark/Classifiers/classifier-RaDark_-_Incoming_Mapper.json
  Packs/KELARaDark/IncidentFields/incidentfield-KELA_RaDark_Details.json
  Packs/KELARaDark/IncidentFields/incidentfield-KELA_RaDark_Sub_Type.json
  Packs/KELARaDark/IncidentFields/incidentfield-KELA_RaDark_Table_Agressor.json
  Packs/KELARaDark/IncidentFields/incidentfield-KELA_RaDark_Table_Botnets.json
  Packs/KELARaDark/IncidentFields/incidentfield-KELA_RaDark_Table_Leaked_Credentials_From_Citadel.json
  Packs/KELARaDark/IncidentFields/incidentfield-KELA_RaDark_Table_Leaked_Credentials_From_Dump.json
  Packs/KELARaDark/IncidentFields/incidentfield-KELA_RaDark_Table_Leaked_Credentials_From_Hacking_Discussions.json
  Packs/KELARaDark/IncidentFields/incidentfield-KELA_RaDark_Table_Leaked_Credentials_From_Instant_Messaging.json
  Packs/KELARaDark/IncidentFields/incidentfield-KELA_RaDark_Table_Russian_Market.json
  Packs/KELARaDark/IncidentFields/incidentfield-RaDark_Incident_URL.json
  Packs/KELARaDark/IncidentFields/incidentfield-RaDark_Monitor_ID.json
  Packs/KELARaDark/IncidentTypes/incidenttype-RaDark.json
  Packs/KELARaDark/Integrations/RaDark/README.md
  Packs/KELARaDark/Integrations/RaDark/RaDark.py
  Packs/KELARaDark/Integrations/RaDark/RaDark.yml
  Packs/KELARaDark/Integrations/RaDark/RaDark_description.md
  Packs/KELARaDark/Integrations/RaDark/RaDark_image.png
  Packs/KELARaDark/Integrations/RaDark/RaDark_test.py
  Packs/KELARaDark/Integrations/RaDark/command_examples.txt
  Packs/KELARaDark/Integrations/RaDark/test_data/email_enrich_info.json
  Packs/KELARaDark/Integrations/RaDark/test_data/fetch_incidents_info.json
  Packs/KELARaDark/Integrations/RaDark/test_data/incident_get_items_info.json
  Packs/KELARaDark/Integrations/RaDark/test_data/item_handle_info.json
  Packs/KELARaDark/Integrations/RaDark/test_data/item_purchase_info.json
  Packs/KELARaDark/Layouts/layoutscontainer-RaDark_Layout.json
  Packs/KELARaDark/Playbooks/Get_RaDark_Detailed_Items.yml
  Packs/KELARaDark/Playbooks/Get_RaDark_Detailed_Items_README.md
  Packs/KELARaDark/README.md
  Packs/KELARaDark/Scripts/MapRaDarkIncidentDetails/MapRaDarkIncidentDetails.py
  Packs/KELARaDark/Scripts/MapRaDarkIncidentDetails/MapRaDarkIncidentDetails.yml
  Packs/KELARaDark/Scripts/MapRaDarkIncidentDetails/README.md
  Packs/KELARaDark/doc_files/Get_RaDark_Detailed_Items.png
  Packs/KELARaDark/pack_metadata.json
Labels: Contribution, Partner, post-demo, Contribution Form Filled

#15010 fix JOB - Integrations and Incidents Health Check - Lists handling
  Packs/IntegrationsAndIncidentsHealthCheck/Playbooks/playbook-JOB_-_Integrations_and_Playbooks_Health_Check_-_Lists_handling.yml
  Packs/IntegrationsAndIncidentsHealthCheck/ReleaseNotes/1_2_6.md
  Packs/IntegrationsAndIncidentsHealthCheck/pack_metadata.json
Labels: docs-approved

#14954 Adds ShiftLeft CORE support
  Packs/ShiftLeft/.gitignore
  Packs/ShiftLeft/.pack-ignore
  Packs/ShiftLeft/.secrets-ignore
  Packs/ShiftLeft/Author_image.png
  Packs/ShiftLeft/Integrations/shiftleft/Pipfile
  Packs/ShiftLeft/Integrations/shiftleft/Pipfile.lock
  Packs/ShiftLeft/Integrations/shiftleft/README.md
  Packs/ShiftLeft/Integrations/shiftleft/command_examples.txt
  Packs/ShiftLeft/Integrations/shiftleft/shiftleft.py
  Packs/ShiftLeft/Integrations/shiftleft/shiftleft.yml
  Packs/ShiftLeft/Integrations/shiftleft/shiftleft_description.md
  Packs/ShiftLeft/Integrations/shiftleft/shiftleft_image.png
  Packs/ShiftLeft/Integrations/shiftleft/shiftleft_test.py
  Packs/ShiftLeft/Integrations/shiftleft/test_data/test_list_findings.json
  Packs/ShiftLeft/README.md
  Packs/ShiftLeft/pack_metadata.json
Labels: Contribution, Partner, post-demo, Contribution Form Filled

#14960 Update the docker image
  Packs/Base/ReleaseNotes/1_13_35.md
  Packs/Base/Scripts/SaneDocReportV2/SaneDocReportV2.yml
  Packs/Base/pack_metadata.json
Labels: docs-approved

#14842 XDR 3.0 add api changes support
  Packs/CortexXDR/.secrets-ignore
  Packs/CortexXDR/IncidentFields/XDR_Status_v2.json
  Packs/CortexXDR/Integrations/CortexXDRIR/CortexXDRIR.py
  Packs/CortexXDR/Integrations/CortexXDRIR/CortexXDRIR.yml
  Packs/CortexXDR/Integrations/CortexXDRIR/CortexXDRIR_test.py
  Packs/CortexXDR/Integrations/CortexXDRIR/README.md
  Packs/CortexXDR/ReleaseNotes/4_1_1.md
  Packs/CortexXDR/Scripts/XDRSyncScript/XDRSyncScript.yml
  Packs/CortexXDR/Scripts/XDRSyncScript_5_9_9/XDRSyncScript_5_9_9.yml
  Packs/CortexXDR/pack_metadata.json
Labels: docs-approved

#15081 Fix Gitlab Branch Deletion Scheduled Pipeline
  .gitlab/ci/miscellaneous.yml
  Utils/delete_mismatched_branches.py
Labels: docs-approved

#15117 bump version to 21.9.1
  .circleci/content_release_vars.sh
Labels: docs-approved

#15027 Cohesity Helios
  Packs/CohesityHelios/.pack-ignore
  Packs/CohesityHelios/.secrets-ignore
  Packs/CohesityHelios/Author_image.png
  Packs/CohesityHelios/Classifiers/classifier-CohesityHelios.json
  Packs/CohesityHelios/Classifiers/classifier-mapper-incoming-CohesityHelios.json
  Packs/CohesityHelios/IncidentFields/incidentfield-Cohesity_Helios_Alert_Cause.json
  Packs/CohesityHelios/IncidentFields/incidentfield-Cohesity_Helios_Alert_Description.json
  Packs/CohesityHelios/IncidentFields/incidentfield-Cohesity_Helios_Anomalous_Object_Name.json
  Packs/CohesityHelios/IncidentFields/incidentfield-Cohesity_Helios_Cluster_Id.json
  Packs/CohesityHelios/IncidentFields/incidentfield-Cohesity_Helios_Cluster_Name.json
  Packs/CohesityHelios/IncidentFields/incidentfield-Cohesity_Helios_Object_Environment.json
  Packs/CohesityHelios/IncidentFields/incidentfields-Cohesity_Helios_Anomaly_Strength.json
  Packs/CohesityHelios/IncidentTypes/incidenttype-Cohesity_Helios_Ransomware_Incident.json
  Packs/CohesityHelios/Integrations/CohesityHelios/CohesityHelios.py
  Packs/CohesityHelios/Integrations/CohesityHelios/CohesityHelios.yml
  Packs/CohesityHelios/Integrations/CohesityHelios/CohesityHelios_description.md
  Packs/CohesityHelios/Integrations/CohesityHelios/CohesityHelios_image.png
  Packs/CohesityHelios/Integrations/CohesityHelios/CohesityHelios_test.py
  Packs/CohesityHelios/Integrations/CohesityHelios/Pipfile
  Packs/CohesityHelios/Integrations/CohesityHelios/Pipfile.lock
  Packs/CohesityHelios/Integrations/CohesityHelios/README.md
  Packs/CohesityHelios/Integrations/CohesityHelios/command_examples
  Packs/CohesityHelios/Integrations/CohesityHelios/command_examples.txt
  Packs/CohesityHelios/Integrations/CohesityHelios/test_data/get_ransomware_alert_detail_resp.json
  Packs/CohesityHelios/Integrations/CohesityHelios/test_data/get_ransomware_alerts_resp.json
  Packs/CohesityHelios/Layouts/layoutscontainer-Cohesity_Helios_Ransomware_Incident.json
  Packs/CohesityHelios/README.md
  Packs/CohesityHelios/pack_metadata.json
Labels: Contribution, Partner, post-demo, Contribution Form Filled

#14751 Xdr isolation and un-isolation warning on disconnected endpoint
  Packs/CortexXDR/Integrations/CortexXDRIR/CortexXDRIR.py
  Packs/CortexXDR/Integrations/CortexXDRIR/CortexXDRIR.yml
  Packs/CortexXDR/Integrations/CortexXDRIR/CortexXDRIR_test.py
  Packs/CortexXDR/Integrations/CortexXDRIR/README.md
  Packs/CortexXDR/ReleaseNotes/4_1_2.md
  Packs/CortexXDR/pack_metadata.json
Labels: docs-approved

#14898 Add Cisco-Meraki integration's Readme
  Packs/cisco-meraki/Integrations/cisco-meraki/README.md
  Packs/cisco-meraki/Integrations/cisco-meraki/cisco-meraki.yml
  Packs/cisco-meraki/Integrations/cisco-meraki/command_examples
  Packs/cisco-meraki/ReleaseNotes/1_0_1.md
  Packs/cisco-meraki/pack_metadata.json
Labels: docs-approved

#14648 Added new phishing campaign dynamic section scripts
  Packs/Campaign/IncidentFields/incidentfield-Actions_On_Campaign_lower_similarity_Incidents.json
  Packs/Campaign/IncidentFields/incidentfield-Select_Campaign_lower_similarity_Incidents.json
  Packs/Campaign/ReleaseNotes/3_0_5.md
  Packs/Campaign/Scripts/GetCampaignIncidentsInfo/GetCampaignIncidentsInfo.py
  Packs/Campaign/Scripts/GetCampaignLowerSimilarityIncidentsIdsAsOptions/GetCampaignLowerSimilarityIncidentsIdsAsOptions.py
  Packs/Campaign/Scripts/GetCampaignLowerSimilarityIncidentsIdsAsOptions/GetCampaignLowerSimilarityIncidentsIdsAsOptions.yml
  Packs/Campaign/Scripts/GetCampaignLowerSimilarityIncidentsIdsAsOptions/GetCampaignLowerSimilarityIncidentsIdsAsOptions_test.py
  Packs/Campaign/Scripts/GetCampaignLowerSimilarityIncidentsIdsAsOptions/README.md
  Packs/Campaign/Scripts/PerformActionOnCampaignIncidents/PerformActionOnCampaignIncidents.py
  Packs/Campaign/Scripts/PerformActionOnCampaignIncidents/PerformActionOnCampaignIncidents.yml
  Packs/Campaign/Scripts/PerformActionOnCampaignIncidents/PerformActionOnCampaignIncidents_test.py
  Packs/Campaign/Scripts/PerformActionOnCampaignIncidents/README.md
  Packs/Campaign/Scripts/ShowCampaignLastIncidentOccurred/README.md
  Packs/Campaign/Scripts/ShowCampaignLastIncidentOccurred/ShowCampaignLastIncidentOccurred.py
  Packs/Campaign/Scripts/ShowCampaignLastIncidentOccurred/ShowCampaignLastIncidentOccurred.yml
  Packs/Campaign/Scripts/ShowCampaignLastIncidentOccurred/ShowCampaignLastIncidentOccurred_test.py
  Packs/Campaign/Scripts/ShowCampaignRecipients/README.md
  Packs/Campaign/Scripts/ShowCampaignRecipients/ShowCampaignRecipients.py
  Packs/Campaign/Scripts/ShowCampaignRecipients/ShowCampaignRecipients.yml
  Packs/Campaign/Scripts/ShowCampaignRecipients/ShowCampaignRecipients_test.py
  Packs/Campaign/Scripts/ShowCampaignSenders/README.md
  Packs/Campaign/Scripts/ShowCampaignSenders/ShowCampaignSenders.py
  Packs/Campaign/Scripts/ShowCampaignSenders/ShowCampaignSenders.yml
  Packs/Campaign/Scripts/ShowCampaignSenders/ShowCampaignSenders_test.py
  Packs/Campaign/Scripts/ShowCampaignSimilarityRange/README.md
  Packs/Campaign/Scripts/ShowCampaignSimilarityRange/ShowCampaignSimilarityRange.py
  Packs/Campaign/Scripts/ShowCampaignSimilarityRange/ShowCampaignSimilarityRange.yml
  Packs/Campaign/Scripts/ShowCampaignSimilarityRange/ShowCampaignSimilarityRange_test.py
  Packs/Campaign/pack_metadata.json
Labels: docs-approved
