Repository demisto/content, pull requests merged in 2021-03, with the labels that each got.

#11603 Unskipping Test Playbooks for PAN-OS
  Tests/conf.json
Labels: docs-approved

#11598 Cyren author
  Packs/FeedCyrenThreatInDepth/Author_image.png
Labels: docs-approved

#11569 Update SanePdfReport script with new docker image
  Packs/Base/ReleaseNotes/1_7_18.md
  Packs/Base/Scripts/SanePdfReport/SanePdfReport.yml
  Packs/Base/pack_metadata.json
Labels: docs-approved, release-notes-only

#11489 panorama tpb run
  Packs/PAN-OS/TestPlaybooks/playbook-palo_alto_panorama_test_pb.yml
  Tests/conf.json
Labels: docs-approved

#11612 Logpoint image fix
  Packs/LogPoint_SIEM_Integration/Author_image.png
Labels: docs-approved

#11610 CheckFieldValue fix
  Packs/CommonScripts/ReleaseNotes/1_3_23.md
  Packs/CommonScripts/Scripts/CheckFieldValue/CheckFieldValue.py
  Packs/CommonScripts/pack_metadata.json
Labels: bug, docs-approved, release-notes-only

#11609 SDP TPB fix
  Packs/ServiceDeskPlus/TestPlaybooks/playbook-Service_Desk_Plus.yml
Labels: docs-approved

#11615 Don't fail the build in case pre-update installation fails
  Tests/configure_and_test_integration_instances.py
Labels: docs-approved

#11619 Updated README.md (Connectivity)
  Packs/SailPointIdentityIQ/Integrations/SailPointIdentityIQ/README.md
Labels: Contribution, docs-approved

#11604 Marketplace: Remove contrib suffix from dependencies images
  Tests/Marketplace/Tests/marketplace_services_test.py
  Tests/Marketplace/marketplace_services.py
Labels: docs-approved

#11621 Unskip TAXII Feed test
  Tests/conf.json
Labels: docs-approved

#11613 Indicator Types-URL-Fixed an issue where URLs with an underscore were not extracted
  Packs/Base/TestPlaybooks/playbook-Indicators-reputation-.json-Test.yml
  Packs/CommonTypes/IndicatorTypes/reputation-url.json
  Packs/CommonTypes/ReleaseNotes/2_8_5.md
  Packs/CommonTypes/pack_metadata.json
  Tests/secrets_white_list.json
Labels: bug, docs-approved, release-notes-only

#11605 fix domain indicator
  Packs/CommonTypes/IndicatorTypes/reputation-domain.json
  Packs/CommonTypes/ReleaseNotes/2_8_6.md
  Packs/CommonTypes/pack_metadata.json
Labels: bug, docs-approved, release-notes-only

#11608 Integrations Health dashboard bug fix- show errors right after fresh install
  Packs/IntegrationsAndIncidentsHealthCheck/ReleaseNotes/1_1_16.md
  Packs/IntegrationsAndIncidentsHealthCheck/Scripts/IntegrationsCheck_Widget_IntegrationsErrorsInfo/IntegrationsCheck_Widget_IntegrationsErrorsInfo.py
  Packs/IntegrationsAndIncidentsHealthCheck/Scripts/IntegrationsCheck_Widget_IntegrationsErrorsInfo/IntegrationsCheck_Widget_IntegrationsErrorsInfo.yml
  Packs/IntegrationsAndIncidentsHealthCheck/Scripts/IntegrationsCheck_Widget_IntegrationsErrorsInfo/IntegrationsCheck_Widget_IntegrationsErrorsInfo_test.py
  Packs/IntegrationsAndIncidentsHealthCheck/Scripts/IntegrationsCheck_Widget_NumberFailingInstances/IntegrationsCheck_Widget_NumberFailingInstances.py
  Packs/IntegrationsAndIncidentsHealthCheck/Scripts/IntegrationsCheck_Widget_NumberFailingInstances/IntegrationsCheck_Widget_NumberFailingInstances.yml
  Packs/IntegrationsAndIncidentsHealthCheck/Scripts/IntegrationsCheck_Widget_NumberFailingInstances/IntegrationsCheck_Widget_NumberFailingInstances_test.py
  Packs/IntegrationsAndIncidentsHealthCheck/pack_metadata.json
Labels: bug, docs-approved, release-notes-only

#11578 EWS O365 Playbooks Output Fix
  Packs/EWS/Playbooks/playbook-O365-SecurityAndCompliance-Search.yml
  Packs/EWS/Playbooks/playbook-O365-SecurityAndCompliance-SearchAction-Delete.yml
  Packs/EWS/Playbooks/playbook-O365-SecurityAndCompliance-SearchAction-Preview.yml
  Packs/EWS/ReleaseNotes/1_8_2.md
  Packs/EWS/TestPlaybooks/playbook-O365-SecurityAndCompliance-ContextResults-Test.yml
  Packs/EWS/pack_metadata.json
  Tests/conf.json
Labels: docs-approved, release-notes-only

#11628 CommonScripts - fixed argument descriptions
  Packs/CommonScripts/ReleaseNotes/1_3_24.md
  Packs/CommonScripts/Scripts/script-ConvertXmlFileToJson.yml
  Packs/CommonScripts/Scripts/script-ConvertXmlToJson.yml
  Packs/CommonScripts/Scripts/script-CreateArray.yml
  Packs/CommonScripts/Scripts/script-CreateEmailHtmlBody.yml
  Packs/CommonScripts/Scripts/script-FileCreateAndUpload.yml
  Packs/CommonScripts/Scripts/script-IncidentAddSystem.yml
  Packs/CommonScripts/Scripts/script-IsGreaterThan.yml
  Packs/CommonScripts/Scripts/script-LessThanPercentage.yml
  Packs/CommonScripts/Scripts/script-MathUtil.yml
  Packs/CommonScripts/Scripts/script-NotInContextVerification.yml
  Packs/CommonScripts/Scripts/script-ParseJSON.yml
  Packs/CommonScripts/Scripts/script-UnEscapeIPs.yml
  Packs/CommonScripts/pack_metadata.json
Labels: bug, docs-approved

#11629 Intsight: Add a second instead of ms to timestamp
  Packs/IntSight/Integrations/IntSight/IntSight.py
  Packs/IntSight/ReleaseNotes/1_0_4.md
  Packs/IntSight/pack_metadata.json
Labels: docs-approved

#11560 Find similar incidents bug
  Packs/CommonScripts/ReleaseNotes/1_3_25.md
  Packs/CommonScripts/Scripts/FindSimilarIncidentsV2/FindSimilarIncidentsV2.py
  Packs/CommonScripts/Scripts/FindSimilarIncidentsV2/FindSimilarIncidentsV2.yml
  Packs/CommonScripts/Scripts/FindSimilarIncidentsV2/find_similar_incidents_test.py
  Packs/CommonScripts/pack_metadata.json
Labels: bug, docs-approved, release-notes-only

#11622 fix tpb for collect test
  Packs/ExpanseV2/TestPlaybooks/playbook-ExpanseV2_Test.yml
  Packs/GreyNoise/TestPlaybooks/playbook-GreyNoise-test.yml
  Packs/XMCyber/TestPlaybooks/XMCyberIntegration-Test.yml
Labels: docs-approved

#11633 bump version
  .circleci/content_release_vars.sh
Labels: docs-approved

#11631 CommonScripts - Fixed scripts descriptions step 2
  Packs/CommonScripts/ReleaseNotes/1_3_26.md
  Packs/CommonScripts/Scripts/Base64EncodeV2/Base64EncodeV2.yml
  Packs/CommonScripts/Scripts/DT/DT.py
  Packs/CommonScripts/Scripts/DT/DT.yml
  Packs/CommonScripts/Scripts/DT/Pipfile
  Packs/CommonScripts/Scripts/DT/Pipfile.lock
  Packs/CommonScripts/Scripts/DT/README.md
  Packs/CommonScripts/Scripts/DumpJSON/DumpJSON.py
  Packs/CommonScripts/Scripts/DumpJSON/DumpJSON.yml
  Packs/CommonScripts/Scripts/DumpJSON/Pipfile
  Packs/CommonScripts/Scripts/DumpJSON/Pipfile.lock
  Packs/CommonScripts/Scripts/DumpJSON/README.md
  Packs/CommonScripts/Scripts/InRange/InRange.py
  Packs/CommonScripts/Scripts/InRange/InRange.yml
  Packs/CommonScripts/Scripts/InRange/Pipfile
  Packs/CommonScripts/Scripts/InRange/Pipfile.lock
  Packs/CommonScripts/Scripts/InRange/README.md
  Packs/CommonScripts/Scripts/PortListenCheck/Pipfile
  Packs/CommonScripts/Scripts/PortListenCheck/Pipfile.lock
  Packs/CommonScripts/Scripts/PortListenCheck/PortListenCheck.py
  Packs/CommonScripts/Scripts/PortListenCheck/PortListenCheck.yml
  Packs/CommonScripts/Scripts/PortListenCheck/README.md
  Packs/CommonScripts/Scripts/UnPackFile/Pipfile
  Packs/CommonScripts/Scripts/UnPackFile/Pipfile.lock
  Packs/CommonScripts/Scripts/UnPackFile/README.md
  Packs/CommonScripts/Scripts/UnPackFile/UnPackFile.py
  Packs/CommonScripts/Scripts/UnPackFile/UnPackFile.yml
  Packs/CommonScripts/Scripts/script-InRange.yml
  Packs/CommonScripts/Scripts/script-PortListenCheck.yml
  Packs/CommonScripts/Scripts/script-UnPackFile.yml
  Packs/CommonScripts/pack_metadata.json
Labels: bug, docs-approved

#11606 Add vendor id private repo
  Tests/Marketplace/Tests/test_data/metadata.json
  Tests/Marketplace/marketplace_services.py
  Tests/Marketplace/upload_packs.py
  Tests/private_build/tests/test_upload_packs_private.py
  Tests/private_build/upload_packs_private.py
Labels: docs-approved

#11636 Generic Webhook README - add mapping example
  Packs/GenericWebhook/Integrations/GenericWebhook/README.md
  Packs/GenericWebhook/doc_imgs/mapping.png
Labels: docs-approved

#11494 MonoDB pipeline query command
  Packs/MongoDB/Integrations/MongoDB/MongoDB.py
  Packs/MongoDB/Integrations/MongoDB/MongoDB.yml
  Packs/MongoDB/Integrations/MongoDB/MongoDB_test.py
  Packs/MongoDB/Integrations/MongoDB/README.md
  Packs/MongoDB/ReleaseNotes/1_2_1.md
  Packs/MongoDB/pack_metadata.json
Labels: docs-approved

#11642 MS ATA - unskip test
  Tests/conf.json
Labels: docs-approved

#11607 Ml scripts run once
  Packs/Base/ReleaseNotes/1_7_19.md
  Packs/Base/Scripts/FindSimilarIncidentsByText/FindSimilarIncidentsByText.yml
  Packs/Base/pack_metadata.json
  Packs/CommonScripts/ReleaseNotes/1_3_27.md
  Packs/CommonScripts/Scripts/GetDuplicatesMlv2/GetDuplicatesMlv2.yml
  Packs/CommonScripts/pack_metadata.json
Labels: docs-approved

#11582 Archer v2 - modify date format to include ms
  Packs/ArcherRSA/Integrations/ArcherV2/ArcherV2.py
  Packs/ArcherRSA/Integrations/ArcherV2/ArcherV2.yml
  Packs/ArcherRSA/Integrations/ArcherV2/ArcherV2_test.py
  Packs/ArcherRSA/Integrations/ArcherV2/README.md
  Packs/ArcherRSA/ReleaseNotes/1_1_12.md
  Packs/ArcherRSA/pack_metadata.json
Labels: docs-approved, release-notes-only

#11640 MS Graph Handle 404 Response
  Packs/ApiModules/Scripts/MicrosoftApiModule/MicrosoftApiModule.py
  Packs/ApiModules/Scripts/MicrosoftApiModule/MicrosoftApiModule_test.py
  Packs/AzureCompute/ReleaseNotes/1_0_6.md
  Packs/AzureCompute/pack_metadata.json
  Packs/AzureKubernetesServices/ReleaseNotes/1_0_1.md
  Packs/AzureKubernetesServices/pack_metadata.json
  Packs/AzureLogAnalytics/ReleaseNotes/1_0_6.md
  Packs/AzureLogAnalytics/pack_metadata.json
  Packs/AzureNetworkSecurityGroups/ReleaseNotes/1_0_1.md
  Packs/AzureNetworkSecurityGroups/pack_metadata.json
  Packs/AzureSQLManagement/ReleaseNotes/1_0_2.md
  Packs/AzureSQLManagement/pack_metadata.json
  Packs/AzureSecurityCenter/ReleaseNotes/1_1_6.md
  Packs/AzureSecurityCenter/pack_metadata.json
  Packs/AzureSentinel/ReleaseNotes/1_0_7.md
  Packs/AzureSentinel/pack_metadata.json
  Packs/AzureWAF/ReleaseNotes/1_0_2.md
  Packs/AzureWAF/pack_metadata.json
  Packs/EWS/ReleaseNotes/1_8_3.md
  Packs/EWS/pack_metadata.json
  Packs/MicrosoftDefenderAdvancedThreatProtection/ReleaseNotes/1_2_11.md
  Packs/MicrosoftDefenderAdvancedThreatProtection/pack_metadata.json
  Packs/MicrosoftGraphAPI/ReleaseNotes/1_0_1.md
  Packs/MicrosoftGraphAPI/pack_metadata.json
  Packs/MicrosoftGraphApplications/ReleaseNotes/1_0_1.md
  Packs/MicrosoftGraphApplications/pack_metadata.json
  Packs/MicrosoftGraphCalendar/ReleaseNotes/1_0_6.md
  Packs/MicrosoftGraphCalendar/pack_metadata.json
  Packs/MicrosoftGraphDeviceManagement/ReleaseNotes/1_0_7.md
  Packs/MicrosoftGraphDeviceManagement/pack_metadata.json
  Packs/MicrosoftGraphFiles/ReleaseNotes/1_0_6.md
  Packs/MicrosoftGraphFiles/pack_metadata.json
  Packs/MicrosoftGraphGroups/ReleaseNotes/1_0_5.md
  Packs/MicrosoftGraphGroups/pack_metadata.json
  Packs/MicrosoftGraphIdentityandAccess/ReleaseNotes/1_0_1.md
  Packs/MicrosoftGraphIdentityandAccess/pack_metadata.json
  Packs/MicrosoftGraphListener/ReleaseNotes/1_0_12.md
  Packs/MicrosoftGraphListener/pack_metadata.json
  Packs/MicrosoftGraphMail/ReleaseNotes/1_0_15.md
  Packs/MicrosoftGraphMail/pack_metadata.json
  Packs/MicrosoftGraphSecurity/ReleaseNotes/2_0_8.md
  Packs/MicrosoftGraphSecurity/pack_metadata.json
  Packs/MicrosoftGraphUser/Integrations/MicrosoftGraphUser/MicrosoftGraphUser.py
  Packs/MicrosoftGraphUser/Integrations/MicrosoftGraphUser/MicrosoftGraphUser.yml
  Packs/MicrosoftGraphUser/Integrations/MicrosoftGraphUser/MicrosoftGraphUser_test.py
  Packs/MicrosoftGraphUser/ReleaseNotes/1_3_7.md
  Packs/MicrosoftGraphUser/pack_metadata.json
  Packs/MicrosoftManagementActivity/ReleaseNotes/1_1_7.md
  Packs/MicrosoftManagementActivity/pack_metadata.json
  Packs/MicrosoftTeams/ReleaseNotes/1_1_2.md
  Packs/MicrosoftTeams/pack_metadata.json
Labels: docs-approved, release-notes-only

#11643 Temprarily unmocking the playbook until multipart header issue is solved
  Tests/conf.json
Labels: docs-approved

#11649 update docker threshold for powershell images
  Tests/conf.json
Labels: docs-approved

#11459 RF reed bug fix
  Packs/FeedRecordedFuture/Integrations/FeedRecordedFuture/FeedRecordedFuture.py
  Packs/FeedRecordedFuture/Integrations/FeedRecordedFuture/FeedRecordedFuture.yml
  Packs/FeedRecordedFuture/Integrations/FeedRecordedFuture/FeedRecordedFuture_test.py
  Packs/FeedRecordedFuture/Integrations/FeedRecordedFuture/README.md
  Packs/FeedRecordedFuture/ReleaseNotes/1_0_7.md
  Packs/FeedRecordedFuture/pack_metadata.json
Labels: bug, docs-approved, release-notes-only

#11551 Draw canvas script
  Packs/Base/ReleaseNotes/1_7_20.md
  Packs/Base/Scripts/DrawRelatedIncidentsCanvas/DrawRelatedIncidentsCanvas.py
  Packs/Base/Scripts/DrawRelatedIncidentsCanvas/DrawRelatedIncidentsCanvas.yml
  Packs/Base/pack_metadata.json
Labels: docs-approved

#11648 removed duplicated fields
  Packs/FeedIntel471/Integrations/Intel471Actors/Intel471Actors.yml
  Packs/FeedIntel471/Integrations/Intel471Malware/Intel471Malware.yml
  Packs/FeedIntel471/ReleaseNotes/1_1_0.md
  Packs/FeedIntel471/pack_metadata.json
Labels: docs-approved

#11657 Revert "Draw canvas script"
  Packs/Base/ReleaseNotes/1_7_20.md
  Packs/Base/Scripts/DrawRelatedIncidentsCanvas/DrawRelatedIncidentsCanvas.py
  Packs/Base/Scripts/DrawRelatedIncidentsCanvas/DrawRelatedIncidentsCanvas.yml
  Packs/Base/pack_metadata.json
Labels: docs-approved

#10825 Emails campaign detection script
  Packs/Campaign/.pack-ignore
  Packs/Campaign/.secrets-ignore
  Packs/Campaign/README.md
  Packs/Campaign/Scripts/FindEmailCampaign/FindEmailCampaign.py
  Packs/Campaign/Scripts/FindEmailCampaign/FindEmailCampaign.yml
  Packs/Campaign/pack_metadata.json
  Packs/Phishing/ReleaseNotes/2_2_1.md
  Packs/Phishing/Scripts/FindDuplicateEmailIncidents/FindDuplicateEmailIncidents.py
  Packs/Phishing/Scripts/FindDuplicateEmailIncidents/FindDuplicateEmailIncidents.yml
  Packs/Phishing/pack_metadata.json
Labels: docs-approved

#11658 HAFUNIUM New playbook
  Packs/MajorBreachesInvestigationandResponse/Playbooks/playbook-HAFNIUM_-_Exchange_0-day_exploits.yml
  Packs/MajorBreachesInvestigationandResponse/ReleaseNotes/1_4_0.md
  Packs/MajorBreachesInvestigationandResponse/doc_files/HAFNIUM_-_Exchange_0-day_exploits.png
  Packs/MajorBreachesInvestigationandResponse/pack_metadata.json
Labels: docs-approved

#11393 Exabeam Enhancement
  Packs/Exabeam/Integrations/Exabeam/Exabeam.py
  Packs/Exabeam/Integrations/Exabeam/Exabeam.yml
  Packs/Exabeam/Integrations/Exabeam/Exabeam_description.md
  Packs/Exabeam/Integrations/Exabeam/Exabeam_test.py
  Packs/Exabeam/Integrations/Exabeam/README.md
  Packs/Exabeam/Integrations/Exabeam/test_data/response_constants.py
  Packs/Exabeam/Integrations/Exabeam/test_data/result_constants.py
  Packs/Exabeam/ReleaseNotes/2_0_0.md
  Packs/Exabeam/TestPlaybooks/playbook-Exabeam-test.yml
  Packs/Exabeam/pack_metadata.json
Labels: docs-approved

#11563 fix TableToMarkdown
  Packs/Base/ReleaseNotes/1_7_20.md
  Packs/Base/Scripts/CommonServerPython/CommonServerPython.py
  Packs/Base/Scripts/CommonServerPython/CommonServerPython_test.py
  Packs/Base/pack_metadata.json
  Packs/CheckpointFirewall/Integrations/CheckPointFirewall_v2/CheckPointFirewall_v2_test.py
Labels: bug, docs-approved, release-notes-only

#11664 MicrosoftApiModule: Fix ok codes
  Packs/ApiModules/Scripts/MicrosoftApiModule/MicrosoftApiModule.py
  Packs/AzureCompute/ReleaseNotes/1_0_7.md
  Packs/AzureCompute/pack_metadata.json
  Packs/AzureKubernetesServices/ReleaseNotes/1_0_2.md
  Packs/AzureKubernetesServices/pack_metadata.json
  Packs/AzureLogAnalytics/ReleaseNotes/1_0_7.md
  Packs/AzureLogAnalytics/pack_metadata.json
  Packs/AzureNetworkSecurityGroups/ReleaseNotes/1_0_2.md
  Packs/AzureNetworkSecurityGroups/pack_metadata.json
  Packs/AzureSQLManagement/ReleaseNotes/1_0_3.md
  Packs/AzureSQLManagement/pack_metadata.json
  Packs/AzureSecurityCenter/ReleaseNotes/1_1_7.md
  Packs/AzureSecurityCenter/pack_metadata.json
  Packs/AzureSentinel/ReleaseNotes/1_0_8.md
  Packs/AzureSentinel/pack_metadata.json
  Packs/AzureWAF/ReleaseNotes/1_0_3.md
  Packs/AzureWAF/pack_metadata.json
  Packs/EWS/ReleaseNotes/1_8_4.md
  Packs/EWS/pack_metadata.json
  Packs/MicrosoftDefenderAdvancedThreatProtection/ReleaseNotes/1_2_12.md
  Packs/MicrosoftDefenderAdvancedThreatProtection/pack_metadata.json
  Packs/MicrosoftGraphAPI/ReleaseNotes/1_0_2.md
  Packs/MicrosoftGraphAPI/pack_metadata.json
  Packs/MicrosoftGraphApplications/ReleaseNotes/1_0_2.md
  Packs/MicrosoftGraphApplications/pack_metadata.json
  Packs/MicrosoftGraphCalendar/ReleaseNotes/1_0_7.md
  Packs/MicrosoftGraphCalendar/pack_metadata.json
  Packs/MicrosoftGraphDeviceManagement/ReleaseNotes/1_0_8.md
  Packs/MicrosoftGraphDeviceManagement/pack_metadata.json
  Packs/MicrosoftGraphFiles/ReleaseNotes/1_0_7.md
  Packs/MicrosoftGraphFiles/pack_metadata.json
  Packs/MicrosoftGraphGroups/ReleaseNotes/1_0_6.md
  Packs/MicrosoftGraphGroups/pack_metadata.json
  Packs/MicrosoftGraphIdentityandAccess/ReleaseNotes/1_0_2.md
  Packs/MicrosoftGraphIdentityandAccess/pack_metadata.json
  Packs/MicrosoftGraphListener/ReleaseNotes/1_0_13.md
  Packs/MicrosoftGraphListener/pack_metadata.json
  Packs/MicrosoftGraphMail/ReleaseNotes/1_0_16.md
  Packs/MicrosoftGraphMail/pack_metadata.json
  Packs/MicrosoftGraphSecurity/ReleaseNotes/2_0_9.md
  Packs/MicrosoftGraphSecurity/pack_metadata.json
  Packs/MicrosoftGraphUser/ReleaseNotes/1_3_8.md
  Packs/MicrosoftGraphUser/pack_metadata.json
  Packs/MicrosoftManagementActivity/ReleaseNotes/1_1_8.md
  Packs/MicrosoftManagementActivity/pack_metadata.json
  Packs/MicrosoftTeams/ReleaseNotes/1_1_3.md
  Packs/MicrosoftTeams/pack_metadata.json
Labels: bug, docs-approved, release-notes-only

#11388 Validate Content script
  Packs/Base/ReleaseNotes/1_7_21.md
  Packs/Base/Scripts/ValidateContent/Pipfile
  Packs/Base/Scripts/ValidateContent/Pipfile.lock
  Packs/Base/Scripts/ValidateContent/README.md
  Packs/Base/Scripts/ValidateContent/ValidateContent.py
  Packs/Base/Scripts/ValidateContent/ValidateContent.yml
  Packs/Base/Scripts/ValidateContent/ValidateContent_test.py
  Packs/Base/Scripts/ValidateContent/test_data/contentpack-6ade7368-803c-4c4b-873c-4a0555c6ca03-Test.zip
  Packs/Base/TestPlaybooks/ValidateContent_-_Test.yml
  Packs/Base/pack_metadata.json
Labels: docs-approved

#11672 Campaign: Update pack_metadata.json - fix typo in name
  Packs/Campaign/pack_metadata.json
Labels: docs-approved

#11586 Upload-Flow Refinement
  Tests/Marketplace/upload_packs.py
  Tests/scripts/slack_notifier.py
  Tests/scripts/validate_index.py
  Tests/scripts/validate_premium_packs.py
  Tests/scripts/validate_premium_packs.sh
Labels: docs-approved

#11671 Jira fix create ticket HR
  Packs/Jira/Integrations/JiraV2/JiraV2.py
  Packs/Jira/Integrations/JiraV2/JiraV2.yml
  Packs/Jira/ReleaseNotes/1_2_12.md
  Packs/Jira/pack_metadata.json
Labels: bug, docs-approved, release-notes-only

#11660 Fixing missing notable events issue
  Packs/SplunkPy/Integrations/SplunkPy/SplunkPy.py
  Packs/SplunkPy/Integrations/SplunkPy/SplunkPy.yml
  Packs/SplunkPy/Integrations/SplunkPy/SplunkPy_test.py
  Packs/SplunkPy/ReleaseNotes/1_3_1.md
  Packs/SplunkPy/pack_metadata.json
Labels: docs-approved

#11653 EWS - Security&Compliance - Search Action Limit Fix
  Packs/EWS/Integrations/SecurityAndCompliance/SecurityAndCompliance.ps1
  Packs/EWS/ReleaseNotes/1_8_5.md
  Packs/EWS/pack_metadata.json
Labels: bug, docs-approved, release-notes-only

#11008 adding fetch limit, aggregate fetch and fields to fetch
  Packs/ArcSightLogger/Integrations/integration-ArcSightLogger.yml
  Packs/ArcSightLogger/ReleaseNotes/1_0_2.md
  Packs/ArcSightLogger/pack_metadata.json
Labels: docs-approved, ready-for-instance-test

#11541 Cyberint - new mapper, classifier, layouts and incident fields.
  Packs/Cyberint/Classifiers/classifier-mapper-incoming-CyberInt.json
  Packs/Cyberint/IncidentFields/incidentfield-Cyberint_CyberInt_Alert_ID.json
  Packs/Cyberint/IncidentFields/incidentfield-Cyberint_CyberInt_Attachments.json
  Packs/Cyberint/IncidentFields/incidentfield-Cyberint_CyberInt_Closure_reason.json
  Packs/Cyberint/IncidentFields/incidentfield-Cyberint_CyberInt_Confidence.json
  Packs/Cyberint/IncidentFields/incidentfield-Cyberint_CyberInt_Created_by .json
  Packs/Cyberint/IncidentFields/incidentfield-Cyberint_CyberInt_Created_date.json
  Packs/Cyberint/IncidentFields/incidentfield-Cyberint_CyberInt_Description.json
  Packs/Cyberint/IncidentFields/incidentfield-Cyberint_CyberInt_Expert_Analysis.json
  Packs/Cyberint/IncidentFields/incidentfield-Cyberint_CyberInt_Impact.json
  Packs/Cyberint/IncidentFields/incidentfield-Cyberint_CyberInt_Recommendation.json
  Packs/Cyberint/IncidentFields/incidentfield-Cyberint_CyberInt_Related_IOCs.json
  Packs/Cyberint/IncidentFields/incidentfield-Cyberint_CyberInt_Related_entities.json
  Packs/Cyberint/IncidentFields/incidentfield-Cyberint_CyberInt_Source.json
  Packs/Cyberint/IncidentFields/incidentfield-Cyberint_CyberInt_Source_category.json
  Packs/Cyberint/IncidentFields/incidentfield-Cyberint_CyberInt_Status.json
  Packs/Cyberint/IncidentFields/incidentfield-Cyberint_CyberInt_Tags.json
  Packs/Cyberint/IncidentFields/incidentfield-Cyberint_CyberInt_Targeted_Brand.json
  Packs/Cyberint/IncidentFields/incidentfield-Cyberint_CyberInt_Targeted_Vector.json
  Packs/Cyberint/IncidentFields/incidentfield-Cyberint_CyberInt_Threat_Actor.json
  Packs/Cyberint/IncidentFields/incidentfield-Cyberint_CyberInt_Ticket_ID.json
  Packs/Cyberint/IncidentFields/incidentfield-Cyberint_CyberInt_Title.json
  Packs/Cyberint/IncidentFields/incidentfield-Cyberint_CyberInt_Type.json
  Packs/Cyberint/IncidentFields/incidentfield-Cyberint_CyberInt_Vulnerable_CName_Record.json
  Packs/Cyberint/IncidentFields/incidentfield-Cyberint_Cyberint_Category.json
  Packs/Cyberint/Layouts/layoutscontainer-Cyberint_Incident_Layout.json
  Packs/Cyberint/ReleaseNotes/1_0_3.md
  Packs/Cyberint/pack_metadata.json
Labels: Contribution, Partner, docs-approved, post-demo

#11183 Creates MITRE ATT&CK indicators When fetching STIX Reports
  Packs/FeedMitreAttack/IndicatorFields/incidentfield-mitrecourseofaction.json
  Packs/FeedMitreAttack/Layouts/layout-indicatorsDetails-MITRE_ATT&CK.json
  Packs/FeedMitreAttack/Layouts/layoutscontainer-MITRE_ATT&CK.json
  Packs/FeedMitreAttack/ReleaseNotes/1_1_10.md
  Packs/FeedMitreAttack/pack_metadata.json
  Packs/FeedUnit42/Integrations/FeedUnit42/FeedUnit42.py
  Packs/FeedUnit42/Integrations/FeedUnit42/FeedUnit42.yml
  Packs/FeedUnit42/Integrations/FeedUnit42/FeedUnit42_test.py
  Packs/FeedUnit42/Integrations/FeedUnit42/README.md
  Packs/FeedUnit42/Integrations/FeedUnit42/test_data/feed_data.py
  Packs/FeedUnit42/ReleaseNotes/1_1_1.md
  Packs/FeedUnit42/pack_metadata.json
Labels: docs-approved

#11665 Fix endpoint enrichment v2.1 test
  Packs/CrowdStrikeHost/TestPlaybooks/playbook-CrowdStrike_Endpoint_Enrichment_-_Test.yml
  Packs/CrowdStrikeHost/TestPlaybooks/playbook-CrowdStrike_FalconHost_test.yml
  Packs/CrowdStrikeHost/TestPlaybooks/playbook-Search_Endpoints_By_Hash_-_CrowdStrike_-_Test.yml
  Packs/Cylance_Protect/TestPlaybooks/playbook-Endpoint_Enrichment_-_Generic_Test.yml
  Tests/conf.json
Labels: docs-approved

#11521 PAN-OS enhancements
  Packs/PAN-OS/Integrations/Panorama/Panorama.py
  Packs/PAN-OS/Integrations/Panorama/Panorama.yml
  Packs/PAN-OS/Integrations/Panorama/Panorama_test.py
  Packs/PAN-OS/Integrations/Panorama/README.md
  Packs/PAN-OS/Integrations/Panorama/command_examples.txt
  Packs/PAN-OS/ReleaseNotes/1_6_15.md
  Packs/PAN-OS/TestPlaybooks/playbook-palo_alto_firewall_test_pb.yml
  Packs/PAN-OS/TestPlaybooks/playbook-palo_alto_panorama_test_pb.yml
  Packs/PAN-OS/pack_metadata.json
Labels: docs-approved

#11656 Fixed multiple bugs with Cortex XDR Incident Handling v3
  Packs/CortexXDR/Playbooks/Cortex_XDR_incident_handling_v3.yml
  Packs/CortexXDR/Playbooks/Cortex_XDR_incident_handling_v3_README.md
  Packs/CortexXDR/ReleaseNotes/2_9_1.md
  Packs/CortexXDR/doc_files/Cortex_XDR_incident_handling_v3.png
  Packs/CortexXDR/pack_metadata.json
Labels: docs-approved, release-notes-only

#11680 fix in exabeam readme
  Packs/Exabeam/Integrations/Exabeam/README.md
Labels: docs-approved

#11585 Trigger a private repo build when changing infrastructure code in content
  .circleci/config.yml
  Utils/get_private_build_status.py
  Utils/tests/trigger_private_build_test.py
  Utils/trigger_private_build.py
Labels: docs-approved

#11684 Palo Alto Networks PAN-OS EDL Management (Deprecated)
  Packs/PaloAltoNetworks_PAN_OS_EDL_Management/Integrations/PaloAltoNetworks_PAN_OS_EDL_Management/PaloAltoNetworks_PAN_OS_EDL_Management.yml
  Packs/PaloAltoNetworks_PAN_OS_EDL_Management/ReleaseNotes/1_0_2.md
  Packs/PaloAltoNetworks_PAN_OS_EDL_Management/pack_metadata.json
  Tests/conf.json
Labels: docs-approved, release-notes-only

#11630 Contrib/concentric ai -> Playbook enhancement.
  Packs/ConcentricAI/Integrations/ConcentricAI/ConcentricAI.py
  Packs/ConcentricAI/Integrations/ConcentricAI/ConcentricAI.yml
  Packs/ConcentricAI/Playbooks/ConcentricAI_Demo.yml
  Packs/ConcentricAI/ReleaseNotes/1_2_0.md
  Packs/ConcentricAI/pack_metadata.json
  Tests/conf.json
  package-lock.json
Labels: Contribution, Partner, docs-approved, ready-for-instance-test

#11151 Added Code42 to generic file retrieval, skipped unavailable playbooks
  Packs/CommonPlaybooks/Playbooks/playbook-Get_File_Sample_By_Hash_-_Generic_v3.yml
  Packs/CommonPlaybooks/Playbooks/playbook-Get_File_Sample_By_Hash_-_Generic_v3_README.md
  Packs/CommonPlaybooks/Playbooks/playbook-Get_File_Sample_From_Path_-_Generic_V2.yml
  Packs/CommonPlaybooks/ReleaseNotes/1_9_0.md
  Packs/CommonPlaybooks/doc_files/Get_File_Sample_By_Hash_-_Generic_v3.png
  Packs/CommonPlaybooks/pack_metadata.json
Labels: docs-approved

#11693 Azure readme fix
  Packs/AzureNetworkSecurityGroups/Integrations/AzureNetworkSecurityGroups/README.md
Labels: docs-approved

#11688 sdk 1-3-1 release
  dev-requirements-py3.txt
Labels: docs-approved

#11432 Ops genie v2
  Packs/Opsgeniev2/.pack-ignore
  Packs/Opsgeniev2/.secrets-ignore
  Packs/Opsgeniev2/Integrations/Opsgeniev2/Opsgeniev2.py
  Packs/Opsgeniev2/Integrations/Opsgeniev2/Opsgeniev2.yml
  Packs/Opsgeniev2/Integrations/Opsgeniev2/Opsgeniev2_description.md
  Packs/Opsgeniev2/Integrations/Opsgeniev2/Opsgeniev2_image.png
  Packs/Opsgeniev2/Integrations/Opsgeniev2/Opsgeniev2_test.py
  Packs/Opsgeniev2/Integrations/Opsgeniev2/README.md
  Packs/Opsgeniev2/Integrations/Opsgeniev2/examples.txt
  Packs/Opsgeniev2/Integrations/Opsgeniev2/test_data/ack_alert.json
  Packs/Opsgeniev2/Integrations/Opsgeniev2/test_data/close_alert.json
  Packs/Opsgeniev2/Integrations/Opsgeniev2/test_data/create_alert.json
  Packs/Opsgeniev2/Integrations/Opsgeniev2/test_data/delete_alert.json
  Packs/Opsgeniev2/Integrations/Opsgeniev2/test_data/get_alert.json
  Packs/Opsgeniev2/Integrations/Opsgeniev2/test_data/get_schedules.json
  Packs/Opsgeniev2/Integrations/Opsgeniev2/test_data/list_alerts.json
  Packs/Opsgeniev2/Integrations/Opsgeniev2/test_data/list_alerts_empty.json
  Packs/Opsgeniev2/Integrations/Opsgeniev2/test_data/list_alerts_paged.json
  Packs/Opsgeniev2/Integrations/Opsgeniev2/test_data/list_schedules.json
  Packs/Opsgeniev2/Integrations/Opsgeniev2/test_data/on_call.json
  Packs/Opsgeniev2/Integrations/Opsgeniev2/tutorial_images/add_api_key.png
  Packs/Opsgeniev2/TestPlaybooks/OpsGenieV2_-_Test_Playbook.yml
  Packs/Opsgeniev2/pack_metadata.json
Labels: Contribution, docs-approved, ready-for-instance-test

#11700 Trigger private build fixes
  .circleci/config.yml
  Utils/get_private_build_status.py
  Utils/trigger_private_build.py
Labels: docs-approved

#11686 Rasterize 4.5 Test - adjust test from and to version
  Packs/rasterize/TestPlaybooks/playbook-Rasterize_4.5_Test.yml
Labels: docs-approved

#11692 Marketplace: Add landingPage sections and tags
  Tests/Marketplace/Tests/marketplace_services_test.py
  Tests/Marketplace/landingPage_sections.json
  Tests/Marketplace/marketplace_services.py
  Tests/Marketplace/upload_packs.py
  Tests/private_build/upload_packs_private.py
Labels: docs-approved

#11699 Cortex XDR - handle empty params and timeout
  Packs/CortexXDR/Integrations/CortexXDRIR/CortexXDRIR.py
  Packs/CortexXDR/Integrations/CortexXDRIR/CortexXDRIR.yml
  Packs/CortexXDR/Integrations/CortexXDRIR/CortexXDRIR_test.py
  Packs/CortexXDR/ReleaseNotes/2_9_2.md
  Packs/CortexXDR/TestPlaybooks/Test_XDR_Playbook.yml
  Packs/CortexXDR/pack_metadata.json
Labels: docs-approved, release-notes-only

#11714 Gfreund mp ownership
  .github/CODEOWNERS
Labels: docs-approved

#11707 removing vendorName from upload process
  Tests/Marketplace/marketplace_services.py
  Tests/Marketplace/upload_packs.py
  Tests/private_build/tests/test_upload_packs_private.py
  Tests/private_build/upload_packs_private.py
Labels: docs-approved

#11725 bump back jira docker version because Outh1() was broken
  Packs/Jira/Integrations/JiraV2/JiraV2.yml
  Packs/Jira/ReleaseNotes/1_2_13.md
  Packs/Jira/pack_metadata.json
Labels: docs-approved, release-notes-only

#11543 [Contribution] abuseipdb-get-blacklist confidenceMinimum addition
  Packs/AbuseDB/Integrations/AbuseDB/AbuseDB.py
  Packs/AbuseDB/Integrations/AbuseDB/AbuseDB.yml
  Packs/AbuseDB/Integrations/AbuseDB/README.md
  Packs/AbuseDB/ReleaseNotes/1_0_2.md
  Packs/AbuseDB/Scripts/AbuseIPDBPopulateIndicators/AbuseIPDBPopulateIndicators.py
  Packs/AbuseDB/Scripts/AbuseIPDBPopulateIndicators/AbuseIPDBPopulateIndicators.yml
  Packs/AbuseDB/Scripts/AbuseIPDBPopulateIndicators/Pipfile
  Packs/AbuseDB/Scripts/AbuseIPDBPopulateIndicators/Pipfile.lock
  Packs/AbuseDB/Scripts/AbuseIPDBPopulateIndicators/README.md
  Packs/AbuseDB/Scripts/script-AbuseIPDBPopulateIndicators.yml
  Packs/AbuseDB/pack_metadata.json
Labels: Contribution, docs-approved, ready-for-instance-test

#11348 Digital shadows fix incident ingest
  Packs/DigitalShadows/Integrations/integration-DigitalShadows.yml
  Packs/DigitalShadows/Playbooks/Playbook-Digital_Shadows_Retrieve_Exposed_Credentials.yml
  Packs/DigitalShadows/ReleaseNotes/1_0_1.md
  Packs/DigitalShadows/pack_metadata.json
Labels: Contribution, Partner, docs-approved

#11742 exabeam doc - html to md
  Packs/Exabeam/Integrations/Exabeam/README.md
Labels: docs-approved

#11706 added reliability to common server python
  Packs/Base/ReleaseNotes/1_7_22.md
  Packs/Base/Scripts/CommonServerPython/CommonServerPython.py
  Packs/Base/pack_metadata.json
Labels: docs-approved, release-notes-only

#11747 Protect landing-page sections file
  .github/CODEOWNERS
Labels: docs-approved

#11741 Update HAFNIUM readme
  Packs/MajorBreachesInvestigationandResponse/Playbooks/playbook-HAFNIUM_-_Exchange_0-day_exploits_5_5_README.md
  Packs/MajorBreachesInvestigationandResponse/README.md
  Packs/MajorBreachesInvestigationandResponse/doc_files/espionage-r3d3-small.png
  Packs/MajorBreachesInvestigationandResponse/pack_metadata.json
Labels: docs-approved

#11753 HUFNIUM | Playbook update
  Packs/MajorBreachesInvestigationandResponse/Playbooks/playbook-HAFNIUM_-_Exchange_0-day_exploits_6.yml
  Packs/MajorBreachesInvestigationandResponse/ReleaseNotes/1_4_2.md
  Packs/MajorBreachesInvestigationandResponse/doc_files/HAFNIUM_-_Exchange_0-day_exploits_6.png
  Packs/MajorBreachesInvestigationandResponse/pack_metadata.json
Labels: docs-approved

#11761 EWS Extenstion Powershell: Fixed removed test
  Packs/EWS/TestPlaybooks/O365-EWS-Extension-Powershell-Online-V2-Test.yml
Labels: docs-approved

#11763 Add EWSO365 integration id to send-mail task
  Packs/EWS/TestPlaybooks/playbook-EWS-Searchmailbox-Test.yml
Labels: docs-approved

#11757 GraphQL - bump docker image tag
  Packs/GraphQL/Integrations/GraphQL/GraphQL.yml
  Packs/GraphQL/ReleaseNotes/1_0_1.md
  Packs/GraphQL/pack_metadata.json
Labels: docs-approved

#10308 Ransomware
  Packs/Active_Directory_Query/Playbooks/playbook-Active_Directory_Investigation.yml
  Packs/Active_Directory_Query/Playbooks/playbook-Active_Directory_Investigation_README.md
  Packs/Active_Directory_Query/ReleaseNotes/1_1_7.md
  Packs/Active_Directory_Query/doc_files/Active_Directory_Investigation.png
  Packs/Active_Directory_Query/pack_metadata.json
  Packs/CommonTypes/IncidentFields/incidentfield-Hostnames.json
  Packs/CommonTypes/IndicatorTypes/reputation-Onion_Address.json
  Packs/CommonTypes/ReleaseNotes/2_8_7.md
  Packs/CommonTypes/pack_metadata.json
  Packs/Ransomware/IncidentFields/incidentfield-Ransomware_Approximate_Number_Of_Encrypted_Endpoints.json
  Packs/Ransomware/IncidentFields/incidentfield-Ransomware_Cryptocurrency_Address.json
  Packs/Ransomware/IncidentFields/incidentfield-Ransomware_Cryptocurrency_Address_Type.json
  Packs/Ransomware/IncidentFields/incidentfield-Ransomware_Data_Encryption_Status.json
  Packs/Ransomware/IncidentFields/incidentfield-Ransomware_Email.json
  Packs/Ransomware/IncidentFields/incidentfield-Ransomware_Encrypted_File_Owner.json
  Packs/Ransomware/IncidentFields/incidentfield-Ransomware_Note.json
  Packs/Ransomware/IncidentFields/incidentfield-Ransomware_Onion_Address.json
  Packs/Ransomware/IncidentFields/incidentfield-Ransomware_Recovery_Tool.json
  Packs/Ransomware/IncidentFields/incidentfield-Ransomware_Strain.json
  Packs/Ransomware/IncidentTypes/incidenttype-Post_Intrusion_Ransomware.json
  Packs/Ransomware/Layouts/layoutscontainer-Post_Intrusion_Ransomware.json
  Packs/Ransomware/Playbooks/playbook-Post_Intrusion_Ransomware_Investigation.yml
  Packs/Ransomware/Playbooks/playbook-Post_Intrusion_Ransomware_Investigation_README.md
  Packs/Ransomware/README.md
  Packs/Ransomware/ReleaseNotes/1_0_3.md
  Packs/Ransomware/Scripts/RansomwareDataEncryptionStatus/RansomwareDataEncryptionStatus.py
  Packs/Ransomware/Scripts/RansomwareDataEncryptionStatus/RansomwareDataEncryptionStatus.yml
  Packs/Ransomware/Scripts/RansomwareHostWidget/RansomwareHostWidget.py
  Packs/Ransomware/Scripts/RansomwareHostWidget/RansomwareHostWidget.yml
  Packs/Ransomware/doc_files/Post_Intrusion_Ransomware_Investigation.png
  Packs/Ransomware/doc_files/Post_Intrusion_Ransomware_Investigation_Layout.png
  Packs/Ransomware/pack_metadata.json
Labels: docs-approved

#11771 Hafnium | SIEM updates
  Packs/MajorBreachesInvestigationandResponse/Playbooks/playbook-HAFNIUM_-_Exchange_0-day_exploits_5_5.yml
  Packs/MajorBreachesInvestigationandResponse/Playbooks/playbook-HAFNIUM_-_Exchange_0-day_exploits_6.yml
  Packs/MajorBreachesInvestigationandResponse/Playbooks/playbook-HAFNIUM_-_Exchange_0-day_exploits_6_README.md
  Packs/MajorBreachesInvestigationandResponse/README.md
  Packs/MajorBreachesInvestigationandResponse/ReleaseNotes/1_4_3.md
  Packs/MajorBreachesInvestigationandResponse/doc_files/HAFNIUM_-_Exchange_0-day_exploits.png
  Packs/MajorBreachesInvestigationandResponse/doc_files/HAFNIUM_-_Exchange_0-day_exploits5_5.png
  Packs/MajorBreachesInvestigationandResponse/doc_files/HAFNIUM_-_Exchange_0-day_exploits_6.png
  Packs/MajorBreachesInvestigationandResponse/pack_metadata.json
Labels: docs-approved

#11581 WF - added the wildfire-get-url-webartifacts cmd and report more outputs
  Packs/Palo_Alto_Networks_WildFire/.secrets-ignore
  Packs/Palo_Alto_Networks_WildFire/Integrations/Palo_Alto_Networks_WildFire_v2/Palo_Alto_Networks_WildFire_v2.py
  Packs/Palo_Alto_Networks_WildFire/Integrations/Palo_Alto_Networks_WildFire_v2/Palo_Alto_Networks_WildFire_v2.yml
  Packs/Palo_Alto_Networks_WildFire/Integrations/Palo_Alto_Networks_WildFire_v2/README.md
  Packs/Palo_Alto_Networks_WildFire/Integrations/Palo_Alto_Networks_WildFire_v2/command_examples.txt
  Packs/Palo_Alto_Networks_WildFire/Playbooks/playbook-Detonate_URL_-_WildFire-v2.1.yml
  Packs/Palo_Alto_Networks_WildFire/Playbooks/playbook-Detonate_URL_-_WildFire-v2_README.md
  Packs/Palo_Alto_Networks_WildFire/ReleaseNotes/1_3_0.md
  Packs/Palo_Alto_Networks_WildFire/TestPlaybooks/playbook-Detonate_URL_-_WildFire-v2.1_-_Test.yml
  Packs/Palo_Alto_Networks_WildFire/pack_metadata.json
Labels: docs-approved

#11775 IsRFC1918Address - Fixed an issue where the script was not working as a transformer.
  Packs/CommonScripts/ReleaseNotes/1_3_28.md
  Packs/CommonScripts/Scripts/IsRFC1918Address/IsRFC1918Address.py
  Packs/CommonScripts/Scripts/IsRFC1918Address/IsRFC1918Address.yml
  Packs/CommonScripts/Scripts/IsRFC1918Address/IsRFC1918Address_test.py
  Packs/CommonScripts/Scripts/IsRFC1918Address/README.md
  Packs/CommonScripts/TestPlaybooks/playbook-IsRFC1918_Test.yml
  Packs/CommonScripts/pack_metadata.json
Labels: bug, docs-approved, release-notes-only

#11773 unskip Generic Webhook - Test TPB
  Tests/conf.json
Labels: docs-approved

#11770 rename context polling readme to proper name
  Packs/CommonPlaybooks/Playbooks/playbook-Context_Polling_-_Generic_README.md
Labels: docs-approved

#11554 Microsoft Graph API - add note about in case unsupported top resource
  Packs/MicrosoftGraphAPI/Integrations/MicrosoftGraphAPI/README.md
Labels: docs-approved

#11673 EWS Extension Online Powershell v2 - add note about exo v2
  Packs/EWS/Integrations/EwsExtensionEXOPowershellV2/README.md
Labels: docs-approved

#11626 pwsh: fix FileResult
  Packs/Base/ReleaseNotes/1_7_23.md
  Packs/Base/Scripts/CommonServerPowerShell/CommonServerPowerShell.Tests.ps1
  Packs/Base/Scripts/CommonServerPowerShell/CommonServerPowerShell.ps1
  Packs/Base/TestPlaybooks/playbook-PowerShellCommon-Test.yml
  Packs/Base/pack_metadata.json
Labels: docs-approved

#11772 Error msgs in QRadar_v2
  Packs/QRadar/Integrations/QRadar_v2/QRadar_v2.py
  Packs/QRadar/Integrations/QRadar_v2/QRadar_v2.yml
  Packs/QRadar/ReleaseNotes/1_2_12.md
  Packs/QRadar/pack_metadata.json
Labels: docs-approved, release-notes-only

#11784 Fixed an issue where an empty S3 bucket would cause a key error
  Packs/AWS-S3/Integrations/AWS-S3/AWS-S3.py
  Packs/AWS-S3/Integrations/AWS-S3/AWS-S3.yml
  Packs/AWS-S3/ReleaseNotes/1_0_4.md
  Packs/AWS-S3/pack_metadata.json
Labels: bug, docs-approved

#11787 Add gmail id to send-mail command on test playbook
  Packs/Gmail/TestPlaybooks/playbook-GmailTest.yml
Labels: docs-approved

#11786 Joe Security - non english chars
  Packs/JoeSecurity/Integrations/JoeSecurity/JoeSecurity.py
  Packs/JoeSecurity/ReleaseNotes/1_0_4.md
  Packs/JoeSecurity/TestPlaybooks/playbook-JoeSecurityTestDetonation.yml
  Packs/JoeSecurity/pack_metadata.json
Labels: bug, docs-approved, release-notes-only

#11734 Add retries to playbook-Office_365_Search_and_Delete.yml
  Packs/EWS/Playbooks/playbook-O365-SecurityAndCompliance-Search.yml
  Packs/EWS/Playbooks/playbook-Office_365_Search_and_Delete.yml
  Packs/EWS/ReleaseNotes/1_8_7.md
  Packs/EWS/pack_metadata.json
  Tests/conf.json
Labels: docs-approved

#11748 CyberInt - Add missing fields to documentation
  Packs/Cyberint/Integrations/Cyberint/Cyberint.yml
  Packs/Cyberint/Integrations/Cyberint/README.md
  Packs/Cyberint/README.md
  Packs/Cyberint/ReleaseNotes/1_0_4.md
  Packs/Cyberint/pack_metadata.json
Labels: Contribution, Partner, docs-approved, ready-for-instance-test

#11799 Avoid test contrib PR to trigger gh workflows
  .github/workflows/check-contributor-pack.yml
  .github/workflows/handle-new-external-pr.yml
Labels: docs-approved

#11764 Mail Listener v2 - improve handling of first fetch time
  Packs/MailListener/Integrations/MailListenerV2/MailListenerV2.py
  Packs/MailListener/Integrations/MailListenerV2/MailListenerV2.yml
  Packs/MailListener/ReleaseNotes/1_0_3.md
  Packs/MailListener/pack_metadata.json
Labels: docs-approved, release-notes-only

#11803 Ransomware fixes
  Packs/CommonTypes/IncidentFields/incidentfield-Hostnames.json
  Packs/CommonTypes/ReleaseNotes/2_8_8.md
  Packs/CommonTypes/pack_metadata.json
  Packs/Ransomware/README.md
Labels: docs-approved

#11796 landing page: update featured and sections
  Tests/Marketplace/landingPage_sections.json
Labels: docs-approved

#11791 GetFailedTasks - Added a hard limit to the number of incidents that c…
  Packs/IntegrationsAndIncidentsHealthCheck/ReleaseNotes/1_1_17.md
  Packs/IntegrationsAndIncidentsHealthCheck/Scripts/GetFailedTasks/GetFailedTasks.py
  Packs/IntegrationsAndIncidentsHealthCheck/Scripts/GetFailedTasks/GetFailedTasks.yml
  Packs/IntegrationsAndIncidentsHealthCheck/Scripts/GetFailedTasks/GetFailedTasks_test.py
  Packs/IntegrationsAndIncidentsHealthCheck/Scripts/GetFailedTasks/README.md
  Packs/IntegrationsAndIncidentsHealthCheck/pack_metadata.json
Labels: bug, docs-approved, release-notes-only

#11677 Jira V2 - fixed command jira-get-id-by-attribute to return only active users
  Packs/Jira/Integrations/JiraV2/JiraV2.py
  Packs/Jira/Integrations/JiraV2/JiraV2.yml
  Packs/Jira/Integrations/JiraV2/README.md
  Packs/Jira/ReleaseNotes/1_2_14.md
  Packs/Jira/TestPlaybooks/playbook-Jira-v2-Test.yml
  Packs/Jira/pack_metadata.json
Labels: docs-approved, release-notes-only

#11669 Gamma.AI content pack for Cortex XSOAR integration
  Packs/Gamma/.pack-ignore
  Packs/Gamma/.secrets-ignore
  Packs/Gamma/Integrations/Gamma/Gamma.py
  Packs/Gamma/Integrations/Gamma/Gamma.yml
  Packs/Gamma/Integrations/Gamma/Gamma_description.md
  Packs/Gamma/Integrations/Gamma/Gamma_image.png
  Packs/Gamma/Integrations/Gamma/Gamma_test.py
  Packs/Gamma/Integrations/Gamma/Pipfile
  Packs/Gamma/Integrations/Gamma/Pipfile.lock
  Packs/Gamma/Integrations/Gamma/README.md
  Packs/Gamma/Integrations/Gamma/command-examples.txt
  Packs/Gamma/README.md
  Packs/Gamma/TestPlaybooks/Gamma_Warning_Notice.yml
  Packs/Gamma/TestPlaybooks/README.md
  Packs/Gamma/pack_metadata.json
Labels: Contribution, Partner, docs-approved, post-demo, ready-for-instance-test

#11448 PR for Qualys FIM
  Packs/QualysFIM/.pack-ignore
  Packs/QualysFIM/.secrets-ignore
  Packs/QualysFIM/Classifiers/classifier-QualysFIM_Mapper.json
  Packs/QualysFIM/Classifiers/classifier-QualysFim_Classifier.json
  Packs/QualysFIM/IncidentFields/incidentfield-Qualys_FIM_Alert_ID.json
  Packs/QualysFIM/IncidentFields/incidentfield-Qualys_FIM_Alert_Name.json
  Packs/QualysFIM/IncidentFields/incidentfield-Qualys_FIM_Approval_Date.json
  Packs/QualysFIM/IncidentFields/incidentfield-Qualys_FIM_Approval_Status.json
  Packs/QualysFIM/IncidentFields/incidentfield-Qualys_FIM_Approval_Type.json
  Packs/QualysFIM/IncidentFields/incidentfield-Qualys_FIM_Assigned_Date.json
  Packs/QualysFIM/IncidentFields/incidentfield-Qualys_FIM_Changed_Type.json
  Packs/QualysFIM/IncidentFields/incidentfield-Qualys_FIM_Comment.json
  Packs/QualysFIM/IncidentFields/incidentfield-Qualys_FIM_Created_By.json
  Packs/QualysFIM/IncidentFields/incidentfield-Qualys_FIM_Created_Date.json
  Packs/QualysFIM/IncidentFields/incidentfield-Qualys_FIM_Event_Type.json
  Packs/QualysFIM/IncidentFields/incidentfield-Qualys_FIM_Last_Updated_By.json
  Packs/QualysFIM/IncidentFields/incidentfield-Qualys_FIM_Query.json
  Packs/QualysFIM/IncidentFields/incidentfield-Qualys_FIM_Reviewers.json
  Packs/QualysFIM/IncidentFields/incidentfield-Qualys_FIM_Status.json
  Packs/QualysFIM/IncidentFields/incidentfield-Qualys_FIM_Updated_Date.json
  Packs/QualysFIM/IncidentTypes/customIncidentTypes.json
  Packs/QualysFIM/Integrations/Qualys/QualysFIM.py
  Packs/QualysFIM/Integrations/Qualys/QualysFIM.yml
  Packs/QualysFIM/Integrations/Qualys/QualysFIM_description.md
  Packs/QualysFIM/Integrations/Qualys/QualysFIM_image.png
  Packs/QualysFIM/Integrations/Qualys/QualysFIM_test.py
  Packs/QualysFIM/Integrations/Qualys/README.md
  Packs/QualysFIM/Integrations/Qualys/command_examples.txt
  Packs/QualysFIM/Integrations/Qualys/test_data/approve_incident.json
  Packs/QualysFIM/Integrations/Qualys/test_data/create_incident.json
  Packs/QualysFIM/Integrations/Qualys/test_data/fetch_incidents.json
  Packs/QualysFIM/Integrations/Qualys/test_data/get_event.json
  Packs/QualysFIM/Integrations/Qualys/test_data/get_incident_events.json
  Packs/QualysFIM/Integrations/Qualys/test_data/list_assets.json
  Packs/QualysFIM/Integrations/Qualys/test_data/list_events.json
  Packs/QualysFIM/Integrations/Qualys/test_data/list_incidents.json
  Packs/QualysFIM/Layouts/layoutscontainer-Qualys_FIM_Layout.json
  Packs/QualysFIM/README.md
  Packs/QualysFIM/Test Playbooks/QualysFIM-Playbook.yml
  Packs/QualysFIM/pack_metadata.json
Labels: Contribution, docs-approved, pending-demo

#11698 Added new command "okta-iam-list-user-applications"
  Packs/Okta/Classifiers/classifier-Okta_IAM.json
  Packs/Okta/Integrations/Okta_IAM/Okta_IAM.py
  Packs/Okta/Integrations/Okta_IAM/Okta_IAM.yml
  Packs/Okta/Integrations/Okta_IAM/README.md
  Packs/Okta/ReleaseNotes/2_1_7.md
  Packs/Okta/pack_metadata.json
Labels: docs-approved

#11816 add mic-atp Indicators Test to skip
  Tests/conf.json
Labels: docs-approved

#11679 Microsoft Graph Mail - get message as attachment
  Packs/MicrosoftGraphMail/Integrations/MicrosoftGraphMail/MicrosoftGraphMail.py
  Packs/MicrosoftGraphMail/Integrations/MicrosoftGraphMail/MicrosoftGraphMail.yml
  Packs/MicrosoftGraphMail/Integrations/MicrosoftGraphMail/MicrosoftGraphMail_test.py
  Packs/MicrosoftGraphMail/Integrations/MicrosoftGraphMail/test_data/mail_with_attachment
  Packs/MicrosoftGraphMail/Integrations/MicrosoftGraphMail/test_data/mail_with_unsupported_attachment
  Packs/MicrosoftGraphMail/ReleaseNotes/1_0_17.md
  Packs/MicrosoftGraphMail/pack_metadata.json
Labels: bug, docs-approved, release-notes-only

#11767 Fireeye key fix
  Packs/fireeye/Integrations/integration-fireeye.yml
  Packs/fireeye/ReleaseNotes/1_0_2.md
  Packs/fireeye/pack_metadata.json
Labels: bug, docs-approved, release-notes-only

#11222 Fraud watch integration
  Packs/CommonTypes/IncidentFields/incidentfield-Dest_Hostname.json
  Packs/CommonTypes/IncidentFields/incidentfield-Incident_Link.json
  Packs/CommonTypes/IncidentFields/incidentfield-Timezone.json
  Packs/CommonTypes/ReleaseNotes/2_8_9.md
  Packs/CommonTypes/pack_metadata.json
  Packs/FraudWatch/.pack-ignore
  Packs/FraudWatch/.secrets-ignore
  Packs/FraudWatch/Classifiers/classifier-FraudWatch_Incident_5_9_9.json
  Packs/FraudWatch/Classifiers/classifier-mapper-incoming-FraudWatch_Incident.json
  Packs/FraudWatch/IncidentFields/incidentfield-FraudWatch_Abuse_Type.json
  Packs/FraudWatch/IncidentFields/incidentfield-FraudWatch_Abuse_URL.json
  Packs/FraudWatch/IncidentFields/incidentfield-FraudWatch_Additional_URLs.json
  Packs/FraudWatch/IncidentFields/incidentfield-FraudWatch_Brand.json
  Packs/FraudWatch/IncidentFields/incidentfield-FraudWatch_Reference_ID.json
  Packs/FraudWatch/IncidentTypes/incidenttype-FraudWatch_Incident.json
  Packs/FraudWatch/Integrations/FraudWatch/FraudWatch.py
  Packs/FraudWatch/Integrations/FraudWatch/FraudWatch.yml
  Packs/FraudWatch/Integrations/FraudWatch/FraudWatch_description.md
  Packs/FraudWatch/Integrations/FraudWatch/FraudWatch_image.png
  Packs/FraudWatch/Integrations/FraudWatch/FraudWatch_test.py
  Packs/FraudWatch/Integrations/FraudWatch/Pipfile
  Packs/FraudWatch/Integrations/FraudWatch/Pipfile.lock
  Packs/FraudWatch/Integrations/FraudWatch/README.md
  Packs/FraudWatch/Integrations/FraudWatch/command_examples.txt
  Packs/FraudWatch/Integrations/FraudWatch/test_data/commands_data.json
  Packs/FraudWatch/Layouts/layout-details-FraudWatch_Incident.json
  Packs/FraudWatch/Layouts/layoutscontainer-FraudWatch_Incident.json
  Packs/FraudWatch/README.md
  Packs/FraudWatch/TestPlaybooks/FraudWatch-Test.yml
  Packs/FraudWatch/doc_files/Token_Generate_Image.png
  Packs/FraudWatch/pack_metadata.json
  Tests/conf.json
Labels: docs-approved

#11790 Upload Flow - Reduce API Calls
  Tests/Marketplace/Tests/marketplace_services_test.py
  Tests/Marketplace/copy_and_upload_packs.py
  Tests/Marketplace/marketplace_services.py
  Tests/Marketplace/upload_packs.py
  Tests/scripts/slack_notifier.py
Labels: docs-approved

#11831 removed secrets
  Packs/FraudWatch/Integrations/FraudWatch/FraudWatch.yml
  Packs/FraudWatch/Integrations/FraudWatch/README.md
  Packs/FraudWatch/Integrations/FraudWatch/test_data/commands_data.json
  Packs/FraudWatch/ReleaseNotes/1_0_1.md
  Packs/FraudWatch/pack_metadata.json
Labels: docs-approved

#11809 Mnemonic mdr
  Packs/mnemonicMDR/Integrations/ArgusManagedDefence/ArgusManagedDefence.py
  Packs/mnemonicMDR/Integrations/ArgusManagedDefence/ArgusManagedDefence.yml
  Packs/mnemonicMDR/Integrations/ArgusManagedDefence/README.md
  Packs/mnemonicMDR/Integrations/ArgusManagedDefence/test_ArgusManagedDefence.py
  Packs/mnemonicMDR/ReleaseNotes/1_1_1.md
  Packs/mnemonicMDR/pack_metadata.json
Labels: Contribution, Partner, docs-approved

#11820 drive readme: fix example link formatting
  Packs/GoogleDrive/Integrations/GoogleDrive/README.md
Labels: docs-approved

#11840 bump version 21.3.1
  .circleci/content_release_vars.sh
Labels: docs-approved

#11627 Content for the MITRE ATT&CK Feed pack README
  Packs/FeedMitreAttack/README.md
Labels: docs-approved

#11623 Created content for the FeedUnit42 Pack README
  Packs/FeedUnit42/README.md
Labels: docs-approved

#11780 Misp: limit attributes in event
  Packs/MISP/Integrations/MISP_V2/MISP_V2.py
  Packs/MISP/Integrations/MISP_V2/MISP_V2.yml
  Packs/MISP/Integrations/MISP_V2/MISP_V2_test.py
  Packs/MISP/Integrations/MISP_V2/test_data/test_constants.py
  Packs/MISP/ReleaseNotes/1_0_5.md
  Packs/MISP/pack_metadata.json
Labels: bug, docs-approved

#11830 RF Feed - fixed fetch indicators json exception
  Packs/FeedRecordedFuture/Integrations/FeedRecordedFuture/FeedRecordedFuture.py
  Packs/FeedRecordedFuture/Integrations/FeedRecordedFuture/FeedRecordedFuture.yml
  Packs/FeedRecordedFuture/Integrations/FeedRecordedFuture/FeedRecordedFuture_test.py
  Packs/FeedRecordedFuture/ReleaseNotes/1_0_8.md
  Packs/FeedRecordedFuture/pack_metadata.json
Labels: bug, docs-approved, release-notes-only

#11732 PhishTank add reliability
  Packs/PhishTank/Integrations/PhishTankV2/PhishTankV2.py
  Packs/PhishTank/Integrations/PhishTankV2/PhishTankV2.yml
  Packs/PhishTank/Integrations/PhishTankV2/PhishTankV2_test.py
  Packs/PhishTank/Integrations/PhishTankV2/README.md
  Packs/PhishTank/ReleaseNotes/2_0_6.md
  Packs/PhishTank/pack_metadata.json
Labels: docs-approved

#11844 increase timeout
  Tests/conf.json
Labels: docs-approved

#11823 Falcon - adding status to cs-falcon-search-device
  Packs/CrowdStrikeFalcon/Integrations/CrowdStrikeFalcon/CrowdStrikeFalcon.py
  Packs/CrowdStrikeFalcon/Integrations/CrowdStrikeFalcon/CrowdStrikeFalcon.yml
  Packs/CrowdStrikeFalcon/Integrations/CrowdStrikeFalcon/README.md
  Packs/CrowdStrikeFalcon/ReleaseNotes/1_2_14.md
  Packs/CrowdStrikeFalcon/pack_metadata.json
Labels: docs-approved, release-notes-only

#11794 Carbon Black Added Readme
  Packs/Carbon_Black_Enterprise_Response/Integrations/README.md
Labels: docs-approved

#11261 Crowdstrike indicator feed
  Packs/CommonTypes/IndicatorFields/incidentfield-actor.json
  Packs/CommonTypes/IndicatorFields/incidentfield-creationdate.json
  Packs/CommonTypes/IndicatorFields/incidentfield-domainname.json
  Packs/CommonTypes/IndicatorFields/incidentfield-ipaddress.json
  Packs/CommonTypes/IndicatorFields/incidentfield-malwarefamily.json
  Packs/CommonTypes/IndicatorFields/incidentfield-updateddate.json
  Packs/CommonTypes/IndicatorFields/indicatorfield-STIX_Kill_Chain_Phases.json
  Packs/CommonTypes/IndicatorFields/indicatorfield-confidence.json
  Packs/CommonTypes/IndicatorFields/indicatorfield-reports.json
  Packs/CommonTypes/IndicatorFields/indicatorfield-targets.json
  Packs/CommonTypes/IndicatorFields/indicatorfield-vulnerabilities.json
  Packs/CommonTypes/ReleaseNotes/2_8_10.md
  Packs/CommonTypes/pack_metadata.json
  Packs/FeedCrowdstrikeFalconIntel/.pack-ignore
  Packs/FeedCrowdstrikeFalconIntel/Integrations/CrowdStrikeIndicatorFeed/CrowdStrikeIndicatorFeed.py
  Packs/FeedCrowdstrikeFalconIntel/Integrations/CrowdStrikeIndicatorFeed/CrowdStrikeIndicatorFeed.yml
  Packs/FeedCrowdstrikeFalconIntel/Integrations/CrowdStrikeIndicatorFeed/CrowdStrikeIndicatorFeed_description.md
  Packs/FeedCrowdstrikeFalconIntel/Integrations/CrowdStrikeIndicatorFeed/CrowdStrikeIndicatorFeed_image.png
  Packs/FeedCrowdstrikeFalconIntel/Integrations/CrowdStrikeIndicatorFeed/CrowdStrikeIndicatorFeed_test.py
  Packs/FeedCrowdstrikeFalconIntel/Integrations/CrowdStrikeIndicatorFeed/Pipfile
  Packs/FeedCrowdstrikeFalconIntel/Integrations/CrowdStrikeIndicatorFeed/Pipfile.lock
  Packs/FeedCrowdstrikeFalconIntel/Integrations/CrowdStrikeIndicatorFeed/README.md
  Packs/FeedCrowdstrikeFalconIntel/Integrations/CrowdStrikeIndicatorFeed/command_examples
  Packs/FeedCrowdstrikeFalconIntel/Integrations/CrowdStrikeIndicatorFeed/test_data/create_indicators_from_response.json
  Packs/FeedCrowdstrikeFalconIntel/Integrations/CrowdStrikeIndicatorFeed/test_data/crowdstrike_indicators_list_command.json
  Packs/FeedCrowdstrikeFalconIntel/Integrations/FeedCrowdstrikeFalconIntel/FeedCrowdstrikeFalconIntel.yml
  Packs/FeedCrowdstrikeFalconIntel/README.md
  Packs/FeedCrowdstrikeFalconIntel/ReleaseNotes/2_0_0.md
  Packs/FeedCrowdstrikeFalconIntel/pack_metadata.json
Labels: docs-approved

#11843 Humio/fix time range error on empty intitial fetch
  Packs/Humio/Integrations/Humio/Humio.py
  Packs/Humio/Integrations/Humio/Humio.yml
  Packs/Humio/ReleaseNotes/1_0_4.md
  Packs/Humio/pack_metadata.json
Labels: Contribution, docs-approved, ready-for-instance-test

#11845 cb-quarantine-device Bug fix
  Packs/Carbon_Black_Enterprise_Response/.pack-ignore
  Packs/Carbon_Black_Enterprise_Response/Integrations/integration-Carbon_Black_Enterprise_Response.yml
  Packs/Carbon_Black_Enterprise_Response/ReleaseNotes/1_1_5.md
  Packs/Carbon_Black_Enterprise_Response/pack_metadata.json
Labels: docs-approved, release-notes-only

#11838 Added reference to Mimecast documentation
  Packs/Mimecast/Integrations/MimecastV2/MimecastV2_description.md
  Packs/Mimecast/Integrations/MimecastV2/README.md
  Packs/Mimecast/ReleaseNotes/1_1_3.md
  Packs/Mimecast/pack_metadata.json
Labels: bug, docs-approved, release-notes-only

#11839 Cisco Stealthwatch - New Pack (#11624)
  Packs/CiscoStealthwatch/.pack-ignore
  Packs/CiscoStealthwatch/.secrets-ignore
  Packs/CiscoStealthwatch/Integrations/CiscoStealthwatch/README.md
  Packs/CiscoStealthwatch/Integrations/CiscoStealthwatch/cisco_stealthwatch.py
  Packs/CiscoStealthwatch/Integrations/CiscoStealthwatch/cisco_stealthwatch.yml
  Packs/CiscoStealthwatch/Integrations/CiscoStealthwatch/cisco_stealthwatch_description.md
  Packs/CiscoStealthwatch/Integrations/CiscoStealthwatch/cisco_stealthwatch_image.png
  Packs/CiscoStealthwatch/Integrations/CiscoStealthwatch/cisco_stealthwatch_test.py
  Packs/CiscoStealthwatch/Integrations/CiscoStealthwatch/command_examples
  Packs/CiscoStealthwatch/Integrations/CiscoStealthwatch/test_data/get_tag.json
  Packs/CiscoStealthwatch/Integrations/CiscoStealthwatch/test_data/get_tag_hourly_traffic_report.json
  Packs/CiscoStealthwatch/Integrations/CiscoStealthwatch/test_data/get_tenant.json
  Packs/CiscoStealthwatch/Integrations/CiscoStealthwatch/test_data/get_top_alarming_tags.json
  Packs/CiscoStealthwatch/Integrations/CiscoStealthwatch/test_data/list_security_events_initialize.json
  Packs/CiscoStealthwatch/Integrations/CiscoStealthwatch/test_data/list_security_events_results.json
  Packs/CiscoStealthwatch/Integrations/CiscoStealthwatch/test_data/list_security_events_status.json
  Packs/CiscoStealthwatch/Integrations/CiscoStealthwatch/test_data/list_tags.json
  Packs/CiscoStealthwatch/Integrations/CiscoStealthwatch/test_data/list_tenants.json
  Packs/CiscoStealthwatch/Integrations/CiscoStealthwatch/test_data/query_flow_initialize.json
  Packs/CiscoStealthwatch/Integrations/CiscoStealthwatch/test_data/query_flow_results.json
  Packs/CiscoStealthwatch/Integrations/CiscoStealthwatch/test_data/query_flow_status.json
  Packs/CiscoStealthwatch/Playbooks/playbook-List_Cisco_Stealthwatch_Security_Events.yml
  Packs/CiscoStealthwatch/Playbooks/playbook-List_Cisco_Stealthwatch_Security_Events_README.md
  Packs/CiscoStealthwatch/Playbooks/playbook-Query_Cisco_Stealthwatch_Flows.yml
  Packs/CiscoStealthwatch/Playbooks/playbook-Query_Cisco_Stealthwatch_Flows_README.md
  Packs/CiscoStealthwatch/README.md
  Packs/CiscoStealthwatch/TestPlaybooks/playbook-Cisco_Stealthwatch-Test.yml
  Packs/CiscoStealthwatch/doc_files/CiscoStealthWatch-List-Security-Events-Playbook.png
  Packs/CiscoStealthwatch/doc_files/CiscoStealthWatch-Query-Flows-Playbook.png
  Packs/CiscoStealthwatch/pack_metadata.json
  Tests/conf.json
Labels: docs-approved

#10992 SUNBURST Azure Enhancement
  Packs/MajorBreachesInvestigationandResponse/Playbooks/playbook-SolarStorm_Activity_Behavior_Hunting_playbook.yml
  Packs/MajorBreachesInvestigationandResponse/Playbooks/playbook-SolarStorm_and_SUNBURST_Hunting_and_Response_Playbook_5_9_9.yml
  Packs/MajorBreachesInvestigationandResponse/Playbooks/playbook-SolarStorm_and_SUNBURST_Hunting_and_Response_Playbook_6.yml
  Packs/MajorBreachesInvestigationandResponse/ReleaseNotes/1_5_0.md
  Packs/MajorBreachesInvestigationandResponse/pack_metadata.json
  Packs/MicrosoftPolicyAndCompliance/.pack-ignore
  Packs/MicrosoftPolicyAndCompliance/.secrets-ignore
  Packs/MicrosoftPolicyAndCompliance/Playbooks/playbook-Azure_Configuration_Analysis.yml
  Packs/MicrosoftPolicyAndCompliance/Playbooks/playbook-Azure_Hunting_playbook.yml
  Packs/MicrosoftPolicyAndCompliance/README.md
  Packs/MicrosoftPolicyAndCompliance/pack_metadata.json
Labels: docs-approved

#11848 regenerated readme for fraudwatch
  Packs/FraudWatch/Integrations/FraudWatch/README.md
Labels: docs-approved

#11819 removed duplicate params from salesforce integration
  Packs/SalesforceIndicators/Integrations/SalesforceIndicators/SalesforceIndicators.yml
  Packs/SalesforceIndicators/ReleaseNotes/1_0_1.md
  Packs/SalesforceIndicators/pack_metadata.json
Labels: docs-approved, release-notes-only

#11852 CyberArkAIM params type fix
  Packs/cyberark_AIM/Integrations/CyberArkAIM_v2/CyberArkAIM_v2.yml
  Packs/cyberark_AIM/ReleaseNotes/1_0_6.md
  Packs/cyberark_AIM/pack_metadata.json
Labels: bug, docs-approved, release-notes-only

#11841 Update README.md
  Packs/EmailCommunication/Scripts/SendEmailReply/README.md
Labels: docs-approved

#11842 Update README.md
  Packs/EmailCommunication/Scripts/PreprocessEmail/README.md
Labels: docs-approved

#11836 Fix Generic Webhook TPB
  Packs/GenericWebhook/TestPlaybooks/Generic_Webhook_-_Test.yml
Labels: docs-approved

#11797 Added timeout arg to start-investigation command.
  Packs/MicrosoftDefenderAdvancedThreatProtection/Integrations/MicrosoftDefenderAdvancedThreatProtection/MicrosoftDefenderAdvancedThreatProtection.py
  Packs/MicrosoftDefenderAdvancedThreatProtection/Integrations/MicrosoftDefenderAdvancedThreatProtection/MicrosoftDefenderAdvancedThreatProtection.yml
  Packs/MicrosoftDefenderAdvancedThreatProtection/ReleaseNotes/1_2_13.md
  Packs/MicrosoftDefenderAdvancedThreatProtection/TestPlaybooks/playbook-Microsoft_Defender_Advanced_Threat_Protection-Test.yml
  Packs/MicrosoftDefenderAdvancedThreatProtection/pack_metadata.json
Labels: docs-approved

#11860 Fix images relative path
  Packs/CiscoStealthwatch/Playbooks/playbook-List_Cisco_Stealthwatch_Security_Events_README.md
  Packs/CiscoStealthwatch/Playbooks/playbook-Query_Cisco_Stealthwatch_Flows_README.md
Labels: docs-approved

#11858 Cyberark fix param encryption
  Packs/cyberark_AIM/Integrations/CyberArkAIM_v2/CyberArkAIM_v2.yml
  Packs/cyberark_AIM/ReleaseNotes/1_0_7.md
  Packs/cyberark_AIM/pack_metadata.json
Labels: bug, docs-approved, release-notes-only

#11859 MS Teams MGMT - add sleep after adding user to cloned team
  Packs/MicrosoftTeams/TestPlaybooks/Microsoft_Teams_Management_-_Test.yml
  Tests/conf.json
Labels: docs-approved

#11675 Crowd Strike Falcon X - bug with uploading file
  Packs/CrowdStrikeFalconX/Integrations/CrowdStrikeFalconX/CrowdStrikeFalconX.py
  Packs/CrowdStrikeFalconX/Integrations/CrowdStrikeFalconX/CrowdStrikeFalconX.yml
  Packs/CrowdStrikeFalconX/Integrations/CrowdStrikeFalconX/README.md
  Packs/CrowdStrikeFalconX/ReleaseNotes/1_1_1.md
  Packs/CrowdStrikeFalconX/pack_metadata.json
Labels: bug, docs-approved, release-notes-only

#11828 fetch-credentials failure caused wrong message in creds page
  Packs/Base/ReleaseNotes/1_7_24.md
  Packs/Base/Scripts/CommonServerPython/CommonServerPython.py
  Packs/Base/Scripts/CommonServerPython/CommonServerPython_test.py
  Packs/Base/pack_metadata.json
  Packs/BeyondTrust_Password_Safe/Integrations/BeyondTrust_Password_Safe/BeyondTrust_Password_Safe.py
  Packs/BeyondTrust_Password_Safe/Integrations/BeyondTrust_Password_Safe/BeyondTrust_Password_Safe.yml
  Packs/BeyondTrust_Password_Safe/ReleaseNotes/1_0_3.md
  Packs/BeyondTrust_Password_Safe/pack_metadata.json
Labels: docs-approved

#11507 Adding a README to the tidy pack
  Packs/Tidy/Integrations/Tidy/README.md
Labels: docs-approved

#11754 Supporting build hardening
  .circleci/config.yml
  dev-requirements-py3.txt
Labels: docs-approved

#11864 content for demisto-sdk 1.3.2
  dev-requirements-py3.txt
Labels: docs-approved

#11826 Update script for adjusted outputs and modify row and col
  Packs/Base/ReleaseNotes/1_7_25.md
  Packs/Base/Scripts/ValidateContent/ValidateContent.py
  Packs/Base/Scripts/ValidateContent/ValidateContent.yml
  Packs/Base/Scripts/ValidateContent/ValidateContent_test.py
  Packs/Base/pack_metadata.json
Labels: docs-approved

#11749 D bot find similar incidents
  Packs/Base/ReleaseNotes/1_7_26.md
  Packs/Base/Scripts/DBotFindSimilarIncidents/DBotFindSimilarIncidents.py
  Packs/Base/Scripts/DBotFindSimilarIncidents/DBotFindSimilarIncidents.yml
  Packs/Base/Scripts/DBotFindSimilarIncidents/dbot_find_similar_incidents_test.py
  Packs/Base/pack_metadata.json
Labels: docs-approved

#11617 Dbot predict similar events indicators
  Packs/Base/ReleaseNotes/1_7_27.md
  Packs/Base/Scripts/DBotFindSimilarIncidentsByIndicators/DBotFindSimilarIncidentsByIndicators.py
  Packs/Base/Scripts/DBotFindSimilarIncidentsByIndicators/DBotFindSimilarIncidentsByIndicators.yml
  Packs/Base/Scripts/DBotFindSimilarIncidentsByIndicators/dbot_find_similar_incidents_by_indicators_test.py
  Packs/Base/pack_metadata.json
Labels: docs-approved

#11846 Splunk token authentication
  Packs/SplunkPy/Integrations/SplunkPy/README.md
  Packs/SplunkPy/Integrations/SplunkPy/SplunkPy.py
  Packs/SplunkPy/Integrations/SplunkPy/SplunkPy_description.md
  Packs/SplunkPy/ReleaseNotes/1_3_3.md
  Packs/SplunkPy/pack_metadata.json
Labels: docs-approved

#11855 graphql: update test-module
  Packs/GraphQL/Integrations/GraphQL/GraphQL.py
  Packs/GraphQL/Integrations/GraphQL/Pipfile
  Packs/GraphQL/Integrations/GraphQL/Pipfile.lock
  Packs/GraphQL/ReleaseNotes/1_0_2.md
  Packs/GraphQL/pack_metadata.json
Labels: docs-approved

#11866 Ransomware dependencies
  Packs/Ransomware/Layouts/layoutscontainer-Post_Intrusion_Ransomware.json
  Packs/Ransomware/ReleaseNotes/1_0_4.md
  Packs/Ransomware/pack_metadata.json
Labels: docs-approved

#11737 idefense - added a reliability parameter
  Packs/iDefense/Integrations/iDefense_v2/README.md
  Packs/iDefense/Integrations/iDefense_v2/iDefense_v2.py
  Packs/iDefense/Integrations/iDefense_v2/iDefense_v2.yml
  Packs/iDefense/Integrations/iDefense_v2/iDefense_v2_test.py
  Packs/iDefense/ReleaseNotes/3_0_2.md
  Packs/iDefense/pack_metadata.json
Labels: docs-approved

#11875 opsgenie v2: fix pack display name
  Packs/Opsgeniev2/pack_metadata.json
Labels: docs-approved

#11863 Fix date in service now mappers
  Packs/ServiceNow/Classifiers/classifier-ServiceNow_5_9_9.json
  Packs/ServiceNow/Classifiers/classifier-mapper-ServiceNow_Create_Ticket_-_Incoming_Mapper.json
  Packs/ServiceNow/Classifiers/classifier-mapper-incoming-ServiceNow.json
  Packs/ServiceNow/Integrations/ServiceNowv2/README.md
  Packs/ServiceNow/ReleaseNotes/2_1_19.md
  Packs/ServiceNow/pack_metadata.json
Labels: docs-approved

#11729 Logpoint playbook
  Packs/LogPoint_SIEM_Integration/Integrations/LogPoint_SIEM_Integration/LogPoint_SIEM_Integration.yml
  Packs/LogPoint_SIEM_Integration/Playbooks/Playbook-LogPoint_SIEM_Playbook.yml
  Packs/LogPoint_SIEM_Integration/Playbooks/Playbook-LogPoint_SIEM_Playbook_README.md
  Packs/LogPoint_SIEM_Integration/ReleaseNotes/1_1_0.md
  Packs/LogPoint_SIEM_Integration/doc_files/LogPoint_SIEM_Playbook.png
  Packs/LogPoint_SIEM_Integration/pack_metadata.json
  Tests/conf.json
Labels: Contribution, Partner, docs-approved, post-demo, ready-for-instance-test

#11696 ParseEmailFiles Bug
  Packs/CommonScripts/ReleaseNotes/1_3_29.md
  Packs/CommonScripts/Scripts/ParseEmailFiles/ParseEmailFiles.py
  Packs/CommonScripts/Scripts/ParseEmailFiles/parse_email_files_test.py
  Packs/CommonScripts/Scripts/ParseEmailFiles/test_data/Phishing_TEST.msg
  Packs/CommonScripts/pack_metadata.json
Labels: docs-approved, release-notes-only

#11829 Cyren ThreatInDepth Base Content Pack v1.5.0
  Packs/FeedCyrenThreatInDepth/Classifiers/classifier-Cyren_Threat_InDepth_Indicator_Mapper.json
  Packs/FeedCyrenThreatInDepth/IndicatorFields/indicatorfield-Cyren_City.json
  Packs/FeedCyrenThreatInDepth/IndicatorFields/indicatorfield-Cyren_City_Name.json
  Packs/FeedCyrenThreatInDepth/IndicatorFields/indicatorfield-Cyren_Geo_Location.json
  Packs/FeedCyrenThreatInDepth/Integrations/CyrenThreatInDepth/CyrenThreatInDepth.py
  Packs/FeedCyrenThreatInDepth/Integrations/CyrenThreatInDepth/CyrenThreatInDepth_test.py
  Packs/FeedCyrenThreatInDepth/Integrations/CyrenThreatInDepth/test_data/ip_reputation.jsonl
  Packs/FeedCyrenThreatInDepth/Integrations/CyrenThreatInDepth/test_data/malware_files.jsonl
  Packs/FeedCyrenThreatInDepth/Integrations/CyrenThreatInDepth/test_data/malware_urls.jsonl
  Packs/FeedCyrenThreatInDepth/Integrations/CyrenThreatInDepth/test_data/phishing_urls.jsonl
  Packs/FeedCyrenThreatInDepth/Layouts/layoutscontainer-Cyren_Threat_InDepth_Indicator_Template.json
  Packs/FeedCyrenThreatInDepth/README.md
  Packs/FeedCyrenThreatInDepth/ReleaseNotes/1_5_0.md
  Packs/FeedCyrenThreatInDepth/pack_metadata.json
Labels: Contribution, Partner, docs-approved, ready-for-instance-test
