Repository demisto/content, pull requests merged in 2021-04, with the labels that each got.

#12000 DBot Truth Bombs Content Pack
  Packs/DBotTruthBombs/.pack-ignore
  Packs/DBotTruthBombs/.secrets-ignore
  Packs/DBotTruthBombs/Integrations/DBotTruthBombs/DBotTruthBombs.py
  Packs/DBotTruthBombs/Integrations/DBotTruthBombs/DBotTruthBombs.yml
  Packs/DBotTruthBombs/Integrations/DBotTruthBombs/DBot_Truth_Bombs_image.png
  Packs/DBotTruthBombs/Integrations/DBotTruthBombs/README.md
  Packs/DBotTruthBombs/README.md
  Packs/DBotTruthBombs/Scripts/FactsAboutYou/FactsAboutYou.py
  Packs/DBotTruthBombs/Scripts/FactsAboutYou/FactsAboutYou.yml
  Packs/DBotTruthBombs/Scripts/FactsAboutYou/README.md
  Packs/DBotTruthBombs/doc_imgs/dbot1.png
  Packs/DBotTruthBombs/doc_imgs/dbot10.png
  Packs/DBotTruthBombs/doc_imgs/dbot11.png
  Packs/DBotTruthBombs/doc_imgs/dbot12.png
  Packs/DBotTruthBombs/doc_imgs/dbot13.png
  Packs/DBotTruthBombs/doc_imgs/dbot14.png
  Packs/DBotTruthBombs/doc_imgs/dbot15.png
  Packs/DBotTruthBombs/doc_imgs/dbot16.png
  Packs/DBotTruthBombs/doc_imgs/dbot2.png
  Packs/DBotTruthBombs/doc_imgs/dbot3.png
  Packs/DBotTruthBombs/doc_imgs/dbot4.png
  Packs/DBotTruthBombs/doc_imgs/dbot5.png
  Packs/DBotTruthBombs/doc_imgs/dbot6.png
  Packs/DBotTruthBombs/doc_imgs/dbot7.png
  Packs/DBotTruthBombs/doc_imgs/dbot8.png
  Packs/DBotTruthBombs/doc_imgs/dbot9.png
  Packs/DBotTruthBombs/pack_metadata.json
  Tests/Marketplace/marketplace_services.py
  Utils/trigger_private_build.py
Labels: docs-approved

#11659 Draw canvas second try
  Packs/Base/ReleaseNotes/1_8_0.md
  Packs/Base/Scripts/DrawRelatedIncidentsCanvas/DrawRelatedIncidentsCanvas.py
  Packs/Base/Scripts/DrawRelatedIncidentsCanvas/DrawRelatedIncidentsCanvas.yml
  Packs/Base/pack_metadata.json
Labels: docs-approved

#11601 Cymulate v2 integration
  Packs/Cymulate/Classifiers/classifier-Cymulate_v2.json
  Packs/Cymulate/Classifiers/classifier-mapper-incoming-Cymulate_v2.json
  Packs/Cymulate/IncidentFields/incidentfield-Cymulate_Cymulate_Agentless.json
  Packs/Cymulate/IncidentFields/incidentfield-Cymulate_Cymulate_Analysis.json
  Packs/Cymulate/IncidentFields/incidentfield-Cymulate_Cymulate_Attack_Type.json
  Packs/Cymulate/IncidentFields/incidentfield-Cymulate_Cymulate_Attack_Vector.json
  Packs/Cymulate/IncidentFields/incidentfield-Cymulate_Cymulate_Description.json
  Packs/Cymulate/IncidentFields/incidentfield-Cymulate_Cymulate_Input.json
  Packs/Cymulate/IncidentFields/incidentfield-Cymulate_Cymulate_Last_Action.json
  Packs/Cymulate/IncidentFields/incidentfield-Cymulate_Cymulate_Mitigation_Details.json
  Packs/Cymulate/IncidentFields/incidentfield-Cymulate_Cymulate_Module.json
  Packs/Cymulate/IncidentFields/incidentfield-Cymulate_Cymulate_Source.json
  Packs/Cymulate/IncidentFields/incidentfield-Cymulate_Cymulate_Source_Email_Address.json
  Packs/Cymulate/IncidentFields/incidentfield-Cymulate_Cymulate_Status.json
  Packs/Cymulate/IncidentFields/incidentfield-Cymulate_Cymulate_Template_Name.json
  Packs/Cymulate/IncidentFields/incidentfield-Cymulate_Cymulate_Test_Case.json
  Packs/Cymulate/IncidentFields/incidentfield-Cymulate_Cymulate_URL.json
  Packs/Cymulate/IncidentTypes/incidenttype-cymulate.json
  Packs/Cymulate/Integrations/Cymulate_v2/Cymulate_v2.py
  Packs/Cymulate/Integrations/Cymulate_v2/Cymulate_v2.yml
  Packs/Cymulate/Integrations/Cymulate_v2/Cymulate_v2_description.md
  Packs/Cymulate/Integrations/Cymulate_v2/Cymulate_v2_image.png
  Packs/Cymulate/Integrations/Cymulate_v2/README.md
  Packs/Cymulate/Integrations/Cymulate_v2/commands_examples.txt
  Packs/Cymulate/Integrations/Cymulate_v2/cymulate_v2_test.py
  Packs/Cymulate/Integrations/Cymulate_v2/test_data/create_phishing_awareness_group.json
  Packs/Cymulate/Integrations/Cymulate_v2/test_data/email_gateway_assessment_status.json
  Packs/Cymulate/Integrations/Cymulate_v2/test_data/endpoint_security_assessment_status.json
  Packs/Cymulate/Integrations/Cymulate_v2/test_data/exfiltration_assessment_status.json
  Packs/Cymulate/Integrations/Cymulate_v2/test_data/extract_name_from_event.json
  Packs/Cymulate/Integrations/Cymulate_v2/test_data/get_phishing_awareness_group.json
  Packs/Cymulate/Integrations/Cymulate_v2/test_data/immediate_threats_assessment_status.json
  Packs/Cymulate/Integrations/Cymulate_v2/test_data/immediate_threats_id_data.json
  Packs/Cymulate/Integrations/Cymulate_v2/test_data/lateral_movement_assessment_status.json
  Packs/Cymulate/Integrations/Cymulate_v2/test_data/list__attack_simulation.json
  Packs/Cymulate/Integrations/Cymulate_v2/test_data/list_agents.json
  Packs/Cymulate/Integrations/Cymulate_v2/test_data/list_attack_simulation_ids.json
  Packs/Cymulate/Integrations/Cymulate_v2/test_data/list_email_gateway_templates.json
  Packs/Cymulate/Integrations/Cymulate_v2/test_data/list_endpoint_security_incidents.json
  Packs/Cymulate/Integrations/Cymulate_v2/test_data/list_endpoint_security_templates.json
  Packs/Cymulate/Integrations/Cymulate_v2/test_data/list_exfiltration_incidents.json
  Packs/Cymulate/Integrations/Cymulate_v2/test_data/list_exfiltration_template.json
  Packs/Cymulate/Integrations/Cymulate_v2/test_data/list_kill_chain_templates.json
  Packs/Cymulate/Integrations/Cymulate_v2/test_data/list_lateral_movement_templates.json
  Packs/Cymulate/Integrations/Cymulate_v2/test_data/list_phishing_awareness_contact_group.json
  Packs/Cymulate/Integrations/Cymulate_v2/test_data/list_waf_templates.json
  Packs/Cymulate/Integrations/Cymulate_v2/test_data/start_attack.json
  Packs/Cymulate/Integrations/Cymulate_v2/test_data/stop_assessment.json
  Packs/Cymulate/Integrations/Cymulate_v2/test_data/waf_assessment_status.json
  Packs/Cymulate/Layouts/layout-details-Cymulate_Immediate_Threats-V2.json
  Packs/Cymulate/Layouts/layoutscontainer-Cymulate_Layout.json
  Packs/Cymulate/Playbooks/Cymulate_Immediate_Threats_Playbook.yml
  Packs/Cymulate/ReleaseNotes/2_0_0.md
  Packs/Cymulate/TestPlaybooks/Cymulate V2 Test.yml
  Packs/Cymulate/pack_metadata.json
  Tests/conf.json
Labels: Contribution, Partner, docs-approved, post-demo

#12004 a fix to support running DbotpredictPhishingWords from playground
  Packs/Base/ReleaseNotes/1_8_1.md
  Packs/Base/Scripts/DBotPredictPhishingWords/DBotPredictPhishingWords.py
  Packs/Base/pack_metadata.json
Labels: docs-approved

#12007 Add error handling - update session
  Packs/ArcherRSA/Integrations/ArcherV2/ArcherV2.py
  Packs/ArcherRSA/Integrations/ArcherV2/ArcherV2_test.py
  Packs/ArcherRSA/ReleaseNotes/1_1_14.md
  Packs/ArcherRSA/pack_metadata.json
Labels: bug, docs-approved, release-notes-only

#11779 Slack: Don't fail invite if user in channel
  Packs/Slack/Integrations/Slack/Slack.py
  Packs/Slack/Integrations/Slack/Slack.yml
  Packs/Slack/ReleaseNotes/1_3_17.md
  Packs/Slack/pack_metadata.json
Labels: Contribution

#12021 Fixed reliability bug
  Packs/Whois/Integrations/Whois/Whois.py
  Packs/Whois/Integrations/Whois/Whois.yml
  Packs/Whois/ReleaseNotes/1_1_9.md
  Packs/Whois/pack_metadata.json
Labels: docs-approved, release-notes-only

#12026 Limit consideration to contribution prs
  Utils/github_workflow_scripts/handle_external_pr.py
Labels: docs-approved

#11804 UrlScan - add reliability
  Packs/UrlScan/Integrations/UrlScan/README.md
  Packs/UrlScan/Integrations/UrlScan/UrlScan.py
  Packs/UrlScan/Integrations/UrlScan/UrlScan.yml
  Packs/UrlScan/Integrations/UrlScan/Urlscan_test.py
  Packs/UrlScan/ReleaseNotes/1_0_8.md
  Packs/UrlScan/pack_metadata.json
Labels: docs-approved

#11850 PhishLabsIOC - Added reliability
  Packs/PhishLabs/Integrations/PhishLabsIOC/PhishLabsIOC.py
  Packs/PhishLabs/Integrations/PhishLabsIOC/PhishLabsIOC.yml
  Packs/PhishLabs/Integrations/PhishLabsIOC/README.md
  Packs/PhishLabs/Integrations/PhishLabsIOC_EIR/PhishLabsIOC_EIR.py
  Packs/PhishLabs/Integrations/PhishLabsIOC_EIR/PhishLabsIOC_EIR.yml
  Packs/PhishLabs/Integrations/PhishLabsIOC_EIR/PhishLabsIOC_EIR_test.py
  Packs/PhishLabs/Integrations/PhishLabsIOC_EIR/README.md
  Packs/PhishLabs/ReleaseNotes/1_0_1.md
  Packs/PhishLabs/pack_metadata.json
Labels: docs-approved

#11884 XForceExchange - Added reliability
  Packs/XForceExchange/Integrations/XFE_v2/README.md
  Packs/XForceExchange/Integrations/XFE_v2/XFE_v2.py
  Packs/XForceExchange/Integrations/XFE_v2/XFE_v2.yml
  Packs/XForceExchange/Integrations/XFE_v2/XFE_v2_test.py
  Packs/XForceExchange/ReleaseNotes/1_0_8.md
  Packs/XForceExchange/pack_metadata.json
Labels: docs-approved

#12039 Rename comannds.txt to commands.txt
  Packs/ThreatConnect/Integrations/ThreatConnect_v2/commands.txt
Labels: Contribution, docs-approved

#12031 google drive readme: fix link formatting
  Packs/GoogleDrive/Integrations/GoogleDrive/README.md
Labels: docs-approved

#12037 added explanation regarding the command in the desc
  Packs/EWS/Integrations/SecurityAndCompliance/README.md
  Packs/EWS/Integrations/SecurityAndCompliance/SecurityAndCompliance.yml
  Packs/EWS/ReleaseNotes/1_8_10.md
  Packs/EWS/pack_metadata.json
Labels: docs-approved, release-notes-only

#12034 Fixed CLI name
  Packs/BitSight/Classifiers/classifier-mapper-incoming-BitSight.json
  Packs/BitSight/IncidentFields/Tags.json
  Packs/BitSight/Layouts/layoutscontainer-BitSight_Findings.json
  Packs/BitSight/ReleaseNotes/1_0_1.md
  Packs/BitSight/pack_metadata.json
Labels: docs-approved

#12033 Skip tanium and tanium tr integrations
  Tests/conf.json
Labels: docs-approved

#12013 Imperva WAF - update readme
  Packs/Imperva_WAF/Integrations/ImpervaWAF/README.md
Labels: docs-approved

#12046 Venfai readme fix
  Packs/Venafi/Integrations/integration-Venafi_README.md
Labels: docs-approved, release-notes-only

#12048 EPO readme ignore error
  Packs/epo/.pack-ignore
Labels: docs-approved

#12049 Imperva WAF - Fix context paths in README
  Packs/Imperva_WAF/Integrations/ImpervaWAF/README.md
Labels: docs-approved

#12047 Jamf update description
  Packs/jamf/Integrations/integration-jamf.yml
  Packs/jamf/ReleaseNotes/1_0_1.md
  Packs/jamf/pack_metadata.json
Labels: docs-approved

#12053 Imperva WAF - Fix README
  Packs/Imperva_WAF/.pack-ignore
  Packs/Imperva_WAF/Integrations/ImpervaWAF/ImpervaWAF.yml
  Packs/Imperva_WAF/Integrations/ImpervaWAF/README.md
  Packs/Imperva_WAF/ReleaseNotes/1_0_1.md
  Packs/Imperva_WAF/pack_metadata.json
Labels: docs-approved

#12050 EPO readme ignore error
  Packs/epo/.pack-ignore
Labels: docs-approved

#11961 Add support for trending packs
  Tests/Marketplace/Tests/marketplace_services_test.py
  Tests/Marketplace/approved_tags.json
  Tests/Marketplace/landingPage_sections.json
  Tests/Marketplace/marketplace_services.py
  Tests/Marketplace/upload_packs.py
Labels: docs-approved

#12008 added error SC105 to some pack ignore of some packs after adding a va…
  Packs/Base/.pack-ignore
  Packs/CommonScripts/.pack-ignore
  Packs/DemistoRESTAPI/.pack-ignore
  Packs/Phishing/.pack-ignore
Labels: docs-approved

#11854 Workday IAM updates
  Packs/Workday/Classifiers/classifier-IAM_Sync_User_-_Workday.json
  Packs/Workday/Classifiers/classifier-Workday_Classifier.json
  Packs/Workday/Integrations/Workday_IAM/README.md
  Packs/Workday/Integrations/Workday_IAM/Workday_IAM.py
  Packs/Workday/Integrations/Workday_IAM/Workday_IAM.yml
  Packs/Workday/Integrations/Workday_IAM/Workday_IAM_test.py
  Packs/Workday/Integrations/Workday_IAM/test_data/event_results.py
  Packs/Workday/Integrations/Workday_IAM/test_data/json_raw_response.json
  Packs/Workday/Integrations/Workday_IAM/test_data/mapped_user.json
  Packs/Workday/ReleaseNotes/1_1_0.md
  Packs/Workday/pack_metadata.json
Labels: docs-approved

#11894 fix TPB O365-SecurityAndCompliance-Test and move from skipped
  Packs/EWS/Integrations/SecurityAndCompliance/SecurityAndCompliance.ps1
  Packs/EWS/Integrations/SecurityAndCompliance/SecurityAndCompliance.yml
  Packs/EWS/ReleaseNotes/1_8_11.md
  Packs/EWS/TestPlaybooks/playbook-O365-SecurityAndCompliance-Test.yml
  Packs/EWS/pack_metadata.json
  Tests/conf.json
Labels: docs-approved, release-notes-only

#11897 Auto focus added outputs to the commands
  Packs/AutoFocus/Integrations/AutofocusV2/AutofocusV2.py
  Packs/AutoFocus/Integrations/AutofocusV2/AutofocusV2.yml
  Packs/AutoFocus/Integrations/AutofocusV2/AutofocusV2_test.py
  Packs/AutoFocus/Integrations/AutofocusV2/README.md
  Packs/AutoFocus/ReleaseNotes/1_1_16.md
  Packs/AutoFocus/TestPlaybooks/playbook-AutoFocus_V2_test.yml
  Packs/AutoFocus/pack_metadata.json
Labels: docs-approved

#11782 Whois - added IP command
  Packs/Whois/.secrets-ignore
  Packs/Whois/Integrations/Whois/README.md
  Packs/Whois/Integrations/Whois/Whois.py
  Packs/Whois/Integrations/Whois/Whois.yml
  Packs/Whois/Integrations/Whois/Whois_description.md
  Packs/Whois/Integrations/Whois/Whois_test.py
  Packs/Whois/Integrations/Whois/examples.txt
  Packs/Whois/Integrations/Whois/test_data/ip_output.json
  Packs/Whois/ReleaseNotes/1_2_0.md
  Packs/Whois/TestPlaybooks/playbook-Whois-Test.yml
  Packs/Whois/pack_metadata.json
Labels: docs-approved

#11441 Guardicore missing parameter bug + test module fix
  Packs/GuardiCore/Integrations/integration-GuardiCore.yml
  Packs/GuardiCore/README.md
  Packs/GuardiCore/ReleaseNotes/1_0_1.md
  Packs/GuardiCore/pack_metadata.json
Labels: bug, docs-approved, release-notes-only

#10951 Wild fire added outputs to the File command
  Packs/Palo_Alto_Networks_WildFire/Integrations/Palo_Alto_Networks_WildFire_v2/Palo_Alto_Networks_WildFire_v2.py
  Packs/Palo_Alto_Networks_WildFire/Integrations/Palo_Alto_Networks_WildFire_v2/Palo_Alto_Networks_WildFire_v2.yml
  Packs/Palo_Alto_Networks_WildFire/Integrations/Palo_Alto_Networks_WildFire_v2/README.md
  Packs/Palo_Alto_Networks_WildFire/ReleaseNotes/1_3_2.md
  Packs/Palo_Alto_Networks_WildFire/pack_metadata.json
Labels: docs-approved

#10979 Url scan added outputs to the URL command
  Packs/UrlScan/Integrations/UrlScan/README.md
  Packs/UrlScan/Integrations/UrlScan/UrlScan.py
  Packs/UrlScan/Integrations/UrlScan/UrlScan.yml
  Packs/UrlScan/ReleaseNotes/1_0_9.md
  Packs/UrlScan/pack_metadata.json
Labels: docs-approved, release-notes-only

#12052 Mcafee ESM v2 - fix raw response
  Packs/McAfee_ESM/Integrations/McAfee_ESM_v2/McAfee_ESM_v2.py
  Packs/McAfee_ESM/Integrations/McAfee_ESM_v2/McAfee_ESM_v2.yml
  Packs/McAfee_ESM/ReleaseNotes/1_1_5.md
  Packs/McAfee_ESM/pack_metadata.json
Labels: docs-approved, release-notes-only

#12022 Palo Alto Networks BPA - Lengthen the timeout of the ***pan-os-bpa-sub…
  Packs/BPA/Integrations/BPA/BPA.py
  Packs/BPA/Integrations/BPA/BPA.yml
  Packs/BPA/Integrations/BPA/README.md
  Packs/BPA/ReleaseNotes/1_2_5.md
  Packs/BPA/pack_metadata.json
Labels: bug, docs-approved, release-notes-only

#12051 Alien vault otx v2 - Add Reliability
  Packs/AlienVault_OTX/Integrations/AlienVault_OTX_v2/AlienVault_OTX_v2.py
  Packs/AlienVault_OTX/Integrations/AlienVault_OTX_v2/AlienVault_OTX_v2.yml
  Packs/AlienVault_OTX/Integrations/AlienVault_OTX_v2/AlienVault_OTX_v2_test.py
  Packs/AlienVault_OTX/Integrations/AlienVault_OTX_v2/README.md
  Packs/AlienVault_OTX/ReleaseNotes/1_0_3.md
  Packs/AlienVault_OTX/pack_metadata.json
Labels: docs-approved

#11810 Urlhaus add reliability
  Packs/URLHaus/Integrations/URLHaus/README.md
  Packs/URLHaus/Integrations/URLHaus/URLHaus.py
  Packs/URLHaus/Integrations/URLHaus/URLHaus.yml
  Packs/URLHaus/Integrations/URLHaus/URLHaus_test.py
  Packs/URLHaus/ReleaseNotes/1_0_2.md
  Packs/URLHaus/pack_metadata.json
Labels: docs-approved

#12073 new branch for https://github.com/xsoar-contrib/content/tree/zh-lim-c…
  Packs/AsanaConnect/.pack-ignore
  Packs/AsanaConnect/.secrets-ignore
  Packs/AsanaConnect/Integrations/AsanaConnect/AsanaConnect.py
  Packs/AsanaConnect/Integrations/AsanaConnect/AsanaConnect.yml
  Packs/AsanaConnect/Integrations/AsanaConnect/AsanaConnect_description.md
  Packs/AsanaConnect/Integrations/AsanaConnect/AsanaConnect_image.png
  Packs/AsanaConnect/Integrations/AsanaConnect/README.md
  Packs/AsanaConnect/README.md
  Packs/AsanaConnect/pack_metadata.json
Labels: Contribution, docs-approved

#10816 IpInfo added outputs to the IP command
  Packs/ipinfo/Integrations/integration-Ipinfo.yml
  Packs/ipinfo/Integrations/integration-Ipinfo_README.md
  Packs/ipinfo/ReleaseNotes/1_0_2.md
  Packs/ipinfo/pack_metadata.json
Labels: docs-approved, release-notes-only

#12078 GitHub - bump docker image
  Packs/GitHub/Integrations/GitHub/GitHub.yml
  Packs/GitHub/ReleaseNotes/1_1_10.md
  Packs/GitHub/pack_metadata.json
Labels: docs-approved

#11892 O365 - Security And Compliance - Search And Delete - fix no emails were found
  Packs/EWS/Playbooks/playbook-O365-SecurityAndCompliance-SearchAndDelete.yml
  Packs/EWS/ReleaseNotes/1_8_12.md
  Packs/EWS/pack_metadata.json
Labels: docs-approved, release-notes-only

#11766 Jira mirror in refactor& jira mirror out- new PR
  Packs/Jira/Classifiers/classifier-mapper-incoming-JiraV2.json
  Packs/Jira/Classifiers/classifier-mapper-outgoing-Jira.json
  Packs/Jira/IncidentFields/Jira_Attachments.json
  Packs/Jira/IncidentFields/Jira_Description.json
  Packs/Jira/IncidentFields/Jira_Due_Date.json
  Packs/Jira/IncidentFields/Jira_Labels.json
  Packs/Jira/IncidentFields/Jira_Priority.json
  Packs/Jira/IncidentFields/Jira_Reporter_Email.json
  Packs/Jira/IncidentFields/Jira_Reporter_Name.json
  Packs/Jira/IncidentFields/Jira_Status.json
  Packs/Jira/IncidentFields/Jira_Summary.json
  Packs/Jira/IncidentFields/Jira_Transitions.json
  Packs/Jira/IncidentFields/Jira_created_time.json
  Packs/Jira/IncidentTypes/Jira_Incident.json
  Packs/Jira/Integrations/JiraV2/JiraV2.py
  Packs/Jira/Integrations/JiraV2/JiraV2.yml
  Packs/Jira/Integrations/JiraV2/JiraV2_test.py
  Packs/Jira/Integrations/JiraV2/README.md
  Packs/Jira/Integrations/JiraV2/test_data/expected_results.py
  Packs/Jira/Layouts/layoutscontainer-Jira_Incident_Layout.json
  Packs/Jira/README.md
  Packs/Jira/ReleaseNotes/1_3_0.md
  Packs/Jira/Scripts/ScriptJiraChangeTransition/Pipfile
  Packs/Jira/Scripts/ScriptJiraChangeTransition/Pipfile.lock
  Packs/Jira/Scripts/ScriptJiraChangeTransition/README.md
  Packs/Jira/Scripts/ScriptJiraChangeTransition/ScriptJiraChangeTransition.py
  Packs/Jira/Scripts/ScriptJiraChangeTransition/ScriptJiraChangeTransition.yml
  Packs/Jira/Scripts/ScriptJiraListTransition/Pipfile
  Packs/Jira/Scripts/ScriptJiraListTransition/Pipfile.lock
  Packs/Jira/Scripts/ScriptJiraListTransition/README.md
  Packs/Jira/Scripts/ScriptJiraListTransition/ScriptJiraListTransition.py
  Packs/Jira/Scripts/ScriptJiraListTransition/ScriptJiraListTransition.yml
  Packs/Jira/doc_files/con_mapper_in_4.png
  Packs/Jira/doc_files/create_new_field_1.png
  Packs/Jira/doc_files/download_as_json_10.png
  Packs/Jira/doc_files/edit_incident_via_layout.png
  Packs/Jira/doc_files/edit_mapper_btn.png
  Packs/Jira/doc_files/fetch_incidents_3.png
  Packs/Jira/doc_files/incoming_editor_5.png
  Packs/Jira/doc_files/list_transitions.png
  Packs/Jira/doc_files/map_in_incident_6.png
  Packs/Jira/doc_files/map_out_field_8.png
  Packs/Jira/doc_files/mirror_incoming_mapper_fields.png
  Packs/Jira/doc_files/outgoing_editor_7.png
  Packs/Jira/doc_files/setting_btn.png
  Packs/Jira/doc_files/settings_find_layout_2.png
  Packs/Jira/doc_files/upload_json_11.png
  Packs/Jira/doc_files/view_full_9.png
  Packs/Jira/pack_metadata.json
  Tests/secrets_white_list.json
Labels: docs-approved

#12077 Microsoft Management Activity - bump docker image
  Packs/MicrosoftManagementActivity/Integrations/MicrosoftManagementActivity/MicrosoftManagementActivity.py
  Packs/MicrosoftManagementActivity/Integrations/MicrosoftManagementActivity/MicrosoftManagementActivity.yml
  Packs/MicrosoftManagementActivity/ReleaseNotes/1_1_9.md
  Packs/MicrosoftManagementActivity/pack_metadata.json
Labels: docs-approved

#12082 Removed description information
  Packs/AsanaConnect/Integrations/AsanaConnect/AsanaConnect_description.md
  Packs/AsanaConnect/ReleaseNotes/1_0_1.md
  Packs/AsanaConnect/pack_metadata.json
Labels: docs-approved

#10724 added indicator fields
  Packs/CommonTypes/IndicatorFields/incidentfield-asn.json
  Packs/CommonTypes/IndicatorFields/incidentfield-geocountry.json
  Packs/CommonTypes/IndicatorFields/incidentfield-organization.json
  Packs/CommonTypes/IndicatorFields/indicatorfield-AS_Owner.json
  Packs/CommonTypes/IndicatorFields/indicatorfield-Behavior.json
  Packs/CommonTypes/IndicatorFields/indicatorfield-Community_Notes.json
  Packs/CommonTypes/IndicatorFields/indicatorfield-Organization_Type.json
  Packs/CommonTypes/IndicatorFields/indicatorfield-Publications.json
  Packs/CommonTypes/IndicatorFields/indicatorfield-Registrar_Abuse_Address.json
  Packs/CommonTypes/IndicatorFields/indicatorfield-Registrar_Abuse_Country.json
  Packs/CommonTypes/IndicatorFields/indicatorfield-Registrar_Abuse_Name.json
  Packs/CommonTypes/IndicatorFields/indicatorfield-Registrar_Abuse_Network.json
  Packs/CommonTypes/IndicatorTypes/reputation-domain.json
  Packs/CommonTypes/IndicatorTypes/reputation-file.json
  Packs/CommonTypes/IndicatorTypes/reputation-ip.json
  Packs/CommonTypes/IndicatorTypes/reputation-url.json
  Packs/CommonTypes/ReleaseNotes/2_8_12.md
  Packs/CommonTypes/pack_metadata.json
Labels: docs-approved

#11992 Update SanePdfReport script with new docker image
  Packs/Base/ReleaseNotes/1_8_2.md
  Packs/Base/Scripts/SanePdfReport/SanePdfReport.yml
  Packs/Base/pack_metadata.json
Labels: docs-approved, release-notes-only

#11934 Cisco umbrela investigate add reliability
  Packs/Cisco-umbrella/Integrations/Cisco-umbrella-investigate/Cisco-umbrella-investigate.py
  Packs/Cisco-umbrella/Integrations/Cisco-umbrella-investigate/Cisco-umbrella-investigate.yml
  Packs/Cisco-umbrella/Integrations/Cisco-umbrella-investigate/Cisco-umbrella-investigate_test.py
  Packs/Cisco-umbrella/Integrations/Cisco-umbrella-investigate/README.md
  Packs/Cisco-umbrella/ReleaseNotes/1_0_3.md
  Packs/Cisco-umbrella/pack_metadata.json
Labels: docs-approved

#11646 Adding new parameter to all Azure integrations
  Packs/ApiModules/Scripts/MicrosoftApiModule/MicrosoftApiModule.py
  Packs/AzureKubernetesServices/Integrations/AzureKubernetesServices/AzureKubernetesServices.py
  Packs/AzureKubernetesServices/Integrations/AzureKubernetesServices/AzureKubernetesServices.yml
  Packs/AzureKubernetesServices/Integrations/AzureKubernetesServices/README.md
  Packs/AzureKubernetesServices/ReleaseNotes/1_0_3.md
  Packs/AzureKubernetesServices/pack_metadata.json
  Packs/AzureNetworkSecurityGroups/Integrations/AzureNetworkSecurityGroups/AzureNetworkSecurityGroups.py
  Packs/AzureNetworkSecurityGroups/Integrations/AzureNetworkSecurityGroups/AzureNetworkSecurityGroups.yml
  Packs/AzureNetworkSecurityGroups/Integrations/AzureNetworkSecurityGroups/README.md
  Packs/AzureNetworkSecurityGroups/ReleaseNotes/1_0_3.md
  Packs/AzureNetworkSecurityGroups/pack_metadata.json
  Packs/AzureSQLManagement/Integrations/AzureSQLManagement/AzureSQLManagement.py
  Packs/AzureSQLManagement/Integrations/AzureSQLManagement/AzureSQLManagement.yml
  Packs/AzureSQLManagement/Integrations/AzureSQLManagement/README.md
  Packs/AzureSQLManagement/ReleaseNotes/1_0_4.md
  Packs/AzureSQLManagement/pack_metadata.json
  Packs/AzureWAF/Integrations/AzureWAF/AzureWAF.py
  Packs/AzureWAF/Integrations/AzureWAF/AzureWAF.yml
  Packs/AzureWAF/Integrations/AzureWAF/README.md
  Packs/AzureWAF/ReleaseNotes/1_0_4.md
  Packs/AzureWAF/pack_metadata.json
  Packs/MicrosoftGraphAPI/Integrations/MicrosoftGraphAPI/MicrosoftGraphAPI.py
  Packs/MicrosoftGraphAPI/Integrations/MicrosoftGraphAPI/MicrosoftGraphAPI.yml
  Packs/MicrosoftGraphAPI/Integrations/MicrosoftGraphAPI/README.md
  Packs/MicrosoftGraphAPI/ReleaseNotes/1_0_3.md
  Packs/MicrosoftGraphAPI/pack_metadata.json
  Packs/MicrosoftGraphApplications/Integrations/MicrosoftGraphApplications/MicrosoftGraphApplications.py
  Packs/MicrosoftGraphApplications/Integrations/MicrosoftGraphApplications/MicrosoftGraphApplications.yml
  Packs/MicrosoftGraphApplications/Integrations/MicrosoftGraphApplications/README.md
  Packs/MicrosoftGraphApplications/ReleaseNotes/1_0_3.md
  Packs/MicrosoftGraphApplications/pack_metadata.json
  Packs/MicrosoftGraphIdentityandAccess/Integrations/MicrosoftGraphIdentityandAccess/MicrosoftGraphIdentityandAccess.py
  Packs/MicrosoftGraphIdentityandAccess/Integrations/MicrosoftGraphIdentityandAccess/MicrosoftGraphIdentityandAccess.yml
  Packs/MicrosoftGraphIdentityandAccess/Integrations/MicrosoftGraphIdentityandAccess/README.md
  Packs/MicrosoftGraphIdentityandAccess/ReleaseNotes/1_0_3.md
  Packs/MicrosoftGraphIdentityandAccess/pack_metadata.json
  Packs/MicrosoftTeams/Integrations/MicrosoftTeamsManagement/MicrosoftTeamsManagement.py
  Packs/MicrosoftTeams/Integrations/MicrosoftTeamsManagement/MicrosoftTeamsManagement.yml
  Packs/MicrosoftTeams/Integrations/MicrosoftTeamsManagement/README.md
  Packs/MicrosoftTeams/ReleaseNotes/1_1_4.md
  Packs/MicrosoftTeams/pack_metadata.json
  Tests/conf.json
Labels: docs-approved, release-notes-only

#12086 Test playbook failure fix
  Packs/AzureSecurityCenter/TestPlaybooks/playbook-AzureSCTestPlaybook.yml
  Tests/conf.json
Labels: docs-approved

#12087 ThreatMiner - remove test playbook from skipped tests
  Tests/conf.json
Labels: docs-approved

#12089 Unskip Tanium and Tanium TR
  Tests/conf.json
Labels: docs-approved

#11926 fixes in IAMInitADUser script
  Packs/Active_Directory_Query/ReleaseNotes/1_1_8.md
  Packs/Active_Directory_Query/Scripts/IAMInitADUser/IAMInitADUser.py
  Packs/Active_Directory_Query/Scripts/IAMInitADUser/IAMInitADUser.yml
  Packs/Active_Directory_Query/pack_metadata.json
Labels: docs-approved

#11364 New azure storage integration
  Packs/AzureStorage/.pack-ignore
  Packs/AzureStorage/.secrets-ignore
  Packs/AzureStorage/Integrations/AzureStorage/AzureStorage.py
  Packs/AzureStorage/Integrations/AzureStorage/AzureStorage.yml
  Packs/AzureStorage/Integrations/AzureStorage/AzureStorage_description.md
  Packs/AzureStorage/Integrations/AzureStorage/AzureStorage_image.png
  Packs/AzureStorage/Integrations/AzureStorage/AzureStorage_test.py
  Packs/AzureStorage/Integrations/AzureStorage/Pipfile
  Packs/AzureStorage/Integrations/AzureStorage/Pipfile.lock
  Packs/AzureStorage/Integrations/AzureStorage/README.md
  Packs/AzureStorage/Integrations/AzureStorage/command_examples
  Packs/AzureStorage/Integrations/AzureStorage/test_data/blob_containers_create_update_response.json
  Packs/AzureStorage/Integrations/AzureStorage/test_data/blob_containers_list_response.json
  Packs/AzureStorage/Integrations/AzureStorage/test_data/blob_containers_single_response.json
  Packs/AzureStorage/Integrations/AzureStorage/test_data/blob_service_properties_get_response.json
  Packs/AzureStorage/Integrations/AzureStorage/test_data/blob_service_properties_set_response.json
  Packs/AzureStorage/Integrations/AzureStorage/test_data/storage_account_list_response.json
  Packs/AzureStorage/Integrations/AzureStorage/test_data/storage_account_single_response.json
  Packs/AzureStorage/README.md
  Packs/AzureStorage/TestPlaybooks/Azure_Storage_-_Test.yml
  Packs/AzureStorage/pack_metadata.json
  Tests/conf.json
Labels: docs-approved

#12095 fix issueJson parameter bug in jira-create-issue command
  Packs/Jira/Integrations/JiraV2/JiraV2.py
  Packs/Jira/ReleaseNotes/1_3_1.md
  Packs/Jira/pack_metadata.json
Labels: docs-approved

#11947 deleteContext fix
  Packs/CommonScripts/ReleaseNotes/1_3_32.md
  Packs/CommonScripts/Scripts/script-DeleteConext.yml
  Packs/CommonScripts/pack_metadata.json
Labels: bug, docs-approved, release-notes-only

#12091 support -104 verdict in wildfire
  Packs/Palo_Alto_Networks_WildFire/Integrations/Palo_Alto_Networks_WildFire_v2/Palo_Alto_Networks_WildFire_v2.py
  Packs/Palo_Alto_Networks_WildFire/ReleaseNotes/1_3_3.md
  Packs/Palo_Alto_Networks_WildFire/pack_metadata.json
Labels: bug, docs-approved, release-notes-only

#12079 Box v2 - bump docker image
  Packs/Box/Integrations/BoxV2/BoxV2.py
  Packs/Box/Integrations/BoxV2/BoxV2.yml
  Packs/Box/ReleaseNotes/2_1_2.md
  Packs/Box/pack_metadata.json
Labels: docs-approved

#12093 Added an option to import ML models as list via scripts
  Packs/ML/ReleaseNotes/1_2_3.md
  Packs/ML/Scripts/ImportMLModel/ImportMLModel.py
  Packs/ML/Scripts/ImportMLModel/ImportMLModel.yml
  Packs/ML/Scripts/ImportMLModel/ImportMLModel_test.py
  Packs/ML/pack_metadata.json
Labels: docs-approved

#11929 Kaspersky Security Center
  Packs/Base/ReleaseNotes/1_8_3.md
  Packs/Base/Scripts/CommonServerPython/CommonServerPython.py
  Packs/Base/pack_metadata.json
  Packs/KasperskySecurityCenter/.pack-ignore
  Packs/KasperskySecurityCenter/.secrets-ignore
  Packs/KasperskySecurityCenter/Integrations/KasperskySecurityCenter/KasperskySecurityCenter.py
  Packs/KasperskySecurityCenter/Integrations/KasperskySecurityCenter/KasperskySecurityCenter.yml
  Packs/KasperskySecurityCenter/Integrations/KasperskySecurityCenter/KasperskySecurityCenter_description.md
  Packs/KasperskySecurityCenter/Integrations/KasperskySecurityCenter/KasperskySecurityCenter_image.png
  Packs/KasperskySecurityCenter/Integrations/KasperskySecurityCenter/KasperskySecurityCenter_test.py
  Packs/KasperskySecurityCenter/Integrations/KasperskySecurityCenter/Pipfile
  Packs/KasperskySecurityCenter/Integrations/KasperskySecurityCenter/Pipfile.lock
  Packs/KasperskySecurityCenter/Integrations/KasperskySecurityCenter/README.md
  Packs/KasperskySecurityCenter/Integrations/KasperskySecurityCenter/command_examples
  Packs/KasperskySecurityCenter/Integrations/KasperskySecurityCenter/test_data/action_response.json
  Packs/KasperskySecurityCenter/Integrations/KasperskySecurityCenter/test_data/find_response.json
  Packs/KasperskySecurityCenter/Integrations/KasperskySecurityCenter/test_data/group_add_response.json
  Packs/KasperskySecurityCenter/Integrations/KasperskySecurityCenter/test_data/groups_list_response.json
  Packs/KasperskySecurityCenter/Integrations/KasperskySecurityCenter/test_data/host_get_response.json
  Packs/KasperskySecurityCenter/Integrations/KasperskySecurityCenter/test_data/hosts_list_response.json
  Packs/KasperskySecurityCenter/Integrations/KasperskySecurityCenter/test_data/policies_list_response.json
  Packs/KasperskySecurityCenter/Integrations/KasperskySecurityCenter/test_data/software_applications_response.json
  Packs/KasperskySecurityCenter/Integrations/KasperskySecurityCenter/test_data/software_patches_response.json
  Packs/KasperskySecurityCenter/README.md
  Packs/KasperskySecurityCenter/TestPlaybooks/Kaspersky_Security_Center_-_Test.yml
  Packs/KasperskySecurityCenter/doc_imgs/role.png
  Packs/KasperskySecurityCenter/pack_metadata.json
Labels: docs-approved

#12043 update gamma support details
  Packs/Gamma/pack_metadata.json
Labels: docs-approved

#11938 Netskope - Fixed an issue where long Alert IDs where rounded down
  Packs/Netskope/Integrations/integration-Netskope.yml
  Packs/Netskope/ReleaseNotes/1_0_1.md
  Packs/Netskope/pack_metadata.json
Labels: docs-approved

#12099 Ignore incident validation
  Packs/Base/.pack-ignore
  Packs/CommonScripts/.pack-ignore
  Packs/DemistoRESTAPI/.pack-ignore
Labels: docs-approved

#12066 Slackv2 bug
  Tests/conf.json
Labels: docs-approved

#12062 Added support for auto cache update
  Packs/AzureLogAnalytics/Integrations/AzureLogAnalytics/AzureLogAnalytics.py
  Packs/AzureLogAnalytics/ReleaseNotes/1_0_8.md
  Packs/AzureLogAnalytics/pack_metadata.json
  Packs/AzureSentinel/Integrations/AzureSentinel/AzureSentinel.py
  Packs/AzureSentinel/ReleaseNotes/1_0_9.md
  Packs/AzureSentinel/pack_metadata.json
  Packs/MicrosoftGraphListener/Integrations/MicrosoftGraphListener/MicrosoftGraphListener.py
  Packs/MicrosoftGraphListener/Integrations/MicrosoftGraphListener/MicrosoftGraphListener.yml
  Packs/MicrosoftGraphListener/ReleaseNotes/1_0_14.md
  Packs/MicrosoftGraphListener/pack_metadata.json
  Packs/MicrosoftManagementActivity/Integrations/MicrosoftManagementActivity/MicrosoftManagementActivity.py
  Packs/MicrosoftManagementActivity/ReleaseNotes/1_1_10.md
  Packs/MicrosoftManagementActivity/pack_metadata.json
  Packs/MicrosoftTeams/Integrations/MicrosoftTeams/MicrosoftTeams.py
  Packs/MicrosoftTeams/ReleaseNotes/1_1_5.md
  Packs/MicrosoftTeams/pack_metadata.json
Labels: bug, docs-approved, release-notes-only

#12113 Adding myself as code owner on config.yml
  .github/CODEOWNERS
Labels: docs-approved

#11980 office 365 doc fix
  Packs/FeedOffice365/Integrations/FeedOffice365/README.md
Labels: docs-approved

#11981 ParseEmailFiles Polish lang - decode fix
  Packs/CommonScripts/ReleaseNotes/1_3_33.md
  Packs/CommonScripts/Scripts/ParseEmailFiles/ParseEmailFiles.py
  Packs/CommonScripts/Scripts/ParseEmailFiles/parse_email_files_test.py
  Packs/CommonScripts/pack_metadata.json
Labels: bug, docs-approved, release-notes-only

#12068 Tagging ingested IOC (HTTPFeedApiModule bug)
  Packs/ApiModules/Scripts/HTTPFeedApiModule/HTTPFeedApiModule.py
  Packs/ApiModules/Scripts/HTTPFeedApiModule/HTTPFeedApiModule_test.py
  Packs/FeedBlocklist_de/ReleaseNotes/1_0_6.md
  Packs/FeedBlocklist_de/pack_metadata.json
  Packs/FeedBruteForceBlocker/ReleaseNotes/1_0_6.md
  Packs/FeedBruteForceBlocker/pack_metadata.json
  Packs/FeedCloudflare/ReleaseNotes/1_0_6.md
  Packs/FeedCloudflare/pack_metadata.json
  Packs/FeedDShield/ReleaseNotes/1_0_6.md
  Packs/FeedDShield/pack_metadata.json
  Packs/FeedFeodoTracker/ReleaseNotes/1_0_9.md
  Packs/FeedFeodoTracker/pack_metadata.json
  Packs/FeedMalwareDomainList/ReleaseNotes/1_0_6.md
  Packs/FeedMalwareDomainList/pack_metadata.json
  Packs/FeedPlainText/ReleaseNotes/1_0_7.md
  Packs/FeedPlainText/pack_metadata.json
  Packs/FeedSpamhaus/ReleaseNotes/1_0_6.md
  Packs/FeedSpamhaus/pack_metadata.json
Labels: bug, docs-approved, release-notes-only

#11821 ThreatMiner added reliability
  Packs/ThreatMiner/Integrations/ThreatMiner/ThreatMiner.py
  Packs/ThreatMiner/Integrations/ThreatMiner/ThreatMiner.yml
  Packs/ThreatMiner/Integrations/ThreatMiner/Threatminer_test.py
  Packs/ThreatMiner/ReleaseNotes/1_0_3.md
  Packs/ThreatMiner/pack_metadata.json
Labels: docs-approved

#12016 Ignore layout validation
  Packs/CommonTypes/.pack-ignore
  Packs/Cymulate/.pack-ignore
  Packs/MicrosoftCloudAppSecurity/.pack-ignore
  Packs/PrismaCloudCompute/.pack-ignore
  Packs/Smokescreen_IllusionBLACK/.pack-ignore
  Packs/Smokescreen_IllusionBLACK/pack_metadata.json
  Packs/XMCyber/.pack-ignore
Labels: docs-approved

#12074 TheHive Project - Added support for the ***get-modified-remote-data***
  Packs/TheHiveProject/IncidentFields/incidentfield-Observables.json
  Packs/TheHiveProject/IncidentFields/incidentfield-Tasks.json
  Packs/TheHiveProject/Integrations/TheHiveProject/TheHiveProject.py
  Packs/TheHiveProject/Integrations/TheHiveProject/TheHiveProject.yml
  Packs/TheHiveProject/ReleaseNotes/1_1_0.md
  Packs/TheHiveProject/pack_metadata.json
Labels: docs-approved

#12097 Feed related indicators fix
  Packs/Base/ReleaseNotes/1_8_4.md
  Packs/Base/Scripts/CommonServerPython/CommonServerPython.py
  Packs/Base/Scripts/CommonServerPython/CommonServerPython_test.py
  Packs/Base/pack_metadata.json
  Packs/Whois/Integrations/Whois/Whois.py
  Packs/Whois/Integrations/Whois/Whois.yml
  Packs/Whois/Integrations/Whois/Whois_test.py
  Packs/Whois/ReleaseNotes/1_2_1.md
  Packs/Whois/pack_metadata.json
Labels: docs-approved

#11632 Hello world feed
  Packs/HelloWorld/Integrations/FeedHelloWorld/.secrets-ignore
  Packs/HelloWorld/Integrations/FeedHelloWorld/FeedHelloWorld.py
  Packs/HelloWorld/Integrations/FeedHelloWorld/FeedHelloWorld.yml
  Packs/HelloWorld/Integrations/FeedHelloWorld/FeedHelloWorld_description.md
  Packs/HelloWorld/Integrations/FeedHelloWorld/FeedHelloWorld_image.png
  Packs/HelloWorld/Integrations/FeedHelloWorld/FeedHelloWorld_test.py
  Packs/HelloWorld/Integrations/FeedHelloWorld/Pipfile
  Packs/HelloWorld/Integrations/FeedHelloWorld/Pipfile.lock
  Packs/HelloWorld/Integrations/FeedHelloWorld/README_example.md
  Packs/HelloWorld/Integrations/FeedHelloWorld/command_examples
  Packs/HelloWorld/Integrations/FeedHelloWorld/test_data/FeedHelloWorld_mock.txt
  Packs/HelloWorld/Integrations/FeedHelloWorld/test_data/build_iterator_results.json
  Packs/HelloWorld/Integrations/FeedHelloWorld/test_data/get_indicators_command_results.json
  Packs/HelloWorld/ReleaseNotes/1_2_2.md
  Packs/HelloWorld/pack_metadata.json
Labels: docs-approved

#11602 Vt v3
  Packs/VirusTotal/Integrations/VirusTotalV3/README.md
  Packs/VirusTotal/Integrations/VirusTotalV3/TestData/comminicating_files.json
  Packs/VirusTotal/Integrations/VirusTotalV3/TestData/domain.json
  Packs/VirusTotal/Integrations/VirusTotalV3/TestData/file.json
  Packs/VirusTotal/Integrations/VirusTotalV3/TestData/ip.json
  Packs/VirusTotal/Integrations/VirusTotalV3/VirusTotalV3.py
  Packs/VirusTotal/Integrations/VirusTotalV3/VirusTotalV3.yml
  Packs/VirusTotal/Integrations/VirusTotalV3/VirusTotalV3_description.md
  Packs/VirusTotal/Integrations/VirusTotalV3/VirusTotalV3_image.png
  Packs/VirusTotal/Integrations/VirusTotalV3/VirusTotalV3_test.py
  Packs/VirusTotal/Integrations/VirusTotalV3/command_example
  Packs/VirusTotal/Playbooks/Detonate_File_-_VirusTotal_V3.yml
  Packs/VirusTotal/Playbooks/Detonate_URL_-_VirusTotal_V3.yml
  Packs/VirusTotal/README.md
  Packs/VirusTotal/ReleaseNotes/2_0_0.md
  Packs/VirusTotal/TestPlaybooks/VirusTotal_V3_Detonate_Test.yml
  Packs/VirusTotal/TestPlaybooks/testplaybook-VirusTotalV3.yml
  Packs/VirusTotal/pack_metadata.json
  Tests/conf.json
Labels: docs-approved

#12083 XDR - block file playbook | Integration enabled check
  Packs/CommonPlaybooks/Playbooks/playbook-Block_File_-_Generic_v2.yml
  Packs/CommonPlaybooks/ReleaseNotes/1_9_1.md
  Packs/CommonPlaybooks/pack_metadata.json
  Packs/CortexXDR/Playbooks/playbook-Cortex_XDR_-_Block_File.yml
  Packs/CortexXDR/ReleaseNotes/3_0_1.md
  Packs/CortexXDR/pack_metadata.json
Labels: docs-approved

#12035 CheckPhish - Added reliability
  Packs/CheckPhish/Integrations/CheckPhish/CheckPhish.py
  Packs/CheckPhish/Integrations/CheckPhish/CheckPhish.yml
  Packs/CheckPhish/Integrations/CheckPhish/CheckPhish_test.py
  Packs/CheckPhish/Integrations/CheckPhish/README.md
  Packs/CheckPhish/Integrations/CheckPhish/command_examples
  Packs/CheckPhish/ReleaseNotes/1_0_2.md
  Packs/CheckPhish/pack_metadata.json
Labels: docs-approved

#12107 AWS-SQS new pack created by split-yml
  Packs/AWS-SQS/Integrations/AWS-SQS/AWS-SQS.py
  Packs/AWS-SQS/Integrations/AWS-SQS/AWS-SQS.yml
  Packs/AWS-SQS/Integrations/AWS-SQS/AWS-SQS_image.png
  Packs/AWS-SQS/Integrations/AWS-SQS/Pipfile
  Packs/AWS-SQS/Integrations/AWS-SQS/Pipfile.lock
  Packs/AWS-SQS/Integrations/AWS-SQS/README.md
  Packs/AWS-SQS/Integrations/integration-AWS-SQS.yml
  Packs/AWS-SQS/ReleaseNotes/1_0_1.md
  Packs/AWS-SQS/pack_metadata.json
Labels: docs-approved, release-notes-only

#12124 demisto sdk release 1-3-4
  dev-requirements-py3.txt
Labels: docs-approved

#12131 Add documentation for WinRM
  Packs/WinRM/Integrations/WindowsRemoteManagement/README.md
  Packs/WinRM/Integrations/WindowsRemoteManagement/WindowsRemoteManagement.yml
  Packs/WinRM/ReleaseNotes/1_0_3.md
  Packs/WinRM/pack_metadata.json
Labels: docs-approved

#12126 added Rule Name and Tags incident fields
  Packs/CommonTypes/IncidentFields/incidentfield-RuleName.json
  Packs/CommonTypes/IncidentFields/incidentfield-Tags.json
  Packs/CommonTypes/ReleaseNotes/2_8_13.md
  Packs/CommonTypes/pack_metadata.json
Labels: docs-approved

#12108 Deprecate Expanse (v1) Pack + add commands to v2 (from v1)
  Packs/Expanse/Integrations/Expanse/Expanse.yml
  Packs/Expanse/ReleaseNotes/1_2_0.md
  Packs/Expanse/pack_metadata.json
  Packs/ExpanseV2/.secrets-ignore
  Packs/ExpanseV2/Integrations/ExpanseV2/ExpanseV2.py
  Packs/ExpanseV2/Integrations/ExpanseV2/ExpanseV2.yml
  Packs/ExpanseV2/Integrations/ExpanseV2/ExpanseV2_test.py
  Packs/ExpanseV2/Integrations/ExpanseV2/README.md
  Packs/ExpanseV2/Integrations/ExpanseV2/test_data/expanse_assets_for_certificate.json
  Packs/ExpanseV2/Integrations/ExpanseV2/test_data/expanse_assets_ips.json
  Packs/ExpanseV2/Integrations/ExpanseV2/test_data/expanse_get_domains_for_certificates.json
  Packs/ExpanseV2/ReleaseNotes/1_1_0.md
  Packs/ExpanseV2/TestPlaybooks/playbook-ExpanseV2_Test.yml
  Packs/ExpanseV2/pack_metadata.json
Labels: docs-approved, release-notes-only

#12142 fix Jira README issues
  Packs/Jira/Integrations/JiraV2/README.md
Labels: docs-approved

#12130 add unit test for jira issueJson param
  Packs/Jira/Integrations/JiraV2/JiraV2_test.py
Labels: docs-approved

#11701 Q radar v3 integration
  Packs/QRadar/.secrets-ignore
  Packs/QRadar/Classifiers/classifier-QRadar_-_Generic_Incoming_Mapper.json
  Packs/QRadar/Integrations/QRadar_v2/QRadar_v2.yml
  Packs/QRadar/Integrations/QRadar_v2/QRadar_v2_description.md
  Packs/QRadar/Integrations/QRadar_v2/README.md
  Packs/QRadar/Integrations/QRadar_v3/Pipfile
  Packs/QRadar/Integrations/QRadar_v3/Pipfile.lock
  Packs/QRadar/Integrations/QRadar_v3/QRadar_v3.py
  Packs/QRadar/Integrations/QRadar_v3/QRadar_v3.yml
  Packs/QRadar/Integrations/QRadar_v3/QRadar_v3_description.md
  Packs/QRadar/Integrations/QRadar_v3/QRadar_v3_image.png
  Packs/QRadar/Integrations/QRadar_v3/QRadar_v3_test.py
  Packs/QRadar/Integrations/QRadar_v3/README.md
  Packs/QRadar/Integrations/QRadar_v3/command_examples.txt
  Packs/QRadar/Integrations/QRadar_v3/test_data/asset_enrich_test.json
  Packs/QRadar/Integrations/QRadar_v3/test_data/command_test_data.json
  Packs/QRadar/README.md
  Packs/QRadar/ReleaseNotes/2_0_0.md
  Packs/QRadar/TestPlaybooks/QRadar_v3-test.yml
  Packs/QRadar/pack_metadata.json
  Tests/conf.json
Labels: docs-approved

#12150 Update circleci/config.yml - unlock HelloWorld Feed in SDK nightly
  .circleci/config.yml
Labels: docs-approved

#12027 CommonServerPython - add skip update to return error in get remote data
  Packs/Base/ReleaseNotes/1_8_5.md
  Packs/Base/Scripts/CommonServerPython/CommonServerPython.py
  Packs/Base/Scripts/CommonServerPython/CommonServerPython_test.py
  Packs/Base/pack_metadata.json
Labels: docs-approved, release-notes-only

#12081 Uptycs - bump docker image
  Packs/Uptycs/Integrations/Uptycs/Uptycs.py
  Packs/Uptycs/Integrations/Uptycs/Uptycs.yml
  Packs/Uptycs/ReleaseNotes/1_0_5.md
  Packs/Uptycs/pack_metadata.json
Labels: docs-approved

#12080 Infinipoint - bump docker image
  Packs/Infinipoint/Integrations/Infinipoint/Infinipoint.py
  Packs/Infinipoint/Integrations/Infinipoint/Infinipoint.yml
  Packs/Infinipoint/ReleaseNotes/1_0_6.md
  Packs/Infinipoint/pack_metadata.json
Labels: docs-approved

#12106 Added AlphaVantage
  Packs/AlphaVantage/.pack-ignore
  Packs/AlphaVantage/.secrets-ignore
  Packs/AlphaVantage/Integrations/AlphaVantage/AlphaVantage.py
  Packs/AlphaVantage/Integrations/AlphaVantage/AlphaVantage.yml
  Packs/AlphaVantage/Integrations/AlphaVantage/AlphaVantage_description.md
  Packs/AlphaVantage/Integrations/AlphaVantage/AlphaVantage_image.png
  Packs/AlphaVantage/Integrations/AlphaVantage/AlphaVantage_test.py
  Packs/AlphaVantage/Integrations/AlphaVantage/Pipfile
  Packs/AlphaVantage/Integrations/AlphaVantage/Pipfile.lock
  Packs/AlphaVantage/Integrations/AlphaVantage/README.md
  Packs/AlphaVantage/Integrations/AlphaVantage/command_examples
  Packs/AlphaVantage/Integrations/AlphaVantage/test_data/stock history get.json
  Packs/AlphaVantage/Integrations/AlphaVantage/test_data/stock-data-get.json
  Packs/AlphaVantage/Playbooks/Notify_Stock_Above_Price.yml
  Packs/AlphaVantage/Playbooks/Notify_Stock_Above_Price_README.md
  Packs/AlphaVantage/README.md
  Packs/AlphaVantage/TestPlaybooks/AlphaVantage Test Playbook.yml
  Packs/AlphaVantage/doc_imgs/Notify-Stock-Above-Price-image.png
  Packs/AlphaVantage/pack_metadata.json
  Tests/conf.json
Labels: Contribution, docs-approved

#12054 Aws ec2 contrib
  Packs/AWS-EC2/Integrations/AWS-EC2/AWS-EC2.py
  Packs/AWS-EC2/Integrations/AWS-EC2/AWS-EC2.yml
  Packs/AWS-EC2/Integrations/AWS-EC2/README.md
  Packs/AWS-EC2/README.md
  Packs/AWS-EC2/ReleaseNotes/1_1_5.md
  Packs/AWS-EC2/TestPlaybooks/playbook-AWS-EC2Test_actions.yml
  Packs/AWS-EC2/pack_metadata.json
Labels: docs-approved

#12032 Gvault - Added contrib enhancement for pagination
  Packs/GoogleVault/Integrations/GoogleVault/GoogleVault.py
  Packs/GoogleVault/Integrations/GoogleVault/GoogleVault.yml
  Packs/GoogleVault/ReleaseNotes/1_0_3.md
  Packs/GoogleVault/pack_metadata.json
Labels: docs-approved, release-notes-only

#12158 added jochman as a vt code owner
  .github/CODEOWNERS
Labels: docs-approved

#11825 vt v3 premium
  Packs/VirusTotal/Classifiers/classifier-VirusTotal_Intelligence_LiveHunt_Notification-5.9.9.json
  Packs/VirusTotal/Classifiers/classifier-mapper-incoming-VirusTotal_Intelligence_LiveHunt_Notification.json
  Packs/VirusTotal/IncidentTypes/incidenttype-VirusTotalNotification.json
  Packs/VirusTotal/Integrations/VirusTotalV3/README.md
  Packs/VirusTotal/Integrations/VirusTotal_V3_Premium/README.md
  Packs/VirusTotal/Integrations/VirusTotal_V3_Premium/VirusTotal_V3_Premium.png
  Packs/VirusTotal/Integrations/VirusTotal_V3_Premium/VirusTotal_V3_Premium.py
  Packs/VirusTotal/Integrations/VirusTotal_V3_Premium/VirusTotal_V3_Premium.yml
  Packs/VirusTotal/Integrations/VirusTotal_V3_Premium/VirusTotal_V3_Premium_description.md
  Packs/VirusTotal/Integrations/VirusTotal_V3_Premium/VirusTotal_V3_Premium_test.py
  Packs/VirusTotal/Integrations/VirusTotal_V3_Premium/command_examples
  Packs/VirusTotal/Playbooks/Create_Zip_from_VirusTotal.yml
  Packs/VirusTotal/README.md
  Packs/VirusTotal/ReleaseNotes/2_0_1.md
  Packs/VirusTotal/TestPlaybooks/VirusTotal Premium v3 TestPlaybook.yml
  Packs/VirusTotal/pack_metadata.json
  Tests/conf.json
Labels: docs-approved

#11962 IBM Resilient Systems- changed type of api fields
  Packs/IBMResilientSystems/Integrations/IBMResilientSystems/IBMResilientSystems.yml
  Packs/IBMResilientSystems/ReleaseNotes/1_0_5.md
  Packs/IBMResilientSystems/pack_metadata.json
Labels: bug, docs-approved, release-notes-only

#12125 Security compliance purge humanreadable and context bug.
  Packs/EWS/Integrations/SecurityAndCompliance/README.md
  Packs/EWS/Integrations/SecurityAndCompliance/SecurityAndCompliance.Tests.ps1
  Packs/EWS/Integrations/SecurityAndCompliance/SecurityAndCompliance.ps1
  Packs/EWS/Integrations/SecurityAndCompliance/SecurityAndCompliance.yml
  Packs/EWS/ReleaseNotes/1_8_13.md
  Packs/EWS/pack_metadata.json
Labels: docs-approved

#12088 Qradar test failure
  Packs/QRadar/TestPlaybooks/playbook-QRadarCorrelationsV2.yml
  Tests/conf.json
Labels: docs-approved

#12165 Rapid7-Nexpose: Updated relative image paths to full.
  Packs/Rapid7_Nexpose/README.md
Labels: bug, docs-approved

#12139 CDL missing arg fix - possible solution
  Packs/CortexDataLake/Integrations/CortexDataLake/CortexDataLake.yml
  Packs/CortexDataLake/ReleaseNotes/1_3_1.md
  Packs/CortexDataLake/pack_metadata.json
Labels: bug, docs-approved, release-notes-only

#12162 AD - add test for custom attributes
  Packs/Active_Directory_Query/Integrations/Active_Directory_Query/Active_Directory_Query.py
  Packs/Active_Directory_Query/Integrations/Active_Directory_Query/Active_Directory_Query.yml
  Packs/Active_Directory_Query/ReleaseNotes/1_1_9.md
  Packs/Active_Directory_Query/TestPlaybooks/playbook-Active_Directory_Test.yml
  Packs/Active_Directory_Query/pack_metadata.json
Labels: docs-approved, release-notes-only

#12141 Tenable SC - Changed a direct get to a safe get - possible solution
  Packs/Tenable_sc/Integrations/Tenable_sc/Tenable_sc.py
  Packs/Tenable_sc/ReleaseNotes/1_0_1.md
  Packs/Tenable_sc/pack_metadata.json
Labels: bug, docs-approved, release-notes-only

#12128 RedCanary: Changed to python3
  Packs/RedCanary/Integrations/RedCanary/RedCanary.py
  Packs/RedCanary/Integrations/RedCanary/RedCanary.yml
  Packs/RedCanary/ReleaseNotes/1_1_0.md
  Packs/RedCanary/pack_metadata.json
Labels: bug, docs-approved

#12163 Add reliability parameter to Google Safe Browsing
  Packs/GoogleSafeBrowsing/Integrations/README.md
  Packs/GoogleSafeBrowsing/Integrations/examples
  Packs/GoogleSafeBrowsing/Integrations/integration-GoogleSafeBrowsing.yml
  Packs/GoogleSafeBrowsing/ReleaseNotes/1_0_2.md
  Packs/GoogleSafeBrowsing/pack_metadata.json
Labels: docs-approved

#12164 Added reliability parameter to ThreatExchange
  Packs/ThreatExchange/Integrations/README.md
  Packs/ThreatExchange/Integrations/integration-ThreatExchange.yml
  Packs/ThreatExchange/ReleaseNotes/1_0_2.md
  Packs/ThreatExchange/pack_metadata.json
Labels: docs-approved

#12114 Bitsight fix fields names
  Packs/BitSight/Classifiers/classifier-mapper-incoming-BitSight.json
  Packs/BitSight/IncidentFields/BitSight_Affects_Rating.json
  Packs/BitSight/IncidentFields/BitSight_Assets.json
  Packs/BitSight/IncidentFields/BitSight_Comments.json
  Packs/BitSight/IncidentFields/BitSight_Evidence_Key.json
  Packs/BitSight/IncidentFields/BitSight_Related_Findings.json
  Packs/BitSight/IncidentFields/BitSight_Remaining_Decay.json
  Packs/BitSight/IncidentFields/BitSight_Risk_Category.json
  Packs/BitSight/IncidentFields/BitSight_Risk_Vector.json
  Packs/BitSight/IncidentFields/BitSight_Risk_Vector_Label.json
  Packs/BitSight/IncidentFields/BitSight_Rolledup_Observation_Id.json
  Packs/BitSight/IncidentFields/BitSight_Severity_Category.json
  Packs/BitSight/IncidentFields/BitSight_Tags.json
  Packs/BitSight/IncidentFields/BitSight_Temporary_Id.json
  Packs/BitSight/Integrations/BitSightForSecurityPerformanceManagement/BitSightForSecurityPerformanceManagement.yml
  Packs/BitSight/Layouts/layoutscontainer-BitSight_Findings.json
  Packs/BitSight/ReleaseNotes/1_0_2.md
  Packs/BitSight/pack_metadata.json
Labels: bug, docs-approved, release-notes-only

#12001 Unisolate generic
  Packs/Carbon_Black_Enterprise_Response/Playbooks/playbook-Carbon_Black_Response_-_Unisolate_Endpoint.yml
  Packs/Carbon_Black_Enterprise_Response/Playbooks/playbook-Carbon_Black_Response_-_Unisolate_Endpoint_README.md
  Packs/Carbon_Black_Enterprise_Response/ReleaseNotes/1_1_6.md
  Packs/Carbon_Black_Enterprise_Response/doc_files/Carbon_Black_Response_-_Unisolate_Endpoint.png
  Packs/Carbon_Black_Enterprise_Response/pack_metadata.json
  Packs/CommonPlaybooks/Playbooks/playbook-Unisolate_Endpoint_-_Generic.yml
  Packs/CommonPlaybooks/Playbooks/playbook-Unisolate_Endpoint_-_Generic_README.md
  Packs/CommonPlaybooks/ReleaseNotes/1_9_2.md
  Packs/CommonPlaybooks/doc_files/Unisolate_Endpoint_-_Generic.png
  Packs/CommonPlaybooks/pack_metadata.json
  Packs/CortexXDR/Playbooks/playbook-Cortex_XDR_-_Unisolate_Endpoint.yml
  Packs/CortexXDR/Playbooks/playbook-Cortex_XDR_-_Unisolate_Endpoint_README.md
  Packs/CortexXDR/ReleaseNotes/3_0_2.md
  Packs/CortexXDR/doc_files/Cortex_XDR_-_Unisolate_Endpoint.png
  Packs/CortexXDR/pack_metadata.json
  Packs/CrowdStrikeFalcon/Playbooks/playbook-Crowdstrike_Falcon_-_Unisolate_Endpoint.yml
  Packs/CrowdStrikeFalcon/Playbooks/playbook-Crowdstrike_Falcon_-_Unisolate_Endpoint_README.md
  Packs/CrowdStrikeFalcon/ReleaseNotes/1_2_15.md
  Packs/CrowdStrikeFalcon/doc_files/Crowdstrike_Falcon_-_Unisolate_Endpoint.png
  Packs/CrowdStrikeFalcon/pack_metadata.json
  Packs/Cybereason/Playbooks/playbook-Unisolate_Endpoint_-_Cybereason.yml
  Packs/Cybereason/Playbooks/playbook-Unisolate_Endpoint_-_Cybereason_README.md
  Packs/Cybereason/ReleaseNotes/1_0_7.md
  Packs/Cybereason/doc_files/Unisolate_Endpoint_-_Cybereason.png
  Packs/Cybereason/pack_metadata.json
  Packs/FireEyeHX/Playbooks/playbook-FireEye_HX_-_Unisolate_Endpoint.yml
  Packs/FireEyeHX/Playbooks/playbook-FireEye_HX_-_Unisolate_Endpoint_README.md
  Packs/FireEyeHX/ReleaseNotes/1_0_10.md
  Packs/FireEyeHX/doc_files/FireEye_HX_-_Unisolate_Endpoint.png
  Packs/FireEyeHX/pack_metadata.json
Labels: docs-approved

#11480 TOPdesk integration
  Packs/TOPdesk/.pack-ignore
  Packs/TOPdesk/.secrets-ignore
  Packs/TOPdesk/Classifiers/classifier-mapper-incoming-TOPdesk.json
  Packs/TOPdesk/IncidentFields/incidentfield-TOPdesk_call_type.json
  Packs/TOPdesk/IncidentFields/incidentfield-TOPdesk_caller_branch_name.json
  Packs/TOPdesk/IncidentFields/incidentfield-TOPdesk_caller_name.json
  Packs/TOPdesk/IncidentFields/incidentfield-TOPdesk_category.json
  Packs/TOPdesk/IncidentFields/incidentfield-TOPdesk_creation_date.json
  Packs/TOPdesk/IncidentFields/incidentfield-TOPdesk_creator.json
  Packs/TOPdesk/IncidentFields/incidentfield-TOPdesk_duration.json
  Packs/TOPdesk/IncidentFields/incidentfield-TOPdesk_entry_type.json
  Packs/TOPdesk/IncidentFields/incidentfield-TOPdesk_impact.json
  Packs/TOPdesk/IncidentFields/incidentfield-TOPdesk_line.json
  Packs/TOPdesk/IncidentFields/incidentfield-TOPdesk_mainincident.json
  Packs/TOPdesk/IncidentFields/incidentfield-TOPdesk_modification_date.json
  Packs/TOPdesk/IncidentFields/incidentfield-TOPdesk_modifier.json
  Packs/TOPdesk/IncidentFields/incidentfield-TOPdesk_number.json
  Packs/TOPdesk/IncidentFields/incidentfield-TOPdesk_priority.json
  Packs/TOPdesk/IncidentFields/incidentfield-TOPdesk_processing_status.json
  Packs/TOPdesk/IncidentFields/incidentfield-TOPdesk_subcategory.json
  Packs/TOPdesk/IncidentFields/incidentfield-TOPdesk_urgency.json
  Packs/TOPdesk/IncidentTypes/incidenttype-TOPdeskIncident.json
  Packs/TOPdesk/Integrations/TOPdesk/Pipfile
  Packs/TOPdesk/Integrations/TOPdesk/Pipfile.lock
  Packs/TOPdesk/Integrations/TOPdesk/README.md
  Packs/TOPdesk/Integrations/TOPdesk/TOPdesk.py
  Packs/TOPdesk/Integrations/TOPdesk/TOPdesk.yml
  Packs/TOPdesk/Integrations/TOPdesk/TOPdesk_description.md
  Packs/TOPdesk/Integrations/TOPdesk/TOPdesk_image.png
  Packs/TOPdesk/Integrations/TOPdesk/TOPdesk_test.py
  Packs/TOPdesk/Integrations/TOPdesk/test_data/mock_upload_file.txt
  Packs/TOPdesk/Integrations/TOPdesk/test_data/topdesk_attachment.json
  Packs/TOPdesk/Integrations/TOPdesk/test_data/topdesk_branch.json
  Packs/TOPdesk/Integrations/TOPdesk/test_data/topdesk_incident.json
  Packs/TOPdesk/Integrations/TOPdesk/test_data/topdesk_operator.json
  Packs/TOPdesk/Integrations/TOPdesk/test_data/topdesk_person.json
  Packs/TOPdesk/Layouts/layoutscontainer-TOPdesk_incident.json
  Packs/TOPdesk/README.md
  Packs/TOPdesk/TestPlaybooks/TestTOPdeskPlaybook.yml
  Packs/TOPdesk/pack_metadata.json
  Tests/conf.json
Labels: docs-approved

#12166 Fix LogRhythm-Test-Playbook
  Packs/LogRhythm/TestPlaybooks/playbook-LogRhythm_Test_Playbook.yml
Labels: docs-approved

#12167 Rename Cisco Stealthwatch & Stealthwatch Cloud
  Packs/CiscoStealthwatch/Integrations/CiscoStealthwatch/README.md
  Packs/CiscoStealthwatch/Integrations/CiscoStealthwatch/cisco_stealthwatch.yml
  Packs/CiscoStealthwatch/ReleaseNotes/1_0_1.md
  Packs/CiscoStealthwatch/pack_metadata.json
  Packs/Stealthwatch_Cloud/Integrations/Stealthwatch_Cloud/README.md
  Packs/Stealthwatch_Cloud/Integrations/Stealthwatch_Cloud/Stealthwatch_Cloud.yml
  Packs/Stealthwatch_Cloud/ReleaseNotes/1_0_4.md
  Packs/Stealthwatch_Cloud/pack_metadata.json
Labels: docs-approved

#12157 Recommend users to use VT-V3
  Packs/VirusTotal/Integrations/integration-VirusTotal_5.5.yml
  Packs/VirusTotal/ReleaseNotes/2_0_2.md
  Packs/VirusTotal/pack_metadata.json
Labels: docs-approved

#12005 Panos to cdl monitoring - xsoar supported
  Packs/PANOStoCDLMonitoring/.pack-ignore
  Packs/PANOStoCDLMonitoring/.secrets-ignore
  Packs/PANOStoCDLMonitoring/IncidentFields/incidentfield-fw_serials.json
  Packs/PANOStoCDLMonitoring/IncidentFields/incidentfield-panos_integration_instance_name.json
  Packs/PANOStoCDLMonitoring/IncidentTypes/incidenttype-CDL_Monitoring.json
  Packs/PANOStoCDLMonitoring/IncidentTypes/incidenttype-PAN-OStoCDLMonitoring-Action_Required.json
  Packs/PANOStoCDLMonitoring/Layouts/layoutscontainer-CortexDataLakeMonitoring.json
  Packs/PANOStoCDLMonitoring/Layouts/layoutscontainer-PAN-OStoCDLMonitoring-Action_Required.json
  Packs/PANOStoCDLMonitoring/Playbooks/PAN-OStoCDLMonitoring-Action_Required.yml
  Packs/PANOStoCDLMonitoring/Playbooks/PAN-OStoCDLMonitoring-Action_Required_README.md
  Packs/PANOStoCDLMonitoring/Playbooks/PANOStoCDLMonitoring-cron_job.yml
  Packs/PANOStoCDLMonitoring/Playbooks/PANOStoCDLMonitoring-cron_job_README.md
  Packs/PANOStoCDLMonitoring/README.md
  Packs/PANOStoCDLMonitoring/Scripts/PANOStoCortexDataLakeMonitoring/PANOStoCortexDataLakeMonitoring.py
  Packs/PANOStoCDLMonitoring/Scripts/PANOStoCortexDataLakeMonitoring/PANOStoCortexDataLakeMonitoring.yml
  Packs/PANOStoCDLMonitoring/Scripts/PANOStoCortexDataLakeMonitoring/PANOStoCortexDataLakeMonitoring_test.py
  Packs/PANOStoCDLMonitoring/Scripts/PANOStoCortexDataLakeMonitoring/README.md
  Packs/PANOStoCDLMonitoring/pack_metadata.json
Labels: docs-approved

#12071 Okta IAM updates
  Packs/Okta/Classifiers/classifier-mapper-Okta_IAM.json
  Packs/Okta/Integrations/Okta_IAM/Okta_IAM.py
  Packs/Okta/Integrations/Okta_IAM/Okta_IAM.yml
  Packs/Okta/Integrations/Okta_IAM/Okta_IAM_test.py
  Packs/Okta/ReleaseNotes/2_1_8.md
  Packs/Okta/pack_metadata.json
Labels: docs-approved, release-notes-only

#12156 pan-os edl migration guide
  Packs/EDL/Integrations/EDL/README.md
  Packs/EDL/ReleaseNotes/1_0_11.md
  Packs/EDL/pack_metadata.json
  Packs/PaloAltoNetworks_PAN_OS_EDL_Management/Integrations/PaloAltoNetworks_PAN_OS_EDL_Management/PaloAltoNetworks_PAN_OS_EDL_Management_description.md
  Packs/PaloAltoNetworks_PAN_OS_EDL_Management/ReleaseNotes/1_0_4.md
  Packs/PaloAltoNetworks_PAN_OS_EDL_Management/pack_metadata.json
Labels: docs-approved

#12092 Fix bug similar incidents by indicators
  Packs/Base/ReleaseNotes/1_8_6.md
  Packs/Base/Scripts/DBotFindSimilarIncidentsByIndicators/DBotFindSimilarIncidentsByIndicators.py
  Packs/Base/Scripts/DBotFindSimilarIncidentsByIndicators/DBotFindSimilarIncidentsByIndicators.yml
  Packs/Base/pack_metadata.json
Labels: docs-approved

#12133 Fix bug similar incident contents return format
  Packs/Base/ReleaseNotes/1_8_7.md
  Packs/Base/Scripts/DBotFindSimilarIncidents/DBotFindSimilarIncidents.py
  Packs/Base/Scripts/DBotFindSimilarIncidents/DBotFindSimilarIncidents.yml
  Packs/Base/pack_metadata.json
Labels: docs-approved

#12109 [EDL] Fixed an issue where an indicator page was skipped
  Packs/EDL/Integrations/EDL/EDL.py
  Packs/EDL/ReleaseNotes/1_0_12.md
  Packs/EDL/pack_metadata.json
Labels: docs-approved

#12104 Added to CommandResults support for PollingCommands results
  Packs/Base/ReleaseNotes/1_8_8.md
  Packs/Base/Scripts/CommonServerPython/CommonServerPython.py
  Packs/Base/pack_metadata.json
Labels: docs-approved, release-notes-only

#12179 Jirav2: Issue reporter bug fix
  Packs/Jira/Integrations/JiraV2/JiraV2.py
  Packs/Jira/Integrations/JiraV2/JiraV2.yml
  Packs/Jira/Integrations/JiraV2/README.md
  Packs/Jira/ReleaseNotes/1_3_2.md
  Packs/Jira/TestPlaybooks/playbook-Jira-v2-Test.yml
  Packs/Jira/pack_metadata.json
Labels: bug, docs-approved, release-notes-only

#12127 Cybereason malop processes bug fix
  Packs/Cybereason/.secrets-ignore
  Packs/Cybereason/Integrations/Cybereason/Cybereason.py
  Packs/Cybereason/Integrations/Cybereason/Cybereason_test.py
  Packs/Cybereason/Integrations/Cybereason/test_files/malop_processes_raw_response.json
  Packs/Cybereason/ReleaseNotes/1_0_8.md
  Packs/Cybereason/TestPlaybooks/playbook-Cybereason_Test.yml
  Packs/Cybereason/pack_metadata.json
Labels: bug, docs-approved, release-notes-only

#11516 Adding create meeting command to MS teams
  Packs/MicrosoftTeams/Integrations/MicrosoftTeams/MicrosoftTeams.py
  Packs/MicrosoftTeams/Integrations/MicrosoftTeams/MicrosoftTeams.yml
  Packs/MicrosoftTeams/Integrations/MicrosoftTeams/MicrosoftTeams_test.py
  Packs/MicrosoftTeams/Integrations/MicrosoftTeams/README.md
  Packs/MicrosoftTeams/ReleaseNotes/1_1_6.md
  Packs/MicrosoftTeams/Scripts/ConfigureAzureApplicationAccessPolicy/ConfigureAzureApplicationAccessPolicy.Tests.ps1
  Packs/MicrosoftTeams/Scripts/ConfigureAzureApplicationAccessPolicy/ConfigureAzureApplicationAccessPolicy.ps1
  Packs/MicrosoftTeams/Scripts/ConfigureAzureApplicationAccessPolicy/ConfigureAzureApplicationAccessPolicy.yml
  Packs/MicrosoftTeams/Scripts/ConfigureAzureApplicationAccessPolicy/README.md
  Packs/MicrosoftTeams/Scripts/ConfigureAzureApplicationAccessPolicy/command_examples
  Packs/MicrosoftTeams/pack_metadata.json
Labels: docs-approved

#11923 Gmail no inbox failure
  Packs/Gmail/Integrations/Gmail/Gmail.py
  Packs/Gmail/Integrations/Gmail/Gmail.yml
  Packs/Gmail/ReleaseNotes/1_1_6.md
  Packs/Gmail/pack_metadata.json
Labels: docs-approved

#12196 bump version 21.4.0
  .circleci/content_release_vars.sh
Labels: docs-approved

#12138 Added GitHub-get-file-content command
  Packs/GitHub/Integrations/GitHub/GitHub.py
  Packs/GitHub/Integrations/GitHub/GitHub.yml
  Packs/GitHub/Integrations/GitHub/README.md
  Packs/GitHub/README.md
  Packs/GitHub/ReleaseNotes/1_1_11.md
  Packs/GitHub/TestPlaybooks/playbook-Git_Integration-Test.yml
  Packs/GitHub/pack_metadata.json
Labels: docs-approved

#12185 UnEscapeURLs - Added support for Proofpoint gov cloud addresses
  Packs/CommonScripts/ReleaseNotes/1_3_34.md
  Packs/CommonScripts/Scripts/script-UnEscapeURLs.yml
  Packs/CommonScripts/TestPlaybooks/playbook-UnEscapeURLs-Test.yml
  Packs/CommonScripts/pack_metadata.json
Labels: bug, docs-approved, release-notes-only

#12210 nessus: fixed outputs
  Packs/nessus/Integrations/integration-nessus.yml
  Packs/nessus/ReleaseNotes/1_0_1.md
  Packs/nessus/pack_metadata.json
Labels: bug, docs-approved

#12214 opencti: rename pack
  Packs/FeedOpenCTI/pack_metadata.json
Labels: docs-approved

#12216 jira: clarify release notes about BC
  Packs/Jira/ReleaseNotes/1_3_2.md
Labels: docs-approved

#12146 StringifyArray - Fixed an incorrect script type in README
  Packs/StringifyArray/README.md
  Packs/StringifyArray/ReleaseNotes/1_0_1.md
  Packs/StringifyArray/pack_metadata.json
Labels: docs-approved

#12215 talos feed: update pack name
  Packs/FeedTalos/pack_metadata.json
Labels: docs-approved

#12136 adding sdk conf file to the gitignore
  .gitignore
Labels: docs-approved

#12090 Fix bug alien vault otx url error response
  Packs/AlienVault_OTX/Integrations/AlienVault_OTX_v2/AlienVault_OTX_v2.py
  Packs/AlienVault_OTX/Integrations/AlienVault_OTX_v2/AlienVault_OTX_v2.yml
  Packs/AlienVault_OTX/Integrations/AlienVault_OTX_v2/AlienVault_OTX_v2_test.py
  Packs/AlienVault_OTX/ReleaseNotes/1_0_4.md
  Packs/AlienVault_OTX/pack_metadata.json
Labels: bug, docs-approved, release-notes-only

#12217 Typo in Nessus
  Packs/nessus/Integrations/integration-nessus.yml
  Packs/nessus/ReleaseNotes/1_0_2.md
  Packs/nessus/pack_metadata.json
Labels: docs-approved

#11966 [Sixgill-195] DVE feed
  Packs/Sixgill-Darkfeed/IndicatorFields/indicator_cvss20score.json
  Packs/Sixgill-Darkfeed/IndicatorFields/indicator_cvss20severity.json
  Packs/Sixgill-Darkfeed/IndicatorFields/indicator_cvss31score.json
  Packs/Sixgill-Darkfeed/IndicatorFields/indicator_cvss31severity.json
  Packs/Sixgill-Darkfeed/IndicatorFields/indicator_eventaction.json
  Packs/Sixgill-Darkfeed/IndicatorFields/indicator_eventdatetime.json
  Packs/Sixgill-Darkfeed/IndicatorFields/indicator_eventdescription.json
  Packs/Sixgill-Darkfeed/IndicatorFields/indicator_eventname.json
  Packs/Sixgill-Darkfeed/IndicatorFields/indicator_eventtype.json
  Packs/Sixgill-Darkfeed/IndicatorFields/indicator_externalid.json
  Packs/Sixgill-Darkfeed/IndicatorFields/indicator_nvdlastmodifieddate.json
  Packs/Sixgill-Darkfeed/IndicatorFields/indicator_nvdlink.json
  Packs/Sixgill-Darkfeed/IndicatorFields/indicator_nvdpublicationdate.json
  Packs/Sixgill-Darkfeed/IndicatorFields/indicator_nvdvectorv20.json
  Packs/Sixgill-Darkfeed/IndicatorFields/indicator_nvdvectorv31.json
  Packs/Sixgill-Darkfeed/IndicatorFields/indicator_previouslevel.json
  Packs/Sixgill-Darkfeed/IndicatorFields/indicator_sixgilldvescorecurrent.json
  Packs/Sixgill-Darkfeed/IndicatorFields/indicator_sixgilldvescorehighestever.json
  Packs/Sixgill-Darkfeed/IndicatorFields/indicator_sixgilldvescorehighesteverdate.json
  Packs/Sixgill-Darkfeed/IndicatorFields/indicator_sixgillpreviouslyexploitedprobability.json
  Packs/Sixgill-Darkfeed/Integrations/Sixgill_DVE_Feed/README.md
  Packs/Sixgill-Darkfeed/Integrations/Sixgill_DVE_Feed/Sixgill_DVE_Feed.py
  Packs/Sixgill-Darkfeed/Integrations/Sixgill_DVE_Feed/Sixgill_DVE_Feed.yml
  Packs/Sixgill-Darkfeed/Integrations/Sixgill_DVE_Feed/Sixgill_DVE_Feed_description.md
  Packs/Sixgill-Darkfeed/Integrations/Sixgill_DVE_Feed/Sixgill_DVE_Feed_image.png
  Packs/Sixgill-Darkfeed/Integrations/Sixgill_DVE_Feed/Sixgill_DVE_Feed_test.py
  Packs/Sixgill-Darkfeed/ReleaseNotes/2_0_0.md
  Packs/Sixgill-Darkfeed/pack_metadata.json
Labels: Contribution, Partner, docs-approved, ready-for-instance-test

#12187 adding limitation to the docs
  Packs/EWS/Integrations/EWSv2/README.md
Labels: docs-approved

#11931 Expanse - Adding support for Services API and POCs
  Packs/ExpanseV2/.secrets-ignore
  Packs/ExpanseV2/Integrations/ExpanseV2/ExpanseV2.py
  Packs/ExpanseV2/Integrations/ExpanseV2/ExpanseV2.yml
  Packs/ExpanseV2/Integrations/ExpanseV2/ExpanseV2_test.py
  Packs/ExpanseV2/Integrations/ExpanseV2/README.md
  Packs/ExpanseV2/Integrations/ExpanseV2/command_examples.txt
  Packs/ExpanseV2/Integrations/ExpanseV2/test_data/expanse_create_poc.json
  Packs/ExpanseV2/Integrations/ExpanseV2/test_data/expanse_get_services.json
  Packs/ExpanseV2/Integrations/ExpanseV2/test_data/expanse_list_pocs.json
  Packs/ExpanseV2/ReleaseNotes/1_2_0.md
  Packs/ExpanseV2/pack_metadata.json
Labels: Contribution, docs-approved, pending-demo

#11891 Aws gd enhancement contrib
  Packs/AWS-GuardDuty/Integrations/AWS-GuardDuty/AWS-GuardDuty.py
  Packs/AWS-GuardDuty/Integrations/AWS-GuardDuty/AWS-GuardDuty.yml
  Packs/AWS-GuardDuty/Integrations/AWS-GuardDuty/README.md
  Packs/AWS-GuardDuty/README.md
  Packs/AWS-GuardDuty/ReleaseNotes/1_1_0.md
  Packs/AWS-GuardDuty/pack_metadata.json
Labels: docs-approved

#12218 SplunkPy: fixed human readable header parsing
  Packs/SplunkPy/Integrations/SplunkPy/SplunkPy.py
  Packs/SplunkPy/Integrations/SplunkPy/SplunkPy_test.py
  Packs/SplunkPy/ReleaseNotes/2_0_1.md
  Packs/SplunkPy/pack_metadata.json
Labels: bug, docs-approved, release-notes-only

#12152 ParseEmailFiles: fixed parsing issue of ics files + encoding issue
  Packs/CommonScripts/ReleaseNotes/1_3_35.md
  Packs/CommonScripts/Scripts/ParseEmailFiles/ParseEmailFiles.py
  Packs/CommonScripts/Scripts/ParseEmailFiles/ParseEmailFiles_test.py
  Packs/CommonScripts/pack_metadata.json
Labels: bug, docs-approved, release-notes-only

#12178 EDL: fixed IPv6 improper exports
  Packs/EDL/.secrets-ignore
  Packs/EDL/Integrations/EDL/EDL.py
  Packs/EDL/Integrations/EDL/EDL_test.py
  Packs/EDL/ReleaseNotes/1_0_13.md
  Packs/EDL/pack_metadata.json
Labels: bug, docs-approved, release-notes-only

#12174 DisplayEmailHTML: fixed None is not iterable bug
  Packs/EmailCommunication/ReleaseNotes/1_3_6.md
  Packs/EmailCommunication/Scripts/DisplayEmailHtml/DisplayEmailHtml.py
  Packs/EmailCommunication/Scripts/DisplayEmailHtml/DisplayEmailHtml.yml
  Packs/EmailCommunication/pack_metadata.json
Labels: bug, docs-approved, release-notes-only

#12143 fixed typo in CortexXDR
  Packs/CortexXDR/Integrations/CortexXDRIR/CortexXDRIR.py
  Packs/CortexXDR/Integrations/CortexXDRIR/CortexXDRIR.yml
  Packs/CortexXDR/ReleaseNotes/3_0_3.md
  Packs/CortexXDR/pack_metadata.json
Labels: docs-approved

#12221 Whois - fixed a wrong output
  Packs/Whois/Integrations/Whois/Whois.py
  Packs/Whois/Integrations/Whois/Whois_test.py
  Packs/Whois/ReleaseNotes/1_2_2.md
  Packs/Whois/pack_metadata.json
Labels: docs-approved, release-notes-only

#12002 AWS-DynamoDB bug
  Packs/AWS_DynamoDB/Integrations/AWS_DynamoDB/AWS_DynamoDB.py
  Packs/AWS_DynamoDB/Integrations/AWS_DynamoDB/AWS_DynamoDB.yml
  Packs/AWS_DynamoDB/ReleaseNotes/1_0_4.md
  Packs/AWS_DynamoDB/TestPlaybooks/playbook-AWS-DynamoDB-Test.yml
  Packs/AWS_DynamoDB/pack_metadata.json
Labels: docs-approved, release-notes-only

#12195 Added `email-header: decode" operator.
  Packs/ExtFilter/ReleaseNotes/1_1_1.md
  Packs/ExtFilter/Scripts/ExtFilter/ExtFilter.py
  Packs/ExtFilter/Scripts/ExtFilter/ExtFilter.yml
  Packs/ExtFilter/Scripts/ExtFilter/README.md
  Packs/ExtFilter/TestPlaybooks/Test_-_ExtFilter.yml
  Packs/ExtFilter/TestPlaybooks/Test_-_ExtFilter_Main.yml
  Packs/ExtFilter/pack_metadata.json
Labels: Contribution, docs-approved

#12223 revert DBot Truth Bombs search rank exception
  Packs/DBotTruthBombs/README.md
  Tests/Marketplace/marketplace_services.py
Labels: docs-approved

#12224 Upload-Flow using regular diff
  Tests/Marketplace/marketplace_services.py
Labels: docs-approved

#12171 AbuseIpdb contrib addition
  Packs/AbuseDB/Integrations/AbuseDB/AbuseDB.py
  Packs/AbuseDB/Integrations/AbuseDB/AbuseDB.yml
  Packs/AbuseDB/ReleaseNotes/1_0_4.md
  Packs/AbuseDB/pack_metadata.json
Labels: docs-approved, release-notes-only

#12229 GoogleSafeBrowing: change API key parameter to encrypted text
  Packs/GoogleSafeBrowsing/Integrations/integration-GoogleSafeBrowsing.yml
  Packs/GoogleSafeBrowsing/ReleaseNotes/1_0_3.md
  Packs/GoogleSafeBrowsing/pack_metadata.json
Labels: bug, docs-approved, release-notes-only

#11705 new integration Cisco ThreatGrid feed
  Packs/ThreatGrid/Integrations/FeedCiscoSecureMalwareAnalytics/FeedCiscoSecureMalwareAnalytics.py
  Packs/ThreatGrid/Integrations/FeedCiscoSecureMalwareAnalytics/FeedCiscoSecureMalwareAnalytics.yml
  Packs/ThreatGrid/Integrations/FeedCiscoSecureMalwareAnalytics/FeedCiscoSecureMalwareAnalytics_description.md
  Packs/ThreatGrid/Integrations/FeedCiscoSecureMalwareAnalytics/FeedCiscoSecureMalwareAnalytics_image.png
  Packs/ThreatGrid/Integrations/FeedCiscoSecureMalwareAnalytics/FeedCiscoSecureMalwareAnalytics_test.py
  Packs/ThreatGrid/Integrations/FeedCiscoSecureMalwareAnalytics/README.md
  Packs/ThreatGrid/Integrations/FeedCiscoSecureMalwareAnalytics/command_example.txt
  Packs/ThreatGrid/Integrations/FeedCiscoSecureMalwareAnalytics/test_data/feed_data.py
  Packs/ThreatGrid/README.md
  Packs/ThreatGrid/ReleaseNotes/1_2_0.md
  Packs/ThreatGrid/pack_metadata.json
Labels: docs-approved

#12183 MS Graph Mail - added reply-mail command
  Packs/EmailCommunication/Classifiers/classifier-MSGraphMail_-_Classifier_-_Email_Communication.json
  Packs/EmailCommunication/Classifiers/classifier-MSGraphMail_-_Classifier_-_Email_Communication_5_9_9.json
  Packs/EmailCommunication/Classifiers/classifier-MSGraphMail_-_Incoming_Mapper_-_Email_Communication.json
  Packs/EmailCommunication/ReleaseNotes/1_3_7.md
  Packs/EmailCommunication/pack_metadata.json
  Packs/MicrosoftGraphMail/Integrations/MicrosoftGraphMail/MicrosoftGraphMail.py
  Packs/MicrosoftGraphMail/Integrations/MicrosoftGraphMail/MicrosoftGraphMail.yml
  Packs/MicrosoftGraphMail/Integrations/MicrosoftGraphMail/MicrosoftGraphMail_test.py
  Packs/MicrosoftGraphMail/Integrations/MicrosoftGraphMail/README.md
  Packs/MicrosoftGraphMail/Integrations/MicrosoftGraphMail/commands.txt
  Packs/MicrosoftGraphMail/ReleaseNotes/1_0_19.md
  Packs/MicrosoftGraphMail/pack_metadata.json
Labels: docs-approved

#12060 XDR scan abort command
  Packs/CortexXDR/Integrations/CortexXDRIR/CortexXDRIR.py
  Packs/CortexXDR/Integrations/CortexXDRIR/CortexXDRIR.yml
  Packs/CortexXDR/Integrations/CortexXDRIR/CortexXDRIR_test.py
  Packs/CortexXDR/Integrations/CortexXDRIR/README.md
  Packs/CortexXDR/Integrations/CortexXDRIR/command_examples
  Packs/CortexXDR/ReleaseNotes/3_0_4.md
  Packs/CortexXDR/pack_metadata.json
Labels: docs-approved

#11129 [Community Contribution] Armis - Content Pack
  Packs/Armis/.pack-ignore
  Packs/Armis/.secrets-ignore
  Packs/Armis/Classifiers/classifier-Armis_5_9_9.json
  Packs/Armis/Classifiers/classifier-Armis_mapper-incoming.json
  Packs/Armis/Classifiers/classifier-classifier-armis-alerts.json
  Packs/Armis/IncidentFields/incidentfields_Armis_Alert_Desctiption.json
  Packs/Armis/IncidentFields/incidentfields_Armis_Alert_ID.json
  Packs/Armis/IncidentFields/incidentfields_Armis_Alert_Severity.json
  Packs/Armis/IncidentFields/incidentfields_Armis_Alert_Status.json
  Packs/Armis/IncidentFields/incidentfields_Armis_Alert_Type.json
  Packs/Armis/IncidentFields/incidentfields_Armis_Device_ID.json
  Packs/Armis/IncidentFields/incidentfields_Armis_Device_Risk_Level.json
  Packs/Armis/IncidentTypes/Armis_Custom_Incident_Types.json
  Packs/Armis/Integrations/Armis/Armis.py
  Packs/Armis/Integrations/Armis/Armis.yml
  Packs/Armis/Integrations/Armis/Armis_description.md
  Packs/Armis/Integrations/Armis/Armis_image.png
  Packs/Armis/Integrations/Armis/Armis_test.py
  Packs/Armis/Integrations/Armis/Pipfile
  Packs/Armis/Integrations/Armis/Pipfile.lock
  Packs/Armis/Integrations/Armis/README.md
  Packs/Armis/Integrations/Armis/command_examples.txt
  Packs/Armis/Layouts/layout-details-Armis_Alert.json
  Packs/Armis/Layouts/layoutscontainer-Armis_Alert.json
  Packs/Armis/Playbooks/Armis_Device_Enrichment.yml
  Packs/Armis/Playbooks/Armis_Device_Enrichment_README.md
  Packs/Armis/README.md
  Packs/Armis/TestPlaybooks/Armis_Test.yml
  Packs/Armis/doc_files/Armis_Alert_Enrichment.png
  Packs/Armis/doc_files/Armis_Device_Enrichment.png
  Packs/Armis/pack_metadata.json
  Tests/conf.json
Labels: Contribution, docs-approved, ready-for-instance-test
