Repository demisto/content, pull requests merged in 2021-02, with the labels that each got.

#10091 Cymptom
  Packs/Cymptom/.pack-ignore
  Packs/Cymptom/.secrets-ignore
  Packs/Cymptom/IncidentTypes/incidenttype-Cymptom_Mitigations.json
  Packs/Cymptom/Integrations/Cymptom/Cymptom.py
  Packs/Cymptom/Integrations/Cymptom/Cymptom.yml
  Packs/Cymptom/Integrations/Cymptom/Cymptom_description.md
  Packs/Cymptom/Integrations/Cymptom/Cymptom_image.png
  Packs/Cymptom/Integrations/Cymptom/Cymptom_test.py
  Packs/Cymptom/Integrations/Cymptom/Pipfile
  Packs/Cymptom/Integrations/Cymptom/Pipfile.lock
  Packs/Cymptom/Integrations/Cymptom/README.md
  Packs/Cymptom/Integrations/Cymptom/command_examples.txt
  Packs/Cymptom/Integrations/Pipfile
  Packs/Cymptom/Playbooks/Cymptom_-_Expire_passwords_for_password_cracked_users.yml
  Packs/Cymptom/README.md
  Packs/Cymptom/TestPlaybooks/TestCymptomPlaybook.yml
  Packs/Cymptom/pack_metadata.json
Labels: Contribution, Partner, docs-approved, ready-for-instance-test

#11126 Cyren ThreatInDepth Base Content Pack v1.3.0
  Packs/FeedCyrenThreatInDepth/.secrets-ignore
  Packs/FeedCyrenThreatInDepth/Integrations/CyrenThreatInDepth/CyrenThreatInDepth.py
  Packs/FeedCyrenThreatInDepth/Integrations/CyrenThreatInDepth/CyrenThreatInDepth.yml
  Packs/FeedCyrenThreatInDepth/Integrations/CyrenThreatInDepth/CyrenThreatInDepth_description.md
  Packs/FeedCyrenThreatInDepth/Integrations/CyrenThreatInDepth/CyrenThreatInDepth_test.py
  Packs/FeedCyrenThreatInDepth/Integrations/CyrenThreatInDepth/README.md
  Packs/FeedCyrenThreatInDepth/ReleaseNotes/1_3_0.md
  Packs/FeedCyrenThreatInDepth/Scripts/CyrenThreatInDepthRandomHunt/CyrenThreatInDepthRandomHunt.py
  Packs/FeedCyrenThreatInDepth/Scripts/CyrenThreatInDepthRandomHunt/CyrenThreatInDepthRandomHunt.yml
  Packs/FeedCyrenThreatInDepth/Scripts/CyrenThreatInDepthRandomHunt/CyrenThreatInDepthRandomHunt_test.py
  Packs/FeedCyrenThreatInDepth/Scripts/CyrenThreatInDepthRandomHunt/README.md
  Packs/FeedCyrenThreatInDepth/Scripts/CyrenThreatInDepthRelatedWidget/CyrenThreatInDepthRelatedWidget.yml
  Packs/FeedCyrenThreatInDepth/pack_metadata.json
Labels: Contribution

#11191 Fix collect_tests_and_content_packs.py
  Tests/scripts/collect_tests_and_content_packs.py
Labels: docs-approved

#11205 Add Readme files to Shift management
  Packs/ShiftManagement/Scripts/AssignAnalystToIncidentOOO/README.md
  Packs/ShiftManagement/Scripts/AssignToNextShiftOOO/README.md
  Packs/ShiftManagement/Scripts/CreateChannelWrapper/README.md
  Packs/ShiftManagement/Scripts/GetNumberOfUsersOnCall/README.md
  Packs/ShiftManagement/Scripts/GetOnCallHoursPerUser/README.md
  Packs/ShiftManagement/Scripts/GetRolesPerShift/README.md
  Packs/ShiftManagement/Scripts/GetShiftsPerUser/README.md
  Packs/ShiftManagement/Scripts/GetUsersOOO/README.md
  Packs/ShiftManagement/Scripts/GetUsersOnCall/README.md
  Packs/ShiftManagement/Scripts/ManageOOOusers/README.md
  Packs/ShiftManagement/Scripts/OutOfOfficeListCleanup/README.md
  Packs/ShiftManagement/Scripts/TimeToNextShift/README.md
Labels: docs-approved

#11207 sophos FW - rm app names from the readme and test
  Packs/SophosXGFirewall/Integrations/README.md
  Packs/SophosXGFirewall/Integrations/sophos_firewall_test.py
  Packs/SophosXGFirewall/Integrations/test_data/app_policy_list.xml
Labels: docs-approved

#11189 update DO - trigger lints
  Packs/Base/ReleaseNotes/1_7_6.md
  Packs/Base/Scripts/GetMLModelEvaluation/GetMLModelEvaluation.py
  Packs/Base/Scripts/GetMLModelEvaluation/GetMLModelEvaluation.yml
  Packs/Base/pack_metadata.json
  Packs/rasterize/Integrations/rasterize/rasterize.py
  Packs/rasterize/Integrations/rasterize/rasterize.yml
  Packs/rasterize/ReleaseNotes/1_0_6.md
  Packs/rasterize/pack_metadata.json
Labels: docs-approved

#11196 fixing vulture error in ML
  Packs/ML/ReleaseNotes/1_2_2.md
  Packs/ML/Scripts/EvaluateMLModllAtProduction/EvaluateMLModllAtProduction.py
  Packs/ML/Scripts/EvaluateMLModllAtProduction/EvaluateMLModllAtProduction.yml
  Packs/ML/pack_metadata.json
Labels: docs-approved, release-notes-only

#11201 humio readme: fix broken link
  Packs/Humio/Integrations/Humio/README.md
Labels: docs-approved

#11200 rst readme: remove dead link
  Packs/RSTCloud/Integrations/RSTCloudThreatFeedAPI/README.md
Labels: docs-approved

#11181 Palo Alto Networks Automatic SLR - rm community text
  Packs/PaloAltoNetworksAutomaticSLR_Community/Integrations/PaloAltoNetworksAutomaticSLRCommunity/PaloAltoNetworksAutomaticSLRCommunity.yml
  Packs/PaloAltoNetworksAutomaticSLR_Community/Integrations/PaloAltoNetworksAutomaticSLRCommunity/README.md
  Packs/PaloAltoNetworksAutomaticSLR_Community/Playbooks/README.md
  Packs/PaloAltoNetworksAutomaticSLR_Community/ReleaseNotes/1_0_1.md
  Packs/PaloAltoNetworksAutomaticSLR_Community/pack_metadata.json
Labels: docs-approved

#11203 XDR - retrieve file bug fix
  Packs/CortexXDR/Integrations/CortexXDRIR/CortexXDRIR.py
  Packs/CortexXDR/Integrations/CortexXDRIR/CortexXDRIR.yml
  Packs/CortexXDR/Integrations/CortexXDRIR/CortexXDRIR_test.py
  Packs/CortexXDR/ReleaseNotes/2_8_2.md
  Packs/CortexXDR/TestPlaybooks/Test_XDR_Playbook.yml
  Packs/CortexXDR/pack_metadata.json
Labels: bug, docs-approved, release-notes-only

#11188 ServiceNow V2 - Added a better file handling
  Packs/ServiceNow/Integrations/ServiceNowv2/ServiceNowv2.py
  Packs/ServiceNow/Integrations/ServiceNowv2/ServiceNowv2.yml
  Packs/ServiceNow/ReleaseNotes/2_1_10.md
  Packs/ServiceNow/pack_metadata.json
Labels: bug, docs-approved, release-notes-only

#11216 Upload-Flow patch for not installing hidden packs
  Tests/Marketplace/search_and_install_packs.py
Labels: docs-approved

#11147 powershell parse date range
  Packs/Base/ReleaseNotes/1_7_7.md
  Packs/Base/Scripts/CommonServerPowerShell/CommonServerPowerShell.Tests.ps1
  Packs/Base/Scripts/CommonServerPowerShell/CommonServerPowerShell.ps1
  Packs/Base/pack_metadata.json
Labels: docs-approved

#11186 GetLargestInputsAndOuputsInIncidents: added table_result argument and fixed task size
  Packs/CommonWidgets/ReleaseNotes/1_0_6.md
  Packs/CommonWidgets/Scripts/GetLargestInputsAndOuputsInIncidents/GetLargestInputsAndOuputsInIncidents.py
  Packs/CommonWidgets/Scripts/GetLargestInputsAndOuputsInIncidents/GetLargestInputsAndOuputsInIncidents.yml
  Packs/CommonWidgets/Scripts/GetLargestInputsAndOuputsInIncidents/GetLargestInputsAndOuputsInIncidents_test.py
  Packs/CommonWidgets/pack_metadata.json
Labels: bug, docs-approved, release-notes-only

#10953 Azure Kubernetes Services
  Packs/AzureKubernetesServices/.pack-ignore
  Packs/AzureKubernetesServices/.secrets-ignore
  Packs/AzureKubernetesServices/Integrations/AzureKubernetesServices/AzureKubernetesServices.py
  Packs/AzureKubernetesServices/Integrations/AzureKubernetesServices/AzureKubernetesServices.yml
  Packs/AzureKubernetesServices/Integrations/AzureKubernetesServices/AzureKubernetesServices_description.md
  Packs/AzureKubernetesServices/Integrations/AzureKubernetesServices/AzureKubernetesServices_image.png
  Packs/AzureKubernetesServices/Integrations/AzureKubernetesServices/AzureKubernetesServices_test.py
  Packs/AzureKubernetesServices/Integrations/AzureKubernetesServices/Pipfile
  Packs/AzureKubernetesServices/Integrations/AzureKubernetesServices/Pipfile.lock
  Packs/AzureKubernetesServices/Integrations/AzureKubernetesServices/README.md
  Packs/AzureKubernetesServices/Integrations/AzureKubernetesServices/command_examples
  Packs/AzureKubernetesServices/Integrations/AzureKubernetesServices/test_data/clusters_list_response.json
  Packs/AzureKubernetesServices/README.md
  Packs/AzureKubernetesServices/TestPlaybooks/Azure_Kubernetes_Services_-_Test.yml
  Packs/AzureKubernetesServices/pack_metadata.json
Labels: docs-approved

#11219 Run polling command fix
  Packs/CommonScripts/ReleaseNotes/1_3_17.md
  Packs/CommonScripts/Scripts/RunPollingCommand/RunPollingCommand.py
  Packs/CommonScripts/Scripts/RunPollingCommand/RunPollingCommand_test.py
  Packs/CommonScripts/pack_metadata.json
Labels: bug, docs-approved, release-notes-only

#11212 Sophos Firewall - Fixed an issue where some arguments were incorrectly marked as default arguments
  Packs/SophosXGFirewall/Integrations/sophos_firewall.yml
  Packs/SophosXGFirewall/ReleaseNotes/1_0_1.md
  Packs/SophosXGFirewall/pack_metadata.json
Labels: docs-approved, release-notes-only

#11225 Remove tag from conf.json
  Tests/conf.json
Labels: docs-approved

#11177 Palo Alto Networks Endpoint Malware Investigation v3 LinkIncidents Fix
  Packs/PANWComprehensiveInvestigation/Playbooks/Palo_Alto_Networks_-_Endpoint_Malware_Investigation_v3.yml
  Packs/PANWComprehensiveInvestigation/Playbooks/Palo_Alto_Networks_-_Endpoint_Malware_Investigation_v3_README.md
  Packs/PANWComprehensiveInvestigation/ReleaseNotes/1_3_5.md
  Packs/PANWComprehensiveInvestigation/pack_metadata.json
Labels: docs-approved

#11220 Update conf fix
  Tests/scripts/update_conf_json.py
Labels: docs-approved

#11230 bump version
  .circleci/config.yml
Labels: docs-approved

#11232 Upload flow hidden rn bugfix
  Tests/Marketplace/marketplace_services.py
Labels: docs-approved

#11114 Fix content for playbook version validation
  Packs/EmployeeOffboarding/.pack-ignore
  Packs/GoogleChronicleBackstory/.pack-ignore
  Packs/PrismaAccess/Integrations/PrismaAccess/PrismaAccess.yml
  Packs/PrismaAccess/ReleaseNotes/1_0_6.md
  Packs/PrismaAccess/pack_metadata.json
  Packs/QRadar/.pack-ignore
  Packs/TIM_SIEM/Playbooks/playbook-TIM_-_Add_All_Indicator_Types_To_SIEM.yml
  Packs/TIM_SIEM/ReleaseNotes/1_0_4.md
  Packs/TIM_SIEM/pack_metadata.json
Labels: docs-approved, release-notes-only

#11185 CommonServerPython + ApiModules: Fixed insecure error message
  Packs/ApiModules/Scripts/CSVFeedApiModule/CSVFeedApiModule.py
  Packs/ApiModules/Scripts/HTTPFeedApiModule/HTTPFeedApiModule.py
  Packs/ApiModules/Scripts/ServiceNowApiModule/ServiceNowApiModule.py
  Packs/Base/ReleaseNotes/1_7_9.md
  Packs/Base/Scripts/CommonServerPython/CommonServerPython.py
  Packs/Base/Scripts/CommonServerPython/CommonServerPython_test.py
  Packs/Base/pack_metadata.json
  Packs/FeedAlienVault/ReleaseNotes/1_0_11.md
  Packs/FeedAlienVault/pack_metadata.json
  Packs/FeedBambenekConsulting/ReleaseNotes/1_0_9.md
  Packs/FeedBambenekConsulting/pack_metadata.json
  Packs/FeedBlocklist_de/ReleaseNotes/1_0_4.md
  Packs/FeedBlocklist_de/pack_metadata.json
  Packs/FeedBruteForceBlocker/ReleaseNotes/1_0_4.md
  Packs/FeedBruteForceBlocker/pack_metadata.json
  Packs/FeedCSV/ReleaseNotes/1_0_9.md
  Packs/FeedCSV/pack_metadata.json
  Packs/FeedCloudflare/ReleaseNotes/1_0_4.md
  Packs/FeedCloudflare/pack_metadata.json
  Packs/FeedDShield/ReleaseNotes/1_0_4.md
  Packs/FeedDShield/pack_metadata.json
  Packs/FeedFeodoTracker/ReleaseNotes/1_0_7.md
  Packs/FeedFeodoTracker/pack_metadata.json
  Packs/FeedMajesticMillion/ReleaseNotes/1_0_4.md
  Packs/FeedMajesticMillion/pack_metadata.json
  Packs/FeedMalwareDomainList/ReleaseNotes/1_0_4.md
  Packs/FeedMalwareDomainList/pack_metadata.json
  Packs/FeedPlainText/ReleaseNotes/1_0_5.md
  Packs/FeedPlainText/pack_metadata.json
  Packs/FeedSpamhaus/ReleaseNotes/1_0_4.md
  Packs/FeedSpamhaus/pack_metadata.json
  Packs/Feedsslabusech/ReleaseNotes/1_0_8.md
  Packs/Feedsslabusech/pack_metadata.json
  Packs/ServiceNow/ReleaseNotes/2_1_11.md
  Packs/ServiceNow/pack_metadata.json
Labels: bug, docs-approved

#11214 openphish v2 - added url parameter
  Packs/OpenPhish/Integrations/OpenPhish_v2/OpenPhish_v2.py
  Packs/OpenPhish/Integrations/OpenPhish_v2/OpenPhish_v2.yml
  Packs/OpenPhish/Integrations/OpenPhish_v2/README.md
  Packs/OpenPhish/ReleaseNotes/2_0_2.md
  Packs/OpenPhish/pack_metadata.json
Labels: docs-approved

#11227 Add dashboard to Shift Management
  Packs/ShiftManagement/Dashboards/dashboard-Shift_Management_.json
  Packs/ShiftManagement/ReleaseNotes/1_2_2.md
  Packs/ShiftManagement/Scripts/GetUsersOOO/GetUsersOOO.py
  Packs/ShiftManagement/Scripts/GetUsersOnCall/GetUsersOnCall.py
  Packs/ShiftManagement/Scripts/GetUsersOnCall/GetUsersOnCall.yml
  Packs/ShiftManagement/pack_metadata.json
Labels: docs-approved

#11173 Fixing private build content installation, pack modification flag & encryption
  Tests/Marketplace/marketplace_services.py
  Tests/Marketplace/search_and_install_packs.py
  Tests/private_build/upload_packs_private.py
  Tests/scripts/prepare_private_content_packs_for_testing.sh
Labels: docs-approved

#10878 Microsoft Teams - enhancements
  Packs/MicrosoftTeams/Integrations/MicrosoftTeamsManagement/MicrosoftTeamsManagement.py
  Packs/MicrosoftTeams/Integrations/MicrosoftTeamsManagement/MicrosoftTeamsManagement.yml
  Packs/MicrosoftTeams/Integrations/MicrosoftTeamsManagement/MicrosoftTeamsManagement_description.md
  Packs/MicrosoftTeams/Integrations/MicrosoftTeamsManagement/MicrosoftTeamsManagement_image.png
  Packs/MicrosoftTeams/Integrations/MicrosoftTeamsManagement/MicrosoftTeamsManagement_test.py
  Packs/MicrosoftTeams/Integrations/MicrosoftTeamsManagement/Pipfile
  Packs/MicrosoftTeams/Integrations/MicrosoftTeamsManagement/Pipfile.lock
  Packs/MicrosoftTeams/Integrations/MicrosoftTeamsManagement/README.md
  Packs/MicrosoftTeams/Integrations/MicrosoftTeamsManagement/command_examples.txt
  Packs/MicrosoftTeams/Integrations/MicrosoftTeamsManagement/test_data/member_get.json
  Packs/MicrosoftTeams/Integrations/MicrosoftTeamsManagement/test_data/members_list.json
  Packs/MicrosoftTeams/Integrations/MicrosoftTeamsManagement/test_data/team_get.json
  Packs/MicrosoftTeams/Integrations/MicrosoftTeamsManagement/test_data/teams_list.json
  Packs/MicrosoftTeams/ReleaseNotes/1_1_0.md
  Packs/MicrosoftTeams/TestPlaybooks/Microsoft_Teams_Management_-_Test.yml
  Packs/MicrosoftTeams/pack_metadata.json
  Tests/conf.json
Labels: docs-approved

#10734 Azure SQL Management
  Packs/AzureSQLManagement/.pack-ignore
  Packs/AzureSQLManagement/.secrets-ignore
  Packs/AzureSQLManagement/Integrations/AzureSQLManagement/AzureSQLManagement.py
  Packs/AzureSQLManagement/Integrations/AzureSQLManagement/AzureSQLManagement.yml
  Packs/AzureSQLManagement/Integrations/AzureSQLManagement/AzureSQLManagement_description.md
  Packs/AzureSQLManagement/Integrations/AzureSQLManagement/AzureSQLManagement_image.png
  Packs/AzureSQLManagement/Integrations/AzureSQLManagement/AzureSQLManagement_test.py
  Packs/AzureSQLManagement/Integrations/AzureSQLManagement/Pipfile
  Packs/AzureSQLManagement/Integrations/AzureSQLManagement/Pipfile.lock
  Packs/AzureSQLManagement/Integrations/AzureSQLManagement/README.md
  Packs/AzureSQLManagement/Integrations/AzureSQLManagement/command_examples
  Packs/AzureSQLManagement/Integrations/AzureSQLManagement/test_data/azure_sql_db_audit_policy_create_update_command_result.json
  Packs/AzureSQLManagement/Integrations/AzureSQLManagement/test_data/azure_sql_db_audit_policy_list_command_result.json
  Packs/AzureSQLManagement/Integrations/AzureSQLManagement/test_data/azure_sql_db_list_command_result.json
  Packs/AzureSQLManagement/Integrations/AzureSQLManagement/test_data/azure_sql_db_threat_policy_create_update_command_result.json
  Packs/AzureSQLManagement/Integrations/AzureSQLManagement/test_data/azure_sql_db_threat_policy_get_command_result.json
  Packs/AzureSQLManagement/Integrations/AzureSQLManagement/test_data/azure_sql_servers_list_result.json
  Packs/AzureSQLManagement/TestPlaybooks/AzureSQL-Test.yml
  Packs/AzureSQLManagement/pack_metadata.json
Labels: docs-approved

#11234 Gmail: updated param display
  Packs/Gmail/Integrations/Gmail/Gmail.yml
  Packs/Gmail/Integrations/Gmail/README.md
  Packs/Gmail/ReleaseNotes/1_1_5.md
  Packs/Gmail/pack_metadata.json
Labels: bug, docs-approved, release-notes-only

#11194 Context change validate fix
  Packs/Akamai_WAF/.pack-ignore
  Packs/ArcSightESM/Integrations/ArcSightESMv2/README.md
  Packs/ArcherRSA/.pack-ignore
  Packs/AutoFocus/.pack-ignore
  Packs/Barracuda/Integrations/BarracudaReputationBlockListBRBL/README.md
  Packs/BastilleNetworks/Integrations/BastilleNetworks/README.md
  Packs/BluelivThreatContext/Integrations/BluelivThreatContext/README.md
  Packs/Code42/.pack-ignore
  Packs/CofenseTriage/.pack-ignore
  Packs/CofenseTriage/Integrations/CofenseTriagev2/README.md
  Packs/CortexDataLake/.pack-ignore
  Packs/CortexXDR/.pack-ignore
  Packs/CounterCraft/.pack-ignore
  Packs/CrowdStrikeFalcon/.pack-ignore
  Packs/CrowdStrikeIntel/Integrations/CrowdStrikeFalconIntel_v2/CrowdStrikeFalconIntel_v2.yml
  Packs/CrowdStrikeIntel/ReleaseNotes/2_0_10.md
  Packs/CrowdStrikeIntel/pack_metadata.json
  Packs/CrowdStrikeMalquery/.pack-ignore
  Packs/DNSDB/.pack-ignore
  Packs/Expanse/.pack-ignore
  Packs/FeedMitreAttack/.pack-ignore
  Packs/FireEyeETP/.pack-ignore
  Packs/Flashpoint/.pack-ignore
  Packs/GooglePubSub/.pack-ignore
  Packs/Gurucul/.pack-ignore
  Packs/Gurucul/Integrations/GuruculGRA/README.md
  Packs/Humio/.pack-ignore
  Packs/Infocyte/Integrations/Infocyte/README.md
  Packs/MicrosoftCloudAppSecurity/.pack-ignore
  Packs/MicrosoftDefenderAdvancedThreatProtection/.pack-ignore
  Packs/NozomiNetworks/.pack-ignore
  Packs/NozomiNetworks/Integrations/NozomiNetworks/README.md
  Packs/PAN-OS/.pack-ignore
  Packs/PAN-OS/Integrations/Panorama/README.md
  Packs/Polygon/Integrations/Polygon/README.md
  Packs/PrismaCloud/.pack-ignore
  Packs/ProofpointServerProtection/.pack-ignore
  Packs/RSTCloud/Integrations/RSTCloudThreatFeedAPI/README.md
  Packs/RecordedFuture/.pack-ignore
  Packs/RiskSense/.pack-ignore
  Packs/SecurityAdvisor/.pack-ignore
  Packs/SophosCentral/Integrations/SophosCentral/README.md
  Packs/Spamcop/.pack-ignore
  Packs/Tufin/Integrations/Tufin/README.md
  Packs/Uptycs/.pack-ignore
  Packs/VMware/.pack-ignore
  Packs/Whois/.pack-ignore
  Packs/XMCyber/.pack-ignore
  Packs/XMCyber/Integrations/XMCyberIntegration/README.md
  Packs/XMatters/.pack-ignore
  Packs/XMatters/Integrations/xMatters/README.md
Labels: docs-approved, release-notes-only

#11236 Add deprecated packs to IGNORED_FILES list
  Tests/Marketplace/Tests/search_and_install_packs_test.py
  Tests/Marketplace/search_and_install_packs.py
Labels: docs-approved

#11208 Cyjax feed
  Packs/FeedCyjax/.pack-ignore
  Packs/FeedCyjax/.secrets-ignore
  Packs/FeedCyjax/IndicatorFields/indicatorfield-Cyjax_Techniques_Tactics_Procedures.json
  Packs/FeedCyjax/IndicatorFields/indicatorfield-Cyjax_industry_types.json
  Packs/FeedCyjax/Integrations/FeedCyjax/FeedCyjax.py
  Packs/FeedCyjax/Integrations/FeedCyjax/FeedCyjax.yml
  Packs/FeedCyjax/Integrations/FeedCyjax/FeedCyjax_description.md
  Packs/FeedCyjax/Integrations/FeedCyjax/FeedCyjax_image.png
  Packs/FeedCyjax/Integrations/FeedCyjax/FeedCyjax_test.py
  Packs/FeedCyjax/Integrations/FeedCyjax/Pipfile
  Packs/FeedCyjax/Integrations/FeedCyjax/Pipfile.lock
  Packs/FeedCyjax/Integrations/FeedCyjax/README.md
  Packs/FeedCyjax/Integrations/FeedCyjax/command_examples
  Packs/FeedCyjax/Integrations/FeedCyjax/test_data/dummy-reposonse.json
  Packs/FeedCyjax/Integrations/FeedCyjax/test_data/enrichment.py
  Packs/FeedCyjax/Integrations/FeedCyjax/test_data/indicators.py
  Packs/FeedCyjax/README.md
  Packs/FeedCyjax/pack_metadata.json
Labels: Contribution, Partner, docs-approved

#11238 Marketplace upload - reverting updated changes
  Tests/Marketplace/marketplace_services.py
  Tests/Marketplace/upload_packs.py
Labels: docs-approved

#11231 XDR - Fixed an issue when the user is none
  Packs/CortexXDR/Integrations/CortexXDRIR/CortexXDRIR.py
  Packs/CortexXDR/Integrations/CortexXDRIR/CortexXDRIR_test.py
  Packs/CortexXDR/ReleaseNotes/2_8_3.md
  Packs/CortexXDR/pack_metadata.json
Labels: bug, docs-approved, release-notes-only

#11250 Revert "Marketplace upload - reverting updated changes"
  Tests/Marketplace/marketplace_services.py
  Tests/Marketplace/upload_packs.py
Labels: docs-approved

#11247 Mocking AWS integrations
  Tests/conf.json
Labels: docs-approved

#11226 More details about MCAS integration token
  Packs/MicrosoftCloudAppSecurity/Integrations/MicrosoftCloudAppSecurity/MicrosoftCloudAppSecurity.yml
  Packs/MicrosoftCloudAppSecurity/Integrations/MicrosoftCloudAppSecurity/README.md
  Packs/MicrosoftCloudAppSecurity/ReleaseNotes/1_0_14.md
  Packs/MicrosoftCloudAppSecurity/pack_metadata.json
Labels: docs-approved

#11255 MS Teams Management Test - increase sleep time to alone cloned team to get created
  Packs/MicrosoftTeams/TestPlaybooks/Microsoft_Teams_Management_-_Test.yml
Labels: docs-approved

#11241 Reverting unmockable integrations and adding all tests
  Tests/conf.json
Labels: docs-approved

#11242 fix validation error RM102, IN136
  Packs/AcalvioShadowplex/.pack-ignore
  Packs/BluelivThreatContext/.pack-ignore
  Packs/BluelivThreatContext/Integrations/BluelivThreatContext/README.md
  Packs/EWS/.pack-ignore
  Packs/Pcysys/.pack-ignore
  Packs/Tufin/Integrations/Tufin/README.md
  Packs/XMatters/.pack-ignore
  dev-requirements-py3.txt
Labels: docs-approved

#11258 revert sdk update
  dev-requirements-py3.txt
Labels: docs-approved

#11267 fix reference to variable name changed in 4.x
  Packs/Axonius/Integrations/Axonius/Axonius.py
  Packs/Axonius/ReleaseNotes/1_0_2.md
  Packs/Axonius/pack_metadata.json
Labels: Contribution, docs-approved

#11264 Add ref to SDK branch to fix master
  dev-requirements-py3.txt
Labels: docs-approved

#11271 add commit hash to ref sdk
  dev-requirements-py3.txt
Labels: docs-approved

#11269 Improved EDL Creation Time
  Packs/EDL/Integrations/EDL/EDL.py
  Packs/EDL/ReleaseNotes/1_0_7.md
  Packs/EDL/pack_metadata.json
Labels: docs-approved, release-notes-only

#11092 Email Communication | Changed the mandatory argument "service_mail" to optional
  Packs/EmailCommunication/ReleaseNotes/1_3_5.md
  Packs/EmailCommunication/Scripts/SendEmailReply/SendEmailReply.yml
  Packs/EmailCommunication/pack_metadata.json
Labels: docs-approved

#11195 Rapid7 Nexpose bug fix
  Packs/Rapid7_Nexpose/.secrets-ignore
  Packs/Rapid7_Nexpose/Integrations/Rapid7_Nexpose/README.md
  Packs/Rapid7_Nexpose/Integrations/Rapid7_Nexpose/Rapid7_Nexpose.py
  Packs/Rapid7_Nexpose/Integrations/Rapid7_Nexpose/Rapid7_Nexpose.yml
  Packs/Rapid7_Nexpose/Integrations/Rapid7_Nexpose/examples.txt
  Packs/Rapid7_Nexpose/Playbooks/playbook-Nexpose_-_GenericPolling_-_Create_and_Download_Report.yml
  Packs/Rapid7_Nexpose/Playbooks/playbook-Nexpose_-_GenericPolling_-_Create_and_Download_Report_README.md
  Packs/Rapid7_Nexpose/README.md
  Packs/Rapid7_Nexpose/ReleaseNotes/1_1_0.md
  Packs/Rapid7_Nexpose/TestPlaybooks/playbook-Nexpose_test.yml
  Packs/Rapid7_Nexpose/doc_files/Nexpose_-_Create_and_download_a_report.png
  Packs/Rapid7_Nexpose/doc_files/Scan_Assets_-_Nexpose.png
  Packs/Rapid7_Nexpose/doc_files/Scan_Site_-_Nexpose.png
  Packs/Rapid7_Nexpose/doc_files/Vulnerability_Handling_-_Nexpose.png
  Packs/Rapid7_Nexpose/doc_files/Vulnerability_Management_-_Nexpose.png
  Packs/Rapid7_Nexpose/pack_metadata.json
  Tests/conf.json
Labels: bug, docs-approved

#11277 XDR - Added back mirroring configuration accidentally removed
  Packs/CortexXDR/Integrations/CortexXDRIR/CortexXDRIR.yml
  Packs/CortexXDR/ReleaseNotes/2_8_4.md
  Packs/CortexXDR/pack_metadata.json
Labels: docs-approved

#11281 Made test_module dict param check safer
  Packs/APIVoid/Integrations/APIVoid/APIVoid.py
Labels: Contribution

#9731 AWS CloudWatchLogs - test fix
  Packs/AWS-CloudWatchLogs/TestPlaybooks/playbook-AWS-CloudWatchLogs_Test.yml
  Tests/conf.json
Labels: docs-approved

#11285 Carbon Black Enterprise EDR: updated argument description
  Packs/CarbonBlackEnterpriseEDR/Integrations/CarbonBlackEnterpriseEDR/CarbonBlackEnterpriseEDR.yml
  Packs/CarbonBlackEnterpriseEDR/Integrations/CarbonBlackEnterpriseEDR/README.md
  Packs/CarbonBlackEnterpriseEDR/ReleaseNotes/1_1_3.md
  Packs/CarbonBlackEnterpriseEDR/pack_metadata.json
Labels: bug, docs-approved

#11284 fixed none is not iterable error
  Packs/EWS/Integrations/EWSv2/EWSv2.py
  Packs/EWS/ReleaseNotes/1_7_4.md
  Packs/EWS/pack_metadata.json
Labels: bug, docs-approved, release-notes-only

#11283 PhishTank v2: added the use_https parameter
  Packs/PhishTank/Integrations/PhishTankV2/PhishTankV2.py
  Packs/PhishTank/Integrations/PhishTankV2/PhishTankV2.yml
  Packs/PhishTank/Integrations/PhishTankV2/PhishTankV2_test.py
  Packs/PhishTank/Integrations/PhishTankV2/README.md
  Packs/PhishTank/ReleaseNotes/2_0_5.md
  Packs/PhishTank/pack_metadata.json
Labels: bug, docs-approved

#11252 Preempt: updated docker image
  Packs/Preempt/Integrations/integration-Preempt.yml
  Packs/Preempt/ReleaseNotes/1_0_1.md
  Packs/Preempt/pack_metadata.json
Labels: bug, docs-approved

#11289 SetIfEmpty: Fix set if empty non ascii chars
  Packs/CommonScripts/ReleaseNotes/1_3_18.md
  Packs/CommonScripts/Scripts/SetIfEmpty/SetIfEmpty.py
  Packs/CommonScripts/Scripts/SetIfEmpty/SetIfEmpty.yml
  Packs/CommonScripts/TestPlaybooks/SetIfEmptyTest.yml
  Packs/CommonScripts/pack_metadata.json
Labels: bug, docs-approved

#11290 added "SetIfEmpty - non-ascii chars - Test" to conf.json
  Tests/conf.json
Labels: docs-approved

#11260 Add ignore for context mismatch
  Packs/AWS-SecurityHub/.pack-ignore
  Packs/CortexDataLake/.pack-ignore
  Packs/DeepInstinct/.pack-ignore
  Packs/MicrosoftDefenderAdvancedThreatProtection/.pack-ignore
  Packs/TaniumThreatResponse/.secrets-ignore
  Packs/Tufin/.pack-ignore
Labels: docs-approved

#11291 Added the policy_id argument to the command's args list
  Packs/qualys/Integrations/integration-qualys.yml
  Packs/qualys/ReleaseNotes/1_0_3.md
  Packs/qualys/pack_metadata.json
Labels: bug, docs-approved, release-notes-only

#10481 SailPoint IdentityIQ
  Packs/SailPointIdentityIQ/.pack-ignore
  Packs/SailPointIdentityIQ/.secrets-ignore
  Packs/SailPointIdentityIQ/Classifiers/classifier-SailPoint_IdentityIQ_Alert_Classifier.json
  Packs/SailPointIdentityIQ/Classifiers/classifier-SailPoint_IdentityIQ_Alert_Mapper.json
  Packs/SailPointIdentityIQ/IncidentFields/incidentfield-SailPoint_IdentityIQ_Alert_Display_Name.json
  Packs/SailPointIdentityIQ/IncidentFields/incidentfield-SailPoint_IdentityIQ_Alert_Target_Display_Name.json
  Packs/SailPointIdentityIQ/IncidentFields/incidentfield-SailPoint_IdentityIQ_Alert_Target_Id.json
  Packs/SailPointIdentityIQ/IncidentFields/incidentfield-SailPoint_IdentityIQ_Alert_Target_Type.json
  Packs/SailPointIdentityIQ/IncidentFields/incidentfield-SailPoint_IdentityIQ_Alert_Type.json
  Packs/SailPointIdentityIQ/IncidentTypes/incidenttype-SailPoint_IdentityIQ_Alert.json
  Packs/SailPointIdentityIQ/Integrations/SailPointIdentityIQ/Pipfile
  Packs/SailPointIdentityIQ/Integrations/SailPointIdentityIQ/Pipfile.lock
  Packs/SailPointIdentityIQ/Integrations/SailPointIdentityIQ/README.md
  Packs/SailPointIdentityIQ/Integrations/SailPointIdentityIQ/SailPointIdentityIQ.py
  Packs/SailPointIdentityIQ/Integrations/SailPointIdentityIQ/SailPointIdentityIQ.yml
  Packs/SailPointIdentityIQ/Integrations/SailPointIdentityIQ/SailPointIdentityIQ_description.md
  Packs/SailPointIdentityIQ/Integrations/SailPointIdentityIQ/SailPointIdentityIQ_image.png
  Packs/SailPointIdentityIQ/Integrations/SailPointIdentityIQ/SailPointIdentityIQ_test.py
  Packs/SailPointIdentityIQ/Integrations/SailPointIdentityIQ/command_examples
  Packs/SailPointIdentityIQ/Integrations/SailPointIdentityIQ/test_data/400_Bad_Request.json
  Packs/SailPointIdentityIQ/Integrations/SailPointIdentityIQ/test_data/404_Not_Found.json
  Packs/SailPointIdentityIQ/Integrations/SailPointIdentityIQ/test_data/405_Method_Not_Allowed.json
  Packs/SailPointIdentityIQ/Integrations/SailPointIdentityIQ/test_data/Account.json
  Packs/SailPointIdentityIQ/Integrations/SailPointIdentityIQ/test_data/Account_Disabled.json
  Packs/SailPointIdentityIQ/Integrations/SailPointIdentityIQ/test_data/Account_Filtered.json
  Packs/SailPointIdentityIQ/Integrations/SailPointIdentityIQ/test_data/Accounts.json
  Packs/SailPointIdentityIQ/Integrations/SailPointIdentityIQ/test_data/Alert.json
  Packs/SailPointIdentityIQ/Integrations/SailPointIdentityIQ/test_data/Alerts.json
  Packs/SailPointIdentityIQ/Integrations/SailPointIdentityIQ/test_data/Entitlement.json
  Packs/SailPointIdentityIQ/Integrations/SailPointIdentityIQ/test_data/Entitlements.json
  Packs/SailPointIdentityIQ/Integrations/SailPointIdentityIQ/test_data/LaunchedWorkflow.json
  Packs/SailPointIdentityIQ/Integrations/SailPointIdentityIQ/test_data/LaunchedWorkflows.json
  Packs/SailPointIdentityIQ/Integrations/SailPointIdentityIQ/test_data/NoResources.json
  Packs/SailPointIdentityIQ/Integrations/SailPointIdentityIQ/test_data/PolicyViolation.json
  Packs/SailPointIdentityIQ/Integrations/SailPointIdentityIQ/test_data/PolicyViolations.json
  Packs/SailPointIdentityIQ/Integrations/SailPointIdentityIQ/test_data/ResourceTypes.json
  Packs/SailPointIdentityIQ/Integrations/SailPointIdentityIQ/test_data/Role.json
  Packs/SailPointIdentityIQ/Integrations/SailPointIdentityIQ/test_data/Roles.json
  Packs/SailPointIdentityIQ/Integrations/SailPointIdentityIQ/test_data/Schemas.json
  Packs/SailPointIdentityIQ/Integrations/SailPointIdentityIQ/test_data/ServiceProviderConfig.json
  Packs/SailPointIdentityIQ/Integrations/SailPointIdentityIQ/test_data/TaskResult.json
  Packs/SailPointIdentityIQ/Integrations/SailPointIdentityIQ/test_data/TaskResults.json
  Packs/SailPointIdentityIQ/Integrations/SailPointIdentityIQ/test_data/User.json
  Packs/SailPointIdentityIQ/Integrations/SailPointIdentityIQ/test_data/User_Filtered.json
  Packs/SailPointIdentityIQ/Integrations/SailPointIdentityIQ/test_data/Users.json
  Packs/SailPointIdentityIQ/Layouts/layoutscontainer-SailPoint_IdentityIQ_Alert.json
  Packs/SailPointIdentityIQ/Playbooks/SailPoint_IdentityIQ_Disable_User_Account_Access.png
  Packs/SailPointIdentityIQ/Playbooks/SailPoint_IdentityIQ_Disable_User_Account_Access.yml
  Packs/SailPointIdentityIQ/Playbooks/SailPoint_IdentityIQ_Disable_User_Account_Access_README.md
  Packs/SailPointIdentityIQ/README.md
  Packs/SailPointIdentityIQ/TestPlaybooks/SailPointIdentityIQ-Test.yml
  Packs/SailPointIdentityIQ/doc_files/High_Risk_User.png
  Packs/SailPointIdentityIQ/doc_files/IdentityIQ_Accounts_Active.png
  Packs/SailPointIdentityIQ/doc_files/IdentityIQ_Accounts_Inactive.png
  Packs/SailPointIdentityIQ/doc_files/IdentityIQ_Provisioning_Success.png
  Packs/SailPointIdentityIQ/doc_files/SailPoint_IdentityIQ_Disable_User_Account_Access.png
  Packs/SailPointIdentityIQ/pack_metadata.json
Labels: Contribution, Partner, post-demo

#10786 Nutanix hypervisor integration
  Packs/CommonTypes/IncidentFields/incidentfield-Last_Seen.json
  Packs/CommonTypes/IncidentFields/incidentfield-Ticket_Acknowledged_Date.json
  Packs/CommonTypes/ReleaseNotes/2_8_2.md
  Packs/CommonTypes/pack_metadata.json
  Packs/NutanixHypervisor/.pack-ignore
  Packs/NutanixHypervisor/.secrets-ignore
  Packs/NutanixHypervisor/Classifiers/classifier-Nutanix_Hypervisor_5_9_9.json
  Packs/NutanixHypervisor/Classifiers/classifier-mapper-incoming-Nutanix_Hypervisor.json
  Packs/NutanixHypervisor/IncidentFields/incidentfield-Acknowledged.json
  Packs/NutanixHypervisor/IncidentFields/incidentfield-Acknowledged_By_Username.json
  Packs/NutanixHypervisor/IncidentFields/incidentfield-Alert_Closing_User.json
  Packs/NutanixHypervisor/IncidentFields/incidentfield-Alert_Type_UUID.json
  Packs/NutanixHypervisor/IncidentFields/incidentfield-Check_ID.json
  Packs/NutanixHypervisor/IncidentFields/incidentfield-Classifications.json
  Packs/NutanixHypervisor/IncidentFields/incidentfield-Cluster_UUID.json
  Packs/NutanixHypervisor/IncidentFields/incidentfield-Message.json
  Packs/NutanixHypervisor/IncidentFields/incidentfield-Operation_Type.json
  Packs/NutanixHypervisor/IncidentFields/incidentfield-Resolved.json
  Packs/NutanixHypervisor/IncidentTypes/Nutanix_Hypervisor_Alert.json
  Packs/NutanixHypervisor/Integrations/NutanixHypervisor/NutanixHypervisor.py
  Packs/NutanixHypervisor/Integrations/NutanixHypervisor/NutanixHypervisor.yml
  Packs/NutanixHypervisor/Integrations/NutanixHypervisor/NutanixHypervisor_description.md
  Packs/NutanixHypervisor/Integrations/NutanixHypervisor/NutanixHypervisor_image.png
  Packs/NutanixHypervisor/Integrations/NutanixHypervisor/NutanixHypervisor_test.py
  Packs/NutanixHypervisor/Integrations/NutanixHypervisor/Pipfile
  Packs/NutanixHypervisor/Integrations/NutanixHypervisor/Pipfile.lock
  Packs/NutanixHypervisor/Integrations/NutanixHypervisor/README.md
  Packs/NutanixHypervisor/Integrations/NutanixHypervisor/test_data/test_command_data.json
  Packs/NutanixHypervisor/Layouts/layout-details-Nutanix_Hypervisor_Alert.json
  Packs/NutanixHypervisor/Layouts/layoutscontainer-Nutanix_Hypervisor_Alert.json
  Packs/NutanixHypervisor/Playbooks/Nutanix_Change_Virtual_Machine_Power_State.yml
  Packs/NutanixHypervisor/TestPlaybooks/Nutanix-test.yml
  Packs/NutanixHypervisor/commands_example.txt
  Packs/NutanixHypervisor/doc_files/Alert Policy.png
  Packs/NutanixHypervisor/pack_metadata.json
  Tests/conf.json
Labels: docs-approved

#11294 fixed author field in pack_metadata.json
  Packs/FeedCyjax/pack_metadata.json
Labels: Contribution, Partner, docs-approved

#11296 timeout fix
  Tests/conf.json
Labels: docs-approved

#11168 Add automation board for project "Contribution Reviews"
  .github/project_conf/contributions.ini
  .github/workflows/project_manager.yml
  .github/workflows/project_manager_daily.yml
  .github/workflows/project_manager_hourly.yml
Labels: docs-approved

#11111 Tidy review
  Packs/Tidy/.pack-ignore
  Packs/Tidy/.secrets-ignore
  Packs/Tidy/IncidentFields/incidentfield-GitHubToken.json
  Packs/Tidy/IncidentFields/incidentfield-TidyHost.json
  Packs/Tidy/IncidentFields/incidentfield-TidyPassword.json
  Packs/Tidy/IncidentFields/incidentfield-TidyUser.json
  Packs/Tidy/IncidentTypes/incidenttype-Tidy_install.json
  Packs/Tidy/Integrations/Tidy/Pipfile
  Packs/Tidy/Integrations/Tidy/Pipfile.lock
  Packs/Tidy/Integrations/Tidy/README.md
  Packs/Tidy/Integrations/Tidy/Tidy.py
  Packs/Tidy/Integrations/Tidy/Tidy.yml
  Packs/Tidy/Integrations/Tidy/Tidy_description.md
  Packs/Tidy/Integrations/Tidy/Tidy_image.png
  Packs/Tidy/Playbooks/playbook-Content_developer_setup.yml
  Packs/Tidy/Playbooks/playbook-Tidy_install_content.yml
  Packs/Tidy/README.md
  Packs/Tidy/layoutscontainer/layoutscontainer-Tidy.json
  Packs/Tidy/pack_metadata.json
Labels: docs-approved

#11149 Implementing the lab lockdown
  .circleci/config.yml
  Tests/Common/__init__.py
  Tests/Marketplace/configure_and_install_packs.py
  Tests/configure_and_test_integration_instances.py
  Tests/instance_notifier.py
  Tests/private_build/tests/test_configure_and_test_integration_instances_private.py
  Tests/scripts/validate_premium_packs.py
  Tests/scripts/wait_until_server_ready.py
  Tests/secrets_white_list.json
  Tests/test_content.py
  Tests/tools.py
Labels: docs-approved

#11301 Increased phishing tests pid threshold to 80
  Tests/conf.json
Labels: docs-approved

#11300 context validation fix - added pack ignore
  Packs/TaniumThreatResponse/.pack-ignore
  Packs/XMatters/.pack-ignore
Labels: docs-approved

#11292 Microsoft Teams Management Test - increase team creation sleep time to 30
  Packs/MicrosoftTeams/TestPlaybooks/Microsoft_Teams_Management_-_Test.yml
  Tests/conf.json
Labels: docs-approved

#11303 Fixing an issue with private build
  Tests/instance_notifier.py
  Tests/private_build/run_content_tests_private.py
  Tests/test_content.py
  Tests/test_integration.py
Labels: docs-approved

#11309 Fixing outgoing xdr mapper
  Packs/CortexXDR/Classifiers/classifier-mapper-outgoing-PaloAltoNetworks_CortexXDR.json
  Packs/CortexXDR/ReleaseNotes/2_8_5.md
  Packs/CortexXDR/pack_metadata.json
Labels: docs-approved, release-notes-only

#11310 Creating tunnel in Pack upload job
  .circleci/config.yml
Labels: docs-approved

#11312 [Contribution Automation] Change Token Used to Update Board
  .github/workflows/project_manager.yml
  .github/workflows/project_manager_daily.yml
  .github/workflows/project_manager_hourly.yml
Labels: docs-approved

#11293 Create 4 processes instead of cpu_count number
  Tests/scripts/update_conf_json.py
Labels: docs-approved

#11313 Making Upload Packs To Marketplace job aware that the instance was created
  .circleci/config.yml
Labels: docs-approved

#11297 SymantecATP-FetchIncidentFix
  Packs/Symantec_Advanced_Threat_Protection/Integrations/integration-Symantec_Advanced_Threat_Protection.yml
  Packs/Symantec_Advanced_Threat_Protection/ReleaseNotes/1_1_2.md
  Packs/Symantec_Advanced_Threat_Protection/pack_metadata.json
Labels: bug, docs-approved, release-notes-only

#11316 [Project Manager] Add names to the project manager workflows
  .github/workflows/project_manager.yml
  .github/workflows/project_manager_daily.yml
  .github/workflows/project_manager_hourly.yml
Labels: docs-approved

#11010 DbotPredictPhishingWords improvements
  Packs/Base/ReleaseNotes/1_7_10.md
  Packs/Base/Scripts/DBotPredictPhishingWords/DBotPredictPhishingWords.py
  Packs/Base/Scripts/DBotPredictPhishingWords/DBotPredictPhishingWords.yml
  Packs/Base/Scripts/DBotPredictPhishingWords/dbot_predict_phishing_words_test.py
  Packs/Base/pack_metadata.json
Labels: docs-approved

#11307 Readmes fixes amp
  Packs/AWS-EC2/Integrations/AWS-EC2/README.md
  Packs/AlphaSOC_Network_Behavior_Analytics/Integrations/integration-AlphaSOC_Network_Behavior_Analytics_README.md
  Packs/Box/Integrations/BoxV2/README.md
  Packs/CrowdStrikeFalcon/Integrations/CrowdStrikeFalcon/README.md
  Packs/FeedIntel471/Integrations/Intel471Actors/README.md
  Packs/FeedIntel471/Integrations/Intel471Malware/README.md
  Packs/Graylog/Integrations/Graylog/README.md
  Packs/Lacework/Integrations/Lacework/README.md
  Packs/Orca/Integrations/Orca/README.md
  Packs/Rapid7_InsightIDR/Integrations/Rapid7_InsightIDR/README.md
  Packs/Salesforce/Integrations/Salesforce/integration-Salesforce_README.md
  Packs/Salesforce/Integrations/Salesforce_IAM/README.md
  Packs/SentinelOne/Integrations/SentinelOne-V2/README.md
  Packs/ServiceNow/Integrations/ServiceNow/README.md
  Packs/ServiceNow/Integrations/ServiceNow_IAM/README.md
  Packs/ServiceNow/Integrations/ServiceNowv2/README.md
  Packs/ServiceNow/Integrations/ServiceNowv2/ServiceNowv2.yml
  Packs/ServiceNow/ReleaseNotes/2_1_12.md
  Packs/ServiceNow/pack_metadata.json
  Packs/XMatters/Integrations/xMatters/README.md
  Packs/iDefense/Integrations/FeediDefense/README.md
Labels: docs-approved

#11324 [Project Manager] Removed event listener
  .github/workflows/project_manager.yml
Labels: docs-approved

#11323 Tenable.io TPBs update
  Packs/Tenable_io/TestPlaybooks/playbook-Tenable.io_Scan_Test.yml
  Packs/Tenable_io/TestPlaybooks/playbook-Tenable.io_test.yml
  Tests/conf.json
Labels: docs-approved

#11308 Added a function to filter the installed packs in nightly and in a build
  Tests/Marketplace/marketplace_services.py
  Tests/scripts/collect_tests_and_content_packs.py
  Tests/scripts/infrastructure_tests/test_collect_tests_and_content_packs.py
  Tests/scripts/utils/content_packs_util.py
  Tests/scripts/utils/tests/content_packs_util_test.py
Labels: docs-approved

#11320 Cyren ThreatInDepth Base Content Pack v1.3.1
  Packs/FeedCyrenThreatInDepth/ReleaseNotes/1_3_1.md
  Packs/FeedCyrenThreatInDepth/pack_metadata.json
Labels: Contribution, docs-approved

#11302 Upload flow - fixing created time change
  Tests/Marketplace/Tests/marketplace_services_test.py
  Tests/Marketplace/marketplace_services.py
Labels: docs-approved

#10729 Maintain "New" tag in packs
  Tests/Marketplace/Tests/marketplace_services_test.py
  Tests/Marketplace/approved_tags.json
  Tests/Marketplace/marketplace_services.py
Labels: docs-approved

#11325 ignore RM102
  Packs/Cymptom/.pack-ignore
Labels: docs-approved

#11007 [greynoise-266] GreyNoise Integration
  Packs/GreyNoise/.pack-ignore
  Packs/GreyNoise/.secrets-ignore
  Packs/GreyNoise/Integrations/GreyNoise/GreyNoise.py
  Packs/GreyNoise/Integrations/GreyNoise/GreyNoise.yml
  Packs/GreyNoise/Integrations/GreyNoise/GreyNoise_description.md
  Packs/GreyNoise/Integrations/GreyNoise/GreyNoise_image.png
  Packs/GreyNoise/Integrations/GreyNoise/GreyNoise_test.py
  Packs/GreyNoise/Integrations/GreyNoise/Pipfile
  Packs/GreyNoise/Integrations/GreyNoise/Pipfile.lock
  Packs/GreyNoise/Integrations/GreyNoise/README.md
  Packs/GreyNoise/Integrations/GreyNoise/test_data/input_data.py
  Packs/GreyNoise/Integrations/GreyNoise/test_data/quick_check.md
  Packs/GreyNoise/Playbooks/Calculate_Severity_-_GreyNoise.yml
  Packs/GreyNoise/Playbooks/Calculate_Severity_-_GreyNoise_README.md
  Packs/GreyNoise/Playbooks/Calculate_Severity_Highest_DBotScore_For_Egress_Network_Traffic_-_GreyNoise.yml
  Packs/GreyNoise/Playbooks/Calculate_Severity_Highest_DBotScore_For_Egress_Network_Traffic_-_GreyNoise_README.md
  Packs/GreyNoise/Playbooks/Calculate_Severity_Highest_DBotScore_For_Ingress_Network_Traffic_-_GreyNoise.yml
  Packs/GreyNoise/Playbooks/Calculate_Severity_Highest_DBotScore_For_Ingress_Network_Traffic_-_GreyNoise_README.md
  Packs/GreyNoise/Playbooks/IP_Reputation-GreyNoise.yml
  Packs/GreyNoise/Playbooks/IP_Reputation-GreyNoise_README.md
  Packs/GreyNoise/README.md
  Packs/GreyNoise/TestPlaybooks/playbook-GreyNoise-test.yml
  Packs/GreyNoise/doc_files/Calculate_Severity_-_GreyNoise.png
  Packs/GreyNoise/doc_files/Calculate_Severity_For_Egress_Network_Request_By_Highest_DBotScore_-_GreyNoise.png
  Packs/GreyNoise/doc_files/Calculate_Severity_For_Ingress_Network_Request_By_Highest_DBotScore_-_GreyNoise.png
  Packs/GreyNoise/doc_files/Calculate_Severity_Highest_DBotScore_For_Egress_Network_Traffic_-_GreyNoise.png
  Packs/GreyNoise/doc_files/Calculate_Severity_Highest_DBotScore_For_Ingress_Network_Traffic_-_GreyNoise.png
  Packs/GreyNoise/doc_files/IP_Reputation-GreyNoise.png
  Packs/GreyNoise/pack_metadata.json
  Tests/conf.json
Labels: Contribution

#11318 demisto-sdk==1.2.19
  dev-requirements-py3.txt
Labels: docs-approved

#10760 Gh integ
  Packs/GreatHorn/.pack-ignore
  Packs/GreatHorn/.secrets-ignore
  Packs/GreatHorn/IncidentTypes/incidenttype-GreatHorn_Phishing.json
  Packs/GreatHorn/Integrations/GreatHorn/GreatHorn.py
  Packs/GreatHorn/Integrations/GreatHorn/GreatHorn.yml
  Packs/GreatHorn/Integrations/GreatHorn/GreatHorn_image.png
  Packs/GreatHorn/Integrations/GreatHorn/GreatHorn_test.py
  Packs/GreatHorn/Integrations/GreatHorn/Pipfile
  Packs/GreatHorn/Integrations/GreatHorn/Pipfile.lock
  Packs/GreatHorn/Integrations/GreatHorn/README.md
  Packs/GreatHorn/Integrations/GreatHorn/command_examples.txt
  Packs/GreatHorn/Integrations/GreatHorn/test_data/message.json
  Packs/GreatHorn/Integrations/GreatHorn/test_data/phish_response.json
  Packs/GreatHorn/Integrations/GreatHorn/test_data/policy.json
  Packs/GreatHorn/Integrations/GreatHorn/test_data/release_response.json
  Packs/GreatHorn/Integrations/GreatHorn/test_data/remediate_alreadydone.json
  Packs/GreatHorn/Integrations/GreatHorn/test_data/remediate_success.json
  Packs/GreatHorn/Integrations/GreatHorn/test_data/revert_success.json
  Packs/GreatHorn/Integrations/GreatHorn/test_data/set_policy_success.json
  Packs/GreatHorn/README.md
  Packs/GreatHorn/TestPlaybooks/TestGreatHornPlaybook.yml
  Packs/GreatHorn/pack_metadata.json
Labels: Contribution, Partner, docs-approved

#10948 Add Is_Successful_Build job to config.yml
  .circleci/config.yml
Labels: docs-approved

#10949 update merge_content_new_zip.py
  .circleci/config.yml
  Utils/merge_content_new_zip.py
Labels: docs-approved

#11332 skipped taxii until next sdk release
  Tests/conf.json
Labels: docs-approved

#11337 increased tenable.io scan test timeout
  Tests/conf.json
Labels: docs-approved

#11314 fixed tabletomarkdown in powershell
  Packs/Base/ReleaseNotes/1_7_11.md
  Packs/Base/Scripts/CommonServerPowerShell/CommonServerPowerShell.Tests.ps1
  Packs/Base/Scripts/CommonServerPowerShell/CommonServerPowerShell.ps1
  Packs/Base/Scripts/CommonServerPowerShell/CommonServerPowerShell.yml
  Packs/Base/pack_metadata.json
Labels: docs-approved, release-notes-only

#11345 [Project Manager] Limit workflow execution to demisto/content
  .github/workflows/check-contributor-pack.yml
  .github/workflows/project_manager_daily.yml
  .github/workflows/project_manager_hourly.yml
Labels: docs-approved

#11341 cymptom: remove developer details from support/publisher. Fix README formatting
  Packs/Arduino/Integrations/Arduino/Arduino_description.md
  Packs/Arduino/ReleaseNotes/1_0_1.md
  Packs/Arduino/pack_metadata.json
  Packs/Cymptom/Integrations/Cymptom/Cymptom_description.md
  Packs/Cymptom/Integrations/Cymptom/README.md
  Packs/Cymptom/ReleaseNotes/1_0_1.md
  Packs/Cymptom/pack_metadata.json
  Packs/RSTCloud/Integrations/RSTCloudThreatFeedAPI/RSTCloudThreatFeedAPI_description.md
  Packs/RSTCloud/ReleaseNotes/1_0_1.md
  Packs/RSTCloud/pack_metadata.json
Labels: docs-approved

#11344 fix validate.sh for contributions
  Tests/scripts/validate.sh
Labels: docs-approved

#11352 Change ML fetch data to run once
  Packs/Base/ReleaseNotes/1_7_12.md
  Packs/Base/Scripts/DBotMLFetchData/DBotMLFetchData.yml
  Packs/Base/pack_metadata.json
Labels: docs-approved

#11101 fixing GetIndicatorDBotScore script
  Packs/CommonScripts/ReleaseNotes/1_3_19.md
  Packs/CommonScripts/Scripts/GetIndicatorDBotScore/GetIndicatorDBotScore.py
  Packs/CommonScripts/pack_metadata.json
  Packs/Pwned/TestPlaybooks/playbook-EmailReputationTest.yml
Labels: bug, docs-approved, release-notes-only

#11343 GreyNoise ignore IN136
  Packs/GreyNoise/.pack-ignore
Labels: docs-approved

#11333 EWS0365 Fix: Avoid HTML template formatting if HTML body is not used
  Packs/EWS/Integrations/EWSO365/EWSO365.py
  Packs/EWS/Integrations/EWSO365/EWSO365.yml
  Packs/EWS/ReleaseNotes/1_7_5.md
  Packs/EWS/pack_metadata.json
Labels: docs-approved, release-notes-only

#11311 Pcap bug
  Packs/PcapAnalysis/Playbooks/playbook-PCAP_Parsing_And_Indicator_Enrichment.yml
  Packs/PcapAnalysis/ReleaseNotes/2_3_8.md
  Packs/PcapAnalysis/pack_metadata.json
Labels: docs-approved

#11299 Don't search for server integrations in id_set
  Tests/scripts/collect_tests_and_content_packs.py
Labels: docs-approved

#9960 adding DHS feed
  Packs/FeedDHS/.pack-ignore
  Packs/FeedDHS/.secrets-ignore
  Packs/FeedDHS/Integrations/DHS_Feed/DHS_Feed.png
  Packs/FeedDHS/Integrations/DHS_Feed/DHS_Feed.py
  Packs/FeedDHS/Integrations/DHS_Feed/DHS_Feed.yml
  Packs/FeedDHS/Integrations/DHS_Feed/DHS_Feed_description.md
  Packs/FeedDHS/Integrations/DHS_Feed/DHS_Feed_test.py
  Packs/FeedDHS/Integrations/DHS_Feed/README.md
  Packs/FeedDHS/Integrations/DHS_Feed/test_data/blocks/blocks_from_Domain_data.json
  Packs/FeedDHS/Integrations/DHS_Feed/test_data/blocks/blocks_from_Email_data.json
  Packs/FeedDHS/Integrations/DHS_Feed/test_data/blocks/blocks_from_File_data.json
  Packs/FeedDHS/Integrations/DHS_Feed/test_data/blocks/blocks_from_IP_data.json
  Packs/FeedDHS/Integrations/DHS_Feed/test_data/blocks/blocks_from_URL_data.json
  Packs/FeedDHS/Integrations/DHS_Feed/test_data/context_indicators/context_from_Domain_data.json
  Packs/FeedDHS/Integrations/DHS_Feed/test_data/context_indicators/context_from_Email_data.json
  Packs/FeedDHS/Integrations/DHS_Feed/test_data/context_indicators/context_from_File_data.json
  Packs/FeedDHS/Integrations/DHS_Feed/test_data/context_indicators/context_from_IP_data.json
  Packs/FeedDHS/Integrations/DHS_Feed/test_data/context_indicators/context_from_URL_data.json
  Packs/FeedDHS/Integrations/DHS_Feed/test_data/data_from_DHS/Domain_data.json
  Packs/FeedDHS/Integrations/DHS_Feed/test_data/data_from_DHS/Email_data.json
  Packs/FeedDHS/Integrations/DHS_Feed/test_data/data_from_DHS/File_data.json
  Packs/FeedDHS/Integrations/DHS_Feed/test_data/data_from_DHS/IP_data.json
  Packs/FeedDHS/Integrations/DHS_Feed/test_data/data_from_DHS/URL_data.json
  Packs/FeedDHS/Integrations/DHS_Feed/test_data/data_indicators/Domain_data_indicators.json
  Packs/FeedDHS/Integrations/DHS_Feed/test_data/data_indicators/Email_data_indicators.json
  Packs/FeedDHS/Integrations/DHS_Feed/test_data/data_indicators/File_data_indicators.json
  Packs/FeedDHS/Integrations/DHS_Feed/test_data/data_indicators/IP_data_indicators.json
  Packs/FeedDHS/Integrations/DHS_Feed/test_data/data_indicators/URL_data_indicators.json
  Packs/FeedDHS/Integrations/DHS_Feed/test_data/indicators/indicators_from_Domain_data.json
  Packs/FeedDHS/Integrations/DHS_Feed/test_data/indicators/indicators_from_Email_data.json
  Packs/FeedDHS/Integrations/DHS_Feed/test_data/indicators/indicators_from_File_data.json
  Packs/FeedDHS/Integrations/DHS_Feed/test_data/indicators/indicators_from_IP_data.json
  Packs/FeedDHS/Integrations/DHS_Feed/test_data/indicators/indicators_from_URL_data.json
  Packs/FeedDHS/Integrations/DHS_Feed/test_data/rsa/2048b-rsa-example-cert.pem
  Packs/FeedDHS/Integrations/DHS_Feed/test_data/rsa/2048b-rsa-example-keypair.pem
  Packs/FeedDHS/Integrations/DHS_Feed/test_data/rsa/test_fix_rsa_data.txt
  Packs/FeedDHS/Integrations/DHS_Feed/test_data/rsa/test_fix_rsa_data2.txt
  Packs/FeedDHS/README.md
  Packs/FeedDHS/pack_metadata.json
Labels: docs-approved

#11356 EWS v2: improved error message
  Packs/EWS/Integrations/EWSv2/EWSv2.py
  Packs/EWS/ReleaseNotes/1_7_6.md
  Packs/EWS/pack_metadata.json
Labels: bug, docs-approved

#11330 CommonTypes - Improved optional dependencies.
  Packs/CommonTypes/ReleaseNotes/2_8_3.md
  Packs/CommonTypes/pack_metadata.json
Labels: docs-approved, release-notes-only

#11362 box: fix broken links
  Packs/Box/Integrations/BoxV2/README.md
Labels: docs-approved

#11350 Rasterize-PDF-Bug-Fix
  Packs/rasterize/Integrations/rasterize/rasterize.py
  Packs/rasterize/Integrations/rasterize/rasterize.yml
  Packs/rasterize/ReleaseNotes/1_0_7.md
  Packs/rasterize/pack_metadata.json
Labels: bug, docs-approved, release-notes-only

#11367 Orca integration text edits
  Packs/Orca/README.md
  Packs/Orca/ReleaseNotes/1_0_3.md
  Packs/Orca/pack_metadata.json
Labels: Contribution, docs-approved

#11370 [PAN PS TEAM]Adding hpsm-update-incident and resource endpoint naming.
  Packs/HPE_Service_Manager/Integrations/integration-HPE_Service_Manager.yml
  Packs/HPE_Service_Manager/ReleaseNotes/1_0_3.md
  Packs/HPE_Service_Manager/pack_metadata.json
Labels: docs-approved

#11376 Ignoring docker image validation in 5.5 and 5.0
  Tests/configure_and_test_integration_instances.py
Labels: docs-approved

#11287 Docs How to - improve entry tags dos
  Documentation/doc-howto.json
Labels: docs-approved

#11374 Arduino: update pack description
  Packs/Arduino/pack_metadata.json
Labels: docs-approved

#11305 Smbv2
  Packs/SMB/.pack-ignore
  Packs/SMB/Integrations/SMB/SMB.yml
  Packs/SMB/Integrations/SMB_v2/README.md
  Packs/SMB/Integrations/SMB_v2/SMB_v2.py
  Packs/SMB/Integrations/SMB_v2/SMB_v2.yml
  Packs/SMB/Integrations/SMB_v2/SMB_v2_description.md
  Packs/SMB/Integrations/SMB_v2/SMB_v2_image.png
  Packs/SMB/Integrations/SMB_v2/examples.txt
  Packs/SMB/ReleaseNotes/2_0_0.md
  Packs/SMB/TestPlaybooks/playbook-SMB_v2-test.yml
  Packs/SMB/pack_metadata.json
  Tests/conf.json
Labels: docs-approved

#11355 SecurityAndCompliance: fixed generic polling DT value
  Packs/EWS/Playbooks/playbook-O365-SecurityAndCompliance-Search.yml
  Packs/EWS/Playbooks/playbook-O365-SecurityAndCompliance-SearchAction-Delete.yml
  Packs/EWS/Playbooks/playbook-O365-SecurityAndCompliance-SearchAction-Preview.yml
  Packs/EWS/ReleaseNotes/1_7_7.md
  Packs/EWS/pack_metadata.json
Labels: bug, docs-approved, release-notes-only

#11019 Service desk plus on premise
  Packs/ServiceDeskPlus_On_Premise/.pack-ignore
  Packs/ServiceDeskPlus_On_Premise/.secrets-ignore
  Packs/ServiceDeskPlus_On_Premise/Integrations/ServiceDeskPlus_On_Premise/README.md
  Packs/ServiceDeskPlus_On_Premise/Integrations/ServiceDeskPlus_On_Premise/ServiceDeskPlus_On_Premise.py
  Packs/ServiceDeskPlus_On_Premise/Integrations/ServiceDeskPlus_On_Premise/ServiceDeskPlus_On_Premise.yml
  Packs/ServiceDeskPlus_On_Premise/Integrations/ServiceDeskPlus_On_Premise/ServiceDeskPlus_On_Premise_description.md
  Packs/ServiceDeskPlus_On_Premise/Integrations/ServiceDeskPlus_On_Premise/ServiceDeskPlus_On_Premise_image.png
  Packs/ServiceDeskPlus_On_Premise/Integrations/ServiceDeskPlus_On_Premise/ServiceDeskPlus_On_Premise_test.py
  Packs/ServiceDeskPlus_On_Premise/Integrations/ServiceDeskPlus_On_Premise/command_examples.txt
  Packs/ServiceDeskPlus_On_Premise/Integrations/ServiceDeskPlus_On_Premise/test_data/response_constants.py
  Packs/ServiceDeskPlus_On_Premise/Integrations/ServiceDeskPlus_On_Premise/test_data/result_constants.py
  Packs/ServiceDeskPlus_On_Premise/README.md
  Packs/ServiceDeskPlus_On_Premise/TestPlaybooks/playbook-Service_Desk_Plus_On_Premise.yml
  Packs/ServiceDeskPlus_On_Premise/pack_metadata.json
  Tests/conf.json
Labels: Contribution, docs-approved, ready-for-instance-test

#11354 GetFailedTasks: added the max_incidents argument
  Packs/IntegrationsAndIncidentsHealthCheck/ReleaseNotes/1_1_12.md
  Packs/IntegrationsAndIncidentsHealthCheck/Scripts/GetFailedTasks/GetFailedTasks.py
  Packs/IntegrationsAndIncidentsHealthCheck/Scripts/GetFailedTasks/GetFailedTasks.yml
  Packs/IntegrationsAndIncidentsHealthCheck/pack_metadata.json
Labels: bug, docs-approved

#11363 Fix for removing metadata versions
  Tests/Marketplace/upload_packs.py
Labels: docs-approved

#11379 updated documentation and description
  Packs/AzureSQLManagement/Integrations/AzureSQLManagement/AzureSQLManagement.yml
  Packs/AzureSQLManagement/Integrations/AzureSQLManagement/README.md
  Packs/AzureSQLManagement/ReleaseNotes/1_0_1.md
  Packs/AzureSQLManagement/pack_metadata.json
Labels: docs-approved, release-notes-only

#11361 Zscaler - Added timeout to the http request
  Packs/Zscaler/Integrations/Zscaler/Zscaler.py
  Packs/Zscaler/ReleaseNotes/1_1_2.md
  Packs/Zscaler/pack_metadata.json
Labels: bug, docs-approved, release-notes-only

#11353 fixing the DT
  Packs/EWS/Integrations/EWSO365/EWSO365.py
  Packs/EWS/ReleaseNotes/1_7_8.md
  Packs/EWS/pack_metadata.json
Labels: bug, docs-approved, release-notes-only

#11270 adding limit argument to `cb-list-sensors` command
  Packs/Carbon_Black_Enterprise_Response/Integrations/integration-Carbon_Black_Enterprise_Response.yml
  Packs/Carbon_Black_Enterprise_Response/ReleaseNotes/1_1_4.md
  Packs/Carbon_Black_Enterprise_Response/pack_metadata.json
Labels: bug, docs-approved

#11360 Slack v2 Improved argument description
  Packs/Slack/Integrations/Slack/README.md
  Packs/Slack/Integrations/Slack/Slack.py
  Packs/Slack/Integrations/Slack/Slack.yml
  Packs/Slack/Integrations/Slack/Slack_test.py
  Packs/Slack/ReleaseNotes/1_3_14.md
  Packs/Slack/pack_metadata.json
Labels: bug, docs-approved, release-notes-only

#11373 Cyberint: Fixed issue with '<' operator
  Packs/Cyberint/Integrations/Cyberint/Cyberint.py
  Packs/Cyberint/ReleaseNotes/1_0_2.md
  Packs/Cyberint/pack_metadata.json
Labels: Contribution, docs-approved

#11389 Zendesk Leftovers
  Packs/AMP/Integrations/integration-AMP_README.md
  Packs/Gmail/Integrations/Gmail/README.md
Labels: docs-approved

#11378 safebreach readme: fix broken link
  Packs/SafeBreach/Integrations/SafeBreach_v2/README.md
Labels: docs-approved

#11397 EDL: fixed out of memory error
  Packs/EDL/Integrations/EDL/EDL.py
  Packs/EDL/Integrations/EDL/EDL.yml
  Packs/EDL/ReleaseNotes/1_0_8.md
  Packs/EDL/pack_metadata.json
Labels: bug, docs-approved

#11349 Workday IAM fetch fix
  Packs/Workday/Integrations/Workday_IAM/Workday_IAM.py
  Packs/Workday/Integrations/Workday_IAM/Workday_IAM_test.py
  Packs/Workday/Integrations/Workday_IAM/test_data/event_results.py
  Packs/Workday/ReleaseNotes/1_0_9.md
  Packs/Workday/pack_metadata.json
Labels: docs-approved, release-notes-only

#11398 Common: mask basic auth
  Packs/Base/ReleaseNotes/1_7_13.md
  Packs/Base/Scripts/CommonServerPython/CommonServerPython.py
  Packs/Base/Scripts/CommonServerPython/CommonServerPython_test.py
  Packs/Base/pack_metadata.json
Labels: docs-approved

#11366 Contribution of Additional KennaV2 Command
  Packs/Kenna/Integrations/KennaV2/KennaV2.py
  Packs/Kenna/Integrations/KennaV2/KennaV2.yml
  Packs/Kenna/Integrations/KennaV2/KennaV2_test.py
  Packs/Kenna/Integrations/KennaV2/README.md
  Packs/Kenna/Integrations/KennaV2/Tests_Data/ExpectedResult.py
  Packs/Kenna/Integrations/KennaV2/Tests_Data/RawData.py
  Packs/Kenna/Integrations/KennaV2/command_examples.txt
  Packs/Kenna/ReleaseNotes/1_1_0.md
  Packs/Kenna/TestPlaybooks/playbook-Kenna_Test.yml
  Packs/Kenna/pack_metadata.json
  Tests/conf.json
Labels: Contribution, docs-approved, ready-for-instance-test

#11080 Audit Log
  Packs/Office365AndAzureAuditLog/.pack-ignore
  Packs/Office365AndAzureAuditLog/.secrets-ignore
  Packs/Office365AndAzureAuditLog/Integrations/MicrosoftPolicyAndComplianceAuditLog/MicrosoftPolicyAndComplianceAuditLog.Tests.ps1
  Packs/Office365AndAzureAuditLog/Integrations/MicrosoftPolicyAndComplianceAuditLog/MicrosoftPolicyAndComplianceAuditLog.ps1
  Packs/Office365AndAzureAuditLog/Integrations/MicrosoftPolicyAndComplianceAuditLog/MicrosoftPolicyAndComplianceAuditLog.yml
  Packs/Office365AndAzureAuditLog/Integrations/MicrosoftPolicyAndComplianceAuditLog/MicrosoftPolicyAndComplianceAuditLog_description.md
  Packs/Office365AndAzureAuditLog/Integrations/MicrosoftPolicyAndComplianceAuditLog/MicrosoftPolicyAndComplianceAuditLog_image.png
  Packs/Office365AndAzureAuditLog/Integrations/MicrosoftPolicyAndComplianceAuditLog/README.md
  Packs/Office365AndAzureAuditLog/Integrations/MicrosoftPolicyAndComplianceAuditLog/command_examples
  Packs/Office365AndAzureAuditLog/README.md
  Packs/Office365AndAzureAuditLog/TestPlaybooks/Auditlogs-test.yml
  Packs/Office365AndAzureAuditLog/pack_metadata.json
  Tests/conf.json
Labels: docs-approved

#11395 IAM pack - Workday mapper fix for unmapped fields (labels)
  Packs/Workday/Classifiers/classifier-IAM_Sync_User_-_Workday.json
  Packs/Workday/ReleaseNotes/1_0_10.md
  Packs/Workday/pack_metadata.json
Labels: docs-approved

#11404 fixed README.md
  Packs/Office365AndAzureAuditLog/Integrations/MicrosoftPolicyAndComplianceAuditLog/README.md
Labels: docs-approved

#11407 Slack v2 - Converted response to json
  Packs/Slack/Integrations/Slack/Slack.py
  Packs/Slack/Integrations/Slack/Slack_test.py
  Packs/Slack/ReleaseNotes/1_3_15.md
  Packs/Slack/pack_metadata.json
  Tests/conf.json
Labels: bug, docs-approved, release-notes-only

#11408 Revert "Fix for removing metadata versions"
  Tests/Marketplace/upload_packs.py
Labels: docs-approved

#11411 Microsoft Teams - improve team_member arg description
  Packs/MicrosoftTeams/Integrations/MicrosoftTeams/MicrosoftTeams.yml
  Packs/MicrosoftTeams/Integrations/MicrosoftTeams/README.md
  Packs/MicrosoftTeams/ReleaseNotes/1_1_1.md
  Packs/MicrosoftTeams/pack_metadata.json
Labels: docs-approved

#11412 CrowdStrikeFalconX: added base_url parameter
  Packs/CrowdStrikeFalconX/Integrations/CrowdStrikeFalconX/CrowdStrikeFalconX.py
  Packs/CrowdStrikeFalconX/Integrations/CrowdStrikeFalconX/CrowdStrikeFalconX.yml
  Packs/CrowdStrikeFalconX/ReleaseNotes/1_1_0.md
  Packs/CrowdStrikeFalconX/pack_metadata.json
Labels: bug, docs-approved

#11256 Mocking the following integrations:
  Tests/conf.json
Labels: docs-approved

#11414 ServiceNow v2: added another validation for the test-module
  Packs/ServiceNow/Integrations/ServiceNowv2/ServiceNowv2.py
  Packs/ServiceNow/ReleaseNotes/2_1_13.md
  Packs/ServiceNow/pack_metadata.json
Labels: bug, docs-approved, release-notes-only

#11400 GoogleCloudTranslate-Test - increase pid to 9
  Tests/conf.json
Labels: docs-approved

#11413 starter pack: update base integration name
  Packs/StarterPack/Integrations/BaseIntegration/BaseIntegration.yml
  Packs/StarterPack/ReleaseNotes/1_0_1.md
  Packs/StarterPack/Scripts/BaseScript/BaseScript.yml
  Packs/StarterPack/pack_metadata.json
Labels: docs-approved

#11383 Fix twinwave description
  Packs/Twinwave/Integrations/Twinwave/README.md
  Packs/Twinwave/Integrations/Twinwave/Twinwave.yml
  Packs/Twinwave/ReleaseNotes/1_0_2.md
  Packs/Twinwave/pack_metadata.json
Labels: Contribution, Partner, docs-approved, ready-for-instance-test

#11204 Splunk CIM mapping fields
  Packs/SplunkPy/Integrations/SplunkPy/README.md
  Packs/SplunkPy/Integrations/SplunkPy/SplunkPy.py
  Packs/SplunkPy/Integrations/SplunkPy/SplunkPy.yml
  Packs/SplunkPy/Integrations/SplunkPy/SplunkPy_test.py
  Packs/SplunkPy/ReleaseNotes/1_3_0.md
  Packs/SplunkPy/pack_metadata.json
Labels: docs-approved

#11423 Active directory query v2 grammer bug fix
  Packs/Active_Directory_Query/Integrations/Active_Directory_Query/Active_Directory_Query.py
  Packs/Active_Directory_Query/ReleaseNotes/1_1_4.md
  Packs/Active_Directory_Query/pack_metadata.json
Labels: docs-approved

#11396 Add sc_req_item and incident ticket types to incident mirroring.
  Packs/ServiceNow/Integrations/ServiceNowv2/ServiceNowv2.py
  Packs/ServiceNow/Integrations/ServiceNowv2/ServiceNowv2.yml
  Packs/ServiceNow/Integrations/ServiceNowv2/ServiceNowv2_test.py
  Packs/ServiceNow/ReleaseNotes/2_1_14.md
  Packs/ServiceNow/pack_metadata.json
Labels: docs-approved, release-notes-only

#11331 CSP GetRemoteDataResponse Bugfix
  Packs/Base/ReleaseNotes/1_7_14.md
  Packs/Base/Scripts/CommonServerPython/CommonServerPython.py
  Packs/Base/pack_metadata.json
Labels: docs-approved

#11321 Content fix files path's
  Packs/Rapid7_InsightIDR/Integrations/Rapid7_InsightIDR/Rapid7_InsightIDR.py
  Packs/Rapid7_InsightIDR/Integrations/Rapid7_InsightIDR/Rapid7_InsightIDR.yml
  Packs/Rapid7_InsightIDR/Integrations/Rapid7_InsightIDR/Rapid7_InsightIDR_description.md
  Packs/Rapid7_InsightIDR/Integrations/Rapid7_InsightIDR/Rapid7_InsightIDR_image.png
  Packs/Rapid7_InsightIDR/Integrations/Rapid7_InsightIDR/Rapid7_InsightIDR_test.py
  Packs/Rapid7_InsightIDR/ReleaseNotes/1_0_1.md
  Packs/Rapid7_InsightIDR/pack_metadata.json
  Packs/Salesforce/Integrations/integration-Salesforce.yml
  Packs/Salesforce/Integrations/integration-Salesforce_README.md
  Packs/Salesforce/ReleaseNotes/1_0_4.md
  Packs/Salesforce/pack_metadata.json
  Packs/SophosXGFirewall/Integrations/SophosXGFirewall/.vulture_whitelist.py
  Packs/SophosXGFirewall/Integrations/SophosXGFirewall/README.md
  Packs/SophosXGFirewall/Integrations/SophosXGFirewall/SophosXGFirewall.py
  Packs/SophosXGFirewall/Integrations/SophosXGFirewall/SophosXGFirewall.yml
  Packs/SophosXGFirewall/Integrations/SophosXGFirewall/SophosXGFirewall_description.md
  Packs/SophosXGFirewall/Integrations/SophosXGFirewall/SophosXGFirewall_image.png
  Packs/SophosXGFirewall/Integrations/SophosXGFirewall/SophosXGFirewall_test.py
  Packs/SophosXGFirewall/Integrations/SophosXGFirewall/command_examples.txt
  Packs/SophosXGFirewall/Integrations/SophosXGFirewall/test_data/app_category_get.xml
  Packs/SophosXGFirewall/Integrations/SophosXGFirewall/test_data/app_category_list.xml
  Packs/SophosXGFirewall/Integrations/SophosXGFirewall/test_data/app_category_set.xml
  Packs/SophosXGFirewall/Integrations/SophosXGFirewall/test_data/app_policy_get.xml
  Packs/SophosXGFirewall/Integrations/SophosXGFirewall/test_data/app_policy_set.xml
  Packs/SophosXGFirewall/Integrations/SophosXGFirewall/test_data/ip_host_get.xml
  Packs/SophosXGFirewall/Integrations/SophosXGFirewall/test_data/ip_host_group_get.xml
  Packs/SophosXGFirewall/Integrations/SophosXGFirewall/test_data/ip_host_group_list.xml
  Packs/SophosXGFirewall/Integrations/SophosXGFirewall/test_data/ip_host_group_set.xml
  Packs/SophosXGFirewall/Integrations/SophosXGFirewall/test_data/ip_host_list.xml
  Packs/SophosXGFirewall/Integrations/SophosXGFirewall/test_data/ip_host_set.xml
  Packs/SophosXGFirewall/Integrations/SophosXGFirewall/test_data/rule_get.json
  Packs/SophosXGFirewall/Integrations/SophosXGFirewall/test_data/rule_get.xml
  Packs/SophosXGFirewall/Integrations/SophosXGFirewall/test_data/rule_group_get.xml
  Packs/SophosXGFirewall/Integrations/SophosXGFirewall/test_data/rule_group_list.xml
  Packs/SophosXGFirewall/Integrations/SophosXGFirewall/test_data/rule_group_set.xml
  Packs/SophosXGFirewall/Integrations/SophosXGFirewall/test_data/rule_list.xml
  Packs/SophosXGFirewall/Integrations/SophosXGFirewall/test_data/rule_set.xml
  Packs/SophosXGFirewall/Integrations/SophosXGFirewall/test_data/services_get.xml
  Packs/SophosXGFirewall/Integrations/SophosXGFirewall/test_data/services_list.xml
  Packs/SophosXGFirewall/Integrations/SophosXGFirewall/test_data/services_set.xml
  Packs/SophosXGFirewall/Integrations/SophosXGFirewall/test_data/url_group_get.xml
  Packs/SophosXGFirewall/Integrations/SophosXGFirewall/test_data/url_group_list.xml
  Packs/SophosXGFirewall/Integrations/SophosXGFirewall/test_data/url_group_set.xml
  Packs/SophosXGFirewall/Integrations/SophosXGFirewall/test_data/user_get.xml
  Packs/SophosXGFirewall/Integrations/SophosXGFirewall/test_data/user_list.xml
  Packs/SophosXGFirewall/Integrations/SophosXGFirewall/test_data/user_set.xml
  Packs/SophosXGFirewall/Integrations/SophosXGFirewall/test_data/web_filter_get.xml
  Packs/SophosXGFirewall/Integrations/SophosXGFirewall/test_data/web_filter_list.xml
  Packs/SophosXGFirewall/Integrations/SophosXGFirewall/test_data/web_filter_set.xml
  Packs/SophosXGFirewall/ReleaseNotes/1_0_2.md
  Packs/SophosXGFirewall/pack_metadata.json
Labels: docs-approved

#11422 remove un-needed readme which was causing errors in content-docs
  Packs/CommonScripts/Scripts/ScheduleGenericPolling/script-ScheduleGenericPolling_README.md
Labels: docs-approved

#11431 slackask: update doc about task tag
  Packs/Slack/Scripts/SlackAsk/README.md
Labels: docs-approved
