Repository demisto/content, pull requests merged in 2021-05, with the labels that each got.

#11994 Remove dedup generic v2
  Packs/Base/ReleaseNotes/1_10_10.md
  Packs/Base/Scripts/FindSimilarIncidentsByText/FindSimilarIncidentsByText.yml
  Packs/Base/pack_metadata.json
  Packs/CommonPlaybooks/Playbooks/playbook-Dedup_-_Generic_v2.yml
  Packs/CommonPlaybooks/Playbooks/playbook-Get_File_Sample_By_Hash_-_Generic_v3.yml
  Packs/CommonPlaybooks/Playbooks/playbook-Get_File_Sample_From_Path_-_Generic_V2.yml
  Packs/CommonPlaybooks/ReleaseNotes/1_9_4.md
  Packs/CommonPlaybooks/pack_metadata.json
  Packs/CommonScripts/ReleaseNotes/1_3_40.md
  Packs/CommonScripts/Scripts/FindSimilarIncidentsV2/FindSimilarIncidentsV2.yml
  Packs/CommonScripts/Scripts/GetDuplicatesMlv2/GetDuplicatesMlv2.yml
  Packs/CommonScripts/pack_metadata.json
  TestPlaybooks/NonCircleTests/Deprecated/playbook-Dedup_-_Generic_v2_-_Test.yml
  Tests/conf.json
Labels: release-notes-only

#12299 Updated Cortex XDR Pack README
  Packs/CortexXDR/README.md
Labels: docs-approved

#12414 Create ServiceNow Content Pack README.md
  Packs/ServiceNow/README.md
Labels: docs-approved

#12461 Zscalar: Fix key error
  Packs/Zscaler/Integrations/Zscaler/Zscaler.py
  Packs/Zscaler/Integrations/Zscaler/Zscaler.yml
  Packs/Zscaler/ReleaseNotes/1_1_3.md
  Packs/Zscaler/pack_metadata.json
Labels: bug, docs-approved, release-notes-only

#12449 Change multi select duplicate similar incident script
  Packs/Base/ReleaseNotes/1_10_11.md
  Packs/Base/Scripts/DBotFindSimilarIncidents/DBotFindSimilarIncidents.py
  Packs/Base/Scripts/DBotFindSimilarIncidents/DBotFindSimilarIncidents.yml
  Packs/Base/pack_metadata.json
Labels: docs-approved

#12460 URLhuas: Fix none type iterable bug
  Packs/URLHaus/Integrations/URLHaus/URLHaus.py
  Packs/URLHaus/Integrations/URLHaus/URLHaus.yml
  Packs/URLHaus/ReleaseNotes/1_0_3.md
  Packs/URLHaus/pack_metadata.json
Labels: bug, docs-approved, release-notes-only

#12181 Cyberint attachment feature
  Packs/Cyberint/Integrations/Cyberint/Cyberint.py
  Packs/Cyberint/Integrations/Cyberint/Cyberint.yml
  Packs/Cyberint/Integrations/Cyberint/Cyberint_test.py
  Packs/Cyberint/Integrations/Cyberint/README.md
  Packs/Cyberint/Integrations/Cyberint/test_data/attachment_file_mock.png
  Packs/Cyberint/Integrations/Cyberint/test_data/expert_analysis_mock.pdf
  Packs/Cyberint/Integrations/Cyberint/test_data/list_alerts.json
  Packs/Cyberint/ReleaseNotes/1_0_5.md
  Packs/Cyberint/TestPlaybooks/playbook-Cyberint_Test.yml
  Packs/Cyberint/pack_metadata.json
Labels: Contribution, Partner, docs-approved

#12427 update README with relevant information
  Packs/Twinwave/README.md
Labels: Contribution, Partner, docs-approved

#12363 Kafka v2 - add max_bytes_per_message parameter
  Packs/Kafka/Integrations/Kafka_V2/Kafka_V2.py
  Packs/Kafka/Integrations/Kafka_V2/Kafka_V2.yml
  Packs/Kafka/ReleaseNotes/1_0_3.md
  Packs/Kafka/pack_metadata.json
Labels: bug, docs-approved

#12379 Carbon black edr incorrect isolation status
  Packs/Carbon_Black_Enterprise_Response/Integrations/integration-Carbon_Black_Enterprise_Response.yml
  Packs/Carbon_Black_Enterprise_Response/ReleaseNotes/1_1_7.md
  Packs/Carbon_Black_Enterprise_Response/pack_metadata.json
Labels: bug, docs-approved, release-notes-only

#12340 MicrosoftApiModule: Verify no session_state in code
  Packs/ApiModules/Scripts/MicrosoftApiModule/MicrosoftApiModule.py
  Packs/AzureLogAnalytics/ReleaseNotes/1_0_9.md
  Packs/AzureLogAnalytics/pack_metadata.json
  Packs/AzureSentinel/ReleaseNotes/1_0_10.md
  Packs/AzureSentinel/pack_metadata.json
  Packs/MicrosoftGraphListener/ReleaseNotes/1_0_15.md
  Packs/MicrosoftGraphListener/pack_metadata.json
  Packs/MicrosoftGraphUser/ReleaseNotes/1_3_9.md
  Packs/MicrosoftGraphUser/pack_metadata.json
  Packs/MicrosoftManagementActivity/ReleaseNotes/1_1_11.md
  Packs/MicrosoftManagementActivity/pack_metadata.json
Labels: bug, docs-approved

#12448 Adding preprocessing stage when applying prediction on a list of texts
  Packs/Base/ReleaseNotes/1_10_12.md
  Packs/Base/Scripts/DBotMLFetchData/DBotMLFetchData.py
  Packs/Base/Scripts/DBotPredictPhishingWords/DBotPredictPhishingWords.py
  Packs/Base/Scripts/DBotPredictPhishingWords/DBotPredictPhishingWords.yml
  Packs/Base/Scripts/DBotPredictPhishingWords/dbot_predict_phishing_words_test.py
  Packs/Base/Scripts/DBotPreprocessTextData/DBotPreprocessTextData.py
  Packs/Base/Scripts/DBotPreprocessTextData/DBotPreprocessTextData.yml
  Packs/Base/pack_metadata.json
  Packs/EWS/TestPlaybooks/playbook-GetEWSFolder-Test.yml
  Packs/ML/ReleaseNotes/1_2_8.md
  Packs/ML/Scripts/DBotPredictIncidentsBatch/DBotPredictIncidentsBatch.py
  Packs/ML/Scripts/DBotPredictIncidentsBatch/DBotPredictIncidentsBatch.yml
  Packs/ML/pack_metadata.json
Labels: docs-approved

#12430 Codecov playbook | GitHub search code
  Packs/ExpanseV2/Playbooks/test.json
  Packs/MajorBreachesInvestigationandResponse/Playbooks/playbook-Codecov_Breach_-_Bash_Uploader.yml
  Packs/MajorBreachesInvestigationandResponse/Playbooks/playbook-Codecov_Breach_-_Bash_Uploader_README.md
  Packs/MajorBreachesInvestigationandResponse/ReleaseNotes/1_6_2.md
  Packs/MajorBreachesInvestigationandResponse/doc_files/Codecov_breach_-_Bash_Uploader.png
  Packs/MajorBreachesInvestigationandResponse/pack_metadata.json
Labels: docs-approved

#12471 Cyberint - fix readme
  Packs/Cyberint/Integrations/Cyberint/README.md
Labels: docs-approved

#12474 Deleted test.json file in Expanse v2 Playbook pack
  Packs/ExpanseV2/Playbooks/test.json
Labels: docs-approved

#12394 Vm ray upload sample bug
  Packs/VMRay/Integrations/VMRay/VMRay.py
  Packs/VMRay/Integrations/VMRay/VMRay.yml
  Packs/VMRay/Integrations/VMRay/VMRay_test.py
  Packs/VMRay/ReleaseNotes/1_0_1.md
  Packs/VMRay/pack_metadata.json
Labels: bug, docs-approved, release-notes-only

#12476 Teams Management - unskip test
  Tests/conf.json
Labels: docs-approved

#12419 return results failed to receive a result entry in a list
  Packs/Base/ReleaseNotes/1_10_13.md
  Packs/Base/Scripts/CommonServerPython/CommonServerPython.py
  Packs/Base/Scripts/CommonServerPython/CommonServerPython_test.py
  Packs/Base/pack_metadata.json
Labels: docs-approved, release-notes-only

#12422 Updated description of URLScan integration
  Packs/UrlScan/Integrations/UrlScan/UrlScan.yml
  Packs/UrlScan/ReleaseNotes/1_1_4.md
  Packs/UrlScan/pack_metadata.json
Labels: docs-approved

#12186 added fields to the indicator classes
  Packs/Base/ReleaseNotes/1_10_14.md
  Packs/Base/Scripts/CommonServerPython/CommonServerPython.py
  Packs/Base/Scripts/CommonServerPython/CommonServerPython_test.py
  Packs/Base/pack_metadata.json
Labels: docs-approved

#12481 Taxii Server - docker image update + TPB
  Packs/TAXIIServer/Integrations/TAXIIServer/TAXIIServer.yml
  Packs/TAXIIServer/ReleaseNotes/1_0_3.md
  Packs/TAXIIServer/pack_metadata.json
Labels: docs-approved, release-notes-only

#12470 Update Microsoft Graph Files Integration README
  Packs/MicrosoftGraphFiles/Integrations/MicrosoftGraphFiles/README.md
Labels: docs-approved

#12484 QradarV1: Update test-module
  Packs/QRadar/Integrations/QRadar/QRadar.py
  Packs/QRadar/ReleaseNotes/2_0_4.md
  Packs/QRadar/pack_metadata.json
Labels: bug, docs-approved, release-notes-only

#12468 RSA Netwitness readme note
  Packs/RSANetWitness_v11_1/Integrations/RSANetWitness_v11_1/README.md
Labels: docs-approved

#11898 mock Feodo Tracker IP Blocklist Feed
  Packs/FeedFeodoTracker/.pack-ignore
  Packs/FeedFeodoTracker/TestPlaybooks/playbook-feodotrackeripblock_test_30_days.yml
  Packs/FeedFeodoTracker/TestPlaybooks/playbook-feodotrackeripblock_test_currently__active.yml
  Tests/conf.json
Labels: docs-approved

#12323 added an option to batch save to kv store
  Packs/SplunkPy/Integrations/SplunkPy/SplunkPy.py
  Packs/SplunkPy/Integrations/SplunkPy/SplunkPy.yml
  Packs/SplunkPy/ReleaseNotes/2_0_2.md
  Packs/SplunkPy/TestPlaybooks/SplunkPy_KV_commands.yml
  Packs/SplunkPy/pack_metadata.json
Labels: bug, docs-approved, release-notes-only

#12505 Cherwell unmocked comment updated
  Tests/conf.json
Labels: docs-approved

#12135 AWS- SQS added credentials - access and secret keys
  Packs/AWS-SQS/Integrations/AWS-SQS/AWS-SQS.py
  Packs/AWS-SQS/Integrations/AWS-SQS/AWS-SQS.yml
  Packs/AWS-SQS/Integrations/AWS-SQS/README.md
  Packs/AWS-SQS/ReleaseNotes/1_1_0.md
  Packs/AWS-SQS/pack_metadata.json
Labels: docs-approved, release-notes-only

#12504 IAM - AD updates
  Packs/Active_Directory_Query/Integrations/Active_Directory_Query/Active_Directory_Query.py
  Packs/Active_Directory_Query/Integrations/Active_Directory_Query/Active_Directory_Query.yml
  Packs/Active_Directory_Query/Integrations/Active_Directory_Query/connection_test.py
  Packs/Active_Directory_Query/ReleaseNotes/1_1_10.md
  Packs/Active_Directory_Query/Scripts/IAMInitADUser/IAMInitADUser.py
  Packs/Active_Directory_Query/Scripts/IAMInitADUser/IAMInitADUser.yml
  Packs/Active_Directory_Query/pack_metadata.json
  Packs/ApiModules/Scripts/IAMApiModule/IAMApiModule.py
  Packs/Attlasian/ReleaseNotes/1_0_1.md
  Packs/Attlasian/pack_metadata.json
  Packs/GitHub/ReleaseNotes/1_2_3.md
  Packs/GitHub/pack_metadata.json
  Packs/HelloIAMWorld/ReleaseNotes/1_0_3.md
  Packs/HelloIAMWorld/pack_metadata.json
  Packs/Okta/ReleaseNotes/2_1_9.md
  Packs/Okta/pack_metadata.json
  Packs/Salesforce/ReleaseNotes/1_0_6.md
  Packs/Salesforce/pack_metadata.json
  Packs/ServiceNow/ReleaseNotes/2_1_21.md
  Packs/ServiceNow/pack_metadata.json
  Packs/Slack/ReleaseNotes/1_3_19.md
  Packs/Slack/pack_metadata.json
Labels: docs-approved

#12483 AWS - Route53 split yml
  Packs/AWS-Route53/Integrations/AWSRoute53/AWSRoute53.py
  Packs/AWS-Route53/Integrations/AWSRoute53/AWSRoute53.yml
  Packs/AWS-Route53/Integrations/AWSRoute53/AWSRoute53_image.png
  Packs/AWS-Route53/Integrations/AWSRoute53/Pipfile
  Packs/AWS-Route53/Integrations/AWSRoute53/Pipfile.lock
  Packs/AWS-Route53/Integrations/AWSRoute53/README.md
  Packs/AWS-Route53/Integrations/integration-AWS-Route53.yml
  Packs/AWS-Route53/Integrations/integration-AWS-Route53_README.md
  Packs/AWS-Route53/ReleaseNotes/1_1_0.md
  Packs/AWS-Route53/pack_metadata.json
Labels: docs-approved, release-notes-only

#12497 EWS TPBs adjustments
  Packs/EWS/TestPlaybooks/playbook-EWS_Public_Folders_Test.yml
  Packs/EWS/TestPlaybooks/playbook-pyEWS_Test.yml
  Tests/conf.json
Labels: docs-approved

#12451 Cyren Threat InDepth: replaced githubUser list
  Packs/FeedCyrenThreatInDepth/ReleaseNotes/1_5_2.md
  Packs/FeedCyrenThreatInDepth/pack_metadata.json
Labels: Contribution, Partner, docs-approved

#12408 Fixed a layout in README that is broken in the web.
  Packs/MapPattern/Scripts/MapPattern/README.md
  Packs/MapPattern/pack_metadata.json
Labels: Contribution, docs-approved

#12386 Updated QueryAI pack's README with new format
  Packs/QueryAI/README.md
Labels: Contribution, Partner, docs-approved

#12509 Cyberint - Add section to layout
  Packs/Cyberint/Layouts/layoutscontainer-Cyberint_Incident_Layout.json
  Packs/Cyberint/ReleaseNotes/1_0_6.md
  Packs/Cyberint/pack_metadata.json
Labels: Contribution, Partner, docs-approved

#12203 Creating gitlab-ci file and writing default attributes of a job:
  .circleci/config.yml
  .circleci/gitlab-ci-env-variables.sh
  .gitlab-ci.yml
  Tests/Marketplace/Tests/marketplace_services_test.py
  Tests/Marketplace/Tests/upload_packs_test.py
  Tests/Marketplace/install_packs.sh
  Tests/Marketplace/upload_packs.py
  Tests/configure_and_test_integration_instances.py
  Tests/instance_notifier.py
  Tests/lastest_server_build_scripts/download_demisto_conf.sh
  Tests/lastest_server_build_scripts/run_installer_on_instance.sh
  Tests/lastest_server_build_scripts/run_tests.sh
  Tests/scripts/collect_tests_and_content_packs.py
  Tests/scripts/download_demisto_conf.sh
  Tests/scripts/infrastructure_tests/test_collect_tests_and_content_packs.py
  Tests/scripts/install_content_and_test_integrations.sh
  Tests/scripts/instance_test.sh
  Tests/scripts/is_file_up_to_date.sh
  Tests/scripts/open_ssh_tunnel.sh
  Tests/scripts/prepare_content_packs_for_testing.sh
  Tests/scripts/prepare_private_content_packs_for_testing.sh
  Tests/scripts/run_tests.sh
  Tests/scripts/should_lint_all.sh
  Tests/scripts/slack_notifier.sh
  Tests/scripts/upload_artifacts.sh
  Tests/scripts/utils/log_util.py
  Tests/scripts/validate_premium_packs.sh
  Tests/scripts/wait_until_server_ready.py
  Tests/test_content.py
  Utils/merge_content_new_zip.py
  Utils/trigger_private_build.py
  dev-requirements-py3.txt
Labels: docs-approved

#12336 Update README.md
  Packs/Cymptom/README.md
Labels: Contribution, Partner, docs-approved

#12527 Supporting zipping content packs from GCS on master branch
  .circleci/config.yml
Labels: docs-approved

#12511 AWS - Sagemaker - split yml
  Packs/AWS_Sagemaker/Integrations/AWSSagemaker/AWSSagemaker.py
  Packs/AWS_Sagemaker/Integrations/AWSSagemaker/AWSSagemaker.yml
  Packs/AWS_Sagemaker/Integrations/AWSSagemaker/AWSSagemaker_image.png
  Packs/AWS_Sagemaker/Integrations/AWSSagemaker/Pipfile
  Packs/AWS_Sagemaker/Integrations/AWSSagemaker/Pipfile.lock
  Packs/AWS_Sagemaker/Integrations/AWSSagemaker/README.md
  Packs/AWS_Sagemaker/ReleaseNotes/1_1_0.md
  Packs/AWS_Sagemaker/pack_metadata.json
Labels: docs-approved

#12530 Taxii Server docker image update
  Packs/TAXIIServer/Integrations/TAXIIServer/TAXIIServer.yml
  Packs/TAXIIServer/ReleaseNotes/1_0_4.md
  Packs/TAXIIServer/pack_metadata.json
Labels: bug, docs-approved

#12526 AzureSecurityCenter: Add subscription_id arg
  Packs/AzureSecurityCenter/Integrations/AzureSecurityCenter_v2/AzureSecurityCenter_v2.yml
  Packs/AzureSecurityCenter/ReleaseNotes/1_1_9.md
  Packs/AzureSecurityCenter/pack_metadata.json
Labels: docs-approved

#12366 Symantec ATP: Fetch Event Bug
  Packs/Symantec_Advanced_Threat_Protection/Integrations/integration-Symantec_Advanced_Threat_Protection.yml
  Packs/Symantec_Advanced_Threat_Protection/ReleaseNotes/1_1_3.md
  Packs/Symantec_Advanced_Threat_Protection/pack_metadata.json
Labels: bug, docs-approved, release-notes-only

#11963 Fixed an issue where **CommandResults** ***to_context*** function ove…
  Packs/Anomali_Enterprise/Integrations/Anomali_Enterprise/Anomali_Enterprise_test.py
  Packs/AnsibleTower/Integrations/AnsibleTower/AnsibleTower_test.py
  Packs/Base/ReleaseNotes/1_10_15.md
  Packs/Base/Scripts/CommonServerPython/CommonServerPython.py
  Packs/Base/Scripts/CommonServerPython/CommonServerPython_test.py
  Packs/Base/pack_metadata.json
  Packs/BmcHelixRemedyForce/Integrations/BmcHelixRemedyForce/TestData/get_queue_details_return_entry.json
  Packs/BmcHelixRemedyForce/Integrations/BmcHelixRemedyForce/TestData/get_user_details_return_entry.json
  Packs/CrowdStrikeFalcon/Integrations/CrowdStrikeFalcon/CrowdStrikeFalcon_test.py
  Packs/CyberArkPAS/Integrations/CyberArkPAS/test_data/context.py
  Packs/ExpanseV2/Integrations/ExpanseV2/ExpanseV2_test.py
  Packs/Flashpoint/Integrations/Flashpoint/Flashpoint_test.py
  Packs/Flashpoint/Integrations/Flashpoint/TestData/domain_ec.json
  Packs/GitHub/Integrations/GitHub/GitHub_test.py
  Packs/GoogleCloudSCC/Integrations/GoogleCloudSCC/GoogleCloudSCC_test.py
  Packs/GoogleCloudSCC/Integrations/GoogleCloudSCC/TestData/list_asset_ec.json
  Packs/GoogleCloudSCC/Integrations/GoogleCloudSCC/TestData/list_finding_ec.json
  Packs/GoogleCloudSCC/Integrations/GoogleCloudSCC/TestData/update_finding_ec.json
  Packs/MicrosoftGraphMail/Integrations/MicrosoftGraphMail/MicrosoftGraphMail_test.py
  Packs/PaloAltoNetworks_Threat_Vault/Integrations/Threat_Vault/Threat_Vault_test.py
  Packs/Polygon/Integrations/Polygon/test_data/results.json
  Packs/RecordedFuture/Integrations/RecordedFuture/RecordedFuture_test.py
  Packs/cyberark_AIM/Integrations/CyberArkAIM_v2/CyberArkAIM_v2_test.py
  Packs/cyberark_AIM/Integrations/CyberArkAIM_v2/test_data/context.py
Labels: docs-approved

#12506 remove Cylance Protect from unmockable list
  Tests/conf.json
Labels: docs-approved

#12380 New playbook for a new pack named 'Advisories Response'.
  Packs/MajorBreachesInvestigationandResponse/Playbooks/playbook-CVE-2021-22893_-_Pulse_Connect_Secure_RCE.yml
  Packs/MajorBreachesInvestigationandResponse/Playbooks/playbook-CVE-2021-22893_-_Pulse_Connect_Secure_RCE_README.md
  Packs/MajorBreachesInvestigationandResponse/README.md
  Packs/MajorBreachesInvestigationandResponse/ReleaseNotes/1_6_3.md
  Packs/MajorBreachesInvestigationandResponse/doc_files/CVE-2021-22893_-_Pulse_Connect_Secure_RCE.png
  Packs/MajorBreachesInvestigationandResponse/pack_metadata.json
Labels: docs-approved

#12404 json feed add indicator_type to rawjson + test improvement
  Packs/ApiModules/Scripts/JSONFeedApiModule/JSONFeedApiModule.py
  Packs/FeedAWS/ReleaseNotes/1_1_3.md
  Packs/FeedAWS/pack_metadata.json
  Packs/FeedFastly/ReleaseNotes/1_1_3.md
  Packs/FeedFastly/pack_metadata.json
  Packs/FeedIntel471/ReleaseNotes/1_1_4.md
  Packs/FeedIntel471/pack_metadata.json
  Packs/FeedJSON/Integrations/FeedJSON/FeedJSON.py
  Packs/FeedJSON/Integrations/FeedJSON/FeedJSON.yml
  Packs/FeedJSON/Integrations/FeedJSON/FeedJSON_description.md
  Packs/FeedJSON/Integrations/FeedJSON/README.md
  Packs/FeedJSON/ReleaseNotes/1_1_3.md
  Packs/FeedJSON/pack_metadata.json
  Packs/iDefense/ReleaseNotes/3_0_4.md
  Packs/iDefense/pack_metadata.json
Labels: docs-approved, release-notes-only

#12486 feat(intezer): add latest report command
  Packs/Intezer/Integrations/IntezerV2/IntezerV2.py
  Packs/Intezer/Integrations/IntezerV2/IntezerV2.yml
  Packs/Intezer/Integrations/IntezerV2/IntezerV2_description.md
  Packs/Intezer/Integrations/IntezerV2/README.md
  Packs/Intezer/Playbooks/playbook-Intezer_-_Analyze_Uploaded_file.yml
  Packs/Intezer/Playbooks/playbook-Intezer_-_Analyze_Uploaded_file_README.md
  Packs/Intezer/Playbooks/playbook-Intezer_-_Analyze_by_hash.yml
  Packs/Intezer/README.md
  Packs/Intezer/ReleaseNotes/1_1_0.md
  Packs/Intezer/pack_metadata.json
Labels: Contribution, Partner, docs-approved

#12538 fixing SDK version in build
  dev-requirements-py3.txt
Labels: docs-approved

#12291 Updated Compliance pack README
  Packs/Compliance/README.md
Labels: docs-approved

#12402 Tidy Test Playbook
  Packs/Tidy/Integrations/Tidy/README.md
  Packs/Tidy/Integrations/Tidy/Tidy.py
  Packs/Tidy/Integrations/Tidy/Tidy.yml
  Packs/Tidy/Playbooks/playbook-Content_developer_setup.yml
  Packs/Tidy/ReleaseNotes/1_0_3.md
  Packs/Tidy/TestPlaybooks/Tidy_-_Test.yml
  Packs/Tidy/pack_metadata.json
  Tests/conf.json
Labels: docs-approved

#12310 IPQualityScore integration.
  Packs/IPQualityScore/.pack-ignore
  Packs/IPQualityScore/.secrets-ignore
  Packs/IPQualityScore/Integrations/IPQualityScore/IPQualityScore.py
  Packs/IPQualityScore/Integrations/IPQualityScore/IPQualityScore.yml
  Packs/IPQualityScore/Integrations/IPQualityScore/IPQualityScore_description.md
  Packs/IPQualityScore/Integrations/IPQualityScore/IPQualityScore_image.png
  Packs/IPQualityScore/Integrations/IPQualityScore/IPQualityScore_test.py
  Packs/IPQualityScore/Integrations/IPQualityScore/README.md
  Packs/IPQualityScore/Integrations/IPQualityScore/command_examples.txt
  Packs/IPQualityScore/Integrations/IPQualityScore/test_data/email_response.json
  Packs/IPQualityScore/Integrations/IPQualityScore/test_data/ip_response.json
  Packs/IPQualityScore/Integrations/IPQualityScore/test_data/url_response.json
  Packs/IPQualityScore/README.md
  Packs/IPQualityScore/TestPlayBooks/TestIPQualityScorePlaybook.yml
  Packs/IPQualityScore/pack_metadata.json
Labels: Contribution, Partner

#12554 Relationships typo
  Packs/Base/ReleaseNotes/1_10_16.md
  Packs/Base/Scripts/CommonServerPython/CommonServerPython.py
  Packs/Base/pack_metadata.json
Labels: docs-approved

#12520 Update BastilleNetworks pack README.md
  Packs/BastilleNetworks/README.md
Labels: Contribution, Partner, docs-approved

#12501 Create Indicator Relationships script
  Packs/Base/ReleaseNotes/1_10_17.md
  Packs/Base/Scripts/CommonServerPython/CommonServerPython.py
  Packs/Base/Scripts/CreateIndicatorRelationship/CreateIndicatorRelationship.py
  Packs/Base/Scripts/CreateIndicatorRelationship/CreateIndicatorRelationship.yml
  Packs/Base/Scripts/CreateIndicatorRelationship/CreateIndicatorRelationship_test.py
  Packs/Base/pack_metadata.json
Labels: docs-approved

#12531 Valid pack name
  Packs/D2/.pack-ignore
  Packs/DefaultPlaybook/.pack-ignore
  Packs/LogPoint_SIEM_Integration/.pack-ignore
  Packs/OTRS/.pack-ignore
  Packs/OnboardingIntegration/.pack-ignore
  Packs/Palo_Alto_Networks_Enterprise_DLP/.pack-ignore
  Packs/StarterPack/.pack-ignore
  Packs/TIM_SIEM/.pack-ignore
  Packs/XMatters/.pack-ignore
  Packs/iDefense/.pack-ignore
  Packs/mnemonicMDR/.pack-ignore
Labels: docs-approved

#12536 Search Indicator Relationships script
  Packs/Base/.secrets-ignore
  Packs/Base/ReleaseNotes/1_10_18.md
  Packs/Base/Scripts/SearchIndicatorRelationships/SearchIndicatorRelationships.py
  Packs/Base/Scripts/SearchIndicatorRelationships/SearchIndicatorRelationships.yml
  Packs/Base/Scripts/SearchIndicatorRelationships/SearchIndicatorRelationships_test.py
  Packs/Base/Scripts/SearchIndicatorRelationships/test_data/searchRelationships-response.json
  Packs/Base/Scripts/SearchIndicatorRelationships/test_data/verbose_false_expected.json
  Packs/Base/Scripts/SearchIndicatorRelationships/test_data/verbose_true_expected.json
  Packs/Base/pack_metadata.json
Labels: docs-approved

#12532 Fixed a bug in searching indicators
  Packs/Base/ReleaseNotes/1_10_19.md
  Packs/Base/Scripts/CommonServerPython/CommonServerPython.py
  Packs/Base/Scripts/CommonServerPython/CommonServerPython_test.py
  Packs/Base/pack_metadata.json
Labels: docs-approved

#12473 MP Dependency Integration Images by Download Count
  Tests/Marketplace/Tests/marketplace_services_test.py
  Tests/Marketplace/marketplace_services.py
  Tests/Marketplace/marketplace_statistics.py
  Tests/Marketplace/upload_packs.py
Labels: docs-approved

#12102 Bad Indicators Activity by Type - Possible solution
  Packs/CommonWidgets/ReleaseNotes/1_0_8.md
  Packs/CommonWidgets/Widgets/widget-IndicatorBadActivityType.json
  Packs/CommonWidgets/pack_metadata.json
Labels: bug, docs-approved, release-notes-only

#12539 Delete Indicator Relationships script
  Packs/Base/ReleaseNotes/1_10_20.md
  Packs/Base/Scripts/DeleteIndicatorRelationships/DeleteIndicatorRelationships.py
  Packs/Base/Scripts/DeleteIndicatorRelationships/DeleteIndicatorRelationships.yml
  Packs/Base/pack_metadata.json
Labels: docs-approved

#12548 Archer v2 - Add levelId arg
  Packs/ArcherRSA/Integrations/ArcherV2/ArcherV2.py
  Packs/ArcherRSA/Integrations/ArcherV2/ArcherV2.yml
  Packs/ArcherRSA/Integrations/ArcherV2/ArcherV2_test.py
  Packs/ArcherRSA/ReleaseNotes/1_1_15.md
  Packs/ArcherRSA/Scripts/ArcherCreateIncidentExample/ArcherCreateIncidentExample.yml
  Packs/ArcherRSA/pack_metadata.json
Labels: bug, docs-approved

#12546 Fixed integrations description names
  Packs/Cylance_Protect/Integrations/Cylance_Protect_v2/Cylance_Protect_v2_description.md
  Packs/Cylance_Protect/ReleaseNotes/1_0_4.md
  Packs/Cylance_Protect/pack_metadata.json
  Packs/OTRS/Integrations/OTRS/OTRS_description.md
  Packs/OTRS/ReleaseNotes/1_0_3.md
  Packs/OTRS/pack_metadata.json
Labels: docs-approved

#12562 renamed relation to relationship around the repo
  Packs/AlienVault_OTX/Integrations/AlienVault_OTX_v2/AlienVault_OTX_v2.py
  Packs/AlienVault_OTX/Integrations/AlienVault_OTX_v2/AlienVault_OTX_v2_test.py
  Packs/AlienVault_OTX/ReleaseNotes/1_1_1.md
  Packs/AlienVault_OTX/pack_metadata.json
  Packs/ApiModules/Scripts/CSVFeedApiModule/CSVFeedApiModule.py
  Packs/ApiModules/Scripts/CSVFeedApiModule/CSVFeedApiModule_test.py
  Packs/ApiModules/Scripts/HTTPFeedApiModule/HTTPFeedApiModule.py
  Packs/ApiModules/Scripts/HTTPFeedApiModule/HTTPFeedApiModule_test.py
  Packs/Base/ReleaseNotes/1_10_21.md
  Packs/Base/Scripts/CommonServerPython/CommonServerPython.py
  Packs/Base/Scripts/CommonServerPython/CommonServerPython_test.py
  Packs/Base/pack_metadata.json
  Packs/BitcoinAbuse/ReleaseNotes/1_0_3.md
  Packs/BitcoinAbuse/pack_metadata.json
  Packs/FeedAlienVault/ReleaseNotes/1_1_1.md
  Packs/FeedAlienVault/pack_metadata.json
  Packs/FeedBambenekConsulting/Integrations/FeedBambenekConsulting/FeedBambenekConsulting.py
  Packs/FeedBambenekConsulting/ReleaseNotes/1_1_1.md
  Packs/FeedBambenekConsulting/pack_metadata.json
  Packs/FeedBlocklist_de/ReleaseNotes/1_1_1.md
  Packs/FeedBlocklist_de/pack_metadata.json
  Packs/FeedBruteForceBlocker/ReleaseNotes/1_1_1.md
  Packs/FeedBruteForceBlocker/pack_metadata.json
  Packs/FeedCSV/ReleaseNotes/1_1_1.md
  Packs/FeedCSV/pack_metadata.json
  Packs/FeedCloudflare/ReleaseNotes/1_1_1.md
  Packs/FeedCloudflare/pack_metadata.json
  Packs/FeedDShield/ReleaseNotes/1_1_1.md
  Packs/FeedDShield/pack_metadata.json
  Packs/FeedFeodoTracker/Integrations/FeedFeodoTrackerIPBlocklist/FeedFeodoTrackerIPBlocklist.py
  Packs/FeedFeodoTracker/ReleaseNotes/1_1_2.md
  Packs/FeedFeodoTracker/pack_metadata.json
  Packs/FeedMajesticMillion/ReleaseNotes/1_1_1.md
  Packs/FeedMajesticMillion/pack_metadata.json
  Packs/FeedMalwareDomainList/ReleaseNotes/1_1_1.md
  Packs/FeedMalwareDomainList/pack_metadata.json
  Packs/FeedPlainText/ReleaseNotes/1_1_1.md
  Packs/FeedPlainText/pack_metadata.json
  Packs/FeedSpamhaus/ReleaseNotes/1_1_1.md
  Packs/FeedSpamhaus/pack_metadata.json
  Packs/Feedsslabusech/ReleaseNotes/1_1_1.md
  Packs/Feedsslabusech/pack_metadata.json
  Packs/Flashpoint/Integrations/Flashpoint/Flashpoint.py
  Packs/Flashpoint/ReleaseNotes/1_1_1.md
  Packs/Flashpoint/pack_metadata.json
  Packs/UrlScan/Integrations/UrlScan/UrlScan.py
  Packs/UrlScan/ReleaseNotes/1_1_5.md
  Packs/UrlScan/pack_metadata.json
  Packs/XForceExchange/Integrations/XFE_v2/XFE_v2.py
  Packs/XForceExchange/Integrations/XFE_v2/XFE_v2_test.py
  Packs/XForceExchange/ReleaseNotes/1_1_1.md
  Packs/XForceExchange/pack_metadata.json
Labels: docs-approved

#12570 GDPR, HIPAA, Breach - update deps, fix typos
  Packs/BreachNotification-US/pack_metadata.json
  Packs/GDPR/pack_metadata.json
  Packs/HIPAA-BreachNotification/pack_metadata.json
Labels: docs-approved

#12566 Skipping Tidy
  Packs/Tidy/TestPlaybooks/Tidy_-_Test.yml
  Tests/conf.json
Labels: docs-approved

#12571 Azure NSG Test Unskip
  Tests/conf.json
Labels: docs-approved

#12576 Create Content Pack README for MicrosoftGraphListener
  Packs/MicrosoftGraphListener/README.md
Labels: docs-approved

#12573 Split GitLab Workflows into Separate Files
  .gitlab-ci.yml
  .gitlab/ci/global.yml
  .gitlab/ci/on-push.yml
  .hooks/bootstrap
  Tests/scripts/validate.sh
Labels: docs-approved

#12251 Google safe browsing v2
  Packs/GoogleSafeBrowsing/Integrations/GoogleSafeBrowsingV2/GoogleSafeBrowsingV2.py
  Packs/GoogleSafeBrowsing/Integrations/GoogleSafeBrowsingV2/GoogleSafeBrowsingV2.yml
  Packs/GoogleSafeBrowsing/Integrations/GoogleSafeBrowsingV2/GoogleSafeBrowsingV2_description.md
  Packs/GoogleSafeBrowsing/Integrations/GoogleSafeBrowsingV2/GoogleSafeBrowsingV2_image.png
  Packs/GoogleSafeBrowsing/Integrations/GoogleSafeBrowsingV2/GoogleSafeBrowsingV2_test.py
  Packs/GoogleSafeBrowsing/Integrations/GoogleSafeBrowsingV2/Pipfile
  Packs/GoogleSafeBrowsing/Integrations/GoogleSafeBrowsingV2/Pipfile.lock
  Packs/GoogleSafeBrowsing/Integrations/GoogleSafeBrowsingV2/README.md
  Packs/GoogleSafeBrowsing/Integrations/GoogleSafeBrowsingV2/command_examples
  Packs/GoogleSafeBrowsing/Integrations/integration-GoogleSafeBrowsing.yml
  Packs/GoogleSafeBrowsing/ReleaseNotes/2_0_0.md
  Packs/GoogleSafeBrowsing/pack_metadata.json
Labels: docs-approved

#12579 fixed relation to relationships
  Packs/Base/ReleaseNotes/1_10_22.md
  Packs/Base/Scripts/CreateIndicatorRelationship/CreateIndicatorRelationship.py
  Packs/Base/pack_metadata.json
Labels: docs-approved

#12456 Update Rubrik Polaris README
  Packs/RubrikPolaris/README.md
Labels: Contribution, Partner, docs-approved

#12580 firepower - added commands to TPB
  Packs/CiscoFirepower/Integrations/CiscoFirepower/CiscoFirepower.yml
  Packs/CiscoFirepower/ReleaseNotes/1_0_4.md
  Packs/CiscoFirepower/TestPlaybooks/playbook-CiscoFirepowerTest.yml
  Packs/CiscoFirepower/pack_metadata.json
Labels: docs-approved, release-notes-only

#12544 Several integrations: Fix duplicate args
  Packs/AWS-EC2/Integrations/AWS-EC2/AWS-EC2.yml
  Packs/AWS-EC2/ReleaseNotes/1_1_8.md
  Packs/AWS-EC2/pack_metadata.json
  Packs/Ansible_Powered_Integrations/Integrations/MicrosoftWindows/MicrosoftWindows.yml
  Packs/Ansible_Powered_Integrations/Integrations/OpenSSL/OpenSSL.yml
  Packs/Ansible_Powered_Integrations/ReleaseNotes/1_0_1.md
  Packs/Ansible_Powered_Integrations/pack_metadata.json
  Packs/FireEyeHX/Integrations/FireEyeHX/FireEyeHX.yml
  Packs/FireEyeHX/ReleaseNotes/1_0_11.md
  Packs/FireEyeHX/pack_metadata.json
  Packs/TheHiveProject/IncidentFields/incidentfield-Observables.json
  Packs/TheHiveProject/Integrations/TheHiveProject/TheHiveProject.yml
  Packs/TheHiveProject/ReleaseNotes/1_1_1.md
  Packs/TheHiveProject/pack_metadata.json
  Tests/conf.json
Labels: docs-approved

#12585 Fixed readme
  Packs/GSuiteSecurityAlertCenter/README.md
Labels: docs-approved

#12584 Axonius docker version bump 19245
  Packs/Axonius/Integrations/Axonius/Axonius.yml
  Packs/Axonius/ReleaseNotes/1_0_3.md
  Packs/Axonius/pack_metadata.json
Labels: Contribution, Partner, docs-approved

#12551 Splunk - Add incoming mirroring limitations
  Packs/SplunkPy/Integrations/SplunkPy/README.md
Labels: docs-approved

#12586 Update Agari README.md
  Packs/AgariPhishingDefense/README.md
Labels: Contribution, docs-approved

#12480 StixCreator: changed reputation values
  Packs/CommonScripts/ReleaseNotes/1_3_41.md
  Packs/CommonScripts/Scripts/StixCreator/README.md
  Packs/CommonScripts/Scripts/StixCreator/StixCreator.py
  Packs/CommonScripts/Scripts/StixCreator/StixCreator.yml
  Packs/CommonScripts/Scripts/script-StixCreator.yml
  Packs/CommonScripts/pack_metadata.json
Labels: bug, docs-approved, release-notes-only

#12512 Update README.md
  Packs/CofenseTriage/README.md
Labels: Contribution, Partner, docs-approved

#12549 Second stage of changes for the adoption of the content pack by Intel 471.
  Packs/FeedIntel471/Integrations/Intel471Actors/Intel471Actors_image.png
  Packs/FeedIntel471/Integrations/Intel471Malware/Intel471Malware_image.png
  Packs/FeedIntel471/README.md
  Packs/FeedIntel471/ReleaseNotes/1_2_0.md
  Packs/FeedIntel471/pack_metadata.json
Labels: Contribution, docs-approved

#12528 MicrosoftGraphMail: fix problem when changeing the account
  Packs/MicrosoftGraphMail/Integrations/MicrosoftGraphMail/MicrosoftGraphMail.py
  Packs/MicrosoftGraphMail/Integrations/MicrosoftGraphMail/MicrosoftGraphMail.yml
  Packs/MicrosoftGraphMail/Integrations/MicrosoftGraphMail/MicrosoftGraphMail_test.py
  Packs/MicrosoftGraphMail/ReleaseNotes/1_0_20.md
  Packs/MicrosoftGraphMail/pack_metadata.json
Labels: bug, docs-approved, release-notes-only

#12405 Update README.md
  Packs/Code42/README.md
Labels: Contribution, Partner, docs-approved

#12593 Active Directory Query v2: fixed null outputs
  Packs/Active_Directory_Query/Integrations/Active_Directory_Query/Active_Directory_Query.py
  Packs/Active_Directory_Query/ReleaseNotes/1_1_11.md
  Packs/Active_Directory_Query/pack_metadata.json
Labels: bug, docs-approved, release-notes-only

#12519 added the default bucket parameter
  Packs/GoogleCloudStorage/Integrations/GoogleCloudStorage/GoogleCloudStorage.py
  Packs/GoogleCloudStorage/Integrations/GoogleCloudStorage/GoogleCloudStorage.yml
  Packs/GoogleCloudStorage/ReleaseNotes/1_0_1.md
  Packs/GoogleCloudStorage/pack_metadata.json
Labels: bug, docs-approved

#12453 [greynoise-266] Update Pack ReadMe on GreyNoise Pack
  Packs/GreyNoise/.secrets-ignore
  Packs/GreyNoise/README.md
  Packs/GreyNoise/pack_metadata.json
Labels: Contribution, Partner, docs-approved

#12601 Update CODEOWNERS
  .github/CODEOWNERS
Labels: docs-approved

#12521 Create README.md
  Packs/AcalvioShadowplex/README.md
Labels: Contribution, Partner, docs-approved

#12432 fixed the release_notes_generator to handle the layoutscontainer on the packs release notes
  Tests/scripts/infrastructure_tests/release_notes_generator_test.py
  Tests/scripts/infrastructure_tests/tests_data/RN_tests_data/FakePack5/Layouts/layoutscontainer-fake.json
  Utils/release_notes_generator.py
Labels: docs-approved

#12443 Configuring nightly
  .gitlab-ci.yml
  .gitlab/ci/nightly.yml
  .gitlab/ci/on-push.yml
  Tests/configure_and_test_integration_instances.py
  Utils/gitlab_triggers/trigger_build_url.sh
  Utils/gitlab_triggers/trigger_content_nightly_build.sh
Labels: docs-approved

#12547 [EDL] Add filter fields and filter EDL queries
  Packs/Base/ReleaseNotes/1_10_23.md
  Packs/Base/Scripts/CommonServerPython/CommonServerPython.py
  Packs/Base/Scripts/CommonServerPython/CommonServerPython_test.py
  Packs/Base/pack_metadata.json
  Packs/EDL/Integrations/EDL/EDL.py
  Packs/EDL/Integrations/EDL/EDL.yml
  Packs/EDL/ReleaseNotes/1_0_15.md
  Packs/EDL/pack_metadata.json
  Tests/demistomock/demistomock.py
Labels: docs-approved

#12445 Recorded Future: Added two new fields to intelligence lookups for CVEs.
  Packs/RecordedFuture/Integrations/RecordedFuture/README.md
  Packs/RecordedFuture/Integrations/RecordedFuture/RecordedFuture.py
  Packs/RecordedFuture/Integrations/RecordedFuture/RecordedFuture.yml
  Packs/RecordedFuture/ReleaseNotes/1_1_1.md
  Packs/RecordedFuture/pack_metadata.json
Labels: Contribution, Partner

#12561 Change to GetIndicatorDBotScore
  Packs/CommonScripts/ReleaseNotes/1_3_42.md
  Packs/CommonScripts/Scripts/GetIndicatorDBotScore/GetIndicatorDBotScore.py
  Packs/CommonScripts/Scripts/GetIndicatorDBotScore/GetIndicatorDBotScore.yml
  Packs/CommonScripts/Scripts/GetIndicatorDBotScore/GetIndicatorDBotScore_test.py
  Packs/CommonScripts/Scripts/GetIndicatorDBotScore/README.md
  Packs/CommonScripts/pack_metadata.json
Labels: bug, docs-approved

#12076 Anomali threat stream tags data bug
  Packs/Anomali_ThreatStream/Integrations/Anomali_ThreatStream_v2/Anomali_ThreatStream_v2.py
  Packs/Anomali_ThreatStream/Integrations/Anomali_ThreatStream_v2/Anomali_ThreatStream_v2.yml
  Packs/Anomali_ThreatStream/Integrations/Anomali_ThreatStream_v2/README.md
  Packs/Anomali_ThreatStream/Integrations/Anomali_ThreatStream_v2/test_data/file_256_context.json
  Packs/Anomali_ThreatStream/Integrations/Anomali_ThreatStream_v2/test_data/file_512_context.json
  Packs/Anomali_ThreatStream/ReleaseNotes/1_1_1.md
  Packs/Anomali_ThreatStream/pack_metadata.json
Labels: bug, docs-approved

#12605 fixing handling of premium packs' pack metadata
  Tests/Marketplace/marketplace_services.py
Labels: docs-approved

#12567 GitHub - Add branch arg and SHA output to Github-list-files
  Packs/GitHub/Integrations/GitHub/GitHub.py
  Packs/GitHub/Integrations/GitHub/GitHub.yml
  Packs/GitHub/ReleaseNotes/1_2_4.md
  Packs/GitHub/pack_metadata.json
Labels: docs-approved

#12377 Cymulate Docs Fix
  Packs/Cymulate/README.md
Labels: Contribution, Partner, docs-approved

#12603 SDK release 1-3-6 content branch
  dev-requirements-py3.txt
Labels: docs-approved

#12577 Get incidents support populate fields
  Packs/Base/ReleaseNotes/1_10_24.md
  Packs/Base/Scripts/GetIncidentsByQuery/GetIncidentsByQuery.py
  Packs/Base/Scripts/GetIncidentsByQuery/GetIncidentsByQuery.yml
  Packs/Base/Scripts/GetIncidentsByQuery/get_incidents_by_query_test.py
  Packs/Base/pack_metadata.json
Labels: docs-approved, release-notes-only

#12568 fixing common types pack deps bug
  Packs/CommonTypes/pack_metadata.json
Labels: docs-approved

#12615 Fixed description name
  Packs/Perch/Integrations/Perch/Perch_description.md
  Packs/Perch/ReleaseNotes/1_0_2.md
  Packs/Perch/pack_metadata.json
Labels: docs-approved

#12616 Expanse v2: removed duplicate argument definition
  Packs/ExpanseV2/Integrations/ExpanseV2/ExpanseV2.yml
  Packs/ExpanseV2/ReleaseNotes/1_4_1.md
  Packs/ExpanseV2/pack_metadata.json
Labels: docs-approved

#9478 Thycotic secret server
  Packs/Thycotic/.pack-ignore
  Packs/Thycotic/.secrets-ignore
  Packs/Thycotic/Integrations/Thycotic/Pipfile
  Packs/Thycotic/Integrations/Thycotic/Pipfile.lock
  Packs/Thycotic/Integrations/Thycotic/README.md
  Packs/Thycotic/Integrations/Thycotic/Thycotic.py
  Packs/Thycotic/Integrations/Thycotic/Thycotic.yml
  Packs/Thycotic/Integrations/Thycotic/Thycotic_description.md
  Packs/Thycotic/Integrations/Thycotic/Thycotic_image.png
  Packs/Thycotic/Integrations/Thycotic/Thycotic_test.py
  Packs/Thycotic/Integrations/Thycotic/command_examples.txt
  Packs/Thycotic/Integrations/Thycotic/test_data/context.py
  Packs/Thycotic/Integrations/Thycotic/test_data/http_responses.py
  Packs/Thycotic/Playbooks/Example-Thycotic-Folder_Operations.yml
  Packs/Thycotic/Playbooks/Example-Thycotic-Retrieved_Username_and_Password.yml
  Packs/Thycotic/Playbooks/Example-Thycotic-Secret_Object_Operations.yml
  Packs/Thycotic/Playbooks/Example-Thycotic-User_object_operations.yml
  Packs/Thycotic/README.md
  Packs/Thycotic/TestPlaybooks/Thycotic-Test.yml
  Packs/Thycotic/pack_metadata.json
  Tests/conf.json
Labels: Contribution, Partner, docs-approved

#12529 Removed O365-SecurityAndCompliance-ContextResults-Test from skipped
  Tests/conf.json
Labels: docs-approved

#12472 rasterize default value fix
  Packs/rasterize/Integrations/rasterize/rasterize.yml
  Packs/rasterize/ReleaseNotes/1_0_8.md
  Packs/rasterize/pack_metadata.json
Labels: bug, docs-approved, release-notes-only

#12578 IsMaliciousIndicator task bug
  Packs/CommonScripts/ReleaseNotes/1_3_43.md
  Packs/CommonScripts/Scripts/script-IsMaliciousIndicatorFound.yml
  Packs/CommonScripts/TestPlaybooks/playbook-TestIsMaliciousIndicatorFound.yml
  Packs/CommonScripts/pack_metadata.json
Labels: bug, docs-approved, release-notes-only

#12489 Microsoft CAS fix example in yml file
  Packs/MicrosoftCloudAppSecurity/Integrations/MicrosoftCloudAppSecurity/MicrosoftCloudAppSecurity.yml
  Packs/MicrosoftCloudAppSecurity/ReleaseNotes/1_0_17.md
  Packs/MicrosoftCloudAppSecurity/pack_metadata.json
Labels: docs-approved

#12441 FindSimilarIncidents - improve query performance
  Packs/CommonScripts/ReleaseNotes/1_3_44.md
  Packs/CommonScripts/Scripts/FindSimilarIncidentsV2/FindSimilarIncidentsV2.py
  Packs/CommonScripts/Scripts/FindSimilarIncidentsV2/find_similar_incidents_test.py
  Packs/CommonScripts/pack_metadata.json
Labels: bug, docs-approved, release-notes-only

#12627 fix release notes for common types
  Packs/CommonTypes/ReleaseNotes/2_8_15.md
Labels: docs-approved

#12597 Updated ReadMe.md
  Packs/RiskSense/README.md
Labels: Contribution, docs-approved

#12622 MISP v2: fixed an issue with max attribute parameter after upgrade
  Packs/MISP/Integrations/MISP_V2/MISP_V2.py
  Packs/MISP/ReleaseNotes/1_0_7.md
  Packs/MISP/pack_metadata.json
Labels: bug, docs-approved, release-notes-only

#12406 XSOARLabUpdates Pack
  Packs/XSOARLabUpdates/.pack-ignore
  Packs/XSOARLabUpdates/.secrets-ignore
  Packs/XSOARLabUpdates/Author_image.png
  Packs/XSOARLabUpdates/Playbooks/NewPacksNotifier.yml
  Packs/XSOARLabUpdates/README.md
  Packs/XSOARLabUpdates/Scripts/BuildSlackBlocksFromIndex/BuildSlackBlocksFromIndex.py
  Packs/XSOARLabUpdates/Scripts/BuildSlackBlocksFromIndex/BuildSlackBlocksFromIndex.yml
  Packs/XSOARLabUpdates/Scripts/BuildSlackBlocksFromIndex/README.md
  Packs/XSOARLabUpdates/pack_metadata.json
Labels: docs-approved

#9646 Deprecate TCPIPUtils
  Packs/TCPIPUtils/.pack-ignore
  Packs/TCPIPUtils/Integrations/integration-TCPIPUtils.yml
  Packs/TCPIPUtils/ReleaseNotes/1_0_1.md
  Packs/TCPIPUtils/pack_metadata.json
Labels: docs-approved

#12620 Hod/instance testing support
  .circleci/config.yml
  .gitlab-ci.yml
  .gitlab/ci/instance-test.yml
  .gitlab/ci/nightly.yml
  .gitlab/ci/on-push.yml
  Tests/instance_notifier.py
  Utils/gitlab_triggers/trigger_content_instance_testing_build.sh
Labels: docs-approved

#12634 added requirement - pygithub
  .circleci/build-requirements.txt
Labels: docs-approved

#12475 Adding support in release branches
  .gitlab/ci/on-push.yml
  Tests/scripts/collect_tests_and_content_packs.py
  Tests/scripts/infrastructure_tests/test_collect_tests_and_content_packs.py
Labels: docs-approved

#12639 Allowing server scripts to continue when one of the step fails
  .gitlab/ci/on-push.yml
Labels: docs-approved

#12638 Update README.md
  Packs/Endace/README.md
Labels: Contribution, Partner, docs-approved

#12637 Search relationships fix
  Packs/Base/ReleaseNotes/1_10_25.md
  Packs/Base/Scripts/SearchIndicatorRelationships/SearchIndicatorRelationships.py
  Packs/Base/Scripts/SearchIndicatorRelationships/SearchIndicatorRelationships.yml
  Packs/Base/pack_metadata.json
Labels: docs-approved

#12641 rename ThreatCrowd_v2.png -> ThreatCrowd_v2_image.png
  Packs/Threat_Crowd/Integrations/ThreatCrowd_v2/ThreatCrowd_v2_image.png
  Packs/Threat_Crowd/ReleaseNotes/2_0_1.md
  Packs/Threat_Crowd/pack_metadata.json
Labels: docs-approved

#12555 TB for relationships scripts
  Packs/Base/ReleaseNotes/1_10_26.md
  Packs/Base/Scripts/CreateIndicatorRelationship/CreateIndicatorRelationship.yml
  Packs/Base/Scripts/DeleteIndicatorRelationships/DeleteIndicatorRelationships.yml
  Packs/Base/Scripts/SearchIndicatorRelationships/SearchIndicatorRelationships.yml
  Packs/Base/TestPlaybooks/Relationships_scripts_Test.yml
  Packs/Base/pack_metadata.json
Labels: docs-approved

#12563 Update README.md
  Packs/ThreatQ/README.md
Labels: Contribution, Partner, docs-approved

#12560 GitHub - list team members
  Packs/GitHub/Integrations/GitHub/GitHub.py
  Packs/GitHub/Integrations/GitHub/GitHub.yml
  Packs/GitHub/Integrations/GitHub/GitHub_test.py
  Packs/GitHub/Integrations/GitHub/README.md
  Packs/GitHub/ReleaseNotes/1_2_5.md
  Packs/GitHub/pack_metadata.json
Labels: docs-approved, release-notes-only

#12094 Unite service desk plus packs
  Packs/ServiceDeskPlus/Integrations/ServiceDeskPlus/README.md
  Packs/ServiceDeskPlus/Integrations/ServiceDeskPlus/ServiceDeskPlus.py
  Packs/ServiceDeskPlus/Integrations/ServiceDeskPlus/ServiceDeskPlus.yml
  Packs/ServiceDeskPlus/Integrations/ServiceDeskPlus/ServiceDeskPlus_description.md
  Packs/ServiceDeskPlus/Integrations/ServiceDeskPlus/ServiceDeskPlus_test.py
  Packs/ServiceDeskPlus/ReleaseNotes/2_0_0.md
  Packs/ServiceDeskPlus/pack_metadata.json
  Packs/ServiceDeskPlus_On_Premise/Integrations/ServiceDeskPlus_On_Premise/ServiceDeskPlus_On_Premise.yml
  Packs/ServiceDeskPlus_On_Premise/ReleaseNotes/1_0_1.md
  Packs/ServiceDeskPlus_On_Premise/pack_metadata.json
Labels: docs-approved

#12656 bump version
  .circleci/content_release_vars.sh
Labels: docs-approved

#12640 [greynoise-266] Add new Integration "GreyNoise Community"
  Packs/GreyNoise/Integrations/GreyNoise_Community/GreyNoise_Community.py
  Packs/GreyNoise/Integrations/GreyNoise_Community/GreyNoise_Community.yml
  Packs/GreyNoise/Integrations/GreyNoise_Community/GreyNoise_Community_description.md
  Packs/GreyNoise/Integrations/GreyNoise_Community/GreyNoise_Community_image.png
  Packs/GreyNoise/Integrations/GreyNoise_Community/GreyNoise_Community_test.py
  Packs/GreyNoise/Integrations/GreyNoise_Community/README.md
  Packs/GreyNoise/Integrations/GreyNoise_Community/test_data/input_data.py
  Packs/GreyNoise/README.md
  Packs/GreyNoise/ReleaseNotes/1_0_2.md
  Packs/GreyNoise/pack_metadata.json
Labels: Contribution, Partner, docs-approved

#12655 Add section_start and section_end helper functions
  .gitlab/ci/global.yml
  .gitlab/helper_functions.sh
Labels: docs-approved

#12665 Build requirements - lock PyGithub
  .circleci/build-requirements.txt
Labels: docs-approved

#12663 fixing validation
  Tests/scripts/validate_premium_packs.py
Labels: docs-approved

#12666 Add link to EWS V2 Troubleshooting information
  Packs/EWS/Integrations/EWSv2/README.md
Labels: docs-approved

#12436 More info about the ioc key
  Packs/ThreatGrid/Integrations/ThreatGrid/ThreatGrid.py
  Packs/ThreatGrid/ReleaseNotes/1_2_2.md
  Packs/ThreatGrid/pack_metadata.json
Labels: bug, docs-approved, release-notes-only

#12629 URL apostrophes bug fix
  Packs/Base/TestPlaybooks/playbook-Indicators-reputation-.json-Test.yml
  Packs/CommonTypes/IndicatorTypes/reputation-url.json
  Packs/CommonTypes/ReleaseNotes/2_9_1.md
  Packs/CommonTypes/pack_metadata.json
Labels: bug, docs-approved, release-notes-only

#12258 Email campaign context key
  Packs/Campaign/ReleaseNotes/1_1_0.md
  Packs/Campaign/Scripts/FindEmailCampaign/FindEmailCampaign.py
  Packs/Campaign/Scripts/FindEmailCampaign/FindEmailCampaign.yml
  Packs/Campaign/Scripts/FindEmailCampaign/FindEmailCampaign_test.py
  Packs/Campaign/pack_metadata.json
Labels: docs-approved

#12559 added more types to remove_code_files function
  Tests/scripts/utils/collect_helpers.py
  Tests/scripts/utils/get_modified_files_for_testing.py
  Tests/scripts/utils/tests/test_get_modified_files_for_testing.py
Labels: docs-approved

#12382 IPinfo v2
  Packs/Base/ReleaseNotes/1_10_27.md
  Packs/Base/Scripts/CommonServerPython/CommonServerPython.py
  Packs/Base/pack_metadata.json
  Packs/ipinfo/Integrations/ipinfo/README.md
  Packs/ipinfo/Integrations/ipinfo/ipinfo.yml
  Packs/ipinfo/Integrations/ipinfo_v2/Pipfile
  Packs/ipinfo/Integrations/ipinfo_v2/Pipfile.lock
  Packs/ipinfo/Integrations/ipinfo_v2/README.md
  Packs/ipinfo/Integrations/ipinfo_v2/command_examples
  Packs/ipinfo/Integrations/ipinfo_v2/ipinfo_v2.py
  Packs/ipinfo/Integrations/ipinfo_v2/ipinfo_v2.yml
  Packs/ipinfo/Integrations/ipinfo_v2/ipinfo_v2_description.md
  Packs/ipinfo/Integrations/ipinfo_v2/ipinfo_v2_image.png
  Packs/ipinfo/Integrations/ipinfo_v2/ipinfo_v2_test.py
  Packs/ipinfo/Integrations/ipinfo_v2/test_data/ip_1.1.1.1_command_results.json
  Packs/ipinfo/Integrations/ipinfo_v2/test_data/ip_1.1.1.1_response.json
  Packs/ipinfo/ReleaseNotes/2_0_0.md
  Packs/ipinfo/TestPlaybooks/playbook-IPinfo_v2_Test.yml
  Packs/ipinfo/pack_metadata.json
  TestPlaybooks/NonCircleTests/Deprecated/playbook-DocumentationTest.yml
  Tests/conf.json
Labels: docs-approved

#12668 Fix Typo in should_lint_all.sh
  Tests/scripts/should_lint_all.sh
Labels: docs-approved

#12148 Github integration update to fetch PR's as incidents,with additional …
  Packs/GitHub/Integrations/GitHub/GitHub.py
  Packs/GitHub/Integrations/GitHub/GitHub.yml
  Packs/GitHub/ReleaseNotes/1_2_6.md
  Packs/GitHub/pack_metadata.json
Labels: Contribution, docs-approved

#12657 prisma cloud readme: fix broken links
  Packs/PrismaCloud/Integrations/RedLock/README.md
Labels: docs-approved

#12681 Updated integration image and added Author_image. Also changed link to website inREADME.md.
  Packs/FeedIntel471/Author_image.png
  Packs/FeedIntel471/Integrations/Intel471Actors/Intel471Actors_image.png
  Packs/FeedIntel471/Integrations/Intel471Malware/Intel471Malware_image.png
  Packs/FeedIntel471/README.md
  Packs/FeedIntel471/ReleaseNotes/1_2_1.md
  Packs/FeedIntel471/pack_metadata.json
Labels: Contribution, Partner, docs-approved

#12692 BeyondTrust Password Safe README - change incident to credential
  Packs/BeyondTrust_Password_Safe/Integrations/BeyondTrust_Password_Safe/README.md
Labels: docs-approved

#12516 Update PCAP Analysis PCAP_File_Carving playbook and layout
  Packs/PcapAnalysis/Layouts/layout-details-PCAP_Analysis.json
  Packs/PcapAnalysis/Layouts/layoutscontainer-PCAP_Analysis.json
  Packs/PcapAnalysis/Playbooks/playbook-PCAP_File_Carving.yml
  Packs/PcapAnalysis/Playbooks/playbook-PCAP_File_Carving_README.md
  Packs/PcapAnalysis/ReleaseNotes/2_4_0.md
  Packs/PcapAnalysis/doc_files/PCAP_File_Carving.png
  Packs/PcapAnalysis/pack_metadata.json
Labels: docs-approved

#12694 Update build related codeowners
  .github/CODEOWNERS
Labels: docs-approved

#12653 SailPointIdentityIQ & SailPointIdentityNow - add secrets ignore
  Packs/SailPointIdentityIQ/.secrets-ignore
  Packs/SailPointIdentityNow/.secrets-ignore
Labels: docs-approved

#12696 Empty readme check add pack ignore
  Packs/NutanixHypervisor/README.md
  Packs/Trello/README.md
  Packs/trendMicroDsm/.pack-ignore
Labels: docs-approved

#12420 GitHub Add Get PRs Of Branch Command
  Packs/GitHub/Integrations/GitHub/GitHub.py
  Packs/GitHub/Integrations/GitHub/GitHub.yml
  Packs/GitHub/Integrations/GitHub/GitHub_test.py
  Packs/GitHub/Integrations/GitHub/README.md
  Packs/GitHub/Integrations/GitHub/command_examples
  Packs/GitHub/Integrations/GitHub/test_data/get-branch-pull-requests-response.json
  Packs/GitHub/ReleaseNotes/1_2_7.md
  Packs/GitHub/TestPlaybooks/playbook-Git_Integration-Test.yml
  Packs/GitHub/pack_metadata.json
Labels: docs-approved, release-notes-only

#12690 Url scan remove not needed relationships
  Packs/UrlScan/Integrations/UrlScan/UrlScan.py
  Packs/UrlScan/ReleaseNotes/1_1_6.md
  Packs/UrlScan/pack_metadata.json
Labels: docs-approved

#12680 fixing validation
  Tests/scripts/validate_premium_packs.py
Labels: docs-approved

#12705 Update contribution team
  Utils/github_workflow_scripts/handle_external_pr.py
Labels: docs-approved

#12702 Change ExampleJSScript to work against reachable domain
  Packs/CommonScripts/ReleaseNotes/1_3_45.md
  Packs/CommonScripts/Scripts/script-ExampleJSScript.yml
  Packs/CommonScripts/pack_metadata.json
Labels: docs-approved

#12689 tim processing: removing broken link
  Packs/TIM_Processing/README.md
Labels: docs-approved

#12714 Misp update search attributes
  Packs/MISP/Integrations/MISP_V2/MISP_V2.py
  Packs/MISP/ReleaseNotes/1_0_9.md
  Packs/MISP/pack_metadata.json
Labels: docs-approved, release-notes-only
