Repository demisto/content, pull requests merged in 2022-02, with the labels that each got.

#17387 Trend Micro - adjust pack/integration display
  Packs/TrendMicroCAS/Integrations/TrendMicroCAS/TrendMicroCAS.yml
  Packs/TrendMicroCAS/ReleaseNotes/1_0_7.md
  Packs/TrendMicroCAS/pack_metadata.json
Labels: docs-approved

#17374 Azure Identity Protection - update required permissions link in detailed desc
  Packs/AzureActiveDirectory/Integrations/AzureADIdentityProtection/AzureADIdentityProtection_description.md
  Packs/AzureActiveDirectory/ReleaseNotes/1_2_1.md
  Packs/AzureActiveDirectory/pack_metadata.json
Labels: docs-approved

#17343 Aburt-gmail-improvement
  Packs/GmailSingleUser/Integrations/GmailSingleUser/GmailSingleUser.py
  Packs/GmailSingleUser/Integrations/GmailSingleUser/GmailSingleUser.yml
  Packs/GmailSingleUser/Integrations/GmailSingleUser/GmailSingleUser_description.md
  Packs/GmailSingleUser/ReleaseNotes/1_2_0.md
  Packs/GmailSingleUser/pack_metadata.json
Labels: Contribution, docs-approved

#17397 Update .pack-ignore
  Packs/TrendMicroDDA/.pack-ignore
Labels: docs-approved

#17392 Unskip test_MsGraphFiles prod TPB
  Packs/MicrosoftGraphFiles/TestPlaybooks/test_MsGraphFiles_prod.yml
  Tests/conf.json
Labels: docs-approved

#17382 adding marketplaces
  Packs/CommonTypes/IncidentFields/incidentfield-Appliance_ID.json
  Packs/CommonTypes/IncidentFields/incidentfield-Appliance_Name.json
  Packs/CommonTypes/IncidentFields/incidentfield-Destination_Network.json
  Packs/CommonTypes/IncidentFields/incidentfield-Parent_CMD_line.json
  Packs/CommonTypes/IncidentFields/incidentfield-Parent_Process.json
  Packs/CommonTypes/IncidentFields/incidentfield-Protocol.json
  Packs/CommonTypes/IncidentFields/incidentfield-Protocols.json
  Packs/CommonTypes/IncidentFields/incidentfield-Src_OS.json
  Packs/CommonTypes/ReleaseNotes/3_2_5.md
  Packs/CommonTypes/pack_metadata.json
  Packs/Phishing/IncidentFields/incidentfield-Email_From.json
  Packs/Phishing/IncidentFields/incidentfield-Email_Subject.json
  Packs/Phishing/IncidentFields/incidentfield-Email_To.json
  Packs/Phishing/ReleaseNotes/3_1_2.md
  Packs/Phishing/pack_metadata.json
Labels: docs-approved

#17398 esm_v2_eol_update
  Packs/McAfee_ESM/Integrations/McAfee_ESM_v2/README.md
Labels: docs-approved

#16532 Qualys v2 enhancement
  Packs/qualys/.secrets-ignore
  Packs/qualys/Integrations/Qualysv2/Qualysv2.py
  Packs/qualys/Integrations/Qualysv2/Qualysv2.yml
  Packs/qualys/Integrations/Qualysv2/Qualysv2_test.py
  Packs/qualys/Integrations/Qualysv2/README.md
  Packs/qualys/Integrations/Qualysv2/command_examples
  Packs/qualys/ReleaseNotes/1_0_16.md
  Packs/qualys/TestPlaybooks/QualysVulnerabilityManagement-Test.yml
  Packs/qualys/pack_metadata.json
  Tests/conf.json
  Tests/known_words.txt
Labels: docs-approved

#17408 Corealertfields fix
  Packs/CommonTypes/IncidentFields/incidentfield-File_SHA256.json
  Packs/CommonTypes/ReleaseNotes/3_2_6.md
  Packs/CommonTypes/pack_metadata.json
  Packs/CoreAlertFields/IncidentFields/incidentfield-Action.json
  Packs/CoreAlertFields/ReleaseNotes/1_0_1.md
  Packs/CoreAlertFields/pack_metadata.json
  Packs/FireMonSecurityManager/IncidentFields/incidentfield-FireMonSecurityManager-Action.json
  Packs/FireMonSecurityManager/ReleaseNotes/1_0_3.md
  Packs/FireMonSecurityManager/pack_metadata.json
  Packs/Malware/pack_metadata.json
Labels: docs-approved

#17390 Update README to include video
  Packs/ContentManagement/README.md
Labels: Contribution, docs-approved

#17410 Salesforce contribution branch fixed
  Packs/SalesforceIndicators/Integrations/SalesforceIndicators/SalesforceIndicators.py
  Packs/SalesforceIndicators/Integrations/SalesforceIndicators/SalesforceIndicators.yml
  Packs/SalesforceIndicators/ReleaseNotes/1_0_5.md
  Packs/SalesforceIndicators/pack_metadata.json
Labels: Contribution, docs-approved

#17191 Validate if build related files are up to date correctly
  .circleci/config.yml
  .gitlab/ci/global.yml
  Tests/scripts/is_file_up_to_date.sh
Labels: docs-approved

#17401 AWS S3 improve list objects command
  Packs/AWS-S3/Integrations/AWS-S3/AWS-S3.py
  Packs/AWS-S3/Integrations/AWS-S3/AWS-S3.yml
  Packs/AWS-S3/Integrations/AWS-S3/README.md
  Packs/AWS-S3/ReleaseNotes/1_2_0.md
  Packs/AWS-S3/pack_metadata.json
Labels: docs-approved

#17346 Add QRadar v3 to the QRadar_hunting_v2 playbook
  Packs/QRadar/Playbooks/playbook-QRadar_Indicator_Hunting_V2.yml
  Packs/QRadar/ReleaseNotes/2_1_31.md
  Packs/QRadar/pack_metadata.json
  Tests/known_words.txt
Labels: docs-approved, release-notes-only

#17225 Arnarayanan contrib xsoar utils
  Packs/Xsoar_Utils/.pack-ignore
  Packs/Xsoar_Utils/.secrets-ignore
  Packs/Xsoar_Utils/Integrations/XsoarUtils/Pipfile
  Packs/Xsoar_Utils/Integrations/XsoarUtils/Pipfile.lock
  Packs/Xsoar_Utils/Integrations/XsoarUtils/README.md
  Packs/Xsoar_Utils/Integrations/XsoarUtils/XsoarUtils.py
  Packs/Xsoar_Utils/Integrations/XsoarUtils/XsoarUtils.yml
  Packs/Xsoar_Utils/Integrations/XsoarUtils/XsoarUtils_description.md
  Packs/Xsoar_Utils/Integrations/XsoarUtils/XsoarUtils_image.png
  Packs/Xsoar_Utils/README.md
  Packs/Xsoar_Utils/pack_metadata.json
Labels: Contribution, docs-approved, Contribution Form Filled, Community

#17415 dont check if tests is up to date
  .circleci/config.yml
  .gitlab/ci/global.yml
Labels: docs-approved

#17414 Unskipping MailListetner-POP3 Test
  Tests/conf.json
Labels: docs-approved

#17354 Improve documentation for autofocus-search-sessions command
  Packs/AutoFocus/Integrations/AutofocusV2/AutofocusV2.yml
  Packs/AutoFocus/ReleaseNotes/2_0_10.md
  Packs/AutoFocus/pack_metadata.json
Labels: docs-approved

#16771 ParseEmailFiles v2
  Packs/CommonScripts/ReleaseNotes/1_6_30.md
  Packs/CommonScripts/Scripts/ParseEmailFilesV2/ParseEmailFilesV2.py
  Packs/CommonScripts/Scripts/ParseEmailFilesV2/ParseEmailFilesV2.yml
  Packs/CommonScripts/Scripts/ParseEmailFilesV2/ParseEmailFilesV2_test.py
  Packs/CommonScripts/Scripts/ParseEmailFilesV2/README.md
  Packs/CommonScripts/Scripts/ParseEmailFilesV2/test_data/DONT_OPEN-MALICIOUS.eml
  Packs/CommonScripts/Scripts/ParseEmailFilesV2/test_data/Fwd_test-inner_attachment_eml.eml
  Packs/CommonScripts/Scripts/ParseEmailFilesV2/test_data/no_content.eml
  Packs/CommonScripts/Scripts/ParseEmailFilesV2/test_data/no_content_type.eml
  Packs/CommonScripts/Scripts/ParseEmailFilesV2/test_data/smime-p7s.msg
  Packs/CommonScripts/Scripts/ParseEmailFilesV2/test_data/smtp_email_type.eml
  Packs/CommonScripts/TestPlaybooks/playbook-ParseEmailFilesV2-test.yml
  Packs/CommonScripts/pack_metadata.json
  Tests/conf.json
Labels: docs-approved

#17396 fix mac address.json
  Utils/release_notes_generator.py
Labels: docs-approved

#17386 remove Traps test playbook from nightly - deprecated
  Packs/Traps/ReleaseNotes/1_0_9.md
  Packs/Traps/TestPlaybooks/playbook-Traps_test.yml
  Packs/Traps/pack_metadata.json
  Tests/conf.json
Labels: docs-approved, release-notes-only

#16878 support sdk-validate update
  Tests/configure_and_test_integration_instances.py
  dev-requirements-py3.txt
Labels: docs-approved

#17422 1.5.9
  dev-requirements-py3.txt
Labels: docs-approved

#17407 Unit 42 v2 Feed - Added malicious verdict to fetched indicators
  Packs/FeedUnit42v2/Integrations/FeedUnit42v2/FeedUnit42v2.py
  Packs/FeedUnit42v2/Integrations/FeedUnit42v2/FeedUnit42v2_test.py
  Packs/FeedUnit42v2/Integrations/FeedUnit42v2/test_data/feed_data.py
  Packs/FeedUnit42v2/ReleaseNotes/1_0_10.md
  Packs/FeedUnit42v2/pack_metadata.json
Labels: docs-approved

#17367 Update FormatURL.py
  Packs/CommonScripts/ReleaseNotes/1_6_31.md
  Packs/CommonScripts/Scripts/FormatURL/.secrets-ignore
  Packs/CommonScripts/Scripts/FormatURL/FormatURL.py
  Packs/CommonScripts/Scripts/FormatURL/FormatURL.yml
  Packs/CommonScripts/Scripts/FormatURL/FormatURL_test.py
  Packs/CommonScripts/pack_metadata.json
Labels: Contribution, docs-approved, Contribution Form Filled, Community

#17393 Update edl creation script
  Packs/CreateEDLInstance/README.md
  Packs/CreateEDLInstance/ReleaseNotes/1_0_1.md
  Packs/CreateEDLInstance/Scripts/CreateEDLInstance/CreateEDLInstance.py
  Packs/CreateEDLInstance/Scripts/CreateEDLInstance/CreateEDLInstance.yml
  Packs/CreateEDLInstance/Scripts/CreateEDLInstance/README.md
  Packs/CreateEDLInstance/pack_metadata.json
Labels: Contribution, docs-approved, Contribution Form Filled, Community

#17434 Add time measure for nightly lint
  .gitlab/ci/global.yml
Labels: docs-approved

#17373 Add dependencies.zip upload to prod
  Tests/Marketplace/marketplace_services.py
  Utils/trigger_test_upload_flow.sh
Labels: docs-approved

#17379 Remove credentials from SNow CMDB TPB
  Packs/ServiceNow/TestPlaybooks/playbook-ServiceNow_CMDB_OAuth_Test.yml
Labels: docs-approved

#16687 Recorded Future Identity Module Integration with XSOAR
  Packs/IdentityRecordedFuture/.pack-ignore
  Packs/IdentityRecordedFuture/.secrets-ignore
  Packs/IdentityRecordedFuture/Author_image.png
  Packs/IdentityRecordedFuture/Integrations/IdentityRecordedFuture/IdentityRecordedFuture.py
  Packs/IdentityRecordedFuture/Integrations/IdentityRecordedFuture/IdentityRecordedFuture.yml
  Packs/IdentityRecordedFuture/Integrations/IdentityRecordedFuture/IdentityRecordedFuture_description.md
  Packs/IdentityRecordedFuture/Integrations/IdentityRecordedFuture/IdentityRecordedFuture_test.py
  Packs/IdentityRecordedFuture/Integrations/IdentityRecordedFuture/Pipfile
  Packs/IdentityRecordedFuture/Integrations/IdentityRecordedFuture/Pipfile.lock
  Packs/IdentityRecordedFuture/Integrations/IdentityRecordedFuture/README.md
  Packs/IdentityRecordedFuture/Integrations/IdentityRecordedFuture/RecordedFuture_image.png
  Packs/IdentityRecordedFuture/Integrations/IdentityRecordedFuture/example_commands.txt
  Packs/IdentityRecordedFuture/Integrations/IdentityRecordedFuture/test_data/identity_lookup_response.json
  Packs/IdentityRecordedFuture/Integrations/IdentityRecordedFuture/test_data/identity_search_response.json
  Packs/IdentityRecordedFuture/Integrations/IdentityRecordedFuture/test_data/test_client_whoami
  Packs/IdentityRecordedFuture/Playbooks/playbook-Recorded_Future_Identity_External_Usecase.yml
  Packs/IdentityRecordedFuture/Playbooks/playbook-Recorded_Future_Identity_External_Usecase_README.md
  Packs/IdentityRecordedFuture/Playbooks/playbook-Recorded_Future_Identity_Workforce_Usecase.yml
  Packs/IdentityRecordedFuture/Playbooks/playbook-Recorded_Future_Identity_Workforce_Usecase_README.md
  Packs/IdentityRecordedFuture/README.md
  Packs/IdentityRecordedFuture/TestPlaybooks/TestIdentityRecordedFuture.yml
  Packs/IdentityRecordedFuture/doc_files/external_playbook.png
  Packs/IdentityRecordedFuture/doc_files/workforce_playbook.png
  Packs/IdentityRecordedFuture/pack_metadata.json
Labels: Contribution, docs-approved, Partner, pending-demo, Contribution Form Filled

#17441 change the demisto-sdk version in requirements
  dev-requirements-py3.txt
Labels: docs-approved

#17446 MPv2: add CoreAlertFields as core pack in mpv2
  Tests/Marketplace/core_packs_mpv2_list.json
Labels: docs-approved

#17412 Red canary test fix
  Packs/RedCanary/TestPlaybooks/playbook-RedCanaryTest.yml
  Tests/conf.json
Labels: docs-approved

#17448 unskip microsoft teams managmenet test playbook
  Tests/conf.json
Labels: docs-approved

#17444 fixed test playbook MicrosoftManagement
  Packs/MicrosoftManagementActivity/TestPlaybooks/MicrosoftManagementActivity_-_Test.yml
Labels: docs-approved

#17450 Upload Flow: marketplace flag fixes
  Tests/Marketplace/copy_and_upload_packs.py
  Tests/Marketplace/upload_packs.py
  Tests/scripts/collect_tests_and_content_packs.py
  Tests/scripts/prepare_content_packs_for_testing.sh
  Utils/trigger_test_upload_flow.sh
  dev-requirements-py3.txt
Labels: docs-approved

#17439 Url format logging improvements
  Packs/CommonScripts/ReleaseNotes/1_6_31.md
  Packs/CommonScripts/Scripts/FormatURL/FormatURL.py
  Packs/CommonScripts/Scripts/FormatURL/FormatURL.yml
  Packs/CommonScripts/pack_metadata.json
Labels: docs-approved

#17466 adding core alert fields as a dependency
  Packs/Phishing/pack_metadata.json
Labels: docs-approved

#17469 switch id
  Tests/conf.json
Labels: docs-approved

#17437 Update argument description for ServiceNow Ticket State Polling
  Packs/ServiceNow/Playbooks/playbook-Create_ServiceNow_Ticket.yml
  Packs/ServiceNow/Playbooks/playbook-ServiceNow_Ticket_State_Polling.yml
  Packs/ServiceNow/ReleaseNotes/2_2_27.md
  Packs/ServiceNow/pack_metadata.json
  Tests/known_words.txt
Labels: docs-approved

#17477 Core alert fields remove grids
  Packs/CommonTypes/IncidentFields/incidentfield-Hostnames.json
  Packs/CommonTypes/ReleaseNotes/3_2_11.md
  Packs/CommonTypes/pack_metadata.json
  Packs/CoreAlertFields/IncidentFields/incidentfield-Hostname.json
  Packs/CoreAlertFields/IncidentFields/incidentfield-User_name.json
  Packs/CoreAlertFields/ReleaseNotes/1_0_6.md
  Packs/CoreAlertFields/pack_metadata.json
Labels: docs-approved

#17453 Core alert fields aliases _ part 3 (sasha)
  Packs/Campaign/IncidentFields/incidentfield-Campaign_Email_To.json
  Packs/Campaign/ReleaseNotes/3_2_6.md
  Packs/Campaign/pack_metadata.json
  Packs/CoreAlertFields/IncidentFields/incidentfield-Email_Recipient.json
  Packs/CoreAlertFields/IncidentFields/incidentfield-Email_Sender.json
  Packs/CoreAlertFields/IncidentFields/incidentfield-Event_Type.json
  Packs/CoreAlertFields/IncidentFields/incidentfield-FW_Name.json
  Packs/CoreAlertFields/IncidentFields/incidentfield-FW_Rule_Name.json
  Packs/CoreAlertFields/IncidentFields/incidentfield-FW_Serial_Number.json
  Packs/CoreAlertFields/IncidentFields/incidentfield-Host_FQDN.json
  Packs/CoreAlertFields/IncidentFields/incidentfield-Initiated_By.json
  Packs/CoreAlertFields/ReleaseNotes/1_0_7.md
  Packs/CoreAlertFields/pack_metadata.json
  Packs/DigitalGuardian/IncidentFields/incidentfield-Digital_Guardian_Email_Recipient.json
  Packs/DigitalGuardian/ReleaseNotes/1_0_12.md
  Packs/DigitalGuardian/pack_metadata.json
  Packs/ExtraHop/IncidentFields/incidentfield-ExtraHop_Appliance_ID.json
  Packs/ExtraHop/ReleaseNotes/1_0_13.md
  Packs/ExtraHop/pack_metadata.json
  Packs/F5Silverline/IncidentFields/incident_f5silverlineirulename.json
  Packs/F5Silverline/ReleaseNotes/1_0_10.md
  Packs/F5Silverline/pack_metadata.json
  Packs/GoogleCloudSCC/IncidentFields/incidentfield-GoogleCloudSCC_Finding_SourceProperties_EventType.json
  Packs/GoogleCloudSCC/ReleaseNotes/2_0_3.md
  Packs/GoogleCloudSCC/pack_metadata.json
  Packs/Lacework/IncidentFields/incidentfield-Lacework_Event_Type.json
  Packs/Lacework/ReleaseNotes/1_1_2.md
  Packs/Lacework/pack_metadata.json
  Packs/PANOStoCDLMonitoring/IncidentFields/incidentfield-fw_serials.json
  Packs/PANOStoCDLMonitoring/ReleaseNotes/1_0_9.md
  Packs/PANOStoCDLMonitoring/pack_metadata.json
  Packs/PrismaCloudCompute/IncidentFields/incidentfield-Prisma_Cloud_Compute_FQDN.json
  Packs/PrismaCloudCompute/ReleaseNotes/1_2_5.md
  Packs/PrismaCloudCompute/pack_metadata.json
  Packs/ProofpointTAP/IncidentFields/incidentfield-ProofPointTAP_SMTP_Recipient.json
  Packs/ProofpointTAP/ReleaseNotes/1_1_12.md
  Packs/ProofpointTAP/pack_metadata.json
  Packs/QualysFIM/IncidentFields/incidentfield-Qualys_FIM_Event_Type.json
  Packs/QualysFIM/ReleaseNotes/1_0_6.md
  Packs/QualysFIM/pack_metadata.json
  Packs/RiskIQDigitalFootprint/IncidentFields/incidentfield-RiskIQ_Asset_GCP_Firewall_Name.json
  Packs/RiskIQDigitalFootprint/ReleaseNotes/1_0_14.md
  Packs/RiskIQDigitalFootprint/pack_metadata.json
  Packs/SolarWinds/IncidentFields/incidentfield-SolarWinds-Event-Type.json
  Packs/SolarWinds/ReleaseNotes/1_0_4.md
  Packs/SolarWinds/pack_metadata.json
  Packs/TaniumThreatResponse/IncidentFields/incidentfield-TaniumTR-taniumtype.json
  Packs/TaniumThreatResponse/ReleaseNotes/2_0_9.md
  Packs/TaniumThreatResponse/pack_metadata.json
  Packs/knowbe4Phisher/IncidentFields/incidentfield-PhishERemailfrom.json
  Packs/knowbe4Phisher/ReleaseNotes/1_0_5.md
  Packs/knowbe4Phisher/pack_metadata.json
  Packs/mnemonicMDR/IncidentFields/incidentfield-Argus_Event_Type.json
  Packs/mnemonicMDR/ReleaseNotes/1_1_3.md
  Packs/mnemonicMDR/pack_metadata.json
Labels: docs-approved

#17480 change field types
  Packs/CoreAlertFields/IncidentFields/incidentfield-Action.json
  Packs/CoreAlertFields/IncidentFields/incidentfield-Agent_OS_Sub_Type.json
  Packs/CoreAlertFields/IncidentFields/incidentfield-Category.json
  Packs/CoreAlertFields/IncidentFields/incidentfield-Domain.json
  Packs/CoreAlertFields/IncidentFields/incidentfield-Host_FQDN.json
  Packs/CoreAlertFields/IncidentFields/incidentfield-Host_Mac_address.json
  Packs/CoreAlertFields/IncidentFields/incidentfield-Host_OS.json
  Packs/CoreAlertFields/IncidentFields/incidentfield-Hostname.json
  Packs/CoreAlertFields/IncidentFields/incidentfield-containsfeaturedhost.json
  Packs/CoreAlertFields/IncidentFields/incidentfield-containsfeaturedipaddress.json
  Packs/CoreAlertFields/IncidentFields/incidentfield-containsfeatureduser.json
  Packs/CoreAlertFields/IncidentFields/incidentfield-isphishing.json
  Packs/CoreAlertFields/IncidentFields/incidentfield-ruleid.json
  Packs/CoreAlertFields/ReleaseNotes/1_0_8.md
  Packs/CoreAlertFields/pack_metadata.json
Labels: docs-approved

#17482 Missing dependencies bug fix
  Tests/Marketplace/Tests/upload_packs_test.py
  Tests/Marketplace/marketplace_services.py
  Tests/Marketplace/marketplace_statistics.py
  Tests/Marketplace/upload_packs.py
  Tests/private_build/upload_packs_private.py
Labels: docs-approved

#17019 Added a comment to content PR's with a link to the unit test coverage report
  .gitlab/ci/global.yml
  Tests/scripts/add_pr_comment.py
  Tests/secrets_white_list.json
Labels: docs-approved

#17206 Open Source Vulnerabilities Integration
  Packs/OpenSourceVulnerabilities/.pack-ignore
  Packs/OpenSourceVulnerabilities/.secrets-ignore
  Packs/OpenSourceVulnerabilities/Author_image.png
  Packs/OpenSourceVulnerabilities/Integrations/OSV/OSV.py
  Packs/OpenSourceVulnerabilities/Integrations/OSV/OSV.yml
  Packs/OpenSourceVulnerabilities/Integrations/OSV/OSV_description.md
  Packs/OpenSourceVulnerabilities/Integrations/OSV/OSV_image.png
  Packs/OpenSourceVulnerabilities/Integrations/OSV/Pipfile
  Packs/OpenSourceVulnerabilities/Integrations/OSV/Pipfile.lock
  Packs/OpenSourceVulnerabilities/Integrations/OSV/README.md
  Packs/OpenSourceVulnerabilities/Integrations/OSV/command_examples
  Packs/OpenSourceVulnerabilities/README.md
  Packs/OpenSourceVulnerabilities/pack_metadata.json
Labels: Contribution, docs-approved, post-demo, Contribution Form Filled, Community

#17326 Added a feature to convert STIX Cyber Observable Objects to STIX Domain Object of 'indicator' so that the Microsoft Azure Sentinel TAXII Connector can feed indicators.
  Packs/TAXIIServer/Integrations/TAXII2Server/TAXII2Server.py
  Packs/TAXIIServer/Integrations/TAXII2Server/TAXII2Server.yml
  Packs/TAXIIServer/Integrations/TAXII2Server/TAXII2Server_test.py
  Packs/TAXIIServer/Integrations/TAXII2Server/test_files/objects20-indicators.json
  Packs/TAXIIServer/ReleaseNotes/2_0_2.md
  Packs/TAXIIServer/pack_metadata.json
Labels: Contribution, docs-approved, post-demo, Contribution Form Filled, Community

#17436 Update edl creation script (#17393)
  Packs/CreateEDLInstance/README.md
  Packs/CreateEDLInstance/ReleaseNotes/1_0_1.md
  Packs/CreateEDLInstance/Scripts/CreateEDLInstance/CreateEDLInstance.py
  Packs/CreateEDLInstance/Scripts/CreateEDLInstance/CreateEDLInstance.yml
  Packs/CreateEDLInstance/Scripts/CreateEDLInstance/README.md
  Packs/CreateEDLInstance/pack_metadata.json
Labels: docs-approved

#17426 Remove enrichment tasks in extract create relationship RSS feed playbook
  Packs/FeedRSS/Playbooks/Extract_and_Create_Relationships.yml
  Packs/FeedRSS/ReleaseNotes/1_0_2.md
  Packs/FeedRSS/doc_files/Extract_and_create_relationships_playbook_image.png
  Packs/FeedRSS/pack_metadata.json
Labels: docs-approved

#17385 Pan Optimizer Rules Query Bug
  Packs/PANOSPolicyOptimizer/Integrations/PANOSPolicyOptimizer/PANOSPolicyOptimizer.py
  Packs/PANOSPolicyOptimizer/Integrations/PANOSPolicyOptimizer/PANOSPolicyOptimizer.yml
  Packs/PANOSPolicyOptimizer/Integrations/PANOSPolicyOptimizer/PANOSPolicyOptimizer_test.py
  Packs/PANOSPolicyOptimizer/Integrations/PANOSPolicyOptimizer/test_data/valid_security_rules_response.json
  Packs/PANOSPolicyOptimizer/ReleaseNotes/1_0_4.md
  Packs/PANOSPolicyOptimizer/pack_metadata.json
Labels: docs-approved

#16690 Trigger contrib build
  .github/workflows/trigger-contribution-build.yml
  Packs/DevSecOps/Integrations/GitLab/GitLab.py
  Packs/DevSecOps/Integrations/GitLab/GitLab.yml
  Packs/DevSecOps/Integrations/GitLab/GitLab_test.py
  Packs/DevSecOps/Integrations/GitLab/test_data/commands_test_data.json
  Packs/DevSecOps/ReleaseNotes/1_0_8.md
  Packs/DevSecOps/pack_metadata.json
  Packs/GitHub/Integrations/GitHub/GitHub.py
  Packs/GitHub/Integrations/GitHub/GitHub.yml
  Packs/GitHub/ReleaseNotes/1_3_14.md
  Packs/GitHub/pack_metadata.json
  Tests/known_words.txt
  Utils/github_workflow_scripts/trigger_contribution_build.py
Labels: docs-approved

#17476 Rf CVE
  Packs/FeedRecordedFuture/Integrations/FeedRecordedFuture/FeedRecordedFuture.py
  Packs/FeedRecordedFuture/Integrations/FeedRecordedFuture/FeedRecordedFuture.yml
  Packs/FeedRecordedFuture/Integrations/FeedRecordedFuture/FeedRecordedFuture_description.md
  Packs/FeedRecordedFuture/Integrations/FeedRecordedFuture/FeedRecordedFuture_test.py
  Packs/FeedRecordedFuture/Integrations/FeedRecordedFuture/README.md
  Packs/FeedRecordedFuture/Integrations/FeedRecordedFuture/test_data/response_risk_score.txt
  Packs/FeedRecordedFuture/ReleaseNotes/1_0_21.md
  Packs/FeedRecordedFuture/pack_metadata.json
Labels: docs-approved

#17399 skipping outsourced integrations
  Tests/conf.json
Labels: docs-approved

#17505 [Infra] Add resilience in test collection for non-versioned zip files
  Tests/Marketplace/Tests/search_and_install_packs_test.py
  Tests/Marketplace/search_and_install_packs.py
Labels: docs-approved

#17472 Fix NoneType error in CrowdStrikeFalcon `endpoint` command
  Packs/CrowdStrikeFalcon/Integrations/CrowdStrikeFalcon/CrowdStrikeFalcon.py
  Packs/CrowdStrikeFalcon/ReleaseNotes/1_4_6.md
  Packs/CrowdStrikeFalcon/pack_metadata.json
Labels: docs-approved

#17504 Microsoft Cloud App Security - API token obtaining documentation
  Packs/MicrosoftCloudAppSecurity/Integrations/MicrosoftCloudAppSecurity/MicrosoftCloudAppSecurity.py
  Packs/MicrosoftCloudAppSecurity/Integrations/MicrosoftCloudAppSecurity/README.md
  Packs/MicrosoftCloudAppSecurity/ReleaseNotes/1_0_26.md
  Packs/MicrosoftCloudAppSecurity/pack_metadata.json
Labels: docs-approved

#17507 FireEye - Increasing the validity of the API Key
  Packs/ApiModules/Scripts/FireEyeApiModule/FireEyeApiModule.py
  Packs/FireEyeCM/Integrations/FireEyeCM/FireEyeCM_description.md
  Packs/FireEyeCM/Integrations/FireEyeCM/README.md
  Packs/FireEyeCM/ReleaseNotes/1_1_8.md
  Packs/FireEyeCM/pack_metadata.json
  Packs/FireEyeEX/Integrations/FireEyeEX/FireEyeEX_description.md
  Packs/FireEyeEX/Integrations/FireEyeEX/README.md
  Packs/FireEyeEX/ReleaseNotes/2_0_5.md
  Packs/FireEyeEX/pack_metadata.json
Labels: docs-approved

#17282 Joe security add types reference to readme
  Packs/JoeSecurity/Integrations/JoeSecurity/JoeSecurity.yml
  Packs/JoeSecurity/Integrations/JoeSecurity/README.md
  Packs/JoeSecurity/ReleaseNotes/1_0_9.md
  Packs/JoeSecurity/pack_metadata.json
Labels: docs-approved

#17503 Cortex XDR - IR Audit management logs fix
  Packs/CortexXDR/Integrations/CortexXDRIR/CortexXDRIR.yml
  Packs/CortexXDR/ReleaseNotes/4_2_17.md
  Packs/CortexXDR/pack_metadata.json
Labels: docs-approved

#16931 Trend Micro Vision One
  Packs/TrendMicroVisionOne/.pack-ignore
  Packs/TrendMicroVisionOne/.secrets-ignore
  Packs/TrendMicroVisionOne/Author_image.png
  Packs/TrendMicroVisionOne/Classifiers/classifier-Trend_Micro_Vision_One_XDR_-_Incoming_Mapper.json
  Packs/TrendMicroVisionOne/IncidentFields/incidentfield-Trend_Micro_Vision_One_XDR_Account_Count.json
  Packs/TrendMicroVisionOne/IncidentFields/incidentfield-Trend_Micro_Vision_One_XDR_Desktop_Count.json
  Packs/TrendMicroVisionOne/IncidentFields/incidentfield-Trend_Micro_Vision_One_XDR_Detail.json
  Packs/TrendMicroVisionOne/IncidentFields/incidentfield-Trend_Micro_Vision_One_XDR_Email_Address_Count.json
  Packs/TrendMicroVisionOne/IncidentFields/incidentfield-Trend_Micro_Vision_One_XDR_Impact_Scope.json
  Packs/TrendMicroVisionOne/IncidentFields/incidentfield-Trend_Micro_Vision_One_XDR_Impacted_Entities.json
  Packs/TrendMicroVisionOne/IncidentFields/incidentfield-Trend_Micro_Vision_One_XDR_Indicators.json
  Packs/TrendMicroVisionOne/IncidentFields/incidentfield-Trend_Micro_Vision_One_XDR_Investigation_Status.json
  Packs/TrendMicroVisionOne/IncidentFields/incidentfield-Trend_Micro_Vision_One_XDR_Priority_Score.json
  Packs/TrendMicroVisionOne/IncidentFields/incidentfield-Trend_Micro_Vision_One_XDR_Server_Count.json
  Packs/TrendMicroVisionOne/IncidentFields/incidentfield-Trend_Micro_Vision_One_XDR_Workbench_ID.json
  Packs/TrendMicroVisionOne/IncidentFields/incidentfield-Trend_Micro_Vision_One_XDR_Workbench_Link.json
  Packs/TrendMicroVisionOne/IncidentTypes/incidenttype-Trend_Micro_Vision_One_XDR_Incident.json
  Packs/TrendMicroVisionOne/Integrations/TrendMicroVisionOne/Pipfile
  Packs/TrendMicroVisionOne/Integrations/TrendMicroVisionOne/Pipfile.lock
  Packs/TrendMicroVisionOne/Integrations/TrendMicroVisionOne/README.md
  Packs/TrendMicroVisionOne/Integrations/TrendMicroVisionOne/TrendMicroVisionOne.py
  Packs/TrendMicroVisionOne/Integrations/TrendMicroVisionOne/TrendMicroVisionOne.yml
  Packs/TrendMicroVisionOne/Integrations/TrendMicroVisionOne/TrendMicroVisionOne_description.md
  Packs/TrendMicroVisionOne/Integrations/TrendMicroVisionOne/TrendMicroVisionOne_image.png
  Packs/TrendMicroVisionOne/Integrations/TrendMicroVisionOne/TrendMicroVisionOne_test.py
  Packs/TrendMicroVisionOne/Integrations/TrendMicroVisionOne/command_examples
  Packs/TrendMicroVisionOne/Layouts/layoutscontainer-Trend_Micro_Vision_One_XDR_Incident.json
  Packs/TrendMicroVisionOne/README.md
  Packs/TrendMicroVisionOne/pack_metadata.json
  Tests/demistomock/demistomock.py
Labels: Contribution, docs-approved, Partner, Contribution Form Filled

#17313 Enable mpv2 jobs
  .gitlab/ci/bucket-upload.yml
  .gitlab/ci/global.yml
  .gitlab/ci/on-push.yml
  Tests/Marketplace/marketplace_services.py
  Tests/scripts/gitlab_slack_notifier.py
Labels: docs-approved

#17510 Field fixes
  Packs/AgariPhishingDefense/IncidentFields/incidentfield-APD_Policy_Action.json
  Packs/AgariPhishingDefense/ReleaseNotes/1_0_10.md
  Packs/AgariPhishingDefense/pack_metadata.json
  Packs/CommonTypes/IncidentFields/incidentfield-Alert_Action.json
  Packs/CommonTypes/IncidentFields/incidentfield-Blocked_Action.json
  Packs/CommonTypes/IncidentFields/incidentfield-Dest_OS.json
  Packs/CommonTypes/IncidentFields/incidentfield-Destination_IPs.json
  Packs/CommonTypes/IncidentFields/incidentfield-OS.json
  Packs/CommonTypes/IncidentFields/incidentfield-Src_OS.json
  Packs/CommonTypes/IncidentFields/incidentfield-Usernames.json
  Packs/CommonTypes/ReleaseNotes/3_2_12.md
  Packs/CommonTypes/pack_metadata.json
  Packs/CoreAlertFields/IncidentFields/incidentfield-Action.json
  Packs/CoreAlertFields/IncidentFields/incidentfield-Event_Type.json
  Packs/CoreAlertFields/IncidentFields/incidentfield-Host_OS.json
  Packs/CoreAlertFields/IncidentFields/incidentfield-User_name.json
  Packs/CoreAlertFields/ReleaseNotes/1_0_9.md
  Packs/CoreAlertFields/pack_metadata.json
  Packs/Cymulate/IncidentFields/incidentfield-Cymulate_Cymulate_Last_Action.json
  Packs/Cymulate/ReleaseNotes/2_0_12.md
  Packs/Cymulate/pack_metadata.json
  Packs/DevSecOps/IncidentFields/DevSecOps_App_Task_Action.json
  Packs/DevSecOps/IncidentFields/DevSecOps_PR_Action.json
  Packs/DevSecOps/ReleaseNotes/1_0_9.md
  Packs/DevSecOps/pack_metadata.json
  Packs/F5Silverline/IncidentFields/incident_f5silverlineaction.json
  Packs/F5Silverline/ReleaseNotes/1_0_11.md
  Packs/F5Silverline/pack_metadata.json
  Packs/FireEyeNX/IncidentFields/incidentfield-FireEye_NX_Alert_Action.json
  Packs/FireEyeNX/ReleaseNotes/1_0_11.md
  Packs/FireEyeNX/pack_metadata.json
  Packs/GoogleCloudSCC/IncidentFields/incidentfield-GoogleCloudSCC_Finding_SourceProperties_EventType.json
  Packs/GoogleCloudSCC/ReleaseNotes/2_0_4.md
  Packs/GoogleCloudSCC/pack_metadata.json
  Packs/IllusiveNetworks/IncidentFields/incidentfield-Illusive_Networks_Source_Operating_System.json
  Packs/IllusiveNetworks/ReleaseNotes/1_0_15.md
  Packs/IllusiveNetworks/pack_metadata.json
  Packs/Lacework/IncidentFields/incidentfield-Lacework_Event_Type.json
  Packs/Lacework/ReleaseNotes/1_1_3.md
  Packs/Lacework/pack_metadata.json
  Packs/LogPoint_SIEM_Integration/IncidentFields/incidentfield-LogPoint_SIEM_Integration_Last_Action.json
  Packs/LogPoint_SIEM_Integration/ReleaseNotes/1_2_6.md
  Packs/LogPoint_SIEM_Integration/pack_metadata.json
  Packs/QualysFIM/IncidentFields/incidentfield-Qualys_FIM_Event_Type.json
  Packs/QualysFIM/ReleaseNotes/1_0_7.md
  Packs/QualysFIM/pack_metadata.json
  Packs/SafeBreach/IncidentFields/incidentfield-SafeBreach_Remediation_Action.json
  Packs/SafeBreach/ReleaseNotes/1_1_12.md
  Packs/SafeBreach/pack_metadata.json
  Packs/SolarWinds/IncidentFields/incidentfield-SolarWinds-Event-Type.json
  Packs/SolarWinds/ReleaseNotes/1_0_5.md
  Packs/SolarWinds/pack_metadata.json
  Packs/TaniumThreatResponse/IncidentFields/incidentfield-TaniumTR-taniumtype.json
  Packs/TaniumThreatResponse/ReleaseNotes/2_0_10.md
  Packs/TaniumThreatResponse/pack_metadata.json
  Packs/mnemonicMDR/IncidentFields/incidentfield-Argus_Event_Type.json
  Packs/mnemonicMDR/ReleaseNotes/1_1_4.md
  Packs/mnemonicMDR/pack_metadata.json
Labels: docs-approved

#17516 Fix dependency filtering for v2
  Tests/Marketplace/marketplace_services.py
Labels: docs-approved

#17244 Indicator Types - remove deprecated splunk enrichment script
  Packs/CommonTypes/IndicatorTypes/reputation-hashRepMD5.json
  Packs/CommonTypes/IndicatorTypes/reputation-hashRepSHA1.json
  Packs/CommonTypes/IndicatorTypes/reputation-ip.json
  Packs/CommonTypes/IndicatorTypes/reputation-url.json
  Packs/CommonTypes/ReleaseNotes/3_2_13.md
  Packs/CommonTypes/pack_metadata.json
Labels: docs-approved

#17411 Bug Cylance - return array entry as DBot type
  Packs/Cylance_Protect/Integrations/Cylance_Protect_v2/Cylance_Protect_v2.py
  Packs/Cylance_Protect/Integrations/Cylance_Protect_v2/Cylance_Protect_v2_test.py
  Packs/Cylance_Protect/ReleaseNotes/1_0_9.md
  Packs/Cylance_Protect/pack_metadata.json
Labels: docs-approved

#17205 ServiceNow SIR Mirroring Support
  Packs/ServiceNow/Classifiers/classifier-ServiceNow.json
  Packs/ServiceNow/Classifiers/classifier-mapper-incoming-ServiceNow.json
  Packs/ServiceNow/Classifiers/classifier-mapper-outgoing-ServiceNow.json
  Packs/ServiceNow/IncidentFields/incidentfield-ServiceNow_Attack_Vector.json
  Packs/ServiceNow/IncidentFields/incidentfield-ServiceNow_Business_Impact.json
  Packs/ServiceNow/IncidentFields/incidentfield-ServiceNow_Category_SIR.json
  Packs/ServiceNow/IncidentFields/incidentfield-ServiceNow_SIR_State.json
  Packs/ServiceNow/IncidentTypes/incidenttype-ServiceNow_SIR_Incident.json
  Packs/ServiceNow/Integrations/ServiceNowv2/README.md
  Packs/ServiceNow/Integrations/ServiceNowv2/ServiceNowv2.py
  Packs/ServiceNow/Integrations/ServiceNowv2/ServiceNowv2.yml
  Packs/ServiceNow/Integrations/ServiceNowv2/ServiceNowv2_test.py
  Packs/ServiceNow/Integrations/ServiceNowv2/test_data/result_constants.py
  Packs/ServiceNow/Layouts/layoutscontainer-ServiceNow_SIR_Incident.json
  Packs/ServiceNow/ReleaseNotes/2_3_0.md
  Packs/ServiceNow/pack_metadata.json
Labels: docs-approved

#17447 Aws api module add sts
  Packs/AWS-ACM/ReleaseNotes/1_1_8.md
  Packs/AWS-ACM/pack_metadata.json
  Packs/AWS-CloudWatchLogs/ReleaseNotes/1_2_4.md
  Packs/AWS-CloudWatchLogs/pack_metadata.json
  Packs/AWS-EC2/ReleaseNotes/1_2_9.md
  Packs/AWS-EC2/pack_metadata.json
  Packs/AWS-GuardDuty/ReleaseNotes/1_2_4.md
  Packs/AWS-GuardDuty/pack_metadata.json
  Packs/AWS-IAM/ReleaseNotes/1_1_10.md
  Packs/AWS-IAM/pack_metadata.json
  Packs/AWS-Lambda/ReleaseNotes/1_2_9.md
  Packs/AWS-Lambda/pack_metadata.json
  Packs/AWS-S3/ReleaseNotes/1_2_1.md
  Packs/AWS-S3/pack_metadata.json
  Packs/AWS-SQS/ReleaseNotes/1_2_5.md
  Packs/AWS-SQS/pack_metadata.json
  Packs/AWS-SecurityHub/ReleaseNotes/1_1_9.md
  Packs/AWS-SecurityHub/pack_metadata.json
  Packs/ApiModules/Scripts/AWSApiModule/AWSApiModule.py
  Packs/ApiModules/Scripts/AWSApiModule/AWSApiModule_test.py
Labels: Contribution, docs-approved, Contribution Form Filled, Community

#17535 logrythem-eol-info
  Packs/LogRhythmRest/Integrations/LogRhythmRestV2/README.md
Labels: docs-approved

#17538 Update conf.json
  Tests/conf.json
Labels: docs-approved

#17525 Fix bug in copy-from RemoteAccess v2
  Packs/RemoteAccess/Integrations/RemoteAccessv2/RemoteAccessv2.py
  Packs/RemoteAccess/ReleaseNotes/1_0_1.md
  Packs/RemoteAccess/pack_metadata.json
Labels: docs-approved

#17536 Revert fail duplicates
  .circleci/config.yml
Labels: docs-approved

#17449 Feature/sepiodev
  Packs/Sepio/Integrations/SepioPrimeAPI/SepioPrimeAPI.py
  Packs/Sepio/Integrations/SepioPrimeAPI/SepioPrimeAPI.yml
  Packs/Sepio/Integrations/SepioPrimeAPI/SepioPrimeAPI_test.py
  Packs/Sepio/ReleaseNotes/1_0_6.md
  Packs/Sepio/pack_metadata.json
Labels: Contribution, Contribution Form Filled, Community

#17542 Update README.md
  Packs/CadoResponse/README.md
Labels: Contribution, docs-approved, Partner, Contribution Form Filled

#17501 CrowdStrike Falcon Intel v2 - encode URLs
  Packs/CrowdStrikeIntel/Integrations/CrowdStrikeFalconIntel_v2/CrowdStrikeFalconIntel_v2.py
  Packs/CrowdStrikeIntel/Integrations/CrowdStrikeFalconIntel_v2/CrowdStrikeFalconIntel_v2.yml
  Packs/CrowdStrikeIntel/ReleaseNotes/2_0_14.md
  Packs/CrowdStrikeIntel/TestPlaybooks/playbook-CrowdStrikeFalconIntel_v2_Test.yml
  Packs/CrowdStrikeIntel/pack_metadata.json
Labels: docs-approved

#17355 Aburt-content-manager-improvements
  Packs/XSOARContentUpdateNotifications/.pack-ignore
  Packs/XSOARContentUpdateNotifications/IncidentFields/incidentfield-Content_Updates_Auto_Install.json
  Packs/XSOARContentUpdateNotifications/IncidentFields/incidentfield-Demisto_REST_API_Instance_Name.json
  Packs/XSOARContentUpdateNotifications/Layouts/layoutscontainer-Content_Update_Manager_Layout.json
  Packs/XSOARContentUpdateNotifications/Playbooks/playbook-Check_For_Content_Installation.yml
  Packs/XSOARContentUpdateNotifications/Playbooks/playbook-Content_Update_Manager.yml
  Packs/XSOARContentUpdateNotifications/ReleaseNotes/1_0_3.md
  Packs/XSOARContentUpdateNotifications/Scripts/GetLatestReleaseNotes/GetLatestReleaseNotes.py
  Packs/XSOARContentUpdateNotifications/Scripts/GetLatestReleaseNotes/GetLatestReleaseNotes.yml
  Packs/XSOARContentUpdateNotifications/pack_metadata.json
Labels: Contribution, docs-approved, Contribution Form Filled

#17544 Mitre fields fix
  Packs/CommonTypes/IncidentFields/incidentfield-Tactic.json
  Packs/CommonTypes/IncidentFields/incidentfield-Tactic_ID.json
  Packs/CommonTypes/IncidentFields/incidentfield-Technique.json
  Packs/CommonTypes/IncidentFields/incidentfield-Technique_ID.json
  Packs/CommonTypes/ReleaseNotes/3_2_14.md
  Packs/CommonTypes/pack_metadata.json
  Packs/CoreAlertFields/IncidentFields/incidentfield-Mitre_ATT&CK_Tactic.json
  Packs/CoreAlertFields/IncidentFields/incidentfield-Mitre_ATT&CK_Technique.json
  Packs/CoreAlertFields/ReleaseNotes/1_0_10.md
  Packs/CoreAlertFields/pack_metadata.json
  Packs/XMCyber/IncidentFields/incidentfield-Technique_Mitre.json
  Packs/XMCyber/IncidentFields/incidentfield-Technique_Name.json
  Packs/XMCyber/ReleaseNotes/1_0_13.md
  Packs/XMCyber/pack_metadata.json
Labels: docs-approved

#17284 [O365, Gmail] add the reply-to header
  Packs/EWS/Integrations/EWSO365/EWSO365.py
  Packs/EWS/Integrations/EWSO365/EWSO365.yml
  Packs/EWS/Integrations/EWSO365/README.md
  Packs/EWS/ReleaseNotes/1_11_4.md
  Packs/EWS/TestPlaybooks/playbook-EWS_O365_send_mail_test.yml
  Packs/EWS/pack_metadata.json
  Packs/MicrosoftGraphListener/.secrets-ignore
  Packs/MicrosoftGraphListener/Integrations/MicrosoftGraphListener/MicrosoftGraphListener.py
  Packs/MicrosoftGraphListener/Integrations/MicrosoftGraphListener/MicrosoftGraphListener.yml
  Packs/MicrosoftGraphListener/Integrations/MicrosoftGraphListener/MicrosoftGraphListener_test.py
  Packs/MicrosoftGraphListener/Integrations/MicrosoftGraphListener/README.md
  Packs/MicrosoftGraphListener/ReleaseNotes/1_0_24.md
  Packs/MicrosoftGraphListener/pack_metadata.json
  Packs/MicrosoftGraphMail/Integrations/MicrosoftGraphMail/MicrosoftGraphMail.py
  Packs/MicrosoftGraphMail/Integrations/MicrosoftGraphMail/MicrosoftGraphMail.yml
  Packs/MicrosoftGraphMail/Integrations/MicrosoftGraphMail/MicrosoftGraphMail_test.py
  Packs/MicrosoftGraphMail/Integrations/MicrosoftGraphMail/README.md
  Packs/MicrosoftGraphMail/ReleaseNotes/1_1_11.md
  Packs/MicrosoftGraphMail/pack_metadata.json
Labels: docs-approved

#17509 skipping confluence cloud
  Tests/conf.json
Labels: docs-approved

#17486 Fix bug in windows ansible pack for !win-package
  Packs/AnsibleMicrosoftWindows/Integrations/AnsibleMicrosoftWindows/AnsibleMicrosoftWindows.yml
  Packs/AnsibleMicrosoftWindows/ReleaseNotes/1_0_3.md
  Packs/AnsibleMicrosoftWindows/pack_metadata.json
Labels: Contribution, docs-approved, Contribution Form Filled, Community

#17533 Improve slack notifier upload message
  Tests/scripts/gitlab_slack_notifier.py
Labels: docs-approved

#17562 sx-support-partner-update
  Packs/Securonix/README.md
Labels: docs-approved

#17357 New Integration: ACTI Vulnerability Query
  Packs/AccentureCTI/Integrations/ACTIIndicatorQuery/README.md
  Packs/AccentureCTI/Integrations/ACTIVulnerabilityQuery/ACTIVulnerabilityQuery.py
  Packs/AccentureCTI/Integrations/ACTIVulnerabilityQuery/ACTIVulnerabilityQuery.yml
  Packs/AccentureCTI/Integrations/ACTIVulnerabilityQuery/ACTIVulnerabilityQuery_description.md
  Packs/AccentureCTI/Integrations/ACTIVulnerabilityQuery/ACTIVulnerabilityQuery_image.png
  Packs/AccentureCTI/Integrations/ACTIVulnerabilityQuery/ACTIVulnerabilityQuery_test.py
  Packs/AccentureCTI/Integrations/ACTIVulnerabilityQuery/Pipfile
  Packs/AccentureCTI/Integrations/ACTIVulnerabilityQuery/Pipfile.lock
  Packs/AccentureCTI/Integrations/ACTIVulnerabilityQuery/README.md
  Packs/AccentureCTI/Integrations/ACTIVulnerabilityQuery/test_data/response_constants.py
  Packs/AccentureCTI/README.md
  Packs/AccentureCTI/ReleaseNotes/1_1_0.md
  Packs/AccentureCTI/pack_metadata.json
Labels: Contribution, docs-approved, Partner, Contribution Form Filled

#17548 Fix ReadPdfFileV2 script bug
  Packs/CommonScripts/.secrets-ignore
  Packs/CommonScripts/ReleaseNotes/1_6_33.md
  Packs/CommonScripts/Scripts/ReadPDFFileV2/ReadPDFFileV2.py
  Packs/CommonScripts/Scripts/ReadPDFFileV2/ReadPDFFileV2_test.py
  Packs/CommonScripts/Scripts/ReadPDFFileV2/test_data/pdf-html-content.html
  Packs/CommonScripts/pack_metadata.json
Labels: docs-approved

#17532 Proofpoint TAP v2 - Handle non-ascii chars in message
  Packs/ProofpointTAP/Integrations/ProofpointTAP_v2/ProofpointTAP_v2.py
  Packs/ProofpointTAP/Integrations/ProofpointTAP_v2/ProofpointTAP_v2.yml
  Packs/ProofpointTAP/Integrations/ProofpointTAP_v2/ProofpointTAP_v2_test.py
  Packs/ProofpointTAP/Integrations/ProofpointTAP_v2/README.md
  Packs/ProofpointTAP/ReleaseNotes/1_1_13.md
  Packs/ProofpointTAP/pack_metadata.json
Labels: docs-approved

#17571 Remove wrong marketplace
  Packs/CoreAlertFields/IncidentFields/incidentfield-Host_IP.json
  Packs/CoreAlertFields/ReleaseNotes/1_0_11.md
  Packs/CoreAlertFields/pack_metadata.json
Labels: docs-approved

#17305 ManageEngine PAM360 Marketplace contribution
  Packs/ManageEngine_PAM360/.pack-ignore
  Packs/ManageEngine_PAM360/.secrets-ignore
  Packs/ManageEngine_PAM360/Author_image.png
  Packs/ManageEngine_PAM360/Integrations/ManageEnginePAM360/ManageEnginePAM360.py
  Packs/ManageEngine_PAM360/Integrations/ManageEnginePAM360/ManageEnginePAM360.yml
  Packs/ManageEngine_PAM360/Integrations/ManageEnginePAM360/ManageEnginePAM360_description.md
  Packs/ManageEngine_PAM360/Integrations/ManageEnginePAM360/ManageEnginePAM360_image.png
  Packs/ManageEngine_PAM360/Integrations/ManageEnginePAM360/ManageEnginePAM360_test.py
  Packs/ManageEngine_PAM360/Integrations/ManageEnginePAM360/Pipfile
  Packs/ManageEngine_PAM360/Integrations/ManageEnginePAM360/Pipfile.lock
  Packs/ManageEngine_PAM360/Integrations/ManageEnginePAM360/README.md
  Packs/ManageEngine_PAM360/Integrations/ManageEnginePAM360/command_examples
  Packs/ManageEngine_PAM360/Integrations/ManageEnginePAM360/test_data/context.py
  Packs/ManageEngine_PAM360/Integrations/ManageEnginePAM360/test_data/responses.py
  Packs/ManageEngine_PAM360/README.md
  Packs/ManageEngine_PAM360/pack_metadata.json
Labels: Contribution, docs-approved, Partner, post-demo, Contribution Form Filled

#17199 New cm
  Packs/Change_Management/.pack-ignore
  Packs/Change_Management/.secrets-ignore
  Packs/Change_Management/IncidentFields/incidentfield-Security_Policy_Match.json
  Packs/Change_Management/IncidentTypes/incidenttype-FW_change_management.json
  Packs/Change_Management/Layouts/layoutscontainer-FW_change_management.json
  Packs/Change_Management/Playbooks/playbook-Change_Management.yml
  Packs/Change_Management/Playbooks/playbook-Change_Management_README.md
  Packs/Change_Management/Playbooks/playbook-Jira_Change_Management.yml
  Packs/Change_Management/Playbooks/playbook-Jira_Change_Management_README.md
  Packs/Change_Management/Playbooks/playbook-PAN-OS_create_or_edit_policy.yml
  Packs/Change_Management/Playbooks/playbook-PAN-OS_create_or_edit_policy_README.md
  Packs/Change_Management/Playbooks/playbook-PAN-OS_edit_policy.yml
  Packs/Change_Management/Playbooks/playbook-PAN-OS_edit_policy_README.md
  Packs/Change_Management/Playbooks/playbook-ServiceNow_Change_Management.yml
  Packs/Change_Management/Playbooks/playbook-ServiceNow_Change_Management_README.md
  Packs/Change_Management/README.md
  Packs/Change_Management/Scripts/IncidentState/IncidentState.py
  Packs/Change_Management/Scripts/IncidentState/IncidentState.yml
  Packs/Change_Management/Scripts/IncidentState/README.md
  Packs/Change_Management/doc_files/Change_management.png
  Packs/Change_Management/doc_files/Jira_Change_Management.png
  Packs/Change_Management/doc_files/PAN-OS_create_or_edit_policy.png
  Packs/Change_Management/doc_files/PAN-OS_edit_policy.png
  Packs/Change_Management/doc_files/ServiceNow_Change_Management.png
  Packs/Change_Management/pack_metadata.json
  Packs/CommonTypes/IncidentFields/incidentfield-Destination_IPs.json
  Packs/CommonTypes/IncidentFields/incidentfield-Destination_Networks.json
  Packs/CommonTypes/IncidentFields/incidentfield-Destination_Ports.json
  Packs/CommonTypes/IncidentFields/incidentfield-Policy_Actions.json
  Packs/CommonTypes/IncidentFields/incidentfield-Protocol_names.json
  Packs/CommonTypes/IncidentFields/incidentfield-Source_IPs.json
  Packs/CommonTypes/IncidentFields/incidentfield-Source_Networks.json
  Packs/CommonTypes/ReleaseNotes/3_2_16.md
  Packs/CommonTypes/pack_metadata.json
  Packs/ServiceNow/Playbooks/playbook-Create_ServiceNow_Ticket.yml
  Packs/ServiceNow/Playbooks/playbook-Create_ServiceNow_Ticket_README.md
  Packs/ServiceNow/ReleaseNotes/2_3_2.md
  Packs/ServiceNow/pack_metadata.json
Labels: docs-approved

#17524 Adding credentials set support domain tools
  Packs/DomainTools/Integrations/DomainTools/DomainTools.js
  Packs/DomainTools/Integrations/DomainTools/DomainTools.yml
  Packs/DomainTools/ReleaseNotes/1_1_2.md
  Packs/DomainTools/pack_metadata.json
  Tests/known_words.txt
Labels: docs-approved

#17575 Agent fqdn
  Packs/CoreAlertFields/IncidentFields/incidentfield-Host_FQDN.json
  Packs/CoreAlertFields/ReleaseNotes/1_0_12.md
  Packs/CoreAlertFields/pack_metadata.json
Labels: docs-approved

#17526 Fixed issue with last run when there are no alerts
  Packs/ApiModules/Scripts/FireEyeApiModule/FireEyeApiModule.py
  Packs/ApiModules/Scripts/FireEyeApiModule/FireEyeApiModule_test.py
  Packs/FireEyeCM/Integrations/FireEyeCM/FireEyeCM.py
  Packs/FireEyeCM/Integrations/FireEyeCM/FireEyeCM_test.py
  Packs/FireEyeCM/Integrations/FireEyeCM/test_data/no_alerts.json
  Packs/FireEyeCM/ReleaseNotes/1_1_9.md
  Packs/FireEyeCM/pack_metadata.json
  Packs/FireEyeEX/Integrations/FireEyeEX/FireEyeEX.py
  Packs/FireEyeEX/Integrations/FireEyeEX/FireEyeEX.yml
  Packs/FireEyeEX/Integrations/FireEyeEX/FireEyeEX_test.py
  Packs/FireEyeEX/Integrations/FireEyeEX/test_data/no_alerts.json
  Packs/FireEyeEX/ReleaseNotes/2_0_6.md
  Packs/FireEyeEX/pack_metadata.json
Labels: docs-approved

#17485 NGFW TS Agent Deployment
  Packs/NGFWTSAgentDeployment/.pack-ignore
  Packs/NGFWTSAgentDeployment/.secrets-ignore
  Packs/NGFWTSAgentDeployment/Playbooks/JOB_-_PANW_NGFW_TS_Agent_Cleanup.yml
  Packs/NGFWTSAgentDeployment/Playbooks/JOB_-_PANW_NGFW_TS_Agent_Cleanup_README.md
  Packs/NGFWTSAgentDeployment/Playbooks/NGFW_Remove_Offline_TS_Agent.yml
  Packs/NGFWTSAgentDeployment/Playbooks/NGFW_Remove_Offline_TS_Agent_README.md
  Packs/NGFWTSAgentDeployment/Playbooks/PANW_NGFW_TS_Agent_Deployment.yml
  Packs/NGFWTSAgentDeployment/Playbooks/PANW_NGFW_TS_Agent_Deployment_README.md
  Packs/NGFWTSAgentDeployment/README.md
  Packs/NGFWTSAgentDeployment/doc_files/JOB_-_PANW_NGFW_TS_Agent_Cleanup_Fri_Feb_04_2022.png
  Packs/NGFWTSAgentDeployment/doc_files/NGFW_Remove_Offline_TS_Agent_Fri_Feb_04_2022.png
  Packs/NGFWTSAgentDeployment/doc_files/PANW_NGFW_TS_Agent_Deployment_Fri_Feb_04_2022.png
  Packs/NGFWTSAgentDeployment/pack_metadata.json
Labels: Contribution, docs-approved, Contribution Form Filled, Community

#17157 replace the deprecated LooseVersion usages
  Tests/Marketplace/Tests/marketplace_services_test.py
  Tests/Marketplace/marketplace_services.py
  Tests/Marketplace/search_and_install_packs.py
  Tests/Marketplace/zip_packs.py
  Tests/configure_and_test_integration_instances.py
  Tests/private_build/run_content_tests_private.py
  Tests/scripts/collect_tests_and_content_packs.py
  Tests/scripts/infrastructure_tests/release_notes_generator_test.py
  Utils/release_notes_generator.py
Labels: docs-approved

#17589 Fix xdr iocs pagination issue
  Packs/CortexXDR/Integrations/XDR_iocs/XDR_iocs.py
  Packs/CortexXDR/Integrations/XDR_iocs/XDR_iocs_test.py
  Packs/CortexXDR/ReleaseNotes/4_2_18.md
  Packs/CortexXDR/pack_metadata.json
Labels: bug, docs-approved

#17583 1.6.0
  dev-requirements-py3.txt
Labels: docs-approved

#17543 Added extra outputs.
  Packs/Nmap/Integrations/Nmap/Nmap.py
  Packs/Nmap/Integrations/Nmap/Nmap.yml
  Packs/Nmap/Integrations/Nmap/README.md
  Packs/Nmap/ReleaseNotes/1_0_2.md
  Packs/Nmap/pack_metadata.json
Labels: docs-approved

#17556 Edit the configuration instructions in the README
  Packs/CortexDataLake/Integrations/CortexDataLake/README.md
Labels: docs-approved

#17600 Panorama small fix
  Packs/PAN-OS/Integrations/Panorama/Panorama.py
  Packs/PAN-OS/ReleaseNotes/1_8_8.md
  Packs/PAN-OS/pack_metadata.json
Labels: docs-approved

#17563 Email enrich fix
  Packs/CommonPlaybooks/Playbooks/playbook-Email_Address_Enrichment_-_Generic_v2.1.yml
  Packs/CommonPlaybooks/ReleaseNotes/2_1_11.md
  Packs/CommonPlaybooks/pack_metadata.json
Labels: docs-approved

#17584 fix SetGridField grid field with null
  Packs/CommonScripts/ReleaseNotes/1_6_34.md
  Packs/CommonScripts/Scripts/SetGridField/SetGridField.py
  Packs/CommonScripts/Scripts/SetGridField/SetGridField.yml
  Packs/CommonScripts/pack_metadata.json
Labels: docs-approved

#17592 Remove mandatory dependencies from CommonPlaybooks pack
  Packs/CommonPlaybooks/pack_metadata.json
Labels: docs-approved

#17474 Parse email files nested
  Packs/CommonScripts/ReleaseNotes/1_6_35.md
  Packs/CommonScripts/Scripts/ParseEmailFiles/ParseEmailFiles.py
  Packs/CommonScripts/Scripts/ParseEmailFiles/ParseEmailFiles.yml
  Packs/CommonScripts/Scripts/ParseEmailFiles/ParseEmailFiles_test.py
  Packs/CommonScripts/pack_metadata.json
Labels: docs-approved

#17547 skip extention-definition objects in TAXII2ApiModule
  Packs/ApiModules/Scripts/TAXII2ApiModule/TAXII2ApiModule.py
  Packs/ApiModules/Scripts/TAXII2ApiModule/TAXII2ApiModule_test.py
  Packs/ApiModules/Scripts/TAXII2ApiModule/test_data/objects_envelopes_v20.json
  Packs/ApiModules/Scripts/TAXII2ApiModule/test_data/objects_envelopes_v21.json
  Packs/FeedTAXII/ReleaseNotes/1_1_4.md
  Packs/FeedTAXII/pack_metadata.json
  Tests/known_words.txt
Labels: docs-approved

#17568 WildFire v2 - Fixed the parsing of the report's network outputs
  Packs/Palo_Alto_Networks_WildFire/.secrets-ignore
  Packs/Palo_Alto_Networks_WildFire/Integrations/Palo_Alto_Networks_WildFire_v2/Palo_Alto_Networks_WildFire_v2.py
  Packs/Palo_Alto_Networks_WildFire/Integrations/Palo_Alto_Networks_WildFire_v2/Palo_Alto_Networks_WildFire_v2_test.py
  Packs/Palo_Alto_Networks_WildFire/ReleaseNotes/2_0_7.md
  Packs/Palo_Alto_Networks_WildFire/TestPlaybooks/playbook-Wildfire_Test.yml
  Packs/Palo_Alto_Networks_WildFire/pack_metadata.json
Labels: docs-approved

#17618 ID Set MPv2: copy debug files to artifact folder
  .gitlab/ci/global.yml
Labels: docs-approved

#17590 Fix for agent id field
  Packs/CommonTypes/IncidentFields/incidentfield-Agents_ID.json
  Packs/CommonTypes/ReleaseNotes/3_2_18.md
  Packs/CommonTypes/pack_metadata.json
  Packs/CoreAlertFields/IncidentFields/incidentfield-Agent_ID.json
  Packs/CoreAlertFields/ReleaseNotes/1_0_14.md
  Packs/CoreAlertFields/pack_metadata.json
Labels: docs-approved

#17619 Update README.md
  Packs/CadoResponse/README.md
Labels: Contribution, docs-approved, Partner, Contribution Form Filled

#17609 update PAN-OS EDL Management description and README
  Packs/PaloAltoNetworks_PAN_OS_EDL_Management/Integrations/PaloAltoNetworks_PAN_OS_EDL_Management/PaloAltoNetworks_PAN_OS_EDL_Management.yml
  Packs/PaloAltoNetworks_PAN_OS_EDL_Management/Integrations/PaloAltoNetworks_PAN_OS_EDL_Management/README.md
  Packs/PaloAltoNetworks_PAN_OS_EDL_Management/ReleaseNotes/1_1_3.md
  Packs/PaloAltoNetworks_PAN_OS_EDL_Management/pack_metadata.json
Labels: docs-approved

#17633 setting test to unmockable
  Tests/conf.json
Labels: docs-approved

#17636 Changed Contributions
  Utils/github_workflow_scripts/handle_external_pr.py
Labels: docs-approved

#17639 Added apicall to demistomock
  Tests/demistomock/demistomock.py
Labels: docs-approved

#17310 Fix broken links in content docs
  Packs/AnsibleLinux/.secrets-ignore
  Packs/AnsibleLinux/Integrations/AnsibleACME/README.md
  Packs/AnsibleLinux/Integrations/AnsibleLinux/README.md
  Packs/AzureActiveDirectory/Integrations/AzureADIdentityProtection/README.md
  Packs/AzureDevOps/Integrations/AzureDevOps/README.md
  Packs/BeyondTrust_Password_Safe/Integrations/BeyondTrust_Password_Safe/README.md
  Packs/Box/Integrations/Box/Box_description.md
  Packs/Box/Integrations/Box/README.md
  Packs/Box/ReleaseNotes/2_1_5.md
  Packs/Box/pack_metadata.json
  Packs/CofenseIntelligenceV2/Integrations/CofenseIntelligenceV2/README.md
  Packs/ConvertTimezoneFromUTC/Scripts/ConvertTimezoneFromUTC/README.md
  Packs/DevSecOps/Integrations/DockerEngine/README.md
  Packs/FeedDHS/README.md
  Packs/Grafana/Integrations/Grafana/README.md
  Packs/Infocyte/Integrations/Infocyte/README.md
  Packs/MicrosoftCloudAppSecurity/Integrations/MicrosoftCloudAppSecurity/README.md
  Packs/MicrosoftGraphSecurity/Integrations/MicrosoftGraphSecurity/README.md
  Packs/MobileIronUEM/.secrets-ignore
  Packs/MobileIronUEM/README.md
  Packs/PAN-OS/Playbooks/playbook-PAN-OS_Log_Forwarding_Setup_And_Maintenance_README.md
  Packs/PassiveTotal/Integrations/PassiveTotal_v2/README.md
  Packs/TrendMicroCAS/Integrations/TrendMicroCAS/TrendMicroCAS_description.md
  Packs/TrendMicroCAS/ReleaseNotes/1_0_8.md
  Packs/TrendMicroCAS/pack_metadata.json
  Packs/XSOARContentUpdateNotifications/README.md
Labels: docs-approved

#17647 Update SDK hot-fix version
  dev-requirements-py3.txt
Labels: docs-approved

#17641 update skippable tasks in playbooks
  Packs/Code42/Playbooks/playbook-Code42_Exfiltration_Playbook.yml
  Packs/Code42/ReleaseNotes/2_0_13.md
  Packs/Code42/pack_metadata.json
  Packs/CommonPlaybooks/Playbooks/playbook-Isolate_Endpoint_-_Generic.yml
  Packs/CommonPlaybooks/ReleaseNotes/2_1_13.md
  Packs/CommonPlaybooks/pack_metadata.json
  Packs/PortScan/Playbooks/Port_Scan_-_Internal_Source.yml
  Packs/PortScan/ReleaseNotes/1_1_7.md
  Packs/PortScan/pack_metadata.json
Labels: docs-approved

#17325 Lastline csv bug
  Packs/Lastline/Integrations/Lastline_v2/Lastline_v2.py
  Packs/Lastline/Integrations/Lastline_v2/Lastline_v2.yml
  Packs/Lastline/Integrations/Lastline_v2/Lastline_v2_test.py
  Packs/Lastline/Integrations/Lastline_v2/README.md
  Packs/Lastline/ReleaseNotes/1_0_10.md
  Packs/Lastline/pack_metadata.json
  Tests/known_words.txt
Labels: bug, docs-approved, release-notes-only

#17028 PhishUp
  .gitignore
  Packs/PhishUp/.pack-ignore
  Packs/PhishUp/.secrets-ignore
  Packs/PhishUp/Author_image.png
  Packs/PhishUp/Classifiers/classifier-PhishUp_Gmail_Mapper.json
  Packs/PhishUp/IncidentTypes/incidenttype-PhishUp.json
  Packs/PhishUp/Integrations/PhishUp/PhishUp.py
  Packs/PhishUp/Integrations/PhishUp/PhishUp.yml
  Packs/PhishUp/Integrations/PhishUp/PhishUp_description.md
  Packs/PhishUp/Integrations/PhishUp/PhishUp_image.png
  Packs/PhishUp/Integrations/PhishUp/PhishUp_test.py
  Packs/PhishUp/Integrations/PhishUp/Pipfile
  Packs/PhishUp/Integrations/PhishUp/Pipfile.lock
  Packs/PhishUp/Integrations/PhishUp/README.md
  Packs/PhishUp/Integrations/PhishUp/command_examples
  Packs/PhishUp/Integrations/PhishUp/test_data/authentication_error.json
  Packs/PhishUp/Integrations/PhishUp/test_data/error.json
  Packs/PhishUp/Integrations/PhishUp/test_data/investigate-success-outputs.json
  Packs/PhishUp/Integrations/PhishUp/test_data/investigate-success-raw-response.json
  Packs/PhishUp/Integrations/PhishUp/test_data/investigate_api_successful_response.json
  Packs/PhishUp/Playbooks/PhishUp_Mail_Scanner.yml
  Packs/PhishUp/Playbooks/PhishUp_Mail_Scanner_README.md
  Packs/PhishUp/README.md
  Packs/PhishUp/doc_files/PhishUp_Mail_Scanner.png
  Packs/PhishUp/pack_metadata.json
  package-lock.json
Labels: Contribution, docs-approved, Partner, Contribution Form Filled

#17653 Change VT name in NonSupported pack
  Packs/NonSupported/Integrations/integration-VirusTotal_5_1_0.yml
  Packs/NonSupported/Integrations/integration-VirusTotal_5_1_0_README.md
Labels: docs-approved

#17315 microsoft-atp add arrays support
  Packs/MicrosoftDefenderAdvancedThreatProtection/Integrations/MicrosoftDefenderAdvancedThreatProtection/MicrosoftDefenderAdvancedThreatProtection.py
  Packs/MicrosoftDefenderAdvancedThreatProtection/Integrations/MicrosoftDefenderAdvancedThreatProtection/MicrosoftDefenderAdvancedThreatProtection.yml
  Packs/MicrosoftDefenderAdvancedThreatProtection/Integrations/MicrosoftDefenderAdvancedThreatProtection/MicrosoftDefenderAdvancedThreatProtection_test.py
  Packs/MicrosoftDefenderAdvancedThreatProtection/Integrations/MicrosoftDefenderAdvancedThreatProtection/README.md
  Packs/MicrosoftDefenderAdvancedThreatProtection/Integrations/MicrosoftDefenderAdvancedThreatProtection/examples.txt
  Packs/MicrosoftDefenderAdvancedThreatProtection/ReleaseNotes/1_4_0.md
  Packs/MicrosoftDefenderAdvancedThreatProtection/Scripts/TransformIndicatorToMSDefenderIOC/README.md
  Packs/MicrosoftDefenderAdvancedThreatProtection/Scripts/TransformIndicatorToMSDefenderIOC/TransformIndicatorToMSDefenderIOC.py
  Packs/MicrosoftDefenderAdvancedThreatProtection/Scripts/TransformIndicatorToMSDefenderIOC/TransformIndicatorToMSDefenderIOC.yml
  Packs/MicrosoftDefenderAdvancedThreatProtection/Scripts/TransformIndicatorToMSDefenderIOC/TransformIndicatorToMSDefenderIOC_test.py
  Packs/MicrosoftDefenderAdvancedThreatProtection/TestPlaybooks/playbook-Microsoft_Defender_Advanced_Threat_Protection-Test.yml
  Packs/MicrosoftDefenderAdvancedThreatProtection/pack_metadata.json
Labels: enhancement, docs-approved, post-demo

#17574 Syslog remove test module
  Packs/Syslog/Integrations/Syslogv2/Syslogv2.py
  Packs/Syslog/Integrations/Syslogv2/Syslogv2.yml
  Packs/Syslog/Integrations/Syslogv2/Syslogv2_test.py
  Packs/Syslog/Integrations/Syslogv2/test_data/long_running_loop_data.json
  Packs/Syslog/ReleaseNotes/2_0_3.md
  Packs/Syslog/pack_metadata.json
  Tests/known_words.txt
Labels: docs-approved

#17656 Change contributors
  Utils/github_workflow_scripts/handle_external_pr.py
Labels: docs-approved

#17651 FIxed bug where SQL returns 0 results
  Packs/SecurityTrails/Integrations/SecurityTrails/SecurityTrails.py
  Packs/SecurityTrails/ReleaseNotes/1_1_1.md
  Packs/SecurityTrails/pack_metadata.json
Labels: Contribution, Contribution Form Filled, Community

#17662 snow update link
  Packs/ServiceNow/Integrations/ServiceNowv2/README.md
Labels: docs-approved

#17348 Cs FX enhancement - Polling commands
  Packs/CrowdStrikeFalconX/.secrets-ignore
  Packs/CrowdStrikeFalconX/Integrations/CrowdStrikeFalconX/CrowdStrikeFalconX.py
  Packs/CrowdStrikeFalconX/Integrations/CrowdStrikeFalconX/CrowdStrikeFalconX.yml
  Packs/CrowdStrikeFalconX/Integrations/CrowdStrikeFalconX/CrowdStrikeFalconX_test.py
  Packs/CrowdStrikeFalconX/Integrations/CrowdStrikeFalconX/README.md
  Packs/CrowdStrikeFalconX/Integrations/CrowdStrikeFalconX/TestsInput/context.py
  Packs/CrowdStrikeFalconX/Integrations/CrowdStrikeFalconX/TestsInput/http_responses.py
  Packs/CrowdStrikeFalconX/ReleaseNotes/1_1_7.md
  Packs/CrowdStrikeFalconX/pack_metadata.json
Labels: docs-approved

#17648 deprecate LogRhythm
  Packs/LogRhythm/Integrations/LogRhythm/LogRhythm.yml
  Packs/LogRhythm/Integrations/LogRhythm/README.md
  Packs/LogRhythm/ReleaseNotes/1_0_1.md
  Packs/LogRhythm/pack_metadata.json
  Tests/conf.json
Labels: docs-approved

#17674 Skip test - will be unskipped once the changes are merged.
  Utils/github_workflow_scripts/github_workflow_scripts_tests/run_docs_review_test.py
Labels: docs-approved

#17671 Core alert fix
  Packs/CoreAlertFields/IncidentFields/incidentfield-File_MD5.json
  Packs/CoreAlertFields/IncidentFields/incidentfield-File_Path.json
  Packs/CoreAlertFields/ReleaseNotes/1_0_17.md
  Packs/CoreAlertFields/pack_metadata.json
Labels: docs-approved

#17167 Crowdstrike falcon sandbox v2 42659
  Packs/Base/ReleaseNotes/1_18_7.md
  Packs/Base/Scripts/CommonServerPython/CommonServerPython.py
  Packs/Base/pack_metadata.json
  Packs/CrowdStrikeFalconSandbox/Integrations/CrowdstrikeFalconSandboxV2/CrowdStrikeFalconSandboxV2.py
  Packs/CrowdStrikeFalconSandbox/Integrations/CrowdstrikeFalconSandboxV2/CrowdStrikeFalconSandboxV2.yml
  Packs/CrowdStrikeFalconSandbox/Integrations/CrowdstrikeFalconSandboxV2/CrowdStrikeFalconSandboxV2_description.md
  Packs/CrowdStrikeFalconSandbox/Integrations/CrowdstrikeFalconSandboxV2/CrowdStrikeFalconSandboxV2_image.png
  Packs/CrowdStrikeFalconSandbox/Integrations/CrowdstrikeFalconSandboxV2/CrowdStrikeFalconSandboxV2_test.py
  Packs/CrowdStrikeFalconSandbox/Integrations/CrowdstrikeFalconSandboxV2/Pipfile
  Packs/CrowdStrikeFalconSandbox/Integrations/CrowdstrikeFalconSandboxV2/Pipfile.lock
  Packs/CrowdStrikeFalconSandbox/Integrations/CrowdstrikeFalconSandboxV2/README.md
  Packs/CrowdStrikeFalconSandbox/Integrations/CrowdstrikeFalconSandboxV2/command_examples.txt
  Packs/CrowdStrikeFalconSandbox/Integrations/CrowdstrikeFalconSandboxV2/test_data/scan_response.json
  Packs/CrowdStrikeFalconSandbox/Integrations/CrowdstrikeFalconSandboxV2/test_data/submission_response.json
  Packs/CrowdStrikeFalconSandbox/Integrations/VxStream/VxStream.yml
  Packs/CrowdStrikeFalconSandbox/Playbooks/playbook-Detonate_File_-_CrowdStrike_Falcon_Sandbox.yml
  Packs/CrowdStrikeFalconSandbox/Playbooks/playbook-Detonate_File_-_CrowdStrike_Falcon_Sandbox_README.md
  Packs/CrowdStrikeFalconSandbox/Playbooks/playbook-Detonate_URL_-_CrowdStrike.yml
  Packs/CrowdStrikeFalconSandbox/Playbooks/playbook-Detonate_URL_-_CrowdStrike_README.md
  Packs/CrowdStrikeFalconSandbox/ReleaseNotes/2_0_0.md
  Packs/CrowdStrikeFalconSandbox/TestPlaybooks/CrowdstrikeFalconSandbox2_Test.yml
  Packs/CrowdStrikeFalconSandbox/TestPlaybooks/playbook-Detonate_URL_-_Crowdstrike_Test.yml
  Packs/CrowdStrikeFalconSandbox/TestPlaybooks/playbook-VxStream_Test.yml
  Packs/CrowdStrikeFalconSandbox/pack_metadata.json
  Tests/conf.json
Labels: docs-approved

#17475 Ml playbook improved memory
  Packs/Base/ReleaseNotes/1_18_8.md
  Packs/Base/Scripts/GetIncidentsByQuery/GetIncidentsByQuery.py
  Packs/Base/Scripts/GetIncidentsByQuery/GetIncidentsByQuery.yml
  Packs/Base/pack_metadata.json
  Packs/DeveloperTools/TestPlaybooks/script-TestCreateIncidentsForPhishingClassifier.yml
  Packs/ML/Playbooks/playbook-DBot_Create_Phishing_Classifier_V2.yml
  Packs/ML/ReleaseNotes/1_4_0.md
  Packs/ML/Scripts/ExtendQueryBasedOnPhishingLabels/ExtendQueryBasedOnPhishingLabels.py
  Packs/ML/Scripts/ExtendQueryBasedOnPhishingLabels/ExtendQueryBasedOnPhishingLabels.yml
  Packs/ML/pack_metadata.json
Labels: docs-approved

#17667 Remove WhereIsTheEgg from MP v2
  Packs/WhereIsTheEgg/pack_metadata.json
  Tests/Marketplace/core_packs_mpv2_list.json
Labels: docs-approved

#17683 PhishUp update README.md
  Packs/PhishUp/README.md
Labels: Contribution, Partner, Contribution Form Filled

#17627 Improving RelatedValuesListId key error in !archer-get-valuelist command
  Packs/ArcherRSA/Integrations/ArcherV2/ArcherV2.py
  Packs/ArcherRSA/Integrations/ArcherV2/ArcherV2.yml
  Packs/ArcherRSA/Integrations/ArcherV2/ArcherV2_test.py
  Packs/ArcherRSA/ReleaseNotes/1_1_33.md
  Packs/ArcherRSA/pack_metadata.json
Labels: docs-approved

#17676 Remove panos dependency
  Packs/EDL/Playbooks/playbook-PAN-OS_EDL_Service_Configuration.yml
  Packs/EDL/ReleaseNotes/3_0_3.md
  Packs/EDL/pack_metadata.json
Labels: docs-approved

#17650 fix target
  Packs/Infinipoint/Integrations/Infinipoint/Infinipoint.py
  Packs/Infinipoint/Integrations/Infinipoint/Infinipoint.yml
  Packs/Infinipoint/ReleaseNotes/1_0_9.md
  Packs/Infinipoint/pack_metadata.json
Labels: Contribution, Contribution Form Filled, Community

#17696 Remove broken video reference
  Packs/ContentManagement/README.md
Labels: docs-approved

#17672 [Chronicle-246] Google Chronicle Backstory Enhancement
  Packs/GoogleChronicleBackstory/Integrations/GoogleChronicleBackstory/GoogleChronicleBackstory.py
  Packs/GoogleChronicleBackstory/Integrations/GoogleChronicleBackstory/GoogleChronicleBackstory.yml
  Packs/GoogleChronicleBackstory/Integrations/GoogleChronicleBackstory/GoogleChronicleBackstory_test.py
  Packs/GoogleChronicleBackstory/Integrations/GoogleChronicleBackstory/README.md
  Packs/GoogleChronicleBackstory/ReleaseNotes/2_0_14.md
  Packs/GoogleChronicleBackstory/pack_metadata.json
Labels: Contribution, docs-approved, Partner, ready-for-instance-test, Contribution Form Filled

#17699 Adding fields core alert
  Packs/CommonTypes/IncidentFields/incidentfield-Alert_URL.json
  Packs/CommonTypes/ReleaseNotes/3_2_20.md
  Packs/CommonTypes/pack_metadata.json
  Packs/CoreAlertFields/IncidentFields/incidentfield-Misc.json
  Packs/CoreAlertFields/IncidentFields/incidentfield-URL.json
  Packs/CoreAlertFields/ReleaseNotes/1_0_18.md
  Packs/CoreAlertFields/pack_metadata.json
Labels: docs-approved

#17692 Unskip ArcherRSA TPB
  Tests/conf.json
Labels: docs-approved

#17640 Initial version fix
  Packs/ExpanseV2/pack_metadata.json
  Tests/Marketplace/Tests/marketplace_services_test.py
  Tests/Marketplace/marketplace_services.py
Labels: docs-approved

#17481 Adding credentials set support ms graph mail
  Packs/MicrosoftGraphMail/Integrations/MicrosoftGraphMail/MicrosoftGraphMail.py
  Packs/MicrosoftGraphMail/Integrations/MicrosoftGraphMail/MicrosoftGraphMail.yml
  Packs/MicrosoftGraphMail/Integrations/MicrosoftGraphMail/MicrosoftGraphMail_test.py
  Packs/MicrosoftGraphMail/ReleaseNotes/1_1_11.md
  Packs/MicrosoftGraphMail/ReleaseNotes/1_1_12.md
  Packs/MicrosoftGraphMail/pack_metadata.json
  Tests/known_words.txt
Labels: docs-approved

#17161 Http v2 script
  Packs/CommonScripts/ReleaseNotes/1_6_36.md
  Packs/CommonScripts/Scripts/HttpV2/HttpV2.py
  Packs/CommonScripts/Scripts/HttpV2/HttpV2.yml
  Packs/CommonScripts/Scripts/HttpV2/HttpV2_test.py
  Packs/CommonScripts/Scripts/HttpV2/README.md
  Packs/CommonScripts/TestPlaybooks/playbook-HttpV2-Test.yml
  Packs/CommonScripts/pack_metadata.json
  Tests/conf.json
Labels: docs-approved

#17708 PicusAutomation Update README
  Packs/PicusAutomation/README.md
Labels: Contribution, docs-approved, Partner, Contribution Form Filled

#17606 Fix dependencies metadata bug
  Tests/Marketplace/Tests/marketplace_services_test.py
  Tests/Marketplace/Tests/marketplace_statistics_test.py
  Tests/Marketplace/Tests/upload_packs_test.py
  Tests/Marketplace/copy_and_upload_packs.py
  Tests/Marketplace/marketplace_constants.py
  Tests/Marketplace/marketplace_services.py
  Tests/Marketplace/upload_packs.py
  Tests/private_build/upload_packs_private.py
Labels: docs-approved

#17719 Update README.md
  Packs/Slack/Integrations/SlackV3/README.md
Labels: Contribution, docs-approved, Contribution Form Filled, Community

#17723 AutoExtract Test - Fixed tasks related to URLs and Domains extractions according to the updated behavior
  Packs/Base/TestPlaybooks/playbook-Autoextract_-_Test.yml
Labels: docs-approved

#17664 Update README.md
  Packs/GenericSQL/Integrations/GenericSQL/README.md
Labels: Contribution, docs-approved

#17730 Increase timeout for Archer TPB
  Tests/conf.json
Labels: docs-approved

#17614 fix zscaler 406 keyerror message
  Packs/Zscaler/Integrations/Zscaler/Zscaler.py
  Packs/Zscaler/Integrations/Zscaler/Zscaler_test.py
  Packs/Zscaler/ReleaseNotes/1_1_17.md
  Packs/Zscaler/pack_metadata.json
Labels: docs-approved

#17467 UrlHaus enchantment
  Packs/URLHaus/.pack-ignore
  Packs/URLHaus/.secrets-ignore
  Packs/URLHaus/Integrations/URLHaus/README.md
  Packs/URLHaus/Integrations/URLHaus/URLHaus.py
  Packs/URLHaus/Integrations/URLHaus/URLHaus.yml
  Packs/URLHaus/Integrations/URLHaus/URLHaus_description.md
  Packs/URLHaus/Integrations/URLHaus/URLHaus_test.py
  Packs/URLHaus/Integrations/URLHaus/command_examples
  Packs/URLHaus/Integrations/URLHaus/test_data/domain_command.json
  Packs/URLHaus/Integrations/URLHaus/test_data/file_command.json
  Packs/URLHaus/Integrations/URLHaus/test_data/url_command.json
  Packs/URLHaus/ReleaseNotes/1_0_13.md
  Packs/URLHaus/TestPlaybooks/playbook-Test-URLhaus.yml
  Packs/URLHaus/pack_metadata.json
  Pipfile
Labels: docs-approved

#17705 searchincidentsv2: limit number of events
  Packs/CommonScripts/ReleaseNotes/1_6_37.md
  Packs/CommonScripts/Scripts/SearchIncidentsV2/SearchIncidentsV2.py
  Packs/CommonScripts/Scripts/SearchIncidentsV2/SearchIncidentsV2.yml
  Packs/CommonScripts/Scripts/SearchIncidentsV2/SearchIncidentsV2_test.py
  Packs/CommonScripts/pack_metadata.json
Labels: docs-approved

#15980 Update README.md
  Packs/EWS/Integrations/EWSv2/README.md
Labels: docs-approved

#17712 Update readme and metadata text
  Packs/PenfieldAI/Playbooks/Penfield_Assign.yml
  Packs/PenfieldAI/Playbooks/Penfield_Assign_README.md
  Packs/PenfieldAI/README.md
  Packs/PenfieldAI/ReleaseNotes/1_0_1.md
  Packs/PenfieldAI/Scripts/PenfieldAssign/PenfieldAssign.yml
  Packs/PenfieldAI/Scripts/PenfieldAssign/README.md
  Packs/PenfieldAI/pack_metadata.json
Labels: Contribution, docs-approved, Partner, Contribution Form Filled
