Repository demisto/content, pull requests merged in 2022-11, with the labels that each got.

#21969 Remove from_xdr_version from OneModelDev
  Packs/OnemodelDev/ModelingRules/OneModelDevModelingRules/OneModelDevModelingRules.yml
  Packs/OnemodelDev/ModelingRules/OneModelDevModelingRules_1_3/OneModelDevModelingRules_1_3.yml
  Packs/OnemodelDev/ReleaseNotes/1_0_1.md
  Packs/OnemodelDev/pack_metadata.json
Labels: docs-approved

#21977 Fix one modeldev 1 3
  Packs/OnemodelDev/ModelingRules/OneModelDevModelingRules_1_3/OneModelDevModelingRules_1_3.xif
  Packs/OnemodelDev/ReleaseNotes/1_0_2.md
  Packs/OnemodelDev/pack_metadata.json
Labels: docs-approved

#21979 OpenSSL Vulns
  Packs/CVE_2022_3786_and_CVE_2022_3602_-_OpenSSL_X.509_Buffer_Overflows/.pack-ignore
  Packs/CVE_2022_3786_and_CVE_2022_3602_-_OpenSSL_X.509_Buffer_Overflows/.secrets-ignore
  Packs/CVE_2022_3786_and_CVE_2022_3602_-_OpenSSL_X.509_Buffer_Overflows/Playbooks/playbook-CVE-2022-3786_&_CVE-2022-3602_-_OpenSSL_X.509_Buffer_Overflows.yml
  Packs/CVE_2022_3786_and_CVE_2022_3602_-_OpenSSL_X.509_Buffer_Overflows/Playbooks/playbook-CVE-2022-3786_&_CVE-2022-3602_-_OpenSSL_X.509_Buffer_Overflows_README.md
  Packs/CVE_2022_3786_and_CVE_2022_3602_-_OpenSSL_X.509_Buffer_Overflows/README.md
  Packs/CVE_2022_3786_and_CVE_2022_3602_-_OpenSSL_X.509_Buffer_Overflows/doc_files/CVE-2022-3786_&_CVE-2022-3602_-_OpenSSL_X.509_Buffer_Overflows.png
  Packs/CVE_2022_3786_and_CVE_2022_3602_-_OpenSSL_X.509_Buffer_Overflows/pack_metadata.json
  Packs/MajorBreachesInvestigationandResponse/ReleaseNotes/1_6_25.md
  Packs/MajorBreachesInvestigationandResponse/pack_metadata.json
Labels: docs-approved

#21942 Bugfix - ansible linux parse error
  Packs/AnsibleAlibabaCloud/.pack-ignore
  Packs/AnsibleAlibabaCloud/ReleaseNotes/1_0_3.md
  Packs/AnsibleAlibabaCloud/pack_metadata.json
  Packs/AnsibleAzure/.pack-ignore
  Packs/AnsibleAzure/ReleaseNotes/1_0_3.md
  Packs/AnsibleAzure/pack_metadata.json
  Packs/AnsibleCiscoIOS/.pack-ignore
  Packs/AnsibleCiscoIOS/ReleaseNotes/1_0_3.md
  Packs/AnsibleCiscoIOS/pack_metadata.json
  Packs/AnsibleCiscoNXOS/.pack-ignore
  Packs/AnsibleCiscoNXOS/ReleaseNotes/1_0_3.md
  Packs/AnsibleCiscoNXOS/pack_metadata.json
  Packs/AnsibleHetznerCloud/.pack-ignore
  Packs/AnsibleHetznerCloud/ReleaseNotes/1_0_3.md
  Packs/AnsibleHetznerCloud/pack_metadata.json
  Packs/AnsibleKubernetes/.pack-ignore
  Packs/AnsibleKubernetes/ReleaseNotes/1_0_3.md
  Packs/AnsibleKubernetes/pack_metadata.json
  Packs/AnsibleLinux/.pack-ignore
  Packs/AnsibleLinux/ReleaseNotes/1_0_6.md
  Packs/AnsibleLinux/pack_metadata.json
  Packs/AnsibleMicrosoftWindows/.pack-ignore
  Packs/AnsibleMicrosoftWindows/ReleaseNotes/1_0_5.md
  Packs/AnsibleMicrosoftWindows/pack_metadata.json
  Packs/AnsibleVMware/.pack-ignore
  Packs/AnsibleVMware/ReleaseNotes/1_0_3.md
  Packs/AnsibleVMware/pack_metadata.json
  Packs/ApiModules/.pack-ignore
  Packs/ApiModules/.secrets-ignore
  Packs/ApiModules/Scripts/AnsibleApiModule/AnsibleApiModule.py
  Packs/ApiModules/Scripts/AnsibleApiModule/AnsibleApiModule_test.py
  Packs/ApiModules/Scripts/AnsibleApiModule/TestsInput/stdout.txt
Labels: docs-approved

#21875 Cisco networks api fix
  Packs/CiscoStealthwatch/Integrations/CiscoStealthwatch/CiscoStealthwatch.py
  Packs/CiscoStealthwatch/Integrations/CiscoStealthwatch/CiscoStealthwatch.yml
  Packs/CiscoStealthwatch/Integrations/CiscoStealthwatch/CiscoStealthwatch_test.py
  Packs/CiscoStealthwatch/ReleaseNotes/1_0_7.md
  Packs/CiscoStealthwatch/pack_metadata.json
Labels: docs-approved, ForceMerge

#21966 update poetry after sdk v1.7.7 release
  poetry.lock
  pyproject.toml
Labels: docs-approved

#21989 Fixed yml file OneModelDev.
  Packs/OnemodelDev/ModelingRules/OneModelDevModelingRules_1_3/OneModelDevModelingRules_1_3_schema.json
  Packs/OnemodelDev/ReleaseNotes/1_0_1.md
  Packs/OnemodelDev/ReleaseNotes/1_0_2.md
  Packs/OnemodelDev/ReleaseNotes/1_0_3.md
  Packs/OnemodelDev/pack_metadata.json
Labels: docs-approved

#21827 Block Indicators - Generic v2/v3 block non-malicious hashes by default
  Packs/CommonPlaybooks/.pack-ignore
  Packs/CommonPlaybooks/Playbooks/playbook-Block_Indicators_-_Generic_v2.yml
  Packs/CommonPlaybooks/Playbooks/playbook-Block_Indicators_-_Generic_v2_README.md
  Packs/CommonPlaybooks/Playbooks/playbook-Block_Indicators_-_Generic_v3.yml
  Packs/CommonPlaybooks/Playbooks/playbook-Block_Indicators_-_Generic_v3_README.md
  Packs/CommonPlaybooks/Playbooks/playbook-Block_URL_-_Generic_v2.yml
  Packs/CommonPlaybooks/Playbooks/playbook-Block_URL_-_Generic_v2_README.md
  Packs/CommonPlaybooks/ReleaseNotes/2_3_8.md
  Packs/CommonPlaybooks/doc_files/Block_Indicators_-_Generic_v2.png
  Packs/CommonPlaybooks/doc_files/Block_Indicators_-_Generic_v3.png
  Packs/CommonPlaybooks/doc_files/Block_URL_-_Generic_v2.png
  Packs/CommonPlaybooks/pack_metadata.json
Labels: docs-approved, release-notes-only

#21153 XDR IOCs - custom severity
  Packs/CortexXDR/Integrations/XDR_iocs/XDR_iocs.py
  Packs/CortexXDR/Integrations/XDR_iocs/XDR_iocs.yml
  Packs/CortexXDR/Integrations/XDR_iocs/XDR_iocs_description.md
  Packs/CortexXDR/Integrations/XDR_iocs/XDR_iocs_test.py
  Packs/CortexXDR/ReleaseNotes/4_9_0.md
  Packs/CortexXDR/pack_metadata.json
Labels: docs-approved

#21821 XSIAM IOC Alert
  Packs/Core/Playbooks/playbook-IOC_Alert.yml
  Packs/Core/Playbooks/playbook-IOC_Alert_README.md
  Packs/Core/ReleaseNotes/1_3_14.md
  Packs/Core/doc_files/IOC_Alert.png
  Packs/Core/pack_metadata.json
Labels: docs-approved

#22001 RBR | openssl enhancements
  Packs/CVE_2022_3786_and_CVE_2022_3602_-_OpenSSL_X.509_Buffer_Overflows/Playbooks/playbook-CVE-2022-3786_&_CVE-2022-3602_-_OpenSSL_X.509_Buffer_Overflows.yml
  Packs/CVE_2022_3786_and_CVE_2022_3602_-_OpenSSL_X.509_Buffer_Overflows/Playbooks/playbook-CVE-2022-3786_&_CVE-2022-3602_-_OpenSSL_X.509_Buffer_Overflows_README.md
  Packs/CVE_2022_3786_and_CVE_2022_3602_-_OpenSSL_X.509_Buffer_Overflows/README.md
  Packs/CVE_2022_3786_and_CVE_2022_3602_-_OpenSSL_X.509_Buffer_Overflows/ReleaseNotes/1_0_1.md
  Packs/CVE_2022_3786_and_CVE_2022_3602_-_OpenSSL_X.509_Buffer_Overflows/doc_files/CVE-2022-3786_&_CVE-2022-3602_-_OpenSSL_X.509_Buffer_Overflows.png
  Packs/CVE_2022_3786_and_CVE_2022_3602_-_OpenSSL_X.509_Buffer_Overflows/pack_metadata.json
Labels: docs-approved

#21955 fixed a bug in service now
  Packs/ServiceNow/.pack-ignore
  Packs/ServiceNow/Integrations/ServiceNowv2/ServiceNowv2.py
  Packs/ServiceNow/Integrations/ServiceNowv2/ServiceNowv2.yml
  Packs/ServiceNow/Integrations/ServiceNowv2/ServiceNowv2_test.py
  Packs/ServiceNow/ReleaseNotes/2_4_1.md
  Packs/ServiceNow/pack_metadata.json
Labels: docs-approved

#21598 Open cti bug
  Packs/FeedOpenCTI/.pack-ignore
  Packs/FeedOpenCTI/Integrations/FeedOpenCTI_v4/FeedOpenCTI_v4.py
  Packs/FeedOpenCTI/Integrations/FeedOpenCTI_v4/FeedOpenCTI_v4.yml
  Packs/FeedOpenCTI/ReleaseNotes/2_0_6.md
  Packs/FeedOpenCTI/pack_metadata.json
  Packs/OpenCTI/.pack-ignore
  Packs/OpenCTI/Integrations/OpenCTI/OpenCTI.py
  Packs/OpenCTI/Integrations/OpenCTI/OpenCTI.yml
  Packs/OpenCTI/ReleaseNotes/1_0_4.md
  Packs/OpenCTI/pack_metadata.json
  Tests/conf.json
Labels: docs-approved

#21984 LogRhythmRestv2 fix
  Packs/LogRhythmRest/.pack-ignore
  Packs/LogRhythmRest/Integrations/LogRhythmRestV2/LogRhythmRestV2.py
  Packs/LogRhythmRest/Integrations/LogRhythmRestV2/LogRhythmRestV2.yml
  Packs/LogRhythmRest/ReleaseNotes/2_0_13.md
  Packs/LogRhythmRest/pack_metadata.json
Labels: docs-approved

#21997 Adding Core pack to XSIAM build.
  Tests/scripts/collect_tests/collect_tests.py
  Tests/scripts/collect_tests/constants.py
  Tests/scripts/collect_tests/utils.py
  Tests/scripts/infrastructure_tests/test_collect_tests.py
  Tests/scripts/infrastructure_tests/tests_data/collect_tests/A_xsiam/Packs/CoreAlertFields/.pack_ignore
  Tests/scripts/infrastructure_tests/tests_data/collect_tests/A_xsiam/Packs/CoreAlertFields/.secrets-ignore
  Tests/scripts/infrastructure_tests/tests_data/collect_tests/A_xsiam/Packs/CoreAlertFields/Integrations/myIntegration/myIntegration.py
  Tests/scripts/infrastructure_tests/tests_data/collect_tests/A_xsiam/Packs/CoreAlertFields/Integrations/myIntegration/myIntegration.yml
  Tests/scripts/infrastructure_tests/tests_data/collect_tests/A_xsiam/Packs/CoreAlertFields/pack_metadata.json
  Tests/scripts/infrastructure_tests/tests_data/collect_tests/B_xsiam/Packs/CoreAlertFields/.pack_ignore
  Tests/scripts/infrastructure_tests/tests_data/collect_tests/B_xsiam/Packs/CoreAlertFields/.secrets-ignore
  Tests/scripts/infrastructure_tests/tests_data/collect_tests/B_xsiam/Packs/CoreAlertFields/Integrations/myIntegration/myIntegration.py
  Tests/scripts/infrastructure_tests/tests_data/collect_tests/B_xsiam/Packs/CoreAlertFields/Integrations/myIntegration/myIntegration.yml
  Tests/scripts/infrastructure_tests/tests_data/collect_tests/B_xsiam/Packs/CoreAlertFields/pack_metadata.json
  Tests/scripts/infrastructure_tests/tests_data/collect_tests/C/Packs/CoreAlertFields/.pack_ignore
  Tests/scripts/infrastructure_tests/tests_data/collect_tests/C/Packs/CoreAlertFields/.secrets-ignore
  Tests/scripts/infrastructure_tests/tests_data/collect_tests/C/Packs/CoreAlertFields/Integrations/myIntegration/myIntegration.py
  Tests/scripts/infrastructure_tests/tests_data/collect_tests/C/Packs/CoreAlertFields/Integrations/myIntegration/myIntegration.yml
  Tests/scripts/infrastructure_tests/tests_data/collect_tests/C/Packs/CoreAlertFields/pack_metadata.json
  Tests/scripts/infrastructure_tests/tests_data/collect_tests/E/Packs/CoreAlertFields/.pack_ignore
  Tests/scripts/infrastructure_tests/tests_data/collect_tests/E/Packs/CoreAlertFields/.secrets-ignore
  Tests/scripts/infrastructure_tests/tests_data/collect_tests/E/Packs/CoreAlertFields/Integrations/myIntegration/myIntegration.py
  Tests/scripts/infrastructure_tests/tests_data/collect_tests/E/Packs/CoreAlertFields/Integrations/myIntegration/myIntegration.yml
  Tests/scripts/infrastructure_tests/tests_data/collect_tests/E/Packs/CoreAlertFields/pack_metadata.json
  Tests/scripts/infrastructure_tests/tests_data/collect_tests/L_XSIAM/Packs/CoreAlertFields/.pack_ignore
  Tests/scripts/infrastructure_tests/tests_data/collect_tests/L_XSIAM/Packs/CoreAlertFields/.secrets-ignore
  Tests/scripts/infrastructure_tests/tests_data/collect_tests/L_XSIAM/Packs/CoreAlertFields/Integrations/myIntegration/myIntegration.py
  Tests/scripts/infrastructure_tests/tests_data/collect_tests/L_XSIAM/Packs/CoreAlertFields/Integrations/myIntegration/myIntegration.yml
  Tests/scripts/infrastructure_tests/tests_data/collect_tests/L_XSIAM/Packs/CoreAlertFields/pack_metadata.json
Labels: docs-approved

#22019 BRB | OpenSSL Adding Threat Brief to playbook
  Packs/CVE_2022_3786_and_CVE_2022_3602_-_OpenSSL_X.509_Buffer_Overflows/Playbooks/playbook-CVE-2022-3786_&_CVE-2022-3602_-_OpenSSL_X.509_Buffer_Overflows.yml
  Packs/CVE_2022_3786_and_CVE_2022_3602_-_OpenSSL_X.509_Buffer_Overflows/Playbooks/playbook-CVE-2022-3786_&_CVE-2022-3602_-_OpenSSL_X.509_Buffer_Overflows_README.md
  Packs/CVE_2022_3786_and_CVE_2022_3602_-_OpenSSL_X.509_Buffer_Overflows/README.md
  Packs/CVE_2022_3786_and_CVE_2022_3602_-_OpenSSL_X.509_Buffer_Overflows/ReleaseNotes/1_0_2.md
  Packs/CVE_2022_3786_and_CVE_2022_3602_-_OpenSSL_X.509_Buffer_Overflows/pack_metadata.json
Labels: docs-approved

#21793 Teams docs
  Packs/MicrosoftTeams/Integrations/MicrosoftTeams/MicrosoftTeams.py
  Packs/MicrosoftTeams/Integrations/MicrosoftTeams/MicrosoftTeams.yml
  Packs/MicrosoftTeams/Integrations/MicrosoftTeams/README.md
  Packs/MicrosoftTeams/ReleaseNotes/1_2_1.md
  Packs/MicrosoftTeams/pack_metadata.json
Labels: docs-approved

#21741 Fix release notes in marketplace
  Packs/CommonTypes/ReleaseNotes/3_3_22.md
  Packs/MicrosoftTeams/ReleaseNotes/1_2_0.md
  Packs/OnemodelDev/ReleaseNotes/1_0_1.md
  Packs/OnemodelDev/ReleaseNotes/1_0_2.md
  Packs/PrismaSaasSecurity/ReleaseNotes/2_0_6.md
  Tests/Marketplace/Tests/marketplace_services_test.py
  Tests/Marketplace/marketplace_constants.py
  Tests/Marketplace/marketplace_services.py
  Tests/Marketplace/upload_packs.py
Labels: docs-approved

#21999 CrowdStrike Falcon - fix cs-falcon-run-script command
  Packs/CrowdStrikeFalcon/Integrations/CrowdStrikeFalcon/CrowdStrikeFalcon.py
  Packs/CrowdStrikeFalcon/Integrations/CrowdStrikeFalcon/CrowdStrikeFalcon.yml
  Packs/CrowdStrikeFalcon/ReleaseNotes/1_9_8.md
  Packs/CrowdStrikeFalcon/pack_metadata.json
Labels: docs-approved

#21830 [VMware] to py3
  Packs/VMware/Integrations/VMware/VMware.py
  Packs/VMware/Integrations/VMware/VMware.yml
  Packs/VMware/Integrations/VMware/VMware_test.py
  Packs/VMware/ReleaseNotes/1_2_4.md
  Packs/VMware/pack_metadata.json
Labels: docs-approved

#21863 Little infra change + tests
  Tests/scripts/collect_tests/collect_tests.py
  Tests/scripts/infrastructure_tests/tests_data/collect_tests/A_xsiam/Tests/conf.json
  Tests/scripts/infrastructure_tests/tests_data/collect_tests/B_xsiam/Tests/conf.json
  Tests/scripts/infrastructure_tests/tests_data/collect_tests/C/Tests/conf.json
  Tests/scripts/infrastructure_tests/tests_data/collect_tests/E/Tests/conf.json
Labels: docs-approved

#21996 fix duplicates
  Tests/Marketplace/Tests/test_data/TestPack/ModelingRules/external-modelingrule-TestModelingRules.yml
  Tests/Marketplace/Tests/test_data/TestPack/ModelingRules/modelingrule-TestModelingRules.yml
  Tests/Marketplace/marketplace_services.py
Labels: docs-approved

#21967 VirusTotal (API v3) - fix vt-comments-get
  Packs/VirusTotal/Integrations/VirusTotalV3/VirusTotalV3.py
  Packs/VirusTotal/Integrations/VirusTotalV3/VirusTotalV3.yml
  Packs/VirusTotal/ReleaseNotes/2_4_12.md
  Packs/VirusTotal/pack_metadata.json
Labels: docs-approved

#22022 Whois - handeling unvalid dates
  Packs/Whois/Integrations/Whois/Whois.py
  Packs/Whois/Integrations/Whois/Whois_test.py
  Packs/Whois/ReleaseNotes/1_4_2.md
  Packs/Whois/pack_metadata.json
Labels: docs-approved

#22032 updated readme, yml files and Test_Bitbucket playbook
  Packs/Bitbucket/Integrations/Bitbucket/Bitbucket.yml
  Packs/Bitbucket/Integrations/Bitbucket/README.md
  Packs/Bitbucket/ReleaseNotes/1_0_1.md
  Packs/Bitbucket/TestPlaybooks/playbook-Test_Bitbucket.yml
  Packs/Bitbucket/pack_metadata.json
Labels: docs-approved

#22040 remove where is the egg from marketplace
  Packs/WhereIsTheEgg/pack_metadata.json
  Tests/Marketplace/core_packs_list.json
Labels: docs-approved

#21978 Cortex Attack Surface Management 2.0.0
  Packs/CortexAttackSurfaceManagement/.secrets-ignore
  Packs/CortexAttackSurfaceManagement/IncidentFields/incidentfield-ASM_-_Tags.json
  Packs/CortexAttackSurfaceManagement/Lists/list-RemediationGuidance.json
  Packs/CortexAttackSurfaceManagement/Playbooks/Cortex_ASM_-_ASM_Alert.yml
  Packs/CortexAttackSurfaceManagement/Playbooks/Cortex_ASM_-_ASM_Alert_README.md
  Packs/CortexAttackSurfaceManagement/Playbooks/Cortex_ASM_-_CMDB_Enrichment.yml
  Packs/CortexAttackSurfaceManagement/Playbooks/Cortex_ASM_-_Detect_Service.yml
  Packs/CortexAttackSurfaceManagement/Playbooks/Cortex_ASM_-_Detect_Service_README.md
  Packs/CortexAttackSurfaceManagement/Playbooks/Cortex_ASM_-_Enrichment.yml
  Packs/CortexAttackSurfaceManagement/Playbooks/Cortex_ASM_-_Enrichment_README.md
  Packs/CortexAttackSurfaceManagement/Playbooks/Cortex_ASM_-_Extract_IP_Indicator.yml
  Packs/CortexAttackSurfaceManagement/Playbooks/Cortex_ASM_-_Remediation_Guidance.yml
  Packs/CortexAttackSurfaceManagement/Playbooks/Cortex_ASM_-_Remediation_Guidance_README.md
  Packs/CortexAttackSurfaceManagement/Playbooks/Cortex_ASM_-_Vulnerability_Management_Enrichment.yml
  Packs/CortexAttackSurfaceManagement/README.md
  Packs/CortexAttackSurfaceManagement/ReleaseNotes/1_2_0.md
  Packs/CortexAttackSurfaceManagement/Scripts/GenerateASMReport/GenerateASMReport.py
  Packs/CortexAttackSurfaceManagement/Scripts/GenerateASMReport/GenerateASMReport.yml
  Packs/CortexAttackSurfaceManagement/Scripts/GenerateASMReport/GenerateASMReport_test.py
  Packs/CortexAttackSurfaceManagement/Scripts/GenerateASMReport/README.md
  Packs/CortexAttackSurfaceManagement/Scripts/GenerateASMReport/test_data/args.json
  Packs/CortexAttackSurfaceManagement/Scripts/GenerateASMReport/test_data/sanepdf_raw.json
  Packs/CortexAttackSurfaceManagement/Scripts/GenerateASMReport/test_data/template.json
  Packs/CortexAttackSurfaceManagement/doc_files/Cortex_ASM_-_ASM_Alert.png
  Packs/CortexAttackSurfaceManagement/doc_files/Cortex_ASM_-_Detect_Service.png
  Packs/CortexAttackSurfaceManagement/doc_files/Cortex_ASM_-_Enrichment.png
  Packs/CortexAttackSurfaceManagement/doc_files/Cortex_ASM_-_Remediation_Guidance.png
  Packs/CortexAttackSurfaceManagement/doc_files/GenerateASMReport.png
  Packs/CortexAttackSurfaceManagement/pack_metadata.json
Labels: Contribution, docs-approved, Contribution Form Filled, Community

#21844 One_DataModel_Ready_2
  Packs/BrocadeSwitch/ModelingRules/BrocadeSwitch/BrocadeSwitch.xif
  Packs/BrocadeSwitch/ModelingRules/BrocadeSwitch_1_3/BrocadeSwitch_1_3.xif
  Packs/BrocadeSwitch/ModelingRules/BrocadeSwitch_1_3/BrocadeSwitch_1_3.yml
  Packs/BrocadeSwitch/ModelingRules/BrocadeSwitch_1_3/BrocadeSwitch_1_3_schema.json
  Packs/BrocadeSwitch/ReleaseNotes/1_0_2.md
  Packs/BrocadeSwitch/pack_metadata.json
  Packs/CiscoASA/ModelingRules/CiscoASA_1_3/CiscoASA_1_3.xif
  Packs/CiscoASA/ModelingRules/CiscoASA_1_3/CiscoASA_1_3.yml
  Packs/CiscoASA/ModelingRules/CiscoASA_1_3/CiscoASA_1_3_schema.json
  Packs/CiscoASA/ReleaseNotes/1_0_24.md
  Packs/CiscoASA/pack_metadata.json
  Packs/JuniperSRX/ModelingRules/JuniperSRX_1_3/JuniperSRX_1_3.xif
  Packs/JuniperSRX/ModelingRules/JuniperSRX_1_3/JuniperSRX_1_3.yml
  Packs/JuniperSRX/ModelingRules/JuniperSRX_1_3/JuniperSRX_1_3_schema.json
  Packs/JuniperSRX/ReleaseNotes/1_0_1.md
  Packs/JuniperSRX/pack_metadata.json
  Packs/Mimecast/ModelingRules/MimecastModelingRules_1_3/MimecastModelingRules_1_3.xif
  Packs/Mimecast/ModelingRules/MimecastModelingRules_1_3/MimecastModelingRules_1_3.yml
  Packs/Mimecast/ModelingRules/MimecastModelingRules_1_3/MimecastModelingRules_1_3_schema.json
  Packs/Mimecast/ReleaseNotes/2_1_2.md
  Packs/Mimecast/pack_metadata.json
  Packs/ProofpointTAP/ModelingRules/ProofpointTAPModelingRules_1_3/ProofpointTAPModelingRules_1_3.xif
  Packs/ProofpointTAP/ModelingRules/ProofpointTAPModelingRules_1_3/ProofpointTAPModelingRules_1_3.yml
  Packs/ProofpointTAP/ModelingRules/ProofpointTAPModelingRules_1_3/ProofpointTAPModelingRules_1_3_schema.json
  Packs/ProofpointTAP/ReleaseNotes/1_1_19.md
  Packs/ProofpointTAP/pack_metadata.json
  Packs/SafeNet_Trusted_Access/ModelingRules/SafeNetTrustedAccessModelingRules_1_3/SafeNetTrustedAccessModelingRules_1_3.xif
  Packs/SafeNet_Trusted_Access/ModelingRules/SafeNetTrustedAccessModelingRules_1_3/SafeNetTrustedAccessModelingRules_1_3.yml
  Packs/SafeNet_Trusted_Access/ModelingRules/SafeNetTrustedAccessModelingRules_1_3/SafeNetTrustedAccessModelingRules_1_3_schema.json
  Packs/SafeNet_Trusted_Access/ReleaseNotes/2_0_5.md
  Packs/SafeNet_Trusted_Access/pack_metadata.json
  Packs/Salesforce/ModelingRules/Salesforce_1_3/Salesforce_1_3.xif
  Packs/Salesforce/ModelingRules/Salesforce_1_3/Salesforce_1_3.yml
  Packs/Salesforce/ModelingRules/Salesforce_1_3/Salesforce_1_3_schema.json
  Packs/Salesforce/ReleaseNotes/2_0_5.md
  Packs/Salesforce/pack_metadata.json
  Packs/Tableau/ModelingRules/Tableau_1_3/Tableau_1_3.xif
  Packs/Tableau/ModelingRules/Tableau_1_3/Tableau_1_3.yml
  Packs/Tableau/ModelingRules/Tableau_1_3/Tableau_1_3_schema.json
  Packs/Tableau/ReleaseNotes/1_0_2.md
  Packs/Tableau/pack_metadata.json
  Packs/VMwareESXi/ModelingRules/VMwareESXI_1_3/VMwareESXI_1_3.xif
  Packs/VMwareESXi/ModelingRules/VMwareESXI_1_3/VMwareESXI_1_3.yml
  Packs/VMwareESXi/ModelingRules/VMwareESXI_1_3/VMwareESXI_1_3_schema.json
  Packs/VMwareESXi/ReleaseNotes/1_0_1.md
  Packs/VMwareESXi/pack_metadata.json
  Packs/VMwareVCenter/ModelingRules/VMwareVcenter_1_3/VMwareVcenter_1_3.xif
  Packs/VMwareVCenter/ModelingRules/VMwareVcenter_1_3/VMwareVcenter_1_3.yml
  Packs/VMwareVCenter/ModelingRules/VMwareVcenter_1_3/VMwareVcenter_1_3_schema.json
  Packs/VMwareVCenter/ReleaseNotes/1_0_1.md
  Packs/VMwareVCenter/pack_metadata.json
  Packs/ZscalerZPA/ModelingRules/ZscalerZPA_1_3/ZscalerZPA_1_3.xif
  Packs/ZscalerZPA/ModelingRules/ZscalerZPA_1_3/ZscalerZPA_1_3.yml
  Packs/ZscalerZPA/ModelingRules/ZscalerZPA_1_3/ZscalerZPA_1_3_schema.json
  Packs/ZscalerZPA/Release Notes/1_0_0.md
  Packs/ZscalerZPA/ReleaseNotes/1_0_1.md
  Packs/ZscalerZPA/pack_metadata.json
  Tests/known_words.txt
Labels: docs-approved

#22063 rm-tags-not-on-packs-101
  Tests/Marketplace/approved_tags.json
Labels: docs-approved

#22046 tags/usecases/categories 250-300
  Packs/CyrenInboxSecurity/pack_metadata.json
  Packs/DB2/pack_metadata.json
  Packs/Darktrace/pack_metadata.json
  Packs/DeHashed/pack_metadata.json
  Packs/DeduplicateValuesbyKey/pack_metadata.json
  Packs/DefaultPlaybook/pack_metadata.json
  Packs/Dig/pack_metadata.json
  Packs/DigitalShadows/pack_metadata.json
  Packs/EWS/pack_metadata.json
  Packs/EWSMailSender/pack_metadata.json
  Packs/EasyVista/pack_metadata.json
  Packs/ElasticsearchMonitoring/pack_metadata.json
  Packs/EmailCommunication/pack_metadata.json
  Packs/EmailRepIO/pack_metadata.json
  Packs/EmployeeOffboarding/pack_metadata.json
  Packs/Envoy/pack_metadata.json
  Packs/FeedDHS/pack_metadata.json
  Packs/dnstwist/pack_metadata.json
Labels: docs-approved

#22059 Upgraded parseEmailFilesV2 docker image
  Packs/CommonScripts/ReleaseNotes/1_9_6.md
  Packs/CommonScripts/Scripts/ParseEmailFilesV2/ParseEmailFilesV2.yml
  Packs/CommonScripts/pack_metadata.json
Labels: docs-approved

#22050 Add freeze_time to test_case_insensitive
  Packs/Base/Scripts/CommonServerPython/CommonServerPython_test.py
Labels: docs-approved

#20254 [STAGING] Introduce content graph to content
  .github/CODEOWNERS
  .gitignore
  .gitlab/ci/.gitlab-ci.yml
  .gitlab/ci/slack-notify.yml
  .gitlab/ci/staging.yml
  Tests/Marketplace/Tests/marketplace_services_test.py
  Tests/Marketplace/Tests/upload_packs_test.py
  Tests/Marketplace/marketplace_services.py
  Tests/Marketplace/upload_packs.py
  Tests/scripts/collect_tests/__init__.py
  Tests/scripts/collect_tests/collect_tests.py
  Tests/scripts/collect_tests/id_set.py
  Tests/scripts/create_artifacts_graph/create_artifacts.py
  Tests/scripts/prepare_content_packs_for_testing.sh
  Tests/scripts/upload_artifacts.sh
  Tests/scripts/utils/compare_staging_graph.py
  poetry.lock
  pyproject.toml
Labels: docs-approved

#22061 update Crowdstrike readme
  Packs/CrowdStrikeFalcon/Integrations/CrowdStrikeFalcon/CrowdStrikeFalcon.yml
  Packs/CrowdStrikeFalcon/Integrations/CrowdStrikeFalcon/README.md
  Packs/CrowdStrikeFalcon/ReleaseNotes/1_9_9.md
  Packs/CrowdStrikeFalcon/pack_metadata.json
Labels: docs-approved

#21985 add close mirrored XSOAR offenses and user query params comment
  Packs/QRadar/Integrations/QRadar_v3/QRadar_v3.py
  Packs/QRadar/Integrations/QRadar_v3/QRadar_v3.yml
  Packs/QRadar/Integrations/QRadar_v3/README.md
  Packs/QRadar/ReleaseNotes/2_3_2.md
  Packs/QRadar/pack_metadata.json
Labels: docs-approved

#22071 hotifx upload filtering
  Tests/Marketplace/upload_packs.py
Labels: docs-approved

#21748 TestCollect: collect packs from which files were removed
  Tests/scripts/collect_tests/collect_tests.py
  Tests/scripts/collect_tests/utils.py
  Tests/scripts/infrastructure_tests/collect_tests.log
  Tests/scripts/infrastructure_tests/test_collect_tests.py
Labels: docs-approved

#22079 removed "Delete Context Subplaybook Test" from nightly
  Tests/conf.json
Labels: docs-approved

#22027 Add Slack Logging Info
  Packs/Slack/Integrations/SlackV3/README.md
  Packs/Slack/Integrations/SlackV3/SlackV3.py
  Packs/Slack/Integrations/SlackV3/SlackV3.yml
  Packs/Slack/ReleaseNotes/3_1_10.md
  Packs/Slack/pack_metadata.json
Labels: docs-approved

#21078 New_url_formatter
  Packs/CommonScripts/ReleaseNotes/1_9_7.md
  Packs/CommonScripts/Scripts/FormatURL/FormatURL.py
  Packs/CommonScripts/Scripts/FormatURL/FormatURL.yml
  Packs/CommonScripts/Scripts/FormatURL/FormatURL_test.py
  Packs/CommonScripts/TestPlaybooks/FormatURL-Test.yml
  Packs/CommonScripts/pack_metadata.json
Labels: docs-approved

#21949 Ews0365 auth bug
  Packs/EWS/.pack-ignore
  Packs/EWS/Integrations/SecurityAndCompliance/SecurityAndCompliance.ps1
  Packs/EWS/Integrations/SecurityAndCompliance/SecurityAndCompliance.yml
  Packs/EWS/ReleaseNotes/1_14_4.md
  Packs/EWS/pack_metadata.json
  Tests/conf.json
Labels: docs-approved, release-notes-only

#22058 remove irrelevant tests from conf.json
  Tests/conf.json
Labels: docs-approved

#22030 Xfe fix test playbook
  Packs/XForceExchange/TestPlaybooks/playbook-Test_XFE_v2.yml
Labels: docs-approved

#22077 Mp packs revamp 450 500
  Packs/FeedJSON/pack_metadata.json
  Packs/FeedMajesticMillion/pack_metadata.json
  Packs/FeedMalwareBazaar/pack_metadata.json
  Packs/FeedMitreAttack/pack_metadata.json
  Packs/FeedMitreAttackv2/pack_metadata.json
  Packs/JARM/pack_metadata.json
  Packs/JWT/pack_metadata.json
  Packs/Jq/pack_metadata.json
  Packs/JsonUnescape/pack_metadata.json
  Packs/KELARaDark/pack_metadata.json
  Packs/Koodous/pack_metadata.json
  Packs/LINENotify/pack_metadata.json
  Packs/LSASSCredentialDumping/pack_metadata.json
  Packs/Lacework/pack_metadata.json
  Packs/Lansweeper/pack_metadata.json
  Packs/Lastline/pack_metadata.json
  Packs/Linkshadow/pack_metadata.json
  Packs/LogPoint_SIEM_Integration/pack_metadata.json
  Packs/Logzio/pack_metadata.json
  Packs/Lost_Stolen_Device/pack_metadata.json
  Packs/Luminate/pack_metadata.json
  Packs/ML/pack_metadata.json
  Packs/MS-ISAC/pack_metadata.json
  Packs/MailListener/pack_metadata.json
  Packs/MailListener_-_POP3/pack_metadata.json
  Packs/MailSenderNew/pack_metadata.json
  Packs/Malware/pack_metadata.json
  Packs/MalwareBazaar/pack_metadata.json
  Packs/MalwareInvestigationAndResponse/pack_metadata.json
  Packs/MitreCaldera/pack_metadata.json
  Packs/PowershellPayloadResponse/pack_metadata.json
  Packs/WinRM/pack_metadata.json
  Packs/jamf/pack_metadata.json
Labels: docs-approved

#21731 hiding packs stage 3
  Packs/Malwr/pack_metadata.json
  Packs/Moloch/pack_metadata.json
  Packs/SandBlastAppliance/pack_metadata.json
  Packs/Sandblast/pack_metadata.json
  Packs/Threat_Crowd/Integrations/ThreatCrowd_v2/ThreatCrowd_v2.py
  Packs/Threat_Crowd/Integrations/ThreatCrowd_v2/ThreatCrowd_v2.yml
  Packs/Threat_Crowd/ReleaseNotes/2_0_8.md
  Packs/Threat_Crowd/pack_metadata.json
  Packs/VirusTotal-Private_API/pack_metadata.json
  Packs/trendMicroDsm/pack_metadata.json
Labels: docs-approved

#22067 Teams bug
  Packs/MicrosoftTeams/Integrations/MicrosoftTeams/MicrosoftTeams.py
  Packs/MicrosoftTeams/Integrations/MicrosoftTeams/MicrosoftTeams_test.py
  Packs/MicrosoftTeams/ReleaseNotes/1_2_3.md
  Packs/MicrosoftTeams/pack_metadata.json
Labels: docs-approved

#22084 tags/usecases/cateogires 366-410
  Packs/GSuiteAdmin/pack_metadata.json
  Packs/GSuiteSecurityAlertCenter/pack_metadata.json
  Packs/GoogleCalendar/pack_metadata.json
  Packs/GoogleCloudCompute/pack_metadata.json
  Packs/GoogleCloudFunctions/pack_metadata.json
  Packs/GoogleCloudSCC/pack_metadata.json
  Packs/GoogleCloudStorage/pack_metadata.json
  Packs/GoogleCloudTranslate/pack_metadata.json
  Packs/GoogleDocs/pack_metadata.json
  Packs/GoogleDrive/pack_metadata.json
  Packs/GoogleKeyManagementService/pack_metadata.json
  Packs/GoogleKubernetesEngine/pack_metadata.json
  Packs/GoogleMaps/pack_metadata.json
  Packs/GooglePubSub/pack_metadata.json
  Packs/GoogleResourceManager/pack_metadata.json
  Packs/GoogleSheets/pack_metadata.json
  Packs/GoogleVault/pack_metadata.json
  Packs/GoogleVisionAPI/pack_metadata.json
  Packs/Gophish/pack_metadata.json
  Packs/Grafana/pack_metadata.json
  Packs/GreatHorn/pack_metadata.json
  Packs/GreyNoise/pack_metadata.json
  Packs/GroupIB_ThreatIntelligenceAttribution/pack_metadata.json
  Packs/GsuiteAuditor/pack_metadata.json
  Packs/GuardiCore/pack_metadata.json
  Packs/Guidance_Encase_Endpoint/pack_metadata.json
  Packs/HIPAA-BreachNotification/pack_metadata.json
  Packs/HackerOne/pack_metadata.json
  Packs/HealthCheck/pack_metadata.json
  Packs/HelloIAMWorld/pack_metadata.json
  Packs/HelloWorld/pack_metadata.json
Labels: docs-approved

#22093 hide packs 107
  Packs/AzureActiveDirectory/pack_metadata.json
  Packs/DeprecatedContent/pack_metadata.json
  Packs/HybridAnalysis/pack_metadata.json
  Packs/Symantec_Advanced_Threat_Protection/pack_metadata.json
Labels: docs-approved

#22094 mp_revamp_500-550
  Packs/FeedMandiant/pack_metadata.json
  Packs/FeedMicrosoftIntune/pack_metadata.json
  Packs/ManageEngine_PAM360/pack_metadata.json
  Packs/Mantis/pack_metadata.json
  Packs/MapPattern/pack_metadata.json
  Packs/MapRegex/pack_metadata.json
  Packs/MarkdownToHTML/pack_metadata.json
  Packs/Mattermost/pack_metadata.json
  Packs/MaxList/pack_metadata.json
  Packs/McAfeeWebGateway/pack_metadata.json
  Packs/McAfee_DXL/pack_metadata.json
  Packs/MergeDictArray/pack_metadata.json
  Packs/MicrosoftAdvancedThreatAnalytics/pack_metadata.json
  Packs/MicrosoftCloudAppSecurity/pack_metadata.json
  Packs/MicrosoftGraphAPI/pack_metadata.json
  Packs/MicrosoftGraphApplications/pack_metadata.json
  Packs/MicrosoftGraphCalendar/pack_metadata.json
  Packs/MicrosoftGraphFiles/pack_metadata.json
  Packs/MicrosoftGraphGroups/pack_metadata.json
  Packs/MicrosoftGraphIdentityandAccess/pack_metadata.json
  Packs/MicrosoftGraphMail/pack_metadata.json
  Packs/MicrosoftGraphUser/pack_metadata.json
  Packs/MicrosoftManagementActivity/pack_metadata.json
  Packs/Mimecast/pack_metadata.json
  Packs/MinList/pack_metadata.json
  Packs/ModulesManagement/pack_metadata.json
  Packs/Moloch/pack_metadata.json
  Packs/ServiceDeskPlus_On_Premise/pack_metadata.json
  Packs/mcafeeDam/pack_metadata.json
Labels: docs-approved

#19493 Cyb xsoar enhancement
  Packs/Cybereason/.pack-ignore
  Packs/Cybereason/Author_image.png
  Packs/Cybereason/Integrations/Cybereason/Cybereason.py
  Packs/Cybereason/Integrations/Cybereason/Cybereason.yml
  Packs/Cybereason/Integrations/Cybereason/Cybereason_test.py
  Packs/Cybereason/Integrations/Cybereason/README.md
  Packs/Cybereason/Integrations/Cybereason/test_data/archive_sensor.json
  Packs/Cybereason/Integrations/Cybereason/test_data/available_remediation_actions_raw_response.json
  Packs/Cybereason/Integrations/Cybereason/test_data/fetch_scan_status_raw_response.json
  Packs/Cybereason/Integrations/Cybereason/test_data/file_outputs.json
  Packs/Cybereason/Integrations/Cybereason/test_data/get_batch_id_raw_response.json
  Packs/Cybereason/Integrations/Cybereason/test_data/get_file_guids_raw_response.json
  Packs/Cybereason/Integrations/Cybereason/test_data/get_machine_guid_raw_response.json
  Packs/Cybereason/Integrations/Cybereason/test_data/get_pylum_id_raw_response.json
  Packs/Cybereason/Integrations/Cybereason/test_data/get_remediation_action.json
  Packs/Cybereason/Integrations/Cybereason/test_data/get_remediation_action_status.json
  Packs/Cybereason/Integrations/Cybereason/test_data/get_sensor_id_raw_response.json
  Packs/Cybereason/Integrations/Cybereason/test_data/is_probe_connected_raw_response.json
  Packs/Cybereason/Integrations/Cybereason/test_data/isolate_machine_raw_response.json
  Packs/Cybereason/Integrations/Cybereason/test_data/machine_outputs.json
  Packs/Cybereason/Integrations/Cybereason/test_data/malop_processes_raw_response.json
  Packs/Cybereason/Integrations/Cybereason/test_data/malware_query_raw_data.json
  Packs/Cybereason/Integrations/Cybereason/test_data/prevent_file_raw_response.json
  Packs/Cybereason/Integrations/Cybereason/test_data/query_domain_raw_response.json
  Packs/Cybereason/Integrations/Cybereason/test_data/query_malop_raw_response.json
  Packs/Cybereason/Integrations/Cybereason/test_data/query_processes_raw_response.json
  Packs/Cybereason/Integrations/Cybereason/test_data/query_user_raw_response.json
  Packs/Cybereason/Integrations/Cybereason/test_data/start_fetch_file_raw_response.json
  Packs/Cybereason/Playbooks/playbook-Block_File_-_Cybereason.yml
  Packs/Cybereason/Playbooks/playbook-Download_Close_File_-_Cybereason.yml
  Packs/Cybereason/Playbooks/playbook-Download_Close_File_-_Cybereason_README.md
  Packs/Cybereason/Playbooks/playbook-Download_File_-_Cybereason.yml
  Packs/Cybereason/Playbooks/playbook-Download_File_-_Cybereason_README.md
  Packs/Cybereason/Playbooks/playbook-Isolate_Endpoint_-_Cybereason.yml
  Packs/Cybereason/Playbooks/playbook-Isolate_Endpoint_-_Cybereason_README.md
  Packs/Cybereason/Playbooks/playbook-Search_Endpoints_By_Hash_-_Cybereason.yml
  Packs/Cybereason/Playbooks/playbook-Unisolate_Endpoint_-_Cybereason.yml
  Packs/Cybereason/Playbooks/playbook-Unisolate_Endpoint_-_Cybereason_README.md
  Packs/Cybereason/README.md
  Packs/Cybereason/ReleaseNotes/1_0_20.md
  Packs/Cybereason/ReleaseNotes/2_0_0.md
  Packs/Cybereason/Scripts/CybereasonPreProcessingExample/CybereasonPreProcessingExample.py
  Packs/Cybereason/Scripts/CybereasonPreProcessingExample/CybereasonPreProcessingExample.yml
  Packs/Cybereason/Scripts/CybereasonPreProcessingExample/CybereasonPreProcessingExample_test.py
  Packs/Cybereason/TestPlaybooks/playbook-Cybereason_Pre_Processing_Test.yml
  Packs/Cybereason/TestPlaybooks/playbook-Cybereason_Test.yml
  Packs/Cybereason/doc_files/Download_Close_File_-_Cybereason.png
  Packs/Cybereason/doc_files/Download_File_-_Cybereason.png
  Packs/Cybereason/pack_metadata.json
Labels: Contribution, docs-approved, Partner, pending-demo, post-demo, Contribution Form Filled

#21948 Joe deprecate playbook
  Packs/JoeSecurity/Integrations/JoeSecurityV2/JoeSecurityV2.py
  Packs/JoeSecurity/Integrations/JoeSecurityV2/JoeSecurityV2.yml
  Packs/JoeSecurity/Integrations/JoeSecurityV2/README.md
  Packs/JoeSecurity/Playbooks/playbook-Detonate_File_-_JoeSecurity.yml
  Packs/JoeSecurity/Playbooks/playbook-Detonate_File_From_URL_-_JoeSecurity.yml
  Packs/JoeSecurity/Playbooks/playbook-Detonate_URL_-_JoeSecurity.yml
  Packs/JoeSecurity/Playbooks/playbook-Detonate_and_Analyze_File_-_JoeSecurity.yml
  Packs/JoeSecurity/ReleaseNotes/1_1_1.md
  Packs/JoeSecurity/pack_metadata.json
Labels: docs-approved, ForceMerge

#21908 Cortex XDR - IR - fix xdr-file-quarantine command
  Packs/CortexXDR/Integrations/CortexXDRIR/CortexXDRIR.py
  Packs/CortexXDR/ReleaseNotes/4_9_1.md
  Packs/CortexXDR/TestPlaybooks/Test_XDR_Playbook.yml
  Packs/CortexXDR/pack_metadata.json
Labels: docs-approved

#22068 Whois return type
  Packs/Whois/.secrets-ignore
  Packs/Whois/Integrations/Whois/README.md
  Packs/Whois/Integrations/Whois/Whois.py
  Packs/Whois/Integrations/Whois/Whois.yml
  Packs/Whois/Integrations/Whois/Whois_test.py
  Packs/Whois/Integrations/Whois/test_data/cnn_pickled
  Packs/Whois/ReleaseNotes/1_4_3.md
  Packs/Whois/pack_metadata.json
Labels: docs-approved

#22098 Add marketplaces field in Dropbox event collector
  Packs/Dropbox/Integrations/DropboxEventCollector/DropboxEventCollector.yml
  Packs/Dropbox/ReleaseNotes/1_0_5.md
  Packs/Dropbox/pack_metadata.json
Labels: docs-approved

#22085 Fix compare zips empty uploaded packs
  .gitlab/ci/staging.yml
  Tests/scripts/utils/compare_staging_graph.py
Labels: docs-approved

#22101 Fix optimizer headers
  Packs/PANOSPolicyOptimizer/Integrations/PANOSPolicyOptimizer/PANOSPolicyOptimizer.py
  Packs/PANOSPolicyOptimizer/ReleaseNotes/1_1_1.md
  Packs/PANOSPolicyOptimizer/pack_metadata.json
Labels: docs-approved

#21910 Xsoar mirroring fix
  Packs/XSOARmirroring/Integrations/XSOARmirroring/README.md
  Packs/XSOARmirroring/Integrations/XSOARmirroring/XSOARmirroring.py
  Packs/XSOARmirroring/Integrations/XSOARmirroring/XSOARmirroring.yml
  Packs/XSOARmirroring/Integrations/XSOARmirroring/XSOARmirroring_test.py
  Packs/XSOARmirroring/ReleaseNotes/2_0_10.md
  Packs/XSOARmirroring/pack_metadata.json
Labels: bug, docs-approved

#22108 usecases/tags/categories mp_revamp_411_450
  Packs/DeveloperTools/pack_metadata.json
  Packs/Hunting/pack_metadata.json
  Packs/IAM-SCIM/pack_metadata.json
  Packs/ILert/pack_metadata.json
  Packs/IP-API/pack_metadata.json
  Packs/IPQualityScore/pack_metadata.json
  Packs/IdentityRecordedFuture/pack_metadata.json
  Packs/IllusiveNetworks/pack_metadata.json
  Packs/ImpossibleTraveler/pack_metadata.json
  Packs/IntegrationsAndIncidentsHealthCheck/pack_metadata.json
  Packs/Inventa/pack_metadata.json
  Packs/InvertEveryTwoItems/pack_metadata.json
  Packs/IsArrayItemInList/pack_metadata.json
  Packs/XForceExchange/pack_metadata.json
  Packs/ipinfo/pack_metadata.json
Labels: docs-approved

#21993 unskip MicrosoftGraphMail tests
  Packs/MicrosoftGraphMail/Integrations/MicrosoftGraphMail/MicrosoftGraphMail.py
  Packs/MicrosoftGraphMail/ReleaseNotes/1_3_2.md
  Packs/MicrosoftGraphMail/pack_metadata.json
  Tests/conf.json
Labels: docs-approved

#22105 fix demisto-sdk installation in staging
  .gitlab/ci/staging.yml
  Tests/scripts/utils/compare_staging_graph.py
Labels: docs-approved

#22035 XDR owner bug fix
  Packs/CortexXDR/Classifiers/classifier-mapper-outgoing-PaloAltoNetworks_CortexXDR.json
  Packs/CortexXDR/Integrations/CortexXDRIR/README.md
  Packs/CortexXDR/ReleaseNotes/4_9_2.md
  Packs/CortexXDR/pack_metadata.json
Labels: docs-approved, ForceMerge

#22089 Jira query add description
  Packs/Jira/Integrations/JiraV2/JiraV2.py
  Packs/Jira/Integrations/JiraV2/JiraV2.yml
  Packs/Jira/Integrations/JiraV2/README.md
  Packs/Jira/Integrations/JiraV2/test_data/expected_results.py
  Packs/Jira/ReleaseNotes/2_0_17.md
  Packs/Jira/pack_metadata.json
Labels: docs-approved

#21530 Initial release of Stairwell integration
  Packs/Stairwell/.pack-ignore
  Packs/Stairwell/.secrets-ignore
  Packs/Stairwell/Author_image.png
  Packs/Stairwell/Integrations/Inception/Inception.py
  Packs/Stairwell/Integrations/Inception/Inception.yml
  Packs/Stairwell/Integrations/Inception/Inception_description.md
  Packs/Stairwell/Integrations/Inception/Inception_image.png
  Packs/Stairwell/Integrations/Inception/Inception_test.py
  Packs/Stairwell/Integrations/Inception/Pipfile
  Packs/Stairwell/Integrations/Inception/Pipfile.lock
  Packs/Stairwell/Integrations/Inception/README.md
  Packs/Stairwell/Integrations/Inception/command_examples
  Packs/Stairwell/Integrations/Inception/test_data/file_enrichment_command_result.json
  Packs/Stairwell/Integrations/Inception/test_data/variant_discovery_command_result.json
  Packs/Stairwell/Integrations/Inception/test_data/variant_discovery_command_results_none.json
  Packs/Stairwell/Integrations/Inception/test_data/variant_discovery_command_results_notfound.json
  Packs/Stairwell/README.md
  Packs/Stairwell/pack_metadata.json
Labels: Contribution, docs-approved, Partner, ready-for-instance-test, pending-demo, Contribution Form Filled

#22112 fix misspelled categories
  Packs/CheckPointDome9/pack_metadata.json
  Packs/Cisco-umbrella-cloud-security/pack_metadata.json
  Packs/FeedCyCognito/pack_metadata.json
  Packs/GoogleDrive/pack_metadata.json
  Packs/SkyhighSecurity/pack_metadata.json
Labels: docs-approved

#22095 mp_revamp_550-600_new
  Packs/FeedOffice365/pack_metadata.json
  Packs/NCSCCyberAsssessmentFramework/pack_metadata.json
  Packs/NIST/pack_metadata.json
  Packs/NTT_Cyber_Threat_Sensor/pack_metadata.json
  Packs/Ncurion/pack_metadata.json
  Packs/Netcraft/pack_metadata.json
  Packs/Netmiko/pack_metadata.json
  Packs/NetscoutArborSightline/pack_metadata.json
  Packs/Netskope/pack_metadata.json
  Packs/NetskopeV2/pack_metadata.json
  Packs/Nexthink/pack_metadata.json
  Packs/Nmap/pack_metadata.json
  Packs/NozomiNetworks/pack_metadata.json
  Packs/NucleonCyber/pack_metadata.json
  Packs/NutanixHypervisor/pack_metadata.json
  Packs/Office365AndAzureAuditLog/pack_metadata.json
  Packs/Oletools/pack_metadata.json
  Packs/OpenCTI/pack_metadata.json
  Packs/OpenPhish/pack_metadata.json
  Packs/Oracle_IAM/pack_metadata.json
  Packs/Orca/pack_metadata.json
  Packs/PANWComprehensiveInvestigation/pack_metadata.json
  Packs/opswat-metadefender/pack_metadata.json
Labels: docs-approved

#20857 PAN-OS - Fix incorrect parsing of Panorama High-Availability state XML
  Packs/PAN-OS/Integrations/Panorama/Panorama.py
  Packs/PAN-OS/Integrations/Panorama/Panorama_test.py
  Packs/PAN-OS/Integrations/Panorama/test_data/show_device_groups.xml
  Packs/PAN-OS/Integrations/Panorama/test_data/show_ha_state_panorama_enabled.xml
  Packs/PAN-OS/ReleaseNotes/1_15_2.md
  Packs/PAN-OS/pack_metadata.json
Labels: Contribution, docs-approved, Contribution Form Filled, Community, pending-contributor

#22109 Fix authorize security group egress command
  Packs/AWS-EC2/Integrations/AWS-EC2/AWS-EC2.py
  Packs/AWS-EC2/Integrations/AWS-EC2/AWS-EC2.yml
  Packs/AWS-EC2/ReleaseNotes/1_2_19.md
  Packs/AWS-EC2/pack_metadata.json
Labels: docs-approved

#22111 TestCollect: remove verbose message
  Tests/scripts/collect_tests/collect_tests.py
  Tests/scripts/collect_tests/test_conf.py
Labels: docs-approved

#22026 Update acc api docs intsights
  Packs/IntSight/Integrations/IntSight/IntSight.py
  Packs/IntSight/Integrations/IntSight/IntSight.yml
  Packs/IntSight/Integrations/IntSight/IntSight_test.py
  Packs/IntSight/Integrations/IntSight/README.md
  Packs/IntSight/ReleaseNotes/2_0_0.json
  Packs/IntSight/ReleaseNotes/2_0_0.md
  Packs/IntSight/pack_metadata.json
Labels: docs-approved, ForceMerge

#22114 Fixed stix version.
  Packs/CommonScripts/ReleaseNotes/1_9_8.md
  Packs/CommonScripts/Scripts/CreateIndicatorsFromSTIX/CreateIndicatorsFromSTIX.yml
  Packs/CommonScripts/Scripts/CreateIndicatorsFromSTIX/README.md
  Packs/CommonScripts/pack_metadata.json
Labels: docs-approved

#21986 Jb slack parsing rule
  Packs/Slack/ParsingRules/SlackParsingRules/SlackParsingRules.xif
  Packs/Slack/ParsingRules/SlackParsingRules/SlackParsingRules.yml
  Packs/Slack/ReleaseNotes/3_1_12.md
  Packs/Slack/pack_metadata.json
Labels: docs-approved

#22119 rm deprecated tags and use cases
  Packs/Armorblox/pack_metadata.json
  Packs/BreachRx/pack_metadata.json
  Packs/KeeperSecretsManager/pack_metadata.json
  Packs/NutanixHypervisor/pack_metadata.json
Labels: docs-approved

#21831 Rename packs and integrations of Azure
  Packs/AzureSecurityCenter/Integrations/AzureSecurityCenter_v2/AzureSecurityCenter_v2.py
  Packs/AzureSecurityCenter/Integrations/AzureSecurityCenter_v2/AzureSecurityCenter_v2.yml
  Packs/AzureSecurityCenter/ReleaseNotes/1_3_2.md
  Packs/AzureSecurityCenter/pack_metadata.json
  Packs/AzureSentinel/Integrations/AzureSentinel/AzureSentinel.py
  Packs/AzureSentinel/Integrations/AzureSentinel/AzureSentinel.yml
  Packs/AzureSentinel/ReleaseNotes/1_4_2.md
  Packs/AzureSentinel/pack_metadata.json
  Packs/MicrosoftCloudAppSecurity/Integrations/MicrosoftCloudAppSecurity/MicrosoftCloudAppSecurity.yml
  Packs/MicrosoftCloudAppSecurity/ReleaseNotes/2_1_6.md
  Packs/MicrosoftCloudAppSecurity/pack_metadata.json
  Tests/conf.json
Labels: docs-approved

#22075 Added "Rank" indicator field
  Packs/CommonTypes/IndicatorFields/indicatorfield-Rank.json
  Packs/CommonTypes/ReleaseNotes/3_3_27.md
  Packs/CommonTypes/pack_metadata.json
Labels: docs-approved

#22129 removed
  Tests/conf.json
Labels: docs-approved

#22123 Threat grid artifacts bug fix
  Packs/ThreatGrid/Integrations/ThreatGrid/ThreatGrid.py
  Packs/ThreatGrid/Integrations/ThreatGrid/ThreatGrid.yml
  Packs/ThreatGrid/Integrations/ThreatGrid/ThreatGrid_test.py
  Packs/ThreatGrid/ReleaseNotes/1_2_18.md
  Packs/ThreatGrid/TestPlaybooks/playbook-Threat_Grid_Test.yml
  Packs/ThreatGrid/pack_metadata.json
  Tests/conf.json
Labels: docs-approved

#21856 ReadPDFFileV2Permissions Fixes (Without Copy Protected)
  Packs/CommonScripts/ReleaseNotes/1_10_0.md
  Packs/CommonScripts/Scripts/ReadPDFFileV2/ReadPDFFileV2.py
  Packs/CommonScripts/Scripts/ReadPDFFileV2/ReadPDFFileV2.yml
  Packs/CommonScripts/Scripts/ReadPDFFileV2/ReadPDFFileV2_test.py
  Packs/CommonScripts/TestPlaybooks/playbook-ReadPDFFileV2_Test.yml
  Packs/CommonScripts/pack_metadata.json
Labels: docs-approved

#22088 Misp add email object bug fix
  Packs/MISP/Integrations/MISPV3/MISPV3.py
  Packs/MISP/Integrations/MISPV3/MISPV3.yml
  Packs/MISP/Integrations/MISPV3/MISPV3_test.py
  Packs/MISP/Integrations/MISPV3/README.md
  Packs/MISP/ReleaseNotes/2_1_12.md
  Packs/MISP/TestPlaybooks/MISP_V3_Test.yml
  Packs/MISP/pack_metadata.json
Labels: docs-approved

#22062 temporary fix of VirusTotal offset 1 error in reputation
  Packs/CommonScripts/.pack-ignore
  Packs/CommonScripts/ReleaseNotes/1_10_1.md
  Packs/CommonScripts/Scripts/DomainReputation/DomainReputation.py
  Packs/CommonScripts/Scripts/DomainReputation/DomainReputation.yml
  Packs/CommonScripts/Scripts/DomainReputation/DomainReputation_test.py
  Packs/CommonScripts/Scripts/FileReputation/FileReputation.py
  Packs/CommonScripts/Scripts/FileReputation/FileReputation.yml
  Packs/CommonScripts/Scripts/FileReputation/FileReputation_test.py
  Packs/CommonScripts/Scripts/URLReputation/URLReputation.py
  Packs/CommonScripts/Scripts/URLReputation/URLReputation.yml
  Packs/CommonScripts/Scripts/URLReputation/URLReputation_test.py
  Packs/CommonScripts/pack_metadata.json
Labels: docs-approved

#22136 install demisto-sdk master correctly in staging
  .gitlab/ci/staging.yml
Labels: docs-approved

#22133 add-CortexAttackSurfaceManagement-pack
  Tests/Marketplace/core_packs_mpv2_list.json
Labels: docs-approved

#21715 [AquatoneDiscover] move to commonscripts, to py3
  Packs/AquatoneDiscover/ReleaseNotes/1_0_1.md
  Packs/AquatoneDiscover/Scripts/script-AquatoneDiscover.yml
  Packs/AquatoneDiscover/pack_metadata.json
  Packs/CommonScripts/ReleaseNotes/1_10_2.md
  Packs/CommonScripts/Scripts/AquatoneDiscoverV2/AquatoneDiscoverV2.py
  Packs/CommonScripts/Scripts/AquatoneDiscoverV2/AquatoneDiscoverV2.yml
  Packs/CommonScripts/Scripts/AquatoneDiscoverV2/AquatoneDiscoverV2_test.py
  Packs/CommonScripts/Scripts/AquatoneDiscoverV2/README.md
  Packs/CommonScripts/pack_metadata.json
Labels: docs-approved

#21258 GitLab new integration
  Packs/GitLab/.secrets-ignore
  Packs/GitLab/Integrations/GitLabv2/GitLabv2.py
  Packs/GitLab/Integrations/GitLabv2/GitLabv2.yml
  Packs/GitLab/Integrations/GitLabv2/GitLabv2_description.md
  Packs/GitLab/Integrations/GitLabv2/GitLabv2_image.png
  Packs/GitLab/Integrations/GitLabv2/GitLabv2_test.py
  Packs/GitLab/Integrations/GitLabv2/README.md
  Packs/GitLab/Integrations/GitLabv2/command_examples
  Packs/GitLab/Integrations/GitLabv2/test_data/commands_test_data.json
  Packs/GitLab/ReleaseNotes/2_0_0.md
  Packs/GitLab/TestPlaybooks/Test-GitLab-v2.yml
  Packs/GitLab/pack_metadata.json
  Tests/conf.json
Labels: docs-approved, ForceMerge

#21695 Deprecate old gitlab
  Packs/DevSecOps/Integrations/GitLab/GitLab.yml
  Packs/DevSecOps/ReleaseNotes/1_1_1.md
  Packs/DevSecOps/pack_metadata.json
Labels: docs-approved

#22151 add pack-ignore
  Packs/AquatoneDiscover/.pack-ignore
Labels: docs-approved

#22150 unskipping tpb for o365 sc aftet fixing the instance in contest-test-…
  Tests/conf.json
Labels: docs-approved

#22159 Ignore IF100 error in CortexAttackSurfaceManagement pack
  Packs/CortexAttackSurfaceManagement/.pack-ignore
Labels: docs-approved

#22157 URLSCAN - The scan visibility of submitted URLs is no longer public by …
  Packs/UrlScan/Integrations/UrlScan/UrlScan.py
  Packs/UrlScan/Integrations/UrlScan/UrlScan.yml
  Packs/UrlScan/Integrations/UrlScan/UrlScan_description.md
  Packs/UrlScan/ReleaseNotes/1_2_1.md
  Packs/UrlScan/pack_metadata.json
Labels: ForceMerge

#22131 TestCollect fix marketplace validation
  Tests/scripts/collect_tests/collect_tests.py
  Tests/scripts/infrastructure_tests/tests_data/collect_tests/A_xsiam/Tests/id_set.json
  Tests/scripts/infrastructure_tests/tests_data/collect_tests/D/Packs/myPack/TestPlaybooks/myTestPlaybook.yml
Labels: docs-approved

#22092 Update auth details in HttpV2-Test tpb
  Packs/CommonScripts/TestPlaybooks/playbook-HttpV2-Test.yml
Labels: docs-approved

#21687 Adding commands in the existing sophos central integration.
  Packs/SophosCentral/Integrations/SophosCentral/README.md
  Packs/SophosCentral/Integrations/SophosCentral/SophosCentral.py
  Packs/SophosCentral/Integrations/SophosCentral/SophosCentral.yml
  Packs/SophosCentral/Integrations/SophosCentral/SophosCentral_test.py
  Packs/SophosCentral/Integrations/SophosCentral/command_examples.txt
  Packs/SophosCentral/Integrations/SophosCentral/test_data/add_endpoints.json
  Packs/SophosCentral/Integrations/SophosCentral/test_data/added_users.json
  Packs/SophosCentral/Integrations/SophosCentral/test_data/deleted_user.json
  Packs/SophosCentral/Integrations/SophosCentral/test_data/endpoint_create_group.json
  Packs/SophosCentral/Integrations/SophosCentral/test_data/endpoint_delete_group.json
  Packs/SophosCentral/Integrations/SophosCentral/test_data/endpoint_get_membership.json
  Packs/SophosCentral/Integrations/SophosCentral/test_data/endpoint_groups_list.json
  Packs/SophosCentral/Integrations/SophosCentral/test_data/endpoint_update_group.json
  Packs/SophosCentral/Integrations/SophosCentral/test_data/get_users_from_usergroup.json
  Packs/SophosCentral/Integrations/SophosCentral/test_data/get_users_from_usergroup_page_not_found.json
  Packs/SophosCentral/Integrations/SophosCentral/test_data/page_not_found.json
  Packs/SophosCentral/Integrations/SophosCentral/test_data/policy_list.json
  Packs/SophosCentral/Integrations/SophosCentral/test_data/policy_single.json
  Packs/SophosCentral/Integrations/SophosCentral/test_data/remove_endpoints.json
  Packs/SophosCentral/Integrations/SophosCentral/test_data/remove_single_endpoints.json
  Packs/SophosCentral/Integrations/SophosCentral/test_data/removed_user.json
  Packs/SophosCentral/Integrations/SophosCentral/test_data/usergroup_delete.json
  Packs/SophosCentral/Integrations/SophosCentral/test_data/usergroup_single.json
  Packs/SophosCentral/Integrations/SophosCentral/test_data/usergroups_list.json
  Packs/SophosCentral/Integrations/SophosCentral/test_data/usergroups_list_page_not_found.json
  Packs/SophosCentral/Integrations/SophosCentral/test_data/users_list.json
  Packs/SophosCentral/Integrations/SophosCentral/test_data/users_single.json
  Packs/SophosCentral/ReleaseNotes/1_2_0.md
  Packs/SophosCentral/pack_metadata.json
Labels: Contribution, docs-approved, Partner, post-demo, Contribution Form Filled

#20941 Replace readme external urls
  Tests/Marketplace/Tests/marketplace_services_test.py
  Tests/Marketplace/Tests/test_data/readme_images_test_data/README_after_replace.md
  Tests/Marketplace/Tests/test_data/readme_images_test_data/original_README.md
  Tests/Marketplace/Tests/test_data/readme_images_test_data/url_replace_README.md
  Tests/Marketplace/copy_and_upload_packs.py
  Tests/Marketplace/marketplace_constants.py
  Tests/Marketplace/marketplace_services.py
  Tests/Marketplace/upload_packs.py
Labels: docs-approved

#22053 ReadPDFFileV2 fix
  Packs/CommonScripts/ReleaseNotes/1_10_4.md
  Packs/CommonScripts/ReleaseNotes/1_10_5.md
  Packs/CommonScripts/Scripts/ReadPDFFileV2/ReadPDFFileV2.py
  Packs/CommonScripts/Scripts/ReadPDFFileV2/ReadPDFFileV2_test.py
  Packs/CommonScripts/pack_metadata.json
Labels: docs-approved, release-notes-only

#22177 Fix dependency for CortexAttackSurfaceManagement
  Packs/CortexAttackSurfaceManagement/pack_metadata.json
Labels: docs-approved

#22180 Added a note to the command documentaion
  Packs/MicrosoftDefenderAdvancedThreatProtection/Integrations/MicrosoftDefenderAdvancedThreatProtection/README.md
Labels: docs-approved

#21861 [OpsGenie] unique identifier
  Packs/OpsGenie/.pack-ignore
  Packs/OpsGenie/Classifiers/classifier-OpsGenie_-_Mapper.json
  Packs/OpsGenie/IncidentFields/incidentfield-OpsGenie_AlertId.json
  Packs/OpsGenie/ReleaseNotes/2_0_10.md
  Packs/OpsGenie/pack_metadata.json
Labels: Contribution, Contribution Form Filled, Community

#22190 Revert "add-CortexAttackSurfaceManagement-pack" - HOLD
  Tests/Marketplace/core_packs_mpv2_list.json
Labels: inprogress, docs-approved

#22194 gitignore testcollect log
  .gitignore
Labels: docs-approved

#22205 New url formatter - "Split" bug
  Packs/CommonScripts/ReleaseNotes/1_10_6.md
  Packs/CommonScripts/Scripts/FormatURL/FormatURL.py
  Packs/CommonScripts/pack_metadata.json
Labels: docs-approved

#22198 Tanium expiration param support
  Packs/Tanium/Integrations/Tanium_v2/README.md
  Packs/Tanium/Integrations/Tanium_v2/Tanium_v2.py
  Packs/Tanium/Integrations/Tanium_v2/Tanium_v2.yml
  Packs/Tanium/ReleaseNotes/1_0_19.md
  Packs/Tanium/pack_metadata.json
Labels: docs-approved

#22183 Headers map to emailheaders
  Packs/Phishing/.pack-ignore
  Packs/Phishing/IncidentFields/incidentfield-emailauthenticitycheck.json
  Packs/Phishing/Playbooks/Process_Email_-_Generic_v2.yml
  Packs/Phishing/ReleaseNotes/3_3_9.md
  Packs/Phishing/pack_metadata.json
Labels: docs-approved

#22206 Fix file enrichment v2
  Packs/CommonPlaybooks/Playbooks/playbook-File_Enrichment_-_Generic_v2.yml
  Packs/CommonPlaybooks/Playbooks/playbook-File_Enrichment_-_Generic_v2_README.md
  Packs/CommonPlaybooks/ReleaseNotes/2_3_9.md
  Packs/CommonPlaybooks/pack_metadata.json
  Tests/conf.json
Labels: docs-approved

#21833 OneLogin event collector
  Packs/OneLogin/.pack-ignore
  Packs/OneLogin/.secrets-ignore
  Packs/OneLogin/Integrations/OneLoginEventCollector/OneLoginEventCollector.py
  Packs/OneLogin/Integrations/OneLoginEventCollector/OneLoginEventCollector.yml
  Packs/OneLogin/Integrations/OneLoginEventCollector/OneLoginEventCollector_description.md
  Packs/OneLogin/Integrations/OneLoginEventCollector/OneLoginEventCollector_image.png
  Packs/OneLogin/Integrations/OneLoginEventCollector/OneLoginEventCollector_test.py
  Packs/OneLogin/Integrations/OneLoginEventCollector/README.md
  Packs/OneLogin/Integrations/OneLoginEventCollector/command_examples
  Packs/OneLogin/Integrations/OneLoginEventCollector/test_data/mock_event_types.json
  Packs/OneLogin/Integrations/OneLoginEventCollector/test_data/mock_events.json
  Packs/OneLogin/ModelingRules/OneLoginModelingRules/OneLoginModelingRules.xif
  Packs/OneLogin/ModelingRules/OneLoginModelingRules/OneLoginModelingRules.yml
  Packs/OneLogin/ModelingRules/OneLoginModelingRules/OneLoginModelingRules_schema.json
  Packs/OneLogin/ModelingRules/OneLoginModelingRules_1_3/OneLoginModelingRules_1_3.xif
  Packs/OneLogin/ModelingRules/OneLoginModelingRules_1_3/OneLoginModelingRules_1_3.yml
  Packs/OneLogin/ModelingRules/OneLoginModelingRules_1_3/OneLoginModelingRules_1_3_schema.json
  Packs/OneLogin/README.md
  Packs/OneLogin/pack_metadata.json
Labels: docs-approved

#22222 remove file enrichment configurations from conf.json
  Tests/conf.json
Labels: docs-approved

#22146 Fixed rasterize_html_command
  Packs/rasterize/Integrations/rasterize/README.md
  Packs/rasterize/Integrations/rasterize/rasterize.py
  Packs/rasterize/Integrations/rasterize/rasterize.yml
  Packs/rasterize/ReleaseNotes/1_2_9.md
  Packs/rasterize/TestPlaybooks/playbook-Rasterize_Test.yml
  Packs/rasterize/pack_metadata.json
Labels: docs-approved, ForceMerge

#21457 Update sdk nightly docker test
  .gitlab/ci/sdk-nightly.yml
Labels: docs-approved

#22176 better upload-packs logging
  Tests/Marketplace/marketplace_constants.py
  Tests/Marketplace/marketplace_services.py
  Tests/Marketplace/upload_packs.py
Labels: docs-approved

#22202 Skip Cortex Data Lake test playbook
  Tests/conf.json
Labels: docs-approved

#22210 Deprecate Microsoft Defender - ATP - Indicators Test TPB
  Packs/MicrosoftDefenderAdvancedThreatProtection/TestPlaybooks/playbook-Microsoft_ATP_indicators_Test.yml
  Tests/conf.json
Labels: docs-approved

#22203 Fix DecodeMimeHeader - Test test playbook
  Packs/CommonScripts/TestPlaybooks/playbook-DecodeMimeHeader_-_Test.yml
Labels: docs-approved

#22186 Delete sub-testPlaybooks for TAXII2
  Tests/conf.json
Labels: docs-approved

#22193 update Tests/Marketplace/approved_categories.json
  Packs/MicrosoftGraphListener/pack_metadata.json
  Tests/Marketplace/approved_categories.json
Labels: docs-approved

#22154 Moved pack to Beta and to community supported
  Packs/PANOSPolicyOptimizer/Integrations/PANOSPolicyOptimizer/PANOSPolicyOptimizer.yml
  Packs/PANOSPolicyOptimizer/Integrations/PANOSPolicyOptimizer/PANOSPolicyOptimizer_description.md
  Packs/PANOSPolicyOptimizer/Integrations/PANOSPolicyOptimizer/README.md
  Packs/PANOSPolicyOptimizer/README.md
  Packs/PANOSPolicyOptimizer/ReleaseNotes/1_1_2.md
  Packs/PANOSPolicyOptimizer/pack_metadata.json
Labels: docs-approved

#21814 Crowdsec Integration
  Packs/CrowdSec/.pack-ignore
  Packs/CrowdSec/.secrets-ignore
  Packs/CrowdSec/Author_image.png
  Packs/CrowdSec/Integrations/CrowdSec/CrowdSec.py
  Packs/CrowdSec/Integrations/CrowdSec/CrowdSec.yml
  Packs/CrowdSec/Integrations/CrowdSec/CrowdSec_description.md
  Packs/CrowdSec/Integrations/CrowdSec/CrowdSec_image.png
  Packs/CrowdSec/Integrations/CrowdSec/CrowdSec_test.py
  Packs/CrowdSec/Integrations/CrowdSec/Pipfile
  Packs/CrowdSec/Integrations/CrowdSec/Pipfile.lock
  Packs/CrowdSec/Integrations/CrowdSec/README.md
  Packs/CrowdSec/Integrations/CrowdSec/command_examples
  Packs/CrowdSec/Integrations/CrowdSec/test_data/test_ip_command.json
  Packs/CrowdSec/Integrations/CrowdSec/test_data/test_unknown_ip_command.json
  Packs/CrowdSec/README.md
  Packs/CrowdSec/pack_metadata.json
Labels: Contribution, docs-approved, Partner, Contribution Form Filled

#22087 Added to collect_tests skip deprecated integrations
  .gitignore
  Tests/scripts/collect_tests/collect_tests.py
  Tests/scripts/infrastructure_tests/collect_tests.log
  Tests/scripts/infrastructure_tests/test_collect_tests.py
  Tests/scripts/infrastructure_tests/tests_data/collect_tests/Q/Packs/myPack/.pack_ignore
  Tests/scripts/infrastructure_tests/tests_data/collect_tests/Q/Packs/myPack/.secrets-ignore
  Tests/scripts/infrastructure_tests/tests_data/collect_tests/Q/Packs/myPack/Integrations/myDeprecatedIntegration/myDeprecatedIntegration.py
  Tests/scripts/infrastructure_tests/tests_data/collect_tests/Q/Packs/myPack/Integrations/myDeprecatedIntegration/myDeprecatedIntegration.yml
  Tests/scripts/infrastructure_tests/tests_data/collect_tests/Q/Packs/myPack/Integrations/myIntegration/myIntegration.py
  Tests/scripts/infrastructure_tests/tests_data/collect_tests/Q/Packs/myPack/Integrations/myIntegration/myIntegration.yml
  Tests/scripts/infrastructure_tests/tests_data/collect_tests/Q/Packs/myPack/Integrations/myIntegration/test_data/file.json
  Tests/scripts/infrastructure_tests/tests_data/collect_tests/Q/Packs/myPack/ParsingRules/Samples/some_sample.json
  Tests/scripts/infrastructure_tests/tests_data/collect_tests/Q/Packs/myPack/TestPlaybooks/myOtherTestPlaybook.yml
  Tests/scripts/infrastructure_tests/tests_data/collect_tests/Q/Packs/myPack/TestPlaybooks/myTestPlaybook.yml
  Tests/scripts/infrastructure_tests/tests_data/collect_tests/Q/Packs/myPack/pack_metadata.json
  Tests/scripts/infrastructure_tests/tests_data/collect_tests/Q/Tests/conf.json
  Tests/scripts/infrastructure_tests/tests_data/collect_tests/Q/Tests/id_set.json
Labels: docs-approved

#22168 Fix for test_module
  Packs/Stairwell/Integrations/Inception/Inception.py
  Packs/Stairwell/ReleaseNotes/1_0_1.md
  Packs/Stairwell/pack_metadata.json
Labels: Contribution, docs-approved, Partner, Contribution Form Filled

#22231 CSV for notifier messages
  Tests/scripts/gitlab_slack_notifier.py
Labels: docs-approved

#22153 CRTX-64873: Display current date instead of N/A in generated reports
  Packs/CaseManagement-Generic/ReleaseNotes/1_3_1.md
  Packs/CaseManagement-Generic/Reports/report-CaseReport.json
  Packs/CaseManagement-Generic/pack_metadata.json
  Packs/CommonReports/ReleaseNotes/1_0_2.md
  Packs/CommonReports/Reports/report-MTTRbyIncidentType2Quar.json
  Packs/CommonReports/Reports/report-MTTRbyOwner2Quar.json
  Packs/CommonReports/Reports/report-ShiftSummary.json
  Packs/CommonReports/Reports/report-csv-dailyIncidentReport.json
  Packs/CommonReports/Reports/report-docx-investigationSummaryReport.json
  Packs/CommonReports/Reports/report-investigationSummaryReport.json
  Packs/CommonReports/Reports/report-lateIncidentsReport.json
  Packs/CommonReports/pack_metadata.json
Labels: docs-approved

#22234 add XDRC Templates rules 1.3
  Packs/MySQLEnterprise/ReleaseNotes/1_0_3.md
  Packs/MySQLEnterprise/XDRCTemplates/MySQLEnterprise/MySQLEnterprise.json
  Packs/MySQLEnterprise/pack_metadata.json
Labels: docs-approved

#22246 Bugfix/cds cy cognito
  Packs/CyCognito/Layouts/layoutscontainer-CyCognito_Issue.json
  Packs/CyCognito/ReleaseNotes/1_0_1.md
  Packs/CyCognito/pack_metadata.json
Labels: Contribution, Partner, Contribution Form Filled

#21019 IBM Resilient safe access dictionaries
  Packs/IBMResilientSystems/.pack-ignore
  Packs/IBMResilientSystems/Integrations/IBMResilientSystems/IBMResilientSystems.py
  Packs/IBMResilientSystems/ReleaseNotes/1_1_3.md
  Packs/IBMResilientSystems/pack_metadata.json
Labels: docs-approved

#22259 pre-commit
  .github/workflows/pre-commit.yml
  .pre-commit-config.yaml
  Tests/secrets_white_list.json
Labels: docs-approved

#22024 bug - ThreatConnect feed groups endpoint tql
  Packs/FeedThreatConnect/Integrations/FeedThreatConnect/FeedThreatConnect.py
  Packs/FeedThreatConnect/Integrations/FeedThreatConnect/FeedThreatConnect.yml
  Packs/FeedThreatConnect/Integrations/FeedThreatConnect/FeedThreatConnect_test.py
  Packs/FeedThreatConnect/Integrations/FeedThreatConnect/README.md
  Packs/FeedThreatConnect/ReleaseNotes/2_1_1.md
  Packs/FeedThreatConnect/pack_metadata.json
Labels: docs-approved

#22260 [Carbon Black EDR Response] In Progress and False Positive Alert issue fix
  Packs/Carbon_Black_Enterprise_Response/Integrations/CarbonBlackResponseV2/CarbonBlackResponseV2.py
  Packs/Carbon_Black_Enterprise_Response/Integrations/CarbonBlackResponseV2/CarbonBlackResponseV2.yml
  Packs/Carbon_Black_Enterprise_Response/ReleaseNotes/2_1_25.md
  Packs/Carbon_Black_Enterprise_Response/pack_metadata.json
Labels: Contribution, docs-approved, Contribution Form Filled, Community

#22250 Added read me comment by Shirley why is it in beta
  Packs/PANOSPolicyOptimizer/Integrations/PANOSPolicyOptimizer/README.md
Labels: docs-approved

#21786 Fixed an issue where !ews-junk-rules-set with enabled=true doesn't take effect to the rule.
  Packs/EWS/Integrations/EwsExtension/EwsExtension.ps1
  Packs/EWS/Integrations/EwsExtension/EwsExtension.yml
  Packs/EWS/Integrations/EwsExtension/README.md
  Packs/EWS/ReleaseNotes/1_14_6.md
  Packs/EWS/pack_metadata.json
Labels: Contribution, docs-approved, Contribution Form Filled, Community, pending-contributor

#22249 Pre update fix
  Tests/configure_and_test_integration_instances.py
  Tests/tests/configure_and_test_integration_instances_test.py
Labels: docs-approved

#22253 Fix whois test playbook
  Packs/Whois/TestPlaybooks/playbook-Whois-Test.yml
Labels: docs-approved

#22213 Remedy ar
  Packs/Remedy_AR/Integrations/RemedyAR/README.md
  Packs/Remedy_AR/Integrations/RemedyAR/RemedyAR.py
  Packs/Remedy_AR/Integrations/RemedyAR/RemedyAR.yml
  Packs/Remedy_AR/Integrations/RemedyAR/RemedyAR_image.png
  Packs/Remedy_AR/Integrations/integration-Remedy_AR.yml
  Packs/Remedy_AR/ReleaseNotes/1_0_7.md
  Packs/Remedy_AR/pack_metadata.json
Labels: docs-approved, ForceMerge

#22128 Add new domain regex to CSP
  Packs/Base/ReleaseNotes/1_31_34.md
  Packs/Base/Scripts/CommonServerPython/CommonServerPython.py
  Packs/Base/Scripts/CommonServerPython/CommonServerPython_test.py
  Packs/Base/pack_metadata.json
Labels: docs-approved

#22270 Add support to get unused rules by both pre and post position
  Packs/PANOSPolicyOptimizer/Integrations/PANOSPolicyOptimizer/PANOSPolicyOptimizer.py
  Packs/PANOSPolicyOptimizer/Integrations/PANOSPolicyOptimizer/PANOSPolicyOptimizer.yml
  Packs/PANOSPolicyOptimizer/Integrations/PANOSPolicyOptimizer/PANOSPolicyOptimizer_test.py
  Packs/PANOSPolicyOptimizer/ReleaseNotes/1_1_3.md
  Packs/PANOSPolicyOptimizer/pack_metadata.json
Labels: docs-approved

#21983 Nav 10302: Bugfix -pass entityTypeId to gra-analytical-features-entity-value
  Packs/Gurucul/Integrations/GuruculGRA/GuruculGRA.py
  Packs/Gurucul/Integrations/GuruculGRA/GuruculGRA.yml
  Packs/Gurucul/Integrations/GuruculGRA/README.md
  Packs/Gurucul/Playbooks/playbook-GRACase_README.md
  Packs/Gurucul/ReleaseNotes/1_2_0.md
  Packs/Gurucul/Scripts/graanalyticalfeaturedisplay/README.md
  Packs/Gurucul/Scripts/graanalyticalfeaturedisplay/graanalyticalfeaturedisplay.py
  Packs/Gurucul/Scripts/graanalyticalfeaturedisplay/graanalyticalfeaturedisplay.yml
  Packs/Gurucul/Scripts/graupdatecasestatus/README.md
  Packs/Gurucul/Scripts/graupdatecasestatus/graupdatecasestatus.yml
  Packs/Gurucul/pack_metadata.json
Labels: Contribution, docs-approved, Partner, ready-for-instance-test, Contribution Form Filled, pending-contributor

#22263 Fix lookback timezone
  Packs/Base/ReleaseNotes/1_31_34.md
  Packs/Base/ReleaseNotes/1_31_35.md
  Packs/Base/Scripts/CommonServerPython/CommonServerPython.py
  Packs/Base/Scripts/CommonServerPython/CommonServerPython_test.py
  Packs/Base/pack_metadata.json
  Packs/DeveloperTools/TestPlaybooks/script-CallTableToMarkdown.yml
  Packs/DeveloperTools/TestPlaybooks/script-TestPyCommonServer.yml
  poetry.lock
  pyproject.toml
Labels: docs-approved

#22034 CRUD email forwarding commands
  Packs/Gmail/Integrations/Gmail/Gmail.py
  Packs/Gmail/Integrations/Gmail/Gmail.yml
  Packs/Gmail/Integrations/Gmail/Gmail_test.py
  Packs/Gmail/Integrations/Gmail/README.md
  Packs/Gmail/Integrations/Gmail/test_data/input_data.py
  Packs/Gmail/ReleaseNotes/1_2_2.md
  Packs/Gmail/pack_metadata.json
  Tests/conf.json
Labels: docs-approved

#22292 Revert cs falcon changes
  Packs/CrowdStrikeFalcon/.pack-ignore
  Packs/CrowdStrikeFalcon/Integrations/CrowdStrikeFalcon/CrowdStrikeFalcon.yml
  Packs/CrowdStrikeFalcon/ReleaseNotes/1_9_10.md
  Packs/CrowdStrikeFalcon/pack_metadata.json
Labels: docs-approved

#22295 1.7.8
  poetry.lock
  pyproject.toml
Labels: docs-approved

#22283 Revert "removed the filter by marketplace for the upload that runs in the build (#19831)"
  Tests/Marketplace/upload_packs.py
Labels: docs-approved

#22227 Core impossibe travel
  Packs/Core/Playbooks/playbook-Impossible_Traveler.yml
  Packs/Core/Playbooks/playbook-Impossible_Traveler_-_Enrichment.yml
  Packs/Core/ReleaseNotes/1_3_15.md
  Packs/Core/pack_metadata.json
Labels: docs-approved

#22280 New url formatter - trailing "]" issue
  Packs/CommonScripts/ReleaseNotes/1_10_7.md
  Packs/CommonScripts/Scripts/FormatURL/FormatURL.py
  Packs/CommonScripts/pack_metadata.json
Labels: docs-approved

#21335 Single Connect Integration
  Packs/SingleConnect/.pack-ignore
  Packs/SingleConnect/.secrets-ignore
  Packs/SingleConnect/Author_image.png
  Packs/SingleConnect/Integrations/SingleConnect/README.md
  Packs/SingleConnect/Integrations/SingleConnect/SingleConnect.py
  Packs/SingleConnect/Integrations/SingleConnect/SingleConnect.yml
  Packs/SingleConnect/Integrations/SingleConnect/SingleConnect_description.md
  Packs/SingleConnect/Integrations/SingleConnect/SingleConnect_image.png
  Packs/SingleConnect/Integrations/SingleConnect/SingleConnect_test.py
  Packs/SingleConnect/Integrations/SingleConnect/command_examples
  Packs/SingleConnect/Integrations/SingleConnect/test_data/http_responses.py
  Packs/SingleConnect/README.md
  Packs/SingleConnect/pack_metadata.json
Labels: Contribution, Partner, pending-demo, Contribution Form Filled

#21965 Fix fireEye hx bugs
  Packs/FireEyeHX/Integrations/FireEyeHXv2/FireEyeHXv2.py
  Packs/FireEyeHX/Integrations/FireEyeHXv2/FireEyeHXv2.yml
  Packs/FireEyeHX/Integrations/FireEyeHXv2/FireEyeHXv2_test.py
  Packs/FireEyeHX/ReleaseNotes/2_2_9.md
  Packs/FireEyeHX/pack_metadata.json
Labels: docs-approved, release-notes-only

#22113 fix path of zip files
  Tests/scripts/utils/compare_staging_graph.py
Labels: docs-approved

#20885 Ms collector alignments
  Packs/Microsoft365Defender/ReleaseNotes/4_4_0.md
  Packs/Microsoft365Defender/pack_metadata.json
  Packs/MicrosoftDefenderAdvancedThreatProtection/Integrations/Microsoft365DefenderEventCollector/Microsoft365DefenderEventCollector.py
  Packs/MicrosoftDefenderAdvancedThreatProtection/Integrations/Microsoft365DefenderEventCollector/Microsoft365DefenderEventCollector.yml
  Packs/MicrosoftDefenderAdvancedThreatProtection/Integrations/Microsoft365DefenderEventCollector/Microsoft365DefenderEventCollector_description.md
  Packs/MicrosoftDefenderAdvancedThreatProtection/Integrations/Microsoft365DefenderEventCollector/Microsoft365DefenderEventCollector_image.png
  Packs/MicrosoftDefenderAdvancedThreatProtection/Integrations/Microsoft365DefenderEventCollector/Microsoft365DefenderEventCollector_test.py
  Packs/MicrosoftDefenderAdvancedThreatProtection/Integrations/Microsoft365DefenderEventCollector/Pipfile
  Packs/MicrosoftDefenderAdvancedThreatProtection/Integrations/Microsoft365DefenderEventCollector/Pipfile.lock
  Packs/MicrosoftDefenderAdvancedThreatProtection/Integrations/Microsoft365DefenderEventCollector/README.md
  Packs/MicrosoftDefenderAdvancedThreatProtection/Integrations/Microsoft365DefenderEventCollector/command_examples
  Packs/MicrosoftDefenderAdvancedThreatProtection/ModelingRules/Microsoft365DefenderEventCollector/Microsoft365DefenderEventCollector.xif
  Packs/MicrosoftDefenderAdvancedThreatProtection/ModelingRules/Microsoft365DefenderEventCollector/Microsoft365DefenderEventCollector.yml
  Packs/MicrosoftDefenderAdvancedThreatProtection/ModelingRules/Microsoft365DefenderEventCollector/Microsoft365DefenderEventCollector_schema.json
  Packs/MicrosoftDefenderAdvancedThreatProtection/ModelingRules/Microsoft365DefenderEventCollector_1_3/Microsoft365DefenderEventCollector_1_3.xif
  Packs/MicrosoftDefenderAdvancedThreatProtection/ModelingRules/Microsoft365DefenderEventCollector_1_3/Microsoft365DefenderEventCollector_1_3.yml
  Packs/MicrosoftDefenderAdvancedThreatProtection/ModelingRules/Microsoft365DefenderEventCollector_1_3/Microsoft365DefenderEventCollector_1_3_schema.json
  Packs/MicrosoftDefenderAdvancedThreatProtection/ReleaseNotes/1_14_0.json
  Packs/MicrosoftDefenderAdvancedThreatProtection/ReleaseNotes/1_14_0.md
  Packs/MicrosoftDefenderAdvancedThreatProtection/pack_metadata.json
Labels: docs-approved

#21549 feat(SEKOIAIntelligenceCenter): add `ip`, `domain`, `url`, `email`, `file` command
  Packs/SEKOIAIntelligenceCenter/.secrets-ignore
  Packs/SEKOIAIntelligenceCenter/Integrations/SEKOIAIntelligenceCenter/README.md
  Packs/SEKOIAIntelligenceCenter/Integrations/SEKOIAIntelligenceCenter/SEKOIAIntelligenceCenter.py
  Packs/SEKOIAIntelligenceCenter/Integrations/SEKOIAIntelligenceCenter/SEKOIAIntelligenceCenter.yml
  Packs/SEKOIAIntelligenceCenter/Integrations/SEKOIAIntelligenceCenter/SEKOIAIntelligenceCenter_test.py
  Packs/SEKOIAIntelligenceCenter/Integrations/SEKOIAIntelligenceCenter/command_examples
  Packs/SEKOIAIntelligenceCenter/ReleaseNotes/1_1_0.md
  Packs/SEKOIAIntelligenceCenter/pack_metadata.json
Labels: Contribution, docs-approved, Partner, Contribution Form Filled, pending-contributor

#22282 Add fields to SaasSecurity modeling rule
  Packs/PrismaSaasSecurity/ModelingRules/SaasSecurityEventCollector_1_3/SaasSecurityEventCollector_1_3.xif
  Packs/PrismaSaasSecurity/ModelingRules/SaasSecurityEventCollector_1_3/SaasSecurityEventCollector_1_3_schema.json
  Packs/PrismaSaasSecurity/ReleaseNotes/2_0_9.md
  Packs/PrismaSaasSecurity/pack_metadata.json
Labels: docs-approved

#22315 Remove mote from landing
  Tests/Marketplace/landingPage_sections.json
Labels: docs-approved

#21888 Fix bug in RemedyOnDemand.js when running test-module
  Packs/Remedy-On-Demand/Integrations/RemedyOnDemand/RemedyOnDemand.js
  Packs/Remedy-On-Demand/ReleaseNotes/1_1_1.md
  Packs/Remedy-On-Demand/pack_metadata.json
Labels: Contribution, docs-approved, ready-for-instance-test, Contribution Form Filled, Community

#22312 Fixed RecordedFuture release notes
  Packs/RecordedFuture/ReleaseNotes/1_3_0.md
Labels: docs-approved

#22110 update reviewers
  Utils/github_workflow_scripts/handle_external_pr.py
Labels: docs-approved

#22325 Fix pytz import in commonserverpython
  Packs/Base/ReleaseNotes/1_31_36.md
  Packs/Base/Scripts/CommonServerPython/CommonServerPython.py
  Packs/Base/pack_metadata.json
Labels: docs-approved, ForceMerge
