Repository demisto/content, pull requests merged in 2022-01, with the labels that each got.

#16758 Syslog UT Fix
  Packs/Syslog/Integrations/Syslogv2/Syslogv2_test.py
  Packs/Syslog/Integrations/Syslogv2/test_data/long_running_loop_data.json
  Packs/Syslog/Integrations/Syslogv2/test_data/rfc_test_data.json
Labels: docs-approved

#16244 Dedup pb
  Packs/CommonScripts/ReleaseNotes/1_6_18.md
  Packs/CommonScripts/Scripts/FindSimilarIncidentsV2/FindSimilarIncidentsV2.py
  Packs/CommonScripts/Scripts/FindSimilarIncidentsV2/FindSimilarIncidentsV2.yml
  Packs/CommonScripts/Scripts/FindSimilarIncidentsV2/find_similar_incidents_test.py
  Packs/CommonScripts/pack_metadata.json
  Tests/conf.json
Labels: docs-approved, release-notes-only

#16767 Fix file name in .pack-ignore
  Packs/CommonScripts/.pack-ignore
Labels: docs-approved

#16759 Update handle_external_pr.py
  Utils/github_workflow_scripts/handle_external_pr.py
Labels: docs-approved

#16772 Un-skipped RF tests
  Tests/conf.json
Labels: docs-approved

#16523 EWS O365 credentials
  Packs/EWS/.pack-ignore
  Packs/EWS/Integrations/EWSO365/EWSO365.py
  Packs/EWS/Integrations/EWSO365/EWSO365.yml
  Packs/EWS/Integrations/EWSO365/EWSO365_test.py
  Packs/EWS/ReleaseNotes/1_11_1.md
  Packs/EWS/pack_metadata.json
Labels: docs-approved

#16768 AWS-guarduty-missing-params
  Packs/AWS-GuardDuty/Integrations/AWSGuardDuty/README.md
Labels: docs-approved

#16688 Revert the runas to DBOt role in deleteContext scrupt
  Packs/CommonScripts/.pack-ignore
  Packs/CommonScripts/ReleaseNotes/1_6_19.md
  Packs/CommonScripts/Scripts/DeleteContext/DeleteContext.yml
  Packs/CommonScripts/pack_metadata.json
  Packs/FeedMitreAttack/TestPlaybooks/playbook-Mitre_Attack_List_2_Indicators_Feed_Test.yml
  Tests/conf.json
Labels: bug, docs-approved, release-notes-only

#16549 No update feature
  Packs/ApiModules/Scripts/CSVFeedApiModule/CSVFeedApiModule.py
  Packs/ApiModules/Scripts/CSVFeedApiModule/CSVFeedApiModule_test.py
  Packs/ApiModules/Scripts/HTTPFeedApiModule/HTTPFeedApiModule.py
  Packs/ApiModules/Scripts/HTTPFeedApiModule/HTTPFeedApiModule_test.py
  Packs/ApiModules/Scripts/JSONFeedApiModule/JSONFeedApiModule.py
  Packs/ApiModules/Scripts/JSONFeedApiModule/JSONFeedApiModule_test.py
  Packs/FeedAWS/Integrations/FeedAWS/FeedAWS.yml
  Packs/FeedAWS/ReleaseNotes/1_1_12.md
  Packs/FeedAWS/pack_metadata.json
Labels: docs-approved

#16647 Gmail single user ga
  Packs/GmailSingleUser/Integrations/GmailSingleUser/GmailSingleUser.py
  Packs/GmailSingleUser/Integrations/GmailSingleUser/GmailSingleUser.yml
  Packs/GmailSingleUser/Integrations/GmailSingleUser/GmailSingleUser_description.md
  Packs/GmailSingleUser/Integrations/GmailSingleUser/GmailSingleUser_test.py
  Packs/GmailSingleUser/Integrations/GmailSingleUser/Pipfile
  Packs/GmailSingleUser/Integrations/GmailSingleUser/Pipfile.lock
  Packs/GmailSingleUser/Integrations/GmailSingleUser/README.md
  Packs/GmailSingleUser/Integrations/GmailSingleUser/commands.txt
  Packs/GmailSingleUser/Integrations/GmailSingleUser/doc_imgs/publish-OAuth-consent-screen.png
  Packs/GmailSingleUser/ReleaseNotes/1_1_5.md
  Packs/GmailSingleUser/pack_metadata.json
Labels: docs-approved

#16793 Update `modified` index - Malware Report
  Packs/ThreatIntelReports/Layouts/layoutscontainer-ThreatIntelReport-MalwareReport.json
  Packs/ThreatIntelReports/ReleaseNotes/1_0_6.md
  Packs/ThreatIntelReports/pack_metadata.json
Labels: docs-approved

#16796 Reported Email Origin Add SelectValues to GitIgnore
  Packs/Phishing/.pack-ignore
Labels: docs-approved

#16784 Azure kubernetes ga
  Packs/AzureKubernetesServices/Integrations/AzureKubernetesServices/AzureKubernetesServices.py
  Packs/AzureKubernetesServices/Integrations/AzureKubernetesServices/AzureKubernetesServices.yml
  Packs/AzureKubernetesServices/Integrations/AzureKubernetesServices/AzureKubernetesServices_description.md
  Packs/AzureKubernetesServices/Integrations/AzureKubernetesServices/Pipfile
  Packs/AzureKubernetesServices/Integrations/AzureKubernetesServices/Pipfile.lock
  Packs/AzureKubernetesServices/Integrations/AzureKubernetesServices/README.md
  Packs/AzureKubernetesServices/ReleaseNotes/1_0_7.md
  Packs/AzureKubernetesServices/pack_metadata.json
  Tests/known_words.txt
Labels: docs-approved

#16777 Change pack incident fields of type multiSelect with no select values to array
  Packs/Asset/IncidentFields/incidentfield-Description_-_Asset.json
  Packs/Asset/IncidentFields/incidentfield-ID_-_Asset.json
  Packs/Asset/IncidentFields/incidentfield-IP_Address_-_Asset.json
  Packs/Asset/IncidentFields/incidentfield-Location_-_Asset.json
  Packs/Asset/IncidentFields/incidentfield-MAC_Address_-_Asset.json
  Packs/Asset/IncidentFields/incidentfield-Switch_ID_-_Asset.json
  Packs/Asset/IncidentFields/incidentfield-Switch_Port_ID_-_Asset.json
  Packs/Asset/ReleaseNotes/1_0_3.md
  Packs/Asset/pack_metadata.json
  Packs/Campaign/IncidentFields/incidentfield-Select_Campaign_Incidents.json
  Packs/Campaign/IncidentFields/incidentfield-Select_Campaign_lower_similarity_Incidents.json
  Packs/Campaign/ReleaseNotes/3_2_3.md
  Packs/Campaign/pack_metadata.json
  Packs/CortexXDR/IncidentFields/incidentfield-XDR_Alert_Category.json
  Packs/CortexXDR/IncidentFields/incidentfield-XDR_Alert_Name.json
  Packs/CortexXDR/IncidentFields/incidentfield-XDR_File_Name.json
  Packs/CortexXDR/IncidentFields/incidentfield-XDR_File_SHA256.json
  Packs/CortexXDR/IncidentFields/incidentfield-XDR_MITRE_Tactics.json
  Packs/CortexXDR/IncidentFields/incidentfield-XDR_MITRE_Techniques.json
  Packs/CortexXDR/IncidentFields/incidentfield-XDR_Users.json
  Packs/CortexXDR/ReleaseNotes/4_2_15.md
  Packs/CortexXDR/pack_metadata.json
  Packs/IntegrationsAndIncidentsHealthCheck/IncidentFields/incidentfield-IntegrationsFailedCategories.json
  Packs/IntegrationsAndIncidentsHealthCheck/IncidentFields/incidentfield-PlaybookNamesWithFailedTasks.json
  Packs/IntegrationsAndIncidentsHealthCheck/IncidentFields/incidentfield-PlaybooksFailedCommands.json
  Packs/IntegrationsAndIncidentsHealthCheck/IncidentFields/incidentfield-PlaybooksWithFailedTasks.json
  Packs/IntegrationsAndIncidentsHealthCheck/IncidentFields/incidentfield-UnassignedIncidents.json
  Packs/IntegrationsAndIncidentsHealthCheck/ReleaseNotes/1_3_4.md
  Packs/IntegrationsAndIncidentsHealthCheck/pack_metadata.json
  Packs/NonSupported/IndicatorFields/incidentfield-tagsMultiSelectType.json
  Packs/QRadar/IncidentFields/incidentfield-Destination_IP_-_Offense.json
  Packs/QRadar/IncidentFields/incidentfield-Destination_Network_-_Offense.json
  Packs/QRadar/IncidentFields/incidentfield-List_of_Rules_-_Offense.json
  Packs/QRadar/IncidentFields/incidentfield-Low_Level_Categories_-_Offense.json
  Packs/QRadar/IncidentFields/incidentfield-Source_IP_-_Offense.json
  Packs/QRadar/IncidentFields/incidentfield-Source_Network_-_Offense.json
  Packs/QRadar/ReleaseNotes/2_1_23.md
  Packs/QRadar/pack_metadata.json
  Packs/Ransomware/IncidentFields/incidentfield-Ransomware_Cryptocurrency_Address.json
  Packs/Ransomware/IncidentFields/incidentfield-Ransomware_Cryptocurrency_Address_Type.json
  Packs/Ransomware/IncidentFields/incidentfield-Ransomware_Email.json
  Packs/Ransomware/IncidentFields/incidentfield-Ransomware_Onion_Address.json
  Packs/Ransomware/ReleaseNotes/1_0_9.md
  Packs/Ransomware/pack_metadata.json
Labels: docs-approved

#16774 moving lint to gitlab
  .circleci/config.yml
  .gitlab/ci/on-push.yml
Labels: docs-approved

#16837 CircleCI: cleanup config file
  .circleci/config.yml
Labels: docs-approved

#16815 Get away users widget
  Packs/ShiftManagement/Dashboards/dashboard-Shift_Management_.json
  Packs/ShiftManagement/ReleaseNotes/1_3_4.md
  Packs/ShiftManagement/Scripts/AssignAnalystToIncidentOOO/AssignAnalystToIncidentOOO.py
  Packs/ShiftManagement/Scripts/AssignAnalystToIncidentOOO/AssignAnalystToIncidentOOO.yml
  Packs/ShiftManagement/Scripts/AssignAnalystToIncidentOOO/AssignAnalystToIncidentOOO_test.py
  Packs/ShiftManagement/Scripts/AssignToNextShiftOOO/AssignToNextShiftOOO.py
  Packs/ShiftManagement/Scripts/AssignToNextShiftOOO/AssignToNextShiftOOO.yml
  Packs/ShiftManagement/Scripts/GetAwayUsers/GetAwayUsers.py
  Packs/ShiftManagement/Scripts/GetAwayUsers/GetAwayUsers.yml
  Packs/ShiftManagement/Scripts/GetAwayUsers/GetAwayUsers_test.py
  Packs/ShiftManagement/Scripts/GetNumberOfUsersOnCall/GetNumberOfUsersOnCall.py
  Packs/ShiftManagement/Scripts/GetNumberOfUsersOnCall/GetNumberOfUsersOnCall.yml
  Packs/ShiftManagement/Scripts/GetNumberOfUsersOnCall/GetNumberOfUsersOnCall_test.py
  Packs/ShiftManagement/Scripts/GetUsersOnCall/GetUsersOnCall.py
  Packs/ShiftManagement/Scripts/GetUsersOnCall/GetUsersOnCall.yml
  Packs/ShiftManagement/Scripts/GetUsersOnCall/GetUsersOnCall_test.py
  Packs/ShiftManagement/Widgets/Widget-AwayUsers.json
  Packs/ShiftManagement/pack_metadata.json
Labels: docs-approved, release-notes-only

#16702 added map range values script
  Packs/FiltersAndTransformers/.pack-ignore
  Packs/FiltersAndTransformers/.secrets-ignore
  Packs/FiltersAndTransformers/README.md
  Packs/FiltersAndTransformers/Scripts/MapRangeValues/MapRangeValues.py
  Packs/FiltersAndTransformers/Scripts/MapRangeValues/MapRangeValues.yml
  Packs/FiltersAndTransformers/Scripts/MapRangeValues/MapRangeValues_test.py
  Packs/FiltersAndTransformers/pack_metadata.json
Labels: docs-approved

#16836 Update pre-commit
  .hooks/pre-commit
Labels: docs-approved

#16382 New Otsecurity Pack
  Packs/OTSecurity/.pack-ignore
  Packs/OTSecurity/.secrets-ignore
  Packs/OTSecurity/Classifiers/classifier-OTSecurity_API_Classifier_v1.json
  Packs/OTSecurity/Classifiers/classifier-mapper-incoming-OTSecurity_API_Incoming_Mapper_v1.json
  Packs/OTSecurity/IncidentFields/OTSecurity_Protocols.json
  Packs/OTSecurity/IncidentFields/OTSecurity_Substation_Contact.json
  Packs/OTSecurity/IncidentFields/OTSecurity_Substation_Location.json
  Packs/OTSecurity/IncidentFields/OTSecurity_Substation_Name.json
  Packs/OTSecurity/IncidentTypes/OTSecurity_Rogue_Device_Found.json
  Packs/OTSecurity/IndicatorTypes/MAC_Address.json
  Packs/OTSecurity/Layouts/layoutscontainer-MAC_Indicator.json
  Packs/OTSecurity/Layouts/layoutscontainer-OTSecurity_Rogue_Device_Found.json
  Packs/OTSecurity/Playbooks/Cisco_ISE_-_Block_MAC_Address.yml
  Packs/OTSecurity/Playbooks/OTSecurity_-_Rogue_Device_Investigation.yml
  Packs/OTSecurity/README.md
  Packs/OTSecurity/doc_files/ATT&CK T810.png
  Packs/OTSecurity/doc_files/ATT&CK T824.png
  Packs/OTSecurity/doc_files/ATT&CK T848.png
  Packs/OTSecurity/doc_files/ATT&CK T851.png
  Packs/OTSecurity/doc_files/ATT&CK T862.png
  Packs/OTSecurity/doc_files/ATT&CK T873.png
  Packs/OTSecurity/doc_files/ATT&CK T875.png
  Packs/OTSecurity/doc_files/IsolatedDeployment.png
  Packs/OTSecurity/doc_files/OTSecurityEnvironment.png
  Packs/OTSecurity/pack_metadata.json
Labels: Contribution, docs-approved, Contribution Form Filled, Community

#16795 Fix outputs in Checkpoint Firewall
  Packs/CheckpointFirewall/Integrations/CheckPointFirewallV2/CheckPointFirewallV2.yml
  Packs/CheckpointFirewall/Integrations/CheckPointFirewallV2/README.md
  Packs/CheckpointFirewall/ReleaseNotes/2_1_10.md
  Packs/CheckpointFirewall/pack_metadata.json
Labels: docs-approved

#16583 CommonServerPython: add traceback line number adjustments
  Documentation/common_server_docs.py
  Packs/Base/ReleaseNotes/1_18_0.md
  Packs/Base/Scripts/CommonServerPython/CommonServerPython.py
  Packs/Base/Scripts/CommonServerPython/CommonServerPython_test.py
  Packs/Base/pack_metadata.json
Labels: docs-approved

#16746 Update Okta_v2.py
  Packs/Okta/Integrations/Okta_v2/Okta_v2.py
  Packs/Okta/Integrations/Okta_v2/Okta_v2.yml
  Packs/Okta/Integrations/Okta_v2/Okta_v2_test.py
  Packs/Okta/ReleaseNotes/2_2_10.md
  Packs/Okta/pack_metadata.json
Labels: Contribution, docs-approved, ready-for-instance-test, post-demo

#16853 Deprecate Blockade.io
  Packs/Blockade.io/Integrations/BlockadeIo/BlockadeIo.yml
  Packs/Blockade.io/ReleaseNotes/1_1_0.md
  Packs/Blockade.io/pack_metadata.json
Labels: docs-approved

#16667 fixed issue with v2 api not on user search
  Packs/Jira/.secrets-ignore
  Packs/Jira/Integrations/JiraV2/JiraV2.py
  Packs/Jira/Integrations/JiraV2/JiraV2.yml
  Packs/Jira/ReleaseNotes/1_4_5.md
  Packs/Jira/pack_metadata.json
Labels: Contribution, docs-approved, Contribution Form Filled, Community

#13872 Grafana integration with all commands
  Packs/Grafana/.pack-ignore
  Packs/Grafana/.secrets-ignore
  Packs/Grafana/Classifiers/classifier-Grafana_Alert.json
  Packs/Grafana/Classifiers/classifier-Grafana_Alert_Mapper.json
  Packs/Grafana/IncidentFields/incidentfield-dashboardlink.json
  Packs/Grafana/IncidentFields/incidentfield-dashboarduid.json
  Packs/Grafana/IncidentFields/incidentfield-panelid.json
  Packs/Grafana/IncidentTypes/incidenttype-Grafana_Alert.json
  Packs/Grafana/Integrations/Grafana/Grafana.py
  Packs/Grafana/Integrations/Grafana/Grafana.yml
  Packs/Grafana/Integrations/Grafana/Grafana_description.md
  Packs/Grafana/Integrations/Grafana/Grafana_image.png
  Packs/Grafana/Integrations/Grafana/Grafana_test.py
  Packs/Grafana/Integrations/Grafana/Pipfile
  Packs/Grafana/Integrations/Grafana/Pipfile.lock
  Packs/Grafana/Integrations/Grafana/README.md
  Packs/Grafana/Integrations/Grafana/TestData/alerts_to_filter_by_date.json
  Packs/Grafana/Integrations/Grafana/TestData/alerts_to_filter_by_time.json
  Packs/Grafana/Integrations/Grafana/TestData/change_key_values.json
  Packs/Grafana/Integrations/Grafana/TestData/concatenate_url_values.json
  Packs/Grafana/Integrations/Grafana/TestData/incidents_to_reduce.json
  Packs/Grafana/Integrations/Grafana/TestData/keys_to_lowercase.json
  Packs/Grafana/Integrations/Grafana/TestData/parse_alerts_values.json
  Packs/Grafana/Integrations/Grafana/command_examples
  Packs/Grafana/Layouts/layoutscontainer-Grafana_Layout.json
  Packs/Grafana/README.md
  Packs/Grafana/TestPlaybooks/Grafana-Test.yml
  Packs/Grafana/pack_metadata.json
  Tests/conf.json
Labels: docs-approved

#16881 FeedCSV - Update
  Packs/FeedCSV/ReleaseNotes/1_1_7.md
  Packs/FeedCSV/pack_metadata.json
Labels: docs-approved

#16857 Add OVERRIDE_ALL_PACKS to allow uploading all packs
  .gitlab/ci/.gitlab-ci.yml
  .gitlab/ci/global.yml
  Tests/Marketplace/marketplace_services.py
  Tests/scripts/prepare_content_packs_for_testing.sh
  Utils/trigger_test_upload_flow.sh
Labels: docs-approved

#16863 Phishingv3 minor bugs fix
  Packs/Phishing/Playbooks/Phishing_-_Generic_v3.yml
  Packs/Phishing/Playbooks/Phishing_-_Generic_v3_README.md
  Packs/Phishing/ReleaseNotes/3_0_2.md
  Packs/Phishing/pack_metadata.json
Labels: docs-approved

#16895 Fixed playbooks keys to support id-set creation
  Packs/Cybereason/Playbooks/playbook-Search_Endpoints_By_Hash_-_Cybereason.yml
  Packs/Cybereason/ReleaseNotes/1_0_18.md
  Packs/Cybereason/pack_metadata.json
  Packs/DigitalGuardian/Playbooks/DigitalGuardian_Demo.yml
  Packs/DigitalGuardian/ReleaseNotes/1_0_8.md
  Packs/DigitalGuardian/pack_metadata.json
  Packs/DomainTools_Iris/Playbooks/playbook-Indicator_Pivoting-DomainTools_Iris.yml
  Packs/DomainTools_Iris/ReleaseNotes/1_1_3.md
  Packs/DomainTools_Iris/pack_metadata.json
  Packs/Endace/Playbooks/playbook_Endace_Search_Archive_Download.yml
  Packs/Endace/ReleaseNotes/1_1_8.md
  Packs/Endace/pack_metadata.json
  Packs/IllusiveNetworks/Playbooks/playbook-Illusive-Retrieve-Incident.yml
  Packs/IllusiveNetworks/ReleaseNotes/1_0_12.md
  Packs/IllusiveNetworks/pack_metadata.json
  Packs/Malwarebytes/Playbooks/Malwarebytes_Endpoint_Isolation.yml
  Packs/Malwarebytes/ReleaseNotes/1_1_7.md
  Packs/Malwarebytes/pack_metadata.json
  Packs/PaloAltoNetworks_PAN_OS_EDL_Management/Playbooks/playbook-PAN-OS_-_Block_IP_and_URL_-_External_Dynamic_List_v2.yml
  Packs/PaloAltoNetworks_PAN_OS_EDL_Management/ReleaseNotes/1_1_2.md
  Packs/PaloAltoNetworks_PAN_OS_EDL_Management/pack_metadata.json
  Packs/Pcysys/Playbooks/playbook-Pentera_Filter_And_Create_Incident.yml
  Packs/Pcysys/ReleaseNotes/1_3_3.md
  Packs/Pcysys/pack_metadata.json
  Packs/PortScan/Playbooks/Port_Scan_-_Generic.yml
  Packs/PortScan/ReleaseNotes/1_1_5.md
  Packs/PortScan/pack_metadata.json
  Packs/QRadar/Playbooks/playbook-QRadarCorrelationLog.yml
  Packs/QRadar/ReleaseNotes/2_1_24.md
  Packs/QRadar/pack_metadata.json
  Packs/TIM_Processing/Playbooks/playbook-TIM_-_Process_CIDR_Indicators_By_Size.yml
  Packs/TIM_Processing/ReleaseNotes/1_1_12.md
  Packs/TIM_Processing/pack_metadata.json
  Packs/epo/Playbooks/playbook-McAfee_ePO_Endpoint_Compliance_v2.yml
  Packs/epo/Playbooks/playbook-McAfee_ePO_Endpoint_Connectivity_Diagnostics_v2.yml
  Packs/epo/ReleaseNotes/2_0_1.md
  Packs/epo/pack_metadata.json
Labels: docs-approved

#16556 adopt vmray pack
  Packs/VMRay/Author_image.png
  Packs/VMRay/README.md
  Packs/VMRay/ReleaseNotes/1_1_5.md
  Packs/VMRay/pack_metadata.json
Labels: Contribution, docs-approved, Partner, Contribution Form Filled, pending-partner

#16879 Fix context name in DbotFindSimilarIncidentByIndicators
  Packs/Base/ReleaseNotes/1_18_1.md
  Packs/Base/Scripts/DBotFindSimilarIncidentsByIndicators/DBotFindSimilarIncidentsByIndicators.py
  Packs/Base/pack_metadata.json
Labels: docs-approved

#14421 New URL Phishing Pack
  Packs/PhishingURL/.pack-ignore
  Packs/PhishingURL/.secrets-ignore
  Packs/PhishingURL/README.md
  Packs/PhishingURL/Scripts/DBotPredictURLPhishing/DBotPredictURLPhishing.py
  Packs/PhishingURL/Scripts/DBotPredictURLPhishing/DBotPredictURLPhishing.yml
  Packs/PhishingURL/Scripts/DBotPredictURLPhishing/dbotpredicturlphishing_test.py
  Packs/PhishingURL/TestPlaybooks/DBotPredictURLPhishing_test.yml
  Packs/PhishingURL/pack_metadata.json
  Tests/conf.json
Labels: docs-approved

#16886 Feed mitre attackv2 links fix
  Packs/FeedMitreAttackv2/Integrations/FeedMitreAttackv2/FeedMitreAttackv2.py
  Packs/FeedMitreAttackv2/Integrations/FeedMitreAttackv2/FeedMitreAttackv2_test.py
  Packs/FeedMitreAttackv2/Integrations/FeedMitreAttackv2/test_data/mitre_test_data.py
  Packs/FeedMitreAttackv2/ReleaseNotes/1_0_9.md
  Packs/FeedMitreAttackv2/pack_metadata.json
Labels: docs-approved

#16904 Fix Slackv2 TestPB
  Packs/Slack/TestPlaybooks/playbook-Slack_TestPlaybook.yml
Labels: docs-approved

#16160 Fix remedy on demand fetch error
  Packs/Remedy-On-Demand/Integrations/RemedyOnDemand/RemedyOnDemand.js
  Packs/Remedy-On-Demand/ReleaseNotes/1_0_4.md
  Packs/Remedy-On-Demand/pack_metadata.json
Labels: bug, docs-approved, release-notes-only

#16907 Remove API key from logs
  Packs/AutoFocus/Integrations/AutoFocusTagsFeed/AutoFocusTagsFeed.py
  Packs/AutoFocus/Integrations/AutoFocusTagsFeed/AutoFocusTagsFeed.yml
  Packs/AutoFocus/Integrations/AutoFocusTagsFeed/AutoFocusTagsFeed_test.py
  Packs/AutoFocus/ReleaseNotes/2_0_7.md
  Packs/AutoFocus/pack_metadata.json
  Packs/Palo_Alto_Networks_WildFire/Integrations/WildFireReports/WildFireReports.py
  Packs/Palo_Alto_Networks_WildFire/Integrations/WildFireReports/WildFireReports.yml
  Packs/Palo_Alto_Networks_WildFire/Integrations/WildFireReports/WildFireReports_test.py
  Packs/Palo_Alto_Networks_WildFire/ReleaseNotes/2_0_5.md
  Packs/Palo_Alto_Networks_WildFire/pack_metadata.json
  Packs/Unit42Intel/Integrations/FeedUnit42IntelObjects/FeedUnit42IntelObjects.py
  Packs/Unit42Intel/Integrations/FeedUnit42IntelObjects/FeedUnit42IntelObjects.yml
  Packs/Unit42Intel/Integrations/FeedUnit42IntelObjects/FeedUnit42IntelObjects_test.py
  Packs/Unit42Intel/ReleaseNotes/1_0_1.md
  Packs/Unit42Intel/pack_metadata.json
Labels: docs-approved

#16760 new Wiz Pack
  Packs/Wiz/.pack-ignore
  Packs/Wiz/.secrets-ignore
  Packs/Wiz/Author_image.png
  Packs/Wiz/Classifiers/classifier-WizIssue.json
  Packs/Wiz/Classifiers/classifier-Wiz_Mapper.json
  Packs/Wiz/Classifiers/classifier-Wiz_Mapper_Webhook.json
  Packs/Wiz/IncidentFields/incidentfield-Wiz_Cloud_Account.json
  Packs/Wiz/IncidentFields/incidentfield-Wiz_Cloud_Account_Name.json
  Packs/Wiz/IncidentFields/incidentfield-Wiz_Cloud_Platform.json
  Packs/Wiz/IncidentFields/incidentfield-Wiz_Details.json
  Packs/Wiz/IncidentFields/incidentfield-Wiz_Issue_Due_Date.json
  Packs/Wiz/IncidentFields/incidentfield-Wiz_Issue_ID.json
  Packs/Wiz/IncidentFields/incidentfield-Wiz_Issue_Note.json
  Packs/Wiz/IncidentFields/incidentfield-Wiz_Resource_ID.json
  Packs/Wiz/IncidentFields/incidentfield-Wiz_Resource_Region.json
  Packs/Wiz/IncidentFields/incidentfield-Wiz_Resource_Type.json
  Packs/Wiz/IncidentTypes/incidenttype-WizIssue.json
  Packs/Wiz/Integrations/Wiz/Pipfile
  Packs/Wiz/Integrations/Wiz/Pipfile.lock
  Packs/Wiz/Integrations/Wiz/README.md
  Packs/Wiz/Integrations/Wiz/Wiz.py
  Packs/Wiz/Integrations/Wiz/Wiz.yml
  Packs/Wiz/Integrations/Wiz/Wiz_description.md
  Packs/Wiz/Integrations/Wiz/Wiz_image.png
  Packs/Wiz/Integrations/Wiz/Wiz_test.py
  Packs/Wiz/Integrations/command_examples.txt
  Packs/Wiz/Layouts/layoutscontainer-Wiz.json
  Packs/Wiz/README.md
  Packs/Wiz/pack_metadata.json
Labels: Contribution, docs-approved, Partner, post-demo, Contribution Form Filled, Community

#16908 Log4j v9
  Packs/CVE_2021_44228/Playbooks/playbook-CVE-2021-44228_-_Log4j_RCE.yml
  Packs/CVE_2021_44228/Playbooks/playbook-CVE-2021-44228_-_Log4j_RCE_README.md
  Packs/CVE_2021_44228/README.md
  Packs/CVE_2021_44228/ReleaseNotes/1_0_9.md
  Packs/CVE_2021_44228/doc_files/CVE-2021-44228_-_Log4j_RCE.png
  Packs/CVE_2021_44228/pack_metadata.json
Labels: docs-approved

#16890 No update feature - update feeds release notes
  Packs/BitcoinAbuse/ReleaseNotes/1_0_16.md
  Packs/BitcoinAbuse/pack_metadata.json
  Packs/FeedAlienVault/ReleaseNotes/1_1_11.md
  Packs/FeedAlienVault/pack_metadata.json
  Packs/FeedBambenekConsulting/ReleaseNotes/1_1_11.md
  Packs/FeedBambenekConsulting/pack_metadata.json
  Packs/FeedBlocklist_de/ReleaseNotes/1_1_11.md
  Packs/FeedBlocklist_de/pack_metadata.json
  Packs/FeedBruteForceBlocker/ReleaseNotes/1_1_11.md
  Packs/FeedBruteForceBlocker/pack_metadata.json
  Packs/FeedCSV/ReleaseNotes/1_1_8.md
  Packs/FeedCSV/pack_metadata.json
  Packs/FeedCloudflare/ReleaseNotes/1_1_11.md
  Packs/FeedCloudflare/pack_metadata.json
  Packs/FeedDShield/ReleaseNotes/1_1_11.md
  Packs/FeedDShield/pack_metadata.json
  Packs/FeedFastly/ReleaseNotes/1_1_10.md
  Packs/FeedFastly/pack_metadata.json
  Packs/FeedFeodoTracker/ReleaseNotes/1_1_13.md
  Packs/FeedFeodoTracker/pack_metadata.json
  Packs/FeedGCPWhitelist/ReleaseNotes/2_0_2.md
  Packs/FeedGCPWhitelist/pack_metadata.json
  Packs/FeedIntel471/ReleaseNotes/2_0_8.md
  Packs/FeedIntel471/pack_metadata.json
  Packs/FeedJSON/ReleaseNotes/1_1_10.md
  Packs/FeedJSON/pack_metadata.json
  Packs/FeedMajesticMillion/ReleaseNotes/1_1_8.md
  Packs/FeedMajesticMillion/pack_metadata.json
  Packs/FeedMalwareBazaar/ReleaseNotes/1_0_2.md
  Packs/FeedMalwareBazaar/pack_metadata.json
  Packs/FeedPlainText/ReleaseNotes/1_1_8.md
  Packs/FeedPlainText/pack_metadata.json
  Packs/FeedSpamhaus/ReleaseNotes/1_1_11.md
  Packs/FeedSpamhaus/pack_metadata.json
  Packs/Feedsslabusech/ReleaseNotes/1_1_11.md
  Packs/Feedsslabusech/pack_metadata.json
  Packs/iDefense/ReleaseNotes/3_2_1.md
  Packs/iDefense/pack_metadata.json
  Tests/known_words.txt
Labels: docs-approved

#16910 Splunk Search Headers Bug Fix
  Packs/SplunkPy/Integrations/SplunkPy/README.md
  Packs/SplunkPy/Integrations/SplunkPy/SplunkPy.py
  Packs/SplunkPy/Integrations/SplunkPy/SplunkPy_test.py
  Packs/SplunkPy/ReleaseNotes/2_2_10.md
  Packs/SplunkPy/pack_metadata.json
Labels: docs-approved

#16809 Fix incorrect layout name assigned to main incident type
  Packs/SocialEngineeringDomainAnalysis/IncidentTypes/incidenttype-Social_Engineering_Domain_Investigation.json
  Packs/SocialEngineeringDomainAnalysis/Playbooks/Social_Engineering_Domain_Enrichment_README.md
  Packs/SocialEngineeringDomainAnalysis/Playbooks/Social_Engineering_Domain_Investigation.yml
  Packs/SocialEngineeringDomainAnalysis/Playbooks/Social_Engineering_Domain_Investigation_README.md
  Packs/SocialEngineeringDomainAnalysis/ReleaseNotes/1_0_1.md
  Packs/SocialEngineeringDomainAnalysis/pack_metadata.json
Labels: Contribution, docs-approved, Contribution Form Filled, Community

#16918 [Fix] DBotPredictURLPhishing validate errors
  Packs/PhishingURL/Scripts/DBotPredictURLPhishing/DBotPredictURLPhishing.yml
  Packs/PhishingURL/TestPlaybooks/DBotPredictURLPhishing_test.yml
  Packs/PhishingURL/pack_metadata.json
Labels: docs-approved

#16924 Add GCP_MARKET_BUCKET build parameter
  .circleci/config.yml
Labels: docs-approved

#16403 Integration tutorial
  docs/tutorial-video/Integration-Yoda_Speak.yml
  docs/tutorial-video/README.md
  docs/tutorial-video/YodaSpeak/.pack-ignore
  docs/tutorial-video/YodaSpeak/.secrets-ignore
  docs/tutorial-video/YodaSpeak/Integrations/YodaSpeak/Pipfile
  docs/tutorial-video/YodaSpeak/Integrations/YodaSpeak/Pipfile.lock
  docs/tutorial-video/YodaSpeak/Integrations/YodaSpeak/README.md
  docs/tutorial-video/YodaSpeak/Integrations/YodaSpeak/YodaSpeak.py
  docs/tutorial-video/YodaSpeak/Integrations/YodaSpeak/YodaSpeak.yml
  docs/tutorial-video/YodaSpeak/Integrations/YodaSpeak/YodaSpeak_description.md
  docs/tutorial-video/YodaSpeak/Integrations/YodaSpeak/YodaSpeak_test.py
  docs/tutorial-video/YodaSpeak/Integrations/YodaSpeak/command_examples
  docs/tutorial-video/YodaSpeak/Integrations/YodaSpeak/test_data/test-module-fail-no-success.json
  docs/tutorial-video/YodaSpeak/Integrations/YodaSpeak/test_data/test-module-fail-zero-success.json
  docs/tutorial-video/YodaSpeak/Integrations/YodaSpeak/test_data/translate-fail-no-translation.json
  docs/tutorial-video/YodaSpeak/Integrations/YodaSpeak/test_data/translate.json
  docs/tutorial-video/YodaSpeak/README.md
  docs/tutorial-video/YodaSpeak/TestPlaybooks/playbook-YodaSpeak_Test.yml
  docs/tutorial-video/YodaSpeak/pack_metadata.json
  docs/tutorial-video/playbook-Yoda_Speak.yml
Labels: docs-approved

#16927 rename tutorial integration path
  docs/tutorial-integration/YodaSpeak/.pack-ignore
  docs/tutorial-integration/YodaSpeak/.secrets-ignore
  docs/tutorial-integration/YodaSpeak/Integrations/YodaSpeak/Pipfile
  docs/tutorial-integration/YodaSpeak/Integrations/YodaSpeak/Pipfile.lock
  docs/tutorial-integration/YodaSpeak/Integrations/YodaSpeak/README.md
  docs/tutorial-integration/YodaSpeak/Integrations/YodaSpeak/YodaSpeak.py
  docs/tutorial-integration/YodaSpeak/Integrations/YodaSpeak/YodaSpeak.yml
  docs/tutorial-integration/YodaSpeak/Integrations/YodaSpeak/YodaSpeak_description.md
  docs/tutorial-integration/YodaSpeak/Integrations/YodaSpeak/YodaSpeak_test.py
  docs/tutorial-integration/YodaSpeak/Integrations/YodaSpeak/command_examples
  docs/tutorial-integration/YodaSpeak/Integrations/YodaSpeak/test_data/test-module-fail-no-success.json
  docs/tutorial-integration/YodaSpeak/Integrations/YodaSpeak/test_data/test-module-fail-zero-success.json
  docs/tutorial-integration/YodaSpeak/Integrations/YodaSpeak/test_data/translate-fail-no-translation.json
  docs/tutorial-integration/YodaSpeak/Integrations/YodaSpeak/test_data/translate.json
  docs/tutorial-integration/YodaSpeak/README.md
  docs/tutorial-integration/YodaSpeak/TestPlaybooks/playbook-YodaSpeak_Test.yml
  docs/tutorial-integration/YodaSpeak/pack_metadata.json
Labels: docs-approved

#16929 Fix validation errors
  Packs/Slack/TestPlaybooks/playbook-Slack_TestPlaybook.yml
  Packs/SocialEngineeringDomainAnalysis/Playbooks/Social_Engineering_Domain_Enrichment_README.md
  Packs/SocialEngineeringDomainAnalysis/Playbooks/Social_Engineering_Domain_Investigation.yml
  Packs/SocialEngineeringDomainAnalysis/Playbooks/Social_Engineering_Domain_Investigation_README.md
Labels: docs-approved

#16820 SetAndHandleEmpty: allow setting of falsy values
  Packs/CommonScripts/ReleaseNotes/1_6_20.md
  Packs/CommonScripts/Scripts/SetAndHandleEmpty/SetAndHandleEmpty.py
  Packs/CommonScripts/Scripts/SetAndHandleEmpty/SetAndHandleEmpty.yml
  Packs/CommonScripts/Scripts/SetAndHandleEmpty/SetAndHandleEmpty_test.py
  Packs/CommonScripts/pack_metadata.json
Labels: docs-approved, release-notes-only

#16920 Fix bug in IsIncidentPartOfCampaign script
  Packs/Campaign/ReleaseNotes/3_2_4.md
  Packs/Campaign/Scripts/IsIncidentPartOfCampaign/IsIncidentPartOfCampaign.py
  Packs/Campaign/Scripts/IsIncidentPartOfCampaign/IsIncidentPartOfCampaign.yml
  Packs/Campaign/Scripts/IsIncidentPartOfCampaign/IsIncidentPartOfCampaign_test.py
  Packs/Campaign/pack_metadata.json
Labels: docs-approved

#16713 Active Directory Query: parse bool fields from userAccountControl
  Packs/Active_Directory_Query/Integrations/Active_Directory_Query/Active_Directory_Query.py
  Packs/Active_Directory_Query/Integrations/Active_Directory_Query/Active_Directory_Query.yml
  Packs/Active_Directory_Query/Integrations/Active_Directory_Query/Active_Directory_Query_test.py
  Packs/Active_Directory_Query/Integrations/Active_Directory_Query/README.md
  Packs/Active_Directory_Query/ReleaseNotes/1_4_3.md
  Packs/Active_Directory_Query/pack_metadata.json
Labels: bug, docs-approved

#16926 lastline documentation
  Packs/Lastline/Integrations/Lastline_v2/README.md
Labels: docs-approved

#16953 Update dev-requirements-py3.txt: replace parinx version
  dev-requirements-py3.txt
Labels: docs-approved

#16846 Prisma cloud compute authentication doc
  Packs/PrismaCloudCompute/Integrations/PaloAltoNetworks_PrismaCloudCompute/PaloAltoNetworks_PrismaCloudCompute.yml
  Packs/PrismaCloudCompute/Integrations/PaloAltoNetworks_PrismaCloudCompute/PaloAltoNetworks_PrismaCloudCompute_description.md
  Packs/PrismaCloudCompute/Integrations/PaloAltoNetworks_PrismaCloudCompute/README.md
  Packs/PrismaCloudCompute/Integrations/PaloAltoNetworks_PrismaCloudCompute/doc_images/available-user-roles.png
  Packs/PrismaCloudCompute/Integrations/PaloAltoNetworks_PrismaCloudCompute/doc_images/user-roles-configuration.png
  Packs/PrismaCloudCompute/ReleaseNotes/1_2_1.md
  Packs/PrismaCloudCompute/pack_metadata.json
  Tests/known_words.txt
Labels: docs-approved

#16922 FixShowLocationOnMap
  Packs/CommonScripts/ReleaseNotes/1_6_21.md
  Packs/CommonScripts/Scripts/ShowLocationOnMap/ShowLocationOnMap.py
  Packs/CommonScripts/Scripts/ShowLocationOnMap/ShowLocationOnMap.yml
  Packs/CommonScripts/Scripts/ShowLocationOnMap/ShowLocationOnMap_test.py
  Packs/CommonScripts/pack_metadata.json
Labels: docs-approved

#16576 SplunkPy- merge pre-release in to the official
  Packs/SplunkPy/Integrations/SplunkPy/SplunkPy.py
  Packs/SplunkPy/Integrations/SplunkPy/SplunkPy.yml
  Packs/SplunkPy/Integrations/SplunkPy/SplunkPy_description.md
  Packs/SplunkPy/README.md
  Packs/SplunkPy/ReleaseNotes/2_3_0.md
  Packs/SplunkPy/pack_metadata.json
  Packs/SplunkPyPreRelease/Integrations/SplunkPyPreRelease/SplunkPyPreRelease.py
  Packs/SplunkPyPreRelease/ReleaseNotes/1_0_5.md
  Packs/SplunkPyPreRelease/pack_metadata.json
Labels: docs-approved

#16954 Panorama - fmt get-logs cmd outputs table
  Packs/PAN-OS/Integrations/Panorama/README.md
Labels: docs-approved

#16882 Need to allow specification of mail-sender when notifying recipients in the Phishing Campaign layout
  Packs/Campaign/IncidentFields/incidentfield-Campaign_Email_Sender_Instance.json
  Packs/Campaign/Layouts/layoutscontainer-Phishing_Campaign.json
  Packs/Campaign/ReleaseNotes/3_2_5.md
  Packs/Campaign/Scripts/GetSendEmailInstances/GetSendEmailInstances.py
  Packs/Campaign/Scripts/GetSendEmailInstances/GetSendEmailInstances.yml
  Packs/Campaign/Scripts/GetSendEmailInstances/GetSendEmailInstances_test.py
  Packs/Campaign/Scripts/SendEmailToCampaignRecipients/SendEmailToCampaignRecipients.py
  Packs/Campaign/Scripts/SendEmailToCampaignRecipients/SendEmailToCampaignRecipients.yml
  Packs/Campaign/Scripts/SendEmailToCampaignRecipients/SendEmailToCampaignRecipients_test.py
  Packs/Campaign/pack_metadata.json
Labels: docs-approved

#16959 Log4j v10
  Packs/CVE_2021_44228/Playbooks/playbook-CVE-2021-44228_-_Log4j_RCE.yml
  Packs/CVE_2021_44228/Playbooks/playbook-CVE-2021-44228_-_Log4j_RCE_README.md
  Packs/CVE_2021_44228/ReleaseNotes/1_0_10.md
  Packs/CVE_2021_44228/pack_metadata.json
Labels: docs-approved

#16143 Extract URL
  Packs/Base/TestPlaybooks/playbook-Indicators-reputation-.json-Test.yml
  Packs/CommonScripts/.secrets-ignore
  Packs/CommonScripts/ReleaseNotes/1_6_22.md
  Packs/CommonScripts/Scripts/FormatURL/FormatURL.py
  Packs/CommonScripts/Scripts/FormatURL/FormatURL.yml
  Packs/CommonScripts/Scripts/FormatURL/FormatURL_test.py
  Packs/CommonScripts/Scripts/FormatURL/README.md
  Packs/CommonScripts/TestPlaybooks/FormatURL-Test.yml
  Packs/CommonScripts/pack_metadata.json
  Packs/CommonTypes/IndicatorTypes/reputation-url.json
  Packs/CommonTypes/ReleaseNotes/3_1_33.json
  Packs/CommonTypes/ReleaseNotes/3_1_33.md
  Packs/CommonTypes/pack_metadata.json
  Tests/conf.json
  Tests/known_words.txt
Labels: docs-approved

#16892 SNOW Change Request enhancements
  Packs/ServiceNow/Integrations/ServiceNowv2/ServiceNowv2.py
  Packs/ServiceNow/Integrations/ServiceNowv2/ServiceNowv2.yml
  Packs/ServiceNow/Integrations/ServiceNowv2/ServiceNowv2_test.py
  Packs/ServiceNow/Integrations/ServiceNowv2/test_data/create_co_from_template_result.json
  Packs/ServiceNow/Integrations/ServiceNowv2/test_data/created_ticket_context.py
  Packs/ServiceNow/Integrations/ServiceNowv2/test_data/get_tasks_for_co_command.json
  Packs/ServiceNow/ReleaseNotes/2_2_20.md
  Packs/ServiceNow/pack_metadata.json
Labels: docs-approved

#16899 STA - Update Product Display Name
  Packs/SafeNet_Trusted_Access/Integrations/SafeNetTrustedAccess/SafeNetTrustedAccess.yml
  Packs/SafeNet_Trusted_Access/ReleaseNotes/2_0_1.md
  Packs/SafeNet_Trusted_Access/pack_metadata.json
Labels: Contribution, docs-approved, Partner, Contribution Form Filled

#16934 remove packs from marketplace v2
  Packs/Campaign/pack_metadata.json
  Packs/CommonDashboards/pack_metadata.json
  Packs/CommonReports/pack_metadata.json
  Packs/CommonWidgets/pack_metadata.json
  Packs/CortexXDR/pack_metadata.json
  Packs/CrowdStrikeFalconStreamingV2/pack_metadata.json
  Packs/ElasticsearchMonitoring/pack_metadata.json
  Packs/EmployeeOffboarding/pack_metadata.json
  Packs/Expanse/pack_metadata.json
  Packs/ExpanseV2/pack_metadata.json
  Packs/IAM-SCIM/pack_metadata.json
  Packs/IntegrationsAndIncidentsHealthCheck/pack_metadata.json
  Packs/MultiTenantPerformance/pack_metadata.json
  Packs/ShiftManagement/pack_metadata.json
  Packs/TIM_Processing/pack_metadata.json
  Packs/TIM_SIEM/pack_metadata.json
  Packs/ThreatIntelReports/pack_metadata.json
  Packs/Traps/pack_metadata.json
Labels: docs-approved

#15906 panorama-security-policy-match test on entire panorama devices
  Packs/PAN-OS/Integrations/Panorama/Panorama.py
  Packs/PAN-OS/Integrations/Panorama/Panorama.yml
  Packs/PAN-OS/Integrations/Panorama/Panorama_test.py
  Packs/PAN-OS/Integrations/Panorama/test_data/devices_list.xml
  Packs/PAN-OS/ReleaseNotes/1_8_3.md
  Packs/PAN-OS/pack_metadata.json
Labels: docs-approved, release-notes-only

#16971 MarketplaceV2: pack_metadata completion
  Packs/AppendIfNotEmpty/pack_metadata.json
  Packs/Armorblox/pack_metadata.json
  Packs/ArrayToCSV/pack_metadata.json
  Packs/AzureDataExplorer/pack_metadata.json
  Packs/AzureDevOps/pack_metadata.json
  Packs/AzureRiskyUsers/pack_metadata.json
  Packs/AzureStorageContainer/pack_metadata.json
  Packs/AzureStorageFileShare/pack_metadata.json
  Packs/AzureStorageQueue/pack_metadata.json
  Packs/AzureStorageTable/pack_metadata.json
  Packs/CVE_2021_44228/pack_metadata.json
  Packs/ContentInstallation/pack_metadata.json
  Packs/CreateHash/pack_metadata.json
  Packs/DateTimeToADTime/pack_metadata.json
  Packs/DeduplicateValuesbyKey/pack_metadata.json
  Packs/DeprecatedContent/pack_metadata.json
  Packs/FeedSOCRadarThreatFeed/pack_metadata.json
  Packs/GetFields/pack_metadata.json
  Packs/Grafana/pack_metadata.json
  Packs/IsArrayItemInList/pack_metadata.json
  Packs/JoeSecurity/pack_metadata.json
  Packs/Lansweeper/pack_metadata.json
  Packs/MS-ISAC/pack_metadata.json
  Packs/OTSecurity/pack_metadata.json
  Packs/PHash/pack_metadata.json
  Packs/PerimeterX/pack_metadata.json
  Packs/PhishingAlerts/pack_metadata.json
  Packs/PhishingURL/pack_metadata.json
  Packs/PicusAutomation/pack_metadata.json
  Packs/RegexExpand/pack_metadata.json
  Packs/RemoteAccess/pack_metadata.json
  Packs/SocialEngineeringDomainAnalysis/pack_metadata.json
Labels: docs-approved

#16961 fix regex syntax
  Packs/Base/ReleaseNotes/1_18_2.md
  Packs/Base/Scripts/CommonServerPython/CommonServerPython.py
  Packs/Base/pack_metadata.json
Labels: docs-approved

#16956 AWS API Module get timeout fix
  Packs/AWS-ACM/ReleaseNotes/1_1_5.md
  Packs/AWS-ACM/pack_metadata.json
  Packs/AWS-CloudWatchLogs/ReleaseNotes/1_2_2.md
  Packs/AWS-CloudWatchLogs/pack_metadata.json
  Packs/AWS-EC2/ReleaseNotes/1_2_7.md
  Packs/AWS-EC2/pack_metadata.json
  Packs/AWS-GuardDuty/ReleaseNotes/1_2_2.md
  Packs/AWS-GuardDuty/pack_metadata.json
  Packs/AWS-IAM/ReleaseNotes/1_1_8.md
  Packs/AWS-IAM/pack_metadata.json
  Packs/AWS-Lambda/ReleaseNotes/1_2_6.md
  Packs/AWS-Lambda/pack_metadata.json
  Packs/AWS-S3/ReleaseNotes/1_1_3.md
  Packs/AWS-S3/pack_metadata.json
  Packs/AWS-SQS/ReleaseNotes/1_2_2.md
  Packs/AWS-SQS/pack_metadata.json
  Packs/AWS-SecurityHub/ReleaseNotes/1_1_6.md
  Packs/AWS-SecurityHub/pack_metadata.json
  Packs/ApiModules/Scripts/AWSApiModule/AWSApiModule.py
  Packs/ApiModules/Scripts/AWSApiModule/AWSApiModule_test.py
Labels: docs-approved, release-notes-only

#16359 Taxii2 server
  Packs/ApiModules/ReleaseNotes/2_2_7.md
  Packs/ApiModules/Scripts/NGINXApiModule/NGINXApiModule.py
  Packs/ApiModules/Scripts/NGINXApiModule/NGINXApiModule_test.py
  Packs/ApiModules/pack_metadata.json
  Packs/EDL/ReleaseNotes/2_1_7.md
  Packs/EDL/pack_metadata.json
  Packs/ExportIndicators/ReleaseNotes/1_0_14.md
  Packs/ExportIndicators/pack_metadata.json
  Packs/Hey/.pack-ignore
  Packs/Hey/ReleaseNotes/1_0_1.md
  Packs/Hey/Scripts/Hey/Hey.py
  Packs/Hey/Scripts/Hey/Hey.yml
  Packs/Hey/Scripts/Hey/Hey_test.py
  Packs/Hey/TestPlaybooks/TAXII2_Indicator_Performance_Test.yml
  Packs/Hey/TestPlaybooks/TAXII2_Performance_Test_-_Concurrency.yml
  Packs/Hey/TestPlaybooks/TAXII2_Server_Performance_Test.yml
  Packs/Hey/pack_metadata.json
  Packs/TAXIIServer/Integrations/TAXII2Server/README.md
  Packs/TAXIIServer/Integrations/TAXII2Server/TAXII2Server.py
  Packs/TAXIIServer/Integrations/TAXII2Server/TAXII2Server.yml
  Packs/TAXIIServer/Integrations/TAXII2Server/TAXII2Server_description.md
  Packs/TAXIIServer/Integrations/TAXII2Server/TAXII2Server_image.png
  Packs/TAXIIServer/Integrations/TAXII2Server/TAXII2Server_test.py
  Packs/TAXIIServer/Integrations/TAXII2Server/test_files/collections20.json
  Packs/TAXIIServer/Integrations/TAXII2Server/test_files/collections21.json
  Packs/TAXIIServer/Integrations/TAXII2Server/test_files/domain_iocs.json
  Packs/TAXIIServer/Integrations/TAXII2Server/test_files/file_iocs.json
  Packs/TAXIIServer/Integrations/TAXII2Server/test_files/ip_iocs.json
  Packs/TAXIIServer/Integrations/TAXII2Server/test_files/malware_iocs.json
  Packs/TAXIIServer/Integrations/TAXII2Server/test_files/manifest20.json
  Packs/TAXIIServer/Integrations/TAXII2Server/test_files/manifest21.json
  Packs/TAXIIServer/Integrations/TAXII2Server/test_files/objects20.json
  Packs/TAXIIServer/Integrations/TAXII2Server/test_files/objects21_domain.json
  Packs/TAXIIServer/Integrations/TAXII2Server/test_files/objects21_file.json
  Packs/TAXIIServer/Integrations/TAXII2Server/test_files/objects21_malware.json
  Packs/TAXIIServer/Integrations/TAXII2Server/test_files/objects21_no_extention_file.json
  Packs/TAXIIServer/Integrations/TAXII2Server/test_files/objects21_spec_fields_file.json
  Packs/TAXIIServer/ReleaseNotes/2_0_0.md
  Packs/TAXIIServer/doc_files/XSOAR_indicator_schema.json
  Packs/TAXIIServer/pack_metadata.json
  Tests/conf.json
Labels: docs-approved

#16968 runas DBotRole and add README.md
  Packs/PhishingURL/.pack-ignore
  Packs/PhishingURL/ReleaseNotes/1_0_1.md
  Packs/PhishingURL/Scripts/DBotPredictURLPhishing/DBotPredictURLPhishing.yml
  Packs/PhishingURL/Scripts/DBotPredictURLPhishing/README.md
  Packs/PhishingURL/pack_metadata.json
Labels: docs-approved

#16962 PAN-OS logs query Update README.md
  Packs/PAN-OS/Integrations/Panorama/README.md
Labels: docs-approved

#16584 Inventa development 1.0
  Packs/Inventa/.pack-ignore
  Packs/Inventa/.secrets-ignore
  Packs/Inventa/Author_image.png
  Packs/Inventa/IncidentFields/incidentfield-Inventa_Birthday.json
  Packs/Inventa/IncidentFields/incidentfield-Inventa_Credit_Card_Number.json
  Packs/Inventa/IncidentFields/incidentfield-Inventa_DSAR_DataAssets.json
  Packs/Inventa/IncidentFields/incidentfield-Inventa_DSAR_DataBases.json
  Packs/Inventa/IncidentFields/incidentfield-Inventa_DSAR_DataSubject_Email.json
  Packs/Inventa/IncidentFields/incidentfield-Inventa_DSAR_DataSubject_ID.json
  Packs/Inventa/IncidentFields/incidentfield-Inventa_DSAR_DataSubject_Name.json
  Packs/Inventa/IncidentFields/incidentfield-Inventa_DSAR_Files.json
  Packs/Inventa/IncidentFields/incidentfield-Inventa_DSAR_Inventa_Ticket.json
  Packs/Inventa/IncidentFields/incidentfield-Inventa_DSAR_PII_Entities.json
  Packs/Inventa/IncidentFields/incidentfield-Inventa_DSAR_Transactions.json
  Packs/Inventa/IncidentFields/incidentfield-Inventa_Driver_License.json
  Packs/Inventa/IncidentFields/incidentfield-Inventa_Full_Name.json
  Packs/Inventa/IncidentFields/incidentfield-Inventa_National_ID.json
  Packs/Inventa/IncidentFields/incidentfield-Inventa_PII_Entities.json
  Packs/Inventa/IncidentFields/incidentfield-Inventa_Passport_Number.json
  Packs/Inventa/IncidentFields/incidentfield-Inventa_Report_Reason.json
  Packs/Inventa/IncidentFields/incidentfield-Inventa_Tax_ID.json
  Packs/Inventa/IncidentFields/incidentfield-Inventa_Vehicle_Number.json
  Packs/Inventa/IncidentTypes/incidenttype-iDSAR.json
  Packs/Inventa/Integrations/Inventa/Inventa.py
  Packs/Inventa/Integrations/Inventa/Inventa.yml
  Packs/Inventa/Integrations/Inventa/Inventa_description.md
  Packs/Inventa/Integrations/Inventa/Inventa_image.png
  Packs/Inventa/Integrations/Inventa/Inventa_test.py
  Packs/Inventa/Integrations/Inventa/Pipfile
  Packs/Inventa/Integrations/Inventa/Pipfile.lock
  Packs/Inventa/Integrations/Inventa/README.md
  Packs/Inventa/Integrations/Inventa/command_examples
  Packs/Inventa/Integrations/Inventa/test_data/test_client.json
  Packs/Inventa/Integrations/Inventa/test_data/test_commands.json
  Packs/Inventa/Layouts/layoutscontainer-Inventa_DSAR_Layout.json
  Packs/Inventa/Playbooks/DSAR_Inventa_Handler.yml
  Packs/Inventa/Playbooks/DSAR_Inventa_Handler_README.md
  Packs/Inventa/README.md
  Packs/Inventa/pack_metadata.json
Labels: Contribution, docs-approved, Partner, Contribution Form Filled

#16911 Remove calculate_single_pack_dependency from content
  Tests/Marketplace/Tests/test_pack_dependencies.py
  Tests/Marketplace/packs_dependencies.py
  dev-requirements-py3.txt
Labels: docs-approved

#16860 Update GitHub Integration README
  Packs/GitHub/Integrations/GitHub/GitHub.yml
  Packs/GitHub/Integrations/GitHub/README.md
Labels: Contribution, docs-approved, Contribution Form Filled, Community

#16980 GitHub since parameter addition
  Packs/GitHub/Integrations/GitHub/GitHub.py
  Packs/GitHub/Integrations/GitHub/GitHub.yml
  Packs/GitHub/Integrations/GitHub/GitHub_test.py
  Packs/GitHub/Integrations/GitHub/README.md
  Packs/GitHub/ReleaseNotes/1_3_12.md
  Packs/GitHub/pack_metadata.json
Labels: docs-approved

#17015 Log analytics docs
  Packs/AzureLogAnalytics/Integrations/AzureLogAnalytics/README.md
Labels: docs-approved

#16997 SlackV3: Add Channel ID when Creating Channel
  Packs/Slack/Integrations/Slack/Slack.py
  Packs/Slack/Integrations/SlackV3/SlackV3.py
  Packs/Slack/ReleaseNotes/2_3_2.md
  Packs/Slack/pack_metadata.json
Labels: Contribution, docs-approved, Contribution Form Filled, Community

#16915 Copied the successful tests txt to the build's artifacts
  .gitlab/ci/on-push.yml
Labels: docs-approved

#17022 Added benchmarking to taxii2 server readme
  Packs/TAXIIServer/Integrations/TAXII2Server/README.md
Labels: docs-approved

#17023 Marketplacev2: Exclude Jobs playbooks from mpv2
  Packs/AnsibleTower/Playbooks/Ansible_Tower-_job_generic_pooling.yml
  Packs/CommonPlaybooks/Playbooks/playbook-Send_Investigation_Summary_Reports_Job.yml
  Packs/ContentManagement/Playbooks/playbook-Configuration_Setup.yml
  Packs/ContentManagement/Scripts/JobCreator/JobCreator.yml
  Packs/CortexXDR/Playbooks/playbook-JOB_-_Cortex_XDR_query_endpoint_device_control_violations.yml
  Packs/FortiSandbox/Playbooks/playbook-FortiSandbox_-_Loop_For_Job_Verdict.yml
  Packs/FortiSandbox/Playbooks/playbook-FortiSandbox_-_Loop_for_Job_Submissions.yml
  Packs/IntegrationsAndIncidentsHealthCheck/Playbooks/playbook-JOB_-_Integrations_and_Playbooks_Health_Check.yml
  Packs/IntegrationsAndIncidentsHealthCheck/Playbooks/playbook-JOB_-_Integrations_and_Playbooks_Health_Check_-_Lists_handling.yml
  Packs/ML/Playbooks/playbook-DBot_Create_Phishing_Classifier_V2_Job.yml
  Packs/PANOStoCDLMonitoring/Playbooks/PANOStoCDLMonitoring-cron_job.yml
  Packs/PopularCybersecurityNews/Playbooks/playbook-JOB_-_Popular_News.yml
  Packs/Rapid7_Nexpose/Playbooks/playbook-Vulnerability_Management_-_Nexpose_(Job).yml
  Packs/XSOAR-SimpleDevToProd/Playbooks/playbook-JOB_-_XSOAR_-_Export_Selected_Custom_Content.yml
  Packs/XSOAR-SimpleDevToProd/Playbooks/playbook-JOB_-_XSOAR_-_Simple_Dev_to_Prod.yml
  Packs/qualys/Playbooks/playbook-Vulnerability_Management_-_Qualys_(Job)_-_V2.yml
  Packs/qualys/Playbooks/playbook-Vulnerability_Management__-_Qualys_(Job).yml
Labels: docs-approved

#16981 Ignore conf json validation if the branch is one of the docker updates
  Tests/scripts/validate.sh
Labels: docs-approved

#16957 Enhance templateParams argument description
  Packs/EWS/Integrations/EWSO365/EWSO365.yml
  Packs/EWS/Integrations/EWSO365/README.md
  Packs/EWS/ReleaseNotes/1_11_2.md
  Packs/EWS/pack_metadata.json
  Packs/Gmail/Integrations/Gmail/Gmail.yml
  Packs/Gmail/Integrations/Gmail/README.md
  Packs/Gmail/ReleaseNotes/1_1_13.md
  Packs/Gmail/pack_metadata.json
  Packs/GmailSingleUser/Integrations/GmailSingleUser/GmailSingleUser.yml
  Packs/GmailSingleUser/Integrations/GmailSingleUser/README.md
  Packs/GmailSingleUser/ReleaseNotes/1_1_6.md
  Packs/GmailSingleUser/pack_metadata.json
  Packs/MailSenderNew/Integrations/MailSenderNew/MailSenderNew.yml
  Packs/MailSenderNew/Integrations/MailSenderNew/README.md
  Packs/MailSenderNew/ReleaseNotes/1_0_5.md
  Packs/MailSenderNew/pack_metadata.json
Labels: docs-approved

#16945 Update README.md
  Packs/PrismaSaasSecurity/Integrations/SaasSecurity/README.md
Labels: Contribution, docs-approved, Contribution Form Filled, Community

#16917 Phishing url prediction
  Packs/CommonPlaybooks/Playbooks/playbook-Extract_Indicators_From_File_-_Generic_v2_4_5.yml
  Packs/CommonPlaybooks/Playbooks/playbook-Extract_Indicators_From_File_-_Generic_v2_4_5_README.md
  Packs/CommonPlaybooks/ReleaseNotes/2_1_8.md
  Packs/CommonPlaybooks/TestPlaybooks/playbook-Extract_Indicators_From_File_-_Generic_v2_-_Test_4_5.yml
  Packs/CommonPlaybooks/TestPlaybooks/playbook-TestDomain.yml
  Packs/CommonPlaybooks/doc_files/Extract_Indicators_From_File_-_Generic_v2.png
  Packs/CommonPlaybooks/pack_metadata.json
  Packs/Phishing/Playbooks/Phishing_-_Generic_v3.yml
  Packs/Phishing/Playbooks/Phishing_-_Generic_v3_README.md
  Packs/Phishing/ReleaseNotes/3_0_3.md
  Packs/Phishing/doc_files/Phishing_-_Generic_v3.png
  Packs/Phishing/pack_metadata.json
Labels: docs-approved

#17045 Ot security read me fix
  Packs/OTSecurity/README.md
Labels: Contribution

#17049 update extract_common_server_js.py
  Documentation/extract_common_server_js.py
Labels: docs-approved

#17035 Unit42 fix error handling
  Packs/FeedUnit42v2/Integrations/FeedUnit42v2/FeedUnit42v2.py
  Packs/FeedUnit42v2/Integrations/FeedUnit42v2/FeedUnit42v2_test.py
  Packs/FeedUnit42v2/Integrations/FeedUnit42v2/Pipfile
  Packs/FeedUnit42v2/Integrations/FeedUnit42v2/Pipfile.lock
  Packs/FeedUnit42v2/Integrations/FeedUnit42v2/test_data/feed_data.py
  Packs/FeedUnit42v2/ReleaseNotes/1_0_8.md
  Packs/FeedUnit42v2/pack_metadata.json
  Tests/known_words.txt
Labels: docs-approved

#16979 Add query similar incident by indicators
  Packs/Base/ReleaseNotes/1_18_3.md
  Packs/Base/Scripts/DBotFindSimilarIncidents/DBotFindSimilarIncidents_test.py
  Packs/Base/Scripts/DBotFindSimilarIncidentsByIndicators/DBotFindSimilarIncidentsByIndicators.py
  Packs/Base/Scripts/DBotFindSimilarIncidentsByIndicators/DBotFindSimilarIncidentsByIndicators.yml
  Packs/Base/Scripts/DBotFindSimilarIncidentsByIndicators/DBotFindSimilarIncidentsByIndicators_test.py
  Packs/Base/pack_metadata.json
Labels: docs-approved

#17063 Update TPB and remove test from skipped
  Packs/PrismaCloud/TestPlaybooks/playbook-RedLockTest.yml
  Tests/conf.json
Labels: docs-approved

#17062 demisto-sdk release 1.5.7
  dev-requirements-py3.txt
Labels: docs-approved

#16484 Vmware
  Packs/VMware/.secrets-ignore
  Packs/VMware/Integrations/VMware/README.md
  Packs/VMware/Integrations/VMware/VMware.py
  Packs/VMware/Integrations/VMware/VMware.yml
  Packs/VMware/Integrations/VMware/VMware_test.py
  Packs/VMware/ReleaseNotes/1_2_0.md
  Packs/VMware/TestPlaybooks/playbook-VMWare_Test.yml
  Packs/VMware/pack_metadata.json
  Tests/conf.json
Labels: docs-approved

#16928 Tripwire fetch bug
  Packs/Tripwire/Integrations/Tripwire/Tripwire.py
  Packs/Tripwire/Integrations/Tripwire/Tripwire.yml
  Packs/Tripwire/Integrations/Tripwire/Tripwire_test.py
  Packs/Tripwire/ReleaseNotes/1_0_8.md
  Packs/Tripwire/pack_metadata.json
Labels: bug, docs-approved, release-notes-only

#17054 Add Read PDF file v2 script DBot role
  Packs/CommonScripts/ReleaseNotes/1_6_23.md
  Packs/CommonScripts/Scripts/ReadPDFFileV2/ReadPDFFileV2.yml
  Packs/CommonScripts/pack_metadata.json
Labels: docs-approved

#17082 ContentPackInstaller Bug Fix
  Packs/ContentInstallation/ReleaseNotes/1_0_1.md
  Packs/ContentInstallation/Scripts/ContentPackInstaller/ContentPackInstaller.py
  Packs/ContentInstallation/Scripts/ContentPackInstaller/ContentPackInstaller.yml
  Packs/ContentInstallation/pack_metadata.json
Labels: docs-approved, release-notes-only

#16989 Wiz pack 3
  Packs/Wiz/.pack-ignore
  Packs/Wiz/.secrets-ignore
  Packs/Wiz/Author_image.png
  Packs/Wiz/Classifiers/classifier-WizIssue.json
  Packs/Wiz/Classifiers/classifier-Wiz_Mapper.json
  Packs/Wiz/Classifiers/classifier-Wiz_Mapper_Webhook.json
  Packs/Wiz/IncidentFields/incidentfield-Wiz_Cloud_Account.json
  Packs/Wiz/IncidentFields/incidentfield-Wiz_Cloud_Account_Name.json
  Packs/Wiz/IncidentFields/incidentfield-Wiz_Cloud_Platform.json
  Packs/Wiz/IncidentFields/incidentfield-Wiz_Details.json
  Packs/Wiz/IncidentFields/incidentfield-Wiz_Issue_Due_Date.json
  Packs/Wiz/IncidentFields/incidentfield-Wiz_Issue_ID.json
  Packs/Wiz/IncidentFields/incidentfield-Wiz_Issue_Note.json
  Packs/Wiz/IncidentFields/incidentfield-Wiz_Resource_ID.json
  Packs/Wiz/IncidentFields/incidentfield-Wiz_Resource_Region.json
  Packs/Wiz/IncidentFields/incidentfield-Wiz_Resource_Type.json
  Packs/Wiz/IncidentTypes/incidenttype-WizIssue.json
  Packs/Wiz/Integrations/Wiz/Pipfile
  Packs/Wiz/Integrations/Wiz/Pipfile.lock
  Packs/Wiz/Integrations/Wiz/README.md
  Packs/Wiz/Integrations/Wiz/Wiz.py
  Packs/Wiz/Integrations/Wiz/Wiz.yml
  Packs/Wiz/Integrations/Wiz/Wiz_description.md
  Packs/Wiz/Integrations/Wiz/Wiz_image.png
  Packs/Wiz/Integrations/Wiz/Wiz_test.py
  Packs/Wiz/Integrations/command_examples.txt
  Packs/Wiz/Layouts/layoutscontainer-Wiz.json
  Packs/Wiz/README.md
  Packs/Wiz/pack_metadata.json
Labels: Contribution, Partner, Contribution Form Filled

#17086 Ignored dbutrunas error
  Packs/CommonScripts/.pack-ignore
Labels: docs-approved

#16987 Added fields parameter to get_list_with_query
  Packs/TOPdesk/Integrations/TOPdesk/README.md
  Packs/TOPdesk/Integrations/TOPdesk/TOPdesk.py
  Packs/TOPdesk/Integrations/TOPdesk/TOPdesk.yml
  Packs/TOPdesk/Integrations/TOPdesk/TOPdesk_test.py
  Packs/TOPdesk/ReleaseNotes/1_1_0.md
  Packs/TOPdesk/pack_metadata.json
Labels: Contribution, pending-demo, Contribution Form Filled, Community

#17084 Contrib/wiz sec wiz pack 3
  Packs/Wiz/.pack-ignore
  Packs/Wiz/.secrets-ignore
  Packs/Wiz/Author_image.png
  Packs/Wiz/Classifiers/classifier-WizIssue.json
  Packs/Wiz/Classifiers/classifier-Wiz_Mapper.json
  Packs/Wiz/Classifiers/classifier-Wiz_Mapper_Webhook.json
  Packs/Wiz/IncidentFields/incidentfield-Wiz_Cloud_Account.json
  Packs/Wiz/IncidentFields/incidentfield-Wiz_Cloud_Account_Name.json
  Packs/Wiz/IncidentFields/incidentfield-Wiz_Cloud_Platform.json
  Packs/Wiz/IncidentFields/incidentfield-Wiz_Details.json
  Packs/Wiz/IncidentFields/incidentfield-Wiz_Issue_Due_Date.json
  Packs/Wiz/IncidentFields/incidentfield-Wiz_Issue_ID.json
  Packs/Wiz/IncidentFields/incidentfield-Wiz_Issue_Note.json
  Packs/Wiz/IncidentFields/incidentfield-Wiz_Resource_ID.json
  Packs/Wiz/IncidentFields/incidentfield-Wiz_Resource_Region.json
  Packs/Wiz/IncidentFields/incidentfield-Wiz_Resource_Type.json
  Packs/Wiz/IncidentTypes/incidenttype-WizIssue.json
  Packs/Wiz/Integrations/Wiz/Pipfile
  Packs/Wiz/Integrations/Wiz/Pipfile.lock
  Packs/Wiz/Integrations/Wiz/README.md
  Packs/Wiz/Integrations/Wiz/Wiz.py
  Packs/Wiz/Integrations/Wiz/Wiz.yml
  Packs/Wiz/Integrations/Wiz/Wiz_description.md
  Packs/Wiz/Integrations/Wiz/Wiz_image.png
  Packs/Wiz/Integrations/Wiz/Wiz_test.py
  Packs/Wiz/Integrations/command_examples.txt
  Packs/Wiz/Layouts/layoutscontainer-Wiz.json
  Packs/Wiz/README.md
  Packs/Wiz/pack_metadata.json
Labels: docs-approved

#17072 Added AWS S3 support to Configuration Setup PB
  Packs/ContentManagement/IncidentFields/incidentfield-CustomPacksSource.json
  Packs/ContentManagement/Playbooks/playbook-Configuration_Setup.yml
  Packs/ContentManagement/ReleaseNotes/1_0_12.md
  Packs/ContentManagement/pack_metadata.json
Labels: docs-approved, release-notes-only

#16988 [QRadar v3] Add Resilience
  Packs/QRadar/Integrations/QRadar_v3/QRadar_v3.py
  Packs/QRadar/Integrations/QRadar_v3/QRadar_v3_test.py
  Packs/QRadar/Integrations/QRadar_v3/test_data/asset_enrich_test.json
  Packs/QRadar/ReleaseNotes/2_1_25.md
  Packs/QRadar/pack_metadata.json
Labels: docs-approved

#16990 Cohesity Update pack README and pack_metadata.json
  Packs/CohesityHelios/Integrations/CohesityHelios/CohesityHelios.yml
  Packs/CohesityHelios/README.md
  Packs/CohesityHelios/ReleaseNotes/1_0_2.md
  Packs/CohesityHelios/doc_files/protect_backup.png
  Packs/CohesityHelios/doc_files/reduce_downtime.png
  Packs/CohesityHelios/pack_metadata.json
Labels: Contribution, Partner, Contribution Form Filled

#15847 feat: Add VirusTotal Livehunt feed
  Packs/VirusTotal/.secrets-ignore
  Packs/VirusTotal/Integrations/FeedLivehunt/FeedLivehunt.py
  Packs/VirusTotal/Integrations/FeedLivehunt/FeedLivehunt.yml
  Packs/VirusTotal/Integrations/FeedLivehunt/FeedLivehunt_description.md
  Packs/VirusTotal/Integrations/FeedLivehunt/FeedLivehunt_image.png
  Packs/VirusTotal/Integrations/FeedLivehunt/FeedLivehunt_test.py
  Packs/VirusTotal/Integrations/FeedLivehunt/README.md
  Packs/VirusTotal/Integrations/FeedLivehunt/command_examples.txt
  Packs/VirusTotal/ReleaseNotes/2_2_0.md
  Packs/VirusTotal/pack_metadata.json
Labels: Contribution, docs-approved, Partner, Contribution Form Filled

#17104 typo in pack logo path in readme
  Packs/Wiz/README.md
Labels: Contribution, docs-approved, Partner, Contribution Form Filled

#16991 Added unit tests checking duplicated indicators to recorded future feed
  Packs/FeedRecordedFuture/.secrets-ignore
  Packs/FeedRecordedFuture/Integrations/FeedRecordedFuture/FeedRecordedFuture.py
  Packs/FeedRecordedFuture/Integrations/FeedRecordedFuture/FeedRecordedFuture_test.py
  Packs/FeedRecordedFuture/Integrations/FeedRecordedFuture/test_data/response_for_duplicate_indicator_test.txt
  Packs/FeedRecordedFuture/ReleaseNotes/1_0_19.md
  Packs/FeedRecordedFuture/pack_metadata.json
  Tests/known_words.txt
Labels: docs-approved, release-notes-only

#17029 Http csv feeds bug
  Packs/ApiModules/Scripts/CSVFeedApiModule/CSVFeedApiModule.py
  Packs/ApiModules/Scripts/CSVFeedApiModule/CSVFeedApiModule_test.py
  Packs/ApiModules/Scripts/HTTPFeedApiModule/HTTPFeedApiModule.py
  Packs/ApiModules/Scripts/HTTPFeedApiModule/HTTPFeedApiModule_test.py
  Packs/BitcoinAbuse/ReleaseNotes/1_0_17.md
  Packs/BitcoinAbuse/pack_metadata.json
  Packs/FeedAlienVault/ReleaseNotes/1_1_12.md
  Packs/FeedAlienVault/pack_metadata.json
  Packs/FeedBambenekConsulting/ReleaseNotes/1_1_12.md
  Packs/FeedBambenekConsulting/pack_metadata.json
  Packs/FeedBlocklist_de/ReleaseNotes/1_1_12.md
  Packs/FeedBlocklist_de/pack_metadata.json
  Packs/FeedBruteForceBlocker/ReleaseNotes/1_1_12.md
  Packs/FeedBruteForceBlocker/pack_metadata.json
  Packs/FeedCSV/ReleaseNotes/1_1_10.md
  Packs/FeedCSV/pack_metadata.json
  Packs/FeedCloudflare/ReleaseNotes/1_1_12.md
  Packs/FeedCloudflare/pack_metadata.json
  Packs/FeedDShield/ReleaseNotes/1_1_12.md
  Packs/FeedDShield/pack_metadata.json
  Packs/FeedFeodoTracker/ReleaseNotes/1_1_14.md
  Packs/FeedFeodoTracker/pack_metadata.json
  Packs/FeedMajesticMillion/ReleaseNotes/1_1_9.md
  Packs/FeedMajesticMillion/pack_metadata.json
  Packs/FeedMalwareDomainList/ReleaseNotes/1_1_7.md
  Packs/FeedMalwareDomainList/pack_metadata.json
  Packs/FeedPlainText/ReleaseNotes/1_1_10.md
  Packs/FeedPlainText/pack_metadata.json
  Packs/FeedSpamhaus/ReleaseNotes/1_1_12.md
  Packs/FeedSpamhaus/pack_metadata.json
  Packs/Feedsslabusech/ReleaseNotes/1_1_12.md
  Packs/Feedsslabusech/pack_metadata.json
  Tests/known_words.txt
  Utils/github_workflow_scripts/run_docs_review.py
Labels: docs-approved, release-notes-only

#16983 added rule to run-unittests-and-lint step to run when it is not upload
  .gitlab/ci/on-push.yml
Labels: docs-approved

#16963 send-mail added from arg
  Packs/EWS/Integrations/EWSO365/EWSO365.py
  Packs/EWS/Integrations/EWSO365/EWSO365.yml
  Packs/EWS/Integrations/EWSO365/README.md
  Packs/EWS/ReleaseNotes/1_11_3.md
  Packs/EWS/TestPlaybooks/playbook-EWS-Searchmailbox-Test.yml
  Packs/EWS/pack_metadata.json
  Packs/EWSMailSender/Integrations/EWSMailSender/EWSMailSender.py
  Packs/EWSMailSender/Integrations/EWSMailSender/EWSMailSender.yml
  Packs/EWSMailSender/Integrations/EWSMailSender/README.md
  Packs/EWSMailSender/ReleaseNotes/1_1_4.md
  Packs/EWSMailSender/pack_metadata.json
  Packs/MicrosoftGraphListener/Integrations/MicrosoftGraphListener/MicrosoftGraphListener.py
  Packs/MicrosoftGraphListener/Integrations/MicrosoftGraphListener/MicrosoftGraphListener.yml
  Packs/MicrosoftGraphListener/Integrations/MicrosoftGraphListener/README.md
  Packs/MicrosoftGraphListener/ReleaseNotes/1_0_22.md
  Packs/MicrosoftGraphListener/pack_metadata.json
Labels: docs-approved

#17114 Change integration display name
  Packs/Zscaler/Integrations/Zscaler/README.md
  Packs/Zscaler/Integrations/Zscaler/Zscaler.yml
  Packs/Zscaler/ReleaseNotes/1_1_16.md
  Packs/Zscaler/pack_metadata.json
Labels: docs-approved

#16869 SQS fetch_incidents will respect the fetch limit instead of pulling only up to 10
  Packs/AWS-SQS/Integrations/AWS-SQS/AWS-SQS.py
  Packs/AWS-SQS/Integrations/AWS-SQS/AWS-SQS.yml
  Packs/AWS-SQS/Integrations/AWS-SQS/README.md
  Packs/AWS-SQS/ReleaseNotes/1_2_2.md
  Packs/AWS-SQS/ReleaseNotes/1_2_3.md
  Packs/AWS-SQS/pack_metadata.json
Labels: Contribution, docs-approved, Contribution Form Filled, Community

#17121 mcafee-atd-add-version
  Packs/McAfee_Advanced_Threat_Defense/.secrets-ignore
  Packs/McAfee_Advanced_Threat_Defense/Integrations/McAfee_Advanced_Threat_Defense/README.md
Labels: docs-approved

#17043 URL fix Service now v2
  Packs/ServiceNow/Integrations/ServiceNowv2/ServiceNowv2.py
  Packs/ServiceNow/ReleaseNotes/2_2_22.md
  Packs/ServiceNow/pack_metadata.json
Labels: docs-approved

#16668 Selective pack's docker image download
  Utils/download_packs_and_docker_images.py
  Utils/tests/download_packs_and_docker_images_test.py
Labels: docs-approved

#17120 deprecate scripts
  Packs/RsaNetWitnessPacketsAndLogs/ReleaseNotes/1_0_4.md
  Packs/RsaNetWitnessPacketsAndLogs/Scripts/script-NetwitnessQuery.yml
  Packs/RsaNetWitnessPacketsAndLogs/Scripts/script-NetwitnessSearch.yml
  Packs/RsaNetWitnessPacketsAndLogs/pack_metadata.json
  Tests/known_words.txt
Labels: docs-approved

#16970 STA - Update Product Display Name (#16899)
  Packs/SafeNet_Trusted_Access/Integrations/SafeNetTrustedAccess/SafeNetTrustedAccess.yml
  Packs/SafeNet_Trusted_Access/ReleaseNotes/2_0_1.md
  Packs/SafeNet_Trusted_Access/pack_metadata.json
Labels: docs-approved

#17129 python 3.10 quick fix
  dev-requirements-py3.txt
Labels: docs-approved

#17141 Gmail - add required scopes per func to README
  Packs/Gmail/Integrations/Gmail/README.md
Labels: docs-approved

#17148 add python 3.10 support
  dev-requirements-py3.txt
Labels: docs-approved

#17126 AWS API Module - timeout not working with unicode class
  Packs/AWS-ACM/ReleaseNotes/1_1_6.md
  Packs/AWS-ACM/pack_metadata.json
  Packs/AWS-CloudWatchLogs/ReleaseNotes/1_2_3.md
  Packs/AWS-CloudWatchLogs/pack_metadata.json
  Packs/AWS-EC2/ReleaseNotes/1_2_8.md
  Packs/AWS-EC2/pack_metadata.json
  Packs/AWS-GuardDuty/ReleaseNotes/1_2_3.md
  Packs/AWS-GuardDuty/pack_metadata.json
  Packs/AWS-IAM/ReleaseNotes/1_1_9.md
  Packs/AWS-IAM/pack_metadata.json
  Packs/AWS-Lambda/ReleaseNotes/1_2_7.md
  Packs/AWS-Lambda/pack_metadata.json
  Packs/AWS-S3/ReleaseNotes/1_1_4.md
  Packs/AWS-S3/pack_metadata.json
  Packs/AWS-SQS/ReleaseNotes/1_2_4.md
  Packs/AWS-SQS/pack_metadata.json
  Packs/AWS-SecurityHub/ReleaseNotes/1_1_7.md
  Packs/AWS-SecurityHub/pack_metadata.json
  Packs/ApiModules/Scripts/AWSApiModule/AWSApiModule.py
  Packs/ApiModules/Scripts/AWSApiModule/AWSApiModule_test.py
  Tests/known_words.txt
Labels: docs-approved

#16177 Add the option to disable caching in SlackV3
  Packs/Slack/.secrets-ignore
  Packs/Slack/Integrations/SlackV3/README.md
  Packs/Slack/Integrations/SlackV3/SlackV3.py
  Packs/Slack/Integrations/SlackV3/SlackV3.yml
  Packs/Slack/Integrations/SlackV3/SlackV3_test.py
  Packs/Slack/ReleaseNotes/2_4_0.md
  Packs/Slack/TestPlaybooks/playbook-SlackV3_Test_NonCached.yml
  Packs/Slack/doc_files/SlackDocs_channel_id.png
  Packs/Slack/pack_metadata.json
  Tests/conf.json
Labels: docs-approved

#16483 Mandiant feed
  Packs/FeedMandiant/.pack-ignore
  Packs/FeedMandiant/.secrets-ignore
  Packs/FeedMandiant/IndicatorFields/indicatorfield-FeedMandiant_Detections.json
  Packs/FeedMandiant/IndicatorFields/indicatorfield-FeedMandiant_Report_Id.json
  Packs/FeedMandiant/IndicatorFields/indicatorfield-FeedMandiant_Version.json
  Packs/FeedMandiant/Integrations/FeedMandiant/FeedMandiant.py
  Packs/FeedMandiant/Integrations/FeedMandiant/FeedMandiant.yml
  Packs/FeedMandiant/Integrations/FeedMandiant/FeedMandiant_description.md
  Packs/FeedMandiant/Integrations/FeedMandiant/FeedMandiant_image.png
  Packs/FeedMandiant/Integrations/FeedMandiant/FeedMandiant_test.py
  Packs/FeedMandiant/Integrations/FeedMandiant/Pipfile
  Packs/FeedMandiant/Integrations/FeedMandiant/Pipfile.lock
  Packs/FeedMandiant/Integrations/FeedMandiant/README.md
  Packs/FeedMandiant/Integrations/FeedMandiant/command_examples
  Packs/FeedMandiant/Integrations/FeedMandiant/test_data/raw_indicators.json
  Packs/FeedMandiant/Integrations/FeedMandiant/test_data/result_indicators.json
  Packs/FeedMandiant/README.md
  Packs/FeedMandiant/pack_metadata.json
  Tests/conf.json
Labels: docs-approved

#17149 demisto-sdk release 1.5.8
  dev-requirements-py3.txt
Labels: docs-approved

#16776 shorten_string_for_printing
  Packs/Base/ReleaseNotes/1_18_4.md
  Packs/Base/Scripts/CommonServerPython/CommonServerPython.py
  Packs/Base/Scripts/CommonServerPython/CommonServerPython_test.py
  Packs/Base/pack_metadata.json
Labels: docs-approved

#17155 Fix error no urls
  Packs/PhishingURL/ReleaseNotes/1_0_2.md
  Packs/PhishingURL/Scripts/DBotPredictURLPhishing/DBotPredictURLPhishing.py
  Packs/PhishingURL/Scripts/DBotPredictURLPhishing/DBotPredictURLPhishing.yml
  Packs/PhishingURL/pack_metadata.json
Labels: docs-approved

#17162 Log4j v11
  Packs/CVE_2021_44228/Playbooks/playbook-CVE-2021-44228_-_Log4j_RCE.yml
  Packs/CVE_2021_44228/ReleaseNotes/1_0_11.md
  Packs/CVE_2021_44228/pack_metadata.json
Labels: docs-approved

#16251 Azure key vault integration fix microsft api module
  Packs/ApiModules/Scripts/MicrosoftApiModule/MicrosoftApiModule.py
  Packs/ApiModules/Scripts/MicrosoftApiModule/MicrosoftApiModule_test.py
  Packs/AzureKeyVault/.pack-ignore
  Packs/AzureKeyVault/.secrets-ignore
  Packs/AzureKeyVault/Integrations/AzureKeyVault/AzureKeyVault.py
  Packs/AzureKeyVault/Integrations/AzureKeyVault/AzureKeyVault.yml
  Packs/AzureKeyVault/Integrations/AzureKeyVault/AzureKeyVault_description.md
  Packs/AzureKeyVault/Integrations/AzureKeyVault/AzureKeyVault_image.png
  Packs/AzureKeyVault/Integrations/AzureKeyVault/AzureKeyVault_test.py
  Packs/AzureKeyVault/Integrations/AzureKeyVault/README.md
  Packs/AzureKeyVault/Integrations/AzureKeyVault/test_data/create_or_update_key_vault.json
  Packs/AzureKeyVault/Integrations/AzureKeyVault/test_data/delete_key.json
  Packs/AzureKeyVault/Integrations/AzureKeyVault/test_data/delete_key_vault.json
  Packs/AzureKeyVault/Integrations/AzureKeyVault/test_data/delete_secret.json
  Packs/AzureKeyVault/Integrations/AzureKeyVault/test_data/get_certificate.json
  Packs/AzureKeyVault/Integrations/AzureKeyVault/test_data/get_certificate_policy.json
  Packs/AzureKeyVault/Integrations/AzureKeyVault/test_data/get_key.json
  Packs/AzureKeyVault/Integrations/AzureKeyVault/test_data/get_key_vault.json
  Packs/AzureKeyVault/Integrations/AzureKeyVault/test_data/get_secret.json
  Packs/AzureKeyVault/Integrations/AzureKeyVault/test_data/get_secret_2.json
  Packs/AzureKeyVault/Integrations/AzureKeyVault/test_data/list_certificate.json
  Packs/AzureKeyVault/Integrations/AzureKeyVault/test_data/list_key_vaults.json
  Packs/AzureKeyVault/Integrations/AzureKeyVault/test_data/list_keys.json
  Packs/AzureKeyVault/Integrations/AzureKeyVault/test_data/list_secrets.json
  Packs/AzureKeyVault/Integrations/AzureKeyVault/test_data/update_access_policy.json
  Packs/AzureKeyVault/README.md
  Packs/AzureKeyVault/TestPlaybooks/playbook-AzureKeyVault-Test.yml
  Packs/AzureKeyVault/pack_metadata.json
  Tests/conf.json
Labels: Contribution

#16424 RSANW 11.5 integration
  Packs/CommonTypes/IncidentFields/incidentfield-First_Seen.json
  Packs/CommonTypes/IncidentFields/incidentfield-Last_Modified_By.json
  Packs/CommonTypes/IncidentFields/incidentfield-Last_Modified_On.json
  Packs/CommonTypes/IncidentFields/incidentfield-Risk_Score.json
  Packs/CommonTypes/IncidentFields/incidentfield-Source_Category.json
  Packs/CommonTypes/IncidentFields/incidentfield-Source_Created_By.json
  Packs/CommonTypes/ReleaseNotes/3_2_0.md
  Packs/CommonTypes/pack_metadata.json
  Packs/RSANetWitness_v11_1/.pack-ignore
  Packs/RSANetWitness_v11_1/.secrets-ignore
  Packs/RSANetWitness_v11_1/Classifiers/classifier-RSA_NetWitness_v11_5.json
  Packs/RSANetWitness_v11_1/IncidentFields/incidentfield-RSA_Alert_Count.json
  Packs/RSANetWitness_v11_1/IncidentFields/incidentfield-RSA_Event_Count.json
  Packs/RSANetWitness_v11_1/IncidentFields/incidentfield-RSA_Id.json
  Packs/RSANetWitness_v11_1/IncidentFields/incidentfield-RSA_Rule_Id.json
  Packs/RSANetWitness_v11_1/IncidentTypes/incidenttype-NetWitness_Incident.json
  Packs/RSANetWitness_v11_1/Integrations/RSANetWitnessv115/Pipfile
  Packs/RSANetWitness_v11_1/Integrations/RSANetWitnessv115/Pipfile.lock
  Packs/RSANetWitness_v11_1/Integrations/RSANetWitnessv115/README.md
  Packs/RSANetWitness_v11_1/Integrations/RSANetWitnessv115/RSANetWitnessv115.py
  Packs/RSANetWitness_v11_1/Integrations/RSANetWitnessv115/RSANetWitnessv115.yml
  Packs/RSANetWitness_v11_1/Integrations/RSANetWitnessv115/RSANetWitnessv115_description.md
  Packs/RSANetWitness_v11_1/Integrations/RSANetWitnessv115/RSANetWitnessv115_image.png
  Packs/RSANetWitness_v11_1/Integrations/RSANetWitnessv115/RSANetWitnessv115_test.py
  Packs/RSANetWitness_v11_1/Integrations/RSANetWitnessv115/test_data/command_results.json
  Packs/RSANetWitness_v11_1/Integrations/RSANetWitnessv115/test_data/create_filter_res.json
  Packs/RSANetWitness_v11_1/Integrations/RSANetWitnessv115/test_data/fetch_results.json
  Packs/RSANetWitness_v11_1/Integrations/RSANetWitnessv115/test_data/http_responses.json
  Packs/RSANetWitness_v11_1/Integrations/RSANetWitnessv115/test_data/paging_command_data.json
  Packs/RSANetWitness_v11_1/Integrations/RSANetWitnessv115/test_data/token_resp.json
  Packs/RSANetWitness_v11_1/Layouts/layoutscontainer-RSA_NetWitness_Layout.json
  Packs/RSANetWitness_v11_1/ReleaseNotes/2_0_0.md
  Packs/RSANetWitness_v11_1/TestPlaybooks/playbook-RSANetWitnessv115-Test.yml
  Packs/RSANetWitness_v11_1/pack_metadata.json
  Tests/conf.json
  Tests/known_words.txt
Labels: docs-approved

#17168 taxii 2 typo
  Packs/TAXIIServer/Integrations/TAXII2Server/README.md
Labels: docs-approved

#17128 Fixed an issue in SplunkPy where setting an empty string as the value of 'app' param caused an error
  Packs/SplunkPy/Integrations/SplunkPy/SplunkPy.py
  Packs/SplunkPy/Integrations/SplunkPy/SplunkPy_test.py
  Packs/SplunkPy/ReleaseNotes/2_3_1.md
  Packs/SplunkPy/pack_metadata.json
Labels: docs-approved

#16670 Add marketplace v2 upload flow
  .gitlab/ci/.gitlab-ci.yml
  .gitlab/ci/bucket-upload.yml
  .gitlab/ci/global.yml
  .gitlab/ci/on-push.yml
  Tests/Marketplace/Tests/marketplace_services_test.py
  Tests/Marketplace/Tests/marketplace_statistics_test.py
  Tests/Marketplace/core_packs_mpv2_list.json
  Tests/Marketplace/marketplace_constants.py
  Tests/Marketplace/marketplace_services.py
  Tests/Marketplace/upload_packs.py
  Tests/configure_and_test_integration_instances.py
  Tests/private_build/upload_packs_private.py
  Tests/scripts/prepare_content_packs_for_testing.sh
  Utils/gitlab_triggers/trigger_upload_flow_build.sh
  Utils/trigger_test_upload_flow.sh
Labels: docs-approved

#17159 fix GetIndicatorDBotScore IPv6 mapping bug
  Packs/CommonScripts/ReleaseNotes/1_6_24.md
  Packs/CommonScripts/Scripts/GetIndicatorDBotScore/GetIndicatorDBotScore.py
  Packs/CommonScripts/Scripts/GetIndicatorDBotScore/GetIndicatorDBotScore.yml
  Packs/CommonScripts/Scripts/GetIndicatorDBotScore/GetIndicatorDBotScore_test.py
  Packs/CommonScripts/pack_metadata.json
Labels: docs-approved

#17180 Fix for SlackV3 Operand Error on missing Bot ID
  Packs/Slack/Integrations/SlackV3/SlackV3.py
  Packs/Slack/ReleaseNotes/2_4_1.md
  Packs/Slack/pack_metadata.json
Labels: docs-approved

#17050 Fixes archer-search-records bug
  Packs/ArcherRSA/Integrations/ArcherV2/ArcherV2.py
  Packs/ArcherRSA/Integrations/ArcherV2/ArcherV2.yml
  Packs/ArcherRSA/Integrations/ArcherV2/ArcherV2_test.py
  Packs/ArcherRSA/Integrations/ArcherV2/README.md
  Packs/ArcherRSA/ReleaseNotes/1_1_32.md
  Packs/ArcherRSA/pack_metadata.json
Labels: docs-approved

#17178 UploadFlow: fix index path
  .gitlab/ci/bucket-upload.yml
  Tests/Marketplace/configure_and_install_packs.py
  Tests/Marketplace/copy_and_upload_packs.py
  Tests/Marketplace/marketplace_constants.py
  Tests/scripts/collect_tests_and_content_packs.py
Labels: docs-approved

#17107 CreateEDLInstance
  Packs/CreateEDLInstance/.pack-ignore
  Packs/CreateEDLInstance/.secrets-ignore
  Packs/CreateEDLInstance/README.md
  Packs/CreateEDLInstance/Scripts/CreateEDLInstance/CreateEDLInstance.py
  Packs/CreateEDLInstance/Scripts/CreateEDLInstance/CreateEDLInstance.yml
  Packs/CreateEDLInstance/Scripts/CreateEDLInstance/README.md
  Packs/CreateEDLInstance/pack_metadata.json
Labels: Contribution, docs-approved, Contribution Form Filled, Community

#17190 change pack support
  Packs/ThreatQ/pack_metadata.json
Labels: docs-approved

#17189 New RBR playbook - WhisperGate
  Packs/WhisperGateCVE-2021-32648/.pack-ignore
  Packs/WhisperGateCVE-2021-32648/.secrets-ignore
  Packs/WhisperGateCVE-2021-32648/Playbooks/playbook-WhisperGate_&_CVE-2021-32648.yml
  Packs/WhisperGateCVE-2021-32648/Playbooks/playbook-WhisperGate_&_CVE-2021-32648_README.md
  Packs/WhisperGateCVE-2021-32648/README.md
  Packs/WhisperGateCVE-2021-32648/doc_files/WhisperGate_&_CVE-2021-32648.png
  Packs/WhisperGateCVE-2021-32648/pack_metadata.json
Labels: docs-approved

#17123 ShowLocationOnMap script bug fix
  Packs/CommonScripts/ReleaseNotes/1_6_25.md
  Packs/CommonScripts/Scripts/ShowLocationOnMap/ShowLocationOnMap.py
  Packs/CommonScripts/Scripts/ShowLocationOnMap/ShowLocationOnMap.yml
  Packs/CommonScripts/Scripts/ShowLocationOnMap/ShowLocationOnMap_test.py
  Packs/CommonScripts/pack_metadata.json
Labels: docs-approved

#16769 adding extract email transformer
  Packs/FiltersAndTransformers/ReleaseNotes/1_0_1.md
  Packs/FiltersAndTransformers/Scripts/ExtractEmailTransformer/ExtractEmailTransformer.py
  Packs/FiltersAndTransformers/Scripts/ExtractEmailTransformer/ExtractEmailTransformer.yml
  Packs/FiltersAndTransformers/Scripts/ExtractEmailTransformer/ExtractEmailTransformer_test.py
  Packs/FiltersAndTransformers/pack_metadata.json
Labels: docs-approved

#17156 bluecat fixed readme
  Packs/BluecatAddressManager/Integrations/BluecatAddressManager/BluecatAddressManager_description.md
  Packs/BluecatAddressManager/Integrations/BluecatAddressManager/README.md
  Packs/BluecatAddressManager/ReleaseNotes/1_0_9.md
  Packs/BluecatAddressManager/pack_metadata.json
Labels: docs-approved

#17095 Phishing domainsquatting fix
  Packs/CommonPlaybooks/Playbooks/playbook-Email_Address_Enrichment_-_Generic_v2.1.yml
  Packs/CommonPlaybooks/ReleaseNotes/2_1_9.md
  Packs/CommonPlaybooks/pack_metadata.json
Labels: docs-approved, release-notes-only

#17146 Added support for manually creating a phishing incident
  Packs/Phishing/Layouts/layoutscontainer-Phishing_v_3.json
  Packs/Phishing/Playbooks/Phishing_-_Generic_v3.yml
  Packs/Phishing/ReleaseNotes/3_1_0.md
  Packs/Phishing/doc_files/Phishing_-_Generic_v3.png
  Packs/Phishing/pack_metadata.json
Labels: docs-approved

#17165 Fixed an issue where the values are appended regardless `append = false` when running in sub playbooks.
  Packs/CommonScripts/ReleaseNotes/1_6_26.md
  Packs/CommonScripts/Scripts/SetAndHandleEmpty/SetAndHandleEmpty.py
  Packs/CommonScripts/Scripts/SetAndHandleEmpty/SetAndHandleEmpty.yml
  Packs/CommonScripts/pack_metadata.json
Labels: Contribution, docs-approved, Contribution Form Filled, Community

#16944 Add Custom Fields arg to jira-issue-query command
  Packs/Jira/Integrations/JiraV2/JiraV2.py
  Packs/Jira/Integrations/JiraV2/JiraV2.yml
  Packs/Jira/Integrations/JiraV2/JiraV2_test.py
  Packs/Jira/Integrations/JiraV2/README.md
  Packs/Jira/Integrations/JiraV2/test_data/expected_results.py
  Packs/Jira/Integrations/JiraV2/test_data/raw_response.py
  Packs/Jira/ReleaseNotes/1_4_6.md
  Packs/Jira/TestPlaybooks/playbook-Jira-v2-Test.yml
  Packs/Jira/pack_metadata.json
Labels: Contribution, docs-approved, Contribution Form Filled, Community

#17214 XSOAR CI/CD Move to GA
  Packs/ContentManagement/pack_metadata.json
Labels: docs-approved

#17099 New Pack Accenture CTI Feed
  Packs/AccentureCTI_Feed/.pack-ignore
  Packs/AccentureCTI_Feed/.secrets-ignore
  Packs/AccentureCTI_Feed/Author_image.png
  Packs/AccentureCTI_Feed/Integrations/ACTIIndicatorFeed/ACTIIndicatorFeed.py
  Packs/AccentureCTI_Feed/Integrations/ACTIIndicatorFeed/ACTIIndicatorFeed.yml
  Packs/AccentureCTI_Feed/Integrations/ACTIIndicatorFeed/ACTIIndicatorFeed_description.md
  Packs/AccentureCTI_Feed/Integrations/ACTIIndicatorFeed/ACTIIndicatorFeed_image.png
  Packs/AccentureCTI_Feed/Integrations/ACTIIndicatorFeed/ACTIIndicatorFeed_test.py
  Packs/AccentureCTI_Feed/Integrations/ACTIIndicatorFeed/README.md
  Packs/AccentureCTI_Feed/README.md
  Packs/AccentureCTI_Feed/pack_metadata.json
Labels: Contribution, docs-approved, Partner, Contribution Form Filled

#17030 Update playbook api path
  Packs/RedCanary/Integrations/RedCanary/RedCanary.py
  Packs/RedCanary/ReleaseNotes/1_1_5.md
  Packs/RedCanary/pack_metadata.json
Labels: Contribution, docs-approved, Contribution Form Filled, Community

#17202 PAN-OS - remove from custom URL category not working
  Packs/PAN-OS/Integrations/Panorama/Panorama.py
  Packs/PAN-OS/Integrations/Panorama/Panorama.yml
  Packs/PAN-OS/Integrations/Panorama/Panorama_test.py
  Packs/PAN-OS/ReleaseNotes/1_8_4.md
  Packs/PAN-OS/pack_metadata.json
Labels: docs-approved

#17219 PAN OS - updated release notes after doc review
  Packs/PAN-OS/ReleaseNotes/1_8_4.md
Labels: docs-approved

#17130 Wrapper script panorama
  Packs/PAN-OS/ReleaseNotes/1_8_5.md
  Packs/PAN-OS/Scripts/PanoramaSecurityPolicyMatchWrapper/PanoramaSecurityPolicyMatchWrapper.py
  Packs/PAN-OS/Scripts/PanoramaSecurityPolicyMatchWrapper/PanoramaSecurityPolicyMatchWrapper.yml
  Packs/PAN-OS/Scripts/PanoramaSecurityPolicyMatchWrapper/PanoramaSecurityPolicyMatchWrapper_test.py
  Packs/PAN-OS/Scripts/PanoramaSecurityPolicyMatchWrapper/README.md
  Packs/PAN-OS/pack_metadata.json
Labels: docs-approved

#17197 Fix field mapping in Whois IP command
  Packs/Whois/Integrations/Whois/Whois.py
  Packs/Whois/Integrations/Whois/Whois_test.py
  Packs/Whois/ReleaseNotes/1_2_9.md
  Packs/Whois/TestPlaybooks/playbook-Whois-Test.yml
  Packs/Whois/pack_metadata.json
  Tests/known_words.txt
Labels: docs-approved

#17143 Added the map_labels param to Elasticsearch v2
  Packs/Elasticsearch/Integrations/Elasticsearch_v2/Elasticsearch_v2.py
  Packs/Elasticsearch/Integrations/Elasticsearch_v2/Elasticsearch_v2.yml
  Packs/Elasticsearch/Integrations/Elasticsearch_v2/Elasticsearch_v2_test.py
  Packs/Elasticsearch/ReleaseNotes/1_2_4.md
  Packs/Elasticsearch/pack_metadata.json
Labels: docs-approved

#17184 Fixed an issue where 'status' is referenced before assignment
  Packs/Palo_Alto_Networks_WildFire/Integrations/Palo_Alto_Networks_WildFire_v2/Palo_Alto_Networks_WildFire_v2.py
  Packs/Palo_Alto_Networks_WildFire/Integrations/Palo_Alto_Networks_WildFire_v2/Palo_Alto_Networks_WildFire_v2.yml
  Packs/Palo_Alto_Networks_WildFire/ReleaseNotes/2_0_6.md
  Packs/Palo_Alto_Networks_WildFire/pack_metadata.json
Labels: Contribution, docs-approved, Contribution Form Filled, Community
