Repository demisto/content, pull requests merged in 2022-09, with the labels that each got.

#20889 Update README auth details
  Packs/Jira/Integrations/JiraV2/README.md
Labels: Contribution, docs-approved, Contribution Form Filled, Community

#20884 TestCollect: change ignore order
  Tests/scripts/collect_tests/collect_tests.py
  Tests/scripts/collect_tests/test_conf.py
  Tests/scripts/infrastructure_tests/test_collect_tests.py
Labels: docs-approved

#20886 TestCollect: improve logs when `tests: no tests` is mentioned
  Tests/scripts/collect_tests/collect_tests.py
Labels: docs-approved

#20818 Update description aws securityhub
  Packs/AWS-SecurityHub/Integrations/AWS_SecurityHub/AWS_SecurityHub_description.md
  Packs/AWS-SecurityHub/Integrations/AWS_SecurityHub/README.md
  Packs/AWS-SecurityHub/ReleaseNotes/1_1_21.md
  Packs/AWS-SecurityHub/pack_metadata.json
Labels: docs-approved

#20736 Fix xdr close reason changed by mirror
  Packs/CortexXDR/Integrations/CortexXDRIR/CortexXDRIR.py
  Packs/CortexXDR/Integrations/CortexXDRIR/CortexXDRIR.yml
  Packs/CortexXDR/Integrations/CortexXDRIR/CortexXDRIR_test.py
  Packs/CortexXDR/ReleaseNotes/4_8_15.md
  Packs/CortexXDR/pack_metadata.json
Labels: docs-approved, release-notes-only

#20863 Add sha512 support as per customer's requirement
  Packs/CreateHash/ReleaseNotes/1_0_2.md
  Packs/CreateHash/Scripts/CreateHash/CreateHash.py
  Packs/CreateHash/Scripts/CreateHash/CreateHash.yml
  Packs/CreateHash/Scripts/CreateHash/README.md
  Packs/CreateHash/pack_metadata.json
Labels: Contribution, docs-approved, ready-for-instance-test, Contribution Form Filled, Community, pending-contributor

#20892 TestCollect: split git diff lines by `\t`
  Tests/scripts/collect_tests/collect_tests.py
Labels: docs-approved

#19799 XSOAR CI/CD - Add pull request automation feature
  Packs/ContentManagement/IncidentFields/incidentfield-Branch.json
  Packs/ContentManagement/IncidentFields/incidentfield-PackName.json
  Packs/ContentManagement/IncidentFields/incidentfield-PullRequestAttachment.json
  Packs/ContentManagement/IncidentFields/incidentfield-PullRequestBranch.json
  Packs/ContentManagement/IncidentFields/incidentfield-PullRequestComment.json
  Packs/ContentManagement/IncidentFields/incidentfield-PullRequestLink.json
  Packs/ContentManagement/IncidentFields/incidentfield-PullRequestReview.json
  Packs/ContentManagement/IncidentFields/incidentfield-PullRequestTitle.json
  Packs/ContentManagement/IncidentFields/incidentfield-Reviewer.json
  Packs/ContentManagement/IncidentTypes/incidenttype-Pull_Request_Creation.json
  Packs/ContentManagement/IncidentTypes/incidenttype-Pull_Request_Update.json
  Packs/ContentManagement/Layouts/layoutscontainer-Pull_Request_Creation.json
  Packs/ContentManagement/Layouts/layoutscontainer-Pull_Request_Update.json
  Packs/ContentManagement/Playbooks/playbook-Pull_Request_Creation_-_Generic.yml
  Packs/ContentManagement/Playbooks/playbook-Pull_Request_Creation_-_Generic_README.md
  Packs/ContentManagement/Playbooks/playbook-Pull_Request_Creation_-_Github.yml
  Packs/ContentManagement/Playbooks/playbook-Pull_Request_Creation_-_Github_README.md
  Packs/ContentManagement/ReleaseNotes/1_1_0.md
  Packs/ContentManagement/Scripts/CommitFiles/CommitFiles.py
  Packs/ContentManagement/Scripts/CommitFiles/CommitFiles.yml
  Packs/ContentManagement/Scripts/CommitFiles/README.md
  Packs/ContentManagement/Scripts/GetPrBranches/GetPrBranches.py
  Packs/ContentManagement/Scripts/GetPrBranches/GetPrBranches.yml
  Packs/ContentManagement/Scripts/GetPrBranches/README.md
  Packs/ContentManagement/Scripts/SuggestBranchName/README.md
  Packs/ContentManagement/Scripts/SuggestBranchName/SuggestBranchName.py
  Packs/ContentManagement/Scripts/SuggestBranchName/SuggestBranchName.yml
  Packs/ContentManagement/doc_files/ci-cd.yml
  Packs/ContentManagement/doc_files/layout.png
  Packs/ContentManagement/doc_files/playbook.png
  Packs/ContentManagement/doc_files/xsoar_config.json
  Packs/ContentManagement/pack_metadata.json
Labels: docs-approved

#20867 Fix bug CrowdStrike api module
  Packs/ApiModules/Scripts/CrowdStrikeApiModule/CrowdStrikeApiModule.py
  Packs/ApiModules/Scripts/CrowdStrikeApiModule/CrowdStrikeApiModule.yml
  Packs/CrowdStrikeIntel/ReleaseNotes/2_0_20.md
  Packs/CrowdStrikeIntel/pack_metadata.json
  Packs/CrowdStrikeOpenAPI/.pack-ignore
  Packs/CrowdStrikeOpenAPI/ReleaseNotes/1_0_9.md
  Packs/CrowdStrikeOpenAPI/pack_metadata.json
  Packs/FeedCrowdstrikeFalconIntel/ReleaseNotes/2_0_16.md
  Packs/FeedCrowdstrikeFalconIntel/pack_metadata.json
Labels: docs-approved

#20875 Remove coverege report link from forked prs
  .circleci/config.yml
Labels: docs-approved

#20880 fixed the bug, extracted the correct value
  Packs/Anomali_ThreatStream/Integrations/AnomaliThreatStreamv3/AnomaliThreatStreamv3.py
  Packs/Anomali_ThreatStream/Integrations/AnomaliThreatStreamv3/AnomaliThreatStreamv3.yml
  Packs/Anomali_ThreatStream/ReleaseNotes/2_0_15.md
  Packs/Anomali_ThreatStream/pack_metadata.json
Labels: docs-approved

#20759 Wiz 1.2.0 - multiple auth endpoints
  Packs/Wiz/Classifiers/classifier-Wiz_Mapper.json
  Packs/Wiz/Classifiers/classifier-Wiz_Mapper_Webhook.json
  Packs/Wiz/IncidentFields/incidentfield-Wiz_Issue_Resolution_Recommendation.json
  Packs/Wiz/Integrations/Wiz/README.md
  Packs/Wiz/Integrations/Wiz/Wiz.py
  Packs/Wiz/Integrations/Wiz/Wiz.yml
  Packs/Wiz/Integrations/Wiz/Wiz_description.md
  Packs/Wiz/Integrations/Wiz/Wiz_test.py
  Packs/Wiz/Integrations/command_examples.txt
  Packs/Wiz/Layouts/layoutscontainer-Wiz.json
  Packs/Wiz/ReleaseNotes/1_1_0.md
  Packs/Wiz/ReleaseNotes/1_2_0.md
  Packs/Wiz/pack_metadata.json
Labels: Contribution, docs-approved, Partner, Contribution Form Filled

#20869 TestCollect: run sanity on xsiam nightly
  Tests/scripts/collect_tests/collect_tests.py
  Tests/scripts/infrastructure_tests/test_collect_tests.py
  Tests/scripts/infrastructure_tests/tests_data/collect_tests/E/Packs/Whois/Sanity Test - Playbook with Unmockable Whois Integration.yml
  Tests/scripts/infrastructure_tests/tests_data/collect_tests/E/Packs/Whois/pack_metadata.json
  Tests/scripts/infrastructure_tests/tests_data/collect_tests/E/Packs/Whois/rationale
  Tests/scripts/infrastructure_tests/tests_data/collect_tests/E/Tests/conf.json
  Tests/scripts/infrastructure_tests/tests_data/collect_tests/E/Tests/id_set.json
  Tests/scripts/infrastructure_tests/tests_data/collect_tests/empty_xsiam/Packs/Whois/pack_metadata.json
  Tests/scripts/infrastructure_tests/tests_data/collect_tests/empty_xsiam/Packs/Whois/rationale
  Tests/scripts/infrastructure_tests/tests_data/collect_tests/empty_xsiam/Tests/conf.json
Labels: docs-approved

#20901 Armorblox sdk code changes
  Packs/Armorblox/.pack-ignore
  Packs/Armorblox/Classifiers/classifier-Armorblox_-_Classifier.json
  Packs/Armorblox/Integrations/Armorblox/Armorblox.py
  Packs/Armorblox/Integrations/Armorblox/Armorblox.yml
  Packs/Armorblox/Integrations/Armorblox/Armorblox_test.py
  Packs/Armorblox/Playbooks/Armorblox_Needs_Review.yml
  Packs/Armorblox/ReleaseNotes/1_0_4.md
  Packs/Armorblox/pack_metadata.json
Labels: Contribution

#20870 [VirusTotal] Deprecate outdated VirusTotal-Private_API
  Packs/VirusTotal-Private_API/Integrations/VirusTotal-Private_API/VirusTotal-Private_API.yml
  Packs/VirusTotal-Private_API/Playbooks/playbook-File_Enrichment_-_Virus_Total_Private_API.yml
  Packs/VirusTotal-Private_API/ReleaseNotes/1_0_16.md
  Packs/VirusTotal-Private_API/pack_metadata.json
Labels: Contribution, Partner, Contribution Form Filled

#20907 SlackV3 add debug severity log line
  Packs/Slack/Integrations/SlackV3/SlackV3.py
  Packs/Slack/Integrations/SlackV3/SlackV3.yml
  Packs/Slack/ReleaseNotes/3_1_1.md
  Packs/Slack/pack_metadata.json
Labels: docs-approved

#20872 [VirusTotal] Deprecate outdated VirusTotal V2 integration
  Packs/VirusTotal/Integrations/VirusTotal/VirusTotal.yml
  Packs/VirusTotal/ReleaseNotes/2_4_8.md
  Packs/VirusTotal/pack_metadata.json
Labels: Contribution, docs-approved, Partner, Contribution Form Filled

#20617 Added *multi_line*, *period_matches_newline* and *action_dt* parameters.
  Packs/RegexReplace/ReleaseNotes/1_0_2.md
  Packs/RegexReplace/Scripts/RegexReplace/README.md
  Packs/RegexReplace/Scripts/RegexReplace/RegexReplace.py
  Packs/RegexReplace/Scripts/RegexReplace/RegexReplace.yml
  Packs/RegexReplace/Scripts/RegexReplace/RegexReplace_test.py
  Packs/RegexReplace/Scripts/RegexReplace/test_data/test-1.json
  Packs/RegexReplace/pack_metadata.json
Labels: Contribution, docs-approved, Contribution Form Filled, Community, pending-contributor

#20331 Thehive bug
  Packs/TheHiveProject/Integrations/TheHiveProject/TheHiveProject.py
  Packs/TheHiveProject/Integrations/TheHiveProject/TheHiveProject.yml
  Packs/TheHiveProject/ReleaseNotes/1_1_14.md
  Packs/TheHiveProject/pack_metadata.json
  Tests/known_words.txt
Labels: docs-approved

#20841 "Organization" IP indicator field - Associate in Threat Intel packs
  Packs/Censys/Integrations/CensysV2/CensysV2.py
  Packs/Censys/Integrations/CensysV2/CensysV2.yml
  Packs/Censys/Integrations/CensysV2/README.md
  Packs/Censys/ReleaseNotes/2_0_11.md
  Packs/Censys/pack_metadata.json
  Packs/VirusTotal/Integrations/VirusTotal/command_examples
  Packs/VirusTotal/Integrations/VirusTotalV3/README.md
  Packs/VirusTotal/Integrations/VirusTotalV3/VirusTotalV3.py
  Packs/VirusTotal/Integrations/VirusTotalV3/VirusTotalV3.yml
  Packs/VirusTotal/ReleaseNotes/2_4_8.md
  Packs/VirusTotal/pack_metadata.json
  Packs/ipinfo/Integrations/ipinfo_v2/README.md
  Packs/ipinfo/Integrations/ipinfo_v2/ipinfo_v2.py
  Packs/ipinfo/Integrations/ipinfo_v2/ipinfo_v2.yml
  Packs/ipinfo/ReleaseNotes/2_1_4.md
  Packs/ipinfo/pack_metadata.json
Labels: docs-approved

#20406 Block indicators generic v3 playbook
  Packs/CiscoStealthwatch/.pack-ignore
  Packs/CiscoStealthwatch/Playbooks/playbook-block_domain-Cisco_Stealthwatch.yml
  Packs/CiscoStealthwatch/Playbooks/playbook-block_domain-Cisco_Stealthwatch_README.md
  Packs/CiscoStealthwatch/ReleaseNotes/1_0_6.md
  Packs/CiscoStealthwatch/doc_files/CiscoStealthwatch-Block-Domain-Playbook.png
  Packs/CiscoStealthwatch/pack_metadata.json
  Packs/CommonPlaybooks/.pack-ignore
  Packs/CommonPlaybooks/.secrets-ignore
  Packs/CommonPlaybooks/Playbooks/playbook-Block_Account_-_Generic_v2.yml
  Packs/CommonPlaybooks/Playbooks/playbook-Block_Account_-_Generic_v2_README.md
  Packs/CommonPlaybooks/Playbooks/playbook-Block_Domain_-_Generic_v2.yml
  Packs/CommonPlaybooks/Playbooks/playbook-Block_Domain_-_Generic_v2_README.md
  Packs/CommonPlaybooks/Playbooks/playbook-Block_Email_-_Generic_v2.yml
  Packs/CommonPlaybooks/Playbooks/playbook-Block_Email_-_Generic_v2_README.md
  Packs/CommonPlaybooks/Playbooks/playbook-Block_Indicators_-_Generic_v3.yml
  Packs/CommonPlaybooks/Playbooks/playbook-Block_Indicators_-_Generic_v3_README.md
  Packs/CommonPlaybooks/Playbooks/playbook-Block_URL_-_Generic_v2.yml
  Packs/CommonPlaybooks/Playbooks/playbook-Block_URL_-_Generic_v2_README.md
  Packs/CommonPlaybooks/ReleaseNotes/2_2_13.md
  Packs/CommonPlaybooks/ReleaseNotes/2_2_15.md
  Packs/CommonPlaybooks/doc_files/Block_Account_-_Generic_v2.png
  Packs/CommonPlaybooks/doc_files/Block_Domain_-_Generic_v2.png
  Packs/CommonPlaybooks/doc_files/Block_Email_-_Generic_v2.png
  Packs/CommonPlaybooks/doc_files/Block_Indicators_-_Generic_v3.png
  Packs/CommonPlaybooks/doc_files/Block_URL_-_Generic_v2.png
  Packs/CommonPlaybooks/pack_metadata.json
Labels: docs-approved

#20899 ignore non-xsoar-support packs in branch collections
  Tests/scripts/collect_tests/collect_tests.py
  Tests/scripts/collect_tests/exceptions.py
  Tests/scripts/collect_tests/utils.py
  Tests/scripts/infrastructure_tests/test_collect_tests.py
  Tests/scripts/infrastructure_tests/tests_data/collect_tests/M3/Packs/myXSOAROnlyPack/.pack_ignore
  Tests/scripts/infrastructure_tests/tests_data/collect_tests/M3/Packs/myXSOAROnlyPack/.secrets-ignore
  Tests/scripts/infrastructure_tests/tests_data/collect_tests/M3/Packs/myXSOAROnlyPack/Integrations/myIntegration/myIntegration.py
  Tests/scripts/infrastructure_tests/tests_data/collect_tests/M3/Packs/myXSOAROnlyPack/Integrations/myIntegration/myIntegration.yml
  Tests/scripts/infrastructure_tests/tests_data/collect_tests/M3/Packs/myXSOAROnlyPack/TestPlaybooks/myOtherTestPlaybook.yml
  Tests/scripts/infrastructure_tests/tests_data/collect_tests/M3/Packs/myXSOAROnlyPack/TestPlaybooks/myTestPlaybook.yml
  Tests/scripts/infrastructure_tests/tests_data/collect_tests/M3/Packs/myXSOAROnlyPack/pack_metadata.json
  Tests/scripts/infrastructure_tests/tests_data/collect_tests/M3/Tests/conf.json
  Tests/scripts/infrastructure_tests/tests_data/collect_tests/M3/Tests/id_set.json
Labels: docs-approved

#20912 Slack V3 Mirror Doc limitation
  Packs/Slack/Integrations/SlackV3/README.md
Labels: docs-approved

#20815 Pan os add device group to commands
  Packs/PAN-OS/Integrations/Panorama/Panorama.py
  Packs/PAN-OS/Integrations/Panorama/Panorama.yml
  Packs/PAN-OS/Integrations/Panorama/Panorama_test.py
  Packs/PAN-OS/Integrations/Panorama/README.md
  Packs/PAN-OS/Integrations/Panorama/test_data/get_security_profiles_response.json
  Packs/PAN-OS/ReleaseNotes/1_14_17.md
  Packs/PAN-OS/pack_metadata.json
Labels: docs-approved, ForceMerge

#20778 Phishing - new ML playbook, added usage of OOTB model, fixed an input bug
  Packs/Phishing/Playbooks/Phishing_-_Generic_v3.yml
  Packs/Phishing/Playbooks/Phishing_-_Generic_v3_README.md
  Packs/Phishing/Playbooks/Phishing_-_Machine_Learning_Analysis.yml
  Packs/Phishing/Playbooks/Phishing_-_Machine_Learning_Analysis_README.md
  Packs/Phishing/ReleaseNotes/3_3_2.md
  Packs/Phishing/doc_files/Phishing_-_Generic_v3.png
  Packs/Phishing/doc_files/Phishing_-_Machine_Learning_Analysis.png
  Packs/Phishing/pack_metadata.json
Labels: docs-approved

#20822 add spaces
  Packs/HelloWorld/ReleaseNotes/1_2_13.md
  Packs/StarterPack/Integrations/BaseIntegration/BaseIntegration_description.md
  Packs/StarterPack/ReleaseNotes/1_0_9.md
  Packs/StarterPack/pack_metadata.json
Labels: docs-approved

#20373 Run SDK End-End Tests
  .gitlab/ci/sdk-nightly.yml
Labels: docs-approved

#20776 Account enrichment generic 2.2
  Packs/CommonPlaybooks/Playbooks/playbook-Account_Enrichment_-_Generic_v2.1.yml
  Packs/CommonPlaybooks/Playbooks/playbook-Account_Enrichment_-_Generic_v2.2.yml
  Packs/CommonPlaybooks/Playbooks/playbook-Account_Enrichment_-_Generic_v2.2_README.md
  Packs/CommonPlaybooks/ReleaseNotes/2_3_0.md
  Packs/CommonPlaybooks/doc_files/Account_Enrichment_-_Generic_v2.2.png
  Packs/CommonPlaybooks/pack_metadata.json
Labels: docs-approved

#20928 [PAN-OS] Add Move Rule Functionality to Add Rule Commands
  Packs/PAN-OS/Integrations/Panorama/Panorama.py
  Packs/PAN-OS/ReleaseNotes/1_14_18.md
  Packs/PAN-OS/pack_metadata.json
Labels: docs-approved

#20932 Fix playbook tenable sc
  Packs/Tenable_sc/Playbooks/playbook-tenable.sc-scan.yml
  Packs/Tenable_sc/ReleaseNotes/1_0_7.md
  Packs/Tenable_sc/pack_metadata.json
Labels: docs-approved, release-notes-only

#20931 Adding note to readme in xsoar mirroring
  Packs/XSOARmirroring/Integrations/XSOARmirroring/README.md
Labels: docs-approved

#20919 always collect xsiam sanity test
  Tests/scripts/collect_tests/collect_tests.py
  Tests/scripts/infrastructure_tests/test_collect_tests.py
  Tests/scripts/infrastructure_tests/tests_data/collect_tests/A_xsiam/Packs/Whois/pack_metadata.json
  Tests/scripts/infrastructure_tests/tests_data/collect_tests/A_xsiam/Packs/Whois/rationale
  Tests/scripts/infrastructure_tests/tests_data/collect_tests/A_xsiam/Tests/conf.json
  Tests/scripts/infrastructure_tests/tests_data/collect_tests/B_xsiam/Packs/Whois/pack_metadata.json
  Tests/scripts/infrastructure_tests/tests_data/collect_tests/B_xsiam/Packs/Whois/rationale
  Tests/scripts/infrastructure_tests/tests_data/collect_tests/B_xsiam/Tests/conf.json
  Tests/scripts/infrastructure_tests/tests_data/collect_tests/C/Packs/Whois/pack_metadata.json
  Tests/scripts/infrastructure_tests/tests_data/collect_tests/C/Packs/Whois/rationale
  Tests/scripts/infrastructure_tests/tests_data/collect_tests/C/Tests/conf.json
Labels: docs-approved

#20923 create modeling rules
  Packs/CiscoASA/ModelingRules/CiscoASA/CiscoASA.xif
  Packs/CiscoASA/ModelingRules/CiscoASA/CiscoASA.yml
  Packs/CiscoASA/ModelingRules/CiscoASA/CiscoASA_schema.json
  Packs/CiscoASA/README.md
  Packs/CiscoASA/ReleaseNotes/1_0_22.md
  Packs/CiscoASA/pack_metadata.json
Labels: docs-approved

#20937 Removing myself as a code owner for common packs.
  .github/CODEOWNERS
Labels: docs-approved

#20927 Cisco umbrella investigate parameterized threshold
  Packs/Cisco-umbrella/Integrations/Cisco-umbrella-investigate/Cisco-umbrella-investigate.py
  Packs/Cisco-umbrella/Integrations/Cisco-umbrella-investigate/Cisco-umbrella-investigate.yml
  Packs/Cisco-umbrella/Integrations/Cisco-umbrella-investigate/Cisco-umbrella-investigate_test.py
  Packs/Cisco-umbrella/ReleaseNotes/1_0_13.md
  Packs/Cisco-umbrella/pack_metadata.json
Labels: docs-approved

#20950 2to3 awsiam
  Packs/AWS-IAM/Integrations/AWS-IAM/AWS-IAM.yml
  Packs/AWS-IAM/ReleaseNotes/1_1_11.md
  Packs/AWS-IAM/pack_metadata.json
Labels: docs-approved

#20882 removed timeout restriction for epo integration
  Packs/epo/Integrations/epoV2/epoV2.py
  Packs/epo/Integrations/epoV2/epoV2.yml
  Packs/epo/ReleaseNotes/2_0_10.md
  Packs/epo/pack_metadata.json
Labels: docs-approved

#20946 bump 2to3 getdockertag
  Packs/CommonScripts/ReleaseNotes/1_7_28.md
  Packs/CommonScripts/Scripts/GetDockerImageLatestTag/GetDockerImageLatestTag.py
  Packs/CommonScripts/Scripts/GetDockerImageLatestTag/GetDockerImageLatestTag.yml
  Packs/CommonScripts/pack_metadata.json
Labels: docs-approved

#20983 python2 EOL Tenable sc
  Packs/Tenable_sc/Integrations/Tenable_sc/Tenable_sc.yml
  Packs/Tenable_sc/ReleaseNotes/1_0_8.md
  Packs/Tenable_sc/pack_metadata.json
Labels: docs-approved

#20957 2to3 resilient
  Packs/IBMResilientSystems/Integrations/IBMResilientSystems/IBMResilientSystems.py
  Packs/IBMResilientSystems/Integrations/IBMResilientSystems/IBMResilientSystems.yml
  Packs/IBMResilientSystems/Integrations/IBMResilientSystems/IBMResilientSystems_test.py
  Packs/IBMResilientSystems/Integrations/IBMResilientSystems/Pipfile
  Packs/IBMResilientSystems/Integrations/IBMResilientSystems/Pipfile.lock
  Packs/IBMResilientSystems/ReleaseNotes/1_1_0.md
  Packs/IBMResilientSystems/pack_metadata.json
Labels: docs-approved

#20995 HighlightWords to py3
  Packs/Base/ReleaseNotes/1_31_19.md
  Packs/Base/Scripts/HighlightWords/HighlightWords.py
  Packs/Base/Scripts/HighlightWords/HighlightWords.yml
  Packs/Base/Scripts/HighlightWords/HighlightWords_test.py
  Packs/Base/Scripts/HighlightWords/README.md
  Packs/Base/Scripts/script-HighlightWords.yml
  Packs/Base/pack_metadata.json
Labels: ForceMerge

#20767 Hpe service manager linuxpakistan
  Packs/HPE_Service_Manager/Integrations/ServiceManager/README.md
  Packs/HPE_Service_Manager/Integrations/ServiceManager/ServiceManager.js
  Packs/HPE_Service_Manager/Integrations/ServiceManager/ServiceManager.yml
  Packs/HPE_Service_Manager/ReleaseNotes/1_0_5.md
  Packs/HPE_Service_Manager/pack_metadata.json
Labels: Contribution, docs-approved, Contribution Form Filled, Community

#20969 Python 2 EOL | Updated JiraCreateIssueExample
  Packs/Jira/.pack-ignore
  Packs/Jira/ReleaseNotes/2_0_11.md
  Packs/Jira/Scripts/JiraCreateIssueExample/JiraCreateIssueExample.py
  Packs/Jira/Scripts/JiraCreateIssueExample/JiraCreateIssueExample.yml
  Packs/Jira/Scripts/JiraCreateIssueExample/JiraCreateIssueExample_test.py
  Packs/Jira/Scripts/JiraCreateIssueExample/README.md
  Packs/Jira/pack_metadata.json
Labels: docs-approved

#21012 All common scripts 2to3
  Packs/CommonScripts/.secrets-ignore
  Packs/CommonScripts/ReleaseNotes/1_7_30.md
  Packs/CommonScripts/Scripts/DecodeMimeHeader/DecodeMimeHeader.py
  Packs/CommonScripts/Scripts/DecodeMimeHeader/DecodeMimeHeader.yml
  Packs/CommonScripts/Scripts/DecodeMimeHeader/DecodeMimeHeader_test.py
  Packs/CommonScripts/Scripts/DecodeMimeHeader/README.md
  Packs/CommonScripts/Scripts/DomainReputation/DomainReputation.py
  Packs/CommonScripts/Scripts/DomainReputation/DomainReputation.yml
  Packs/CommonScripts/Scripts/DomainReputation/DomainReputation_test.py
  Packs/CommonScripts/Scripts/DomainReputation/README.md
  Packs/CommonScripts/Scripts/IPReputation/IPReputation.py
  Packs/CommonScripts/Scripts/IPReputation/IPReputation.yml
  Packs/CommonScripts/Scripts/IPReputation/IPReputation_test.py
  Packs/CommonScripts/Scripts/IPReputation/README.md
  Packs/CommonScripts/Scripts/IsEmailAddressInternal/IsEmailAddressInternal.py
  Packs/CommonScripts/Scripts/IsEmailAddressInternal/IsEmailAddressInternal.yml
  Packs/CommonScripts/Scripts/IsEmailAddressInternal/IsEmailAddressInternal_test.py
  Packs/CommonScripts/Scripts/IsEmailAddressInternal/README.md
  Packs/CommonScripts/Scripts/IsIntegrationAvailable/IsIntegrationAvailable.py
  Packs/CommonScripts/Scripts/IsIntegrationAvailable/IsIntegrationAvailable.yml
  Packs/CommonScripts/Scripts/IsIntegrationAvailable/IsIntegrationAvailable_test.py
  Packs/CommonScripts/Scripts/IsIntegrationAvailable/README.md
  Packs/CommonScripts/Scripts/JoinIfSingleElementOnly/JoinIfSingleElementOnly.py
  Packs/CommonScripts/Scripts/JoinIfSingleElementOnly/JoinIfSingleElementOnly.yml
  Packs/CommonScripts/Scripts/JoinIfSingleElementOnly/JoinIfSingleElementOnly_test.py
  Packs/CommonScripts/Scripts/JoinIfSingleElementOnly/README.md
  Packs/CommonScripts/Scripts/MarkAsNoteByTag/MarkAsNoteByTag.py
  Packs/CommonScripts/Scripts/MarkAsNoteByTag/MarkAsNoteByTag.yml
  Packs/CommonScripts/Scripts/MarkAsNoteByTag/MarkAsNoteByTag_test.py
  Packs/CommonScripts/Scripts/MarkAsNoteByTag/README.md
  Packs/CommonScripts/Scripts/PDFUnlocker/PDFUnlocker.py
  Packs/CommonScripts/Scripts/PDFUnlocker/PDFUnlocker.yml
  Packs/CommonScripts/Scripts/PrintContext/PrintContext.py
  Packs/CommonScripts/Scripts/PrintContext/PrintContext.yml
  Packs/CommonScripts/Scripts/PrintContext/PrintContext_test.py
  Packs/CommonScripts/Scripts/PrintContext/README.md
  Packs/CommonScripts/Scripts/SetMultipleValues/README.md
  Packs/CommonScripts/Scripts/SetMultipleValues/SetMultipleValues.py
  Packs/CommonScripts/Scripts/SetMultipleValues/SetMultipleValues.yml
  Packs/CommonScripts/Scripts/SetMultipleValues/SetMultipleValues_test.py
  Packs/CommonScripts/Scripts/URLNumberOfAds/README.md
  Packs/CommonScripts/Scripts/URLNumberOfAds/URLNumberOfAds.py
  Packs/CommonScripts/Scripts/URLNumberOfAds/URLNumberOfAds.yml
  Packs/CommonScripts/Scripts/URLNumberOfAds/URLNumberOfAds_test.py
  Packs/CommonScripts/Scripts/URLReputation/README.md
  Packs/CommonScripts/Scripts/URLReputation/URLReputation.py
  Packs/CommonScripts/Scripts/URLReputation/URLReputation.yml
  Packs/CommonScripts/Scripts/URLReputation/URLReputation_test.py
  Packs/CommonScripts/Scripts/URLSSLVerification/URLSSLVerification.py
  Packs/CommonScripts/Scripts/URLSSLVerification/URLSSLVerification.yml
  Packs/CommonScripts/Scripts/URLSSLVerification/URLSSLVerification_test.py
  Packs/CommonScripts/Scripts/script-DecodeMimeHeader.yml
  Packs/CommonScripts/Scripts/script-IsEmailAddressInternal.yml
  Packs/CommonScripts/Scripts/script-MarkAsNoteByTag.yml
  Packs/CommonScripts/Scripts/script-PrintContext.yml
  Packs/CommonScripts/Scripts/script-URLNumberOfAds.yml
  Packs/CommonScripts/pack_metadata.json
Labels: docs-approved, ForceMerge

#21001 Grr scripts deprecate
  Packs/GRR/ReleaseNotes/1_0_7.md
  Packs/GRR/Scripts/GrrGetFiles/GrrGetFiles.yml
  Packs/GRR/Scripts/GrrGetFlows/GrrGetFlows.yml
  Packs/GRR/Scripts/GrrGetHunt/GrrGetHunt.yml
  Packs/GRR/Scripts/GrrGetHunts/GrrGetHunts.yml
  Packs/GRR/Scripts/GrrSetFlows/GrrSetFlows.yml
  Packs/GRR/Scripts/GrrSetHunts/GrrSetHunts.yml
  Packs/GRR/pack_metadata.json
Labels: docs-approved, release-notes-only

#20918 TestCollect: filter incompatible marketplaces
  Tests/scripts/collect_tests/collect_tests.py
  Tests/scripts/collect_tests/exceptions.py
  Tests/scripts/collect_tests/test_conf.py
  Tests/scripts/collect_tests/utils.py
  Tests/scripts/collect_tests/version_range.py
  Tests/scripts/infrastructure_tests/tests_data/collect_tests/E/Tests/id_set.json
  Tests/scripts/infrastructure_tests/tests_data/collect_tests/L_XSIAM/Packs/myXSIAMOnlyPack/Wizards/harry.json
  Tests/scripts/infrastructure_tests/tests_data/collect_tests/L_XSIAM/Packs/myXSIAMOnlyPack/pack_metadata.json
Labels: docs-approved

#20956 ParseWordDoc - Updated the script to support python3
  Packs/CommonScripts/ReleaseNotes/1_7_31.md
  Packs/CommonScripts/Scripts/ParseWordDoc/ParseWordDoc.yml
  Packs/CommonScripts/pack_metadata.json
Labels: docs-approved

#21003 Upgrade OSQueryBasicQuery to python3 and add test
  Packs/OSQuery/ReleaseNotes/1_0_5.md
  Packs/OSQuery/Scripts/OSQueryBasicQuery/OSQueryBasicQuery.py
  Packs/OSQuery/Scripts/OSQueryBasicQuery/OSQueryBasicQuery.yml
  Packs/OSQuery/Scripts/OSQueryBasicQuery/OSQueryBasicQuery_test.py
  Packs/OSQuery/Scripts/OSQueryBasicQuery/README.md
  Packs/OSQuery/Scripts/script-OSQueryBasicQuery.yml
  Packs/OSQuery/pack_metadata.json
Labels: docs-approved, ForceMerge

#20879 get-prevalence command context order
  Packs/Core/Integrations/CortexCoreIR/CortexCoreIR.py
  Packs/Core/Integrations/CortexCoreIR/CortexCoreIR.yml
  Packs/Core/Integrations/CortexCoreIR/CortexCoreIR_test.py
  Packs/Core/ReleaseNotes/1_3_8.md
  Packs/Core/pack_metadata.json
Labels: docs-approved

#21005 CBFindIP - update to python 3.10
  Packs/Carbon_Black_Enterprise_Response/ReleaseNotes/2_1_21.md
  Packs/Carbon_Black_Enterprise_Response/Scripts/CBFindIP/CBFindIP.py
  Packs/Carbon_Black_Enterprise_Response/Scripts/CBFindIP/CBFindIP.yml
  Packs/Carbon_Black_Enterprise_Response/Scripts/CBFindIP/README.md
  Packs/Carbon_Black_Enterprise_Response/pack_metadata.json
Labels: docs-approved

#20944 Jb fix getindicatordbot
  Packs/CommonScripts/.pack-ignore
  Packs/CommonScripts/ReleaseNotes/1_7_32.md
  Packs/CommonScripts/Scripts/GetIndicatorDBotScore/GetIndicatorDBotScore.py
  Packs/CommonScripts/Scripts/GetIndicatorDBotScore/GetIndicatorDBotScore.yml
  Packs/CommonScripts/pack_metadata.json
Labels: docs-approved

#20965 SlackV3 Fix for questions expiration
  Packs/Slack/Integrations/SlackV3/SlackV3.py
  Packs/Slack/ReleaseNotes/3_1_2.md
  Packs/Slack/pack_metadata.json
Labels: docs-approved

#20947 EC2 -> PY3
  Packs/AWS-EC2/Integrations/AWS-EC2/AWS-EC2.py
  Packs/AWS-EC2/Integrations/AWS-EC2/AWS-EC2.yml
  Packs/AWS-EC2/ReleaseNotes/1_2_16.md
  Packs/AWS-EC2/pack_metadata.json
Labels: docs-approved

#21013 Salesforce ask user python2 to python3
  Packs/Salesforce/ReleaseNotes/2_0_4.md
  Packs/Salesforce/Scripts/SalesforceAskUser/README.md
  Packs/Salesforce/Scripts/SalesforceAskUser/SalesforceAskUser.py
  Packs/Salesforce/Scripts/SalesforceAskUser/SalesforceAskUser.yml
  Packs/Salesforce/Scripts/SalesforceAskUser/SalesforceAskUser_test.py
  Packs/Salesforce/Scripts/script-SalesforceAskUser.yml
  Packs/Salesforce/pack_metadata.json
Labels: docs-approved, ForceMerge

#20055 mapper,beta deprication, and proxy removed
  Packs/MailListener_-_POP3/Classifiers/classifier-Mail_Listener_-_POP3_-_Incoming_Mapper.json
  Packs/MailListener_-_POP3/Integrations/MailListener_POP3/MailListener_POP3.py
  Packs/MailListener_-_POP3/Integrations/MailListener_POP3/MailListener_POP3.yml
  Packs/MailListener_-_POP3/Integrations/MailListener_POP3/MailListener_POP3_description.md
  Packs/MailListener_-_POP3/Integrations/MailListener_POP3/MailListener_POP3_test.py
  Packs/MailListener_-_POP3/Integrations/MailListener_POP3/README.md
  Packs/MailListener_-_POP3/ReleaseNotes/2_0_0.md
  Packs/MailListener_-_POP3/pack_metadata.json
Labels: docs-approved, ForceMerge

#21021 Awake security python3
  Packs/AwakeSecurity/Integrations/AwakeSecurity/AwakeSecurity.py
  Packs/AwakeSecurity/Integrations/AwakeSecurity/AwakeSecurity.yml
  Packs/AwakeSecurity/ReleaseNotes/1_0_12.md
  Packs/AwakeSecurity/pack_metadata.json
Labels: docs-approved

#21022 Ews Mail sender: subtype py3
  Packs/EWSMailSender/Integrations/EWSMailSender/EWSMailSender.yml
  Packs/EWSMailSender/ReleaseNotes/1_1_13.md
  Packs/EWSMailSender/pack_metadata.json
Labels: docs-approved

#21040 FortiGate --> PY3
  Packs/FortiGate/Integrations/FortiGate/FortiGate.py
  Packs/FortiGate/Integrations/FortiGate/FortiGate.yml
  Packs/FortiGate/ReleaseNotes/1_0_11.md
  Packs/FortiGate/pack_metadata.json
Labels: docs-approved

#21057 Signal Sciences WAF --> PY3
  Packs/SignalSciences/.pack-ignore
  Packs/SignalSciences/Integrations/SignalSciences/SignalSciences.py
  Packs/SignalSciences/Integrations/SignalSciences/SignalSciences.yml
  Packs/SignalSciences/ReleaseNotes/1_0_10.md
  Packs/SignalSciences/pack_metadata.json
Labels: docs-approved

#21036 AWS - CloudWatchLogs --> PY3
  Packs/AWS-CloudWatchLogs/Integrations/AWS-CloudWatchLogs/AWS-CloudWatchLogs.yml
  Packs/AWS-CloudWatchLogs/ReleaseNotes/1_2_5.md
  Packs/AWS-CloudWatchLogs/pack_metadata.json
Labels: docs-approved

#20854 BlueCat Manager - support v9.2.0
  Packs/BluecatAddressManager/Integrations/BluecatAddressManager/BluecatAddressManager.py
  Packs/BluecatAddressManager/Integrations/BluecatAddressManager/BluecatAddressManager.yml
  Packs/BluecatAddressManager/Integrations/BluecatAddressManager/BluecatAddressManager_description.md
  Packs/BluecatAddressManager/Integrations/BluecatAddressManager/README.md
  Packs/BluecatAddressManager/ReleaseNotes/1_1_0.md
  Packs/BluecatAddressManager/pack_metadata.json
Labels: docs-approved

#20936 For release SDK 1.7.4
  .circleci/config.yml
  .gitlab/ci/.gitlab-ci.yml
  .gitlab/ci/global.yml
  poetry.lock
  pyproject.toml
Labels: docs-approved

#21060 BigFix --> PY3
  Packs/BigFix/Integrations/BigFix/BigFix.py
  Packs/BigFix/Integrations/BigFix/BigFix.yml
  Packs/BigFix/ReleaseNotes/1_0_9.md
  Packs/BigFix/pack_metadata.json
Labels: docs-approved

#21016 Test coverage report less then 70
  .circleci/config.yml
Labels: docs-approved

#21037 Common Scripts 2to3
  Packs/CommonScripts/ReleaseNotes/1_7_33.md
  Packs/CommonScripts/Scripts/FindSimilarIncidentsV2/FindSimilarIncidentsV2.py
  Packs/CommonScripts/Scripts/FindSimilarIncidentsV2/FindSimilarIncidentsV2.yml
  Packs/CommonScripts/Scripts/ParseCSV/ParseCSV.py
  Packs/CommonScripts/Scripts/ParseCSV/ParseCSV.yml
  Packs/CommonScripts/Scripts/ParseCSV/ParseCSV_test.py
  Packs/CommonScripts/pack_metadata.json
Labels: docs-approved

#20987 GCP Compute - py3
  Packs/GoogleCloudCompute/Integrations/GoogleCloudCompute/GoogleCloudCompute.py
  Packs/GoogleCloudCompute/Integrations/GoogleCloudCompute/GoogleCloudCompute.yml
  Packs/GoogleCloudCompute/ReleaseNotes/1_0_4.md
  Packs/GoogleCloudCompute/TestPlaybooks/playbook-GoogleCloudComputeList_Test.yml
  Packs/GoogleCloudCompute/TestPlaybooks/playbook-GoogleCloudcompute_test.yml
  Packs/GoogleCloudCompute/pack_metadata.json
  Tests/conf.json
Labels: docs-approved

#20992 Fire eye etp python3
  Packs/FireEyeETP/.pack-ignore
  Packs/FireEyeETP/Integrations/FireEyeETP/FireEyeETP.py
  Packs/FireEyeETP/Integrations/FireEyeETP/FireEyeETP.yml
  Packs/FireEyeETP/ReleaseNotes/1_0_9.md
  Packs/FireEyeETP/pack_metadata.json
Labels: docs-approved

#21079 remedy_SR - python 2 to 3
  Packs/remedy_SR/Integrations/remedy_SR/remedy_SR.py
  Packs/remedy_SR/Integrations/remedy_SR/remedy_SR.yml
  Packs/remedy_SR/Integrations/remedy_SR/remedy_SR_test.py
  Packs/remedy_SR/ReleaseNotes/1_0_8.md
  Packs/remedy_SR/pack_metadata.json
Labels: docs-approved

#20968 [PassiveTotal v2] Fix ip Command Handling of Lists
  Packs/PassiveTotal/Integrations/PassiveTotal_v2/PassiveTotal_v2.py
  Packs/PassiveTotal/Integrations/PassiveTotal_v2/PassiveTotal_v2.yml
  Packs/PassiveTotal/ReleaseNotes/2_1_3.md
  Packs/PassiveTotal/pack_metadata.json
Labels: docs-approved

#21074 TestCollect: collect packs containing TPBs
  Tests/scripts/collect_tests/collect_tests.py
  Tests/scripts/infrastructure_tests/test_collect_tests.py
  Tests/scripts/infrastructure_tests/tests_data/collect_tests/A_xsiam/Packs/Whois/TestPlaybooks/Sanity Test - Playbook with Unmockable Whois Integration.yml
  Tests/scripts/infrastructure_tests/tests_data/collect_tests/A_xsiam/Tests/id_set.json
  Tests/scripts/infrastructure_tests/tests_data/collect_tests/B_xsiam/Packs/Whois/TestPlaybooks/Sanity Test - Playbook with Unmockable Whois Integration.yml
  Tests/scripts/infrastructure_tests/tests_data/collect_tests/B_xsiam/Tests/id_set.json
  Tests/scripts/infrastructure_tests/tests_data/collect_tests/C/Packs/Whois/TestPlaybooks/Sanity Test - Playbook with Unmockable Whois Integration.yml
  Tests/scripts/infrastructure_tests/tests_data/collect_tests/C/Tests/id_set.json
  Tests/scripts/infrastructure_tests/tests_data/collect_tests/empty/Packs/Whois/TestPlaybooks/Sanity Test - Playbook with Unmockable Whois Integration.yml
  Tests/scripts/infrastructure_tests/tests_data/collect_tests/empty/Packs/Whois/TestPlaybooks/Sanity Test - Playbook with integration.yml
  Tests/scripts/infrastructure_tests/tests_data/collect_tests/empty/Packs/Whois/TestPlaybooks/Sanity Test - Playbook with mocked integration.yml
  Tests/scripts/infrastructure_tests/tests_data/collect_tests/empty/Packs/Whois/TestPlaybooks/Sanity Test - Playbook with no integration.yml
  Tests/scripts/infrastructure_tests/tests_data/collect_tests/empty/Tests/id_set.json
Labels: docs-approved

#21072 changed to python3
  Packs/D2/ReleaseNotes/1_0_6.md
  Packs/D2/Scripts/RegPathReputationBasicLists/RegPathReputationBasicLists.py
  Packs/D2/Scripts/RegPathReputationBasicLists/RegPathReputationBasicLists.yml
  Packs/D2/Scripts/RegPathReputationBasicLists/RegPathReputationBasicLists_test.py
  Packs/D2/pack_metadata.json
Labels: docs-approved

#21061 Move carbon black protect scripts to py3
  Packs/CarbonBlackProtect/ReleaseNotes/1_0_28.md
  Packs/CarbonBlackProtect/Scripts/CBPApproveHash/CBPApproveHash.yml
  Packs/CarbonBlackProtect/Scripts/CBPBanHash/CBPBanHash.yml
  Packs/CarbonBlackProtect/Scripts/CBPCatalogFindHash/CBPCatalogFindHash.py
  Packs/CarbonBlackProtect/Scripts/CBPCatalogFindHash/CBPCatalogFindHash.yml
  Packs/CarbonBlackProtect/Scripts/CBPCatalogFindHash/CBPCatalogFindHash_test.py
  Packs/CarbonBlackProtect/Scripts/CBPCatalogFindHash/README.md
  Packs/CarbonBlackProtect/Scripts/CBPFindComputer/CBPFindComputer.py
  Packs/CarbonBlackProtect/Scripts/CBPFindComputer/CBPFindComputer.yml
  Packs/CarbonBlackProtect/Scripts/CBPFindComputer/CBPFindComputer_test.py
  Packs/CarbonBlackProtect/Scripts/CBPFindComputer/README.md
  Packs/CarbonBlackProtect/Scripts/CBPFindRule/CBPFindRule.py
  Packs/CarbonBlackProtect/Scripts/CBPFindRule/CBPFindRule.yml
  Packs/CarbonBlackProtect/Scripts/CBPFindRule/CBPFindRule_test.py
  Packs/CarbonBlackProtect/Scripts/CBPFindRule/README.md
  Packs/CarbonBlackProtect/Scripts/script-CBPCatalogFindHash.yml
  Packs/CarbonBlackProtect/Scripts/script-CBPFindComputer.yml
  Packs/CarbonBlackProtect/Scripts/script-CBPFindRule.yml
  Packs/CarbonBlackProtect/pack_metadata.json
Labels: docs-approved

#20991 Deprecate ProtectWise scripts
  Packs/ProtectWise/.pack-ignore
  Packs/ProtectWise/ReleaseNotes/1_0_6.md
  Packs/ProtectWise/Scripts/PWEventPcapDownload/PWEventPcapDownload.yml
  Packs/ProtectWise/Scripts/PWObservationPcapDownload/PWObservationPcapDownload.yml
  Packs/ProtectWise/pack_metadata.json
Labels: docs-approved

#21071 TestCollect: ignore `test_data` etc
  Tests/scripts/collect_tests/collect_tests.py
  Tests/scripts/infrastructure_tests/test_collect_tests.py
  Tests/scripts/infrastructure_tests/tests_data/collect_tests/J/Packs/myPack/Integrations/myIntegration/test_data/file.json
Labels: docs-approved

#20124 OpenLDAP - Adding support for Active Directory Auth with Start TLS
  Packs/OpenLDAP/.pack-ignore
  Packs/OpenLDAP/.secrets-ignore
  Packs/OpenLDAP/Integrations/OpenLDAP/OpenLDAP.py
  Packs/OpenLDAP/Integrations/OpenLDAP/OpenLDAP.yml
  Packs/OpenLDAP/Integrations/OpenLDAP/OpenLDAP_image.png
  Packs/OpenLDAP/Integrations/OpenLDAP/OpenLDAP_test.py
  Packs/OpenLDAP/Integrations/OpenLDAP/README.md
  Packs/OpenLDAP/ReleaseNotes/2_0_0.md
  Packs/OpenLDAP/TestPlaybooks/LDAP_Authentication_Test.yml
  Packs/OpenLDAP/pack_metadata.json
  Tests/conf.json
Labels: docs-approved, ForceMerge

#21091 utf 8 encoding fix
  Packs/MailListener_-_POP3/Integrations/MailListener_POP3/MailListener_POP3_test.py
Labels: docs-approved

#20859 Prisma Access SSH Malformed JSON fix
  Packs/PrismaAccess/Integrations/PrismaAccess/PrismaAccess.py
  Packs/PrismaAccess/Integrations/PrismaAccess/PrismaAccess.yml
  Packs/PrismaAccess/ReleaseNotes/1_0_11.md
  Packs/PrismaAccess/pack_metadata.json
Labels: docs-approved

#20929 Servicenow bug fix
  Packs/ServiceNow/Integrations/ServiceNowv2/ServiceNowv2.py
  Packs/ServiceNow/ReleaseNotes/2_3_22.md
  Packs/ServiceNow/TestPlaybooks/playbook-ServiceNow_Test_New.yml
  Packs/ServiceNow/pack_metadata.json
Labels: docs-approved, release-notes-only, ForceMerge

#21010 Convert InfoArmorVigilanteATI integration to python3
  Packs/InfoArmor_VigilanteATI/.pack-ignore
  Packs/InfoArmor_VigilanteATI/Integrations/InfoArmorVigilanteATI/InfoArmorVigilanteATI.py
  Packs/InfoArmor_VigilanteATI/Integrations/InfoArmorVigilanteATI/InfoArmorVigilanteATI.yml
  Packs/InfoArmor_VigilanteATI/Integrations/InfoArmorVigilanteATI/InfoArmorVigilanteATI_description.md
  Packs/InfoArmor_VigilanteATI/Integrations/InfoArmorVigilanteATI/InfoArmorVigilanteATI_image.png
  Packs/InfoArmor_VigilanteATI/Integrations/InfoArmorVigilanteATI/InfoArmorVigilanteATI_test.py
  Packs/InfoArmor_VigilanteATI/Integrations/InfoArmorVigilanteATI/README.md
  Packs/InfoArmor_VigilanteATI/Integrations/integration-InfoArmor_VigilanteATI.yml
  Packs/InfoArmor_VigilanteATI/ReleaseNotes/1_0_6.md
  Packs/InfoArmor_VigilanteATI/pack_metadata.json
Labels: docs-approved, ForceMerge

#21070 Aws sage maker python3
  Packs/AWS_Sagemaker/.pack-ignore
  Packs/AWS_Sagemaker/Integrations/AWSSagemaker/AWSSagemaker.yml
  Packs/AWS_Sagemaker/ReleaseNotes/1_1_2.md
  Packs/AWS_Sagemaker/pack_metadata.json
Labels: docs-approved

#21110 Updated the Pack ignore file of InfoArmor_VigilanteATI
  Packs/InfoArmor_VigilanteATI/.pack-ignore
Labels: docs-approved

#21080 Tenable io python2 to 3
  Packs/Tenable_io/Integrations/Tenable_io/Tenable_io.py
  Packs/Tenable_io/Integrations/Tenable_io/Tenable_io.yml
  Packs/Tenable_io/Integrations/Tenable_io/Tenable_io_test.py
  Packs/Tenable_io/ReleaseNotes/1_1_8.md
  Packs/Tenable_io/pack_metadata.json
Labels: docs-approved

#21084 Fp set rule 2to3
  Packs/Forcepoint/ReleaseNotes/1_0_5.md
  Packs/Forcepoint/Scripts/FPDeleteRule/FPDeleteRule.py
  Packs/Forcepoint/Scripts/FPDeleteRule/FPDeleteRule.yml
  Packs/Forcepoint/Scripts/FPDeleteRule/FPDeleteRule_test.py
  Packs/Forcepoint/Scripts/FPDeleteRule/README.md
  Packs/Forcepoint/Scripts/FPSetRule/FPSetRule.py
  Packs/Forcepoint/Scripts/FPSetRule/FPSetRule.yml
  Packs/Forcepoint/Scripts/FPSetRule/FPSetRule_test.py
  Packs/Forcepoint/Scripts/FPSetRule/README.md
  Packs/Forcepoint/Scripts/script-FPDeleteRule.yml
  Packs/Forcepoint/Scripts/script-FPSetRule.yml
  Packs/Forcepoint/pack_metadata.json
Labels: docs-approved

#20921 Unit42 atom feed fix
  Packs/FeedUnit42v2/Integrations/FeedUnit42v2/FeedUnit42v2.py
  Packs/FeedUnit42v2/Integrations/FeedUnit42v2/FeedUnit42v2_test.py
  Packs/FeedUnit42v2/ReleaseNotes/1_0_14.md
  Packs/FeedUnit42v2/pack_metadata.json
Labels: docs-approved

#20990 Check email py3
  Packs/Phishing/ReleaseNotes/3_3_3.md
  Packs/Phishing/Scripts/CheckEmailAuthenticity/CheckEmailAuthenticity.yml
  Packs/Phishing/Scripts/CheckEmailAuthenticity/README.md
  Packs/Phishing/pack_metadata.json
Labels: docs-approved, release-notes-only

#20542 feat(intezer): add phishing email playbook, deprecates scan host
  Packs/Intezer/Integrations/IntezerV2/IntezerV2.py
  Packs/Intezer/Integrations/IntezerV2/IntezerV2.yml
  Packs/Intezer/Integrations/IntezerV2/IntezerV2_description.md
  Packs/Intezer/Integrations/IntezerV2/IntezerV2_test.py
  Packs/Intezer/Integrations/IntezerV2/README.md
  Packs/Intezer/Playbooks/playbook-Intezer_-_Analyze_File_and_URL.yml
  Packs/Intezer/Playbooks/playbook-Intezer_-_Analyze_File_and_URL_README.md
  Packs/Intezer/Playbooks/playbook-Intezer_-_Analyze_Uploaded_file_README.md
  Packs/Intezer/Playbooks/playbook-Intezer_-_Analyze_by_hash_README.md
  Packs/Intezer/Playbooks/playbook-Intezer_-_scan_host.yml
  Packs/Intezer/Playbooks/playbook-Intezer_-_scan_host_README.md
  Packs/Intezer/README.md
  Packs/Intezer/ReleaseNotes/1_4_0.md
  Packs/Intezer/Scripts/IntezerRunScanner/IntezerRunScanner.yml
  Packs/Intezer/Scripts/IntezerRunScanner/README.md
  Packs/Intezer/Scripts/IntezerScanHost/IntezerScanHost.yml
  Packs/Intezer/Scripts/IntezerScanHost/README.md
  Packs/Intezer/TestPlaybooks/playbook-Intezer_Test_v2.yml
  Packs/Intezer/doc_files/Intezer_Analyze_File_and_URL.png
  Packs/Intezer/doc_files/Intezer_Analyze_Uploaded_file.png
  Packs/Intezer/doc_files/Intezer_Analyze_by_hash.png
  Packs/Intezer/pack_metadata.json
Labels: Contribution, docs-approved, Partner, ready-for-instance-test, pending-demo, post-demo, Contribution Form Filled, pending-contributor

#21089 fixed an issue in suspicious threshold
  Packs/Cisco-umbrella/Integrations/Cisco-umbrella-investigate/Cisco-umbrella-investigate.py
  Packs/Cisco-umbrella/ReleaseNotes/1_0_14.md
  Packs/Cisco-umbrella/pack_metadata.json
Labels: docs-approved

#20973 python2 EOL Threat grid
  Packs/ThreatGrid/Integrations/ThreatGrid/ThreatGrid.py
  Packs/ThreatGrid/Integrations/ThreatGrid/ThreatGrid.yml
  Packs/ThreatGrid/Integrations/ThreatGrid/ThreatGrid_test.py
  Packs/ThreatGrid/ReleaseNotes/1_2_14.md
  Packs/ThreatGrid/pack_metadata.json
Labels: docs-approved, ForceMerge

#20993 EncodeToAscii - update to python 3.10
  Packs/CommonScripts/ReleaseNotes/1_7_34.md
  Packs/CommonScripts/Scripts/EncodeToAscii/EncodeToAscii.py
  Packs/CommonScripts/Scripts/EncodeToAscii/EncodeToAscii.yml
  Packs/CommonScripts/Scripts/EncodeToAscii/README.md
  Packs/CommonScripts/Scripts/script-EncodeToAscii.yml
  Packs/CommonScripts/pack_metadata.json
Labels: docs-approved

#20977 Update threat x to python3
  Packs/ThreatX/Integrations/ThreatX/ThreatX.yml
  Packs/ThreatX/ReleaseNotes/1_0_8.md
  Packs/ThreatX/pack_metadata.json
Labels: docs-approved, ForceMerge

#20986 Upgrade fortis siem to python3
  Packs/FortiSIEM/Integrations/FortiSIEM/FortiSIEM.py
  Packs/FortiSIEM/Integrations/FortiSIEM/FortiSIEM.yml
  Packs/FortiSIEM/ReleaseNotes/2_0_3.md
  Packs/FortiSIEM/pack_metadata.json
Labels: docs-approved, ForceMerge

#21063 Mcafee mar - update to python 3
  Packs/McAfee-MAR/Integrations/McAfee-MAR/McAfee-MAR.yml
  Packs/McAfee-MAR/ReleaseNotes/1_0_4.md
  Packs/McAfee-MAR/pack_metadata.json
Labels: docs-approved

#21067 Intsignht 2to3
  Packs/IntSight/Integrations/IntSight/IntSight.py
  Packs/IntSight/Integrations/IntSight/IntSight.yml
  Packs/IntSight/Integrations/IntSight/IntSight_test.py
  Packs/IntSight/ReleaseNotes/1_0_14.md
  Packs/IntSight/pack_metadata.json
Labels: docs-approved

#21126 StealthWatch Cloud --> PY3
  Packs/Stealthwatch_Cloud/.pack-ignore
  Packs/Stealthwatch_Cloud/Integrations/Stealthwatch_Cloud/Stealthwatch_Cloud.py
  Packs/Stealthwatch_Cloud/Integrations/Stealthwatch_Cloud/Stealthwatch_Cloud.yml
  Packs/Stealthwatch_Cloud/ReleaseNotes/1_0_10.md
  Packs/Stealthwatch_Cloud/pack_metadata.json
Labels: docs-approved

#21033 Treat miner python3
  Packs/ThreatMiner/Integrations/ThreatMiner/ThreatMiner.py
  Packs/ThreatMiner/Integrations/ThreatMiner/ThreatMiner.yml
  Packs/ThreatMiner/ReleaseNotes/1_0_9.md
  Packs/ThreatMiner/pack_metadata.json
Labels: docs-approved

#20988 Rtir python3
  Packs/RTIR/Integrations/RTIR/README.md
  Packs/RTIR/Integrations/RTIR/RTIR.py
  Packs/RTIR/Integrations/RTIR/RTIR.yml
  Packs/RTIR/ReleaseNotes/1_0_12.md
  Packs/RTIR/pack_metadata.json
Labels: docs-approved

#21127 Attivo Botsink --> PY3
  Packs/AttivoBotsink/Integrations/AttivoBotsink/AttivoBotsink.py
  Packs/AttivoBotsink/Integrations/AttivoBotsink/AttivoBotsink.yml
  Packs/AttivoBotsink/ReleaseNotes/1_0_9.md
  Packs/AttivoBotsink/pack_metadata.json
Labels: docs-approved

#17638 Replaced Demisto name
  Packs/CommonScripts/ReleaseNotes/1_7_35.md
  Packs/CommonScripts/Scripts/DemistoVersion/DemistoVersion.yml
  Packs/CommonScripts/Scripts/DemistoVersion/README.md
  Packs/CommonScripts/Scripts/ProvidesCommand/ProvidesCommand.yml
  Packs/CommonScripts/Scripts/ProvidesCommand/README.md
  Packs/CommonScripts/pack_metadata.json
  Packs/DemistoLocking/Integrations/CoreLock/CoreLock.js
  Packs/DemistoLocking/Integrations/CoreLock/CoreLock.yml
  Packs/DemistoLocking/Integrations/CoreLock/CoreLock_description.md
  Packs/DemistoLocking/Integrations/CoreLock/CoreLock_image.png
  Packs/DemistoLocking/Integrations/CoreLock/README.md
  Packs/DemistoLocking/ReleaseNotes/1_0_4.md
  Packs/DemistoLocking/pack_metadata.json
  Packs/DemistoRESTAPI/.pack-ignore
  Packs/DemistoRESTAPI/Integrations/CoreRESTAPI/CoreRESTAPI.js
  Packs/DemistoRESTAPI/Integrations/CoreRESTAPI/CoreRESTAPI.yml
  Packs/DemistoRESTAPI/Integrations/CoreRESTAPI/CoreRESTAPI_description.md
  Packs/DemistoRESTAPI/Integrations/CoreRESTAPI/CoreRESTAPI_image.png
  Packs/DemistoRESTAPI/Integrations/CoreRESTAPI/README.md
  Packs/DemistoRESTAPI/ReleaseNotes/1_3_1.md
  Packs/DemistoRESTAPI/Scripts/DemistoCreateList/DemistoCreateList.yml
  Packs/DemistoRESTAPI/Scripts/DemistoGetIncidentTasksByState/DemistoGetIncidentTasksByState.yml
  Packs/DemistoRESTAPI/Scripts/DemistoLeaveAllInvestigations/DemistoLeaveAllInvestigations.yml
  Packs/DemistoRESTAPI/Scripts/DemistoLinkIncidents/DemistoLinkIncidents.yml
  Packs/DemistoRESTAPI/Scripts/DemistoLogsBundle/DemistoLogsBundle.yml
  Packs/DemistoRESTAPI/Scripts/DemistoLogsBundle/README.md
  Packs/DemistoRESTAPI/Scripts/DemistoSendInvite/DemistoSendInvite.yml
  Packs/DemistoRESTAPI/Scripts/DemistoSendInvite/README.md
  Packs/DemistoRESTAPI/Scripts/DemistoUploadFileV2/DemistoUploadFileV2.yml
  Packs/DemistoRESTAPI/Scripts/DemistoUploadFileV2/README.md
  Packs/DemistoRESTAPI/pack_metadata.json
  Packs/IntegrationsAndIncidentsHealthCheck/ReleaseNotes/1_3_7.md
  Packs/IntegrationsAndIncidentsHealthCheck/Scripts/GetFailedTasks/GetFailedTasks.yml
  Packs/IntegrationsAndIncidentsHealthCheck/Scripts/RestartFailedTasks/RestartFailedTasks.yml
  Packs/IntegrationsAndIncidentsHealthCheck/pack_metadata.json
  Packs/XSOAR-SimpleDevToProd/ReleaseNotes/1_0_2.md
  Packs/XSOAR-SimpleDevToProd/Scripts/IsDemistoRestAPIInstanceAvailable/IsDemistoRestAPIInstanceAvailable.yml
  Packs/XSOAR-SimpleDevToProd/Scripts/IsDemistoRestAPIInstanceAvailable/README.md
  Packs/XSOAR-SimpleDevToProd/pack_metadata.json
Labels: docs-approved, ForceMerge

#21129 TaniumFilterComputersByIndexQueryFileDetails --> PY3
  Packs/Tanium/ReleaseNotes/1_0_18.md
  Packs/Tanium/Scripts/TaniumFilterComputersByIndexQueryFileDetails/TaniumFilterComputersByIndexQueryFileDetails.yml
  Packs/Tanium/pack_metadata.json
Labels: docs-approved

#20219 SecneurX Analysis Initial Commit
  Packs/CommonPlaybooks/Playbooks/playbook-Detonate_File_-_Generic.yml
  Packs/CommonPlaybooks/Playbooks/playbook-Detonate_File_-_Generic_README.md
  Packs/CommonPlaybooks/Playbooks/playbook-Detonate_URL_-_Generic.yml
  Packs/CommonPlaybooks/Playbooks/playbook-Detonate_URL_-_Generic_README.md
  Packs/CommonPlaybooks/ReleaseNotes/2_3_1.md
  Packs/CommonPlaybooks/pack_metadata.json
  Packs/SecneurXAnalysis/.pack-ignore
  Packs/SecneurXAnalysis/.secrets-ignore
  Packs/SecneurXAnalysis/Author_image.png
  Packs/SecneurXAnalysis/Integrations/SecneurXAnalysis/Pipfile
  Packs/SecneurXAnalysis/Integrations/SecneurXAnalysis/README.md
  Packs/SecneurXAnalysis/Integrations/SecneurXAnalysis/SecneurXAnalysis.py
  Packs/SecneurXAnalysis/Integrations/SecneurXAnalysis/SecneurXAnalysis.yml
  Packs/SecneurXAnalysis/Integrations/SecneurXAnalysis/SecneurXAnalysis_description.md
  Packs/SecneurXAnalysis/Integrations/SecneurXAnalysis/SecneurXAnalysis_image.png
  Packs/SecneurXAnalysis/Integrations/SecneurXAnalysis/SecneurXAnalysis_test.py
  Packs/SecneurXAnalysis/Integrations/SecneurXAnalysis/command_examples
  Packs/SecneurXAnalysis/Integrations/SecneurXAnalysis/test_data/dummy_file.txt
  Packs/SecneurXAnalysis/Integrations/SecneurXAnalysis/test_data/get_response_example.json
  Packs/SecneurXAnalysis/Playbooks/Detonate_File_-_SecneurX_Analysis.yml
  Packs/SecneurXAnalysis/Playbooks/Detonate_File_-_SecneurX_Analysis_README.md
  Packs/SecneurXAnalysis/Playbooks/Detonate_URL_-_SecneurX_Analysis.yml
  Packs/SecneurXAnalysis/Playbooks/Detonate_URL_-_SecneurX_Analysis_README.md
  Packs/SecneurXAnalysis/README.md
  Packs/SecneurXAnalysis/TestPlaybooks/Detonate_File_-_SecneurX_Analysis_-_Test.yml
  Packs/SecneurXAnalysis/TestPlaybooks/Detonate_URL_-_SecneurX_Analysis_-_Test.yml
  Packs/SecneurXAnalysis/doc_files/Detonate_File_SecneurX_Analysis.png
  Packs/SecneurXAnalysis/doc_files/Detonate_URL_SecneurX_Analysis.png
  Packs/SecneurXAnalysis/pack_metadata.json
  Tests/conf.json
Labels: Contribution, docs-approved, Partner, ready-for-instance-test, post-demo, Contribution Form Filled, pending-contributor

#19853 Whois Integration issues
  Packs/Whois/Integrations/Whois/Whois.py
  Packs/Whois/ReleaseNotes/1_3_2.md
  Packs/Whois/pack_metadata.json
Labels: docs-approved

#21093 Ipstack 2to3
  Packs/Ipstack/Integrations/Ipstack/Ipstack.py
  Packs/Ipstack/Integrations/Ipstack/Ipstack.yml
  Packs/Ipstack/Integrations/Ipstack/Ipstack_test.py
  Packs/Ipstack/ReleaseNotes/1_0_8.md
  Packs/Ipstack/pack_metadata.json
Labels: docs-approved, ForceMerge

#21014 McAfee Advanced Threat
  Packs/McAfee_Advanced_Threat_Defense/.secrets-ignore
  Packs/McAfee_Advanced_Threat_Defense/Integrations/McAfee_Advanced_Threat_Defense/McAfee_Advanced_Threat_Defense.py
  Packs/McAfee_Advanced_Threat_Defense/Integrations/McAfee_Advanced_Threat_Defense/McAfee_Advanced_Threat_Defense.yml
  Packs/McAfee_Advanced_Threat_Defense/Integrations/McAfee_Advanced_Threat_Defense/McAfee_Advanced_Threat_Defense_test.py
  Packs/McAfee_Advanced_Threat_Defense/ReleaseNotes/1_0_18.md
  Packs/McAfee_Advanced_Threat_Defense/pack_metadata.json
Labels: docs-approved, ForceMerge

#21098 Mcafee script 2to3
  Packs/mcafeeDam/ReleaseNotes/1_0_4.md
  Packs/mcafeeDam/Scripts/DamSensorDown/DamSensorDown.py
  Packs/mcafeeDam/Scripts/DamSensorDown/DamSensorDown.yml
  Packs/mcafeeDam/Scripts/DamSensorDown/DamSensorDown_test.py
  Packs/mcafeeDam/Scripts/DamSensorDown/README.md
  Packs/mcafeeDam/Scripts/script-McafeeDAMSensorDown.yml
  Packs/mcafeeDam/pack_metadata.json
Labels: docs-approved, ForceMerge

#21121 fix slack notify
  .gitlab/ci/slack-notify.yml
Labels: docs-approved

#21029 Vmray p3
  Packs/PAN-OS/README.md
  Packs/VMRay/Integrations/VMRay/VMRay.py
  Packs/VMRay/Integrations/VMRay/VMRay.yml
  Packs/VMRay/Integrations/VMRay/VMRay_test.py
  Packs/VMRay/ReleaseNotes/1_1_6.md
  Packs/VMRay/pack_metadata.json
Labels: docs-approved

#21140 InfoArmorVigilanteATI: Update .pack-ignore
  Packs/InfoArmor_VigilanteATI/.pack-ignore
Labels: docs-approved

#21077 Zcaler -> python3
  Packs/Zscaler/Integrations/Zscaler/Zscaler.yml
  Packs/Zscaler/Integrations/Zscaler/test_data/results/get_users.json
  Packs/Zscaler/ReleaseNotes/1_2_4.md
  Packs/Zscaler/pack_metadata.json
Labels: docs-approved

#21002 CheckSender - update to python 3.10
  Packs/Pipl/.secrets-ignore
  Packs/Pipl/ReleaseNotes/1_0_5.md
  Packs/Pipl/Scripts/CheckSender/CheckSender.py
  Packs/Pipl/Scripts/CheckSender/CheckSender.yml
  Packs/Pipl/Scripts/CheckSender/CheckSender_test.py
  Packs/Pipl/Scripts/CheckSender/README.md
  Packs/Pipl/Scripts/script-CheckSender.yml
  Packs/Pipl/pack_metadata.json
Labels: docs-approved

#21073 FetchFromInstance - update to python 3
  Packs/DeveloperTools/ReleaseNotes/1_2_26.md
  Packs/DeveloperTools/Scripts/FetchFromInstance/FetchFromInstance.py
  Packs/DeveloperTools/Scripts/FetchFromInstance/FetchFromInstance.yml
  Packs/DeveloperTools/Scripts/FetchFromInstance/README.md
  Packs/DeveloperTools/Scripts/script-FetchFromInstance.yml
  Packs/DeveloperTools/pack_metadata.json
Labels: docs-approved

#21097 moved to python3
  Packs/Carbon_Black_Enterprise_Response/ReleaseNotes/2_1_22.md
  Packs/Carbon_Black_Enterprise_Response/Scripts/CBAlerts/CBAlerts.py
  Packs/Carbon_Black_Enterprise_Response/Scripts/CBAlerts/CBAlerts.yml
  Packs/Carbon_Black_Enterprise_Response/Scripts/CBAlerts/CBAlerts_test.py
  Packs/Carbon_Black_Enterprise_Response/Scripts/CBAlerts/README.md
  Packs/Carbon_Black_Enterprise_Response/Scripts/CBWatchlists/CBWatchlists.py
  Packs/Carbon_Black_Enterprise_Response/Scripts/CBWatchlists/CBWatchlists.yml
  Packs/Carbon_Black_Enterprise_Response/Scripts/CBWatchlists/CBWatchlists_test.py
  Packs/Carbon_Black_Enterprise_Response/Scripts/CBWatchlists/README.md
  Packs/Carbon_Black_Enterprise_Response/Scripts/script-CBAlerts.yml
  Packs/Carbon_Black_Enterprise_Response/Scripts/script-CBWatchlists.yml
  Packs/Carbon_Black_Enterprise_Response/pack_metadata.json
Labels: docs-approved, ForceMerge

#21028 Symantec py3
  Packs/SymantecEndpointProtection/Integrations/SymantecEndpointProtection_V2/SymantecEndpointProtection_V2.py
  Packs/SymantecEndpointProtection/Integrations/SymantecEndpointProtection_V2/SymantecEndpointProtection_V2.yml
  Packs/SymantecEndpointProtection/ReleaseNotes/1_1_1.md
  Packs/SymantecEndpointProtection/Scripts/SEPCheckOutdatedEndpoints/README.md
  Packs/SymantecEndpointProtection/Scripts/SEPCheckOutdatedEndpoints/SEPCheckOutdatedEndpoints.py
  Packs/SymantecEndpointProtection/Scripts/SEPCheckOutdatedEndpoints/SEPCheckOutdatedEndpoints.yml
  Packs/SymantecEndpointProtection/Scripts/SEPCheckOutdatedEndpoints/SEPCheckOutdatedEndpoints_test.py
  Packs/SymantecEndpointProtection/Scripts/script-SEPCheckOutdatedEndpoints.yml
  Packs/SymantecEndpointProtection/pack_metadata.json
Labels: docs-approved

#20980 Upgrade aws sns to python3
  Packs/AWS-SNS/.pack-ignore
  Packs/AWS-SNS/Integrations/AWSSNS/AWSSNS.yml
  Packs/AWS-SNS/ReleaseNotes/1_0_1.md
  Packs/AWS-SNS/pack_metadata.json
Labels: docs-approved

#21095 AccessdataCheckProcessExistsInSnapshot to python3
  Packs/Accessdata/ReleaseNotes/1_0_13.md
  Packs/Accessdata/Scripts/AccessdataCheckProcessExistsInSnapshot/AccessdataCheckProcessExistsInSnapshot.py
  Packs/Accessdata/Scripts/AccessdataCheckProcessExistsInSnapshot/AccessdataCheckProcessExistsInSnapshot.yml
  Packs/Accessdata/Scripts/AccessdataCheckProcessExistsInSnapshot/AccessdataCheckProcessExistsInSnapshot_test.py
  Packs/Accessdata/pack_metadata.json
Labels: ForceMerge

#20967 Migrate JSONtoCSV to Python3
  Packs/CommonScripts/ReleaseNotes/1_7_36.md
  Packs/CommonScripts/Scripts/JSONFileToCSV/JSONFileToCSV_test.py
  Packs/CommonScripts/Scripts/JSONtoCSV/JSONtoCSV.py
  Packs/CommonScripts/Scripts/JSONtoCSV/JSONtoCSV.yml
  Packs/CommonScripts/Scripts/JSONtoCSV/README.md
  Packs/CommonScripts/pack_metadata.json
Labels: docs-approved

#21030 Aws guardduty to py3
  Packs/AWS-GuardDuty/Integrations/AWSGuardDuty/AWSGuardDuty.py
  Packs/AWS-GuardDuty/Integrations/AWSGuardDuty/AWSGuardDuty.yml
  Packs/AWS-GuardDuty/Integrations/AWSGuardDuty/AWSGuardDuty_test.py
  Packs/AWS-GuardDuty/Integrations/AWSGuardDuty/test_data/api_responses_for_test.py
  Packs/AWS-GuardDuty/ReleaseNotes/1_2_10.md
  Packs/AWS-GuardDuty/pack_metadata.json
Labels: docs-approved, release-notes-only

#21145 Hotfix: demisto-sdk 1.7.4
  poetry.lock
  pyproject.toml
Labels: docs-approved

#21124 Cybereason py2to3
  Packs/Cybereason/ReleaseNotes/1_0_21.md
  Packs/Cybereason/Scripts/CybereasonPreProcessingExample/CybereasonPreProcessingExample.py
  Packs/Cybereason/Scripts/CybereasonPreProcessingExample/CybereasonPreProcessingExample.yml
  Packs/Cybereason/Scripts/CybereasonPreProcessingExample/CybereasonPreProcessingExample_test.py
  Packs/Cybereason/Scripts/CybereasonPreProcessingExample/README.md
  Packs/Cybereason/Scripts/script-CybereasonPreProcessing.yml
  Packs/Cybereason/pack_metadata.json
Labels: docs-approved, ForceMerge

#20974 PwnedV2 to py3
  Packs/Pwned/Integrations/PwnedV2/PwnedV2.yml
  Packs/Pwned/ReleaseNotes/1_0_9.md
  Packs/Pwned/pack_metadata.json
Labels: docs-approved

#20982 Migrate JSONFileToCSV to Python 3
  Packs/CommonScripts/ReleaseNotes/1_7_37.md
  Packs/CommonScripts/Scripts/JSONFileToCSV/JSONFileToCSV.py
  Packs/CommonScripts/Scripts/JSONFileToCSV/JSONFileToCSV.yml
  Packs/CommonScripts/Scripts/JSONFileToCSV/README.md
  Packs/CommonScripts/pack_metadata.json
Labels: docs-approved

#21101 Carbon black py3
  Packs/Carbon_Black_Enterprise_Response/ReleaseNotes/2_1_23.md
  Packs/Carbon_Black_Enterprise_Response/Scripts/CBLiveFetchFiles/CBLiveFetchFiles.yml
  Packs/Carbon_Black_Enterprise_Response/Scripts/CBLiveFetchFiles/README.md
  Packs/Carbon_Black_Enterprise_Response/pack_metadata.json
Labels: docs-approved

#21059 update to python3
  Packs/Mimecast/ReleaseNotes/2_0_3.md
  Packs/Mimecast/Scripts/MimecastFindEmail/MimecastFindEmail.py
  Packs/Mimecast/Scripts/MimecastFindEmail/MimecastFindEmail.yml
  Packs/Mimecast/Scripts/MimecastFindEmail/MimecastFindEmail_test.py
  Packs/Mimecast/Scripts/MimecastFindEmail/README.md
  Packs/Mimecast/Scripts/script-MimecastQuery.yml
  Packs/Mimecast/Scripts/script-MimecastQuery_README.md
  Packs/Mimecast/pack_metadata.json
Labels: docs-approved, ForceMerge

#21143 Mattermost ask user - Updated the script to support python3
  Packs/Mattermost/ReleaseNotes/1_0_4.md
  Packs/Mattermost/Scripts/MattermostAskUser/MattermostAskUser.py
  Packs/Mattermost/Scripts/MattermostAskUser/MattermostAskUser.yml
  Packs/Mattermost/Scripts/MattermostAskUser/MattermostAskUser_test.py
  Packs/Mattermost/pack_metadata.json
Labels: docs-approved

#21102 Service now scripts to python3
  Packs/ServiceNow/ReleaseNotes/2_3_23.md
  Packs/ServiceNow/Scripts/ServiceNowCreateIncident/ServiceNowCreateIncident.py
  Packs/ServiceNow/Scripts/ServiceNowCreateIncident/ServiceNowCreateIncident.yml
  Packs/ServiceNow/Scripts/ServiceNowCreateIncident/ServiceNowCreateIncident_test.py
  Packs/ServiceNow/Scripts/ServiceNowQueryIncident/ServiceNowQueryIncident.py
  Packs/ServiceNow/Scripts/ServiceNowQueryIncident/ServiceNowQueryIncident.yml
  Packs/ServiceNow/Scripts/ServiceNowQueryIncident/ServiceNowQueryIncident_test.py
  Packs/ServiceNow/Scripts/ServiceNowUpdateIncident/ServiceNowUpdateIncident.py
  Packs/ServiceNow/Scripts/ServiceNowUpdateIncident/ServiceNowUpdateIncident.yml
  Packs/ServiceNow/Scripts/ServiceNowUpdateIncident/ServiceNowUpdateIncident_test.py
  Packs/ServiceNow/pack_metadata.json
Labels: docs-approved

#21123 Aws s3 py3
  Packs/AWS-S3/Integrations/AWS-S3/AWS-S3.py
  Packs/AWS-S3/Integrations/AWS-S3/AWS-S3.yml
  Packs/AWS-S3/Integrations/AWS-S3/AWS-S3_test.py
  Packs/AWS-S3/Integrations/AWS-S3/test_data/get_bucket_policy.json
  Packs/AWS-S3/ReleaseNotes/1_2_2.md
  Packs/AWS-S3/pack_metadata.json
Labels: docs-approved

#20924 intsight -revert v1.0.13
  Packs/IntSight/Integrations/IntSight/IntSight.py
  Packs/IntSight/ReleaseNotes/1_0_15.md
  Packs/IntSight/pack_metadata.json
Labels: docs-approved

#21118 Move stop time to assign on owner change to py3
  Packs/CommonScripts/ReleaseNotes/1_7_38.md
  Packs/CommonScripts/Scripts/StopTimeToAssignOnOwnerChange/StopTimeToAssignOnOwnerChange.py
  Packs/CommonScripts/Scripts/StopTimeToAssignOnOwnerChange/StopTimeToAssignOnOwnerChange.yml
  Packs/CommonScripts/Scripts/StopTimeToAssignOnOwnerChange/StopTimeToAssignOnOwnerChange_test.py
  Packs/CommonScripts/pack_metadata.json
Labels: docs-approved

#20535 Mimecast
  Packs/Mimecast/.pack-ignore
  Packs/Mimecast/.secrets-ignore
  Packs/Mimecast/Integrations/MimecastEventCollector/MimecastEventCollector_image.png
  Packs/Mimecast/Integrations/MimecastV2/MimecastV2.py
  Packs/Mimecast/Integrations/MimecastV2/MimecastV2.yml
  Packs/Mimecast/Integrations/MimecastV2/MimecastV2_test.py
  Packs/Mimecast/Integrations/MimecastV2/README.md
  Packs/Mimecast/Integrations/MimecastV2/command_examples
  Packs/Mimecast/Integrations/MimecastV2/test_data/get_message_info_response.json
  Packs/Mimecast/Integrations/MimecastV2/test_data/hold_message_summary_response.json
  Packs/Mimecast/Integrations/MimecastV2/test_data/list_hold_messages_response.json
  Packs/Mimecast/Integrations/MimecastV2/test_data/release_hold_message_response.json
  Packs/Mimecast/Integrations/MimecastV2/test_data/search_message_response.json
  Packs/Mimecast/Integrations/MimecastV2/test_data/search_processing_message_response.json
  Packs/Mimecast/ReleaseNotes/2_1_0.md
  Packs/Mimecast/TestPlaybooks/playbook-Mimecast_Test.yml
  Packs/Mimecast/pack_metadata.json
Labels: docs-approved

#21026 Incapsula scrips to py3
  Packs/Incapsula/ReleaseNotes/1_0_6.md
  Packs/Incapsula/Scripts/IncapGetAppInfo/IncapGetAppInfo.py
  Packs/Incapsula/Scripts/IncapGetAppInfo/IncapGetAppInfo.yml
  Packs/Incapsula/Scripts/IncapGetAppInfo/README.md
  Packs/Incapsula/Scripts/IncapGetDomainApproverEmail/IncapGetDomainApproverEmail.py
  Packs/Incapsula/Scripts/IncapGetDomainApproverEmail/IncapGetDomainApproverEmail.yml
  Packs/Incapsula/Scripts/IncapGetDomainApproverEmail/README.md
  Packs/Incapsula/Scripts/IncapListSites/IncapListSites.py
  Packs/Incapsula/Scripts/IncapListSites/IncapListSites.yml
  Packs/Incapsula/Scripts/IncapListSites/README.md
  Packs/Incapsula/Scripts/IncapScheduleTask/IncapScheduleTask.py
  Packs/Incapsula/Scripts/IncapScheduleTask/IncapScheduleTask.yml
  Packs/Incapsula/Scripts/IncapScheduleTask/README.md
  Packs/Incapsula/Scripts/IncapWhitelistCompliance/IncapWhitelistCompliance.py
  Packs/Incapsula/Scripts/IncapWhitelistCompliance/IncapWhitelistCompliance.yml
  Packs/Incapsula/Scripts/IncapWhitelistCompliance/IncapWhitelistCompliance_test.py
  Packs/Incapsula/Scripts/IncapWhitelistCompliance/README.md
  Packs/Incapsula/Scripts/script-IncapGetAppInfo.yml
  Packs/Incapsula/Scripts/script-IncapGetDomainApproverEmail.yml
  Packs/Incapsula/Scripts/script-IncapWhitelistCompliance.yml
  Packs/Incapsula/Scripts/script-IncapWhitelistCompliance_README.md
  Packs/Incapsula/pack_metadata.json
Labels: docs-approved, ForceMerge

#21004 Duoadmin py3
  Packs/DuoAdminApi/.pack-ignore
  Packs/DuoAdminApi/Integrations/DuoAdminApi/DuoAdminApi.py
  Packs/DuoAdminApi/Integrations/DuoAdminApi/DuoAdminApi.yml
  Packs/DuoAdminApi/Integrations/DuoAdminApi/DuoAdminApi_test.py
  Packs/DuoAdminApi/Integrations/DuoAdminApi/README.md
  Packs/DuoAdminApi/Integrations/DuoAdminApi/test_data/get_all_bypass_codes.json
  Packs/DuoAdminApi/Integrations/DuoAdminApi/test_data/get_all_devices.json
  Packs/DuoAdminApi/Integrations/DuoAdminApi/test_data/get_authentication_logs_by_user.json
  Packs/DuoAdminApi/Integrations/DuoAdminApi/test_data/get_users.json
  Packs/DuoAdminApi/ReleaseNotes/3_1_0.md
  Packs/DuoAdminApi/TestPlaybooks/playbook-DuoAdminaAPITest.yml
  Packs/DuoAdminApi/pack_metadata.json
Labels: docs-approved

#21090 Move fireye denote file script to py3
  Packs/fireeye/ReleaseNotes/1_0_10.md
  Packs/fireeye/Scripts/FireEyeDetonateFile/FireEyeDetonateFile.py
  Packs/fireeye/Scripts/FireEyeDetonateFile/FireEyeDetonateFile.yml
  Packs/fireeye/Scripts/FireEyeDetonateFile/FireEyeDetonateFile_test.py
  Packs/fireeye/Scripts/FireEyeDetonateFile/README.md
  Packs/fireeye/Scripts/script-FireEyeDetonateFile.yml
  Packs/fireeye/pack_metadata.json
Labels: docs-approved, ForceMerge

#21017 Move algosec get ticket to py3
  Packs/Algosec/ReleaseNotes/1_0_8.md
  Packs/Algosec/Scripts/AlgosecGetTicket/AlgosecGetTicket.py
  Packs/Algosec/Scripts/AlgosecGetTicket/AlgosecGetTicket.yml
  Packs/Algosec/Scripts/AlgosecGetTicket/AlgosecGetTicket_test.py
  Packs/Algosec/Scripts/AlgosecGetTicket/README.md
  Packs/Algosec/Scripts/script-AlgosecGetTicket.yml
  Packs/Algosec/pack_metadata.json
Labels: docs-approved, ForceMerge

#20998 deprecate archerRSA scripts
  Packs/ArcherRSA/ReleaseNotes/1_2_1.md
  Packs/ArcherRSA/Scripts/ArcherCreateSecurityIncident/ArcherCreateSecurityIncident.py
  Packs/ArcherRSA/Scripts/ArcherCreateSecurityIncident/ArcherCreateSecurityIncident.yml
  Packs/ArcherRSA/Scripts/ArcherCreateSecurityIncident/README.md
  Packs/ArcherRSA/Scripts/ArcherUpdateSecurityIncident/ArcherUpdateSecurityIncident.py
  Packs/ArcherRSA/Scripts/ArcherUpdateSecurityIncident/ArcherUpdateSecurityIncident.yml
  Packs/ArcherRSA/Scripts/ArcherUpdateSecurityIncident/README.md
  Packs/ArcherRSA/Scripts/RSAArcherManualFetch/README.md
  Packs/ArcherRSA/Scripts/RSAArcherManualFetch/RSAArcherManualFetch.py
  Packs/ArcherRSA/Scripts/RSAArcherManualFetch/RSAArcherManualFetch.yml
  Packs/ArcherRSA/Scripts/script-ArcherCreateSecurityIncident.yml
  Packs/ArcherRSA/Scripts/script-ArcherCreateSecurityIncident_README.md
  Packs/ArcherRSA/Scripts/script-ArcherUpdateSecurityIncident.yml
  Packs/ArcherRSA/Scripts/script-ArcherUpdateSecurityIncident_README.md
  Packs/ArcherRSA/Scripts/script-RSAArcherManualFetch.yml
  Packs/ArcherRSA/Scripts/script-RSAArcherManualFetch_README.md
  Packs/ArcherRSA/pack_metadata.json
Labels: docs-approved, ForceMerge

#20954 pcap_https_to_py3
  Packs/CommonScripts/ReleaseNotes/1_7_38.md
  Packs/CommonScripts/ReleaseNotes/1_7_39.md
  Packs/CommonScripts/Scripts/PcapHTTPExtractor/PcapHTTPExtractor.py
  Packs/CommonScripts/Scripts/PcapHTTPExtractor/PcapHTTPExtractor.yml
  Packs/CommonScripts/Scripts/PcapHTTPExtractor/PcapHTTPExtractor_test.py
  Packs/CommonScripts/Scripts/PcapHTTPExtractor/README.md
  Packs/CommonScripts/Scripts/PcapHTTPExtractor/test_data/TestPcapPost.pcap
  Packs/CommonScripts/pack_metadata.json
Labels: docs-approved

#21086 sane pdf: use temp files
  Packs/Base/ReleaseNotes/1_31_20.md
  Packs/Base/Scripts/SanePdfReport/README.md
  Packs/Base/Scripts/SanePdfReport/SanePdfReport.py
  Packs/Base/Scripts/SanePdfReport/SanePdfReport.yml
  Packs/Base/pack_metadata.json
Labels: docs-approved

#21027 TestCollect: content items without ID
  Tests/scripts/collect_tests/collect_tests.py
  Tests/scripts/collect_tests/exceptions.py
  Tests/scripts/collect_tests/utils.py
Labels: docs-approved

#21119 Checkpoint deprecation scripts
  Packs/CheckpointFirewall/ReleaseNotes/2_3_1.md
  Packs/CheckpointFirewall/Scripts/CheckpointFWBackupStatus/CheckpointFWBackupStatus.yml
  Packs/CheckpointFirewall/Scripts/CheckpointFWCreateBackup/CheckpointFWCreateBackup.yml
  Packs/CheckpointFirewall/pack_metadata.json
Labels: docs-approved

#20959 move BuildTWSQuery script to py3
  Packs/EWS/ReleaseNotes/1_12_7.md
  Packs/EWS/Scripts/BuildEWSQuery/BuildEWSQuery.py
  Packs/EWS/Scripts/BuildEWSQuery/BuildEWSQuery.yml
  Packs/EWS/Scripts/BuildEWSQuery/BuildEWSQuery_test.py
  Packs/EWS/pack_metadata.json
Labels: docs-approved, ForceMerge

#20971 2to3CuckooSandbox
  Packs/CuckooSandbox/ReleaseNotes/1_1_2.md
  Packs/CuckooSandbox/Scripts/CuckooDetonateFile/CuckooDetonateFile.py
  Packs/CuckooSandbox/Scripts/CuckooDetonateFile/CuckooDetonateFile.yml
  Packs/CuckooSandbox/Scripts/CuckooDetonateFile/README.md
  Packs/CuckooSandbox/Scripts/CuckooDetonateURL/CuckooDetonateURL.py
  Packs/CuckooSandbox/Scripts/CuckooDetonateURL/CuckooDetonateURL.yml
  Packs/CuckooSandbox/Scripts/CuckooDetonateURL/README.md
  Packs/CuckooSandbox/Scripts/CuckooDisplayReport/CuckooDisplayReport.py
  Packs/CuckooSandbox/Scripts/CuckooDisplayReport/CuckooDisplayReport.yml
  Packs/CuckooSandbox/Scripts/CuckooGetReport/CuckooGetReport.py
  Packs/CuckooSandbox/Scripts/CuckooGetReport/CuckooGetReport.yml
  Packs/CuckooSandbox/Scripts/CuckooGetReport/README.md
  Packs/CuckooSandbox/Scripts/CuckooGetScreenshot/CuckooGetScreenshot.py
  Packs/CuckooSandbox/Scripts/CuckooGetScreenshot/CuckooGetScreenshot.yml
  Packs/CuckooSandbox/Scripts/CuckooGetScreenshot/README.md
  Packs/CuckooSandbox/Scripts/CuckooTaskStatus/CuckooTaskStatus.py
  Packs/CuckooSandbox/Scripts/CuckooTaskStatus/CuckooTaskStatus.yml
  Packs/CuckooSandbox/Scripts/CuckooTaskStatus/README.md
  Packs/CuckooSandbox/Scripts/script-CuckooDetonateURL.yml
  Packs/CuckooSandbox/Scripts/script-CuckooTaskStatus.yml
  Packs/CuckooSandbox/pack_metadata.json
Labels: docs-approved, ForceMerge

#21092 Centreon - python 2to3
  Packs/Centreon/Integrations/Centreon/Centreon.py
  Packs/Centreon/Integrations/Centreon/Centreon.yml
  Packs/Centreon/Integrations/Centreon/Centreon_test.py
  Packs/Centreon/ReleaseNotes/1_0_7.md
  Packs/Centreon/pack_metadata.json
Labels: docs-approved

#20849 Exterro1.0
  Packs/Exterro/.pack-ignore
  Packs/Exterro/.secrets-ignore
  Packs/Exterro/Author_image.png
  Packs/Exterro/Integrations/Exterro/Exterro.py
  Packs/Exterro/Integrations/Exterro/Exterro.yml
  Packs/Exterro/Integrations/Exterro/Exterro_description.md
  Packs/Exterro/Integrations/Exterro/Exterro_image.png
  Packs/Exterro/Integrations/Exterro/Exterro_test.py
  Packs/Exterro/Integrations/Exterro/Pipfile
  Packs/Exterro/Integrations/Exterro/Pipfile.lock
  Packs/Exterro/Integrations/Exterro/README.md
  Packs/Exterro/Integrations/Exterro/command_examples
  Packs/Exterro/README.md
  Packs/Exterro/pack_metadata.json
Labels: Contribution, docs-approved, Partner, Contribution Form Filled

#20953 CheckPhish - python 2 to 3
  Packs/CheckPhish/Integrations/CheckPhish/CheckPhish.py
  Packs/CheckPhish/Integrations/CheckPhish/CheckPhish.yml
  Packs/CheckPhish/ReleaseNotes/1_0_10.md
  Packs/CheckPhish/pack_metadata.json
Labels: docs-approved, ForceMerge

#21107 Confluence - python 2 to 3
  Packs/Confluence/Integrations/Confluence/Confluence.py
  Packs/Confluence/Integrations/Confluence/Confluence.yml
  Packs/Confluence/Integrations/Confluence/Confluence_test.py
  Packs/Confluence/ReleaseNotes/1_0_6.md
  Packs/Confluence/pack_metadata.json
Labels: docs-approved

#21025 Deprecate UserEnrichAD Script
  Packs/Active_Directory_Query/ReleaseNotes/1_4_18.md
  Packs/Active_Directory_Query/Scripts/UserEnrichAD/UserEnrichAD.py
  Packs/Active_Directory_Query/Scripts/UserEnrichAD/UserEnrichAD.yml
  Packs/Active_Directory_Query/Scripts/UserEnrichAD/UserEnrichAD_README.md
  Packs/Active_Directory_Query/pack_metadata.json
Labels: docs-approved

#20255 Jb GitHub jira integration action
  .github/workflows/close_jira_issue_by_pr_merge.yml
  .github/workflows/link_edited_pr_to_jira_issue.yml
  Tests/secrets_white_list.json
  Utils/github_workflow_scripts/github_workflow_scripts_tests/link_pr_to_jira_issue_test.py
  Utils/github_workflow_scripts/jira_integration_scripts/link_pr_to_jira_issue.py
Labels: docs-approved

#21020 Migrate CheckDockerImageAvailable Script to Python 3
  Packs/Base/ReleaseNotes/1_31_21.md
  Packs/Base/Scripts/CheckDockerImageAvailable/CheckDockerImageAvailable.py
  Packs/Base/Scripts/CheckDockerImageAvailable/CheckDockerImageAvailable.yml
  Packs/Base/Scripts/CheckDockerImageAvailable/README.md
  Packs/Base/pack_metadata.json
Labels: docs-approved

#21167 fix jira_github workflow
  .github/workflows/close_jira_issue_by_pr_merge.yml
Labels: docs-approved

#20842 [Archer v2] Added raw_response for a few commands
  Packs/ArcherRSA/Integrations/ArcherV2/ArcherV2.py
  Packs/ArcherRSA/Integrations/ArcherV2/ArcherV2.yml
  Packs/ArcherRSA/ReleaseNotes/1_2_2.md
  Packs/ArcherRSA/pack_metadata.json
Labels: docs-approved

#20938 Updating the Readme files
  Packs/MicrosoftDNS/README.md
  Packs/MicrosoftExchangeServer/README.md
  Packs/MicrosoftNPS/README.md
  Packs/MicrosoftWSUS/README.md
Labels: docs-approved

#21131 IndicatorMaliciousRatioCalculation --> PY3
  Packs/CommonScripts/ReleaseNotes/1_7_40.md
  Packs/CommonScripts/Scripts/IndicatorMaliciousRatioCalculation/IndicatorMaliciousRatioCalculation.py
  Packs/CommonScripts/Scripts/IndicatorMaliciousRatioCalculation/IndicatorMaliciousRatioCalculation.yml
  Packs/CommonScripts/pack_metadata.json
Labels: docs-approved
