Repository demisto/content, pull requests merged in 2022-07, with the labels that each got.

#19846 Fix panorama pcap bug
  Packs/PAN-OS/Integrations/Panorama/Panorama.py
  Packs/PAN-OS/ReleaseNotes/1_14_5.md
  Packs/PAN-OS/pack_metadata.json
Labels: docs-approved

#19674 Active directory query v2 a santamarina
  Packs/Active_Directory_Query/Integrations/Active_Directory_Query/Active_Directory_Query.py
  Packs/Active_Directory_Query/Integrations/Active_Directory_Query/Active_Directory_Query.yml
  Packs/Active_Directory_Query/Integrations/Active_Directory_Query/Active_Directory_Query_test.py
  Packs/Active_Directory_Query/Integrations/Active_Directory_Query/README.md
  Packs/Active_Directory_Query/ReleaseNotes/1_4_15.md
  Packs/Active_Directory_Query/pack_metadata.json
Labels: Contribution, docs-approved, ready-for-instance-test, pending-demo, post-demo, Contribution Form Filled, Community

#19617 Cs incident fixes
  Packs/CrowdStrikeFalcon/Classifiers/classifier-CrowdStrike_Falcon_Mapper_6.5.json
  Packs/CrowdStrikeFalcon/Playbooks/playbook-CrowdStrike_Falcon_-_Get_Detections_by_Incident.yml
  Packs/CrowdStrikeFalcon/Playbooks/playbook-CrowdStrike_Falcon_Malware_-_Incident_Enrichment.yml
  Packs/CrowdStrikeFalcon/Playbooks/playbook-CrowdStrike_Falcon_Malware_-_Incident_Enrichment_README.md
  Packs/CrowdStrikeFalcon/Playbooks/playbook-CrowdStrike_Falcon_Malware_-_Investigation_and_Response.yml
  Packs/CrowdStrikeFalcon/Playbooks/playbook-CrowdStrike_Falcon_SIEM_ingestion_-_Get_Incident_Data.yml
  Packs/CrowdStrikeFalcon/Playbooks/playbook-CrowdStrike_Falcon_SIEM_ingestion_-_Get_Incident_Data_README.md
  Packs/CrowdStrikeFalcon/ReleaseNotes/1_8_7.md
  Packs/CrowdStrikeFalcon/doc_files/CrowdStrike_Falcon_-_Get_Detections_by_Incident.png
  Packs/CrowdStrikeFalcon/doc_files/CrowdStrike_Falcon_-_SIEM_ingestion_-_Get_Incident_Data.png
  Packs/CrowdStrikeFalcon/doc_files/CrowdStrike_Falcon_Malware_-_Incident_Enrichment.png
  Packs/CrowdStrikeFalcon/doc_files/CrowdStrike_Falcon_Malware_-_Investigation_and_Response.png
  Packs/CrowdStrikeFalcon/pack_metadata.json
  Packs/MalwareInvestigationAndResponse/Playbooks/playbook-Malware_Investigation_and_Response_Incident_Handler.yml
  Packs/MalwareInvestigationAndResponse/Playbooks/playbook-Malware_SIEM_Ingestion_-_Get_Incident_Data.yml
  Packs/MalwareInvestigationAndResponse/Playbooks/playbook-Malware_SIEM_Ingestion_-_Get_Incident_Data_README.md
  Packs/MalwareInvestigationAndResponse/ReleaseNotes/1_5_5.md
  Packs/MalwareInvestigationAndResponse/pack_metadata.json
Labels: docs-approved

#19870 MITRE ATT&CK v2 handle incorrect attack-pattern
  Packs/FeedMitreAttackv2/Integrations/FeedMitreAttackv2/FeedMitreAttackv2.py
  Packs/FeedMitreAttackv2/ReleaseNotes/1_1_2.md
  Packs/FeedMitreAttackv2/pack_metadata.json
Labels: docs-approved

#19831 Removing the filter by marketplace for the upload that runs in the build
  Tests/Marketplace/upload_packs.py
Labels: docs-approved, ForceMerge

#19759 Repair of fetch-incidents command
  Packs/AWS-SQS/Integrations/AWS-SQS/AWS-SQS.py
  Packs/AWS-SQS/Integrations/AWS-SQS/AWS-SQS_test.py
  Packs/AWS-SQS/ReleaseNotes/1_2_10.md
  Packs/AWS-SQS/pack_metadata.json
Labels: docs-approved

#19481 XDR file retrieve logic fix
  Packs/ApiModules/Scripts/CoreIRApiModule/CoreIRApiModule.py
  Packs/ApiModules/Scripts/CoreIRApiModule/CoreIRApiModule_test.py
  Packs/Core/ReleaseNotes/1_3_1.md
  Packs/Core/pack_metadata.json
  Packs/CortexXDR/Integrations/CortexXDRIR/CortexXDRIR.py
  Packs/CortexXDR/Integrations/CortexXDRIR/CortexXDRIR.yml
  Packs/CortexXDR/Integrations/CortexXDRIR/README.md
  Packs/CortexXDR/ReleaseNotes/4_7_1.md
  Packs/CortexXDR/pack_metadata.json
Labels: docs-approved

#19872 Falcon get detections bug fix
  Packs/CrowdStrikeFalcon/Integrations/CrowdStrikeFalcon/CrowdStrikeFalcon.py
  Packs/CrowdStrikeFalcon/Integrations/CrowdStrikeFalcon/CrowdStrikeFalcon.yml
  Packs/CrowdStrikeFalcon/ReleaseNotes/1_8_8.md
  Packs/CrowdStrikeFalcon/pack_metadata.json
Labels: docs-approved

#19877 Fix cortexCoreIR
  Packs/Core/Integrations/CortexCoreIR/CortexCoreIR.py
  Packs/Core/Integrations/CortexCoreIR/CortexCoreIR.yml
  Packs/Core/ReleaseNotes/1_3_2.md
  Packs/Core/pack_metadata.json
Labels: docs-approved

#19801 HashiCorp Vault - Add namespace param
  Packs/HashiCorp-Vault/.pack-ignore
  Packs/HashiCorp-Vault/Integrations/HashiCorpVault/HashiCorpVault.py
  Packs/HashiCorp-Vault/Integrations/HashiCorpVault/HashiCorpVault.yml
  Packs/HashiCorp-Vault/ReleaseNotes/1_0_8.md
  Packs/HashiCorp-Vault/pack_metadata.json
Labels: docs-approved

#19866 File case fixing
  Packs/CommonPlaybooks/Playbooks/playbook-Command-Line_Analysis.yml
  Packs/CommonPlaybooks/ReleaseNotes/2_2_6.md
  Packs/CommonPlaybooks/pack_metadata.json
Labels: docs-approved, release-notes-only

#19512 Future feed file not getting deleted
  Packs/FeedRecordedFuture/.pack-ignore
  Packs/FeedRecordedFuture/Integrations/FeedRecordedFuture/FeedRecordedFuture.py
  Packs/FeedRecordedFuture/Integrations/FeedRecordedFuture/FeedRecordedFuture.yml
  Packs/FeedRecordedFuture/ReleaseNotes/1_0_27.md
  Packs/FeedRecordedFuture/pack_metadata.json
Labels: docs-approved

#19848 removed copyright section
  Packs/AnsibleCiscoIOS/.pack-ignore
  Packs/AnsibleLinux/.pack-ignore
  Packs/AnsibleMicrosoftWindows/.pack-ignore
  Packs/CommonScripts/.pack-ignore
  Packs/CommonScripts/ReleaseNotes/1_7_12.md
  Packs/CommonScripts/Scripts/ParseEmailFiles/ParseEmailFiles.py
  Packs/CommonScripts/pack_metadata.json
  Packs/DNSDB/.pack-ignore
  Packs/DNSDB/Integrations/DNSDB_v2/DNSDB_v2.py
  Packs/DNSDB/Integrations/DNSDB_v2/DNSDB_v2.yml
  Packs/DNSDB/Integrations/DNSDB_v2/DNSDB_v2_test.py
  Packs/DNSDB/ReleaseNotes/2_1_8.md
  Packs/DNSDB/pack_metadata.json
  Packs/Endace/Integrations/Endace/Endace.py
  Packs/Endace/Integrations/Endace/Endace.yml
  Packs/Endace/Integrations/Endace/Endace_test.py
  Packs/Endace/ReleaseNotes/1_1_9.md
  Packs/Endace/pack_metadata.json
  Packs/GoogleChronicleBackstory/.pack-ignore
  Packs/Infocyte/.pack-ignore
  Packs/Qintel/.pack-ignore
  Packs/RiskSense/.pack-ignore
  Packs/SecBI/.pack-ignore
  Packs/Silverfort/.pack-ignore
  Packs/qualys/.pack-ignore
Labels: docs-approved

#19874 Fix scriptname field in playbook
  Packs/Phishing/Playbooks/Phishing_-_Generic_v3.yml
  Packs/Phishing/ReleaseNotes/3_2_6.md
  Packs/Phishing/pack_metadata.json
Labels: docs-approved

#19881 skip firewall test playbooks
  Tests/conf.json
Labels: docs-approved

#18703 Microsoft Ip named location
  Packs/AzureActiveDirectory/Integrations/AzureADIdentityProtection/AzureADIdentityProtection.yml
  Packs/AzureActiveDirectory/ReleaseNotes/1_2_10.md
  Packs/AzureActiveDirectory/pack_metadata.json
  Packs/MicrosoftGraphIdentityandAccess/.pack-ignore
  Packs/MicrosoftGraphIdentityandAccess/.secrets-ignore
  Packs/MicrosoftGraphIdentityandAccess/Classifiers/classifier-Azure_Active_Directory_Identity_Protection_Classifier.json
  Packs/MicrosoftGraphIdentityandAccess/Classifiers/classifier-mapping-incoming-Azure_Active_Directory_Identity_Protection-Incoming_Mapper.json
  Packs/MicrosoftGraphIdentityandAccess/IncidentFields/incidentfield-Activity.json
  Packs/MicrosoftGraphIdentityandAccess/IncidentFields/incidentfield-Alert_Type.json
  Packs/MicrosoftGraphIdentityandAccess/IncidentFields/incidentfield-DetectedDateTime.json
  Packs/MicrosoftGraphIdentityandAccess/IncidentFields/incidentfield-DetectionTimingType.json
  Packs/MicrosoftGraphIdentityandAccess/IncidentFields/incidentfield-TokenIssuerType.json
  Packs/MicrosoftGraphIdentityandAccess/IncidentTypes/incidenttype-MsGraphIdentityAndAccess.json
  Packs/MicrosoftGraphIdentityandAccess/Integrations/MicrosoftGraphIdentityandAccess/MicrosoftGraphIdentityandAccess.py
  Packs/MicrosoftGraphIdentityandAccess/Integrations/MicrosoftGraphIdentityandAccess/MicrosoftGraphIdentityandAccess.yml
  Packs/MicrosoftGraphIdentityandAccess/Integrations/MicrosoftGraphIdentityandAccess/MicrosoftGraphIdentityandAccess_description.md
  Packs/MicrosoftGraphIdentityandAccess/Integrations/MicrosoftGraphIdentityandAccess/MicrosoftGraphIdentityandAccess_test.py
  Packs/MicrosoftGraphIdentityandAccess/Integrations/MicrosoftGraphIdentityandAccess/README.md
  Packs/MicrosoftGraphIdentityandAccess/Integrations/MicrosoftGraphIdentityandAccess/command_examples
  Packs/MicrosoftGraphIdentityandAccess/Layouts/layoutscontainer-Azure_Active_Directory_Identity_Protection_Layout.json
  Packs/MicrosoftGraphIdentityandAccess/README.md
  Packs/MicrosoftGraphIdentityandAccess/ReleaseNotes/1_1_0.md
  Packs/MicrosoftGraphIdentityandAccess/TestPlaybooks/MSGraph-Identity-testplaybook.yml
  Packs/MicrosoftGraphIdentityandAccess/pack_metadata.json
Labels: docs-approved

#19867 Phishing attachments
  Packs/Phishing/Layouts/layoutscontainer-Phishing_v_3.json
  Packs/Phishing/Playbooks/Process_Email_-_Generic_v2.yml
  Packs/Phishing/ReleaseNotes/3_2_7.md
  Packs/Phishing/doc_files/Process_Email_-_Generic_v2.png
  Packs/Phishing/pack_metadata.json
Labels: docs-approved

#18548 Rasterize Enhancements
  Packs/rasterize/Integrations/rasterize/README.md
  Packs/rasterize/Integrations/rasterize/rasterize.py
  Packs/rasterize/Integrations/rasterize/rasterize.yml
  Packs/rasterize/Integrations/rasterize/rasterize_test.py
  Packs/rasterize/ReleaseNotes/1_2_0.md
  Packs/rasterize/TestPlaybooks/playbook-Rasterize_Test.yml
  Packs/rasterize/pack_metadata.json
  Tests/known_words.txt
Labels: docs-approved

#19264 Crowdstrike falcon x
  Packs/CrowdStrikeFalconX/.pack-ignore
  Packs/CrowdStrikeFalconX/Integrations/CrowdStrikeFalconX/CrowdStrikeFalconX.py
  Packs/CrowdStrikeFalconX/Integrations/CrowdStrikeFalconX/CrowdStrikeFalconX.yml
  Packs/CrowdStrikeFalconX/Playbooks/Detonate_File_-_CrowdStrike_Falcon_X.yml
  Packs/CrowdStrikeFalconX/Playbooks/playbook-FalconX_Detonate_and_Analyze_File.yml
  Packs/CrowdStrikeFalconX/ReleaseNotes/1_2_9.md
  Packs/CrowdStrikeFalconX/pack_metadata.json
  Tests/conf.json
  Tests/known_words.txt
Labels: docs-approved

#19885 Updated DBotPredictURLPhishing readme with security disclaimer
  Packs/PhishingURL/Scripts/DBotPredictURLPhishing/README.md
Labels: docs-approved

#19882 Cherwell download attachments bug fix
  Packs/Cherwell/Integrations/Cherwell/Cherwell.py
  Packs/Cherwell/Integrations/Cherwell/Cherwell.yml
  Packs/Cherwell/ReleaseNotes/1_0_12.md
  Packs/Cherwell/pack_metadata.json
Labels: bug, docs-approved, release-notes-only

#19338 Switching panorama scripts and playbooks dependencies
  Packs/Change_Management/.pack-ignore
  Packs/Change_Management/Playbooks/playbook-Jira_Change_Management.yml
  Packs/Change_Management/Playbooks/playbook-PAN-OS_create_or_edit_policy.yml
  Packs/Change_Management/Playbooks/playbook-PAN-OS_edit_policy.yml
  Packs/Change_Management/Playbooks/playbook-ServiceNow_Change_Management.yml
  Packs/Change_Management/ReleaseNotes/1_0_1.md
  Packs/Change_Management/pack_metadata.json
  Packs/CommonPlaybooks/Playbooks/playbook-Block_Account_-_Generic.yml
  Packs/CommonPlaybooks/ReleaseNotes/2_2_7.md
  Packs/CommonPlaybooks/pack_metadata.json
  Packs/Digital_Defense_FrontlineVM/.pack-ignore
  Packs/Digital_Defense_FrontlineVM/Playbooks/playbook-Digital_Defense_FrontlineVM_-_PAN-OS_block_assets.yml
  Packs/Digital_Defense_FrontlineVM/ReleaseNotes/1_1_6.md
  Packs/Digital_Defense_FrontlineVM/pack_metadata.json
  Packs/EDL/Playbooks/playbook-PAN-OS_EDL_Service_Configuration.yml
  Packs/EDL/ReleaseNotes/3_1_5.md
  Packs/EDL/pack_metadata.json
  Packs/ExpanseV2/Playbooks/playbook-Expanse_Attribution.yml
  Packs/ExpanseV2/Playbooks/playbook-Handle_Expanse_Incident.yml
  Packs/ExpanseV2/ReleaseNotes/1_10_16.md
  Packs/ExpanseV2/pack_metadata.json
  Packs/GoogleChronicleBackstory/Playbooks/playbook-Investigate_On_Bad_Domain_Matches_-_Chronicle.yml
  Packs/GoogleChronicleBackstory/ReleaseNotes/2_0_20.md
  Packs/GoogleChronicleBackstory/pack_metadata.json
  Packs/NGFWTSAgentDeployment/.pack-ignore
  Packs/NGFWTSAgentDeployment/Playbooks/JOB_-_PANW_NGFW_TS_Agent_Cleanup.yml
  Packs/NGFWTSAgentDeployment/Playbooks/NGFW_Remove_Offline_TS_Agent.yml
  Packs/NGFWTSAgentDeployment/Playbooks/PANW_NGFW_TS_Agent_Deployment.yml
  Packs/NGFWTSAgentDeployment/ReleaseNotes/1_0_1.md
  Packs/NGFWTSAgentDeployment/pack_metadata.json
  Packs/PAN-OS/Playbooks/playbook-Pan-OS_Commit_Configuration.yml
  Packs/PAN-OS/ReleaseNotes/1_14_5.md
  Packs/PAN-OS/ReleaseNotes/1_14_6.md
  Packs/PAN-OS/TestPlaybooks/playbook-PAN-OS_DAG_Configuration_Test.yml
  Packs/PAN-OS/pack_metadata.json
  Packs/PANOSPolicyOptimizer/.pack-ignore
  Packs/PANOSPolicyOptimizer/Playbooks/playbook-Policy_Optimizer_-_Add_Applications_to_Policy_Rules.yml
  Packs/PANOSPolicyOptimizer/Playbooks/playbook-Policy_Optimizer_-_Manage_Port_Based_Rules.yml
  Packs/PANOSPolicyOptimizer/Playbooks/playbook-Policy_Optimizer_-_Manage_Rules_with_Unused_Applications.yml
  Packs/PANOSPolicyOptimizer/Playbooks/playbook-Policy_Optimizer_-_Manage_Unused_Rules.yml
  Packs/PANOSPolicyOptimizer/ReleaseNotes/1_0_7.md
  Packs/PANOSPolicyOptimizer/pack_metadata.json
  Packs/PANOStoCDLMonitoring/ReleaseNotes/1_0_10.md
  Packs/PANOStoCDLMonitoring/Scripts/PANOStoCortexDataLakeMonitoring/PANOStoCortexDataLakeMonitoring.py
  Packs/PANOStoCDLMonitoring/Scripts/PANOStoCortexDataLakeMonitoring/PANOStoCortexDataLakeMonitoring.yml
  Packs/PANOStoCDLMonitoring/Scripts/PANOStoCortexDataLakeMonitoring/Pipfile
  Packs/PANOStoCDLMonitoring/Scripts/PANOStoCortexDataLakeMonitoring/Pipfile.lock
  Packs/PANOStoCDLMonitoring/Scripts/PANOStoCortexDataLakeMonitoring/README.md
  Packs/PANOStoCDLMonitoring/pack_metadata.json
  Packs/PaloAltoNetworks_PAN_OS_EDL_Management/.pack-ignore
  Packs/PaloAltoNetworks_PAN_OS_EDL_Management/Playbooks/playbook-PAN-OS_-_Block_Domain_-_External_Dynamic_List.yml
  Packs/PaloAltoNetworks_PAN_OS_EDL_Management/Playbooks/playbook-PAN-OS_-_Block_IP_and_URL_-_External_Dynamic_List_v2.yml
  Packs/PaloAltoNetworks_PAN_OS_EDL_Management/Playbooks/playbook-PAN-OS_EDL_Setup_v3.yml
  Packs/PaloAltoNetworks_PAN_OS_EDL_Management/ReleaseNotes/1_1_4.md
  Packs/PaloAltoNetworks_PAN_OS_EDL_Management/ReleaseNotes/1_1_5.md
  Packs/PaloAltoNetworks_PAN_OS_EDL_Management/pack_metadata.json
  TestPlaybooks/NonCircleTests/Deprecated/playbook-palo_alto_firewall_test_pb.yml
Labels: docs-approved

#19803 Switching deprecated commands with non deprecated
  Packs/RsaNetwitnessSecurityAnalytics/.pack-ignore
  Packs/RsaNetwitnessSecurityAnalytics/ReleaseNotes/1_0_6.md
  Packs/RsaNetwitnessSecurityAnalytics/Scripts/NetwitnessSAAddEventsToIncident/NetwitnessSAAddEventsToIncident.py
  Packs/RsaNetwitnessSecurityAnalytics/Scripts/NetwitnessSAAddEventsToIncident/NetwitnessSAAddEventsToIncident.yml
  Packs/RsaNetwitnessSecurityAnalytics/Scripts/NetwitnessSAAddEventsToIncident/Pipfile
  Packs/RsaNetwitnessSecurityAnalytics/Scripts/NetwitnessSAAddEventsToIncident/Pipfile.lock
  Packs/RsaNetwitnessSecurityAnalytics/Scripts/NetwitnessSAAddEventsToIncident/README.md
  Packs/RsaNetwitnessSecurityAnalytics/Scripts/NetwitnessSACreateIncident/NetwitnessSACreateIncident.py
  Packs/RsaNetwitnessSecurityAnalytics/Scripts/NetwitnessSACreateIncident/NetwitnessSACreateIncident.yml
  Packs/RsaNetwitnessSecurityAnalytics/Scripts/NetwitnessSACreateIncident/Pipfile
  Packs/RsaNetwitnessSecurityAnalytics/Scripts/NetwitnessSACreateIncident/Pipfile.lock
  Packs/RsaNetwitnessSecurityAnalytics/Scripts/NetwitnessSACreateIncident/README.md
  Packs/RsaNetwitnessSecurityAnalytics/Scripts/NetwitnessSAGetAvailableAssignees/NetwitnessSAGetAvailableAssignees.py
  Packs/RsaNetwitnessSecurityAnalytics/Scripts/NetwitnessSAGetAvailableAssignees/NetwitnessSAGetAvailableAssignees.yml
  Packs/RsaNetwitnessSecurityAnalytics/Scripts/NetwitnessSAGetAvailableAssignees/Pipfile
  Packs/RsaNetwitnessSecurityAnalytics/Scripts/NetwitnessSAGetAvailableAssignees/Pipfile.lock
  Packs/RsaNetwitnessSecurityAnalytics/Scripts/NetwitnessSAGetAvailableAssignees/README.md
  Packs/RsaNetwitnessSecurityAnalytics/Scripts/NetwitnessSAGetComponents/NetwitnessSAGetComponents.py
  Packs/RsaNetwitnessSecurityAnalytics/Scripts/NetwitnessSAGetComponents/NetwitnessSAGetComponents.yml
  Packs/RsaNetwitnessSecurityAnalytics/Scripts/NetwitnessSAGetComponents/Pipfile
  Packs/RsaNetwitnessSecurityAnalytics/Scripts/NetwitnessSAGetComponents/Pipfile.lock
  Packs/RsaNetwitnessSecurityAnalytics/Scripts/NetwitnessSAGetComponents/README.md
  Packs/RsaNetwitnessSecurityAnalytics/Scripts/NetwitnessSAGetEvents/NetwitnessSAGetEvents.py
  Packs/RsaNetwitnessSecurityAnalytics/Scripts/NetwitnessSAGetEvents/NetwitnessSAGetEvents.yml
  Packs/RsaNetwitnessSecurityAnalytics/Scripts/NetwitnessSAGetEvents/Pipfile
  Packs/RsaNetwitnessSecurityAnalytics/Scripts/NetwitnessSAGetEvents/Pipfile.lock
  Packs/RsaNetwitnessSecurityAnalytics/Scripts/NetwitnessSAGetEvents/README.md
  Packs/RsaNetwitnessSecurityAnalytics/Scripts/NetwitnessSAListIncidents/NetwitnessSAListIncidents.py
  Packs/RsaNetwitnessSecurityAnalytics/Scripts/NetwitnessSAListIncidents/NetwitnessSAListIncidents.yml
  Packs/RsaNetwitnessSecurityAnalytics/Scripts/NetwitnessSAListIncidents/Pipfile
  Packs/RsaNetwitnessSecurityAnalytics/Scripts/NetwitnessSAListIncidents/Pipfile.lock
  Packs/RsaNetwitnessSecurityAnalytics/Scripts/NetwitnessSAListIncidents/README.md
  Packs/RsaNetwitnessSecurityAnalytics/Scripts/script-NetwitnessSAGetAvailableAssignees.yml
  Packs/RsaNetwitnessSecurityAnalytics/Scripts/script-NetwitnessSAGetComponents.yml
  Packs/RsaNetwitnessSecurityAnalytics/pack_metadata.json
Labels: docs-approved, ForceMerge

#19905 disable autosave in container settings
  .devcontainer/devcontainer.json
Labels: docs-approved

#19852 MicrosoftGraphMail - add an option to fetch the entire email body
  Packs/MicrosoftGraphListener/Integrations/MicrosoftGraphListener/MicrosoftGraphListener_test.py
  Packs/MicrosoftGraphMail/Integrations/MicrosoftGraphMail/MicrosoftGraphMail.py
  Packs/MicrosoftGraphMail/Integrations/MicrosoftGraphMail/MicrosoftGraphMail.yml
  Packs/MicrosoftGraphMail/Integrations/MicrosoftGraphMail/MicrosoftGraphMail_test.py
  Packs/MicrosoftGraphMail/Integrations/MicrosoftGraphMail/README.md
  Packs/MicrosoftGraphMail/Integrations/MicrosoftGraphMail/test_data/emails_data_full_body
  Packs/MicrosoftGraphMail/Integrations/MicrosoftGraphMail/test_data/expected_incident_full_body
  Packs/MicrosoftGraphMail/ReleaseNotes/1_1_20.md
  Packs/MicrosoftGraphMail/pack_metadata.json
Labels: docs-approved

#19700 Msde polling inhancement
  Packs/MicrosoftDefenderAdvancedThreatProtection/Integrations/MicrosoftDefenderAdvancedThreatProtection/MicrosoftDefenderAdvancedThreatProtection.py
  Packs/MicrosoftDefenderAdvancedThreatProtection/Integrations/MicrosoftDefenderAdvancedThreatProtection/MicrosoftDefenderAdvancedThreatProtection.yml
  Packs/MicrosoftDefenderAdvancedThreatProtection/Integrations/MicrosoftDefenderAdvancedThreatProtection/MicrosoftDefenderAdvancedThreatProtection_test.py
  Packs/MicrosoftDefenderAdvancedThreatProtection/ReleaseNotes/1_11_5.md
  Packs/MicrosoftDefenderAdvancedThreatProtection/pack_metadata.json
Labels: docs-approved

#19827 Cybleevent updates
  Packs/CybleEvents/Integrations/CybleEvents/CybleEvents.py
  Packs/CybleEvents/Integrations/CybleEvents/CybleEvents.yml
  Packs/CybleEvents/Integrations/CybleEvents/CybleEvents_test.py
  Packs/CybleEvents/Integrations/CybleEvents/README.md
  Packs/CybleEvents/ReleaseNotes/1_0_2.md
  Packs/CybleEvents/pack_metadata.json
Labels: Contribution, docs-approved, Partner, Contribution Form Filled

#19900 License header remove
  Packs/AnsibleCiscoNXOS/.pack-ignore
  Packs/AnsibleLinux/.pack-ignore
  Packs/CommonScripts/.pack-ignore
  Packs/OpenPhish/.pack-ignore
Labels: docs-approved

#19932 Added a sleep step to playbook
  Packs/CommonScripts/TestPlaybooks/playbook-Test-IPIndicatorFields.yml
Labels: docs-approved

#19734 Updated JiraV2 integration to combine issueJson with the transition a…
  Packs/Jira/Integrations/JiraV2/JiraV2.py
  Packs/Jira/ReleaseNotes/2_0_7.md
  Packs/Jira/pack_metadata.json
Labels: Contribution, docs-approved, ready-for-instance-test, Contribution Form Filled, Community, pending-contributor

#19880 Remove lint from gitlab
  .gitlab/ci/global.yml
Labels: docs-approved

#19791 Cloudflare waf integration v101
  Packs/CloudflareWAF/Integrations/CloudflareWAF/CloudflareWAF.py
  Packs/CloudflareWAF/Integrations/CloudflareWAF/CloudflareWAF.yml
  Packs/CloudflareWAF/Integrations/CloudflareWAF/CloudflareWAF_test.py
  Packs/CloudflareWAF/Integrations/CloudflareWAF/test_data/ip_list_item_list.json
  Packs/CloudflareWAF/Integrations/CloudflareWAF/test_data/list_zone.json
  Packs/CloudflareWAF/ReleaseNotes/1_0_1.md
  Packs/CloudflareWAF/pack_metadata.json
  Tests/conf.json
  dev-requirements-py3.txt
Labels: Contribution, Partner, Contribution Form Filled, pending-contributor

#16266 Qradar create query and hunting
  Packs/QRadar/Playbooks/playbook-QRadar_Build_Query_and_Search.yml
  Packs/QRadar/Playbooks/playbook-QRadar_Build_Query_and_Search_README.md
  Packs/QRadar/Playbooks/playbook-QRadar_Get_Hunting_Results.yml
  Packs/QRadar/Playbooks/playbook-QRadar_Get_Hunting_Results_README.md
  Packs/QRadar/ReleaseNotes/2_2_0.md
  Packs/QRadar/ReleaseNotes/2_2_1.md
  Packs/QRadar/doc_files/QRadar_Build_Query_and_Search.png
  Packs/QRadar/doc_files/QRadar_Get_Hunting_Results.png
  Packs/QRadar/pack_metadata.json
Labels: docs-approved

#19859 Added inputs for the date field used for filtering
  Packs/SalesforceIndicators/Integrations/SalesforceIndicators/SalesforceIndicators.py
  Packs/SalesforceIndicators/Integrations/SalesforceIndicators/SalesforceIndicators.yml
  Packs/SalesforceIndicators/ReleaseNotes/1_0_8.md
  Packs/SalesforceIndicators/pack_metadata.json
Labels: Contribution, docs-approved, Contribution Form Filled, Community

#19454 Initial commit for iboss integration pack
  Packs/Iboss/.pack-ignore
  Packs/Iboss/.secrets-ignore
  Packs/Iboss/Author_image.png
  Packs/Iboss/Integrations/Iboss/Iboss.py
  Packs/Iboss/Integrations/Iboss/Iboss_description.md
  Packs/Iboss/Integrations/Iboss/Iboss_image.png
  Packs/Iboss/Integrations/Iboss/Iboss_test.py
  Packs/Iboss/Integrations/Iboss/README.md
  Packs/Iboss/Integrations/Iboss/command_examples.txt
  Packs/Iboss/Integrations/Iboss/iboss.yml
  Packs/Iboss/README.md
  Packs/Iboss/pack_metadata.json
Labels: Contribution, docs-approved, Partner, ready-for-instance-test, pending-demo, post-demo, Contribution Form Filled, pending-contributor

#19377 Demisto class
  Documentation/common_server_docs.py
  Packs/ApiModules/Scripts/DemistoClassApiModule/DemistoClassApiModule.py
  Packs/ApiModules/Scripts/DemistoClassApiModule/DemistoClassApiModule.yml
  Packs/ApiModules/Scripts/DemistoClassApiModule/README.md
  Packs/Base/ReleaseNotes/1_31_7.md
  Packs/Base/Scripts/CommonServerPython/CommonServerPython.py
  Packs/Base/pack_metadata.json
Labels: docs-approved

#19779 Update to all latest detonate url playbooks
  Packs/CommonPlaybooks/Playbooks/playbook-Detonate_URL_-_Generic.yml
  Packs/CommonPlaybooks/Playbooks/playbook-Detonate_URL_-_Generic_README.md
  Packs/CommonPlaybooks/ReleaseNotes/2_2_6.md
  Packs/CommonPlaybooks/ReleaseNotes/2_2_8.md
  Packs/CommonPlaybooks/doc_files/Detonate_URL_-_Generic.png
  Packs/CommonPlaybooks/pack_metadata.json
  Packs/HatchingTriage/Playbooks/playbook-Detonate_URL_-_Hatching_Triage.yml
  Packs/HatchingTriage/Playbooks/playbook-Detonate_URL_-_Hatching_Triage_README.md
  Packs/HatchingTriage/ReleaseNotes/1_0_5.md
  Packs/HatchingTriage/doc_files/Detonate_URL_-_Hatching_Triage.png
  Packs/HatchingTriage/pack_metadata.json
  Packs/HybridAnalysis/Playbooks/playbook-Detonate_URL_-_Hybrid_Analysis.yml
  Packs/HybridAnalysis/Playbooks/playbook-Detonate_URL_-_Hybrid_Analysis_README.md
  Packs/HybridAnalysis/ReleaseNotes/1_0_2.md
  Packs/HybridAnalysis/doc_files/Detonate_URL_-_Hybrid_Analysis.png
  Packs/HybridAnalysis/pack_metadata.json
  Packs/fireeye/Playbooks/playbook-Detonate_URL_-_FireEye_AX.yml
  Packs/fireeye/Playbooks/playbook-Detonate_URL_-_FireEye_AX_README.md
  Packs/fireeye/ReleaseNotes/1_0_9.md
  Packs/fireeye/doc_files/Detonate_URL_-_FireEye_AX.png
  Packs/fireeye/pack_metadata.json
Labels: docs-approved

#19904 Xdr query by username
  Packs/ApiModules/Scripts/CoreIRApiModule/CoreIRApiModule.py
  Packs/Core/Integrations/CortexCoreIR/CortexCoreIR.yml
  Packs/Core/Integrations/CortexCoreIR/README.md
  Packs/Core/ReleaseNotes/1_3_3.md
  Packs/Core/pack_metadata.json
  Packs/CortexXDR/Integrations/CortexXDRIR/CortexXDRIR.yml
  Packs/CortexXDR/Integrations/CortexXDRIR/README.md
  Packs/CortexXDR/ReleaseNotes/4_7_2.md
  Packs/CortexXDR/pack_metadata.json
Labels: docs-approved, ForceMerge

#19961 change qualys TPB timeout
  Tests/conf.json
Labels: docs-approved

#19648 Update deprecated and new MITRE + Unit 42 display names
  Packs/FeedMitreAttack/Dashboards/MITRE_ATT&CK.json
  Packs/FeedMitreAttack/Integrations/FeedMitreAttack/FeedMitreAttack.yml
  Packs/FeedMitreAttack/ReleaseNotes/1_2_2.md
  Packs/FeedMitreAttack/pack_metadata.json
  Packs/FeedMitreAttackv2/Dashboards/MITRE_ATT&CK_v2.json
  Packs/FeedMitreAttackv2/Integrations/FeedMitreAttackv2/FeedMitreAttackv2.yml
  Packs/FeedMitreAttackv2/Integrations/FeedMitreAttackv2/FeedMitreAttackv2_description.md
  Packs/FeedMitreAttackv2/Integrations/FeedMitreAttackv2/README.md
  Packs/FeedMitreAttackv2/README.md
  Packs/FeedMitreAttackv2/ReleaseNotes/1_1_3.md
  Packs/FeedMitreAttackv2/TestPlaybooks/FeedMitreAttackv2_test.yml
  Packs/FeedMitreAttackv2/pack_metadata.json
  Packs/FeedUnit42/Integrations/FeedUnit42/FeedUnit42.yml
  Packs/FeedUnit42/ReleaseNotes/1_2_1.md
  Packs/FeedUnit42/pack_metadata.json
  Packs/FeedUnit42v2/Integrations/FeedUnit42v2/FeedUnit42v2_description.md
  Packs/FeedUnit42v2/ReleaseNotes/1_0_13.md
  Packs/FeedUnit42v2/pack_metadata.json
Labels: docs-approved, release-notes-only

#19969 ignore PB110 for PB
  Packs/CommonPlaybooks/.pack-ignore
Labels: docs-approved

#19943 Fixed bug in xdr-file-retrieve which caused failing of the command
  Packs/CortexXDR/Integrations/CortexXDRIR/CortexXDRIR.py
  Packs/CortexXDR/ReleaseNotes/4_7_3.md
  Packs/CortexXDR/pack_metadata.json
Labels: docs-approved

#19972 changing params function in demisto
  Packs/ApiModules/Scripts/DemistoClassApiModule/DemistoClassApiModule.py
Labels: docs-approved

#19953 Fixing phishing attachments bug
  Packs/Phishing/Layouts/layoutscontainer-Phishing_v_3.json
  Packs/Phishing/Playbooks/Process_Email_-_Generic_v2.yml
  Packs/Phishing/ReleaseNotes/3_2_8.md
  Packs/Phishing/doc_files/Process_Email_-_Generic_v2.png
  Packs/Phishing/pack_metadata.json
Labels: docs-approved

#19968 RSS Feed - Fixed an issue in the RSS URL formatting
  Packs/FeedRSS/Integrations/FeedRSS/FeedRSS.py
  Packs/FeedRSS/Integrations/FeedRSS/FeedRSS.yml
  Packs/FeedRSS/Integrations/FeedRSS/FeedRSS_test.py
  Packs/FeedRSS/ReleaseNotes/1_0_8.md
  Packs/FeedRSS/pack_metadata.json
Labels: docs-approved

#19906 Ewso365 sendmail bug fix
  Packs/EWS/Integrations/EWSO365/EWSO365.py
  Packs/EWS/ReleaseNotes/1_12_1.md
  Packs/EWS/pack_metadata.json
Labels: docs-approved

#19975 MITRE dashboard name bug fix
  Packs/FeedMitreAttack/.pack-ignore
  Packs/FeedMitreAttackv2/.pack-ignore
Labels: docs-approved

#19841 TAXII 2 Server - get collection list
  Packs/TAXIIServer/Integrations/TAXII2Server/.secrets-ignore
  Packs/TAXIIServer/Integrations/TAXII2Server/README.md
  Packs/TAXIIServer/Integrations/TAXII2Server/TAXII2Server.py
  Packs/TAXIIServer/Integrations/TAXII2Server/TAXII2Server.yml
  Packs/TAXIIServer/Integrations/TAXII2Server/TAXII2Server_test.py
  Packs/TAXIIServer/Integrations/TAXII2Server/command_examples
  Packs/TAXIIServer/ReleaseNotes/2_0_8.md
  Packs/TAXIIServer/pack_metadata.json
Labels: docs-approved

#19749 Silverfort integration new risk api
  Packs/Silverfort/Integrations/Silverfort/README.md
  Packs/Silverfort/Integrations/Silverfort/Silverfort.py
  Packs/Silverfort/Integrations/Silverfort/Silverfort.yml
  Packs/Silverfort/Integrations/Silverfort/Silverfort_description.md
  Packs/Silverfort/Integrations/Silverfort/Silverfort_test.py
  Packs/Silverfort/ReleaseNotes/2_0_0.md
  Packs/Silverfort/pack_metadata.json
Labels: Contribution, docs-approved, Partner, ready-for-instance-test, Contribution Form Filled, pending-contributor

#19914 More devcontainer small fixes
  .devcontainer/Dockerfile
  .devcontainer/devcontainer.json
  .devcontainer/docker-compose.yml
  .github/CODEOWNERS
Labels: docs-approved

#19989 Added "no tests" to MITRE v1 (deprecated) integration
  Packs/FeedMitreAttack/Integrations/FeedMitreAttack/FeedMitreAttack.yml
Labels: docs-approved

#19659 dev-task - Remove excessive error traceback printing - Packs T U V
  Packs/TOPdesk/Integrations/TOPdesk/TOPdesk.py
  Packs/TOPdesk/Integrations/TOPdesk/TOPdesk.yml
  Packs/TOPdesk/ReleaseNotes/1_2_2.md
  Packs/TOPdesk/pack_metadata.json
  Packs/TheHiveProject/Integrations/TheHiveProject/TheHiveProject.py
  Packs/TheHiveProject/Integrations/TheHiveProject/TheHiveProject.yml
  Packs/TheHiveProject/ReleaseNotes/1_1_12.md
  Packs/TheHiveProject/pack_metadata.json
  Packs/ThreatGrid/Integrations/FeedCiscoSecureMalwareAnalytics/FeedCiscoSecureMalwareAnalytics.py
  Packs/ThreatGrid/Integrations/FeedCiscoSecureMalwareAnalytics/FeedCiscoSecureMalwareAnalytics.yml
  Packs/ThreatGrid/ReleaseNotes/1_2_13.md
  Packs/ThreatGrid/pack_metadata.json
  Packs/Threat_Crowd/Integrations/ThreatCrowd_v2/ThreatCrowd_v2.py
  Packs/Threat_Crowd/Integrations/ThreatCrowd_v2/ThreatCrowd_v2.yml
  Packs/Threat_Crowd/ReleaseNotes/2_0_7.md
  Packs/Threat_Crowd/pack_metadata.json
  Packs/Tidy/Integrations/Tidy/Tidy.py
  Packs/Tidy/Integrations/Tidy/Tidy.yml
  Packs/Tidy/ReleaseNotes/1_0_8.md
  Packs/Tidy/pack_metadata.json
  Packs/TrendMicroCAS/Integrations/TrendMicroCAS/TrendMicroCAS.py
  Packs/TrendMicroCAS/Integrations/TrendMicroCAS/TrendMicroCAS.yml
  Packs/TrendMicroCAS/ReleaseNotes/1_0_12.md
  Packs/TrendMicroCAS/pack_metadata.json
  Packs/TrendMicroDeepSecurity/Integrations/TrendMicroDeepSecurity/TrendMicroDeepSecurity.py
  Packs/TrendMicroDeepSecurity/Integrations/TrendMicroDeepSecurity/TrendMicroDeepSecurity.yml
  Packs/TrendMicroDeepSecurity/ReleaseNotes/1_0_3.md
  Packs/TrendMicroDeepSecurity/pack_metadata.json
  Packs/Tripwire/Integrations/Tripwire/Tripwire.py
  Packs/Tripwire/Integrations/Tripwire/Tripwire.yml
  Packs/Tripwire/ReleaseNotes/1_0_13.md
  Packs/Tripwire/pack_metadata.json
  Packs/Troubleshoot/ReleaseNotes/2_0_5.md
  Packs/Troubleshoot/Scripts/TroubleshootAggregateResults/TroubleshootAggregateResults.py
  Packs/Troubleshoot/Scripts/TroubleshootAggregateResults/TroubleshootAggregateResults.yml
  Packs/Troubleshoot/pack_metadata.json
  Packs/Unit42Intel/Integrations/FeedUnit42IntelObjects/FeedUnit42IntelObjects.py
  Packs/Unit42Intel/Integrations/FeedUnit42IntelObjects/FeedUnit42IntelObjects.yml
  Packs/Unit42Intel/ReleaseNotes/1_0_4.md
  Packs/Unit42Intel/pack_metadata.json
  Packs/VMwareWorkspaceONEUEM/Integrations/VMwareWorkspaceONEUEM/VMwareWorkspaceONEUEM.py
  Packs/VMwareWorkspaceONEUEM/Integrations/VMwareWorkspaceONEUEM/VMwareWorkspaceONEUEM.yml
  Packs/VMwareWorkspaceONEUEM/ReleaseNotes/1_0_3.md
  Packs/VMwareWorkspaceONEUEM/pack_metadata.json
Labels: docs-approved, ForceMerge

#19066 Microsoft look back
  Packs/Active_Directory_Query/ReleaseNotes/1_4_11.md
  Packs/MicrosoftCloudAppSecurity/Integrations/MicrosoftCloudAppSecurity/MicrosoftCloudAppSecurity.py
  Packs/MicrosoftCloudAppSecurity/Integrations/MicrosoftCloudAppSecurity/MicrosoftCloudAppSecurity.yml
  Packs/MicrosoftCloudAppSecurity/Integrations/MicrosoftCloudAppSecurity/MicrosoftCloudAppSecurity_test.py
  Packs/MicrosoftCloudAppSecurity/Integrations/MicrosoftCloudAppSecurity/README.md
  Packs/MicrosoftCloudAppSecurity/ReleaseNotes/2_0_1.md
  Packs/MicrosoftCloudAppSecurity/pack_metadata.json
  Tests/known_words.txt
Labels: docs-approved

#19988 adding ignore error
  Packs/ApiModules/Scripts/DemistoClassApiModule/DemistoClassApiModule.py
Labels: docs-approved

#19856 Parameterized server URL
  Packs/CrowdStrikeFalconSandbox/Integrations/CrowdStrikeFalconSandboxV2/CrowdStrikeFalconSandboxV2.py
  Packs/CrowdStrikeFalconSandbox/Integrations/CrowdStrikeFalconSandboxV2/CrowdStrikeFalconSandboxV2.yml
  Packs/CrowdStrikeFalconSandbox/Integrations/CrowdStrikeFalconSandboxV2/README.md
  Packs/CrowdStrikeFalconSandbox/ReleaseNotes/2_0_3.json
  Packs/CrowdStrikeFalconSandbox/ReleaseNotes/2_0_3.md
  Packs/CrowdStrikeFalconSandbox/pack_metadata.json
Labels: Contribution, ready-for-instance-test, Contribution Form Filled, Community

#19747 Docker Engine API improvements
  Packs/DevSecOps/Integrations/DockerEngine/DockerEngine.py
  Packs/DevSecOps/Integrations/DockerEngine/DockerEngine.yml
  Packs/DevSecOps/Integrations/DockerEngine/DockerEngine_description.md
  Packs/DevSecOps/Integrations/DockerEngine/README.md
  Packs/DevSecOps/Integrations/DockerEngine/command_examples
  Packs/DevSecOps/ReleaseNotes/1_1_0.md
  Packs/DevSecOps/pack_metadata.json
Labels: Contribution, ready-for-instance-test, Contribution Form Filled, Community

#19948 pan-os-get-url-category bug fix
  Packs/PAN-OS/Integrations/Panorama/Panorama.py
  Packs/PAN-OS/Integrations/Panorama/Panorama_test.py
  Packs/PAN-OS/ReleaseNotes/1_14_8.md
  Packs/PAN-OS/pack_metadata.json
Labels: bug, docs-approved

#19970 Update file enrichment generic v2 playbook
  Packs/CommonPlaybooks/.pack-ignore
  Packs/CommonPlaybooks/Playbooks/playbook-File_Enrichment_-_Generic_v2.yml
  Packs/CommonPlaybooks/Playbooks/playbook-File_Enrichment_-_Generic_v2_README.md
  Packs/CommonPlaybooks/ReleaseNotes/2_2_9.md
  Packs/CommonPlaybooks/doc_files/File_Enrichment_-_Generic_v2.png
  Packs/CommonPlaybooks/pack_metadata.json
  Packs/VirusTotal/Playbooks/File_Enrichment_-_Virus_Total_v3.yml
  Packs/VirusTotal/Playbooks/File_Enrichment_-_Virus_Total_v3_README.md
  Packs/VirusTotal/ReleaseNotes/2_4_4.md
  Packs/VirusTotal/doc_files/File_Enrichment_-_Virus_Total_(API_v3).png
  Packs/VirusTotal/pack_metadata.json
Labels: docs-approved

#19929 Added system proxy configuration option
  Packs/TrendMicroVisionOne/Integrations/TrendMicroVisionOne/TrendMicroVisionOne.py
  Packs/TrendMicroVisionOne/Integrations/TrendMicroVisionOne/TrendMicroVisionOne.yml
  Packs/TrendMicroVisionOne/Integrations/TrendMicroVisionOne/TrendMicroVisionOne_test.py
  Packs/TrendMicroVisionOne/ReleaseNotes/1_2_0.md
  Packs/TrendMicroVisionOne/pack_metadata.json
Labels: Contribution, docs-approved, Partner, ready-for-instance-test, Contribution Form Filled, pending-contributor

#19850 Support for API auth
  Packs/ANYRUN/Integrations/ANYRUN/ANYRUN.py
  Packs/ANYRUN/Integrations/ANYRUN/ANYRUN.yml
  Packs/ANYRUN/Integrations/ANYRUN/ANYRUN_description.md
  Packs/ANYRUN/Integrations/ANYRUN/README.md
  Packs/ANYRUN/ReleaseNotes/1_0_10.md
  Packs/ANYRUN/pack_metadata.json
Labels: Contribution, docs-approved, ready-for-instance-test, Contribution Form Filled, Community, pending-contributor

#20010 poetry update (release SDK)
  .hooks/bootstrap
  poetry.lock
  poetry.toml
  pyproject.toml
Labels: docs-approved

#19990 Service now - add tag to mirrored attachments
  Packs/ServiceNow/Integrations/ServiceNowv2/README.md
  Packs/ServiceNow/Integrations/ServiceNowv2/ServiceNowv2.py
  Packs/ServiceNow/Integrations/ServiceNowv2/ServiceNowv2.yml
  Packs/ServiceNow/Integrations/ServiceNowv2/ServiceNowv2_test.py
  Packs/ServiceNow/ReleaseNotes/2_3_15.md
  Packs/ServiceNow/pack_metadata.json
Labels: docs-approved

#20017 Rename iboss.yml to Iboss.yml
  Packs/Iboss/Integrations/Iboss/Iboss.yml
  Packs/Iboss/ReleaseNotes/1_0_1.md
  Packs/Iboss/pack_metadata.json
Labels: docs-approved

#19959 SymanteecMSS: switch docker image
  Packs/SymantecMSS/Integrations/SymantecMSS/SymantecMSS.yml
  Packs/SymantecMSS/ReleaseNotes/1_0_4.md
  Packs/SymantecMSS/pack_metadata.json
Labels: docs-approved

#19947 Fixed an issue where it doesn't return any errors when failed to pars…
  Packs/PcapAnalysis/ReleaseNotes/2_4_4.md
  Packs/PcapAnalysis/Scripts/PcapConvert/PcapConvert.py
  Packs/PcapAnalysis/Scripts/PcapExtractStreams/PcapExtractStreams.py
  Packs/PcapAnalysis/pack_metadata.json
Labels: Contribution, Contribution Form Filled, Community

#19595 Stix export upgrade
  Packs/CommonScripts/ReleaseNotes/1_7_13.md
  Packs/CommonScripts/Scripts/StixCreator/StixCreator.py
  Packs/CommonScripts/Scripts/StixCreator/StixCreator.yml
  Packs/CommonScripts/TestPlaybooks/playbook-TestStixCreator.yml
  Packs/CommonScripts/pack_metadata.json
Labels: docs-approved

#19879 Add misp add email command
  Packs/MISP/.secrets-ignore
  Packs/MISP/Integrations/MISPV3/MISPV3.py
  Packs/MISP/Integrations/MISPV3/MISPV3.yml
  Packs/MISP/Integrations/MISPV3/MISPV3_test.py
  Packs/MISP/Integrations/MISPV3/README.md
  Packs/MISP/Integrations/MISPV3/command_examples
  Packs/MISP/Integrations/MISPV3/test_data/response_mock_add_email_object_test.json
  Packs/MISP/Integrations/MISPV3/test_data/test_add_email_object_case_1.eml
  Packs/MISP/Integrations/MISPV3/test_data/test_add_email_object_case_2.eml
  Packs/MISP/Integrations/MISPV3/test_data/test_add_email_object_case_3.eml
  Packs/MISP/ReleaseNotes/2_1_9.md
  Packs/MISP/TestPlaybooks/MISP_V3_Test.yml
  Packs/MISP/pack_metadata.json
Labels: docs-approved

#20029 Removed unnecessary proxy constructor arg
  Packs/TrendMicroVisionOne/Integrations/TrendMicroVisionOne/TrendMicroVisionOne.py
  Packs/TrendMicroVisionOne/ReleaseNotes/1_2_1.md
  Packs/TrendMicroVisionOne/pack_metadata.json
  Tests/known_words.txt
Labels: docs-approved, Partner

#20008 Graph mail fix user id
  Packs/MicrosoftGraphMail/.pack-ignore
  Packs/MicrosoftGraphMail/Integrations/MicrosoftGraphMail/MicrosoftGraphMail.yml
  Packs/MicrosoftGraphMail/ReleaseNotes/1_1_21.md
  Packs/MicrosoftGraphMail/pack_metadata.json
Labels: docs-approved

#20039 fix docs of VT PB
  Packs/VirusTotal/Playbooks/File_Enrichment_-_Virus_Total_v3_README.md
  Packs/VirusTotal/doc_files/File_Enrichment_-_Virus_Total_API_v3.png
Labels: docs-approved

#20041 Moved ParseEmailFilesV2 from beta to GA.
  Packs/CommonScripts/ReleaseNotes/1_7_14.md
  Packs/CommonScripts/Scripts/ParseEmailFilesV2/ParseEmailFilesV2.yml
  Packs/CommonScripts/pack_metadata.json
Labels: docs-approved

#19971 QRadar fixes
  Packs/QRadar/.secrets-ignore
  Packs/QRadar/Integrations/QRadar_v3/QRadar_v3.py
  Packs/QRadar/Integrations/QRadar_v3/QRadar_v3.yml
  Packs/QRadar/Integrations/QRadar_v3/QRadar_v3_test.py
  Packs/QRadar/Integrations/QRadar_v3/README.md
  Packs/QRadar/Integrations/QRadar_v3/command_examples.txt
  Packs/QRadar/Integrations/QRadar_v3/test_data/command_test_data.json
  Packs/QRadar/ReleaseNotes/2_2_3.md
  Packs/QRadar/TestPlaybooks/QRadar_v3-test.yml
  Packs/QRadar/pack_metadata.json
Labels: docs-approved

#20045 The fetch-incidents command did not work.
  Packs/AWS-SQS/Integrations/AWS-SQS/AWS-SQS.py
  Packs/AWS-SQS/ReleaseNotes/1_2_11.md
  Packs/AWS-SQS/pack_metadata.json
Labels: docs-approved

#19665 Aburt-wordpress
  Packs/Wordpress/.pack-ignore
  Packs/Wordpress/.secrets-ignore
  Packs/Wordpress/Author_image.png
  Packs/Wordpress/Integrations/Wordpress/Pipfile
  Packs/Wordpress/Integrations/Wordpress/Pipfile.lock
  Packs/Wordpress/Integrations/Wordpress/README.md
  Packs/Wordpress/Integrations/Wordpress/Wordpress.py
  Packs/Wordpress/Integrations/Wordpress/Wordpress.yml
  Packs/Wordpress/Integrations/Wordpress/Wordpress_description.md
  Packs/Wordpress/Integrations/Wordpress/Wordpress_image.png
  Packs/Wordpress/Integrations/Wordpress/command_examples
  Packs/Wordpress/README.md
  Packs/Wordpress/pack_metadata.json
Labels: Contribution, docs-approved, ready-for-instance-test, Contribution Form Filled, Community, pending-contributor

#19825 ADiaz-Drift
  Packs/Drift/.pack-ignore
  Packs/Drift/.secrets-ignore
  Packs/Drift/Integrations/Drift/Drift.py
  Packs/Drift/Integrations/Drift/Drift.yml
  Packs/Drift/Integrations/Drift/Drift_description.md
  Packs/Drift/Integrations/Drift/Drift_image.png
  Packs/Drift/Integrations/Drift/Pipfile
  Packs/Drift/Integrations/Drift/Pipfile.lock
  Packs/Drift/Integrations/Drift/README.md
  Packs/Drift/Integrations/Drift/command_examples
  Packs/Drift/README.md
  Packs/Drift/pack_metadata.json
  Packs/Iboss/Integrations/Iboss/iboss.yml
Labels: Contribution, docs-approved, ready-for-instance-test, Contribution Form Filled, Community

#20059 update pyproject.tml to use a specific revision of demiso-sdk
  poetry.lock
  pyproject.toml
Labels: docs-approved

#20061 Checkout poetry files when they are changed in master
  .circleci/config.yml
  .gitlab/ci/global.yml
  Tests/scripts/is_file_up_to_date.sh
Labels: docs-approved

#20038 devcontainer to latest sdk + powershell
  .devcontainer/Dockerfile
  .devcontainer/devcontainer.json
Labels: docs-approved

#20048 Phishing att fix 2
  Packs/Phishing/Playbooks/Process_Email_-_Generic_v2.yml
  Packs/Phishing/ReleaseNotes/3_2_9.md
  Packs/Phishing/pack_metadata.json
Labels: docs-approved, release-notes-only

#19927 [Carbon Black Enterprise Response] Netconn parser
  Packs/Carbon_Black_Enterprise_Response/.secrets-ignore
  Packs/Carbon_Black_Enterprise_Response/Integrations/CarbonBlackResponseV2/CarbonBlackResponseV2.py
  Packs/Carbon_Black_Enterprise_Response/Integrations/CarbonBlackResponseV2/CarbonBlackResponseV2.yml
  Packs/Carbon_Black_Enterprise_Response/Integrations/CarbonBlackResponseV2/CarbonBlackResponseV2_test.py
  Packs/Carbon_Black_Enterprise_Response/Integrations/CarbonBlackResponseV2/Pipfile
  Packs/Carbon_Black_Enterprise_Response/Integrations/CarbonBlackResponseV2/Pipfile.lock
  Packs/Carbon_Black_Enterprise_Response/ReleaseNotes/2_1_18.md
  Packs/Carbon_Black_Enterprise_Response/pack_metadata.json
Labels: Contribution, docs-approved, ready-for-instance-test, Contribution Form Filled, Community, pending-contributor

#20063 Config option to disable cert validate
  Packs/TrendMicroVisionOne/Integrations/TrendMicroVisionOne/README.md
  Packs/TrendMicroVisionOne/Integrations/TrendMicroVisionOne/TrendMicroVisionOne.py
  Packs/TrendMicroVisionOne/Integrations/TrendMicroVisionOne/TrendMicroVisionOne.yml
  Packs/TrendMicroVisionOne/Integrations/TrendMicroVisionOne/TrendMicroVisionOne_test.py
  Packs/TrendMicroVisionOne/ReleaseNotes/1_2_2.md
  Packs/TrendMicroVisionOne/pack_metadata.json
Labels: Contribution, docs-approved, Partner, ready-for-instance-test, Contribution Form Filled

#19475 [EDL] Add XSOAR - XSIAM specific docs
  Packs/EDL/Integrations/EDL/EDL_description.md
  Packs/EDL/README.md
  Packs/EDL/ReleaseNotes/3_1_6.md
  Packs/EDL/pack_metadata.json
Labels: docs-approved

#19903 change description indicator field to markdown
  Packs/CommonTypes/.pack-ignore
  Packs/CommonTypes/IndicatorFields/incidentfield-description.json
  Packs/CommonTypes/IndicatorFields/incidentfield-groups.json
  Packs/CommonTypes/IndicatorFields/incidentfield-shortdescription.json
  Packs/CommonTypes/IndicatorFields/indicatorfield-applications.json
  Packs/CommonTypes/ReleaseNotes/3_2_40.md
  Packs/CommonTypes/pack_metadata.json
Labels: docs-approved, ForceMerge

#19743 Cleanups: remove old Phishing incident type
  Packs/Phishing/IncidentTypes/Phishing.json
  Packs/Phishing/IncidentTypes/incidenttype-Phishing_6.0.json
Labels: docs-approved, ForceMerge

#20077 add malware video
  Packs/MalwareInvestigationAndResponse/pack_metadata.json
Labels: docs-approved

#19854 Fix contributors
  Packs/EWS/CONTRIBUTORS.json
  Packs/EWS/CONTRIBUTORS.md
  Packs/EmailCommunication/CONTRIBUTORS.json
  Packs/EmailCommunication/CONTRIBUTORS.md
  Packs/PAN-OS/CONTRIBUTORS.json
  Packs/PAN-OS/CONTRIBUTORS.md
  Packs/PANOSPolicyOptimizer/CONTRIBUTORS.json
  Packs/PANOSPolicyOptimizer/CONTRIBUTORS.md
  Packs/TOPdesk/CONTRIBUTORS.json
  Packs/TOPdesk/CONTRIBUTORS.md
Labels: docs-approved, ForceMerge

#19755 Supporting token auth JAMFV2
  Packs/jamf/Integrations/jamfV2/jamfV2.py
  Packs/jamf/Integrations/jamfV2/jamfV2_description.md
  Packs/jamf/ReleaseNotes/2_1_0.md
  Packs/jamf/pack_metadata.json
Labels: docs-approved

#19996 Xdr malware fixes
  Packs/CortexXDR/Playbooks/playbook-Cortex_XDR_-_Endpoint_Investigation.yml
  Packs/CortexXDR/Playbooks/playbook-Cortex_XDR_-_Endpoint_Investigation_README.md
  Packs/CortexXDR/Playbooks/playbook-Cortex_XDR_-_False_Positive_Incident_Handling.yml
  Packs/CortexXDR/Playbooks/playbook-Cortex_XDR_-_False_Positive_Incident_Handling_README.md
  Packs/CortexXDR/Playbooks/playbook-Cortex_XDR_-_Get_File_Path_from_alerts_by_hash.yml
  Packs/CortexXDR/Playbooks/playbook-Cortex_XDR_-_Get_File_Path_from_alerts_by_hash_README.md
  Packs/CortexXDR/Playbooks/playbook-Cortex_XDR_-_Retrieve_File_by_sha256.yml
  Packs/CortexXDR/Playbooks/playbook-Cortex_XDR_-_Retrieve_File_by_sha256_README.md
  Packs/CortexXDR/Playbooks/playbook-Cortex_XDR_-_True_Positive_Incident_Handling.yml
  Packs/CortexXDR/Playbooks/playbook-Cortex_XDR_-_True_Positive_Incident_Handling_README.md
  Packs/CortexXDR/Playbooks/playbook-Cortex_XDR_Malware_-_Incident_Enrichment.yml
  Packs/CortexXDR/Playbooks/playbook-Cortex_XDR_Malware_-_Incident_Enrichment_README.md
  Packs/CortexXDR/Playbooks/playbook-Cortex_XDR_Malware_-_Investigation_And_Response.yml
  Packs/CortexXDR/Playbooks/playbook-Cortex_XDR_Malware_-_Investigation_And_Response_README.md
  Packs/CortexXDR/ReleaseNotes/4_8_0.md
  Packs/CortexXDR/doc_files/Cortex_XDR_-_Get_File_Path_from_alerts_by_hash.png
  Packs/CortexXDR/doc_files/Cortex_XDR_-_Retrieve_File_by_sha256.png
  Packs/CortexXDR/doc_files/Cortex_XDR_Malware_-_Investigation_And_Response.png
  Packs/CortexXDR/pack_metadata.json
Labels: docs-approved

#19901 Added 6.8 server version and removed 6.2 (EOL)
  .gitlab/ci/bucket-upload.yml
  .gitlab/ci/on-push.yml
  Tests/Marketplace/configure_and_install_packs.py
  Tests/scripts/collect_tests_and_content_packs.py
  Tests/scripts/infrastructure_tests/test_collect_tests_and_content_packs.py
Labels: docs-approved

#19772 Filter packs by minServerVersion upload flow
  Tests/Marketplace/configure_and_install_packs.py
Labels: docs-approved

#19991 will not create new incidents on update
  Packs/PrismaCloud/Integrations/RedLock/RedLock.py
  Packs/PrismaCloud/Integrations/RedLock/RedLock.yml
  Packs/PrismaCloud/ReleaseNotes/2_0_14.md
  Packs/PrismaCloud/pack_metadata.json
Labels: bug, docs-approved, release-notes-only

#20094 Removed the unsupported *fromServerVersion* field from Incident Fields
  Packs/CortexXDR/IncidentFields/XDR_Modification_time.json
  Packs/CortexXDR/ReleaseNotes/4_8_1.md
  Packs/CortexXDR/pack_metadata.json
Labels: docs-approved

#20087 Private build - Copying index.zip and printing logs
  Tests/private_build/upload_packs_private.py
  Tests/scripts/prepare_private_content_packs_for_testing.sh
Labels: docs-approved

#19832 Cyblethreatintel updates
  Packs/CybleThreatIntel/Integrations/CybleThreatIntel/CybleThreatIntel.py
  Packs/CybleThreatIntel/Integrations/CybleThreatIntel/CybleThreatIntel.yml
  Packs/CybleThreatIntel/Integrations/CybleThreatIntel/CybleThreatIntel_description.md
  Packs/CybleThreatIntel/Integrations/CybleThreatIntel/CybleThreatIntel_test.py
  Packs/CybleThreatIntel/Integrations/CybleThreatIntel/README.md
  Packs/CybleThreatIntel/Integrations/CybleThreatIntel/test_data/collection.json
  Packs/CybleThreatIntel/Integrations/CybleThreatIntel/test_data/cyble_threat_intel.json
  Packs/CybleThreatIntel/Integrations/CybleThreatIntel/test_data/data.json
  Packs/CybleThreatIntel/Integrations/CybleThreatIntel/test_data/data.xml
  Packs/CybleThreatIntel/Integrations/CybleThreatIntel/test_data/data_err.xml
  Packs/CybleThreatIntel/Integrations/CybleThreatIntel/test_data/input.json
  Packs/CybleThreatIntel/Integrations/CybleThreatIntel/test_data/results.json
  Packs/CybleThreatIntel/Integrations/CybleThreatIntel/test_data/test.json
  Packs/CybleThreatIntel/README.md
  Packs/CybleThreatIntel/ReleaseNotes/2_0_0.json
  Packs/CybleThreatIntel/ReleaseNotes/2_0_0.md
  Packs/CybleThreatIntel/pack_metadata.json
Labels: Contribution, Partner, ready-for-instance-test, Contribution Form Filled, pending-contributor

#20054 Msopof contrib microsoft defender advanced threat protection - machine offboard
  Packs/MicrosoftDefenderAdvancedThreatProtection/Integrations/MicrosoftDefenderAdvancedThreatProtection/MicrosoftDefenderAdvancedThreatProtection.py
  Packs/MicrosoftDefenderAdvancedThreatProtection/Integrations/MicrosoftDefenderAdvancedThreatProtection/MicrosoftDefenderAdvancedThreatProtection.yml
  Packs/MicrosoftDefenderAdvancedThreatProtection/Integrations/MicrosoftDefenderAdvancedThreatProtection/MicrosoftDefenderAdvancedThreatProtection_description.md
  Packs/MicrosoftDefenderAdvancedThreatProtection/Integrations/MicrosoftDefenderAdvancedThreatProtection/MicrosoftDefenderAdvancedThreatProtection_test.py
  Packs/MicrosoftDefenderAdvancedThreatProtection/Integrations/MicrosoftDefenderAdvancedThreatProtection/README.md
  Packs/MicrosoftDefenderAdvancedThreatProtection/ReleaseNotes/1_11_6.md
  Packs/MicrosoftDefenderAdvancedThreatProtection/pack_metadata.json
Labels: Contribution, docs-approved, ready-for-instance-test, Contribution Form Filled, Community, pending-contributor

#20086 pan-os-get-url-category fix dbot score returning multiple values for the same URL
  Packs/PAN-OS/Integrations/Panorama/Panorama.py
  Packs/PAN-OS/Integrations/Panorama/Panorama_test.py
  Packs/PAN-OS/ReleaseNotes/1_14_10.md
  Packs/PAN-OS/pack_metadata.json
Labels: docs-approved

#19820 Fix for the private build
  Tests/configure_and_test_integration_instances.py
  Tests/tests/configure_and_test_integration_instances_test.py
Labels: docs-approved

#20099 Update marketplace name (lowercase), update author from dev to compan…
  Packs/Iboss/.pack-ignore
  Packs/Iboss/ReleaseNotes/1_0_2.md
  Packs/Iboss/pack_metadata.json
Labels: Contribution, Partner, ready-for-instance-test, Contribution Form Filled

#20107 update rn for CommonTypes 3.2.40
  Packs/CommonTypes/ReleaseNotes/3_2_40.md
Labels: docs-approved

#20081 Added filter to the mapping rules
  Packs/DuoAdminApi/ModelingRules/DuoModelingRule/DuoModelingRule.xif
  Packs/DuoAdminApi/ReleaseNotes/3_0_1.md
  Packs/DuoAdminApi/pack_metadata.json
Labels: docs-approved

#20113 export IOC service - better readme
  Packs/EDL/README.md
Labels: docs-approved

#20095 ParseEmailFilesV2 Update Docker Image
  Packs/CommonScripts/ReleaseNotes/1_7_15.md
  Packs/CommonScripts/Scripts/ParseEmailFilesV2/ParseEmailFilesV2.yml
  Packs/CommonScripts/pack_metadata.json
Labels: docs-approved, release-notes-only

#20085 Crowdstrike Falcon bug fix
  Packs/CrowdStrikeIntel/Integrations/CrowdStrikeFalconIntel_v2/CrowdStrikeFalconIntel_v2.py
  Packs/CrowdStrikeIntel/Integrations/CrowdStrikeFalconIntel_v2/CrowdStrikeFalconIntel_v2.yml
  Packs/CrowdStrikeIntel/Integrations/CrowdStrikeFalconIntel_v2/CrowdStrikeFalconIntel_v2_test.py
  Packs/CrowdStrikeIntel/ReleaseNotes/2_0_17.md
  Packs/CrowdStrikeIntel/pack_metadata.json
Labels: docs-approved

#20122 hide deprecated non relevant packs
  Packs/FeedMitreAttack/pack_metadata.json
  Packs/LogRhythm/pack_metadata.json
  Packs/McAfee_ESM-v10/pack_metadata.json
  Packs/MicrosoftPolicyAndCompliance/pack_metadata.json
  Packs/Recorded_Future/pack_metadata.json
Labels: docs-approved, ForceMerge

#19676 [greynoise-266] Add ability to set Integration Reliability Value
  Packs/GreyNoise/.secrets-ignore
  Packs/GreyNoise/Integrations/GreyNoise/GreyNoise.py
  Packs/GreyNoise/Integrations/GreyNoise/GreyNoise.yml
  Packs/GreyNoise/Integrations/GreyNoise/GreyNoise_test.py
  Packs/GreyNoise/Integrations/GreyNoise/test_data/input_data.py
  Packs/GreyNoise/Integrations/GreyNoise_Community/GreyNoise_Community.py
  Packs/GreyNoise/Integrations/GreyNoise_Community/GreyNoise_Community.yml
  Packs/GreyNoise/Integrations/GreyNoise_Community/GreyNoise_Community_test.py
  Packs/GreyNoise/Integrations/GreyNoise_Community/test_data/input_data.py
  Packs/GreyNoise/README.md
  Packs/GreyNoise/ReleaseNotes/1_2_0.md
  Packs/GreyNoise/pack_metadata.json
Labels: Contribution, docs-approved, Partner, ready-for-instance-test, Contribution Form Filled, pending-contributor

#20056 Rasterize - pass html as UTF-8
  Packs/rasterize/Integrations/rasterize/rasterize.py
  Packs/rasterize/Integrations/rasterize/rasterize.yml
  Packs/rasterize/ReleaseNotes/1_2_1.md
  Packs/rasterize/pack_metadata.json
Labels: bug, docs-approved, release-notes-only

#20110 Pushing update to re-add missing integration
  poetry.lock
  pyproject.toml
Labels: docs-approved, ForceMerge

#19928 Feat(Cortex XSOAR/content): Add SEKOIA.IO integration
  Packs/SEKOIAIntelligenceCenter/.pack-ignore
  Packs/SEKOIAIntelligenceCenter/.secrets-ignore
  Packs/SEKOIAIntelligenceCenter/Author_image.png
  Packs/SEKOIAIntelligenceCenter/Integrations/SEKOIAIntelligenceCenter/Pipfile
  Packs/SEKOIAIntelligenceCenter/Integrations/SEKOIAIntelligenceCenter/Pipfile.lock
  Packs/SEKOIAIntelligenceCenter/Integrations/SEKOIAIntelligenceCenter/README.md
  Packs/SEKOIAIntelligenceCenter/Integrations/SEKOIAIntelligenceCenter/SEKOIAIntelligenceCenter.md
  Packs/SEKOIAIntelligenceCenter/Integrations/SEKOIAIntelligenceCenter/SEKOIAIntelligenceCenter.py
  Packs/SEKOIAIntelligenceCenter/Integrations/SEKOIAIntelligenceCenter/SEKOIAIntelligenceCenter.yml
  Packs/SEKOIAIntelligenceCenter/Integrations/SEKOIAIntelligenceCenter/SEKOIAIntelligenceCenter_image.png
  Packs/SEKOIAIntelligenceCenter/Integrations/SEKOIAIntelligenceCenter/SEKOIAIntelligenceCenter_test.py
  Packs/SEKOIAIntelligenceCenter/Integrations/SEKOIAIntelligenceCenter/command_examples
  Packs/SEKOIAIntelligenceCenter/Integrations/SEKOIAIntelligenceCenter/test_data/indicator.json
  Packs/SEKOIAIntelligenceCenter/Integrations/SEKOIAIntelligenceCenter/test_data/indicator_context_domain_name.json
  Packs/SEKOIAIntelligenceCenter/Integrations/SEKOIAIntelligenceCenter/test_data/indicator_context_email.json
  Packs/SEKOIAIntelligenceCenter/Integrations/SEKOIAIntelligenceCenter/test_data/indicator_context_file.json
  Packs/SEKOIAIntelligenceCenter/Integrations/SEKOIAIntelligenceCenter/test_data/indicator_context_filename.json
  Packs/SEKOIAIntelligenceCenter/Integrations/SEKOIAIntelligenceCenter/test_data/indicator_context_ip.json
  Packs/SEKOIAIntelligenceCenter/Integrations/SEKOIAIntelligenceCenter/test_data/indicator_context_unknown.json
  Packs/SEKOIAIntelligenceCenter/Integrations/SEKOIAIntelligenceCenter/test_data/indicator_context_url.json
  Packs/SEKOIAIntelligenceCenter/Integrations/SEKOIAIntelligenceCenter/test_data/indicator_unknown.json
  Packs/SEKOIAIntelligenceCenter/Integrations/SEKOIAIntelligenceCenter/test_data/observable.json
  Packs/SEKOIAIntelligenceCenter/Integrations/SEKOIAIntelligenceCenter/test_data/observable_unknown.json
  Packs/SEKOIAIntelligenceCenter/README.md
  Packs/SEKOIAIntelligenceCenter/pack_metadata.json
Labels: Contribution, docs-approved, Partner, ready-for-instance-test, Contribution Form Filled, pending-contributor

#20018 add 'aws-ec2-authorize-security-group-egress-rule' command
  Packs/AWS-EC2/Integrations/AWS-EC2/AWS-EC2.py
  Packs/AWS-EC2/Integrations/AWS-EC2/AWS-EC2.yml
  Packs/AWS-EC2/Integrations/AWS-EC2/AWS-EC2_test.py
  Packs/AWS-EC2/Integrations/AWS-EC2/README.md
  Packs/AWS-EC2/Integrations/AWS-EC2/command_examples.txt
  Packs/AWS-EC2/ReleaseNotes/1_2_15.md
  Packs/AWS-EC2/TestPlaybooks/playbook-AWS-EC2Test_actions.yml
  Packs/AWS-EC2/pack_metadata.json
Labels: docs-approved, ForceMerge

#20053 Azure sentinel bug fix
  Packs/AzureSentinel/Integrations/AzureSentinel/AzureSentinel.py
  Packs/AzureSentinel/Integrations/AzureSentinel/AzureSentinel_test.py
  Packs/AzureSentinel/ReleaseNotes/1_3_15.md
  Packs/AzureSentinel/pack_metadata.json
Labels: bug, docs-approved, release-notes-only

#20158 update file names
  Packs/AzureEventsHub/ModelingRules/AzureEventsHub/AzureEventsHub.xif
  Packs/AzureEventsHub/ModelingRules/AzureEventsHub/AzureEventsHub.yml
  Packs/BrocadeSwitch/ModelingRules/BrocadeSwitch/BrocadeSwitch.xif
  Packs/BrocadeSwitch/ModelingRules/BrocadeSwitch/BrocadeSwitch.yml
  Packs/IllusiveNetworks/ModelingRules/IllusiveNetworks/IllusiveNetworks.xif
  Packs/IllusiveNetworks/ModelingRules/IllusiveNetworks/IllusiveNetworks.yml
  Packs/Infoblox/ModelingRules/Infoblox/Infoblox.xif
  Packs/Infoblox/ModelingRules/Infoblox/Infoblox.yml
  Packs/LinuxEventsCollection/ModelingRules/LinuxEventsCollection/LinuxEventsCollection.xif
  Packs/LinuxEventsCollection/ModelingRules/LinuxEventsCollection/LinuxEventsCollection.yml
  Packs/MicrosoftADFS/ModelingRules/MicrosoftADFS/MicrosoftADFS.xif
  Packs/MicrosoftADFS/ModelingRules/MicrosoftADFS/MicrosoftADFS.yml
  Packs/MicrosoftADFS/README.md
  Packs/MicrosoftECM/ModelingRules/MicrosoftECM/MicrosoftECM.xif
  Packs/MicrosoftECM/ModelingRules/MicrosoftECM/MicrosoftECM.yml
  Packs/MicrosoftNPS/ModelingRules/MicrosoftNPS/MicrosoftNPS.xif
  Packs/MicrosoftNPS/ModelingRules/MicrosoftNPS/MicrosoftNPS.yml
  Packs/PrismaSaasSecurity/ModelingRules/SaasSecurityEventCollector/SaasSecurityEventCollector.xif
  Packs/PrismaSaasSecurity/ModelingRules/SaasSecurityEventCollector/SaasSecurityEventCollector.yml
  Packs/jamf/ModelingRules/Jamf/Jamf.xif
  Packs/jamf/ModelingRules/Jamf/Jamf.yml
Labels: docs-approved, ForceMerge

#20160 batch iocs in tim insert json xdr ioc
  Packs/CortexXDR/Integrations/XDR_iocs/XDR_iocs.py
  Packs/CortexXDR/Integrations/XDR_iocs/XDR_iocs.yml
  Packs/CortexXDR/Integrations/XDR_iocs/XDR_iocs_test.py
  Packs/CortexXDR/ReleaseNotes/4_8_3.md
  Packs/CortexXDR/pack_metadata.json
Labels: bug, docs-approved, release-notes-only

#20154 skip pan-os 8.1 test playbooks
  Tests/conf.json
Labels: docs-approved

#20150 Fix malformed release notes - CrowdStrikeFalcon
  Packs/CrowdStrikeFalcon/ReleaseNotes/1_8_9.md
Labels: docs-approved

#20164 Added blank line between blockquote and proofpoint-get-forensics
  Packs/ProofpointTAP/Integrations/ProofpointTAP_v2/README.md
Labels: Contribution, docs-approved, Contribution Form Filled, Community

#20157 vision-one-add-mp-mpv2
  Packs/TrendMicroVisionOne/pack_metadata.json
Labels: docs-approved

#19926 CrowdStrike Api Module - reuse cached token
  Packs/ApiModules/Scripts/CrowdStrikeApiModule/CrowdStrikeApiModule.py
  Packs/ApiModules/Scripts/CrowdStrikeApiModule/CrowdStrikeApiModule_test.py
  Packs/CrowdStrikeIntel/ReleaseNotes/2_0_18.md
  Packs/CrowdStrikeIntel/pack_metadata.json
  Packs/CrowdStrikeOpenAPI/ReleaseNotes/1_0_6.md
  Packs/CrowdStrikeOpenAPI/pack_metadata.json
  Packs/FeedCrowdstrikeFalconIntel/ReleaseNotes/2_0_15.md
  Packs/FeedCrowdstrikeFalconIntel/pack_metadata.json
Labels: docs-approved, release-notes-only

#19974 adding using argument
  Packs/CommonScripts/ReleaseNotes/1_7_16.md
  Packs/CommonScripts/Scripts/RunPollingCommand/RunPollingCommand.py
  Packs/CommonScripts/Scripts/RunPollingCommand/RunPollingCommand_test.py
  Packs/CommonScripts/pack_metadata.json
Labels: docs-approved, ForceMerge

#20140 Pan-os check logs status bug fix
  Packs/PAN-OS/Integrations/Panorama/Panorama.py
  Packs/PAN-OS/ReleaseNotes/1_14_11.md
  Packs/PAN-OS/pack_metadata.json
Labels: bug, docs-approved, ForceMerge

#20146 Add override
  Utils/gitlab_triggers/trigger_upload_flow_build.sh
Labels: docs-approved, ForceMerge

#20176 fix md issue in sane report pdf and bump image version
  Packs/Base/ReleaseNotes/1_31_9.md
  Packs/Base/Scripts/SanePdfReport/SanePdfReport.yml
  Packs/Base/pack_metadata.json
Labels: docs-approved

#20119 [O365 Outlook Mail] - Add the replayTo arg to the reply-mail command
  Packs/MicrosoftGraphMail/Integrations/MicrosoftGraphMail/MicrosoftGraphMail.py
  Packs/MicrosoftGraphMail/Integrations/MicrosoftGraphMail/MicrosoftGraphMail.yml
  Packs/MicrosoftGraphMail/Integrations/MicrosoftGraphMail/MicrosoftGraphMail_test.py
  Packs/MicrosoftGraphMail/Integrations/MicrosoftGraphMail/README.md
  Packs/MicrosoftGraphMail/ReleaseNotes/1_1_22.md
  Packs/MicrosoftGraphMail/pack_metadata.json
Labels: docs-approved

#20197 SNOW mirroring permissions - Update README.md
  Packs/ServiceNow/Integrations/ServiceNowv2/README.md
Labels: docs-approved

#20195 fix SEKOIAIntelligenceCenter unit tests
  Packs/SEKOIAIntelligenceCenter/Integrations/SEKOIAIntelligenceCenter/SEKOIAIntelligenceCenter_test.py
Labels: docs-approved, ForceMerge

#20200 Update script-CommonServerUserPython_README.md
  Packs/NonSupported/Scripts/script-CommonServerUserPython_README.md
Labels: docs-approved

#20186 Google pubsub fix
  Packs/GooglePubSub/Integrations/GooglePubSub/GooglePubSub.py
  Packs/GooglePubSub/Integrations/GooglePubSub/GooglePubSub.yml
  Packs/GooglePubSub/ReleaseNotes/1_0_17.md
  Packs/GooglePubSub/pack_metadata.json
Labels: bug, docs-approved, release-notes-only

#20196 fix_adfs_yml
  Packs/BrocadeSwitch/ModelingRules/BrocadeSwitch/BrocadeSwitch.xif
  Packs/BrocadeSwitch/ReleaseNotes/1_0_1.md
  Packs/BrocadeSwitch/pack_metadata.json
  Packs/Infoblox/ModelingRules/Infoblox/Infoblox.xif
  Packs/Infoblox/ReleaseNotes/1_0_10.md
  Packs/Infoblox/pack_metadata.json
  Packs/MicrosoftADFS/ModelingRules/MicrosoftADFS/MicrosoftADFS.yml
  Packs/MicrosoftADFS/ReleaseNotes/1_0_1.md
  Packs/MicrosoftADFS/pack_metadata.json
  Packs/MicrosoftIISWebServer/README.md
Labels: docs-approved, ForceMerge

#20188 Fix typo in inputs description for pan-os-custom-block-rule
  Packs/PAN-OS/.pack-ignore
  Packs/PAN-OS/Integrations/Panorama/Panorama.yml
  Packs/PAN-OS/Integrations/Panorama/README.md
  Packs/PAN-OS/ReleaseNotes/1_14_12.md
  Packs/PAN-OS/pack_metadata.json
Labels: Contribution, docs-approved, ready-for-instance-test, Contribution Form Filled, Community

#19746 Threat connect v2 bug
  Packs/ThreatConnect/Integrations/ThreatConnect_v2/ThreatConnect_v2.py
  Packs/ThreatConnect/ReleaseNotes/2_0_19.md
  Packs/ThreatConnect/pack_metadata.json
Labels: docs-approved

#20083 add to pan-os-commit the ability of polling
  Packs/Base/ReleaseNotes/1_31_10.md
  Packs/Base/Scripts/CommonServerPython/CommonServerPython.py
  Packs/Base/pack_metadata.json
  Packs/CrowdStrikeFalconSandbox/Integrations/CrowdStrikeFalconSandboxV2/CrowdStrikeFalconSandboxV2.py
  Packs/CrowdStrikeFalconSandbox/Integrations/CrowdStrikeFalconSandboxV2/CrowdStrikeFalconSandboxV2_test.py
  Packs/CrowdStrikeFalconSandbox/ReleaseNotes/2_0_5.md
  Packs/CrowdStrikeFalconSandbox/pack_metadata.json
  Packs/PAN-OS/Integrations/Panorama/Panorama.py
  Packs/PAN-OS/Integrations/Panorama/Panorama.yml
  Packs/PAN-OS/Integrations/Panorama/Panorama_test.py
  Packs/PAN-OS/Integrations/Panorama/README.md
  Packs/PAN-OS/Integrations/Panorama/command_examples.txt
  Packs/PAN-OS/ReleaseNotes/1_14_12.md
  Packs/PAN-OS/pack_metadata.json
Labels: docs-approved, ForceMerge

#20205 Rasterize - Changed the output to be "png" instead of "jpeg"
  Packs/rasterize/Integrations/rasterize/rasterize.py
  Packs/rasterize/ReleaseNotes/1_2_2.md
  Packs/rasterize/TestPlaybooks/playbook-Rasterize_Test.yml
  Packs/rasterize/pack_metadata.json
Labels: docs-approved

#20198 Fix VSCode broken SVG shield on README
  README.md
Labels: docs-approved

#20215 Cortex xdrir add on
  Packs/CortexXDR/Integrations/CortexXDRIR/CortexXDRIR.py
  Packs/CortexXDR/ReleaseNotes/4_8_4.md
  Packs/CortexXDR/pack_metadata.json
Labels: docs-approved

#20233 build fix
  poetry.lock
  pyproject.toml
Labels: docs-approved

#20177 Add pagination and filters to okta v2 list users
  Packs/Okta/Integrations/Okta_v2/Okta_v2.py
  Packs/Okta/Integrations/Okta_v2/Okta_v2.yml
  Packs/Okta/Integrations/Okta_v2/Okta_v2_test.py
  Packs/Okta/Integrations/Okta_v2/README.md
  Packs/Okta/Integrations/Okta_v2/example.txt
  Packs/Okta/ReleaseNotes/3_0_4.md
  Packs/Okta/pack_metadata.json
Labels: docs-approved

#20236 For release SDK 1.7.1
  poetry.lock
  pyproject.toml
Labels: docs-approved

#20234 Deprecate XDR IR Commands
  Packs/CortexXDR/Integrations/CortexXDRIR/CortexXDRIR.yml
  Packs/CortexXDR/Integrations/CortexXDRIR/README.md
  Packs/CortexXDR/ReleaseNotes/4_8_5.md
  Packs/CortexXDR/pack_metadata.json
Labels: docs-approved

#20240 Fix exchange
  Packs/MicrosoftExchangeServer/ModelingRules/MicrosoftExchangeServerModeling/MicrosoftExchangeServerModeling.xif
  Packs/MicrosoftExchangeServer/ReleaseNotes/1_0_1.md
  Packs/MicrosoftExchangeServer/pack_metadata.json
  Tests/known_words.txt
Labels: docs-approved

#20239 Update docker imange for ml docker
  Packs/Base/ReleaseNotes/1_31_11.md
  Packs/Base/Scripts/DBotPredictPhishingWords/DBotPredictPhishingWords.yml
  Packs/Base/pack_metadata.json
  Packs/ML/ReleaseNotes/1_4_3.md
  Packs/ML/Scripts/DBotPredictOutOfTheBoxV2/DBotPredictOutOfTheBoxV2.yml
  Packs/ML/pack_metadata.json
Labels: docs-approved

#20173 RN filtering fixes in upload flow
  Tests/Marketplace/Tests/marketplace_services_test.py
  Tests/Marketplace/marketplace_services.py
  Tests/Marketplace/upload_packs.py
Labels: docs-approved

#20229 Cybleevents readme sync
  Packs/CybleEvents/README.md
  Packs/CybleEvents/ReleaseNotes/1_0_3.md
  Packs/CybleEvents/pack_metadata.json
Labels: Contribution, Partner, Contribution Form Filled, pending-contributor

#19907 Malware mde fixes
  Packs/CrowdStrikeFalcon/.pack-ignore
  Packs/MicrosoftDefenderAdvancedThreatProtection/Playbooks/playbook-MDE_-_False_Positive_Incident_Handling.yml
  Packs/MicrosoftDefenderAdvancedThreatProtection/Playbooks/playbook-MDE_-_False_Positive_Incident_Handling_README.md
  Packs/MicrosoftDefenderAdvancedThreatProtection/Playbooks/playbook-MDE_-_Host_Advanced_Hunting.yml
  Packs/MicrosoftDefenderAdvancedThreatProtection/Playbooks/playbook-MDE_-_Host_Advanced_Hunting_For_Network_Activity.yml
  Packs/MicrosoftDefenderAdvancedThreatProtection/Playbooks/playbook-MDE_-_Host_Advanced_Hunting_For_Network_Activity_README.md
  Packs/MicrosoftDefenderAdvancedThreatProtection/Playbooks/playbook-MDE_-_Host_Advanced_Hunting_For_Persistence.yml
  Packs/MicrosoftDefenderAdvancedThreatProtection/Playbooks/playbook-MDE_-_Host_Advanced_Hunting_For_Persistence_README.md
  Packs/MicrosoftDefenderAdvancedThreatProtection/Playbooks/playbook-MDE_-_Host_Advanced_Hunting_For_Powershell_Executions.yml
  Packs/MicrosoftDefenderAdvancedThreatProtection/Playbooks/playbook-MDE_-_Host_Advanced_Hunting_For_Powershell_Executions_README.md
  Packs/MicrosoftDefenderAdvancedThreatProtection/Playbooks/playbook-MDE_-_Host_Advanced_Hunting_README.md
  Packs/MicrosoftDefenderAdvancedThreatProtection/Playbooks/playbook-MDE_-_Pro-Active_Actions.yml
  Packs/MicrosoftDefenderAdvancedThreatProtection/Playbooks/playbook-MDE_-_Pro-Active_Actions_README.md
  Packs/MicrosoftDefenderAdvancedThreatProtection/Playbooks/playbook-MDE_-_Retrieve_File.yml
  Packs/MicrosoftDefenderAdvancedThreatProtection/Playbooks/playbook-MDE_-_Retrieve_File_README.md
  Packs/MicrosoftDefenderAdvancedThreatProtection/Playbooks/playbook-MDE_-_True_Positive_Incident_Handling.yml
  Packs/MicrosoftDefenderAdvancedThreatProtection/Playbooks/playbook-MDE_-_True_Positive_Incident_Handling_README.md
  Packs/MicrosoftDefenderAdvancedThreatProtection/Playbooks/playbook-MDE_Malware_-_Incident_Enrichment.yml
  Packs/MicrosoftDefenderAdvancedThreatProtection/Playbooks/playbook-MDE_Malware_-_Incident_Enrichment_README.md
  Packs/MicrosoftDefenderAdvancedThreatProtection/Playbooks/playbook-MDE_Malware_-_Investigation_and_Response.yml
  Packs/MicrosoftDefenderAdvancedThreatProtection/Playbooks/playbook-MDE_Malware_-_Investigation_and_Response_README.md
  Packs/MicrosoftDefenderAdvancedThreatProtection/Playbooks/playbook-MDE_SIEM_ingestion_-_Get_Incident_Data.yml
  Packs/MicrosoftDefenderAdvancedThreatProtection/Playbooks/playbook-MDE_SIEM_ingestion_-_Get_Incident_Data_README.md
  Packs/MicrosoftDefenderAdvancedThreatProtection/ReleaseNotes/1_11_7.md
  Packs/MicrosoftDefenderAdvancedThreatProtection/doc_files/MDE_-_Host_Advanced_Hunting.png
  Packs/MicrosoftDefenderAdvancedThreatProtection/doc_files/MDE_-_Host_Advanced_Hunting_For_Network_Activity.png
  Packs/MicrosoftDefenderAdvancedThreatProtection/doc_files/MDE_-_Host_Advanced_Hunting_For_Persistence.png
  Packs/MicrosoftDefenderAdvancedThreatProtection/doc_files/MDE_-_Retrieve_File.png
  Packs/MicrosoftDefenderAdvancedThreatProtection/doc_files/MDE_Malware_-_Investigation_and_Response.png
  Packs/MicrosoftDefenderAdvancedThreatProtection/pack_metadata.json
Labels: docs-approved

#20218 Teams email bug
  Packs/MicrosoftTeams/Integrations/MicrosoftTeams/MicrosoftTeams.py
  Packs/MicrosoftTeams/Integrations/MicrosoftTeams/MicrosoftTeams.yml
  Packs/MicrosoftTeams/Integrations/MicrosoftTeams/MicrosoftTeams_test.py
  Packs/MicrosoftTeams/ReleaseNotes/1_1_29.md
  Packs/MicrosoftTeams/pack_metadata.json
Labels: docs-approved

#20241 add to thinkst Canary pack the modeling rules
  Packs/ThinkstCanary/ModelingRules/ThinkstCanary/ThinkstCanary.xif
  Packs/ThinkstCanary/ModelingRules/ThinkstCanary/ThinkstCanary.yml
  Packs/ThinkstCanary/ModelingRules/ThinkstCanary/ThinkstCanary_schema.json
  Packs/ThinkstCanary/README.md
  Packs/ThinkstCanary/ReleaseNotes/1_0_12.md
  Packs/ThinkstCanary/pack_metadata.json
Labels: docs-approved

#19992 Oletools automation
  Packs/Oletools/.pack-ignore
  Packs/Oletools/.secrets-ignore
  Packs/Oletools/Playbooks/Microsoft_Office_File_Enrichment_-_Oletools.yml
  Packs/Oletools/Playbooks/Microsoft_Office_File_Enrichment_-_Oletools_README.md
  Packs/Oletools/README.md
  Packs/Oletools/Scripts/OletoolsScript/OletoolsScript.py
  Packs/Oletools/Scripts/OletoolsScript/OletoolsScript.yml
  Packs/Oletools/Scripts/OletoolsScript/OletoolsScript_image.png
  Packs/Oletools/Scripts/OletoolsScript/OletoolsScript_test.py
  Packs/Oletools/Scripts/OletoolsScript/README.md
  Packs/Oletools/Scripts/OletoolsScript/test_data/ActiveBarcode-Demo-Bind-Text.docm
  Packs/Oletools/Scripts/OletoolsScript/test_data/commands_outputs.py
  Packs/Oletools/Scripts/OletoolsScript/test_data/oleid_decrypted_readable.md
  Packs/Oletools/Scripts/OletoolsScript/test_data/oleid_readable.md
  Packs/Oletools/Scripts/OletoolsScript/test_data/oleobj_readable.md
  Packs/Oletools/Scripts/OletoolsScript/test_data/olevba_readable.md
  Packs/Oletools/Scripts/OletoolsScript/test_data/protected.docm
  Packs/Oletools/doc_files/Microsoft_Office_File_Enrichment_-_Oletools.png
  Packs/Oletools/pack_metadata.json
Labels: docs-approved

#20223 PCC - Fix bug when no items exist in custom feeds
  Packs/PrismaCloudCompute/Integrations/PaloAltoNetworks_PrismaCloudCompute/PaloAltoNetworks_PrismaCloudCompute.py
  Packs/PrismaCloudCompute/ReleaseNotes/1_2_14.md
  Packs/PrismaCloudCompute/pack_metadata.json
Labels: Contribution, docs-approved, ready-for-instance-test, Contribution Form Filled, Community

#20268 Crowdstrike openapi enhancemnet
  Packs/CrowdStrikeOpenAPI/Integrations/CrowdStrikeOpenAPI/CrowdStrikeOpenAPI.py
  Packs/CrowdStrikeOpenAPI/Integrations/CrowdStrikeOpenAPI/CrowdStrikeOpenAPI.yml
  Packs/CrowdStrikeOpenAPI/ReleaseNotes/1_0_7.md
  Packs/CrowdStrikeOpenAPI/pack_metadata.json
Labels: docs-approved, ForceMerge

#20250 Fixed an issue where it fails to parse a date string which has 7 or m…
  Packs/Base/ReleaseNotes/1_31_12.md
  Packs/Base/Scripts/CommonServerPython/CommonServerPython.py
  Packs/Base/pack_metadata.json
Labels: Contribution, docs-approved, ready-for-instance-test, Contribution Form Filled, Community

#20294 Crodstrike openapi fix
  Packs/CrowdStrikeOpenAPI/Integrations/CrowdStrikeOpenAPI/CrowdStrikeOpenAPI.yml
Labels: docs-approved, ForceMerge

#20274 Virus Total Detonate DT fix
  Packs/VirusTotal/Playbooks/Detonate_File_-_VirusTotal_V3_README.md
  Packs/VirusTotal/Playbooks/Detonate_URL_-_VirusTotal_V3.yml
  Packs/VirusTotal/Playbooks/Detonate_URL_-_VirusTotal_V3_README.md
  Packs/VirusTotal/ReleaseNotes/2_4_5.md
  Packs/VirusTotal/doc_files/Detonate_File_-_VirusTotal_API_v3.png
  Packs/VirusTotal/doc_files/Detonate_URL_-_VirusTotal_API_v3.png
  Packs/VirusTotal/pack_metadata.json
Labels: docs-approved
