Repository demisto/content, pull requests merged in 2022-05, with the labels that each got.

#18832 Fix newline in input name O365AllowNotFoundExchangeLocations
  Packs/CommonPlaybooks/Playbooks/playbook-Search_And_Delete_Emails_-_Generic_-_v2.yml
Labels: Contribution, docs-approved, Contribution Form Filled, Community

#18828 update readme
  Packs/PhishUp/README.md
Labels: Contribution, docs-approved, Partner, Contribution Form Filled

#18733 Acti indicator query playbook
  Packs/AccentureCTI/IndicatorFields/indicatorfield-ACTI_Abstract.json
  Packs/AccentureCTI/IndicatorFields/indicatorfield-ACTI_Analysis.json
  Packs/AccentureCTI/IndicatorFields/indicatorfield-ACTI_Conclusion.json
  Packs/AccentureCTI/IndicatorFields/indicatorfield-ACTI_Index_Timestamp.json
  Packs/AccentureCTI/IndicatorFields/indicatorfield-ACTI_Last_Modified.json
  Packs/AccentureCTI/IndicatorFields/indicatorfield-ACTI_Last_Published.json
  Packs/AccentureCTI/IndicatorFields/indicatorfield-ACTI_Mitigation.json
  Packs/AccentureCTI/IndicatorFields/indicatorfield-ACTI_Report_Title.json
  Packs/AccentureCTI/IndicatorFields/indicatorfield-ACTI_Severity.json
  Packs/AccentureCTI/IndicatorFields/indicatorfield-ACTI_Threat_Types.json
  Packs/AccentureCTI/IndicatorFields/indicatorfield-ACTI_UUID.json
  Packs/AccentureCTI/IndicatorTypes/indicatortype-ACTI_Intelligence_Alert.json
  Packs/AccentureCTI/IndicatorTypes/indicatortype-ACTI_Intelligence_Report.json
  Packs/AccentureCTI/Integrations/ACTIIndicatorQuery/ACTIIndicatorQuery.py
  Packs/AccentureCTI/Integrations/ACTIIndicatorQuery/ACTIIndicatorQuery.yml
  Packs/AccentureCTI/Integrations/ACTIIndicatorQuery/ACTIIndicatorQuery_test.py
  Packs/AccentureCTI/Integrations/ACTIIndicatorQuery/README.md
  Packs/AccentureCTI/Integrations/ACTIVulnerabilityQuery/ACTIVulnerabilityQuery.py
  Packs/AccentureCTI/Integrations/ACTIVulnerabilityQuery/ACTIVulnerabilityQuery.yml
  Packs/AccentureCTI/Integrations/ACTIVulnerabilityQuery/README.md
  Packs/AccentureCTI/Layouts/layoutscontainer-ACTI_Intelligence_Alert.json
  Packs/AccentureCTI/Layouts/layoutscontainer-ACTI_Intelligence_Report.json
  Packs/AccentureCTI/Playbooks/playbook-ACTI_Block_High_Severity_Indicators.yml
  Packs/AccentureCTI/Playbooks/playbook-ACTI_Block_High_Severity_Indicators_README.md
  Packs/AccentureCTI/Playbooks/playbook-ACTI_Block_Indicators_from_an_Incident.yml
  Packs/AccentureCTI/Playbooks/playbook-ACTI_Block_Indicators_from_an_Incident_README.md
  Packs/AccentureCTI/Playbooks/playbook-ACTI_Create_Report-Indicator_Associations.yml
  Packs/AccentureCTI/Playbooks/playbook-ACTI_Create_Report-Indicator_Associations_README.md
  Packs/AccentureCTI/Playbooks/playbook-ACTI_Incident_Enrichment.yml
  Packs/AccentureCTI/Playbooks/playbook-ACTI_Incident_Enrichment_README.md
  Packs/AccentureCTI/Playbooks/playbook-ACTI_Indicator_Enrichment.yml
  Packs/AccentureCTI/Playbooks/playbook-ACTI_Indicator_Enrichment_README.md
  Packs/AccentureCTI/Playbooks/playbook-ACTI_Report_Enrichment.yml
  Packs/AccentureCTI/Playbooks/playbook-ACTI_Report_Enrichment_README.md
  Packs/AccentureCTI/Playbooks/playbook-ACTI_Vulnerability_Enrichment.yml
  Packs/AccentureCTI/Playbooks/playbook-ACTI_Vulnerability_Enrichment_README.md
  Packs/AccentureCTI/README.md
  Packs/AccentureCTI/ReleaseNotes/2_1_0.md
  Packs/AccentureCTI/pack_metadata.json
  Packs/AccentureCTI_Feed/Integrations/ACTIIndicatorFeed/ACTIIndicatorFeed.py
  Packs/AccentureCTI_Feed/Integrations/ACTIIndicatorFeed/README.md
  Packs/AccentureCTI_Feed/ReleaseNotes/1_1_0.md
  Packs/AccentureCTI_Feed/pack_metadata.json
Labels: Contribution, docs-approved, Partner, Contribution Form Filled

#18818 Update documentation and remove licensing
  Packs/CimTrak-SystemIntegrityAssurance/.secrets-ignore
  Packs/CimTrak-SystemIntegrityAssurance/Integrations/CimTrak/CimTrak.py
  Packs/CimTrak-SystemIntegrityAssurance/Integrations/CimTrak/CimTrak.yml
  Packs/CimTrak-SystemIntegrityAssurance/README.md
  Packs/CimTrak-SystemIntegrityAssurance/ReleaseNotes/1_0_2.md
  Packs/CimTrak-SystemIntegrityAssurance/pack_metadata.json
Labels: Contribution, docs-approved, Partner

#18831 Enhance README.md
  Packs/EDL/Integrations/EDL/README.md
Labels: Contribution, docs-approved

#18775 Add command to get the last Sigma analysis of a file
  Packs/VirusTotal/Integrations/VirusTotalV3/README.md
  Packs/VirusTotal/Integrations/VirusTotalV3/VirusTotalV3.py
  Packs/VirusTotal/Integrations/VirusTotalV3/VirusTotalV3.yml
  Packs/VirusTotal/ReleaseNotes/2_4_0.md
  Packs/VirusTotal/pack_metadata.json
Labels: Contribution, docs-approved, Partner, Contribution Form Filled

#18655 Symantec DLP v2 update outputs
  Packs/SymantecDLP/.secrets-ignore
  Packs/SymantecDLP/Integrations/SymantecDLPV2/README.md
  Packs/SymantecDLP/Integrations/SymantecDLPV2/SymantecDLPV2.py
  Packs/SymantecDLP/Integrations/SymantecDLPV2/SymantecDLPV2.yml
  Packs/SymantecDLP/Integrations/SymantecDLPV2/SymantecDLPV2_test.py
  Packs/SymantecDLP/Integrations/SymantecDLPV2/command_examples
  Packs/SymantecDLP/Integrations/SymantecDLPV2/test_data/incident_details_context.json
  Packs/SymantecDLP/Integrations/SymantecDLPV2/test_data/incident_editable_attributes_first.json
  Packs/SymantecDLP/Integrations/SymantecDLPV2/test_data/incident_editable_attributes_second.json
  Packs/SymantecDLP/ReleaseNotes/2_0_1.md
  Packs/SymantecDLP/pack_metadata.json
Labels: docs-approved

#18839 Export IOCS - terms of time
  Packs/EDL/Integrations/EDL/README.md
Labels: docs-approved

#18813 fix 400 error handling
  Tests/Marketplace/search_and_install_packs.py
Labels: docs-approved

#18814 Documantation changes to EDL
  Packs/EDL/.secrets-ignore
  Packs/EDL/Integrations/EDL/README.md
Labels: docs-approved

#18841 revision: add ignore to mypy missing imports on py2
  Packs/CommonScripts/Scripts/FindSimilarIncidentsV2/FindSimilarIncidentsV2.py
  Packs/CommonScripts/Scripts/GetDuplicatesMlv2/GetDuplicatesMlv2.py
  Packs/CommonScripts/Scripts/IndicatorMaliciousRatioCalculation/IndicatorMaliciousRatioCalculation.py
  Packs/SplunkPy/Integrations/SplunkPy/SplunkPy.py
  Packs/SplunkPyPreRelease/Integrations/SplunkPyPreRelease/SplunkPyPreRelease.py
Labels: docs-approved

#18805 A BA116 error was added to the .pack-ignore of some files
  Packs/ContentManagement/.pack-ignore
  Packs/Cyberint/.pack-ignore
  Packs/Edgescan/.pack-ignore
  Packs/FeedRSS/.pack-ignore
  Packs/JARM/.pack-ignore
Labels: docs-approved

#18844 Azure ad bug
  Packs/AzureActiveDirectory/Integrations/AzureADIdentityProtection/AzureADIdentityProtection.py
  Packs/AzureActiveDirectory/ReleaseNotes/1_2_7.md
  Packs/AzureActiveDirectory/pack_metadata.json
Labels: bug, docs-approved, release-notes-only

#18523 EDL playbooks update
  Packs/CommonScripts/ReleaseNotes/1_6_57.md
  Packs/CommonScripts/Scripts/CIDRBiggerThanPrefix/CIDRBiggerThanPrefix.py
  Packs/CommonScripts/Scripts/CIDRBiggerThanPrefix/CIDRBiggerThanPrefix.yml
  Packs/CommonScripts/Scripts/CIDRBiggerThanPrefix/CIDRBiggerThanPrefix_test.py
  Packs/CommonScripts/Scripts/CIDRBiggerThanPrefix/README.md
  Packs/CommonScripts/Scripts/CheckIfSubdomain/CheckIfSubdomain.py
  Packs/CommonScripts/Scripts/CheckIfSubdomain/CheckIfSubdomain.yml
  Packs/CommonScripts/Scripts/CheckIfSubdomain/CheckIfSubdomain_test.py
  Packs/CommonScripts/Scripts/CheckIfSubdomain/README.md
  Packs/CommonScripts/Scripts/IsInCidrRanges/IsInCidrRanges.py
  Packs/CommonScripts/Scripts/IsInCidrRanges/IsInCidrRanges.yml
  Packs/CommonScripts/Scripts/IsInCidrRanges/IsInCidrRanges_test.py
  Packs/CommonScripts/Scripts/IsInCidrRanges/README.md
  Packs/CommonScripts/TestPlaybooks/playbook-CIDRBiggerThanPrefix_Test.yml
  Packs/CommonScripts/TestPlaybooks/playbook-CheckIfSubdomain_Test.yml
  Packs/CommonScripts/pack_metadata.json
  Packs/EDL/Playbooks/Tag_massive_and_internal_IOCs_to_avoid_EDL_listing.yml
  Packs/EDL/Playbooks/Tag_massive_and_internal_IOCs_to_avoid_EDL_listing_README.md
  Packs/EDL/ReleaseNotes/3_1_2.md
  Packs/EDL/doc_files/Tag_massive_and_internal_IOCs_to_avoid_EDL_listing.png
  Packs/EDL/pack_metadata.json
  Tests/conf.json
  Tests/known_words.txt
Labels: docs-approved

#18820 major: SiemAPIModule
  Packs/ApiModules/Scripts/SiemApiModule/Pipfile
  Packs/ApiModules/Scripts/SiemApiModule/Pipfile.lock
  Packs/ApiModules/Scripts/SiemApiModule/README.md
  Packs/ApiModules/Scripts/SiemApiModule/SiemApiModule.py
  Packs/ApiModules/Scripts/SiemApiModule/SiemApiModule.yml
  Packs/ApiModules/Scripts/SiemApiModule/SiemApiModule_test.py
Labels: docs-approved

#18842 Kenna bug in query sent to API
  Packs/Kenna/Integrations/KennaV2/KennaV2.py
  Packs/Kenna/ReleaseNotes/1_1_12.md
  Packs/Kenna/pack_metadata.json
Labels: docs-approved

#18652 Contrib/CDS Flashpoint Feed Safe Get
  Packs/FlashpointFeed/Integrations/FlashpointFeed/FlashpointFeed.py
  Packs/FlashpointFeed/Integrations/FlashpointFeed/FlashpointFeed.yml
  Packs/FlashpointFeed/Integrations/FlashpointFeed/FlashpointFeed_image.png
  Packs/FlashpointFeed/Integrations/FlashpointFeed/FlashpointFeed_test.py
  Packs/FlashpointFeed/ReleaseNotes/1_0_2.md
  Packs/FlashpointFeed/pack_metadata.json
Labels: Contribution, docs-approved, Partner, Contribution Form Filled

#18845 Remove bad build locks
  Tests/scripts/wait_in_line_for_xsiam_env.sh
Labels: docs-approved

#18702 Fixed look-back tests
  Packs/Base/ReleaseNotes/1_30_3.md
  Packs/Base/Scripts/CommonServerPython/CommonServerPython.py
  Packs/Base/Scripts/CommonServerPython/CommonServerPython_test.py
  Packs/Base/pack_metadata.json
Labels: docs-approved

#18590 Mitre playbook
  Packs/FeedMitreAttackv2/Playbooks/Mitre_Attack_-_Extract_Technique_Information_From_ID.yml
  Packs/FeedMitreAttackv2/Playbooks/Mitre_Attack_-_Extract_Technique_Information_From_ID_README.md
  Packs/FeedMitreAttackv2/ReleaseNotes/1_1_0.md
  Packs/FeedMitreAttackv2/doc_files/Mitre_Attack _-_Extract_Technique_Information_From_ID.png
  Packs/FeedMitreAttackv2/pack_metadata.json
Labels: docs-approved

#18453 Added microsoft-atp-get-machine-alerts and microsoft-atp-get-machine-users
  Packs/MicrosoftDefenderAdvancedThreatProtection/.pack-ignore
  Packs/MicrosoftDefenderAdvancedThreatProtection/Integrations/MicrosoftDefenderAdvancedThreatProtection/MicrosoftDefenderAdvancedThreatProtection.py
  Packs/MicrosoftDefenderAdvancedThreatProtection/Integrations/MicrosoftDefenderAdvancedThreatProtection/MicrosoftDefenderAdvancedThreatProtection.yml
  Packs/MicrosoftDefenderAdvancedThreatProtection/Integrations/MicrosoftDefenderAdvancedThreatProtection/MicrosoftDefenderAdvancedThreatProtection_test.py
  Packs/MicrosoftDefenderAdvancedThreatProtection/Integrations/MicrosoftDefenderAdvancedThreatProtection/README.md
  Packs/MicrosoftDefenderAdvancedThreatProtection/Integrations/MicrosoftDefenderAdvancedThreatProtection/examples.txt
  Packs/MicrosoftDefenderAdvancedThreatProtection/Playbooks/Microsoft_Defender_Advanced_Threat_Protection_Get_Machine_Action_Status_README.md
  Packs/MicrosoftDefenderAdvancedThreatProtection/ReleaseNotes/1_7_0.md
  Packs/MicrosoftDefenderAdvancedThreatProtection/Scripts/TransformIndicatorToMSDefenderIOC/TransformIndicatorToMSDefenderIOC.yml
  Packs/MicrosoftDefenderAdvancedThreatProtection/TestPlaybooks/Microsoft_Defender_Advanced_Threat_Protection_-_Test_dev.yml
  Packs/MicrosoftDefenderAdvancedThreatProtection/TestPlaybooks/Microsoft_Defender_Advanced_Threat_Protection_-_Test_prod.yml
  Packs/MicrosoftDefenderAdvancedThreatProtection/TestPlaybooks/Microsoft_Defender_Advanced_Threat_Protection_-_Test_self_deployed.yml
  Packs/MicrosoftDefenderAdvancedThreatProtection/TestPlaybooks/playbook-Microsoft_ATP_indicators_SC_Test.yml
  Packs/MicrosoftDefenderAdvancedThreatProtection/TestPlaybooks/playbook-Microsoft_ATP_indicators_Test.yml
  Packs/MicrosoftDefenderAdvancedThreatProtection/TestPlaybooks/playbook-Microsoft_Defender_Advanced_Threat_Protection-Test.yml
  Packs/MicrosoftDefenderAdvancedThreatProtection/pack_metadata.json
  dev-requirements-py3.txt
Labels: Contribution, ready-for-instance-test, post-demo, Contribution Form Filled, Community

#18859 Update CODEOWNERS - `collect_tests_and_content_packs.py`
  .github/CODEOWNERS
Labels: docs-approved

#18868 fix last three yml's
  Packs/FeedCyjax/Integrations/FeedCyjax/FeedCyjax.yml
  Packs/FeedCyjax/ReleaseNotes/1_0_5.md
  Packs/FeedCyjax/pack_metadata.json
  Packs/Qintel/Integrations/QintelQWatch/QintelQWatch.yml
  Packs/Qintel/ReleaseNotes/1_0_3.md
  Packs/Qintel/pack_metadata.json
  Packs/Slack/Integrations/SlackV3/SlackV3.yml
  Packs/Slack/ReleaseNotes/2_5_9.md
  Packs/Slack/pack_metadata.json
Labels: docs-approved

#18840 bump sdk to 1.6.5
  dev-requirements-py3.txt
Labels: docs-approved

#18546 Added extraction of embedded URLs to ReadPDFFileV2
  Packs/CommonScripts/.secrets-ignore
  Packs/CommonScripts/ReleaseNotes/1_6_58.md
  Packs/CommonScripts/Scripts/ReadPDFFileV2/README.md
  Packs/CommonScripts/Scripts/ReadPDFFileV2/ReadPDFFileV2.py
  Packs/CommonScripts/Scripts/ReadPDFFileV2/ReadPDFFileV2.yml
  Packs/CommonScripts/Scripts/ReadPDFFileV2/ReadPDFFileV2_test.py
  Packs/CommonScripts/Scripts/ReadPDFFileV2/test_data/URLs_Extraction_Test_PDF_Encoding_Google_Docs_Renderer.pdf
  Packs/CommonScripts/Scripts/ReadPDFFileV2/test_data/URLs_Extraction_Test_PDF_Encoding_Google_Docs_Renderer_protected.pdf
  Packs/CommonScripts/Scripts/ReadPDFFileV2/test_data/URLs_Extraction_Test_PDF_Encoding_LibreOffice.pdf
  Packs/CommonScripts/Scripts/ReadPDFFileV2/test_data/URLs_Extraction_Test_PDF_Encoding_LibreOffice_protected.pdf
  Packs/CommonScripts/Scripts/ReadPDFFileV2/test_data/URLs_Extraction_Test_PDF_Encoding_Quartz_PDFContext.pdf
  Packs/CommonScripts/Scripts/ReadPDFFileV2/test_data/URLs_Extraction_Test_PDF_Encoding_Quartz_PDFContext_protected.pdf
  Packs/CommonScripts/pack_metadata.json
  Tests/known_words.txt
Labels: docs-approved

#18876 Orca_rm_video_readme_add_metadata
  Packs/Orca/README.md
  Packs/Orca/pack_metadata.json
Labels: docs-approved

#18658 Upload xsiam
  .gitlab/ci/bucket-upload.yml
  .gitlab/ci/on-push.yml
  Tests/Marketplace/configure_and_install_packs.py
  Tests/Marketplace/install_packs.sh
  Tests/Marketplace/marketplace_services.py
  Tests/scripts/collect_tests_and_content_packs.py
Labels: docs-approved

#18852 Change 'Integrations and incidents health check' incident fields to array type
  Packs/IntegrationsAndIncidentsHealthCheck/.pack-ignore
  Packs/IntegrationsAndIncidentsHealthCheck/IncidentFields/incidentfield-CreatedDateFailedIncidents.json
  Packs/IntegrationsAndIncidentsHealthCheck/IncidentFields/incidentfield-IntegrationsCategories.json
  Packs/IntegrationsAndIncidentsHealthCheck/IncidentFields/incidentfield-similarIncident.json
  Packs/IntegrationsAndIncidentsHealthCheck/ReleaseNotes/1_3_6.md
  Packs/IntegrationsAndIncidentsHealthCheck/pack_metadata.json
Labels: docs-approved

#18853 fix pan-os-list-applications command bug
  Packs/PAN-OS/Integrations/Panorama/Panorama.py
  Packs/PAN-OS/Integrations/Panorama/Panorama_test.py
  Packs/PAN-OS/Integrations/Panorama/test_data/list_applications_response.json
  Packs/PAN-OS/ReleaseNotes/1_12_1.md
  Packs/PAN-OS/pack_metadata.json
Labels: docs-approved

#18874 fix(intezer): bump SDK version and update documentation
  Packs/Intezer/Integrations/IntezerV2/IntezerV2.py
  Packs/Intezer/Integrations/IntezerV2/IntezerV2.yml
  Packs/Intezer/Integrations/IntezerV2/README.md
  Packs/Intezer/ReleaseNotes/1_3_1.md
  Packs/Intezer/pack_metadata.json
Labels: Contribution, docs-approved, Partner, Contribution Form Filled

#18889 Lowercase `isfetchevents`
  Tests/Marketplace/Tests/marketplace_services_test.py
  Tests/Marketplace/marketplace_services.py
Labels: docs-approved

#18895 Fix HttpV2 TPB
  Packs/CommonScripts/TestPlaybooks/playbook-HttpV2-Test.yml
Labels: docs-approved

#18893 Added prints to debug content bot
  Utils/github_workflow_scripts/handle_external_pr.py
Labels: docs-approved

#18847 Added new workflow to update base branch
  .github/workflows/sync-contribution-base-branch-on-change.yml
  Utils/github_workflow_scripts/sync_contrib_base.py
Labels: docs-approved

#18877 OTRS bug fix
  Packs/OTRS/Integrations/OTRS/OTRS.py
  Packs/OTRS/Integrations/OTRS/OTRS.yml
  Packs/OTRS/ReleaseNotes/1_0_12.md
  Packs/OTRS/pack_metadata.json
Labels: docs-approved

#18432 Contrib/cds google chronicle backstory fetch all detections
  Packs/GoogleChronicleBackstory/Integrations/GoogleChronicleBackstory/GoogleChronicleBackstory.py
  Packs/GoogleChronicleBackstory/Integrations/GoogleChronicleBackstory/GoogleChronicleBackstory.yml
  Packs/GoogleChronicleBackstory/Integrations/GoogleChronicleBackstory/GoogleChronicleBackstory_test.py
  Packs/GoogleChronicleBackstory/Integrations/GoogleChronicleBackstory/README.md
  Packs/GoogleChronicleBackstory/README.md
  Packs/GoogleChronicleBackstory/ReleaseNotes/2_0_18.md
  Packs/GoogleChronicleBackstory/Scripts/ChronicleAssetEventsForHostnameWidgetScript/ChronicleAssetEventsForHostnameWidgetScript.yml
  Packs/GoogleChronicleBackstory/Scripts/ChronicleAssetEventsForIPWidgetScript/ChronicleAssetEventsForIPWidgetScript.yml
  Packs/GoogleChronicleBackstory/Scripts/ChronicleAssetEventsForMACWidgetScript/ChronicleAssetEventsForMACWidgetScript.yml
  Packs/GoogleChronicleBackstory/Scripts/ChronicleAssetEventsForProductIDWidgetScript/ChronicleAssetEventsForProductIDWidgetScript.yml
  Packs/GoogleChronicleBackstory/Scripts/ChronicleAssetIdentifierScript/ChronicleAssetIdentifierScript.yml
  Packs/GoogleChronicleBackstory/Scripts/ChronicleAssetIdentifierScript/ChronicleAssetIdentifierScript_test.py
  Packs/GoogleChronicleBackstory/Scripts/ChronicleDBotScoreWidgetScript/ChronicleDBotScoreWidgetScript.yml
  Packs/GoogleChronicleBackstory/Scripts/ChronicleDomainIntelligenceSourcesWidgetScript/ChronicleDomainIntelligenceSourcesWidgetScript.yml
  Packs/GoogleChronicleBackstory/Scripts/ChronicleIsolatedHostnameWidgetScript/ChronicleIsolatedHostnameWidgetScript.yml
  Packs/GoogleChronicleBackstory/Scripts/ChronicleIsolatedHostnameWidgetScript/ChronicleIsolatedHostnameWidgetScript_test.py
  Packs/GoogleChronicleBackstory/Scripts/ChronicleIsolatedIPWidgetScript/ChronicleIsolatedIPWidgetScript.yml
  Packs/GoogleChronicleBackstory/Scripts/ChronicleIsolatedIPWidgetScript/ChronicleIsolatedIPWidgetScript_test.py
  Packs/GoogleChronicleBackstory/Scripts/ChronicleListDeviceEventsByEventTypeWidgetScript/ChronicleListDeviceEventsByEventTypeWidgetScript.yml
  Packs/GoogleChronicleBackstory/Scripts/ChronicleListDeviceEventsByEventTypeWidgetScript/ChronicleListDeviceEventsByEventTypeWidgetScript_test.py
  Packs/GoogleChronicleBackstory/Scripts/ChroniclePotentiallyBlockedIPWidgetScript/ChroniclePotentiallyBlockedIPWidgetScript.yml
  Packs/GoogleChronicleBackstory/Scripts/ChroniclePotentiallyBlockedIPWidgetScript/ChroniclePotentiallyBlockedIPWidgetScript_test.py
  Packs/GoogleChronicleBackstory/Scripts/ConvertDomainToURLs/ConvertDomainToURLs.py
  Packs/GoogleChronicleBackstory/Scripts/ConvertDomainToURLs/ConvertDomainToURLs.yml
  Packs/GoogleChronicleBackstory/Scripts/ExtractDomainFromIOCDomainMatchRes/ExtractDomainFromIOCDomainMatchRes.yml
  Packs/GoogleChronicleBackstory/Scripts/ListDeviceEventsScript/ListDeviceEventsScript.yml
  Packs/GoogleChronicleBackstory/pack_metadata.json
Labels: Contribution, docs-approved, Partner, post-demo, Contribution Form Filled

#18896 Update README.md
  Packs/ArcherRSA/Integrations/ArcherV2/README.md
Labels: Contribution, docs-approved, Contribution Form Filled, Community

#18902 Add packs to XSIAM marketplace
  Packs/AzureFirewall/pack_metadata.json
  Packs/AzureKeyVault/pack_metadata.json
  Packs/BatchData/pack_metadata.json
  Packs/CreateEDLInstance/pack_metadata.json
  Packs/DB2/pack_metadata.json
  Packs/DeepL/pack_metadata.json
  Packs/FeedMandiant/pack_metadata.json
  Packs/GCP-IAM/pack_metadata.json
  Packs/GoogleSheets/pack_metadata.json
  Packs/MacVendors/pack_metadata.json
  Packs/MaxList/pack_metadata.json
  Packs/MinList/pack_metadata.json
  Packs/NationalVulnerabilityDatabaseFeed/pack_metadata.json
  Packs/NetskopeV2/pack_metadata.json
  Packs/PowerShellUtilities/pack_metadata.json
  Packs/RandomElementFromList/pack_metadata.json
  Packs/VerifyIPv4Indicator/pack_metadata.json
  Packs/WolkenITSM/pack_metadata.json
  Packs/Xsoar_Utils/pack_metadata.json
Labels: docs-approved

#18879 testing commit
  Packs/CommonPlaybooks/Playbooks/playbook-Block_IP_-_Generic_v3.yml
  Packs/Core/Playbooks/playbook-NGFW_Scan.yml
Labels: docs-approved

#18906 update integration fromversion (workaround)
  Packs/AzureFirewall/Integrations/AzureFirewall/AzureFirewall.yml
Labels: docs-approved

#18662 Changes made to fix the issue caused by wrong field name.
  Packs/CreatePlbkDoc/.pack-ignore
  Packs/CreatePlbkDoc/ReleaseNotes/1_2_0.md
  Packs/CreatePlbkDoc/Scripts/CreatePlbkDoc/CreatePlbkDoc.py
  Packs/CreatePlbkDoc/Scripts/CreatePlbkDoc/CreatePlbkDoc.yml
  Packs/CreatePlbkDoc/pack_metadata.json
Labels: Contribution, docs-approved, Contribution Form Filled, Community

#18892 [VirusTotal] Improve packs use global stats
  Packs/VirusTotal-Private_API/Integrations/VirusTotal-Private_API/VirusTotal-Private_API.py
  Packs/VirusTotal-Private_API/ReleaseNotes/1_0_15.md
  Packs/VirusTotal-Private_API/pack_metadata.json
  Packs/VirusTotal/Integrations/VirusTotal/VirusTotal.js
  Packs/VirusTotal/Integrations/VirusTotalV3/VirusTotalV3.py
  Packs/VirusTotal/Integrations/VirusTotal_V3_Premium/VirusTotal_V3_Premium.py
  Packs/VirusTotal/Integrations/VirusTotal_V3_Premium/VirusTotal_V3_Premium.yml
  Packs/VirusTotal/ReleaseNotes/2_4_1.md
  Packs/VirusTotal/pack_metadata.json
Labels: Contribution, docs-approved, Partner, Contribution Form Filled

#18872 urlscan - Set Useragent
  Packs/UrlScan/Integrations/UrlScan/UrlScan.py
  Packs/UrlScan/ReleaseNotes/1_1_22.md
  Packs/UrlScan/pack_metadata.json
Labels: Contribution, docs-approved, Partner, Contribution Form Filled

#18894 Fix submit and add fetch support for HatchingTriage
  Packs/HatchingTriage/Integrations/HatchingTriage/HatchingTriage.py
  Packs/HatchingTriage/Integrations/HatchingTriage/HatchingTriage.yml
  Packs/HatchingTriage/ReleaseNotes/1_0_4.md
  Packs/HatchingTriage/pack_metadata.json
Labels: Contribution, docs-approved, Partner, Contribution Form Filled

#18926 fix codeowners error
  .github/CODEOWNERS
Labels: docs-approved

#18927 build: pip list to artifacts
  .circleci/config.yml
  .gitlab/ci/global.yml
Labels: docs-approved

#18870 remove trailing `,` from yml
  Packs/CofenseTriage/TestPlaybooks/playbook-Cofense_Triage_v2-Test.yml
  Packs/MISP/TestPlaybooks/playbook-MISP_V2-Test.yml
Labels: docs-approved

#18815 add look-back to service-now fetch incidents
  Packs/ServiceNow/.pack-ignore
  Packs/ServiceNow/Integrations/ServiceNowv2/README.md
  Packs/ServiceNow/Integrations/ServiceNowv2/ServiceNowv2.py
  Packs/ServiceNow/Integrations/ServiceNowv2/ServiceNowv2.yml
  Packs/ServiceNow/Integrations/ServiceNowv2/ServiceNowv2_description.md
  Packs/ServiceNow/Integrations/ServiceNowv2/ServiceNowv2_test.py
  Packs/ServiceNow/Integrations/ServiceNowv2/command_examples.txt
  Packs/ServiceNow/Integrations/ServiceNowv2/test_data/response_constants.py
  Packs/ServiceNow/ReleaseNotes/2_3_8.md
  Packs/ServiceNow/pack_metadata.json
Labels: docs-approved

#18850 Qradar test module to 1 minute
  Packs/QRadar/Integrations/QRadar_v3/QRadar_v3.py
  Packs/QRadar/ReleaseNotes/2_1_38.md
  Packs/QRadar/pack_metadata.json
Labels: docs-approved

#18830 Initial draft of changes
  Packs/MISP/Integrations/MISPV3/MISPV3.py
  Packs/MISP/Integrations/MISPV3/MISPV3.yml
  Packs/MISP/Integrations/MISPV3/MISPV3_test.py
  Packs/MISP/Integrations/MISPV3/README.md
  Packs/MISP/Integrations/MISPV3/command_examples
  Packs/MISP/Integrations/MISPV3/test_data/warninglist_outputs.md
  Packs/MISP/Integrations/MISPV3/test_data/warninglist_response.json
  Packs/MISP/ReleaseNotes/2_1_5.md
  Packs/MISP/pack_metadata.json
Labels: Contribution, docs-approved, Contribution Form Filled, Community

#18935 Fix lint on bandit
  .gitlab/ci/.gitlab-ci.yml
Labels: docs-approved

#18428 Paloalto security
  Packs/Palo_Alto_Networks_Security_Advisories/.pack-ignore
  Packs/Palo_Alto_Networks_Security_Advisories/.secrets-ignore
  Packs/Palo_Alto_Networks_Security_Advisories/Integrations/PaloAltoNetworksSecurityAdvisories/PaloAltoNetworksSecurityAdvisories.py
  Packs/Palo_Alto_Networks_Security_Advisories/Integrations/PaloAltoNetworksSecurityAdvisories/PaloAltoNetworksSecurityAdvisories.yml
  Packs/Palo_Alto_Networks_Security_Advisories/Integrations/PaloAltoNetworksSecurityAdvisories/PaloAltoNetworksSecurityAdvisories_image.png
  Packs/Palo_Alto_Networks_Security_Advisories/Integrations/PaloAltoNetworksSecurityAdvisories/PaloAltoNetworksSecurityAdvisories_test.py
  Packs/Palo_Alto_Networks_Security_Advisories/Integrations/PaloAltoNetworksSecurityAdvisories/README.md
  Packs/Palo_Alto_Networks_Security_Advisories/Integrations/PaloAltoNetworksSecurityAdvisories/command_examples.txt
  Packs/Palo_Alto_Networks_Security_Advisories/Integrations/PaloAltoNetworksSecurityAdvisories/test_data/advisories.json
  Packs/Palo_Alto_Networks_Security_Advisories/README.md
  Packs/Palo_Alto_Networks_Security_Advisories/Scripts/CheckPanosVersionAffected/CheckPanosVersionAffected.py
  Packs/Palo_Alto_Networks_Security_Advisories/Scripts/CheckPanosVersionAffected/CheckPanosVersionAffected.yml
  Packs/Palo_Alto_Networks_Security_Advisories/Scripts/CheckPanosVersionAffected/CheckPanosVersionAffected_test.py
  Packs/Palo_Alto_Networks_Security_Advisories/Scripts/CheckPanosVersionAffected/README.md
  Packs/Palo_Alto_Networks_Security_Advisories/Scripts/CheckPanosVersionAffected/command_examples.txt
  Packs/Palo_Alto_Networks_Security_Advisories/Scripts/CheckPanosVersionAffected/test_data/example_advisories_data.json
  Packs/Palo_Alto_Networks_Security_Advisories/Scripts/CheckPanosVersionAffected/test_data/expected_response.json
  Packs/Palo_Alto_Networks_Security_Advisories/TestPlaybooks/testPlaybook-Palo_Alto_Networks_Security_Advisories.yml
  Packs/Palo_Alto_Networks_Security_Advisories/pack_metadata.json
Labels: Contribution, docs-approved, Contribution Form Filled, Community

#18843 Alerts handling v3 enhancement
  Packs/CortexXDR/Playbooks/Cortex_XDR_-_Malware_Investigation.yml
  Packs/CortexXDR/Playbooks/Cortex_XDR_-_Malware_Investigation_README.md
  Packs/CortexXDR/Playbooks/Cortex_XDR_Alerts_Handling.yml
  Packs/CortexXDR/Playbooks/Cortex_XDR_Alerts_Handling_README.md
  Packs/CortexXDR/ReleaseNotes/4_2_25.md
  Packs/CortexXDR/doc_files/Cortex_XDR_-_Malware_Investigation.png
  Packs/CortexXDR/pack_metadata.json
Labels: docs-approved

#18420 Update README - updated Configure Incident Mirroring and Troubleshooting
  Packs/ServiceNow/Integrations/ServiceNowv2/README.md
Labels: docs-approved

#18791 Fixing zipstrings script to also strings
  Packs/CommonScripts/ReleaseNotes/1_6_59.md
  Packs/CommonScripts/Scripts/ZipStringsArrays/ZipStringsArrays.py
  Packs/CommonScripts/Scripts/ZipStringsArrays/ZipStringsArrays.yml
  Packs/CommonScripts/Scripts/ZipStringsArrays/ZipStringsArrays_test.py
  Packs/CommonScripts/pack_metadata.json
Labels: docs-approved

#18943 ews-mail-sender-reply-to-bug
  Packs/EWSMailSender/.pack-ignore
  Packs/EWSMailSender/.secrets-ignore
  Packs/EWSMailSender/Integrations/EWSMailSender/EWSMailSender.py
  Packs/EWSMailSender/Integrations/EWSMailSender/EWSMailSender_test.py
  Packs/EWSMailSender/ReleaseNotes/1_1_8.md
  Packs/EWSMailSender/pack_metadata.json
Labels: docs-approved

#18806 Upload-flow: support upload images to new marketplace
  Tests/Marketplace/marketplace_services.py
  Tests/Marketplace/upload_packs.py
Labels: docs-approved

#18863 Add Github Event Collector
  Packs/GitHub/.pack-ignore
  Packs/GitHub/Integrations/GitHubEventCollector/GitHubEventCollector.py
  Packs/GitHub/Integrations/GitHubEventCollector/GitHubEventCollector.yml
  Packs/GitHub/Integrations/GitHubEventCollector/GitHubEventCollector_description.md
  Packs/GitHub/Integrations/GitHubEventCollector/GitHubEventCollector_image.png
  Packs/GitHub/Integrations/GitHubEventCollector/README.md
  Packs/GitHub/ReleaseNotes/2_0_0.md
  Packs/GitHub/TestPlaybooks/playbook-Github_Event_Collector-test.yml
  Packs/GitHub/pack_metadata.json
  Tests/conf.json
  dev-requirements-py3.txt
Labels: docs-approved

#18051 Updated CommonServerPython with new fields for field restructure
  Packs/AccentureCTI/.pack-ignore
  Packs/AccentureCTI/Integrations/ACTIVulnerabilityQuery/ACTIVulnerabilityQuery.py
  Packs/AccentureCTI/Integrations/ACTIVulnerabilityQuery/ACTIVulnerabilityQuery.yml
  Packs/AccentureCTI/Integrations/ACTIVulnerabilityQuery/ACTIVulnerabilityQuery_test.py
  Packs/AccentureCTI/ReleaseNotes/2_1_1.md
  Packs/AccentureCTI/pack_metadata.json
  Packs/AlienVault_OTX/Integrations/AlienVault_OTX_v2/AlienVault_OTX_v2_test.py
  Packs/Base/ReleaseNotes/1_30_4.md
  Packs/Base/Scripts/CommonServerPython/CommonServerPython.py
  Packs/Base/Scripts/CommonServerPython/CommonServerPython_test.py
  Packs/Base/pack_metadata.json
  Packs/CrowdStrikeFalconX/Integrations/CrowdStrikeFalconX/CrowdStrikeFalconX_test.py
  Packs/CrowdStrikeFalconX/Integrations/CrowdStrikeFalconX/TestsInput/context.py
  Packs/Polygon/Integrations/Polygon/test_data/results.json
  Packs/ReversingLabs_A1000/.pack-ignore
  Packs/ReversingLabs_A1000/Integrations/ReversingLabsA1000v2/TestData/a1000_context.json
  Packs/ReversingLabs_A1000/Integrations/ReversingLabsA1000v2/TestData/a1000_get_classification_context.json
  Packs/ReversingLabs_TitaniumScale/.pack-ignore
  Packs/ReversingLabs_TitaniumScale/Integrations/ReversingLabsTitaniumScale/TestData/tiscale_context.json
  Packs/ReversingLabs_Titanium_Cloud/.pack-ignore
  Packs/ReversingLabs_Titanium_Cloud/Integrations/ReversingLabsTitaniumCloudv2/TestData/av_scanners_context.json
  Packs/ReversingLabs_Titanium_Cloud/Integrations/ReversingLabsTitaniumCloudv2/TestData/file_analysis_context.json
  Packs/ReversingLabs_Titanium_Cloud/Integrations/ReversingLabsTitaniumCloudv2/TestData/file_reputation_context.json
  Packs/ReversingLabs_Titanium_Cloud/Integrations/ReversingLabsTitaniumCloudv2/TestData/rha1_analytics_context.json
Labels: docs-approved

#18756 added info about limitations to set script
  Packs/CommonScripts/Scripts/Set/README.md
Labels: docs-approved

#18945 Azure ad bug
  Packs/AzureActiveDirectory/Integrations/AzureADIdentityProtection/AzureADIdentityProtection.py
  Packs/AzureActiveDirectory/ReleaseNotes/1_2_8.md
  Packs/AzureActiveDirectory/pack_metadata.json
  Tests/known_words.txt
Labels: bug, docs-approved, release-notes-only

#18955 [Marketplace Contribution] jq (#18867)
  Packs/Jq/.pack-ignore
  Packs/Jq/.secrets-ignore
  Packs/Jq/README.md
  Packs/Jq/Scripts/Jq/Jq.py
  Packs/Jq/Scripts/Jq/Jq.yml
  Packs/Jq/Scripts/Jq/Pipfile
  Packs/Jq/Scripts/Jq/Pipfile.lock
  Packs/Jq/Scripts/Jq/README.md
  Packs/Jq/pack_metadata.json
Labels: docs-approved

#18962 Update README.md
  Packs/ServiceNow/Integrations/ServiceNowv2/README.md
Labels: docs-approved

#18956 Send events enhancements
  Packs/Base/ReleaseNotes/1_30_5.md
  Packs/Base/Scripts/CommonServerPython/CommonServerPython.py
  Packs/Base/Scripts/CommonServerPython/CommonServerPython_test.py
  Packs/Base/Scripts/CommonServerPython/test_data/send_events_to_xsiam_data.py
  Packs/Base/pack_metadata.json
Labels: docs-approved

#18949 Download Packs and Docker Images - add option to run on all packs
  Utils/download_packs_and_docker_images.py
Labels: docs-approved

#18947 Update README.md
  Packs/Cybereason/Integrations/Cybereason/README.md
Labels: docs-approved

#18928 Permissions documentation fix in ms graph mail
  Packs/MicrosoftGraphMail/Integrations/MicrosoftGraphMail/README.md
Labels: docs-approved

#18964 Additional fields
  Packs/CommonTypes/IncidentFields/incidentfield-Device_Internal_IPs.json
  Packs/CommonTypes/ReleaseNotes/3_2_33.md
  Packs/CommonTypes/pack_metadata.json
Labels: docs-approved, release-notes-only

#18711 Xsiam jira integration
  Packs/Jira/.secrets-ignore
  Packs/Jira/Integrations/JiraEventCollector/JiraEventCollector.py
  Packs/Jira/Integrations/JiraEventCollector/JiraEventCollector.yml
  Packs/Jira/Integrations/JiraEventCollector/JiraEventCollector_description.md
  Packs/Jira/Integrations/JiraEventCollector/JiraEventCollector_image.png
  Packs/Jira/Integrations/JiraEventCollector/JiraEventCollector_test.py
  Packs/Jira/Integrations/JiraEventCollector/Pipfile
  Packs/Jira/Integrations/JiraEventCollector/Pipfile.lock
  Packs/Jira/Integrations/JiraEventCollector/README.md
  Packs/Jira/Integrations/JiraEventCollector/command_examples
  Packs/Jira/Integrations/JiraEventCollector/test_data/events.json
  Packs/Jira/Integrations/JiraEventCollector/test_data/no_events.json
  Packs/Jira/ModelingRules/JiraEventCollector/JiraEventCollector.xif
  Packs/Jira/ModelingRules/JiraEventCollector/JiraEventCollector.yml
  Packs/Jira/ReleaseNotes/2_0_0.md
  Packs/Jira/pack_metadata.json
  Tests/known_words.txt
Labels: docs-approved

#18968 Add docker service to run-commands-against-instance
  .gitlab/ci/sdk-nightly.yml
Labels: docs-approved

#18937 Service now v2 miroring
  Packs/Base/.pack-ignore
  Packs/Base/ReleaseNotes/1_30_6.md
  Packs/Base/Scripts/CommonServerPython/CommonServerPython.py
  Packs/Base/pack_metadata.json
  Packs/ServiceNow/.pack-ignore
  Packs/ServiceNow/Integrations/ServiceNowv2/ServiceNowv2.py
  Packs/ServiceNow/Integrations/ServiceNowv2/ServiceNowv2_test.py
  Packs/ServiceNow/ReleaseNotes/2_3_9.md
  Packs/ServiceNow/pack_metadata.json
Labels: docs-approved

#18967 SDK 1.6.6
  dev-requirements-py3.txt
Labels: docs-approved

#18614 added File enrichment
  Packs/RSTCloud/.pack-ignore
  Packs/RSTCloud/.secrets-ignore
  Packs/RSTCloud/Author_image.png
  Packs/RSTCloud/Integrations/RSTCloudThreatFeedAPI/README.md
  Packs/RSTCloud/Integrations/RSTCloudThreatFeedAPI/RSTCloudThreatFeedAPI.py
  Packs/RSTCloud/Integrations/RSTCloudThreatFeedAPI/RSTCloudThreatFeedAPI.yml
  Packs/RSTCloud/Integrations/RSTCloudThreatFeedAPI/RSTCloudThreatFeedAPI_description.md
  Packs/RSTCloud/Integrations/RSTCloudThreatFeedAPI/RSTCloudThreatFeedAPI_image.png
  Packs/RSTCloud/Integrations/RSTCloudThreatFeedAPI/RSTCloudThreatFeedAPI_test.py
  Packs/RSTCloud/Integrations/RSTCloudThreatFeedAPI/command_examples.txt
  Packs/RSTCloud/Integrations/RSTCloudThreatFeedAPI/test_data/domain_reputation.json
  Packs/RSTCloud/Integrations/RSTCloudThreatFeedAPI/test_data/hash_reputation.json
  Packs/RSTCloud/Integrations/RSTCloudThreatFeedAPI/test_data/ip_reputation.json
  Packs/RSTCloud/Integrations/RSTCloudThreatFeedAPI/test_data/test_response.json
  Packs/RSTCloud/Integrations/RSTCloudThreatFeedAPI/test_data/url_reputation.json
  Packs/RSTCloud/Playbooks/Domain_Enrichment_-_RST_Threat_Feed.yml
  Packs/RSTCloud/Playbooks/Domain_Enrichment_-_RST_Threat_Feed_README.md
  Packs/RSTCloud/Playbooks/File_Enrichment_-_RST_Threat_Feed.yml
  Packs/RSTCloud/Playbooks/File_Enrichment_-_RST_Threat_Feed_README.md
  Packs/RSTCloud/Playbooks/IP_Enrichment_-_External_-_RST_Threat_Feed.yml
  Packs/RSTCloud/Playbooks/IP_Enrichment_-_External_-_RST_Threat_Feed_README.md
  Packs/RSTCloud/Playbooks/URL_Enrichment_-_RST_Threat_Feed.yml
  Packs/RSTCloud/Playbooks/URL_Enrichment_-_RST_Threat_Feed_README.md
  Packs/RSTCloud/README.md
  Packs/RSTCloud/ReleaseNotes/1_1_0.md
  Packs/RSTCloud/pack_metadata.json
Labels: Contribution, docs-approved, Partner, post-demo, Contribution Form Filled

#18966 FindSimilarIncidents script fix
  Packs/CommonScripts/ReleaseNotes/1_6_60.md
  Packs/CommonScripts/Scripts/FindSimilarIncidentsV2/FindSimilarIncidentsV2.py
  Packs/CommonScripts/Scripts/FindSimilarIncidentsV2/FindSimilarIncidentsV2.yml
  Packs/CommonScripts/Scripts/FindSimilarIncidentsV2/README.md
  Packs/CommonScripts/Scripts/FindSimilarIncidentsV2/find_similar_incidents_test.py
  Packs/CommonScripts/pack_metadata.json
Labels: docs-approved

#18978 Update README.md
  Packs/CyberArkPAS/Integrations/CyberArkPAS/README.md
Labels: docs-approved

#18981 Update README.md
  Packs/CyberArkPAS/Integrations/CyberArkPAS/README.md
Labels: docs-approved

#18858 AD query V2-fix
  Packs/Active_Directory_Query/Integrations/Active_Directory_Query/Active_Directory_Query.py
  Packs/Active_Directory_Query/Integrations/Active_Directory_Query/Active_Directory_Query.yml
  Packs/Active_Directory_Query/Integrations/Active_Directory_Query/Active_Directory_Query_test.py
  Packs/Active_Directory_Query/Integrations/Active_Directory_Query/README.md
  Packs/Active_Directory_Query/ReleaseNotes/1_4_10.md
  Packs/Active_Directory_Query/pack_metadata.json
Labels: docs-approved

#18944 Update description with correct param names 365 MS Defender
  Packs/Microsoft365Defender/Integrations/Microsoft365Defender/Microsoft365Defender_description.md
  Packs/Microsoft365Defender/Integrations/Microsoft365Defender/README.md
  Packs/Microsoft365Defender/ReleaseNotes/3_0_6.md
  Packs/Microsoft365Defender/pack_metadata.json
Labels: docs-approved

#18990 fix parameter reference for sqs parse body as json
  Packs/AWS-SQS/Integrations/AWS-SQS/AWS-SQS.yml
Labels: Contribution, docs-approved, Contribution Form Filled, Community

#18977 Update README.md
  Packs/Cybereason/Integrations/Cybereason/README.md
Labels: docs-approved

#18971 Corrections to the fromVersion key
  Packs/CaseManagement-Generic/.pack-ignore
  Packs/CaseManagement-Generic/ReleaseNotes/1_2_3.md
  Packs/CaseManagement-Generic/Widgets/widget-Mean_Time_To_Remediation_SLA.json
  Packs/CaseManagement-Generic/Widgets/widget-My_Mean_Time_To_Remediation_SLA.json
  Packs/CaseManagement-Generic/Widgets/widget-Time_To_Assignment.json
  Packs/CaseManagement-Generic/pack_metadata.json
Labels: docs-approved

#18963 Added the KillProcessWrapper script
  Packs/MalwareInvestigationAndResponse/.pack-ignore
  Packs/MalwareInvestigationAndResponse/.secrets-ignore
  Packs/MalwareInvestigationAndResponse/README.md
  Packs/MalwareInvestigationAndResponse/Scripts/KillProcessWrapper/KillProcessWrapper.py
  Packs/MalwareInvestigationAndResponse/Scripts/KillProcessWrapper/KillProcessWrapper.yml
  Packs/MalwareInvestigationAndResponse/Scripts/KillProcessWrapper/KillProcessWrapper_test.py
  Packs/MalwareInvestigationAndResponse/Scripts/KillProcessWrapper/README.md
  Packs/MalwareInvestigationAndResponse/pack_metadata.json
Labels: docs-approved

#18986 MicrosoftGraphMail
  Packs/MicrosoftGraphMail/Integrations/MicrosoftGraphMail/README.md
Labels: docs-approved

#18989 Teams documentation impovment
  Packs/MicrosoftTeams/Integrations/MicrosoftTeams/README.md
Labels: docs-approved

#18987 feat: change videos key to list
  Packs/ContentManagement/pack_metadata.json
  Packs/CortexXDR/pack_metadata.json
  Packs/CrisisManagement/pack_metadata.json
  Packs/Orca/pack_metadata.json
  Packs/Slack/pack_metadata.json
  Tests/Marketplace/marketplace_services.py
Labels: docs-approved

#18974 Generic Export Indicators Service docs improvements
  Packs/EDL/Integrations/EDL/README.md
Labels: docs-approved

#18997 feat: SiemApiModule set limit to optional
  Packs/ApiModules/Scripts/SiemApiModule/SiemApiModule.py
Labels: docs-approved

#18998 Move Code Owner
  .github/CODEOWNERS
Labels: docs-approved

#18999 Add files via upload
  Packs/Cybereason/doc_files/cybereason-pre-process.png
Labels: docs-approved

#18915 Panos network operations hygine checks
  Packs/PAN-OS/Integrations/Panorama/Panorama.py
  Packs/PAN-OS/Integrations/Panorama/Panorama.yml
  Packs/PAN-OS/Integrations/Panorama/Panorama_test.py
  Packs/PAN-OS/Integrations/Panorama/README.md
  Packs/PAN-OS/ReleaseNotes/1_13_0.md
  Packs/PAN-OS/TestPlaybooks/PAN-OS-firewall-topology-test-pb.yml
  Packs/PAN-OS/TestPlaybooks/PAN-OS-panorama-topology-test-pb.yml
  Packs/PAN-OS/pack_metadata.json
Labels: Contribution, docs-approved, post-demo, Contribution Form Filled, Community

#19001 feat: SiemApiModule set proxy to Optional[bool] to handle none value
  Packs/ApiModules/Scripts/SiemApiModule/SiemApiModule.py
Labels: docs-approved

#18898 aws_securityhub list_members date format fixes
  Packs/AWS-SecurityHub/.pack-ignore
  Packs/AWS-SecurityHub/Integrations/AWS_SecurityHub/AWS_SecurityHub.py
  Packs/AWS-SecurityHub/Integrations/AWS_SecurityHub/AWS_SecurityHub.yml
  Packs/AWS-SecurityHub/Integrations/AWS_SecurityHub/AWS_SecurityHub_test.py
  Packs/AWS-SecurityHub/ReleaseNotes/1_1_16.md
  Packs/AWS-SecurityHub/pack_metadata.json
Labels: docs-approved

#19004 Update README.md
  Packs/Cybereason/Integrations/Cybereason/README.md
Labels: docs-approved

#18992 Trend Micro Vision One 1.1
  Packs/TrendMicroVisionOne/Integrations/TrendMicroVisionOne/README.md
  Packs/TrendMicroVisionOne/Integrations/TrendMicroVisionOne/TrendMicroVisionOne.py
  Packs/TrendMicroVisionOne/Integrations/TrendMicroVisionOne/TrendMicroVisionOne.yml
  Packs/TrendMicroVisionOne/Integrations/TrendMicroVisionOne/TrendMicroVisionOne_test.py
  Packs/TrendMicroVisionOne/ReleaseNotes/1_1_0.md
  Packs/TrendMicroVisionOne/pack_metadata.json
Labels: Contribution, docs-approved, Partner, Contribution Form Filled

#19026 Update handle_external_pr.py
  Utils/github_workflow_scripts/handle_external_pr.py
Labels: docs-approved

#18253 Di davidr patch 1
  Packs/DeepInstinct/Integrations/DeepInstinct-3x/DeepInstinct.py
  Packs/DeepInstinct/Integrations/DeepInstinct-3x/DeepInstinct.yml
  Packs/DeepInstinct/Integrations/DeepInstinct-3x/DeepInstinct_description.md
  Packs/DeepInstinct/Integrations/DeepInstinct-3x/DeepInstinct_image.png
  Packs/DeepInstinct/Integrations/DeepInstinct-3x/DeepInstinct_test.py
  Packs/DeepInstinct/Integrations/DeepInstinct-3x/Pipfile
  Packs/DeepInstinct/Integrations/DeepInstinct-3x/Pipfile.lock
  Packs/DeepInstinct/Integrations/DeepInstinct-3x/README.md
Labels: Contribution, Partner, Contribution Form Filled, pending-partner

#19028 netskope-readme
  Packs/Netskope/Integrations/NetskopeAPIv1/README.md
Labels: docs-approved

#18888 SaaS to GA
  Packs/PrismaSaasSecurity/Integrations/SaasSecurity/SaasSecurity.yml
  Packs/PrismaSaasSecurity/Integrations/SaasSecurity/SaasSecurity_description.md
  Packs/PrismaSaasSecurity/ReleaseNotes/1_2_12.md
  Packs/PrismaSaasSecurity/pack_metadata.json
Labels: docs-approved

#18726 Box generic integration
  Packs/Box/Integrations/Box/command_examples
  Packs/Box/Integrations/BoxEventsCollector/BoxEventsCollector.py
  Packs/Box/Integrations/BoxEventsCollector/BoxEventsCollector.yml
  Packs/Box/Integrations/BoxEventsCollector/BoxEventsCollector_image.png
  Packs/Box/Integrations/BoxEventsCollector/BoxEventsCollector_test.py
  Packs/Box/Integrations/BoxEventsCollector/README.md
  Packs/Box/Integrations/BoxEventsCollector/commands.txt
  Packs/Box/ReleaseNotes/3_0_0.md
  Packs/Box/pack_metadata.json
Labels: docs-approved

#18511 [upload flow] Add Wizard Support
  Tests/Marketplace/marketplace_constants.py
  Tests/Marketplace/marketplace_services.py
Labels: docs-approved

#18808 Added Sec-Eng team as owners of Common packs
  .github/CODEOWNERS
Labels: docs-approved

#19020 Updated demisto.updateModuleHealth
  Tests/demistomock/demistomock.py
Labels: docs-approved

#18946 Refactoring wait in line script
  Tests/scripts/wait_in_line_for_xsiam_env.sh
Labels: docs-approved

#19032 took off permissions and added default val
  Packs/Slack/Integrations/SlackV3/README.md
  Packs/Slack/Integrations/SlackV3/SlackV3.yml
  Packs/Slack/Integrations/SlackV3/command_example.txt
  Packs/Slack/ReleaseNotes/2_5_11.md
  Packs/Slack/doc_files/SlackV3_app_manifest.yml
  Packs/Slack/pack_metadata.json
Labels: docs-approved

#19041 Revert to installing all packs in upload flow
  Tests/Marketplace/configure_and_install_packs.py
Labels: docs-approved

#19053 Wait in line issue
  Tests/scripts/wait_in_line_for_xsiam_env.sh
Labels: docs-approved

#19050 Remove 6.1 from build
  .gitlab/ci/bucket-upload.yml
  .gitlab/ci/on-push.yml
  Tests/Marketplace/configure_and_install_packs.py
Labels: docs-approved

#19029 Added link to guide
  Packs/PowershellRemoting/Integrations/PowerShellRemoting/README.md
Labels: docs-approved

#18988 Active directory bug get members
  Packs/Active_Directory_Query/Integrations/Active_Directory_Query/Active_Directory_Query.py
  Packs/Active_Directory_Query/Integrations/Active_Directory_Query/Active_Directory_Query_test.py
  Packs/Active_Directory_Query/ReleaseNotes/1_4_11.md
  Packs/Active_Directory_Query/pack_metadata.json
Labels: docs-approved

#18985 Adding error handling and documentation to red lock
  Packs/PrismaCloud/Integrations/RedLock/README.md
  Packs/PrismaCloud/Integrations/RedLock/RedLock.yml
  Packs/PrismaCloud/ReleaseNotes/2_0_9.md
  Packs/PrismaCloud/pack_metadata.json
Labels: docs-approved

#18970 fix the link
  Packs/MicrosoftGraphCalendar/Integrations/MicrosoftGraphCalendar/README.md
Labels: docs-approved

#19043 ParseEmailFilesV2: Update docker to support extract RTF body from msg emails
  Packs/CommonScripts/.pack-ignore
  Packs/CommonScripts/ReleaseNotes/1_6_61.md
  Packs/CommonScripts/Scripts/ParseEmailFilesV2/ParseEmailFilesV2.yml
  Packs/CommonScripts/pack_metadata.json
Labels: docs-approved

#19018 Added the instructions to connect to Microsoft Sentinel
  Packs/TAXIIServer/Integrations/TAXII2Server/README.md
  Packs/TAXIIServer/doc_files/MS-Sentinel-TI-Config.png
Labels: Contribution, docs-approved, Contribution Form Filled, Community

#19056 [VirusTotal] Fix network request error
  Packs/VirusTotal/Integrations/VirusTotal/VirusTotal.js
  Packs/VirusTotal/ReleaseNotes/2_4_2.md
  Packs/VirusTotal/pack_metadata.json
Labels: Contribution, docs-approved, Partner, Contribution Form Filled

#19064 feat: ActiveMQ - updated docker image
  Packs/ActiveMQ/Integrations/ActiveMQ/ActiveMQ.py
  Packs/ActiveMQ/Integrations/ActiveMQ/ActiveMQ.yml
  Packs/ActiveMQ/ReleaseNotes/1_1_0.md
  Packs/ActiveMQ/pack_metadata.json
Labels: docs-approved

#18996 Qualys script bug
  Packs/qualys/ReleaseNotes/1_0_19.md
  Packs/qualys/Scripts/QualysCreateIncidentFromReport/Pipfile
  Packs/qualys/Scripts/QualysCreateIncidentFromReport/Pipfile.lock
  Packs/qualys/Scripts/QualysCreateIncidentFromReport/QualysCreateIncidentFromReport.py
  Packs/qualys/Scripts/QualysCreateIncidentFromReport/QualysCreateIncidentFromReport.yml
  Packs/qualys/Scripts/QualysCreateIncidentFromReport/QualysCreateIncidentFromReport_test.py
  Packs/qualys/Scripts/QualysCreateIncidentFromReport/README.md
  Packs/qualys/Scripts/QualysCreateIncidentFromReport/test_data/qualys_host_list_rawresponse.xml
  Packs/qualys/Scripts/QualysCreateIncidentFromReport/test_data/test_report.xml
  Packs/qualys/Scripts/script-QualysCreateIncidentFromReport.yml
  Packs/qualys/pack_metadata.json
Labels: docs-approved

#19067 Temporary remove XSIAM server job dependency
  .gitlab/ci/bucket-upload.yml
Labels: docs-approved

#19039 write investigation id to env
  .github/workflows/run-secrets-detection.yml
  Utils/github_workflow_scripts/run_secrets_detection.py
Labels: docs-approved

#19095 Corepack malware remove
  Tests/Marketplace/core_packs_list.json
  Tests/Marketplace/core_packs_mpv2_list.json
Labels: docs-approved

#19075 SplunkPY- Fixed rawToDict function which parsed incorrectly field with "message-id" in its value.
  Packs/SplunkPy/.secrets-ignore
  Packs/SplunkPy/Integrations/SplunkPy/SplunkPy.py
  Packs/SplunkPy/Integrations/SplunkPy/SplunkPy_test.py
  Packs/SplunkPy/ReleaseNotes/2_4_3.md
  Packs/SplunkPy/pack_metadata.json
Labels: docs-approved

#19098 Remove lint quiet mode
  .gitlab/ci/global.yml
Labels: docs-approved

#19100 add pending-contributor label
  .github/project_conf/contributions.ini
Labels: docs-approved

#19052 Missing dependencies fix
  Packs/CommonPlaybooks/pack_metadata.json
  Packs/CreatePlbkDoc/pack_metadata.json
  Packs/ForwardXSOARAuditLogsToSplunkHEC/pack_metadata.json
  Packs/GoogleChronicleBackstory/pack_metadata.json
  Packs/IntegrationsAndIncidentsHealthCheck/pack_metadata.json
  Packs/PANOSPolicyOptimizer/pack_metadata.json
  Packs/PANOStoCDLMonitoring/pack_metadata.json
  Packs/PcapAnalysis/pack_metadata.json
  Packs/PhishingURL/pack_metadata.json
  Packs/PrismaCloud/pack_metadata.json
  Packs/TIM_Processing/pack_metadata.json
  Packs/Wiz/pack_metadata.json
  Tests/Marketplace/marketplace_services.py
  Tests/Marketplace/upload_packs.py
  Utils/trigger_test_upload_flow.sh
Labels: docs-approved

#16144 Adding MSDE PBs for isolation and unisolation for devices
  Packs/CommonPlaybooks/Playbooks/playbook-Isolate_Endpoint_-_Generic_V2.yml
  Packs/CommonPlaybooks/Playbooks/playbook-Isolate_Endpoint_-_Generic_V2_README.md
  Packs/CommonPlaybooks/Playbooks/playbook-Unisolate_Endpoint_-_Generic.yml
  Packs/CommonPlaybooks/Playbooks/playbook-Unisolate_Endpoint_-_Generic_README.md
  Packs/CommonPlaybooks/ReleaseNotes/2_2_0.md
  Packs/CommonPlaybooks/doc_files/Isolate_Endpoint_-_Generic_V2.png
  Packs/CommonPlaybooks/doc_files/Unisolate_Endpoint_-_Generic.png
  Packs/CommonPlaybooks/pack_metadata.json
  Packs/MicrosoftDefenderAdvancedThreatProtection/Playbooks/playbook-Microsoft_Defender_For_Endpoint_-_Isolate_Endpoint.yml
  Packs/MicrosoftDefenderAdvancedThreatProtection/Playbooks/playbook-Microsoft_Defender_For_Endpoint_-_Isolate_Endpoint_README.md
  Packs/MicrosoftDefenderAdvancedThreatProtection/Playbooks/playbook-Microsoft_Defender_For_Endpoint_-_Unisolate_Endpoint.yml
  Packs/MicrosoftDefenderAdvancedThreatProtection/Playbooks/playbook-Microsoft_Defender_For_Endpoint_-_Unisolate_Endpoint_README.md
  Packs/MicrosoftDefenderAdvancedThreatProtection/ReleaseNotes/1_6_2.md
  Packs/MicrosoftDefenderAdvancedThreatProtection/ReleaseNotes/1_6_3.md
  Packs/MicrosoftDefenderAdvancedThreatProtection/ReleaseNotes/1_8_0.md
  Packs/MicrosoftDefenderAdvancedThreatProtection/doc_files/Microsoft_Defender_For_Endpoint_-_Isolate_Endpoint.png
  Packs/MicrosoftDefenderAdvancedThreatProtection/doc_files/Microsoft_Defender_For_Endpoint_-_Unisolate_Endpoint.png
  Packs/MicrosoftDefenderAdvancedThreatProtection/pack_metadata.json
Labels: docs-approved

#19105 revert malware changes
  Packs/Malware/pack_metadata.json
  Tests/Marketplace/core_packs_list.json
  Tests/Marketplace/core_packs_mpv2_list.json
Labels: docs-approved

#19109 CommonPlaybooks: Rename v2_2_0 to v2_1_22
  Packs/CommonPlaybooks/ReleaseNotes/2_1_22.md
  Packs/CommonPlaybooks/pack_metadata.json
Labels: docs-approved

#19096 Update README.md
  Packs/rasterize/README.md
Labels: docs-approved

#18950 Adjust pan os test-playbooks to 9.1
  Packs/PAN-OS/TestPlaybooks/PAN-OS-firewall-topology-test-pb.yml
  Packs/PAN-OS/TestPlaybooks/PAN-OS-panorama-topology-test-pb.yml
  Packs/PAN-OS/TestPlaybooks/playbook-PAN-OS_Create_Or_Edit_Rule_Test.yml
  Packs/PAN-OS/TestPlaybooks/playbook-palo_alto_firewall_test_pb.yml
  Packs/PAN-OS/TestPlaybooks/playbook-palo_alto_panorama_test_pb.yml
  Tests/conf.json
Labels: docs-approved

#19097 Malware fields
  Packs/MalwareInvestigationAndResponse/IncidentFields/incidentfield-Malware_Detailed_Investigation_Summary.json
  Packs/MalwareInvestigationAndResponse/IncidentFields/incidentfield-Malware_Investigation_Summary.json
  Packs/MalwareInvestigationAndResponse/ReleaseNotes/1_0_1.md
  Packs/MalwareInvestigationAndResponse/pack_metadata.json
Labels: docs-approved

#19051 Fix bigquery
  Packs/GoogleBigQuery/Integrations/GoogleBigQuery/GoogleBigQuery.py
  Packs/GoogleBigQuery/Integrations/GoogleBigQuery/GoogleBigQuery.yml
  Packs/GoogleBigQuery/Integrations/GoogleBigQuery/GoogleBigQuery_test.py
  Packs/GoogleBigQuery/ReleaseNotes/1_1_0.md
  Packs/GoogleBigQuery/pack_metadata.json
Labels: docs-approved

#19102 changed display to display password
  Packs/AzureActiveDirectory/Integrations/AzureADIdentityProtection/AzureADIdentityProtection.yml
  Packs/AzureActiveDirectory/ReleaseNotes/1_2_9.md
  Packs/AzureActiveDirectory/pack_metadata.json
Labels: docs-approved

#19068 add slack-notifier to query failed XSIAM test-playbooks
  Tests/scripts/gitlab_slack_notifier.py
Labels: docs-approved

#19035 Update FortiAuthenticator integration to version 1.0.4
  Packs/FortiAuthenticator/Integrations/FortiAuthenticator/FortiAuthenticator.py
  Packs/FortiAuthenticator/Integrations/FortiAuthenticator/FortiAuthenticator.yml
  Packs/FortiAuthenticator/ReleaseNotes/1_0_4.md
  Packs/FortiAuthenticator/pack_metadata.json
Labels: Contribution, docs-approved, Contribution Form Filled, Community

#19133 snow-remove-not-needed-note
  Packs/ServiceNow/Integrations/ServiceNowv2/README.md
Labels: docs-approved

#19094 Make port argument mandatory for PortListenCheck
  Packs/CommonScripts/ReleaseNotes/1_6_64.md
  Packs/CommonScripts/Scripts/PortListenCheck/PortListenCheck.py
  Packs/CommonScripts/Scripts/PortListenCheck/PortListenCheck.yml
  Packs/CommonScripts/Scripts/PortListenCheck/PortListenCheck_test.py
  Packs/CommonScripts/pack_metadata.json
Labels: docs-approved

#18991 Fix capitalization in outputs: Ivantiheat -> IvantiHeat
  Packs/IvantiHeat/Integrations/IvantiHeat/IvantiHeat.yml
  Packs/IvantiHeat/Integrations/IvantiHeat/README.md
  Packs/IvantiHeat/ReleaseNotes/1_0_6.json
  Packs/IvantiHeat/ReleaseNotes/1_0_6.md
  Packs/IvantiHeat/pack_metadata.json
Labels: Contribution, Contribution Form Filled, Community

#19140 [Fix] Changing the query for MSDE
  Packs/Microsoft365Defender/Integrations/Microsoft365Defender/Microsoft365Defender.py
  Packs/Microsoft365Defender/ReleaseNotes/3_0_8.md
  Packs/Microsoft365Defender/pack_metadata.json
  Packs/MicrosoftDefenderAdvancedThreatProtection/Integrations/MicrosoftDefenderAdvancedThreatProtection/MicrosoftDefenderAdvancedThreatProtection.py
  Packs/MicrosoftDefenderAdvancedThreatProtection/Integrations/MicrosoftDefenderAdvancedThreatProtection/test_data/expected_hunting_queries.json
  Packs/MicrosoftDefenderAdvancedThreatProtection/ReleaseNotes/1_8_1.md
  Packs/MicrosoftDefenderAdvancedThreatProtection/pack_metadata.json
Labels: docs-approved

#19125 increase sqs message visibility timeout
  Packs/AWS-SQS/Integrations/AWS-SQS/AWS-SQS.py
  Packs/AWS-SQS/ReleaseNotes/1_2_8.md
  Packs/AWS-SQS/pack_metadata.json
Labels: Contribution, docs-approved, Contribution Form Filled, Community

#16579 Dedup Generic V4 - new playbook
  Packs/CommonPlaybooks/Playbooks/playbook-Dedup_-_Generic_v4.yml
  Packs/CommonPlaybooks/Playbooks/playbook-Dedup_-_Generic_v4_README.md
  Packs/CommonPlaybooks/ReleaseNotes/2_2_0.md
  Packs/CommonPlaybooks/doc_files/Dedup_-_Generic_v4.png
  Packs/CommonPlaybooks/pack_metadata.json
Labels: docs-approved

#18776 XDR get-alert enhancement
  Packs/ApiModules/Scripts/CoreIRApiModule/CoreIRApiModule.py
  Packs/ApiModules/Scripts/CoreIRApiModule/CoreIRApiModule_test.py
  Packs/ApiModules/Scripts/CoreIRApiModule/test_data/get_alerts_by_filter_results.json
  Packs/Core/ReleaseNotes/1_2_0.md
  Packs/Core/pack_metadata.json
  Packs/CortexXDR/Integrations/CortexXDRIR/CortexXDRIR.py
  Packs/CortexXDR/Integrations/CortexXDRIR/CortexXDRIR.yml
  Packs/CortexXDR/Integrations/CortexXDRIR/README.md
  Packs/CortexXDR/Integrations/CortexXDRIR/command_examples
  Packs/CortexXDR/Integrations/CortexXDRIR/test_data/get_alerts_by_filter_results.json
  Packs/CortexXDR/ReleaseNotes/4_4_0.md
  Packs/CortexXDR/pack_metadata.json
Labels: docs-approved

#19037 Xsiam jira integration fixed fetch duplicates event
  Packs/Jira/.pack-ignore
  Packs/Jira/Integrations/JiraEventCollector/JiraEventCollector.py
  Packs/Jira/Integrations/JiraEventCollector/JiraEventCollector.yml
  Packs/Jira/Integrations/JiraEventCollector/JiraEventCollector_test.py
  Packs/Jira/Integrations/JiraEventCollector/README.md
  Packs/Jira/ModelingRules/JiraEventCollector/JiraEventCollector.xif
  Packs/Jira/ReleaseNotes/2_0_1.md
  Packs/Jira/pack_metadata.json
Labels: docs-approved

#19016 Azure update 2
  Packs/AzureCompute/Integrations/AzureCompute_v2/AzureCompute_v2.py
  Packs/AzureCompute/Integrations/AzureCompute_v2/AzureCompute_v2.yml
  Packs/AzureCompute/Integrations/AzureCompute_v2/AzureCompute_v2_test.py
  Packs/AzureCompute/Integrations/AzureCompute_v2/README.md
  Packs/AzureCompute/Integrations/AzureCompute_v2/command_examples.txt
  Packs/AzureCompute/Integrations/AzureCompute_v2/test_data/create_nic_command.json
  Packs/AzureCompute/Integrations/AzureCompute_v2/test_data/get_network_interface_command.json
  Packs/AzureCompute/Integrations/AzureCompute_v2/test_data/get_public_ip_details_command.json
  Packs/AzureCompute/Integrations/AzureCompute_v2/test_data/list_vms_command.json
  Packs/AzureCompute/ReleaseNotes/1_0_14.md
  Packs/AzureCompute/pack_metadata.json
Labels: Contribution, docs-approved, pending-demo, post-demo, Contribution Form Filled, Community

#19134 Create content for CrowdStrikeFalcon Pack README
  Packs/CrowdStrikeFalcon/README.md
Labels: docs-approved

#19017 Added PcapConvert, PcapExtractStreams and PcapFileExtractStreams.
  Packs/PcapAnalysis/.secrets-ignore
  Packs/PcapAnalysis/ReleaseNotes/2_4_3.md
  Packs/PcapAnalysis/Scripts/PcapConvert/PcapConvert.py
  Packs/PcapAnalysis/Scripts/PcapConvert/PcapConvert.yml
  Packs/PcapAnalysis/Scripts/PcapConvert/PcapConvert_test.py
  Packs/PcapAnalysis/Scripts/PcapConvert/README.md
  Packs/PcapAnalysis/Scripts/PcapConvert/test_data/test-1.json
  Packs/PcapAnalysis/Scripts/PcapExtractStreams/PcapExtractStreams.py
  Packs/PcapAnalysis/Scripts/PcapExtractStreams/PcapExtractStreams.yml
  Packs/PcapAnalysis/Scripts/PcapExtractStreams/PcapExtractStreams_test.py
  Packs/PcapAnalysis/Scripts/PcapExtractStreams/README.md
  Packs/PcapAnalysis/Scripts/PcapExtractStreams/test_data/test-1.json
  Packs/PcapAnalysis/Scripts/PcapFileExtractStreams/PcapFileExtractStreams.py
  Packs/PcapAnalysis/Scripts/PcapFileExtractStreams/PcapFileExtractStreams.yml
  Packs/PcapAnalysis/Scripts/PcapFileExtractStreams/PcapFileExtractStreams_test.py
  Packs/PcapAnalysis/Scripts/PcapFileExtractStreams/README.md
  Packs/PcapAnalysis/Scripts/PcapFileExtractStreams/test_data/1.pcap
  Packs/PcapAnalysis/Scripts/PcapFileExtractStreams/test_data/2.pcap
  Packs/PcapAnalysis/Scripts/PcapFileExtractStreams/test_data/3.pcap
  Packs/PcapAnalysis/Scripts/PcapFileExtractStreams/test_data/test-1.json
  Packs/PcapAnalysis/pack_metadata.json
Labels: Contribution, docs-approved, Contribution Form Filled, Community

#19152 contrib fix
  Packs/AttachmentsPreProcessing/.pack-ignore
Labels: docs-approved, release-notes-only

#19072 Sync marketplace
  Tests/configure_and_test_integration_instances.py
Labels: docs-approved

#19138 Update README.md
  Packs/MicrosoftDefenderAdvancedThreatProtection/README.md
Labels: docs-approved

#19116 Fix install packs error response handling
  Tests/Marketplace/Tests/search_and_install_packs_test.py
  Tests/Marketplace/search_and_install_packs.py
Labels: docs-approved

#18272 InvestigationSummaryParse
  Packs/Malware/.pack-ignore
  Packs/MalwareInvestigationAndResponse/ReleaseNotes/1_1_0.md
  Packs/MalwareInvestigationAndResponse/Scripts/InvestigationSummaryParse/InvestigationSummaryParse.py
  Packs/MalwareInvestigationAndResponse/Scripts/InvestigationSummaryParse/InvestigationSummaryParse.yml
  Packs/MalwareInvestigationAndResponse/Scripts/InvestigationSummaryParse/InvestigationSummaryParse_test.py
  Packs/MalwareInvestigationAndResponse/Scripts/InvestigationSummaryParse/README.md
  Packs/MalwareInvestigationAndResponse/Scripts/InvestigationSummaryParse/test_data/empty_context.json
  Packs/MalwareInvestigationAndResponse/Scripts/InvestigationSummaryParse/test_data/kill_chain_0.json
  Packs/MalwareInvestigationAndResponse/Scripts/InvestigationSummaryParse/test_data/kill_chain_1.json
  Packs/MalwareInvestigationAndResponse/Scripts/InvestigationSummaryParse/test_data/kill_chain_2.json
  Packs/MalwareInvestigationAndResponse/Scripts/InvestigationSummaryParse/test_data/kill_chain_3.json
  Packs/MalwareInvestigationAndResponse/Scripts/InvestigationSummaryToTable/InvestigationSummaryToTable.py
  Packs/MalwareInvestigationAndResponse/Scripts/InvestigationSummaryToTable/InvestigationSummaryToTable.yml
  Packs/MalwareInvestigationAndResponse/Scripts/InvestigationSummaryToTable/InvestigationSummaryToTable_test.py
  Packs/MalwareInvestigationAndResponse/Scripts/InvestigationSummaryToTable/README.md
  Packs/MalwareInvestigationAndResponse/Scripts/InvestigationSummaryToTable/test_data/expected_context.json
  Packs/MalwareInvestigationAndResponse/pack_metadata.json
Labels: docs-approved

#19135 added 6.5 & 6.6 server versions
  .gitlab/ci/bucket-upload.yml
  .gitlab/ci/on-push.yml
  Tests/Marketplace/configure_and_install_packs.py
  Tests/scripts/collect_tests_and_content_packs.py
  Tests/scripts/infrastructure_tests/test_collect_tests_and_content_packs.py
Labels: docs-approved
