Repository demisto/content, pull requests merged in 2022-06, with the labels that each got.

#19202 Gitlab Event Collector
  Packs/GitLab/.pack-ignore
  Packs/GitLab/.secrets-ignore
  Packs/GitLab/Integrations/GitLabEventCollector/GitLabEventCollector.py
  Packs/GitLab/Integrations/GitLabEventCollector/GitLabEventCollector.yml
  Packs/GitLab/Integrations/GitLabEventCollector/GitLabEventCollector_description.md
  Packs/GitLab/Integrations/GitLabEventCollector/GitLabEventCollector_image.png
  Packs/GitLab/Integrations/GitLabEventCollector/GitLabEventCollector_test.py
  Packs/GitLab/Integrations/GitLabEventCollector/README.md
  Packs/GitLab/ModelingRules/GitlabModelingRules/GitlabModelingRules.xif
  Packs/GitLab/ModelingRules/GitlabModelingRules/GitlabModelingRules.yml
  Packs/GitLab/README.md
  Packs/GitLab/pack_metadata.json
Labels: docs-approved

#19305 Fixes for malware investigation
  Packs/CommonPlaybooks/ReleaseNotes/2_2_3.md
  Packs/CortexXDR/Playbooks/playbook-Cortex_XDR_-_Endpoint_Investigation.yml
  Packs/CortexXDR/Playbooks/playbook-Cortex_XDR_Malware_-_Incident_Enrichment.yml
  Packs/CortexXDR/Playbooks/playbook-Cortex_XDR_Malware_-_Investigation_And_Response.yml
  Packs/CortexXDR/ReleaseNotes/4_6_2.md
  Packs/CortexXDR/pack_metadata.json
  Packs/MalwareInvestigationAndResponse/pack_metadata.json
  Packs/MicrosoftDefenderAdvancedThreatProtection/Playbooks/playbook-MDE_-_Host_Advanced_Hunting.yml
  Packs/MicrosoftDefenderAdvancedThreatProtection/Playbooks/playbook-MDE_-_Host_Advanced_Hunting_For_Network_Activity.yml
  Packs/MicrosoftDefenderAdvancedThreatProtection/Playbooks/playbook-MDE_-_Host_Advanced_Hunting_For_Persistence.yml
  Packs/MicrosoftDefenderAdvancedThreatProtection/Playbooks/playbook-MDE_-_Host_Advanced_Hunting_For_Powershell_Executions.yml
  Packs/MicrosoftDefenderAdvancedThreatProtection/Playbooks/playbook-MDE_Malware_-_Incident_Enrichment.yml
  Packs/MicrosoftDefenderAdvancedThreatProtection/ReleaseNotes/1_11_2.md
  Packs/MicrosoftDefenderAdvancedThreatProtection/pack_metadata.json
Labels: docs-approved

#19324 CVE-2022-30190 Enhancement
  Packs/CVE_2022_30190/Playbooks/playbook-CVE-2022-30190_-_MSDT_RCE.yml
  Packs/CVE_2022_30190/Playbooks/playbook-CVE-2022-30190_-_MSDT_RCE_README.md
  Packs/CVE_2022_30190/README.md
  Packs/CVE_2022_30190/ReleaseNotes/1_0_1.md
  Packs/CVE_2022_30190/doc_files/CVE-2022-30190_-_MSDT_RCE.png
  Packs/CVE_2022_30190/pack_metadata.json
Labels: docs-approved

#19323 ParseEmailFilesV2 - French letters fix
  Packs/CommonScripts/ReleaseNotes/1_6_69.md
  Packs/CommonScripts/Scripts/ParseEmailFilesV2/ParseEmailFilesV2.yml
  Packs/CommonScripts/pack_metadata.json
Labels: docs-approved

#18784 EWSMailSender bug fix
  Packs/EWSMailSender/.pack-ignore
  Packs/EWSMailSender/Integrations/EWSMailSender/EWSMailSender.py
  Packs/EWSMailSender/Integrations/EWSMailSender/EWSMailSender_test.py
  Packs/EWSMailSender/ReleaseNotes/1_1_10.md
  Packs/EWSMailSender/pack_metadata.json
Labels: docs-approved

#19341 Images fix mpv2
  Tests/Marketplace/marketplace_services.py
  Tests/Marketplace/upload_packs.py
Labels: docs-approved

#19042 Cyber ark xsiam
  Packs/CyberArkIdentity/.pack-ignore
  Packs/CyberArkIdentity/.secrets-ignore
  Packs/CyberArkIdentity/Integrations/CyberArkIdentityEventCollector/CyberArkIdentityEventCollector.py
  Packs/CyberArkIdentity/Integrations/CyberArkIdentityEventCollector/CyberArkIdentityEventCollector.yml
  Packs/CyberArkIdentity/Integrations/CyberArkIdentityEventCollector/CyberArkIdentityEventCollector_description.md
  Packs/CyberArkIdentity/Integrations/CyberArkIdentityEventCollector/CyberArkIdentityEventCollector_image.png
  Packs/CyberArkIdentity/Integrations/CyberArkIdentityEventCollector/CyberArkIdentityEventCollector_test.py
  Packs/CyberArkIdentity/Integrations/CyberArkIdentityEventCollector/Pipfile
  Packs/CyberArkIdentity/Integrations/CyberArkIdentityEventCollector/Pipfile.lock
  Packs/CyberArkIdentity/Integrations/CyberArkIdentityEventCollector/README.md
  Packs/CyberArkIdentity/Integrations/CyberArkIdentityEventCollector/command_examples
  Packs/CyberArkIdentity/Integrations/CyberArkIdentityEventCollector/test_data/events.json
  Packs/CyberArkIdentity/ModelingRules/CyberArkIdentityEventCollector/CyberArkIdentityEventCollector.xif
  Packs/CyberArkIdentity/ModelingRules/CyberArkIdentityEventCollector/CyberArkIdentityEventCollector.yml
  Packs/CyberArkIdentity/README.md
  Packs/CyberArkIdentity/pack_metadata.json
Labels: docs-approved

#19149 Update jira-modeling-rule
  Packs/Jira/Integrations/JiraEventCollector/JiraEventCollector.yml
  Packs/Jira/ModelingRules/JiraEventCollector/JiraEventCollector.xif
  Packs/Jira/ModelingRules/JiraEventCollector/JiraEventCollector.yml
  Packs/Jira/ReleaseNotes/2_0_2.md
  Packs/Jira/pack_metadata.json
Labels: docs-approved

#19339 DeleteContext bug in parsing nested path
  Packs/CommonScripts/ReleaseNotes/1_6_70.md
  Packs/CommonScripts/Scripts/DeleteContext/DeleteContext.js
  Packs/CommonScripts/pack_metadata.json
Labels: docs-approved

#19342 malware readme and desc updates
  Packs/Malware/README.md
  Packs/Malware/pack_metadata.json
  Packs/MalwareInvestigationAndResponse/README.md
  Packs/MalwareInvestigationAndResponse/doc_files/Malware_Investigation_&_Response_layout.png
  Packs/MalwareInvestigationAndResponse/pack_metadata.json
  Tests/Marketplace/landingPage_sections.json
Labels: docs-approved

#19113 Add Oracle DB Modeling Rules
  Packs/Oracle/.pack-ignore
  Packs/Oracle/.secrets-ignore
  Packs/Oracle/ModelingRules/OracleDBEventCollector/OracleDBEventCollector.xif
  Packs/Oracle/ModelingRules/OracleDBEventCollector/OracleDBEventCollector.yml
  Packs/Oracle/README.md
  Packs/Oracle/pack_metadata.json
Labels: docs-approved

#19233 (Partner ID: cyware-238) - CTIX new V3 app for XSOAR ( CLA compatible copy of PR https://github.com/demisto/content/pull/19060)
  Packs/CTIX/.secrets-ignore
  Packs/CTIX/Integrations/CTIX/README.md
  Packs/CTIX/Integrations/CTIXv3/CTIXv3.py
  Packs/CTIX/Integrations/CTIXv3/CTIXv3.yml
  Packs/CTIX/Integrations/CTIXv3/CTIXv3_description.md
  Packs/CTIX/Integrations/CTIXv3/CTIXv3_image.png
  Packs/CTIX/Integrations/CTIXv3/CTIXv3_test.py
  Packs/CTIX/Integrations/CTIXv3/Pipfile
  Packs/CTIX/Integrations/CTIXv3/Pipfile.lock
  Packs/CTIX/Integrations/CTIXv3/README.md
  Packs/CTIX/Integrations/CTIXv3/command_examples
  Packs/CTIX/Integrations/CTIXv3/test_data/add_analyst_score.json
  Packs/CTIX/Integrations/CTIXv3/test_data/add_analyst_tlp.json
  Packs/CTIX/Integrations/CTIXv3/test_data/add_indicator_as_false_positive.json
  Packs/CTIX/Integrations/CTIXv3/test_data/add_tag_indicator.json
  Packs/CTIX/Integrations/CTIXv3/test_data/conversion_feed_source.json
  Packs/CTIX/Integrations/CTIXv3/test_data/create_tag.json
  Packs/CTIX/Integrations/CTIXv3/test_data/delete_tag.json
  Packs/CTIX/Integrations/CTIXv3/test_data/deprecate_ioc.json
  Packs/CTIX/Integrations/CTIXv3/test_data/get_actions.json
  Packs/CTIX/Integrations/CTIXv3/test_data/get_conversion_details.json
  Packs/CTIX/Integrations/CTIXv3/test_data/get_conversion_feed_source.json
  Packs/CTIX/Integrations/CTIXv3/test_data/get_indicator_details.json
  Packs/CTIX/Integrations/CTIXv3/test_data/get_indicator_observations.json
  Packs/CTIX/Integrations/CTIXv3/test_data/get_indicator_relations.json
  Packs/CTIX/Integrations/CTIXv3/test_data/get_indicator_tags.json
  Packs/CTIX/Integrations/CTIXv3/test_data/get_lookup_threat_data.json
  Packs/CTIX/Integrations/CTIXv3/test_data/get_saved_result_set.json
  Packs/CTIX/Integrations/CTIXv3/test_data/get_server_collections.json
  Packs/CTIX/Integrations/CTIXv3/test_data/get_tags.json
  Packs/CTIX/Integrations/CTIXv3/test_data/get_threat_data.json
  Packs/CTIX/Integrations/CTIXv3/test_data/get_whitelist_iocs.json
  Packs/CTIX/Integrations/CTIXv3/test_data/ioc_manual_review.json
  Packs/CTIX/Integrations/CTIXv3/test_data/remove_tag_from_indicator.json
  Packs/CTIX/Integrations/CTIXv3/test_data/remove_whitelist_ioc.json
  Packs/CTIX/Integrations/CTIXv3/test_data/saved_result_set.json
  Packs/CTIX/Integrations/CTIXv3/test_data/search_for_tag.json
  Packs/CTIX/Integrations/CTIXv3/test_data/whitelist_iocs.json
  Packs/CTIX/README.md
  Packs/CTIX/ReleaseNotes/1_1_0.md
  Packs/CTIX/ReleaseNotes/2_0_0.md
  Packs/CTIX/pack_metadata.json
Labels: Contribution, Partner, ready-for-instance-test, Contribution Form Filled, pending-contributor

#19336 Malware cs fixes
  Packs/CommonPlaybooks/Playbooks/playbook-Detonate_and_Analyze_File_-_Generic.yml
  Packs/CommonPlaybooks/Playbooks/playbook-Search_For_Hash_In_Sandbox_-_Generic.yml
  Packs/CommonPlaybooks/ReleaseNotes/2_2_4.md
  Packs/CommonPlaybooks/doc_files/Search_For_Hash_In_Sandbox_-_Generic.png
  Packs/CommonPlaybooks/pack_metadata.json
Labels: docs-approved, release-notes-only

#19292 Syslog Readme Troubleshoot update
  Packs/Syslog/Integrations/Syslogv2/README.md
Labels: docs-approved

#19360 Build: improve error messages
  .gitlab/ci/.gitlab-ci.yml
  Tests/scripts/is_file_up_to_date.sh
Labels: docs-approved

#19371 "Malware Investigation and Response" instead of "Malware" as a landin…
  Tests/Marketplace/landingPage_sections.json
Labels: docs-approved

#19375 detailed investigation to table - multiple techniques bug
  Packs/MalwareInvestigationAndResponse/ReleaseNotes/1_5_2.md
  Packs/MalwareInvestigationAndResponse/Scripts/InvestigationDetailedSummaryToTable/InvestigationDetailedSummaryToTable.py
  Packs/MalwareInvestigationAndResponse/Scripts/InvestigationDetailedSummaryToTable/InvestigationDetailedSummaryToTable_test.py
  Packs/MalwareInvestigationAndResponse/Scripts/InvestigationDetailedSummaryToTable/test_data/table_command.json
  Packs/MalwareInvestigationAndResponse/pack_metadata.json
Labels: docs-approved

#19117 Add Alibaba Event Collector
  Packs/AlibabaActionTrail/.pack-ignore
  Packs/AlibabaActionTrail/.secrets-ignore
  Packs/AlibabaActionTrail/Integrations/AlibabaActionTrailEventCollector/AlibabaActionTrailEventCollector.py
  Packs/AlibabaActionTrail/Integrations/AlibabaActionTrailEventCollector/AlibabaActionTrailEventCollector.yml
  Packs/AlibabaActionTrail/Integrations/AlibabaActionTrailEventCollector/AlibabaActionTrailEventCollector_image.png
  Packs/AlibabaActionTrail/Integrations/AlibabaActionTrailEventCollector/README.md
  Packs/AlibabaActionTrail/ModelingRules/AlibabaModelingRules/AlibabaModelingRules.xif
  Packs/AlibabaActionTrail/ModelingRules/AlibabaModelingRules/AlibabaModelingRules.yml
  Packs/AlibabaActionTrail/README.md
  Packs/AlibabaActionTrail/TestPlaybooks/playbook-Alibaba_Event_Collector-test.yml
  Packs/AlibabaActionTrail/pack_metadata.json
  Packs/ApiModules/Scripts/SiemApiModule/SiemApiModule.py
  Tests/conf.json
Labels: docs-approved

#19388 add SpyCloud integration
  Packs/SpyCloud/.pack-ignore
  Packs/SpyCloud/.secrets-ignore
  Packs/SpyCloud/Author_image.png
  Packs/SpyCloud/Integrations/SpyCloud/README.md
  Packs/SpyCloud/Integrations/SpyCloud/SpyCloud.py
  Packs/SpyCloud/Integrations/SpyCloud/SpyCloud.yml
  Packs/SpyCloud/Integrations/SpyCloud/SpyCloud_description.md
  Packs/SpyCloud/Integrations/SpyCloud/SpyCloud_image.png
  Packs/SpyCloud/README.md
  Packs/SpyCloud/pack_metadata.json
Labels: docs-approved

#19008 Dou event collector XSIAM
  Packs/DuoAdminApi/Integrations/DuoEventCollector/DuoEventCollector.py
  Packs/DuoAdminApi/Integrations/DuoEventCollector/DuoEventCollector.yml
  Packs/DuoAdminApi/Integrations/DuoEventCollector/DuoEventCollector_description.md
  Packs/DuoAdminApi/Integrations/DuoEventCollector/DuoEventCollector_image.png
  Packs/DuoAdminApi/Integrations/DuoEventCollector/DuoEventCollector_test.py
  Packs/DuoAdminApi/Integrations/DuoEventCollector/README.md
  Packs/DuoAdminApi/ModelingRules/DuoModelingRule/DuoModelingRule.xif
  Packs/DuoAdminApi/ModelingRules/DuoModelingRule/DuoModelingRule.yml
  Packs/DuoAdminApi/ReleaseNotes/3_0_0.md
  Packs/DuoAdminApi/pack_metadata.json
Labels: docs-approved

#19395 Red Hat pack metadata files
  Packs/RedHat/README.md
  Packs/RedHat/pack_metadata.json
Labels: docs-approved

#19409 remove "filter" object key
  Packs/Base/ReleaseNotes/1_30_11.md
  Packs/Base/Scripts/SearchIndicatorRelationships/SearchIndicatorRelationships.py
  Packs/Base/Scripts/SearchIndicatorRelationships/SearchIndicatorRelationships.yml
  Packs/Base/Scripts/SearchIndicatorRelationships/SearchIndicatorRelationships_test.py
  Packs/Base/pack_metadata.json
Labels: docs-approved

#19384 Little fix for the description of Server URL parameter.
  Packs/IBMResilientSystems/Integrations/IBMResilientSystems/IBMResilientSystems.yml
  Packs/IBMResilientSystems/ReleaseNotes/1_0_10.md
  Packs/IBMResilientSystems/pack_metadata.json
Labels: Contribution, docs-approved, Contribution Form Filled, Community

#19346 Update integrate Help file
  Packs/Unit42Intel/Integrations/FeedUnit42IntelObjects/FeedUnit42IntelObjects_description.md
  Packs/Unit42Intel/ReleaseNotes/1_0_3.md
  Packs/Unit42Intel/pack_metadata.json
Labels: Contribution, Contribution Form Filled, Community

#19381 Fix error to get script to work on particular MIME entity file type
  Packs/CommonScripts/ReleaseNotes/1_6_71.md
  Packs/CommonScripts/Scripts/ParseEmailFiles/ParseEmailFiles.py
  Packs/CommonScripts/pack_metadata.json
Labels: Contribution, ready-for-instance-test, Contribution Form Filled, Community

#19366 [Fix] splunk-kv-store-collection-search-entry not working with values containing substring "limit"
  Packs/SplunkPy/Integrations/SplunkPy/SplunkPy.py
  Packs/SplunkPy/ReleaseNotes/2_4_4.md
  Packs/SplunkPy/pack_metadata.json
Labels: docs-approved

#19385 Mark defaultRegion param as mandatory
  Packs/AWS-GuardDuty/Integrations/AWSGuardDuty/AWSGuardDuty.yml
  Packs/AWS-GuardDuty/Integrations/AWSGuardDuty/README.md
  Packs/AWS-GuardDuty/ReleaseNotes/1_2_6.json
  Packs/AWS-GuardDuty/ReleaseNotes/1_2_6.md
  Packs/AWS-GuardDuty/pack_metadata.json
Labels: Contribution, docs-approved, ready-for-instance-test, Contribution Form Filled, Community

#19397 Update Oracle Pack Readme
  Packs/Oracle/README.md
Labels: docs-approved

#19398 MySQL Enterprise Pack Readme Update
  Packs/MySQLEnterprise/README.md
Labels: docs-approved

#19297 MS Exchange Server - modeling rule
  Packs/MicrosoftExchangeServer/.pack-ignore
  Packs/MicrosoftExchangeServer/.secrets-ignore
  Packs/MicrosoftExchangeServer/ModelingRules/MicrosoftExchangeServerModeling/MicrosoftExchangeModeling.xif
  Packs/MicrosoftExchangeServer/ModelingRules/MicrosoftExchangeServerModeling/MicrosoftExchangeModeling.yml
  Packs/MicrosoftExchangeServer/README.md
  Packs/MicrosoftExchangeServer/pack_metadata.json
Labels: docs-approved

#19444 demisto-sdk lint hotfix
  Packs/GitHub/Integrations/GitHubEventCollector/GitHubEventCollector.py
  Packs/GitHub/ReleaseNotes/2_0_3.md
  Packs/GitHub/pack_metadata.json
  Packs/PhishLabs/Integrations/PhishLabsIOC/PhishLabsIOC.py
  Packs/PhishLabs/ReleaseNotes/1_1_10.md
  Packs/PhishLabs/pack_metadata.json
  dev-requirements-py3.txt
Labels: docs-approved, ForceMerge

#19413 fix for pb and added rasterize to test
  Packs/Phishing/Playbooks/Phishing_-_Generic_v3.yml
  Packs/Phishing/ReleaseNotes/3_2_2.md
  Packs/Phishing/pack_metadata.json
  Tests/conf.json
Labels: docs-approved, release-notes-only

#19311 Add GetErrors PB Error Handling Utility Script
  Packs/CommonScripts/.pack-ignore
  Packs/CommonScripts/ReleaseNotes/1_7_0.md
  Packs/CommonScripts/Scripts/GetErrorsFromEntry/GetErrorsFromEntry.py
  Packs/CommonScripts/Scripts/GetErrorsFromEntry/GetErrorsFromEntry.yml
  Packs/CommonScripts/Scripts/GetErrorsFromEntry/GetErrorsFromEntry_test.py
  Packs/CommonScripts/Scripts/GetErrorsFromEntry/README.md
  Packs/CommonScripts/pack_metadata.json
Labels: docs-approved

#19403 Contrib/CDS Flashpoint Add Bearer
  Packs/Flashpoint/Integrations/Flashpoint/Flashpoint.py
  Packs/Flashpoint/ReleaseNotes/1_3_3.md
  Packs/Flashpoint/pack_metadata.json
Labels: Contribution, docs-approved, Partner, Contribution Form Filled

#19399 Illusive connector
  Packs/IllusiveNetworks/ModelingRules/IllusiveNetworks/illusiveModelingRules.xif
  Packs/IllusiveNetworks/ModelingRules/IllusiveNetworks/illusiveModelingRules.yml
  Packs/IllusiveNetworks/README.md
  Packs/IllusiveNetworks/ReleaseNotes/1_0_17.md
  Packs/IllusiveNetworks/pack_metadata.json
Labels: docs-approved

#19460 Proofpoint TAP - Added 'Proofpoint TAP Long Subject' incident field
  Packs/ProofpointTAP/Classifiers/classifier-ProofPointTAP_Mapper.json
  Packs/ProofpointTAP/IncidentFields/incidentfield-ProofPointTAP_Long_Subject.json
  Packs/ProofpointTAP/Layouts/layoutscontainer-ProofPointTAP_Message_Layout.json
  Packs/ProofpointTAP/ReleaseNotes/1_1_17.md
  Packs/ProofpointTAP/pack_metadata.json
Labels: docs-approved

#19402 readme xsiam
  Packs/jamf/README.md
Labels: docs-approved

#19440 Update SaaS Security modeling rule
  Packs/PrismaSaasSecurity/.pack-ignore
  Packs/PrismaSaasSecurity/ModelingRules/SaasSecurityEventCollector/SaasSecurityModelingRules.xif
  Packs/PrismaSaasSecurity/ReleaseNotes/2_0_1.md
  Packs/PrismaSaasSecurity/pack_metadata.json
Labels: docs-approved

#19462 Fix modeling rule
  Packs/RedHat/ModelingRules/RedHatEventsCollectorBrokerVM/RedHatEventsCollectorBrokerVM.xif
  Packs/RedHat/ModelingRules/RedHatEventsCollectorBrokerVM/RedHatEventsCollectorBrokerVM.yml
  Packs/RedHat/ModelingRules/RedHatEventsCollectorXDRC/RedHatEventsCollectorXDRC.xif
  Packs/RedHat/ModelingRules/RedHatEventsCollectorXDRC/RedHatEventsCollectorXDRC.yml
Labels: docs-approved

#19394 [Automox] Fix for vulnerability file upload command
  Packs/Automox/Integrations/Automox/Automox.py
  Packs/Automox/Integrations/Automox/Automox.yml
  Packs/Automox/Integrations/Automox/Automox_test.py
  Packs/Automox/ReleaseNotes/1_0_1.md
  Packs/Automox/pack_metadata.json
Labels: Contribution, docs-approved, Partner, ready-for-instance-test, pending-demo, post-demo, Contribution Form Filled, pending-contributor

#19400 ServiceNowV2 - Rollbacked the removal of the 'sn_si_incident' ticket type
  Packs/ServiceNow/Integrations/ServiceNowv2/ServiceNowv2.yml
  Packs/ServiceNow/ReleaseNotes/2_3_11.md
  Packs/ServiceNow/pack_metadata.json
Labels: docs-approved

#16724 Add API Metrics Reporting Support to CommonServer
  Packs/Base/.secrets-ignore
  Packs/Base/ReleaseNotes/1_31_0.md
  Packs/Base/Scripts/CommonServerPython/CommonServerPython.py
  Packs/Base/Scripts/CommonServerPython/CommonServerPython_test.py
  Packs/Base/pack_metadata.json
  Packs/CommonDashboards/Dashboards/dashboard-APIExecutionMetrics.json
  Packs/CommonDashboards/ReleaseNotes/1_2_0.md
  Packs/CommonDashboards/pack_metadata.json
  Packs/DeveloperTools/.pack-ignore
  Packs/DeveloperTools/Dashboards/dashboard-Metrics_Test_Cases_Validation.json
  Packs/DeveloperTools/Integrations/APIMetricsValidation/APIMetricsValidation.py
  Packs/DeveloperTools/Integrations/APIMetricsValidation/APIMetricsValidation.yml
  Packs/DeveloperTools/Integrations/APIMetricsValidation/APIMetricsValidation_description.md
  Packs/DeveloperTools/Integrations/APIMetricsValidation/APIMetricsValidation_image.png
  Packs/DeveloperTools/Integrations/APIMetricsValidation/APIMetricsValidation_test.py
  Packs/DeveloperTools/Integrations/APIMetricsValidation/Pipfile
  Packs/DeveloperTools/Integrations/APIMetricsValidation/Pipfile.lock
  Packs/DeveloperTools/Integrations/APIMetricsValidation/README.md
  Packs/DeveloperTools/ReleaseNotes/1_2_21.md
  Packs/DeveloperTools/TestPlaybooks/playbook-Metrics_Test_Case_Validation.yml
  Packs/DeveloperTools/pack_metadata.json
  Packs/QRadar/Integrations/QRadar_v3/QRadar_v3_test.py
Labels: docs-approved

#19438 Reversing labs a1000v2 action update
  Packs/ReversingLabs_A1000/Integrations/ReversingLabsA1000v2/README.md
  Packs/ReversingLabs_A1000/Integrations/ReversingLabsA1000v2/ReversingLabsA1000v2.py
  Packs/ReversingLabs_A1000/Integrations/ReversingLabsA1000v2/ReversingLabsA1000v2.yml
  Packs/ReversingLabs_A1000/ReleaseNotes/2_0_4.md
  Packs/ReversingLabs_A1000/pack_metadata.json
Labels: Contribution, docs-approved, Partner, ready-for-instance-test, Contribution Form Filled, pending-contributor

#19469 Adding modeling rules for Linux Events Collection
  Packs/LinuxEventsCollection/.pack-ignore
  Packs/LinuxEventsCollection/.secrets-ignore
  Packs/LinuxEventsCollection/ModelingRules/LinuxEventsCollection/LinuxEventsCollectionModelingRules.xif
  Packs/LinuxEventsCollection/ModelingRules/LinuxEventsCollection/LinuxEventsCollectionModelingRules.yml
  Packs/LinuxEventsCollection/README.md
  Packs/LinuxEventsCollection/pack_metadata.json
Labels: docs-approved

#19362 Microsoft ECM
  Packs/MicrosoftECM/ModelingRules/MicrosoftECM/MicrosoftECMModelingRules.xif
  Packs/MicrosoftECM/ModelingRules/MicrosoftECM/MicrosoftECMModelingRules.yml
  Packs/MicrosoftECM/README.md
  Packs/MicrosoftECM/ReleaseNotes/1_0_4.md
  Packs/MicrosoftECM/pack_metadata.json
Labels: docs-approved

#19435 Cyber ark xsiam Demo fixes
  Packs/CyberArkIdentity/Integrations/CyberArkIdentityEventCollector/CyberArkIdentityEventCollector.py
  Packs/CyberArkIdentity/Integrations/CyberArkIdentityEventCollector/CyberArkIdentityEventCollector.yml
  Packs/CyberArkIdentity/Integrations/CyberArkIdentityEventCollector/CyberArkIdentityEventCollector_description.md
  Packs/CyberArkIdentity/Integrations/CyberArkIdentityEventCollector/README.md
  Packs/CyberArkIdentity/ModelingRules/CyberArkIdentityEventCollector/CyberArkIdentityEventCollector.xif
  Packs/CyberArkIdentity/ReleaseNotes/1_0_1.md
  Packs/CyberArkIdentity/pack_metadata.json
Labels: docs-approved

#18908 Addition of other fundamentals to ACTI Indicator Query integration
  Packs/AccentureCTI/IndicatorFields/indicatorfield-ACTI_Abstract.json
  Packs/AccentureCTI/IndicatorFields/indicatorfield-ACTI_Analysis.json
  Packs/AccentureCTI/IndicatorFields/indicatorfield-ACTI_Index_Timestamp.json
  Packs/AccentureCTI/IndicatorFields/indicatorfield-ACTI_Last_Modified.json
  Packs/AccentureCTI/IndicatorFields/indicatorfield-ACTI_Last_Published.json
  Packs/AccentureCTI/IndicatorFields/indicatorfield-ACTI_Report_Title.json
  Packs/AccentureCTI/IndicatorFields/indicatorfield-ACTI_Severity.json
  Packs/AccentureCTI/IndicatorFields/indicatorfield-ACTI_Threat_Types.json
  Packs/AccentureCTI/IndicatorFields/indicatorfield-ACTI_UUID.json
  Packs/AccentureCTI/IndicatorTypes/indicatortype-ACTI_Malware_Family.json
  Packs/AccentureCTI/IndicatorTypes/indicatortype-ACTI_Threat_Actor.json
  Packs/AccentureCTI/IndicatorTypes/indicatortype-ACTI_Threat_Campaign.json
  Packs/AccentureCTI/IndicatorTypes/indicatortype-ACTI_Threat_Group.json
  Packs/AccentureCTI/Integrations/ACTIIndicatorQuery/ACTIIndicatorQuery.py
  Packs/AccentureCTI/Integrations/ACTIIndicatorQuery/ACTIIndicatorQuery.yml
  Packs/AccentureCTI/Integrations/ACTIIndicatorQuery/ACTIIndicatorQuery_test.py
  Packs/AccentureCTI/Integrations/ACTIIndicatorQuery/README.md
  Packs/AccentureCTI/Integrations/ACTIIndicatorQuery/test_data/response_constants.py
  Packs/AccentureCTI/Layouts/layoutscontainer-ACTI_Malware_Family.json
  Packs/AccentureCTI/Layouts/layoutscontainer-ACTI_Threat_Actor.json
  Packs/AccentureCTI/Layouts/layoutscontainer-ACTI_Threat_Campaign.json
  Packs/AccentureCTI/Layouts/layoutscontainer-ACTI_Threat_Group.json
  Packs/AccentureCTI/Playbooks/playbook-ACTI_Block_High_Severity_Indicators.yml
  Packs/AccentureCTI/Playbooks/playbook-ACTI_Block_High_Severity_Indicators_README.md
  Packs/AccentureCTI/Playbooks/playbook-ACTI_Block_Indicators_from_an_Incident.yml
  Packs/AccentureCTI/Playbooks/playbook-ACTI_Block_Indicators_from_an_Incident_README.md
  Packs/AccentureCTI/Playbooks/playbook-ACTI_Create_Report-Indicator_Associations.yml
  Packs/AccentureCTI/Playbooks/playbook-ACTI_Create_Report-Indicator_Associations_README.md
  Packs/AccentureCTI/Playbooks/playbook-ACTI_Incident_Enrichment.yml
  Packs/AccentureCTI/Playbooks/playbook-ACTI_Incident_Enrichment_README.md
  Packs/AccentureCTI/Playbooks/playbook-ACTI_Indicator_Enrichment.yml
  Packs/AccentureCTI/Playbooks/playbook-ACTI_Indicator_Enrichment_README.md
  Packs/AccentureCTI/Playbooks/playbook-ACTI_Report_Enrichment.yml
  Packs/AccentureCTI/Playbooks/playbook-ACTI_Report_Enrichment_README.md
  Packs/AccentureCTI/Playbooks/playbook-ACTI_Vulnerability_Enrichment.yml
  Packs/AccentureCTI/Playbooks/playbook-ACTI_Vulnerability_Enrichment_README.md
  Packs/AccentureCTI/README.md
  Packs/AccentureCTI/ReleaseNotes/2_2_0.md
  Packs/AccentureCTI/pack_metadata.json
Labels: Contribution, Partner, post-demo, Contribution Form Filled

#19502 Deleted rhel
  Packs/RedHat/.pack-ignore
  Packs/RedHat/.secrets-ignore
  Packs/RedHat/ModelingRules/RedHatEventsCollectorBrokerVM/RedHatEventsCollectorBrokerVM.xif
  Packs/RedHat/ModelingRules/RedHatEventsCollectorBrokerVM/RedHatEventsCollectorBrokerVM.yml
  Packs/RedHat/ModelingRules/RedHatEventsCollectorXDRC/RedHatEventsCollectorXDRC.xif
  Packs/RedHat/ModelingRules/RedHatEventsCollectorXDRC/RedHatEventsCollectorXDRC.yml
  Packs/RedHat/README.md
  Packs/RedHat/pack_metadata.json
Labels: docs-approved

#18851 Cloudflare waf integration
  .gitignore
  Packs/CloudflareWAF/.pack-ignore
  Packs/CloudflareWAF/.secrets-ignore
  Packs/CloudflareWAF/Integrations/CloudflareWAF/CloudflareWAF.py
  Packs/CloudflareWAF/Integrations/CloudflareWAF/CloudflareWAF.yml
  Packs/CloudflareWAF/Integrations/CloudflareWAF/CloudflareWAF_description.md
  Packs/CloudflareWAF/Integrations/CloudflareWAF/CloudflareWAF_image.png
  Packs/CloudflareWAF/Integrations/CloudflareWAF/CloudflareWAF_test.py
  Packs/CloudflareWAF/Integrations/CloudflareWAF/README.md
  Packs/CloudflareWAF/Integrations/CloudflareWAF/test_data/create_filter.json
  Packs/CloudflareWAF/Integrations/CloudflareWAF/test_data/create_firewall_rule.json
  Packs/CloudflareWAF/Integrations/CloudflareWAF/test_data/create_ip_list.json
  Packs/CloudflareWAF/Integrations/CloudflareWAF/test_data/delete_filter.json
  Packs/CloudflareWAF/Integrations/CloudflareWAF/test_data/delete_firewall_rule.json
  Packs/CloudflareWAF/Integrations/CloudflareWAF/test_data/delete_ip_list.json
  Packs/CloudflareWAF/Integrations/CloudflareWAF/test_data/ip_list_item.json
  Packs/CloudflareWAF/Integrations/CloudflareWAF/test_data/list_filter.json
  Packs/CloudflareWAF/Integrations/CloudflareWAF/test_data/list_firewall_rule.json
  Packs/CloudflareWAF/Integrations/CloudflareWAF/test_data/list_item_ip_list.json
  Packs/CloudflareWAF/Integrations/CloudflareWAF/test_data/list_zone.json
  Packs/CloudflareWAF/Integrations/CloudflareWAF/test_data/lists_ip_list.json
  Packs/CloudflareWAF/README.md
  Packs/CloudflareWAF/TestPlaybooks/playbook-TestCloudflareWAFPlaybook_Test.yml
  Packs/CloudflareWAF/pack_metadata.json
  Tests/conf.json
  dev-requirements-py3.txt
Labels: Contribution, docs-approved, ready-for-instance-test, pending-contributor

#19163 Create pack readme for Crowdstrike Falcon X
  Packs/CrowdStrikeFalconX/README.md
Labels: docs-approved

#18274 First commit of new Manual EDL Change pack
  Packs/EDL/IncidentFields/incidentfield-EDL_Action.json
  Packs/EDL/IncidentFields/incidentfield-EDL_Indicator_Type.json
  Packs/EDL/IncidentFields/incidentfield-EDL_Indicators_List.json
  Packs/EDL/IncidentFields/incidentfield-EDL_Tag.json
  Packs/EDL/IncidentTypes/incidenttype-EDL_Change.json
  Packs/EDL/Layouts/layoutscontainer-EDL_Change_Layout.json
  Packs/EDL/Playbooks/Modify_EDL.yml
  Packs/EDL/Playbooks/Modify_EDL_README.md
  Packs/EDL/README.md
  Packs/EDL/ReleaseNotes/3_1_4.md
  Packs/EDL/doc_files/Modify_EDL.png
  Packs/EDL/pack_metadata.json
Labels: Contribution, post-demo, Contribution Form Filled, Community

#19509 Deprecate traps
  Packs/Traps/Integrations/PaloAlto_TrapsESM_Beta/PaloAlto_TrapsESM_Beta.yml
  Packs/Traps/Playbooks/playbook-Block_File_-_Quarantine_-_Traps.yml
  Packs/Traps/Playbooks/playbook-Isolate_Endpoint_-_Traps.yml
  Packs/Traps/Playbooks/playbook-Traps_Blacklist_File.yml
  Packs/Traps/Playbooks/playbook-Traps_Retrieve_And_Download_Files.yml
  Packs/Traps/Playbooks/playbook-Traps_Scan_Endpoint.yml
  Packs/Traps/ReleaseNotes/1_0_10.md
  Packs/Traps/pack_metadata.json
Labels: docs-approved

#19412 Ne xdr prevent only mode
  Packs/CortexXDR/Integrations/CortexXDRIR/CortexXDRIR.py
  Packs/CortexXDR/Integrations/CortexXDRIR/CortexXDRIR.yml
  Packs/CortexXDR/ReleaseNotes/4_6_3.md
  Packs/CortexXDR/pack_metadata.json
Labels: Contribution, docs-approved, ready-for-instance-test, Contribution Form Filled, Community, pending-contributor

#19406 Gitlab fix
  Packs/GitLab/Integrations/GitLabEventCollector/GitLabEventCollector.py
  Packs/GitLab/Integrations/GitLabEventCollector/GitLabEventCollector_test.py
  Packs/GitLab/ModelingRules/GitlabModelingRules/GitlabModelingRules.xif
  Packs/GitLab/ModelingRules/GitlabModelingRules/GitlabModelingRules.yml
Labels: docs-approved, ForceMerge

#19248 Microsoft iis web server
  Packs/MicrosoftIISWebServer/ModelingRules/MicrosoftIISWebServerModelingRules.xif
  Packs/MicrosoftIISWebServer/ModelingRules/MicrosoftIISWebServerModelingRules.yml
  Packs/MicrosoftIISWebServer/ModelingRules/README.md
  Packs/MicrosoftIISWebServer/ModelingRules/pack_metadata.json
Labels: Contribution, docs-approved, Contribution Form Filled

#19254 Apache Tomcat
  ApacheTomcat/ModelingRules/ApacheTomcatModelingRules.xif
  ApacheTomcat/ModelingRules/ApacheTomcatModelingRules.yml
  ApacheTomcat/ModelingRules/README.md
  ApacheTomcat/ModelingRules/pack_metadata.json
Labels: Contribution, docs-approved, Contribution Form Filled

#19260 Juniper SRX
  Packs/JuniperSRX/ModelingRules/JuniperSRXModelingRules.xif
  Packs/JuniperSRX/ModelingRules/JuniperSRXModelingRules.yml
  Packs/JuniperSRX/ModelingRules/README.md
  Packs/JuniperSRX/ModelingRules/pack_metadata.json
Labels: Contribution, docs-approved, Contribution Form Filled

#19263 NGINXWebServer
  Packs/NGINXWebServer/ModelingRules/NGINXWebServerModelingRules.xif
  Packs/NGINXWebServer/ModelingRules/NGINXWebServerModelingRules.yml
  Packs/NGINXWebServer/ModelingRules/README.md
  Packs/NGINXWebServer/ModelingRules/pack_metadata.json
Labels: Contribution, docs-approved, Contribution Form Filled

#19249 ApacheWebServer
  Packs/ApacheWebServer/ModelingRules/ApacheWebServerModelingRules.xif
  Packs/ApacheWebServer/ModelingRules/ApacheWebServerModelingRules.yml
  Packs/ApacheWebServer/ModelingRules/README.md
  Packs/ApacheWebServer/ModelingRules/pack_metadata.json
Labels: Contribution, docs-approved, Contribution Form Filled

#19257 F5ASM
  Packs/F5ASM/ModelingRules/F5ASMModelingRules.xif
  Packs/F5ASM/ModelingRules/F5ASMModelingRules.yml
  Packs/F5ASM/ModelingRules/README.md
  Packs/F5ASM/ModelingRules/pack_metadata.json
Labels: Contribution, docs-approved, Contribution Form Filled

#19505 Update README.md
  Packs/MySQLEnterprise/README.md
Labels: docs-approved

#19115 added adoption scripts
  Utils/adopt_pack.bash
  Utils/adopt_utils.bash
Labels: docs-approved

#19189 Prisma pb update
  Packs/PrismaCloud/Classifiers/classifier-Prisma_Cloud.json
  Packs/PrismaCloud/Classifiers/classifier-mapper-incoming-Prisma_Cloud.json
  Packs/PrismaCloud/Playbooks/playbook-PCR_-_AWS_EC2_Instance_Misconfig.yml
  Packs/PrismaCloud/Playbooks/playbook-PCR_-_AWS_EC2_Instance_Misconfig_README.md
  Packs/PrismaCloud/Playbooks/playbook-PCR_-_AWS_EC2_SG_Misconfig.yml
  Packs/PrismaCloud/Playbooks/playbook-PCR_-_AWS_EC2_SG_Misconfig_README.md
  Packs/PrismaCloud/ReleaseNotes/2_0_10.md
  Packs/PrismaCloud/pack_metadata.json
Labels: Contribution, docs-approved, pending-demo, post-demo, Contribution Form Filled, Community, pending-contributor

#19506 ReadPDFFileV2 bug fix
  Packs/CommonScripts/ReleaseNotes/1_7_2.md
  Packs/CommonScripts/Scripts/ReadPDFFileV2/ReadPDFFileV2.py
  Packs/CommonScripts/Scripts/ReadPDFFileV2/ReadPDFFileV2.yml
  Packs/CommonScripts/pack_metadata.json
Labels: docs-approved

#19197 Securonix Pack Adoption
  Packs/Securonix/README.md
  Packs/Securonix/ReleaseNotes/1_1_12.md
  Packs/Securonix/pack_metadata.json
Labels: Contribution, docs-approved, pending-contributor

#19151 Implementation used with threads in gmail-search-all-mailboxes command
  Packs/Gmail/Integrations/Gmail/Gmail.py
  Packs/Gmail/Integrations/Gmail/Gmail.yml
  Packs/Gmail/Integrations/Gmail/README.md
  Packs/Gmail/ReleaseNotes/1_1_17.md
  Packs/Gmail/pack_metadata.json
Labels: docs-approved

#19532 Add XDR owner
  .github/CODEOWNERS
Labels: docs-approved

#17717 Contrib/mikerizzo email communication
  Packs/EmailCommunication/.pack-ignore
  Packs/EmailCommunication/.secrets-ignore
  Packs/EmailCommunication/CONTRIBUTORS.md
  Packs/EmailCommunication/IncidentFields/incidentfield-Add_BCC_To_Email.json
  Packs/EmailCommunication/IncidentFields/incidentfield-Email_Generated_Codes.json
  Packs/EmailCommunication/IncidentFields/incidentfield-Email_New_Attachment.json
  Packs/EmailCommunication/IncidentFields/incidentfield-Email_New_Body.json
  Packs/EmailCommunication/IncidentFields/incidentfield-Email_New_Recipients.json
  Packs/EmailCommunication/IncidentFields/incidentfield-Email_New_Subject.json
  Packs/EmailCommunication/IncidentFields/incidentfield-Email_Selected_Thread.json
  Packs/EmailCommunication/Layouts/layoutscontainer-Email_Threads.json
  Packs/EmailCommunication/README.md
  Packs/EmailCommunication/ReleaseNotes/2_0_0.md
  Packs/EmailCommunication/Scripts/DisplayEmailHtml/DisplayEmailHtml.yml
  Packs/EmailCommunication/Scripts/DisplayEmailHtmlThread/DisplayEmailHtmlThread.py
  Packs/EmailCommunication/Scripts/DisplayEmailHtmlThread/DisplayEmailHtmlThread.yml
  Packs/EmailCommunication/Scripts/DisplayEmailHtmlThread/DisplayEmailHtmlThread_test.py
  Packs/EmailCommunication/Scripts/DisplayEmailHtmlThread/README.md
  Packs/EmailCommunication/Scripts/DisplayEmailHtmlThread/test_data/cleaned_html.txt
  Packs/EmailCommunication/Scripts/DisplayEmailHtmlThread/test_data/email_threads.json
  Packs/EmailCommunication/Scripts/DisplayEmailHtmlThread/test_data/good_result.txt
  Packs/EmailCommunication/Scripts/DisplayEmailHtmlThread/test_data/multiple_html_docs.txt
  Packs/EmailCommunication/Scripts/DisplayEmailHtmlThread/test_data/single_html_doc.txt
  Packs/EmailCommunication/Scripts/PreprocessEmail/PreprocessEmail.py
  Packs/EmailCommunication/Scripts/PreprocessEmail/PreprocessEmail.yml
  Packs/EmailCommunication/Scripts/PreprocessEmail/PreprocessEmail_test.py
  Packs/EmailCommunication/Scripts/PreprocessEmail/test_data/email_related_incident_response_2.json
  Packs/EmailCommunication/Scripts/PreprocessEmail/test_data/getList_querywindow_error.json
  Packs/EmailCommunication/Scripts/PreprocessEmail/test_data/getList_querywindow_success.json
  Packs/EmailCommunication/Scripts/SendEmailReply/README.md
  Packs/EmailCommunication/Scripts/SendEmailReply/SendEmailReply.py
  Packs/EmailCommunication/Scripts/SendEmailReply/SendEmailReply.yml
  Packs/EmailCommunication/Scripts/SendEmailReply/SendEmailReply_test.py
  Packs/EmailCommunication/Scripts/SendEmailReply/test_data/email_threads.json
  Packs/EmailCommunication/Scripts/SendEmailReply/test_data/getList_querywindow_error.json
  Packs/EmailCommunication/Scripts/SendEmailReply/test_data/getList_querywindow_success.json
  Packs/EmailCommunication/Scripts/SendEmailReply/test_data/getList_signature_error.json
  Packs/EmailCommunication/Scripts/SendEmailReply/test_data/getList_signature_success.json
  Packs/EmailCommunication/Scripts/SendEmailReply/test_data/incident_data.json
  Packs/EmailCommunication/Scripts/SummarizeEmailThreads/README.md
  Packs/EmailCommunication/Scripts/SummarizeEmailThreads/SummarizeEmailThreads.py
  Packs/EmailCommunication/Scripts/SummarizeEmailThreads/SummarizeEmailThreads.yml
  Packs/EmailCommunication/Scripts/SummarizeEmailThreads/SummarizeEmailThreads_test.py
  Packs/EmailCommunication/Scripts/SummarizeEmailThreads/test_data/email_threads.json
  Packs/EmailCommunication/Scripts/SummarizeEmailThreads/test_data/valid_table_data.txt
  Packs/EmailCommunication/pack_metadata.json
Labels: Contribution, ready-for-instance-test, Contribution Form Filled, Community

#19103 EWS - Adding O365 Tenant Allow/Block List Management
  Packs/EWS/CONTRIBUTORS.md
  Packs/EWS/Integrations/EwsExtensionEXOPowershellV2/EwsExtensionEXOPowershellV2.ps1
  Packs/EWS/Integrations/EwsExtensionEXOPowershellV2/EwsExtensionEXOPowershellV2.yml
  Packs/EWS/Integrations/EwsExtensionEXOPowershellV2/README.md
  Packs/EWS/README.md
  Packs/EWS/ReleaseNotes/1_12_0.md
  Packs/EWS/pack_metadata.json
Labels: Contribution, docs-approved, Contribution Form Filled, Community

#19411 Add API Metrics Reporting + Widget to VTv3
  Packs/VirusTotal/.pack-ignore
  Packs/VirusTotal/.secrets-ignore
  Packs/VirusTotal/Dashboards/dashboard-VirusTotal_API_Execution_Metrics.json
  Packs/VirusTotal/Integrations/VirusTotalV3/README.md
  Packs/VirusTotal/Integrations/VirusTotalV3/VirusTotalV3.py
  Packs/VirusTotal/Integrations/VirusTotalV3/VirusTotalV3.yml
  Packs/VirusTotal/Integrations/VirusTotalV3/VirusTotalV3_test.py
  Packs/VirusTotal/Integrations/VirusTotalV3/test_data/comminicating_files.json
  Packs/VirusTotal/Integrations/VirusTotalV3/test_data/domain.json
  Packs/VirusTotal/Integrations/VirusTotalV3/test_data/domain_results.json
  Packs/VirusTotal/Integrations/VirusTotalV3/test_data/file.json
  Packs/VirusTotal/Integrations/VirusTotalV3/test_data/ip.json
  Packs/VirusTotal/Integrations/VirusTotalV3/test_data/ip_results.json
  Packs/VirusTotal/Integrations/VirusTotalV3/test_data/relationships.json
  Packs/VirusTotal/Integrations/VirusTotalV3/test_data/url.json
  Packs/VirusTotal/Integrations/VirusTotalV3/test_data/url_results.json
  Packs/VirusTotal/ReleaseNotes/2_4_3.md
  Packs/VirusTotal/Widgets/Widget-API_Call_Results_for_VirusTotalV3.json
  Packs/VirusTotal/pack_metadata.json
Labels: docs-approved

#19363 Brocade Switch pack
  Packs/BrocadeSwitch/.pack-ignore
  Packs/BrocadeSwitch/.secrets-ignore
  Packs/BrocadeSwitch/ModelingRules/BrocadeSwitch/BrocadeSwitchModelingRules.xif
  Packs/BrocadeSwitch/ModelingRules/BrocadeSwitch/BrocadeSwitchModelingRules.yml
  Packs/BrocadeSwitch/README.md
  Packs/BrocadeSwitch/pack_metadata.json
Labels: docs-approved

#19565 Add that Phishing pack is required for Phishing Alerts pack
  Packs/PhishingAlerts/README.md
Labels: docs-approved

#19564 MS graph fix wipe device command
  Packs/MicrosoftGraphDeviceManagement/Integrations/MicrosoftGraphDeviceManagement/MicrosoftGraphDeviceManagement.py
  Packs/MicrosoftGraphDeviceManagement/ReleaseNotes/1_0_18.md
  Packs/MicrosoftGraphDeviceManagement/pack_metadata.json
Labels: docs-approved

#19480 Add MalwareInvestigationToTable `Waiting on entries` message
  Packs/MalwareInvestigationAndResponse/ReleaseNotes/1_5_3.md
  Packs/MalwareInvestigationAndResponse/Scripts/InvestigationSummaryToTable/InvestigationSummaryToTable.py
  Packs/MalwareInvestigationAndResponse/Scripts/InvestigationSummaryToTable/InvestigationSummaryToTable.yml
  Packs/MalwareInvestigationAndResponse/Scripts/InvestigationSummaryToTable/InvestigationSummaryToTable_test.py
  Packs/MalwareInvestigationAndResponse/pack_metadata.json
Labels: docs-approved

#19556 switch dep
  dev-requirements-py3.txt
Labels: docs-approved

#19332 MIcorosft NPS pack
  Packs/MicrosoftNPS/.pack-ignore
  Packs/MicrosoftNPS/.secrets-ignore
  Packs/MicrosoftNPS/ModelingRules/MicrosoftNPS/MicrosoftNPSModelingRules.xif
  Packs/MicrosoftNPS/ModelingRules/MicrosoftNPS/MicrosoftNPSModelingRules.yml
  Packs/MicrosoftNPS/README.md
  Packs/MicrosoftNPS/pack_metadata.json
Labels: docs-approved

#19527 Deprecate ExportIndicators/MicrosoftPolicyAndCompliance/Expanse/Cofense-Intelligence/TCPIPUtils
  Packs/Cofense-Intelligence/pack_metadata.json
  Packs/Expanse/Playbooks/Expanse_Behavior_Severity_Update.yml
  Packs/Expanse/Playbooks/Expanse_Incident_Playbook.yml
  Packs/Expanse/ReleaseNotes/1_2_4.md
  Packs/Expanse/Scripts/ExpanseParseRawIncident/ExpanseParseRawIncident.yml
  Packs/Expanse/pack_metadata.json
  Packs/ExportIndicators/pack_metadata.json
  Packs/MicrosoftPolicyAndCompliance/Playbooks/playbook-Azure_Configuration_Analysis.yml
  Packs/MicrosoftPolicyAndCompliance/Playbooks/playbook-Azure_Hunting_playbook.yml
  Packs/MicrosoftPolicyAndCompliance/ReleaseNotes/1_0_2.md
  Packs/MicrosoftPolicyAndCompliance/pack_metadata.json
Labels: docs-approved

#19559 Add information about Phishing content pack
  Packs/Phishing/README.md
Labels: docs-approved

#19569 Fix recorded future
  Packs/Recorded_Future/ReleaseNotes/1_1_5.md
  Packs/Recorded_Future/Scripts/script-RecordedFutureDomainRiskList.yml
  Packs/Recorded_Future/Scripts/script-RecordedFutureHashRiskList.yml
  Packs/Recorded_Future/Scripts/script-RecordedFutureIPRiskList.yml
  Packs/Recorded_Future/Scripts/script-RecordedFutureURLRiskList.yml
  Packs/Recorded_Future/Scripts/script-RecordedFutureVulnerabilityRiskList.yml
  Packs/Recorded_Future/pack_metadata.json
Labels: docs-approved

#18717 Azure log analytics client credentials
  Packs/AzureLogAnalytics/Integrations/AzureLogAnalytics/AzureLogAnalytics.py
  Packs/AzureLogAnalytics/Integrations/AzureLogAnalytics/AzureLogAnalytics.yml
  Packs/AzureLogAnalytics/Integrations/AzureLogAnalytics/AzureLogAnalytics_description.md
  Packs/AzureLogAnalytics/Integrations/AzureLogAnalytics/AzureLogAnalytics_test.py
  Packs/AzureLogAnalytics/Integrations/AzureLogAnalytics/README.md
  Packs/AzureLogAnalytics/ReleaseNotes/1_0_13.md
  Packs/AzureLogAnalytics/pack_metadata.json
Labels: docs-approved

#19365 Dropbox xsiam
  Packs/Dropbox/.pack-ignore
  Packs/Dropbox/.secrets-ignore
  Packs/Dropbox/Integrations/DropboxEventCollector/DropboxEventCollector.py
  Packs/Dropbox/Integrations/DropboxEventCollector/DropboxEventCollector.yml
  Packs/Dropbox/Integrations/DropboxEventCollector/DropboxEventCollector_description.md
  Packs/Dropbox/Integrations/DropboxEventCollector/DropboxEventCollector_image.png
  Packs/Dropbox/Integrations/DropboxEventCollector/DropboxEventCollector_test.py
  Packs/Dropbox/Integrations/DropboxEventCollector/Pipfile
  Packs/Dropbox/Integrations/DropboxEventCollector/Pipfile.lock
  Packs/Dropbox/Integrations/DropboxEventCollector/README.md
  Packs/Dropbox/Integrations/DropboxEventCollector/command_examples
  Packs/Dropbox/Integrations/DropboxEventCollector/test_data/events_1_.json
  Packs/Dropbox/Integrations/DropboxEventCollector/test_data/events_2_.json
  Packs/Dropbox/ModelingRules/DropboxEventCollector/DropboxEventCollector.xif
  Packs/Dropbox/ModelingRules/DropboxEventCollector/DropboxEventCollector.yml
  Packs/Dropbox/README.md
  Packs/Dropbox/doc_files/Screen Shot 2022-06-13 at 10.03.00.png
  Packs/Dropbox/doc_files/Screen Shot 2022-06-13 at 10.03.22.png
  Packs/Dropbox/doc_files/Screen Shot 2022-06-13 at 10.04.11.png
  Packs/Dropbox/doc_files/Screen Shot 2022-06-13 at 10.04.34.png
  Packs/Dropbox/pack_metadata.json
Labels: docs-approved

#19228 Contrib/hsue panw dlp integration1.2.0
  Packs/Palo_Alto_Networks_Enterprise_DLP/Integrations/Palo_Alto_Networks_Enterprise_DLP/Palo_Alto_Networks_Enterprise_DLP.py
  Packs/Palo_Alto_Networks_Enterprise_DLP/Integrations/Palo_Alto_Networks_Enterprise_DLP/Palo_Alto_Networks_Enterprise_DLP.yml
  Packs/Palo_Alto_Networks_Enterprise_DLP/Integrations/Palo_Alto_Networks_Enterprise_DLP/Palo_Alto_Networks_Enterprise_DLP_test.py
  Packs/Palo_Alto_Networks_Enterprise_DLP/Integrations/Palo_Alto_Networks_Enterprise_DLP/README.md
  Packs/Palo_Alto_Networks_Enterprise_DLP/Playbooks/DLP_Incident_Feedback_Loop.yml
  Packs/Palo_Alto_Networks_Enterprise_DLP/Playbooks/DLP_Incident_Feedback_Loop_README.md
  Packs/Palo_Alto_Networks_Enterprise_DLP/ReleaseNotes/1_2_0.json
  Packs/Palo_Alto_Networks_Enterprise_DLP/ReleaseNotes/1_2_0.md
  Packs/Palo_Alto_Networks_Enterprise_DLP/Scripts/DlpAskFeedback/DlpAskFeedback.py
  Packs/Palo_Alto_Networks_Enterprise_DLP/Scripts/DlpAskFeedback/DlpAskFeedback.yml
  Packs/Palo_Alto_Networks_Enterprise_DLP/Scripts/DlpAskFeedback/DlpAskFeedback_test.py
  Packs/Palo_Alto_Networks_Enterprise_DLP/Scripts/DlpAskFeedback/README.md
  Packs/Palo_Alto_Networks_Enterprise_DLP/pack_metadata.json
Labels: Contribution, docs-approved, Contribution Form Filled, Community, pending-contributor

#19566 [Google Pub/Sub] Improve Messages Decode
  Packs/GooglePubSub/Integrations/GooglePubSub/GooglePubSub.py
  Packs/GooglePubSub/Integrations/GooglePubSub/GooglePubSub.yml
  Packs/GooglePubSub/Integrations/GooglePubSub/GooglePubSub_test.py
  Packs/GooglePubSub/Integrations/GooglePubSub/test_data/commands_outputs.json
  Packs/GooglePubSub/Integrations/GooglePubSub/test_data/raw_responses.json
  Packs/GooglePubSub/ReleaseNotes/1_0_15.md
  Packs/GooglePubSub/pack_metadata.json
Labels: docs-approved

#19370 add id set filtering in xsoar job
  .gitlab/ci/global.yml
  .gitlab/ci/on-push.yml
  dev-requirements-py3.txt
Labels: docs-approved

#19561 Update deprecated dockers 1
  Packs/CommonWidgets/ReleaseNotes/1_2_7.md
  Packs/CommonWidgets/Scripts/RSSWidget/RSSWidget.yml
  Packs/CommonWidgets/pack_metadata.json
  Packs/Core/ReleaseNotes/1_2_3.md
  Packs/Core/Scripts/impossibleTravelerGetDistance/impossibleTravelerGetDistance.yml
  Packs/Core/pack_metadata.json
  Packs/CrowdStrikeFalconStreamingV2/Integrations/CrowdStrikeFalconStreamingV2/CrowdStrikeFalconStreamingV2.yml
  Packs/CrowdStrikeFalconStreamingV2/ReleaseNotes/1_1_2.md
  Packs/CrowdStrikeFalconStreamingV2/pack_metadata.json
  Packs/Elasticsearch/Integrations/Elasticsearch_v2/Elasticsearch_v2.yml
  Packs/Elasticsearch/ReleaseNotes/1_2_13.md
  Packs/Elasticsearch/pack_metadata.json
  Packs/FeedAWS/Integrations/FeedAWS/FeedAWS.yml
  Packs/FeedAWS/ReleaseNotes/1_1_14.md
  Packs/FeedAWS/pack_metadata.json
  Packs/FeedElasticsearch/Integrations/FeedElasticsearch/FeedElasticsearch.yml
  Packs/FeedElasticsearch/ReleaseNotes/1_0_21.md
  Packs/FeedElasticsearch/pack_metadata.json
  Packs/FeedFastly/Integrations/FeedFastly/FeedFastly.yml
  Packs/FeedFastly/ReleaseNotes/1_1_12.md
  Packs/FeedFastly/pack_metadata.json
  Packs/FeedRSS/Integrations/FeedRSS/FeedRSS.yml
  Packs/FeedRSS/ReleaseNotes/1_0_6.md
  Packs/FeedRSS/pack_metadata.json
  Packs/ImpossibleTraveler/ReleaseNotes/1_2_6.md
  Packs/ImpossibleTraveler/Scripts/CalculateGeoDistance/CalculateGeoDistance.py
  Packs/ImpossibleTraveler/Scripts/CalculateGeoDistance/CalculateGeoDistance.yml
  Packs/ImpossibleTraveler/Scripts/CalculateGeoDistance/README.md
  Packs/ImpossibleTraveler/pack_metadata.json
  Packs/MongoDB/Integrations/MongoDBLog/MongoDBLog.py
  Packs/MongoDB/Integrations/MongoDBLog/MongoDBLog.yml
  Packs/MongoDB/ReleaseNotes/1_2_9.md
  Packs/MongoDB/pack_metadata.json
  Packs/OpenLDAP/Integrations/OpenLDAP/OpenLDAP.yml
  Packs/OpenLDAP/ReleaseNotes/1_0_7.md
  Packs/OpenLDAP/pack_metadata.json
  Packs/Vertica/Integrations/Vertica/Vertica.yml
  Packs/Vertica/ReleaseNotes/1_0_3.md
  Packs/Vertica/pack_metadata.json
Labels: docs-approved

#19587 update CS Falcon README.md
  Packs/CrowdStrikeFalcon/Integrations/CrowdStrikeFalcon/README.md
Labels: docs-approved

#19588 Create content for RSAWitness pack readme
  Packs/RSANetWitness_v11_1/README.md
Labels: docs-approved

#19331 fix file names & parse correctly
  Packs/Microsoft365Defender/Integrations/Microsoft365DefenderEventCollector/Microsoft365DefenderEventCollector.py
  Packs/Microsoft365Defender/Integrations/Microsoft365DefenderEventCollector/Microsoft365DefenderEventCollector.yml
  Packs/Microsoft365Defender/ModelingRules/Microsoft365DefenderEventCollector/Microsoft365DefenderEventCollector.xif
  Packs/Microsoft365Defender/ModelingRules/Microsoft365DefenderEventCollector/Microsoft365DefenderEventCollector.yml
  Packs/Microsoft365Defender/ReleaseNotes/4_0_0.md
Labels: docs-approved

#17566 Cortex XSOAR replace name
  .gitlab/ci/on-push.yml
Labels: docs-approved

#19538 Adding more logs for better debugging
  Tests/scripts/wait_in_line_for_xsiam_env.sh
Labels: docs-approved

#19591 Fixed a bug with deleting email from the layout
  Packs/Phishing/Layouts/layoutscontainer-Phishing_v_3.json
  Packs/Phishing/ReleaseNotes/3_2_4.md
  Packs/Phishing/pack_metadata.json
Labels: docs-approved, release-notes-only

#19593 Build extras
  .circleci/config.yml
  .hooks/bootstrap
  poetry.lock
  pyproject.toml
Labels: docs-approved

#19534 Deprecate Jask/PaloAltoNetworks_Threat_Vault/SNDBOX/WindowsDefenderAdvancedThreatProtection/CrowdStrikeHost
  Packs/CrowdStrikeHost/Playbooks/playbook-CrowdStrike_Endpoint_Enrichment.yml
  Packs/CrowdStrikeHost/Playbooks/playbook-CrowdStrike_Rapid_IOC_Hunting_v2.yml
  Packs/CrowdStrikeHost/Playbooks/playbook-Search_Endpoints_By_Hash_-_CrowdStrike.yml
  Packs/CrowdStrikeHost/ReleaseNotes/1_1_7.md
  Packs/CrowdStrikeHost/Scripts/script-CrowdStrikeUrlParse.yml
  Packs/CrowdStrikeHost/pack_metadata.json
  Packs/Jask/pack_metadata.json
  Packs/PaloAltoNetworks_Threat_Vault/Playbooks/Threat_Vault_-_Signature_Search.yml
  Packs/PaloAltoNetworks_Threat_Vault/ReleaseNotes/1_0_15.md
  Packs/PaloAltoNetworks_Threat_Vault/pack_metadata.json
  Packs/SNDBOX/Playbooks/playbook-Detonate_File_-_SNDBOX.yml
  Packs/SNDBOX/ReleaseNotes/1_0_7.md
  Packs/SNDBOX/pack_metadata.json
Labels: docs-approved

#19529 Deprecate PrismaCloudComputeReporting/PaloAltoNetworks_PAN_OS_EDL_Management/FeedUnit42/DeprecatedContent/FeedMitreAttack
  Packs/DeprecatedContent/pack_metadata.json
  Packs/FeedMitreAttack/ReleaseNotes/1_2_1.md
  Packs/FeedMitreAttack/Scripts/MITREIndicatorsByOpenIncidents/MITREIndicatorsByOpenIncidents.yml
  Packs/FeedMitreAttack/Scripts/MItreIDLayoutDynamicSection/MitreIDLayoutDynamicSection.yml
  Packs/FeedMitreAttack/Scripts/MItreNameLayoutDynamicSection/MitreNameLayoutDynamicSection.yml
  Packs/FeedMitreAttack/pack_metadata.json
  Packs/FeedUnit42/pack_metadata.json
  Packs/PaloAltoNetworks_PAN_OS_EDL_Management/Playbooks/playbook-Block_IOCs_from_CSV_-_External_Dynamic_List.yml
  Packs/PaloAltoNetworks_PAN_OS_EDL_Management/Playbooks/playbook-PAN-OS_-_Block_Domain_-_External_Dynamic_List.yml
  Packs/PaloAltoNetworks_PAN_OS_EDL_Management/Playbooks/playbook-PAN-OS_-_Block_IP_and_URL_-_External_Dynamic_List_v2.yml
  Packs/PaloAltoNetworks_PAN_OS_EDL_Management/Playbooks/playbook-PAN-OS_EDL_Setup_v3.yml
  Packs/PaloAltoNetworks_PAN_OS_EDL_Management/ReleaseNotes/1_1_4.md
  Packs/PaloAltoNetworks_PAN_OS_EDL_Management/pack_metadata.json
  Packs/PrismaCloudComputeReporting/Playbooks/Prisma_Cloud_Compute_Vulnerability_and_Compliance_Reporting.yml
  Packs/PrismaCloudComputeReporting/ReleaseNotes/1_0_2.md
  Packs/PrismaCloudComputeReporting/Scripts/PrismaCloudComputeCreateCVEReport/PrismaCloudComputeCreateCVEReport.yml
  Packs/PrismaCloudComputeReporting/Scripts/PrismaCloudComputeCreateComplianceSummary/PrismaCloudComputeCreateComplianceSummary.yml
  Packs/PrismaCloudComputeReporting/Scripts/PrismaCloudComputeCreateImpactTableForCVE/PrismaCloudComputeCreateImpactTableForCVE.yml
  Packs/PrismaCloudComputeReporting/pack_metadata.json
Labels: docs-approved

#19590 Added cgroups v2 support to DockerHardeningScript
  Packs/CommonScripts/ReleaseNotes/1_7_4.md
  Packs/CommonScripts/Scripts/DockerHardeningCheck/DockerHardeningCheck.py
  Packs/CommonScripts/Scripts/DockerHardeningCheck/DockerHardeningCheck.yml
  Packs/CommonScripts/pack_metadata.json
Labels: Contribution, docs-approved, Contribution Form Filled, Community

#19606 is file up to date change to poetry
  .circleci/config.yml
  .gitlab/ci/global.yml
Labels: docs-approved

#19558 Jira demo fixes
  Packs/Jira/Integrations/JiraEventCollector/JiraEventCollector.py
  Packs/Jira/Integrations/JiraEventCollector/JiraEventCollector.yml
  Packs/Jira/Integrations/JiraEventCollector/JiraEventCollector_description.md
  Packs/Jira/Integrations/JiraEventCollector/JiraEventCollector_test.py
  Packs/Jira/Integrations/JiraEventCollector/README.md
  Packs/Jira/ReleaseNotes/2_0_3.md
  Packs/Jira/pack_metadata.json
Labels: docs-approved

#19620 [Graph Mail] Fix Fetch When Moving Mails
  Packs/MicrosoftGraphMail/Integrations/MicrosoftGraphMail/MicrosoftGraphMail.py
  Packs/MicrosoftGraphMail/ReleaseNotes/1_1_19.md
  Packs/MicrosoftGraphMail/pack_metadata.json
Labels: docs-approved

#19287 Filter changelog based on MP
  Tests/Marketplace/Tests/marketplace_services_test.py
  Tests/Marketplace/marketplace_constants.py
  Tests/Marketplace/marketplace_services.py
  Tests/Marketplace/upload_packs.py
  Utils/release_notes_generator.py
Labels: docs-approved

#19626 Update README.md
  Packs/Okta/Integrations/Okta_IAM/README.md
Labels: docs-approved

#19389 Csp fix xsiam
  Packs/Base/.secrets-ignore
  Packs/Base/ReleaseNotes/1_31_2.md
  Packs/Base/Scripts/CommonServerPython/CommonServerPython.py
  Packs/Base/Scripts/CommonServerPython/CommonServerPython_test.py
  Packs/Base/pack_metadata.json
Labels: docs-approved, ForceMerge

#19474 Add userPrincipalname for Azure Sentinel Update Command
  Packs/AzureSentinel/Integrations/AzureSentinel/AzureSentinel.py
  Packs/AzureSentinel/Integrations/AzureSentinel/AzureSentinel.yml
  Packs/AzureSentinel/Integrations/AzureSentinel/README.md
  Packs/AzureSentinel/ReleaseNotes/1_3_13.md
  Packs/AzureSentinel/pack_metadata.json
Labels: docs-approved

#19621 Cortex XDR - Classifier's id bug fix
  Packs/CortexXDR/Classifiers/classifier-PaloAltoNetworks_Cortex_XDR_Incident_Handler.json
  Packs/CortexXDR/ReleaseNotes/4_6_4.json
  Packs/CortexXDR/ReleaseNotes/4_6_4.md
  Packs/CortexXDR/pack_metadata.json
Labels: docs-approved

#19367 Microsoft Defender for Cloud Apps Event Collector
  Packs/MicrosoftCloudAppSecurity/Integrations/MicrosoftDefenderEventCollector/MicrosoftDefenderEventCollector.py
  Packs/MicrosoftCloudAppSecurity/Integrations/MicrosoftDefenderEventCollector/MicrosoftDefenderEventCollector.yml
  Packs/MicrosoftCloudAppSecurity/Integrations/MicrosoftDefenderEventCollector/MicrosoftDefenderEventCollector_image.png
  Packs/MicrosoftCloudAppSecurity/Integrations/MicrosoftDefenderEventCollector/README.md
  Packs/MicrosoftCloudAppSecurity/ModelingRules/MicrosoftDefenderModelingRules/MicrosoftDefenderModelingRules.xif
  Packs/MicrosoftCloudAppSecurity/ModelingRules/MicrosoftDefenderModelingRules/MicrosoftDefenderModelingRules.yml
  Packs/MicrosoftCloudAppSecurity/ReleaseNotes/2_0_0.md
  Packs/MicrosoftCloudAppSecurity/TestPlaybooks/playbook-Microsoft_Defender_for_Cloud_Apps_Event_Collector-test.yml
  Packs/MicrosoftCloudAppSecurity/pack_metadata.json
  Tests/conf.json
Labels: docs-approved

#19625 Xsiam triggers pr
  Packs/Core/.pack-ignore
  Packs/Core/ReleaseNotes/1_2_4.md
  Packs/Core/Triggers/Trigger_-_Impossible_Traveler.json
  Packs/Core/Triggers/Trigger_-_NGFW_Scan.json
  Packs/Core/Triggers/Trigger_-_T1036_-_Masquerading.json
  Packs/Core/Triggers/Trigger_-_T1059_-_Command_and_Scripting_Interpreter.json
  Packs/Core/Triggers/Trigger_-_WildFire_and_Wildfire_Post_detection.json
  Packs/Core/pack_metadata.json
Labels: docs-approved

#19537 dev task - remove excessive traceback error printing - Packs H I J K L
  Packs/HPEArubaClearPass/Integrations/HPEArubaClearPass/HPEArubaClearPass.py
  Packs/HPEArubaClearPass/Integrations/HPEArubaClearPass/HPEArubaClearPass.yml
  Packs/HPEArubaClearPass/ReleaseNotes/1_0_11.md
  Packs/HPEArubaClearPass/pack_metadata.json
  Packs/HelloIAMWorld/Integrations/HelloIAMWorld/HelloIAMWorld.py
  Packs/HelloIAMWorld/Integrations/HelloIAMWorld/HelloIAMWorld.yml
  Packs/HelloIAMWorld/ReleaseNotes/1_1_5.md
  Packs/HelloIAMWorld/pack_metadata.json
  Packs/HelloWorld/Integrations/HelloWorld/HelloWorld.py
  Packs/HelloWorld/Integrations/HelloWorld/HelloWorld.yml
  Packs/HelloWorld/ReleaseNotes/1_2_12.md
  Packs/HelloWorld/Scripts/HelloWorldScript/HelloWorldScript.py
  Packs/HelloWorld/Scripts/HelloWorldScript/HelloWorldScript.yml
  Packs/HelloWorld/pack_metadata.json
  Packs/Hey/ReleaseNotes/1_0_2.md
  Packs/Hey/Scripts/Hey/Hey.py
  Packs/Hey/pack_metadata.json
  Packs/HostIo/Integrations/HostIo/HostIo.py
  Packs/HostIo/Integrations/HostIo/HostIo.yml
  Packs/HostIo/ReleaseNotes/1_0_12.md
  Packs/HostIo/pack_metadata.json
Labels: docs-approved, ForceMerge

#19570 dev-task - Removed excessive error traceback printing - Packs M N
  Packs/Malware/ReleaseNotes/1_4_1.md
  Packs/Malware/Scripts/CreateHashIndicatorWrapper/CreateHashIndicatorWrapper.py
  Packs/Malware/Scripts/CreateHashIndicatorWrapper/CreateHashIndicatorWrapper.yml
  Packs/Malware/Scripts/IsolationAssetWrapper/IsolationAssetWrapper.py
  Packs/Malware/Scripts/IsolationAssetWrapper/IsolationAssetWrapper.yml
  Packs/Malware/Scripts/RemoveFileWrapper/RemoveFileWrapper.py
  Packs/Malware/Scripts/RemoveFileWrapper/RemoveFileWrapper.yml
  Packs/Malware/pack_metadata.json
  Packs/MalwationAIMA/Integrations/MalwationAIMA/MalwationAIMA.py
  Packs/MalwationAIMA/Integrations/MalwationAIMA/MalwationAIMA.yml
  Packs/MalwationAIMA/ReleaseNotes/1_0_1.md
  Packs/MalwationAIMA/pack_metadata.json
  Packs/Microsoft365Defender/Integrations/Microsoft365Defender/Microsoft365Defender.py
  Packs/Microsoft365Defender/Integrations/Microsoft365Defender/Microsoft365Defender.yml
  Packs/Microsoft365Defender/Integrations/Microsoft365DefenderEventCollector/Microsoft365DefenderEventCollector.py
  Packs/Microsoft365Defender/ReleaseNotes/4_0_1.md
  Packs/Microsoft365Defender/pack_metadata.json
  Packs/MicrosoftAdvancedThreatAnalytics/Integrations/MicrosoftAdvancedThreatAnalytics/MicrosoftAdvancedThreatAnalytics.py
  Packs/MicrosoftAdvancedThreatAnalytics/ReleaseNotes/1_0_3.md
  Packs/MicrosoftAdvancedThreatAnalytics/pack_metadata.json
  Packs/MicrosoftDefenderAdvancedThreatProtection/ReleaseNotes/1_11_3.md
  Packs/MicrosoftDefenderAdvancedThreatProtection/Scripts/TransformIndicatorToMSDefenderIOC/TransformIndicatorToMSDefenderIOC.py
  Packs/MicrosoftDefenderAdvancedThreatProtection/Scripts/TransformIndicatorToMSDefenderIOC/TransformIndicatorToMSDefenderIOC.yml
  Packs/MicrosoftDefenderAdvancedThreatProtection/pack_metadata.json
  Packs/MicrosoftGraphAPI/Integrations/MicrosoftGraphAPI/MicrosoftGraphAPI.py
  Packs/MicrosoftGraphAPI/ReleaseNotes/1_0_16.md
  Packs/MicrosoftGraphAPI/pack_metadata.json
  Packs/MicrosoftGraphApplications/Integrations/MicrosoftGraphApplications/MicrosoftGraphApplications.py
  Packs/MicrosoftGraphApplications/ReleaseNotes/1_0_13.md
  Packs/MicrosoftGraphApplications/pack_metadata.json
  Packs/MicrosoftGraphIdentityandAccess/Integrations/MicrosoftGraphIdentityandAccess/MicrosoftGraphIdentityandAccess.py
  Packs/MicrosoftGraphIdentityandAccess/ReleaseNotes/1_0_13.md
  Packs/MicrosoftGraphIdentityandAccess/pack_metadata.json
  Packs/NetscoutArborSightline/Integrations/NetscoutArborSightline/NetscoutArborSightline.py
  Packs/NetscoutArborSightline/Integrations/NetscoutArborSightline/NetscoutArborSightline.yml
  Packs/NetscoutArborSightline/ReleaseNotes/1_0_12.md
  Packs/NetscoutArborSightline/pack_metadata.json
  Packs/Netskope/Integrations/NetskopeAPIv1/NetskopeAPIv1.py
  Packs/Netskope/Integrations/NetskopeAPIv1/NetskopeAPIv1.yml
  Packs/Netskope/ReleaseNotes/2_0_1.md
  Packs/Netskope/pack_metadata.json
  Packs/NutanixHypervisor/Integrations/NutanixHypervisor/NutanixHypervisor.py
  Packs/NutanixHypervisor/Integrations/NutanixHypervisor/NutanixHypervisor.yml
  Packs/NutanixHypervisor/ReleaseNotes/1_0_12.md
  Packs/NutanixHypervisor/pack_metadata.json
Labels: docs-approved, ForceMerge

#19498 Bug fixes
  Packs/HarfangLabEDR/Integrations/Hurukai/Hurukai.py
  Packs/HarfangLabEDR/Integrations/Hurukai/Hurukai.yml
  Packs/HarfangLabEDR/Playbooks/playbook-Hurukai_-_Get_All_Artifacts.yml
  Packs/HarfangLabEDR/Playbooks/playbook-Hurukai_-_Get_Artifact_Evtx.yml
  Packs/HarfangLabEDR/Playbooks/playbook-Hurukai_-_Get_Artifact_Filesystem.yml
  Packs/HarfangLabEDR/Playbooks/playbook-Hurukai_-_Get_Artifact_Hives.yml
  Packs/HarfangLabEDR/Playbooks/playbook-Hurukai_-_Get_Artifact_Logs.yml
  Packs/HarfangLabEDR/Playbooks/playbook-Hurukai_-_Get_Artifact_MFT.yml
  Packs/HarfangLabEDR/Playbooks/playbook-Hurukai_-_Get_Artifact_RAM_Dump.yml
  Packs/HarfangLabEDR/Playbooks/playbook-Hurukai_-_Get_Driver_List.yml
  Packs/HarfangLabEDR/Playbooks/playbook-Hurukai_-_Get_Network_Connection_List.yml
  Packs/HarfangLabEDR/Playbooks/playbook-Hurukai_-_Get_Network_Share_List.yml
  Packs/HarfangLabEDR/Playbooks/playbook-Hurukai_-_Get_Persistence_List.yml
  Packs/HarfangLabEDR/Playbooks/playbook-Hurukai_-_Get_Pipe_List.yml
  Packs/HarfangLabEDR/Playbooks/playbook-Hurukai_-_Get_Prefetch_List.yml
  Packs/HarfangLabEDR/Playbooks/playbook-Hurukai_-_Get_Process_List.yml
  Packs/HarfangLabEDR/Playbooks/playbook-Hurukai_-_Get_Runkey_List.yml
  Packs/HarfangLabEDR/Playbooks/playbook-Hurukai_-_Get_Scheduled_Task_List.yml
  Packs/HarfangLabEDR/Playbooks/playbook-Hurukai_-_Get_Service_List.yml
  Packs/HarfangLabEDR/Playbooks/playbook-Hurukai_-_Get_Session_List.yml
  Packs/HarfangLabEDR/Playbooks/playbook-Hurukai_-_Get_Startup_List.yml
  Packs/HarfangLabEDR/Playbooks/playbook-Hurukai_-_Get_WMI_List.yml
  Packs/HarfangLabEDR/ReleaseNotes/1_0_2.md
  Packs/HarfangLabEDR/pack_metadata.json
Labels: Contribution, docs-approved, Partner, Contribution Form Filled, pending-contributor

#19633 added BA101 to pack ignore to the relevant classifiers
  Packs/AgariPhishingDefense/.pack-ignore
  Packs/Armorblox/.pack-ignore
  Packs/AzureActiveDirectory/.pack-ignore
  Packs/BmcHelixRemedyForce/.pack-ignore
  Packs/CimTrak-SystemIntegrityAssurance/.pack-ignore
  Packs/Claroty/.pack-ignore
  Packs/CommonTypes/.pack-ignore
  Packs/CortexXDR/.pack-ignore
  Packs/CrowdStrikeFalcon/.pack-ignore
  Packs/CrowdStrikeFalconStreamingV2/.pack-ignore
  Packs/CybleEvents/.pack-ignore
  Packs/Cymulate/.pack-ignore
  Packs/CyrenInboxSecurity/.pack-ignore
  Packs/Darktrace/.pack-ignore
  Packs/DevSecOps/.pack-ignore
  Packs/EWS/.pack-ignore
  Packs/EmailCommunication/.pack-ignore
  Packs/ExpanseV2/.pack-ignore
  Packs/F5Silverline/.pack-ignore
  Packs/FeedAWS/.pack-ignore
  Packs/FireEyeEX/.pack-ignore
  Packs/FireEyeNX/.pack-ignore
  Packs/Gmail/.pack-ignore
  Packs/GmailSingleUser/.pack-ignore
  Packs/GoogleChronicleBackstory/.pack-ignore
  Packs/GoogleCloudSCC/.pack-ignore
  Packs/GoogleDrive/.pack-ignore
  Packs/Grafana/.pack-ignore
  Packs/GroupIB_ThreatIntelligenceAttribution/.pack-ignore
  Packs/HelloWorld/.pack-ignore
  Packs/IllusiveNetworks/.pack-ignore
  Packs/Indeni/.pack-ignore
  Packs/Infinipoint/.pack-ignore
  Packs/IronDefense/.pack-ignore
  Packs/LogsignSiem/.pack-ignore
  Packs/Logzio/.pack-ignore
  Packs/MicroFocusSMAX/.pack-ignore
  Packs/MicrosoftAdvancedThreatAnalytics/.pack-ignore
  Packs/MicrosoftCloudAppSecurity/.pack-ignore
  Packs/MicrosoftGraphListener/.pack-ignore
  Packs/OTSecurity/.pack-ignore
  Packs/OnboardingIntegration/.pack-ignore
  Packs/OpsGenie/.pack-ignore
  Packs/Orca/.pack-ignore
  Packs/PrismaCloud/.pack-ignore
  Packs/PrismaCloudCompute/.pack-ignore
  Packs/QRadar/.pack-ignore
  Packs/QualysFIM/.pack-ignore
  Packs/Rapid7_InsightIDR/.pack-ignore
  Packs/Respond/.pack-ignore
  Packs/ServiceNow/.pack-ignore
  Packs/Smokescreen_IllusionBLACK/.pack-ignore
  Packs/SolarWinds/.pack-ignore
  Packs/SplunkPy/.pack-ignore
  Packs/TrendMicroCAS/.pack-ignore
  Packs/Tripwire/.pack-ignore
  Packs/Zimperium/.pack-ignore
  Packs/mnemonicMDR/.pack-ignore
Labels: docs-approved

#19639 added BA101 to pack ignore
  Packs/Cymulate/.pack-ignore
Labels: docs-approved

#19646 trigger contrib fix
  .github/workflows/run-secrets-detection.yml
  .github/workflows/trigger-contribution-build.yml
Labels: docs-approved

#18621 XSIAM ransomware playbooks
  Packs/Core/.secrets-ignore
  Packs/Core/Playbooks/playbook-Ransomware_Advanced_Analysis.yml
  Packs/Core/Playbooks/playbook-Ransomware_Advanced_Analysis_README.md
  Packs/Core/Playbooks/playbook-Ransomware_Enrich_and_Contain.yml
  Packs/Core/Playbooks/playbook-Ransomware_Enrich_and_Contain_README.md
  Packs/Core/Playbooks/playbook-Ransomware_Response.yml
  Packs/Core/Playbooks/playbook-Ransomware_Response_README.md
  Packs/Core/ReleaseNotes/1_2_5.md
  Packs/Core/doc_files/Ransomware_Advanced_Analysis.png
  Packs/Core/doc_files/Ransomware_Enrich_and_Contain.png
  Packs/Core/doc_files/Ransomware_Response.png
  Packs/Core/pack_metadata.json
Labels: docs-approved

#19636 Hide packs - phase 1
  Packs/Cofense-Intelligence/pack_metadata.json
  Packs/Expanse/pack_metadata.json
  Packs/FeedMalwareDomainList/pack_metadata.json
  Packs/Jask/pack_metadata.json
  Packs/Traps/pack_metadata.json
Labels: docs-approved

#19647 remove double contributor credits
  Packs/EmailCommunication/README.md
Labels: docs-approved

#19642 Azure log analytics - the argument was misspelled in the playbook
  Packs/AzureLogAnalytics/Playbooks/AzureLogAnalytics_QuerySavedSearch.yml
  Packs/AzureLogAnalytics/Playbooks/AzureLogAnalytics_QuerySavedSearch_README.md
  Packs/AzureLogAnalytics/ReleaseNotes/1_0_14.md
  Packs/AzureLogAnalytics/doc_files/AzureLogAnalytics_QuerySavedSearch.png
  Packs/AzureLogAnalytics/pack_metadata.json
Labels: docs-approved

#19628 hotfix to coverage version
  .github/CODEOWNERS
  poetry.lock
  pyproject.toml
Labels: docs-approved

#19651 Handle Filtering in Indicator Format Scripts
  Packs/CommonScripts/.secrets-ignore
  Packs/CommonScripts/ReleaseNotes/1_7_6.md
  Packs/CommonScripts/Scripts/ExtractEmailFormatting/ExtractEmailFormatting.py
  Packs/CommonScripts/Scripts/ExtractEmailFormatting/ExtractEmailFormatting.yml
  Packs/CommonScripts/Scripts/ExtractEmailFormatting/ExtractEmailFormatting_test.py
  Packs/CommonScripts/Scripts/VerifyIPv6Indicator/README.md
  Packs/CommonScripts/Scripts/VerifyIPv6Indicator/VerifyIPv6Indicator.py
  Packs/CommonScripts/Scripts/VerifyIPv6Indicator/VerifyIPv6Indicator.yml
  Packs/CommonScripts/Scripts/VerifyIPv6Indicator/VerifyIPv6Indicator_test.py
  Packs/CommonScripts/TestPlaybooks/playbook-ExtractEmail-Test.yml
  Packs/CommonScripts/TestPlaybooks/playbook-IndicatorFormatFiltering_Test.yml
  Packs/CommonScripts/pack_metadata.json
  Packs/Cryptocurrency/ReleaseNotes/1_1_19.md
  Packs/Cryptocurrency/Scripts/CryptoCurrenciesFormat/CryptoCurrenciesFormat.py
  Packs/Cryptocurrency/Scripts/CryptoCurrenciesFormat/CryptoCurrenciesFormat.yml
  Packs/Cryptocurrency/Scripts/CryptoCurrenciesFormat/CryptoCurrenciesFormat_test.py
  Packs/Cryptocurrency/pack_metadata.json
  Tests/conf.json
Labels: docs-approved

#19663 Update Oracle DB Pack README
  Packs/Oracle/README.md
Labels: docs-approved

#19414 Rasterize: support chrome headless cmd option
  Packs/rasterize/.pack-ignore
  Packs/rasterize/Integrations/rasterize/README.md
  Packs/rasterize/Integrations/rasterize/rasterize.py
  Packs/rasterize/Integrations/rasterize/rasterize.yml
  Packs/rasterize/Integrations/rasterize/rasterize_description.md
  Packs/rasterize/Integrations/rasterize/rasterize_test.py
  Packs/rasterize/ReleaseNotes/1_1_0.md
  Packs/rasterize/pack_metadata.json
Labels: docs-approved

#19670 update poetry - new sdk hotfix
  poetry.lock
  pyproject.toml
Labels: docs-approved

#19664 change description to deprecated packs
  Packs/Ansible_Powered_Integrations/pack_metadata.json
  Packs/Blockade.io/pack_metadata.json
  Packs/CrowdStrikeHost/pack_metadata.json
  Packs/DeprecatedContent/pack_metadata.json
  Packs/Expanse/pack_metadata.json
  Packs/ExportIndicators/pack_metadata.json
  Packs/FeedMalwareDomainList/pack_metadata.json
  Packs/FeedMitreAttack/pack_metadata.json
  Packs/FeedUnit42/pack_metadata.json
  Packs/Jask/pack_metadata.json
  Packs/McAfee_ESM-v10/pack_metadata.json
  Packs/MicrosoftPolicyAndCompliance/pack_metadata.json
  Packs/PaloAltoNetworks_PAN_OS_EDL_Management/pack_metadata.json
  Packs/PaloAltoNetworks_Threat_Vault/pack_metadata.json
  Packs/PhishAI/pack_metadata.json
  Packs/PrismaCloudComputeReporting/pack_metadata.json
  Packs/Recorded_Future/pack_metadata.json
  Packs/SNDBOX/pack_metadata.json
  Packs/Skyformation/pack_metadata.json
  Packs/TCPIPUtils/pack_metadata.json
  Packs/WindowsDefenderAdvancedThreatProtection/pack_metadata.json
Labels: docs-approved

#19644 Jira change vendor name
  Packs/Jira/Integrations/JiraEventCollector/JiraEventCollector.py
  Packs/Jira/ModelingRules/JiraEventCollector/JiraEventCollector.xif
  Packs/Jira/ModelingRules/JiraEventCollector/JiraEventCollector.yml
  Packs/Jira/ReleaseNotes/2_0_4.md
  Packs/Jira/pack_metadata.json
Labels: docs-approved, release-notes-only

#19466 Update docker image ml - BERT OOB version
  Packs/Base/ReleaseNotes/1_31_3.md
  Packs/Base/Scripts/DBotBuildPhishingClassifier/DBotBuildPhishingClassifier.yml
  Packs/Base/Scripts/DBotBuildPhishingClassifier/README.md
  Packs/Base/Scripts/DBotPredictPhishingWords/DBotPredictPhishingWords.yml
  Packs/Base/Scripts/DBotPredictPhishingWords/README.md
  Packs/Base/Scripts/DBotPreprocessTextData/DBotPreprocessTextData.yml
  Packs/Base/Scripts/DBotPreprocessTextData/README.md
  Packs/Base/Scripts/DBotTrainTextClassifierV2/DBotTrainTextClassifierV2.yml
  Packs/Base/Scripts/DBotTrainTextClassifierV2/README.md
  Packs/Base/Scripts/GetIncidentsByQuery/GetIncidentsByQuery.yml
  Packs/Base/Scripts/GetIncidentsByQuery/README.md
  Packs/Base/Scripts/GetMLModelEvaluation/GetMLModelEvaluation.yml
  Packs/Base/Scripts/GetMLModelEvaluation/README.md
  Packs/Base/TestPlaybooks/playbook-DBot_Build_Phishing_Classifier_Test_-_Multiple_Algorithms.yml
  Packs/Base/pack_metadata.json
  Packs/ML/ReleaseNotes/1_4_2.md
  Packs/ML/Scripts/DBotPredictOutOfTheBoxV2/DBotPredictOutOfTheBoxV2.py
  Packs/ML/Scripts/DBotPredictOutOfTheBoxV2/DBotPredictOutOfTheBoxV2.yml
  Packs/ML/Scripts/DBotPredictOutOfTheBoxV2/README.md
  Packs/ML/TestPlaybooks/playbook-DBotPredictOutOfTheBoxV2-test.yml
  Packs/ML/pack_metadata.json
  Tests/conf.json
Labels: docs-approved

#19684 little fixes
  Tests/scripts/wait_in_line_for_xsiam_env.sh
Labels: docs-approved

#19668 Remove un-relevant logging SaaS Security
  Packs/PrismaSaasSecurity/Integrations/SaasSecurityEventCollector/SaasSecurityEventCollector.py
  Packs/PrismaSaasSecurity/ReleaseNotes/2_0_3.md
  Packs/PrismaSaasSecurity/pack_metadata.json
Labels: docs-approved

#19685 Deprecate traps playbooks
  Packs/Traps/Playbooks/playbook-Block_File_-_Quarantine_-_Traps.yml
  Packs/Traps/Playbooks/playbook-Isolate_Endpoint_-_Traps.yml
  Packs/Traps/Playbooks/playbook-Traps_Blacklist_File.yml
  Packs/Traps/Playbooks/playbook-Traps_Retrieve_And_Download_Files.yml
  Packs/Traps/Playbooks/playbook-Traps_Scan_Endpoint.yml
  Packs/Traps/ReleaseNotes/1_0_11.md
  Packs/Traps/pack_metadata.json
Labels: docs-approved

#19275 Create pack readme for Azure Log Analytics
  Packs/AzureLogAnalytics/README.md
Labels: docs-approved

#19184 Qradar mirroring removed from long running instance
  Packs/QRadar/Classifiers/classifier-QRadar_-_Generic_Incoming_Mapper.json
  Packs/QRadar/Integrations/QRadar_v3/QRadar_v3.py
  Packs/QRadar/Integrations/QRadar_v3/QRadar_v3.yml
  Packs/QRadar/Integrations/QRadar_v3/QRadar_v3_test.py
  Packs/QRadar/Integrations/QRadar_v3/test_data/command_test_data.json
  Packs/QRadar/Integrations/QRadar_v3/test_data/integration_context_tests.json
  Packs/QRadar/ReleaseNotes/2_2_0.md
  Packs/QRadar/Scripts/QRadarPrintEvents/QRadarPrintEvents.py
  Packs/QRadar/Scripts/QRadarPrintEvents/QRadarPrintEvents.yml
  Packs/QRadar/TestPlaybooks/QRadar_v3-test.yml
  Packs/QRadar/pack_metadata.json
Labels: docs-approved

#19637 update Gmail admin user details
  Packs/Gmail/Integrations/Gmail/Gmail.yml
  Packs/Gmail/Integrations/Gmail/Gmail_description.md
  Packs/Gmail/ReleaseNotes/1_1_18.md
  Packs/Gmail/pack_metadata.json
Labels: docs-approved

#19483 Drop SetIRProceduresMarkdown -> Demisto REST API dependency
  Packs/DemistoRESTAPI/ReleaseNotes/1_3_0.md
  Packs/DemistoRESTAPI/Scripts/GetTasksWithSections/GetTasksWithSections.py
  Packs/DemistoRESTAPI/Scripts/GetTasksWithSections/GetTasksWithSections.yml
  Packs/DemistoRESTAPI/Scripts/GetTasksWithSections/README.md
  Packs/DemistoRESTAPI/Scripts/SetIRProceduresMarkdown/README.md
  Packs/DemistoRESTAPI/Scripts/SetIRProceduresMarkdown/SetIRProceduresMarkdown.yml
  Packs/DemistoRESTAPI/pack_metadata.json
Labels: docs-approved, release-notes-only

#19535 Prisma cloud dashboard
  Packs/PrismaCloud/Dashboards/dashboard-Prisma_Cloud_Incidents.json
  Packs/PrismaCloud/ReleaseNotes/2_0_12.md
  Packs/PrismaCloud/pack_metadata.json
Labels: Contribution, docs-approved, ready-for-instance-test, pending-demo, post-demo, Contribution Form Filled, Community, pending-contributor

#19698 Update advisories.json
  Packs/PaloAltoNetworks_SecurityAdvisories/Integrations/PaloAltoNetworksSecurityAdvisories/test_data/advisories.json
Labels: docs-approved

#18735 Topdesk mirror integration
  Packs/TOPdesk/CONTRIBUTORS.md
  Packs/TOPdesk/Classifiers/classifier-TOPdesk-Incident.json
  Packs/TOPdesk/Classifiers/classifier-mapper-incoming-TOPdesk.json
  Packs/TOPdesk/Classifiers/classifier-mapper-outgoing-TOPdesk.json
  Packs/TOPdesk/Integrations/TOPdesk/README.md
  Packs/TOPdesk/Integrations/TOPdesk/TOPdesk.py
  Packs/TOPdesk/Integrations/TOPdesk/TOPdesk.yml
  Packs/TOPdesk/Integrations/TOPdesk/TOPdesk_test.py
  Packs/TOPdesk/Integrations/TOPdesk/test_data/topdesk_actions.json
  Packs/TOPdesk/Integrations/TOPdesk/test_data/topdesk_incident.json
  Packs/TOPdesk/Layouts/layoutscontainer-TOPdesk_incident.json
  Packs/TOPdesk/ReleaseNotes/2_0_0.md
  Packs/TOPdesk/pack_metadata.json
Labels: Contribution, docs-approved, post-demo, Contribution Form Filled, Community, pending-contributor

#19713 xsoar tools hotfix
  Packs/Base/ReleaseNotes/1_31_5.md
  Packs/Base/Scripts/ValidateContent/ValidateContent.yml
  Packs/Base/pack_metadata.json
Labels: docs-approved

#19716 fixed url parsing
  Tests/configure_and_test_integration_instances.py
Labels: docs-approved

#19669 Added support for passing the headers parameter as string to HttpV2.
  Packs/CommonScripts/ReleaseNotes/1_7_7.md
  Packs/CommonScripts/Scripts/HttpV2/HttpV2.py
  Packs/CommonScripts/Scripts/HttpV2/HttpV2.yml
  Packs/CommonScripts/Scripts/HttpV2/HttpV2_test.py
  Packs/CommonScripts/Scripts/HttpV2/README.md
  Packs/CommonScripts/pack_metadata.json
Labels: docs-approved

#19729 email comm - add video
  Packs/EmailCommunication/pack_metadata.json
Labels: docs-approved

#19715 Fix Jira first fetch
  Packs/Jira/Integrations/JiraV2/JiraV2.py
  Packs/Jira/ReleaseNotes/2_0_5.md
  Packs/Jira/pack_metadata.json
Labels: docs-approved

#19740 fix markdown of prisma-cloud-compute README
  Packs/PrismaCloudCompute/Integrations/PaloAltoNetworks_PrismaCloudCompute/README.md
Labels: docs-approved

#19696 Fix upload not relevant for mp bug
  Tests/Marketplace/Tests/marketplace_services_test.py
  Tests/Marketplace/marketplace_constants.py
  Tests/Marketplace/marketplace_services.py
  Tests/Marketplace/upload_packs.py
Labels: docs-approved

#19707 Changed file names to support new validation
  Packs/AnsibleLinux/Integrations/AnsibleACME/AnsibleACME_image.png
  Packs/BitDam/Integrations/BitDam/BitDam_description.md
  Packs/BmcHelixRemedyForce/.pack-ignore
  Packs/BmcHelixRemedyForce/Integrations/BmcHelixRemedyForce/BmcHelixRemedyForce.py
  Packs/BmcHelixRemedyForce/Integrations/BmcHelixRemedyForce/BmcHelixRemedyForce.yml
  Packs/BmcHelixRemedyForce/Integrations/BmcHelixRemedyForce/BmcHelixRemedyForce_description.md
  Packs/BmcHelixRemedyForce/Integrations/BmcHelixRemedyForce/BmcHelixRemedyForce_image.png
  Packs/BmcHelixRemedyForce/Integrations/BmcHelixRemedyForce/BmcHelixRemedyForce_test.py
  Packs/BmcHelixRemedyForce/ReleaseNotes/1_0_17.md
  Packs/BmcHelixRemedyForce/pack_metadata.json
  Packs/CrowdStrikeFalconSandbox/Integrations/CrowdStrikeFalconSandboxV2/CrowdStrikeFalconSandboxV2.py
  Packs/CrowdStrikeFalconSandbox/Integrations/CrowdStrikeFalconSandboxV2/CrowdStrikeFalconSandboxV2.yml
  Packs/CrowdStrikeFalconSandbox/Integrations/CrowdStrikeFalconSandboxV2/CrowdStrikeFalconSandboxV2_description.md
  Packs/CrowdStrikeFalconSandbox/Integrations/CrowdStrikeFalconSandboxV2/CrowdStrikeFalconSandboxV2_image.png
  Packs/CrowdStrikeFalconSandbox/Integrations/CrowdStrikeFalconSandboxV2/CrowdStrikeFalconSandboxV2_test.py
  Packs/CrowdStrikeFalconSandbox/Integrations/CrowdStrikeFalconSandboxV2/Pipfile
  Packs/CrowdStrikeFalconSandbox/Integrations/CrowdStrikeFalconSandboxV2/Pipfile.lock
  Packs/CrowdStrikeFalconSandbox/Integrations/CrowdStrikeFalconSandboxV2/README.md
  Packs/CrowdStrikeFalconSandbox/Integrations/CrowdStrikeFalconSandboxV2/command_examples.txt
  Packs/CrowdStrikeFalconSandbox/Integrations/CrowdStrikeFalconSandboxV2/test_data/scan_response.json
  Packs/CrowdStrikeFalconSandbox/Integrations/CrowdStrikeFalconSandboxV2/test_data/submission_response.json
  Packs/CrowdStrikeFalconSandbox/ReleaseNotes/2_0_2.md
  Packs/CrowdStrikeFalconSandbox/pack_metadata.json
  Packs/Cymulate/Integrations/Cymulate_v2/Cymulate_v2_test.py
  Packs/DBotTruthBombs/Integrations/DBotTruthBombs/DBotTruthBombs_image.png
  Packs/FeedAzureADConnectHealth/Integrations/AzureADConnectHealthFeed/AzureADConnectHealthFeed_test.py
  Packs/FeedCrowdstrikeFalconIntel/Integrations/FeedCrowdstrikeFalconIntel/FeedCrowdstrikeFalconIntel_image.png
  Packs/FeedOpenCTI/Integrations/FeedOpenCTI/FeedOpenCTI_image.png
  Packs/IdentityRecordedFuture/Integrations/IdentityRecordedFuture/IdentityRecordedFuture_image.png
  Packs/McAfee-TIE/Integrations/McAfee-TIE/McAfee-TIE_test.py
  Packs/NetscoutAED/Integrations/NetscoutAED/NetscoutAED_image.png
  Packs/SymantecEndpointProtection/Integrations/SymantecEndpointProtection_V2/SymantecEndpointProtection_V2_test.py
  Packs/mnemonicMDR/Integrations/ArgusManagedDefence/ArgusManagedDefence_test.py
Labels: docs-approved, ForceMerge

#19708 Changed file names to support new validation
  Packs/AWS-IAM/Integrations/AWS-IAM/AWS-IAM_test.py
  Packs/ConcentricAI/Integrations/ConcentricAI/ConcentricAI_test.py
  Packs/FeedBlocklist_de/Integrations/FeedBlocklist_de/FeedBlocklist_de_image.png
  Packs/Mimecast/Integrations/MimecastV2/MimecastV2_test.py
  Packs/PagerDuty/Integrations/PagerDuty/PagerDuty_test.py
  Packs/RemoteAccess/Integrations/RemoteAccessv2/RemoteAccessv2_image.png
  Packs/ThreatMiner/Integrations/ThreatMiner/ThreatMiner_test.py
  Packs/URLHaus/Integrations/URLHaus/URLHaus_image.png
  Packs/UrlScan/Integrations/UrlScan/UrlScan_test.py
Labels: docs-approved, ForceMerge

#19635 Wildfire fix file report
  Packs/Palo_Alto_Networks_WildFire/Integrations/Palo_Alto_Networks_WildFire_v2/Palo_Alto_Networks_WildFire_v2.py
  Packs/Palo_Alto_Networks_WildFire/Integrations/Palo_Alto_Networks_WildFire_v2/Palo_Alto_Networks_WildFire_v2.yml
  Packs/Palo_Alto_Networks_WildFire/Integrations/Palo_Alto_Networks_WildFire_v2/Palo_Alto_Networks_WildFire_v2_test.py
  Packs/Palo_Alto_Networks_WildFire/ReleaseNotes/2_1_5.md
  Packs/Palo_Alto_Networks_WildFire/pack_metadata.json
Labels: docs-approved

#19724 Ansible linux fix
  Packs/AnsibleLinux/Integrations/AnsibleLinux/AnsibleLinux.yml
  Packs/AnsibleLinux/ReleaseNotes/1_0_4.md
  Packs/AnsibleLinux/pack_metadata.json
Labels: docs-approved

#19544 Bugfix for SQS max_fetch type
  Packs/AWS-SQS/Integrations/AWS-SQS/AWS-SQS.py
  Packs/AWS-SQS/ReleaseNotes/1_2_9.md
  Packs/AWS-SQS/pack_metadata.json
Labels: Contribution, docs-approved, ready-for-instance-test, Contribution Form Filled, Community

#19660 dev-task - Remove excessive error traceback printing - Packs W X Y Z
  Packs/X509Certificate/ReleaseNotes/1_0_12.md
  Packs/X509Certificate/Scripts/CertificateExtract/CertificateExtract.py
  Packs/X509Certificate/Scripts/CertificateExtract/CertificateExtract.yml
  Packs/X509Certificate/Scripts/CertificateReputation/CertificateReputation.py
  Packs/X509Certificate/Scripts/CertificateReputation/CertificateReputation.yml
  Packs/X509Certificate/pack_metadata.json
  Packs/XSOARmirroring/Integrations/XSOARmirroring/XSOARmirroring.py
  Packs/XSOARmirroring/Integrations/XSOARmirroring/XSOARmirroring.yml
  Packs/XSOARmirroring/ReleaseNotes/2_0_8.md
  Packs/XSOARmirroring/pack_metadata.json
  Packs/Zoom/Integrations/Zoom_IAM/Zoom_IAM.py
  Packs/Zoom/Integrations/Zoom_IAM/Zoom_IAM.yml
  Packs/Zoom/ReleaseNotes/1_1_2.md
  Packs/Zoom/pack_metadata.json
Labels: docs-approved, ForceMerge

#19738 Create Empty Indicator When FormatURL Fails
  Packs/CommonScripts/ReleaseNotes/1_7_8.md
  Packs/CommonScripts/Scripts/FormatURL/FormatURL.py
  Packs/CommonScripts/Scripts/FormatURL/FormatURL.yml
  Packs/CommonScripts/Scripts/FormatURL/FormatURL_test.py
  Packs/CommonScripts/pack_metadata.json
Labels: docs-approved

#19753 Patch hidden packs issue
  Tests/configure_and_test_integration_instances.py
  Utils/trigger_private_build.py
Labels: docs-approved

#19767 Jira fix application name check
  Packs/Jira/Integrations/JiraV2/JiraV2.py
  Packs/Jira/ReleaseNotes/2_0_6.md
  Packs/Jira/pack_metadata.json
Labels: docs-approved

#19757 LogRhythmRestV2 - Search query Playbook - Added statuses to the polling
  Packs/LogRhythmRest/Playbooks/playbook-LogRhythmRestV2-_Search_query.yml
  Packs/LogRhythmRest/Playbooks/playbook-LogRhythmRestV2-_Search_query_README.md
  Packs/LogRhythmRest/ReleaseNotes/2_0_11.md
  Packs/LogRhythmRest/doc_files/LogRhythmRestV2-_Search_query.png
  Packs/LogRhythmRest/pack_metadata.json
Labels: docs-approved
