Repository demisto/content, pull requests merged in 2022-10, with the labels that each got.

#21407 XSIAM playbook | added prevalence playbook
  Packs/CommonPlaybooks/Playbooks/playbook-Enrichment_for_Verdict.yml
  Packs/CommonPlaybooks/Playbooks/playbook-Enrichment_for_Verdict_README.md
  Packs/CommonPlaybooks/Playbooks/playbook-Get_prevalence_for_IOCs.yml
  Packs/CommonPlaybooks/Playbooks/playbook-Get_prevalence_for_IOCs_README.md
  Packs/CommonPlaybooks/ReleaseNotes/2_3_5.md
  Packs/CommonPlaybooks/doc_files/Enrichment_for_Verdict.png
  Packs/CommonPlaybooks/doc_files/Get_prevalence_for_IOCs.png
  Packs/CommonPlaybooks/pack_metadata.json
Labels: docs-approved

#21303 Fixed a bug when there is spaces in file name
  Packs/CrowdStrikeFalcon/Integrations/CrowdStrikeFalcon/CrowdStrikeFalcon.py
  Packs/CrowdStrikeFalcon/Integrations/CrowdStrikeFalcon/CrowdStrikeFalcon_test.py
  Packs/CrowdStrikeFalcon/ReleaseNotes/1_9_4.md
  Packs/CrowdStrikeFalcon/pack_metadata.json
Labels: docs-approved

#21557 [Elasticsearch] Fix first run time usage
  Packs/Elasticsearch/Integrations/Elasticsearch_v2/Elasticsearch_v2.py
  Packs/Elasticsearch/Integrations/Elasticsearch_v2/Elasticsearch_v2.yml
  Packs/Elasticsearch/ReleaseNotes/1_3_2.md
  Packs/Elasticsearch/pack_metadata.json
Labels: docs-approved

#21211 Redlock lookback fix
  Packs/PrismaCloud/Integrations/RedLock/RedLock.py
  Packs/PrismaCloud/Integrations/RedLock/RedLock.yml
  Packs/PrismaCloud/Integrations/RedLock/RedLock_test.py
  Packs/PrismaCloud/ReleaseNotes/2_0_16.md
  Packs/PrismaCloud/pack_metadata.json
Labels: docs-approved

#21494 Improved the DT parser to support nested DT expressions
  Packs/ExtFilter/ReleaseNotes/1_1_12.md
  Packs/ExtFilter/Scripts/ExtFilter/ExtFilter.py
  Packs/ExtFilter/Scripts/ExtFilter/ExtFilter.yml
  Packs/ExtFilter/Scripts/ExtFilter/test_data/test-1.json
  Packs/ExtFilter/pack_metadata.json
  Packs/MapPattern/ReleaseNotes/1_0_7.md
  Packs/MapPattern/Scripts/MapPattern/MapPattern.py
  Packs/MapPattern/Scripts/MapPattern/MapPattern.yml
  Packs/MapPattern/Scripts/MapPattern/test_data/test-1.json
  Packs/MapPattern/pack_metadata.json
Labels: Contribution, docs-approved, Contribution Form Filled, Community

#21205 Fix threat hunting playbooks - Change queries to be pointing not on global context paths
  Packs/PANWComprehensiveInvestigation/Playbooks/Palo_Alto_Networks_-_Hunting_And_Threat_Detection.yml
  Packs/PANWComprehensiveInvestigation/ReleaseNotes/1_3_12.md
  Packs/PANWComprehensiveInvestigation/pack_metadata.json
  Packs/QRadar/Playbooks/playbook-QRadarFullSearch.yml
  Packs/QRadar/Playbooks/playbook-QRadar_Indicator_Hunting_V2.yml
  Packs/QRadar/ReleaseNotes/2_3_1.md
  Packs/QRadar/TestPlaybooks/playbook-QRadar_Indicator_Hunting_Test.yml
  Packs/QRadar/pack_metadata.json
  Packs/SplunkPy/Playbooks/playbook-Splunk_Indicator_Hunting.yml
  Packs/SplunkPy/ReleaseNotes/2_4_15.md
  Packs/SplunkPy/pack_metadata.json
  Tests/conf.json
Labels: docs-approved

#21579 Servicenow fix assigned to mirror
  Packs/ServiceNow/Integrations/ServiceNowv2/ServiceNowv2.py
  Packs/ServiceNow/Integrations/ServiceNowv2/ServiceNowv2_test.py
  Packs/ServiceNow/ReleaseNotes/2_3_25.md
  Packs/ServiceNow/pack_metadata.json
Labels: docs-approved, release-notes-only

#21587 ProxyNotShell Response Pack
  Packs/CVE_2022_41040_and_CVE_2022_41082_-_ProxyNotShell/.pack-ignore
  Packs/CVE_2022_41040_and_CVE_2022_41082_-_ProxyNotShell/.secrets-ignore
  Packs/CVE_2022_41040_and_CVE_2022_41082_-_ProxyNotShell/Playbooks/playbook-CVE-2022-41040_&_CVE-2022-41082_-_ProxyNotShell.yml
  Packs/CVE_2022_41040_and_CVE_2022_41082_-_ProxyNotShell/Playbooks/playbook-CVE-2022-41040_&_CVE-2022-41082_-_ProxyNotShell_README.md
  Packs/CVE_2022_41040_and_CVE_2022_41082_-_ProxyNotShell/README.md
  Packs/CVE_2022_41040_and_CVE_2022_41082_-_ProxyNotShell/doc_files/CVE-2022-41040_&_CVE-2022-41082_-_ProxyNotShell.png
  Packs/CVE_2022_41040_and_CVE_2022_41082_-_ProxyNotShell/pack_metadata.json
  Packs/MajorBreachesInvestigationandResponse/ReleaseNotes/1_6_24.md
  Packs/MajorBreachesInvestigationandResponse/pack_metadata.json
Labels: docs-approved

#21577 For release SDK 1.7.6
  poetry.lock
  pyproject.toml
Labels: docs-approved

#21558 Opswat scan file bug fix
  Packs/opswat-metadefender/.pack-ignore
  Packs/opswat-metadefender/.secrets-ignore
  Packs/opswat-metadefender/Integrations/OPSWATMetadefenderV2/OPSWATMetadefenderV2.py
  Packs/opswat-metadefender/Integrations/OPSWATMetadefenderV2/OPSWATMetadefenderV2.yml
  Packs/opswat-metadefender/Integrations/OPSWATMetadefenderV2/OPSWATMetadefenderV2_image.png
  Packs/opswat-metadefender/Integrations/OPSWATMetadefenderV2/README.md
  Packs/opswat-metadefender/Integrations/integration-opswat-metadefender-v2.yml
  Packs/opswat-metadefender/ReleaseNotes/1_0_4.md
  Packs/opswat-metadefender/pack_metadata.json
Labels: docs-approved

#21507 [PAN-OS] add the pan-os-list-templates command
  Packs/PAN-OS/Integrations/Panorama/Panorama.py
  Packs/PAN-OS/Integrations/Panorama/Panorama.yml
  Packs/PAN-OS/Integrations/Panorama/Panorama_test.py
  Packs/PAN-OS/Integrations/Panorama/README.md
  Packs/PAN-OS/Integrations/Panorama/command_examples.txt
  Packs/PAN-OS/Integrations/Panorama/test_data/list_templates_including_uncommitted.json
  Packs/PAN-OS/ReleaseNotes/1_14_22.md
  Packs/PAN-OS/pack_metadata.json
Labels: docs-approved

#21588 [CrowdStrike Falcon] Fix integration README file
  Packs/CrowdStrikeFalcon/Integrations/CrowdStrikeFalcon/README.md
Labels: docs-approved

#20914 adding agent config to mp
  Tests/Marketplace/marketplace_constants.py
  Tests/Marketplace/marketplace_services.py
  Tests/scripts/collect_tests/constants.py
  Tests/scripts/infrastructure_tests/test_collect_tests.py
Labels: docs-approved

#20961 Upgrade HTTPListRedirects to py3
  Packs/CommonScripts/ReleaseNotes/1_8_1.md
  Packs/CommonScripts/Scripts/HTTPListRedirects/HTTPListRedirects.py
  Packs/CommonScripts/Scripts/HTTPListRedirects/HTTPListRedirects.yml
  Packs/CommonScripts/Scripts/HTTPListRedirects/HTTPListRedirects_test.py
  Packs/CommonScripts/pack_metadata.json
Labels: docs-approved

#21581 Adding GA XSIAM machines
  .gitlab/ci/bucket-upload.yml
  .gitlab/ci/on-push.yml
  Tests/Marketplace/configure_and_install_packs.py
Labels: docs-approved, ForceMerge

#21399 [DATA ONBOARDING] - sections
  Packs/AWS-GuardDuty/Integrations/AWSGuardDuty/AWSGuardDuty.yml
  Packs/AWS-GuardDuty/pack_metadata.json
  Packs/GoogleDrive/Integrations/GoogleDrive/GoogleDrive.yml
  Packs/GoogleDrive/pack_metadata.json
  Packs/SplunkPy/Integrations/SplunkPy/SplunkPy.yml
  Packs/SplunkPy/pack_metadata.json
  Tests/Marketplace/approved_tags.json
Labels: docs-approved

#21590 TLP 2.0 Support
  Packs/CommonTypes/IndicatorFields/incidentfield-tlp.json
  Packs/CommonTypes/ReleaseNotes/3_3_23.md
  Packs/CommonTypes/pack_metadata.json
Labels: docs-approved

#21589 ProxyNotShell v2
  Packs/CVE_2022_41040_and_CVE_2022_41082_-_ProxyNotShell/Playbooks/playbook-CVE-2022-41040_&_CVE-2022-41082_-_ProxyNotShell.yml
  Packs/CVE_2022_41040_and_CVE_2022_41082_-_ProxyNotShell/ReleaseNotes/1_0_1.md
  Packs/CVE_2022_41040_and_CVE_2022_41082_-_ProxyNotShell/pack_metadata.json
Labels: docs-approved

#21604 Servicenow documentation
  Packs/ServiceNow/Integrations/ServiceNowv2/README.md
Labels: docs-approved

#21603 Crowdstrike deprecated bug fix
  Packs/CrowdStrikeFalcon/Integrations/CrowdStrikeFalcon/CrowdStrikeFalcon.py
  Packs/CrowdStrikeFalcon/Integrations/CrowdStrikeFalcon/CrowdStrikeFalcon_test.py
  Packs/CrowdStrikeFalcon/ReleaseNotes/1_9_5.md
  Packs/CrowdStrikeFalcon/pack_metadata.json
Labels: docs-approved

#20105 rewrite zendesk v2
  Packs/Zendesk/.pack-ignore
  Packs/Zendesk/.secrets-ignore
  Packs/Zendesk/Classifier/classifier-Zendesk_-_Incoming_Mapper.json
  Packs/Zendesk/IncidentFields/icidentfiled-Zendesk_CC'd.json
  Packs/Zendesk/IncidentFields/icidentfiled-Zendesk_Collaborators.json
  Packs/Zendesk/IncidentFields/icidentfiled-Zendesk_Custom_Fields.json
  Packs/Zendesk/IncidentFields/icidentfiled-Zendesk_Followers.json
  Packs/Zendesk/IncidentFields/icidentfiled-Zendesk_Forum_Id.json
  Packs/Zendesk/IncidentFields/icidentfiled-Zendesk_Organization.json
  Packs/Zendesk/IncidentFields/icidentfiled-Zendesk_Problem_Id.json
  Packs/Zendesk/IncidentFields/icidentfiled-Zendesk_Recipient.json
  Packs/Zendesk/IncidentFields/icidentfiled-Zendesk_Requester.json
  Packs/Zendesk/IncidentFields/icidentfiled-Zendesk_Ticket_Type.json
  Packs/Zendesk/Integrations/Zendeskv2/README.md
  Packs/Zendesk/Integrations/Zendeskv2/Zendeskv2.py
  Packs/Zendesk/Integrations/Zendeskv2/Zendeskv2.yml
  Packs/Zendesk/Integrations/Zendeskv2/Zendeskv2_image.png
  Packs/Zendesk/Integrations/Zendeskv2/Zendeskv2_test.py
  Packs/Zendesk/Integrations/Zendeskv2/test_data/no_orgainzations.json
  Packs/Zendesk/Integrations/Zendeskv2/test_data/one_orgainzation.json
  Packs/Zendesk/Integrations/Zendeskv2/test_data/single_organization.json
  Packs/Zendesk/Integrations/Zendeskv2/test_data/single_user.json
  Packs/Zendesk/Integrations/Zendeskv2/test_data/ticket_events/created_only_ticket_events.json
  Packs/Zendesk/Integrations/Zendeskv2/test_data/ticket_events/mixed_ticket_events.json
  Packs/Zendesk/Integrations/Zendeskv2/test_data/ticket_events/no_ticket_events.json
  Packs/Zendesk/Integrations/Zendeskv2/test_data/ticket_events/updated_only_ticket_events.json
  Packs/Zendesk/Integrations/Zendeskv2/test_data/tickets/10.json
  Packs/Zendesk/Integrations/Zendeskv2/test_data/tickets/20.json
  Packs/Zendesk/Integrations/Zendeskv2/test_data/two_orgainzations.json
  Packs/Zendesk/Integrations/Zendeskv2/test_data/users/1.json
  Packs/Zendesk/Integrations/Zendeskv2/test_data/users/2.json
  Packs/Zendesk/ReleaseNotes/2_0_0.md
  Packs/Zendesk/TestPlaybooks/Zendesk_V2_TEST.yml
  Packs/Zendesk/incidentTypes/incidenttype-Zendesk_Ticket.json
  Packs/Zendesk/pack_metadata.json
  Tests/conf.json
Labels: docs-approved

#21555 Crowdstrike FalconX Fix png Download
  Packs/CrowdStrikeFalconX/Integrations/CrowdStrikeFalconX/CrowdStrikeFalconX.py
  Packs/CrowdStrikeFalconX/Integrations/CrowdStrikeFalconX/CrowdStrikeFalconX.yml
  Packs/CrowdStrikeFalconX/Integrations/CrowdStrikeFalconX/CrowdStrikeFalconX_test.py
  Packs/CrowdStrikeFalconX/ReleaseNotes/1_2_12.md
  Packs/CrowdStrikeFalconX/pack_metadata.json
Labels: docs-approved

#21112 Migrate SendEmailToManager to Python 3
  Packs/Active_Directory_Query/.secrets-ignore
  Packs/Active_Directory_Query/ReleaseNotes/1_5_2.md
  Packs/Active_Directory_Query/Scripts/SendEmailToManager/README.md
  Packs/Active_Directory_Query/Scripts/SendEmailToManager/SendEmailToManager.py
  Packs/Active_Directory_Query/Scripts/SendEmailToManager/SendEmailToManager.yml
  Packs/Active_Directory_Query/Scripts/SendEmailToManager/SendEmailToManager_test.py
  Packs/Active_Directory_Query/Scripts/SendEmailToManager/test_data/ad-search.json
  Packs/Active_Directory_Query/Scripts/SendEmailToManager/test_data/addentitlement.json
  Packs/Active_Directory_Query/Scripts/SendEmailToManager/test_data/incident.json
  Packs/Active_Directory_Query/pack_metadata.json
Labels: docs-approved

#21620 fix .pack-ignore file
  Packs/Zendesk/.pack-ignore
Labels: docs-approved

#21625 RBR - ProxyNotShell updated descriptions
  Packs/CVE_2022_41040_and_CVE_2022_41082_-_ProxyNotShell/Playbooks/playbook-CVE-2022-41040_&_CVE-2022-41082_-_ProxyNotShell.yml
  Packs/CVE_2022_41040_and_CVE_2022_41082_-_ProxyNotShell/Playbooks/playbook-CVE-2022-41040_&_CVE-2022-41082_-_ProxyNotShell_README.md
  Packs/CVE_2022_41040_and_CVE_2022_41082_-_ProxyNotShell/README.md
  Packs/CVE_2022_41040_and_CVE_2022_41082_-_ProxyNotShell/ReleaseNotes/1_0_2.md
  Packs/CVE_2022_41040_and_CVE_2022_41082_-_ProxyNotShell/pack_metadata.json
Labels: docs-approved

#21593 Adding account outputs to azure active directory users
  Packs/MicrosoftGraphUser/.secrets-ignore
  Packs/MicrosoftGraphUser/Integrations/MicrosoftGraphUser/MicrosoftGraphUser.py
  Packs/MicrosoftGraphUser/Integrations/MicrosoftGraphUser/MicrosoftGraphUser.yml
  Packs/MicrosoftGraphUser/Integrations/MicrosoftGraphUser/MicrosoftGraphUser_test.py
  Packs/MicrosoftGraphUser/Integrations/MicrosoftGraphUser/README.md
  Packs/MicrosoftGraphUser/ReleaseNotes/1_5_1.md
  Packs/MicrosoftGraphUser/pack_metadata.json
Labels: docs-approved

#20851 [Enhancement] - Feed threat connect STIX objects
  Packs/FeedThreatConnect/.pack-ignore
  Packs/FeedThreatConnect/Integrations/FeedThreatConnect/FeedThreatConnect.py
  Packs/FeedThreatConnect/Integrations/FeedThreatConnect/FeedThreatConnect.yml
  Packs/FeedThreatConnect/Integrations/FeedThreatConnect/FeedThreatConnect_test.py
  Packs/FeedThreatConnect/Integrations/FeedThreatConnect/FeedThreatConnect_test/parsed_indicator.json
  Packs/FeedThreatConnect/Integrations/FeedThreatConnect/README.md
  Packs/FeedThreatConnect/Integrations/FeedThreatConnect/command_examples
  Packs/FeedThreatConnect/Integrations/FeedThreatConnect/test_data/indicators.json
  Packs/FeedThreatConnect/Integrations/FeedThreatConnect/test_data/parsed_indicator.json
  Packs/FeedThreatConnect/README.md
  Packs/FeedThreatConnect/ReleaseNotes/2_1_0.md
  Packs/FeedThreatConnect/pack_metadata.json
Labels: docs-approved

#21629 CIDR formatting script
  Packs/CommonScripts/ReleaseNotes/1_8_2.md
  Packs/CommonScripts/Scripts/VerifyCIDR/README.md
  Packs/CommonScripts/Scripts/VerifyCIDR/VerifyCIDR.py
  Packs/CommonScripts/Scripts/VerifyCIDR/VerifyCIDR.yml
  Packs/CommonScripts/Scripts/VerifyCIDR/VerifyCIDR_test.py
  Packs/CommonScripts/TestPlaybooks/VerifyCIDR-Test.yml
  Packs/CommonScripts/pack_metadata.json
  Packs/CommonTypes/.pack-ignore
  Packs/CommonTypes/IndicatorTypes/reputation-cidr.json
  Packs/CommonTypes/ReleaseNotes/3_3_24.md
  Packs/CommonTypes/pack_metadata.json
  Tests/conf.json
Labels: docs-approved

#21606 Send events extra logs
  Packs/Base/ReleaseNotes/1_31_27.md
  Packs/Base/Scripts/CommonServerPython/CommonServerPython.py
  Packs/Base/Scripts/CommonServerPython/CommonServerPython_test.py
  Packs/Base/Scripts/CommonServerPython/test_data/send_events_to_xsiam_data.py
  Packs/Base/pack_metadata.json
Labels: docs-approved

#20934 Changed body data to url params
  Packs/SignalSciences/Integrations/SignalSciences/SignalSciences.py
  Packs/SignalSciences/Integrations/SignalSciences/SignalSciences.yml
  Packs/SignalSciences/ReleaseNotes/1_0_11.md
  Packs/SignalSciences/pack_metadata.json
Labels: docs-approved

#21627 ibm_bigfix_display
  Packs/BigFix/pack_metadata.json
Labels: docs-approved

#21621 Panw pack names change
  Packs/AutoFocus/pack_metadata.json
  Packs/BPA/pack_metadata.json
  Packs/CortexDataLake/pack_metadata.json
  Packs/CortexXDR/pack_metadata.json
  Packs/ExpanseV2/pack_metadata.json
  Packs/PAN-OS/pack_metadata.json
  Packs/PANWComprehensiveInvestigation/pack_metadata.json
  Packs/PaloAltoNetworksAutomaticSLR_Community/pack_metadata.json
  Packs/PaloAltoNetworks_IoT/pack_metadata.json
  Packs/PaloAltoNetworks_IoT3rdParty/pack_metadata.json
  Packs/PaloAltoNetworks_SecurityAdvisories/pack_metadata.json
  Packs/PaloAltoNetworks_Threat_Vault/pack_metadata.json
  Packs/Palo_Alto_Networks_Enterprise_DLP/pack_metadata.json
  Packs/Palo_Alto_Networks_WildFire/pack_metadata.json
  Packs/PrismaAccess/pack_metadata.json
  Packs/PrismaCloud/pack_metadata.json
  Packs/PrismaCloudCompute/pack_metadata.json
  Packs/PrismaSaasSecurity/pack_metadata.json
Labels: docs-approved

#21630 Fixed bug in GetFailedTasks script
  Packs/IntegrationsAndIncidentsHealthCheck/ReleaseNotes/1_3_8.md
  Packs/IntegrationsAndIncidentsHealthCheck/Scripts/GetFailedTasks/GetFailedTasks.py
  Packs/IntegrationsAndIncidentsHealthCheck/Scripts/GetFailedTasks/GetFailedTasks.yml
  Packs/IntegrationsAndIncidentsHealthCheck/Scripts/GetFailedTasks/GetFailedTasks_test.py
  Packs/IntegrationsAndIncidentsHealthCheck/Scripts/GetFailedTasks/test_data/constants.py
  Packs/IntegrationsAndIncidentsHealthCheck/pack_metadata.json
Labels: docs-approved

#21645 fix import bug
  Packs/Zendesk/Integrations/Zendeskv2/Zendeskv2.py
  Packs/Zendesk/Integrations/Zendeskv2/Zendeskv2.yml
  Packs/Zendesk/ReleaseNotes/2_0_1.md
  Packs/Zendesk/pack_metadata.json
Labels: docs-approved

#21647 Temporarily fix for Zendesk v2 lint failure
  .gitlab/ci/bucket-upload.yml
Labels: docs-approved, ForceMerge

#21622 hide_deprecated_accenture_deepsight
  Packs/Symantec_Deepsight/pack_metadata.json
Labels: docs-approved

#21654 Redlock UTC Timestamp fix
  Packs/PrismaCloud/Integrations/RedLock/RedLock.py
  Packs/PrismaCloud/Integrations/RedLock/RedLock.yml
  Packs/PrismaCloud/ReleaseNotes/2_0_17.md
  Packs/PrismaCloud/pack_metadata.json
Labels: docs-approved

#21656 Revert "hide_deprecated_accenture_deepsight" & disable Mypy
  .gitlab/ci/global.yml
  Packs/Symantec_Deepsight/pack_metadata.json
Labels: docs-approved, ForceMerge

#21550 XSOAR Active Directory Query content pack update v1.5.0 issue
  Packs/Active_Directory_Query/Integrations/Active_Directory_Query/Active_Directory_Query.py
  Packs/Active_Directory_Query/Integrations/Active_Directory_Query/Active_Directory_Query.yml
  Packs/Active_Directory_Query/Integrations/Active_Directory_Query/Active_Directory_Query_test.py
  Packs/Active_Directory_Query/ReleaseNotes/1_5_3.md
  Packs/Active_Directory_Query/pack_metadata.json
Labels: docs-approved

#19383 Exodus Intelligence Contribution
  Packs/ExodusIntelligence/.pack-ignore
  Packs/ExodusIntelligence/.secrets-ignore
  Packs/ExodusIntelligence/Author_image.png
  Packs/ExodusIntelligence/IndicatorFields/indicatorfield-Application.json
  Packs/ExodusIntelligence/IndicatorFields/indicatorfield-Attack_Vector.json
  Packs/ExodusIntelligence/IndicatorFields/indicatorfield-CPE23URI.json
  Packs/ExodusIntelligence/IndicatorFields/indicatorfield-CPE_MATCH.json
  Packs/ExodusIntelligence/IndicatorFields/indicatorfield-CVE.json
  Packs/ExodusIntelligence/IndicatorFields/indicatorfield-Identifier.json
  Packs/ExodusIntelligence/IndicatorFields/indicatorfield-Links.json
  Packs/ExodusIntelligence/IndicatorFields/indicatorfield-Methods.json
  Packs/ExodusIntelligence/IndicatorFields/indicatorfield-Mitigation.json
  Packs/ExodusIntelligence/IndicatorFields/indicatorfield-Modules.json
  Packs/ExodusIntelligence/IndicatorFields/indicatorfield-Ports.json
  Packs/ExodusIntelligence/IndicatorFields/indicatorfield-Transport.json
  Packs/ExodusIntelligence/IndicatorFields/indicatorfield-XI_CVSS.json
  Packs/ExodusIntelligence/IndicatorFields/indicatorfield-XI_Description.json
  Packs/ExodusIntelligence/IndicatorFields/indicatorfield-XI_Scores.json
  Packs/ExodusIntelligence/IndicatorFields/indicatorfield-ZDIS.json
  Packs/ExodusIntelligence/IndicatorFields/indicatorfield-cpes.json
  Packs/ExodusIntelligence/IndicatorFields/indicatorfield-modified.json
  Packs/ExodusIntelligence/IndicatorFields/indicatorfield-product.json
  Packs/ExodusIntelligence/IndicatorFields/indicatorfield-published.json
  Packs/ExodusIntelligence/IndicatorFields/indicatorfield-vendor.json
  Packs/ExodusIntelligence/IndicatorTypes/ExodusIntelligence.json
  Packs/ExodusIntelligence/Integrations/ExodusVulnerabilityEnrichment/ExodusVulnerabilityEnrichment.py
  Packs/ExodusIntelligence/Integrations/ExodusVulnerabilityEnrichment/ExodusVulnerabilityEnrichment.yml
  Packs/ExodusIntelligence/Integrations/ExodusVulnerabilityEnrichment/ExodusVulnerabilityEnrichment_description.md
  Packs/ExodusIntelligence/Integrations/ExodusVulnerabilityEnrichment/ExodusVulnerabilityEnrichment_image.png
  Packs/ExodusIntelligence/Integrations/ExodusVulnerabilityEnrichment/ExodusVulnerabilityEnrichment_test.py
  Packs/ExodusIntelligence/Integrations/ExodusVulnerabilityEnrichment/Pipfile
  Packs/ExodusIntelligence/Integrations/ExodusVulnerabilityEnrichment/Pipfile.lock
  Packs/ExodusIntelligence/Integrations/ExodusVulnerabilityEnrichment/README.md
  Packs/ExodusIntelligence/Integrations/ExodusVulnerabilityEnrichment/command_examples
  Packs/ExodusIntelligence/Layouts/layoutscontainer-Exodus_Intelligence.json
  Packs/ExodusIntelligence/README.md
  Packs/ExodusIntelligence/TestPlaybooks/Test.yml
  Packs/ExodusIntelligence/pack_metadata.json
  package-lock.json
  package.json
Labels: Contribution, docs-approved, Partner, pending-demo, Contribution Form Filled, pending-contributor

#21653 deprecating d2, rming from XSIAM MP
  Packs/D2/pack_metadata.json
Labels: docs-approved

#21658 Remove Space to fix upload issue
  Tests/Marketplace/configure_and_install_packs.py
Labels: ForceMerge

#21597 [Luminate] Deprecate
  Packs/Luminate/Integrations/Luminate/Luminate.yml
  Packs/Luminate/ReleaseNotes/1_0_4.md
  Packs/Luminate/pack_metadata.json
Labels: docs-approved

#21657 Fix command line analysis tags
  Packs/CortexXDR/TestPlaybooks/Test_XDR_Playbook.yml
  Packs/CrowdStrikeFalcon/Playbooks/playbook-CrowdStrike_Falcon_Malware_-_Investigation_and_Response.yml
  Packs/CrowdStrikeFalcon/ReleaseNotes/1_9_6.md
  Packs/CrowdStrikeFalcon/pack_metadata.json
  Packs/MicrosoftDefenderAdvancedThreatProtection/Playbooks/playbook-MDE_Malware_-_Investigation_and_Response.yml
  Packs/MicrosoftDefenderAdvancedThreatProtection/ReleaseNotes/1_13_1.md
  Packs/MicrosoftDefenderAdvancedThreatProtection/pack_metadata.json
Labels: docs-approved

#21665 Added versioning info
  Packs/CiscoStealthwatch/Integrations/CiscoStealthwatch/README.md
Labels: docs-approved

#21633 [ThreatGrid] - fix bug in threat-grid-get-html-report-by-id command
  Packs/ThreatGrid/Integrations/ThreatGrid/ThreatGrid.py
  Packs/ThreatGrid/Integrations/ThreatGrid/ThreatGrid.yml
  Packs/ThreatGrid/ReleaseNotes/1_2_17.md
  Packs/ThreatGrid/pack_metadata.json
Labels: docs-approved, ForceMerge

#21600 [ExtractIndicatorsFromWordFile] to py3
  Packs/CommonScripts/ReleaseNotes/1_8_3.md
  Packs/CommonScripts/Scripts/ExtractIndicatorsFromWordFile/ExtractIndicatorsFromWordFile.py
  Packs/CommonScripts/Scripts/ExtractIndicatorsFromWordFile/ExtractIndicatorsFromWordFile.yml
  Packs/CommonScripts/Scripts/ExtractIndicatorsFromWordFile/README.md
  Packs/CommonScripts/pack_metadata.json
Labels: docs-approved

#21341 Tenable event collector
  Packs/Tenable_io/.secrets-ignore
  Packs/Tenable_io/Integrations/TenableioEventCollector/Pipfile
  Packs/Tenable_io/Integrations/TenableioEventCollector/Pipfile.lock
  Packs/Tenable_io/Integrations/TenableioEventCollector/README.md
  Packs/Tenable_io/Integrations/TenableioEventCollector/TenableioEventCollector.py
  Packs/Tenable_io/Integrations/TenableioEventCollector/TenableioEventCollector.yml
  Packs/Tenable_io/Integrations/TenableioEventCollector/TenableioEventCollector_description.md
  Packs/Tenable_io/Integrations/TenableioEventCollector/TenableioEventCollector_image.png
  Packs/Tenable_io/Integrations/TenableioEventCollector/TenableioEventCollector_test.py
  Packs/Tenable_io/Integrations/TenableioEventCollector/command_examples
  Packs/Tenable_io/Integrations/TenableioEventCollector/test_data/mock_chunk_content.json
  Packs/Tenable_io/Integrations/TenableioEventCollector/test_data/mock_chunks_status.json
  Packs/Tenable_io/Integrations/TenableioEventCollector/test_data/mock_chunks_status_error.json
  Packs/Tenable_io/Integrations/TenableioEventCollector/test_data/mock_chunks_status_processing.json
  Packs/Tenable_io/Integrations/TenableioEventCollector/test_data/mock_events.json
  Packs/Tenable_io/Integrations/TenableioEventCollector/test_data/mock_export_uuid.json
  Packs/Tenable_io/ModelingRules/TenableioEventCollector/TenableioEventCollector.xif
  Packs/Tenable_io/ModelingRules/TenableioEventCollector/TenableioEventCollector.yml
  Packs/Tenable_io/ModelingRules/TenableioEventCollector/TenableioEventCollector_schema.json
  Packs/Tenable_io/ReleaseNotes/2_0_0.md
  Packs/Tenable_io/pack_metadata.json
Labels: docs-approved

#21667 Partner doit solutions adoption start
  Packs/Pulsedive/README.md
  Packs/Pulsedive/ReleaseNotes/1_6_1.md
  Packs/Pulsedive/pack_metadata.json
Labels: Contribution, docs-approved, Partner, Contribution Form Filled

#21675 doIT solutions Pack Addopton
  Packs/CyberX-CentralManager/README.md
  Packs/CyberX-CentralManager/ReleaseNotes/1_0_4.md
  Packs/CyberX-CentralManager/pack_metadata.json
Labels: Contribution, docs-approved, Partner, Contribution Form Filled

#21691 Alibaba fix fetch no events
  Packs/AlibabaActionTrail/Integrations/AlibabaActionTrailEventCollector/AlibabaActionTrailEventCollector.py
  Packs/AlibabaActionTrail/Integrations/AlibabaActionTrailEventCollector/AlibabaActionTrailEventCollector.yml
  Packs/AlibabaActionTrail/ReleaseNotes/1_0_2.md
  Packs/AlibabaActionTrail/pack_metadata.json
Labels: docs-approved

#21559 Base64Decode - Add padding automatically
  Packs/CommonScripts/ReleaseNotes/1_9_0.md
  Packs/CommonScripts/Scripts/Base64Decode/Base64Decode.py
  Packs/CommonScripts/Scripts/Base64Decode/Base64Decode.yml
  Packs/CommonScripts/Scripts/Base64Decode/Base64Decode_test.py
  Packs/CommonScripts/Scripts/Base64Decode/README.md
  Packs/CommonScripts/pack_metadata.json
Labels: docs-approved

#21678 Add arg validation to slack-invite-users command
  Packs/Slack/Integrations/SlackV3/SlackV3.py
  Packs/Slack/Integrations/SlackV3/SlackV3.yml
  Packs/Slack/ReleaseNotes/3_1_5.md
  Packs/Slack/pack_metadata.json
Labels: docs-approved

#21624 Preview images
  Tests/Marketplace/marketplace_constants.py
  Tests/Marketplace/marketplace_services.py
  Tests/Marketplace/upload_packs.py
  Tests/scripts/collect_tests/constants.py
Labels: docs-approved

#20781 McAfee TIE - python 3
  Packs/McAfee-TIE/Integrations/McAfeeTIEV2/McAfeeTIEV2.py
  Packs/McAfee-TIE/Integrations/McAfeeTIEV2/McAfeeTIEV2.yml
  Packs/McAfee-TIE/Integrations/McAfeeTIEV2/McAfeeTIEV2_description.md
  Packs/McAfee-TIE/Integrations/McAfeeTIEV2/McAfeeTIEV2_image.png
  Packs/McAfee-TIE/Integrations/McAfeeTIEV2/McAfeeTIEV2_test.py
  Packs/McAfee-TIE/Integrations/McAfeeTIEV2/README.md
  Packs/McAfee-TIE/Integrations/McAfeeTIEV2/test_data/files_reputations/parsed_results.json
  Packs/McAfee-TIE/Integrations/McAfeeTIEV2/test_data/files_reputations/parsed_results_empty.json
  Packs/McAfee-TIE/Integrations/McAfeeTIEV2/test_data/files_reputations/raw_result.json
  Packs/McAfee-TIE/Integrations/McAfeeTIEV2/test_data/files_reputations/raw_result_empty.json
  Packs/McAfee-TIE/README.md
  Packs/McAfee-TIE/ReleaseNotes/2_0_0.md
  Packs/McAfee-TIE/pack_metadata.json
Labels: docs-approved

#21677 Cybereason Fetch Incidents Fix
  Packs/Cybereason/Integrations/Cybereason/Cybereason.py
  Packs/Cybereason/Integrations/Cybereason/Cybereason.yml
  Packs/Cybereason/Integrations/Cybereason/Cybereason_test.py
  Packs/Cybereason/ReleaseNotes/1_0_23.md
  Packs/Cybereason/pack_metadata.json
Labels: docs-approved

#20917 add pan-os nat, pbf, application-group CRUD commands
  Packs/PAN-OS/.pack-ignore
  Packs/PAN-OS/.secrets-ignore
  Packs/PAN-OS/Integrations/Panorama/Panorama.py
  Packs/PAN-OS/Integrations/Panorama/Panorama.yml
  Packs/PAN-OS/Integrations/Panorama/Panorama_test.py
  Packs/PAN-OS/Integrations/Panorama/README.md
  Packs/PAN-OS/Integrations/Panorama/command_examples.txt
  Packs/PAN-OS/Integrations/Panorama/test_data/list-nat-rules-response.json
  Packs/PAN-OS/Integrations/Panorama/test_data/list-pbf-rules-response-commited.json
  Packs/PAN-OS/Integrations/Panorama/test_data/list-pbf-rules-response-un-committed.json
  Packs/PAN-OS/Integrations/Panorama/test_data/list-redistribution-profiles-un-committed-response.json
  Packs/PAN-OS/Integrations/Panorama/test_data/list-virtual-routers-response-un-commited-router.json
  Packs/PAN-OS/Integrations/Panorama/test_data/list-virtual-routers-response.json
  Packs/PAN-OS/Integrations/Panorama/test_data/list_application_groups_un_committed.json
  Packs/PAN-OS/ReleaseNotes/1_15_0.md
  Packs/PAN-OS/pack_metadata.json
Labels: docs-approved

#21721 Slack malformed users
  Packs/Slack/Integrations/SlackV3/SlackV3.py
  Packs/Slack/ReleaseNotes/3_1_6.md
  Packs/Slack/pack_metadata.json
Labels: docs-approved

#21661 hiding packs stage 2
  Packs/Ansible_Powered_Integrations/pack_metadata.json
  Packs/CrowdStrikeHost/pack_metadata.json
  Packs/ExportIndicators/pack_metadata.json
  Packs/PrismaCloudComputeReporting/pack_metadata.json
  Packs/RSS/pack_metadata.json
  Packs/SNDBOX/pack_metadata.json
  Packs/Symantec_Deepsight/pack_metadata.json
  Packs/TCPIPUtils/pack_metadata.json
  Packs/WindowsDefenderAdvancedThreatProtection/pack_metadata.json
  Tests/Marketplace/search_and_install_packs.py
Labels: docs-approved

#21628 [Check Point Threat Emulation] - fix file command
  Packs/CheckPointSandBlast/Integrations/CheckPointSandBlast/CheckPointSandBlast.py
  Packs/CheckPointSandBlast/Integrations/CheckPointSandBlast/CheckPointSandBlast.yml
  Packs/CheckPointSandBlast/Integrations/CheckPointSandBlast/CheckPointSandBlast_test.py
  Packs/CheckPointSandBlast/Integrations/CheckPointSandBlast/README.md
  Packs/CheckPointSandBlast/ReleaseNotes/1_0_1.md
  Packs/CheckPointSandBlast/pack_metadata.json
Labels: docs-approved

#21722 Syslog V2 Tooltips Text
  Packs/Syslog/Integrations/Syslogv2/README.md
  Packs/Syslog/Integrations/Syslogv2/Syslogv2.yml
  Packs/Syslog/ReleaseNotes/2_0_10.md
  Packs/Syslog/pack_metadata.json
Labels: docs-approved

#21692 Adding urls formatting for finding phishing incidents text similarity
  Packs/Phishing/ReleaseNotes/3_3_6.md
  Packs/Phishing/Scripts/FindDuplicateEmailIncidents/FindDuplicateEmailIncidents.py
  Packs/Phishing/Scripts/FindDuplicateEmailIncidents/FindDuplicateEmailIncidents.yml
  Packs/Phishing/Scripts/FindDuplicateEmailIncidents/FindDuplicateEmailIncidents_test.py
  Packs/Phishing/Scripts/FindDuplicateEmailIncidents/README.md
  Packs/Phishing/pack_metadata.json
Labels: docs-approved

#21723 Deleted one model modeling rules
  Packs/FireEyeNX/ModelingRules/FireEyeNX_1_3/FireEyeNX_1_3.xif
  Packs/FireEyeNX/ModelingRules/FireEyeNX_1_3/FireEyeNX_1_3.yml
  Packs/FireEyeNX/ModelingRules/FireEyeNX_1_3/FireEyeNX_1_3_schema.json
  Packs/FortiGate/ModelingRules/FortiGate_1_3/FortiGate_1_3.xif
  Packs/FortiGate/ModelingRules/FortiGate_1_3/FortiGate_1_3.yml
  Packs/FortiGate/ModelingRules/FortiGate_1_3/FortiGate_1_3_schema.json
  Packs/Jira/ModelingRules/JiraEventCollector_1_3/JiraEventCollector_1_3.xif
  Packs/Jira/ModelingRules/JiraEventCollector_1_3/JiraEventCollector_1_3.yml
  Packs/Jira/ModelingRules/JiraEventCollector_1_3/JiraEventCollector_1_3_schema.json
  Packs/KnowBe4_KMSAT/ModelingRules/KnowBe4KMSATEventCollector_1_3/KnowBe4KMSATEventCollector_1_3.xif
  Packs/KnowBe4_KMSAT/ModelingRules/KnowBe4KMSATEventCollector_1_3/KnowBe4KMSATEventCollector_1_3.yml
  Packs/KnowBe4_KMSAT/ModelingRules/KnowBe4KMSATEventCollector_1_3/KnowBe4KMSATEventCollector_1_3_schema.json
  Packs/Zscaler/ModelingRules/ZscalerModelingRule_1_3/ZscalerModelingRule_1_3.xif
  Packs/Zscaler/ModelingRules/ZscalerModelingRule_1_3/ZscalerModelingRule_1_3.yml
  Packs/Zscaler/ModelingRules/ZscalerModelingRule_1_3/ZscalerModelingRule_1_3_schema.json
Labels: docs-approved

#21088 Add Pagination to MSCAS list-activities command
  Packs/MicrosoftCloudAppSecurity/Integrations/MicrosoftCloudAppSecurity/MicrosoftCloudAppSecurity.py
  Packs/MicrosoftCloudAppSecurity/Integrations/MicrosoftCloudAppSecurity/MicrosoftCloudAppSecurity.yml
  Packs/MicrosoftCloudAppSecurity/ReleaseNotes/2_1_2.md
  Packs/MicrosoftCloudAppSecurity/pack_metadata.json
Labels: docs-approved

#21745 install github actions with ci group
  .github/workflows/check-contributor-pack.yml
  .github/workflows/close_jira_issue_by_pr_merge.yml
  .github/workflows/link_edited_pr_to_jira_issue.yml
  .github/workflows/review-release-notes.yml
  .github/workflows/run-secrets-detection.yml
  .github/workflows/trigger-contribution-build.yml
Labels: docs-approved

#21740 devcontainer fix permissions
  .devcontainer/Dockerfile
  .devcontainer/createCerts.sh
  .devcontainer/createCommand.sh
  .devcontainer/devcontainer.json
Labels: docs-approved

#21744 SlackV3 NoneType users handling
  Packs/Slack/Integrations/SlackV3/SlackV3.py
  Packs/Slack/Integrations/SlackV3/SlackV3_test.py
  Packs/Slack/ReleaseNotes/3_1_7.md
  Packs/Slack/pack_metadata.json
Labels: docs-approved

#21747 update the docker images to python3
  Packs/DeveloperTools/TestPlaybooks/script-CreateDuplicateIncident.yml
  Packs/DeveloperTools/TestPlaybooks/script-TestCreateWordFile.yml
Labels: docs-approved

#21686 Adoption Script Fixes
  Utils/adopt_pack.bash
  Utils/adopt_utils.bash
Labels: docs-approved

#21743 Fix parse email files p7m bug
  Packs/CommonScripts/ReleaseNotes/1_9_1.md
  Packs/CommonScripts/Scripts/ParseEmailFilesV2/ParseEmailFilesV2.py
  Packs/CommonScripts/Scripts/ParseEmailFilesV2/ParseEmailFilesV2.yml
  Packs/CommonScripts/pack_metadata.json
Labels: docs-approved

#21746 update rn
  Packs/FireEyeNX/ReleaseNotes/1_1_6.md
  Packs/FireEyeNX/pack_metadata.json
  Packs/FortiGate/ReleaseNotes/1_0_14.md
  Packs/FortiGate/pack_metadata.json
  Packs/Jira/ReleaseNotes/2_0_14.md
  Packs/Jira/pack_metadata.json
  Packs/KnowBe4_KMSAT/ReleaseNotes/1_0_1.md
  Packs/KnowBe4_KMSAT/pack_metadata.json
  Packs/Zscaler/ReleaseNotes/1_3_1.md
  Packs/Zscaler/pack_metadata.json
Labels: docs-approved

#21716 Update Violation ID description
  Packs/Gamma/Integrations/Gamma/Gamma_description.md
  Packs/Gamma/Integrations/Gamma/README.md
  Packs/Gamma/ReleaseNotes/1_0_6.md
  Packs/Gamma/pack_metadata.json
Labels: docs-approved

#21751 volume for poetry and fix git config
  .devcontainer/Dockerfile
  .devcontainer/createCommand.sh
  .devcontainer/devcontainer.json
  .devcontainer/settings.json
Labels: docs-approved

#21739 Fix a bug FireEyeEX
  Packs/FireEyeEX/.pack-ignore
  Packs/FireEyeEX/Integrations/FireEyeEX/FireEyeEX.py
  Packs/FireEyeEX/Integrations/FireEyeEX/FireEyeEX.yml
  Packs/FireEyeEX/ReleaseNotes/2_0_9.md
  Packs/FireEyeEX/pack_metadata.json
Labels: docs-approved

#21664 Updated the integration to enable the new MAEC report capabilities an…
  Packs/Palo_Alto_Networks_WildFire/Integrations/Palo_Alto_Networks_WildFire_v2/Palo_Alto_Networks_WildFire_v2.py
  Packs/Palo_Alto_Networks_WildFire/Integrations/Palo_Alto_Networks_WildFire_v2/Palo_Alto_Networks_WildFire_v2.yml
  Packs/Palo_Alto_Networks_WildFire/Integrations/Palo_Alto_Networks_WildFire_v2/Palo_Alto_Networks_WildFire_v2_description.md
  Packs/Palo_Alto_Networks_WildFire/Integrations/Palo_Alto_Networks_WildFire_v2/README.md
  Packs/Palo_Alto_Networks_WildFire/Integrations/Palo_Alto_Networks_WildFire_v2/command_examples.txt
  Packs/Palo_Alto_Networks_WildFire/README.md
  Packs/Palo_Alto_Networks_WildFire/ReleaseNotes/2_1_7.md
  Packs/Palo_Alto_Networks_WildFire/pack_metadata.json
Labels: Contribution, Partner, Contribution Form Filled

#21694 Oletools phishing
  Packs/CommonPlaybooks/Playbooks/playbook-Extract_Indicators_From_File_-_Generic_v2_4_5.yml
  Packs/CommonPlaybooks/Playbooks/playbook-Extract_Indicators_From_File_-_Generic_v2_4_5_README.md
  Packs/CommonPlaybooks/ReleaseNotes/2_3_6.md
  Packs/CommonPlaybooks/doc_files/Extract_Indicators_From_File_-_Generic_v2.png
  Packs/CommonPlaybooks/pack_metadata.json
  Packs/CommonTypes/IncidentFields/incidentfield-Macro_Source_Code.json
  Packs/CommonTypes/ReleaseNotes/3_3_25.md
  Packs/CommonTypes/pack_metadata.json
  Packs/Phishing/Layouts/layoutscontainer-Phishing_v_3.json
  Packs/Phishing/Playbooks/Phishing_-_Generic_v3.yml
  Packs/Phishing/ReleaseNotes/3_3_7.md
  Packs/Phishing/doc_files/Phishing_-_Generic_v3.png
  Packs/Phishing/pack_metadata.json
Labels: docs-approved

#21632 Asm x2fields
  Packs/CortexAttackSurfaceManagement/IncidentFields/incidentfield-ASM_-_Alert_Summary.json
  Packs/CortexAttackSurfaceManagement/IncidentFields/incidentfield-ASM_-_Asset_ID.json
  Packs/CortexAttackSurfaceManagement/IncidentFields/incidentfield-ASM_-_Attack_Surface_Rule_ID.json
  Packs/CortexAttackSurfaceManagement/IncidentFields/incidentfield-ASM_-_Cloud.json
  Packs/CortexAttackSurfaceManagement/IncidentFields/incidentfield-ASM_-_Data_Collection.json
  Packs/CortexAttackSurfaceManagement/IncidentFields/incidentfield-ASM_-_Notification.json
  Packs/CortexAttackSurfaceManagement/IncidentFields/incidentfield-ASM_-_Private_IP.json
  Packs/CortexAttackSurfaceManagement/IncidentFields/incidentfield-ASM_-_Related.json
  Packs/CortexAttackSurfaceManagement/IncidentFields/incidentfield-ASM_-_Remediation.json
  Packs/CortexAttackSurfaceManagement/IncidentFields/incidentfield-ASM_-_Service_Detection.json
  Packs/CortexAttackSurfaceManagement/IncidentFields/incidentfield-ASM_-_Service_ID.json
  Packs/CortexAttackSurfaceManagement/IncidentFields/incidentfield-ASM_-_Service_Owner.json
  Packs/CortexAttackSurfaceManagement/IncidentFields/incidentfield-ASM_-_System_IDs.json
  Packs/CortexAttackSurfaceManagement/IncidentFields/incidentfield-ASM_-_Tags.json
  Packs/CortexAttackSurfaceManagement/ReleaseNotes/1_0_2.md
  Packs/CortexAttackSurfaceManagement/pack_metadata.json
Labels: Contribution, Contribution Form Filled, Internal

#21650 Jwilkes snow enrich
  Packs/ServiceNow/Playbooks/playbook-ServiceNow_CMDB_Search.yml
  Packs/ServiceNow/Playbooks/playbook-ServiceNow_CMDB_Search_README.md
  Packs/ServiceNow/ReleaseNotes/2_4_0.md
  Packs/ServiceNow/doc_files/ServiceNow_CMDB_Search.png
  Packs/ServiceNow/pack_metadata.json
Labels: Contribution, Contribution Form Filled, Community

#21784 fix create command
  .devcontainer/createCommand.sh
Labels: docs-approved

#21181 Gmail to python 3
  Packs/Gmail/.secrets-ignore
  Packs/Gmail/Integrations/Gmail/Gmail.py
  Packs/Gmail/Integrations/Gmail/Gmail.yml
  Packs/Gmail/Integrations/Gmail/Gmail_test.py
  Packs/Gmail/Integrations/Gmail/README.md
  Packs/Gmail/Integrations/Gmail/test_data/input_data.py
  Packs/Gmail/ReleaseNotes/1_2_0.md
  Packs/Gmail/TestPlaybooks/playbook-Get_Original_Email_-_Gmail_-_Test.yml
  Packs/Gmail/pack_metadata.json
  Packs/Phishing/Playbooks/Get_Original_Email_-_Gmail.yml
  Packs/Phishing/ReleaseNotes/3_3_8.md
  Packs/Phishing/pack_metadata.json
  Tests/conf.json
Labels: docs-approved

#19129 Add the first version of the Gatewatcher pack
  Packs/Gatewatcher-AionIQ/.pack-ignore
  Packs/Gatewatcher-AionIQ/.secrets-ignore
  Packs/Gatewatcher-AionIQ/Author_image.png
  Packs/Gatewatcher-AionIQ/Integrations/GCenter/GCenter.py
  Packs/Gatewatcher-AionIQ/Integrations/GCenter/GCenter.yml
  Packs/Gatewatcher-AionIQ/Integrations/GCenter/GCenter_description.md
  Packs/Gatewatcher-AionIQ/Integrations/GCenter/GCenter_image.png
  Packs/Gatewatcher-AionIQ/Integrations/GCenter/GCenter_test.py
  Packs/Gatewatcher-AionIQ/Integrations/GCenter/Pipfile
  Packs/Gatewatcher-AionIQ/Integrations/GCenter/Pipfile.lock
  Packs/Gatewatcher-AionIQ/Integrations/GCenter/README.md
  Packs/Gatewatcher-AionIQ/Integrations/GCenter/commands_examples.txt
  Packs/Gatewatcher-AionIQ/Integrations/GCenter/test_data/add_dga_list.json
  Packs/Gatewatcher-AionIQ/Integrations/GCenter/test_data/add_malcore_list.json
  Packs/Gatewatcher-AionIQ/Integrations/GCenter/test_data/es_query.json
  Packs/Gatewatcher-AionIQ/Integrations/GCenter/test_data/ignore_asset_name.json
  Packs/Gatewatcher-AionIQ/Integrations/GCenter/test_data/ignore_kuser_ip.json
  Packs/Gatewatcher-AionIQ/Integrations/GCenter/test_data/ignore_kuser_name.json
  Packs/Gatewatcher-AionIQ/Integrations/GCenter/test_data/ignore_mac_address.json
  Packs/Gatewatcher-AionIQ/Integrations/GCenter/test_data/raw_alerts_list.json
  Packs/Gatewatcher-AionIQ/Integrations/GCenter/test_data/raw_alerts_read.json
  Packs/Gatewatcher-AionIQ/Integrations/GCenter/test_data/send_malware.json
  Packs/Gatewatcher-AionIQ/Integrations/GCenter/test_data/send_powershell.json
  Packs/Gatewatcher-AionIQ/Integrations/GCenter/test_data/send_shellcode.json
  Packs/Gatewatcher-AionIQ/README.md
  Packs/Gatewatcher-AionIQ/TestPlaybooks/GCenter.yml
  Packs/Gatewatcher-AionIQ/pack_metadata.json
Labels: Contribution, docs-approved, Partner, ready-for-instance-test, pending-demo, post-demo, Contribution Form Filled, pending-contributor

#21790 mp packs revamp 1-30
  Packs/AWS-ACM/pack_metadata.json
  Packs/AWS-Athena/pack_metadata.json
  Packs/AWS-CloudTrail/pack_metadata.json
  Packs/AWS-EC2/pack_metadata.json
  Packs/AWS-GuardDuty/pack_metadata.json
  Packs/AWS-IAM/pack_metadata.json
  Packs/AWS-ILM/pack_metadata.json
  Packs/AWS-Lambda/pack_metadata.json
  Packs/AWS-NetworkFirewall/pack_metadata.json
  Packs/AWS-Route53/pack_metadata.json
  Packs/AWS-S3/pack_metadata.json
  Packs/AWS-SNS/pack_metadata.json
  Packs/AWS-SQS/pack_metadata.json
  Packs/AWS-SecurityHub/pack_metadata.json
  Packs/AWS_DynamoDB/pack_metadata.json
  Packs/AbnormalSecurity/pack_metadata.json
  Packs/AccentureCTI_Feed/pack_metadata.json
  Packs/FeedAWS/pack_metadata.json
  Packs/Feedsslabusech/pack_metadata.json
Labels: docs-approved

#21749 mp-team-updates
  .github/CODEOWNERS
Labels: docs-approved

#21750 permissions for defender 365
  Packs/Microsoft365Defender/Integrations/Microsoft365Defender/Microsoft365Defender_description.md
  Packs/Microsoft365Defender/Integrations/Microsoft365Defender/README.md
  Packs/Microsoft365Defender/ReleaseNotes/4_3_1.md
  Packs/Microsoft365Defender/pack_metadata.json
Labels: bug, docs-approved

#21707 Accessdata v1
  Packs/Accessdata/Integrations/Accessdata/Accessdata.yml
  Packs/Accessdata/Playbooks/playbook-Accessdata__Dump_memory_for_malicious_process.yml
  Packs/Accessdata/Scripts/AccessdataCheckProcessExistsInSnapshot/AccessdataCheckProcessExistsInSnapshot.yml
  Packs/Accessdata/pack_metadata.json
Labels: Contribution, Partner, Contribution Form Filled

#21163 XM 7356 cortex xsoar dynamic entity search
  Packs/XMCyber/Author_image.png
  Packs/XMCyber/Classifiers/classifier-mapper-XM_Cyber_Incident.json
  Packs/XMCyber/IncidentFields/incidentfield-Affected_Entities_List.json
  Packs/XMCyber/IncidentFields/incidentfield-Compromising_Techniques.json
  Packs/XMCyber/IncidentFields/incidentfield-Critical_Assets_At_Risk.json
  Packs/XMCyber/IncidentFields/incidentfield-Critical_Assets_at_Risk_List.json
  Packs/XMCyber/IncidentFields/incidentfield-Entity_Name.json
  Packs/XMCyber/IncidentFields/incidentfield-Entity_Report.json
  Packs/XMCyber/IncidentFields/incidentfield-Entity_Type.json
  Packs/XMCyber/IncidentFields/incidentfield-Is_Entity_Critical_Asset.json
  Packs/XMCyber/IncidentFields/incidentfield-Security_Score_Trend.json
  Packs/XMCyber/IncidentFields/incidentfield-Technique_Choke_Points.json
  Packs/XMCyber/IncidentFields/incidentfield-Technique_Name.json
  Packs/XMCyber/IncidentFields/incidentfield-XM_Cyber_Advices.json
  Packs/XMCyber/IncidentFields/incidentfield-XM_Cyber_Avg_Complexity_Level.json
  Packs/XMCyber/IncidentFields/incidentfield-XM_Cyber_Avg_Complexity_Score.json
  Packs/XMCyber/IncidentFields/incidentfield-XM_Cyber_Critical_Assets_Trend.json
  Packs/XMCyber/IncidentFields/incidentfield-XM_Cyber_Dashboard.json
  Packs/XMCyber/IncidentFields/incidentfield-XM_Cyber_Mitre.json
  Packs/XMCyber/IncidentFields/incidentfield-XM_Cyber_Report.json
  Packs/XMCyber/IncidentFields/incidentfield-XM_Cyber_Security_Score.json
  Packs/XMCyber/IncidentFields/incidentfield-XM_Cyber_Security_Score_Grade.json
  Packs/XMCyber/IncidentFields/incidentfield-XM_Cyber_Security_Score_Trend.json
  Packs/XMCyber/IncidentFields/incidentfield-XM_Cyber_Technique_Description.json
  Packs/XMCyber/Integrations/XMCyberIntegration/README.md
  Packs/XMCyber/Integrations/XMCyberIntegration/XMCyberIntegration.py
  Packs/XMCyber/Integrations/XMCyberIntegration/XMCyberIntegration.yml
  Packs/XMCyber/Integrations/XMCyberIntegration/XMCyberIntegration_image.png
  Packs/XMCyber/Integrations/XMCyberIntegration/XMCyberIntegration_test.py
  Packs/XMCyber/Integrations/XMCyberIntegration/test_data/entity_id.json
  Packs/XMCyber/Integrations/XMCyberIntegration/test_data/version.json
  Packs/XMCyber/Layouts/layoutscontainer-XM_Cyber_Layout.json
  Packs/XMCyber/Layouts/layoutscontainer-XM_Cyber_Security_Score.json
  Packs/XMCyber/Layouts/layoutscontainer-XM_Cyber_Technique.json
  Packs/XMCyber/Playbooks/Endpoint_Enrichment_By_EntityId_XM_Cyber.yml
  Packs/XMCyber/Playbooks/Endpoint_Enrichment_By_EntityId_XM_Cyber_README.md
  Packs/XMCyber/Playbooks/Endpoint_Enrichment_By_Hostname_XM_Cyber.yml
  Packs/XMCyber/Playbooks/Endpoint_Enrichment_By_Hostname_XM_Cyber_README.md
  Packs/XMCyber/Playbooks/Endpoint_Enrichment_By_IP_XM_Cyber.yml
  Packs/XMCyber/Playbooks/Endpoint_Enrichment_By_IP_XM_Cyber_README.md
  Packs/XMCyber/Playbooks/Scan_and_Isolate_XM_Cyber.yml
  Packs/XMCyber/Playbooks/Scan_and_Isolate_XM_Cyber_README.md
  Packs/XMCyber/ReleaseNotes/1_0_16.json
  Packs/XMCyber/ReleaseNotes/1_0_16.md
  Packs/XMCyber/TestPlaybooks/XMCyberIntegration-Test.yml
  Packs/XMCyber/doc_files/Endpoint_Enrichment_By_Hostname_-_XM_Cyber.png
  Packs/XMCyber/pack_metadata.json
Labels: Contribution, docs-approved, Partner, Contribution Form Filled, pending-contributor

#21602 [Preempt] deprecate
  Packs/Preempt/Integrations/Preempt/Preempt.yml
  Packs/Preempt/Integrations/Preempt/README.md
  Packs/Preempt/ReleaseNotes/1_0_7.md
  Packs/Preempt/TestPlaybooks/playbook-Preempt_Test.yml
  Packs/Preempt/pack_metadata.json
  Tests/conf.json
Labels: docs-approved

#20800 Profpoint trap event collector
  Packs/ProofpointThreatResponse/Integrations/ProofpointThreatResponseEventCollector/ProofpointThreatResponseEventCollector.py
  Packs/ProofpointThreatResponse/Integrations/ProofpointThreatResponseEventCollector/ProofpointThreatResponseEventCollector.yml
  Packs/ProofpointThreatResponse/Integrations/ProofpointThreatResponseEventCollector/ProofpointThreatResponseEventCollector_description.md
  Packs/ProofpointThreatResponse/Integrations/ProofpointThreatResponseEventCollector/ProofpointThreatResponseEventCollector_image.png
  Packs/ProofpointThreatResponse/Integrations/ProofpointThreatResponseEventCollector/ProofpointThreatResponseEventCollector_test.py
  Packs/ProofpointThreatResponse/Integrations/ProofpointThreatResponseEventCollector/README.md
  Packs/ProofpointThreatResponse/Integrations/ProofpointThreatResponseEventCollector/test_data/expected_result.json
  Packs/ProofpointThreatResponse/Integrations/ProofpointThreatResponseEventCollector/test_data/raw_response.json
  Packs/ProofpointThreatResponse/ModelingRules/ProofpointThreatResponseModelingRules/ProofpointThreatResponseModelingRules.xif
  Packs/ProofpointThreatResponse/ModelingRules/ProofpointThreatResponseModelingRules/ProofpointThreatResponseModelingRules.yml
  Packs/ProofpointThreatResponse/ModelingRules/ProofpointThreatResponseModelingRules/ProofpointThreatResponseModelingRules_schema.json
  Packs/ProofpointThreatResponse/ReleaseNotes/2_0_0.md
  Packs/ProofpointThreatResponse/pack_metadata.json
Labels: docs-approved, ForceMerge

#21806 add-Threat Intelligence Management-tag
  Tests/Marketplace/approved_tags.json
Labels: docs-approved

#21799 Fireeye hx file bug fix
  Packs/FireEyeHX/Integrations/FireEyeHXv2/FireEyeHXv2.py
  Packs/FireEyeHX/Integrations/FireEyeHXv2/FireEyeHXv2.yml
  Packs/FireEyeHX/ReleaseNotes/2_2_8.md
  Packs/FireEyeHX/TestPlaybooks/playbook-FireEyeHXv2_Test.yml
  Packs/FireEyeHX/TestPlaybooks/playbook-FireEyeHXv2_without_polling_Test.yml
  Packs/FireEyeHX/pack_metadata.json
Labels: docs-approved, release-notes-only

#21802 update tags/cateogries 103
  Packs/AWS_DynamoDB/pack_metadata.json
  Packs/AccessInvestigation/pack_metadata.json
  Packs/Active_Directory_Query/pack_metadata.json
  Packs/AgariPhishingDefense/pack_metadata.json
  Packs/AlienVault_OTX/pack_metadata.json
  Packs/AnsibleAlibabaCloud/pack_metadata.json
  Packs/AnsibleAzure/pack_metadata.json
  Packs/AnsibleCiscoIOS/pack_metadata.json
  Packs/AnsibleCiscoNXOS/pack_metadata.json
  Packs/AnsibleHetznerCloud/pack_metadata.json
  Packs/AnsibleKubernetes/pack_metadata.json
  Packs/AnsibleLinux/pack_metadata.json
  Packs/AnsibleMicrosoftWindows/pack_metadata.json
  Packs/AnsibleTower/pack_metadata.json
  Packs/AnsibleVMware/pack_metadata.json
  Packs/Arkime/pack_metadata.json
  Packs/FeedAlienVault/pack_metadata.json
  Packs/TeamCymru/pack_metadata.json
Labels: docs-approved

#21819 add missing "tags", add tag to approved_tags
  Packs/AbnormalSecurity/pack_metadata.json
  Tests/Marketplace/approved_tags.json
Labels: docs-approved

#21007 Moving to py3 RunDockerCommand
  Packs/CommonScripts/ReleaseNotes/1_9_2.md
  Packs/CommonScripts/Scripts/RunDockerCommand/README.md
  Packs/CommonScripts/Scripts/RunDockerCommand/RunDockerCommand.py
  Packs/CommonScripts/Scripts/RunDockerCommand/RunDockerCommand.yml
  Packs/CommonScripts/Scripts/RunDockerCommand/RunDockerCommand_test.py
  Packs/CommonScripts/pack_metadata.json
Labels: docs-approved

#21794 Update google vault to py3
  Packs/GoogleVault/Integrations/GoogleVault/GoogleVault.py
  Packs/GoogleVault/Integrations/GoogleVault/GoogleVault.yml
  Packs/GoogleVault/ReleaseNotes/1_0_8.md
  Packs/GoogleVault/pack_metadata.json
Labels: docs-approved

#21576 [AWS Feed] Support missing feeds
  Packs/FeedAWS/Integrations/FeedAWS/FeedAWS.py
  Packs/FeedAWS/Integrations/FeedAWS/FeedAWS.yml
  Packs/FeedAWS/Integrations/FeedAWS/README.md
  Packs/FeedAWS/ReleaseNotes/1_1_19.md
  Packs/FeedAWS/pack_metadata.json
Labels: docs-approved

#21807 Mp revamp 600 630
  Packs/CortexXDR/pack_metadata.json
  Packs/PICUS/pack_metadata.json
  Packs/PaloAltoNetworks_IoT/pack_metadata.json
  Packs/PaloAltoNetworks_IoT3rdParty/pack_metadata.json
  Packs/PaloAltoNetworks_PAN_OS_EDL_Management/pack_metadata.json
  Packs/PaloAltoNetworks_SecurityAdvisories/pack_metadata.json
  Packs/PaloAltoNetworks_Threat_Vault/pack_metadata.json
  Packs/Palo_Alto_Networks_Enterprise_DLP/pack_metadata.json
  Packs/Palo_Alto_Networks_WildFire/pack_metadata.json
  Packs/ParseHTMLTables/pack_metadata.json
  Packs/ParseYAML/pack_metadata.json
  Packs/PcapAnalysis/pack_metadata.json
  Packs/PenfieldAI/pack_metadata.json
  Packs/PerceptionPoint/pack_metadata.json
  Packs/Perch/pack_metadata.json
  Packs/PhishUp/pack_metadata.json
  Packs/Phishing/pack_metadata.json
  Packs/PhishingAlerts/pack_metadata.json
  Packs/PhishingURL/pack_metadata.json
Labels: docs-approved

#21822 revamp usecases/tags/categories 70-109
  Packs/Arduino/pack_metadata.json
  Packs/ArrayToCSV/pack_metadata.json
  Packs/Asset/pack_metadata.json
  Packs/AtlassianConfluenceCloud/pack_metadata.json
  Packs/AttachmentsPreProcessing/pack_metadata.json
  Packs/Attlasian/pack_metadata.json
  Packs/AutoFocus/pack_metadata.json
  Packs/Automox/pack_metadata.json
  Packs/AzureActiveDirectory/pack_metadata.json
  Packs/AzureCompute/pack_metadata.json
  Packs/AzureDataExplorer/pack_metadata.json
  Packs/AzureFirewall/pack_metadata.json
  Packs/AzureKeyVault/pack_metadata.json
  Packs/AzureKubernetesServices/pack_metadata.json
  Packs/AzureNetworkSecurityGroups/pack_metadata.json
  Packs/AzureRiskyUsers/pack_metadata.json
  Packs/AzureSQLManagement/pack_metadata.json
  Packs/AzureSentinel/pack_metadata.json
  Packs/AzureStorage/pack_metadata.json
  Packs/AzureStorageContainer/pack_metadata.json
  Packs/AzureStorageFileShare/pack_metadata.json
  Packs/AzureStorageQueue/pack_metadata.json
  Packs/AzureStorageTable/pack_metadata.json
  Packs/AzureWAF/pack_metadata.json
Labels: docs-approved

#21785 Changed author for OctoxLabs Pack
  Packs/OctoxLabs/pack_metadata.json
Labels: docs-approved

#21825 Fix validation failure
  Packs/AccessInvestigation/pack_metadata.json
Labels: docs-approved

#21719 Optimizer fix for veersion 10.1.6
  Packs/PANOSPolicyOptimizer/Integrations/PANOSPolicyOptimizer/PANOSPolicyOptimizer.py
  Packs/PANOSPolicyOptimizer/Integrations/PANOSPolicyOptimizer/PANOSPolicyOptimizer.yml
  Packs/PANOSPolicyOptimizer/Integrations/PANOSPolicyOptimizer/PANOSPolicyOptimizer_test.py
  Packs/PANOSPolicyOptimizer/Integrations/PANOSPolicyOptimizer/README.md
  Packs/PANOSPolicyOptimizer/ReleaseNotes/1_1_0.md
  Packs/PANOSPolicyOptimizer/pack_metadata.json
Labels: docs-approved

#21149 Adding new integration - Aws Secrets Manager
  Packs/Aws-SecretsManager/.pack-ignore
  Packs/Aws-SecretsManager/.secrets-ignore
  Packs/Aws-SecretsManager/Integrations/AwsSecretsManager/AwsSecretsManager.py
  Packs/Aws-SecretsManager/Integrations/AwsSecretsManager/AwsSecretsManager.yml
  Packs/Aws-SecretsManager/Integrations/AwsSecretsManager/AwsSecretsManager_description.md
  Packs/Aws-SecretsManager/Integrations/AwsSecretsManager/AwsSecretsManager_image.png
  Packs/Aws-SecretsManager/Integrations/AwsSecretsManager/AwsSecretsManager_test.py
  Packs/Aws-SecretsManager/Integrations/AwsSecretsManager/Pipfile
  Packs/Aws-SecretsManager/Integrations/AwsSecretsManager/Pipfile.lock
  Packs/Aws-SecretsManager/Integrations/AwsSecretsManager/README.md
  Packs/Aws-SecretsManager/Integrations/AwsSecretsManager/command_examples
  Packs/Aws-SecretsManager/README.md
  Packs/Aws-SecretsManager/TestPlaybooks/AwsSecretsManagerTest.yml
  Packs/Aws-SecretsManager/pack_metadata.json
  Tests/conf.json
Labels: docs-approved

#21826 revamp usecases/tags/categories 110-138
  Packs/BMCDiscovery/pack_metadata.json
  Packs/Base/pack_metadata.json
  Packs/BatchData/pack_metadata.json
  Packs/Binalyze/pack_metadata.json
  Packs/BitDam/pack_metadata.json
  Packs/BitcoinAbuse/pack_metadata.json
  Packs/BluecatAddressManager/pack_metadata.json
  Packs/Bonusly/pack_metadata.json
  Packs/BruteForce/pack_metadata.json
  Packs/CIRCLHashlookup/pack_metadata.json
  Packs/CTIX/pack_metadata.json
  Packs/CVESearch/pack_metadata.json
  Packs/FeedBambenekConsulting/pack_metadata.json
  Packs/FeedCSV/pack_metadata.json
Labels: docs-approved

#21631 bug fix Mcafee EMS
  Packs/McAfee_ESM/Integrations/McAfee_ESM_v2/McAfee_ESM_v2.py
  Packs/McAfee_ESM/Integrations/McAfee_ESM_v2/McAfee_ESM_v2.yml
  Packs/McAfee_ESM/Integrations/McAfee_ESM_v2/McAfee_ESM_v2_test.py
  Packs/McAfee_ESM/ReleaseNotes/1_1_24.md
  Packs/McAfee_ESM/pack_metadata.json
  Tests/conf.json
Labels: docs-approved

#21782 Update google resource manager to py3
  Packs/GoogleResourceManager/Integrations/GoogleResourceManager/GoogleResourceManager.py
  Packs/GoogleResourceManager/Integrations/GoogleResourceManager/GoogleResourceManager.yml
  Packs/GoogleResourceManager/ReleaseNotes/1_0_3.md
  Packs/GoogleResourceManager/pack_metadata.json
Labels: docs-approved

#21336 Update reputation commands with isarray
  Packs/EmailRepIO/.pack-ignore
  Packs/EmailRepIO/Integrations/EmailRepIO/EmailRepIO.py
  Packs/EmailRepIO/Integrations/EmailRepIO/EmailRepIO.yml
  Packs/EmailRepIO/Integrations/EmailRepIO/EmailRepIO_test.py
  Packs/EmailRepIO/Integrations/EmailRepIO/test_data/multiple_reputation_get_results.json
  Packs/EmailRepIO/ReleaseNotes/1_0_18.md
  Packs/EmailRepIO/pack_metadata.json
  Packs/ImpossibleTraveler/Playbooks/Impossible_Traveler.yml
  Packs/ImpossibleTraveler/ReleaseNotes/1_2_7.md
  Packs/ImpossibleTraveler/pack_metadata.json
  Packs/Ipstack/.pack-ignore
  Packs/Ipstack/Integrations/Ipstack/Ipstack.py
  Packs/Ipstack/Integrations/Ipstack/Ipstack.yml
  Packs/Ipstack/Integrations/Ipstack/Ipstack_test.py
  Packs/Ipstack/ReleaseNotes/1_0_9.md
  Packs/Ipstack/pack_metadata.json
  Packs/ThreatMiner/.pack-ignore
  Packs/ThreatMiner/Integrations/ThreatMiner/ThreatMiner.py
  Packs/ThreatMiner/Integrations/ThreatMiner/ThreatMiner.yml
  Packs/ThreatMiner/ReleaseNotes/1_0_10.md
  Packs/ThreatMiner/pack_metadata.json
  Packs/ipinfo/.pack-ignore
  Packs/ipinfo/Integrations/ipinfo_v2/ipinfo_v2.py
  Packs/ipinfo/Integrations/ipinfo_v2/ipinfo_v2.yml
  Packs/ipinfo/Integrations/ipinfo_v2/ipinfo_v2_test.py
  Packs/ipinfo/Integrations/ipinfo_v2/test_data/ip_8.8.8.8_command_results.json
  Packs/ipinfo/Integrations/ipinfo_v2/test_data/ip_8.8.8.8_response.json
  Packs/ipinfo/ReleaseNotes/2_1_5.md
  Packs/ipinfo/pack_metadata.json
Labels: docs-approved

#21818 Mp packs revamp 631 660
  Packs/FeedPlainText/pack_metadata.json
  Packs/FeedPublicDNS/pack_metadata.json
  Packs/PicusAutomation/pack_metadata.json
  Packs/PingIdentity/pack_metadata.json
  Packs/PolySwarm/pack_metadata.json
  Packs/PopularCybersecurityNews/pack_metadata.json
  Packs/PostmarkSpamcheck/pack_metadata.json
  Packs/PowerShellUtilities/pack_metadata.json
  Packs/PowershellRemoting/pack_metadata.json
  Packs/PrismaAccess/pack_metadata.json
  Packs/PrismaCloud/pack_metadata.json
  Packs/PrismaCloudCompute/pack_metadata.json
  Packs/PrismaCloudComputeReporting/pack_metadata.json
  Packs/PrismaSaasSecurity/pack_metadata.json
  Packs/ProofpointServerProtection/pack_metadata.json
  Packs/ProofpointTAP/pack_metadata.json
  Packs/ProofpointThreatResponse/pack_metadata.json
  Packs/PublishList/pack_metadata.json
  Packs/Pulsedive/pack_metadata.json
  Packs/QRCodeReader/pack_metadata.json
  Packs/Qintel/pack_metadata.json
Labels: docs-approved

#21816 [malwarebytes-254] Fixed an issue with ***!malwarebytes-list-endpoint-info*** command
  Packs/Malwarebytes/Integrations/Malwarebytes/Malwarebytes.py
  Packs/Malwarebytes/Integrations/Malwarebytes/Malwarebytes.yml
  Packs/Malwarebytes/ReleaseNotes/1_1_9.md
  Packs/Malwarebytes/pack_metadata.json
Labels: Contribution, docs-approved, Partner, Contribution Form Filled

#21839 add Core to approved, fix tag in bitcoin abuse
  Packs/Base/pack_metadata.json
  Packs/BitcoinAbuse/pack_metadata.json
  Tests/Marketplace/approved_tags.json
Labels: docs-approved

#21859 add-breach-simulation
  Tests/Marketplace/approved_tags.json
Labels: docs-approved

#21554 Malware Investigation and response v2
  Packs/CommonTypes/IncidentFields/incidentfield-Containment_SLA.json
  Packs/CommonTypes/IncidentFields/incidentfield-Triage_SLA.json
  Packs/CommonTypes/ReleaseNotes/3_3_26.md
  Packs/CommonTypes/pack_metadata.json
  Packs/CortexXDR/Playbooks/playbook-Cortex_XDR_-_True_Positive_Incident_Handling.yml
  Packs/CortexXDR/Playbooks/playbook-Cortex_XDR_-_True_Positive_Incident_Handling_README.md
  Packs/CortexXDR/Playbooks/playbook-Cortex_XDR_Malware_-_Investigation_And_Response.yml
  Packs/CortexXDR/ReleaseNotes/4_8_22.md
  Packs/CortexXDR/doc_files/Cortex_XDR_-_True_Positive_Incident_Handling.png
  Packs/CortexXDR/doc_files/Cortex_XDR_Malware_-_Investigation_And_Response.png
  Packs/CortexXDR/pack_metadata.json
  Packs/CrowdStrikeFalcon/Playbooks/playbook-CrowdStrike_Falcon_-_True_Positive_Incident_Handling.yml
  Packs/CrowdStrikeFalcon/Playbooks/playbook-CrowdStrike_Falcon_-_True_Positive_Incident_Handling_README.md
  Packs/CrowdStrikeFalcon/Playbooks/playbook-CrowdStrike_Falcon_Malware_-_Investigation_and_Response.yml
  Packs/CrowdStrikeFalcon/ReleaseNotes/1_9_7.md
  Packs/CrowdStrikeFalcon/doc_files/CrowdStrike_Falcon_-_True_Positive_Incident_Handling.png
  Packs/CrowdStrikeFalcon/doc_files/CrowdStrike_Falcon_Malware_-_Investigation_and_Response.png
  Packs/CrowdStrikeFalcon/pack_metadata.json
  Packs/MalwareInvestigationAndResponse/Layouts/layoutscontainer-Malware_Investigation_and_Response.json
  Packs/MalwareInvestigationAndResponse/Playbooks/playbook-Malware_Investigation_and_Response_Incident_Handler.yml
  Packs/MalwareInvestigationAndResponse/ReleaseNotes/2_0_0.md
  Packs/MalwareInvestigationAndResponse/doc_files/Malware_Investigation_&_Response_Incident_Handler.png
  Packs/MalwareInvestigationAndResponse/pack_metadata.json
  Packs/MicrosoftDefenderAdvancedThreatProtection/Playbooks/playbook-MDE_-_Host_Advanced_Hunting.yml
  Packs/MicrosoftDefenderAdvancedThreatProtection/Playbooks/playbook-MDE_-_Host_Advanced_Hunting_README.md
  Packs/MicrosoftDefenderAdvancedThreatProtection/Playbooks/playbook-MDE_-_True_Positive_Incident_Handling.yml
  Packs/MicrosoftDefenderAdvancedThreatProtection/Playbooks/playbook-MDE_-_True_Positive_Incident_Handling_README.md
  Packs/MicrosoftDefenderAdvancedThreatProtection/Playbooks/playbook-MDE_Malware_-_Investigation_and_Response.yml
  Packs/MicrosoftDefenderAdvancedThreatProtection/Playbooks/playbook-MDE_Malware_-_Investigation_and_Response_README.md
  Packs/MicrosoftDefenderAdvancedThreatProtection/ReleaseNotes/1_13_2.md
  Packs/MicrosoftDefenderAdvancedThreatProtection/doc_files/MDE_-_Host_Advanced_Hunting.png
  Packs/MicrosoftDefenderAdvancedThreatProtection/doc_files/MDE_-_True_Positive_Incident_Handling.png
  Packs/MicrosoftDefenderAdvancedThreatProtection/doc_files/MDE_Malware_-_Investigation_and_Response.png
  Packs/MicrosoftDefenderAdvancedThreatProtection/pack_metadata.json
Labels: docs-approved

#21832 Editing sanity tests list in XSIAM
  Tests/conf.json
Labels: docs-approved

#21643 [System Diagnostics and Health Check] HealthCheckPlaybookAnalysis script error fix
  Packs/HealthCheck/ReleaseNotes/2_0_3.md
  Packs/HealthCheck/Scripts/HealthCheckPlaybookAnalysis/HealthCheckPlaybookAnalysis.py
  Packs/HealthCheck/Scripts/HealthCheckPlaybookAnalysis/HealthCheckPlaybookAnalysis.yml
  Packs/HealthCheck/pack_metadata.json
Labels: Contribution, docs-approved, Contribution Form Filled, Community

#21649 Partner Armis adopt complete
  Packs/Armis/Author_image.png
  Packs/Armis/README.md
  Packs/Armis/ReleaseNotes/1_0_11.md
  Packs/Armis/pack_metadata.json
Labels: Contribution, docs-approved, Partner, Contribution Form Filled, pending-contributor

#21824 mp_packs_revamp_661-702
  Packs/FeedRSS/pack_metadata.json
  Packs/FeedReversingLabsRansomwareAndRelatedToolsApp/pack_metadata.json
  Packs/MajorBreachesInvestigationandResponse/pack_metadata.json
  Packs/QSS/pack_metadata.json
  Packs/QuestKace/pack_metadata.json
  Packs/RSS/pack_metadata.json
  Packs/RSTCloud/pack_metadata.json
  Packs/RandomElementFromList/pack_metadata.json
  Packs/RandomImages_VideosAndAudio/pack_metadata.json
  Packs/Ransomware/pack_metadata.json
  Packs/RedCanary/pack_metadata.json
  Packs/Redact_DefangIndicators_URLs_IPs_Email/pack_metadata.json
  Packs/RegexReplace/pack_metadata.json
  Packs/Remedy_AR/pack_metadata.json
  Packs/RemoveEmpty/pack_metadata.json
  Packs/RemoveEmptyEvidence/pack_metadata.json
  Packs/ReversingLabs_A1000/pack_metadata.json
  Packs/ReversingLabs_TitaniumScale/pack_metadata.json
  Packs/ReversingLabs_Titanium_Cloud/pack_metadata.json
  Packs/knowbe4Phisher/pack_metadata.json
  Packs/remedy_SR/pack_metadata.json
Labels: docs-approved

#21841 mp_packs_revamp_751-800
  Packs/HealthCheck/pack_metadata.json
  Packs/SlashNextPhishingIncidentResponse/pack_metadata.json
  Packs/SolarWinds/pack_metadata.json
  Packs/SophosCentral/pack_metadata.json
  Packs/SophosXGFirewall/pack_metadata.json
  Packs/SplunkCIMFields/pack_metadata.json
  Packs/SpringRCEs/pack_metadata.json
  Packs/StarterPack/pack_metadata.json
  Packs/StringifyArray/pack_metadata.json
  Packs/StripAccentMarksFromString/pack_metadata.json
  Packs/SymantecMSS/pack_metadata.json
  Packs/Symantec_Messaging_Gateway/pack_metadata.json
  Packs/Syslog/pack_metadata.json
  Packs/TAXIIServer/pack_metadata.json
  Packs/TIMCampaignTracking/pack_metadata.json
  Packs/TIM_Processing/pack_metadata.json
  Packs/TIM_SIEM/pack_metadata.json
  Packs/TeamManagement/pack_metadata.json
  Packs/Tenable_io/pack_metadata.json
Labels: docs-approved

#21742 Gmail Single User: new auth flow
  Packs/GmailSingleUser/Integrations/GmailSingleUser/GmailSingleUser.py
  Packs/GmailSingleUser/Integrations/GmailSingleUser/GmailSingleUser.yml
  Packs/GmailSingleUser/Integrations/GmailSingleUser/GmailSingleUser_description.md
  Packs/GmailSingleUser/Integrations/GmailSingleUser/GmailSingleUser_test.py
  Packs/GmailSingleUser/Integrations/GmailSingleUser/README.md
  Packs/GmailSingleUser/Integrations/GmailSingleUser/doc_imgs/auth-uris.png
  Packs/GmailSingleUser/Integrations/GmailSingleUser/doc_imgs/localhost-auth.png
  Packs/GmailSingleUser/Integrations/GmailSingleUser/doc_imgs/oproxy-auth.png
  Packs/GmailSingleUser/ReleaseNotes/1_3_0.md
  Packs/GmailSingleUser/pack_metadata.json
Labels: docs-approved

#21862 update tags/usecases/categories to 60 more packs
  Packs/CVE_2021_40444/pack_metadata.json
  Packs/CVE_2021_44228/pack_metadata.json
  Packs/CVE_2022_26134/pack_metadata.json
  Packs/CVE_2022_30190/pack_metadata.json
  Packs/CVE_2022_41040_and_CVE_2022_41082_-_ProxyNotShell/pack_metadata.json
  Packs/CVSS/pack_metadata.json
  Packs/CadoResponse/pack_metadata.json
  Packs/Campaign/pack_metadata.json
  Packs/CaseManagement-Generic/pack_metadata.json
  Packs/Centreon/pack_metadata.json
  Packs/Change_Management/pack_metadata.json
  Packs/CheckPhish/pack_metadata.json
  Packs/CheckPointDome9/pack_metadata.json
  Packs/CheckpointFirewall/pack_metadata.json
  Packs/CimTrak-SystemIntegrityAssurance/pack_metadata.json
  Packs/Cisco-umbrella-cloud-security/pack_metadata.json
  Packs/CiscoESAIronPortEmailAPI/pack_metadata.json
  Packs/CiscoEmailSecurity/pack_metadata.json
  Packs/CiscoWSA/pack_metadata.json
  Packs/CiscoWebExFeed/pack_metadata.json
  Packs/Clarizen/pack_metadata.json
Labels: docs-approved

#21226 Asm 082922
  Packs/CortexAttackSurfaceManagement/.secrets-ignore
  Packs/CortexAttackSurfaceManagement/Integrations/CortexAttackSurfaceManagement/CortexAttackSurfaceManagement.py
  Packs/CortexAttackSurfaceManagement/Integrations/CortexAttackSurfaceManagement/CortexAttackSurfaceManagement.yml
  Packs/CortexAttackSurfaceManagement/Integrations/CortexAttackSurfaceManagement/CortexAttackSurfaceManagement_description.md
  Packs/CortexAttackSurfaceManagement/Integrations/CortexAttackSurfaceManagement/CortexAttackSurfaceManagement_image.png
  Packs/CortexAttackSurfaceManagement/Integrations/CortexAttackSurfaceManagement/CortexAttackSurfaceManagement_test.py
  Packs/CortexAttackSurfaceManagement/Integrations/CortexAttackSurfaceManagement/Pipfile
  Packs/CortexAttackSurfaceManagement/Integrations/CortexAttackSurfaceManagement/Pipfile.lock
  Packs/CortexAttackSurfaceManagement/Integrations/CortexAttackSurfaceManagement/README.md
  Packs/CortexAttackSurfaceManagement/Integrations/CortexAttackSurfaceManagement/command_examples
  Packs/CortexAttackSurfaceManagement/Integrations/CortexAttackSurfaceManagement/test_data/expected_results.py
  Packs/CortexAttackSurfaceManagement/Integrations/CortexAttackSurfaceManagement/test_data/raw_response.py
  Packs/CortexAttackSurfaceManagement/README.md
  Packs/CortexAttackSurfaceManagement/ReleaseNotes/1_1_0.md
  Packs/CortexAttackSurfaceManagement/TestPlaybooks/playbook-CortexAttackSurfaceManagement_Test.yml
  Packs/CortexAttackSurfaceManagement/pack_metadata.json
  Tests/conf.json
Labels: Contribution, docs-approved, ready-for-instance-test, pending-demo, post-demo, Contribution Form Filled, Community, pending-contributor

#21797 Check API key against new endpoint in HatchingTriage integration
  Packs/HatchingTriage/Integrations/HatchingTriage/HatchingTriage.py
  Packs/HatchingTriage/Integrations/HatchingTriage/HatchingTriage.yml
  Packs/HatchingTriage/ReleaseNotes/1_0_7.md
  Packs/HatchingTriage/pack_metadata.json
Labels: Contribution, docs-approved, Partner, ready-for-instance-test, Contribution Form Filled, pending-contributor

#21867 Mp packs revamp 801 end
  Packs/BreachNotification-US/pack_metadata.json
  Packs/FeedThreatConnect/pack_metadata.json
  Packs/FeedTorExitAddresses/pack_metadata.json
  Packs/FeedURLhaus/pack_metadata.json
  Packs/FeedUnit42v2/pack_metadata.json
  Packs/FeedZoom/pack_metadata.json
  Packs/Iboss/pack_metadata.json
  Packs/PICUS/pack_metadata.json
  Packs/SafeNet_Trusted_Access/pack_metadata.json
  Packs/TheHiveProject/pack_metadata.json
  Packs/ThousandEyes/pack_metadata.json
  Packs/ThreatIntelReports/pack_metadata.json
  Packs/ThreatIntelligenceManagement/pack_metadata.json
  Packs/ThreatMiner/pack_metadata.json
  Packs/ThreatX/pack_metadata.json
  Packs/Tidy/pack_metadata.json
  Packs/TrendMicroCAS/pack_metadata.json
  Packs/TrendMicroVisionOne/pack_metadata.json
  Packs/Tripwire/pack_metadata.json
  Packs/TrustwaveSEG/pack_metadata.json
  Packs/TwitterIOCHunter-FullDailyFeed/pack_metadata.json
  Packs/UBIRCH/pack_metadata.json
  Packs/UnifiVideoNVR/pack_metadata.json
  Packs/UnisysStealth/pack_metadata.json
  Packs/UpdateEntriesBySearch/pack_metadata.json
  Packs/UrlScan/pack_metadata.json
  Packs/VMwareWorkspaceONEUEM/pack_metadata.json
  Packs/Vectra_AI/pack_metadata.json
  Packs/Verodin/pack_metadata.json
  Packs/Viper/pack_metadata.json
  Packs/VirusTotal/pack_metadata.json
  Packs/Volatility/pack_metadata.json
  Packs/WebScraper/pack_metadata.json
  Packs/WhatIsMyBrowser/pack_metadata.json
  Packs/WhisperGateCVE-2021-32648/pack_metadata.json
  Packs/Whois/pack_metadata.json
  Packs/WindowsDefenderAdvancedThreatProtection/pack_metadata.json
  Packs/WindowsForensics/pack_metadata.json
  Packs/Wiz/pack_metadata.json
  Packs/Workday/pack_metadata.json
  Packs/X509Certificate/pack_metadata.json
  Packs/XMCyber/pack_metadata.json
  Packs/XMatters/pack_metadata.json
  Packs/XSOARmirroring/pack_metadata.json
  Packs/Yara/pack_metadata.json
  Packs/Zabbix/pack_metadata.json
  Packs/ZeroTrustAnalyticsPlatform/pack_metadata.json
  Packs/mnemonicMDR/pack_metadata.json
Labels: docs-approved

#21876 fix pack tags
  Packs/FeedURLhaus/pack_metadata.json
  Packs/TIM_Processing/pack_metadata.json
  Packs/ThreatIntelligenceManagement/pack_metadata.json
  Packs/TwitterIOCHunter-FullDailyFeed/pack_metadata.json
Labels: docs-approved

#21835 Updating conf.json to include all integrations, test playbooks dependencies
  Tests/conf.json
Labels: docs-approved, release-notes-only

#21651 ReversingLabs TitaniumCloud 2.0.4
  Packs/ReversingLabs_A1000/Integrations/ReversingLabsA1000v2/ReversingLabsA1000v2.py
  Packs/ReversingLabs_A1000/Integrations/ReversingLabsA1000v2/ReversingLabsA1000v2.yml
  Packs/ReversingLabs_A1000/ReleaseNotes/2_0_6.md
  Packs/ReversingLabs_A1000/pack_metadata.json
  Packs/ReversingLabs_TitaniumScale/Integrations/ReversingLabsTitaniumScale/ReversingLabsTitaniumScale.py
  Packs/ReversingLabs_TitaniumScale/Integrations/ReversingLabsTitaniumScale/ReversingLabsTitaniumScale.yml
  Packs/ReversingLabs_TitaniumScale/ReleaseNotes/1_0_2.md
  Packs/ReversingLabs_TitaniumScale/pack_metadata.json
  Packs/ReversingLabs_Titanium_Cloud/Integrations/ReversingLabsTitaniumCloudv2/ReversingLabsTitaniumCloudv2.py
  Packs/ReversingLabs_Titanium_Cloud/Integrations/ReversingLabsTitaniumCloudv2/ReversingLabsTitaniumCloudv2.yml
  Packs/ReversingLabs_Titanium_Cloud/ReleaseNotes/2_0_4.md
  Packs/ReversingLabs_Titanium_Cloud/pack_metadata.json
Labels: Contribution, docs-approved, Partner, ready-for-instance-test, Contribution Form Filled, pending-contributor

#21828 Mp packs revamp 702 750
  Packs/FeedSOCRadarThreatFeed/pack_metadata.json
  Packs/PcapAnalysis/pack_metadata.json
  Packs/RubrikPolaris/pack_metadata.json
  Packs/Rundeck/pack_metadata.json
  Packs/SANS/pack_metadata.json
  Packs/SAP_IAM/pack_metadata.json
  Packs/SEKOIAIntelligenceCenter/pack_metadata.json
  Packs/SOCRadar/pack_metadata.json
  Packs/SafeBreach/pack_metadata.json
  Packs/SailPointIdentityIQ/pack_metadata.json
  Packs/SailPointIdentityNow/pack_metadata.json
  Packs/SalesforceFusion/pack_metadata.json
  Packs/ScheduleTaskAndPoll/pack_metadata.json
  Packs/SecBI/pack_metadata.json
  Packs/SecneurXThreatFeeds/pack_metadata.json
  Packs/SecureWorks/pack_metadata.json
  Packs/SecurityAdvisor/pack_metadata.json
  Packs/SecurityScorecard/pack_metadata.json
  Packs/SecurityTrails/pack_metadata.json
  Packs/ServerLogs/pack_metadata.json
  Packs/ServiceNow/pack_metadata.json
  Packs/ShadowIT/pack_metadata.json
  Packs/ShiftManagement-AssignToNextShift/pack_metadata.json
  Packs/ShiftManagement/pack_metadata.json
  Packs/Silverfort/pack_metadata.json
  Packs/Sixgill-Darkfeed/pack_metadata.json
  Packs/sampleSiem/pack_metadata.json
Labels: docs-approved

#21834 cSpell ignored words
  .devcontainer/devcontainer.json
Labels: docs-approved

#21290 Stix Parser Enchasement
  Packs/Base/.secrets-ignore
  Packs/Base/ReleaseNotes/1_31_28.md
  Packs/Base/Scripts/StixParser/README.md
  Packs/Base/Scripts/StixParser/StixParser.py
  Packs/Base/Scripts/StixParser/StixParser.yml
  Packs/Base/Scripts/StixParser/StixParser_test.py
  Packs/Base/Scripts/StixParser/TestData/little_stix2.json
  Packs/Base/Scripts/StixParser/TestData/little_stix2_results.json
  Packs/Base/Scripts/StixParser/TestData/missing_firstSeen.json
  Packs/Base/Scripts/StixParser/TestData/stix1/file-stix-ioc-results.json
  Packs/Base/Scripts/StixParser/TestData/stix1/ip-stix-ioc-results.json
  Packs/Base/Scripts/StixParser/TestData/stix1/url-stix-ioc-results.json
  Packs/Base/Scripts/StixParser/TestData/stix2_results.json
  Packs/Base/Scripts/StixParser/test_data/stix1_tests/STIX_Domain_Watchlist.xml
  Packs/Base/Scripts/StixParser/test_data/stix1_tests/STIX_Domain_Watchlist_result.json
  Packs/Base/Scripts/StixParser/test_data/stix1_tests/STIX_FileHash_Watchlist.xml
  Packs/Base/Scripts/StixParser/test_data/stix1_tests/STIX_FileHash_Watchlist_result.json
  Packs/Base/Scripts/StixParser/test_data/stix1_tests/STIX_Phishing_Indicator.xml
  Packs/Base/Scripts/StixParser/test_data/stix1_tests/STIX_Phishing_Indicator_result.json
  Packs/Base/Scripts/StixParser/test_data/stix1_tests/STIX_URL_Watchlist.xml
  Packs/Base/Scripts/StixParser/test_data/stix1_tests/STIX_URL_Watchlist_result.json
  Packs/Base/Scripts/StixParser/test_data/stix1_tests/collection_example.xml
  Packs/Base/Scripts/StixParser/test_data/stix1_tests/file-stix-ioc-results.json
  Packs/Base/Scripts/StixParser/test_data/stix1_tests/file-stix-ioc.xml
  Packs/Base/Scripts/StixParser/test_data/stix1_tests/indicators_example.json
  Packs/Base/Scripts/StixParser/test_data/stix1_tests/ip-stix-ioc-results.json
  Packs/Base/Scripts/StixParser/test_data/stix1_tests/ip-stix-ioc.xml
  Packs/Base/Scripts/StixParser/test_data/stix1_tests/url-stix-ioc-results.json
  Packs/Base/Scripts/StixParser/test_data/stix1_tests/url-stix-ioc.xml
  Packs/Base/Scripts/StixParser/test_data/stix2_tests/expected_result_example1.json
  Packs/Base/Scripts/StixParser/test_data/stix2_tests/expected_result_example2.json
  Packs/Base/Scripts/StixParser/test_data/stix2_tests/expected_result_example3.json
  Packs/Base/Scripts/StixParser/test_data/stix2_tests/expected_result_example4.json
  Packs/Base/Scripts/StixParser/test_data/stix2_tests/expected_result_example5.json
  Packs/Base/Scripts/StixParser/test_data/stix2_tests/expected_result_example6.json
  Packs/Base/Scripts/StixParser/test_data/stix2_tests/expected_result_example7.json
  Packs/Base/Scripts/StixParser/test_data/stix2_tests/expected_result_extension1.json
  Packs/Base/Scripts/StixParser/test_data/stix2_tests/expected_result_extension2.json
  Packs/Base/Scripts/StixParser/test_data/stix2_tests/stix2.json
  Packs/Base/Scripts/StixParser/test_data/stix2_tests/stix2_example1.json
  Packs/Base/Scripts/StixParser/test_data/stix2_tests/stix2_example2.json
  Packs/Base/Scripts/StixParser/test_data/stix2_tests/stix2_example3.json
  Packs/Base/Scripts/StixParser/test_data/stix2_tests/stix2_example4.json
  Packs/Base/Scripts/StixParser/test_data/stix2_tests/stix2_example5.json
  Packs/Base/Scripts/StixParser/test_data/stix2_tests/stix2_example6.json
  Packs/Base/Scripts/StixParser/test_data/stix2_tests/stix2_example7.json
  Packs/Base/Scripts/StixParser/test_data/stix2_tests/stix2_extension1.json
  Packs/Base/Scripts/StixParser/test_data/stix2_tests/stix2_extension2.json
  Packs/Base/Scripts/StixParser/test_data/stix2_tests/stix2_results.json
  Packs/Base/pack_metadata.json
  Packs/CommonScripts/ReleaseNotes/1_9_3.md
  Packs/CommonScripts/Scripts/CreateIndicatorsFromSTIX/CreateIndicatorsFromSTIX.py
  Packs/CommonScripts/Scripts/CreateIndicatorsFromSTIX/CreateIndicatorsFromSTIX.yml
  Packs/CommonScripts/Scripts/CreateIndicatorsFromSTIX/CreateIndicatorsFromSTIX_test.py
  Packs/CommonScripts/Scripts/CreateIndicatorsFromSTIX/README.md
  Packs/CommonScripts/Scripts/CreateIndicatorsFromSTIX/test_data/expected_result_example3.json
  Packs/CommonScripts/Scripts/CreateIndicatorsFromSTIX/test_data/stix2_example3.json
  Packs/CommonScripts/pack_metadata.json
  Tests/conf.json
Labels: docs-approved, ForceMerge

#21890 fix-tags-usecases-complaince
  Packs/Compliance/pack_metadata.json
Labels: docs-approved

#21264 ElasticSearch support regex was added
  Packs/Elasticsearch/Integrations/Elasticsearch_v2/Elasticsearch_v2.py
  Packs/Elasticsearch/Integrations/Elasticsearch_v2/Elasticsearch_v2.yml
  Packs/Elasticsearch/Integrations/Elasticsearch_v2/Elasticsearch_v2_test.py
  Packs/Elasticsearch/ReleaseNotes/1_3_4.md
  Packs/Elasticsearch/pack_metadata.json
Labels: docs-approved

#21636 Assign credentials appropriately allowing sshkey within GitHub integration
  Packs/GitHub/Integrations/GitHub/GitHub.py
  Packs/GitHub/Integrations/GitHub/GitHub.yml
  Packs/GitHub/Integrations/GitHub/README.md
  Packs/GitHub/ReleaseNotes/2_0_5.md
  Packs/GitHub/pack_metadata.json
Labels: Contribution, docs-approved, Contribution Form Filled, Community

#21881 Malware investigation and response fix
  Packs/MalwareInvestigationAndResponse/ReleaseNotes/2_0_1.md
  Packs/MalwareInvestigationAndResponse/Scripts/ReadNetstatFileWrapper/ReadNetstatFileWrapper.py
  Packs/MalwareInvestigationAndResponse/Scripts/ReadNetstatFileWrapper/ReadNetstatFileWrapper.yml
  Packs/MalwareInvestigationAndResponse/pack_metadata.json
Labels: docs-approved

#21829 Fix XDR close reason
  Packs/ApiModules/Scripts/CoreIRApiModule/CoreIRApiModule.py
  Packs/ApiModules/Scripts/CoreIRApiModule/CoreIRApiModule_test.py
  Packs/Core/ReleaseNotes/1_3_13.md
  Packs/Core/pack_metadata.json
  Packs/CortexXDR/Classifiers/classifier-mapper-outgoing-PaloAltoNetworks_CortexXDR.json
  Packs/CortexXDR/Integrations/CortexXDRIR/CortexXDRIR.py
  Packs/CortexXDR/Integrations/CortexXDRIR/CortexXDRIR.yml
  Packs/CortexXDR/Integrations/CortexXDRIR/CortexXDRIR_test.py
  Packs/CortexXDR/ReleaseNotes/4_8_23.md
  Packs/CortexXDR/pack_metadata.json
Labels: docs-approved, release-notes-only

#21864 Add approved_categories file
  .github/CODEOWNERS
  Tests/Marketplace/approved_categories.json
Labels: docs-approved, ForceMerge

#21880 Slack Block Builder fixes
  Packs/Slack/Integrations/SlackV3/SlackV3.py
  Packs/Slack/Integrations/SlackV3/SlackV3.yml
  Packs/Slack/ReleaseNotes/3_1_8.md
  Packs/Slack/Scripts/SlackBlockBuilder/SlackBlockBuilder.py
  Packs/Slack/Scripts/SlackBlockBuilder/SlackBlockBuilder.yml
  Packs/Slack/pack_metadata.json
Labels: docs-approved

#21754 Signal science fix
  Packs/SignalSciences/Integrations/SignalSciences/SignalSciences.py
  Packs/SignalSciences/Integrations/SignalSciences/SignalSciences.yml
  Packs/SignalSciences/ReleaseNotes/1_0_12.md
  Packs/SignalSciences/pack_metadata.json
Labels: bug, docs-approved, release-notes-only

#21886 ListUsedDockerImages support in custom dockerImages
  Packs/CommonScripts/ReleaseNotes/1_9_4.md
  Packs/CommonScripts/Scripts/ListUsedDockerImages/ListUsedDockerImages.py
  Packs/CommonScripts/Scripts/ListUsedDockerImages/ListUsedDockerImages.yml
  Packs/CommonScripts/Scripts/ListUsedDockerImages/ListUsedDockerImages_test.py
  Packs/CommonScripts/pack_metadata.json
Labels: docs-approved

#21883 Omri rbr
  Packs/CVE_2021_40444/Playbooks/playbook-CVE-2021-40444_-_MSHTML_RCE.yml
  Packs/CVE_2021_40444/Playbooks/playbook-CVE-2021-40444_-_MSHTML_RCE_README.md
  Packs/CVE_2021_40444/ReleaseNotes/1_0_3.md
  Packs/CVE_2021_40444/pack_metadata.json
  Packs/CVE_2021_44228/Playbooks/playbook-CVE-2021-44228_-_Log4j_RCE.yml
  Packs/CVE_2021_44228/Playbooks/playbook-CVE-2021-44228_-_Log4j_RCE_README.md
  Packs/CVE_2021_44228/ReleaseNotes/1_0_12.md
  Packs/CVE_2021_44228/pack_metadata.json
  Packs/CVE_2022_26134/Playbooks/playbook-CVE-2022-26134_-_Confluence_RCE.yml
  Packs/CVE_2022_26134/Playbooks/playbook-CVE-2022-26134_-_Confluence_RCE_README.md
  Packs/CVE_2022_26134/ReleaseNotes/1_0_1.md
  Packs/CVE_2022_26134/pack_metadata.json
  Packs/CVE_2022_30190/Playbooks/playbook-CVE-2022-30190_-_MSDT_RCE.yml
  Packs/CVE_2022_30190/Playbooks/playbook-CVE-2022-30190_-_MSDT_RCE_README.md
  Packs/CVE_2022_30190/ReleaseNotes/1_0_3.md
  Packs/CVE_2022_30190/doc_files/CVE-2022-30190_-_MSDT_RCE.png
  Packs/CVE_2022_30190/pack_metadata.json
Labels: docs-approved

#21898 GridFieldSetup Automation
  Packs/CommonScripts/ReleaseNotes/1_10_0.md
  Packs/CommonScripts/ReleaseNotes/1_9_2.md
  Packs/CommonScripts/Scripts/GridFieldSetup/GridFieldSetup.py
  Packs/CommonScripts/Scripts/GridFieldSetup/GridFieldSetup.yml
  Packs/CommonScripts/Scripts/GridFieldSetup/GridFieldSetup_test.py
  Packs/CommonScripts/Scripts/GridFieldSetup/README.md
  Packs/CommonScripts/Scripts/GridFieldSetup/command_examples.txt
  Packs/CommonScripts/TestPlaybooks/playbook-GridFieldSetup_Test.yml
  Tests/conf.json
Labels: Contribution, docs-approved

#21379 TaegisXDR - Add support for comments
  Packs/SecureWorks/Integrations/TaegisXDR/README.md
  Packs/SecureWorks/Integrations/TaegisXDR/TaegisXDR.py
  Packs/SecureWorks/Integrations/TaegisXDR/TaegisXDR.yml
  Packs/SecureWorks/Integrations/TaegisXDR/TaegisXDR_test.py
  Packs/SecureWorks/Integrations/TaegisXDR/command_examples
  Packs/SecureWorks/Integrations/TaegisXDR/test_data/data.py
  Packs/SecureWorks/ReleaseNotes/4_1_0.md
  Packs/SecureWorks/pack_metadata.json
Labels: Contribution, docs-approved, Partner, ready-for-instance-test, Contribution Form Filled, pending-contributor

#21885 improve SplunkPy integration doc
  Packs/SplunkPy/Integrations/SplunkPy/README.md
  Packs/SplunkPy/Integrations/SplunkPy/SplunkPy.yml
  Packs/SplunkPy/ReleaseNotes/2_4_16.md
  Packs/SplunkPy/pack_metadata.json
Labels: docs-approved

#21263 Bitbucket New Integration
  Packs/Bitbucket/.pack-ignore
  Packs/Bitbucket/.secrets-ignore
  Packs/Bitbucket/Integrations/Bitbucket/Bitbucket.py
  Packs/Bitbucket/Integrations/Bitbucket/Bitbucket.yml
  Packs/Bitbucket/Integrations/Bitbucket/Bitbucket_description.md
  Packs/Bitbucket/Integrations/Bitbucket/Bitbucket_image.png
  Packs/Bitbucket/Integrations/Bitbucket/Bitbucket_test.py
  Packs/Bitbucket/Integrations/Bitbucket/Pipfile
  Packs/Bitbucket/Integrations/Bitbucket/Pipfile.lock
  Packs/Bitbucket/Integrations/Bitbucket/README.md
  Packs/Bitbucket/Integrations/Bitbucket/command_examples
  Packs/Bitbucket/Integrations/Bitbucket/test_data/commands_test_data.json
  Packs/Bitbucket/README.md
  Packs/Bitbucket/TestPlaybooks/playbook-Test_Bitbucket.yml
  Packs/Bitbucket/pack_metadata.json
  Tests/conf.json
Labels: docs-approved

#21868 Fixes to the extraction of XDR instance domain/URL
  Packs/CortexXDR/Playbooks/Cortex_XDR_incident_handling_v3.yml
  Packs/CortexXDR/Playbooks/Cortex_XDR_incident_handling_v3_README.md
  Packs/CortexXDR/ReleaseNotes/4_8_24.md
  Packs/CortexXDR/pack_metadata.json
Labels: docs-approved

#21904 Omrii msdt new
  Packs/CVE_2022_30190/Playbooks/playbook-CVE-2022-30190_-_MSDT_RCE.yml
  Packs/CVE_2022_30190/Playbooks/playbook-CVE-2022-30190_-_MSDT_RCE_README.md
  Packs/CVE_2022_30190/ReleaseNotes/1_0_4.md
  Packs/CVE_2022_30190/pack_metadata.json
Labels: docs-approved

#21709 Microsoft cas docs fix
  Packs/MicrosoftCloudAppSecurity/Integrations/MicrosoftCloudAppSecurity/MicrosoftCloudAppSecurity.yml
  Packs/MicrosoftCloudAppSecurity/Integrations/MicrosoftCloudAppSecurity/MicrosoftCloudAppSecurity_description.md
  Packs/MicrosoftCloudAppSecurity/Integrations/MicrosoftCloudAppSecurity/README.md
  Packs/MicrosoftCloudAppSecurity/ReleaseNotes/2_1_3.md
  Packs/MicrosoftCloudAppSecurity/pack_metadata.json
Labels: bug, docs-approved

#21900 bug fix get_private_build_status
  Utils/get_private_build_status.py
Labels: docs-approved

#21887 fix code owner - upload
  .github/CODEOWNERS
Labels: docs-approved

#21873 fix broken image in pdf report
  Packs/Base/ReleaseNotes/1_31_29.md
  Packs/Base/Scripts/CommonServerPython/CommonServerPython.py
  Packs/Base/Scripts/CommonServerPython/CommonServerPython_test.py
  Packs/Base/Scripts/SanePdfReport/SanePdfReport.py
  Packs/Base/Scripts/SanePdfReport/SanePdfReport.yml
  Packs/Base/Scripts/SanePdfReport/SanePdfReport_test.py
  Packs/Base/pack_metadata.json
Labels: docs-approved

#20900 Joe security v2
  Packs/CommonDashboards/Dashboards/dashboard-APIExecutionMetrics.json
  Packs/CommonDashboards/ReleaseNotes/1_2_3.md
  Packs/CommonDashboards/pack_metadata.json
  Packs/JoeSecurity/.pack-ignore
  Packs/JoeSecurity/Integrations/JoeSecurityV2/JoeSecurityV2.py
  Packs/JoeSecurity/Integrations/JoeSecurityV2/JoeSecurityV2.yml
  Packs/JoeSecurity/Integrations/JoeSecurityV2/JoeSecurityV2_description.md
  Packs/JoeSecurity/Integrations/JoeSecurityV2/JoeSecurityV2_image.png
  Packs/JoeSecurity/Integrations/JoeSecurityV2/JoeSecurityV2_test.py
  Packs/JoeSecurity/Integrations/JoeSecurityV2/Pipfile
  Packs/JoeSecurity/Integrations/JoeSecurityV2/Pipfile.lock
  Packs/JoeSecurity/Integrations/JoeSecurityV2/README.md
  Packs/JoeSecurity/Integrations/JoeSecurityV2/command_examples
  Packs/JoeSecurity/Integrations/JoeSecurityV2/test_data/list_analysis_expected_output.json
  Packs/JoeSecurity/Integrations/JoeSecurityV2/test_data/list_analysis_raw_response.json
  Packs/JoeSecurity/ReleaseNotes/1_0_12.md
  Packs/JoeSecurity/TestPlaybooks/testplaybook-_JoeSecuirtyV2.yml
  Packs/JoeSecurity/Widgets/Widget-API_Call_Results_for_Joe_Security.json
  Packs/JoeSecurity/pack_metadata.json
  Tests/conf.json
Labels: docs-approved

#21905 Kmsat modelingrules hotfix
  Packs/KnowBe4_KMSAT/ModelingRules/KnowBe4KMSATEventCollector/KnowBe4KMSATEventCollector_schema.json
  Packs/KnowBe4_KMSAT/ReleaseNotes/1_0_2.md
  Packs/KnowBe4_KMSAT/pack_metadata.json
Labels: docs-approved

#21937 Omri msdt rce
  Packs/CVE_2022_30190/Playbooks/playbook-CVE-2022-30190_-_MSDT_RCE.yml
  Packs/CVE_2022_30190/Playbooks/playbook-CVE-2022-30190_-_MSDT_RCE_README.md
  Packs/CVE_2022_30190/ReleaseNotes/1_0_5.md
  Packs/CVE_2022_30190/pack_metadata.json
Labels: docs-approved

#20940 Sandbox generic enrichment - adding support for Joe Sandbox
  Packs/CommonPlaybooks/Playbooks/playbook-Detonate_and_Analyze_File_-_Generic.yml
  Packs/CommonPlaybooks/Playbooks/playbook-Detonate_and_Analyze_File_-_Generic_README.md
  Packs/CommonPlaybooks/Playbooks/playbook-Search_For_Hash_In_Sandbox_-_Generic.yml
  Packs/CommonPlaybooks/Playbooks/playbook-Search_For_Hash_In_Sandbox_-_Generic_README.md
  Packs/CommonPlaybooks/ReleaseNotes/2_3_7.md
  Packs/CommonPlaybooks/doc_files/Detonate_and_Analyze_File_-_Generic.png
  Packs/CommonPlaybooks/doc_files/Search_For_Hash_In_Sandbox_-_Generic.png
  Packs/CommonPlaybooks/pack_metadata.json
  Packs/JoeSecurity/Playbooks/playbook-Detonate_and_Analyze_File_-_JoeSecurity.yml
  Packs/JoeSecurity/Playbooks/playbook-Detonate_and_Analyze_File_-_JoeSecurity_README.md
  Packs/JoeSecurity/ReleaseNotes/1_1_0.md
  Packs/JoeSecurity/doc_files/Detonate_and_Analyze_File_-_JoeSecurity.png
  Packs/JoeSecurity/pack_metadata.json
Labels: docs-approved
