Repository demisto/content, pull requests merged in 2023-01, with the labels that each got.

#23098 Tanium threat response v2 fetch fix
  Packs/TaniumThreatResponse/.pack-ignore
  Packs/TaniumThreatResponse/Integrations/TaniumThreatResponseV2/TaniumThreatResponseV2.py
  Packs/TaniumThreatResponse/Integrations/TaniumThreatResponseV2/TaniumThreatResponseV2.yml
  Packs/TaniumThreatResponse/Integrations/TaniumThreatResponseV2/TaniumThreatResponseV2_test.py
  Packs/TaniumThreatResponse/ReleaseNotes/2_1_3.md
  Packs/TaniumThreatResponse/pack_metadata.json
Labels: docs-approved

#23394 Circl to py3
  Packs/CIRCL/Integrations/CIRCL/CIRCL.py
  Packs/CIRCL/Integrations/CIRCL/CIRCL.yml
  Packs/CIRCL/ReleaseNotes/1_0_8.md
  Packs/CIRCL/pack_metadata.json
  Tests/conf.json
Labels: docs-approved

#23393 Fix Sixgill deprecation
  Packs/Sixgill-Darkfeed/Integrations/SixgillDVEFeed/SixgillDVEFeed.py
  Packs/Sixgill-Darkfeed/Integrations/SixgillDVEFeed/SixgillDVEFeed.yml
  Packs/Sixgill-Darkfeed/ReleaseNotes/2_0_13.md
  Packs/Sixgill-Darkfeed/pack_metadata.json
Labels: docs-approved

#23424 Deprecate demisto leave all investigations
  Packs/DemistoRESTAPI/ReleaseNotes/1_3_7.md
  Packs/DemistoRESTAPI/Scripts/DemistoLeaveAllInvestigations/DemistoLeaveAllInvestigations.yml
  Packs/DemistoRESTAPI/pack_metadata.json
Labels: docs-approved

#23367 Opencti doc update
  Packs/FeedOpenCTI/Integrations/FeedOpenCTI_v4/FeedOpenCTI_v4.yml
  Packs/FeedOpenCTI/README.md
  Packs/FeedOpenCTI/ReleaseNotes/2_0_11.md
  Packs/FeedOpenCTI/pack_metadata.json
  Packs/OpenCTI/Integrations/OpenCTI/OpenCTI.yml
  Packs/OpenCTI/ReleaseNotes/1_0_6.md
  Packs/OpenCTI/pack_metadata.json
  Tests/conf.json
Labels: docs-approved

#23369 Deprecate DemistoGetIncidentTasksByState
  Packs/DemistoRESTAPI/ReleaseNotes/1_3_8.md
  Packs/DemistoRESTAPI/Scripts/DemistoGetIncidentTasksByState/DemistoGetIncidentTasksByState.yml
  Packs/DemistoRESTAPI/pack_metadata.json
Labels: docs-approved

#23398 FuardiCore added an example of the url with the suffix
  Packs/GuardiCore/Integrations/GuardiCoreV2/GuardiCoreV2.py
  Packs/GuardiCore/Integrations/GuardiCoreV2/GuardiCoreV2.yml
  Packs/GuardiCore/Integrations/GuardiCoreV2/README.md
  Packs/GuardiCore/ReleaseNotes/2_0_6.md
  Packs/GuardiCore/pack_metadata.json
Labels: docs-approved

#23425 Deprecate demisto link incidents
  Packs/DemistoRESTAPI/ReleaseNotes/1_3_9.md
  Packs/DemistoRESTAPI/Scripts/DemistoLinkIncidents/DemistoLinkIncidents.yml
  Packs/DemistoRESTAPI/pack_metadata.json
Labels: docs-approved

#23430 fix PAN-OS URL Filtering enrichment - Test test-playbook
  Packs/PAN-OS/.secrets-ignore
  Packs/PAN-OS/TestPlaybooks/playbook-PAN-OS_-_URL_FIltering_Enrichment-Test.yml
Labels: docs-approved

#23381 Fixed Data Model Names
  Packs/DelineaSS/ModelingRules/DelineaSS_1_3/DelineaSS_1_3.xif
  Packs/DelineaSS/ModelingRules/DelineaSS_1_3/DelineaSS_1_3_schema.json
  Packs/DelineaSS/README.md
  Packs/DelineaSS/ReleaseNotes/2_0_1.md
  Packs/DelineaSS/pack_metadata.json
  Packs/JuniperSRX/ModelingRules/JuniperSRX_1_3/JuniperSRX_1_3.xif
  Packs/JuniperSRX/ModelingRules/JuniperSRX_1_3/JuniperSRX_1_3_schema.json
  Packs/JuniperSRX/README.md
  Packs/JuniperSRX/ReleaseNotes/1_0_6.md
  Packs/JuniperSRX/pack_metadata.json
  Packs/Tableau/ModelingRules/Tableau_1_3/Tableau_1_3.xif
  Packs/Tableau/ModelingRules/Tableau_1_3/Tableau_1_3_schema.json
  Packs/Tableau/ReleaseNotes/1_0_6.md
  Packs/Tableau/pack_metadata.json
Labels: docs-approved

#23386 Microsoft graph security filter office365 doesn't work
  Packs/MicrosoftGraphSecurity/Integrations/MicrosoftGraphSecurity/MicrosoftGraphSecurity.py
  Packs/MicrosoftGraphSecurity/Integrations/MicrosoftGraphSecurity/MicrosoftGraphSecurity.yml
  Packs/MicrosoftGraphSecurity/Integrations/MicrosoftGraphSecurity/MicrosoftGraphSecurity_test.py
  Packs/MicrosoftGraphSecurity/Integrations/MicrosoftGraphSecurity/README.md
  Packs/MicrosoftGraphSecurity/ReleaseNotes/2_1_9.md
  Packs/MicrosoftGraphSecurity/pack_metadata.json
Labels: docs-approved

#23426 Deprecate demisto logs bundle
  Packs/DemistoRESTAPI/ReleaseNotes/1_3_10.md
  Packs/DemistoRESTAPI/Scripts/DemistoLogsBundle/DemistoLogsBundle.yml
  Packs/DemistoRESTAPI/pack_metadata.json
Labels: docs-approved

#23435 switched the url t look for
  Packs/URLHaus/Integrations/URLHaus/URLHaus.py
  Packs/URLHaus/Integrations/URLHaus/URLHaus.yml
  Packs/URLHaus/Integrations/URLHaus/URLHaus_test.py
  Packs/URLHaus/ReleaseNotes/1_0_17.md
  Packs/URLHaus/TestPlaybooks/playbook-Test-URLhaus.yml
  Packs/URLHaus/pack_metadata.json
Labels: docs-approved

#23307 Citrix ADC Modeling Rules
  Packs/CitrixADC/.pack-ignore
  Packs/CitrixADC/.secrets-ignore
  Packs/CitrixADC/ModelingRules/CitrixADC_1_3/CitrixADC_1_3.xif
  Packs/CitrixADC/ModelingRules/CitrixADC_1_3/CitrixADC_1_3.yml
  Packs/CitrixADC/ModelingRules/CitrixADC_1_3/CitrixADC_1_3_schema.json
  Packs/CitrixADC/ParsingRules/CitrixADC_1_3/CitrixADC_1_3.xif
  Packs/CitrixADC/ParsingRules/CitrixADC_1_3/CitrixADC_1_3.yml
  Packs/CitrixADC/README.md
  Packs/CitrixADC/doc_imgs/citrixadc1.png
  Packs/CitrixADC/doc_imgs/citrixadc2.png
  Packs/CitrixADC/pack_metadata.json
Labels: docs-approved

#23427 Deprecate demisto send invite
  Packs/DemistoRESTAPI/ReleaseNotes/1_3_11.md
  Packs/DemistoRESTAPI/Scripts/DemistoSendInvite/DemistoSendInvite.yml
  Packs/DemistoRESTAPI/pack_metadata.json
Labels: docs-approved

#22660 adding new upn param
  Packs/EWS/.pack-ignore
  Packs/EWS/Integrations/EWSO365/EWSO365.py
  Packs/EWS/Integrations/EWSO365/EWSO365.yml
  Packs/EWS/Integrations/EWSO365/README.md
  Packs/EWS/ReleaseNotes/2_0_7.md
  Packs/EWS/pack_metadata.json
Labels: docs-approved

#22735 PAN-OS Fetch Incidents Enhancement
  Packs/PAN-OS/Classifiers/classifier-Panorama_Classifier.json
  Packs/PAN-OS/Classifiers/classifier-Panorama_Mapper.json
  Packs/PAN-OS/Integrations/Panorama/Panorama.py
  Packs/PAN-OS/Integrations/Panorama/Panorama.yml
  Packs/PAN-OS/Integrations/Panorama/Panorama_description.md
  Packs/PAN-OS/Integrations/Panorama/Panorama_test.py
  Packs/PAN-OS/Integrations/Panorama/README.md
  Packs/PAN-OS/Integrations/Panorama/test_data/fetch_incidents_input.py
  Packs/PAN-OS/ReleaseNotes/1_16_0.md
  Packs/PAN-OS/pack_metadata.json
Labels: docs-approved

#23450 Added "No instance" to "skipped_tests"
  Tests/conf.json
Labels: docs-approved

#23388 New Software indicator, fields and layout
  Packs/CommonTypes/.pack-ignore
  Packs/CommonTypes/IndicatorFields/indicatorfield-Languages.json
  Packs/CommonTypes/IndicatorFields/indicatorfield-Vendor.json
  Packs/CommonTypes/IndicatorFields/indicatorfield-Version.json
  Packs/CommonTypes/IndicatorFields/indicatorfield-cpe.json
  Packs/CommonTypes/IndicatorFields/indicatorfield-swid.json
  Packs/CommonTypes/IndicatorTypes/reputation-Software.json
  Packs/CommonTypes/Layouts/layoutscontainer-Software.json
  Packs/CommonTypes/ReleaseNotes/3_3_41.md
  Packs/CommonTypes/pack_metadata.json
Labels: docs-approved

#23436 Content items fixes
  Packs/AutoFocus/Integrations/FeedAutofocus/command_examples.txt
  Packs/AzureActiveDirectory/Integrations/AzureADIdentityProtection/command_examples.txt
  Packs/FidelisEndpoint/.pack-ignore
  Packs/FidelisEndpoint/Integrations/FidelisEndpoint/FidelisEndpoint.py
  Packs/FidelisEndpoint/Integrations/FidelisEndpoint/FidelisEndpoint.yml
  Packs/FidelisEndpoint/Integrations/FidelisEndpoint/command_examples.txt
  Packs/FidelisEndpoint/ReleaseNotes/1_0_4.md
  Packs/FidelisEndpoint/pack_metadata.json
  Packs/Ironscales/Integrations/Ironscales/package.json
  Packs/MongoDB/Integrations/MongoDBKeyValueStore/command_examples.txt
  Packs/MongoDB/Integrations/MongoDBLog/command_examples.txt
  Packs/VirusTotal/Integrations/VirusTotalV3/command_examples.txt
Labels: docs-approved

#22877 Adding GCP Enrichment and Remediation playbooks
  Packs/GCP-Enrichment-Remediation/Playbooks/GCP_-_Enrichment.yml
  Packs/GCP-Enrichment-Remediation/Playbooks/GCP_-_Enrichment_README.md
  Packs/GCP-Enrichment-Remediation/Playbooks/GCP_-_Firewall_Remediation.yml
  Packs/GCP-Enrichment-Remediation/Playbooks/GCP_-_Firewall_Remediation_README.md
  Packs/GCP-Enrichment-Remediation/README.md
  Packs/GCP-Enrichment-Remediation/ReleaseNotes/1_1_0.md
  Packs/GCP-Enrichment-Remediation/doc_files/GCP_-_Enrichment.png
  Packs/GCP-Enrichment-Remediation/doc_files/GCP_-_Firewall_Remediation.png
  Packs/GCP-Enrichment-Remediation/pack_metadata.json
Labels: Contribution, Contribution Form Filled, Community

#23383 Rasterize comment
  Packs/rasterize/Integrations/rasterize/rasterize.py
  Packs/rasterize/Integrations/rasterize/rasterize.yml
  Packs/rasterize/ReleaseNotes/1_2_13.md
  Packs/rasterize/pack_metadata.json
Labels: docs-approved

#23368 bug - TIR is not read-only to all after publish
  Packs/ThreatIntelReports/ReleaseNotes/1_0_7.md
  Packs/ThreatIntelReports/Scripts/PublishThreatIntelReport/PublishThreatIntelReport.py
  Packs/ThreatIntelReports/Scripts/PublishThreatIntelReport/PublishThreatIntelReport.yml
  Packs/ThreatIntelReports/Scripts/PublishThreatIntelReport/README.md
  Packs/ThreatIntelReports/Scripts/UnpublishThreatIntelReport/README.md
  Packs/ThreatIntelReports/Scripts/UnpublishThreatIntelReport/UnpublishThreatIntelReport.yml
  Packs/ThreatIntelReports/TestPlaybooks/Threat_Intel_Report_test.yml
  Packs/ThreatIntelReports/pack_metadata.json
  Tests/conf.json
Labels: docs-approved

#23439 added a license description
  Packs/AzureSecurityCenter/README.md
  Packs/Microsoft365Defender/README.md
  Packs/MicrosoftDefenderAdvancedThreatProtection/README.md
Labels: docs-approved

#23475 Jamf modify modeling rule
  Packs/jamf/ModelingRules/Jamf_1_3/Jamf_1_3.xif
  Packs/jamf/ReleaseNotes/2_1_11.md
  Packs/jamf/pack_metadata.json
Labels: docs-approved

#21644 Adding updated EclecticIQ extensions
  Packs/EclecticIQ/.secrets-ignore
  Packs/EclecticIQ/Author_image.png
  Packs/EclecticIQ/Integrations/EclecticIQv2/EclecticIQv2.py
  Packs/EclecticIQ/Integrations/EclecticIQv2/EclecticIQv2.yml
  Packs/EclecticIQ/Integrations/EclecticIQv2/EclecticIQv2_description.md
  Packs/EclecticIQ/Integrations/EclecticIQv2/EclecticIQv2_image.png
  Packs/EclecticIQ/Integrations/EclecticIQv2/EclecticIQv2_test.py
  Packs/EclecticIQ/Integrations/EclecticIQv2/README.md
  Packs/EclecticIQ/Integrations/EclecticIQv2/command_examples
  Packs/EclecticIQ/README.md
  Packs/EclecticIQ/ReleaseNotes/2_0_0.md
  Packs/EclecticIQ/TestPlaybooks/playbook-EclecticIQTestv2.yml
  Packs/EclecticIQ/pack_metadata.json
Labels: Contribution, docs-approved, Partner, pending-demo, Contribution Form Filled

#23472 changing value of cs-falcon-device-count-ioc test playbook command
  Packs/CrowdStrikeFalcon/Integrations/CrowdStrikeFalcon/CrowdStrikeFalcon.yml
  Packs/CrowdStrikeFalcon/ReleaseNotes/1_10_1.md
  Packs/CrowdStrikeFalcon/TestPlaybooks/playbook-CrowdStrikeFalcon-Test.yml
  Packs/CrowdStrikeFalcon/pack_metadata.json
Labels: docs-approved

#23018 [ASM] expandr-1587
  Packs/CortexAttackSurfaceManagement/Playbooks/Cortex_ASM_-_ASM_Alert.yml
  Packs/CortexAttackSurfaceManagement/Playbooks/Cortex_ASM_-_ASM_Alert_README.md
  Packs/CortexAttackSurfaceManagement/Playbooks/Cortex_ASM_-_Detect_Service.yml
  Packs/CortexAttackSurfaceManagement/Playbooks/Cortex_ASM_-_Tenable.io_Enrichment.yml
  Packs/CortexAttackSurfaceManagement/README.md
  Packs/CortexAttackSurfaceManagement/ReleaseNotes/1_3_1.md
  Packs/CortexAttackSurfaceManagement/doc_files/Cortex_ASM_-_Tenable.io_Enrichment.png
  Packs/CortexAttackSurfaceManagement/pack_metadata.json
Labels: Contribution, Contribution Form Filled, Community

#23461 ignore
  Packs/AWS-NetworkFirewall/Integrations/AWS-NetworkFirewall/AWS-NetworkFirewall-config.json
  Packs/ArcherRSA/.pack-ignore
  Packs/Box/.pack-ignore
  Packs/Censys/.pack-ignore
  Packs/Expanse/.pack-ignore
  Packs/LogRhythm/.pack-ignore
  Packs/Malwr/.pack-ignore
  Packs/PolySwarm/.pack-ignore
  Packs/iDefense/.pack-ignore
  Packs/illuminate/.pack-ignore
  Packs/jamf/.pack-ignore
Labels: docs-approved

#23446 Content items validate fixes
  Packs/Anomali_ThreatStream/.pack-ignore
  Packs/Blockade.io/.pack-ignore
  Packs/CheckpointFirewall/.pack-ignore
  Packs/CiscoEmailSecurity/Integrations/CiscoEmailSecurity/CiscoEmailSecurity_test.py
  Packs/CiscoEmailSecurity/Integrations/CiscoEmailSecurity/test_data/test_data.json
  Packs/CofenseTriage/.pack-ignore
  Packs/CrowdStrikeHost/.pack-ignore
  Packs/CrowdStrikeIntel/.pack-ignore
  Packs/DeprecatedContent/.pack-ignore
  Packs/FeedCrowdstrikeFalconIntel/Integrations/FeedCrowdstrikeFalconIntel/FeedCrowdstrikeFalconIntel_test.py
  Packs/FeedCrowdstrikeFalconIntel/Integrations/FeedCrowdstrikeFalconIntel/test_data/test_data.json
  Packs/FeedGCPWhitelist/.pack-ignore
  Packs/FeedIntel471/.pack-ignore
  Packs/GoogleSafeBrowsing/.pack-ignore
  Packs/IronPort/.pack-ignore
  Packs/McAfee_ESM-v10/.pack-ignore
  Packs/Stealthwatch_Cloud/Integrations/Stealthwatch_Cloud/Stealthwatch_Cloud.py
  Packs/Stealthwatch_Cloud/Integrations/Stealthwatch_Cloud/Stealthwatch_Cloud.yml
  Packs/Stealthwatch_Cloud/Integrations/Stealthwatch_Cloud/Stealthwatch_Cloud_test.py
  Packs/Stealthwatch_Cloud/Integrations/Stealthwatch_Cloud/test_data/test_data.json
  Packs/Stealthwatch_Cloud/ReleaseNotes/1_0_11.md
  Packs/Stealthwatch_Cloud/pack_metadata.json
  Packs/ThreatConnect/.pack-ignore
  Packs/Threat_Crowd/.pack-ignore
  Packs/XForceExchange/.pack-ignore
  Packs/epo/.pack-ignore
Labels: docs-approved

#23463 add skipped tests
  Tests/conf.json
Labels: docs-approved

#23505 pan-os fetch incidents sdk bug
  Packs/PAN-OS/Integrations/Panorama/Panorama_test.py
  Packs/PAN-OS/Integrations/Panorama/test_data/fetch_incidents_input.py
Labels: docs-approved

#23444 CrowdStrike Falcon X - Fix TPBs
  Packs/CrowdStrikeFalconX/Integrations/CrowdStrikeFalconX/CrowdStrikeFalconX.py
  Packs/CrowdStrikeFalconX/Integrations/CrowdStrikeFalconX/CrowdStrikeFalconX.yml
  Packs/CrowdStrikeFalconX/ReleaseNotes/1_2_16.md
  Packs/CrowdStrikeFalconX/pack_metadata.json
  Tests/conf.json
Labels: docs-approved, release-notes-only

#23390 Microsoft Cloud App Security
  Packs/Microsoft365Defender/ParsingRules/Microsoft365Defender/Microsoft365Defender.yml
  Packs/MicrosoftCloudAppSecurity/ModelingRules/MicrosoftCloudAppSecurity_1_3/MicrosoftCloudAppSecurity_1_3.xif
  Packs/MicrosoftCloudAppSecurity/ModelingRules/MicrosoftCloudAppSecurity_1_3/MicrosoftCloudAppSecurity_1_3.yml
  Packs/MicrosoftCloudAppSecurity/ModelingRules/MicrosoftCloudAppSecurity_1_3/MicrosoftCloudAppSecurity_1_3_schema.json
  Packs/MicrosoftCloudAppSecurity/ParsingRules/MicrosoftCloudAppSecurity/MicrosoftCloudAppSecurity.xif
  Packs/MicrosoftCloudAppSecurity/ParsingRules/MicrosoftCloudAppSecurity/MicrosoftCloudAppSecurity.yml
  Packs/MicrosoftCloudAppSecurity/README.md
  Packs/MicrosoftCloudAppSecurity/ReleaseNotes/2_1_11.md
  Packs/MicrosoftCloudAppSecurity/pack_metadata.json
  Packs/MicrosoftDefenderAdvancedThreatProtection/ParsingRules/MicrosoftDefenderAdvancedThreatProtection/MicrosoftDefenderAdvancedThreatProtection.xif
  Packs/MicrosoftDefenderAdvancedThreatProtection/ParsingRules/MicrosoftDefenderAdvancedThreatProtection/MicrosoftDefenderAdvancedThreatProtection.yml
  Packs/MicrosoftDefenderAdvancedThreatProtection/ReleaseNotes/1_15_2.md
  Packs/MicrosoftDefenderAdvancedThreatProtection/pack_metadata.json
Labels: docs-approved, ForceMerge

#23206 Adding new github action
  .github/workflows/auto-merge-dockers.yml
  Tests/secrets_white_list.json
Labels: docs-approved, docker-image-auto-update

#23526 sdk 1.8.2
  .gitlab/ci/bucket-upload.yml
  .gitlab/ci/global.yml
  .gitlab/ci/on-push.yml
  poetry.lock
  pyproject.toml
Labels: docs-approved

#23451 Remove is_data_source when not applicable
  Tests/Marketplace/marketplace_services.py
Labels: docs-approved

#23237 Transformer convert counrty code name
  Packs/CommonScripts/ReleaseNotes/1_10_35.md
  Packs/CommonScripts/Scripts/ConvertCountryCodeCountryName/ConvertCountryCodeCountryName.py
  Packs/CommonScripts/Scripts/ConvertCountryCodeCountryName/ConvertCountryCodeCountryName.yml
  Packs/CommonScripts/Scripts/ConvertCountryCodeCountryName/ConvertCountryCodeCountryName_test.py
  Packs/CommonScripts/Scripts/ConvertCountryCodeCountryName/README.md
  Packs/CommonScripts/TestPlaybooks/playbook-ConvertCountryCodeCountryName_Test.yml
  Packs/CommonScripts/pack_metadata.json
Labels: docs-approved

#23524 Update integration icons
  Packs/CheckPointDome9/Integrations/CheckPointDome9/CheckPointDome9_image.png
  Packs/CheckPointDome9/ReleaseNotes/1_0_2.md
  Packs/CheckPointDome9/pack_metadata.json
  Packs/Cyberint/Integrations/Cyberint/Cyberint.py
  Packs/Cyberint/Integrations/Cyberint/Cyberint.yml
  Packs/Cyberint/Integrations/Cyberint/Cyberint_image.png
  Packs/Cyberint/ReleaseNotes/1_0_15.md
  Packs/Cyberint/pack_metadata.json
Labels: docs-approved

#23173 bug - TAXII2 server missing entries in sdo indicator
  Packs/TAXIIServer/Integrations/TAXII2Server/TAXII2Server.py
  Packs/TAXIIServer/Integrations/TAXII2Server/TAXII2Server.yml
  Packs/TAXIIServer/Integrations/TAXII2Server/TAXII2Server_test.py
  Packs/TAXIIServer/Integrations/TAXII2Server/test_data/collections20.json
  Packs/TAXIIServer/Integrations/TAXII2Server/test_data/collections21.json
  Packs/TAXIIServer/Integrations/TAXII2Server/test_data/domain_iocs.json
  Packs/TAXIIServer/Integrations/TAXII2Server/test_data/file_iocs.json
  Packs/TAXIIServer/Integrations/TAXII2Server/test_data/ip_iocs.json
  Packs/TAXIIServer/Integrations/TAXII2Server/test_data/malware_iocs.json
  Packs/TAXIIServer/Integrations/TAXII2Server/test_data/manifest20.json
  Packs/TAXIIServer/Integrations/TAXII2Server/test_data/manifest21.json
  Packs/TAXIIServer/Integrations/TAXII2Server/test_data/objects20-indicators.json
  Packs/TAXIIServer/Integrations/TAXII2Server/test_data/objects20.json
  Packs/TAXIIServer/Integrations/TAXII2Server/test_data/objects21_domain.json
  Packs/TAXIIServer/Integrations/TAXII2Server/test_data/objects21_file.json
  Packs/TAXIIServer/Integrations/TAXII2Server/test_data/objects21_malware.json
  Packs/TAXIIServer/Integrations/TAXII2Server/test_data/objects21_no_extention_file.json
  Packs/TAXIIServer/Integrations/TAXII2Server/test_data/objects21_spec_fields_file.json
  Packs/TAXIIServer/ReleaseNotes/2_0_20.md
  Packs/TAXIIServer/pack_metadata.json
Labels: docs-approved

#23271 Elastic search query dsl bug fix
  Packs/Elasticsearch/Integrations/Elasticsearch_v2/Elasticsearch_v2.py
  Packs/Elasticsearch/Integrations/Elasticsearch_v2/Elasticsearch_v2.yml
  Packs/Elasticsearch/Integrations/Elasticsearch_v2/Elasticsearch_v2_test.py
  Packs/Elasticsearch/ReleaseNotes/1_3_10.md
  Packs/Elasticsearch/pack_metadata.json
Labels: docs-approved

#23449 Remove gold server url from content repo
  .github/workflows/run-secrets-detection.yml
  .github/workflows/trigger-contribution-build.yml
  Utils/github_workflow_scripts/run_secrets_detection.py
  Utils/github_workflow_scripts/run_secrets_detection_get_playbook_status.py
  Utils/github_workflow_scripts/trigger_contribution_build.py
Labels: docs-approved

#23540 Remove marketplace v2 from ML pack
  Packs/ML/pack_metadata.json
Labels: docs-approved

#23438 Change widgets to use rawName, rawType and rawCloseRreason
  Packs/CaseManagement-Generic/Dashboards/My_Incidents.json
  Packs/CaseManagement-Generic/Dashboards/dashboard-Incidents_Overview.json
  Packs/CaseManagement-Generic/ReleaseNotes/1_4_1.md
  Packs/CaseManagement-Generic/Widgets/widget-My_Incidents_by_Type.json
  Packs/CaseManagement-Generic/pack_metadata.json
  Packs/CommonDashboards/Dashboards/dashboard-Home.json
  Packs/CommonDashboards/Dashboards/dashboard-Incidents.json
  Packs/CommonDashboards/Dashboards/dashboard-SLA.json
  Packs/CommonDashboards/ReleaseNotes/1_3_1.md
  Packs/CommonDashboards/pack_metadata.json
  Packs/CommonWidgets/ReleaseNotes/1_2_11.md
  Packs/CommonWidgets/Widgets/Widget-LateSLAbyType.json
  Packs/CommonWidgets/Widgets/Widget-WithinSLAbyType.json
  Packs/CommonWidgets/Widgets/widget-ActiveIncidentsLine.json
  Packs/CommonWidgets/Widgets/widget-IncidentByCloseReason.json
  Packs/CommonWidgets/Widgets/widget-IncidentSeverityByType.json
  Packs/CommonWidgets/Widgets/widget-IncidentTypesBySeverity.json
  Packs/CommonWidgets/Widgets/widget-MttdByType.json
  Packs/CommonWidgets/Widgets/widget-MttrByType.json
  Packs/CommonWidgets/Widgets/widget-MttrByTypeInMinutes.json
  Packs/CommonWidgets/Widgets/widget-MttrByTypeOccurred.json
  Packs/CommonWidgets/Widgets/widget-SLAbyType.json
  Packs/CommonWidgets/pack_metadata.json
  Packs/Cybersixgill-ActionableAlerts/Dashboards/dashboard_Cybersixgill_Actionable_Alerts.json
  Packs/Cybersixgill-ActionableAlerts/ReleaseNotes/1_1_4.md
  Packs/Cybersixgill-ActionableAlerts/pack_metadata.json
  Packs/PrismaCloud/Dashboards/dashboard-Prisma_Cloud_Incidents.json
  Packs/PrismaCloud/ReleaseNotes/2_0_20.md
  Packs/PrismaCloud/pack_metadata.json
  Packs/ProofpointTAP/Dashboards/dashboard-ProofpointTAP.json
  Packs/ProofpointTAP/ReleaseNotes/1_1_23.md
  Packs/ProofpointTAP/pack_metadata.json
  Packs/RecordedFuture/Dashboards/dashboard-Recorded_Future.json
  Packs/RecordedFuture/ReleaseNotes/1_3_1.md
  Packs/RecordedFuture/pack_metadata.json
Labels: docs-approved

#23503 Fix SMB test playbook
  Packs/SMB/TestPlaybooks/playbook-SMB_test.yml
Labels: docs-approved

#23510 fix Qradar-v3 tpb
  Packs/QRadar/TestPlaybooks/QRadar_v3-test.yml
  Tests/conf.json
Labels: docs-approved

#23434 move files to filters and transformers-1
  Packs/CommonScripts/ReleaseNotes/1_10_36.json
  Packs/CommonScripts/ReleaseNotes/1_10_36.md
  Packs/CommonScripts/pack_metadata.json
  Packs/FiltersAndTransformers/ReleaseNotes/1_1_8.md
  Packs/FiltersAndTransformers/Scripts/AfterRelativeDate/AfterRelativeDate.py
  Packs/FiltersAndTransformers/Scripts/AfterRelativeDate/AfterRelativeDate.yml
  Packs/FiltersAndTransformers/Scripts/AfterRelativeDate/AfterRelativeDate_test.py
  Packs/FiltersAndTransformers/Scripts/CIDRBiggerThanPrefix/CIDRBiggerThanPrefix.py
  Packs/FiltersAndTransformers/Scripts/CIDRBiggerThanPrefix/CIDRBiggerThanPrefix.yml
  Packs/FiltersAndTransformers/Scripts/CIDRBiggerThanPrefix/CIDRBiggerThanPrefix_test.py
  Packs/FiltersAndTransformers/Scripts/CIDRBiggerThanPrefix/README.md
  Packs/FiltersAndTransformers/Scripts/CheckIfSubdomain/CheckIfSubdomain.py
  Packs/FiltersAndTransformers/Scripts/CheckIfSubdomain/CheckIfSubdomain.yml
  Packs/FiltersAndTransformers/Scripts/CheckIfSubdomain/CheckIfSubdomain_test.py
  Packs/FiltersAndTransformers/Scripts/CheckIfSubdomain/README.md
  Packs/FiltersAndTransformers/Scripts/GreaterCidrNumAddresses/.secrets-ignore
  Packs/FiltersAndTransformers/Scripts/GreaterCidrNumAddresses/GreaterCidrNumAddresses.py
  Packs/FiltersAndTransformers/Scripts/GreaterCidrNumAddresses/GreaterCidrNumAddresses.yml
  Packs/FiltersAndTransformers/Scripts/GreaterCidrNumAddresses/GreaterCidrNumAddresses_test.py
  Packs/FiltersAndTransformers/Scripts/InRange/InRange.py
  Packs/FiltersAndTransformers/Scripts/InRange/InRange.yml
  Packs/FiltersAndTransformers/Scripts/InRange/InRange_test.py
  Packs/FiltersAndTransformers/Scripts/InRange/Pipfile
  Packs/FiltersAndTransformers/Scripts/InRange/Pipfile.lock
  Packs/FiltersAndTransformers/Scripts/InRange/README.md
  Packs/FiltersAndTransformers/TestPlaybooks/playbook-CIDRBiggerThanPrefix_Test.yml
  Packs/FiltersAndTransformers/TestPlaybooks/playbook-CheckIfSubdomain_Test.yml
  Packs/FiltersAndTransformers/pack_metadata.json
Labels: docs-approved

#22134 Created trigger for IOC alert playbook
  Packs/Core/.pack-ignore
  Packs/Core/ReleaseNotes/1_3_23.md
  Packs/Core/Triggers/Trigger_-_IOC_Alert.json
  Packs/Core/pack_metadata.json
Labels: docs-approved

#23541 [Microsoft Graph Mail Single User] fetch-incidents Bugfix
  Packs/MicrosoftGraphListener/Integrations/MicrosoftGraphListener/MicrosoftGraphListener.py
  Packs/MicrosoftGraphListener/Integrations/MicrosoftGraphListener/MicrosoftGraphListener_test.py
  Packs/MicrosoftGraphListener/ReleaseNotes/1_3_3.md
  Packs/MicrosoftGraphListener/pack_metadata.json
Labels: docs-approved

#23545 hotfix to upload content graph
  .gitlab/ci/bucket-upload.yml
Labels: docs-approved

#23554 raise timeout to ms_graph_mail tpb
  Tests/conf.json
Labels: docs-approved

#23502 QRadar mirroring fix
  Packs/QRadar/Integrations/QRadar_v3/QRadar_v3.py
  Packs/QRadar/Integrations/QRadar_v3/QRadar_v3.yml
  Packs/QRadar/ReleaseNotes/2_4_2.md
  Packs/QRadar/pack_metadata.json
Labels: docs-approved

#23556 Duo v2auth api
  Packs/DuoAdminApi/Integrations/DuoEventCollector/DuoEventCollector.py
  Packs/DuoAdminApi/Integrations/DuoEventCollector/DuoEventCollector.yml
  Packs/DuoAdminApi/ReleaseNotes/3_2_0.md
  Packs/DuoAdminApi/pack_metadata.json
Labels: docs-approved

#23352 adding `context_key` to the `ConvertTableToHTML` script
  Packs/CommonScripts/ReleaseNotes/1_10_39.md
  Packs/CommonScripts/Scripts/ConvertTableToHTML/ConvertTableToHTML.js
  Packs/CommonScripts/Scripts/ConvertTableToHTML/ConvertTableToHTML.yml
  Packs/CommonScripts/Scripts/ConvertTableToHTML/README.md
  Packs/CommonScripts/TestPlaybooks/ConvertTableToHTML_-_TEST.yml
  Packs/CommonScripts/pack_metadata.json
Labels: docs-approved

#23563 fix upload graph in upload-flow
  .gitlab/ci/bucket-upload.yml
Labels: docs-approved

#23236 [CommonServerPython] CommandResults tagging support for the war room
  Packs/Base/ReleaseNotes/1_31_52.md
  Packs/Base/Scripts/CommonServerPython/CommonServerPython.py
  Packs/Base/Scripts/CommonServerPython/CommonServerPython_test.py
  Packs/Base/pack_metadata.json
Labels: Contribution, Contribution Form Filled, Community

#23500 Google Cloud SCC release 212
  Packs/GoogleCloudSCC/Integrations/GoogleCloudSCC/GoogleCloudSCC.yml
  Packs/GoogleCloudSCC/Integrations/GoogleCloudSCC/GoogleCloudSCC_description.md
  Packs/GoogleCloudSCC/Integrations/GoogleCloudSCC/README.md
  Packs/GoogleCloudSCC/ReleaseNotes/2_1_2.md
  Packs/GoogleCloudSCC/pack_metadata.json
Labels: Contribution, Partner, Contribution Form Filled

#23550 Change DemistoLock display name
  Packs/DemistoLocking/pack_metadata.json
Labels: docs-approved

#23557 EXPANDR-2058
  Packs/Tenable_io/Integrations/Tenable_io/Tenable_io.yml
  Packs/Tenable_io/ReleaseNotes/2_1_1.md
  Packs/Tenable_io/pack_metadata.json
Labels: Contribution, docs-approved, ready-for-instance-test, Contribution Form Filled, Community

#23440 Added dns rtdns spywarec2 reputation in threat vault v2
  Packs/PaloAltoNetworks_Threat_Vault/.pack-ignore
  Packs/PaloAltoNetworks_Threat_Vault/Integrations/ThreatVaultv2/README.md
  Packs/PaloAltoNetworks_Threat_Vault/Integrations/ThreatVaultv2/ThreatVaultv2.py
  Packs/PaloAltoNetworks_Threat_Vault/Integrations/ThreatVaultv2/ThreatVaultv2.yml
  Packs/PaloAltoNetworks_Threat_Vault/Integrations/ThreatVaultv2/ThreatVaultv2_test.py
  Packs/PaloAltoNetworks_Threat_Vault/ReleaseNotes/2_0_3.md
  Packs/PaloAltoNetworks_Threat_Vault/pack_metadata.json
Labels: docs-approved

#23566 Wiz 1.2.1
  Packs/Wiz/Integrations/Wiz/Wiz.py
  Packs/Wiz/Integrations/Wiz/Wiz.yml
  Packs/Wiz/Integrations/Wiz/Wiz_test.py
  Packs/Wiz/ReleaseNotes/1_2_1.md
  Packs/Wiz/pack_metadata.json
Labels: Contribution, Partner, Contribution Form Filled, pending-contributor

#23565 Whois date
  Packs/Whois/.pack-ignore
  Packs/Whois/Integrations/Whois/Whois.yml
  Packs/Whois/ReleaseNotes/1_4_6.md
  Packs/Whois/pack_metadata.json
Labels: docs-approved

#23575 Duo hotfix
  Packs/DuoAdminApi/Integrations/DuoEventCollector/DuoEventCollector.py
  Packs/DuoAdminApi/ReleaseNotes/3_2_1.md
  Packs/DuoAdminApi/pack_metadata.json
Labels: docs-approved

#23558 Update ZeroTrustAnalyticsPlatform to 1.1.3
  Packs/ZeroTrustAnalyticsPlatform/Integrations/ZeroTrustAnalyticsPlatform/ZeroTrustAnalyticsPlatform.py
  Packs/ZeroTrustAnalyticsPlatform/Integrations/ZeroTrustAnalyticsPlatform/ZeroTrustAnalyticsPlatform.yml
  Packs/ZeroTrustAnalyticsPlatform/README.md
  Packs/ZeroTrustAnalyticsPlatform/ReleaseNotes/1_1_3.md
  Packs/ZeroTrustAnalyticsPlatform/pack_metadata.json
Labels: Contribution, docs-approved, Partner, Contribution Form Filled, pending-contributor

#23602 Azure compute update
  Packs/AzureCompute/.secrets-ignore
  Packs/AzureCompute/Integrations/AzureCompute_v2/AzureCompute_v2.py
  Packs/AzureCompute/Integrations/AzureCompute_v2/AzureCompute_v2.yml
  Packs/AzureCompute/Integrations/AzureCompute_v2/AzureCompute_v2_description.md
  Packs/AzureCompute/Integrations/AzureCompute_v2/AzureCompute_v2_test.py
  Packs/AzureCompute/Integrations/AzureCompute_v2/README.md
  Packs/AzureCompute/Integrations/AzureCompute_v2/test_data/get_public_ip_details_command.json
  Packs/AzureCompute/Integrations/AzureCompute_v2/test_data/get_public_ip_details_command_multiple_ips.json
  Packs/AzureCompute/ReleaseNotes/1_2_0.md
  Packs/AzureCompute/TestPlaybooks/AzureComputeTest.yml
  Packs/AzureCompute/pack_metadata.json
Labels: Contribution, docs-approved, post-demo, Contribution Form Filled, Community

#23577 Fix release notes in marketplace
  Packs/AzureKeyVault/ReleaseNotes/1_1_5.md
  Packs/AzureRiskyUsers/ReleaseNotes/1_1_5.md
  Packs/AzureSQLManagement/ReleaseNotes/1_1_5.md
  Packs/AzureSecurityCenter/ReleaseNotes/1_3_6.md
  Packs/AzureSentinel/ReleaseNotes/1_4_6.md
  Packs/AzureStorage/ReleaseNotes/1_2_5.md
  Packs/AzureWAF/ReleaseNotes/1_1_5.md
  Packs/CheckPointDome9/ReleaseNotes/1_0_2.md
  Packs/CommonScripts/ReleaseNotes/1_10_36.md
  Packs/CommonScripts/ReleaseNotes/1_10_37.md
  Packs/Cyberint/ReleaseNotes/1_0_15.md
  Packs/MicrosoftCloudAppSecurity/ReleaseNotes/2_1_12.md
  Packs/MicrosoftDefenderAdvancedThreatProtection/ReleaseNotes/1_15_3.md
  Packs/MicrosoftGraphApplications/ReleaseNotes/1_2_5.md
  Packs/MicrosoftGraphCalendar/ReleaseNotes/1_1_5.md
  Packs/MicrosoftGraphDeviceManagement/ReleaseNotes/1_1_5.md
  Packs/MicrosoftGraphGroups/ReleaseNotes/1_1_5.md
  Packs/MicrosoftGraphIdentityandAccess/ReleaseNotes/1_2_6.md
  Packs/MicrosoftGraphMail/ReleaseNotes/1_4_1.md
  Packs/QRadar/ReleaseNotes/2_4_2.md
  Packs/SailPointIdentityIQ/ReleaseNotes/1_0_8.md
  Tests/Marketplace/marketplace_services.py
Labels: docs-approved, ForceMerge

#23443 Pngs rename and relocation
  Packs/Akamai_SIEM/Integrations/Akamai_SIEM/pytest.ini
  Packs/Base/Scripts/DBotMLFetchData/glove_top_20.p
  Packs/Base/Scripts/DBotMLFetchData/test_data.p
  Packs/PhishLabs/Integrations/PhishLabsIOC_DRP/pytest.ini
  Packs/QRadar/Integrations/QRadar/QRadar_image.png
  Packs/QRadar/Integrations/QRadar/Qradar_image.png
  Packs/QRadar/Integrations/QRadar_v2/QRadar_v2_image.png
  Packs/QRadar/Integrations/QRadar_v2/Qradar_v2_image.png
  Packs/QRadar/ReleaseNotes/2_4_3.md
  Packs/QRadar/pack_metadata.json
  Packs/ReversingLabs_A1000/doc_files/Playbook_-_Detonate_File_-_ReversingLabs_A1000.png
  Packs/ReversingLabs_TitaniumScale/doc_files/Detonate_File_-_ReversingLabs_TitaniumScale.png
  Packs/ReversingLabs_Titanium_Cloud/doc_files/Playbook_-_Analyze_URL_-_ReversingLabs_TitaniumCloud.png
  Packs/ReversingLabs_Titanium_Cloud/doc_files/Playbook_-_File_Reputation_-_ReversingLabs_TitaniumCloud.png
Labels: docs-approved, ForceMerge

#23433 [Azure Storage Container] - fix issue in the azure-storage-container-blob-create command
  Packs/AzureStorageContainer/Integrations/AzureStorageContainer/AzureStorageContainer.py
  Packs/AzureStorageContainer/Integrations/AzureStorageContainer/AzureStorageContainer.yml
  Packs/AzureStorageContainer/Integrations/AzureStorageContainer/AzureStorageContainer_test.py
  Packs/AzureStorageContainer/Integrations/AzureStorageContainer/README.md
  Packs/AzureStorageContainer/ReleaseNotes/1_0_4.md
  Packs/AzureStorageContainer/pack_metadata.json
Labels: docs-approved

#23606 removed ssh un relevant ssh acctions from circle
  .circleci/config.yml
Labels: docs-approved

#22601 Add Custom Fields to JiraCreateIssueExample Script
  Packs/Jira/.pack-ignore
  Packs/Jira/ReleaseNotes/2_0_22.md
  Packs/Jira/Scripts/JiraCreateIssueExample/JiraCreateIssueExample.py
  Packs/Jira/Scripts/JiraCreateIssueExample/JiraCreateIssueExample.yml
  Packs/Jira/Scripts/JiraCreateIssueExample/JiraCreateIssueExample_test.py
  Packs/Jira/Scripts/JiraCreateIssueExample/README.md
  Packs/Jira/pack_metadata.json
Labels: docs-approved

#23428 Crowd strike falcon x renaming
  Packs/CommonPlaybooks/Playbooks/playbook-Detonate_File_-_Generic.yml
  Packs/CommonPlaybooks/Playbooks/playbook-Detonate_URL_-_Generic.yml
  Packs/CommonPlaybooks/Playbooks/playbook-Detonate_URL_-_Generic_README.md
  Packs/CommonPlaybooks/Playbooks/playbook-Detonate_and_Analyze_File_-_Generic.yml
  Packs/CommonPlaybooks/Playbooks/playbook-Detonate_and_Analyze_File_-_Generic_README.md
  Packs/CommonPlaybooks/Playbooks/playbook-Search_For_Hash_In_Sandbox_-_Generic.yml
  Packs/CommonPlaybooks/Playbooks/playbook-Search_For_Hash_In_Sandbox_-_Generic_README.md
  Packs/CommonPlaybooks/ReleaseNotes/2_3_24.md
  Packs/CommonPlaybooks/pack_metadata.json
  Packs/CommonScripts/Scripts/Set/README.md
  Packs/CortexXDR/Playbooks/playbook-Cortex_XDR_Malware_-_Investigation_And_Response.yml
  Packs/CortexXDR/ReleaseNotes/4_9_15.md
  Packs/CortexXDR/pack_metadata.json
  Packs/CrowdStrikeFalconX/Integrations/CrowdStrikeFalconX/CrowdStrikeFalconX.py
  Packs/CrowdStrikeFalconX/Integrations/CrowdStrikeFalconX/CrowdStrikeFalconX.yml
  Packs/CrowdStrikeFalconX/Integrations/CrowdStrikeFalconX/CrowdStrikeFalconX_description.md
  Packs/CrowdStrikeFalconX/Integrations/CrowdStrikeFalconX/README.md
  Packs/CrowdStrikeFalconX/Playbooks/Detonate_File_-_CrowdStrike_Falcon_X.yml
  Packs/CrowdStrikeFalconX/Playbooks/Detonate_File_-_CrowdStrike_Falcon_X_README.md
  Packs/CrowdStrikeFalconX/Playbooks/Detonate_URL_-_CrowdStrike_Falcon_X.yml
  Packs/CrowdStrikeFalconX/Playbooks/Detonate_URL_-_CrowdStrike_Falcon_X_README.md
  Packs/CrowdStrikeFalconX/Playbooks/playbook-FalconX_Detonate_and_Analyze_File.yml
  Packs/CrowdStrikeFalconX/Playbooks/playbook-FalconX_Detonate_and_Analyze_File_README.md
  Packs/CrowdStrikeFalconX/README.md
  Packs/CrowdStrikeFalconX/ReleaseNotes/1_2_17.md
  Packs/CrowdStrikeFalconX/ReleaseNotes/1_2_5.md
  Packs/CrowdStrikeFalconX/TestPlaybooks/CrowdStrike_Falcon_X_-Test-Detonate_File.yml
  Packs/CrowdStrikeFalconX/TestPlaybooks/CrowdStrike_Falcon_X_-Test-Detonate_URL.yml
  Packs/CrowdStrikeFalconX/pack_metadata.json
  Packs/Phishing/ReleaseNotes/3_3_12.md
  Packs/Phishing/Wizards/wizard-Phishing.json
  Packs/Phishing/pack_metadata.json
Labels: docs-approved, release-notes-only

#23608 fix
  Packs/ReversingLabs_A1000/Playbooks/Detonate_File_-_ReversingLabs_A1000_README.md
  Packs/ReversingLabs_TitaniumScale/Playbooks/Detonate_File_-_ReversingLabs_TitaniumScale_README.md
  Packs/ReversingLabs_Titanium_Cloud/Playbooks/Analyze_URL_-_ReversingLabs_TitaniumCloud_README.md
  Packs/ReversingLabs_Titanium_Cloud/Playbooks/File_Reputation_-_ReversingLabs_TitaniumCloud_README.md
Labels: docs-approved

#23175 Gmail: Search large numbers of mailboxes
  Packs/Gmail/.pack-ignore
  Packs/Gmail/Integrations/Gmail/Gmail.py
  Packs/Gmail/Integrations/Gmail/Gmail.yml
  Packs/Gmail/Integrations/Gmail/Gmail_test.py
  Packs/Gmail/Integrations/Gmail/README.md
  Packs/Gmail/Integrations/Gmail/test_data/input_data.py
  Packs/Gmail/Playbooks/playbook-Search-all-mailboxes_with_polling.yml
  Packs/Gmail/Playbooks/playbook-Search-all-mailboxes_with_polling_README.md
  Packs/Gmail/Playbooks/playbook-Search-in-mailboxes_Loop_with_polling.yml
  Packs/Gmail/Playbooks/playbook-Search-in-mailboxes_Loop_with_polling_README.md
  Packs/Gmail/ReleaseNotes/1_3_0.json
  Packs/Gmail/ReleaseNotes/1_3_0.md
  Packs/Gmail/doc_files/Search_all_mailboxes_-_Gmail_with_polling.png
  Packs/Gmail/doc_files/Search_in_mailboxes_Gmail_(Loop)_with_polling.png
  Packs/Gmail/pack_metadata.json
  Tests/known_words.txt
Labels: docs-approved

#23576 Apache web server fix
  Packs/ApacheWebServer/ModelingRules/ApacheWebServerModelingRules_1_3/ApacheWebServerModelingRules_1_3.xif
  Packs/ApacheWebServer/ReleaseNotes/1_0_6.md
  Packs/ApacheWebServer/pack_metadata.json
Labels: docs-approved

#23385 ResolveShortenedURL Enhancement
  Packs/CommonScripts/.secrets-ignore
  Packs/CommonScripts/ReleaseNotes/1_10_40.md
  Packs/CommonScripts/Scripts/ResolveShortenedURL/README.md
  Packs/CommonScripts/Scripts/ResolveShortenedURL/ResolveShortenedURL.py
  Packs/CommonScripts/Scripts/ResolveShortenedURL/ResolveShortenedURL.yml
  Packs/CommonScripts/Scripts/ResolveShortenedURL/ResolveShortenedURL_test.py
  Packs/CommonScripts/Scripts/ResolveShortenedURL/test_data/built-in/invalid_url_expected_output.json
  Packs/CommonScripts/Scripts/ResolveShortenedURL/test_data/built-in/limited_unshorten_expected_output.json
  Packs/CommonScripts/Scripts/ResolveShortenedURL/test_data/built-in/nested_unshorten_expected_output.json
  Packs/CommonScripts/Scripts/ResolveShortenedURL/test_data/longurl.in/invalid_url.json
  Packs/CommonScripts/Scripts/ResolveShortenedURL/test_data/longurl.in/invalid_url_expected_output.json
  Packs/CommonScripts/Scripts/ResolveShortenedURL/test_data/longurl.in/limited_unshorten_expected_output.json
  Packs/CommonScripts/Scripts/ResolveShortenedURL/test_data/longurl.in/nested_unshorten_0.json
  Packs/CommonScripts/Scripts/ResolveShortenedURL/test_data/longurl.in/nested_unshorten_1.json
  Packs/CommonScripts/Scripts/ResolveShortenedURL/test_data/longurl.in/nested_unshorten_2.json
  Packs/CommonScripts/Scripts/ResolveShortenedURL/test_data/longurl.in/nested_unshorten_expected_output.json
  Packs/CommonScripts/Scripts/ResolveShortenedURL/test_data/unshorten.me/invalid_url.json
  Packs/CommonScripts/Scripts/ResolveShortenedURL/test_data/unshorten.me/invalid_url_expected_output.json
  Packs/CommonScripts/Scripts/ResolveShortenedURL/test_data/unshorten.me/limited_unshorten_expected_output.json
  Packs/CommonScripts/Scripts/ResolveShortenedURL/test_data/unshorten.me/nested_unshorten_0.json
  Packs/CommonScripts/Scripts/ResolveShortenedURL/test_data/unshorten.me/nested_unshorten_1.json
  Packs/CommonScripts/Scripts/ResolveShortenedURL/test_data/unshorten.me/nested_unshorten_2.json
  Packs/CommonScripts/Scripts/ResolveShortenedURL/test_data/unshorten.me/nested_unshorten_expected_output.json
  Packs/CommonScripts/pack_metadata.json
Labels: docs-approved

#23230 SMIME stderr bug fix
  Packs/SMIME_Messaging/Integrations/SMIME_Messaging/SMIME_Messaging.py
  Packs/SMIME_Messaging/Integrations/SMIME_Messaging/SMIME_Messaging.yml
  Packs/SMIME_Messaging/ReleaseNotes/1_0_7.md
  Packs/SMIME_Messaging/pack_metadata.json
Labels: docs-approved

#23359 Changes to Slack Logger
  Packs/Slack/Integrations/SlackV3/SlackV3.py
  Packs/Slack/Integrations/SlackV3/SlackV3.yml
  Packs/Slack/Integrations/SlackV3/SlackV3_test.py
  Packs/Slack/ReleaseNotes/3_1_15.md
  Packs/Slack/pack_metadata.json
Labels: docs-approved

#23544 Tim indicator relationships analysis
  Packs/TIM_Processing/Playbooks/playbook-TIM_-_Indicator_Relationships_Analysis.yml
  Packs/TIM_Processing/Playbooks/playbook-TIM_-_Indicator_Relationships_Analysis_README.md
  Packs/TIM_Processing/ReleaseNotes/1_1_13.md
  Packs/TIM_Processing/doc_files/TIM_-_Indicator_Relationships_Analysis.png
  Packs/TIM_Processing/pack_metadata.json
Labels: docs-approved

#23623 SDK v1.8.3.
  poetry.lock
  pyproject.toml
Labels: docs-approved

#23624 change update to create graphs on builds
  .gitlab/ci/on-push.yml
Labels: docs-approved

#23618 Update EDL_description.md
  Packs/EDL/Integrations/EDL/EDL_description.md
  Packs/EDL/ReleaseNotes/3_1_15.md
  Packs/EDL/pack_metadata.json
Labels: docs-approved

#23300 CortexXDR - add support in credential store
  Packs/CortexXDR/.pack-ignore
  Packs/CortexXDR/Integrations/XDR_iocs/XDR_iocs.py
  Packs/CortexXDR/Integrations/XDR_iocs/XDR_iocs.yml
  Packs/CortexXDR/ReleaseNotes/4_9_16.md
  Packs/CortexXDR/pack_metadata.json
Labels: docs-approved

#23600 MSGraphMail TPB fix
  Packs/MicrosoftGraphMail/TestPlaybooks/playbook-MicrosoftGraphMail-Test.yml
Labels: docs-approved

#23658 Search in mailboxes playbook update the image path
  Packs/Gmail/Playbooks/playbook-Search-in-mailboxes_Loop_with_polling_README.md
  Packs/Gmail/doc_files/Search_in_mailboxes_Gmail_Loop_with_polling.png
Labels: docs-approved

#22561 Neosec Pack
  Packs/Neosec/.pack-ignore
  Packs/Neosec/.secrets-ignore
  Packs/Neosec/Author_image.png
  Packs/Neosec/Classifiers/classifier-mapper-incoming-Neosec.json
  Packs/Neosec/IncidentFields/incidentfield-Neosec_Endpoints.json
  Packs/Neosec/IncidentFields/incidentfield-Neosec_Entities.json
  Packs/Neosec/IncidentFields/incidentfield-Neosec_Labels.json
  Packs/Neosec/IncidentFields/incidentfield-Neosec_Recommendations.json
  Packs/Neosec/IncidentTypes/incidenttype-Neosec_Incident.json
  Packs/Neosec/Integrations/Neosec/Neosec.py
  Packs/Neosec/Integrations/Neosec/Neosec.yml
  Packs/Neosec/Integrations/Neosec/Neosec_description.md
  Packs/Neosec/Integrations/Neosec/Neosec_image.png
  Packs/Neosec/Integrations/Neosec/Neosec_test.py
  Packs/Neosec/Integrations/Neosec/Pipfile
  Packs/Neosec/Integrations/Neosec/Pipfile.lock
  Packs/Neosec/Integrations/Neosec/README.md
  Packs/Neosec/Integrations/Neosec/command_examples
  Packs/Neosec/Layouts/layoutscontainer-Neosec_Incident_Layout.json
  Packs/Neosec/README.md
  Packs/Neosec/pack_metadata.json
Labels: Contribution, Partner, post-demo, Contribution Form Filled, pending-contributor

#23630 Update DeveloperTools in bucket
  Packs/DeveloperTools/ReleaseNotes/1_2_30.md
  Packs/DeveloperTools/Scripts/WaitAndCompleteTask/WaitAndCompleteTask.yml
  Packs/DeveloperTools/pack_metadata.json
Labels: docs-approved, release-notes-only

#23559 trigger build on content private custom branch
  .gitlab/ci/on-push.yml
  Tests/scripts/check_if_branch_exist.sh
  Tests/secrets_white_list.json
  Utils/trigger_private_build.py
Labels: docs-approved

#23353 AutoFocus - add support in credential store
  Packs/AutoFocus/.pack-ignore
  Packs/AutoFocus/Integrations/AutofocusV2/AutofocusV2.py
  Packs/AutoFocus/Integrations/AutofocusV2/AutofocusV2.yml
  Packs/AutoFocus/Integrations/FeedAutofocus/FeedAutofocus.py
  Packs/AutoFocus/Integrations/FeedAutofocus/FeedAutofocus.yml
  Packs/AutoFocus/ReleaseNotes/2_0_34.md
  Packs/AutoFocus/pack_metadata.json
Labels: docs-approved

#23551 Remove unnecessary scripts from XSIAM
  Packs/Base/ReleaseNotes/1_31_53.md
  Packs/Base/Scripts/DrawRelatedIncidentsCanvas/DrawRelatedIncidentsCanvas.yml
  Packs/Base/pack_metadata.json
  Packs/CommonScripts/ReleaseNotes/1_10_41.md
  Packs/CommonScripts/Scripts/LinkIncidentsWithRetry/LinkIncidentsWithRetry.yml
  Packs/CommonScripts/Scripts/MarkRelatedIncidents/MarkRelatedIncidents.yml
  Packs/CommonScripts/pack_metadata.json
Labels: docs-approved

#23145 Collect packs to upload
  Tests/Marketplace/Tests/marketplace_services_test.py
  Tests/Marketplace/Tests/upload_packs_test.py
  Tests/Marketplace/marketplace_constants.py
  Tests/Marketplace/marketplace_services.py
  Tests/Marketplace/upload_packs.py
  Tests/configure_and_test_integration_instances.py
  Tests/scripts/collect_tests/collect_tests.py
  Tests/scripts/collect_tests/path_manager.py
  Tests/scripts/infrastructure_tests/test_collect_tests.py
  Tests/scripts/infrastructure_tests/tests_data/collect_tests/A_xsiam/Packs/Whois/pack_metadata.json
  Tests/scripts/infrastructure_tests/tests_data/collect_tests/B_xsiam/Packs/Whois/pack_metadata.json
  Tests/scripts/infrastructure_tests/tests_data/collect_tests/C/Packs/Whois/pack_metadata.json
  Tests/scripts/infrastructure_tests/tests_data/collect_tests/D/Packs/myPack/pack_metadata.json
  Tests/scripts/infrastructure_tests/tests_data/collect_tests/E/Packs/Whois/pack_metadata.json
  Tests/scripts/infrastructure_tests/tests_data/collect_tests/E/Packs/myPack/pack_metadata.json
  Tests/scripts/infrastructure_tests/tests_data/collect_tests/Q/Packs/myPack/pack_metadata.json
  Tests/scripts/infrastructure_tests/tests_data/collect_tests/R/Packs/CoreAlertFields/Integrations/myIntegration/myIntegration.py
  Tests/scripts/infrastructure_tests/tests_data/collect_tests/R/Packs/CoreAlertFields/Integrations/myIntegration/myIntegration.yml
  Tests/scripts/infrastructure_tests/tests_data/collect_tests/R/Packs/CoreAlertFields/pack_metadata.json
  Tests/scripts/infrastructure_tests/tests_data/collect_tests/R/Packs/bothMarketplacesPack/TestPlaybooks/myTestPlaybook.yml
  Tests/scripts/infrastructure_tests/tests_data/collect_tests/R/Packs/bothMarketplacesPack/pack_metadata.json
  Tests/scripts/infrastructure_tests/tests_data/collect_tests/R/Packs/bothMarketplacesPackOnlyXSIAMIntegration/Integrations/onlyXSIAMIntegration/onlyXSIAMIntegration.py
  Tests/scripts/infrastructure_tests/tests_data/collect_tests/R/Packs/bothMarketplacesPackOnlyXSIAMIntegration/Integrations/onlyXSIAMIntegration/onlyXSIAMIntegration.yml
  Tests/scripts/infrastructure_tests/tests_data/collect_tests/R/Packs/bothMarketplacesPackOnlyXSIAMIntegration/TestPlaybooks/myTestPlaybook.yml
  Tests/scripts/infrastructure_tests/tests_data/collect_tests/R/Packs/bothMarketplacesPackOnlyXSIAMIntegration/pack_metadata.json
  Tests/scripts/infrastructure_tests/tests_data/collect_tests/R/Packs/myXSIAMOnlyPack/Integrations/onlyXSIAMIntegration/onlyXSIAMIntegration.py
  Tests/scripts/infrastructure_tests/tests_data/collect_tests/R/Packs/myXSIAMOnlyPack/Integrations/onlyXSIAMIntegration/onlyXSIAMIntegration.yml
  Tests/scripts/infrastructure_tests/tests_data/collect_tests/R/Packs/myXSIAMOnlyPack/TestPlaybooks/myXSIAMOnlyTestPlaybook.yml
  Tests/scripts/infrastructure_tests/tests_data/collect_tests/R/Packs/myXSIAMOnlyPack/pack_metadata.json
  Tests/scripts/infrastructure_tests/tests_data/collect_tests/R/Packs/myXSOAROnlyPack/TestPlaybooks/myXSOAROnlyTestPlaybook.yml
  Tests/scripts/infrastructure_tests/tests_data/collect_tests/R/Packs/myXSOAROnlyPack/pack_metadata.json
  Tests/scripts/infrastructure_tests/tests_data/collect_tests/R/Tests/conf.json
  Tests/scripts/infrastructure_tests/tests_data/collect_tests/R/Tests/id_set.json
  Tests/scripts/prepare_content_packs_for_testing.sh
Labels: docs-approved, ForceMerge

#23476 Add epp malop v2.0.1
  Packs/Cybereason/Integrations/Cybereason/Cybereason.py
  Packs/Cybereason/Integrations/Cybereason/Cybereason.yml
  Packs/Cybereason/Integrations/Cybereason/Cybereason_test.py
  Packs/Cybereason/Integrations/Cybereason/test_data/malop_detection_data.json
  Packs/Cybereason/Integrations/Cybereason/test_data/malop_to_incident.json
  Packs/Cybereason/Integrations/Cybereason/test_data/non_edr.json
  Packs/Cybereason/ReleaseNotes/2_1_0.md
  Packs/Cybereason/Scripts/CybereasonPreProcessingExample/CybereasonPreProcessingExample.yml
  Packs/Cybereason/pack_metadata.json
Labels: Contribution, Partner, Contribution Form Filled

#23581 Teams workaround
  Packs/MicrosoftTeams/Integrations/MicrosoftTeams/MicrosoftTeams.py
  Packs/MicrosoftTeams/Integrations/MicrosoftTeams/MicrosoftTeams.yml
  Packs/MicrosoftTeams/Integrations/MicrosoftTeams/README.md
  Packs/MicrosoftTeams/ReleaseNotes/1_2_10.md
  Packs/MicrosoftTeams/pack_metadata.json
Labels: docs-approved

#23441 SplunkPy - add support in credential store
  Packs/SplunkPy/.pack-ignore
  Packs/SplunkPy/Integrations/SplunkPy/SplunkPy.py
  Packs/SplunkPy/Integrations/SplunkPy/SplunkPy.yml
  Packs/SplunkPy/ReleaseNotes/3_0_2.md
  Packs/SplunkPy/pack_metadata.json
Labels: docs-approved

#23470 Unit42v2 Feed - add support in credential store
  Packs/FeedUnit42v2/.pack-ignore
  Packs/FeedUnit42v2/Integrations/FeedUnit42v2/FeedUnit42v2.py
  Packs/FeedUnit42v2/Integrations/FeedUnit42v2/FeedUnit42v2.yml
  Packs/FeedUnit42v2/ReleaseNotes/1_0_20.md
  Packs/FeedUnit42v2/pack_metadata.json
Labels: docs-approved

#23473 WildFire-Reports
  Packs/Palo_Alto_Networks_WildFire/.pack-ignore
  Packs/Palo_Alto_Networks_WildFire/Integrations/WildFireReports/WildFireReports.py
  Packs/Palo_Alto_Networks_WildFire/Integrations/WildFireReports/WildFireReports.yml
  Packs/Palo_Alto_Networks_WildFire/ReleaseNotes/2_1_9.md
  Packs/Palo_Alto_Networks_WildFire/pack_metadata.json
Labels: docs-approved

#23668 Fix ExpanseV2 TPB
  Packs/ExpanseV2/TestPlaybooks/playbook-ExpanseV2_Test.yml
Labels: docs-approved

#23610 devcontainer fixes
  .devcontainer/Dockerfile
  .devcontainer/devcontainer.json
Labels: docs-approved

#23515 Microsoft Defender Advanced Threat Protection - add support in credential store
  Packs/MicrosoftDefenderAdvancedThreatProtection/.pack-ignore
  Packs/MicrosoftDefenderAdvancedThreatProtection/Integrations/MicrosoftDefenderAdvancedThreatProtection/MicrosoftDefenderAdvancedThreatProtection.py
  Packs/MicrosoftDefenderAdvancedThreatProtection/Integrations/MicrosoftDefenderAdvancedThreatProtection/MicrosoftDefenderAdvancedThreatProtection.yml
  Packs/MicrosoftDefenderAdvancedThreatProtection/ReleaseNotes/1_15_4.md
  Packs/MicrosoftDefenderAdvancedThreatProtection/pack_metadata.json
Labels: docs-approved

#23625 URL Regex update to fix IP catching issue and random highlights
  Packs/CommonTypes/.pack-ignore
  Packs/CommonTypes/IndicatorTypes/reputation-url.json
  Packs/CommonTypes/ReleaseNotes/3_3_42.md
  Packs/CommonTypes/pack_metadata.json
Labels: docs-approved

#23634 fixed validation error
  Packs/CommunityCommonScripts/.pack-ignore
  Packs/CommunityCommonScripts/Scripts/GetFilePathPreProcessing/GetFilePathPreProcessing.yml
Labels: docs-approved

#23669 Increased Timeout Indicator Formatter TPB
  Tests/conf.json
Labels: docs-approved

#21994 Cisco AMP Integration
  Packs/CiscoAMP/.pack-ignore
  Packs/CiscoAMP/.secrets-ignore
  Packs/CiscoAMP/Integrations/CiscoAMP/CiscoAMP.py
  Packs/CiscoAMP/Integrations/CiscoAMP/CiscoAMP.yml
  Packs/CiscoAMP/Integrations/CiscoAMP/CiscoAMP_description.md
  Packs/CiscoAMP/Integrations/CiscoAMP/CiscoAMP_image.png
  Packs/CiscoAMP/Integrations/CiscoAMP/CiscoAMP_test.py
  Packs/CiscoAMP/Integrations/CiscoAMP/README.md
  Packs/CiscoAMP/Integrations/CiscoAMP/test_data/app_trajectory_query_response.json
  Packs/CiscoAMP/Integrations/CiscoAMP/test_data/computer_activity_response.json
  Packs/CiscoAMP/Integrations/CiscoAMP/test_data/computer_delete_fail_response.json
  Packs/CiscoAMP/Integrations/CiscoAMP/test_data/computer_delete_response.json
  Packs/CiscoAMP/Integrations/CiscoAMP/test_data/computer_get_response.json
  Packs/CiscoAMP/Integrations/CiscoAMP/test_data/computer_list_response.json
  Packs/CiscoAMP/Integrations/CiscoAMP/test_data/computer_move_response.json
  Packs/CiscoAMP/Integrations/CiscoAMP/test_data/computer_trajectory_response.json
  Packs/CiscoAMP/Integrations/CiscoAMP/test_data/computer_user_activity_response.json
  Packs/CiscoAMP/Integrations/CiscoAMP/test_data/computer_user_trajectory_response.json
  Packs/CiscoAMP/Integrations/CiscoAMP/test_data/computer_vulnerabilities_response.json
  Packs/CiscoAMP/Integrations/CiscoAMP/test_data/event_list_response.json
  Packs/CiscoAMP/Integrations/CiscoAMP/test_data/event_type_list_response.json
  Packs/CiscoAMP/Integrations/CiscoAMP/test_data/file_list_application_blocking_response.json
  Packs/CiscoAMP/Integrations/CiscoAMP/test_data/file_list_item_create_response.json
  Packs/CiscoAMP/Integrations/CiscoAMP/test_data/file_list_item_delete_fail_response.json
  Packs/CiscoAMP/Integrations/CiscoAMP/test_data/file_list_item_delete_response.json
  Packs/CiscoAMP/Integrations/CiscoAMP/test_data/file_list_item_get_response.json
  Packs/CiscoAMP/Integrations/CiscoAMP/test_data/file_list_item_list_response.json
  Packs/CiscoAMP/Integrations/CiscoAMP/test_data/file_list_list_response.json
  Packs/CiscoAMP/Integrations/CiscoAMP/test_data/file_list_simple_custom_detections_response.json
  Packs/CiscoAMP/Integrations/CiscoAMP/test_data/group_delete_fail_response.json
  Packs/CiscoAMP/Integrations/CiscoAMP/test_data/group_delete_response.json
  Packs/CiscoAMP/Integrations/CiscoAMP/test_data/group_list_response.json
  Packs/CiscoAMP/Integrations/CiscoAMP/test_data/group_response.json
  Packs/CiscoAMP/Integrations/CiscoAMP/test_data/indicator_get_response.json
  Packs/CiscoAMP/Integrations/CiscoAMP/test_data/indicator_list_response.json
  Packs/CiscoAMP/Integrations/CiscoAMP/test_data/isolation_response.json
  Packs/CiscoAMP/Integrations/CiscoAMP/test_data/policy_get_response.json
  Packs/CiscoAMP/Integrations/CiscoAMP/test_data/policy_list_response.json
  Packs/CiscoAMP/Integrations/CiscoAMP/test_data/version_get_response.json
  Packs/CiscoAMP/Integrations/CiscoAMP/test_data/vulnerability_get_response.json
  Packs/CiscoAMP/Integrations/CiscoAMP/test_data/vulnerability_list_response.json
  Packs/CiscoAMP/README.md
  Packs/CiscoAMP/TestPlaybooks/playbook-CiscoAMP_Test.yml
  Packs/CiscoAMP/pack_metadata.json
  Tests/conf.json
Labels: Contribution, docs-approved, Contribution Form Filled, Community, Internal

#23613 Add Stored Credentials Support to Zoom Integrations
  Packs/Zoom/.pack-ignore
  Packs/Zoom/Integrations/Zoom/Zoom.py
  Packs/Zoom/Integrations/Zoom/Zoom.yml
  Packs/Zoom/Integrations/Zoom_IAM/Zoom_IAM.py
  Packs/Zoom/Integrations/Zoom_IAM/Zoom_IAM.yml
  Packs/Zoom/ReleaseNotes/1_2_1.md
  Packs/Zoom/pack_metadata.json
Labels: docs-approved

#23598 APIVoid - add support in credential store
  Packs/APIVoid/.pack-ignore
  Packs/APIVoid/Integrations/APIVoid/APIVoid.py
  Packs/APIVoid/Integrations/APIVoid/APIVoid.yml
  Packs/APIVoid/ReleaseNotes/1_0_27.md
  Packs/APIVoid/pack_metadata.json
Labels: docs-approved

#23579 Microsoft Graph Mail Single User - add support in credential store
  Packs/MicrosoftGraphListener/.pack-ignore
  Packs/MicrosoftGraphListener/Integrations/MicrosoftGraphListener/MicrosoftGraphListener.py
  Packs/MicrosoftGraphListener/Integrations/MicrosoftGraphListener/MicrosoftGraphListener.yml
  Packs/MicrosoftGraphListener/ReleaseNotes/1_3_4.md
  Packs/MicrosoftGraphListener/pack_metadata.json
Labels: docs-approved

#23483 Slack - add support in credential store
  Packs/Slack/.pack-ignore
  Packs/Slack/Integrations/Slack/Slack.py
  Packs/Slack/Integrations/Slack/Slack.yml
  Packs/Slack/Integrations/Slack_IAM/README.md
  Packs/Slack/Integrations/Slack_IAM/Slack_IAM.py
  Packs/Slack/Integrations/Slack_IAM/Slack_IAM.yml
  Packs/Slack/ReleaseNotes/3_1_16.md
  Packs/Slack/pack_metadata.json
Labels: docs-approved

#23437 FeedTAXII - add support in credential store
  Packs/FeedTAXII/.pack-ignore
  Packs/FeedTAXII/Integrations/FeedTAXII/FeedTAXII.py
  Packs/FeedTAXII/Integrations/FeedTAXII/FeedTAXII.yml
  Packs/FeedTAXII/Integrations/FeedTAXII2/FeedTAXII2.py
  Packs/FeedTAXII/Integrations/FeedTAXII2/FeedTAXII2.yml
  Packs/FeedTAXII/ReleaseNotes/1_1_19.md
  Packs/FeedTAXII/pack_metadata.json
Labels: docs-approved

#23256 Add command github_add_Assginee to github pack
  Packs/GitHub/.pack-ignore
  Packs/GitHub/Integrations/GitHub/GitHub.py
  Packs/GitHub/Integrations/GitHub/GitHub.yml
  Packs/GitHub/Integrations/GitHub/GitHub_test.py
  Packs/GitHub/Integrations/GitHub/README.md
  Packs/GitHub/ReleaseNotes/2_0_10.md
  Packs/GitHub/TestPlaybooks/Git_Integration-Test.yml
  Packs/GitHub/pack_metadata.json
Labels: docs-approved

#23479 Reduce index zip size
  Tests/Marketplace/Tests/marketplace_services_test.py
  Tests/Marketplace/Tests/upload_packs_test.py
  Tests/Marketplace/marketplace_services.py
  Tests/Marketplace/upload_packs.py
  Tests/private_build/upload_packs_private.py
Labels: docs-approved

#23117 graph update all level dependencies
  .gitlab/ci/bucket-upload.yml
  Tests/Marketplace/marketplace_services.py
  Tests/scripts/create_artifacts_graph/create_artifacts.py
Labels: docs-approved

#23679 Fix collect always installed packs
  Tests/scripts/collect_tests/collect_tests.py
Labels: docs-approved

#23684 Make summary retrieval command accept array and more
  Packs/HatchingTriage/Integrations/HatchingTriage/HatchingTriage.py
  Packs/HatchingTriage/Integrations/HatchingTriage/HatchingTriage.yml
  Packs/HatchingTriage/ReleaseNotes/1_0_8.md
  Packs/HatchingTriage/pack_metadata.json
Labels: Contribution, docs-approved, Partner, ready-for-instance-test, Contribution Form Filled

#23511 Gmail Single User - add support in credential store
  Packs/GmailSingleUser/.pack-ignore
  Packs/GmailSingleUser/Integrations/GmailSingleUser/GmailSingleUser.py
  Packs/GmailSingleUser/Integrations/GmailSingleUser/GmailSingleUser.yml
  Packs/GmailSingleUser/ReleaseNotes/1_3_4.md
  Packs/GmailSingleUser/pack_metadata.json
Labels: docs-approved

#23516 TaegisXDR - Assignee User Support
  Packs/SecureWorks/Integrations/TaegisXDR/README.md
  Packs/SecureWorks/Integrations/TaegisXDR/TaegisXDR.py
  Packs/SecureWorks/Integrations/TaegisXDR/TaegisXDR.yml
  Packs/SecureWorks/Integrations/TaegisXDR/TaegisXDR_test.py
  Packs/SecureWorks/Integrations/TaegisXDR/command_examples
  Packs/SecureWorks/Integrations/TaegisXDR/test_data/data.py
  Packs/SecureWorks/ReleaseNotes/4_2_0.md
  Packs/SecureWorks/pack_metadata.json
Labels: Contribution, docs-approved, Partner, Contribution Form Filled, pending-contributor

#23468 Move Base64Decode, BetweenDates, BetweenHours and ConvertAllExcept to FiltersAndTransformers pack.
  Packs/CommonScripts/.pack-ignore
  Packs/CommonScripts/ReleaseNotes/1_10_42.json
  Packs/CommonScripts/ReleaseNotes/1_10_42.md
  Packs/CommonScripts/pack_metadata.json
  Packs/FiltersAndTransformers/.pack-ignore
  Packs/FiltersAndTransformers/ReleaseNotes/1_2_0.md
  Packs/FiltersAndTransformers/Scripts/Base64Decode/Base64Decode.py
  Packs/FiltersAndTransformers/Scripts/Base64Decode/Base64Decode.yml
  Packs/FiltersAndTransformers/Scripts/Base64Decode/Base64Decode_test.py
  Packs/FiltersAndTransformers/Scripts/Base64Decode/Pipfile
  Packs/FiltersAndTransformers/Scripts/Base64Decode/Pipfile.lock
  Packs/FiltersAndTransformers/Scripts/Base64Decode/README.md
  Packs/FiltersAndTransformers/Scripts/BetweenDates/BetweenDates.py
  Packs/FiltersAndTransformers/Scripts/BetweenDates/BetweenDates.yml
  Packs/FiltersAndTransformers/Scripts/BetweenDates/BetweenDates_test.py
  Packs/FiltersAndTransformers/Scripts/BetweenDates/Pipfile
  Packs/FiltersAndTransformers/Scripts/BetweenDates/Pipfile.lock
  Packs/FiltersAndTransformers/Scripts/BetweenDates/README.md
  Packs/FiltersAndTransformers/Scripts/BetweenHours/BetweenHours.py
  Packs/FiltersAndTransformers/Scripts/BetweenHours/BetweenHours.yml
  Packs/FiltersAndTransformers/Scripts/BetweenHours/BetweenHours_test.py
  Packs/FiltersAndTransformers/Scripts/BetweenHours/Pipfile
  Packs/FiltersAndTransformers/Scripts/BetweenHours/Pipfile.lock
  Packs/FiltersAndTransformers/Scripts/BetweenHours/README.md
  Packs/FiltersAndTransformers/Scripts/ConvertAllExcept/ConvertAllExcept.py
  Packs/FiltersAndTransformers/Scripts/ConvertAllExcept/ConvertAllExcept.yml
  Packs/FiltersAndTransformers/Scripts/ConvertAllExcept/ConvertAllExcept_test.py
  Packs/FiltersAndTransformers/Scripts/ConvertAllExcept/README.md
  Packs/FiltersAndTransformers/TestPlaybooks/Base64Decode_-_Test.yml
  Packs/FiltersAndTransformers/pack_metadata.json
Labels: docs-approved

#23667 Comparing server versions did not work as expected
  Packs/Base/ReleaseNotes/1_31_54.md
  Packs/Base/Scripts/CommonServer/CommonServer.js
  Packs/Base/pack_metadata.json
Labels: docs-approved

#23693 remove un relevant python2 & update docker tag for circle
  .circleci/config.yml
  .gitlab/ci/global.yml
  Tests/scripts/linters_runner.sh
  Tests/scripts/pyflake.sh
Labels: docs-approved

#23675 Xdr tpb split
  Packs/CortexXDR/Integrations/CortexXDRIR/CortexXDRIR.yml
  Packs/CortexXDR/Integrations/CortexXDRIR/README.md
  Packs/CortexXDR/ReleaseNotes/4_9_17.md
  Packs/CortexXDR/TestPlaybooks/Test_XDR_execute_script_Playbook.yml
  Packs/CortexXDR/TestPlaybooks/Test_XDR_general_and_file_commands_Playbook.yml
  Packs/CortexXDR/pack_metadata.json
  Tests/conf.json
Labels: docs-approved

#23674 ReadPDFFileV2 warnings bug
  Packs/CommonScripts/ReleaseNotes/1_10_43.md
  Packs/CommonScripts/Scripts/ReadPDFFileV2/ReadPDFFileV2.py
  Packs/CommonScripts/Scripts/ReadPDFFileV2/ReadPDFFileV2.yml
  Packs/CommonScripts/pack_metadata.json
Labels: docs-approved

#23635 Community common scripts 19-26
  Packs/CommunityCommonScripts/.secrets-ignore
  Packs/CommunityCommonScripts/ReleaseNotes/1_0_2.md
  Packs/CommunityCommonScripts/Scripts/IPCalcCheckSubnetCollision/IPCalcCheckSubnetCollision.py
  Packs/CommunityCommonScripts/Scripts/IPCalcCheckSubnetCollision/IPCalcCheckSubnetCollision.yml
  Packs/CommunityCommonScripts/Scripts/IPCalcCheckSubnetCollision/README.md
  Packs/CommunityCommonScripts/Scripts/IPCalcReturnAddressBinary/IPCalcReturnAddressBinary.py
  Packs/CommunityCommonScripts/Scripts/IPCalcReturnAddressBinary/IPCalcReturnAddressBinary.yml
  Packs/CommunityCommonScripts/Scripts/IPCalcReturnAddressBinary/README.md
  Packs/CommunityCommonScripts/Scripts/IPCalcReturnAddressIANAAllocation/IPCalcReturnAddressIANAAllocation.py
  Packs/CommunityCommonScripts/Scripts/IPCalcReturnAddressIANAAllocation/IPCalcReturnAddressIANAAllocation.yml
  Packs/CommunityCommonScripts/Scripts/IPCalcReturnAddressIANAAllocation/README.md
  Packs/CommunityCommonScripts/Scripts/IPCalcReturnSubnetAddresses/IPCalcReturnSubnetAddresses.py
  Packs/CommunityCommonScripts/Scripts/IPCalcReturnSubnetAddresses/IPCalcReturnSubnetAddresses.yml
  Packs/CommunityCommonScripts/Scripts/IPCalcReturnSubnetAddresses/README.md
  Packs/CommunityCommonScripts/Scripts/IPCalcReturnSubnetBroadcastAddress/IPCalcReturnSubnetBroadcastAddress.py
  Packs/CommunityCommonScripts/Scripts/IPCalcReturnSubnetBroadcastAddress/IPCalcReturnSubnetBroadcastAddress.yml
  Packs/CommunityCommonScripts/Scripts/IPCalcReturnSubnetBroadcastAddress/README.md
  Packs/CommunityCommonScripts/Scripts/IPCalcReturnSubnetNetwork/IPCalcReturnSubnetNetwork.py
  Packs/CommunityCommonScripts/Scripts/IPCalcReturnSubnetNetwork/IPCalcReturnSubnetNetwork.yml
  Packs/CommunityCommonScripts/Scripts/IPCalcReturnSubnetNetwork/README.md
  Packs/CommunityCommonScripts/Scripts/PHash/PHash.py
  Packs/CommunityCommonScripts/Scripts/PHash/PHash.yml
  Packs/CommunityCommonScripts/Scripts/PHash/README.md
  Packs/CommunityCommonScripts/pack_metadata.json
  Packs/NetCalc/.pack-ignore
  Packs/NetCalc/ReleaseNotes/1_0_1.json
  Packs/NetCalc/ReleaseNotes/1_0_1.md
  Packs/NetCalc/pack_metadata.json
  Packs/PHash/.pack-ignore
  Packs/PHash/ReleaseNotes/1_0_1.json
  Packs/PHash/ReleaseNotes/1_0_1.md
  Packs/PHash/pack_metadata.json
Labels: docs-approved, ForceMerge

#23691 deprecate alexa v1 and v2
  Packs/Alexa/Integrations/Alexa/Alexa.yml
  Packs/Alexa/Integrations/AlexaV2/AlexaV2.yml
  Packs/Alexa/ReleaseNotes/2_0_23.md
  Packs/Alexa/pack_metadata.json
Labels: docs-approved

#23673 Neosec Pack (#22561)
  Packs/Neosec/.pack-ignore
  Packs/Neosec/.secrets-ignore
  Packs/Neosec/Author_image.png
  Packs/Neosec/Classifiers/classifier-mapper-incoming-Neosec.json
  Packs/Neosec/IncidentFields/incidentfield-Neosec_Endpoints.json
  Packs/Neosec/IncidentFields/incidentfield-Neosec_Entities.json
  Packs/Neosec/IncidentFields/incidentfield-Neosec_Labels.json
  Packs/Neosec/IncidentFields/incidentfield-Neosec_Recommendations.json
  Packs/Neosec/IncidentTypes/incidenttype-Neosec_Incident.json
  Packs/Neosec/Integrations/Neosec/Neosec.py
  Packs/Neosec/Integrations/Neosec/Neosec.yml
  Packs/Neosec/Integrations/Neosec/Neosec_description.md
  Packs/Neosec/Integrations/Neosec/Neosec_image.png
  Packs/Neosec/Integrations/Neosec/Neosec_test.py
  Packs/Neosec/Integrations/Neosec/Pipfile
  Packs/Neosec/Integrations/Neosec/Pipfile.lock
  Packs/Neosec/Integrations/Neosec/README.md
  Packs/Neosec/Integrations/Neosec/command_examples
  Packs/Neosec/Layouts/layoutscontainer-Neosec_Incident_Layout.json
  Packs/Neosec/README.md
  Packs/Neosec/pack_metadata.json
Labels: docs-approved

#23696 Add RDP Brute force to classifier
  Packs/CortexXDR/Classifiers/classifier-PaloAltoNetworks_Cortex_XDR_Incident_Handler.json
  Packs/CortexXDR/ReleaseNotes/4_9_18.md
  Packs/CortexXDR/pack_metadata.json
Labels: docs-approved

#23680 Jb adding section phase 2
  Packs/CrowdStrikeFalcon/Integrations/CrowdStrikeFalcon/CrowdStrikeFalcon.yml
  Packs/CrowdStrikeFalcon/ReleaseNotes/1_10_2.md
  Packs/CrowdStrikeFalcon/pack_metadata.json
  Packs/EDL/Integrations/EDL/EDL.yml
  Packs/EDL/ReleaseNotes/3_1_16.md
  Packs/EDL/pack_metadata.json
  Packs/EWSMailSender/Integrations/EWSMailSender/EWSMailSender.yml
  Packs/EWSMailSender/ReleaseNotes/1_1_16.md
  Packs/EWSMailSender/pack_metadata.json
  Packs/HelloWorld/Integrations/HelloWorld/HelloWorld.yml
  Packs/HelloWorld/ReleaseNotes/1_2_15.md
  Packs/HelloWorld/pack_metadata.json
  Packs/MicrosoftDefenderAdvancedThreatProtection/Integrations/Microsoft365DefenderEventCollector/Microsoft365DefenderEventCollector.yml
  Packs/MicrosoftDefenderAdvancedThreatProtection/Integrations/MicrosoftDefenderAdvancedThreatProtection/MicrosoftDefenderAdvancedThreatProtection.yml
  Packs/MicrosoftDefenderAdvancedThreatProtection/ReleaseNotes/1_15_5.md
  Packs/MicrosoftDefenderAdvancedThreatProtection/pack_metadata.json
  Packs/Palo_Alto_Networks_WildFire/Integrations/Palo_Alto_Networks_WildFire_v2/Palo_Alto_Networks_WildFire_v2.yml
  Packs/Palo_Alto_Networks_WildFire/Integrations/WildFireReports/WildFireReports.yml
  Packs/Palo_Alto_Networks_WildFire/ReleaseNotes/2_1_10.md
  Packs/Palo_Alto_Networks_WildFire/pack_metadata.json
  Packs/QRadar/Integrations/QRadar_v3/QRadar_v3.yml
  Packs/QRadar/ReleaseNotes/2_4_4.md
  Packs/QRadar/pack_metadata.json
  Packs/Slack/Integrations/Slack/Slack.yml
  Packs/Slack/Integrations/SlackEventCollector/SlackEventCollector.py
  Packs/Slack/Integrations/SlackEventCollector/SlackEventCollector.yml
  Packs/Slack/Integrations/SlackV3/SlackV3.yml
  Packs/Slack/Integrations/Slack_IAM/Slack_IAM.yml
  Packs/Slack/ReleaseNotes/3_1_17.md
  Packs/Slack/pack_metadata.json
  Packs/UrlScan/Integrations/UrlScan/UrlScan.yml
  Packs/UrlScan/ReleaseNotes/1_2_6.md
  Packs/UrlScan/pack_metadata.json
  Packs/Whois/Integrations/Whois/Whois.yml
  Packs/Whois/ReleaseNotes/1_4_7.md
  Packs/Whois/pack_metadata.json
Labels: docs-approved

#23683 pre-commit: validate pyproject
  .pre-commit-config.yaml
Labels: docs-approved

#23621 Palo Alto Networks IoT - add support in credential store
  Packs/PaloAltoNetworks_IoT/.pack-ignore
  Packs/PaloAltoNetworks_IoT/Integrations/PaloAltoNetworks_IoT/PaloAltoNetworks_IoT.py
  Packs/PaloAltoNetworks_IoT/Integrations/PaloAltoNetworks_IoT/PaloAltoNetworks_IoT.yml
  Packs/PaloAltoNetworks_IoT/ReleaseNotes/1_0_17.md
  Packs/PaloAltoNetworks_IoT/pack_metadata.json
Labels: docs-approved

#23620 AbuseIPDB - add support in credential store
  Packs/AbuseDB/.pack-ignore
  Packs/AbuseDB/Integrations/AbuseDB/AbuseDB.py
  Packs/AbuseDB/Integrations/AbuseDB/AbuseDB.yml
  Packs/AbuseDB/ReleaseNotes/1_0_17.md
  Packs/AbuseDB/pack_metadata.json
Labels: docs-approved

#23619 Proofpoint Threat Response - add support in credential store
  Packs/ProofpointThreatResponse/.pack-ignore
  Packs/ProofpointThreatResponse/Integrations/ProofpointThreatResponse/ProofpointThreatResponse.py
  Packs/ProofpointThreatResponse/Integrations/ProofpointThreatResponse/ProofpointThreatResponse.yml
  Packs/ProofpointThreatResponse/ReleaseNotes/2_0_5.md
  Packs/ProofpointThreatResponse/pack_metadata.json
Labels: docs-approved

#22951 upload pack dependencies bug fix
  Tests/Marketplace/Tests/marketplace_services_test.py
  Tests/Marketplace/copy_and_upload_packs.py
  Tests/Marketplace/marketplace_constants.py
  Tests/Marketplace/marketplace_services.py
  Tests/Marketplace/upload_packs.py
  Tests/private_build/upload_packs_private.py
  Tests/scripts/gitlab_slack_notifier.py
Labels: docs-approved

#23687 Add_campaign_to_mitre
  Packs/FeedMitreAttackv2/Integrations/FeedMitreAttackv2/FeedMitreAttackv2.py
  Packs/FeedMitreAttackv2/Integrations/FeedMitreAttackv2/FeedMitreAttackv2.yml
  Packs/FeedMitreAttackv2/Integrations/FeedMitreAttackv2/FeedMitreAttackv2_test.py
  Packs/FeedMitreAttackv2/Integrations/FeedMitreAttackv2/test_data/mitre_test_data.py
  Packs/FeedMitreAttackv2/ReleaseNotes/1_1_6.md
  Packs/FeedMitreAttackv2/pack_metadata.json
Labels: docs-approved

#23661 Community common scripts 27-32
  Packs/CommunityCommonScripts/.secrets-ignore
  Packs/CommunityCommonScripts/ReleaseNotes/1_0_3.md
  Packs/CommunityCommonScripts/Scripts/CalculateTimeSpan/CalculateTimeSpan.Tests.ps1
  Packs/CommunityCommonScripts/Scripts/CalculateTimeSpan/CalculateTimeSpan.ps1
  Packs/CommunityCommonScripts/Scripts/CalculateTimeSpan/CalculateTimeSpan.yml
  Packs/CommunityCommonScripts/Scripts/CalculateTimeSpan/README.md
  Packs/CommunityCommonScripts/Scripts/RandomElementFromList/README.md
  Packs/CommunityCommonScripts/Scripts/RandomElementFromList/RandomElementFromList.py
  Packs/CommunityCommonScripts/Scripts/RandomElementFromList/RandomElementFromList.yml
  Packs/CommunityCommonScripts/Scripts/RandomPhotoNasa/Pipfile
  Packs/CommunityCommonScripts/Scripts/RandomPhotoNasa/Pipfile.lock
  Packs/CommunityCommonScripts/Scripts/RandomPhotoNasa/README.md
  Packs/CommunityCommonScripts/Scripts/RandomPhotoNasa/RandomPhotoNasa.py
  Packs/CommunityCommonScripts/Scripts/RandomPhotoNasa/RandomPhotoNasa.yml
  Packs/CommunityCommonScripts/Scripts/VersionEqualTo/README.md
  Packs/CommunityCommonScripts/Scripts/VersionEqualTo/VersionEqualTo.Tests.ps1
  Packs/CommunityCommonScripts/Scripts/VersionEqualTo/VersionEqualTo.ps1
  Packs/CommunityCommonScripts/Scripts/VersionEqualTo/VersionEqualTo.yml
  Packs/CommunityCommonScripts/Scripts/VersionGreaterThan/README.md
  Packs/CommunityCommonScripts/Scripts/VersionGreaterThan/VersionGreaterThan.Tests.ps1
  Packs/CommunityCommonScripts/Scripts/VersionGreaterThan/VersionGreaterThan.ps1
  Packs/CommunityCommonScripts/Scripts/VersionGreaterThan/VersionGreaterThan.yml
  Packs/CommunityCommonScripts/Scripts/VersionLessThan/README.md
  Packs/CommunityCommonScripts/Scripts/VersionLessThan/VersionLessThan.Tests.ps1
  Packs/CommunityCommonScripts/Scripts/VersionLessThan/VersionLessThan.ps1
  Packs/CommunityCommonScripts/Scripts/VersionLessThan/VersionLessThan.yml
  Packs/CommunityCommonScripts/pack_metadata.json
  Packs/PowerShellUtilities/.pack-ignore
  Packs/PowerShellUtilities/ReleaseNotes/1_0_1.json
  Packs/PowerShellUtilities/ReleaseNotes/1_0_1.md
  Packs/PowerShellUtilities/pack_metadata.json
  Packs/RandomElementFromList/.pack-ignore
  Packs/RandomElementFromList/ReleaseNotes/1_0_1.json
  Packs/RandomElementFromList/ReleaseNotes/1_0_1.md
  Packs/RandomElementFromList/pack_metadata.json
  Packs/RandomImages_VideosAndAudio/.pack-ignore
  Packs/RandomImages_VideosAndAudio/ReleaseNotes/1_0_2.json
  Packs/RandomImages_VideosAndAudio/ReleaseNotes/1_0_2.md
  Packs/RandomImages_VideosAndAudio/pack_metadata.json
Labels: docs-approved, ForceMerge

#23709 Hotfix - demisto-sdk 1.8.3
  poetry.lock
  pyproject.toml
Labels: docs-approved

#23477 Move ConvertKeysToTableFieldFormat, ConvertToSingleElementArray, Cut, DateToISOFormat, DT to the filters and transformers pack.
  Packs/CommonScripts/.pack-ignore
  Packs/CommonScripts/ReleaseNotes/1_10_44.json
  Packs/CommonScripts/ReleaseNotes/1_10_44.md
  Packs/CommonScripts/Scripts/ConvertToSingleElementArray/ConvertToSingleElementArray.py
  Packs/CommonScripts/Scripts/Cut/Cut_test.py
  Packs/CommonScripts/pack_metadata.json
  Packs/FiltersAndTransformers/ReleaseNotes/1_2_1.md
  Packs/FiltersAndTransformers/Scripts/ConvertKeysToTableFieldFormat/ConvertKeysToTableFieldFormat.js
  Packs/FiltersAndTransformers/Scripts/ConvertKeysToTableFieldFormat/ConvertKeysToTableFieldFormat.yml
  Packs/FiltersAndTransformers/Scripts/ConvertKeysToTableFieldFormat/README.md
  Packs/FiltersAndTransformers/Scripts/ConvertToSingleElementArray/ConvertToSingleElementArray.py
  Packs/FiltersAndTransformers/Scripts/ConvertToSingleElementArray/ConvertToSingleElementArray.yml
  Packs/FiltersAndTransformers/Scripts/ConvertToSingleElementArray/ConvertToSingleElementArray_test.py
  Packs/FiltersAndTransformers/Scripts/ConvertToSingleElementArray/README.md
  Packs/FiltersAndTransformers/Scripts/Cut/Cut.py
  Packs/FiltersAndTransformers/Scripts/Cut/Cut.yml
  Packs/FiltersAndTransformers/Scripts/Cut/Cut_test.py
  Packs/FiltersAndTransformers/Scripts/Cut/Pipfile
  Packs/FiltersAndTransformers/Scripts/Cut/Pipfile.lock
  Packs/FiltersAndTransformers/Scripts/Cut/README.md
  Packs/FiltersAndTransformers/Scripts/DT/DT.py
  Packs/FiltersAndTransformers/Scripts/DT/DT.yml
  Packs/FiltersAndTransformers/Scripts/DT/Pipfile
  Packs/FiltersAndTransformers/Scripts/DT/Pipfile.lock
  Packs/FiltersAndTransformers/Scripts/DT/README.md
  Packs/FiltersAndTransformers/Scripts/DateStringToISOFormat/DateStringToISOFormat.py
  Packs/FiltersAndTransformers/Scripts/DateStringToISOFormat/DateStringToISOFormat.yml
  Packs/FiltersAndTransformers/Scripts/DateStringToISOFormat/DateStringToISOFormat_test.py
  Packs/FiltersAndTransformers/Scripts/DateStringToISOFormat/README.md
  Packs/FiltersAndTransformers/TestPlaybooks/playbook-CutTransformerTest.yml
  Packs/FiltersAndTransformers/pack_metadata.json
Labels: docs-approved, ForceMerge

#23713 Set timeout for install packs on XSIAM - Hot Fix
  Tests/Marketplace/search_and_install_packs.py
Labels: docs-approved

#23364 Xdr close incident with resolve comment only
  Packs/ApiModules/Scripts/CoreIRApiModule/CoreIRApiModule.py
  Packs/ApiModules/Scripts/CoreIRApiModule/CoreIRApiModule_test.py
  Packs/Core/ReleaseNotes/1_3_24.md
  Packs/Core/pack_metadata.json
  Packs/CortexXDR/ReleaseNotes/4_9_19.md
  Packs/CortexXDR/pack_metadata.json
Labels: docs-approved

#23612 Microsoft Graph API - add support in credential store
  Packs/MicrosoftGraphAPI/.pack-ignore
  Packs/MicrosoftGraphAPI/Integrations/MicrosoftGraphAPI/MicrosoftGraphAPI.py
  Packs/MicrosoftGraphAPI/Integrations/MicrosoftGraphAPI/MicrosoftGraphAPI.yml
  Packs/MicrosoftGraphAPI/ReleaseNotes/1_1_6.md
  Packs/MicrosoftGraphAPI/pack_metadata.json
Labels: docs-approved

#23702 Adding comment to qradar query param
  Packs/QRadar/Integrations/QRadar_v3/QRadar_v3.yml
  Packs/QRadar/Integrations/QRadar_v3/README.md
  Packs/QRadar/ReleaseNotes/2_4_5.md
  Packs/QRadar/pack_metadata.json
Labels: docs-approved

#23677 Add Stored Credentials Support to Shodan_v2
  Packs/Shodan/.pack-ignore
  Packs/Shodan/Integrations/Shodan_v2/Shodan_v2.py
  Packs/Shodan/Integrations/Shodan_v2/Shodan_v2.yml
  Packs/Shodan/ReleaseNotes/1_1_6.md
  Packs/Shodan/TestPlaybooks/playbook-Test_shodan_v2.yml
  Packs/Shodan/pack_metadata.json
Labels: docs-approved

#23727 Fix commit update in index.json
  Tests/Marketplace/upload_packs.py
Labels: docs-approved

#23710 Slackv2 fix asyncio + Deprecate
  Packs/Slack/Integrations/Slack/README.md
  Packs/Slack/Integrations/Slack/Slack.py
  Packs/Slack/Integrations/Slack/Slack.yml
  Packs/Slack/Integrations/Slack/Slack_description.md
  Packs/Slack/ReleaseNotes/3_1_18.md
  Packs/Slack/pack_metadata.json
Labels: docs-approved

#23609 Microsoft Graph Security - add support in credential store
  Packs/MicrosoftGraphSecurity/.pack-ignore
  Packs/MicrosoftGraphSecurity/Integrations/MicrosoftGraphSecurity/MicrosoftGraphSecurity.py
  Packs/MicrosoftGraphSecurity/Integrations/MicrosoftGraphSecurity/MicrosoftGraphSecurity.yml
  Packs/MicrosoftGraphSecurity/ReleaseNotes/2_1_10.md
  Packs/MicrosoftGraphSecurity/pack_metadata.json
Labels: docs-approved

#23605 JsonWhoIs - add support in credential store
  Packs/JsonWhoIs/.pack-ignore
  Packs/JsonWhoIs/Integrations/JsonWhoIs/JsonWhoIs.py
  Packs/JsonWhoIs/Integrations/JsonWhoIs/JsonWhoIs.yml
  Packs/JsonWhoIs/ReleaseNotes/1_0_18.md
  Packs/JsonWhoIs/pack_metadata.json
Labels: docs-approved

#23571 Dig [Common Scripts Utility Consolidations]
  Packs/CommonScripts/ReleaseNotes/1_10_45.md
  Packs/CommonScripts/Scripts/Dig/Dig.py
  Packs/CommonScripts/Scripts/Dig/Dig.yml
  Packs/CommonScripts/Scripts/Dig/Dig_test.py
  Packs/CommonScripts/Scripts/Dig/README.md
  Packs/CommonScripts/pack_metadata.json
  Packs/Dig/ReleaseNotes/1_1_1.json
  Packs/Dig/ReleaseNotes/1_1_1.md
  Packs/Dig/Scripts/Dig/Pipfile
  Packs/Dig/Scripts/Dig/Pipfile.lock
  Packs/Dig/pack_metadata.json
  Tests/known_words.txt
Labels: docs-approved, ForceMerge

#23599 AlienVault OTX TAXII Feed - add support in credential store
  Packs/FeedAlienVault/.pack-ignore
  Packs/FeedAlienVault/Integrations/FeedAlienVaultOTXTaxii/FeedAlienVaultOTXTaxii.py
  Packs/FeedAlienVault/Integrations/FeedAlienVaultOTXTaxii/FeedAlienVaultOTXTaxii.yml
  Packs/FeedAlienVault/ReleaseNotes/1_1_25.md
  Packs/FeedAlienVault/pack_metadata.json
Labels: docs-approved

#23705 Expanse retries
  Packs/ExpanseV2/Integrations/ExpanseV2/ExpanseV2.py
  Packs/ExpanseV2/ReleaseNotes/1_10_25.md
  Packs/ExpanseV2/pack_metadata.json
Labels: docs-approved

#23739 Crowd strike falcon x renaming more fixes
  Packs/CrowdStrikeFalconX/Playbooks/Detonate_File_-_CrowdStrike_Falcon_X.yml
  Packs/CrowdStrikeFalconX/Playbooks/Detonate_URL_-_CrowdStrike_Falcon_X.yml
  Packs/CrowdStrikeFalconX/Playbooks/Detonate_URL_-_CrowdStrike_Falcon_X_README.md
  Packs/CrowdStrikeFalconX/Playbooks/playbook-FalconX_Detonate_and_Analyze_File_README.md
  Packs/CrowdStrikeFalconX/README.md
  Packs/CrowdStrikeFalconX/ReleaseNotes/1_2_18.md
  Packs/CrowdStrikeFalconX/TestPlaybooks/CrowdStrike_Falcon_X_-Test-Detonate_File.yml
  Packs/CrowdStrikeFalconX/pack_metadata.json
Labels: docs-approved

#23743 Added get_tenant_info-command
  Packs/CortexXDR/Integrations/CortexXDRIR/CortexXDRIR.py
  Packs/CortexXDR/Integrations/CortexXDRIR/CortexXDRIR.yml
  Packs/CortexXDR/Integrations/CortexXDRIR/CortexXDRIR_test.py
  Packs/CortexXDR/Integrations/CortexXDRIR/README.md
  Packs/CortexXDR/Integrations/CortexXDRIR/command_examples
  Packs/CortexXDR/Integrations/CortexXDRIR/test_data/get_tenant_info.json
Labels: Contribution, Contribution Form Filled, Community

#23514 MicrosoftGraphMail - add support in credential store
  Packs/MicrosoftGraphMail/.pack-ignore
  Packs/MicrosoftGraphMail/Integrations/MicrosoftGraphMail/MicrosoftGraphMail.py
  Packs/MicrosoftGraphMail/Integrations/MicrosoftGraphMail/MicrosoftGraphMail.yml
  Packs/MicrosoftGraphMail/ReleaseNotes/1_4_2.md
  Packs/MicrosoftGraphMail/pack_metadata.json
Labels: docs-approved

#23744 Add campaign to mitre
  Packs/FeedMitreAttackv2/Integrations/FeedMitreAttackv2/FeedMitreAttackv2.py
  Packs/FeedMitreAttackv2/Integrations/FeedMitreAttackv2/FeedMitreAttackv2_test.py
  Packs/FeedMitreAttackv2/ReleaseNotes/1_1_7.md
  Packs/FeedMitreAttackv2/pack_metadata.json
Labels: docs-approved

#23522 Smime_sign_regional_characters
  Packs/FiltersAndTransformers/.pack-ignore
  Packs/SMIME_Messaging/Integrations/SMIME_Messaging/SMIME_Messaging.py
  Packs/SMIME_Messaging/Integrations/SMIME_Messaging/SMIME_Messaging.yml
  Packs/SMIME_Messaging/ReleaseNotes/1_0_8.md
  Packs/SMIME_Messaging/pack_metadata.json
Labels: Contribution, pending-demo, Contribution Form Filled, Community, pending-contributor
