Repository demisto/content, pull requests merged in 2023-03, with the labels that each got.

#24940 SEKOIAIntelligenceCenter: change DevEmails
  Packs/SEKOIAIntelligenceCenter/pack_metadata.json
Labels: Contribution, docs-approved, Partner, Contribution Form Filled

#24963 fixup fromVersion for InfobloxBloxOneThreatDefense
  Packs/InfobloxBloxOne/Integrations/InfobloxBloxOneThreatDefense/InfobloxBloxOneThreatDefense.yml
Labels: docs-approved

#24715 EWS V2 Params Bug
  Packs/MicrosoftExchangeOnPremise/Integrations/EWSv2/EWSv2.py
  Packs/MicrosoftExchangeOnPremise/Integrations/EWSv2/EWSv2.yml
  Packs/MicrosoftExchangeOnPremise/Integrations/EWSv2/EWSv2_test.py
  Packs/MicrosoftExchangeOnPremise/Integrations/EWSv2/README.md
  Packs/MicrosoftExchangeOnPremise/ReleaseNotes/1_0_3.md
  Packs/MicrosoftExchangeOnPremise/TestPlaybooks/playbook-EWS-V2-send-mail-Test.yml
  Packs/MicrosoftExchangeOnPremise/TestPlaybooks/playbook-Send-Email-To-Recipients-Test.yml
  Packs/MicrosoftExchangeOnPremise/pack_metadata.json
Labels: docs-approved

#24948 Microsoft cas docs fix
  Packs/MicrosoftCloudAppSecurity/Integrations/MicrosoftCloudAppSecurity/MicrosoftCloudAppSecurity.yml
  Packs/MicrosoftCloudAppSecurity/Integrations/MicrosoftCloudAppSecurity/README.md
  Packs/MicrosoftCloudAppSecurity/ReleaseNotes/2_1_24.md
  Packs/MicrosoftCloudAppSecurity/pack_metadata.json
Labels: docs-approved

#24949 Zpa fixes
  Packs/ZscalerZPA/ModelingRules/ZscalerZPA_1_3/ZscalerZPA_1_3.xif
  Packs/ZscalerZPA/ModelingRules/ZscalerZPA_1_3/ZscalerZPA_1_3_schema.json
  Packs/ZscalerZPA/ReleaseNotes/1_0_6.md
  Packs/ZscalerZPA/pack_metadata.json
Labels: docs-approved

#24965 Search incidents bug
  Packs/CommonScripts/ReleaseNotes/1_11_39.md
  Packs/CommonScripts/Scripts/SearchIncidentsV2/SearchIncidentsV2.py
  Packs/CommonScripts/Scripts/SearchIncidentsV2/SearchIncidentsV2_test.py
  Packs/CommonScripts/pack_metadata.json
Labels: docs-approved

#24966 Proofpoint protection server: update README (typo)
  Packs/ProofpointServerProtection/Integrations/ProofpointProtectionServerV2/README.md
Labels: docs-approved

#24941 Change the pack category Messaging to Messaging and Conferencing part 2
  Packs/ActiveMQ/Integrations/ActiveMQ/ActiveMQ.yml
  Packs/ActiveMQ/ReleaseNotes/1_1_13.md
  Packs/ActiveMQ/pack_metadata.json
  Packs/CiscoSpark/.pack-ignore
  Packs/CiscoSpark/Integrations/CiscoSpark/CiscoSpark.yml
  Packs/CiscoSpark/Integrations/CiscoSpark/README.md
  Packs/CiscoSpark/ReleaseNotes/1_0_2.md
  Packs/CiscoSpark/pack_metadata.json
  Packs/GooglePubSub/Integrations/GooglePubSub/GooglePubSub.yml
  Packs/GooglePubSub/ReleaseNotes/1_0_26.md
  Packs/GooglePubSub/pack_metadata.json
  Tests/Marketplace/approved_categories.json
  Tests/scripts/infrastructure_tests/tests_data/RN_tests_data/FakePack5/Integrations/fake_integration.yml
  Tests/scripts/infrastructure_tests/tests_data/fake_integration.yml
  Tests/scripts/infrastructure_tests/tests_data/fake_integration/fake_integration.yml
  Tests/scripts/infrastructure_tests/tests_data/mock_integrations/fake_integration.yml
  Tests/scripts/infrastructure_tests/tests_data/mock_integrations/fake_integration/fake_integration.yml
  Tests/scripts/infrastructure_tests/tests_data/mock_integrations/future_integration_1.yml
  Tests/scripts/infrastructure_tests/tests_data/mock_integrations/future_integration_2.yml
  Tests/scripts/infrastructure_tests/tests_data/mock_integrations/past_integration_1.yml
  Tests/scripts/infrastructure_tests/tests_data/mock_integrations/skipped_integration_1.yml
  Tests/scripts/infrastructure_tests/tests_data/mock_integrations/skipped_test_integration_1.yml
  Tests/scripts/infrastructure_tests/tests_data/mock_integrations/test_fake_integration.yml
  Tests/setup/integration-test.yml
Labels: docs-approved, ForceMerge

#24886 InsightVM / Nexpose Bugfixes
  Packs/Rapid7_Nexpose/Integrations/Rapid7_Nexpose/Rapid7_Nexpose.py
  Packs/Rapid7_Nexpose/Integrations/Rapid7_Nexpose/Rapid7_Nexpose.yml
  Packs/Rapid7_Nexpose/Integrations/Rapid7_Nexpose/Rapid7_Nexpose_test.py
  Packs/Rapid7_Nexpose/Integrations/Rapid7_Nexpose/test_data/api_mock/client_get_site_assets.json
  Packs/Rapid7_Nexpose/Integrations/Rapid7_Nexpose/test_data/expected_post_data/start_site_scan_command.json
  Packs/Rapid7_Nexpose/ReleaseNotes/1_2_4.md
  Packs/Rapid7_Nexpose/pack_metadata.json
Labels: docs-approved

#24845 tenable_io
  Packs/Tenable_io/.secrets-ignore
  Packs/Tenable_io/Integrations/Tenable_io/README.md
  Packs/Tenable_io/Integrations/Tenable_io/Tenable_io.py
  Packs/Tenable_io/Integrations/Tenable_io/Tenable_io.yml
  Packs/Tenable_io/Integrations/Tenable_io/Tenable_io_test.py
  Packs/Tenable_io/Integrations/Tenable_io/test_data/response_and_results.py
  Packs/Tenable_io/ReleaseNotes/2_1_4.md
  Packs/Tenable_io/TestPlaybooks/playbook-Tenable.io_Scan_Test.yml
  Packs/Tenable_io/TestPlaybooks/playbook-Tenable.io_test.yml
  Packs/Tenable_io/pack_metadata.json
  Tests/conf.json
Labels: docs-approved

#24944 [CommonServerPython] `urlRegex` Fix
  Packs/Base/ReleaseNotes/1_31_69.md
  Packs/Base/Scripts/CommonServerPython/CommonServerPython.py
  Packs/Base/Scripts/CommonServerPython/CommonServerPython_test.py
  Packs/Base/pack_metadata.json
Labels: docs-approved

#24967 fix fetch-incidents bug
  Packs/Exabeam/Integrations/Exabeam/Exabeam.py
  Packs/Exabeam/Integrations/Exabeam/Exabeam.yml
  Packs/Exabeam/Integrations/Exabeam/test_data/response_incidents.py
  Packs/Exabeam/ReleaseNotes/2_2_3.md
  Packs/Exabeam/pack_metadata.json
Labels: docs-approved

#24969 always sync buckets
  .gitlab/ci/bucket-upload.yml
Labels: docs-approved

#24719 Reintroduce the `Email` pack category
  Packs/MicrosoftExchangeOnPremise/Integrations/EWSv2/EWSv2.yml
  Packs/MicrosoftExchangeOnPremise/ReleaseNotes/1_0_3.md
  Packs/MicrosoftExchangeOnPremise/ReleaseNotes/1_0_4.md
  Packs/MicrosoftExchangeOnPremise/pack_metadata.json
  Packs/MicrosoftExchangeOnline/Integrations/EWSO365/EWSO365.yml
  Packs/MicrosoftExchangeOnline/Integrations/EwsExtension/EwsExtension.yml
  Packs/MicrosoftExchangeOnline/Integrations/EwsExtensionEXOPowershellV2/EwsExtensionEXOPowershellV2.yml
  Packs/MicrosoftExchangeOnline/ReleaseNotes/1_1_1.md
  Packs/MicrosoftExchangeOnline/TestPlaybooks/O365-EWS-Extension-Powershell-Online-V2-Test.yml
  Packs/MicrosoftExchangeOnline/TestPlaybooks/playbook-EWS_O365_Extension_test.yml
  Packs/MicrosoftExchangeOnline/pack_metadata.json
  Packs/MicrosoftGraphFiles/Integrations/MicrosoftGraphFiles/MicrosoftGraphFiles.yml
  Packs/MicrosoftGraphFiles/ReleaseNotes/1_1_11.md
  Packs/MicrosoftGraphFiles/pack_metadata.json
  Packs/Mimecast/Integrations/MimecastEventCollector/MimecastEventCollector.py
  Packs/Mimecast/Integrations/MimecastEventCollector/MimecastEventCollector.yml
  Packs/Mimecast/Integrations/MimecastV2/MimecastV2.yml
  Packs/Mimecast/ReleaseNotes/2_1_6.md
  Packs/Mimecast/pack_metadata.json
  Packs/PerceptionPoint/Integrations/PerceptionPoint/PerceptionPoint.yml
  Packs/PerceptionPoint/ReleaseNotes/1_0_5.md
  Packs/PerceptionPoint/pack_metadata.json
  Packs/ProofpointTAP/Integrations/ProofpointTAP_v2/ProofpointTAP_v2.yml
  Packs/ProofpointTAP/ReleaseNotes/1_2_1.md
  Packs/ProofpointTAP/pack_metadata.json
  Packs/Symantec_Messaging_Gateway/Integrations/SymantecMessagingGateway/SymantecMessagingGateway.yml
  Packs/Symantec_Messaging_Gateway/ReleaseNotes/1_0_12.md
  Packs/Symantec_Messaging_Gateway/pack_metadata.json
  Tests/conf.json
Labels: docs-approved

#24976 Add keywords
  Packs/AWS-AccessAnalyzer/pack_metadata.json
  Packs/AWS-SQS/pack_metadata.json
  Packs/AWS-SecurityHub/pack_metadata.json
  Packs/AzureDevOps/pack_metadata.json
  Packs/AzureStorageQueue/pack_metadata.json
  Packs/Gmail/pack_metadata.json
  Packs/GmailSingleUser/pack_metadata.json
Labels: docs-approved

#24987 Fix EWS Mail Sender release notes
  Packs/EWSMailSender/ReleaseNotes/1_1_18.md
  Packs/EWSMailSender/ReleaseNotes/1_2_0.md
Labels: docs-approved

#24528 Microsoft Sentinel - Enhancement
  Packs/AzureSentinel/.pack-ignore
  Packs/AzureSentinel/Classifiers/classifier-Microsoft_Sentinel_-_Classifier.json
  Packs/AzureSentinel/Classifiers/classifier-Microsoft_Sentinel_-_Incoming_Mapper.json
  Packs/AzureSentinel/Classifiers/classifier-Microsoft_Sentinel_-_Outgoing_Mapper.json
  Packs/AzureSentinel/IncidentFields/incidentfield-Microsoft_Sentinel_Alert_Count.json
  Packs/AzureSentinel/IncidentFields/incidentfield-Microsoft_Sentinel_Alerts.json
  Packs/AzureSentinel/IncidentFields/incidentfield-Microsoft_Sentinel_Classification_Comment.json
  Packs/AzureSentinel/IncidentFields/incidentfield-Microsoft_Sentinel_Comments.json
  Packs/AzureSentinel/IncidentFields/incidentfield-Microsoft_Sentinel_Entities.json
  Packs/AzureSentinel/IncidentFields/incidentfield-Microsoft_Sentinel_Incident_Number.json
  Packs/AzureSentinel/IncidentFields/incidentfield-Microsoft_Sentinel_Owner.json
  Packs/AzureSentinel/IncidentFields/incidentfield-Microsoft_Sentinel_Relations.json
  Packs/AzureSentinel/IncidentFields/incidentfield-Microsoft_Sentinel_Rule_Id.json
  Packs/AzureSentinel/IncidentTypes/incidenttype-Microsoft_Sentinel_Incident.json
  Packs/AzureSentinel/Integrations/AzureSentinel/AzureSentinel.py
  Packs/AzureSentinel/Integrations/AzureSentinel/AzureSentinel.yml
  Packs/AzureSentinel/Integrations/AzureSentinel/AzureSentinel_image.png
  Packs/AzureSentinel/Integrations/AzureSentinel/AzureSentinel_test.py
  Packs/AzureSentinel/Integrations/AzureSentinel/README.md
  Packs/AzureSentinel/Integrations/AzureSentinel/test_data/create_alert_rule-mock_response.json
  Packs/AzureSentinel/Integrations/AzureSentinel/test_data/expected_alerts.json
  Packs/AzureSentinel/Integrations/AzureSentinel/test_data/expected_entities.json
  Packs/AzureSentinel/Integrations/AzureSentinel/test_data/expected_watchlist_items.json
  Packs/AzureSentinel/Integrations/AzureSentinel/test_data/expected_watchlists.json
  Packs/AzureSentinel/Integrations/AzureSentinel/test_data/get_alert_rule-mock_response.json
  Packs/AzureSentinel/Integrations/AzureSentinel/test_data/get_alert_rule_template-mock_response.json
  Packs/AzureSentinel/Integrations/AzureSentinel/test_data/list_alert_rule-mock_response.json
  Packs/AzureSentinel/Integrations/AzureSentinel/test_data/list_alert_rule_template-mock_response.json
  Packs/AzureSentinel/Layouts/layoutscontainer-Microsoft_Sentinel.json
  Packs/AzureSentinel/ReleaseNotes/1_5_0.md
  Packs/AzureSentinel/Scripts/MicrosoftSentinelConvertAlertsToTable/MicrosoftSentinelConvertAlertsToTable.py
  Packs/AzureSentinel/Scripts/MicrosoftSentinelConvertAlertsToTable/MicrosoftSentinelConvertAlertsToTable.yml
  Packs/AzureSentinel/Scripts/MicrosoftSentinelConvertAlertsToTable/MicrosoftSentinelConvertAlertsToTable_test.py
  Packs/AzureSentinel/Scripts/MicrosoftSentinelConvertAlertsToTable/README.md
  Packs/AzureSentinel/Scripts/MicrosoftSentinelConvertCommentsToTable/MicrosoftSentinelConvertCommentsToTable.py
  Packs/AzureSentinel/Scripts/MicrosoftSentinelConvertCommentsToTable/MicrosoftSentinelConvertCommentsToTable.yml
  Packs/AzureSentinel/Scripts/MicrosoftSentinelConvertCommentsToTable/MicrosoftSentinelConvertCommentsToTable_test.py
  Packs/AzureSentinel/Scripts/MicrosoftSentinelConvertCommentsToTable/README.md
  Packs/AzureSentinel/Scripts/MicrosoftSentinelConvertEntitiesToTable/MicrosoftSentinelConvertEntitiesToTable.py
  Packs/AzureSentinel/Scripts/MicrosoftSentinelConvertEntitiesToTable/MicrosoftSentinelConvertEntitiesToTable.yml
  Packs/AzureSentinel/Scripts/MicrosoftSentinelConvertEntitiesToTable/MicrosoftSentinelConvertEntitiesToTable_test.py
  Packs/AzureSentinel/Scripts/MicrosoftSentinelConvertEntitiesToTable/README.md
  Packs/AzureSentinel/Scripts/MicrosoftSentinelConvertRelationsToTable/MicrosoftSentinelConvertRelationsToTable.py
  Packs/AzureSentinel/Scripts/MicrosoftSentinelConvertRelationsToTable/MicrosoftSentinelConvertRelationsToTable.yml
  Packs/AzureSentinel/Scripts/MicrosoftSentinelConvertRelationsToTable/MicrosoftSentinelConvertRelationsToTable_test.py
  Packs/AzureSentinel/Scripts/MicrosoftSentinelConvertRelationsToTable/README.md
  Packs/AzureSentinel/pack_metadata.json
  Packs/CommonTypes/IncidentFields/incidentfield-Closing_Reason.json
  Packs/CommonTypes/IncidentFields/incidentfield-Last_Seen.json
  Packs/CommonTypes/IncidentFields/incidentfield-Last_Update_Time.json
  Packs/CommonTypes/IncidentFields/incidentfield-Resource_ID.json
  Packs/CommonTypes/IncidentFields/incidentfield-Source_Id.json
  Packs/CommonTypes/IncidentFields/incidentfield-Start_Time.json
  Packs/CommonTypes/IncidentFields/incidentfield-Vendor_Product.json
  Packs/CommonTypes/ReleaseNotes/3_3_52.md
  Packs/CommonTypes/pack_metadata.json
Labels: docs-approved

#24988 Tenable.io pack readme
  Packs/Tenable_io/README.md
Labels: docs-approved

#24945 ScheduleGenericPolling
  Packs/CommonScripts/ReleaseNotes/1_11_40.md
  Packs/CommonScripts/Scripts/ScheduleGenericPolling/ScheduleGenericPolling.py
  Packs/CommonScripts/Scripts/ScheduleGenericPolling/ScheduleGenericPolling.yml
  Packs/CommonScripts/pack_metadata.json
Labels: docs-approved

#24993 [Tests] Office365_Feed_Test - memory threshold increase
  Tests/conf.json
Labels: docs-approved

#24971 stabilize_rasterize_coverage
  Packs/rasterize/Integrations/rasterize/rasterize.py
  Packs/rasterize/Integrations/rasterize/rasterize.yml
  Packs/rasterize/ReleaseNotes/1_2_17.md
  Packs/rasterize/pack_metadata.json
Labels: docs-approved

#24991 [Tests] Microsoft Defender Advanced Threat Protection - Test - increase test timeout
  Tests/conf.json
Labels: docs-approved

#24735 Lock cloud machines
  .gitlab/ci/bucket-upload.yml
  .gitlab/ci/on-push.yml
  Tests/scripts/infrastructure_tests/lock_cloud_machines_test.py
  Tests/scripts/lock_cloud_machines.py
  Tests/scripts/wait_in_line_for_cloud_env.sh
Labels: docs-approved

#25025 Fix core layout
  Packs/Core/Layouts/layoutscontainer-Default.json
  Packs/Core/Layouts/layoutscontainer-Default_XDR_Alert.json
  Packs/Core/ReleaseNotes/1_3_36.md
  Packs/Core/pack_metadata.json
Labels: ForceMerge

#25009 [ASM] Expander - Remediation Guidance - February
  Packs/CortexAttackSurfaceManagement/.pack-ignore
  Packs/CortexAttackSurfaceManagement/.secrets-ignore
  Packs/CortexAttackSurfaceManagement/Lists/list-RemediationGuidance.json
  Packs/CortexAttackSurfaceManagement/ReleaseNotes/1_5_5.md
  Packs/CortexAttackSurfaceManagement/pack_metadata.json
Labels: Contribution, docs-approved, Contribution Form Filled, Community

#23601 Jb adding sections phase1
  Packs/Active_Directory_Query/Integrations/Active_Directory_Query/Active_Directory_Query.yml
  Packs/Active_Directory_Query/ReleaseNotes/1_6_7.md
  Packs/Active_Directory_Query/pack_metadata.json
  Packs/PAN-OS/Integrations/Panorama/Panorama.yml
  Packs/PAN-OS/ReleaseNotes/1_16_11.md
  Packs/PAN-OS/pack_metadata.json
  Tests/conf.json
Labels: docs-approved

#24285 Ne Prisma Cloud Compute Audit Playbook
  Packs/PrismaCloudCompute/.pack-ignore
  Packs/PrismaCloudCompute/IncidentFields/incidentfield-PCC_Defender_Logs.json
  Packs/PrismaCloudCompute/IncidentFields/incidentfield-Prisma_Audit_Table.json
  Packs/PrismaCloudCompute/IncidentFields/incidentfield-Prisma_Cloud_Compute_Defender_Logs.json
  Packs/PrismaCloudCompute/IncidentFields/incidentfield-Prisma_Cloud_Compute_FQDN.json
  Packs/PrismaCloudCompute/IncidentFields/incidentfield-Prisma_Cloud_Compute_Host.json
  Packs/PrismaCloudCompute/IncidentFields/incidentfield-Prisma_Cloud_Compute_Image.json
  Packs/PrismaCloudCompute/IncidentFields/incidentfield-Prisma_Cloud_Compute_Raw_Alert_JSON.json
  Packs/PrismaCloudCompute/IncidentTypes/incidenttype-Prisma_Cloud_Compute_Audit_v2.json
  Packs/PrismaCloudCompute/Integrations/PaloAltoNetworks_PrismaCloudCompute/PaloAltoNetworks_PrismaCloudCompute.yml
  Packs/PrismaCloudCompute/Layouts/layoutscontainer-Prisma_Cloud_Compute_Audit_Layout_v2.json
  Packs/PrismaCloudCompute/Layouts/layoutscontainer-Prisma_Cloud_Compute_Compliance.json
  Packs/PrismaCloudCompute/Playbooks/Prisma_Cloud_Compute_-_Audit_Alert_v2.yml
  Packs/PrismaCloudCompute/ReleaseNotes/1_3_2.md
  Packs/PrismaCloudCompute/Scripts/CreatePrismaCloudComputeComplianceReportButton/CreatePrismaCloudComputeComplianceReportButton.py
  Packs/PrismaCloudCompute/Scripts/CreatePrismaCloudComputeComplianceReportButton/CreatePrismaCloudComputeComplianceReportButton.yml
  Packs/PrismaCloudCompute/Scripts/CreatePrismaCloudComputeComplianceReportButton/README.md
  Packs/PrismaCloudCompute/Scripts/CreatePrismaCloudComputeLink/CreatePrismaCloudComputeLink.py
  Packs/PrismaCloudCompute/Scripts/CreatePrismaCloudComputeLink/CreatePrismaCloudComputeLink.yml
  Packs/PrismaCloudCompute/Scripts/CreatePrismaCloudComputeLink/README.md
  Packs/PrismaCloudCompute/Scripts/TagIndicatorButton/README.md
  Packs/PrismaCloudCompute/Scripts/TagIndicatorButton/TagIndicatorButton.py
  Packs/PrismaCloudCompute/Scripts/TagIndicatorButton/TagIndicatorButton.yml
  Packs/PrismaCloudCompute/TestPlaybooks/playbook-PaloAltoNetworks_PrismaCloudCompute-Test.yml
  Packs/PrismaCloudCompute/pack_metadata.json
Labels: Contribution, docs-approved, Contribution Form Filled, Community, pending-contributor

#25049 fix-failur-TestPlaybook(XDR)
  Tests/conf.json
Labels: docs-approved

#24999 [Fire eye central management] Adding sections
  Packs/FireEyeCM/Integrations/FireEyeCM/FireEyeCM.yml
  Packs/FireEyeCM/ReleaseNotes/1_1_19.md
  Packs/FireEyeCM/pack_metadata.json
Labels: docs-approved

#25000 [Fire eye email security (ex)] Adding sections
  Packs/FireEyeEX/Integrations/FireEyeEX/FireEyeEX.yml
  Packs/FireEyeEX/ReleaseNotes/2_0_13.md
  Packs/FireEyeEX/pack_metadata.json
Labels: docs-approved

#25001 [Fire eye hx] Adding sections
  Packs/FireEyeHX/Integrations/FireEyeHXv2/FireEyeHXv2.yml
  Packs/FireEyeHX/ReleaseNotes/2_3_3.md
  Packs/FireEyeHX/pack_metadata.json
Labels: docs-approved

#25003 Detonate URL - WildFire-v2 - Test - increase test timeout
  Tests/conf.json
Labels: docs-approved

#25004 CrowdStrike_Falcon_X_-Test-Detonate_URL - increasing timeout
  Tests/conf.json
Labels: docs-approved

#24869 update category to "Deception & Breach Simulation"
  Packs/AcalvioShadowplex/Integrations/acalvioapp/acalvioapp.yml
  Packs/AcalvioShadowplex/ReleaseNotes/1_0_10.md
  Packs/AcalvioShadowplex/pack_metadata.json
  Packs/AttivoBotsink/Integrations/AttivoBotsink/AttivoBotsink.yml
  Packs/AttivoBotsink/ReleaseNotes/1_0_11.md
  Packs/AttivoBotsink/pack_metadata.json
  Packs/CounterCraft/Integrations/CounterCraft/CounterCraft.yml
  Packs/CounterCraft/ReleaseNotes/1_0_8.md
  Packs/CounterCraft/pack_metadata.json
  Packs/Cymulate/Integrations/Cymulate/Cymulate.yml
  Packs/Cymulate/Integrations/Cymulate_v2/Cymulate_v2.yml
  Packs/Cymulate/ReleaseNotes/2_0_17.md
  Packs/Cymulate/pack_metadata.json
  Packs/Gophish/Integrations/Gophish/Gophish.py
  Packs/Gophish/Integrations/Gophish/Gophish.yml
  Packs/Gophish/ReleaseNotes/1_0_4.md
  Packs/Gophish/pack_metadata.json
  Packs/GuardiCore/Integrations/GuardiCore/GuardiCore.yml
  Packs/GuardiCore/Integrations/GuardiCoreV2/GuardiCoreV2.yml
  Packs/GuardiCore/ReleaseNotes/2_0_9.md
  Packs/GuardiCore/pack_metadata.json
  Packs/IllusiveNetworks/Integrations/IllusiveNetworks/IllusiveNetworks.yml
  Packs/IllusiveNetworks/ReleaseNotes/1_0_24.md
  Packs/IllusiveNetworks/pack_metadata.json
  Packs/RedCanary/Integrations/RedCanary/RedCanary.yml
  Packs/RedCanary/ReleaseNotes/1_1_12.md
  Packs/RedCanary/pack_metadata.json
  Packs/SafeBreach/Integrations/SafeBreach_v2/SafeBreach_v2.py
  Packs/SafeBreach/Integrations/SafeBreach_v2/SafeBreach_v2.yml
  Packs/SafeBreach/ReleaseNotes/1_1_16.md
  Packs/SafeBreach/pack_metadata.json
  Packs/Smokescreen_IllusionBLACK/Integrations/Smokescreen_IllusionBLACK/Smokescreen_IllusionBLACK.py
  Packs/Smokescreen_IllusionBLACK/Integrations/Smokescreen_IllusionBLACK/Smokescreen_IllusionBLACK.yml
  Packs/Smokescreen_IllusionBLACK/ReleaseNotes/1_0_13.md
  Packs/Smokescreen_IllusionBLACK/pack_metadata.json
  Packs/ThinkstCanary/.pack-ignore
  Packs/ThinkstCanary/Integrations/ThinkstCanary/ThinkstCanary.yml
  Packs/ThinkstCanary/ReleaseNotes/1_0_17.md
  Packs/ThinkstCanary/TestPlaybooks/playbook-CanaryTools_Test.yml
  Packs/ThinkstCanary/pack_metadata.json
  Tests/Marketplace/approved_categories.json
Labels: docs-approved

#24984 [PAN-OS] - enhance pan-os-get-pcap docs
  Packs/PAN-OS/Integrations/Panorama/Panorama.yml
  Packs/PAN-OS/Integrations/Panorama/README.md
  Packs/PAN-OS/ReleaseNotes/1_16_12.md
  Packs/PAN-OS/doc_files/application-pcap-api.png
  Packs/PAN-OS/doc_files/dlp-pcap-api.png
  Packs/PAN-OS/doc_files/fliter-pcap-api.png
  Packs/PAN-OS/doc_files/threat-pcap-api.png
  Packs/PAN-OS/pack_metadata.json
Labels: docs-approved

#24995 [FireEye Network Security (NX)] Adding sections
  Packs/FireEyeNX/Integrations/FireEyeNX/FireEyeNX.yml
  Packs/FireEyeNX/ReleaseNotes/1_1_17.md
  Packs/FireEyeNX/pack_metadata.json
Labels: docs-approved

#24690 Knowbe4 KMSAT integration pack
  Packs/KnowBe4KMSAT/.pack-ignore
  Packs/KnowBe4KMSAT/.secrets-ignore
  Packs/KnowBe4KMSAT/Author_image.png
  Packs/KnowBe4KMSAT/Integrations/KnowBe4KMSAT/KnowBe4KMSAT.py
  Packs/KnowBe4KMSAT/Integrations/KnowBe4KMSAT/KnowBe4KMSAT.yml
  Packs/KnowBe4KMSAT/Integrations/KnowBe4KMSAT/KnowBe4KMSAT_description.md
  Packs/KnowBe4KMSAT/Integrations/KnowBe4KMSAT/KnowBe4KMSAT_image.png
  Packs/KnowBe4KMSAT/Integrations/KnowBe4KMSAT/KnowBe4KMSAT_test.py
  Packs/KnowBe4KMSAT/Integrations/KnowBe4KMSAT/Pipfile
  Packs/KnowBe4KMSAT/Integrations/KnowBe4KMSAT/Pipfile.lock
  Packs/KnowBe4KMSAT/Integrations/KnowBe4KMSAT/README.md
  Packs/KnowBe4KMSAT/Integrations/KnowBe4KMSAT/command_examples
  Packs/KnowBe4KMSAT/Integrations/KnowBe4KMSAT/test_data/account_response.json
  Packs/KnowBe4KMSAT/Integrations/KnowBe4KMSAT/test_data/account_risk_score_history_response.json
  Packs/KnowBe4KMSAT/Integrations/KnowBe4KMSAT/test_data/groups_members_response.json
  Packs/KnowBe4KMSAT/Integrations/KnowBe4KMSAT/test_data/groups_risk_score_history_response.json
  Packs/KnowBe4KMSAT/Integrations/KnowBe4KMSAT/test_data/phishing_security_campaign_security_response.json
  Packs/KnowBe4KMSAT/Integrations/KnowBe4KMSAT/test_data/phishing_security_tests_failed_recipients_response.json
  Packs/KnowBe4KMSAT/Integrations/KnowBe4KMSAT/test_data/phishing_security_tests_recipients_response.json
  Packs/KnowBe4KMSAT/Integrations/KnowBe4KMSAT/test_data/phishing_security_tests_response.json
  Packs/KnowBe4KMSAT/Integrations/KnowBe4KMSAT/test_data/training_campaigns_response.json
  Packs/KnowBe4KMSAT/Integrations/KnowBe4KMSAT/test_data/training_enrollments_response.json
  Packs/KnowBe4KMSAT/Integrations/KnowBe4KMSAT/test_data/user_event_response.json
  Packs/KnowBe4KMSAT/Integrations/KnowBe4KMSAT/test_data/user_event_status_response.json
  Packs/KnowBe4KMSAT/Integrations/KnowBe4KMSAT/test_data/user_event_statuses_response.json
  Packs/KnowBe4KMSAT/Integrations/KnowBe4KMSAT/test_data/user_event_types_response.json
  Packs/KnowBe4KMSAT/Integrations/KnowBe4KMSAT/test_data/user_events_response.json
  Packs/KnowBe4KMSAT/Integrations/KnowBe4KMSAT/test_data/user_risk_score_history_response.json
  Packs/KnowBe4KMSAT/README.md
  Packs/KnowBe4KMSAT/pack_metadata.json
Labels: Contribution, Partner, Contribution Form Filled

#25063 Core Rest API fix default marketplace URL
  Packs/DemistoRESTAPI/Integrations/CoreRESTAPI/CoreRESTAPI.yml
  Packs/DemistoRESTAPI/Integrations/DemistoRESTAPI/DemistoRESTAPI.yml
  Packs/DemistoRESTAPI/ReleaseNotes/1_3_19.md
  Packs/DemistoRESTAPI/pack_metadata.json
Labels: docs-approved, ForceMerge

#25046 Fix from version SymantecEDR
  Packs/SymantecEDR/Classifiers/classifier-SymantecEDR_-_Incident_Classifier.json
  Packs/SymantecEDR/Classifiers/classifier-SymantecEDR_-_Incoming_Mapper.json
  Packs/SymantecEDR/IncidentFields/incidentfield-SymantecEDR_Actor_File.json
  Packs/SymantecEDR/IncidentFields/incidentfield-SymantecEDR_Actor_User.json
  Packs/SymantecEDR/IncidentFields/incidentfield-SymantecEDR_Enriched_Data.json
  Packs/SymantecEDR/IncidentFields/incidentfield-SymantecEDR_Event_Actor.json
  Packs/SymantecEDR/IncidentFields/incidentfield-SymantecEDR_Event_Process.json
  Packs/SymantecEDR/IncidentFields/incidentfield-SymantecEDR_Incident_Comments.json
  Packs/SymantecEDR/IncidentFields/incidentfield-SymantecEDR_Incident_Detection_type.json
  Packs/SymantecEDR/IncidentFields/incidentfield-SymantecEDR_Incident_Events.json
  Packs/SymantecEDR/IncidentFields/incidentfield-SymantecEDR_Process_File.json
  Packs/SymantecEDR/IncidentFields/incidentfield-SymantecEDR_Process_User.json
  Packs/SymantecEDR/IncidentFields/incidentfield-SymantecEDR_Recommended_Action.json
  Packs/SymantecEDR/IncidentFields/incidentfield-SymantecEDR_Rule_ID.json
  Packs/SymantecEDR/IncidentFields/incidentfield-SymantecEDR_attacks.json
  Packs/SymantecEDR/IncidentTypes/incidenttype-SymantecEDR_incident.json
  Packs/SymantecEDR/Integrations/SymantecEDR/SymantecEDR.yml
  Packs/SymantecEDR/Layouts/layoutscontainer-SymantecEDR_layout.json
  Packs/SymantecEDR/TestPlaybooks/playbook-SymantecEDR_Test.yml
Labels: docs-approved, ForceMerge

#25002 Changed the get_agent func logic to base on the platform only
  Packs/Palo_Alto_Networks_WildFire/Integrations/WildFireReports/WildFireReports.py
  Packs/Palo_Alto_Networks_WildFire/Integrations/WildFireReports/WildFireReports.yml
  Packs/Palo_Alto_Networks_WildFire/Integrations/WildFireReports/WildFireReports_test.py
  Packs/Palo_Alto_Networks_WildFire/ReleaseNotes/2_1_17.md
  Packs/Palo_Alto_Networks_WildFire/pack_metadata.json
Labels: docs-approved

#25053 Fix fetch-incidents occurred field MSGraphMail
  Packs/MicrosoftGraphMail/Integrations/MicrosoftGraphMail/MicrosoftGraphMail.py
  Packs/MicrosoftGraphMail/Integrations/MicrosoftGraphMail/MicrosoftGraphMail.yml
  Packs/MicrosoftGraphMail/Integrations/MicrosoftGraphMail/MicrosoftGraphMail_test.py
  Packs/MicrosoftGraphMail/ReleaseNotes/1_4_12.md
  Packs/MicrosoftGraphMail/pack_metadata.json
Labels: docs-approved

#25057 [MicrosoftSentinelConvertEntitiesToTable ] - Fix the script with json.loads
  Packs/AzureSentinel/ReleaseNotes/1_5_1.md
  Packs/AzureSentinel/Scripts/MicrosoftSentinelConvertAlertsToTable/MicrosoftSentinelConvertAlertsToTable.py
  Packs/AzureSentinel/Scripts/MicrosoftSentinelConvertAlertsToTable/MicrosoftSentinelConvertAlertsToTable_test.py
  Packs/AzureSentinel/Scripts/MicrosoftSentinelConvertCommentsToTable/MicrosoftSentinelConvertCommentsToTable.py
  Packs/AzureSentinel/Scripts/MicrosoftSentinelConvertCommentsToTable/MicrosoftSentinelConvertCommentsToTable_test.py
  Packs/AzureSentinel/Scripts/MicrosoftSentinelConvertEntitiesToTable/MicrosoftSentinelConvertEntitiesToTable.py
  Packs/AzureSentinel/Scripts/MicrosoftSentinelConvertEntitiesToTable/MicrosoftSentinelConvertEntitiesToTable_test.py
  Packs/AzureSentinel/Scripts/MicrosoftSentinelConvertRelationsToTable/MicrosoftSentinelConvertRelationsToTable.py
  Packs/AzureSentinel/Scripts/MicrosoftSentinelConvertRelationsToTable/MicrosoftSentinelConvertRelationsToTable_test.py
  Packs/AzureSentinel/pack_metadata.json
Labels: docs-approved

#24977 Fix PaloAltoNetworks_IoT-Test
  Packs/PaloAltoNetworks_IoT/Integrations/PaloAltoNetworks_IoT/PaloAltoNetworks_IoT.py
  Packs/PaloAltoNetworks_IoT/ReleaseNotes/1_0_21.md
  Packs/PaloAltoNetworks_IoT/TestPlaybooks/playbook-PaloAltoNetworks_IoT-Test.yml
  Packs/PaloAltoNetworks_IoT/pack_metadata.json
Labels: docs-approved

#24951 AzureRiskyUsers - Add filtering options
  Packs/AzureRiskyUsers/Integrations/AzureRiskyUsers/AzureRiskyUsers.py
  Packs/AzureRiskyUsers/Integrations/AzureRiskyUsers/AzureRiskyUsers.yml
  Packs/AzureRiskyUsers/Integrations/AzureRiskyUsers/AzureRiskyUsers_test.py
  Packs/AzureRiskyUsers/Integrations/AzureRiskyUsers/README.md
  Packs/AzureRiskyUsers/ReleaseNotes/1_1_11.md
  Packs/AzureRiskyUsers/pack_metadata.json
Labels: docs-approved

#24852 Change the pack category `Messaging` to `Messaging and Conferencing`
  Packs/ILert/Integrations/ILert/ILert.py
  Packs/ILert/Integrations/ILert/ILert.yml
  Packs/ILert/ReleaseNotes/1_0_5.md
  Packs/ILert/pack_metadata.json
  Packs/Kafka/Integrations/KafkaV3/KafkaV3.yml
  Packs/Kafka/ReleaseNotes/2_0_5.md
  Packs/Kafka/pack_metadata.json
  Packs/MailListener/Integrations/MailListenerV2/MailListenerV2.yml
  Packs/MailListener/ReleaseNotes/1_0_31.md
  Packs/MailListener/pack_metadata.json
  Packs/MicrosoftTeams/Integrations/MicrosoftTeams/MicrosoftTeams.yml
  Packs/MicrosoftTeams/Integrations/MicrosoftTeamsManagement/MicrosoftTeamsManagement.yml
  Packs/MicrosoftTeams/Integrations/MicrosoftTeamsWebhook/MicrosoftTeamsWebhook.yml
  Packs/MicrosoftTeams/ReleaseNotes/1_4_9.md
  Packs/MicrosoftTeams/pack_metadata.json
  Packs/PagerDuty/Integrations/PagerDuty/PagerDuty.py
  Packs/PagerDuty/Integrations/PagerDuty/PagerDuty.yml
  Packs/PagerDuty/ReleaseNotes/1_1_5.md
  Packs/PagerDuty/pack_metadata.json
  Packs/PostmarkSpamcheck/Integrations/PostmarkSpamcheck/PostmarkSpamcheck.py
  Packs/PostmarkSpamcheck/Integrations/PostmarkSpamcheck/PostmarkSpamcheck.yml
  Packs/PostmarkSpamcheck/ReleaseNotes/1_0_1.md
  Packs/PostmarkSpamcheck/pack_metadata.json
  Packs/SendGrid/Integrations/SendGrid/README.md
  Packs/SendGrid/Integrations/SendGrid/SendGrid.yml
  Packs/SendGrid/ReleaseNotes/1_1_1.md
  Packs/SendGrid/pack_metadata.json
  Packs/Slack/Integrations/SlackV3/SlackV3.yml
  Packs/Slack/ReleaseNotes/3_1_24.md
  Packs/Slack/pack_metadata.json
  Packs/Telegram/Integrations/Telegram/Telegram.py
  Packs/Telegram/Integrations/Telegram/Telegram.yml
  Packs/Telegram/ReleaseNotes/1_0_5.md
  Packs/Telegram/pack_metadata.json
  Packs/Twilio/Integrations/Twilio/README.md
  Packs/Twilio/Integrations/Twilio/Twilio.yml
  Packs/Twilio/ReleaseNotes/1_0_3.md
  Packs/Twilio/pack_metadata.json
  Packs/Zoom/Integrations/Zoom/Zoom.yml
  Packs/Zoom/ReleaseNotes/1_2_6.md
  Packs/Zoom/pack_metadata.json
Labels: docs-approved

#25043 Fix skyhigh security proxy issue
  Packs/SkyhighSecurity/Integrations/SkyhighSecurity/SkyhighSecurity.py
  Packs/SkyhighSecurity/ReleaseNotes/1_0_4.md
  Packs/SkyhighSecurity/pack_metadata.json
Labels: docs-approved

#25041 [NetskopeCollector] Support up to 30k events per type
  Packs/Netskope/Integrations/NetskopeEventCollector/NetskopeEventCollector.py
  Packs/Netskope/Integrations/NetskopeEventCollector/NetskopeEventCollector.yml
  Packs/Netskope/Integrations/NetskopeEventCollector/NetskopeEventCollector_test.py
  Packs/Netskope/Integrations/NetskopeEventCollector/README.md
  Packs/Netskope/Integrations/NetskopeEventCollector/test_data/events_raw_v2_2_results.json
  Packs/Netskope/ReleaseNotes/3_0_11.md
  Packs/Netskope/pack_metadata.json
Labels: docs-approved

#24701 IPQualityScore Encoding and Results Bug Fixes
  Packs/IPQualityScore/Integrations/IPQualityScore/IPQualityScore.py
  Packs/IPQualityScore/Integrations/IPQualityScore/IPQualityScore.yml
  Packs/IPQualityScore/Integrations/IPQualityScore/IPQualityScore_test.py
  Packs/IPQualityScore/ReleaseNotes/1_0_6.md
  Packs/IPQualityScore/pack_metadata.json
Labels: Contribution, docs-approved, Partner, Contribution Form Filled

#24930 EXPANDR-1614 Updating ServiceNow playbook
  Packs/ServiceNow/Playbooks/playbook-ServiceNow_CMDB_Search.yml
  Packs/ServiceNow/Playbooks/playbook-ServiceNow_CMDB_Search_README.md
  Packs/ServiceNow/ReleaseNotes/2_5_13.md
  Packs/ServiceNow/doc_files/ServiceNow_CMDB_Search.png
  Packs/ServiceNow/pack_metadata.json
Labels: Contribution, docs-approved, Contribution Form Filled, Community

#25051 Abnormal security fix array
  Packs/AbnormalSecurity/ModelingRules/AbnormalSecurityEventCollector_1_3/AbnormalSecurityEventCollector_1_3.xif
  Packs/AbnormalSecurity/ReleaseNotes/2_0_9.md
  Packs/AbnormalSecurity/pack_metadata.json
Labels: docs-approved, release-notes-only

#24985 adjustments to the pack categories
  Tests/Marketplace/approved_categories.json
Labels: docs-approved

#25066 Updated code points in the URL formatter
  Packs/CommonScripts/ReleaseNotes/1_11_41.md
  Packs/CommonScripts/Scripts/FormatURL/FormatURL.py
  Packs/CommonScripts/Scripts/FormatURL/FormatURL_test.py
  Packs/CommonScripts/pack_metadata.json
Labels: docs-approved

#25069 Increase Test XDR Playbook retrieve file command timeout
  Tests/conf.json
Labels: docs-approved

#25068 Increase EvaluateMLModllAtProduction-Test timeout
  Tests/conf.json
Labels: docs-approved

#24376 Mirroring AWS Security Hub
  Packs/AWS-SecurityHub/Classifiers/classifier-AWS_Security_Hub_-_Incoming_Mapper.json
  Packs/AWS-SecurityHub/Classifiers/classifier-AWS_Security_Hub_-_Outgoing_Mapper.json
  Packs/AWS-SecurityHub/IncidentFields/incidentfields-AWS_Security_Hub_Action.json
  Packs/AWS-SecurityHub/IncidentFields/incidentfields-AWS_Security_Hub_Company_Name.json
  Packs/AWS-SecurityHub/IncidentFields/incidentfields-AWS_Security_Hub_Compliance.json
  Packs/AWS-SecurityHub/IncidentFields/incidentfields-AWS_Security_Hub_Confidence.json
  Packs/AWS-SecurityHub/IncidentFields/incidentfields-AWS_Security_Hub_Criticality.json
  Packs/AWS-SecurityHub/IncidentFields/incidentfields-AWS_Security_Hub_Generator_Id.json
  Packs/AWS-SecurityHub/IncidentFields/incidentfields-AWS_Security_Hub_Malware.json
  Packs/AWS-SecurityHub/IncidentFields/incidentfields-AWS_Security_Hub_Network_Path.json
  Packs/AWS-SecurityHub/IncidentFields/incidentfields-AWS_Security_Hub_Product_Arn.json
  Packs/AWS-SecurityHub/IncidentFields/incidentfields-AWS_Security_Hub_Product_Fields.json
  Packs/AWS-SecurityHub/IncidentFields/incidentfields-AWS_Security_Hub_Product_Name.json
  Packs/AWS-SecurityHub/IncidentFields/incidentfields-AWS_Security_Hub_Provider_Fields.json
  Packs/AWS-SecurityHub/IncidentFields/incidentfields-AWS_Security_Hub_Provider_Updated_At.json
  Packs/AWS-SecurityHub/IncidentFields/incidentfields-AWS_Security_Hub_Record_State.json
  Packs/AWS-SecurityHub/IncidentFields/incidentfields-AWS_Security_Hub_Related_Findings.json
  Packs/AWS-SecurityHub/IncidentFields/incidentfields-AWS_Security_Hub_Remediation.json
  Packs/AWS-SecurityHub/IncidentFields/incidentfields-AWS_Security_Hub_Resources.json
  Packs/AWS-SecurityHub/IncidentFields/incidentfields-AWS_Security_Hub_Schema_Version.json
  Packs/AWS-SecurityHub/IncidentFields/incidentfields-AWS_Security_Hub_Severity.json
  Packs/AWS-SecurityHub/IncidentFields/incidentfields-AWS_Security_Hub_Threat_Intel_Indicators.json
  Packs/AWS-SecurityHub/IncidentFields/incidentfields-AWS_Security_Hub_Threats.json
  Packs/AWS-SecurityHub/IncidentFields/incidentfields-AWS_Security_Hub_Types.json
  Packs/AWS-SecurityHub/IncidentFields/incidentfields-AWS_Security_Hub_User_Defined_Fields.json
  Packs/AWS-SecurityHub/IncidentFields/incidentfields-AWS_Security_Hub_Verification_State.json
  Packs/AWS-SecurityHub/IncidentFields/incidentfields-AWS_Security_Hub_Vulnerabilities.json
  Packs/AWS-SecurityHub/IncidentFields/incidentfields-AWS_Security_Hub_Workflow_Status.json
  Packs/AWS-SecurityHub/IncidentTypes/incidenttype-AWS_Security_Hub.json
  Packs/AWS-SecurityHub/Integrations/AWS_SecurityHub/AWS_SecurityHub.py
  Packs/AWS-SecurityHub/Integrations/AWS_SecurityHub/AWS_SecurityHub.yml
  Packs/AWS-SecurityHub/Integrations/AWS_SecurityHub/AWS_SecurityHub_test.py
  Packs/AWS-SecurityHub/Integrations/AWS_SecurityHub/README.md
  Packs/AWS-SecurityHub/Layouts/layoutscontainer-AWS_Security_Hub_Finding.json
  Packs/AWS-SecurityHub/ReleaseNotes/1_2_0.md
  Packs/AWS-SecurityHub/pack_metadata.json
  Packs/CommonTypes/IncidentFields/incidentfield-Account_ID.json
  Packs/CommonTypes/IncidentFields/incidentfield-Alert_URL.json
  Packs/CommonTypes/IncidentFields/incidentfield-Detection_Update_Time.json
  Packs/CommonTypes/IncidentFields/incidentfield-Last_Update_Time.json
  Packs/CommonTypes/IncidentFields/incidentfield-Region.json
  Packs/CommonTypes/IncidentFields/incidentfield-Risk_Score.json
  Packs/CommonTypes/IncidentFields/incidentfield-Title.json
  Packs/CommonTypes/ReleaseNotes/3_3_52.md
  Packs/CommonTypes/ReleaseNotes/3_3_54.md
  Packs/CommonTypes/pack_metadata.json
Labels: docs-approved, ForceMerge

#25054 Retrieve File from Endpoint - Generic V2 Test - Replacing a deprecated integration
  Packs/Carbon_Black_Enterprise_Response/Playbooks/playbook-Get_binary_file_from_Carbon_Black_by_its_MD5_hash.yml
  Packs/Carbon_Black_Enterprise_Response/ReleaseNotes/2_1_29.md
  Packs/Carbon_Black_Enterprise_Response/TestPlaybooks/playbook-Carbon_Black_Response_Test.yml
  Packs/Carbon_Black_Enterprise_Response/pack_metadata.json
  Tests/conf.json
Labels: docs-approved

#25055 Use static CSV instead of downloading it from PhishTank API.
  Packs/PhishTank/TestPlaybooks/playbook-PhishTank-Test.yml
Labels: docs-approved

#25093 Fix incidentfield sumourl
  Packs/SumoLogic_Cloud_SIEM/IncidentFields/incidentfield-Sumo_Logic_Cloud_SIEM_Insight_Signals.json
  Packs/SumoLogic_Cloud_SIEM/ReleaseNotes/1_1_8.md
  Packs/SumoLogic_Cloud_SIEM/pack_metadata.json
Labels: docs-approved

#24992 Removing all packs that are not PANW from marketplace
  Tests/Marketplace/core_packs_list.json
  Tests/Marketplace/core_packs_mpv2_list.json
Labels: docs-approved

#25097 Test XDR Playbook execute script commands - increase test timeout
  Tests/conf.json
Labels: docs-approved

#25070 Fix ParseCSV context output
  Packs/CommonScripts/ReleaseNotes/1_11_41.md
  Packs/CommonScripts/ReleaseNotes/1_11_42.md
  Packs/CommonScripts/Scripts/ParseCSV/ParseCSV.py
  Packs/CommonScripts/Scripts/ParseCSV/ParseCSV.yml
  Packs/CommonScripts/Scripts/ParseCSV/ParseCSV_test.py
  Packs/CommonScripts/Scripts/ParseCSV/test_data/IOCs.csv
  Packs/CommonScripts/Scripts/ParseCSV/test_data/IOCs_results.json
  Packs/CommonScripts/Scripts/ParseCSV/test_data/empty.csv
  Packs/CommonScripts/Scripts/ParseCSV/test_data/empty_result.json
  Packs/CommonScripts/Scripts/ParseCSV/test_data/nullbytes.csv
  Packs/CommonScripts/Scripts/ParseCSV/test_data/nullbytes_results.json
  Packs/CommonScripts/Scripts/ParseCSV/test_data/one_is_hash.csv
  Packs/CommonScripts/Scripts/ParseCSV/test_data/one_is_hash_results.json
  Packs/CommonScripts/Scripts/ParseCSV/test_data/one_lined_csv.csv
  Packs/CommonScripts/Scripts/ParseCSV/test_data/one_lined_csv_results.json
  Packs/CommonScripts/Scripts/ParseCSV/test_data/simple.csv
  Packs/CommonScripts/Scripts/ParseCSV/test_data/simple_non_utf.csv
  Packs/CommonScripts/Scripts/ParseCSV/test_data/simple_non_utf_results.json
  Packs/CommonScripts/Scripts/ParseCSV/test_data/simple_results.json
  Packs/CommonScripts/pack_metadata.json
Labels: docs-approved

#25094 XSOAR Mirroring docs update
  Packs/XSOARmirroring/Integrations/XSOARmirroring/README.md
  Packs/XSOARmirroring/Integrations/XSOARmirroring/XSOARmirroring.yml
  Packs/XSOARmirroring/Integrations/XSOARmirroring/XSOARmirroring_description.md
  Packs/XSOARmirroring/Integrations/XSOARmirroring/command_examples
  Packs/XSOARmirroring/ReleaseNotes/2_0_13.md
  Packs/XSOARmirroring/pack_metadata.json
Labels: docs-approved

#25045 1.10.6
  .circleci/config.yml
  .gitlab/ci/.gitlab-ci.yml
  .gitlab/ci/global.yml
  poetry.lock
  pyproject.toml
Labels: docs-approved

#24812 Cloud iam user access investigation
  Packs/CommonPlaybooks/Playbooks/playbook-Cloud_IAM_Enrichment_-_Generic.yml
  Packs/CommonPlaybooks/Playbooks/playbook-Cloud_IAM_Enrichment_-_Generic_README.md
  Packs/CommonPlaybooks/ReleaseNotes/2_3_41.md
  Packs/CommonPlaybooks/doc_files/Cloud_IAM_Enrichment_-_Generic.png
  Packs/CommonPlaybooks/pack_metadata.json
  Packs/CortexXDR/Playbooks/Cortex_XDR_Alerts_Handling.yml
  Packs/CortexXDR/Playbooks/Cortex_XDR_Alerts_Handling_README.md
  Packs/CortexXDR/Playbooks/playbook-Cortex_XDR_-_Cloud_IAM_User_Access_Investigation.yml
  Packs/CortexXDR/Playbooks/playbook-Cortex_XDR_-_Cloud_IAM_User_Access_Investigation_README.md
  Packs/CortexXDR/ReleaseNotes/4_10_19.md
  Packs/CortexXDR/doc_files/Cortex_XDR_-_Cloud_IAM_User_Access_Investigation.png
  Packs/CortexXDR/doc_files/Cortex_XDR_Alerts_Handling.png
  Packs/CortexXDR/pack_metadata.json
Labels: docs-approved

#25098 Fixed IndexError when the URL ends with "\"
  Packs/CommonScripts/.pack-ignore
  Packs/CommonScripts/ReleaseNotes/1_11_43.md
  Packs/CommonScripts/Scripts/FormatURL/FormatURL.py
  Packs/CommonScripts/Scripts/FormatURL/FormatURL_test.py
  Packs/CommonScripts/pack_metadata.json
Labels: docs-approved

#25067 CommonServerPython remove "1" as a valid IP from URL regex
  Packs/Base/ReleaseNotes/1_31_70.md
  Packs/Base/Scripts/CommonServerPython/CommonServerPython.py
  Packs/Base/pack_metadata.json
Labels: docs-approved

#25114 Revert "adjustments to the pack categories (#24985)"
  Tests/Marketplace/approved_categories.json
Labels: docs-approved, ForceMerge

#24822 Enhancement block indicators generic v3
  Packs/CommonPlaybooks/Playbooks/playbook-Block_File_-_Generic_v2.yml
  Packs/CommonPlaybooks/Playbooks/playbook-Block_File_-_Generic_v2_README.md
  Packs/CommonPlaybooks/Playbooks/playbook-Block_Indicators_-_Generic_v3.yml
  Packs/CommonPlaybooks/Playbooks/playbook-Block_Indicators_-_Generic_v3_README.md
  Packs/CommonPlaybooks/ReleaseNotes/2_3_42.md
  Packs/CommonPlaybooks/doc_files/Block_Indicators_-_Generic_v3.png
  Packs/CommonPlaybooks/pack_metadata.json
Labels: docs-approved

#25118 Fixe README tags
  Packs/AWS-SecurityHub/Integrations/AWS_SecurityHub/README.md
Labels: docs-approved

#25122 symantec-edr-pack-name-change
  Packs/SymantecEDR/pack_metadata.json
Labels: docs-approved

#24858 Fixes For 'Cortex XDR - False Positive Incident Handling' playbook
  Packs/CortexXDR/.pack-ignore
  Packs/CortexXDR/Playbooks/playbook-Cortex_XDR_-_False_Positive_Incident_Handling.yml
  Packs/CortexXDR/Playbooks/playbook-Cortex_XDR_-_False_Positive_Incident_Handling_README.md
  Packs/CortexXDR/ReleaseNotes/4_10_20.md
  Packs/CortexXDR/pack_metadata.json
Labels: docs-approved

#25119 Change contribution form automatic message
  Utils/github_workflow_scripts/handle_external_pr.py
Labels: docs-approved

#25121 Fix PaloAltoNetworks_IoT-Test
  Packs/PaloAltoNetworks_IoT/TestPlaybooks/playbook-PaloAltoNetworks_IoT-Test.yml
Labels: docs-approved

#25087 Rdp brute force fixes
  Packs/CortexXDR/Playbooks/Cortex_XDR_Alerts_Handling.yml
  Packs/CortexXDR/Playbooks/playbook-Cortex_XDR_-_Possible_External_RDP_Brute-Force.yml
  Packs/CortexXDR/ReleaseNotes/4_10_21.md
  Packs/CortexXDR/pack_metadata.json
Labels: docs-approved

#25092 Update content build image in CircleCI
  .circleci/config.yml
Labels: docs-approved

#25127 Remote access port bug
  Packs/RemoteAccess/Integrations/RemoteAccessv2/RemoteAccessv2.py
  Packs/RemoteAccess/ReleaseNotes/1_0_16.md
  Packs/RemoteAccess/pack_metadata.json
Labels: docs-approved

#25135 Revert removal of "VirusTotal"
  Tests/Marketplace/core_packs_list.json
  Tests/Marketplace/core_packs_mpv2_list.json
Labels: docs-approved

#25136 Fix Test - CrowdStrike Falcon
  Packs/CrowdStrikeFalcon/TestPlaybooks/playbook-CrowdStrikeFalcon-Test.yml
Labels: docs-approved

#25113 Update url argument description
  Packs/ThreatGrid/Integrations/ThreatGridv2/README.md
  Packs/ThreatGrid/Integrations/ThreatGridv2/ThreatGridv2.py
  Packs/ThreatGrid/Integrations/ThreatGridv2/ThreatGridv2.yml
  Packs/ThreatGrid/Integrations/ThreatGridv2/ThreatGridv2_test.py
  Packs/ThreatGrid/ReleaseNotes/2_0_3.md
  Packs/ThreatGrid/pack_metadata.json
Labels: Contribution, docs-approved, Contribution Form Filled, Community

#25107 Update DragosWorldview.py to break loop on edge case
  Packs/DragosWorldview/Integrations/DragosWorldview/DragosWorldview.py
  Packs/DragosWorldview/ReleaseNotes/1_0_3.md
  Packs/DragosWorldview/pack_metadata.json
Labels: Contribution, docs-approved, Contribution Form Filled, Community, pending-contributor

#25108 Awake Security: Fix python3 issue where map returns an iterator instead of a list
  Packs/AwakeSecurity/Integrations/AwakeSecurity/AwakeSecurity.py
  Packs/AwakeSecurity/ReleaseNotes/1_0_19.md
  Packs/AwakeSecurity/pack_metadata.json
Labels: Contribution

#24942 adding sections to cortexxdr
  Packs/CortexXDR/.pack-ignore
  Packs/CortexXDR/Integrations/CortexXDRIR/CortexXDRIR.yml
  Packs/CortexXDR/Integrations/XQLQueryingEngine/XQLQueryingEngine.yml
  Packs/CortexXDR/ReleaseNotes/4_10_22.md
  Packs/CortexXDR/pack_metadata.json
Labels: docs-approved

#25120 Updated CS Falcon docs
  Packs/CrowdStrikeFalcon/Integrations/CrowdStrikeFalcon/README.md
Labels: docs-approved

#25143 Add packs to update core packs list
  Tests/Marketplace/core_packs_xpanse_list.json
Labels: docs-approved

#24917 Cisco WSA
  Packs/CiscoWSA/.secrets-ignore
  Packs/CiscoWSA/Integrations/CiscoWSA/CiscoWSA.yml
  Packs/CiscoWSA/Integrations/CiscoWSAV2/CiscoWSAV2.py
  Packs/CiscoWSA/Integrations/CiscoWSAV2/CiscoWSAV2.yml
  Packs/CiscoWSA/Integrations/CiscoWSAV2/CiscoWSAV2_description.md
  Packs/CiscoWSA/Integrations/CiscoWSAV2/CiscoWSAV2_image.png
  Packs/CiscoWSA/Integrations/CiscoWSAV2/CiscoWSAV2_test.py
  Packs/CiscoWSA/Integrations/CiscoWSAV2/README.md
  Packs/CiscoWSA/Integrations/CiscoWSAV2/command_examples.txt
  Packs/CiscoWSA/Integrations/CiscoWSAV2/test_data/outputs/access_policy_create_fail.json
  Packs/CiscoWSA/Integrations/CiscoWSAV2/test_data/outputs/access_policy_delete_fail.json
  Packs/CiscoWSA/Integrations/CiscoWSAV2/test_data/outputs/access_policy_list.json
  Packs/CiscoWSA/Integrations/CiscoWSAV2/test_data/outputs/domain_map_create.json
  Packs/CiscoWSA/Integrations/CiscoWSAV2/test_data/outputs/domain_map_create_fail.json
  Packs/CiscoWSA/Integrations/CiscoWSAV2/test_data/outputs/domain_map_delete.json
  Packs/CiscoWSA/Integrations/CiscoWSAV2/test_data/outputs/domain_map_delete_fail.json
  Packs/CiscoWSA/Integrations/CiscoWSAV2/test_data/outputs/domain_map_list.json
  Packs/CiscoWSA/Integrations/CiscoWSAV2/test_data/outputs/domain_map_update.json
  Packs/CiscoWSA/Integrations/CiscoWSAV2/test_data/outputs/domain_map_update_fail.json
  Packs/CiscoWSA/Integrations/CiscoWSAV2/test_data/outputs/identification_profiles_delete_fail.json
  Packs/CiscoWSA/Integrations/CiscoWSAV2/test_data/outputs/identification_profiles_delete_multi.json
  Packs/CiscoWSA/Integrations/CiscoWSAV2/test_data/outputs/identification_profiles_list.json
  Packs/CiscoWSA/Integrations/CiscoWSAV2/test_data/outputs/login.json
  Packs/CiscoWSA/Integrations/CiscoWSAV2/test_data/outputs/login_fail.json
  Packs/CiscoWSA/Integrations/CiscoWSAV2/test_data/outputs/url_categories_list.json
  Packs/CiscoWSA/README.md
  Packs/CiscoWSA/ReleaseNotes/2_0_0.md
  Packs/CiscoWSA/TestPlaybooks/playbook-CiscoWSA_Test.yml
  Packs/CiscoWSA/pack_metadata.json
  Tests/conf.json
Labels: Contribution, docs-approved, ready-for-instance-test, Contribution Form Filled, Community, pending-contributor

#24881 [MongoDB] Upsert flag and bulk update
  Packs/MongoDB/.pack-ignore
  Packs/MongoDB/Integrations/MongoDB/MongoDB.py
  Packs/MongoDB/Integrations/MongoDB/MongoDB.yml
  Packs/MongoDB/Integrations/MongoDB/MongoDB_test.py
  Packs/MongoDB/Integrations/MongoDB/README.md
  Packs/MongoDB/ReleaseNotes/1_3_0.md
  Packs/MongoDB/TestPlaybooks/playbook-MongoDBTest.yml
  Packs/MongoDB/pack_metadata.json
Labels: docs-approved

#25008 Content Pack for Fortanix DSM Integration
  Packs/Fortanix-DSM/.pack-ignore
  Packs/Fortanix-DSM/.secrets-ignore
  Packs/Fortanix-DSM/Author_image.png
  Packs/Fortanix-DSM/Integrations/FortanixDSM/FortanixDSM.py
  Packs/Fortanix-DSM/Integrations/FortanixDSM/FortanixDSM.yml
  Packs/Fortanix-DSM/Integrations/FortanixDSM/FortanixDSM_description.md
  Packs/Fortanix-DSM/Integrations/FortanixDSM/FortanixDSM_image.png
  Packs/Fortanix-DSM/Integrations/FortanixDSM/FortanixDSM_test.py
  Packs/Fortanix-DSM/Integrations/FortanixDSM/Pipfile
  Packs/Fortanix-DSM/Integrations/FortanixDSM/Pipfile.lock
  Packs/Fortanix-DSM/Integrations/FortanixDSM/README.md
  Packs/Fortanix-DSM/Integrations/FortanixDSM/command_examples
  Packs/Fortanix-DSM/README.md
  Packs/Fortanix-DSM/pack_metadata.json
Labels: Contribution, docs-approved, Partner, Contribution Form Filled

#25133 Ms ask enhancement
  Packs/MicrosoftTeams/ReleaseNotes/1_4_10.md
  Packs/MicrosoftTeams/Scripts/MicrosoftTeamsAsk/MicrosoftTeamsAsk.py
  Packs/MicrosoftTeams/Scripts/MicrosoftTeamsAsk/MicrosoftTeamsAsk.yml
  Packs/MicrosoftTeams/Scripts/MicrosoftTeamsAsk/MicrosoftTeamsAsk_test.py
  Packs/MicrosoftTeams/Scripts/MicrosoftTeamsAsk/README.md
  Packs/MicrosoftTeams/pack_metadata.json
Labels: docs-approved

#24943 Microsoft Defender for Identity Modeling
  Packs/MicrosoftAdvancedThreatAnalytics/ModelingRules/MicrosoftAdvancedThreatAnalytics/MicrosoftAdvancedThreatAnalytics.xif
  Packs/MicrosoftAdvancedThreatAnalytics/ModelingRules/MicrosoftAdvancedThreatAnalytics/MicrosoftAdvancedThreatAnalytics_testdata.json
  Packs/MicrosoftAdvancedThreatAnalytics/ReleaseNotes/1_0_12.md
  Packs/MicrosoftAdvancedThreatAnalytics/pack_metadata.json
  Packs/MicrosoftDefenderforIdentity/.pack-ignore
  Packs/MicrosoftDefenderforIdentity/.secrets-ignore
  Packs/MicrosoftDefenderforIdentity/ModelingRules/MicrosoftDefenderforIdentity/MicrosoftDefenderforIdentity.xif
  Packs/MicrosoftDefenderforIdentity/ModelingRules/MicrosoftDefenderforIdentity/MicrosoftDefenderforIdentity.yml
  Packs/MicrosoftDefenderforIdentity/ModelingRules/MicrosoftDefenderforIdentity/MicrosoftDefenderforIdentity_schema.json
  Packs/MicrosoftDefenderforIdentity/README.md
  Packs/MicrosoftDefenderforIdentity/pack_metadata.json
Labels: docs-approved

#25005 [InsightVM / Nexpose] "duration" Error Bugfix
  Packs/Rapid7_Nexpose/Integrations/Rapid7_Nexpose/Rapid7_Nexpose.py
  Packs/Rapid7_Nexpose/ReleaseNotes/1_2_6.md
  Packs/Rapid7_Nexpose/TestPlaybooks/playbook-Nexpose_test.yml
  Packs/Rapid7_Nexpose/pack_metadata.json
Labels: docs-approved

#25146 Unskip validate all in test upload-flow
  .github/CODEOWNERS
  .gitlab/ci/global.yml
  .gitlab/ci/on-push.yml
Labels: docs-approved

#24939 [TAXII 2 Server] Revoke objects, Support SCO structure
  Packs/Base/.pack-ignore
  Packs/Base/ReleaseNotes/1_31_72.md
  Packs/Base/Scripts/CommonServerPython/CommonServerPython.py
  Packs/Base/Scripts/CommonServerPython/CommonServerPython_test.py
  Packs/Base/pack_metadata.json
  Packs/TAXIIServer/.secrets-ignore
  Packs/TAXIIServer/Integrations/TAXII2Server/README.md
  Packs/TAXIIServer/Integrations/TAXII2Server/TAXII2Server.py
  Packs/TAXIIServer/Integrations/TAXII2Server/TAXII2Server.yml
  Packs/TAXIIServer/Integrations/TAXII2Server/TAXII2Server_test.py
  Packs/TAXIIServer/Integrations/TAXII2Server/test_data/entity_b_iocs.json
  Packs/TAXIIServer/Integrations/TAXII2Server/test_data/objects21_ip_with_relationships.json
  Packs/TAXIIServer/Integrations/TAXII2Server/test_data/searchRelationships-response.json
  Packs/TAXIIServer/Integrations/TAXII2Server/test_data/sort_ip_iocs.json
  Packs/TAXIIServer/ReleaseNotes/2_0_28.md
  Packs/TAXIIServer/pack_metadata.json
Labels: docs-approved

#25172 Setting me first
  Utils/github_workflow_scripts/handle_external_pr.py
Labels: docs-approved

#25026 Add 2 new command to Reco Pack
  Packs/Reco/Integrations/Reco/Reco.py
  Packs/Reco/Integrations/Reco/Reco.yml
  Packs/Reco/Integrations/Reco/Reco_test.py
  Packs/Reco/README.md
  Packs/Reco/ReleaseNotes/1_0_1.md
  Packs/Reco/pack_metadata.json
Labels: Contribution, Partner, pending-demo, Contribution Form Filled, pending-contributor

#25161 Fix parseCSV markdown output
  Packs/CommonScripts/ReleaseNotes/1_11_47.md
  Packs/CommonScripts/Scripts/ParseCSV/ParseCSV.py
  Packs/CommonScripts/Scripts/ParseCSV/ParseCSV_test.py
  Packs/CommonScripts/Scripts/ParseCSV/test_data/IOCs.csv
  Packs/CommonScripts/Scripts/ParseCSV/test_data/IOCs_results.json
  Packs/CommonScripts/Scripts/ParseCSV/test_data/one_is_hash_results.json
  Packs/CommonScripts/pack_metadata.json
Labels: docs-approved

#25176 Remove unnecessary spaces in names
  Packs/MicrosoftAdvancedThreatAnalytics/Classifiers/classifier-MicrosoftAdvancedThreatAnalytics.json
  Packs/MicrosoftAdvancedThreatAnalytics/Classifiers/classifier-mapper-incoming-MicrosoftAdvancedThreatAnalytics.json
  Packs/MicrosoftAdvancedThreatAnalytics/ReleaseNotes/1_0_13.md
  Packs/MicrosoftAdvancedThreatAnalytics/pack_metadata.json
Labels: docs-approved

#22750 Add zerohack xdr
  Packs/Zerohack_XDR/.pack-ignore
  Packs/Zerohack_XDR/.secrets-ignore
  Packs/Zerohack_XDR/Author_image.png
  Packs/Zerohack_XDR/CONTRIBUTORS.json
  Packs/Zerohack_XDR/IncidentTypes/IncidentType-Zerohack_XDR.json
  Packs/Zerohack_XDR/Integrations/ZerohackXDR/README.md
  Packs/Zerohack_XDR/Integrations/ZerohackXDR/ZerohackXDR.py
  Packs/Zerohack_XDR/Integrations/ZerohackXDR/ZerohackXDR.yml
  Packs/Zerohack_XDR/Integrations/ZerohackXDR/ZerohackXDR_description.md
  Packs/Zerohack_XDR/Integrations/ZerohackXDR/ZerohackXDR_image.png
  Packs/Zerohack_XDR/Integrations/ZerohackXDR/ZerohackXDR_test.py
  Packs/Zerohack_XDR/Integrations/ZerohackXDR/command_examples
  Packs/Zerohack_XDR/Integrations/ZerohackXDR/test_data/fetch_incidents.json
  Packs/Zerohack_XDR/Integrations/ZerohackXDR/test_data/get-sample-incident.json
  Packs/Zerohack_XDR/Integrations/ZerohackXDR/test_data/get_latest_incident.json
  Packs/Zerohack_XDR/README.md
  Packs/Zerohack_XDR/doc_imgs/CLI_command_execute.png
  Packs/Zerohack_XDR/doc_imgs/Xdr_dashboard_sidepanel.png
  Packs/Zerohack_XDR/doc_imgs/Xdr_homepage.png
  Packs/Zerohack_XDR/doc_imgs/command_result.png
  Packs/Zerohack_XDR/doc_imgs/createAPI1.1.png
  Packs/Zerohack_XDR/doc_imgs/createAPI_2.1.png
  Packs/Zerohack_XDR/doc_imgs/createAPI_3.1.png
  Packs/Zerohack_XDR/doc_imgs/createAPI_4.1.png
  Packs/Zerohack_XDR/doc_imgs/createAPI_5.1.png
  Packs/Zerohack_XDR/doc_imgs/createAPI_6.1.png
  Packs/Zerohack_XDR/doc_imgs/dashboard_sidepanel.png
  Packs/Zerohack_XDR/doc_imgs/latest_fetch_history.png
  Packs/Zerohack_XDR/doc_imgs/settings_integrations.png
  Packs/Zerohack_XDR/doc_imgs/settings_integrations1.png
  Packs/Zerohack_XDR/doc_imgs/settings_integrations2.png
  Packs/Zerohack_XDR/doc_imgs/settings_integrations_add.png
  Packs/Zerohack_XDR/doc_imgs/test_results.png
  Packs/Zerohack_XDR/doc_imgs/xsoar_dash.png
  Packs/Zerohack_XDR/pack_metadata.json
Labels: Contribution, Partner, post-demo, Contribution Form Filled

#25036 [ASM] - Add Email Notification for Remediation Action for Service Owners - Expander - 3032
  Packs/CortexAttackSurfaceManagement/Playbooks/Cortex_ASM_-_ASM_Alert.yml
  Packs/CortexAttackSurfaceManagement/README.md
  Packs/CortexAttackSurfaceManagement/ReleaseNotes/1_5_6.md
  Packs/CortexAttackSurfaceManagement/doc_files/Cortex_ASM_-_ASM_Alert.png
  Packs/CortexAttackSurfaceManagement/pack_metadata.json
Labels: Contribution, docs-approved, Contribution Form Filled, Community

#24519 Splunk - add basic auth option
  Packs/SplunkPy/Integrations/SplunkPy/SplunkPy.py
  Packs/SplunkPy/Integrations/SplunkPy/SplunkPy_description.md
  Packs/SplunkPy/Integrations/SplunkPy/SplunkPy_test.py
  Packs/SplunkPy/ReleaseNotes/3_0_12.md
  Packs/SplunkPy/pack_metadata.json
Labels: docs-approved

#25181 fireEye ETP fix documentation
  Packs/FireEyeETP/Integrations/FireEyeETP/FireEyeETP.yml
  Packs/FireEyeETP/ReleaseNotes/1_2_2.md
  Packs/FireEyeETP/pack_metadata.json
Labels: docs-approved

#25159 XSIAM Playbooks Fixes
  Packs/CommonPlaybooks/Playbooks/playbook-Enrichment_for_Verdict.yml
  Packs/CommonPlaybooks/Playbooks/playbook-Enrichment_for_Verdict_README.md
  Packs/CommonPlaybooks/ReleaseNotes/2_3_44.md
  Packs/CommonPlaybooks/doc_files/Enrichment_for_Verdict.png
  Packs/CommonPlaybooks/pack_metadata.json
  Packs/Core/Playbooks/playbook-Local_Analysis_alert_Investigation.yml
  Packs/Core/Playbooks/playbook-Local_Analysis_alert_Investigation_README.md
  Packs/Core/Playbooks/playbook-WildFire_Malware.yml
  Packs/Core/Playbooks/playbook-WildFire_Malware_README.md
  Packs/Core/ReleaseNotes/1_3_38.md
  Packs/Core/pack_metadata.json
Labels: docs-approved

#25115 [ASM] - EXPANDR-1614 - Servicenow pack asm integration
  Packs/CortexAttackSurfaceManagement/.pack-ignore
  Packs/CortexAttackSurfaceManagement/Playbooks/Cortex_ASM_-_ASM_Alert.yml
  Packs/CortexAttackSurfaceManagement/Playbooks/Cortex_ASM_-_ServiceNow_CMDB_Enrichment.yml
  Packs/CortexAttackSurfaceManagement/ReleaseNotes/1_5_7.md
  Packs/CortexAttackSurfaceManagement/pack_metadata.json
Labels: Contribution, docs-approved, Contribution Form Filled, Community

#25184 [RecordedFuture] Fixed docs link
  Packs/RecordedFuture/Integrations/RecordedFuture/RecordedFuture_description.md
  Packs/RecordedFuture/ReleaseNotes/1_3_4.md
  Packs/RecordedFuture/pack_metadata.json
Labels: docs-approved

#25104 Fix DBotPredictURLPhishing
  Packs/PhishingURL/ReleaseNotes/1_0_7.md
  Packs/PhishingURL/Scripts/DBotPredictURLPhishing/DBotPredictURLPhishing.py
  Packs/PhishingURL/Scripts/DBotPredictURLPhishing/dbotpredicturlphishing_test.py
  Packs/PhishingURL/pack_metadata.json
Labels: docs-approved, ForceMerge

#25170 CiscoFirepower Pack README update
  Packs/CiscoFirepower/README.md
Labels: docs-approved

#25173 St GitHub iam test fix
  Packs/GitHub/Integrations/GitHub_IAM/GitHub_IAM.py
  Packs/GitHub/Integrations/GitHub_IAM/GitHub_IAM.yml
  Packs/GitHub/ReleaseNotes/2_0_13.md
  Packs/GitHub/pack_metadata.json
Labels: docs-approved

#25179 365 bug
  Packs/Microsoft365Defender/Integrations/Microsoft365Defender/Microsoft365Defender.py
  Packs/Microsoft365Defender/Integrations/Microsoft365Defender/Microsoft365Defender.yml
  Packs/Microsoft365Defender/Integrations/Microsoft365Defender/Microsoft365Defender_description.md
  Packs/Microsoft365Defender/ReleaseNotes/4_5_3.md
  Packs/Microsoft365Defender/pack_metadata.json
Labels: docs-approved

#25157 Taxi bug
  Packs/ApiModules/Scripts/TAXII2ApiModule/TAXII2ApiModule.py
  Packs/ApiModules/Scripts/TAXII2ApiModule/TAXII2ApiModule_test.py
  Packs/ApiModules/Scripts/TAXII2ApiModule/test_data/cortex_parsed_indicators_complex_skipped_14-19.json
  Packs/ApiModules/Scripts/TAXII2ApiModule/test_data/parsed_stix_objects.json
  Packs/FeedTAXII/Integrations/FeedTAXII2/FeedTAXII2.yml
  Packs/FeedTAXII/ReleaseNotes/1_1_22.md
  Packs/FeedTAXII/pack_metadata.json
Labels: docs-approved

#25102 Abnormal security fix toaddresses
  Packs/AbnormalSecurity/ModelingRules/AbnormalSecurityEventCollector_1_3/AbnormalSecurityEventCollector_1_3.xif
  Packs/AbnormalSecurity/ReleaseNotes/2_0_10.md
  Packs/AbnormalSecurity/pack_metadata.json
Labels: docs-approved, release-notes-only

#24733 Prisma cloud vm prioritization
  Packs/CommonTypes/IncidentFields/incidentfield-Account_ID.json
  Packs/CommonTypes/IncidentFields/incidentfield-Account_Name.json
  Packs/CommonTypes/IncidentFields/incidentfield-First_Seen.json
  Packs/CommonTypes/IncidentFields/incidentfield-Last_Modified_By.json
  Packs/CommonTypes/IncidentFields/incidentfield-Last_Modified_On.json
  Packs/CommonTypes/IncidentFields/incidentfield-Last_Seen.json
  Packs/CommonTypes/IncidentFields/incidentfield-Last_Update_Time.json
  Packs/CommonTypes/IncidentFields/incidentfield-Policy_Deleted.json
  Packs/CommonTypes/IncidentFields/incidentfield-Policy_Description.json
  Packs/CommonTypes/IncidentFields/incidentfield-Policy_Details.json
  Packs/CommonTypes/IncidentFields/incidentfield-Policy_ID.json
  Packs/CommonTypes/IncidentFields/incidentfield-Policy_Recommendation.json
  Packs/CommonTypes/IncidentFields/incidentfield-Policy_Remediable.json
  Packs/CommonTypes/IncidentFields/incidentfield-Policy_Severity.json
  Packs/CommonTypes/IncidentFields/incidentfield-Policy_Type.json
  Packs/CommonTypes/IncidentFields/incidentfield-Rating.json
  Packs/CommonTypes/IncidentFields/incidentfield-Region.json
  Packs/CommonTypes/IncidentFields/incidentfield-Region_ID.json
  Packs/CommonTypes/IncidentFields/incidentfield-Resource_ID.json
  Packs/CommonTypes/IncidentFields/incidentfield-Resource_Name.json
  Packs/CommonTypes/IncidentFields/incidentfield-Resource_Type.json
  Packs/CommonTypes/IncidentFields/incidentfield-Risk_Rating.json
  Packs/CommonTypes/IncidentFields/incidentfield-Risk_Score.json
  Packs/CommonTypes/IncidentFields/incidentfield-SKU_Name.json
  Packs/CommonTypes/IncidentFields/incidentfield-SKU_TIER.json
  Packs/CommonTypes/ReleaseNotes/3_3_55.md
  Packs/CommonTypes/pack_metadata.json
  Packs/PrismaCloud/Classifiers/classifier-Prisma_Cloud.json
  Packs/PrismaCloud/Classifiers/classifier-mapper-incoming-Prisma_Cloud.json
  Packs/PrismaCloud/IncidentFields/incidentfield-Prisma_Cloud_Findings_Results.json
  Packs/PrismaCloud/IncidentFields/incidentfield-Prisma_Cloud_IAM_Results.json
  Packs/PrismaCloud/IncidentFields/incidentfield-Prisma_Cloud_ID.json
  Packs/PrismaCloud/IncidentFields/incidentfield-Prisma_Cloud_Reason.json
  Packs/PrismaCloud/IncidentFields/incidentfield-Prisma_Cloud_Rules.json
  Packs/PrismaCloud/IncidentFields/incidentfield-Prisma_Cloud_Status.json
  Packs/PrismaCloud/IncidentFields/incidentfield-Prisma_Cloud_Time.json
  Packs/PrismaCloud/IncidentFields/incidentfield-RRN.json
  Packs/PrismaCloud/IncidentFields/incidentfield-Resource_API_Name.json
  Packs/PrismaCloud/IncidentFields/incidentfield-Resource_Cloud_Type.json
  Packs/PrismaCloud/IncidentFields/incidentfield-Subscription_Assigned_By.json
  Packs/PrismaCloud/IncidentFields/incidentfield-Subscription_Created_By.json
  Packs/PrismaCloud/IncidentFields/incidentfield-Subscription_Created_On.json
  Packs/PrismaCloud/IncidentFields/incidentfield-Subscription_Description.json
  Packs/PrismaCloud/IncidentFields/incidentfield-Subscription_ID.json
  Packs/PrismaCloud/IncidentFields/incidentfield-Subscription_Name.json
  Packs/PrismaCloud/IncidentFields/incidentfield-Subscription_Type.json
  Packs/PrismaCloud/IncidentFields/incidentfield-Subscription_Updated_By.json
  Packs/PrismaCloud/IncidentFields/incidentfield-Subscription_Updated_On.json
  Packs/PrismaCloud/IncidentFields/incidentfield-System_Default.json
  Packs/PrismaCloud/IncidentFields/incidentfield-VPC_ID.json
  Packs/PrismaCloud/IncidentTypes/incidenttype-Prisma_Cloud_VM_Alert_prioritization.json
  Packs/PrismaCloud/Layouts/layoutscontainer-Prisma_Cloud_-_VM_Alert_Prioritization.json
  Packs/PrismaCloud/Playbooks/playbook-Prisma_Cloud_-_VM_Alert_Prioritization.yml
  Packs/PrismaCloud/Playbooks/playbook-Prisma_Cloud_-_VM_Alert_Prioritization_README.md
  Packs/PrismaCloud/ReleaseNotes/3_0_1.md
  Packs/PrismaCloud/doc_files/Prisma_Cloud_-_VM_Alert_Prioritization.png
  Packs/PrismaCloud/doc_files/layout_case_info.png
  Packs/PrismaCloud/doc_files/layout_investigation.png
  Packs/PrismaCloud/pack_metadata.json
Labels: docs-approved

#24947 Teams enhancements
  Packs/MicrosoftTeams/Integrations/MicrosoftTeams/MicrosoftTeams.py
  Packs/MicrosoftTeams/Integrations/MicrosoftTeams/MicrosoftTeams_test.py
  Packs/MicrosoftTeams/Integrations/MicrosoftTeams/README.md
  Packs/MicrosoftTeams/ReleaseNotes/1_4_11.md
  Packs/MicrosoftTeams/pack_metadata.json
Labels: docs-approved

#25106 Filter Fixes for 'Cortex XDR - Get File Path from alerts by hash' pla…
  Packs/CortexXDR/Playbooks/playbook-Cortex_XDR_-_Get_File_Path_from_alerts_by_hash.yml
  Packs/CortexXDR/Playbooks/playbook-Cortex_XDR_-_Get_File_Path_from_alerts_by_hash_README.md
  Packs/CortexXDR/ReleaseNotes/4_10_24.md
  Packs/CortexXDR/pack_metadata.json
Labels: docs-approved

#25212 Mapping field defender correlation rule
  Packs/MicrosoftDefenderAdvancedThreatProtection/CorrelationRules/MicrosoftDefenderAdvancedThreatProtection_correlation-rule.yml
  Packs/MicrosoftDefenderAdvancedThreatProtection/ReleaseNotes/1_15_15.md
  Packs/MicrosoftDefenderAdvancedThreatProtection/pack_metadata.json
Labels: docs-approved, release-notes-only

#24517 [Rapid Breach Response] Replace usage of deprecated `Isolate Endpoint - Generic` playbook
  Packs/MajorBreachesInvestigationandResponse/Playbooks/playbook-FireEye_Red_Team_Tools_Investigation_and_Response.yml
  Packs/MajorBreachesInvestigationandResponse/Playbooks/playbook-FireEye_Red_Team_Tools_Investigation_and_Response_README.md
  Packs/MajorBreachesInvestigationandResponse/ReleaseNotes/1_6_28.md
  Packs/MajorBreachesInvestigationandResponse/doc_files/FireEye_Red_Team_Tools_Inestigation_and_Response.png
  Packs/MajorBreachesInvestigationandResponse/doc_files/FireEye_Red_Team_Tools_Investigation_and_Response.png
  Packs/MajorBreachesInvestigationandResponse/pack_metadata.json
Labels: docs-approved

#24527 [XM Cyber] Replace usage of deprecated `Isolate Endpoint - Generic` playbook
  Packs/XMCyber/Playbooks/Scan_and_Isolate_XM_Cyber.yml
  Packs/XMCyber/Playbooks/Scan_and_Isolate_XM_Cyber_README.md
  Packs/XMCyber/ReleaseNotes/1_0_20.md
  Packs/XMCyber/doc_files/Scan_and_Isolate_-_XM_Cyber.png
  Packs/XMCyber/pack_metadata.json
Labels: docs-approved

#25047 [CommonServerPython] Remove Regex Duplicates
  Packs/Base/ReleaseNotes/1_31_73.md
  Packs/Base/Scripts/CommonServerPython/CommonServerPython.py
  Packs/Base/pack_metadata.json
Labels: docs-approved, ForceMerge

#25131 Fixes for 'Search For Hash In Sandbox - Generic' Playbook
  Packs/CommonPlaybooks/.pack-ignore
  Packs/CommonPlaybooks/Playbooks/playbook-Search_For_Hash_In_Sandbox_-_Generic.yml
  Packs/CommonPlaybooks/Playbooks/playbook-Search_For_Hash_In_Sandbox_-_Generic_README.md
  Packs/CommonPlaybooks/ReleaseNotes/2_3_45.md
  Packs/CommonPlaybooks/doc_files/Search_For_Hash_In_Sandbox_-_Generic.png
  Packs/CommonPlaybooks/pack_metadata.json
Labels: docs-approved

#25091 Impossible Traveler Response Fixes
  Packs/Core/Playbooks/playbook-Impossible_Traveler_-_Enrichment.yml
  Packs/Core/Playbooks/playbook-Impossible_Traveler_-_Enrichment_README.md
  Packs/Core/ReleaseNotes/1_3_39.md
  Packs/Core/pack_metadata.json
Labels: docs-approved

#25216 Remove forward slash from URL regex path part
  Packs/CommonScripts/ReleaseNotes/1_11_48.md
  Packs/CommonScripts/Scripts/FormatURL/FormatURL.py
  Packs/CommonScripts/pack_metadata.json
  Packs/CommonTypes/IndicatorTypes/reputation-url.json
  Packs/CommonTypes/ReleaseNotes/3_3_56.md
  Packs/CommonTypes/pack_metadata.json
Labels: docs-approved

#24676 redirect_fromversion_reading
  Tests/Marketplace/configure_and_install_packs.py
  Tests/configure_and_test_integration_instances.py
  Tests/tests/configure_and_test_integration_instances_test.py
  Utils/test_upload_flow/TestUploadFlow/Classifiers/classifier-TestUploadFlowClass.json
  Utils/test_upload_flow/TestUploadFlow/Classifiers/classifier-TestUploadFlowIndicatorClass.json
  Utils/test_upload_flow/TestUploadFlow/Layouts/layoutscontainer-TestUploadFlowLayout.json
  Utils/test_upload_flow/create_test_branch.py
  Utils/test_upload_flow/verify_bucket.py
Labels: docs-approved

#25177 Syslog bug
  Packs/Syslog/Integrations/SyslogSender/SyslogSender.py
  Packs/Syslog/Integrations/SyslogSender/SyslogSender.yml
  Packs/Syslog/ReleaseNotes/2_0_15.md
  Packs/Syslog/pack_metadata.json
Labels: docs-approved

#25233 [TimeComponents] Fix Unit-Test Failure
  Packs/FiltersAndTransformers/Scripts/TimeComponents/test_data/test.json
Labels: docs-approved

#24508 [Sixgill Darkfeed] Replace usage of deprecated `Isolate Endpoint - Generic` playbook
  Packs/Sixgill-Darkfeed/.pack-ignore
  Packs/Sixgill-Darkfeed/Playbooks/Darkfeed_Threat_hunting_research.yml
  Packs/Sixgill-Darkfeed/Playbooks/Darkfeed_Threat_hunting_research_README.md
  Packs/Sixgill-Darkfeed/ReleaseNotes/2_0_19.md
  Packs/Sixgill-Darkfeed/doc_files/Darkfeed_Threat_hunting-research.png
  Packs/Sixgill-Darkfeed/doc_files/Darkfeed_Threat_hunting_research.png
  Packs/Sixgill-Darkfeed/pack_metadata.json
Labels: docs-approved

#24608 [SANS] Replace usage of deprecated `Isolate Endpoint - Generic` playbook
  Packs/SANS/Playbooks/playbook-Brute_Force_Investigation_-_Generic_-_SANS.yml
  Packs/SANS/Playbooks/playbook-Brute_Force_Investigation_-_Generic_-_SANS_README.md
  Packs/SANS/ReleaseNotes/1_1_4.md
  Packs/SANS/doc_files/Brute_Force_Investigation_-_Generic_-_SANS.png
  Packs/SANS/pack_metadata.json
Labels: docs-approved

#25232 Bug/XSUP 22240/strings bug
  Packs/CommonScripts/ReleaseNotes/1_11_49.md
  Packs/CommonScripts/Scripts/Strings/Strings.py
  Packs/CommonScripts/Scripts/Strings/Strings.yml
  Packs/CommonScripts/Scripts/Strings/Strings_test.py
  Packs/CommonScripts/Scripts/Strings/test_data/pdf_file.pdf
  Packs/CommonScripts/pack_metadata.json
Labels: docs-approved

#24553 [Brute Force] Replace usage of deprecated `Isolate Endpoint - Generic` playbook
  Packs/BruteForce/Playbooks/Brute_Force_Investigation_-_Generic.yml
  Packs/BruteForce/Playbooks/Brute_Force_Investigation_-_Generic_README.md
  Packs/BruteForce/README.md
  Packs/BruteForce/ReleaseNotes/1_2_4.md
  Packs/BruteForce/doc_files/Brute_Force_Investigation_-_Generic.png
  Packs/BruteForce/pack_metadata.json
Labels: docs-approved

#24891 csfalconx parse indicator bugfix
  Packs/CrowdStrikeFalconX/Integrations/CrowdStrikeFalconX/CrowdStrikeFalconX.py
  Packs/CrowdStrikeFalconX/Integrations/CrowdStrikeFalconX/CrowdStrikeFalconX_test.py
  Packs/CrowdStrikeFalconX/ReleaseNotes/1_2_24.md
  Packs/CrowdStrikeFalconX/pack_metadata.json
Labels: docs-approved

#25096 Fixed fetch incidents logic, added better handling for None severities.
  Packs/AMP/Integrations/AMPv2/AMPv2.py
  Packs/AMP/Integrations/AMPv2/AMPv2.yml
  Packs/AMP/ReleaseNotes/2_0_4.md
  Packs/AMP/pack_metadata.json
Labels: Contribution, Contribution Form Filled, Community

#25225 Ciscowsa/release note fix
  Packs/CiscoWSA/ReleaseNotes/2_0_0.md
Labels: Contribution, Contribution Form Filled, Community

#25178 Added the vsys param to the register_ip_tag command
  Packs/PAN-OS/Integrations/Panorama/Panorama.py
  Packs/PAN-OS/Integrations/Panorama/Panorama_test.py
  Packs/PAN-OS/ReleaseNotes/1_16_14.md
  Packs/PAN-OS/pack_metadata.json
Labels: docs-approved

#24413 "Isolate Endpoint - Generic" Playbook Deprecation
  Packs/CommonPlaybooks/Playbooks/playbook-Isolate_Endpoint_-_Generic.yml
  Packs/CommonPlaybooks/ReleaseNotes/2_3_46.md
  Packs/CommonPlaybooks/pack_metadata.json
Labels: docs-approved

#25239 St update dockers bug
  Packs/CommonScripts/ReleaseNotes/1_11_51.md
  Packs/CommonScripts/Scripts/CreateHash/CreateHash.yml
  Packs/CommonScripts/Scripts/DeduplicateValuesbyKey/DeduplicateValuesbyKey.yml
  Packs/CommonScripts/Scripts/DockerHardeningCheck/DockerHardeningCheck.yml
  Packs/CommonScripts/Scripts/ExifRead/ExifRead.yml
  Packs/CommonScripts/Scripts/ExtractDomainAndFQDNFromUrlAndEmail/ExtractDomainAndFQDNFromUrlAndEmail.yml
  Packs/CommonScripts/Scripts/ExtractDomainFromUrlFormat/ExtractDomainFromUrlFormat.yml
  Packs/CommonScripts/Scripts/ExtractFQDNFromUrlAndEmail/ExtractFQDNFromUrlAndEmail.yml
  Packs/CommonScripts/Scripts/ExtractHTMLTables/ExtractHTMLTables.yml
  Packs/CommonScripts/Scripts/GridFieldSetup/GridFieldSetup.yml
  Packs/CommonScripts/Scripts/JsonUnescape/JsonUnescape.yml
  Packs/CommonScripts/Scripts/LanguageDetect/LanguageDetect.yml
  Packs/CommonScripts/Scripts/ParseExcel/ParseExcel.py
  Packs/CommonScripts/Scripts/ParseExcel/ParseExcel.yml
  Packs/CommonScripts/Scripts/RunDockerCommand/RunDockerCommand.yml
  Packs/CommonScripts/Scripts/StixCreator/StixCreator.yml
  Packs/CommonScripts/Scripts/ZipFile/ZipFile.yml
  Packs/CommonScripts/pack_metadata.json
  Packs/FiltersAndTransformers/ReleaseNotes/1_2_12.md
  Packs/FiltersAndTransformers/Scripts/Jmespath/Jmespath.yml
  Packs/FiltersAndTransformers/Scripts/MapRangeValues/MapRangeValues.yml
  Packs/FiltersAndTransformers/Scripts/MapRangeValues/README.md
  Packs/FiltersAndTransformers/Scripts/ParseHTMLTables/ParseHTMLTables.yml
  Packs/FiltersAndTransformers/pack_metadata.json
Labels: docs-approved

#25190 Fixing empty response domain command
  Packs/Whois/Integrations/Whois/README.md
  Packs/Whois/Integrations/Whois/Whois.py
  Packs/Whois/ReleaseNotes/1_4_12.md
  Packs/Whois/pack_metadata.json
Labels: docs-approved

#25209 Add IpPermissionsFull Arg to Multiple EC2 Commands
  Packs/AWS-EC2/.pack-ignore
  Packs/AWS-EC2/Integrations/AWS-EC2/AWS-EC2.py
  Packs/AWS-EC2/Integrations/AWS-EC2/AWS-EC2.yml
  Packs/AWS-EC2/Integrations/AWS-EC2/AWS-EC2_test.py
  Packs/AWS-EC2/Integrations/AWS-EC2/README.md
  Packs/AWS-EC2/ReleaseNotes/1_2_31.md
  Packs/AWS-EC2/pack_metadata.json
Labels: Contribution, Contribution Form Filled, Community

#25142 Microsoft Intune Modeling Rules
  Packs/MicrosoftIntune/.pack-ignore
  Packs/MicrosoftIntune/.secrets-ignore
  Packs/MicrosoftIntune/ModelingRules/MicrosoftIntune_1_3/MicrosoftIntune_1_3.xif
  Packs/MicrosoftIntune/ModelingRules/MicrosoftIntune_1_3/MicrosoftIntune_1_3.yml
  Packs/MicrosoftIntune/ModelingRules/MicrosoftIntune_1_3/MicrosoftIntune_1_3_schema.json
  Packs/MicrosoftIntune/ParsingRules/MicrosoftIntuneParsingRules/MicrosoftIntuneParsingRules.xif
  Packs/MicrosoftIntune/ParsingRules/MicrosoftIntuneParsingRules/MicrosoftIntuneParsingRules.yml
  Packs/MicrosoftIntune/README.md
  Packs/MicrosoftIntune/pack_metadata.json
Labels: docs-approved

#25267 Remove mandatory dependencies for Prisma Cloud
  Packs/PrismaCloud/pack_metadata.json
Labels: docs-approved

#25134 Updated email regex and formatter to allow idna
  Packs/Base/TestPlaybooks/playbook-Email_extraction_test.yml
  Packs/CommonScripts/ReleaseNotes/1_11_52.md
  Packs/CommonScripts/Scripts/ExtractEmailFormatting/ExtractEmailFormatting.py
  Packs/CommonScripts/Scripts/ExtractEmailFormatting/ExtractEmailFormatting_test.py
  Packs/CommonScripts/pack_metadata.json
  Packs/CommonTypes/IndicatorTypes/reputation-email.json
  Packs/CommonTypes/ReleaseNotes/3_3_58.md
  Packs/CommonTypes/pack_metadata.json
Labels: docs-approved

#25182 Kubernetes mapping
  Packs/Kubernetes/.pack-ignore
  Packs/Kubernetes/.secrets-ignore
  Packs/Kubernetes/ModelingRules/Kubernetes/Kubernetes.xif
  Packs/Kubernetes/ModelingRules/Kubernetes/Kubernetes.yml
  Packs/Kubernetes/ModelingRules/Kubernetes/Kubernetes_schema.json
  Packs/Kubernetes/ParsingRules/Kubernetes/Kubernetes.xif
  Packs/Kubernetes/ParsingRules/Kubernetes/Kubernetes.yml
  Packs/Kubernetes/README.md
  Packs/Kubernetes/pack_metadata.json
Labels: docs-approved

#25269 [Time Components] Add `freeze_time` to unit test to make it consistent
  Packs/FiltersAndTransformers/Scripts/TimeComponents/TimeComponents_test.py
  Packs/FiltersAndTransformers/Scripts/TimeComponents/test_data/test.json
Labels: docs-approved

#25052 testing
  .circleci/config.yml
  .gitlab/ci/global.yml
  .gitlab/ci/on-push.yml
  .gitlab/helper_functions.sh
  Tests/scripts/check_jobs_done.py
Labels: Contribution, ready-for-instance-test

#25186 Fix demisto-sdk nightly auth
  .gitlab/ci/sdk-nightly.yml
Labels: docs-approved

#25088 Remove ast.literal_eval from install_packs
  Tests/Marketplace/Tests/search_and_install_packs_test.py
  Tests/Marketplace/search_and_install_packs.py
  Tests/private_build/tests/test_configure_and_test_integration_instances_private.py
Labels: docs-approved

#25219 add reputation command to enrichment pb
  Packs/CommonPlaybooks/Playbooks/playbook-Domain_Enrichment_-_Generic_v2.yml
  Packs/CommonPlaybooks/Playbooks/playbook-Domain_Enrichment_-_Generic_v2_README.md
  Packs/CommonPlaybooks/Playbooks/playbook-Email_Address_Enrichment_-_Generic_v2.1.yml
  Packs/CommonPlaybooks/Playbooks/playbook-Email_Address_Enrichment_-_Generic_v2.1_README.md
  Packs/CommonPlaybooks/Playbooks/playbook-Endpoint_Enrichment_-_Generic_v2.1.yml
  Packs/CommonPlaybooks/Playbooks/playbook-Endpoint_Enrichment_-_Generic_v2.1_README.md
  Packs/CommonPlaybooks/Playbooks/playbook-File_Enrichment_-_Generic_v2.yml
  Packs/CommonPlaybooks/Playbooks/playbook-File_Enrichment_-_Generic_v2_README.md
  Packs/CommonPlaybooks/Playbooks/playbook-URL_Enrichment_-_Generic_v2.yml
  Packs/CommonPlaybooks/Playbooks/playbook-URL_Enrichment_-_Generic_v2_README.md
  Packs/CommonPlaybooks/ReleaseNotes/2_3_47.md
  Packs/CommonPlaybooks/doc_files/Domain_Enrichment_-_Generic_v2.png
  Packs/CommonPlaybooks/doc_files/Email_Address_Enrichment_-_Generic_v2.1.png
  Packs/CommonPlaybooks/doc_files/Endpoint_Enrichment_-_Generic_v2.1.png
  Packs/CommonPlaybooks/doc_files/File_Enrichment_-_Generic_v2.png
  Packs/CommonPlaybooks/doc_files/URL_Enrichment_-_Generic_v2.png
  Packs/CommonPlaybooks/pack_metadata.json
Labels: docs-approved

#25174 Fix microsoft cas duplicate incidents
  Packs/MicrosoftCloudAppSecurity/Integrations/MicrosoftCloudAppSecurity/MicrosoftCloudAppSecurity.py
  Packs/MicrosoftCloudAppSecurity/Integrations/MicrosoftCloudAppSecurity/MicrosoftCloudAppSecurity.yml
  Packs/MicrosoftCloudAppSecurity/Integrations/MicrosoftCloudAppSecurity/MicrosoftCloudAppSecurity_test.py
  Packs/MicrosoftCloudAppSecurity/ReleaseNotes/2_1_25.md
  Packs/MicrosoftCloudAppSecurity/pack_metadata.json
Labels: docs-approved

#25280 St symantec dlp yml fix
  Packs/SymantecDLP/Integrations/SymantecDLPV2/SymantecDLPV2.yml
  Packs/SymantecDLP/ReleaseNotes/2_0_9.md
  Packs/SymantecDLP/pack_metadata.json
Labels: docs-approved

#24746 Cryptojacking Fixes
  Packs/Core/Playbooks/playbook-XCloud_Cryptomining.yml
  Packs/Core/ReleaseNotes/1_3_40.md
  Packs/Core/pack_metadata.json
  Packs/CortexXDR/.pack-ignore
  Packs/CortexXDR/IncidentTypes/incidenttype-Cortex_XDR_-_XCLOUD_Cryptomining.json
  Packs/CortexXDR/Layouts/layoutscontainer-Cortex_XDR_-_XCLOUD_Cryptomining.json
  Packs/CortexXDR/Playbooks/Cortex_XDR_Alerts_Handling.yml
  Packs/CortexXDR/Playbooks/Cortex_XDR_Alerts_Handling_README.md
  Packs/CortexXDR/Playbooks/playbook-Cortex_XDR_-_Cloud_Cryptomining.yml
  Packs/CortexXDR/Playbooks/playbook-Cortex_XDR_-_Cloud_Cryptomining_-_Set_Verdict.yml
  Packs/CortexXDR/Playbooks/playbook-Cortex_XDR_-_Cloud_Cryptomining_-_Set_Verdict_README.md
  Packs/CortexXDR/Playbooks/playbook-Cortex_XDR_-_Cloud_Cryptomining_README.md
  Packs/CortexXDR/ReleaseNotes/4_10_25.md
  Packs/CortexXDR/pack_metadata.json
Labels: docs-approved

#25244 Block i pv3 fix
  Packs/CommonPlaybooks/Playbooks/playbook-Block_IP_-_Generic_v3.yml
  Packs/CommonPlaybooks/Playbooks/playbook-Block_IP_-_Generic_v3_README.md
  Packs/CommonPlaybooks/ReleaseNotes/2_3_48.md
  Packs/CommonPlaybooks/doc_files/Block_IP_-_Generic_v3.png
  Packs/CommonPlaybooks/pack_metadata.json
Labels: docs-approved

#25123 demisto-sdk logging-standardization
  .gitignore
  Tests/scripts/spell_checker.py
  Tests/scripts/verify_base_branch_for_contribution.py
  Utils/comment_on_pr.py
  Utils/update_contribution_pack_in_base_branch.py
  poetry.lock
  pyproject.toml
Labels: docs-approved

#25252 Case mgmt updates mar2023
  Packs/CaseManagement-Generic/Classifiers/classifier-Case_Management_-_Generic_Mapper.json
  Packs/CaseManagement-Generic/Dashboards/dashboard-Incidents_Overview.json
  Packs/CaseManagement-Generic/Layouts/layoutscontainer-Case_Management_Layout_v2.json
  Packs/CaseManagement-Generic/Playbooks/Case_Management_-_Generic_-_Send_On_Call_Notification.yml
  Packs/CaseManagement-Generic/Playbooks/Case_Management_-_Generic_-_Send_On_Call_Notification_README.md
  Packs/CaseManagement-Generic/Playbooks/Case_Management_-_Generic_-_Set_SLAs_based_on_Severity_README.md
  Packs/CaseManagement-Generic/Playbooks/Case_Management_-_Generic_-_Start_SLA_Timers_README.md
  Packs/CaseManagement-Generic/Playbooks/Case_Management_-_Generic_v2.yml
  Packs/CaseManagement-Generic/Playbooks/Case_Management_-_Generic_v2_README.md
  Packs/CaseManagement-Generic/Playbooks/playbook-Case_Management_-_Generic_README.md
  Packs/CaseManagement-Generic/README.md
  Packs/CaseManagement-Generic/ReleaseNotes/1_4_5.md
  Packs/CaseManagement-Generic/Reports/report-CaseReport.json
  Packs/CaseManagement-Generic/Scripts/AddUserToIncidentTeam/AddUserToIncidentTeam.yml
  Packs/CaseManagement-Generic/Scripts/AddUserToIncidentTeam/README.md
  Packs/CaseManagement-Generic/Scripts/CaseMgmtAnalystTools/README.md
  Packs/CaseManagement-Generic/Scripts/CaseMgmtDisplayLabels/CaseMgmtDisplayLabels.py
  Packs/CaseManagement-Generic/Scripts/CaseMgmtDisplayLabels/CaseMgmtDisplayLabels.yml
  Packs/CaseManagement-Generic/Scripts/CaseMgmtDisplayLabels/README.md
  Packs/CaseManagement-Generic/Scripts/CaseMgmtIncidentTypesByRole/CaseMgmtIncidentTypesByRole.py
  Packs/CaseManagement-Generic/Scripts/CaseMgmtIncidentTypesByRole/CaseMgmtIncidentTypesByRole.yml
  Packs/CaseManagement-Generic/Scripts/CaseMgmtIncidentTypesByRole/README.md
  Packs/CaseManagement-Generic/Scripts/CaseMgmtIncidentTypesDisplay/CaseMgmtIncidentTypesDisplay.yml
  Packs/CaseManagement-Generic/Scripts/CaseMgmtIncidentTypesDisplay/README.md
  Packs/CaseManagement-Generic/Scripts/CaseMgmtResponseProcess/CaseMgmtResponseProcess.py
  Packs/CaseManagement-Generic/Scripts/CaseMgmtResponseProcess/CaseMgmtResponseProcess.yml
  Packs/CaseManagement-Generic/Scripts/CaseMgmtResponseProcess/README.md
  Packs/CaseManagement-Generic/Scripts/CloseLinkedIncidentsPostProcessing/CloseLinkedIncidentsPostProcessing.py
  Packs/CaseManagement-Generic/Scripts/CloseLinkedIncidentsPostProcessing/CloseLinkedIncidentsPostProcessing.yml
  Packs/CaseManagement-Generic/Scripts/CloseLinkedIncidentsPostProcessing/README.md
  Packs/CaseManagement-Generic/Scripts/CompleteTaskOnTimerBreach/CompleteTaskOnTimerBreach.yml
  Packs/CaseManagement-Generic/Scripts/CompleteTaskOnTimerBreach/README.md
  Packs/CaseManagement-Generic/Scripts/TimersOnOwnerChange/README.md
  Packs/CaseManagement-Generic/Scripts/TimersOnOwnerChange/TimersOnOwnerChange.yml
  Packs/CaseManagement-Generic/doc_files/Case_Management_-_Generic.png
  Packs/CaseManagement-Generic/doc_files/Case_Management_-_Generic_-_Send_On_Call_Notification.png
  Packs/CaseManagement-Generic/doc_files/Case_Management_-_Generic_-_Set_SLAs_based_on_Severity.png
  Packs/CaseManagement-Generic/doc_files/Case_Management_-_Generic_-_Start_SLA_Timers.png
  Packs/CaseManagement-Generic/doc_files/Case_Management_-_Generic_v2.png
  Packs/CaseManagement-Generic/pack_metadata.json
Labels: Contribution, docs-approved, Contribution Form Filled, Community

#25286 EXPANDR-1610 Qualys integration - Add "details" arg to qualys-host-list command
  Packs/qualys/Integrations/Qualysv2/Qualysv2.py
  Packs/qualys/Integrations/Qualysv2/Qualysv2.yml
  Packs/qualys/Integrations/Qualysv2/README.md
  Packs/qualys/ReleaseNotes/1_2_3.md
  Packs/qualys/pack_metadata.json
Labels: Contribution, docs-approved, Contribution Form Filled, Community
