Repository demisto/content, pull requests merged in 2023-07, with the labels that each got.

#27770 Test Playbook - CrowdStrike Falcon - Retrieve File
  Packs/CrowdStrikeFalcon/Playbooks/playbook-CrowdStrike_Falcon_-_Retrieve_File.yml
  Packs/CrowdStrikeFalcon/ReleaseNotes/1_10_29.md
  Packs/CrowdStrikeFalcon/TestPlaybooks/Test_Playbook_-_CrowdStrike_Falcon_-_Retrieve_File.yml
  Packs/CrowdStrikeFalcon/pack_metadata.json
  Tests/conf.json
Labels: docs-approved

#27626 Traceable AI API Security Platform Integration
  Packs/Traceable/.pack-ignore
  Packs/Traceable/.secrets-ignore
  Packs/Traceable/Author_image.png
  Packs/Traceable/Integrations/Traceable/README.md
  Packs/Traceable/Integrations/Traceable/Traceable.py
  Packs/Traceable/Integrations/Traceable/Traceable.yml
  Packs/Traceable/Integrations/Traceable/Traceable_description.md
  Packs/Traceable/Integrations/Traceable/Traceable_image.png
  Packs/Traceable/Integrations/Traceable/Traceable_test.py
  Packs/Traceable/Integrations/Traceable/command_examples
  Packs/Traceable/README.md
  Packs/Traceable/pack_metadata.json
Labels: Contribution, docs-approved, Partner, ready-for-instance-test, post-demo, Contribution Form Filled, pending-contributor, Partner Support Level

#27702 xsiam-model-rule-schema-is-array-toggling-fix-1
  Packs/GoogleDrive/ModelingRules/GoogleDrive_1_3/GoogleDrive_1_3.yml
  Packs/GoogleDrive/ModelingRules/GoogleDrive_1_3/GoogleDrive_1_3_schema.json
  Packs/GoogleDrive/ParsingRules/GoogleDrive/GoogleDrive.yml
  Packs/GoogleDrive/ReleaseNotes/1_2_35.md
  Packs/GoogleDrive/pack_metadata.json
  Packs/MicrosoftCloudAppSecurity/ModelingRules/MicrosoftCloudAppSecurity_1_3/MicrosoftCloudAppSecurity_1_3.xif
  Packs/MicrosoftCloudAppSecurity/ModelingRules/MicrosoftCloudAppSecurity_1_3/MicrosoftCloudAppSecurity_1_3.yml
  Packs/MicrosoftCloudAppSecurity/ModelingRules/MicrosoftCloudAppSecurity_1_3/MicrosoftCloudAppSecurity_1_3_schema.json
  Packs/MicrosoftCloudAppSecurity/ParsingRules/MicrosoftCloudAppSecurity/MicrosoftCloudAppSecurity.yml
  Packs/MicrosoftCloudAppSecurity/ReleaseNotes/2_1_33.md
  Packs/MicrosoftCloudAppSecurity/pack_metadata.json
  Packs/MicrosoftDefenderAdvancedThreatProtection/ModelingRules/Microsoft365DefenderEventCollector_1_3/Microsoft365DefenderEventCollector_1_3.yml
  Packs/MicrosoftDefenderAdvancedThreatProtection/ModelingRules/Microsoft365DefenderEventCollector_1_3/Microsoft365DefenderEventCollector_1_3_schema.json
  Packs/MicrosoftDefenderAdvancedThreatProtection/ParsingRules/MicrosoftDefenderAdvancedThreatProtection/MicrosoftDefenderAdvancedThreatProtection.yml
  Packs/MicrosoftDefenderAdvancedThreatProtection/ReleaseNotes/1_15_28.md
  Packs/MicrosoftDefenderAdvancedThreatProtection/pack_metadata.json
Labels: docs-approved

#26927 Enable branch protection for all contributor branches
  .github/workflows/protect-infra-directories.yml
Labels: docs-approved

#27847 GetListRow: fix code to align context path
  Packs/CommonScripts/ReleaseNotes/1_11_92.md
  Packs/CommonScripts/Scripts/GetlistRow/GetListRow.py
  Packs/CommonScripts/Scripts/GetlistRow/GetListRow.yml
  Packs/CommonScripts/Scripts/GetlistRow/GetListRow_test.py
  Packs/CommonScripts/pack_metadata.json
Labels: docs-approved

#27701 create McAfee NSM modeling rules
  Packs/McAfeeNSM/ModelingRules/McAfeeNSM_1_3/McAfeeNSM_1_3.xif
  Packs/McAfeeNSM/ModelingRules/McAfeeNSM_1_3/McAfeeNSM_1_3.yml
  Packs/McAfeeNSM/ModelingRules/McAfeeNSM_1_3/McAfeeNSM_1_3_schema.json
  Packs/McAfeeNSM/ParsingRules/McAfeeNSM/McAfeeNSM.xif
  Packs/McAfeeNSM/ParsingRules/McAfeeNSM/McAfeeNSM.yml
  Packs/McAfeeNSM/README.md
  Packs/McAfeeNSM/ReleaseNotes/1_2_6.md
  Packs/McAfeeNSM/doc_imgs/nsm_add_target_server.png
  Packs/McAfeeNSM/doc_imgs/nsm_audit_severity_mapping.png
  Packs/McAfeeNSM/doc_imgs/nsm_faults_severity_mapping.png
  Packs/McAfeeNSM/doc_imgs/nsm_ips_severity_mapping.png
  Packs/McAfeeNSM/pack_metadata.json
Labels: docs-approved

#27839 Test Playbook For MDE - Retrieve File
  Packs/MicrosoftDefenderAdvancedThreatProtection/Playbooks/playbook-MDE_-_Retrieve_File.yml
  Packs/MicrosoftDefenderAdvancedThreatProtection/ReleaseNotes/1_15_29.md
  Packs/MicrosoftDefenderAdvancedThreatProtection/TestPlaybooks/Test_Playbook_-_MDE_-_Retrieve_File.yml
  Packs/MicrosoftDefenderAdvancedThreatProtection/pack_metadata.json
  Tests/conf.json
Labels: docs-approved

#27849 Update DBotPredictPhishingWords docker
  Packs/Base/ReleaseNotes/1_32_19.md
  Packs/Base/Scripts/DBotPredictPhishingWords/DBotPredictPhishingWords.yml
  Packs/Base/pack_metadata.json
Labels: docs-approved

#27836 Fix for 'MDE - Host Advanced Hunting For Powershell Executions' playbook
  Packs/MicrosoftDefenderAdvancedThreatProtection/Playbooks/playbook-MDE_-_Host_Advanced_Hunting_For_Powershell_Executions.yml
  Packs/MicrosoftDefenderAdvancedThreatProtection/ReleaseNotes/1_15_30.md
  Packs/MicrosoftDefenderAdvancedThreatProtection/pack_metadata.json
Labels: docs-approved

#27838 Test Playbook - MDE SIEM ingestion - Get Incident Data
  Packs/MicrosoftDefenderAdvancedThreatProtection/Playbooks/playbook-MDE_SIEM_ingestion_-_Get_Incident_Data.yml
  Packs/MicrosoftDefenderAdvancedThreatProtection/ReleaseNotes/1_15_31.md
  Packs/MicrosoftDefenderAdvancedThreatProtection/TestPlaybooks/Test_Playbook_-_MDE_SIEM_ingestion_-_Get_Incident_Data.yml
  Packs/MicrosoftDefenderAdvancedThreatProtection/pack_metadata.json
  Tests/conf.json
Labels: docs-approved

#27718 Align credentials stores part 26
  Packs/CheckPhish/.pack-ignore
  Packs/CheckPhish/Integrations/CheckPhish/CheckPhish.py
  Packs/CheckPhish/Integrations/CheckPhish/CheckPhish.yml
  Packs/CheckPhish/ReleaseNotes/1_0_18.md
  Packs/CheckPhish/pack_metadata.json
  Packs/isight/.pack-ignore
  Packs/isight/Integrations/FireEyeISIGHT/FireEyeISIGHT.js
  Packs/isight/Integrations/FireEyeISIGHT/FireEyeISIGHT.yml
  Packs/isight/Integrations/FireEyeISIGHT/FireEyeISIGHT_description.md
  Packs/isight/Integrations/FireEyeISIGHT/README.md
  Packs/isight/ReleaseNotes/1_0_3.md
  Packs/isight/pack_metadata.json
  Tests/conf.json
Labels: docs-approved, ForceMerge

#27846 [Microsoft Teams] Fix URL RegEx
  Packs/MicrosoftTeams/Integrations/MicrosoftTeams/MicrosoftTeams.py
  Packs/MicrosoftTeams/Integrations/MicrosoftTeams/MicrosoftTeams_test.py
  Packs/MicrosoftTeams/ReleaseNotes/1_4_22.md
  Packs/MicrosoftTeams/pack_metadata.json
Labels: docs-approved

#27794 OPSWAT Filescan Sandbox (rename)
  Packs/OPSWAT-Filescan/.pack-ignore
  Packs/OPSWAT-Filescan/Author_image.png
  Packs/OPSWAT-Filescan/Integrations/OPSWATFilescan/OPSWATFilescan.py
  Packs/OPSWAT-Filescan/Integrations/OPSWATFilescan/OPSWATFilescan.yml
  Packs/OPSWAT-Filescan/Integrations/OPSWATFilescan/OPSWATFilescan_description.md
  Packs/OPSWAT-Filescan/Integrations/OPSWATFilescan/OPSWATFilescan_image.png
  Packs/OPSWAT-Filescan/Integrations/OPSWATFilescan/OPSWATFilescan_test.py
  Packs/OPSWAT-Filescan/Integrations/OPSWATFilescan/README.md
  Packs/OPSWAT-Filescan/README.md
  Packs/OPSWAT-Filescan/ReleaseNotes/1_0_1.md
  Packs/OPSWAT-Filescan/pack_metadata.json
Labels: Contribution, Partner, ready-for-instance-test, Contribution Form Filled, Partner Support Level

#27859 [Delete Custom Content] Add input - `using`
  Packs/ContentManagement/.pack-ignore
  Packs/ContentManagement/Playbooks/playbook-Delete_Custom_Content.yml
  Packs/ContentManagement/Playbooks/playbook-Delete_Custom_Content_README.md
  Packs/ContentManagement/ReleaseNotes/1_2_10.md
  Packs/ContentManagement/Scripts/DeleteContent/DeleteContent.py
  Packs/ContentManagement/Scripts/DeleteContent/DeleteContent.yml
  Packs/ContentManagement/pack_metadata.json
Labels: docs-approved

#23690 migrate to gcp
  .circleci/config.yml
  .gitlab/ci/bucket-upload.yml
  .gitlab/ci/global.yml
  .gitlab/ci/instance-test.yml
  .gitlab/ci/on-push.yml
  .gitlab/ci/sdk-nightly.yml
  Tests/Marketplace/configure_and_install_packs.py
  Tests/configure_and_test_integration_instances.py
  Tests/lastest_server_build_scripts/download_demisto_conf.sh
  Tests/lastest_server_build_scripts/run_installer_on_instance.sh
  Tests/scripts/check_jobs_done.py
  Tests/scripts/collect_tests/utils.py
  Tests/scripts/destroy_instances.py
  Tests/scripts/destroy_instances.sh
  Tests/scripts/download_conf_repos.sh
  Tests/scripts/infrastructure_tests/test_collect_tests.py
  Tests/scripts/infrastructure_tests/tests_data/collect_tests/D/Packs/myPack/TestPlaybooks/myTestPlaybook.yml
  Tests/scripts/infrastructure_tests/tests_data/collect_tests/D/Tests/id_set.json
  Tests/scripts/linters_runner.sh
  Tests/scripts/pyflake.sh
  Tests/scripts/run_installer_on_instance.sh
  Tests/scripts/validate_premium_packs.py
  Tests/scripts/wait_until_server_ready.py
  Tests/test_content.py
  Tests/test_integration.py
  Tests/tools.py
  poetry.lock
  pyproject.toml
Labels: docs-approved

#27811 [AbnormalSecurity] Update documentation and examples
  Packs/AbnormalSecurity/Integrations/AbnormalSecurity/AbnormalSecurity.py
  Packs/AbnormalSecurity/Integrations/AbnormalSecurity/AbnormalSecurity.yml
  Packs/AbnormalSecurity/Integrations/AbnormalSecurity/README.md
  Packs/AbnormalSecurity/Integrations/AbnormalSecurity/command_examples
  Packs/AbnormalSecurity/ReleaseNotes/2_0_21.md
  Packs/AbnormalSecurity/pack_metadata.json
Labels: Contribution, Partner, ready-for-instance-test, Contribution Form Filled, Partner Support Level

#26925 Jb zoom enhancement
  Packs/ApiModules/Scripts/ZoomApiModule/ZoomApiModule.py
  Packs/Zoom/.secrets-ignore
  Packs/Zoom/Integrations/Zoom/README.md
  Packs/Zoom/Integrations/Zoom/Zoom.py
  Packs/Zoom/Integrations/Zoom/Zoom.yml
  Packs/Zoom/Integrations/Zoom/Zoom_test.py
  Packs/Zoom/Integrations/Zoom/commands.txt
  Packs/Zoom/ReleaseNotes/1_5_0.md
  Packs/Zoom/TestPlaybooks/playbook-TestZoomChat.yml
  Packs/Zoom/pack_metadata.json
Labels: docs-approved

#27602 change Ansible Tower pack name
  Packs/AnsibleTower/.pack-ignore
  Packs/AnsibleTower/Integrations/AnsibleTower/AnsibleTower.yml
  Packs/AnsibleTower/Integrations/AnsibleTower/AnsibleTower_description.md
  Packs/AnsibleTower/Integrations/AnsibleTower/AnsibleTower_image.png
  Packs/AnsibleTower/Integrations/AnsibleTower/README.md
  Packs/AnsibleTower/Playbooks/Ansible_Tower-_ad_hoc_command-_generic_polling.yml
  Packs/AnsibleTower/Playbooks/Ansible_Tower-_ad_hoc_command-_generic_polling_README.md
  Packs/AnsibleTower/Playbooks/Ansible_Tower-_job_generic_polling.yml
  Packs/AnsibleTower/Playbooks/Ansible_Tower-_job_generic_polling_README.md
  Packs/AnsibleTower/ReleaseNotes/1_1_0.md
  Packs/AnsibleTower/pack_metadata.json
Labels: docs-approved

#27488 [CrowdStrikeFalcon] Behaviours Pattern Disposition Details (new field)
  Packs/CrowdStrikeFalcon/Classifiers/classifier-CrowdStrike_Falcon_Mapper_6.5.json
  Packs/CrowdStrikeFalcon/IncidentFields/incidentfield-Behaviour_Pattern_Disposition_Details.json
  Packs/CrowdStrikeFalcon/ReleaseNotes/1_10_30.md
  Packs/CrowdStrikeFalcon/pack_metadata.json
Labels: Contribution, docs-approved, ready-for-instance-test, post-demo, Contribution Form Filled, Community, pending-contributor, Xsoar Support Level

#27856 [MyToDoTasksWidget] automation query bug fix
  Packs/CommonWidgets/.pack-ignore
  Packs/CommonWidgets/ReleaseNotes/1_2_25.md
  Packs/CommonWidgets/Scripts/MyToDoTasksWidget/MyToDoTasksWidget.py
  Packs/CommonWidgets/Scripts/MyToDoTasksWidget/MyToDoTasksWidget.yml
  Packs/CommonWidgets/Scripts/MyToDoTasksWidget/README.md
  Packs/CommonWidgets/pack_metadata.json
Labels: docs-approved

#27693 add warning message not to press the test button twice
  Packs/EDL/Integrations/EDL/EDL.yml
  Packs/EDL/Integrations/EDL/EDL_description.md
  Packs/EDL/Integrations/EDL/README.md
  Packs/EDL/ReleaseNotes/3_2_1.md
  Packs/EDL/pack_metadata.json
Labels: docs-approved

#27860 FeedTAXII2: return report object with the relationships
  Packs/ApiModules/Scripts/TAXII2ApiModule/TAXII2ApiModule.py
  Packs/ApiModules/Scripts/TAXII2ApiModule/TAXII2ApiModule_test.py
  Packs/ApiModules/Scripts/TAXII2ApiModule/test_data/id_to_object_test.json
  Packs/ApiModules/Scripts/TAXII2ApiModule/test_data/objects_envelopes_v20.json
  Packs/ApiModules/Scripts/TAXII2ApiModule/test_data/objects_envelopes_v21.json
  Packs/ApiModules/Scripts/TAXII2ApiModule/test_data/parsed_stix_objects.json
  Packs/FeedDHS/Integrations/DHSFeedV2/DHSFeedV2.py
  Packs/FeedDHS/ReleaseNotes/2_0_13.md
  Packs/FeedDHS/pack_metadata.json
  Packs/FeedMitreAttackv2/ReleaseNotes/1_1_14.md
  Packs/FeedMitreAttackv2/pack_metadata.json
  Packs/FeedTAXII/ReleaseNotes/1_1_28.md
  Packs/FeedTAXII/pack_metadata.json
Labels: docs-approved

#27899 Add a note to XDR readme
  Packs/CortexXDR/Integrations/CortexXDRIR/README.md
Labels: docs-approved

#27003 update Uptycs jwt token authentication and add new commands
  Packs/Uptycs/Integrations/Uptycs/README.md
  Packs/Uptycs/Integrations/Uptycs/Uptycs.py
  Packs/Uptycs/Integrations/Uptycs/Uptycs.yml
  Packs/Uptycs/Integrations/Uptycs/Uptycs_test.py
  Packs/Uptycs/Integrations/Uptycs/test_data/blob.tar
  Packs/Uptycs/Integrations/Uptycs/test_data/look_up_table_test.csv
  Packs/Uptycs/ReleaseNotes/1_0_9.md
  Packs/Uptycs/pack_metadata.json
Labels: Contribution, docs-approved, Partner, ready-for-instance-test, pending-demo, post-demo, Contribution Form Filled, Partner Support Level

#27930 Add IN145 To Failing Integrations
  Packs/AnsibleCiscoIOS/.pack-ignore
  Packs/AnsibleKubernetes/.pack-ignore
  Packs/AnsibleLinux/.pack-ignore
  Packs/AzureKeyVault/.pack-ignore
  Packs/CloudConvert/.pack-ignore
  Packs/FreshDesk/.pack-ignore
  Packs/GoogleKubernetesEngine/.pack-ignore
  Packs/GoogleSafeBrowsing/.pack-ignore
  Packs/GoogleVault/.pack-ignore
  Packs/Jira/.pack-ignore
  Packs/Perch/.pack-ignore
  Packs/SalesforceFusion/.pack-ignore
  Packs/SplunkPyPreRelease/.pack-ignore
  Packs/TrendMicroCAS/.pack-ignore
  Packs/TrendMicroDDA/.pack-ignore
  Packs/VMwareWorkspaceONEUEM/.pack-ignore
  Packs/VersaDirector/.pack-ignore
  Packs/cyberark_AIM/.pack-ignore
Labels: docs-approved

#27907 CIRCL CVE Search parse CVSS version
  Packs/CIRCL/Integrations/CirclCVESearch/CirclCVESearch.py
  Packs/CIRCL/Integrations/CirclCVESearch/CirclCVESearch_test.py
  Packs/CIRCL/ReleaseNotes/1_0_13.md
  Packs/CIRCL/ReleaseNotes/1_0_14.md
  Packs/CIRCL/pack_metadata.json
Labels: docs-approved

#27908 Gmail integration query - change default value
  Packs/CommonScripts/Scripts/EmailAskUser/README.md
  Packs/Gmail/Integrations/Gmail/Gmail.yml
  Packs/Gmail/ReleaseNotes/1_3_11.md
  Packs/Gmail/pack_metadata.json
Labels: docs-approved

#27923 Add Xpanse MP to Jira Pack
  Packs/Jira/.pack-ignore
  Packs/Jira/ReleaseNotes/3_0_5.md
  Packs/Jira/pack_metadata.json
Labels: Contribution, Contribution Form Filled, Community, Xsoar Support Level

#27812 Test Playbook - MDE Malware - Incident Enrichment
  Packs/MicrosoftDefenderAdvancedThreatProtection/Playbooks/playbook-MDE_Malware_-_Incident_Enrichment.yml
  Packs/MicrosoftDefenderAdvancedThreatProtection/ReleaseNotes/1_15_32.md
  Packs/MicrosoftDefenderAdvancedThreatProtection/TestPlaybooks/Test_Playbook_-_MDE_Malware_-_Incident_Enrichment.yml
  Packs/MicrosoftDefenderAdvancedThreatProtection/pack_metadata.json
  Tests/conf.json
Labels: docs-approved

#27931 removed packs from unremovable pacs
  .gitlab/ci/bucket-upload.yml
  .gitlab/ci/on-push.yml
  Tests/Marketplace/search_and_uninstall_pack.py
  Tests/configure_and_test_integration_instances.py
Labels: docs-approved, ForceMerge

#27941 Kaspersky Security Center - add test pb to conf.json
  Packs/Campaign/ReleaseNotes/3_3_3.md
  Packs/Campaign/Scripts/CollectCampaignRecipients/CollectCampaignRecipients.py
  Packs/Campaign/Scripts/CollectCampaignRecipients/CollectCampaignRecipients.yml
  Packs/Campaign/pack_metadata.json
  Packs/CommonScripts/Scripts/UnzipFile/data_test/testZip.yml
  Packs/KasperskySecurityCenter/TestPlaybooks/Kaspersky_Security_Center_-_Test.yml
  Tests/conf.json
Labels: docs-approved, ForceMerge

#27919 [DBotPredictURLPhishing] Update Error Message
  Packs/PhishingURL/ReleaseNotes/1_1_3.md
  Packs/PhishingURL/Scripts/DBotPredictURLPhishing/DBotPredictURLPhishing.py
  Packs/PhishingURL/Scripts/DBotPredictURLPhishing/dbotpredicturlphishing_test.py
  Packs/PhishingURL/pack_metadata.json
Labels: docs-approved, ForceMerge

#27944 Contribution - Add Jira to Xpanse MP
  Packs/Jira/ReleaseNotes/3_0_5.md
  Packs/Jira/pack_metadata.json
  Tests/known_words.txt
Labels: docs-approved

#27624 [ASM] - Expandr 4735
  Packs/CortexAttackSurfaceManagement/ReleaseNotes/1_6_21.md
  Packs/CortexAttackSurfaceManagement/Scripts/RankServiceOwners/RankServiceOwners.py
  Packs/CortexAttackSurfaceManagement/Scripts/RankServiceOwners/RankServiceOwners_test.py
  Packs/CortexAttackSurfaceManagement/pack_metadata.json
Labels: Contribution, docs-approved, ready-for-instance-test, Contribution Form Filled, Community, pending-contributor, Xsoar Support Level

#27858 Crowdstrike falcon run command timeout
  Packs/CrowdStrikeFalcon/Integrations/CrowdStrikeFalcon/CrowdStrikeFalcon.py
  Packs/CrowdStrikeFalcon/Integrations/CrowdStrikeFalcon/CrowdStrikeFalcon.yml
  Packs/CrowdStrikeFalcon/Integrations/CrowdStrikeFalcon/README.md
  Packs/CrowdStrikeFalcon/ReleaseNotes/1_10_31.md
  Packs/CrowdStrikeFalcon/pack_metadata.json
Labels: docs-approved

#27566 Add GitHub trigger and GitHub list workflow commands
  Packs/GitHub/Integrations/GitHub/GitHub.py
  Packs/GitHub/Integrations/GitHub/GitHub.yml
  Packs/GitHub/Integrations/GitHub/GitHub_test.py
  Packs/GitHub/Integrations/GitHub/README.md
  Packs/GitHub/Integrations/GitHub/command_examples
  Packs/GitHub/Integrations/GitHub/test_data/list_workflow.json
  Packs/GitHub/ReleaseNotes/2_0_15.md
  Packs/GitHub/pack_metadata.json
Labels: docs-approved

#27915 MS Azure Events Hub to Hidden
  Packs/AzureEventsHub/ReleaseNotes/1_0_5.md
  Packs/AzureEventsHub/pack_metadata.json
Labels: docs-approved

#27806 Linux Events Update
  Packs/LinuxEventsCollection/ModelingRules/LinuxEventsCollection_1_3/LinuxEventsCollection_1_3.xif
  Packs/LinuxEventsCollection/ModelingRules/LinuxEventsCollection_1_3/LinuxEventsCollection_1_3.yml
  Packs/LinuxEventsCollection/ParsingRules/LinuxEventsCollectionParsingRules/LinuxEventsCollectionParsingRules.xif
  Packs/LinuxEventsCollection/ParsingRules/LinuxEventsCollectionParsingRules/LinuxEventsCollectionParsingRules.yml
  Packs/LinuxEventsCollection/ReleaseNotes/1_0_5.md
  Packs/LinuxEventsCollection/pack_metadata.json
Labels: docs-approved

#27873 Fix forcepointdlp datasetname
  Packs/ForcepointDLP/ModelingRules/ForcepointDLP_1_4/ForcepointDLP_1_4.xif
  Packs/ForcepointDLP/ModelingRules/ForcepointDLP_1_4/ForcepointDLP_1_4_schema.json
  Packs/ForcepointDLP/ParsingRules/ForcepointDLP/ForcepointDLP.xif
  Packs/ForcepointDLP/ParsingRules/ForcepointDLP/ForcepointDLP.yml
  Packs/ForcepointDLP/README.md
  Packs/ForcepointDLP/ReleaseNotes/1_0_1.md
  Packs/ForcepointDLP/pack_metadata.json
Labels: docs-approved

#27927 Taxii2 feed: fixed an issue where the custom fields is returned outside the custom_fields dict
  Packs/ApiModules/ReleaseNotes/2_2_17.md
  Packs/ApiModules/Scripts/TAXII2ApiModule/TAXII2ApiModule.py
  Packs/ApiModules/Scripts/TAXII2ApiModule/TAXII2ApiModule_test.py
  Packs/ApiModules/pack_metadata.json
  Packs/FeedDHS/ReleaseNotes/2_0_14.md
  Packs/FeedDHS/pack_metadata.json
  Packs/FeedMitreAttackv2/ReleaseNotes/1_1_15.md
  Packs/FeedMitreAttackv2/pack_metadata.json
  Packs/FeedTAXII/ReleaseNotes/1_1_29.md
  Packs/FeedTAXII/pack_metadata.json
Labels: docs-approved

#27953 Ignore any Python update in ApiModules, until we can properly determine their desired version.
  pyproject.toml
Labels: docs-approved

#27326 Sourcery config
  .sourcery.yaml
Labels: docs-approved

#27938 Fixed cveReputationV2 to handle None value
  Packs/CommonScripts/ReleaseNotes/1_11_93.md
  Packs/CommonScripts/Scripts/CveReputationV2/CveReputationV2.py
  Packs/CommonScripts/Scripts/CveReputationV2/CveReputationV2_test.py
  Packs/CommonScripts/pack_metadata.json
Labels: docs-approved

#27728 xsiam-model-rule-schema-is-array-toggling-fix-2
  Packs/Mimecast/ModelingRules/MimecastModelingRules_1_3/MimecastModelingRules_1_3.xif
  Packs/Mimecast/ModelingRules/MimecastModelingRules_1_3/MimecastModelingRules_1_3.yml
  Packs/Mimecast/ModelingRules/MimecastModelingRules_1_3/MimecastModelingRules_1_3_schema.json
  Packs/Mimecast/ParsingRules/MimecastParsingRules/MimecastParsingRules.yml
  Packs/Mimecast/ReleaseNotes/2_1_8.md
  Packs/Mimecast/ReleaseNotes/2_1_9.md
  Packs/Mimecast/pack_metadata.json
  Packs/Okta/ModelingRules/OktaModelingRules_1_3/OktaModelingRules_1_3.yml
  Packs/Okta/ModelingRules/OktaModelingRules_1_3/OktaModelingRules_1_3_schema.json
  Packs/Okta/ParsingRules/Okta/Okta.yml
  Packs/Okta/ReleaseNotes/3_1_22.md
  Packs/Okta/pack_metadata.json
  Packs/OneLogin/.pack-ignore
  Packs/OneLogin/.secrets-ignore
  Packs/OneLogin/ModelingRules/OneLoginModelingRules_1_3/OneLoginModelingRules_1_3.xif
  Packs/OneLogin/ModelingRules/OneLoginModelingRules_1_3/OneLoginModelingRules_1_3.yml
  Packs/OneLogin/ModelingRules/OneLoginModelingRules_1_3/OneLoginModelingRules_1_3_schema.json
  Packs/OneLogin/ReleaseNotes/1_0_6.md
  Packs/OneLogin/ReleaseNotes/1_0_7.md
  Packs/OneLogin/pack_metadata.json
Labels: docs-approved

#27952 Fix test traceable
  Packs/Traceable/Integrations/Traceable/Traceable_test.py
Labels: docs-approved

#27959 forcepoint dlp update readme
  Packs/ForcepointDLP/README.md
Labels: docs-approved

#27928 Replace cve_id with cve for cve command in CS falcon integration
  Packs/CrowdStrikeFalcon/Integrations/CrowdStrikeFalcon/CrowdStrikeFalcon.py
  Packs/CrowdStrikeFalcon/Integrations/CrowdStrikeFalcon/CrowdStrikeFalcon.yml
  Packs/CrowdStrikeFalcon/Integrations/CrowdStrikeFalcon/README.md
  Packs/CrowdStrikeFalcon/ReleaseNotes/1_10_31.md
  Packs/CrowdStrikeFalcon/ReleaseNotes/1_10_32.md
  Packs/CrowdStrikeFalcon/pack_metadata.json
Labels: docs-approved

#27957 Kill long running container when container is close
  Packs/ApiModules/Scripts/NGINXApiModule/NGINXApiModule.py
  Packs/EDL/ReleaseNotes/3_2_2.md
  Packs/EDL/pack_metadata.json
  Packs/ExportIndicators/ReleaseNotes/1_0_18.md
  Packs/ExportIndicators/pack_metadata.json
  Packs/TAXIIServer/ReleaseNotes/2_0_39.md
  Packs/TAXIIServer/pack_metadata.json
Labels: docs-approved

#27970 [ASM] - Expander 4135 - IPv4 / IPv6
  Packs/CortexAttackSurfaceManagement/Playbooks/Cortex_ASM_-_Enrichment.yml
  Packs/CortexAttackSurfaceManagement/ReleaseNotes/1_6_22.md
  Packs/CortexAttackSurfaceManagement/pack_metadata.json
Labels: Contribution, Contribution Form Filled, Community, Xsoar Support Level

#27946 Update README.md Dependencies and Troubleshooting
  Packs/Slack/Scripts/SlackBlockBuilder/README.md
Labels: Contribution, docs-approved, Contribution Form Filled, Community, Xsoar Support Level

#27939 CVECVSSColor auto adjust according to user theme color
  Packs/CommonScripts/ReleaseNotes/1_11_94.md
  Packs/CommonScripts/Scripts/CVECVSSColor/CVECVSSColor.py
  Packs/CommonScripts/Scripts/CVECVSSColor/CVECVSSColor_test.py
  Packs/CommonScripts/pack_metadata.json
Labels: docs-approved

#27986 Corrected "author"
  Packs/Traceable/pack_metadata.json
Labels: Contribution, Partner, Contribution Form Filled, Partner Support Level

#28003 XSIAM | Remove dependencies from Windows Packs & Fix for Windows Events Modeling (EventType)
  Packs/MicrosoftADFS/pack_metadata.json
  Packs/MicrosoftCore/pack_metadata.json
  Packs/MicrosoftWindowsEvents/ModelingRules/MicrosoftWindowsEvents_1_3/MicrosoftWindowsEvents_1_3.xif
  Packs/MicrosoftWindowsEvents/ReleaseNotes/1_0_5.md
  Packs/MicrosoftWindowsEvents/pack_metadata.json
Labels: docs-approved

#27412 Fortiweb enhancement
  Packs/FortinetFortiwebVM/.secrets-ignore
  Packs/FortinetFortiwebVM/Integrations/FortinetFortiwebVM/FortinetFortiwebVM.py
  Packs/FortinetFortiwebVM/Integrations/FortinetFortiwebVM/FortinetFortiwebVM.yml
  Packs/FortinetFortiwebVM/Integrations/FortinetFortiwebVM/FortinetFortiwebVM_description.md
  Packs/FortinetFortiwebVM/Integrations/FortinetFortiwebVM/FortinetFortiwebVM_test.py
  Packs/FortinetFortiwebVM/Integrations/FortinetFortiwebVM/README.md
  Packs/FortinetFortiwebVM/Integrations/FortinetFortiwebVM/test_data/server_pool/v1_list.json
  Packs/FortinetFortiwebVM/Integrations/FortinetFortiwebVM/test_data/server_pool/v2_create_update.json
  Packs/FortinetFortiwebVM/Integrations/FortinetFortiwebVM/test_data/server_pool/v2_get_op.json
  Packs/FortinetFortiwebVM/Integrations/FortinetFortiwebVM/test_data/server_pool/v2_get_rp.json
  Packs/FortinetFortiwebVM/Integrations/FortinetFortiwebVM/test_data/server_pool/v2_get_ti.json
  Packs/FortinetFortiwebVM/Integrations/FortinetFortiwebVM/test_data/server_pool/v2_get_ttp.json
  Packs/FortinetFortiwebVM/Integrations/FortinetFortiwebVM/test_data/server_pool/v2_get_wccp.json
  Packs/FortinetFortiwebVM/Integrations/FortinetFortiwebVM/test_data/server_pool/v2_list.json
  Packs/FortinetFortiwebVM/Integrations/FortinetFortiwebVM/test_data/server_pool_dependencies/v1_local_certificate.json
  Packs/FortinetFortiwebVM/Integrations/FortinetFortiwebVM/test_data/server_pool_dependencies/v1_network_interface.json
  Packs/FortinetFortiwebVM/Integrations/FortinetFortiwebVM/test_data/server_pool_dependencies/v1_persistence_policy.json
  Packs/FortinetFortiwebVM/Integrations/FortinetFortiwebVM/test_data/server_pool_dependencies/v1_server_health_check.json
  Packs/FortinetFortiwebVM/Integrations/FortinetFortiwebVM/test_data/server_pool_dependencies/v2_letsencrypt.json
  Packs/FortinetFortiwebVM/Integrations/FortinetFortiwebVM/test_data/server_pool_dependencies/v2_local_certificate.json
  Packs/FortinetFortiwebVM/Integrations/FortinetFortiwebVM/test_data/server_pool_dependencies/v2_multi_certificate.json
  Packs/FortinetFortiwebVM/Integrations/FortinetFortiwebVM/test_data/server_pool_dependencies/v2_network_interface.json
  Packs/FortinetFortiwebVM/Integrations/FortinetFortiwebVM/test_data/server_pool_dependencies/v2_persistence_policy.json
  Packs/FortinetFortiwebVM/Integrations/FortinetFortiwebVM/test_data/server_pool_dependencies/v2_sdn_connector.json
  Packs/FortinetFortiwebVM/Integrations/FortinetFortiwebVM/test_data/server_pool_dependencies/v2_server_health_check.json
  Packs/FortinetFortiwebVM/Integrations/FortinetFortiwebVM/test_data/server_pool_dependencies/v2_sni_certificate.json
  Packs/FortinetFortiwebVM/Integrations/FortinetFortiwebVM/test_data/server_pool_rule/v1_list.json
  Packs/FortinetFortiwebVM/Integrations/FortinetFortiwebVM/test_data/server_pool_rule/v2_create.json
  Packs/FortinetFortiwebVM/Integrations/FortinetFortiwebVM/test_data/server_pool_rule/v2_list.json
  Packs/FortinetFortiwebVM/Integrations/FortinetFortiwebVM/test_data/url_access_rule_condition/v1_create.json
  Packs/FortinetFortiwebVM/Integrations/FortinetFortiwebVM/test_data/url_access_rule_condition/v1_list.json
  Packs/FortinetFortiwebVM/Integrations/FortinetFortiwebVM/test_data/url_access_rule_condition/v2_create.json
  Packs/FortinetFortiwebVM/Integrations/FortinetFortiwebVM/test_data/url_access_rule_condition/v2_get.json
  Packs/FortinetFortiwebVM/Integrations/FortinetFortiwebVM/test_data/url_access_rule_condition/v2_list.json
  Packs/FortinetFortiwebVM/Integrations/FortinetFortiwebVM/test_data/url_access_rule_group/v1_list.json
  Packs/FortinetFortiwebVM/Integrations/FortinetFortiwebVM/test_data/url_access_rule_group/v2_create.json
  Packs/FortinetFortiwebVM/Integrations/FortinetFortiwebVM/test_data/url_access_rule_group/v2_list.json
  Packs/FortinetFortiwebVM/Integrations/FortinetFortiwebVM/test_data/url_access_rule_group/v2_update.json
  Packs/FortinetFortiwebVM/Integrations/FortinetFortiwebVM/test_data/v1_create_update_group.json
  Packs/FortinetFortiwebVM/Integrations/FortinetFortiwebVM/test_data/v1_delete.json
  Packs/FortinetFortiwebVM/Integrations/FortinetFortiwebVM/test_data/v2_delete.json
  Packs/FortinetFortiwebVM/Integrations/FortinetFortiwebVM/test_data/virtual_server_group/v1_list.json
  Packs/FortinetFortiwebVM/Integrations/FortinetFortiwebVM/test_data/virtual_server_group/v2_create.json
  Packs/FortinetFortiwebVM/Integrations/FortinetFortiwebVM/test_data/virtual_server_group/v2_list.json
  Packs/FortinetFortiwebVM/Integrations/FortinetFortiwebVM/test_data/virtual_server_item/v2_create_update.json
  Packs/FortinetFortiwebVM/Integrations/FortinetFortiwebVM/test_data/virtual_server_item/v2_list.json
  Packs/FortinetFortiwebVM/ReleaseNotes/2_0_0.md
  Packs/FortinetFortiwebVM/TestPlaybooks/playbook-FortiwebVMEnhancement_V1_Test.yml
  Packs/FortinetFortiwebVM/TestPlaybooks/playbook-FortiwebVMEnhancement_V2_Test.yml
  Packs/FortinetFortiwebVM/pack_metadata.json
Labels: Contribution, docs-approved, Contribution Form Filled, Community, Xsoar Support Level

#27751 xsiam-model-rule-schema-is-array-toggling-fix-3
  Packs/ProofpointTAP/.pack-ignore
  Packs/ProofpointTAP/ModelingRules/ProofpointTAPModelingRules_1_3/ProofpointTAPModelingRules_1_3.xif
  Packs/ProofpointTAP/ModelingRules/ProofpointTAPModelingRules_1_3/ProofpointTAPModelingRules_1_3.yml
  Packs/ProofpointTAP/ModelingRules/ProofpointTAPModelingRules_1_3/ProofpointTAPModelingRules_1_3_schema.json
  Packs/ProofpointTAP/ParsingRules/ProofpointTAP/ProofpointTAP.yml
  Packs/ProofpointTAP/ReleaseNotes/1_2_5.md
  Packs/ProofpointTAP/pack_metadata.json
  Packs/Tenable_io/.pack-ignore
  Packs/Tenable_io/ModelingRules/TenableioEventCollector_1_3/TenableioEventCollector_1_3.xif
  Packs/Tenable_io/ModelingRules/TenableioEventCollector_1_3/TenableioEventCollector_1_3.yml
  Packs/Tenable_io/ModelingRules/TenableioEventCollector_1_3/TenableioEventCollector_1_3_schema.json
  Packs/Tenable_io/ParsingRules/Tenable_ioParsingRules/Tenable_ioParsingRules.yml
  Packs/Tenable_io/ReleaseNotes/2_1_8.md
  Packs/Tenable_io/ReleaseNotes/2_1_9.md
  Packs/Tenable_io/pack_metadata.json
  Packs/Vectra_AI/ModelingRules/Vectra_AIEventCollector_1_3/Vectra_AIEventCollector_1_3.xif
  Packs/Vectra_AI/ModelingRules/Vectra_AIEventCollector_1_3/Vectra_AIEventCollector_1_3.yml
  Packs/Vectra_AI/ModelingRules/Vectra_AIEventCollector_1_3/Vectra_AIEventCollector_1_3_schema.json
  Packs/Vectra_AI/ReleaseNotes/1_2_5.md
  Packs/Vectra_AI/ReleaseNotes/1_2_6.md
  Packs/Vectra_AI/pack_metadata.json
Labels: docs-approved

#27783 Pwsh memory leak fix for ExtensionV3 & SafeLinks
  Packs/Microsoft365Defender/Integrations/O365DefenderSafeLinks/O365DefenderSafeLinks.ps1
  Packs/Microsoft365Defender/Integrations/O365DefenderSafeLinks/O365DefenderSafeLinks.yml
  Packs/Microsoft365Defender/Integrations/O365DefenderSafeLinks/README.md
  Packs/Microsoft365Defender/ReleaseNotes/4_5_7.md
  Packs/Microsoft365Defender/pack_metadata.json
  Packs/MicrosoftExchangeOnline/Integrations/EwsExtensionEXOPowershellV3/README.md
  Packs/MicrosoftExchangeOnline/ReleaseNotes/1_2_10.md
  Packs/MicrosoftExchangeOnline/pack_metadata.json
Labels: docs-approved

#28005 Add update-demisto-sdk-version GitHub action
  .github/workflows/update-demisto-sdk-version.yml
Labels: docs-approved

#28008 [RSA NetWitness] Code Improvements
  Packs/RSANetWitness_v11_1/.pack-ignore
  Packs/RSANetWitness_v11_1/Integrations/RSANetWitnessv115/RSANetWitnessv115.py
  Packs/RSANetWitness_v11_1/Integrations/RSANetWitnessv115/RSANetWitnessv115_test.py
  Packs/RSANetWitness_v11_1/ReleaseNotes/3_0_3.md
  Packs/RSANetWitness_v11_1/pack_metadata.json
Labels: docs-approved

#27347 Align credentials for GoogleKubernetesEngine, CloudConvert, GoogleSafeBrowsingV2
  Packs/CloudConvert/.pack-ignore
  Packs/CloudConvert/Integrations/CloudConvert/CloudConvert.py
  Packs/CloudConvert/Integrations/CloudConvert/CloudConvert.yml
  Packs/CloudConvert/Integrations/CloudConvert/CloudConvert_description.md
  Packs/CloudConvert/Integrations/CloudConvert/README.md
  Packs/CloudConvert/ReleaseNotes/1_0_7.md
  Packs/CloudConvert/pack_metadata.json
  Packs/GoogleKubernetesEngine/.pack-ignore
  Packs/GoogleKubernetesEngine/Integrations/GoogleKubernetesEngine/GoogleKubernetesEngine.py
  Packs/GoogleKubernetesEngine/Integrations/GoogleKubernetesEngine/GoogleKubernetesEngine.yml
  Packs/GoogleKubernetesEngine/Integrations/GoogleKubernetesEngine/README.md
  Packs/GoogleKubernetesEngine/ReleaseNotes/1_0_2.md
  Packs/GoogleKubernetesEngine/pack_metadata.json
  Packs/GoogleSafeBrowsing/Integrations/GoogleSafeBrowsingV2/GoogleSafeBrowsingV2.py
  Packs/GoogleSafeBrowsing/Integrations/GoogleSafeBrowsingV2/GoogleSafeBrowsingV2.yml
  Packs/GoogleSafeBrowsing/Integrations/GoogleSafeBrowsingV2/README.md
  Packs/GoogleSafeBrowsing/Integrations/GoogleSafeBrowsingV2/command_examples
  Packs/GoogleSafeBrowsing/Integrations/examples
  Packs/GoogleSafeBrowsing/ReleaseNotes/2_0_19.md
  Packs/GoogleSafeBrowsing/pack_metadata.json
  Tests/conf.json
Labels: docs-approved, ForceMerge

#27781 fix get_indicators_command
  Packs/SafeBreach/Integrations/SafeBreach_v2/SafeBreach_v2.py
  Packs/SafeBreach/Integrations/SafeBreach_v2/SafeBreach_v2_test.py
  Packs/SafeBreach/Integrations/SafeBreach_v2/test_data/remediation_data_with_unvaild_string.json
  Packs/SafeBreach/ReleaseNotes/1_2_4.md
  Packs/SafeBreach/pack_metadata.json
Labels: Contribution, docs-approved, Partner, ready-for-instance-test, Contribution Form Filled, Partner Support Level

#27888 Move LINK_PR_TO_JIRA_ISSUE to Content Gold NG
  .github/workflows/close_jira_issue_by_pr_merge.yml
  .github/workflows/link_edited_pr_to_jira_issue.yml
  Utils/github_workflow_scripts/jira_integration_scripts/link_pr_to_jira_issue.py
Labels: docs-approved

#27807 Added warning and color to gsm logs
  Tests/scripts/add_secrets_file_to_build.py
  Tests/scripts/utils/GoogleSecretManagerModule.py
Labels: docs-approved

#27993 Align Credentials For CyberArkAIM_v2, SalesforceFusionIAM, SplunkPyPreRelease
  Packs/SalesforceFusion/.pack-ignore
  Packs/SalesforceFusion/Integrations/SalesforceFusionIAM/SalesforceFusionIAM.py
  Packs/SalesforceFusion/Integrations/SalesforceFusionIAM/SalesforceFusionIAM.yml
  Packs/SalesforceFusion/ReleaseNotes/1_0_10.md
  Packs/SalesforceFusion/pack_metadata.json
  Packs/cyberark_AIM/.pack-ignore
  Packs/cyberark_AIM/Integrations/CyberArkAIM_v2/CyberArkAIM_v2.py
  Packs/cyberark_AIM/Integrations/CyberArkAIM_v2/CyberArkAIM_v2.yml
  Packs/cyberark_AIM/ReleaseNotes/1_0_13.md
  Packs/cyberark_AIM/pack_metadata.json
Labels: docs-approved

#28027 Parsing rules fix filter
  Packs/AzureEventsHub/ParsingRules/AzureEventsHub/AzureEventsHub.xif
  Packs/AzureEventsHub/ReleaseNotes/1_0_6.md
  Packs/AzureEventsHub/pack_metadata.json
  Packs/BrocadeSwitch/ParsingRules/BrocadeSwitch/BrocadeSwitch.xif
  Packs/BrocadeSwitch/ReleaseNotes/1_0_8.md
  Packs/BrocadeSwitch/pack_metadata.json
  Packs/MicrosoftCore/ParsingRules/MicrosoftCommonParsingRules/MicrosoftCommonParsingRules.xif
  Packs/MicrosoftCore/ReleaseNotes/1_0_1.md
  Packs/MicrosoftCore/pack_metadata.json
  Packs/MicrosoftDNS/ParsingRules/MicrosoftDNS/MicrosoftDNS.xif
  Packs/MicrosoftDNS/ReleaseNotes/1_0_5.md
  Packs/MicrosoftDNS/pack_metadata.json
  Packs/MicrosoftNPS/ParsingRules/MicrosoftNPSParsingRules/MicrosoftNPSParsingRules.xif
  Packs/MicrosoftNPS/ReleaseNotes/1_0_5.md
  Packs/MicrosoftNPS/pack_metadata.json
  Packs/VMwareVCenter/ParsingRules/VMwareVcenterParsingRules/VMwareVcenterParsingRules.xif
  Packs/VMwareVCenter/ReleaseNotes/1_0_9.md
  Packs/VMwareVCenter/pack_metadata.json
Labels: docs-approved

#27901 Enhance the lookback
  Packs/Base/ReleaseNotes/1_32_20.md
  Packs/Base/Scripts/CommonServerPython/CommonServerPython.py
  Packs/Base/Scripts/CommonServerPython/CommonServerPython_test.py
  Packs/Base/pack_metadata.json
  Packs/CrowdStrikeFalcon/Integrations/CrowdStrikeFalcon/CrowdStrikeFalcon_test.py
  Packs/Exabeam/Integrations/Exabeam/test_data/response_incidents.py
Labels: docs-approved

#28041 Documentation changes
  Packs/DomainToolsIrisDetect/Integrations/DomainToolsIrisDetect/README.md
  Packs/DomainToolsIrisDetect/README.md
  Packs/DomainToolsIrisDetect/pack_metadata.json
Labels: Contribution, docs-approved, Partner, ready-for-instance-test, Contribution Form Filled, Partner Support Level

#27958 TAXIIServer:add objects ref to report
  Packs/TAXIIServer/Integrations/TAXII2Server/TAXII2Server.py
  Packs/TAXIIServer/Integrations/TAXII2Server/TAXII2Server_test.py
  Packs/TAXIIServer/ReleaseNotes/2_0_40.md
  Packs/TAXIIServer/pack_metadata.json
Labels: docs-approved

#27795 [ASM] - Expander- 4148
  Packs/CortexAttackSurfaceManagement/IncidentFields/incidentfield-ASM_-_Remediation_Objectives.json
  Packs/CortexAttackSurfaceManagement/Playbooks/Cortex_ASM_-_ASM_Alert.yml
  Packs/CortexAttackSurfaceManagement/Playbooks/Cortex_ASM_-_Prisma_Cloud_Enrichment.yml
  Packs/CortexAttackSurfaceManagement/Playbooks/Cortex_ASM_-_Remediation.yml
  Packs/CortexAttackSurfaceManagement/Playbooks/Cortex_ASM_-_Remediation_Objectives.yml
  Packs/CortexAttackSurfaceManagement/Playbooks/Cortex_ASM_-_Remediation_Objectives_README.md
  Packs/CortexAttackSurfaceManagement/Playbooks/Cortex_ASM_-_Remediation_Path_Rules.yml
  Packs/CortexAttackSurfaceManagement/Playbooks/Cortex_ASM_-_Remediation_Path_Rules_README.md
  Packs/CortexAttackSurfaceManagement/README.md
  Packs/CortexAttackSurfaceManagement/ReleaseNotes/1_6_23.md
  Packs/CortexAttackSurfaceManagement/doc_files/Cortex_ASM_-_ASM_Alert.png
  Packs/CortexAttackSurfaceManagement/doc_files/Cortex_ASM_-_Remediation_Objectives.png
  Packs/CortexAttackSurfaceManagement/doc_files/Cortex_ASM_-_Remediation_Path_Rules.png
  Packs/CortexAttackSurfaceManagement/pack_metadata.json
Labels: Contribution, docs-approved, ready-for-instance-test, Contribution Form Filled, Community, Xsoar Support Level

#28030 [DBotAverageScore] Migrate to Python, and fix '0' average causing a null value
  Packs/CommonScripts/ReleaseNotes/1_11_97.md
  Packs/CommonScripts/Scripts/DBotAverageScore/DBotAverageScore.js
  Packs/CommonScripts/Scripts/DBotAverageScore/DBotAverageScore.py
  Packs/CommonScripts/Scripts/DBotAverageScore/DBotAverageScore.yml
  Packs/CommonScripts/Scripts/DBotAverageScore/DBotAverageScore_test.py
  Packs/CommonScripts/Scripts/DBotAverageScore/README.md
  Packs/CommonScripts/Scripts/DBotAverageScore/test_data/sample_data.json
  Packs/CommonScripts/pack_metadata.json
  Tests/known_words.txt
Labels: docs-approved, ForceMerge

#28029 fix WildFire v2 file command for files array
  Packs/Palo_Alto_Networks_WildFire/Integrations/Palo_Alto_Networks_WildFire_v2/Palo_Alto_Networks_WildFire_v2.py
  Packs/Palo_Alto_Networks_WildFire/Integrations/Palo_Alto_Networks_WildFire_v2/Palo_Alto_Networks_WildFire_v2_test.py
  Packs/Palo_Alto_Networks_WildFire/ReleaseNotes/2_1_29.md
  Packs/Palo_Alto_Networks_WildFire/pack_metadata.json
Labels: docs-approved, release-notes-only

#28010 Fix update dep workflow
  .github/workflows/update-demisto-sdk-version.yml
Labels: docs-approved

#27904 Core REST API - fix test module
  Packs/DemistoRESTAPI/Integrations/CoreRESTAPI/CoreRESTAPI.js
  Packs/DemistoRESTAPI/Integrations/DemistoRESTAPI/DemistoRESTAPI.js
  Packs/DemistoRESTAPI/ReleaseNotes/1_3_30.md
  Packs/DemistoRESTAPI/pack_metadata.json
Labels: docs-approved

#28048 Add inputs to GitHub workflows
  Packs/GitHub/Integrations/GitHub/GitHub.py
  Packs/GitHub/Integrations/GitHub/GitHub.yml
  Packs/GitHub/Integrations/GitHub/README.md
  Packs/GitHub/ReleaseNotes/2_0_17.md
  Packs/GitHub/pack_metadata.json
Labels: docs-approved

#27992 Align Credentials For FreshDesk, VMwareWorkspaceONEUEM, Perch, GoogleVault
  Packs/FreshDesk/.pack-ignore
  Packs/FreshDesk/Integrations/FreshDesk/FreshDesk.py
  Packs/FreshDesk/Integrations/FreshDesk/FreshDesk.yml
  Packs/FreshDesk/ReleaseNotes/1_0_13.md
  Packs/FreshDesk/pack_metadata.json
  Packs/GoogleVault/.pack-ignore
  Packs/GoogleVault/Integrations/GoogleVault/GoogleVault.py
  Packs/GoogleVault/Integrations/GoogleVault/GoogleVault.yml
  Packs/GoogleVault/ReleaseNotes/1_0_11.md
  Packs/GoogleVault/pack_metadata.json
  Packs/Perch/.pack-ignore
  Packs/Perch/Integrations/Perch/Perch.py
  Packs/Perch/Integrations/Perch/Perch.yml
  Packs/Perch/ReleaseNotes/1_0_17.md
  Packs/Perch/pack_metadata.json
  Packs/VMwareWorkspaceONEUEM/.pack-ignore
  Packs/VMwareWorkspaceONEUEM/Integrations/VMwareWorkspaceONEUEM/VMwareWorkspaceONEUEM.py
  Packs/VMwareWorkspaceONEUEM/Integrations/VMwareWorkspaceONEUEM/VMwareWorkspaceONEUEM.yml
  Packs/VMwareWorkspaceONEUEM/ReleaseNotes/1_0_8.md
  Packs/VMwareWorkspaceONEUEM/pack_metadata.json
Labels: ForceMerge

#28067 CIAC-4682 | Test Security Label and Assignment
  .devcontainer/devcontainer.json
  .github/workflows/update-demisto-sdk-version.yml
  Packs/HelloWorld/Playbooks/playbook-Handle_Hello_World_Alert.yml
Labels: Contribution, Community Support Level, Security, External PR

#27774 Jira V3 fetch incidents by id error
  Packs/Jira/Integrations/JiraV3/JiraV3.py
  Packs/Jira/Integrations/JiraV3/JiraV3.yml
  Packs/Jira/Integrations/JiraV3/JiraV3_test.py
  Packs/Jira/Integrations/JiraV3/README.md
  Packs/Jira/Integrations/JiraV3/command_examples
  Packs/Jira/README.md
  Packs/Jira/ReleaseNotes/3_0_6.md
  Packs/Jira/pack_metadata.json
Labels: docs-approved

#27544 Git lab add trigger pipeline command
  Packs/GitLab/Integrations/GitLabv2/GitLabv2.py
  Packs/GitLab/Integrations/GitLabv2/GitLabv2.yml
  Packs/GitLab/Integrations/GitLabv2/GitLabv2_test.py
  Packs/GitLab/Integrations/GitLabv2/README.md
  Packs/GitLab/Integrations/GitLabv2/test_data/commands_test_data.json
  Packs/GitLab/ReleaseNotes/2_2_11.md
  Packs/GitLab/pack_metadata.json
  Tests/conf.json
Labels: docs-approved

#27456 changed that run_tests won't fail on test_playbooks in nightly
  .gitlab/ci/.gitlab-ci.yml
  .gitlab/ci/on-push.yml
  Tests/Marketplace/install_packs.sh
  Tests/Marketplace/print_testplaybook_summary.py
  Tests/scripts/run_tests.sh
Labels: docs-approved, ForceMerge

#27785 Build with secrets from gitlab
  .gitlab/ci/bucket-upload.yml
  .gitlab/ci/global.yml
  .gitlab/ci/on-push.yml
  Tests/scripts/add_secrets_file_to_build.py
  Tests/scripts/download_conf_repos.sh
  Tests/scripts/utils/GoogleSecretManagerModule.py
Labels: docs-approved

#28035 [Splunk] Code improvement
  Packs/SplunkPy/Integrations/SplunkPy/SplunkPy.py
  Packs/SplunkPy/Integrations/SplunkPy/SplunkPy_test.py
  Packs/SplunkPy/ReleaseNotes/3_0_23.md
  Packs/SplunkPy/pack_metadata.json
Labels: docs-approved

#27530 Delete offset from CrowdStrike fetch
  Packs/CrowdStrikeFalcon/Integrations/CrowdStrikeFalcon/CrowdStrikeFalcon.py
  Packs/CrowdStrikeFalcon/Integrations/CrowdStrikeFalcon/CrowdStrikeFalcon_test.py
  Packs/CrowdStrikeFalcon/ReleaseNotes/1_11_0.md
  Packs/CrowdStrikeFalcon/pack_metadata.json
Labels: docs-approved

#28097 TEST | CIAC-4682 | Add internal, security labels and assignment
  .devcontainer/devcontainer.json
  Packs/HelloWorld/Playbooks/playbook-HelloWorld_Scan.yml
Labels: Contribution, Community Support Level, External PR, Security Review

#27410 ADD User to MISP
  Packs/MISP/Integrations/MISPV3/MISPV3.py
  Packs/MISP/Integrations/MISPV3/MISPV3.yml
  Packs/MISP/Integrations/MISPV3/MISPV3_test.py
  Packs/MISP/Integrations/MISPV3/README.md
  Packs/MISP/Integrations/MISPV3/command_examples
  Packs/MISP/ReleaseNotes/2_1_28.md
  Packs/MISP/TestPlaybooks/MISP_V3_Test.yml
  Packs/MISP/pack_metadata.json
Labels: Contribution, docs-approved, ready-for-instance-test, Contribution Form Filled, Community, pending-contributor, Xsoar Support Level

#28104 TEST | CIAC-4682
  Packs/HelloWorld/Playbooks/playbook-Handle_Hello_World_Alert.yml
Labels: Contribution, Community Support Level, External PR, Security Review

#28078 [Traceable] Bug fix when no events arrive
  Packs/Traceable/Integrations/Traceable/Traceable.py
  Packs/Traceable/Integrations/Traceable/Traceable_test.py
  Packs/Traceable/ReleaseNotes/1_0_1.md
  Packs/Traceable/pack_metadata.json
Labels: Contribution, Partner, ready-for-instance-test, Contribution Form Filled, Partner Support Level

#28081 Test revert
  .gitlab/ci/bucket-upload.yml
  .gitlab/ci/global.yml
  .gitlab/ci/on-push.yml
  Tests/scripts/add_secrets_file_to_build.py
  Tests/scripts/download_conf_repos.sh
  Tests/scripts/utils/GoogleSecretManagerModule.py
Labels: docs-approved

#27663 populated DEMISTO_SDK_NIGHTLY var to trigger test upload flow
  .gitlab/ci/.gitlab-ci.yml
  .gitlab/ci/global.yml
  Utils/trigger_test_upload_flow.sh
Labels: docs-approved, ForceMerge

#28037 Wiz v1.2.7
  Packs/Wiz/Integrations/Wiz/Wiz.py
  Packs/Wiz/Integrations/Wiz/Wiz.yml
  Packs/Wiz/Integrations/Wiz/Wiz_description.md
  Packs/Wiz/Integrations/Wiz/Wiz_test.py
  Packs/Wiz/ReleaseNotes/1_2_7.md
  Packs/Wiz/pack_metadata.json
Labels: Contribution, Partner, Contribution Form Filled, Partner Support Level

#27439 Fix link to EXO v3 module
  Packs/MicrosoftExchangeOnline/Integrations/EwsExtensionEXOPowershellV3/README.md
Labels: docs-approved

#27937 Align credentials stores fix
  Packs/AzureKeyVault/.pack-ignore
  Packs/AzureKeyVault/Integrations/AzureKeyVault/AzureKeyVault.py
  Packs/AzureKeyVault/Integrations/AzureKeyVault/AzureKeyVault.yml
  Packs/AzureKeyVault/ReleaseNotes/1_1_22.md
  Packs/AzureKeyVault/pack_metadata.json
  Packs/TrendMicroCAS/.pack-ignore
  Packs/TrendMicroCAS/Integrations/TrendMicroCAS/TrendMicroCAS.py
  Packs/TrendMicroCAS/Integrations/TrendMicroCAS/TrendMicroCAS.yml
  Packs/TrendMicroCAS/ReleaseNotes/1_1_5.md
  Packs/TrendMicroCAS/pack_metadata.json
  Packs/TrendMicroDDA/.pack-ignore
  Packs/TrendMicroDDA/Integrations/TrendMicroDDA/TrendMicroDDA.py
  Packs/TrendMicroDDA/Integrations/TrendMicroDDA/TrendMicroDDA.yml
  Packs/TrendMicroDDA/ReleaseNotes/1_0_15.md
  Packs/TrendMicroDDA/pack_metadata.json
  Packs/VersaDirector/.pack-ignore
  Packs/VersaDirector/Integrations/VersaDirector/VersaDirector.py
  Packs/VersaDirector/Integrations/VersaDirector/VersaDirector.yml
  Packs/VersaDirector/ReleaseNotes/1_0_4.md
  Packs/VersaDirector/pack_metadata.json
Labels: docs-approved

#28025 Fix-For-ADFS-and-Windows-Event-Logs
  Packs/MicrosoftADFS/ModelingRules/MicrosoftADFS_1_3/MicrosoftADFS_1_3.xif
  Packs/MicrosoftADFS/ModelingRules/MicrosoftADFS_1_3/MicrosoftADFS_1_3_schema.json
  Packs/MicrosoftADFS/ParsingRules/MicrosoftADFSParsingRules/MicrosoftADFSParsingRules.xif
  Packs/MicrosoftADFS/ParsingRules/MicrosoftADFSParsingRules/MicrosoftADFSParsingRules.yml
  Packs/MicrosoftADFS/README.md
  Packs/MicrosoftADFS/ReleaseNotes/1_0_14.md
  Packs/MicrosoftADFS/doc_imgs/ADFSWEC.png
  Packs/MicrosoftADFS/pack_metadata.json
  Packs/MicrosoftCore/pack_metadata.json
  Packs/MicrosoftWindowsEvents/ParsingRules/MicrosoftWindowsEvents/MicrosoftWindowsEvents.xif
  Packs/MicrosoftWindowsEvents/ParsingRules/MicrosoftWindowsEvents/MicrosoftWindowsEvents.yml
  Packs/MicrosoftWindowsEvents/README.md
  Packs/MicrosoftWindowsEvents/ReleaseNotes/1_0_6.md
  Packs/MicrosoftWindowsEvents/pack_metadata.json
Labels: docs-approved

#28066 GetListRow: added support to use \t as separator
  Packs/CommonScripts/ReleaseNotes/1_12_1.md
  Packs/CommonScripts/Scripts/GetlistRow/GetListRow.py
  Packs/CommonScripts/Scripts/GetlistRow/GetListRow.yml
  Packs/CommonScripts/Scripts/GetlistRow/GetListRow_test.py
  Packs/CommonScripts/Scripts/GetlistRow/README.md
  Packs/CommonScripts/pack_metadata.json
Labels: docs-approved

#26989 Qualys Event Collector
  Packs/qualys/.secrets-ignore
  Packs/qualys/Integrations/QualysEventCollector/QualysEventCollector.py
  Packs/qualys/Integrations/QualysEventCollector/QualysEventCollector.yml
  Packs/qualys/Integrations/QualysEventCollector/QualysEventCollector_description.md
  Packs/qualys/Integrations/QualysEventCollector/QualysEventCollector_image.png
  Packs/qualys/Integrations/QualysEventCollector/QualysEventCollector_test.py
  Packs/qualys/Integrations/QualysEventCollector/README.md
  Packs/qualys/Integrations/QualysEventCollector/command_examples
  Packs/qualys/Integrations/QualysEventCollector/test_data/activity_logs.csv
  Packs/qualys/Integrations/QualysEventCollector/test_data/host_list_detections_raw.xml
  Packs/qualys/ModelingRules/QualysModelingRules/QualysModelingRules.xif
  Packs/qualys/ModelingRules/QualysModelingRules/QualysModelingRules.yml
  Packs/qualys/ModelingRules/QualysModelingRules/QualysModelingRules_schema.json
  Packs/qualys/README.md
  Packs/qualys/ReleaseNotes/2_0_0.md
  Packs/qualys/pack_metadata.json
Labels: docs-approved

#28054 Tableau Parsing Update
  Packs/Tableau/ParsingRules/Tableau/Tableau.xif
  Packs/Tableau/README.md
  Packs/Tableau/ReleaseNotes/1_0_11.md
  Packs/Tableau/pack_metadata.json
Labels: docs-approved

#28069 Parsingrules filters guy
  Packs/Auditd/ParsingRules/Auditd/Auditd.xif
  Packs/Auditd/ReleaseNotes/1_0_2.md
  Packs/Auditd/pack_metadata.json
  Packs/BarracudaWAF/ParsingRules/BarracudaWAFParsingRules/BarracudaWAFParsingRules.xif
  Packs/BarracudaWAF/ReleaseNotes/1_0_1.md
  Packs/BarracudaWAF/pack_metadata.json
  Packs/CiscoCatalyst/ParsingRules/CiscoCatalyst/CiscoCatalyst.xif
  Packs/CiscoCatalyst/ReleaseNotes/1_0_3.md
  Packs/CiscoCatalyst/pack_metadata.json
Labels: docs-approved

#27861 CheckPointHEC Pack first version
  Packs/CheckPointHEC/.pack-ignore
  Packs/CheckPointHEC/.secrets-ignore
  Packs/CheckPointHEC/Author_image.png
  Packs/CheckPointHEC/CONTRIBUTORS.json
  Packs/CheckPointHEC/IncidentFields/incidentfield-CheckPointHEC_Customer.json
  Packs/CheckPointHEC/IncidentFields/incidentfield-CheckPointHEC_Entity.json
  Packs/CheckPointHEC/IncidentFields/incidentfield-CheckPointHEC_Saas.json
  Packs/CheckPointHEC/IncidentFields/incidentfield-CheckPointHEC_Type.json
  Packs/CheckPointHEC/IncidentTypes/incidenttype-CheckPointHEC_Security_Event.json
  Packs/CheckPointHEC/Integrations/CheckPointHEC/CheckPointHEC.py
  Packs/CheckPointHEC/Integrations/CheckPointHEC/CheckPointHEC.yml
  Packs/CheckPointHEC/Integrations/CheckPointHEC/CheckPointHEC_description.md
  Packs/CheckPointHEC/Integrations/CheckPointHEC/CheckPointHEC_image.png
  Packs/CheckPointHEC/Integrations/CheckPointHEC/CheckPointHEC_test.py
  Packs/CheckPointHEC/Integrations/CheckPointHEC/README.md
  Packs/CheckPointHEC/Integrations/CheckPointHEC/command_examples
  Packs/CheckPointHEC/Integrations/CheckPointHEC/test_data/checkpointhec-get_entity.json
  Packs/CheckPointHEC/Integrations/CheckPointHEC/test_data/checkpointhec-get_scopes.json
  Packs/CheckPointHEC/Integrations/CheckPointHEC/test_data/checkpointhec-query_events.json
  Packs/CheckPointHEC/Layouts/layoutscontainer-CheckPointHEC_Security_Event_Layout.json
  Packs/CheckPointHEC/Playbooks/CheckPointHEC_Get_email_for_incident.yml
  Packs/CheckPointHEC/Playbooks/CheckPointHEC_Get_email_for_incident_README.md
  Packs/CheckPointHEC/README.md
  Packs/CheckPointHEC/doc_files/CheckPointHEC_Get_email_for_incident.png
  Packs/CheckPointHEC/pack_metadata.json
Labels: Contribution, Partner, ready-for-instance-test, Contribution Form Filled, pending-contributor

#28112 Proofpoint parsing issue
  Packs/ProofpointTAP/ParsingRules/ProofpointTAP/ProofpointTAP.xif
  Packs/ProofpointTAP/ReleaseNotes/1_2_6.md
  Packs/ProofpointTAP/pack_metadata.json
Labels: docs-approved

#28009 documented size limitation on set script
  Packs/CommonScripts/Scripts/Set/README.md
Labels: docs-approved

#28057 Rplaced all realative with absulote paths
  Packs/Lumu/Integrations/Lumu/Lumu_description.md
  Packs/Lumu/ReleaseNotes/1_0_7.md
  Packs/Lumu/pack_metadata.json
  Packs/Microsoft365Defender/Integrations/O365DefenderSafeLinks/O365DefenderSafeLinks_description.md
  Packs/Microsoft365Defender/ReleaseNotes/4_5_8.md
  Packs/Microsoft365Defender/pack_metadata.json
  Packs/SplunkPy/Integrations/SplunkPy/SplunkPy_description.md
  Packs/SplunkPy/ReleaseNotes/3_0_24.md
  Packs/SplunkPy/pack_metadata.json
Labels: docs-approved

#27313 Cs falcon enhancement
  Packs/CommonTypes/IncidentFields/incidentfield-Account_ID.json
  Packs/CommonTypes/IncidentFields/incidentfield-Account_Name.json
  Packs/CommonTypes/IncidentFields/incidentfield-Display_Name.json
  Packs/CommonTypes/IncidentFields/incidentfield-End_Time.json
  Packs/CommonTypes/IncidentFields/incidentfield-Last_Update_Time.json
  Packs/CommonTypes/IncidentFields/incidentfield-Src_NT_Domain.json
  Packs/CommonTypes/IncidentFields/incidentfield-Start_Time.json
  Packs/CommonTypes/IncidentFields/incidentfield-Vendor_Product.json
  Packs/CommonTypes/ReleaseNotes/3_3_81.md
  Packs/CommonTypes/pack_metadata.json
  Packs/CrowdStrikeFalcon/.pack-ignore
  Packs/CrowdStrikeFalcon/Classifiers/classifier-CrowdStrike_Falcon_Incident_Classifier.json
  Packs/CrowdStrikeFalcon/Classifiers/classifier-CrowdStrike_Falcon_Mapper.json
  Packs/CrowdStrikeFalcon/Classifiers/classifier-CrowdStrike_Falcon_Mapper_6.5.json
  Packs/CrowdStrikeFalcon/Classifiers/classifier-mapper-outgoing-CrowdStrike_Falcon.json
  Packs/CrowdStrikeFalcon/IncidentFields/incidentfield-Behaviour_Objective.json
  Packs/CrowdStrikeFalcon/IncidentFields/incidentfield-Behaviour_Pattern_Disposition_Details.json
  Packs/CrowdStrikeFalcon/IncidentFields/incidentfield-Behaviour_Scenario.json
  Packs/CrowdStrikeFalcon/IncidentFields/incidentfield-Behaviour_Tactic.json
  Packs/CrowdStrikeFalcon/IncidentFields/incidentfield-Crawled_Timestamp.json
  Packs/CrowdStrikeFalcon/IncidentFields/incidentfield-Detection_Type.json
  Packs/CrowdStrikeFalcon/IncidentFields/incidentfield-Pattern_ID.json
  Packs/CrowdStrikeFalcon/IncidentTypes/incidenttype-CrowdStrikeFalconIDPDetection.json
  Packs/CrowdStrikeFalcon/Integrations/CrowdStrikeFalcon/CrowdStrikeFalcon.py
  Packs/CrowdStrikeFalcon/Integrations/CrowdStrikeFalcon/CrowdStrikeFalcon.yml
  Packs/CrowdStrikeFalcon/Integrations/CrowdStrikeFalcon/CrowdStrikeFalcon_description.md
  Packs/CrowdStrikeFalcon/Integrations/CrowdStrikeFalcon/CrowdStrikeFalcon_test.py
  Packs/CrowdStrikeFalcon/Integrations/CrowdStrikeFalcon/README.md
  Packs/CrowdStrikeFalcon/Integrations/CrowdStrikeFalcon/test_data/input_data.py
  Packs/CrowdStrikeFalcon/Integrations/CrowdStrikeFalcon/test_data/test_list_identity_entities_command.json
  Packs/CrowdStrikeFalcon/ReleaseNotes/1_11_1.md
  Packs/CrowdStrikeFalcon/TestPlaybooks/playbook-CrowdStrikeFalcon-Test.yml
  Packs/CrowdStrikeFalcon/pack_metadata.json
Labels: docs-approved, ForceMerge

#28021 Cdl query issues
  Packs/CortexDataLake/Integrations/CortexDataLake/CortexDataLake.py
  Packs/CortexDataLake/Integrations/CortexDataLake/CortexDataLake.yml
  Packs/CortexDataLake/ReleaseNotes/1_4_7.md
  Packs/CortexDataLake/pack_metadata.json
Labels: docs-approved

#28058 Cryptojacking files to the Cloud Incident Response pack
  Packs/CloudIncidentResponse/.pack-ignore
  Packs/CloudIncidentResponse/Layouts/layoutscontainer-Cortex_XDR_-_XCLOUD_Cryptomining.json
  Packs/CloudIncidentResponse/Playbooks/playbook-Cortex_XDR_-_Cloud_Cryptomining.yml
  Packs/CloudIncidentResponse/Playbooks/playbook-Cortex_XDR_-_Cloud_Cryptomining_-_Set_Verdict.yml
  Packs/CloudIncidentResponse/Playbooks/playbook-Cortex_XDR_-_Cloud_Cryptomining_-_Set_Verdict_README.md
  Packs/CloudIncidentResponse/Playbooks/playbook-Cortex_XDR_-_Cloud_Cryptomining_README.md
  Packs/CloudIncidentResponse/Playbooks/playbook-Cortex_XDR_-_Cloud_Enrichment.yml
  Packs/CloudIncidentResponse/Playbooks/playbook-Cortex_XDR_-_Cloud_Enrichment_README.md
  Packs/CloudIncidentResponse/Playbooks/playbook-XCloud_Alert_Enrichment.yml
  Packs/CloudIncidentResponse/Playbooks/playbook-XCloud_Alert_Enrichment_README.md
  Packs/CloudIncidentResponse/Playbooks/playbook-XCloud_Cryptomining.yml
  Packs/CloudIncidentResponse/Playbooks/playbook-XCloud_Cryptomining_-_Set_Verdict.yml
  Packs/CloudIncidentResponse/Playbooks/playbook-XCloud_Cryptomining_-_Set_Verdict_README.md
  Packs/CloudIncidentResponse/Playbooks/playbook-XCloud_Cryptomining_README.md
  Packs/CloudIncidentResponse/ReleaseNotes/1_0_4.md
  Packs/CloudIncidentResponse/Triggers/Trigger_-_XCloud_Cryptojacking.json
  Packs/CloudIncidentResponse/doc_files/Cortex_XDR_-_Cloud_Cryptomining.png
  Packs/CloudIncidentResponse/doc_files/Cortex_XDR_-_Cloud_Enrichment.png
  Packs/CloudIncidentResponse/doc_files/Cortex_XDR_-_Cryptomining_-_Set_Verdict.png
  Packs/CloudIncidentResponse/doc_files/XCloud_Alert_Enrichment.png
  Packs/CloudIncidentResponse/doc_files/XCloud_Cryptomining.png
  Packs/CloudIncidentResponse/doc_files/XCloud_Cryptomining_-_Set_Verdict.png
  Packs/CloudIncidentResponse/pack_metadata.json
  Packs/Core/ReleaseNotes/2_0_0.json
  Packs/Core/ReleaseNotes/2_0_0.md
  Packs/Core/pack_metadata.json
  Packs/CortexXDR/.pack-ignore
  Packs/CortexXDR/Playbooks/Cortex_XDR_Alerts_Handling.yml
  Packs/CortexXDR/Playbooks/Cortex_XDR_Alerts_Handling_README.md
  Packs/CortexXDR/ReleaseNotes/5_0_0.json
  Packs/CortexXDR/ReleaseNotes/5_0_0.md
  Packs/CortexXDR/doc_files/Cortex_XDR_Alerts_Handling.png
  Packs/CortexXDR/pack_metadata.json
Labels: docs-approved

#28120 slack collector add retries
  Packs/Slack/Integrations/SlackEventCollector/SlackEventCollector.py
  Packs/Slack/ReleaseNotes/3_1_42.md
  Packs/Slack/pack_metadata.json
Labels: docs-approved

#27956 Portnox modeling rules
  Packs/Portnox/.pack-ignore
  Packs/Portnox/.secrets-ignore
  Packs/Portnox/ModelingRules/Portnox_1_3/Portnox_1_3.xif
  Packs/Portnox/ModelingRules/Portnox_1_3/Portnox_1_3.yml
  Packs/Portnox/ModelingRules/Portnox_1_3/Portnox_1_3_schema.json
  Packs/Portnox/README.md
  Packs/Portnox/doc_imgs/all_events.png
  Packs/Portnox/doc_imgs/all_networks.png
  Packs/Portnox/doc_imgs/event_conf.png
  Packs/Portnox/doc_imgs/send_alerts_by.png
  Packs/Portnox/doc_imgs/syslog_ip.png
  Packs/Portnox/pack_metadata.json
Labels: docs-approved

#27943 [PAN-OS] - pan-os-create-tag fails with error "set failed, may need to override template object first"
  Packs/PAN-OS/Integrations/Panorama/Panorama.py
  Packs/PAN-OS/Integrations/Panorama/Panorama.yml
  Packs/PAN-OS/Integrations/Panorama/Panorama_test.py
  Packs/PAN-OS/ReleaseNotes/1_17_14.md
  Packs/PAN-OS/pack_metadata.json
Labels: docs-approved

#28076 Slack Modeling/Parsing Update
  Packs/Slack/ModelingRules/SlackModelingRules_1_3/SlackModelingRules_1_3.xif
  Packs/Slack/ParsingRules/SlackParsingRules/SlackParsingRules.xif
  Packs/Slack/ReleaseNotes/3_1_43.md
  Packs/Slack/pack_metadata.json
Labels: docs-approved

#28122 Aws security hub master date issue
  Packs/AWS-SecurityHub/Integrations/AWS_SecurityHub/AWS_SecurityHub.py
  Packs/AWS-SecurityHub/Integrations/AWS_SecurityHub/AWS_SecurityHub.yml
  Packs/AWS-SecurityHub/ReleaseNotes/1_3_6.md
  Packs/AWS-SecurityHub/pack_metadata.json
Labels: docs-approved

#28083 Missing logo crtx 49756
  Packs/Gmail/Integrations/Gmail/Gmail.py
  Packs/Gmail/Integrations/Gmail/Gmail.yml
  Packs/Gmail/ReleaseNotes/1_3_12.md
  Packs/Gmail/pack_metadata.json
Labels: docs-approved

#28142 remove duplicate conf clone
  .gitlab/ci/bucket-upload.yml
  .gitlab/ci/global.yml
Labels: docs-approved

#28173 Fix core readme pack broken link
  Packs/Core/README.md
Labels: docs-approved

#28131 [Cortex XDR] Fixed status parsing issue
  Packs/ApiModules/ReleaseNotes/2_2_18.md
  Packs/ApiModules/Scripts/CoreIRApiModule/CoreIRApiModule.py
  Packs/ApiModules/pack_metadata.json
  Packs/Core/Integrations/CortexCoreIR/CortexCoreIR.yml
  Packs/Core/Integrations/CortexCoreIR/README.md
  Packs/Core/ReleaseNotes/2_0_1.md
  Packs/Core/pack_metadata.json
  Packs/CortexXDR/Integrations/CortexXDRIR/CortexXDRIR.yml
  Packs/CortexXDR/Integrations/CortexXDRIR/README.md
  Packs/CortexXDR/ReleaseNotes/5_0_1.md
  Packs/CortexXDR/pack_metadata.json
Labels: Contribution, ready-for-instance-test, Contribution Form Filled, Community, Xsoar Support Level

#28174 Updated the sql query in the readme for oracle
  Packs/Oracle/README.md
Labels: docs-approved

#28144 [EDL] warn of updating with empty query
  Packs/EDL/Integrations/EDL/EDL.py
  Packs/EDL/Integrations/EDL/EDL.yml
  Packs/EDL/ReleaseNotes/3_2_3.md
  Packs/EDL/pack_metadata.json
Labels: docs-approved

#28070 Generic polling logs
  Packs/CommonScripts/ReleaseNotes/1_12_2.md
  Packs/CommonScripts/Scripts/ScheduleGenericPolling/ScheduleGenericPolling.py
  Packs/CommonScripts/pack_metadata.json
Labels: docs-approved

#20217 Stringsifter automation
  Packs/StringSifter/.pack-ignore
  Packs/StringSifter/.secrets-ignore
  Packs/StringSifter/README.md
  Packs/StringSifter/Scripts/StringSifter/README.md
  Packs/StringSifter/Scripts/StringSifter/StringSifter.py
  Packs/StringSifter/Scripts/StringSifter/StringSifter.yml
  Packs/StringSifter/Scripts/StringSifter/StringSifter_test.py
  Packs/StringSifter/Scripts/StringSifter/test_data/redable_output_string_text.md
  Packs/StringSifter/Scripts/StringSifter/test_data/score_results.txt
  Packs/StringSifter/Scripts/StringSifter/test_data/string_text_outputs.json
  Packs/StringSifter/Scripts/StringSifter/test_data/stringsifter_result.md
  Packs/StringSifter/Scripts/StringSifter/test_data/stringsifter_results_with_filters.md
  Packs/StringSifter/Scripts/StringSifter/test_data/temp_out.txt
  Packs/StringSifter/Scripts/StringSifter/test_data/test_words.txt
  Packs/StringSifter/Scripts/StringSifter/test_data/words_rating.json
  Packs/StringSifter/Scripts/StringSifter/test_data/words_rating_with_filter.json
  Packs/StringSifter/pack_metadata.json
Labels: docs-approved

#28068 Parsing rules fix filter 2
  Packs/CiscoISR/ParsingRules/CiscoISR/CiscoISR.xif
  Packs/CiscoISR/ReleaseNotes/1_0_1.md
  Packs/CiscoISR/pack_metadata.json
  Packs/Squid/ParsingRules/Squid/Squid.xif
  Packs/Squid/ReleaseNotes/1_0_2.md
  Packs/Squid/pack_metadata.json
  Packs/SymantecEndpointProtection/ParsingRules/SymantecEndpointProtection/SymantecEndpointProtection.xif
  Packs/SymantecEndpointProtection/ReleaseNotes/1_1_6.md
  Packs/SymantecEndpointProtection/pack_metadata.json
Labels: docs-approved

#28118 Parsing rules fix filter 3
  Packs/Infoblox/ParsingRules/InfobloxParsingRules/InfobloxParsingRules.xif
  Packs/Infoblox/ReleaseNotes/1_0_17.md
  Packs/Infoblox/pack_metadata.json
  Packs/TaniumThreatResponse/ParsingRules/TaniumThreatResponse/TaniumThreatResponse.xif
  Packs/TaniumThreatResponse/ReleaseNotes/2_2_4.md
  Packs/TaniumThreatResponse/pack_metadata.json
  Packs/cisco-ise/ParsingRules/cisco-ise/cisco-ise.xif
  Packs/cisco-ise/ParsingRules/cisco-ise/cisco-ise.yml
  Packs/cisco-ise/ReleaseNotes/1_0_12.md
  Packs/cisco-ise/pack_metadata.json
Labels: docs-approved

#28149 Properly sourcing `mscore` for `fetch_reputation` function
  Packs/MandiantAdvantageThreatIntelligence/Integrations/MandiantAdvantageThreatIntelligence/MandiantAdvantageThreatIntelligence.py
  Packs/MandiantAdvantageThreatIntelligence/ReleaseNotes/1_0_5.md
  Packs/MandiantAdvantageThreatIntelligence/pack_metadata.json
Labels: Contribution, Partner, Contribution Form Filled, Partner Support Level

#28185 [Core REST API] fixed test-module
  Packs/DemistoRESTAPI/Integrations/CoreRESTAPI/CoreRESTAPI.js
  Packs/DemistoRESTAPI/ReleaseNotes/1_3_31.md
  Packs/DemistoRESTAPI/pack_metadata.json
Labels: docs-approved

#28189 Shorter pull_request_template.md
  .github/pull_request_template.md
Labels: docs-approved

#26650 Micro Trend One Vision Event Collector
  Packs/TrendMicroVisionOne/Integrations/TrendMicroVisionOneEventCollector/README.md
  Packs/TrendMicroVisionOne/Integrations/TrendMicroVisionOneEventCollector/TrendMicroVisionOneEventCollector.py
  Packs/TrendMicroVisionOne/Integrations/TrendMicroVisionOneEventCollector/TrendMicroVisionOneEventCollector.yml
  Packs/TrendMicroVisionOne/Integrations/TrendMicroVisionOneEventCollector/TrendMicroVisionOneEventCollector_description.md
  Packs/TrendMicroVisionOne/Integrations/TrendMicroVisionOneEventCollector/TrendMicroVisionOneEventCollector_image.png
  Packs/TrendMicroVisionOne/Integrations/TrendMicroVisionOneEventCollector/TrendMicroVisionOneEventCollector_test.py
  Packs/TrendMicroVisionOne/ModelingRules/TrendMicroVisionOneModelingRules/TrendMicroVisionOneModelingRules.xif
  Packs/TrendMicroVisionOne/ModelingRules/TrendMicroVisionOneModelingRules/TrendMicroVisionOneModelingRules.yml
  Packs/TrendMicroVisionOne/ModelingRules/TrendMicroVisionOneModelingRules/TrendMicroVisionOneModelingRules_schema.json
  Packs/TrendMicroVisionOne/ReleaseNotes/3_0_0.md
  Packs/TrendMicroVisionOne/pack_metadata.json
Labels: docs-approved

#28084 Gcp expandr 5021
  Packs/GoogleCloudCompute/Integrations/GoogleCloudCompute/GoogleCloudCompute.py
  Packs/GoogleCloudCompute/Integrations/GoogleCloudCompute/GoogleCloudCompute.yml
  Packs/GoogleCloudCompute/ReleaseNotes/1_1_4.md
  Packs/GoogleCloudCompute/pack_metadata.json
Labels: Contribution, ready-for-instance-test, Contribution Form Filled, Community, Xsoar Support Level

#28080 Convert github workflow inputs argument from str to dict
  Packs/GitHub/Integrations/GitHub/GitHub.py
  Packs/GitHub/Integrations/GitHub/GitHub.yml
  Packs/GitHub/ReleaseNotes/2_0_19.md
  Packs/GitHub/pack_metadata.json
Labels: docs-approved

#28023 Parsing Rules Update1
  Packs/AWS-GuardDuty/ModelingRules/AWSGuardDutyModelingRules_1_3/AWSGuardDutyModelingRules_1_3.xif
  Packs/AWS-GuardDuty/ParsingRules/AWS-GuardDuty/AWS-GuardDuty.xif
  Packs/AWS-GuardDuty/ParsingRules/AWS-GuardDuty/AWS-GuardDuty.yml
  Packs/AWS-GuardDuty/ReleaseNotes/1_3_26.md
  Packs/AWS-GuardDuty/pack_metadata.json
  Packs/AristaSwitch/ParsingRules/AristaSwitch/AristaSwitch.xif
  Packs/AristaSwitch/ReleaseNotes/1_0_1.md
  Packs/AristaSwitch/pack_metadata.json
  Packs/BarracudaEmailProtection/ParsingRules/BarracudaEmailProtection/BarracudaEmailProtectionParsingRules/BarracudaEmailProtectionParsingRules.xif
  Packs/BarracudaEmailProtection/ReleaseNotes/1_0_2.md
  Packs/BarracudaEmailProtection/pack_metadata.json
Labels: docs-approved

#28180 Kill long running container when the connection is lost
  Packs/ApiModules/Scripts/NGINXApiModule/NGINXApiModule.py
  Packs/ApiModules/Scripts/NGINXApiModule/NGINXApiModule_test.py
  Packs/EDL/ReleaseNotes/3_2_4.md
  Packs/EDL/pack_metadata.json
  Packs/ExportIndicators/ReleaseNotes/1_0_19.md
  Packs/ExportIndicators/pack_metadata.json
  Packs/TAXIIServer/ReleaseNotes/2_0_41.md
  Packs/TAXIIServer/pack_metadata.json
Labels: docs-approved

#28109 CIAC-4682 | Add Internal, External, Security Labels
  Utils/github_workflow_scripts/create_internal_pr.py
  Utils/github_workflow_scripts/github_workflow_scripts_tests/handle_external_pr_test.py
  Utils/github_workflow_scripts/handle_external_pr.py
Labels: docs-approved

#28045 Okta Auth0 event collector
  Packs/OktaAuth0/.pack-ignore
  Packs/OktaAuth0/.secrets-ignore
  Packs/OktaAuth0/Integrations/OktaAuth0EventCollector/OktaAuth0EventCollector.py
  Packs/OktaAuth0/Integrations/OktaAuth0EventCollector/OktaAuth0EventCollector.yml
  Packs/OktaAuth0/Integrations/OktaAuth0EventCollector/OktaAuth0EventCollector_description.md
  Packs/OktaAuth0/Integrations/OktaAuth0EventCollector/OktaAuth0EventCollector_image.png
  Packs/OktaAuth0/Integrations/OktaAuth0EventCollector/OktaAuth0EventCollector_test.py
  Packs/OktaAuth0/Integrations/OktaAuth0EventCollector/README.md
  Packs/OktaAuth0/Integrations/OktaAuth0EventCollector/test_data/mock_events.json
  Packs/OktaAuth0/ModelingRules/OktaAuth0ModelingRules/OktaAuth0ModelingRules.xif
  Packs/OktaAuth0/ModelingRules/OktaAuth0ModelingRules/OktaAuth0ModelingRules.yml
  Packs/OktaAuth0/ModelingRules/OktaAuth0ModelingRules/OktaAuth0ModelingRules_schema.json
  Packs/OktaAuth0/README.md
  Packs/OktaAuth0/pack_metadata.json
Labels: docs-approved

#27922 enhance pre-commit
  .pre-commit-config_template.yaml
  poetry.lock
Labels: docs-approved

#27990 MispFeed - fix default tags value
  Packs/FeedMISP/Integrations/FeedMISP/FeedMISP.py
  Packs/FeedMISP/ReleaseNotes/1_0_25.md
  Packs/FeedMISP/pack_metadata.json
Labels: docs-approved

#28201 CVE-2023-36884 - Microsoft Office and Windows HTML RCE
  Packs/CVE_2023_36884_-_Microsoft_Office_and_Windows_RCE/.pack-ignore
  Packs/CVE_2023_36884_-_Microsoft_Office_and_Windows_RCE/.secrets-ignore
  Packs/CVE_2023_36884_-_Microsoft_Office_and_Windows_RCE/Playbooks/playbook-CVE-2023-36884_-_Microsoft_Office_and_Windows_HTML_RCE.yml
  Packs/CVE_2023_36884_-_Microsoft_Office_and_Windows_RCE/Playbooks/playbook-CVE-2023-36884_-_Microsoft_Office_and_Windows_HTML_RCE_README.md
  Packs/CVE_2023_36884_-_Microsoft_Office_and_Windows_RCE/README.md
  Packs/CVE_2023_36884_-_Microsoft_Office_and_Windows_RCE/doc_files/CVE-2023-36884_-_Microsoft_Office_and_Windows_HTML_RCE.png
  Packs/CVE_2023_36884_-_Microsoft_Office_and_Windows_RCE/pack_metadata.json
  Packs/MajorBreachesInvestigationandResponse/.pack-ignore
  Packs/MajorBreachesInvestigationandResponse/ReleaseNotes/1_6_35.md
  Packs/MajorBreachesInvestigationandResponse/pack_metadata.json
Labels: docs-approved

#27898 Added a feature to support SSL client certificate authentication for Mail listener
  Packs/MailListener/Integrations/MailListenerV2/MailListenerV2.py
  Packs/MailListener/Integrations/MailListenerV2/MailListenerV2.yml
  Packs/MailListener/Integrations/MailListenerV2/MailListenerV2_description.md
  Packs/MailListener/Integrations/MailListenerV2/MailListenerV2_test.py
  Packs/MailListener/Integrations/MailListenerV2/README.md
  Packs/MailListener/ReleaseNotes/1_0_41.md
  Packs/MailListener/pack_metadata.json
Labels: Contribution, ready-for-instance-test, Contribution Form Filled, Community, pending-contributor, Xsoar Support Level

#28181 removed pack version from scripts
  Packs/DragosWorldview/Integrations/DragosWorldview/DragosWorldview.py
  Packs/DragosWorldview/ReleaseNotes/1_1_2.md
  Packs/DragosWorldview/pack_metadata.json
  Packs/EDL/Integrations/EDL/EDL.py
  Packs/EDL/ReleaseNotes/3_2_5.md
  Packs/EDL/pack_metadata.json
  Packs/SentinelOne/Integrations/SentinelOne-V2/SentinelOne-V2.py
  Packs/SentinelOne/ReleaseNotes/3_2_4.md
  Packs/SentinelOne/pack_metadata.json
Labels: docs-approved

#28229 Upgrade the docker image for parse emails
  Packs/CommonScripts/ReleaseNotes/1_12_3.md
  Packs/CommonScripts/Scripts/ParseEmailFilesV2/ParseEmailFilesV2.yml
  Packs/CommonScripts/pack_metadata.json
Labels: docs-approved

#28134 [Xsup 26102] ConvertXmlFileToJson script to py3
  Packs/CommonScripts/ReleaseNotes/1_12_4.md
  Packs/CommonScripts/Scripts/ConvertXmlFileToJson/ConvertXmlFileToJson.js
  Packs/CommonScripts/Scripts/ConvertXmlFileToJson/ConvertXmlFileToJson.py
  Packs/CommonScripts/Scripts/ConvertXmlFileToJson/ConvertXmlFileToJson.yml
  Packs/CommonScripts/Scripts/ConvertXmlFileToJson/ConvertXmlFileToJson_test.py
  Packs/CommonScripts/Scripts/ConvertXmlFileToJson/test_data/input.xml
  Packs/CommonScripts/pack_metadata.json
Labels: docs-approved, ForceMerge

#28138 Fixing an issue in API metrics dashboard
  Packs/CommonDashboards/Dashboards/dashboard-APIExecutionMetrics.json
  Packs/CommonDashboards/ReleaseNotes/1_3_5.md
  Packs/CommonDashboards/pack_metadata.json
Labels: docs-approved

#28158 [ASM] - Expander - Update Remediation Guidance July 2023
  Packs/CortexAttackSurfaceManagement/.secrets-ignore
  Packs/CortexAttackSurfaceManagement/Lists/list-RemediationGuidance.json
  Packs/CortexAttackSurfaceManagement/ReleaseNotes/1_6_24.md
  Packs/CortexAttackSurfaceManagement/pack_metadata.json
Labels: Contribution, Contribution Form Filled, Community, Xsoar Support Level

#28179 Active Directory Query v2: fix ad-modify-user-ou command
  Packs/Active_Directory_Query/Integrations/Active_Directory_Query/Active_Directory_Query.py
  Packs/Active_Directory_Query/Integrations/Active_Directory_Query/Active_Directory_Query.yml
  Packs/Active_Directory_Query/ReleaseNotes/1_6_18.md
  Packs/Active_Directory_Query/pack_metadata.json
Labels: docs-approved

#28192 Parsing Rules Update Round 1
  Packs/GitHub/ParsingRules/GitHub_ParsingRules/GitHub_ParsingRules.xif
  Packs/GitHub/ReleaseNotes/2_0_20.md
  Packs/GitHub/pack_metadata.json
  Packs/GitLab/ParsingRules/GitLab/GitLab.xif
  Packs/GitLab/ReleaseNotes/2_2_12.md
  Packs/GitLab/pack_metadata.json
  Packs/Jira/ParsingRules/JiraParsingRules/JiraParsingRules.xif
  Packs/Jira/ReleaseNotes/3_0_8.md
  Packs/Jira/pack_metadata.json
Labels: docs-approved

#28147 [Traceable] New input filter and new filter values
  Packs/Traceable/Integrations/Traceable/README.md
  Packs/Traceable/Integrations/Traceable/Traceable.py
  Packs/Traceable/Integrations/Traceable/Traceable.yml
  Packs/Traceable/Integrations/Traceable/Traceable_description.md
  Packs/Traceable/Integrations/Traceable/Traceable_test.py
  Packs/Traceable/README.md
  Packs/Traceable/ReleaseNotes/1_0_2.md
  Packs/Traceable/pack_metadata.json
Labels: Contribution, Partner, pending-demo, Contribution Form Filled, pending-contributor, Partner Support Level

#27987 ASM - Expander - Jira Notification
  Packs/CortexAttackSurfaceManagement/.pack-ignore
  Packs/CortexAttackSurfaceManagement/Playbooks/Cortex_ASM_-_ASM_Alert.yml
  Packs/CortexAttackSurfaceManagement/Playbooks/Cortex_ASM_-_ASM_Alert_README.md
  Packs/CortexAttackSurfaceManagement/Playbooks/Cortex_ASM_-_Decision.yml
  Packs/CortexAttackSurfaceManagement/Playbooks/Cortex_ASM_-_Email_Notification.yml
  Packs/CortexAttackSurfaceManagement/Playbooks/Cortex_ASM_-_Email_Notification_README.md
  Packs/CortexAttackSurfaceManagement/Playbooks/Cortex_ASM_-_Jira_Notification.yml
  Packs/CortexAttackSurfaceManagement/Playbooks/Cortex_ASM_-_Jira_Notification_README.md
  Packs/CortexAttackSurfaceManagement/Playbooks/Cortex_ASM_-_Remediation_Path_Rules.yml
  Packs/CortexAttackSurfaceManagement/Playbooks/Cortex_ASM_-_Remediation_Path_Rules_README.md
  Packs/CortexAttackSurfaceManagement/Playbooks/Cortex_ASM_-_ServiceNow_Notification.yml
  Packs/CortexAttackSurfaceManagement/Playbooks/Cortex_ASM_-_ServiceNow_Notification_README.md
  Packs/CortexAttackSurfaceManagement/README.md
  Packs/CortexAttackSurfaceManagement/ReleaseNotes/1_6_24.md
  Packs/CortexAttackSurfaceManagement/doc_files/Cortex_ASM_-_ASM_Alert.png
  Packs/CortexAttackSurfaceManagement/doc_files/Cortex_ASM_-_Email_Notification.png
  Packs/CortexAttackSurfaceManagement/doc_files/Cortex_ASM_-_Jira_Notification.png
  Packs/CortexAttackSurfaceManagement/doc_files/Cortex_ASM_-_Remediation_Path_Rules.png
  Packs/CortexAttackSurfaceManagement/doc_files/Cortex_ASM_-_ServiceNow_Notification.png
  Packs/CortexAttackSurfaceManagement/pack_metadata.json
  Tests/Marketplace/core_packs_xpanse_list.json
Labels: Contribution, docs-approved, ready-for-instance-test, Contribution Form Filled, Community, Xsoar Support Level

#28191 Fortigate Schema Update
  Packs/FortiGate/ModelingRules/FortiGate_1_3/FortiGate_1_3_schema.json
  Packs/FortiGate/ParsingRules/FortiGate/FortiGate.xif
  Packs/FortiGate/ReleaseNotes/1_0_23.md
  Packs/FortiGate/pack_metadata.json
Labels: docs-approved

#28217 Parsingrule Update 3
  Packs/CorelightZeek/ParsingRules/CorelightZeek/CorelightZeek.xif
  Packs/CorelightZeek/README.md
  Packs/CorelightZeek/ReleaseNotes/1_0_6.md
  Packs/CorelightZeek/pack_metadata.json
  Packs/CyberArkIdentity/ParsingRules/CyberArkIdentityParsingRules/CyberArkIdentityParsingRules.xif
  Packs/CyberArkIdentity/README.md
  Packs/CyberArkIdentity/ReleaseNotes/1_0_26.md
  Packs/CyberArkIdentity/pack_metadata.json
  Packs/Dropbox/ParsingRules/DropboxParsingRules/DropboxParsingRules.xif
  Packs/Dropbox/README.md
  Packs/Dropbox/ReleaseNotes/1_0_24.md
  Packs/Dropbox/pack_metadata.json
Labels: docs-approved

#28255 add stop section for external contrib builds
  .gitlab/ci/global.yml
Labels: docs-approved, ForceMerge

#28204 Taxi feed: headers bug
  Packs/ApiModules/ReleaseNotes/2_2_19.md
  Packs/ApiModules/Scripts/TAXII2ApiModule/TAXII2ApiModule.py
  Packs/ApiModules/Scripts/TAXII2ApiModule/TAXII2ApiModule_test.py
  Packs/ApiModules/pack_metadata.json
  Packs/FeedDHS/ReleaseNotes/2_0_15.md
  Packs/FeedDHS/pack_metadata.json
  Packs/FeedMitreAttackv2/ReleaseNotes/1_1_17.md
  Packs/FeedMitreAttackv2/pack_metadata.json
  Packs/FeedTAXII/ReleaseNotes/1_1_30.md
  Packs/FeedTAXII/pack_metadata.json
  Utils/gitlab_triggers/trigger_content_instance_testing_build.sh
Labels: docs-approved

#28117 update parsing rules
  Packs/AlibabaActionTrail/ParsingRules/AlibabaParsingRules/AlibabaParsingRules.xif
  Packs/AlibabaActionTrail/ReleaseNotes/1_0_18.md
  Packs/AlibabaActionTrail/pack_metadata.json
  Packs/ApacheTomcat/ParsingRules/ApacheTomcatParsingRules/ApacheTomcatParsingRules.xif
  Packs/ApacheTomcat/ReleaseNotes/1_0_6.md
  Packs/ApacheTomcat/pack_metadata.json
Labels: docs-approved

#28040 Packs/GSuiteAdmin.py: added user signout command
  Packs/GSuiteAdmin/.pack-ignore
  Packs/GSuiteAdmin/Integrations/GSuiteAdmin/GSuiteAdmin.py
  Packs/GSuiteAdmin/Integrations/GSuiteAdmin/GSuiteAdmin.yml
  Packs/GSuiteAdmin/Integrations/GSuiteAdmin/GSuiteAdmin_test.py
  Packs/GSuiteAdmin/Integrations/GSuiteAdmin/README.md
  Packs/GSuiteAdmin/ReleaseNotes/1_1_23.md
  Packs/GSuiteAdmin/TestPlaybooks/playbook-GSuiteAdmin-Test.yml
  Packs/GSuiteAdmin/pack_metadata.json
  Packs/GoogleDrive/Integrations/GoogleDrive/GoogleDrive.py
  Packs/GoogleDrive/Integrations/GoogleDrive/GoogleDrive.yml
  Packs/GoogleDrive/Integrations/GoogleDrive/README.md
  Packs/GoogleDrive/ReleaseNotes/1_2_37.md
  Packs/GoogleDrive/pack_metadata.json
Labels: Contribution, Partner, ready-for-instance-test, Contribution Form Filled, Xsoar Support Level

#28175 added artifacts path to step xsiam_server_ga_test_playbooks_results
  .gitlab/ci/on-push.yml
Labels: docs-approved

#28216 Parsingrule Update 2
  Packs/Barracuda_Cloudgen_Firewall/ParsingRules/Barracuda_Cloudgen_FirewallParsingRules/Barracuda_Cloudgen_FirewallParsingRules.xif
  Packs/Barracuda_Cloudgen_Firewall/README.md
  Packs/Barracuda_Cloudgen_Firewall/ReleaseNotes/1_0_1.md
  Packs/Barracuda_Cloudgen_Firewall/pack_metadata.json
  Packs/BluecatAddressManager/ParsingRules/BluecatAddressManager_1_3/BluecatAddressManager_1_3.xif
  Packs/BluecatAddressManager/ReleaseNotes/1_1_11.md
  Packs/BluecatAddressManager/pack_metadata.json
  Packs/Box/ParsingRules/BoxEventCollectorParsingRules/BoxEventCollectorParsingRules.xif
  Packs/Box/ReleaseNotes/3_1_28.md
  Packs/Box/pack_metadata.json
Labels: docs-approved

#28186 updated credentials display from credentials to Username
  Packs/Active_Directory_Query/Integrations/Active_Directory_Query/Active_Directory_Query.yml
  Packs/Active_Directory_Query/ReleaseNotes/1_6_19.md
  Packs/Active_Directory_Query/pack_metadata.json
Labels: docs-approved

#28263 [pan-os-create-tag] without comment argument
  Packs/PAN-OS/Integrations/Panorama/Panorama.py
  Packs/PAN-OS/Integrations/Panorama/Panorama_test.py
  Packs/PAN-OS/ReleaseNotes/1_17_15.md
  Packs/PAN-OS/pack_metadata.json
Labels: docs-approved
