Repository demisto/content, pull requests merged in 2023-12, with the labels that each got.

#31236 F5 APM fixed the marketplace build failure
  Packs/F5APM/README.md
Labels: docs-approved

#31183 Fixes For 'IP Enrichment - Generic v2' Playbook
  Packs/CommonPlaybooks/Playbooks/playbook-IP_Enrichment_-_Generic_v2.yml
  Packs/CommonPlaybooks/Playbooks/playbook-IP_Enrichment_-_Generic_v2_README.md
  Packs/CommonPlaybooks/ReleaseNotes/2_4_38.md
  Packs/CommonPlaybooks/pack_metadata.json
Labels: docs-approved

#31245 Check if should run Instance role
  .gitlab/ci/.gitlab-ci.bucket-upload.yml
Labels: docs-approved

#31254 Sync mp xsoar saas - with saas bucket.
  .gitlab/ci/.gitlab-ci.bucket-upload.yml
  Tests/scripts/validate_synced_buckets.sh
Labels: docs-approved

#30525 AWS Organizations
  Packs/AWS-Organizations/.pack-ignore
  Packs/AWS-Organizations/.secrets-ignore
  Packs/AWS-Organizations/Integrations/AWSOrganizations/AWSOrganizations.py
  Packs/AWS-Organizations/Integrations/AWSOrganizations/AWSOrganizations.yml
  Packs/AWS-Organizations/Integrations/AWSOrganizations/AWSOrganizations_description.md
  Packs/AWS-Organizations/Integrations/AWSOrganizations/AWSOrganizations_image.png
  Packs/AWS-Organizations/Integrations/AWSOrganizations/AWSOrganizations_test.py
  Packs/AWS-Organizations/Integrations/AWSOrganizations/README.md
  Packs/AWS-Organizations/Integrations/AWSOrganizations/command_examples.txt
  Packs/AWS-Organizations/Integrations/AWSOrganizations/test_data/data.py
  Packs/AWS-Organizations/README.md
  Packs/AWS-Organizations/TestPlaybooks/playbook-AWS-Organizations_Test.yml
  Packs/AWS-Organizations/pack_metadata.json
  Tests/conf.json
  organizations/organizations_description.md
Labels: docs-approved

#30501 NextToken in CommandResults
  Packs/Base/ReleaseNotes/1_32_52.md
  Packs/Base/Scripts/CommonServerPython/CommonServerPython.py
  Packs/Base/Scripts/CommonServerPython/CommonServerPython_test.py
  Packs/Base/pack_metadata.json
Labels: docs-approved

#31247 modified modeling rules of clearswift dlp
  Packs/ClearswiftDLP/.pack-ignore
  Packs/ClearswiftDLP/ModelingRules/ClearswiftDLP/ClearswiftDLP.xif
  Packs/ClearswiftDLP/ParsingRules/ClearswiftDLP/ClearswiftDLP.xif
  Packs/ClearswiftDLP/ReleaseNotes/1_0_3.md
  Packs/ClearswiftDLP/pack_metadata.json
Labels: docs-approved

#31084 QRadar: continue to poll in case of networking issues
  Packs/QRadar/Integrations/QRadar_v3/QRadar_v3.py
  Packs/QRadar/Integrations/QRadar_v3/QRadar_v3.yml
  Packs/QRadar/ReleaseNotes/2_4_42.md
  Packs/QRadar/pack_metadata.json
Labels: docs-approved

#31234 [ASM] EXPANDR 7225 - Update Ev1 Integration Display Name
  Packs/ExpanseV2/Integrations/ExpanseV2/ExpanseV2.yml
  Packs/ExpanseV2/ReleaseNotes/1_10_45.md
  Packs/ExpanseV2/pack_metadata.json
Labels: Contribution, docs-approved, Contribution Form Filled, Community, Xsoar Support Level, External PR, TIM Review

#31144 [xsoar-8 coverage] - use poll functions from SDK clients
  Tests/tests_e2e/client_utils.py
  Tests/tests_e2e/content/xsoar_saas/test_e2e_xsoar_saas.py
Labels: docs-approved

#31265 [CrowdStrike Falcon Intel v2] Fixed an issue in 'cs-actors' and 'cs-reports' commands
  Packs/CrowdStrikeIntel/Integrations/CrowdStrikeFalconIntel_v2/CrowdStrikeFalconIntel_v2.py
  Packs/CrowdStrikeIntel/Integrations/CrowdStrikeFalconIntel_v2/CrowdStrikeFalconIntel_v2.yml
  Packs/CrowdStrikeIntel/ReleaseNotes/2_0_34.md
  Packs/CrowdStrikeIntel/pack_metadata.json
Labels: docs-approved

#31253 oncall- installation orders
  Tests/Marketplace/search_and_install_packs.py
Labels: docs-approved

#31272 [XSUP 30575] Added full fields query param
  Packs/FeedCrowdstrikeFalconIntel/Integrations/FeedCrowdstrikeFalconIntel/FeedCrowdstrikeFalconIntel.py
  Packs/FeedCrowdstrikeFalconIntel/Integrations/FeedCrowdstrikeFalconIntel/FeedCrowdstrikeFalconIntel.yml
  Packs/FeedCrowdstrikeFalconIntel/Integrations/FeedCrowdstrikeFalconIntel/FeedCrowdstrikeFalconIntel_test.py
  Packs/FeedCrowdstrikeFalconIntel/Integrations/FeedCrowdstrikeFalconIntel/test_data/test_data.json
  Packs/FeedCrowdstrikeFalconIntel/ReleaseNotes/2_1_13.md
  Packs/FeedCrowdstrikeFalconIntel/pack_metadata.json
Labels: docs-approved

#31296 [Native Image] Add Symantec MSS to ignored content items
  Tests/docker_native_image_config.json
Labels: docs-approved

#30756 SentinelOne v2: Add 2 new commands
  Packs/SentinelOne/Integrations/SentinelOne-V2/README.md
  Packs/SentinelOne/Integrations/SentinelOne-V2/SentinelOne-V2.py
  Packs/SentinelOne/Integrations/SentinelOne-V2/SentinelOne-V2.yml
  Packs/SentinelOne/ReleaseNotes/3_2_13.md
  Packs/SentinelOne/pack_metadata.json
Labels: Contribution, Contribution Form Filled, Community, Partner Support Level, External PR, Partner-Approved

#31271 [XSUP 30870] Added full fields option for cs-actors and cs-reports commands
  Packs/CrowdStrikeIntel/Integrations/CrowdStrikeFalconIntel_v2/CrowdStrikeFalconIntel_v2.py
  Packs/CrowdStrikeIntel/Integrations/CrowdStrikeFalconIntel_v2/CrowdStrikeFalconIntel_v2.yml
  Packs/CrowdStrikeIntel/Integrations/CrowdStrikeFalconIntel_v2/CrowdStrikeFalconIntel_v2_test.py
  Packs/CrowdStrikeIntel/Integrations/CrowdStrikeFalconIntel_v2/README.md
  Packs/CrowdStrikeIntel/ReleaseNotes/2_0_35.md
  Packs/CrowdStrikeIntel/pack_metadata.json
Labels: docs-approved

#31314 update codeowners file
  .github/CODEOWNERS
Labels: docs-approved

#31308 fixing CimTrak_test.py unit tests
  Packs/CimTrak-SystemIntegrityAssurance/Integrations/CimTrak/CimTrak_test.py
  Packs/CimTrak-SystemIntegrityAssurance/Integrations/CimTrak/test_data/add_hash_allow_list.json
  Packs/CimTrak-SystemIntegrityAssurance/Integrations/CimTrak/test_data/add_hash_deny_list.json
  Packs/CimTrak-SystemIntegrityAssurance/Integrations/CimTrak/test_data/add_ticket.json
  Packs/CimTrak-SystemIntegrityAssurance/Integrations/CimTrak/test_data/add_ticket_comment.json
  Packs/CimTrak-SystemIntegrityAssurance/Integrations/CimTrak/test_data/check_file_against_trusted_file_registry_by_hash.json
  Packs/CimTrak-SystemIntegrityAssurance/Integrations/CimTrak/test_data/compliance_scan_children.json
  Packs/CimTrak-SystemIntegrityAssurance/Integrations/CimTrak/test_data/compliance_scan_with_summary.json
  Packs/CimTrak-SystemIntegrityAssurance/Integrations/CimTrak/test_data/delete_hash_allow_list.json
  Packs/CimTrak-SystemIntegrityAssurance/Integrations/CimTrak/test_data/delete_hash_deny_list.json
  Packs/CimTrak-SystemIntegrityAssurance/Integrations/CimTrak/test_data/demote_authoritative_baseline_files.json
  Packs/CimTrak-SystemIntegrityAssurance/Integrations/CimTrak/test_data/deploy.json
  Packs/CimTrak-SystemIntegrityAssurance/Integrations/CimTrak/test_data/deploy_by_date.json
  Packs/CimTrak-SystemIntegrityAssurance/Integrations/CimTrak/test_data/fetch_incidents.json
  Packs/CimTrak-SystemIntegrityAssurance/Integrations/CimTrak/test_data/file_analysis_by_hash.json
  Packs/CimTrak-SystemIntegrityAssurance/Integrations/CimTrak/test_data/file_analysis_by_object_detail_id.json
  Packs/CimTrak-SystemIntegrityAssurance/Integrations/CimTrak/test_data/force_sync.json
  Packs/CimTrak-SystemIntegrityAssurance/Integrations/CimTrak/test_data/get_agent_info.json
  Packs/CimTrak-SystemIntegrityAssurance/Integrations/CimTrak/test_data/get_agent_object_by_alternate_id.json
  Packs/CimTrak-SystemIntegrityAssurance/Integrations/CimTrak/test_data/get_agent_object_by_ip.json
  Packs/CimTrak-SystemIntegrityAssurance/Integrations/CimTrak/test_data/get_agent_object_by_name.json
  Packs/CimTrak-SystemIntegrityAssurance/Integrations/CimTrak/test_data/get_agent_object_id_by_alternate_system_id.json
  Packs/CimTrak-SystemIntegrityAssurance/Integrations/CimTrak/test_data/get_compliance_archive_details.json
  Packs/CimTrak-SystemIntegrityAssurance/Integrations/CimTrak/test_data/get_compliance_archive_summary.json
  Packs/CimTrak-SystemIntegrityAssurance/Integrations/CimTrak/test_data/get_current_compliance_items.json
  Packs/CimTrak-SystemIntegrityAssurance/Integrations/CimTrak/test_data/get_events.json
  Packs/CimTrak-SystemIntegrityAssurance/Integrations/CimTrak/test_data/get_object.json
  Packs/CimTrak-SystemIntegrityAssurance/Integrations/CimTrak/test_data/get_object_group.json
  Packs/CimTrak-SystemIntegrityAssurance/Integrations/CimTrak/test_data/get_objects.json
  Packs/CimTrak-SystemIntegrityAssurance/Integrations/CimTrak/test_data/get_sub_generations.json
  Packs/CimTrak-SystemIntegrityAssurance/Integrations/CimTrak/test_data/get_ticket_tasks.json
  Packs/CimTrak-SystemIntegrityAssurance/Integrations/CimTrak/test_data/get_tickets.json
  Packs/CimTrak-SystemIntegrityAssurance/Integrations/CimTrak/test_data/lock.json
  Packs/CimTrak-SystemIntegrityAssurance/Integrations/CimTrak/test_data/promote_authoritative_baseline_files.json
  Packs/CimTrak-SystemIntegrityAssurance/Integrations/CimTrak/test_data/run_report_by_name.json
  Packs/CimTrak-SystemIntegrityAssurance/Integrations/CimTrak/test_data/unlock.json
  Packs/CimTrak-SystemIntegrityAssurance/Integrations/CimTrak/test_data/update_task_disposition.json
  Packs/CimTrak-SystemIntegrityAssurance/Integrations/CimTrak/test_data/update_ticket.json
  Packs/CimTrak-SystemIntegrityAssurance/Integrations/CimTrak/test_data/view_file.json
Labels: docs-approved

#31269 Anomali ThreatStream v3 - Fix threatstream-get-indicators command
  Packs/Anomali_ThreatStream/Integrations/AnomaliThreatStreamv3/AnomaliThreatStreamv3.py
  Packs/Anomali_ThreatStream/Integrations/AnomaliThreatStreamv3/AnomaliThreatStreamv3.yml
  Packs/Anomali_ThreatStream/Integrations/AnomaliThreatStreamv3/AnomaliThreatStreamv3_test.py
  Packs/Anomali_ThreatStream/ReleaseNotes/2_2_9.md
  Packs/Anomali_ThreatStream/pack_metadata.json
Labels: docs-approved, release-notes-only

#31297 fixing jira file attachments, fixing mapping of newly created tickets
  Tests/scripts/convert_test_playbook_result_to_jira_issues.py
  Tests/scripts/test_modeling_rule_report.py
Labels: docs-approved

#31315 CiscoSMA Update
  Packs/CiscoSMA/ModelingRules/CiscoSMAModelingRules_1_3/CiscoSMAModelingRules_1_3.xif
  Packs/CiscoSMA/ReleaseNotes/1_1_23.md
  Packs/CiscoSMA/pack_metadata.json
Labels: docs-approved

#31192 updated docs
  Packs/MicrosoftGraphDeviceManagement/Integrations/MicrosoftGraphDeviceManagement/MicrosoftGraphDeviceManagement.yml
  Packs/MicrosoftGraphDeviceManagement/Integrations/MicrosoftGraphDeviceManagement/README.md
  Packs/MicrosoftGraphDeviceManagement/ReleaseNotes/1_1_20.md
  Packs/MicrosoftGraphDeviceManagement/pack_metadata.json
Labels: docs-approved

#31267 Fix an issue when there is only one incident in fetch_incidents powershell
  Packs/Base/ReleaseNotes/1_32_53.md
  Packs/Base/Scripts/CommonServerPowerShell/CommonServerPowerShell.Tests.ps1
  Packs/Base/Scripts/CommonServerPowerShell/CommonServerPowerShell.ps1
  Packs/Base/Scripts/CommonServerPowerShell/CommonServerPowerShell.yml
  Packs/Base/pack_metadata.json
Labels: docs-approved

#31310 fix for sdk nightly e2e tests
  .gitlab/ci/.gitlab-ci.sdk-nightly.yml
Labels: docs-approved

#31246 [qradar-v3] - handle connection errors
  Packs/QRadar/Integrations/QRadar_v3/QRadar_v3.py
  Packs/QRadar/Integrations/QRadar_v3/QRadar_v3.yml
  Packs/QRadar/Integrations/QRadar_v3/QRadar_v3_test.py
  Packs/QRadar/ReleaseNotes/2_4_43.md
  Packs/QRadar/pack_metadata.json
Labels: docs-approved

#31300 oncall-sdk-nightly-create-xsoar-instance
  .gitlab/ci/.gitlab-ci.on-push.yml
Labels: docs-approved

#31320 Support contributions when the name of the repo isn't content
  Utils/github_workflow_scripts/handle_external_pr.py
Labels: docs-approved

#31324 Oncall sdk nightly create xsoar instance
  .gitlab/ci/.gitlab-ci.on-push.yml
Labels: docs-approved, ForceMerge

#31146 EWS o365 eml download/incident creation inconsistencies
  Packs/MicrosoftExchangeOnline/Integrations/EWSO365/EWSO365.py
  Packs/MicrosoftExchangeOnline/Integrations/EWSO365/EWSO365.yml
  Packs/MicrosoftExchangeOnline/Integrations/EWSO365/EWSO365_test.py
  Packs/MicrosoftExchangeOnline/ReleaseNotes/1_2_32.md
  Packs/MicrosoftExchangeOnline/pack_metadata.json
Labels: Contribution, docs-approved, release-notes-only, Contribution Form Filled, Community, pending-contributor, Xsoar Support Level, External PR

#31319 [Native Image] Update native candidate
  Tests/docker_native_image_config.json
Labels: docs-approved

#30940 MATI - Supporting multiple inputs for generic enrichment commands
  Packs/MandiantAdvantageThreatIntelligence/Integrations/MandiantAdvantageThreatIntelligence/MandiantAdvantageThreatIntelligence.py
  Packs/MandiantAdvantageThreatIntelligence/Integrations/MandiantAdvantageThreatIntelligence/MandiantAdvantageThreatIntelligence.yml
  Packs/MandiantAdvantageThreatIntelligence/Integrations/MandiantAdvantageThreatIntelligence/MandiantAdvantageThreatIntelligence_test.py
  Packs/MandiantAdvantageThreatIntelligence/ReleaseNotes/1_0_13.md
  Packs/MandiantAdvantageThreatIntelligence/pack_metadata.json
Labels: Contribution, docs-approved, Partner, post-demo, Contribution Form Filled, pending-contributor, Partner Support Level, External PR, Partner-Approved, TIM Review

#31337 [Cortex Data Lake] Update the Docker Image and run ruff
  Packs/CortexDataLake/Integrations/CortexDataLake/CortexDataLake.py
  Packs/CortexDataLake/Integrations/CortexDataLake/CortexDataLake.yml
  Packs/CortexDataLake/ReleaseNotes/1_4_8.md
  Packs/CortexDataLake/pack_metadata.json
Labels: docs-approved

#30110 Support Threat Assessment functionality in MS Graph Security
  Packs/MicrosoftGraphSecurity/Integrations/MicrosoftGraphSecurity/MicrosoftGraphSecurity.py
  Packs/MicrosoftGraphSecurity/Integrations/MicrosoftGraphSecurity/MicrosoftGraphSecurity.yml
  Packs/MicrosoftGraphSecurity/Integrations/MicrosoftGraphSecurity/MicrosoftGraphSecurity_test.py
  Packs/MicrosoftGraphSecurity/Integrations/MicrosoftGraphSecurity/README.md
  Packs/MicrosoftGraphSecurity/Integrations/MicrosoftGraphSecurity/test_data/email_file_assessment_request.json
  Packs/MicrosoftGraphSecurity/Integrations/MicrosoftGraphSecurity/test_data/file_assessment_request.json
  Packs/MicrosoftGraphSecurity/Integrations/MicrosoftGraphSecurity/test_data/list_threat_assessment.json
  Packs/MicrosoftGraphSecurity/Integrations/MicrosoftGraphSecurity/test_data/mail_assessment_request.json
  Packs/MicrosoftGraphSecurity/Integrations/MicrosoftGraphSecurity/test_data/url_assessment_request.json
  Packs/MicrosoftGraphSecurity/ReleaseNotes/2_2_6.md
  Packs/MicrosoftGraphSecurity/TestPlaybooks/Microsoft_Graph_Security_test_threat_assessment.yml
  Packs/MicrosoftGraphSecurity/TestPlaybooks/Microsoft_Graph_security_test_ediscovery.yml
  Packs/MicrosoftGraphSecurity/pack_metadata.json
  Tests/conf.json
Labels: docs-approved

#31340 incident field helloworld onprem
  Packs/HelloWorld/IncidentFields/incidentfield-Hello_World_OnPrem.json
  Packs/HelloWorld/ReleaseNotes/3_0_2.md
  Packs/HelloWorld/pack_metadata.json
Labels: docs-approved

#31331 update ParseEmailFilesV2 to 0.1.19
  Packs/CommonScripts/ReleaseNotes/1_12_55.md
  Packs/CommonScripts/Scripts/ParseEmailFilesV2/ParseEmailFilesV2.py
  Packs/CommonScripts/Scripts/ParseEmailFilesV2/ParseEmailFilesV2.yml
  Packs/CommonScripts/Scripts/ParseEmailFilesV2/ParseEmailFilesV2_test.py
  Packs/CommonScripts/pack_metadata.json
Labels: docs-approved

#31124 Ciac 3790/add auto determine LDAP vendor
  Packs/OpenLDAP/Integrations/OpenLDAP/OpenLDAP.py
  Packs/OpenLDAP/Integrations/OpenLDAP/OpenLDAP.yml
  Packs/OpenLDAP/Integrations/OpenLDAP/OpenLDAP_description.md
  Packs/OpenLDAP/Integrations/OpenLDAP/OpenLDAP_test.py
  Packs/OpenLDAP/Integrations/OpenLDAP/README.md
  Packs/OpenLDAP/ReleaseNotes/2_0_13.md
  Packs/OpenLDAP/pack_metadata.json
Labels: docs-approved

#31327 [Versa Director] Update response data formats
  Packs/VersaDirector/Integrations/VersaDirector/VersaDirector.py
  Packs/VersaDirector/Integrations/VersaDirector/VersaDirector.yml
  Packs/VersaDirector/Integrations/VersaDirector/VersaDirector_test.py
  Packs/VersaDirector/ReleaseNotes/1_0_7.md
  Packs/VersaDirector/pack_metadata.json
Labels: docs-approved

#31028 Tessian integration setup
  Packs/Tessian/.pack-ignore
  Packs/Tessian/.secrets-ignore
  Packs/Tessian/Author_image.png
  Packs/Tessian/Integrations/Tessian/README.md
  Packs/Tessian/Integrations/Tessian/Tessian.py
  Packs/Tessian/Integrations/Tessian/Tessian.yml
  Packs/Tessian/Integrations/Tessian/Tessian_description.md
  Packs/Tessian/Integrations/Tessian/Tessian_image.png
  Packs/Tessian/Integrations/Tessian/Tessian_test.py
  Packs/Tessian/Integrations/Tessian/command_examples
  Packs/Tessian/README.md
  Packs/Tessian/pack_metadata.json
  package-lock.json
Labels: Contribution, docs-approved, Partner, post-demo, Contribution Form Filled, pending-contributor, Partner Support Level, External PR, Partner-Approved

#31212 [ASM] - EXPANDER 3741 - XSIAM Layout and Rule
  Packs/CortexAttackSurfaceManagement/LayoutRules/ASM.json
  Packs/CortexAttackSurfaceManagement/Layouts/layoutscontainer-ASM_Alert_Layout.json
  Packs/CortexAttackSurfaceManagement/README.md
  Packs/CortexAttackSurfaceManagement/ReleaseNotes/1_7_16.md
  Packs/CortexAttackSurfaceManagement/pack_metadata.json
  Tests/Marketplace/server_content_items.json
Labels: Contribution, Contribution Form Filled, Community, Xsoar Support Level, External PR, Security Review

#31230 Kiteworks Modeling CIAC-6377
  Packs/Kiteworks/.pack-ignore
  Packs/Kiteworks/.secrets-ignore
  Packs/Kiteworks/ModelingRules/Kiteworks/Kiteworks.xif
  Packs/Kiteworks/ModelingRules/Kiteworks/Kiteworks.yml
  Packs/Kiteworks/ModelingRules/Kiteworks/Kiteworks_schema.json
  Packs/Kiteworks/ParsingRules/Kiteworks/Kiteworks.xif
  Packs/Kiteworks/ParsingRules/Kiteworks/Kiteworks.yml
  Packs/Kiteworks/README.md
  Packs/Kiteworks/pack_metadata.json
Labels: docs-approved

#31346 Prisma SASE - Quarantine Host With Active Threat
  Packs/PrismaAccess/Playbooks/playbook-Prisma_SASE_-_Quarantine_Host_With_Active_Threat.yml
  Packs/PrismaAccess/Playbooks/playbook-Prisma_SASE_-_Quarantine_Host_With_Active_Threat_README.md
  Packs/PrismaAccess/ReleaseNotes/2_1_3.md
  Packs/PrismaAccess/doc_files/Prisma_SASE_-_Quarantine_Host_With_Active_Threat.png
  Packs/PrismaAccess/pack_metadata.json
Labels: docs-approved

#30990 Symantec web security service pack long running
  Packs/SymantecCloudSecureWebGateway/.pack-ignore
  Packs/SymantecCloudSecureWebGateway/.secrets-ignore
  Packs/SymantecCloudSecureWebGateway/Integrations/SymantecCloudSecureWebGatewayEventCollector/README.md
  Packs/SymantecCloudSecureWebGateway/Integrations/SymantecCloudSecureWebGatewayEventCollector/SymantecCloudSecureWebGatewayEventCollector.py
  Packs/SymantecCloudSecureWebGateway/Integrations/SymantecCloudSecureWebGatewayEventCollector/SymantecCloudSecureWebGatewayEventCollector.yml
  Packs/SymantecCloudSecureWebGateway/Integrations/SymantecCloudSecureWebGatewayEventCollector/SymantecCloudSecureWebGatewayEventCollector_description.md
  Packs/SymantecCloudSecureWebGateway/Integrations/SymantecCloudSecureWebGatewayEventCollector/SymantecCloudSecureWebGatewayEventCollector_image.png
  Packs/SymantecCloudSecureWebGateway/Integrations/SymantecCloudSecureWebGatewayEventCollector/SymantecCloudSecureWebGatewayEventCollector_test.py
  Packs/SymantecCloudSecureWebGateway/ModelingRules/SymantecCloudSecureWebGateway/SymantecCloudSecureWebGateway.xif
  Packs/SymantecCloudSecureWebGateway/ModelingRules/SymantecCloudSecureWebGateway/SymantecCloudSecureWebGateway.yml
  Packs/SymantecCloudSecureWebGateway/ModelingRules/SymantecCloudSecureWebGateway/SymantecCloudSecureWebGateway_schema.json
  Packs/SymantecCloudSecureWebGateway/ParsingRules/SymantecCloudSecureWebGateway/SymantecCloudSecureWebGateway.xif
  Packs/SymantecCloudSecureWebGateway/ParsingRules/SymantecCloudSecureWebGateway/SymantecCloudSecureWebGateway.yml
  Packs/SymantecCloudSecureWebGateway/README.md
  Packs/SymantecCloudSecureWebGateway/pack_metadata.json
Labels: docs-approved

#30819 FireEye ETP Event Collector fixes
  Packs/FireEyeETP/Integrations/FireEyeETPEventCollector/FireEyeETPEventCollector.py
  Packs/FireEyeETP/Integrations/FireEyeETPEventCollector/FireEyeETPEventCollector.yml
  Packs/FireEyeETP/Integrations/FireEyeETPEventCollector/FireEyeETPEventCollector_test.py
  Packs/FireEyeETP/Integrations/FireEyeETPEventCollector/test_data/activity_log.json
  Packs/FireEyeETP/ReleaseNotes/1_4_0.md
  Packs/FireEyeETP/pack_metadata.json
Labels: docs-approved

#30157 Trend micro vision one
  Packs/TrendMicroVisionOne/.secrets-ignore
  Packs/TrendMicroVisionOne/Integrations/TrendMicroVisionOneV3/README.md
  Packs/TrendMicroVisionOne/Integrations/TrendMicroVisionOneV3/TrendMicroVisionOneV3.py
  Packs/TrendMicroVisionOne/Integrations/TrendMicroVisionOneV3/TrendMicroVisionOneV3.yml
  Packs/TrendMicroVisionOne/Integrations/TrendMicroVisionOneV3/TrendMicroVisionOneV3_description.md
  Packs/TrendMicroVisionOne/Integrations/TrendMicroVisionOneV3/TrendMicroVisionOneV3_test.py
  Packs/TrendMicroVisionOne/Integrations/TrendMicroVisionOneV3/command_examples
  Packs/TrendMicroVisionOne/Integrations/TrendMicroVisionOneV3/test_data/add_blocklist.json
  Packs/TrendMicroVisionOne/Integrations/TrendMicroVisionOneV3/test_data/add_exception.json
  Packs/TrendMicroVisionOne/Integrations/TrendMicroVisionOneV3/test_data/add_note.json
  Packs/TrendMicroVisionOne/Integrations/TrendMicroVisionOneV3/test_data/add_suspicious_list.json
  Packs/TrendMicroVisionOne/Integrations/TrendMicroVisionOneV3/test_data/check_task_status.json
  Packs/TrendMicroVisionOne/Integrations/TrendMicroVisionOneV3/test_data/collect_forensic_file.json
  Packs/TrendMicroVisionOne/Integrations/TrendMicroVisionOneV3/test_data/delete_email.json
  Packs/TrendMicroVisionOne/Integrations/TrendMicroVisionOneV3/test_data/delete_suspicious_list.json
  Packs/TrendMicroVisionOne/Integrations/TrendMicroVisionOneV3/test_data/disable_user_account.json
  Packs/TrendMicroVisionOne/Integrations/TrendMicroVisionOneV3/test_data/download_analysis_report.json
  Packs/TrendMicroVisionOne/Integrations/TrendMicroVisionOneV3/test_data/download_information_collected_file.json
  Packs/TrendMicroVisionOne/Integrations/TrendMicroVisionOneV3/test_data/download_investigation_package.json
  Packs/TrendMicroVisionOne/Integrations/TrendMicroVisionOneV3/test_data/download_suspicious_object_list.json
  Packs/TrendMicroVisionOne/Integrations/TrendMicroVisionOneV3/test_data/enable_user_account.json
  Packs/TrendMicroVisionOne/Integrations/TrendMicroVisionOneV3/test_data/force_password_reset.json
  Packs/TrendMicroVisionOne/Integrations/TrendMicroVisionOneV3/test_data/force_signout.json
  Packs/TrendMicroVisionOne/Integrations/TrendMicroVisionOneV3/test_data/get_alert_details.json
  Packs/TrendMicroVisionOne/Integrations/TrendMicroVisionOneV3/test_data/get_email_activity_data.json
  Packs/TrendMicroVisionOne/Integrations/TrendMicroVisionOneV3/test_data/get_endpoint_activity_data.json
  Packs/TrendMicroVisionOne/Integrations/TrendMicroVisionOneV3/test_data/get_endpoint_info.json
  Packs/TrendMicroVisionOne/Integrations/TrendMicroVisionOneV3/test_data/get_file_analysis_result.json
  Packs/TrendMicroVisionOne/Integrations/TrendMicroVisionOneV3/test_data/get_file_analysis_status.json
  Packs/TrendMicroVisionOne/Integrations/TrendMicroVisionOneV3/test_data/isolate_endpoint.json
  Packs/TrendMicroVisionOne/Integrations/TrendMicroVisionOneV3/test_data/quarantine_email.json
  Packs/TrendMicroVisionOne/Integrations/TrendMicroVisionOneV3/test_data/remove_blocklist.json
  Packs/TrendMicroVisionOne/Integrations/TrendMicroVisionOneV3/test_data/remove_exception.json
  Packs/TrendMicroVisionOne/Integrations/TrendMicroVisionOneV3/test_data/remove_suspicious_list.json
  Packs/TrendMicroVisionOne/Integrations/TrendMicroVisionOneV3/test_data/restore_email_message.json
  Packs/TrendMicroVisionOne/Integrations/TrendMicroVisionOneV3/test_data/restore_endpoint.json
  Packs/TrendMicroVisionOne/Integrations/TrendMicroVisionOneV3/test_data/sandbox_submission_polling.json
  Packs/TrendMicroVisionOne/Integrations/TrendMicroVisionOneV3/test_data/submit_file_to_sandbox.json
  Packs/TrendMicroVisionOne/Integrations/TrendMicroVisionOneV3/test_data/submit_urls_sandbox.json
  Packs/TrendMicroVisionOne/Integrations/TrendMicroVisionOneV3/test_data/terminate_process.json
  Packs/TrendMicroVisionOne/Integrations/TrendMicroVisionOneV3/test_data/update_status.json
  Packs/TrendMicroVisionOne/ReleaseNotes/4_0_0.json
  Packs/TrendMicroVisionOne/ReleaseNotes/4_0_0.md
  Packs/TrendMicroVisionOne/pack_metadata.json
Labels: Contribution, Partner, ready-for-instance-test, pending-demo, post-demo, Contribution Form Filled, pending-contributor, Partner Support Level, External PR, Partner-Approved

#31347 README.md Update FeedORKL
  Packs/FeedORKL/README.md
Labels: Contribution, Contribution Form Filled, Community, Community Support Level, External PR

#30981 Feed Recorded Future download all compressed data on disk bug
  Packs/FeedRecordedFuture/Integrations/FeedRecordedFuture/FeedRecordedFuture.py
  Packs/FeedRecordedFuture/Integrations/FeedRecordedFuture/FeedRecordedFuture.yml
  Packs/FeedRecordedFuture/Integrations/FeedRecordedFuture/FeedRecordedFuture_test.py
  Packs/FeedRecordedFuture/Integrations/FeedRecordedFuture/test_data/test_gzip_compressed.txt
  Packs/FeedRecordedFuture/Integrations/FeedRecordedFuture/test_data/test_gzip_compressed.txt.gz
  Packs/FeedRecordedFuture/ReleaseNotes/1_0_32.md
  Packs/FeedRecordedFuture/pack_metadata.json
Labels: docs-approved

#31349 CISCO SMA u200b Update
  Packs/CiscoSMA/ModelingRules/CiscoSMAModelingRules_1_3/CiscoSMAModelingRules_1_3.xif
  Packs/CiscoSMA/ReleaseNotes/1_1_24.md
  Packs/CiscoSMA/pack_metadata.json
Labels: docs-approved

#31362 [e2e xsoar-saas] - fix issue with taxii2-server test
  Tests/tests_e2e/content/xsoar_saas/test_e2e_xsoar_saas.py
Labels: docs-approved

#31385 MS IIS Update3
  Packs/MicrosoftIISWebServer/ModelingRules/MicrosoftIISWebServerModelingRules_1_3/MicrosoftIISWebServerModelingRules_1_3.xif
  Packs/MicrosoftIISWebServer/ReleaseNotes/1_0_9.md
  Packs/MicrosoftIISWebServer/pack_metadata.json
Labels: docs-approved

#30787 Cybersixgill alerts typosquatting
  Packs/Cybersixgill-ActionableAlerts/.pack-ignore
  Packs/Cybersixgill-ActionableAlerts/Classifiers/classifier-mapper-incoming-Cybersixgill-Actionable-Alerts.json
  Packs/Cybersixgill-ActionableAlerts/IncidentFields/incidentfield-Cybersixgill_Suspicious_Domain.json
  Packs/Cybersixgill-ActionableAlerts/IncidentFields/incidentfield-Cybersixgill_Triggered_Domain.json
  Packs/Cybersixgill-ActionableAlerts/Integrations/CybersixgillActionableAlerts/CybersixgillActionableAlerts.py
  Packs/Cybersixgill-ActionableAlerts/Integrations/CybersixgillActionableAlerts/CybersixgillActionableAlerts.yml
  Packs/Cybersixgill-ActionableAlerts/Integrations/CybersixgillActionableAlerts/CybersixgillActionableAlerts_test.py
  Packs/Cybersixgill-ActionableAlerts/ReleaseNotes/1_2_10.json
  Packs/Cybersixgill-ActionableAlerts/ReleaseNotes/1_2_10.md
  Packs/Cybersixgill-ActionableAlerts/pack_metadata.json
Labels: Contribution, docs-approved, Partner, ready-for-instance-test, pending-demo, post-demo, Contribution Form Filled, pending-contributor, Partner Support Level, External PR, Security Review, Partner-Approved

#31123 Add a manual fatch once in 12 hours
  Packs/AccentureCTI_Feed/ReleaseNotes/1_1_28.md
  Packs/AccentureCTI_Feed/pack_metadata.json
  Packs/ApiModules/Scripts/CSVFeedApiModule/CSVFeedApiModule.py
  Packs/ApiModules/Scripts/CSVFeedApiModule/CSVFeedApiModule_test.py
  Packs/ApiModules/Scripts/HTTPFeedApiModule/HTTPFeedApiModule.py
  Packs/ApiModules/Scripts/HTTPFeedApiModule/HTTPFeedApiModule_test.py
  Packs/ApiModules/Scripts/JSONFeedApiModule/JSONFeedApiModule.py
  Packs/ApiModules/Scripts/JSONFeedApiModule/JSONFeedApiModule_test.py
  Packs/Base/ReleaseNotes/1_33_1.md
  Packs/Base/Scripts/CommonServerPython/CommonServerPython.py
  Packs/Base/Scripts/CommonServerPython/CommonServerPython_test.py
  Packs/Base/pack_metadata.json
  Packs/BitcoinAbuse/ReleaseNotes/1_0_41.md
  Packs/BitcoinAbuse/pack_metadata.json
  Packs/FeedAWS/ReleaseNotes/1_1_45.md
  Packs/FeedAWS/pack_metadata.json
  Packs/FeedAlienVault/ReleaseNotes/1_1_29.md
  Packs/FeedAlienVault/pack_metadata.json
  Packs/FeedBambenekConsulting/ReleaseNotes/1_1_27.md
  Packs/FeedBambenekConsulting/pack_metadata.json
  Packs/FeedBlocklist_de/ReleaseNotes/1_1_28.md
  Packs/FeedBlocklist_de/pack_metadata.json
  Packs/FeedBruteForceBlocker/ReleaseNotes/1_1_26.md
  Packs/FeedBruteForceBlocker/pack_metadata.json
  Packs/FeedCSV/ReleaseNotes/1_1_30.md
  Packs/FeedCSV/pack_metadata.json
  Packs/FeedCloudflare/ReleaseNotes/1_1_26.md
  Packs/FeedCloudflare/pack_metadata.json
  Packs/FeedDShield/ReleaseNotes/1_1_30.md
  Packs/FeedDShield/pack_metadata.json
  Packs/FeedFastly/ReleaseNotes/1_1_26.md
  Packs/FeedFastly/pack_metadata.json
  Packs/FeedFeodoTracker/ReleaseNotes/1_1_29.md
  Packs/FeedFeodoTracker/pack_metadata.json
  Packs/FeedGCPWhitelist/ReleaseNotes/2_0_31.md
  Packs/FeedGCPWhitelist/pack_metadata.json
  Packs/FeedIntel471/ReleaseNotes/2_1_2.md
  Packs/FeedIntel471/pack_metadata.json
  Packs/FeedJSON/ReleaseNotes/1_1_29.md
  Packs/FeedJSON/pack_metadata.json
  Packs/FeedMajesticMillion/ReleaseNotes/1_1_13.md
  Packs/FeedMajesticMillion/pack_metadata.json
  Packs/FeedMalwareBazaar/ReleaseNotes/1_0_31.md
  Packs/FeedMalwareBazaar/pack_metadata.json
  Packs/FeedMalwareDomainList/ReleaseNotes/1_1_9.md
  Packs/FeedMalwareDomainList/pack_metadata.json
  Packs/FeedPlainText/ReleaseNotes/1_1_26.md
  Packs/FeedPlainText/pack_metadata.json
  Packs/FeedSpamhaus/ReleaseNotes/1_1_23.md
  Packs/FeedSpamhaus/pack_metadata.json
  Packs/FeedURLhaus/.pack-ignore
  Packs/FeedURLhaus/ReleaseNotes/1_0_10.md
  Packs/FeedURLhaus/pack_metadata.json
  Packs/FeedZeroDayLiveTIFusion/ReleaseNotes/1_0_2.md
  Packs/FeedZeroDayLiveTIFusion/pack_metadata.json
  Packs/Feedsslabusech/ReleaseNotes/1_1_25.md
  Packs/Feedsslabusech/pack_metadata.json
  Packs/iDefense/ReleaseNotes/3_2_12.md
  Packs/iDefense/pack_metadata.json
  Tests/conf.json
Labels: docs-approved, ForceMerge

#31342 Fix gmail get mail context output
  Packs/Gmail/Integrations/Gmail/Gmail.py
  Packs/Gmail/Integrations/Gmail/Gmail.yml
  Packs/Gmail/Integrations/Gmail/README.md
  Packs/Gmail/ReleaseNotes/1_3_15.json
  Packs/Gmail/ReleaseNotes/1_3_15.md
  Packs/Gmail/pack_metadata.json
Labels: docs-approved, ForceMerge

#30637 [Zscaler] Add URLs to Retaining Parent Category
  Packs/Zscaler/Integrations/Zscaler/Zscaler.py
  Packs/Zscaler/Integrations/Zscaler/Zscaler.yml
  Packs/Zscaler/Integrations/Zscaler/Zscaler_test.py
  Packs/Zscaler/ReleaseNotes/1_3_16.md
  Packs/Zscaler/pack_metadata.json
Labels: docs-approved

#31378 Armis event collector extend alerts data set
  Packs/Armis/Integrations/ArmisEventCollector/ArmisEventCollector.py
  Packs/Armis/Integrations/ArmisEventCollector/ArmisEventCollector.yml
  Packs/Armis/Integrations/ArmisEventCollector/ArmisEventCollector_test.py
  Packs/Armis/ReleaseNotes/1_1_9.md
  Packs/Armis/pack_metadata.json
Labels: docs-approved

#31155 fixed - add-test-xdr-env-ng-nightly
  .gitlab/ci/.gitlab-ci.on-push.yml
  Tests/scripts/check_jobs_done.py
Labels: docs-approved

#31357 [EWS v2] Update docker image with previous exchangelib version
  Packs/MicrosoftExchangeOnPremise/Integrations/EWSv2/EWSv2.yml
  Packs/MicrosoftExchangeOnPremise/ReleaseNotes/2_0_11.md
  Packs/MicrosoftExchangeOnPremise/pack_metadata.json
Labels: docs-approved, ForceMerge

#31237 EXPANDR-7181 Fix issues for AWS rule logic
  Packs/AWS-Enrichment-Remediation/ReleaseNotes/1_1_9.md
  Packs/AWS-Enrichment-Remediation/Scripts/AWSRecreateSG/AWSRecreateSG.py
  Packs/AWS-Enrichment-Remediation/Scripts/AWSRecreateSG/AWSRecreateSG.yml
  Packs/AWS-Enrichment-Remediation/Scripts/AWSRecreateSG/AWSRecreateSG_test.py
  Packs/AWS-Enrichment-Remediation/pack_metadata.json
Labels: Contribution, docs-approved, release-notes-only, Contribution Form Filled, Community, Xsoar Support Level, External PR

#31330 Fix for playbooks that uses deprecated sub-playbooks
  Packs/CommonPlaybooks/Playbooks/playbook-Detonate_File_-_Generic.yml
  Packs/CommonPlaybooks/Playbooks/playbook-Detonate_File_-_Generic_README.md
  Packs/CommonPlaybooks/Playbooks/playbook-Detonate_URL_-_Generic_v1.5.yml
  Packs/CommonPlaybooks/Playbooks/playbook-Detonate_URL_-_Generic_v1.5_README.md
  Packs/CommonPlaybooks/ReleaseNotes/2_4_39.md
  Packs/CommonPlaybooks/doc_files/Detonate_File_-_Generic.png
  Packs/CommonPlaybooks/doc_files/Detonate_URL_-_Generic_v1.5.png
  Packs/CommonPlaybooks/pack_metadata.json
  Packs/Core/Playbooks/playbook-Ransomware_Enrich_and_Contain.yml
  Packs/Core/Playbooks/playbook-Ransomware_Enrich_and_Contain_README.md
  Packs/Core/ReleaseNotes/3_0_3.md
  Packs/Core/doc_files/Ransomware_Enrich_and_Contain.png
  Packs/Core/pack_metadata.json
  Packs/CortexXDR/Playbooks/Cortex_XDR_-_Malware_Investigation.yml
  Packs/CortexXDR/Playbooks/Cortex_XDR_-_Malware_Investigation_README.md
  Packs/CortexXDR/ReleaseNotes/6_0_8.md
  Packs/CortexXDR/doc_files/Cortex_XDR_-_Malware_Investigation.png
  Packs/CortexXDR/pack_metadata.json
Labels: docs-approved

#31403 Update "malware investigation and response" and cortex xdr image path
  Packs/CortexXDR/README.md
  Packs/MalwareInvestigationAndResponse/README.md
Labels: docs-approved

#31339 [Qradar] - add timeout param, update test-module and implement retry for connection errors
  Packs/QRadar/Integrations/QRadar_v3/QRadar_v3.py
  Packs/QRadar/Integrations/QRadar_v3/QRadar_v3.yml
  Packs/QRadar/Integrations/QRadar_v3/QRadar_v3_test.py
  Packs/QRadar/Integrations/QRadar_v3/README.md
  Packs/QRadar/ReleaseNotes/2_4_45.md
  Packs/QRadar/pack_metadata.json
Labels: docs-approved

#30694 [AWS Athena] Move From Beta to GA
  Packs/AWS-Athena/Integrations/AWS-Athena/AWS-Athena.py
  Packs/AWS-Athena/Integrations/AWS-Athena/AWS-Athena.yml
  Packs/AWS-Athena/Integrations/AWS-Athena/AWS-Athena_description.md
  Packs/AWS-Athena/Integrations/AWS-Athena/AWS-Athena_test.py
  Packs/AWS-Athena/Integrations/AWS-Athena/README.md
  Packs/AWS-Athena/Integrations/AWS-Athena/test_data/expected_context/get_query_execution_command.json
  Packs/AWS-Athena/Integrations/AWS-Athena/test_data/expected_context/get_query_results_command.json
  Packs/AWS-Athena/Integrations/AWS-Athena/test_data/expected_context/start_query_command.json
  Packs/AWS-Athena/Integrations/AWS-Athena/test_data/expected_hr/get_query_results_command.txt
  Packs/AWS-Athena/Integrations/AWS-Athena/test_data/raw_data_mock/get_query_execution.json
  Packs/AWS-Athena/Integrations/AWS-Athena/test_data/raw_data_mock/get_query_results.json
  Packs/AWS-Athena/Integrations/AWS-Athena/test_data/raw_data_mock/start_query_execution.json
  Packs/AWS-Athena/ReleaseNotes/2_0_0.json
  Packs/AWS-Athena/ReleaseNotes/2_0_0.md
  Packs/AWS-Athena/TestPlaybooks/playbook-AWS-Athena-Beta.yml
  Packs/AWS-Athena/pack_metadata.json
Labels: docs-approved

#31399 Malware Investigation and Response - Added specification for integration brand for the !endpoint command.
  Packs/CrowdStrikeFalcon/Playbooks/playbook-CrowdStrike_Falcon_Malware_-_Incident_Enrichment.yml
  Packs/CrowdStrikeFalcon/ReleaseNotes/1_12_7.md
  Packs/CrowdStrikeFalcon/pack_metadata.json
  Packs/MicrosoftDefenderAdvancedThreatProtection/Playbooks/playbook-MDE_Malware_-_Incident_Enrichment.yml
  Packs/MicrosoftDefenderAdvancedThreatProtection/ReleaseNotes/1_16_20.md
  Packs/MicrosoftDefenderAdvancedThreatProtection/pack_metadata.json
Labels: docs-approved

#31414 Fix js get incident tasks by state
  Packs/DemistoRESTAPI/ReleaseNotes/1_3_41.md
  Packs/DemistoRESTAPI/Scripts/GetIncidentTasksByState/GetIncidentTasksByState.js
  Packs/DemistoRESTAPI/pack_metadata.json
Labels: docs-approved, ForceMerge

#31065 Azure sentinel assignement options
  Packs/AzureSentinel/.pack-ignore
  Packs/AzureSentinel/Integrations/AzureSentinel/AzureSentinel.py
  Packs/AzureSentinel/Integrations/AzureSentinel/AzureSentinel.yml
  Packs/AzureSentinel/Integrations/AzureSentinel/AzureSentinel_description.md
  Packs/AzureSentinel/Integrations/AzureSentinel/README.md
  Packs/AzureSentinel/README.md
  Packs/AzureSentinel/ReleaseNotes/1_5_33.md
  Packs/AzureSentinel/pack_metadata.json
Labels: Contribution, docs-approved, post-demo, Contribution Form Filled, Community, Xsoar Support Level, External PR, Security Review

#31329 Bugfix/XSUP-30713/add-InternalIPRanges-as-playbook-input
  Packs/CortexXDR/Playbooks/Cortex_XDR_Alerts_Handling.yml
  Packs/CortexXDR/Playbooks/Cortex_XDR_Alerts_Handling_README.md
  Packs/CortexXDR/Playbooks/Cortex_XDR_incident_handling_v3_6_5.yml
  Packs/CortexXDR/Playbooks/Cortex_XDR_incident_handling_v3_6_5_README.md
  Packs/CortexXDR/ReleaseNotes/6_0_9.md
  Packs/CortexXDR/pack_metadata.json
Labels: docs-approved

#31420 CRTX-96742: Release a new base pack
  Packs/Base/ReleaseNotes/1_33_4.md
  Packs/Base/Scripts/SanePdfReport/SanePdfReport.yml
  Packs/Base/pack_metadata.json
Labels: docs-approved

#31318 SetGridField fixes
  Packs/CommonScripts/ReleaseNotes/1_12_57.md
  Packs/CommonScripts/Scripts/SetGridField/SetGridField.py
  Packs/CommonScripts/Scripts/SetGridField/SetGridField.yml
  Packs/CommonScripts/Scripts/SetGridField/SetGridField_test.py
  Packs/CommonScripts/pack_metadata.json
Labels: docs-approved

#31062 O365 security and compliance - search action - handle no results better
  Packs/MicrosoftExchangeOnline/Integrations/SecurityAndComplianceV2/SecurityAndComplianceV2.ps1
  Packs/MicrosoftExchangeOnline/Integrations/SecurityAndComplianceV2/SecurityAndComplianceV2.yml
  Packs/MicrosoftExchangeOnline/Playbooks/playbook-O365-SecurityAndCompliance-Search.yml
  Packs/MicrosoftExchangeOnline/ReleaseNotes/1_2_32.md
  Packs/MicrosoftExchangeOnline/pack_metadata.json
Labels: docs-approved, release-notes-only

#31417 added xsoar-saas_test_e2e_results
  Tests/scripts/check_jobs_done.py
Labels: docs-approved

#31418 Fix "unexpected keyword argument" Error
  Packs/FiltersAndTransformers/ReleaseNotes/1_2_45.md
  Packs/FiltersAndTransformers/Scripts/IfElif/IfElif.py
  Packs/FiltersAndTransformers/Scripts/IfElif/IfElif.yml
  Packs/FiltersAndTransformers/pack_metadata.json
Labels: docs-approved

#31323 New script: ReadQRCode
  Packs/CommonScripts/.pack-ignore
  Packs/CommonScripts/ReleaseNotes/1_13_0.md
  Packs/CommonScripts/Scripts/ReadQRCode/README.md
  Packs/CommonScripts/Scripts/ReadQRCode/ReadQRCode.py
  Packs/CommonScripts/Scripts/ReadQRCode/ReadQRCode.yml
  Packs/CommonScripts/Scripts/ReadQRCode/ReadQRCode_test.py
  Packs/CommonScripts/Scripts/ReadQRCode/test_data/not_a_qr_code.png
  Packs/CommonScripts/Scripts/ReadQRCode/test_data/qr_code.png
  Packs/CommonScripts/Scripts/ReadQRCode/test_data/text.txt
  Packs/CommonScripts/pack_metadata.json
Labels: docs-approved

#31355 Add argument include_resolved_param to sentinelone-get-threats
  Packs/SentinelOne/Integrations/SentinelOne-V2/README.md
  Packs/SentinelOne/Integrations/SentinelOne-V2/SentinelOne-V2.py
  Packs/SentinelOne/Integrations/SentinelOne-V2/SentinelOne-V2.yml
  Packs/SentinelOne/ReleaseNotes/3_2_14.md
  Packs/SentinelOne/pack_metadata.json
Labels: Contribution, Contribution Form Filled, Community, Partner Support Level, External PR, Partner-Approved

#31398 Fix MDE settings description
  Packs/MicrosoftDefenderAdvancedThreatProtection/Integrations/MicrosoftDefenderAdvancedThreatProtection/MicrosoftDefenderAdvancedThreatProtection.yml
  Packs/MicrosoftDefenderAdvancedThreatProtection/Integrations/MicrosoftDefenderAdvancedThreatProtection/README.md
  Packs/MicrosoftDefenderAdvancedThreatProtection/ReleaseNotes/1_16_21.md
  Packs/MicrosoftDefenderAdvancedThreatProtection/pack_metadata.json
Labels: docs-approved

#31434 Armis fix url suffix
  Packs/Armis/Integrations/Armis/Armis.py
  Packs/Armis/Integrations/Armis/Armis.yml
  Packs/Armis/Integrations/Armis/Armis_test.py
  Packs/Armis/ReleaseNotes/1_1_10.md
  Packs/Armis/pack_metadata.json
Labels: docs-approved

#31377 Feed Elastic: fetch in batches
  Packs/FeedElasticsearch/Integrations/FeedElasticsearch/FeedElasticsearch.py
  Packs/FeedElasticsearch/Integrations/FeedElasticsearch/FeedElasticsearch.yml
  Packs/FeedElasticsearch/Integrations/FeedElasticsearch/FeedElasticsearch_test.py
  Packs/FeedElasticsearch/ReleaseNotes/1_1_3.md
  Packs/FeedElasticsearch/pack_metadata.json
Labels: docs-approved

#31229 added logs
  Packs/FreshworksFreshservice/Integrations/FreshworksFreshservice/FreshworksFreshservice.py
  Packs/FreshworksFreshservice/Integrations/FreshworksFreshservice/FreshworksFreshservice.yml
  Packs/FreshworksFreshservice/ReleaseNotes/1_0_19.md
  Packs/FreshworksFreshservice/pack_metadata.json
Labels: docs-approved

#31345 Updated the extraction logic to extract all type of artifacts instead of only domains.
  Packs/GoogleChronicleBackstory/Integrations/GoogleChronicleBackstory/GoogleChronicleBackstory.py
  Packs/GoogleChronicleBackstory/Integrations/GoogleChronicleBackstory/GoogleChronicleBackstory.yml
  Packs/GoogleChronicleBackstory/Integrations/GoogleChronicleBackstory/GoogleChronicleBackstory_test.py
  Packs/GoogleChronicleBackstory/Integrations/GoogleChronicleBackstory/README.md
  Packs/GoogleChronicleBackstory/Integrations/GoogleChronicleBackstory/test_data/list_ioc_ec.json
  Packs/GoogleChronicleBackstory/Integrations/GoogleChronicleBackstory/test_data/list_ioc_response.txt
  Packs/GoogleChronicleBackstory/ReleaseNotes/3_0_8.md
  Packs/GoogleChronicleBackstory/pack_metadata.json
Labels: Contribution, Partner, Contribution Form Filled, Partner Support Level, External PR, Partner-Approved

#31359 Added support for report attachment download
  Packs/CofenseTriage/.pack-ignore
  Packs/CofenseTriage/Integrations/CofenseTriagev3/CofenseTriagev3.py
  Packs/CofenseTriage/Integrations/CofenseTriagev3/CofenseTriagev3.yml
  Packs/CofenseTriage/Integrations/CofenseTriagev3/CofenseTriagev3_test.py
  Packs/CofenseTriage/Integrations/CofenseTriagev3/README.md
  Packs/CofenseTriage/Integrations/CofenseTriagev3/test_data/report_attachment/report_attachment_download_response.xml
  Packs/CofenseTriage/Integrations/CofenseTriagev3/test_data/report_attachment/report_attachment_list.md
  Packs/CofenseTriage/Integrations/CofenseTriagev3/test_data/report_attachment/report_attachment_list_context.json
  Packs/CofenseTriage/Integrations/CofenseTriagev3/test_data/report_attachment/report_attachment_list_response.json
  Packs/CofenseTriage/ReleaseNotes/2_1_20.md
  Packs/CofenseTriage/pack_metadata.json
Labels: Contribution, Partner, Contribution Form Filled, Partner Support Level, External PR, Partner-Approved, TIM Review

#31394 CS Falcon - Add batch_id argument to run_command
  Packs/CrowdStrikeFalcon/Integrations/CrowdStrikeFalcon/CrowdStrikeFalcon.py
  Packs/CrowdStrikeFalcon/Integrations/CrowdStrikeFalcon/CrowdStrikeFalcon.yml
  Packs/CrowdStrikeFalcon/Integrations/CrowdStrikeFalcon/CrowdStrikeFalcon_test.py
  Packs/CrowdStrikeFalcon/Integrations/CrowdStrikeFalcon/README.md
  Packs/CrowdStrikeFalcon/Integrations/CrowdStrikeFalcon/test_data/run_command/run_command_with_batch.json
  Packs/CrowdStrikeFalcon/ReleaseNotes/1_12_8.md
  Packs/CrowdStrikeFalcon/pack_metadata.json
  Tests/conf.json
Labels: docs-approved

#31140 Added context output and indicator tagging to CreateIndicatorsFromStix
  Packs/CommonScripts/ReleaseNotes/1_13_5.md
  Packs/CommonScripts/Scripts/CreateIndicatorsFromSTIX/CreateIndicatorsFromSTIX.py
  Packs/CommonScripts/Scripts/CreateIndicatorsFromSTIX/CreateIndicatorsFromSTIX.yml
  Packs/CommonScripts/Scripts/CreateIndicatorsFromSTIX/CreateIndicatorsFromSTIX_test.py
  Packs/CommonScripts/Scripts/CreateIndicatorsFromSTIX/README.md
  Packs/CommonScripts/pack_metadata.json
Labels: Contribution, docs-approved, Contribution Form Filled, Community, pending-contributor, Xsoar Support Level, External PR

#31475 Update condition for create link to jira for contributions prs
  .github/workflows/close_jira_issue_by_pr_merge.yml
  .github/workflows/link_edited_pr_to_jira_issue.yml
Labels: docs-approved

#31476 bug fix
  Packs/RSASecureID/ParsingRules/RSASecureID/RSASecureID.xif
  Packs/RSASecureID/ParsingRules/RSASecureID/RSASecureID.yml
Labels: docs-approved, ForceMerge

#31194 Fixed auto closing tickets in service now
  Packs/ServiceNow/Integrations/ServiceNowv2/ServiceNowv2.py
  Packs/ServiceNow/Integrations/ServiceNowv2/ServiceNowv2.yml
  Packs/ServiceNow/ReleaseNotes/2_5_48.md
  Packs/ServiceNow/pack_metadata.json
Labels: docs-approved

#31481 Fix email com
  Packs/EmailCommunication/Classifiers/classifier-EWS_-_Incoming_Mapper_-_Email_Communication.json
  Packs/EmailCommunication/Classifiers/classifier-Gmail_-_Incoming_Mapper_-_Email_Communication.json
  Packs/EmailCommunication/Classifiers/classifier-MSGraphMailSingleUser_-_Incoming_Mapper_-_Email_Communication.json
  Packs/EmailCommunication/Classifiers/classifier-MSGraphMail_-_Incoming_Mapper_-_Email_Communication.json
  Packs/EmailCommunication/ReleaseNotes/2_0_16.json
  Packs/EmailCommunication/ReleaseNotes/2_0_16.md
  Packs/EmailCommunication/Scripts/SendEmailReply/SendEmailReply.py
  Packs/EmailCommunication/Scripts/SendEmailReply/SendEmailReply.yml
  Packs/EmailCommunication/Scripts/SendEmailReply/SendEmailReply_test.py
  Packs/EmailCommunication/pack_metadata.json
Labels: docs-approved

#31328 Replacing Qradar search PB with the representative command
  Packs/CommonPlaybooks/Playbooks/playbook-SIEM_-_Search_for_Failed_logins.yml
  Packs/CommonPlaybooks/Playbooks/playbook-SIEM_-_Search_for_Failed_logins_README.md
  Packs/CommonPlaybooks/ReleaseNotes/2_4_40.json
  Packs/CommonPlaybooks/ReleaseNotes/2_4_40.md
  Packs/CommonPlaybooks/doc_files/SIEM_-_Search_for_Failed_logins.png
  Packs/CommonPlaybooks/pack_metadata.json
  Packs/QRadar/Playbooks/playbook-QRadarFullSearch.yml
  Packs/QRadar/Playbooks/playbook-QRadarFullSearch_README.md
  Packs/QRadar/Playbooks/playbook-QRadar_-_Get_Offense_Logs.yml
  Packs/QRadar/Playbooks/playbook-QRadar_-_Get_Offense_Logs_README.md
  Packs/QRadar/Playbooks/playbook-QRadar_Build_Query_and_Search.yml
  Packs/QRadar/Playbooks/playbook-QRadar_Build_Query_and_Search_README.md
  Packs/QRadar/ReleaseNotes/2_4_46.json
  Packs/QRadar/ReleaseNotes/2_4_46.md
  Packs/QRadar/doc_files/QRadar_-_Get_Offense_Logs.png
  Packs/QRadar/doc_files/QRadar_Build_Query_and_Search.png
  Packs/QRadar/pack_metadata.json
Labels: docs-approved

#31402 [PAN-OS Policy Optimizer] Add pagination support to `pan-os-po-get-rules`
  Packs/PANOSPolicyOptimizer/Integrations/PANOSPolicyOptimizer/PANOSPolicyOptimizer.py
  Packs/PANOSPolicyOptimizer/Integrations/PANOSPolicyOptimizer/PANOSPolicyOptimizer.yml
  Packs/PANOSPolicyOptimizer/Integrations/PANOSPolicyOptimizer/PANOSPolicyOptimizer_test.py
  Packs/PANOSPolicyOptimizer/Integrations/PANOSPolicyOptimizer/README.md
  Packs/PANOSPolicyOptimizer/ReleaseNotes/1_1_20.md
  Packs/PANOSPolicyOptimizer/pack_metadata.json
Labels: docs-approved

#31510 adding xsoar-saas_test_e2e_results to needs list
  .gitlab/ci/.gitlab-ci.on-push.yml
Labels: docs-approved

#31019 Free Feeds Pack \ Small fixes to names
  Packs/FreeFeeds/pack_metadata.json
Labels: docs-approved

#31482 OpenCVE throws an error when trying to enrich a CVE
  Packs/OpenCVE/Integrations/OpenCVE/OpenCVE.py
  Packs/OpenCVE/Integrations/OpenCVE/OpenCVE.yml
  Packs/OpenCVE/Integrations/OpenCVE/test_data/CVE-2021-26418.json
  Packs/OpenCVE/ReleaseNotes/1_0_2.md
  Packs/OpenCVE/pack_metadata.json
Labels: docs-approved

#31483 CTF fixes
  Packs/CTF02/Playbooks/playbook-CTF_2_-_Classify_an_incident_RDP_Brute_force.yml
  Packs/CTF02/ReleaseNotes/1_0_1.md
  Packs/CTF02/pack_metadata.json
  Packs/ctf01/Playbooks/playbook-CTF_1_-_Get_to_know_XSOAR8.yml
  Packs/ctf01/ReleaseNotes/1_0_3.md
  Packs/ctf01/pack_metadata.json
Labels: docs-approved

#31461 Fix command analysis PB
  Packs/CommonPlaybooks/Playbooks/playbook-Command-Line_Analysis.yml
  Packs/CommonPlaybooks/ReleaseNotes/2_4_41.md
  Packs/CommonPlaybooks/doc_files/Command-Line_Analysis.png
  Packs/CommonPlaybooks/pack_metadata.json
Labels: docs-approved

#31136 Added Plug and Fetch tags
  Packs/FeedLOLBAS/pack_metadata.json
  Packs/FeedMitreAttackv2/pack_metadata.json
Labels: docs-approved

#31393 Slack bb fixes
  Packs/Slack/.pack-ignore
  Packs/Slack/Integrations/SlackV3/SlackV3.py
  Packs/Slack/Integrations/SlackV3/SlackV3.yml
  Packs/Slack/Integrations/SlackV3/SlackV3_test.py
  Packs/Slack/Integrations/SlackV3/test_data/entitlement_response_payload.txt
  Packs/Slack/Playbooks/playbook-SlackBlockBuilderResponseExample.yml
  Packs/Slack/Playbooks/playbook-SlackBlockBuilderResponseExample_README.md
  Packs/Slack/ReleaseNotes/3_3_0.json
  Packs/Slack/ReleaseNotes/3_3_0.md
  Packs/Slack/Scripts/GetSlackBlockBuilderResponse/GetSlackBlockBuilderResponse.py
  Packs/Slack/Scripts/GetSlackBlockBuilderResponse/GetSlackBlockBuilderResponse.yml
  Packs/Slack/Scripts/GetSlackBlockBuilderResponse/GetSlackBlockBuilderResponse_test.py
  Packs/Slack/Scripts/GetSlackBlockBuilderResponse/README.md
  Packs/Slack/Scripts/SlackBlockBuilder/README.md
  Packs/Slack/doc_files/SlackBlockBuilder_Response_Example.png
  Packs/Slack/pack_metadata.json
Labels: docs-approved

#31404 Update incident occurred time
  Packs/AbnormalSecurity/Integrations/AbnormalSecurity/AbnormalSecurity.py
  Packs/AbnormalSecurity/Integrations/AbnormalSecurity/AbnormalSecurity_test.py
  Packs/AbnormalSecurity/Integrations/AbnormalSecurity/test_data/test_get_details_of_a_threat.json
  Packs/AbnormalSecurity/Integrations/AbnormalSecurity/test_data/test_get_list_of_abnormal_threats.json
  Packs/AbnormalSecurity/Integrations/AbnormalSecurity/test_data/test_get_list_of_abuse_campaigns.json
  Packs/AbnormalSecurity/ReleaseNotes/2_2_1.md
  Packs/AbnormalSecurity/pack_metadata.json
Labels: Contribution, Partner, Contribution Form Filled, pending-contributor, Partner Support Level, External PR, Partner-Approved, TIM Review

#31520 install specific version of neo4j in ci
  .circleci/config.yml
Labels: docs-approved

#31514 Update Elasticsearch pack README.md
  Packs/Elasticsearch/README.md
Labels: docs-approved

#31517 [Azure Compute v2] Fixed the API version
  Packs/AzureCompute/Integrations/AzureCompute_v2/AzureCompute_v2.py
  Packs/AzureCompute/Integrations/AzureCompute_v2/AzureCompute_v2.yml
  Packs/AzureCompute/ReleaseNotes/1_2_19.md
  Packs/AzureCompute/pack_metadata.json
Labels: docs-approved

#31512 First sso fix ip task
  Packs/CortexXDR/Playbooks/playbook-Cortex_XDR_-_First_SSO_Access.yml
  Packs/CortexXDR/ReleaseNotes/6_0_10.md
  Packs/CortexXDR/pack_metadata.json
Labels: docs-approved

#31167 Added new pack: Email Hippo
  Packs/CommonDashboards/Dashboards/dashboard-APIExecutionMetrics.json
  Packs/CommonDashboards/ReleaseNotes/1_3_8.md
  Packs/CommonDashboards/pack_metadata.json
  Packs/EmailHippo/.pack-ignore
  Packs/EmailHippo/.secrets-ignore
  Packs/EmailHippo/Integrations/EmailHippo/EmailHippo.py
  Packs/EmailHippo/Integrations/EmailHippo/EmailHippo.yml
  Packs/EmailHippo/Integrations/EmailHippo/EmailHippo_description.md
  Packs/EmailHippo/Integrations/EmailHippo/EmailHippo_image.png
  Packs/EmailHippo/Integrations/EmailHippo/EmailHippo_test.py
  Packs/EmailHippo/Integrations/EmailHippo/README.md
  Packs/EmailHippo/Integrations/EmailHippo/commands.txt
  Packs/EmailHippo/Integrations/EmailHippo/test_data/get_domain_output.json
  Packs/EmailHippo/Integrations/EmailHippo/test_data/get_email_output.json
  Packs/EmailHippo/Integrations/EmailHippo/test_data/get_quota_output.json
  Packs/EmailHippo/README.md
  Packs/EmailHippo/TestPlaybooks/HippoEmailTest.yml
  Packs/EmailHippo/pack_metadata.json
Labels: docs-approved

#31496 Google Cloud Storage - Update gcs-list-bucket-objects to support prefix and delimiter arguments.
  Packs/GoogleCloudStorage/Integrations/GoogleCloudStorage/GoogleCloudStorage.py
  Packs/GoogleCloudStorage/Integrations/GoogleCloudStorage/GoogleCloudStorage.yml
  Packs/GoogleCloudStorage/Integrations/GoogleCloudStorage/README.md
  Packs/GoogleCloudStorage/ReleaseNotes/1_0_12.md
  Packs/GoogleCloudStorage/pack_metadata.json
Labels: Contribution, docs-approved, Contribution Form Filled, Community, pending-contributor, Xsoar Support Level, External PR

#31531 changed test to correspond to the latest changes on xsoar8
  Packs/CommonScripts/ReleaseNotes/1_13_8.md
  Packs/CommonScripts/Scripts/SearchIncidentsV2/SearchIncidentsV2.py
  Packs/CommonScripts/Scripts/SearchIncidentsV2/SearchIncidentsV2.yml
  Packs/CommonScripts/Scripts/SearchIncidentsV2/SearchIncidentsV2_test.py
  Packs/CommonScripts/pack_metadata.json
Labels: docs-approved, ForceMerge

#31495 Update copy of Tessian Integration
  Packs/Tessian/README.md
  Packs/Tessian/pack_metadata.json
Labels: Contribution, docs-approved, Partner, Contribution Form Filled, pending-contributor, Partner Support Level, External PR, Partner-Approved

#31533 [QRadar_v3-test] Add input for offense_id
  Packs/QRadar/TestPlaybooks/QRadar_v3-test.yml
Labels: docs-approved

#31565 Workaround for pre-commit job
  .github/workflows/pre-commit.yml
Labels: docs-approved

#31479 Joe security detonate file playbook fixes
  Packs/CommonPlaybooks/Playbooks/playbook-Detonate_File_-_Generic.yml
  Packs/CommonPlaybooks/Playbooks/playbook-Detonate_File_-_Generic_README.md
  Packs/CommonPlaybooks/ReleaseNotes/2_4_42.md
  Packs/CommonPlaybooks/pack_metadata.json
  Packs/JoeSecurity/Playbooks/playbook-Detonate_File_-_JoeSecurity_V2.yml
  Packs/JoeSecurity/Playbooks/playbook-Detonate_File_-_JoeSecurity_V2_README.md
  Packs/JoeSecurity/ReleaseNotes/1_1_17.md
  Packs/JoeSecurity/pack_metadata.json
  Packs/SecneurXAnalysis/Playbooks/Detonate_File_-_SecneurX_Analysis.yml
  Packs/SecneurXAnalysis/Playbooks/Detonate_File_-_SecneurX_Analysis_README.md
  Packs/SecneurXAnalysis/ReleaseNotes/1_0_8.md
  Packs/SecneurXAnalysis/pack_metadata.json
Labels: docs-approved

#31487 [Jira-v3] - fix issue with summary argument in jira-create-issue command
  Packs/Jira/Integrations/JiraV3/JiraV3.py
  Packs/Jira/Integrations/JiraV3/JiraV3.yml
  Packs/Jira/Integrations/JiraV3/JiraV3_test.py
  Packs/Jira/Integrations/JiraV3/README.md
  Packs/Jira/ReleaseNotes/3_1_6.md
  Packs/Jira/pack_metadata.json
Labels: docs-approved

#31535 Images as doc_file
  Packs/CortexAttackSurfaceManagement/README.md
  Packs/CortexAttackSurfaceManagement/doc_files/Active_Response_in_Cortex_Xpanse.jpg
  Packs/Devo/Integrations/Devo_v2/README.md
  Packs/Devo/doc_files/devo_video.jpg
  Packs/ExpanseV2/README.md
  Packs/ExpanseV2/doc_files/Expanse_And_Cortex_XSOAR.png
  Packs/PcapAnalysis/README.md
  Packs/PcapAnalysis/doc_files/PCAP_Analysis_in_Cortex_XSOAR.jpg
  Packs/PrismaCloud/Playbooks/playbook-Prisma_Cloud_-_VM_Alert_Prioritization_README.md
  Packs/PrismaCloud/doc_files/Prisma_Cloud_-_VM_Alert_Prioritization_Video.png
  Packs/SOCRadar/README.md
  Packs/SOCRadar/doc_files/SOCRadar_in_Cortex_XSOAR.jpg
Labels: docs-approved

#31421 Fix images special chars when uploading to GCP
  Packs/DevSecOps/.pack-ignore
  Packs/DevSecOps/ReleaseNotes/1_1_8.md
  Packs/DevSecOps/pack_metadata.json
  Packs/GroupIB_ThreatIntelligenceAttribution/.pack-ignore
  Packs/GroupIB_ThreatIntelligenceAttribution/ReleaseNotes/1_4_1.md
  Packs/GroupIB_ThreatIntelligenceAttribution/pack_metadata.json
  Packs/MITRECoA/.pack-ignore
  Packs/MITRECoA/ReleaseNotes/1_0_4.md
  Packs/MITRECoA/pack_metadata.json
  Packs/MalwareInvestigationAndResponse/.pack-ignore
  Packs/MalwareInvestigationAndResponse/ReleaseNotes/2_0_9.md
  Packs/MalwareInvestigationAndResponse/pack_metadata.json
  Packs/OTSecurity/.pack-ignore
  Packs/OTSecurity/ReleaseNotes/1_0_3.md
  Packs/OTSecurity/pack_metadata.json
  Packs/WhisperGateCVE-2021-32648/.pack-ignore
  Packs/WhisperGateCVE-2021-32648/ReleaseNotes/1_0_5.md
  Packs/WhisperGateCVE-2021-32648/pack_metadata.json
  Tests/Marketplace/Tests/pack_readme_handler_test.py
  Tests/Marketplace/pack_readme_handler.py
Labels: docs-approved

#30983 replaced CI_BUILD_ID with CI_JOB_ID
  Tests/Marketplace/upload_packs.py
  Tests/lastest_server_build_scripts/run_tests.sh
  Tests/scripts/instance_test.sh
  Tests/scripts/prepare_content_packs_for_testing.sh
  Tests/test_content.py
Labels: docs-approved

#31568 Adding article to the CTF pack README files
  Packs/CTF02/README.md
  Packs/ctf01/README.md
Labels: docs-approved

#31436 Custom Remedy AR
  Packs/Remedy_AR/.secrets-ignore
  Packs/Remedy_AR/Integrations/RemedyAR/RemedyAR.py
  Packs/Remedy_AR/Integrations/RemedyAR/RemedyAR.yml
  Packs/Remedy_AR/Integrations/RemedyAR/RemedyAR_test.py
  Packs/Remedy_AR/ReleaseNotes/1_0_9.md
  Packs/Remedy_AR/pack_metadata.json
Labels: docs-approved

#31518 New pack: HashiCorp Terraform
  Packs/HashiCorpTerraform/.pack-ignore
  Packs/HashiCorpTerraform/.secrets-ignore
  Packs/HashiCorpTerraform/Author_image.png
  Packs/HashiCorpTerraform/Integrations/HashiCorpTerraform/HashiCorpTerraform.py
  Packs/HashiCorpTerraform/Integrations/HashiCorpTerraform/HashiCorpTerraform.yml
  Packs/HashiCorpTerraform/Integrations/HashiCorpTerraform/HashiCorpTerraform_description.md
  Packs/HashiCorpTerraform/Integrations/HashiCorpTerraform/HashiCorpTerraform_image.png
  Packs/HashiCorpTerraform/Integrations/HashiCorpTerraform/HashiCorpTerraform_test.py
  Packs/HashiCorpTerraform/Integrations/HashiCorpTerraform/README.md
  Packs/HashiCorpTerraform/Integrations/HashiCorpTerraform/command_examples
  Packs/HashiCorpTerraform/Integrations/HashiCorpTerraform/test_data/plan_get_request.json
  Packs/HashiCorpTerraform/Integrations/HashiCorpTerraform/test_data/policies_check_list_request.json
  Packs/HashiCorpTerraform/Integrations/HashiCorpTerraform/test_data/policies_list_request.json
  Packs/HashiCorpTerraform/Integrations/HashiCorpTerraform/test_data/policy_set_list_request.json
  Packs/HashiCorpTerraform/Integrations/HashiCorpTerraform/test_data/run_action_request.json
  Packs/HashiCorpTerraform/Integrations/HashiCorpTerraform/test_data/runs_list_request.json
  Packs/HashiCorpTerraform/README.md
  Packs/HashiCorpTerraform/TestPlaybooks/HasiCoprTerraformTest.yml
  Packs/HashiCorpTerraform/pack_metadata.json
  Tests/conf.json
Labels: docs-approved

#31224 pre-commit: add pytest to template & demisto-sdk v1.25.0 release
  .github/workflows/pre-commit-reuse.yml
  .github/workflows/pre-commit.yml
  .gitignore
  .hooks/pre-commit
  .pre-commit-config_template.yaml
  Tests/configure_and_test_integration_instances.py
  Tests/scripts/dev_envs/pytest/conftest.py
  Tests/scripts/script_runner.py
  Tests/tests_e2e/content/xsoar_saas/test_e2e_xsoar_saas.py
  poetry.lock
  pyproject.toml
Labels: docs-approved

#31574 remove summary report pre-commit
  .github/workflows/pre-commit-reuse.yml
Labels: docs-approved

#31191 Quick Fix for the entrywidgetregionnamexcloud widget
  Packs/CloudIncidentResponse/ReleaseNotes/1_0_9.md
  Packs/CloudIncidentResponse/Scripts/EntryWidgetRegionNameXCLOUD/EntryWidgetRegionNameXCLOUD.py
  Packs/CloudIncidentResponse/Scripts/EntryWidgetRegionNameXCLOUD/EntryWidgetRegionNameXCLOUD.yml
  Packs/CloudIncidentResponse/Scripts/EntryWidgetResourceTypeXCLOUD/EntryWidgetResourceTypeXCLOUD.py
  Packs/CloudIncidentResponse/Scripts/EntryWidgetResourceTypeXCLOUD/EntryWidgetResourceTypeXCLOUD.yml
  Packs/CloudIncidentResponse/Scripts/XCloudIdentitiesWidget/XCloudIdentitiesWidget.py
  Packs/CloudIncidentResponse/Scripts/XCloudIdentitiesWidget/XCloudIdentitiesWidget.yml
  Packs/CloudIncidentResponse/Scripts/XCloudRelatedAlertsWidget/XCloudRelatedAlertsWidget.py
  Packs/CloudIncidentResponse/Scripts/XCloudRelatedAlertsWidget/XCloudRelatedAlertsWidget.yml
  Packs/CloudIncidentResponse/pack_metadata.json
Labels: docs-approved

#31579 [pre-commit] remove __init__folders, fix script_runner and add commit mode
  .hooks/pre-commit
  .pre-commit-config_template.yaml
  Packs/Base/Scripts/CommonServerPython/test_data/__init__.py
  Packs/Mimecast/Integrations/MimecastEventCollector/test_data/__init__.py
  Packs/Netcraft_V2/Integrations/Netcraft/test_data/__init__.py
  Tests/scripts/script_runner.py
Labels: ForceMerge

#31536 fix SetGridField
  Packs/CommonScripts/ReleaseNotes/1_13_10.md
  Packs/CommonScripts/Scripts/SetGridField/SetGridField.py
  Packs/CommonScripts/Scripts/SetGridField/SetGridField_test.py
  Packs/CommonScripts/pack_metadata.json
Labels: docs-approved

#31578 XForceExchange README update
  Packs/XForceExchange/Integrations/XFE_v2/README.md
Labels: docs-approved

#31438 [ExportIncidentsToCSV] - Improve logs
  Packs/CommonScripts/ReleaseNotes/1_13_11.md
  Packs/CommonScripts/Scripts/ExportIncidentsToCSV/ExportIncidentsToCSV.py
  Packs/CommonScripts/Scripts/ExportIncidentsToCSV/ExportIncidentsToCSV_test.py
  Packs/CommonScripts/pack_metadata.json
Labels: docs-approved

#31583 moving the pack to on_prem support only
  Packs/ElasticsearchMonitoring/pack_metadata.json
Labels: docs-approved

#31067 Content Pack Installer docs update
  Packs/CommonScripts/Scripts/ContentPackInstaller/README.md
  Packs/DemistoRESTAPI/Integrations/CoreRESTAPI/CoreRESTAPI.js
  Packs/DemistoRESTAPI/ReleaseNotes/1_3_43.md
  Packs/DemistoRESTAPI/pack_metadata.json
Labels: docs-approved

#31575 add dependency for xsoar-saas mp
  .gitlab/ci/.gitlab-ci.bucket-upload.yml
Labels: docs-approved, ForceMerge

#31298 XSUP-29866
  Packs/EmailCommunication/ReleaseNotes/2_0_18.md
  Packs/EmailCommunication/Scripts/SendEmailReply/SendEmailReply.py
  Packs/EmailCommunication/Scripts/SendEmailReply/SendEmailReply_test.py
  Packs/EmailCommunication/pack_metadata.json
  Packs/MicrosoftExchangeOnPremise/Integrations/EWSv2/EWSv2.py
  Packs/MicrosoftExchangeOnPremise/Integrations/EWSv2/EWSv2.yml
  Packs/MicrosoftExchangeOnPremise/ReleaseNotes/2_0_12.md
  Packs/MicrosoftExchangeOnPremise/pack_metadata.json
Labels: docs-approved, ForceMerge

#31513 [SanePdfReport] - Increase resourceTimeout
  Packs/Base/Scripts/SanePdfReport/SanePdfReport_test.py
Labels: docs-approved

#31526 Oncall validate premium pack missing machine
  .gitlab/ci/.gitlab-ci.bucket-upload.yml
Labels: docs-approved, ForceMerge

#31511 Human-readable output using the JsonToTable script not giving expected results
  Packs/FiltersAndTransformers/ReleaseNotes/1_2_48.md
  Packs/FiltersAndTransformers/Scripts/JsonToTable/JsonToTable.py
  Packs/FiltersAndTransformers/Scripts/JsonToTable/JsonToTable.yml
  Packs/FiltersAndTransformers/Scripts/JsonToTable/JsonToTable_test.py
  Packs/FiltersAndTransformers/Scripts/JsonToTable/README.md
  Packs/FiltersAndTransformers/pack_metadata.json
Labels: docs-approved, ForceMerge

#31577 Adding notes to README
  Packs/MicrosoftGraphGroups/Integrations/MicrosoftGraphGroups/README.md
Labels: docs-approved

#31654 Duo 2.0 (Research) Update
  Packs/DuoAdminApi/ModelingRules/DuoModelingRule_2_0/DuoModelingRule_2_0.xif
  Packs/DuoAdminApi/ReleaseNotes/4_0_15.md
  Packs/DuoAdminApi/pack_metadata.json
Labels: docs-approved

#31659 xsiam-checkpoint-add-mp-keywords-ciac-9214
  Packs/CheckPointDome9/pack_metadata.json
  Packs/CheckPointHEC/pack_metadata.json
  Packs/CheckPointSandBlast/pack_metadata.json
  Packs/CheckpointFirewall/pack_metadata.json
Labels: docs-approved

#31671 fix validate condition
  .gitlab/ci/.gitlab-ci.bucket-upload.yml
Labels: docs-approved

#31576 Add Joesecurity onprem integration
  .gitlab/ci/.gitlab-ci.bucket-upload.yml
Labels: Contribution, Contribution Form Filled, Community, Xsoar Support Level, External PR, Security Review

#30189 Content - e2e tests in SDK Nightly
  .gitlab/ci/.gitlab-ci.global.yml
  .gitlab/ci/.gitlab-ci.sdk-nightly.yml
  Tests/scripts/run_tests.sh
  Tests/scripts/test_modeling_rules.sh
Labels: docs-approved

#31648 [VirusTotal] Fix missing suspicious value for running instances
  Packs/VirusTotal/Integrations/VirusTotalV3/VirusTotalV3.py
  Packs/VirusTotal/ReleaseNotes/2_6_13.md
  Packs/VirusTotal/pack_metadata.json
Labels: Contribution, Partner, Contribution Form Filled, Partner Support Level, External PR, Partner-Approved, TIM Review

#31480 Siemens SiPass new pack
  Packs/Siemens_SiPass/.pack-ignore
  Packs/Siemens_SiPass/.secrets-ignore
  Packs/Siemens_SiPass/ModelingRules/Siemens_SiPass/Siemens_SiPass.xif
  Packs/Siemens_SiPass/ModelingRules/Siemens_SiPass/Siemens_SiPass.yml
  Packs/Siemens_SiPass/ModelingRules/Siemens_SiPass/Siemens_SiPass_schema.json
  Packs/Siemens_SiPass/ParsingRules/Siemens_SiPass/Siemens_SiPass.xif
  Packs/Siemens_SiPass/ParsingRules/Siemens_SiPass/Siemens_SiPass.yml
  Packs/Siemens_SiPass/README.md
  Packs/Siemens_SiPass/pack_metadata.json
Labels: docs-approved

#31682 Test branch before sync
  Packs/Siemens_SiPass/.pack-ignore
  Packs/Siemens_SiPass/.secrets-ignore
  Packs/Siemens_SiPass/ModelingRules/Siemens_SiPass/Siemens_SiPass.xif
  Packs/Siemens_SiPass/ModelingRules/Siemens_SiPass/Siemens_SiPass.yml
  Packs/Siemens_SiPass/ModelingRules/Siemens_SiPass/Siemens_SiPass_schema.json
  Packs/Siemens_SiPass/ParsingRules/Siemens_SiPass/Siemens_SiPass.xif
  Packs/Siemens_SiPass/ParsingRules/Siemens_SiPass/Siemens_SiPass.yml
  Packs/Siemens_SiPass/README.md
  Packs/Siemens_SiPass/pack_metadata.json
Labels: Contribution, Xsoar Support Level, External PR, Security Review

#31356 [Okta v2] Add OAuth 2.0 Authentication
  Packs/ApiModules/Scripts/OktaApiModule/OktaApiModule.py
  Packs/ApiModules/Scripts/OktaApiModule/OktaApiModule.yml
  Packs/ApiModules/Scripts/OktaApiModule/OktaApiModule_test.py
  Packs/ApiModules/Scripts/OktaApiModule/test_data/raw_api_responses/roles_already_assigned_error.json
  Packs/ApiModules/Scripts/OktaApiModule/test_data/raw_api_responses/token_generation.json
  Packs/Okta/Integrations/Okta_v2/Okta_v2.py
  Packs/Okta/Integrations/Okta_v2/Okta_v2.yml
  Packs/Okta/Integrations/Okta_v2/Okta_v2_description.md
  Packs/Okta/Integrations/Okta_v2/Okta_v2_test.py
  Packs/Okta/Integrations/Okta_v2/README.md
  Packs/Okta/ReleaseNotes/3_2_6.md
  Packs/Okta/pack_metadata.json
  Tests/secrets_white_list.json
Labels: docs-approved

#31595 SentinelOneV2
  Packs/SentinelOne/Integrations/SentinelOne-V2/SentinelOne-V2.py
  Packs/SentinelOne/ReleaseNotes/3_2_15.md
  Packs/SentinelOne/pack_metadata.json
Labels: Contribution, Partner, Contribution Form Filled, Partner Support Level, External PR, Partner-Approved

#31441 Identity Analytics Alert Handling Playbook for XSIAM
  Packs/Azure-Enrichment-Remediation/Playbooks/playbook-Azure_-_User_Investigation.yml
  Packs/Azure-Enrichment-Remediation/Playbooks/playbook-Azure_-_User_Investigation_README.md
  Packs/Azure-Enrichment-Remediation/ReleaseNotes/1_1_9.md
  Packs/Azure-Enrichment-Remediation/doc_files/Azure_-_User_Investigation.png
  Packs/Azure-Enrichment-Remediation/pack_metadata.json
  Packs/CommonScripts/.pack-ignore
  Packs/CommonScripts/ReleaseNotes/1_13_12.md
  Packs/CommonScripts/Scripts/VerdictResult/README.md
  Packs/CommonScripts/Scripts/VerdictResult/VerdictResult.py
  Packs/CommonScripts/Scripts/VerdictResult/VerdictResult.yml
  Packs/CommonScripts/Scripts/VerdictResult/VerdictResult_test.py
  Packs/CommonScripts/pack_metadata.json
  Packs/Core/LayoutRules/Identity_Analytics_Alerts.json
  Packs/Core/Layouts/layoutscontainer-Identity_Analytics_Alerts.json
  Packs/Core/Playbooks/playbook-Identity_Analytics_-_Alert_Handling.yml
  Packs/Core/Playbooks/playbook-Identity_Analytics_-_Alert_Handling_README.md
  Packs/Core/ReleaseNotes/3_0_4.md
  Packs/Core/Triggers/Trigger_-_Identity_Analytics_Alerts.json
  Packs/Core/doc_files/Identity_Analytics_-_Alert_Handling.png
  Packs/Core/pack_metadata.json
  Packs/CoreAlertFields/.pack-ignore
  Packs/CoreAlertFields/IncidentFields/incidentfield-Alert_Search_Results.json
  Packs/CoreAlertFields/ReleaseNotes/1_0_30.md
  Packs/CoreAlertFields/pack_metadata.json
Labels: docs-approved

#31581 oncall- increase the install_packs timeout to 15 min
  Tests/Marketplace/search_and_install_packs.py
Labels: docs-approved

#31532 removed not runned task from message
  Tests/scripts/gitlab_slack_notifier.py
Labels: docs-approved

#31661 Extract indicators from file enhancement
  Packs/CommonPlaybooks/Playbooks/playbook-Extract_Indicators_From_File_-_Generic_v2_4_5.yml
  Packs/CommonPlaybooks/Playbooks/playbook-Extract_Indicators_From_File_-_Generic_v2_4_5_README.md
  Packs/CommonPlaybooks/ReleaseNotes/2_4_44.md
  Packs/CommonPlaybooks/doc_files/Extract_Indicators_From_File_-_Generic_v2.png
  Packs/CommonPlaybooks/pack_metadata.json
Labels: docs-approved

#31316 update EDL_description.md
  Packs/EDL/Integrations/EDL/EDL.yml
  Packs/EDL/Integrations/EDL/EDL_description.md
  Packs/EDL/ReleaseNotes/3_2_16.md
  Packs/EDL/pack_metadata.json
Labels: docs-approved

#31592 [pre-commit] fix script runner
  Tests/scripts/script_runner.py
Labels: docs-approved

#30846 Updated file variable revert test variable
  .gitlab/ci/.gitlab-ci.bucket-upload.yml
  .gitlab/ci/.gitlab-ci.global.yml
  .gitlab/ci/.gitlab-ci.on-push.yml
  Tests/Marketplace/install_packs.sh
  Tests/scripts/install_content_and_test_integrations.sh
  Tests/scripts/reinstall_packs_on_cloud_instances.sh
  Tests/scripts/run_e2e_tests.sh
  Tests/scripts/run_tests.sh
  Tests/scripts/test_modeling_rules.sh
  Tests/scripts/uninstall_packs_and_reset_bucket_cloud.sh
Labels: docs-approved

#31395 [Whois] test_socks_proxy UT failed
  Packs/Whois/Integrations/Whois/Whois_test.py
Labels: docs-approved

#31658 Delete test data files from repo
  Packs/AWS-SecurityHub/ModelingRules/AWSSecurityHubModelingRules/AWSSecurityHubModelingRules_testdata.json
  Packs/AlibabaActionTrail/ModelingRules/AlibabaModelingRules_1_3/AlibabaModelingRules_1_3_testdata.json
  Packs/ManageEngine-ADAudit/ModelingRules/ManageEngine-ADAudit_1_3/ManageEngine-ADAudit_1_3_testdata.json
  Packs/MicrosoftAdvancedThreatAnalytics/ModelingRules/MicrosoftAdvancedThreatAnalytics/MicrosoftAdvancedThreatAnalytics_testdata.json
  Packs/NetBox/ModelingRules/NetBoxModelingRules_1_3/NetBoxModelingRules_1_3_testdata.json
  Packs/RecordedFuture/ModelingRules/RecordedFutureModelingRules_1_4/RecordedFutureModelingRules_1_4_testdata.json
  Packs/RunZero/ModelingRules/RunZeroModelingRules/RunZeroModelingRules_testdata.json
  Packs/Zoom/ModelingRules/Zoom/Zoom_testdata.json
Labels: docs-approved, ForceMerge

#31690 NetskopeAPIv2 `alert_query` argument
  Packs/Netskope/Integrations/NetskopeAPIv2/NetskopeAPIv2.py
  Packs/Netskope/Integrations/NetskopeAPIv2/NetskopeAPIv2.yml
  Packs/Netskope/Integrations/NetskopeAPIv2/NetskopeAPIv2_test.py
  Packs/Netskope/ReleaseNotes/3_3_2.md
  Packs/Netskope/pack_metadata.json
Labels: docs-approved

#31683 ParseEmailFiles: Update docker
  Packs/CommonScripts/ReleaseNotes/1_13_13.md
  Packs/CommonScripts/Scripts/ParseEmailFilesV2/ParseEmailFilesV2.yml
  Packs/CommonScripts/pack_metadata.json
Labels: docs-approved

#31118 Adding Cloud Alerts Layout
  Packs/CloudIncidentResponse/LayoutRules/layoutrule-Cloud_Alerts.json
  Packs/CloudIncidentResponse/Layouts/layoutscontainer-Cloud_Alerts.json
  Packs/CloudIncidentResponse/ReleaseNotes/1_0_10.md
  Packs/CloudIncidentResponse/Scripts/XCloudAdditionalAlertInformationWidget/README.md
  Packs/CloudIncidentResponse/Scripts/XCloudAdditionalAlertInformationWidget/XCloudAdditionalAlertInformationWidget.py
  Packs/CloudIncidentResponse/Scripts/XCloudAdditionalAlertInformationWidget/XCloudAdditionalAlertInformationWidget.yml
  Packs/CloudIncidentResponse/Scripts/XCloudAdditionalAlertInformationWidget/XCloudAdditionalAlertInformationWidget_test.py
  Packs/CloudIncidentResponse/pack_metadata.json
Labels: docs-approved

#31672 YR/-Test-slack-messages/Take1/CIAC-9065 -"replace"
  Tests/scripts/common.py
  Tests/scripts/gitlab_slack_notifier.py
  Tests/scripts/infrastructure_tests/common_test.py
Labels: docs-approved
