Repository demisto/content, pull requests merged in 2023-09, with the labels that each got.

#29377 [CortexAttackSurfaceManagement] Remove `TestForPlaybooks` folder
  Packs/CortexAttackSurfaceManagement/Integrations/CortexAttackSurfaceManagement/test_data/TestsForPlaybooks/CortexASMAWSEnrichment_test.py
  Packs/CortexAttackSurfaceManagement/Integrations/CortexAttackSurfaceManagement/test_data/TestsForPlaybooks/CortexASMAzureEnrichment_test.py
  Packs/CortexAttackSurfaceManagement/Integrations/CortexAttackSurfaceManagement/test_data/TestsForPlaybooks/CortexASMGCPEnrichment_test.py
  Packs/CortexAttackSurfaceManagement/Integrations/CortexAttackSurfaceManagement/test_data/TestsForPlaybooks/CortexASMPrismaCloudEnrichment_test.py
  Packs/CortexAttackSurfaceManagement/Integrations/CortexAttackSurfaceManagement/test_data/TestsForPlaybooks/CortexASMQualysEnrichment_test.py
  Packs/CortexAttackSurfaceManagement/Integrations/CortexAttackSurfaceManagement/test_data/TestsForPlaybooks/CortexASMRapid7Enrichment_test.py
  Packs/CortexAttackSurfaceManagement/Integrations/CortexAttackSurfaceManagement/test_data/TestsForPlaybooks/CortexASMSNOWCMDBEnrichment_test.py
  Packs/CortexAttackSurfaceManagement/Integrations/CortexAttackSurfaceManagement/test_data/TestsForPlaybooks/CortexASMTenableEnrichment_test.py
  Packs/CortexAttackSurfaceManagement/Integrations/CortexAttackSurfaceManagement/test_data/TestsForPlaybooks/utils/helper.py
Labels: ForceMerge

#29365 sdk pylint error checking script was broken
  Tests/scripts/sdk_pylint_check.sh
Labels: docs-approved

#29085 Test modeling rules junit
  .gitlab/ci/.gitlab-ci.on-push.yml
  Tests/scripts/convert_test_result_to_jira_issues.py
  Tests/scripts/gitlab_slack_notifier.py
  Tests/scripts/install_content_and_test_integrations.sh
  Tests/scripts/print_cloud_machine_details.sh
  Tests/scripts/test_modeling_rules.sh
  poetry.lock
  pyproject.toml
Labels: docs-approved

#28950 Deprecated playbooks replacements
  Packs/CommonPlaybooks/Playbooks/playbook-Detonate_File_-_Generic.yml
  Packs/CommonPlaybooks/Playbooks/playbook-Detonate_File_-_Generic_README.md
  Packs/CommonPlaybooks/Playbooks/playbook-Detonate_and_Analyze_File_-_Generic.yml
  Packs/CommonPlaybooks/Playbooks/playbook-Detonate_and_Analyze_File_-_Generic_README.md
  Packs/CommonPlaybooks/ReleaseNotes/2_3_99.md
  Packs/CommonPlaybooks/doc_files/Detonate_File_-_Generic.png
  Packs/CommonPlaybooks/doc_files/Detonate_and_Analyze_File_-_Generic.png
  Packs/CommonPlaybooks/pack_metadata.json
  Packs/DefaultPlaybook/Playbooks/Default_8_2.yml
  Packs/DefaultPlaybook/Playbooks/Default_8_2_README.md
  Packs/DefaultPlaybook/ReleaseNotes/2_0_4.md
  Packs/DefaultPlaybook/doc_files/Default_8_2.png
  Packs/DefaultPlaybook/pack_metadata.json
  Packs/PortScan/.pack-ignore
  Packs/PortScan/Playbooks/Port_Scan_-_Internal_Source_6_0.yml
  Packs/PortScan/Playbooks/Port_Scan_-_Internal_Source_6_0_README.md
  Packs/PortScan/ReleaseNotes/1_1_12.md
  Packs/PortScan/doc_files/Port_Scan_-_Internal_Source.png
  Packs/PortScan/pack_metadata.json
  Packs/Rapid7_Nexpose/Playbooks/playbook-Vulnerability_Handling_-_Nexpose.yml
  Packs/Rapid7_Nexpose/Playbooks/playbook-Vulnerability_Handling_-_Nexpose_README.md
  Packs/Rapid7_Nexpose/ReleaseNotes/1_2_16.md
  Packs/Rapid7_Nexpose/doc_files/Vulnerability_Handling_-_Nexpose.png
  Packs/Rapid7_Nexpose/pack_metadata.json
Labels: docs-approved

#29349 Okta user investigation - Enhancement
  Packs/Okta/Playbooks/playbook-Okta_-_User_Investigation.yml
  Packs/Okta/Playbooks/playbook-Okta_-_User_Investigation_README.md
  Packs/Okta/ReleaseNotes/3_1_29.md
  Packs/Okta/doc_files/Okta_-_User_Investigation.png
  Packs/Okta/pack_metadata.json
Labels: docs-approved

#29336 git clone check branch exists and support slashes
  .gitlab/ci/.gitlab-ci.bucket-upload.yml
  .gitlab/ci/.gitlab-ci.global.yml
  .gitlab/ci/.gitlab-ci.on-push.yml
  Tests/scripts/check_if_branch_exist.sh
  Tests/scripts/download_conf_repos.sh
Labels: docs-approved

#29379 The hive severity fix
  Packs/TheHiveProject/Integrations/TheHiveProject/TheHiveProject.py
  Packs/TheHiveProject/Integrations/TheHiveProject/TheHiveProject.yml
  Packs/TheHiveProject/ReleaseNotes/1_1_18.md
  Packs/TheHiveProject/pack_metadata.json
Labels: docs-approved

#29198 fixed limit issue, fixed sample issue
  Packs/ThreatGrid/Integrations/ThreatGridv2/ThreatGridv2.py
  Packs/ThreatGrid/Integrations/ThreatGridv2/ThreatGridv2.yml
  Packs/ThreatGrid/ReleaseNotes/2_0_14.md
  Packs/ThreatGrid/pack_metadata.json
Labels: docs-approved

#29374 Fix for 'NGFW Scan' playbook
  Packs/Core/.pack-ignore
  Packs/Core/Playbooks/playbook-NGFW_Scan.yml
  Packs/Core/ReleaseNotes/2_0_12.md
  Packs/Core/pack_metadata.json
Labels: docs-approved

#29405 [pre-commit check-yaml] Align the entire repo with check-yaml
  Tests/setup/playbook-invalid-id-test.yml
  Tests/setup/playbook-valid-id-test.yml
Labels: docs-approved

#28800 Pack upload support
  .gitlab/ci/.gitlab-ci.bucket-upload.yml
  Tests/Marketplace/marketplace_services.py
  Tests/Marketplace/upload_packs.py
  Tests/scripts/prepare_content_packs_for_testing.sh
  Tests/scripts/validate.sh
Labels: docs-approved

#28970 ServiceNow add default type to note
  Packs/ServiceNow/Integrations/ServiceNowv2/ServiceNowv2.py
  Packs/ServiceNow/Integrations/ServiceNowv2/ServiceNowv2.yml
  Packs/ServiceNow/ReleaseNotes/2_5_38.md
  Packs/ServiceNow/TestPlaybooks/ServiceNow_Fetch_Incidents_Test.yml
  Packs/ServiceNow/pack_metadata.json
  Tests/conf.json
Labels: docs-approved

#29415 fix bash condition
  Tests/scripts/test_modeling_rules.sh
Labels: docs-approved, ForceMerge

#29416 fix test modeling rule
  Tests/scripts/test_modeling_rules.sh
Labels: docs-approved

#29258 added the code and some UT
  Packs/rasterize/Integrations/rasterize/rasterize.py
  Packs/rasterize/Integrations/rasterize/rasterize.yml
  Packs/rasterize/Integrations/rasterize/rasterize_test.py
  Packs/rasterize/ReleaseNotes/1_2_25.md
  Packs/rasterize/pack_metadata.json
Labels: docs-approved, ForceMerge

#29413 Added fields to schema file
  Packs/IronscalesEventCollector/ModelingRules/IronscalesModelingRules/IronscalesModelingRules_schema.json
  Packs/IronscalesEventCollector/ReleaseNotes/1_0_7.md
  Packs/IronscalesEventCollector/pack_metadata.json
Labels: docs-approved

#29408 [Recorded Future Identity] Deleting an unused import
  Packs/IdentityRecordedFuture/Integrations/IdentityRecordedFuture/IdentityRecordedFuture.py
  Packs/IdentityRecordedFuture/Integrations/IdentityRecordedFuture/IdentityRecordedFuture.yml
  Packs/IdentityRecordedFuture/ReleaseNotes/1_1_4.md
  Packs/IdentityRecordedFuture/pack_metadata.json
Labels: docs-approved

#29409 [ServiceNow v2] Deleting an unused import
  Packs/ServiceNow/Integrations/ServiceNowv2/test_data/response_constants.py
Labels: docs-approved

#29407 1.20.0
  .gitlab/ci/.gitlab-ci.bucket-upload.yml
  .gitlab/ci/.gitlab-ci.on-push.yml
  .gitlab/ci/.gitlab-ci.yml
  Tests/Marketplace/Tests/marketplace_services_test.py
  Tests/Marketplace/Tests/pack_readme_handler_test.py
  Tests/Marketplace/Tests/test_data/markdown_images.json
  Tests/Marketplace/Tests/test_data/readme_images.json
  Tests/Marketplace/copy_and_upload_packs.py
  Tests/Marketplace/marketplace_constants.py
  Tests/Marketplace/marketplace_services.py
  Tests/Marketplace/pack_readme_handler.py
  Tests/Marketplace/upload_packs.py
  Tests/scripts/collect_tests/collect_tests.py
  Tests/scripts/prepare_content_packs_for_testing.sh
  Utils/gitlab_triggers/trigger_upload_flow_build.sh
  Utils/trigger_test_upload_flow.sh
  poetry.lock
  pyproject.toml
Labels: docs-approved

#29422 [Release Notes Generator] Change log info to debug
  Utils/release_notes_generator.py
Labels: docs-approved

#29406 XSUP-27732 Unable to query for emails
  Packs/Mimecast/Integrations/MimecastV2/MimecastV2.py
  Packs/Mimecast/Integrations/MimecastV2/MimecastV2.yml
  Packs/Mimecast/Integrations/MimecastV2/MimecastV2_test.py
  Packs/Mimecast/ReleaseNotes/2_2_1.md
  Packs/Mimecast/pack_metadata.json
Labels: docs-approved

#29424 [AbnormalSecurity] Delete invalid file
  Packs/AbnormalSecurity/secrets_white_list.json
Labels: ForceMerge

#29137 Ciac 7986
  Packs/CommonScripts/ReleaseNotes/1_12_20.md
  Packs/CommonScripts/Scripts/SetGridField/README.md
  Packs/CommonScripts/Scripts/SetGridField/SetGridField.py
  Packs/CommonScripts/Scripts/SetGridField/SetGridField.yml
  Packs/CommonScripts/Scripts/SetGridField/SetGridField_test.py
  Packs/CommonScripts/Scripts/SetGridField/doc_files/nested_dict_grid.png
  Packs/CommonScripts/Scripts/SetGridField/test_data/context_entry_dict.json
  Packs/CommonScripts/Scripts/SetGridField/test_data/context_entry_dict_with_elements.json
  Packs/CommonScripts/Scripts/SetGridField/test_data/context_entry_list.json
  Packs/CommonScripts/Scripts/SetGridField/test_data/context_entry_list_missing_key.json
  Packs/CommonScripts/Scripts/SetGridField/test_data/context_entry_list_of_dicts.json
  Packs/CommonScripts/Scripts/SetGridField/test_data/context_entry_list_of_dicts_complex.json
  Packs/CommonScripts/Scripts/SetGridField/test_data/context_entry_list_of_dicts_non_sorted.json
  Packs/CommonScripts/Scripts/SetGridField/test_data/context_entry_list_of_dicts_non_sorted_multi.json
  Packs/CommonScripts/Scripts/SetGridField/test_data/context_entry_list_of_values.json
  Packs/CommonScripts/Scripts/SetGridField/test_data/context_single_dict_with_keys.json
  Packs/CommonScripts/Scripts/SetGridField/test_data/expected_dict_grid.json
  Packs/CommonScripts/Scripts/SetGridField/test_data/expected_dict_with_elements_grid.json
  Packs/CommonScripts/Scripts/SetGridField/test_data/expected_entry_list_of_dicts_sorted.json
  Packs/CommonScripts/Scripts/SetGridField/test_data/expected_entry_list_of_dicts_sorted_multi.json
  Packs/CommonScripts/Scripts/SetGridField/test_data/expected_list_grid.json
  Packs/CommonScripts/Scripts/SetGridField/test_data/expected_list_grid_none_value.json
  Packs/CommonScripts/Scripts/SetGridField/test_data/expected_list_of_dicts_complex.json
  Packs/CommonScripts/Scripts/SetGridField/test_data/expected_list_of_dicts_grid.json
  Packs/CommonScripts/Scripts/SetGridField/test_data/expected_list_of_values_grid.json
  Packs/CommonScripts/Scripts/SetGridField/test_data/expected_single_dict_with_keys_grid.json
  Packs/CommonScripts/pack_metadata.json
Labels: docs-approved

#29428 Fix generic-sql-mssql-encrypted-connection TPB
  Packs/GenericSQL/TestPlaybooks/generic-sql-mssql-encrypted-connection.yml
  Tests/conf.json
Labels: docs-approved

#29423 [Azure Active Directory Groups] fixed bug when calling command
  Packs/MicrosoftGraphGroups/Integrations/MicrosoftGraphGroups/MicrosoftGraphGroups.py
  Packs/MicrosoftGraphGroups/Integrations/MicrosoftGraphGroups/MicrosoftGraphGroups.yml
  Packs/MicrosoftGraphGroups/ReleaseNotes/1_1_31.md
  Packs/MicrosoftGraphGroups/pack_metadata.json
Labels: docs-approved

#28622 [Microsoft] support auth-reset command
  Packs/AzureSecurityCenter/Integrations/MicrosoftDefenderForCloudEventCollector/MicrosoftDefenderForCloudEventCollector.py
  Packs/AzureSecurityCenter/Integrations/MicrosoftDefenderForCloudEventCollector/MicrosoftDefenderForCloudEventCollector.yml
  Packs/AzureSecurityCenter/Integrations/MicrosoftDefenderForCloudEventCollector/README.md
  Packs/AzureSecurityCenter/ReleaseNotes/2_0_12.md
  Packs/AzureSecurityCenter/pack_metadata.json
  Packs/Microsoft365Defender/Integrations/Microsoft365Defender/Microsoft365Defender.py
  Packs/Microsoft365Defender/Integrations/Microsoft365Defender/Microsoft365Defender.yml
  Packs/Microsoft365Defender/ReleaseNotes/4_5_16.md
  Packs/Microsoft365Defender/pack_metadata.json
  Packs/MicrosoftCloudAppSecurity/Integrations/MicrosoftDefenderEventCollector/MicrosoftDefenderEventCollector.py
  Packs/MicrosoftCloudAppSecurity/Integrations/MicrosoftDefenderEventCollector/MicrosoftDefenderEventCollector.yml
  Packs/MicrosoftCloudAppSecurity/Integrations/MicrosoftDefenderEventCollector/README.md
  Packs/MicrosoftCloudAppSecurity/ReleaseNotes/2_1_42.md
  Packs/MicrosoftCloudAppSecurity/pack_metadata.json
  Packs/MicrosoftDefenderAdvancedThreatProtection/Integrations/Microsoft365DefenderEventCollector/Microsoft365DefenderEventCollector.py
  Packs/MicrosoftDefenderAdvancedThreatProtection/Integrations/Microsoft365DefenderEventCollector/Microsoft365DefenderEventCollector.yml
  Packs/MicrosoftDefenderAdvancedThreatProtection/Integrations/Microsoft365DefenderEventCollector/README.md
  Packs/MicrosoftDefenderAdvancedThreatProtection/ReleaseNotes/1_16_8.md
  Packs/MicrosoftDefenderAdvancedThreatProtection/pack_metadata.json
  Packs/MicrosoftExchangeOnline/Integrations/EWSO365/EWSO365.py
  Packs/MicrosoftExchangeOnline/Integrations/EWSO365/EWSO365.yml
  Packs/MicrosoftExchangeOnline/Integrations/EWSO365/README.md
  Packs/MicrosoftExchangeOnline/ReleaseNotes/1_2_24.md
  Packs/MicrosoftExchangeOnline/pack_metadata.json
Labels: docs-approved

#29431 Fix GeneratePassword-Test TPB
  Packs/CommonScripts/TestPlaybooks/playbook-GeneratePassword-Test.yml
Labels: docs-approved

#29441 fix test modeling rule
  Tests/scripts/test_modeling_rules.sh
Labels: docs-approved, ForceMerge

#29378 Implement the unit test case for Get_access_token
  Packs/DelineaDSV/Integrations/DelineaDSV/DelineaDSV_test.py
Labels: Contribution, Partner, ready-for-instance-test, Contribution Form Filled, Partner Support Level, External PR, Partner-Approved

#28618 SplunkPy mirror out fails if userMapping is enabled and new user is not found
  Packs/SplunkPy/Integrations/SplunkPy/SplunkPy.py
  Packs/SplunkPy/Integrations/SplunkPy/SplunkPy.yml
  Packs/SplunkPy/ReleaseNotes/3_1_5.md
  Packs/SplunkPy/pack_metadata.json
Labels: docs-approved

#29421 ES add format to the query string
  Packs/Elasticsearch/Integrations/Elasticsearch_v2/Elasticsearch_v2.py
  Packs/Elasticsearch/Integrations/Elasticsearch_v2/Elasticsearch_v2.yml
  Packs/Elasticsearch/Integrations/Elasticsearch_v2/Elasticsearch_v2_test.py
  Packs/Elasticsearch/Integrations/Elasticsearch_v2/README.md
  Packs/Elasticsearch/ReleaseNotes/1_3_16.md
  Packs/Elasticsearch/pack_metadata.json
Labels: docs-approved

#28944 added autocommit to execution sql queries
  Packs/GenericSQL/Integrations/GenericSQL/GenericSQL.py
  Packs/GenericSQL/Integrations/GenericSQL/GenericSQL_test.py
  Packs/GenericSQL/ReleaseNotes/1_0_24.md
  Packs/GenericSQL/pack_metadata.json
  Tests/conf.json
Labels: docs-approved, ForceMerge

#29327 Xsup 27483/Report Object References
  Packs/ApiModules/Scripts/TAXII2ApiModule/TAXII2ApiModule.py
  Packs/ApiModules/Scripts/TAXII2ApiModule/test_data/parsed_stix_objects.json
  Packs/CommonTypes/IndicatorFields/indicatorfield-report_objects_references.json
  Packs/CommonTypes/ReleaseNotes/3_3_84.md
  Packs/CommonTypes/pack_metadata.json
  Packs/FeedDHS/ReleaseNotes/2_0_20.md
  Packs/FeedDHS/pack_metadata.json
  Packs/FeedMitreAttackv2/ReleaseNotes/1_1_22.md
  Packs/FeedMitreAttackv2/pack_metadata.json
  Packs/FeedTAXII/ReleaseNotes/1_1_33.md
  Packs/FeedTAXII/pack_metadata.json
Labels: docs-approved

#29362 Cisco ISE Enrichment
  Packs/cisco-ise/ModelingRules/cisco-ise/cisco-ise.xif
  Packs/cisco-ise/ModelingRules/cisco-ise/cisco-ise.yml
  Packs/cisco-ise/ReleaseNotes/1_0_17.md
  Packs/cisco-ise/pack_metadata.json
Labels: docs-approved

#29449 revert changes regardin xsoar_ng_server_ga
  .gitlab/ci/.gitlab-ci.on-push.yml
Labels: docs-approved

#28651 Parsing rules fix filter 10
  Packs/MicrosoftExchangeServer/ParsingRules/MicrosoftExchangeServerParsingRules/MicrosoftExchangeServerParsingRules.xif
  Packs/MicrosoftExchangeServer/ReleaseNotes/1_0_6.md
  Packs/MicrosoftExchangeServer/pack_metadata.json
  Packs/PrismaSaasSecurity/ParsingRules/PrismaSaasSecurity/PrismaSaasSecurity.xif
  Packs/PrismaSaasSecurity/ReleaseNotes/2_0_26.md
  Packs/PrismaSaasSecurity/pack_metadata.json
Labels: docs-approved

#29429 Onelogin iam schema fix
  Packs/OneLogin/ModelingRules/OneLoginModelingRules_1_3/OneLoginModelingRules_1_3.xif
  Packs/OneLogin/ReleaseNotes/1_0_10.md
  Packs/OneLogin/pack_metadata.json
Labels: docs-approved

#29301 Return Results human readable bug
  Packs/Base/ReleaseNotes/1_32_31.md
  Packs/Base/Scripts/CommonServerPython/CommonServerPython.py
  Packs/Base/Scripts/CommonServerPython/CommonServerPython_test.py
  Packs/Base/pack_metadata.json
Labels: docs-approved, ForceMerge

#29197 XSUP-27024/exabeam
  Packs/Exabeam/Integrations/Exabeam/Exabeam.py
  Packs/Exabeam/Integrations/Exabeam/Exabeam.yml
  Packs/Exabeam/Integrations/Exabeam/Exabeam_test.py
  Packs/Exabeam/Integrations/Exabeam/README.md
  Packs/Exabeam/Integrations/Exabeam/test_data/response_incidents.py
  Packs/Exabeam/ReleaseNotes/2_2_7.md
  Packs/Exabeam/pack_metadata.json
Labels: docs-approved

#29359 Dlp description
  Packs/Palo_Alto_Networks_Enterprise_DLP/Layouts/layoutscontainer-Data_Loss_Prevention_6_8.json
  Packs/Palo_Alto_Networks_Enterprise_DLP/Playbooks/DLP_Incident_Feedback_Loop_6_8.yml
  Packs/Palo_Alto_Networks_Enterprise_DLP/Playbooks/DLP_Incident_Feedback_Loop_6_8_README.md
  Packs/Palo_Alto_Networks_Enterprise_DLP/ReleaseNotes/2_0_4.md
  Packs/Palo_Alto_Networks_Enterprise_DLP/pack_metadata.json
Labels: docs-approved

#29288 Add basic authentication jira v3
  Packs/Jira/Integrations/JiraV3/JiraV3.py
  Packs/Jira/Integrations/JiraV3/JiraV3.yml
  Packs/Jira/Integrations/JiraV3/JiraV3_description.md
  Packs/Jira/Integrations/JiraV3/JiraV3_test.py
  Packs/Jira/Integrations/JiraV3/README.md
  Packs/Jira/ReleaseNotes/3_1_0.md
  Packs/Jira/TestPlaybooks/playbook_JiraV3_Test.yml
  Packs/Jira/pack_metadata.json
  Tests/conf.json
Labels: docs-approved

#29451 Test playbook xsiam fix
  Packs/CommonPlaybooks/Playbooks/playbook-Containment_Plan_-_Clear_User_Sessions.yml
  Packs/CommonPlaybooks/ReleaseNotes/2_4_0.md
  Packs/CommonPlaybooks/TestPlaybooks/playbook-Containment_Plan-Test.yml
  Packs/CommonPlaybooks/TestPlaybooks/playbook-Eradication_plan_-_Test.yml
  Packs/CommonPlaybooks/pack_metadata.json
Labels: docs-approved

#29339 Xpanse api updates
  Packs/CortexXpanse/Classifiers/classifier-Xpanse_-_Incoming_Mapper.json
  Packs/CortexXpanse/IncidentFields/incidentfield-Xpanse_Tags.json
  Packs/CortexXpanse/IncidentFields/incidentfields-Xpanse_Provider.json
  Packs/CortexXpanse/Integrations/CortexXpanse/CortexXpanse.yml
  Packs/CortexXpanse/ReleaseNotes/1_0_10.md
  Packs/CortexXpanse/pack_metadata.json
Labels: Contribution, ready-for-instance-test, Contribution Form Filled, Community, Xsoar Support Level, External PR, Security Review

#29432 Fixed schema for teamviewer
  Packs/TeamViewer/ModelingRules/TeamViewer/TeamViewer_schema.json
  Packs/TeamViewer/ReleaseNotes/1_0_7.md
  Packs/TeamViewer/pack_metadata.json
Labels: docs-approved

#29435 Cs detections empty list issue
  Packs/CrowdStrikeFalcon/Integrations/CrowdStrikeFalcon/CrowdStrikeFalcon.py
  Packs/CrowdStrikeFalcon/Integrations/CrowdStrikeFalcon/CrowdStrikeFalcon.yml
  Packs/CrowdStrikeFalcon/Integrations/CrowdStrikeFalcon/CrowdStrikeFalcon_test.py
  Packs/CrowdStrikeFalcon/ReleaseNotes/1_11_7.md
  Packs/CrowdStrikeFalcon/TestPlaybooks/playbook-CrowdStrikeFalcon-Test.yml
  Packs/CrowdStrikeFalcon/pack_metadata.json
Labels: docs-approved

#29335 AWS-WAF Adding Modeling Rules
  Packs/AWS_WAF/ModelingRules/AWS_WAF/AWS_WAF.xif
  Packs/AWS_WAF/ModelingRules/AWS_WAF/AWS_WAF.yml
  Packs/AWS_WAF/ModelingRules/AWS_WAF/AWS_WAF_schema.json
  Packs/AWS_WAF/ParsingRules/AWS_WAF/AWS_WAF.xif
  Packs/AWS_WAF/ParsingRules/AWS_WAF/AWS_WAF.yml
  Packs/AWS_WAF/README.md
  Packs/AWS_WAF/ReleaseNotes/1_0_2.md
  Packs/AWS_WAF/pack_metadata.json
Labels: docs-approved

#29414 Removing unsupported xdr fields from mapper
  Packs/CortexXDR/Classifiers/classifier-mapper-incoming-PaloAltoNetworks_CortexXDR.json
  Packs/CortexXDR/ReleaseNotes/5_1_3.json
  Packs/CortexXDR/ReleaseNotes/5_1_3.md
  Packs/CortexXDR/pack_metadata.json
Labels: docs-approved, ForceMerge

#29461 Qualys fix schema
  Packs/qualys/ModelingRules/QualysModelingRules/QualysModelingRules_schema.json
  Packs/qualys/ReleaseNotes/2_0_4.md
  Packs/qualys/pack_metadata.json
Labels: docs-approved

#29481 Revert "Bump markdownlint from 0.26.2 to 0.30.0"
  package-lock.json
  package.json
Labels: docs-approved, ForceMerge

#29470 fix-sdk-warning-messages-vvv
  .circleci/config.yml
Labels: docs-approved

#29453 Deprecating block url generic
  Packs/CommonPlaybooks/.pack-ignore
  Packs/CommonPlaybooks/Playbooks/playbook-Block_URL_-_Generic.yml
  Packs/CommonPlaybooks/Playbooks/playbook-Block_URL_-_Generic_README.md
  Packs/CommonPlaybooks/ReleaseNotes/2_4_1.md
  Packs/CommonPlaybooks/doc_files/Block_URL_-_Generic.png
  Packs/CommonPlaybooks/pack_metadata.json
Labels: docs-approved

#29455 Fix dnstwistTest TPB
  Packs/dnstwist/TestPlaybooks/playbook-dnstwist_Test.yml
Labels: docs-approved

#29467 Fix Get Original Email - Microsoft Graph Mail - test TPB
  Packs/MicrosoftGraphMail/.secrets-ignore
  Packs/MicrosoftGraphMail/TestPlaybooks/playbook-Get_Original_Email_-_Microsoft_Graph_Mail_-_test.yml
Labels: docs-approved

#25915 Security scans
  .gitlab/ci/.gitlab-ci.on-push.yml
  .gitlab/ci/.gitlab-ci.security-scans.yml
  .gitlab/ci/.gitlab-ci.yml
  Tests/scripts/gitlab_slack_notifier.py
Labels: docs-approved

#29440 Fixed schema for Sentinel one
  Packs/SentinelOne/ModelingRules/SentinelOneModelingRules/SentinelOneModelingRules_schema.json
  Packs/SentinelOne/ReleaseNotes/3_2_8.md
  Packs/SentinelOne/pack_metadata.json
Labels: docs-approved

#29482 fix demisto-sdk -vvv in content management pack
  Packs/ContentManagement/doc_files/ci-cd.yml
Labels: docs-approved

#29299 Devcontainer maintanence
  .devcontainer/Dockerfile
  .devcontainer/createCommand.sh
  .devcontainer/devcontainer.json
Labels: docs-approved

#29433 Servicenow api fix
  Packs/ServiceNow/Integrations/ServiceNowv2/README.md
  Packs/ServiceNow/Integrations/ServiceNowv2/ServiceNowv2.py
  Packs/ServiceNow/Integrations/ServiceNowv2/ServiceNowv2.yml
  Packs/ServiceNow/Integrations/ServiceNowv2/ServiceNowv2_test.py
  Packs/ServiceNow/ReleaseNotes/2_5_40.md
  Packs/ServiceNow/pack_metadata.json
Labels: docs-approved

#29503 Deprecate qradar access investigation
  Packs/QRadar/Playbooks/playbook-Access_Investigation_-_QRadar.yml
  Packs/QRadar/ReleaseNotes/2_4_35.md
  Packs/QRadar/pack_metadata.json
Labels: docs-approved

#27960 Core api file delete: reverting deleting files from context data
  Packs/DemistoRESTAPI/Integrations/CoreRESTAPI/CoreRESTAPI.js
  Packs/DemistoRESTAPI/Integrations/CoreRESTAPI/CoreRESTAPI.yml
  Packs/DemistoRESTAPI/ReleaseNotes/1_3_35.md
  Packs/DemistoRESTAPI/pack_metadata.json
Labels: docs-approved

#29383 Removed MSG-ediscovery-tpb from skipped_tests.
  Tests/conf.json
Labels: docs-approved

#29515 fix regex
  Tests/test_content.py
  Tests/tests/configure_and_test_integration_instances_test.py
Labels: docs-approved

#29411 Cs falcon fetch limit issue
  Packs/CrowdStrikeFalcon/Integrations/CrowdStrikeFalcon/CrowdStrikeFalcon.py
  Packs/CrowdStrikeFalcon/Integrations/CrowdStrikeFalcon/CrowdStrikeFalcon.yml
  Packs/CrowdStrikeFalcon/Integrations/CrowdStrikeFalcon/CrowdStrikeFalcon_test.py
  Packs/CrowdStrikeFalcon/ReleaseNotes/1_11_8.md
  Packs/CrowdStrikeFalcon/pack_metadata.json
Labels: docs-approved

#29529 certificate-rehash-warning
  .gitlab/ci/.gitlab-ci.global.yml
  .gitlab/ci/.gitlab-ci.yml
Labels: docs-approved

#29371 Added keywords related to DNS sinkhole to the PAN-OS pack
  Packs/PAN-OS/pack_metadata.json
Labels: docs-approved

#29403 [pre-commit check-json] Align the entire repo with check-json
  Packs/CofenseIntelligenceV2/Integrations/CofenseIntelligenceV2/test_data/test_threats.json
  Packs/CortexXDR/Classifiers/classifier-PaloAltoNetworks_CortexXDR_5_9_9.json
  Packs/CortexXDR/ReleaseNotes/5_1_4.md
  Packs/CortexXDR/pack_metadata.json
  Packs/DuoAdminApi/ModelingRules/DuoModelingRule/DuoModelingRule_schema.json
  Packs/DuoAdminApi/ReleaseNotes/4_0_9.md
  Packs/DuoAdminApi/pack_metadata.json
  Packs/MicrosoftAdvancedThreatAnalytics/IncidentTypes/incidenttype-MicrosoftATASuspiciousActivity.json
  Packs/MicrosoftAdvancedThreatAnalytics/ReleaseNotes/1_0_15.md
  Packs/MicrosoftAdvancedThreatAnalytics/pack_metadata.json
  Packs/Palo_Alto_Networks_WildFire/Integrations/Palo_Alto_Networks_WildFire_v2/tests_data/report_url_response_success.json
  Packs/PhishLabs/Integrations/PhishLabsIOC_DRP/test_data/client_methods/get_cases/begin_date_filter/output_1.json
  Packs/PrismaSaasSecurity/ModelingRules/SaasSecurityEventCollector_1_3/SaasSecurityEventCollector_1_3_schema.json
  Packs/PrismaSaasSecurity/ReleaseNotes/2_0_27.md
  Packs/PrismaSaasSecurity/pack_metadata.json
  Packs/RiskIQDigitalFootprint/Integrations/RiskIQDigitalFootprint/test_data/get_asset_ip_address_resp.json
  Packs/RiskIQDigitalFootprint/Integrations/RiskIQDigitalFootprint/test_data/get_asset_page_resp.json
  Packs/SecurityScorecard/Integrations/SecurityScorecard/test_data/data.json
  Packs/epo/ModelingRules/McafeeEpoModelingRules/McafeeEpoModelingRules_schema.json
  Packs/epo/ReleaseNotes/2_0_26.md
  Packs/epo/pack_metadata.json
Labels: docs-approved, ForceMerge

#29528 [ASM] - EXPANDR-5879
  Packs/CortexAttackSurfaceManagement/Playbooks/Cortex_ASM_-_GCP_Enrichment.yml
  Packs/CortexAttackSurfaceManagement/ReleaseNotes/1_6_33.md
  Packs/CortexAttackSurfaceManagement/doc_files/Cortex_ASM_-_GCP_Enrichment.png
  Packs/CortexAttackSurfaceManagement/pack_metadata.json
Labels: Contribution, ready-for-instance-test, Contribution Form Filled, Community, Xsoar Support Level, External PR, Security Review

#28832 Workday Sign on Event Collector
  Packs/Workday/.pack-ignore
  Packs/Workday/Integrations/WorkdaySignOnEventCollector/README.md
  Packs/Workday/Integrations/WorkdaySignOnEventCollector/WorkdaySignOnEventCollector.py
  Packs/Workday/Integrations/WorkdaySignOnEventCollector/WorkdaySignOnEventCollector.yml
  Packs/Workday/Integrations/WorkdaySignOnEventCollector/WorkdaySignOnEventCollector_description.md
  Packs/Workday/Integrations/WorkdaySignOnEventCollector/WorkdaySignOnEventCollector_image.png
  Packs/Workday/Integrations/WorkdaySignOnEventCollector/WorkdaySignOnEventCollector_test.py
  Packs/Workday/Integrations/WorkdaySignOnEventCollector/command_examples
  Packs/Workday/Integrations/WorkdaySignOnEventCollector/test_data/example_event.json
  Packs/Workday/Integrations/WorkdaySignonEventGenerator/README.md
  Packs/Workday/Integrations/WorkdaySignonEventGenerator/WorkdaySignonEventGenerator.py
  Packs/Workday/Integrations/WorkdaySignonEventGenerator/WorkdaySignonEventGenerator.yml
  Packs/Workday/Integrations/WorkdaySignonEventGenerator/WorkdaySignonEventGenerator_description.md
  Packs/Workday/Integrations/WorkdaySignonEventGenerator/WorkdaySignonEventGenerator_image.png
  Packs/Workday/Integrations/WorkdaySignonEventGenerator/WorkdaySignonEventGenerator_test.py
  Packs/Workday/ModelingRules/WorkdayEventCollector/WorkdayEventCollector.xif
  Packs/Workday/ModelingRules/WorkdayEventCollector/WorkdayEventCollector.yml
  Packs/Workday/ModelingRules/WorkdayEventCollector/WorkdayEventCollector_schema.json
  Packs/Workday/README.md
  Packs/Workday/ReleaseNotes/1_4_0.md
  Packs/Workday/pack_metadata.json
Labels: docs-approved

#29463 Netskope Update
  Packs/Netskope/ModelingRules/NetskopeEventCollector_1_3/NetskopeEventCollector_1_3.xif
  Packs/Netskope/ModelingRules/NetskopeEventCollector_1_3/NetskopeEventCollector_1_3_schema.json
  Packs/Netskope/ReleaseNotes/3_2_3.md
  Packs/Netskope/pack_metadata.json
Labels: docs-approved, ForceMerge

#29471 SplunkPy help links in description broken
  Packs/SplunkPy/Integrations/SplunkPy/SplunkPy_description.md
  Packs/SplunkPy/ReleaseNotes/3_1_6.md
  Packs/SplunkPy/pack_metadata.json
Labels: docs-approved

#29550 Cs limit in idp detections
  Packs/CrowdStrikeFalcon/Integrations/CrowdStrikeFalcon/CrowdStrikeFalcon.py
  Packs/CrowdStrikeFalcon/ReleaseNotes/1_11_9.md
  Packs/CrowdStrikeFalcon/pack_metadata.json
Labels: docs-approved

#29504 Revert autocommitgenericsql
  Packs/GenericSQL/Integrations/GenericSQL/GenericSQL.py
  Packs/GenericSQL/Integrations/GenericSQL/GenericSQL_test.py
  Packs/GenericSQL/ReleaseNotes/1_0_25.json
  Packs/GenericSQL/ReleaseNotes/1_0_25.md
  Packs/GenericSQL/pack_metadata.json
Labels: docs-approved, ForceMerge

#29370 TAXII2 - Report obj issues
  Packs/TAXIIServer/Integrations/TAXII2Server/TAXII2Server.py
  Packs/TAXIIServer/Integrations/TAXII2Server/TAXII2Server.yml
  Packs/TAXIIServer/Integrations/TAXII2Server/TAXII2Server_test.py
  Packs/TAXIIServer/Integrations/TAXII2Server/test_data/ioc_for_report_relationship.json
  Packs/TAXIIServer/Integrations/TAXII2Server/test_data/relationship_report_file.json
  Packs/TAXIIServer/ReleaseNotes/2_0_45.md
  Packs/TAXIIServer/pack_metadata.json
Labels: docs-approved, ForceMerge

#29553 Cisco ISE Update
  Packs/cisco-ise/ModelingRules/cisco-ise/cisco-ise.xif
  Packs/cisco-ise/ReleaseNotes/1_0_18.md
  Packs/cisco-ise/pack_metadata.json
Labels: docs-approved

#29546 [native-runner] - update native:ga
  Tests/docker_native_image_config.json
Labels: docs-approved

#29363 unhide insecure
  Packs/MicrosoftExchangeOnline/Integrations/SecurityAndComplianceV2/SecurityAndComplianceV2.ps1
  Packs/MicrosoftExchangeOnline/Integrations/SecurityAndComplianceV2/SecurityAndComplianceV2.yml
  Packs/MicrosoftExchangeOnline/ReleaseNotes/1_2_25.md
  Packs/MicrosoftExchangeOnline/pack_metadata.json
Labels: docs-approved

#29309 Addition of risky asset outputs to Entity Enrichment & Endpoint Enrichment fix
  Packs/CommonPlaybooks/.pack-ignore
  Packs/CommonPlaybooks/Playbooks/Entity_Enrichment_-_Generic_v3.yml
  Packs/CommonPlaybooks/Playbooks/Entity_Enrichment_-_Generic_v3_README.md
  Packs/CommonPlaybooks/Playbooks/playbook-Endpoint_Enrichment_-_Generic_v2.1_6_8.yml
  Packs/CommonPlaybooks/ReleaseNotes/2_4_2.md
  Packs/CommonPlaybooks/pack_metadata.json
  Tests/known_words.txt
Labels: docs-approved

#29311 AWSRecreateSG Improvements
  Packs/AWS-Enrichment-Remediation/Playbooks/AWS_-_Security_Group_Remediation_v2.yml
  Packs/AWS-Enrichment-Remediation/Playbooks/AWS_-_Security_Group_Remediation_v2_README.md
  Packs/AWS-Enrichment-Remediation/ReleaseNotes/1_1_4.md
  Packs/AWS-Enrichment-Remediation/Scripts/AWSRecreateSG/AWSRecreateSG.py
  Packs/AWS-Enrichment-Remediation/Scripts/AWSRecreateSG/AWSRecreateSG.yml
  Packs/AWS-Enrichment-Remediation/Scripts/AWSRecreateSG/AWSRecreateSG_test.py
  Packs/AWS-Enrichment-Remediation/Scripts/AWSRecreateSG/README.md
  Packs/AWS-Enrichment-Remediation/Scripts/AWSRecreateSG/test_data/sample.py
  Packs/AWS-Enrichment-Remediation/pack_metadata.json
Labels: Contribution, docs-approved, ready-for-instance-test, pending-demo, Contribution Form Filled, Community, Xsoar Support Level, External PR

#27902 Multi commands in the same SSH session
  Packs/RemoteAccess/Integrations/RemoteAccessv2/README.md
  Packs/RemoteAccess/Integrations/RemoteAccessv2/RemoteAccessv2.yml
  Packs/RemoteAccess/ReleaseNotes/1_0_29.md
  Packs/RemoteAccess/pack_metadata.json
Labels: docs-approved, stale-branch

#29447 [slack] - fix issue with mirror-investigation
  Packs/Slack/Integrations/SlackV3/SlackV3.py
  Packs/Slack/Integrations/SlackV3/SlackV3.yml
  Packs/Slack/Integrations/SlackV3/SlackV3_test.py
  Packs/Slack/ReleaseNotes/3_2_1.md
  Packs/Slack/pack_metadata.json
Labels: docs-approved

#29439 Fix SaasSecurity-Test TPB
  Packs/PrismaSaasSecurity/TestPlaybooks/SaasSecurity-Test.yml
Labels: docs-approved

#29583 [Armis Event Collector] Add connectionIds to modeling rules schema
  Packs/Armis/ModelingRules/ArmisModelingRules/ArmisModelingRules_schema.json
  Packs/Armis/ReleaseNotes/1_1_1.md
  Packs/Armis/pack_metadata.json
Labels: docs-approved

#27054 StixCreator: fix report parser and continue on indicators errors
  Packs/CommonScripts/ReleaseNotes/1_12_21.md
  Packs/CommonScripts/Scripts/StixCreator/README.md
  Packs/CommonScripts/Scripts/StixCreator/StixCreator.py
  Packs/CommonScripts/Scripts/StixCreator/StixCreator.yml
  Packs/CommonScripts/pack_metadata.json
  Tests/demistomock/demistomock.py
Labels: docs-approved

#29508 Create one pre-commit-config file with all Python versions
  .pre-commit-config_template.yaml
Labels: docs-approved

#29571 XSIAM-Linux-Modeling-Enhancement-CIAC-7839
  Packs/LinuxEventsCollection/.pack-ignore
  Packs/LinuxEventsCollection/ModelingRules/LinuxEventsCollection_1_3/LinuxEventsCollection_1_3.xif
  Packs/LinuxEventsCollection/ReleaseNotes/1_0_7.md
  Packs/LinuxEventsCollection/pack_metadata.json
Labels: docs-approved

#29590 fixed content path
  .gitlab/ci/.gitlab-ci.bucket-upload.yml
Labels: docs-approved

#29427 locking core packs
  Tests/Marketplace/versions-metadata.json
Labels: docs-approved, ForceMerge

#29565 test modeling rule logging to the build
  Tests/scripts/convert_test_result_to_jira_issues.py
  Tests/scripts/test_modeling_rules.sh
  Utils/gitlab_triggers/trigger_content_nightly_build.sh
Labels: docs-approved

#29588 Netskope Schema Update
  Packs/Netskope/ModelingRules/NetskopeEventCollector_1_3/NetskopeEventCollector_1_3_schema.json
  Packs/Netskope/ReleaseNotes/3_2_4.md
  Packs/Netskope/pack_metadata.json
Labels: docs-approved

#29287 deprecating the PaloAltoNetworks content pack published in market place.
  Packs/PaloAltoNetworks_IoT3rdParty/Integrations/PaloAltoNetworksIoT3rdParty/PaloAltoNetworksIoT3rdParty.yml
  Packs/PaloAltoNetworks_IoT3rdParty/README.md
  Packs/PaloAltoNetworks_IoT3rdParty/ReleaseNotes/2_0_0.md
  Packs/PaloAltoNetworks_IoT3rdParty/pack_metadata.json
Labels: Contribution, docs-approved, pending-contributor, Xsoar Support Level, External PR

#29472 Removed unnecessary debug logs.
  Packs/Exabeam/Integrations/Exabeam/Exabeam.py
  Packs/Exabeam/Integrations/Exabeam/Exabeam.yml
  Packs/Exabeam/ReleaseNotes/2_2_8.md
  Packs/Exabeam/pack_metadata.json
Labels: docs-approved

#29602 timeout for polling command (create file) was updated.
  Packs/CommonPlaybooks/TestPlaybooks/playbook-Containment_Plan-Test.yml
  Packs/CommonPlaybooks/TestPlaybooks/playbook-Eradication_plan_-_Test.yml
Labels: docs-approved

#29518 GoogleDrive - Added missing arguments to perform actions in Shared Drives
  Packs/GoogleDrive/.pack-ignore
  Packs/GoogleDrive/Integrations/GoogleDrive/GoogleDrive.py
  Packs/GoogleDrive/Integrations/GoogleDrive/GoogleDrive.yml
  Packs/GoogleDrive/Integrations/GoogleDrive/README.md
  Packs/GoogleDrive/ReleaseNotes/1_2_41.md
  Packs/GoogleDrive/TestPlaybooks/playbook-GoogleDrive-Test.yml
  Packs/GoogleDrive/pack_metadata.json
Labels: docs-approved

#29513 Added 'UserVerification' as input for 'NGFW Scan' playbook
  Packs/Core/Playbooks/playbook-NGFW_Scan.yml
  Packs/Core/Playbooks/playbook-NGFW_Scan_README.md
  Packs/Core/ReleaseNotes/2_0_14.md
  Packs/Core/pack_metadata.json
Labels: docs-approved

#29606 Prisma Cloud V2 Test Playbook Fix
  Packs/PrismaCloud/TestPlaybooks/Prisma_Cloud_Test.yml
Labels: docs-approved

#29187 Add command prisma-cloud-compute-get-file-integrity-events
  Packs/PrismaCloudCompute/Integrations/PaloAltoNetworks_PrismaCloudCompute/PaloAltoNetworks_PrismaCloudCompute.py
  Packs/PrismaCloudCompute/Integrations/PaloAltoNetworks_PrismaCloudCompute/PaloAltoNetworks_PrismaCloudCompute.yml
  Packs/PrismaCloudCompute/Integrations/PaloAltoNetworks_PrismaCloudCompute/PaloAltoNetworks_PrismaCloudCompute_description.md
  Packs/PrismaCloudCompute/Integrations/PaloAltoNetworks_PrismaCloudCompute/PaloAltoNetworks_PrismaCloudCompute_test.py
  Packs/PrismaCloudCompute/Integrations/PaloAltoNetworks_PrismaCloudCompute/README.md
  Packs/PrismaCloudCompute/Integrations/PaloAltoNetworks_PrismaCloudCompute/commands.txt
  Packs/PrismaCloudCompute/Integrations/PaloAltoNetworks_PrismaCloudCompute/test_data/file_integrity_events.json
  Packs/PrismaCloudCompute/ReleaseNotes/1_4_9.md
  Packs/PrismaCloudCompute/pack_metadata.json
Labels: Contribution, docs-approved, post-demo, Contribution Form Filled, Community, Xsoar Support Level, External PR

#29610 [DBotFindSimilarIncidentsByIndicators] Fixed the output
  Packs/Base/ReleaseNotes/1_32_33.md
  Packs/Base/Scripts/DBotFindSimilarIncidentsByIndicators/DBotFindSimilarIncidentsByIndicators.py
  Packs/Base/pack_metadata.json
Labels: docs-approved

#29612 Turn markdown logs to debug
  Tests/Marketplace/pack_readme_handler.py
  Tests/Marketplace/upload_packs.py
Labels: docs-approved

#29591 fixing relative path sourcing in triggers scripts
  Utils/gitlab_triggers/trigger_build_url.sh
  Utils/gitlab_triggers/trigger_build_with_ttl.sh
  Utils/gitlab_triggers/trigger_content_instance_testing_build.sh
  Utils/gitlab_triggers/trigger_content_nightly_build.sh
  Utils/gitlab_triggers/trigger_upload_flow_build.sh
Labels: docs-approved

#29578 Xdr layout fixes
  Packs/CortexXDR/Layouts/layoutscontainer-Cortex_XDR_Incident.json
  Packs/CortexXDR/ReleaseNotes/5_1_5.md
  Packs/CortexXDR/pack_metadata.json
Labels: docs-approved

#29626 fix trigger script, missing comment
  Utils/gitlab_triggers/trigger_content_instance_testing_build.sh
  Utils/gitlab_triggers/trigger_content_nightly_build.sh
Labels: docs-approved

#29181 Fix proxy usage (#85)
  Packs/ZeroFox/Integrations/ZeroFox/ZeroFox.py
  Packs/ZeroFox/Integrations/ZeroFox/ZeroFox_test.py
  Packs/ZeroFox/ReleaseNotes/1_1_1.md
  Packs/ZeroFox/pack_metadata.json
Labels: Contribution, Partner, post-demo, Contribution Form Filled, Partner Support Level, External PR

#28985 Proofpoint Email Security Event Collector
  Packs/ProofpointEmailSecurity/.pack-ignore
  Packs/ProofpointEmailSecurity/.secrets-ignore
  Packs/ProofpointEmailSecurity/Integrations/ProofpointEmailSecurityEventCollector/ProofpointEmailSecurityEventCollector.py
  Packs/ProofpointEmailSecurity/Integrations/ProofpointEmailSecurityEventCollector/ProofpointEmailSecurityEventCollector.yml
  Packs/ProofpointEmailSecurity/Integrations/ProofpointEmailSecurityEventCollector/ProofpointEmailSecurityEventCollector_description.md
  Packs/ProofpointEmailSecurity/Integrations/ProofpointEmailSecurityEventCollector/ProofpointEmailSecurityEventCollector_image.png
  Packs/ProofpointEmailSecurity/Integrations/ProofpointEmailSecurityEventCollector/ProofpointEmailSecurityEventCollector_test.py
  Packs/ProofpointEmailSecurity/Integrations/ProofpointEmailSecurityEventCollector/README.md
  Packs/ProofpointEmailSecurity/ModelingRules/ProofpointEmailSecurity/ProofpointEmailSecurity.xif
  Packs/ProofpointEmailSecurity/ModelingRules/ProofpointEmailSecurity/ProofpointEmailSecurity.yml
  Packs/ProofpointEmailSecurity/ModelingRules/ProofpointEmailSecurity/ProofpointEmailSecurity_schema.json
  Packs/ProofpointEmailSecurity/README.md
  Packs/ProofpointEmailSecurity/pack_metadata.json
Labels: docs-approved

#29631 Updated native candidate
  Tests/docker_native_image_config.json
Labels: docs-approved

#29632 Test upload: use the SDK_REF in the test upload job
  Utils/trigger_test_upload_flow.sh
Labels: docs-approved

#29633 Compute audit v2 mapper
  Packs/PrismaCloudCompute/Classifiers/classifier-mapper-incoming-PrismaCloudCompute.json
  Packs/PrismaCloudCompute/IncidentFields/incidentfield-Prisma_Cloud_Compute_Activity_Type.json
  Packs/PrismaCloudCompute/IncidentFields/incidentfield-Prisma_Cloud_Compute_AppID.json
  Packs/PrismaCloudCompute/IncidentFields/incidentfield-Prisma_Cloud_Compute_Category.json
  Packs/PrismaCloudCompute/IncidentFields/incidentfield-Prisma_Cloud_Compute_Command.json
  Packs/PrismaCloudCompute/IncidentFields/incidentfield-Prisma_Cloud_Compute_Container.json
  Packs/PrismaCloudCompute/IncidentFields/incidentfield-Prisma_Cloud_Compute_Forensic.json
  Packs/PrismaCloudCompute/IncidentFields/incidentfield-Prisma_Cloud_Compute_Function.json
  Packs/PrismaCloudCompute/IncidentFields/incidentfield-Prisma_Cloud_Compute_Interactive.json
  Packs/PrismaCloudCompute/IncidentFields/incidentfield-Prisma_Cloud_Compute_Kubernetes_Resource.json
  Packs/PrismaCloudCompute/IncidentFields/incidentfield-Prisma_Cloud_Compute_Labels.json
  Packs/PrismaCloudCompute/IncidentFields/incidentfield-Prisma_Cloud_Compute_Line.json
  Packs/PrismaCloudCompute/IncidentFields/incidentfield-Prisma_Cloud_Compute_Log_File.json
  Packs/PrismaCloudCompute/IncidentFields/incidentfield-Prisma_Cloud_Compute_Message.json
  Packs/PrismaCloudCompute/IncidentFields/incidentfield-Prisma_Cloud_Compute_Region.json
  Packs/PrismaCloudCompute/IncidentFields/incidentfield-Prisma_Cloud_Compute_Rule.json
  Packs/PrismaCloudCompute/IncidentFields/incidentfield-Prisma_Cloud_Compute_Runtime.json
  Packs/PrismaCloudCompute/IncidentFields/incidentfield-Prisma_Cloud_Compute_Service.json
  Packs/PrismaCloudCompute/IncidentFields/incidentfield-Prisma_Cloud_Compute_Type.json
  Packs/PrismaCloudCompute/IncidentFields/incidentfield-Prisma_Cloud_Compute_User.json
  Packs/PrismaCloudCompute/ReleaseNotes/1_4_9.md
  Packs/PrismaCloudCompute/pack_metadata.json
Labels: docs-approved

#29603 [pre-commit ruff] Align the entire repo with ruff
  Packs/CimTrak-SystemIntegrityAssurance/Integrations/CimTrak/CimTrak_test.py
  Utils/_script_docker_python_loop_example.py
  Utils/update_playbook.py
Labels: docs-approved

#29621 remove code to trigger upload on dev branches
  .gitlab/ci/.gitlab-ci.bucket-upload.yml
Labels: docs-approved

#29611 [pre-commit pycln] Align the entire repo with pycln
  Packs/AccentureCTI/Integrations/ACTIIndicatorQuery/ACTIIndicatorQuery_test.py
  Packs/AccentureCTI/Integrations/ACTIVulnerabilityQuery/ACTIVulnerabilityQuery_test.py
  Packs/CommonScripts/ReleaseNotes/1_12_23.md
  Packs/CommonScripts/Scripts/GetDomainDNSDetails/GetDomainDNSDetails.py
  Packs/CommonScripts/Scripts/GetDomainDNSDetails/GetDomainDNSDetails.yml
  Packs/CommonScripts/Scripts/PositiveDetectionsVSDetectionEngines/PositiveDetectionsVSDetectionEngines_test.py
  Packs/CommonScripts/pack_metadata.json
  Packs/DatadogCloudSIEM/Integrations/DatadogCloudSIEM/DatadogCloudSIEM_test.py
  Packs/LogsignSiem/Integrations/LogsignSiem/LogsignSiem_test.py
  Packs/MobileIronUEM/Integrations/MobileIronCLOUD/MobileIronCLOUD_test.py
  Packs/PAN-OS/Integrations/Panorama/Panorama.py
  Packs/PAN-OS/Integrations/Panorama/Panorama.yml
  Packs/PAN-OS/ReleaseNotes/2_1_6.md
  Packs/PAN-OS/pack_metadata.json
  Packs/knowbe4Phisher/Integrations/knowbe4Phisher/knowbe4Phisher_test.py
  Tests/scripts/utils/logging_wrapper/__init__.py
  Tests/test_content.py
Labels: docs-approved, ForceMerge

#29338 Mde list indicator filter
  Packs/MicrosoftDefenderAdvancedThreatProtection/Integrations/MicrosoftDefenderAdvancedThreatProtection/MicrosoftDefenderAdvancedThreatProtection.py
  Packs/MicrosoftDefenderAdvancedThreatProtection/Integrations/MicrosoftDefenderAdvancedThreatProtection/MicrosoftDefenderAdvancedThreatProtection.yml
  Packs/MicrosoftDefenderAdvancedThreatProtection/Integrations/MicrosoftDefenderAdvancedThreatProtection/README.md
  Packs/MicrosoftDefenderAdvancedThreatProtection/ReleaseNotes/1_16_9.md
  Packs/MicrosoftDefenderAdvancedThreatProtection/pack_metadata.json
Labels: Contribution, pending-demo, post-demo, Contribution Form Filled, Community, pending-contributor, Xsoar Support Level, External PR

#29025 Recordedfuture threathunting v2.5.0
  Packs/RecordedFuture/Integrations/RecordedFuture/README.md
  Packs/RecordedFuture/Integrations/RecordedFuture/RecordedFuture.py
  Packs/RecordedFuture/Integrations/RecordedFuture/RecordedFuture.yml
  Packs/RecordedFuture/Integrations/RecordedFuture/RecordedFuture_test.py
  Packs/RecordedFuture/Playbooks/playbook-Recorded_Future_Threat_Actor_Search.yml
  Packs/RecordedFuture/Playbooks/playbook-Recorded_Future_Threat_Actor_Search_README.md
  Packs/RecordedFuture/ReleaseNotes/1_7_0.md
  Packs/RecordedFuture/pack_metadata.json
Labels: Contribution, Partner, ready-for-instance-test, post-demo, Contribution Form Filled, Partner Support Level, External PR, Security Review, Partner-Approved

#29593 [ASM] - EXPANDR-5553
  Packs/CortexAttackSurfaceManagement/Playbooks/Cortex_ASM_-_AWS_Enrichment.yml
  Packs/CortexAttackSurfaceManagement/ReleaseNotes/1_6_35.md
  Packs/CortexAttackSurfaceManagement/pack_metadata.json
Labels: Contribution, ready-for-instance-test, Contribution Form Filled, Community, Xsoar Support Level, External PR, Security Review

#29638 [pre-commit autopep8] Align the entire repo with autopep8 hook #2
  Packs/APIVoid/Integrations/APIVoid/APIVoid.py
  Packs/ARIAPacketIntelligence/Integrations/ARIAPacketIntelligence/ARIAPacketIntelligence.py
  Packs/AWS-GuardDuty/Integrations/AWSGuardDutyEventCollector/AWSGuardDutyEventCollector.py
  Packs/AWS-NetworkFirewall/Integrations/AWS-NetworkFirewall/AWS-NetworkFirewall.py
  Packs/Akamai_WAF/Integrations/Akamai_WAF/Akamai_WAF.py
  Packs/Attlasian/Integrations/Attlasian_IAM/Attlasian_IAM.py
  Packs/BMCDiscovery/Integrations/BMCDiscovery/BMCDiscovery.py
  Packs/Base/Scripts/StixParser/StixParser.py
  Packs/BeyondTrust_Password_Safe/Integrations/BeyondTrust_Password_Safe/BeyondTrust_Password_Safe.py
  Packs/CarbonBlackDefense/Integrations/CarbonBlackEndpointStandard/CarbonBlackEndpointStandard.py
  Packs/CarbonBlackDefense/Integrations/CarbonBlackLiveResponseCloud/CarbonBlackLiveResponseCloud.py
  Packs/Carbon_Black_Enterprise_Response/Integrations/CarbonBlackResponseV2/CarbonBlackResponseV2.py
  Packs/CiscoFirepower/Integrations/CiscoFirepower/CiscoFirepower.py
  Packs/CiscoUmbrellaReporting/Integrations/CiscoUmbrellaReporting/CiscoUmbrellaReporting.py
  Packs/CommonScripts/Scripts/ExtractHTMLTables/ExtractHTMLTables.py
  Packs/CommonScripts/Scripts/HTTPListRedirects/HTTPListRedirects.py
  Packs/CommonScripts/Scripts/ParseHTMLIndicators/ParseHTMLIndicators.py
  Packs/CommunityCommonScripts/Scripts/CreatePlbkDoc/CreatePlbkDoc.py
  Packs/ConcentricAI/Integrations/ConcentricAI/ConcentricAI.py
  Packs/CounterTack/Integrations/CounterTack/CounterTack.py
  Packs/CrowdStrikeFalconStreamingV2/Integrations/CrowdStrikeFalconStreamingV2/CrowdStrikeFalconStreamingV2.py
  Packs/CrowdStrikeMalquery/Integrations/CrowdStrikeMalquery/CrowdStrikeMalquery.py
  Packs/CrowdStrikeOpenAPI/Integrations/CrowdStrikeOpenAPI/CrowdStrikeOpenAPI.py
  Packs/CybleEvents/Integrations/CybleEvents/CybleEvents.py
  Packs/Endace/Integrations/Endace/Endace.py
  Packs/ExceedLMS/Integrations/IAMExceedLMS/IAMExceedLMS.py
  Packs/FeedAlienVault/Integrations/FeedAlienVaultOTXTaxii/FeedAlienVaultOTXTaxii.py
  Packs/FeedCrowdstrikeFalconIntel/Integrations/FeedCrowdstrikeFalconIntel/FeedCrowdstrikeFalconIntel.py
  Packs/FidelisEndpoint/Integrations/FidelisEndpoint/FidelisEndpoint.py
  Packs/FiltersAndTransformers/Scripts/DedupBy/DedupBy.py
  Packs/FiltersAndTransformers/Scripts/SortBy/SortBy.py
  Packs/FireEyeCM/Integrations/FireEyeCM/FireEyeCM.py
  Packs/ForcepointSecurityManagementCenter/Integrations/ForcepointSecurityManagementCenter/ForcepointSecurityManagementCenter.py
  Packs/GoogleKeyManagementService/Integrations/GoogleKeyManagementService/GoogleKeyManagementService.py
  Packs/GoogleVertexAI/Integrations/GoogleVertexAI/GoogleVertexAI.py
  Packs/Looker/Integrations/Looker/Looker.py
  Packs/McAfee-MAR/Integrations/McAfee-MAR/McAfee-MAR.py
  Packs/McAfee-TIE/Integrations/McAfeeTIEV2/McAfeeTIEV2.py
  Packs/McAfeeWebGateway/Integrations/SkyhighSecureWebGatewayOnPrem/SkyhighSecureWebGatewayOnPrem.py
  Packs/OracleCloudInfrastructure/Integrations/OracleCloudInfrastructureEventCollector/OracleCloudInfrastructureEventCollector.py
  Packs/PaloAltoNetworks_IoT3rdParty/Scripts/SendAllPANWIoTAssetsToSIEM/SendAllPANWIoTAssetsToSIEM.py
  Packs/PaloAltoNetworks_IoT3rdParty/Scripts/SendAllPANWIoTDevicesToCiscoISE/SendAllPANWIoTDevicesToCiscoISE.py
  Packs/PicusAutomation/Integrations/Picus/Picus.py
  Packs/QutteraWebsiteMalwareScanner/Integrations/QutteraWebsiteMalwareScanner/QutteraWebsiteMalwareScanner.py
  Packs/Respond/Integrations/RespondAnalyst/RespondAnalyst.py
  Packs/SafeNet_Trusted_Access/Integrations/SafeNetTrustedAccessEventCollector/SafeNetTrustedAccessEventCollector.py
  Packs/SecneurXAnalysis/Integrations/SecneurXAnalysis/SecneurXAnalysis.py
  Packs/SecurityScorecard/Integrations/SecurityScorecard/SecurityScorecard.py
  Packs/ServiceNow/Scripts/ServiceNowCreateIncident/ServiceNowCreateIncident.py
  Packs/ServiceNow/Scripts/ServiceNowQueryIncident/ServiceNowQueryIncident.py
  Packs/ServiceNow/Scripts/ServiceNowUpdateIncident/ServiceNowUpdateIncident.py
  Packs/Stairwell/Integrations/Inception/Inception.py
  Packs/Stealthwatch_Cloud/Integrations/Stealthwatch_Cloud/Stealthwatch_Cloud.py
  Packs/SumoLogic_Cloud_SIEM/Integrations/SumoLogicCloudSIEM/SumoLogicCloudSIEM.py
  Packs/TOPdesk/Integrations/TOPdesk/TOPdesk.py
  Packs/Vectra_AI/Integrations/VectraDetect/VectraDetect.py
  Packs/WithSecure/Integrations/WithSecureEventCollector/WithSecureEventCollector.py
Labels: ForceMerge

#29619 [ASM] Expander 5777
  Packs/CortexAttackSurfaceManagement/Playbooks/Cortex_ASM_-_Remediation.yml
  Packs/CortexAttackSurfaceManagement/Playbooks/Cortex_ASM_-_Remediation_README.md
  Packs/CortexAttackSurfaceManagement/ReleaseNotes/1_6_35.md
  Packs/CortexAttackSurfaceManagement/doc_files/Cortex_ASM_-_Remediation.png
  Packs/CortexAttackSurfaceManagement/pack_metadata.json
Labels: Contribution, ready-for-instance-test, Contribution Form Filled, Community, Xsoar Support Level, External PR, Security Review

#29644 [MS Teams] support reset_graph_auth
  Packs/MicrosoftTeams/Integrations/MicrosoftTeams/MicrosoftTeams.py
  Packs/MicrosoftTeams/Integrations/MicrosoftTeams/MicrosoftTeams.yml
  Packs/MicrosoftTeams/Integrations/MicrosoftTeams/MicrosoftTeams_test.py
  Packs/MicrosoftTeams/ReleaseNotes/1_4_34.md
  Packs/MicrosoftTeams/pack_metadata.json
Labels: docs-approved

#29585 XDR Malware Enrichment - hotfix for usernames (split)
  Packs/CortexXDR/Playbooks/playbook-Cortex_XDR_Malware_-_Incident_Enrichment.yml
  Packs/CortexXDR/ReleaseNotes/5_1_6.md
  Packs/CortexXDR/doc_files/Cortex_XDR_Malware_-_Incident_Enrichment.png
  Packs/CortexXDR/pack_metadata.json
Labels: docs-approved, release-notes-only

#28703 Add reliability parameter to cves and pipl integration
  Packs/Pipl/.pack-ignore
  Packs/Pipl/Integrations/Pipl/Pipl.js
  Packs/Pipl/Integrations/Pipl/Pipl.yml
  Packs/Pipl/Integrations/Pipl/README.md
  Packs/Pipl/ReleaseNotes/1_0_8.md
  Packs/Pipl/pack_metadata.json
  Packs/PrismaCloudCompute/.pack-ignore
  Packs/PrismaCloudCompute/Integrations/PaloAltoNetworks_PrismaCloudCompute/PaloAltoNetworks_PrismaCloudCompute.py
  Packs/PrismaCloudCompute/Integrations/PaloAltoNetworks_PrismaCloudCompute/PaloAltoNetworks_PrismaCloudCompute.yml
  Packs/PrismaCloudCompute/Integrations/PaloAltoNetworks_PrismaCloudCompute/PaloAltoNetworks_PrismaCloudCompute_test.py
  Packs/PrismaCloudCompute/Integrations/PaloAltoNetworks_PrismaCloudCompute/README.md
  Packs/PrismaCloudCompute/ReleaseNotes/1_4_10.md
  Packs/PrismaCloudCompute/TestPlaybooks/playbook-PaloAltoNetworks_PrismaCloudCompute-Test.yml
  Packs/PrismaCloudCompute/pack_metadata.json
Labels: docs-approved, ForceMerge

#29651 Proofpoint email security pack: update description
  Packs/ProofpointEmailSecurity/ModelingRules/ProofpointEmailSecurity/ProofpointEmailSecurity_schema.json
  Packs/ProofpointEmailSecurity/ReleaseNotes/1_0_1.md
  Packs/ProofpointEmailSecurity/pack_metadata.json
Labels: docs-approved

#29649 Jira v2 deprecated
  Packs/Jira/Integrations/JiraV2/JiraV2.yml
  Packs/Jira/Playbooks/playbook-Create_Jira_Issue.yml
  Packs/Jira/Playbooks/playbook-Create_Jira_Issue_README.md
  Packs/Jira/ReleaseNotes/3_1_2.md
  Packs/Jira/doc_files/Create_Jira_Issue.png
  Packs/Jira/pack_metadata.json
  Tests/conf.json
Labels: docs-approved

#29458 XSUP-27717/FortiSIEM
  Packs/FortiSIEM/Integrations/FortiSIEMV2/FortiSIEMV2.py
  Packs/FortiSIEM/Integrations/FortiSIEMV2/FortiSIEMV2.yml
  Packs/FortiSIEM/Integrations/FortiSIEMV2/FortiSIEMV2_test.py
  Packs/FortiSIEM/Integrations/FortiSIEMV2/test_data/fetch_incidents_without_incidentTitle.json
  Packs/FortiSIEM/ReleaseNotes/2_0_21.md
  Packs/FortiSIEM/pack_metadata.json
Labels: docs-approved

#29607 reverting the Docker image
  Packs/cyberark_AIM/Integrations/CyberArkAIM_v2/CyberArkAIM_v2.yml
  Packs/cyberark_AIM/ReleaseNotes/1_0_14.md
  Packs/cyberark_AIM/pack_metadata.json
Labels: docs-approved, ForceMerge

#29646 add unstuck fetch stream command
  Packs/PrismaCloudCompute/Integrations/PaloAltoNetworks_PrismaCloudCompute/PaloAltoNetworks_PrismaCloudCompute.py
  Packs/PrismaCloudCompute/Integrations/PaloAltoNetworks_PrismaCloudCompute/PaloAltoNetworks_PrismaCloudCompute.yml
  Packs/PrismaCloudCompute/Integrations/PaloAltoNetworks_PrismaCloudCompute/README.md
  Packs/PrismaCloudCompute/ReleaseNotes/1_4_11.md
  Packs/PrismaCloudCompute/pack_metadata.json
Labels: docs-approved

#29665 [pre-commit pycln] Align the entire repo with pycln #4
  Packs/CarbonBlackDefense/Integrations/CarbonBlackLiveResponseCloud/CarbonBlackLiveResponseCloud_test.py
  Packs/SendGrid/Integrations/SendGrid/SendGrid.py
  Packs/SendGrid/Integrations/SendGrid/SendGrid.yml
  Packs/SendGrid/ReleaseNotes/1_1_3.md
  Packs/SendGrid/pack_metadata.json
Labels: docs-approved

#29605 Remove unnecessary recommendations from extensions.json
  .devcontainer/devcontainer.json
  .vscode/extensions.json
Labels: docs-approved

#29223 PANOS - EXPANDR-5744
  Packs/PAN-OS/Playbooks/playbook-PAN-OS_-_Block_Destination_Service.yml
  Packs/PAN-OS/Playbooks/playbook-PAN-OS_-_Block_Destination_Service_README.md
  Packs/PAN-OS/ReleaseNotes/2_1_7.md
  Packs/PAN-OS/doc_files/PAN-OS_-_Block_Destination_Service.png
  Packs/PAN-OS/pack_metadata.json
Labels: Contribution, docs-approved, pending-demo, Contribution Form Filled, Community, Xsoar Support Level, External PR, Security Review

#29134 Rapid7 appsec
  Packs/Rapid7AppSec/.pack-ignore
  Packs/Rapid7AppSec/.secrets-ignore
  Packs/Rapid7AppSec/Integrations/Rapid7AppSec/README.md
  Packs/Rapid7AppSec/Integrations/Rapid7AppSec/Rapid7AppSec.py
  Packs/Rapid7AppSec/Integrations/Rapid7AppSec/Rapid7AppSec.yml
  Packs/Rapid7AppSec/Integrations/Rapid7AppSec/Rapid7AppSec_description.md
  Packs/Rapid7AppSec/Integrations/Rapid7AppSec/Rapid7AppSec_image.png
  Packs/Rapid7AppSec/Integrations/Rapid7AppSec/Rapid7AppSec_test.py
  Packs/Rapid7AppSec/Integrations/Rapid7AppSec/command_examples.txt
  Packs/Rapid7AppSec/Integrations/Rapid7AppSec/test_data/scan/get_app_engine_group.json
  Packs/Rapid7AppSec/Integrations/Rapid7AppSec/test_data/scan/get_attack_template.json
  Packs/Rapid7AppSec/Integrations/Rapid7AppSec/test_data/scan/get_engine.json
  Packs/Rapid7AppSec/Integrations/Rapid7AppSec/test_data/scan/get_execution_details.json
  Packs/Rapid7AppSec/Integrations/Rapid7AppSec/test_data/scan/get_module.json
  Packs/Rapid7AppSec/Integrations/Rapid7AppSec/test_data/scan/get_scan.json
  Packs/Rapid7AppSec/Integrations/Rapid7AppSec/test_data/scan/get_scan_config.json
  Packs/Rapid7AppSec/Integrations/Rapid7AppSec/test_data/scan/list_app.json
  Packs/Rapid7AppSec/Integrations/Rapid7AppSec/test_data/scan/list_attack_template.json
  Packs/Rapid7AppSec/Integrations/Rapid7AppSec/test_data/scan/list_engine.json
  Packs/Rapid7AppSec/Integrations/Rapid7AppSec/test_data/scan/list_engine_events.json
  Packs/Rapid7AppSec/Integrations/Rapid7AppSec/test_data/scan/list_engine_group.json
  Packs/Rapid7AppSec/Integrations/Rapid7AppSec/test_data/scan/list_modules.json
  Packs/Rapid7AppSec/Integrations/Rapid7AppSec/test_data/scan/list_platform_events.json
  Packs/Rapid7AppSec/Integrations/Rapid7AppSec/test_data/scan/list_scan.json
  Packs/Rapid7AppSec/Integrations/Rapid7AppSec/test_data/scan/list_scan_config.json
  Packs/Rapid7AppSec/Integrations/Rapid7AppSec/test_data/scan/scan_action.json
  Packs/Rapid7AppSec/Integrations/Rapid7AppSec/test_data/vulnerability/get.json
  Packs/Rapid7AppSec/Integrations/Rapid7AppSec/test_data/vulnerability/get_attack.json
  Packs/Rapid7AppSec/Integrations/Rapid7AppSec/test_data/vulnerability/get_attack_documentation.json
  Packs/Rapid7AppSec/Integrations/Rapid7AppSec/test_data/vulnerability/get_comment.json
  Packs/Rapid7AppSec/Integrations/Rapid7AppSec/test_data/vulnerability/list.json
  Packs/Rapid7AppSec/Integrations/Rapid7AppSec/test_data/vulnerability/list_2.json
  Packs/Rapid7AppSec/Integrations/Rapid7AppSec/test_data/vulnerability/list_3.json
  Packs/Rapid7AppSec/Integrations/Rapid7AppSec/test_data/vulnerability/list_comment.json
  Packs/Rapid7AppSec/Integrations/Rapid7AppSec/test_data/vulnerability/list_history.json
  Packs/Rapid7AppSec/README.md
  Packs/Rapid7AppSec/TestPlaybooks/playbook-Rapid7AppSec_Test.yml
  Packs/Rapid7AppSec/pack_metadata.json
Labels: Contribution, docs-approved, ready-for-instance-test, Contribution Form Filled, Community, External PR

#29094 Zscaler-FW-Logs
  Packs/Zscaler/ModelingRules/ZscalerModelingRule_1_3/ZscalerModelingRule_1_3.xif
  Packs/Zscaler/ModelingRules/ZscalerModelingRule_1_3/ZscalerModelingRule_1_3_schema.json
  Packs/Zscaler/README.md
  Packs/Zscaler/ReleaseNotes/1_3_13.md
  Packs/Zscaler/pack_metadata.json
Labels: docs-approved

#29681 Workday documentation fix
  Packs/Workday/Integrations/WorkdayEventCollector/README.md
  Packs/Workday/Integrations/WorkdayEventCollector/WorkdayEventCollector.yml
  Packs/Workday/ReleaseNotes/1_4_1.md
  Packs/Workday/pack_metadata.json
Labels: docs-approved

#29680 Big query bug xsup 28132
  Packs/GoogleBigQuery/Integrations/GoogleBigQuery/GoogleBigQuery.py
  Packs/GoogleBigQuery/Integrations/GoogleBigQuery/GoogleBigQuery.yml
  Packs/GoogleBigQuery/ReleaseNotes/1_1_7.md
  Packs/GoogleBigQuery/pack_metadata.json
Labels: docs-approved

#29323 New Prisma Cloud v2 commands
  Packs/PrismaCloud/Integrations/PrismaCloudV2/PrismaCloudV2.py
  Packs/PrismaCloud/Integrations/PrismaCloudV2/PrismaCloudV2.yml
  Packs/PrismaCloud/Integrations/PrismaCloudV2/PrismaCloudV2_test.py
  Packs/PrismaCloud/Integrations/PrismaCloudV2/README.md
  Packs/PrismaCloud/Integrations/PrismaCloudV2/command_examples
  Packs/PrismaCloud/ReleaseNotes/4_2_3.md
  Packs/PrismaCloud/TestPlaybooks/Prisma_Cloud_Test.yml
  Packs/PrismaCloud/pack_metadata.json
Labels: docs-approved

#29666 Prisma Cloud Update
  Packs/PrismaCloud/ModelingRules/PrismaCloud/PrismaCloud.xif
  Packs/PrismaCloud/ReleaseNotes/4_2_4.md
  Packs/PrismaCloud/pack_metadata.json
Labels: docs-approved

#29672 Panos add param
  Packs/PAN-OS/Integrations/Panorama/Panorama.py
  Packs/PAN-OS/Integrations/Panorama/Panorama.yml
  Packs/PAN-OS/Integrations/Panorama/Panorama_test.py
  Packs/PAN-OS/Integrations/Panorama/README.md
  Packs/PAN-OS/ReleaseNotes/2_1_8.md
  Packs/PAN-OS/pack_metadata.json
Labels: docs-approved

#29506 [ASM] - Expander - Update ASM fields (4821)
  Packs/CortexAttackSurfaceManagement/IncidentFields/incidentfield-ASM_-_Alert_Summary.json
  Packs/CortexAttackSurfaceManagement/IncidentFields/incidentfield-ASM_-_Asset_ID.json
  Packs/CortexAttackSurfaceManagement/IncidentFields/incidentfield-ASM_-_Attack_Surface_Rule_ID.json
  Packs/CortexAttackSurfaceManagement/IncidentFields/incidentfield-ASM_-_Cloud.json
  Packs/CortexAttackSurfaceManagement/IncidentFields/incidentfield-ASM_-_Data_Collection.json
  Packs/CortexAttackSurfaceManagement/IncidentFields/incidentfield-ASM_-_Dev_Check_Details.json
  Packs/CortexAttackSurfaceManagement/IncidentFields/incidentfield-ASM_-_Enrichment_Status.json
  Packs/CortexAttackSurfaceManagement/IncidentFields/incidentfield-ASM_-_Notification.json
  Packs/CortexAttackSurfaceManagement/IncidentFields/incidentfield-ASM_-_Playbook_Stage.json
  Packs/CortexAttackSurfaceManagement/IncidentFields/incidentfield-ASM_-_Private_IP.json
  Packs/CortexAttackSurfaceManagement/IncidentFields/incidentfield-ASM_-_Related.json
  Packs/CortexAttackSurfaceManagement/IncidentFields/incidentfield-ASM_-_Remediation.json
  Packs/CortexAttackSurfaceManagement/IncidentFields/incidentfield-ASM_-_Remediation_Objectives.json
  Packs/CortexAttackSurfaceManagement/IncidentFields/incidentfield-ASM_-_Remediation_Path_Rule.json
  Packs/CortexAttackSurfaceManagement/IncidentFields/incidentfield-ASM_-_Service_Detection.json
  Packs/CortexAttackSurfaceManagement/IncidentFields/incidentfield-ASM_-_Service_Owner.json
  Packs/CortexAttackSurfaceManagement/IncidentFields/incidentfield-ASM_-_Service_Owner_Unranked_Raw.json
  Packs/CortexAttackSurfaceManagement/IncidentFields/incidentfield-ASM_-_System_IDs.json
  Packs/CortexAttackSurfaceManagement/IncidentFields/incidentfield-ASM_-_Tags.json
  Packs/CortexAttackSurfaceManagement/ReleaseNotes/1_6_33.md
  Packs/CortexAttackSurfaceManagement/ReleaseNotes/1_6_37.md
  Packs/CortexAttackSurfaceManagement/pack_metadata.json
Labels: Contribution, docs-approved, Contribution Form Filled, Community, Xsoar Support Level, External PR, Security Review

#28989 Missing dependencies when installing packs
  Tests/Marketplace/Tests/search_and_install_packs_test.py
  Tests/Marketplace/Tests/search_and_unistall_pack_test.py
  Tests/Marketplace/common.py
  Tests/Marketplace/search_and_install_packs.py
  Tests/Marketplace/search_and_uninstall_pack.py
  Tests/private_build/configure_and_test_integration_instances_private.py
  Tests/private_build/tests/test_configure_and_test_integration_instances_private.py
Labels: docs-approved

#29573 Deprecate Picus Community
  Packs/PICUS/Integrations/PICUS/PICUS.yml
  Packs/PICUS/ReleaseNotes/1_0_4.md
  Packs/PICUS/pack_metadata.json
  Packs/PicusNGAutomation/Integrations/PicusNG/PicusNG.yml
  Packs/PicusNGAutomation/ReleaseNotes/1_0_9.md
  Packs/PicusNGAutomation/pack_metadata.json
Labels: docs-approved, Partner-Approved

#29220 Rsa netwitness mirroring
  Packs/RSANetWitness_v11_1/.pack-ignore
  Packs/RSANetWitness_v11_1/.secrets-ignore
  Packs/RSANetWitness_v11_1/CONTRIBUTORS.json
  Packs/RSANetWitness_v11_1/Classifiers/classifier-RSA_NetWitness_v11_5.json
  Packs/RSANetWitness_v11_1/IncidentFields/incidentfield-RSA_Alerts.json
  Packs/RSANetWitness_v11_1/IncidentFields/incidentfield-RSA_Metas_Events.json
  Packs/RSANetWitness_v11_1/IncidentFields/incidentfield-RSA_Raw_Logs_List.json
  Packs/RSANetWitness_v11_1/IncidentTypes/incidenttype-NetWitness_Incident.json
  Packs/RSANetWitness_v11_1/Integrations/RSANetWitness_v11_1/RSANetWitness_v11_1.yml
  Packs/RSANetWitness_v11_1/Integrations/RSANetWitnessv115/README.md
  Packs/RSANetWitness_v11_1/Integrations/RSANetWitnessv115/RSANetWitnessv115.py
  Packs/RSANetWitness_v11_1/Integrations/RSANetWitnessv115/RSANetWitnessv115.yml
  Packs/RSANetWitness_v11_1/Integrations/RSANetWitnessv115/RSANetWitnessv115_test.py
  Packs/RSANetWitness_v11_1/Integrations/RSANetWitnessv115/test_data/command_results.json
  Packs/RSANetWitness_v11_1/Integrations/RSANetWitnessv115/test_data/fetch_incidents.json
  Packs/RSANetWitness_v11_1/Layouts/layoutscontainer-RSA_NetWitness_Layout.json
  Packs/RSANetWitness_v11_1/ReleaseNotes/3_2_0.md
  Packs/RSANetWitness_v11_1/Scripts/RSADisplayMetasEvents/README.md
  Packs/RSANetWitness_v11_1/Scripts/RSADisplayMetasEvents/RSADisplayMetasEvents.py
  Packs/RSANetWitness_v11_1/Scripts/RSADisplayMetasEvents/RSADisplayMetasEvents.yml
  Packs/RSANetWitness_v11_1/Scripts/RSADisplayMetasEvents/RSADisplayMetasEvents_test.py
  Packs/RSANetWitness_v11_1/Scripts/RSAGetRawLog/README.md
  Packs/RSANetWitness_v11_1/Scripts/RSAGetRawLog/RSAGetRawLog.py
  Packs/RSANetWitness_v11_1/Scripts/RSAGetRawLog/RSAGetRawLog.yml
  Packs/RSANetWitness_v11_1/Scripts/RSAGetRawLog/RSAGetRawLog_test.py
  Packs/RSANetWitness_v11_1/Scripts/SetRSANetWitnessAlertsMD/SetRSANetWitnessAlertsMD.py
  Packs/RSANetWitness_v11_1/Scripts/SetRSANetWitnessAlertsMD/SetRSANetWitnessAlertsMD.yml
  Packs/RSANetWitness_v11_1/Scripts/SetRSANetWitnessAlertsMD/SetRSANetWitnessAlertsMD_test.py
  Packs/RSANetWitness_v11_1/pack_metadata.json
Labels: Contribution, docs-approved, ready-for-instance-test, Contribution Form Filled, Community, Xsoar Support Level, External PR, Security Review

#29708 Remove generic-sql-oracle from skipped_tests
  Tests/conf.json
Labels: docs-approved

#29669 Resolved auto
  Packs/CortexXDR/IncidentFields/XDR_Status_v2.json
  Packs/CortexXDR/ReleaseNotes/5_1_7.md
  Packs/CortexXDR/pack_metadata.json
Labels: docs-approved

#29712 Fix Test XDR Playbook general commands TPB
  Packs/CortexXDR/TestPlaybooks/Test_XDR_Playbook_general_commands.yml
Labels: docs-approved

#29688 Wiz v1 2 11
  Packs/Wiz/Integrations/Wiz/Wiz.py
  Packs/Wiz/Integrations/Wiz/Wiz.yml
  Packs/Wiz/ReleaseNotes/1_2_11.md
  Packs/Wiz/pack_metadata.json
Labels: Contribution, Partner, Contribution Form Filled, Partner Support Level, External PR, Partner-Approved

#29549 Sentinelonev2 v3.2.9
  Packs/SentinelOne/Integrations/SentinelOne-V2/README.md
  Packs/SentinelOne/Integrations/SentinelOne-V2/SentinelOne-V2.py
  Packs/SentinelOne/Integrations/SentinelOne-V2/SentinelOne-V2.yml
  Packs/SentinelOne/Integrations/SentinelOneEventCollector/SentinelOneEventCollector.yml
  Packs/SentinelOne/ReleaseNotes/3_2_9.md
  Packs/SentinelOne/pack_metadata.json
Labels: Contribution, Partner, ready-for-instance-test, post-demo, Contribution Form Filled, Partner Support Level, External PR, Partner-Approved

#29689 cisco-meraki-modeling-rules-enhancement
  Packs/cisco-meraki/ModelingRules/CiscoMerakiModelingRules_1_3/CiscoMerakiModelingRules_1_3.xif
  Packs/cisco-meraki/ModelingRules/CiscoMerakiModelingRules_1_3/CiscoMerakiModelingRules_1_3.yml
  Packs/cisco-meraki/ModelingRules/CiscoMerakiModelingRules_1_3/CiscoMerakiModelingRules_1_3_schema.json
  Packs/cisco-meraki/ParsingRules/CiscoMerakiParsingRules/CiscoMerakiParsingRules.xif
  Packs/cisco-meraki/ParsingRules/CiscoMerakiParsingRules/CiscoMerakiParsingRules.yml
  Packs/cisco-meraki/README.md
  Packs/cisco-meraki/ReleaseNotes/1_0_9.md
  Packs/cisco-meraki/pack_metadata.json
Labels: docs-approved

#29683 Kafka Client Certificate Hidden
  Packs/Kafka/Integrations/KafkaV3/KafkaV3.yml
  Packs/Kafka/ReleaseNotes/2_0_16.md
  Packs/Kafka/pack_metadata.json
Labels: docs-approved

#29204 removed release_notes_generator from prepare testing bucket
  .gitlab/ci/.gitlab-ci.instance-test.yml
  .gitlab/ci/.gitlab-ci.on-push.yml
  .gitlab/ci/.gitlab-ci.sdk-nightly.yml
  .gitlab/ci/.gitlab-ci.yml
  Tests/Marketplace/marketplace_services.py
  Tests/scripts/infrastructure_tests/release_notes_handler_test.py
  Utils/release_notes_handler.py
Labels: docs-approved, ForceMerge

#29749 Fixing a test in RSA Netwitness
  Packs/RSANetWitness_v11_1/Integrations/RSANetWitnessv115/RSANetWitnessv115_test.py
Labels: docs-approved

#29699 fix poetry installation under CI
  .hooks/bootstrap
Labels: docs-approved

#29707 Fix slack v3 docs
  Packs/Slack/Integrations/SlackV3/README.md
  Packs/Slack/Integrations/SlackV3/SlackV3.yml
  Packs/Slack/ReleaseNotes/3_2_2.md
  Packs/Slack/Scripts/SlackBlockBuilder/README.md
  Packs/Slack/Scripts/SlackBlockBuilder/SlackBlockBuilder.yml
  Packs/Slack/pack_metadata.json
Labels: docs-approved

#29587 Adding hsts header to nginx
  Packs/ApiModules/Scripts/NGINXApiModule/NGINXApiModule.py
  Packs/ApiModules/Scripts/NGINXApiModule/NGINXApiModule.yml
  Packs/EDL/Integrations/EDL/EDL.yml
  Packs/EDL/ReleaseNotes/3_2_10.md
  Packs/EDL/pack_metadata.json
  Packs/ExportIndicators/Integrations/ExportIndicators/ExportIndicators.yml
  Packs/ExportIndicators/ReleaseNotes/1_0_20.md
  Packs/ExportIndicators/pack_metadata.json
  Packs/TAXIIServer/Integrations/TAXII2Server/TAXII2Server.yml
  Packs/TAXIIServer/ReleaseNotes/2_0_46.md
  Packs/TAXIIServer/pack_metadata.json
  Tests/known_words.txt
Labels: docs-approved, ForceMerge

#29753 update netmiko docker
  Packs/RemoteAccess/Integrations/RemoteAccessv2/RemoteAccessv2.yml
  Packs/RemoteAccess/ReleaseNotes/1_0_30.md
  Packs/RemoteAccess/pack_metadata.json
Labels: docs-approved

#29752 fixing "operation is already in progress" string search
  Tests/Marketplace/common.py
Labels: docs-approved
