Repository demisto/content, pull requests merged in 2023-11, with the labels that each got.

#30596 Update README with correct API version.
  Packs/BluecatAddressManager/Integrations/BluecatAddressManager/README.md
Labels: docs-approved

#30576 [pre-commit] Make not mandatory in Packs supported by the community
  .github/workflows/pre-commit.yml
Labels: docs-approved

#30593 Fix xsiam machine cleanup
  Tests/Marketplace/search_and_uninstall_pack.py
Labels: docs-approved

#30588 Remove the "advanced: true" from one field, and the "see Detailed Instructions (?)" from 3 fields
  Packs/MicrosoftGraphMail/Integrations/MicrosoftGraphListener/MicrosoftGraphListener.yml
  Packs/MicrosoftGraphMail/ReleaseNotes/1_5_20.md
  Packs/MicrosoftGraphMail/pack_metadata.json
Labels: docs-approved

#30608 fix jira convert issues print
  Tests/Marketplace/print_test_modeling_rule_summary.py
  Tests/Marketplace/print_test_playbook_summary.py
  Tests/scripts/common.py
  Tests/scripts/convert_test_modeling_result_to_jira_issues.py
  Tests/scripts/convert_test_playbook_result_to_jira_issues.py
  Tests/scripts/jira_issues.py
  Tests/scripts/test_playbooks_report.py
Labels: docs-approved

#30609 fix merge dev secrets and sync buckets
  .gitlab/ci/.gitlab-ci.bucket-upload.yml
  .gitlab/ci/.gitlab-ci.on-push.yml
Labels: docs-approved

#30379 Fixed Gitlab event collector fetch
  Packs/GitLab/Integrations/GitLabEventCollector/GitLabEventCollector.py
  Packs/GitLab/Integrations/GitLabEventCollector/GitLabEventCollector.yml
  Packs/GitLab/Integrations/GitLabEventCollector/GitLabEventCollector_description.md
  Packs/GitLab/Integrations/GitLabEventCollector/GitLabEventCollector_test.py
  Packs/GitLab/Integrations/GitLabEventCollector/README.md
  Packs/GitLab/ReleaseNotes/2_2_19.md
  Packs/GitLab/pack_metadata.json
Labels: docs-approved, ForceMerge

#30351 Remove checking 6.2 server version
  Packs/AlienVault_OTX/Integrations/AlienVault_OTX_v2/AlienVault_OTX_v2_test.py
  Packs/ApiModules/Scripts/HTTPFeedApiModule/HTTPFeedApiModule_test.py
  Packs/AutoFocus/Integrations/AutofocusV2/AutofocusV2_test.py
  Packs/Base/ReleaseNotes/1_32_41.md
  Packs/Base/Scripts/CommonServerPython/CommonServerPython.py
  Packs/Base/Scripts/CommonServerPython/CommonServerPython_test.py
  Packs/Base/Scripts/CreateIndicatorRelationship/CreateIndicatorRelationship_test.py
  Packs/Base/pack_metadata.json
  Packs/DeveloperTools/TestPlaybooks/playbook-TestCommonPython.yml
  Packs/FeedCrowdstrikeFalconIntel/Integrations/FeedCrowdstrikeFalconIntel/FeedCrowdstrikeFalconIntel_test.py
  Packs/FeedCrowdstrikeFalconIntel/Integrations/FeedCrowdstrikeFalconIntel/test_data/test_data.json
  Packs/Netskope/Integrations/NetskopeAPIv1/NetskopeAPIv1.py
  Packs/Netskope/Integrations/NetskopeAPIv1/NetskopeAPIv1.yml
  Packs/Netskope/ReleaseNotes/3_3_1.md
  Packs/Netskope/pack_metadata.json
  Packs/TAXIIServer/Integrations/TAXII2Server/TAXII2Server_test.py
  Packs/TAXIIServer/Integrations/TAXII2Server/test_data/objects21_no_extention_file.json
  Packs/TAXIIServer/Integrations/TAXII2Server/test_data/objects21_spec_fields_file.json
  Packs/XForceExchange/Integrations/XFE_v2/XFE_v2_test.py
Labels: docs-approved

#30610 Fix for dhcp
  Packs/MicrosoftDHCP/ModelingRules/MicrosoftDHCP_1_3/MicrosoftDHCP_1_3.xif
  Packs/MicrosoftDHCP/ReleaseNotes/1_0_3.md
  Packs/MicrosoftDHCP/pack_metadata.json
Labels: docs-approved

#30497 Xdr lite playbbok
  Packs/CommonTypes/.pack-ignore
  Packs/CommonTypes/IncidentFields/incidentfield-Command_Line_Verdict.json
  Packs/CommonTypes/IncidentFields/incidentfield-High_Risky_Hosts.json
  Packs/CommonTypes/IncidentFields/incidentfield-High_Risky_Users.json
  Packs/CommonTypes/IncidentFields/incidentfield-Number_Of_Found_Related_Alerts.json
  Packs/CommonTypes/ReleaseNotes/3_3_89.md
  Packs/CommonTypes/pack_metadata.json
  Packs/CortexXDR/.pack-ignore
  Packs/CortexXDR/Classifiers/classifier-mapper-incoming-PaloAltoNetworks_CortexXDR.json
  Packs/CortexXDR/IncidentTypes/incidenttype-Cortex_XDR_-_Lite.json
  Packs/CortexXDR/Integrations/CortexXDRIR/CortexXDRIR.yml
  Packs/CortexXDR/Layouts/layoutscontainer-Cortex_XDR_-_Lite.json
  Packs/CortexXDR/Playbooks/playbook-Cortex_XDR_Lite_-_Incident_Handling.yml
  Packs/CortexXDR/Playbooks/playbook-Cortex_XDR_Lite_-_Incident_Handling_README.md
  Packs/CortexXDR/README.md
  Packs/CortexXDR/ReleaseNotes/5_2_4.md
  Packs/CortexXDR/Scripts/CortexXDRInvestigationVerdict/CortexXDRInvestigationVerdict.py
  Packs/CortexXDR/Scripts/CortexXDRInvestigationVerdict/CortexXDRInvestigationVerdict.yml
  Packs/CortexXDR/Scripts/CortexXDRInvestigationVerdict/README.md
  Packs/CortexXDR/TestPlaybooks/Test_XDR_Playbook_execute_script_commands.yml
  Packs/CortexXDR/doc_files/Cortex_XDR_Lite_-_Incident_Handling.png
  Packs/CortexXDR/pack_metadata.json
Labels: docs-approved

#30632 collect_tests: removing unused condition
  Tests/scripts/collect_tests/collect_tests.py
Labels: docs-approved

#30579 OpsGenie v3 - Fix polling commands
  Packs/OpsGenie/Integrations/OpsGenieV3/OpsGenieV3.py
  Packs/OpsGenie/Integrations/OpsGenieV3/OpsGenieV3.yml
  Packs/OpsGenie/Integrations/OpsGenieV3/OpsGenieV3_test.py
  Packs/OpsGenie/ReleaseNotes/2_0_21.md
  Packs/OpsGenie/pack_metadata.json
Labels: docs-approved, release-notes-only

#30532 add a way to upload binary file
  Packs/XSOARFileManagement/Integrations/XSOARFileManagement/XSOARFileManagement.py
  Packs/XSOARFileManagement/Integrations/XSOARFileManagement/XSOARFileManagement.yml
  Packs/XSOARFileManagement/ReleaseNotes/1_0_2.md
  Packs/XSOARFileManagement/pack_metadata.json
Labels: Contribution, pending-demo, Contribution Form Filled, Community, pending-contributor, Community Support Level, External PR

#30048 [ASM] - Expander - Add new case_id_list argument
  Packs/CortexXpanse/Integrations/CortexXpanse/CortexXpanse.py
  Packs/CortexXpanse/Integrations/CortexXpanse/CortexXpanse.yml
  Packs/CortexXpanse/Integrations/CortexXpanse/README.md
  Packs/CortexXpanse/ReleaseNotes/1_0_13.md
  Packs/CortexXpanse/pack_metadata.json
Labels: Contribution, docs-approved, ready-for-instance-test, Contribution Form Filled, Community, Xsoar Support Level, External PR

#30636 temporary fix for finding invalid server version
  Tests/test_content.py
  Tests/tests/configure_and_test_integration_instances_test.py
Labels: docs-approved

#30073 [content-nightly] - install packs from artifacts + use Packs folder from latest upload commit
  .gitlab/ci/.gitlab-ci.global.yml
  Tests/Marketplace/search_and_install_packs.py
  Tests/configure_and_test_integration_instances.py
  Tests/scripts/collect_tests/utils.py
  Tests/scripts/validate.sh
Labels: docs-approved

#30597 Update README.md with XSOAR 8 info
  Packs/CortexDataLake/Integrations/CortexDataLake/README.md
Labels: docs-approved

#30628 Armis Release 116: Updated the authentication mechanism to pass the secret key in the body parameter.
  Packs/Armis/Integrations/Armis/Armis.py
  Packs/Armis/Integrations/Armis/Armis.yml
  Packs/Armis/Integrations/Armis/Armis_test.py
  Packs/Armis/ReleaseNotes/1_1_6.md
  Packs/Armis/pack_metadata.json
Labels: Contribution, docs-approved, Partner, Contribution Form Filled, Partner Support Level, External PR, Partner-Approved

#30364 String-Similiarity-Fix
  Packs/CommonScripts/ReleaseNotes/1_12_39.md
  Packs/CommonScripts/Scripts/StringSimilarity/README.md
  Packs/CommonScripts/Scripts/StringSimilarity/StringSimilarity.py
  Packs/CommonScripts/Scripts/StringSimilarity/StringSimilarity.yml
  Packs/CommonScripts/Scripts/StringSimilarity/StringSimilarity_test.py
  Packs/CommonScripts/pack_metadata.json
Labels: docs-approved

#30589 [Whois] skipped unittest
  Packs/Whois/Integrations/Whois/Whois_test.py
Labels: docs-approved, ForceMerge

#30653 update docs
  Packs/Microsoft365Defender/Integrations/Microsoft365Defender/README.md
Labels: docs-approved

#30539 XSOAR EDL Checker - Add support for XSOAR 8.x - Oct 2023
  Packs/XSOAR_EDL_Checker/Integrations/XSOAREDLChecker/README.md
  Packs/XSOAR_EDL_Checker/Integrations/XSOAREDLChecker/XSOAREDLChecker.py
  Packs/XSOAR_EDL_Checker/Integrations/XSOAREDLChecker/XSOAREDLChecker.yml
  Packs/XSOAR_EDL_Checker/Integrations/XSOAREDLChecker/XSOAREDLChecker_description.md
  Packs/XSOAR_EDL_Checker/Playbooks/JOB_-_XSOAR_EDL_Checker.yml
  Packs/XSOAR_EDL_Checker/ReleaseNotes/1_1_0.md
  Packs/XSOAR_EDL_Checker/pack_metadata.json
Labels: Contribution, Contribution Form Filled, Community, pending-contributor, Community Support Level, External PR, Security Review

#30335 FindSimilar logs
  Packs/Base/ReleaseNotes/1_32_42.md
  Packs/Base/Scripts/DBotFindSimilarIncidents/DBotFindSimilarIncidents.py
  Packs/Base/Scripts/DBotFindSimilarIncidents/DBotFindSimilarIncidents_test.py
  Packs/Base/pack_metadata.json
Labels: docs-approved

#30519 Add is malicious to process Cortex XDR
  Packs/ApiModules/Scripts/CoreIRApiModule/CoreIRApiModule.py
  Packs/Core/ReleaseNotes/2_1_1.md
  Packs/Core/pack_metadata.json
  Packs/CortexXDR/Integrations/CortexXDRIR/CortexXDRIR.yml
  Packs/CortexXDR/Integrations/CortexXDRIR/README.md
  Packs/CortexXDR/ReleaseNotes/5_2_5.md
  Packs/CortexXDR/pack_metadata.json
Labels: docs-approved

#30502 Email regex - Not allowing pipe in local-part first char
  Packs/Base/TestPlaybooks/playbook-Email_extraction_test.yml
  Packs/CommonTypes/IndicatorTypes/reputation-email.json
  Packs/CommonTypes/ReleaseNotes/3_3_90.md
  Packs/CommonTypes/pack_metadata.json
Labels: docs-approved, ForceMerge

#30308 XDR Expandr-3361
  Packs/ApiModules/ReleaseNotes/2_2_21.md
  Packs/ApiModules/Scripts/CoreIRApiModule/CoreIRApiModule.py
  Packs/ApiModules/Scripts/CoreIRApiModule/CoreIRApiModule.yml
  Packs/ApiModules/pack_metadata.json
  Packs/Core/Integrations/CortexCoreIR/CortexCoreIR.yml
  Packs/Core/Integrations/CortexCoreIR/README.md
  Packs/Core/ReleaseNotes/2_1_1.md
  Packs/Core/pack_metadata.json
  Packs/CortexXDR/IncidentTypes/Cortex_XDR_Incident.json
  Packs/CortexXDR/IncidentTypes/Cortex_XDR_Incident_5_9_9.json
  Packs/CortexXDR/IncidentTypes/incidenttype-Cortex_XDR_-_XCLOUD_Cryptomining.json
  Packs/CortexXDR/IncidentTypes/incidenttype-XDR_Device_Control_Violations.json
  Packs/CortexXDR/Integrations/CortexXDRIR/CortexXDRIR.yml
  Packs/CortexXDR/Integrations/CortexXDRIR/README.md
  Packs/CortexXDR/Playbooks/Cortex_XDR_-_Port_Scan_-_Adjusted.yml
  Packs/CortexXDR/Playbooks/Cortex_XDR_Alerts_Handling.yml
  Packs/CortexXDR/Playbooks/Cortex_XDR_incident_handling_v3_6_5.yml
  Packs/CortexXDR/Playbooks/playbook-Cortex_XDR_-_First_SSO_Access.yml
  Packs/CortexXDR/Playbooks/playbook-Cortex_XDR_-_Possible_External_RDP_Brute-Force.yml
  Packs/CortexXDR/Playbooks/playbook-Cortex_XDR_-_PrintNightmare_Detection_and_Response_6_5.yml
  Packs/CortexXDR/Playbooks/playbook-Cortex_XDR_Lite_-_Incident_Handling.yml
  Packs/CortexXDR/Playbooks/playbook-Cortex_XDR_Malware_-_Incident_Enrichment.yml
  Packs/CortexXDR/Playbooks/playbook-Cortex_XDR_Malware_-_Investigation_And_Response.yml
  Packs/CortexXDR/Playbooks/playbook-Cortex_XDR_device_control_violations.yml
  Packs/CortexXDR/ReleaseNotes/5_2_5.md
  Packs/CortexXDR/Scripts/DBotGroupXDRIncidents/DBotGroupXDRIncidents.yml
  Packs/CortexXDR/pack_metadata.json
Labels: Contribution, docs-approved, ready-for-instance-test, pending-demo, post-demo, Contribution Form Filled, Community, Xsoar Support Level, External PR

#30490 [Azure log analytics] Updated docs
  Packs/AzureLogAnalytics/Integrations/AzureLogAnalytics/AzureLogAnalytics.py
  Packs/AzureLogAnalytics/Integrations/AzureLogAnalytics/AzureLogAnalytics.yml
  Packs/AzureLogAnalytics/Integrations/AzureLogAnalytics/AzureLogAnalytics_description.md
  Packs/AzureLogAnalytics/Integrations/AzureLogAnalytics/README.md
  Packs/AzureLogAnalytics/ReleaseNotes/1_1_20.md
  Packs/AzureLogAnalytics/pack_metadata.json
Labels: docs-approved

#30651 [CSP] Lookback: continue to use lookback even if offest is set
  Packs/Base/ReleaseNotes/1_32_43.md
  Packs/Base/Scripts/CommonServerPython/CommonServerPython.py
  Packs/Base/Scripts/CommonServerPython/CommonServerPython_test.py
  Packs/Base/pack_metadata.json
Labels: docs-approved

#30361 Made premium packs free. Added new alert states to the Code42 Check I…
  Packs/Code42/.secrets-ignore
  Packs/Code42/Integrations/Code42/Code42.py
  Packs/Code42/Integrations/Code42/Code42.yml
  Packs/Code42/Integrations/Code42/Code42_test.py
  Packs/Code42/Playbooks/playbook-Code42_Add_Departing_Employee_From_Ticketing_System_v2.yml
  Packs/Code42/Playbooks/playbook-Code42_Add_Departing_Employee_From_Ticketing_System_v2_README.md
  Packs/Code42/Playbooks/playbook-Code42_Check_Incydr_Status_And_Close_XSOAR_Incident.yml
  Packs/Code42/Playbooks/playbook-Code42_Copy_File_To_Ticketing_System_v2.yml
  Packs/Code42/Playbooks/playbook-Code42_Copy_File_To_Ticketing_System_v2_README.md
  Packs/Code42/Playbooks/playbook-Code42_File_Search_v2.yml
  Packs/Code42/Playbooks/playbook-Code42_File_Search_v2_README.md
  Packs/Code42/Playbooks/playbook-Code42_Suspicious_Activity_Action_v2.yml
  Packs/Code42/Playbooks/playbook-Code42_Suspicious_Activity_Action_v2_README.md
  Packs/Code42/Playbooks/playbook-Code42_Suspicious_Activity_Review_v2.yml
  Packs/Code42/Playbooks/playbook-Code42_Suspicious_Activity_Review_v2_README.md
  Packs/Code42/ReleaseNotes/4_0_0.json
  Packs/Code42/ReleaseNotes/4_0_0.md
  Packs/Code42/Scripts/Code42FileEventsToMarkdownTable/Code42FileEventsToMarkdownTable.yml
  Packs/Code42/TestPlaybooks/playbook-Code42-Test.yml
  Packs/Code42/TestPlaybooks/playbook-Code42_Suspicious_Activity_Action_v2_Test.yml
  Packs/Code42/doc_files/Code42_Add_Departing_Employee_From_Ticketing_System_v2.png
  Packs/Code42/doc_files/Code42_Copy_File_To_Ticketing_System_v2.png
  Packs/Code42/doc_files/Code42_File_Search_v2.png
  Packs/Code42/doc_files/Code42_Suspicious_Activity_Action_v2.png
  Packs/Code42/doc_files/Code42_Suspicious_Activity_Review_v2.png
  Packs/Code42/pack_metadata.json
  Tests/conf.json
Labels: Contribution, Partner, ready-for-instance-test, Contribution Form Filled, pending-contributor, Partner Support Level, External PR, Security Review, Partner-Approved

#30668 [trend-micro-vision-one] - update wrong link to search logs
  Packs/TrendMicroVisionOne/Integrations/TrendMicroVisionOneEventCollector/README.md
  Packs/TrendMicroVisionOne/Integrations/TrendMicroVisionOneEventCollector/TrendMicroVisionOneEventCollector_description.md
  Packs/TrendMicroVisionOne/ReleaseNotes/3_0_4.md
  Packs/TrendMicroVisionOne/pack_metadata.json
Labels: docs-approved, Partner-Approved

#30627 [ASM] EXAPNDR-6427 Adding delete context changes
  Packs/CortexAttackSurfaceManagement/.pack-ignore
  Packs/CortexAttackSurfaceManagement/Playbooks/Cortex_ASM_-_ASM_Alert.yml
  Packs/CortexAttackSurfaceManagement/Playbooks/Cortex_ASM_-_ASM_Alert_README.md
  Packs/CortexAttackSurfaceManagement/ReleaseNotes/1_7_10.md
  Packs/CortexAttackSurfaceManagement/doc_files/Cortex_ASM_-_ASM_Alert.png
  Packs/CortexAttackSurfaceManagement/pack_metadata.json
Labels: Contribution, ready-for-instance-test, Contribution Form Filled, Community, Xsoar Support Level, External PR, Security Review

#28708 [Crowdstrike Falcon] Mirroring incidents - severity
  Packs/CrowdStrikeFalcon/Integrations/CrowdStrikeFalcon/CrowdStrikeFalcon.py
  Packs/CrowdStrikeFalcon/Integrations/CrowdStrikeFalcon/CrowdStrikeFalcon.yml
  Packs/CrowdStrikeFalcon/Integrations/CrowdStrikeFalcon/CrowdStrikeFalcon_test.py
  Packs/CrowdStrikeFalcon/Integrations/CrowdStrikeFalcon/test_data/input_data.py
  Packs/CrowdStrikeFalcon/ReleaseNotes/1_12_4.md
  Packs/CrowdStrikeFalcon/TestPlaybooks/playbook-CrowdStrikeFalcon-Test.yml
  Packs/CrowdStrikeFalcon/pack_metadata.json
Labels: docs-approved

#30634 [The Hive] Pre-Commit and format
  Packs/TheHiveProject/Integrations/TheHiveProject/README.md
  Packs/TheHiveProject/Integrations/TheHiveProject/TheHiveProject.py
  Packs/TheHiveProject/Integrations/TheHiveProject/TheHiveProject.yml
  Packs/TheHiveProject/Integrations/TheHiveProject/TheHiveProject_test.py
  Packs/TheHiveProject/ReleaseNotes/1_1_19.md
  Packs/TheHiveProject/pack_metadata.json
Labels: docs-approved

#30500 Fix handle values bug [Google Sheets]
  Packs/GoogleSheets/Integrations/GoogleSheets/GoogleSheets.py
  Packs/GoogleSheets/Integrations/GoogleSheets/GoogleSheets_test.py
  Packs/GoogleSheets/ReleaseNotes/1_0_36.md
  Packs/GoogleSheets/pack_metadata.json
Labels: docs-approved

#30615 improve email squatting script faster
  Packs/CommonScripts/ReleaseNotes/1_12_40.md
  Packs/CommonScripts/Scripts/EmailDomainSquattingReputation/EmailDomainSquattingReputation.js
  Packs/CommonScripts/Scripts/EmailDomainSquattingReputation/EmailDomainSquattingReputation.yml
  Packs/CommonScripts/pack_metadata.json
Labels: docs-approved

#30509 Splitting prepare-testing-bucket output to be per server type
  .gitlab/ci/.gitlab-ci.bucket-upload.yml
  .gitlab/ci/.gitlab-ci.build-machines-cleanup.yml
  .gitlab/ci/.gitlab-ci.global.yml
  .gitlab/ci/.gitlab-ci.on-push.yml
  .gitlab/ci/.gitlab-ci.sdk-nightly.yml
  .gitlab/ci/.gitlab-ci.variables.yml
  Tests/Marketplace/configure_and_install_packs.py
  Tests/Marketplace/download_private_id_set.py
  Tests/Marketplace/install_packs.sh
  Tests/Marketplace/private_build_prepare_for_testing.py
  Tests/Marketplace/upload_packs.py
  Tests/configure_and_test_integration_instances.py
  Tests/instance_notifier.py
  Tests/private_build/upload_packs_private.py
  Tests/scripts/collect_tests/path_manager.py
  Tests/scripts/destroy_instances.py
  Tests/scripts/download_conf_repos.sh
  Tests/scripts/extract_content_test_conf.py
  Tests/scripts/find_pack_dependencies_changes.py
  Tests/scripts/gitlab_slack_notifier.py
  Tests/scripts/infrastructure_tests/gitlab_client_test.py
  Tests/scripts/install_content_and_test_integrations.sh
  Tests/scripts/prepare_content_packs_for_testing.sh
  Tests/scripts/prepare_private_content_packs_for_testing.sh
  Tests/scripts/reinstall_packs_on_cloud_instances.sh
  Tests/scripts/run_private_build_tests.sh
  Tests/scripts/test_modeling_rules.sh
  Tests/scripts/uninstall_packs_and_reset_bucket_cloud.sh
  Tests/scripts/upload_artifacts.sh
  Tests/scripts/utils/compare_staging_graph.py
  Tests/scripts/wait_until_server_ready.py
  Tests/test_content.py
  Tests/tests/configure_and_test_integration_instances_test.py
  Utils/release_notes_generator.py
  Utils/trigger_nightly_sdk_build.sh
Labels: docs-approved

#30650 [CS Falcon] Use date format with fractional seconds in detections fetch
  Packs/CrowdStrikeFalcon/Integrations/CrowdStrikeFalcon/CrowdStrikeFalcon.py
  Packs/CrowdStrikeFalcon/Integrations/CrowdStrikeFalcon/CrowdStrikeFalcon_test.py
  Packs/CrowdStrikeFalcon/ReleaseNotes/1_12_5.md
  Packs/CrowdStrikeFalcon/pack_metadata.json
Labels: docs-approved

#30695 Tenable IO Update
  Packs/Tenable_io/ModelingRules/TenableioEventCollector_1_3/TenableioEventCollector_1_3_schema.json
  Packs/Tenable_io/ReleaseNotes/2_1_14.md
  Packs/Tenable_io/pack_metadata.json
Labels: docs-approved

#30343 Claroty-CTD-Modeling-Rules-CIAC-7022
  Packs/Claroty/.pack-ignore
  Packs/Claroty/ModelingRules/Claroty/Claroty.xif
  Packs/Claroty/ModelingRules/Claroty/Claroty.yml
  Packs/Claroty/ModelingRules/Claroty/Claroty_schema.json
  Packs/Claroty/README.md
  Packs/Claroty/ReleaseNotes/1_0_26.md
  Packs/Claroty/pack_metadata.json
Labels: docs-approved

#30664 Edl enhancements
  Packs/EDL/Integrations/EDL/EDL.yml
  Packs/EDL/ReleaseNotes/3_2_13.md
  Packs/EDL/pack_metadata.json
Labels: docs-approved

#30703 fixing the check validating build files are up to date
  .gitlab/ci/.gitlab-ci.global.yml
Labels: docs-approved

#29564 [PAN-OS] Add the capability to export a TSF
  Packs/PAN-OS/Integrations/Panorama/Panorama.py
  Packs/PAN-OS/Integrations/Panorama/Panorama.yml
  Packs/PAN-OS/Integrations/Panorama/README.md
  Packs/PAN-OS/Integrations/Panorama/command_examples.txt
  Packs/PAN-OS/ReleaseNotes/2_1_12.md
  Packs/PAN-OS/doc_files/PAN-OS_-_Export_Tech_Support_File.png
  Packs/PAN-OS/pack_metadata.json
Labels: Contribution, ready-for-instance-test, post-demo, Contribution Form Filled, Community, pending-contributor, Xsoar Support Level, External PR, Security Review

#30711 fix bucket upload
  .gitlab/ci/.gitlab-ci.bucket-upload.yml
Labels: docs-approved

#30583 SysAid add get file
  Packs/SysAid/Integrations/SysAid/README.md
  Packs/SysAid/Integrations/SysAid/SysAid.py
  Packs/SysAid/Integrations/SysAid/SysAid.yml
  Packs/SysAid/Integrations/SysAid/SysAid_test.py
  Packs/SysAid/ReleaseNotes/1_0_13.md
  Packs/SysAid/pack_metadata.json
Labels: Contribution, ready-for-instance-test, pending-demo, Contribution Form Filled, Community, pending-contributor, Xsoar Support Level, External PR

#30708 change arg split to argToList
  Packs/ThreatConnect/Integrations/ThreatConnectV3/ThreatConnectV3.py
  Packs/ThreatConnect/Integrations/ThreatConnectV3/ThreatConnectV3.yml
  Packs/ThreatConnect/Integrations/ThreatConnectV3/ThreatConnectV3_test.py
  Packs/ThreatConnect/ReleaseNotes/3_0_14.md
  Packs/ThreatConnect/pack_metadata.json
Labels: docs-approved

#30700 MicrosoftDefenderAdvancedThreatProtection - fix TPB
  Packs/MicrosoftDefenderAdvancedThreatProtection/TestPlaybooks/playbook-Microsoft_Defender_Advanced_Threat_Protection-Test.yml
Labels: docs-approved

#30336 Add support GetDataCollectionLink for xsoar8 and XSIAM
  Packs/CommonScripts/ReleaseNotes/1_12_41.md
  Packs/CommonScripts/Scripts/GetDataCollectionLink/GetDataCollectionLink.py
  Packs/CommonScripts/Scripts/GetDataCollectionLink/GetDataCollectionLink.yml
  Packs/CommonScripts/Scripts/GetDataCollectionLink/GetDataCollectionLink_test.py
  Packs/CommonScripts/pack_metadata.json
Labels: docs-approved

#30654 Clean Needed URLs
  Packs/ApiModules/.secrets-ignore
  Packs/ArcSightESM/Integrations/ArcSightESMv2/README.md
  Packs/Base/Scripts/DBotSuggestClassifierMapping/TestData/arcsight.json
  Packs/Base/Scripts/DBotSuggestClassifierMapping/TestData/splunk.json
  Packs/BigFix/Integrations/BigFix/README.md
  Packs/CadoResponse/.secrets-ignore
  Packs/CarbonBlackProtect/.secrets-ignore
  Packs/CarbonBlackProtect/Integrations/CarbonBlackProtect/CarbonBlackProtect_test.py
  Packs/ExpanseV2/Scripts/ExpansePrintSuggestions/test_data/output.md
  Packs/ExpanseV2/Scripts/ExpansePrintSuggestions/test_data/prisma_cloud.json
  Packs/HPEArubaClearPass/Integrations/HPEArubaClearPass/test_data/attributes_list_response.json
  Packs/MicrosoftAdvancedThreatAnalytics/Integrations/MicrosoftAdvancedThreatAnalytics/README.md
  Packs/MicrosoftAdvancedThreatAnalytics/Integrations/MicrosoftAdvancedThreatAnalytics/test_data/suspicious_activity.json
  Packs/MicrosoftAdvancedThreatAnalytics/Integrations/MicrosoftAdvancedThreatAnalytics/test_data/suspicious_activity_details.json
  Packs/NetscoutArborSightline/Integrations/NetscoutArborSightline/NetscoutArborSightline_test.py
  Packs/NetscoutArborSightline/Integrations/NetscoutArborSightline/README.md
  Packs/NetscoutArborSightline/Integrations/NetscoutArborSightline/test_data/command_results.json
  Packs/NetscoutArborSightline/Integrations/NetscoutArborSightline/test_data/http_responses.json
  Packs/PrismaCloud/.secrets-ignore
  Packs/PrismaCloud/Integrations/RedLock/README.md
  Packs/PrismaCloud/Scripts/PrismaCloudAttribution/PrismaCloudAttribution_test.py
  Packs/PrismaCloud/Scripts/PrismaCloudAttribution/README.md
  Packs/PrismaCloud/Scripts/PrismaCloudAttribution/test_data/assets.json
  Packs/QRadar/Integrations/QRadar_v2/QRadar_v2_test.py
  Packs/QRadar/Integrations/QRadar_v2/README.md
  Packs/QRadar/Integrations/QRadar_v2/TestData/commands_outputs.json
  Packs/QRadar/Integrations/QRadar_v2/TestData/raw_responses.json
  Packs/QRadar/Integrations/QRadar_v3/README.md
  Packs/Rapid7_Nexpose/Integrations/Rapid7_Nexpose/test_data/api_mock/client_search_assets.json
  Packs/Rapid7_Nexpose/Integrations/Rapid7_Nexpose/test_data/expected_context/search_assets_command.json
  Packs/Tenable_io/.secrets-ignore
  Packs/Troubleshoot/Scripts/CertificatesTroubleshoot/README.md
  Tests/secrets_white_list.json
Labels: docs-approved

#30322 [ASM] - EXPANDER - 4378 - NotificationTicketType Input for ServiceNow
  Packs/CortexAttackSurfaceManagement/Playbooks/Cortex_ASM_-_ASM_Alert.yml
  Packs/CortexAttackSurfaceManagement/Playbooks/Cortex_ASM_-_ASM_Alert_README.md
  Packs/CortexAttackSurfaceManagement/Playbooks/Cortex_ASM_-_ServiceNow_Notification.yml
  Packs/CortexAttackSurfaceManagement/Playbooks/Cortex_ASM_-_ServiceNow_Notification_README.md
  Packs/CortexAttackSurfaceManagement/ReleaseNotes/1_7_7.md
Labels: Contribution, Contribution Form Filled, Community, Xsoar Support Level, External PR, Security Review

#30719 [Upload Flow Ref] Remove detect_modified
  Tests/Marketplace/Tests/marketplace_services_test.py
  Tests/Marketplace/marketplace_constants.py
  Tests/Marketplace/marketplace_services.py
  Tests/Marketplace/upload_packs.py
Labels: docs-approved

#30381 ImageOCR Docker Image
  Packs/ImageOCR/Integrations/ImageOCR/ImageOCR.yml
  Packs/ImageOCR/ReleaseNotes/1_1_20.md
  Packs/ImageOCR/pack_metadata.json
Labels: docs-approved, ForceMerge

#30721 [UploadFlow Ref] Remove filter by modified files
  Tests/Marketplace/Tests/marketplace_services_test.py
  Tests/Marketplace/marketplace_services.py
  Tests/Marketplace/upload_packs.py
Labels: docs-approved

#30667 [Upload Flow Ref] Remove filtering packs by marketplace
  Tests/Marketplace/upload_packs.py
  Utils/test_upload_flow/TestUploadFlowXSOAR/.pack-ignore
  Utils/test_upload_flow/TestUploadFlowXSOAR/.secrets-ignore
  Utils/test_upload_flow/TestUploadFlowXSOAR/Integrations/TestUploadFlowXSOAR/README.md
  Utils/test_upload_flow/TestUploadFlowXSOAR/Integrations/TestUploadFlowXSOAR/TestUploadFlowXSOAR.py
  Utils/test_upload_flow/TestUploadFlowXSOAR/Integrations/TestUploadFlowXSOAR/TestUploadFlowXSOAR.yml
  Utils/test_upload_flow/TestUploadFlowXSOAR/Integrations/TestUploadFlowXSOAR/TestUploadFlowXSOAR_description.md
  Utils/test_upload_flow/TestUploadFlowXSOAR/Integrations/TestUploadFlowXSOAR/TestUploadFlowXSOAR_image.png
  Utils/test_upload_flow/TestUploadFlowXSOAR/Integrations/TestUploadFlowXSOAR/TestUploadFlowXSOAR_test.py
  Utils/test_upload_flow/TestUploadFlowXSOAR/README.md
  Utils/test_upload_flow/TestUploadFlowXSOAR/pack_metadata.json
  Utils/test_upload_flow/create_test_branch.py
  Utils/test_upload_flow/verify_bucket.py
Labels: docs-approved

#30706 Windows Firewall Events Mapping
  Packs/MicrosoftWindowsEvents/ModelingRules/MicrosoftWindowsEvents_1_3/MicrosoftWindowsEvents_1_3.xif
  Packs/MicrosoftWindowsEvents/README.md
  Packs/MicrosoftWindowsEvents/ReleaseNotes/1_1_4.md
  Packs/MicrosoftWindowsEvents/pack_metadata.json
Labels: docs-approved

#30730 fixing destroy instance
  Tests/scripts/destroy_instances.py
Labels: docs-approved

#30722 [validate] - prev-ver should be origin/master on custom branches
  Tests/scripts/validate.sh
Labels: docs-approved

#30626 SentinelOne v 3 2 12
  Packs/SentinelOne/Classifiers/classifier-SentinelOne_Incident_Classifier.json
  Packs/SentinelOne/Integrations/SentinelOne-V2/SentinelOne-V2.py
  Packs/SentinelOne/Integrations/SentinelOne-V2/SentinelOne-V2.yml
  Packs/SentinelOne/ReleaseNotes/3_2_12.md
  Packs/SentinelOne/pack_metadata.json
Labels: Contribution, Partner, Contribution Form Filled, Partner Support Level, External PR, Security Review, Partner-Approved

#30743 QRadar: update conf file with instance name
  Tests/conf.json
Labels: docs-approved

#30728 Clean Needed URLs - 2
  Packs/CadoResponse/.secrets-ignore
  Packs/Jira/Integrations/JiraV3/test_data/fetch_incidents_test/issue_incident.json
  Packs/Jira/Integrations/JiraV3/test_data/get_issue_query_test/raw_response.json
  Packs/Jira/Integrations/JiraV3/test_data/get_issue_test/parsed_result.json
  Packs/Jira/Integrations/JiraV3/test_data/get_issue_test/raw_response.json
  Packs/Jira/Integrations/JiraV3/test_data/get_issue_test/raw_response_extended_issues.json
  Packs/Jira/Integrations/JiraV3/test_data/get_specific_field_test/parsed_result.json
  Packs/Jira/Integrations/JiraV3/test_data/get_specific_field_test/raw_response.json
  Packs/Jira/Integrations/JiraV3/test_data/issue_query_test/raw_response.json
  Packs/Jira/Integrations/JiraV3/test_data/parsed_issue_custom_fields.json
  Packs/Troubleshoot/Scripts/CertificatesTroubleshoot/README.md
  Packs/Use_Case_Builder/.secrets-ignore
Labels: docs-approved

#30507 ReversingLabs v2.4.0
  Packs/ReversingLabs_Titanium_Cloud/.secrets-ignore
  Packs/ReversingLabs_Titanium_Cloud/Integrations/ReversingLabsTitaniumCloudv2/README.md
  Packs/ReversingLabs_Titanium_Cloud/Integrations/ReversingLabsTitaniumCloudv2/ReversingLabsTitaniumCloudv2.py
  Packs/ReversingLabs_Titanium_Cloud/Integrations/ReversingLabsTitaniumCloudv2/ReversingLabsTitaniumCloudv2.yml
  Packs/ReversingLabs_Titanium_Cloud/Integrations/ReversingLabsTitaniumCloudv2/ReversingLabsTitaniumCloudv2_test.py
  Packs/ReversingLabs_Titanium_Cloud/Integrations/ReversingLabsTitaniumCloudv2/command_examples.txt
  Packs/ReversingLabs_Titanium_Cloud/Integrations/ReversingLabsTitaniumCloudv2/test_data/domain_downloaded_files.json
  Packs/ReversingLabs_Titanium_Cloud/Integrations/ReversingLabsTitaniumCloudv2/test_data/domain_downloaded_files_context.json
  Packs/ReversingLabs_Titanium_Cloud/Integrations/ReversingLabsTitaniumCloudv2/test_data/domain_related_domains.json
  Packs/ReversingLabs_Titanium_Cloud/Integrations/ReversingLabsTitaniumCloudv2/test_data/domain_related_domains_context.json
  Packs/ReversingLabs_Titanium_Cloud/Integrations/ReversingLabsTitaniumCloudv2/test_data/domain_report.json
  Packs/ReversingLabs_Titanium_Cloud/Integrations/ReversingLabsTitaniumCloudv2/test_data/domain_report_context.json
  Packs/ReversingLabs_Titanium_Cloud/Integrations/ReversingLabsTitaniumCloudv2/test_data/domain_to_ip.json
  Packs/ReversingLabs_Titanium_Cloud/Integrations/ReversingLabsTitaniumCloudv2/test_data/domain_to_ip_context.json
  Packs/ReversingLabs_Titanium_Cloud/Integrations/ReversingLabsTitaniumCloudv2/test_data/domain_urls.json
  Packs/ReversingLabs_Titanium_Cloud/Integrations/ReversingLabsTitaniumCloudv2/test_data/domain_urls_context.json
  Packs/ReversingLabs_Titanium_Cloud/Integrations/ReversingLabsTitaniumCloudv2/test_data/ip_downloaded_files.json
  Packs/ReversingLabs_Titanium_Cloud/Integrations/ReversingLabsTitaniumCloudv2/test_data/ip_downloaded_files_context.json
  Packs/ReversingLabs_Titanium_Cloud/Integrations/ReversingLabsTitaniumCloudv2/test_data/ip_report.json
  Packs/ReversingLabs_Titanium_Cloud/Integrations/ReversingLabsTitaniumCloudv2/test_data/ip_report_context.json
  Packs/ReversingLabs_Titanium_Cloud/Integrations/ReversingLabsTitaniumCloudv2/test_data/ip_to_domain.json
  Packs/ReversingLabs_Titanium_Cloud/Integrations/ReversingLabsTitaniumCloudv2/test_data/ip_to_domain_context.json
  Packs/ReversingLabs_Titanium_Cloud/Integrations/ReversingLabsTitaniumCloudv2/test_data/ip_urls.json
  Packs/ReversingLabs_Titanium_Cloud/Integrations/ReversingLabsTitaniumCloudv2/test_data/ip_urls_context.json
  Packs/ReversingLabs_Titanium_Cloud/Integrations/ReversingLabsTitaniumCloudv2/test_data/network_reputation.json
  Packs/ReversingLabs_Titanium_Cloud/Integrations/ReversingLabsTitaniumCloudv2/test_data/network_reputation_context.json
  Packs/ReversingLabs_Titanium_Cloud/ReleaseNotes/2_4_0.md
  Packs/ReversingLabs_Titanium_Cloud/pack_metadata.json
Labels: Contribution, docs-approved, Partner, ready-for-instance-test, post-demo, Contribution Form Filled, pending-contributor, Partner Support Level, External PR, Partner-Approved

#30292 Bug fixes and enchancements in integration
  Packs/CybleEventsV2/Classifiers/classifier-CybleEventsv2-Incoming-Mapper.json
  Packs/CybleEventsV2/Classifiers/classifier-CybleEventsv2-Outgoing-Mapper.json
  Packs/CybleEventsV2/IncidentFields/incidentfield-Application.json
  Packs/CybleEventsV2/IncidentFields/incidentfield-CE_Filename.json
  Packs/CybleEventsV2/IncidentFields/incidentfield-CE_Username.json
  Packs/CybleEventsV2/IncidentFields/incidentfield-Card_Brand.json
  Packs/CybleEventsV2/IncidentFields/incidentfield-Card_CVV.json
  Packs/CybleEventsV2/IncidentFields/incidentfield-Card_Expiry.json
  Packs/CybleEventsV2/IncidentFields/incidentfield-Card_Level.json
  Packs/CybleEventsV2/IncidentFields/incidentfield-Card_No.json
  Packs/CybleEventsV2/IncidentFields/incidentfield-Card_Type.json
  Packs/CybleEventsV2/IncidentFields/incidentfield-Keyword.json
  Packs/CybleEventsV2/IncidentFields/incidentfield-Password.json
  Packs/CybleEventsV2/IncidentFields/incidentfield-URL.json
  Packs/CybleEventsV2/IncidentTypes/incidenttype-Cyble_Vision_Alert_V2.json
  Packs/CybleEventsV2/Integrations/CybleEventsV2/CybleEventsV2.py
  Packs/CybleEventsV2/Integrations/CybleEventsV2/CybleEventsV2.yml
  Packs/CybleEventsV2/Integrations/CybleEventsV2/CybleEventsV2_description.md
  Packs/CybleEventsV2/Integrations/CybleEventsV2/CybleEventsV2_test.py
  Packs/CybleEventsV2/Integrations/CybleEventsV2/README.md
  Packs/CybleEventsV2/Integrations/CybleEventsV2/test_data/dummy_update_incident.json
  Packs/CybleEventsV2/Layouts/layoutscontainer-Cyble_Vision_Alert_V2.json
  Packs/CybleEventsV2/ReleaseNotes/1_0_2.md
  Packs/CybleEventsV2/doc_files/Cyble_Vision_Alert_V2.png
  Packs/CybleEventsV2/doc_files/Cyble_Vision_Alert_V2_Wed_Apr_26_2023.png
  Packs/CybleEventsV2/pack_metadata.json
Labels: Contribution, docs-approved, Partner, Contribution Form Filled, Partner Support Level, External PR, Security Review, Partner-Approved

#30739 terminate old machines of stopped pipelines
  .gitlab/ci/.gitlab-ci.on-push.yml
  Tests/scripts/gcp_instances.py
  Tests/scripts/stop_running_pipeline.py
Labels: docs-approved

#30749 fix prepare_content_packs_for_testing.sh
  .gitlab/ci/.gitlab-ci.bucket-upload.yml
  .gitlab/ci/.gitlab-ci.build-machines-cleanup.yml
  Tests/scripts/prepare_content_packs_for_testing.sh
  Tests/scripts/uninstall_packs_and_reset_bucket_cloud.sh
Labels: docs-approved

#30714 convert jira issues - removing backward compatible, adding links
  .gitlab/ci/.gitlab-ci.global.yml
  .gitlab/ci/.gitlab-ci.on-push.yml
  Tests/Marketplace/print_test_modeling_rule_summary.py
  Tests/Marketplace/print_test_playbook_summary.py
  Tests/scripts/common.py
  Tests/scripts/convert_test_modeling_result_to_jira_issues.py
  Tests/scripts/convert_test_playbook_result_to_jira_issues.py
  Tests/scripts/gitlab_slack_notifier.py
  Tests/scripts/jira_issues.py
  Tests/scripts/test_modeling_rule_report.py
  Tests/scripts/test_playbooks_report.py
Labels: docs-approved

#30666 [Versa Director] Updade request headers
  Packs/VersaDirector/Integrations/VersaDirector/VersaDirector.py
  Packs/VersaDirector/Integrations/VersaDirector/VersaDirector.yml
  Packs/VersaDirector/Integrations/VersaDirector/VersaDirector_test.py
  Packs/VersaDirector/Integrations/VersaDirector/test_data/input_data.py
  Packs/VersaDirector/ReleaseNotes/1_0_6.md
  Packs/VersaDirector/pack_metadata.json
Labels: docs-approved

#30755 QRadar: update conf file with instance name
  Tests/conf.json
Labels: docs-approved

#30534 XSOAR Simple Dev to Prod Update - Oct 2023
  Packs/XSOAR-SimpleDevToProd/.pack-ignore
  Packs/XSOAR-SimpleDevToProd/IncidentFields/incidentfield-XSOAR_Dev_Instance_Name.json
  Packs/XSOAR-SimpleDevToProd/IncidentFields/incidentfield-XSOAR_Dev_to_Prod_Method.json
  Packs/XSOAR-SimpleDevToProd/IncidentFields/incidentfield-XSOAR_Prod_Instance_Name.json
  Packs/XSOAR-SimpleDevToProd/IncidentTypes/incidenttype-XSOAR_Dev_to_Prod.json
  Packs/XSOAR-SimpleDevToProd/Layouts/layoutscontainer-XSOAR_Dev_to_Prod.json
  Packs/XSOAR-SimpleDevToProd/Playbooks/playbook-JOB_-_XSOAR_-_Export_Selected_Custom_Content.yml
  Packs/XSOAR-SimpleDevToProd/Playbooks/playbook-JOB_-_XSOAR_-_Export_Selected_Custom_Content_README.md
  Packs/XSOAR-SimpleDevToProd/Playbooks/playbook-JOB_-_XSOAR_-_Simple_Dev_to_Prod.yml
  Packs/XSOAR-SimpleDevToProd/Playbooks/playbook-JOB_-_XSOAR_-_Simple_Dev_to_Prod_README.md
  Packs/XSOAR-SimpleDevToProd/README.md
  Packs/XSOAR-SimpleDevToProd/ReleaseNotes/1_0_6.md
  Packs/XSOAR-SimpleDevToProd/Scripts/CustomContentBundleWizardry/CustomContentBundleWizardry.yml
  Packs/XSOAR-SimpleDevToProd/Scripts/CustomContentBundleWizardry/README.md
  Packs/XSOAR-SimpleDevToProd/Scripts/IsDemistoRestAPIInstanceAvailable/IsDemistoRestAPIInstanceAvailable.py
  Packs/XSOAR-SimpleDevToProd/Scripts/IsDemistoRestAPIInstanceAvailable/IsDemistoRestAPIInstanceAvailable.yml
  Packs/XSOAR-SimpleDevToProd/Scripts/IsDemistoRestAPIInstanceAvailable/README.md
  Packs/XSOAR-SimpleDevToProd/pack_metadata.json
Labels: Contribution, docs-approved, ready-for-instance-test, Contribution Form Filled, Community, pending-contributor, Community Support Level, External PR, Security Review

#30599 SNOW add custom resolution code parameter
  Packs/ServiceNow/Integrations/ServiceNowv2/README.md
  Packs/ServiceNow/Integrations/ServiceNowv2/ServiceNowv2.py
  Packs/ServiceNow/Integrations/ServiceNowv2/ServiceNowv2.yml
  Packs/ServiceNow/Integrations/ServiceNowv2/ServiceNowv2_test.py
  Packs/ServiceNow/ReleaseNotes/2_5_45.md
  Packs/ServiceNow/pack_metadata.json
Labels: docs-approved

#27619 Google chrome pack
  Packs/GoogleChrome/.pack-ignore
  Packs/GoogleChrome/.secrets-ignore
  Packs/GoogleChrome/CorrelationRules/GoogleChrome_-_Chrome_Extension_Install_Event.yml
  Packs/GoogleChrome/CorrelationRules/GoogleChrome_-_Known_Malicious_Site_Visit.yml
  Packs/GoogleChrome/CorrelationRules/GoogleChrome_-_Known_Malware_Downloaded.yml
  Packs/GoogleChrome/CorrelationRules/GoogleChrome_-_User_Phished_or_Password_Re-useorBreach_event.yml
  Packs/GoogleChrome/ModelingRules/GoogleChrome/GoogleChrome.xif
  Packs/GoogleChrome/ModelingRules/GoogleChrome/GoogleChrome.yml
  Packs/GoogleChrome/ModelingRules/GoogleChrome/GoogleChrome_schema.json
  Packs/GoogleChrome/ParsingRules/GoogleChrome/GoogleChrome.xif
  Packs/GoogleChrome/ParsingRules/GoogleChrome/GoogleChrome.yml
  Packs/GoogleChrome/README.md
  Packs/GoogleChrome/XSIAMDashboards/GoogleChrome_Dashboard.json
  Packs/GoogleChrome/XSIAMDashboards/GoogleChrome_Dashboard_image.png
  Packs/GoogleChrome/pack_metadata.json
Labels: docs-approved, stale-branch

#30631 Okta event collector refactor
  Packs/Okta/Integrations/OktaEventCollector/OktaEventCollector.py
  Packs/Okta/Integrations/OktaEventCollector/OktaEventCollector.yml
  Packs/Okta/Integrations/OktaEventCollector/OktaEventCollector_test.py
  Packs/Okta/ReleaseNotes/3_2_3.md
  Packs/Okta/pack_metadata.json
Labels: docs-approved, ForceMerge

#30731 Ms ecm enhancement
  Packs/MicrosoftECM/ModelingRules/MicrosoftECM_1_3/MicrosoftECM_1_3.xif
  Packs/MicrosoftECM/ModelingRules/MicrosoftECM_1_3/MicrosoftECM_1_3_schema.json
  Packs/MicrosoftECM/ReleaseNotes/1_0_9.md
  Packs/MicrosoftECM/pack_metadata.json
Labels: docs-approved

#30770 Rapid7 IntSight Adoption complete
  Packs/IntSight/Author_image.png
  Packs/IntSight/README.md
  Packs/IntSight/ReleaseNotes/3_0_7.md
  Packs/IntSight/pack_metadata.json
Labels: Contribution, Partner, Contribution Form Filled, Partner Support Level, External PR, Partner-Approved

#30764 [RTIR] Improving the description
  Packs/RTIR/Integrations/RTIR/RTIR.yml
  Packs/RTIR/Integrations/RTIR/RTIR_description.md
  Packs/RTIR/ReleaseNotes/1_0_19.md
  Packs/RTIR/pack_metadata.json
Labels: docs-approved

#30185 [Azure Firewall] Support altering/Multiple Subscription IDs, Resource Group
  Packs/AzureFirewall/Integrations/AzureFirewall/AzureFirewall.py
  Packs/AzureFirewall/Integrations/AzureFirewall/AzureFirewall.yml
  Packs/AzureFirewall/Integrations/AzureFirewall/AzureFirewall_test.py
  Packs/AzureFirewall/Integrations/AzureFirewall/README.md
  Packs/AzureFirewall/Integrations/AzureFirewall/test_data/resource_group_list.json
  Packs/AzureFirewall/Integrations/AzureFirewall/test_data/subscriptions_list.json
  Packs/AzureFirewall/ReleaseNotes/1_1_32.md
  Packs/AzureFirewall/pack_metadata.json
Labels: ForceMerge

#30693 [Azure Log Analytics] Support altering/Multiple Subscription IDs, Resource Group
  Packs/AzureLogAnalytics/Integrations/AzureLogAnalytics/AzureLogAnalytics.py
  Packs/AzureLogAnalytics/Integrations/AzureLogAnalytics/AzureLogAnalytics.yml
  Packs/AzureLogAnalytics/Integrations/AzureLogAnalytics/AzureLogAnalytics_test.py
  Packs/AzureLogAnalytics/Integrations/AzureLogAnalytics/README.md
  Packs/AzureLogAnalytics/Integrations/AzureLogAnalytics/test_data/resource_group_list.json
  Packs/AzureLogAnalytics/Integrations/AzureLogAnalytics/test_data/subscriptions_list.json
  Packs/AzureLogAnalytics/Integrations/AzureLogAnalytics/test_data/workspace_list.json
  Packs/AzureLogAnalytics/ReleaseNotes/1_1_21.md
  Packs/AzureLogAnalytics/pack_metadata.json
Labels: docs-approved

#30511 Ataya integration
  Packs/Ataya/.pack-ignore
  Packs/Ataya/.secrets-ignore
  Packs/Ataya/Author_image.png
  Packs/Ataya/Classifiers/classifier-Ataya_-_Incoming_Mapper.json
  Packs/Ataya/IncidentFields/incidentfield-Ataya_ID.json
  Packs/Ataya/IncidentFields/incidentfield-Ataya_IMEI.json
  Packs/Ataya/IncidentFields/incidentfield-Ataya_IMSI.json
  Packs/Ataya/IncidentTypes/incidenttype-Ataya.json
  Packs/Ataya/Integrations/Ataya/Ataya.py
  Packs/Ataya/Integrations/Ataya/Ataya.yml
  Packs/Ataya/Integrations/Ataya/Ataya_description.md
  Packs/Ataya/Integrations/Ataya/Ataya_image.png
  Packs/Ataya/Integrations/Ataya/Ataya_test.py
  Packs/Ataya/Integrations/Ataya/README.md
  Packs/Ataya/Integrations/Ataya/command_examples
  Packs/Ataya/Layouts/layoutscontainer-Ataya_Incident_Layout.json
  Packs/Ataya/Playbooks/Ataya_-_Securely_logging_device_access_to_network.yml
  Packs/Ataya/Playbooks/Ataya_-_Securely_logging_device_access_to_network_README.md
  Packs/Ataya/README.md
  Packs/Ataya/doc_files/Ataya_-_Securely_logging_device_access_to_network.png
  Packs/Ataya/pack_metadata.json
Labels: Contribution, Partner, ready-for-instance-test, post-demo, Contribution Form Filled, pending-contributor, Partner Support Level, External PR, Security Review, Partner-Approved

#30768 Infoblox Update
  Packs/Infoblox/ParsingRules/InfobloxParsingRules/InfobloxParsingRules.xif
  Packs/Infoblox/README.md
  Packs/Infoblox/ReleaseNotes/1_0_18.md
  Packs/Infoblox/pack_metadata.json
Labels: docs-approved

#30738 [UploadFlow Ref] Remove check_if_exists_in_index
  Tests/Marketplace/upload_packs.py
Labels: docs-approved

#30773 change test when state argument is missing
  Packs/ProofpointThreatResponse/Integrations/ProofpointThreatResponse/ProofpointThreatResponse.py
  Packs/ProofpointThreatResponse/Integrations/ProofpointThreatResponse/ProofpointThreatResponse.yml
  Packs/ProofpointThreatResponse/ReleaseNotes/2_0_15.md
  Packs/ProofpointThreatResponse/pack_metadata.json
Labels: docs-approved

#30794 Handle lint errors.
  Packs/Okta/Integrations/OktaEventCollector/OktaEventCollector.py
  Packs/Okta/ReleaseNotes/3_2_4.md
  Packs/Okta/pack_metadata.json
Labels: docs-approved

#30315 [Azure Compute] - Support altering/Multiple Subscription IDs, Resource Group
  Packs/AzureCompute/Integrations/AzureCompute_v2/AzureCompute_v2.py
  Packs/AzureCompute/Integrations/AzureCompute_v2/AzureCompute_v2.yml
  Packs/AzureCompute/Integrations/AzureCompute_v2/AzureCompute_v2_test.py
  Packs/AzureCompute/Integrations/AzureCompute_v2/README.md
  Packs/AzureCompute/ReleaseNotes/1_2_18.md
  Packs/AzureCompute/pack_metadata.json
Labels: docs-approved

#30786 [ASM] EXPANDR-6887 Docker version changes
  Packs/CortexAttackSurfaceManagement/ReleaseNotes/1_7_13.md
  Packs/CortexAttackSurfaceManagement/Scripts/GenerateASMReport/GenerateASMReport.yml
  Packs/CortexAttackSurfaceManagement/pack_metadata.json
Labels: Contribution, Contribution Form Filled, Community, Xsoar Support Level, External PR

#30642 XSIAM_Armis_Modeling_Ehhancement_CIAC-8720
  Packs/Armis/Integrations/ArmisEventCollector/ArmisEventCollector.py
  Packs/Armis/Integrations/ArmisEventCollector/ArmisEventCollector.yml
  Packs/Armis/Integrations/ArmisEventCollector/ArmisEventCollector_test.py
  Packs/Armis/ModelingRules/ArmisModelingRules/ArmisModelingRules.xif
  Packs/Armis/ModelingRules/ArmisModelingRules/ArmisModelingRules_schema.json
  Packs/Armis/ParsingRules/Armis/Armis.xif
  Packs/Armis/ParsingRules/Armis/Armis.yml
  Packs/Armis/README.md
  Packs/Armis/ReleaseNotes/1_1_7.md
  Packs/Armis/pack_metadata.json
Labels: docs-approved

#30735 symantec-bluecoat-enhancement-ciac-7624
  Packs/SymantecBlueCoatProxySG/.pack-ignore
  Packs/SymantecBlueCoatProxySG/.secrets-ignore
  Packs/SymantecBlueCoatProxySG/ModelingRules/SymantecBlueCoatProxySG/SymantecBlueCoatProxySG.xif
  Packs/SymantecBlueCoatProxySG/ParsingRules/SymantecBlueCoatProxySG/SymantecBlueCoatProxySG.xif
  Packs/SymantecBlueCoatProxySG/ReleaseNotes/1_0_3.md
  Packs/SymantecBlueCoatProxySG/pack_metadata.json
Labels: docs-approved

#30754 Extract_Inidicator_PDF_Image_Bug_Fix
  Packs/CommonPlaybooks/Playbooks/playbook-Extract_Indicators_From_File_-_Generic_v2_4_5.yml
  Packs/CommonPlaybooks/Playbooks/playbook-Extract_Indicators_From_File_-_Generic_v2_4_5_README.md
  Packs/CommonPlaybooks/ReleaseNotes/2_4_14.md
  Packs/CommonPlaybooks/TestPlaybooks/playbook-Extract_Indicators_From_File_-_Generic_v2_-_Test_4_5.yml
  Packs/CommonPlaybooks/doc_files/Extract_Indicators_From_File_-_Generic_v2.png
  Packs/CommonPlaybooks/pack_metadata.json
Labels: docs-approved

#30697 [qradar] fix mirroring issue
  Packs/QRadar/Integrations/QRadar_v3/QRadar_v3.py
  Packs/QRadar/Integrations/QRadar_v3/QRadar_v3.yml
  Packs/QRadar/Integrations/QRadar_v3/QRadar_v3_test.py
  Packs/QRadar/ReleaseNotes/2_4_40.md
  Packs/QRadar/TestPlaybooks/QRadar_v3-test.yml
  Packs/QRadar/pack_metadata.json
  Tests/conf.json
Labels: docs-approved

#30387 [Microsoft Defender for Cloud] multiple subscription ids and resource groups
  Packs/AzureSecurityCenter/.pack-ignore
  Packs/AzureSecurityCenter/Integrations/AzureSecurityCenter_v2/AzureSecurityCenter_v2.py
  Packs/AzureSecurityCenter/Integrations/AzureSecurityCenter_v2/AzureSecurityCenter_v2.yml
  Packs/AzureSecurityCenter/Integrations/AzureSecurityCenter_v2/README.md
  Packs/AzureSecurityCenter/ReleaseNotes/2_0_17.md
  Packs/AzureSecurityCenter/pack_metadata.json
Labels: docs-approved

#30797 Update ZoomEventCollector_description.md
  Packs/Zoom/Integrations/Zoom/README.md
  Packs/Zoom/Integrations/ZoomEventCollector/ZoomEventCollector_description.md
  Packs/Zoom/ReleaseNotes/1_6_1.md
  Packs/Zoom/pack_metadata.json
Labels: docs-approved

#30590 XSIAM - New Phishing layout + playbook fixes
  Packs/CommonPlaybooks/Playbooks/playbook-Block_Indicators_-_Generic_v3.yml
  Packs/CommonPlaybooks/Playbooks/playbook-Block_Indicators_-_Generic_v3_README.md
  Packs/CommonPlaybooks/ReleaseNotes/2_4_15.md
  Packs/CommonPlaybooks/pack_metadata.json
  Packs/Phishing/IncidentFields/incidentfield-MaliciousURLViewed.json
  Packs/Phishing/LayoutRules/Phishing.json
  Packs/Phishing/Layouts/layoutscontainer-Phishing_Layout_XSIAM.json
  Packs/Phishing/Playbooks/Process_Email_-_Generic_v2.yml
  Packs/Phishing/Playbooks/Process_Email_-_Generic_v2_README.md
  Packs/Phishing/ReleaseNotes/3_6_0.md
  Packs/Phishing/Triggers/Trigger_-_Phishing.json
  Packs/Phishing/doc_files/Process_Email_-_Generic_v2.png
  Packs/Phishing/pack_metadata.json
  Tests/known_words.txt
  poetry.lock
Labels: docs-approved

#30659 CiscoFeed added proxy handling
  Packs/ThreatGrid/Integrations/FeedCiscoSecureMalwareAnalytics/FeedCiscoSecureMalwareAnalytics.py
  Packs/ThreatGrid/Integrations/FeedCiscoSecureMalwareAnalytics/FeedCiscoSecureMalwareAnalytics.yml
  Packs/ThreatGrid/Integrations/FeedCiscoSecureMalwareAnalytics/FeedCiscoSecureMalwareAnalytics_test.py
  Packs/ThreatGrid/ReleaseNotes/2_0_15.md
  Packs/ThreatGrid/pack_metadata.json
Labels: docs-approved

#30729 updated CTF 01/ 02 pack metadata and updated the dependencies
  Packs/CTF02/README.md
  Packs/CTF02/pack_metadata.json
  Packs/ctf01/Playbooks/playbook-Cortex_XDR_incident_handling_v3_CTF.yml
  Packs/ctf01/ReleaseNotes/1_0_1.md
  Packs/ctf01/pack_metadata.json
Labels: docs-approved

#30470 Group-IB hot fix integration
  Packs/GroupIB_ThreatIntelligenceAttribution/IncidentTypes/incidenttype-GIB_Brand_Protection_Domain.json
  Packs/GroupIB_ThreatIntelligenceAttribution/Integrations/GroupIBTIA/GroupIBTIA.py
  Packs/GroupIB_ThreatIntelligenceAttribution/Integrations/GroupIBTIA/GroupIBTIA.yml
  Packs/GroupIB_ThreatIntelligenceAttribution/Integrations/GroupIBTIA/GroupIBTIA_description.md
  Packs/GroupIB_ThreatIntelligenceAttribution/Integrations/GroupIBTIA/README.md
  Packs/GroupIB_ThreatIntelligenceAttribution/Integrations/GroupIB_TIA_Feed/GroupIB_TIA_Feed.py
  Packs/GroupIB_ThreatIntelligenceAttribution/Integrations/GroupIB_TIA_Feed/README.md
  Packs/GroupIB_ThreatIntelligenceAttribution/Layouts/layoutscontainer-GIB_Brand_Protection_Domain_Layout.json
  Packs/GroupIB_ThreatIntelligenceAttribution/Playbooks/Incident_Postprocessing_-_Group-IB_Threat_Intelligence_&_Attribution_README.md
  Packs/GroupIB_ThreatIntelligenceAttribution/README.md
  Packs/GroupIB_ThreatIntelligenceAttribution/ReleaseNotes/1_4_0.md
  Packs/GroupIB_ThreatIntelligenceAttribution/Scripts/GIBIncidentUpdate/GIBIncidentUpdate.py
  Packs/GroupIB_ThreatIntelligenceAttribution/Scripts/GIBIncidentUpdateIncludingClosed/GIBIncidentUpdateIncludingClosed.py
  Packs/GroupIB_ThreatIntelligenceAttribution/pack_metadata.json
  package-lock.json
Labels: Contribution, Partner, Contribution Form Filled, Community, pending-contributor, Partner Support Level, External PR, Security Review, Partner-Approved

#30850 made exchange2016compliance hidden
  Packs/Exchange2016_Compliance/pack_metadata.json
Labels: docs-approved

#30080 Modified integration to avoid analysis of private IPs
  Packs/AbuseDB/Integrations/AbuseDB/AbuseDB.py
  Packs/AbuseDB/Integrations/AbuseDB/AbuseDB.yml
  Packs/AbuseDB/Integrations/AbuseDB/AbuseDB_test.py
  Packs/AbuseDB/Integrations/AbuseDB/README.md
  Packs/AbuseDB/ReleaseNotes/1_0_29.md
  Packs/AbuseDB/pack_metadata.json
Labels: Contribution, Contribution Form Filled, Community, Xsoar Support Level, External PR

#30744 added handling for xsoar8 image
  Packs/Base/ReleaseNotes/1_32_44.md
  Packs/Base/Scripts/SanePdfReport/SanePdfReport.py
  Packs/Base/Scripts/SanePdfReport/SanePdfReport_test.py
  Packs/Base/pack_metadata.json
Labels: docs-approved

#30471 [The Hive] Use new endpoint in fetch incidents
  Packs/TheHiveProject/Integrations/TheHiveProject/TheHiveProject.py
  Packs/TheHiveProject/Integrations/TheHiveProject/TheHiveProject.yml
  Packs/TheHiveProject/Integrations/TheHiveProject/TheHiveProject_test.py
  Packs/TheHiveProject/Integrations/TheHiveProject/test_data/cases_list.json
  Packs/TheHiveProject/Integrations/TheHiveProject/test_data/cases_list_new.json
  Packs/TheHiveProject/ReleaseNotes/1_1_20.md
  Packs/TheHiveProject/pack_metadata.json
Labels: docs-approved

#30702 Ciac 8762/support rawjson for test incidents integration
  Packs/DeveloperTools/Integrations/CreateIncidents/CreateIncidents.py
  Packs/DeveloperTools/Integrations/CreateIncidents/CreateIncidents.yml
  Packs/DeveloperTools/Integrations/CreateIncidents/CreateIncidents_test.py
  Packs/DeveloperTools/Integrations/CreateIncidents/README.md
  Packs/DeveloperTools/ReleaseNotes/1_2_59.md
  Packs/DeveloperTools/pack_metadata.json
Labels: docs-approved

#30851 Get User Devices by Username - Generic - fixed an issue where Core didn't run in XSIAM
  Packs/CommonPlaybooks/Playbooks/playbook-Get_User_Devices_by_Username_-_Generic.yml
  Packs/CommonPlaybooks/Playbooks/playbook-Get_User_Devices_by_Username_-_Generic_README.md
  Packs/CommonPlaybooks/ReleaseNotes/2_4_16.md
  Packs/CommonPlaybooks/doc_files/Get_User_Devices_by_Username_-_Generic.png
  Packs/CommonPlaybooks/pack_metadata.json
Labels: docs-approved

#30498 sync from marketplace-saas-dist instead of marketplace-dist
  .gitlab/ci/.gitlab-ci.bucket-upload.yml
Labels: docs-approved

#30291 Azure mirror close with closing reason already set
  Packs/AzureSentinel/Integrations/AzureSentinel/AzureSentinel.py
  Packs/AzureSentinel/Integrations/AzureSentinel/AzureSentinel.yml
  Packs/AzureSentinel/Integrations/AzureSentinel/AzureSentinel_test.py
  Packs/AzureSentinel/ReleaseNotes/1_5_27.md
  Packs/AzureSentinel/pack_metadata.json
Labels: docs-approved, release-notes-only

#30785 OTRS 1.0.21 - Added Owner to otrs-update-ticket command
  Packs/OTRS/CONTRIBUTORS.json
  Packs/OTRS/Integrations/OTRS/OTRS.py
  Packs/OTRS/Integrations/OTRS/OTRS.yml
  Packs/OTRS/ReleaseNotes/1_0_21.md
  Packs/OTRS/pack_metadata.json
Labels: Contribution, ready-for-instance-test, Contribution Form Filled, Community, Partner Support Level, External PR, Partner-Approved

#30617 Fix cisco-amp-event-list command [AMP v2]
  Packs/AMP/.secrets-ignore
  Packs/AMP/Integrations/AMPv2/AMPv2.py
  Packs/AMP/Integrations/AMPv2/AMPv2.yml
  Packs/AMP/Integrations/AMPv2/AMPv2_test.py
  Packs/AMP/Integrations/AMPv2/README.md
  Packs/AMP/Integrations/AMPv2/test_data/event_list_response.json
  Packs/AMP/Integrations/AMPv2/test_data/incidents_response_1.json
  Packs/AMP/Integrations/AMPv2/test_data/incidents_response_2.json
  Packs/AMP/Integrations/AMPv2/test_data/incidents_response_3.json
  Packs/AMP/Integrations/AMPv2/test_data/incidents_response_4.json
  Packs/AMP/ReleaseNotes/2_0_17.md
  Packs/AMP/pack_metadata.json
Labels: docs-approved

#30769 Darktrace: Patch post request
  Packs/Darktrace/Integrations/DarktraceMBs/DarktraceMBs.py
  Packs/Darktrace/ReleaseNotes/3_0_6.md
  Packs/Darktrace/pack_metadata.json
Labels: Contribution, Partner, Contribution Form Filled, Partner Support Level, External PR, Partner-Approved

#30879 Calculate Severity By Highest DBotScore - performance improvement
  Packs/CommonPlaybooks/Playbooks/playbook-Calculate_Severity_By_Highest_DBotScore_6_0.yml
  Packs/CommonPlaybooks/ReleaseNotes/2_4_17.md
  Packs/CommonPlaybooks/pack_metadata.json
Labels: docs-approved, release-notes-only

#30648 [PAN-OS] UI output for url command
  Packs/PAN-OS/Integrations/Panorama/Panorama.py
  Packs/PAN-OS/ReleaseNotes/2_1_13.md
  Packs/PAN-OS/pack_metadata.json
Labels: docs-approved

#30876 update the retry count to 0
  Packs/Whois/Integrations/Whois/Whois.py
  Packs/Whois/Integrations/Whois/Whois.yml
  Packs/Whois/ReleaseNotes/1_5_5.json
  Packs/Whois/ReleaseNotes/1_5_5.md
  Packs/Whois/pack_metadata.json
  Tests/conf.json
Labels: docs-approved, ForceMerge

#30878 Group-IB hot fix integration
  Packs/GroupIB_ThreatIntelligenceAttribution/IncidentTypes/incidenttype-GIB_Brand_Protection_Domain.json
  Packs/GroupIB_ThreatIntelligenceAttribution/Integrations/GroupIBTIA/GroupIBTIA.py
  Packs/GroupIB_ThreatIntelligenceAttribution/Integrations/GroupIBTIA/GroupIBTIA.yml
  Packs/GroupIB_ThreatIntelligenceAttribution/Integrations/GroupIBTIA/GroupIBTIA_description.md
  Packs/GroupIB_ThreatIntelligenceAttribution/Integrations/GroupIBTIA/README.md
  Packs/GroupIB_ThreatIntelligenceAttribution/Integrations/GroupIB_TIA_Feed/GroupIB_TIA_Feed.py
  Packs/GroupIB_ThreatIntelligenceAttribution/Integrations/GroupIB_TIA_Feed/README.md
  Packs/GroupIB_ThreatIntelligenceAttribution/Layouts/layoutscontainer-GIB_Brand_Protection_Domain_Layout.json
  Packs/GroupIB_ThreatIntelligenceAttribution/Playbooks/Incident_Postprocessing_-_Group-IB_Threat_Intelligence_&_Attribution_README.md
  Packs/GroupIB_ThreatIntelligenceAttribution/README.md
  Packs/GroupIB_ThreatIntelligenceAttribution/ReleaseNotes/1_4_0.md
  Packs/GroupIB_ThreatIntelligenceAttribution/Scripts/GIBIncidentUpdate/GIBIncidentUpdate.py
  Packs/GroupIB_ThreatIntelligenceAttribution/Scripts/GIBIncidentUpdateIncludingClosed/GIBIncidentUpdateIncludingClosed.py
  Packs/GroupIB_ThreatIntelligenceAttribution/pack_metadata.json
  package-lock.json
Labels: Contribution, docs-approved, External PR

#30875 Fix for 'Detonate URL - FireEye AX' playbook
  Packs/fireeye/Playbooks/playbook-Detonate_URL_-_FireEye_AX.yml
  Packs/fireeye/Playbooks/playbook-Detonate_URL_-_FireEye_AX_README.md
  Packs/fireeye/ReleaseNotes/1_0_16.md
  Packs/fireeye/doc_files/Detonate_URL_-_FireEye_AX.png
  Packs/fireeye/pack_metadata.json
Labels: docs-approved

#28650 Cloud Incident Response Docs
  Packs/CloudIncidentResponse/Playbooks/playbook-Cloud_IAM_User_Access_Investigation.yml
  Packs/CloudIncidentResponse/Playbooks/playbook-Cloud_IAM_User_Access_Investigation_README.md
  Packs/CloudIncidentResponse/Playbooks/playbook-Cortex_XDR_-_Cloud_IAM_User_Access_Investigation.yml
  Packs/CloudIncidentResponse/Playbooks/playbook-Cortex_XDR_-_Cloud_IAM_User_Access_Investigation_README.md
  Packs/CloudIncidentResponse/README.md
  Packs/CloudIncidentResponse/ReleaseNotes/1_0_8.md
  Packs/CloudIncidentResponse/Triggers/Trigger_-_Cloud_IAM_User_Access_Investigation.json
  Packs/CloudIncidentResponse/doc_files/Cloud_IAM_User_Access_Investigation.png
  Packs/CloudIncidentResponse/doc_files/Cortex_XDR_-_Cloud_IAM_User_Access_Investigation.png
  Packs/CloudIncidentResponse/pack_metadata.json
  Packs/Core/ReleaseNotes/3_0_0.json
  Packs/Core/ReleaseNotes/3_0_0.md
  Packs/Core/pack_metadata.json
  Packs/CortexXDR/ReleaseNotes/6_0_0.json
  Packs/CortexXDR/ReleaseNotes/6_0_0.md
  Packs/CortexXDR/pack_metadata.json
Labels: docs-approved

#30774 Get Email From Email Gateway - Generic - removed unused User ID input
  Packs/CommonPlaybooks/Playbooks/playbook-Get_Email_From_Email_Gateway_-_Generic.yml
  Packs/CommonPlaybooks/Playbooks/playbook-Get_Email_From_Email_Gateway_-_Generic_README.md
  Packs/CommonPlaybooks/ReleaseNotes/2_4_19.md
  Packs/CommonPlaybooks/pack_metadata.json
Labels: docs-approved, release-notes-only

#30865 update GetIndicatorDBotScoreFromCache
  Packs/CommonScripts/ReleaseNotes/1_12_42.md
  Packs/CommonScripts/Scripts/GetIndicatorDBotScoreFromCache/GetIndicatorDBotScoreFromCache.py
  Packs/CommonScripts/Scripts/GetIndicatorDBotScoreFromCache/GetIndicatorDBotScoreFromCache.yml
  Packs/CommonScripts/Scripts/GetIndicatorDBotScoreFromCache/GetIndicatorDBotScoreFromCache_test.py
  Packs/CommonScripts/Scripts/GetIndicatorDBotScoreFromCache/README.md
  Packs/CommonScripts/pack_metadata.json
Labels: docs-approved

#30709 Fixes For 'Detonate URL - ThreatGrid v2' Playbook
  Packs/ThreatGrid/Playbooks/playbook-Detonate_URL_-_ThreatGrid_v2.yml
  Packs/ThreatGrid/Playbooks/playbook-Detonate_URL_-_ThreatGrid_v2_README.md
  Packs/ThreatGrid/ReleaseNotes/2_0_16.md
  Packs/ThreatGrid/pack_metadata.json
Labels: docs-approved

#30904 fixed base url
  Packs/ThreatGrid/Integrations/FeedCiscoSecureMalwareAnalytics/FeedCiscoSecureMalwareAnalytics.py
  Packs/ThreatGrid/ReleaseNotes/2_0_17.md
  Packs/ThreatGrid/pack_metadata.json
Labels: docs-approved

#30853 Create ManageEngine AD Self Service Plus pack
  Packs/ManageEngine-ADSelfServicePlus/.pack-ignore
  Packs/ManageEngine-ADSelfServicePlus/.secrets-ignore
  Packs/ManageEngine-ADSelfServicePlus/ModelingRules/ManageEngine-ADSelfServicePlus/ManageEngine-ADSelfServicePlus.xif
  Packs/ManageEngine-ADSelfServicePlus/ModelingRules/ManageEngine-ADSelfServicePlus/ManageEngine-ADSelfServicePlus.yml
  Packs/ManageEngine-ADSelfServicePlus/ModelingRules/ManageEngine-ADSelfServicePlus/ManageEngine-ADSelfServicePlus_schema.json
  Packs/ManageEngine-ADSelfServicePlus/ParsingRules/ManageEngine-ADSelfServicePlus/ManageEngine-ADSelfServicePlus.xif
  Packs/ManageEngine-ADSelfServicePlus/ParsingRules/ManageEngine-ADSelfServicePlus/ManageEngine-ADSelfServicePlus.yml
  Packs/ManageEngine-ADSelfServicePlus/README.md
  Packs/ManageEngine-ADSelfServicePlus/pack_metadata.json
Labels: docs-approved

#30152 add tim reveiwer
  Utils/github_workflow_scripts/handle_external_pr.py
  Utils/github_workflow_scripts/utils.py
  Utils/github_workflow_scripts/utils_test.py
Labels: docs-approved, TIM Review

#30903 Revert docker image - DBotPredictURLPhishing
  Packs/PhishingURL/ReleaseNotes/1_1_6.md
  Packs/PhishingURL/Scripts/DBotPredictURLPhishing/DBotPredictURLPhishing.yml
  Packs/PhishingURL/TestPlaybooks/DBotPredictURLPhishing_test.yml
  Packs/PhishingURL/pack_metadata.json
Labels: docs-approved, ForceMerge

#30881 added timeout arg to get-alerts command
  Packs/ApiModules/Scripts/FireEyeApiModule/FireEyeApiModule.py
  Packs/FireEyeCM/Integrations/FireEyeCM/FireEyeCM.py
  Packs/FireEyeCM/Integrations/FireEyeCM/FireEyeCM.yml
  Packs/FireEyeCM/ReleaseNotes/1_1_23.md
  Packs/FireEyeCM/pack_metadata.json
  Packs/FireEyeEX/ReleaseNotes/2_0_27.md
  Packs/FireEyeEX/pack_metadata.json
Labels: docs-approved

#30801 Jira TBP/TMR bot improvements and fixes
  Tests/scripts/common.py
  Tests/scripts/convert_test_modeling_result_to_jira_issues.py
  Tests/scripts/convert_test_playbook_result_to_jira_issues.py
  Tests/scripts/gitlab_slack_notifier.py
  Tests/scripts/jira_issues.py
  Tests/scripts/test_modeling_rule_report.py
  Tests/scripts/test_playbooks_report.py
Labels: docs-approved

#30858 fixing clean machine script, not having an artifacts folder created
  .gitlab/ci/.gitlab-ci.global.yml
Labels: docs-approved

#30920 fixing cloud machine unlock script to handle cases that no machines was locked.
  .gitlab/ci/.gitlab-ci.global.yml
Labels: docs-approved

#30848 Xdr lite playbook description
  Packs/CortexXDR/Playbooks/playbook-Cortex_XDR_Lite_-_Incident_Handling.yml
  Packs/CortexXDR/Playbooks/playbook-Cortex_XDR_Lite_-_Incident_Handling_README.md
  Packs/CortexXDR/ReleaseNotes/6_0_1.md
  Packs/CortexXDR/pack_metadata.json
Labels: docs-approved

#30778 [UploadFlow Ref] update_index fixes
  Tests/Marketplace/Tests/marketplace_services_test.py
  Tests/Marketplace/Tests/test_data/metadata.json
  Tests/Marketplace/Tests/upload_packs_test.py
  Tests/Marketplace/marketplace_services.py
  Tests/Marketplace/upload_packs.py
  Tests/private_build/marketplace_services_private.py
  Tests/private_build/tests/test_upload_packs_private.py
  Tests/private_build/upload_packs_private.py
  Utils/test_upload_flow/verify_bucket.py
  Utils/test_upload_flow/wait_for_upload.py
Labels: docs-approved

#30665 [Upload Flow Ref] Remove missing_dependency logic
  Tests/Marketplace/Tests/marketplace_services_test.py
  Tests/Marketplace/marketplace_services.py
  Tests/Marketplace/upload_packs.py
Labels: docs-approved

#30937 fix XSOAR XSIAM close tags
  Packs/CloudIncidentResponse/README.md
Labels: docs-approved

#30939 Change content roles for contribution round
  .github/content_roles.json
Labels: docs-approved

#30531 Fix truncated data from PAN OS
  Packs/PAN-OS/Integrations/Panorama/Panorama.py
  Packs/PAN-OS/Integrations/Panorama/Panorama.yml
  Packs/PAN-OS/Integrations/Panorama/README.md
  Packs/PAN-OS/ReleaseNotes/2_1_14.md
  Packs/PAN-OS/pack_metadata.json
Labels: docs-approved

#30782 XSOAR Engineer - Added link to Live Community to README
  Packs/XSOAR_Engineer_Training/README.md
Labels: Contribution, ready-for-instance-test, Contribution Form Filled, Community, pending-contributor, Community Support Level, External PR

#30779 Get File Sample By Hash - Generic v3 - updated description to include Code42
  Packs/CommonPlaybooks/Playbooks/playbook-Get_File_Sample_By_Hash_-_Generic_v3.yml
  Packs/CommonPlaybooks/Playbooks/playbook-Get_File_Sample_By_Hash_-_Generic_v3_README.md
  Packs/CommonPlaybooks/ReleaseNotes/2_4_20.md
  Packs/CommonPlaybooks/pack_metadata.json
Labels: docs-approved, release-notes-only

#30860 install in batches in claud build
  Tests/Marketplace/search_and_install_packs.py
  Tests/configure_and_test_integration_instances.py
Labels: docs-approved

#30925 MISP v3: make TPB sequentially
  Packs/MISP/TestPlaybooks/MISP_V3_Test.yml
Labels: docs-approved

#30758 Fixing MATI Ingestion Issues
  Packs/MandiantAdvantageThreatIntelligence/Integrations/MandiantAdvantageThreatIntelligence/MandiantAdvantageThreatIntelligence.py
  Packs/MandiantAdvantageThreatIntelligence/Integrations/MandiantAdvantageThreatIntelligence/MandiantAdvantageThreatIntelligence.yml
  Packs/MandiantAdvantageThreatIntelligence/Integrations/MandiantAdvantageThreatIntelligence/MandiantAdvantageThreatIntelligence_test.py
  Packs/MandiantAdvantageThreatIntelligence/ReleaseNotes/1_0_12.md
  Packs/MandiantAdvantageThreatIntelligence/pack_metadata.json
Labels: Contribution, docs-approved, Partner, ready-for-instance-test, Contribution Form Filled, pending-contributor, Partner Support Level, External PR, Partner-Approved

#30927 ReadPDFFileV2 add support for owner password
  Packs/CommonScripts/ReleaseNotes/1_12_43.md
  Packs/CommonScripts/Scripts/ReadPDFFileV2/ReadPDFFileV2.py
  Packs/CommonScripts/Scripts/ReadPDFFileV2/ReadPDFFileV2.yml
  Packs/CommonScripts/Scripts/ReadPDFFileV2/ReadPDFFileV2_test.py
  Packs/CommonScripts/Scripts/ReadPDFFileV2/test_data/dummy-with-owner-pass.pdf
  Packs/CommonScripts/pack_metadata.json
Labels: docs-approved

#30161 Contrib/binalyze air update
  Packs/Binalyze/Integrations/BinalyzeAIR/BinalyzeAIR.py
  Packs/Binalyze/Integrations/BinalyzeAIR/BinalyzeAIR.yml
  Packs/Binalyze/Integrations/BinalyzeAIR/BinalyzeAIR_description.md
  Packs/Binalyze/Integrations/BinalyzeAIR/BinalyzeAIR_test.py
  Packs/Binalyze/Integrations/BinalyzeAIR/README.md
  Packs/Binalyze/Integrations/BinalyzeAIR/command_examples
  Packs/Binalyze/Integrations/BinalyzeAIR/test_data/profile_id.json
  Packs/Binalyze/README.md
  Packs/Binalyze/ReleaseNotes/1_1_0.md
  Packs/Binalyze/pack_metadata.json
Labels: Contribution, docs-approved, Partner, ready-for-instance-test, pending-demo, post-demo, Contribution Form Filled, pending-contributor, Partner Support Level, External PR, Partner-Approved

#30480 [Azure Log Analytics] Search Jobs
  Packs/AzureLogAnalytics/Integrations/AzureLogAnalytics/AzureLogAnalytics.py
  Packs/AzureLogAnalytics/Integrations/AzureLogAnalytics/AzureLogAnalytics.yml
  Packs/AzureLogAnalytics/Integrations/AzureLogAnalytics/AzureLogAnalytics_test.py
  Packs/AzureLogAnalytics/Integrations/AzureLogAnalytics/README.md
  Packs/AzureLogAnalytics/Integrations/AzureLogAnalytics/command_examples
  Packs/AzureLogAnalytics/Integrations/AzureLogAnalytics/test_data/get_search_job.json
  Packs/AzureLogAnalytics/ReleaseNotes/1_1_22.md
  Packs/AzureLogAnalytics/TestPlaybooks/playbook-AzureLogAnalytics-test.yml
  Packs/AzureLogAnalytics/pack_metadata.json
  Tests/conf.json
Labels: docs-approved

#30041 Fix test-upload merge general release notes
  Tests/Marketplace/Tests/marketplace_services_test.py
  Tests/Marketplace/marketplace_constants.py
  Tests/Marketplace/marketplace_services.py
  Tests/scripts/infrastructure_tests/release_notes_generator_test.py
  Utils/release_notes_generator.py
  Utils/test_upload_flow/create_test_branch.py
  Utils/test_upload_flow/verify_bucket.py
Labels: docs-approved

#30899 QualysV2 fix TPB (updated the map and scan IDs)
  Packs/qualys/TestPlaybooks/QualysVulnerabilityManagement-Test.yml
Labels: docs-approved

#30781 Get File Sample From Path - Generic v3 - added AcquiredFile output
  Packs/CommonPlaybooks/Playbooks/playbook-Get_File_Sample_From_Path_-_Generic_V3.yml
  Packs/CommonPlaybooks/Playbooks/playbook-Get_File_Sample_From_Path_-_Generic_V3_README.md
  Packs/CommonPlaybooks/ReleaseNotes/2_4_21.md
  Packs/CommonPlaybooks/pack_metadata.json
Labels: docs-approved, release-notes-only

#30907 move IsInCidrRanges to JS for performance improvement
  Packs/FiltersAndTransformers/.secrets-ignore
  Packs/FiltersAndTransformers/ReleaseNotes/1_2_37.md
  Packs/FiltersAndTransformers/Scripts/IsInCidrRanges/IsInCidrRanges.js
  Packs/FiltersAndTransformers/Scripts/IsInCidrRanges/IsInCidrRanges.py
  Packs/FiltersAndTransformers/Scripts/IsInCidrRanges/IsInCidrRanges.yml
  Packs/FiltersAndTransformers/Scripts/IsInCidrRanges/IsInCidrRanges_test.py
  Packs/FiltersAndTransformers/TestPlaybooks/playbook-TestIsInCidrRanges.yml
  Packs/FiltersAndTransformers/pack_metadata.json
  Tests/conf.json
Labels: docs-approved, ForceMerge

#30477 Add Roles to GCP IAM policy lookup - EXPANDR 5945
  Packs/GCP-IAM/Integrations/GCPIAM/GCPIAM.py
  Packs/GCP-IAM/Integrations/GCPIAM/GCPIAM.yml
  Packs/GCP-IAM/Integrations/GCPIAM/GCPIAM_test.py
  Packs/GCP-IAM/Integrations/GCPIAM/README.md
  Packs/GCP-IAM/ReleaseNotes/1_0_21.md
  Packs/GCP-IAM/pack_metadata.json
Labels: Contribution, docs-approved, ready-for-instance-test, pending-demo, post-demo, Contribution Form Filled, Community, pending-contributor, Xsoar Support Level, External PR

#30644 Fixes for 'Detonate_File_-_Generic' playbook
  Packs/CommonPlaybooks/Playbooks/playbook-Detonate_File_-_Generic.yml
  Packs/CommonPlaybooks/Playbooks/playbook-Detonate_File_-_Generic_README.md
  Packs/CommonPlaybooks/ReleaseNotes/2_4_22.md
  Packs/CommonPlaybooks/doc_files/Detonate_File_-_Generic.png
  Packs/CommonPlaybooks/pack_metadata.json
Labels: docs-approved

#30206 Fixes for 'Detonate and Analyze File - Generic' Playbook
  Packs/CommonPlaybooks/Playbooks/playbook-Detonate_and_Analyze_File_-_Generic.yml
  Packs/CommonPlaybooks/Playbooks/playbook-Detonate_and_Analyze_File_-_Generic_README.md
  Packs/CommonPlaybooks/ReleaseNotes/2_4_23.md
  Packs/CommonPlaybooks/doc_files/Detonate_and_Analyze_File_-_Generic.png
  Packs/CommonPlaybooks/pack_metadata.json
Labels: docs-approved

#30902 Added *fetch-through-merge-base
  .gitlab/ci/.gitlab-ci.global.yml
  .gitlab/ci/.gitlab-ci.variables.yml
Labels: docs-approved

#30369 Qradar mirroring close note when closing offense
  Packs/QRadar/Integrations/QRadar_v3/QRadar_v3.py
  Packs/QRadar/Integrations/QRadar_v3/QRadar_v3_test.py
  Packs/QRadar/ReleaseNotes/2_4_41.md
  Packs/QRadar/pack_metadata.json
Labels: docs-approved

#30958 Revert "Added *fetch-through-merge-base"
  .gitlab/ci/.gitlab-ci.global.yml
  .gitlab/ci/.gitlab-ci.variables.yml
Labels: docs-approved

#30725 [taxii2-server] - fix bug when creating relationships
  Packs/TAXIIServer/Integrations/TAXII2Server/TAXII2Server.py
  Packs/TAXIIServer/Integrations/TAXII2Server/TAXII2Server.yml
  Packs/TAXIIServer/ReleaseNotes/2_0_50.md
  Packs/TAXIIServer/pack_metadata.json
Labels: ForceMerge

#30720 Reco: get user context by email address
  Packs/Reco/.secrets-ignore
  Packs/Reco/Integrations/Reco/README.md
  Packs/Reco/Integrations/Reco/Reco.py
  Packs/Reco/Integrations/Reco/Reco.yml
  Packs/Reco/Integrations/Reco/Reco_test.py
  Packs/Reco/README.md
  Packs/Reco/ReleaseNotes/1_2_0.md
  Packs/Reco/pack_metadata.json
Labels: Contribution, docs-approved, Partner, ready-for-instance-test, pending-demo, post-demo, Contribution Form Filled, pending-contributor, Partner Support Level, External PR, Partner-Approved

#30934 add_new_validate_script
  Tests/scripts/new_validate.sh
Labels: docs-approved

#30863 Azure sentinel: move the suffix in close reason
  Packs/AzureSentinel/Integrations/AzureSentinel/AzureSentinel.py
  Packs/AzureSentinel/Integrations/AzureSentinel/AzureSentinel_test.py
  Packs/AzureSentinel/ReleaseNotes/1_5_28.json
  Packs/AzureSentinel/ReleaseNotes/1_5_28.md
  Packs/AzureSentinel/pack_metadata.json
Labels: docs-approved

#30938 [UploadFlow Ref] Remove collect_content_items
  Tests/Marketplace/Tests/marketplace_services_test.py
  Tests/Marketplace/marketplace_services.py
Labels: docs-approved

#30919 Prevent the xsoar_ng_server_ga from running if the prepare-xsoar-saas…
  .gitlab/ci/.gitlab-ci.on-push.yml
Labels: docs-approved
