Repository demisto/content, pull requests merged in 2023-02, with the labels that each got.

#23927 [ASM] - EXPANDR-1598 - Snmp server use case changes
  Packs/CortexAttackSurfaceManagement/IncidentFields/incidentfield-ASM_-_Dev_Check.json
  Packs/CortexAttackSurfaceManagement/Playbooks/Cortex_ASM_-_ASM_Alert.yml
  Packs/CortexAttackSurfaceManagement/Playbooks/Cortex_ASM_-_Detect_Service.yml
  Packs/CortexAttackSurfaceManagement/Playbooks/Cortex_ASM_-_Detect_Service_README.md
  Packs/CortexAttackSurfaceManagement/Playbooks/Cortex_ASM_-_Enrichment.yml
  Packs/CortexAttackSurfaceManagement/Playbooks/Cortex_ASM_-_Enrichment_README.md
  Packs/CortexAttackSurfaceManagement/Playbooks/Cortex_ASM_-_SNMP_Check.yml
  Packs/CortexAttackSurfaceManagement/Playbooks/Cortex_ASM_-_SNMP_Check_README.md
  Packs/CortexAttackSurfaceManagement/README.md
  Packs/CortexAttackSurfaceManagement/ReleaseNotes/1_4_2.md
  Packs/CortexAttackSurfaceManagement/Scripts/InferWhetherServiceIsDev/InferWhetherServiceIsDev.py
  Packs/CortexAttackSurfaceManagement/Scripts/InferWhetherServiceIsDev/InferWhetherServiceIsDev.yml
  Packs/CortexAttackSurfaceManagement/Scripts/InferWhetherServiceIsDev/InferWhetherServiceIsDev_test.py
  Packs/CortexAttackSurfaceManagement/Scripts/InferWhetherServiceIsDev/README.md
  Packs/CortexAttackSurfaceManagement/Scripts/SnmpDetection/README.md
  Packs/CortexAttackSurfaceManagement/Scripts/SnmpDetection/SnmpDetection.py
  Packs/CortexAttackSurfaceManagement/Scripts/SnmpDetection/SnmpDetection.yml
  Packs/CortexAttackSurfaceManagement/Scripts/SnmpDetection/SnmpDetection_test.py
  Packs/CortexAttackSurfaceManagement/Scripts/SnmpDetection/test_data/snmp_output.json
  Packs/CortexAttackSurfaceManagement/doc_files/Cortex_ASM_-_Detect_Service.png
  Packs/CortexAttackSurfaceManagement/doc_files/Cortex_ASM_-_Enrichment.png
  Packs/CortexAttackSurfaceManagement/doc_files/Cortex_ASM_-_SNMP_Check.png
  Packs/CortexAttackSurfaceManagement/doc_files/InferWhetherServiceIsDev.png
  Packs/CortexAttackSurfaceManagement/doc_files/SnmpDetection.png
  Packs/CortexAttackSurfaceManagement/pack_metadata.json
Labels: Contribution, docs-approved, Contribution Form Filled, Community

#24068 align pdf unlocker to native image
  Packs/CommonScripts/ReleaseNotes/1_11_19.md
  Packs/CommonScripts/Scripts/PDFUnlocker/PDFUnlocker.py
  Packs/CommonScripts/Scripts/PDFUnlocker/PDFUnlocker.yml
  Packs/CommonScripts/pack_metadata.json
Labels: docs-approved

#24258 Fixing from version of the script
  Packs/CommonScripts/ReleaseNotes/1_11_20.md
  Packs/CommonScripts/Scripts/ContentPackInstaller/ContentPackInstaller.yml
  Packs/CommonScripts/pack_metadata.json
Labels: docs-approved, ForceMerge

#24260 Fix TrendMicroVisionOne tests
  Packs/TrendMicroVisionOne/Integrations/TrendMicroVisionOneV3/TrendMicroVisionOneV3_test.py
Labels: docs-approved

#24218 Update README.md
  README.md
Labels: docs-approved

#24257 Fix alerts mapping xdrbruteverdict
  Packs/CortexXDR/Playbooks/playbook-Cortex_XDR_-_Possible_External_RDP_Brute-Force_-_Set_Verdict.yml
  Packs/CortexXDR/ReleaseNotes/4_10_8.md
  Packs/CortexXDR/pack_metadata.json
Labels: docs-approved

#24119 [ASM] rc list 01252023
  Packs/CortexAttackSurfaceManagement/Lists/list-RemediationGuidance.json
  Packs/CortexAttackSurfaceManagement/ReleaseNotes/1_4_3.md
  Packs/CortexAttackSurfaceManagement/pack_metadata.json
Labels: Contribution, docs-approved, Contribution Form Filled, Community, pending-contributor

#24231 Renaming falcon x update images
  Packs/CommonPlaybooks/Playbooks/playbook-Detonate_and_Analyze_File_-_Generic.yml
  Packs/CommonPlaybooks/Playbooks/playbook-Detonate_and_Analyze_File_-_Generic_README.md
  Packs/CommonPlaybooks/ReleaseNotes/2_3_30.md
  Packs/CommonPlaybooks/doc_files/Detonate_URL_-_Generic.png
  Packs/CommonPlaybooks/doc_files/Detonate_and_Analyze_File_-_Generic.png
  Packs/CommonPlaybooks/pack_metadata.json
  Packs/CrowdStrikeFalconX/Playbooks/playbook-FalconX_Detonate_and_Analyze_File.yml
  Packs/CrowdStrikeFalconX/ReleaseNotes/1_2_21.md
  Packs/CrowdStrikeFalconX/doc_files/FalconX_Detonate_and_Analyze.png
  Packs/CrowdStrikeFalconX/pack_metadata.json
Labels: docs-approved

#21245 Upload testing flow
  .gitlab/ci/.gitlab-ci.yml
  .gitlab/ci/on-push.yml
  Tests/Marketplace/marketplace_services.py
  Utils/test_upload_flow/TestUploadFlow/IndicatorTypes/reputation-TestUploadFlowIndicatortype.json
  Utils/test_upload_flow/create_test_branch.py
  Utils/test_upload_flow/verify_bucket.py
  Utils/test_upload_flow/wait_for_upload.py
  Utils/trigger_private_build.py
  Utils/trigger_test_upload_flow.sh
Labels: docs-approved

#24065 bug - stix 2.0 indicator conventions
  Packs/TAXIIServer/Integrations/TAXII2Server/TAXII2Server.py
  Packs/TAXIIServer/Integrations/TAXII2Server/TAXII2Server_test.py
  Packs/TAXIIServer/Integrations/TAXII2Server/test_data/sco_indicator_file.json
  Packs/TAXIIServer/ReleaseNotes/2_0_24.md
  Packs/TAXIIServer/pack_metadata.json
Labels: docs-approved, ForceMerge

#24057 SplunkPy - Support Closing Custom Status Labels on Mirror
  Packs/SplunkPy/Integrations/SplunkPy/README.md
  Packs/SplunkPy/Integrations/SplunkPy/SplunkPy.py
  Packs/SplunkPy/Integrations/SplunkPy/SplunkPy.yml
  Packs/SplunkPy/Integrations/SplunkPy/SplunkPy_description.md
  Packs/SplunkPy/Integrations/SplunkPy/SplunkPy_test.py
  Packs/SplunkPy/ReleaseNotes/3_0_8.md
  Packs/SplunkPy/pack_metadata.json
Labels: docs-approved

#24229 IfThenElse Enhancenment
  Packs/FiltersAndTransformers/ReleaseNotes/1_2_8.md
  Packs/FiltersAndTransformers/Scripts/IfThenElse/IfThenElse.js
  Packs/FiltersAndTransformers/Scripts/IfThenElse/IfThenElse.yml
  Packs/FiltersAndTransformers/Scripts/IfThenElse/README.md
  Packs/FiltersAndTransformers/TestPlaybooks/playbook-IfThenElse-Test.yml
  Packs/FiltersAndTransformers/pack_metadata.json
Labels: docs-approved

#24273 Fix TrendMicroVisionOneV3 UT endpoints with mock
  Packs/TrendMicroVisionOne/Integrations/TrendMicroVisionOneV3/TrendMicroVisionOneV3_test.py
Labels: docs-approved

#24268 layout marketplace fix
  Packs/ProofpointTAP/Layouts/layoutscontainer-ProofPointTAP_Message_Layout.json
  Packs/ProofpointTAP/ReleaseNotes/1_1_26.md
  Packs/ProofpointTAP/pack_metadata.json
Labels: docs-approved

#24270 [Netskope] Fix lastrun missing event_type
  Packs/Netskope/Integrations/NetskopeEventCollector/NetskopeEventCollector.py
  Packs/Netskope/Integrations/NetskopeEventCollector/NetskopeEventCollector.yml
  Packs/Netskope/ReleaseNotes/3_0_8.md
  Packs/Netskope/pack_metadata.json
Labels: docs-approved

#24233 Xsoar mirroring bug
  Packs/XSOARmirroring/.pack-ignore
  Packs/XSOARmirroring/Integrations/XSOARmirroring/README.md
  Packs/XSOARmirroring/Integrations/XSOARmirroring/XSOARmirroring.py
  Packs/XSOARmirroring/Integrations/XSOARmirroring/XSOARmirroring.yml
  Packs/XSOARmirroring/Integrations/XSOARmirroring/XSOARmirroring_test.py
  Packs/XSOARmirroring/ReleaseNotes/2_0_12.md
  Packs/XSOARmirroring/pack_metadata.json
Labels: docs-approved

#24299 Alibaba test modeling rules fix
  Packs/AlibabaActionTrail/ModelingRules/AlibabaModelingRules_1_3/AlibabaModelingRules_1_3_testdata.json
Labels: docs-approved

#23974 Updating CommonServerPython URL regex to accept defanged colon
  Packs/Base/ReleaseNotes/1_31_59.md
  Packs/Base/Scripts/CommonServerPython/CommonServerPython.py
  Packs/Base/Scripts/CommonServerPython/CommonServerPython_test.py
  Packs/Base/pack_metadata.json
Labels: docs-approved

#24190 added KB4 header
  Packs/knowbe4Phisher/Integrations/knowbe4Phisher/knowbe4Phisher.py
  Packs/knowbe4Phisher/Integrations/knowbe4Phisher/knowbe4Phisher.yml
  Packs/knowbe4Phisher/Integrations/knowbe4Phisher/knowbe4Phisher_test.py
  Packs/knowbe4Phisher/ReleaseNotes/1_0_10.md
  Packs/knowbe4Phisher/ReleaseNotes/1_0_9.md
  Packs/knowbe4Phisher/pack_metadata.json
Labels: Contribution, docs-approved, Partner, Contribution Form Filled

#24296 Fix bug CS feed
  Packs/FeedCrowdstrikeFalconIntel/Integrations/CrowdStrikeIndicatorFeed/CrowdStrikeIndicatorFeed.py
  Packs/FeedCrowdstrikeFalconIntel/Integrations/CrowdStrikeIndicatorFeed/CrowdStrikeIndicatorFeed.yml
  Packs/FeedCrowdstrikeFalconIntel/Integrations/CrowdStrikeIndicatorFeed/CrowdStrikeIndicatorFeed_test.py
  Packs/FeedCrowdstrikeFalconIntel/ReleaseNotes/2_0_21.md
  Packs/FeedCrowdstrikeFalconIntel/pack_metadata.json
Labels: docs-approved

#24056 update native image ga tag and run lint on all packages when native config file is changed
  Packs/CheckPointDome9/Integrations/CheckPointDome9/CheckPointDome9_test.py
  Tests/docker_native_image_config.json
  Tests/scripts/should_lint_all.sh
Labels: docs-approved

#24271 rm spam tag
  Packs/FeedCyrenThreatInDepth/pack_metadata.json
  Tests/Marketplace/approved_tags.json
Labels: docs-approved

#24163 [Google IP Ranges Feed] - fix memory leak bug
  Packs/AccentureCTI_Feed/Integrations/ACTIIndicatorFeed/ACTIIndicatorFeed.yml
  Packs/AccentureCTI_Feed/ReleaseNotes/1_1_5.md
  Packs/AccentureCTI_Feed/pack_metadata.json
  Packs/ApiModules/.secrets-ignore
  Packs/ApiModules/ReleaseNotes/2_2_14.md
  Packs/ApiModules/Scripts/JSONFeedApiModule/JSONFeedApiModule.py
  Packs/ApiModules/Scripts/JSONFeedApiModule/JSONFeedApiModule_test.py
  Packs/FeedAWS/Integrations/FeedAWS/FeedAWS.yml
  Packs/FeedAWS/ReleaseNotes/1_1_26.md
  Packs/FeedAWS/pack_metadata.json
  Packs/FeedFastly/Integrations/FeedFastly/FeedFastly.yml
  Packs/FeedFastly/ReleaseNotes/1_1_23.md
  Packs/FeedFastly/pack_metadata.json
  Packs/FeedGCPWhitelist/.secrets-ignore
  Packs/FeedGCPWhitelist/Integrations/FeedGoogleIPRanges/FeedGoogleIPRanges.yml
  Packs/FeedGCPWhitelist/Integrations/FeedGoogleIPRanges/FeedGoogleIPRanges_test.py
  Packs/FeedGCPWhitelist/ReleaseNotes/2_0_7.md
  Packs/FeedGCPWhitelist/pack_metadata.json
  Packs/FeedIntel471/Integrations/Intel471Actors/Intel471Actors.yml
  Packs/FeedIntel471/Integrations/Intel471Malware/Intel471Malware.yml
  Packs/FeedIntel471/Integrations/Intel471MalwareIndicator/Intel471MalwareIndicator.yml
  Packs/FeedIntel471/ReleaseNotes/2_0_16.md
  Packs/FeedIntel471/pack_metadata.json
  Packs/FeedJSON/Integrations/FeedJSON/FeedJSON.yml
  Packs/FeedJSON/ReleaseNotes/1_1_26.md
  Packs/FeedJSON/pack_metadata.json
  Packs/FeedMalwareBazaar/.secrets-ignore
  Packs/FeedMalwareBazaar/Integrations/MalwareBazaarFeed/MalwareBazaarFeed.py
  Packs/FeedMalwareBazaar/Integrations/MalwareBazaarFeed/MalwareBazaarFeed.yml
  Packs/FeedMalwareBazaar/Integrations/MalwareBazaarFeed/MalwareBazaarFeed_test.py
  Packs/FeedMalwareBazaar/ReleaseNotes/1_0_8.md
  Packs/FeedMalwareBazaar/pack_metadata.json
  Packs/iDefense/ReleaseNotes/3_2_9.md
  Packs/iDefense/pack_metadata.json
Labels: docs-approved

#24066 Stop running pipeline
  .gitlab/ci/on-push.yml
  Utils/gitlab/stop_running_pipelines.sh
Labels: docs-approved

#24333 Run zero validate modeling rules
  Packs/RunZero/Integrations/RunZeroEventCollector/RunZeroEventCollector.py
  Packs/RunZero/Integrations/RunZeroEventCollector/RunZeroEventCollector.yml
  Packs/RunZero/ModelingRules/RunZeroModelingRules/RunZeroModelingRules_testdata.json
  Packs/RunZero/ReleaseNotes/1_0_1.md
  Packs/RunZero/pack_metadata.json
Labels: docs-approved

#24170 [ServiceNow] Custom close state from SNOW
  Packs/ServiceNow/Integrations/ServiceNowv2/README.md
  Packs/ServiceNow/Integrations/ServiceNowv2/ServiceNowv2.py
  Packs/ServiceNow/Integrations/ServiceNowv2/ServiceNowv2.yml
  Packs/ServiceNow/Integrations/ServiceNowv2/ServiceNowv2_test.py
  Packs/ServiceNow/Integrations/ServiceNowv2/doc_files/closing-mirror-xsoar.png
  Packs/ServiceNow/Integrations/ServiceNowv2/test_data/response_constants.py
  Packs/ServiceNow/ReleaseNotes/2_5_10.md
  Packs/ServiceNow/pack_metadata.json
Labels: docs-approved

#24279 fix(sekoia-io-cti): broken link in description file
  Packs/SEKOIAIntelligenceCenter/Integrations/SEKOIAIntelligenceCenter/SEKOIAIntelligenceCenter.py
  Packs/SEKOIAIntelligenceCenter/Integrations/SEKOIAIntelligenceCenter/SEKOIAIntelligenceCenter.yml
  Packs/SEKOIAIntelligenceCenter/Integrations/SEKOIAIntelligenceCenter/SEKOIAIntelligenceCenter_description.md
  Packs/SEKOIAIntelligenceCenter/Integrations/SEKOIAIntelligenceCenter/SEKOIAIntelligenceCenter_test.py
  Packs/SEKOIAIntelligenceCenter/ReleaseNotes/1_2_0.md
  Packs/SEKOIAIntelligenceCenter/pack_metadata.json
Labels: Contribution, Partner, Contribution Form Filled

#24306 Cortex code improvements
  Packs/ApiModules/ReleaseNotes/2_2_14.md
  Packs/ApiModules/Scripts/CoreIRApiModule/CoreIRApiModule.py
  Packs/ApiModules/pack_metadata.json
  Packs/CortexXDR/Integrations/CortexXDRIR/CortexXDRIR.py
  Packs/CortexXDR/Integrations/CortexXDRIR/CortexXDRIR.yml
  Packs/CortexXDR/ReleaseNotes/4_10_9.md
  Packs/CortexXDR/pack_metadata.json
Labels: Contribution, Contribution Form Filled, Community

#24341 Adding Log that telling which pack I am installing now
  Tests/Marketplace/search_and_install_packs.py
Labels: docs-approved

#24281 [CortexXDR] add comment_update arg to update_incident command
  Packs/ApiModules/Scripts/CoreIRApiModule/CoreIRApiModule.py
  Packs/ApiModules/Scripts/CoreIRApiModule/CoreIRApiModule_test.py
  Packs/Core/Integrations/CortexCoreIR/CortexCoreIR.py
  Packs/Core/Integrations/CortexCoreIR/CortexCoreIR.yml
  Packs/Core/ReleaseNotes/1_3_26.md
  Packs/Core/pack_metadata.json
  Packs/CortexXDR/Integrations/CortexXDRIR/CortexXDRIR.py
  Packs/CortexXDR/Integrations/CortexXDRIR/CortexXDRIR.yml
  Packs/CortexXDR/Integrations/CortexXDRIR/CortexXDRIR_test.py
  Packs/CortexXDR/ReleaseNotes/4_10_9.md
  Packs/CortexXDR/pack_metadata.json
Labels: docs-approved

#22860 Bug - parisma-access-logout-user domain arg is not required
  Packs/PrismaAccess/Integrations/PrismaAccess/PrismaAccess.py
  Packs/PrismaAccess/Integrations/PrismaAccess/PrismaAccess.yml
  Packs/PrismaAccess/ReleaseNotes/1_0_13.md
  Packs/PrismaAccess/pack_metadata.json
Labels: docs-approved, ForceMerge

#23916 Cisco WebEx Feed Adoption
  Packs/CiscoWebExFeed/.pack-ignore
  Packs/CiscoWebExFeed/Integrations/CiscoWebExFeed/CiscoWebExFeed.py
  Packs/CiscoWebExFeed/Integrations/CiscoWebExFeed/CiscoWebExFeed.yml
  Packs/CiscoWebExFeed/Integrations/CiscoWebExFeed/CiscoWebExFeed_description.md
  Packs/CiscoWebExFeed/Integrations/CiscoWebExFeed/CiscoWebExFeed_test.py
  Packs/CiscoWebExFeed/Integrations/CiscoWebExFeed/README.md
  Packs/CiscoWebExFeed/Integrations/CiscoWebExFeed/commands.txt
  Packs/CiscoWebExFeed/Integrations/CiscoWebExFeed/tests_data_1.json
  Packs/CiscoWebExFeed/Integrations/CiscoWebExFeed/tests_data_2.json
  Packs/CiscoWebExFeed/Playbooks/playbook-Check_WebEx_Feed.yml
  Packs/CiscoWebExFeed/README.md
  Packs/CiscoWebExFeed/ReleaseNotes/1_2_0.json
  Packs/CiscoWebExFeed/ReleaseNotes/1_2_0.md
  Packs/CiscoWebExFeed/TestPlaybooks/playbook-Test_Cisco_WebEx_Feed.yml
  Packs/CiscoWebExFeed/pack_metadata.json
  Tests/conf.json
Labels: docs-approved

#24346 Deprecate ParseEmailFiles and update ParseEmailFilesV2
  Packs/CommonScripts/ReleaseNotes/1_11_21.md
  Packs/CommonScripts/Scripts/ParseEmailFiles/ParseEmailFiles.yml
  Packs/CommonScripts/Scripts/ParseEmailFilesV2/ParseEmailFilesV2.yml
  Packs/CommonScripts/pack_metadata.json
Labels: docs-approved

#24353 Microsoft graph mail single user fetch bug
  Packs/MicrosoftGraphMail/Integrations/MicrosoftGraphListener/MicrosoftGraphListener.py
  Packs/MicrosoftGraphMail/Integrations/MicrosoftGraphListener/MicrosoftGraphListener_test.py
  Packs/MicrosoftGraphMail/ReleaseNotes/1_4_6.md
  Packs/MicrosoftGraphMail/pack_metadata.json
Labels: docs-approved

#24352 Feed blocklist de added detect type
  Packs/FeedBlocklist_de/Integrations/FeedBlocklist_de/FeedBlocklist_de.py
  Packs/FeedBlocklist_de/Integrations/FeedBlocklist_de/FeedBlocklist_de.yml
  Packs/FeedBlocklist_de/ReleaseNotes/1_1_24.md
  Packs/FeedBlocklist_de/pack_metadata.json
Labels: docs-approved

#24365 master hotfix
  Packs/CiscoWebExFeed/Integrations/CiscoWebExFeed/CiscoWebExFeed_test.py
  Packs/CiscoWebExFeed/Integrations/CiscoWebExFeed/test_data/tests_data_1.json
  Packs/CiscoWebExFeed/Integrations/CiscoWebExFeed/test_data/tests_data_2.json
  Packs/MalwareInvestigationAndResponse/ReleaseNotes/2_0_3.md
  Packs/MalwareInvestigationAndResponse/Wizards/wizard-Malware_Investigation_and_Response.json
  Packs/MalwareInvestigationAndResponse/Wizards/wizard-Malware_Investigation_and_Response_6.8.json
  Packs/MalwareInvestigationAndResponse/pack_metadata.json
  Packs/MicrosoftExchangeOnline/Integrations/SecurityAndComplianceV2/README.md
  Packs/Phishing/ReleaseNotes/3_5_4.md
  Packs/Phishing/Wizards/wizard-Phishing.json
  Packs/Phishing/pack_metadata.json
Labels: docs-approved

#24362 Fail on failure test modeling rules
  .gitlab/ci/on-push.yml
Labels: docs-approved

#24369 Fixed the playbook description and the 'Get Device's Process List' pl…
  Packs/CortexXDR/Playbooks/playbook-Cortex_XDR_Malware_-_Investigation_And_Response.yml
  Packs/CortexXDR/Playbooks/playbook-Cortex_XDR_Malware_-_Investigation_And_Response_README.md
  Packs/CortexXDR/ReleaseNotes/4_10_10.md
  Packs/CortexXDR/pack_metadata.json
Labels: docs-approved

#24379 Hashicorp vault specific roles bug
  Packs/HashiCorp-Vault/Integrations/HashiCorpVault/HashiCorpVault.py
  Packs/HashiCorp-Vault/Integrations/HashiCorpVault/HashiCorpVault.yml
  Packs/HashiCorp-Vault/ReleaseNotes/1_1_3.md
  Packs/HashiCorp-Vault/pack_metadata.json
Labels: docs-approved

#24374 Align find email campaign script to native image
  Packs/Campaign/ReleaseNotes/3_2_18.md
  Packs/Campaign/Scripts/FindEmailCampaign/FindEmailCampaign.py
  Packs/Campaign/Scripts/FindEmailCampaign/FindEmailCampaign.yml
  Packs/Campaign/pack_metadata.json
  Tests/docker_native_image_config.json
Labels: docs-approved

#24378 Deprecating Netcraft
  Packs/Netcraft/Integrations/Netcraft/Netcraft.yml
  Packs/Netcraft/ReleaseNotes/1_0_15.md
  Packs/Netcraft/TestPlaybooks/playbook-Netcraft_Test.yml
  Packs/Netcraft/pack_metadata.json
Labels: docs-approved

#24147 [ASM] - Rapid 7 Nexpose update
  Packs/Rapid7_Nexpose/.secrets-ignore
  Packs/Rapid7_Nexpose/Integrations/Rapid7_Nexpose/README.md
  Packs/Rapid7_Nexpose/Integrations/Rapid7_Nexpose/Rapid7_Nexpose.py
  Packs/Rapid7_Nexpose/Integrations/Rapid7_Nexpose/Rapid7_Nexpose.yml
  Packs/Rapid7_Nexpose/Integrations/Rapid7_Nexpose/Rapid7_Nexpose_test.py
  Packs/Rapid7_Nexpose/Integrations/Rapid7_Nexpose/test_data/api_mock/client_get_asset_tags.json
  Packs/Rapid7_Nexpose/Integrations/Rapid7_Nexpose/test_data/expected_context/get_asset_tags_command.json
  Packs/Rapid7_Nexpose/Playbooks/Rapid7_-_Nexpose_-_Enrichment.yml
  Packs/Rapid7_Nexpose/Playbooks/Rapid7_-_Nexpose_-_Enrichment_README.md
  Packs/Rapid7_Nexpose/ReleaseNotes/1_2_2.md
  Packs/Rapid7_Nexpose/TestPlaybooks/playbook-Nexpose_test.yml
  Packs/Rapid7_Nexpose/doc_files/Rapid7_-_Nexpose_-_Enrichment.png
  Packs/Rapid7_Nexpose/pack_metadata.json
Labels: Contribution, docs-approved, Contribution Form Filled, Community

#24408 Remove cisco-asa test-data
  Packs/CiscoASA/ModelingRules/CiscoASA_1_3/CiscoASA_1_3_testdata.json
Labels: docs-approved, ForceMerge

#23615 Prisma sase new commands
  Packs/PrismaAccess/.pack-ignore
  Packs/PrismaAccess/.secrets-ignore
  Packs/PrismaAccess/CONTRIBUTORS.json
  Packs/PrismaAccess/Integrations/PrismaSASE/PrismaSASE.py
  Packs/PrismaAccess/Integrations/PrismaSASE/PrismaSASE.yml
  Packs/PrismaAccess/Integrations/PrismaSASE/PrismaSASE_description.md
  Packs/PrismaAccess/Integrations/PrismaSASE/PrismaSASE_image.png
  Packs/PrismaAccess/Integrations/PrismaSASE/PrismaSASE_test.py
  Packs/PrismaAccess/Integrations/PrismaSASE/README.md
  Packs/PrismaAccess/Integrations/PrismaSASE/command_examples
  Packs/PrismaAccess/Integrations/PrismaSASE/test_data/address-object.json
  Packs/PrismaAccess/Integrations/PrismaSASE/test_data/custom-url-category.json
  Packs/PrismaAccess/Integrations/PrismaSASE/test_data/dynamic-address-group.json
  Packs/PrismaAccess/Integrations/PrismaSASE/test_data/edit-security-rule.json
  Packs/PrismaAccess/Integrations/PrismaSASE/test_data/external-dynamic-list.json
  Packs/PrismaAccess/Integrations/PrismaSASE/test_data/get-config-jobs-by-id-with-parent.json
  Packs/PrismaAccess/Integrations/PrismaSASE/test_data/get-config-jobs-by-id.json
  Packs/PrismaAccess/Integrations/PrismaSASE/test_data/list-address-group.json
  Packs/PrismaAccess/Integrations/PrismaSASE/test_data/list-address-objects.json
  Packs/PrismaAccess/Integrations/PrismaSASE/test_data/list-config-jobs.json
  Packs/PrismaAccess/Integrations/PrismaSASE/test_data/list-custom-url-category.json
  Packs/PrismaAccess/Integrations/PrismaSASE/test_data/list-external-dynamic-list.json
  Packs/PrismaAccess/Integrations/PrismaSASE/test_data/list-security-rules.json
  Packs/PrismaAccess/Integrations/PrismaSASE/test_data/list-tags.json
  Packs/PrismaAccess/Integrations/PrismaSASE/test_data/push-candidate-config.json
  Packs/PrismaAccess/Integrations/PrismaSASE/test_data/security-rule.json
  Packs/PrismaAccess/Integrations/PrismaSASE/test_data/static-address-group.json
  Packs/PrismaAccess/Integrations/PrismaSASE/test_data/tag.json
  Packs/PrismaAccess/Integrations/PrismaSASE/test_data/update-security-rule.json
  Packs/PrismaAccess/README.md
  Packs/PrismaAccess/ReleaseNotes/2_0_0.md
  Packs/PrismaAccess/TestPlaybooks/playbook-PrismaSASE_Test.yml
  Packs/PrismaAccess/pack_metadata.json
  Tests/conf.json
Labels: docs-approved

#23969 [ASM] - EXPANDR-1620 Unclaimed S3 bucket use case
  Packs/AWS-Enrichment-Remediation/Playbooks/AWS_-_Unclaimed_S3_Bucket_Remediation.yml
  Packs/AWS-Enrichment-Remediation/Playbooks/AWS_-_Unclaimed_S3_Bucket_Remediation_README.md
  Packs/AWS-Enrichment-Remediation/Playbooks/AWS_-_Unclaimed_S3_Bucket_Validation.yml
  Packs/AWS-Enrichment-Remediation/Playbooks/AWS_-_Unclaimed_S3_Bucket_Validation_README.md
  Packs/AWS-Enrichment-Remediation/README.md
  Packs/AWS-Enrichment-Remediation/ReleaseNotes/1_1_0.md
  Packs/AWS-Enrichment-Remediation/doc_files/AWS_-_Unclaimed_S3_Bucket_Remediation.png
  Packs/AWS-Enrichment-Remediation/doc_files/AWS_-_Unclaimed_S3_Bucket_Validation.png
  Packs/AWS-Enrichment-Remediation/pack_metadata.json
Labels: Contribution, docs-approved, Contribution Form Filled, Community, pending-contributor

#24411 bump packmetadata apimodules
  Packs/ApiModules/pack_metadata.json
Labels: docs-approved

#24294 [HealthCheck] Core REST API Support
  Packs/HealthCheck/ReleaseNotes/2_0_8.md
  Packs/HealthCheck/Scripts/HealthCheckAPIvalidation/HealthCheckAPIvalidation.py
  Packs/HealthCheck/Scripts/HealthCheckAPIvalidation/HealthCheckAPIvalidation.yml
  Packs/HealthCheck/pack_metadata.json
  Packs/Jira/Classifiers/classifier-mapper-incoming-JiraV2.json
  Packs/Jira/ReleaseNotes/2_0_27.md
  Packs/Jira/pack_metadata.json
Labels: Contribution, docs-approved, Contribution Form Filled, Community

#24371 QRadar mirroring fixes
  Packs/QRadar/Integrations/QRadar_v3/QRadar_v3.py
  Packs/QRadar/Integrations/QRadar_v3/QRadar_v3.yml
  Packs/QRadar/ReleaseNotes/2_4_9.md
  Packs/QRadar/pack_metadata.json
Labels: docs-approved

#24417 Azure active directory didn't work with Client Credentials
  Packs/MicrosoftGraphUser/Integrations/MicrosoftGraphUser/MicrosoftGraphUser.py
  Packs/MicrosoftGraphUser/ReleaseNotes/1_5_12.md
  Packs/MicrosoftGraphUser/pack_metadata.json
Labels: docs-approved

#24405 Updating Action
  .github/workflows/auto-merge-dockers.yml
Labels: docs-approved

#23945 twitter_v2
  Packs/Twitter/.secrets-ignore
  Packs/Twitter/Integrations/Twitter/Twitter.yml
  Packs/Twitter/Integrations/Twitterv2/README.md
  Packs/Twitter/Integrations/Twitterv2/Twitterv2.py
  Packs/Twitter/Integrations/Twitterv2/Twitterv2.yml
  Packs/Twitter/Integrations/Twitterv2/Twitterv2_description.md
  Packs/Twitter/Integrations/Twitterv2/Twitterv2_image.png
  Packs/Twitter/Integrations/Twitterv2/Twitterv2_test.py
  Packs/Twitter/Integrations/Twitterv2/command_examples
  Packs/Twitter/Integrations/Twitterv2/test_data/test_data.json
  Packs/Twitter/README.md
  Packs/Twitter/ReleaseNotes/2_0_0.json
  Packs/Twitter/ReleaseNotes/2_0_0.md
  Packs/Twitter/TestPlaybooks/playbook-Test_Twitter_v2.yml
  Packs/Twitter/pack_metadata.json
  Tests/conf.json
Labels: docs-approved

#24059 Override flag fix
  .gitlab/ci/on-push.yml
  Tests/Marketplace/configure_and_install_packs.py
  Tests/Marketplace/install_packs.sh
  Tests/Marketplace/upload_packs.py
  Tests/scripts/collect_tests/collect_tests.py
  Tests/scripts/infrastructure_tests/test_collect_tests.py
Labels: docs-approved

#24419 Fix AzureStorageApiModule bug
  Packs/ApiModules/Scripts/MicrosoftAzureStorageApiModule/MicrosoftAzureStorageApiModule.py
  Packs/AzureStorageContainer/ReleaseNotes/1_0_8.md
  Packs/AzureStorageContainer/pack_metadata.json
  Packs/AzureStorageFileShare/ReleaseNotes/1_0_6.md
  Packs/AzureStorageFileShare/pack_metadata.json
  Packs/AzureStorageQueue/ReleaseNotes/1_0_6.md
  Packs/AzureStorageQueue/pack_metadata.json
  Packs/AzureStorageTable/ReleaseNotes/1_0_6.md
  Packs/AzureStorageTable/pack_metadata.json
Labels: docs-approved

#24179 Tanium v4 support
  Packs/TaniumThreatResponse/Integrations/TaniumThreatResponseV2/README.md
  Packs/TaniumThreatResponse/Integrations/TaniumThreatResponseV2/TaniumThreatResponseV2.py
  Packs/TaniumThreatResponse/Integrations/TaniumThreatResponseV2/TaniumThreatResponseV2.yml
  Packs/TaniumThreatResponse/Integrations/TaniumThreatResponseV2/TaniumThreatResponseV2_test.py
  Packs/TaniumThreatResponse/ReleaseNotes/2_1_6.md
  Packs/TaniumThreatResponse/TestPlaybooks/playbook-Tanium_Threat_Response_V2_Test.yml
  Packs/TaniumThreatResponse/pack_metadata.json
  Tests/conf.json
Labels: docs-approved

#24418 CSP URL regex doesnt capture defanged IP based URLs
  Packs/Base/ReleaseNotes/1_31_60.md
  Packs/Base/Scripts/CommonServerPython/CommonServerPython.py
  Packs/Base/Scripts/CommonServerPython/CommonServerPython_test.py
  Packs/Base/pack_metadata.json
Labels: docs-approved

#23562 feat: Lacework integration was updated to use APIv2 [APIv1 Deprecation]
  Packs/Lacework/.pack-ignore
  Packs/Lacework/.secrets-ignore
  Packs/Lacework/Classifiers/classifier-Lacework.json
  Packs/Lacework/Classifiers/classifier-Lacework_5_9_9.json
  Packs/Lacework/Classifiers/classifier-mapper-incoming-Lacework.json
  Packs/Lacework/IncidentFields/incidentfield-Lacework_Recommendation_Account_Alias.json
  Packs/Lacework/IncidentFields/incidentfield-Lacework_Recommendation_Account_Id.json
  Packs/Lacework/IncidentFields/incidentfield-Lacework_Recommendation_Id.json
  Packs/Lacework/IncidentFields/incidentfield-Lacework_Recommendation_Title.json
  Packs/Lacework/IncidentTypes/incidenttype-Lacework_Alert.json
  Packs/Lacework/Integrations/Lacework/Lacework.py
  Packs/Lacework/Integrations/Lacework/Lacework.yml
  Packs/Lacework/Integrations/Lacework/Lacework_description.md
  Packs/Lacework/Integrations/Lacework/Lacework_image.png
  Packs/Lacework/Integrations/Lacework/README.md
  Packs/Lacework/Integrations/Lacework/command_examples.txt
  Packs/Lacework/ReleaseNotes/2_0_0.json
  Packs/Lacework/ReleaseNotes/2_0_0.md
  Packs/Lacework/pack_metadata.json
Labels: Contribution, Contribution Form Filled, Community, pending-contributor

#24211 remove 6.2 doc links from script documentation
  Packs/Base/Scripts/GetIncidentsByQuery/README.md
  Packs/Campaign/Scripts/GetCampaignIncidentsInfo/README.md
  Packs/Campaign/Scripts/GetCampaignLowSimilarityIncidentsInfo/README.md
  Packs/Campaign/Scripts/PerformActionOnCampaignIncidents/README.md
  Packs/Campaign/Scripts/SplitCampaignContext/README.md
  Packs/CommonScripts/Scripts/CompareIncidentsLabels/README.md
  Packs/CommonScripts/Scripts/CopyContextToField/README.md
  Packs/CommonScripts/Scripts/DeleteContext/README.md
  Packs/CommonScripts/Scripts/ExtractIndicatorsFromTextFile/README.md
  Packs/CommonScripts/Scripts/ExtractIndicatorsFromWordFile/README.md
  Packs/CommonScripts/Scripts/FindIncidentsWithIndicator/README.md
  Packs/CommonScripts/Scripts/FindSimilarIncidentsV2/README.md
  Packs/CommonScripts/Scripts/IndicatorMaliciousRatioCalculation/README.md
  Packs/CommonScripts/Scripts/MarkRelatedIncidents/README.md
  Packs/CommonScripts/Scripts/SearchIncidentsV2/README.md
  Packs/CommonScripts/Scripts/SetAndHandleEmpty/README.md
  Packs/CommonScripts/Scripts/SetByIncidentId/README.md
  Packs/CrowdStrikeFalconStreamingV2/Scripts/CrowdStrikeStreamingPreProcessing/README.md
  Packs/CyrenInboxSecurity/Scripts/CyrenFindSimilarIncidents/README.md
  Packs/EmailCommunication/Scripts/PreprocessEmail/README.md
  Packs/EmailCommunication/Scripts/SendEmailReply/README.md
  Packs/ExpanseV2/Scripts/ExpanseGenerateIssueMapWidgetScript/README.md
  Packs/GroupIB_ThreatIntelligenceAttribution/Scripts/GIBIncidentUpdate/README.md
  Packs/GroupIB_ThreatIntelligenceAttribution/Scripts/GIBIncidentUpdateIncludingClosed/README.md
  Packs/IntegrationsAndIncidentsHealthCheck/Scripts/CopyLinkedAnalystNotes/README.md
  Packs/IntegrationsAndIncidentsHealthCheck/Scripts/GetFailedTasks/README.md
  Packs/NCSCCyberAsssessmentFramework/Scripts/NCSCReportDetails/README.md
  Packs/NCSCCyberAsssessmentFramework/Scripts/NCSCReportDetailsA/README.md
  Packs/NCSCCyberAsssessmentFramework/Scripts/NCSCReportDetailsB/README.md
  Packs/NCSCCyberAsssessmentFramework/Scripts/NCSCReportDetailsC/README.md
  Packs/NCSCCyberAsssessmentFramework/Scripts/NCSCReportDetailsD/README.md
  Packs/NCSCCyberAsssessmentFramework/Scripts/NCSCReportOverview/README.md
  Packs/OnboardingIntegration/Scripts/OnboardingCleanup/README.md
  Packs/PaloAltoNetworks_IoT3rdParty/Scripts/SendPANWIoTDevicesToCiscoISE/README.md
  Packs/ShiftManagement-AssignToNextShift/Scripts/AssignToNextShift/README.md
  Packs/ShiftManagement/Scripts/AssignAnalystToIncidentOOO/README.md
  Packs/ShiftManagement/Scripts/AssignToNextShiftOOO/README.md
  Packs/ShiftManagement/Scripts/CreateChannelWrapper/README.md
Labels: docs-approved

#23983 fixes for **aws-ec2-revoke-security-group-egress-rule**
  Packs/AWS-EC2/Integrations/AWS-EC2/AWS-EC2.py
  Packs/AWS-EC2/Integrations/AWS-EC2/AWS-EC2.yml
  Packs/AWS-EC2/ReleaseNotes/1_2_30.md
  Packs/AWS-EC2/pack_metadata.json
Labels: docs-approved

#24410 Fix xsoar linter failures FeedJsonApiModule
  Packs/AccentureCTI_Feed/Integrations/ACTIIndicatorFeed/ACTIIndicatorFeed.yml
  Packs/AccentureCTI_Feed/ReleaseNotes/1_1_6.md
  Packs/AccentureCTI_Feed/pack_metadata.json
  Packs/ApiModules/.pack-ignore
  Packs/ApiModules/ReleaseNotes/2_2_15.md
  Packs/ApiModules/Scripts/JSONFeedApiModule/JSONFeedApiModule.py
  Packs/ApiModules/pack_metadata.json
  Packs/FeedAWS/Integrations/FeedAWS/FeedAWS.yml
  Packs/FeedAWS/ReleaseNotes/1_1_27.md
  Packs/FeedAWS/pack_metadata.json
  Packs/FeedFastly/Integrations/FeedFastly/FeedFastly.yml
  Packs/FeedFastly/ReleaseNotes/1_1_24.md
  Packs/FeedFastly/pack_metadata.json
  Packs/FeedGCPWhitelist/Integrations/FeedGoogleIPRanges/FeedGoogleIPRanges.yml
  Packs/FeedGCPWhitelist/ReleaseNotes/2_0_8.md
  Packs/FeedGCPWhitelist/pack_metadata.json
  Packs/FeedIntel471/Integrations/Intel471Actors/Intel471Actors.yml
  Packs/FeedIntel471/Integrations/Intel471Malware/Intel471Malware.yml
  Packs/FeedIntel471/Integrations/Intel471MalwareIndicator/Intel471MalwareIndicator.yml
  Packs/FeedIntel471/ReleaseNotes/2_0_17.md
  Packs/FeedIntel471/pack_metadata.json
  Packs/FeedJSON/.pack-ignore
  Packs/FeedJSON/ReleaseNotes/1_1_27.md
  Packs/FeedJSON/pack_metadata.json
  Packs/FeedMalwareBazaar/Integrations/MalwareBazaarFeed/MalwareBazaarFeed.yml
  Packs/FeedMalwareBazaar/ReleaseNotes/1_0_9.md
  Packs/FeedMalwareBazaar/pack_metadata.json
  Packs/iDefense/ReleaseNotes/3_2_10.md
  Packs/iDefense/pack_metadata.json
Labels: docs-approved

#24382 Fixed an issue where it broke a backward compatibility.
  Packs/FiltersAndTransformers/ReleaseNotes/1_2_9.md
  Packs/FiltersAndTransformers/Scripts/IfThenElse/IfThenElse.js
  Packs/FiltersAndTransformers/pack_metadata.json
Labels: Contribution, docs-approved, Contribution Form Filled, Community

#24272 Execution metrics default content type
  Packs/Base/ReleaseNotes/1_31_61.md
  Packs/Base/Scripts/CommonServerPython/CommonServerPython.py
  Packs/Base/Scripts/CommonServerPython/CommonServerPython_test.py
  Packs/Base/pack_metadata.json
Labels: docs-approved

#24433 1.10.0
  .circleci/config.yml
  .gitlab/ci/global.yml
  .gitlab/ci/on-push.yml
  Tests/scripts/collect_tests/constants.py
  Tests/scripts/create_artifacts_graph/create_artifacts.py
  Tests/scripts/infrastructure_tests/test_collect_tests.py
  Tests/scripts/validate.sh
  Tests/secrets_white_list.json
  poetry.lock
  pyproject.toml
Labels: docs-approved

#24332 [PAN-OS] - add audit-comment support to pan-os-edit-rule command
  Packs/PAN-OS/Integrations/Panorama/Panorama.py
  Packs/PAN-OS/Integrations/Panorama/Panorama.yml
  Packs/PAN-OS/Integrations/Panorama/Panorama_test.py
  Packs/PAN-OS/ReleaseNotes/1_16_7.md
  Packs/PAN-OS/pack_metadata.json
Labels: docs-approved

#24377 Anomali bug in confidence parama
  Packs/Anomali_ThreatStream/Integrations/AnomaliThreatStreamv3/AnomaliThreatStreamv3.py
  Packs/Anomali_ThreatStream/Integrations/AnomaliThreatStreamv3/AnomaliThreatStreamv3.yml
  Packs/Anomali_ThreatStream/Integrations/AnomaliThreatStreamv3/AnomaliThreatStreamv3_test.py
  Packs/Anomali_ThreatStream/ReleaseNotes/2_0_27.md
  Packs/Anomali_ThreatStream/pack_metadata.json
Labels: docs-approved

#24063 Cortex XDR - First SSO Access
  Packs/CommonPlaybooks/Playbooks/playbook-SIEM_-_Search_for_Failed_logins.yml
  Packs/CommonPlaybooks/Playbooks/playbook-SIEM_-_Search_for_Failed_logins_README.md
  Packs/CommonPlaybooks/Playbooks/playbook-User_Investigation_-_Generic.yml
  Packs/CommonPlaybooks/Playbooks/playbook-User_Investigation_-_Generic_README.md
  Packs/CommonPlaybooks/ReleaseNotes/2_3_33.md
  Packs/CommonPlaybooks/doc_files/SIEM_-_Search_for_Failed_logins.png
  Packs/CommonPlaybooks/doc_files/User_Investigation_-_Generic.png
  Packs/CommonPlaybooks/pack_metadata.json
  Packs/CommonTypes/IncidentFields/incidentfield-ASN_Name.json
  Packs/CommonTypes/ReleaseNotes/3_3_48.md
  Packs/CommonTypes/pack_metadata.json
  Packs/CortexXDR/IncidentFields/incidentfield-XDR_Investigation_results.json
  Packs/CortexXDR/Layouts/layoutscontainer-Cortex_XDR_Incident.json
  Packs/CortexXDR/Playbooks/Cortex_XDR_Alerts_Handling.yml
  Packs/CortexXDR/Playbooks/playbook-Cortex_XDR_-_Cloud_Cryptomining_-_Set_Verdict_README.md
  Packs/CortexXDR/Playbooks/playbook-Cortex_XDR_-_First_SSO_Access.yml
  Packs/CortexXDR/Playbooks/playbook-Cortex_XDR_-_First_SSO_Access_-_Set_Verdict.yml
  Packs/CortexXDR/Playbooks/playbook-Cortex_XDR_-_First_SSO_Access_-_Set_Verdict_README.md
  Packs/CortexXDR/Playbooks/playbook-Cortex_XDR_-_First_SSO_Access_README.md
  Packs/CortexXDR/ReleaseNotes/4_10_13.md
  Packs/CortexXDR/doc_files/Cortex_XDR_-_First_SSO_Access.png
  Packs/CortexXDR/doc_files/Cortex_XDR_-_First_SSO_Access_-_Set_Verdict.png
  Packs/CortexXDR/doc_files/Cortex_XDR_Alerts_Handling.png
  Packs/CortexXDR/pack_metadata.json
  Packs/Okta/Playbooks/playbook-Okta_-_User_Investigation.yml
  Packs/Okta/Playbooks/playbook-Okta_-_User_Investigation_README.md
  Packs/Okta/ReleaseNotes/3_1_8.md
  Packs/Okta/doc_files/Okta_-_User_Investigation.png
  Packs/Okta/pack_metadata.json
Labels: docs-approved

#24469 Updated the watch checks step
  .github/workflows/auto-merge-dockers.yml
Labels: docs-approved

#24373 Update ML docker image
  Packs/Base/ReleaseNotes/1_31_62.md
  Packs/Base/Scripts/DBotTrainTextClassifierV2/DBotTrainTextClassifierV2.yml
  Packs/Base/pack_metadata.json
Labels: docs-approved

#24470 fix check devcontainer.json update
  .github/workflows/check-devcontainer.yml
Labels: docs-approved

#24423 add `check-merge-conflict` pre-commit hook
  .pre-commit-config.yaml
Labels: docs-approved

#24442 Trend micro vision one
  Packs/TrendMicroVisionOne/Integrations/TrendMicroVisionOneV3/TrendMicroVisionOneV3.yml
  Packs/TrendMicroVisionOne/ReleaseNotes/2_0_2.md
  Packs/TrendMicroVisionOne/pack_metadata.json
Labels: Contribution, docs-approved, Partner, Contribution Form Filled

#23360 Cisco threat grid integration
  Packs/ThreatGrid/.pack-ignore
  Packs/ThreatGrid/.secrets-ignore
  Packs/ThreatGrid/Integrations/ThreatGrid/ThreatGrid.yml
  Packs/ThreatGrid/Integrations/ThreatGridv2/Pipfile
  Packs/ThreatGrid/Integrations/ThreatGridv2/Pipfile.lock
  Packs/ThreatGrid/Integrations/ThreatGridv2/README.md
  Packs/ThreatGrid/Integrations/ThreatGridv2/ThreatGridv2.py
  Packs/ThreatGrid/Integrations/ThreatGridv2/ThreatGridv2.yml
  Packs/ThreatGrid/Integrations/ThreatGridv2/ThreatGridv2_description.md
  Packs/ThreatGrid/Integrations/ThreatGridv2/ThreatGridv2_image.png
  Packs/ThreatGrid/Integrations/ThreatGridv2/ThreatGridv2_test.py
  Packs/ThreatGrid/Integrations/ThreatGridv2/command_examples.txt
  Packs/ThreatGrid/Integrations/ThreatGridv2/test_data/associated_samples_list.json
  Packs/ThreatGrid/Integrations/ThreatGridv2/test_data/domain_associated_ips.json
  Packs/ThreatGrid/Integrations/ThreatGridv2/test_data/domain_associated_urls.json
  Packs/ThreatGrid/Integrations/ThreatGridv2/test_data/feeds.json
  Packs/ThreatGrid/Integrations/ThreatGridv2/test_data/input_search_query.json
  Packs/ThreatGrid/Integrations/ThreatGridv2/test_data/ip_associated_domains.json
  Packs/ThreatGrid/Integrations/ThreatGridv2/test_data/ip_associated_urls.json
  Packs/ThreatGrid/Integrations/ThreatGridv2/test_data/rate_limit.json
  Packs/ThreatGrid/Integrations/ThreatGridv2/test_data/sample_analysis.json
  Packs/ThreatGrid/Integrations/ThreatGridv2/test_data/sample_get.json
  Packs/ThreatGrid/Integrations/ThreatGridv2/test_data/sample_upload.json
  Packs/ThreatGrid/Integrations/ThreatGridv2/test_data/search.json
  Packs/ThreatGrid/Integrations/ThreatGridv2/test_data/specific_feed.json
  Packs/ThreatGrid/Integrations/ThreatGridv2/test_data/submission_search.json
  Packs/ThreatGrid/Integrations/ThreatGridv2/test_data/whoami.json
  Packs/ThreatGrid/Playbooks/playbook-Detonate_File_-_ThreatGrid.yml
  Packs/ThreatGrid/Playbooks/playbook-Detonate_File_-_ThreatGrid_v2.yml
  Packs/ThreatGrid/Playbooks/playbook-Detonate_File_-_ThreatGrid_v2_README.md
  Packs/ThreatGrid/Playbooks/playbook-Detonate_URL_-_ThreatGrid.yml
  Packs/ThreatGrid/Playbooks/playbook-Detonate_URL_-_ThreatGrid_v2.yml
  Packs/ThreatGrid/Playbooks/playbook-Detonate_URL_-_ThreatGrid_v2_README.md
  Packs/ThreatGrid/ReleaseNotes/2_0_0.md
  Packs/ThreatGrid/TestPlaybooks/playbook-ThreatGrid_v2_Test.yml
  Packs/ThreatGrid/doc_files/Detonate_File_-_ThreatGrid_v2.png
  Packs/ThreatGrid/doc_files/Detonate_URL_-_ThreatGrid_v2.png
  Packs/ThreatGrid/pack_metadata.json
  Tests/conf.json
Labels: Contribution, docs-approved, Contribution Form Filled, Community

#24021 add-FiltersAndTransformers
  Tests/Marketplace/core_packs_xpanse_list.json
Labels: docs-approved

#23626 Corelight Zeek Modeling & Parsing
  Packs/CorelightZeek/.pack-ignore
  Packs/CorelightZeek/.secrets-ignore
  Packs/CorelightZeek/ModelingRules/CorelightZeek/CorelightZeek.xif
  Packs/CorelightZeek/ModelingRules/CorelightZeek/CorelightZeek.yml
  Packs/CorelightZeek/ModelingRules/CorelightZeek/CorelightZeek_schema.json
  Packs/CorelightZeek/ParsingRules/CorelightZeek/CorelightZeek.xif
  Packs/CorelightZeek/ParsingRules/CorelightZeek/CorelightZeek.yml
  Packs/CorelightZeek/README.md
  Packs/CorelightZeek/pack_metadata.json
Labels: docs-approved

#24375 [Deprecation Management] Search Endpoints By Hash - Generic V2 playbook
  Packs/CommonPlaybooks/Playbooks/playbook-Search_Endpoints_By_Hash_-_Generic_V2.yml
  Packs/CommonPlaybooks/Playbooks/playbook-Search_Endpoints_By_Hash_-_Generic_V2_README.md
  Packs/CommonPlaybooks/ReleaseNotes/2_3_34.md
  Packs/CommonPlaybooks/doc_files/Search_Endpoints_By_Hash_-_Generic_V2.png
  Packs/CommonPlaybooks/pack_metadata.json
Labels: docs-approved

#24437 fix(SEKOIAIntelligenceCenter): fix endpoint for test command
  Packs/SEKOIAIntelligenceCenter/Integrations/SEKOIAIntelligenceCenter/SEKOIAIntelligenceCenter.py
  Packs/SEKOIAIntelligenceCenter/Integrations/SEKOIAIntelligenceCenter/SEKOIAIntelligenceCenter.yml
  Packs/SEKOIAIntelligenceCenter/Integrations/SEKOIAIntelligenceCenter/SEKOIAIntelligenceCenter_test.py
  Packs/SEKOIAIntelligenceCenter/ReleaseNotes/1_2_1.md
  Packs/SEKOIAIntelligenceCenter/pack_metadata.json
Labels: Contribution, docs-approved, Partner, Contribution Form Filled, pending-contributor

#24372 Add manager details Okta_v2
  Packs/Okta/Integrations/Okta_v2/Okta_v2.py
  Packs/Okta/Integrations/Okta_v2/Okta_v2.yml
  Packs/Okta/Integrations/Okta_v2/Okta_v2_test.py
  Packs/Okta/Integrations/Okta_v2/README.md
  Packs/Okta/ReleaseNotes/3_1_9.md
  Packs/Okta/pack_metadata.json
Labels: docs-approved, ForceMerge

#21350 Recreate Quttera branch
  Packs/QutteraWebsiteMalwareScanner/.pack-ignore
  Packs/QutteraWebsiteMalwareScanner/.secrets-ignore
  Packs/QutteraWebsiteMalwareScanner/Author_image.png
  Packs/QutteraWebsiteMalwareScanner/Integrations/QutteraWebsiteMalwareScanner/.secrets-ignore
  Packs/QutteraWebsiteMalwareScanner/Integrations/QutteraWebsiteMalwareScanner/Pipfile
  Packs/QutteraWebsiteMalwareScanner/Integrations/QutteraWebsiteMalwareScanner/Pipfile.lock
  Packs/QutteraWebsiteMalwareScanner/Integrations/QutteraWebsiteMalwareScanner/QutteraWebsiteMalwareScanner.py
  Packs/QutteraWebsiteMalwareScanner/Integrations/QutteraWebsiteMalwareScanner/QutteraWebsiteMalwareScanner.yml
  Packs/QutteraWebsiteMalwareScanner/Integrations/QutteraWebsiteMalwareScanner/QutteraWebsiteMalwareScanner_description.md
  Packs/QutteraWebsiteMalwareScanner/Integrations/QutteraWebsiteMalwareScanner/QutteraWebsiteMalwareScanner_image.png
  Packs/QutteraWebsiteMalwareScanner/Integrations/QutteraWebsiteMalwareScanner/QutteraWebsiteMalwareScanner_test.py
  Packs/QutteraWebsiteMalwareScanner/Integrations/QutteraWebsiteMalwareScanner/README.md
  Packs/QutteraWebsiteMalwareScanner/Integrations/QutteraWebsiteMalwareScanner/command_examples.txt
  Packs/QutteraWebsiteMalwareScanner/README.md
  Packs/QutteraWebsiteMalwareScanner/pack_metadata.json
Labels: Contribution, docs-approved, Partner, ready-for-instance-test, Contribution Form Filled, pending-contributor

#24489 Added xpanse to FiltersAndTransformers
  Packs/FiltersAndTransformers/pack_metadata.json
Labels: docs-approved

#24491 Ignore IF100
  Packs/CommonTypes/.pack-ignore
Labels: docs-approved

#24404 Hiding this pack after deprecating it
  Packs/Netcraft/pack_metadata.json
Labels: docs-approved

#24334 CiscoISE Content
  Packs/cisco-ise/ModelingRules/cisco-ise/cisco-ise.xif
  Packs/cisco-ise/ModelingRules/cisco-ise/cisco-ise.yml
  Packs/cisco-ise/ModelingRules/cisco-ise/cisco-ise_schema.json
  Packs/cisco-ise/ParsingRules/cisco-ise/cisco-ise.xif
  Packs/cisco-ise/ParsingRules/cisco-ise/cisco-ise.yml
  Packs/cisco-ise/README.md
  Packs/cisco-ise/ReleaseNotes/1_0_9.md
  Packs/cisco-ise/pack_metadata.json
Labels: docs-approved

#24432 Cisco stealth watch remove protocol
  Packs/CiscoStealthwatch/ModelingRules/CiscoStealthwatch/CiscoStealthwatch.xif
  Packs/CiscoStealthwatch/ReleaseNotes/1_0_10.md
  Packs/CiscoStealthwatch/pack_metadata.json
Labels: docs-approved

#24337 Neosec fix time format bug
  Packs/Neosec/Integrations/Neosec/Neosec.py
  Packs/Neosec/ReleaseNotes/1_0_2.md
  Packs/Neosec/pack_metadata.json
Labels: Contribution, Partner, Contribution Form Filled, pending-contributor

#24507 Temporary change to create graph
  .gitlab/ci/on-push.yml
Labels: docs-approved, ForceMerge

#24505 1.10.1 hotfix
  .gitlab/ci/on-push.yml
  poetry.lock
  pyproject.toml
Labels: docs-approved

#24308 Feature/splunk/edit disposition
  Packs/SplunkPy/Integrations/SplunkPy/README.md
  Packs/SplunkPy/Integrations/SplunkPy/SplunkPy.py
  Packs/SplunkPy/Integrations/SplunkPy/SplunkPy.yml
  Packs/SplunkPy/ReleaseNotes/3_0_9.md
  Packs/SplunkPy/pack_metadata.json
Labels: Contribution, docs-approved, Contribution Form Filled, Community, pending-contributor

#24497 Fixed an issue where some operators with `path` didn't work to nested…
  Packs/CommunityCommonScripts/ReleaseNotes/1_0_7.md
  Packs/CommunityCommonScripts/Scripts/ExtFilter/ExtFilter.py
  Packs/CommunityCommonScripts/Scripts/ExtFilter/ExtFilter.yml
  Packs/CommunityCommonScripts/Scripts/ExtFilter/README.md
  Packs/CommunityCommonScripts/Scripts/ExtFilter/test_data/test-1.json
  Packs/CommunityCommonScripts/pack_metadata.json
Labels: Contribution, docs-approved, Contribution Form Filled, Community

#24493 Wildfire verdicts c2 fix
  Packs/Palo_Alto_Networks_WildFire/Integrations/Palo_Alto_Networks_WildFire_v2/Palo_Alto_Networks_WildFire_v2.py
  Packs/Palo_Alto_Networks_WildFire/Integrations/Palo_Alto_Networks_WildFire_v2/Palo_Alto_Networks_WildFire_v2_test.py
  Packs/Palo_Alto_Networks_WildFire/ReleaseNotes/2_1_15.md
  Packs/Palo_Alto_Networks_WildFire/pack_metadata.json
Labels: Contribution, docs-approved, Contribution Form Filled, Community, pending-contributor

#24511 Update email
  Packs/VaronisDataSecurityPlatform/pack_metadata.json
Labels: Contribution, docs-approved, Partner, Contribution Form Filled, pending-contributor

#24363 Updating EIQ Extension Settings
  Packs/EclecticIQ/Integrations/EclecticIQv2/EclecticIQv2.py
  Packs/EclecticIQ/Integrations/EclecticIQv2/EclecticIQv2.yml
  Packs/EclecticIQ/Integrations/EclecticIQv2/EclecticIQv2_test.py
  Packs/EclecticIQ/ReleaseNotes/2_0_2.md
  Packs/EclecticIQ/pack_metadata.json
Labels: Contribution, Partner, Contribution Form Filled

#24409 CheckPoint Threat Emulation / Sandblast - Fix get_dbotscore()
  Packs/CheckPointSandBlast/Integrations/CheckPointSandBlast/CheckPointSandBlast.py
  Packs/CheckPointSandBlast/ReleaseNotes/1_0_5.md
  Packs/CheckPointSandBlast/pack_metadata.json
Labels: Contribution, Contribution Form Filled, Community

#24471 Adding re-installation
  Tests/Marketplace/search_and_install_packs.py
Labels: docs-approved, ForceMerge

#23574 [Marketplace Contribution] Picus NG Content Pack
  Packs/PicusNGAutomation/.pack-ignore
  Packs/PicusNGAutomation/.secrets-ignore
  Packs/PicusNGAutomation/Author_image.png
  Packs/PicusNGAutomation/Integrations/PicusNG/PicusNG.py
  Packs/PicusNGAutomation/Integrations/PicusNG/PicusNG.yml
  Packs/PicusNGAutomation/Integrations/PicusNG/PicusNG_description.md
  Packs/PicusNGAutomation/Integrations/PicusNG/PicusNG_image.png
  Packs/PicusNGAutomation/Integrations/PicusNG/PicusNG_test.py
  Packs/PicusNGAutomation/Integrations/PicusNG/Pipfile
  Packs/PicusNGAutomation/Integrations/PicusNG/Pipfile.lock
  Packs/PicusNGAutomation/Integrations/PicusNG/README.md
  Packs/PicusNGAutomation/Integrations/PicusNG/command_examples
  Packs/PicusNGAutomation/Integrations/PicusNG/test_data/createSimulation.json
  Packs/PicusNGAutomation/Integrations/PicusNG/test_data/get_AgentDetail.json
  Packs/PicusNGAutomation/Integrations/PicusNG/test_data/get_AgentList.json
  Packs/PicusNGAutomation/Integrations/PicusNG/test_data/get_IntegrationAgentList.json
  Packs/PicusNGAutomation/Integrations/PicusNG/test_data/get_LatestSimulationResult.json
  Packs/PicusNGAutomation/Integrations/PicusNG/test_data/get_MitigationDevices.json
  Packs/PicusNGAutomation/Integrations/PicusNG/test_data/get_SignatureList.json
  Packs/PicusNGAutomation/Integrations/PicusNG/test_data/get_SimulationActions.json
  Packs/PicusNGAutomation/Integrations/PicusNG/test_data/get_SimulationDetail.json
  Packs/PicusNGAutomation/Integrations/PicusNG/test_data/get_SimulationList.json
  Packs/PicusNGAutomation/Integrations/PicusNG/test_data/get_SimulationResult.json
  Packs/PicusNGAutomation/Integrations/PicusNG/test_data/get_SimulationThreats.json
  Packs/PicusNGAutomation/Integrations/PicusNG/test_data/get_TemplateList.json
  Packs/PicusNGAutomation/Integrations/PicusNG/test_data/simulateNow.json
  Packs/PicusNGAutomation/Pipfile
  Packs/PicusNGAutomation/Pipfile.lock
  Packs/PicusNGAutomation/Playbooks/PicusNG.yml
  Packs/PicusNGAutomation/Playbooks/PicusNG_README.md
  Packs/PicusNGAutomation/README.md
  Packs/PicusNGAutomation/doc_files/PICUS_NG_-_Simulation_Validation_Automation.png
  Packs/PicusNGAutomation/doc_files/search_integration.png
  Packs/PicusNGAutomation/doc_files/test_integration.png
  Packs/PicusNGAutomation/pack_metadata.json
  package-lock.json
  package.json
Labels: Contribution, Partner, Contribution Form Filled, pending-contributor

#24102 Packs/Reco: Integration with XSOAR
  Packs/Reco/.pack-ignore
  Packs/Reco/.secrets-ignore
  Packs/Reco/Author_image.png
  Packs/Reco/Classifier/classifier-Reco_Incident_Mapper.json
  Packs/Reco/IncidentTypes/incidenttype-RecoFinding.json
  Packs/Reco/Integrations/Reco/Pipfile
  Packs/Reco/Integrations/Reco/Pipfile.lock
  Packs/Reco/Integrations/Reco/README.md
  Packs/Reco/Integrations/Reco/Reco.py
  Packs/Reco/Integrations/Reco/Reco.yml
  Packs/Reco/Integrations/Reco/Reco_image.png
  Packs/Reco/Integrations/Reco/Reco_test.py
  Packs/Reco/Integrations/Reco/test_utils/structs.py
  Packs/Reco/Layouts/layoutscontainer-Reco_Finding.json
  Packs/Reco/README.md
  Packs/Reco/pack_metadata.json
Labels: Contribution, docs-approved, Partner, Contribution Form Filled, pending-contributor

#24552 Tanium readme update
  Packs/TaniumThreatResponse/Integrations/TaniumThreatResponseV2/README.md
  Packs/TaniumThreatResponse/ReleaseNotes/2_1_7.md
  Packs/TaniumThreatResponse/pack_metadata.json
Labels: docs-approved

#24516 Deprecated Volatility.
  Packs/Volatility/ReleaseNotes/1_0_2.md
  Packs/Volatility/Scripts/Volatility/README.md
  Packs/Volatility/Scripts/Volatility/Volatility.yml
  Packs/Volatility/pack_metadata.json
Labels: docs-approved

#24535 [ASM] - Updating Rapid7 - Nexpose - Enrichment playbook
  Packs/Rapid7_Nexpose/Playbooks/Rapid7_-_Nexpose_-_Enrichment.yml
  Packs/Rapid7_Nexpose/ReleaseNotes/1_2_3.md
  Packs/Rapid7_Nexpose/pack_metadata.json
Labels: Contribution, Contribution Form Filled, Community

#24480 Changed headers for fireeye-nx-get-artifacts-by-alert command
  Packs/FireEyeNX/.pack-ignore
  Packs/FireEyeNX/Integrations/FireEyeNX/FireEyeNX.py
  Packs/FireEyeNX/Integrations/FireEyeNX/FireEyeNX.yml
  Packs/FireEyeNX/Integrations/FireEyeNX/FireEyeNX_test.py
  Packs/FireEyeNX/ReleaseNotes/1_1_10.md
  Packs/FireEyeNX/ReleaseNotes/1_1_14.md
  Packs/FireEyeNX/pack_metadata.json
Labels: docs-approved

#24494 Added validation for base URL fireeye HX
  Packs/FireEyeHX/Integrations/FireEyeHXv2/FireEyeHXv2.py
  Packs/FireEyeHX/Integrations/FireEyeHXv2/FireEyeHXv2.yml
  Packs/FireEyeHX/Integrations/FireEyeHXv2/FireEyeHXv2_test.py
  Packs/FireEyeHX/ReleaseNotes/2_3_1.md
  Packs/FireEyeHX/pack_metadata.json
Labels: docs-approved

#24439 Add O365DefenderSafeLinks atp-policy-get and atp-policy-set commands
  Packs/Microsoft365Defender/Integrations/O365DefenderSafeLinks/O365DefenderSafeLinks.ps1
  Packs/Microsoft365Defender/Integrations/O365DefenderSafeLinks/O365DefenderSafeLinks.yml
  Packs/Microsoft365Defender/Integrations/O365DefenderSafeLinks/README.md
  Packs/Microsoft365Defender/ReleaseNotes/4_5_0.md
  Packs/Microsoft365Defender/pack_metadata.json
Labels: docs-approved

#24476 Add file name to crowdStirke Falcon X upload command
  Packs/CrowdStrikeFalconX/Integrations/CrowdStrikeFalconX/CrowdStrikeFalconX.py
  Packs/CrowdStrikeFalconX/Integrations/CrowdStrikeFalconX/CrowdStrikeFalconX.yml
  Packs/CrowdStrikeFalconX/Integrations/CrowdStrikeFalconX/CrowdStrikeFalconX_test.py
  Packs/CrowdStrikeFalconX/Integrations/CrowdStrikeFalconX/README.md
  Packs/CrowdStrikeFalconX/Integrations/CrowdStrikeFalconX/test_data/context.py
  Packs/CrowdStrikeFalconX/Integrations/CrowdStrikeFalconX/test_data/http_responses.py
  Packs/CrowdStrikeFalconX/ReleaseNotes/1_2_22.md
  Packs/CrowdStrikeFalconX/pack_metadata.json
Labels: docs-approved

#24510 Azure Sentinel description updated
  Packs/AzureSentinel/Integrations/AzureSentinel/AzureSentinel.yml
  Packs/AzureSentinel/Integrations/AzureSentinel/AzureSentinel_description.md
  Packs/AzureSentinel/ReleaseNotes/1_4_12.md
  Packs/AzureSentinel/pack_metadata.json
Labels: docs-approved

#23839 Collect xsiam items for tests even when xsoar supported
  Tests/scripts/collect_tests/collect_tests.py
  Tests/scripts/collect_tests/constants.py
  Tests/scripts/infrastructure_tests/test_collect_tests.py
Labels: docs-approved

#24478 appendContext bugfix
  Packs/Base/.pack-ignore
  Packs/Base/ReleaseNotes/1_31_63.md
  Packs/Base/Scripts/CommonServerPython/CommonServerPython.py
  Packs/Base/Scripts/CommonServerPython/CommonServerPython_test.py
  Packs/Base/pack_metadata.json
Labels: docs-approved

#23481 Xsiam layout rule
  Packs/AccessInvestigation/LayoutRules/Access.json
  Packs/AccessInvestigation/ReleaseNotes/1_2_3.md
  Packs/AccessInvestigation/pack_metadata.json
  Packs/CommonTypes/LayoutRules/Indicator_Feed.json
  Packs/CommonTypes/LayoutRules/Vulnerability.json
  Packs/CommonTypes/ReleaseNotes/3_3_49.md
  Packs/CommonTypes/pack_metadata.json
  Packs/CrisisManagement/LayoutRules/Employee_Health_Check.json
  Packs/CrisisManagement/ReleaseNotes/1_2_3.md
  Packs/CrisisManagement/pack_metadata.json
  Packs/IronDefense/LayoutRules/IronDefense_Alert_Notification.json
  Packs/IronDefense/LayoutRules/IronDefense_Event_Notification.json
  Packs/IronDefense/LayoutRules/IronDefense_IronDome_Notification.json
  Packs/IronDefense/ReleaseNotes/1_1_15.md
  Packs/IronDefense/pack_metadata.json
  Tests/Marketplace/marketplace_constants.py
  Tests/Marketplace/marketplace_services.py
  Tests/scripts/collect_tests/utils.py
Labels: docs-approved

#22589 SplunkPy - set the time period when fetch with offset
  Packs/SplunkPy/Integrations/SplunkPy/SplunkPy.py
  Packs/SplunkPy/ReleaseNotes/3_0_10.md
  Packs/SplunkPy/pack_metadata.json
Labels: docs-approved

#24573 Add missing scope to SlackV3 manifest
  Packs/Slack/doc_files/SlackV3_app_manifest.yml
Labels: docs-approved

#24339 Deprecate "Get Original Email - Generic" Playbook
  Packs/CommonPlaybooks/Playbooks/Get_Original_Email_-_Generic.yml
  Packs/CommonPlaybooks/Playbooks/Get_Original_Email_-_Generic_README.md
  Packs/CommonPlaybooks/ReleaseNotes/2_3_35.md
  Packs/CommonPlaybooks/doc_files/Get_Original_Email_-_Generic.png
  Packs/CommonPlaybooks/pack_metadata.json
  Packs/rasterize/TestPlaybooks/playbook-Process_Email_-_Generic_for_rasterize.yml
Labels: docs-approved

#24574 Microsoft-Sentinel-pack-desc
  Packs/AzureSentinel/pack_metadata.json
Labels: docs-approved

#24348 [Block File - Generic v2 Playbook] Remove Usage of Deprecated Traps Pack
  Packs/CommonPlaybooks/Playbooks/playbook-Block_File_-_Generic_v2.yml
  Packs/CommonPlaybooks/Playbooks/playbook-Block_File_-_Generic_v2_README.md
  Packs/CommonPlaybooks/ReleaseNotes/2_3_36.md
  Packs/CommonPlaybooks/doc_files/Block_File_-_Generic_v2.png
  Packs/CommonPlaybooks/pack_metadata.json
Labels: docs-approved

#24539 Fixed an issue to prevent from generating "No result returned" against an empty value.
  Packs/FiltersAndTransformers/ReleaseNotes/1_2_10.md
  Packs/FiltersAndTransformers/Scripts/AppendIfNotEmpty/AppendIfNotEmpty.js
  Packs/FiltersAndTransformers/Scripts/AppendIfNotEmpty/AppendIfNotEmpty.yml
  Packs/FiltersAndTransformers/TestPlaybooks/AppendIfNotEmpty_test.yml
  Packs/FiltersAndTransformers/pack_metadata.json
Labels: Contribution, docs-approved, Contribution Form Filled, Community, pending-contributor

#24578 [FlashPoint] - fix flaky unit-test
  Packs/Flashpoint/Integrations/Flashpoint/Flashpoint_test.py
Labels: docs-approved

#24298 Pan os add filter to rules commands
  Packs/PAN-OS/Integrations/Panorama/Panorama.py
  Packs/PAN-OS/Integrations/Panorama/Panorama.yml
  Packs/PAN-OS/Integrations/Panorama/Panorama_test.py
  Packs/PAN-OS/Integrations/Panorama/README.md
  Packs/PAN-OS/Integrations/Panorama/test_data/list-nat-rules-response.json
  Packs/PAN-OS/Integrations/Panorama/test_data/list-pbf-rules-response-un-committed.json
  Packs/PAN-OS/Integrations/Panorama/test_data/mock_rules.py
  Packs/PAN-OS/ReleaseNotes/1_16_8.md
  Packs/PAN-OS/pack_metadata.json
Labels: docs-approved

#24582 fix
  Packs/QutteraWebsiteMalwareScanner/pack_metadata.json
Labels: docs-approved

#24585 create graph
  .gitlab/ci/on-push.yml
Labels: docs-approved

#24515 [Aella_StarLight] to py3
  Packs/Aella_StarLight/Integrations/AellaStarLight/AellaStarLight.py
  Packs/Aella_StarLight/Integrations/AellaStarLight/AellaStarLight.yml
  Packs/Aella_StarLight/Integrations/AellaStarLight/AellaStarLight_image.png
  Packs/Aella_StarLight/Integrations/AellaStarLight/README.md
  Packs/Aella_StarLight/Integrations/integration-Aella_StarLight.yml
  Packs/Aella_StarLight/ReleaseNotes/1_0_7.md
  Packs/Aella_StarLight/pack_metadata.json
Labels: docs-approved

#24560 Fix git diff in test upload job
  .gitlab/ci/on-push.yml
  Utils/should_trigger_test_upload.sh
Labels: docs-approved

#24547 Reimplementation CS indicator feed
  Packs/FeedCrowdstrikeFalconIntel/Integrations/CrowdStrikeIndicatorFeed/CrowdStrikeIndicatorFeed.py
  Packs/FeedCrowdstrikeFalconIntel/Integrations/CrowdStrikeIndicatorFeed/CrowdStrikeIndicatorFeed.yml
  Packs/FeedCrowdstrikeFalconIntel/Integrations/CrowdStrikeIndicatorFeed/CrowdStrikeIndicatorFeed_test.py
  Packs/FeedCrowdstrikeFalconIntel/ReleaseNotes/2_1_0.md
  Packs/FeedCrowdstrikeFalconIntel/pack_metadata.json
Labels: docs-approved

#24301 update package
  .gitlab/ci/global.yml
  Tests/scripts/validate.sh
  package-lock.json
  package.json
  poetry.lock
  pyproject.toml
Labels: docs-approved

#24424 CoreRestAPI fixes and improvements
  Packs/DemistoRESTAPI/Integrations/CoreRESTAPI/CoreRESTAPI.js
  Packs/DemistoRESTAPI/Integrations/CoreRESTAPI/CoreRESTAPI.yml
  Packs/DemistoRESTAPI/Integrations/CoreRESTAPI/CoreRESTAPI_description.md
  Packs/DemistoRESTAPI/Integrations/CoreRESTAPI/README.md
  Packs/DemistoRESTAPI/Integrations/DemistoRESTAPI/DemistoRESTAPI.js
  Packs/DemistoRESTAPI/Integrations/DemistoRESTAPI/DemistoRESTAPI.yml
  Packs/DemistoRESTAPI/ReleaseNotes/1_3_17.md
  Packs/DemistoRESTAPI/pack_metadata.json
Labels: ForceMerge

#22241 hide trimevents arg
  Packs/CommonScripts/ReleaseNotes/1_11_23.md
  Packs/CommonScripts/Scripts/SearchIncidentsV2/SearchIncidentsV2.py
  Packs/CommonScripts/Scripts/SearchIncidentsV2/SearchIncidentsV2.yml
  Packs/CommonScripts/Scripts/SearchIncidentsV2/SearchIncidentsV2_test.py
  Packs/CommonScripts/pack_metadata.json
Labels: docs-approved

#24518 [Prisma Cloud Compute] - moved images the content repo
  Packs/PrismaCloudCompute/README.md
  Packs/PrismaCloudCompute/doc_files/prisma_alert_outputs.png
  Packs/PrismaCloudCompute/doc_files/prisma_alert_raw_input.png
  Packs/PrismaCloudCompute/doc_files/prisma_instance.png
Labels: docs-approved

#24486 Added the Unzip File playbook
  Packs/CommonPlaybooks/Playbooks/playbook-Unzip_File.yml
  Packs/CommonPlaybooks/Playbooks/playbook-Unzip_File_README.md
  Packs/CommonPlaybooks/ReleaseNotes/2_3_37.md
  Packs/CommonPlaybooks/doc_files/Unzip_File.png
  Packs/CommonPlaybooks/pack_metadata.json
Labels: docs-approved

#24420 Zendesk v2 permissions documentations
  Packs/Zendesk/Classifiers/classifier-Zendesk_-_Incoming_Mapper.json
  Packs/Zendesk/Integrations/Zendesk/Zendesk.yml
  Packs/Zendesk/Integrations/Zendeskv2/README.md
  Packs/Zendesk/Integrations/Zendeskv2/Zendeskv2.py
  Packs/Zendesk/Integrations/Zendeskv2/Zendeskv2.yml
  Packs/Zendesk/Integrations/Zendeskv2/Zendeskv2_description.md
  Packs/Zendesk/ReleaseNotes/2_0_3.md
  Packs/Zendesk/pack_metadata.json
Labels: docs-approved

#24225 save incompatible marketplaces false
  Tests/scripts/collect_tests/collect_tests.py
Labels: docs-approved

#24586 [OpsGenie] Invite User Command
  Packs/OpsGenie/Integrations/OpsGenieV3/OpsGenieV3.py
  Packs/OpsGenie/Integrations/OpsGenieV3/OpsGenieV3.yml
  Packs/OpsGenie/Integrations/OpsGenieV3/OpsGenieV3_description.md
  Packs/OpsGenie/Integrations/OpsGenieV3/OpsGenieV3_test.py
  Packs/OpsGenie/Integrations/OpsGenieV3/README.md
  Packs/OpsGenie/Integrations/OpsGenieV3/test_data/invite_user.json
  Packs/OpsGenie/ReleaseNotes/2_0_11.md
  Packs/OpsGenie/pack_metadata.json
Labels: Contribution, docs-approved, Contribution Form Filled, Community, pending-contributor

#24300 Move reputation tests configuration to conf.json
  Tests/conf.json
  Tests/scripts/collect_tests/collect_tests.py
  Tests/scripts/collect_tests/constants.py
  Tests/scripts/infrastructure_tests/test_collect_tests.py
  Tests/scripts/infrastructure_tests/tests_data/collect_tests/T/Packs/Base/TestPlaybooks/playbook-Domain_extraction_test.yml
  Tests/scripts/infrastructure_tests/tests_data/collect_tests/T/Packs/Base/TestPlaybooks/playbook-Email_extraction_test.yml
  Tests/scripts/infrastructure_tests/tests_data/collect_tests/T/Packs/Base/pack_metadata.json
  Tests/scripts/infrastructure_tests/tests_data/collect_tests/T/Packs/CommonTypes/IndicatorTypes/reputation-domain.json
  Tests/scripts/infrastructure_tests/tests_data/collect_tests/T/Packs/CommonTypes/pack_metadata.json
  Tests/scripts/infrastructure_tests/tests_data/collect_tests/T/Packs/DeveloperTools/TestPlaybooks/playbook-FormattingPerformance_-_Test.yml
  Tests/scripts/infrastructure_tests/tests_data/collect_tests/T/Packs/DeveloperTools/pack_metadata.json
  Tests/scripts/infrastructure_tests/tests_data/collect_tests/T/Tests/conf.json
  Tests/scripts/infrastructure_tests/tests_data/collect_tests/T/Tests/id_set.json
Labels: docs-approved

#24599 Downgrade aella fromversion
  Packs/Aella_StarLight/Integrations/AellaStarLight/AellaStarLight.yml
  Packs/Aella_StarLight/ReleaseNotes/1_0_8.md
  Packs/Aella_StarLight/pack_metadata.json
Labels: docs-approved

#24488 Added the Get File Sample - Generic playbook
  Packs/CommonPlaybooks/Playbooks/Get_File_Sample_-_Generic.yml
  Packs/CommonPlaybooks/Playbooks/Get_File_Sample_-_Generic_README.md
  Packs/CommonPlaybooks/ReleaseNotes/2_3_38.md
  Packs/CommonPlaybooks/doc_files/Get_File_Sample_-_Generic.png
  Packs/CommonPlaybooks/pack_metadata.json
Labels: docs-approved

#23665 [MS Teams] new commands and expand functionalities to the Chat functionality
  Packs/MicrosoftTeams/.pack-ignore
  Packs/MicrosoftTeams/.secrets-ignore
  Packs/MicrosoftTeams/Integrations/MicrosoftTeams/MicrosoftTeams.py
  Packs/MicrosoftTeams/Integrations/MicrosoftTeams/MicrosoftTeams.yml
  Packs/MicrosoftTeams/Integrations/MicrosoftTeams/MicrosoftTeams_commands.txt
  Packs/MicrosoftTeams/Integrations/MicrosoftTeams/MicrosoftTeams_description.md
  Packs/MicrosoftTeams/Integrations/MicrosoftTeams/MicrosoftTeams_test.py
  Packs/MicrosoftTeams/Integrations/MicrosoftTeams/README.md
  Packs/MicrosoftTeams/Integrations/MicrosoftTeams/test_data/chats_test_data.json
  Packs/MicrosoftTeams/ReleaseNotes/1_4_5.md
  Packs/MicrosoftTeams/pack_metadata.json
Labels: docs-approved

#24168 Check Point FW - Compatibility with XDR mapping
  Packs/CheckpointFirewall/ModelingRules/CheckpointFirewall_1_3/CheckpointFirewall_1_3.xif
  Packs/CheckpointFirewall/ReleaseNotes/2_3_8.md
  Packs/CheckpointFirewall/pack_metadata.json
Labels: docs-approved

#24600 not module
  package.json
  poetry.lock
  pyproject.toml
Labels: docs-approved, ForceMerge

#24609 Fixed should_trigger_test_upload script
  .gitlab/ci/on-push.yml
  Utils/should_trigger_test_upload.sh
  Utils/test_upload_flow/wait_for_upload.py
Labels: docs-approved

#24611 Skip triggering CI for test branches
  Utils/test_upload_flow/create_test_branch.py
Labels: docs-approved

#24612 ignored snow errors
  Packs/ServiceNow/.pack-ignore
Labels: docs-approved

#24607 Fix playbooks
  Packs/CommonPlaybooks/Playbooks/playbook-URL_Enrichment_-_Generic_v2.yml
  Packs/CommonPlaybooks/ReleaseNotes/2_3_39.md
  Packs/CommonPlaybooks/pack_metadata.json
Labels: docs-approved

#24504 Phishing v3 bug
  Tests/conf.json
Labels: docs-approved

#24628 Microsoft Teams: add generate login uri command
  Packs/MicrosoftTeams/Integrations/MicrosoftTeams/MicrosoftTeams.py
  Packs/MicrosoftTeams/Integrations/MicrosoftTeams/MicrosoftTeams.yml
  Packs/MicrosoftTeams/Integrations/MicrosoftTeams/MicrosoftTeams_commands.txt
  Packs/MicrosoftTeams/Integrations/MicrosoftTeams/MicrosoftTeams_test.py
  Packs/MicrosoftTeams/Integrations/MicrosoftTeams/README.md
  Packs/MicrosoftTeams/ReleaseNotes/1_4_6.md
  Packs/MicrosoftTeams/pack_metadata.json
Labels: docs-approved

#24532 Moving Mail sender to EWS v2
  Packs/MicrosoftExchangeOnPremise/Integrations/EWSMailSender/EWSMailSender.yml
  Packs/MicrosoftExchangeOnPremise/Integrations/EWSMailSender/EWSMailSender_description.md
  Packs/MicrosoftExchangeOnPremise/Integrations/EWSv2/EWSv2.py
  Packs/MicrosoftExchangeOnPremise/Integrations/EWSv2/EWSv2.yml
  Packs/MicrosoftExchangeOnPremise/Integrations/EWSv2/EWSv2_test.py
  Packs/MicrosoftExchangeOnPremise/Integrations/EWSv2/README.md
  Packs/MicrosoftExchangeOnPremise/ReleaseNotes/1_0_1.md
  Packs/MicrosoftExchangeOnPremise/TestPlaybooks/playbook-EWS-Searchmailbox-Test.yml
  Packs/MicrosoftExchangeOnPremise/TestPlaybooks/playbook-EWS-V2-Send-Mail-Test-2.yml
  Packs/MicrosoftExchangeOnPremise/TestPlaybooks/playbook-EWS-V2-Send-Mail-Test-3.yml
  Packs/MicrosoftExchangeOnPremise/TestPlaybooks/playbook-EWS-V2-send-mail-Test.yml
  Packs/MicrosoftExchangeOnPremise/TestPlaybooks/playbook-Send-Email-To-Recipients-Test.yml
  Packs/MicrosoftExchangeOnPremise/pack_metadata.json
  Packs/SMIME_Messaging/.pack-ignore
  Packs/SMIME_Messaging/Integrations/SMIME_Messaging/SMIME_Messaging.yml
  Packs/SMIME_Messaging/ReleaseNotes/1_0_10.md
  Packs/SMIME_Messaging/pack_metadata.json
  Tests/conf.json
Labels: docs-approved

#24624 graph depedencies test
  Tests/scripts/create_artifacts_graph/create_artifacts.py
Labels: docs-approved

#24561 [Azure Active Directory Users] Support A Custom Delimiter on `msgraph-user-update`
  Packs/MicrosoftGraphUser/Integrations/MicrosoftGraphUser/MicrosoftGraphUser.py
  Packs/MicrosoftGraphUser/Integrations/MicrosoftGraphUser/MicrosoftGraphUser.yml
  Packs/MicrosoftGraphUser/Integrations/MicrosoftGraphUser/MicrosoftGraphUser_test.py
  Packs/MicrosoftGraphUser/Integrations/MicrosoftGraphUser/README.md
  Packs/MicrosoftGraphUser/Integrations/MicrosoftGraphUser/examples.txt
  Packs/MicrosoftGraphUser/ReleaseNotes/1_5_16.md
  Packs/MicrosoftGraphUser/pack_metadata.json
  Tests/known_words.txt
Labels: docs-approved

#24577 Hide Deprecation Banner from EWS Extension
  Packs/MicrosoftExchangeOnline/Integrations/EwsExtension/EwsExtension.ps1
  Packs/MicrosoftExchangeOnline/ReleaseNotes/1_0_5.md
  Packs/MicrosoftExchangeOnline/pack_metadata.json
Labels: docs-approved

#24474 Added the lr-get-alarm-details and lr-alarm-drilldown command to LogRythmV2
  Packs/LogRhythmRest/Integrations/LogRhythmRestV2/LogRhythmRestV2.py
  Packs/LogRhythmRest/Integrations/LogRhythmRestV2/LogRhythmRestV2.yml
  Packs/LogRhythmRest/Integrations/LogRhythmRestV2/README.md
  Packs/LogRhythmRest/ReleaseNotes/2_0_16.md
  Packs/LogRhythmRest/pack_metadata.json
Labels: docs-approved

#24625 First sso access classification
  Packs/CortexXDR/Classifiers/classifier-PaloAltoNetworks_Cortex_XDR_Incident_Handler.json
  Packs/CortexXDR/ReleaseNotes/4_10_14.md
  Packs/CortexXDR/pack_metadata.json
Labels: docs-approved

#24380 [ASM] - EXPANDR - 1578
  Packs/CortexAttackSurfaceManagement/.pack-ignore
  Packs/CortexAttackSurfaceManagement/.secrets-ignore
  Packs/CortexAttackSurfaceManagement/IncidentFields/incidentfield-ASM_-_Asset_ID.json
  Packs/CortexAttackSurfaceManagement/IncidentFields/incidentfield-ASM_-_Attack_Surface_Rule_ID.json
  Packs/CortexAttackSurfaceManagement/IncidentFields/incidentfield-ASM_-_Remediation_Path_Rule.json
  Packs/CortexAttackSurfaceManagement/IncidentFields/incidentfield-ASM_-_Service_ID.json
  Packs/CortexAttackSurfaceManagement/Integrations/CortexAttackSurfaceManagement/CortexAttackSurfaceManagement.py
  Packs/CortexAttackSurfaceManagement/Integrations/CortexAttackSurfaceManagement/CortexAttackSurfaceManagement.yml
  Packs/CortexAttackSurfaceManagement/Integrations/CortexAttackSurfaceManagement/CortexAttackSurfaceManagement_test.py
  Packs/CortexAttackSurfaceManagement/Integrations/CortexAttackSurfaceManagement/README.md
  Packs/CortexAttackSurfaceManagement/Integrations/CortexAttackSurfaceManagement/command_examples
  Packs/CortexAttackSurfaceManagement/Integrations/CortexAttackSurfaceManagement/test_data/expected_results.py
  Packs/CortexAttackSurfaceManagement/Integrations/CortexAttackSurfaceManagement/test_data/raw_response.py
  Packs/CortexAttackSurfaceManagement/Playbooks/Cortex_ASM_-_ASM_Alert.yml
  Packs/CortexAttackSurfaceManagement/Playbooks/Cortex_ASM_-_ASM_Alert_README.md
  Packs/CortexAttackSurfaceManagement/Playbooks/Cortex_ASM_-_CMDB_Enrichment.yml
  Packs/CortexAttackSurfaceManagement/Playbooks/Cortex_ASM_-_Decision.yml
  Packs/CortexAttackSurfaceManagement/Playbooks/Cortex_ASM_-_Decision_README.md
  Packs/CortexAttackSurfaceManagement/Playbooks/Cortex_ASM_-_Detect_Service.yml
  Packs/CortexAttackSurfaceManagement/Playbooks/Cortex_ASM_-_Enrichment.yml
  Packs/CortexAttackSurfaceManagement/Playbooks/Cortex_ASM_-_GCP_Enrichment.yml
  Packs/CortexAttackSurfaceManagement/Playbooks/Cortex_ASM_-_Remediation.yml
  Packs/CortexAttackSurfaceManagement/Playbooks/Cortex_ASM_-_Remediation_Guidance.yml
  Packs/CortexAttackSurfaceManagement/Playbooks/Cortex_ASM_-_Remediation_Path_Rules.yml
  Packs/CortexAttackSurfaceManagement/Playbooks/Cortex_ASM_-_Remediation_Path_Rules_README.md
  Packs/CortexAttackSurfaceManagement/Playbooks/Cortex_ASM_-_Tenable.io_Enrichment.yml
  Packs/CortexAttackSurfaceManagement/README.md
  Packs/CortexAttackSurfaceManagement/ReleaseNotes/1_5_1.md
  Packs/CortexAttackSurfaceManagement/Scripts/GenerateASMReport/GenerateASMReport.py
  Packs/CortexAttackSurfaceManagement/Scripts/GenerateASMReport/GenerateASMReport.yml
  Packs/CortexAttackSurfaceManagement/Scripts/GenerateASMReport/GenerateASMReport_test.py
  Packs/CortexAttackSurfaceManagement/Scripts/GenerateASMReport/README.md
  Packs/CortexAttackSurfaceManagement/Scripts/RemediationPathRuleEvaluation/README.md
  Packs/CortexAttackSurfaceManagement/Scripts/RemediationPathRuleEvaluation/RemediationPathRuleEvaluation.py
  Packs/CortexAttackSurfaceManagement/Scripts/RemediationPathRuleEvaluation/RemediationPathRuleEvaluation.yml
  Packs/CortexAttackSurfaceManagement/Scripts/RemediationPathRuleEvaluation/RemediationPathRuleEvaluation_test.py
  Packs/CortexAttackSurfaceManagement/TestPlaybooks/playbook-CortexAttackSurfaceManagement_Test.yml
  Packs/CortexAttackSurfaceManagement/doc_files/Cortex_ASM_-_ASM_Alert.png
  Packs/CortexAttackSurfaceManagement/doc_files/Cortex_ASM_-_Decision.png
  Packs/CortexAttackSurfaceManagement/doc_files/Cortex_ASM_-_Remediation_Path_Rules.png
  Packs/CortexAttackSurfaceManagement/doc_files/RemediationPathRuleEvaluation.png
  Packs/CortexAttackSurfaceManagement/pack_metadata.json
Labels: Contribution, docs-approved, Contribution Form Filled, Community, ForceMerge

#24595 ShowScheduledEntries script
  Packs/CommonScripts/ReleaseNotes/1_11_25.md
  Packs/CommonScripts/Scripts/ShowScheduledEntries/ShowScheduledEntries.js
  Packs/CommonScripts/Scripts/ShowScheduledEntries/ShowScheduledEntries.yml
  Packs/CommonScripts/pack_metadata.json
Labels: docs-approved

#24638 1.10.2
  poetry.lock
  pyproject.toml
Labels: docs-approved

#24562 Okta Diffs
  Packs/Okta/ModelingRules/OktaModelingRules_1_3/OktaModelingRules_1_3.xif
  Packs/Okta/ReleaseNotes/3_1_10.md
  Packs/Okta/pack_metadata.json
Labels: docs-approved

#24665 FireEyeETP fix unittest
  Packs/FireEyeETP/Integrations/FireEyeETP/FireEyeETP_test.py
Labels: docs-approved

#24667 Xdm.event.outcome bulk5
  Packs/AzureEventsHub/ModelingRules/AzureEventsHub_1_3/AzureEventsHub_1_3.xif
  Packs/AzureEventsHub/ReleaseNotes/1_0_4.md
  Packs/AzureEventsHub/pack_metadata.json
  Packs/BrocadeSwitch/ModelingRules/BrocadeSwitch_1_3/BrocadeSwitch_1_3.xif
  Packs/BrocadeSwitch/ReleaseNotes/1_0_7.md
  Packs/BrocadeSwitch/pack_metadata.json
  Packs/CheckpointFirewall/ModelingRules/CheckpointFirewall_1_3/CheckpointFirewall_1_3.xif
  Packs/CheckpointFirewall/ReleaseNotes/2_3_9.md
  Packs/CheckpointFirewall/pack_metadata.json
Labels: docs-approved
