Repository demisto/content, pull requests merged in 2023-04, with the labels that each got.

#25510 MSFT ADFS - update extraction from event data
  Packs/MicrosoftADFS/ModelingRules/MicrosoftADFS_1_3/MicrosoftADFS_1_3.xif
  Packs/MicrosoftADFS/ReleaseNotes/1_0_12.md
  Packs/MicrosoftADFS/pack_metadata.json
Labels: docs-approved

#25599 YR-add-deleted-part-to-XDR-TestPlaybook
  Packs/CortexXDR/TestPlaybooks/Test_XDR_Playbook_general_commands.yml
Labels: docs-approved

#25401 Update Code42 integration to support V2 File Events
  Packs/Code42/Classifiers/classifier-mapper-incoming-Code42.json
  Packs/Code42/IncidentFields/incidentfield-Code42_File_Events.json
  Packs/Code42/IncidentFields/incidentfield-Code42_File_Events_Version.json
  Packs/Code42/Integrations/Code42/Code42.py
  Packs/Code42/Integrations/Code42/Code42.yml
  Packs/Code42/Integrations/Code42/Code42_test.py
  Packs/Code42/Integrations/Code42/README.md
  Packs/Code42/Integrations/Code42/test_data/v2_file_event_response.json
  Packs/Code42/Layouts/layoutscontainer-Code42_Security_Alert.json
  Packs/Code42/Playbooks/playbook-Code42_Exfiltration_Playbook.yml
  Packs/Code42/Playbooks/playbook-Code42_Exfiltration_Playbook_README.md
  Packs/Code42/Playbooks/playbook-Code42_File_Download_README.md
  Packs/Code42/Playbooks/playbook-Code42_File_Search_README.md
  Packs/Code42/README.md
  Packs/Code42/ReleaseNotes/3_1_5.md
  Packs/Code42/Scripts/Code42FileEventsToMarkdownTable/Code42FileEventsToMarkdownTable.py
  Packs/Code42/Scripts/Code42FileEventsToMarkdownTable/Code42FileEventsToMarkdownTable.yml
  Packs/Code42/Scripts/Code42FileEventsToMarkdownTable/README.md
  Packs/Code42/pack_metadata.json
Labels: Contribution, docs-approved, Partner, Contribution Form Filled

#25395 bug - adding indicator polling before calculating severity
  Packs/CommonPlaybooks/Playbooks/playbook-Calculate_Severity_By_Highest_DBotScore_6_0.yml
  Packs/CommonPlaybooks/Playbooks/playbook-Calculate_Severity_By_Highest_DBotScore_6_0_README.md
  Packs/CommonPlaybooks/Playbooks/playbook-Indicator_Registration_Polling_-_Generic.yml
  Packs/CommonPlaybooks/ReleaseNotes/2_3_54.md
  Packs/CommonPlaybooks/doc_files/Calculate_Severity_By_Highest_DBotScore.png
  Packs/CommonPlaybooks/pack_metadata.json
Labels: docs-approved

#25634 [QRadar v3] Ignore missing value when deleting reference set value
  Packs/QRadar/Integrations/QRadar_v3/QRadar_v3.py
  Packs/QRadar/Integrations/QRadar_v3/QRadar_v3.yml
  Packs/QRadar/ReleaseNotes/2_4_14.md
  Packs/QRadar/pack_metadata.json
Labels: docs-approved

#24780 Recorded future event collector
  Packs/RecordedFuture/Integrations/RecordedFutureEventCollector/Pipfile
  Packs/RecordedFuture/Integrations/RecordedFutureEventCollector/Pipfile.lock
  Packs/RecordedFuture/Integrations/RecordedFutureEventCollector/README.md
  Packs/RecordedFuture/Integrations/RecordedFutureEventCollector/RecordedFutureEventCollector.py
  Packs/RecordedFuture/Integrations/RecordedFutureEventCollector/RecordedFutureEventCollector.yml
  Packs/RecordedFuture/Integrations/RecordedFutureEventCollector/RecordedFutureEventCollector_description.md
  Packs/RecordedFuture/Integrations/RecordedFutureEventCollector/RecordedFutureEventCollector_image.png
  Packs/RecordedFuture/Integrations/RecordedFutureEventCollector/RecordedFutureEventCollector_test.py
  Packs/RecordedFuture/Integrations/RecordedFutureEventCollector/command_examples
  Packs/RecordedFuture/Integrations/RecordedFutureEventCollector/test_data/first_fetch.json
  Packs/RecordedFuture/Integrations/RecordedFutureEventCollector/test_data/second_fetch.json
  Packs/RecordedFuture/ModelingRules/RecordedFutureModelingRules_1_4/RecordedFutureModelingRules_1_4.xif
  Packs/RecordedFuture/ModelingRules/RecordedFutureModelingRules_1_4/RecordedFutureModelingRules_1_4.yml
  Packs/RecordedFuture/ModelingRules/RecordedFutureModelingRules_1_4/RecordedFutureModelingRules_1_4_schema.json
  Packs/RecordedFuture/ModelingRules/RecordedFutureModelingRules_1_4/RecordedFutureModelingRules_1_4_testdata.json
  Packs/RecordedFuture/ReleaseNotes/1_5_0.md
  Packs/RecordedFuture/pack_metadata.json
Labels: docs-approved

#25632 HatchingTriage v1.0.9 - Add user tags to sample submit
  Packs/HatchingTriage/Integrations/HatchingTriage/HatchingTriage.py
  Packs/HatchingTriage/Integrations/HatchingTriage/HatchingTriage.yml
  Packs/HatchingTriage/ReleaseNotes/1_0_9.md
  Packs/HatchingTriage/pack_metadata.json
Labels: Contribution, docs-approved, Partner, Contribution Form Filled

#25673 Fixed RecordedFuture layouts
  Packs/RecordedFuture/Layouts/layoutscontainer-Recorded_Future_Domain_Abuse_Layout.json
  Packs/RecordedFuture/Layouts/layoutscontainer-Recorded_Future_Playbook_Alert.json
  Packs/RecordedFuture/Layouts/layoutscontainer-Recorded_Future_Vulnerability_Layout.json
  Packs/RecordedFuture/ReleaseNotes/1_5_1.md
  Packs/RecordedFuture/pack_metadata.json
Labels: docs-approved

#25473 CSFalcon 401 error code bug
  Packs/CrowdStrikeFalcon/Integrations/CrowdStrikeFalcon/CrowdStrikeFalcon.py
  Packs/CrowdStrikeFalcon/ReleaseNotes/1_10_10.md
  Packs/CrowdStrikeFalcon/pack_metadata.json
Labels: docs-approved

#25429 Fix feed mandiant
  Packs/FeedMandiant/Integrations/FeedMandiant/FeedMandiant.py
  Packs/FeedMandiant/Integrations/FeedMandiant/FeedMandiant.yml
  Packs/FeedMandiant/Integrations/FeedMandiant/FeedMandiant_test.py
  Packs/FeedMandiant/Integrations/FeedMandiant/test_data/result_indicators.json
  Packs/FeedMandiant/ReleaseNotes/1_0_10.md
  Packs/FeedMandiant/pack_metadata.json
Labels: docs-approved

#25629 Add error message for locked reports
  Packs/VMRay/Integrations/VMRay/VMRay.py
  Packs/VMRay/Integrations/VMRay/VMRay.yml
  Packs/VMRay/Integrations/VMRay/VMRay_test.py
  Packs/VMRay/ReleaseNotes/1_1_8.md
  Packs/VMRay/pack_metadata.json
Labels: Contribution, docs-approved, Partner, Contribution Form Filled

#25675 search_and_install_packs logs
  Tests/Marketplace/search_and_install_packs.py
Labels: docs-approved

#21151 Remove Nightly Integrations
  Tests/conf.json
  Tests/private_build/run_content_tests_private.py
  Tests/scripts/infrastructure_tests/tests_data/collect_tests/A_xsiam/Tests/conf.json
  Tests/scripts/infrastructure_tests/tests_data/collect_tests/A_xsoar/Tests/conf.json
  Tests/scripts/infrastructure_tests/tests_data/collect_tests/B_xsiam/Tests/conf.json
  Tests/scripts/infrastructure_tests/tests_data/collect_tests/B_xsoar/Tests/conf.json
  Tests/scripts/infrastructure_tests/tests_data/collect_tests/C/Tests/conf.json
  Tests/scripts/infrastructure_tests/tests_data/collect_tests/D/Tests/conf.json
  Tests/scripts/infrastructure_tests/tests_data/collect_tests/E/Tests/conf.json
  Tests/scripts/infrastructure_tests/tests_data/collect_tests/F/Tests/conf.json
  Tests/scripts/infrastructure_tests/tests_data/collect_tests/G/Tests/conf.json
  Tests/scripts/infrastructure_tests/tests_data/collect_tests/H/Tests/conf.json
  Tests/scripts/infrastructure_tests/tests_data/collect_tests/I_xsoar/Tests/conf.json
  Tests/scripts/infrastructure_tests/tests_data/collect_tests/J/Tests/conf.json
  Tests/scripts/infrastructure_tests/tests_data/collect_tests/K/Tests/conf.json
  Tests/scripts/infrastructure_tests/tests_data/collect_tests/L_XSIAM/Tests/conf.json
  Tests/scripts/infrastructure_tests/tests_data/collect_tests/M1/Tests/conf.json
  Tests/scripts/infrastructure_tests/tests_data/collect_tests/M2/Tests/conf.json
  Tests/scripts/infrastructure_tests/tests_data/collect_tests/M3/Tests/conf.json
  Tests/scripts/infrastructure_tests/tests_data/collect_tests/MR1/Tests/conf.json
  Tests/scripts/infrastructure_tests/tests_data/collect_tests/P/Tests/conf.json
  Tests/scripts/infrastructure_tests/tests_data/collect_tests/Q/Tests/conf.json
  Tests/scripts/infrastructure_tests/tests_data/collect_tests/R/Tests/conf.json
  Tests/scripts/infrastructure_tests/tests_data/collect_tests/S/Tests/conf.json
  Tests/scripts/infrastructure_tests/tests_data/collect_tests/T/Tests/conf.json
  Tests/scripts/infrastructure_tests/tests_data/collect_tests/empty/Tests/conf.json
  Tests/scripts/infrastructure_tests/tests_data/collect_tests/empty_xsiam/Tests/conf.json
  Tests/scripts/infrastructure_tests/tests_data/collect_tests/limited_nightly_packs/Tests/conf.json
  Tests/scripts/infrastructure_tests/tests_data/collect_tests/non_api_test/Tests/conf.json
  Tests/scripts/infrastructure_tests/tests_data/collect_tests/release_notes_config/Tests/conf.json
  Tests/scripts/infrastructure_tests/tests_data/collect_tests/script_non_api_test/Tests/conf.json
  Tests/scripts/infrastructure_tests/tests_data/collect_tests/skipped_nightly_test/Tests/conf.json
  Tests/scripts/infrastructure_tests/tests_data/mock_conf.json
  Tests/test_content.py
Labels: docs-approved

#25686 The last file to ignore validation BA124 from
  Packs/Code42/.pack-ignore
Labels: docs-approved

#25671 ClearswiftDLP Modeling Test
  Packs/ClearswiftDLP/ModelingRules/ClearswiftDLP/ClearswiftDLP.xif
  Packs/ClearswiftDLP/ReleaseNotes/1_0_1.md
  Packs/ClearswiftDLP/pack_metadata.json
Labels: docs-approved

#25611 New regex for URL with scheme and no path option and removing HTML tags
  Packs/CommonTypes/IndicatorTypes/reputation-url.json
  Packs/CommonTypes/ReleaseNotes/3_3_61.md
  Packs/CommonTypes/pack_metadata.json
Labels: docs-approved

#25636 Allow installation to be retried three times if it fails - build issue
  .hooks/bootstrap
Labels: docs-approved

#25554 Fix taxii2 rs issue
  Packs/ApiModules/Scripts/TAXII2ApiModule/TAXII2ApiModule.py
  Packs/FeedTAXII/Integrations/FeedTAXII2/FeedTAXII2.py
  Packs/FeedTAXII/Integrations/FeedTAXII2/FeedTAXII2.yml
  Packs/FeedTAXII/Integrations/FeedTAXII2/FeedTAXII2_test.py
  Packs/FeedTAXII/ReleaseNotes/1_1_24.md
  Packs/FeedTAXII/pack_metadata.json
Labels: docs-approved

#25640 Add urlscan res page to content output
  Packs/UrlScan/Integrations/UrlScan/UrlScan.py
  Packs/UrlScan/Integrations/UrlScan/UrlScan.yml
  Packs/UrlScan/ReleaseNotes/1_2_7.md
  Packs/UrlScan/pack_metadata.json
Labels: Contribution, docs-approved, Contribution Form Filled, Community

#25628 CSP mypy errors fix
  Packs/Base/ReleaseNotes/1_31_83.md
  Packs/Base/Scripts/CommonServerPython/CommonServerPython.py
  Packs/Base/pack_metadata.json
Labels: docs-approved

#25698 update circle-ci remote docker version
  .circleci/config.yml
Labels: docs-approved

#25681 AWS private link support
  Packs/AWS-CloudWatchLogs/Integrations/AWS-CloudWatchLogs/AWS-CloudWatchLogs.py
  Packs/AWS-CloudWatchLogs/Integrations/AWS-CloudWatchLogs/AWS-CloudWatchLogs.yml
  Packs/AWS-CloudWatchLogs/ReleaseNotes/1_2_17.md
  Packs/AWS-CloudWatchLogs/pack_metadata.json
  Packs/AWS-EC2/Integrations/AWS-EC2/AWS-EC2.py
  Packs/AWS-EC2/Integrations/AWS-EC2/AWS-EC2.yml
  Packs/AWS-EC2/ReleaseNotes/1_2_33.md
  Packs/AWS-EC2/pack_metadata.json
  Packs/AWS-GuardDuty/Integrations/AWSGuardDuty/AWSGuardDuty.py
  Packs/AWS-GuardDuty/Integrations/AWSGuardDuty/AWSGuardDuty.yml
  Packs/AWS-GuardDuty/Integrations/AWSGuardDutyEventCollector/AWSGuardDutyEventCollector.py
  Packs/AWS-GuardDuty/Integrations/AWSGuardDutyEventCollector/AWSGuardDutyEventCollector.yml
  Packs/AWS-GuardDuty/ReleaseNotes/1_3_17.md
  Packs/AWS-GuardDuty/pack_metadata.json
  Packs/AWS-Lambda/Integrations/AWS-Lambda/AWS-Lambda.py
  Packs/AWS-Lambda/Integrations/AWS-Lambda/AWS-Lambda.yml
  Packs/AWS-Lambda/ReleaseNotes/1_2_35.md
  Packs/AWS-Lambda/pack_metadata.json
  Packs/AWS-S3/Integrations/AWS-S3/AWS-S3.py
  Packs/AWS-S3/Integrations/AWS-S3/AWS-S3.yml
  Packs/AWS-S3/ReleaseNotes/1_2_16.md
  Packs/AWS-S3/pack_metadata.json
  Packs/AWS-SecurityHub/Integrations/AWS_SecurityHub/AWS_SecurityHub.py
  Packs/AWS-SecurityHub/Integrations/AWS_SecurityHub/AWS_SecurityHub.yml
  Packs/AWS-SecurityHub/ReleaseNotes/1_2_2.md
  Packs/AWS-SecurityHub/pack_metadata.json
  Packs/ApiModules/Scripts/AWSApiModule/AWSApiModule.py
  Packs/ApiModules/Scripts/AWSApiModule/AWSApiModule.yml
Labels: docs-approved, release-notes-only

#25683 Moved the Reporter Email Address field from Phishing to CommonTypes pack
  Packs/CommonTypes/IncidentFields/incidentfield-reporteremailaddress.json
  Packs/CommonTypes/ReleaseNotes/3_3_62.md
  Packs/CommonTypes/pack_metadata.json
  Packs/Phishing/.pack-ignore
  Packs/Phishing/ReleaseNotes/3_5_11.json
  Packs/Phishing/ReleaseNotes/3_5_11.md
  Packs/Phishing/pack_metadata.json
Labels: docs-approved, ForceMerge

#25706 Changed action name
  .github/workflows/auto-merge-dockers.yml
Labels: docs-approved

#25700 Add chinese encodings to parse-emails v2
  Packs/CommonScripts/ReleaseNotes/1_11_59.md
  Packs/CommonScripts/Scripts/ParseEmailFilesV2/ParseEmailFilesV2.py
  Packs/CommonScripts/Scripts/ParseEmailFilesV2/ParseEmailFilesV2.yml
  Packs/CommonScripts/pack_metadata.json
Labels: docs-approved

#25705 v1.12.0
  poetry.lock
  pyproject.toml
Labels: docs-approved

#25723 Deprecate AutoFocues tags feed
  Packs/AutoFocus/Integrations/AutoFocusTagsFeed/AutoFocusTagsFeed.yml
  Packs/AutoFocus/ReleaseNotes/2_1_5.md
  Packs/AutoFocus/pack_metadata.json
Labels: docs-approved

#25665 [AWS] - fix issue with SessionDuration parameter
  Packs/AWS-ACM/ReleaseNotes/1_1_33.md
  Packs/AWS-ACM/pack_metadata.json
  Packs/AWS-AccessAnalyzer/ReleaseNotes/1_1_3.md
  Packs/AWS-AccessAnalyzer/pack_metadata.json
  Packs/AWS-CloudWatchLogs/ReleaseNotes/1_2_18.md
  Packs/AWS-CloudWatchLogs/pack_metadata.json
  Packs/AWS-EC2/ReleaseNotes/1_2_34.md
  Packs/AWS-EC2/pack_metadata.json
  Packs/AWS-GuardDuty/ReleaseNotes/1_3_18.md
  Packs/AWS-GuardDuty/pack_metadata.json
  Packs/AWS-IAM/ReleaseNotes/1_1_27.md
  Packs/AWS-IAM/pack_metadata.json
  Packs/AWS-Lambda/ReleaseNotes/1_2_36.md
  Packs/AWS-Lambda/pack_metadata.json
  Packs/AWS-S3/ReleaseNotes/1_2_17.md
  Packs/AWS-S3/pack_metadata.json
  Packs/AWS-SNS/ReleaseNotes/1_0_6.md
  Packs/AWS-SNS/pack_metadata.json
  Packs/AWS-SQS/ReleaseNotes/1_2_23.md
  Packs/AWS-SQS/pack_metadata.json
  Packs/AWS-SecurityHub/ReleaseNotes/1_2_3.md
  Packs/AWS-SecurityHub/pack_metadata.json
  Packs/ApiModules/Scripts/AWSApiModule/AWSApiModule.py
  Packs/ApiModules/Scripts/AWSApiModule/AWSApiModule_test.py
  Packs/Aws-SecretsManager/ReleaseNotes/1_0_13.md
  Packs/Aws-SecretsManager/pack_metadata.json
Labels: docs-approved

#25624 Block indicators tag indicators fix
  Packs/CommonPlaybooks/.pack-ignore
  Packs/CommonPlaybooks/Playbooks/playbook-Block_Account_-_Generic_v2.yml
  Packs/CommonPlaybooks/Playbooks/playbook-Block_IP_-_Generic_v3.yml
  Packs/CommonPlaybooks/Playbooks/playbook-Block_Indicators_-_Generic_v3.yml
  Packs/CommonPlaybooks/ReleaseNotes/2_3_57.md
  Packs/CommonPlaybooks/pack_metadata.json
  Packs/EDL/Playbooks/playbook-Block_Domain_-_External_Dynamic_List.yml
  Packs/EDL/ReleaseNotes/3_1_21.md
  Packs/EDL/pack_metadata.json
Labels: docs-approved

#25268 infoblox event collector
  Packs/InfobloxBloxOne/Integrations/InfobloxBloxOneThreatDefenseEventCollector/InfobloxBloxOneThreatDefenseEventCollector.py
  Packs/InfobloxBloxOne/Integrations/InfobloxBloxOneThreatDefenseEventCollector/InfobloxBloxOneThreatDefenseEventCollector.yml
  Packs/InfobloxBloxOne/Integrations/InfobloxBloxOneThreatDefenseEventCollector/InfobloxBloxOneThreatDefenseEventCollector_description.md
  Packs/InfobloxBloxOne/Integrations/InfobloxBloxOneThreatDefenseEventCollector/InfobloxBloxOneThreatDefenseEventCollector_image.png
  Packs/InfobloxBloxOne/Integrations/InfobloxBloxOneThreatDefenseEventCollector/InfobloxBloxOneThreatDefenseEventCollector_test.py
  Packs/InfobloxBloxOne/Integrations/InfobloxBloxOneThreatDefenseEventCollector/README.md
  Packs/InfobloxBloxOne/Integrations/InfobloxBloxOneThreatDefenseEventCollector/command_examples
  Packs/InfobloxBloxOne/ModelingRules/InfobloxBloxOneThreatDefense/InfobloxBloxOneThreatDefense.xif
  Packs/InfobloxBloxOne/ModelingRules/InfobloxBloxOneThreatDefense/InfobloxBloxOneThreatDefense.yml
  Packs/InfobloxBloxOne/ModelingRules/InfobloxBloxOneThreatDefense/InfobloxBloxOneThreatDefense_schema.json
  Packs/InfobloxBloxOne/ReleaseNotes/1_1_0.md
  Packs/InfobloxBloxOne/pack_metadata.json
Labels: docs-approved

#25728 Ignore RM108 for AWS README file
  Packs/AWS-Enrichment-Remediation/.pack-ignore
Labels: docs-approved

#25731 Sixgill Darkfeed - update pack-ignore
  Packs/Sixgill-Darkfeed/.pack-ignore
Labels: docs-approved

#25729 replace broken readme links - modify date time
  Packs/FiltersAndTransformers/Scripts/ModifyDateTime/README.md
Labels: docs-approved

#25724 CBR v2 endpoint fix
  Packs/Carbon_Black_Enterprise_Response/Integrations/CarbonBlackResponseV2/CarbonBlackResponseV2.py
  Packs/Carbon_Black_Enterprise_Response/Integrations/CarbonBlackResponseV2/CarbonBlackResponseV2.yml
  Packs/Carbon_Black_Enterprise_Response/Integrations/CarbonBlackResponseV2/CarbonBlackResponseV2_test.py
  Packs/Carbon_Black_Enterprise_Response/ReleaseNotes/2_1_31.md
  Packs/Carbon_Black_Enterprise_Response/pack_metadata.json
Labels: docs-approved

#25559 Modifed Druva_FindDevice_Command in druva.py,Druva Ransomware Respons…
  Packs/Druva/Integrations/Druva/Druva.py
  Packs/Druva/Integrations/Druva/Druva.yml
  Packs/Druva/Integrations/Druva/Druva_test.py
  Packs/Druva/Playbooks/Druva-Ransomware-Response-User-resource-URL.yml
  Packs/Druva/Playbooks/Druva-Ransomware-Response-User-resource-URL_README.md
  Packs/Druva/Playbooks/Druva-Ransomware-Response.yml
  Packs/Druva/Playbooks/Druva-Ransomware-Response_README.md
  Packs/Druva/ReleaseNotes/1_1_3.md
  Packs/Druva/doc_files/Druva-Ransomware-Response_Playbook.png
  Packs/Druva/pack_metadata.json
Labels: Contribution

#25709 Fix CommonServerPython mypy errors
  Packs/Base/ReleaseNotes/1_31_84.md
  Packs/Base/Scripts/CommonServerPython/CommonServerPython.py
  Packs/Base/pack_metadata.json
Labels: docs-approved

#25618 F5 LTM Modeling Rules
  Packs/F5LTM/ModelingRules/F5LTMModelingRules_1_3/F5LTMModelingRules_1_3.xif
  Packs/F5LTM/ModelingRules/F5LTMModelingRules_1_3/F5LTMModelingRules_1_3.yml
  Packs/F5LTM/ModelingRules/F5LTMModelingRules_1_3/F5LTMModelingRules_1_3_schema.json
  Packs/F5LTM/ParsingRules/F5LTMParsingRules/F5LTMParsingRules.xif
  Packs/F5LTM/ParsingRules/F5LTMParsingRules/F5LTMParsingRules.yml
  Packs/F5LTM/README.md
  Packs/F5LTM/ReleaseNotes/1_0_4.md
  Packs/F5LTM/doc_imgs/F5LTM.png
  Packs/F5LTM/pack_metadata.json
Labels: docs-approved

#25734 Fixed broken images in AWS S3
  Packs/AWS-Enrichment-Remediation/.pack-ignore
  Packs/AWS-Enrichment-Remediation/README.md
Labels: docs-approved

#25725 AWS-CloudTrail new attributes
  Packs/AWS-CloudTrail/Integrations/AWS-CloudTrail/AWS-CloudTrail.yml
  Packs/AWS-CloudTrail/ReleaseNotes/1_0_9.md
  Packs/AWS-CloudTrail/pack_metadata.json
Labels: docs-approved

#25737 Netskope collector fix
  Packs/Netskope/Integrations/NetskopeEventCollector/NetskopeEventCollector.py
  Packs/Netskope/Integrations/NetskopeEventCollector/NetskopeEventCollector.yml
  Packs/Netskope/Integrations/NetskopeEventCollector/NetskopeEventCollector_test.py
  Packs/Netskope/ReleaseNotes/3_0_13.md
  Packs/Netskope/pack_metadata.json
Labels: docs-approved

#25711 3CX playbook v3
  Packs/3CXDesktopApp_Supply_Chain_Attack/Playbooks/playbook-3CXDesktopApp_Supply_Chain_Attack.yml
  Packs/3CXDesktopApp_Supply_Chain_Attack/Playbooks/playbook-3CXDesktopApp_Supply_Chain_Attack_README.md
  Packs/3CXDesktopApp_Supply_Chain_Attack/ReleaseNotes/1_0_1.md
  Packs/3CXDesktopApp_Supply_Chain_Attack/doc_files/3CXDesktopApp_Supply_Chain_Attack.png
  Packs/3CXDesktopApp_Supply_Chain_Attack/pack_metadata.json
  Packs/MajorBreachesInvestigationandResponse/.pack-ignore
  Packs/MajorBreachesInvestigationandResponse/README.md
  Packs/MajorBreachesInvestigationandResponse/ReleaseNotes/1_6_30.md
  Packs/MajorBreachesInvestigationandResponse/pack_metadata.json
Labels: docs-approved

#25752 fix issue with note .split()
  Packs/ServiceNow/Integrations/ServiceNowv2/ServiceNowv2.py
  Packs/ServiceNow/Integrations/ServiceNowv2/ServiceNowv2.yml
  Packs/ServiceNow/ReleaseNotes/2_5_17.md
  Packs/ServiceNow/pack_metadata.json
Labels: Contribution

#25027 Add support for Mal-Eval
  Packs/Stairwell/Integrations/Inception/Inception.py
  Packs/Stairwell/Integrations/Inception/Inception.yml
  Packs/Stairwell/Integrations/Inception/Inception_test.py
  Packs/Stairwell/Integrations/Inception/test_data/file_enrichment_command_result.json
  Packs/Stairwell/ReleaseNotes/1_0_4.md
  Packs/Stairwell/pack_metadata.json
Labels: Contribution, Partner, Contribution Form Filled, pending-contributor

#25580 added withsecure pack
  Packs/WithSecure/.pack-ignore
  Packs/WithSecure/.secrets-ignore
  Packs/WithSecure/Integrations/WithSecureEventCollector/Pipfile
  Packs/WithSecure/Integrations/WithSecureEventCollector/Pipfile.lock
  Packs/WithSecure/Integrations/WithSecureEventCollector/README.md
  Packs/WithSecure/Integrations/WithSecureEventCollector/WithSecureEventCollector.py
  Packs/WithSecure/Integrations/WithSecureEventCollector/WithSecureEventCollector.yml
  Packs/WithSecure/Integrations/WithSecureEventCollector/WithSecureEventCollector_description.md
  Packs/WithSecure/Integrations/WithSecureEventCollector/WithSecureEventCollector_image.png
  Packs/WithSecure/Integrations/WithSecureEventCollector/WithSecureEventCollector_test.py
  Packs/WithSecure/Integrations/WithSecureEventCollector/command_examples.txt
  Packs/WithSecure/Integrations/WithSecureEventCollector/test_data/fetch_events.json
  Packs/WithSecure/Integrations/WithSecureEventCollector/test_data/get_events.json
  Packs/WithSecure/ModelingRules/WithSecure/WithSecure.xif
  Packs/WithSecure/ModelingRules/WithSecure/WithSecure.yml
  Packs/WithSecure/ModelingRules/WithSecure/WithSecure_schema.json
  Packs/WithSecure/README.md
  Packs/WithSecure/pack_metadata.json
Labels: docs-approved

#25463 add server url configuration to BoxCollector and BoxV2
  Packs/Box/.secrets-ignore
  Packs/Box/Integrations/BoxEventsCollector/BoxEventsCollector.py
  Packs/Box/Integrations/BoxEventsCollector/BoxEventsCollector.yml
  Packs/Box/Integrations/BoxEventsCollector/BoxEventsCollector_test.py
  Packs/Box/Integrations/BoxV2/BoxV2.py
  Packs/Box/Integrations/BoxV2/BoxV2.yml
  Packs/Box/Integrations/BoxV2/BoxV2_test.py
  Packs/Box/ReleaseNotes/3_1_20.md
  Packs/Box/pack_metadata.json
Labels: docs-approved, release-notes-only, ForceMerge

#25336 AWS Security Hub Event Collector
  Packs/AWS-SecurityHub/Integrations/AWSSecurityHubEventCollector/AWSSecurityHubEventCollector.py
  Packs/AWS-SecurityHub/Integrations/AWSSecurityHubEventCollector/AWSSecurityHubEventCollector.yml
  Packs/AWS-SecurityHub/Integrations/AWSSecurityHubEventCollector/AWSSecurityHubEventCollector_description.md
  Packs/AWS-SecurityHub/Integrations/AWSSecurityHubEventCollector/AWSSecurityHubEventCollector_image.png
  Packs/AWS-SecurityHub/Integrations/AWSSecurityHubEventCollector/AWSSecurityHubEventCollector_test.py
  Packs/AWS-SecurityHub/Integrations/AWSSecurityHubEventCollector/README.md
  Packs/AWS-SecurityHub/Integrations/AWSSecurityHubEventCollector/test_data/api_mock/get_findings_10.json
  Packs/AWS-SecurityHub/Integrations/AWSSecurityHubEventCollector/test_data/expected_results/fetch_events_expected_results_0.json
  Packs/AWS-SecurityHub/Integrations/AWSSecurityHubEventCollector/test_data/expected_results/fetch_events_expected_results_1.json
  Packs/AWS-SecurityHub/ModelingRules/AWSSecurityHubModelingRules/AWSSecurityHubModelingRules.xif
  Packs/AWS-SecurityHub/ModelingRules/AWSSecurityHubModelingRules/AWSSecurityHubModelingRules.yml
  Packs/AWS-SecurityHub/ModelingRules/AWSSecurityHubModelingRules/AWSSecurityHubModelingRules_schema.json
  Packs/AWS-SecurityHub/ModelingRules/AWSSecurityHubModelingRules/AWSSecurityHubModelingRules_testdata.json
  Packs/AWS-SecurityHub/ReleaseNotes/1_3_0.md
  Packs/AWS-SecurityHub/pack_metadata.json
Labels: docs-approved

#25514 Anomali threat stream v3 enhancement
  Packs/Anomali_ThreatStream/.secrets-ignore
  Packs/Anomali_ThreatStream/Integrations/AnomaliThreatStreamv3/AnomaliThreatStreamv3.py
  Packs/Anomali_ThreatStream/Integrations/AnomaliThreatStreamv3/AnomaliThreatStreamv3.yml
  Packs/Anomali_ThreatStream/Integrations/AnomaliThreatStreamv3/AnomaliThreatStreamv3_test.py
  Packs/Anomali_ThreatStream/Integrations/AnomaliThreatStreamv3/README.md
  Packs/Anomali_ThreatStream/Integrations/AnomaliThreatStreamv3/test_data/mocked_data.json
  Packs/Anomali_ThreatStream/ReleaseNotes/2_1_0.md
  Packs/Anomali_ThreatStream/TestPlaybooks/playbook-ThreatStream-Test.yml
  Packs/Anomali_ThreatStream/pack_metadata.json
Labels: docs-approved

#25155 Add native:candidate testing workflow
  .circleci/config.yml
  .gitlab/ci/.gitlab-ci.yml
  .gitlab/ci/global.yml
  .gitlab/ci/on-push.yml
  .gitlab/ci/test-native-candidate.yml
  Tests/docker_native_image_config.json
  Tests/scripts/check_jobs_done.py
  Tests/scripts/get_latest_docker_image.py
  Tests/scripts/gitlab_slack_notifier.py
Labels: docs-approved, ForceMerge

#25754 updating CDL integration to add ThreatName to two threat log queries
  Packs/CortexDataLake/CONTRIBUTORS.json
  Packs/CortexDataLake/Integrations/CortexDataLake/CortexDataLake.py
  Packs/CortexDataLake/Integrations/CortexDataLake/CortexDataLake.yml
  Packs/CortexDataLake/ReleaseNotes/1_4_4.md
  Packs/CortexDataLake/pack_metadata.json
Labels: Contribution, docs-approved

#25555 [Zoom] Create Zoom Event Collector
  Packs/Zoom/Integrations/ZoomEventCollector/README.md
  Packs/Zoom/Integrations/ZoomEventCollector/ZoomEventCollector.py
  Packs/Zoom/Integrations/ZoomEventCollector/ZoomEventCollector.yml
  Packs/Zoom/Integrations/ZoomEventCollector/ZoomEventCollector_description.md
  Packs/Zoom/Integrations/ZoomEventCollector/ZoomEventCollector_image.png
  Packs/Zoom/Integrations/ZoomEventCollector/ZoomEventCollector_test.py
  Packs/Zoom/Integrations/ZoomEventCollector/test_data/fetch_events_activities.json
  Packs/Zoom/Integrations/ZoomEventCollector/test_data/fetch_events_operationlogs.json
  Packs/Zoom/Integrations/ZoomEventCollector/test_data/get_events_activities.json
  Packs/Zoom/Integrations/ZoomEventCollector/test_data/get_events_operationlogs.json
  Packs/Zoom/Integrations/ZoomEventCollector/test_data/zoom_fetch_events.json
  Packs/Zoom/Integrations/ZoomEventCollector/test_data/zoom_fetch_events_with_token.json
  Packs/Zoom/Integrations/ZoomEventCollector/test_data/zoom_get_events.json
  Packs/Zoom/ModelingRules/Zoom/Zoom.xif
  Packs/Zoom/ModelingRules/Zoom/Zoom.yml
  Packs/Zoom/ModelingRules/Zoom/Zoom_schema.json
  Packs/Zoom/ModelingRules/Zoom/Zoom_testdata.json
  Packs/Zoom/ReleaseNotes/1_3_0.md
  Packs/Zoom/pack_metadata.json
Labels: docs-approved

#25784 Added sleep step to wait till gitlab start running
  .github/workflows/auto-merge-dockers.yml
Labels: docs-approved

#25765 Servicenow add ticket type
  Packs/ServiceNow/Integrations/ServiceNowv2/ServiceNowv2.yml
  Packs/ServiceNow/ReleaseNotes/2_5_18.md
  Packs/ServiceNow/pack_metadata.json
Labels: docs-approved

#25743 [PAN-OS] fix panorama_list_edls command
  Packs/PAN-OS/Integrations/Panorama/Panorama.py
  Packs/PAN-OS/Integrations/Panorama/Panorama.yml
  Packs/PAN-OS/Integrations/Panorama/Panorama_test.py
  Packs/PAN-OS/Integrations/Panorama/test_data/prettify_edls_arr_expected_result.json
  Packs/PAN-OS/Integrations/Panorama/test_data/prettify_edls_arr_sample.json
  Packs/PAN-OS/ReleaseNotes/1_16_17.md
  Packs/PAN-OS/pack_metadata.json
Labels: docs-approved

#25666 Added mapper functionality to SlackV3
  Packs/Slack/Integrations/SlackV3/SlackV3.py
  Packs/Slack/Integrations/SlackV3/SlackV3.yml
  Packs/Slack/Integrations/SlackV3/SlackV3_test.py
  Packs/Slack/ReleaseNotes/3_1_30.md
  Packs/Slack/pack_metadata.json
Labels: docs-approved

#25785 Crowdstrike - fix fetch detections
  Packs/CrowdStrikeFalcon/Integrations/CrowdStrikeFalcon/CrowdStrikeFalcon.py
  Packs/CrowdStrikeFalcon/Integrations/CrowdStrikeFalcon/CrowdStrikeFalcon.yml
  Packs/CrowdStrikeFalcon/Integrations/CrowdStrikeFalcon/CrowdStrikeFalcon_test.py
  Packs/CrowdStrikeFalcon/ReleaseNotes/1_10_11.md
  Packs/CrowdStrikeFalcon/pack_metadata.json
Labels: docs-approved

#25392 TAXII Server 2 - Updated the way the server serves file hashes and other SCOs
  Packs/Base/.pack-ignore
  Packs/Base/ReleaseNotes/1_31_85.md
  Packs/Base/Scripts/CommonServerPython/CommonServerPython.py
  Packs/Base/pack_metadata.json
  Packs/TAXIIServer/Integrations/TAXII2Server/TAXII2Server.py
  Packs/TAXIIServer/Integrations/TAXII2Server/TAXII2Server.yml
  Packs/TAXIIServer/Integrations/TAXII2Server/TAXII2Server_test.py
  Packs/TAXIIServer/Integrations/TAXII2Server/test_data/entity_b_iocs.json
  Packs/TAXIIServer/Integrations/TAXII2Server/test_data/file_iocs.json
  Packs/TAXIIServer/Integrations/TAXII2Server/test_data/file_iocs_filter_test.json
  Packs/TAXIIServer/Integrations/TAXII2Server/test_data/objects21_file.json
  Packs/TAXIIServer/Integrations/TAXII2Server/test_data/objects21_ip_with_relationships.json
  Packs/TAXIIServer/Integrations/TAXII2Server/test_data/objects21_no_extention_file.json
  Packs/TAXIIServer/Integrations/TAXII2Server/test_data/objects21_spec_fields_file.json
  Packs/TAXIIServer/Integrations/TAXII2Server/test_data/sco_indicator_file.json
  Packs/TAXIIServer/Integrations/TAXII2Server/test_data/searchRelationships-response.json
  Packs/TAXIIServer/Integrations/TAXII2Server/test_data/sort_ip_iocs.json
  Packs/TAXIIServer/Integrations/TAXII2Server/test_data/stix_sco_indicators.json
  Packs/TAXIIServer/Integrations/TAXII2Server/test_data/xsoar_sco_indicators.json
  Packs/TAXIIServer/ReleaseNotes/2_0_31.md
  Packs/TAXIIServer/pack_metadata.json
Labels: docs-approved

#25766 Cisco ASA parsing rules - iso8601
  Packs/CiscoASA/ParsingRules/CiscoASA/CiscoASA.xif
  Packs/CiscoASA/README.md
  Packs/CiscoASA/ReleaseNotes/1_0_34.md
  Packs/CiscoASA/doc_imgs/CiscoASATimestamp.png
  Packs/CiscoASA/pack_metadata.json
Labels: docs-approved

#25795 Crowdstrike endpoint command bug fix
  Packs/CrowdStrikeFalcon/Integrations/CrowdStrikeFalcon/CrowdStrikeFalcon.py
  Packs/CrowdStrikeFalcon/Integrations/CrowdStrikeFalcon/CrowdStrikeFalcon_test.py
  Packs/CrowdStrikeFalcon/ReleaseNotes/1_10_12.md
  Packs/CrowdStrikeFalcon/pack_metadata.json
Labels: docs-approved

#25793 [WildFire] Improve error message when failing to upload an unsupported file
  Packs/Palo_Alto_Networks_WildFire/Integrations/Palo_Alto_Networks_WildFire_v2/Palo_Alto_Networks_WildFire_v2.py
  Packs/Palo_Alto_Networks_WildFire/Integrations/Palo_Alto_Networks_WildFire_v2/Palo_Alto_Networks_WildFire_v2.yml
  Packs/Palo_Alto_Networks_WildFire/ReleaseNotes/2_1_20.md
  Packs/Palo_Alto_Networks_WildFire/pack_metadata.json
Labels: docs-approved

#24747 Devo integration v2 Improvement
  Packs/Devo/Integrations/Devo_v2/Devo_v2.py
  Packs/Devo/Integrations/Devo_v2/Devo_v2.yml
  Packs/Devo/Integrations/Devo_v2/Devo_v2_test.py
  Packs/Devo/Integrations/Devo_v2/README.md
  Packs/Devo/ReleaseNotes/1_2_0.md
  Packs/Devo/pack_metadata.json
Labels: Contribution, Partner, Contribution Form Filled, pending-contributor

#25789 Improve the doc of SNOW integration
  Packs/ServiceNow/Integrations/ServiceNowv2/README.md
Labels: docs-approved

#25767 Updated F5 LTM README and Modeling Rules
  Packs/F5LTM/ModelingRules/F5LTMModelingRules_1_3/F5LTMModelingRules_1_3.xif
  Packs/F5LTM/README.md
  Packs/F5LTM/ReleaseNotes/1_0_5.md
  Packs/F5LTM/pack_metadata.json
Labels: docs-approved

#25669 Improve KQL query in DeleteReportedEmail
  Packs/Phishing/ReleaseNotes/3_5_12.md
  Packs/Phishing/Scripts/DeleteReportedEmail/DeleteReportedEmail.py
  Packs/Phishing/Scripts/DeleteReportedEmail/DeleteReportedEmail.yml
  Packs/Phishing/pack_metadata.json
Labels: docs-approved

#25674 Enhancement/avoid period as output prefix in context data
  Packs/Base/ReleaseNotes/1_31_86.md
  Packs/Base/Scripts/CommonServerPython/CommonServerPython.py
  Packs/Base/Scripts/CommonServerPython/CommonServerPython_test.py
  Packs/Base/pack_metadata.json
Labels: docs-approved, release-notes-only

#25478 Recorded future identity 1.1
  Packs/IdentityRecordedFuture/.secrets-ignore
  Packs/IdentityRecordedFuture/IncidentTypes/incidenttype-customIncidentTypes-identity.json
  Packs/IdentityRecordedFuture/Integrations/IdentityRecordedFuture/IdentityRecordedFuture.py
  Packs/IdentityRecordedFuture/Integrations/IdentityRecordedFuture/IdentityRecordedFuture.yml
  Packs/IdentityRecordedFuture/Integrations/IdentityRecordedFuture/IdentityRecordedFuture_description.md
  Packs/IdentityRecordedFuture/Integrations/IdentityRecordedFuture/IdentityRecordedFuture_test.py
  Packs/IdentityRecordedFuture/Integrations/IdentityRecordedFuture/README.md
  Packs/IdentityRecordedFuture/Integrations/IdentityRecordedFuture/example_commands.txt
  Packs/IdentityRecordedFuture/Layouts/layoutscontainer-Recorded_Future_Identity_Incident.json
  Packs/IdentityRecordedFuture/Playbooks/playbook-Recorded_Future_Identity_Create_Incident_sub.yml
  Packs/IdentityRecordedFuture/Playbooks/playbook-Recorded_Future_Identity_Create_Incident_sub_README.md
  Packs/IdentityRecordedFuture/Playbooks/playbook-Recorded_Future_Identity_External_Usecase.yml
  Packs/IdentityRecordedFuture/Playbooks/playbook-Recorded_Future_Identity_External_Usecase_README.md
  Packs/IdentityRecordedFuture/Playbooks/playbook-Recorded_Future_Identity_Identity_Found_incident.yml
  Packs/IdentityRecordedFuture/Playbooks/playbook-Recorded_Future_Identity_Identity_Found_incident_README.md
  Packs/IdentityRecordedFuture/Playbooks/playbook-Recorded_Future_Identity_Lookup_Identities_parent.yml
  Packs/IdentityRecordedFuture/Playbooks/playbook-Recorded_Future_Identity_Lookup_Identities_parent_README.md
  Packs/IdentityRecordedFuture/Playbooks/playbook-Recorded_Future_Identity_Workforce_Usecase.yml
  Packs/IdentityRecordedFuture/Playbooks/playbook-Recorded_Future_Identity_Workforce_Usecase_README.md
  Packs/IdentityRecordedFuture/README.md
  Packs/IdentityRecordedFuture/ReleaseNotes/1_1_0.md
  Packs/IdentityRecordedFuture/TestPlaybooks/TestIdentityRecordedFuture.yml
  Packs/IdentityRecordedFuture/doc_files/Recorded_Future_Identity_-_Create_Incident_sub.png
  Packs/IdentityRecordedFuture/doc_files/Recorded_Future_Identity_-_Identity_Found_incident.png
  Packs/IdentityRecordedFuture/doc_files/Recorded_Future_Identity_-_Lookup_Identities_parent.png
  Packs/IdentityRecordedFuture/pack_metadata.json
Labels: Contribution, docs-approved, Partner, Contribution Form Filled

#25828 Dou collector missing events
  Packs/DuoAdminApi/Integrations/DuoEventCollector/DuoEventCollector.py
  Packs/DuoAdminApi/Integrations/DuoEventCollector/DuoEventCollector.yml
  Packs/DuoAdminApi/ReleaseNotes/3_2_10.md
  Packs/DuoAdminApi/pack_metadata.json
Labels: docs-approved

#25843 Adding video to PrismaCloud Pack
  Packs/PrismaCloud/Playbooks/playbook-Prisma_Cloud_-_VM_Alert_Prioritization_README.md
  Packs/PrismaCloud/pack_metadata.json
Labels: docs-approved

#25826 Email subject unmapped
  Packs/CoreAlertFields/IncidentFields/incidentfield-Email_Subject.json
  Packs/CoreAlertFields/ReleaseNotes/1_0_24.md
  Packs/CoreAlertFields/pack_metadata.json
Labels: docs-approved

#25421 Xsup 17927/microsoft DATP
  Packs/MicrosoftDefenderAdvancedThreatProtection/Integrations/MicrosoftDefenderAdvancedThreatProtection/MicrosoftDefenderAdvancedThreatProtection.py
  Packs/MicrosoftDefenderAdvancedThreatProtection/Integrations/MicrosoftDefenderAdvancedThreatProtection/MicrosoftDefenderAdvancedThreatProtection.yml
  Packs/MicrosoftDefenderAdvancedThreatProtection/Integrations/MicrosoftDefenderAdvancedThreatProtection/MicrosoftDefenderAdvancedThreatProtection_test.py
  Packs/MicrosoftDefenderAdvancedThreatProtection/ReleaseNotes/1_15_19.md
  Packs/MicrosoftDefenderAdvancedThreatProtection/pack_metadata.json
Labels: docs-approved

#25562 Add Additional Prisma Cloud Compute Commands
  Packs/PrismaCloudCompute/Integrations/PaloAltoNetworks_PrismaCloudCompute/PaloAltoNetworks_PrismaCloudCompute.py
  Packs/PrismaCloudCompute/Integrations/PaloAltoNetworks_PrismaCloudCompute/PaloAltoNetworks_PrismaCloudCompute.yml
  Packs/PrismaCloudCompute/Integrations/PaloAltoNetworks_PrismaCloudCompute/PaloAltoNetworks_PrismaCloudCompute_test.py
  Packs/PrismaCloudCompute/Integrations/PaloAltoNetworks_PrismaCloudCompute/README.md
  Packs/PrismaCloudCompute/Integrations/PaloAltoNetworks_PrismaCloudCompute/test_data/backups.json
  Packs/PrismaCloudCompute/Integrations/PaloAltoNetworks_PrismaCloudCompute/test_data/defender_logs.json
  Packs/PrismaCloudCompute/Integrations/PaloAltoNetworks_PrismaCloudCompute/test_data/defender_settings.json
  Packs/PrismaCloudCompute/Integrations/PaloAltoNetworks_PrismaCloudCompute/test_data/get_alert_profiles.json
  Packs/PrismaCloudCompute/ReleaseNotes/1_4_0.md
  Packs/PrismaCloudCompute/pack_metadata.json
Labels: Contribution, docs-approved, post-demo, Contribution Form Filled, Community

#25832 Kmsat readme update to merge integrations
  Packs/KnowBe4_KMSAT/Integrations/KnowBe4KMSAT/KnowBe4KMSAT.yml
  Packs/KnowBe4_KMSAT/Integrations/KnowBe4KMSATEventCollector/KnowBe4KMSATEventCollector.yml
  Packs/KnowBe4_KMSAT/README.md
  Packs/KnowBe4_KMSAT/ReleaseNotes/1_0_9.md
  Packs/KnowBe4_KMSAT/pack_metadata.json
Labels: Contribution, docs-approved, Partner, Contribution Form Filled

#25432 Ms teams bot id fix
  Packs/MicrosoftTeams/Integrations/MicrosoftTeams/MicrosoftTeams.py
  Packs/MicrosoftTeams/Integrations/MicrosoftTeams/MicrosoftTeams.yml
  Packs/MicrosoftTeams/Integrations/MicrosoftTeams/MicrosoftTeams_test.py
  Packs/MicrosoftTeams/Integrations/MicrosoftTeams/README.md
  Packs/MicrosoftTeams/ReleaseNotes/1_4_15.md
  Packs/MicrosoftTeams/pack_metadata.json
Labels: docs-approved

#25846 fix job done upload
  Tests/scripts/check_jobs_done.py
Labels: docs-approved

#25848 Fixing coverage report file
  .gitlab/ci/global.yml
Labels: docs-approved, ForceMerge

#25850 '# pragma no cover' for solving the coverage problem
  Packs/Base/ReleaseNotes/1_31_87.md
  Packs/Base/Scripts/SanePdfReport/SanePdfReport.py
  Packs/Base/Scripts/SanePdfReport/SanePdfReport.yml
  Packs/Base/pack_metadata.json
  Packs/CommonScripts/ReleaseNotes/1_11_60.md
  Packs/CommonScripts/Scripts/ConvertFile/ConvertFile.py
  Packs/CommonScripts/Scripts/ConvertFile/ConvertFile.yml
  Packs/CommonScripts/pack_metadata.json
Labels: docs-approved

#25748 [CommonServerPython] execute_command returning DemistoException
  Packs/Base/ReleaseNotes/1_31_87.md
  Packs/Base/Scripts/CommonServerPython/CommonServerPython.py
  Packs/Base/Scripts/CommonServerPython/CommonServerPython_test.py
  Packs/Base/pack_metadata.json
Labels: Contribution, docs-approved, ready-for-instance-test, Contribution Form Filled, Community, pending-contributor

#25815 Updated the QRadar links
  Packs/QRadar/Integrations/QRadar_v3/QRadar_v3_description.md
  Packs/QRadar/ReleaseNotes/2_4_16.md
  Packs/QRadar/pack_metadata.json
Labels: docs-approved

#25635 update native ga
  Tests/docker_native_image_config.json
Labels: docs-approved

#25493 Bug archer add cache
  Packs/ArcherRSA/Integrations/ArcherV2/ArcherV2.py
  Packs/ArcherRSA/Integrations/ArcherV2/ArcherV2.yml
  Packs/ArcherRSA/Integrations/ArcherV2/ArcherV2_test.py
  Packs/ArcherRSA/Integrations/ArcherV2/README.md
  Packs/ArcherRSA/ReleaseNotes/1_2_9.md
  Packs/ArcherRSA/pack_metadata.json
Labels: docs-approved, ForceMerge

#25792 [Cortex XDR] support for multiple endpoint statuses
  Packs/ApiModules/ReleaseNotes/2_2_16.md
  Packs/ApiModules/Scripts/CoreIRApiModule/CoreIRApiModule.py
  Packs/ApiModules/pack_metadata.json
  Packs/CortexXDR/Integrations/CortexXDRIR/CortexXDRIR.py
  Packs/CortexXDR/Integrations/CortexXDRIR/CortexXDRIR.yml
  Packs/CortexXDR/ReleaseNotes/4_10_31.md
  Packs/CortexXDR/pack_metadata.json
Labels: Contribution, docs-approved, ready-for-instance-test, Contribution Form Filled, Community

#25858 Fix content variable in edit ticket post req.
  Packs/RTIR/Integrations/RTIR/RTIR.py
  Packs/RTIR/Integrations/RTIR/RTIR.yml
  Packs/RTIR/ReleaseNotes/1_0_14.md
  Packs/RTIR/pack_metadata.json
Labels: docs-approved

#25854 Email regex revert to allow slash at start of email
  Packs/CommonTypes/IndicatorTypes/reputation-email.json
  Packs/CommonTypes/ReleaseNotes/3_3_63.md
  Packs/CommonTypes/pack_metadata.json
Labels: docs-approved

#25909 SanePDFReport: Change port number in test and Increase timeout
  Packs/Base/Scripts/SanePdfReport/SanePdfReport_test.py
Labels: docs-approved

#25277 [Oracle Cloud Infrastructure] Create Audit Event Collector
  Packs/OracleCloudInfrastructure/.pack-ignore
  Packs/OracleCloudInfrastructure/.secrets-ignore
  Packs/OracleCloudInfrastructure/Integrations/OracleCloudInfrastructureEventCollector/OracleCloudInfrastructureEventCollector.py
  Packs/OracleCloudInfrastructure/Integrations/OracleCloudInfrastructureEventCollector/OracleCloudInfrastructureEventCollector.yml
  Packs/OracleCloudInfrastructure/Integrations/OracleCloudInfrastructureEventCollector/OracleCloudInfrastructureEventCollector_description.md
  Packs/OracleCloudInfrastructure/Integrations/OracleCloudInfrastructureEventCollector/OracleCloudInfrastructureEventCollector_image.png
  Packs/OracleCloudInfrastructure/Integrations/OracleCloudInfrastructureEventCollector/OracleCloudInfrastructureEventCollector_test.py
  Packs/OracleCloudInfrastructure/Integrations/OracleCloudInfrastructureEventCollector/README.md
  Packs/OracleCloudInfrastructure/ModelingRules/OracleCloudInfrastructureModelingRules/OracleCloudInfrastructureModelingRules.xif
  Packs/OracleCloudInfrastructure/ModelingRules/OracleCloudInfrastructureModelingRules/OracleCloudInfrastructureModelingRules.yml
  Packs/OracleCloudInfrastructure/ModelingRules/OracleCloudInfrastructureModelingRules/OracleCloudInfrastructureModelingRules_schema.json
  Packs/OracleCloudInfrastructure/README.md
  Packs/OracleCloudInfrastructure/pack_metadata.json
Labels: docs-approved

#25797 Adding debug logs for lookback feature
  Packs/Base/ReleaseNotes/1_31_88.md
  Packs/Base/Scripts/CommonServerPython/CommonServerPython.py
  Packs/Base/pack_metadata.json
Labels: docs-approved

#25581 Opswat filescan
  Packs/OPSWAT-Filescan/.pack-ignore
  Packs/OPSWAT-Filescan/.secrets-ignore
  Packs/OPSWAT-Filescan/Author_image.png
  Packs/OPSWAT-Filescan/Integrations/OPSWATFilescan/OPSWATFilescan.py
  Packs/OPSWAT-Filescan/Integrations/OPSWATFilescan/OPSWATFilescan.yml
  Packs/OPSWAT-Filescan/Integrations/OPSWATFilescan/OPSWATFilescan_description.md
  Packs/OPSWAT-Filescan/Integrations/OPSWATFilescan/OPSWATFilescan_image.png
  Packs/OPSWAT-Filescan/Integrations/OPSWATFilescan/OPSWATFilescan_test.py
  Packs/OPSWAT-Filescan/Integrations/OPSWATFilescan/README.md
  Packs/OPSWAT-Filescan/Integrations/OPSWATFilescan/command_examples
  Packs/OPSWAT-Filescan/Integrations/OPSWATFilescan/test_data/query_hash_badfile.json
  Packs/OPSWAT-Filescan/Integrations/OPSWATFilescan/test_data/query_hash_cleanfile.json
  Packs/OPSWAT-Filescan/Integrations/OPSWATFilescan/test_data/query_url_google.json
  Packs/OPSWAT-Filescan/Integrations/OPSWATFilescan/test_data/scan_command_url_response.json
  Packs/OPSWAT-Filescan/Integrations/OPSWATFilescan/test_data/scan_command_zip_invalid_pass.json
  Packs/OPSWAT-Filescan/Integrations/OPSWATFilescan/test_data/scan_command_zip_response.json
  Packs/OPSWAT-Filescan/Integrations/OPSWATFilescan/test_data/scan_command_zip_valid_pass.json
  Packs/OPSWAT-Filescan/README.md
  Packs/OPSWAT-Filescan/pack_metadata.json
Labels: Contribution, docs-approved, Partner, post-demo, Contribution Form Filled

#25919 fixing broken python code
  Packs/Luminate/Integrations/Luminate/Luminate.py
  Packs/Luminate/ReleaseNotes/1_0_5.md
  Packs/Luminate/pack_metadata.json
Labels: docs-approved

#25830 Little improvments XSIAM build
  Tests/Marketplace/search_and_install_packs.py
  Tests/Marketplace/search_and_uninstall_pack.py
Labels: docs-approved

#25790 [DeleteReportedEmail] - add support for O365 Security and Compliance V2
  Packs/Phishing/ReleaseNotes/3_5_13.md
  Packs/Phishing/Scripts/DeleteReportedEmail/DeleteReportedEmail.py
  Packs/Phishing/Scripts/DeleteReportedEmail/DeleteReportedEmail.yml
  Packs/Phishing/Scripts/DeleteReportedEmail/DeleteReportedEmail_test.py
  Packs/Phishing/Scripts/GetBrandDeleteReportedEmail/GetBrandDeleteReportedEmail.py
  Packs/Phishing/Scripts/GetBrandDeleteReportedEmail/GetBrandDeleteReportedEmail.yml
  Packs/Phishing/pack_metadata.json
Labels: docs-approved

#25732 Install packs: convert recursion to loop, add sleep for retry
  Tests/Marketplace/search_and_install_packs.py
Labels: docs-approved

#25908 Release 1.13.0
  poetry.lock
  pyproject.toml
Labels: docs-approved

#25183 Orca Event Collector
  Packs/Orca/Integrations/OrcaEventCollector/OrcaEventCollector.py
  Packs/Orca/Integrations/OrcaEventCollector/OrcaEventCollector.yml
  Packs/Orca/Integrations/OrcaEventCollector/OrcaEventCollector_description.md
  Packs/Orca/Integrations/OrcaEventCollector/OrcaEventCollector_image.png
  Packs/Orca/Integrations/OrcaEventCollector/OrcaEventCollector_test.py
  Packs/Orca/Integrations/OrcaEventCollector/README.md
  Packs/Orca/Integrations/OrcaEventCollector/test_data/get_alerts_test.json
  Packs/Orca/ModelingRules/OrcaModelingRules_1_3/OrcaModelingRules_1_3.xif
  Packs/Orca/ModelingRules/OrcaModelingRules_1_3/OrcaModelingRules_1_3.yml
  Packs/Orca/ModelingRules/OrcaModelingRules_1_3/OrcaModelingRules_1_3_schema.json
  Packs/Orca/ReleaseNotes/2_1_0.md
  Packs/Orca/pack_metadata.json
Labels: docs-approved

#25833 Fix/pan os rule filter
  Packs/PAN-OS/Integrations/Panorama/Panorama.py
  Packs/PAN-OS/Integrations/Panorama/Panorama_test.py
  Packs/PAN-OS/ReleaseNotes/1_16_18.md
  Packs/PAN-OS/pack_metadata.json
Labels: bug, docs-approved, release-notes-only

#25860 Account enrichment PB - Domain prefix fix
  Packs/CommonPlaybooks/Playbooks/playbook-Account_Enrichment_-_Generic_v2.2.yml
  Packs/CommonPlaybooks/ReleaseNotes/2_3_58.md
  Packs/CommonPlaybooks/TestPlaybooks/playbook-Account_Enrichment_-_Generic_v2.1_-_Test.yml
  Packs/CommonPlaybooks/doc_files/Account_Enrichment_-_Generic_v2.2.png
  Packs/CommonPlaybooks/pack_metadata.json
  Tests/conf.json
Labels: docs-approved

#25925 [Qualys V2] Add outputs to Launch And Fetch Scan Based Findings Report - Qualys
  Packs/qualys/Playbooks/playbook-Launch_And_Fetch_Scan_Based_Findings_Report_-_Qualys.yml
  Packs/qualys/Playbooks/playbook-Launch_And_Fetch_Scan_Based_Findings_Report_-_Qualys_README.md
  Packs/qualys/ReleaseNotes/1_2_4.md
  Packs/qualys/pack_metadata.json
Labels: docs-approved

#25841 [Microsoft 365 Defender] Credentials support and redirected/merged incidents
  Packs/Microsoft365Defender/Integrations/Microsoft365Defender/Microsoft365Defender.py
  Packs/Microsoft365Defender/Integrations/Microsoft365Defender/Microsoft365Defender.yml
  Packs/Microsoft365Defender/ReleaseNotes/4_5_5.md
  Packs/Microsoft365Defender/pack_metadata.json
Labels: Contribution, docs-approved, Contribution Form Filled, Community

#25821 removed condition that prevents timeout and persistent args to work t…
  Packs/PAN-OS/Integrations/Panorama/Panorama.py
  Packs/PAN-OS/Integrations/Panorama/Panorama_test.py
  Packs/PAN-OS/ReleaseNotes/1_16_19.md
  Packs/PAN-OS/pack_metadata.json
Labels: docs-approved

#25859 Updated URL formatter to filter URLs with invalid TLDs
  Packs/CommonScripts/ReleaseNotes/1_11_61.md
  Packs/CommonScripts/Scripts/FormatURL/FormatURL.py
  Packs/CommonScripts/Scripts/FormatURL/FormatURL.yml
  Packs/CommonScripts/Scripts/FormatURL/FormatURL_test.py
  Packs/CommonScripts/pack_metadata.json
Labels: docs-approved

#25812 [ASM] rc list 04122023
  Packs/CortexAttackSurfaceManagement/.secrets-ignore
  Packs/CortexAttackSurfaceManagement/Lists/list-RemediationGuidance.json
  Packs/CortexAttackSurfaceManagement/ReleaseNotes/1_6_4.md
  Packs/CortexAttackSurfaceManagement/pack_metadata.json
Labels: Contribution, docs-approved, ready-for-instance-test, Contribution Form Filled, Community

#25949 Added false positive secrets of XIF files to ignored
  Packs/AWS-SecurityHub/.secrets-ignore
  Packs/AbnormalSecurity/.secrets-ignore
  Packs/AzureEventsHub/.secrets-ignore
  Packs/CiscoFirepower/.secrets-ignore
  Packs/CorelightZeek/.secrets-ignore
  Packs/CyberArkIdentity/.secrets-ignore
  Packs/F5LTM/.secrets-ignore
  Packs/ForcepointEmailSecurity/.secrets-ignore
  Packs/FortiGate/.secrets-ignore
  Packs/JuniperSRX/.secrets-ignore
  Packs/Kubernetes/.secrets-ignore
  Packs/MicrosoftADFS/.secrets-ignore
  Packs/MicrosoftCloudAppSecurity/.secrets-ignore
  Packs/MicrosoftDefenderAdvancedThreatProtection/.secrets-ignore
  Packs/MicrosoftGraphSecurity/.secrets-ignore
  Packs/MicrosoftIISWebServer/.secrets-ignore
  Packs/MicrosoftIntune/.secrets-ignore
  Packs/MicrosoftWindowsEvents/.secrets-ignore
  Packs/MySQLEnterprise/.secrets-ignore
  Packs/Netskope/.secrets-ignore
  Packs/Okta/.secrets-ignore
  Packs/Orca/.secrets-ignore
  Packs/PrismaCloud/.secrets-ignore
  Packs/SafeNet_Trusted_Access/.secrets-ignore
  Packs/SentinelOne/.secrets-ignore
  Packs/SymantecBlueCoatProxySG/.secrets-ignore
  Packs/Tableau/.secrets-ignore
  Packs/WithSecure/.secrets-ignore
  Packs/Zscaler/.secrets-ignore
  Packs/ZscalerZPA/.secrets-ignore
  Packs/cisco-ise/.secrets-ignore
  Packs/jamf/.secrets-ignore
Labels: docs-approved

#25911 Anomali threatstream build ioc json
  Packs/Anomali_ThreatStream/.secrets-ignore
  Packs/Anomali_ThreatStream/Integrations/AnomaliThreatStreamv3/AnomaliThreatStreamv3.py
  Packs/Anomali_ThreatStream/Integrations/AnomaliThreatStreamv3/AnomaliThreatStreamv3.yml
  Packs/Anomali_ThreatStream/Integrations/AnomaliThreatStreamv3/README.md
  Packs/Anomali_ThreatStream/ReleaseNotes/2_1_1.md
  Packs/Anomali_ThreatStream/Scripts/ThreatstreamBuildIocImportJson/README.md
  Packs/Anomali_ThreatStream/Scripts/ThreatstreamBuildIocImportJson/ThreatstreamBuildIocImportJson.py
  Packs/Anomali_ThreatStream/Scripts/ThreatstreamBuildIocImportJson/ThreatstreamBuildIocImportJson.yml
  Packs/Anomali_ThreatStream/Scripts/ThreatstreamBuildIocImportJson/ThreatstreamBuildIocImportJson_test.py
  Packs/Anomali_ThreatStream/pack_metadata.json
Labels: docs-approved

#25922 Remove Druva Dev PB
  Packs/Druva/Playbooks/Druva-Ransomware-Response-User-resource-URL.yml
  Packs/Druva/Playbooks/Druva-Ransomware-Response-User-resource-URL_README.md
  Packs/Druva/ReleaseNotes/1_1_5.json
  Packs/Druva/ReleaseNotes/1_1_5.md
  Packs/Druva/pack_metadata.json
Labels: docs-approved, ForceMerge

#25913 SlackV3: fix missing user messages
  Packs/Slack/Integrations/SlackV3/SlackV3.py
  Packs/Slack/Integrations/SlackV3/SlackV3.yml
  Packs/Slack/Integrations/SlackV3/SlackV3_test.py
  Packs/Slack/ReleaseNotes/3_1_31.md
  Packs/Slack/pack_metadata.json
Labels: docs-approved

#25940 Filter new packs on server min version
  Tests/configure_and_test_integration_instances.py
Labels: docs-approved

#25950 Cortex XDR - True Positive Incident Handling - fix playbook inputs
  Packs/CortexXDR/Playbooks/playbook-Cortex_XDR_-_True_Positive_Incident_Handling.yml
  Packs/CortexXDR/Playbooks/playbook-Cortex_XDR_-_True_Positive_Incident_Handling_README.md
  Packs/CortexXDR/ReleaseNotes/4_10_32.md
  Packs/CortexXDR/pack_metadata.json
Labels: docs-approved

#25943 Catch and ignore error on pack version retrieval
  Packs/HatchingTriage/Integrations/HatchingTriage/HatchingTriage.py
  Packs/HatchingTriage/Integrations/HatchingTriage/HatchingTriage.yml
  Packs/HatchingTriage/ReleaseNotes/1_0_10.md
  Packs/HatchingTriage/pack_metadata.json
Labels: Contribution, docs-approved, Partner, Contribution Form Filled

#25083 CrowdStrike file quarantine and exclusion
  Packs/CrowdStrikeFalcon/.secrets-ignore
  Packs/CrowdStrikeFalcon/Integrations/CrowdStrikeFalcon/CrowdStrikeFalcon.py
  Packs/CrowdStrikeFalcon/Integrations/CrowdStrikeFalcon/CrowdStrikeFalcon.yml
  Packs/CrowdStrikeFalcon/Integrations/CrowdStrikeFalcon/CrowdStrikeFalcon_test.py
  Packs/CrowdStrikeFalcon/Integrations/CrowdStrikeFalcon/README.md
  Packs/CrowdStrikeFalcon/Integrations/CrowdStrikeFalcon/examples.txt
  Packs/CrowdStrikeFalcon/Integrations/CrowdStrikeFalcon/test_data/create_ioa_exclusion.json
  Packs/CrowdStrikeFalcon/Integrations/CrowdStrikeFalcon/test_data/create_ml_exclusion.json
  Packs/CrowdStrikeFalcon/Integrations/CrowdStrikeFalcon/test_data/list_quarantine_files.json
  Packs/CrowdStrikeFalcon/ReleaseNotes/1_10_10.md
  Packs/CrowdStrikeFalcon/ReleaseNotes/1_10_13.md
  Packs/CrowdStrikeFalcon/TestPlaybooks/playbook-CrowdStrikeFalcon-Test.yml
  Packs/CrowdStrikeFalcon/pack_metadata.json
  Tests/conf.json
Labels: docs-approved

#25944 Isincidentpartofcampaign json loads bug
  Packs/Campaign/ReleaseNotes/3_2_21.md
  Packs/Campaign/Scripts/IsIncidentPartOfCampaign/IsIncidentPartOfCampaign.py
  Packs/Campaign/Scripts/IsIncidentPartOfCampaign/IsIncidentPartOfCampaign.yml
  Packs/Campaign/pack_metadata.json
Labels: docs-approved

#25951 change_to_community
  Packs/GigamonThreatINSIGHT/ReleaseNotes/1_0_2.md
  Packs/GigamonThreatINSIGHT/pack_metadata.json
Labels: docs-approved

#25923 Adding logs for EDL
  Packs/EDL/Integrations/EDL/EDL.py
  Packs/EDL/Integrations/EDL/EDL.yml
  Packs/EDL/ReleaseNotes/3_1_23.md
  Packs/EDL/pack_metadata.json
Labels: docs-approved

#25959 wrong filter for pdf files in playbook extract indicators from file generic v2
  Packs/CommonPlaybooks/Playbooks/playbook-Extract_Indicators_From_File_-_Generic_v2_4_5.yml
  Packs/CommonPlaybooks/Playbooks/playbook-Extract_Indicators_From_File_-_Generic_v2_4_5_README.md
  Packs/CommonPlaybooks/ReleaseNotes/2_3_59.md
  Packs/CommonPlaybooks/pack_metadata.json
Labels: docs-approved

#25957 update README.md
  Packs/Slack/Scripts/SlackBlockBuilder/README.md
Labels: docs-approved

#23800 Password Reset via Chatbot (new use-case)
  Packs/CommonTypes/IncidentFields/incidentfield-Approval_Status.json
  Packs/CommonTypes/IncidentFields/incidentfield-Approver.json
  Packs/CommonTypes/IncidentFields/incidentfield-Email_Sent_Successfully.json
  Packs/CommonTypes/IncidentFields/incidentfield-Password_Reset_Successfully.json
  Packs/CommonTypes/IncidentFields/incidentfield-Verification_Method.json
  Packs/CommonTypes/IncidentFields/incidentfield-Verification_Status.json
  Packs/CommonTypes/IncidentFields/incidentfield-reporteremailaddress.json
  Packs/CommonTypes/ReleaseNotes/3_3_64.md
  Packs/CommonTypes/pack_metadata.json
  Packs/PasswordResetViaChatbot/.pack-ignore
  Packs/PasswordResetViaChatbot/.secrets-ignore
  Packs/PasswordResetViaChatbot/IncidentTypes/incidenttype-Password_Reset_via_Chatbot.json
  Packs/PasswordResetViaChatbot/Layouts/layoutscontainer-Password_Reset_via_Chatbot.json
  Packs/PasswordResetViaChatbot/Playbooks/Reset_User_Password_via_Chatbot.yml
  Packs/PasswordResetViaChatbot/Playbooks/Reset_User_Password_via_Chatbot_README.md
  Packs/PasswordResetViaChatbot/README.md
  Packs/PasswordResetViaChatbot/doc_files/Reset_User_Password_via_Chatbot.png
  Packs/PasswordResetViaChatbot/pack_metadata.json
  Packs/Slack/Classifiers/classifier-Slack_Classifier.json
  Packs/Slack/Classifiers/classifier-Slack_Mapper.json
  Packs/Slack/ReleaseNotes/3_1_32.md
  Packs/Slack/pack_metadata.json
  Tests/known_words.txt
Labels: docs-approved

#25931 Added a new command !wfr-upload-file to upload a file with a specified file name.
  .devcontainer/devcontainer.json
  Packs/WebFileRepository/Integrations/WebFileRepository/README.md
  Packs/WebFileRepository/Integrations/WebFileRepository/WebFileRepository.py
  Packs/WebFileRepository/Integrations/WebFileRepository/WebFileRepository.yml
  Packs/WebFileRepository/Integrations/WebFileRepository/WebFileRepository_test.py
  Packs/WebFileRepository/ReleaseNotes/1_0_7.md
  Packs/WebFileRepository/pack_metadata.json
Labels: Contribution, docs-approved, Contribution Form Filled, Community

#25983 Bump sane-pdf-reports docker image
  Packs/Base/ReleaseNotes/1_31_89.md
  Packs/Base/Scripts/SanePdfReport/SanePdfReport.yml
  Packs/Base/pack_metadata.json
Labels: docs-approved

#25852 [GreyNoise Community] Fix to main function
  Packs/GreyNoise/.pack-ignore
  Packs/GreyNoise/Integrations/GreyNoise_Community/GreyNoise_Community.py
  Packs/GreyNoise/ReleaseNotes/1_2_8.md
  Packs/GreyNoise/pack_metadata.json
Labels: docs-approved

#25509 Arcsight json bug
  Packs/ArcSightESM/Integrations/ArcSightESMv2/ArcSightESMv2.py
  Packs/ArcSightESM/Integrations/ArcSightESMv2/ArcSightESMv2_test.py
  Packs/ArcSightESM/ReleaseNotes/1_1_10.md
  Packs/ArcSightESM/pack_metadata.json
Labels: docs-approved

#25809 Gcp folder tag
  Packs/CortexAttackSurfaceManagement/.pack-ignore
  Packs/CortexAttackSurfaceManagement/Playbooks/Cortex_ASM_-_ASM_Alert.yml
  Packs/CortexAttackSurfaceManagement/Playbooks/Cortex_ASM_-_ASM_Alert_README.md
  Packs/CortexAttackSurfaceManagement/Playbooks/Cortex_ASM_-_GCP_Enrichment.yml
  Packs/CortexAttackSurfaceManagement/Playbooks/Cortex_ASM_-_GCP_Enrichment_README.md
  Packs/CortexAttackSurfaceManagement/Playbooks/Cortex_ASM_-_Remediation_Path_Rules.yml
  Packs/CortexAttackSurfaceManagement/Playbooks/Cortex_ASM_-_Remediation_Path_Rules_README.md
  Packs/CortexAttackSurfaceManagement/ReleaseNotes/1_6_6.md
  Packs/CortexAttackSurfaceManagement/doc_files/Cortex_ASM_-_GCP_Enrichment.png
  Packs/CortexAttackSurfaceManagement/pack_metadata.json
  Packs/GCP-Enrichment-Remediation/Playbooks/GCP_-_Enrichment.yml
  Packs/GCP-Enrichment-Remediation/Playbooks/GCP_-_Enrichment_README.md
  Packs/GCP-Enrichment-Remediation/README.md
  Packs/GCP-Enrichment-Remediation/ReleaseNotes/1_1_2.md
  Packs/GCP-Enrichment-Remediation/Scripts/GCPProjectHierarchy/GCPProjectHierarchy.py
  Packs/GCP-Enrichment-Remediation/Scripts/GCPProjectHierarchy/GCPProjectHierarchy.yml
  Packs/GCP-Enrichment-Remediation/Scripts/GCPProjectHierarchy/GCPProjectHierarchy_test.py
  Packs/GCP-Enrichment-Remediation/Scripts/GCPProjectHierarchy/README.md
  Packs/GCP-Enrichment-Remediation/doc_files/GCPProjecHierarchy.png
  Packs/GCP-Enrichment-Remediation/doc_files/GCP_-_Enrichment.png
  Packs/GCP-Enrichment-Remediation/pack_metadata.json
  Packs/GCP-IAM/Integrations/GCPIAM/GCPIAM.py
  Packs/GCP-IAM/Integrations/GCPIAM/GCPIAM.yml
  Packs/GCP-IAM/Integrations/GCPIAM/GCPIAM_test.py
  Packs/GCP-IAM/Integrations/GCPIAM/README.md
  Packs/GCP-IAM/Integrations/GCPIAM/test_data/tag_bindings/tag_bindings.json
  Packs/GCP-IAM/Integrations/GCPIAM/test_data/tag_bindings/tag_keys.json
  Packs/GCP-IAM/Integrations/GCPIAM/test_data/tag_bindings/tag_values.json
  Packs/GCP-IAM/ReleaseNotes/1_0_16.md
  Packs/GCP-IAM/pack_metadata.json
Labels: Contribution, docs-approved, ready-for-instance-test, post-demo, Contribution Form Filled, Community

#25912 Saas security add query param
  Packs/PrismaSaasSecurity/Integrations/SaasSecurityEventCollector/README.md
  Packs/PrismaSaasSecurity/Integrations/SaasSecurityEventCollector/SaasSecurityEventCollector.py
  Packs/PrismaSaasSecurity/Integrations/SaasSecurityEventCollector/SaasSecurityEventCollector.yml
  Packs/PrismaSaasSecurity/Integrations/SaasSecurityEventCollector/SaasSecurityEventCollector_description.md
  Packs/PrismaSaasSecurity/Integrations/SaasSecurityEventCollector/SaasSecurityEventCollector_test.py
  Packs/PrismaSaasSecurity/ReleaseNotes/2_0_20.md
  Packs/PrismaSaasSecurity/pack_metadata.json
Labels: docs-approved

#25487 SonicWallNSv Modeling Rules
  Packs/SonicWallNSv/.pack-ignore
  Packs/SonicWallNSv/.secrets-ignore
  Packs/SonicWallNSv/ModelingRules/SonicWallNSv_1_3/SonicWallNSv_1_3.xif
  Packs/SonicWallNSv/ModelingRules/SonicWallNSv_1_3/SonicWallNSv_1_3.yml
  Packs/SonicWallNSv/ModelingRules/SonicWallNSv_1_3/SonicWallNSv_1_3_schema.json
  Packs/SonicWallNSv/ParsingRules/SonicWallNSvParsingRules/SonicWallNSvParsingRules.xif
  Packs/SonicWallNSv/ParsingRules/SonicWallNSvParsingRules/SonicWallNSvParsingRules.yml
  Packs/SonicWallNSv/README.md
  Packs/SonicWallNSv/pack_metadata.json
Labels: docs-approved

#26003 Integration/freshworks freshservice
  Packs/FreshworksFreshservice/README.md
  Packs/FreshworksFreshservice/pack_metadata.json
Labels: Contribution

#25786 Add workflow to check is changes were made to a protected directory
  .github/workflows/protect-infra-directories.yml
  Utils/check_protected_directories.py
Labels: docs-approved

#24565 disable network in docker images
  Packs/ApiModules/.pack-ignore
  Packs/Base/.pack-ignore
  Packs/CommonScripts/.pack-ignore
  Packs/Slack/.pack-ignore
  Packs/SymantecDLP/.pack-ignore
  Packs/WebFileRepository/.pack-ignore
  Packs/Whois/.pack-ignore
  Packs/rasterize/.pack-ignore
Labels: docs-approved

#25938 Map pattern: Fixed an issue where the entire comparison value was not given for the DT.
  Packs/FiltersAndTransformers/ReleaseNotes/1_2_15.md
  Packs/FiltersAndTransformers/Scripts/MapPattern/MapPattern.py
  Packs/FiltersAndTransformers/Scripts/MapPattern/MapPattern.yml
  Packs/FiltersAndTransformers/Scripts/MapPattern/MapPattern_test.py
  Packs/FiltersAndTransformers/Scripts/MapPattern/test_data/test-1.json
  Packs/FiltersAndTransformers/pack_metadata.json
Labels: Contribution, Contribution Form Filled, Community

#26008 Fix path issue in protected dir validation
  .github/workflows/protect-infra-directories.yml
Labels: docs-approved

#25978 Fix outdated QRadar document links
  Packs/QRadar/Integrations/QRadar_v3/QRadar_v3.yml
  Packs/QRadar/Integrations/QRadar_v3/README.md
  Packs/QRadar/ReleaseNotes/2_4_17.md
  Packs/QRadar/pack_metadata.json
Labels: docs-approved

#25968 [ResolveShortenedURL] Add Proxy Support
  Packs/CommonScripts/ReleaseNotes/1_11_62.md
  Packs/CommonScripts/Scripts/ResolveShortenedURL/ResolveShortenedURL.py
  Packs/CommonScripts/Scripts/ResolveShortenedURL/ResolveShortenedURL.yml
  Packs/CommonScripts/pack_metadata.json
Labels: docs-approved

#26027 Fix instructions for Get URL
  Packs/CortexXDR/Integrations/CortexXDRIR/CortexXDRIR_description.md
  Packs/CortexXDR/Integrations/CortexXDRIR/README.md
  Packs/CortexXDR/ReleaseNotes/4_10_34.md
  Packs/CortexXDR/pack_metadata.json
Labels: docs-approved

#26013 Search packs one by one in the build install packs step
  Tests/Marketplace/search_and_install_packs.py
Labels: docs-approved

#26032 Vmware Vcenter Parsing Logic Update
  Packs/VMwareVCenter/ParsingRules/VMwareVcenterParsingRules/VMwareVcenterParsingRules.xif
  Packs/VMwareVCenter/ReleaseNotes/1_0_6.md
  Packs/VMwareVCenter/pack_metadata.json
Labels: docs-approved

#25769 XSUP-22673 - SumoLogic search limit
  Packs/SumoLogic/Integrations/SumoLogic/SumoLogic.js
  Packs/SumoLogic/Integrations/SumoLogic/SumoLogic.yml
  Packs/SumoLogic/ReleaseNotes/1_1_2.md
  Packs/SumoLogic/pack_metadata.json
  Tests/conf.json
Labels: ForceMerge

#26028 remove traps from native image config
  Tests/docker_native_image_config.json
Labels: docs-approved

#25699 Cloudflare waf modeling rules
  Packs/CloudflareWAF/ModelingRules/CloudflareWAF/CloudflareWAF.xif
  Packs/CloudflareWAF/ModelingRules/CloudflareWAF/CloudflareWAF.yml
  Packs/CloudflareWAF/ModelingRules/CloudflareWAF/CloudflareWAF_schema.json
  Packs/CloudflareWAF/ParsingRules/CloudflareWAF/CloudflareWAF.xif
  Packs/CloudflareWAF/ParsingRules/CloudflareWAF/CloudflareWAF.yml
  Packs/CloudflareWAF/README.md
  Packs/CloudflareWAF/ReleaseNotes/1_0_12.md
  Packs/CloudflareWAF/pack_metadata.json
Labels: docs-approved

#26039 Duo modelingrules schema fix
  Packs/DuoAdminApi/ModelingRules/DuoModelingRule_1_3/DuoModelingRule_1_3_schema.json
  Packs/DuoAdminApi/ReleaseNotes/3_2_11.md
  Packs/DuoAdminApi/pack_metadata.json
Labels: docs-approved

#25996 Joe security v2 palybook
  Packs/CommonPlaybooks/Playbooks/playbook-Detonate_File_-_Generic.yml
  Packs/CommonPlaybooks/Playbooks/playbook-Detonate_File_-_Generic_README.md
  Packs/CommonPlaybooks/ReleaseNotes/2_3_60.md
  Packs/CommonPlaybooks/doc_files/Detonate_File_-_Generic.png
  Packs/CommonPlaybooks/pack_metadata.json
  Packs/JoeSecurity/Playbooks/playbook-Detonate_File_-_JoeSecurity_V2.yml
  Packs/JoeSecurity/Playbooks/playbook-Detonate_File_-_JoeSecurity_V2_README.md
  Packs/JoeSecurity/ReleaseNotes/1_1_9.md
  Packs/JoeSecurity/doc_files/Detonate_File_-_JoeSecurity_V2.png
  Packs/JoeSecurity/pack_metadata.json
Labels: docs-approved, release-notes-only

#26033 Fix/CIAC 6329/fix TPB test CrowdStrike falcon
  Packs/CrowdStrikeFalcon/TestPlaybooks/playbook-CrowdStrikeFalcon-Test.yml
Labels: docs-approved

#25946 zendesk fetch query
  Packs/Zendesk/Integrations/Zendeskv2/README.md
  Packs/Zendesk/Integrations/Zendeskv2/Zendeskv2.py
  Packs/Zendesk/Integrations/Zendeskv2/Zendeskv2.yml
  Packs/Zendesk/Integrations/Zendeskv2/Zendeskv2_test.py
  Packs/Zendesk/ReleaseNotes/2_0_6.json
  Packs/Zendesk/ReleaseNotes/2_0_6.md
  Packs/Zendesk/pack_metadata.json
Labels: docs-approved

#26035 Proof point log version
  Packs/ProofpointTAP/Integrations/ProofpointTAP_v2/ProofpointTAP_v2.py
  Packs/ProofpointTAP/Integrations/ProofpointTAP_v2/ProofpointTAP_v2.yml
  Packs/ProofpointTAP/ReleaseNotes/1_2_3.md
  Packs/ProofpointTAP/pack_metadata.json
Labels: docs-approved

#26034 fix urllib warnings
  Tests/scripts/destroy_instances.py
Labels: docs-approved

#26038 Fixed test playbook for URL extraction and added it as a test PB to formatter
  Packs/Base/.secrets-ignore
  Packs/Base/TestPlaybooks/playbook-URLextraction-Test.yml
  Packs/CommonScripts/ReleaseNotes/1_11_63.md
  Packs/CommonScripts/Scripts/FormatURL/FormatURL.yml
  Packs/CommonScripts/pack_metadata.json
Labels: docs-approved

#26031 [PAN-OS] fixed contextPath
  Packs/PAN-OS/Integrations/Panorama/Panorama.yml
  Packs/PAN-OS/Integrations/Panorama/README.md
  Packs/PAN-OS/ReleaseNotes/1_16_20.md
  Packs/PAN-OS/pack_metadata.json
Labels: docs-approved, ForceMerge

#26044 Issue in get durationin GetIncidentsByQuery
  Packs/Base/ReleaseNotes/1_31_91.md
  Packs/Base/Scripts/GetIncidentsByQuery/GetIncidentsByQuery.py
  Packs/Base/Scripts/GetIncidentsByQuery/GetIncidentsByQuery.yml
  Packs/Base/Scripts/GetIncidentsByQuery/GetIncidentsByQuery_test.py
  Packs/Base/pack_metadata.json
Labels: docs-approved

#25975 Qualys: update PB to try get the scan metadata after creation
  Packs/qualys/Integrations/Qualysv2/Qualysv2.py
  Packs/qualys/Integrations/Qualysv2/Qualysv2.yml
  Packs/qualys/Playbooks/playbook-Launch_And_Fetch_Scan_Based_Findings_Report_-_Qualys.yml
  Packs/qualys/Playbooks/playbook-Launch_And_Fetch_Scan_Based_Findings_Report_-_Qualys_README.md
  Packs/qualys/ReleaseNotes/1_2_6.json
  Packs/qualys/ReleaseNotes/1_2_6.md
  Packs/qualys/doc_files/Launch_And_Fetch_Scan_Based_Findings_Report_-_Qualys.png
  Packs/qualys/pack_metadata.json
Labels: docs-approved

#25995 Add certificate auth to aad identity and acess
  Packs/MicrosoftGraphIdentityandAccess/Integrations/MicrosoftGraphIdentityandAccess/MicrosoftGraphIdentityandAccess.py
  Packs/MicrosoftGraphIdentityandAccess/Integrations/MicrosoftGraphIdentityandAccess/MicrosoftGraphIdentityandAccess.yml
  Packs/MicrosoftGraphIdentityandAccess/Integrations/MicrosoftGraphIdentityandAccess/MicrosoftGraphIdentityandAccess_test.py
  Packs/MicrosoftGraphIdentityandAccess/Integrations/MicrosoftGraphIdentityandAccess/README.md
  Packs/MicrosoftGraphIdentityandAccess/ReleaseNotes/1_2_19.md
  Packs/MicrosoftGraphIdentityandAccess/pack_metadata.json
Labels: docs-approved

#26070 [HelloWorld Feed] Handling case of an empty relationship
  Packs/HelloWorld/Integrations/FeedHelloWorld/FeedHelloWorld.py
  Packs/HelloWorld/Integrations/FeedHelloWorld/FeedHelloWorld.yml
  Packs/HelloWorld/ReleaseNotes/1_2_19.md
  Packs/HelloWorld/pack_metadata.json
Labels: docs-approved

#25226 show html body in send-mail
  Packs/CommonScripts/ReleaseNotes/1_11_64.md
  Packs/CommonScripts/Scripts/EmailAskUser/EmailAskUser.js
  Packs/CommonScripts/Scripts/EmailAskUser/EmailAskUser.yml
  Packs/CommonScripts/pack_metadata.json
  Packs/Gmail/Integrations/Gmail/Gmail.py
  Packs/Gmail/Integrations/Gmail/Gmail.yml
  Packs/Gmail/ReleaseNotes/1_3_5.md
  Packs/Gmail/pack_metadata.json
  Packs/GmailSingleUser/Integrations/GmailSingleUser/GmailSingleUser.py
  Packs/GmailSingleUser/Integrations/GmailSingleUser/GmailSingleUser.yml
  Packs/GmailSingleUser/ReleaseNotes/1_3_8.md
  Packs/GmailSingleUser/pack_metadata.json
  Packs/MailSenderNew/Integrations/MailSenderNew/MailSenderNew.py
  Packs/MailSenderNew/Integrations/MailSenderNew/MailSenderNew.yml
  Packs/MailSenderNew/Integrations/MailSenderNew/MailSenderNew_test.py
  Packs/MailSenderNew/ReleaseNotes/1_0_12.md
  Packs/MailSenderNew/ReleaseNotes/1_0_13.md
  Packs/MailSenderNew/pack_metadata.json
  Packs/MicrosoftExchangeOnPremise/Integrations/EWSv2/EWSv2.py
  Packs/MicrosoftExchangeOnPremise/Integrations/EWSv2/EWSv2.yml
  Packs/MicrosoftExchangeOnPremise/Integrations/EWSv2/EWSv2_test.py
  Packs/MicrosoftExchangeOnPremise/ReleaseNotes/1_0_9.md
  Packs/MicrosoftExchangeOnPremise/TestPlaybooks/playbook-EWS-Searchmailbox-Test.yml
  Packs/MicrosoftExchangeOnPremise/pack_metadata.json
  Packs/MicrosoftExchangeOnline/Integrations/EWSO365/EWSO365.py
  Packs/MicrosoftExchangeOnline/Integrations/EWSO365/EWSO365.yml
  Packs/MicrosoftExchangeOnline/ReleaseNotes/1_1_7.md
  Packs/MicrosoftExchangeOnline/TestPlaybooks/playbook-EWS_O365_test.yml
  Packs/MicrosoftExchangeOnline/pack_metadata.json
  Packs/MicrosoftGraphMail/Integrations/MicrosoftGraphListener/MicrosoftGraphListener.py
  Packs/MicrosoftGraphMail/Integrations/MicrosoftGraphListener/MicrosoftGraphListener.yml
  Packs/MicrosoftGraphMail/Integrations/MicrosoftGraphListener/MicrosoftGraphListener_test.py
  Packs/MicrosoftGraphMail/Integrations/MicrosoftGraphMail/MicrosoftGraphMail.py
  Packs/MicrosoftGraphMail/Integrations/MicrosoftGraphMail/MicrosoftGraphMail.yml
  Packs/MicrosoftGraphMail/ReleaseNotes/1_4_18.md
  Packs/MicrosoftGraphMail/pack_metadata.json
  Tests/conf.json
Labels: docs-approved, ForceMerge

#26104 [Symantec Data Loss Protection V2] fixed - 'ValueError: empty separator' when using the incidentStatusId parameter
  Packs/SymantecDLP/.pack-ignore
  Packs/SymantecDLP/Integrations/SymantecDLPV2/SymantecDLPV2.py
  Packs/SymantecDLP/Integrations/SymantecDLPV2/SymantecDLPV2.yml
  Packs/SymantecDLP/ReleaseNotes/2_0_10.md
  Packs/SymantecDLP/pack_metadata.json
Labels: docs-approved

#26102 Modify schema file couldflare waf
  Packs/CloudflareWAF/.pack-ignore
  Packs/CloudflareWAF/ModelingRules/CloudflareWAF/CloudflareWAF_schema.json
  Packs/CloudflareWAF/ReleaseNotes/1_0_13.md
  Packs/CloudflareWAF/pack_metadata.json
Labels: docs-approved

#26073 Fix For 'Cortex XDR - Retrieve File by sha256' playbook
  Packs/CortexXDR/.pack-ignore
  Packs/CortexXDR/Playbooks/playbook-Cortex_XDR_-_Retrieve_File_by_sha256.yml
  Packs/CortexXDR/Playbooks/playbook-Cortex_XDR_-_Retrieve_File_by_sha256_README.md
  Packs/CortexXDR/ReleaseNotes/4_10_35.md
  Packs/CortexXDR/pack_metadata.json
Labels: docs-approved

#26108 Validate content-test-conf failed when brachname is substring of the branchname
  .gitlab/ci/on-push.yml
Labels: docs-approved
