Repository demisto/content, pull requests merged in 2023-05, with the labels that each got.

#25684 Fixing the slack notify upload bug (show only packs which uploaded successfully for xsiam)
  Tests/Marketplace/marketplace_constants.py
  Tests/Marketplace/marketplace_services.py
  Tests/scripts/gitlab_slack_notifier.py
Labels: docs-approved

#26152 [Box] Fix LastRun setting in event collector
  Packs/Box/Integrations/BoxEventsCollector/BoxEventsCollector.py
  Packs/Box/Integrations/BoxEventsCollector/BoxEventsCollector.yml
  Packs/Box/ReleaseNotes/3_1_21.md
  Packs/Box/pack_metadata.json
Labels: docs-approved

#26120 Fix several integration issues created by recent XSOAR platform changes.
  Packs/Box/Integrations/BoxEventsCollector/BoxEventsCollector.py
  Packs/Box/Integrations/BoxEventsCollector/BoxEventsCollector.yml
  Packs/Box/ReleaseNotes/3_1_21.md
  Packs/Box/pack_metadata.json
Labels: Contribution, Partner, Contribution Form Filled

#26153 Set Fields Searchable
  Packs/SentinelOne/IncidentFields/incidentfield-SentinelOne_Threat_Analyst_Verdict.json
  Packs/SentinelOne/IncidentFields/incidentfield-SentinelOne_Threat_ID.json
  Packs/SentinelOne/IncidentFields/incidentfield-SentinelOne_Threat_Status.json
  Packs/SentinelOne/ReleaseNotes/3_1_2.md
  Packs/SentinelOne/pack_metadata.json
Labels: docs-approved, Partner

#26155 Added option to distinguish between fixes and relates in jira message
  Utils/github_workflow_scripts/github_workflow_scripts_tests/link_pr_to_jira_issue_test.py
  Utils/github_workflow_scripts/jira_integration_scripts/link_pr_to_jira_issue.py
Labels: docs-approved

#26163 Change NG job to be required
  .gitlab/ci/on-push.yml
Labels: docs-approved

#26160 [CoreIRApiModule] endpoint command
  Packs/ApiModules/Scripts/CoreIRApiModule/CoreIRApiModule.py
  Packs/ApiModules/Scripts/CoreIRApiModule/CoreIRApiModule_test.py
  Packs/Core/ReleaseNotes/1_3_48.md
  Packs/Core/pack_metadata.json
  Packs/CortexXDR/ReleaseNotes/4_10_36.md
  Packs/CortexXDR/pack_metadata.json
Labels: docs-approved

#26150 Add fields argument to core-delete-incidents
  Packs/DemistoRESTAPI/Integrations/CoreRESTAPI/CoreRESTAPI.yml
  Packs/DemistoRESTAPI/ReleaseNotes/1_3_22.md
  Packs/DemistoRESTAPI/pack_metadata.json
Labels: docs-approved, ForceMerge

#26103 Mandiant feed convert to aware date_time
  Packs/FeedMandiant/Integrations/FeedMandiant/FeedMandiant.py
  Packs/FeedMandiant/Integrations/FeedMandiant/FeedMandiant.yml
  Packs/FeedMandiant/Integrations/FeedMandiant/FeedMandiant_test.py
  Packs/FeedMandiant/ReleaseNotes/1_0_12.md
  Packs/FeedMandiant/pack_metadata.json
Labels: docs-approved

#26161 Update CODEOWNERS
  .github/CODEOWNERS
Labels: docs-approved

#26151 Yr ciac 6129 fix 8 commands to work with a singel fw
  Packs/PAN-OS/Integrations/Panorama/Panorama.py
  Packs/PAN-OS/Integrations/Panorama/Panorama_test.py
  Packs/PAN-OS/ReleaseNotes/1_16_22.md
  Packs/PAN-OS/pack_metadata.json
Labels: docs-approved

#26077 Upload latest pb ciac 5787
  Tests/Marketplace/Tests/test_data/TestPack/Playbooks/playbook-Threat_Hunting_-_Generic copy.yml
  Tests/Marketplace/Tests/test_data/TestPack/Playbooks/playbook-Threat_Hunting_-_Generic.yml
  Tests/Marketplace/Tests/test_data/TestPack/Playbooks/playbook-Threat_Hunting_-_Generic_6_2.yml
  Tests/Marketplace/Tests/test_data/TestPack/Playbooks/playbook-Threat_Hunting_-_Generic_6_5.yml
  Tests/Marketplace/marketplace_services.py
  Tests/known_words.txt
Labels: docs-approved

#26188 [FireEyeHX] Fix LastRun setting in event collector
  Packs/FireEyeHX/Integrations/FireEyeHXEventCollector/FireEyeHXEventCollector.py
  Packs/FireEyeHX/Integrations/FireEyeHXEventCollector/FireEyeHXEventCollector.yml
  Packs/FireEyeHX/ReleaseNotes/2_3_6.md
  Packs/FireEyeHX/pack_metadata.json
Labels: docs-approved

#26212 Cloudflare fix timestamp
  Packs/CloudflareWAF/ParsingRules/CloudflareWAF/CloudflareWAF.xif
  Packs/CloudflareWAF/ReleaseNotes/1_0_14.md
  Packs/CloudflareWAF/pack_metadata.json
Labels: docs-approved

#26154 Fixed typo in vmray-get-sample Command
  Packs/VMRay/Integrations/VMRay/VMRay.py
  Packs/VMRay/Integrations/VMRay/VMRay.yml
  Packs/VMRay/ReleaseNotes/1_1_9.md
  Packs/VMRay/pack_metadata.json
Labels: docs-approved, Partner

#26156 Account enrichment fix
  Packs/CommonPlaybooks/Playbooks/playbook-Account_Enrichment_-_Generic_v2.2.yml
  Packs/CommonPlaybooks/ReleaseNotes/2_3_61.md
  Packs/CommonPlaybooks/pack_metadata.json
Labels: docs-approved

#26209 [Mimecast] Fix LastRun setting in event collector
  Packs/Mimecast/Integrations/MimecastEventCollector/MimecastEventCollector.py
  Packs/Mimecast/Integrations/MimecastEventCollector/MimecastEventCollector.yml
  Packs/Mimecast/Integrations/MimecastEventCollector/MimecastEventCollector_test.py
  Packs/Mimecast/ReleaseNotes/2_1_7.md
  Packs/Mimecast/pack_metadata.json
Labels: docs-approved

#26086 EXPANDR-3582 Resolving AWS-IAM bug
  Packs/AWS-Enrichment-Remediation/Playbooks/AWS_-_Enrichment.yml
  Packs/AWS-Enrichment-Remediation/Playbooks/AWS_-_Enrichment_README.md
  Packs/AWS-Enrichment-Remediation/README.md
  Packs/AWS-Enrichment-Remediation/ReleaseNotes/1_1_2.md
  Packs/AWS-Enrichment-Remediation/doc_files/AWS_-_Enrichment.png
  Packs/AWS-Enrichment-Remediation/pack_metadata.json
Labels: Contribution, ready-for-instance-test, Contribution Form Filled, Community, pending-contributor

#26220 [Netbox] Fix LastRun setting in event collector
  Packs/NetBox/Integrations/NetBoxEventCollector/NetBoxEventCollector.py
  Packs/NetBox/Integrations/NetBoxEventCollector/NetBoxEventCollector.yml
  Packs/NetBox/ReleaseNotes/1_0_4.md
  Packs/NetBox/pack_metadata.json
Labels: docs-approved

#26123 [ASM] EXPANDR-3750 - Serviceownership enrichment hotfix
  Packs/CortexAttackSurfaceManagement/Playbooks/Cortex_ASM_-_Enrichment.yml
  Packs/CortexAttackSurfaceManagement/ReleaseNotes/1_6_8.md
  Packs/CortexAttackSurfaceManagement/pack_metadata.json
Labels: Contribution, docs-approved, ready-for-instance-test, Contribution Form Filled, Community

#26221 [Netskope] Fix LastRun setting in event collector
  Packs/Netskope/Integrations/NetskopeEventCollector/NetskopeEventCollector.py
  Packs/Netskope/Integrations/NetskopeEventCollector/NetskopeEventCollector.yml
  Packs/Netskope/ReleaseNotes/3_0_14.md
  Packs/Netskope/pack_metadata.json
Labels: docs-approved

#26224 [OneLogin] Fix LastRun setting in event collector
  Packs/OneLogin/Integrations/OneLoginEventCollector/OneLoginEventCollector.py
  Packs/OneLogin/Integrations/OneLoginEventCollector/OneLoginEventCollector.yml
  Packs/OneLogin/ReleaseNotes/1_0_4.md
  Packs/OneLogin/pack_metadata.json
Labels: docs-approved, ForceMerge

#26227 run test-upload-flow in sdk nightly
  Utils/should_trigger_test_upload.sh
Labels: docs-approved

#26065 extract content test conf properly
  Tests/scripts/download_demisto_conf.sh
  Tests/scripts/extract_content_test_conf.py
  Tests/scripts/gitlab_slack_notifier.py
Labels: docs-approved

#26225 [ProofpointThreatResponse] Fix LastRun setting in event collector
  Packs/ProofpointThreatResponse/Integrations/ProofpointThreatResponseEventCollector/ProofpointThreatResponseEventCollector.py
  Packs/ProofpointThreatResponse/Integrations/ProofpointThreatResponseEventCollector/ProofpointThreatResponseEventCollector.yml
  Packs/ProofpointThreatResponse/ReleaseNotes/2_0_9.md
  Packs/ProofpointThreatResponse/pack_metadata.json
Labels: docs-approved

#26203 Fixd Dashboard date range
  Packs/CommonDashboards/Dashboards/dashboard-My_Threat_Landscape.json
  Packs/CommonDashboards/ReleaseNotes/1_3_2.md
  Packs/CommonDashboards/pack_metadata.json
Labels: docs-approved

#26041 Added new transformers which are MakePair, SortBy and DedupBy
  Packs/FiltersAndTransformers/.secrets-ignore
  Packs/FiltersAndTransformers/ReleaseNotes/1_2_16.md
  Packs/FiltersAndTransformers/Scripts/DedupBy/DedupBy.py
  Packs/FiltersAndTransformers/Scripts/DedupBy/DedupBy.yml
  Packs/FiltersAndTransformers/Scripts/DedupBy/DedupBy_test.py
  Packs/FiltersAndTransformers/Scripts/DedupBy/README.md
  Packs/FiltersAndTransformers/Scripts/DedupBy/test_data/test-1.json
  Packs/FiltersAndTransformers/Scripts/MakePair/MakePair.py
  Packs/FiltersAndTransformers/Scripts/MakePair/MakePair.yml
  Packs/FiltersAndTransformers/Scripts/MakePair/MakePair_test.py
  Packs/FiltersAndTransformers/Scripts/MakePair/README.md
  Packs/FiltersAndTransformers/Scripts/MakePair/test_data/test-1.json
  Packs/FiltersAndTransformers/Scripts/SortBy/README.md
  Packs/FiltersAndTransformers/Scripts/SortBy/SortBy.py
  Packs/FiltersAndTransformers/Scripts/SortBy/SortBy.yml
  Packs/FiltersAndTransformers/Scripts/SortBy/SortBy_test.py
  Packs/FiltersAndTransformers/Scripts/SortBy/test_data/test-shuffleable.json
  Packs/FiltersAndTransformers/pack_metadata.json
Labels: Contribution, docs-approved, ready-for-instance-test, post-demo, Contribution Form Filled, Community, pending-contributor

#25939 [VirusTotal] Add private scanning
  Packs/VirusTotal/Integrations/FeedLivehunt/FeedLivehunt.yml
  Packs/VirusTotal/Integrations/FeedRetrohunt/FeedRetrohunt.yml
  Packs/VirusTotal/Integrations/VirusTotalV3/README.md
  Packs/VirusTotal/Integrations/VirusTotalV3/VirusTotalV3.py
  Packs/VirusTotal/Integrations/VirusTotalV3/VirusTotalV3.yml
  Packs/VirusTotal/Integrations/VirusTotalV3/VirusTotalV3_test.py
  Packs/VirusTotal/Integrations/VirusTotalV3/test_data/private_file.json
  Packs/VirusTotal/Integrations/VirusTotalV3/test_data/private_file_results.json
  Packs/VirusTotal/Integrations/VirusTotal_V3_Premium/VirusTotal_V3_Premium.yml
  Packs/VirusTotal/Playbooks/Detonate_Private_File_-_VirusTotal_V3.yml
  Packs/VirusTotal/Playbooks/Detonate_Private_File_-_VirusTotal_V3_README.md
  Packs/VirusTotal/README.md
  Packs/VirusTotal/ReleaseNotes/2_6_0.md
  Packs/VirusTotal/doc_files/Detonate_Private_File_-_VirusTotal_V3.png
  Packs/VirusTotal/pack_metadata.json
Labels: Contribution, docs-approved, Partner, ready-for-instance-test, post-demo, Contribution Form Filled, pending-contributor

#26228 fix splunk 404 error msg
  Packs/SplunkPy/Integrations/SplunkPy/SplunkPy.py
  Packs/SplunkPy/Integrations/SplunkPy/SplunkPy.yml
  Packs/SplunkPy/ReleaseNotes/3_0_16.md
  Packs/SplunkPy/pack_metadata.json
Labels: docs-approved, release-notes-only

#26012 Check if packs is dict or list.
  Packs/GreyNoise/Integrations/GreyNoise/GreyNoise.py
  Packs/GreyNoise/ReleaseNotes/1_2_9.md
  Packs/GreyNoise/pack_metadata.json
Labels: docs-approved

#26233 SDK Release 1.14.0
  .gitlab/ci/.gitlab-ci.yml
  .gitlab/ci/bucket-upload.yml
  .gitlab/ci/on-push.yml
  .gitlab/ci/sdk-nightly.yml
  poetry.lock
  pyproject.toml
Labels: docs-approved, ForceMerge

#26243 CrowdStrike Falcon Intel Feed Actors: add offset to last run
  Packs/FeedCrowdstrikeFalconIntel/Integrations/FeedCrowdstrikeFalconIntel/FeedCrowdstrikeFalconIntel.py
  Packs/FeedCrowdstrikeFalconIntel/Integrations/FeedCrowdstrikeFalconIntel/FeedCrowdstrikeFalconIntel.yml
  Packs/FeedCrowdstrikeFalconIntel/Integrations/FeedCrowdstrikeFalconIntel/FeedCrowdstrikeFalconIntel_test.py
  Packs/FeedCrowdstrikeFalconIntel/ReleaseNotes/2_1_5.md
  Packs/FeedCrowdstrikeFalconIntel/pack_metadata.json
Labels: docs-approved

#23811 Reimplment precommit
  .github/workflows/pre-commit.yml
  .gitignore
  .hooks/pre-commit
  .pre-commit-config.yaml
  Tests/Marketplace/copy_and_upload_packs.py
  Tests/Marketplace/marketplace_services.py
  Tests/Marketplace/search_and_install_packs.py
  Tests/Marketplace/upload_packs.py
  Tests/configure_and_test_integration_instances.py
  Tests/private_build/upload_packs_private.py
  Tests/scripts/collect_tests/collect_tests.py
  Tests/scripts/collect_tests/exceptions.py
  Tests/scripts/collect_tests/test_conf.py
  Tests/scripts/collect_tests/utils.py
  Tests/scripts/destroy_instances.py
  Tests/scripts/gitlab_slack_notifier.py
  Tests/scripts/infrastructure_tests/test_collect_tests.py
  Tests/scripts/is_file_up_to_date.sh
  Tests/scripts/linters_runner.sh
  Tests/scripts/lock_cloud_machines.py
  Tests/scripts/mypy.sh
  Tests/scripts/utils/GoogleSecretManagerModule.py
  Tests/scripts/validate_premium_packs.py
  Tests/scripts/verify_base_branch_for_contribution.py
  Tests/scripts/wait_until_server_ready.py
  Tests/secrets_white_list.json
  Tests/test_content.py
  Utils/delete_mismatched_branches.py
  Utils/get_private_build_status.py
  Utils/release_notes_generator.py
  Utils/trigger_private_build.py
  __init__.py
  poetry.lock
  pyproject.toml
Labels: ForceMerge

#26264 Update CODEOWNERS
  .github/CODEOWNERS
Labels: docs-approved

#25917 [Microsoft Policy And Compliance (Audit Log)] Remove Support for Deprecated Basic Auth
  Packs/Office365AndAzureAuditLog/Integrations/MicrosoftPolicyAndComplianceAuditLog/MicrosoftPolicyAndComplianceAuditLog.ps1
  Packs/Office365AndAzureAuditLog/Integrations/MicrosoftPolicyAndComplianceAuditLog/MicrosoftPolicyAndComplianceAuditLog.yml
  Packs/Office365AndAzureAuditLog/Integrations/MicrosoftPolicyAndComplianceAuditLog/MicrosoftPolicyAndComplianceAuditLog_description.md
  Packs/Office365AndAzureAuditLog/Integrations/MicrosoftPolicyAndComplianceAuditLog/README.md
  Packs/Office365AndAzureAuditLog/ReleaseNotes/1_0_4.md
  Packs/Office365AndAzureAuditLog/pack_metadata.json
  Tests/conf.json
Labels: docs-approved

#26248 Improve pr link in jira comment
  Utils/github_workflow_scripts/jira_integration_scripts/link_pr_to_jira_issue.py
Labels: docs-approved

#26267 [SearchIncidentsV2] - update unit-tests
  Packs/CommonScripts/Scripts/SearchIncidentsV2/SearchIncidentsV2_test.py
Labels: docs-approved

#26105 [MISP Feed] Update test-module
  Packs/FeedMISP/Integrations/FeedMISP/FeedMISP.py
  Packs/FeedMISP/Integrations/FeedMISP/FeedMISP.yml
  Packs/FeedMISP/ReleaseNotes/1_0_21.md
  Packs/FeedMISP/pack_metadata.json
Labels: docs-approved

#26266 Corelight zeek modeling fix2
  Packs/CorelightZeek/ModelingRules/CorelightZeek/CorelightZeek.xif
  Packs/CorelightZeek/ModelingRules/CorelightZeek/CorelightZeek_schema.json
  Packs/CorelightZeek/ReleaseNotes/1_0_3.md
  Packs/CorelightZeek/pack_metadata.json
Labels: docs-approved

#25736 xsiam reports support
  Tests/Marketplace/marketplace_constants.py
  Tests/Marketplace/marketplace_services.py
  Tests/scripts/collect_tests/utils.py
Labels: docs-approved

#26140 Cisco integrations - fix format_timestamp method
  Packs/CiscoSMA/Integrations/CiscoSMA/CiscoSMA.py
  Packs/CiscoSMA/Integrations/CiscoSMA/CiscoSMA_test.py
  Packs/CiscoSMA/ReleaseNotes/1_1_11.md
  Packs/CiscoSMA/pack_metadata.json
  Packs/IronPort/Integrations/CiscoEmailSecurityApplianceIronPortV2/CiscoEmailSecurityApplianceIronPortV2.py
  Packs/IronPort/Integrations/CiscoEmailSecurityApplianceIronPortV2/CiscoEmailSecurityApplianceIronPortV2_test.py
  Packs/IronPort/ReleaseNotes/2_0_6.md
  Packs/IronPort/pack_metadata.json
Labels: docs-approved

#26207 [Microsoft365Defender] Fix LastRun setting in event collector
  Packs/MicrosoftDefenderAdvancedThreatProtection/Integrations/Microsoft365DefenderEventCollector/Microsoft365DefenderEventCollector.py
  Packs/MicrosoftDefenderAdvancedThreatProtection/Integrations/Microsoft365DefenderEventCollector/Microsoft365DefenderEventCollector.yml
  Packs/MicrosoftDefenderAdvancedThreatProtection/Integrations/Microsoft365DefenderEventCollector/Microsoft365DefenderEventCollector_test.py
  Packs/MicrosoftDefenderAdvancedThreatProtection/ReleaseNotes/1_15_21.md
  Packs/MicrosoftDefenderAdvancedThreatProtection/pack_metadata.json
Labels: docs-approved

#26274 [MSGraphMail] - TPB - mail-sending loop
  Packs/MicrosoftGraphMail/TestPlaybooks/playbook-MicrosoftGraphMail-Test.yml
Labels: docs-approved

#26223 [Okta] Fix LastRun setting in event collector
  Packs/Okta/Integrations/OktaEventCollector/OktaEventCollector.py
  Packs/Okta/ReleaseNotes/3_1_17.md
  Packs/Okta/pack_metadata.json
Labels: docs-approved

#26047 Updated tags for Plug & fetch feeds in XSOAR
  Packs/FeedAlienVault/pack_metadata.json
  Packs/FeedBlocklist_de/pack_metadata.json
  Packs/FeedBruteForceBlocker/pack_metadata.json
  Packs/FeedCSV/pack_metadata.json
  Packs/FeedDShield/pack_metadata.json
  Packs/FeedElasticsearch/pack_metadata.json
  Packs/FeedFeodoTracker/pack_metadata.json
  Packs/FeedJSON/pack_metadata.json
  Packs/FeedMajesticMillion/pack_metadata.json
  Packs/FeedMalwareBazaar/pack_metadata.json
  Packs/FeedMitreAttack/pack_metadata.json
  Packs/FeedOpenCTI/pack_metadata.json
  Packs/FeedPlainText/pack_metadata.json
  Packs/FeedRSS/pack_metadata.json
  Packs/FeedSpamhaus/pack_metadata.json
  Packs/FeedTAXII/pack_metadata.json
  Packs/FeedTalos/pack_metadata.json
  Packs/FeedTorExitAddresses/pack_metadata.json
  Packs/Feedsslabusech/pack_metadata.json
  Packs/FreeFeeds/.pack-ignore
  Packs/FreeFeeds/.secrets-ignore
  Packs/FreeFeeds/README.md
  Packs/FreeFeeds/pack_metadata.json
  Packs/NationalVulnerabilityDatabaseFeed/pack_metadata.json
  Packs/SnortIPBlocklist/pack_metadata.json
  Packs/TwitterIOCHunter-FullDailyFeed/pack_metadata.json
  Packs/URLHaus/pack_metadata.json
  Tests/Marketplace/approved_tags.json
Labels: docs-approved

#26235 Fix send-mail error
  Packs/Gmail/Integrations/Gmail/Gmail.yml
  Packs/Gmail/ReleaseNotes/1_3_6.md
  Packs/Gmail/pack_metadata.json
  Packs/GmailSingleUser/Integrations/GmailSingleUser/GmailSingleUser.py
  Packs/GmailSingleUser/Integrations/GmailSingleUser/GmailSingleUser.yml
  Packs/GmailSingleUser/ReleaseNotes/1_3_9.md
  Packs/GmailSingleUser/pack_metadata.json
  Packs/MailSenderNew/Integrations/MailSenderNew/MailSenderNew.yml
  Packs/MailSenderNew/ReleaseNotes/1_0_14.md
  Packs/MailSenderNew/pack_metadata.json
  Packs/MicrosoftExchangeOnPremise/Integrations/EWSv2/EWSv2.py
  Packs/MicrosoftExchangeOnPremise/Integrations/EWSv2/EWSv2.yml
  Packs/MicrosoftExchangeOnPremise/ReleaseNotes/1_0_10.md
  Packs/MicrosoftExchangeOnPremise/pack_metadata.json
  Packs/MicrosoftExchangeOnline/Integrations/EWSO365/EWSO365.py
  Packs/MicrosoftExchangeOnline/Integrations/EWSO365/EWSO365.yml
  Packs/MicrosoftExchangeOnline/ReleaseNotes/1_2_1.md
  Packs/MicrosoftExchangeOnline/pack_metadata.json
  Packs/MicrosoftGraphMail/Integrations/MicrosoftGraphListener/MicrosoftGraphListener.yml
  Packs/MicrosoftGraphMail/Integrations/MicrosoftGraphMail/MicrosoftGraphMail.py
  Packs/MicrosoftGraphMail/Integrations/MicrosoftGraphMail/MicrosoftGraphMail.yml
  Packs/MicrosoftGraphMail/ReleaseNotes/1_4_19.md
  Packs/MicrosoftGraphMail/pack_metadata.json
Labels: docs-approved, ForceMerge

#26275 Tableau ModelingRules Fix
  Packs/Tableau/ModelingRules/Tableau_1_3/Tableau_1_3.xif
  Packs/Tableau/ReleaseNotes/1_0_10.md
  Packs/Tableau/pack_metadata.json
Labels: docs-approved

#26282 [CoreIRApiModule] fix bug in retrieve-files
  Packs/ApiModules/Scripts/CoreIRApiModule/CoreIRApiModule.py
  Packs/ApiModules/Scripts/CoreIRApiModule/CoreIRApiModule_test.py
  Packs/ApiModules/Scripts/CoreIRApiModule/test_data/get_endpoints_linux_response.json
  Packs/ApiModules/Scripts/CoreIRApiModule/test_data/get_endpoints_mac_response.json
  Packs/ApiModules/Scripts/CoreIRApiModule/test_data/get_endpoints_windows_response.json
  Packs/Core/ReleaseNotes/1_3_49.md
  Packs/Core/pack_metadata.json
  Packs/CortexXDR/ReleaseNotes/4_10_37.md
  Packs/CortexXDR/pack_metadata.json
Labels: docs-approved

#26287 [ASM] - Expander - Update service owner playbook
  Packs/CortexAttackSurfaceManagement/Playbooks/Cortex_ASM_-_Service_Ownership.yml
  Packs/CortexAttackSurfaceManagement/Playbooks/Cortex_ASM_-_Service_Ownership_README.md
  Packs/CortexAttackSurfaceManagement/README.md
  Packs/CortexAttackSurfaceManagement/ReleaseNotes/1_6_9.md
  Packs/CortexAttackSurfaceManagement/doc_files/Cortex_ASM_-_Service_Ownership.png
  Packs/CortexAttackSurfaceManagement/pack_metadata.json
Labels: Contribution, ready-for-instance-test, Contribution Form Filled, Community

#26276 Securonix Release 203
  Packs/Securonix/Integrations/Securonix/Securonix.py
  Packs/Securonix/Integrations/Securonix/Securonix.yml
  Packs/Securonix/ReleaseNotes/2_0_3.md
  Packs/Securonix/Scripts/SecuronixCloseHistoricalXSOARIncidents/SecuronixCloseHistoricalXSOARIncidents.yml
  Packs/Securonix/Scripts/SecuronixCloseHistoricalXSOARIncidents/SecuronixCloseHistoricalXSOARIncidents_test.py
  Packs/Securonix/Scripts/SecuronixCloseHistoricalXSOARIncidents/test_data/incident_activity_history_get_response.json
  Packs/Securonix/Scripts/SecuronixCloseHistoricalXSOARIncidents/test_data/mock_incident_contents.json
  Packs/Securonix/Scripts/SecuronixCloseHistoricalXSOARIncidents/test_data/mock_incidents.json
  Packs/Securonix/Scripts/SecuronixGetViolations/SecuronixGetViolations.yml
  Packs/Securonix/Scripts/SecuronixGetViolations/SecuronixGetViolations_test.py
  Packs/Securonix/Scripts/SecuronixGetViolations/test_data/get_violations_response.json
  Packs/Securonix/Scripts/SecuronixGetViolations/test_data/get_violations_response_hr.md
  Packs/Securonix/Scripts/UpdateSecuronixIncidentStatus/UpdateSecuronixIncidentStatus.yml
  Packs/Securonix/Scripts/UpdateSecuronixIncidentStatus/UpdateSecuronixIncidentStatus_test.py
  Packs/Securonix/pack_metadata.json
Labels: Contribution, docs-approved, Partner, ready-for-instance-test, Contribution Form Filled

#26283 Changed AutoFocus Tags Feed to not be configured by default
  Packs/AutoFocus/Integrations/AutoFocusTagsFeed/AutoFocusTagsFeed.yml
  Packs/AutoFocus/ReleaseNotes/2_1_8.md
  Packs/AutoFocus/pack_metadata.json
Labels: docs-approved

#26261 LogRhythm: correct the drilldown data endpoint & the headers
  Packs/LogRhythmRest/Integrations/LogRhythmRestV2/LogRhythmRestV2.py
  Packs/LogRhythmRest/Integrations/LogRhythmRestV2/LogRhythmRestV2.yml
  Packs/LogRhythmRest/ReleaseNotes/2_0_18.md
  Packs/LogRhythmRest/TestPlaybooks/playbook-LogRhythmRestV2-test.yml
  Packs/LogRhythmRest/pack_metadata.json
Labels: docs-approved

#26246 [RecordedFuture, RunZero, SafeNetTrustedAccess, SentinelOne] Fix LastRun setting in event collector
  Packs/RecordedFuture/Integrations/RecordedFutureEventCollector/RecordedFutureEventCollector.py
  Packs/RecordedFuture/Integrations/RecordedFutureEventCollector/RecordedFutureEventCollector.yml
  Packs/RecordedFuture/Integrations/RecordedFutureEventCollector/RecordedFutureEventCollector_test.py
  Packs/RecordedFuture/ReleaseNotes/1_5_2.md
  Packs/RecordedFuture/pack_metadata.json
  Packs/RunZero/Integrations/RunZeroEventCollector/RunZeroEventCollector.py
  Packs/RunZero/Integrations/RunZeroEventCollector/RunZeroEventCollector.yml
  Packs/RunZero/ReleaseNotes/1_0_6.md
  Packs/RunZero/pack_metadata.json
  Packs/SafeNet_Trusted_Access/Integrations/SafeNetTrustedAccessEventCollector/SafeNetTrustedAccessEventCollector.py
  Packs/SafeNet_Trusted_Access/Integrations/SafeNetTrustedAccessEventCollector/SafeNetTrustedAccessEventCollector.yml
  Packs/SafeNet_Trusted_Access/ReleaseNotes/2_0_12.md
  Packs/SafeNet_Trusted_Access/pack_metadata.json
  Packs/SentinelOne/Integrations/SentinelOneEventCollector/SentinelOneEventCollector.py
  Packs/SentinelOne/Integrations/SentinelOneEventCollector/SentinelOneEventCollector.yml
  Packs/SentinelOne/ReleaseNotes/3_1_3.md
  Packs/SentinelOne/pack_metadata.json
Labels: docs-approved, ForceMerge

#26302 fix unit tests run-doc-review
  Utils/github_workflow_scripts/github_workflow_scripts_tests/run_docs_review_test.py
  Utils/github_workflow_scripts/run_docs_review.py
  Utils/github_workflow_scripts/utils.py
Labels: docs-approved, ForceMerge

#26310 CrowdStrike Falcon - Add User-Agent header
  Packs/CrowdStrikeFalcon/Integrations/CrowdStrikeFalcon/CrowdStrikeFalcon.py
  Packs/CrowdStrikeFalcon/Integrations/CrowdStrikeFalcon/CrowdStrikeFalcon.yml
  Packs/CrowdStrikeFalcon/ReleaseNotes/1_10_17.md
  Packs/CrowdStrikeFalcon/pack_metadata.json
Labels: docs-approved

#26262 update graph with -g
  .gitlab/ci/on-push.yml
Labels: docs-approved

#26325 Ciac 6453/improve generic polling
  Packs/CommonScripts/ReleaseNotes/1_11_66.md
  Packs/CommonScripts/Scripts/GenericPollingScheduledTask/GenericPollingScheduledTask.js
  Packs/CommonScripts/Scripts/GenericPollingScheduledTask/GenericPollingScheduledTask.yml
  Packs/CommonScripts/Scripts/ScheduleGenericPolling/ScheduleGenericPolling.py
  Packs/CommonScripts/Scripts/ScheduleGenericPolling/ScheduleGenericPolling.yml
  Packs/CommonScripts/pack_metadata.json
Labels: docs-approved, ForceMerge

#26133 User investigation fix
  Packs/CommonPlaybooks/.pack-ignore
  Packs/CommonPlaybooks/Playbooks/playbook-User_Investigation_-_Generic.yml
  Packs/CommonPlaybooks/Playbooks/playbook-User_Investigation_-_Generic_README.md
  Packs/CommonPlaybooks/ReleaseNotes/2_3_63.md
  Packs/CommonPlaybooks/doc_files/User_Investigation_-_Generic.png
  Packs/CommonPlaybooks/pack_metadata.json
Labels: docs-approved

#26318 FreeFeeds - Added all "Allow list" feeds to the pack and relevant tags.
  Packs/CiscoWebExFeed/pack_metadata.json
  Packs/FeedAWS/pack_metadata.json
  Packs/FeedAzure/pack_metadata.json
  Packs/FeedAzureADConnectHealth/pack_metadata.json
  Packs/FeedCloudflare/pack_metadata.json
  Packs/FeedFastly/pack_metadata.json
  Packs/FeedGCPWhitelist/pack_metadata.json
  Packs/FeedMicrosoftIntune/pack_metadata.json
  Packs/FeedOffice365/pack_metadata.json
  Packs/FeedPublicDNS/pack_metadata.json
  Packs/FeedZoom/pack_metadata.json
  Packs/FreeFeeds/pack_metadata.json
  Tests/Marketplace/approved_tags.json
Labels: docs-approved

#26322 added log line to job-done
  .gitlab/helper_functions.sh
Labels: docs-approved

#26301 [ASM] EXPANDR-3582 - Prisma cloud changes and Emails from Tags changes.
  Packs/CortexAttackSurfaceManagement/Playbooks/Cortex_ASM_-_AWS_Enrichment.yml
  Packs/CortexAttackSurfaceManagement/Playbooks/Cortex_ASM_-_Enrichment.yml
  Packs/CortexAttackSurfaceManagement/Playbooks/Cortex_ASM_-_Enrichment_README.md
  Packs/CortexAttackSurfaceManagement/Playbooks/Cortex_ASM_-_Prisma_Cloud_Enrichment.yml
  Packs/CortexAttackSurfaceManagement/Playbooks/Cortex_ASM_-_Prisma_Cloud_Enrichment_README.md
  Packs/CortexAttackSurfaceManagement/README.md
  Packs/CortexAttackSurfaceManagement/ReleaseNotes/1_6_11.md
  Packs/CortexAttackSurfaceManagement/doc_files/Cortex_ASM_-_AWS_Enrichment.png
  Packs/CortexAttackSurfaceManagement/doc_files/Cortex_ASM_-_Enrichment.png
  Packs/CortexAttackSurfaceManagement/doc_files/Cortex_ASM_-_Prisma_Cloud_Enrichment.png
  Packs/CortexAttackSurfaceManagement/pack_metadata.json
  Packs/PrismaCloud/pack_metadata.json
  Tests/Marketplace/core_packs_xpanse_list.json
Labels: Contribution, docs-approved, ready-for-instance-test, Contribution Form Filled, Community

#26213 Forcepoint dlp
  Packs/ForcepointDLP/.pack-ignore
  Packs/ForcepointDLP/.secrets-ignore
  Packs/ForcepointDLP/ModelingRules/ForcepointDLP_1_4/ForcepointDLP_1_4.xif
  Packs/ForcepointDLP/ModelingRules/ForcepointDLP_1_4/ForcepointDLP_1_4.yml
  Packs/ForcepointDLP/ModelingRules/ForcepointDLP_1_4/ForcepointDLP_1_4_schema.json
  Packs/ForcepointDLP/README.md
  Packs/ForcepointDLP/pack_metadata.json
Labels: docs-approved

#26354 MicrosoftGraphMailApiModule: ignore BA124
  Packs/ApiModules/.pack-ignore
Labels: docs-approved

#26348 fix unit test to use logger instead of capsys
  Utils/github_workflow_scripts/github_workflow_scripts_tests/run_docs_review_test.py
Labels: docs-approved, ForceMerge

#26320 [DeleteContent] - Fixed the issue in the script that prevented him from working
  Packs/ContentManagement/ReleaseNotes/1_2_7.md
  Packs/ContentManagement/Scripts/DeleteContent/DeleteContent.py
  Packs/ContentManagement/Scripts/DeleteContent/DeleteContent.yml
  Packs/ContentManagement/Scripts/DeleteContent/DeleteContent_test.py
  Packs/ContentManagement/pack_metadata.json
Labels: docs-approved

#26272 Fixes For 'Cortex XDR Malware - Incident Enrichment' Playbook
  Packs/CortexXDR/Playbooks/playbook-Cortex_XDR_Malware_-_Incident_Enrichment.yml
  Packs/CortexXDR/Playbooks/playbook-Cortex_XDR_Malware_-_Incident_Enrichment_README.md
  Packs/CortexXDR/ReleaseNotes/4_10_38.md
  Packs/CortexXDR/doc_files/Cortex_XDR_Malware_-_Incident_Enrichment.png
  Packs/CortexXDR/pack_metadata.json
Labels: docs-approved

#26351 Revert poetry.lock wrong changes
  poetry.lock
Labels: docs-approved

#26273 Skip non-relevant steps in test upload-flow build
  .gitlab/ci/bucket-upload.yml
Labels: docs-approved

#26356 set pythonpath to review release notes
  .github/workflows/review-release-notes.yml
Labels: docs-approved

#26352 Deprecate Mandiant feed
  Packs/FeedMandiant/Integrations/FeedMandiant/FeedMandiant.yml
  Packs/FeedMandiant/ReleaseNotes/1_0_13.md
  Packs/FeedMandiant/pack_metadata.json
Labels: docs-approved

#26337 Detonate URL - CrowdStrike Falcon PB changed to quiet mode
  Packs/CrowdStrikeFalconX/Playbooks/Detonate_URL_-_CrowdStrike_Falcon_X.yml
  Packs/CrowdStrikeFalconX/ReleaseNotes/1_2_27.md
  Packs/CrowdStrikeFalconX/pack_metadata.json
Labels: docs-approved

#26361 PreproccessEmail: correct the if condition
  Packs/EmailCommunication/ReleaseNotes/2_0_7.md
  Packs/EmailCommunication/Scripts/PreprocessEmail/PreprocessEmail.py
  Packs/EmailCommunication/Scripts/PreprocessEmail/PreprocessEmail.yml
  Packs/EmailCommunication/Scripts/PreprocessEmail/PreprocessEmail_test.py
  Packs/EmailCommunication/pack_metadata.json
Labels: docs-approved

#25633 Cisco asa patterns
  Packs/CiscoASA/ModelingRules/CiscoASA_1_4/CiscoASA_1_4.xif
  Packs/CiscoASA/README.md
  Packs/CiscoASA/ReleaseNotes/1_0_36.md
  Packs/CiscoASA/pack_metadata.json
Labels: docs-approved

#26362 Updated the update_core_packs_list
  Tests/Marketplace/core_packs_list.json
Labels: docs-approved

#26317 Search incidents v2 limit bug
  Packs/CommonScripts/ReleaseNotes/1_11_67.md
  Packs/CommonScripts/Scripts/SearchIncidentsV2/SearchIncidentsV2.py
  Packs/CommonScripts/Scripts/SearchIncidentsV2/SearchIncidentsV2.yml
  Packs/CommonScripts/Scripts/SearchIncidentsV2/SearchIncidentsV2_test.py
  Packs/CommonScripts/pack_metadata.json
Labels: docs-approved

#26265 [Slack, Tenableio, WithSecure, Zoom] Fix LastRun setting in event collector
  Packs/Slack/Integrations/SlackEventCollector/SlackEventCollector.py
  Packs/Slack/Integrations/SlackEventCollector/SlackEventCollector.yml
  Packs/Slack/ReleaseNotes/3_1_34.md
  Packs/Slack/pack_metadata.json
  Packs/Tenable_io/Integrations/TenableioEventCollector/TenableioEventCollector.py
  Packs/Tenable_io/Integrations/TenableioEventCollector/TenableioEventCollector.yml
  Packs/Tenable_io/Integrations/TenableioEventCollector/TenableioEventCollector_test.py
  Packs/Tenable_io/ReleaseNotes/2_1_5.md
  Packs/Tenable_io/pack_metadata.json
  Packs/WithSecure/Integrations/WithSecureEventCollector/WithSecureEventCollector.py
  Packs/WithSecure/Integrations/WithSecureEventCollector/WithSecureEventCollector.yml
  Packs/WithSecure/Integrations/WithSecureEventCollector/WithSecureEventCollector_test.py
  Packs/WithSecure/ReleaseNotes/1_0_1.md
  Packs/WithSecure/pack_metadata.json
  Packs/Zoom/Integrations/ZoomEventCollector/ZoomEventCollector.py
  Packs/Zoom/Integrations/ZoomEventCollector/ZoomEventCollector.yml
  Packs/Zoom/ReleaseNotes/1_4_1.md
  Packs/Zoom/pack_metadata.json
Labels: docs-approved

#26367 1.14.1 release
  poetry.lock
  pyproject.toml
Labels: docs-approved

#26343 Remove citation from description.
  Packs/FeedMitreAttackv2/Integrations/FeedMitreAttackv2/FeedMitreAttackv2.py
  Packs/FeedMitreAttackv2/Integrations/FeedMitreAttackv2/FeedMitreAttackv2.yml
  Packs/FeedMitreAttackv2/Integrations/FeedMitreAttackv2/FeedMitreAttackv2_test.py
  Packs/FeedMitreAttackv2/Integrations/FeedMitreAttackv2/test_data/mitre_test_data.py
  Packs/FeedMitreAttackv2/ReleaseNotes/1_1_11.md
  Packs/FeedMitreAttackv2/pack_metadata.json
Labels: docs-approved

#26350 [SetMultipleValues] Added support for arrays
  Packs/CommonScripts/ReleaseNotes/1_11_68.md
  Packs/CommonScripts/Scripts/SetMultipleValues/SetMultipleValues.py
  Packs/CommonScripts/Scripts/SetMultipleValues/SetMultipleValues.yml
  Packs/CommonScripts/Scripts/SetMultipleValues/SetMultipleValues_test.py
  Packs/CommonScripts/pack_metadata.json
Labels: docs-approved

#26269 Cybersixgill darkfeed confidence filter
  Packs/Sixgill-Darkfeed/Integrations/Sixgill_Darkfeed/README.md
  Packs/Sixgill-Darkfeed/Integrations/Sixgill_Darkfeed/Sixgill_Darkfeed.py
  Packs/Sixgill-Darkfeed/Integrations/Sixgill_Darkfeed/Sixgill_Darkfeed.yml
  Packs/Sixgill-Darkfeed/Integrations/Sixgill_Darkfeed/Sixgill_Darkfeed_description.md
  Packs/Sixgill-Darkfeed/Integrations/Sixgill_Darkfeed/Sixgill_Darkfeed_test.py
  Packs/Sixgill-Darkfeed/ReleaseNotes/2_2_0.md
  Packs/Sixgill-Darkfeed/pack_metadata.json
Labels: Contribution, docs-approved, Partner, ready-for-instance-test, Contribution Form Filled

#26380 [SlackV3] Added support for war room mentions
  Packs/Slack/Integrations/SlackV3/SlackV3.yml
  Packs/Slack/ReleaseNotes/3_1_35.md
  Packs/Slack/pack_metadata.json
Labels: Contribution, docs-approved, ready-for-instance-test, Contribution Form Filled, Community

#26376 Fix TIM IP enrichment playbook - wrong value in task #134
  Packs/TIM_Processing/.pack-ignore
  Packs/TIM_Processing/Playbooks/playbook-TIM_-_Run_Enrichment_For_IP_Indicators_6_0_0.yml
  Packs/TIM_Processing/Playbooks/playbook-TIM_-_Run_Enrichment_For_IP_Indicators_6_0_0_README.md
  Packs/TIM_Processing/ReleaseNotes/1_1_17.md
  Packs/TIM_Processing/pack_metadata.json
Labels: docs-approved

#26124 RecordedFutureASI v2.0.0 (support Incident by Host)
  Packs/RecordedFutureASI/Classifiers/classifier-Recorded_Future_ASI_Incoming_Mapper.json
  Packs/RecordedFutureASI/IncidentFields/incidentfield-Recorded_Future_Attack_Surface_Intelligence_Affected_Hosts.json
  Packs/RecordedFutureASI/IncidentFields/incidentfield-Recorded_Future_Attack_Surface_Intelligence_Attack_Surface_Rule.json
  Packs/RecordedFutureASI/IncidentFields/incidentfield-Recorded_Future_Attack_Surface_Intelligence_Triggered_Rules.json
  Packs/RecordedFutureASI/IncidentTypes/incidenttype-RecordedFutureASIAlert.json
  Packs/RecordedFutureASI/Integrations/RecordedFutureASI/README.md
  Packs/RecordedFutureASI/Integrations/RecordedFutureASI/RecordedFutureASI.py
  Packs/RecordedFutureASI/Integrations/RecordedFutureASI/RecordedFutureASI.yml
  Packs/RecordedFutureASI/Integrations/RecordedFutureASI/RecordedFutureASI_description.md
  Packs/RecordedFutureASI/Integrations/RecordedFutureASI/RecordedFutureASI_test.py
  Packs/RecordedFutureASI/Integrations/RecordedFutureASI/command_examples
  Packs/RecordedFutureASI/Integrations/RecordedFutureASI/test_data/by-host-issues.json
  Packs/RecordedFutureASI/Integrations/RecordedFutureASI/test_data/current-issues.json
  Packs/RecordedFutureASI/Layouts/layoutscontainer-RecordedFutureASILayout.json
  Packs/RecordedFutureASI/ReleaseNotes/2_0_0.md
  Packs/RecordedFutureASI/pack_metadata.json
Labels: Contribution, Partner, ready-for-instance-test, post-demo, Contribution Form Filled, pending-contributor

#26385 Revert gp fix
  Packs/CommonScripts/ReleaseNotes/1_11_70.md
  Packs/CommonScripts/Scripts/GenericPollingScheduledTask/GenericPollingScheduledTask.js
  Packs/CommonScripts/Scripts/ScheduleGenericPolling/ScheduleGenericPolling.py
  Packs/CommonScripts/pack_metadata.json
Labels: docs-approved, ForceMerge

#26393 Fixing url in 'core-get-script-execution-result-files' XSIAM command
  Packs/ApiModules/Scripts/CoreIRApiModule/CoreIRApiModule.py
  Packs/ApiModules/Scripts/CoreIRApiModule/CoreIRApiModule_test.py
  Packs/Core/ReleaseNotes/1_3_50.md
  Packs/Core/pack_metadata.json
  Packs/CortexXDR/ReleaseNotes/4_10_39.md
  Packs/CortexXDR/pack_metadata.json
Labels: docs-approved

#26384 1.14.3 release
  .hooks/pre-commit
  poetry.lock
  pyproject.toml
Labels: docs-approved

#26395 [splunk] fix for proxy parameter wasn't parsed correctly
  Packs/SplunkPy/Integrations/SplunkPy/SplunkPy.py
  Packs/SplunkPy/Integrations/SplunkPy/SplunkPy.yml
  Packs/SplunkPy/ReleaseNotes/3_0_17.md
  Packs/SplunkPy/pack_metadata.json
Labels: docs-approved

#26396 Run pre-commit hook with poetry env
  .hooks/bootstrap
  .hooks/pre-commit
Labels: docs-approved

#26359 Hide manidant feed
  Packs/FeedMandiant/pack_metadata.json
Labels: docs-approved

#25561 New commands for Orca Integration
  Packs/Orca/.secrets-ignore
  Packs/Orca/Integrations/Orca/Orca.py
  Packs/Orca/Integrations/Orca/Orca.yml
  Packs/Orca/Integrations/Orca/Orca_test.py
  Packs/Orca/Integrations/Orca/README.md
  Packs/Orca/Integrations/OrcaEventCollector/OrcaEventCollector.yml
  Packs/Orca/ReleaseNotes/2_2_0.md
  Packs/Orca/pack_metadata.json
Labels: Contribution, Partner, ready-for-instance-test, pending-demo, Contribution Form Filled, pending-contributor

#26386 DBotFindSimilarIncidentsByIndicators - fix fromDate filter
  Packs/Base/ReleaseNotes/1_31_95.md
  Packs/Base/Scripts/DBotFindSimilarIncidentsByIndicators/DBotFindSimilarIncidentsByIndicators.py
  Packs/Base/Scripts/DBotFindSimilarIncidentsByIndicators/DBotFindSimilarIncidentsByIndicators.yml
  Packs/Base/pack_metadata.json
Labels: docs-approved

#26284 Default Pack - small playbook fix and readme update
  Packs/DefaultPlaybook/Playbooks/Default_8_2.yml
  Packs/DefaultPlaybook/README.md
  Packs/DefaultPlaybook/ReleaseNotes/2_0_2.md
  Packs/DefaultPlaybook/pack_metadata.json
  Tests/conf.json
Labels: docs-approved

#26370 Test Playbook for - Cortex XDR - Retrieve File by sha256
  Packs/CortexXDR/Playbooks/playbook-Cortex_XDR_-_Retrieve_File_by_sha256.yml
  Packs/CortexXDR/ReleaseNotes/4_10_40.md
  Packs/CortexXDR/TestPlaybooks/Test_Playbook_-_Cortex_XDR_-_Retrieve_File_by_sha256.yml
  Packs/CortexXDR/pack_metadata.json
  Tests/conf.json
Labels: docs-approved

#26130 Email Integrations Enhancement - Categories
  Packs/ApiModules/Scripts/MicrosoftGraphMailApiModule/MicrosoftGraphMailApiModule.py
  Packs/MicrosoftGraphMail/Classifiers/classifier-Microsoft_Graph_Mail_Mapper.json
  Packs/MicrosoftGraphMail/Classifiers/classifier-mapper-incomming-MicrosoftGraphListener.json
  Packs/MicrosoftGraphMail/Integrations/MicrosoftGraphListener/test_data/emails_data
  Packs/MicrosoftGraphMail/Integrations/MicrosoftGraphListener/test_data/expected_incident
  Packs/MicrosoftGraphMail/Integrations/MicrosoftGraphMail/test_data/emails_data_full_body_html
  Packs/MicrosoftGraphMail/Integrations/MicrosoftGraphMail/test_data/emails_data_full_body_text
  Packs/MicrosoftGraphMail/Integrations/MicrosoftGraphMail/test_data/emails_data_html
  Packs/MicrosoftGraphMail/Integrations/MicrosoftGraphMail/test_data/emails_data_html_without_body
  Packs/MicrosoftGraphMail/Integrations/MicrosoftGraphMail/test_data/emails_data_text
  Packs/MicrosoftGraphMail/Integrations/MicrosoftGraphMail/test_data/emails_data_text_without_body
  Packs/MicrosoftGraphMail/Integrations/MicrosoftGraphMail/test_data/expected_incident
  Packs/MicrosoftGraphMail/Integrations/MicrosoftGraphMail/test_data/expected_incident_full_body
  Packs/MicrosoftGraphMail/Integrations/MicrosoftGraphMail/test_data/mail
  Packs/MicrosoftGraphMail/Integrations/MicrosoftGraphMail/test_data/mails
  Packs/MicrosoftGraphMail/ReleaseNotes/1_5_1.md
  Packs/MicrosoftGraphMail/pack_metadata.json
  Packs/Phishing/Layouts/layoutscontainer-Phishing_v_3.json
  Packs/Phishing/ReleaseNotes/3_5_15.md
  Packs/Phishing/pack_metadata.json
Labels: docs-approved

#26137 fix archer get record unexpected response format
  Packs/ArcherRSA/Integrations/ArcherV2/ArcherV2.py
  Packs/ArcherRSA/Integrations/ArcherV2/ArcherV2.yml
  Packs/ArcherRSA/ReleaseNotes/1_2_10.md
  Packs/ArcherRSA/pack_metadata.json
Labels: docs-approved, release-notes-only

#26418 ruff check F821
  .hooks/pre-commit
  pyproject.toml
Labels: docs-approved

#26419 Fortinet Fortigate fix
  Packs/FortiGate/ParsingRules/FortiGate/FortiGate.xif
  Packs/FortiGate/README.md
  Packs/FortiGate/ReleaseNotes/1_0_20.md
  Packs/FortiGate/pack_metadata.json
Labels: docs-approved, ForceMerge

#26366 WildFire v2 - improved the error message
  Packs/Palo_Alto_Networks_WildFire/Integrations/Palo_Alto_Networks_WildFire_v2/Palo_Alto_Networks_WildFire_v2.py
  Packs/Palo_Alto_Networks_WildFire/Integrations/Palo_Alto_Networks_WildFire_v2/Palo_Alto_Networks_WildFire_v2.yml
  Packs/Palo_Alto_Networks_WildFire/Integrations/Palo_Alto_Networks_WildFire_v2/Palo_Alto_Networks_WildFire_v2_test.py
  Packs/Palo_Alto_Networks_WildFire/ReleaseNotes/2_1_22.md
  Packs/Palo_Alto_Networks_WildFire/pack_metadata.json
Labels: docs-approved

#26026 Refactor/CIAC 832/Process Indicators as SCOs
  Packs/CommonScripts/.secrets-ignore
  Packs/CommonScripts/ReleaseNotes/1_11_72.md
  Packs/CommonScripts/Scripts/StixCreator/StixCreator.py
  Packs/CommonScripts/Scripts/StixCreator/StixCreator.yml
  Packs/CommonScripts/Scripts/StixCreator/StixCreator_test.py
  Packs/CommonScripts/TestPlaybooks/playbook-TestStixCreator.yml
  Packs/CommonScripts/pack_metadata.json
Labels: docs-approved

#26416 update the native:candiadte to latest native:dev
  Tests/docker_native_image_config.json
Labels: docs-approved

#26230 Modeling rules for Taniumm Threat Response.
  Packs/TaniumThreatResponse/.secrets-ignore
  Packs/TaniumThreatResponse/ModelingRules/TaniumThreatResponse/TaniumThreatResponse.xif
  Packs/TaniumThreatResponse/ModelingRules/TaniumThreatResponse/TaniumThreatResponse.yml
  Packs/TaniumThreatResponse/ModelingRules/TaniumThreatResponse/TaniumThreatResponse_schema.json
  Packs/TaniumThreatResponse/ParsingRules/TaniumThreatResponse/TaniumThreatResponse.xif
  Packs/TaniumThreatResponse/ParsingRules/TaniumThreatResponse/TaniumThreatResponse.yml
  Packs/TaniumThreatResponse/README.md
  Packs/TaniumThreatResponse/ReleaseNotes/2_1_14.md
  Packs/TaniumThreatResponse/pack_metadata.json
Labels: docs-approved

#25702 Code42 new playbooks
  Packs/Code42/Integrations/Code42/Code42.py
  Packs/Code42/Integrations/Code42/Code42.yml
  Packs/Code42/Integrations/Code42/Code42_test.py
  Packs/Code42/Integrations/Code42/README.md
  Packs/Code42/Layouts/layoutscontainer-Code42_Security_Alert.json
  Packs/Code42/Playbooks/playbook-Code42_Add_Employees_To_Departing_Employee_Watchlist.yml
  Packs/Code42/Playbooks/playbook-Code42_Add_Employees_To_Departing_Employee_Watchlist_README.md
  Packs/Code42/Playbooks/playbook-Code42_Add_Employees_To_New_Hire_Watchlist.yml
  Packs/Code42/Playbooks/playbook-Code42_Add_Employees_To_New_Hire_Watchlist_README.md
  Packs/Code42/Playbooks/playbook-Code42_Check_Incydr_Status_And_Close_XSOAR_Incident.yml
  Packs/Code42/Playbooks/playbook-Code42_Check_Incydr_Status_And_Close_XSOAR_Incident_README.md
  Packs/Code42/Playbooks/playbook-Code42_Close_Related_XSOAR_And_Incydr_Incidents.yml
  Packs/Code42/Playbooks/playbook-Code42_Close_Related_XSOAR_And_Incydr_Incidents_README.md
  Packs/Code42/Playbooks/playbook-Code42_Departing_Employee_Auto-Add.yml
  Packs/Code42/Playbooks/playbook-Code42_Departing_Employee_Auto-Add_README.md
  Packs/Code42/Playbooks/playbook-Code42_Departing_Employee_Clean-Up.yml
  Packs/Code42/Playbooks/playbook-Code42_Departing_Employee_Clean-Up_README.md
  Packs/Code42/Playbooks/playbook-Code42_Exfiltration_Playbook_README.md
  Packs/Code42/Playbooks/playbook-Code42_File_Download_README.md
  Packs/Code42/Playbooks/playbook-Code42_File_Search_README.md
  Packs/Code42/Playbooks/playbook-Code42_Get_Code42_Employee_Information.yml
  Packs/Code42/Playbooks/playbook-Code42_Get_Code42_Employee_Information_README.md
  Packs/Code42/Playbooks/playbook-Code42_New_Hire_Auto-Add.yml
  Packs/Code42/Playbooks/playbook-Code42_New_Hire_Auto-Add_README.md
  Packs/Code42/Playbooks/playbook-Code42_New_Hire_Clean-Up.yml
  Packs/Code42/Playbooks/playbook-Code42_New_Hire_Clean-Up_README.md
  Packs/Code42/Playbooks/playbook-Code42_Remove_Employees_From_Departing_Employee_Watchlist.yml
  Packs/Code42/Playbooks/playbook-Code42_Remove_Employees_From_Departing_Employee_Watchlist_README.md
  Packs/Code42/Playbooks/playbook-Code42_Remove_Employees_From_New_Hire_Watchlist.yml
  Packs/Code42/Playbooks/playbook-Code42_Remove_Employees_From_New_Hire_Watchlist_README.md
  Packs/Code42/Playbooks/playbook-Code42_Security_Alert.yml
  Packs/Code42/Playbooks/playbook-Code42_Security_Alert_README.md
  Packs/Code42/ReleaseNotes/3_1_6.md
  Packs/Code42/ReleaseNotes/3_1_8.md
  Packs/Code42/Scripts/Code42FileEventsToMarkdownTable/Code42FileEventsToMarkdownTable.yml
  Packs/Code42/Scripts/Code42FileEventsToMarkdownTable/Code42FileEventsToMarkdownTable_test.py
  Packs/Code42/doc_files/Add_Employees_to_Departing_Employee_Watchlist.png
  Packs/Code42/doc_files/Add_Employees_to_New_Hire_Watchlist.png
  Packs/Code42/doc_files/Check_Incydr_Status_and_Close_XSOAR_Incident.png
  Packs/Code42/doc_files/Close_Related_XSOAR_and_Incydr_Incidents.png
  Packs/Code42/doc_files/Code42_Exfiltration_Playbook.png
  Packs/Code42/doc_files/Code42_Security_Alert.png
  Packs/Code42/doc_files/Departing_Employee_Auto-Add.png
  Packs/Code42/doc_files/Departing_Employee_Clean-Up.png
  Packs/Code42/doc_files/Get_Code42_Employee_Information.png
  Packs/Code42/doc_files/New_Hire_Auto-Add.png
  Packs/Code42/doc_files/New_Hire_Clean-Up.png
  Packs/Code42/doc_files/Remove_Employees_from_Departing_Employee_Watchlist.png
  Packs/Code42/doc_files/Remove_Employees_from_New_Hire_Watchlist.png
  Packs/Code42/pack_metadata.json
Labels: Contribution, Partner, ready-for-instance-test, Contribution Form Filled

#26278 CTIX v3 - Minor fixes.
  Packs/CTIX/Integrations/CTIXv3/CTIXv3.py
  Packs/CTIX/Integrations/CTIXv3/CTIXv3.yml
  Packs/CTIX/ReleaseNotes/2_2_8.md
  Packs/CTIX/pack_metadata.json
Labels: Contribution, Partner, ready-for-instance-test, Contribution Form Filled

#26075 Update to threatvaultV2 adding 2 commands
  Packs/PaloAltoNetworks_Threat_Vault/.secrets-ignore
  Packs/PaloAltoNetworks_Threat_Vault/Integrations/ThreatVaultv2/CONTRIBUTORS.json
  Packs/PaloAltoNetworks_Threat_Vault/Integrations/ThreatVaultv2/README.md
  Packs/PaloAltoNetworks_Threat_Vault/Integrations/ThreatVaultv2/ThreatVaultv2.py
  Packs/PaloAltoNetworks_Threat_Vault/Integrations/ThreatVaultv2/ThreatVaultv2.yml
  Packs/PaloAltoNetworks_Threat_Vault/ReleaseNotes/2_0_6.md
  Packs/PaloAltoNetworks_Threat_Vault/Scripts/SetThreatVaultIncidentMarkdownRepresentation/SetThreatVaultIncidentMarkdownRepresentation.yml
  Packs/PaloAltoNetworks_Threat_Vault/pack_metadata.json
Labels: Contribution, ready-for-instance-test, pending-demo, Contribution Form Filled, Community, pending-contributor

#26424 add demisto-sdk logs to gitlab
  .gitlab/ci/.gitlab-ci.yml
Labels: docs-approved

#26411 apache_web_server_testdata
  Packs/ApacheWebServer/ModelingRules/ApacheWebServerModelingRules_1_3/ApacheWebServerModelingRules_1_3.xif
  Packs/ApacheWebServer/ReleaseNotes/1_0_7.md
  Packs/ApacheWebServer/pack_metadata.json
Labels: docs-approved

#26334 [ASM] - Expander - Update Cortex ASM - Service Ownership playbook
  Packs/CortexAttackSurfaceManagement/Playbooks/Cortex_ASM_-_GCP_Enrichment.yml
  Packs/CortexAttackSurfaceManagement/Playbooks/Cortex_ASM_-_Service_Ownership.yml
  Packs/CortexAttackSurfaceManagement/Playbooks/Cortex_ASM_-_Service_Ownership_README.md
  Packs/CortexAttackSurfaceManagement/ReleaseNotes/1_6_11.md
  Packs/CortexAttackSurfaceManagement/doc_files/Cortex_ASM_-_GCP_Enrichment.png
  Packs/CortexAttackSurfaceManagement/doc_files/Cortex_ASM_-_Service_Ownership.png
  Packs/CortexAttackSurfaceManagement/pack_metadata.json
Labels: Contribution, ready-for-instance-test, Contribution Form Filled, Community

#26439 Fail if modeling rules command fails
  Tests/scripts/test_modeling_rules.sh
Labels: docs-approved

#26321 Use version 2.0.0 of argus-toolbelt docker image
  Packs/mnemonicMDR/Integrations/ArgusManagedDefence/ArgusManagedDefence.yml
  Packs/mnemonicMDR/ReleaseNotes/1_1_10.md
  Packs/mnemonicMDR/pack_metadata.json
Labels: Contribution, Partner, ready-for-instance-test, Contribution Form Filled

#26372 Ciac 6453/improve generic polling - hotfix
  Packs/CommonScripts/ReleaseNotes/1_11_73.md
  Packs/CommonScripts/Scripts/GenericPollingScheduledTask/GenericPollingScheduledTask.js
  Packs/CommonScripts/Scripts/GenericPollingScheduledTask/GenericPollingScheduledTask.yml
  Packs/CommonScripts/Scripts/GenericPollingScheduledTask/README.md
  Packs/CommonScripts/Scripts/ScheduleCommand/README.md
  Packs/CommonScripts/Scripts/ScheduleCommand/ScheduleCommand.yml
  Packs/CommonScripts/Scripts/ScheduleGenericPolling/ScheduleGenericPolling.py
  Packs/CommonScripts/Scripts/ScheduleGenericPolling/ScheduleGenericPolling.yml
  Packs/CommonScripts/pack_metadata.json
Labels: docs-approved, ForceMerge

#25840 Wallix
  Packs/WALLIXBastion/.pack-ignore
  Packs/WALLIXBastion/.secrets-ignore
  Packs/WALLIXBastion/Author_image.png
  Packs/WALLIXBastion/Integrations/WAB/README.md
  Packs/WALLIXBastion/Integrations/WAB/WAB.py
  Packs/WALLIXBastion/Integrations/WAB/WAB.yml
  Packs/WALLIXBastion/Integrations/WAB/WAB_description.md
  Packs/WALLIXBastion/Integrations/WAB/WAB_image.png
  Packs/WALLIXBastion/Integrations/WAB/WAB_test.py
  Packs/WALLIXBastion/README.md
  Packs/WALLIXBastion/TestPlaybooks/WAB_test.yml
  Packs/WALLIXBastion/pack_metadata.json
Labels: Contribution, docs-approved, ready-for-instance-test, post-demo, Contribution Form Filled, Community, pending-contributor

#26457 changed reviewers
  Utils/github_workflow_scripts/handle_external_pr.py
Labels: docs-approved

#26428 Phishing enhance
  Packs/Phishing/Playbooks/Phishing_-_Generic_v3_6_5.yml
  Packs/Phishing/Playbooks/Phishing_-_Generic_v3_6_5_README.md
  Packs/Phishing/Playbooks/Process_Email_-_Generic_v2.yml
  Packs/Phishing/ReleaseNotes/3_5_16.md
  Packs/Phishing/doc_files/Phishing_-_Generic_v3_6_5.png
  Packs/Phishing/pack_metadata.json
Labels: docs-approved

#26342 Reco add new type of alerts
  Packs/Reco/.secrets-ignore
  Packs/Reco/Integrations/Reco/README.md
  Packs/Reco/Integrations/Reco/Reco.py
  Packs/Reco/Integrations/Reco/Reco.yml
  Packs/Reco/Integrations/Reco/Reco_test.py
  Packs/Reco/ReleaseNotes/1_1_0.md
  Packs/Reco/pack_metadata.json
Labels: Contribution, Partner, ready-for-instance-test, post-demo, Contribution Form Filled

#26413 added sort field and direction to event-search and alert-search
  Packs/PrismaCloud/Integrations/PrismaCloudV2/PrismaCloudV2.py
  Packs/PrismaCloud/Integrations/PrismaCloudV2/PrismaCloudV2.yml
  Packs/PrismaCloud/Integrations/PrismaCloudV2/README.md
  Packs/PrismaCloud/ReleaseNotes/4_1_0.md
  Packs/PrismaCloud/pack_metadata.json
Labels: docs-approved, ForceMerge

#26226 Yr xsup 22806 pan os fetching issues (multiple devices)
  Packs/PAN-OS/Integrations/Panorama/Panorama.py
  Packs/PAN-OS/Integrations/Panorama/Panorama.yml
  Packs/PAN-OS/Integrations/Panorama/Panorama_test.py
  Packs/PAN-OS/Integrations/Panorama/README.md
  Packs/PAN-OS/Integrations/Panorama/test_data/fetch_incidents_input.py
  Packs/PAN-OS/ReleaseNotes/1_17_0.json
  Packs/PAN-OS/ReleaseNotes/1_17_0.md
  Packs/PAN-OS/pack_metadata.json
Labels: docs-approved

#26410 dontcheckhostname verify false
  Packs/Base/ReleaseNotes/1_32_0.md
  Packs/Base/Scripts/CommonServerPython/CommonServerPython.py
  Packs/Base/pack_metadata.json
Labels: docs-approved, ForceMerge

#26338 Corelight Zeek / Prisma Cloud Modeling Rule fix4
  Packs/CorelightZeek/ModelingRules/CorelightZeek/CorelightZeek.xif
  Packs/CorelightZeek/ModelingRules/CorelightZeek/CorelightZeek_schema.json
  Packs/CorelightZeek/ReleaseNotes/1_0_5.md
  Packs/CorelightZeek/pack_metadata.json
  Packs/MicrosoftGraphSecurity/ModelingRules/MicrosoftGraphSecurity/MicrosoftGraphSecurity.xif
  Packs/MicrosoftGraphSecurity/ReleaseNotes/2_1_20.md
  Packs/MicrosoftGraphSecurity/pack_metadata.json
  Packs/PrismaCloud/ModelingRules/PrismaCloud/PrismaCloud.xif
  Packs/PrismaCloud/ModelingRules/PrismaCloud/PrismaCloud_schema.json
  Packs/PrismaCloud/ReleaseNotes/4_1_1.md
  Packs/PrismaCloud/pack_metadata.json
Labels: docs-approved, ForceMerge

#26465 Url encode - enable the script
  Packs/FiltersAndTransformers/ReleaseNotes/1_2_17.md
  Packs/FiltersAndTransformers/Scripts/URLEncode/README.md
  Packs/FiltersAndTransformers/Scripts/URLEncode/URLEncode.yml
  Packs/FiltersAndTransformers/pack_metadata.json
Labels: docs-approved, release-notes-only

#26392 Wildfile url param clarify desc
  Packs/Palo_Alto_Networks_WildFire/Integrations/Palo_Alto_Networks_WildFire_v2/Palo_Alto_Networks_WildFire_v2.yml
  Packs/Palo_Alto_Networks_WildFire/ReleaseNotes/2_1_23.md
  Packs/Palo_Alto_Networks_WildFire/pack_metadata.json
Labels: docs-approved

#26048 Creating Test Playbooks Checking Empty Inputs
  Packs/CommonPlaybooks/Playbooks/playbook-Retrieve_File_from_Endpoint_-_Generic_V3.yml
  Packs/CommonPlaybooks/ReleaseNotes/2_3_62.md
  Packs/CommonPlaybooks/ReleaseNotes/2_3_63.md
  Packs/CommonPlaybooks/ReleaseNotes/2_3_64.md
  Packs/CommonPlaybooks/TestPlaybooks/playbook-Account_Enrichment_-_Generic_v2.1_-_Test.yml
  Packs/CommonPlaybooks/TestPlaybooks/playbook-Block_IP_-_Generic_V3_Test.yml
  Packs/CommonPlaybooks/TestPlaybooks/playbook-Calculate_Severity_-_Generic_v2_-_Test.yml
  Packs/CommonPlaybooks/TestPlaybooks/playbook-Detonate_File_-_Generic_Test.yml
  Packs/CommonPlaybooks/TestPlaybooks/playbook-Detonate_URL_-_Generic_Test.yml
  Packs/CommonPlaybooks/TestPlaybooks/playbook-Domain_Enrichment_-_Generic_v2_-_Test.yml
  Packs/CommonPlaybooks/TestPlaybooks/playbook-Endpoint_Enrichment_-_Generic_v2.1_-_Test.yml
  Packs/CommonPlaybooks/TestPlaybooks/playbook-Endpoint_Enrichment_-_Generic_v2.1_6_8-_Test.yml
  Packs/CommonPlaybooks/TestPlaybooks/playbook-Extract_Indicators_From_File_-_Generic_v2_-_Test_4_5.yml
  Packs/CommonPlaybooks/TestPlaybooks/playbook-File_Enrichment_-_Generic_v2_-_Test.yml
  Packs/CommonPlaybooks/TestPlaybooks/playbook-Get_endpoint_details_-_Generic_-_test.yml
  Packs/CommonPlaybooks/TestPlaybooks/playbook-IP_Enrichment_-_Generic_v2_-_Test.yml
  Packs/CommonPlaybooks/TestPlaybooks/playbook-Isolate_and_unisolate_endpoint_-_test.yml
  Packs/CommonPlaybooks/TestPlaybooks/playbook-Retrieve_File_from_Endpoint_-_Generic_V3_Test.yml
  Packs/CommonPlaybooks/TestPlaybooks/playbook-URL_Enrichment_-_Generic_v2_-_Test.yml
  Packs/CommonPlaybooks/pack_metadata.json
  Packs/Cybereason/Playbooks/playbook-Unisolate_Endpoint_-_Cybereason.yml
  Packs/Cybereason/ReleaseNotes/2_1_7.md
  Packs/Cybereason/pack_metadata.json
  Tests/conf.json
Labels: docs-approved, release-notes-only

#26438 add sane arg to support force using server formatted time strings
  Packs/Base/ReleaseNotes/1_32_1.md
  Packs/Base/Scripts/SanePdfReport/SanePdfReport.py
  Packs/Base/Scripts/SanePdfReport/SanePdfReport.yml
  Packs/Base/pack_metadata.json
Labels: docs-approved

#26480 MicrosoftGraphListener: remove the "from" arg in "send-mail" and "reply-mail"
  Packs/MicrosoftGraphMail/Integrations/MicrosoftGraphListener/MicrosoftGraphListener.yml
  Packs/MicrosoftGraphMail/Integrations/MicrosoftGraphListener/README.md
  Packs/MicrosoftGraphMail/ReleaseNotes/1_5_2.json
  Packs/MicrosoftGraphMail/ReleaseNotes/1_5_2.md
  Packs/MicrosoftGraphMail/pack_metadata.json
Labels: docs-approved

#26453 Trend Micro Deep Security Modeling Rules (#CIAC-3156)
  Packs/TrendMicroDeepSecurity/ModelingRules/TrendMicroDeepSecurity/TrendMicroDeepSecurity.xif
  Packs/TrendMicroDeepSecurity/ModelingRules/TrendMicroDeepSecurity/TrendMicroDeepSecurity.yml
  Packs/TrendMicroDeepSecurity/ModelingRules/TrendMicroDeepSecurity/TrendMicroDeepSecurity_schema.json
  Packs/TrendMicroDeepSecurity/README.md
  Packs/TrendMicroDeepSecurity/ReleaseNotes/1_0_5.md
  Packs/TrendMicroDeepSecurity/pack_metadata.json
Labels: docs-approved

#24824 XSIAM | Add Vectra Event Collector
  Packs/Vectra_AI/.secrets-ignore
  Packs/Vectra_AI/Integrations/VectraAIEventCollector/Pipfile
  Packs/Vectra_AI/Integrations/VectraAIEventCollector/README.md
  Packs/Vectra_AI/Integrations/VectraAIEventCollector/VectraAIEventCollector.py
  Packs/Vectra_AI/Integrations/VectraAIEventCollector/VectraAIEventCollector.yml
  Packs/Vectra_AI/Integrations/VectraAIEventCollector/VectraAIEventCollector_description.md
  Packs/Vectra_AI/Integrations/VectraAIEventCollector/VectraAIEventCollector_image.png
  Packs/Vectra_AI/Integrations/VectraAIEventCollector/VectraAIEventCollector_test.py
  Packs/Vectra_AI/Integrations/VectraAIEventCollector/command_examples
  Packs/Vectra_AI/Integrations/VectraAIEventCollector/test_data/audits.json
  Packs/Vectra_AI/Integrations/VectraAIEventCollector/test_data/search_detections.json
  Packs/Vectra_AI/ModelingRules/Vectra_AIEventCollector_1_3/Vectra_AIEventCollector_1_3.xif
  Packs/Vectra_AI/ModelingRules/Vectra_AIEventCollector_1_3/Vectra_AIEventCollector_1_3.yml
  Packs/Vectra_AI/ModelingRules/Vectra_AIEventCollector_1_3/Vectra_AIEventCollector_1_3_schema.json
  Packs/Vectra_AI/README.md
  Packs/Vectra_AI/ReleaseNotes/1_2_2.md
  Packs/Vectra_AI/pack_metadata.json
Labels: docs-approved

#26490 MS teams adding hyper link parameter
  Packs/MicrosoftTeams/Integrations/MicrosoftTeams/MicrosoftTeams.py
  Packs/MicrosoftTeams/Integrations/MicrosoftTeams/MicrosoftTeams.yml
  Packs/MicrosoftTeams/Integrations/MicrosoftTeams/MicrosoftTeams_description.md
  Packs/MicrosoftTeams/Integrations/MicrosoftTeams/MicrosoftTeams_test.py
  Packs/MicrosoftTeams/Integrations/MicrosoftTeams/README.md
  Packs/MicrosoftTeams/ReleaseNotes/1_4_18.md
  Packs/MicrosoftTeams/pack_metadata.json
Labels: docs-approved

#26437 Azure feed set default indicator service to indicator ID
  Packs/FeedAzure/Integrations/FeedAzure/FeedAzure.py
  Packs/FeedAzure/Integrations/FeedAzure/FeedAzure.yml
  Packs/FeedAzure/Integrations/FeedAzure/FeedAzure_test.py
  Packs/FeedAzure/ReleaseNotes/1_0_25.md
  Packs/FeedAzure/pack_metadata.json
Labels: docs-approved

#26234 XSIAM Layouts Buttons Name
  Packs/Core/Layouts/layoutscontainer-Default_XDR_Alert.json
  Packs/Core/ReleaseNotes/1_3_51.md
  Packs/Core/pack_metadata.json
Labels: docs-approved

#26492 Fixed an issue in upload where a variable is referenced before assignment
  Tests/Marketplace/upload_packs.py
Labels: docs-approved

#26387 Fix containment plan PB - Removed the Username input from Block Indicators Sub playbook
  Packs/CommonPlaybooks/Playbooks/playbook-Containment_Plan.yml
  Packs/CommonPlaybooks/ReleaseNotes/2_3_65.md
  Packs/CommonPlaybooks/pack_metadata.json
Labels: docs-approved

#26470 First sso access containment update
  Packs/CortexXDR/Playbooks/playbook-Cortex_XDR_-_First_SSO_Access.yml
  Packs/CortexXDR/Playbooks/playbook-Cortex_XDR_-_First_SSO_Access_README.md
  Packs/CortexXDR/ReleaseNotes/4_10_41.md
  Packs/CortexXDR/doc_files/Cortex_XDR_-_First_SSO_Access.png
  Packs/CortexXDR/pack_metadata.json
Labels: docs-approved

#26504 Deprecate opsgenieV2
  Packs/Opsgeniev2/Integrations/Opsgeniev2/Opsgeniev2.yml
  Packs/Opsgeniev2/ReleaseNotes/1_0_6.md
  Packs/Opsgeniev2/pack_metadata.json
Labels: docs-approved

#26500 1.14.5
  .hooks/pre-commit
  poetry.lock
  pyproject.toml
Labels: docs-approved

#25796 Team viewer collector
  Packs/TeamViewer/.pack-ignore
  Packs/TeamViewer/.secrets-ignore
  Packs/TeamViewer/Integrations/TeamViewerEventCollector/README.md
  Packs/TeamViewer/Integrations/TeamViewerEventCollector/TeamViewerEventCollector.py
  Packs/TeamViewer/Integrations/TeamViewerEventCollector/TeamViewerEventCollector.yml
  Packs/TeamViewer/Integrations/TeamViewerEventCollector/TeamViewerEventCollector_description.md
  Packs/TeamViewer/Integrations/TeamViewerEventCollector/TeamViewerEventCollector_image.png
  Packs/TeamViewer/Integrations/TeamViewerEventCollector/TeamViewerEventCollector_test.py
  Packs/TeamViewer/ModelingRules/TeamViewer/TeamViewer.xif
  Packs/TeamViewer/ModelingRules/TeamViewer/TeamViewer.yml
  Packs/TeamViewer/ModelingRules/TeamViewer/TeamViewer_schema.json
  Packs/TeamViewer/README.md
  Packs/TeamViewer/pack_metadata.json
Labels: docs-approved

#26512 Limit Hypothesis Examples
  Packs/Vectra_AI/Integrations/VectraAIEventCollector/VectraAIEventCollector.yml
  Packs/Vectra_AI/Integrations/VectraAIEventCollector/VectraAIEventCollector_test.py
  Packs/Vectra_AI/ReleaseNotes/1_2_3.md
  Packs/Vectra_AI/pack_metadata.json
Labels: docs-approved

#26450 google-cloud-logging
  Packs/GoogleCloudLogging/.pack-ignore
  Packs/GoogleCloudLogging/.secrets-ignore
  Packs/GoogleCloudLogging/Integrations/GoogleCloudLogging/GoogleCloudLogging.py
  Packs/GoogleCloudLogging/Integrations/GoogleCloudLogging/GoogleCloudLogging.yml
  Packs/GoogleCloudLogging/Integrations/GoogleCloudLogging/GoogleCloudLogging_description.md
  Packs/GoogleCloudLogging/Integrations/GoogleCloudLogging/GoogleCloudLogging_image.png
  Packs/GoogleCloudLogging/Integrations/GoogleCloudLogging/GoogleCloudLogging_test.py
  Packs/GoogleCloudLogging/Integrations/GoogleCloudLogging/README.md
  Packs/GoogleCloudLogging/Integrations/GoogleCloudLogging/command_examples
  Packs/GoogleCloudLogging/Integrations/GoogleCloudLogging/test_data/service_account_json.json
  Packs/GoogleCloudLogging/Integrations/GoogleCloudLogging/test_data/test_data.json
  Packs/GoogleCloudLogging/README.md
  Packs/GoogleCloudLogging/pack_metadata.json
Labels: docs-approved

#26506 Xsup 17927/ms dfe/fix fetch
  Packs/MicrosoftDefenderAdvancedThreatProtection/Integrations/MicrosoftDefenderAdvancedThreatProtection/MicrosoftDefenderAdvancedThreatProtection.py
  Packs/MicrosoftDefenderAdvancedThreatProtection/Integrations/MicrosoftDefenderAdvancedThreatProtection/MicrosoftDefenderAdvancedThreatProtection.yml
  Packs/MicrosoftDefenderAdvancedThreatProtection/ReleaseNotes/1_15_22.md
  Packs/MicrosoftDefenderAdvancedThreatProtection/pack_metadata.json
Labels: docs-approved

#26516 Fixing layout "Campaign Duration" in phishing campaign incident
  Packs/Campaign/ReleaseNotes/3_2_22.md
  Packs/Campaign/Scripts/GetCampaignDuration/GetCampaignDuration.py
  Packs/Campaign/Scripts/GetCampaignDuration/GetCampaignDuration.yml
  Packs/Campaign/Scripts/GetCampaignDuration/GetCampaignDuration_test.py
  Packs/Campaign/pack_metadata.json
Labels: docs-approved

#26552 Mandiant fix
  Packs/FeedMandiant/Integrations/FeedMandiant/FeedMandiant.py
  Packs/FeedMandiant/Integrations/FeedMandiant/test_data/result_indicators.json
  Packs/FeedMandiant/ReleaseNotes/1_0_14.md
  Packs/FeedMandiant/pack_metadata.json
Labels: docs-approved

#26109 [EDL] Improve Documentation & Add additional HTTP Header
  Packs/EDL/Integrations/EDL/EDL.py
  Packs/EDL/Integrations/EDL/EDL.yml
  Packs/EDL/Integrations/EDL/EDL_test.py
  Packs/EDL/Integrations/EDL/README.md
  Packs/EDL/ReleaseNotes/3_1_24.md
  Packs/EDL/pack_metadata.json
  Tests/conf.json
Labels: docs-approved

#26560 fix sanepdf current time when forcing server formatting
  Packs/Base/ReleaseNotes/1_32_2.md
  Packs/Base/Scripts/SanePdfReport/SanePdfReport.yml
  Packs/Base/pack_metadata.json
Labels: docs-approved

#26559 Rapid7 widget id update
  Packs/CommonDashboards/Dashboards/dashboard-APIExecutionMetrics.json
  Packs/CommonDashboards/ReleaseNotes/1_3_4.md
  Packs/CommonDashboards/pack_metadata.json
  Packs/IntSight/ReleaseNotes/3_0_1.md
  Packs/IntSight/Widgets/Widget-API_Call_Results_for_Rapid7_Threat_Command.json
  Packs/IntSight/pack_metadata.json
Labels: docs-approved

#26564 devcontainer updates
  .devcontainer/Dockerfile
  .devcontainer/createCommand.sh
  .devcontainer/devcontainer.json
  .devcontainer/settings.json
  .github/workflows/check-devcontainer.yml
  .vscode/extensions.json
Labels: docs-approved

#26497 fix data source packs filtering to contain only packs with one integration
  Tests/Marketplace/Tests/marketplace_services_test.py
  Tests/Marketplace/marketplace_services.py
Labels: docs-approved

#26561 Extract indicators exclude oft
  Packs/CommonPlaybooks/Playbooks/playbook-Extract_Indicators_From_File_-_Generic_v2_4_5.yml
  Packs/CommonPlaybooks/ReleaseNotes/2_3_66.md
  Packs/CommonPlaybooks/pack_metadata.json
Labels: docs-approved

#26553 Upload preview images every upload-flow and not only by git diff
  Tests/Marketplace/marketplace_services.py
  Tests/Marketplace/pack_readme_handler.py
  Tests/Marketplace/upload_packs.py
Labels: docs-approved

#26577 TeamViewer readme fix
  Packs/TeamViewer/.secrets-ignore
  Packs/TeamViewer/README.md
Labels: docs-approved

#25853 Test Playbook - Cortex XDR Malware - Incident Enrichment
  Packs/CortexXDR/Playbooks/playbook-Cortex_XDR_Malware_-_Incident_Enrichment.yml
  Packs/CortexXDR/ReleaseNotes/4_10_42.md
  Packs/CortexXDR/TestPlaybooks/Test_Playbook_-_Cortex_XDR_Malware_-_Incident_Enrichment.yml
  Packs/CortexXDR/pack_metadata.json
  Tests/conf.json
Labels: docs-approved

#26456 added core packs lists as required to be up-to-date from master
  .circleci/config.yml
  .gitlab/ci/global.yml
  Tests/scripts/is_file_up_to_date.sh
Labels: docs-approved

#26578 Fixing an issue in Jira v2 when the language is not English
  Packs/Jira/Integrations/JiraV2/JiraV2.py
  Packs/Jira/Integrations/JiraV2/JiraV2.yml
  Packs/Jira/Integrations/JiraV2/JiraV2_test.py
  Packs/Jira/ReleaseNotes/2_0_36.md
  Packs/Jira/pack_metadata.json
Labels: docs-approved
