Repository demisto/content, pull requests merged in 2023-08, with the labels that each got.

#28598 Similarity list bugfix
  Packs/CommonScripts/ReleaseNotes/1_12_10.md
  Packs/CommonScripts/Scripts/StringSimilarity/README.md
  Packs/CommonScripts/Scripts/StringSimilarity/StringSimilarity.py
  Packs/CommonScripts/Scripts/StringSimilarity/StringSimilarity.yml
  Packs/CommonScripts/Scripts/StringSimilarity/StringSimilarity_test.py
  Packs/CommonScripts/pack_metadata.json
Labels: ForceMerge

#28601 demisto-sdk update dep add pre-commit
  .github/workflows/update-demisto-sdk-version.yml
Labels: docs-approved

#28425 Parsing rules fix filter 7
  Packs/MySQLEnterprise/ParsingRules/MySQLEnterprise/MySQLEnterprise.xif
  Packs/MySQLEnterprise/README.md
  Packs/MySQLEnterprise/ReleaseNotes/1_0_5.md
  Packs/MySQLEnterprise/pack_metadata.json
  Packs/NGINXWebServer/ParsingRules/NGINXWebServerParsingRules/NGINXWebServerParsingRules.xif
  Packs/NGINXWebServer/README.md
  Packs/NGINXWebServer/ReleaseNotes/1_0_6.md
  Packs/NGINXWebServer/pack_metadata.json
Labels: docs-approved

#28218 Parsing Rules Filter Fix Round 2
  Packs/ManageEngine-ADManager/.pack-ignore
  Packs/ManageEngine-ADManager/.secrets-ignore
  Packs/ManageEngine-ADManager/ParsingRules/ManageEngine-ADManager/ManageEngine-ADManager.xif
  Packs/ManageEngine-ADManager/ParsingRules/ManageEngine-ADManager/ManageEngine-ADManager.yml
  Packs/ManageEngine-ADManager/README.md
  Packs/ManageEngine-ADManager/ReleaseNotes/1_0_1.md
  Packs/ManageEngine-ADManager/pack_metadata.json
  Packs/Mimecast/ParsingRules/MimecastParsingRules/MimecastParsingRules.xif
  Packs/Mimecast/README.md
  Packs/Mimecast/ReleaseNotes/2_1_10.md
  Packs/Mimecast/pack_metadata.json
  Packs/Workday/ParsingRules/WorkdayParsingRules/WorkdayParsingRules.xif
  Packs/Workday/README.md
  Packs/Workday/ReleaseNotes/1_3_7.md
  Packs/Workday/pack_metadata.json
Labels: docs-approved

#28629 skip scripts running with native-image
  Tests/docker_native_image_config.json
Labels: docs-approved

#28573 [ASM] - Expander - Enrichment Status and N/A values (3581 & 4820)
  Packs/CortexAttackSurfaceManagement/IncidentFields/incidentfield-ASM_-_Enrichment_Status.json
  Packs/CortexAttackSurfaceManagement/Playbooks/Cortex_ASM_-_AWS_Enrichment.yml
  Packs/CortexAttackSurfaceManagement/Playbooks/Cortex_ASM_-_Azure_Enrichment.yml
  Packs/CortexAttackSurfaceManagement/Playbooks/Cortex_ASM_-_GCP_Enrichment.yml
  Packs/CortexAttackSurfaceManagement/Playbooks/Cortex_ASM_-_Prisma_Cloud_Enrichment.yml
  Packs/CortexAttackSurfaceManagement/Playbooks/Cortex_ASM_-_Qualys_Enrichment.yml
  Packs/CortexAttackSurfaceManagement/Playbooks/Cortex_ASM_-_Rapid7_Enrichment.yml
  Packs/CortexAttackSurfaceManagement/Playbooks/Cortex_ASM_-_Remediation_Confirmation_Scan.yml
  Packs/CortexAttackSurfaceManagement/Playbooks/Cortex_ASM_-_ServiceNow_CMDB_Enrichment.yml
  Packs/CortexAttackSurfaceManagement/Playbooks/Cortex_ASM_-_Splunk_Enrichment.yml
  Packs/CortexAttackSurfaceManagement/Playbooks/Cortex_ASM_-_Tenable.io_Enrichment.yml
  Packs/CortexAttackSurfaceManagement/ReleaseNotes/1_6_27.md
  Packs/CortexAttackSurfaceManagement/Scripts/GenerateASMReport/GenerateASMReport.py
  Packs/CortexAttackSurfaceManagement/Scripts/GenerateASMReport/GenerateASMReport.yml
  Packs/CortexAttackSurfaceManagement/Scripts/GenerateASMReport/GenerateASMReport_test.py
  Packs/CortexAttackSurfaceManagement/doc_files/Cortex_ASM_-_AWS_Enrichment.png
  Packs/CortexAttackSurfaceManagement/doc_files/Cortex_ASM_-_Azure_Enrichment.png
  Packs/CortexAttackSurfaceManagement/doc_files/Cortex_ASM_-_GCP_Enrichment.png
  Packs/CortexAttackSurfaceManagement/doc_files/Cortex_ASM_-_Prisma_Cloud_Enrichment.png
  Packs/CortexAttackSurfaceManagement/doc_files/Cortex_ASM_-_Qualys_Enrichment.png
  Packs/CortexAttackSurfaceManagement/doc_files/Cortex_ASM_-_Rapid7_Enrichment.png
  Packs/CortexAttackSurfaceManagement/doc_files/Cortex_ASM_-_ServiceNow_CMDB_Enrichment.png
  Packs/CortexAttackSurfaceManagement/doc_files/Cortex_ASM_-_Splunk_Enrichment.png
  Packs/CortexAttackSurfaceManagement/doc_files/Cortex_ASM_-_Tenable.io_Enrichment.png
  Packs/CortexAttackSurfaceManagement/pack_metadata.json
Labels: Contribution, Contribution Form Filled, Community, Xsoar Support Level, External PR, Security Review

#28653 fixed dt condition in snow ticket state polling playbook
  Packs/ServiceNow/Playbooks/playbook-ServiceNow_Ticket_State_Polling.yml
  Packs/ServiceNow/ReleaseNotes/2_5_35.md
  Packs/ServiceNow/pack_metadata.json
Labels: docs-approved

#28522 Code review google chronicle
  Packs/GoogleChronicleBackstory/.pack-ignore
  Packs/GoogleChronicleBackstory/Integrations/GoogleChronicleBackstory/GoogleChronicleBackstory.yml
  Packs/GoogleChronicleBackstory/ReleaseNotes/3_0_0.md
  Packs/GoogleChronicleBackstory/ReleaseNotes/3_0_1.md
  Packs/GoogleChronicleBackstory/pack_metadata.json
Labels: docs-approved

#28666 Remove `BA125` from `.pack-ignore`
  Packs/HarfangLabEDR/.pack-ignore
  Packs/Zabbix/.pack-ignore
Labels: docs-approved

#28662 Override corepacks-8.3.0.json File
  Tests/Marketplace/versions-metadata.json
Labels: docs-approved, ForceMerge

#28672 Re-lock corepacks-8.3.0.json file
  Tests/Marketplace/versions-metadata.json
Labels: docs-approved

#28676 CIAC-7524 test
  Packs/HelloWorld/Playbooks/playbook-HelloWorld_Scan.yml
  Packs/HelloWorld/ReleaseNotes/1_1_0.md
Labels: Contribution, Community Support Level, External PR, Security Review

#28533 Pan os edit rule error without commit issue
  Packs/PAN-OS/Integrations/Panorama/Panorama.py
  Packs/PAN-OS/Integrations/Panorama/Panorama.yml
  Packs/PAN-OS/Integrations/Panorama/Panorama_test.py
  Packs/PAN-OS/ReleaseNotes/1_17_17.md
  Packs/PAN-OS/pack_metadata.json
Labels: docs-approved

#28594 Command line analysis lolbas enahancement
  Packs/CommonPlaybooks/Playbooks/playbook-Command-Line_Analysis.yml
  Packs/CommonPlaybooks/Playbooks/playbook-Command-Line_Analysis_README.md
  Packs/CommonPlaybooks/ReleaseNotes/2_3_84.md
  Packs/CommonPlaybooks/doc_files/Command-Line_Analysis.png
  Packs/CommonPlaybooks/pack_metadata.json
  Packs/FeedLOLBAS/Playbooks/playbook-Compare_Process_Execution_Arguments_To_LOLBAS_Patterns.yml
  Packs/FeedLOLBAS/Playbooks/playbook-Compare_Process_Execution_Arguments_To_LOLBAS_Patterns_README.md
  Packs/FeedLOLBAS/ReleaseNotes/1_0_4.md
  Packs/FeedLOLBAS/doc_files/Compare_Process_Execution_Arguments_To_LOLBAS_Patterns.png
  Packs/FeedLOLBAS/pack_metadata.json
Labels: docs-approved

#28597 [AWSSecurityHubCollector] Fix `is_array` in Schema File
  Packs/AWS-SecurityHub/ModelingRules/AWSSecurityHubModelingRules/AWSSecurityHubModelingRules_schema.json
  Packs/AWS-SecurityHub/ReleaseNotes/1_3_8.md
  Packs/AWS-SecurityHub/pack_metadata.json
Labels: docs-approved

#28384 Mde fetch alerts by detectionsource
  Packs/MicrosoftDefenderAdvancedThreatProtection/Integrations/MicrosoftDefenderAdvancedThreatProtection/MicrosoftDefenderAdvancedThreatProtection.py
  Packs/MicrosoftDefenderAdvancedThreatProtection/Integrations/MicrosoftDefenderAdvancedThreatProtection/MicrosoftDefenderAdvancedThreatProtection.yml
  Packs/MicrosoftDefenderAdvancedThreatProtection/Integrations/MicrosoftDefenderAdvancedThreatProtection/MicrosoftDefenderAdvancedThreatProtection_test.py
  Packs/MicrosoftDefenderAdvancedThreatProtection/Integrations/MicrosoftDefenderAdvancedThreatProtection/README.md
  Packs/MicrosoftDefenderAdvancedThreatProtection/ReleaseNotes/1_16_0.md
  Packs/MicrosoftDefenderAdvancedThreatProtection/pack_metadata.json
Labels: Contribution, docs-approved, ready-for-instance-test, pending-demo, Contribution Form Filled, Community, ignore-auto-bump-version, Xsoar Support Level, External PR

#28695 Adding new queue for upload machines
  .gitlab/ci/.gitlab-ci.bucket-upload.yml
Labels: docs-approved

#28668 Fixed fetch incidents debug logs
  Packs/Base/ReleaseNotes/1_32_23.md
  Packs/Base/Scripts/CommonServerPython/CommonServerPython.py
  Packs/Base/pack_metadata.json
Labels: docs-approved

#28656 [native-runner] - stop supporting 8.2
  Tests/docker_native_image_config.json
Labels: docs-approved

#28671 Add skip:true to skip sourcery
  .pre-commit-config_template.yaml
Labels: docs-approved

#28701 QRadar: pre-commit
  Packs/QRadar/Integrations/QRadar_v3/QRadar_v3.py
  Packs/QRadar/Integrations/QRadar_v3/QRadar_v3_test.py
  Packs/QRadar/ReleaseNotes/2_4_27.md
  Packs/QRadar/pack_metadata.json
Labels: docs-approved

#28667 Account enrichment & endpoint enrichment playbooks enhancement
  Packs/CommonPlaybooks/Playbooks/playbook-Account_Enrichment_-_Generic_v2.2.yml
  Packs/CommonPlaybooks/Playbooks/playbook-Account_Enrichment_-_Generic_v2.2_README.md
  Packs/CommonPlaybooks/Playbooks/playbook-Endpoint_Enrichment_-_Generic_v2.1_6_8.yml
  Packs/CommonPlaybooks/Playbooks/playbook-Endpoint_Enrichment_-_Generic_v2.1_6_8_README.md
  Packs/CommonPlaybooks/ReleaseNotes/2_3_85.md
  Packs/CommonPlaybooks/doc_files/Account_Enrichment_-_Generic_v2.1.png
  Packs/CommonPlaybooks/doc_files/Endpoint_Enrichment_-_Generic_v2.1_6_8.png
  Packs/CommonPlaybooks/pack_metadata.json
Labels: docs-approved

#28674 Fix merge master secrets
  .gitlab/ci/.gitlab-ci.on-push.yml
Labels: docs-approved

#28689 delete old modeling rules
  Packs/CiscoASA/ModelingRules/CiscoASA/CiscoASA.xif
  Packs/CiscoASA/ModelingRules/CiscoASA/CiscoASA.yml
  Packs/CiscoASA/ModelingRules/CiscoASA/CiscoASA_schema.json
  Packs/CiscoASA/ModelingRules/CiscoASA_1_3/CiscoASA_1_3.xif
  Packs/CiscoASA/ModelingRules/CiscoASA_1_3/CiscoASA_1_3.yml
  Packs/CiscoASA/ModelingRules/CiscoASA_1_3/CiscoASA_1_3_schema.json
  Packs/CiscoASA/ModelingRules/CiscoASA_1_3/CiscoASA_1_3_testdata.json
  Packs/CyberArkIdentity/ModelingRules/CyberArkIdentityEventCollector/CyberArkIdentityEventCollector.xif
  Packs/CyberArkIdentity/ModelingRules/CyberArkIdentityEventCollector/CyberArkIdentityEventCollector.yml
  Packs/CyberArkIdentity/ModelingRules/CyberArkIdentityEventCollector/CyberArkIdentityEventCollector_schema.json
  Packs/FortiGate/ModelingRules/FortiGate/FortiGate.xif
  Packs/FortiGate/ModelingRules/FortiGate/FortiGate.yml
  Packs/FortiGate/ModelingRules/FortiGate/FortiGate_schema.json
  Packs/MicrosoftDNS/ModelingRules/MicrosoftDNS/MicrosoftDNS.xif
  Packs/MicrosoftDNS/ModelingRules/MicrosoftDNS/MicrosoftDNS.yml
  Packs/MicrosoftDNS/ModelingRules/MicrosoftDNS/MicrosoftDNS_schema.json
Labels: docs-approved, ForceMerge

#28694 Override corepack-8.3.0.json using the latest version
  Tests/Marketplace/corepacks_override.json
Labels: docs-approved

#28722 Test Tech Writer Assignee Removal from Internal PR
  Packs/HelloWorld/README.md
  Packs/HelloWorld/ReleaseNotes/1_1_0.md
Labels: Contribution, Community Support Level, External PR

#28706 fixed display for type 9 parameters in workday
  Packs/Workday/Integrations/Workday/Workday.yml
  Packs/Workday/ReleaseNotes/1_3_8.md
  Packs/Workday/pack_metadata.json
Labels: docs-approved

#28717 pre-commit fixed the --no-unit-test flag
  .github/workflows/update-demisto-sdk-version.yml
Labels: docs-approved

#28538 Packs/SlacV3: added user session reset command
  Packs/Slack/Integrations/SlackV3/SlackV3.py
  Packs/Slack/Integrations/SlackV3/SlackV3.yml
  Packs/Slack/Integrations/SlackV3/SlackV3_test.py
  Packs/Slack/ReleaseNotes/3_1_45.md
  Packs/Slack/pack_metadata.json
Labels: Contribution, Partner, Contribution Form Filled, Xsoar Support Level, External PR

#28739 AzureEventHub to Hidden
  Packs/AzureEventsHub/pack_metadata.json
Labels: docs-approved

#28713 [MicrosoftManagementActivity] updated fetch start_time
  Packs/MicrosoftManagementActivity/Integrations/MicrosoftManagementActivity/MicrosoftManagementActivity.py
  Packs/MicrosoftManagementActivity/Integrations/MicrosoftManagementActivity/MicrosoftManagementActivity.yml
  Packs/MicrosoftManagementActivity/Integrations/MicrosoftManagementActivity/MicrosoftManagementActivity_test.py
  Packs/MicrosoftManagementActivity/Integrations/MicrosoftManagementActivity/README.md
  Packs/MicrosoftManagementActivity/ReleaseNotes/1_3_24.md
  Packs/MicrosoftManagementActivity/pack_metadata.json
Labels: docs-approved

#28696 Yr/create a new filter any match/ciac 6748
  Packs/FiltersAndTransformers/.pack-ignore
  Packs/FiltersAndTransformers/ReleaseNotes/1_2_26.md
  Packs/FiltersAndTransformers/Scripts/AnyMatch/AnyMatch.py
  Packs/FiltersAndTransformers/Scripts/AnyMatch/AnyMatch.yml
  Packs/FiltersAndTransformers/Scripts/AnyMatch/AnyMatch_test.py
  Packs/FiltersAndTransformers/Scripts/AnyMatch/README.md
  Packs/FiltersAndTransformers/TestPlaybooks/AnyMatch_Test.yml
  Packs/FiltersAndTransformers/pack_metadata.json
  Tests/conf.json
Labels: docs-approved

#28518 cymulate commit-attempt3-new creds
  Packs/Cymulate/Integrations/Cymulate_v2/Cymulate_v2.py
  Packs/Cymulate/Integrations/Cymulate_v2/Cymulate_v2.yml
  Packs/Cymulate/ReleaseNotes/2_0_22.md
  Packs/Cymulate/pack_metadata.json
Labels: Contribution, Partner, Contribution Form Filled, Partner Support Level, External PR

#28577 Update GenericWebhook README.md
  Packs/GenericWebhook/Integrations/GenericWebhook/README.md
Labels: docs-approved

#28590 Changed HarfangLab api key type
  Packs/HarfangLabEDR/Integrations/Hurukai/Hurukai.py
  Packs/HarfangLabEDR/Integrations/Hurukai/Hurukai.yml
  Packs/HarfangLabEDR/Integrations/Hurukai/README.md
  Packs/HarfangLabEDR/ReleaseNotes/1_1_5.md
  Packs/HarfangLabEDR/pack_metadata.json
Labels: docs-approved

#28746 ruff: remove `SIM108`
  pyproject.toml
Labels: docs-approved

#28744 git-add-before-pre-commit
  .github/workflows/update-demisto-sdk-version.yml
Labels: docs-approved

#28636 Mcafee nsm modeling rule enhancement
  Packs/McAfeeNSM/ModelingRules/McAfeeNSM_1_3/McAfeeNSM_1_3.xif
  Packs/McAfeeNSM/ReleaseNotes/1_2_9.md
  Packs/McAfeeNSM/pack_metadata.json
Labels: docs-approved

#28714 Ignore Intezer from Running on Native Docker Images
  Tests/docker_native_image_config.json
Labels: docs-approved

#28702 S&c fix for delegation
  Packs/MicrosoftExchangeOnline/Integrations/SecurityAndCompliance/SecurityAndCompliance.yml
  Packs/MicrosoftExchangeOnline/Integrations/SecurityAndComplianceV2/README.md
  Packs/MicrosoftExchangeOnline/Integrations/SecurityAndComplianceV2/SecurityAndComplianceV2.ps1
  Packs/MicrosoftExchangeOnline/Integrations/SecurityAndComplianceV2/SecurityAndComplianceV2.yml
  Packs/MicrosoftExchangeOnline/Integrations/SecurityAndComplianceV2/SecurityAndComplianceV2_description.md
  Packs/MicrosoftExchangeOnline/ReleaseNotes/1_2_15.md
  Packs/MicrosoftExchangeOnline/pack_metadata.json
  Tests/conf.json
Labels: docs-approved

#28560 Update documentation for pan-os-platform-get-device-g…
  Packs/PAN-OS/Integrations/Panorama/Panorama.yml
  Packs/PAN-OS/Integrations/Panorama/README.md
  Packs/PAN-OS/ReleaseNotes/1_17_18.md
  Packs/PAN-OS/pack_metadata.json
Labels: docs-approved

#28678 Fix server logs download
  .gitlab/ci/.gitlab-ci.bucket-upload.yml
  .gitlab/ci/.gitlab-ci.instance-test.yml
  .gitlab/ci/.gitlab-ci.on-push.yml
  .gitlab/ci/.gitlab-ci.sdk-nightly.yml
  .pre-commit-config_template.yaml
  Tests/scripts/destroy_instances.py
  Tests/scripts/wait_until_server_ready.py
  poetry.lock
  pyproject.toml
Labels: docs-approved

#28738 Update README.md
  Packs/MicrosoftTeams/Integrations/MicrosoftTeams/README.md
Labels: docs-approved

#28637 CrowdStrike Falcon X playbook - branch logic is incorrect
  Packs/CrowdStrikeFalconX/Playbooks/playbook-FalconX_Detonate_and_Analyze_File.yml
  Packs/CrowdStrikeFalconX/ReleaseNotes/1_2_32.md
  Packs/CrowdStrikeFalconX/pack_metadata.json
Labels: Contribution, Contribution Form Filled, Community, Xsoar Support Level, External PR, Security Review

#28787 Add breaking change notice to S&C
  Packs/MicrosoftExchangeOnline/ReleaseNotes/1_2_15.json
  Packs/MicrosoftExchangeOnline/ReleaseNotes/1_2_15.md
Labels: docs-approved

#28776 Symantec DLP key error
  Packs/SymantecDLP/Integrations/SymantecDLPV2/SymantecDLPV2.py
  Packs/SymantecDLP/Integrations/SymantecDLPV2/SymantecDLPV2.yml
  Packs/SymantecDLP/ReleaseNotes/2_1_2.md
  Packs/SymantecDLP/pack_metadata.json
Labels: docs-approved

#28724 [ASM] - Expander - Initialization
  Packs/CortexAttackSurfaceManagement/IncidentFields/incidentfield-ASM_-_Data_Collection.json
  Packs/CortexAttackSurfaceManagement/IncidentFields/incidentfield-ASM_-_Service_Detection.json
  Packs/CortexAttackSurfaceManagement/IncidentFields/incidentfield-ASM_-_Service_Owner_Unranked_Raw.json
  Packs/CortexAttackSurfaceManagement/Playbooks/Cortex_ASM_-_ASM_Alert.yml
  Packs/CortexAttackSurfaceManagement/Playbooks/Cortex_ASM_-_Remediation_Path_Rules.yml
  Packs/CortexAttackSurfaceManagement/Playbooks/Cortex_ASM_-_Remediation_Path_Rules_README.md
  Packs/CortexAttackSurfaceManagement/ReleaseNotes/1_6_27.md
  Packs/CortexAttackSurfaceManagement/doc_files/Cortex_ASM_-_ASM_Alert.png
  Packs/CortexAttackSurfaceManagement/pack_metadata.json
Labels: Contribution, docs-approved, Contribution Form Filled, Community, Xsoar Support Level, External PR, Security Review

#27381 QRadar: Support API version 17
  Packs/QRadar/Integrations/QRadar_v3/QRadar_v3.py
  Packs/QRadar/Integrations/QRadar_v3/QRadar_v3.yml
  Packs/QRadar/Integrations/QRadar_v3/QRadar_v3_test.py
  Packs/QRadar/Integrations/QRadar_v3/README.md
  Packs/QRadar/Integrations/QRadar_v3/command_examples.txt
  Packs/QRadar/Integrations/QRadar_v3/test_data/command_test_data.json
  Packs/QRadar/Playbooks/playbook-QRadar_-_Get_Offense_Logs.yml
  Packs/QRadar/ReleaseNotes/2_4_28.md
  Packs/QRadar/TestPlaybooks/QRadar_v3-test.yml
  Packs/QRadar/TestPlaybooks/playbook-QRadar_-_Get_Offense_Logs_Test.yml
  Packs/QRadar/pack_metadata.json
  Tests/conf.json
Labels: docs-approved

#28785 QRadar - XSUP-26888 - Fix skipped incidents when creation failed
  Packs/QRadar/Integrations/QRadar_v3/QRadar_v3.py
  Packs/QRadar/ReleaseNotes/2_4_29.md
  Packs/QRadar/pack_metadata.json
Labels: docs-approved

#28792 update native candidate
  Tests/docker_native_image_config.json
Labels: docs-approved

#28719 packs/Reco: add change alert status command
  Packs/Reco/Integrations/Reco/README.md
  Packs/Reco/Integrations/Reco/Reco.py
  Packs/Reco/Integrations/Reco/Reco.yml
  Packs/Reco/Integrations/Reco/Reco_test.py
  Packs/Reco/ReleaseNotes/1_1_5.md
  Packs/Reco/pack_metadata.json
Labels: Contribution, Partner, Contribution Form Filled, Partner Support Level, External PR

#28588 Ignore schema testdata validations
  Packs/AWS-SecurityHub/ModelingRules/AWSSecurityHubModelingRules/AWSSecurityHubModelingRules_testdata.json
  Packs/ManageEngine-ADAudit/ModelingRules/ManageEngine-ADAudit_1_3/ManageEngine-ADAudit_1_3_testdata.json
  Packs/NetBox/ModelingRules/NetBoxModelingRules_1_3/NetBoxModelingRules_1_3_testdata.json
  Packs/RunZero/ModelingRules/RunZeroModelingRules/RunZeroModelingRules_testdata.json
  Packs/Zoom/ModelingRules/Zoom/Zoom_testdata.json
Labels: docs-approved

#28794 [Mimecast] Pre-Commit and some improvement
  Packs/Mimecast/Integrations/MimecastV2/MimecastV2.py
  Packs/Mimecast/Integrations/MimecastV2/MimecastV2.yml
  Packs/Mimecast/Integrations/MimecastV2/MimecastV2_test.py
  Packs/Mimecast/ReleaseNotes/2_1_11.md
  Packs/Mimecast/pack_metadata.json
Labels: docs-approved

#28795 added loggings
  .gitlab/ci/.gitlab-ci.global.yml
Labels: docs-approved

#28799 MicrosoftGraphSecurity README Update
  Packs/MicrosoftGraphSecurity/README.md
Labels: docs-approved

#28796 XDR classifier fix
  Packs/CortexXDR/Classifiers/classifier-PaloAltoNetworks_Cortex_XDR_Incident_Handler.json
  Packs/CortexXDR/ReleaseNotes/5_0_6.md
  Packs/CortexXDR/pack_metadata.json
Labels: docs-approved

#28567 Added the option to pass chunk size to send_events_to_xsiam
  Packs/Base/ReleaseNotes/1_32_25.md
  Packs/Base/Scripts/CommonServerPython/CommonServerPython.py
  Packs/Base/Scripts/CommonServerPython/CommonServerPython_test.py
  Packs/Base/pack_metadata.json
Labels: docs-approved

#28704 Changed the type of the Phone Number incident field
  Packs/CommonTypes/IncidentFields/incidentfield-PhoneNumber.json
  Packs/CommonTypes/ReleaseNotes/3_3_83.md
  Packs/CommonTypes/pack_metadata.json
Labels: docs-approved, release-notes-only, ForceMerge

#28751 Tanium additional log types mapping
  Packs/Tanium/ModelingRules/Tanium/Tanium.xif
  Packs/Tanium/ModelingRules/Tanium/Tanium.yml
  Packs/Tanium/ModelingRules/Tanium/Tanium_schema.json
  Packs/Tanium/ParsingRules/Tanium/Tanium.xif
  Packs/Tanium/ParsingRules/Tanium/Tanium.yml
  Packs/Tanium/README.md
  Packs/Tanium/ReleaseNotes/1_0_28.md
  Packs/Tanium/doc_files/Tanium_Integrity_Monitor_TimeStamp.png
  Packs/Tanium/pack_metadata.json
  Packs/TaniumThreatResponse/README.md
Labels: docs-approved

#28469 [Build] Fix Dependency Issues (Restore & fix after revert)
  Tests/Marketplace/Tests/search_and_install_packs_test.py
  Tests/Marketplace/Tests/test_data/gitlab_api_pack_metadata/hidden-pack.json
  Tests/Marketplace/Tests/test_data/gitlab_api_pack_metadata/non-hidden-pack.json
  Tests/Marketplace/Tests/test_data/search_dependencies/AzureSentinel_1.5.8.json
  Tests/Marketplace/Tests/test_data/search_dependencies/HelloWorld_1.2.19.json
  Tests/Marketplace/configure_and_install_packs.py
  Tests/Marketplace/search_and_install_packs.py
  Tests/Marketplace/search_and_uninstall_pack.py
  Tests/configure_and_test_integration_instances.py
Labels: docs-approved

#28619 Private upload mode - docs #2
  Packs/CTIX/.pack-ignore
  Packs/CTIX/Integrations/CTIX/CTIX_description.md
  Packs/CTIX/Integrations/CTIX/README.md
  Packs/CTIX/Integrations/CTIXv3/CTIXv3_description.md
  Packs/CTIX/Integrations/CTIXv3/README.md
  Packs/CTIX/ReleaseNotes/2_2_12.md
  Packs/CTIX/pack_metadata.json
  Packs/CheckPhish/Integrations/CheckPhish/CheckPhish_description.md
  Packs/CheckPhish/Integrations/CheckPhish/README.md
  Packs/CheckPhish/ReleaseNotes/1_0_19.md
  Packs/CheckPhish/pack_metadata.json
  Packs/JsonWhoIs/Integrations/JsonWhoIs/JsonWhoIs_description.md
  Packs/JsonWhoIs/Integrations/JsonWhoIs/README.md
  Packs/JsonWhoIs/ReleaseNotes/1_0_21.md
  Packs/JsonWhoIs/pack_metadata.json
  Packs/MandiantAdvantageThreatIntelligence/.pack-ignore
  Packs/MandiantAdvantageThreatIntelligence/Integrations/MandiantAdvantageThreatIntelligence/MandiantAdvantageThreatIntelligence_description.md
  Packs/MandiantAdvantageThreatIntelligence/Integrations/MandiantAdvantageThreatIntelligence/README.md
  Packs/MandiantAdvantageThreatIntelligence/ReleaseNotes/1_0_7.md
  Packs/MandiantAdvantageThreatIntelligence/pack_metadata.json
  Packs/McAfee_Advanced_Threat_Defense/.pack-ignore
  Packs/McAfee_Advanced_Threat_Defense/Integrations/McAfee_Advanced_Threat_Defense/McAfee_Advanced_Threat_Defense_description.md
  Packs/McAfee_Advanced_Threat_Defense/Integrations/McAfee_Advanced_Threat_Defense/README.md
  Packs/McAfee_Advanced_Threat_Defense/ReleaseNotes/1_0_25.md
  Packs/McAfee_Advanced_Threat_Defense/pack_metadata.json
Labels: docs-approved

#28670 Private upload mode docs #4
  Packs/HatchingTriage/Integrations/HatchingTriage/HatchingTriage_description.md
  Packs/HatchingTriage/Integrations/HatchingTriage/README.md
  Packs/HatchingTriage/ReleaseNotes/1_0_13.md
  Packs/HatchingTriage/pack_metadata.json
  Packs/Intezer/Integrations/IntezerV2/IntezerV2_description.md
  Packs/Intezer/Integrations/IntezerV2/README.md
  Packs/Intezer/ReleaseNotes/1_5_13.md
  Packs/Intezer/pack_metadata.json
  Packs/JoeSecurity/Integrations/JoeSecurityV2/JoeSecurityV2_description.md
  Packs/JoeSecurity/Integrations/JoeSecurityV2/README.md
  Packs/JoeSecurity/ReleaseNotes/1_1_11.md
  Packs/JoeSecurity/pack_metadata.json
  Packs/Lastline/Integrations/Lastline_v2/Lastline_v2_description.md
  Packs/Lastline/Integrations/Lastline_v2/README.md
  Packs/Lastline/ReleaseNotes/1_0_17.md
  Packs/Lastline/pack_metadata.json
  Packs/OPSWAT-Filescan/.pack-ignore
  Packs/OPSWAT-Filescan/Integrations/OPSWATFilescan/OPSWATFilescan_description.md
  Packs/OPSWAT-Filescan/Integrations/OPSWATFilescan/README.md
  Packs/OPSWAT-Filescan/ReleaseNotes/1_0_2.md
  Packs/OPSWAT-Filescan/pack_metadata.json
Labels: docs-approved

#28700 Private upload mode docs #5
  Packs/Palo_Alto_Networks_WildFire/Integrations/Palo_Alto_Networks_WildFire_v2/Palo_Alto_Networks_WildFire_v2_description.md
  Packs/Palo_Alto_Networks_WildFire/Integrations/Palo_Alto_Networks_WildFire_v2/README.md
  Packs/Palo_Alto_Networks_WildFire/ReleaseNotes/2_1_32.md
  Packs/Palo_Alto_Networks_WildFire/pack_metadata.json
  Packs/QutteraWebsiteMalwareScanner/Integrations/QutteraWebsiteMalwareScanner/QutteraWebsiteMalwareScanner_description.md
  Packs/QutteraWebsiteMalwareScanner/Integrations/QutteraWebsiteMalwareScanner/README.md
  Packs/QutteraWebsiteMalwareScanner/ReleaseNotes/1_0_8.md
  Packs/QutteraWebsiteMalwareScanner/pack_metadata.json
  Packs/SlashNextPhishingIncidentResponse/Integrations/SlashNextPhishingIncidentResponse/README.md
  Packs/SlashNextPhishingIncidentResponse/Integrations/SlashNextPhishingIncidentResponse/SlashNextPhishingIncidentResponse_description.md
  Packs/SlashNextPhishingIncidentResponse/ReleaseNotes/1_3_5.md
  Packs/SlashNextPhishingIncidentResponse/pack_metadata.json
  Packs/SymantecBlueCoatMalwareAnalysis/Integrations/SymantecBlueCoatMalwareAnalysis/README.md
  Packs/SymantecBlueCoatMalwareAnalysis/Integrations/SymantecBlueCoatMalwareAnalysis/SymantecBlueCoatMalwareAnalysis_description.md
  Packs/SymantecBlueCoatMalwareAnalysis/ReleaseNotes/1_0_9.md
  Packs/SymantecBlueCoatMalwareAnalysis/pack_metadata.json
  Packs/UrlScan/Integrations/UrlScan/README.md
  Packs/UrlScan/Integrations/UrlScan/UrlScan_description.md
  Packs/UrlScan/ReleaseNotes/1_2_9.md
  Packs/UrlScan/pack_metadata.json
  Packs/fireeye/Integrations/Fireeye/README.md
Labels: docs-approved

#27932 XSIAM CyberArkEPV ModelingRules
  Packs/CyberArkEPV/.pack-ignore
  Packs/CyberArkEPV/.secrets-ignore
  Packs/CyberArkEPV/ModelingRules/CyberArkEPV/CyberArkEPV.xif
  Packs/CyberArkEPV/ModelingRules/CyberArkEPV/CyberArkEPV.yml
  Packs/CyberArkEPV/ModelingRules/CyberArkEPV/CyberArkEPV_schema.json
  Packs/CyberArkEPV/ParsingRules/CyberArkEPV/CyberArkEPV.xif
  Packs/CyberArkEPV/ParsingRules/CyberArkEPV/CyberArkEPV.yml
  Packs/CyberArkEPV/README.md
  Packs/CyberArkEPV/doc_files/config_isotimestamp_mapping.png
  Packs/CyberArkEPV/pack_metadata.json
Labels: docs-approved

#28628 Cisco asa cnx events 2
  Packs/CiscoASA/ModelingRules/CiscoASA_1_4/CiscoASA_1_4.xif
  Packs/CiscoASA/README.md
  Packs/CiscoASA/ReleaseNotes/1_1_2.md
  Packs/CiscoASA/pack_metadata.json
Labels: docs-approved

#28815 fixed machines_locks path for removing the lock in bucket upload
  .gitlab/ci/.gitlab-ci.bucket-upload.yml
Labels: docs-approved

#28812 Cloud response azure fix
  Packs/Azure-Enrichment-Remediation/Playbooks/playbook-Cloud_Response_-_Azure.yml
  Packs/Azure-Enrichment-Remediation/ReleaseNotes/1_1_4.md
  Packs/Azure-Enrichment-Remediation/doc_files/Cloud_Response_-_Azure.png
  Packs/Azure-Enrichment-Remediation/pack_metadata.json
Labels: docs-approved

#28669 Qradar indicator hunting fix
  Packs/QRadar/Playbooks/playbook-QRadar_Indicator_Hunting_V2.yml
  Packs/QRadar/Playbooks/playbook-QRadar_Indicator_Hunting_V2_README.md
  Packs/QRadar/ReleaseNotes/2_4_30.md
  Packs/QRadar/doc_files/QRadar_Indicator_Hunting_V2.png
  Packs/QRadar/pack_metadata.json
Labels: docs-approved

#27963 Trend Micro Email Security (new pack)
  Packs/TrendMicroEmailSecurity/.pack-ignore
  Packs/TrendMicroEmailSecurity/.secrets-ignore
  Packs/TrendMicroEmailSecurity/Integrations/TrendMicroEmailSecurityEventCollector/README.md
  Packs/TrendMicroEmailSecurity/Integrations/TrendMicroEmailSecurityEventCollector/TrendMicroEmailSecurityEventCollector.py
  Packs/TrendMicroEmailSecurity/Integrations/TrendMicroEmailSecurityEventCollector/TrendMicroEmailSecurityEventCollector.yml
  Packs/TrendMicroEmailSecurity/Integrations/TrendMicroEmailSecurityEventCollector/TrendMicroEmailSecurityEventCollector_description.md
  Packs/TrendMicroEmailSecurity/Integrations/TrendMicroEmailSecurityEventCollector/TrendMicroEmailSecurityEventCollector_image.png
  Packs/TrendMicroEmailSecurity/Integrations/TrendMicroEmailSecurityEventCollector/TrendMicroEmailSecurityEventCollector_test.py
  Packs/TrendMicroEmailSecurity/Integrations/TrendMicroEmailSecurityEventCollector/test_data/test_events.json
  Packs/TrendMicroEmailSecurity/ModelingRules/TrendMicroEmailSecurityModelingRule/TrendMicroEmailSecurityModelingRule.xif
  Packs/TrendMicroEmailSecurity/ModelingRules/TrendMicroEmailSecurityModelingRule/TrendMicroEmailSecurityModelingRule.yml
  Packs/TrendMicroEmailSecurity/ModelingRules/TrendMicroEmailSecurityModelingRule/TrendMicroEmailSecurityModelingRule_schema.json
  Packs/TrendMicroEmailSecurity/README.md
  Packs/TrendMicroEmailSecurity/pack_metadata.json
Labels: docs-approved

#27742 Microsoft support of national clouds - Microsoft Graph API
  Packs/MicrosoftGraphAPI/.pack-ignore
  Packs/MicrosoftGraphAPI/Integrations/MicrosoftGraphAPI/MicrosoftGraphAPI.py
  Packs/MicrosoftGraphAPI/Integrations/MicrosoftGraphAPI/MicrosoftGraphAPI.yml
  Packs/MicrosoftGraphAPI/Integrations/MicrosoftGraphAPI/MicrosoftGraphAPI_test.py
  Packs/MicrosoftGraphAPI/Integrations/MicrosoftGraphAPI/README.md
  Packs/MicrosoftGraphAPI/ReleaseNotes/1_1_25.md
  Packs/MicrosoftGraphAPI/pack_metadata.json
Labels: docs-approved

#28802 Private upload mode - docs #7
  Packs/EclecticIQ/Integrations/EclecticIQ/EclecticIQ_description.md
  Packs/EclecticIQ/Integrations/EclecticIQ/README.md
  Packs/EclecticIQ/ReleaseNotes/2_0_13.md
  Packs/EclecticIQ/pack_metadata.json
  Packs/FireEye-Detection-on-Demand/Integrations/FireEye-Detection-on-Demand/FireEye-Detection-on-Demand_description.md
  Packs/FireEye-Detection-on-Demand/Integrations/FireEye-Detection-on-Demand/README.md
  Packs/FireEye-Detection-on-Demand/ReleaseNotes/1_0_4.md
  Packs/FireEye-Detection-on-Demand/pack_metadata.json
  Packs/FullHunt/Integrations/FullHunt/FullHunt_description.md
  Packs/FullHunt/Integrations/FullHunt/README.md
  Packs/FullHunt/ReleaseNotes/1_0_3.md
  Packs/FullHunt/pack_metadata.json
  Packs/GoogleSafeBrowsing/Integrations/GoogleSafeBrowsing/GoogleSafeBrowsing_description.md
  Packs/GoogleSafeBrowsing/Integrations/GoogleSafeBrowsing/README.md
  Packs/GoogleSafeBrowsing/Integrations/GoogleSafeBrowsingV2/GoogleSafeBrowsingV2_description.md
  Packs/GoogleSafeBrowsing/Integrations/GoogleSafeBrowsingV2/README.md
  Packs/GoogleSafeBrowsing/ReleaseNotes/2_0_20.md
  Packs/GoogleSafeBrowsing/pack_metadata.json
Labels: docs-approved

#28813 Private upload mode docs #8
  Packs/IPQualityScore/Integrations/IPQualityScore/IPQualityScore_description.md
  Packs/IPQualityScore/Integrations/IPQualityScore/README.md
  Packs/IPQualityScore/ReleaseNotes/1_0_8.md
  Packs/IPQualityScore/pack_metadata.json
  Packs/InfoArmor_VigilanteATI/Integrations/InfoArmorVigilanteATI/InfoArmorVigilanteATI_description.md
  Packs/InfoArmor_VigilanteATI/Integrations/InfoArmorVigilanteATI/README.md
  Packs/InfoArmor_VigilanteATI/ReleaseNotes/1_0_10.md
  Packs/InfoArmor_VigilanteATI/pack_metadata.json
  Packs/InfobloxBloxOne/.pack-ignore
  Packs/InfobloxBloxOne/Integrations/InfobloxBloxOneThreatDefense/InfobloxBloxOneThreatDefense_description.md
  Packs/InfobloxBloxOne/Integrations/InfobloxBloxOneThreatDefense/README.md
  Packs/InfobloxBloxOne/ReleaseNotes/1_1_8.md
  Packs/InfobloxBloxOne/pack_metadata.json
  Packs/MISP/Integrations/MISPV3/MISPV3_description.md
  Packs/MISP/Integrations/MISPV3/README.md
  Packs/MISP/Integrations/MISP_V2/MISP_V2_description.md
  Packs/MISP/Integrations/MISP_V2/README.md
  Packs/MISP/ReleaseNotes/2_1_30.md
  Packs/MISP/pack_metadata.json
  Packs/Maltiverse/Integrations/Maltiverse/Maltiverse_description.md
  Packs/Maltiverse/Integrations/Maltiverse/README.md
  Packs/Maltiverse/ReleaseNotes/1_0_24.md
  Packs/Maltiverse/pack_metadata.json
Labels: docs-approved

#28786 Proofpoint TAP v2: Fetch limit
  Packs/ProofpointTAP/Integrations/ProofpointTAP_v2/ProofpointTAP_v2.py
  Packs/ProofpointTAP/Integrations/ProofpointTAP_v2/ProofpointTAP_v2.yml
  Packs/ProofpointTAP/Integrations/ProofpointTAP_v2/README.md
  Packs/ProofpointTAP/ReleaseNotes/1_2_8.md
  Packs/ProofpointTAP/pack_metadata.json
Labels: docs-approved

#28829 remove non ignorable error from pack ignore
  Packs/Active_Directory_Query/.pack-ignore
  Packs/Base/.pack-ignore
  Packs/Campaign/.pack-ignore
  Packs/CommonTypes/.pack-ignore
  Packs/DeveloperTools/.pack-ignore
  Packs/ReversingLabs_TitaniumScale/.pack-ignore
Labels: docs-approved

#28791 Containment plan enhancement
  Packs/CommonPlaybooks/Playbooks/playbook-Containment_Plan.yml
  Packs/CommonPlaybooks/Playbooks/playbook-Containment_Plan_README.md
  Packs/CommonPlaybooks/ReleaseNotes/2_3_87.md
  Packs/CommonPlaybooks/pack_metadata.json
Labels: docs-approved

#28839 fix `AssignAnalystToAlert` to `AssignAnalystToIncident`
  Packs/CommonScripts/ReleaseNotes/1_12_12.md
  Packs/CommonScripts/Scripts/AssignAnalystToIncident/AssignAnalystToIncident.yml
  Packs/CommonScripts/pack_metadata.json
Labels: ForceMerge

#28835 Private upload mode docs #9
  Packs/MxToolBox/Integrations/MxToolBox/MxToolBox_description.md
  Packs/MxToolBox/Integrations/MxToolBox/README.md
  Packs/MxToolBox/ReleaseNotes/1_0_3.md
  Packs/MxToolBox/pack_metadata.json
  Packs/PassiveTotal/Integrations/PassiveTotal_v2/PassiveTotal_v2_description.md
  Packs/PassiveTotal/Integrations/PassiveTotal_v2/README.md
  Packs/PassiveTotal/ReleaseNotes/2_1_11.md
  Packs/PassiveTotal/pack_metadata.json
  Packs/PhishTank/Integrations/PhishTankV2/PhishTankV2_description.md
  Packs/PhishTank/Integrations/PhishTankV2/README.md
  Packs/PhishTank/ReleaseNotes/2_0_27.md
  Packs/PhishTank/pack_metadata.json
  Packs/PolySwarm/Integrations/PolySwarmV2/PolySwarmV2_description.md
  Packs/PolySwarm/Integrations/PolySwarmV2/README.md
  Packs/PolySwarm/ReleaseNotes/2_0_5.md
  Packs/PolySwarm/pack_metadata.json
  Packs/Pulsedive/Integrations/Pulsedive/Pulsedive_description.md
  Packs/Pulsedive/Integrations/Pulsedive/README.md
  Packs/Pulsedive/ReleaseNotes/1_6_5.md
  Packs/Pulsedive/pack_metadata.json
Labels: docs-approved

#28836 Private upload mode docs #10
  Packs/Pwned/Integrations/PwnedV2/PwnedV2_description.md
  Packs/Pwned/Integrations/PwnedV2/README.md
  Packs/Pwned/ReleaseNotes/1_0_11.md
  Packs/Pwned/pack_metadata.json
  Packs/ReversingLabs_Titanium_Cloud/Integrations/ReversingLabsTitaniumCloudv2/README.md
  Packs/ReversingLabs_Titanium_Cloud/Integrations/ReversingLabsTitaniumCloudv2/ReversingLabsTitaniumCloudv2_description.md
  Packs/ReversingLabs_Titanium_Cloud/ReleaseNotes/2_1_1.md
  Packs/ReversingLabs_Titanium_Cloud/pack_metadata.json
  Packs/SEKOIAIntelligenceCenter/Integrations/SEKOIAIntelligenceCenter/README.md
  Packs/SEKOIAIntelligenceCenter/Integrations/SEKOIAIntelligenceCenter/SEKOIAIntelligenceCenter_description.md
  Packs/SEKOIAIntelligenceCenter/ReleaseNotes/1_2_13.md
  Packs/SEKOIAIntelligenceCenter/pack_metadata.json
  Packs/SecurityTrails/Integrations/SecurityTrails/README.md
  Packs/SecurityTrails/Integrations/SecurityTrails/SecurityTrails_description.md
  Packs/SecurityTrails/ReleaseNotes/1_1_6.md
  Packs/SecurityTrails/pack_metadata.json
  Packs/Sixgill-Darkfeed/.pack-ignore
  Packs/Sixgill-Darkfeed/Integrations/Sixgill_Darkfeed_Enrichment/README.md
  Packs/Sixgill-Darkfeed/Integrations/Sixgill_Darkfeed_Enrichment/Sixgill_Darkfeed_Enrichment_description.md
  Packs/Sixgill-Darkfeed/ReleaseNotes/2_2_5.md
  Packs/Sixgill-Darkfeed/pack_metadata.json
Labels: docs-approved

#28698 Validate sync marketplaces
  .gitlab/ci/.gitlab-ci.bucket-upload.yml
  Tests/scripts/validate_synced_buckets.sh
Labels: docs-approved

#28845 added loggings for unsuccessful processes
  Tests/Marketplace/search_and_uninstall_pack.py
Labels: ForceMerge

#28851 AWS Guardduty Fix
  Packs/AWS-GuardDuty/ParsingRules/AWS-GuardDuty/AWS-GuardDuty.xif
  Packs/AWS-GuardDuty/ReleaseNotes/1_3_28.md
  Packs/AWS-GuardDuty/pack_metadata.json
Labels: docs-approved

#28743 [OpsGenie] get alert logs
  Packs/OpsGenie/Integrations/OpsGenieV3/OpsGenieV3.py
  Packs/OpsGenie/Integrations/OpsGenieV3/OpsGenieV3.yml
  Packs/OpsGenie/Integrations/OpsGenieV3/OpsGenieV3_test.py
  Packs/OpsGenie/Integrations/OpsGenieV3/test_data/add_alert_details.json
  Packs/OpsGenie/Integrations/OpsGenieV3/test_data/add_alert_note.json
  Packs/OpsGenie/Integrations/OpsGenieV3/test_data/get_alert_logs.json
  Packs/OpsGenie/ReleaseNotes/2_0_18.md
  Packs/OpsGenie/pack_metadata.json
Labels: Contribution, Contribution Form Filled, Community, Xsoar Support Level, External PR

#28819 Setting the NG step as required
  .gitlab/ci/.gitlab-ci.on-push.yml
Labels: docs-approved

#28710 [TAXII 2 Feed] Remove default list of objects types
  Packs/ApiModules/Scripts/TAXII2ApiModule/TAXII2ApiModule.py
  Packs/ApiModules/Scripts/TAXII2ApiModule/TAXII2ApiModule_test.py
  Packs/FeedDHS/ReleaseNotes/2_0_18.md
  Packs/FeedDHS/pack_metadata.json
  Packs/FeedMitreAttackv2/ReleaseNotes/1_1_21.md
  Packs/FeedMitreAttackv2/pack_metadata.json
  Packs/FeedTAXII/Integrations/FeedTAXII2/FeedTAXII2.py
  Packs/FeedTAXII/Integrations/FeedTAXII2/FeedTAXII2.yml
  Packs/FeedTAXII/ReleaseNotes/1_1_32.md
  Packs/FeedTAXII/pack_metadata.json
Labels: docs-approved

#28847 Modified the mapping for team viewer
  Packs/TeamViewer/ModelingRules/TeamViewer/TeamViewer.xif
  Packs/TeamViewer/ReleaseNotes/1_0_5.md
  Packs/TeamViewer/pack_metadata.json
Labels: docs-approved

#28712 Xsup 26357/fortisiem v2 fetch incidents
  Packs/FortiSIEM/Integrations/FortiSIEMV2/FortiSIEMV2.py
  Packs/FortiSIEM/Integrations/FortiSIEMV2/FortiSIEMV2.yml
  Packs/FortiSIEM/Integrations/FortiSIEMV2/FortiSIEMV2_test.py
  Packs/FortiSIEM/ReleaseNotes/2_0_17.md
  Packs/FortiSIEM/pack_metadata.json
Labels: docs-approved

#28850 ConvertFile Doc
  Packs/CommonScripts/Scripts/ConvertFile/README.md
Labels: docs-approved

#28456 Elasticsearch datetime format
  Packs/Elasticsearch/Integrations/Elasticsearch_v2/Elasticsearch_v2.py
  Packs/Elasticsearch/Integrations/Elasticsearch_v2/Elasticsearch_v2.yml
  Packs/Elasticsearch/Integrations/Elasticsearch_v2/Elasticsearch_v2_test.py
  Packs/Elasticsearch/ReleaseNotes/1_3_13.md
  Packs/Elasticsearch/pack_metadata.json
Labels: docs-approved

#28301 Enabling auto bump mechanism for contributions PRs
  Tests/Marketplace/marketplace_constants.py
  Utils/github_workflow_scripts/autobump_release_notes/skip_conditions.py
  Utils/github_workflow_scripts/github_workflow_scripts_tests/autobump_rn_test.py
Labels: docs-approved

#28755 Usecasebuildermodifications
  Packs/Use_Case_Builder/.secrets-ignore
  Packs/Use_Case_Builder/IncidentFields/incidentfield-Network_Security_IDS.json
  Packs/Use_Case_Builder/IncidentFields/incidentfield-Use_Case_Builder_Authentication.json
  Packs/Use_Case_Builder/IncidentFields/incidentfield-Use_Case_Builder_Data_Enrichment_and_Threat_Intelligence.json
  Packs/Use_Case_Builder/IncidentFields/incidentfield-Use_Case_Builder_Endpoint.json
  Packs/Use_Case_Builder/IncidentFields/incidentfield-Use_Case_Builder_Forensics_and_Malware_Analysis.json
  Packs/Use_Case_Builder/IncidentFields/incidentfield-Use_Case_Builder_Getting_Started.json
  Packs/Use_Case_Builder/IncidentFields/incidentfield-Use_Case_Builder_SEIM.json
  Packs/Use_Case_Builder/IncidentFields/incidentfield-Use_Case_Category.json
  Packs/Use_Case_Builder/Layouts/layoutscontainer-Use_Case_Builder.json
  Packs/Use_Case_Builder/Playbooks/Create_Use_Case_Steps_List.yml
  Packs/Use_Case_Builder/Playbooks/Create_Use_Case_Template_List.yml
  Packs/Use_Case_Builder/Playbooks/Create_XSOAR_Incident_Flow_List.yml
  Packs/Use_Case_Builder/Playbooks/Entity_Enrichment_-_Generic_v4.yml
  Packs/Use_Case_Builder/Playbooks/Entity_Enrichment_-_Generic_v4_README.md
  Packs/Use_Case_Builder/Playbooks/Generate_Playbooks_Based_On_Category.yml
  Packs/Use_Case_Builder/Playbooks/Generate_Use_Case_Builder_Lists.yml
  Packs/Use_Case_Builder/Playbooks/Quick_Start_Investigation.yml
  Packs/Use_Case_Builder/Playbooks/Quick_Start_Main_Playbook.yml
  Packs/Use_Case_Builder/Playbooks/Quick_Start_Remediation.yml
  Packs/Use_Case_Builder/Playbooks/Setting_up_the_Use_Case_Builder_Content.yml
  Packs/Use_Case_Builder/Playbooks/Use_Case_Builder.yml
  Packs/Use_Case_Builder/Playbooks/Use_Case_Builder_Playbook_Reset.yml
  Packs/Use_Case_Builder/README.md
  Packs/Use_Case_Builder/ReleaseNotes/1_0_2.md
  Packs/Use_Case_Builder/Scripts/CreateUseCaseTemplateList/CreateUseCaseTemplateList.py
  Packs/Use_Case_Builder/Scripts/CreateUseCaseTemplateList/CreateUseCaseTemplateList.yml
  Packs/Use_Case_Builder/Scripts/UseCaseAdoptionMetrics/UseCaseAdoptionMetrics.py
  Packs/Use_Case_Builder/Scripts/UseCaseAdoptionMetrics/UseCaseAdoptionMetrics.yml
  Packs/Use_Case_Builder/doc_files/Entity_Enrichment_-_Generic_v4.png
  Packs/Use_Case_Builder/doc_files/usecasebuilder.png
  Packs/Use_Case_Builder/pack_metadata.json
Labels: Contribution, Contribution Form Filled, Community, Community Support Level, External PR, Security Review

#28859 [CortexCoreIR] change the "email" argument of core-report-incorrect-wildfire
  Packs/Core/Integrations/CortexCoreIR/CortexCoreIR.yml
  Packs/Core/ReleaseNotes/2_0_5.json
  Packs/Core/ReleaseNotes/2_0_5.md
  Packs/Core/pack_metadata.json
Labels: ForceMerge

#28867 [ProofPoint Tap v2] Fix '<' is not supported
  Packs/ProofpointTAP/Integrations/ProofpointTAP_v2/ProofpointTAP_v2.py
  Packs/ProofpointTAP/ReleaseNotes/1_2_9.md
  Packs/ProofpointTAP/pack_metadata.json
Labels: docs-approved

#27236 Initial Checkin - Content Pack - Commvault Security IQ
  Packs/CommvaultSecurityIQ/.pack-ignore
  Packs/CommvaultSecurityIQ/.secrets-ignore
  Packs/CommvaultSecurityIQ/Author_image.png
  Packs/CommvaultSecurityIQ/Classifiers/classifier-Suspicious_File_Activity_Mapper.json
  Packs/CommvaultSecurityIQ/IncidentFields/incidentfield-Affected_Files_Count.json
  Packs/CommvaultSecurityIQ/IncidentFields/incidentfield-Created_Files_Count.json
  Packs/CommvaultSecurityIQ/IncidentFields/incidentfield-Deleted_Files_Count.json
  Packs/CommvaultSecurityIQ/IncidentFields/incidentfield-Event_Time.json
  Packs/CommvaultSecurityIQ/IncidentFields/incidentfield-Files_List.json
  Packs/CommvaultSecurityIQ/IncidentFields/incidentfield-Job_Id.json
  Packs/CommvaultSecurityIQ/IncidentFields/incidentfield-Modified_Files_Count.json
  Packs/CommvaultSecurityIQ/IncidentFields/incidentfield-Originating_Client.json
  Packs/CommvaultSecurityIQ/IncidentFields/incidentfield-Originating_Program.json
  Packs/CommvaultSecurityIQ/IncidentFields/incidentfield-Renamed_Files_Count.json
  Packs/CommvaultSecurityIQ/IncidentFields/incidentfield-Scanned_Folder_List.json
  Packs/CommvaultSecurityIQ/IncidentTypes/incidenttype-Suspicious_File_Activity.json
  Packs/CommvaultSecurityIQ/Integrations/CommvaultSecurityIQ/CommvaultSecurityIQ.py
  Packs/CommvaultSecurityIQ/Integrations/CommvaultSecurityIQ/CommvaultSecurityIQ.yml
  Packs/CommvaultSecurityIQ/Integrations/CommvaultSecurityIQ/CommvaultSecurityIQ_description.md
  Packs/CommvaultSecurityIQ/Integrations/CommvaultSecurityIQ/CommvaultSecurityIQ_image.png
  Packs/CommvaultSecurityIQ/Integrations/CommvaultSecurityIQ/CommvaultSecurityIQ_test.py
  Packs/CommvaultSecurityIQ/Integrations/CommvaultSecurityIQ/README.md
  Packs/CommvaultSecurityIQ/Integrations/CommvaultSecurityIQ/command_examples
  Packs/CommvaultSecurityIQ/Layouts/layoutscontainer-Suspicious_File_Activity_Layout.json
  Packs/CommvaultSecurityIQ/Playbooks/playbook-Suspicious_File_Activity_Remediation.yml
  Packs/CommvaultSecurityIQ/Playbooks/playbook-Suspicious_File_Activity_Remediation_README.md
  Packs/CommvaultSecurityIQ/README.md
  Packs/CommvaultSecurityIQ/pack_metadata.json
Labels: Contribution, Partner, ready-for-instance-test, post-demo, Contribution Form Filled, pending-contributor, Partner Support Level

#27700 PAN-OS - DNS Sinkhole
  Packs/PAN-OS/Playbooks/PAN-OS_-_Add_Anti-Spyware_Security_Profile_To_Rule.yml
  Packs/PAN-OS/Playbooks/PAN-OS_-_Add_Anti-Spyware_Security_Profile_To_Rule_README.md
  Packs/PAN-OS/Playbooks/PAN-OS_-_Configure_DNS_Sinkhole.yml
  Packs/PAN-OS/Playbooks/PAN-OS_-_Configure_DNS_Sinkhole_README.md
  Packs/PAN-OS/Playbooks/PAN-OS_-_Extract_IPs_From_Traffic_Logs_To_Sinkhole.yml
  Packs/PAN-OS/Playbooks/PAN-OS_-_Extract_IPs_From_Traffic_Logs_To_Sinkhole_README.md
  Packs/PAN-OS/ReleaseNotes/2_0_0.md
  Packs/PAN-OS/TestPlaybooks/PAN-OS_-_Add_Anti-Spyware_Security_Profile_To_Rule_-_Test.yml
  Packs/PAN-OS/doc_files/PAN-OS_-_Add_Anti-Spyware_Security_Profile_To_Rule.png
  Packs/PAN-OS/doc_files/PAN-OS_-_Configure_DNS_Sinkhole.png
  Packs/PAN-OS/doc_files/PAN-OS_-_Extract_IPs_From_Traffic_Logs_To_Sinkhole.png
  Packs/PAN-OS/pack_metadata.json
  Tests/conf.json
Labels: docs-approved

#28803 [CreateNewInidcatorsOnly] escaped_value before calling findIndicators
  Packs/CommonScripts/ReleaseNotes/1_12_13.md
  Packs/CommonScripts/Scripts/CreateNewIndicatorsOnly/CreateNewIndicatorsOnly.py
  Packs/CommonScripts/Scripts/CreateNewIndicatorsOnly/CreateNewIndicatorsOnly.yml
  Packs/CommonScripts/Scripts/CreateNewIndicatorsOnly/CreateNewIndicatorsOnly_test.py
  Packs/CommonScripts/pack_metadata.json
Labels: docs-approved

#28657 Support dynamic dashboard svg images in upload-flow
  Tests/Marketplace/Tests/marketplace_services_test.py
  Tests/Marketplace/copy_and_upload_packs.py
  Tests/Marketplace/marketplace_constants.py
  Tests/Marketplace/marketplace_services.py
  Tests/Marketplace/upload_packs.py
Labels: docs-approved

#28457 Fix: Fix getting file from Linux endpoints
  Packs/Carbon_Black_Enterprise_Live_Response/Integrations/Carbonblackliveresponse/Carbonblackliveresponse.js
  Packs/Carbon_Black_Enterprise_Live_Response/ReleaseNotes/1_1_6.md
  Packs/Carbon_Black_Enterprise_Live_Response/pack_metadata.json
Labels: Contribution, ready-for-instance-test, Contribution Form Filled, Community, Xsoar Support Level, External PR

#28884 search and install packs error message from NG contains invalid response
  Tests/Marketplace/search_and_install_packs.py
Labels: docs-approved, ForceMerge

#28864 Fix destroy services to consider successful runs
  Tests/configure_and_test_integration_instances.py
  Tests/scripts/destroy_instances.py
  Tests/scripts/run_tests.sh
Labels: docs-approved, ForceMerge

#28428 Carbon Black EDR (Live Response API): fix get file issue on Linux
  Packs/Carbon_Black_Enterprise_Live_Response/Integrations/Carbonblackliveresponse/Carbonblackliveresponse.js
  Packs/Carbon_Black_Enterprise_Live_Response/ReleaseNotes/1_1_6.md
  Packs/Carbon_Black_Enterprise_Live_Response/pack_metadata.json
Labels: docs-approved

#28886 changed link to redirect
  Packs/Neosec/.secrets-ignore
  Packs/Neosec/README.md
Labels: docs-approved

#28358 Reversing labs v2.2.0
  Packs/ReversingLabs_A1000/Integrations/ReversingLabsA1000v2/ReversingLabsA1000v2.py
  Packs/ReversingLabs_A1000/Integrations/ReversingLabsA1000v2/ReversingLabsA1000v2.yml
  Packs/ReversingLabs_A1000/Playbooks/File_Analysis_-_ReversingLabs_A1000.yml
  Packs/ReversingLabs_A1000/Playbooks/File_Analysis_-_ReversingLabs_A1000_README.md
  Packs/ReversingLabs_A1000/ReleaseNotes/2_2_0.md
  Packs/ReversingLabs_A1000/doc_files/File_Analysis_-_ReversingLabs_A1000.png
  Packs/ReversingLabs_A1000/pack_metadata.json
  Packs/ReversingLabs_Titanium_Cloud/Integrations/ReversingLabsTitaniumCloudv2/ReversingLabsTitaniumCloudv2.py
  Packs/ReversingLabs_Titanium_Cloud/Integrations/ReversingLabsTitaniumCloudv2/ReversingLabsTitaniumCloudv2.yml
  Packs/ReversingLabs_Titanium_Cloud/Playbooks/URL_Reputation_-_ReversingLabs_TitaniumCloud.yml
  Packs/ReversingLabs_Titanium_Cloud/Playbooks/URL_Reputation_-_ReversingLabs_TitaniumCloud_README.md
  Packs/ReversingLabs_Titanium_Cloud/ReleaseNotes/2_2_0.md
  Packs/ReversingLabs_Titanium_Cloud/doc_files/URL_Reputation_-_ReversingLabs_TitaniumCloud.png
  Packs/ReversingLabs_Titanium_Cloud/pack_metadata.json
Labels: Contribution, docs-approved, Partner, ready-for-instance-test, post-demo, Contribution Form Filled, Partner Support Level, External PR, Security Review

#28895 [native-image] - skip FindEmailCampaign
  Tests/docker_native_image_config.json
Labels: docs-approved

#28896 Cisco Catalyst Update
  Packs/CiscoCatalyst/pack_metadata.json
Labels: docs-approved

#28888 Semperis Update
  Packs/SemperisDSP/ModelingRules/SemperisDSP/SemperisDSP.xif
  Packs/SemperisDSP/ParsingRules/SemperisDSP/SemperisDSP.xif
  Packs/SemperisDSP/ParsingRules/SemperisDSP/SemperisDSP.yml
  Packs/SemperisDSP/README.md
  Packs/SemperisDSP/ReleaseNotes/1_0_1.md
  Packs/SemperisDSP/pack_metadata.json
Labels: docs-approved

#28844 Microsoft Windows AMSI Mapping
  Packs/MicrosoftWindowsAMSI/.pack-ignore
  Packs/MicrosoftWindowsAMSI/.secrets-ignore
  Packs/MicrosoftWindowsAMSI/ModelingRules/MicrosoftWindowsAMSI/MicrosoftWindowsAMSI.xif
  Packs/MicrosoftWindowsAMSI/ModelingRules/MicrosoftWindowsAMSI/MicrosoftWindowsAMSI.yml
  Packs/MicrosoftWindowsAMSI/ModelingRules/MicrosoftWindowsAMSI/MicrosoftWindowsAMSI_schema.json
  Packs/MicrosoftWindowsAMSI/ParsingRules/MicrosoftWindowsAMSI/MicrosoftWindowsAMSI.xif
  Packs/MicrosoftWindowsAMSI/ParsingRules/MicrosoftWindowsAMSI/MicrosoftWindowsAMSI.yml
  Packs/MicrosoftWindowsAMSI/README.md
  Packs/MicrosoftWindowsAMSI/pack_metadata.json
  Packs/MicrosoftWindowsEvents/ParsingRules/MicrosoftWindowsEvents/MicrosoftWindowsEvents.xif
  Packs/MicrosoftWindowsEvents/ReleaseNotes/1_0_8.md
  Packs/MicrosoftWindowsEvents/pack_metadata.json
Labels: docs-approved

#27525 [mimecast] use queried fields
  Packs/Mimecast/Integrations/MimecastV2/MimecastV2.py
  Packs/Mimecast/Integrations/MimecastV2/MimecastV2.yml
  Packs/Mimecast/Integrations/MimecastV2/MimecastV2_test.py
  Packs/Mimecast/Integrations/MimecastV2/test_data/query_response.json
  Packs/Mimecast/ReleaseNotes/2_2_0.md
  Packs/Mimecast/pack_metadata.json
Labels: docs-approved

#28885 Panorama get address group command fix
  Packs/PAN-OS/Integrations/Panorama/Panorama.py
  Packs/PAN-OS/Integrations/Panorama/Panorama.yml
  Packs/PAN-OS/ReleaseNotes/2_1_1.md
  Packs/PAN-OS/pack_metadata.json
Labels: docs-approved, ForceMerge

#28873 [ASM] - Expander - Lowercase GridField Keys
  Packs/CortexAttackSurfaceManagement/Playbooks/Cortex_ASM_-_ASM_Alert.yml
  Packs/CortexAttackSurfaceManagement/Playbooks/Cortex_ASM_-_ASM_Alert_README.md
  Packs/CortexAttackSurfaceManagement/Playbooks/Cortex_ASM_-_AWS_Enrichment.yml
  Packs/CortexAttackSurfaceManagement/Playbooks/Cortex_ASM_-_Azure_Enrichment.yml
  Packs/CortexAttackSurfaceManagement/Playbooks/Cortex_ASM_-_Detect_Service.yml
  Packs/CortexAttackSurfaceManagement/Playbooks/Cortex_ASM_-_Detect_Service_README.md
  Packs/CortexAttackSurfaceManagement/Playbooks/Cortex_ASM_-_Email_Notification.yml
  Packs/CortexAttackSurfaceManagement/Playbooks/Cortex_ASM_-_Enrichment.yml
  Packs/CortexAttackSurfaceManagement/Playbooks/Cortex_ASM_-_GCP_Enrichment.yml
  Packs/CortexAttackSurfaceManagement/Playbooks/Cortex_ASM_-_Jira_Notification.yml
  Packs/CortexAttackSurfaceManagement/Playbooks/Cortex_ASM_-_Prisma_Cloud_Enrichment.yml
  Packs/CortexAttackSurfaceManagement/Playbooks/Cortex_ASM_-_Qualys_Enrichment.yml
  Packs/CortexAttackSurfaceManagement/Playbooks/Cortex_ASM_-_Rapid7_Enrichment.yml
  Packs/CortexAttackSurfaceManagement/Playbooks/Cortex_ASM_-_Remediation.yml
  Packs/CortexAttackSurfaceManagement/Playbooks/Cortex_ASM_-_Remediation_Confirmation_Scan.yml
  Packs/CortexAttackSurfaceManagement/Playbooks/Cortex_ASM_-_Remediation_Objectives.yml
  Packs/CortexAttackSurfaceManagement/Playbooks/Cortex_ASM_-_Remediation_Path_Rules.yml
  Packs/CortexAttackSurfaceManagement/Playbooks/Cortex_ASM_-_ServiceNow_CMDB_Enrichment.yml
  Packs/CortexAttackSurfaceManagement/Playbooks/Cortex_ASM_-_ServiceNow_Notification.yml
  Packs/CortexAttackSurfaceManagement/Playbooks/Cortex_ASM_-_Service_Ownership.yml
  Packs/CortexAttackSurfaceManagement/Playbooks/Cortex_ASM_-_Splunk_Enrichment.yml
  Packs/CortexAttackSurfaceManagement/Playbooks/Cortex_ASM_-_Tenable.io_Enrichment.yml
  Packs/CortexAttackSurfaceManagement/ReleaseNotes/1_6_30.md
  Packs/CortexAttackSurfaceManagement/Scripts/GenerateASMReport/GenerateASMReport.py
  Packs/CortexAttackSurfaceManagement/Scripts/GenerateASMReport/GenerateASMReport.yml
  Packs/CortexAttackSurfaceManagement/Scripts/GenerateASMReport/test_data/args.json
  Packs/CortexAttackSurfaceManagement/Scripts/InferWhetherServiceIsDev/InferWhetherServiceIsDev.py
  Packs/CortexAttackSurfaceManagement/Scripts/InferWhetherServiceIsDev/InferWhetherServiceIsDev.yml
  Packs/CortexAttackSurfaceManagement/Scripts/InferWhetherServiceIsDev/InferWhetherServiceIsDev_test.py
  Packs/CortexAttackSurfaceManagement/Scripts/RankServiceOwners/RankServiceOwners.py
  Packs/CortexAttackSurfaceManagement/Scripts/RankServiceOwners/RankServiceOwners.yml
  Packs/CortexAttackSurfaceManagement/Scripts/RankServiceOwners/RankServiceOwners_test.py
  Packs/CortexAttackSurfaceManagement/Scripts/RemediationPathRuleEvaluation/RemediationPathRuleEvaluation.py
  Packs/CortexAttackSurfaceManagement/Scripts/RemediationPathRuleEvaluation/RemediationPathRuleEvaluation.yml
  Packs/CortexAttackSurfaceManagement/Scripts/RemediationPathRuleEvaluation/RemediationPathRuleEvaluation_test.py
  Packs/CortexAttackSurfaceManagement/pack_metadata.json
Labels: Contribution, docs-approved, Contribution Form Filled, Community, Xsoar Support Level, External PR, Security Review

#28911 EDL HA Doc
  Packs/EDL/Integrations/EDL/EDL_description.md
  Packs/EDL/ReleaseNotes/3_2_7.md
  Packs/EDL/pack_metadata.json
Labels: docs-approved

#28897 Usecasebuildermodifications
  Packs/Use_Case_Builder/README.md
  Packs/Use_Case_Builder/doc_files/ucbmain.png
Labels: Contribution, Contribution Form Filled, Community, Community Support Level, External PR

#28821 Cisco asa cnx events 3
  Packs/CiscoASA/ModelingRules/CiscoASA_1_4/CiscoASA_1_4.xif
  Packs/CiscoASA/README.md
  Packs/CiscoASA/ReleaseNotes/1_1_3.md
  Packs/CiscoASA/pack_metadata.json
Labels: docs-approved

#28747 XDRIR headers calculation before API call
  Packs/CortexXDR/Integrations/CortexXDRIR/CortexXDRIR.py
  Packs/CortexXDR/Integrations/CortexXDRIR/CortexXDRIR.yml
  Packs/CortexXDR/Integrations/CortexXDRIR/CortexXDRIR_test.py
  Packs/CortexXDR/ReleaseNotes/5_0_7.md
  Packs/CortexXDR/pack_metadata.json
Labels: docs-approved, ForceMerge

#28775 Update CrowdStrikeFalconX.py to fix pop_polling_related_args
  Packs/CrowdStrikeFalconX/Integrations/CrowdStrikeFalconX/CrowdStrikeFalconX.py
  Packs/CrowdStrikeFalconX/Integrations/CrowdStrikeFalconX/CrowdStrikeFalconX.yml
  Packs/CrowdStrikeFalconX/ReleaseNotes/1_2_34.md
  Packs/CrowdStrikeFalconX/pack_metadata.json
Labels: Contribution, ready-for-instance-test, Contribution Form Filled, Community, Xsoar Support Level, External PR

#28883 [MS Teams] updated error_parser
  Packs/MicrosoftTeams/Integrations/MicrosoftTeams/MicrosoftTeams.py
  Packs/MicrosoftTeams/Integrations/MicrosoftTeams/MicrosoftTeams.yml
  Packs/MicrosoftTeams/ReleaseNotes/1_4_28.md
  Packs/MicrosoftTeams/pack_metadata.json
Labels: docs-approved

#27969 Update ZeroFox Integration
  Packs/ZeroFox/.pack-ignore
  Packs/ZeroFox/Author_image.png
  Packs/ZeroFox/Classifiers/classifier-ZeroFox_Mapping.json
  Packs/ZeroFox/Integrations/ZeroFox/README.md
  Packs/ZeroFox/Integrations/ZeroFox/TestData/alert.json
  Packs/ZeroFox/Integrations/ZeroFox/TestData/alert_result.json
  Packs/ZeroFox/Integrations/ZeroFox/TestData/contents_result.json
  Packs/ZeroFox/Integrations/ZeroFox/ZeroFox.py
  Packs/ZeroFox/Integrations/ZeroFox/ZeroFox.yml
  Packs/ZeroFox/Integrations/ZeroFox/ZeroFox_description.md
  Packs/ZeroFox/Integrations/ZeroFox/ZeroFox_test.py
  Packs/ZeroFox/Integrations/ZeroFox/test_data/alerts/change_tags.json
  Packs/ZeroFox/Integrations/ZeroFox/test_data/alerts/closed_alert.json
  Packs/ZeroFox/Integrations/ZeroFox/test_data/alerts/list_10_records.json
  Packs/ZeroFox/Integrations/ZeroFox/test_data/alerts/list_10_records_and_more.json
  Packs/ZeroFox/Integrations/ZeroFox/test_data/alerts/list_no_records.json
  Packs/ZeroFox/Integrations/ZeroFox/test_data/alerts/opened_alert.json
  Packs/ZeroFox/Integrations/ZeroFox/test_data/alerts/submit_threat.json
  Packs/ZeroFox/Integrations/ZeroFox/test_data/cti/botnet-compromised-credentials.json
  Packs/ZeroFox/Integrations/ZeroFox/test_data/cti/botnet.json
  Packs/ZeroFox/Integrations/ZeroFox/test_data/cti/c2-domains.json
  Packs/ZeroFox/Integrations/ZeroFox/test_data/cti/compromised-credentials.json
  Packs/ZeroFox/Integrations/ZeroFox/test_data/cti/email-addresses.json
  Packs/ZeroFox/Integrations/ZeroFox/test_data/cti/exploits.json
  Packs/ZeroFox/Integrations/ZeroFox/test_data/cti/malware.json
  Packs/ZeroFox/Integrations/ZeroFox/test_data/cti/phishing.json
  Packs/ZeroFox/Integrations/ZeroFox/test_data/entities/create_entity.json
  Packs/ZeroFox/Integrations/ZeroFox/test_data/entities/entities_8_records.json
  Packs/ZeroFox/Integrations/ZeroFox/test_data/entities/entities_no_records.json
  Packs/ZeroFox/Integrations/ZeroFox/test_data/entities/entity_types_10_records.json
  Packs/ZeroFox/Integrations/ZeroFox/test_data/entities/entity_types_no_records.json
  Packs/ZeroFox/Integrations/ZeroFox/test_data/policies/policy_types_13_records.json
  Packs/ZeroFox/Integrations/ZeroFox/test_data/policies/policy_types_no_records.json
  Packs/ZeroFox/README.md
  Packs/ZeroFox/ReleaseNotes/1_1_0.md
  Packs/ZeroFox/pack_metadata.json
Labels: Contribution, Partner, ready-for-instance-test, Contribution Form Filled, pending-contributor, Xsoar Support Level

#23777 OpenCVE
  Packs/OpenCVE/.pack-ignore
  Packs/OpenCVE/.secrets-ignore
  Packs/OpenCVE/Integrations/OpenCVE/OpenCVE.py
  Packs/OpenCVE/Integrations/OpenCVE/OpenCVE.yml
  Packs/OpenCVE/Integrations/OpenCVE/OpenCVE_description.md
  Packs/OpenCVE/Integrations/OpenCVE/OpenCVE_image.png
  Packs/OpenCVE/Integrations/OpenCVE/OpenCVE_test.py
  Packs/OpenCVE/Integrations/OpenCVE/README.md
  Packs/OpenCVE/Integrations/OpenCVE/test_data/CVE-2019-0708.json
  Packs/OpenCVE/Integrations/OpenCVE/test_data/CVE-2021-26418.json
  Packs/OpenCVE/Integrations/OpenCVE/test_data/CVE-2021-28478.json
  Packs/OpenCVE/Integrations/OpenCVE/test_data/KLMHU9EB4N8C_alerts.json
  Packs/OpenCVE/Integrations/OpenCVE/test_data/NZSBGGBLW4TH_alerts.json
  Packs/OpenCVE/Integrations/OpenCVE/test_data/alert_475fde88-00dc-4024-9499-8197e334dfe7.json
  Packs/OpenCVE/Integrations/OpenCVE/test_data/alerts_KLMHU9EB4N8C.json
  Packs/OpenCVE/Integrations/OpenCVE/test_data/get_alerts_expected_outputs.json
  Packs/OpenCVE/Integrations/OpenCVE/test_data/get_cve_command_outputs.json
  Packs/OpenCVE/Integrations/OpenCVE/test_data/indicator.json
  Packs/OpenCVE/Integrations/OpenCVE/test_data/my_products.json
  Packs/OpenCVE/Integrations/OpenCVE/test_data/my_vendors.json
  Packs/OpenCVE/Integrations/OpenCVE/test_data/parsed_Cve.json
  Packs/OpenCVE/Integrations/OpenCVE/test_data/reports_response.json
  Packs/OpenCVE/Integrations/OpenCVE/test_data/single_report_response.json
  Packs/OpenCVE/Integrations/OpenCVE/test_data/vendors.json
  Packs/OpenCVE/Integrations/OpenCVE/test_data/vendors_specific_vendor.json
  Packs/OpenCVE/README.md
  Packs/OpenCVE/pack_metadata.json
Labels: Contribution, docs-approved, Contribution Form Filled, Community, pending-contributor

#28924 [VMRay] Change files permissions
  Packs/VMRay/Playbooks/playbook-VMRay-File-Enrichment.yml
  Packs/VMRay/Playbooks/playbook-VMRay-File-Enrichment_README.md
  Packs/VMRay/ReleaseNotes/1_1_1.md
  Packs/VMRay/TestPlaybooks/playbook-VMRay-test-File-Enrichment.yml
Labels: docs-approved, ForceMerge

#28862 [Nightly TPBs] Refactor generic-sql TPB
  Packs/GenericSQL/TestPlaybooks/generic-sql.yml
Labels: docs-approved, Allow auto bump

#27469 Removed the Default pack from XSIAM
  Packs/DefaultPlaybook/pack_metadata.json
Labels: docs-approved

#28912 Microsoft Defender Advanced Threat Protection - fix polling command
  Packs/MicrosoftDefenderAdvancedThreatProtection/Integrations/MicrosoftDefenderAdvancedThreatProtection/MicrosoftDefenderAdvancedThreatProtection.py
  Packs/MicrosoftDefenderAdvancedThreatProtection/Integrations/MicrosoftDefenderAdvancedThreatProtection/MicrosoftDefenderAdvancedThreatProtection.yml
  Packs/MicrosoftDefenderAdvancedThreatProtection/ReleaseNotes/1_16_2.md
  Packs/MicrosoftDefenderAdvancedThreatProtection/pack_metadata.json
Labels: docs-approved

#28483 Remove Tech Writer from Internal PR
  .github/content_roles.json
  Utils/github_workflow_scripts/create_internal_pr.py
  Utils/github_workflow_scripts/utils.py
  Utils/github_workflow_scripts/utils_test.py
Labels: docs-approved

#28922 Update versions-metadata.json
  Tests/Marketplace/versions-metadata.json
Labels: docs-approved

#28889 StringSimilarity return bugfix
  Packs/CommonScripts/ReleaseNotes/1_12_14.md
  Packs/CommonScripts/Scripts/StringSimilarity/StringSimilarity.py
  Packs/CommonScripts/Scripts/StringSimilarity/StringSimilarity.yml
  Packs/CommonScripts/Scripts/StringSimilarity/StringSimilarity_test.py
  Packs/CommonScripts/pack_metadata.json
Labels: docs-approved

#28936 Update core_packs_mpv2_list.json
  Tests/Marketplace/core_packs_mpv2_list.json
Labels: docs-approved, ForceMerge

#28920 Azure Sentinel: send the original owner in mirror
  Packs/AzureSentinel/Integrations/AzureSentinel/AzureSentinel.py
  Packs/AzureSentinel/Integrations/AzureSentinel/AzureSentinel.yml
  Packs/AzureSentinel/ReleaseNotes/1_5_16.md
  Packs/AzureSentinel/pack_metadata.json
Labels: docs-approved

#28923 Unskip MS Device Managment TPB
  Tests/conf.json
Labels: docs-approved

#28934 feature(IntezerV2)- add some commands. Support sending and retrieving…
  Packs/Intezer/Integrations/IntezerV2/IntezerV2.py
  Packs/Intezer/Integrations/IntezerV2/IntezerV2.yml
  Packs/Intezer/Integrations/IntezerV2/IntezerV2_test.py
  Packs/Intezer/Integrations/IntezerV2/README.md
  Packs/Intezer/ReleaseNotes/1_6_0.md
  Packs/Intezer/pack_metadata.json
  Tests/docker_native_image_config.json
Labels: Contribution, docs-approved, Partner, ready-for-instance-test, Contribution Form Filled, Partner Support Level, External PR

#28943 updated the reviewers and security architect
  .github/content_roles.json
Labels: docs-approved

#28933 update native:ga and skip slack
  Tests/docker_native_image_config.json
Labels: docs-approved

#28907 Detonate file crowdstrike fix
  Packs/CommonPlaybooks/Playbooks/playbook-Detonate_File_-_Generic.yml
  Packs/CommonPlaybooks/Playbooks/playbook-Detonate_File_-_Generic_README.md
  Packs/CommonPlaybooks/ReleaseNotes/2_3_89.md
  Packs/CommonPlaybooks/doc_files/Detonate_File_-_Generic.png
  Packs/CommonPlaybooks/pack_metadata.json
  Packs/CrowdStrikeFalconSandbox/Playbooks/playbook-Detonate_file_-_CrowdStrike_Falcon_Sandbox_v2.yml
  Packs/CrowdStrikeFalconSandbox/Playbooks/playbook-Detonate_file_-_CrowdStrike_Falcon_Sandbox_v2_README.md
  Packs/CrowdStrikeFalconSandbox/ReleaseNotes/2_0_17.md
  Packs/CrowdStrikeFalconSandbox/doc_files/Detonate_file_-_CrowdStrike_Falcon_Sandbox_v2.png
  Packs/CrowdStrikeFalconSandbox/pack_metadata.json
Labels: docs-approved

#28894 removed flaky checks from TPB
  Packs/CrowdStrikeFalcon/TestPlaybooks/playbook-CrowdStrikeFalcon-Test.yml
Labels: docs-approved

#28926 Optimize Find Similar Incidents
  Packs/Base/ReleaseNotes/1_32_27.md
  Packs/Base/Scripts/DBotFindSimilarIncidentsByIndicators/DBotFindSimilarIncidentsByIndicators.py
  Packs/Base/Scripts/DBotFindSimilarIncidentsByIndicators/DBotFindSimilarIncidentsByIndicators.yml
  Packs/Base/Scripts/DBotFindSimilarIncidentsByIndicators/DBotFindSimilarIncidentsByIndicators_test.py
  Packs/Base/pack_metadata.json
Labels: docs-approved

#28843 Cloud user investigation
  Packs/AWS-Enrichment-Remediation/Playbooks/playbook-AWS_-_User_Investigation.yml
  Packs/AWS-Enrichment-Remediation/Playbooks/playbook-AWS_-_User_Investigation_README.md
  Packs/AWS-Enrichment-Remediation/ReleaseNotes/1_1_3.md
  Packs/AWS-Enrichment-Remediation/doc_files/AWS_-_User_Investigation.png
  Packs/AWS-Enrichment-Remediation/pack_metadata.json
  Packs/Azure-Enrichment-Remediation/Playbooks/playbook-Azure_-_User_Investigation.yml
  Packs/Azure-Enrichment-Remediation/Playbooks/playbook-Azure_-_User_Investigation_README.md
  Packs/Azure-Enrichment-Remediation/ReleaseNotes/1_1_5.md
  Packs/Azure-Enrichment-Remediation/doc_files/Azure_-_User_Investigation.png
  Packs/Azure-Enrichment-Remediation/pack_metadata.json
  Packs/CommonPlaybooks/Playbooks/playbook-Cloud_User_Investigation_-_Generic.yml
  Packs/CommonPlaybooks/Playbooks/playbook-Cloud_User_Investigation_-_Generic_README.md
  Packs/CommonPlaybooks/ReleaseNotes/2_3_90.md
  Packs/CommonPlaybooks/doc_files/Cloud_User_Investigation_-_Generic.png
  Packs/CommonPlaybooks/pack_metadata.json
  Packs/GCP-Enrichment-Remediation/Playbooks/playbook-GCP_-_User_Investigation.yml
  Packs/GCP-Enrichment-Remediation/Playbooks/playbook-GCP_-_User_Investigation_README.md
  Packs/GCP-Enrichment-Remediation/ReleaseNotes/1_1_6.md
  Packs/GCP-Enrichment-Remediation/doc_files/GCP_-_User_Investigation.png
  Packs/GCP-Enrichment-Remediation/pack_metadata.json
Labels: docs-approved

#28954 remove mandatory dependancies for some packs
  Packs/BreachNotification-US/pack_metadata.json
  Packs/BruteForce/pack_metadata.json
  Packs/CortexDataLake/pack_metadata.json
  Packs/GDPR/pack_metadata.json
  Packs/HIPAA-BreachNotification/pack_metadata.json
  Packs/RiskIQDigitalFootprint/pack_metadata.json
  Packs/SANS/pack_metadata.json
  Packs/XSOARContentUpdateNotifications/pack_metadata.json
Labels: docs-approved

#28949 CyberarkEPV-CIAC-7862-fix-field-datatype-mismatch
  Packs/CyberArkEPV/ModelingRules/CyberArkEPV/CyberArkEPV_schema.json
  Packs/CyberArkEPV/ReleaseNotes/1_0_1.md
  Packs/CyberArkEPV/pack_metadata.json
Labels: docs-approved

#28874 Force handle htmlbody xsup 26821
  Packs/Gmail/Integrations/Gmail/Gmail.py
  Packs/Gmail/Integrations/Gmail/Gmail.yml
  Packs/Gmail/Integrations/Gmail/README.md
  Packs/Gmail/ReleaseNotes/1_3_13.md
  Packs/Gmail/pack_metadata.json
Labels: docs-approved

#28846 Microsoft Windows Events - Adding System Logs
  Packs/MicrosoftWindowsEvents/ModelingRules/MicrosoftWindowsEvents_1_3/MicrosoftWindowsEvents_1_3.xif
  Packs/MicrosoftWindowsEvents/README.md
  Packs/MicrosoftWindowsEvents/ReleaseNotes/1_0_9.md
  Packs/MicrosoftWindowsEvents/pack_metadata.json
Labels: docs-approved

#28946 ParseEmailsV2: update docker image
  Packs/CommonScripts/ReleaseNotes/1_12_15.md
  Packs/CommonScripts/Scripts/ParseEmailFilesV2/ParseEmailFilesV2.py
  Packs/CommonScripts/Scripts/ParseEmailFilesV2/ParseEmailFilesV2.yml
  Packs/CommonScripts/pack_metadata.json
Labels: docs-approved

#28972 deleting playbook-Intezer_-_scan_host from Intezer
  Packs/Intezer/Playbooks/playbook-Intezer_-_scan_host.yml
  Packs/Intezer/Playbooks/playbook-Intezer_-_scan_host_README.md
Labels: docs-approved, ForceMerge

#28908 [ASM] - Expander - August 2023 Bugs
  Packs/CortexAttackSurfaceManagement/Playbooks/Cortex_ASM_-_ASM_Alert.yml
  Packs/CortexAttackSurfaceManagement/Playbooks/Cortex_ASM_-_Prisma_Cloud_Enrichment.yml
  Packs/CortexAttackSurfaceManagement/ReleaseNotes/1_6_30.md
  Packs/CortexAttackSurfaceManagement/ReleaseNotes/1_6_31.md
  Packs/CortexAttackSurfaceManagement/doc_files/Cortex_ASM_-_ASM_Alert.png
  Packs/CortexAttackSurfaceManagement/doc_files/Cortex_ASM_-_Prisma_Cloud_Enrichment.png
  Packs/CortexAttackSurfaceManagement/pack_metadata.json
Labels: Contribution, docs-approved, ready-for-instance-test, Contribution Form Filled, Community, Xsoar Support Level, External PR, Security Review

#27370 Add API Execution Metrics to Whois
  Packs/Whois/.secrets-ignore
  Packs/Whois/Integrations/Whois/Whois.py
  Packs/Whois/Integrations/Whois/Whois.yml
  Packs/Whois/Integrations/Whois/Whois_test.py
  Packs/Whois/ReleaseNotes/1_5_0.json
  Packs/Whois/ReleaseNotes/1_5_0.md
  Packs/Whois/pack_metadata.json
  Tests/conf.json
Labels: docs-approved

#28981 Add analyze-nightly-logs script to Tests/scripts
  Tests/scripts/analyze_nightly_logs.py
Labels: docs-approved

#28918 Checkpoint vpn mapping enhancement
  Packs/CheckpointFirewall/ModelingRules/CheckpointFirewall_1_3/CheckpointFirewall_1_3.xif
  Packs/CheckpointFirewall/ModelingRules/CheckpointFirewall_1_3/CheckpointFirewall_1_3_schema.json
  Packs/CheckpointFirewall/ReleaseNotes/2_3_16.md
  Packs/CheckpointFirewall/pack_metadata.json
Labels: docs-approved

#28797 XSIAM-VMware-vCenter-Modeling-Enhancement-CIAC-7533
  Packs/VMwareVCenter/.pack-ignore
  Packs/VMwareVCenter/ModelingRules/VMwareVcenter_1_3/VMwareVcenter_1_3.xif
  Packs/VMwareVCenter/README.md
  Packs/VMwareVCenter/ReleaseNotes/1_0_10.md
  Packs/VMwareVCenter/pack_metadata.json
Labels: docs-approved

#29009 Mimecast everyone to everyone fix
  Packs/CommonPlaybooks/Playbooks/playbook-Block_Email_-_Generic_v2.yml
  Packs/CommonPlaybooks/ReleaseNotes/2_3_91.md
  Packs/CommonPlaybooks/doc_files/Block_Email_-_Generic_v2.png
  Packs/CommonPlaybooks/pack_metadata.json
Labels: docs-approved

#28978 [Discord] Add support for credentials (type 9)
  Packs/Discord/Integrations/Discord/Discord.py
  Packs/Discord/Integrations/Discord/Discord.yml
  Packs/Discord/ReleaseNotes/1_0_1.md
  Packs/Discord/pack_metadata.json
Labels: docs-approved

#28955 Taegisxdrv2 Investigations Hotfix
  Packs/SecureWorks/Integrations/TaegisXDRv2/TaegisXDRv2.py
  Packs/SecureWorks/Integrations/TaegisXDRv2/TaegisXDRv2.yml
  Packs/SecureWorks/ReleaseNotes/5_0_1.md
  Packs/SecureWorks/pack_metadata.json
Labels: Contribution, Partner, Contribution Form Filled, Partner Support Level, External PR

#29016 Commandline analysis fix
  Packs/CommonPlaybooks/Playbooks/playbook-Command-Line_Analysis.yml
  Packs/CommonPlaybooks/ReleaseNotes/2_3_92.md
  Packs/CommonPlaybooks/pack_metadata.json
Labels: docs-approved

#28991 CrowdStrike Falcon timeout argument
  Packs/CrowdStrikeFalcon/Integrations/CrowdStrikeFalcon/CrowdStrikeFalcon.py
  Packs/CrowdStrikeFalcon/Integrations/CrowdStrikeFalcon/CrowdStrikeFalcon.yml
  Packs/CrowdStrikeFalcon/Integrations/CrowdStrikeFalcon/CrowdStrikeFalcon_test.py
  Packs/CrowdStrikeFalcon/ReleaseNotes/1_11_5.md
  Packs/CrowdStrikeFalcon/pack_metadata.json
Labels: docs-approved
