Repository demisto/content, pull requests merged in 2024-07, with the labels that each got.

#34710 Fix AWS-EC2 Timeout
  Packs/AWS-EC2/Integrations/AWS-EC2/AWS-EC2.py
  Packs/AWS-EC2/Integrations/AWS-EC2/AWS-EC2.yml
  Packs/AWS-EC2/ReleaseNotes/1_4_10.md
  Packs/AWS-EC2/pack_metadata.json
Labels: docs-approved

#35132 [CSP] Revert PR 34921
  Packs/Base/ReleaseNotes/1_34_15.md
  Packs/Base/ReleaseNotes/1_34_19.md
  Packs/Base/Scripts/CommonServerPython/CommonServerPython.py
  Packs/Base/pack_metadata.json
Labels: docs-approved

#35128 remove policy rule install command from integration
  Packs/CheckPointHarmonyEndpoint/Integrations/CheckPointHarmonyEndpoint/CheckPointHarmonyEndpoint.py
  Packs/CheckPointHarmonyEndpoint/Integrations/CheckPointHarmonyEndpoint/CheckPointHarmonyEndpoint.yml
  Packs/CheckPointHarmonyEndpoint/Integrations/CheckPointHarmonyEndpoint/CheckPointHarmonyEndpoint_test.py
  Packs/CheckPointHarmonyEndpoint/Integrations/CheckPointHarmonyEndpoint/README.md
  Packs/CheckPointHarmonyEndpoint/ReleaseNotes/1_0_1.json
  Packs/CheckPointHarmonyEndpoint/ReleaseNotes/1_0_1.md
  Packs/CheckPointHarmonyEndpoint/TestPlaybooks/playbook-CheckPointHarmonyEndpoint_Test.yml
  Packs/CheckPointHarmonyEndpoint/pack_metadata.json
Labels: Contribution, Contribution Form Filled, Community, Xsoar Support Level, External PR, TIM Review

#35145 demisto/googleapi-python3:1.0.0.100240 | 0-100 | PR batch #1/1
  Packs/GoogleVertexAI/Integrations/GoogleVertexAI/GoogleVertexAI.yml
Labels: docs-approved, auto-update-docker

#35146 demisto/lacework:1.0.0.100340 | 0-100 | PR batch #1/1
  Packs/Lacework/Integrations/Lacework/Lacework.yml
Labels: docs-approved, auto-update-docker

#34666 rasterize frameStoppedLoading
  Packs/rasterize/Integrations/rasterize/rasterize.py
  Packs/rasterize/Integrations/rasterize/rasterize.yml
  Packs/rasterize/ReleaseNotes/2_0_15.md
  Packs/rasterize/pack_metadata.json
Labels: docs-approved, ForceMerge

#35109 TeamCymru Pack Adoption Start
  Packs/TeamCymru/README.md
  Packs/TeamCymru/ReleaseNotes/1_0_23.md
  Packs/TeamCymru/pack_metadata.json
Labels: Contribution, docs-approved, Partner, Contribution Form Filled, Xsoar Support Level, External PR

#35129 [Native & Github Feed] Remove From The Ignore List Of `candidate` Image
  Tests/docker_native_image_config.json
Labels: docs-approved

#35153 avoid collect draft prs in autobump
  .github/github_workflow_scripts/autobump_rn.py
Labels: docs-approved

#34490 Yc/rapid7/ciac 9577
  Packs/Rapid7_Nexpose/Integrations/Rapid7_Nexpose/README.md
  Packs/Rapid7_Nexpose/Integrations/Rapid7_Nexpose/Rapid7_Nexpose.py
  Packs/Rapid7_Nexpose/Integrations/Rapid7_Nexpose/Rapid7_Nexpose.yml
  Packs/Rapid7_Nexpose/Integrations/Rapid7_Nexpose/Rapid7_Nexpose_test.py
  Packs/Rapid7_Nexpose/Integrations/Rapid7_Nexpose/examples.txt
  Packs/Rapid7_Nexpose/Integrations/Rapid7_Nexpose/test_data/api_mock/client_get_asset_groups.json
  Packs/Rapid7_Nexpose/Integrations/Rapid7_Nexpose/test_data/api_mock/client_get_list_tag.json
  Packs/Rapid7_Nexpose/ReleaseNotes/1_2_24.md
  Packs/Rapid7_Nexpose/TestPlaybooks/playbook-Nexpose_test.yml
  Packs/Rapid7_Nexpose/pack_metadata.json
Labels: docs-approved

#34820 Mail Listener v2 - Fix fetch
  Packs/MailListener/Integrations/MailListenerV2/MailListenerV2.py
  Packs/MailListener/Integrations/MailListenerV2/MailListenerV2.yml
  Packs/MailListener/Integrations/MailListenerV2/MailListenerV2_test.py
  Packs/MailListener/ReleaseNotes/1_0_55.md
  Packs/MailListener/pack_metadata.json
Labels: docs-approved

#35149 [CSP] Increasing timeout for generic_http_request to 60 seconds
  Packs/Base/ReleaseNotes/1_34_20.md
  Packs/Base/Scripts/CommonServerPython/CommonServerPython.py
  Packs/Base/pack_metadata.json
Labels: docs-approved

#34993 [CortexXpanse] - EXPANDR 9482 - Update Cortex Xpanse Integration Commands
  Packs/CortexXpanse/Integrations/CortexXpanse/CortexXpanse.py
  Packs/CortexXpanse/Integrations/CortexXpanse/CortexXpanse.yml
  Packs/CortexXpanse/Integrations/CortexXpanse/CortexXpanse_test.py
  Packs/CortexXpanse/Integrations/CortexXpanse/README.md
  Packs/CortexXpanse/Integrations/CortexXpanse/command_examples
  Packs/CortexXpanse/Integrations/CortexXpanse/test_data/expected_results.py
  Packs/CortexXpanse/Integrations/CortexXpanse/test_data/raw_response.py
  Packs/CortexXpanse/ReleaseNotes/1_2_1.md
  Packs/CortexXpanse/pack_metadata.json
Labels: Contribution, docs-approved, Contribution Form Filled, Community, Xsoar Support Level, External PR, TIM Review

#35028 Add Mattermost Pack to all marketplaces
  Packs/Mattermost/Integrations/MattermostV2/MattermostV2.yml
  Packs/Mattermost/Integrations/MattermostV2/README.md
  Packs/Mattermost/ReleaseNotes/2_0_1.md
  Packs/Mattermost/Scripts/MattermostAskUser/MattermostAskUser.yml
  Packs/Mattermost/pack_metadata.json
Labels: docs-approved

#35143 [CortexXDRIR] Updated the descriptions for the lte_creation_time and gte_creation_time arguments in the xdr-get-incidents
  Packs/CortexXDR/Integrations/CortexXDRIR/CortexXDRIR.yml
  Packs/CortexXDR/Integrations/CortexXDRIR/README.md
  Packs/CortexXDR/ReleaseNotes/6_1_50.md
  Packs/CortexXDR/pack_metadata.json
Labels: docs-approved

#34860 Ciac 4934 jira service management
  Packs/AtlassianJiraServiceManagement/.pack-ignore
  Packs/AtlassianJiraServiceManagement/.secrets-ignore
  Packs/AtlassianJiraServiceManagement/Integrations/AtlassianJiraServiceManagement/AtlassianJiraServiceManagement.py
  Packs/AtlassianJiraServiceManagement/Integrations/AtlassianJiraServiceManagement/AtlassianJiraServiceManagement.yml
  Packs/AtlassianJiraServiceManagement/Integrations/AtlassianJiraServiceManagement/AtlassianJiraServiceManagement_description.md
  Packs/AtlassianJiraServiceManagement/Integrations/AtlassianJiraServiceManagement/AtlassianJiraServiceManagement_image.png
  Packs/AtlassianJiraServiceManagement/Integrations/AtlassianJiraServiceManagement/AtlassianJiraServiceManagement_test.py
  Packs/AtlassianJiraServiceManagement/Integrations/AtlassianJiraServiceManagement/README.md
  Packs/AtlassianJiraServiceManagement/Integrations/AtlassianJiraServiceManagement/command_examples
  Packs/AtlassianJiraServiceManagement/Integrations/AtlassianJiraServiceManagement/test_data/command_test_data.json
  Packs/AtlassianJiraServiceManagement/README.md
  Packs/AtlassianJiraServiceManagement/pack_metadata.json
Labels: docs-approved

#35156 fix o365 docker bc
  Packs/MicrosoftExchangeOnline/Integrations/EWSO365/EWSO365.py
  Packs/MicrosoftExchangeOnline/Integrations/EWSO365/EWSO365.yml
  Packs/MicrosoftExchangeOnline/ReleaseNotes/1_3_16.md
  Packs/MicrosoftExchangeOnline/pack_metadata.json
Labels: docs-approved

#35174 Fix issue when finding reviewer and reviewer already finished the review updated
  .github/github_workflow_scripts/handle_external_pr.py
Labels: docs-approved

#35159 CTF Packs - Removed XSOAR on-prem Marketplace
  Packs/CTF02/ReleaseNotes/1_0_4.md
  Packs/CTF02/Scripts/CTF2BF/CTF2BF.yml
  Packs/CTF02/pack_metadata.json
  Packs/ctf01/Integrations/CortexXDRIRCTF/CortexXDRIRCTF.yml
  Packs/ctf01/Integrations/OHMYVTCTF/OHMYVTCTF.yml
  Packs/ctf01/ReleaseNotes/1_0_19.md
  Packs/ctf01/Scripts/CTF1/CTF1.yml
  Packs/ctf01/pack_metadata.json
Labels: docs-approved, ForceMerge

#35167 [XSUP-39029] fix unhandled error
  Packs/Zscaler/Integrations/Zscaler/Zscaler.py
  Packs/Zscaler/Integrations/Zscaler/Zscaler_test.py
  Packs/Zscaler/ReleaseNotes/1_3_22.md
  Packs/Zscaler/pack_metadata.json
Labels: docs-approved

#35187 Revert "CTF Packs - Removed XSOAR on-prem Marketplace"
  Packs/CTF02/ReleaseNotes/1_0_4.md
  Packs/CTF02/Scripts/CTF2BF/CTF2BF.yml
  Packs/CTF02/pack_metadata.json
  Packs/ctf01/Integrations/CortexXDRIRCTF/CortexXDRIRCTF.yml
  Packs/ctf01/Integrations/OHMYVTCTF/OHMYVTCTF.yml
  Packs/ctf01/ReleaseNotes/1_0_19.md
  Packs/ctf01/Scripts/CTF1/CTF1.yml
  Packs/ctf01/pack_metadata.json
Labels: ForceMerge

#35179 ExtractIndicators add outputs
  Packs/CommonScripts/ReleaseNotes/1_15_19.md
  Packs/CommonScripts/Scripts/ExtractIndicatorsFromTextFile/ExtractIndicatorsFromTextFile.py
  Packs/CommonScripts/Scripts/ExtractIndicatorsFromTextFile/ExtractIndicatorsFromTextFile.yml
  Packs/CommonScripts/Scripts/ExtractIndicatorsFromTextFile/ExtractIndicatorsFromTextFile_test.py
  Packs/CommonScripts/pack_metadata.json
Labels: docs-approved

#35185 [Auto Update Docker] AUD-demisto/auto_update_docker_staging_branch_7
  Packs/GoogleVertexAI/Integrations/GoogleVertexAI/GoogleVertexAI.yml
  Packs/GoogleVertexAI/ReleaseNotes/1_0_2.md
  Packs/GoogleVertexAI/pack_metadata.json
  Packs/Lacework/Integrations/Lacework/Lacework.yml
  Packs/Lacework/ReleaseNotes/2_0_1.md
  Packs/Lacework/pack_metadata.json
  Packs/PopularCybersecurityNews/Integrations/PopularNews/PopularNews.yml
  Packs/PopularCybersecurityNews/ReleaseNotes/1_0_6.md
  Packs/PopularCybersecurityNews/pack_metadata.json
  Packs/SimpleSFTP/Integrations/SimpleSFTP/SimpleSFTP.yml
  Packs/SimpleSFTP/ReleaseNotes/1_2_1.md
  Packs/SimpleSFTP/pack_metadata.json
Labels: docs-approved

#35199 Revert "[Marketplace Contribution] FTP"
  Packs/FTP/.pack-ignore
  Packs/FTP/.secrets-ignore
  Packs/FTP/Integrations/FTP/FTP.py
  Packs/FTP/Integrations/FTP/FTP.yml
  Packs/FTP/Integrations/FTP/FTP_description.md
  Packs/FTP/Integrations/FTP/FTP_image.png
  Packs/FTP/Integrations/FTP/README.md
  Packs/FTP/README.md
  Packs/FTP/pack_metadata.json
Labels: ForceMerge

#34695 Ciac 10544 rasterize handle regression regarding integration option parameter
  Packs/rasterize/.secrets-ignore
  Packs/rasterize/Integrations/rasterize/README.md
  Packs/rasterize/Integrations/rasterize/rasterize.py
  Packs/rasterize/Integrations/rasterize/rasterize.yml
  Packs/rasterize/Integrations/rasterize/rasterize_description.md
  Packs/rasterize/Integrations/rasterize/rasterize_test.py
  Packs/rasterize/Integrations/rasterize/test_data/info.tsv
  Packs/rasterize/ReleaseNotes/2_0_15.md
  Packs/rasterize/ReleaseNotes/2_0_16.md
  Packs/rasterize/ReleaseNotes/2_0_17.md
  Packs/rasterize/pack_metadata.json
  Tests/conf.json
Labels: docs-approved

#35004 Added external last updated time incident field to the commontypes
  Packs/CommonTypes/IncidentFields/incidentfield-External_Last_Updated_Time.json
  Packs/CommonTypes/ReleaseNotes/3_5_6.md
  Packs/CommonTypes/pack_metadata.json
Labels: docs-approved

#35201 HPE switch marketplace
  Packs/HPESwitch/ReleaseNotes/1_0_1.md
  Packs/HPESwitch/pack_metadata.json
Labels: ForceMerge

#35200 Revert "Revert "[Marketplace Contribution] FTP""
  Packs/FTP/.pack-ignore
  Packs/FTP/.secrets-ignore
  Packs/FTP/Integrations/FTP/FTP.py
  Packs/FTP/Integrations/FTP/FTP.yml
  Packs/FTP/Integrations/FTP/FTP_description.md
  Packs/FTP/Integrations/FTP/FTP_image.png
  Packs/FTP/Integrations/FTP/README.md
  Packs/FTP/README.md
  Packs/FTP/pack_metadata.json
Labels: docs-approved

#35181 Update PaloAltoNetworks_Cortex_XDR_Incident_Sync_README.md
  Packs/CortexXDR/Playbooks/PaloAltoNetworks_Cortex_XDR_Incident_Sync_README.md
Labels: docs-approved

#35208 [SplunkPy] Update the README Troubleshooting
  Packs/SplunkPy/Integrations/SplunkPy/README.md
Labels: docs-approved

#35136 Align dbot output context path and IN124 problematic packs
  Packs/AWS-ACM/.pack-ignore
  Packs/AWS-ACM/Integrations/AWS-ACM/AWS-ACM.yml
  Packs/AWS-ACM/ReleaseNotes/1_1_36.md
  Packs/AWS-ACM/pack_metadata.json
  Packs/AWS-NetworkFirewall/.pack-ignore
  Packs/AWS-S3/.pack-ignore
  Packs/AWS-S3/Integrations/AWS-S3/AWS-S3.yml
  Packs/AWS-S3/ReleaseNotes/1_2_25.md
  Packs/AWS-S3/pack_metadata.json
  Packs/AWS_Sagemaker/.pack-ignore
  Packs/AWS_Sagemaker/Integrations/AWSSagemaker/AWSSagemaker.yml
  Packs/AWS_Sagemaker/ReleaseNotes/1_1_6.md
  Packs/AWS_Sagemaker/pack_metadata.json
  Packs/Anomali_Enterprise/.pack-ignore
  Packs/Anomali_Enterprise/Integrations/Anomali_Enterprise/Anomali_Enterprise.yml
  Packs/Anomali_Enterprise/Integrations/Anomali_Enterprise/README.md
  Packs/Anomali_Enterprise/ReleaseNotes/1_0_33.md
  Packs/Anomali_Enterprise/pack_metadata.json
  Packs/CIRCL/Integrations/CirclCVESearch/CirclCVESearch.yml
  Packs/CIRCL/Integrations/CirclCVESearch/README.md
  Packs/CIRCL/ReleaseNotes/1_0_23.md
  Packs/CIRCL/pack_metadata.json
  Packs/CortexDataLake/.pack-ignore
  Packs/CortexDataLake/Integrations/CortexDataLake/CortexDataLake.yml
  Packs/CortexDataLake/ReleaseNotes/1_4_11.md
  Packs/CortexDataLake/pack_metadata.json
  Packs/ForcepointDLP/.pack-ignore
  Packs/ForcepointDLP/Integrations/ForcepointEventCollector/ForcepointEventCollector.yml
  Packs/ForcepointDLP/ReleaseNotes/1_0_8.md
  Packs/ForcepointDLP/pack_metadata.json
  Packs/IsItPhishing/Integrations/IsItPhishing/IsItPhishing.yml
  Packs/IsItPhishing/Integrations/IsItPhishing/README.md
  Packs/IsItPhishing/ReleaseNotes/1_0_5.md
  Packs/IsItPhishing/pack_metadata.json
  Packs/PrismaAccess/.pack-ignore
  Packs/PrismaAccess/Integrations/PrismaAccessEgressIPFeed/PrismaAccessEgressIPFeed.yml
  Packs/PrismaAccess/ReleaseNotes/2_1_8.md
  Packs/PrismaAccess/pack_metadata.json
  Packs/Pwned/Integrations/PwnedV2/PwnedV2.yml
  Packs/Pwned/ReleaseNotes/1_0_14.md
  Packs/Pwned/pack_metadata.json
  Packs/illuminate/Integrations/Analyst1/Analyst1.yml
  Packs/illuminate/Integrations/Analyst1/README.md
  Packs/illuminate/ReleaseNotes/1_1_9.md
  Packs/illuminate/pack_metadata.json
  Packs/isight/Integrations/FireEyeISIGHT/FireEyeISIGHT.yml
  Packs/isight/ReleaseNotes/1_0_6.md
  Packs/isight/pack_metadata.json
  validation_config.toml
Labels: docs-approved, ForceMerge

#35197 fix ComonServerPython docstring
  Packs/Base/ReleaseNotes/1_34_22.md
  Packs/Base/Scripts/CommonServerPython/CommonServerPython.py
  Packs/Base/pack_metadata.json
Labels: docs-approved

#35209 Prevent changing infra files
  .github/workflows/protect-files.yml
  .github/workflows/protect-infra-directories-contributions.yml
Labels: docs-approved

#35211 Use DemistoWrapper in all integrations and scripts
  Packs/ApiModules/Scripts/DemistoClassApiModule/DemistoClassApiModule.py
  Packs/Base/ReleaseNotes/1_34_23.md
  Packs/Base/pack_metadata.json
Labels: docs-approved

#35220 New pack for CVE-2024-6387
  Packs/CVE_2024_6387_-_OpenSSH_RCE_RegreSSHion/.pack-ignore
  Packs/CVE_2024_6387_-_OpenSSH_RCE_RegreSSHion/.secrets-ignore
  Packs/CVE_2024_6387_-_OpenSSH_RCE_RegreSSHion/Playbooks/playbook-CVE-2024-6387_-_OpenSSH_RegreSSHion_RCE.yml
  Packs/CVE_2024_6387_-_OpenSSH_RCE_RegreSSHion/Playbooks/playbook-CVE-2024-6387_-_OpenSSH_RegreSSHion_RCE_README.md
  Packs/CVE_2024_6387_-_OpenSSH_RCE_RegreSSHion/README.md
  Packs/CVE_2024_6387_-_OpenSSH_RCE_RegreSSHion/doc_files/CVE-2024-6387_-_OpenSSH_RegreSSHion_RCE.png
  Packs/CVE_2024_6387_-_OpenSSH_RCE_RegreSSHion/pack_metadata.json
Labels: docs-approved

#35133 Fix roles in common playbooks data collection task
  Packs/CommonPlaybooks/Playbooks/playbook-Block_Account_-_Generic_v2.yml
  Packs/CommonPlaybooks/Playbooks/playbook-Block_IP_-_Generic_v3.yml
  Packs/CommonPlaybooks/Playbooks/playbook-Block_URL_-_Generic_v2.yml
  Packs/CommonPlaybooks/ReleaseNotes/2_6_34.md
  Packs/CommonPlaybooks/pack_metadata.json
Labels: docs-approved

#35112 Prisma Cloud Compute - Update integration logo
  Packs/PrismaCloudCompute/CONTRIBUTORS.json
  Packs/PrismaCloudCompute/Integrations/PaloAltoNetworks_PrismaCloudCompute/PaloAltoNetworks_PrismaCloudCompute_image.png
  Packs/PrismaCloudCompute/ReleaseNotes/1_7_2.md
  Packs/PrismaCloudCompute/pack_metadata.json
Labels: Contribution, docs-approved, Contribution Form Filled, Community, Xsoar Support Level, External PR

#35030 Recorded Future Intelligence Cloud CIAC - 10390
  Packs/RecordedFuture/ModelingRules/RecordedFutureModelingRules_1_4/RecordedFutureModelingRules_1_4.xif
  Packs/RecordedFuture/ModelingRules/RecordedFutureModelingRules_1_4/RecordedFutureModelingRules_1_4_schema.json
  Packs/RecordedFuture/ReleaseNotes/1_7_13.md
  Packs/RecordedFuture/pack_metadata.json
Labels: docs-approved

#35183 Zerofox/add cac data
  Packs/ZeroFox/Integrations/ZeroFox/README.md
  Packs/ZeroFox/Integrations/ZeroFox/ZeroFox.py
  Packs/ZeroFox/Integrations/ZeroFox/ZeroFox.yml
  Packs/ZeroFox/Integrations/ZeroFox/ZeroFox_description.md
  Packs/ZeroFox/Integrations/ZeroFox/ZeroFox_test.py
  Packs/ZeroFox/Integrations/ZeroFox/test_data/breach_data/breach_123.csv
  Packs/ZeroFox/ReleaseNotes/1_3_4.md
  Packs/ZeroFox/pack_metadata.json
Labels: Contribution, docs-approved, Partner, Contribution Form Filled, Partner Support Level, External PR, Partner-Approved, TIM Review

#35221 fixed test pb Microsoft Defender Advanced Threat Protection - Test prod fails nightly
  Packs/MicrosoftDefenderAdvancedThreatProtection/TestPlaybooks/playbook-Microsoft_Defender_Advanced_Threat_Protection-Test.yml
Labels: docs-approved

#35205 demisto/yolo-coco:1.0.0.98891 | 0-100 | PR batch #1/1
  Packs/ComputerVisionEngine/Integrations/ComputerVisionEngine/ComputerVisionEngine.yml
Labels: docs-approved, auto-update-docker

#35204 demisto/ibm-db2:1.0.0.100241 | 0-100 | PR batch #1/1
  Packs/DB2/Integrations/DB2/DB2.yml
Labels: docs-approved, auto-update-docker

#35203 demisto/feed-performance-test:1.0.99137 | 0-100 | PR batch #1/1
  Packs/DeveloperTools/Integrations/CreateMockFeed/CreateMockFeed.yml
Labels: docs-approved, auto-update-docker

#35137 demisto/bs4-py3:1.0.0.100299 | 0-100 | PR batch #1/1
  Packs/CommunityCommonScripts/Scripts/MarkdownToHTML/MarkdownToHTML.yml
  Packs/Use_Case_Builder/Scripts/UseCaseBuilderMarkdownToHTML/UseCaseBuilderMarkdownToHTML.yml
  Packs/WebScraper/Scripts/WebScraper/WebScraper.yml
Labels: auto-update-docker

#34874 Switch netutils
  Packs/ProofpointEmailSecurity/Integrations/ProofpointEmailSecurityEventCollector/ProofpointEmailSecurityEventCollector.yml
  Packs/ProofpointEmailSecurity/ReleaseNotes/1_0_2.md
  Packs/ProofpointEmailSecurity/pack_metadata.json
Labels: docs-approved

#35139 demisto/jq:1.0.0.100247 | 0-100 | PR batch #1/1
  Packs/CommunityCommonScripts/Scripts/Jq/Jq.yml
Labels: auto-update-docker

#35222 updated the classifier and layout of the qradar integration
  Packs/QRadar/Classifiers/classifier-QRadar_-_Generic_Incoming_Mapper.json
  Packs/QRadar/Layouts/layoutscontainer-Qradar_Generic.json
  Packs/QRadar/ReleaseNotes/2_5_1.md
  Packs/QRadar/pack_metadata.json
Labels: docs-approved

#33954 improved implementation of IsIncidentPartOfCampaign
  Packs/Campaign/ReleaseNotes/3_4_5.md
  Packs/Campaign/Scripts/IsIncidentPartOfCampaign/IsIncidentPartOfCampaign.py
  Packs/Campaign/Scripts/IsIncidentPartOfCampaign/IsIncidentPartOfCampaign.yml
  Packs/Campaign/Scripts/IsIncidentPartOfCampaign/IsIncidentPartOfCampaign_test.py
  Packs/Campaign/Scripts/IsIncidentPartOfCampaign/README.md
  Packs/Campaign/pack_metadata.json
Labels: docs-approved

#35206 Fixed CortexCoreIR http_request
  Packs/ApiModules/Scripts/CoreIRApiModule/CoreIRApiModule.py
  Packs/ApiModules/Scripts/CoreIRApiModule/CoreIRApiModule_test.py
  Packs/Base/ReleaseNotes/1_34_24.md
  Packs/Base/Scripts/CommonServerPython/CommonServerPython.py
  Packs/Base/pack_metadata.json
  Packs/Core/Integrations/CoreIOCs/CoreIOCs.py
  Packs/Core/Integrations/CortexCoreIR/CortexCoreIR.py
  Packs/Core/ReleaseNotes/3_0_49.md
  Packs/Core/pack_metadata.json
  Packs/CortexXDR/Integrations/CortexXDRIR/CortexXDRIR_test.py
  Packs/CortexXDR/ReleaseNotes/6_1_51.md
  Packs/CortexXDR/pack_metadata.json
  Packs/ctf01/ReleaseNotes/1_0_19.md
  Packs/ctf01/pack_metadata.json
  Tests/conf.json
Labels: docs-approved, ForceMerge

#35175 Azure SQL Management - Client Credentials
  Packs/AzureSQLManagement/Integrations/AzureSQLManagement/AzureSQLManagement.py
  Packs/AzureSQLManagement/Integrations/AzureSQLManagement/AzureSQLManagement.yml
  Packs/AzureSQLManagement/Integrations/AzureSQLManagement/AzureSQLManagement_description.md
  Packs/AzureSQLManagement/Integrations/AzureSQLManagement/README.md
  Packs/AzureSQLManagement/ReleaseNotes/1_2_0.md
  Packs/AzureSQLManagement/pack_metadata.json
Labels: docs-approved, sync-gsm

#35182 Azure waf client credentials
  Packs/AzureWAF/Integrations/AzureWAF/AzureWAF.py
  Packs/AzureWAF/Integrations/AzureWAF/AzureWAF.yml
  Packs/AzureWAF/Integrations/AzureWAF/AzureWAF_description.md
  Packs/AzureWAF/Integrations/AzureWAF/README.md
  Packs/AzureWAF/ReleaseNotes/1_2_0.md
  Packs/AzureWAF/pack_metadata.json
Labels: docs-approved

#35034 Azure devops client credentials
  Packs/AzureDevOps/Integrations/AzureDevOps/AzureDevOps.py
  Packs/AzureDevOps/Integrations/AzureDevOps/AzureDevOps.yml
  Packs/AzureDevOps/Integrations/AzureDevOps/AzureDevOps_description.md
  Packs/AzureDevOps/Integrations/AzureDevOps/AzureDevOps_test.py
  Packs/AzureDevOps/Integrations/AzureDevOps/README.md
  Packs/AzureDevOps/ReleaseNotes/1_4_0.md
  Packs/AzureDevOps/pack_metadata.json
Labels: docs-approved

#35162 SplunkPy:get drilldown search in correct format
  Packs/SplunkPy/Integrations/SplunkPy/SplunkPy.py
  Packs/SplunkPy/Integrations/SplunkPy/SplunkPy.yml
  Packs/SplunkPy/Integrations/SplunkPy/SplunkPy_test.py
  Packs/SplunkPy/ReleaseNotes/3_1_32.md
  Packs/SplunkPy/pack_metadata.json
Labels: docs-approved

#35141 demisto/unzip:1.0.0.100283 | 0-100 | PR batch #1/1
  Packs/XSOARLabUpdates/Scripts/BuildSlackBlocksFromIndex/BuildSlackBlocksFromIndex.yml
Labels: auto-update-docker

#35140 demisto/python-phash:1.0.0.100267 | 0-100 | PR batch #1/1
  Packs/CommunityCommonScripts/Scripts/PHash/PHash.yml
Labels: auto-update-docker

#35223 [MicrosoftAzureStorageApiModule] fixed token to start with '?'
  Packs/ApiModules/Scripts/MicrosoftAzureStorageApiModule/MicrosoftAzureStorageApiModule.py
  Packs/ApiModules/Scripts/MicrosoftAzureStorageApiModule/MicrosoftAzureStorageApiModule.yml
  Packs/AzureStorageContainer/Integrations/AzureStorageContainer/AzureStorageContainer.py
  Packs/AzureStorageContainer/Integrations/AzureStorageContainer/AzureStorageContainer.yml
  Packs/AzureStorageContainer/Integrations/AzureStorageContainer/AzureStorageContainer_test.py
  Packs/AzureStorageContainer/ReleaseNotes/1_0_21.md
  Packs/AzureStorageContainer/pack_metadata.json
  Packs/AzureStorageFileShare/Integrations/AzureStorageFileShare/AzureStorageFileShare.py
  Packs/AzureStorageFileShare/Integrations/AzureStorageFileShare/AzureStorageFileShare.yml
  Packs/AzureStorageFileShare/Integrations/AzureStorageFileShare/AzureStorageFileShare_test.py
  Packs/AzureStorageFileShare/ReleaseNotes/1_0_28.md
  Packs/AzureStorageFileShare/pack_metadata.json
  Packs/AzureStorageQueue/Integrations/AzureStorageQueue/AzureStorageQueue.py
  Packs/AzureStorageQueue/Integrations/AzureStorageQueue/AzureStorageQueue.yml
  Packs/AzureStorageQueue/Integrations/AzureStorageQueue/AzureStorageQueue_test.py
  Packs/AzureStorageQueue/ReleaseNotes/1_0_20.md
  Packs/AzureStorageQueue/pack_metadata.json
  Packs/AzureStorageTable/Integrations/AzureStorageTable/AzureStorageTable.py
  Packs/AzureStorageTable/Integrations/AzureStorageTable/AzureStorageTable.yml
  Packs/AzureStorageTable/Integrations/AzureStorageTable/AzureStorageTable_test.py
  Packs/AzureStorageTable/ReleaseNotes/1_0_22.md
  Packs/AzureStorageTable/pack_metadata.json
Labels: docs-approved

#35232 [Auto Update Docker] AUD-demisto/bump-demisto-xsoar-tools
  Packs/CommonScripts/ReleaseNotes/1_15_20.md
  Packs/CommonScripts/Scripts/ContentPackInstaller/ContentPackInstaller.yml
  Packs/CommonScripts/pack_metadata.json
  Packs/ContentManagement/ReleaseNotes/1_2_22.md
  Packs/ContentManagement/Scripts/CustomPackInstaller/CustomPackInstaller.yml
  Packs/ContentManagement/Scripts/JobCreator/JobCreator.yml
  Packs/ContentManagement/pack_metadata.json
Labels: docs-approved, auto-update-docker

#35231 [Auto Update Docker] AUD-demisto/auto_update_docker_staging_branch_8
  Packs/ComputerVisionEngine/Integrations/ComputerVisionEngine/ComputerVisionEngine.yml
  Packs/ComputerVisionEngine/ReleaseNotes/1_0_2.md
  Packs/ComputerVisionEngine/pack_metadata.json
  Packs/DB2/Integrations/DB2/DB2.yml
  Packs/DB2/ReleaseNotes/1_0_1.md
  Packs/DB2/pack_metadata.json
  Packs/DeveloperTools/Integrations/CreateMockFeed/CreateMockFeed.yml
  Packs/DeveloperTools/ReleaseNotes/1_3_17.md
  Packs/DeveloperTools/pack_metadata.json
Labels: docs-approved, auto-update-docker

#35253 Removing demistomock ignore exclusion
  .gitignore
Labels: docs-approved

#35255 Arcanna ai 1.2.1 bugfix
  Packs/Arcanna/Integrations/ArcannaAI/ArcannaAI.py
  Packs/Arcanna/ReleaseNotes/1_2_1.md
  Packs/Arcanna/pack_metadata.json
Labels: Contribution, docs-approved, Partner, Contribution Form Filled, Partner Support Level, External PR, Partner-Approved

#35234 demisto/python3:3.10.14.100715 | 0-100 | PR batch #1/19
  Packs/Aella_StarLight/Integrations/AellaStarLight/AellaStarLight.yml
  Packs/AlphaVantage/Integrations/AlphaVantage/AlphaVantage.yml
  Packs/Arduino/Integrations/Arduino/Arduino.yml
  Packs/Barracuda/Integrations/BarracudaReputationBlockListBRBL/BarracudaReputationBlockListBRBL.yml
  Packs/BitDam/Integrations/BitDam/BitDam.yml
  Packs/BluelivThreatContext/Integrations/BluelivThreatContext/BluelivThreatContext.yml
  Packs/Bonusly/Integrations/Bonusly/Bonusly.yml
  Packs/Bonusly/Scripts/IncOwnerToBonuslyUser/IncOwnerToBonuslyUser.yml
  Packs/CaseManagement-Generic/Scripts/AddUserToIncidentTeam/AddUserToIncidentTeam.yml
  Packs/CaseManagement-Generic/Scripts/CaseMgmtAnalystTools/CaseMgmtAnalystTools.yml
Labels: docs-approved, auto-update-docker

#35242 demisto/python3:3.10.14.100715 | 0-100 | PR batch #9/19
  Packs/HealthCheck/Scripts/HealthCheckReadConf/HealthCheckReadConf.yml
  Packs/HealthCheck/Scripts/HealthCheckReadTemeletryLog/HealthCheckReadTemeletryLog.yml
  Packs/HealthCheck/Scripts/HealthCheckReadVC/HealthCheckReadVC.yml
  Packs/HealthCheck/Scripts/HealthCheckServerLog/HealthCheckServerLog.yml
  Packs/HealthCheck/Scripts/HealthCheckUnpack/HealthCheckUnpack.yml
  Packs/HelloWorld/Integrations/FeedHelloWorld/FeedHelloWorld.yml
  Packs/IP-API/Integrations/IPAPI/IPAPI.yml
  Packs/Ja3er/Integrations/Ja3er/Ja3er.yml
  Packs/LINENotify/Integrations/LINENotify/LINENotify.yml
  Packs/MicroFocusSMAX/Integrations/MicroFocusSMAX/MicroFocusSMAX.yml
Labels: docs-approved, auto-update-docker

#35241 demisto/python3:3.10.14.100715 | 0-100 | PR batch #8/19
  Packs/HealthCheck/Scripts/HealthCheckFileSystem/HealthCheckFileSystem.yml
  Packs/HealthCheck/Scripts/HealthCheckGetLargestInputsAndOutputsInIncidents/HealthCheckGetLargestInputsAndOutputsInIncidents.yml
  Packs/HealthCheck/Scripts/HealthCheckLicenseData/HealthCheckLicenseData.yml
  Packs/HealthCheck/Scripts/HealthCheckNumberOfEngines/HealthCheckNumberOfEngines.yml
  Packs/HealthCheck/Scripts/HealthCheckNumberOfLargeIOIncidents/HealthCheckNumberOfLargeIOIncidents.yml
  Packs/HealthCheck/Scripts/HealthCheckNumberOfLargeIncidents/HealthCheckNumberOfLargeIncidents.yml
  Packs/HealthCheck/Scripts/HealthCheckNumberOfPartitions/HealthCheckNumberOfPartitions.yml
  Packs/HealthCheck/Scripts/HealthCheckOutdatedPacks/HealthCheckOutdatedPacks.yml
  Packs/HealthCheck/Scripts/HealthCheckPacksInstalled/HealthCheckPacksInstalled.yml
  Packs/HealthCheck/Scripts/HealthCheckPanicLog/HealthCheckPanicLog.yml
Labels: docs-approved, auto-update-docker

#35240 demisto/python3:3.10.14.100715 | 0-100 | PR batch #7/19
  Packs/FeedCyrenThreatInDepth/Scripts/CyrenThreatInDepthRenderRelated/CyrenThreatInDepthRenderRelated.yml
  Packs/FeedTalos/Integrations/FeedTalos/FeedTalos.yml
  Packs/FortiAuthenticator/Integrations/FortiAuthenticator/FortiAuthenticator.yml
  Packs/FullHunt/Integrations/FullHunt/FullHunt.yml
  Packs/GigamonThreatINSIGHT/Integrations/GigamonThreatINSIGHT/GigamonThreatINSIGHT.yml
  Packs/GoogleDorking/Integrations/GoogleDorking/GoogleDorking.yml
  Packs/GoogleDorking/Scripts/ExtractUsernames/ExtractUsernames.yml
  Packs/Graylog/Integrations/Graylog/Graylog.yml
  Packs/HealthCheck/Scripts/HealthCheckDockerLog/HealthCheckDockerLog.yml
  Packs/HealthCheck/Scripts/HealthCheckExportSummary/HealthCheckExportSummary.yml
Labels: docs-approved, auto-update-docker

#35237 demisto/python3:3.10.14.100715 | 0-100 | PR batch #4/19
  Packs/CommunityCommonScripts/Scripts/IPCalcReturnAddressBinary/IPCalcReturnAddressBinary.yml
  Packs/CommunityCommonScripts/Scripts/IPCalcReturnAddressIANAAllocation/IPCalcReturnAddressIANAAllocation.yml
  Packs/CommunityCommonScripts/Scripts/IPCalcReturnSubnetAddresses/IPCalcReturnSubnetAddresses.yml
  Packs/CommunityCommonScripts/Scripts/IPCalcReturnSubnetBroadcastAddress/IPCalcReturnSubnetBroadcastAddress.yml
  Packs/CommunityCommonScripts/Scripts/IPCalcReturnSubnetNetwork/IPCalcReturnSubnetNetwork.yml
  Packs/CommunityCommonScripts/Scripts/MapRegex/MapRegex.yml
  Packs/CommunityCommonScripts/Scripts/MaxList/MaxList.yml
  Packs/CommunityCommonScripts/Scripts/MinList/MinList.yml
  Packs/CommunityCommonScripts/Scripts/RandomElementFromList/RandomElementFromList.yml
  Packs/CommunityCommonScripts/Scripts/isArrayItemInList/IsArrayItemInList.yml
Labels: docs-approved, auto-update-docker

#35244 demisto/python3:3.10.14.100715 | 0-100 | PR batch #11/19
  Packs/MS-ISAC/Integrations/MSISAC/MSISAC.yml
  Packs/MitreCaldera/Scripts/CalderaReadOnlyFields/CalderaReadOnlyFields.yml
  Packs/MitreCaldera/Scripts/CalderaStartOperation/CalderaStartOperation.yml
  Packs/NCSCCyberAsssessmentFramework/Scripts/EntryWidgetNCSCResultsA/EntryWidgetNCSCResultsA.yml
  Packs/NCSCCyberAsssessmentFramework/Scripts/EntryWidgetNCSCResultsB/EntryWidgetNCSCResultsB.yml
  Packs/NCSCCyberAsssessmentFramework/Scripts/EntryWidgetNCSCResultsC/EntryWidgetNCSCResultsC.yml
  Packs/NCSCCyberAsssessmentFramework/Scripts/EntryWidgetNCSCResultsD/EntryWidgetNCSCResultsD.yml
  Packs/NCSCCyberAsssessmentFramework/Scripts/NCSCCalculateQuestionsScore/NCSCCalculateQuestionsScore.yml
  Packs/NCSCCyberAsssessmentFramework/Scripts/NCSCFieldProtection/NCSCFieldProtection.yml
  Packs/NCSCCyberAsssessmentFramework/Scripts/NCSCQuestionPopulate/NCSCQuestionPopulate.yml
Labels: auto-update-docker

#35252 demisto/python3:3.10.14.100715 | 0-100 | PR batch #19/19
  Packs/XSOARContentUpdateNotifications/Scripts/FormatContentData/FormatContentData.yml
  Packs/XSOARContentUpdateNotifications/Scripts/GetLatestReleaseNotes/GetLatestReleaseNotes.yml
  Packs/XsoarWebserver/Scripts/EmailSLABreach/EmailSLABreach.yml
  Packs/XsoarWebserver/Scripts/XsoarWsParseContext/XsoarWsParseContext.yml
  Packs/XsoarWebserver/Scripts/XsoarWsPollStatus/XsoarWsPollStatus.yml
Labels: auto-update-docker

#35236 demisto/python3:3.10.14.100715 | 0-100 | PR batch #3/19
  Packs/CommunityCommonScripts/Scripts/CreateArrayWithDuplicates/CreateArrayWithDuplicates.yml
  Packs/CommunityCommonScripts/Scripts/CreateFileFromPathObject/CreateFileFromPathObject.yml
  Packs/CommunityCommonScripts/Scripts/DateTimeToADTime/DateTimeToADTime.yml
  Packs/CommunityCommonScripts/Scripts/DeleteExpiredIndicatorWithExlusion/DeleteExpiredIndicatorWithExlusion.yml
  Packs/CommunityCommonScripts/Scripts/DisplayIndicatorReputationContent/DisplayIndicatorReputationContent.yml
  Packs/CommunityCommonScripts/Scripts/DisplayTaggedWarroomEntries/DisplayTaggedWarroomEntries.yml
  Packs/CommunityCommonScripts/Scripts/GetFields/GetFields.yml
  Packs/CommunityCommonScripts/Scripts/GetFilePathPreProcessing/GetFilePathPreProcessing.yml
  Packs/CommunityCommonScripts/Scripts/IPCalcCheckSubnetCollision/IPCalcCheckSubnetCollision.yml
  Packs/CommunityCommonScripts/Scripts/InvertEveryTwoItems/InvertEveryTwoItems.yml
Labels: docs-approved, auto-update-docker

#34437 Fetch assets is stuck on an expired export uuid
  Packs/Base/ReleaseNotes/1_34_25.md
  Packs/Base/Scripts/CommonServerPython/CommonServerPython.py
  Packs/Base/pack_metadata.json
  Packs/Tenable_io/Integrations/Tenable_io/Tenable_io.py
  Packs/Tenable_io/Integrations/Tenable_io/Tenable_io.yml
  Packs/Tenable_io/Integrations/Tenable_io/Tenable_io_test.py
  Packs/Tenable_io/ReleaseNotes/2_2_4.md
  Packs/Tenable_io/TestPlaybooks/playbook-Tenable.io_test.yml
  Packs/Tenable_io/pack_metadata.json
Labels: docs-approved, ignore-auto-bump-version

#35138 demisto/cloudshare:1.0.0.73056 | 0-100 | PR batch #1/1
  Packs/CloudShare/Integrations/CloudShare/CloudShare.yml
Labels: auto-update-docker

#33742 Install And Archive Python Library script
  Packs/CommonScripts/ReleaseNotes/1_15_21.md
  Packs/CommonScripts/Scripts/DownloadAndArchivePythonLibrary/DownloadAndArchivePythonLibrary.py
  Packs/CommonScripts/Scripts/DownloadAndArchivePythonLibrary/DownloadAndArchivePythonLibrary.yml
  Packs/CommonScripts/Scripts/DownloadAndArchivePythonLibrary/DownloadAndArchivePythonLibrary_test.py
  Packs/CommonScripts/Scripts/DownloadAndArchivePythonLibrary/README.md
  Packs/CommonScripts/pack_metadata.json
Labels: docs-approved

#35269 Malicious Pod Response
  Packs/AWS-Enrichment-Remediation/Playbooks/playbook-Function_Deployment_-_AWS.yml
  Packs/AWS-Enrichment-Remediation/Playbooks/playbook-Function_Deployment_-_AWS_README.md
  Packs/AWS-Enrichment-Remediation/Playbooks/playbook-Function_Removal_-_AWS.yml
  Packs/AWS-Enrichment-Remediation/Playbooks/playbook-Function_Removal_-_AWS_README.md
  Packs/AWS-Enrichment-Remediation/ReleaseNotes/1_1_19.md
  Packs/AWS-Enrichment-Remediation/doc_files/Function_Deployment_-_AWS.png
  Packs/AWS-Enrichment-Remediation/doc_files/Function_Removal_-_AWS.png
  Packs/AWS-Enrichment-Remediation/pack_metadata.json
  Packs/CloudIncidentResponse/Playbooks/playbook-Cortex_XDR_-_Malicious_Pod_Response_-_Agent.yml
  Packs/CloudIncidentResponse/Playbooks/playbook-Cortex_XDR_-_Malicious_Pod_Response_-_Agent_README.md
  Packs/CloudIncidentResponse/ReleaseNotes/1_0_17.md
  Packs/CloudIncidentResponse/doc_files/Cortex_XDR_-_Malicious_Pod_Response_-_Agent.png
  Packs/CloudIncidentResponse/pack_metadata.json
  Packs/CortexXDR/Playbooks/Cortex_XDR_Alerts_Handling_v2.yml
  Packs/CortexXDR/Playbooks/Cortex_XDR_Alerts_Handling_v2_README.md
  Packs/CortexXDR/ReleaseNotes/6_1_52.md
  Packs/CortexXDR/doc_files/Cortex_XDR_Alerts_Handling_v2.png
  Packs/CortexXDR/pack_metadata.json
Labels: docs-approved

#35245 demisto/python3:3.10.14.100715 | 0-100 | PR batch #12/19
  Packs/NCSCCyberAsssessmentFramework/Scripts/NCSCReportDetails/NCSCReportDetails.yml
  Packs/NCSCCyberAsssessmentFramework/Scripts/NCSCReportDetailsA/NCSCReportDetailsA.yml
  Packs/NCSCCyberAsssessmentFramework/Scripts/NCSCReportDetailsB/NCSCReportDetailsB.yml
  Packs/NCSCCyberAsssessmentFramework/Scripts/NCSCReportDetailsC/NCSCReportDetailsC.yml
  Packs/NCSCCyberAsssessmentFramework/Scripts/NCSCReportDetailsD/NCSCReportDetailsD.yml
  Packs/NCSCCyberAsssessmentFramework/Scripts/NCSCReportOverview/NCSCReportOverview.yml
  Packs/NTT_Cyber_Threat_Sensor/Integrations/NTT_Cyber_Threat_Sensor/NTT_Cyber_Threat_Sensor.yml
  Packs/Nexthink/Integrations/Nexthink/Nexthink.yml
  Packs/OpenSourceVulnerabilities/Integrations/OSV/OSV.yml
  Packs/OracleCloudInfrastructureFeed/Integrations/OracleCloudInfrastructureFeed/OracleCloudInfrastructureFeed.yml
Labels: auto-update-docker

#35246 demisto/python3:3.10.14.100715 | 0-100 | PR batch #13/19
  Packs/PANOSPolicyOptimizer/Scripts/EntryWidgetPortBasedRules/EntryWidgetPortBasedRules.yml
  Packs/PANOSPolicyOptimizer/Scripts/EntryWidgetUnusedApplications/EntryWidgetUnusedApplications.yml
  Packs/PANOSPolicyOptimizer/Scripts/EntryWidgetUnusedRules/EntryWidgetUnusedRules.yml
  Packs/PANOStoCDLMonitoring/Scripts/PANOStoCortexDataLakeMonitoring/PANOStoCortexDataLakeMonitoring.yml
  Packs/PassiveTotal/Scripts/RiskIQPassiveTotalComponentsScript/RiskIQPassiveTotalComponentsScript.yml
  Packs/PassiveTotal/Scripts/RiskIQPassiveTotalComponentsWidgetScript/RiskIQPassiveTotalComponentsWidgetScript.yml
  Packs/PassiveTotal/Scripts/RiskIQPassiveTotalHostPairChildrenScript/RiskIQPassiveTotalHostPairChildrenScript.yml
  Packs/PassiveTotal/Scripts/RiskIQPassiveTotalHostPairParentsScript/RiskIQPassiveTotalHostPairParentsScript.yml
  Packs/PassiveTotal/Scripts/RiskIQPassiveTotalHostPairsChildrenWidgetScript/RiskIQPassiveTotalHostPairsChildrenWidgetScript.yml
  Packs/PassiveTotal/Scripts/RiskIQPassiveTotalHostPairsParentsWidgetScript/RiskIQPassiveTotalHostPairsParentsWidgetScript.yml
Labels: auto-update-docker

#35247 demisto/python3:3.10.14.100715 | 0-100 | PR batch #14/19
  Packs/PassiveTotal/Scripts/RiskIQPassiveTotalPDNSScript/RiskIQPassiveTotalPDNSScript.yml
  Packs/PassiveTotal/Scripts/RiskIQPassiveTotalPDNSWidgetScript/RiskIQPassiveTotalPDNSWidgetScript.yml
  Packs/PassiveTotal/Scripts/RiskIQPassiveTotalSSLForIssuerEmailWidgetScript/RiskIQPassiveTotalSSLForIssuerEmailWidgetScript.yml
  Packs/PassiveTotal/Scripts/RiskIQPassiveTotalSSLForSubjectEmailWidgetScript/RiskIQPassiveTotalSSLForSubjectEmailWidgetScript.yml
  Packs/PassiveTotal/Scripts/RiskIQPassiveTotalSSLScript/RiskIQPassiveTotalSSLScript.yml
  Packs/PassiveTotal/Scripts/RiskIQPassiveTotalSSLWidgetScript/RiskIQPassiveTotalSSLWidgetScript.yml
  Packs/PassiveTotal/Scripts/RiskIQPassiveTotalTrackersScript/RiskIQPassiveTotalTrackersScript.yml
  Packs/PassiveTotal/Scripts/RiskIQPassiveTotalTrackersWidgetScript/RiskIQPassiveTotalTrackersWidgetScript.yml
  Packs/PassiveTotal/Scripts/RiskIQPassiveTotalWhoisScript/RiskIQPassiveTotalWhoisScript.yml
  Packs/PassiveTotal/Scripts/RiskIQPassiveTotalWhoisWidgetScript/RiskIQPassiveTotalWhoisWidgetScript.yml
Labels: auto-update-docker

#35250 demisto/python3:3.10.14.100715 | 0-100 | PR batch #17/19
  Packs/UltraMSG/Integrations/UltraMSG/UltraMSG.yml
  Packs/UnisysStealth/Integrations/UnisysStealth/UnisysStealth.yml
  Packs/UpdateEntriesBySearch/Scripts/MarkAsEvidenceBySearch/MarkAsEvidenceBySearch.yml
  Packs/UpdateEntriesBySearch/Scripts/MarkAsNoteBySearch/MarkAsNoteBySearch.yml
  Packs/UpdateEntriesBySearch/Scripts/SetTagsBySearch/SetTagsBySearch.yml
  Packs/Use_Case_Builder/Scripts/CreateUseCaseStepsList/CreateUseCaseStepsList.yml
  Packs/Use_Case_Builder/Scripts/CreateXSOARIncidentFlowList/CreateXSOARIncidentFlowList.yml
  Packs/Use_Case_Builder/Scripts/DeleteAndExcludeIndicators/DeleteAndExcludeIndicators.yml
  Packs/Use_Case_Builder/Scripts/GettingStartedWithXSOAR/GettingStartedWithXSOAR.yml
  Packs/Use_Case_Builder/Scripts/PlaybookAutoGeneratorDynamicSectionMessage/PlaybookAutoGeneratorDynamicSectionMessage.yml
Labels: auto-update-docker

#35160 Ia servicenow
  Packs/ServiceNow/Integrations/ServiceNowv2/README.md
  Packs/ServiceNow/Integrations/ServiceNowv2/ServiceNowv2.yml
  Packs/ServiceNow/ReleaseNotes/2_6_4.md
  Packs/ServiceNow/ReleaseNotes/2_6_5.md
  Packs/ServiceNow/pack_metadata.json
Labels: docs-approved

#35248 demisto/python3:3.10.14.100715 | 0-100 | PR batch #15/19
  Packs/PostmarkSpamcheck/Integrations/PostmarkSpamcheck/PostmarkSpamcheck.yml
  Packs/Pulsedive/Integrations/Pulsedive/Pulsedive.yml
  Packs/QRCodeReader/Integrations/QRCodeReaderGoqrMe/QRCodeReaderGoqrMe.yml
  Packs/Rapid7InsightVMCloud/Integrations/Rapid7InsightVMCloud/Rapid7InsightVMCloud.yml
  Packs/SalesforceIndicators/Integrations/SalesforceIndicators/SalesforceIndicators.yml
  Packs/SalesforceV2/Integrations/SalesforceV2/SalesforceV2.yml
  Packs/SalesforceV2/Scripts/SalesforceCaseStatus/SalesforceCaseStatus.yml
  Packs/SalesforceV2/Scripts/SalesforceCaseStatusPicklist/SalesforceCaseStatusPicklist.yml
  Packs/SecurityTrails/Integrations/SecurityTrails/SecurityTrails.yml
  Packs/ShiftManagement-AssignToNextShift/Scripts/AssignToNextShift/AssignToNextShift.yml
Labels: auto-update-docker

#34936 [PAN-OS Policy Optimizer]
  Packs/PANOSPolicyOptimizer/Integrations/PANOSPolicyOptimizer/PANOSPolicyOptimizer.py
  Packs/PANOSPolicyOptimizer/Integrations/PANOSPolicyOptimizer/PANOSPolicyOptimizer.yml
  Packs/PANOSPolicyOptimizer/README.md
  Packs/PANOSPolicyOptimizer/ReleaseNotes/1_1_26.md
  Packs/PANOSPolicyOptimizer/ReleaseNotes/1_1_27.md
  Packs/PANOSPolicyOptimizer/pack_metadata.json
Labels: docs-approved

#35249 demisto/python3:3.10.14.100715 | 0-100 | PR batch #16/19
  Packs/SSLCertificates/Scripts/SSLVerifierV2ParseOutput/SSLVerifierV2ParseOutput.yml
  Packs/SimpleDebugger/Scripts/SimpleDebugger/SimpleDebugger.yml
  Packs/SnortIPBlocklist/Integrations/FeedSnortIPBlocklist/FeedSnortIPBlocklist.yml
  Packs/SpyCloud/Integrations/SpyCloud/SpyCloud.yml
  Packs/StarterPack/Integrations/BaseIntegration/BaseIntegration.yml
  Packs/StarterPack/Scripts/BaseScript/BaseScript.yml
  Packs/TeamManagement/Scripts/EnumerateRoles/EnumerateRoles.yml
  Packs/ThousandEyes/Integrations/ThousandEyes/ThousandEyes.yml
  Packs/Trello/Integrations/Trello/Trello.yml
  Packs/TwitterIOCHunter-FullDailyFeed/Integrations/TwitterIOCHunterFullDailyFeed/TwitterIOCHunterFullDailyFeed.yml
Labels: auto-update-docker

#35235 demisto/python3:3.10.14.100715 | 0-100 | PR batch #2/19
  Packs/CaseManagement-Generic/Scripts/CaseMgmtDisplayLabels/CaseMgmtDisplayLabels.yml
  Packs/CaseManagement-Generic/Scripts/CaseMgmtIncidentTypesByRole/CaseMgmtIncidentTypesByRole.py
  Packs/CaseManagement-Generic/Scripts/CaseMgmtIncidentTypesByRole/CaseMgmtIncidentTypesByRole.yml
  Packs/CaseManagement-Generic/Scripts/CaseMgmtIncidentTypesDisplay/CaseMgmtIncidentTypesDisplay.yml
  Packs/CaseManagement-Generic/Scripts/CaseMgmtResponseProcess/CaseMgmtResponseProcess.yml
  Packs/CaseManagement-Generic/Scripts/CompleteTaskOnTimerBreach/CompleteTaskOnTimerBreach.yml
  Packs/CaseManagement-Generic/Scripts/TimersOnOwnerChange/TimersOnOwnerChange.yml
  Packs/CentrifyVault/Integrations/CentrifyVault/CentrifyVault.py
  Packs/CentrifyVault/Integrations/CentrifyVault/CentrifyVault.yml
  Packs/CommunityCommonScripts/Scripts/BatchData/BatchData.py
  Packs/CommunityCommonScripts/Scripts/BatchData/BatchData.yml
  Packs/CommunityCommonScripts/Scripts/CompareList/CompareList.yml
  Packs/CommunityCommonScripts/Scripts/ConvertUTCEpochTimeToTimeStamp/ConvertUTCEpochTimeToTimeStamp.yml
Labels: docs-approved, auto-update-docker

#35210 XSUP-38911/ArcSight/FixErrorMsg
  Packs/ArcSightESM/Integrations/ArcSightESMv2/ArcSightESMv2.py
  Packs/ArcSightESM/Integrations/ArcSightESMv2/ArcSightESMv2.yml
  Packs/ArcSightESM/ReleaseNotes/1_2_3.md
  Packs/ArcSightESM/pack_metadata.json
Labels: docs-approved

#35219 XSUP-39128/OpsGenieV3/get_on_call_start_date_fix
  Packs/OpsGenie/Integrations/OpsGenieV3/OpsGenieV3.py
  Packs/OpsGenie/Integrations/OpsGenieV3/OpsGenieV3.yml
  Packs/OpsGenie/Integrations/OpsGenieV3/OpsGenieV3_test.py
  Packs/OpsGenie/ReleaseNotes/2_0_24.md
  Packs/OpsGenie/pack_metadata.json
Labels: docs-approved

#35189 CTF Packs - Removed XSOAR on-prem Marketplace
  Packs/CTF02/ReleaseNotes/1_0_4.md
  Packs/CTF02/Scripts/CTF2BF/CTF2BF.yml
  Packs/CTF02/pack_metadata.json
  Packs/ctf01/Integrations/CortexXDRIRCTF/CortexXDRIRCTF.yml
  Packs/ctf01/Integrations/OHMYVTCTF/OHMYVTCTF.yml
  Packs/ctf01/ReleaseNotes/1_0_20.md
  Packs/ctf01/Scripts/CTF1/CTF1.yml
  Packs/ctf01/pack_metadata.json
Labels: docs-approved, ForceMerge

#35161 Azure Kubernetes Services client credentials flow
  Packs/AzureKubernetesServices/Integrations/AzureKubernetesServices/AzureKubernetesServices.py
  Packs/AzureKubernetesServices/Integrations/AzureKubernetesServices/AzureKubernetesServices.yml
  Packs/AzureKubernetesServices/Integrations/AzureKubernetesServices/AzureKubernetesServices_description.md
  Packs/AzureKubernetesServices/Integrations/AzureKubernetesServices/AzureKubernetesServices_test.py
  Packs/AzureKubernetesServices/Integrations/AzureKubernetesServices/README.md
  Packs/AzureKubernetesServices/ReleaseNotes/1_2_0.md
  Packs/AzureKubernetesServices/pack_metadata.json
Labels: docs-approved, sync-gsm

#35258 Defang Added
  Packs/CommunityCommonScripts/CONTRIBUTORS.json
  Packs/CommunityCommonScripts/ReleaseNotes/1_2_2.md
  Packs/CommunityCommonScripts/Scripts/Defang/Defang.py
  Packs/CommunityCommonScripts/Scripts/Defang/Defang.yml
  Packs/CommunityCommonScripts/Scripts/Defang/README.md
  Packs/CommunityCommonScripts/pack_metadata.json
Labels: Contribution, pending-demo, Contribution Form Filled, Community, Community Support Level, External PR

#35271 Imperva WAF README Update
  Packs/Imperva_WAF/README.md
Labels: docs-approved

#35277 DemistoRESTAPI: added logs
  Packs/DemistoRESTAPI/Integrations/CoreRESTAPI/CoreRESTAPI.js
  Packs/DemistoRESTAPI/ReleaseNotes/1_3_57.md
  Packs/DemistoRESTAPI/pack_metadata.json
Labels: docs-approved

#35284 CRTX-120855/ GitHub Event Collector
  Packs/GitHub/Integrations/GitHubEventCollector/GitHubEventCollector.py
  Packs/GitHub/Integrations/GitHubEventCollector/GitHubEventCollector.yml
  Packs/GitHub/ReleaseNotes/2_1_2.md
  Packs/GitHub/pack_metadata.json
Labels: docs-approved

#35283 Demisto class for most
  Packs/ApiModules/Scripts/DemistoClassApiModule/DemistoClassApiModule.py
  Packs/Base/ReleaseNotes/1_34_26.md
  Packs/Base/pack_metadata.json
Labels: docs-approved

#34916 Update CrowdStrikeFalcon.yml
  Packs/CrowdStrikeFalcon/Integrations/CrowdStrikeFalcon/CrowdStrikeFalcon.yml
  Packs/CrowdStrikeFalcon/Integrations/CrowdStrikeFalcon/CrowdStrikeFalcon_description.md
  Packs/CrowdStrikeFalcon/Integrations/CrowdStrikeFalcon/README.md
  Packs/CrowdStrikeFalcon/ReleaseNotes/1_13_13.md
  Packs/CrowdStrikeFalcon/pack_metadata.json
Labels: Contribution, docs-approved

#33951 Fix 3.11 issues
  Packs/AWS-SQS/Integrations/AWS-SQS/AWS-SQS_test.py
  Packs/ApiModules/Scripts/CSVFeedApiModule/CSVFeedApiModule.py
  Packs/ApiModules/Scripts/CSVFeedApiModule/CSVFeedApiModule.yml
  Packs/ApiModules/Scripts/CSVFeedApiModule/CSVFeedApiModule_test.py
  Packs/BitcoinAbuse/ReleaseNotes/1_0_42.md
  Packs/BitcoinAbuse/pack_metadata.json
  Packs/Cisco-umbrella/Integrations/Cisco-umbrella-investigate/Cisco-umbrella-investigate_test.py
  Packs/CommonScripts/ReleaseNotes/1_15_22.md
  Packs/CommonScripts/Scripts/ParseCSV/ParseCSV.py
  Packs/CommonScripts/Scripts/ParseCSV/ParseCSV.yml
  Packs/CommonScripts/Scripts/ParseCSV/ParseCSV_test.py
  Packs/CommonScripts/pack_metadata.json
  Packs/FeedAlienVault/ReleaseNotes/1_1_32.md
  Packs/FeedAlienVault/pack_metadata.json
  Packs/FeedBambenekConsulting/ReleaseNotes/1_2_3.md
  Packs/FeedBambenekConsulting/pack_metadata.json
  Packs/FeedCSV/ReleaseNotes/1_1_31.md
  Packs/FeedCSV/pack_metadata.json
  Packs/FeedMajesticMillion/ReleaseNotes/1_1_15.md
  Packs/FeedMajesticMillion/pack_metadata.json
  Packs/FeedURLhaus/ReleaseNotes/1_0_11.md
  Packs/FeedURLhaus/pack_metadata.json
  Packs/FeedZeroDayLiveTIFusion/ReleaseNotes/1_0_3.md
  Packs/FeedZeroDayLiveTIFusion/pack_metadata.json
  Packs/Feedsslabusech/ReleaseNotes/1_1_27.md
  Packs/Feedsslabusech/pack_metadata.json
Labels: docs-approved

#34757 Ys cb eedr update version
  Packs/CarbonBlackEnterpriseEDR/Integrations/CarbonBlackEnterpriseEDR/CarbonBlackEnterpriseEDR.py
  Packs/CarbonBlackEnterpriseEDR/Integrations/CarbonBlackEnterpriseEDR/CarbonBlackEnterpriseEDR.yml
  Packs/CarbonBlackEnterpriseEDR/Integrations/CarbonBlackEnterpriseEDR/CarbonBlackEnterpriseEDR_test.py
  Packs/CarbonBlackEnterpriseEDR/Integrations/CarbonBlackEnterpriseEDR/README.md
  Packs/CarbonBlackEnterpriseEDR/Integrations/CarbonBlackEnterpriseEDR/command_examples.txt
  Packs/CarbonBlackEnterpriseEDR/Playbooks/Carbon_Black_EDR_Search_Process.yml
  Packs/CarbonBlackEnterpriseEDR/ReleaseNotes/1_1_34.json
  Packs/CarbonBlackEnterpriseEDR/ReleaseNotes/1_1_34.md
  Packs/CarbonBlackEnterpriseEDR/TestPlaybooks/Carbon_Black_Enterprise_EDR_Test.yml
  Packs/CarbonBlackEnterpriseEDR/TestPlaybooks/Carbon_Black_Enterprise_EDR_alert-workflow-update_Test.yml
  Packs/CarbonBlackEnterpriseEDR/TestPlaybooks/Carbon_Black_Enterprise_EDR_process_search_with_polling_test.yml
  Packs/CarbonBlackEnterpriseEDR/pack_metadata.json
Labels: docs-approved, ForceMerge

#35289 Fix multi-tenant auth issue in S&CV2
  Packs/MicrosoftExchangeOnline/Integrations/SecurityAndComplianceV2/SecurityAndComplianceV2.ps1
  Packs/MicrosoftExchangeOnline/Integrations/SecurityAndComplianceV2/SecurityAndComplianceV2_description.md
  Packs/MicrosoftExchangeOnline/ReleaseNotes/1_3_17.md
  Packs/MicrosoftExchangeOnline/pack_metadata.json
Labels: docs-approved

#35196 [Demisto Lock] Upgrade polling logic
  Packs/DemistoLocking/Integrations/DemistoLock/DemistoLock.js
  Packs/DemistoLocking/ReleaseNotes/1_1_2.md
  Packs/DemistoLocking/pack_metadata.json
Labels: docs-approved

#35102 Ia zimperium v2
  Packs/Zimperium/Integrations/ZimperiumV2/README.md
  Packs/Zimperium/Integrations/ZimperiumV2/ZimperiumV2.py
  Packs/Zimperium/Integrations/ZimperiumV2/ZimperiumV2.yml
  Packs/Zimperium/Integrations/ZimperiumV2/ZimperiumV2_test.py
  Packs/Zimperium/Integrations/ZimperiumV2/test_data/users_search_by_email.json
  Packs/Zimperium/ReleaseNotes/2_0_4.md
  Packs/Zimperium/TestPlaybooks/Zimperiumv2-TestPlaybook.yml
  Packs/Zimperium/pack_metadata.json
Labels: docs-approved

#35239 demisto/python3:3.10.14.100715 | 0-100 | PR batch #6/19
  Packs/DNSOverHttps/Integrations/DNSOverHttps/DNSOverHttps.yml
  Packs/DevSecOps/Integrations/DockerEngine/DockerEngine.py
  Packs/DevSecOps/Integrations/DockerEngine/DockerEngine.yml
  Packs/DevSecOps/Integrations/LGTM/LGTM.yml
  Packs/Drift/Integrations/Drift/Drift.py
  Packs/Drift/Integrations/Drift/Drift.yml
  Packs/EDLMonitor/Integrations/EDLMonitor/EDLMonitor.py
  Packs/EDLMonitor/Integrations/EDLMonitor/EDLMonitor.yml
  Packs/F5LTM/Integrations/F5LTM/F5LTM.py
  Packs/F5LTM/Integrations/F5LTM/F5LTM.yml
  Packs/FeedCyrenThreatInDepth/Scripts/CyrenCountryLookup/CyrenCountryLookup.py
  Packs/FeedCyrenThreatInDepth/Scripts/CyrenCountryLookup/CyrenCountryLookup.yml
  Packs/FeedCyrenThreatInDepth/Scripts/CyrenCountryLookup/CyrenCountryLookup_test.py
  Packs/FeedCyrenThreatInDepth/Scripts/CyrenThreatInDepthRandomHunt/CyrenThreatInDepthRandomHunt.py
  Packs/FeedCyrenThreatInDepth/Scripts/CyrenThreatInDepthRandomHunt/CyrenThreatInDepthRandomHunt.yml
  Packs/FeedCyrenThreatInDepth/Scripts/CyrenThreatInDepthRandomHunt/CyrenThreatInDepthRandomHunt_test.py
  Packs/FeedCyrenThreatInDepth/Scripts/CyrenThreatInDepthRelatedWidget/CyrenThreatInDepthRelatedWidget.py
  Packs/FeedCyrenThreatInDepth/Scripts/CyrenThreatInDepthRelatedWidget/CyrenThreatInDepthRelatedWidget.yml
  Packs/FeedCyrenThreatInDepth/Scripts/CyrenThreatInDepthRelatedWidget/CyrenThreatInDepthRelatedWidget_test.py
  Packs/FeedCyrenThreatInDepth/Scripts/CyrenThreatInDepthRelatedWidgetQuick/CyrenThreatInDepthRelatedWidgetQuick.py
  Packs/FeedCyrenThreatInDepth/Scripts/CyrenThreatInDepthRelatedWidgetQuick/CyrenThreatInDepthRelatedWidgetQuick.yml
  Packs/FeedCyrenThreatInDepth/Scripts/CyrenThreatInDepthRelatedWidgetQuick/CyrenThreatInDepthRelatedWidgetQuick_test.py
Labels: docs-approved, auto-update-docker

#35130 DBotGroupXDRIncidents - set marketplace to xsoar_on_prem
  Packs/CortexXDR/Dashboards/dashboard-Cortex_XDR_Events_Grouping.json
  Packs/CortexXDR/ReleaseNotes/6_1_53.md
  Packs/CortexXDR/Scripts/DBotGroupXDRIncidents/DBotGroupXDRIncidents.yml
  Packs/CortexXDR/Widgets/Widget-Cortex_XDR_Groups_Incidents.json
  Packs/CortexXDR/Widgets/Widget-Cortex_XDR_Groups_Scatter.json
  Packs/CortexXDR/Widgets/Widget-Cortex_XDR_Groups_Summary.json
  Packs/CortexXDR/pack_metadata.json
Labels: docs-approved

#35280 Fixed an issue on XSOAR 6 ExportAuditLogsToFile
  Packs/CommonScripts/ReleaseNotes/1_15_23.md
  Packs/CommonScripts/Scripts/ExportAuditLogsToFile/ExportAuditLogsToFile.py
  Packs/CommonScripts/Scripts/ExportAuditLogsToFile/ExportAuditLogsToFile.yml
  Packs/CommonScripts/pack_metadata.json
Labels: docs-approved

#35238 demisto/python3:3.10.14.100715 | 0-100 | PR batch #5/19
  Packs/CommunityCommonScripts/Scripts/RandomPhotoNasa/RandomPhotoNasa.yml
  Packs/CommunityCommonScripts/Scripts/SSLVerifier/SSLVerifier.yml
  Packs/CommunityCommonScripts/Scripts/StripAccentMarksFromString/StripAccentMarksFromString.yml
  Packs/CyberChef/Integrations/CyberChef/CyberChef.yml
  Packs/DeepL/Integrations/DeepL/DeepL.yml
  Packs/DeveloperTools/Scripts/FetchFromInstance/FetchFromInstance.py
  Packs/DeveloperTools/Scripts/FetchFromInstance/FetchFromInstance.yml
  Packs/DeveloperTools/Scripts/GetInstanceName/GetInstanceName.py
  Packs/DeveloperTools/Scripts/GetInstanceName/GetInstanceName.yml
  Packs/DeveloperTools/Scripts/VerifyEnoughIncidents/VerifyEnoughIncidents.yml
  Packs/DeveloperTools/Scripts/VerifyEnoughIndicators/VerifyEnoughIndicators.yml
  Packs/DeveloperTools/Scripts/VerifyObjectFieldsList/VerifyObjectFieldsList.py
  Packs/DeveloperTools/Scripts/VerifyObjectFieldsList/VerifyObjectFieldsList.yml
Labels: docs-approved, auto-update-docker

#35291 checking ignore rm108
  Packs/CloudIDS/.pack-ignore
  Packs/CloudIDS/README.md
Labels: docs-approved

#35285 XSUP-39103/JiraV3/Fix_Incoming_Comments
  Packs/Jira/Integrations/JiraV3/JiraV3.py
  Packs/Jira/Integrations/JiraV3/JiraV3.yml
  Packs/Jira/Integrations/JiraV3/JiraV3_test.py
  Packs/Jira/ReleaseNotes/3_2_1.md
  Packs/Jira/pack_metadata.json
Labels: docs-approved

#35293 added sort to the verify endpoint id
  Packs/MicrosoftDefenderAdvancedThreatProtection/TestPlaybooks/playbook-Microsoft_Defender_Advanced_Threat_Protection-Test.yml
Labels: docs-approved

#35264 reduced the timeout configured for Test Playbook - Cortex XDR - Retri…
  Tests/conf.json
Labels: docs-approved

#35218 reduced the timeout configured for Test Playbook - Cortex XDR Malware…
  Tests/conf.json
Labels: docs-approved

#35288 [Auto Update Docker] AUD-demisto/auto_update_docker_staging_branch_6
  Packs/CloudShare/Integrations/CloudShare/CloudShare.yml
  Packs/CloudShare/ReleaseNotes/1_0_3.md
  Packs/CloudShare/pack_metadata.json
  Packs/CommunityCommonScripts/ReleaseNotes/1_2_3.md
  Packs/CommunityCommonScripts/Scripts/Jq/Jq.yml
  Packs/CommunityCommonScripts/Scripts/MarkdownToHTML/MarkdownToHTML.yml
  Packs/CommunityCommonScripts/Scripts/PHash/PHash.yml
  Packs/CommunityCommonScripts/pack_metadata.json
  Packs/Use_Case_Builder/ReleaseNotes/1_0_6.md
  Packs/Use_Case_Builder/Scripts/UseCaseBuilderMarkdownToHTML/UseCaseBuilderMarkdownToHTML.yml
  Packs/Use_Case_Builder/pack_metadata.json
  Packs/WebScraper/ReleaseNotes/1_0_1.md
  Packs/WebScraper/Scripts/WebScraper/WebScraper.yml
  Packs/WebScraper/pack_metadata.json
  Packs/XSOARLabUpdates/ReleaseNotes/1_0_3.md
  Packs/XSOARLabUpdates/Scripts/BuildSlackBlocksFromIndex/BuildSlackBlocksFromIndex.yml
  Packs/XSOARLabUpdates/pack_metadata.json
Labels: docs-approved, auto-update-docker

#35251 demisto/python3:3.10.14.100715 | 0-100 | PR batch #18/19
  Packs/USTA/Integrations/USTA/USTA.yml
  Packs/Use_Case_Builder/Scripts/StopUseCaseDevelopmentTimer/StopUseCaseDevelopmentTimer.yml
  Packs/Use_Case_Builder/Scripts/UseCaseDevelopmentTimers/UseCaseDevelopmentTimers.yml
  Packs/VerifyIPv4Indicator/Scripts/VerifyIPv4Indicator/VerifyIPv4Indicator.yml
  Packs/Viper/Integrations/Viper/Viper.yml
  Packs/WolkenITSM/Integrations/WolkenITSM/WolkenITSM.yml
  Packs/Wordpress/Integrations/Wordpress/Wordpress.yml
  Packs/XSOARContentUpdateNotifications/Scripts/CollectPacksData/CollectPacksData.yml
  Packs/XSOAR_EDL_Checker/Scripts/XSOARAllEDLCheckerAutomation/XSOARAllEDLCheckerAutomation.yml
  Packs/Xsoar_Utils/Integrations/XsoarUtils/XsoarUtils.yml
Labels: auto-update-docker

#35307 Increased Account Enrichment - Generic v2.1 - Test memory_threshold
  Tests/conf.json
Labels: docs-approved

#35261 Domaintools irisdetect v1.0.14
  Packs/DomainToolsIrisDetect/Integrations/DomainToolsIrisDetect/DomainToolsIrisDetect.py
  Packs/DomainToolsIrisDetect/Integrations/DomainToolsIrisDetect/DomainToolsIrisDetect.yml
  Packs/DomainToolsIrisDetect/Integrations/DomainToolsIrisDetect/DomainToolsIrisDetect_test.py
  Packs/DomainToolsIrisDetect/ReleaseNotes/1_0_14.md
  Packs/DomainToolsIrisDetect/pack_metadata.json
Labels: Contribution, docs-approved, Partner, Contribution Form Filled, Partner Support Level, External PR, Partner-Approved, TIM Review

#35038 custom close reason support
  Packs/ApiModules/Scripts/CoreIRApiModule/CoreIRApiModule.py
  Packs/ApiModules/Scripts/CoreIRApiModule/CoreIRApiModule.yml
  Packs/Base/ReleaseNotes/1_34_27.md
  Packs/Base/Scripts/CommonServerPython/CommonServerPython.py
  Packs/Base/Scripts/CommonServerPython/CommonServerPython_test.py
  Packs/Base/pack_metadata.json
  Packs/Core/ReleaseNotes/3_0_50.md
  Packs/Core/pack_metadata.json
  Packs/CortexXDR/Integrations/CortexXDRIR/CortexXDRIR.py
  Packs/CortexXDR/Integrations/CortexXDRIR/CortexXDRIR.yml
  Packs/CortexXDR/Integrations/CortexXDRIR/CortexXDRIR_test.py
  Packs/CortexXDR/ReleaseNotes/6_1_54.md
  Packs/CortexXDR/pack_metadata.json
  Packs/ctf01/ReleaseNotes/1_0_21.md
  Packs/ctf01/pack_metadata.json
Labels: docs-approved, ForceMerge

#35111 [CortexXpanse] Option to add tags to assets
  Packs/CortexXpanse/IncidentFields/incidentfield-Xpanse_Certificate_Asset.json
  Packs/CortexXpanse/IncidentFields/incidentfield-Xpanse_Cloud_Asset.json
  Packs/CortexXpanse/IncidentFields/incidentfield-Xpanse_Domain_Asset.json
  Packs/CortexXpanse/IncidentFields/incidentfield-Xpanse_Responsive_IP_Asset.json
  Packs/CortexXpanse/IncidentTypes/incidenttype-Xpanse_Alert6.8.json
  Packs/CortexXpanse/Playbooks/Xpanse_-_Alert_Handler.yml
  Packs/CortexXpanse/Playbooks/Xpanse_-_Alert_Handler_README.md
  Packs/CortexXpanse/Playbooks/Xpanse_-_Alert_Self-Enrichment.yml
  Packs/CortexXpanse/ReleaseNotes/1_2_2.md
  Packs/CortexXpanse/doc_files/Xpanse_-_Alert_Handler.png
  Packs/CortexXpanse/pack_metadata.json
Labels: Contribution, docs-approved, Contribution Form Filled, Community, Xsoar Support Level, External PR, Security Review

#35192 BmcITSM- fix duplicate incidents
  Packs/BmcITSM/Integrations/BmcITSM/BmcITSM.py
  Packs/BmcITSM/Integrations/BmcITSM/BmcITSM.yml
  Packs/BmcITSM/Integrations/BmcITSM/BmcITSM_test.py
  Packs/BmcITSM/Integrations/BmcITSM/test_data/list_tickets_not_sorted.json
  Packs/BmcITSM/ReleaseNotes/1_0_23.md
  Packs/BmcITSM/pack_metadata.json
Labels: docs-approved

#35113 Update logo to align to common prisma cloud logo
  Packs/PrismaCloud/Integrations/PrismaCloudIAM/PrismaCloudIAM_image.png
  Packs/PrismaCloud/ReleaseNotes/4_3_7.md
  Packs/PrismaCloud/pack_metadata.json
Labels: Contribution, docs-approved, Contribution Form Filled, Community, Xsoar Support Level, External PR

#35060 Anomali bug
  Packs/Anomali_ThreatStream/Integrations/AnomaliThreatStreamv3/AnomaliThreatStreamv3.py
  Packs/Anomali_ThreatStream/Integrations/AnomaliThreatStreamv3/AnomaliThreatStreamv3.yml
  Packs/Anomali_ThreatStream/Integrations/AnomaliThreatStreamv3/AnomaliThreatStreamv3_test.py
  Packs/Anomali_ThreatStream/ReleaseNotes/2_2_21.md
  Packs/Anomali_ThreatStream/pack_metadata.json
Labels: docs-approved

#35276 Aws waf regions
  Packs/AWS_WAF/Integrations/AWSWAF/AWSWAF.yml
  Packs/AWS_WAF/ReleaseNotes/1_0_7.md
  Packs/AWS_WAF/pack_metadata.json
Labels: docs-approved

#35083 Fix Fetch-Alerts Microsoft Defender for Cloud Apps
  Packs/MicrosoftCloudAppSecurity/Integrations/MicrosoftDefenderEventCollector/MicrosoftDefenderEventCollector.py
  Packs/MicrosoftCloudAppSecurity/ReleaseNotes/2_2_1.md
  Packs/MicrosoftCloudAppSecurity/pack_metadata.json
Labels: docs-approved, release-notes-only

#32121 [Marketplace Contribution] - EXPANDR-7038 - Azure Resource Graph
  Packs/AzureResourceGraph/.pack-ignore
  Packs/AzureResourceGraph/.secrets-ignore
  Packs/AzureResourceGraph/Integrations/AzureResourceGraph/AzureResourceGraph.py
  Packs/AzureResourceGraph/Integrations/AzureResourceGraph/AzureResourceGraph.yml
  Packs/AzureResourceGraph/Integrations/AzureResourceGraph/AzureResourceGraph_description.md
  Packs/AzureResourceGraph/Integrations/AzureResourceGraph/AzureResourceGraph_image.png
  Packs/AzureResourceGraph/Integrations/AzureResourceGraph/AzureResourceGraph_test.py
  Packs/AzureResourceGraph/Integrations/AzureResourceGraph/README.md
  Packs/AzureResourceGraph/Integrations/AzureResourceGraph/command_examples
  Packs/AzureResourceGraph/Integrations/AzureResourceGraph/test_data/test_list_operations_output.json
  Packs/AzureResourceGraph/Integrations/AzureResourceGraph/test_data/test_resources_query_output.json
  Packs/AzureResourceGraph/Integrations/AzureResourceGraph/test_data/test_resources_query_paging_output.json
  Packs/AzureResourceGraph/README.md
  Packs/AzureResourceGraph/pack_metadata.json
Labels: Contribution, docs-approved, Contribution Form Filled, Community, pending-contributor, External PR

#35114 [ASM] EXPANDR-9733 Cortex ASM Patching files
  Packs/CortexAttackSurfaceManagement/Playbooks/Cortex_ASM_-_ASM_Alert.yml
  Packs/CortexAttackSurfaceManagement/Playbooks/Cortex_ASM_-_AWS_Enrichment.yml
  Packs/CortexAttackSurfaceManagement/Playbooks/Cortex_ASM_-_AWS_Enrichment_README.md
  Packs/CortexAttackSurfaceManagement/Playbooks/Cortex_ASM_-_Remediation.yml
  Packs/CortexAttackSurfaceManagement/Playbooks/Cortex_ASM_-_Remediation_Path_Rules.yml
  Packs/CortexAttackSurfaceManagement/Playbooks/Cortex_ASM_-_Remediation_Path_Rules_README.md
  Packs/CortexAttackSurfaceManagement/Playbooks/Cortex_ASM_-_Remediation_README.md
  Packs/CortexAttackSurfaceManagement/README.md
  Packs/CortexAttackSurfaceManagement/ReleaseNotes/1_7_42.md
  Packs/CortexAttackSurfaceManagement/doc_files/Cortex_ASM_-_ASM_Alert.png
  Packs/CortexAttackSurfaceManagement/doc_files/Cortex_ASM_-_AWS_Enrichment.png
  Packs/CortexAttackSurfaceManagement/doc_files/Cortex_ASM_-_Remediation.png
  Packs/CortexAttackSurfaceManagement/doc_files/Cortex_ASM_-_Remediation_Path_Rules.png
  Packs/CortexAttackSurfaceManagement/pack_metadata.json
Labels: Contribution, Contribution Form Filled, Community, Xsoar Support Level, External PR, Security Review

#35315 fix-ews-get-attachment
  Packs/MicrosoftExchangeOnline/Integrations/EWSO365/EWSO365.py
  Packs/MicrosoftExchangeOnline/ReleaseNotes/1_3_18.md
  Packs/MicrosoftExchangeOnline/pack_metadata.json
Labels: docs-approved

#35333 demisto/powershell:7.4.0.80528 | 0-100 | PR batch #1/1
  Packs/CommunityCommonScripts/Scripts/CalculateTimeSpan/CalculateTimeSpan.yml
  Packs/CommunityCommonScripts/Scripts/VersionEqualTo/VersionEqualTo.yml
  Packs/CommunityCommonScripts/Scripts/VersionGreaterThan/VersionGreaterThan.yml
  Packs/CommunityCommonScripts/Scripts/VersionLessThan/VersionLessThan.yml
Labels: docs-approved, auto-update-docker

#35292 Fix for XSOAR automation insights dashboard
  Packs/CommonDashboards/Dashboards/XSOAR_Automation_Insights.json
  Packs/CommonDashboards/ReleaseNotes/1_7_4.md
  Packs/CommonDashboards/Scripts/AdoptionMetrics/AdoptionMetrics.py
  Packs/CommonDashboards/pack_metadata.json
Labels: docs-approved

#35338 Fix modify edl playbook
  Packs/EDL/Playbooks/Modify_EDL.yml
  Packs/EDL/ReleaseNotes/3_3_3.md
  Packs/EDL/pack_metadata.json
Labels: docs-approved

#35334 demisto/py3-tools:1.0.0.102774 | 0-100 | PR batch #1/2
  Packs/AccentureCTI_Feed/Integrations/ACTIIndicatorFeed/ACTIIndicatorFeed.yml
  Packs/AsanaConnect/Integrations/AsanaConnect/AsanaConnect.yml
  Packs/DevSecOps/Integrations/MinIO/MinIO.yml
  Packs/FeedIntel471/Integrations/Intel471MalwareIndicator/Intel471MalwareIndicator.yml
  Packs/FeedIntel471/Integrations/Intel471WatcherAlerts/Intel471WatcherAlerts.yml
  Packs/FeedZeroDayLiveTIFusion/Integrations/FeedZeroDayLiveTIFUSION/FeedZeroDayLiveTIFUSION.yml
  Packs/GZip/Scripts/GZipFile/GZipFile.yml
  Packs/GZip/Scripts/UnzipGZFile/UnzipGZFile.yml
  Packs/Intezer/Integrations/IntezerV2/IntezerV2.yml
  Packs/SEKOIAIntelligenceCenter/Integrations/SEKOIAIntelligenceCenter/SEKOIAIntelligenceCenter.yml
Labels: docs-approved, auto-update-docker

#35259 Zimperuim_v2_playbook
  Packs/Zimperium/Classifiers/classifier-Zimperium_v2_-_Incoming_Mapper.json
  Packs/Zimperium/Integrations/ZimperiumV2/ZimperiumV2.yml
  Packs/Zimperium/Playbooks/playbook-Zimperium_Incident_Enrichment.yml
  Packs/Zimperium/Playbooks/playbook-Zimperium_Incident_Enrichment_README.md
  Packs/Zimperium/ReleaseNotes/2_0_5.md
  Packs/Zimperium/doc_files/Zimperium_Incident_Enrichment.png
  Packs/Zimperium/pack_metadata.json
Labels: docs-approved

#35324 demisto/ansible-runner:1.0.0.102086 | 0-100 | PR batch #1/1
  Packs/SSLCertificates/Scripts/GenerateCSR/GenerateCSR.yml
  Packs/SSLCertificates/Scripts/SSLVerifierV2/SSLVerifierV2.yml
  Packs/SSLCertificates/Scripts/SSLVerifierV2GenerateEmailBody/SSLVerifierV2GenerateEmailBody.yml
Labels: auto-update-docker

#35325 demisto/chromium:126.0.6478.102778 | 0-100 | PR batch #1/1
  Packs/CofenseTriage/Integrations/CofenseTriagev2/CofenseTriagev2.yml
Labels: auto-update-docker

#35336 demisto/python3-deb:3.11.9.102626 | 0-100 | PR batch #1/1
  Packs/CyberX-CentralManager/Integrations/CyberXCentralManager/CyberXCentralManager.yml
Labels: auto-update-docker

#35330 update contribution team members.
  .github/content_roles.json
Labels: docs-approved

#35343 Update 1_34_26.md
  Packs/Base/ReleaseNotes/1_34_26.md
Labels: docs-approved

#35279 ipv6 regex fix
  Packs/Base/TestPlaybooks/playbook-IPv6_extraction_test.yml
  Packs/CommonScripts/ReleaseNotes/1_15_25.md
  Packs/CommonScripts/Scripts/VerifyIPv6Indicator/VerifyIPv6Indicator.py
  Packs/CommonScripts/Scripts/VerifyIPv6Indicator/VerifyIPv6Indicator.yml
  Packs/CommonScripts/Scripts/VerifyIPv6Indicator/VerifyIPv6Indicator_test.py
  Packs/CommonScripts/pack_metadata.json
  Packs/CommonTypes/.pack-ignore
  Packs/CommonTypes/IndicatorTypes/reputation-ipv6.json
  Packs/CommonTypes/ReleaseNotes/3_5_7.md
  Packs/CommonTypes/pack_metadata.json
Labels: docs-approved

#35344 [Auto Update Docker] AUD-demisto/auto_update_docker_staging_branch_5
  Packs/CofenseTriage/Integrations/CofenseTriagev2/CofenseTriagev2.yml
  Packs/CofenseTriage/ReleaseNotes/2_1_26.md
  Packs/CofenseTriage/pack_metadata.json
  Packs/SSLCertificates/ReleaseNotes/1_0_3.md
  Packs/SSLCertificates/Scripts/GenerateCSR/GenerateCSR.yml
  Packs/SSLCertificates/Scripts/SSLVerifierV2/SSLVerifierV2.yml
  Packs/SSLCertificates/Scripts/SSLVerifierV2GenerateEmailBody/SSLVerifierV2GenerateEmailBody.yml
  Packs/SSLCertificates/pack_metadata.json
Labels: docs-approved, auto-update-docker

#35346 [Auto Update Docker] AUD-demisto/auto_update_docker_staging_branch_10
  Packs/AccentureCTI_Feed/Integrations/ACTIIndicatorFeed/ACTIIndicatorFeed.yml
  Packs/AccentureCTI_Feed/ReleaseNotes/1_1_37.md
  Packs/AccentureCTI_Feed/pack_metadata.json
  Packs/AsanaConnect/Integrations/AsanaConnect/AsanaConnect.yml
  Packs/AsanaConnect/ReleaseNotes/1_0_3.md
  Packs/AsanaConnect/pack_metadata.json
  Packs/CommunityCommonScripts/ReleaseNotes/1_2_5.md
  Packs/CommunityCommonScripts/Scripts/CalculateTimeSpan/CalculateTimeSpan.yml
  Packs/CommunityCommonScripts/Scripts/VersionEqualTo/VersionEqualTo.yml
  Packs/CommunityCommonScripts/Scripts/VersionGreaterThan/VersionGreaterThan.yml
  Packs/CommunityCommonScripts/Scripts/VersionLessThan/VersionLessThan.yml
  Packs/CommunityCommonScripts/pack_metadata.json
  Packs/CyberX-CentralManager/Integrations/CyberXCentralManager/CyberXCentralManager.yml
  Packs/CyberX-CentralManager/ReleaseNotes/1_0_5.md
  Packs/CyberX-CentralManager/pack_metadata.json
  Packs/DevSecOps/Integrations/MinIO/MinIO.yml
  Packs/DevSecOps/ReleaseNotes/1_1_10.md
  Packs/DevSecOps/pack_metadata.json
  Packs/FeedIntel471/Integrations/Intel471MalwareIndicator/Intel471MalwareIndicator.yml
  Packs/FeedIntel471/Integrations/Intel471WatcherAlerts/Intel471WatcherAlerts.yml
  Packs/FeedIntel471/ReleaseNotes/2_1_6.md
  Packs/FeedIntel471/pack_metadata.json
  Packs/FeedZeroDayLiveTIFusion/Integrations/FeedZeroDayLiveTIFUSION/FeedZeroDayLiveTIFUSION.yml
  Packs/FeedZeroDayLiveTIFusion/ReleaseNotes/1_0_4.md
  Packs/FeedZeroDayLiveTIFusion/pack_metadata.json
  Packs/GZip/ReleaseNotes/1_0_1.md
  Packs/GZip/Scripts/GZipFile/GZipFile.yml
  Packs/GZip/Scripts/UnzipGZFile/UnzipGZFile.yml
  Packs/GZip/pack_metadata.json
  Packs/Intezer/Integrations/IntezerV2/IntezerV2.yml
  Packs/Intezer/ReleaseNotes/1_6_17.md
  Packs/Intezer/pack_metadata.json
  Packs/SEKOIAIntelligenceCenter/Integrations/SEKOIAIntelligenceCenter/SEKOIAIntelligenceCenter.yml
  Packs/SEKOIAIntelligenceCenter/ReleaseNotes/1_2_33.md
  Packs/SEKOIAIntelligenceCenter/pack_metadata.json
  Packs/SendGrid/Integrations/SendGrid/SendGrid.yml
  Packs/SendGrid/ReleaseNotes/1_1_4.md
  Packs/SendGrid/pack_metadata.json
  Packs/Synapse/Integrations/Synapse/Synapse.yml
  Packs/Synapse/ReleaseNotes/1_0_7.md
  Packs/Synapse/pack_metadata.json
  Packs/UBIRCH/Integrations/UBIRCH/UBIRCH.yml
  Packs/UBIRCH/ReleaseNotes/1_0_2.md
  Packs/UBIRCH/pack_metadata.json
  Packs/XSOARSummaryDashboard/ReleaseNotes/1_0_2.md
  Packs/XSOARSummaryDashboard/Scripts/RSSWidgetLC/RSSWidgetLC.yml
  Packs/XSOARSummaryDashboard/pack_metadata.json
Labels: docs-approved, auto-update-docker

#35327 Tenable fetch bug
  Packs/Tenable_io/Integrations/Tenable_io/Tenable_io.py
  Packs/Tenable_io/ReleaseNotes/2_2_5.md
  Packs/Tenable_io/pack_metadata.json
Labels: docs-approved

#34564 Ciac 9706
  .github/github_workflow_scripts/handle_external_pr.py
  .github/github_workflow_scripts/utils.py
Labels: docs-approved

#35265 [CoreRESTApi] Fix httpMultipart loop
  Packs/DemistoRESTAPI/Integrations/CoreRESTAPI/CoreRESTAPI.js
  Packs/DemistoRESTAPI/ReleaseNotes/1_3_58.md
  Packs/DemistoRESTAPI/pack_metadata.json
Labels: docs-approved

#35352 [Auto Update Docker] AUD-demisto/auto_update_docker_staging_branch_11
  Packs/PopularCybersecurityNews/Integrations/PopularNews/PopularNews.yml
  Packs/PopularCybersecurityNews/ReleaseNotes/1_0_7.md
  Packs/PopularCybersecurityNews/pack_metadata.json
Labels: docs-approved, auto-update-docker

#35320 increased the memo for EWS Public Folders Test
  Tests/conf.json
Labels: docs-approved

#35311 CIAC-10305 Fortinet Fortigate XDM Modeling Enhancement
  Packs/FortiGate/.secrets-ignore
  Packs/FortiGate/ModelingRules/FortiGate_1_3/FortiGate_1_3.xif
  Packs/FortiGate/ModelingRules/FortiGate_1_3/FortiGate_1_3_schema.json
  Packs/FortiGate/README.md
  Packs/FortiGate/ReleaseNotes/2_0_2.md
  Packs/FortiGate/pack_metadata.json
Labels: docs-approved

#35050 Rewrite Whois
  Packs/SuspiciousDomainHunting/Playbooks/playbook-Suspicious_Domain_Hunting_Incident_Handling.yml
  Packs/SuspiciousDomainHunting/ReleaseNotes/1_0_4.md
  Packs/SuspiciousDomainHunting/pack_metadata.json
  Packs/Whois/.secrets-ignore
  Packs/Whois/Integrations/Whois/README.md
  Packs/Whois/Integrations/Whois/Whois.py
  Packs/Whois/Integrations/Whois/Whois.yml
  Packs/Whois/Integrations/Whois/Whois_description.md
  Packs/Whois/Integrations/Whois/Whois_test.py
  Packs/Whois/Integrations/Whois/test_data/test-arrange-data.json
  Packs/Whois/ReleaseNotes/1_5_15.md
  Packs/Whois/TestPlaybooks/Whois_A_new_layout_implemented_with_python-whois_service.yml
  Packs/Whois/pack_metadata.json
  Tests/conf.json
Labels: docs-approved, sync-gsm

#35350 Akamai waf event collector missing and duplicated events issue
  Packs/Akamai_SIEM/Integrations/Akamai_SIEM/Akamai_SIEM.py
  Packs/Akamai_SIEM/Integrations/Akamai_SIEM/Akamai_SIEM_test.py
  Packs/Akamai_SIEM/ReleaseNotes/1_1_5.md
  Packs/Akamai_SIEM/pack_metadata.json
Labels: docs-approved, ForceMerge

#35135 DisplyHTMLWIthImages: fix embeded images
  Packs/CommonScripts/ReleaseNotes/1_15_26.md
  Packs/CommonScripts/Scripts/DisplayHTMLWithImages/DisplayHTMLWithImages.py
  Packs/CommonScripts/Scripts/DisplayHTMLWithImages/DisplayHTMLWithImages.yml
  Packs/CommonScripts/Scripts/DisplayHTMLWithImages/DisplayHTMLWithImages_test.py
  Packs/CommonScripts/pack_metadata.json
Labels: docs-approved

#35081 Update docker ml
  Packs/Base/ReleaseNotes/1_34_28.md
  Packs/Base/Scripts/DBotBuildPhishingClassifier/DBotBuildPhishingClassifier.py
  Packs/Base/Scripts/DBotBuildPhishingClassifier/DBotBuildPhishingClassifier.yml
  Packs/Base/Scripts/DBotBuildPhishingClassifier/DBotBuildPhishingClassifier_test.py
  Packs/Base/Scripts/DBotFindSimilarIncidents/DBotFindSimilarIncidents.yml
  Packs/Base/Scripts/DBotFindSimilarIncidentsByIndicators/DBotFindSimilarIncidentsByIndicators.yml
  Packs/Base/Scripts/DBotPredictPhishingWords/DBotPredictPhishingWords.py
  Packs/Base/Scripts/DBotPredictPhishingWords/DBotPredictPhishingWords.yml
  Packs/Base/Scripts/DBotPredictPhishingWords/DBotPredictPhishingWords_test.py
  Packs/Base/Scripts/DBotPreprocessTextData/DBotPreprocessTextData.py
  Packs/Base/Scripts/DBotPreprocessTextData/DBotPreprocessTextData.yml
  Packs/Base/Scripts/DBotTrainTextClassifierV2/DBotTrainTextClassifierV2.py
  Packs/Base/Scripts/DBotTrainTextClassifierV2/DBotTrainTextClassifierV2.yml
  Packs/Base/Scripts/DBotTrainTextClassifierV2/DBotTrainTextClassifierV2_test.py
  Packs/Base/Scripts/GetMLModelEvaluation/GetMLModelEvaluation.py
  Packs/Base/Scripts/GetMLModelEvaluation/GetMLModelEvaluation.yml
  Packs/Base/Scripts/GetMLModelEvaluation/GetMLModelEvaluation_test.py
  Packs/Base/Scripts/GetMLModelEvaluation/README.md
  Packs/Base/TestPlaybooks/playbook-DBotFindSimilarIncidents-test.yml
  Packs/Base/pack_metadata.json
  Packs/DeveloperTools/TestPlaybooks/script-TestCreateIncidentsFile.yml
  Packs/DeveloperTools/TestPlaybooks/script-TestCreateIncidentsForPhishingClassifier.yml
  Packs/ML/ReleaseNotes/1_4_11.md
  Packs/ML/Scripts/DBotPredictIncidentsBatch/DBotPredictIncidentsBatch.py
  Packs/ML/Scripts/DBotPredictIncidentsBatch/DBotPredictIncidentsBatch.yml
  Packs/ML/Scripts/DBotPredictIncidentsBatch/DBotPredictIncidentsBatch_test.py
  Packs/ML/Scripts/DBotPredictIncidentsBatch/README.md
  Packs/ML/Scripts/DBotPredictOutOfTheBoxV2/DBotPredictOutOfTheBoxV2.py
  Packs/ML/Scripts/DBotPredictOutOfTheBoxV2/DBotPredictOutOfTheBoxV2.yml
  Packs/ML/Scripts/EvaluateMLModllAtProduction/EvaluateMLModllAtProduction.py
  Packs/ML/Scripts/EvaluateMLModllAtProduction/EvaluateMLModllAtProduction.yml
  Packs/ML/Scripts/EvaluateMLModllAtProduction/README.md
  Packs/ML/TestPlaybooks/playbook-Create_Phishing_Classifier_V2_ML_Test.yml
  Packs/ML/TestPlaybooks/playbook-DBotPredictOutOfTheBoxV2-test.yml
  Packs/ML/TestPlaybooks/playbook-DBot_Create_Phishing_Classifier_V2_From_File-_Test.yml
  Packs/ML/TestPlaybooks/script-CompareEnvPredictionsToExpectedPredictions.yml
  Packs/ML/TestPlaybooks/script-CreateIncidentsForEvaluateMLModllAtProduction.yml
  Packs/ML/TestPlaybooks/script-CreateIncidentsOutOfTheBoxV2.yml
  Packs/ML/pack_metadata.json
  Tests/conf.json
Labels: docs-approved, ForceMerge

#35106 PrismaCloud V2 dashboard update
  Packs/PrismaCloud/CONTRIBUTORS.json
  Packs/PrismaCloud/Dashboards/dashboard-Prisma_Cloud_Incidents.json
  Packs/PrismaCloud/Integrations/PrismaCloudV2/PrismaCloudV2.py
  Packs/PrismaCloud/ReleaseNotes/4_3_7.md
  Packs/PrismaCloud/pack_metadata.json
Labels: Contribution, Contribution Form Filled, Community, Xsoar Support Level, External PR, Security Review

#35371 Raise armis event collector default limit
  Packs/Armis/Integrations/ArmisEventCollector/ArmisEventCollector.yml
  Packs/Armis/Integrations/ArmisEventCollector/ArmisEventCollector_description.md
  Packs/Armis/ReleaseNotes/1_1_16.json
  Packs/Armis/ReleaseNotes/1_1_16.md
  Packs/Armis/pack_metadata.json
Labels: docs-approved

#35348 [Google Threat Intelligence] Add curated collections commands and improve polling commands
  Packs/GoogleThreatIntelligence/Integrations/GoogleThreatIntelligence/GoogleThreatIntelligence.py
  Packs/GoogleThreatIntelligence/Integrations/GoogleThreatIntelligence/GoogleThreatIntelligence.yml
  Packs/GoogleThreatIntelligence/Integrations/GoogleThreatIntelligence/GoogleThreatIntelligence_image.png
  Packs/GoogleThreatIntelligence/Integrations/GoogleThreatIntelligence/GoogleThreatIntelligence_test.py
  Packs/GoogleThreatIntelligence/ReleaseNotes/1_0_1.md
  Packs/GoogleThreatIntelligence/pack_metadata.json
Labels: Contribution, Partner, Contribution Form Filled, Partner Support Level, External PR, Partner-Approved, TIM Review

#35354 Fix for 'Search For Hash In Sandbox - Generic' playbook
  Packs/CommonPlaybooks/Playbooks/playbook-Search_For_Hash_In_Sandbox_-_Generic.yml
  Packs/CommonPlaybooks/ReleaseNotes/2_6_35.md
  Packs/CommonPlaybooks/doc_files/Search_For_Hash_In_Sandbox_-_Generic.png
  Packs/CommonPlaybooks/pack_metadata.json
Labels: docs-approved

#35298 Fix SNOW files mirroring issue
  Packs/ServiceNow/Integrations/ServiceNowv2/ServiceNowv2.py
  Packs/ServiceNow/Integrations/ServiceNowv2/ServiceNowv2.yml
  Packs/ServiceNow/Integrations/ServiceNowv2/ServiceNowv2_test.py
  Packs/ServiceNow/Integrations/ServiceNowv2/test_data/response_constants.py
  Packs/ServiceNow/ReleaseNotes/2_6_6.md
  Packs/ServiceNow/pack_metadata.json
Labels: docs-approved

#35267 Add support for [Get/Export/Release]-QuarantineMessage to EWSO PS v3
  Packs/MicrosoftExchangeOnline/Integrations/EwsExtensionEXOPowershellV3/EwsExtensionEXOPowershellV3.ps1
  Packs/MicrosoftExchangeOnline/Integrations/EwsExtensionEXOPowershellV3/EwsExtensionEXOPowershellV3.yml
  Packs/MicrosoftExchangeOnline/Integrations/EwsExtensionEXOPowershellV3/README.md
  Packs/MicrosoftExchangeOnline/ReleaseNotes/1_4_0.md
  Packs/MicrosoftExchangeOnline/pack_metadata.json
Labels: Contribution, docs-approved, Contribution Form Filled, Community, Xsoar Support Level, External PR

#35367 XSUP-38544/DisplayHtmlWithImages/fix_text_color
  Packs/CommonScripts/ReleaseNotes/1_15_27.md
  Packs/CommonScripts/Scripts/DisplayHTMLWithImages/DisplayHTMLWithImages.py
  Packs/CommonScripts/Scripts/DisplayHTMLWithImages/DisplayHTMLWithImages.yml
  Packs/CommonScripts/Scripts/DisplayHTMLWithImages/DisplayHTMLWithImages_test.py
  Packs/CommonScripts/pack_metadata.json
Labels: docs-approved

#35378 remove IN150 from validation_config.toml
  validation_config.toml
Labels: docs-approved
