Repository demisto/content, pull requests merged in 2024-04, with the labels that each got.

#33654 [PrismaCloud v2] Issue With Docker Timeout Instead `urlib` Timeout
  Packs/PrismaCloud/Integrations/PrismaCloudV2/PrismaCloudV2.py
  Packs/PrismaCloud/Integrations/PrismaCloudV2/PrismaCloudV2.yml
  Packs/PrismaCloud/Integrations/PrismaCloudV2/PrismaCloudV2_test.py
  Packs/PrismaCloud/ReleaseNotes/4_3_1.md
  Packs/PrismaCloud/pack_metadata.json
Labels: docs-approved

#33664 Fixed typos in documentation page for StringReplace
  Packs/CommonScripts/Scripts/StringReplace/README.md
Labels: docs-approved

#33289 Add trigger-contribution-build job
  .gitlab/ci/.gitlab-ci.global.yml
  .gitlab/ci/.gitlab-ci.on-push.yml
  .gitlab/ci/.gitlab-ci.trigger-contribution-build.yml
  .gitlab/ci/.gitlab-ci.yml
  Utils/tests/test_trigger_contribution_build.py
  Utils/trigger_contribution_build.py
Labels: docs-approved, nightly-ok

#33647 [Build Machines Cleanup] Fix issue in uninstall packs
  .gitlab/ci/.gitlab-ci.build-machines-cleanup.yml
  .gitlab/ci/.gitlab-ci.variables.yml
  Tests/Marketplace/search_and_uninstall_pack.py
  Tests/scripts/uninstall_packs_and_reset_bucket_cloud.sh
Labels: docs-approved, nightly-ok

#33251 Create Xpanse Wizard
  Packs/CortexXpanse/ReleaseNotes/1_0_21.md
  Packs/CortexXpanse/Wizards/wizard-Xpanse_ASM.json
  Packs/CortexXpanse/pack_metadata.json
Labels: Contribution, Contribution Form Filled, Community, Xsoar Support Level, External PR, Security Review

#33495 fix file with invalid name
  Packs/LogPoint_SIEM_Integration/Classifiers/classifier-mapper-incoming-LogPoint_SIEM_Integration.json
  Packs/LogPoint_SIEM_Integration/ReleaseNotes/1_2_9.md
  Packs/LogPoint_SIEM_Integration/pack_metadata.json
Labels: docs-approved

#33686 [CIAC-10181] Remove trigger contribution build GitHub workflow
  .github/workflows/trigger-contribution-build.yml
  Utils/github_workflow_scripts/trigger_contribution_build.py
Labels: docs-approved

#33663 Jira v3 remove mirroring prameters
  Packs/Jira/Integrations/JiraV3/JiraV3.yml
  Packs/Jira/ReleaseNotes/3_1_13.md
  Packs/Jira/pack_metadata.json
Labels: docs-approved

#33690 Release base pack v1.33.46
  Packs/Base/ReleaseNotes/1_33_46.md
  Packs/Base/Scripts/SanePdfReport/SanePdfReport.yml
  Packs/Base/pack_metadata.json
Labels: docs-approved

#33367 Feature: Add Field Effect Broker Support
  Packs/CovalenceManagedSecurity/Integrations/CovalenceManagedSecurity/CovalenceManagedSecurity.py
  Packs/CovalenceManagedSecurity/Integrations/CovalenceManagedSecurity/CovalenceManagedSecurity.yml
  Packs/CovalenceManagedSecurity/Integrations/CovalenceManagedSecurity/CovalenceManagedSecurity_description.md
  Packs/CovalenceManagedSecurity/Integrations/CovalenceManagedSecurity/CovalenceManagedSecurity_test.py
  Packs/CovalenceManagedSecurity/Integrations/CovalenceManagedSecurity/README.md
  Packs/CovalenceManagedSecurity/Integrations/CovalenceManagedSecurity/command_examples
  Packs/CovalenceManagedSecurity/Integrations/CovalenceManagedSecurity/test_data/broker_cloud_action.json
  Packs/CovalenceManagedSecurity/Integrations/CovalenceManagedSecurity/test_data/broker_endpoint_action.json
  Packs/CovalenceManagedSecurity/Integrations/CovalenceManagedSecurity/test_data/broker_list_org.json
  Packs/CovalenceManagedSecurity/README.md
  Packs/CovalenceManagedSecurity/ReleaseNotes/1_2_0.md
  Packs/CovalenceManagedSecurity/pack_metadata.json
Labels: Contribution, Partner, post-demo, Contribution Form Filled, pending-contributor, Partner Support Level, External PR, Partner-Approved

#33693 Re-Enable MongoDB TPB
  Tests/conf.json
Labels: docs-approved

#33332 [ThreatGridv2] fix analysis_sample_command, get_dbotscore
  Packs/ThreatGrid/Integrations/ThreatGridv2/ThreatGridv2.py
  Packs/ThreatGrid/Integrations/ThreatGridv2/ThreatGridv2_test.py
  Packs/ThreatGrid/ReleaseNotes/2_0_21.md
  Packs/ThreatGrid/pack_metadata.json
Labels: docs-approved

#33697 increase memory for Alienvault_OTX_v2
  Tests/conf.json
Labels: docs-approved

#33688 URL Regex update - Allowing commas
  Packs/Base/TestPlaybooks/playbook-URLextraction-Test.yml
  Packs/CommonTypes/IndicatorTypes/reputation-url.json
  Packs/CommonTypes/ReleaseNotes/3_4_8.md
  Packs/CommonTypes/pack_metadata.json
Labels: docs-approved

#33551 condition on next trigger
  Packs/Netskope/Integrations/NetskopeEventCollector/NetskopeEventCollector.py
  Packs/Netskope/Integrations/NetskopeEventCollector/NetskopeEventCollector.yml
  Packs/Netskope/Integrations/NetskopeEventCollector/NetskopeEventCollector_test.py
  Packs/Netskope/ReleaseNotes/3_3_9.md
  Packs/Netskope/pack_metadata.json
Labels: docs-approved

#33324 Add gentec security center
  Packs/Base/ReleaseNotes/1_33_47.md
  Packs/Base/Scripts/CommonServerPython/CommonServerPython.py
  Packs/Base/pack_metadata.json
  Packs/GenetecSecurityCenter/.pack-ignore
  Packs/GenetecSecurityCenter/.secrets-ignore
  Packs/GenetecSecurityCenter/Integrations/GenetecSecurityCenterEventCollector/GenetecSecurityCenterEventCollector.py
  Packs/GenetecSecurityCenter/Integrations/GenetecSecurityCenterEventCollector/GenetecSecurityCenterEventCollector.yml
  Packs/GenetecSecurityCenter/Integrations/GenetecSecurityCenterEventCollector/GenetecSecurityCenterEventCollector_description.md
  Packs/GenetecSecurityCenter/Integrations/GenetecSecurityCenterEventCollector/GenetecSecurityCenterEventCollector_image.png
  Packs/GenetecSecurityCenter/Integrations/GenetecSecurityCenterEventCollector/GenetecSecurityCenterEventCollector_test.py
  Packs/GenetecSecurityCenter/Integrations/GenetecSecurityCenterEventCollector/README.md
  Packs/GenetecSecurityCenter/Integrations/GenetecSecurityCenterEventCollector/command_examples
  Packs/GenetecSecurityCenter/ModelingRules/GenetecSecurityCenter/GenetecSecurityCenter.xif
  Packs/GenetecSecurityCenter/ModelingRules/GenetecSecurityCenter/GenetecSecurityCenter.yml
  Packs/GenetecSecurityCenter/ModelingRules/GenetecSecurityCenter/GenetecSecurityCenter_schema.json
  Packs/GenetecSecurityCenter/README.md
  Packs/GenetecSecurityCenter/pack_metadata.json
Labels: docs-approved

#33699 [run-pre-commit] fix rules
  .gitlab/ci/.gitlab-ci.on-push.yml
Labels: docs-approved, nightly-ok

#33400 added v2 for fortisandbox, deprecated v1 and playbooks
  Packs/CommonDashboards/Dashboards/dashboard-APIExecutionMetrics.json
  Packs/CommonDashboards/ReleaseNotes/1_4_0.md
  Packs/CommonDashboards/pack_metadata.json
  Packs/FortiSandbox/.secrets-ignore
  Packs/FortiSandbox/Dashboards/FortiSandbox_API_Execution_Metrics.json
  Packs/FortiSandbox/Integrations/FortiSandbox/FortiSandbox.yml
  Packs/FortiSandbox/Integrations/FortiSandboxv2/FortiSandboxv2.py
  Packs/FortiSandbox/Integrations/FortiSandboxv2/FortiSandboxv2.yml
  Packs/FortiSandbox/Integrations/FortiSandboxv2/FortiSandboxv2_description.md
  Packs/FortiSandbox/Integrations/FortiSandboxv2/FortiSandboxv2_image.png
  Packs/FortiSandbox/Integrations/FortiSandboxv2/FortiSandboxv2_test.py
  Packs/FortiSandbox/Integrations/FortiSandboxv2/README.md
  Packs/FortiSandbox/Integrations/FortiSandboxv2/test_data/file_verdict_known.json
  Packs/FortiSandbox/Integrations/FortiSandboxv2/test_data/file_verdict_unknown.json
  Packs/FortiSandbox/Integrations/FortiSandboxv2/test_data/job_list_done.json
  Packs/FortiSandbox/Integrations/FortiSandboxv2/test_data/job_list_empty.json
  Packs/FortiSandbox/Integrations/FortiSandboxv2/test_data/job_list_inprogress.json
  Packs/FortiSandbox/Integrations/FortiSandboxv2/test_data/job_report.json
  Packs/FortiSandbox/Integrations/FortiSandboxv2/test_data/job_verdict.json
  Packs/FortiSandbox/Integrations/FortiSandboxv2/test_data/job_verdict_inprogress.json
  Packs/FortiSandbox/Integrations/FortiSandboxv2/test_data/url_rating_known.json
  Packs/FortiSandbox/Integrations/FortiSandboxv2/test_data/url_rating_unknown.json
  Packs/FortiSandbox/Playbooks/playbook-Detonate_File-FortiSandbox.yml
  Packs/FortiSandbox/Playbooks/playbook-FortiSandbox_-_Loop_For_Job_Verdict.yml
  Packs/FortiSandbox/Playbooks/playbook-FortiSandbox_-_Loop_for_Job_Submissions.yml
  Packs/FortiSandbox/Playbooks/playbook-FortiSandbox_-_Upload_Multiple_Files.yml
  Packs/FortiSandbox/ReleaseNotes/2_0_0.md
  Packs/FortiSandbox/TestPlaybooks/playbook-FortiSandboxv2_Test.yml
  Packs/FortiSandbox/Widgets/Widget-FortiSandbox2.json
  Packs/FortiSandbox/pack_metadata.json
Labels: Contribution, docs-approved, Contribution Form Filled, Community, Xsoar Support Level, External PR, Security Review

#33413 MS Defender Threat Hunting move to Graph API
  Packs/MicrosoftGraphSecurity/Integrations/MicrosoftGraphSecurity/MicrosoftGraphSecurity.py
  Packs/MicrosoftGraphSecurity/Integrations/MicrosoftGraphSecurity/MicrosoftGraphSecurity.yml
  Packs/MicrosoftGraphSecurity/Integrations/MicrosoftGraphSecurity/MicrosoftGraphSecurity_test.py
  Packs/MicrosoftGraphSecurity/Integrations/MicrosoftGraphSecurity/README.md
  Packs/MicrosoftGraphSecurity/Integrations/MicrosoftGraphSecurity/command_examples.txt
  Packs/MicrosoftGraphSecurity/Integrations/MicrosoftGraphSecurity/test_data/advanced_hunting_response.json
  Packs/MicrosoftGraphSecurity/Integrations/MicrosoftGraphSecurity/test_data/advanced_hunting_results.json
  Packs/MicrosoftGraphSecurity/Integrations/MicrosoftGraphSecurity/test_data/advanced_hunting_results_365_defenfer.json
  Packs/MicrosoftGraphSecurity/Integrations/MicrosoftGraphSecurity/test_data/incident_update_response.json
  Packs/MicrosoftGraphSecurity/Integrations/MicrosoftGraphSecurity/test_data/incident_update_results.json
  Packs/MicrosoftGraphSecurity/Integrations/MicrosoftGraphSecurity/test_data/incidents_list_response.json
  Packs/MicrosoftGraphSecurity/Integrations/MicrosoftGraphSecurity/test_data/incidents_list_results.json
  Packs/MicrosoftGraphSecurity/Integrations/MicrosoftGraphSecurity/test_data/incidents_single_response.json
  Packs/MicrosoftGraphSecurity/Integrations/MicrosoftGraphSecurity/test_data/incidents_single_results.json
  Packs/MicrosoftGraphSecurity/ReleaseNotes/2_2_13.md
  Packs/MicrosoftGraphSecurity/ReleaseNotes/2_2_14.md
  Packs/MicrosoftGraphSecurity/TestPlaybooks/playbook-Microsoft_Graph_Test_V2.yml
  Packs/MicrosoftGraphSecurity/pack_metadata.json
Labels: docs-approved

#33604 Update README.md
  Packs/EmailCommunication/README.md
Labels: Contribution, Contribution Form Filled, Community, Xsoar Support Level, External PR

#33661 Absolute xsup 35504
  Packs/Absolute/Integrations/Absolute/Absolute.py
  Packs/Absolute/Integrations/Absolute/Absolute.yml
  Packs/Absolute/Integrations/Absolute/Absolute_test.py
  Packs/Absolute/ReleaseNotes/1_0_23.md
  Packs/Absolute/pack_metadata.json
Labels: docs-approved, ForceMerge

#33721 Fix validate invalid flag issue
  Tests/scripts/new_validate.sh
Labels: docs-approved

#33587 Ibm guardium modeling
  Packs/IBMGuardium/.pack-ignore
  Packs/IBMGuardium/.secrets-ignore
  Packs/IBMGuardium/ModelingRules/IBMGuardium/IBMGuardium.xif
  Packs/IBMGuardium/ModelingRules/IBMGuardium/IBMGuardium.yml
  Packs/IBMGuardium/ModelingRules/IBMGuardium/IBMGuardium_schema.json
  Packs/IBMGuardium/README.md
  Packs/IBMGuardium/pack_metadata.json
Labels: docs-approved

#33698 XSUP-34949/Added a sort argument to 2 commands in CS Falcon
  Packs/CrowdStrikeFalcon/Integrations/CrowdStrikeFalcon/CrowdStrikeFalcon.py
  Packs/CrowdStrikeFalcon/Integrations/CrowdStrikeFalcon/CrowdStrikeFalcon.yml
  Packs/CrowdStrikeFalcon/Integrations/CrowdStrikeFalcon/CrowdStrikeFalcon_test.py
  Packs/CrowdStrikeFalcon/Integrations/CrowdStrikeFalcon/README.md
  Packs/CrowdStrikeFalcon/ReleaseNotes/1_13_3.md
  Packs/CrowdStrikeFalcon/pack_metadata.json
Labels: docs-approved, ForceMerge

#33106 STIX Parser API Module
  Packs/ApiModules/.secrets-ignore
  Packs/ApiModules/Scripts/TAXII2ApiModule/TAXII2ApiModule.py
  Packs/ApiModules/Scripts/TAXII2ApiModule/TAXII2ApiModule.yml
  Packs/ApiModules/Scripts/TAXII2ApiModule/TAXII2ApiModule_test.py
  Packs/ApiModules/Scripts/TAXII2ApiModule/test_data/create_indicators_test_results.json
  Packs/ApiModules/Scripts/TAXII2ApiModule/test_data/create_relationships_test.json
  Packs/ApiModules/Scripts/TAXII2ApiModule/test_data/entity_b_iocs.json
  Packs/ApiModules/Scripts/TAXII2ApiModule/test_data/indicator_publication_test.json
  Packs/ApiModules/Scripts/TAXII2ApiModule/test_data/ioc_for_report_relationship.json
  Packs/ApiModules/Scripts/TAXII2ApiModule/test_data/objects21_file.json
  Packs/ApiModules/Scripts/TAXII2ApiModule/test_data/parsed_stix_objects.json
  Packs/ApiModules/Scripts/TAXII2ApiModule/test_data/relationship_report_file.json
  Packs/ApiModules/Scripts/TAXII2ApiModule/test_data/sco_indicator_file.json
  Packs/ApiModules/Scripts/TAXII2ApiModule/test_data/searchRelationships-response.json
  Packs/ApiModules/Scripts/TAXII2ApiModule/test_data/sort_ip_iocs.json
  Packs/ApiModules/Scripts/TAXII2ApiModule/test_data/stix_sco_indicators.json
  Packs/ApiModules/Scripts/TAXII2ApiModule/test_data/xsoar_sco_indicators.json
  Packs/Base/ReleaseNotes/1_33_48.md
  Packs/Base/Scripts/CommonServerPython/CommonServerPython.py
  Packs/Base/pack_metadata.json
  Packs/CommonScripts/ReleaseNotes/1_14_25.md
  Packs/CommonScripts/Scripts/StixCreator/StixCreator.py
  Packs/CommonScripts/Scripts/StixCreator/StixCreator.yml
  Packs/CommonScripts/Scripts/StixCreator/StixCreator_test.py
  Packs/CommonScripts/pack_metadata.json
  Packs/DeveloperTools/TestPlaybooks/TAXII2_Server_Performance_Test.yml
  Packs/FeedDHS/ReleaseNotes/2_0_37.md
  Packs/FeedDHS/pack_metadata.json
  Packs/FeedMitreAttackv2/Integrations/FeedMitreAttackv2/FeedMitreAttackv2.py
  Packs/FeedMitreAttackv2/Integrations/FeedMitreAttackv2/FeedMitreAttackv2.yml
  Packs/FeedMitreAttackv2/Integrations/FeedMitreAttackv2/FeedMitreAttackv2_test.py
  Packs/FeedMitreAttackv2/ReleaseNotes/1_1_33.md
  Packs/FeedMitreAttackv2/pack_metadata.json
  Packs/FeedTAXII/Integrations/FeedTAXII2/FeedTAXII2.yml
  Packs/FeedTAXII/ReleaseNotes/1_2_12.md
  Packs/FeedTAXII/pack_metadata.json
  Packs/FeedUnit42v2/Integrations/FeedUnit42v2/FeedUnit42v2.py
  Packs/FeedUnit42v2/Integrations/FeedUnit42v2/FeedUnit42v2.yml
  Packs/FeedUnit42v2/Integrations/FeedUnit42v2/FeedUnit42v2_test.py
  Packs/FeedUnit42v2/Integrations/FeedUnit42v2/test_data/feed_data.py
  Packs/FeedUnit42v2/ReleaseNotes/1_0_50.md
  Packs/FeedUnit42v2/pack_metadata.json
  Packs/TAXIIServer/Integrations/TAXII2Server/TAXII2Server.py
  Packs/TAXIIServer/Integrations/TAXII2Server/TAXII2Server.yml
  Packs/TAXIIServer/Integrations/TAXII2Server/TAXII2Server_test.py
  Packs/TAXIIServer/Integrations/TAXII2Server/test_data/objects21_malware.json
  Packs/TAXIIServer/ReleaseNotes/2_0_59.md
  Packs/TAXIIServer/pack_metadata.json
  Tests/conf.json
Labels: docs-approved, ForceMerge

#32411 upload-metadata-file-update
  Tests/Marketplace/Tests/marketplace_services_test.py
  Tests/Marketplace/Tests/upload_packs_test.py
  Tests/Marketplace/marketplace_constants.py
  Tests/Marketplace/marketplace_services.py
  Tests/Marketplace/upload_packs.py
  Tests/private_build/marketplace_services_private.py
  Tests/scripts/collect_tests/collect_tests.py
  Tests/scripts/collect_tests/path_manager.py
  Tests/scripts/collect_tests/utils.py
  Tests/scripts/infrastructure_tests/test_collect_tests.py
  Tests/scripts/prepare_content_packs_for_testing.sh
  Utils/test_upload_flow/create_test_branch.py
  Utils/test_upload_flow/verify_bucket.py
Labels: docs-approved

#33541 added fetch-events
  Packs/Akamai_SIEM/.pack-ignore
  Packs/Akamai_SIEM/Integrations/Akamai_SIEM/Akamai_SIEM.py
  Packs/Akamai_SIEM/Integrations/Akamai_SIEM/Akamai_SIEM.yml
  Packs/Akamai_SIEM/Integrations/Akamai_SIEM/Akamai_SIEM_test.py
  Packs/Akamai_SIEM/Integrations/Akamai_SIEM/Akamai_SIEM_test/TestCommandsFunctions/sec_events_six_results.txt
  Packs/Akamai_SIEM/Integrations/Akamai_SIEM/Akamai_SIEM_test/TestCommandsFunctions/sec_events_two_results.txt
  Packs/Akamai_SIEM/ModelingRules/Akamai_WAF/Akamai_WAF.xif
  Packs/Akamai_SIEM/ModelingRules/Akamai_WAF/Akamai_WAF.yml
  Packs/Akamai_SIEM/ModelingRules/Akamai_WAF/Akamai_WAF_schema.json
  Packs/Akamai_SIEM/ReleaseNotes/1_1_0.json
  Packs/Akamai_SIEM/ReleaseNotes/1_1_0.md
  Packs/Akamai_SIEM/pack_metadata.json
Labels: docs-approved, ForceMerge

#33711 printing instance connection ssh command within build logs.
  .gitlab/ci/.gitlab-ci.bucket-upload.yml
  .gitlab/ci/.gitlab-ci.on-push.yml
Labels: docs-approved, ForceMerge, nightly-ok

#33590 fix: prevent incidents time range control at fetch incidents
  Packs/LogsignSiem/Integrations/LogsignSiem/LogsignSiem.py
  Packs/LogsignSiem/ReleaseNotes/1_0_13.md
  Packs/LogsignSiem/pack_metadata.json
Labels: Contribution, Partner, Contribution Form Filled, Partner Support Level, External PR, Partner-Approved

#33646 YR/Add-Bearer-Token-Authentication/Jamfv2/CIAC-10058
  Packs/jamf/Integrations/jamfV2/README.md
  Packs/jamf/Integrations/jamfV2/jamfV2.py
  Packs/jamf/Integrations/jamfV2/jamfV2.yml
  Packs/jamf/Integrations/jamfV2/jamfV2_description.md
  Packs/jamf/Integrations/jamfV2/jamfV2_test.py
  Packs/jamf/ReleaseNotes/2_2_0.md
  Packs/jamf/pack_metadata.json
Labels: docs-approved, ForceMerge

#33659 reco.py: change validate api key endpoint
  Packs/Reco/Integrations/Reco/Reco.py
  Packs/Reco/Integrations/Reco/Reco.yml
  Packs/Reco/Integrations/Reco/Reco_test.py
  Packs/Reco/ReleaseNotes/1_2_1.md
  Packs/Reco/pack_metadata.json
Labels: Contribution, Partner, Contribution Form Filled, Partner Support Level, External PR, Partner-Approved, TIM Review

#33738 Revert "Ibm guardium modeling"
  Packs/IBMGuardium/.pack-ignore
  Packs/IBMGuardium/.secrets-ignore
  Packs/IBMGuardium/ModelingRules/IBMGuardium/IBMGuardium.xif
  Packs/IBMGuardium/ModelingRules/IBMGuardium/IBMGuardium.yml
  Packs/IBMGuardium/ModelingRules/IBMGuardium/IBMGuardium_schema.json
  Packs/IBMGuardium/README.md
  Packs/IBMGuardium/pack_metadata.json
Labels: ForceMerge

#33644 fix pre commit -a
  .github/workflows/pre-commit-reuse.yml
  .gitlab/ci/.gitlab-ci.bucket-upload.yml
  .gitlab/ci/.gitlab-ci.global.yml
  .gitlab/ci/.gitlab-ci.variables.yml
  .pre-commit-config_template.yaml
  Packs/Base/Scripts/SanePdfReport/SanePdfReport_test.py
  Packs/CommonScripts/Scripts/ConvertFile/ConvertFile_test.py
  Packs/CommonScripts/Scripts/DockerHardeningCheck/DockerHardeningCheck_test.py
  Tests/scripts/lock_cloud_machines.py
  Tests/test_content.py
  Utils/merge_content_new_zip.py
Labels: docs-approved, nightly-ok

#33728 [Trigger contribution build] Add missing ENV variable in trigger pipeline request
  Utils/trigger_contribution_build.py
Labels: docs-approved

#33691 [Prisma cloud v2] Update Test Module Timeout
  Packs/PrismaCloud/Integrations/PrismaCloudV2/PrismaCloudV2.py
  Packs/PrismaCloud/ReleaseNotes/4_3_2.md
  Packs/PrismaCloud/pack_metadata.json
Labels: docs-approved

#33371 Changes related to the Rubrik release 1.3.1
  Packs/RubrikPolaris/.secrets-ignore
  Packs/RubrikPolaris/Classifiers/classifier-Rubrik_Polaris_Radar_-_Mapping.json
  Packs/RubrikPolaris/Integrations/RubrikPolaris/README.md
  Packs/RubrikPolaris/Integrations/RubrikPolaris/RubrikPolaris.py
  Packs/RubrikPolaris/Integrations/RubrikPolaris/RubrikPolaris.yml
  Packs/RubrikPolaris/Integrations/RubrikPolaris/RubrikPolaris_test.py
  Packs/RubrikPolaris/Integrations/RubrikPolaris/test_data/gps_snapshot_file_download_response.json
  Packs/RubrikPolaris/Integrations/RubrikPolaris/test_data/radar_suspicious_file_list_hr.md
  Packs/RubrikPolaris/Integrations/RubrikPolaris/test_data/radar_suspicious_file_list_no_anomalies_hr.md
  Packs/RubrikPolaris/Integrations/RubrikPolaris/test_data/radar_suspicious_file_list_response.json
  Packs/RubrikPolaris/Playbooks/playbook-Rubrik_Anomaly_Incident_Response_-_Rubrik_Polaris.yml
  Packs/RubrikPolaris/Playbooks/playbook-Rubrik_Anomaly_Incident_Response_-_Rubrik_Polaris_README.md
  Packs/RubrikPolaris/Playbooks/playbook-Rubrik_File_Context_Analysis_-_Rubrik_Polaris.yml
  Packs/RubrikPolaris/Playbooks/playbook-Rubrik_File_Context_Analysis_-_Rubrik_Polaris_README.md
  Packs/RubrikPolaris/Playbooks/playbook-Rubrik_Object_Context_Analysis_-_Rubrik_Polaris.yml
  Packs/RubrikPolaris/Playbooks/playbook-Rubrik_Object_Context_Analysis_-_Rubrik_Polaris_README.md
  Packs/RubrikPolaris/Playbooks/playbook-Rubrik_Poll_Async_Result_-_Rubrik_Polaris.yml
  Packs/RubrikPolaris/Playbooks/playbook-Rubrik_Poll_Async_Result_-_Rubrik_Polaris_README.md
  Packs/RubrikPolaris/Playbooks/playbook-Rubrik_Retrieve_Anomaly_Result_-_Rubrik_Security_Cloud.yml
  Packs/RubrikPolaris/Playbooks/playbook-Rubrik_Retrieve_Anomaly_Result_-_Rubrik_Security_Cloud_README.md
  Packs/RubrikPolaris/Playbooks/playbook-Rubrik_Retrieve_User_Access_Information_-_Rubrik_Polaris.yml
  Packs/RubrikPolaris/Playbooks/playbook-Rubrik_Retrieve_User_Access_Information_-_Rubrik_Polaris_README.md
  Packs/RubrikPolaris/Playbooks/playbook-Rubrik_User_Access_Analysis_-_Rubrik_Polaris.yml
  Packs/RubrikPolaris/Playbooks/playbook-Rubrik_User_Access_Analysis_-_Rubrik_Polaris_README.md
  Packs/RubrikPolaris/ReleaseNotes/1_3_1.md
  Packs/RubrikPolaris/TestPlaybooks/playbook-RubrikPolaris-test.yml
  Packs/RubrikPolaris/doc_files/Rubrik_Anomaly_Incident_Response_-_Rubrik_Polaris.png
  Packs/RubrikPolaris/doc_files/Rubrik_Poll_Async_Result_-_Rubrik_Polaris.png
  Packs/RubrikPolaris/doc_files/Rubrik_Retrieve_Anomaly_Result_-_Rubrik_Security_Cloud.png
  Packs/RubrikPolaris/pack_metadata.json
Labels: Contribution, Partner, Contribution Form Filled, Partner Support Level, External PR, Security Review, Partner-Approved

#33750 add readme docs
  Packs/CrowdStrikeFalcon/Integrations/CrowdStrikeFalcon/README.md
Labels: docs-approved

#33736 Generic sql - problem with Teradata DB results
  Packs/GenericSQL/Integrations/GenericSQL/GenericSQL.py
  Packs/GenericSQL/ReleaseNotes/1_2_4.md
  Packs/GenericSQL/pack_metadata.json
Labels: docs-approved

#33754 ews workaround
  Packs/MicrosoftExchangeOnline/Integrations/EWSO365/EWSO365.py
  Packs/MicrosoftExchangeOnline/Integrations/EWSO365/EWSO365_test.py
  Packs/MicrosoftExchangeOnline/ReleaseNotes/1_3_0.md
  Packs/MicrosoftExchangeOnline/pack_metadata.json
Labels: docs-approved

#33700 Add XSOAR Saas bucket to SDK nightly test upload
  .gitlab/ci/.gitlab-ci.sdk-nightly.yml
Labels: docs-approved, nightly-ok

#33719 Fix search hash in sandbox generic cs falcon
  Packs/CommonPlaybooks/Playbooks/playbook-Search_For_Hash_In_Sandbox_-_Generic.yml
  Packs/CommonPlaybooks/ReleaseNotes/2_6_27.md
  Packs/CommonPlaybooks/pack_metadata.json
Labels: docs-approved

#33696 new dashboard
  Packs/CommonDashboards/Dashboards/XSOAR_Automation_Insights.json
  Packs/CommonDashboards/ReleaseNotes/1_4_1.md
  Packs/CommonDashboards/pack_metadata.json
Labels: docs-approved

#33558 Fixing incident alerts and artifacts is not populated
  Packs/CortexXDR/Integrations/CortexXDRIR/CortexXDRIR.py
  Packs/CortexXDR/Integrations/CortexXDRIR/CortexXDRIR_test.py
  Packs/CortexXDR/Integrations/CortexXDRIR/test_data/get_extra_data_all_alerts.json
  Packs/CortexXDR/Integrations/CortexXDRIR/test_data/get_incident_extra_data_new_status.json
  Packs/CortexXDR/ReleaseNotes/6_1_27.md
  Packs/CortexXDR/pack_metadata.json
Labels: docs-approved, ForceMerge

#33645 Web file repository - Fixed where large file uploading fails.
  Packs/WebFileRepository/Integrations/WebFileRepository/WebFileRepository.py
  Packs/WebFileRepository/Integrations/WebFileRepository/WebFileRepository_test.py
  Packs/WebFileRepository/ReleaseNotes/1_0_26.md
  Packs/WebFileRepository/pack_metadata.json
Labels: Contribution, Contribution Form Filled, Community, Community Support Level, External PR

#33240 Qualys VMDR unify
  Packs/qualys/.pack-ignore
  Packs/qualys/Integrations/QualysEventCollector/QualysEventCollector.py
  Packs/qualys/Integrations/QualysEventCollector/QualysEventCollector.yml
  Packs/qualys/Integrations/QualysEventCollector/QualysEventCollector_description.md
  Packs/qualys/Integrations/QualysEventCollector/QualysEventCollector_image.png
  Packs/qualys/Integrations/QualysEventCollector/QualysEventCollector_test.py
  Packs/qualys/Integrations/QualysEventCollector/README.md
  Packs/qualys/Integrations/QualysEventCollector/command_examples
  Packs/qualys/Integrations/Qualysv2/Qualysv2.py
  Packs/qualys/Integrations/Qualysv2/Qualysv2.yml
  Packs/qualys/Integrations/Qualysv2/Qualysv2_dark.svg
  Packs/qualys/Integrations/Qualysv2/Qualysv2_light.svg
  Packs/qualys/Integrations/Qualysv2/Qualysv2_test.py
  Packs/qualys/Integrations/Qualysv2/README.md
  Packs/qualys/Integrations/Qualysv2/test_data/activity_logs.csv
  Packs/qualys/Integrations/Qualysv2/test_data/host_list_detections_raw.xml
  Packs/qualys/Integrations/Qualysv2/test_data/vulnerabilities_raw.xml
  Packs/qualys/ReleaseNotes/3_0_0.json
  Packs/qualys/ReleaseNotes/3_0_0.md
  Packs/qualys/pack_metadata.json
Labels: docs-approved, ForceMerge

#33634 Hyperlink extract from office docs - added to extract indicators from file playbook
  Packs/CommonPlaybooks/Playbooks/playbook-Extract_Indicators_From_File_-_Generic_v2_4_5.yml
  Packs/CommonPlaybooks/ReleaseNotes/2_6_28.md
  Packs/CommonPlaybooks/doc_files/Extract_Indicators_From_File_-_Generic_v2.png
  Packs/CommonPlaybooks/pack_metadata.json
Labels: docs-approved

#33771 Xsup 35665 part 2
  Packs/MicrosoftExchangeOnline/Integrations/EWSO365/EWSO365.py
  Packs/MicrosoftExchangeOnline/ReleaseNotes/1_3_1.md
  Packs/MicrosoftExchangeOnline/pack_metadata.json
Labels: docs-approved

#33609 AWS Lambda - Update Layer Version Command Enhancement
  Packs/AWS-Lambda/Integrations/AWS_Lambda/AWS_Lambda.py
  Packs/AWS-Lambda/Integrations/AWS_Lambda/AWS_Lambda.yml
  Packs/AWS-Lambda/Integrations/AWS_Lambda/AWS_Lambda_test.py
  Packs/AWS-Lambda/Integrations/AWS_Lambda/README.md
  Packs/AWS-Lambda/ReleaseNotes/1_3_4.md
  Packs/AWS-Lambda/pack_metadata.json
Labels: docs-approved

#33709 Dataminr Pulse release 1.0.9
  Packs/DataminrPulse/.pack-ignore
  Packs/DataminrPulse/Integrations/DataminrPulse/DataminrPulse.py
  Packs/DataminrPulse/Integrations/DataminrPulse/DataminrPulse.yml
  Packs/DataminrPulse/ReleaseNotes/1_0_9.md
  Packs/DataminrPulse/pack_metadata.json
Labels: Contribution, Partner, Contribution Form Filled, Partner Support Level, External PR, Partner-Approved, TIM Review

#33763 remove allow failure from new validate steps
  .gitlab/ci/.gitlab-ci.bucket-upload.yml
  .gitlab/ci/.gitlab-ci.on-push.yml
  .gitlab/ci/.gitlab-ci.sdk-nightly.yml
Labels: docs-approved, nightly-ok

#33785 Add support for rule parameter in query-traffic-logs command
  Packs/CortexDataLake/Integrations/CortexDataLake/CortexDataLake.py
  Packs/CortexDataLake/Integrations/CortexDataLake/CortexDataLake.yml
  Packs/CortexDataLake/Integrations/CortexDataLake/CortexDataLake_test.py
  Packs/CortexDataLake/ReleaseNotes/1_4_10.md
  Packs/CortexDataLake/pack_metadata.json
Labels: docs-approved

#33651 [PreprocessEmail] Fix an issue in parsing images
  Packs/Base/ReleaseNotes/1_33_50.md
  Packs/Base/Scripts/CommonServerPython/CommonServerPython.py
  Packs/Base/pack_metadata.json
  Packs/EmailCommunication/ReleaseNotes/2_0_27.md
  Packs/EmailCommunication/Scripts/PreprocessEmail/PreprocessEmail.py
  Packs/EmailCommunication/Scripts/PreprocessEmail/PreprocessEmail.yml
  Packs/EmailCommunication/Scripts/PreprocessEmail/PreprocessEmail_test.py
  Packs/EmailCommunication/pack_metadata.json
  Packs/MicrosoftExchangeOnPremise/Integrations/EWSv2/EWSv2.py
  Packs/MicrosoftExchangeOnPremise/Integrations/EWSv2/EWSv2.yml
  Packs/MicrosoftExchangeOnPremise/ReleaseNotes/2_1_2.md
  Packs/MicrosoftExchangeOnPremise/pack_metadata.json
  Packs/MicrosoftExchangeOnline/Integrations/EWSO365/EWSO365.py
  Packs/MicrosoftExchangeOnline/Integrations/EWSO365/EWSO365.yml
  Packs/MicrosoftExchangeOnline/ReleaseNotes/1_3_3.md
  Packs/MicrosoftExchangeOnline/pack_metadata.json
Labels: docs-approved, ForceMerge

#33788 Review and update CortexXDRIR README.md
  Packs/CortexXDR/Integrations/CortexXDRIR/README.md
Labels: docs-approved

#33607 Crowd strike indicator feed - Get correct threat actor names
  Packs/FeedCrowdstrikeFalconIntel/Integrations/CrowdStrikeIndicatorFeed/CrowdStrikeIndicatorFeed.py
  Packs/FeedCrowdstrikeFalconIntel/Integrations/CrowdStrikeIndicatorFeed/CrowdStrikeIndicatorFeed_test.py
  Packs/FeedCrowdstrikeFalconIntel/Integrations/CrowdStrikeIndicatorFeed/test_data/create_indicators_from_response.json
  Packs/FeedCrowdstrikeFalconIntel/Integrations/CrowdStrikeIndicatorFeed/test_data/crowdstrike_test_actors_convert.json
  Packs/FeedCrowdstrikeFalconIntel/ReleaseNotes/2_1_16.md
  Packs/FeedCrowdstrikeFalconIntel/pack_metadata.json
Labels: docs-approved

#33761 [ServiceNow] Support mirroring notes created before fetch
  Packs/ServiceNow/Integrations/ServiceNowv2/README.md
  Packs/ServiceNow/Integrations/ServiceNowv2/ServiceNowv2.py
  Packs/ServiceNow/Integrations/ServiceNowv2/ServiceNowv2.yml
  Packs/ServiceNow/Integrations/ServiceNowv2/ServiceNowv2_test.py
  Packs/ServiceNow/Integrations/ServiceNowv2/test_data/response_constants.py
  Packs/ServiceNow/ReleaseNotes/2_5_65.md
  Packs/ServiceNow/pack_metadata.json
Labels: docs-approved

#33396 GsuiteAdmin update - 7 new commands
  Packs/GSuiteAdmin/Integrations/GSuiteAdmin/GSuiteAdmin.py
  Packs/GSuiteAdmin/Integrations/GSuiteAdmin/GSuiteAdmin.yml
  Packs/GSuiteAdmin/Integrations/GSuiteAdmin/GSuiteAdmin_description.md
  Packs/GSuiteAdmin/Integrations/GSuiteAdmin/GSuiteAdmin_test.py
  Packs/GSuiteAdmin/Integrations/GSuiteAdmin/README.md
  Packs/GSuiteAdmin/Integrations/GSuiteAdmin/test_data/chromebrowser_list_by_device_response.json
  Packs/GSuiteAdmin/Integrations/GSuiteAdmin/test_data/chromebrowser_list_context.json
  Packs/GSuiteAdmin/Integrations/GSuiteAdmin/test_data/chromebrowser_list_response.json
  Packs/GSuiteAdmin/Integrations/GSuiteAdmin/test_data/chromebrwoser_list_by_device_context.json
  Packs/GSuiteAdmin/Integrations/GSuiteAdmin/test_data/policy_resolve_context.json
  Packs/GSuiteAdmin/Integrations/GSuiteAdmin/test_data/policy_resolve_response.json
  Packs/GSuiteAdmin/Integrations/GSuiteAdmin/test_data/policy_schemas_list_context.json
  Packs/GSuiteAdmin/Integrations/GSuiteAdmin/test_data/policy_schemas_list_context_schema_name.json
  Packs/GSuiteAdmin/Integrations/GSuiteAdmin/test_data/policy_schemas_list_reponse.json
  Packs/GSuiteAdmin/Integrations/GSuiteAdmin/test_data/policy_schemas_list_reponse_schema_name.json
  Packs/GSuiteAdmin/Integrations/GSuiteAdmin/test_data/user_password_reset_context.json
  Packs/GSuiteAdmin/Integrations/GSuiteAdmin/test_data/user_password_reset_response.json
  Packs/GSuiteAdmin/ReleaseNotes/1_2_0.json
  Packs/GSuiteAdmin/ReleaseNotes/1_2_0.md
  Packs/GSuiteAdmin/TestPlaybooks/playbook-GSuiteAdmin-Test.yml
  Packs/GSuiteAdmin/pack_metadata.json
Labels: docs-approved

#33789 [pre-commit] - do not run ruff with parelleisem
  .pre-commit-config_template.yaml
Labels: docs-approved

#33760 fixing all keys deletion
  Packs/CommonScripts/ReleaseNotes/1_14_27.md
  Packs/CommonScripts/Scripts/DeleteContext/DeleteContext.js
  Packs/CommonScripts/TestPlaybooks/playbook-DeleteContext-test.yml
  Packs/CommonScripts/pack_metadata.json
Labels: docs-approved

#33791 Web file repository - Fixed syntax errors
  Packs/WebFileRepository/Integrations/WebFileRepository/WebFileRepository.py
  Packs/WebFileRepository/ReleaseNotes/1_0_27.md
  Packs/WebFileRepository/pack_metadata.json
Labels: Contribution, docs-approved, Contribution Form Filled, Community, Community Support Level, External PR

#33795 bump `actions/setup-python@v5`, `Gr1N/setup-poetry@v9`
  .github/workflows/autobump_rn.yml
  .github/workflows/check-contribution-form-filled.yml
  .github/workflows/check-contributor-pack.yml
  .github/workflows/check-partner-approved-label.yml
  .github/workflows/close_jira_issue_by_pr_merge.yml
  .github/workflows/link_edited_pr_to_jira_issue.yml
  .github/workflows/pre-commit-reuse.yml
  .github/workflows/project_manager_daily.yml
  .github/workflows/project_manager_hourly.yml
  .github/workflows/review-release-notes.yml
  .github/workflows/run-secrets-detection.yml
  .github/workflows/sync-contribution-base-branch-on-change.yml
  .github/workflows/sync-contribution-base-branch.yml
  .github/workflows/update-demisto-sdk-version.yml
  Packs/ContentManagement/doc_files/ci-cd.yml
Labels: docs-approved

#33825 Revert ZipFile image
  Packs/CommonScripts/ReleaseNotes/1_14_28.md
  Packs/CommonScripts/Scripts/ZipFile/ZipFile.py
  Packs/CommonScripts/Scripts/ZipFile/ZipFile.yml
  Packs/CommonScripts/pack_metadata.json
Labels: docs-approved, ForceMerge

#33830 demisto/pcap-miner:1.0.0.91369 | 0-100 | PR batch #1/3
  Packs/PcapAnalysis/Scripts/PcapConvert/PcapConvert.yml
  Packs/PcapAnalysis/Scripts/PcapExtractStreams/PcapExtractStreams.yml
Labels: auto-update-docker

#33805 Docker Hardening test - fix flaky test
  Packs/CommonScripts/ReleaseNotes/1_14_29.md
  Packs/CommonScripts/Scripts/DockerHardeningCheck/DockerHardeningCheck.yml
  Packs/CommonScripts/Scripts/DockerHardeningCheck/DockerHardeningCheck_test.py
  Packs/CommonScripts/pack_metadata.json
Labels: docs-approved

#33707 [malwarebytes-254] Changed Domain to threatdown.com
  Packs/Malwarebytes/Integrations/Malwarebytes/Malwarebytes.py
  Packs/Malwarebytes/Integrations/Malwarebytes/Malwarebytes.yml
  Packs/Malwarebytes/Integrations/Malwarebytes/Malwarebytes_description.md
  Packs/Malwarebytes/Integrations/Malwarebytes/Malwarebytes_test.py
  Packs/Malwarebytes/ReleaseNotes/1_1_16.md
  Packs/Malwarebytes/pack_metadata.json
Labels: Contribution, docs-approved, Partner, pending-demo, Contribution Form Filled, Partner Support Level, External PR, Partner-Approved

#33732 Qradar delete reference set value bug
  Packs/QRadar/Integrations/QRadar_v3/QRadar_v3.py
  Packs/QRadar/ReleaseNotes/2_4_55.md
  Packs/QRadar/pack_metadata.json
Labels: docs-approved

#33831 demisto/pcap-miner:1.0.0.91369 | 0-100 | PR batch #2/3
  Packs/PcapAnalysis/Scripts/PcapFileExtractStreams/PcapFileExtractStreams.yml
  Packs/PcapAnalysis/Scripts/PcapFileExtractor/PcapFileExtractor.yml
Labels: auto-update-docker

#33828 demisto/paho-mqtt:1.0.0.56447 | 0-100 | PR batch #1/1
  Packs/CommonScripts/pack_metadata.json
  Packs/UBIRCH/Integrations/UBIRCH/UBIRCH.yml
Labels: docs-approved, auto-update-docker

#33725 Update pack for XSOAR 8
  Packs/MultiTenantPerformance/ReleaseNotes/1_0_1.md
  Packs/MultiTenantPerformance/pack_metadata.json
Labels: docs-approved, ForceMerge

#33764 Falcon CrowdStrike - True Positive handling playbook fixes
  Packs/CrowdStrikeFalcon/Playbooks/playbook-CrowdStrike_Falcon_-_True_Positive_Incident_Handling.yml
  Packs/CrowdStrikeFalcon/ReleaseNotes/1_13_4.md
  Packs/CrowdStrikeFalcon/pack_metadata.json
Labels: docs-approved

#33842 [Splunk] Fixed TPB
  Packs/SplunkPy/TestPlaybooks/playbook-SplunkPy-Test-V2.yml
Labels: docs-approved

#33847 drop-redundant-keystokeep-code
  Packs/CommonScripts/ReleaseNotes/1_14_30.md
  Packs/CommonScripts/Scripts/DeleteContext/DeleteContext.js
  Packs/CommonScripts/TestPlaybooks/playbook-DeleteContext-test.yml
  Packs/CommonScripts/pack_metadata.json
Labels: docs-approved

#33637 Gitlab v2.2.22 - Argument Description Change
  Packs/GitLab/CONTRIBUTORS.json
  Packs/GitLab/Integrations/GitLabEventCollector/GitLabEventCollector.yml
  Packs/GitLab/Integrations/GitLabv2/GitLabv2.py
  Packs/GitLab/Integrations/GitLabv2/GitLabv2.yml
  Packs/GitLab/Integrations/GitLabv2/README.md
  Packs/GitLab/ReleaseNotes/2_2_22.md
  Packs/GitLab/pack_metadata.json
Labels: Contribution, docs-approved, Contribution Form Filled, Community, pending-contributor, Xsoar Support Level, External PR

#33853 fix - sort_packs_to_upload - new pack
  Tests/scripts/collect_tests/collect_tests.py
  Tests/scripts/infrastructure_tests/test_collect_tests.py
Labels: docs-approved

#33849 Crowdstrike: added argument polling_timeout to cs-falcon-rtr-retrieve-file command
  Packs/CrowdStrikeFalcon/Integrations/CrowdStrikeFalcon/CrowdStrikeFalcon.py
  Packs/CrowdStrikeFalcon/Integrations/CrowdStrikeFalcon/CrowdStrikeFalcon.yml
  Packs/CrowdStrikeFalcon/Integrations/CrowdStrikeFalcon/README.md
  Packs/CrowdStrikeFalcon/ReleaseNotes/1_13_5.md
  Packs/CrowdStrikeFalcon/pack_metadata.json
Labels: docs-approved

#33862 updated security reviewer
  .github/content_roles.json
Labels: docs-approved

#33612 [ASM] EXPANDR-6789 - Rcslayout changes
  Packs/CortexAttackSurfaceManagement/Layouts/layoutscontainer-ASM_Alert_Layout.json
  Packs/CortexAttackSurfaceManagement/ReleaseNotes/1_7_31.md
  Packs/CortexAttackSurfaceManagement/Scripts/RCSScan/RCSScan.py
  Packs/CortexAttackSurfaceManagement/Scripts/RCSScan/RCSScan.yml
  Packs/CortexAttackSurfaceManagement/Scripts/RCSScan/RCSScan_test.py
  Packs/CortexAttackSurfaceManagement/Scripts/RCSScan/README.md
  Packs/CortexAttackSurfaceManagement/pack_metadata.json
Labels: Contribution, docs-approved, ready-for-instance-test, Contribution Form Filled, Community, Xsoar Support Level, External PR, Security Review

#33706 Path validations: fix `InvalidDepthZeroFile`
  .pre-commit-config_template.yaml
  Packs/BitcoinAbuse/Integrations/BitcoinAbuse/command_examples
  Packs/Druva/doc_files/CortexXsoar.png
  Packs/FireMonSecurityManager/secrets_white_list.json
  Packs/GRR/pack_metadata.json.lock
  Packs/MicrosoftECM/Integrations/MicrosoftECM/command_examples
  Packs/NutanixHypervisor/Integrations/NutanixHypervisor/command_examples
  Packs/Sandblast/pack_metadata.json.lock
  Packs/XSOARmirroring/CHANGELOG.md
  Tests/secrets_white_list.json
Labels: docs-approved, ForceMerge

#33871 demisto/py3-tools:1.0.0.91908 | 0-100 | PR batch #1/3
  Packs/AccentureCTI_Feed/Integrations/ACTIIndicatorFeed/ACTIIndicatorFeed.yml
  Packs/Anomali_ThreatStream/Integrations/AnomaliThreatStreamv3/AnomaliThreatStreamv3.yml
  Packs/CommonScripts/Scripts/ExifRead/ExifRead.yml
  Packs/CommonScripts/Scripts/ExtractDomainAndFQDNFromUrlAndEmail/ExtractDomainAndFQDNFromUrlAndEmail.yml
  Packs/CommonScripts/Scripts/ExtractDomainFromUrlFormat/ExtractDomainFromUrlFormat.yml
  Packs/CommonScripts/Scripts/ExtractFQDNFromUrlAndEmail/ExtractFQDNFromUrlAndEmail.yml
  Packs/CommonScripts/Scripts/FetchIndicatorsFromFile/FetchIndicatorsFromFile.yml
  Packs/CommonScripts/Scripts/LanguageDetect/LanguageDetect.yml
  Packs/CommonScripts/Scripts/ParseExcel/ParseExcel.yml
  Packs/CommonScripts/Scripts/StixCreator/StixCreator.yml
Labels: auto-update-docker

#33864 Wf description
  Packs/Palo_Alto_Networks_WildFire/Integrations/WildFireReports/WildFireReports_description.md
  Packs/Palo_Alto_Networks_WildFire/ReleaseNotes/2_1_44.md
  Packs/Palo_Alto_Networks_WildFire/pack_metadata.json
Labels: docs-approved

#33767 XSUP 35568 VMware Patch
  Packs/VMware/Integrations/VMware/VMware.py
  Packs/VMware/Integrations/VMware/VMware.yml
  Packs/VMware/ReleaseNotes/1_2_10.md
  Packs/VMware/pack_metadata.json
  Tests/conf.json
Labels: docs-approved

#33797 YR/-Ews-update-to-latest-version-of-exchangelib/CIAC-10245
  Packs/MicrosoftExchangeOnline/Integrations/EWSO365/EWSO365.py
  Packs/MicrosoftExchangeOnline/Integrations/EWSO365/EWSO365.yml
  Packs/MicrosoftExchangeOnline/Integrations/EWSO365/EWSO365_test.py
  Packs/MicrosoftExchangeOnline/ReleaseNotes/1_3_4.md
  Packs/MicrosoftExchangeOnline/pack_metadata.json
  Tests/docker_native_image_config.json
Labels: docs-approved

#33356 Varonis SaaS pack updates
  Packs/VaronisSaaS/Integrations/VaronisSaaS/README.md
  Packs/VaronisSaaS/Integrations/VaronisSaaS/VaronisSaaS.py
  Packs/VaronisSaaS/Integrations/VaronisSaaS/VaronisSaaS.yml
  Packs/VaronisSaaS/Integrations/VaronisSaaS/VaronisSaaS_test.py
  Packs/VaronisSaaS/Integrations/VaronisSaaS/command_examples.txt
  Packs/VaronisSaaS/Integrations/VaronisSaaS/test_data/demisto_search_alerts_args.json
  Packs/VaronisSaaS/ReleaseNotes/1_0_4.json
  Packs/VaronisSaaS/ReleaseNotes/1_0_4.md
Labels: Contribution, Partner, post-demo, Contribution Form Filled, Partner Support Level, External PR, Partner-Approved

#33863 [GenericSQL] Improve TPB
  Packs/GenericSQL/TestPlaybooks/generic-sql.yml
Labels: docs-approved

#33784 Tanium - fix proxy handling
  Packs/Tanium/Integrations/Tanium_v2/Tanium_v2.py
  Packs/Tanium/ReleaseNotes/1_0_32.md
  Packs/Tanium/pack_metadata.json
Labels: docs-approved

#33225 Add CertStream Integration Pack
  Packs/CertStream/.pack-ignore
  Packs/CertStream/.secrets-ignore
  Packs/CertStream/IncidentFields/incidentfield-Certificate_Index.json
  Packs/CertStream/IncidentFields/incidentfield-Certificate_Source.json
  Packs/CertStream/IncidentFields/incidentfield-domain_registrar_abuse_email.json
  Packs/CertStream/IncidentFields/incidentfield-fingerprint.json
  Packs/CertStream/IncidentFields/incidentfield-levenshteindistance.json
  Packs/CertStream/IncidentFields/incidentfield-userasset.json
  Packs/CertStream/Integrations/CertStream/CertStream.py
  Packs/CertStream/Integrations/CertStream/CertStream.yml
  Packs/CertStream/Integrations/CertStream/CertStream_description.md
  Packs/CertStream/Integrations/CertStream/CertStream_image.png
  Packs/CertStream/Integrations/CertStream/CertStream_test.py
  Packs/CertStream/Integrations/CertStream/README.md
  Packs/CertStream/Playbooks/playbook-Create_list_for_PTH.yml
  Packs/CertStream/Playbooks/playbook-Create_list_for_PTH_README.md
  Packs/CertStream/README.md
  Packs/CertStream/doc_files/Create_list_for_PTH.png
  Packs/CertStream/pack_metadata.json
Labels: ForceMerge, Community Support Level

#33908 ParseEmailFilesV2: added log handler
  Packs/CommonScripts/ReleaseNotes/1_14_31.md
  Packs/CommonScripts/Scripts/ParseEmailFilesV2/ParseEmailFilesV2.py
  Packs/CommonScripts/Scripts/ParseEmailFilesV2/ParseEmailFilesV2.yml
  Packs/CommonScripts/pack_metadata.json
Labels: docs-approved

#33889 added PrismaCloud to core packs and lock core packs
  Tests/Marketplace/core_packs_mpv2_list.json
Labels: docs-approved, ForceMerge

#33729 XSUP-35181/Azure NSG - update the creation of token_retrieval_url
  Packs/AzureNetworkSecurityGroups/Integrations/AzureNetworkSecurityGroups/AzureNetworkSecurityGroups.py
  Packs/AzureNetworkSecurityGroups/Integrations/AzureNetworkSecurityGroups/AzureNetworkSecurityGroups.yml
  Packs/AzureNetworkSecurityGroups/Integrations/AzureNetworkSecurityGroups/AzureNetworkSecurityGroups_test.py
  Packs/AzureNetworkSecurityGroups/ReleaseNotes/1_2_26.md
  Packs/AzureNetworkSecurityGroups/pack_metadata.json
Labels: docs-approved

#33806 XSUP-35612/ Fixing mirroring issues
  Packs/CrowdStrikeFalcon/Classifiers/classifier-CrowdStrike_Falcon_Mapper_6.5.json
  Packs/CrowdStrikeFalcon/Integrations/CrowdStrikeFalcon/CrowdStrikeFalcon.py
  Packs/CrowdStrikeFalcon/Integrations/CrowdStrikeFalcon/CrowdStrikeFalcon_test.py
  Packs/CrowdStrikeFalcon/Integrations/CrowdStrikeFalcon/test_data/input_data.py
  Packs/CrowdStrikeFalcon/ReleaseNotes/1_13_6.md
  Packs/CrowdStrikeFalcon/pack_metadata.json
Labels: docs-approved

#33436 Improve Fetch incidents structure and add append notes funcitonality
  Packs/ZeroFox/Integrations/ZeroFox/ZeroFox.py
  Packs/ZeroFox/Integrations/ZeroFox/ZeroFox.yml
  Packs/ZeroFox/Integrations/ZeroFox/ZeroFox_test.py
  Packs/ZeroFox/Integrations/ZeroFox/test_data/alerts/list_10_records.json
  Packs/ZeroFox/Integrations/ZeroFox/test_data/alerts/list_10_records_and_more.json
  Packs/ZeroFox/ReleaseNotes/1_3_1.json
  Packs/ZeroFox/ReleaseNotes/1_3_1.md
Labels: Contribution, Partner, pending-demo, Contribution Form Filled, pending-contributor, Partner Support Level, External PR, Partner-Approved, TIM Review

#33909 Fix CloseLinkedIncidentsPostProcessing Error
  Packs/CaseManagement-Generic/ReleaseNotes/1_4_7.md
  Packs/CaseManagement-Generic/Scripts/CloseLinkedIncidentsPostProcessing/CloseLinkedIncidentsPostProcessing.py
  Packs/CaseManagement-Generic/Scripts/CloseLinkedIncidentsPostProcessing/CloseLinkedIncidentsPostProcessing.yml
  Packs/CaseManagement-Generic/pack_metadata.json
Labels: docs-approved

#33911 Removed brackets from README images in Prisma cloud playbbok
  Packs/PrismaCloudCompute/Playbooks/Prisma_Cloud_Compute_-_Jira_Ticket_(Markdown_Table)_README.md
  Packs/PrismaCloudCompute/Playbooks/Prisma_Cloud_Compute_-_Jira_Ticket_(XLSX)_README.md
  Packs/PrismaCloudCompute/Playbooks/Prisma_Cloud_Compute_-_ServiceNow_Ticket_(HTML_Table)_README.md
  Packs/PrismaCloudCompute/Playbooks/Prisma_Cloud_Compute_-_ServiceNow_Ticket_(XLSX)_README.md
  Packs/PrismaCloudCompute/doc_files/Prisma_Cloud_Compute_-_Jira_Ticket_Markdown_Table.png
  Packs/PrismaCloudCompute/doc_files/Prisma_Cloud_Compute_-_Jira_Ticket_XLSX.png
  Packs/PrismaCloudCompute/doc_files/Prisma_Cloud_Compute_-_ServiceNow_Ticket_HTML_Table.png
  Packs/PrismaCloudCompute/doc_files/Prisma_Cloud_Compute_-_ServiceNow_Ticket_XLSX.png
Labels: docs-approved

#33881 Fixing TPB and adding to conf
  Packs/CommonScripts/ReleaseNotes/1_14_32.md
  Packs/CommonScripts/Scripts/DeleteContext/DeleteContext.yml
  Packs/CommonScripts/TestPlaybooks/playbook-DeleteContext-test.yml
  Packs/CommonScripts/pack_metadata.json
  Tests/conf.json
Labels: docs-approved

#33917 remove servicenow as default value
  Packs/PrismaCloudCompute/Playbooks/Prisma_Cloud_Compute_-_Compliance_Alert_v2_README.md
Labels: docs-approved

#33808 Added a warning about the email body in phishing layout (XSOAR)
  Packs/Phishing/Layouts/layoutscontainer-Phishing_Layout_XSIAM.json
  Packs/Phishing/Layouts/layoutscontainer-Phishing_v_3.json
  Packs/Phishing/ReleaseNotes/3_6_18.md
  Packs/Phishing/pack_metadata.json
Labels: docs-approved, release-notes-only

#33614 Service now audit
  Packs/ServiceNow/Integrations/ServiceNowEventCollector/README.md
  Packs/ServiceNow/Integrations/ServiceNowEventCollector/ServiceNowEventCollector.py
  Packs/ServiceNow/Integrations/ServiceNowEventCollector/ServiceNowEventCollector.yml
  Packs/ServiceNow/Integrations/ServiceNowEventCollector/ServiceNowEventCollector_description.md
  Packs/ServiceNow/Integrations/ServiceNowEventCollector/ServiceNowEventCollector_image.png
  Packs/ServiceNow/Integrations/ServiceNowEventCollector/ServiceNowEventCollector_test.py
  Packs/ServiceNow/Integrations/ServiceNowEventCollector/command_examples
  Packs/ServiceNow/Integrations/ServiceNowEventCollector/test_data/audit_logs.json
  Packs/ServiceNow/Integrations/ServiceNowEventCollector/test_data/fetch_audit_logs.json
  Packs/ServiceNow/Integrations/ServiceNowEventCollector/test_data/single_audit_log.json
  Packs/ServiceNow/ModelingRules/ServiceNow/ServiceNow.xif
  Packs/ServiceNow/ModelingRules/ServiceNow/ServiceNow.yml
  Packs/ServiceNow/ModelingRules/ServiceNow/ServiceNow_schema.json
  Packs/ServiceNow/ReleaseNotes/2_6_0.md
  Packs/ServiceNow/pack_metadata.json
Labels: docs-approved

#33895 lock core packs 8.6
  Tests/Marketplace/versions-metadata.json
Labels: docs-approved, ForceMerge

#33914 IllusiveNetworks: freeze time in unit test
  Packs/IllusiveNetworks/Integrations/IllusiveNetworks/IllusiveNetworks.yml
  Packs/IllusiveNetworks/Integrations/IllusiveNetworks/IllusiveNetworks_test.py
  Packs/IllusiveNetworks/ReleaseNotes/1_0_31.md
  Packs/IllusiveNetworks/pack_metadata.json
Labels: docs-approved

#33781 Prisma cloud xsiam
  Packs/CommonPlaybooks/Playbooks/playbook-Cloud_Response_-_Generic.yml
  Packs/CommonPlaybooks/ReleaseNotes/2_6_29.md
  Packs/CommonPlaybooks/pack_metadata.json
  Packs/CommonTypes/.pack-ignore
  Packs/CommonTypes/IncidentFields/incidentfield-Alert_Rules.json
  Packs/CommonTypes/IncidentFields/incidentfield-CVE_ID.json
  Packs/CommonTypes/IncidentFields/incidentfield-CVE_Published.json
  Packs/CommonTypes/IncidentFields/incidentfield-Policy_Recommendation.json
  Packs/CommonTypes/IncidentFields/incidentfield-Policy_Type.json
  Packs/CommonTypes/IncidentFields/incidentfield-Resource_URL.json
  Packs/CommonTypes/IncidentFields/incidentfield-User_Anomaly_Count.json
  Packs/CommonTypes/IncidentFields/incidentfield-Vulnerable_Product.json
  Packs/CommonTypes/ReleaseNotes/3_4_10.md
  Packs/CommonTypes/pack_metadata.json
  Packs/PrismaCloud/.pack-ignore
  Packs/PrismaCloud/LayoutRules/Prisma_Cloud_Network_API_and_Anomaly.json
  Packs/PrismaCloud/Layouts/layoutscontainer-Prisma_Cloud_-_Network_Incident_Layout.json
  Packs/PrismaCloud/Playbooks/Prisma_Cloud_-_RQL_Execution.yml
  Packs/PrismaCloud/Playbooks/Prisma_Cloud_-_RQL_Execution_README.md
  Packs/PrismaCloud/Playbooks/playbook-Prisma_Cloud_-_Network__API_and_Anomaly_Incidents.yml
  Packs/PrismaCloud/Playbooks/playbook-Prisma_Cloud_-_Network__API_and_Anomaly_Incidents_README.md
  Packs/PrismaCloud/ReleaseNotes/4_3_3.md
  Packs/PrismaCloud/Triggers/Prisma_Cloud_Netwok_API_Anomaly.json
  Packs/PrismaCloud/doc_files/Prisma_Cloud_-_Network_API_and_Anomaly_Incidents.png
  Packs/PrismaCloud/doc_files/Prisma_Cloud_-_RQL_Execution.png
  Packs/PrismaCloud/pack_metadata.json
Labels: docs-approved

#33920 [FileCreateAndUploadV2] Added Support For `EntryNote` Type
  Packs/CommonScripts/ReleaseNotes/1_14_33.md
  Packs/CommonScripts/Scripts/FileCreateAndUploadV2/FileCreateAndUploadV2.py
  Packs/CommonScripts/Scripts/FileCreateAndUploadV2/FileCreateAndUploadV2_test.py
  Packs/CommonScripts/pack_metadata.json
Labels: docs-approved

#33772 InfoBlox | Fix Unknown IP Key
  Packs/Infoblox/Integrations/Infoblox/Infoblox.py
  Packs/Infoblox/Integrations/Infoblox/Infoblox_test.py
  Packs/Infoblox/ReleaseNotes/1_1_1.md
  Packs/Infoblox/pack_metadata.json
Labels: bug, docs-approved

#33915 Exabeam: added default false for isFetch
  Packs/Exabeam/Integrations/Exabeam/Exabeam.py
  Packs/Exabeam/Integrations/Exabeam/Exabeam.yml
  Packs/Exabeam/ReleaseNotes/2_3_1.md
  Packs/Exabeam/pack_metadata.json
Labels: docs-approved

#33358 Palo alto networks ai ops
  Packs/PaloAltoNetworksAIOps/.pack-ignore
  Packs/PaloAltoNetworksAIOps/.secrets-ignore
  Packs/PaloAltoNetworksAIOps/Integrations/PaloAltoNetworksAIOps/PaloAltoNetworksAIOps.py
  Packs/PaloAltoNetworksAIOps/Integrations/PaloAltoNetworksAIOps/PaloAltoNetworksAIOps.yml
  Packs/PaloAltoNetworksAIOps/Integrations/PaloAltoNetworksAIOps/PaloAltoNetworksAIOps_description.md
  Packs/PaloAltoNetworksAIOps/Integrations/PaloAltoNetworksAIOps/PaloAltoNetworksAIOps_image.png
  Packs/PaloAltoNetworksAIOps/Integrations/PaloAltoNetworksAIOps/PaloAltoNetworksAIOps_test.py
  Packs/PaloAltoNetworksAIOps/Integrations/PaloAltoNetworksAIOps/README.md
  Packs/PaloAltoNetworksAIOps/Integrations/PaloAltoNetworksAIOps/command_examples
  Packs/PaloAltoNetworksAIOps/README.md
  Packs/PaloAltoNetworksAIOps/TestPlaybooks/PaloAltoNetworksAIOps-Test.yml
  Packs/PaloAltoNetworksAIOps/pack_metadata.json
  Tests/conf.json
Labels: docs-approved

#33777 [Trigger contribution build] Add missing variables for pipeline trigger request
  .circleci/config.yml
  .gitlab/ci/.gitlab-ci.global.yml
  Utils/tests/test_trigger_contribution_build.py
  Utils/tests/update_contribution_pack_in_base_branch_test.py
  Utils/trigger_contribution_build.py
  Utils/update_contribution_pack_in_base_branch.py
Labels: docs-approved, nightly-ok

#33774 Modified BetweenHours.py script to handle midnight range
  Packs/FiltersAndTransformers/CONTRIBUTORS.json
  Packs/FiltersAndTransformers/ReleaseNotes/1_2_67.md
  Packs/FiltersAndTransformers/Scripts/BetweenHours/BetweenHours.py
  Packs/FiltersAndTransformers/Scripts/BetweenHours/BetweenHours.yml
  Packs/FiltersAndTransformers/Scripts/BetweenHours/BetweenHours_test.py
  Packs/FiltersAndTransformers/pack_metadata.json
Labels: Contribution, docs-approved, pending-demo, Contribution Form Filled, Community, Xsoar Support Level, External PR

#33867 fixing xdr_close_reason_resolution
  Packs/ApiModules/ReleaseNotes/2_2_23.md
  Packs/ApiModules/Scripts/CoreIRApiModule/CoreIRApiModule.py
  Packs/ApiModules/Scripts/CoreIRApiModule/CoreIRApiModule.yml
  Packs/ApiModules/Scripts/CoreIRApiModule/CoreIRApiModule_test.py
  Packs/ApiModules/pack_metadata.json
  Packs/Core/ReleaseNotes/3_0_24.md
  Packs/Core/pack_metadata.json
  Packs/CortexXDR/ReleaseNotes/6_1_28.md
  Packs/CortexXDR/pack_metadata.json
  Packs/ctf01/ReleaseNotes/1_0_11.md
  Packs/ctf01/pack_metadata.json
Labels: docs-approved, ForceMerge

#33687 Rasterize URL Comma
  Packs/rasterize/Integrations/rasterize/rasterize.py
  Packs/rasterize/ReleaseNotes/2_0_6.md
  Packs/rasterize/pack_metadata.json
Labels: docs-approved, ForceMerge

#33931 [XSUP-35785][Netskope] Add the `is_overwrite` Argument
  Packs/Netskope/Integrations/NetskopeAPIv2/NetskopeAPIv2.yml
  Packs/Netskope/ReleaseNotes/3_3_10.md
  Packs/Netskope/pack_metadata.json
Labels: docs-approved

#33546 Fix threat grid v2 upload sample command
  Packs/ThreatGrid/Integrations/ThreatGridv2/ThreatGridv2.py
  Packs/ThreatGrid/Integrations/ThreatGridv2/ThreatGridv2.yml
  Packs/ThreatGrid/Integrations/ThreatGridv2/ThreatGridv2_test.py
  Packs/ThreatGrid/ReleaseNotes/2_0_22.md
  Packs/ThreatGrid/pack_metadata.json
Labels: docs-approved

#33840 No ticket_type default value in servicenow-update-ticket
  Packs/ServiceNow/Integrations/ServiceNowv2/ServiceNowv2.py
  Packs/ServiceNow/Integrations/ServiceNowv2/ServiceNowv2.yml
  Packs/ServiceNow/ReleaseNotes/2_6_1.md
  Packs/ServiceNow/pack_metadata.json
Labels: docs-approved

#33934 safebreach expose
  Packs/SafeBreach/Integrations/SafeBreach/SafeBreach.py
  Packs/SafeBreach/ReleaseNotes/1_4_1.md
  Packs/SafeBreach/pack_metadata.json
Labels: docs-approved

#33857 [ASM] - EXPANDER 8513 - XDR Mitigation for ASM
  Packs/CortexAttackSurfaceManagement/Playbooks/Cortex_ASM_-_ASM_Alert.yml
  Packs/CortexAttackSurfaceManagement/Playbooks/Cortex_ASM_-_Cortex_Endpoint_Remediation.yml
  Packs/CortexAttackSurfaceManagement/Playbooks/Cortex_ASM_-_Cortex_Endpoint_Remediation_README.md
  Packs/CortexAttackSurfaceManagement/Playbooks/Cortex_ASM_-_Remediation.yml
  Packs/CortexAttackSurfaceManagement/Playbooks/Cortex_ASM_-_Remediation_Path_Rules.yml
  Packs/CortexAttackSurfaceManagement/README.md
  Packs/CortexAttackSurfaceManagement/ReleaseNotes/1_7_32.md
  Packs/CortexAttackSurfaceManagement/doc_files/Cortex_ASM_-_Cortex_Endpoint_Remediation.png
  Packs/CortexAttackSurfaceManagement/pack_metadata.json
Labels: Contribution, Contribution Form Filled, Community, Xsoar Support Level, External PR, Security Review

#33935 Fix the creation of the curl commands within the logs.
  Packs/Base/ReleaseNotes/1_33_51.md
  Packs/Base/Scripts/CommonServerPython/CommonServerPython.py
  Packs/Base/Scripts/CommonServerPython/CommonServerPython_test.py
  Packs/Base/pack_metadata.json
Labels: docs-approved

#33778 Replace XSOAR 8 Example in Generic Webhook README
  Packs/GenericWebhook/Integrations/GenericWebhook/GenericWebhook.py
  Packs/GenericWebhook/Integrations/GenericWebhook/GenericWebhook.yml
  Packs/GenericWebhook/Integrations/GenericWebhook/README.md
  Packs/GenericWebhook/ReleaseNotes/1_0_29.md
  Packs/GenericWebhook/pack_metadata.json
  Tests/conf.json
Labels: docs-approved

#33896 druva: fix image link
  Packs/Druva/README.md
Labels: docs-approved

#33947 Update permission needed for API calls in ServiceNow
  Packs/ServiceNow/Integrations/ServiceNowv2/README.md
Labels: docs-approved

#33944 Add `native:candidate` to pre-commit template `docker_image:nightly`
  .pre-commit-config_template.yaml
Labels: docs-approved

#33922 moved init of auth to startup instead of first request
  Packs/GenericWebhook/.secrets-ignore
  Packs/GenericWebhook/Integrations/GenericWebhook/GenericWebhook.py
  Packs/GenericWebhook/ReleaseNotes/1_0_30.md
  Packs/GenericWebhook/TestPlaybooks/Generic_Webhook_-_Test.yml
  Packs/GenericWebhook/TestPlaybooks/script-GetWebhookUrl.yml
  Packs/GenericWebhook/pack_metadata.json
Labels: docs-approved

#33837 XSUP-35465/add argument
  Packs/ThreatConnect/Integrations/ThreatConnectV3/ThreatConnectV3.py
  Packs/ThreatConnect/Integrations/ThreatConnectV3/ThreatConnectV3.yml
  Packs/ThreatConnect/Integrations/ThreatConnectV3/ThreatConnectV3_test.py
  Packs/ThreatConnect/ReleaseNotes/3_1_5.md
  Packs/ThreatConnect/pack_metadata.json
Labels: docs-approved, nightly-ok

#33522 Deprecate BPA
  Packs/BPA/Integrations/BPA/BPA.yml
  Packs/BPA/Playbooks/playbook-BPA.yml
  Packs/BPA/Playbooks/playbook-Comprehensive_PAN-OS_Best_Practice_Assessment.yml
  Packs/BPA/ReleaseNotes/1_2_23.md
  Packs/BPA/pack_metadata.json
  Tests/conf.json
Labels: docs-approved

#33843 [McAfee] Test TPB
  Packs/epo/TestPlaybooks/playbook-epo_v2_Test.yml
Labels: docs-approved

#33745 Fix ews unserializable items error
  Packs/MicrosoftExchangeOnPremise/Integrations/EWSv2/EWSv2.py
  Packs/MicrosoftExchangeOnPremise/Integrations/EWSv2/EWSv2_test.py
  Packs/MicrosoftExchangeOnPremise/ReleaseNotes/2_1_4.md
  Packs/MicrosoftExchangeOnPremise/pack_metadata.json
Labels: docs-approved, ForceMerge

#33861 delete lint from gitlab build
  .gitlab/ci/.gitlab-ci.bucket-upload.yml
  .gitlab/ci/.gitlab-ci.global.yml
  .gitlab/ci/.gitlab-ci.on-push.yml
  .gitlab/ci/.gitlab-ci.sdk-nightly.yml
  .gitlab/ci/.gitlab-ci.test-native-candidate.yml
  Tests/scripts/check_jobs_done.py
Labels: docs-approved, nightly-ok

#33962 poetry: set `package-mode = false`
  .gitlab/ci/.gitlab-ci.variables.yml
  .pre-commit-config_template.yaml
  pyproject.toml
Labels: docs-approved, nightly-ok

#33941 Add "is_error" check to ReadQRCode
  Packs/CommonScripts/ReleaseNotes/1_14_34.md
  Packs/CommonScripts/Scripts/ReadQRCode/ReadQRCode.py
  Packs/CommonScripts/Scripts/ReadQRCode/ReadQRCode_test.py
  Packs/CommonScripts/pack_metadata.json
Labels: docs-approved

#33919 Fixed description of demisto.incidents
  Tests/demistomock/demistomock.py
Labels: docs-approved

#33807 SkyHigh Security Bug Fix
  Packs/SkyhighSecurity/Integrations/SkyhighSecurity/SkyhighSecurity.py
  Packs/SkyhighSecurity/Integrations/SkyhighSecurity/SkyhighSecurity.yml
  Packs/SkyhighSecurity/Integrations/SkyhighSecurity/SkyhighSecurity_test.py
  Packs/SkyhighSecurity/Integrations/SkyhighSecurity/test_data/activities.txt
  Packs/SkyhighSecurity/ReleaseNotes/1_0_15.md
  Packs/SkyhighSecurity/pack_metadata.json
Labels: docs-approved

#33910 Qradar Deprecated hidden commands
  Packs/QRadar/Integrations/QRadar_v3/QRadar_v3.yml
  Packs/QRadar/Integrations/QRadar_v3/README.md
  Packs/QRadar/ReleaseNotes/2_4_57.md
  Packs/QRadar/pack_metadata.json
Labels: docs-approved

#31903 Improve performance for DBotPredictURLPhishing
  Packs/PhishingURL/ReleaseNotes/1_1_12.md
  Packs/PhishingURL/Scripts/DBotPredictURLPhishing/DBotPredictURLPhishing.py
  Packs/PhishingURL/Scripts/DBotPredictURLPhishing/dbotpredicturlphishing_test.py
  Packs/PhishingURL/pack_metadata.json
  Packs/rasterize/Integrations/rasterize/rasterize.py
  Packs/rasterize/Integrations/rasterize/rasterize.yml
  Packs/rasterize/Integrations/rasterize/rasterize_test.py
  Packs/rasterize/ReleaseNotes/2_0_7.md
  Packs/rasterize/TestPlaybooks/playbook-Process_Email_-_Generic_for_rasterize.yml
  Packs/rasterize/TestPlaybooks/playbook-RasterizeImageTest.yml
  Packs/rasterize/TestPlaybooks/playbook-Rasterize_Test.yml
  Packs/rasterize/pack_metadata.json
Labels: docs-approved, ForceMerge

#33888 added base_dn_query parameter
  Packs/Active_Directory_Query/Integrations/Active_Directory_Query/Active_Directory_Query.py
  Packs/Active_Directory_Query/ReleaseNotes/1_6_34.md
  Packs/Active_Directory_Query/pack_metadata.json
Labels: docs-approved

#33969 PANW DLP - Setup instructions
  Packs/Palo_Alto_Networks_Enterprise_DLP/Integrations/Palo_Alto_Networks_Enterprise_DLP/Palo_Alto_Networks_Enterprise_DLP.yml
  Packs/Palo_Alto_Networks_Enterprise_DLP/Integrations/Palo_Alto_Networks_Enterprise_DLP/Palo_Alto_Networks_Enterprise_DLP_description.md
  Packs/Palo_Alto_Networks_Enterprise_DLP/Integrations/Palo_Alto_Networks_Enterprise_DLP/README.md
  Packs/Palo_Alto_Networks_Enterprise_DLP/ReleaseNotes/2_0_10.md
  Packs/Palo_Alto_Networks_Enterprise_DLP/pack_metadata.json
Labels: docs-approved

#33838 CitrixADC_Enhancement_CIAC-9982
  Packs/CitrixADC/.pack-ignore
  Packs/CitrixADC/ModelingRules/CitrixADC_1_3/CitrixADC_1_3.xif
  Packs/CitrixADC/ReleaseNotes/1_0_3.md
  Packs/CitrixADC/pack_metadata.json
Labels: docs-approved

#33746 XSUP-35581/JiraV3- update file mime type in upload_file_command
  Packs/Jira/Integrations/JiraV3/JiraV3.py
  Packs/Jira/Integrations/JiraV3/JiraV3.yml
  Packs/Jira/Integrations/JiraV3/JiraV3_test.py
  Packs/Jira/Integrations/JiraV3/test_data/upload_file_test/raw_response.json
  Packs/Jira/ReleaseNotes/3_1_14.md
  Packs/Jira/pack_metadata.json
Labels: docs-approved

#34025 remove MP from generic webhook
  Tests/conf.json
Labels: docs-approved

#34027 Add `validate-conf-json` hook
  .pre-commit-config_template.yaml
  Tests/conf.json
Labels: docs-approved

#33933 Xpanse wizard fixes
  Packs/CortexXpanse/ReleaseNotes/1_0_22.md
  Packs/CortexXpanse/Wizards/wizard-Xpanse_ASM.json
  Packs/CortexXpanse/pack_metadata.json
Labels: docs-approved

#34032 minimize validate-conf-json friction
  .pre-commit-config_template.yaml
Labels: docs-approved

#34033 Update Redmine.yml tests
  Packs/Redmine/Integrations/Redmine/Redmine.yml
  Packs/Redmine/ReleaseNotes/1_0_2.md
  Packs/Redmine/pack_metadata.json
Labels: docs-approved

#34023 Fix subscription notification.
  Packs/AWS-SNS-Listener/Integrations/AWSSNSListener/AWSSNSListener.py
  Packs/AWS-SNS-Listener/Integrations/AWSSNSListener/AWSSNSListener.yml
  Packs/AWS-SNS-Listener/ReleaseNotes/1_0_1.md
  Packs/AWS-SNS-Listener/pack_metadata.json
Labels: docs-approved

#34013 XSUP-36157 - A fix to MapRangeValues script
  Packs/FiltersAndTransformers/ReleaseNotes/1_2_68.md
  Packs/FiltersAndTransformers/Scripts/MapRangeValues/MapRangeValues.py
  Packs/FiltersAndTransformers/Scripts/MapRangeValues/MapRangeValues.yml
  Packs/FiltersAndTransformers/Scripts/MapRangeValues/MapRangeValues_test.py
  Packs/FiltersAndTransformers/Scripts/MapRangeValues/README.md
  Packs/FiltersAndTransformers/TestPlaybooks/playbook-MapRangeValues_Test.yml
  Packs/FiltersAndTransformers/pack_metadata.json
  Tests/conf.json
Labels: docs-approved

#34045 add memory_threshold
  Tests/conf.json
Labels: docs-approved

#34048 Identity analytics for XSIAM - layout fix
  Packs/Core/Layouts/layoutscontainer-Identity_Analytics_Alerts.json
  Packs/Core/ReleaseNotes/3_0_25.md
  Packs/Core/pack_metadata.json
Labels: docs-approved

#34051 revert docker
  Packs/AnsibleCiscoIOS/Integrations/AnsibleCiscoIOS/AnsibleCiscoIOS.yml
  Packs/AnsibleCiscoIOS/ReleaseNotes/1_0_7.md
  Packs/AnsibleCiscoIOS/pack_metadata.json
Labels: docs-approved, ForceMerge

#34054 Thinks canary playbook fix
  Packs/ThinkstCanary/Playbooks/playbook-Enrich_Thinkst_Canary_Events.yml
  Packs/ThinkstCanary/ReleaseNotes/1_0_21.md
  Packs/ThinkstCanary/pack_metadata.json
Labels: docs-approved

#33432 Code42 Event Collector
  Packs/Code42/.secrets-ignore
  Packs/Code42/Integrations/Code42EventCollector/Code42EventCollector.py
  Packs/Code42/Integrations/Code42EventCollector/Code42EventCollector.yml
  Packs/Code42/Integrations/Code42EventCollector/Code42EventCollector_description.md
  Packs/Code42/Integrations/Code42EventCollector/Code42EventCollector_image.png
  Packs/Code42/Integrations/Code42EventCollector/Code42EventCollector_test.py
  Packs/Code42/Integrations/Code42EventCollector/README.md
  Packs/Code42/Integrations/Code42EventCollector/command_examples
  Packs/Code42/ModelingRules/Code42/Code42.xif
  Packs/Code42/ModelingRules/Code42/Code42.yml
  Packs/Code42/ModelingRules/Code42/Code42_schema.json
  Packs/Code42/ReleaseNotes/5_0_0.md
  Packs/Code42/pack_metadata.json
Labels: docs-approved

#34058 fix pre commit nightly
  .gitlab/ci/.gitlab-ci.global.yml
  .pre-commit-config_template.yaml
Labels: docs-approved, nightly-ok

#34061 Rapid7 fix
  Packs/Rapid7_InsightIDR/Integrations/Rapid7_InsightIDR/Rapid7_InsightIDR.py
  Packs/Rapid7_InsightIDR/ReleaseNotes/2_0_1.md
  Packs/Rapid7_InsightIDR/pack_metadata.json
Labels: docs-approved

#34060 Fix DBotPredictURLPhishing failing on rasterize errors
  Packs/PhishingURL/ReleaseNotes/1_1_13.md
  Packs/PhishingURL/Scripts/DBotPredictURLPhishing/DBotPredictURLPhishing.py
  Packs/PhishingURL/Scripts/DBotPredictURLPhishing/dbotpredicturlphishing_test.py
  Packs/PhishingURL/pack_metadata.json
Labels: docs-approved

#34066 ActiveMQ Config Data Types
  Packs/ActiveMQ/Integrations/ActiveMQ/ActiveMQ.yml
  Packs/ActiveMQ/ReleaseNotes/1_1_15.md
  Packs/ActiveMQ/pack_metadata.json
Labels: docs-approved

#33926 [ASM] EXPANDR-9134 service account changes
  Packs/CortexAttackSurfaceManagement/Playbooks/Cortex_ASM_-_GCP_Enrichment.yml
  Packs/CortexAttackSurfaceManagement/Playbooks/Cortex_ASM_-_Service_Ownership.yml
  Packs/CortexAttackSurfaceManagement/ReleaseNotes/1_7_33.md
  Packs/CortexAttackSurfaceManagement/doc_files/Cortex_ASM_-_GCP_Enrichment.png
  Packs/CortexAttackSurfaceManagement/pack_metadata.json
Labels: Contribution, docs-approved, Contribution Form Filled, Community, Xsoar Support Level, External PR, Security Review
