Repository demisto/content, pull requests merged in 2024-01, with the labels that each got.

#31804 change on call to thefrieddan1 and MosheEichler
  .github/content_roles.json
Labels: docs-approved

#31686 IPv6 regex update
  Packs/Base/.secrets-ignore
  Packs/Base/TestPlaybooks/playbook-IPv6_extraction_test.yml
  Packs/CommonTypes/IndicatorTypes/reputation-ipv6.json
  Packs/CommonTypes/ReleaseNotes/3_3_97.md
  Packs/CommonTypes/pack_metadata.json
Labels: docs-approved

#31873 Ews new rules commands
  Packs/MicrosoftExchangeOnline/Integrations/EwsExtensionEXOPowershellV3/EwsExtensionEXOPowershellV3.ps1
  Packs/MicrosoftExchangeOnline/Integrations/EwsExtensionEXOPowershellV3/EwsExtensionEXOPowershellV3.yml
  Packs/MicrosoftExchangeOnline/Integrations/EwsExtensionEXOPowershellV3/README.md
  Packs/MicrosoftExchangeOnline/ReleaseNotes/1_2_36.md
  Packs/MicrosoftExchangeOnline/TestPlaybooks/O365-EWS-Extension-Powershell-Online-V3-Test copy.yml
  Packs/MicrosoftExchangeOnline/pack_metadata.json
Labels: docs-approved

#31876 added support to assets modeling rules
  Tests/Marketplace/marketplace_constants.py
  Tests/scripts/collect_tests/collect_tests.py
  Tests/scripts/collect_tests/constants.py
  Tests/scripts/infrastructure_tests/test_collect_tests.py
Labels: docs-approved

#31884 Edit playbook name
  Packs/MicrosoftExchangeOnline/TestPlaybooks/O365-EWS-Extension-Powershell-Online-V3-Test.yml
Labels: docs-approved

#31664 FortiGate Enhancement
  Packs/FortiGate/.secrets-ignore
  Packs/FortiGate/Integrations/FortiGate/FortiGate.py
  Packs/FortiGate/Integrations/FortiGate/FortiGate.yml
  Packs/FortiGate/Integrations/FortiGate/FortiGate_description.md
  Packs/FortiGate/Integrations/FortiGate/FortiGate_test.py
  Packs/FortiGate/Integrations/FortiGate/README.md
  Packs/FortiGate/Integrations/FortiGate/test_data/address_ipv4_group_outputs.json
  Packs/FortiGate/Integrations/FortiGate/test_data/address_ipv4_group_response.json
  Packs/FortiGate/Integrations/FortiGate/test_data/address_ipv4_multicast_outputs.json
  Packs/FortiGate/Integrations/FortiGate/test_data/address_ipv4_multicast_response.json
  Packs/FortiGate/Integrations/FortiGate/test_data/address_ipv4_outputs.json
  Packs/FortiGate/Integrations/FortiGate/test_data/address_ipv4_response.json
  Packs/FortiGate/Integrations/FortiGate/test_data/address_ipv6_group_outputs.json
  Packs/FortiGate/Integrations/FortiGate/test_data/address_ipv6_group_response.json
  Packs/FortiGate/Integrations/FortiGate/test_data/address_ipv6_multicast_outputs.json
  Packs/FortiGate/Integrations/FortiGate/test_data/address_ipv6_multicast_response.json
  Packs/FortiGate/Integrations/FortiGate/test_data/address_ipv6_outputs.json
  Packs/FortiGate/Integrations/FortiGate/test_data/address_ipv6_response.json
  Packs/FortiGate/Integrations/FortiGate/test_data/banned_ip_outputs.json
  Packs/FortiGate/Integrations/FortiGate/test_data/banned_ip_response.json
  Packs/FortiGate/Integrations/FortiGate/test_data/non_get_response.json
  Packs/FortiGate/Integrations/FortiGate/test_data/policy_outputs.json
  Packs/FortiGate/Integrations/FortiGate/test_data/policy_response.json
  Packs/FortiGate/Integrations/FortiGate/test_data/service_group_outputs.json
  Packs/FortiGate/Integrations/FortiGate/test_data/service_group_response.json
  Packs/FortiGate/Integrations/FortiGate/test_data/service_outputs.json
  Packs/FortiGate/Integrations/FortiGate/test_data/service_response.json
  Packs/FortiGate/Integrations/FortiGate/test_data/vdom_outputs.json
  Packs/FortiGate/Integrations/FortiGate/test_data/vdom_response.json
  Packs/FortiGate/ReleaseNotes/2_0_0.md
  Packs/FortiGate/TestPlaybooks/playbook-Fortigate_Test.yml
  Packs/FortiGate/pack_metadata.json
Labels: Contribution, Contribution Form Filled, Community, Xsoar Support Level, External PR, Security Review

#31886 Revert Changes In conf.json File
  Tests/conf.json
Labels: docs-approved

#31569 Bugfix/CIAC-8180/Command_line_analysis_missing_output_declarations
  Packs/CommonPlaybooks/Playbooks/playbook-Command-Line_Analysis.yml
  Packs/CommonPlaybooks/Playbooks/playbook-Command-Line_Analysis_README.md
  Packs/CommonPlaybooks/ReleaseNotes/2_5_2.md
  Packs/CommonPlaybooks/pack_metadata.json
Labels: docs-approved

#31750 Reverted migration changes
  .circleci/config.yml
  .gitlab/ci/.gitlab-ci.bucket-upload.yml
  .gitlab/ci/.gitlab-ci.build-machines-cleanup.yml
  .gitlab/ci/.gitlab-ci.global.yml
  .gitlab/ci/.gitlab-ci.on-push.yml
  .gitlab/ci/.gitlab-ci.sdk-nightly.yml
  .gitlab/ci/.gitlab-ci.variables.yml
  Tests/Marketplace/Tests/copy_and_upload_packs_test.py
  Tests/Marketplace/Tests/search_and_install_packs_test.py
  Tests/Marketplace/Tests/upload_packs_test.py
  Tests/Marketplace/install_packs.sh
  Tests/Marketplace/marketplace_constants.py
  Tests/Marketplace/upload_packs.py
  Tests/configure_and_test_integration_instances.py
  Tests/scripts/install_content_and_test_integrations.sh
  Tests/scripts/lock_cloud_machines.py
  Tests/scripts/prepare_content_packs_for_testing.sh
  Tests/scripts/prepare_private_content_packs_for_testing.sh
  Tests/scripts/reinstall_packs_on_cloud_instances.sh
  Tests/scripts/run_e2e_tests.sh
  Tests/scripts/run_tests.sh
  Tests/scripts/test_modeling_rules.sh
  Tests/scripts/uninstall_packs_and_reset_bucket_cloud.sh
  Utils/download_packs_and_docker_images.py
  Utils/gitlab_triggers/trigger_content_instance_testing_build.sh
  Utils/gitlab_triggers/trigger_content_nightly_build.sh
  Utils/gitlab_triggers/trigger_upload_flow_build.sh
  Utils/merge_content_new_zip.py
  Utils/trigger_test_upload_flow.sh
  Utils/upload_code_coverage_report.py
Labels: docs-approved

#31839 check dependency version
  Tests/Marketplace/search_and_install_packs.py
Labels: docs-approved

#31711 Feed misp
  Packs/FeedMISP/Integrations/FeedMISP/FeedMISP.py
  Packs/FeedMISP/Integrations/FeedMISP/FeedMISP.yml
  Packs/FeedMISP/Integrations/FeedMISP/FeedMISP_test.py
  Packs/FeedMISP/ReleaseNotes/1_0_30.md
  Packs/FeedMISP/pack_metadata.json
Labels: docs-approved

#31892 Forcepoint dlp eventcollector
  Packs/ForcepointDLP/.pack-ignore
  Packs/ForcepointDLP/Integrations/ForcepointEventCollector/ForcepointEventCollector.py
  Packs/ForcepointDLP/Integrations/ForcepointEventCollector/ForcepointEventCollector.yml
  Packs/ForcepointDLP/Integrations/ForcepointEventCollector/ForcepointEventCollector_description.md
  Packs/ForcepointDLP/Integrations/ForcepointEventCollector/ForcepointEventCollector_image.png
  Packs/ForcepointDLP/Integrations/ForcepointEventCollector/ForcepointEventCollector_test.py
  Packs/ForcepointDLP/Integrations/ForcepointEventCollector/README.md
  Packs/ForcepointDLP/Integrations/ForcepointEventCollector/command_examples
  Packs/ForcepointDLP/ModelingRules/ForcepointDLP_1_4/ForcepointDLP_1_4.xif
  Packs/ForcepointDLP/ModelingRules/ForcepointDLP_1_4/ForcepointDLP_1_4_schema.json
  Packs/ForcepointDLP/ParsingRules/ForcepointDLP/ForcepointDLP.xif
  Packs/ForcepointDLP/ReleaseNotes/1_0_2.md
  Packs/ForcepointDLP/pack_metadata.json
Labels: docs-approved

#31773 RecordedFuture event collector: using and align the new api endpoint
  Packs/RecordedFuture/Integrations/RecordedFutureEventCollector/RecordedFutureEventCollector.py
  Packs/RecordedFuture/Integrations/RecordedFutureEventCollector/RecordedFutureEventCollector_test.py
  Packs/RecordedFuture/Integrations/RecordedFutureEventCollector/test_data/first_fetch.json
  Packs/RecordedFuture/Integrations/RecordedFutureEventCollector/test_data/second_fetch.json
  Packs/RecordedFuture/ModelingRules/RecordedFutureModelingRules_1_4/RecordedFutureModelingRules_1_4.xif
  Packs/RecordedFuture/ReleaseNotes/1_7_7.md
  Packs/RecordedFuture/pack_metadata.json
Labels: docs-approved

#31774 [CrowdStrike Falcon] Add 2 new commands, and update existing
  Packs/CrowdStrikeFalcon/.secrets-ignore
  Packs/CrowdStrikeFalcon/Integrations/CrowdStrikeFalcon/CrowdStrikeFalcon.py
  Packs/CrowdStrikeFalcon/Integrations/CrowdStrikeFalcon/CrowdStrikeFalcon.yml
  Packs/CrowdStrikeFalcon/Integrations/CrowdStrikeFalcon/CrowdStrikeFalcon_test.py
  Packs/CrowdStrikeFalcon/Integrations/CrowdStrikeFalcon/README.md
  Packs/CrowdStrikeFalcon/Integrations/CrowdStrikeFalcon/examples.txt
  Packs/CrowdStrikeFalcon/Integrations/CrowdStrikeFalcon/test_data/entities_behaviors_response.json
  Packs/CrowdStrikeFalcon/Integrations/CrowdStrikeFalcon/test_data/input_data.py
  Packs/CrowdStrikeFalcon/Integrations/CrowdStrikeFalcon/test_data/list_users_command/entities_users_response.json
  Packs/CrowdStrikeFalcon/Integrations/CrowdStrikeFalcon/test_data/list_users_command/queries_users_response.json
  Packs/CrowdStrikeFalcon/ReleaseNotes/1_12_10.md
  Packs/CrowdStrikeFalcon/pack_metadata.json
Labels: docs-approved

#31274 Add new validate manager to builds
  .gitlab/ci/.gitlab-ci.global.yml
  Tests/scripts/check_jobs_done.py
Labels: docs-approved

#31916 Revert "Add new validate manager to builds"
  .gitlab/ci/.gitlab-ci.global.yml
  Tests/scripts/check_jobs_done.py
Labels: docs-approved, ForceMerge

#31912 Updated OktaModelingRules_2_0
  Packs/Okta/ModelingRules/OktaModelingRules_2_0/OktaModelingRules_2_0.xif
  Packs/Okta/ReleaseNotes/3_2_7.md
  Packs/Okta/pack_metadata.json
Labels: docs-approved

#31877 Fix SplunkPy splunk-kv-store-collection-data-list description
  Packs/SplunkPy/Integrations/SplunkPy/SplunkPy.yml
  Packs/SplunkPy/ReleaseNotes/3_1_15.md
  Packs/SplunkPy/pack_metadata.json
Labels: docs-approved

#31642 [long-running] - restart container if total is None
  Packs/Base/ReleaseNotes/1_33_11.md
  Packs/Base/Scripts/CommonServerPython/CommonServerPython.py
  Packs/Base/Scripts/CommonServerPython/CommonServerPython_test.py
  Packs/Base/pack_metadata.json
  Packs/CloudIncidentResponse/Scripts/XCloudAdditionalAlertInformationWidget/XCloudAdditionalAlertInformationWidget_test.py
  Packs/Core/Integrations/CoreIOCs/CoreIOCs_test.py
  Packs/CortexXDR/Integrations/XDR_iocs/XDR_iocs_test.py
  Packs/ExpanseV2/Integrations/ExpanseV2/ExpanseV2_test.py
  Packs/FeedCyrenThreatInDepth/Scripts/CyrenThreatInDepthRenderRelated/CyrenThreatInDepthRenderRelated_test.py
  Packs/MandiantAdvantageThreatIntelligence/Integrations/MandiantAdvantageThreatIntelligence/MandiantAdvantageThreatIntelligence_test.py
  Packs/ThreatIntelligenceManagement/Scripts/ThreatIntelligenceManagementGetIncidentsPerFeed/ThreatIntelligenceManagementGetIncidentsPerFeed_test.py
Labels: docs-approved

#31681 [Saas e2e] - Print all errors messages coming from war-room entries
  Tests/tests_e2e/content/xsoar_saas/test_e2e_xsoar_saas.py
Labels: docs-approved

#31853 Change 'incident' to 'alert' only for XSIAM
  Packs/Base/ReleaseNotes/1_33_12.md
  Packs/Base/Scripts/DBotFindSimilarIncidents/DBotFindSimilarIncidents.py
  Packs/Base/Scripts/DBotFindSimilarIncidents/DBotFindSimilarIncidents.yml
  Packs/Base/pack_metadata.json
  Packs/CommonScripts/ReleaseNotes/1_13_17.md
  Packs/CommonScripts/Scripts/FindSimilarIncidentsV2/FindSimilarIncidentsV2.py
  Packs/CommonScripts/pack_metadata.json
Labels: docs-approved

#31869 Extract Indicators From File - Generic v2 - Performance Improvements
  Packs/CommonPlaybooks/Playbooks/playbook-Extract_Indicators_From_File_-_Generic_v2_4_5.yml
  Packs/CommonPlaybooks/Playbooks/playbook-Extract_Indicators_From_File_-_Generic_v2_4_5_README.md
  Packs/CommonPlaybooks/ReleaseNotes/2_5_3.md
  Packs/CommonPlaybooks/doc_files/Extract_Indicators_From_File_-_Generic_v2.png
  Packs/CommonPlaybooks/pack_metadata.json
Labels: docs-approved, release-notes-only

#31925 Upgrade tj-actions/changed-files
  .github/workflows/review-release-notes.yml
  Tests/secrets_white_list.json
Labels: docs-approved

#31524 Microsoft ECM - added a check to verify if the drive exist, if not create it before Set-Location
  Packs/MicrosoftECM/Integrations/MicrosoftECM/MicrosoftECM.ps1
  Packs/MicrosoftECM/Integrations/MicrosoftECM/MicrosoftECM.yml
  Packs/MicrosoftECM/ReleaseNotes/1_0_10.md
  Packs/MicrosoftECM/pack_metadata.json
Labels: docs-approved

#31924 fix CSP logs
  Packs/Base/ReleaseNotes/1_33_13.md
  Packs/Base/Scripts/CommonServerPython/CommonServerPython.py
  Packs/Base/pack_metadata.json
Labels: docs-approved

#31935 Update README.md
  Packs/CommonScripts/Scripts/SetGridField/README.md
Labels: docs-approved

#31936 Added round transformer for playbook "wait until datetime"
  Packs/CommonPlaybooks/Playbooks/playbook-Wait_Until_Datetime.yml
  Packs/CommonPlaybooks/ReleaseNotes/2_5_4.md
  Packs/CommonPlaybooks/pack_metadata.json
Labels: docs-approved

#31891 [Autobump] added handle error when merge fails
  Utils/github_workflow_scripts/autobump_release_notes/skip_conditions.py
Labels: docs-approved

#31950 Revert palo alto networks core expandr 3361 3
  Packs/CommonScripts/ReleaseNotes/1_13_18.md
  Packs/CommonScripts/pack_metadata.json
  Packs/FeedMitreAttackv2/pack_metadata.json
  Packs/MalwareInvestigationAndResponse/Scripts/ReadNetstatFileWrapper/ReadNetstatFileWrapper.yml
  Packs/MalwareInvestigationAndResponse/Scripts/ReadProcessFileWrapper/ReadProcessFileWrapper.yml
  Packs/MalwareInvestigationAndResponse/pack_metadata.json
  Tests/Marketplace/core_packs_xpanse_list.json
Labels: docs-approved, ForceMerge

#31351 Service now mirroring issue fix
  Packs/ServiceNow/Integrations/ServiceNowv2/ServiceNowv2.py
  Packs/ServiceNow/Integrations/ServiceNowv2/ServiceNowv2_test.py
  Packs/ServiceNow/ReleaseNotes/2_5_49.md
  Packs/ServiceNow/pack_metadata.json
Labels: docs-approved

#31866 [O365 File Management] Add Auth code authentication support
  Packs/MicrosoftGraphFiles/Integrations/MicrosoftGraphFiles/MicrosoftGraphFiles.py
  Packs/MicrosoftGraphFiles/Integrations/MicrosoftGraphFiles/MicrosoftGraphFiles.yml
  Packs/MicrosoftGraphFiles/Integrations/MicrosoftGraphFiles/MicrosoftGraphFiles_description.md
  Packs/MicrosoftGraphFiles/Integrations/MicrosoftGraphFiles/MicrosoftGraphFiles_test.py
  Packs/MicrosoftGraphFiles/Integrations/MicrosoftGraphFiles/README.md
  Packs/MicrosoftGraphFiles/ReleaseNotes/1_1_21.md
  Packs/MicrosoftGraphFiles/pack_metadata.json
Labels: docs-approved

#31849 EXPANDR-5778: Organizational scope searching for EC2
  Packs/AWS-Enrichment-Remediation/.pack-ignore
  Packs/AWS-Enrichment-Remediation/Playbooks/AWS_-_Enrichment.yml
  Packs/AWS-Enrichment-Remediation/Playbooks/AWS_-_Enrichment_README.md
  Packs/AWS-Enrichment-Remediation/ReleaseNotes/1_1_11.md
  Packs/AWS-Enrichment-Remediation/doc_files/AWS_-_Enrichment.png
  Packs/AWS-Enrichment-Remediation/pack_metadata.json
Labels: Contribution, docs-approved, Contribution Form Filled, Community, Xsoar Support Level, External PR, Security Review

#31780 Xsup 31703 pager duty
  Packs/PagerDuty/Integrations/PagerDuty/PagerDuty.py
  Packs/PagerDuty/Integrations/PagerDuty/PagerDuty.yml
  Packs/PagerDuty/Integrations/PagerDuty/PagerDuty_test.py
  Packs/PagerDuty/ReleaseNotes/1_1_9.md
  Packs/PagerDuty/pack_metadata.json
Labels: docs-approved

#31965 [Pre-Commit] Dont comment in fork PR
  .github/workflows/pre-commit-reuse.yml
Labels: docs-approved

#31918 Added support for attachCIDs argument - EmailAskUser
  Packs/CommonScripts/ReleaseNotes/1_13_19.md
  Packs/CommonScripts/Scripts/EmailAskUser/EmailAskUser.js
  Packs/CommonScripts/Scripts/EmailAskUser/EmailAskUser.yml
  Packs/CommonScripts/Scripts/EmailAskUser/README.md
  Packs/CommonScripts/pack_metadata.json
Labels: docs-approved, ForceMerge

#31854 GCP - Specify instance on 'GCP - Firewall Remediation' playbook
  Packs/GCP-Enrichment-Remediation/.pack-ignore
  Packs/GCP-Enrichment-Remediation/Playbooks/GCP_-_Firewall_Remediation.yml
  Packs/GCP-Enrichment-Remediation/Playbooks/GCP_-_Firewall_Remediation_README.md
  Packs/GCP-Enrichment-Remediation/ReleaseNotes/1_1_13.md
  Packs/GCP-Enrichment-Remediation/pack_metadata.json
Labels: Contribution, docs-approved, ready-for-instance-test, Contribution Form Filled, Community, Xsoar Support Level, External PR, Security Review

#31940 Okta event type update2
  Packs/Okta/ModelingRules/OktaModelingRules_2_0/OktaModelingRules_2_0.xif
  Packs/Okta/ReleaseNotes/3_2_8.md
  Packs/Okta/pack_metadata.json
Labels: docs-approved

#31957 Add description to google sheets spreadsheet get command
  Packs/GoogleSheets/Integrations/GoogleSheets/GoogleSheets.yml
  Packs/GoogleSheets/ReleaseNotes/1_0_39.md
  Packs/GoogleSheets/pack_metadata.json
Labels: docs-approved

#31673 [Rapid7] - handle connection errors
  Packs/QRadar/Integrations/QRadar_v3/QRadar_v3_test.py
  Packs/Rapid7_Nexpose/Integrations/Rapid7_Nexpose/Rapid7_Nexpose.py
  Packs/Rapid7_Nexpose/Integrations/Rapid7_Nexpose/Rapid7_Nexpose.yml
  Packs/Rapid7_Nexpose/Integrations/Rapid7_Nexpose/Rapid7_Nexpose_test.py
  Packs/Rapid7_Nexpose/ReleaseNotes/1_2_19.md
  Packs/Rapid7_Nexpose/pack_metadata.json
Labels: docs-approved

#31971 Update README.md
  Packs/CommonScripts/Scripts/SetGridField/README.md
Labels: docs-approved

#31984 freeze time for Devo UT
  Packs/Devo/Integrations/Devo_v2/Devo_v2_test.py
Labels: docs-approved

#31855 [ASM] - EXPANDR-6923 Prisma cloud changes
  Packs/CortexAttackSurfaceManagement/Playbooks/Cortex_ASM_-_Azure_Enrichment.yml
  Packs/CortexAttackSurfaceManagement/Playbooks/Cortex_ASM_-_Prisma_Cloud_Enrichment.yml
  Packs/CortexAttackSurfaceManagement/ReleaseNotes/1_7_18.md
  Packs/CortexAttackSurfaceManagement/pack_metadata.json
Labels: Contribution, docs-approved, ready-for-instance-test, Contribution Form Filled, Community, pending-contributor, Xsoar Support Level, External PR, Security Review

#31994 Update Documentation for S&C
  Packs/MicrosoftExchangeOnline/Integrations/SecurityAndComplianceV2/README.md
Labels: docs-approved

#31977 Enhancement ecm sccm username field
  Packs/MicrosoftECM/ModelingRules/MicrosoftECM_1_3/MicrosoftECM_1_3.xif
  Packs/MicrosoftECM/ReleaseNotes/1_0_11.md
  Packs/MicrosoftECM/pack_metadata.json
Labels: docs-approved

#31733 Taxii 2 feed last run issue fix
  Packs/TAXIIServer/Integrations/TAXII2Server/TAXII2Server.py
  Packs/TAXIIServer/Integrations/TAXII2Server/TAXII2Server.yml
  Packs/TAXIIServer/Integrations/TAXII2Server/TAXII2Server_test.py
  Packs/TAXIIServer/ReleaseNotes/2_0_53.md
  Packs/TAXIIServer/pack_metadata.json
Labels: docs-approved, ForceMerge

#31982 GCP - Specify instance on 'GCP - Firewall Remediation' playbook (#31854)
  Packs/GCP-Enrichment-Remediation/.pack-ignore
  Packs/GCP-Enrichment-Remediation/Playbooks/GCP_-_Firewall_Remediation.yml
  Packs/GCP-Enrichment-Remediation/Playbooks/GCP_-_Firewall_Remediation_README.md
  Packs/GCP-Enrichment-Remediation/ReleaseNotes/1_1_13.md
  Packs/GCP-Enrichment-Remediation/pack_metadata.json
Labels: docs-approved

#32001 CRTX-101690: Release a new base pack
  Packs/Base/ReleaseNotes/1_33_14.md
  Packs/Base/Scripts/SanePdfReport/SanePdfReport.yml
  Packs/Base/pack_metadata.json
Labels: docs-approved

#31981 GenericPolling - performance improvement
  Packs/CommonPlaybooks/Playbooks/playbook-GenericPolling.yml
  Packs/CommonPlaybooks/ReleaseNotes/2_5_5.md
  Packs/CommonPlaybooks/pack_metadata.json
Labels: docs-approved, release-notes-only

#31993 Function to extract data without using DT
  Packs/AWS-Enrichment-Remediation/ReleaseNotes/1_1_11.md
  Packs/AWS-Enrichment-Remediation/Scripts/AWSRecreateSG/AWSRecreateSG.py
  Packs/AWS-Enrichment-Remediation/Scripts/AWSRecreateSG/AWSRecreateSG_test.py
  Packs/AWS-Enrichment-Remediation/pack_metadata.json
Labels: docs-approved

#31996 Clearify the integration description
  Packs/Fortimail/Integrations/Fortimail/Fortimail_description.md
  Packs/Fortimail/ReleaseNotes/1_0_1.md
  Packs/Fortimail/pack_metadata.json
Labels: docs-approved

#31948 bug fix
  Packs/Infoblox/ParsingRules/InfobloxParsingRules/InfobloxParsingRules.xif
  Packs/Infoblox/ReleaseNotes/1_0_19.md
  Packs/Infoblox/pack_metadata.json
Labels: docs-approved

#31938 FeedRecordedFuture Avoid Null Byte
  Packs/FeedRecordedFuture/Integrations/FeedRecordedFuture/FeedRecordedFuture.py
  Packs/FeedRecordedFuture/Integrations/FeedRecordedFuture/FeedRecordedFuture.yml
  Packs/FeedRecordedFuture/ReleaseNotes/1_0_33.md
  Packs/FeedRecordedFuture/pack_metadata.json
Labels: docs-approved

#31885 Block file generic enhancment for mde and falcon
  Packs/CommonPlaybooks/Playbooks/playbook-Block_File_-_Generic_v2.yml
  Packs/CommonPlaybooks/Playbooks/playbook-Block_File_-_Generic_v2_README.md
  Packs/CommonPlaybooks/ReleaseNotes/2_5_6.md
  Packs/CommonPlaybooks/doc_files/Block_File_-_Generic_v2.png
  Packs/CommonPlaybooks/pack_metadata.json
  Packs/CrowdStrikeFalcon/Playbooks/CrowdStrike_Falcon_-_Block_File.yml
  Packs/CrowdStrikeFalcon/Playbooks/CrowdStrike_Falcon_-_Block_File_README.md
  Packs/CrowdStrikeFalcon/ReleaseNotes/1_12_11.md
  Packs/CrowdStrikeFalcon/doc_files/CrowdStrike_Falcon_-_Block_File.png
  Packs/CrowdStrikeFalcon/pack_metadata.json
  Packs/MicrosoftDefenderAdvancedThreatProtection/Playbooks/MDE_-_Block_File.yml
  Packs/MicrosoftDefenderAdvancedThreatProtection/Playbooks/MDE_-_Block_File_README.md
  Packs/MicrosoftDefenderAdvancedThreatProtection/ReleaseNotes/1_16_24.md
  Packs/MicrosoftDefenderAdvancedThreatProtection/doc_files/MDE_-_Block_File.png
  Packs/MicrosoftDefenderAdvancedThreatProtection/pack_metadata.json
Labels: docs-approved

#31988 [SentinelOne] Update argument computer_name of command sentinelone-list-agents
  Packs/SentinelOne/Integrations/SentinelOne-V2/README.md
  Packs/SentinelOne/Integrations/SentinelOne-V2/SentinelOne-V2.py
  Packs/SentinelOne/Integrations/SentinelOne-V2/SentinelOne-V2.yml
  Packs/SentinelOne/ReleaseNotes/3_2_17.md
  Packs/SentinelOne/pack_metadata.json
Labels: Contribution, ready-for-instance-test, Contribution Form Filled, Community, Partner Support Level, External PR, Partner-Approved

#31998 [sdk-nightly] - use only sanity playbook without integrations
  Tests/scripts/collect_tests/collect_tests.py
Labels: docs-approved

#31946 Updated outputs to cmds ip and abuseipdb-check-cidr-block
  Packs/AbuseDB/Integrations/AbuseDB/AbuseDB.py
  Packs/AbuseDB/Integrations/AbuseDB/AbuseDB.yml
  Packs/AbuseDB/Integrations/AbuseDB/README.md
  Packs/AbuseDB/ReleaseNotes/1_0_30.md
  Packs/AbuseDB/pack_metadata.json
Labels: Contribution, ready-for-instance-test, Contribution Form Filled, Community, Xsoar Support Level, External PR, TIM Review

#31890 Inputs groups playbooks improvement xsoar
  Packs/CloudIncidentResponse/Playbooks/playbook-Cortex_XDR_-_Cloud_Cryptomining.yml
  Packs/CloudIncidentResponse/Playbooks/playbook-Cortex_XDR_-_Cloud_Cryptomining_README.md
  Packs/CloudIncidentResponse/Playbooks/playbook-Cortex_XDR_-_Cloud_IAM_User_Access_Investigation.yml
  Packs/CloudIncidentResponse/Playbooks/playbook-Cortex_XDR_-_Cloud_IAM_User_Access_Investigation_README.md
  Packs/CloudIncidentResponse/ReleaseNotes/1_0_11.md
  Packs/CloudIncidentResponse/pack_metadata.json
  Packs/CommonPlaybooks/Playbooks/playbook-Cloud_User_Investigation_-_Generic.yml
  Packs/CommonPlaybooks/Playbooks/playbook-Cloud_User_Investigation_-_Generic_README.md
  Packs/CommonPlaybooks/ReleaseNotes/2_5_7.md
  Packs/CommonPlaybooks/pack_metadata.json
  Packs/CortexXDR/Playbooks/Cortex_XDR_incident_handling_v3_6_5.yml
  Packs/CortexXDR/Playbooks/Cortex_XDR_incident_handling_v3_6_5_README.md
  Packs/CortexXDR/Playbooks/playbook-Cortex_XDR_Lite_-_Incident_Handling.yml
  Packs/CortexXDR/Playbooks/playbook-Cortex_XDR_Lite_-_Incident_Handling_README.md
  Packs/CortexXDR/ReleaseNotes/6_1_2.md
  Packs/CortexXDR/pack_metadata.json
  Packs/MalwareInvestigationAndResponse/Playbooks/playbook-Malware_Investigation_and_Response_Incident_Handler.yml
  Packs/MalwareInvestigationAndResponse/Playbooks/playbook-Malware_Investigation_and_Response_Incident_Handler_README.md
  Packs/MalwareInvestigationAndResponse/ReleaseNotes/2_0_12.md
  Packs/MalwareInvestigationAndResponse/pack_metadata.json
Labels: docs-approved

#31702 Sanitize Curl Logs
  Packs/Base/ReleaseNotes/1_33_15.md
  Packs/Base/Scripts/CommonServerPython/CommonServerPython.py
  Packs/Base/Scripts/CommonServerPython/CommonServerPython_test.py
  Packs/Base/pack_metadata.json
Labels: docs-approved, ForceMerge

#31706 CiscoWebex event collector
  Packs/CiscoSpark/.secrets-ignore
  Packs/CiscoSpark/Integrations/CiscoWebexEventCollector/CiscoWebexEventCollector.py
  Packs/CiscoSpark/Integrations/CiscoWebexEventCollector/CiscoWebexEventCollector.yml
  Packs/CiscoSpark/Integrations/CiscoWebexEventCollector/CiscoWebexEventCollector_description.md
  Packs/CiscoSpark/Integrations/CiscoWebexEventCollector/CiscoWebexEventCollector_image.png
  Packs/CiscoSpark/Integrations/CiscoWebexEventCollector/CiscoWebexEventCollector_test.py
  Packs/CiscoSpark/Integrations/CiscoWebexEventCollector/README.md
  Packs/CiscoSpark/Integrations/CiscoWebexEventCollector/command_examples
  Packs/CiscoSpark/Integrations/CiscoWebexEventCollector/test_data/admin_audits.json
  Packs/CiscoSpark/Integrations/CiscoWebexEventCollector/test_data/events.json
  Packs/CiscoSpark/Integrations/CiscoWebexEventCollector/test_data/no_events.json
  Packs/CiscoSpark/Integrations/CiscoWebexEventCollector/test_data/security_audits.json
  Packs/CiscoSpark/ModelingRules/CiscoWebex/CiscoWebex.xif
  Packs/CiscoSpark/ModelingRules/CiscoWebex/CiscoWebex.yml
  Packs/CiscoSpark/ModelingRules/CiscoWebex/CiscoWebex_schema.json
  Packs/CiscoSpark/ReleaseNotes/1_0_5.md
  Packs/CiscoSpark/doc_files/get_organization_id.png
  Packs/CiscoSpark/pack_metadata.json
Labels: docs-approved

#32048 [xsoar-saas-e2e-taxii2] - break when test is complete
  Tests/tests_e2e/content/xsoar_saas/test_e2e_xsoar_saas.py
Labels: docs-approved

#31416 Add support for running AWS - EC2 commands on all accounts
  Packs/AWS-EC2/Integrations/AWS-EC2/AWS-EC2.py
  Packs/AWS-EC2/Integrations/AWS-EC2/AWS-EC2.yml
  Packs/AWS-EC2/Integrations/AWS-EC2/AWS-EC2_test.py
  Packs/AWS-EC2/Integrations/AWS-EC2/README.md
  Packs/AWS-EC2/ReleaseNotes/1_3_0.md
  Packs/AWS-EC2/pack_metadata.json
Labels: docs-approved

#32052 CRTX-101690: Release a new base pack
  Packs/Base/ReleaseNotes/1_33_16.md
  Packs/Base/Scripts/SanePdfReport/SanePdfReport.yml
  Packs/Base/pack_metadata.json
Labels: docs-approved

#31999 Refactor user invitation logic in Slack, Add incidentAssigned to notification types
  Packs/Slack/Integrations/SlackV3/SlackV3.py
  Packs/Slack/Integrations/SlackV3/SlackV3.yml
  Packs/Slack/Integrations/SlackV3/SlackV3_test.py
  Packs/Slack/ReleaseNotes/3_4_1.md
  Packs/Slack/pack_metadata.json
Labels: docs-approved

#32031 Cisco isr testdata fix
  Packs/CiscoISR/ParsingRules/CiscoISR/CiscoISR.xif
  Packs/CiscoISR/ReleaseNotes/1_0_2.md
  Packs/CiscoISR/pack_metadata.json
Labels: docs-approved

#32019 Cisco catalyst testdata fix
  Packs/CiscoCatalyst/ParsingRules/CiscoCatalyst/CiscoCatalyst.xif
  Packs/CiscoCatalyst/ReleaseNotes/1_0_4.md
  Packs/CiscoCatalyst/pack_metadata.json
Labels: docs-approved

#31949 [Palo Alto Networks Security Advisories]
  Packs/PaloAltoNetworks_SecurityAdvisories/.secrets-ignore
  Packs/PaloAltoNetworks_SecurityAdvisories/Integrations/PaloAltoNetworksSecurityAdvisories/CONTRIBUTORS.json
  Packs/PaloAltoNetworks_SecurityAdvisories/Integrations/PaloAltoNetworksSecurityAdvisories/PaloAltoNetworksSecurityAdvisories.py
  Packs/PaloAltoNetworks_SecurityAdvisories/Integrations/PaloAltoNetworksSecurityAdvisories/PaloAltoNetworksSecurityAdvisories.yml
  Packs/PaloAltoNetworks_SecurityAdvisories/Integrations/PaloAltoNetworksSecurityAdvisories/PaloAltoNetworksSecurityAdvisories_test.py
  Packs/PaloAltoNetworks_SecurityAdvisories/Integrations/PaloAltoNetworksSecurityAdvisories/test_data/advisories4.json
  Packs/PaloAltoNetworks_SecurityAdvisories/ReleaseNotes/1_0_5.md
  Packs/PaloAltoNetworks_SecurityAdvisories/Scripts/CheckPanosVersionAffected/CheckPanosVersionAffected.py
  Packs/PaloAltoNetworks_SecurityAdvisories/Scripts/CheckPanosVersionAffected/CheckPanosVersionAffected.yml
  Packs/PaloAltoNetworks_SecurityAdvisories/pack_metadata.json
Labels: Contribution, docs-approved, ready-for-instance-test, Contribution Form Filled, Community, pending-contributor, Xsoar Support Level, External PR, TIM Review

#32054 Add the 'Stringify' transformer to the sleep task - fix a bug
  Packs/CommonPlaybooks/.pack-ignore
  Packs/CommonPlaybooks/Playbooks/playbook-Wait_Until_Datetime.yml
  Packs/CommonPlaybooks/ReleaseNotes/2_5_8.md
  Packs/CommonPlaybooks/pack_metadata.json
Labels: docs-approved

#32053 Encode branch name when checking if a PR exist for a branch
  .gitlab/ci/.gitlab-ci.global.yml
Labels: docs-approved

#31964 Xsoar saas upload test 2
  .gitlab/ci/.gitlab-ci.on-push.yml
  .gitlab/ci/.gitlab-ci.variables.yml
  Utils/test_upload_flow/TestUploadFlowXSOAR/ReleaseNotes/1_0_0.md
  Utils/test_upload_flow/TestUploadFlowXsoarSaaS/.pack-ignore
  Utils/test_upload_flow/TestUploadFlowXsoarSaaS/.secrets-ignore
  Utils/test_upload_flow/TestUploadFlowXsoarSaaS/README.md
  Utils/test_upload_flow/TestUploadFlowXsoarSaaS/ReleaseNotes/1_0_0.md
  Utils/test_upload_flow/TestUploadFlowXsoarSaaS/Scripts/XsoarSaaSOnlyScript/README.md
  Utils/test_upload_flow/TestUploadFlowXsoarSaaS/Scripts/XsoarSaaSOnlyScript/XsoarSaaSOnlyScript.py
  Utils/test_upload_flow/TestUploadFlowXsoarSaaS/Scripts/XsoarSaaSOnlyScript/XsoarSaaSOnlyScript.yml
  Utils/test_upload_flow/TestUploadFlowXsoarSaaS/Scripts/XsoarSaaSOnlyScript/XsoarSaaSOnlyScript_test.py
  Utils/test_upload_flow/TestUploadFlowXsoarSaaS/pack_metadata.json
  Utils/test_upload_flow/create_test_branch.py
  Utils/test_upload_flow/verify_bucket.py
Labels: docs-approved

#32017 Add file_name arg to download_file_command
  Packs/MicrosoftGraphFiles/Integrations/MicrosoftGraphFiles/MicrosoftGraphFiles.py
  Packs/MicrosoftGraphFiles/Integrations/MicrosoftGraphFiles/MicrosoftGraphFiles.yml
  Packs/MicrosoftGraphFiles/Integrations/MicrosoftGraphFiles/MicrosoftGraphFiles_test.py
  Packs/MicrosoftGraphFiles/Integrations/MicrosoftGraphFiles/README.md
  Packs/MicrosoftGraphFiles/ReleaseNotes/1_1_22.md
  Packs/MicrosoftGraphFiles/pack_metadata.json
Labels: docs-approved

#31921 Illumio - Fix Invalid IP List HREF
  Packs/Illumio/Playbooks/playbook-Rapid_ransomware_containment_-_Illumio.yml
  Packs/Illumio/ReleaseNotes/1_0_19.md
  Packs/Illumio/doc_files/Rapid_ransomware_containment_-_Illumio.png
  Packs/Illumio/pack_metadata.json
Labels: Contribution, docs-approved, Partner, ready-for-instance-test, Contribution Form Filled, pending-contributor, Partner Support Level, External PR, Security Review, Partner-Approved

#32045 [ASM] - EXPANDR-2883 Playbook trigger suggestion
  Packs/CortexAttackSurfaceManagement/ReleaseNotes/1_7_19.md
  Packs/CortexAttackSurfaceManagement/Triggers/Trigger_-_Cortex_ASM_-_ASM_Alert.json
  Packs/CortexAttackSurfaceManagement/pack_metadata.json
Labels: Contribution, Contribution Form Filled, Community, pending-contributor, Xsoar Support Level, External PR

#32049 Fixing an error of Bcc values was processed as an array of values
  Packs/MicrosoftGraphMail/Classifiers/classifier-Microsoft_Graph_Mail_Mapper.json
  Packs/MicrosoftGraphMail/ReleaseNotes/1_6_2.md
  Packs/MicrosoftGraphMail/pack_metadata.json
Labels: docs-approved

#32051 fixed a bug in upload flow
  Utils/test_upload_flow/verify_bucket.py
Labels: docs-approved

#31893 Inputs groups playbooks improvement xsiam
  Packs/CloudIncidentResponse/Playbooks/playbook-Cloud_IAM_User_Access_Investigation.yml
  Packs/CloudIncidentResponse/Playbooks/playbook-Cloud_IAM_User_Access_Investigation_README.md
  Packs/CloudIncidentResponse/Playbooks/playbook-XCloud_Cryptomining.yml
  Packs/CloudIncidentResponse/Playbooks/playbook-XCloud_Cryptomining_README.md
  Packs/CloudIncidentResponse/ReleaseNotes/1_0_12.md
  Packs/CloudIncidentResponse/pack_metadata.json
  Packs/Core/Playbooks/playbook-Identity_Analytics_-_Alert_Handling.yml
  Packs/Core/Playbooks/playbook-Identity_Analytics_-_Alert_Handling_README.md
  Packs/Core/ReleaseNotes/3_0_6.md
  Packs/Core/pack_metadata.json
Labels: docs-approved

#32057 Local analysis investigation fix
  Packs/CommonPlaybooks/Playbooks/playbook-Enrichment_for_Verdict.yml
  Packs/CommonPlaybooks/Playbooks/playbook-Enrichment_for_Verdict_README.md
  Packs/CommonPlaybooks/ReleaseNotes/2_5_9.md
  Packs/CommonPlaybooks/pack_metadata.json
  Packs/Core/Playbooks/playbook-Local_Analysis_alert_Investigation.yml
  Packs/Core/Playbooks/playbook-Local_Analysis_alert_Investigation_README.md
  Packs/Core/ReleaseNotes/3_0_7.md
  Packs/Core/pack_metadata.json
Labels: docs-approved

#32050 Enhance saas e2e tests
  Tests/tests_e2e/content/xsoar_saas/test_e2e_xsoar_saas.py
Labels: docs-approved

#31908 new commands
  Packs/ThreatConnect/.secrets-ignore
  Packs/ThreatConnect/Integrations/ThreatConnectV3/README.md
  Packs/ThreatConnect/Integrations/ThreatConnectV3/ThreatConnectV3.py
  Packs/ThreatConnect/Integrations/ThreatConnectV3/ThreatConnectV3.yml
  Packs/ThreatConnect/Integrations/ThreatConnectV3/ThreatConnectV3_test.py
  Packs/ThreatConnect/Integrations/ThreatConnectV3/command_examples.txt
  Packs/ThreatConnect/Integrations/ThreatConnectV3/test_data/assets.json
  Packs/ThreatConnect/ReleaseNotes/3_1_0.json
  Packs/ThreatConnect/ReleaseNotes/3_1_0.md
  Packs/ThreatConnect/TestPlaybooks/test-threatConnectV3.yml
  Packs/ThreatConnect/pack_metadata.json
  Tests/conf.json
Labels: docs-approved, ForceMerge

#31979 MicrosoftATPTPB
  Packs/MicrosoftDefenderAdvancedThreatProtection/Integrations/MicrosoftDefenderAdvancedThreatProtection/MicrosoftDefenderAdvancedThreatProtection.py
  Packs/MicrosoftDefenderAdvancedThreatProtection/Integrations/MicrosoftDefenderAdvancedThreatProtection/MicrosoftDefenderAdvancedThreatProtection_test.py
  Packs/MicrosoftDefenderAdvancedThreatProtection/ReleaseNotes/1_16_25.md
  Packs/MicrosoftDefenderAdvancedThreatProtection/pack_metadata.json
Labels: docs-approved

#31816 Remove self references in CommonServerPowershell
  Packs/Base/ReleaseNotes/1_33_17.md
  Packs/Base/Scripts/CommonServerPowerShell/CommonServerPowerShell.Tests.ps1
  Packs/Base/Scripts/CommonServerPowerShell/CommonServerPowerShell.ps1
  Packs/Base/pack_metadata.json
Labels: docs-approved, release-notes-only

#32108 Slack Entitlement Fixes
  Packs/Slack/.secrets-ignore
  Packs/Slack/Integrations/SlackV3/SlackV3.py
  Packs/Slack/Integrations/SlackV3/SlackV3.yml
  Packs/Slack/ReleaseNotes/3_4_2.md
  Packs/Slack/Scripts/SlackBlockBuilder/SlackBlockBuilder.py
  Packs/Slack/Scripts/SlackBlockBuilder/SlackBlockBuilder.yml
  Packs/Slack/Scripts/SlackBlockBuilder/SlackBlockBuilder_test.py
  Packs/Slack/Scripts/SlackBlockBuilder/test_data/blocks_xsup_31982.json
  Packs/Slack/pack_metadata.json
Labels: docs-approved

#31956 Xdr change command results list
  Packs/ApiModules/Scripts/CoreIRApiModule/CoreIRApiModule.py
  Packs/ApiModules/Scripts/CoreIRApiModule/CoreIRApiModule_test.py
  Packs/Core/ReleaseNotes/3_0_8.md
  Packs/Core/pack_metadata.json
  Packs/CortexXDR/ReleaseNotes/6_1_3.md
  Packs/CortexXDR/pack_metadata.json
  Packs/ctf01/ReleaseNotes/1_0_5.md
  Packs/ctf01/pack_metadata.json
Labels: docs-approved

#32113 [Hatching Triage] - remove usage of get pack version
  Packs/HatchingTriage/Integrations/HatchingTriage/HatchingTriage.py
  Packs/HatchingTriage/Integrations/HatchingTriage/HatchingTriage.yml
  Packs/HatchingTriage/ReleaseNotes/1_0_16.md
  Packs/HatchingTriage/pack_metadata.json
Labels: docs-approved

#32117 XSUP-29866- Fixed an issue where the bodyType argument was missing from the SendEmailReply script.
  Packs/EmailCommunication/ReleaseNotes/2_0_20.md
  Packs/EmailCommunication/Scripts/SendEmailReply/SendEmailReply.py
  Packs/EmailCommunication/Scripts/SendEmailReply/SendEmailReply.yml
  Packs/EmailCommunication/pack_metadata.json
Labels: docs-approved

#31951 EXPANDR-5776 - AWS Hierarchy Information
  Packs/AWS-Enrichment-Remediation/Playbooks/AWS_-_Enrichment.yml
  Packs/AWS-Enrichment-Remediation/Playbooks/AWS_-_Enrichment_README.md
  Packs/AWS-Enrichment-Remediation/README.md
  Packs/AWS-Enrichment-Remediation/ReleaseNotes/1_1_13.md
  Packs/AWS-Enrichment-Remediation/Scripts/AWSAccountHierarchy/AWSAccountHierarchy.py
  Packs/AWS-Enrichment-Remediation/Scripts/AWSAccountHierarchy/AWSAccountHierarchy.yml
  Packs/AWS-Enrichment-Remediation/Scripts/AWSAccountHierarchy/AWSAccountHierarchy_test.py
  Packs/AWS-Enrichment-Remediation/Scripts/AWSAccountHierarchy/README.md
  Packs/AWS-Enrichment-Remediation/doc_files/AWSAccountHierarchy.png
  Packs/AWS-Enrichment-Remediation/doc_files/AWS_-_Enrichment.png
  Packs/AWS-Enrichment-Remediation/pack_metadata.json
  Packs/AWS-Organizations/Integrations/AWSOrganizations/AWSOrganizations.yml
  Packs/AWS-Organizations/ReleaseNotes/1_0_1.md
  Packs/AWS-Organizations/pack_metadata.json
Labels: Contribution, docs-approved, Contribution Form Filled, Community, pending-contributor, Xsoar Support Level, External PR, Security Review

#31992 [CrowdStrike Falcon] Additional command to get IOA Rules for custom IOA rule triggered detections.
  Packs/CrowdStrikeFalcon/Integrations/CrowdStrikeFalcon/CrowdStrikeFalcon.py
  Packs/CrowdStrikeFalcon/Integrations/CrowdStrikeFalcon/CrowdStrikeFalcon.yml
  Packs/CrowdStrikeFalcon/Integrations/CrowdStrikeFalcon/README.md
  Packs/CrowdStrikeFalcon/Integrations/CrowdStrikeFalcon/examples.txt
  Packs/CrowdStrikeFalcon/ReleaseNotes/1_12_12.md
  Packs/CrowdStrikeFalcon/pack_metadata.json
Labels: Contribution, Contribution Form Filled, Community, pending-contributor, Xsoar Support Level, External PR

#31913 CSP - IPv4 Regex update
  Packs/AutoFocus/Integrations/FeedAutofocus/FeedAutofocus_test.py
  Packs/Base/.secrets-ignore
  Packs/Base/ReleaseNotes/1_33_18.md
  Packs/Base/Scripts/CommonServerPython/CommonServerPython.py
  Packs/Base/Scripts/CommonServerPython/CommonServerPython_test.py
  Packs/Base/pack_metadata.json
Labels: docs-approved

#31354 Xsup 31117 mimecast
  Packs/Mimecast/Integrations/MimecastV2/MimecastV2.py
  Packs/Mimecast/Integrations/MimecastV2/MimecastV2.yml
  Packs/Mimecast/Integrations/MimecastV2/MimecastV2_test.py
  Packs/Mimecast/Integrations/MimecastV2/README.md
  Packs/Mimecast/ReleaseNotes/2_2_3.md
  Packs/Mimecast/pack_metadata.json
Labels: docs-approved

#31922 EXPANDR-7462 Updating code to check corner cases and re-organizing the code
  Packs/AWS-Enrichment-Remediation/ReleaseNotes/1_1_13.md
  Packs/AWS-Enrichment-Remediation/Scripts/AWSRecreateSG/AWSRecreateSG.py
  Packs/AWS-Enrichment-Remediation/Scripts/AWSRecreateSG/AWSRecreateSG_test.py
  Packs/AWS-Enrichment-Remediation/pack_metadata.json
Labels: Contribution, docs-approved, ready-for-instance-test, Contribution Form Filled, Community, pending-contributor, Xsoar Support Level, External PR

#31856 [ASM] - Expander - Organizational scope searching for EC2
  Packs/CortexAttackSurfaceManagement/Playbooks/Cortex_ASM_-_ASM_Alert.yml
  Packs/CortexAttackSurfaceManagement/Playbooks/Cortex_ASM_-_ASM_Alert_README.md
  Packs/CortexAttackSurfaceManagement/Playbooks/Cortex_ASM_-_AWS_Enrichment.yml
  Packs/CortexAttackSurfaceManagement/Playbooks/Cortex_ASM_-_AWS_Enrichment_README.md
  Packs/CortexAttackSurfaceManagement/Playbooks/Cortex_ASM_-_Enrichment.yml
  Packs/CortexAttackSurfaceManagement/Playbooks/Cortex_ASM_-_Enrichment_README.md
  Packs/CortexAttackSurfaceManagement/ReleaseNotes/1_7_20.md
  Packs/CortexAttackSurfaceManagement/pack_metadata.json
Labels: Contribution, docs-approved, Contribution Form Filled, Community, pending-contributor, Xsoar Support Level, External PR, Security Review

#31748 Xsiam-remote-psexec-lolbin-command-execution-playbook
  Packs/Core/Playbooks/playbook-Remote_PsExec_with_Lolbin_Command_Execution_alert.yml
  Packs/Core/Playbooks/playbook-Remote_PsExec_with_Lolbin_Command_Execution_alert_README.md
  Packs/Core/ReleaseNotes/3_0_9.md
  Packs/Core/doc_files/Remote_PsExec_with_LOLBIN_command_execution_alert.png
  Packs/Core/pack_metadata.json
  Packs/CortexXDR/Playbooks/playbook-Cortex_XDR_-_Remote_PsExec_with_LOLBIN_command_execution_alert.yml
  Packs/CortexXDR/Playbooks/playbook-Cortex_XDR_-_Remote_PsExec_with_LOLBIN_command_execution_alert_README.md
  Packs/CortexXDR/ReleaseNotes/6_1_4.md
  Packs/CortexXDR/pack_metadata.json
Labels: docs-approved

#32102 Fix fetch incidents Blueliv Threat Compass
  Packs/BluelivThreatCompass/Integrations/BluelivThreatCompass/BluelivThreatCompass.py
  Packs/BluelivThreatCompass/Integrations/BluelivThreatCompass/BluelivThreatCompass.yml
  Packs/BluelivThreatCompass/Integrations/BluelivThreatCompass/BluelivThreatCompass_description.md
  Packs/BluelivThreatCompass/ReleaseNotes/1_0_12.md
  Packs/BluelivThreatCompass/pack_metadata.json
Labels: Contribution, docs-approved, Partner, ready-for-instance-test, pending-demo, Contribution Form Filled, pending-contributor, Community Support Level, External PR

#32140 set AWS organizations test to 6.10
  Tests/conf.json
Labels: docs-approved

#32009 AWS SecHub Fix for AWS Filter Limitation
  Packs/AWS-SecurityHub/Integrations/AWSSecurityHubEventCollector/AWSSecurityHubEventCollector.py
  Packs/AWS-SecurityHub/Integrations/AWSSecurityHubEventCollector/AWSSecurityHubEventCollector.yml
  Packs/AWS-SecurityHub/Integrations/AWSSecurityHubEventCollector/AWSSecurityHubEventCollector_test.py
  Packs/AWS-SecurityHub/ReleaseNotes/1_3_26.md
  Packs/AWS-SecurityHub/pack_metadata.json
Labels: docs-approved

#31848 XSIAM TrendMicro IWSS Content Pack CIAC-7506
  Packs/TrendMicroInterScanWebSecurity/.pack-ignore
  Packs/TrendMicroInterScanWebSecurity/.secrets-ignore
  Packs/TrendMicroInterScanWebSecurity/ModelingRules/TrendMicroIWSS/TrendMicroIWSS.xif
  Packs/TrendMicroInterScanWebSecurity/ModelingRules/TrendMicroIWSS/TrendMicroIWSS.yml
  Packs/TrendMicroInterScanWebSecurity/ModelingRules/TrendMicroIWSS/TrendMicroIWSS_schema.json
  Packs/TrendMicroInterScanWebSecurity/ParsingRules/TrendMicroIWSS/TrendMicroIWSS.xif
  Packs/TrendMicroInterScanWebSecurity/ParsingRules/TrendMicroIWSS/TrendMicroIWSS.yml
  Packs/TrendMicroInterScanWebSecurity/README.md
  Packs/TrendMicroInterScanWebSecurity/pack_metadata.json
Labels: docs-approved

#32150 [Crowdstrike Falcon] Update CrowdStrikeFalcon.py - Fixed the function to retrieve correct ioa rules correctly.
  Packs/CrowdStrikeFalcon/Integrations/CrowdStrikeFalcon/CrowdStrikeFalcon.py
  Packs/CrowdStrikeFalcon/ReleaseNotes/1_12_13.md
  Packs/CrowdStrikeFalcon/pack_metadata.json
Labels: Contribution, Contribution Form Filled, Community, Xsoar Support Level, External PR

#31991 [ASM] EXPANDR-5776: Add AWS Hierarchy Info to Main Playbook
  Packs/CortexAttackSurfaceManagement/Playbooks/Cortex_ASM_-_AWS_Enrichment.yml
  Packs/CortexAttackSurfaceManagement/Playbooks/Cortex_ASM_-_AWS_Enrichment_README.md
  Packs/CortexAttackSurfaceManagement/ReleaseNotes/1_7_21.md
  Packs/CortexAttackSurfaceManagement/doc_files/Cortex_ASM_-_AWS_Enrichment.png
  Packs/CortexAttackSurfaceManagement/pack_metadata.json
Labels: Contribution, docs-approved, ready-for-instance-test, Contribution Form Filled, Community, pending-contributor, Xsoar Support Level, External PR, Security Review

#31837 Symantec EDR enhancement
  Packs/SymantecEDR/Classifiers/classifier-SymantecEDR_Event_-_Incoming_Mapper.json
  Packs/SymantecEDR/IncidentFields/incidentfield-SymantecEDR_Antivirus.json
  Packs/SymantecEDR/IncidentFields/incidentfield-SymantecEDR_Event_Log_Name.json
  Packs/SymantecEDR/IncidentFields/incidentfield-SymantecEDR_Event_Type_ID.json
  Packs/SymantecEDR/IncidentFields/incidentfield-SymantecEDR_Intrusion.json
  Packs/SymantecEDR/IncidentFields/incidentfield-SymantecEDR_Scan.json
  Packs/SymantecEDR/IncidentFields/incidentfield-SymantecEDR_Threat.json
  Packs/SymantecEDR/IncidentTypes/incidenttype-SymantecEDR_event.json
  Packs/SymantecEDR/Integrations/SymantecEDR/README.md
  Packs/SymantecEDR/Integrations/SymantecEDR/SymantecEDR.py
  Packs/SymantecEDR/Integrations/SymantecEDR/SymantecEDR.yml
  Packs/SymantecEDR/Integrations/SymantecEDR/SymantecEDR_test.py
  Packs/SymantecEDR/Layouts/layoutscontainer-SymantecEDR_Event_layout.json
  Packs/SymantecEDR/ReleaseNotes/2_0_0.md
  Packs/SymantecEDR/pack_metadata.json
Labels: Contribution, docs-approved, ready-for-instance-test, post-demo, Contribution Form Filled, pending-contributor, Xsoar Support Level, External PR, Security Review, TIM Review

#32134 [Common Scripts] Make MITRE ATT&CK optional dependency
  Packs/CommonScripts/pack_metadata.json
Labels: docs-approved

#32147 Packs/Reco: update description and readme
  Packs/Reco/README.md
  Packs/Reco/pack_metadata.json
Labels: Contribution, docs-approved, Partner, Contribution Form Filled, Partner Support Level, External PR, Partner-Approved

#32162 [saas-e2e] - print incident metadata each iteration
  Tests/tests_e2e/content/xsoar_saas/test_e2e_xsoar_saas.py
Labels: docs-approved

#31257 Add marketplaces to tests in Tests/conf.json
  Tests/conf.json
  Tests/scripts/collect_tests/collect_tests.py
  Tests/scripts/collect_tests/constants.py
  Tests/scripts/collect_tests/exceptions.py
  Tests/scripts/collect_tests/test_conf.py
  Tests/scripts/collect_tests/utils.py
  Tests/scripts/infrastructure_tests/test_collect_tests.py
  Tests/scripts/infrastructure_tests/tests_data/collect_tests/conf marketplaces/Packs/myPack/.pack_ignore
  Tests/scripts/infrastructure_tests/tests_data/collect_tests/conf marketplaces/Packs/myPack/.secrets-ignore
  Tests/scripts/infrastructure_tests/tests_data/collect_tests/conf marketplaces/Packs/myPack/TestPlaybooks/myTestPlaybook_both.yml
  Tests/scripts/infrastructure_tests/tests_data/collect_tests/conf marketplaces/Packs/myPack/TestPlaybooks/myTestPlaybook_both2.yml
  Tests/scripts/infrastructure_tests/tests_data/collect_tests/conf marketplaces/Packs/myPack/TestPlaybooks/myTestPlaybook_on_prem.yml
  Tests/scripts/infrastructure_tests/tests_data/collect_tests/conf marketplaces/Packs/myPack/TestPlaybooks/myTestPlaybook_saas.yml
  Tests/scripts/infrastructure_tests/tests_data/collect_tests/conf marketplaces/Packs/myPack/TestPlaybooks/myTestPlaybook_two_entries.yml
  Tests/scripts/infrastructure_tests/tests_data/collect_tests/conf marketplaces/Packs/myPack/pack_metadata.json
  Tests/scripts/infrastructure_tests/tests_data/collect_tests/conf marketplaces/Tests/conf.json
  Tests/scripts/infrastructure_tests/tests_data/collect_tests/conf marketplaces/Tests/id_set.json
Labels: docs-approved

#32167 [Pre-Commit] Run pre-commit in community PR
  .github/workflows/pre-commit.yml
Labels: docs-approved

#31678 Phishing Campaign - Add/Remove incident
  Packs/Campaign/IncidentFields/incidentfield-Actions_On_Campaign_Incidents.json
  Packs/Campaign/Playbooks/Detect_&_Manage_Phishing_Campaigns.yml
  Packs/Campaign/ReleaseNotes/3_4_0.json
  Packs/Campaign/ReleaseNotes/3_4_0.md
  Packs/Campaign/Scripts/GetCampaignIncidentsInfo/GetCampaignIncidentsInfo.py
  Packs/Campaign/Scripts/GetCampaignIncidentsInfo/GetCampaignIncidentsInfo.yml
  Packs/Campaign/Scripts/GetCampaignIndicatorsByIncidentId/GetCampaignIndicatorsByIncidentId.py
  Packs/Campaign/Scripts/GetCampaignIndicatorsByIncidentId/GetCampaignIndicatorsByIncidentId.yml
  Packs/Campaign/Scripts/GetCampaignIndicatorsByIncidentId/GetCampaignIndicatorsByIncidentId_test.py
  Packs/Campaign/Scripts/PerformActionOnCampaignIncidents/PerformActionOnCampaignIncidents.py
  Packs/Campaign/Scripts/PerformActionOnCampaignIncidents/PerformActionOnCampaignIncidents.yml
  Packs/Campaign/Scripts/PerformActionOnCampaignIncidents/PerformActionOnCampaignIncidents_test.py
  Packs/Campaign/Scripts/ShowCampaignIncidentsOwners/ShowCampaignIncidentsOwners.py
  Packs/Campaign/Scripts/ShowCampaignIncidentsOwners/ShowCampaignIncidentsOwners.yml
  Packs/Campaign/Scripts/ShowCampaignIncidentsOwners/ShowCampaignIncidentsOwners_test.py
  Packs/Campaign/Scripts/ShowCampaignLastIncidentOccurred/ShowCampaignLastIncidentOccurred.py
  Packs/Campaign/Scripts/ShowCampaignLastIncidentOccurred/ShowCampaignLastIncidentOccurred.yml
  Packs/Campaign/Scripts/ShowCampaignLastIncidentOccurred/ShowCampaignLastIncidentOccurred_test.py
  Packs/Campaign/Scripts/ShowCampaignRecipients/ShowCampaignRecipients.py
  Packs/Campaign/Scripts/ShowCampaignRecipients/ShowCampaignRecipients.yml
  Packs/Campaign/Scripts/ShowCampaignRecipients/ShowCampaignRecipients_test.py
  Packs/Campaign/Scripts/ShowCampaignSenders/ShowCampaignSenders.py
  Packs/Campaign/Scripts/ShowCampaignSenders/ShowCampaignSenders.yml
  Packs/Campaign/Scripts/ShowCampaignSenders/ShowCampaignSenders_test.py
  Packs/Campaign/Scripts/ShowCampaignSimilarityRange/ShowCampaignSimilarityRange.py
  Packs/Campaign/Scripts/ShowCampaignSimilarityRange/ShowCampaignSimilarityRange.yml
  Packs/Campaign/TestPlaybooks/Detect_&_Manage_Phishing_Campaigns_-_Test.yml
  Packs/Campaign/pack_metadata.json
  Tests/conf.json
Labels: docs-approved, ForceMerge

#31973 replace packs nightly
  Packs/MicrosoftExchangeOnPremise/TestPlaybooks/playbook-EWSv2_empty_attachment_test.yml
  Tests/conf.json
Labels: docs-approved

#32021 add CIAC tickets to conf
  Tests/conf.json
Labels: docs-approved

#32182 mock requests for docker image UT
  Packs/CommonScripts/Scripts/GetDockerImageLatestTag/GetDockerImageLatestTag_test.py
Labels: docs-approved

#32170 [Microsoft Defender for Cloud Apps Event Collector] Fix the Client
  Packs/MicrosoftCloudAppSecurity/Integrations/MicrosoftDefenderEventCollector/MicrosoftDefenderEventCollector.py
  Packs/MicrosoftCloudAppSecurity/Integrations/MicrosoftDefenderEventCollector/MicrosoftDefenderEventCollector.yml
  Packs/MicrosoftCloudAppSecurity/Integrations/MicrosoftDefenderEventCollector/MicrosoftDefenderEventCollector_description.md
  Packs/MicrosoftCloudAppSecurity/ReleaseNotes/2_1_54.md
  Packs/MicrosoftCloudAppSecurity/pack_metadata.json
Labels: docs-approved

#32199 Skipped end 2 end tests
  .gitlab/ci/.gitlab-ci.on-push.yml
  .gitlab/ci/.gitlab-ci.sdk-nightly.yml
Labels: docs-approved

#32201 Alibaba ActionTrail CorrelationRules Fix
  Packs/AlibabaActionTrail/CorrelationRules/AlibabaActionTrail_Correlation.yml
  Packs/AlibabaActionTrail/ReleaseNotes/1_0_22.md
  Packs/AlibabaActionTrail/pack_metadata.json
Labels: docs-approved

#32215 Added dependency on Microsoft exchange online pack
  Packs/Phishing/pack_metadata.json
Labels: docs-approved

#32169 [dev-task] Reduce length of upload slack message
  Tests/scripts/gitlab_slack_notifier.py
Labels: docs-approved

#32218 Update blocked indicator field to be searchable
  Packs/CommonTypes/IndicatorFields/indicatorfield-Blocked.json
  Packs/CommonTypes/ReleaseNotes/3_3_99.md
  Packs/CommonTypes/pack_metadata.json
Labels: docs-approved

#32203 Override dataset fields fix - CheckPoint FW
  Packs/CheckpointFirewall/ModelingRules/CheckpointFirewall_1_3/CheckpointFirewall_1_3.xif
  Packs/CheckpointFirewall/ReleaseNotes/2_3_20.md
  Packs/CheckpointFirewall/pack_metadata.json
Labels: docs-approved

#31943 Default playbook 8.2 - multiple fixes and performance improvements
  Packs/DefaultPlaybook/Playbooks/Default_8_2.yml
  Packs/DefaultPlaybook/Playbooks/Default_8_2_README.md
  Packs/DefaultPlaybook/ReleaseNotes/2_0_6.md
  Packs/DefaultPlaybook/doc_files/Default_8_2.png
  Packs/DefaultPlaybook/pack_metadata.json
Labels: docs-approved, release-notes-only

#32098 wait-in-line: collect statics with Slack
  Tests/scripts/infrastructure_tests/lock_cloud_machines_test.py
  Tests/scripts/lock_cloud_machines.py
Labels: docs-approved

#32204 Override dataset fields fix2 - MS Windows Events
  Packs/MicrosoftWindowsEvents/ModelingRules/MicrosoftWindowsEvents_1_3/MicrosoftWindowsEvents_1_3.xif
  Packs/MicrosoftWindowsEvents/ReleaseNotes/1_1_6.md
  Packs/MicrosoftWindowsEvents/pack_metadata.json
Labels: docs-approved

#32144 Calculate Severity - Performance improvements for 3 playbooks
  Packs/CommonPlaybooks/Playbooks/playbook-Calculate_Severity_-_Generic_v2.yml
  Packs/CommonPlaybooks/Playbooks/playbook-Calculate_Severity_-_Generic_v2_README.md
  Packs/CommonPlaybooks/Playbooks/playbook-Calculate_Severity_-_Standard.yml
  Packs/CommonPlaybooks/Playbooks/playbook-Calculate_Severity_-_Standard_README.md
  Packs/CommonPlaybooks/Playbooks/playbook-Calculate_Severity_By_Highest_DBotScore_6_0.yml
  Packs/CommonPlaybooks/Playbooks/playbook-Calculate_Severity_By_Highest_DBotScore_6_0_README.md
  Packs/CommonPlaybooks/ReleaseNotes/2_6_0.json
  Packs/CommonPlaybooks/ReleaseNotes/2_6_0.md
  Packs/CommonPlaybooks/TestPlaybooks/playbook-Calculate_Severity_-_Generic_v2_-_Test.yml
  Packs/CommonPlaybooks/TestPlaybooks/playbook-Calculate_Severity_-_Standard_-_Test.yml
  Packs/CommonPlaybooks/doc_files/Calculate_Severity_-_Standard.png
  Packs/CommonPlaybooks/doc_files/Calculate_Severity_By_Highest_DBotScore.png
  Packs/CommonPlaybooks/pack_metadata.json
  Tests/conf.json
Labels: docs-approved

#32224 add `freeze_time` on time-related UT
  Packs/Base/Scripts/CommonServerPython/CommonServerPython_test.py
Labels: docs-approved

#32235 update-demisto-sdk-version - git add post pre-commit
  .github/workflows/update-demisto-sdk-version.yml
Labels: docs-approved

#32232 Move Slack Token/Channel to Local method
  Tests/scripts/infrastructure_tests/lock_cloud_machines_test.py
  Tests/scripts/lock_cloud_machines.py
Labels: docs-approved

#32110 Extend CarbonBlackEnterpriseEDR to support new API v7 methods.
  Packs/CarbonBlackEnterpriseEDR/CONTRIBUTORS.json
  Packs/CarbonBlackEnterpriseEDR/Integrations/CarbonBlackEnterpriseEDR/CarbonBlackEnterpriseEDR.py
  Packs/CarbonBlackEnterpriseEDR/Integrations/CarbonBlackEnterpriseEDR/CarbonBlackEnterpriseEDR.yml
  Packs/CarbonBlackEnterpriseEDR/Integrations/CarbonBlackEnterpriseEDR/CarbonBlackEnterpriseEDR_test.py
  Packs/CarbonBlackEnterpriseEDR/Integrations/CarbonBlackEnterpriseEDR/README.md
  Packs/CarbonBlackEnterpriseEDR/Integrations/CarbonBlackEnterpriseEDR/command_examples.txt
  Packs/CarbonBlackEnterpriseEDR/ReleaseNotes/1_1_33.md
  Packs/CarbonBlackEnterpriseEDR/pack_metadata.json
Labels: Contribution, docs-approved, ready-for-instance-test, pending-demo, Contribution Form Filled, Community, pending-contributor, Xsoar Support Level, External PR

#32241 Update dockerimage in DBotUpdateLogoURLPhishing.yml
  Packs/CommonScripts/ReleaseNotes/1_13_20.md
  Packs/CommonScripts/Scripts/DBotUpdateLogoURLPhishing/DBotUpdateLogoURLPhishing.py
  Packs/CommonScripts/Scripts/DBotUpdateLogoURLPhishing/DBotUpdateLogoURLPhishing.yml
  Packs/CommonScripts/pack_metadata.json
Labels: docs-approved

#32238 [malwarebytes-254] Changing Integration Name from 'Malwarebytes' to 'ThreatDown' GI-1379
  Packs/Malwarebytes/Author_image.png
  Packs/Malwarebytes/Integrations/Malwarebytes/Malwarebytes_dark.svg
  Packs/Malwarebytes/Integrations/Malwarebytes/Malwarebytes_description.md
  Packs/Malwarebytes/Integrations/Malwarebytes/Malwarebytes_image.png
  Packs/Malwarebytes/Integrations/Malwarebytes/Malwarebytes_light.svg
  Packs/Malwarebytes/Integrations/Malwarebytes/README.md
  Packs/Malwarebytes/README.md
  Packs/Malwarebytes/ReleaseNotes/1_1_15.md
  Packs/Malwarebytes/pack_metadata.json
Labels: Contribution, docs-approved, Partner, ready-for-instance-test, Contribution Form Filled, Partner Support Level, External PR, Partner-Approved

#32239 Linux events collection par diff fix
  Packs/LinuxEventsCollection/ParsingRules/LinuxEventsCollectionParsingRules/LinuxEventsCollectionParsingRules.xif
  Packs/LinuxEventsCollection/ReleaseNotes/1_0_8.md
  Packs/LinuxEventsCollection/pack_metadata.json
Labels: docs-approved

#32227 Fix parsing logic cisco catalyst
  Packs/CiscoCatalyst/ParsingRules/CiscoCatalyst/CiscoCatalyst.xif
  Packs/CiscoCatalyst/ReleaseNotes/1_0_5.md
  Packs/CiscoCatalyst/pack_metadata.json
Labels: docs-approved

#32217 30281 fix msgraph updated
  Packs/MicrosoftGraphDeviceManagement/Integrations/MicrosoftGraphDeviceManagement/MicrosoftGraphDeviceManagement.py
  Packs/MicrosoftGraphDeviceManagement/Integrations/MicrosoftGraphDeviceManagement/MicrosoftGraphDeviceManagement.yml
  Packs/MicrosoftGraphDeviceManagement/Integrations/MicrosoftGraphDeviceManagement/MicrosoftGraphDeviceManagement_test.py
  Packs/MicrosoftGraphDeviceManagement/Integrations/MicrosoftGraphDeviceManagement/README.md
  Packs/MicrosoftGraphDeviceManagement/ReleaseNotes/1_1_21.md
  Packs/MicrosoftGraphDeviceManagement/pack_metadata.json
Labels: docs-approved

#32229 Fix parsing logic cisco isr
  Packs/CiscoISR/ParsingRules/CiscoISR/CiscoISR.xif
  Packs/CiscoISR/ReleaseNotes/1_0_3.md
  Packs/CiscoISR/pack_metadata.json
Labels: docs-approved

#32060 Remove the styling and color from EWS V2
  Packs/EmailCommunication/ReleaseNotes/2_0_21.md
  Packs/EmailCommunication/Scripts/DisplayEmailHtmlThread/DisplayEmailHtmlThread.py
  Packs/EmailCommunication/Scripts/DisplayEmailHtmlThread/DisplayEmailHtmlThread.yml
  Packs/EmailCommunication/Scripts/DisplayEmailHtmlThread/DisplayEmailHtmlThread_test.py
  Packs/EmailCommunication/Scripts/DisplayEmailHtmlThread/test_data/email_thread_with_html_styling.json
  Packs/EmailCommunication/Scripts/DisplayEmailHtmlThread/test_data/good_result.txt
  Packs/EmailCommunication/pack_metadata.json
Labels: docs-approved

#32010 XSIAM SecureAuth Identity Platform Mapping CIAC-9150
  Packs/SecureAuthIdentityPlatform/.pack-ignore
  Packs/SecureAuthIdentityPlatform/.secrets-ignore
  Packs/SecureAuthIdentityPlatform/ModelingRules/SecureAuthIdentityPlatform/SecureAuthIdentityPlatform.xif
  Packs/SecureAuthIdentityPlatform/ModelingRules/SecureAuthIdentityPlatform/SecureAuthIdentityPlatform.yml
  Packs/SecureAuthIdentityPlatform/ModelingRules/SecureAuthIdentityPlatform/SecureAuthIdentityPlatform_schema.json
  Packs/SecureAuthIdentityPlatform/ParsingRules/SecureAuthIdentityPlatform/SecureAuthIdentityPlatform.xif
  Packs/SecureAuthIdentityPlatform/ParsingRules/SecureAuthIdentityPlatform/SecureAuthIdentityPlatform.yml
  Packs/SecureAuthIdentityPlatform/README.md
  Packs/SecureAuthIdentityPlatform/pack_metadata.json
Labels: docs-approved

#31933 Chronicle - [Google Chronicle Backstory]
  Packs/GoogleChronicleBackstory/.pack-ignore
  Packs/GoogleChronicleBackstory/.secrets-ignore
  Packs/GoogleChronicleBackstory/Integrations/GoogleChronicleBackstory/GoogleChronicleBackstory.py
  Packs/GoogleChronicleBackstory/Integrations/GoogleChronicleBackstory/GoogleChronicleBackstory.yml
  Packs/GoogleChronicleBackstory/Integrations/GoogleChronicleBackstory/GoogleChronicleBackstory_test.py
  Packs/GoogleChronicleBackstory/Integrations/GoogleChronicleBackstory/README.md
  Packs/GoogleChronicleBackstory/ReleaseNotes/3_1_0.md
  Packs/GoogleChronicleBackstory/pack_metadata.json
Labels: Contribution, Partner, ready-for-instance-test, pending-demo, Contribution Form Filled, pending-contributor, Partner Support Level, External PR, Partner-Approved

#32032 [KennaV2] Enhancement 2 New Commands
  Packs/Kenna/Integrations/KennaV2/CONTRIBUTORS.json
  Packs/Kenna/Integrations/KennaV2/KennaV2.py
  Packs/Kenna/Integrations/KennaV2/KennaV2.yml
  Packs/Kenna/Integrations/KennaV2/KennaV2_description.md
  Packs/Kenna/Integrations/KennaV2/KennaV2_test.py
  Packs/Kenna/Integrations/KennaV2/README.md
  Packs/Kenna/Integrations/KennaV2/command_examples.txt
  Packs/Kenna/Integrations/KennaV2/test_data/assets_response.json
  Packs/Kenna/Playbooks/playbook-Kenna_-_Vulnerability_Handling.yml
  Packs/Kenna/Playbooks/playbook-Kenna_-_Vulnerability_Handling_README.md
  Packs/Kenna/ReleaseNotes/1_1_20.md
  Packs/Kenna/TestPlaybooks/playbook-Kenna_Test.yml
  Packs/Kenna/doc_files/Kenna_-_Search_and_Handle_Asset_Vulnerabilities.png
  Packs/Kenna/pack_metadata.json
Labels: Contribution, docs-approved, ready-for-instance-test, pending-demo, Contribution Form Filled, Community, pending-contributor, Xsoar Support Level, External PR

#32219 Audit alert v3 indicators enrichment fix
  Packs/PrismaCloudCompute/Playbooks/Prisma_Cloud_Compute_-_Audit_Alert_Enrichment.yml
  Packs/PrismaCloudCompute/Playbooks/Prisma_Cloud_Compute_-_Audit_Alert_Vulnerabilities_Enrichment.yml
  Packs/PrismaCloudCompute/Playbooks/Prisma_Cloud_Compute_-_Audit_Alert_Vulnerabilities_Enrichment_README.md
  Packs/PrismaCloudCompute/Playbooks/Prisma_Cloud_Compute_-_Audit_Alert_v3.yml
  Packs/PrismaCloudCompute/Playbooks/Prisma_Cloud_Compute_-_Audit_Alert_v3_README.md
  Packs/PrismaCloudCompute/Playbooks/Prisma_Cloud_Compute_-_Get_Container_Events.yml
  Packs/PrismaCloudCompute/Playbooks/Prisma_Cloud_Compute_-_Get_Container_Events_README.md
  Packs/PrismaCloudCompute/README.md
  Packs/PrismaCloudCompute/ReleaseNotes/1_5_1.md
  Packs/PrismaCloudCompute/doc_files/Prisma_Cloud_Compute_-_Audit_Alert_Vulnerabilities_Enrichment.png
  Packs/PrismaCloudCompute/doc_files/Prisma_Cloud_Compute_-_Audit_Alert_v3.png
  Packs/PrismaCloudCompute/doc_files/Prisma_Cloud_Compute_-_Get_Container_Events.png
  Packs/PrismaCloudCompute/pack_metadata.json
Labels: docs-approved

#32243 Kiteworks par diff fix
  Packs/Kiteworks/ParsingRules/Kiteworks/Kiteworks.xif
  Packs/Kiteworks/ReleaseNotes/1_0_1.md
  Packs/Kiteworks/pack_metadata.json
Labels: docs-approved

#32252 Juniper srx par diff fix
  Packs/JuniperSRX/ParsingRules/JuniperSRX/JuniperSRX.xif
  Packs/JuniperSRX/ReleaseNotes/1_0_10.md
  Packs/JuniperSRX/pack_metadata.json
Labels: docs-approved

#32265 Devcontainer (and codespaces) maintanance
  .devcontainer/createCommand.sh
  .devcontainer/devcontainer.json
  .devcontainer/settings.json
Labels: ForceMerge

#32263 Change script to base script in server nodes
  Tests/Marketplace/server_content_items.json
Labels: docs-approved

#32129 Identity analytics alert handling improvement
  Packs/Core/Playbooks/playbook-Identity_Analytics_-_Alert_Handling.yml
  Packs/Core/Playbooks/playbook-Identity_Analytics_-_Alert_Handling_README.md
  Packs/Core/ReleaseNotes/3_0_10.md
  Packs/Core/pack_metadata.json
Labels: docs-approved

#32255 Change extraction settings to none
  Packs/IntegrationsAndIncidentsHealthCheck/IncidentTypes/incidenttype-IntegrationsandIncidentsHealthCheck.json
  Packs/IntegrationsAndIncidentsHealthCheck/ReleaseNotes/1_3_19.md
  Packs/IntegrationsAndIncidentsHealthCheck/pack_metadata.json
Labels: docs-approved

#32266 Brocadeswitch srx par diff fix
  Packs/BrocadeSwitch/ParsingRules/BrocadeSwitch/BrocadeSwitch.xif
  Packs/BrocadeSwitch/ReleaseNotes/1_0_10.md
  Packs/BrocadeSwitch/pack_metadata.json
Labels: docs-approved

#31978 Feature/add-xpanse-integration-command-get-external-websites
  Packs/CortexXpanse/Integrations/CortexXpanse/CortexXpanse.py
  Packs/CortexXpanse/Integrations/CortexXpanse/CortexXpanse.yml
  Packs/CortexXpanse/Integrations/CortexXpanse/CortexXpanse_test.py
  Packs/CortexXpanse/Integrations/CortexXpanse/README.md
  Packs/CortexXpanse/Integrations/CortexXpanse/command_examples
  Packs/CortexXpanse/Integrations/CortexXpanse/test_data/expected_results.py
  Packs/CortexXpanse/Integrations/CortexXpanse/test_data/raw_response.py
  Packs/CortexXpanse/ReleaseNotes/1_0_17.md
  Packs/CortexXpanse/pack_metadata.json
Labels: docs-approved

#32271 Bluecat am srx par diff fix
  Packs/BluecatAddressManager/ParsingRules/BluecatAddressManager_1_3/BluecatAddressManager_1_3.xif
  Packs/BluecatAddressManager/ReleaseNotes/1_1_12.md
  Packs/BluecatAddressManager/pack_metadata.json
Labels: docs-approved

#32205 Add playbook trigger for remote psexec lolbin command execution playbook
  Packs/Core/ReleaseNotes/3_0_10.md
  Packs/Core/ReleaseNotes/3_0_11.md
  Packs/Core/Triggers/Trigger_-_Remote_PsExec_with_LOLBIN_command_execution_alert.json
  Packs/Core/pack_metadata.json
Labels: docs-approved

#32236 add deprecated TPB to skipped tests list
  Tests/conf.json
Labels: docs-approved

#32267 update docker image
  Packs/PhishingURL/ReleaseNotes/1_1_8.md
  Packs/PhishingURL/Scripts/DBotPredictURLPhishing/DBotPredictURLPhishing.yml
  Packs/PhishingURL/pack_metadata.json
Labels: docs-approved, ForceMerge

#32143 XSUP-30439: TAXII 2 Feed Fix Fetch Indicators V2
  Packs/ApiModules/Scripts/TAXII2ApiModule/TAXII2ApiModule.py
  Packs/FeedDHS/ReleaseNotes/2_0_29.md
  Packs/FeedDHS/pack_metadata.json
  Packs/FeedMitreAttackv2/ReleaseNotes/1_1_27.md
  Packs/FeedMitreAttackv2/pack_metadata.json
  Packs/FeedTAXII/Integrations/FeedTAXII2/FeedTAXII2.py
  Packs/FeedTAXII/Integrations/FeedTAXII2/FeedTAXII2.yml
  Packs/FeedTAXII/Integrations/FeedTAXII2/FeedTAXII2_test.py
  Packs/FeedTAXII/ReleaseNotes/1_2_3.md
  Packs/FeedTAXII/pack_metadata.json
Labels: docs-approved

#31904 Fix for search incidents v2 xsiam
  Packs/CommonPlaybooks/Playbooks/playbook-Enrichment_for_Verdict.yml
  Packs/CommonPlaybooks/Playbooks/playbook-Enrichment_for_Verdict_README.md
  Packs/CommonPlaybooks/ReleaseNotes/2_6_1.md
  Packs/CommonPlaybooks/pack_metadata.json
  Packs/Core/Playbooks/playbook-Get_entity_alerts_by_MITRE_tactics.yml
  Packs/Core/Playbooks/playbook-Get_entity_alerts_by_MITRE_tactics_README.md
  Packs/Core/ReleaseNotes/3_0_12.md
  Packs/Core/pack_metadata.json
Labels: docs-approved

#32278 Barracuda cf srx par diff fix
  Packs/Barracuda_Cloudgen_Firewall/ParsingRules/Barracuda_Cloudgen_FirewallParsingRules/Barracuda_Cloudgen_FirewallParsingRules.xif
  Packs/Barracuda_Cloudgen_Firewall/ReleaseNotes/1_0_2.md
  Packs/Barracuda_Cloudgen_Firewall/pack_metadata.json
Labels: docs-approved

#32270 Fix Long Sleep w/Int
  Packs/CommonScripts/ReleaseNotes/1_13_22.md
  Packs/CommonScripts/Scripts/Sleep/Sleep.js
  Packs/CommonScripts/pack_metadata.json
Labels: docs-approved

#32277 URL IOC not being sent to XDR
  Packs/CortexXDR/Integrations/XDR_iocs/XDR_iocs.py
  Packs/CortexXDR/Integrations/XDR_iocs/XDR_iocs.yml
  Packs/CortexXDR/Integrations/XDR_iocs/XDR_iocs_test.py
  Packs/CortexXDR/ReleaseNotes/6_1_5.md
  Packs/CortexXDR/pack_metadata.json
Labels: docs-approved
