Repository demisto/content, pull requests merged in 2024-12, with the labels that each got.

#37471 commit files - akamai increase rate
  Packs/Akamai_SIEM/Integrations/Akamai_SIEM/Akamai_SIEM.py
  Packs/Akamai_SIEM/Integrations/Akamai_SIEM/Akamai_SIEM.yml
  Packs/Akamai_SIEM/Integrations/Akamai_SIEM/Akamai_SIEM_test.py
  Packs/Akamai_SIEM/Integrations/Akamai_SIEM/README.md
  Packs/Akamai_SIEM/ReleaseNotes/1_1_9.md
  Packs/Akamai_SIEM/pack_metadata.json
Labels: ForceMerge

#37263 Bug fix/XSUP-43864/FireEye NX fixed fetch incidents
  Packs/FireEyeNX/Integrations/FireEyeNX/FireEyeNX.py
  Packs/FireEyeNX/Integrations/FireEyeNX/FireEyeNX.yml
  Packs/FireEyeNX/Integrations/FireEyeNX/FireEyeNX_test.py
  Packs/FireEyeNX/ReleaseNotes/1_1_35.md
  Packs/FireEyeNX/pack_metadata.json
Labels: docs-approved, release-notes-only, ForceMerge

#37340 Add Padding
  Packs/ApiModules/README.md
  Packs/ApiModules/ReleaseNotes/2_2_30.md
  Packs/ApiModules/Scripts/MicrosoftGraphMailApiModule/MicrosoftGraphMailApiModule.py
  Packs/ApiModules/pack_metadata.json
  Packs/Base/ReleaseNotes/1_35_6.md
  Packs/Base/Scripts/CommonServerPython/CommonServerPython.py
  Packs/Base/Scripts/CommonServerPython/CommonServerPython_test.py
  Packs/Base/pack_metadata.json
  Packs/Gmail/Integrations/Gmail/Gmail.py
  Packs/Gmail/ReleaseNotes/1_3_29.md
  Packs/Gmail/pack_metadata.json
  Packs/GmailSingleUser/Integrations/GmailSingleUser/GmailSingleUser.py
  Packs/GmailSingleUser/ReleaseNotes/1_4_9.md
  Packs/GmailSingleUser/pack_metadata.json
  Packs/MicrosoftExchangeOnPremise/Integrations/EWSv2/EWSv2.py
  Packs/MicrosoftExchangeOnPremise/ReleaseNotes/2_1_16.md
  Packs/MicrosoftExchangeOnPremise/pack_metadata.json
  Packs/MicrosoftExchangeOnline/Integrations/EWSO365/EWSO365.py
  Packs/MicrosoftExchangeOnline/ReleaseNotes/1_5_18.md
  Packs/MicrosoftExchangeOnline/pack_metadata.json
  Packs/MicrosoftGraphMail/ReleaseNotes/1_6_20.md
  Packs/MicrosoftGraphMail/pack_metadata.json
Labels: docs-approved, ForceMerge

#37015 CortexXDRIR updated the mirror in time range
  Packs/CortexXDR/Integrations/CortexXDRIR/CortexXDRIR.py
  Packs/CortexXDR/Integrations/CortexXDRIR/CortexXDRIR_test.py
  Packs/CortexXDR/ReleaseNotes/6_1_94.md
  Packs/CortexXDR/pack_metadata.json
Labels: docs-approved, ForceMerge

#37466 Edl port bug
  Packs/EDL/Integrations/EDL/EDL.yml
  Packs/EDL/ReleaseNotes/3_3_5.md
  Packs/EDL/pack_metadata.json
Labels: docs-approved, ForceMerge

#36853 Mongo DB Atlas Event Collector
  Packs/MongoDBAtlas/.pack-ignore
  Packs/MongoDBAtlas/.secrets-ignore
  Packs/MongoDBAtlas/Author_image.png
  Packs/MongoDBAtlas/Integrations/MongoDBAtlasEventCollector/MongoDBAtlasEventCollector.py
  Packs/MongoDBAtlas/Integrations/MongoDBAtlasEventCollector/MongoDBAtlasEventCollector.yml
  Packs/MongoDBAtlas/Integrations/MongoDBAtlasEventCollector/MongoDBAtlasEventCollector_description.md
  Packs/MongoDBAtlas/Integrations/MongoDBAtlasEventCollector/MongoDBAtlasEventCollector_image.png
  Packs/MongoDBAtlas/Integrations/MongoDBAtlasEventCollector/MongoDBAtlasEventCollector_test.py
  Packs/MongoDBAtlas/Integrations/MongoDBAtlasEventCollector/README.md
  Packs/MongoDBAtlas/Integrations/MongoDBAtlasEventCollector/command_examples
  Packs/MongoDBAtlas/Integrations/MongoDBAtlasEventCollector/test_data/raw_alerts_page_1.json
  Packs/MongoDBAtlas/Integrations/MongoDBAtlasEventCollector/test_data/raw_alerts_page_1_with_more_alerts.json
  Packs/MongoDBAtlas/Integrations/MongoDBAtlasEventCollector/test_data/raw_alerts_page_2.json
  Packs/MongoDBAtlas/Integrations/MongoDBAtlasEventCollector/test_data/raw_events_page_1.json
  Packs/MongoDBAtlas/Integrations/MongoDBAtlasEventCollector/test_data/raw_events_page_2.json
  Packs/MongoDBAtlas/Integrations/MongoDBAtlasEventCollector/test_data/raw_events_page_duplicated_dates.json
  Packs/MongoDBAtlas/README.md
  Packs/MongoDBAtlas/pack_metadata.json
Labels: docs-approved

#37484 Parse email files update docker image
  Packs/CommonScripts/ReleaseNotes/1_15_95.md
  Packs/CommonScripts/Scripts/ParseEmailFilesV2/ParseEmailFilesV2.yml
  Packs/CommonScripts/pack_metadata.json
Labels: docs-approved

#37268 Enhance ms teams functionalities part1
  Packs/MicrosoftTeams/.secrets-ignore
  Packs/MicrosoftTeams/Integrations/MicrosoftTeams/MicrosoftTeams.py
  Packs/MicrosoftTeams/Integrations/MicrosoftTeams/MicrosoftTeams.yml
  Packs/MicrosoftTeams/Integrations/MicrosoftTeams/MicrosoftTeams_test.py
  Packs/MicrosoftTeams/Integrations/MicrosoftTeams/README.md
  Packs/MicrosoftTeams/ReleaseNotes/1_5_7.md
  Packs/MicrosoftTeams/pack_metadata.json
Labels: docs-approved

#37454 [Microsoft Graph Mail] Updated integration category to *Email*
  Packs/MicrosoftGraphMail/Integrations/MicrosoftGraphListener/MicrosoftGraphListener.yml
  Packs/MicrosoftGraphMail/Integrations/MicrosoftGraphMail/MicrosoftGraphMail.yml
  Packs/MicrosoftGraphMail/ReleaseNotes/1_6_21.md
  Packs/MicrosoftGraphMail/pack_metadata.json
Labels: docs-approved

#37485 Modified parsing rule for msft_azure_ad_audit_raw - Azure Logs
  Packs/MicrosoftEntraID/ParsingRules/MicrosoftEntraID/MicrosoftEntraID.xif
  Packs/MicrosoftEntraID/ReleaseNotes/1_0_2.md
  Packs/MicrosoftEntraID/pack_metadata.json
Labels: docs-approved

#37255 Aggregated command clear-user-session
  Packs/CommonScripts/ReleaseNotes/1_15_96.md
  Packs/CommonScripts/Scripts/ClearUserSession/ClearUserSession.py
  Packs/CommonScripts/Scripts/ClearUserSession/ClearUserSession.yml
  Packs/CommonScripts/Scripts/ClearUserSession/ClearUserSession_test.py
  Packs/CommonScripts/Scripts/ClearUserSession/README.md
  Packs/CommonScripts/pack_metadata.json
Labels: docs-approved

#37212 logging improvements
  Packs/ApiModules/Scripts/DemistoClassApiModule/DemistoClassApiModule.py
  Packs/Base/ReleaseNotes/1_36_0.md
  Packs/Base/Scripts/CommonServerPython/CommonServerPython.py
  Packs/Base/pack_metadata.json
  Tests/demistomock/demistomock.py
Labels: docs-approved

#37478 Fixing export button (#37434)
  Packs/HealthCheck/ReleaseNotes/3_0_1.md
  Packs/HealthCheck/Scripts/HealthCheckExportSummary/HealthCheckExportSummary.py
  Packs/HealthCheck/Scripts/HealthCheckExportSummary/HealthCheckExportSummary.yml
  Packs/HealthCheck/pack_metadata.json
Labels: docs-approved, Internal PR

#37461 QRadar - Generic Incoming Mapper - add name field
  Packs/QRadar/Classifiers/classifier-QRadar_-_Generic_Incoming_Mapper.json
  Packs/QRadar/Integrations/QRadar_v3/QRadar_v3.py
  Packs/QRadar/ReleaseNotes/2_5_9.md
  Packs/QRadar/pack_metadata.json
Labels: docs-approved

#37453 Bug fix/xsup 44128/ews mark item as junk improve docs
  Packs/MicrosoftExchangeOnline/Integrations/EWSO365/EWSO365.yml
  Packs/MicrosoftExchangeOnline/Integrations/EWSO365/README.md
  Packs/MicrosoftExchangeOnline/ReleaseNotes/1_5_19.md
  Packs/MicrosoftExchangeOnline/pack_metadata.json
Labels: docs-approved

#36712 Script rerun PB on alerts
  Packs/Troubleshoot/ReleaseNotes/2_1_4.md
  Packs/Troubleshoot/Scripts/TroubleshootCloseAlertsByQuery/README.md
  Packs/Troubleshoot/Scripts/TroubleshootCloseAlertsByQuery/TroubleshootCloseAlertsByQuery.py
  Packs/Troubleshoot/Scripts/TroubleshootCloseAlertsByQuery/TroubleshootCloseAlertsByQuery.yml
  Packs/Troubleshoot/Scripts/TroubleshootCloseAlertsByQuery/TroubleshootCloseAlertsByQuery_test.py
  Packs/Troubleshoot/Scripts/TroubleshootExecutePlaybookByAlertQuery/README.md
  Packs/Troubleshoot/Scripts/TroubleshootExecutePlaybookByAlertQuery/TroubleshootExecutePlaybookByAlertQuery.py
  Packs/Troubleshoot/Scripts/TroubleshootExecutePlaybookByAlertQuery/TroubleshootExecutePlaybookByAlertQuery.yml
  Packs/Troubleshoot/Scripts/TroubleshootExecutePlaybookByAlertQuery/TroubleshootExecutePlaybookByAlertQuery_test.py
  Packs/Troubleshoot/pack_metadata.json
Labels: docs-approved

#37463 Rasterize url bug
  Packs/rasterize/Integrations/rasterize/rasterize.py
  Packs/rasterize/Integrations/rasterize/rasterize.yml
  Packs/rasterize/ReleaseNotes/2_0_30.md
  Packs/rasterize/pack_metadata.json
Labels: docs-approved, ForceMerge

#37451 [ExportToCSV] Ensure Consistent Line Terminators in Generated CSV Files
  Packs/CommonScripts/ReleaseNotes/1_15_97.md
  Packs/CommonScripts/Scripts/ExportToCSV/ExportToCSV.js
  Packs/CommonScripts/pack_metadata.json
Labels: docs-approved

#37489 Revert "Fix WildFire TPB"
  Packs/Palo_Alto_Networks_WildFire/TestPlaybooks/playbook-Wildfire_Test_With_Polling.yml
Labels: docs-approved

#37504 [GetFailedTasks] New argument - get_scripts_name
  Packs/IntegrationsAndIncidentsHealthCheck/ReleaseNotes/1_3_23.md
  Packs/IntegrationsAndIncidentsHealthCheck/Scripts/GetFailedTasks/GetFailedTasks.py
  Packs/IntegrationsAndIncidentsHealthCheck/Scripts/GetFailedTasks/GetFailedTasks.yml
  Packs/IntegrationsAndIncidentsHealthCheck/Scripts/GetFailedTasks/GetFailedTasks_test.py
  Packs/IntegrationsAndIncidentsHealthCheck/pack_metadata.json
Labels: docs-approved

#37425 Aud demisto/auto update docker staging branch 70
  Packs/Base/ReleaseNotes/1_35_6.md
  Packs/Base/ReleaseNotes/1_36_1.md
  Packs/Base/Scripts/DrawRelatedIncidentsCanvas/DrawRelatedIncidentsCanvas.yml
  Packs/Base/pack_metadata.json
  Packs/Campaign/ReleaseNotes/3_4_12.md
  Packs/Campaign/Scripts/GetCampaignIndicatorsByIncidentId/GetCampaignIndicatorsByIncidentId.yml
  Packs/Campaign/pack_metadata.json
  Packs/Code42/Integrations/Code42/Code42.yml
  Packs/Code42/Integrations/Code42EventCollector/Code42EventCollector.yml
  Packs/Code42/ReleaseNotes/5_0_4.md
  Packs/Code42/pack_metadata.json
  Packs/CommonScripts/ReleaseNotes/1_15_94.md
  Packs/CommonScripts/ReleaseNotes/1_15_98.md
  Packs/CommonScripts/Scripts/GenerateAsBuilt/GenerateAsBuilt.yml
  Packs/CommonScripts/Scripts/SetGridField/SetGridField.yml
  Packs/CommonScripts/pack_metadata.json
  Packs/CommunityCommonDashboards/ReleaseNotes/2_0_6.md
  Packs/CommunityCommonDashboards/Scripts/XSOARValueMetrics/XSOARValueMetrics.yml
  Packs/CommunityCommonDashboards/pack_metadata.json
  Packs/DSPM/ReleaseNotes/1_0_1.md
  Packs/DSPM/Scripts/DSPMRerunIncidents/DSPMRerunIncidents.yml
  Packs/DSPM/pack_metadata.json
  Packs/GoogleCloudStorage/Integrations/GoogleCloudStorage/GoogleCloudStorage.yml
  Packs/GoogleCloudStorage/ReleaseNotes/1_0_15.md
  Packs/GoogleCloudStorage/pack_metadata.json
  Packs/ML/ReleaseNotes/1_4_17.md
  Packs/ML/Scripts/DBotPredictIncidentsBatch/DBotPredictIncidentsBatch.yml
  Packs/ML/Scripts/EvaluateMLModllAtProduction/EvaluateMLModllAtProduction.yml
  Packs/ML/pack_metadata.json
  Packs/MicrosoftTeams/ReleaseNotes/1_5_6.md
  Packs/MicrosoftTeams/ReleaseNotes/1_5_7.md
  Packs/PrismaCloudCompute/ReleaseNotes/1_7_8.md
  Packs/PrismaCloudCompute/Scripts/PrismaCloudComputeComplianceTable/PrismaCloudComputeComplianceTable.yml
  Packs/PrismaCloudCompute/pack_metadata.json
  Packs/Workday/Integrations/WorkdayIAMEventsGenerator/WorkdayIAMEventsGenerator.yml
  Packs/Workday/Integrations/WorkdaySignonEventGenerator/WorkdaySignonEventGenerator.yml
  Packs/Workday/ReleaseNotes/1_4_16.md
  Packs/Workday/pack_metadata.json
Labels: docs-approved

#37494 Debug log dropbox event collector
  Packs/Dropbox/Integrations/DropboxEventCollector/DropboxEventCollector.py
  Packs/Dropbox/ReleaseNotes/1_1_5.md
  Packs/Dropbox/pack_metadata.json
Labels: docs-approved

#37535 bump version for AccessInvestigation pack
  Packs/AccessInvestigation/ReleaseNotes/1_2_10.md
  Packs/AccessInvestigation/pack_metadata.json
Labels: docs-approved, bypass.url

#37436 Added xsoar engine related functions to the CSP
  Packs/Base/.secrets-ignore
  Packs/Base/ReleaseNotes/1_36_2.md
  Packs/Base/Scripts/CommonServerPython/CommonServerPython.py
  Packs/Base/Scripts/CommonServerPython/CommonServerPython_test.py
  Packs/Base/pack_metadata.json
Labels: docs-approved

#37538 revert
  Packs/ApiModules/Scripts/DemistoClassApiModule/DemistoClassApiModule.py
  Packs/Base/ReleaseNotes/1_37_0.md
  Packs/Base/pack_metadata.json
Labels: docs-approved

#37541 demisto/readpdf:1.0.0.117518 | 0-100 | PR batch #1/1
  Packs/CommonScripts/Scripts/PDFUnlocker/PDFUnlocker.yml
  Packs/CommonScripts/Scripts/ReadPDFFileV2/ReadPDFFileV2.yml
Labels: auto-update-docker

#37542 demisto/dxl:1.0.0.116949 | 0-100 | PR batch #1/1
  Packs/McAfee-MAR/Integrations/McAfee-MAR/McAfee-MAR.yml
  Packs/McAfee-TIE/Integrations/McAfeeTIEV2/McAfeeTIEV2.yml
  Packs/McAfee_DXL/Integrations/McAfee_DXL/McAfee_DXL.yml
Labels: auto-update-docker

#37536 MS Teams - Fixed the 'xdr' substitution for XSIAM machines
  Packs/MicrosoftTeams/Integrations/MicrosoftTeams/MicrosoftTeams.py
  Packs/MicrosoftTeams/Integrations/MicrosoftTeams/MicrosoftTeams_test.py
  Packs/MicrosoftTeams/ReleaseNotes/1_5_8.md
  Packs/MicrosoftTeams/pack_metadata.json
Labels: docs-approved

#37534 Bug fix/XSUP-44464/big-query handle bytes
  Packs/GoogleBigQuery/Integrations/GoogleBigQuery/GoogleBigQuery.py
  Packs/GoogleBigQuery/Integrations/GoogleBigQuery/GoogleBigQuery_test.py
  Packs/GoogleBigQuery/ReleaseNotes/1_1_9.md
  Packs/GoogleBigQuery/pack_metadata.json
Labels: docs-approved, release-notes-only

#37521 CISOMetrics - remove dashboard from saas marketplace
  Packs/CommunityCommonDashboards/Dashboards/CISOMetrics.json
  Packs/CommunityCommonDashboards/ReleaseNotes/2_0_7.md
  Packs/CommunityCommonDashboards/pack_metadata.json
Labels: docs-approved, ForceMerge

#37411 ThreatVault new endpoints - API
  Packs/Base/ReleaseNotes/1_38_0.md
  Packs/Base/Scripts/CommonServerPython/CommonServerPython.py
  Packs/Base/pack_metadata.json
  Packs/PaloAltoNetworks_Threat_Vault/Integrations/ThreatVaultv2/ThreatVaultv2.py
  Packs/PaloAltoNetworks_Threat_Vault/Integrations/ThreatVaultv2/ThreatVaultv2.yml
  Packs/PaloAltoNetworks_Threat_Vault/Integrations/ThreatVaultv2/ThreatVaultv2_test.py
  Packs/PaloAltoNetworks_Threat_Vault/Integrations/ThreatVaultv2/test_data/ip_batch_results.json
  Packs/PaloAltoNetworks_Threat_Vault/Integrations/ThreatVaultv2/test_data/single_ip_result.json
  Packs/PaloAltoNetworks_Threat_Vault/README.md
  Packs/PaloAltoNetworks_Threat_Vault/ReleaseNotes/2_0_16.md
  Packs/PaloAltoNetworks_Threat_Vault/pack_metadata.json
Labels: docs-approved

#37547 dbot mirror id only if not empty
  Packs/Elasticsearch/Integrations/Elasticsearch_v2/Elasticsearch_v2.py
  Packs/Elasticsearch/ReleaseNotes/1_3_24.md
  Packs/Elasticsearch/pack_metadata.json
  Packs/SplunkPy/Integrations/SplunkPy/SplunkPy.py
  Packs/SplunkPy/ReleaseNotes/3_1_48.md
  Packs/SplunkPy/pack_metadata.json
Labels: docs-approved

#37481 MDE XSUP-44022 - Correlation Rule Update
  Packs/MicrosoftDefenderAdvancedThreatProtection/CorrelationRules/MicrosoftDefenderAdvancedThreatProtection_correlation-rule.yml
  Packs/MicrosoftDefenderAdvancedThreatProtection/ReleaseNotes/1_17_6.md
  Packs/MicrosoftDefenderAdvancedThreatProtection/pack_metadata.json
Labels: docs-approved, bypass.url

#37328 Ciac 12050 ews extension online powershell v3 add commands
  Packs/MicrosoftExchangeOnline/Integrations/EwsExtensionEXOPowershellV3/EwsExtensionEXOPowershellV3.ps1
  Packs/MicrosoftExchangeOnline/Integrations/EwsExtensionEXOPowershellV3/EwsExtensionEXOPowershellV3.yml
  Packs/MicrosoftExchangeOnline/Integrations/EwsExtensionEXOPowershellV3/README.md
  Packs/MicrosoftExchangeOnline/ReleaseNotes/1_5_21.md
  Packs/MicrosoftExchangeOnline/pack_metadata.json
Labels: docs-approved

#37533 CRTX-117198 - Modified xdm.source.ipv4 field and added mapping other ip fields
  Packs/MicrosoftADFS/ModelingRules/MicrosoftADFS_1_3/MicrosoftADFS_1_3.xif
  Packs/MicrosoftADFS/ReleaseNotes/1_0_18.md
  Packs/MicrosoftADFS/pack_metadata.json
Labels: docs-approved

#37498 AzureSentinel: restriction on mirror out
  Packs/AzureSentinel/Integrations/AzureSentinel/AzureSentinel.py
  Packs/AzureSentinel/Integrations/AzureSentinel/AzureSentinel.yml
  Packs/AzureSentinel/Integrations/AzureSentinel/AzureSentinel_test.py
  Packs/AzureSentinel/ReleaseNotes/1_5_56.md
  Packs/AzureSentinel/TestPlaybooks/TestAzureSentinelPlaybookV2.yml
  Packs/AzureSentinel/pack_metadata.json
Labels: docs-approved

#37462 Chronicle Release 4.1.0
  Packs/GoogleChronicleBackstory/.pack-ignore
  Packs/GoogleChronicleBackstory/Integrations/GoogleChronicleBackstory/GoogleChronicleBackstory.py
  Packs/GoogleChronicleBackstory/Integrations/GoogleChronicleBackstory/GoogleChronicleBackstory.yml
  Packs/GoogleChronicleBackstory/Integrations/GoogleChronicleBackstory/GoogleChronicleBackstory_test.py
  Packs/GoogleChronicleBackstory/Integrations/GoogleChronicleBackstory/README.md
  Packs/GoogleChronicleBackstory/Integrations/GoogleChronicleBackstory/test_data/gcb_get_event_command_invalid_event_id_400.json
  Packs/GoogleChronicleBackstory/Integrations/GoogleChronicleBackstory/test_data/gcb_verify_rule_ec.json
  Packs/GoogleChronicleBackstory/Integrations/GoogleChronicleBackstory/test_data/gcb_verify_rule_hr.md
  Packs/GoogleChronicleBackstory/Integrations/GoogleChronicleBackstory/test_data/gcb_verify_rule_invalid_format_ec.json
  Packs/GoogleChronicleBackstory/Integrations/GoogleChronicleBackstory/test_data/gcb_verify_rule_invalid_format_hr.md
  Packs/GoogleChronicleBackstory/Integrations/GoogleChronicleBackstory/test_data/gcb_verify_rule_invalid_format_response.json
  Packs/GoogleChronicleBackstory/Integrations/GoogleChronicleBackstory/test_data/gcb_verify_rule_response.json
  Packs/GoogleChronicleBackstory/Integrations/GoogleChronicleBackstory/test_data/gcb_verify_value_in_reference_list_command_ec.json
  Packs/GoogleChronicleBackstory/Integrations/GoogleChronicleBackstory/test_data/gcb_verify_value_in_reference_list_command_hr.md
  Packs/GoogleChronicleBackstory/Integrations/GoogleChronicleBackstory/test_data/gcb_verify_value_in_reference_list_command_response.json
  Packs/GoogleChronicleBackstory/Integrations/GoogleChronicleBackstory/test_data/get_event_ec.json
  Packs/GoogleChronicleBackstory/Integrations/GoogleChronicleBackstory/test_data/get_event_hr.md
  Packs/GoogleChronicleBackstory/Integrations/GoogleChronicleBackstory/test_data/get_event_response.json
  Packs/GoogleChronicleBackstory/Integrations/GoogleChronicleBackstory/test_data/list_events_ec.json
  Packs/GoogleChronicleBackstory/Integrations/GoogleChronicleBackstoryStreamingAPI/GoogleChronicleBackstoryStreamingAPI.py
  Packs/GoogleChronicleBackstory/Integrations/GoogleChronicleBackstoryStreamingAPI/GoogleChronicleBackstoryStreamingAPI.yml
  Packs/GoogleChronicleBackstory/Integrations/GoogleChronicleBackstoryStreamingAPI/GoogleChronicleBackstoryStreamingAPI_test.py
  Packs/GoogleChronicleBackstory/Integrations/GoogleChronicleBackstoryStreamingAPI/README.md
  Packs/GoogleChronicleBackstory/Integrations/GoogleChronicleBackstoryStreamingAPI/test_data/steam_detection_outputs.json
  Packs/GoogleChronicleBackstory/Integrations/GoogleChronicleBackstoryStreamingAPI/test_data/stream_detections.txt
  Packs/GoogleChronicleBackstory/ReleaseNotes/4_1_0.md
  Packs/GoogleChronicleBackstory/pack_metadata.json
Labels: Contribution, Partner, Contribution Form Filled, Partner Support Level, External PR, Partner-Approved

#37439 CISCO ESA dictionary api commands
  Packs/IronPort/Integrations/CiscoEmailSecurityApplianceIronPortV2/CiscoEmailSecurityApplianceIronPortV2.py
  Packs/IronPort/Integrations/CiscoEmailSecurityApplianceIronPortV2/CiscoEmailSecurityApplianceIronPortV2.yml
  Packs/IronPort/Integrations/CiscoEmailSecurityApplianceIronPortV2/CiscoEmailSecurityApplianceIronPortV2_test.py
  Packs/IronPort/Integrations/CiscoEmailSecurityApplianceIronPortV2/README.md
  Packs/IronPort/Integrations/CiscoEmailSecurityApplianceIronPortV2/command-examples.txt
  Packs/IronPort/ReleaseNotes/2_1_0.md
  Packs/IronPort/TestPlaybooks/CiscoESA_dictionary_commands_tpb.yml
  Packs/IronPort/pack_metadata.json
  Tests/conf.json
Labels: docs-approved

#37455 CRTX-141354-Zscaler NSS Firewall
  Packs/Zscaler/.secrets-ignore
  Packs/Zscaler/ModelingRules/ZscalerModelingRule_1_3/ZscalerModelingRule_1_3.xif
  Packs/Zscaler/ModelingRules/ZscalerModelingRule_1_3/ZscalerModelingRule_1_3_schema.json
  Packs/Zscaler/README.md
  Packs/Zscaler/ReleaseNotes/1_3_29.md
  Packs/Zscaler/pack_metadata.json
Labels: docs-approved, bypass.url

#37558 Chronicle Release 4.1.0
  Packs/GoogleChronicleBackstory/.pack-ignore
  Packs/GoogleChronicleBackstory/Integrations/GoogleChronicleBackstory/GoogleChronicleBackstory.py
  Packs/GoogleChronicleBackstory/Integrations/GoogleChronicleBackstory/GoogleChronicleBackstory.yml
  Packs/GoogleChronicleBackstory/Integrations/GoogleChronicleBackstory/GoogleChronicleBackstory_test.py
  Packs/GoogleChronicleBackstory/Integrations/GoogleChronicleBackstory/README.md
  Packs/GoogleChronicleBackstory/Integrations/GoogleChronicleBackstory/test_data/gcb_get_event_command_invalid_event_id_400.json
  Packs/GoogleChronicleBackstory/Integrations/GoogleChronicleBackstory/test_data/gcb_verify_rule_ec.json
  Packs/GoogleChronicleBackstory/Integrations/GoogleChronicleBackstory/test_data/gcb_verify_rule_hr.md
  Packs/GoogleChronicleBackstory/Integrations/GoogleChronicleBackstory/test_data/gcb_verify_rule_invalid_format_ec.json
  Packs/GoogleChronicleBackstory/Integrations/GoogleChronicleBackstory/test_data/gcb_verify_rule_invalid_format_hr.md
  Packs/GoogleChronicleBackstory/Integrations/GoogleChronicleBackstory/test_data/gcb_verify_rule_invalid_format_response.json
  Packs/GoogleChronicleBackstory/Integrations/GoogleChronicleBackstory/test_data/gcb_verify_rule_response.json
  Packs/GoogleChronicleBackstory/Integrations/GoogleChronicleBackstory/test_data/gcb_verify_value_in_reference_list_command_ec.json
  Packs/GoogleChronicleBackstory/Integrations/GoogleChronicleBackstory/test_data/gcb_verify_value_in_reference_list_command_hr.md
  Packs/GoogleChronicleBackstory/Integrations/GoogleChronicleBackstory/test_data/gcb_verify_value_in_reference_list_command_response.json
  Packs/GoogleChronicleBackstory/Integrations/GoogleChronicleBackstory/test_data/get_event_ec.json
  Packs/GoogleChronicleBackstory/Integrations/GoogleChronicleBackstory/test_data/get_event_hr.md
  Packs/GoogleChronicleBackstory/Integrations/GoogleChronicleBackstory/test_data/get_event_response.json
  Packs/GoogleChronicleBackstory/Integrations/GoogleChronicleBackstory/test_data/list_events_ec.json
  Packs/GoogleChronicleBackstory/Integrations/GoogleChronicleBackstoryStreamingAPI/GoogleChronicleBackstoryStreamingAPI.py
  Packs/GoogleChronicleBackstory/Integrations/GoogleChronicleBackstoryStreamingAPI/GoogleChronicleBackstoryStreamingAPI.yml
  Packs/GoogleChronicleBackstory/Integrations/GoogleChronicleBackstoryStreamingAPI/GoogleChronicleBackstoryStreamingAPI_test.py
  Packs/GoogleChronicleBackstory/Integrations/GoogleChronicleBackstoryStreamingAPI/README.md
  Packs/GoogleChronicleBackstory/Integrations/GoogleChronicleBackstoryStreamingAPI/test_data/steam_detection_outputs.json
  Packs/GoogleChronicleBackstory/Integrations/GoogleChronicleBackstoryStreamingAPI/test_data/stream_detections.txt
  Packs/GoogleChronicleBackstory/ReleaseNotes/4_1_0.md
  Packs/GoogleChronicleBackstory/pack_metadata.json
Labels: Contribution, docs-approved, Partner, Contribution Form Filled, Partner Support Level, Internal PR, Partner-Approved

#37449 Fix: Updated the parsing logic for the autonomous system indicator to convert the value to a string
  Packs/ApiModules/ReleaseNotes/2_2_31.md
  Packs/ApiModules/Scripts/TAXII2ApiModule/TAXII2ApiModule.py
  Packs/ApiModules/Scripts/TAXII2ApiModule/TAXII2ApiModule.yml
  Packs/ApiModules/Scripts/TAXII2ApiModule/TAXII2ApiModule_test.py
  Packs/ApiModules/pack_metadata.json
Labels: Contribution, Partner, Contribution Form Filled, Xsoar Support Level, External PR, Partner-Approved

#37565 demisto/python3:3.11.10.115186 | 0-100 | PR batch #2/2
  Packs/ShiftManagement-AssignToNextShift/Scripts/AssignToNextShift/AssignToNextShift.yml
  Packs/Signum/Integrations/Signum/Signum.yml
  Packs/SimpleDebugger/Scripts/SimpleDebugger/SimpleDebugger.yml
  Packs/Smokescreen_IllusionBLACK/Integrations/Smokescreen_IllusionBLACK/Smokescreen_IllusionBLACK.yml
  Packs/SnortIPBlocklist/Integrations/FeedSnortIPBlocklist/FeedSnortIPBlocklist.yml
  Packs/SpyCloud/Integrations/SpyCloud/SpyCloud.yml
  Packs/StarterPack/Integrations/BaseIntegration/BaseIntegration.yml
  Packs/StarterPack/Scripts/BaseScript/BaseScript.yml
  Packs/StellarCyber/Integrations/StellarCyber/StellarCyber.yml
  Packs/SumoLogic_Cloud_SIEM/Integrations/SumoLogicCloudSIEM/SumoLogicCloudSIEM.yml
  Packs/TeamCymru/Integrations/TeamCymruScout/TeamCymruScout.yml
  Packs/TeamManagement/Scripts/EnumerateRoles/EnumerateRoles.yml
  Packs/ThousandEyes/Integrations/ThousandEyes/ThousandEyes.yml
  Packs/Traceable/Integrations/Traceable/Traceable.yml
  Packs/Trello/Integrations/Trello/Trello.yml
  Packs/TrendMicroVisionOne/Integrations/TrendMicroVisionOne/TrendMicroVisionOne.yml
  Packs/TwitterIOCHunter-FullDailyFeed/Integrations/TwitterIOCHunterFullDailyFeed/TwitterIOCHunterFullDailyFeed.yml
  Packs/USTA/Integrations/USTA/USTA.yml
  Packs/UltraMSG/Integrations/UltraMSG/UltraMSG.yml
  Packs/UnisysStealth/Integrations/UnisysStealth/UnisysStealth.yml
  Packs/UpdateEntriesBySearch/Scripts/MarkAsEvidenceBySearch/MarkAsEvidenceBySearch.yml
  Packs/UpdateEntriesBySearch/Scripts/MarkAsNoteBySearch/MarkAsNoteBySearch.yml
  Packs/UpdateEntriesBySearch/Scripts/SetTagsBySearch/SetTagsBySearch.yml
  Packs/Use_Case_Builder/Scripts/CreateUseCaseStepsList/CreateUseCaseStepsList.yml
  Packs/Use_Case_Builder/Scripts/CreateXSOARIncidentFlowList/CreateXSOARIncidentFlowList.yml
  Packs/Use_Case_Builder/Scripts/DeleteAndExcludeIndicators/DeleteAndExcludeIndicators.yml
  Packs/Use_Case_Builder/Scripts/GettingStartedWithXSOAR/GettingStartedWithXSOAR.yml
  Packs/Use_Case_Builder/Scripts/PlaybookAutoGeneratorDynamicSectionMessage/PlaybookAutoGeneratorDynamicSectionMessage.yml
  Packs/Use_Case_Builder/Scripts/StopUseCaseDevelopmentTimer/StopUseCaseDevelopmentTimer.yml
  Packs/Use_Case_Builder/Scripts/UseCaseDevelopmentTimers/UseCaseDevelopmentTimers.yml
  Packs/Veeam/Integrations/VBRRESTAPI/VBRRESTAPI.yml
  Packs/Veeam/Integrations/VeeamONERESTAPI/VeeamONERESTAPI.yml
  Packs/Veeam/Scripts/GetRestoredVmName/GetRestoredVmName.yml
  Packs/Veeam/Scripts/getfoldername/getfoldername.yml
  Packs/Veeam/Scripts/gethostname/gethostname.yml
  Packs/VerifyIPv4Indicator/Scripts/VerifyIPv4Indicator/VerifyIPv4Indicator.yml
  Packs/Viper/Integrations/Viper/Viper.yml
  Packs/VirusTotal/Integrations/VirusTotalV3/VirusTotalV3.yml
  Packs/Wiz/Integrations/Wiz/Wiz.yml
  Packs/WolkenITSM/Integrations/WolkenITSM/WolkenITSM.yml
  Packs/Wordpress/Integrations/Wordpress/Wordpress.yml
  Packs/XMCO/Integrations/Serenety/Serenety.yml
  Packs/XSOARContentUpdateNotifications/Scripts/CollectPacksData/CollectPacksData.yml
  Packs/XSOARContentUpdateNotifications/Scripts/FormatContentData/FormatContentData.yml
  Packs/XSOARContentUpdateNotifications/Scripts/GetLatestReleaseNotes/GetLatestReleaseNotes.yml
  Packs/XSOAR_EDL_Checker/Scripts/XSOARAllEDLCheckerAutomation/XSOARAllEDLCheckerAutomation.yml
  Packs/XsoarWebserver/Scripts/EmailSLABreach/EmailSLABreach.yml
  Packs/XsoarWebserver/Scripts/XsoarWsParseContext/XsoarWsParseContext.yml
  Packs/XsoarWebserver/Scripts/XsoarWsPollStatus/XsoarWsPollStatus.yml
  Packs/Xsoar_Utils/Integrations/XsoarUtils/XsoarUtils.yml
  Packs/Zafran/Integrations/Zafran/Zafran.yml
  Packs/ZeroFox/Integrations/ZeroFox/ZeroFox.yml
  Packs/cisco-ise/Integrations/cisco-ise/cisco-ise.yml
Labels: auto-update-docker

#37216 Flashpoint Release 2.0.2
  Packs/Flashpoint/Classifiers/classifier-mapper-incoming-Flashpoint_Compromised_Credentials.json
  Packs/Flashpoint/IncidentTypes/IncidentTypes-Compromised-Credentials.json
  Packs/Flashpoint/Integrations/Ignite/Ignite.py
  Packs/Flashpoint/Integrations/Ignite/Ignite.yml
  Packs/Flashpoint/Integrations/Ignite/Ignite_test.py
  Packs/Flashpoint/Integrations/Ignite/README.md
  Packs/Flashpoint/Integrations/Ignite/test_data/fetch_compromised_credentials.json
  Packs/Flashpoint/Integrations/Ignite/test_data/fetch_incidents_compromised_credentials_check_duplicate.json
  Packs/Flashpoint/Integrations/Ignite/test_data/get_compromised_credentials_hr_output.md
  Packs/Flashpoint/Integrations/Ignite/test_data/incidents_compromised_credentials.json
  Packs/Flashpoint/Integrations/Ignite/test_data/incidents_compromised_credentials_when_email_not_present.json
  Packs/Flashpoint/Integrations/Ignite/test_data/incidents_compromised_credentials_when_email_username_not_present.json
  Packs/Flashpoint/ReleaseNotes/2_0_2.md
  Packs/Flashpoint/pack_metadata.json
Labels: Contribution, docs-approved, Partner, Contribution Form Filled, Partner Support Level, External PR, Security Review, Partner-Approved, Security Approved

#37568 demisto/chromium:131.0.6778.117810 | 0-100 | PR batch #1/1
  Packs/CofenseTriage/Integrations/CofenseTriagev2/CofenseTriagev2.yml
  Packs/rasterize/Integrations/rasterize/rasterize.yml
Labels: auto-update-docker

#37569 demisto/m2crypto:1.0.0.117200 | 0-100 | PR batch #1/1
  Packs/SMIME_Messaging/Integrations/SMIME_Messaging/SMIME_Messaging.yml
Labels: auto-update-docker

#37570 demisto/google-k8s-engine:1.0.0.117480 | 0-100 | PR batch #1/1
  Packs/GoogleKubernetesEngine/Integrations/GoogleKubernetesEngine/GoogleKubernetesEngine.yml
Labels: auto-update-docker

#37572 demisto/syslog:1.0.0.117331 | 0-100 | PR batch #1/1
  Packs/Syslog/Integrations/SyslogSender/SyslogSender.yml
  Packs/Syslog/Integrations/Syslogv2/Syslogv2.yml
Labels: auto-update-docker

#37476 Veeam: Documentation and metadata changes. XSIAM marketplace supported.
  Packs/Veeam/README.md
  Packs/Veeam/ReleaseNotes/1_0_3.md
  Packs/Veeam/doc_files/Veeam_Data_Platform_Monitoring_Dashboard_image.png
  Packs/Veeam/doc_files/Veeam_Security_Activities_Dashboard_image.png
  Packs/Veeam/doc_files/Veeam_XSOAR_Dashboard.png
  Packs/Veeam/doc_files/Veeam_XSOAR_Playbooks.png
  Packs/Veeam/pack_metadata.json
Labels: Contribution, docs-approved, Partner, Contribution Form Filled, Partner Support Level, External PR, Partner-Approved

#37573 Flashpoint Release 2.0.2
  Packs/Flashpoint/Classifiers/classifier-mapper-incoming-Flashpoint_Compromised_Credentials.json
  Packs/Flashpoint/IncidentTypes/IncidentTypes-Compromised-Credentials.json
  Packs/Flashpoint/Integrations/Ignite/Ignite.py
  Packs/Flashpoint/Integrations/Ignite/Ignite.yml
  Packs/Flashpoint/Integrations/Ignite/Ignite_test.py
  Packs/Flashpoint/Integrations/Ignite/README.md
  Packs/Flashpoint/Integrations/Ignite/test_data/fetch_compromised_credentials.json
  Packs/Flashpoint/Integrations/Ignite/test_data/fetch_incidents_compromised_credentials_check_duplicate.json
  Packs/Flashpoint/Integrations/Ignite/test_data/get_compromised_credentials_hr_output.md
  Packs/Flashpoint/Integrations/Ignite/test_data/incidents_compromised_credentials.json
  Packs/Flashpoint/Integrations/Ignite/test_data/incidents_compromised_credentials_when_email_not_present.json
  Packs/Flashpoint/Integrations/Ignite/test_data/incidents_compromised_credentials_when_email_username_not_present.json
  Packs/Flashpoint/ReleaseNotes/2_0_2.md
  Packs/Flashpoint/pack_metadata.json
Labels: Contribution, docs-approved, Partner, Contribution Form Filled, Partner Support Level, Security Review, Internal PR, Partner-Approved, Security Approved

#37499 Fix xdr test playbook
  Packs/CortexXDR/TestPlaybooks/Test_XDR_Playbook_general_commands.yml
Labels: docs-approved

#36804 added integration for symnatec email security
  Packs/CoreAlertFields/IncidentFields/incidentfield-Category_Name.json
  Packs/CoreAlertFields/IncidentFields/incidentfield-Email_Recipient.json
  Packs/CoreAlertFields/IncidentFields/incidentfield-Email_Sender.json
  Packs/CoreAlertFields/IncidentFields/incidentfield-Email_Subject.json
  Packs/SymantecEmailSecurity/.pack-ignore
  Packs/SymantecEmailSecurity/.secrets-ignore
  Packs/SymantecEmailSecurity/Classifiers/classifier-Symantec_Email_Security_Cloud_-_Classifier.json
  Packs/SymantecEmailSecurity/Classifiers/classifier-Symantec_Email_Security_Cloud_-_Mapper.json
  Packs/SymantecEmailSecurity/IncidentFields/incidentfield-Symantec_ESC_Detection_Method.json
  Packs/SymantecEmailSecurity/IncidentFields/incidentfield-Symantec_ESC_Email_Attachment.json
  Packs/SymantecEmailSecurity/IncidentFields/incidentfield-Symantec_ESC_Email_Body.json
  Packs/SymantecEmailSecurity/IncidentFields/incidentfield-Symantec_ESC_Email_Direction.json
  Packs/SymantecEmailSecurity/IncidentFields/incidentfield-Symantec_ESC_Email_Malware_Category.json
  Packs/SymantecEmailSecurity/IncidentFields/incidentfield-Symantec_ESC_Email_Malware_Name.json
  Packs/SymantecEmailSecurity/IncidentFields/incidentfield-Symantec_ESC_Email_Recipient.json
  Packs/SymantecEmailSecurity/IncidentFields/incidentfield-Symantec_ESC_Email_Sender.json
  Packs/SymantecEmailSecurity/IncidentFields/incidentfield-Symantec_ESC_Email_Subject.json
  Packs/SymantecEmailSecurity/IncidentFields/incidentfield-Symantec_ESC_Quarantine_Rule.json
  Packs/SymantecEmailSecurity/IncidentFields/incidentfield-Symantec_ESC_Security_Service.json
  Packs/SymantecEmailSecurity/IncidentTypes/incidenttype-Symantec_ESC_Incident.json
  Packs/SymantecEmailSecurity/IncidentTypes/incidenttype-Symantec_ESC_Quarantine.json
  Packs/SymantecEmailSecurity/Integrations/SymantecEmailSecurity/README.md
  Packs/SymantecEmailSecurity/Integrations/SymantecEmailSecurity/SymantecEmailSecurity.py
  Packs/SymantecEmailSecurity/Integrations/SymantecEmailSecurity/SymantecEmailSecurity.yml
  Packs/SymantecEmailSecurity/Integrations/SymantecEmailSecurity/SymantecEmailSecurity_description.md
  Packs/SymantecEmailSecurity/Integrations/SymantecEmailSecurity/SymantecEmailSecurity_image.png
  Packs/SymantecEmailSecurity/Integrations/SymantecEmailSecurity/SymantecEmailSecurity_test.py
  Packs/SymantecEmailSecurity/Integrations/SymantecEmailSecurity/command_examples.txt
  Packs/SymantecEmailSecurity/Integrations/SymantecEmailSecurity/test_data/data_list_response.json
  Packs/SymantecEmailSecurity/Integrations/SymantecEmailSecurity/test_data/data_list_table.json
  Packs/SymantecEmailSecurity/Integrations/SymantecEmailSecurity/test_data/email_queue_list_response.json
  Packs/SymantecEmailSecurity/Integrations/SymantecEmailSecurity/test_data/ioc_list_response.json
  Packs/SymantecEmailSecurity/Integrations/SymantecEmailSecurity/test_data/ioc_list_table.json
  Packs/SymantecEmailSecurity/Integrations/SymantecEmailSecurity/test_data/item_allow_block_list_response.json
  Packs/SymantecEmailSecurity/Integrations/SymantecEmailSecurity/test_data/item_allow_block_list_table.json
  Packs/SymantecEmailSecurity/Integrations/SymantecEmailSecurity/test_data/quarantine_email_list_response.json
  Packs/SymantecEmailSecurity/Integrations/SymantecEmailSecurity/test_data/quarantine_email_list_table.json
  Packs/SymantecEmailSecurity/Integrations/SymantecEmailSecurity/test_data/quarantine_email_preview_response.json
  Packs/SymantecEmailSecurity/Integrations/SymantecEmailSecurity/test_data/quarantine_email_preview_table.json
  Packs/SymantecEmailSecurity/Layouts/layoutscontainer-Symantec_Email_Security_Cloud_-_Layout.json
  Packs/SymantecEmailSecurity/README.md
  Packs/SymantecEmailSecurity/TestPlaybooks/playbook-SymantecEmailSecurity_Test.yml
  Packs/SymantecEmailSecurity/pack_metadata.json
Labels: Contribution, docs-approved, Contribution Form Filled, Community, Xsoar Support Level, External PR, Security Review

#37550 reco: change EP for optimization
  Packs/Reco/Integrations/Reco/Reco.py
  Packs/Reco/Integrations/Reco/Reco_test.py
  Packs/Reco/ReleaseNotes/1_5_2.md
  Packs/Reco/pack_metadata.json
Labels: Contribution, Partner, Contribution Form Filled, Partner Support Level, External PR, Partner-Approved

#37464 reco: change default timeout to 3 mins
  Packs/Reco/Integrations/Reco/Reco.py
  Packs/Reco/ReleaseNotes/1_5_2.md
  Packs/Reco/pack_metadata.json
Labels: Contribution, docs-approved, Partner, Contribution Form Filled, Partner Support Level, External PR, Partner-Approved

#37575 SplunkPy: use retry mechanism
  Packs/SplunkPy/Integrations/SplunkPy/SplunkPy.py
  Packs/SplunkPy/ReleaseNotes/3_1_49.md
  Packs/SplunkPy/pack_metadata.json
Labels: docs-approved

#37584 reco: change default timeout to 3 mins
  Packs/Reco/Integrations/Reco/Reco.py
  Packs/Reco/ReleaseNotes/1_5_2.md
  Packs/Reco/pack_metadata.json
Labels: Contribution, docs-approved, Partner, Contribution Form Filled, Partner Support Level, Internal PR, Partner-Approved

#37583 reco: change EP for optimization
  Packs/Reco/Integrations/Reco/Reco.py
  Packs/Reco/Integrations/Reco/Reco_test.py
  Packs/Reco/ReleaseNotes/1_5_3.md
  Packs/Reco/pack_metadata.json
Labels: Contribution, docs-approved, Partner, Contribution Form Filled, Partner Support Level, Internal PR, Partner-Approved

#37503 Issue in xdm.email.recipients
  Packs/Office365/ModelingRules/Office365/Office365.xif
  Packs/Office365/ReleaseNotes/1_0_8.md
  Packs/Office365/pack_metadata.json
Labels: docs-approved

#37295 Adding CybelAngel Pack
  Packs/Office365/ModelingRules/Office365/Office365.xif
  Packs/Office365/ReleaseNotes/1_0_8.md
  Packs/Office365/pack_metadata.json
Labels: Contribution, Partner, Contribution Form Filled, Partner Support Level, External PR, Security Review, Partner-Approved

#37594 Chronicle Release 4.1.1
  Packs/GoogleChronicleBackstory/Integrations/GoogleChronicleBackstoryStreamingAPI/GoogleChronicleBackstoryStreamingAPI.py
  Packs/GoogleChronicleBackstory/ReleaseNotes/4_1_1.md
  Packs/GoogleChronicleBackstory/pack_metadata.json
Labels: Contribution, Partner, Contribution Form Filled, Partner Support Level, External PR, Partner-Approved

#37582 Bug fix/data message
  Packs/CybleEventsV2/Integrations/CybleEventsV2/CybleEventsV2.py
  Packs/CybleEventsV2/ReleaseNotes/1_0_6.md
  Packs/CybleEventsV2/pack_metadata.json
Labels: Contribution, Partner, Contribution Form Filled, Partner Support Level, External PR, Partner-Approved

#37488 Skyhigh Secure Web Gateway Add logs
  Packs/McAfeeWebGateway/Integrations/SkyhighSecureWebGatewayOnPrem/SkyhighSecureWebGatewayOnPrem.py
  Packs/McAfeeWebGateway/Integrations/SkyhighSecureWebGatewayOnPrem/SkyhighSecureWebGatewayOnPrem_test.py
  Packs/McAfeeWebGateway/ReleaseNotes/1_0_13.md
  Packs/McAfeeWebGateway/pack_metadata.json
Labels: docs-approved, release-notes-only

#37361 CyberArk - update name and logo
  Packs/cyberark_AIM/Integrations/CyberArkAIM/CyberArkAIM_image.png
  Packs/cyberark_AIM/Integrations/CyberArkAIM_v2/CyberArkAIM_v2_description.md
  Packs/cyberark_AIM/Integrations/CyberArkAIM_v2/CyberArkAIM_v2_image.png
  Packs/cyberark_AIM/Integrations/CyberArkAIM_v2/README.md
  Packs/cyberark_AIM/ReleaseNotes/1_0_20.md
  Packs/cyberark_AIM/pack_metadata.json
Labels: Contribution, docs-approved, Partner, Contribution Form Filled, Partner Support Level, External PR, Partner-Approved

#37602 Bug fix/data message
  Packs/CybleEventsV2/Integrations/CybleEventsV2/CybleEventsV2.py
  Packs/CybleEventsV2/Integrations/CybleEventsV2/CybleEventsV2.yml
  Packs/CybleEventsV2/ReleaseNotes/1_0_6.md
  Packs/CybleEventsV2/pack_metadata.json
Labels: Contribution, docs-approved, Partner, Contribution Form Filled, Partner Support Level, Internal PR, Partner-Approved

#37600 Chronicle Release 4.1.1
  Packs/GoogleChronicleBackstory/Integrations/GoogleChronicleBackstoryStreamingAPI/GoogleChronicleBackstoryStreamingAPI.py
  Packs/GoogleChronicleBackstory/ReleaseNotes/4_1_1.md
  Packs/GoogleChronicleBackstory/pack_metadata.json
Labels: Contribution, docs-approved, Partner, Contribution Form Filled, Partner Support Level, Internal PR, Partner-Approved

#37586 ServiceNowV2: Hide mirror fileds in XSIAM
  Packs/ServiceNow/Integrations/ServiceNowv2/ServiceNowv2.yml
  Packs/ServiceNow/ReleaseNotes/2_7_1.md
  Packs/ServiceNow/pack_metadata.json
Labels: docs-approved, ForceMerge

#37447 [XSIAM PB] Suspicious access to shadow file
  Packs/Core/Playbooks/playbook-Uncommon_creation_or_access_operation_of_sensitive_shadow_copy_by_a_high_risk_process.yml
  Packs/Core/Playbooks/playbook-Uncommon_creation_or_access_operation_of_sensitive_shadow_copy_by_a_high_risk_process_README.md
  Packs/Core/ReleaseNotes/3_2_0.md
  Packs/Core/Triggers/Trigger_-_Suspicious_access_to_shadow_file.json
  Packs/Core/doc_files/Uncommon_creation_or_access_operation_of_sensitive_shadow_copy_by_a_high-risk_process.png
  Packs/Core/pack_metadata.json
Labels: docs-approved

#37605 Update cyberchef tag
  Packs/CyberChef/Integrations/CyberChef/CyberChef.yml
  Packs/CyberChef/ReleaseNotes/1_0_9.md
  Packs/CyberChef/pack_metadata.json
Labels: docs-approved

#37561 update commvault docker image tag
  Packs/CommvaultSecurityIQ/Integrations/CommvaultSecurityIQ/CommvaultSecurityIQ.yml
  Packs/CommvaultSecurityIQ/ReleaseNotes/1_1_2.md
  Packs/CommvaultSecurityIQ/pack_metadata.json
Labels: docs-approved

#37607 Parse emails update docker image
  Packs/CommonScripts/ReleaseNotes/1_17_2.md
  Packs/CommonScripts/Scripts/ParseEmailFilesV2/ParseEmailFilesV2.yml
  Packs/CommonScripts/pack_metadata.json
Labels: docs-approved

#37578 Append get_asset_details_command
  Packs/Core/Integrations/CortexCoreIR/CortexCoreIR.py
  Packs/Core/Integrations/CortexCoreIR/CortexCoreIR.yml
  Packs/Core/Integrations/CortexCoreIR/CortexCoreIR_test.py
  Packs/Core/Integrations/CortexCoreIR/README.md
  Packs/Core/Integrations/CortexCoreIR/command_examples
  Packs/Core/ReleaseNotes/3_2_1.md
  Packs/Core/pack_metadata.json
Labels: docs-approved

#37606 [EDL] update XSIAM prefix
  Packs/EDL/Integrations/EDL/README.md
Labels: docs-approved, bypass.url

#37440 Profilers
  Packs/Base/ReleaseNotes/1_38_1.md
  Packs/Base/Scripts/CommonServerPython/CommonServerPython.py
  Packs/Base/pack_metadata.json
Labels: docs-approved

#37250 Enhance core run script execute commands
  Packs/ApiModules/Scripts/CoreIRApiModule/CoreIRApiModule.py
  Packs/ApiModules/Scripts/CoreIRApiModule/CoreIRApiModule_test.py
  Packs/Core/Integrations/CortexCoreIR/CortexCoreIR.yml
  Packs/Core/Integrations/CortexCoreIR/README.md
  Packs/Core/ReleaseNotes/3_2_2.md
  Packs/Core/pack_metadata.json
  Packs/CortexXDR/Integrations/CortexXDRIR/CortexXDRIR.yml
  Packs/CortexXDR/Integrations/CortexXDRIR/README.md
  Packs/CortexXDR/ReleaseNotes/6_1_95.md
  Packs/CortexXDR/pack_metadata.json
  Packs/ctf01/ReleaseNotes/1_0_33.md
  Packs/ctf01/pack_metadata.json
Labels: enhancement, docs-approved, python, ignore-auto-bump-version

#37574 Aud demisto/auto update docker staging branch 76
  Packs/GoogleKubernetesEngine/Integrations/GoogleKubernetesEngine/GoogleKubernetesEngine.yml
  Packs/GoogleKubernetesEngine/ReleaseNotes/1_0_5.md
  Packs/GoogleKubernetesEngine/pack_metadata.json
  Packs/SMIME_Messaging/Integrations/SMIME_Messaging/SMIME_Messaging.yml
  Packs/SMIME_Messaging/ReleaseNotes/2_0_1.md
  Packs/SMIME_Messaging/pack_metadata.json
  Packs/Syslog/Integrations/SyslogSender/SyslogSender.yml
  Packs/Syslog/Integrations/Syslogv2/Syslogv2.yml
  Packs/Syslog/ReleaseNotes/2_0_19.md
  Packs/Syslog/pack_metadata.json
Labels: docs-approved

#37619 demisto/bs4-py3:1.0.0.117152 | 0-100 | PR batch #1/1
  Packs/CommunityCommonScripts/Scripts/MarkdownToHTML/MarkdownToHTML.yml
  Packs/PopularCybersecurityNews/Integrations/PopularNews/PopularNews.yml
  Packs/Symantec_Messaging_Gateway/Integrations/SymantecMessagingGateway/SymantecMessagingGateway.yml
  Packs/Use_Case_Builder/Scripts/UseCaseBuilderMarkdownToHTML/UseCaseBuilderMarkdownToHTML.yml
  Packs/WebScraper/Scripts/WebScraper/WebScraper.yml
Labels: auto-update-docker

#37618 demisto/bs4-tld:1.0.0.117606 | 0-100 | PR batch #1/1
  Packs/CloudIncidentResponse/Scripts/ExtractIndicatorsCloudLogging/ExtractIndicatorsCloudLogging.yml
  Packs/CommonScripts/Scripts/ParseHTMLIndicators/ParseHTMLIndicators.yml
Labels: auto-update-docker

#37617 demisto/office-utils:2.0.0.117810 | 0-100 | PR batch #1/1
  Packs/CommonScripts/Scripts/ConvertFile/ConvertFile.yml
  Packs/CommonScripts/Scripts/ExtractHyperlinksFromOfficeFiles/ExtractHyperlinksFromOfficeFiles.yml
  Packs/CommonScripts/Scripts/ExtractIndicatorsFromWordFile/ExtractIndicatorsFromWordFile.yml
  Packs/CommonScripts/Scripts/ParseWordDoc/ParseWordDoc.yml
Labels: auto-update-docker

#37563 Fix: Updated the parsing logic for the autonomous system indicator to convert the value to a string
  Packs/ApiModules/ReleaseNotes/2_2_31.md
  Packs/ApiModules/Scripts/TAXII2ApiModule/TAXII2ApiModule.py
  Packs/ApiModules/Scripts/TAXII2ApiModule/TAXII2ApiModule.yml
  Packs/ApiModules/Scripts/TAXII2ApiModule/TAXII2ApiModule_test.py
  Packs/ApiModules/pack_metadata.json
  Packs/CommonScripts/ReleaseNotes/1_17_3.md
  Packs/CommonScripts/pack_metadata.json
  Packs/FeedDHS/ReleaseNotes/2_0_47.md
  Packs/FeedDHS/pack_metadata.json
  Packs/FeedGitHub/ReleaseNotes/1_0_13.md
  Packs/FeedGitHub/pack_metadata.json
  Packs/FeedMitreAttackv2/ReleaseNotes/1_1_47.md
  Packs/FeedMitreAttackv2/pack_metadata.json
  Packs/FeedTAXII/ReleaseNotes/1_2_25.md
  Packs/FeedTAXII/pack_metadata.json
  Packs/FeedUnit42v2/ReleaseNotes/1_0_61.md
  Packs/FeedUnit42v2/pack_metadata.json
  Packs/TAXIIServer/ReleaseNotes/2_0_73.md
  Packs/TAXIIServer/pack_metadata.json
  Tests/conf.json
Labels: Contribution, docs-approved, Partner, Contribution Form Filled, Xsoar Support Level, Internal PR, Partner-Approved

#37150 Bug fix/XSUP-43237/JamfProtect next run fix
  Packs/JamfProtect/Integrations/JamfProtectEventCollector/JamfProtectEventCollector.py
  Packs/JamfProtect/Integrations/JamfProtectEventCollector/JamfProtectEventCollector_test.py
  Packs/JamfProtect/ReleaseNotes/1_1_6.md
  Packs/JamfProtect/pack_metadata.json
Labels: docs-approved, release-notes-only

#37621 JAMF - Add Get configuration-profiles-by-id commands
  Packs/jamf/CONTRIBUTORS.json
  Packs/jamf/Integrations/jamfV2/README.md
  Packs/jamf/Integrations/jamfV2/command_examples.txt
  Packs/jamf/Integrations/jamfV2/jamfV2.py
  Packs/jamf/Integrations/jamfV2/jamfV2.yml
  Packs/jamf/Integrations/jamfV2/jamfV2_test.py
  Packs/jamf/Integrations/jamfV2/test_data/get_computer_configuration_profiles/get_computer_configuration_profiles_by_id_raw_response.json
  Packs/jamf/Integrations/jamfV2/test_data/get_mobile_configuration_profiles/get_mobile_configuration_profiles_by_id_raw_response.json
  Packs/jamf/ReleaseNotes/2_2_4.md
  Packs/jamf/pack_metadata.json
Labels: Contribution, docs-approved, Contribution Form Filled, Community, Xsoar Support Level, Internal PR

#37456 CRTX-133229 MSFT Azure FW Normalizations and Azure Logs Installation Issue Fix
  Packs/AzureFirewall/ModelingRules/AzureFirewall/AzureFirewall.xif
  Packs/AzureFirewall/ModelingRules/AzureFirewall/AzureFirewall.yml
  Packs/AzureFirewall/ModelingRules/AzureFirewall/AzureFirewall_schema.json
  Packs/AzureFirewall/ParsingRules/AzureFirewall/AzureFirewall.xif
  Packs/AzureFirewall/ParsingRules/AzureFirewall/AzureFirewall.yml
  Packs/AzureFirewall/README.md
  Packs/AzureFirewall/ReleaseNotes/1_1_46.md
  Packs/AzureFirewall/pack_metadata.json
  Packs/MicrosoftEntraID/ModelingRules/MicrosoftEntraID/MicrosoftEntraID.xif
  Packs/MicrosoftEntraID/ModelingRules/MicrosoftEntraID/MicrosoftEntraID_schema.json
  Packs/MicrosoftEntraID/ParsingRules/MicrosoftEntraID/MicrosoftEntraID.xif
  Packs/MicrosoftEntraID/README.md
  Packs/MicrosoftEntraID/ReleaseNotes/1_0_3.md
  Packs/MicrosoftEntraID/pack_metadata.json
Labels: docs-approved

#37552 IBMSecurityVerify - xdm.auth.service modification
  Packs/IBMSecurityVerify/ModelingRules/IBMSecurityVerify/IBMSecurityVerify.xif
  Packs/IBMSecurityVerify/ReleaseNotes/1_0_2.md
  Packs/IBMSecurityVerify/pack_metadata.json
Labels: docs-approved

#37351 Nozomi fix lost incidents
  Packs/NozomiNetworks/Integrations/NozomiNetworks/NozomiNetworks.py
  Packs/NozomiNetworks/Integrations/NozomiNetworks/NozomiNetworks.yml
  Packs/NozomiNetworks/Integrations/NozomiNetworks/NozomiNetworks_description.md
  Packs/NozomiNetworks/Integrations/NozomiNetworks/NozomiNetworks_test.py
  Packs/NozomiNetworks/Integrations/NozomiNetworks/test_data/incidents_better_than_time.json
  Packs/NozomiNetworks/ReleaseNotes/1_0_12.md
  Packs/NozomiNetworks/pack_metadata.json
Labels: Contribution, docs-approved, Partner, post-demo, Contribution Form Filled, Partner Support Level, External PR, Partner-Approved

#37620 Aud demisto/auto update docker staging branch 77
  Packs/CloudIncidentResponse/ReleaseNotes/1_0_21.md
  Packs/CloudIncidentResponse/Scripts/ExtractIndicatorsCloudLogging/ExtractIndicatorsCloudLogging.yml
  Packs/CloudIncidentResponse/pack_metadata.json
  Packs/CommonScripts/ReleaseNotes/1_17_4.md
  Packs/CommonScripts/Scripts/ConvertFile/ConvertFile.yml
  Packs/CommonScripts/Scripts/ExtractHyperlinksFromOfficeFiles/ExtractHyperlinksFromOfficeFiles.yml
  Packs/CommonScripts/Scripts/ExtractIndicatorsFromWordFile/ExtractIndicatorsFromWordFile.yml
  Packs/CommonScripts/Scripts/ParseHTMLIndicators/ParseHTMLIndicators.yml
  Packs/CommonScripts/Scripts/ParseWordDoc/ParseWordDoc.yml
  Packs/CommonScripts/pack_metadata.json
  Packs/CommunityCommonScripts/ReleaseNotes/1_3_7.md
  Packs/CommunityCommonScripts/Scripts/MarkdownToHTML/MarkdownToHTML.yml
  Packs/CommunityCommonScripts/pack_metadata.json
  Packs/PopularCybersecurityNews/Integrations/PopularNews/PopularNews.yml
  Packs/PopularCybersecurityNews/ReleaseNotes/1_0_8.md
  Packs/PopularCybersecurityNews/pack_metadata.json
  Packs/Symantec_Messaging_Gateway/Integrations/SymantecMessagingGateway/SymantecMessagingGateway.yml
  Packs/Symantec_Messaging_Gateway/ReleaseNotes/1_0_18.md
  Packs/Symantec_Messaging_Gateway/pack_metadata.json
  Packs/Use_Case_Builder/ReleaseNotes/1_0_10.md
  Packs/Use_Case_Builder/Scripts/UseCaseBuilderMarkdownToHTML/UseCaseBuilderMarkdownToHTML.yml
  Packs/Use_Case_Builder/pack_metadata.json
  Packs/WebScraper/ReleaseNotes/1_0_2.md
  Packs/WebScraper/Scripts/WebScraper/WebScraper.yml
  Packs/WebScraper/pack_metadata.json
Labels: docs-approved

#37623 demisto-sdk-release 1.33.0
  poetry.lock
  pyproject.toml
Labels: docs-approved

#37628 Nozomi fix lost incidents
  Packs/NozomiNetworks/Integrations/NozomiNetworks/NozomiNetworks.py
  Packs/NozomiNetworks/Integrations/NozomiNetworks/NozomiNetworks.yml
  Packs/NozomiNetworks/Integrations/NozomiNetworks/NozomiNetworks_description.md
  Packs/NozomiNetworks/Integrations/NozomiNetworks/NozomiNetworks_test.py
  Packs/NozomiNetworks/Integrations/NozomiNetworks/test_data/incidents_better_than_time.json
  Packs/NozomiNetworks/ReleaseNotes/1_0_12.md
  Packs/NozomiNetworks/pack_metadata.json
Labels: Contribution, docs-approved, Partner, post-demo, Contribution Form Filled, Partner Support Level, Internal PR, Partner-Approved

#37163 Taxii Feed bug
  Packs/FeedTAXII/Integrations/FeedTAXII/FeedTAXII.py
  Packs/FeedTAXII/Integrations/FeedTAXII/FeedTAXII_test.py
  Packs/FeedTAXII/Integrations/FeedTAXII/test_data/StixDecodeTest/domain-stix-ioc-result.json
  Packs/FeedTAXII/Integrations/FeedTAXII/test_data/StixDecodeTest/domain-stix-ioc.xml
  Packs/FeedTAXII/Integrations/FeedTAXII/test_data/StixDecodeTest/email-stix-ioc-result.json
  Packs/FeedTAXII/Integrations/FeedTAXII/test_data/StixDecodeTest/email-stix-ioc.xml
  Packs/FeedTAXII/Integrations/FeedTAXII/test_data/StixDecodeTest/file-stix-ioc-result.json
  Packs/FeedTAXII/Integrations/FeedTAXII/test_data/StixDecodeTest/file-stix-ioc.xml
  Packs/FeedTAXII/Integrations/FeedTAXII/test_data/StixDecodeTest/ip-stix-ioc-result.json
  Packs/FeedTAXII/Integrations/FeedTAXII/test_data/StixDecodeTest/ip-stix-ioc.xml
  Packs/FeedTAXII/Integrations/FeedTAXII/test_data/StixDecodeTest/ipv6-stix-ioc-result.json
  Packs/FeedTAXII/Integrations/FeedTAXII/test_data/StixDecodeTest/ipv6-stix-ioc.xml
  Packs/FeedTAXII/Integrations/FeedTAXII/test_data/StixDecodeTest/url-stix-ioc-result.json
  Packs/FeedTAXII/Integrations/FeedTAXII/test_data/StixDecodeTest/url-stix-ioc.xml
  Packs/FeedTAXII/ReleaseNotes/1_2_26.md
  Packs/FeedTAXII/pack_metadata.json
Labels: docs-approved, ForceMerge

#37244 [ASM] EXPANDR-11761 - Update Remediation Guidance
  Packs/CortexAttackSurfaceManagement/Playbooks/Cortex_ASM_-_Remediation_Guidance.yml
  Packs/CortexAttackSurfaceManagement/ReleaseNotes/1_7_61.md
  Packs/CortexAttackSurfaceManagement/pack_metadata.json
Labels: Contribution, docs-approved, Contribution Form Filled, Community, Xsoar Support Level, External PR, Security Review, Security Approved

#37634 [ASM] EXPANDR-11761 - Update Remediation Guidance
  Packs/CortexAttackSurfaceManagement/Playbooks/Cortex_ASM_-_Remediation_Guidance.yml
  Packs/CortexAttackSurfaceManagement/ReleaseNotes/1_7_61.md
  Packs/CortexAttackSurfaceManagement/pack_metadata.json
Labels: Contribution, docs-approved, Contribution Form Filled, Community, Xsoar Support Level, Security Review, Internal PR, Security Approved

#37554 Securonix Release 2.0.23
  Packs/Securonix/Classifiers/classifier-Securonix_Incident_-_Incoming_Mapper.json
  Packs/Securonix/IncidentFields/incidentfield-Securonix-Policy-Stages.json
  Packs/Securonix/Integrations/Securonix/README.md
  Packs/Securonix/Integrations/Securonix/Securonix.py
  Packs/Securonix/Integrations/Securonix/Securonix.yml
  Packs/Securonix/Integrations/Securonix/Securonix_test.py
  Packs/Securonix/Integrations/Securonix/test_data/response_constants.py
  Packs/Securonix/Integrations/Securonix/test_data/result_constants.py
  Packs/Securonix/Layouts/layoutscontainer-Securonix_Incident_information.json
  Packs/Securonix/ReleaseNotes/2_0_23.md
  Packs/Securonix/pack_metadata.json
Labels: Contribution, Partner, post-demo, Contribution Form Filled, Partner Support Level, External PR, Security Review, Partner-Approved, Security Approved

#37290 Add Support for Panorama/PAN-OS Master Key Rotation
  Packs/PAN-OS/Integrations/Panorama/Panorama.py
  Packs/PAN-OS/Integrations/Panorama/Panorama.yml
  Packs/PAN-OS/Integrations/Panorama/Panorama_description.md
  Packs/PAN-OS/Integrations/Panorama/Panorama_test.py
  Packs/PAN-OS/Integrations/Panorama/README.md
  Packs/PAN-OS/Integrations/Panorama/command_examples.txt
  Packs/PAN-OS/Integrations/Panorama/test_data/create_master_key.xml
  Packs/PAN-OS/Integrations/Panorama/test_data/get_master_key.xml
  Packs/PAN-OS/ReleaseNotes/2_3_0.md
  Packs/PAN-OS/TestPlaybooks/playbook-palo_alto_firewall_test_pb.yml
  Packs/PAN-OS/TestPlaybooks/playbook-palo_alto_panorama_test_pb.yml
  Packs/PAN-OS/pack_metadata.json
Labels: enhancement, docs-approved, python, ForceMerge, ignore-auto-bump-version, sync-gsm

#37638 Securonix Release 2.0.23
  Packs/Securonix/Classifiers/classifier-Securonix_Incident_-_Incoming_Mapper.json
  Packs/Securonix/IncidentFields/incidentfield-Securonix-Policy-Stages.json
  Packs/Securonix/Integrations/Securonix/README.md
  Packs/Securonix/Integrations/Securonix/Securonix.py
  Packs/Securonix/Integrations/Securonix/Securonix.yml
  Packs/Securonix/Integrations/Securonix/Securonix_test.py
  Packs/Securonix/Integrations/Securonix/test_data/response_constants.py
  Packs/Securonix/Integrations/Securonix/test_data/result_constants.py
  Packs/Securonix/Layouts/layoutscontainer-Securonix_Incident_information.json
  Packs/Securonix/ReleaseNotes/2_0_23.md
  Packs/Securonix/pack_metadata.json
Labels: Contribution, docs-approved, Partner, post-demo, Contribution Form Filled, Partner Support Level, Security Review, Internal PR, Partner-Approved, Security Approved

#37145 Ciac 11988 refactor update remote system command xdrir
  Packs/ApiModules/ReleaseNotes/2_2_31.md
  Packs/ApiModules/ReleaseNotes/2_2_32.md
  Packs/ApiModules/Scripts/CoreIRApiModule/CoreIRApiModule.py
  Packs/ApiModules/Scripts/CoreIRApiModule/CoreIRApiModule_test.py
  Packs/ApiModules/pack_metadata.json
  Packs/Core/ReleaseNotes/3_2_3.md
  Packs/Core/pack_metadata.json
  Packs/CortexXDR/Integrations/CortexXDRIR/CortexXDRIR.py
  Packs/CortexXDR/Integrations/CortexXDRIR/CortexXDRIR_test.py
  Packs/CortexXDR/ReleaseNotes/6_1_95.md
  Packs/CortexXDR/ReleaseNotes/6_1_96.md
  Packs/CortexXDR/pack_metadata.json
  Packs/ctf01/ReleaseNotes/1_0_34.md
  Packs/ctf01/pack_metadata.json
Labels: docs-approved

#37587 fixed an issue to rasterize urls as a list
  Packs/rasterize/Integrations/rasterize/rasterize.yml
  Packs/rasterize/ReleaseNotes/2_0_31.md
  Packs/rasterize/pack_metadata.json
Labels: docs-approved, ForceMerge

#37245 Change Automation Insights dashboard default timeframe to 6 months
  Packs/CommonDashboards/Dashboards/XSOAR_Automation_Insights.json
  Packs/CommonDashboards/ReleaseNotes/1_7_7.md
  Packs/CommonDashboards/ReleaseNotes/1_7_8.md
  Packs/CommonDashboards/pack_metadata.json
Labels: Contribution, docs-approved, Contribution Form Filled, Community, Xsoar Support Level, External PR, Security Review, Security Approved

#37562 TIM \ REGEX \ URLFormatter \ Allow parenthesis in the query part of the URL
  Packs/ApiModules/ReleaseNotes/2_2_33.md
  Packs/ApiModules/Scripts/FormatURLApiModule/FormatURLApiModule.py
  Packs/ApiModules/Scripts/FormatURLApiModule/FormatURLApiModule_test.py
  Packs/ApiModules/Scripts/FormatURLApiModule/README.md
  Packs/ApiModules/pack_metadata.json
  Packs/CommonScripts/ReleaseNotes/1_17_5.md
  Packs/CommonScripts/Scripts/FormatURL/FormatURL.py
  Packs/CommonScripts/pack_metadata.json
  Packs/CommonTypes/IndicatorTypes/reputation-url.json
  Packs/CommonTypes/ReleaseNotes/3_6_1.md
  Packs/CommonTypes/pack_metadata.json
  Packs/Phishing/ReleaseNotes/3_6_28.md
  Packs/Phishing/pack_metadata.json
Labels: docs-approved

#37651 fixed rn
  Packs/rasterize/ReleaseNotes/2_0_31.md
Labels: docs-approved

#37445 Fix README formatting/typos
  Packs/Zoom/Integrations/Zoom/README.md
  Packs/Zoom/ReleaseNotes/1_6_18.md
  Packs/Zoom/pack_metadata.json
Labels: Contribution, docs-approved, Contribution Form Filled, Community, Xsoar Support Level, External PR

#37639 Aud demisto/auto update docker staging branch 79
  Packs/Base/ReleaseNotes/1_38_2.md
  Packs/Base/Scripts/SanePdfReport/SanePdfReport.yml
  Packs/Base/pack_metadata.json
  Packs/CommonScripts/ReleaseNotes/1_17_6.md
  Packs/CommonScripts/Scripts/AquatoneDiscoverV2/AquatoneDiscoverV2.yml
  Packs/CommonScripts/Scripts/ExportToXLSX/ExportToXLSX.yml
  Packs/CommonScripts/Scripts/ReadQRCode/ReadQRCode.yml
  Packs/CommonScripts/pack_metadata.json
  Packs/CortexDataLake/Integrations/CortexDataLake/CortexDataLake.yml
  Packs/CortexDataLake/ReleaseNotes/1_4_15.md
  Packs/CortexDataLake/pack_metadata.json
  Packs/GoogleBigQuery/Integrations/GoogleBigQuery/GoogleBigQuery.yml
  Packs/GoogleBigQuery/ReleaseNotes/1_1_10.md
  Packs/GoogleBigQuery/pack_metadata.json
  Packs/GoogleCloudTranslate/Integrations/GoogleCloudTranslate/GoogleCloudTranslate.yml
  Packs/GoogleCloudTranslate/ReleaseNotes/1_0_12.md
  Packs/GoogleCloudTranslate/pack_metadata.json
  Packs/GoogleKeyManagementService/Integrations/GoogleKeyManagementService/GoogleKeyManagementService.yml
  Packs/GoogleKeyManagementService/ReleaseNotes/1_0_27.md
  Packs/GoogleKeyManagementService/pack_metadata.json
  Packs/GraphQL/Integrations/GraphQL/GraphQL.yml
  Packs/GraphQL/ReleaseNotes/1_0_19.md
  Packs/GraphQL/pack_metadata.json
  Packs/KeeperSecurity/Integrations/KeeperSecurity/KeeperSecurity.yml
  Packs/KeeperSecurity/ReleaseNotes/1_0_2.md
  Packs/KeeperSecurity/pack_metadata.json
  Packs/OracleCloudInfrastructure/Integrations/OracleCloudInfrastructureEventCollector/OracleCloudInfrastructureEventCollector.yml
  Packs/OracleCloudInfrastructure/ReleaseNotes/1_0_27.md
  Packs/OracleCloudInfrastructure/pack_metadata.json
  Packs/TaniumThreatResponse/Integrations/TaniumThreatResponseV2/TaniumThreatResponseV2.yml
  Packs/TaniumThreatResponse/ReleaseNotes/2_2_18.md
  Packs/TaniumThreatResponse/pack_metadata.json
  Packs/Tidy/Integrations/Tidy/Tidy.yml
  Packs/Tidy/ReleaseNotes/1_0_12.md
  Packs/Tidy/pack_metadata.json
Labels: docs-approved, auto-update-docker

#37653 ParseEmailFilesV2 - update docker
  Packs/CommonScripts/ReleaseNotes/1_17_7.md
  Packs/CommonScripts/Scripts/ParseEmailFilesV2/ParseEmailFilesV2.yml
  Packs/CommonScripts/pack_metadata.json
Labels: docs-approved

#37654 Improve CS Falcon documentation
  Packs/CrowdStrikeFalcon/Integrations/CrowdStrikeFalcon/README.md
Labels: docs-approved

#37240 Feature: Infoblox manage session with cookies in integration storage
  Packs/Infoblox/CONTRIBUTORS.json
  Packs/Infoblox/Integrations/Infoblox/Infoblox.py
  Packs/Infoblox/Integrations/Infoblox/Infoblox.yml
  Packs/Infoblox/ReleaseNotes/1_1_3.md
  Packs/Infoblox/ReleaseNotes/1_1_4.md
  Packs/Infoblox/pack_metadata.json
Labels: Contribution, docs-approved, Partner, post-demo, Contribution Form Filled, pending-contributor, Xsoar Support Level, External PR

#37273 Fix 'upload file' test playbook
  Packs/DemistoRESTAPI/Integrations/CoreRESTAPI/CoreRESTAPI.yml
  Packs/DemistoRESTAPI/Integrations/DemistoRESTAPI/DemistoRESTAPI.yml
  Packs/DemistoRESTAPI/ReleaseNotes/1_3_64.md
  Packs/DemistoRESTAPI/TestPlaybooks/playbook-UploadFile-test.yml
  Packs/DemistoRESTAPI/pack_metadata.json
  Packs/Grafana/TestPlaybooks/Grafana-Test.yml
  Tests/conf.json
Labels: docs-approved, ForceMerge, sync-gsm

#37629 Excessive user account lockouts playbook
  Packs/Core/.pack-ignore
  Packs/Core/Playbooks/playbook-Excessive_User_Account_Lockouts.yml
  Packs/Core/Playbooks/playbook-Excessive_User_Account_Lockouts_README.md
  Packs/Core/ReleaseNotes/3_2_4.md
  Packs/Core/Triggers/Trigger_-_Excessive_User_Account_Lockkouts.json
  Packs/Core/doc_files/Excessive_User_Account_Lockouts.png
  Packs/Core/pack_metadata.json
Labels: docs-approved

#37663 update validation config.toml
  validation_config.toml
Labels: docs-approved

#37278 Implement additional parameters for restore requests incidents
  Packs/CheckPointHEC/Integrations/CheckPointHEC/CheckPointHEC.py
  Packs/CheckPointHEC/Integrations/CheckPointHEC/CheckPointHEC.yml
  Packs/CheckPointHEC/Integrations/CheckPointHEC/README.md
  Packs/CheckPointHEC/ReleaseNotes/1_1_6.md
  Packs/CheckPointHEC/pack_metadata.json
Labels: Contribution, docs-approved, Partner, post-demo, Contribution Form Filled, Partner Support Level, External PR, Partner-Approved

#37674 move some validations to warning
  validation_config.toml
Labels: docs-approved

#37640 Rasterize - Fix timeout issue
  Packs/rasterize/Integrations/rasterize/rasterize.py
  Packs/rasterize/ReleaseNotes/2_0_32.md
  Packs/rasterize/pack_metadata.json
Labels: docs-approved, ForceMerge

#37201 EWSv2, EWSo365: Skip-on-error skips all exceptions
  Packs/MicrosoftExchangeOnPremise/Integrations/EWSv2/EWSv2.py
  Packs/MicrosoftExchangeOnPremise/ReleaseNotes/2_1_17.md
  Packs/MicrosoftExchangeOnPremise/pack_metadata.json
  Packs/MicrosoftExchangeOnline/Integrations/EWSO365/EWSO365.py
  Packs/MicrosoftExchangeOnline/ReleaseNotes/1_5_22.md
  Packs/MicrosoftExchangeOnline/pack_metadata.json
Labels: docs-approved, ForceMerge

#37668 Aud demisto/auto update docker staging branch 81
  Packs/VMware/Integrations/VMware/VMware.yml
  Packs/VMware/ReleaseNotes/1_2_11.md
  Packs/VMware/pack_metadata.json
  Packs/WindowsForensics/ReleaseNotes/1_0_8.md
  Packs/WindowsForensics/Scripts/Etl2Pcap/Etl2Pcap.yml
  Packs/WindowsForensics/pack_metadata.json
  Packs/dnstwist/Integrations/dnstwist/dnstwist.yml
  Packs/dnstwist/ReleaseNotes/1_1_14.md
  Packs/dnstwist/pack_metadata.json
Labels: docs-approved

#37686 add RN107 to warnings
  validation_config.toml
Labels: docs-approved

#37645 Valid accounts guest user invitation
  Packs/Core/Playbooks/playbook-Successful_guest_user_invitation.yml
  Packs/Core/Playbooks/playbook-Successful_guest_user_invitation_README.md
  Packs/Core/ReleaseNotes/3_2_5.md
  Packs/Core/Triggers/Trigger_-_Successful_guest_user_invitation.json
  Packs/Core/doc_files/Successful_guest_user_invitation.png
  Packs/Core/pack_metadata.json
Labels: docs-approved, bypass.url

#37417 Taxii str bug
  Packs/FeedTAXII/Integrations/FeedTAXII2/FeedTAXII2.py
  Packs/FeedTAXII/ReleaseNotes/1_2_27.md
  Packs/FeedTAXII/pack_metadata.json
Labels: docs-approved

#37630 Aud demisto/auto update docker staging branch 78
  Packs/FiltersAndTransformers/ReleaseNotes/1_2_86.md
  Packs/FiltersAndTransformers/Scripts/DateStringToISOFormat/DateStringToISOFormat.py
  Packs/FiltersAndTransformers/Scripts/DateStringToISOFormat/DateStringToISOFormat.yml
  Packs/FiltersAndTransformers/Scripts/FormattedDateToEpoch/FormattedDateToEpoch.py
  Packs/FiltersAndTransformers/Scripts/FormattedDateToEpoch/FormattedDateToEpoch.yml
  Packs/FiltersAndTransformers/Scripts/TimeComponents/TimeComponents.py
  Packs/FiltersAndTransformers/Scripts/TimeComponents/TimeComponents.yml
  Packs/FiltersAndTransformers/Scripts/TimeComponents/TimeComponents_test.py
  Packs/FiltersAndTransformers/pack_metadata.json
  Packs/FireEyeETP/Integrations/FireEyeETPEventCollector/FireEyeETPEventCollector.yml
  Packs/FireEyeETP/Integrations/FireEyeETPEventCollector/FireEyeETPEventCollector_test.py
  Packs/FireEyeETP/ReleaseNotes/2_0_2.md
  Packs/FireEyeETP/pack_metadata.json
  Packs/Forescout/Integrations/Forescout/Forescout.py
  Packs/Forescout/Integrations/Forescout/Forescout.yml
  Packs/Forescout/ReleaseNotes/1_0_11.md
  Packs/Forescout/pack_metadata.json
  Packs/cisco-ise/Integrations/cisco-ise/cisco-ise.py
  Packs/cisco-ise/Integrations/cisco-ise/cisco-ise.yml
  Packs/cisco-ise/Integrations/cisco-ise/cisco-ise_test.py
  Packs/cisco-ise/ReleaseNotes/1_0_22.md
  Packs/cisco-ise/pack_metadata.json
  Tests/docker_native_image_config.json
Labels: docs-approved, auto-update-docker

#37661 Box event collector fix
  Packs/Box/Integrations/BoxEventsCollector/BoxEventsCollector.py
  Packs/Box/Integrations/BoxEventsCollector/BoxEventsCollector.yml
  Packs/Box/Integrations/BoxV2/BoxV2.py
  Packs/Box/ReleaseNotes/3_2_6.md
  Packs/Box/pack_metadata.json
  Tests/conf.json
Labels: docs-approved

#37689 Bugfix/netskope v2 manual pagination
  Packs/Netskope/Integrations/NetskopeAPIv2/NetskopeAPIv2.py
  Packs/Netskope/Integrations/NetskopeAPIv2/NetskopeAPIv2.yml
  Packs/Netskope/ReleaseNotes/4_0_2.md
  Packs/Netskope/pack_metadata.json
Labels: Contribution, docs-approved, Contribution Form Filled, Community, Xsoar Support Level, External PR

#37679 Rasterize email output unique file name
  Packs/rasterize/Integrations/rasterize/rasterize.py
  Packs/rasterize/Integrations/rasterize/rasterize.yml
  Packs/rasterize/Integrations/rasterize/rasterize_test.py
  Packs/rasterize/ReleaseNotes/2_0_33.md
  Packs/rasterize/pack_metadata.json
Labels: docs-approved, release-notes-only, ForceMerge

#37691 [IR] Update limit for risky commands
  Packs/ApiModules/ReleaseNotes/2_2_34.md
  Packs/ApiModules/Scripts/CoreIRApiModule/CoreIRApiModule.py
  Packs/ApiModules/pack_metadata.json
  Packs/Core/Integrations/CortexCoreIR/CortexCoreIR.yml
  Packs/Core/Integrations/CortexCoreIR/README.md
  Packs/Core/ReleaseNotes/3_2_6.md
  Packs/Core/pack_metadata.json
  Packs/CortexXDR/Integrations/CortexXDRIR/CortexXDRIR.yml
  Packs/CortexXDR/Integrations/CortexXDRIR/README.md
  Packs/CortexXDR/ReleaseNotes/6_1_97.md
  Packs/CortexXDR/pack_metadata.json
Labels: docs-approved

#37267 Feature/use incydr
  Packs/Code42/.secrets-ignore
  Packs/Code42/Classifiers/classifier-mapper-incoming-Code42.json
  Packs/Code42/Integrations/Code42/Code42.py
  Packs/Code42/Integrations/Code42/Code42.yml
  Packs/Code42/Integrations/Code42/Code42_test.py
  Packs/Code42/Integrations/Code42/README.md
  Packs/Code42/Integrations/Code42/test_data/actor_response.json
  Packs/Code42/Integrations/Code42/test_data/risk_profile_response.json
  Packs/Code42/Integrations/Code42/test_data/rule_response.json
  Packs/Code42/Integrations/Code42/test_data/session_response.json
  Packs/Code42/Integrations/Code42/test_data/session_response_2.json
  Packs/Code42/Integrations/Code42/test_data/session_response_3.json
  Packs/Code42/Integrations/Code42EventCollector/Code42EventCollector.yml
  Packs/Code42/Playbooks/playbook-Code42_Exfiltration_Playbook.yml
  Packs/Code42/Playbooks/playbook-Code42_Exfiltration_Playbook_README.md
  Packs/Code42/ReleaseNotes/6_0_0.json
  Packs/Code42/ReleaseNotes/6_0_0.md
  Packs/Code42/doc_files/Code42_Exfiltration_Playbook.png
  Packs/Code42/pack_metadata.json
Labels: Contribution, docs-approved, Partner, post-demo, Contribution Form Filled, ForceMerge, Partner Support Level, External PR, Security Review, Partner-Approved, Security Approved

#37270 Feature: OpenCTI Improvements
  Packs/OpenCTI/CONTRIBUTORS.json
  Packs/OpenCTI/Integrations/OpenCTI/OpenCTI.py
  Packs/OpenCTI/Integrations/OpenCTI/OpenCTI.yml
  Packs/OpenCTI/Integrations/OpenCTI/OpenCTI_description.md
  Packs/OpenCTI/Integrations/OpenCTI/OpenCTI_test.py
  Packs/OpenCTI/Integrations/OpenCTI/README.md
  Packs/OpenCTI/Integrations/OpenCTI/command_examples
  Packs/OpenCTI/Integrations/OpenCTI/test_data/data.py
  Packs/OpenCTI/Playbooks/OpenCTI_-_Create_Indicator.yml
  Packs/OpenCTI/Playbooks/OpenCTI_-_Create_Indicator_README.md
  Packs/OpenCTI/README.md
  Packs/OpenCTI/ReleaseNotes/2_0_0.json
  Packs/OpenCTI/ReleaseNotes/2_0_0.md
  Packs/OpenCTI/TestPlaybooks/playbook-OpenCTI_Test.yml
  Packs/OpenCTI/pack_metadata.json
Labels: Contribution, docs-approved, Partner, ready-for-instance-test, post-demo, Contribution Form Filled, Xsoar Support Level, External PR

#37609 Fix ms defender for endpoint
  Packs/MicrosoftDefenderAdvancedThreatProtection/Integrations/MicrosoftDefenderAdvancedThreatProtection/MicrosoftDefenderAdvancedThreatProtection.py
  Packs/MicrosoftDefenderAdvancedThreatProtection/Integrations/MicrosoftDefenderAdvancedThreatProtection/MicrosoftDefenderAdvancedThreatProtection.yml
  Packs/MicrosoftDefenderAdvancedThreatProtection/Integrations/MicrosoftDefenderAdvancedThreatProtection/MicrosoftDefenderAdvancedThreatProtection_description.md
  Packs/MicrosoftDefenderAdvancedThreatProtection/Integrations/MicrosoftDefenderAdvancedThreatProtection/MicrosoftDefenderAdvancedThreatProtection_test.py
  Packs/MicrosoftDefenderAdvancedThreatProtection/ReleaseNotes/1_17_7.json
  Packs/MicrosoftDefenderAdvancedThreatProtection/ReleaseNotes/1_17_7.md
  Packs/MicrosoftDefenderAdvancedThreatProtection/pack_metadata.json
  validation_config.toml
Labels: docs-approved

#37616 MS Teams - Auto-resetting the token info when switching between authentication types
  Packs/MicrosoftTeams/Integrations/MicrosoftTeams/MicrosoftTeams.py
  Packs/MicrosoftTeams/Integrations/MicrosoftTeams/MicrosoftTeams.yml
  Packs/MicrosoftTeams/Integrations/MicrosoftTeams/MicrosoftTeams_description.md
  Packs/MicrosoftTeams/Integrations/MicrosoftTeams/MicrosoftTeams_test.py
  Packs/MicrosoftTeams/Integrations/MicrosoftTeams/README.md
  Packs/MicrosoftTeams/ReleaseNotes/1_5_9.md
  Packs/MicrosoftTeams/pack_metadata.json
Labels: docs-approved

#37672 Enhancement for ServiceNow - Transactions logs mapping
  Packs/ServiceNow/ModelingRules/ServiceNow/ServiceNow.xif
  Packs/ServiceNow/ModelingRules/ServiceNow/ServiceNow_schema.json
  Packs/ServiceNow/README.md
  Packs/ServiceNow/ReleaseNotes/2_7_2.md
  Packs/ServiceNow/pack_metadata.json
Labels: docs-approved

#37701 Profiler patch
  Packs/Base/ReleaseNotes/1_38_4.md
  Packs/Base/Scripts/CommonServerPython/CommonServerPython.py
  Packs/Base/pack_metadata.json
Labels: docs-approved

#37656 MongoDB Atlas Mapping
  Packs/MongoDBAtlas/ModelingRules/MongoDBAtlas/MongoDBAtlas.xif
  Packs/MongoDBAtlas/ModelingRules/MongoDBAtlas/MongoDBAtlas.yml
  Packs/MongoDBAtlas/ModelingRules/MongoDBAtlas/MongoDBAtlas_schema.json
  Packs/MongoDBAtlas/README.md
  Packs/MongoDBAtlas/ReleaseNotes/1_0_1.md
  Packs/MongoDBAtlas/pack_metadata.json
Labels: docs-approved

#37161 [ZeroFox] Improve error doc
  Packs/ZeroFox/Integrations/ZeroFox/ZeroFox.py
  Packs/ZeroFox/Integrations/ZeroFox/ZeroFox.yml
  Packs/ZeroFox/Integrations/ZeroFox/ZeroFox_test.py
  Packs/ZeroFox/ReleaseNotes/1_3_5.md
  Packs/ZeroFox/pack_metadata.json
Labels: Contribution, docs-approved, Partner, ready-for-instance-test, post-demo, Contribution Form Filled, Partner Support Level, External PR, Partner-Approved

#37694 ThreatConnect Feed - Fix Authorization header generation
  Packs/FeedThreatConnect/Integrations/FeedThreatConnect/FeedThreatConnect.py
  Packs/FeedThreatConnect/ReleaseNotes/2_1_25.md
  Packs/FeedThreatConnect/pack_metadata.json
Labels: docs-approved

#37362 CyberArk - Integration rename and consolidation
  Packs/CyberArkEPV/README.md
  Packs/CyberArkEPV/ReleaseNotes/1_0_4.md
  Packs/CyberArkEPV/doc_files/XSIAM.xsl
  Packs/CyberArkEPV/pack_metadata.json
Labels: Contribution, docs-approved, Partner, Contribution Form Filled, Xsoar Support Level, External PR

#37690 update links last batch
  Packs/TrendMicroCAS/Playbooks/playbook-Trend_Micro_CAS_-_Indicators_Hunting.yml
  Packs/TrendMicroCAS/ReleaseNotes/1_1_9.md
  Packs/TrendMicroCAS/pack_metadata.json
  Packs/Troubleshoot/Scripts/CertificatesTroubleshoot/README.md
  Packs/Twitter/TestPlaybooks/playbook-Test_Twitter_v2.yml
  Packs/Use_Case_Builder/IncidentFields/incidentfield-Use_Case_Ingestion_Best_Practice.json
  Packs/Use_Case_Builder/IncidentFields/incidentfield-Use_Case_TIM_Best_Practice.json
  Packs/Use_Case_Builder/Playbooks/Use_Case_Builder.yml
  Packs/Use_Case_Builder/ReleaseNotes/1_0_12.md
  Packs/Use_Case_Builder/pack_metadata.json
  Packs/VMware/TestPlaybooks/playbook-VMWare_Test.yml
  Packs/Vectra/Integrations/Vectra/README.md
  Packs/VectraXDR/Integrations/VectraXDR/README.md
  Packs/VectraXDR/Playbooks/playbook-Dispatch_Incident_-_Vectra_XDR.yml
  Packs/VectraXDR/Playbooks/playbook-Process_Incident_-_Vectra_XDR.yml
  Packs/VectraXDR/ReleaseNotes/1_0_8.md
  Packs/VectraXDR/pack_metadata.json
  Packs/Vectra_AI/Integrations/VectraDetect/README.md
  Packs/Vectra_AI/Playbooks/playbook-Close_Duplicate_XSOAR_Incidents_-_Vectra_Detect.yml
  Packs/Vectra_AI/Playbooks/playbook-Dispatch_Incident_-_Vectra_Detect.yml
  Packs/Vectra_AI/Playbooks/playbook-Process_Incident_-_Vectra_Detect.yml
  Packs/Vectra_AI/ReleaseNotes/2_0_2.md
  Packs/Vectra_AI/pack_metadata.json
  Packs/Veeam/Playbooks/Veeam_Start_Configuration_Backup.yml
  Packs/Veeam/Playbooks/Veeam_Start_Instant_VM_Recovery_Automatically.yml
  Packs/Veeam/Playbooks/Veeam_Start_Instant_VM_Recovery_Manually.yml
  Packs/Veeam/ReleaseNotes/1_0_5.md
  Packs/Veeam/pack_metadata.json
  Packs/Venafi/TestPlaybooks/VenafiV2_Test.yml
  Packs/Whois/TestPlaybooks/Whois_A_new_layout_implemented_with_python-whois_service.yml
  Packs/Zendesk/TestPlaybooks/Zendesk_V2_TEST.yml
  Packs/epo/TestPlaybooks/playbook-epo_v2_Test.yml
  Packs/qualys/TestPlaybooks/QualysVulnerabilityManagement-Test.yml
  Packs/rasterize/Integrations/rasterize/README.md
  Packs/rasterize/Integrations/rasterize/rasterize_description.md
  Packs/rasterize/ReleaseNotes/2_0_34.md
  Packs/rasterize/pack_metadata.json
Labels: docs-approved, ForceMerge, bypass.url

#37699 Deprecate permitted_notifications in SlackV3
  Packs/Slack/.pack-ignore
  Packs/Slack/Integrations/SlackV3/README.md
  Packs/Slack/Integrations/SlackV3/SlackV3.yml
  Packs/Slack/ReleaseNotes/3_5_4.md
  Packs/Slack/pack_metadata.json
Labels: docs-approved, bypass.url

#37741 Box v2 fix
  Packs/Box/Integrations/BoxV2/BoxV2.py
  Packs/Box/Integrations/BoxV2/BoxV2_test.py
  Packs/Box/ReleaseNotes/3_2_7.md
  Packs/Box/pack_metadata.json
Labels: docs-approved

#37749 Revert "Feature/use incydr"
  Packs/Code42/.secrets-ignore
  Packs/Code42/Classifiers/classifier-mapper-incoming-Code42.json
  Packs/Code42/Integrations/Code42/Code42.py
  Packs/Code42/Integrations/Code42/Code42.yml
  Packs/Code42/Integrations/Code42/Code42_test.py
  Packs/Code42/Integrations/Code42/README.md
  Packs/Code42/Integrations/Code42/test_data/actor_response.json
  Packs/Code42/Integrations/Code42/test_data/risk_profile_response.json
  Packs/Code42/Integrations/Code42/test_data/rule_response.json
  Packs/Code42/Integrations/Code42/test_data/session_response.json
  Packs/Code42/Integrations/Code42/test_data/session_response_2.json
  Packs/Code42/Integrations/Code42/test_data/session_response_3.json
  Packs/Code42/Integrations/Code42EventCollector/Code42EventCollector.yml
  Packs/Code42/Playbooks/playbook-Code42_Exfiltration_Playbook.yml
  Packs/Code42/Playbooks/playbook-Code42_Exfiltration_Playbook_README.md
  Packs/Code42/ReleaseNotes/6_0_0.json
  Packs/Code42/ReleaseNotes/6_0_0.md
  Packs/Code42/doc_files/Code42_Exfiltration_Playbook.png
  Packs/Code42/pack_metadata.json
Labels: ForceMerge

#37595 Connection timeout fix
  Packs/CybleThreatIntel/Integrations/CybleThreatIntel/CybleThreatIntel.py
  Packs/CybleThreatIntel/Integrations/CybleThreatIntel/CybleThreatIntel.yml
  Packs/CybleThreatIntel/Integrations/CybleThreatIntel/CybleThreatIntel_test.py
  Packs/CybleThreatIntel/ReleaseNotes/2_0_24.md
  Packs/CybleThreatIntel/pack_metadata.json
Labels: Contribution, docs-approved, Partner, Contribution Form Filled, Partner Support Level, External PR, Partner-Approved, TIM Review

#37746 Update the security reviewer
  .github/content_roles.json
Labels: docs-approved

#37700 fix the tpb
  Packs/AWS-EC2/TestPlaybooks/playbook-AWS-EC2_test.yml
  Tests/conf.json
Labels: docs-approved, sync-gsm

#37736 Added a fix to the source_user parsing
  Packs/PrismaAccess/Integrations/PrismaSASE/PrismaSASE.py
  Packs/PrismaAccess/Integrations/PrismaSASE/PrismaSASE_test.py
  Packs/PrismaAccess/ReleaseNotes/2_1_12.md
  Packs/PrismaAccess/pack_metadata.json
Labels: docs-approved

#37667 revert backoff factor
  Packs/FeedAzure/Integrations/FeedAzure/FeedAzure.py
  Packs/FeedAzure/ReleaseNotes/1_0_32.md
  Packs/FeedAzure/pack_metadata.json
Labels: docs-approved

#37698 update links betch 1c
  Packs/CommonScripts/ReleaseNotes/1_18_1.md
  Packs/CommonScripts/Scripts/CompareIncidentsLabels/CompareIncidentsLabels.yml
  Packs/CommonScripts/Scripts/CompareIncidentsLabels/README.md
  Packs/CommonScripts/Scripts/CopyContextToField/CopyContextToField.yml
  Packs/CommonScripts/Scripts/CopyContextToField/README.md
  Packs/CommonScripts/Scripts/DeleteContext/DeleteContext.yml
  Packs/CommonScripts/Scripts/DeleteContext/README.md
  Packs/CommonScripts/Scripts/DockerHardeningCheck/DockerHardeningCheck.yml
  Packs/CommonScripts/Scripts/DockerHardeningCheck/README.md
  Packs/CommonScripts/Scripts/ExtractIndicatorsFromTextFile/ExtractIndicatorsFromTextFile.yml
  Packs/CommonScripts/Scripts/ExtractIndicatorsFromTextFile/README.md
  Packs/CommonScripts/Scripts/ExtractIndicatorsFromWordFile/ExtractIndicatorsFromWordFile.yml
  Packs/CommonScripts/Scripts/ExtractIndicatorsFromWordFile/README.md
  Packs/CommonScripts/Scripts/FindIncidentsWithIndicator/FindIncidentsWithIndicator.yml
  Packs/CommonScripts/Scripts/FindIncidentsWithIndicator/README.md
  Packs/CommonScripts/Scripts/FindSimilarIncidentsV2/FindSimilarIncidentsV2.yml
  Packs/CommonScripts/Scripts/FindSimilarIncidentsV2/README.md
  Packs/CommonScripts/Scripts/GetDuplicatesMlv2/GetDuplicatesMlv2.yml
  Packs/CommonScripts/Scripts/IndicatorMaliciousRatioCalculation/IndicatorMaliciousRatioCalculation.yml
  Packs/CommonScripts/Scripts/MarkRelatedIncidents/MarkRelatedIncidents.yml
  Packs/CommonScripts/Scripts/MarkRelatedIncidents/README.md
  Packs/CommonScripts/Scripts/NumberOfPhishingAttemptPerUser/NumberOfPhishingAttemptPerUser.yml
  Packs/CommonScripts/Scripts/NumberOfPhishingAttemptPerUser/README.md
  Packs/CommonScripts/Scripts/RunPollingCommand/RunPollingCommand.yml
  Packs/CommonScripts/Scripts/SearchIncidentsV2/README.md
  Packs/CommonScripts/Scripts/SearchIncidentsV2/SearchIncidentsV2.yml
  Packs/CommonScripts/Scripts/SetAndHandleEmpty/README.md
  Packs/CommonScripts/Scripts/SetAndHandleEmpty/SetAndHandleEmpty.yml
  Packs/CommonScripts/Scripts/SetByIncidentId/README.md
  Packs/CommonScripts/Scripts/SetByIncidentId/SetByIncidentId.yml
  Packs/CommonScripts/TestPlaybooks/DBotUpdateLogoURLPhishing_test.yml
  Packs/CommonScripts/TestPlaybooks/FileCreateAndUploadV2-Test.yml
  Packs/CommonScripts/TestPlaybooks/IsEmailAddressInternal_Test.yml
  Packs/CommonScripts/TestPlaybooks/SetAndHandleEmpty_Test.yml
  Packs/CommonScripts/TestPlaybooks/playbook-DeleteContext-test.yml
  Packs/CommonScripts/TestPlaybooks/playbook-HttpV2-Test.yml
  Packs/CommonScripts/TestPlaybooks/playbook-Test_Delete_Context.yml
  Packs/CommonScripts/pack_metadata.json
  Packs/ContentManagement/Playbooks/playbook-Delete_Custom_Content.yml
  Packs/ContentManagement/Playbooks/playbook-Pull_Request_Creation_-_AzureDevOps.yml
  Packs/ContentManagement/Playbooks/playbook-Pull_Request_Creation_-_Bitbucket.yml
  Packs/ContentManagement/ReleaseNotes/1_2_26.md
  Packs/ContentManagement/pack_metadata.json
Labels: docs-approved, ForceMerge, bypass.url

#37695 update links batch 1a
  Packs/AHA/TestPlaybooks/AHA_TestPlaybook.yml
  Packs/AWS-EC2/TestPlaybooks/playbook-AWS-EC2_test.yml
  Packs/AWS-EKS/TestPlaybooks/playbook-AWSEKS_Test.yml
  Packs/AWS-IAM/TestPlaybooks/playbook-AWS-IAM-Test.yml
  Packs/AWS_SystemManager/TestPlaybooks/playbook-AWSSystemManager-test.yml
  Packs/AccentureCTI/Playbooks/playbook-ACTI_Block_Indicators_from_an_Incident.yml
  Packs/AccentureCTI/ReleaseNotes/2_2_39.md
  Packs/AccentureCTI/pack_metadata.json
  Packs/Active_Directory_Query/Playbooks/Active_Directory_-_Get_User_Manager_Email.yml
  Packs/Active_Directory_Query/ReleaseNotes/1_6_42.md
  Packs/Active_Directory_Query/TestPlaybooks/IAMInitADUser_-_Test.yml
  Packs/Active_Directory_Query/pack_metadata.json
  Packs/Anomali_ThreatStream/TestPlaybooks/playbook-ThreatStream-Test.yml
  Packs/AnsibleAlibabaCloud/Integrations/AnsibleAlibabaCloud/README.md
  Packs/AnsibleAzure/Integrations/AnsibleAzure/README.md
  Packs/AnsibleCiscoIOS/Integrations/AnsibleCiscoIOS/README.md
  Packs/AnsibleCiscoNXOS/Integrations/AnsibleCiscoNXOS/README.md
  Packs/AnsibleHetznerCloud/Integrations/AnsibleHCloud/README.md
  Packs/AnsibleKubernetes/Integrations/AnsibleKubernetes/README.md
  Packs/AnsibleLinux/Integrations/AnsibleACME/README.md
  Packs/AnsibleLinux/Integrations/AnsibleDNS/README.md
  Packs/AnsibleLinux/Integrations/AnsibleLinux/README.md
  Packs/AnsibleLinux/Integrations/AnsibleOpenSSL/README.md
  Packs/AnsibleMicrosoftWindows/Integrations/AnsibleMicrosoftWindows/README.md
  Packs/AnsibleVMware/Integrations/AnsibleVMware/README.md
  Packs/ArcSightLogger/Integrations/ArcSightLogger/README.md
  Packs/AutoFocus/Playbooks/playbook-Autofocus_-_File_Indicators_Hunting.yml
  Packs/AutoFocus/Playbooks/playbook-Autofocus_-_Traffic_Indicators_Hunting.yml
  Packs/AutoFocus/ReleaseNotes/2_2_8.md
  Packs/AutoFocus/pack_metadata.json
  Packs/Azure-Enrichment-Remediation/Playbooks/playbook-Azure_-_User_Investigation.yml
  Packs/Azure-Enrichment-Remediation/ReleaseNotes/1_1_22.md
  Packs/Azure-Enrichment-Remediation/pack_metadata.json
  Packs/AzureLogAnalytics/TestPlaybooks/playbook-AzureLogAnalytics-test.yml
  Packs/BMCDiscovery/TestPlaybooks/BMC_Discovery_-_Test.yml
  Packs/Base/ReleaseNotes/1_39_1.md
  Packs/Base/Scripts/CreateIndicatorRelationship/CreateIndicatorRelationship.yml
  Packs/Base/Scripts/CreateIndicatorRelationship/README.md
  Packs/Base/Scripts/FindSimilarIncidentsByText/FindSimilarIncidentsByText.yml
  Packs/Base/Scripts/FindSimilarIncidentsByText/README.md
  Packs/Base/Scripts/GetIncidentsByQuery/GetIncidentsByQuery.yml
  Packs/Base/Scripts/GetIncidentsByQuery/README.md
  Packs/Base/TestPlaybooks/DBotFindSimilarIncidentsByIndicators_-_Test.yml
  Packs/Base/TestPlaybooks/playbook-DBotFindSimilarIncidents-test.yml
  Packs/Base/TestPlaybooks/playbook-DBotTrainClustering-test.yml
  Packs/Base/TestPlaybooks/playbook-Onion_address_extraction_test.yml
  Packs/Base/TestPlaybooks/playbook-URLextraction-Test.yml
  Packs/Base/pack_metadata.json
  Packs/Bitbucket/TestPlaybooks/playbook-Test_Bitbucket.yml
  Packs/CIRCL/TestPlaybooks/playbook-CIRCL_CVE_Search_Test.yml
Labels: docs-approved, ForceMerge, bypass.url

#37754 revert docker image
  Packs/CrowdStrikeFalconStreamingV2/ReleaseNotes/1_1_15.md
  Packs/CrowdStrikeFalconStreamingV2/Scripts/CrowdStrikeStreamingPreProcessing/CrowdStrikeStreamingPreProcessing.yml
  Packs/CrowdStrikeFalconStreamingV2/pack_metadata.json
  Packs/CyrenInboxSecurity/ReleaseNotes/1_1_16.md
  Packs/CyrenInboxSecurity/Scripts/CyrenFindSimilarIncidents/CyrenFindSimilarIncidents.yml
  Packs/CyrenInboxSecurity/Scripts/CyrenShowThreatIndicators/CyrenShowThreatIndicators.yml
  Packs/CyrenInboxSecurity/pack_metadata.json
  Packs/GroupIB_ThreatIntelligenceAttribution/ReleaseNotes/1_4_6.md
  Packs/GroupIB_ThreatIntelligenceAttribution/Scripts/GIBIncidentUpdate/GIBIncidentUpdate.yml
  Packs/GroupIB_ThreatIntelligenceAttribution/Scripts/GIBIncidentUpdateIncludingClosed/GIBIncidentUpdateIncludingClosed.yml
  Packs/GroupIB_ThreatIntelligenceAttribution/pack_metadata.json
  Packs/IntegrationsAndIncidentsHealthCheck/ReleaseNotes/1_3_25.md
  Packs/IntegrationsAndIncidentsHealthCheck/Scripts/CopyLinkedAnalystNotes/CopyLinkedAnalystNotes.yml
  Packs/IntegrationsAndIncidentsHealthCheck/Scripts/GetFailedTasks/GetFailedTasks.yml
  Packs/IntegrationsAndIncidentsHealthCheck/pack_metadata.json
Labels: docs-approved

#37755 Delete the github action Run Legacy Validate on Contributions
  .github/workflows/run-legacy-validate-for-contribution.yml
Labels: docs-approved, ForceMerge

#37588 Aligning long-running port code and documentation
  Packs/AWS-SNS-Listener/Integrations/AWSSNSListener/AWSSNSListener.py
  Packs/AWS-SNS-Listener/Integrations/AWSSNSListener/AWSSNSListener.yml
  Packs/AWS-SNS-Listener/ReleaseNotes/1_0_6.md
  Packs/AWS-SNS-Listener/pack_metadata.json
  Packs/EDL/Integrations/EDL/EDL.py
  Packs/EDL/Integrations/EDL/EDL.yml
  Packs/EDL/ReleaseNotes/3_3_6.md
  Packs/EDL/pack_metadata.json
  Packs/GenericWebhook/.pack-ignore
  Packs/GenericWebhook/Integrations/GenericWebhook/GenericWebhook.py
  Packs/GenericWebhook/Integrations/GenericWebhook/GenericWebhook.yml
  Packs/GenericWebhook/Integrations/GenericWebhook/README.md
  Packs/GenericWebhook/ReleaseNotes/1_1_4.md
  Packs/GenericWebhook/pack_metadata.json
  Packs/Syslog/.pack-ignore
  Packs/Syslog/Integrations/Syslogv2/Syslogv2.py
  Packs/Syslog/Integrations/Syslogv2/Syslogv2_test.py
  Packs/Syslog/ReleaseNotes/2_0_20.md
  Packs/Syslog/pack_metadata.json
  Packs/TAXIIServer/.pack-ignore
  Packs/TAXIIServer/Integrations/TAXII2Server/TAXII2Server.py
  Packs/TAXIIServer/Integrations/TAXII2Server/TAXII2Server.yml
  Packs/TAXIIServer/Integrations/TAXIIServer/TAXIIServer.py
  Packs/TAXIIServer/Integrations/TAXIIServer/TAXIIServer.yml
  Packs/TAXIIServer/ReleaseNotes/2_1_0.md
  Packs/TAXIIServer/pack_metadata.json
Labels: docs-approved, ForceMerge

#37753 Nozomi fix broken proxy2
  Packs/NozomiNetworks/Integrations/NozomiNetworks/NozomiNetworks.py
  Packs/NozomiNetworks/Integrations/NozomiNetworks/NozomiNetworks_test.py
  Packs/NozomiNetworks/ReleaseNotes/1_0_13.md
  Packs/NozomiNetworks/pack_metadata.json
Labels: Contribution, Partner, ready-for-instance-test, Contribution Form Filled, Partner Support Level, External PR, Partner-Approved

#37747 Bug fixes for Office365 exchange online
  Packs/Office365/ModelingRules/Office365/Office365.xif
  Packs/Office365/ReleaseNotes/1_0_9.md
  Packs/Office365/pack_metadata.json
Labels: docs-approved

#37692 Ciac 10794 handle rate limit errors
  Packs/ApiModules/Scripts/CoreXQLApiModule/CoreXQLApiModule.py
  Packs/ApiModules/Scripts/CoreXQLApiModule/CoreXQLApiModule_test.py
  Packs/Core/ReleaseNotes/3_2_8.md
  Packs/Core/pack_metadata.json
  Packs/CortexXDR/ReleaseNotes/6_1_99.md
  Packs/CortexXDR/pack_metadata.json
Labels: docs-approved

#37693 Azure AD Connect Health Feed - Fix indicators parsing
  Packs/FeedAzureADConnectHealth/Integrations/AzureADConnectHealthFeed/AzureADConnectHealthFeed.py
  Packs/FeedAzureADConnectHealth/Integrations/AzureADConnectHealthFeed/AzureADConnectHealthFeed.yml
  Packs/FeedAzureADConnectHealth/Integrations/AzureADConnectHealthFeed/test_data/Microsoft_endpoint_mock.html
  Packs/FeedAzureADConnectHealth/ReleaseNotes/1_0_22.md
  Packs/FeedAzureADConnectHealth/pack_metadata.json
Labels: docs-approved

#37704 Aligning long running integrations not by default
  Packs/MicrosoftTeams/.pack-ignore
  Packs/MicrosoftTeams/Integrations/MicrosoftTeams/MicrosoftTeams.yml
  Packs/MicrosoftTeams/ReleaseNotes/1_5_10.md
  Packs/MicrosoftTeams/pack_metadata.json
  Packs/Zoom/Integrations/Zoom/README.md
  Packs/Zoom/Integrations/Zoom/Zoom.yml
  Packs/Zoom/ReleaseNotes/1_6_19.md
  Packs/Zoom/pack_metadata.json
Labels: docs-approved

#37725 [Google PubSub] For ACK dont skip older messages
  Packs/GooglePubSub/Integrations/GooglePubSub/GooglePubSub.py
  Packs/GooglePubSub/Integrations/GooglePubSub/GooglePubSub.yml
  Packs/GooglePubSub/Integrations/GooglePubSub/GooglePubSub_test.py
  Packs/GooglePubSub/ReleaseNotes/1_1_5.md
  Packs/GooglePubSub/pack_metadata.json
Labels: docs-approved

#37702 Update comment to xsoar+xsiam in SearchIncidentsV2
  Packs/CommonScripts/ReleaseNotes/1_18_3.md
  Packs/CommonScripts/Scripts/SearchIncidentsV2/README.md
  Packs/CommonScripts/Scripts/SearchIncidentsV2/SearchIncidentsV2.yml
  Packs/CommonScripts/pack_metadata.json
Labels: bypass.url

#37766 GenerixSQL: update docker image with cryptography
  Packs/GenericSQL/Integrations/GenericSQL/GenericSQL.yml
  Packs/GenericSQL/ReleaseNotes/1_3_7.md
  Packs/GenericSQL/pack_metadata.json
Labels: docs-approved
