Repository demisto/content, pull requests merged in 2024-11, with the labels that each got.

#36893 update varonis logo
  Packs/VaronisSaaS/Integrations/VaronisSaaS/VaronisSaaS_light.svg
  Packs/VaronisSaaS/ReleaseNotes/1_0_7.md
  Packs/VaronisSaaS/pack_metadata.json
Labels: Contribution, docs-approved, Partner, Contribution Form Filled, Partner Support Level, External PR, Partner-Approved

#36512 urlscan - file metadata issue fix
  Packs/UrlScan/Integrations/UrlScan/UrlScan.py
  Packs/UrlScan/ReleaseNotes/1_2_16.md
  Packs/UrlScan/pack_metadata.json
Labels: Contribution, docs-approved, Contribution Form Filled, Community, Partner Support Level, External PR, Partner-Approved

#34795 CIAC-8968 - Enhancement Hashicorp Vault integration
  Packs/HashiCorp-Vault/Integrations/HashiCorpVault/HashiCorpVault.py
  Packs/HashiCorp-Vault/Integrations/HashiCorpVault/HashiCorpVault.yml
  Packs/HashiCorp-Vault/Integrations/HashiCorpVault/HashiCorpVault_test.py
  Packs/HashiCorp-Vault/Integrations/HashiCorpVault/README.md
  Packs/HashiCorp-Vault/Integrations/HashiCorpVault/command_example.txt
  Packs/HashiCorp-Vault/ReleaseNotes/1_1_26.md
  Packs/HashiCorp-Vault/pack_metadata.json
Labels: docs-approved, ignore-stale

#36719 Migrate slack-send-file command in SlackV3 Integration to new APIs
  Packs/Slack/Integrations/SlackV3/README.md
  Packs/Slack/Integrations/SlackV3/SlackV3.py
  Packs/Slack/Integrations/SlackV3/SlackV3.yml
  Packs/Slack/Integrations/SlackV3/SlackV3_test.py
  Packs/Slack/ReleaseNotes/3_5_0.md
  Packs/Slack/pack_metadata.json
Labels: docs-approved, python, good first issue

#36767 V 1.1.0
  Packs/CheckPointNDR/IncidentFields/incidentfield-CheckPointNDR_ApplicationNames.json
  Packs/CheckPointNDR/IncidentFields/incidentfield-CheckPointNDR_ReceivedBytes.json
  Packs/CheckPointNDR/IncidentFields/incidentfield-CheckPointNDR_SentBytes.json
  Packs/CheckPointNDR/Integrations/CheckPointNDR/CheckPointNDR.py
  Packs/CheckPointNDR/Integrations/CheckPointNDR/CheckPointNDR.yml
  Packs/CheckPointNDR/Integrations/CheckPointNDR/CheckPointNDR_test.py
  Packs/CheckPointNDR/Integrations/CheckPointNDR/README.md
  Packs/CheckPointNDR/Integrations/CheckPointNDR/test_data/checkpointndr-get_insight_event.json
  Packs/CheckPointNDR/Integrations/CheckPointNDR/test_data/checkpointndr-parse_insights-output.json
  Packs/CheckPointNDR/Layouts/layoutscontainer-CheckPointNDR_Incident_Layout.json
  Packs/CheckPointNDR/README.md
  Packs/CheckPointNDR/ReleaseNotes/1_1_0.md
  Packs/CheckPointNDR/pack_metadata.json
Labels: Contribution, docs-approved, Partner, Contribution Form Filled, Partner Support Level, External PR, Security Review, Partner-Approved

#36756 Oktav2 revoke sessions
  Packs/Okta/Integrations/Okta_v2/Okta_v2.py
  Packs/Okta/Integrations/Okta_v2/Okta_v2.yml
  Packs/Okta/Integrations/Okta_v2/Okta_v2_test.py
  Packs/Okta/Integrations/Okta_v2/README.md
  Packs/Okta/ReleaseNotes/3_3_5.md
  Packs/Okta/pack_metadata.json
Labels: Contribution, docs-approved, Contribution Form Filled, Community, Xsoar Support Level, External PR

#37025 Xsup 42432 snow auth issue
  Packs/ServiceNow/Integrations/ServiceNowv2/ServiceNowv2.py
  Packs/ServiceNow/Integrations/ServiceNowv2/ServiceNowv2_test.py
  Packs/ServiceNow/ReleaseNotes/2_6_12.md
  Packs/ServiceNow/pack_metadata.json
Labels: docs-approved

#36898 Fixed alerts message reading error
  Packs/CybleEventsV2/Integrations/CybleEventsV2/CybleEventsV2.py
  Packs/CybleEventsV2/ReleaseNotes/1_0_5.md
  Packs/CybleEventsV2/pack_metadata.json
Labels: Contribution, Partner, Contribution Form Filled, Partner Support Level, External PR, Partner-Approved

#36686 Identical YML configs update
  Packs/BluecatAddressManager/ModelingRules/BluecatAddressManager_1_3/BluecatAddressManager_1_3.yml
  Packs/BluecatAddressManager/ParsingRules/BluecatAddressManager_1_3/BluecatAddressManager_1_3.yml
  Packs/BluecatAddressManager/ReleaseNotes/1_1_14.md
  Packs/BluecatAddressManager/pack_metadata.json
  Packs/CiscoASR/ModelingRules/CiscoASR/CiscoASR.yml
  Packs/CiscoASR/ParsingRules/CiscoASR/CiscoASR.yml
  Packs/CiscoASR/ReleaseNotes/1_0_3.md
  Packs/CiscoASR/pack_metadata.json
  Packs/CiscoISR/ModelingRules/CiscoISR/CiscoISR.yml
  Packs/CiscoISR/ParsingRules/CiscoISR/CiscoISR.yml
  Packs/CiscoISR/ReleaseNotes/1_0_4.md
  Packs/CiscoISR/pack_metadata.json
  Packs/CitrixADC/ModelingRules/CitrixADC_1_3/CitrixADC_1_3.yml
  Packs/CitrixADC/ParsingRules/CitrixADC_1_3/CitrixADC_1_3.yml
  Packs/CitrixADC/ReleaseNotes/1_0_4.md
  Packs/CitrixADC/pack_metadata.json
  Packs/MicrosoftDHCP/ModelingRules/MicrosoftDHCP_1_3/MicrosoftDHCP_1_3.yml
  Packs/MicrosoftDHCP/ParsingRules/MicrosoftDHCP/MicrosoftDHCP.yml
  Packs/MicrosoftDHCP/ReleaseNotes/1_0_4.md
  Packs/MicrosoftDHCP/pack_metadata.json
  Packs/MicrosoftDNS/ModelingRules/MicrosoftDNS_1_3/MicrosoftDNS_1_3.yml
  Packs/MicrosoftDNS/ParsingRules/MicrosoftDNS/MicrosoftDNS.yml
  Packs/MicrosoftDNS/ReleaseNotes/1_0_8.md
  Packs/MicrosoftDNS/pack_metadata.json
  Packs/PrismaSaasSecurity/ModelingRules/SaasSecurityEventCollector_1_3/SaasSecurityEventCollector_1_3.yml
  Packs/PrismaSaasSecurity/ParsingRules/PrismaSaasSecurity/PrismaSaasSecurity.yml
  Packs/PrismaSaasSecurity/ReleaseNotes/2_0_32.md
  Packs/PrismaSaasSecurity/pack_metadata.json
  Packs/Squid/ModelingRules/Squid/Squid.yml
  Packs/Squid/ParsingRules/Squid/Squid.yml
  Packs/Squid/ReleaseNotes/1_0_3.md
  Packs/Squid/pack_metadata.json
  Packs/SymantecEndpointProtection/ModelingRules/SymantecEndpointProtection_1_3/SymantecEndpointProtection_1_3.yml
  Packs/SymantecEndpointProtection/ParsingRules/SymantecEndpointProtection/SymantecEndpointProtection.yml
  Packs/SymantecEndpointProtection/ReleaseNotes/1_1_12.md
  Packs/SymantecEndpointProtection/pack_metadata.json
  Packs/TaniumThreatResponse/ModelingRules/TaniumThreatResponse/TaniumThreatResponse.yml
  Packs/TaniumThreatResponse/ParsingRules/TaniumThreatResponse/TaniumThreatResponse.yml
  Packs/TaniumThreatResponse/ReleaseNotes/2_2_17.md
  Packs/TaniumThreatResponse/pack_metadata.json
  Packs/jamf/ModelingRules/Jamf_1_3/Jamf_1_3.yml
  Packs/jamf/ParsingRules/jamf/jamf.yml
  Packs/jamf/ReleaseNotes/2_2_2.md
  Packs/jamf/pack_metadata.json
Labels: docs-approved, ForceMerge, bypass.url

#36874 CiscoUmbrellaReporting: Added optional "categories" argument to supporting commands
  Packs/CiscoUmbrellaReporting/Integrations/CiscoUmbrellaReporting/CiscoUmbrellaReporting.yml
  Packs/CiscoUmbrellaReporting/Integrations/CiscoUmbrellaReporting/README.md
  Packs/CiscoUmbrellaReporting/ReleaseNotes/1_1_4.md
  Packs/CiscoUmbrellaReporting/pack_metadata.json
Labels: Contribution, docs-approved, Contribution Form Filled, Community, pending-contributor, Xsoar Support Level, External PR

#37039 XSUP-42968 Linux Parsing Rule Extension for Additional Timestamp Formats
  Packs/LinuxEventsCollection/ParsingRules/LinuxEventsCollectionParsingRules/LinuxEventsCollectionParsingRules.xif
  Packs/LinuxEventsCollection/ReleaseNotes/1_0_11.md
  Packs/LinuxEventsCollection/pack_metadata.json
Labels: docs-approved, bypass.url

#37016 Axonius Pack - Add proxy support
  Packs/Axonius/Integrations/Axonius/Axonius.py
  Packs/Axonius/Integrations/Axonius/Axonius.yml
  Packs/Axonius/ReleaseNotes/1_2_5.md
  Packs/Axonius/pack_metadata.json
Labels: Contribution, docs-approved, Partner, Contribution Form Filled, Partner Support Level, External PR, Partner-Approved

#36668 Feature/search warninglists
  Packs/MISP/.secrets-ignore
  Packs/MISP/Integrations/MISPV3/MISPV3.py
  Packs/MISP/Integrations/MISPV3/MISPV3.yml
  Packs/MISP/Integrations/MISPV3/MISPV3_test.py
  Packs/MISP/Integrations/MISPV3/README.md
  Packs/MISP/ReleaseNotes/2_1_47.md
  Packs/MISP/pack_metadata.json
Labels: Contribution, docs-approved, post-demo, Contribution Form Filled, Community, Xsoar Support Level, External PR

#36794 Update DomainTools_Iris.py
  Packs/DomainTools_Iris/Integrations/DomainTools_Iris/DomainTools_Iris.py
  Packs/DomainTools_Iris/Integrations/DomainTools_Iris/DomainTools_Iris.yml
  Packs/DomainTools_Iris/ReleaseNotes/2_1_0.md
  Packs/DomainTools_Iris/pack_metadata.json
Labels: Contribution, docs-approved, Contribution Form Filled, Community, Partner Support Level, External PR, Partner-Approved

#37035 Update README.md
  Packs/CrowdStrikeFalcon/Integrations/CrowdStrikeFalcon/CrowdStrikeFalcon.yml
  Packs/CrowdStrikeFalcon/Integrations/CrowdStrikeFalcon/README.md
  Packs/CrowdStrikeFalcon/ReleaseNotes/2_0_23.md
  Packs/CrowdStrikeFalcon/pack_metadata.json
Labels: docs-approved

#37048 Ciac 12033 - Hide includeinformational argument in SearchAlertsV2 script in XSOAR using hidden in yml
  Packs/CommonScripts/ReleaseNotes/1_15_78.md
  Packs/CommonScripts/Scripts/SearchIncidentsV2/SearchIncidentsV2.py
  Packs/CommonScripts/Scripts/SearchIncidentsV2/SearchIncidentsV2.yml
  Packs/CommonScripts/Scripts/SearchIncidentsV2/SearchIncidentsV2_test.py
  Packs/CommonScripts/pack_metadata.json
Labels: docs-approved

#37045 Increase timeout
  Packs/ML/TestPlaybooks/playbook-Hash_Incident_Fields_test.yml
Labels: docs-approved

#36709 Adding support for for HC pack for x8
  Packs/HealthCheck/Playbooks/HealthCheck.yml
  Packs/HealthCheck/Playbooks/HealthCheck_README.md
  Packs/HealthCheck/Playbooks/Health_Check_-_Collect_Log_Bundle.yml
  Packs/HealthCheck/Playbooks/Health_Check_-_Log_Analysis_Read_All_files.yml
  Packs/HealthCheck/Playbooks/Health_Check_-_Log_Analysis_Read_All_files_README.md
  Packs/HealthCheck/ReleaseNotes/3_0_0.md
  Packs/HealthCheck/Scripts/HealthCheckAPIvalidation/HealthCheckAPIvalidation.yml
  Packs/HealthCheck/Scripts/HealthCheckAnalyzeLargeInvestigations/HealthCheckAnalyzeLargeInvestigations.py
  Packs/HealthCheck/Scripts/HealthCheckAnalyzeLargeInvestigations/HealthCheckAnalyzeLargeInvestigations.yml
  Packs/HealthCheck/Scripts/HealthCheckAnalyzeLargeInvestigations/HealthCheckAnalyzeLargeInvestigations_test.py
  Packs/HealthCheck/Scripts/HealthCheckCPU/HealthCheckCPU.py
  Packs/HealthCheck/Scripts/HealthCheckCPU/HealthCheckCPU.yml
  Packs/HealthCheck/Scripts/HealthCheckCommonIndicators/HealthCheckCommonIndicators.yml
  Packs/HealthCheck/Scripts/HealthCheckContainersStatus/HealthCheckContainersStatus.py
  Packs/HealthCheck/Scripts/HealthCheckContainersStatus/HealthCheckContainersStatus.yml
  Packs/HealthCheck/Scripts/HealthCheckDiskUsage/HealthCheckDiskUsage.py
  Packs/HealthCheck/Scripts/HealthCheckDiskUsage/HealthCheckDiskUsage.yml
  Packs/HealthCheck/Scripts/HealthCheckDiskUsageLine/HealthCheckDiskUsageLine.py
  Packs/HealthCheck/Scripts/HealthCheckDiskUsageLine/HealthCheckDiskUsageLine.yml
  Packs/HealthCheck/Scripts/HealthCheckDockerLog/HealthCheckDockerLog.py
  Packs/HealthCheck/Scripts/HealthCheckDockerLog/HealthCheckDockerLog.yml
  Packs/HealthCheck/Scripts/HealthCheckFields/HealthCheckFields.py
  Packs/HealthCheck/Scripts/HealthCheckFileSystem/HealthCheckFileSystem.py
  Packs/HealthCheck/Scripts/HealthCheckGetLargestInputsAndOutputsInIncidents/HealthCheckGetLargestInputsAndOutputsInIncidents.py
  Packs/HealthCheck/Scripts/HealthCheckGetLargestInputsAndOutputsInIncidents/HealthCheckGetLargestInputsAndOutputsInIncidents.yml
  Packs/HealthCheck/Scripts/HealthCheckIncidentTypes/HealthCheckIncidentTypes.yml
  Packs/HealthCheck/Scripts/HealthCheckIncidentsCreatedDaily/HealthCheckIncidentsCreatedDaily.py
  Packs/HealthCheck/Scripts/HealthCheckIncidentsCreatedDaily/HealthCheckIncidentsCreatedDaily.yml
  Packs/HealthCheck/Scripts/HealthCheckIncidentsCreatedMonthly/HealthCheckIncidentsCreatedMonthly.py
  Packs/HealthCheck/Scripts/HealthCheckIncidentsCreatedMonthly/HealthCheckIncidentsCreatedMonthly.yml
  Packs/HealthCheck/Scripts/HealthCheckIncidentsCreatedWeekly/HealthCheckIncidentsCreatedWeekly.py
  Packs/HealthCheck/Scripts/HealthCheckIncidentsCreatedWeekly/HealthCheckIncidentsCreatedWeekly.yml
  Packs/HealthCheck/Scripts/HealthCheckInstalledPacks/HealthCheckInstalledPacks.py
  Packs/HealthCheck/Scripts/HealthCheckInstalledPacks/HealthCheckInstalledPacks.yml
  Packs/HealthCheck/Scripts/HealthCheckIntegrations/HealthCheckIntegrations.yml
  Packs/HealthCheck/Scripts/HealthCheckLicenseData/HealthCheckLicenseData.py
  Packs/HealthCheck/Scripts/HealthCheckLicenseData/HealthCheckLicenseData.yml
  Packs/HealthCheck/Scripts/HealthCheckMemory/HealthCheckMemory.py
  Packs/HealthCheck/Scripts/HealthCheckMemory/HealthCheckMemory.yml
  Packs/HealthCheck/Scripts/HealthCheckNumberOfDroppedIncidents/HealthCheckNumberOfDroppedIncidents.py
  Packs/HealthCheck/Scripts/HealthCheckNumberOfDroppedIncidents/HealthCheckNumberOfDroppedIncidents.yml
  Packs/HealthCheck/Scripts/HealthCheckNumberOfLargeIOIncidents/HealthCheckNumberOfLargeIOIncidents.py
  Packs/HealthCheck/Scripts/HealthCheckNumberOfLargeIOIncidents/HealthCheckNumberOfLargeIOIncidents.yml
  Packs/HealthCheck/Scripts/HealthCheckNumberOfLargeIncidents/HealthCheckNumberOfLargeIncidents.py
  Packs/HealthCheck/Scripts/HealthCheckNumberOfLargeIncidents/HealthCheckNumberOfLargeIncidents.yml
  Packs/HealthCheck/Scripts/HealthCheckNumberOfPartitions/HealthCheckNumberOfPartitions.py
  Packs/HealthCheck/Scripts/HealthCheckNumberOfPartitions/HealthCheckNumberOfPartitions.yml
  Packs/HealthCheck/Scripts/HealthCheckPanicLog/HealthCheckPanicLog.py
  Packs/HealthCheck/Scripts/HealthCheckPanicLog/HealthCheckPanicLog.yml
  Packs/HealthCheck/Scripts/HealthCheckPlaybookAnalysis/HealthCheckPlaybookAnalysis.yml
  Packs/HealthCheck/Scripts/HealthCheckServerConfiguration/HealthCheckServerConfiguration.yml
  Packs/HealthCheck/Scripts/HealthCheckSystemDiagnostics/HealthCheckSystemDiagnostics.py
  Packs/HealthCheck/Scripts/HealthCheckSystemDiagnostics/HealthCheckSystemDiagnostics.yml
  Packs/HealthCheck/Scripts/HealthCheckWorkers/HealthCheckWorkers.py
  Packs/HealthCheck/Scripts/HealthCheckWorkers/HealthCheckWorkers.yml
  Packs/HealthCheck/Scripts/HealthCheckWorkers/README.md
  Packs/HealthCheck/pack_metadata.json
Labels: Contribution, docs-approved, post-demo, Contribution Form Filled, Community, Community Support Level, External PR, Security Review

#37040 Updated docker image to demisto/yolo-coco:1.0.0.115114. PR batch #1/1…
  Packs/ComputerVisionEngine/Integrations/ComputerVisionEngine/ComputerVisionEngine.yml
  Packs/ComputerVisionEngine/ReleaseNotes/1_0_4.md
  Packs/ComputerVisionEngine/pack_metadata.json
Labels: docs-approved

#37046 Updated docker image to demisto/ansible-runner:1.0.0.115040. PR batch…
  Packs/AnsibleAlibabaCloud/Integrations/AnsibleAlibabaCloud/AnsibleAlibabaCloud.yml
  Packs/AnsibleAlibabaCloud/ReleaseNotes/1_0_8.md
  Packs/AnsibleAlibabaCloud/pack_metadata.json
  Packs/AnsibleAzure/Integrations/AnsibleAzure/AnsibleAzure.yml
  Packs/AnsibleAzure/ReleaseNotes/1_0_10.md
  Packs/AnsibleAzure/pack_metadata.json
  Packs/AnsibleCiscoIOS/Integrations/AnsibleCiscoIOS/AnsibleCiscoIOS.yml
  Packs/AnsibleCiscoIOS/ReleaseNotes/1_0_10.md
  Packs/AnsibleCiscoIOS/pack_metadata.json
  Packs/AnsibleCiscoNXOS/Integrations/AnsibleCiscoNXOS/AnsibleCiscoNXOS.yml
  Packs/AnsibleCiscoNXOS/ReleaseNotes/1_0_8.md
  Packs/AnsibleCiscoNXOS/pack_metadata.json
  Packs/AnsibleHetznerCloud/Integrations/AnsibleHCloud/AnsibleHCloud.yml
  Packs/AnsibleHetznerCloud/ReleaseNotes/1_0_8.md
  Packs/AnsibleHetznerCloud/pack_metadata.json
  Packs/AnsibleKubernetes/Integrations/AnsibleKubernetes/AnsibleKubernetes.yml
  Packs/AnsibleKubernetes/ReleaseNotes/1_0_9.md
  Packs/AnsibleKubernetes/pack_metadata.json
  Packs/AnsibleLinux/Integrations/AnsibleACME/AnsibleACME.yml
  Packs/AnsibleLinux/Integrations/AnsibleDNS/AnsibleDNS.yml
  Packs/AnsibleLinux/Integrations/AnsibleLinux/AnsibleLinux.yml
  Packs/AnsibleLinux/Integrations/AnsibleOpenSSL/AnsibleOpenSSL.yml
  Packs/AnsibleLinux/ReleaseNotes/1_0_11.md
  Packs/AnsibleLinux/pack_metadata.json
  Packs/AnsibleMicrosoftWindows/Integrations/AnsibleMicrosoftWindows/AnsibleMicrosoftWindows.yml
  Packs/AnsibleMicrosoftWindows/ReleaseNotes/1_0_10.md
  Packs/AnsibleMicrosoftWindows/pack_metadata.json
  Packs/AnsibleVMware/Integrations/AnsibleVMware/AnsibleVMware.yml
  Packs/AnsibleVMware/ReleaseNotes/1_0_8.md
  Packs/AnsibleVMware/pack_metadata.json
  Packs/ArcherRSA/Integrations/ArcherV2/ArcherV2.yml
  Packs/ArcherRSA/ReleaseNotes/1_2_19.md
  Packs/ArcherRSA/pack_metadata.json
  Packs/CommonScripts/ReleaseNotes/1_15_79.md
  Packs/CommonScripts/Scripts/JsonUnescape/JsonUnescape.yml
  Packs/CommonScripts/pack_metadata.json
  Packs/CyberX-CentralManager/Integrations/CyberXCentralManager/CyberXCentralManager.yml
  Packs/CyberX-CentralManager/ReleaseNotes/1_0_6.md
  Packs/CyberX-CentralManager/pack_metadata.json
  Packs/SSLCertificates/ReleaseNotes/1_0_4.md
  Packs/SSLCertificates/Scripts/GenerateCSR/GenerateCSR.yml
  Packs/SSLCertificates/Scripts/SSLVerifierV2/SSLVerifierV2.yml
  Packs/SSLCertificates/Scripts/SSLVerifierV2GenerateEmailBody/SSLVerifierV2GenerateEmailBody.yml
  Packs/SSLCertificates/pack_metadata.json
Labels: docs-approved

#36658 XDR iocs integration- 'XSOAR Comment Field Exporting To XDR' parameter is handled incorrectly
  Packs/CortexXDR/Integrations/XDR_iocs/XDR_iocs.py
  Packs/CortexXDR/Integrations/XDR_iocs/XDR_iocs_test.py
  Packs/CortexXDR/Integrations/XDR_iocs/test_data/Domain_sync_file.txt
  Packs/CortexXDR/Integrations/XDR_iocs/test_data/File_sync_file.txt
  Packs/CortexXDR/Integrations/XDR_iocs/test_data/IP_sync_file.txt
  Packs/CortexXDR/ReleaseNotes/6_1_86.md
  Packs/CortexXDR/pack_metadata.json
Labels: docs-approved

#37032 Prisma Cloud Compute custom feeds ip remove (CIAC-11607)
  Packs/PrismaCloudCompute/Integrations/PaloAltoNetworks_PrismaCloudCompute/PaloAltoNetworks_PrismaCloudCompute.py
  Packs/PrismaCloudCompute/Integrations/PaloAltoNetworks_PrismaCloudCompute/PaloAltoNetworks_PrismaCloudCompute.yml
  Packs/PrismaCloudCompute/Integrations/PaloAltoNetworks_PrismaCloudCompute/PaloAltoNetworks_PrismaCloudCompute_test.py
  Packs/PrismaCloudCompute/Integrations/PaloAltoNetworks_PrismaCloudCompute/README.md
  Packs/PrismaCloudCompute/Integrations/PaloAltoNetworks_PrismaCloudCompute/commands.txt
  Packs/PrismaCloudCompute/ReleaseNotes/1_7_5.md
  Packs/PrismaCloudCompute/pack_metadata.json
Labels: docs-approved

#37067 Update README.md
  Packs/EDL/Integrations/EDL/README.md
Labels: docs-approved

#37066 Updated docker image to demisto/auth-utils:1.0.0.114762. PR batch #1/1
  Packs/MicrosoftDefenderAdvancedThreatProtection/Integrations/Microsoft365DefenderEventCollector/Microsoft365DefenderEventCollector.yml
  Packs/MicrosoftDefenderAdvancedThreatProtection/ReleaseNotes/1_16_42.md
  Packs/MicrosoftDefenderAdvancedThreatProtection/pack_metadata.json
Labels: docs-approved, auto-update-docker

#37011 Ews online bug
  Packs/MicrosoftExchangeOnline/Integrations/EwsExtensionEXOPowershellV3/EwsExtensionEXOPowershellV3.ps1
  Packs/MicrosoftExchangeOnline/ReleaseNotes/1_5_12.md
  Packs/MicrosoftExchangeOnline/pack_metadata.json
Labels: docs-approved

#37072 update armis docker image
  Packs/Armis/Integrations/Armis/Armis.yml
  Packs/Armis/ReleaseNotes/1_1_17.md
  Packs/Armis/pack_metadata.json
Labels: docs-approved

#37075 AUD-demisto/auto update docker staging branch 29
  Packs/GSuiteAdmin/Integrations/GSuiteAdmin/GSuiteAdmin.yml
  Packs/GSuiteAdmin/ReleaseNotes/1_2_3.md
  Packs/GSuiteAdmin/pack_metadata.json
  Packs/GSuiteSecurityAlertCenter/Integrations/GSuiteSecurityAlertCenter/GSuiteSecurityAlertCenter.yml
  Packs/GSuiteSecurityAlertCenter/ReleaseNotes/1_1_46.md
  Packs/GSuiteSecurityAlertCenter/pack_metadata.json
  Packs/GoogleCalendar/Integrations/GoogleCalendar/GoogleCalendar.yml
  Packs/GoogleCalendar/ReleaseNotes/1_1_48.md
  Packs/GoogleCalendar/pack_metadata.json
  Packs/GoogleCloudCompute/Integrations/GoogleCloudCompute/GoogleCloudCompute.yml
  Packs/GoogleCloudCompute/ReleaseNotes/1_1_13.md
  Packs/GoogleCloudCompute/pack_metadata.json
  Packs/GoogleDocs/Integrations/GoogleDocs/GoogleDocs.yml
  Packs/GoogleDocs/ReleaseNotes/1_0_27.md
  Packs/GoogleDocs/pack_metadata.json
  Packs/GoogleDrive/Integrations/GoogleDrive/GoogleDrive.yml
  Packs/GoogleDrive/ReleaseNotes/1_3_10.md
  Packs/GoogleDrive/pack_metadata.json
  Packs/GooglePubSub/Integrations/GooglePubSub/GooglePubSub.yml
  Packs/GooglePubSub/ReleaseNotes/1_1_3.md
  Packs/GooglePubSub/pack_metadata.json
  Packs/GoogleResourceManager/Integrations/GoogleResourceManager/GoogleResourceManager.yml
  Packs/GoogleResourceManager/ReleaseNotes/1_0_8.md
  Packs/GoogleResourceManager/pack_metadata.json
  Packs/GoogleSheets/Integrations/GoogleSheets/GoogleSheets.yml
  Packs/GoogleSheets/ReleaseNotes/1_0_46.md
  Packs/GoogleSheets/pack_metadata.json
  Packs/GoogleVault/Integrations/GoogleVault/GoogleVault.yml
  Packs/GoogleVault/ReleaseNotes/1_0_15.md
  Packs/GoogleVault/pack_metadata.json
  Packs/GoogleVertexAI/Integrations/GoogleVertexAI/GoogleVertexAI.yml
  Packs/GoogleVertexAI/ReleaseNotes/1_0_3.md
  Packs/GoogleVertexAI/pack_metadata.json
  Packs/GsuiteAuditor/Integrations/GsuiteAuditor/GsuiteAuditor.yml
  Packs/GsuiteAuditor/ReleaseNotes/1_0_25.md
  Packs/GsuiteAuditor/pack_metadata.json
Labels: docs-approved

#37080 DBotPredictURLPhishing - remove mailto urls
  Packs/PhishingURL/ReleaseNotes/1_1_20.md
  Packs/PhishingURL/Scripts/DBotPredictURLPhishing/DBotPredictURLPhishing.py
  Packs/PhishingURL/Scripts/DBotPredictURLPhishing/DBotPredictURLPhishing.yml
  Packs/PhishingURL/pack_metadata.json
Labels: docs-approved

#37049 Knowbe4 bug
  Packs/KnowBe4_KMSAT/Integrations/KnowBe4KMSATEventCollector/KnowBe4KMSATEventCollector.py
  Packs/KnowBe4_KMSAT/Integrations/KnowBe4KMSATEventCollector/KnowBe4KMSATEventCollector.yml
  Packs/KnowBe4_KMSAT/ReleaseNotes/1_0_34.md
  Packs/KnowBe4_KMSAT/pack_metadata.json
Labels: docs-approved

#37073 AUD-demisto/auto_update_docker_staging_branch_28
  Packs/AWS-SNS-Listener/Integrations/AWSSNSListener/AWSSNSListener.yml
  Packs/AWS-SNS-Listener/ReleaseNotes/1_0_5.md
  Packs/AWS-SNS-Listener/pack_metadata.json
  Packs/GenericWebhook/Integrations/GenericWebhook/GenericWebhook.yml
  Packs/GenericWebhook/ReleaseNotes/1_1_3.md
  Packs/GenericWebhook/pack_metadata.json
  Packs/GenericWebhook_FormData/Integrations/GenericWebhookFormData/GenericWebhookFormData.yml
  Packs/GenericWebhook_FormData/ReleaseNotes/1_0_1.md
  Packs/GenericWebhook_FormData/pack_metadata.json
  Packs/GitLab/Integrations/GitLabEventCollector/GitLabEventCollector.yml
  Packs/GitLab/ReleaseNotes/2_2_24.md
  Packs/GitLab/pack_metadata.json
  Packs/Okta/Integrations/OktaEventCollector/OktaEventCollector.yml
  Packs/Okta/ReleaseNotes/3_3_6.md
  Packs/Okta/pack_metadata.json
  Packs/PublishList/Integrations/PublishList/PublishList.yml
  Packs/PublishList/ReleaseNotes/1_1_4.md
  Packs/PublishList/pack_metadata.json
  Packs/SimpleAPIProxy/Integrations/SimpleAPIProxy/SimpleAPIProxy.yml
  Packs/SimpleAPIProxy/ReleaseNotes/1_0_4.md
  Packs/SimpleAPIProxy/pack_metadata.json
  Packs/Zoom/Integrations/Zoom/Zoom.yml
  Packs/Zoom/ReleaseNotes/1_6_15.md
  Packs/Zoom/Scripts/ZoomAsk/ZoomAsk.yml
  Packs/Zoom/pack_metadata.json
Labels: docs-approved

#37101 VaronisSaaS: Updated a Varonis log image for marketplace.
  Packs/VaronisSaaS/Integrations/VaronisSaaS/VaronisSaaS_image.png
  Packs/VaronisSaaS/ReleaseNotes/1_0_8.md
  Packs/VaronisSaaS/pack_metadata.json
Labels: Contribution, docs-approved, Partner, Contribution Form Filled, Partner Support Level, External PR, Partner-Approved

#36602 CrowdStrikeFalcon: ioc count in case of rate limit
  Packs/CrowdStrikeFalcon/Integrations/CrowdStrikeFalcon/CrowdStrikeFalcon.py
  Packs/CrowdStrikeFalcon/Integrations/CrowdStrikeFalcon/CrowdStrikeFalcon.yml
  Packs/CrowdStrikeFalcon/Integrations/CrowdStrikeFalcon/CrowdStrikeFalcon_test.py
  Packs/CrowdStrikeFalcon/ReleaseNotes/2_0_24.md
  Packs/CrowdStrikeFalcon/pack_metadata.json
Labels: docs-approved

#37050 [MimecastV2] mimecast-query - fixes
  Packs/Mimecast/Integrations/MimecastV2/MimecastV2.py
  Packs/Mimecast/Integrations/MimecastV2/MimecastV2.yml
  Packs/Mimecast/Integrations/MimecastV2/MimecastV2_description.md
  Packs/Mimecast/Integrations/MimecastV2/MimecastV2_test.py
  Packs/Mimecast/ReleaseNotes/2_5_2.md
  Packs/Mimecast/pack_metadata.json
Labels: docs-approved

#37103 Aud demisto/auto update docker staging branch 33
  Packs/CommonScripts/ReleaseNotes/1_15_81.md
  Packs/CommonScripts/Scripts/PreProcessImage/PreProcessImage.yml
  Packs/CommonScripts/pack_metadata.json
  Packs/SuspiciousDomainHunting/ReleaseNotes/1_0_7.md
  Packs/SuspiciousDomainHunting/Scripts/Imagecompare/Imagecompare.yml
  Packs/SuspiciousDomainHunting/Scripts/RasterizeImageOriginal/RasterizeImageOriginal.yml
  Packs/SuspiciousDomainHunting/Scripts/RasterizeImageSuspicious/RasterizeImageSuspicious.yml
  Packs/SuspiciousDomainHunting/pack_metadata.json
Labels: docs-approved

#37089 Aud demisto/auto update docker staging branch 31
  Packs/Active_Directory_Query/Integrations/Active_Directory_Query/Active_Directory_Query.yml
  Packs/Active_Directory_Query/ReleaseNotes/1_6_40.md
  Packs/Active_Directory_Query/pack_metadata.json
Labels: docs-approved, auto-update-docker

#37091 Aud demisto/auto update docker staging branch 32
  Packs/GCP-IAM/Integrations/GCPIAM/GCPIAM.yml
  Packs/GCP-IAM/ReleaseNotes/1_0_29.md
  Packs/GCP-IAM/pack_metadata.json
  Packs/Gmail/Integrations/Gmail/Gmail.yml
  Packs/Gmail/ReleaseNotes/1_3_27.md
  Packs/Gmail/pack_metadata.json
  Packs/GmailSingleUser/Integrations/GmailSingleUser/GmailSingleUser.yml
  Packs/GmailSingleUser/ReleaseNotes/1_4_7.md
  Packs/GmailSingleUser/pack_metadata.json
  Packs/GoogleCloudFunctions/Integrations/GoogleCloudFunctions/GoogleCloudFunctions.yml
  Packs/GoogleCloudFunctions/ReleaseNotes/1_0_30.md
  Packs/GoogleCloudFunctions/pack_metadata.json
  Packs/GoogleCloudLogging/Integrations/GoogleCloudLogging/GoogleCloudLogging.yml
  Packs/GoogleCloudLogging/ReleaseNotes/1_0_16.md
  Packs/GoogleCloudLogging/pack_metadata.json
Labels: docs-approved, auto-update-docker

#37110 DBotPredictURLPhishing - check mailto_urls value before return the results
  Packs/PhishingURL/ReleaseNotes/1_1_21.md
  Packs/PhishingURL/Scripts/DBotPredictURLPhishing/DBotPredictURLPhishing.py
  Packs/PhishingURL/pack_metadata.json
Labels: docs-approved, release-notes-only

#37071 TIM Email type indicator layout fix - adding the verdict section to quick view
  Packs/CommonTypes/Layouts/layoutscontainer-AccountV2.json
  Packs/CommonTypes/Layouts/layoutscontainer-DomainV2.json
  Packs/CommonTypes/Layouts/layoutscontainer-EmailV2.json
  Packs/CommonTypes/Layouts/layoutscontainer-FileV2.json
  Packs/CommonTypes/Layouts/layoutscontainer-Windows_Registry_KeyV2.json
  Packs/CommonTypes/Layouts/layoutscontainer-registryKey.json
  Packs/CommonTypes/ReleaseNotes/3_5_24.md
  Packs/CommonTypes/pack_metadata.json
Labels: docs-approved

#36378 kafka consumer only
  Packs/Kafka/Integrations/KafkaV3/KafkaV3.py
  Packs/Kafka/Integrations/KafkaV3/KafkaV3.yml
  Packs/Kafka/Integrations/KafkaV3/KafkaV3_description.md
  Packs/Kafka/Integrations/KafkaV3/KafkaV3_test.py
  Packs/Kafka/Integrations/KafkaV3/README.md
  Packs/Kafka/ReleaseNotes/2_0_23.md
  Packs/Kafka/TestPlaybooks/playbook-KafkaV3_Test.yml
  Packs/Kafka/pack_metadata.json
  Tests/conf.json
Labels: docs-approved, sync-gsm

#34872 ElasticsearchV2 - Added Support for v8.x
  Packs/Elasticsearch/Integrations/Elasticsearch_v2/Elasticsearch_v2.py
  Packs/Elasticsearch/Integrations/Elasticsearch_v2/Elasticsearch_v2.yml
  Packs/Elasticsearch/Integrations/Elasticsearch_v2/Elasticsearch_v2_description.md
  Packs/Elasticsearch/Integrations/Elasticsearch_v2/Elasticsearch_v2_test.py
  Packs/Elasticsearch/Integrations/Elasticsearch_v2/README.md
  Packs/Elasticsearch/ReleaseNotes/1_3_23.md
  Packs/Elasticsearch/TestPlaybooks/playbook-Elasticsearch_v2_test-v7-v8.yml
  Packs/Elasticsearch/TestPlaybooks/playbook-Elasticsearch_v2_test-v8.yml
  Packs/Elasticsearch/pack_metadata.json
  Tests/conf.json
Labels: docs-approved

#37008 CIAC-12086 - Command core-get-cloud-original-alerts fails in debugger (due to alert ID)
  Packs/ApiModules/Scripts/CoreIRApiModule/CoreIRApiModule.py
  Packs/ApiModules/Scripts/CoreIRApiModule/CoreIRApiModule_test.py
  Packs/Core/ReleaseNotes/3_0_87.md
  Packs/Core/pack_metadata.json
  Packs/CortexXDR/ReleaseNotes/6_1_87.md
  Packs/CortexXDR/pack_metadata.json
  Packs/ctf01/ReleaseNotes/1_0_31.md
  Packs/ctf01/pack_metadata.json
Labels: docs-approved

#37116 [DBotFindSimilarIncidentsByIndicators] Fix issue with field that is not populated in incidents
  Packs/Base/ReleaseNotes/1_34_44.md
  Packs/Base/Scripts/DBotFindSimilarIncidentsByIndicators/DBotFindSimilarIncidentsByIndicators.py
  Packs/Base/Scripts/DBotFindSimilarIncidentsByIndicators/DBotFindSimilarIncidentsByIndicators.yml
  Packs/Base/Scripts/DBotFindSimilarIncidentsByIndicators/DBotFindSimilarIncidentsByIndicators_test.py
  Packs/Base/pack_metadata.json
Labels: docs-approved

#36405 Akamai 416 and duplications fix
  Packs/Akamai_SIEM/.pack-ignore
  Packs/Akamai_SIEM/Integrations/Akamai_SIEM/Akamai_SIEM.py
  Packs/Akamai_SIEM/Integrations/Akamai_SIEM/Akamai_SIEM.yml
  Packs/Akamai_SIEM/Integrations/Akamai_SIEM/Akamai_SIEM_test.py
  Packs/Akamai_SIEM/Integrations/Akamai_SIEM/README.md
  Packs/Akamai_SIEM/ReleaseNotes/1_1_6.md
  Packs/Akamai_SIEM/pack_metadata.json
Labels: docs-approved, ForceMerge

#37119 XSUP-42968 Linux Parsing Rule Improve ISO 8601 Coverage
  Packs/LinuxEventsCollection/ParsingRules/LinuxEventsCollectionParsingRules/LinuxEventsCollectionParsingRules.xif
  Packs/LinuxEventsCollection/README.md
  Packs/LinuxEventsCollection/ReleaseNotes/1_0_12.md
  Packs/LinuxEventsCollection/pack_metadata.json
Labels: docs-approved

#37064 Compromise accounts - user rejected numerous sso mfa attempts
  Packs/Core/Playbooks/playbook-Compromise_Accounts_-_User_rejected_numerous_SSO_MFA_attempts.yml
  Packs/Core/Playbooks/playbook-Compromise_Accounts_-_User_rejected_numerous_SSO_MFA_attempts_README.md
  Packs/Core/ReleaseNotes/3_0_88.md
  Packs/Core/Triggers/Trigger_-_Compromise_Accounts_-_User_rejected_numerous_SSO_MFA_attempts.json
  Packs/Core/doc_files/Compromise_Accounts_-_User_rejected_numerous_SSO_MFA_attempts.png
  Packs/Core/pack_metadata.json
Labels: docs-approved, bypass.url

#37027 Incident Layouts | Add default Incident Layout For XSIAM
  Packs/Core/Layouts/layoutscontainer-Default_XSIAM_Case.json
  Packs/Core/ReleaseNotes/3_0_89.md
  Packs/Core/pack_metadata.json
Labels: docs-approved, bypass.url

#36812 Microsoft Intune - Update Microsoft Intune endpoint URL
  Packs/FeedMicrosoftIntune/Integrations/FeedMicrosoftIntune/FeedMicrosoftIntune.yml
  Packs/FeedMicrosoftIntune/Integrations/FeedMicrosoftIntune/FeedMicrosoftIntune_description.md
  Packs/FeedMicrosoftIntune/Integrations/FeedMicrosoftIntune/FeedMicrosoftIntune_test.py
  Packs/FeedMicrosoftIntune/ReleaseNotes/1_0_21.md
  Packs/FeedMicrosoftIntune/pack_metadata.json
Labels: docs-approved

#37038 [EWS0365/EWSv2] Add parsing exceptions handling in fetch-incidents
  Packs/MicrosoftExchangeOnPremise/Integrations/EWSv2/EWSv2.py
  Packs/MicrosoftExchangeOnPremise/Integrations/EWSv2/EWSv2.yml
  Packs/MicrosoftExchangeOnPremise/Integrations/EWSv2/EWSv2_test.py
  Packs/MicrosoftExchangeOnPremise/Integrations/EWSv2/README.md
  Packs/MicrosoftExchangeOnPremise/ReleaseNotes/2_1_14.md
  Packs/MicrosoftExchangeOnPremise/pack_metadata.json
  Packs/MicrosoftExchangeOnline/Integrations/EWSO365/EWSO365.py
  Packs/MicrosoftExchangeOnline/Integrations/EWSO365/EWSO365.yml
  Packs/MicrosoftExchangeOnline/Integrations/EWSO365/EWSO365_test.py
  Packs/MicrosoftExchangeOnline/Integrations/EWSO365/README.md
  Packs/MicrosoftExchangeOnline/ReleaseNotes/1_5_14.md
  Packs/MicrosoftExchangeOnline/pack_metadata.json
Labels: docs-approved

#36849 Elasticsearch Feed support Elasticsearch client v8
  Packs/FeedElasticsearch/Integrations/FeedElasticsearch/FeedElasticsearch.py
  Packs/FeedElasticsearch/Integrations/FeedElasticsearch/FeedElasticsearch.yml
  Packs/FeedElasticsearch/Integrations/FeedElasticsearch/FeedElasticsearch_description.md
  Packs/FeedElasticsearch/Integrations/FeedElasticsearch/FeedElasticsearch_test.py
  Packs/FeedElasticsearch/Integrations/FeedElasticsearch/README.md
  Packs/FeedElasticsearch/ReleaseNotes/1_1_10.md
  Packs/FeedElasticsearch/pack_metadata.json
  Tests/conf.json
Labels: docs-approved, sync-gsm

#37131 Partner csc adoption complete
  Packs/CSCDomainManager/README.md
  Packs/CSCDomainManager/ReleaseNotes/1_0_3.md
  Packs/CSCDomainManager/pack_metadata.json
Labels: Contribution, docs-approved, Partner, Contribution Form Filled, Partner Support Level, External PR, Partner-Approved

#37122 Aud demisto/auto update docker staging branch 35
  Packs/CommonScripts/ReleaseNotes/1_15_82.md
  Packs/CommonScripts/Scripts/Dig/Dig.yml
  Packs/CommonScripts/Scripts/GetDomainDNSDetails/GetDomainDNSDetails.yml
  Packs/CommonScripts/Scripts/Ping/Ping.yml
  Packs/CommonScripts/pack_metadata.json
  Packs/FeedPublicDNS/Integrations/FeedPublicDNS/FeedPublicDNS.yml
  Packs/FeedPublicDNS/ReleaseNotes/1_0_17.md
  Packs/FeedPublicDNS/pack_metadata.json
  Packs/FiltersAndTransformers/ReleaseNotes/1_2_80.md
  Packs/FiltersAndTransformers/Scripts/IPv4Blacklist/IPv4Blacklist.yml
  Packs/FiltersAndTransformers/Scripts/IPv4Whitelist/IPv4Whitelist.yml
  Packs/FiltersAndTransformers/Scripts/IsRFC1918Address/IsRFC1918Address.yml
  Packs/FiltersAndTransformers/pack_metadata.json
  Packs/Mattermost/Integrations/MattermostV2/MattermostV2.yml
  Packs/Mattermost/ReleaseNotes/2_0_3.md
  Packs/Mattermost/pack_metadata.json
  Packs/Nmap/Integrations/Nmap/Nmap.yml
  Packs/Nmap/ReleaseNotes/1_2_4.md
  Packs/Nmap/pack_metadata.json
  Packs/ProofpointEmailSecurity/Integrations/ProofpointEmailSecurityEventCollector/ProofpointEmailSecurityEventCollector.yml
  Packs/ProofpointEmailSecurity/ReleaseNotes/1_0_5.md
  Packs/ProofpointEmailSecurity/pack_metadata.json
Labels: docs-approved, auto-update-docker

#37120 Aud demisto/auto update docker staging branch 38
  Packs/Akamai_WAF/Integrations/Akamai_WAF/Akamai_WAF.yml
  Packs/Akamai_WAF/ReleaseNotes/2_0_13.md
  Packs/Akamai_WAF/pack_metadata.json
  Packs/AlibabaActionTrail/Integrations/AlibabaActionTrailEventCollector/AlibabaActionTrailEventCollector.yml
  Packs/AlibabaActionTrail/ReleaseNotes/1_1_1.md
  Packs/AlibabaActionTrail/pack_metadata.json
  Packs/AzureDataExplorer/Integrations/AzureDataExplorer/AzureDataExplorer.yml
  Packs/AzureDataExplorer/ReleaseNotes/1_3_4.md
  Packs/AzureDataExplorer/pack_metadata.json
  Packs/Box/Integrations/BoxEventsCollector/BoxEventsCollector.yml
  Packs/Box/ReleaseNotes/3_2_3.md
  Packs/Box/pack_metadata.json
  Packs/Cylance_Protect/Integrations/Cylance_Protect_v2/Cylance_Protect_v2.yml
  Packs/Cylance_Protect/ReleaseNotes/1_1_37.md
  Packs/Cylance_Protect/pack_metadata.json
  Packs/Gem/Integrations/Gem/Gem.yml
  Packs/Gem/ReleaseNotes/1_0_2.md
  Packs/Gem/pack_metadata.json
  Packs/GitHub/Integrations/GitHub/GitHub.yml
  Packs/GitHub/ReleaseNotes/2_1_3.md
  Packs/GitHub/pack_metadata.json
  Packs/JWT/Integrations/JWT/JWT.yml
  Packs/JWT/ReleaseNotes/1_0_3.md
  Packs/JWT/pack_metadata.json
  Packs/Keyfactor/Integrations/Keyfactor/Keyfactor.yml
  Packs/Keyfactor/ReleaseNotes/1_0_2.md
  Packs/Keyfactor/pack_metadata.json
  Packs/Malwarebytes/Integrations/Malwarebytes/Malwarebytes.yml
  Packs/Malwarebytes/ReleaseNotes/1_1_19.md
  Packs/Malwarebytes/pack_metadata.json
  Packs/MicrosoftCloudAppSecurity/Integrations/MicrosoftDefenderEventCollector/MicrosoftDefenderEventCollector.yml
  Packs/MicrosoftCloudAppSecurity/ReleaseNotes/2_2_7.md
  Packs/MicrosoftCloudAppSecurity/pack_metadata.json
  Packs/MicrosoftDefenderAdvancedThreatProtection/Integrations/Microsoft365DefenderEventCollector/Microsoft365DefenderEventCollector.yml
  Packs/MicrosoftDefenderAdvancedThreatProtection/ReleaseNotes/1_16_43.md
  Packs/MicrosoftDefenderAdvancedThreatProtection/pack_metadata.json
  Packs/MicrosoftManagementActivity/Integrations/MicrosoftManagementActivity/MicrosoftManagementActivity.yml
  Packs/MicrosoftManagementActivity/ReleaseNotes/1_3_49.md
  Packs/MicrosoftManagementActivity/pack_metadata.json
  Packs/Pcysys/Integrations/Pcysys/Pcysys.yml
  Packs/Pcysys/ReleaseNotes/1_3_9.md
  Packs/Pcysys/pack_metadata.json
  Packs/Silverfort/Integrations/Silverfort/Silverfort.yml
  Packs/Silverfort/ReleaseNotes/2_0_28.md
  Packs/Silverfort/pack_metadata.json
  Packs/Troubleshoot/ReleaseNotes/2_1_1.md
  Packs/Troubleshoot/Scripts/CertificatesTroubleshoot/CertificatesTroubleshoot.yml
  Packs/Troubleshoot/pack_metadata.json
  Packs/Uptycs/Integrations/Uptycs/Uptycs.yml
  Packs/Uptycs/ReleaseNotes/1_0_13.md
  Packs/Uptycs/pack_metadata.json
  Packs/WinRM/Integrations/WindowsRemoteManagement/WindowsRemoteManagement.yml
  Packs/WinRM/ReleaseNotes/1_0_5.md
  Packs/WinRM/pack_metadata.json
  Packs/Zoom/Integrations/Zoom_IAM/Zoom_IAM.yml
  Packs/Zoom/ReleaseNotes/1_6_16.md
  Packs/Zoom/pack_metadata.json
Labels: docs-approved, auto-update-docker

#37115 Aud demisto/auto update docker staging branch 36
  Packs/Base/ReleaseNotes/1_34_45.md
  Packs/Base/Scripts/ValidateContent/ValidateContent.yml
  Packs/Base/pack_metadata.json
  Packs/CommonScripts/ReleaseNotes/1_15_83.md
  Packs/CommonScripts/Scripts/ContentPackInstaller/ContentPackInstaller.yml
  Packs/CommonScripts/pack_metadata.json
  Packs/ContentManagement/ReleaseNotes/1_2_24.md
  Packs/ContentManagement/Scripts/CommitFiles/CommitFiles.yml
  Packs/ContentManagement/Scripts/ConfigurationSetup/ConfigurationSetup.yml
  Packs/ContentManagement/Scripts/CustomPackInstaller/CustomPackInstaller.yml
  Packs/ContentManagement/Scripts/GetIdsFromCustomContent/GetIdsFromCustomContent.yml
  Packs/ContentManagement/Scripts/JobCreator/JobCreator.yml
  Packs/ContentManagement/Scripts/ListCreator/ListCreator.yml
  Packs/ContentManagement/pack_metadata.json
Labels: docs-approved, auto-update-docker

#37129 UploadFile script fix deprecation message
  Packs/DemistoRESTAPI/ReleaseNotes/1_3_62.md
  Packs/DemistoRESTAPI/Scripts/DemistoUploadFile/DemistoUploadFile.yml
  Packs/DemistoRESTAPI/pack_metadata.json
Labels: docs-approved, release-notes-only

#37135 update parse-email to 0.1.30
  Packs/CommonScripts/ReleaseNotes/1_15_84.md
  Packs/CommonScripts/Scripts/ParseEmailFilesV2/ParseEmailFilesV2.yml
  Packs/CommonScripts/pack_metadata.json
Labels: docs-approved

#36859 rasterize - fix timeout issue
  Packs/rasterize/Integrations/rasterize/rasterize.py
  Packs/rasterize/Integrations/rasterize/rasterize.yml
  Packs/rasterize/Integrations/rasterize/rasterize_test.py
  Packs/rasterize/ReleaseNotes/2_0_26.md
  Packs/rasterize/pack_metadata.json
Labels: docs-approved

#37126 Incapsula - pass arguments in url params
  Packs/Incapsula/Integrations/Incapsula/Incapsula.js
  Packs/Incapsula/ReleaseNotes/1_1_7.md
  Packs/Incapsula/pack_metadata.json
Labels: docs-approved, ForceMerge

#36637 Veeam Check for XSIAM v2.5
  Packs/Veeam/.pack-ignore
  Packs/Veeam/README.md
  Packs/Veeam/ReleaseNotes/1_0_1.md
  Packs/Veeam/XSIAMDashboards/Veeam_Data_Platform_Monitoring_Dashboard.json
  Packs/Veeam/XSIAMDashboards/Veeam_Data_Platform_Monitoring_Dashboard_image.png
  Packs/Veeam/XSIAMDashboards/Veeam_Security_Activities_Dashboard.json
  Packs/Veeam/XSIAMDashboards/Veeam_Security_Activities_Dashboard_image.png
  Packs/Veeam/XSIAMReports/Veeam_All_Veeam_failed_multi-factor_authentication_events_for_the_last_24h.json
  Packs/Veeam/XSIAMReports/Veeam_All_Veeam_finished_jobs_for_the_last_24h.json
  Packs/Veeam/XSIAMReports/Veeam_All_Veeam_four-eyes_authorization_events_for_the_last_24h.json
  Packs/Veeam/XSIAMReports/Veeam_All_Veeam_malware_detection_events_for_the_last_24h.json
  Packs/Veeam/XSIAMReports/Veeam_All_Veeam_security_events_for_the_last_7_days.json
  Packs/Veeam/XSIAMReports/Veeam_All_Veeam_security_events_with_Critical_and_High_severity_for_the_last_24h.json
  Packs/Veeam/XSIAMReports/Veeam_All_Veeam_triggered_alarms_for_the_last_7_days.json
  Packs/Veeam/doc_files/Veeam_XSOAR_Dashboard.png
  Packs/Veeam/doc_files/Veeam_XSOAR_Playbooks.png
  Packs/Veeam/pack_metadata.json
Labels: docs-approved, bypass.url

#37083 Scheduled task created with http or ftp reference enhancement
  Packs/Core/Playbooks/playbook-Scheduled_task_created_with_HTTP_or_FTP_reference.yml
  Packs/Core/Playbooks/playbook-Scheduled_task_created_with_HTTP_or_FTP_reference_README.md
  Packs/Core/ReleaseNotes/3_0_91.md
  Packs/Core/doc_files/Scheduled_task_created_with_HTTP_or_FTP_reference.png
  Packs/Core/pack_metadata.json
Labels: docs-approved

#37029 Uncommon remote scheduled task created
  Packs/CommonPlaybooks/Playbooks/playbook-Command-Line_Analysis.yml
  Packs/CommonPlaybooks/Playbooks/playbook-Command-Line_Analysis_README.md
  Packs/CommonPlaybooks/ReleaseNotes/2_6_47.md
  Packs/CommonPlaybooks/doc_files/Command-Line_Analysis.png
  Packs/CommonPlaybooks/pack_metadata.json
  Packs/Core/Playbooks/playbook-Uncommon_remote_scheduled_task_created.yml
  Packs/Core/Playbooks/playbook-Uncommon_remote_scheduled_task_created_README.md
  Packs/Core/ReleaseNotes/3_0_92.md
  Packs/Core/Triggers/Trigger_-_Uncommon_remote_scheduled_task_created.json
  Packs/Core/doc_files/Uncommon_remote_scheduled_task_created.png
  Packs/Core/pack_metadata.json
Labels: docs-approved

#37084 added new command support in EclecticIQ pack
  Packs/EclecticIQ/Integrations/EclecticIQIntelligenceCenterv3/EclecticIQIntelligenceCenterv3.py
  Packs/EclecticIQ/Integrations/EclecticIQIntelligenceCenterv3/EclecticIQIntelligenceCenterv3.yml
  Packs/EclecticIQ/Integrations/EclecticIQIntelligenceCenterv3/EclecticIQIntelligenceCenterv3_test.py
  Packs/EclecticIQ/Integrations/EclecticIQIntelligenceCenterv3/README.md
  Packs/EclecticIQ/Integrations/EclecticIQIntelligenceCenterv3/command_examples.txt
  Packs/EclecticIQ/ReleaseNotes/3_0_5.md
  Packs/EclecticIQ/pack_metadata.json
Labels: Contribution, docs-approved, Partner, Contribution Form Filled, Partner Support Level, External PR, Partner-Approved

#36453 TIM - Malware indicator type layout mismatch
  Packs/CommonTypes/Layouts/layoutscontainer-MalwareV2.json
  Packs/CommonTypes/ReleaseNotes/3_5_25.md
  Packs/CommonTypes/pack_metadata.json
Labels: docs-approved, ForceMerge, bypass.url

#37106 T1564.002 - Hide Artifacts: Hidden Users] - Suspicious hidden user created
  Packs/Core/.pack-ignore
  Packs/Core/Playbooks/playbook-Suspicious_Hidden_User_Created.yml
  Packs/Core/Playbooks/playbook-Suspicious_Hidden_User_Created_README.md
  Packs/Core/ReleaseNotes/3_0_93.md
  Packs/Core/Triggers/Trigger_-_Suspicious_Hidden_User_Created.json
  Packs/Core/doc_files/Suspicious_Hidden_User_Created.png
  Packs/Core/pack_metadata.json
Labels: docs-approved

#37146 Aud demisto/auto update docker staging branch 41
  Packs/GSuiteAdmin/Integrations/GSuiteAdmin/GSuiteAdmin.yml
  Packs/GSuiteAdmin/ReleaseNotes/1_2_4.md
  Packs/GSuiteAdmin/pack_metadata.json
  Packs/GSuiteSecurityAlertCenter/Integrations/GSuiteSecurityAlertCenter/GSuiteSecurityAlertCenter.yml
  Packs/GSuiteSecurityAlertCenter/ReleaseNotes/1_1_47.md
  Packs/GSuiteSecurityAlertCenter/pack_metadata.json
  Packs/GoogleCalendar/Integrations/GoogleCalendar/GoogleCalendar.yml
  Packs/GoogleCalendar/ReleaseNotes/1_1_49.md
  Packs/GoogleCalendar/pack_metadata.json
  Packs/GoogleChronicleBackstory/Integrations/GoogleChronicleBackstory/GoogleChronicleBackstory.yml
  Packs/GoogleChronicleBackstory/Integrations/GoogleChronicleBackstoryStreamingAPI/GoogleChronicleBackstoryStreamingAPI.yml
  Packs/GoogleChronicleBackstory/ReleaseNotes/4_0_3.md
  Packs/GoogleChronicleBackstory/pack_metadata.json
  Packs/GoogleCloudCompute/Integrations/GoogleCloudCompute/GoogleCloudCompute.yml
  Packs/GoogleCloudCompute/ReleaseNotes/1_1_14.md
  Packs/GoogleCloudCompute/pack_metadata.json
  Packs/GoogleDocs/Integrations/GoogleDocs/GoogleDocs.yml
  Packs/GoogleDocs/ReleaseNotes/1_0_28.md
  Packs/GoogleDocs/pack_metadata.json
  Packs/GoogleDrive/Integrations/GoogleDrive/GoogleDrive.yml
  Packs/GoogleDrive/ReleaseNotes/1_3_11.md
  Packs/GoogleDrive/pack_metadata.json
  Packs/GooglePubSub/Integrations/GooglePubSub/GooglePubSub.yml
  Packs/GooglePubSub/ReleaseNotes/1_1_4.md
  Packs/GooglePubSub/pack_metadata.json
  Packs/GoogleResourceManager/Integrations/GoogleResourceManager/GoogleResourceManager.yml
  Packs/GoogleResourceManager/ReleaseNotes/1_0_9.md
  Packs/GoogleResourceManager/pack_metadata.json
  Packs/GoogleSheets/Integrations/GoogleSheets/GoogleSheets.yml
  Packs/GoogleSheets/ReleaseNotes/1_0_47.md
  Packs/GoogleSheets/pack_metadata.json
  Packs/GoogleVault/Integrations/GoogleVault/GoogleVault.yml
  Packs/GoogleVault/ReleaseNotes/1_0_16.md
  Packs/GoogleVault/pack_metadata.json
  Packs/GsuiteAuditor/Integrations/GsuiteAuditor/GsuiteAuditor.yml
  Packs/GsuiteAuditor/ReleaseNotes/1_0_26.md
  Packs/GsuiteAuditor/pack_metadata.json
Labels: docs-approved, auto-update-docker

#37127 Update README.md
  Packs/GenericWebhook/Integrations/GenericWebhook/README.md
Labels: docs-approved

#37121 Update README.md
  Packs/EDL/Integrations/EDL/README.md
Labels: docs-approved

#37155 [Xsup 43700] LinkToPhishingCampaign -Fixed the incident links
  Packs/Phishing/ReleaseNotes/3_6_25.md
  Packs/Phishing/Scripts/LinkToPhishingCampaign/LinkToPhishingCampaign.py
  Packs/Phishing/Scripts/LinkToPhishingCampaign/README.md
  Packs/Phishing/pack_metadata.json
Labels: docs-approved

#37124 Aud demisto/auto update docker staging branch 37
  Packs/CiscoWebExFeed/Integrations/CiscoWebExFeed/CiscoWebExFeed.yml
  Packs/CiscoWebExFeed/ReleaseNotes/1_2_16.md
  Packs/CiscoWebExFeed/pack_metadata.json
  Packs/CommonScripts/ReleaseNotes/1_15_83.md
  Packs/CommonScripts/Scripts/HTMLtoMD/HTMLtoMD.yml
  Packs/CyberArkEPM/Integrations/CyberArkEPMEventCollector/CyberArkEPMEventCollector.yml
  Packs/CyberArkEPM/ReleaseNotes/1_0_5.md
  Packs/CyberArkEPM/pack_metadata.json
  Packs/EmailCommunication/ReleaseNotes/2_0_33.md
  Packs/EmailCommunication/Scripts/DisplayEmailHtmlThread/DisplayEmailHtmlThread.yml
  Packs/EmailCommunication/pack_metadata.json
  Packs/FeedAzureADConnectHealth/Integrations/AzureADConnectHealthFeed/AzureADConnectHealthFeed.yml
  Packs/FeedAzureADConnectHealth/ReleaseNotes/1_0_21.md
  Packs/FeedAzureADConnectHealth/pack_metadata.json
  Packs/FeedMicrosoftIntune/ReleaseNotes/1_0_21.md
  Packs/FeedZoom/Integrations/FeedZoom/FeedZoom.yml
  Packs/FeedZoom/ReleaseNotes/1_1_16.md
  Packs/FeedZoom/pack_metadata.json
  Packs/Jira/Integrations/JiraV3/JiraV3.yml
  Packs/Jira/ReleaseNotes/3_2_9.md
  Packs/Jira/pack_metadata.json
  Packs/jamf/Integrations/jamfV2/jamfV2.yml
  Packs/jamf/ReleaseNotes/2_2_3.md
  Packs/jamf/pack_metadata.json
Labels: docs-approved, auto-update-docker

#37165 Revert "Veeam Check for XSIAM v2.5"
  Packs/Veeam/.pack-ignore
  Packs/Veeam/README.md
  Packs/Veeam/ReleaseNotes/1_0_2.md
  Packs/Veeam/XSIAMDashboards/Veeam_Data_Platform_Monitoring_Dashboard.json
  Packs/Veeam/XSIAMDashboards/Veeam_Data_Platform_Monitoring_Dashboard_image.png
  Packs/Veeam/XSIAMDashboards/Veeam_Security_Activities_Dashboard.json
  Packs/Veeam/XSIAMDashboards/Veeam_Security_Activities_Dashboard_image.png
  Packs/Veeam/XSIAMReports/Veeam_All_Veeam_failed_multi-factor_authentication_events_for_the_last_24h.json
  Packs/Veeam/XSIAMReports/Veeam_All_Veeam_finished_jobs_for_the_last_24h.json
  Packs/Veeam/XSIAMReports/Veeam_All_Veeam_four-eyes_authorization_events_for_the_last_24h.json
  Packs/Veeam/XSIAMReports/Veeam_All_Veeam_malware_detection_events_for_the_last_24h.json
  Packs/Veeam/XSIAMReports/Veeam_All_Veeam_security_events_for_the_last_7_days.json
  Packs/Veeam/XSIAMReports/Veeam_All_Veeam_security_events_with_Critical_and_High_severity_for_the_last_24h.json
  Packs/Veeam/XSIAMReports/Veeam_All_Veeam_triggered_alarms_for_the_last_7_days.json
  Packs/Veeam/doc_files/Veeam_XSOAR_Dashboard.png
  Packs/Veeam/doc_files/Veeam_XSOAR_Playbooks.png
  Packs/Veeam/pack_metadata.json
Labels: ForceMerge

#37164 Bump image tags to latest in requested packs XSUP-44312
  Packs/Armis/Integrations/ArmisEventCollector/ArmisEventCollector.yml
  Packs/Armis/ReleaseNotes/1_1_18.md
  Packs/Armis/pack_metadata.json
  Packs/BitwardenPasswordManager/Integrations/BitwardenPasswordManager/BitwardenPasswordManager.yml
  Packs/BitwardenPasswordManager/ReleaseNotes/1_0_2.md
  Packs/BitwardenPasswordManager/pack_metadata.json
  Packs/CarbonBlackDefense/Integrations/CarbonBlackEndpointStandardV3/CarbonBlackEndpointStandardV3.yml
  Packs/CarbonBlackDefense/ReleaseNotes/4_0_4.md
  Packs/CarbonBlackDefense/pack_metadata.json
  Packs/DNSDB/Integrations/DNSDB_v2/DNSDB_v2.yml
  Packs/DNSDB/ReleaseNotes/2_1_24.md
  Packs/DNSDB/pack_metadata.json
  Packs/FeedCyrenThreatInDepth/ReleaseNotes/1_5_27.md
  Packs/FeedCyrenThreatInDepth/Scripts/CyrenThreatInDepthRenderRelated/CyrenThreatInDepthRenderRelated.yml
  Packs/FeedCyrenThreatInDepth/pack_metadata.json
  Packs/FeedRecordedFuture/Integrations/FeedRecordedFuture/FeedRecordedFuture.yml
  Packs/FeedRecordedFuture/ReleaseNotes/1_1_6.md
  Packs/FeedRecordedFuture/pack_metadata.json
  Packs/IntSight/Integrations/Rapid7ThreatCommand/Rapid7ThreatCommand.yml
  Packs/IntSight/ReleaseNotes/3_1_5.md
  Packs/IntSight/pack_metadata.json
  Packs/Rapid7AppSec/Integrations/Rapid7AppSec/Rapid7AppSec.yml
  Packs/Rapid7AppSec/ReleaseNotes/1_0_5.md
  Packs/Rapid7AppSec/pack_metadata.json
  Packs/Respond/Integrations/RespondAnalyst/RespondAnalyst.yml
  Packs/Respond/ReleaseNotes/1_0_9.md
  Packs/Respond/pack_metadata.json
  Packs/ThreatConnect/Integrations/ThreatConnectV3/ThreatConnectV3.yml
  Packs/ThreatConnect/ReleaseNotes/3_1_9.md
  Packs/ThreatConnect/pack_metadata.json
Labels: docs-approved

#37044 potential fix
  Packs/SplunkPy/Integrations/SplunkPy/SplunkPy.py
  Packs/SplunkPy/Integrations/SplunkPy/SplunkPy.yml
  Packs/SplunkPy/Integrations/SplunkPy/SplunkPy_test.py
  Packs/SplunkPy/ReleaseNotes/3_1_41.md
  Packs/SplunkPy/pack_metadata.json
Labels: docs-approved

#37162 Aud demisto/auto update docker staging branch 42
  Packs/Base/ReleaseNotes/1_34_46.md
  Packs/Base/Scripts/DBotFindSimilarIncidents/DBotFindSimilarIncidents.yml
  Packs/Base/Scripts/DBotPredictPhishingWords/DBotPredictPhishingWords.yml
  Packs/Base/Scripts/DBotPreprocessTextData/DBotPreprocessTextData.yml
  Packs/Base/Scripts/DBotTrainTextClassifierV2/DBotTrainTextClassifierV2.yml
  Packs/Base/Scripts/GetMLModelEvaluation/GetMLModelEvaluation.yml
  Packs/Base/pack_metadata.json
  Packs/ML/ReleaseNotes/1_4_14.md
  Packs/ML/Scripts/DBotPredictOutOfTheBoxV2/DBotPredictOutOfTheBoxV2.yml
  Packs/ML/pack_metadata.json
Labels: docs-approved

#37158 changed bearer to Bearer
  Packs/GuardiCore/Integrations/GuardiCoreV2/GuardiCoreV2.py
  Packs/GuardiCore/Integrations/GuardiCoreV2/GuardiCoreV2.yml
  Packs/GuardiCore/Integrations/GuardiCoreV2/GuardiCoreV2_test.py
  Packs/GuardiCore/ReleaseNotes/2_0_13.md
  Packs/GuardiCore/pack_metadata.json
Labels: docs-approved

#35282 10611 change path to relative md files scripts
  Packs/CommonScripts/ReleaseNotes/1_15_86.md
  Packs/CommonScripts/Scripts/EmailAskUser/README.md
  Packs/CommonScripts/Scripts/SetGridField/README.md
  Packs/CommonScripts/Scripts/SetMultipleValues/README.md
  Packs/CommonScripts/Scripts/SetMultipleValues/SetMultipleValues.yml
  Packs/CommonScripts/pack_metadata.json
  Packs/OpenPhish/Integrations/OpenPhish_v2/OpenPhish_v2.py
  Packs/OpenPhish/Integrations/OpenPhish_v2/OpenPhish_v2.yml
  Packs/OpenPhish/ReleaseNotes/2_0_19.md
  Packs/OpenPhish/pack_metadata.json
  Packs/PhishLabs/.pack-ignore
  Packs/PhishLabs/Integrations/PhishLabsIOC/PhishLabsIOC.py
  Packs/PhishLabs/Integrations/PhishLabsIOC/PhishLabsIOC.yml
  Packs/PhishLabs/ReleaseNotes/1_1_22.md
  Packs/PhishLabs/pack_metadata.json
  Packs/Slack/Scripts/SlackAsk/README.md
  Packs/Slack/Scripts/SlackAskV2/README.md
  Packs/Zoom/Scripts/ZoomAsk/README.md
Labels: docs-approved, ForceMerge

#36795 A mail forwarding google workspace
  Packs/Core/.pack-ignore
  Packs/Core/Playbooks/playbook-A_mail_forwarding_rule_was_configured_in_Google_Workspace.yml
  Packs/Core/Playbooks/playbook-A_mail_forwarding_rule_was_configured_in_Google_Workspace_README.md
  Packs/Core/ReleaseNotes/3_0_94.md
  Packs/Core/Triggers/Trigger_-_A_mail_forwarding_rule_was_configured_in_Google_Workspace.json
  Packs/Core/doc_files/A_mail_forwarding_rule_was_configured_in_Google_Workspace.png
  Packs/Core/pack_metadata.json
Labels: docs-approved, bypass.url

#36897 [ASM] EXPANDR-10510 Updated ServiceNow playbook
  Packs/CortexAttackSurfaceManagement/Playbooks/Cortex_ASM_-_ServiceNow_Notification.yml
  Packs/CortexAttackSurfaceManagement/ReleaseNotes/1_7_57.md
  Packs/CortexAttackSurfaceManagement/doc_files/Cortex_ASM_-_ServiceNow_Notification.png
  Packs/CortexAttackSurfaceManagement/pack_metadata.json
Labels: Contribution, docs-approved, Contribution Form Filled, Community, Xsoar Support Level, External PR, Security Review

#36471 mcafee dxl phishlabs file paths update
  Packs/McAfee_DXL/Integrations/McAfee_DXL/McAfee_DXL.yml
  Packs/McAfee_DXL/Integrations/McAfee_DXL/README.md
  Packs/McAfee_DXL/ReleaseNotes/1_0_6.md
  Packs/McAfee_DXL/doc_files/click_edit.png
  Packs/McAfee_DXL/doc_files/select_client_crt_file.png
  Packs/McAfee_DXL/pack_metadata.json
  Packs/PhishLabs/.pack-ignore
  Packs/PhishLabs/Integrations/PhishLabsIOC/README.md
  Packs/PhishLabs/doc_files/58381182-d8408200-7fc2-11e9-8726-8056cab1feea.png
Labels: docs-approved, ForceMerge

#37176 Displaymappedfield script pipe parse fix
  Packs/CommonScripts/ReleaseNotes/1_15_87.md
  Packs/CommonScripts/Scripts/diplayMappedFields/diplayMappedFields.py
  Packs/CommonScripts/Scripts/diplayMappedFields/diplayMappedFields.yml
  Packs/CommonScripts/pack_metadata.json
Labels: docs-approved

#37190 added rn
  Packs/VirusTotal/ReleaseNotes/2_6_24.md
  Packs/VirusTotal/pack_metadata.json
Labels: docs-approved

#37177 CRTX-139456 Parsing Rule Fixes for Cisco Catalyst and Azure Security Center
  Packs/AzureSecurityCenter/ParsingRules/AzureSecurityCenter/AzureSecurityCenter.xif
  Packs/AzureSecurityCenter/ReleaseNotes/2_0_33.md
  Packs/AzureSecurityCenter/pack_metadata.json
  Packs/CiscoCatalyst/ParsingRules/CiscoCatalyst/CiscoCatalyst.xif
  Packs/CiscoCatalyst/ReleaseNotes/1_0_7.md
  Packs/CiscoCatalyst/pack_metadata.json
Labels: docs-approved, bypass.url

#37160 RSS Feed - add user-agent header
  Packs/FeedRSS/Integrations/FeedRSS/FeedRSS.py
  Packs/FeedRSS/ReleaseNotes/1_0_13.md
  Packs/FeedRSS/pack_metadata.json
Labels: docs-approved, release-notes-only

#37133 Add Sub Resolution Option When Closing An Insight
  Packs/SumoLogic_Cloud_SIEM/Integrations/SumoLogicCloudSIEM/README.md
  Packs/SumoLogic_Cloud_SIEM/Integrations/SumoLogicCloudSIEM/SumoLogicCloudSIEM.py
  Packs/SumoLogic_Cloud_SIEM/Integrations/SumoLogicCloudSIEM/SumoLogicCloudSIEM_test.py
  Packs/SumoLogic_Cloud_SIEM/ReleaseNotes/1_1_25.md
  Packs/SumoLogic_Cloud_SIEM/pack_metadata.json
Labels: Contribution, docs-approved, Partner, Contribution Form Filled, Partner Support Level, External PR, Partner-Approved

#37171 Google Workspace - Parsing Rule Update
  Packs/GoogleChrome/ParsingRules/GoogleChrome/GoogleChrome.xif
  Packs/GoogleChrome/ReleaseNotes/1_0_3.md
  Packs/GoogleChrome/pack_metadata.json
Labels: docs-approved

#37195 script update in M integrations
  Packs/Maltiverse/Integrations/Maltiverse/README.md
  Packs/McAfee-MAR/Integrations/McAfee-MAR/README.md
  Packs/McAfee-MAR/doc_files/51327213-7eaad280-1a79-11e9-98a4-f38eaac9eb5f.png
  Packs/McAfee-MAR/doc_files/51330887-237cde00-1a81-11e9-9cbf-e748467a1e87.png
  Packs/McAfee-MAR/doc_files/51332801-15c95780-1a85-11e9-9c10-9c80ce2644a5.png
  Packs/McAfee-MAR/doc_files/53962321-6f4c1b00-40f3-11e9-9694-46e36aa9a85c.png
  Packs/McAfee-MAR/doc_files/53962359-8c80e980-40f3-11e9-95ec-01be67333154.png
  Packs/McAfee-MAR/doc_files/53962402-a7535e00-40f3-11e9-90d7-65d334ae475f.png
  Packs/McAfee-MAR/doc_files/53962439-c18d3c00-40f3-11e9-9716-4876d3291139.png
  Packs/McAfee-MAR/doc_files/53962484-db2e8380-40f3-11e9-80d6-a3b6b5b3f688.png
  Packs/McAfee-MAR/doc_files/53962572-192ba780-40f4-11e9-8e89-f8b1bd3bb2d4.png
  Packs/McAfee-MAR/doc_files/53962702-6e67b900-40f4-11e9-825a-06f1e377c323.png
  Packs/McAfee-MAR/doc_files/53962741-88a19700-40f4-11e9-8443-73e9bba8badb.png
  Packs/McAfee-MAR/doc_files/integration-McAfee-MAR_McAfee_Active_Response.png
  Packs/McAfee-TIE/Integrations/McAfee-TIE/README.md
  Packs/McAfee-TIE/doc_files/62193823-43228680-b381-11e9-94c6-1a31e905b14e.png
  Packs/McAfee-TIE/doc_files/62193925-7402bb80-b381-11e9-948e-a9467a62b61b.png
  Packs/McAfee-TIE/doc_files/62193959-8e3c9980-b381-11e9-8f6a-c2c90c57118a.png
  Packs/McAfeeNSM/Integrations/McAfeeNSM/README.md
  Packs/McAfeeNSM/doc_files/46800139-7565e780-cd5f-11e8-81d6-02f79db8dddf.png
  Packs/McAfeeNSM/doc_files/46800212-a5ad8600-cd5f-11e8-8f11-86ebf0f2ca56.png
  Packs/McAfeeNSM/doc_files/46800465-6cc1e100-cd60-11e8-972a-35871783836f.png
  Packs/McAfeeNSM/doc_files/46800954-ead2b780-cd61-11e8-90d5-b2ee2a75980e.png
  Packs/McAfeeNSM/doc_files/46801086-4bfa8b00-cd62-11e8-90f6-f292a615d366.png
  Packs/McAfee_Advanced_Threat_Defense/Integrations/McAfee_Advanced_Threat_Defense/README.md
  Packs/McAfee_Advanced_Threat_Defense/doc_files/40072030-28d30712-587b-11e8-812a-4fedbf7c1001.png
  Packs/McAfee_Advanced_Threat_Defense/doc_files/40295195-22d87fb2-5ce1-11e8-970a-6cf5056b56de.png
  Packs/McAfee_Advanced_Threat_Defense/doc_files/40305260-6b07b0f2-5d02-11e8-8c6a-1ade6c796ef4.png
  Packs/McAfee_Advanced_Threat_Defense/doc_files/40305663-1b4031a0-5d04-11e8-8860-dcb5ddfb2654.png
  Packs/McAfee_Advanced_Threat_Defense/doc_files/40306682-4b9ef512-5d08-11e8-900e-088899639569.png
  Packs/McAfee_Advanced_Threat_Defense/doc_files/40610544-7cbb0438-627b-11e8-9842-77cec02258c9.png
  Packs/McAfee_Advanced_Threat_Defense/doc_files/40611388-ce82cef6-627e-11e8-97d5-c41379e1e6b4.png
  Packs/McAfee_Advanced_Threat_Defense/doc_files/40612912-138722f8-6285-11e8-81d8-f912aefc07d7.png
  Packs/Microsoft365Defender/Integrations/O365DefenderSafeLinks/O365DefenderSafeLinks_description.md
  Packs/Microsoft365Defender/ReleaseNotes/4_5_35.md
  Packs/Microsoft365Defender/doc_files/credentials_example.png
  Packs/Microsoft365Defender/pack_metadata.json
  Packs/MicrosoftTeams/Integrations/MicrosoftTeams/README.md
Labels: docs-approved

#37065 SplunkPy: fix the Server URL param
  Packs/SplunkPy/Integrations/SplunkPy/SplunkPy.py
  Packs/SplunkPy/Integrations/SplunkPy/SplunkPy_test.py
  Packs/SplunkPy/ReleaseNotes/3_1_43.md
  Packs/SplunkPy/pack_metadata.json
Labels: docs-approved

#37197 script update in N O Q integrations
  Packs/NutanixHypervisor/Integrations/NutanixHypervisor/NutanixHypervisor_description.md
  Packs/NutanixHypervisor/Integrations/NutanixHypervisor/README.md
  Packs/NutanixHypervisor/ReleaseNotes/1_0_24.md
  Packs/NutanixHypervisor/pack_metadata.json
  Packs/Office365AndAzureAuditLog/Integrations/MicrosoftPolicyAndComplianceAuditLog/MicrosoftPolicyAndComplianceAuditLog_description.md
  Packs/Office365AndAzureAuditLog/ReleaseNotes/2_0_3.md
  Packs/Office365AndAzureAuditLog/doc_files/credentials_example.png
  Packs/Office365AndAzureAuditLog/pack_metadata.json
  Packs/Okta/Integrations/Okta/README.md
  Packs/Okta/Integrations/Okta_IAM/README.md
  Packs/Okta/doc_files/43457688-4e6ba010-94d0-11e8-9697-89a0edda4ba3.png
  Packs/Okta/doc_files/43457838-c2f59d64-94d0-11e8-99d5-743216e3cf57.png
  Packs/Okta/doc_files/43458368-b70ff2a4-94d2-11e8-91b3-dd8467e3e076.png
  Packs/Okta/doc_files/43458391-cbbeda8a-94d2-11e8-99cd-7913ec999799.png
  Packs/Okta/doc_files/43460338-02e11d74-94d9-11e8-86d5-058fa1e15651.png
  Packs/Okta/doc_files/43460466-632e38c4-94d9-11e8-9f2a-2187b3076b18.png
  Packs/Okta/doc_files/43460554-9fa5d1fe-94d9-11e8-8769-eddc01050544.png
  Packs/Okta/doc_files/43461863-3629ab34-94dd-11e8-8959-58bafde323ef.png
  Packs/Okta/doc_files/43462076-ccb0ee46-94dd-11e8-8bac-9a54b5315c9a.png
  Packs/Okta/doc_files/43462420-baffa5ec-94de-11e8-853f-bf02b25c9690.png
  Packs/Okta/doc_files/43462731-91389038-94df-11e8-9fe5-39b030db28fe.png
  Packs/Okta/doc_files/43463068-64380af4-94e0-11e8-9824-b7f9f0d0ed43.png
  Packs/Okta/doc_files/43463112-8652d6dc-94e0-11e8-88a0-e53e59dc79e4.png
  Packs/Okta/doc_files/43464242-3cd6e748-94e3-11e8-974e-5d27d1b0ccbf.png
  Packs/Okta/doc_files/43464335-8cb9d3ec-94e3-11e8-900b-8b27c7789dd6.png
  Packs/Okta/doc_files/44389432-8189b180-a533-11e8-8984-b29dcd5851e5.png
  Packs/Okta/doc_files/44389475-a0884380-a533-11e8-8c0f-365e1b9bc723.png
  Packs/Okta/doc_files/49521506-3e6b0880-f8ae-11e8-9f2a-37ec8d49d5b0.png
  Packs/Okta/doc_files/49521733-c2bd8b80-f8ae-11e8-878f-e10e60a951ac.png
  Packs/Okta/doc_files/49521874-00221900-f8af-11e8-8ab8-5c50575a372c.png
  Packs/Okta/doc_files/gfskliw1i51ScX6pf0h7
  Packs/Okta/doc_files/gfsnda403rf16Qe790h7
  Packs/OpenLDAP/Integrations/OpenLDAP/README.md
  Packs/OpenPhish/Integrations/OpenPhish_v2/README.md
  Packs/QRadar/Integrations/QRadar/README.md
  Packs/QRadar/doc_files/47648599-299aa700-db83-11e8-934f-bf3394767da9.png
  Packs/QRadar/doc_files/47648802-cbba8f00-db83-11e8-8f08-bd00838990af.png
  Packs/QRadar/doc_files/47649297-84350280-db85-11e8-8ada-f478394b3c41.png
  Packs/QRadar/doc_files/47649648-89df1800-db86-11e8-8c2f-a164c8c7517f.png
  Packs/QRadar/doc_files/47650820-10e1bf80-db8a-11e8-9577-3c639cc88472.png
  Packs/QRadar/doc_files/47650998-a67d4f00-db8a-11e8-8cb1-9791acccdff4.png
  Packs/QRadar/doc_files/47652269-278a1580-db8e-11e8-913a-f761a9338f25.png
  Packs/QRadar/doc_files/47652373-69b35700-db8e-11e8-80cf-e42e65bcd3c1.png
  Packs/QRadar/doc_files/47652469-b5fe9700-db8e-11e8-89ec-eab5dd6af828.png
  Packs/QRadar/doc_files/47652630-1d1c4b80-db8f-11e8-9dd7-52947cfa8927.png
  Packs/QRadar/doc_files/47652885-da0ea800-db8f-11e8-9d8b-e5e46cb8cb17.png
  Packs/QRadar/doc_files/48839982-f91ae700-ed95-11e8-85f4-6bce65b27f33.png
  Packs/QRadar/doc_files/49079426-345f5f00-f249-11e8-8855-aecf575781f0.png
  Packs/QRadar/doc_files/49080365-10514d00-f24c-11e8-92a1-e61367eb9fb1.png
  Packs/QRadar/doc_files/49080464-632b0480-f24c-11e8-91cd-3560d2626c2f.png
  Packs/QRadar/doc_files/49081012-1811f100-f24e-11e8-81e6-af9cdf4f1a5a.png
  Packs/QRadar/doc_files/49081049-37108300-f24e-11e8-9554-95b2adccd563.png
  Packs/epo/Integrations/epoV2/README.md
  Packs/epo/Integrations/epoV2/epoV2_description.md
  Packs/epo/ReleaseNotes/2_0_37.md
  Packs/epo/pack_metadata.json
Labels: docs-approved

#37180 [FindDuplicateEmailIncidents] fix performance issues
  Packs/Phishing/ReleaseNotes/3_6_26.md
  Packs/Phishing/Scripts/FindDuplicateEmailIncidents/FindDuplicateEmailIncidents.py
  Packs/Phishing/Scripts/FindDuplicateEmailIncidents/FindDuplicateEmailIncidents.yml
  Packs/Phishing/pack_metadata.json
Labels: docs-approved

#37186 [TAXII2Server] Fix longRunningPort
  Packs/TAXIIServer/Integrations/TAXII2Server/TAXII2Server.py
  Packs/TAXIIServer/ReleaseNotes/2_0_70.md
  Packs/TAXIIServer/pack_metadata.json
Labels: ForceMerge

#37172 XDR IR fix when close_xdr_incident is False
  Packs/CortexXDR/Integrations/CortexXDRIR/CortexXDRIR.py
  Packs/CortexXDR/Integrations/CortexXDRIR/CortexXDRIR.yml
  Packs/CortexXDR/Integrations/CortexXDRIR/CortexXDRIR_test.py
  Packs/CortexXDR/ReleaseNotes/6_1_88.md
  Packs/CortexXDR/pack_metadata.json
Labels: docs-approved

#37200 Bug fix/CIAC-12171/update discovery url in TAXII feed
  Packs/FeedTAXII/Integrations/FeedTAXII/FeedTAXII.yml
  Packs/FeedTAXII/Integrations/FeedTAXII/FeedTAXII_description.md
  Packs/FeedTAXII/Integrations/FeedTAXII/README.md
  Packs/FeedTAXII/ReleaseNotes/1_2_21.md
  Packs/FeedTAXII/pack_metadata.json
Labels: docs-approved, ForceMerge

#36915 MS Entra Enhancement
  Packs/MicrosoftEntraID/ModelingRules/MicrosoftEntraID/MicrosoftEntraID.xif
  Packs/MicrosoftEntraID/ModelingRules/MicrosoftEntraID/MicrosoftEntraID_schema.json
  Packs/MicrosoftEntraID/ParsingRules/MicrosoftEntraID/MicrosoftEntraID.xif
  Packs/MicrosoftEntraID/README.md
  Packs/MicrosoftEntraID/ReleaseNotes/1_0_1.md
  Packs/MicrosoftEntraID/doc_files/MicrosoftEntraID_Azure_Event_Hub.png
  Packs/MicrosoftEntraID/doc_files/MicrosoftEntraID_Office_365.png
  Packs/MicrosoftEntraID/pack_metadata.json
  Packs/Office365/README.md
Labels: docs-approved

#37211 fix image
  Packs/Office365AndAzureAuditLog/doc_files/credentials_example.png
Labels: docs-approved, bypass.url

#37166 Update TAXII Service integration README.md
  Packs/TAXIIServer/Integrations/TAXIIServer/README.md
Labels: docs-approved

#37169 Update the TAXII2 Server Integration README.md
  Packs/TAXIIServer/Integrations/TAXII2Server/README.md
Labels: docs-approved

#37170 Update Web File Repository Integration README.md
  Packs/WebFileRepository/Integrations/WebFileRepository/README.md
Labels: docs-approved

#37191 Aud demisto/auto update docker staging branch 43
  Packs/PcapAnalysis/ReleaseNotes/2_4_10.md
  Packs/PcapAnalysis/Scripts/PcapConvert/PcapConvert.yml
  Packs/PcapAnalysis/Scripts/PcapExtractStreams/PcapExtractStreams.yml
  Packs/PcapAnalysis/Scripts/PcapFileExtractStreams/PcapFileExtractStreams.yml
  Packs/PcapAnalysis/Scripts/PcapFileExtractor/PcapFileExtractor.yml
  Packs/PcapAnalysis/Scripts/PcapMinerV2/PcapMinerV2.yml
  Packs/PcapAnalysis/pack_metadata.json
Labels: docs-approved

#37187 Microsoft Windows Events modeling enhancement
  Packs/MicrosoftWindowsEvents/ModelingRules/MicrosoftWindowsEvents_1_3/MicrosoftWindowsEvents_1_3.xif
  Packs/MicrosoftWindowsEvents/ReleaseNotes/1_1_9.md
  Packs/MicrosoftWindowsEvents/pack_metadata.json
Labels: docs-approved

#37204 Finish CyberArk PAS Pack Adoption
  Packs/CyberArkPAS/Author_image.png
  Packs/CyberArkPAS/README.md
  Packs/CyberArkPAS/ReleaseNotes/1_0_15.md
  Packs/CyberArkPAS/pack_metadata.json
Labels: docs-approved

#37220 Update TAXII2 Integration README.md
  Packs/TAXIIServer/Integrations/TAXII2Server/README.md
Labels: docs-approved

#36694 Symantec Endpoint Security (New pack)
  Packs/SymantecEndpointSecurity/.pack-ignore
  Packs/SymantecEndpointSecurity/.secrets-ignore
  Packs/SymantecEndpointSecurity/Integrations/SymantecEndpointSecurity/README.md
  Packs/SymantecEndpointSecurity/Integrations/SymantecEndpointSecurity/SymantecEndpointSecurity.py
  Packs/SymantecEndpointSecurity/Integrations/SymantecEndpointSecurity/SymantecEndpointSecurity.yml
  Packs/SymantecEndpointSecurity/Integrations/SymantecEndpointSecurity/SymantecEndpointSecurity_description.md
  Packs/SymantecEndpointSecurity/Integrations/SymantecEndpointSecurity/SymantecEndpointSecurity_image.png
  Packs/SymantecEndpointSecurity/Integrations/SymantecEndpointSecurity/SymantecEndpointSecurity_test.py
  Packs/SymantecEndpointSecurity/README.md
  Packs/SymantecEndpointSecurity/pack_metadata.json
Labels: docs-approved

#37014 Add support for execution metrics to GenericSQL integration.
  Packs/GenericSQL/CONTRIBUTORS.json
  Packs/GenericSQL/Integrations/GenericSQL/GenericSQL.py
  Packs/GenericSQL/Integrations/GenericSQL/GenericSQL_test.py
  Packs/GenericSQL/ReleaseNotes/1_3_4.md
  Packs/GenericSQL/pack_metadata.json
Labels: Contribution, docs-approved, Contribution Form Filled, Community, Xsoar Support Level, External PR

#37217 Akamai - fix docker timeout due to integration context not json serializable
  Packs/Akamai_SIEM/Integrations/Akamai_SIEM/Akamai_SIEM.py
  Packs/Akamai_SIEM/Integrations/Akamai_SIEM/Akamai_SIEM.yml
  Packs/Akamai_SIEM/Integrations/Akamai_SIEM/Akamai_SIEM_test.py
  Packs/Akamai_SIEM/Integrations/Akamai_SIEM/README.md
  Packs/Akamai_SIEM/ReleaseNotes/1_1_6.md
  Packs/Akamai_SIEM/ReleaseNotes/1_1_7.md
  Packs/Akamai_SIEM/pack_metadata.json
Labels: docs-approved

#36892 XSIAM Analytics Playbooks Effort - Unsigned and unpopular process performed an injection
  Packs/Core/Playbooks/playbook-Unsigned_and_unpopular_process_performed_an_injection.yml
  Packs/Core/Playbooks/playbook-Unsigned_and_unpopular_process_performed_an_injection_README.md
  Packs/Core/ReleaseNotes/3_0_95.md
  Packs/Core/Triggers/Trigger_-_Unsigned_and_unpopular_process_performed_an_injection.json
  Packs/Core/doc_files/Unsigned_and_unpopular_process_performed_an_injection.png
  Packs/Core/pack_metadata.json
Labels: docs-approved

#37233 Add logs XDR-IR
  Packs/CortexXDR/Integrations/CortexXDRIR/CortexXDRIR.py
  Packs/CortexXDR/ReleaseNotes/6_1_90.md
  Packs/CortexXDR/pack_metadata.json
Labels: docs-approved

#37231 replace-on-call
  .github/content_roles.json
Labels: docs-approved

#37224 Enrichment for Verdict test
  Tests/conf.json
Labels: docs-approved

#37232 CiscoWebex event collector fixed OAuth test command
  Packs/CiscoSpark/Integrations/CiscoWebexEventCollector/CiscoWebexEventCollector.py
  Packs/CiscoSpark/Integrations/CiscoWebexEventCollector/CiscoWebexEventCollector.yml
  Packs/CiscoSpark/Integrations/CiscoWebexEventCollector/CiscoWebexEventCollector_test.py
  Packs/CiscoSpark/ReleaseNotes/1_0_11.md
  Packs/CiscoSpark/pack_metadata.json
Labels: docs-approved, release-notes-only

#37031 Ibm maas360 security collector
  Packs/IBMMaaS360Security/.pack-ignore
  Packs/IBMMaaS360Security/.secrets-ignore
  Packs/IBMMaaS360Security/Integrations/IBMMaaS360SecurityEventCollector/IBMMaaS360SecurityEventCollector.py
  Packs/IBMMaaS360Security/Integrations/IBMMaaS360SecurityEventCollector/IBMMaaS360SecurityEventCollector.yml
  Packs/IBMMaaS360Security/Integrations/IBMMaaS360SecurityEventCollector/IBMMaaS360SecurityEventCollector_description.md
  Packs/IBMMaaS360Security/Integrations/IBMMaaS360SecurityEventCollector/IBMMaaS360SecurityEventCollector_image.png
  Packs/IBMMaaS360Security/Integrations/IBMMaaS360SecurityEventCollector/IBMMaaS360SecurityEventCollector_test.py
  Packs/IBMMaaS360Security/Integrations/IBMMaaS360SecurityEventCollector/README.md
  Packs/IBMMaaS360Security/Integrations/IBMMaaS360SecurityEventCollector/command_examples
  Packs/IBMMaaS360Security/Integrations/IBMMaaS360SecurityEventCollector/test_data/mock_admin_changes.json
  Packs/IBMMaaS360Security/Integrations/IBMMaaS360SecurityEventCollector/test_data/mock_login_events.json
  Packs/IBMMaaS360Security/README.md
  Packs/IBMMaaS360Security/doc_files/admin-read-only-role.png
  Packs/IBMMaaS360Security/doc_files/administrators-page.png
  Packs/IBMMaaS360Security/doc_files/edit-admin-roles.png
  Packs/IBMMaaS360Security/doc_files/find-billing-id.png
  Packs/IBMMaaS360Security/doc_files/generate-key.png
  Packs/IBMMaaS360Security/doc_files/generate-key2.png
  Packs/IBMMaaS360Security/doc_files/generate-key3.png
  Packs/IBMMaaS360Security/doc_files/manage-access-keys.png
  Packs/IBMMaaS360Security/pack_metadata.json
Labels: docs-approved

#36814 Generic SQL yml description
  Packs/GenericSQL/Integrations/GenericSQL/GenericSQL.yml
  Packs/GenericSQL/ReleaseNotes/1_3_5.md
  Packs/GenericSQL/pack_metadata.json
Labels: docs-approved

#37185 Generic SQL Trino support
  Packs/GenericSQL/Integrations/GenericSQL/GenericSQL.py
  Packs/GenericSQL/Integrations/GenericSQL/GenericSQL.yml
  Packs/GenericSQL/Integrations/GenericSQL/GenericSQL_description.md
  Packs/GenericSQL/Integrations/GenericSQL/GenericSQL_test.py
  Packs/GenericSQL/Integrations/GenericSQL/README.md
  Packs/GenericSQL/ReleaseNotes/1_3_6.md
  Packs/GenericSQL/pack_metadata.json
Labels: docs-approved

#37022 Add Defender for Endpoint File Indicator to file statistics command
  Packs/Base/ReleaseNotes/1_35_0.md
  Packs/Base/Scripts/CommonServerPython/CommonServerPython.py
  Packs/Base/Scripts/CommonServerPython/CommonServerPython_test.py
  Packs/Base/pack_metadata.json
  Packs/CommonTypes/IndicatorFields/indicatorfield-globalprevalence.json
  Packs/CommonTypes/IndicatorFields/indicatorfield-organizationfirstseen.json
  Packs/CommonTypes/IndicatorFields/indicatorfield-organizationlastseen.json
  Packs/CommonTypes/IndicatorFields/indicatorfield-organizationprevalence.json
  Packs/CommonTypes/IndicatorTypes/reputation-domain.json
  Packs/CommonTypes/IndicatorTypes/reputation-file.json
  Packs/CommonTypes/IndicatorTypes/reputation-ip.json
  Packs/CommonTypes/IndicatorTypes/reputation-ipv6.json
  Packs/CommonTypes/IndicatorTypes/reputation-url.json
  Packs/CommonTypes/ReleaseNotes/3_6_0.md
  Packs/CommonTypes/pack_metadata.json
  Packs/MicrosoftDefenderAdvancedThreatProtection/Integrations/MicrosoftDefenderAdvancedThreatProtection/MicrosoftDefenderAdvancedThreatProtection.py
  Packs/MicrosoftDefenderAdvancedThreatProtection/Integrations/MicrosoftDefenderAdvancedThreatProtection/MicrosoftDefenderAdvancedThreatProtection.yml
  Packs/MicrosoftDefenderAdvancedThreatProtection/Integrations/MicrosoftDefenderAdvancedThreatProtection/MicrosoftDefenderAdvancedThreatProtection_test.py
  Packs/MicrosoftDefenderAdvancedThreatProtection/Integrations/MicrosoftDefenderAdvancedThreatProtection/README.md
  Packs/MicrosoftDefenderAdvancedThreatProtection/ReleaseNotes/1_17_0.md
  Packs/MicrosoftDefenderAdvancedThreatProtection/pack_metadata.json
Labels: enhancement, docs-approved, python, ignore-auto-bump-version

#36746 Checkpoint Publish and Install playbook fix
  Packs/CheckpointFirewall/Playbooks/Checkpoint_-_Publish&Install_configuration.yml
  Packs/CheckpointFirewall/ReleaseNotes/2_3_22.md
  Packs/CheckpointFirewall/pack_metadata.json
Labels: docs-approved

#37225 Aud demisto/auto update docker staging branch 46
  Packs/CommonScripts/ReleaseNotes/1_15_89.md
  Packs/CommonScripts/Scripts/ConvertXmlFileToJson/ConvertXmlFileToJson.yml
  Packs/CommonScripts/pack_metadata.json
  Packs/FeedDHS/Integrations/DHS_Feed/DHS_Feed.yml
  Packs/FeedDHS/ReleaseNotes/2_0_44.md
  Packs/FeedDHS/pack_metadata.json
  Packs/GenetecSecurityCenter/Integrations/GenetecSecurityCenterEventCollector/GenetecSecurityCenterEventCollector.yml
  Packs/GenetecSecurityCenter/ReleaseNotes/1_0_1.md
  Packs/GenetecSecurityCenter/pack_metadata.json
  Packs/PaloAltoNetworksAutomaticSLR_Community/Integrations/PaloAltoNetworksAutomaticSLRCommunity/PaloAltoNetworksAutomaticSLRCommunity.yml
  Packs/PaloAltoNetworksAutomaticSLR_Community/ReleaseNotes/1_0_4.md
  Packs/PaloAltoNetworksAutomaticSLR_Community/pack_metadata.json
Labels: docs-approved

#37251 F5 APM Parsing Update
  Packs/CyberArkEPV/README.md
  Packs/F5APM/ParsingRules/F5APM/F5APM.xif
  Packs/F5APM/ParsingRules/F5APM/F5APM.yml
  Packs/F5APM/README.md
  Packs/F5APM/ReleaseNotes/1_0_1.md
  Packs/F5APM/pack_metadata.json
Labels: docs-approved

#37249 Revert ML docker updates
  Packs/Base/ReleaseNotes/1_35_1.md
  Packs/Base/Scripts/DBotFindSimilarIncidents/DBotFindSimilarIncidents.yml
  Packs/Base/Scripts/DBotPredictPhishingWords/DBotPredictPhishingWords.yml
  Packs/Base/Scripts/DBotPreprocessTextData/DBotPreprocessTextData.yml
  Packs/Base/Scripts/DBotTrainTextClassifierV2/DBotTrainTextClassifierV2.yml
  Packs/Base/Scripts/GetMLModelEvaluation/GetMLModelEvaluation.yml
  Packs/Base/pack_metadata.json
  Packs/ML/ReleaseNotes/1_4_15.md
  Packs/ML/Scripts/DBotPredictOutOfTheBoxV2/DBotPredictOutOfTheBoxV2.yml
  Packs/ML/pack_metadata.json
Labels: docs-approved, ForceMerge

#37230 Aud demisto/auto update docker staging branch 48
  Packs/GCP-IAM/Integrations/GCPIAM/GCPIAM.yml
  Packs/GCP-IAM/ReleaseNotes/1_0_30.md
  Packs/GCP-IAM/pack_metadata.json
  Packs/Gmail/Integrations/Gmail/Gmail.yml
  Packs/Gmail/ReleaseNotes/1_3_28.md
  Packs/Gmail/pack_metadata.json
  Packs/GmailSingleUser/Integrations/GmailSingleUser/GmailSingleUser.yml
  Packs/GmailSingleUser/ReleaseNotes/1_4_8.md
  Packs/GmailSingleUser/pack_metadata.json
  Packs/GoogleCloudFunctions/Integrations/GoogleCloudFunctions/GoogleCloudFunctions.yml
  Packs/GoogleCloudFunctions/ReleaseNotes/1_0_31.md
  Packs/GoogleCloudFunctions/pack_metadata.json
  Packs/GoogleCloudLogging/Integrations/GoogleCloudLogging/GoogleCloudLogging.yml
  Packs/GoogleCloudLogging/ReleaseNotes/1_0_17.md
  Packs/GoogleCloudLogging/pack_metadata.json
  Packs/GoogleCloudSCC/Integrations/GoogleCloudSCC/GoogleCloudSCC.yml
  Packs/GoogleCloudSCC/ReleaseNotes/2_1_24.md
  Packs/GoogleCloudSCC/pack_metadata.json
Labels: docs-approved

#36880 ServiceNow - append syslog transactions logs
  Packs/ServiceNow/Integrations/ServiceNowEventCollector/README.md
  Packs/ServiceNow/Integrations/ServiceNowEventCollector/ServiceNowEventCollector.py
  Packs/ServiceNow/Integrations/ServiceNowEventCollector/ServiceNowEventCollector.yml
  Packs/ServiceNow/Integrations/ServiceNowEventCollector/ServiceNowEventCollector_description.md
  Packs/ServiceNow/Integrations/ServiceNowEventCollector/ServiceNowEventCollector_test.py
  Packs/ServiceNow/ReleaseNotes/2_7_0.md
  Packs/ServiceNow/pack_metadata.json
Labels: docs-approved

#37214 Aud demisto/auto update docker staging branch 44
  Packs/Base/ReleaseNotes/1_35_2.md
  Packs/Base/Scripts/CommonServerPowerShell/CommonServerPowerShell.yml
  Packs/Base/pack_metadata.json
  Packs/CommonScripts/ReleaseNotes/1_15_90.md
  Packs/CommonScripts/Scripts/VerifyJSON/VerifyJSON.yml
  Packs/CommonScripts/pack_metadata.json
  Packs/CommunityCommonScripts/ReleaseNotes/1_3_3.md
  Packs/CommunityCommonScripts/Scripts/CalculateTimeSpan/CalculateTimeSpan.yml
  Packs/CommunityCommonScripts/Scripts/VersionEqualTo/VersionEqualTo.yml
  Packs/CommunityCommonScripts/Scripts/VersionGreaterThan/VersionGreaterThan.yml
  Packs/CommunityCommonScripts/Scripts/VersionLessThan/VersionLessThan.yml
  Packs/CommunityCommonScripts/pack_metadata.json
Labels: docs-approved

#37260 Aud demisto/auto update docker staging branch 45
  Packs/CofenseTriage/Integrations/CofenseTriagev2/CofenseTriagev2.yml
  Packs/CofenseTriage/ReleaseNotes/2_1_30.md
  Packs/CofenseTriage/pack_metadata.json
Labels: docs-approved

#34466 Add Sekoia XDR pack
  Packs/SekoiaXDR/Classifiers/classifier-Sekoia_XDR_-_Incoming_Mapper.json
  Packs/SekoiaXDR/IncidentFields/incident_sekoia_xdr_mirrorout_field.json
  Packs/SekoiaXDR/Integrations/SekoiaXDR/README.md
  Packs/SekoiaXDR/Integrations/SekoiaXDR/SekoiaXDR.py
  Packs/SekoiaXDR/Integrations/SekoiaXDR/SekoiaXDR.yml
  Packs/SekoiaXDR/Integrations/SekoiaXDR/SekoiaXDR_description.md
  Packs/SekoiaXDR/Integrations/SekoiaXDR/SekoiaXDR_test.py
  Packs/SekoiaXDR/Layouts/layoutscontainer-Sekoia_XDR_Layout.json
  Packs/SekoiaXDR/ReleaseNotes/1_1_0.md
  Packs/SekoiaXDR/Scripts/SekoiaXDRChangeStatus/README.md
  Packs/SekoiaXDR/Scripts/SekoiaXDRChangeStatus/SekoiaXDRChangeStatus.py
  Packs/SekoiaXDR/Scripts/SekoiaXDRChangeStatus/SekoiaXDRChangeStatus.yml
  Packs/SekoiaXDR/Scripts/SekoiaXDRChangeStatus/SekoiaXDRChangeStatus_test.py
  Packs/SekoiaXDR/Scripts/SekoiaXDRCloseAlert/SekoiaXDRCloseAlert.py
  Packs/SekoiaXDR/Scripts/SekoiaXDRCloseAlert/SekoiaXDRCloseAlert_test.py
  Packs/SekoiaXDR/pack_metadata.json
Labels: Contribution, docs-approved, Partner, pending-demo, post-demo, Contribution Form Filled, External PR, Partner-Approved

#37248 [CSP - Account] Added an option to receive custom fields
  Packs/Base/ReleaseNotes/1_35_3.md
  Packs/Base/Scripts/CommonServerPython/CommonServerPython.py
  Packs/Base/Scripts/CommonServerPython/CommonServerPython_test.py
  Packs/Base/pack_metadata.json
Labels: docs-approved

#37246 XDR IR fix in close_xdr_incident error 500
  Packs/CortexXDR/Integrations/CortexXDRIR/CortexXDRIR.py
  Packs/CortexXDR/Integrations/CortexXDRIR/CortexXDRIR.yml
  Packs/CortexXDR/Integrations/CortexXDRIR/CortexXDRIR_description.md
  Packs/CortexXDR/Integrations/CortexXDRIR/CortexXDRIR_test.py
  Packs/CortexXDR/ReleaseNotes/6_1_91.md
  Packs/CortexXDR/pack_metadata.json
Labels: docs-approved

#37156 CRTX-133201 AWS CloudTrail Audit Logs XDM Modeling
  Packs/AWS-CloudTrail/ModelingRules/AWSCloudTrail/AWSCloudTrail.xif
  Packs/AWS-CloudTrail/ModelingRules/AWSCloudTrail/AWSCloudTrail.yml
  Packs/AWS-CloudTrail/ModelingRules/AWSCloudTrail/AWSCloudTrail_schema.json
  Packs/AWS-CloudTrail/ParsingRules/AWSCloudTrail/AWSCloudTrail.xif
  Packs/AWS-CloudTrail/ParsingRules/AWSCloudTrail/AWSCloudTrail.yml
  Packs/AWS-CloudTrail/README.md
  Packs/AWS-CloudTrail/ReleaseNotes/1_1_6.md
  Packs/AWS-CloudTrail/doc_files/Amazon_S3_DataSource_Config.png
  Packs/AWS-CloudTrail/pack_metadata.json
Labels: docs-approved

#37287 Aud demisto/auto update docker staging branch 52
  Packs/Base/ReleaseNotes/1_35_4.md
  Packs/Base/Scripts/CommonServerPowerShell/CommonServerPowerShell.yml
  Packs/Base/pack_metadata.json
  Packs/CommonScripts/ReleaseNotes/1_15_91.md
  Packs/CommonScripts/Scripts/VerifyJSON/VerifyJSON.yml
  Packs/CommonScripts/pack_metadata.json
  Packs/CommunityCommonScripts/ReleaseNotes/1_3_4.md
  Packs/CommunityCommonScripts/Scripts/CalculateTimeSpan/CalculateTimeSpan.yml
  Packs/CommunityCommonScripts/Scripts/VersionEqualTo/VersionEqualTo.yml
  Packs/CommunityCommonScripts/Scripts/VersionGreaterThan/VersionGreaterThan.yml
  Packs/CommunityCommonScripts/Scripts/VersionLessThan/VersionLessThan.yml
  Packs/CommunityCommonScripts/pack_metadata.json
Labels: docs-approved

#37281 demisto/py3-tools3:1.0.0.116158 | 0-100 | PR batch #1/1
  Packs/CommonWidgets/ReleaseNotes/1_2_52.md
  Packs/CommonWidgets/Scripts/RSSWidget/RSSWidget.yml
  Packs/CommonWidgets/pack_metadata.json
  Packs/JARM/Integrations/JARM/JARM.yml
  Packs/JARM/ReleaseNotes/1_0_16.md
  Packs/JARM/pack_metadata.json
  Packs/Zabbix/Integrations/Zabbix/Zabbix.yml
  Packs/Zabbix/ReleaseNotes/1_0_35.md
  Packs/Zabbix/pack_metadata.json
Labels: docs-approved, auto-update-docker

#37125 add a new modeling rule to shodan pack
  Packs/Shodan/ModelingRules/Shodan/Shodan.xif
  Packs/Shodan/ModelingRules/Shodan/Shodan.yml
  Packs/Shodan/ModelingRules/Shodan/Shodan_schema.json
  Packs/Shodan/README.md
  Packs/Shodan/ReleaseNotes/1_2_2.md
  Packs/Shodan/pack_metadata.json
Labels: docs-approved, bypass.url

#37302 [Microsoft Defender for Endpoint] fix for GCC High
  Packs/MicrosoftDefenderAdvancedThreatProtection/Integrations/Microsoft365DefenderEventCollector/Microsoft365DefenderEventCollector.py
  Packs/MicrosoftDefenderAdvancedThreatProtection/Integrations/MicrosoftDefenderAdvancedThreatProtection/MicrosoftDefenderAdvancedThreatProtection.py
  Packs/MicrosoftDefenderAdvancedThreatProtection/ReleaseNotes/1_17_3.md
  Packs/MicrosoftDefenderAdvancedThreatProtection/pack_metadata.json
Labels: docs-approved

#37304 Deprecated old modelingrule vmware exsi
  Packs/VMwareESXi/ModelingRules/VMwareESXiModelingRules/VMwareESXiModelingRules.xif
  Packs/VMwareESXi/ModelingRules/VMwareESXiModelingRules/VMwareESXiModelingRules.yml
  Packs/VMwareESXi/ModelingRules/VMwareESXiModelingRules/VMwareESXiModelingRules_schema.json
  Packs/VMwareESXi/ReleaseNotes/1_0_6.md
  Packs/VMwareESXi/pack_metadata.json
Labels: docs-approved, ForceMerge

#37307 ys splunk docs improvement
  Packs/SplunkPy/Integrations/SplunkPy/SplunkPy.py
  Packs/SplunkPy/Integrations/SplunkPy/SplunkPy_test.py
  Packs/SplunkPy/ReleaseNotes/3_1_46.md
  Packs/SplunkPy/pack_metadata.json
Labels: docs-approved

#37313 Add Note to SlackBlockBuilder README
  Packs/Slack/ReleaseNotes/3_5_3.md
  Packs/Slack/Scripts/SlackBlockBuilder/README.md
  Packs/Slack/pack_metadata.json
Labels: docs-approved

#37315 Aud demisto/auto update docker staging branch 55
  Packs/CyCognito/Integrations/CyCognito/CyCognito.yml
  Packs/CyCognito/ReleaseNotes/1_0_24.md
  Packs/CyCognito/Scripts/ThreeDigitAlphaCountryCodeToCountryName/ThreeDigitAlphaCountryCodeToCountryName.yml
  Packs/CyCognito/pack_metadata.json
  Packs/Cybersixgill-ActionableAlerts/Integrations/CybersixgillActionableAlerts/CybersixgillActionableAlerts.yml
  Packs/Cybersixgill-ActionableAlerts/ReleaseNotes/1_2_18.md
  Packs/Cybersixgill-ActionableAlerts/Scripts/CybersixgillActionableAlertStatusUpdate/CybersixgillActionableAlertStatusUpdate.yml
  Packs/Cybersixgill-ActionableAlerts/pack_metadata.json
  Packs/Cybersixgill-DVE/Integrations/CybersixgillDVEEnrichment/CybersixgillDVEEnrichment.yml
  Packs/Cybersixgill-DVE/Integrations/CybersixgillDVEFeed/CybersixgillDVEFeed.yml
  Packs/Cybersixgill-DVE/ReleaseNotes/1_0_7.md
  Packs/Cybersixgill-DVE/pack_metadata.json
  Packs/FeedCyCognito/Integrations/FeedCyCognito/FeedCyCognito.yml
  Packs/FeedCyCognito/ReleaseNotes/1_0_24.md
  Packs/FeedCyCognito/pack_metadata.json
  Packs/Infocyte/Integrations/Infocyte/Infocyte.yml
  Packs/Infocyte/ReleaseNotes/1_0_6.md
  Packs/Infocyte/pack_metadata.json
  Packs/OTRS/Integrations/OTRS/OTRS.yml
  Packs/OTRS/ReleaseNotes/1_1_1.md
  Packs/OTRS/pack_metadata.json
  Packs/Sixgill-Darkfeed/Integrations/Sixgill_Darkfeed/Sixgill_Darkfeed.yml
  Packs/Sixgill-Darkfeed/Integrations/Sixgill_Darkfeed_Enrichment/Sixgill_Darkfeed_Enrichment.yml
  Packs/Sixgill-Darkfeed/ReleaseNotes/2_2_23.md
  Packs/Sixgill-Darkfeed/pack_metadata.json
  Packs/XsoarWebserver/Integrations/XSOARWebServer/XSOARWebServer.yml
  Packs/XsoarWebserver/ReleaseNotes/1_0_4.md
  Packs/XsoarWebserver/pack_metadata.json
Labels: docs-approved

#36238 added modeling rule
  Packs/IBMSecurityVerify/ModelingRules/IBMSecurityVerify/IBMSecurityVerify.xif
  Packs/IBMSecurityVerify/ModelingRules/IBMSecurityVerify/IBMSecurityVerify.yml
  Packs/IBMSecurityVerify/ModelingRules/IBMSecurityVerify/IBMSecurityVerify_schema.json
  Packs/IBMSecurityVerify/ReleaseNotes/1_0_1.md
  Packs/IBMSecurityVerify/pack_metadata.json
Labels: docs-approved

#37258 adding workaround for rasterize command
  Packs/rasterize/Integrations/rasterize/rasterize.py
  Packs/rasterize/Integrations/rasterize/rasterize_test.py
  Packs/rasterize/Integrations/rasterize/test_data/chrome_instances.json
  Packs/rasterize/ReleaseNotes/2_0_28.md
  Packs/rasterize/pack_metadata.json
Labels: docs-approved, ForceMerge

#37316 Reco: add identities support
  Packs/Reco/Integrations/Reco/Reco.py
  Packs/Reco/Integrations/Reco/Reco.yml
  Packs/Reco/Integrations/Reco/Reco_test.py
  Packs/Reco/ReleaseNotes/1_5_1.md
  Packs/Reco/pack_metadata.json
Labels: Contribution, docs-approved, Partner, Contribution Form Filled, Partner Support Level, External PR, Partner-Approved

#37276 Trend micro vision one
  Packs/TrendMicroVisionOne/.secrets-ignore
  Packs/TrendMicroVisionOne/Integrations/TrendMicroVisionOneV3/README.md
  Packs/TrendMicroVisionOne/Integrations/TrendMicroVisionOneV3/TrendMicroVisionOneV3.py
  Packs/TrendMicroVisionOne/Integrations/TrendMicroVisionOneV3/TrendMicroVisionOneV3.yml
  Packs/TrendMicroVisionOne/Integrations/TrendMicroVisionOneV3/TrendMicroVisionOneV3_test.py
  Packs/TrendMicroVisionOne/Integrations/TrendMicroVisionOneV3/test_data/get_alert_details.json
  Packs/TrendMicroVisionOne/ReleaseNotes/4_1_4.md
  Packs/TrendMicroVisionOne/pack_metadata.json
Labels: Contribution, docs-approved, Partner, Contribution Form Filled, Partner Support Level, External PR, Partner-Approved

#37280 Update integration listing content and metadata
  Packs/CyberArkEPM/Integrations/CyberArkEPMEventCollector/CyberArkEPMEventCollector_image.png
  Packs/CyberArkEPM/README.md
  Packs/CyberArkEPM/ReleaseNotes/1_0_6.md
  Packs/CyberArkEPM/pack_metadata.json
Labels: Contribution, docs-approved, Partner, Contribution Form Filled, Xsoar Support Level, External PR, Partner-Approved

#37257 [Microsoft Teams] - Update
  Packs/MicrosoftTeams/Integrations/MicrosoftTeams/MicrosoftTeams.py
  Packs/MicrosoftTeams/Integrations/MicrosoftTeams/README.md
  Packs/MicrosoftTeams/ReleaseNotes/1_5_5.md
  Packs/MicrosoftTeams/pack_metadata.json
Labels: docs-approved

#37285 demisto/python3:3.11.10.116439, demisto/boto3py3:1.0.0.116921, demist…
  Packs/AWS-SecurityHub/Integrations/AWS_SecurityHub/AWS_SecurityHub.py
  Packs/AWS-SecurityHub/Integrations/AWS_SecurityHub/AWS_SecurityHub.yml
  Packs/AWS-SecurityHub/ReleaseNotes/1_3_38.md
  Packs/AWS-SecurityHub/pack_metadata.json
  Packs/Akamai_SIEM/Integrations/Akamai_SIEM/Akamai_SIEM.yml
  Packs/Akamai_SIEM/ReleaseNotes/1_1_8.md
  Packs/Akamai_SIEM/pack_metadata.json
  Packs/Box/Integrations/BoxV2/BoxV2.py
  Packs/Box/Integrations/BoxV2/BoxV2.yml
  Packs/Box/ReleaseNotes/3_2_5.md
  Packs/Box/pack_metadata.json
  Packs/CrowdStrikeIntel/Integrations/CrowdStrikeFalconIntel_v2/CrowdStrikeFalconIntel_v2.py
  Packs/CrowdStrikeIntel/Integrations/CrowdStrikeFalconIntel_v2/CrowdStrikeFalconIntel_v2.yml
  Packs/CrowdStrikeIntel/ReleaseNotes/2_0_38.md
  Packs/CrowdStrikeIntel/pack_metadata.json
  Packs/Cyberpion/Integrations/Cyberpion/Cyberpion.py
  Packs/Cyberpion/Integrations/Cyberpion/Cyberpion.yml
  Packs/Cyberpion/ReleaseNotes/1_1_10.md
  Packs/Cyberpion/pack_metadata.json
  Packs/Darktrace/Integrations/DarktraceEventCollector/DarktraceEventCollector.py
  Packs/Darktrace/Integrations/DarktraceEventCollector/DarktraceEventCollector.yml
  Packs/Darktrace/ReleaseNotes/3_0_12.md
  Packs/Darktrace/pack_metadata.json
  Packs/FraudWatch/Integrations/FraudWatch/FraudWatch.yml
  Packs/FraudWatch/Integrations/FraudWatch/FraudWatch_test.py
  Packs/FraudWatch/ReleaseNotes/1_0_13.md
  Packs/FraudWatch/pack_metadata.json
  Packs/Infinipoint/Integrations/Infinipoint/Infinipoint.py
  Packs/Infinipoint/Integrations/Infinipoint/Infinipoint.yml
  Packs/Infinipoint/ReleaseNotes/1_0_15.md
  Packs/Infinipoint/pack_metadata.json
  Packs/PaloAltoNetworks_IoT/Integrations/PaloAltoNetworks_IoT/PaloAltoNetworks_IoT.py
  Packs/PaloAltoNetworks_IoT/Integrations/PaloAltoNetworks_IoT/PaloAltoNetworks_IoT.yml
  Packs/PaloAltoNetworks_IoT/ReleaseNotes/1_0_37.md
  Packs/PaloAltoNetworks_IoT/pack_metadata.json
  Packs/SecurityIntelligenceServicesFeed/Integrations/SecurityIntelligenceServicesFeed/SecurityIntelligenceServicesFeed.py
  Packs/SecurityIntelligenceServicesFeed/Integrations/SecurityIntelligenceServicesFeed/SecurityIntelligenceServicesFeed.yml
  Packs/SecurityIntelligenceServicesFeed/ReleaseNotes/1_0_39.md
  Packs/SecurityIntelligenceServicesFeed/pack_metadata.json
  Packs/Zoom/Integrations/ZoomEventCollector/ZoomEventCollector.py
  Packs/Zoom/Integrations/ZoomEventCollector/ZoomEventCollector.yml
  Packs/Zoom/Integrations/ZoomEventCollector/ZoomEventCollector_test.py
  Packs/Zoom/ReleaseNotes/1_6_17.md
  Packs/Zoom/pack_metadata.json
  Tests/docker_native_image_config.json
Labels: docs-approved, auto-update-docker

#36736 Fix Core release notes
  Packs/Core/ReleaseNotes/3_0_78.md
Labels: docs-approved, bypass.url

#37321 Ciac 12223/carbonblack endpoint standart v3/fix none type access
  Packs/CarbonBlackDefense/Integrations/CarbonBlackEndpointStandardV3/CarbonBlackEndpointStandardV3.py
  Packs/CarbonBlackDefense/ReleaseNotes/4_0_5.md
  Packs/CarbonBlackDefense/pack_metadata.json
Labels: docs-approved

#37329 Add a check for Security Approved for contributions
  .github/workflows/security-label-check.yml
Labels: docs-approved, Security Approved

#37082 Suspicious process execution by scheduled task on a sensitive server
  Packs/Core/Playbooks/playbook-Suspicious_process_execution_by_scheduled_task_on_a_sensitive_server.yml
  Packs/Core/Playbooks/playbook-Suspicious_process_execution_by_scheduled_task_on_a_sensitive_server_README.md
  Packs/Core/ReleaseNotes/3_0_96.md
  Packs/Core/Triggers/Trigger_-_Suspicious_process_execution_by_scheduled_task_on_a_sensitive_server.json
  Packs/Core/doc_files/Suspicious_process_execution_by_scheduled_task_on_a_sensitive_server.png
  Packs/Core/pack_metadata.json
Labels: docs-approved

#37300 changed tldextracl to use file
  Packs/FiltersAndTransformers/ReleaseNotes/1_2_83.md
  Packs/FiltersAndTransformers/Scripts/CheckIfSubdomain/CheckIfSubdomain.py
  Packs/FiltersAndTransformers/Scripts/CheckIfSubdomain/CheckIfSubdomain.yml
  Packs/FiltersAndTransformers/Scripts/CheckIfSubdomain/CheckIfSubdomain_test.py
  Packs/FiltersAndTransformers/Scripts/CheckIfSubdomain/test_data/public_list.dat
  Packs/FiltersAndTransformers/pack_metadata.json
Labels: docs-approved, ForceMerge

#37079 Az 10061 microsoft sentinel
  Packs/AzureSentinel/Classifiers/classifier-Microsoft_Sentinel_-_Incoming_Mapper.json
  Packs/AzureSentinel/Classifiers/classifier-Microsoft_Sentinel_-_Outgoing_Mapper.json
  Packs/AzureSentinel/IncidentFields/incidentfield-Microsoft_Sentinel_Classification_Reason.json
  Packs/AzureSentinel/IncidentFields/incidentfield-Microsoft_Sentinel_Owner.json
  Packs/AzureSentinel/Integrations/AzureSentinel/AzureSentinel.py
  Packs/AzureSentinel/Integrations/AzureSentinel/AzureSentinel_test.py
  Packs/AzureSentinel/Layouts/layoutscontainer-Microsoft_Sentinel.json
  Packs/AzureSentinel/ReleaseNotes/1_5_52.md
  Packs/AzureSentinel/Scripts/MicrosoftSentinelConvertCommentsToTable/MicrosoftSentinelConvertCommentsToTable.py
  Packs/AzureSentinel/Scripts/MicrosoftSentinelConvertCommentsToTable/MicrosoftSentinelConvertCommentsToTable.yml
  Packs/AzureSentinel/Scripts/MicrosoftSentinelConvertCommentsToTable/MicrosoftSentinelConvertCommentsToTable_test.py
  Packs/AzureSentinel/Scripts/MicrosoftSentinelSetOwner/MicrosoftSentinelSetOwner.py
  Packs/AzureSentinel/Scripts/MicrosoftSentinelSetOwner/MicrosoftSentinelSetOwner.yml
  Packs/AzureSentinel/Scripts/MicrosoftSentinelSetOwner/MicrosoftSentinelSetOwner_test.py
  Packs/AzureSentinel/Scripts/MicrosoftSentinelSetOwner/README.md
  Packs/AzureSentinel/Scripts/MicrosoftSentinelSubmitNewComment/MicrosoftSentinelSubmitNewComment.py
  Packs/AzureSentinel/Scripts/MicrosoftSentinelSubmitNewComment/MicrosoftSentinelSubmitNewComment.yml
  Packs/AzureSentinel/Scripts/MicrosoftSentinelSubmitNewComment/MicrosoftSentinelSubmitNewComment_test.py
  Packs/AzureSentinel/Scripts/MicrosoftSentinelSubmitNewComment/README.md
  Packs/AzureSentinel/pack_metadata.json
Labels: docs-approved, post-demo

#37373 [download_packs_and_docker_images.py] Add Handling for Packs with no ContentItems
  Utils/download_packs_and_docker_images.py
  contribution/utils/download_packs_and_docker_images.py
Labels: docs-approved

#37408 [ReadPDFFileV2] Fix issue where the script failed to handle binary data
  Packs/CommonScripts/ReleaseNotes/1_15_92.md
  Packs/CommonScripts/Scripts/ReadPDFFileV2/ReadPDFFileV2.py
  Packs/CommonScripts/Scripts/ReadPDFFileV2/ReadPDFFileV2_test.py
  Packs/CommonScripts/pack_metadata.json
Labels: docs-approved

#37391 365 hunting playbook url fix
  Packs/Microsoft365Defender/Playbooks/playbook-Microsoft_365_Defender_-_Emails_Indicators_Hunt.yml
  Packs/Microsoft365Defender/Playbooks/playbook-Microsoft_365_Defender_-_Get_Email_URL_Clicks.yml
  Packs/Microsoft365Defender/ReleaseNotes/4_5_37.md
  Packs/Microsoft365Defender/pack_metadata.json
Labels: docs-approved

#37347 Endpoint initiated uncommon remote scheduled task creation
  Packs/Core/Playbooks/playbook-Endpoint_initiated_uncommon_remote_scheduled_task_creation.yml
  Packs/Core/Playbooks/playbook-Endpoint_initiated_uncommon_remote_scheduled_task_creation_README.md
  Packs/Core/ReleaseNotes/3_0_98.md
  Packs/Core/Triggers/Trigger_-_Endpoint_initiated_uncommon_remote_scheduled_task_creation.json
  Packs/Core/doc_files/Endpoint_initiated_uncommon_remote_scheduled_task_creation.png
  Packs/Core/pack_metadata.json
Labels: docs-approved

#37409 Ews powershell bug
  Packs/MicrosoftExchangeOnline/Integrations/EwsExtensionEXOPowershellV3/EwsExtensionEXOPowershellV3.ps1
  Packs/MicrosoftExchangeOnline/ReleaseNotes/1_5_17.md
  Packs/MicrosoftExchangeOnline/pack_metadata.json
Labels: docs-approved

#37188 Update QualysFIM events and incidents API endpoints to V2 and V3
  Packs/QualysFIM/Integrations/QualysFIM/QualysFIM.py
  Packs/QualysFIM/Integrations/QualysFIM/QualysFIM.yml
  Packs/QualysFIM/Integrations/QualysFIM/QualysFIM_test.py
  Packs/QualysFIM/ReleaseNotes/1_1_0.md
  Packs/QualysFIM/pack_metadata.json
Labels: docs-approved, python
