Repository demisto/content, pull requests merged in 2024-03, with the labels that each got.

#32302 Added XSOAR linter to pre-commit
  .pre-commit-config_template.yaml
  Packs/Base/ReleaseNotes/1_33_36.md
  Packs/Base/Scripts/CommonServerPython/CommonServerPython.py
  Packs/Base/pack_metadata.json
Labels: docs-approved

#33136 [MicrosoftGraphMail] update docs send-mail command
  Packs/MicrosoftGraphMail/Integrations/MicrosoftGraphMail/README.md
Labels: docs-approved

#33062 Added Compatibility with new Allowed Indicator Module in CTIX 3.6
  Packs/CTIX/Integrations/CTIX/CTIX.py
  Packs/CTIX/Integrations/CTIX/CTIX.yml
  Packs/CTIX/Integrations/CTIX/CTIX_test.py
  Packs/CTIX/Integrations/CTIXv3/CTIXv3.py
  Packs/CTIX/Integrations/CTIXv3/CTIXv3.yml
  Packs/CTIX/Integrations/CTIXv3/CTIXv3_test.py
  Packs/CTIX/ReleaseNotes/2_2_16.md
  Packs/CTIX/pack_metadata.json
Labels: Contribution, ready-for-instance-test, Contribution Form Filled, Community, Partner Support Level, External PR, Partner-Approved, TIM Review

#33028 move GetIncidentsByQuery to api module
  Packs/ApiModules/Scripts/GetIncidentsApiModule/GetIncidentsApiModule.py
  Packs/ApiModules/Scripts/GetIncidentsApiModule/GetIncidentsApiModule.yml
  Packs/ApiModules/Scripts/GetIncidentsApiModule/GetIncidentsApiModule_test.py
  Packs/Base/ReleaseNotes/1_33_37.md
  Packs/Base/Scripts/DBotFindSimilarIncidents/DBotFindSimilarIncidents.py
  Packs/Base/Scripts/DBotFindSimilarIncidents/DBotFindSimilarIncidents.yml
  Packs/Base/Scripts/DBotFindSimilarIncidents/DBotFindSimilarIncidents_test.py
  Packs/Base/Scripts/DBotFindSimilarIncidentsByIndicators/DBotFindSimilarIncidentsByIndicators.py
  Packs/Base/Scripts/DBotFindSimilarIncidentsByIndicators/DBotFindSimilarIncidentsByIndicators.yml
  Packs/Base/Scripts/DBotFindSimilarIncidentsByIndicators/DBotFindSimilarIncidentsByIndicators_test.py
  Packs/Base/Scripts/GetIncidentsByQuery/GetIncidentsByQuery.py
  Packs/Base/Scripts/GetIncidentsByQuery/GetIncidentsByQuery.yml
  Packs/Base/Scripts/GetIncidentsByQuery/GetIncidentsByQuery_test.py
  Packs/Base/Scripts/GetIncidentsByQuery/README.md
  Packs/Base/pack_metadata.json
Labels: docs-approved

#32950 Stix creator bug
  Packs/CommonScripts/ReleaseNotes/1_14_4.md
  Packs/CommonScripts/Scripts/StixCreator/StixCreator.py
  Packs/CommonScripts/Scripts/StixCreator/StixCreator.yml
  Packs/CommonScripts/pack_metadata.json
Labels: docs-approved

#33125 Fix formatting in Readme files
  Packs/Okta/Integrations/Okta_IAM/README.md
  Packs/Okta/Integrations/Okta_v2/README.md
Labels: docs-approved

#33167 Phishing URL Docker Image Update
  Packs/PhishingURL/ReleaseNotes/1_1_11.md
  Packs/PhishingURL/Scripts/DBotPredictURLPhishing/DBotPredictURLPhishing.yml
  Packs/PhishingURL/pack_metadata.json
Labels: docs-approved

#33085 [ASM] EXPANDR-8305: SO Bug fix
  Packs/CortexAttackSurfaceManagement/Playbooks/Cortex_ASM_-_Service_Ownership.yml
  Packs/CortexAttackSurfaceManagement/ReleaseNotes/1_7_30.md
  Packs/CortexAttackSurfaceManagement/doc_files/Cortex_ASM_-_Service_Ownership.png
  Packs/CortexAttackSurfaceManagement/pack_metadata.json
Labels: Contribution, ready-for-instance-test, Contribution Form Filled, Community, Xsoar Support Level, External PR, Security Review

#33114 [Whois] DomainTools Iris Update
  Packs/Whois/pack_metadata.json
Labels: Contribution, Partner, ready-for-instance-test, Contribution Form Filled, Xsoar Support Level, External PR, Partner-Approved

#32878 Schedule Command Sanitize
  Packs/CommonScripts/ReleaseNotes/1_14_5.md
  Packs/CommonScripts/Scripts/ScheduleGenericPolling/ScheduleGenericPolling.py
  Packs/CommonScripts/Scripts/ScheduleGenericPolling/ScheduleGenericPolling.yml
  Packs/CommonScripts/Scripts/ScheduleGenericPolling/ScheduleGenericPolling_test.py
  Packs/CommonScripts/pack_metadata.json
Labels: docs-approved

#32470 Identity analytics playbook xsoar
  Packs/CommonTypes/.pack-ignore
  Packs/CommonTypes/IncidentFields/incidentfield-Alert_tags.json
  Packs/CommonTypes/IncidentFields/incidentfield-User_Risk_Level.json
  Packs/CommonTypes/ReleaseNotes/3_4_3.md
  Packs/CommonTypes/pack_metadata.json
  Packs/Core/Layouts/layoutscontainer-Identity_Analytics_Alerts.json
  Packs/Core/Playbooks/playbook-Identity_Analytics_-_Alert_Handling.yml
  Packs/Core/ReleaseNotes/3_0_21.md
  Packs/Core/pack_metadata.json
  Packs/CoreAlertFields/IncidentFields/incidentfield-User_Risk_level.json
  Packs/CoreAlertFields/ReleaseNotes/1_0_33.md
  Packs/CoreAlertFields/pack_metadata.json
  Packs/CortexXDR/Classifiers/classifier-mapper-incoming-PaloAltoNetworks_CortexXDR.json
  Packs/CortexXDR/Layouts/layoutscontainer-Cortex_XDR_Incident.json
  Packs/CortexXDR/Playbooks/Cortex_XDR_Alerts_Handling_v2.yml
  Packs/CortexXDR/Playbooks/Cortex_XDR_Alerts_Handling_v2_README.md
  Packs/CortexXDR/Playbooks/playbook-Cortex_XDR_-_First_SSO_Access.yml
  Packs/CortexXDR/Playbooks/playbook-Cortex_XDR_-_First_SSO_Access_-_Set_Verdict.yml
  Packs/CortexXDR/Playbooks/playbook-Cortex_XDR_-_First_SSO_Access_-_Set_Verdict_README.md
  Packs/CortexXDR/Playbooks/playbook-Cortex_XDR_-_First_SSO_Access_README.md
  Packs/CortexXDR/Playbooks/playbook-Cortex_XDR_-_Identity_Analytics.yml
  Packs/CortexXDR/Playbooks/playbook-Cortex_XDR_-_Identity_Analytics_README.md
  Packs/CortexXDR/ReleaseNotes/6_1_18.md
  Packs/CortexXDR/doc_files/Cortex_XDR_-_Identity_Analytics.png
  Packs/CortexXDR/doc_files/Cortex_XDR_Alerts_Handling_v2.png
  Packs/CortexXDR/pack_metadata.json
Labels: docs-approved

#33020 Update `demisto/python3` 50-100 coverage rate
  Packs/ExpanseV2/ReleaseNotes/1_10_50.md
  Packs/ExpanseV2/Scripts/ExpanseEnrichAttribution/ExpanseEnrichAttribution.yml
  Packs/ExpanseV2/Scripts/ExpanseRefreshIssueAssets/ExpanseRefreshIssueAssets.yml
  Packs/ExpanseV2/pack_metadata.json
  Packs/IntegrationsAndIncidentsHealthCheck/ReleaseNotes/1_3_20.md
  Packs/IntegrationsAndIncidentsHealthCheck/Scripts/IncidentsCheck_Widget_CommandsNames/IncidentsCheck_Widget_CommandsNames.yml
  Packs/IntegrationsAndIncidentsHealthCheck/Scripts/IncidentsCheck_Widget_NumberofErrors/IncidentsCheck_Widget_NumberofErrors.yml
  Packs/IntegrationsAndIncidentsHealthCheck/pack_metadata.json
  Packs/Phishing/ReleaseNotes/3_6_9.md
  Packs/Phishing/Scripts/DeleteReportedEmail/DeleteReportedEmail.yml
  Packs/Phishing/pack_metadata.json
  Packs/PrismaCloudCompute/ReleaseNotes/1_6_2.md
  Packs/PrismaCloudCompute/Scripts/PrismaCloudComputeParseAuditAlert/PrismaCloudComputeParseAuditAlert.yml
  Packs/PrismaCloudCompute/pack_metadata.json
  Packs/ShiftManagement/ReleaseNotes/1_3_10.md
  Packs/ShiftManagement/Scripts/TimeToNextShift/TimeToNextShift.yml
  Packs/ShiftManagement/pack_metadata.json
  Packs/SplunkPy/ReleaseNotes/3_1_21.md
  Packs/SplunkPy/Scripts/SplunkShowDrilldown/SplunkShowDrilldown.yml
  Packs/SplunkPy/pack_metadata.json
Labels: docs-approved, ForceMerge

#33202 Uploadfile with using argument
  Packs/DemistoRESTAPI/ReleaseNotes/1_3_51.md
  Packs/DemistoRESTAPI/Scripts/UploadFile/UploadFile.py
  Packs/DemistoRESTAPI/Scripts/UploadFile/UploadFile.yml
  Packs/DemistoRESTAPI/Scripts/UploadFile/UploadFile_test.py
  Packs/DemistoRESTAPI/pack_metadata.json
Labels: docs-approved

#33170 bump candidate
  Tests/docker_native_image_config.json
Labels: docs-approved

#33058 [ServiceNow v2] Fixed issue in fetch incidents
  Packs/ServiceNow/Integrations/ServiceNowv2/ServiceNowv2.py
  Packs/ServiceNow/Integrations/ServiceNowv2/ServiceNowv2.yml
  Packs/ServiceNow/Integrations/ServiceNowv2/ServiceNowv2_test.py
  Packs/ServiceNow/Integrations/ServiceNowv2/test_data/response_constants.py
  Packs/ServiceNow/ReleaseNotes/2_5_56.md
  Packs/ServiceNow/pack_metadata.json
Labels: docs-approved

#33141 [ConvertFile] Bump Docker version
  Packs/CommonScripts/ReleaseNotes/1_14_6.md
  Packs/CommonScripts/Scripts/ConvertFile/ConvertFile.py
  Packs/CommonScripts/Scripts/ConvertFile/ConvertFile.yml
  Packs/CommonScripts/Scripts/ConvertFile/ConvertFile_test.py
  Packs/CommonScripts/pack_metadata.json
Labels: ForceMerge

#33154 Fix/[XSUP-33795]/Logo does not shown in data collection form
  Packs/Gmail/Integrations/Gmail/Gmail.py
  Packs/Gmail/Integrations/Gmail/Gmail.yml
  Packs/Gmail/Integrations/Gmail/Gmail_test.py
  Packs/Gmail/ReleaseNotes/1_3_17.md
  Packs/Gmail/pack_metadata.json
  Packs/GmailSingleUser/Integrations/GmailSingleUser/GmailSingleUser.py
  Packs/GmailSingleUser/Integrations/GmailSingleUser/GmailSingleUser.yml
  Packs/GmailSingleUser/Integrations/GmailSingleUser/GmailSingleUser_test.py
  Packs/GmailSingleUser/ReleaseNotes/1_3_13.md
  Packs/GmailSingleUser/pack_metadata.json
Labels: docs-approved

#32997 Rasterize Latest Poppler
  Packs/rasterize/Integrations/rasterize/rasterize.yml
  Packs/rasterize/Integrations/rasterize/rasterize_test.py
  Packs/rasterize/ReleaseNotes/2_0_1.md
  Packs/rasterize/pack_metadata.json
Labels: docs-approved, ForceMerge

#33164 Teams generate url command bug
  Packs/MicrosoftTeams/Integrations/MicrosoftTeams/MicrosoftTeams.py
  Packs/MicrosoftTeams/Integrations/MicrosoftTeams/MicrosoftTeams.yml
  Packs/MicrosoftTeams/Integrations/MicrosoftTeams/MicrosoftTeams_test.py
  Packs/MicrosoftTeams/Integrations/MicrosoftTeams/README.md
  Packs/MicrosoftTeams/ReleaseNotes/1_4_54.json
  Packs/MicrosoftTeams/ReleaseNotes/1_4_54.md
  Packs/MicrosoftTeams/pack_metadata.json
Labels: docs-approved

#33211 Update README.md
  Packs/CommonScripts/Scripts/ScheduleCommand/README.md
Labels: docs-approved

#33204 download and move images to content repo
  Packs/GoogleVertexAI/Integrations/GoogleVertexAI/README.md
  Packs/GoogleVertexAI/ReleaseNotes/1_0_1.md
  Packs/GoogleVertexAI/doc_files/AppScope.png
  Packs/GoogleVertexAI/doc_files/CreateProject.png
  Packs/GoogleVertexAI/doc_files/allow.png
  Packs/GoogleVertexAI/doc_files/appInfo.png
  Packs/GoogleVertexAI/doc_files/authCode.png
  Packs/GoogleVertexAI/doc_files/authorizationURL.png
  Packs/GoogleVertexAI/doc_files/commandOutput.png
  Packs/GoogleVertexAI/doc_files/consentScreen.png
  Packs/GoogleVertexAI/doc_files/createCredential.png
  Packs/GoogleVertexAI/doc_files/credential.png
  Packs/GoogleVertexAI/doc_files/credentialInfo.png
  Packs/GoogleVertexAI/doc_files/enableVertexAIAPI.png
  Packs/GoogleVertexAI/doc_files/finalAppLook.png
  Packs/GoogleVertexAI/doc_files/image20.png
  Packs/GoogleVertexAI/doc_files/instanceInfo.png
  Packs/GoogleVertexAI/doc_files/instancePreview.png
  Packs/GoogleVertexAI/doc_files/marketplacesearch.png
  Packs/GoogleVertexAI/doc_files/projName1.png
  Packs/GoogleVertexAI/doc_files/projectID.png
  Packs/GoogleVertexAI/doc_files/readOnlyScope.png
  Packs/GoogleVertexAI/doc_files/resetIntegrationCache.png
  Packs/GoogleVertexAI/doc_files/userType.png
  Packs/GoogleVertexAI/doc_files/vertexAPIMarketplace.png
  Packs/GoogleVertexAI/pack_metadata.json
Labels: docs-approved

#33206 Mark Prisma Cloud v2 `hybrid`
  Packs/PrismaCloud/Integrations/PrismaCloudV2/PrismaCloudV2.yml
  Packs/PrismaCloud/ReleaseNotes/4_3_0.md
  Packs/PrismaCloud/pack_metadata.json
Labels: docs-approved

#33207 Fix create_sdk_pr.py
  Tests/sdk_release/create_sdk_pr.py
Labels: docs-approved

#33116 Add alert attachments
  Packs/ZeroFox/Integrations/ZeroFox/README.md
  Packs/ZeroFox/Integrations/ZeroFox/ZeroFox.py
  Packs/ZeroFox/Integrations/ZeroFox/ZeroFox.yml
  Packs/ZeroFox/Integrations/ZeroFox/ZeroFox_test.py
  Packs/ZeroFox/Integrations/ZeroFox/test_data/alerts/attachments.json
  Packs/ZeroFox/ReleaseNotes/1_3_0.md
  Packs/ZeroFox/pack_metadata.json
Labels: Contribution, Partner, ready-for-instance-test, Contribution Form Filled, Partner Support Level, External PR, Partner-Approved, TIM Review

#32790 [CIAC-6775] [PAN-OS] Add audit-comment argument
  Packs/PAN-OS/Integrations/Panorama/Panorama.py
  Packs/PAN-OS/Integrations/Panorama/Panorama.yml
  Packs/PAN-OS/Integrations/Panorama/Panorama_test.py
  Packs/PAN-OS/Integrations/Panorama/README.md
  Packs/PAN-OS/ReleaseNotes/2_1_23.md
  Packs/PAN-OS/pack_metadata.json
Labels: docs-approved

#33124 Support mmm-dd-yyyy time format in SNOW
  Packs/ServiceNow/.pack-ignore
  Packs/ServiceNow/Integrations/ServiceNowv2/ServiceNowv2.py
  Packs/ServiceNow/Integrations/ServiceNowv2/ServiceNowv2.yml
  Packs/ServiceNow/Integrations/ServiceNowv2/ServiceNowv2_test.py
  Packs/ServiceNow/ReleaseNotes/2_5_57.md
  Packs/ServiceNow/pack_metadata.json
Labels: docs-approved

#33217 Generic SQL fix
  Packs/GenericSQL/Integrations/GenericSQL/GenericSQL.py
  Packs/GenericSQL/Integrations/GenericSQL/GenericSQL.yml
  Packs/GenericSQL/Integrations/GenericSQL/GenericSQL_test.py
  Packs/GenericSQL/ReleaseNotes/1_2_1.md
  Packs/GenericSQL/pack_metadata.json
Labels: docs-approved

#32039 [Event Collector] - GitGuaridan
  Packs/GitGuardian/.pack-ignore
  Packs/GitGuardian/.secrets-ignore
  Packs/GitGuardian/Integrations/GitGuardianEventCollector/GitGuardianEventCollector.py
  Packs/GitGuardian/Integrations/GitGuardianEventCollector/GitGuardianEventCollector.yml
  Packs/GitGuardian/Integrations/GitGuardianEventCollector/GitGuardianEventCollector_description.md
  Packs/GitGuardian/Integrations/GitGuardianEventCollector/GitGuardianEventCollector_image.png
  Packs/GitGuardian/Integrations/GitGuardianEventCollector/GitGuardianEventCollector_test.py
  Packs/GitGuardian/Integrations/GitGuardianEventCollector/README.md
  Packs/GitGuardian/Integrations/GitGuardianEventCollector/command_examples
  Packs/GitGuardian/Integrations/GitGuardianEventCollector/test_data/audit_log_response.json
  Packs/GitGuardian/Integrations/GitGuardianEventCollector/test_data/audit_log_response_next_link.json
  Packs/GitGuardian/Integrations/GitGuardianEventCollector/test_data/incident_response.json
  Packs/GitGuardian/ModelingRules/GitGuardian/GitGuardian.xif
  Packs/GitGuardian/ModelingRules/GitGuardian/GitGuardian.yml
  Packs/GitGuardian/ModelingRules/GitGuardian/GitGuardian_schema.json
  Packs/GitGuardian/README.md
  Packs/GitGuardian/pack_metadata.json
Labels: docs-approved

#33130 Bump github action dependencies in contributions github actions
  .github/workflows/create-internal-pr-from-external.yml
  .github/workflows/handle-new-external-pr.yml
Labels: docs-approved

#32417 EclecticIQ v3 integration
  Packs/EclecticIQ/.secrets-ignore
  Packs/EclecticIQ/Author_image.png
  Packs/EclecticIQ/IndicatorFields/indicatorfield-EclecticIQ_Entity_Description.json
  Packs/EclecticIQ/IndicatorFields/indicatorfield-EclecticIQ_Entity_ID.json
  Packs/EclecticIQ/IndicatorFields/indicatorfield-EclecticIQ_Entity_Title.json
  Packs/EclecticIQ/IndicatorFields/indicatorfield-EclecticIQ_Entity_Type.json
  Packs/EclecticIQ/IndicatorFields/indicatorfield-EclecticIQ_Feed_ID.json
  Packs/EclecticIQ/IndicatorFields/indicatorfield-EclecticIQ_Source.json
  Packs/EclecticIQ/Integrations/EclecticIQIntelligenceCenterv3/EclecticIQIntelligenceCenterv3.py
  Packs/EclecticIQ/Integrations/EclecticIQIntelligenceCenterv3/EclecticIQIntelligenceCenterv3.yml
  Packs/EclecticIQ/Integrations/EclecticIQIntelligenceCenterv3/EclecticIQIntelligenceCenterv3_image.png
  Packs/EclecticIQ/Integrations/EclecticIQIntelligenceCenterv3/EclecticIQIntelligenceCenterv3_test.py
  Packs/EclecticIQ/Integrations/EclecticIQIntelligenceCenterv3/README.md
  Packs/EclecticIQ/Integrations/EclecticIQIntelligenceCenterv3/command_examples.txt
  Packs/EclecticIQ/Integrations/EclecticIQv2/EclecticIQv2.yml
  Packs/EclecticIQ/ReleaseNotes/3_0_0.md
  Packs/EclecticIQ/pack_metadata.json
Labels: Contribution, Partner, ready-for-instance-test, pending-demo, Contribution Form Filled, Partner Support Level, External PR, Security Review, Partner-Approved, TIM Review

#33212 Splunkpy cache incidents by window error
  Packs/SplunkPy/Integrations/SplunkPy/SplunkPy.py
  Packs/SplunkPy/Integrations/SplunkPy/SplunkPy.yml
  Packs/SplunkPy/Integrations/SplunkPy/SplunkPy_test.py
  Packs/SplunkPy/ReleaseNotes/3_1_22.md
  Packs/SplunkPy/pack_metadata.json
Labels: docs-approved

#33229 SplunkPy: fix supported version in readme
  Packs/SplunkPy/Integrations/SplunkPy/README.md
Labels: docs-approved

#33230 CoreRESTAPI: fix command message
  Packs/DemistoRESTAPI/Integrations/CoreRESTAPI/CoreRESTAPI.js
  Packs/DemistoRESTAPI/ReleaseNotes/1_3_52.md
  Packs/DemistoRESTAPI/pack_metadata.json
Labels: docs-approved

#33219 Fix sumologic field
  Packs/SumoLogic_Cloud_SIEM/IncidentFields/incidentfield-Sumo_Logic_Cloud_SIEM_Insight_Signals.json
  Packs/SumoLogic_Cloud_SIEM/ReleaseNotes/1_1_22.md
  Packs/SumoLogic_Cloud_SIEM/pack_metadata.json
Labels: docs-approved

#33148 When more than 1 reviewer has the lowest number of assigned PRs, choose randomly
  Utils/github_workflow_scripts/github_workflow_scripts_tests/handle_external_pr_test.py
  Utils/github_workflow_scripts/handle_external_pr.py
Labels: docs-approved

#32980 changed integration name and pack name as for customer request
  Packs/AWS-SecurityLake/Integrations/AWSSecurityLake/AWSSecurityLake.yml
  Packs/AWS-SecurityLake/Integrations/AWSSecurityLake/README.md
  Packs/AWS-SecurityLake/README.md
  Packs/AWS-SecurityLake/ReleaseNotes/1_0_6.md
  Packs/AWS-SecurityLake/pack_metadata.json
Labels: docs-approved

#33104 SplunkPy add channel_request parameter for submitting hec events
  Packs/SplunkPy/Integrations/SplunkPy/README.md
  Packs/SplunkPy/Integrations/SplunkPy/SplunkPy.py
  Packs/SplunkPy/Integrations/SplunkPy/SplunkPy.yml
  Packs/SplunkPy/Integrations/SplunkPy/SplunkPy_test.py
  Packs/SplunkPy/ReleaseNotes/3_1_23.md
  Packs/SplunkPy/pack_metadata.json
Labels: docs-approved

#32563 Trend micro vision one
  Packs/TrendMicroVisionOne/.secrets-ignore
  Packs/TrendMicroVisionOne/Classifiers/classifier-Trend_Micro_Vision_One_V3_XDR_-_Incoming_Mapper.json
  Packs/TrendMicroVisionOne/Integrations/TrendMicroVisionOneV3/README.md
  Packs/TrendMicroVisionOne/Integrations/TrendMicroVisionOneV3/TrendMicroVisionOneV3.py
  Packs/TrendMicroVisionOne/Integrations/TrendMicroVisionOneV3/TrendMicroVisionOneV3.yml
  Packs/TrendMicroVisionOne/Integrations/TrendMicroVisionOneV3/TrendMicroVisionOneV3_test.py
  Packs/TrendMicroVisionOne/Integrations/TrendMicroVisionOneV3/command_examples
  Packs/TrendMicroVisionOne/Integrations/TrendMicroVisionOneV3/test_data/add_custom_script.json
  Packs/TrendMicroVisionOne/Integrations/TrendMicroVisionOneV3/test_data/delete_custom_script.json
  Packs/TrendMicroVisionOne/Integrations/TrendMicroVisionOneV3/test_data/download_custom_script.json
  Packs/TrendMicroVisionOne/Integrations/TrendMicroVisionOneV3/test_data/download_information_collected_file.json
  Packs/TrendMicroVisionOne/Integrations/TrendMicroVisionOneV3/test_data/get_custom_script_list.json
  Packs/TrendMicroVisionOne/Integrations/TrendMicroVisionOneV3/test_data/run_custom_script.json
  Packs/TrendMicroVisionOne/Integrations/TrendMicroVisionOneV3/test_data/update_custom_script.json
  Packs/TrendMicroVisionOne/ReleaseNotes/4_1_0.md
  Packs/TrendMicroVisionOne/pack_metadata.json
Labels: Contribution, docs-approved, Partner, ready-for-instance-test, Contribution Form Filled, pending-contributor, Partner Support Level, External PR, Security Review, Partner-Approved

#33126 Deprecated-EOL
  Packs/CommonPlaybooks/Playbooks/playbook-Block_Email_-_Generic_v2.yml
  Packs/CommonPlaybooks/Playbooks/playbook-Block_Email_-_Generic_v2_README.md
  Packs/CommonPlaybooks/Playbooks/playbook-Block_URL_-_Generic_v2.yml
  Packs/CommonPlaybooks/Playbooks/playbook-Block_URL_-_Generic_v2_README.md
  Packs/CommonPlaybooks/ReleaseNotes/2_6_16.md
  Packs/CommonPlaybooks/doc_files/Block_Email_-_Generic_v2.png
  Packs/CommonPlaybooks/pack_metadata.json
Labels: docs-approved

#33222 Formatter fix
  Packs/CommonScripts/ReleaseNotes/1_14_8.md
  Packs/CommonScripts/Scripts/FormatURL/FormatURL.py
  Packs/CommonScripts/Scripts/FormatURL/FormatURL.yml
  Packs/CommonScripts/Scripts/FormatURL/FormatURL_test.py
  Packs/CommonScripts/pack_metadata.json
Labels: docs-approved

#32681 "xdr-iocs-sync" command enhanced to add a link to the indicator page within XSOAR.
  Packs/CortexXDR/Integrations/XDR_iocs/XDR_iocs.py
  Packs/CortexXDR/Integrations/XDR_iocs/XDR_iocs.yml
  Packs/CortexXDR/Integrations/XDR_iocs/XDR_iocs_test.py
  Packs/CortexXDR/ReleaseNotes/6_1_19.md
  Packs/CortexXDR/pack_metadata.json
Labels: docs-approved

#33227 Remove redundant demisto params in HelloWorld integration
  Packs/HelloWorld/Integrations/HelloWorld/HelloWorld.py
  Packs/HelloWorld/Integrations/HelloWorld/HelloWorld.yml
  Packs/HelloWorld/ReleaseNotes/3_0_8.md
  Packs/HelloWorld/pack_metadata.json
Labels: docs-approved

#33237 fix create graph due to incorrect boolean value
  Packs/X509Certificate/ReleaseNotes/1_0_41.md
  Packs/X509Certificate/pack_metadata.json
Labels: ForceMerge

#32858 Symantec certificate
  Packs/SymantecMSS/Integrations/SymantecMSS/SymantecMSS.py
  Packs/SymantecMSS/Integrations/SymantecMSS/SymantecMSS.yml
  Packs/SymantecMSS/ReleaseNotes/1_0_8.md
  Packs/SymantecMSS/pack_metadata.json
  Tests/known_words.txt
Labels: docs-approved, ForceMerge

#33075 BeyondTrust Password Safe XSIAM Mapping
  Packs/BeyondTrust_Password_Safe/.secrets-ignore
  Packs/BeyondTrust_Password_Safe/ModelingRules/BeyondTrust_Password_Safe/BeyondTrust_Password_Safe.xif
  Packs/BeyondTrust_Password_Safe/ModelingRules/BeyondTrust_Password_Safe/BeyondTrust_Password_Safe.yml
  Packs/BeyondTrust_Password_Safe/ModelingRules/BeyondTrust_Password_Safe/BeyondTrust_Password_Safe_schema.json
  Packs/BeyondTrust_Password_Safe/ParsingRules/BeyondTrust_Password_Safe/BeyondTrust_Password_Safe.xif
  Packs/BeyondTrust_Password_Safe/ParsingRules/BeyondTrust_Password_Safe/BeyondTrust_Password_Safe.yml
  Packs/BeyondTrust_Password_Safe/README.md
  Packs/BeyondTrust_Password_Safe/ReleaseNotes/1_1_6.md
  Packs/BeyondTrust_Password_Safe/pack_metadata.json
Labels: docs-approved

#33140 Ciac 8941/enhancement/cortex xdr flexible close reason mappings mirroring
  Packs/ApiModules/Scripts/CoreIRApiModule/CoreIRApiModule.py
  Packs/ApiModules/Scripts/CoreIRApiModule/CoreIRApiModule_test.py
  Packs/Base/ReleaseNotes/1_33_38.md
  Packs/Base/Scripts/CommonServerPython/CommonServerPython.py
  Packs/Base/pack_metadata.json
  Packs/Core/ReleaseNotes/3_0_22.md
  Packs/Core/pack_metadata.json
  Packs/CortexXDR/Integrations/CortexXDRIR/CortexXDRIR.py
  Packs/CortexXDR/Integrations/CortexXDRIR/CortexXDRIR.yml
  Packs/CortexXDR/Integrations/CortexXDRIR/CortexXDRIR_description.md
  Packs/CortexXDR/Integrations/CortexXDRIR/CortexXDRIR_test.py
  Packs/CortexXDR/Integrations/CortexXDRIR/README.md
  Packs/CortexXDR/Integrations/CortexXDRIR/test_data/resolved_incident_data.json
  Packs/CortexXDR/ReleaseNotes/6_1_20.md
  Packs/CortexXDR/pack_metadata.json
  Packs/ctf01/ReleaseNotes/1_0_10.md
  Packs/ctf01/pack_metadata.json
Labels: docs-approved

#32991 fix a bug in fetch-indicators
  Packs/FeedMISP/Integrations/FeedMISP/FeedMISP.py
  Packs/FeedMISP/Integrations/FeedMISP/FeedMISP.yml
  Packs/FeedMISP/Integrations/FeedMISP/FeedMISP_test.py
  Packs/FeedMISP/ReleaseNotes/1_0_32.md
  Packs/FeedMISP/pack_metadata.json
Labels: docs-approved

#33119 Cohesity event collector
  Packs/CohesityHelios/Integrations/CohesityHeliosEventCollector/CohesityHeliosEventCollector.py
  Packs/CohesityHelios/Integrations/CohesityHeliosEventCollector/CohesityHeliosEventCollector.yml
  Packs/CohesityHelios/Integrations/CohesityHeliosEventCollector/CohesityHeliosEventCollector_description.md
  Packs/CohesityHelios/Integrations/CohesityHeliosEventCollector/CohesityHeliosEventCollector_image.png
  Packs/CohesityHelios/Integrations/CohesityHeliosEventCollector/CohesityHeliosEventCollector_test.py
  Packs/CohesityHelios/Integrations/CohesityHeliosEventCollector/README.md
  Packs/CohesityHelios/Integrations/CohesityHeliosEventCollector/command_examples
  Packs/CohesityHelios/Integrations/CohesityHeliosEventCollector/test_data/CohesityHeliosEventCollector-AlertList.json
  Packs/CohesityHelios/Integrations/CohesityHeliosEventCollector/test_data/CohesityHeliosEventCollector-AuditLogList.json
  Packs/CohesityHelios/ReleaseNotes/1_1_0.md
  Packs/CohesityHelios/pack_metadata.json
Labels: docs-approved

#33242 URL Formatter - Authority part bug fix
  Packs/CommonScripts/ReleaseNotes/1_14_9.md
  Packs/CommonScripts/Scripts/FormatURL/FormatURL.py
  Packs/CommonScripts/Scripts/FormatURL/FormatURL_test.py
  Packs/CommonScripts/pack_metadata.json
Labels: docs-approved

#32982 YR/Handle long running pipelines/CIAC-9386
  Tests/scripts/common.py
  Tests/scripts/gitlab_slack_notifier.py
  Tests/scripts/infrastructure_tests/common_test.py
Labels: docs-approved

#33249 Fix pre-commit for CortexXDRIR
  Packs/CortexXDR/Integrations/CortexXDRIR/CortexXDRIR.py
  Packs/CortexXDR/ReleaseNotes/6_1_21.md
  Packs/CortexXDR/pack_metadata.json
Labels: docs-approved

#33209 GoogleDrive.py: fix get-parents infinite loop
  Packs/GoogleDrive/Integrations/GoogleDrive/GoogleDrive.py
  Packs/GoogleDrive/Integrations/GoogleDrive/GoogleDrive.yml
  Packs/GoogleDrive/ReleaseNotes/1_3_4.md
  Packs/GoogleDrive/pack_metadata.json
Labels: Contribution, ready-for-instance-test, Contribution Form Filled, Community, pending-contributor, Xsoar Support Level, External PR

#31937 Move SophosCentral support from partner to xsoar
  Packs/SophosCentral/.pack-ignore
  Packs/SophosCentral/Integrations/SophosCentral/SophosCentral.py
  Packs/SophosCentral/Integrations/SophosCentral/SophosCentral.yml
  Packs/SophosCentral/Layouts/layoutscontainer-Sophos_Central_Event.json
  Packs/SophosCentral/ReleaseNotes/1_3_0.md
  Packs/SophosCentral/pack_metadata.json
Labels: docs-approved

#33236 bug - gg first fetch timing
  Packs/GitGuardian/Integrations/GitGuardianEventCollector/GitGuardianEventCollector.py
  Packs/GitGuardian/Integrations/GitGuardianEventCollector/GitGuardianEventCollector.yml
  Packs/GitGuardian/ReleaseNotes/1_0_1.md
  Packs/GitGuardian/pack_metadata.json
Labels: docs-approved

#33241 TAXII2 Feed description and parameters update
  Packs/FeedTAXII/Integrations/FeedTAXII2/FeedTAXII2.py
  Packs/FeedTAXII/Integrations/FeedTAXII2/FeedTAXII2.yml
  Packs/FeedTAXII/Integrations/FeedTAXII2/FeedTAXII2_description.md
  Packs/FeedTAXII/ReleaseNotes/1_2_9.md
  Packs/FeedTAXII/pack_metadata.json
Labels: docs-approved

#33260 Fix broken link in mimecast documentation
  Packs/Mimecast/Integrations/MimecastV2/MimecastV2_description.md
  Packs/Mimecast/ReleaseNotes/2_2_5.md
  Packs/Mimecast/pack_metadata.json
Labels: docs-approved, release-notes-only

#33145 O365 SecurityAndComplianceV2 Enhance with Export Action
  Packs/MicrosoftExchangeOnline/Integrations/SecurityAndComplianceV2/README.md
  Packs/MicrosoftExchangeOnline/Integrations/SecurityAndComplianceV2/SecurityAndComplianceV2.ps1
  Packs/MicrosoftExchangeOnline/Integrations/SecurityAndComplianceV2/SecurityAndComplianceV2.yml
  Packs/MicrosoftExchangeOnline/ReleaseNotes/1_2_42.md
  Packs/MicrosoftExchangeOnline/pack_metadata.json
Labels: docs-approved

#33246 IP CIDR Ranges IPv4 IPv6 Mismatches
  Packs/FiltersAndTransformers/ReleaseNotes/1_2_63.md
  Packs/FiltersAndTransformers/Scripts/IsInCidrRanges/IsInCidrRanges.js
  Packs/FiltersAndTransformers/Scripts/IsInCidrRanges/IsInCidrRanges.yml
  Packs/FiltersAndTransformers/Scripts/IsInCidrRanges/README.md
  Packs/FiltersAndTransformers/pack_metadata.json
Labels: docs-approved

#33127 Test-playbook-endpoint-investigation-plan
  Packs/CommonPlaybooks/Playbooks/playbook-Endpoint_Investigation_Plan.yml
  Packs/CommonPlaybooks/ReleaseNotes/2_6_18.md
  Packs/CommonPlaybooks/TestPlaybooks/playbook-Endpoint_Investigation_Plan_-_Test.yml
  Packs/CommonPlaybooks/pack_metadata.json
  Tests/conf.json
Labels: docs-approved

#32960 Get trail status
  Packs/AWS-CloudTrail/Integrations/AWS-CloudTrail/AWS-CloudTrail.py
  Packs/AWS-CloudTrail/Integrations/AWS-CloudTrail/AWS-CloudTrail.yml
  Packs/AWS-CloudTrail/Integrations/AWS-CloudTrail/AWS-CloudTrail_description.md
  Packs/AWS-CloudTrail/Integrations/AWS-CloudTrail/AWS-CloudTrail_test.py
  Packs/AWS-CloudTrail/Integrations/AWS-CloudTrail/README.md
  Packs/AWS-CloudTrail/ReleaseNotes/1_1_0.md
  Packs/AWS-CloudTrail/pack_metadata.json
  package-lock.json
Labels: Contribution, docs-approved, pending-contributor, Xsoar Support Level, External PR

#32832 Change override flow
  .gitlab/ci/.gitlab-ci.global.yml
  .gitlab/ci/.gitlab-ci.on-push.yml
  Tests/Marketplace/Tests/marketplace_services_test.py
  Tests/Marketplace/Tests/override_core_packs_versions_test.py
  Tests/Marketplace/Tests/upload_packs_test.py
  Tests/Marketplace/corepacks_override.json
  Tests/Marketplace/marketplace_constants.py
  Tests/Marketplace/override_core_packs_versions.py
  Tests/Marketplace/upload_packs.py
  Tests/Marketplace/upload_versions_core_files.sh
  Tests/Marketplace/versions-metadata.json
  Tests/scripts/prepare_content_packs_for_testing.sh
Labels: docs-approved, nightly-ok

#32981 Validate Conf.json
  Packs/AHA/TestPlaybooks/AHA_TestPlaybook.yml
  Packs/AWS-CloudTrail/TestPlaybooks/playbook-AWS-CloudTrail_Test_.yml
  Packs/AnsibleAlibabaCloud/TestPlaybooks/Test-AlibabaCloud.yml
  Packs/AnsibleHetznerCloud/TestPlaybooks/Test-AnsibleHCloud.yml
  Packs/CarbonBlackProtect/TestPlaybooks/playbook-CbP-PlayBook.yml
  Packs/CommonScripts/ReleaseNotes/1_14_10.md
  Packs/CommonScripts/Scripts/GridFieldSetup/GridFieldSetup.py
  Packs/CommonScripts/Scripts/GridFieldSetup/GridFieldSetup.yml
  Packs/CommonScripts/pack_metadata.json
  Packs/JoeSecurity/Integrations/JoeSecurityV2/JoeSecurityV2.yml
  Packs/JoeSecurity/ReleaseNotes/1_1_20.md
  Packs/JoeSecurity/TestPlaybooks/testplaybook-_JoeSecuirtyV2.yml
  Packs/JoeSecurity/pack_metadata.json
  Packs/Whois/TestPlaybooks/Sanity_Test_-_Playbbok_with_Unmockable_integration_whois.yml
  Tests/conf.json
Labels: docs-approved

#32989 Devo v2 dev
  Packs/Devo/Integrations/Devo_v2/Devo_v2.py
  Packs/Devo/Integrations/Devo_v2/Devo_v2.yml
  Packs/Devo/Integrations/Devo_v2/Devo_v2_test.py
  Packs/Devo/Integrations/Devo_v2/README.md
  Packs/Devo/ReleaseNotes/1_3_1.md
  Packs/Devo/pack_metadata.json
Labels: Contribution, docs-approved, Partner, ready-for-instance-test, Contribution Form Filled, pending-contributor, Partner Support Level, External PR, Partner-Approved

#33284 Fix conf.json checks failing
  Packs/GSuiteAdmin/Integrations/GSuiteAdmin/GSuiteAdmin.py
  Packs/GSuiteAdmin/Integrations/GSuiteAdmin/GSuiteAdmin.yml
  Packs/GSuiteAdmin/Integrations/GSuiteAdmin/GSuiteAdmin_test.py
  Packs/GSuiteAdmin/ReleaseNotes/1_1_37.md
  Packs/GSuiteAdmin/pack_metadata.json
  Tests/conf.json
Labels: docs-approved

#33110 Spur context api
  Packs/SpurContextAPI/.pack-ignore
  Packs/SpurContextAPI/.secrets-ignore
  Packs/SpurContextAPI/Author_image.png
  Packs/SpurContextAPI/Integrations/SpurContextAPI/README.md
  Packs/SpurContextAPI/Integrations/SpurContextAPI/SpurContextAPI.py
  Packs/SpurContextAPI/Integrations/SpurContextAPI/SpurContextAPI.yml
  Packs/SpurContextAPI/Integrations/SpurContextAPI/SpurContextAPI_description.md
  Packs/SpurContextAPI/Integrations/SpurContextAPI/SpurContextAPI_image.png
  Packs/SpurContextAPI/Integrations/SpurContextAPI/SpurContextAPI_test.py
  Packs/SpurContextAPI/Integrations/SpurContextAPI/command_examples
  Packs/SpurContextAPI/README.md
  Packs/SpurContextAPI/pack_metadata.json
Labels: Contribution, docs-approved, Partner, ready-for-instance-test, Contribution Form Filled, Partner Support Level, External PR, Partner-Approved

#33287 Update CODEOWNERS
  .github/CODEOWNERS
Labels: docs-approved

#33288 Bug fix is internal domain name return false positive
  Packs/CommonScripts/ReleaseNotes/1_14_11.md
  Packs/CommonScripts/Scripts/IsInternalDomainName/IsInternalDomainName.py
  Packs/CommonScripts/Scripts/IsInternalDomainName/IsInternalDomainName.yml
  Packs/CommonScripts/Scripts/IsInternalDomainName/IsInternalDomainName_test.py
  Packs/CommonScripts/pack_metadata.json
Labels: docs-approved

#33291 Fix for the 'Entity Enrichment - Generic v3' playbook
  Packs/CommonPlaybooks/Playbooks/Entity_Enrichment_-_Generic_v3.yml
  Packs/CommonPlaybooks/Playbooks/Entity_Enrichment_-_Generic_v3_README.md
  Packs/CommonPlaybooks/ReleaseNotes/2_6_19.md
  Packs/CommonPlaybooks/pack_metadata.json
Labels: docs-approved

#33243 Prisma SASE playbook name change
  Packs/PrismaAccess/.pack-ignore
  Packs/PrismaAccess/Playbooks/playbook-Prisma_SASE_-_Quarantine_Host_With_Active_Threat.yml
  Packs/PrismaAccess/Playbooks/playbook-Prisma_SASE_-_Quarantine_Host_With_Active_Threat_README.md
  Packs/PrismaAccess/ReleaseNotes/2_1_5.md
  Packs/PrismaAccess/pack_metadata.json
Labels: docs-approved

#33256 Enhancement/ciac 3501/delete context should support comma separated values in key parameter
  Packs/CommonScripts/ReleaseNotes/1_14_12.md
  Packs/CommonScripts/Scripts/DeleteContext/DeleteContext.js
  Packs/CommonScripts/Scripts/DeleteContext/DeleteContext.yml
  Packs/CommonScripts/pack_metadata.json
Labels: docs-approved

#33129 Add primary email address field to the phishing v3 layout
  Packs/CommonPlaybooks/Playbooks/playbook-Email_Address_Enrichment_-_Generic_v2.1.yml
  Packs/CommonPlaybooks/ReleaseNotes/2_6_20.md
  Packs/CommonPlaybooks/doc_files/Email_Address_Enrichment_-_Generic_v2.1.png
  Packs/CommonPlaybooks/pack_metadata.json
  Packs/CommonTypes/IncidentFields/incidentfield-Additional_Email_Addresses.json
  Packs/CommonTypes/ReleaseNotes/3_4_5.md
  Packs/CommonTypes/pack_metadata.json
  Packs/Phishing/Layouts/layoutscontainer-Phishing_v_3.json
  Packs/Phishing/ReleaseNotes/3_6_11.md
  Packs/Phishing/pack_metadata.json
Labels: docs-approved

#33146 Add support auto extract in generic polling playbook
  Packs/CommonPlaybooks/Playbooks/playbook-GenericPolling.yml
  Packs/CommonPlaybooks/Playbooks/playbook-GenericPolling_README.md
  Packs/CommonPlaybooks/ReleaseNotes/2_6_21.md
  Packs/CommonPlaybooks/pack_metadata.json
  Packs/CommonScripts/ReleaseNotes/1_14_13.md
  Packs/CommonScripts/Scripts/GenericPollingScheduledTask/GenericPollingScheduledTask.js
  Packs/CommonScripts/Scripts/GenericPollingScheduledTask/GenericPollingScheduledTask.yml
  Packs/CommonScripts/Scripts/ScheduleGenericPolling/ScheduleGenericPolling.py
  Packs/CommonScripts/Scripts/ScheduleGenericPolling/ScheduleGenericPolling.yml
  Packs/CommonScripts/Scripts/ScheduleGenericPolling/ScheduleGenericPolling_test.py
  Packs/CommonScripts/pack_metadata.json
Labels: docs-approved

#33262 In Handle External PR workflow, ignore CONTRIBUTORS.json files when checking file types
  Utils/github_workflow_scripts/handle_external_pr.py
Labels: docs-approved

#33121 Rename prisma sase
  Packs/PrismaAccess/Integrations/PrismaSASE/PrismaSASE.py
  Packs/PrismaAccess/Integrations/PrismaSASE/PrismaSASE.yml
  Packs/PrismaAccess/Integrations/PrismaSASE/README.md
  Packs/PrismaAccess/ReleaseNotes/2_1_6.md
  Packs/PrismaAccess/TestPlaybooks/playbook-PrismaSASE_Test.yml
  Packs/PrismaAccess/pack_metadata.json
  Tests/conf.json
Labels: docs-approved, ForceMerge

#33234 ActiveDirectoryQuery removes lastname when modifiying OU
  Packs/Active_Directory_Query/Integrations/Active_Directory_Query/Active_Directory_Query.py
  Packs/Active_Directory_Query/Integrations/Active_Directory_Query/Active_Directory_Query.yml
  Packs/Active_Directory_Query/Integrations/Active_Directory_Query/Active_Directory_Query_test.py
  Packs/Active_Directory_Query/ReleaseNotes/1_6_31.md
  Packs/Active_Directory_Query/pack_metadata.json
Labels: docs-approved, ForceMerge

#31914 Validate refactor build migration
  .gitlab/ci/.gitlab-ci.bucket-upload.yml
  .gitlab/ci/.gitlab-ci.global.yml
  .gitlab/ci/.gitlab-ci.on-push.yml
  .gitlab/ci/.gitlab-ci.sdk-nightly.yml
  Tests/scripts/check_jobs_done.py
  Tests/scripts/new_validate.sh
  validation_config.toml
Labels: docs-approved, nightly-ok

#33244 Palo Alto Networks - hunting and detection enhancement
  Packs/PANWComprehensiveInvestigation/Playbooks/Palo_Alto_Networks_-_Hunting_And_Threat_Detection.yml
  Packs/PANWComprehensiveInvestigation/Playbooks/Palo_Alto_Networks_-_Hunting_And_Threat_Detection_README.md
  Packs/PANWComprehensiveInvestigation/README.md
  Packs/PANWComprehensiveInvestigation/ReleaseNotes/1_3_23.md
  Packs/PANWComprehensiveInvestigation/doc_files/Palo_Alto_Networks_-_Hunting_And_Threat_Detection.png
  Packs/PANWComprehensiveInvestigation/pack_metadata.json
Labels: docs-approved

#33313 [XSUP-34670] Remove usage of executeCommand
  Packs/FiltersAndTransformers/ReleaseNotes/1_2_64.md
  Packs/FiltersAndTransformers/Scripts/IsInCidrRanges/IsInCidrRanges.js
  Packs/FiltersAndTransformers/Scripts/IsNotInCidrRanges/IsNotInCidrRanges.js
  Packs/FiltersAndTransformers/TestPlaybooks/playbook-TestIsNotInCidrRanges.yml
  Packs/FiltersAndTransformers/pack_metadata.json
Labels: docs-approved

#33224 Hide sensitive info from logs
  Packs/Base/ReleaseNotes/1_33_39.md
  Packs/Base/Scripts/CommonServerPython/CommonServerPython.py
  Packs/Base/Scripts/CommonServerPython/CommonServerPython_test.py
  Packs/Base/pack_metadata.json
Labels: docs-approved

#33326 Fix Microsoft windows events dashboard
  Packs/MicrosoftWindowsEvents/ReleaseNotes/1_1_7.md
  Packs/MicrosoftWindowsEvents/XSIAMDashboards/MicrosoftWindowsEvents_Dashboard.json
  Packs/MicrosoftWindowsEvents/pack_metadata.json
Labels: docs-approved

#33330 Update the README files with the correct script type
  Packs/CommonScripts/Scripts/IsEmailAddressInternal/README.md
  Packs/CommonScripts/Scripts/SetAndHandleEmpty/README.md
  Packs/FiltersAndTransformers/Scripts/SetIfEmpty/README.md
Labels: docs-approved

#33032 [ArcSight ESM] Resolve JSON Parsing Issues
  Packs/ArcSightESM/Integrations/ArcSightESMv2/ArcSightESMv2.py
  Packs/ArcSightESM/Integrations/ArcSightESMv2/ArcSightESMv2.yml
  Packs/ArcSightESM/Integrations/ArcSightESMv2/ArcSightESMv2_test.py
  Packs/ArcSightESM/Integrations/ArcSightESMv2/test_data/QueryViewerService_getMatrixData_invalid_api_response.txt
  Packs/ArcSightESM/ReleaseNotes/1_2_1.md
  Packs/ArcSightESM/pack_metadata.json
Labels: docs-approved

#32469 bug - Proofpoint Protection Server 503 error
  Packs/ProofpointServerProtection/Integrations/ProofpointProtectionServerV2/ProofpointProtectionServerV2.py
  Packs/ProofpointServerProtection/Integrations/ProofpointProtectionServerV2/ProofpointProtectionServerV2.yml
  Packs/ProofpointServerProtection/Integrations/ProofpointProtectionServerV2/ProofpointProtectionServerV2_test.py
  Packs/ProofpointServerProtection/ReleaseNotes/2_1_7.md
  Packs/ProofpointServerProtection/pack_metadata.json
Labels: docs-approved

#32945 Add CybelAngelEventCollector
  Packs/CybelAngel/.pack-ignore
  Packs/CybelAngel/.secrets-ignore
  Packs/CybelAngel/Integrations/CybelAngelEventCollector/CybelAngelEventCollector.py
  Packs/CybelAngel/Integrations/CybelAngelEventCollector/CybelAngelEventCollector.yml
  Packs/CybelAngel/Integrations/CybelAngelEventCollector/CybelAngelEventCollector_description.md
  Packs/CybelAngel/Integrations/CybelAngelEventCollector/CybelAngelEventCollector_image.png
  Packs/CybelAngel/Integrations/CybelAngelEventCollector/CybelAngelEventCollector_test.py
  Packs/CybelAngel/Integrations/CybelAngelEventCollector/README.md
  Packs/CybelAngel/Integrations/CybelAngelEventCollector/command_examples
  Packs/CybelAngel/ModelingRules/CybelAngel/CybelAngel.xif
  Packs/CybelAngel/ModelingRules/CybelAngel/CybelAngel.yml
  Packs/CybelAngel/ModelingRules/CybelAngel/CybelAngel_schema.json
  Packs/CybelAngel/README.md
  Packs/CybelAngel/pack_metadata.json
Labels: docs-approved

#33304 [XSUP-34558] Update GetMLModelEvaluation docker image
  Packs/Base/ReleaseNotes/1_33_40.md
  Packs/Base/Scripts/GetMLModelEvaluation/GetMLModelEvaluation.py
  Packs/Base/Scripts/GetMLModelEvaluation/GetMLModelEvaluation.yml
  Packs/Base/pack_metadata.json
Labels: docs-approved

#33295 Rasterize Fix Arrays Support
  Packs/rasterize/Integrations/rasterize/rasterize.py
  Packs/rasterize/Integrations/rasterize/rasterize.yml
  Packs/rasterize/Integrations/rasterize/rasterize_test.py
  Packs/rasterize/ReleaseNotes/2_0_3.md
  Packs/rasterize/pack_metadata.json
Labels: docs-approved, ForceMerge

#33317 Carbon Black EDR sort
  Packs/Carbon_Black_Enterprise_Response/Integrations/CarbonBlackResponseV2/CarbonBlackResponseV2.py
  Packs/Carbon_Black_Enterprise_Response/Integrations/CarbonBlackResponseV2/CarbonBlackResponseV2.yml
  Packs/Carbon_Black_Enterprise_Response/ReleaseNotes/2_1_46.md
  Packs/Carbon_Black_Enterprise_Response/pack_metadata.json
Labels: docs-approved, ForceMerge

#33064 [CIAC-6413][PANOS] Add CRUD commands for security profile groups
  Packs/PAN-OS/Integrations/Panorama/Panorama.py
  Packs/PAN-OS/Integrations/Panorama/Panorama.yml
  Packs/PAN-OS/Integrations/Panorama/Panorama_test.py
  Packs/PAN-OS/Integrations/Panorama/README.md
  Packs/PAN-OS/Integrations/Panorama/command_examples.txt
  Packs/PAN-OS/ReleaseNotes/2_1_24.md
  Packs/PAN-OS/TestPlaybooks/playbook-palo_alto_panorama_test_pb.yml
  Packs/PAN-OS/pack_metadata.json
  Tests/conf.json
Labels: docs-approved, ForceMerge

#33319 [ServiceNow v2] Add the add_as_entry arg to get-ticket-notes command
  Packs/ServiceNow/Integrations/ServiceNowv2/README.md
  Packs/ServiceNow/Integrations/ServiceNowv2/ServiceNowv2.py
  Packs/ServiceNow/Integrations/ServiceNowv2/ServiceNowv2.yml
  Packs/ServiceNow/Integrations/ServiceNowv2/ServiceNowv2_test.py
  Packs/ServiceNow/Integrations/ServiceNowv2/test_data/result_constants.py
  Packs/ServiceNow/ReleaseNotes/2_5_58.md
  Packs/ServiceNow/pack_metadata.json
Labels: docs-approved

#33158 [Symantec Messaging Gateway] Resolve Proxy Issues
  Packs/Symantec_Messaging_Gateway/Integrations/SymantecMessagingGateway/SymantecMessagingGateway.py
  Packs/Symantec_Messaging_Gateway/Integrations/SymantecMessagingGateway/SymantecMessagingGateway.yml
  Packs/Symantec_Messaging_Gateway/ReleaseNotes/1_0_16.md
  Packs/Symantec_Messaging_Gateway/pack_metadata.json
Labels: docs-approved

#33354 Update codeowners files to include the validate config file
  .github/CODEOWNERS
Labels: docs-approved

#33305 Fix wrong condition for using TAXII 2.0 instead of 2.1
  Packs/ApiModules/ReleaseNotes/2_2_22.md
  Packs/ApiModules/Scripts/TAXII2ApiModule/TAXII2ApiModule.py
  Packs/ApiModules/pack_metadata.json
  Packs/FeedDHS/ReleaseNotes/2_0_35.md
  Packs/FeedDHS/pack_metadata.json
  Packs/FeedMitreAttackv2/ReleaseNotes/1_1_31.md
  Packs/FeedMitreAttackv2/pack_metadata.json
  Packs/FeedTAXII/CONTRIBUTORS.json
  Packs/FeedTAXII/ReleaseNotes/1_2_10.md
  Packs/FeedTAXII/pack_metadata.json
Labels: Contribution, Contribution Form Filled, Community, pending-contributor, Xsoar Support Level, External PR

#33316 CyberTotal - return command result when non_field_errors exists
  Packs/CyberTotal/Integrations/CyberTotal/CyberTotal.py
  Packs/CyberTotal/Integrations/CyberTotal/CyberTotal.yml
  Packs/CyberTotal/ReleaseNotes/1_0_14.md
  Packs/CyberTotal/pack_metadata.json
Labels: docs-approved

#33325 [Microsoft Graph Security] update docs
  Packs/MicrosoftGraphSecurity/Integrations/MicrosoftGraphSecurity/MicrosoftGraphSecurity.yml
  Packs/MicrosoftGraphSecurity/Integrations/MicrosoftGraphSecurity/MicrosoftGraphSecurity_description.md
  Packs/MicrosoftGraphSecurity/Integrations/MicrosoftGraphSecurity/README.md
  Packs/MicrosoftGraphSecurity/ReleaseNotes/2_2_12.md
  Packs/MicrosoftGraphSecurity/pack_metadata.json
Labels: docs-approved

#33228 Service Now work_notes
  Packs/ServiceNow/Integrations/ServiceNowv2/ServiceNowv2.py
  Packs/ServiceNow/ReleaseNotes/2_5_59.md
  Packs/ServiceNow/Scripts/ServiceNowAddComment/ServiceNowAddComment.py
  Packs/ServiceNow/Scripts/ServiceNowAddComment/ServiceNowAddComment.yml
  Packs/ServiceNow/pack_metadata.json
Labels: docs-approved, ForceMerge

#32867 Large Upload Playbook
  Packs/CommonPlaybooks/Playbooks/playbook-Account_Enrichment_-_Generic_v2.2.yml
  Packs/CommonPlaybooks/Playbooks/playbook-Account_Enrichment_-_Generic_v2.2_README.md
  Packs/CommonPlaybooks/Playbooks/playbook-Command-Line_Analysis.yml
  Packs/CommonPlaybooks/Playbooks/playbook-Command-Line_Analysis_README.md
  Packs/CommonPlaybooks/Playbooks/playbook-File_Enrichment_-_Generic_v2.yml
  Packs/CommonPlaybooks/Playbooks/playbook-File_Enrichment_-_Generic_v2_README.md
  Packs/CommonPlaybooks/Playbooks/playbook-IP_Enrichment_-_Generic_v2.yml
  Packs/CommonPlaybooks/Playbooks/playbook-IP_Enrichment_-_Generic_v2_README.md
  Packs/CommonPlaybooks/Playbooks/playbook-Threat_Hunting_-_Generic_6_5.yml
  Packs/CommonPlaybooks/Playbooks/playbook-Threat_Hunting_-_Generic_6_5_README.md
  Packs/CommonPlaybooks/Playbooks/playbook-User_Investigation_-_Generic.yml
  Packs/CommonPlaybooks/Playbooks/playbook-User_Investigation_-_Generic_README.md
  Packs/CommonPlaybooks/ReleaseNotes/2_6_22.md
  Packs/CommonPlaybooks/pack_metadata.json
  Packs/CortexXDR/.pack-ignore
  Packs/CortexXDR/Layouts/layoutscontainer-Cortex_XDR_Incident.json
  Packs/CortexXDR/Playbooks/Cortex_XDR_-_Large_Upload.yml
  Packs/CortexXDR/Playbooks/Cortex_XDR_-_Large_Upload_README.md
  Packs/CortexXDR/Playbooks/Cortex_XDR_Alerts_Handling_v2.yml
  Packs/CortexXDR/Playbooks/Cortex_XDR_Alerts_Handling_v2_README.md
  Packs/CortexXDR/Playbooks/playbook-Cortex_XDR_-_Search_and_Compare_Process_Executions_-_XDR_Alerts.yml
  Packs/CortexXDR/Playbooks/playbook-Cortex_XDR_-_Search_and_Compare_Process_Executions_-_XDR_Alerts_README.md
  Packs/CortexXDR/ReleaseNotes/6_1_22.md
  Packs/CortexXDR/doc_files/Cortex_XDR_-_Large_Upload.png
  Packs/CortexXDR/doc_files/Cortex_XDR_Alerts_Handling_v2.png
  Packs/CortexXDR/pack_metadata.json
Labels: docs-approved

#33252 VirusTotal Fix File Sandbox Report Error Handling
  Packs/VirusTotal/CONTRIBUTORS.json
  Packs/VirusTotal/Integrations/VirusTotalV3/VirusTotalV3.py
  Packs/VirusTotal/Integrations/VirusTotalV3/VirusTotalV3.yml
  Packs/VirusTotal/Integrations/VirusTotalV3/VirusTotalV3_test.py
  Packs/VirusTotal/Playbooks/File_Enrichment_-_Virus_Total_v3.yml
  Packs/VirusTotal/ReleaseNotes/2_6_18.md
  Packs/VirusTotal/pack_metadata.json
Labels: Contribution, ready-for-instance-test, Contribution Form Filled, Community, Partner Support Level, External PR, Security Review, Partner-Approved

#32402 Containment_Plan test playbooks fix
  Packs/CommonPlaybooks/TestPlaybooks/playbook-Containment_Plan-Test.yml
Labels: docs-approved, ForceMerge

#33380 Carbon Black EDR YML Fix
  Packs/Carbon_Black_Enterprise_Response/Integrations/CarbonBlackResponseV2/CarbonBlackResponseV2.yml
  Packs/Carbon_Black_Enterprise_Response/ReleaseNotes/2_1_47.md
  Packs/Carbon_Black_Enterprise_Response/pack_metadata.json
Labels: docs-approved

#33386 Add log prints to Slack notifier
  Tests/scripts/common.py
  Tests/scripts/gitlab_slack_notifier.py
Labels: docs-approved

#31907 Update Listen Port description
  Packs/EDL/Integrations/EDL/EDL_description.md
  Packs/EDL/Integrations/EDL/README.md
  Packs/EDL/ReleaseNotes/3_2_21.md
  Packs/EDL/pack_metadata.json
  Packs/GenericWebhook/Integrations/GenericWebhook/GenericWebhook_description.md
  Packs/GenericWebhook/Integrations/GenericWebhook/README.md
  Packs/GenericWebhook/ReleaseNotes/1_0_28.md
  Packs/GenericWebhook/pack_metadata.json
  Packs/PingCastle/Integrations/PingCastle/README.md
  Packs/PublishList/Integrations/PublishList/PublishList_description.md
  Packs/PublishList/ReleaseNotes/1_1_3.md
  Packs/PublishList/pack_metadata.json
  Packs/SimpleAPIProxy/Integrations/SimpleAPIProxy/SimpleAPIProxy_description.md
  Packs/SimpleAPIProxy/ReleaseNotes/1_0_3.md
  Packs/SimpleAPIProxy/pack_metadata.json
  Packs/TAXIIServer/Integrations/TAXII2Server/TAXII2Server_description.md
  Packs/TAXIIServer/Integrations/TAXIIServer/README.md
  Packs/TAXIIServer/ReleaseNotes/2_0_57.md
  Packs/TAXIIServer/pack_metadata.json
  Packs/XsoarWebserver/Integrations/XSOARWebServer/README.md
Labels: docs-approved

#33392 SymantecMessagingGateway: fix an ssl connection error
  Packs/Symantec_Messaging_Gateway/Integrations/SymantecMessagingGateway/SymantecMessagingGateway.py
  Packs/Symantec_Messaging_Gateway/ReleaseNotes/1_0_17.md
  Packs/Symantec_Messaging_Gateway/pack_metadata.json
Labels: docs-approved

#33364 [Microsoft Graph Mail] update docs and sections
  Packs/MicrosoftGraphMail/Integrations/MicrosoftGraphListener/MicrosoftGraphListener.yml
  Packs/MicrosoftGraphMail/Integrations/MicrosoftGraphListener/MicrosoftGraphListener_description.md
  Packs/MicrosoftGraphMail/Integrations/MicrosoftGraphMail/MicrosoftGraphMail.yml
  Packs/MicrosoftGraphMail/Integrations/MicrosoftGraphMail/MicrosoftGraphMail_description.md
  Packs/MicrosoftGraphMail/ReleaseNotes/1_6_5.md
  Packs/MicrosoftGraphMail/pack_metadata.json
Labels: docs-approved

#33310 [Zscaler] - fix zscaler-category-remove-ip, zscaler-category-add-ip
  Packs/Zscaler/.secrets-ignore
  Packs/Zscaler/Integrations/Zscaler/README.md
  Packs/Zscaler/Integrations/Zscaler/Zscaler.py
  Packs/Zscaler/Integrations/Zscaler/Zscaler.yml
  Packs/Zscaler/Integrations/Zscaler/Zscaler_test.py
  Packs/Zscaler/Integrations/Zscaler/test_data/results/blacklist_urls.txt
  Packs/Zscaler/Integrations/Zscaler/test_data/results/remove_ip.json
  Packs/Zscaler/Integrations/Zscaler/test_data/results/undo_blacklist_urls.txt
  Packs/Zscaler/ReleaseNotes/1_3_17.md
  Packs/Zscaler/pack_metadata.json
Labels: docs-approved

#33347 MSFT Sysmon Mapping
  Packs/MicrosoftWindowsEvents/ParsingRules/MicrosoftWindowsEvents/MicrosoftWindowsEvents.xif
  Packs/MicrosoftWindowsEvents/README.md
  Packs/MicrosoftWindowsEvents/ReleaseNotes/1_1_8.md
  Packs/MicrosoftWindowsEvents/pack_metadata.json
  Packs/MicrosoftWindowsSysmon/.pack-ignore
  Packs/MicrosoftWindowsSysmon/.secrets-ignore
  Packs/MicrosoftWindowsSysmon/ModelingRules/MicrosoftWindowsSysmon/MicrosoftWindowsSysmon.xif
  Packs/MicrosoftWindowsSysmon/ModelingRules/MicrosoftWindowsSysmon/MicrosoftWindowsSysmon.yml
  Packs/MicrosoftWindowsSysmon/ModelingRules/MicrosoftWindowsSysmon/MicrosoftWindowsSysmon_schema.json
  Packs/MicrosoftWindowsSysmon/ParsingRules/MicrosoftWindowsSysmon/MicrosoftWindowsSysmon.xif
  Packs/MicrosoftWindowsSysmon/ParsingRules/MicrosoftWindowsSysmon/MicrosoftWindowsSysmon.yml
  Packs/MicrosoftWindowsSysmon/README.md
  Packs/MicrosoftWindowsSysmon/pack_metadata.json
Labels: docs-approved

#33203 CommonServerPython: Improved implementation of *ConnectionError* handling
  Packs/Base/ReleaseNotes/1_33_41.md
  Packs/Base/Scripts/CommonServerPython/CommonServerPython.py
  Packs/Base/Scripts/CommonServerPython/CommonServerPython_test.py
  Packs/Base/pack_metadata.json
Labels: docs-approved

#33394 [netskope_api_v2] Fixed an issue in the list_type argument
  Packs/Netskope/Integrations/NetskopeAPIv2/NetskopeAPIv2.py
  Packs/Netskope/Integrations/NetskopeAPIv2/NetskopeAPIv2.yml
  Packs/Netskope/ReleaseNotes/3_3_7.md
  Packs/Netskope/pack_metadata.json
Labels: docs-approved

#33341 [ServiceNow v2] Fixed issue in mirroring
  Packs/ServiceNow/Classifiers/classifier-mapper-incoming-ServiceNow.json
  Packs/ServiceNow/Integrations/ServiceNowv2/ServiceNowv2.py
  Packs/ServiceNow/Integrations/ServiceNowv2/ServiceNowv2_test.py
  Packs/ServiceNow/Integrations/ServiceNowv2/test_data/response_constants.py
  Packs/ServiceNow/ReleaseNotes/2_5_60.md
  Packs/ServiceNow/pack_metadata.json
Labels: docs-approved

#33247 [Microsoft Teams] add microsoft-teams-graph-auth-reset command
  Packs/MicrosoftTeams/Integrations/MicrosoftTeams/MicrosoftTeams.py
  Packs/MicrosoftTeams/Integrations/MicrosoftTeams/MicrosoftTeams.yml
  Packs/MicrosoftTeams/Integrations/MicrosoftTeams/README.md
  Packs/MicrosoftTeams/ReleaseNotes/1_4_55.md
  Packs/MicrosoftTeams/pack_metadata.json
Labels: docs-approved

#33402 Cortex XDR - IOC - update xdr-iocs-create-sync-file in README
  Packs/CortexXDR/Integrations/XDR_iocs/README.md
Labels: docs-approved

#33407 fixing csv key passing
  Packs/CommonScripts/ReleaseNotes/1_14_18.md
  Packs/CommonScripts/Scripts/DeleteContext/DeleteContext.js
  Packs/CommonScripts/pack_metadata.json
Labels: docs-approved

#33403 Active Directory Query - correct argument name in add_member_to_group()
  Packs/Active_Directory_Query/Integrations/Active_Directory_Query/Active_Directory_Query.py
  Packs/Active_Directory_Query/ReleaseNotes/1_6_33.md
  Packs/Active_Directory_Query/pack_metadata.json
Labels: Contribution, ready-for-instance-test, Contribution Form Filled, Community, Xsoar Support Level, External PR

#33210 Jamf Protect Event Collector
  Packs/JamfProtect/.pack-ignore
  Packs/JamfProtect/.secrets-ignore
  Packs/JamfProtect/Integrations/JamfProtectEventCollector/JamfProtectEventCollector.py
  Packs/JamfProtect/Integrations/JamfProtectEventCollector/JamfProtectEventCollector.yml
  Packs/JamfProtect/Integrations/JamfProtectEventCollector/JamfProtectEventCollector_description.md
  Packs/JamfProtect/Integrations/JamfProtectEventCollector/JamfProtectEventCollector_image.png
  Packs/JamfProtect/Integrations/JamfProtectEventCollector/JamfProtectEventCollector_test.py
  Packs/JamfProtect/Integrations/JamfProtectEventCollector/README.md
  Packs/JamfProtect/Integrations/JamfProtectEventCollector/command_examples.txt
  Packs/JamfProtect/Integrations/JamfProtectEventCollector/test_data/raw_alerts.json
  Packs/JamfProtect/Integrations/JamfProtectEventCollector/test_data/raw_audits.json
  Packs/JamfProtect/ModelingRules/JamfProtect/JamfProtect.xif
  Packs/JamfProtect/ModelingRules/JamfProtect/JamfProtect.yml
  Packs/JamfProtect/ModelingRules/JamfProtect/JamfProtect_schema.json
  Packs/JamfProtect/README.md
  Packs/JamfProtect/pack_metadata.json
Labels: docs-approved

#33311 TOPDesk Integration: Add defaultCallerId
  Packs/TOPdesk/Integrations/TOPdesk/README.md
  Packs/TOPdesk/Integrations/TOPdesk/TOPdesk.py
  Packs/TOPdesk/Integrations/TOPdesk/TOPdesk.yml
  Packs/TOPdesk/ReleaseNotes/1_2_11.md
  Packs/TOPdesk/pack_metadata.json
Labels: Contribution, docs-approved, ready-for-instance-test, Contribution Form Filled, Community, Xsoar Support Level, External PR

#33411 Phishing generic v3 non malicious emails
  Packs/Phishing/Playbooks/Phishing_-_Generic_v3_6_8.yml
  Packs/Phishing/Playbooks/Phishing_-_Generic_v3_6_8_README.md
  Packs/Phishing/ReleaseNotes/3_6_13.md
  Packs/Phishing/doc_files/Phishing_-_Generic_v3.png
  Packs/Phishing/pack_metadata.json
Labels: docs-approved

#33421 fix is not in cidr bug
  Packs/FiltersAndTransformers/ReleaseNotes/1_2_65.md
  Packs/FiltersAndTransformers/Scripts/IsNotInCidrRanges/IsNotInCidrRanges.js
  Packs/FiltersAndTransformers/TestPlaybooks/playbook-TestIsNotInCidrRanges.yml
  Packs/FiltersAndTransformers/pack_metadata.json
Labels: docs-approved

#33293 Adding support for uploading the delta from Last Upload in builds
  Tests/scripts/collect_tests/collect_tests.py
  Tests/scripts/infrastructure_tests/test_collect_tests.py
Labels: docs-approved

#33410 CIAC-10004/Change-Triage-SLA-incident-field-to-searchable
  Packs/CommonTypes/IncidentFields/incidentfield-Containment_SLA.json
  Packs/CommonTypes/IncidentFields/incidentfield-Incident_Duration.json
  Packs/CommonTypes/IncidentFields/incidentfield-Triage_SLA.json
  Packs/CommonTypes/ReleaseNotes/3_4_6.md
  Packs/CommonTypes/pack_metadata.json
Labels: docs-approved

#33298 Cortex xdr incident handling enhancement
  Packs/CortexXDR/Playbooks/Cortex_XDR_Alerts_Handling_v2.yml
  Packs/CortexXDR/Playbooks/Cortex_XDR_incident_handling_v3_6_5.yml
  Packs/CortexXDR/ReleaseNotes/6_1_24.md
  Packs/CortexXDR/doc_files/Cortex_XDR_Alerts_Handling_v2.png
  Packs/CortexXDR/pack_metadata.json
Labels: docs-approved

#33419 New fields
  Packs/CommonTypes/.pack-ignore
  Packs/CommonTypes/IndicatorFields/indicatorfield-numberofsubkeys.json
  Packs/CommonTypes/IndicatorFields/indicatorfield-samples.json
  Packs/CommonTypes/ReleaseNotes/3_4_7.md
  Packs/CommonTypes/pack_metadata.json
Labels: docs-approved

#33306 Add copy command to Google Cloud Storage integration
  Packs/GoogleCloudStorage/Integrations/GoogleCloudStorage/GoogleCloudStorage.py
  Packs/GoogleCloudStorage/Integrations/GoogleCloudStorage/GoogleCloudStorage.yml
  Packs/GoogleCloudStorage/Integrations/GoogleCloudStorage/README.md
  Packs/GoogleCloudStorage/ReleaseNotes/1_0_13.md
  Packs/GoogleCloudStorage/pack_metadata.json
Labels: Contribution, docs-approved, Contribution Form Filled, Community, Xsoar Support Level, External PR

#32824 XSUP-32897
  Packs/EmailCommunication/ReleaseNotes/2_0_26.md
  Packs/EmailCommunication/Scripts/SendEmailReply/SendEmailReply.py
  Packs/EmailCommunication/Scripts/SendEmailReply/SendEmailReply.yml
  Packs/EmailCommunication/Scripts/SendEmailReply/SendEmailReply_test.py
  Packs/EmailCommunication/pack_metadata.json
Labels: docs-approved

#33429 MISP v3 - add certificates
  Packs/MISP/Integrations/MISPV3/MISPV3.py
  Packs/MISP/Integrations/MISPV3/MISPV3.yml
  Packs/MISP/Integrations/MISPV3/README.md
  Packs/MISP/ReleaseNotes/2_1_42.md
  Packs/MISP/pack_metadata.json
Labels: docs-approved

#33425 Gmail: fix fetch duplicate incident
  Packs/Gmail/Integrations/Gmail/Gmail.py
  Packs/Gmail/Integrations/Gmail/Gmail.yml
  Packs/Gmail/Integrations/Gmail/Gmail_test.py
  Packs/Gmail/Integrations/Gmail/test_data/input_data.py
  Packs/Gmail/ReleaseNotes/1_3_18.md
  Packs/Gmail/pack_metadata.json
Labels: docs-approved

#33443 Add link to supported file types
  Packs/Palo_Alto_Networks_WildFire/Integrations/Palo_Alto_Networks_WildFire_v2/README.md
Labels: docs-approved

#32691 Symantec dlp modeling
  Packs/SymantecDLP/ModelingRules/SymantecDLP/SymantecDLP.xif
  Packs/SymantecDLP/ModelingRules/SymantecDLP/SymantecDLP.yml
  Packs/SymantecDLP/ModelingRules/SymantecDLP/SymantecDLP_schema.json
  Packs/SymantecDLP/README.md
  Packs/SymantecDLP/ReleaseNotes/2_1_3.md
  Packs/SymantecDLP/pack_metadata.json
Labels: docs-approved

#33446 Tenable_sc: short the description
  Packs/Tenable_sc/Integrations/Tenable_sc/README.md
  Packs/Tenable_sc/Integrations/Tenable_sc/Tenable_sc.yml
  Packs/Tenable_sc/ReleaseNotes/1_0_12.md
  Packs/Tenable_sc/pack_metadata.json
Labels: docs-approved, ForceMerge

#33408 Azure EXPANDR-8554 - Minor Typo/Bug Fix
  Packs/Azure-Enrichment-Remediation/Playbooks/Azure_-_Network_Security_Group_Remediation.yml
  Packs/Azure-Enrichment-Remediation/ReleaseNotes/1_1_15.md
  Packs/Azure-Enrichment-Remediation/doc_files/Azure_-_Network_Security_Group_Remediation.png
  Packs/Azure-Enrichment-Remediation/pack_metadata.json
Labels: Contribution, docs-approved, Contribution Form Filled, Community, Xsoar Support Level, External PR, Security Review

#33444 EWS O365 - fix fetch emails
  Packs/MicrosoftExchangeOnline/Integrations/EWSO365/EWSO365.py
  Packs/MicrosoftExchangeOnline/ReleaseNotes/1_2_44.md
  Packs/MicrosoftExchangeOnline/pack_metadata.json
Labels: docs-approved

#33448 workaround for mypack bug
  .gitlab/ci/.gitlab-ci.global.yml
Labels: docs-approved

#33232 [pre-commit] - add the validate-deleted-files hook
  .pre-commit-config_template.yaml
Labels: docs-approved

#33441 Move PingCastle to Community Support
  Packs/PingCastle/ReleaseNotes/1_0_9.md
  Packs/PingCastle/pack_metadata.json
Labels: docs-approved

#33456 Release new base pack
  Packs/Base/ReleaseNotes/1_33_43.md
  Packs/Base/Scripts/SanePdfReport/SanePdfReport.yml
  Packs/Base/pack_metadata.json
Labels: docs-approved

#33435 Add proxy to zimperium
  Packs/Zimperium/Integrations/ZimperiumV2/ZimperiumV2.py
  Packs/Zimperium/Integrations/ZimperiumV2/ZimperiumV2.yml
  Packs/Zimperium/Integrations/ZimperiumV2/ZimperiumV2_test.py
  Packs/Zimperium/ReleaseNotes/2_0_2.md
  Packs/Zimperium/pack_metadata.json
Labels: docs-approved

#33433 Teams docs and logs upate
  Packs/MicrosoftTeams/Integrations/MicrosoftTeams/MicrosoftTeams.py
  Packs/MicrosoftTeams/Integrations/MicrosoftTeams/README.md
  Packs/MicrosoftTeams/ReleaseNotes/1_4_56.md
  Packs/MicrosoftTeams/pack_metadata.json
Labels: docs-approved

#33420 CIAC-8501 FortiManager XSIAM Modeling
  Packs/FortiManager/ModelingRules/FortiManager/FortiManager.xif
  Packs/FortiManager/ModelingRules/FortiManager/FortiManager.yml
  Packs/FortiManager/ModelingRules/FortiManager/FortiManager_schema.json
  Packs/FortiManager/ParsingRules/FortiManager/FortiManager.xif
  Packs/FortiManager/ParsingRules/FortiManager/FortiManager.yml
  Packs/FortiManager/README.md
  Packs/FortiManager/ReleaseNotes/1_0_9.md
  Packs/FortiManager/pack_metadata.json
Labels: docs-approved

#33457 Rf threshold bug fix
  Packs/FeedRecordedFuture/Integrations/FeedRecordedFuture/FeedRecordedFuture.py
  Packs/FeedRecordedFuture/Integrations/FeedRecordedFuture/FeedRecordedFuture_test.py
  Packs/FeedRecordedFuture/ReleaseNotes/1_1_2.md
  Packs/FeedRecordedFuture/pack_metadata.json
Labels: docs-approved

#33447 [Gmail] Added To`contextPath` The `File.EntryID`&`File.Extension`
  Packs/Gmail/Integrations/Gmail/Gmail.yml
  Packs/Gmail/Integrations/Gmail/README.md
  Packs/Gmail/Integrations/Gmail/command_examples
  Packs/Gmail/ReleaseNotes/1_3_19.md
  Packs/Gmail/pack_metadata.json
Labels: docs-approved

#33139 Redmine integration
  Packs/Redmine/.pack-ignore
  Packs/Redmine/.secrets-ignore
  Packs/Redmine/Integrations/Redmine/README.md
  Packs/Redmine/Integrations/Redmine/Redmine.py
  Packs/Redmine/Integrations/Redmine/Redmine.yml
  Packs/Redmine/Integrations/Redmine/Redmine_description.md
  Packs/Redmine/Integrations/Redmine/Redmine_image.png
  Packs/Redmine/Integrations/Redmine/Redmine_test.py
  Packs/Redmine/Integrations/Redmine/TestPlaybooks/Redmine-Test.yml
  Packs/Redmine/Integrations/Redmine/command_examples
  Packs/Redmine/README.md
  Packs/Redmine/pack_metadata.json
  Tests/conf.json
Labels: docs-approved

#32482 adding support in new api call
  Packs/CortexXDR/Integrations/CortexXDRIR/CortexXDRIR.py
  Packs/CortexXDR/Integrations/CortexXDRIR/CortexXDRIR.yml
  Packs/CortexXDR/Integrations/CortexXDRIR/CortexXDRIR_test.py
  Packs/CortexXDR/Integrations/CortexXDRIR/test_data/get_extra_data_all_alerts.json
  Packs/CortexXDR/Integrations/CortexXDRIR/test_data/get_incident_extra_data_host_id_array.json
  Packs/CortexXDR/Integrations/CortexXDRIR/test_data/get_incidents_list_multiple_incidents_extra_data.json
  Packs/CortexXDR/Integrations/CortexXDRIR/test_data/get_multiple_incidents_extra_data.json
  Packs/CortexXDR/ReleaseNotes/6_1_25.md
  Packs/CortexXDR/pack_metadata.json
Labels: docs-approved, ForceMerge

#32986 TAXII2 Indicator Fields
  Packs/ApiModules/Scripts/TAXII2ApiModule/TAXII2ApiModule.py
  Packs/ApiModules/Scripts/TAXII2ApiModule/TAXII2ApiModule_test.py
  Packs/ApiModules/Scripts/TAXII2ApiModule/test_data/cortex_parsed_indicators_17-19.json
  Packs/ApiModules/Scripts/TAXII2ApiModule/test_data/cortex_parsed_indicators_complex_20-19.json
  Packs/ApiModules/Scripts/TAXII2ApiModule/test_data/cortex_parsed_indicators_complex_skipped_14-19.json
  Packs/ApiModules/Scripts/TAXII2ApiModule/test_data/parsed_stix_objects.json
  Packs/FeedDHS/.pack-ignore
  Packs/FeedDHS/ReleaseNotes/2_0_36.md
  Packs/FeedDHS/pack_metadata.json
  Packs/FeedMitreAttackv2/.pack-ignore
  Packs/FeedMitreAttackv2/ReleaseNotes/1_1_32.md
  Packs/FeedMitreAttackv2/pack_metadata.json
  Packs/FeedTAXII/.pack-ignore
  Packs/FeedTAXII/ReleaseNotes/1_2_11.md
  Packs/FeedTAXII/pack_metadata.json
Labels: docs-approved

#33472 remove myself
  .github/content_roles.json
Labels: docs-approved

#33477 change playbook location
  Packs/Redmine/TestPlaybooks/Redmine-Test.yml
Labels: docs-approved

#33461 Fix for the visuality of phishing generic v3
  Packs/Phishing/Playbooks/Phishing_-_Generic_v3_6_8.yml
  Packs/Phishing/Playbooks/Phishing_-_Generic_v3_6_8_README.md
  Packs/Phishing/ReleaseNotes/3_6_15.md
  Packs/Phishing/pack_metadata.json
Labels: docs-approved

#33365 Feature/ciac 9941/service now add delete attachment
  Packs/ServiceNow/Integrations/ServiceNowv2/README.md
  Packs/ServiceNow/Integrations/ServiceNowv2/ServiceNowv2.py
  Packs/ServiceNow/Integrations/ServiceNowv2/ServiceNowv2.yml
  Packs/ServiceNow/Integrations/ServiceNowv2/ServiceNowv2_test.py
  Packs/ServiceNow/Integrations/ServiceNowv2/command_examples.txt
  Packs/ServiceNow/ReleaseNotes/2_5_61.md
  Packs/ServiceNow/TestPlaybooks/playbook-ServiceNow_Test_New.yml
  Packs/ServiceNow/pack_metadata.json
Labels: docs-approved

#33315 Feature/ciac 9901/jira v3 add delete attachment command
  Packs/Jira/Integrations/JiraV3/JiraV3.py
  Packs/Jira/Integrations/JiraV3/JiraV3.yml
  Packs/Jira/Integrations/JiraV3/JiraV3_test.py
  Packs/Jira/Integrations/JiraV3/README.md
  Packs/Jira/ReleaseNotes/3_1_12.md
  Packs/Jira/TestPlaybooks/playbook_JiraV3_Test.yml
  Packs/Jira/pack_metadata.json
Labels: docs-approved

#33122 "Cloud Response - generic" Fixes
  Packs/AWS-Enrichment-Remediation/Playbooks/playbook-Cloud_Response_-_AWS.yml
  Packs/AWS-Enrichment-Remediation/ReleaseNotes/1_1_17.md
  Packs/AWS-Enrichment-Remediation/pack_metadata.json
  Packs/CommonPlaybooks/Playbooks/playbook-Cloud_Response_-_Generic.yml
  Packs/CommonPlaybooks/ReleaseNotes/2_6_25.md
  Packs/CommonPlaybooks/doc_files/Cloud_Response_-_Generic.png
  Packs/CommonPlaybooks/pack_metadata.json
  Packs/GCP-Enrichment-Remediation/Playbooks/playbook-Cloud_Response_-_GCP.yml
  Packs/GCP-Enrichment-Remediation/Playbooks/playbook-Cloud_Response_-_GCP_README.md
  Packs/GCP-Enrichment-Remediation/ReleaseNotes/1_1_17.md
  Packs/GCP-Enrichment-Remediation/doc_files/Cloud_Response_-_GCP.png
  Packs/GCP-Enrichment-Remediation/pack_metadata.json
Labels: docs-approved

#33336 Cybereason v2.1.17
  Packs/Cybereason/Integrations/Cybereason/Cybereason.py
  Packs/Cybereason/Integrations/Cybereason/Cybereason.yml
  Packs/Cybereason/Integrations/Cybereason/Cybereason_test.py
  Packs/Cybereason/Integrations/Cybereason/README.md
  Packs/Cybereason/Integrations/Cybereason/test_data/query_malop_management_raw_response.json
  Packs/Cybereason/ReleaseNotes/2_1_17.md
  Packs/Cybereason/Scripts/CybereasonPreProcessingExample/CybereasonPreProcessingExample.py
  Packs/Cybereason/Scripts/CybereasonPreProcessingExample/CybereasonPreProcessingExample.yml
  Packs/Cybereason/pack_metadata.json
Labels: Contribution, Partner, Contribution Form Filled, Partner Support Level, External PR, Partner-Approved

#33492 fix description Microsoft Defender
  Packs/WindowsDefenderAdvancedThreatProtection/pack_metadata.json
Labels: docs-approved

#33258 ReadPDFFileV2 unescaping
  Packs/CommonPlaybooks/.pack-ignore
  Packs/CommonPlaybooks/Playbooks/playbook-Extract_Indicators_From_File_-_Generic_v2_4_5.yml
  Packs/CommonPlaybooks/ReleaseNotes/2_6_26.md
  Packs/CommonPlaybooks/pack_metadata.json
  Packs/CommonScripts/.pack-ignore
  Packs/CommonScripts/ReleaseNotes/1_14_20.json
  Packs/CommonScripts/ReleaseNotes/1_14_20.md
  Packs/CommonScripts/Scripts/ReadPDFFileV2/ReadPDFFileV2.py
  Packs/CommonScripts/Scripts/ReadPDFFileV2/ReadPDFFileV2.yml
  Packs/CommonScripts/Scripts/ReadPDFFileV2/ReadPDFFileV2_test.py
  Packs/CommonScripts/Scripts/ReadPDFFileV2/test_data/xml_with_urls.pdf
  Packs/CommonScripts/TestPlaybooks/playbook-ConvertFile-Test.yml
  Packs/CommonScripts/TestPlaybooks/playbook-ReadPDFFileV2_Test.yml
  Packs/CommonScripts/pack_metadata.json
Labels: docs-approved
