Repository demisto/content, pull requests merged in 2024-08, with the labels that each got.

#35693 O365 Mapping Update
  Packs/Office365/ModelingRules/Office365/Office365.xif
  Packs/Office365/ModelingRules/Office365/Office365_schema.json
  Packs/Office365/ReleaseNotes/1_0_2.md
  Packs/Office365/pack_metadata.json
Labels: docs-approved, bypass.url

#35649 Update indicatorfield-primary_motivation.json
  Packs/CommonTypes/IndicatorFields/indicatorfield-primary_motivation.json
  Packs/CommonTypes/ReleaseNotes/3_5_11.md
  Packs/CommonTypes/pack_metadata.json
Labels: Contribution, Contribution Form Filled, Community, Xsoar Support Level, External PR, Security Review

#35645 update ml docker
  Packs/Base/ReleaseNotes/1_34_31.md
  Packs/Base/Scripts/DBotFindSimilarIncidents/DBotFindSimilarIncidents.yml
  Packs/Base/Scripts/DBotFindSimilarIncidentsByIndicators/DBotFindSimilarIncidentsByIndicators.yml
  Packs/Base/Scripts/DBotPredictPhishingWords/DBotPredictPhishingWords.yml
  Packs/Base/Scripts/DBotPreprocessTextData/DBotPreprocessTextData.yml
  Packs/Base/Scripts/DBotTrainTextClassifierV2/DBotTrainTextClassifierV2.yml
  Packs/Base/Scripts/GetMLModelEvaluation/GetMLModelEvaluation.yml
  Packs/Base/pack_metadata.json
  Packs/ML/ReleaseNotes/1_4_13.md
  Packs/ML/Scripts/DBotPredictOutOfTheBoxV2/DBotPredictOutOfTheBoxV2.yml
  Packs/ML/pack_metadata.json
Labels: docs-approved

#35691 Carbon Black Enterprise EDR Device list fix
  Packs/CarbonBlackEnterpriseEDR/Integrations/CarbonBlackEnterpriseEDR/CarbonBlackEnterpriseEDR.py
  Packs/CarbonBlackEnterpriseEDR/Integrations/CarbonBlackEnterpriseEDR/CarbonBlackEnterpriseEDR.yml
  Packs/CarbonBlackEnterpriseEDR/ReleaseNotes/1_1_37.md
  Packs/CarbonBlackEnterpriseEDR/TestPlaybooks/Carbon_Black_Enterprise_EDR_Test.yml
  Packs/CarbonBlackEnterpriseEDR/pack_metadata.json
  Tests/conf.json
Labels: docs-approved

#35715 Stop Interpreting Special Characters
  .github/workflows/update-demisto-sdk-version.yml
Labels: docs-approved

#35662 bug fix gmail reply mail
  Packs/Gmail/Integrations/Gmail/Gmail.py
  Packs/Gmail/ReleaseNotes/1_3_23.md
  Packs/Gmail/pack_metadata.json
  Packs/GmailSingleUser/Integrations/GmailSingleUser/GmailSingleUser.py
  Packs/GmailSingleUser/ReleaseNotes/1_4_4.md
  Packs/GmailSingleUser/pack_metadata.json
Labels: docs-approved, ForceMerge

#35718 Update CODEOWNERS with ML scripts
  .github/CODEOWNERS
Labels: docs-approved

#35647 added skip proxy if proxy is false
  Packs/EclecticIQ/Integrations/EclecticIQIntelligenceCenterv3/EclecticIQIntelligenceCenterv3.py
  Packs/EclecticIQ/Integrations/EclecticIQIntelligenceCenterv3/EclecticIQIntelligenceCenterv3_test.py
  Packs/EclecticIQ/ReleaseNotes/3_0_2.md
  Packs/EclecticIQ/pack_metadata.json
Labels: Contribution, docs-approved, Partner, Contribution Form Filled, Partner Support Level, External PR, Partner-Approved, TIM Review

#35717 Fix set-junk-rules regular and global commands
  Packs/MicrosoftExchangeOnline/Integrations/EwsExtensionEXOPowershellV3/EwsExtensionEXOPowershellV3.ps1
  Packs/MicrosoftExchangeOnline/ReleaseNotes/1_4_5.md
  Packs/MicrosoftExchangeOnline/pack_metadata.json
Labels: docs-approved

#35664 bug fix arg to boolean
  Packs/FeedRecordedFuture/Integrations/FeedRecordedFuture/FeedRecordedFuture.py
  Packs/FeedRecordedFuture/Integrations/FeedRecordedFuture/FeedRecordedFuture.yml
  Packs/FeedRecordedFuture/ReleaseNotes/1_1_4.md
  Packs/FeedRecordedFuture/pack_metadata.json
Labels: docs-approved

#35725 Microsoft Defender Collector - limit issue
  Packs/MicrosoftCloudAppSecurity/Integrations/MicrosoftDefenderEventCollector/MicrosoftDefenderEventCollector.py
  Packs/MicrosoftCloudAppSecurity/Integrations/MicrosoftDefenderEventCollector/MicrosoftDefenderEventCollector.yml
  Packs/MicrosoftCloudAppSecurity/ReleaseNotes/2_2_3.json
  Packs/MicrosoftCloudAppSecurity/ReleaseNotes/2_2_3.md
  Packs/MicrosoftCloudAppSecurity/pack_metadata.json
Labels: docs-approved

#35731 commit
  Tests/conf.json
Labels: docs-approved

#35729 New pack for Unit42 Blog Fighting Ursa
  Packs/Unit42_Threat_Brief_-_Fighting_Ursa/.pack-ignore
  Packs/Unit42_Threat_Brief_-_Fighting_Ursa/.secrets-ignore
  Packs/Unit42_Threat_Brief_-_Fighting_Ursa/Playbooks/playbook-Fighting_Ursa_Luring_Targets_With_Car_For_Sale.yml
  Packs/Unit42_Threat_Brief_-_Fighting_Ursa/Playbooks/playbook-Fighting_Ursa_Luring_Targets_With_Car_For_Sale_README.md
  Packs/Unit42_Threat_Brief_-_Fighting_Ursa/README.md
  Packs/Unit42_Threat_Brief_-_Fighting_Ursa/doc_files/Fighting_Ursa_Luring_Targets_With_Car_For_Sale.png
  Packs/Unit42_Threat_Brief_-_Fighting_Ursa/pack_metadata.json
Labels: docs-approved

#35701 Fix upload rel paths
  Packs/FeedGitHub/Integrations/FeedGitHub/FeedGitHub_description.md
  Packs/FeedGitHub/ReleaseNotes/1_0_6.md
  Packs/FeedGitHub/pack_metadata.json
Labels: docs-approved

#35726 Add EWS v2 to phishing v3 domain EML malicious
  Tests/conf.json
Labels: docs-approved

#35646 [rasterize] Fix timeout for mailto URLs
  Packs/rasterize/Integrations/rasterize/rasterize.py
  Packs/rasterize/Integrations/rasterize/rasterize_test.py
  Packs/rasterize/ReleaseNotes/2_0_22.md
  Packs/rasterize/pack_metadata.json
Labels: docs-approved, ForceMerge

#35702 DisplayHTMLWithImages: added support for XSOAR 8
  Packs/CommonScripts/ReleaseNotes/1_15_41.md
  Packs/CommonScripts/Scripts/DisplayHTMLWithImages/DisplayHTMLWithImages.py
  Packs/CommonScripts/Scripts/DisplayHTMLWithImages/DisplayHTMLWithImages.yml
  Packs/CommonScripts/Scripts/DisplayHTMLWithImages/DisplayHTMLWithImages_test.py
  Packs/CommonScripts/pack_metadata.json
Labels: docs-approved

#35542 fix cb eedr testplaybook
  Packs/CarbonBlackEnterpriseEDR/Integrations/CarbonBlackEnterpriseEDR/CarbonBlackEnterpriseEDR.py
  Packs/CarbonBlackEnterpriseEDR/Integrations/CarbonBlackEnterpriseEDR/CarbonBlackEnterpriseEDR.yml
  Packs/CarbonBlackEnterpriseEDR/Integrations/CarbonBlackEnterpriseEDR/CarbonBlackEnterpriseEDR_test.py
  Packs/CarbonBlackEnterpriseEDR/ReleaseNotes/1_1_38.md
  Packs/CarbonBlackEnterpriseEDR/TestPlaybooks/Carbon_Black_Enterprise_EDR_Process_Search_Test.yml
  Packs/CarbonBlackEnterpriseEDR/TestPlaybooks/Carbon_Black_Enterprise_EDR_Test.yml
  Packs/CarbonBlackEnterpriseEDR/TestPlaybooks/Carbon_Black_Enterprise_EDR_alert-workflow-update_Test.yml
  Packs/CarbonBlackEnterpriseEDR/TestPlaybooks/Carbon_Black_Enterprise_EDR_process_search_with_polling_test.yml
  Packs/CarbonBlackEnterpriseEDR/pack_metadata.json
  Tests/conf.json
Labels: docs-approved, sync-gsm

#35708 CRTX-123835 Cisco ASA Modeling Filter Fix for 302015
  Packs/CiscoASA/ModelingRules/CiscoASA_1_4/CiscoASA_1_4.xif
  Packs/CiscoASA/ReleaseNotes/1_1_9.md
  Packs/CiscoASA/pack_metadata.json
Labels: docs-approved

#35580 Qualys vmdr: added nextTigger to fetch assets
  Packs/Base/ReleaseNotes/1_34_32.md
  Packs/Base/Scripts/CommonServerPython/CommonServerPython.py
  Packs/Base/Scripts/CommonServerPython/CommonServerPython_test.py
  Packs/Base/pack_metadata.json
  Packs/qualys/Integrations/Qualysv2/Qualysv2.py
  Packs/qualys/Integrations/Qualysv2/Qualysv2.yml
  Packs/qualys/Integrations/Qualysv2/Qualysv2_test.py
  Packs/qualys/ReleaseNotes/3_0_5.md
  Packs/qualys/TestPlaybooks/QualysVulnerabilityManagement-Test.yml
  Packs/qualys/pack_metadata.json
Labels: docs-approved

#35738 Updated the security reviewers and the logic to select them
  .github/content_roles.json
  .github/github_workflow_scripts/handle_external_pr.py
Labels: docs-approved

#35743 Update get_content_reviewers
  .github/github_workflow_scripts/utils.py
  .github/github_workflow_scripts/utils_test.py
Labels: docs-approved

#35737 Impartner from version
  Packs/Impartner/Integrations/Impartner/Impartner.yml
  Packs/Impartner/ReleaseNotes/1_0_2.md
  Packs/Impartner/pack_metadata.json
Labels: docs-approved

#35746 Change contribution lead.
  .github/content_roles.json
Labels: docs-approved

#35421 Update DBotTrainClustering docker
  Packs/Base/.secrets-ignore
  Packs/Base/ReleaseNotes/1_34_33.md
  Packs/Base/Scripts/DBotTrainClustering/DBotTrainClustering.py
  Packs/Base/Scripts/DBotTrainClustering/DBotTrainClustering.yml
  Packs/Base/Scripts/DBotTrainClustering/README.md
  Packs/Base/Scripts/DBotTrainClustering/dbottrainclustering_test.py
  Packs/Base/TestPlaybooks/playbook-DBotTrainClustering-test.yml
  Packs/Base/pack_metadata.json
  Tests/conf.json
Labels: docs-approved

#35744 exclude TPB
  Tests/conf.json
Labels: docs-approved

#34697 [Jamf Protect Event Collector] Computer Events
  Packs/JamfProtect/Integrations/JamfProtectEventCollector/JamfProtectEventCollector.py
  Packs/JamfProtect/Integrations/JamfProtectEventCollector/JamfProtectEventCollector.yml
  Packs/JamfProtect/Integrations/JamfProtectEventCollector/JamfProtectEventCollector_description.md
  Packs/JamfProtect/Integrations/JamfProtectEventCollector/JamfProtectEventCollector_image.png
  Packs/JamfProtect/Integrations/JamfProtectEventCollector/JamfProtectEventCollector_test.py
  Packs/JamfProtect/Integrations/JamfProtectEventCollector/README.md
  Packs/JamfProtect/Integrations/JamfProtectEventCollector/test_data/raw_computers.json
  Packs/JamfProtect/ModelingRules/JamfProtect/JamfProtect.xif
  Packs/JamfProtect/ModelingRules/JamfProtect/JamfProtect_schema.json
  Packs/JamfProtect/ReleaseNotes/1_1_0.md
  Packs/JamfProtect/pack_metadata.json
Labels: docs-approved

#35740 Fix an issue in the resolve detection command that is returning a 500 error
  Packs/CrowdStrikeFalcon/Integrations/CrowdStrikeFalcon/CrowdStrikeFalcon.py
  Packs/CrowdStrikeFalcon/Integrations/CrowdStrikeFalcon/CrowdStrikeFalcon_test.py
  Packs/CrowdStrikeFalcon/ReleaseNotes/2_0_9.md
  Packs/CrowdStrikeFalcon/pack_metadata.json
Labels: docs-approved

#35480 [FindEmailCampaign][FindDuplicateEmailIncidents] Remove runonce=true
  Packs/Campaign/.secrets-ignore
  Packs/Campaign/ReleaseNotes/3_4_7.md
  Packs/Campaign/Scripts/FindEmailCampaign/FindEmailCampaign.yml
  Packs/Campaign/TestPlaybooks/Detect_and_Manage_Phishing_Campaigns_-_Test.yml
  Packs/Campaign/pack_metadata.json
  Packs/Phishing/.secrets-ignore
  Packs/Phishing/ReleaseNotes/3_6_21.md
  Packs/Phishing/Scripts/FindDuplicateEmailIncidents/FindDuplicateEmailIncidents.yml
  Packs/Phishing/pack_metadata.json
Labels: docs-approved

#35719 rasterize - update docker image
  Packs/rasterize/Integrations/rasterize/rasterize.py
  Packs/rasterize/Integrations/rasterize/rasterize.yml
  Packs/rasterize/ReleaseNotes/2_0_23.md
  Packs/rasterize/pack_metadata.json
Labels: docs-approved

#35622 refactor ContentPackInstaller a little, tests, clearer error
  Packs/CommonScripts/ReleaseNotes/1_15_42.md
  Packs/CommonScripts/Scripts/ContentPackInstaller/ContentPackInstaller.py
  Packs/CommonScripts/Scripts/ContentPackInstaller/ContentPackInstaller.yml
  Packs/CommonScripts/Scripts/ContentPackInstaller/ContentPackInstaller_test.py
  Packs/CommonScripts/pack_metadata.json
Labels: docs-approved, ForceMerge

#35633 Add new script to convert json to html table
  Packs/CommunityCommonScripts/CONTRIBUTORS.json
  Packs/CommunityCommonScripts/ReleaseNotes/1_2_6.md
  Packs/CommunityCommonScripts/Scripts/Json2HtmlTable/Json2HtmlTable.py
  Packs/CommunityCommonScripts/Scripts/Json2HtmlTable/Json2HtmlTable.yml
  Packs/CommunityCommonScripts/Scripts/Json2HtmlTable/Json2HtmlTable_test.py
  Packs/CommunityCommonScripts/Scripts/Json2HtmlTable/README.md
  Packs/CommunityCommonScripts/pack_metadata.json
Labels: Contribution, Contribution Form Filled, Community, Community Support Level, External PR

#35755 Update chromium docker
  Packs/CofenseTriage/Integrations/CofenseTriagev2/CofenseTriagev2.yml
  Packs/CofenseTriage/ReleaseNotes/2_1_29.md
  Packs/CofenseTriage/pack_metadata.json
  Packs/ExpanseV2/ReleaseNotes/1_10_59.md
  Packs/ExpanseV2/Scripts/ExpanseGenerateIssueMapWidgetScript/ExpanseGenerateIssueMapWidgetScript.yml
  Packs/ExpanseV2/pack_metadata.json
Labels: docs-approved

#35608 removed hasDuplicates
  Packs/CommonScripts/ReleaseNotes/1_15_43.md
  Packs/CommonScripts/Scripts/DeleteContext/DeleteContext.js
  Packs/CommonScripts/TestPlaybooks/playbook-Test_Delete_Context.yml
  Packs/CommonScripts/pack_metadata.json
Labels: docs-approved, ForceMerge

#35720 CRTX-111308: DBotGroupXDRIncidents
  Packs/CortexXDR/ReleaseNotes/6_1_59.md
  Packs/CortexXDR/Scripts/DBotGroupXDRIncidents/DBotGroupXDRIncidents.py
  Packs/CortexXDR/Scripts/DBotGroupXDRIncidents/DBotGroupXDRIncidents_test.py
  Packs/CortexXDR/pack_metadata.json
Labels: docs-approved

#35759 Bump ContentTesting Docker Images
  Packs/ContentTesting/ReleaseNotes/2_1_3.md
  Packs/ContentTesting/Scripts/UnitTest/UnitTest.yml
  Packs/ContentTesting/Scripts/UpgradeCheck/UpgradeCheck.yml
  Packs/ContentTesting/pack_metadata.json
Labels: docs-approved

#35741 XSUP-40226-NGINX-Update
  Packs/NGINXWebServer/ParsingRules/NGINXWebServerParsingRules/NGINXWebServerParsingRules.xif
  Packs/NGINXWebServer/README.md
  Packs/NGINXWebServer/ReleaseNotes/1_0_8.md
  Packs/NGINXWebServer/pack_metadata.json
Labels: docs-approved, bypass.url

#35732 ParseEmailFilesV2: Update docker image
  Packs/CommonScripts/ReleaseNotes/1_15_44.md
  Packs/CommonScripts/Scripts/ParseEmailFilesV2/ParseEmailFilesV2.yml
  Packs/CommonScripts/pack_metadata.json
Labels: docs-approved

#35750 Cs falcon status update
  Packs/CrowdStrikeFalcon/Integrations/CrowdStrikeFalcon/CrowdStrikeFalcon.py
  Packs/CrowdStrikeFalcon/Integrations/CrowdStrikeFalcon/CrowdStrikeFalcon.yml
  Packs/CrowdStrikeFalcon/Integrations/CrowdStrikeFalcon/CrowdStrikeFalcon_test.py
  Packs/CrowdStrikeFalcon/Integrations/CrowdStrikeFalcon/test_data/online_states_response.json
  Packs/CrowdStrikeFalcon/Integrations/CrowdStrikeFalcon/test_data/test_data2.json
  Packs/CrowdStrikeFalcon/ReleaseNotes/2_0_10.md
  Packs/CrowdStrikeFalcon/pack_metadata.json
Labels: docs-approved

#35650 [Marketplace Contribution] - EXPANDR - 9174 - Azure NSG Remediation Playbook Fix
  Packs/Azure-Enrichment-Remediation/Playbooks/Azure_-_Network_Security_Group_Remediation.yml
  Packs/Azure-Enrichment-Remediation/ReleaseNotes/1_1_19.md
  Packs/Azure-Enrichment-Remediation/pack_metadata.json
Labels: Contribution, docs-approved, Contribution Form Filled, Community, Xsoar Support Level, External PR, Security Review

#35762 added versions
  Packs/CommonScripts/TestPlaybooks/playbook-Test_Delete_Context.yml
Labels: docs-approved

#35711 Add support for zoom gov Oauth
  Packs/ApiModules/ReleaseNotes/2_2_28.md
  Packs/ApiModules/Scripts/ZoomApiModule/ZoomApiModule.py
  Packs/ApiModules/Scripts/ZoomApiModule/ZoomApiModule.yml
  Packs/ApiModules/pack_metadata.json
  Packs/Zoom/ReleaseNotes/1_6_12.md
  Packs/Zoom/pack_metadata.json
Labels: docs-approved, release-notes-only

#35735 Fix ews-release-quarntinemessage release_to_all arg
  Packs/MicrosoftExchangeOnline/Integrations/EwsExtensionEXOPowershellV3/EwsExtensionEXOPowershellV3.ps1
  Packs/MicrosoftExchangeOnline/ReleaseNotes/1_5_1.md
  Packs/MicrosoftExchangeOnline/pack_metadata.json
Labels: docs-approved

#35166 XSUP-38612/TAXII2Feed
  Packs/FeedTAXII/Integrations/FeedTAXII2/FeedTAXII2.py
  Packs/FeedTAXII/Integrations/FeedTAXII2/FeedTAXII2.yml
  Packs/FeedTAXII/Integrations/FeedTAXII2/FeedTAXII2_test.py
  Packs/FeedTAXII/ReleaseNotes/1_2_15.md
  Packs/FeedTAXII/pack_metadata.json
Labels: docs-approved

#34318 [Partner Contribution] Jizo NDR Pack V2
  Packs/Jizo_M/.pack-ignore
  Packs/Jizo_M/.secrets-ignore
  Packs/Jizo_M/Author_image.png
  Packs/Jizo_M/Classifiers/classifier-Jizo_M_Incoming_Mapper.json
  Packs/Jizo_M/IncidentTypes/incidenttype-Jizo_Alert.json
  Packs/Jizo_M/Integrations/JizoM/JizoM.py
  Packs/Jizo_M/Integrations/JizoM/JizoM.yml
  Packs/Jizo_M/Integrations/JizoM/JizoM_description.md
  Packs/Jizo_M/Integrations/JizoM/JizoM_image.png
  Packs/Jizo_M/Integrations/JizoM/JizoM_test.py
  Packs/Jizo_M/Integrations/JizoM/README.md
  Packs/Jizo_M/Integrations/JizoM/command_example.txt
  Packs/Jizo_M/Integrations/JizoM/test_data/connect.json
  Packs/Jizo_M/Integrations/JizoM/test_data/fetch_incidents.json
  Packs/Jizo_M/Integrations/JizoM/test_data/peers.json
  Packs/Jizo_M/Integrations/JizoM/test_data/protocols.json
  Packs/Jizo_M/Integrations/JizoM/test_data/query_records.json
  Packs/Jizo_M/README.md
  Packs/Jizo_M/TestPlaybooks/playbook-JizoM.yml
  Packs/Jizo_M/pack_metadata.json
Labels: Contribution, docs-approved, Partner, post-demo, Contribution Form Filled, Partner Support Level, External PR, Security Review, Partner-Approved

#35604 Add Purge Branch Protection Rules Job
  .github/github_workflow_scripts/github_workflow_scripts_tests/test_files/test_delete_protection_rule_response.json
  .github/github_workflow_scripts/github_workflow_scripts_tests/test_files/test_get_repo_branch_protection_rules_data.json
  .github/github_workflow_scripts/purge_branch_protection_rules.py
  .github/github_workflow_scripts/purge_branch_protection_rules_test.py
  .github/github_workflow_scripts/utils.py
  .github/workflows/purge_branch_protection_rules.yml
Labels: docs-approved, github_actions

#35696 [Cortex XDR - IR] Fix incidents not pulled
  Packs/CortexXDR/Integrations/CortexXDRIR/CortexXDRIR.py
  Packs/CortexXDR/Integrations/CortexXDRIR/CortexXDRIR_test.py
  Packs/CortexXDR/Integrations/CortexXDRIR/test_data/get_incidents_list_dedup.json
  Packs/CortexXDR/ReleaseNotes/6_1_60.md
  Packs/CortexXDR/pack_metadata.json
Labels: docs-approved

#35722 Team Cymru - Release 2.0.0
  Packs/TeamCymru/.pack-ignore
  Packs/TeamCymru/.secrets-ignore
  Packs/TeamCymru/Integrations/TeamCymruScout/README.md
  Packs/TeamCymru/Integrations/TeamCymruScout/TeamCymruScout.py
  Packs/TeamCymru/Integrations/TeamCymruScout/TeamCymruScout.yml
  Packs/TeamCymru/Integrations/TeamCymruScout/TeamCymruScout_description.md
  Packs/TeamCymru/Integrations/TeamCymruScout/TeamCymruScout_image.png
  Packs/TeamCymru/Integrations/TeamCymruScout/TeamCymruScout_test.py
  Packs/TeamCymru/Integrations/TeamCymruScout/command_examples
  Packs/TeamCymru/Integrations/TeamCymruScout/test_data/ip_hr.md
  Packs/TeamCymru/Integrations/TeamCymruScout/test_data/ip_indicator.json
  Packs/TeamCymru/Integrations/TeamCymruScout/test_data/ip_output.json
  Packs/TeamCymru/Integrations/TeamCymruScout/test_data/ip_raw_response.json
  Packs/TeamCymru/Integrations/TeamCymruScout/test_data/ip_relationships.json
  Packs/TeamCymru/Integrations/TeamCymruScout/test_data/ip_response.json
  Packs/TeamCymru/Integrations/TeamCymruScout/test_data/scout_api_usage_hr.md
  Packs/TeamCymru/Integrations/TeamCymruScout/test_data/scout_api_usage_output.json
  Packs/TeamCymru/Integrations/TeamCymruScout/test_data/scout_api_usage_response.json
  Packs/TeamCymru/Integrations/TeamCymruScout/test_data/scout_indicator_search_entry_context.json
  Packs/TeamCymru/Integrations/TeamCymruScout/test_data/scout_indicator_search_hr.md
  Packs/TeamCymru/Integrations/TeamCymruScout/test_data/scout_indicator_search_output.json
  Packs/TeamCymru/Integrations/TeamCymruScout/test_data/scout_indicator_search_response.json
  Packs/TeamCymru/Integrations/TeamCymruScout/test_data/scout_ip_list_hr.md
  Packs/TeamCymru/Integrations/TeamCymruScout/test_data/scout_ip_list_output.json
  Packs/TeamCymru/Integrations/TeamCymruScout/test_data/scout_ip_list_response.json
  Packs/TeamCymru/README.md
  Packs/TeamCymru/ReleaseNotes/2_0_0.md
  Packs/TeamCymru/pack_metadata.json
Labels: Contribution, docs-approved, Partner, Contribution Form Filled, Partner Support Level, External PR, Partner-Approved

#35752 XSUP-39406-O365-Update
  Packs/Office365/ModelingRules/Office365/Office365.xif
  Packs/Office365/README.md
  Packs/Office365/ReleaseNotes/1_0_3.md
  Packs/Office365/doc_files/Office_365_Collector_Settings.png
  Packs/Office365/pack_metadata.json
Labels: docs-approved, bypass.url

#35766 Update dockers
  Packs/DeveloperTools/ReleaseNotes/1_3_20.md
  Packs/DeveloperTools/Scripts/Hey/Hey.yml
  Packs/DeveloperTools/pack_metadata.json
  Packs/VaronisDataSecurityPlatform/Integrations/VaronisDataSecurityPlatform/VaronisDataSecurityPlatform.yml
  Packs/VaronisDataSecurityPlatform/ReleaseNotes/1_0_3.md
  Packs/VaronisDataSecurityPlatform/pack_metadata.json
  Packs/cyberark_AIM/Integrations/CyberArkAIM_v2/CyberArkAIM_v2.yml
  Packs/cyberark_AIM/ReleaseNotes/1_0_19.json
  Packs/cyberark_AIM/ReleaseNotes/1_0_19.md
  Packs/cyberark_AIM/pack_metadata.json
Labels: docs-approved

#35515 Core IR: core-retrieve-file-details bug fix
  Packs/ApiModules/Scripts/CoreIRApiModule/CoreIRApiModule.py
  Packs/ApiModules/Scripts/CoreIRApiModule/CoreIRApiModule_test.py
  Packs/Core/ReleaseNotes/3_0_52.md
  Packs/Core/pack_metadata.json
  Packs/CortexXDR/ReleaseNotes/6_1_61.md
  Packs/CortexXDR/pack_metadata.json
  Packs/ctf01/ReleaseNotes/1_0_24.md
  Packs/ctf01/pack_metadata.json
  Tests/demistomock/demistomock.py
Labels: docs-approved

#35783 [Office365AndAzureAuditLog] Add missing image
  Packs/Office365AndAzureAuditLog/doc_files/credentials_example.png
Labels: docs-approved

#35781 The hive severity fix
  Packs/TheHiveProject/Integrations/TheHiveProject/TheHiveProject.py
  Packs/TheHiveProject/Integrations/TheHiveProject/TheHiveProject.yml
  Packs/TheHiveProject/ReleaseNotes/1_1_21.md
  Packs/TheHiveProject/pack_metadata.json
Labels: docs-approved

#35774 [native-image] Ignore Json2HtmlTable script
  Tests/docker_native_image_config.json
Labels: docs-approved

#35787 [isIntegrationAvailable] Fixed an issue with raw-response
  Packs/CommonScripts/ReleaseNotes/1_15_45.md
  Packs/CommonScripts/Scripts/IsIntegrationAvailable/IsIntegrationAvailable.js
  Packs/CommonScripts/pack_metadata.json
Labels: docs-approved

#34070 YR/Sailpoint-IdentityNow-Collector/CIAC-6503
  Packs/SailPointIdentityNow/Integrations/SailPointIdentityNowEventCollector/README.md
  Packs/SailPointIdentityNow/Integrations/SailPointIdentityNowEventCollector/SailPointIdentityNowEventCollector.py
  Packs/SailPointIdentityNow/Integrations/SailPointIdentityNowEventCollector/SailPointIdentityNowEventCollector.yml
  Packs/SailPointIdentityNow/Integrations/SailPointIdentityNowEventCollector/SailPointIdentityNowEventCollector_description.md
  Packs/SailPointIdentityNow/Integrations/SailPointIdentityNowEventCollector/SailPointIdentityNowEventCollector_image.png
  Packs/SailPointIdentityNow/Integrations/SailPointIdentityNowEventCollector/SailPointIdentityNowEventCollector_test.py
  Packs/SailPointIdentityNow/ModelingRules/SailPointIdentityNow/SailPointIdentityNow.xif
  Packs/SailPointIdentityNow/ModelingRules/SailPointIdentityNow/SailPointIdentityNow.yml
  Packs/SailPointIdentityNow/ModelingRules/SailPointIdentityNow/SailPointIdentityNow_schema.json
  Packs/SailPointIdentityNow/ReleaseNotes/1_0_8.md
  Packs/SailPointIdentityNow/pack_metadata.json
Labels: docs-approved

#35801 Disable DockerHardeningCheck UT
  Packs/CommonScripts/ReleaseNotes/1_15_46.md
  Packs/CommonScripts/Scripts/DockerHardeningCheck/DockerHardeningCheck.py
  Packs/CommonScripts/Scripts/DockerHardeningCheck/DockerHardeningCheck.yml
  Packs/CommonScripts/Scripts/DockerHardeningCheck/DockerHardeningCheck_test.py
  Packs/CommonScripts/pack_metadata.json
Labels: docs-approved

#35768 Remove types-pkg-resources
  poetry.lock
  pyproject.toml
Labels: docs-approved, ForceMerge

#35790 JiraV3 Mirror Out
  Packs/Jira/Integrations/JiraV3/JiraV3.py
  Packs/Jira/ReleaseNotes/3_2_3.md
  Packs/Jira/pack_metadata.json
Labels: docs-approved

#35798 [PAN-OS] fix incidents not classified
  Packs/PAN-OS/Integrations/Panorama/Panorama.py
  Packs/PAN-OS/Integrations/Panorama/Panorama.yml
  Packs/PAN-OS/Integrations/Panorama/Panorama_test.py
  Packs/PAN-OS/Integrations/Panorama/test_data/fetch_incidents_input.py
  Packs/PAN-OS/ReleaseNotes/2_1_33.md
  Packs/PAN-OS/pack_metadata.json
Labels: docs-approved

#35788 Cyble enhancements
  Packs/CybleEventsV2/Integrations/CybleEventsV2/CybleEventsV2.py
  Packs/CybleEventsV2/Integrations/CybleEventsV2/CybleEventsV2.yml
  Packs/CybleEventsV2/Integrations/CybleEventsV2/CybleEventsV2_test.py
  Packs/CybleEventsV2/Integrations/CybleEventsV2/README.md
  Packs/CybleEventsV2/Integrations/CybleEventsV2/test_data/dummy_fetch_iocs.json
  Packs/CybleEventsV2/ReleaseNotes/1_0_4.md
  Packs/CybleEventsV2/pack_metadata.json
Labels: Contribution, Partner, Contribution Form Filled, Partner Support Level, External PR, Partner-Approved

#35796 Fix issue in ParseEmails script
  Packs/CommonScripts/ReleaseNotes/1_15_47.md
  Packs/CommonScripts/Scripts/ParseEmailFilesV2/ParseEmailFilesV2.yml
  Packs/CommonScripts/pack_metadata.json
  Tests/docker_native_image_config.json
Labels: docs-approved

#35811 [Cortex XDR - IR] Fix multiple incidents pulled
  Packs/CortexXDR/Integrations/CortexXDRIR/CortexXDRIR.py
  Packs/CortexXDR/Integrations/CortexXDRIR/CortexXDRIR_test.py
  Packs/CortexXDR/ReleaseNotes/6_1_62.md
  Packs/CortexXDR/pack_metadata.json
Labels: docs-approved

#35795 fixed the searchAfter in the searchIndicators function
  Tests/demistomock/demistomock.py
Labels: docs-approved

#35793 [AWS E+R] EXPANDR-10800
  Packs/AWS-Enrichment-Remediation/ReleaseNotes/1_1_20.md
  Packs/AWS-Enrichment-Remediation/Scripts/AWSRecreateSG/AWSRecreateSG.py
  Packs/AWS-Enrichment-Remediation/Scripts/AWSRecreateSG/AWSRecreateSG.yml
  Packs/AWS-Enrichment-Remediation/pack_metadata.json
Labels: Contribution, docs-approved, Contribution Form Filled, Community, Xsoar Support Level, External PR

#35643 Remove `mypy` Global Ignores
  Packs/AzureDataExplorer/Integrations/AzureDataExplorer/AzureDataExplorer.py
  Packs/AzureDataExplorer/ReleaseNotes/1_3_2.md
  Packs/AzureDataExplorer/pack_metadata.json
  Packs/AzureDevOps/Integrations/AzureDevOps/AzureDevOps.py
  Packs/AzureDevOps/ReleaseNotes/1_4_2.md
  Packs/AzureDevOps/pack_metadata.json
  Packs/Base/ReleaseNotes/1_34_31.md
  Packs/Base/ReleaseNotes/1_34_34.md
  Packs/Base/Scripts/FindSimilarIncidentsByText/FindSimilarIncidentsByText.py
  Packs/Base/pack_metadata.json
  Packs/BmcITSM/Integrations/BmcITSM/BmcITSM.py
  Packs/BmcITSM/ReleaseNotes/1_0_24.md
  Packs/BmcITSM/pack_metadata.json
  Packs/CheckPointDome9/Integrations/CheckPointDome9/CheckPointDome9.py
  Packs/CheckPointDome9/Integrations/CheckPointDome9/CheckPointDome9.yml
  Packs/CheckPointDome9/Integrations/CheckPointDome9/CheckPointDome9_test.py
  Packs/CheckPointDome9/ReleaseNotes/1_0_17.md
  Packs/CheckPointDome9/pack_metadata.json
  Packs/CommonScripts/ReleaseNotes/1_15_48.md
  Packs/CommonScripts/Scripts/FindSimilarIncidentsV2/FindSimilarIncidentsV2.py
  Packs/CommonScripts/pack_metadata.json
  Packs/CyrenInboxSecurity/ReleaseNotes/1_1_13.md
  Packs/CyrenInboxSecurity/Scripts/CyrenFindSimilarIncidents/CyrenFindSimilarIncidents.py
  Packs/CyrenInboxSecurity/Scripts/CyrenShowThreatIndicators/CyrenShowThreatIndicators.py
  Packs/CyrenInboxSecurity/pack_metadata.json
  Packs/ForescoutEyeInspect/Integrations/ForescoutEyeInspect/ForescoutEyeInspect.py
  Packs/ForescoutEyeInspect/Integrations/ForescoutEyeInspect/ForescoutEyeInspect.yml
  Packs/ForescoutEyeInspect/ReleaseNotes/1_0_22.md
  Packs/ForescoutEyeInspect/pack_metadata.json
  Packs/FortiSIEM/Integrations/FortiSIEMV2/FortiSIEMV2.py
  Packs/FortiSIEM/Integrations/FortiSIEMV2/FortiSIEMV2.yml
  Packs/FortiSIEM/ReleaseNotes/2_0_36.md
  Packs/FortiSIEM/pack_metadata.json
  Packs/GCP-IAM/Integrations/GCPIAM/GCPIAM.py
  Packs/GCP-IAM/Integrations/GCPIAM/GCPIAM.yml
  Packs/GCP-IAM/ReleaseNotes/1_0_26.md
  Packs/GCP-IAM/pack_metadata.json
  Packs/IronDefense/Integrations/IronDefense/IronDefense_test.py
  Packs/MISP/Integrations/MISPV3/MISPV3.py
  Packs/MISP/Integrations/MISPV3/MISPV3_test.py
  Packs/MISP/Integrations/MISP_V2/MISP_V2.py
  Packs/MISP/ReleaseNotes/2_1_44.md
  Packs/MISP/pack_metadata.json
  Packs/Netskope/Integrations/NetskopeAPIv1/NetskopeAPIv1.py
  Packs/Netskope/Integrations/NetskopeAPIv1/NetskopeAPIv1.yml
  Packs/Netskope/ReleaseNotes/3_3_11.md
  Packs/Netskope/pack_metadata.json
  Packs/Tenable_io/Integrations/Tenable_io/Tenable_io_test.py
Labels: docs-approved, ForceMerge

#35653 added the incident endpoint to netskope collector
  Packs/Netskope/Integrations/NetskopeEventCollector/NetskopeEventCollector.py
  Packs/Netskope/Integrations/NetskopeEventCollector/NetskopeEventCollector.yml
  Packs/Netskope/Integrations/NetskopeEventCollector/NetskopeEventCollector_test.py
  Packs/Netskope/Integrations/NetskopeEventCollector/test_data/multiple_events_raw.json
  Packs/Netskope/ReleaseNotes/3_3_12.md
  Packs/Netskope/pack_metadata.json
Labels: docs-approved

#35481 [FileToBase64List] Remove "runeonce: true"
  Packs/CommonScripts/ReleaseNotes/1_15_49.md
  Packs/CommonScripts/Scripts/FileToBase64List/FileToBase64List.py
  Packs/CommonScripts/Scripts/FileToBase64List/FileToBase64List.yml
  Packs/CommonScripts/Scripts/FileToBase64List/file_to_base64_list_test.py
  Packs/CommonScripts/pack_metadata.json
Labels: docs-approved

#35754 TEZ-5540:
  Packs/Gurucul/CONTRIBUTORS.json
  Packs/Gurucul/Integrations/GuruculGRA/GuruculGRA.py
  Packs/Gurucul/Integrations/GuruculGRA/GuruculGRA.yml
  Packs/Gurucul/Integrations/GuruculGRA/README.md
  Packs/Gurucul/Integrations/GuruculGRA/command_examples
  Packs/Gurucul/ReleaseNotes/2_0_5.md
  Packs/Gurucul/Scripts/GRAAnomaliesDisplay/GRAAnomaliesDisplay.py
  Packs/Gurucul/Scripts/GRAAnomaliesDisplay/GRAAnomaliesDisplay.yml
  Packs/Gurucul/Scripts/graanalyticalfeaturedisplay/graanalyticalfeaturedisplay.py
  Packs/Gurucul/Scripts/graanalyticalfeaturedisplay/graanalyticalfeaturedisplay.yml
  Packs/Gurucul/Scripts/graanalyticalfeaturedisplay/graanalyticalfeaturedisplay_test.py
  Packs/Gurucul/Scripts/graupdatecasestatus/graupdatecasestatus.py
  Packs/Gurucul/Scripts/graupdatecasestatus/graupdatecasestatus.yml
  Packs/Gurucul/Scripts/graupdatecasestatus/graupdatecasestatus_test.py
  Packs/Gurucul/pack_metadata.json
Labels: Contribution, docs-approved, Partner, Contribution Form Filled, Partner Support Level, External PR, Partner-Approved

#35809 Fix instructions and a typo
  Packs/HealthCheck/Scripts/HealthCheckFields/HealthCheckFields.py
Labels: Contribution, docs-approved, Contribution Form Filled, Community, Community Support Level, External PR

#35805 [Native Image] py3-native:8.7
  Tests/docker_native_image_config.json
Labels: docs-approved

#35825 [Microsoft Sentinel] Update the README.md
  Packs/AzureSentinel/Integrations/AzureSentinel/README.md
Labels: docs-approved

#35824 SplunkPy: better error handling in `splunk-search`
  Packs/SplunkPy/Integrations/SplunkPy/SplunkPy.py
  Packs/SplunkPy/Integrations/SplunkPy/SplunkPy.yml
  Packs/SplunkPy/Integrations/SplunkPy/SplunkPy_test.py
  Packs/SplunkPy/ReleaseNotes/3_1_37.json
  Packs/SplunkPy/ReleaseNotes/3_1_37.md
  Packs/SplunkPy/pack_metadata.json
Labels: docs-approved

#35838 Add AUD mode to ruff
  .pre-commit-config_template.yaml
Labels: docs-approved

#35403 demisto/office-utils:2.0.0.103232 | 0-100 | PR batch #1/1
  Packs/CommonScripts/ReleaseNotes/1_15_50.md
  Packs/CommonScripts/Scripts/ConvertFile/ConvertFile.yml
  Packs/CommonScripts/Scripts/ExtractHyperlinksFromOfficeFiles/ExtractHyperlinksFromOfficeFiles.yml
  Packs/CommonScripts/Scripts/ExtractIndicatorsFromWordFile/ExtractIndicatorsFromWordFile.py
  Packs/CommonScripts/Scripts/ExtractIndicatorsFromWordFile/ExtractIndicatorsFromWordFile.yml
  Packs/CommonScripts/Scripts/ParseWordDoc/ParseWordDoc.yml
  Packs/CommonScripts/pack_metadata.json
Labels: docs-approved, auto-update-docker

#35765 Ciac 9334 smime messaging enhancement
  Packs/SMIME_Messaging/Integrations/SMIME_Messaging/README.md
  Packs/SMIME_Messaging/Integrations/SMIME_Messaging/SMIME_Messaging.py
  Packs/SMIME_Messaging/Integrations/SMIME_Messaging/SMIME_Messaging.yml
  Packs/SMIME_Messaging/Integrations/SMIME_Messaging/SMIME_Messaging_description.md
  Packs/SMIME_Messaging/Integrations/SMIME_Messaging/SMIME_Messaging_test.py
  Packs/SMIME_Messaging/Integrations/SMIME_Messaging/test_data/attachment1.txt
  Packs/SMIME_Messaging/Integrations/SMIME_Messaging/test_data/attachment2.txt
  Packs/SMIME_Messaging/Integrations/SMIME_Messaging/test_data/encrypted-binary-format.p7m
  Packs/SMIME_Messaging/Integrations/SMIME_Messaging/test_data/recipient2.pem
  Packs/SMIME_Messaging/Integrations/SMIME_Messaging/test_data/recipient2_key.pem
  Packs/SMIME_Messaging/Integrations/SMIME_Messaging/test_data/signed-binary-format.p7m
  Packs/SMIME_Messaging/ReleaseNotes/2_0_0.md
  Packs/SMIME_Messaging/TestPlaybooks/SMIME_Messaging-Test.yml
  Packs/SMIME_Messaging/pack_metadata.json
  Tests/conf.json
Labels: docs-approved

#35847 Add Filter example in Readme
  Packs/FeedCrowdstrikeFalconIntel/Integrations/CrowdStrikeIndicatorFeed/README.md
Labels: docs-approved

#35827 XSUP-39406-o365-parsing-update
  Packs/Office365/ParsingRules/Office365/Office365.xif
  Packs/Office365/README.md
  Packs/Office365/ReleaseNotes/1_0_4.md
  Packs/Office365/pack_metadata.json
Labels: docs-approved, bypass.url

#35736 fix expire_password_command
  Packs/Okta/Integrations/Okta_v2/Okta_v2.py
  Packs/Okta/Integrations/Okta_v2/Okta_v2_test.py
  Packs/Okta/ReleaseNotes/3_3_1.md
  Packs/Okta/pack_metadata.json
Labels: docs-approved

#35848 CyberArkEPV Parsing Update
  Packs/CyberArkEPV/ParsingRules/CyberArkEPV/CyberArkEPV.xif
  Packs/CyberArkEPV/ReleaseNotes/1_0_3.md
  Packs/CyberArkEPV/pack_metadata.json
Labels: docs-approved, bypass.url

#35852 Exterro FTK - update docker
  Packs/Exterro/Integrations/Exterro/Exterro.yml
  Packs/Exterro/ReleaseNotes/1_0_12.md
  Packs/Exterro/pack_metadata.json
Labels: docs-approved

#35353 Remove suddenDeath option from incremental feeds
  Packs/FeedCrowdstrikeFalconIntel/Integrations/FeedCrowdstrikeFalconIntel/FeedCrowdstrikeFalconIntel.yml
  Packs/FeedCrowdstrikeFalconIntel/ReleaseNotes/2_1_17.md
  Packs/FeedCrowdstrikeFalconIntel/pack_metadata.json
  Packs/FeedCyCognito/.pack-ignore
  Packs/FeedCyCognito/Integrations/FeedCyCognito/FeedCyCognito.yml
  Packs/FeedCyCognito/ReleaseNotes/1_0_22.md
  Packs/FeedCyCognito/pack_metadata.json
  Packs/FeedDHS/.pack-ignore
  Packs/FeedDHS/Integrations/DHSFeedV2/DHSFeedV2.yml
  Packs/FeedDHS/Integrations/DHS_Feed/DHS_Feed.yml
  Packs/FeedDHS/ReleaseNotes/2_0_40.md
  Packs/FeedDHS/pack_metadata.json
  Packs/FeedElasticsearch/.pack-ignore
  Packs/FeedElasticsearch/Integrations/FeedElasticsearch/FeedElasticsearch.yml
  Packs/FeedElasticsearch/ReleaseNotes/1_1_6.md
  Packs/FeedElasticsearch/pack_metadata.json
  Packs/FeedFeedly/.pack-ignore
  Packs/FeedFeedly/Integrations/FeedFeedly/FeedFeedly.yml
  Packs/FeedFeedly/ReleaseNotes/1_0_4.md
  Packs/FeedFeedly/pack_metadata.json
  Packs/FeedGitHub/Integrations/FeedGitHub/FeedGitHub.yml
  Packs/FeedGitHub/ReleaseNotes/1_0_7.md
  Packs/FeedGitHub/pack_metadata.json
  Packs/FeedMISP/.pack-ignore
  Packs/FeedMISP/Integrations/FeedMISP/FeedMISP.yml
  Packs/FeedMISP/ReleaseNotes/1_0_35.md
  Packs/FeedMISP/pack_metadata.json
  Packs/FeedMandiant/Integrations/FeedMandiant/FeedMandiant.yml
  Packs/FeedMandiant/ReleaseNotes/1_0_15.md
  Packs/FeedMandiant/pack_metadata.json
  Packs/FeedNVDv2/.pack-ignore
  Packs/FeedNVDv2/Integrations/FeedNVDv2/FeedNVDv2.yml
  Packs/FeedNVDv2/ReleaseNotes/1_0_3.md
  Packs/FeedNVDv2/pack_metadata.json
  Packs/FeedORKL/.pack-ignore
  Packs/FeedORKL/Integrations/FeedORKL/FeedORKL.yml
  Packs/FeedORKL/ReleaseNotes/1_0_1.md
  Packs/FeedORKL/pack_metadata.json
  Packs/FeedTAXII/.pack-ignore
  Packs/FeedTAXII/Integrations/FeedTAXII/FeedTAXII.yml
  Packs/FeedTAXII/ReleaseNotes/1_2_16.md
  Packs/FeedTAXII/pack_metadata.json
  Packs/FeedThreatConnect/.pack-ignore
  Packs/FeedThreatConnect/Integrations/FeedThreatConnect/FeedThreatConnect.yml
  Packs/FeedThreatConnect/ReleaseNotes/2_1_23.md
  Packs/FeedThreatConnect/pack_metadata.json
  Packs/NationalVulnerabilityDatabaseFeed/.pack-ignore
  Packs/NationalVulnerabilityDatabaseFeed/Integrations/NationalVulnerabilityDatabaseFeed/NationalVulnerabilityDatabaseFeed.yml
  Packs/NationalVulnerabilityDatabaseFeed/ReleaseNotes/1_0_6.md
  Packs/NationalVulnerabilityDatabaseFeed/pack_metadata.json
Labels: docs-approved, ForceMerge

#35837 Ignore FireEye from docker native 3.10
  Packs/FireEyeNX/Integrations/FireEyeNX/FireEyeNX_test.py
  Tests/docker_native_image_config.json
Labels: docs-approved

#34492 Druva event collector
  Packs/Druva/Integrations/DruvaEventCollector/DruvaEventCollector.py
  Packs/Druva/Integrations/DruvaEventCollector/DruvaEventCollector.yml
  Packs/Druva/Integrations/DruvaEventCollector/DruvaEventCollector_description.md
  Packs/Druva/Integrations/DruvaEventCollector/DruvaEventCollector_image.png
  Packs/Druva/Integrations/DruvaEventCollector/DruvaEventCollector_test.py
  Packs/Druva/Integrations/DruvaEventCollector/README.md
  Packs/Druva/ModelingRules/Druva/Druva.xif
  Packs/Druva/ModelingRules/Druva/Druva.yml
  Packs/Druva/ModelingRules/Druva/Druva_schema.json
  Packs/Druva/ReleaseNotes/1_2_0.md
  Packs/Druva/pack_metadata.json
Labels: docs-approved

#35782 Microsoft Advanced Threat Analytics -update docker
  Packs/MicrosoftAdvancedThreatAnalytics/Integrations/MicrosoftAdvancedThreatAnalytics/MicrosoftAdvancedThreatAnalytics.yml
  Packs/MicrosoftAdvancedThreatAnalytics/ReleaseNotes/1_0_17.md
  Packs/MicrosoftAdvancedThreatAnalytics/pack_metadata.json
  Tests/conf.json
Labels: docs-approved

#35590 bug - pp threat response AttributeError
  Packs/ProofpointThreatResponse/Integrations/ProofpointThreatResponse/ProofpointThreatResponse.py
  Packs/ProofpointThreatResponse/Integrations/ProofpointThreatResponse/ProofpointThreatResponse.yml
  Packs/ProofpointThreatResponse/Integrations/ProofpointThreatResponse/ProofpointThreatResponse_test.py
  Packs/ProofpointThreatResponse/Integrations/ProofpointThreatResponse/test_data/incident_str_messageDeliveryTime.json
  Packs/ProofpointThreatResponse/ReleaseNotes/2_0_17.md
  Packs/ProofpointThreatResponse/pack_metadata.json
Labels: docs-approved

#35853 Xsup 40172 parse chinese
  Packs/CommonScripts/ReleaseNotes/1_15_51.md
  Packs/CommonScripts/Scripts/ParseEmailFilesV2/ParseEmailFilesV2.yml
  Packs/CommonScripts/pack_metadata.json
Labels: docs-approved

#35846 [ASM] Update Enrichment Playbooks to use asmserviceownerunrankedraw
  Packs/CortexAttackSurfaceManagement/Playbooks/Cortex_ASM_-_Azure_Enrichment.yml
  Packs/CortexAttackSurfaceManagement/Playbooks/Cortex_ASM_-_Enrichment.yml
  Packs/CortexAttackSurfaceManagement/Playbooks/Cortex_ASM_-_Qualys_Enrichment.yml
  Packs/CortexAttackSurfaceManagement/Playbooks/Cortex_ASM_-_Rapid7_Enrichment.yml
  Packs/CortexAttackSurfaceManagement/Playbooks/Cortex_ASM_-_ServiceNow_CMDB_Enrichment.yml
  Packs/CortexAttackSurfaceManagement/Playbooks/Cortex_ASM_-_Service_Ownership.yml
  Packs/CortexAttackSurfaceManagement/Playbooks/Cortex_ASM_-_Splunk_Enrichment.yml
  Packs/CortexAttackSurfaceManagement/Playbooks/Cortex_ASM_-_Tenable.io_Enrichment.yml
  Packs/CortexAttackSurfaceManagement/ReleaseNotes/1_7_46.md
  Packs/CortexAttackSurfaceManagement/pack_metadata.json
Labels: Contribution, docs-approved, Contribution Form Filled, Community, Xsoar Support Level, External PR, Security Review

#35857 Release native image for XSOAR-NG 8.7
  Tests/docker_native_image_config.json
Labels: docs-approved

#35879 Update README.md
  Packs/DeveloperTools/Integrations/CreateIncidents/README.md
Labels: docs-approved

#35877 update conf
  Tests/conf.json
Labels: docs-approved

#35878 Druva Collector - add missing field inSyncDataSourceName to the Schema
  Packs/Druva/ModelingRules/Druva/Druva_schema.json
  Packs/Druva/ReleaseNotes/1_2_1.md
  Packs/Druva/pack_metadata.json
Labels: docs-approved

#35881 Update contributors list (Q3-2 2024)
  .github/content_roles.json
Labels: docs-approved

#35438 SNOW request specific fields in test module
  Packs/ServiceNow/Integrations/ServiceNowv2/ServiceNowv2.py
  Packs/ServiceNow/ReleaseNotes/2_6_7.md
  Packs/ServiceNow/pack_metadata.json
Labels: docs-approved, release-notes-only

#35639 CRTX-121331 GCP Google Cloud Logging XDM Modeling
  Packs/GoogleCloudLogging/.secrets-ignore
  Packs/GoogleCloudLogging/ModelingRules/GoogleCloudLogging/GoogleCloudLogging.xif
  Packs/GoogleCloudLogging/ModelingRules/GoogleCloudLogging/GoogleCloudLogging.yml
  Packs/GoogleCloudLogging/ModelingRules/GoogleCloudLogging/GoogleCloudLogging_schema.json
  Packs/GoogleCloudLogging/ParsingRules/GoogleCloudLogging/GoogleCloudLogging.xif
  Packs/GoogleCloudLogging/ParsingRules/GoogleCloudLogging/GoogleCloudLogging.yml
  Packs/GoogleCloudLogging/README.md
  Packs/GoogleCloudLogging/ReleaseNotes/1_0_13.md
  Packs/GoogleCloudLogging/pack_metadata.json
Labels: docs-approved, bypass.url

#35504 CDL Pagination
  Packs/CortexDataLake/Integrations/CortexDataLake/CortexDataLake.py
  Packs/CortexDataLake/Integrations/CortexDataLake/CortexDataLake.yml
  Packs/CortexDataLake/Integrations/CortexDataLake/CortexDataLake_test.py
  Packs/CortexDataLake/Integrations/CortexDataLake/README.md
  Packs/CortexDataLake/ReleaseNotes/1_4_12.md
  Packs/CortexDataLake/pack_metadata.json
Labels: docs-approved

#35849 [DBotPredictURLPhishing] Fix mailto URLs fail with rasterize responses.
  Packs/PhishingURL/ReleaseNotes/1_1_19.md
  Packs/PhishingURL/Scripts/DBotPredictURLPhishing/DBotPredictURLPhishing.py
  Packs/PhishingURL/pack_metadata.json
Labels: docs-approved

#35883 raising an error
  Packs/Slack/Integrations/SlackV3/README.md
  Packs/Slack/Integrations/SlackV3/SlackV3.py
  Packs/Slack/Integrations/SlackV3/SlackV3.yml
  Packs/Slack/Integrations/SlackV3/SlackV3_test.py
  Packs/Slack/ReleaseNotes/3_4_18.md
  Packs/Slack/pack_metadata.json
Labels: docs-approved

#35630 Xsup 39289 mirroring fix
  Packs/ApiModules/Scripts/CoreIRApiModule/CoreIRApiModule.py
  Packs/ApiModules/Scripts/CoreIRApiModule/CoreIRApiModule.yml
  Packs/Core/ReleaseNotes/3_0_53.md
  Packs/Core/pack_metadata.json
  Packs/CortexXDR/Integrations/CortexXDRIR/CortexXDRIR.py
  Packs/CortexXDR/Integrations/CortexXDRIR/CortexXDRIR.yml
  Packs/CortexXDR/Integrations/CortexXDRIR/CortexXDRIR_description.md
  Packs/CortexXDR/Integrations/CortexXDRIR/CortexXDRIR_test.py
  Packs/CortexXDR/Integrations/CortexXDRIR/README.md
  Packs/CortexXDR/ReleaseNotes/6_1_63.md
  Packs/CortexXDR/pack_metadata.json
  Packs/ctf01/ReleaseNotes/1_0_25.md
  Packs/ctf01/pack_metadata.json
Labels: docs-approved

#35891 Generic SQL - update docker
  Packs/GenericSQL/Integrations/GenericSQL/GenericSQL.yml
  Packs/GenericSQL/ReleaseNotes/1_3_2.md
  Packs/GenericSQL/pack_metadata.json
Labels: docs-approved

#35579 Domaintools_Iris Release v2.0.4
  Packs/DomainTools_Iris/Playbooks/DomainTools_Iris_Risk_Score/DomainTools_Iris_Risk_Score.yml
  Packs/DomainTools_Iris/Playbooks/DomainTools_Iris_Risk_Score/DomainTools_Iris_Risk_Score_README.md
  Packs/DomainTools_Iris/ReleaseNotes/2_0_4.md
  Packs/DomainTools_Iris/Scripts/AddDomainRiskScoreToContext/AddDomainRiskScoreToContext.yml
  Packs/DomainTools_Iris/Scripts/AssociateIndicatorsToIncident/AssociateIndicatorsToIncident.yml
  Packs/DomainTools_Iris/Scripts/CheckLastEnrichment/CheckLastEnrichment.py
  Packs/DomainTools_Iris/Scripts/CheckLastEnrichment/CheckLastEnrichment.yml
  Packs/DomainTools_Iris/Scripts/CheckLastEnrichment/CheckLastEnrichment_test.py
  Packs/DomainTools_Iris/Scripts/CheckPivotableDomains/CheckPivotableDomains.yml
  Packs/DomainTools_Iris/Scripts/CheckTags/CheckTags.py
  Packs/DomainTools_Iris/Scripts/CheckTags/CheckTags.yml
  Packs/DomainTools_Iris/Scripts/DomainExtractAndEnrich/DomainExtractAndEnrich.py
  Packs/DomainTools_Iris/Scripts/DomainExtractAndEnrich/DomainExtractAndEnrich.yml
  Packs/DomainTools_Iris/Scripts/DomainExtractAndEnrich/DomainExtractAndEnrich_test.py
  Packs/DomainTools_Iris/Scripts/DomainExtractAndInvestigate/DomainExtractAndInvestigate.yml
  Packs/DomainTools_Iris/Scripts/DomainExtractAndInvestigate/DomainExtractAndInvestigate_test.py
  Packs/DomainTools_Iris/Scripts/SetIndicatorTableData/SetIndicatorTableData.py
  Packs/DomainTools_Iris/Scripts/SetIndicatorTableData/SetIndicatorTableData.yml
  Packs/DomainTools_Iris/doc_files/DomainTools_Iris_Risk_Score.png
  Packs/DomainTools_Iris/pack_metadata.json
Labels: Contribution, Partner, Contribution Form Filled, Partner Support Level, External PR, Security Review, Partner-Approved

#35867 change logo
  Packs/SentinelOne/Integrations/SentinelOne-V2/SentinelOne-V2_image.png
  Packs/SentinelOne/ReleaseNotes/3_2_29.md
  Packs/SentinelOne/pack_metadata.json
Labels: docs-approved

#35893 TheHive custom fields fix
  Packs/TheHiveProject/Integrations/TheHiveProject/TheHiveProject.py
  Packs/TheHiveProject/Integrations/TheHiveProject/TheHiveProject.yml
  Packs/TheHiveProject/ReleaseNotes/1_1_22.md
  Packs/TheHiveProject/pack_metadata.json
Labels: docs-approved

#35897 Revert #35696, #35811
  Packs/CortexXDR/Integrations/CortexXDRIR/CortexXDRIR.py
  Packs/CortexXDR/Integrations/CortexXDRIR/CortexXDRIR_test.py
  Packs/CortexXDR/ReleaseNotes/6_1_64.md
  Packs/CortexXDR/pack_metadata.json
Labels: docs-approved

#35851 Microsoft Defender for Cloud (Azure security center) event hub
  Packs/AzureSecurityCenter/.secrets-ignore
  Packs/AzureSecurityCenter/ModelingRules/MicrosoftDefenderForCloudModelingRules/MicrosoftDefenderForCloudModelingRules.xif
  Packs/AzureSecurityCenter/ModelingRules/MicrosoftDefenderForCloudModelingRules/MicrosoftDefenderForCloudModelingRules_schema.json
  Packs/AzureSecurityCenter/ParsingRules/AzureSecurityCenter/AzureSecurityCenter.xif
  Packs/AzureSecurityCenter/ParsingRules/AzureSecurityCenter/AzureSecurityCenter.yml
  Packs/AzureSecurityCenter/README.md
  Packs/AzureSecurityCenter/ReleaseNotes/2_0_30.md
  Packs/AzureSecurityCenter/pack_metadata.json
Labels: docs-approved

#35899 Update AquatoneDiscoverV2 and Axonius dockers
  Packs/Axonius/Integrations/Axonius/Axonius.yml
  Packs/Axonius/ReleaseNotes/1_2_4.md
  Packs/Axonius/pack_metadata.json
  Packs/CommonScripts/ReleaseNotes/1_15_52.md
  Packs/CommonScripts/Scripts/AquatoneDiscoverV2/AquatoneDiscoverV2.yml
  Packs/CommonScripts/pack_metadata.json
Labels: docs-approved

#35845 XSUP_39884_parsing_rules
  Packs/GoogleChrome/ModelingRules/GoogleChrome/GoogleChrome.xif
  Packs/GoogleChrome/ModelingRules/GoogleChrome/GoogleChrome_schema.json
  Packs/GoogleChrome/ParsingRules/GoogleChrome/GoogleChrome.xif
  Packs/GoogleChrome/README.md
  Packs/GoogleChrome/ReleaseNotes/1_0_2.md
  Packs/GoogleChrome/pack_metadata.json
Labels: docs-approved, bypass.url

#35888 Link Service Now test playbook to integration yml
  Packs/ServiceNow/Integrations/ServiceNowv2/ServiceNowv2.yml
  Packs/ServiceNow/TestPlaybooks/ServiceNow_Fetch_Incidents_Test.yml
  Tests/conf.json
Labels: docs-approved

#35903 Fix unsupported relative images
  Packs/IdentityRecordedFuture/Integrations/IdentityRecordedFuture/IdentityRecordedFuture_description.md
  Packs/IdentityRecordedFuture/ReleaseNotes/2_0_1.md
  Packs/IdentityRecordedFuture/pack_metadata.json
  Packs/Microsoft365Defender/Integrations/O365DefenderSafeLinks/O365DefenderSafeLinks_description.md
  Packs/Microsoft365Defender/ReleaseNotes/4_5_31.md
  Packs/Microsoft365Defender/pack_metadata.json
  Packs/Office365AndAzureAuditLog/Integrations/MicrosoftPolicyAndComplianceAuditLog/MicrosoftPolicyAndComplianceAuditLog_description.md
  Packs/Office365AndAzureAuditLog/ReleaseNotes/2_0_2.md
  Packs/Office365AndAzureAuditLog/pack_metadata.json
  Packs/SlashNextPhishingIncidentResponse/README.md
Labels: docs-approved

#35728 Ciac 10634 prisma cloud extend commands
  Packs/PrismaCloud/Integrations/PrismaCloudV2/PrismaCloudV2.py
  Packs/PrismaCloud/Integrations/PrismaCloudV2/PrismaCloudV2.yml
  Packs/PrismaCloud/Integrations/PrismaCloudV2/PrismaCloudV2_test.py
  Packs/PrismaCloud/Integrations/PrismaCloudV2/README.md
  Packs/PrismaCloud/ReleaseNotes/4_3_9.md
  Packs/PrismaCloud/TestPlaybooks/Prisma_Cloud_Test.yml
  Packs/PrismaCloud/pack_metadata.json
Labels: docs-approved

#35869 Add legacy-validate GHA for contributions
  .github/workflows/run-legacy-validate-for-contribution.yml
Labels: docs-approved

#35516 Darktrace ASM updates
  Packs/DarktraceASM/Classifiers/classifier-DarktraceASM_Risk_Incoming_Mapper.json
  Packs/DarktraceASM/IncidentFields/incidentfield-DarktraceASM_ASM_Asset_URL.json
  Packs/DarktraceASM/IncidentFields/incidentfield-DarktraceASM_ASM_RISK_URL.json
  Packs/DarktraceASM/Integrations/DarktraceASMRisk/DarktraceASMRisk.py
  Packs/DarktraceASM/Integrations/DarktraceASMRisk/test_data/formatted_edit_asm_comment.json
  Packs/DarktraceASM/Integrations/DarktraceASMRisk/test_data/formatted_get_asm_risk.json
  Packs/DarktraceASM/Integrations/DarktraceASMRisk/test_data/formatted_post_asm_comment.json
  Packs/DarktraceASM/Layouts/layoutscontainer-DarktraceASM_ASM_Layout.json
  Packs/DarktraceASM/ReleaseNotes/1_0_1.md
  Packs/DarktraceASM/pack_metadata.json
Labels: Contribution, docs-approved, Partner, Contribution Form Filled, Partner Support Level, External PR, Security Review, Partner-Approved

#35826 JiraV3/fetch-attachments/fix
  Packs/Jira/Integrations/JiraV3/JiraV3.py
  Packs/Jira/Integrations/JiraV3/JiraV3.yml
  Packs/Jira/Integrations/JiraV3/JiraV3_test.py
  Packs/Jira/ReleaseNotes/3_2_4.md
  Packs/Jira/pack_metadata.json
Labels: docs-approved

#35918 XSUP_40226_NGINX_Parsing
  Packs/NGINXWebServer/ParsingRules/NGINXWebServerParsingRules/NGINXWebServerParsingRules.xif
  Packs/NGINXWebServer/ReleaseNotes/1_0_9.md
  Packs/NGINXWebServer/pack_metadata.json
Labels: docs-approved

#35920 Deprecate hey script
  Packs/DeveloperTools/.pack-ignore
  Packs/DeveloperTools/ReleaseNotes/1_3_21.md
  Packs/DeveloperTools/Scripts/Hey/Hey.yml
  Packs/DeveloperTools/pack_metadata.json
Labels: docs-approved

#35661 Adding new Actor/Action process instance id fields
  Packs/CoreAlertFields/IncidentFields/incidentfield-Action_Process_Instance_ID.json
  Packs/CoreAlertFields/IncidentFields/incidentfield-Actor_Process_Instance_ID.json
  Packs/CoreAlertFields/ReleaseNotes/1_0_36.md
  Packs/CoreAlertFields/pack_metadata.json
Labels: docs-approved, bypass.url

#35705 Enrichment excluded IOCs (Allow-list) layouts update
  Packs/CommonScripts/ReleaseNotes/1_15_53.md
  Packs/CommonScripts/Scripts/EnrichExcludeButton/EnrichExcludeButton.py
  Packs/CommonScripts/Scripts/EnrichExcludeButton/EnrichExcludeButton.yml
  Packs/CommonScripts/Scripts/EnrichExcludeButton/EnrichExcludeButton_test.py
  Packs/CommonScripts/Scripts/EnrichExcludeButton/README.md
  Packs/CommonScripts/pack_metadata.json
  Packs/CommonTypes/.pack-ignore
  Packs/CommonTypes/Layouts/layoutscontainer-DomainV2.json
  Packs/CommonTypes/Layouts/layoutscontainer-EmailV2.json
  Packs/CommonTypes/Layouts/layoutscontainer-FileV2.json
  Packs/CommonTypes/Layouts/layoutscontainer-IPV2.json
  Packs/CommonTypes/Layouts/layoutscontainer-URLV2.json
  Packs/CommonTypes/ReleaseNotes/3_5_12.md
  Packs/CommonTypes/pack_metadata.json
Labels: docs-approved

#35928 use `fetch-depth:0` in `legacy-validate`
  .github/workflows/run-legacy-validate-for-contribution.yml
Labels: docs-approved

#35892 Fixed issue with missing IP and added UT
  Packs/ApiModules/Scripts/CoreIRApiModule/CoreIRApiModule.py
  Packs/ApiModules/Scripts/CoreIRApiModule/CoreIRApiModule_test.py
  Packs/Core/ReleaseNotes/3_0_54.md
  Packs/Core/pack_metadata.json
  Packs/CortexXDR/ReleaseNotes/6_1_65.md
  Packs/CortexXDR/pack_metadata.json
  Packs/ctf01/ReleaseNotes/1_0_26.md
  Packs/ctf01/pack_metadata.json
Labels: docs-approved

#35924 Jamf protect action enhancement
  Packs/JamfProtect/ModelingRules/JamfProtect/JamfProtect.xif
  Packs/JamfProtect/ReleaseNotes/1_1_1.md
  Packs/JamfProtect/pack_metadata.json
Labels: docs-approved

#35748 Tim Feed Threatfox
  Packs/FeedThreatFox/.pack-ignore
  Packs/FeedThreatFox/.secrets-ignore
  Packs/FeedThreatFox/Integrations/FeedThreatFox/FeedThreatFox.py
  Packs/FeedThreatFox/Integrations/FeedThreatFox/FeedThreatFox.yml
  Packs/FeedThreatFox/Integrations/FeedThreatFox/FeedThreatFox_description.md
  Packs/FeedThreatFox/Integrations/FeedThreatFox/FeedThreatFox_image.png
  Packs/FeedThreatFox/Integrations/FeedThreatFox/FeedThreatFox_test.py
  Packs/FeedThreatFox/Integrations/FeedThreatFox/README.md
  Packs/FeedThreatFox/README.md
  Packs/FeedThreatFox/pack_metadata.json
Labels: docs-approved

#35935 Minor fix o365 description
  Packs/Microsoft365Defender/Integrations/O365DefenderSafeLinks/O365DefenderSafeLinks_description.md
  Packs/Microsoft365Defender/ReleaseNotes/4_5_32.md
  Packs/Microsoft365Defender/pack_metadata.json
Labels: docs-approved, bypass.url

#35931 XSUP_39406_Parsing_Product_Update
  Packs/Office365/ParsingRules/Office365/Office365.xif
  Packs/Office365/README.md
  Packs/Office365/ReleaseNotes/1_0_5.md
  Packs/Office365/pack_metadata.json
Labels: docs-approved, bypass.url

#35926 adding parse malware
  Packs/FeedUnit42v2/Integrations/FeedUnit42v2/FeedUnit42v2.py
  Packs/FeedUnit42v2/Integrations/FeedUnit42v2/FeedUnit42v2.yml
  Packs/FeedUnit42v2/Integrations/FeedUnit42v2/FeedUnit42v2_test.py
  Packs/FeedUnit42v2/Integrations/FeedUnit42v2/test_data/feed_data.py
  Packs/FeedUnit42v2/ReleaseNotes/1_0_56.md
  Packs/FeedUnit42v2/pack_metadata.json
Labels: docs-approved

#35870 XSUP-40483 - Documentation update in CS Falcon
  Packs/CrowdStrikeFalcon/Integrations/CrowdStrikeFalcon/CrowdStrikeFalcon.yml
  Packs/CrowdStrikeFalcon/Integrations/CrowdStrikeFalcon/README.md
  Packs/CrowdStrikeFalcon/ReleaseNotes/2_0_12.md
  Packs/CrowdStrikeFalcon/pack_metadata.json
Labels: docs-approved

#35939 Fortigate fix
  Packs/FortiGate/Integrations/FortiGate/FortiGate.py
  Packs/FortiGate/Integrations/FortiGate/FortiGate.yml
  Packs/FortiGate/Integrations/FortiGate/FortiGate_test.py
  Packs/FortiGate/ReleaseNotes/2_0_3.md
  Packs/FortiGate/pack_metadata.json
Labels: docs-approved

#35938 add new validation batch
  validation_config.toml
Labels: docs-approved

#35917 bug - FortiSiem fetch with events work for version 6.6 and below
  Packs/FortiSIEM/Integrations/FortiSIEMV2/FortiSIEMV2.yml
  Packs/FortiSIEM/Integrations/FortiSIEMV2/README.md
  Packs/FortiSIEM/ReleaseNotes/2_0_37.md
  Packs/FortiSIEM/pack_metadata.json
Labels: docs-approved

#35792 CSC Pack Adoption
  Packs/CSCDomainManager/README.md
  Packs/CSCDomainManager/ReleaseNotes/1_0_2.md
  Packs/CSCDomainManager/pack_metadata.json
Labels: Contribution, docs-approved, Partner, Contribution Form Filled, Xsoar Support Level, External PR, Partner-Approved

#35902 [ASM] - EXPANDER - 10863 - Fix for Cortex ASM - Azure Enrichment Playbook
  Packs/CortexAttackSurfaceManagement/Playbooks/Cortex_ASM_-_Azure_Enrichment.yml
  Packs/CortexAttackSurfaceManagement/ReleaseNotes/1_7_47.md
  Packs/CortexAttackSurfaceManagement/doc_files/Cortex_ASM_-_Azure_Enrichment.png
  Packs/CortexAttackSurfaceManagement/pack_metadata.json
Labels: Contribution, docs-approved, Contribution Form Filled, Community, Xsoar Support Level, External PR, Security Review

#35956 Correct wildfire playbook inputs desc
  Packs/Palo_Alto_Networks_WildFire/Playbooks/Detonate_File_From_URL_-_WildFire_v2.yml
  Packs/Palo_Alto_Networks_WildFire/Playbooks/Detonate_File_From_URL_-_WildFire_v2_README.md
  Packs/Palo_Alto_Networks_WildFire/Playbooks/WildFire_-_Detonate_file_v2.yml
  Packs/Palo_Alto_Networks_WildFire/Playbooks/WildFire_-_Detonate_file_v2_README.md
  Packs/Palo_Alto_Networks_WildFire/ReleaseNotes/2_1_50.md
  Packs/Palo_Alto_Networks_WildFire/pack_metadata.json
Labels: docs-approved

#35946 [ASM] - XPSUPPORT - 2951 (EXPANDR) - Improved Fetching and Searchable Fields
  Packs/CortexXpanse/IncidentFields/incidentfield-Xpanse_Alert_ID.json
  Packs/CortexXpanse/IncidentFields/incidentfield-Xpanse_Asset_IDs.json
  Packs/CortexXpanse/IncidentFields/incidentfield-Xpanse_Attack_Surface_Rule_Name.json
  Packs/CortexXpanse/IncidentFields/incidentfield-Xpanse_Business_Units.json
  Packs/CortexXpanse/IncidentFields/incidentfield-Xpanse_Category.json
  Packs/CortexXpanse/IncidentFields/incidentfield-Xpanse_Certificate_Asset.json
  Packs/CortexXpanse/IncidentFields/incidentfield-Xpanse_Cloud_Asset.json
  Packs/CortexXpanse/IncidentFields/incidentfield-Xpanse_Country_Code.json
  Packs/CortexXpanse/IncidentFields/incidentfield-Xpanse_Description.json
  Packs/CortexXpanse/IncidentFields/incidentfield-Xpanse_Domain_Asset.json
  Packs/CortexXpanse/IncidentFields/incidentfield-Xpanse_External_ID.json
  Packs/CortexXpanse/IncidentFields/incidentfield-Xpanse_Host_Name.json
  Packs/CortexXpanse/IncidentFields/incidentfield-Xpanse_IP.json
  Packs/CortexXpanse/IncidentFields/incidentfield-Xpanse_Port.json
  Packs/CortexXpanse/IncidentFields/incidentfield-Xpanse_Progress_Status.json
  Packs/CortexXpanse/IncidentFields/incidentfield-Xpanse_Protocol.json
  Packs/CortexXpanse/IncidentFields/incidentfield-Xpanse_Remediation_Guidance.json
  Packs/CortexXpanse/IncidentFields/incidentfield-Xpanse_Responsive_IP_Asset.json
  Packs/CortexXpanse/IncidentFields/incidentfield-Xpanse_Service_Classifications.json
  Packs/CortexXpanse/IncidentFields/incidentfield-Xpanse_Service_Details.json
  Packs/CortexXpanse/IncidentFields/incidentfield-Xpanse_Service_ID.json
  Packs/CortexXpanse/IncidentFields/incidentfield-Xpanse_Service_Validation.json
  Packs/CortexXpanse/IncidentFields/incidentfields-Xpanse_Provider.json
  Packs/CortexXpanse/Integrations/CortexXpanse/CortexXpanse.py
  Packs/CortexXpanse/Integrations/CortexXpanse/CortexXpanse.yml
  Packs/CortexXpanse/Integrations/CortexXpanse/CortexXpanse_test.py
  Packs/CortexXpanse/Integrations/CortexXpanse/README.md
  Packs/CortexXpanse/Integrations/CortexXpanse/test_data/raw_response.py
  Packs/CortexXpanse/ReleaseNotes/1_2_3.md
  Packs/CortexXpanse/pack_metadata.json
Labels: Contribution, docs-approved, Contribution Form Filled, Community, Xsoar Support Level, External PR, Security Review

#35900 DeCYFIR IoC Integration bug fixes
  Packs/DeCYFIR/Integrations/decyfiriocs/decyfiriocs.py
  Packs/DeCYFIR/Integrations/decyfiriocs/decyfiriocs.yml
  Packs/DeCYFIR/ReleaseNotes/1_0_13.md
  Packs/DeCYFIR/pack_metadata.json
  package-lock.json
Labels: Contribution, docs-approved, Partner, Contribution Form Filled, Partner Support Level, External PR, Partner-Approved, TIM Review

#35951 Reco: get-assets by id
  Packs/Reco/Integrations/Reco/README.md
  Packs/Reco/Integrations/Reco/Reco.py
  Packs/Reco/Integrations/Reco/Reco.yml
  Packs/Reco/ReleaseNotes/1_5_0.md
  Packs/Reco/pack_metadata.json
Labels: Contribution, docs-approved, Partner, post-demo, Contribution Form Filled, Partner Support Level, External PR, Partner-Approved

#35940 CRTX-125833 Microsoft IIS Parsing and Modeling fixes and improvements
  Packs/MicrosoftIISWebServer/.secrets-ignore
  Packs/MicrosoftIISWebServer/ModelingRules/MicrosoftIISWebServerModelingRules_1_3/MicrosoftIISWebServerModelingRules_1_3.xif
  Packs/MicrosoftIISWebServer/ModelingRules/MicrosoftIISWebServerModelingRules_1_3/MicrosoftIISWebServerModelingRules_1_3_schema.json
  Packs/MicrosoftIISWebServer/ParsingRules/MicrosoftIISWebServer/MicrosoftIISWebServer.xif
  Packs/MicrosoftIISWebServer/README.md
  Packs/MicrosoftIISWebServer/ReleaseNotes/1_0_10.md
  Packs/MicrosoftIISWebServer/pack_metadata.json
Labels: docs-approved, bypass.url

#35968 change contributions tl
  .github/content_roles.json
Labels: docs-approved

#35985 Fix relative paths
  Packs/CiscoSpark/Integrations/CiscoWebexEventCollector/CiscoWebexEventCollector_description.md
  Packs/CiscoSpark/ReleaseNotes/1_0_8.md
  Packs/CiscoSpark/pack_metadata.json
Labels: docs-approved

#35976 filter first array element for process email attachments
  Packs/Phishing/Playbooks/Process_Email_-_Generic_v2.yml
  Packs/Phishing/Playbooks/Process_Email_-_Generic_v2_README.md
  Packs/Phishing/ReleaseNotes/3_6_22.md
  Packs/Phishing/pack_metadata.json
Labels: docs-approved

#35943 Fix RSS feed fetch-indicators
  Packs/FeedRSS/Integrations/FeedRSS/FeedRSS.py
  Packs/FeedRSS/Integrations/FeedRSS/FeedRSS.yml
  Packs/FeedRSS/Integrations/FeedRSS/FeedRSS_test.py
  Packs/FeedRSS/Integrations/FeedRSS/test_data/test_variables.py
  Packs/FeedRSS/ReleaseNotes/1_0_10.md
  Packs/FeedRSS/pack_metadata.json
Labels: docs-approved, ForceMerge

#35987 CRTX-125833 IIS Fix 1.0.10 Release Notes
  Packs/MicrosoftIISWebServer/ReleaseNotes/1_0_10.md
Labels: docs-approved

#35960 TIM - URL regex fix to allow user:pass in URL
  Packs/Base/TestPlaybooks/playbook-URLextraction-Test.yml
  Packs/CommonTypes/IndicatorTypes/reputation-url.json
  Packs/CommonTypes/ReleaseNotes/3_5_13.md
  Packs/CommonTypes/pack_metadata.json
Labels: docs-approved

#35863 Fix FindEmailCampaign
  Packs/Campaign/ReleaseNotes/3_4_8.md
  Packs/Campaign/Scripts/FindEmailCampaign/FindEmailCampaign.py
  Packs/Campaign/Scripts/FindEmailCampaign/FindEmailCampaign.yml
  Packs/Campaign/pack_metadata.json
Labels: docs-approved

#35884 bug - parseEmail does not remove "RE:" prefix in subject
  Packs/EmailCommunication/ReleaseNotes/2_0_31.md
  Packs/EmailCommunication/Scripts/SendEmailReply/SendEmailReply.py
  Packs/EmailCommunication/Scripts/SendEmailReply/SendEmailReply_test.py
  Packs/EmailCommunication/pack_metadata.json
Labels: docs-approved

#35979 fix a bug with limit_assets
  Packs/QRadar/Integrations/QRadar_v3/QRadar_v3.py
  Packs/QRadar/ReleaseNotes/2_5_3.md
  Packs/QRadar/pack_metadata.json
Labels: docs-approved

#35997 team members changes
  .github/content_roles.json
Labels: docs-approved

#35922 Deprecate the pack
  Packs/MicrosoftAdvancedThreatAnalytics/Integrations/MicrosoftAdvancedThreatAnalytics/MicrosoftAdvancedThreatAnalytics.yml
  Packs/MicrosoftAdvancedThreatAnalytics/Integrations/MicrosoftAdvancedThreatAnalytics/README.md
  Packs/MicrosoftAdvancedThreatAnalytics/ReleaseNotes/1_0_18.md
  Packs/MicrosoftAdvancedThreatAnalytics/TestPlaybooks/MicrosoftAdvancedThreatAnalytics-Test.yml
  Packs/MicrosoftAdvancedThreatAnalytics/pack_metadata.json
  Tests/conf.json
Labels: docs-approved

#35727 Cisco Umbrella
  Packs/Cisco-umbrella/.secrets-ignore
  Packs/Cisco-umbrella/Integrations/Cisco-umbrella-investigate/Cisco-umbrella-investigate.py
  Packs/Cisco-umbrella/Integrations/Cisco-umbrella-investigate/Cisco-umbrella-investigate.yml
  Packs/Cisco-umbrella/Integrations/Cisco-umbrella-investigate/Cisco-umbrella-investigate_description.md
  Packs/Cisco-umbrella/Integrations/Cisco-umbrella-investigate/Cisco-umbrella-investigate_test.py
  Packs/Cisco-umbrella/Integrations/Cisco-umbrella-investigate/README.md
  Packs/Cisco-umbrella/Integrations/Cisco-umbrella-investigate/command_example copy.txt
  Packs/Cisco-umbrella/Integrations/Cisco-umbrella-investigate/command_example.txt
  Packs/Cisco-umbrella/Integrations/Cisco-umbrella-investigate/test_data/asn_bgp.json
  Packs/Cisco-umbrella/Integrations/Cisco-umbrella-investigate/test_data/domain_categorization.json
  Packs/Cisco-umbrella/Integrations/Cisco-umbrella-investigate/test_data/domain_co_occurence.json
  Packs/Cisco-umbrella/Integrations/Cisco-umbrella-investigate/test_data/domain_related_domains.json
  Packs/Cisco-umbrella/Integrations/Cisco-umbrella-investigate/test_data/domain_risk_score.json
  Packs/Cisco-umbrella/Integrations/Cisco-umbrella-investigate/test_data/domain_security.json
  Packs/Cisco-umbrella/Integrations/Cisco-umbrella-investigate/test_data/domain_sub_domain.json
  Packs/Cisco-umbrella/Integrations/Cisco-umbrella-investigate/test_data/domain_volume.json
  Packs/Cisco-umbrella/Integrations/Cisco-umbrella-investigate/test_data/domain_whois.json
  Packs/Cisco-umbrella/Integrations/Cisco-umbrella-investigate/test_data/email_whois.json
  Packs/Cisco-umbrella/Integrations/Cisco-umbrella-investigate/test_data/ip_bgp.json
  Packs/Cisco-umbrella/Integrations/Cisco-umbrella-investigate/test_data/list_timeline.json
  Packs/Cisco-umbrella/Integrations/Cisco-umbrella-investigate/test_data/nameserver_whois.json
  Packs/Cisco-umbrella/Integrations/Cisco-umbrella-investigate/test_data/regex_whois.json
  Packs/Cisco-umbrella/Integrations/Cisco-umbrella-investigate/test_data/resource_records.json
  Packs/Cisco-umbrella/Integrations/Cisco-umbrella-investigate/test_data/search_domain.json
  Packs/Cisco-umbrella/Integrations/Cisco-umbrella-investigate/test_data/top_domain.json
  Packs/Cisco-umbrella/Integrations/Cisco-umbrella-investigate/test_data/whois_history.json
  Packs/Cisco-umbrella/README.md
  Packs/Cisco-umbrella/ReleaseNotes/2_0_0.json
  Packs/Cisco-umbrella/ReleaseNotes/2_0_0.md
  Packs/Cisco-umbrella/TestPlaybooks/playbook-cisco_umbrella_investigate_Test.yml
  Packs/Cisco-umbrella/pack_metadata.json
Labels: Contribution, docs-approved, Contribution Form Filled, Community, Xsoar Support Level, External PR

#35986 Zoom Argument Fix
  Packs/Zoom/.pack-ignore
  Packs/Zoom/Integrations/Zoom/README.md
  Packs/Zoom/Integrations/Zoom/Zoom.yml
  Packs/Zoom/ReleaseNotes/1_6_13.md
  Packs/Zoom/pack_metadata.json
Labels: docs-approved

#35703 MISP Feed Timeout
  Packs/FeedMISP/Integrations/FeedMISP/FeedMISP.py
  Packs/FeedMISP/Integrations/FeedMISP/FeedMISP.yml
  Packs/FeedMISP/Integrations/FeedMISP/FeedMISP_test.py
  Packs/FeedMISP/ReleaseNotes/1_0_36.md
  Packs/FeedMISP/pack_metadata.json
Labels: docs-approved

#35989 [Microsoft Teams] fix get_team_aad_id url
  Packs/MicrosoftTeams/Integrations/MicrosoftTeams/MicrosoftTeams.py
  Packs/MicrosoftTeams/Integrations/MicrosoftTeams/MicrosoftTeams_test.py
  Packs/MicrosoftTeams/ReleaseNotes/1_4_66.md
  Packs/MicrosoftTeams/pack_metadata.json
  validation_config.toml
Labels: docs-approved
