Repository demisto/content, pull requests merged in 2024-06, with the labels that each got.

#34638 MS teams docs update
  Packs/MicrosoftTeams/Integrations/MicrosoftTeams/README.md
Labels: docs-approved

#34658 fix the exclude_fields field
  Packs/CortexXDR/Integrations/CortexXDRIR/CortexXDRIR.py
  Packs/CortexXDR/Integrations/CortexXDRIR/CortexXDRIR_test.py
  Packs/CortexXDR/ReleaseNotes/6_1_42.md
  Packs/CortexXDR/pack_metadata.json
Labels: docs-approved

#33924 Email DT fix
  Packs/Anomali_ThreatStream/ReleaseNotes/2_2_19.json
  Packs/Anomali_ThreatStream/ReleaseNotes/2_2_19.md
  Packs/Anomali_ThreatStream/pack_metadata.json
  Packs/Base/.pack-ignore
  Packs/Base/ReleaseNotes/1_34_8.json
  Packs/Base/ReleaseNotes/1_34_8.md
  Packs/Base/Scripts/CommonServerPython/CommonServerPython.py
  Packs/Base/Scripts/CommonServerPython/CommonServerPython_test.py
  Packs/Base/pack_metadata.json
  Packs/CofenseIntelligenceV2/ReleaseNotes/1_1_16.json
  Packs/CofenseIntelligenceV2/ReleaseNotes/1_1_16.md
  Packs/CofenseIntelligenceV2/pack_metadata.json
  Packs/CommonTypes/ReleaseNotes/3_5_4.md
  Packs/CommonTypes/pack_metadata.json
  Packs/EclecticIQ/ReleaseNotes/3_0_1.json
  Packs/EclecticIQ/ReleaseNotes/3_0_1.md
  Packs/EclecticIQ/pack_metadata.json
  Packs/EmailHippo/Integrations/EmailHippo/test_data/get_email_output.json
  Packs/EmailHippo/ReleaseNotes/1_0_6.json
  Packs/EmailHippo/ReleaseNotes/1_0_6.md
  Packs/EmailHippo/pack_metadata.json
  Packs/IPQualityScore/ReleaseNotes/1_0_10.json
  Packs/IPQualityScore/ReleaseNotes/1_0_10.md
  Packs/IPQualityScore/pack_metadata.json
  Packs/MISP/ReleaseNotes/2_1_43.json
  Packs/MISP/ReleaseNotes/2_1_43.md
  Packs/MISP/pack_metadata.json
  Packs/ReversingLabs_Titanium_Cloud/ReleaseNotes/2_5_1.json
  Packs/ReversingLabs_Titanium_Cloud/ReleaseNotes/2_5_1.md
  Packs/ReversingLabs_Titanium_Cloud/pack_metadata.json
  Packs/SEKOIAIntelligenceCenter/ReleaseNotes/1_2_32.json
  Packs/SEKOIAIntelligenceCenter/ReleaseNotes/1_2_32.md
  Packs/SEKOIAIntelligenceCenter/pack_metadata.json
  Packs/ThreatZone/ReleaseNotes/1_0_3.json
  Packs/ThreatZone/ReleaseNotes/1_0_3.md
  Packs/ThreatZone/pack_metadata.json
  Packs/VMRay/ReleaseNotes/1_1_15.json
  Packs/VMRay/ReleaseNotes/1_1_15.md
  Packs/VMRay/pack_metadata.json
Labels: docs-approved

#34562 Add autoupdate_docker mode
  .github/workflows/pre-commit-reuse.yml
  .pre-commit-config_template.yaml
Labels: docs-approved

#34646 Fix EWSv2_empty_attachment_test
  Packs/MicrosoftExchangeOnPremise/TestPlaybooks/playbook-EWSv2_empty_attachment_test.yml
Labels: docs-approved

#34597 Gem Pack - Add "trust any certificate" option
  Packs/Gem/Integrations/Gem/Gem.py
  Packs/Gem/Integrations/Gem/Gem.yml
  Packs/Gem/Integrations/Gem/README.md
  Packs/Gem/ReleaseNotes/1_0_1.md
  Packs/Gem/pack_metadata.json
Labels: Contribution, docs-approved, Partner, post-demo, Contribution Form Filled, Partner Support Level, External PR, Partner-Approved

#34662 CRTX 115858 cisco meraki
  Packs/cisco-meraki/ModelingRules/CiscoMerakiModelingRules/CiscoMerakiModelingRules.xif
  Packs/cisco-meraki/ModelingRules/CiscoMerakiModelingRules/CiscoMerakiModelingRules.yml
  Packs/cisco-meraki/ModelingRules/CiscoMerakiModelingRules/CiscoMerakiModelingRules_schema.json
  Packs/cisco-meraki/ReleaseNotes/1_0_11.md
  Packs/cisco-meraki/pack_metadata.json
Labels: docs-approved, ForceMerge

#34465 [Auto Update Docker] auto_update_docker_staging_branch
  Packs/AccentureCTI_Feed/Integrations/ACTIIndicatorFeed/ACTIIndicatorFeed.py
  Packs/AccentureCTI_Feed/Integrations/ACTIIndicatorFeed/ACTIIndicatorFeed.yml
  Packs/AccentureCTI_Feed/ReleaseNotes/1_1_36.md
  Packs/AccentureCTI_Feed/pack_metadata.json
  Packs/Anomali_ThreatStream/ReleaseNotes/2_2_20.md
  Packs/Anomali_ThreatStream/pack_metadata.json
  Packs/CommonScripts/ReleaseNotes/1_15_4.md
  Packs/CommonScripts/Scripts/ExifRead/ExifRead.py
  Packs/CommonScripts/Scripts/ExifRead/ExifRead.yml
  Packs/CommonScripts/Scripts/ExtractDomainAndFQDNFromUrlAndEmail/ExtractDomainAndFQDNFromUrlAndEmail.yml
  Packs/CommonScripts/Scripts/ExtractDomainFromUrlFormat/ExtractDomainFromUrlFormat.py
  Packs/CommonScripts/Scripts/ExtractDomainFromUrlFormat/ExtractDomainFromUrlFormat.yml
  Packs/CommonScripts/Scripts/ExtractDomainFromUrlFormat/ExtractDomainFromUrlFormat_test.py
  Packs/CommonScripts/Scripts/ExtractFQDNFromUrlAndEmail/ExtractFQDNFromUrlAndEmail.py
  Packs/CommonScripts/Scripts/ExtractFQDNFromUrlAndEmail/ExtractFQDNFromUrlAndEmail.yml
  Packs/CommonScripts/Scripts/ExtractFQDNFromUrlAndEmail/ExtractFQDNFromUrlAndEmail_test.py
  Packs/CommonScripts/Scripts/FetchIndicatorsFromFile/FetchIndicatorsFromFile.py
  Packs/CommonScripts/Scripts/FetchIndicatorsFromFile/FetchIndicatorsFromFile.yml
  Packs/CommonScripts/Scripts/FetchIndicatorsFromFile/FetchIndicatorsFromFile_test.py
  Packs/CommonScripts/Scripts/LanguageDetect/LanguageDetect.yml
  Packs/CommonScripts/Scripts/ParseExcel/ParseExcel.yml
  Packs/CommonScripts/Scripts/StixCreator/StixCreator.yml
  Packs/CommonScripts/pack_metadata.json
  Packs/PolySwarm/Integrations/PolySwarmV2/PolySwarmV2.py
  Packs/PolySwarm/Integrations/PolySwarmV2/PolySwarmV2.yml
  Packs/PolySwarm/ReleaseNotes/2_0_6.md
  Packs/PolySwarm/pack_metadata.json
  Packs/UBIRCH/Integrations/UBIRCH/UBIRCH.py
  Packs/UBIRCH/Integrations/UBIRCH/UBIRCH.yml
  Packs/UBIRCH/Integrations/UBIRCH/UBIRCH_test.py
  Packs/UBIRCH/ReleaseNotes/1_0_1.md
  Packs/UBIRCH/pack_metadata.json
Labels: docs-approved, auto-update-docker

#34661 Added XSIAM tags to fireeyehx readme
  Packs/FireEyeHX/README.md
Labels: docs-approved

#34644 Added usage notes to the phishing test playbooks
  Packs/Phishing/TestPlaybooks/Phishing_v3_-_DomainSquatting+EML+MaliciousIndicators_-_Test.yml
  Packs/Phishing/TestPlaybooks/Phishing_v3_-_Get_Original_Email_+_Search_&_Delete_-_Test.yml
Labels: docs-approved

#34643 redmine commands - handle multiselect customfield
  Packs/Redmine/Integrations/Redmine/README.md
  Packs/Redmine/Integrations/Redmine/Redmine.py
  Packs/Redmine/Integrations/Redmine/Redmine.yml
  Packs/Redmine/Integrations/Redmine/Redmine_test.py
  Packs/Redmine/ReleaseNotes/1_0_4.md
  Packs/Redmine/pack_metadata.json
Labels: docs-approved

#34586 ZScaler ZIA Cloud NSS Modeling
  Packs/Zscaler/.pack-ignore
  Packs/Zscaler/.secrets-ignore
  Packs/Zscaler/ModelingRules/ZscalerModelingRule_1_3/ZscalerModelingRule_1_3.xif
  Packs/Zscaler/ModelingRules/ZscalerModelingRule_1_3/ZscalerModelingRule_1_3_schema.json
  Packs/Zscaler/ParsingRules/ZscalerZIA/ZscalerZIA.xif
  Packs/Zscaler/ParsingRules/ZscalerZIA/ZscalerZIA.yml
  Packs/Zscaler/README.md
  Packs/Zscaler/ReleaseNotes/1_3_21.md
  Packs/Zscaler/pack_metadata.json
Labels: docs-approved

#34669 search mail- test playbook re write
  Packs/MicrosoftExchangeOnPremise/TestPlaybooks/playbook-EWS-Searchmailbox-Test.yml
  Tests/conf.json
Labels: docs-approved

#34664 fix HttpV2 TPB
  Packs/CommonScripts/.secrets-ignore
  Packs/CommonScripts/TestPlaybooks/playbook-HttpV2-Test.yml
Labels: docs-approved

#34581 Fix xdr mirroring issue
  Packs/CortexXDR/Integrations/CortexXDRIR/CortexXDRIR.py
  Packs/CortexXDR/Integrations/CortexXDRIR/CortexXDRIR.yml
  Packs/CortexXDR/ReleaseNotes/6_1_42.md
  Packs/CortexXDR/ReleaseNotes/6_1_43.md
  Packs/CortexXDR/TestPlaybooks/Test_Playbook_-_Cortex_XDR_-_Retrieve_File_by_sha256.yml
  Packs/CortexXDR/pack_metadata.json
Labels: docs-approved

#34372 SentinelOne v2: Fixes sentinelone-disconnect-agent and sentinelone-connect-agent issues.
  Packs/SentinelOne/Integrations/SentinelOne-V2/README.md
  Packs/SentinelOne/Integrations/SentinelOne-V2/SentinelOne-V2.py
  Packs/SentinelOne/Integrations/SentinelOne-V2/SentinelOne-V2.yml
  Packs/SentinelOne/ReleaseNotes/3_2_25.md
  Packs/SentinelOne/pack_metadata.json
Labels: Contribution, pending-demo, post-demo, Contribution Form Filled, Community, pending-contributor, Partner Support Level, External PR

#34627 Reco fix api
  Packs/Reco/Integrations/Reco/README.md
  Packs/Reco/Integrations/Reco/Reco.py
  Packs/Reco/Integrations/Reco/Reco.yml
  Packs/Reco/Integrations/Reco/Reco_test.py
  Packs/Reco/README.md
  Packs/Reco/ReleaseNotes/1_4_0.md
  Packs/Reco/pack_metadata.json
Labels: Contribution, Partner, Contribution Form Filled, Partner Support Level, External PR, Partner-Approved, TIM Review

#34445 Container Script
  Packs/Base/ReleaseNotes/1_34_9.md
  Packs/Base/Scripts/CommonServerPython/CommonServerPython.py
  Packs/Base/pack_metadata.json
Labels: docs-approved

#34624 remove lint from build
  .circleci/analyze_non_packs_files.sh
  .circleci/config.yml
Labels: docs-approved

#34551 [ASM] EXPANDR-6928 Certificate changes
  Packs/CortexAttackSurfaceManagement/Playbooks/Cortex_ASM_-_Certificate_Enrichment.yml
  Packs/CortexAttackSurfaceManagement/Playbooks/Cortex_ASM_-_Certificate_Enrichment_README.md
  Packs/CortexAttackSurfaceManagement/Playbooks/Cortex_ASM_-_Enrichment.yml
  Packs/CortexAttackSurfaceManagement/Playbooks/Cortex_ASM_-_Enrichment_README.md
  Packs/CortexAttackSurfaceManagement/README.md
  Packs/CortexAttackSurfaceManagement/ReleaseNotes/1_7_39.md
  Packs/CortexAttackSurfaceManagement/doc_files/Cortex_ASM_-_Certificate_Enrichment.png
  Packs/CortexAttackSurfaceManagement/doc_files/Cortex_ASM_-_Enrichment.png
  Packs/CortexAttackSurfaceManagement/pack_metadata.json
  Packs/Venafi/pack_metadata.json
Labels: Contribution, docs-approved, Contribution Form Filled, Community, Xsoar Support Level, External PR, Security Review

#34632 Remove PhishTank TPB
  Packs/PhishTank/Integrations/PhishTankV2/PhishTankV2.yml
  Packs/PhishTank/ReleaseNotes/2_0_31.md
  Packs/PhishTank/pack_metadata.json
  Tests/conf.json
Labels: docs-approved

#34678 Ewso365 - Fix fetch
  Packs/MicrosoftExchangeOnline/Integrations/EWSO365/EWSO365.py
  Packs/MicrosoftExchangeOnline/ReleaseNotes/1_3_11.md
  Packs/MicrosoftExchangeOnline/pack_metadata.json
Labels: docs-approved

#34657 Implemented bypassing malformed indicators
  Packs/CybleThreatIntel/Integrations/CybleThreatIntel/CybleThreatIntel.py
  Packs/CybleThreatIntel/Integrations/CybleThreatIntel/CybleThreatIntel.yml
  Packs/CybleThreatIntel/Integrations/CybleThreatIntel/CybleThreatIntel_test.py
  Packs/CybleThreatIntel/Integrations/CybleThreatIntel/test_data/input.json
  Packs/CybleThreatIntel/ReleaseNotes/2_0_23.md
  Packs/CybleThreatIntel/pack_metadata.json
Labels: Contribution, docs-approved, Partner, Contribution Form Filled, Partner Support Level, External PR, Partner-Approved

#34671 Extract hyperlinks from office files
  Packs/CommonScripts/.pack-ignore
  Packs/CommonScripts/ReleaseNotes/1_15_5.md
  Packs/CommonScripts/Scripts/ExtractHyperlinksFromOfficeFiles/ExtractHyperlinksFromOfficeFiles.py
  Packs/CommonScripts/Scripts/ExtractHyperlinksFromOfficeFiles/ExtractHyperlinksFromOfficeFiles.yml
  Packs/CommonScripts/Scripts/ExtractHyperlinksFromOfficeFiles/ExtractHyperlinksFromOfficeFiles_test.py
  Packs/CommonScripts/Scripts/ExtractHyperlinksFromOfficeFiles/test_data/d3.docx
  Packs/CommonScripts/pack_metadata.json
Labels: docs-approved

#34681 Container Script Null ExecutedCommands
  Packs/Base/ReleaseNotes/1_34_10.md
  Packs/Base/Scripts/CommonServerPython/CommonServerPython.py
  Packs/Base/pack_metadata.json
Labels: docs-approved

#34676 [API Execution Metrics] Added Error Types To The Main Widget
  Packs/CommonDashboards/Dashboards/dashboard-APIExecutionMetrics.json
  Packs/CommonDashboards/ReleaseNotes/1_6_0.md
  Packs/CommonDashboards/pack_metadata.json
Labels: docs-approved

#34700 Changes related to the Vectra XDR release 1.0.5
  Packs/VectraXDR/.pack-ignore
  Packs/VectraXDR/Integrations/VectraXDR/README.md
  Packs/VectraXDR/Integrations/VectraXDR/VectraXDR.py
  Packs/VectraXDR/Integrations/VectraXDR/VectraXDR.yml
  Packs/VectraXDR/Integrations/VectraXDR/VectraXDR_description.md
  Packs/VectraXDR/Integrations/VectraXDR/VectraXDR_test.py
  Packs/VectraXDR/Integrations/VectraXDR/test_data/invalid_page_number_404_error.json
  Packs/VectraXDR/ReleaseNotes/1_0_5.md
  Packs/VectraXDR/pack_metadata.json
Labels: Contribution, docs-approved, Partner, Contribution Form Filled, Partner Support Level, External PR, Partner-Approved

#34701 CIAC-8513 Notify when there is more than 1 PR that was contributed by the same author - addition to find internal PR's as well
  Utils/github_workflow_scripts/handle_external_pr.py
Labels: docs-approved

#34117 Adding Armis logos for the XSIAM ingestion dashboard
  Packs/Armis/Integrations/ArmisEventCollector/ArmisEventCollector_dark.svg
  Packs/Armis/Integrations/ArmisEventCollector/ArmisEventCollector_light.svg
  Packs/Armis/ReleaseNotes/1_1_14.md
  Packs/Armis/pack_metadata.json
Labels: Contribution, docs-approved, Contribution Form Filled, Community, Partner Support Level, External PR, Partner-Approved

#34660 section updated to advance
  Packs/Censys/Integrations/CensysV2/CensysV2.yml
  Packs/Censys/ReleaseNotes/2_0_30.md
  Packs/Censys/pack_metadata.json
Labels: docs-approved

#34684 MISP V3 Test
  Packs/Anomali_ThreatStream/ReleaseNotes/2_2_19.md
  Packs/Base/ReleaseNotes/1_34_8.json
  Packs/Base/ReleaseNotes/1_34_8.md
  Packs/CofenseIntelligenceV2/ReleaseNotes/1_1_16.md
  Packs/EclecticIQ/ReleaseNotes/3_0_1.md
  Packs/EmailHippo/ReleaseNotes/1_0_6.md
  Packs/IPQualityScore/ReleaseNotes/1_0_10.md
  Packs/MISP/TestPlaybooks/MISP_V3_Test.yml
  Packs/ReversingLabs_Titanium_Cloud/ReleaseNotes/2_5_1.md
  Packs/SEKOIAIntelligenceCenter/ReleaseNotes/1_2_32.md
  Packs/ThreatZone/ReleaseNotes/1_0_3.md
  Packs/VMRay/ReleaseNotes/1_1_15.md
Labels: docs-approved, ForceMerge

#34696 Fix for 'Identity Analytics - Alert Handling' playbook
  Packs/Core/Playbooks/playbook-Identity_Analytics_-_Alert_Handling.yml
  Packs/Core/Playbooks/playbook-Identity_Analytics_-_Alert_Handling_README.md
  Packs/Core/ReleaseNotes/3_0_34.md
  Packs/Core/pack_metadata.json
Labels: docs-approved

#34706 Fix Incapsula authorization error
  Packs/Incapsula/Integrations/Incapsula/Incapsula.js
  Packs/Incapsula/Integrations/Incapsula/Incapsula.yml
  Packs/Incapsula/ReleaseNotes/1_1_6.md
  Packs/Incapsula/pack_metadata.json
Labels: docs-approved, release-notes-only, ForceMerge

#34692 Microsoft defender rebranding
  Packs/Microsoft365Defender/Integrations/Microsoft365Defender/Microsoft365Defender_dark.svg
  Packs/Microsoft365Defender/Integrations/Microsoft365Defender/Microsoft365Defender_description.md
  Packs/Microsoft365Defender/Integrations/Microsoft365Defender/Microsoft365Defender_image.png
  Packs/Microsoft365Defender/Integrations/Microsoft365Defender/Microsoft365Defender_light.svg
  Packs/Microsoft365Defender/Integrations/Microsoft365Defender/README.md
  Packs/Microsoft365Defender/Integrations/O365DefenderSafeLinks/O365DefenderSafeLinks.yml
  Packs/Microsoft365Defender/Integrations/O365DefenderSafeLinks/O365DefenderSafeLinks_description.md
  Packs/Microsoft365Defender/Integrations/O365DefenderSafeLinks/README.md
  Packs/Microsoft365Defender/Integrations/O365DefenderSafeLinksSingleUser/O365DefenderSafeLinksSingleUser_description.md
  Packs/Microsoft365Defender/Integrations/O365DefenderSafeLinksSingleUser/README.md
  Packs/Microsoft365Defender/Playbooks/playbook-Microsoft_365_Defender_-_Emails_Indicators_Hunt_README.md
  Packs/Microsoft365Defender/Playbooks/playbook-Microsoft_365_Defender_-_Get_Email_URL_Clicks_README.md
  Packs/Microsoft365Defender/Playbooks/playbook-Microsoft_365_Defender_-_Threat_Hunting_Generic_README.md
  Packs/Microsoft365Defender/README.md
  Packs/Microsoft365Defender/ReleaseNotes/4_5_26.md
  Packs/Microsoft365Defender/pack_metadata.json
Labels: docs-approved

#33735 9835 GitHub feed
  Packs/FeedGitHub/.pack-ignore
  Packs/FeedGitHub/.secrets-ignore
  Packs/FeedGitHub/Integrations/FeedGitHub/FeedGitHub.py
  Packs/FeedGitHub/Integrations/FeedGitHub/FeedGitHub.yml
  Packs/FeedGitHub/Integrations/FeedGitHub/FeedGitHub_description.md
  Packs/FeedGitHub/Integrations/FeedGitHub/FeedGitHub_image.png
  Packs/FeedGitHub/Integrations/FeedGitHub/FeedGitHub_test.py
  Packs/FeedGitHub/Integrations/FeedGitHub/README.md
  Packs/FeedGitHub/Integrations/FeedGitHub/command_examples
  Packs/FeedGitHub/Integrations/FeedGitHub/test_data/all-commit-files-res.json
  Packs/FeedGitHub/Integrations/FeedGitHub/test_data/build_iterator_results.json
  Packs/FeedGitHub/Integrations/FeedGitHub/test_data/content_files_from_repo.json
  Packs/FeedGitHub/Integrations/FeedGitHub/test_data/extract_commit_response.json
  Packs/FeedGitHub/Integrations/FeedGitHub/test_data/fetch-indicators-res.json
  Packs/FeedGitHub/Integrations/FeedGitHub/test_data/files-list.json
  Packs/FeedGitHub/Integrations/FeedGitHub/test_data/get_content-files-from-repo-result.json
  Packs/FeedGitHub/Integrations/FeedGitHub/test_data/get_indicators_command_results.json
  Packs/FeedGitHub/Integrations/FeedGitHub/test_data/hr-indicators.json
  Packs/FeedGitHub/Integrations/FeedGitHub/test_data/iocs-res.json
  Packs/FeedGitHub/Integrations/FeedGitHub/test_data/iterator-test.json
  Packs/FeedGitHub/Integrations/FeedGitHub/test_data/list-parsed-rules-res.json
  Packs/FeedGitHub/Integrations/FeedGitHub/test_data/owner-repo-example.png
  Packs/FeedGitHub/Integrations/FeedGitHub/test_data/relevant-files.json
  Packs/FeedGitHub/Integrations/FeedGitHub/test_data/split-critical-yara-rule-res.json
  Packs/FeedGitHub/Integrations/FeedGitHub/test_data/taxii_test.json
  Packs/FeedGitHub/Integrations/FeedGitHub/test_data/taxii_test_res.json
  Packs/FeedGitHub/Integrations/FeedGitHub/test_data/test-ioc-indicators.txt
  Packs/FeedGitHub/Integrations/FeedGitHub/test_data/test-split-yara-1.yar
  Packs/FeedGitHub/Integrations/FeedGitHub/test_data/test-split-yara-critical-rule.yar
  Packs/FeedGitHub/Integrations/FeedGitHub/test_data/test_yara_parser_res.txt
  Packs/FeedGitHub/Integrations/FeedGitHub/test_data/yara-rule-1-res.json
  Packs/FeedGitHub/Integrations/FeedGitHub/test_data/yara-rule-1.yar
  Packs/FeedGitHub/Integrations/FeedGitHub/test_data/yara-rule-2-res.json
  Packs/FeedGitHub/Integrations/FeedGitHub/test_data/yara-rule-2.yar
  Packs/FeedGitHub/Integrations/FeedGitHub/test_data/yara-rule-3-res.json
  Packs/FeedGitHub/Integrations/FeedGitHub/test_data/yara-rule-3.yar
  Packs/FeedGitHub/README.md
  Packs/FeedGitHub/pack_metadata.json
  Tests/docker_native_image_config.json
Labels: docs-approved

#34714 Remove nightly-ok github workflow
  .github/workflows/check-nightly-ok-label.yml
Labels: docs-approved

#34725 Updated Hello World Docker Image
  Packs/HelloWorld/Integrations/HelloWorld/HelloWorld.yml
  Packs/HelloWorld/ReleaseNotes/3_0_10.md
  Packs/HelloWorld/pack_metadata.json
Labels: docs-approved

#34694 Joe-submission-info command Update
  Packs/JoeSecurity/Integrations/JoeSecurityV2/JoeSecurityV2.yml
  Packs/JoeSecurity/Integrations/JoeSecurityV2/README.md
  Packs/JoeSecurity/ReleaseNotes/1_1_21.json
  Packs/JoeSecurity/ReleaseNotes/1_1_21.md
  Packs/JoeSecurity/pack_metadata.json
Labels: docs-approved, ForceMerge

#34734 Fix duo-get-events command
  Packs/DuoAdminApi/Integrations/DuoEventCollector/DuoEventCollector.py
  Packs/DuoAdminApi/Integrations/DuoEventCollector/DuoEventCollector.yml
  Packs/DuoAdminApi/ReleaseNotes/4_0_19.md
  Packs/DuoAdminApi/pack_metadata.json
Labels: docs-approved

#34640 SymantecCloudSOC: fix date format error
  Packs/SymantecCloudSOC/Integrations/SymantecCloudSOCEventCollector/SymantecCloudSOCEventCollector.py
  Packs/SymantecCloudSOC/Integrations/SymantecCloudSOCEventCollector/SymantecCloudSOCEventCollector.yml
  Packs/SymantecCloudSOC/Integrations/SymantecCloudSOCEventCollector/SymantecCloudSOCEventCollector_test.py
  Packs/SymantecCloudSOC/ReleaseNotes/1_0_8.md
  Packs/SymantecCloudSOC/pack_metadata.json
Labels: docs-approved

#34724 MicrosoftDefnderForCloud: update documentation
  Packs/AzureSecurityCenter/Integrations/MicrosoftDefenderForCloudEventCollector/MicrosoftDefenderForCloudEventCollector_description.md
  Packs/AzureSecurityCenter/ReleaseNotes/2_0_27.md
  Packs/AzureSecurityCenter/pack_metadata.json
Labels: docs-approved

#34652 Get list row
  Packs/CommonScripts/ReleaseNotes/1_15_6.md
  Packs/CommonScripts/Scripts/GetListRow/GetListRow.py
  Packs/CommonScripts/Scripts/GetListRow/GetListRow.yml
  Packs/CommonScripts/Scripts/GetListRow/GetListRow_test.py
  Packs/CommonScripts/Scripts/GetListRow/README.md
  Packs/CommonScripts/pack_metadata.json
Labels: docs-approved

#34443 Qradar delete and cancel searches
  Packs/QRadar/Integrations/QRadar_v3/QRadar_v3.py
  Packs/QRadar/Integrations/QRadar_v3/QRadar_v3.yml
  Packs/QRadar/Integrations/QRadar_v3/QRadar_v3_test.py
  Packs/QRadar/Integrations/QRadar_v3/README.md
  Packs/QRadar/Integrations/QRadar_v3/command_examples.txt
  Packs/QRadar/Integrations/QRadar_v3/test_data/command_test_data.json
  Packs/QRadar/ReleaseNotes/2_4_59.md
  Packs/QRadar/pack_metadata.json
Labels: docs-approved

#34730 Infoblox Update
  Packs/Infoblox/ParsingRules/InfobloxParsingRules/InfobloxParsingRules.xif
  Packs/Infoblox/ReleaseNotes/1_1_2.md
  Packs/Infoblox/pack_metadata.json
Labels: docs-approved

#34653 Fix unittest in CommonServerPython script
  Packs/Base/Scripts/CommonServerPython/CommonServerPython_test.py
Labels: docs-approved

#34709 [CortexXpanse] - New Xpanse Feed
  Packs/CortexXpanse/.secrets-ignore
  Packs/CortexXpanse/Integrations/FeedXpanse/FeedXpanse.py
  Packs/CortexXpanse/Integrations/FeedXpanse/FeedXpanse.yml
  Packs/CortexXpanse/Integrations/FeedXpanse/FeedXpanse_description.md
  Packs/CortexXpanse/Integrations/FeedXpanse/FeedXpanse_image.png
  Packs/CortexXpanse/Integrations/FeedXpanse/FeedXpanse_test.py
  Packs/CortexXpanse/Integrations/FeedXpanse/README.md
  Packs/CortexXpanse/Integrations/FeedXpanse/command_examples
  Packs/CortexXpanse/Integrations/FeedXpanse/test_data/raw_response.py
  Packs/CortexXpanse/ReleaseNotes/1_2_0.md
  Packs/CortexXpanse/pack_metadata.json
Labels: Contribution, docs-approved, Contribution Form Filled, Community, Xsoar Support Level, External PR

#34732 XSUP 37940 aruba clearpass
  Packs/HPEArubaClearPass/ModelingRules/HPEArubaClearPass/HPEArubaClearPass.xif
  Packs/HPEArubaClearPass/ModelingRules/HPEArubaClearPass/HPEArubaClearPass_schema.json
  Packs/HPEArubaClearPass/ParsingRules/HPEArubaClearPass/HPEArubaClearPass.xif
  Packs/HPEArubaClearPass/ReleaseNotes/1_0_27.md
  Packs/HPEArubaClearPass/pack_metadata.json
Labels: docs-approved

#34667 [Azure Log Analytics] Add High GCC support
  Packs/AzureLogAnalytics/.pack-ignore
  Packs/AzureLogAnalytics/Integrations/AzureLogAnalytics/AzureLogAnalytics.py
  Packs/AzureLogAnalytics/Integrations/AzureLogAnalytics/AzureLogAnalytics.yml
  Packs/AzureLogAnalytics/Integrations/AzureLogAnalytics/AzureLogAnalytics_test.py
  Packs/AzureLogAnalytics/ReleaseNotes/1_1_33.md
  Packs/AzureLogAnalytics/pack_metadata.json
Labels: docs-approved

#34759 Update clean_stale_branches.yml
  .github/workflows/clean_stale_branches.yml
Labels: docs-approved

#32423 [Integration] - Mattermost V2
  Packs/Mattermost/.secrets-ignore
  Packs/Mattermost/Integrations/MattermostV2/MattermostV2.py
  Packs/Mattermost/Integrations/MattermostV2/MattermostV2.yml
  Packs/Mattermost/Integrations/MattermostV2/MattermostV2_description.md
  Packs/Mattermost/Integrations/MattermostV2/MattermostV2_image.png
  Packs/Mattermost/Integrations/MattermostV2/MattermostV2_test.py
  Packs/Mattermost/Integrations/MattermostV2/README.md
  Packs/Mattermost/Integrations/MattermostV2/command_examples
  Packs/Mattermost/Integrations/MattermostV2/test_data/create_channel_response.json
  Packs/Mattermost/Integrations/MattermostV2/test_data/create_post_response.json
  Packs/Mattermost/Integrations/MattermostV2/test_data/get_bot_response.json
  Packs/Mattermost/Integrations/MattermostV2/test_data/get_team_response.json
  Packs/Mattermost/Integrations/MattermostV2/test_data/list_channels_response.json
  Packs/Mattermost/Integrations/MattermostV2/test_data/list_users_response.json
  Packs/Mattermost/Integrations/MattermostV2/test_data/posted_data_bot.json
  Packs/Mattermost/Integrations/MattermostV2/test_data/posted_data_user.json
  Packs/Mattermost/Integrations/MattermostV2/test_data/send_file_response.json
  Packs/Mattermost/ReleaseNotes/2_0_0.json
  Packs/Mattermost/ReleaseNotes/2_0_0.md
  Packs/Mattermost/Scripts/MattermostAskUser/MattermostAskUser.py
  Packs/Mattermost/Scripts/MattermostAskUser/MattermostAskUser.yml
  Packs/Mattermost/Scripts/MattermostAskUser/MattermostAskUser_test.py
  Packs/Mattermost/Scripts/MattermostAskUser/README.md
  Packs/Mattermost/TestPlaybooks/MattermostAskUser_testplaybook.yml
  Packs/Mattermost/TestPlaybooks/Mattermost_V2_-_testplaybook.yml
  Packs/Mattermost/pack_metadata.json
  Tests/conf.json
Labels: docs-approved, ForceMerge

#34598 MITRE ATT&CK - Save intrusion-sets as threat-actor indicators parameter
  Packs/FeedMitreAttackv2/Integrations/FeedMitreAttackv2/FeedMitreAttackv2.py
  Packs/FeedMitreAttackv2/Integrations/FeedMitreAttackv2/FeedMitreAttackv2.yml
  Packs/FeedMitreAttackv2/Integrations/FeedMitreAttackv2/FeedMitreAttackv2_test.py
  Packs/FeedMitreAttackv2/Integrations/FeedMitreAttackv2/test_data/mitre_test_data.py
  Packs/FeedMitreAttackv2/ReleaseNotes/1_1_38.md
  Packs/FeedMitreAttackv2/pack_metadata.json
Labels: Contribution, docs-approved

#34745 Update XSOAR Engineer Training Docker Image
  Packs/XSOAR_Engineer_Training/Integrations/XSOAREngineerTraining/XSOAREngineerTraining.yml
  Packs/XSOAR_Engineer_Training/ReleaseNotes/1_0_2.md
  Packs/XSOAR_Engineer_Training/pack_metadata.json
Labels: docs-approved

#34762 Fixed links to graphics
  Packs/CortexAttackSurfaceManagement/README.md
Labels: docs-approved

#34327 Support multiple drilldown searches response
  Packs/SplunkPy/.pack-ignore
  Packs/SplunkPy/Integrations/SplunkPy/README.md
  Packs/SplunkPy/Integrations/SplunkPy/SplunkPy.py
  Packs/SplunkPy/Integrations/SplunkPy/SplunkPy.yml
  Packs/SplunkPy/Integrations/SplunkPy/SplunkPy_description.md
  Packs/SplunkPy/Integrations/SplunkPy/SplunkPy_test.py
  Packs/SplunkPy/ReleaseNotes/3_1_28.json
  Packs/SplunkPy/ReleaseNotes/3_1_28.md
  Packs/SplunkPy/Scripts/SplunkShowDrilldown/SplunkShowDrilldown.py
  Packs/SplunkPy/Scripts/SplunkShowDrilldown/SplunkShowDrilldown.yml
  Packs/SplunkPy/Scripts/SplunkShowDrilldown/SplunkShowDrilldown_test.py
  Packs/SplunkPy/pack_metadata.json
Labels: docs-approved

#34742 fix pyEWS TPB
  Packs/MicrosoftExchangeOnPremise/TestPlaybooks/playbook-pyEWS_Test.yml
  Tests/conf.json
Labels: docs-approved

#34774 Implement support for other regions
  Packs/CheckPointHEC/Integrations/CheckPointHEC/CheckPointHEC.yml
  Packs/CheckPointHEC/Integrations/CheckPointHEC/CheckPointHEC_description.md
  Packs/CheckPointHEC/Integrations/CheckPointHEC/README.md
  Packs/CheckPointHEC/ReleaseNotes/1_1_3.md
  Packs/CheckPointHEC/pack_metadata.json
Labels: Contribution, docs-approved, Partner, Contribution Form Filled, Partner Support Level, External PR, Partner-Approved

#34763 VMware ESXi Parsing Update
  Packs/VMwareESXi/ParsingRules/VMwareESXiParsingRules/VMwareESXiParsingRules.xif
  Packs/VMwareESXi/ReleaseNotes/1_0_5.md
  Packs/VMwareESXi/pack_metadata.json
Labels: docs-approved

#34756 Get Original Email - EWS v2 - test - fix
  Packs/MicrosoftExchangeOnPremise/TestPlaybooks/playbook-Get_Original_Email_-_EWS_v2_-_test.yml
Labels: docs-approved

#34747 Fixes For 'IOC Alert' XSIAM Playbook
  Packs/Core/Playbooks/playbook-IOC_Alert.yml
  Packs/Core/Playbooks/playbook-IOC_Alert_README.md
  Packs/Core/ReleaseNotes/3_0_35.md
  Packs/Core/doc_files/IOC_Alert.png
  Packs/Core/pack_metadata.json
Labels: docs-approved

#34675 CS Falcon - Reopen incident statuses
  Packs/CrowdStrikeFalcon/Integrations/CrowdStrikeFalcon/CrowdStrikeFalcon.py
  Packs/CrowdStrikeFalcon/Integrations/CrowdStrikeFalcon/CrowdStrikeFalcon.yml
  Packs/CrowdStrikeFalcon/Integrations/CrowdStrikeFalcon/CrowdStrikeFalcon_test.py
  Packs/CrowdStrikeFalcon/Integrations/CrowdStrikeFalcon/README.md
  Packs/CrowdStrikeFalcon/Integrations/CrowdStrikeFalcon/test_data/input_data.py
  Packs/CrowdStrikeFalcon/ReleaseNotes/1_13_10.md
  Packs/CrowdStrikeFalcon/pack_metadata.json
Labels: docs-approved

#34777 Fix for 'Identity Analytics - Alert Handling' XSIAM playbook
  Packs/Core/Playbooks/playbook-Identity_Analytics_-_Alert_Handling.yml
  Packs/Core/Playbooks/playbook-Identity_Analytics_-_Alert_Handling_README.md
  Packs/Core/ReleaseNotes/3_0_36.md
  Packs/Core/pack_metadata.json
Labels: docs-approved

#34788 Skip sending Slack Notifications for Tests
  .github/workflows/handle-new-external-pr.yml
Labels: docs-approved

#34729 Deprecate O365 Defender SafeLinks - Single User
  Packs/Microsoft365Defender/Integrations/O365DefenderSafeLinksSingleUser/O365DefenderSafeLinksSingleUser.yml
  Packs/Microsoft365Defender/ReleaseNotes/4_5_27.md
  Packs/Microsoft365Defender/pack_metadata.json
Labels: docs-approved

#34691 [API Execution Metrics] Add Main Widget & Remove Integration Widgets
  Packs/CommonDashboards/Dashboards/dashboard-APIExecutionMetrics.json
  Packs/CommonDashboards/ReleaseNotes/1_7_0.md
  Packs/CommonDashboards/pack_metadata.json
Labels: docs-approved

#34593 New Integration: Chronicle Streaming API
  Packs/GoogleChronicleBackstory/.pack-ignore
  Packs/GoogleChronicleBackstory/Classifiers/classifier-mapper-incoming-Chronicle.json
  Packs/GoogleChronicleBackstory/Integrations/GoogleChronicleBackstory/GoogleChronicleBackstory.py
  Packs/GoogleChronicleBackstory/Integrations/GoogleChronicleBackstory/GoogleChronicleBackstory.yml
  Packs/GoogleChronicleBackstory/Integrations/GoogleChronicleBackstoryStreamingAPI/GoogleChronicleBackstoryStreamingAPI.py
  Packs/GoogleChronicleBackstory/Integrations/GoogleChronicleBackstoryStreamingAPI/GoogleChronicleBackstoryStreamingAPI.yml
  Packs/GoogleChronicleBackstory/Integrations/GoogleChronicleBackstoryStreamingAPI/GoogleChronicleBackstoryStreamingAPI_dark.svg
  Packs/GoogleChronicleBackstory/Integrations/GoogleChronicleBackstoryStreamingAPI/GoogleChronicleBackstoryStreamingAPI_description.md
  Packs/GoogleChronicleBackstory/Integrations/GoogleChronicleBackstoryStreamingAPI/GoogleChronicleBackstoryStreamingAPI_image.png
  Packs/GoogleChronicleBackstory/Integrations/GoogleChronicleBackstoryStreamingAPI/GoogleChronicleBackstoryStreamingAPI_light.svg
  Packs/GoogleChronicleBackstory/Integrations/GoogleChronicleBackstoryStreamingAPI/GoogleChronicleBackstoryStreamingAPI_test.py
  Packs/GoogleChronicleBackstory/Integrations/GoogleChronicleBackstoryStreamingAPI/README.md
  Packs/GoogleChronicleBackstory/Integrations/GoogleChronicleBackstoryStreamingAPI/test_data/steam_detection_outputs.json
  Packs/GoogleChronicleBackstory/Integrations/GoogleChronicleBackstoryStreamingAPI/test_data/stream_detections.txt
  Packs/GoogleChronicleBackstory/Integrations/GoogleChronicleBackstoryStreamingAPI/test_data/stream_detections_empty.txt
  Packs/GoogleChronicleBackstory/Integrations/GoogleChronicleBackstoryStreamingAPI/test_data/stream_detections_error.txt
  Packs/GoogleChronicleBackstory/Integrations/GoogleChronicleBackstoryStreamingAPI/test_data/stream_detections_error_2.txt
  Packs/GoogleChronicleBackstory/Layouts/layoutscontainer-Chronicle_Rule_Detection.json
  Packs/GoogleChronicleBackstory/ReleaseNotes/4_0_0.md
  Packs/GoogleChronicleBackstory/pack_metadata.json
Labels: Contribution, docs-approved, Partner, Contribution Form Filled, Partner Support Level, External PR, Security Review, Partner-Approved

#34783 Fix links to graphics in Pack Readme
  Packs/CortexAttackSurfaceManagement/README.md
Labels: docs-approved

#34765 Print to incident and other alert's waroom
  Packs/CommonScripts/ReleaseNotes/1_15_8.md
  Packs/CommonScripts/Scripts/PrintToAlert/PrintToAlert.py
  Packs/CommonScripts/Scripts/PrintToAlert/PrintToAlert.yml
  Packs/CommonScripts/Scripts/PrintToAlert/PrintToAlert_test.py
  Packs/CommonScripts/Scripts/PrintToAlert/README.md
  Packs/CommonScripts/Scripts/PrintToParentIncident/PrintToParentIncident.py
  Packs/CommonScripts/Scripts/PrintToParentIncident/PrintToParentIncident.yml
  Packs/CommonScripts/Scripts/PrintToParentIncident/PrintToParentIncident_test.py
  Packs/CommonScripts/Scripts/PrintToParentIncident/README.md
  Packs/CommonScripts/pack_metadata.json
Labels: docs-approved

#34485 [QRadar v3] Metrics
  Packs/QRadar/Integrations/QRadar_v3/QRadar_v3.py
  Packs/QRadar/Integrations/QRadar_v3/README.md
  Packs/QRadar/ReleaseNotes/2_5_0.md
  Packs/QRadar/pack_metadata.json
Labels: docs-approved

#34768 MyToDoTasksWidget: fix broken link
  Packs/CommonWidgets/ReleaseNotes/1_2_51.md
  Packs/CommonWidgets/Scripts/MyToDoTasksWidget/MyToDoTasksWidget.py
  Packs/CommonWidgets/Scripts/MyToDoTasksWidget/MyToDoTasksWidget.yml
  Packs/CommonWidgets/Scripts/MyToDoTasksWidget/MyToDoTasksWidget_test.py
  Packs/CommonWidgets/pack_metadata.json
Labels: docs-approved

#34818 special_lucin_char_indicators_from_cache
  Packs/CommonScripts/ReleaseNotes/1_15_9.md
  Packs/CommonScripts/Scripts/GetIndicatorDBotScoreFromCache/GetIndicatorDBotScoreFromCache.py
  Packs/CommonScripts/Scripts/GetIndicatorDBotScoreFromCache/GetIndicatorDBotScoreFromCache_test.py
  Packs/CommonScripts/pack_metadata.json
Labels: docs-approved

#34772 [CortexXpanse] Integration README Formatting
  Packs/CortexXpanse/Integrations/FeedXpanse/README.md
Labels: Contribution, docs-approved, Contribution Form Filled, Community, Xsoar Support Level, External PR, TIM Review

#34748 Removed username display in the configuration form and kept API key(password)
  Packs/SafeBreach/Integrations/SafeBreach/README.md
  Packs/SafeBreach/Integrations/SafeBreach/SafeBreach.yml
  Packs/SafeBreach/ReleaseNotes/1_4_3.md
  Packs/SafeBreach/pack_metadata.json
Labels: Contribution, docs-approved, Partner, Contribution Form Filled, pending-contributor, Partner Support Level, External PR, Partner-Approved

#34832 added validations to validation_config file
  validation_config.toml
Labels: docs-approved

#34833 [MS teams] update URLs
  Packs/MicrosoftTeams/Integrations/MicrosoftTeams/MicrosoftTeams.yml
  Packs/MicrosoftTeams/Integrations/MicrosoftTeams/MicrosoftTeams_description.md
  Packs/MicrosoftTeams/Integrations/MicrosoftTeams/README.md
  Packs/MicrosoftTeams/ReleaseNotes/1_4_62.md
  Packs/MicrosoftTeams/pack_metadata.json
Labels: docs-approved

#34829 Change Forescout Pack Name
  Packs/Forescout/ReleaseNotes/1_0_10.md
  Packs/Forescout/pack_metadata.json
Labels: docs-approved

#34834 fix
  Packs/GoogleChronicleBackstory/pack_metadata.json
Labels: docs-approved

#34839 Deprecate Slack Test Playbook used for slackv2 integration which is deprecated
  Packs/Slack/TestPlaybooks/playbook-Slack_TestPlaybook.yml
  Tests/conf.json
Labels: docs-approved

#34828 removed extra args from readmem
  Packs/MicrosoftGraphIdentityandAccess/Integrations/MicrosoftGraphIdentityandAccess/MicrosoftGraphIdentityandAccess.yml
  Packs/MicrosoftGraphIdentityandAccess/Integrations/MicrosoftGraphIdentityandAccess/README.md
  Packs/MicrosoftGraphIdentityandAccess/ReleaseNotes/1_2_52.md
  Packs/MicrosoftGraphIdentityandAccess/pack_metadata.json
Labels: docs-approved

#34388 PAN-OS Correlation Logs
  Packs/PAN-OS/Classifiers/classifier-Panorama_Mapper.json
  Packs/PAN-OS/IncidentTypes/incidenttype-Correlation.json
  Packs/PAN-OS/IncidentTypes/incidenttype-Data.json
  Packs/PAN-OS/IncidentTypes/incidenttype-Decryption.json
  Packs/PAN-OS/IncidentTypes/incidenttype-System.json
  Packs/PAN-OS/IncidentTypes/incidenttype-Threat.json
  Packs/PAN-OS/IncidentTypes/incidenttype-Traffic.json
  Packs/PAN-OS/IncidentTypes/incidenttype-URL.json
  Packs/PAN-OS/IncidentTypes/incidenttype-WildfireSubmissions.json
  Packs/PAN-OS/Integrations/Panorama/Panorama.py
  Packs/PAN-OS/Integrations/Panorama/Panorama.yml
  Packs/PAN-OS/Integrations/Panorama/Panorama_test.py
  Packs/PAN-OS/Integrations/Panorama/test_data/corr_logs.json
  Packs/PAN-OS/Integrations/Panorama/test_data/fetch_incidents_input.py
  Packs/PAN-OS/ReleaseNotes/2_1_29.md
  Packs/PAN-OS/pack_metadata.json
Labels: docs-approved

#34838 [CoretxXDRIR] edited the tooltip
  Packs/CortexXDR/Integrations/CortexXDRIR/CortexXDRIR.yml
  Packs/CortexXDR/Integrations/CortexXDRIR/README.md
  Packs/CortexXDR/ReleaseNotes/6_1_44.md
  Packs/CortexXDR/pack_metadata.json
  validation_config.toml
Labels: docs-approved

#34761 [Azure Log Analytics] Update README.md
  Packs/AzureLogAnalytics/Integrations/AzureLogAnalytics/README.md
Labels: docs-approved

#34858 Update README.md
  Packs/DeveloperTools/Integrations/CreateIncidents/README.md
Labels: Contribution, docs-approved, Community Support Level, External PR

#34764 add parameter to Microsoft defender cloud apps event collector
  Packs/MicrosoftCloudAppSecurity/Integrations/MicrosoftDefenderEventCollector/MicrosoftDefenderEventCollector.py
  Packs/MicrosoftCloudAppSecurity/Integrations/MicrosoftDefenderEventCollector/MicrosoftDefenderEventCollector.yml
  Packs/MicrosoftCloudAppSecurity/Integrations/MicrosoftDefenderEventCollector/README.md
  Packs/MicrosoftCloudAppSecurity/ReleaseNotes/2_2_0.md
  Packs/MicrosoftCloudAppSecurity/pack_metadata.json
Labels: docs-approved

#34738 added before query param to Armis event collector
  Packs/Armis/Integrations/ArmisEventCollector/ArmisEventCollector.py
  Packs/Armis/Integrations/ArmisEventCollector/ArmisEventCollector.yml
  Packs/Armis/Integrations/ArmisEventCollector/ArmisEventCollector_test.py
  Packs/Armis/Integrations/ArmisEventCollector/README.md
  Packs/Armis/ReleaseNotes/1_1_15.json
  Packs/Armis/ReleaseNotes/1_1_15.md
  Packs/Armis/pack_metadata.json
Labels: docs-approved

#34716 demisto/pcap-miner:1.0.0.96695 | 0-100 | PR batch #1/1
  Packs/PcapAnalysis/Scripts/PcapExtractStreams/PcapExtractStreams.yml
Labels: auto-update-docker

#34718 demisto/pycountry:1.0.0.96960 | 0-100 | PR batch #1/1
  Packs/CyCognito/Scripts/ThreeDigitAlphaCountryCodeToCountryName/ThreeDigitAlphaCountryCodeToCountryName.yml
Labels: auto-update-docker

#34717 demisto/py3-tools:1.0.0.96976 | 0-100 | PR batch #1/1
  Packs/FeedIntel471/Integrations/Intel471WatcherAlerts/Intel471WatcherAlerts.yml
Labels: auto-update-docker

#34719 demisto/xsoar-tools:1.0.0.96723 | 0-100 | PR batch #1/1
  Packs/ContentManagement/Scripts/ConfigurationSetup/ConfigurationSetup.yml
  Packs/ContentManagement/Scripts/ListCreator/ListCreator.yml
  Packs/CovalenceForSecurityProviders/Integrations/CovalenceForSecurityProviders/CovalenceForSecurityProviders.yml
Labels: auto-update-docker

#34538 Adding AdoptionMetricts script to CommonDashboard
  Packs/CommonDashboards/.pack-ignore
  Packs/CommonDashboards/.secrets-ignore
  Packs/CommonDashboards/ReleaseNotes/1_7_1.md
  Packs/CommonDashboards/Scripts/AdoptionMetrics/AdoptionMetrics.py
  Packs/CommonDashboards/Scripts/AdoptionMetrics/AdoptionMetrics.yml
  Packs/CommonDashboards/Scripts/AdoptionMetrics/AdoptionMetrics_test.py
  Packs/CommonDashboards/Scripts/AdoptionMetrics/README.md
  Packs/CommonDashboards/pack_metadata.json
Labels: Contribution, docs-approved, Contribution Form Filled, Internal PR

#34715 demisto/ansible-runner:1.0.0.96928 | 0-100 | PR batch #1/1
  Packs/AnsibleCiscoIOS/Integrations/AnsibleCiscoIOS/AnsibleCiscoIOS.yml
Labels: auto-update-docker

#34846 Remove redundant password.
  Packs/AWS-SNS/Integrations/AWSSNS/AWSSNS.py
  Packs/AWS-SNS/Integrations/AWSSNS/AWSSNS.yml
  Packs/AWS-SNS/Integrations/AWSSNS/README.md
  Packs/AWS-SNS/ReleaseNotes/1_0_16.md
  Packs/AWS-SNS/pack_metadata.json
Labels: docs-approved

#34845 Move misplaced files (InvalidDepthOneFile)
  .pre-commit-config_template.yaml
  Packs/ArcSightXML/Integrations/ArcSightXML/ArcSightXML.py
  Packs/ArcSightXML/Integrations/ArcSightXML/ArcSightXML.yml
  Packs/ArcSightXML/Integrations/ArcSightXML/ArcSightXML_image.png
  Packs/ArcSightXML/Integrations/ArcSightXML/README.md
  Packs/ArcSightXML/Integrations/integration-ArcSightXML.yml
  Packs/Cofense-Intelligence/Integrations/CofenseIntelligence/command_examples
  Packs/DelineaDSV/Integrations/README.md
  Packs/GLIMPS_Detect/Integrations/README.md
  Packs/GoogleMaps/Integrations/.secrets-ignore
  Packs/Orca/Integrations/Orca/command_examples.txt
  Packs/ThreatExchange/Integrations/ThreatExchange/examples.txt
  Packs/Venafi/Integrations/command_examples
Labels: ForceMerge

#34864 Cyberark epm add instance param
  Packs/CyberArkEPM/Integrations/CyberArkEPMEventCollector/CyberArkEPMEventCollector.py
  Packs/CyberArkEPM/Integrations/CyberArkEPMEventCollector/CyberArkEPMEventCollector.yml
  Packs/CyberArkEPM/Integrations/CyberArkEPMEventCollector/CyberArkEPMEventCollector_test.py
  Packs/CyberArkEPM/ReleaseNotes/1_0_2.md
  Packs/CyberArkEPM/pack_metadata.json
Labels: docs-approved

#34817 MITRE IDs pack - update scripts dir name
  Packs/FeedMitreAttack/ReleaseNotes/1_2_3.md
  Packs/FeedMitreAttack/Scripts/MitreIDLayoutDynamicSection/MitreIDLayoutDynamicSection.py
  Packs/FeedMitreAttack/Scripts/MitreIDLayoutDynamicSection/MitreIDLayoutDynamicSection.yml
  Packs/FeedMitreAttack/Scripts/MitreNameLayoutDynamicSection/MitreNameLayoutDynamicSection.py
  Packs/FeedMitreAttack/Scripts/MitreNameLayoutDynamicSection/MitreNameLayoutDynamicSection.yml
  Packs/FeedMitreAttack/pack_metadata.json
Labels: docs-approved

#34686 New XSIAM Dashboards/Reports
  Packs/XSIAMCompliance_GDPR/.pack-ignore
  Packs/XSIAMCompliance_GDPR/.secrets-ignore
  Packs/XSIAMCompliance_GDPR/README.md
  Packs/XSIAMCompliance_GDPR/pack_metadata.json
  Packs/XSIAMCompliance_ISO_27001/.pack-ignore
  Packs/XSIAMCompliance_ISO_27001/.secrets-ignore
  Packs/XSIAMCompliance_ISO_27001/README.md
  Packs/XSIAMCompliance_ISO_27001/pack_metadata.json
Labels: Contribution, docs-approved

#34865 Microsoft WSUS readme modifications
  Packs/MicrosoftWSUS/README.md
Labels: docs-approved

#34867 fix arcsight image
  Packs/ArcSightXML/Integrations/ArcSightXML/ArcSightXML.py
  Packs/ArcSightXML/Integrations/ArcSightXML/ArcSightXML_image.png
  Packs/ArcSightXML/ReleaseNotes/1_0_7.md
  Packs/ArcSightXML/pack_metadata.json
Labels: docs-approved

#34863 MapRangeValues - XSUP 38471
  Packs/FiltersAndTransformers/ReleaseNotes/1_2_74.md
  Packs/FiltersAndTransformers/Scripts/MapRangeValues/MapRangeValues.py
  Packs/FiltersAndTransformers/Scripts/MapRangeValues/MapRangeValues_test.py
  Packs/FiltersAndTransformers/TestPlaybooks/playbook-MapRangeValues_Test.yml
  Packs/FiltersAndTransformers/pack_metadata.json
Labels: docs-approved

#34880 Remove script_info.txt creation
  Packs/Base/ReleaseNotes/1_34_12.md
  Packs/Base/Scripts/CommonServerPython/CommonServerPython.py
  Packs/Base/pack_metadata.json
Labels: docs-approved

#34876 Extract hyperlinks pptx issue
  Packs/CommonScripts/ReleaseNotes/1_15_10.md
  Packs/CommonScripts/Scripts/ExtractHyperlinksFromOfficeFiles/ExtractHyperlinksFromOfficeFiles.py
  Packs/CommonScripts/Scripts/ExtractHyperlinksFromOfficeFiles/ExtractHyperlinksFromOfficeFiles_test.py
  Packs/CommonScripts/Scripts/ExtractHyperlinksFromOfficeFiles/test_data/p3.pptx
  Packs/CommonScripts/pack_metadata.json
Labels: docs-approved

#34386 Mimecast integration ciac 9090
  Packs/Mimecast/Integrations/MimecastV2/MimecastV2.py
  Packs/Mimecast/Integrations/MimecastV2/MimecastV2.yml
  Packs/Mimecast/Integrations/MimecastV2/MimecastV2_description.md
  Packs/Mimecast/Integrations/MimecastV2/MimecastV2_test.py
  Packs/Mimecast/Integrations/MimecastV2/README.md
  Packs/Mimecast/Integrations/MimecastV2/command_examples
  Packs/Mimecast/Integrations/MimecastV2/test_data/create_antispoofing_bypass_policy_response.json
  Packs/Mimecast/Integrations/MimecastV2/test_data/create_block_sender_policy_response.json
  Packs/Mimecast/Integrations/MimecastV2/test_data/create_block_sender_policy_result_outputs.json
  Packs/Mimecast/Integrations/MimecastV2/test_data/create_block_sender_policy_result_readable_output.md
  Packs/Mimecast/Integrations/MimecastV2/test_data/get_archive_search_logs_response.json
  Packs/Mimecast/Integrations/MimecastV2/test_data/get_search_logs_response.json
  Packs/Mimecast/Integrations/MimecastV2/test_data/get_view_logs_response.json
  Packs/Mimecast/Integrations/MimecastV2/test_data/list_account_response.json
  Packs/Mimecast/Integrations/MimecastV2/test_data/list_policies_response.json
  Packs/Mimecast/Integrations/MimecastV2/test_data/update_address_alteration_policy_response.json
  Packs/Mimecast/Integrations/MimecastV2/test_data/update_antispoofing_bypass_policy_response.json
  Packs/Mimecast/ReleaseNotes/2_3_0.md
  Packs/Mimecast/TestPlaybooks/playbook-Mimecast_test_api_2.0.yml
  Packs/Mimecast/pack_metadata.json
  Tests/conf.json
Labels: docs-approved

#34827 [ASM] Adding Slack Messages
  Packs/CortexAttackSurfaceManagement/Playbooks/Cortex_ASM_-_ASM_Alert.yml
  Packs/CortexAttackSurfaceManagement/Playbooks/Cortex_ASM_-_ASM_Alert_README.md
  Packs/CortexAttackSurfaceManagement/Playbooks/Cortex_ASM_-_Instant_Message.yml
  Packs/CortexAttackSurfaceManagement/Playbooks/Cortex_ASM_-_Instant_Message_README.md
  Packs/CortexAttackSurfaceManagement/Playbooks/Cortex_ASM_-_Remediation_Path_Rules.yml
  Packs/CortexAttackSurfaceManagement/Playbooks/Cortex_ASM_-_Remediation_Path_Rules_README.md
  Packs/CortexAttackSurfaceManagement/README.md
  Packs/CortexAttackSurfaceManagement/ReleaseNotes/1_7_41.md
  Packs/CortexAttackSurfaceManagement/doc_files/Cortex_ASM_-_ASM_Alert.png
  Packs/CortexAttackSurfaceManagement/doc_files/Cortex_ASM_-_Instant_Message.png
  Packs/CortexAttackSurfaceManagement/doc_files/Cortex_ASM_-_Remediation_Path_Rules.png
  Packs/CortexAttackSurfaceManagement/pack_metadata.json
  Packs/Slack/Integrations/SlackEventCollector/SlackEventCollector.yml
  Packs/Slack/Integrations/SlackV3/SlackV3.yml
  Packs/Slack/Integrations/Slack_IAM/Slack_IAM.yml
  Packs/Slack/ReleaseNotes/3_4_16.md
  Packs/Slack/Scripts/GetSlackBlockBuilderResponse/GetSlackBlockBuilderResponse.yml
  Packs/Slack/Scripts/SlackAsk/SlackAsk.yml
  Packs/Slack/pack_metadata.json
Labels: Contribution, docs-approved, Contribution Form Filled, Community, Xsoar Support Level, External PR, Security Review

#34881 CS Falcon -readme update
  Packs/CrowdStrikeFalcon/Integrations/CrowdStrikeFalcon/CrowdStrikeFalcon.yml
  Packs/CrowdStrikeFalcon/Integrations/CrowdStrikeFalcon/CrowdStrikeFalcon_test.py
  Packs/CrowdStrikeFalcon/Integrations/CrowdStrikeFalcon/README.md
  Packs/CrowdStrikeFalcon/ReleaseNotes/1_13_11.md
  Packs/CrowdStrikeFalcon/pack_metadata.json
Labels: docs-approved

#34884 fixed pre-commit autopep8 malformed packs
  Packs/SuspiciousDomainHunting/ReleaseNotes/1_0_2.md
  Packs/SuspiciousDomainHunting/Scripts/DisplaySiteCategory/DisplaySiteCategory.py
  Packs/SuspiciousDomainHunting/Scripts/DisplaySiteCategory/DisplaySiteCategory.yml
  Packs/SuspiciousDomainHunting/Scripts/MSEScoreWidget/MSEScoreWidget.py
  Packs/SuspiciousDomainHunting/Scripts/RasterizeImageOriginal/RasterizeImageOriginal.py
  Packs/SuspiciousDomainHunting/Scripts/SSIMScoreWidget/SSIMScoreWidget.py
  Packs/SuspiciousDomainHunting/pack_metadata.json
Labels: docs-approved

#34799 YARA script - create relationships for YARA indicators
  Packs/Yara/.pack-ignore
  Packs/Yara/ReleaseNotes/1_0_7.md
  Packs/Yara/Scripts/CreateYARARuleIndicators/CreateYARARuleIndicators.py
  Packs/Yara/Scripts/CreateYARARuleIndicators/CreateYARARuleIndicators.yml
  Packs/Yara/Scripts/CreateYARARuleIndicators/CreateYARARuleIndicators_test.py
  Packs/Yara/pack_metadata.json
Labels: Contribution, docs-approved

#34886 Add setting to keep artifacts in GitLab jobs
  .gitlab/ci/.gitlab-ci.yml
Labels: docs-approved

#34512 Prisma logo update
  Packs/PrismaCloud/Integrations/PrismaCloudV2/PrismaCloudV2.yml
  Packs/PrismaCloud/Integrations/PrismaCloudV2/PrismaCloudV2_dark.svg
  Packs/PrismaCloud/Integrations/PrismaCloudV2/PrismaCloudV2_image.png
  Packs/PrismaCloud/Integrations/PrismaCloudV2/PrismaCloudV2_light.svg
  Packs/PrismaCloud/ReleaseNotes/4_3_6.md
  Packs/PrismaCloud/pack_metadata.json
  Packs/PrismaCloudCompute/Integrations/PaloAltoNetworks_PrismaCloudCompute/PaloAltoNetworks_PrismaCloudCompute.yml
  Packs/PrismaCloudCompute/Integrations/PaloAltoNetworks_PrismaCloudCompute/PaloAltoNetworks_PrismaCloudCompute_dark.svg
  Packs/PrismaCloudCompute/Integrations/PaloAltoNetworks_PrismaCloudCompute/PaloAltoNetworks_PrismaCloudCompute_image.png
  Packs/PrismaCloudCompute/Integrations/PaloAltoNetworks_PrismaCloudCompute/PaloAltoNetworks_PrismaCloudCompute_light.svg
  Packs/PrismaCloudCompute/ReleaseNotes/1_7_1.md
  Packs/PrismaCloudCompute/pack_metadata.json
Labels: docs-approved

#34887 Move GitHub workflow scripts
  .circleci/update_contribution_pack_in_base_branch.py
  .github/github_workflow_scripts/autobump_release_notes/autobump_rn.py
  .github/github_workflow_scripts/autobump_release_notes/skip_conditions.py
  .github/github_workflow_scripts/check_if_needs_to_fill_contribution_form.py
  .github/github_workflow_scripts/check_if_partner_approved_label_exists.py
  .github/github_workflow_scripts/check_protected_directories.py
  .github/github_workflow_scripts/create_internal_pr.py
  .github/github_workflow_scripts/github_workflow_scripts_tests/autobump_rn_test.py
  .github/github_workflow_scripts/github_workflow_scripts_tests/check_if_partner_approved_label_test.py
  .github/github_workflow_scripts/github_workflow_scripts_tests/handle_external_pr_test.py
  .github/github_workflow_scripts/github_workflow_scripts_tests/link_pr_to_jira_issue_test.py
  .github/github_workflow_scripts/github_workflow_scripts_tests/test_files/Packs/Pack1/pack_metadata.json
  .github/github_workflow_scripts/github_workflow_scripts_tests/test_files/Packs/Pack2/pack_metadata.json
  .github/github_workflow_scripts/handle_external_pr.py
  .github/github_workflow_scripts/jira_integration_scripts/link_pr_to_jira_issue.py
  .github/github_workflow_scripts/parse_junit_per_pack.py
  .github/github_workflow_scripts/request_contributor_review.py
  .github/github_workflow_scripts/run_secrets_detection.py
  .github/github_workflow_scripts/run_secrets_detection_get_playbook_status.py
  .github/github_workflow_scripts/send_slack_message.py
  .github/github_workflow_scripts/sync_contrib_base.py
  .github/github_workflow_scripts/utils.py
  .github/github_workflow_scripts/utils_test.py
  .github/workflows/autobump_rn.yml
  .github/workflows/check-contribution-form-filled.yml
  .github/workflows/check-contributor-pack.yml
  .github/workflows/check-partner-approved-label.yml
  .github/workflows/close_jira_issue_by_pr_merge.yml
  .github/workflows/create-internal-pr-from-external.yml
  .github/workflows/handle-new-external-pr.yml
  .github/workflows/link_edited_pr_to_jira_issue.yml
  .github/workflows/pre-commit-reuse.yml
  .github/workflows/protect-infra-directories.yml
  .github/workflows/run-secrets-detection.yml
  .github/workflows/sync-contribution-base-branch-on-change.yml
  .github/workflows/sync-contribution-base-branch.yml
Labels: ForceMerge

#34889 Update FireEyeNX.py
  Packs/FireEyeNX/Integrations/FireEyeNX/FireEyeNX.py
  Packs/FireEyeNX/Integrations/FireEyeNX/FireEyeNX_test.py
  Packs/FireEyeNX/ReleaseNotes/1_1_32.md
  Packs/FireEyeNX/pack_metadata.json
Labels: docs-approved, ForceMerge

#34877 change access to response
  Packs/ApiModules/ReleaseNotes/2_2_25.md
  Packs/ApiModules/Scripts/CoreIRApiModule/CoreIRApiModule.py
  Packs/ApiModules/Scripts/CoreIRApiModule/CoreIRApiModule.yml
  Packs/ApiModules/Scripts/CoreIRApiModule/CoreIRApiModule_test.py
  Packs/ApiModules/pack_metadata.json
  Packs/Core/ReleaseNotes/3_0_38.md
  Packs/Core/pack_metadata.json
  Packs/CortexXDR/ReleaseNotes/6_1_45.md
  Packs/CortexXDR/pack_metadata.json
  Packs/ctf01/ReleaseNotes/1_0_16.md
  Packs/ctf01/pack_metadata.json
Labels: docs-approved

#34909 fix contribution workflow scripts
  .github/github_workflow_scripts/autobump_release_notes/autobump_rn.py
  .github/github_workflow_scripts/check_if_partner_approved_label_exists.py
  .github/github_workflow_scripts/create_internal_pr.py
  .github/github_workflow_scripts/handle_external_pr.py
Labels: ForceMerge

#34903 skipping autopep8 on nightlies
  .pre-commit-config_template.yaml
Labels: docs-approved

#34906 Replace links so they link to master
  Packs/CortexAttackSurfaceManagement/README.md
Labels: docs-approved

#34619 SentinelOne V2- 3.2.25 - Updating Mappers
  Packs/SentinelOne/.pack-ignore
  Packs/SentinelOne/Classifiers/classifier-mapper-incoming-SentinelOne.json
  Packs/SentinelOne/IncidentFields/incidentfield-SentinelOne_Account_ID.json
  Packs/SentinelOne/IncidentFields/incidentfield-SentinelOne_Account_Name.json
  Packs/SentinelOne/IncidentFields/incidentfield-SentinelOne_Agent_NetworkStatus.json
  Packs/SentinelOne/IncidentFields/incidentfield-SentinelOne_Classification_Source.json
  Packs/SentinelOne/IncidentFields/incidentfield-SentinelOne_Cloud_Provider.json
  Packs/SentinelOne/IncidentFields/incidentfield-SentinelOne_Cloud_Provider_Account.json
  Packs/SentinelOne/IncidentFields/incidentfield-SentinelOne_Cloud_Provider_Image.json
  Packs/SentinelOne/IncidentFields/incidentfield-SentinelOne_Cloud_Provider_Instance_ID.json
  Packs/SentinelOne/IncidentFields/incidentfield-SentinelOne_Cloud_Provider_Instance_Size.json
  Packs/SentinelOne/IncidentFields/incidentfield-SentinelOne_Cloud_Provider_Location.json
  Packs/SentinelOne/IncidentFields/incidentfield-SentinelOne_Cloud_Provider_Network.json
  Packs/SentinelOne/IncidentFields/incidentfield-SentinelOne_Cloud_Provider_Resource_Group.json
  Packs/SentinelOne/IncidentFields/incidentfield-SentinelOne_Cloud_Provider_Role.json
  Packs/SentinelOne/IncidentFields/incidentfield-SentinelOne_Cloud_Provider_Security_Group.json
  Packs/SentinelOne/IncidentFields/incidentfield-SentinelOne_Cloud_Provider_Serviceaccount.json
  Packs/SentinelOne/IncidentFields/incidentfield-SentinelOne_Cloud_Provider_Subnet_Id.json
  Packs/SentinelOne/IncidentFields/incidentfield-SentinelOne_Cloud_Provider_Tag.json
  Packs/SentinelOne/IncidentFields/incidentfield-SentinelOne_Group_ID.json
  Packs/SentinelOne/IncidentFields/incidentfield-SentinelOne_Group_Name.json
  Packs/SentinelOne/IncidentFields/incidentfield-SentinelOne_Kubernetes_Cluster.json
  Packs/SentinelOne/IncidentFields/incidentfield-SentinelOne_Kubernetes_Controller_Kind.json
  Packs/SentinelOne/IncidentFields/incidentfield-SentinelOne_Kubernetes_Controller_Labels.json
  Packs/SentinelOne/IncidentFields/incidentfield-SentinelOne_Kubernetes_Controller_Name.json
  Packs/SentinelOne/IncidentFields/incidentfield-SentinelOne_Kubernetes_Namespace.json
  Packs/SentinelOne/IncidentFields/incidentfield-SentinelOne_Kubernetes_Namespace_Label.json
  Packs/SentinelOne/IncidentFields/incidentfield-SentinelOne_Kubernetes_Node.json
  Packs/SentinelOne/IncidentFields/incidentfield-SentinelOne_Kubernetes_Node_Label.json
  Packs/SentinelOne/IncidentFields/incidentfield-SentinelOne_Kubernetes_Pod.json
  Packs/SentinelOne/IncidentFields/incidentfield-SentinelOne_Kubernetes_Pod_Labels.json
  Packs/SentinelOne/IncidentFields/incidentfield-SentinelOne_Kubernetes_isQuarantine.json
  Packs/SentinelOne/IncidentFields/incidentfield-SentinelOne_NetworkInterface.json
  Packs/SentinelOne/IncidentFields/incidentfield-SentinelOne_Site_ID.json
  Packs/SentinelOne/IncidentFields/incidentfield-SentinelOne_Site_Name.json
  Packs/SentinelOne/IncidentFields/incidentfield-SentinelOne_Threat_StoryLine.json
  Packs/SentinelOne/IncidentTypes/incidenttype-SentinelOneIncident.json
  Packs/SentinelOne/Layouts/layoutscontainer-SentinelOne_Incident_Layout.json
  Packs/SentinelOne/ReleaseNotes/3_2_26.md
  Packs/SentinelOne/pack_metadata.json
Labels: Contribution, docs-approved, Partner, pending-demo, post-demo, Contribution Form Filled, Partner Support Level, External PR, Security Review, Partner-Approved

#34908 ReadPDFFileV2 open in binary mode
  Packs/CommonScripts/ReleaseNotes/1_15_11.md
  Packs/CommonScripts/Scripts/ReadPDFFileV2/README.md
  Packs/CommonScripts/Scripts/ReadPDFFileV2/ReadPDFFileV2.py
  Packs/CommonScripts/Scripts/ReadPDFFileV2/ReadPDFFileV2.yml
  Packs/CommonScripts/pack_metadata.json
Labels: docs-approved

#34823 CommonServerPython: truncate `return_error` messages
  Packs/Base/.pack-ignore
  Packs/Base/ReleaseNotes/1_34_13.md
  Packs/Base/Scripts/CommonServerPython/CommonServerPython.py
  Packs/Base/Scripts/CommonServerPython/CommonServerPython_test.py
  Packs/Base/pack_metadata.json
Labels: docs-approved

#34918 moved lo107 to warning
  validation_config.toml
Labels: docs-approved, ForceMerge

#34816 adding a fix to parsing_user_query
  Packs/FeedMISP/Integrations/FeedMISP/FeedMISP.py
  Packs/FeedMISP/Integrations/FeedMISP/FeedMISP.yml
  Packs/FeedMISP/Integrations/FeedMISP/FeedMISP_test.py
  Packs/FeedMISP/ReleaseNotes/1_0_33.md
  Packs/FeedMISP/pack_metadata.json
Labels: docs-approved

#34630 update to lates exchangelib version in ewsv2, remove pwsh
  Packs/MicrosoftExchangeOnPremise/Integrations/EWSv2/EWSv2.py
  Packs/MicrosoftExchangeOnPremise/Integrations/EWSv2/EWSv2.yml
  Packs/MicrosoftExchangeOnPremise/ReleaseNotes/2_1_7.json
  Packs/MicrosoftExchangeOnPremise/ReleaseNotes/2_1_7.md
  Packs/MicrosoftExchangeOnPremise/pack_metadata.json
Labels: docs-approved, ForceMerge

#34871 fixed an issue where test-module failed with oauth process.
  Packs/CommonScripts/.pack-ignore
  Packs/CommonScripts/ReleaseNotes/1_15_12.md
  Packs/CommonScripts/Scripts/FailedInstances/FailedInstances.js
  Packs/CommonScripts/pack_metadata.json
Labels: docs-approved

#34767 [Native Image] Update Candidate To `py3-native:8.6.0.98251`
  Tests/docker_native_image_config.json
Labels: docs-approved

#34879 Update base author image
  Packs/AHA/Author_image.png
  Packs/AWS-Enrichment-Remediation/Author_image.png
  Packs/BarracudaEmailProtection/Author_image.png
  Packs/BarracudaWAF/Author_image.png
  Packs/Barracuda_Cloudgen_Firewall/Author_image.png
  Packs/Base/Author_image.png
  Packs/CiscoUmbrellaReporting/Author_image.png
  Packs/Core/Author_image.png
  Packs/CortexAttackSurfaceManagement/Author_image.png
  Packs/CortexXpanse/Author_image.png
  Packs/DatadogCloudSIEM/Author_image.png
  Packs/FeedNVDv2/Author_image.png
  Packs/Gamma/Author_image.png
  Packs/GoogleSheets/Author_image.png
  Packs/HashiCorpTerraform/Author_image.png
  Packs/IronscalesEventCollector/Author_image.png
  Packs/OpenAI/Author_image.png
  Packs/SuspiciousDomainHunting/Author_image.png
  Packs/SymantecEDR/Author_image.png
  Packs/TeamCymru/Author_image.png
  Packs/ThreatQ/Author_image.png
  Packs/VerifyIPv4Indicator/Author_image.png
  Packs/Volatility/Author_image.png
Labels: docs-approved, ForceMerge

#34912 Cisco webex update authentication call to use body instead of url params
  Packs/CiscoSpark/Integrations/CiscoWebexEventCollector/CiscoWebexEventCollector.py
  Packs/CiscoSpark/Integrations/CiscoWebexEventCollector/CiscoWebexEventCollector.yml
  Packs/CiscoSpark/Integrations/CiscoWebexEventCollector/CiscoWebexEventCollector_test.py
  Packs/CiscoSpark/ReleaseNotes/1_0_7.md
  Packs/CiscoSpark/pack_metadata.json
Labels: docs-approved, release-notes-only

#34840 SplunkPy: use expandtoken in mirroring query
  Packs/SplunkPy/Integrations/SplunkPy/SplunkPy.py
  Packs/SplunkPy/Integrations/SplunkPy/SplunkPy.yml
  Packs/SplunkPy/ReleaseNotes/3_1_30.md
  Packs/SplunkPy/pack_metadata.json
Labels: docs-approved

#34931 [sane-pdf-reports] - assign markdown server port automatically
  Packs/Base/ReleaseNotes/1_34_14.md
  Packs/Base/Scripts/SanePdfReport/SanePdfReport.py
  Packs/Base/Scripts/SanePdfReport/SanePdfReport_test.py
  Packs/Base/pack_metadata.json
Labels: docs-approved

#34892 Joe security bug
  Packs/JoeSecurity/Integrations/JoeSecurityV2/JoeSecurityV2.py
  Packs/JoeSecurity/Integrations/JoeSecurityV2/JoeSecurityV2.yml
  Packs/JoeSecurity/ReleaseNotes/1_1_22.md
  Packs/JoeSecurity/pack_metadata.json
Labels: docs-approved

#34920 Digital guardian Bug
  Packs/DigitalGuardian/Integrations/DigitalGuardian/DigitalGuardian.py
  Packs/DigitalGuardian/Integrations/DigitalGuardian/DigitalGuardian.yml
  Packs/DigitalGuardian/Integrations/DigitalGuardianARCEventCollector/DigitalGuardianARCEventCollector.py
  Packs/DigitalGuardian/Integrations/DigitalGuardianARCEventCollector/DigitalGuardianARCEventCollector.yml
  Packs/DigitalGuardian/Integrations/DigitalGuardianARCEventCollector/DigitalGuardianARCEventCollector_test.py
  Packs/DigitalGuardian/Integrations/DigitalGuardianARCEventCollector/test_data/events.json
  Packs/DigitalGuardian/Integrations/DigitalGuardianARCEventCollector/test_data/events_mock_1_response.json
  Packs/DigitalGuardian/Integrations/DigitalGuardianARCEventCollector/test_data/events_mock_request.json
  Packs/DigitalGuardian/ReleaseNotes/1_1_5.md
  Packs/DigitalGuardian/pack_metadata.json
Labels: docs-approved

#34926 demisto-sdk-release 1.31.0
  poetry.lock
  pyproject.toml
Labels: docs-approved

#34814 Ys add 'get-machine-by-ip- command
  Packs/MicrosoftDefenderAdvancedThreatProtection/Integrations/MicrosoftDefenderAdvancedThreatProtection/MicrosoftDefenderAdvancedThreatProtection.py
  Packs/MicrosoftDefenderAdvancedThreatProtection/Integrations/MicrosoftDefenderAdvancedThreatProtection/MicrosoftDefenderAdvancedThreatProtection.yml
  Packs/MicrosoftDefenderAdvancedThreatProtection/Integrations/MicrosoftDefenderAdvancedThreatProtection/MicrosoftDefenderAdvancedThreatProtection_test.py
  Packs/MicrosoftDefenderAdvancedThreatProtection/Integrations/MicrosoftDefenderAdvancedThreatProtection/README.md
  Packs/MicrosoftDefenderAdvancedThreatProtection/Integrations/MicrosoftDefenderAdvancedThreatProtection/examples.txt
  Packs/MicrosoftDefenderAdvancedThreatProtection/ReleaseNotes/1_16_35.md
  Packs/MicrosoftDefenderAdvancedThreatProtection/pack_metadata.json
Labels: docs-approved

#34811 Added backslashes handling to drilldown enrichment
  Packs/SplunkPy/Integrations/SplunkPy/SplunkPy.py
  Packs/SplunkPy/Integrations/SplunkPy/SplunkPy_test.py
  Packs/SplunkPy/ReleaseNotes/3_1_31.md
  Packs/SplunkPy/pack_metadata.json
Labels: docs-approved

#34964 Barracuda Cloudgen Firewall - Readme Fix
  Packs/Barracuda_Cloudgen_Firewall/README.md
Labels: docs-approved

#34654 AzureRiskyUsers v1.1.36 - azure-risky-users-list extension
  Packs/AzureRiskyUsers/CONTRIBUTORS.json
  Packs/AzureRiskyUsers/Integrations/AzureRiskyUsers/AzureRiskyUsers.py
  Packs/AzureRiskyUsers/Integrations/AzureRiskyUsers/AzureRiskyUsers.yml
  Packs/AzureRiskyUsers/Integrations/AzureRiskyUsers/AzureRiskyUsers_test.py
  Packs/AzureRiskyUsers/Integrations/AzureRiskyUsers/README.md
  Packs/AzureRiskyUsers/ReleaseNotes/1_1_37.md
  Packs/AzureRiskyUsers/pack_metadata.json
Labels: Contribution, docs-approved, pending-demo, Contribution Form Filled, Community, Xsoar Support Level, External PR

#34967 Fixed an issue where test button failed with un informative error.
  Packs/AutoFocus/Integrations/AutofocusV2/AutofocusV2.py
  Packs/AutoFocus/Integrations/AutofocusV2/AutofocusV2.yml
  Packs/AutoFocus/ReleaseNotes/2_2_3.md
  Packs/AutoFocus/pack_metadata.json
Labels: docs-approved

#34921 [CSP] Fixed issue uploading large files
  Packs/Base/ReleaseNotes/1_34_15.md
  Packs/Base/Scripts/CommonServerPython/CommonServerPython.py
  Packs/Base/pack_metadata.json
Labels: docs-approved

#34990 delete tpb carbon black
  Packs/Base/TestPlaybooks/playbook-Search_Endpoints_By_Hash_-_Carbon_Black_Protection_-_Test.yml
Labels: docs-approved

#34896 O365 Security and Compliance Auth Fix
  Packs/MicrosoftExchangeOnline/.pack-ignore
  Packs/MicrosoftExchangeOnline/Integrations/SecurityAndComplianceV2/SecurityAndComplianceV2.ps1
  Packs/MicrosoftExchangeOnline/Integrations/SecurityAndComplianceV2/SecurityAndComplianceV2.yml
  Packs/MicrosoftExchangeOnline/Integrations/SecurityAndComplianceV2/SecurityAndComplianceV2_description.md
  Packs/MicrosoftExchangeOnline/ReleaseNotes/1_3_12.json
  Packs/MicrosoftExchangeOnline/ReleaseNotes/1_3_12.md
  Packs/MicrosoftExchangeOnline/pack_metadata.json
Labels: docs-approved

#34966 Fix alert regression in create email html body script
  Packs/CommonScripts/ReleaseNotes/1_15_14.md
  Packs/CommonScripts/Scripts/CreateEmailHtmlBody/CreateEmailHtmlBody.js
  Packs/CommonScripts/pack_metadata.json
Labels: docs-approved, release-notes-only

#34985 [Xsup 38544 ] DisplayHTMLWithImages no default color for background
  Packs/CommonScripts/ReleaseNotes/1_15_15.md
  Packs/CommonScripts/Scripts/DisplayHTMLWithImages/DisplayHTMLWithImages.py
  Packs/CommonScripts/Scripts/DisplayHTMLWithImages/DisplayHTMLWithImages.yml
  Packs/CommonScripts/pack_metadata.json
Labels: docs-approved

#34983 Fix proofpoint widget
  Packs/ProofpointTAP/.pack-ignore
  Packs/ProofpointTAP/ReleaseNotes/1_2_13.md
  Packs/ProofpointTAP/Scripts/ProofpointTAPMostAttackedUsers/ProofpointTAPMostAttackedUsers.py
  Packs/ProofpointTAP/Scripts/ProofpointTAPMostAttackedUsers/ProofpointTAPMostAttackedUsers.yml
  Packs/ProofpointTAP/Scripts/ProofpointTAPMostAttackedUsers/ProofpointTAPMostAttackedUsers_test.py
  Packs/ProofpointTAP/Scripts/ProofpointTapTopClickers/ProofpointTapTopClickers.py
  Packs/ProofpointTAP/Scripts/ProofpointTapTopClickers/ProofpointTapTopClickers.yml
  Packs/ProofpointTAP/Scripts/ProofpointTapTopClickers/ProofpointTapTopClickers_test.py
  Packs/ProofpointTAP/pack_metadata.json
Labels: docs-approved

#34255 Use `demisto/py3-tools` instead of `demisto/fastapi` for Pydantic
  Packs/AlibabaActionTrail/Integrations/AlibabaActionTrailEventCollector/AlibabaActionTrailEventCollector.yml
  Packs/AlibabaActionTrail/ReleaseNotes/1_1_0.md
  Packs/AlibabaActionTrail/pack_metadata.json
  Packs/ApiModules/Scripts/SiemApiModule/SiemApiModule.yml
  Packs/Box/Integrations/BoxEventsCollector/BoxEventsCollector.py
  Packs/Box/Integrations/BoxEventsCollector/BoxEventsCollector.yml
  Packs/Box/ReleaseNotes/3_2_0.md
  Packs/Box/pack_metadata.json
  Packs/CyberArkIdentity/Integrations/CyberArkIdentityEventCollector/CyberArkIdentityEventCollector.yml
  Packs/CyberArkIdentity/ReleaseNotes/1_1_0.md
  Packs/CyberArkIdentity/pack_metadata.json
  Packs/Dropbox/Integrations/DropboxEventCollector/DropboxEventCollector.py
  Packs/Dropbox/Integrations/DropboxEventCollector/DropboxEventCollector.yml
  Packs/Dropbox/Integrations/DropboxEventCollector/DropboxEventCollector_test.py
  Packs/Dropbox/ReleaseNotes/1_1_0.md
  Packs/Dropbox/pack_metadata.json
  Packs/GitHub/Integrations/GitHubEventCollector/GitHubEventCollector.py
  Packs/GitHub/Integrations/GitHubEventCollector/GitHubEventCollector.yml
  Packs/GitHub/ReleaseNotes/2_1_0.md
  Packs/GitHub/pack_metadata.json
  Packs/Jira/Integrations/JiraEventCollector/JiraEventCollector.yml
  Packs/Jira/Integrations/JiraEventCollector/JiraEventCollector_test.py
  Packs/Jira/ReleaseNotes/3_2_0.md
  Packs/Jira/pack_metadata.json
  Packs/Mimecast/Integrations/MimecastEventCollector/MimecastEventCollector.yml
  Packs/Mimecast/ReleaseNotes/2_4_0.md
  Packs/Mimecast/pack_metadata.json
  Packs/Salesforce/Integrations/SalesForceEventCollector/SalesForceEventCollector.yml
  Packs/Salesforce/ReleaseNotes/2_1_0.md
  Packs/Salesforce/pack_metadata.json
Labels: ForceMerge

#34999 move autobump rn to source github_workflow_scripts folder
  .github/github_workflow_scripts/autobump_rn.py
  .github/github_workflow_scripts/skip_conditions.py
  .github/workflows/autobump_rn.yml
Labels: docs-approved

#34913 reverted insecure parameter in OpenCTI
  Packs/OpenCTI/Integrations/OpenCTI/OpenCTI.py
  Packs/OpenCTI/ReleaseNotes/1_0_12.json
  Packs/OpenCTI/ReleaseNotes/1_0_12.md
  Packs/OpenCTI/pack_metadata.json
Labels: docs-approved

#35000 Replace IP used in AlienVault's TPB
  Packs/AlienVault_OTX/TestPlaybooks/playbook-Alienvault_OTX_v2-test.yml
  Tests/secrets_white_list.json
Labels: docs-approved

#35002 Revert "delete tpb carbon black"
  Packs/Base/TestPlaybooks/playbook-Search_Endpoints_By_Hash_-_Carbon_Black_Protection_-_Test.yml
Labels: docs-approved

#34932 Get Content Roles from Blob
  .github/github_workflow_scripts/handle_external_pr.py
  .github/github_workflow_scripts/utils.py
  .github/github_workflow_scripts/utils_test.py
Labels: docs-approved

#34862 [sane-pdf-reports] - fix issue where large customer logos were not parsed correctly
  Packs/Base/ReleaseNotes/1_34_16.md
  Packs/Base/Scripts/SanePdfReport/SanePdfReport.py
  Packs/Base/Scripts/SanePdfReport/SanePdfReport.yml
  Packs/Base/pack_metadata.json
Labels: docs-approved

#35005 [Auto Update Docker] Update demisto/unifi-video
  Packs/UnifiVideoNVR/Integrations/UnifiVideo/UnifiVideo.yml
  Packs/UnifiVideoNVR/ReleaseNotes/1_0_2.md
  Packs/UnifiVideoNVR/pack_metadata.json
Labels: docs-approved

#34868 [CortexXDRIR] Adjusted to rely on remote_args.data for closing in mirroring.
  Packs/CortexXDR/Integrations/CortexXDRIR/CortexXDRIR.py
  Packs/CortexXDR/ReleaseNotes/6_1_47.md
  Packs/CortexXDR/pack_metadata.json
Labels: docs-approved

#34977 Fix Typo of SecureID instead of the correct "SecurID"
  Packs/RSASecureID/ModelingRules/RSASecureID/RSASecureID.xif
  Packs/RSASecureID/ModelingRules/RSASecureID/RSASecureID_schema.json
  Packs/RSASecureID/README.md
  Packs/RSASecureID/ReleaseNotes/1_0_1.json
  Packs/RSASecureID/ReleaseNotes/1_0_1.md
  Packs/RSASecureID/pack_metadata.json
Labels: docs-approved

#35009 Update approved_categories.json
  Packs/MicrosoftCloudAppSecurity/pack_metadata.json
  Packs/Orca/pack_metadata.json
  Packs/PrismaCloud/pack_metadata.json
  Packs/PrismaCloudCompute/pack_metadata.json
  Packs/PrismaSaasSecurity/pack_metadata.json
  Packs/Wiz/pack_metadata.json
  Tests/Marketplace/approved_categories.json
Labels: docs-approved
