Repository demisto/content, pull requests merged in 2025-01, with the labels that each got.

#37855 Add script to delete indicators
  Packs/CommunityCommonScripts/CONTRIBUTORS.json
  Packs/CommunityCommonScripts/ReleaseNotes/1_3_9.md
  Packs/CommunityCommonScripts/Scripts/DeleteIndicators/DeleteIndicators.py
  Packs/CommunityCommonScripts/Scripts/DeleteIndicators/DeleteIndicators.yml
  Packs/CommunityCommonScripts/Scripts/DeleteIndicators/README.md
  Packs/CommunityCommonScripts/pack_metadata.json
Labels: Contribution, docs-approved, post-demo, Contribution Form Filled, Community, Community Support Level, External PR

#37893 Update the reviewers list with the correct users
  .github/content_roles.json
Labels: docs-approved

#37710 Cs_command_and_scripting
  Packs/CrowdStrikeFalcon/.pack-ignore
  Packs/CrowdStrikeFalcon/Classifiers/classifier-CrowdStrike_Falcon_Incident_Classifier.json
  Packs/CrowdStrikeFalcon/Classifiers/classifier-CrowdStrike_Falcon_Mapper_6.5.json
  Packs/CrowdStrikeFalcon/IncidentFields/incidentfield-Grand_Parent_Process.json
  Packs/CrowdStrikeFalcon/IncidentTypes/incidenttype-Crowdstrike_Command_And_Scripting.json
  Packs/CrowdStrikeFalcon/Layouts/layoutscontainer-CrowdStrike_Falcon_Layout.json
  Packs/CrowdStrikeFalcon/Playbooks/playbook-Command_and_Scripting_Interpreter.yml
  Packs/CrowdStrikeFalcon/Playbooks/playbook-Command_and_Scripting_Interpreter_README.md
  Packs/CrowdStrikeFalcon/Playbooks/playbook-CrowdStrike_Falcon_-_Search_Endpoints_By_Indicators.yml
  Packs/CrowdStrikeFalcon/Playbooks/playbook-CrowdStrike_Falcon_-_Search_Endpoints_By_Indicators_README.md
  Packs/CrowdStrikeFalcon/ReleaseNotes/2_1_1.md
  Packs/CrowdStrikeFalcon/Scripts/Cspresentgrandparentprocess/Cspresentgrandparentprocess.py
  Packs/CrowdStrikeFalcon/Scripts/Cspresentgrandparentprocess/Cspresentgrandparentprocess.yml
  Packs/CrowdStrikeFalcon/Scripts/Cspresentgrandparentprocess/Cspresentgrandparentprocess_test.py
  Packs/CrowdStrikeFalcon/Scripts/Cspresentgrandparentprocess/README.md
  Packs/CrowdStrikeFalcon/Scripts/Cspresentparentprocess/Cspresentparentprocess.py
  Packs/CrowdStrikeFalcon/Scripts/Cspresentparentprocess/Cspresentparentprocess.yml
  Packs/CrowdStrikeFalcon/Scripts/Cspresentparentprocess/Cspresentparentprocess_test.py
  Packs/CrowdStrikeFalcon/Scripts/Cspresentparentprocess/README.md
  Packs/CrowdStrikeFalcon/Scripts/Cspresentpolicyactions/Cspresentpolicyactions.py
  Packs/CrowdStrikeFalcon/Scripts/Cspresentpolicyactions/Cspresentpolicyactions.yml
  Packs/CrowdStrikeFalcon/Scripts/Cspresentpolicyactions/Cspresentpolicyactions_test.py
  Packs/CrowdStrikeFalcon/Scripts/Cspresentpolicyactions/README.md
  Packs/CrowdStrikeFalcon/doc_files/Command_and_Scripting_Interpreter.png
  Packs/CrowdStrikeFalcon/doc_files/CrowdStrike_Falcon_-_Search_Endpoints_By_Indicators.png
  Packs/CrowdStrikeFalcon/pack_metadata.json
Labels: docs-approved, bypass.url

#37707 Trend micro vision one update status bug fix
  Packs/TrendMicroVisionOne/Integrations/TrendMicroVisionOneV3/README.md
  Packs/TrendMicroVisionOne/Integrations/TrendMicroVisionOneV3/TrendMicroVisionOneV3.py
  Packs/TrendMicroVisionOne/Integrations/TrendMicroVisionOneV3/TrendMicroVisionOneV3.yml
  Packs/TrendMicroVisionOne/Integrations/TrendMicroVisionOneV3/TrendMicroVisionOneV3_test.py
  Packs/TrendMicroVisionOne/Integrations/TrendMicroVisionOneV3/command_examples
  Packs/TrendMicroVisionOne/ReleaseNotes/4_2_0.md
  Packs/TrendMicroVisionOne/pack_metadata.json
Labels: Contribution, docs-approved, Partner, post-demo, Contribution Form Filled, pending-contributor, Partner Support Level, External PR, Partner-Approved

#37182 Ciac 11199/support new validate in validate content script
  Packs/Base/ReleaseNotes/1_39_7.md
  Packs/Base/Scripts/ValidateContent/README.md
  Packs/Base/Scripts/ValidateContent/ValidateContent.py
  Packs/Base/Scripts/ValidateContent/ValidateContent.yml
  Packs/Base/Scripts/ValidateContent/ValidateContent_test.py
  Packs/Base/TestPlaybooks/ValidateContent_-_Test.yml
  Packs/Base/pack_metadata.json
Labels: docs-approved

#37899 Fix-large-upload-playbooks
  Packs/Core/Playbooks/playbook-Large_Upload_Alert.yml
  Packs/Core/Playbooks/playbook-Large_Upload_Alert_README.md
  Packs/Core/ReleaseNotes/3_2_15.md
  Packs/Core/pack_metadata.json
  Packs/CortexXDR/Playbooks/Cortex_XDR_-_Large_Upload.yml
  Packs/CortexXDR/ReleaseNotes/6_2_4.md
  Packs/CortexXDR/pack_metadata.json
Labels: docs-approved

#37678 Updated archer-upload-file to support multiple entryIds
  Packs/ArcherRSA/Integrations/ArcherV2/ArcherV2.py
  Packs/ArcherRSA/Integrations/ArcherV2/ArcherV2.yml
  Packs/ArcherRSA/Integrations/ArcherV2/ArcherV2_test.py
  Packs/ArcherRSA/Integrations/ArcherV2/README.md
  Packs/ArcherRSA/ReleaseNotes/1_2_21.md
  Packs/ArcherRSA/pack_metadata.json
Labels: docs-approved

#37907 Remove wildfire polling fields
  Packs/CommonPlaybooks/Playbooks/playbook-Detonate_File_-_Generic.yml
  Packs/CommonPlaybooks/ReleaseNotes/2_6_49.md
  Packs/CommonPlaybooks/pack_metadata.json
Labels: docs-approved

#37848 Fix TroubleshootExecutePlaybookByAlertQuery
  Packs/Troubleshoot/ReleaseNotes/2_1_5.md
  Packs/Troubleshoot/Scripts/TroubleshootExecutePlaybookByAlertQuery/TroubleshootExecutePlaybookByAlertQuery.py
  Packs/Troubleshoot/Scripts/TroubleshootExecutePlaybookByAlertQuery/TroubleshootExecutePlaybookByAlertQuery.yml
  Packs/Troubleshoot/Scripts/TroubleshootExecutePlaybookByAlertQuery/TroubleshootExecutePlaybookByAlertQuery_test.py
  Packs/Troubleshoot/pack_metadata.json
Labels: docs-approved

#37867 Add long running integration link to description files
  Packs/EDL/Integrations/EDL/EDL_description.md
  Packs/EDL/ReleaseNotes/3_3_7.md
  Packs/EDL/pack_metadata.json
  Packs/GenericWebhook/Integrations/GenericWebhook/GenericWebhook_description.md
  Packs/GenericWebhook/ReleaseNotes/1_1_5.md
  Packs/GenericWebhook/pack_metadata.json
  Packs/MicrosoftGraphTeams/Integrations/MicrosoftGraphTeams/MicrosoftGraphTeams_description.md
  Packs/MicrosoftGraphTeams/ReleaseNotes/1_1_10.md
  Packs/MicrosoftGraphTeams/pack_metadata.json
  Packs/PingCastle/Integrations/PingCastle/PingCastle_description.md
  Packs/PingCastle/ReleaseNotes/1_0_11.md
  Packs/PingCastle/pack_metadata.json
  Packs/PublishList/Integrations/PublishList/PublishList_description.md
  Packs/PublishList/ReleaseNotes/1_1_5.md
  Packs/PublishList/pack_metadata.json
  Packs/SimpleAPIProxy/Integrations/SimpleAPIProxy/SimpleAPIProxy_description.md
  Packs/SimpleAPIProxy/ReleaseNotes/1_0_5.md
  Packs/SimpleAPIProxy/pack_metadata.json
  Packs/Syslog/Integrations/Syslogv2/Syslogv2_description.md
  Packs/Syslog/ReleaseNotes/2_0_21.md
  Packs/Syslog/pack_metadata.json
  Packs/TAXIIServer/Integrations/TAXII2Server/TAXII2Server_description.md
  Packs/TAXIIServer/Integrations/TAXIIServer/TAXIIServer_description.md
  Packs/TAXIIServer/ReleaseNotes/2_1_1.md
  Packs/TAXIIServer/pack_metadata.json
  Packs/WebFileRepository/Integrations/WebFileRepository/WebFileRepository_description.md
  Packs/WebFileRepository/ReleaseNotes/1_0_28.md
  Packs/WebFileRepository/pack_metadata.json
Labels: docs-approved

#37780 Rasterize - kill zombie processes
  Packs/rasterize/Integrations/rasterize/rasterize.py
  Packs/rasterize/ReleaseNotes/2_0_35.md
  Packs/rasterize/pack_metadata.json
Labels: docs-approved, ForceMerge

#37789 Aud demisto/auto update docker staging branch 86
  Packs/CommonScripts/ReleaseNotes/1_19_2.md
  Packs/CommonScripts/Scripts/PcapHTTPExtractor/PcapHTTPExtractor.yml
  Packs/CommonScripts/pack_metadata.json
  Packs/Core/Integrations/CoreIOCs/CoreIOCs.py
  Packs/Core/Integrations/CoreIOCs/CoreIOCs.yml
  Packs/Core/ReleaseNotes/3_2_17.md
  Packs/Core/pack_metadata.json
  Packs/DatadogCloudSIEM/Integrations/DatadogCloudSIEM/DatadogCloudSIEM.py
  Packs/DatadogCloudSIEM/Integrations/DatadogCloudSIEM/DatadogCloudSIEM.yml
  Packs/DatadogCloudSIEM/ReleaseNotes/1_0_14.md
  Packs/DatadogCloudSIEM/pack_metadata.json
  Packs/DeveloperTools/Integrations/XsoarPowershellTesting/XsoarPowershellTesting.yml
  Packs/DeveloperTools/ReleaseNotes/1_3_26.md
  Packs/DeveloperTools/pack_metadata.json
  Packs/MicrosoftECM/Integrations/MicrosoftECM/MicrosoftECM.yml
  Packs/MicrosoftECM/ReleaseNotes/1_0_12.md
  Packs/MicrosoftECM/pack_metadata.json
  Packs/PowershellRemoting/Integrations/PowerShellRemoting/PowerShellRemoting.yml
  Packs/PowershellRemoting/ReleaseNotes/1_0_6.md
  Packs/PowershellRemoting/pack_metadata.json
Labels: docs-approved

#37910 Changed AWS SNS Listener - Test to be dynamic
  Packs/AWS-SNS-Listener/TestPlaybooks/AWS_SNS_Listener_-_Test.yml
  Tests/conf.json
Labels: docs-approved, sync-gsm

#37926 XSUP-45343 - symantec ep parsing fix
  Packs/SymantecEndpointProtection/ParsingRules/SymantecEndpointProtection/SymantecEndpointProtection.xif
  Packs/SymantecEndpointProtection/README.md
  Packs/SymantecEndpointProtection/ReleaseNotes/1_1_15.md
  Packs/SymantecEndpointProtection/pack_metadata.json
Labels: docs-approved, bypass.url

#37880 relative images
  Packs/ShiftManagement/.pack-ignore
  Packs/ShiftManagement/Playbooks/playbook-ShiftManagment_Assign_Active_Incidents_to_Next_Shift.yml
  Packs/ShiftManagement/Playbooks/playbook-ShiftManagment_Assign_Active_Incidents_to_Next_Shift_README.md
  Packs/ShiftManagement/Playbooks/playbook-ShiftManagment_Set_up_a_Shift_handover_meeting.yml
  Packs/ShiftManagement/Playbooks/playbook-ShiftManagment_Set_up_a_Shift_handover_meeting_README.md
  Packs/ShiftManagement/Playbooks/playbook-ShiftManagment_Shift_handover.yml
  Packs/ShiftManagement/Playbooks/playbook-ShiftManagment_Shift_handover_README.md
  Packs/ShiftManagement/README.md
  Packs/ShiftManagement/ReleaseNotes/1_3_16.md
  Packs/ShiftManagement/doc_files/ShiftManagment_Assign_Active_Incidents_to_Next_Shift.png
  Packs/ShiftManagement/doc_files/ShiftManagment_Set_up_a_Shift_handover_meeting.png
  Packs/ShiftManagement/doc_files/ShiftManagment_Shift_handover.png
  Packs/ShiftManagement/doc_files/ShiftManagment_layout.png
  Packs/ShiftManagement/pack_metadata.json
Labels: docs-approved, bypass.url

#37916 validatecontent-tpb
  Packs/Base/ReleaseNotes/1_39_8.md
  Packs/Base/Scripts/ValidateContent/ValidateContent.yml
  Packs/Base/Scripts/ValidateContent/test_data/integration-witherrors.yml
  Packs/Base/TestPlaybooks/ValidateContent_-_Test.yml
  Packs/Base/pack_metadata.json
  Tests/conf.json
Labels: docs-approved

#37879 Added links to long running integrations documentation for readme files
  Packs/EDL/Integrations/EDL/README.md
  Packs/GenericWebhook/Integrations/GenericWebhook/README.md
  Packs/MicrosoftGraphTeams/Integrations/MicrosoftGraphTeams/README.md
  Packs/PingCastle/Integrations/PingCastle/README.md
  Packs/Syslog/Integrations/Syslogv2/README.md
  Packs/TAXIIServer/Integrations/TAXII2Server/README.md
  Packs/TAXIIServer/Integrations/TAXIIServer/README.md
  Packs/WebFileRepository/Integrations/WebFileRepository/README.md
Labels: docs-approved

#37886 [DatadogCloudSIEM] MyPy In Docker
  Packs/DatadogCloudSIEM/Integrations/DatadogCloudSIEM/DatadogCloudSIEM.py
  Packs/DatadogCloudSIEM/ReleaseNotes/1_0_15.md
  Packs/DatadogCloudSIEM/pack_metadata.json
Labels: docs-approved

#37919 [Windows Remote Management] MyPy In Docker
  Packs/WinRM/Integrations/WindowsRemoteManagement/WindowsRemoteManagement.py
  Packs/WinRM/Integrations/WindowsRemoteManagement/WindowsRemoteManagement.yml
  Packs/WinRM/ReleaseNotes/1_0_6.md
  Packs/WinRM/pack_metadata.json
Labels: docs-approved

#37920 [Elasticsearch] MyPy In Docker
  Packs/Elasticsearch/Integrations/Elasticsearch_v2/Elasticsearch_v2.py
  Packs/Elasticsearch/Integrations/Elasticsearch_v2/Elasticsearch_v2.yml
  Packs/Elasticsearch/ReleaseNotes/1_3_26.md
  Packs/Elasticsearch/pack_metadata.json
  Packs/FeedElasticsearch/Integrations/FeedElasticsearch/FeedElasticsearch.py
  Packs/FeedElasticsearch/Integrations/FeedElasticsearch/FeedElasticsearch.yml
  Packs/FeedElasticsearch/ReleaseNotes/1_1_11.md
  Packs/FeedElasticsearch/pack_metadata.json
Labels: docs-approved

#37941 Exchange forwarding playbook
  Packs/CortexResponseAndRemediation/Playbooks/playbook-Exchange_User_Mailbox_Forwarding.yml
  Packs/CortexResponseAndRemediation/Playbooks/playbook-Exchange_User_Mailbox_Forwarding_README.md
  Packs/CortexResponseAndRemediation/ReleaseNotes/1_0_1.md
  Packs/CortexResponseAndRemediation/Triggers/Trigger_-_Exchange_User_Mailbox_Forwarding.json
  Packs/CortexResponseAndRemediation/doc_files/Exchange_User_Mailbox_Forwarding.png
  Packs/CortexResponseAndRemediation/pack_metadata.json
Labels: docs-approved

#37828 Netskope fix incident fields
  Packs/Netskope/Integrations/NetskopeAPIv2/NetskopeAPIv2.py
  Packs/Netskope/Integrations/NetskopeAPIv2/NetskopeAPIv2_test.py
  Packs/Netskope/ReleaseNotes/4_0_4.md
  Packs/Netskope/pack_metadata.json
Labels: docs-approved, release-notes-only

#37881 Qualys handle timeout
  Packs/qualys/Integrations/Qualysv2/Qualysv2.py
  Packs/qualys/Integrations/Qualysv2/Qualysv2.yml
  Packs/qualys/Integrations/Qualysv2/Qualysv2_test.py
  Packs/qualys/ReleaseNotes/3_1_3.md
  Packs/qualys/pack_metadata.json
Labels: docs-approved

#37743 Update Pack: CTM360
  Packs/CTM360-CyberBlindspot/.pack-ignore
  Packs/CTM360-CyberBlindspot/.secrets-ignore
  Packs/CTM360-CyberBlindspot/Classifiers/classifier-mapper-incoming-CTM360-HackerView.json
  Packs/CTM360-CyberBlindspot/Dashboards/dashboard-HackerView.json
  Packs/CTM360-CyberBlindspot/IncidentFields/incidentfields-Asset_Type.json
  Packs/CTM360-CyberBlindspot/IncidentFields/incidentfields-Potential_Attack.json
  Packs/CTM360-CyberBlindspot/IncidentFields/incidentfields-Potential_Impact.json
  Packs/CTM360-CyberBlindspot/IncidentFields/incidentfields-Technologies.json
  Packs/CTM360-CyberBlindspot/IncidentTypes/HackerView_Incident.json
  Packs/CTM360-CyberBlindspot/Integrations/CyberBlindspot/CyberBlindspot.yml
  Packs/CTM360-CyberBlindspot/Integrations/HackerView/HackerView.py
  Packs/CTM360-CyberBlindspot/Integrations/HackerView/HackerView.yml
  Packs/CTM360-CyberBlindspot/Integrations/HackerView/HackerView_description.md
  Packs/CTM360-CyberBlindspot/Integrations/HackerView/HackerView_image.png
  Packs/CTM360-CyberBlindspot/Integrations/HackerView/HackerView_test.py
  Packs/CTM360-CyberBlindspot/Integrations/HackerView/README.md
  Packs/CTM360-CyberBlindspot/Integrations/HackerView/command_examples
  Packs/CTM360-CyberBlindspot/Integrations/HackerView/test_data/fetch_incidents_response_invalid.json
  Packs/CTM360-CyberBlindspot/Integrations/HackerView/test_data/fetch_incidents_response_valid.json
  Packs/CTM360-CyberBlindspot/Integrations/HackerView/test_data/incident_details_response_valid.json
  Packs/CTM360-CyberBlindspot/Integrations/HackerView/test_data/incident_list_cmd_result_valid.json
  Packs/CTM360-CyberBlindspot/Integrations/HackerView/test_data/incident_status_change_response_invalid_id.json
  Packs/CTM360-CyberBlindspot/Integrations/HackerView/test_data/incident_status_change_response_invalid_status.json
  Packs/CTM360-CyberBlindspot/Integrations/HackerView/test_data/incident_status_change_response_valid.json
  Packs/CTM360-CyberBlindspot/Integrations/HackerView/test_data/invalid_api_key_response.json
  Packs/CTM360-CyberBlindspot/Playbooks/playbook-HackerView_Incident_Management.yml
  Packs/CTM360-CyberBlindspot/Playbooks/playbook-HackerView_Incident_Management_README.md
  Packs/CTM360-CyberBlindspot/ReleaseNotes/2_0_0.md
  Packs/CTM360-CyberBlindspot/doc_files/HackerView_Incident_Management.png
  Packs/CTM360-CyberBlindspot/pack_metadata.json
Labels: Contribution, docs-approved, Partner, post-demo, Contribution Form Filled, Partner Support Level, External PR, Security Review, Partner-Approved, Security Approved

#37261 Update RSANetWitnessv115.py with fetch alerts api call
  Packs/RSANetWitness_v11_1/Integrations/RSANetWitnessv115/README.md
  Packs/RSANetWitness_v11_1/Integrations/RSANetWitnessv115/RSANetWitnessv115.py
  Packs/RSANetWitness_v11_1/Integrations/RSANetWitnessv115/RSANetWitnessv115_dark.svg
  Packs/RSANetWitness_v11_1/ReleaseNotes/3_2_6.md
  Packs/RSANetWitness_v11_1/pack_metadata.json
Labels: Contribution, Partner, Contribution Form Filled, Partner Support Level, External PR, Partner-Approved

#37964 [pre-commit] Add again pycln hook
  .pre-commit-config_template.yaml
Labels: docs-approved

#37921 [Azure] MyPy In Docker
  Packs/AzureDevOps/Integrations/AzureDevOps/AzureDevOps.py
  Packs/AzureDevOps/Integrations/AzureDevOps/AzureDevOps.yml
  Packs/AzureDevOps/ReleaseNotes/1_4_6.md
  Packs/AzureDevOps/pack_metadata.json
  Packs/AzureSentinel/Integrations/AzureSentinel/AzureSentinel.py
  Packs/AzureSentinel/ReleaseNotes/1_5_57.md
  Packs/AzureSentinel/pack_metadata.json
  Packs/AzureWAF/Integrations/AzureWAF/AzureWAF.py
  Packs/AzureWAF/Integrations/AzureWAF/AzureWAF.yml
  Packs/AzureWAF/Integrations/AzureWAF/AzureWAF_test.py
  Packs/AzureWAF/ReleaseNotes/1_2_6.md
  Packs/AzureWAF/pack_metadata.json
  Packs/MicrosoftCloudAppSecurity/Integrations/MicrosoftCloudAppSecurity/MicrosoftCloudAppSecurity.py
  Packs/MicrosoftCloudAppSecurity/Integrations/MicrosoftCloudAppSecurity/MicrosoftCloudAppSecurity.yml
  Packs/MicrosoftCloudAppSecurity/ReleaseNotes/2_2_10.md
  Packs/MicrosoftCloudAppSecurity/pack_metadata.json
Labels: docs-approved

#37876 Change code owner for xdr
  .github/CODEOWNERS
Labels: docs-approved

#37966 Veeam: Code functionality improvements
  Packs/Veeam/.secrets-ignore
  Packs/Veeam/Integrations/VeeamONERESTAPI/VeeamONERESTAPI.py
  Packs/Veeam/Integrations/VeeamONERESTAPI/VeeamONERESTAPI_test.py
  Packs/Veeam/ReleaseNotes/1_0_7.md
  Packs/Veeam/pack_metadata.json
Labels: Contribution, docs-approved, Partner, Contribution Form Filled, Partner Support Level, External PR, Partner-Approved

#37929 Fix-playbook-name-for-t1059-cs
  Packs/CrowdStrikeFalcon/IncidentTypes/incidenttype-Crowdstrike_Command_And_Scripting.json
  Packs/CrowdStrikeFalcon/Playbooks/playbook-Command_and_Scripting_Interpreter.yml
  Packs/CrowdStrikeFalcon/ReleaseNotes/2_1_2.md
  Packs/CrowdStrikeFalcon/pack_metadata.json
Labels: docs-approved, ForceMerge

#37918 [AWS - Security Hub] mypy in docker
  Packs/AWS-SecurityHub/Integrations/AWS_SecurityHub/AWS_SecurityHub.py
  Packs/AWS-SecurityHub/Integrations/AWS_SecurityHub/AWS_SecurityHub.yml
  Packs/AWS-SecurityHub/ReleaseNotes/1_3_40.md
  Packs/AWS-SecurityHub/pack_metadata.json
Labels: docs-approved

#37681 Cisco ThousandEyes - XSIAM Collector
  Packs/CiscoThousandEyes/.pack-ignore
  Packs/CiscoThousandEyes/.secrets-ignore
  Packs/CiscoThousandEyes/Author_image.png
  Packs/CiscoThousandEyes/Integrations/CiscoThousandEyes/CiscoThousandEyes.py
  Packs/CiscoThousandEyes/Integrations/CiscoThousandEyes/CiscoThousandEyes.yml
  Packs/CiscoThousandEyes/Integrations/CiscoThousandEyes/CiscoThousandEyes_description.md
  Packs/CiscoThousandEyes/Integrations/CiscoThousandEyes/CiscoThousandEyes_image.png
  Packs/CiscoThousandEyes/Integrations/CiscoThousandEyes/CiscoThousandEyes_test.py
  Packs/CiscoThousandEyes/Integrations/CiscoThousandEyes/README.md
  Packs/CiscoThousandEyes/Integrations/CiscoThousandEyes/command_examples
  Packs/CiscoThousandEyes/Integrations/CiscoThousandEyes/test_data/alerts_list.json
  Packs/CiscoThousandEyes/Integrations/CiscoThousandEyes/test_data/events_list.json
  Packs/CiscoThousandEyes/ModelingRules/CiscoThousandEyes/CiscoThousandEyes.xif
  Packs/CiscoThousandEyes/ModelingRules/CiscoThousandEyes/CiscoThousandEyes.yml
  Packs/CiscoThousandEyes/ModelingRules/CiscoThousandEyes/CiscoThousandEyes_schema.json
  Packs/CiscoThousandEyes/README.md
  Packs/CiscoThousandEyes/pack_metadata.json
Labels: docs-approved

#37922 [DBotPreProcessTextData] MyPy In Docker
  Packs/Base/ReleaseNotes/1_39_11.md
  Packs/Base/Scripts/DBotPreprocessTextData/DBotPreprocessTextData.py
  Packs/Base/pack_metadata.json
Labels: docs-approved

#37989 [CyCognito] MyPy In Docker
  Packs/CyCognito/Integrations/CyCognito/CyCognito.py
  Packs/CyCognito/ReleaseNotes/1_0_26.md
  Packs/CyCognito/pack_metadata.json
Labels: docs-approved

#37991 [SetGridField] MyPy In Docker
  Packs/CommonScripts/ReleaseNotes/1_19_4.md
  Packs/CommonScripts/Scripts/SetGridField/SetGridField.py
  Packs/CommonScripts/pack_metadata.json
Labels: docs-approved

#37993 [MattermostV2] MyPy In Docker
  Packs/Mattermost/Integrations/MattermostV2/MattermostV2.py
  Packs/Mattermost/Integrations/MattermostV2/MattermostV2.yml
  Packs/Mattermost/ReleaseNotes/2_0_6.md
  Packs/Mattermost/pack_metadata.json
Labels: docs-approved

#37996 [Lumu] MyPy In Docker
  Packs/Lumu/Integrations/Lumu/Lumu.py
  Packs/Lumu/Integrations/Lumu/Lumu.yml
  Packs/Lumu/ReleaseNotes/1_0_24.md
  Packs/Lumu/pack_metadata.json
Labels: docs-approved

#37997 [ReversingLabs_A1000] MyPy In Docker
  Packs/ReversingLabs_A1000/ReleaseNotes/2_4_2.md
  Packs/ReversingLabs_A1000/Scripts/A1000FinalClassification/A1000FinalClassification.py
  Packs/ReversingLabs_A1000/Scripts/A1000FinalClassification/A1000FinalClassification.yml
  Packs/ReversingLabs_A1000/pack_metadata.json
Labels: docs-approved

#37999 [QueryAI] MyPy In Docker
  Packs/QueryAI/Integrations/QueryAI/QueryAI.py
  Packs/QueryAI/Integrations/QueryAI/QueryAI.yml
  Packs/QueryAI/ReleaseNotes/1_0_13.md
  Packs/QueryAI/pack_metadata.json
Labels: docs-approved

#38000 [Fortiweb VM] MyPy In Docker
  Packs/FortinetFortiwebVM/Integrations/FortinetFortiwebVM/FortinetFortiwebVM.py
  Packs/FortinetFortiwebVM/Integrations/FortinetFortiwebVM/FortinetFortiwebVM.yml
  Packs/FortinetFortiwebVM/ReleaseNotes/2_0_9.md
  Packs/FortinetFortiwebVM/pack_metadata.json
Labels: docs-approved

#38013 [FortiSIEMV2] MyPy In Docker
  Packs/FortiSIEM/Integrations/FortiSIEMV2/FortiSIEMV2.py
  Packs/FortiSIEM/Integrations/FortiSIEMV2/FortiSIEMV2.yml
  Packs/FortiSIEM/ReleaseNotes/2_0_40.md
  Packs/FortiSIEM/pack_metadata.json
Labels: docs-approved

#38018 [FreshDesk] MyPy In Docker
  Packs/FreshDesk/Integrations/FreshDesk/FreshDesk.py
  Packs/FreshDesk/Integrations/FreshDesk/FreshDesk.yml
  Packs/FreshDesk/ReleaseNotes/1_0_16.md
  Packs/FreshDesk/pack_metadata.json
Labels: docs-approved

#38023 [CoreXQLApiModule] MyPy In Docker
  Packs/ApiModules/Scripts/CoreXQLApiModule/CoreXQLApiModule.py
  Packs/ApiModules/Scripts/CoreXQLApiModule/CoreXQLApiModule.yml
  Packs/Core/ReleaseNotes/3_2_18.md
  Packs/Core/pack_metadata.json
  Packs/CortexXDR/ReleaseNotes/6_2_5.md
  Packs/CortexXDR/pack_metadata.json
Labels: docs-approved

#38025 RubrikPolaris
  Packs/RubrikPolaris/Integrations/RubrikPolaris/RubrikPolaris.py
  Packs/RubrikPolaris/Integrations/RubrikPolaris/RubrikPolaris.yml
  Packs/RubrikPolaris/ReleaseNotes/1_4_2.md
  Packs/RubrikPolaris/pack_metadata.json
Labels: docs-approved

#37934 Anomali Threatstream update playbook to v3
  Packs/Anomali_ThreatStream/Playbooks/playbook-Detonate_URL_-_ThreatStream.yml
  Packs/Anomali_ThreatStream/Playbooks/playbook-Detonate_URL_-_ThreatStream_README.md
  Packs/Anomali_ThreatStream/ReleaseNotes/2_2_26.md
  Packs/Anomali_ThreatStream/doc_files/Detonate_URL_-_ThreatStream.png
  Packs/Anomali_ThreatStream/pack_metadata.json
Labels: docs-approved

#37984 Office process creates a scheduled task
  Packs/CortexResponseAndRemediation/Playbooks/playbook-A_successful_SSO_sign-in_from_TOR.yml
  Packs/CortexResponseAndRemediation/Playbooks/playbook-A_successful_SSO_sign-in_from_TOR_README.md
  Packs/CortexResponseAndRemediation/Playbooks/playbook-Office_process_creates_a_scheduled_task_via_file_access.yml
  Packs/CortexResponseAndRemediation/Playbooks/playbook-Office_process_creates_a_scheduled_task_via_file_access_README.md
  Packs/CortexResponseAndRemediation/ReleaseNotes/1_0_2.md
  Packs/CortexResponseAndRemediation/Triggers/Trigger_-_Office_process_creates_a_scheduled_task_via_file_access.json
  Packs/CortexResponseAndRemediation/doc_files/Office_process_creates_a_scheduled_task_via_file_access.png
  Packs/CortexResponseAndRemediation/pack_metadata.json
Labels: docs-approved

#38022 [SafeBreach] MyPy In Docker
  Packs/SafeBreach/Integrations/SafeBreach/SafeBreach.py
  Packs/SafeBreach/Integrations/SafeBreach/SafeBreach.yml
  Packs/SafeBreach/ReleaseNotes/1_4_5.md
  Packs/SafeBreach/pack_metadata.json
Labels: docs-approved

#38028 [CreatePlbkDoc] MyPy In Docker
  Packs/CommunityCommonScripts/ReleaseNotes/1_3_10.md
  Packs/CommunityCommonScripts/Scripts/CreatePlbkDoc/CreatePlbkDoc.py
  Packs/CommunityCommonScripts/pack_metadata.json
Labels: docs-approved

#38040 [ReversingLabsA1000v2] MyPy In Docker
  Packs/ReversingLabs_A1000/Integrations/ReversingLabsA1000v2/ReversingLabsA1000v2.py
  Packs/ReversingLabs_A1000/Integrations/ReversingLabsA1000v2/ReversingLabsA1000v2.yml
  Packs/ReversingLabs_A1000/ReleaseNotes/2_4_3.md
  Packs/ReversingLabs_A1000/pack_metadata.json
Labels: docs-approved

#37923 [EWSv2] MyPy In Docker
  Packs/MicrosoftExchangeOnPremise/Integrations/EWSv2/EWSv2.py
  Packs/MicrosoftExchangeOnPremise/ReleaseNotes/2_1_21.md
  Packs/MicrosoftExchangeOnPremise/pack_metadata.json
Labels: docs-approved, ForceMerge

#38049 Office process creates a scheduled task fix
  Packs/CortexResponseAndRemediation/Playbooks/playbook-Office_process_creates_a_scheduled_task_via_file_access.yml
  Packs/CortexResponseAndRemediation/ReleaseNotes/1_0_3.md
  Packs/CortexResponseAndRemediation/pack_metadata.json
Labels: docs-approved

#37924 [py3-tools] MyPy In Docker
  Packs/CommonScripts/ReleaseNotes/1_19_5.md
  Packs/CommonScripts/Scripts/ExtractDomainAndFQDNFromUrlAndEmail/ExtractDomainAndFQDNFromUrlAndEmail.py
  Packs/CommonScripts/Scripts/ExtractDomainAndFQDNFromUrlAndEmail/ExtractDomainAndFQDNFromUrlAndEmail.yml
  Packs/CommonScripts/pack_metadata.json
  Packs/CrowdStrikeFalcon/Integrations/CrowdStrikeFalcon/CrowdStrikeFalcon.py
  Packs/CrowdStrikeFalcon/Integrations/CrowdStrikeFalcon/CrowdStrikeFalcon.yml
  Packs/CrowdStrikeFalcon/ReleaseNotes/2_1_3.md
  Packs/CrowdStrikeFalcon/Scripts/ReadNetstatFile/README.md
  Packs/CrowdStrikeFalcon/pack_metadata.json
  Packs/MailListener/Integrations/MailListenerV2/MailListenerV2.py
  Packs/MailListener/Integrations/MailListenerV2/MailListenerV2.yml
  Packs/MailListener/ReleaseNotes/1_0_60.md
  Packs/MailListener/pack_metadata.json
Labels: docs-approved

#38039 [VMware] MyPy In Docker
  Packs/VMware/Integrations/VMware/VMware.py
  Packs/VMware/ReleaseNotes/1_2_12.md
  Packs/VMware/pack_metadata.json
Labels: docs-approved

#38024 [ReliaQuestGreyMatterDRPEventCollector] MyPy In Docker
  Packs/DigitalShadows/Integrations/ReliaQuestGreyMatterDRPEventCollector/README.md
  Packs/DigitalShadows/Integrations/ReliaQuestGreyMatterDRPEventCollector/ReliaQuestGreyMatterDRPEventCollector.py
  Packs/DigitalShadows/Integrations/ReliaQuestGreyMatterDRPEventCollector/ReliaQuestGreyMatterDRPEventCollector.yml
  Packs/DigitalShadows/Integrations/ReliaQuestGreyMatterDRPEventCollector/command_examples
  Packs/DigitalShadows/ReleaseNotes/2_0_5.md
  Packs/DigitalShadows/pack_metadata.json
Labels: docs-approved

#38009 [Qualysv2] MyPy In Docker
  Packs/qualys/Integrations/Qualysv2/Qualysv2.py
  Packs/qualys/Integrations/Qualysv2/Qualysv2.yml
  Packs/qualys/ReleaseNotes/3_1_4.md
  Packs/qualys/pack_metadata.json
Labels: docs-approved

#37992 [MISPV3] MyPy In Docker
  Packs/MISP/Integrations/MISPV3/MISPV3.py
  Packs/MISP/Integrations/MISPV3/MISPV3.yml
  Packs/MISP/ReleaseNotes/2_1_49.md
  Packs/MISP/pack_metadata.json
Labels: docs-approved

#38046 CRTX-144037-Microsoft-Windows-Events-fix
  Packs/MicrosoftWindowsEvents/ModelingRules/MicrosoftWindowsEvents_1_3/MicrosoftWindowsEvents_1_3.xif
  Packs/MicrosoftWindowsEvents/ReleaseNotes/1_1_10.md
  Packs/MicrosoftWindowsEvents/ReleaseNotes/1_1_11.md
  Packs/MicrosoftWindowsEvents/pack_metadata.json
Labels: docs-approved

#37531 Nozomi make result per run configurble
  Packs/NozomiNetworks/Integrations/NozomiNetworks/NozomiNetworks.py
  Packs/NozomiNetworks/Integrations/NozomiNetworks/NozomiNetworks.yml
  Packs/NozomiNetworks/Integrations/NozomiNetworks/NozomiNetworks_test.py
  Packs/NozomiNetworks/Integrations/NozomiNetworks/README.md
  Packs/NozomiNetworks/ReleaseNotes/1_0_14.md
  Packs/NozomiNetworks/pack_metadata.json
Labels: Contribution, docs-approved, Partner, post-demo, Contribution Form Filled, Partner Support Level, External PR, Partner-Approved

#38060 AccentureCTI fixed image path
  Packs/AccentureCTI/Playbooks/playbook-ACTI_Vulnerability_Enrichment_README.md
Labels: docs-approved

#38035 [SplunkPy] MyPy In Docker
  Packs/SplunkPy/Integrations/SplunkPy/SplunkPy.py
  Packs/SplunkPy/Integrations/SplunkPy/SplunkPy.yml
  Packs/SplunkPy/ReleaseNotes/3_1_50.md
  Packs/SplunkPy/pack_metadata.json
Labels: docs-approved

#38026 [python3:3.11.10.115186] MyPy In Docker
  Packs/CommonScripts/ReleaseNotes/1_19_7.md
  Packs/CommonScripts/Scripts/CreateHash/CreateHash.py
  Packs/CommonScripts/Scripts/CreateHash/CreateHash.yml
  Packs/CommonScripts/Scripts/LookupCSV/LookupCSV.py
  Packs/CommonScripts/Scripts/LookupCSV/LookupCSV.yml
  Packs/CommonScripts/pack_metadata.json
  Packs/PrismaSaasSecurity/Integrations/SaasSecurity/SaasSecurity.py
  Packs/PrismaSaasSecurity/Integrations/SaasSecurity/SaasSecurity.yml
  Packs/PrismaSaasSecurity/ReleaseNotes/2_0_35.md
  Packs/PrismaSaasSecurity/pack_metadata.json
  Packs/ThreatConnect/Integrations/ThreatConnectV3/ThreatConnectV3.py
  Packs/ThreatConnect/Integrations/ThreatConnectV3/ThreatConnectV3.yml
  Packs/ThreatConnect/ReleaseNotes/3_1_11.md
  Packs/ThreatConnect/pack_metadata.json
Labels: docs-approved

#37901 dev-bug - remove more sensitive data from the logs
  Packs/Base/ReleaseNotes/1_39_12.md
  Packs/Base/Scripts/CommonServerPython/CommonServerPython.py
  Packs/Base/Scripts/CommonServerPython/CommonServerPython_test.py
  Packs/Base/pack_metadata.json
Labels: docs-approved, ForceMerge

#38055 Fix Pylint errors in F packs
  Packs/FeedCognyteLuminar/Integrations/CognyteLuminar/CognyteLuminar.py
  Packs/FeedCognyteLuminar/Integrations/CognyteLuminar/CognyteLuminar.yml
  Packs/FeedCognyteLuminar/ReleaseNotes/1_0_7.md
  Packs/FeedCognyteLuminar/pack_metadata.json
  Packs/FidelisEndpoint/Integrations/FidelisEndpoint/FidelisEndpoint.py
  Packs/FidelisEndpoint/Integrations/FidelisEndpoint/FidelisEndpoint.yml
  Packs/FidelisEndpoint/ReleaseNotes/1_0_8.md
  Packs/FidelisEndpoint/pack_metadata.json
  Packs/FireEyeHX/Integrations/FireEyeHXv2/FireEyeHXv2.py
  Packs/FireEyeHX/Integrations/FireEyeHXv2/FireEyeHXv2.yml
  Packs/FireEyeHX/ReleaseNotes/2_3_17.md
  Packs/FireEyeHX/pack_metadata.json
  Packs/FreshworksFreshservice/Integrations/FreshworksFreshservice/FreshworksFreshservice.py
  Packs/FreshworksFreshservice/Integrations/FreshworksFreshservice/FreshworksFreshservice.yml
  Packs/FreshworksFreshservice/ReleaseNotes/1_0_28.md
  Packs/FreshworksFreshservice/pack_metadata.json
Labels: docs-approved

#38058 Fix Pylint errors in G + H packs
  Packs/GithubMaltrailFeed/Integrations/GithubMaltrailFeed/GithubMaltrailFeed.py
  Packs/GithubMaltrailFeed/Integrations/GithubMaltrailFeed/GithubMaltrailFeed.yml
  Packs/GithubMaltrailFeed/ReleaseNotes/1_0_2.md
  Packs/GithubMaltrailFeed/pack_metadata.json
  Packs/GoogleCloudCompute/Integrations/GoogleCloudCompute/GoogleCloudCompute.py
  Packs/GoogleCloudCompute/Integrations/GoogleCloudCompute/GoogleCloudCompute.yml
  Packs/GoogleCloudCompute/ReleaseNotes/1_1_15.md
  Packs/GoogleCloudCompute/pack_metadata.json
  Packs/GoogleKeyManagementService/Integrations/GoogleKeyManagementService/GoogleKeyManagementService.py
  Packs/GoogleKeyManagementService/Integrations/GoogleKeyManagementService/GoogleKeyManagementService.yml
  Packs/GoogleKeyManagementService/ReleaseNotes/1_0_28.md
  Packs/GoogleKeyManagementService/pack_metadata.json
  Packs/GreyNoise/Integrations/GreyNoise/GreyNoise.py
  Packs/GreyNoise/Integrations/GreyNoise/GreyNoise.yml
  Packs/GreyNoise/ReleaseNotes/1_4_2.md
  Packs/GreyNoise/pack_metadata.json
  Packs/HashiCorp-Vault/Integrations/HashiCorpVault/HashiCorpVault.py
  Packs/HashiCorp-Vault/Integrations/HashiCorpVault/HashiCorpVault.yml
  Packs/HashiCorp-Vault/ReleaseNotes/1_1_28.md
  Packs/HashiCorp-Vault/pack_metadata.json
  Packs/HealthCheck/ReleaseNotes/3_0_4.md
  Packs/HealthCheck/Scripts/HealthCheckSystemDiagnostics/HealthCheckSystemDiagnostics.py
  Packs/HealthCheck/Scripts/HealthCheckSystemDiagnostics/HealthCheckSystemDiagnostics.yml
  Packs/HealthCheck/pack_metadata.json
Labels: docs-approved

#38053 Fix Pylint errors in E packs
  Packs/EclecticIQ/Integrations/EclecticIQIntelligenceCenterv3/EclecticIQIntelligenceCenterv3.py
  Packs/EclecticIQ/Integrations/EclecticIQIntelligenceCenterv3/EclecticIQIntelligenceCenterv3.yml
  Packs/EclecticIQ/ReleaseNotes/3_0_6.md
  Packs/EclecticIQ/pack_metadata.json
  Packs/Elasticsearch/Integrations/Elasticsearch_v2/Elasticsearch_v2.py
  Packs/Elasticsearch/ReleaseNotes/1_3_27.md
  Packs/Elasticsearch/pack_metadata.json
  Packs/EmailCommunication/ReleaseNotes/2_0_37.md
  Packs/EmailCommunication/Scripts/SendEmailReply/SendEmailReply.py
  Packs/EmailCommunication/pack_metadata.json
  Packs/ExabeamDataLake/Integrations/ExabeamDataLake/ExabeamDataLake.py
  Packs/ExabeamDataLake/Integrations/ExabeamDataLake/ExabeamDataLake.yml
  Packs/ExabeamDataLake/ReleaseNotes/1_0_2.md
  Packs/ExabeamDataLake/pack_metadata.json
  Packs/ExabeamSecurityOperationsPlatform/Integrations/ExabeamSecOpsPlatform/ExabeamSecOpsPlatform.py
  Packs/ExabeamSecurityOperationsPlatform/Integrations/ExabeamSecOpsPlatform/ExabeamSecOpsPlatform.yml
  Packs/ExabeamSecurityOperationsPlatform/ReleaseNotes/1_1_2.md
  Packs/ExabeamSecurityOperationsPlatform/pack_metadata.json
Labels: docs-approved, ForceMerge

#38043 Fix Pylint errors in CommonScript and CSF
  Packs/CommonScripts/ReleaseNotes/1_19_8.md
  Packs/CommonScripts/Scripts/BMCTool/BMCTool.py
  Packs/CommonScripts/Scripts/BMCTool/BMCTool.yml
  Packs/CommonScripts/Scripts/CertificateReputation/CertificateReputation.py
  Packs/CommonScripts/Scripts/CertificateReputation/CertificateReputation.yml
  Packs/CommonScripts/Scripts/ClearUserSession/ClearUserSession.py
  Packs/CommonScripts/Scripts/ClearUserSession/ClearUserSession.yml
  Packs/CommonScripts/Scripts/GenerateAsBuiltConfiguration/GenerateAsBuiltConfiguration.py
  Packs/CommonScripts/Scripts/GenerateAsBuiltConfiguration/GenerateAsBuiltConfiguration.yml
  Packs/CommonScripts/Scripts/GetDockerImageLatestTag/GetDockerImageLatestTag.py
  Packs/CommonScripts/Scripts/GetDockerImageLatestTag/GetDockerImageLatestTag.yml
  Packs/CommonScripts/Scripts/GetDockerImageLatestTag/GetDockerImageLatestTag_test.py
  Packs/CommonScripts/Scripts/ResolveShortenedURL/ResolveShortenedURL.py
  Packs/CommonScripts/Scripts/ResolveShortenedURL/ResolveShortenedURL.yml
  Packs/CommonScripts/Scripts/UnzipFile/UnzipFile.py
  Packs/CommonScripts/Scripts/UnzipFile/UnzipFile.yml
  Packs/CommonScripts/pack_metadata.json
  Packs/CommunityCommonScripts/ReleaseNotes/1_3_11.md
  Packs/CommunityCommonScripts/Scripts/ExtFilter/ExtFilter.py
  Packs/CommunityCommonScripts/Scripts/ExtFilter/ExtFilter.yml
  Packs/CommunityCommonScripts/Scripts/ExtFilter/ExtFilter_test.py
  Packs/CommunityCommonScripts/pack_metadata.json
Labels: docs-approved

#37953 Remove ArcherV2 from skipped
  Tests/conf.json
Labels: docs-approved, sync-gsm

#38059 Fix Pylint errors in I + J packs
  Packs/IBMResilientSystems/Integrations/IBMResilientSystems/IBMResilientSystems.py
  Packs/IBMResilientSystems/Integrations/IBMResilientSystems/IBMResilientSystems.yml
  Packs/IBMResilientSystems/ReleaseNotes/1_2_1.md
  Packs/IBMResilientSystems/pack_metadata.json
  Packs/Infoblox/Integrations/Infoblox/Infoblox.py
  Packs/Infoblox/ReleaseNotes/1_1_5.md
  Packs/Infoblox/pack_metadata.json
  Packs/IronDefense/Integrations/IronDefense/IronDefense.py
  Packs/IronDefense/Integrations/IronDefense/IronDefense.yml
  Packs/IronDefense/ReleaseNotes/1_1_32.md
  Packs/IronDefense/pack_metadata.json
  Packs/IronPort/Integrations/CiscoEmailSecurityApplianceIronPortV2/CiscoEmailSecurityApplianceIronPortV2.py
  Packs/IronPort/ReleaseNotes/2_1_1.md
  Packs/IronPort/pack_metadata.json
  Packs/Jira/Integrations/JiraV3/JiraV3.py
  Packs/Jira/Integrations/JiraV3/JiraV3.yml
  Packs/Jira/ReleaseNotes/3_2_12.md
  Packs/Jira/pack_metadata.json
Labels: docs-approved

#38061 Fix Pylint errors in M packs
  Packs/ML/ReleaseNotes/1_4_19.md
  Packs/ML/Scripts/HashIncidentsFields/HashIncidentsFields.py
  Packs/ML/Scripts/HashIncidentsFields/HashIncidentsFields.yml
  Packs/ML/pack_metadata.json
  Packs/Malwarebytes/Integrations/Malwarebytes/Malwarebytes.py
  Packs/Malwarebytes/Integrations/Malwarebytes/Malwarebytes.yml
  Packs/Malwarebytes/ReleaseNotes/1_1_20.md
  Packs/Malwarebytes/pack_metadata.json
  Packs/McAfee_Advanced_Threat_Defense/Integrations/McAfee_Advanced_Threat_Defense/McAfee_Advanced_Threat_Defense.py
  Packs/McAfee_Advanced_Threat_Defense/Integrations/McAfee_Advanced_Threat_Defense/McAfee_Advanced_Threat_Defense.yml
  Packs/McAfee_Advanced_Threat_Defense/Integrations/McAfee_Advanced_Threat_Defense/McAfee_Advanced_Threat_Defense_test.py
  Packs/McAfee_Advanced_Threat_Defense/ReleaseNotes/1_0_30.md
  Packs/McAfee_Advanced_Threat_Defense/pack_metadata.json
  Packs/MinervaLabsAntiEvasionPlatform/Integrations/MinervaLabsAntiEvasionPlatform/MinervaLabsAntiEvasionPlatform.py
  Packs/MinervaLabsAntiEvasionPlatform/Integrations/MinervaLabsAntiEvasionPlatform/MinervaLabsAntiEvasionPlatform.yml
  Packs/MinervaLabsAntiEvasionPlatform/ReleaseNotes/1_0_12.md
  Packs/MinervaLabsAntiEvasionPlatform/pack_metadata.json
  Packs/MitreCaldera/ReleaseNotes/1_0_8.md
  Packs/MitreCaldera/Scripts/CalderaPopulateAgents/CalderaPopulateAgents.py
  Packs/MitreCaldera/Scripts/CalderaPopulateAgents/CalderaPopulateAgents.yml
  Packs/MitreCaldera/pack_metadata.json
Labels: docs-approved

#38072 Adding tpbs to skip
  Tests/conf.json
Labels: docs-approved

#38076 [pre-commit] PyLint disable E0601 and E0606
  .pre-commit-config_template.yaml
Labels: docs-approved

#38082 Fix Pylint errors in S part 1 packs
  Packs/SEKOIAIntelligenceCenter/Integrations/SEKOIAIntelligenceCenter/SEKOIAIntelligenceCenter.py
  Packs/SEKOIAIntelligenceCenter/Integrations/SEKOIAIntelligenceCenter/SEKOIAIntelligenceCenter.yml
  Packs/SEKOIAIntelligenceCenter/ReleaseNotes/1_2_35.md
  Packs/SEKOIAIntelligenceCenter/pack_metadata.json
  Packs/SafeBreach/Integrations/SafeBreach/SafeBreach.py
  Packs/SafeBreach/Integrations/SafeBreach/SafeBreach.yml
  Packs/SafeBreach/ReleaseNotes/1_4_6.md
  Packs/SafeBreach/pack_metadata.json
  Packs/SafeNet_Trusted_Access/Integrations/SafeNetTrustedAccess/SafeNetTrustedAccess.py
  Packs/SafeNet_Trusted_Access/Integrations/SafeNetTrustedAccess/SafeNetTrustedAccess.yml
  Packs/SafeNet_Trusted_Access/ReleaseNotes/2_0_42.md
  Packs/SafeNet_Trusted_Access/pack_metadata.json
  Packs/SalesforceV2/Integrations/SalesforceV2/SalesforceV2.py
  Packs/SalesforceV2/Integrations/SalesforceV2/SalesforceV2.yml
  Packs/SalesforceV2/ReleaseNotes/1_0_7.md
  Packs/SalesforceV2/pack_metadata.json
  Packs/SecureWorks/Integrations/TaegisXDRv2/TaegisXDRv2.py
  Packs/SecureWorks/Integrations/TaegisXDRv2/TaegisXDRv2.yml
  Packs/SecureWorks/ReleaseNotes/5_0_10.md
  Packs/SecureWorks/pack_metadata.json
  Packs/SendGrid/Integrations/SendGrid/SendGrid.py
  Packs/SendGrid/Integrations/SendGrid/SendGrid.yml
  Packs/SendGrid/ReleaseNotes/1_1_6.md
  Packs/SendGrid/pack_metadata.json
  Packs/SentinelOne/Integrations/SentinelOne-V2/SentinelOne-V2.py
  Packs/SentinelOne/Integrations/SentinelOne-V2/SentinelOne-V2.yml
  Packs/SentinelOne/ReleaseNotes/3_2_36.md
  Packs/SentinelOne/pack_metadata.json
  Packs/ServiceNow/ReleaseNotes/2_7_4.md
  Packs/ServiceNow/Scripts/ServiceNowQueryIncident/ServiceNowQueryIncident.py
  Packs/ServiceNow/Scripts/ServiceNowQueryIncident/ServiceNowQueryIncident.yml
  Packs/ServiceNow/pack_metadata.json
  Packs/Spamcop/Integrations/Spamcop/Spamcop.py
  Packs/Spamcop/Integrations/Spamcop/Spamcop.yml
  Packs/Spamcop/ReleaseNotes/1_0_10.md
  Packs/Spamcop/pack_metadata.json
Labels: docs-approved

#38074 AlibabaActionTrail Event Collector - Fixed a parsing error related to the First fetch time interval parameter
  Packs/AlibabaActionTrail/Integrations/AlibabaActionTrailEventCollector/AlibabaActionTrailEventCollector.py
  Packs/AlibabaActionTrail/Integrations/AlibabaActionTrailEventCollector/AlibabaActionTrailEventCollector.yml
  Packs/AlibabaActionTrail/ReleaseNotes/1_1_2.md
  Packs/AlibabaActionTrail/pack_metadata.json
Labels: docs-approved, ForceMerge

#38071 XSUP 45126 Cyberark Identity Update
  Packs/CyberArkIdentity/ModelingRules/CyberArkIdentityEventCollector_1_3/CyberArkIdentityEventCollector_1_3.xif
  Packs/CyberArkIdentity/ParsingRules/CyberArkIdentityParsingRules/CyberArkIdentityParsingRules.xif
  Packs/CyberArkIdentity/README.md
  Packs/CyberArkIdentity/ReleaseNotes/1_1_3.md
  Packs/CyberArkIdentity/pack_metadata.json
Labels: docs-approved

#38083 part 7 - fixing relative files
  Packs/Salesforce/Integrations/Salesforce/README.md
  Packs/Salesforce/doc_files/44449362-98450c80-a5f6-11e8-94e0-6a5b31093efb.png
  Packs/Salesforce/doc_files/44452383-0db4db00-a5ff-11e8-8f75-6027a8a339e2.png
  Packs/Salesforce/doc_files/44452464-43f25a80-a5ff-11e8-918a-7efb4af4ea29.png
  Packs/Salesforce/doc_files/44452529-66847380-a5ff-11e8-80af-32177c2479d0.png
  Packs/Salesforce/doc_files/44452576-874cc900-a5ff-11e8-9c5b-4ce0f75ae3f9.png
  Packs/Salesforce/doc_files/44452616-a8adb500-a5ff-11e8-96d5-46069125ce64 (1).png
  Packs/Salesforce/doc_files/44452616-a8adb500-a5ff-11e8-96d5-46069125ce64.png
  Packs/Salesforce/doc_files/44452804-1bb72b80-a600-11e8-9ab0-85b6fb631091.png
  Packs/Salesforce/doc_files/integration-Salesforce_mceclip1.png
  Packs/Salesforce/doc_files/integration-Salesforce_mceclip2.png
  Packs/Salesforce/doc_files/integration-Salesforce_mceclip3.png
  Packs/Salesforce/doc_files/integration-Salesforce_mceclip4.png
  Packs/Salesforce/doc_files/integration-Salesforce_mceclip5.png
  Packs/Salesforce/doc_files/integration-Salesforce_mceclip6.png
  Packs/Salesforce/doc_files/integration-Salesforce_mceclip7.png
  Packs/SecureWorks/Integrations/SecureWorks/README.md
  Packs/SecureWorks/doc_files/40653720-a9dd4e52-6344-11e8-8911-1988d74f4eb4.png
  Packs/SecureWorks/doc_files/40656711-f069e7be-634d-11e8-834e-23f454a48067.png
  Packs/SecureWorks/doc_files/40658614-78930ba6-6354-11e8-9b87-a125bd8d6d81.png
  Packs/SecureWorks/doc_files/40768782-f4c671ca-64be-11e8-9380-3240eb3629a3.png
  Packs/SecureWorks/doc_files/46961277-1a0e5f00-d0a9-11e8-946c-42bedfe8d4ac.png
  Packs/SecureWorks/doc_files/46999808-5f756f80-d12f-11e8-9219-108908a2bdfc.png
  Packs/SecureWorks/doc_files/47001732-d7459900-d133-11e8-90c4-4436dd18bf29.png
  Packs/SecureWorks/doc_files/47002456-b5e5ac80-d135-11e8-905b-f7f41c8e062c.png
  Packs/SecureWorks/doc_files/47002702-5cca4880-d136-11e8-826f-0f2400771017.png
  Packs/SecureWorks/doc_files/47002995-ef6ae780-d136-11e8-8c71-ce8d2d0e481e.png
  Packs/SecureWorks/doc_files/58482464-14ace300-8167-11e9-86c5-fa389b49a99c.png
  Packs/ShadowIT/README.md
  Packs/ShiftManagement/README.md
  Packs/SlashNextPhishingIncidentResponse/README.md
  Packs/SplunkPy/Playbooks/playbook-Splunk_Generic_README.md
  Packs/SplunkPy/Playbooks/playbook-Splunk_Indicator_Hunting_README.md
  Packs/SplunkPy/ReleaseNotes/3_1_51.md
  Packs/SplunkPy/pack_metadata.json
  Packs/Tanium/README.md
  Packs/TeamManagement/Playbooks/playbook-Set_Team_Members_README.md
  Packs/TeamManagement/doc_files/Set_Team_Members.png
  Packs/ThreatIntelReports/README.md
  Packs/VersaDirector/README.md
  Packs/WhatIsMyBrowser/Integrations/WhatIsMyBrowser/README.md
  Packs/WhatIsMyBrowser/doc_files/52565803-8e1b0280-2e10-11e9-9a79-d0172cde27d1.png
  Packs/Whois/Playbooks/playbook-TIM_-_Process_Domain_Age_With_Whois_README.md
  Packs/Whois/Playbooks/playbook-TIM_-_Process_Domains_With_Whois_README.md
  Packs/Whois/README.md
  Packs/Wiz/Playbooks/playbook-Assess_Wiz_Issues.yml
  Packs/Wiz/Playbooks/playbook-Assess_Wiz_Issues_README.md
  Packs/Wiz/README.md
  Packs/Wiz/ReleaseNotes/1_3_4.md
  Packs/Wiz/doc_files/Assess_Wiz_Issues.png
  Packs/Wiz/pack_metadata.json
  Packs/dnstwist/Integrations/dnstwist/README.md
  Packs/dnstwist/doc_files/dnswist_for_domain.png
  Packs/fireeye/Playbooks/playbook-Detonate_File_-_FireEye_AX_README.md
  Packs/fireeye/doc_files/Detonate_File_-_FireEye_AX.png
Labels: docs-approved

#37963 [EWS v2] Fix issue with files not opening
  Packs/MicrosoftExchangeOnPremise/Integrations/EWSv2/EWSv2.py
  Packs/MicrosoftExchangeOnPremise/ReleaseNotes/2_1_22.md
  Packs/MicrosoftExchangeOnPremise/pack_metadata.json
Labels: docs-approved, ForceMerge

#37954 CRTX-146122-ProofPoint-Email-Security
  Packs/ProofpointEmailSecurity/ModelingRules/ProofpointEmailSecurity/ProofpointEmailSecurity.xif
  Packs/ProofpointEmailSecurity/ModelingRules/ProofpointEmailSecurity/ProofpointEmailSecurity_schema.json
  Packs/ProofpointEmailSecurity/ParsingRules/ProofpointEmailSecurity/ProofpointEmailSecurity.xif
  Packs/ProofpointEmailSecurity/ParsingRules/ProofpointEmailSecurity/ProofpointEmailSecurity.yml
  Packs/ProofpointEmailSecurity/ReleaseNotes/1_0_6.md
  Packs/ProofpointEmailSecurity/pack_metadata.json
Labels: docs-approved

#37933 New Playbook - Suspicious Local Administrator Login
  Packs/CortexResponseAndRemediation/.pack-ignore
  Packs/CortexResponseAndRemediation/Playbooks/playbook-Suspicious_Local_Administrator_Login.yml
  Packs/CortexResponseAndRemediation/Playbooks/playbook-Suspicious_Local_Administrator_Login_README.md
  Packs/CortexResponseAndRemediation/ReleaseNotes/1_0_4.md
  Packs/CortexResponseAndRemediation/Triggers/Trigger_-_Suspicious_Local_Administrator_Login.json
  Packs/CortexResponseAndRemediation/doc_files/Suspicious_Local_Administrator_Login.png
  Packs/CortexResponseAndRemediation/pack_metadata.json
Labels: docs-approved, bypass.url

#38098 Remove native from .pre-commit-config_template.yaml
  .pre-commit-config_template.yaml
Labels: docs-approved

#38089 Netskope fixed zero division error
  Packs/Netskope/Integrations/NetskopeAPIv2/NetskopeAPIv2.py
  Packs/Netskope/Integrations/NetskopeAPIv2/NetskopeAPIv2_test.py
  Packs/Netskope/ReleaseNotes/4_0_5.md
  Packs/Netskope/pack_metadata.json
Labels: docs-approved, release-notes-only

#38079 CS Falcon: fix cs-falcon-search-device
  Packs/CrowdStrikeFalcon/Integrations/CrowdStrikeFalcon/CrowdStrikeFalcon.py
  Packs/CrowdStrikeFalcon/ReleaseNotes/2_1_5.md
  Packs/CrowdStrikeFalcon/pack_metadata.json
Labels: docs-approved

#38086 Fix Pylint errors in T packs
  Packs/Tanium/Integrations/Tanium_v2/Tanium_v2.py
  Packs/Tanium/Integrations/Tanium_v2/Tanium_v2.yml
  Packs/Tanium/ReleaseNotes/1_0_36.md
  Packs/Tanium/pack_metadata.json
  Packs/ThreatQ/Integrations/ThreatQ_v2/ThreatQ_v2.py
  Packs/ThreatQ/Integrations/ThreatQ_v2/ThreatQ_v2.yml
  Packs/ThreatQ/ReleaseNotes/1_0_28.md
  Packs/ThreatQ/pack_metadata.json
  Packs/ThreatZone/Integrations/ThreatZone/ThreatZone.py
  Packs/ThreatZone/Integrations/ThreatZone/ThreatZone.yml
  Packs/ThreatZone/ReleaseNotes/1_0_5.md
  Packs/ThreatZone/pack_metadata.json
  Packs/TrendMicroApex/Integrations/TrendMicroApex/TrendMicroApex.py
  Packs/TrendMicroApex/Integrations/TrendMicroApex/TrendMicroApex.yml
  Packs/TrendMicroApex/ReleaseNotes/2_0_8.md
  Packs/TrendMicroApex/pack_metadata.json
  Packs/TrendMicroVisionOne/Integrations/TrendMicroVisionOne/TrendMicroVisionOne.py
  Packs/TrendMicroVisionOne/Integrations/TrendMicroVisionOne/TrendMicroVisionOne.yml
  Packs/TrendMicroVisionOne/Integrations/TrendMicroVisionOne/TrendMicroVisionOne_test.py
  Packs/TrendMicroVisionOne/ReleaseNotes/4_2_1.md
  Packs/TrendMicroVisionOne/pack_metadata.json
Labels: docs-approved

#38102 Locked dependencies of core packs
  Packs/ThreatIntelReports/ReleaseNotes/1_0_20.md
  Packs/ThreatIntelReports/pack_metadata.json
  Packs/Whois/ReleaseNotes/1_5_20.md
  Packs/Whois/pack_metadata.json
Labels: docs-approved, bypass.url

#38068 ProofpointThreatResponseEventCollector: fixed bug in fetch events
  Packs/ProofpointThreatResponse/Integrations/ProofpointThreatResponseEventCollector/ProofpointThreatResponseEventCollector.py
  Packs/ProofpointThreatResponse/Integrations/ProofpointThreatResponseEventCollector/ProofpointThreatResponseEventCollector_test.py
  Packs/ProofpointThreatResponse/ReleaseNotes/2_0_20.md
  Packs/ProofpointThreatResponse/pack_metadata.json
Labels: docs-approved

#38106 Fix MISPV3 that returned indicator with DBot score unknown
  Packs/MISP/Integrations/MISPV3/MISPV3.py
  Packs/MISP/ReleaseNotes/2_1_50.md
  Packs/MISP/pack_metadata.json
Labels: docs-approved

#38099 Change all paths in Readme and Description file-part6
  Packs/BitDam/Playbooks/playbook-BitDam_Scan_File_README.md
  Packs/BitDam/doc_files/BitDam_Scan_File.png
  Packs/BreachNotification-US/README.md
  Packs/BruteForce/README.md
  Packs/CVE_2021_44228/README.md
  Packs/CVE_2022_26134/README.md
  Packs/Campaign/README.md
  Packs/Campaign/doc_files/campaign-overview.png
  Packs/CarbonBlackProtect/Playbooks/playbook-Carbon_black_Protection_Rapid_IOC_Hunting_README.md
  Packs/CarbonBlackProtect/Playbooks/playbook-Search_Endpoints_By_Hash_-_Carbon_Black_Protection_README.md
  Packs/CarbonBlackProtect/doc_files/Search_Endpoints_By_Hash_-_Carbon_Black_Protection.png
  Packs/CiscoASA/README.md
  Packs/CitrixADC/README.md
  Packs/CohesityHelios/README.md
  Packs/CyrenInboxSecurity/README.md
  Packs/DevSecOps/README.md
  Packs/DomainTools_Iris/Playbooks/playbook-Indicator_Pivoting-DomainTools_Iris_README.md
  Packs/DomainTools_Iris/doc_files/Indicator_Pivoting-DomainTools_Iris.png
  Packs/ExtraHop/Playbooks/playbook-ExtraHop_-_CVE-2019-0708_BlueKeep_README.md
  Packs/ExtraHop/Playbooks/playbook-ExtraHop_-_Default_README.md
  Packs/ExtraHop/Playbooks/playbook-ExtraHop_-_Get_Peers_by_Host_README.md
  Packs/ExtraHop/README.md
  Packs/ExtraHop/doc_files/ExtraHop_-_CVE-2019-0708_BlueKeep.png
  Packs/ExtraHop/doc_files/ExtraHop_-_Default.png
  Packs/ExtraHop/doc_files/ExtraHop_-_Get_Peers_by_Host.png
  Packs/ThreatIntelReports/ReleaseNotes/1_0_21.md
  Packs/ThreatIntelReports/pack_metadata.json
  Packs/Whois/ReleaseNotes/1_5_21.md
  Packs/Whois/pack_metadata.json
Labels: docs-approved, bypass.url

#38104 Change all paths in Readme and Description file- core packs
  Packs/Core/Playbooks/playbook-Ransomware_Advanced_Analysis_README.md
  Packs/CortexXDR/Playbooks/playbook-Cortex_XDR_-_Block_File_README.md
  Packs/CortexXDR/Playbooks/playbook-Cortex_XDR_-_Run_script_README.md
  Packs/CortexXDR/Playbooks/playbook-Cortex_XDR_disconnected_endpoints_README.md
  Packs/CortexXDR/Playbooks/playbook-JOB_-_Cortex_XDR_query_endpoint_device_control_violations_README.md
  Packs/CortexXDR/README.md
Labels: docs-approved, bypass.url

#38107 change all paths in readme and description - part 8
  Packs/PANWComprehensiveInvestigation/README.md
  Packs/PenfieldAI/Playbooks/Penfield_Assign_README.md
  Packs/PenfieldAI/doc_files/playbook_Penfield_Assign.png
  Packs/PhishingAlerts/Playbooks/playbook-Phishing_Alerts_-_Check_Severity_README.md
  Packs/PingCastle/Playbooks/SX_-_PC_-_PingCastle_Report_README.md
  Packs/PingCastle/doc_files/SX_-_PC_-_PingCastle_Report.png
  Packs/Portnox/README.md
  Packs/PrismaAccess/Playbooks/playbook-Prisma_Access_-_Connection_Health_Check_README.md
  Packs/PrismaAccess/Playbooks/playbook-Prisma_Access_Whitelist_Egress_IPs_on_SaaS_Services_README.md
  Packs/PrismaAccess/doc_files/Prisma_Access_-_Connection_Health_Check.png
  Packs/PrismaCloudCompute/Integrations/PaloAltoNetworks_PrismaCloudCompute/README.md
  Packs/PrismaCloudCompute/Playbooks/Prisma_Cloud_Compute_-_Audit_Alert_README.md
  Packs/PrismaCloudCompute/Playbooks/Prisma_Cloud_Compute_-_Compliance_Alert_README.md
  Packs/PrismaCloudCompute/Playbooks/playbook-Prisma_Cloud_Compute_-_Cloud_Discovery_Alert.yml
  Packs/PrismaCloudCompute/Playbooks/playbook-Prisma_Cloud_Compute_-_Cloud_Discovery_Alert_README.md
  Packs/PrismaCloudCompute/ReleaseNotes/1_7_10.md
  Packs/PrismaCloudCompute/doc_files/Prisma_Cloud_Compute_-_Cloud_Discovery_Alert.png
  Packs/PrismaCloudCompute/doc_files/available-user-roles.png
  Packs/PrismaCloudCompute/doc_files/user-roles-configuration.png
  Packs/PrismaCloudCompute/pack_metadata.json
  Packs/ProofpointServerProtection/Playbooks/playbook-Get_Email_From_Email_Gateway_-_Proofpoint_Protection_Server_README.md
  Packs/ProtectWise/Integrations/ProtectWise/README.md
  Packs/ProtectWise/doc_files/netflows.png
  Packs/ProtectWise/doc_files/protectwise_event_info.png
  Packs/ProtectWise/doc_files/protectwise_event_search.png
  Packs/ProtectWise/doc_files/protectwise_uploaded_file.png
  Packs/ProtectWise/doc_files/protectwith_sensors.png
  Packs/Ransomware/README.md
  Packs/RedCanary/Integrations/RedCanary/README.md
  Packs/RedCanary/doc_files/47003133-3c4ebe00-d137-11e8-98eb-ca627c18d7fd.png
  Packs/RedCanary/doc_files/47007260-80928c00-d140-11e8-8d41-6c9e90a9d615.png
  Packs/RedCanary/doc_files/47007379-c0597380-d140-11e8-98aa-531be44f8c56.png
  Packs/RedCanary/doc_files/47007761-a0767f80-d141-11e8-90e2-09c67fea5381.png
  Packs/RedCanary/doc_files/47012290-9d34c100-d14c-11e8-971c-7cb6187fd010.png
  Packs/RedCanary/doc_files/47012455-f13fa580-d14c-11e8-98fa-a49e288d325f.png
  Packs/RedCanary/doc_files/47012686-7b880980-d14d-11e8-95be-8c88dfda4cbf.png
  Packs/RedCanary/doc_files/47012822-e6d1db80-d14d-11e8-9773-0b69802f9ba8.png
  Packs/RiskSense/Playbooks/playbook-CVE_Exposure_-_RiskSense_README.md
  Packs/RiskSense/Playbooks/playbook-Ransomware_Exposure_-_RiskSense_README.md
  Packs/RsaNetWitnessPacketsAndLogs/Integrations/RSANetWitnessPacketsAndLogs/README.md
  Packs/RsaNetWitnessPacketsAndLogs/doc_files/38615982-2db34cce-3d9b-11e8-8a7e-48a679f0d10c.png
  Packs/RsaNetWitnessPacketsAndLogs/doc_files/38616096-834a48e0-3d9b-11e8-8b06-a2a0a309a95e.png
  Packs/RsaNetWitnessPacketsAndLogs/doc_files/38616236-f1648674-3d9b-11e8-8e27-e805af8d0679.png
  Packs/RsaNetWitnessPacketsAndLogs/doc_files/38616272-1ae3b682-3d9c-11e8-81db-f873a0c0e454.png
  Packs/RsaNetWitnessPacketsAndLogs/doc_files/38617765-8289dd30-3da0-11e8-9d43-07e43711cbd5.png
  Packs/RsaNetWitnessPacketsAndLogs/doc_files/38617956-fe7a9a24-3da0-11e8-9a0a-62762a81ff8c.png
  Packs/RsaNetWitnessPacketsAndLogs/doc_files/38618665-00d56770-3da3-11e8-84ab-364a38e82cfe.png
  Packs/RsaNetWitnessPacketsAndLogs/doc_files/38619069-02ebbb4e-3da4-11e8-97be-d9f096860fae.png
  Packs/RubrikPolaris/README.md
  Packs/Rundeck/Playbooks/Rundeck-job-execute-Generic_README.md
Labels: docs-approved, bypass.url

#38081 Fix remote-access documentation
  Packs/RemoteAccess/Integrations/RemoteAccessv2/README.md
Labels: docs-approved

#38093 Fix Pylint errors in A packs
  Packs/AHA/Integrations/AHA/AHA.py
  Packs/AHA/Integrations/AHA/AHA.yml
  Packs/AHA/Integrations/AHA/AHA_test.py
  Packs/AHA/ReleaseNotes/1_0_29.md
  Packs/AHA/pack_metadata.json
  Packs/AccentureCTI/Integrations/ACTIIndicatorQuery/ACTIIndicatorQuery.py
  Packs/AccentureCTI/Integrations/ACTIIndicatorQuery/ACTIIndicatorQuery.yml
  Packs/AccentureCTI/ReleaseNotes/2_2_41.md
  Packs/AccentureCTI/pack_metadata.json
  Packs/Akamai_WAF/Integrations/Akamai_WAF/Akamai_WAF.py
  Packs/Akamai_WAF/Integrations/Akamai_WAF/Akamai_WAF.yml
  Packs/Akamai_WAF/ReleaseNotes/2_1_1.md
  Packs/Akamai_WAF/pack_metadata.json
  Packs/ArcherRSA/Integrations/ArcherV2/ArcherV2.py
  Packs/ArcherRSA/Integrations/ArcherV2/ArcherV2.yml
  Packs/ArcherRSA/ReleaseNotes/1_2_22.md
  Packs/ArcherRSA/pack_metadata.json
  Packs/Armis/Integrations/ArmisEventCollector/ArmisEventCollector.py
  Packs/Armis/Integrations/ArmisEventCollector/ArmisEventCollector.yml
  Packs/Armis/ReleaseNotes/1_1_19.md
  Packs/Armis/pack_metadata.json
  Packs/AzureLogAnalytics/Integrations/AzureLogAnalytics/AzureLogAnalytics.py
  Packs/AzureLogAnalytics/Integrations/AzureLogAnalytics/AzureLogAnalytics.yml
  Packs/AzureLogAnalytics/ReleaseNotes/1_1_42.md
  Packs/AzureLogAnalytics/pack_metadata.json
  Packs/AzureRiskyUsers/Integrations/AzureRiskyUsers/AzureRiskyUsers.py
  Packs/AzureRiskyUsers/Integrations/AzureRiskyUsers/AzureRiskyUsers.yml
  Packs/AzureRiskyUsers/ReleaseNotes/1_1_42.md
  Packs/AzureRiskyUsers/pack_metadata.json
Labels: docs-approved, ForceMerge

#38064 Fix Pylint errors in N packs
  Packs/NationalVulnerabilityDatabaseFeed/Integrations/NationalVulnerabilityDatabaseFeed/NationalVulnerabilityDatabaseFeed.py
  Packs/NationalVulnerabilityDatabaseFeed/Integrations/NationalVulnerabilityDatabaseFeed/NationalVulnerabilityDatabaseFeed.yml
  Packs/NationalVulnerabilityDatabaseFeed/ReleaseNotes/1_0_9.md
  Packs/NationalVulnerabilityDatabaseFeed/pack_metadata.json
  Packs/Netcraft_V2/Integrations/Netcraft/Netcraft.py
  Packs/Netcraft_V2/Integrations/Netcraft/Netcraft.yml
  Packs/Netcraft_V2/ReleaseNotes/1_0_4.md
  Packs/Netcraft_V2/pack_metadata.json
  Packs/NetscoutArborSightline/Integrations/NetscoutArborSightline/NetscoutArborSightline.py
  Packs/NetscoutArborSightline/Integrations/NetscoutArborSightline/NetscoutArborSightline.yml
  Packs/NetscoutArborSightline/Integrations/NetscoutArborSightline/NetscoutArborSightline_test.py
  Packs/NetscoutArborSightline/ReleaseNotes/1_0_19.md
  Packs/NetscoutArborSightline/pack_metadata.json
  Packs/Nexthink/Integrations/Nexthink/Nexthink.py
  Packs/Nexthink/Integrations/Nexthink/Nexthink.yml
  Packs/Nexthink/ReleaseNotes/1_0_6.md
  Packs/Nexthink/pack_metadata.json
Labels: docs-approved, ForceMerge

#37932 [Panorama] MyPy In Docker
  Packs/PAN-OS/Integrations/Panorama/Panorama.py
  Packs/PAN-OS/ReleaseNotes/2_3_2.md
  Packs/PAN-OS/pack_metadata.json
Labels: ForceMerge

#37995 [McAfeeNSMv2] MyPy In Docker
  Packs/McAfeeNSM/Integrations/McAfeeNSMv2/McAfeeNSMv2.py
  Packs/McAfeeNSM/Integrations/McAfeeNSMv2/McAfeeNSMv2.yml
  Packs/McAfeeNSM/ReleaseNotes/1_2_20.md
  Packs/McAfeeNSM/pack_metadata.json
Labels: docs-approved, ForceMerge

#38108 Change all paths in Readme and Description file-part9
  Packs/Cylance_Protect/Playbooks/playbook-Endpoint_Enrichment_-_Cylance_Protect_v2_README.md
  Packs/Cylance_Protect/Playbooks/playbook-Get_File_Sample_By_Hash_-_Cylance_Protect_README.md
  Packs/Cylance_Protect/Playbooks/playbook-Get_File_Sample_By_Hash_-_Cylance_Protect_v2_README.md
  Packs/Cylance_Protect/doc_files/Endpoint_Enrichment_-_Cylance_Protect_v2.png
  Packs/Cylance_Protect/doc_files/Get_File_Sample_By_Hash_-_Cylance_Protect.png
  Packs/Cylance_Protect/doc_files/Get_File_Sample_By_Hash_-_Cylance_Protect_v2.png
  Packs/F5LTM/README.md
  Packs/FeedAzure/Playbooks/playbook-TIM_-_Process_Azure_indicators_README.md
  Packs/FeedCyrenThreatInDepth/README.md
  Packs/FeedOffice365/Playbooks/playbook-TIM_-_Process_Office365_indicators_README.md
  Packs/FireEyeEX/Playbooks/playbook-Block_Domain_-_FireEye_Email_Security_README.md
  Packs/FireEyeEX/Playbooks/playbook-Get_Email_From_Email_Gateway_-_FireEye_README.md
  Packs/GCP-Enrichment-Remediation/README.md
  Packs/GCP-Enrichment-Remediation/ReleaseNotes/1_1_21.md
  Packs/GCP-Enrichment-Remediation/pack_metadata.json
  Packs/GDPR/Playbooks/playbook-GDPR_Breach_Notification_README.md
  Packs/GDPR/README.md
  Packs/GRR/Integrations/GRR/README.md
  Packs/GRR/doc_files/grr_get_clients.png
  Packs/GRR/doc_files/grr_get_flows.png
  Packs/GRR/doc_files/grr_get_hunt_hunt_id.png
  Packs/GRR/doc_files/grr_get_hunts.png
  Packs/GRR/doc_files/grr_set_flows.png
  Packs/GRR/doc_files/grr_set_hunts.png
  Packs/GettingStartedWithXSOAR/README.md
  Packs/GoogleCloudCompute/Playbooks/playbook-IP_Whitelist_-_GCP_Firewall_README.md
  Packs/GoogleCloudCompute/ReleaseNotes/1_1_16.md
  Packs/GoogleCloudCompute/pack_metadata.json
  Packs/HIPAA-BreachNotification/README.md
Labels: docs-approved, bypass.url

#38097 Add logs to xql query
  Packs/ApiModules/ReleaseNotes/2_2_38.md
  Packs/ApiModules/Scripts/CoreXQLApiModule/CoreXQLApiModule.py
  Packs/ApiModules/pack_metadata.json
  Packs/Core/ReleaseNotes/3_2_19.md
  Packs/Core/pack_metadata.json
  Packs/CortexXDR/ReleaseNotes/6_2_6.md
  Packs/CortexXDR/pack_metadata.json
Labels: docs-approved

#37990 [EWSO365] MyPy In Docker
  Packs/MicrosoftExchangeOnline/Integrations/EWSO365/EWSO365.py
  Packs/MicrosoftExchangeOnline/Integrations/EWSO365/EWSO365.yml
  Packs/MicrosoftExchangeOnline/ReleaseNotes/1_5_24.md
  Packs/MicrosoftExchangeOnline/pack_metadata.json
Labels: docs-approved

#38105 add retry
  Packs/Base/ReleaseNotes/1_39_13.md
  Packs/Base/TestPlaybooks/ValidateContent_-_Test.yml
  Packs/Base/pack_metadata.json
Labels: docs-approved, sync-gsm

#37977 Aud demisto/auto update docker staging branch 89
  Packs/Campaign/ReleaseNotes/3_4_15.md
  Packs/Campaign/Scripts/FindEmailCampaign/FindEmailCampaign.py
  Packs/Campaign/pack_metadata.json
  Packs/CommonScripts/ReleaseNotes/1_19_9.md
  Packs/CommonScripts/Scripts/GetDomainDNSDetails/GetDomainDNSDetails.yml
  Packs/CommonScripts/Scripts/GetDomainDNSDetails/GetDomainDNSDetails_test.py
  Packs/CommonScripts/Scripts/Ping/Ping.yml
  Packs/CommonScripts/pack_metadata.json
  Packs/FeedPublicDNS/Integrations/FeedPublicDNS/FeedPublicDNS.yml
  Packs/FeedPublicDNS/ReleaseNotes/1_0_18.md
  Packs/FeedPublicDNS/pack_metadata.json
  Packs/FiltersAndTransformers/ReleaseNotes/1_2_88.md
  Packs/FiltersAndTransformers/Scripts/IPv4Blacklist/IPv4Blacklist.yml
  Packs/FiltersAndTransformers/Scripts/IPv4Whitelist/IPv4Whitelist.yml
  Packs/FiltersAndTransformers/Scripts/IsRFC1918Address/IsRFC1918Address.yml
  Packs/FiltersAndTransformers/pack_metadata.json
  Packs/Mattermost/ReleaseNotes/2_0_7.md
  Packs/Mattermost/pack_metadata.json
  Packs/Phishing/ReleaseNotes/3_6_30.md
  Packs/Phishing/Scripts/FindDuplicateEmailIncidents/FindDuplicateEmailIncidents.yml
  Packs/Phishing/pack_metadata.json
  Packs/ProofpointEmailSecurity/Integrations/ProofpointEmailSecurityEventCollector/ProofpointEmailSecurityEventCollector.yml
  Packs/ProofpointEmailSecurity/ReleaseNotes/1_0_7.md
  Packs/ProofpointEmailSecurity/pack_metadata.json
  Packs/rasterize/Integrations/rasterize/rasterize.yml
  Packs/rasterize/ReleaseNotes/2_0_36.md
  Packs/rasterize/pack_metadata.json
Labels: docs-approved, ForceMerge

#38063 Enhancement for Exchange forwarding rule
  Packs/CortexResponseAndRemediation/Playbooks/playbook-Exchange_forwarding_rule_configured.yml
  Packs/CortexResponseAndRemediation/Playbooks/playbook-Exchange_forwarding_rule_configured_README.md
  Packs/CortexResponseAndRemediation/ReleaseNotes/1_0_6.md
  Packs/CortexResponseAndRemediation/Triggers/Trigger_-_Exchange_forwarding_rule_configured.json
  Packs/CortexResponseAndRemediation/doc_files/Exchange_forwarding_rule_configured.png
  Packs/CortexResponseAndRemediation/pack_metadata.json
Labels: docs-approved, bypass.url

#38122 Change all paths in Readme and Description file-part10
  Packs/HelloWorld/Playbooks/playbook-Handle_Hello_World_Alert_README.md
  Packs/Humio/Playbooks/playbook-Humio_QueryJob_Poll_README.md
  Packs/Humio/doc_files/Humio_QueryJob_Poll.png
  Packs/ImpossibleTraveler/README.md
  Packs/InfoArmor_VigilanteATI/Integrations/InfoArmorVigilanteATI/README.md
  Packs/InfoArmor_VigilanteATI/doc_files/49703409-71463100-fc0d-11e8-81e8-96fdb7eb04fe.png
  Packs/InfoArmor_VigilanteATI/doc_files/49703479-5cb66880-fc0e-11e8-817f-508a2b963d47.png
  Packs/InfoArmor_VigilanteATI/doc_files/49703730-6d1c1280-fc11-11e8-8e08-139ff002bbcf.png
  Packs/InfoArmor_VigilanteATI/doc_files/49703770-077c5600-fc12-11e8-8f2b-372b4014f2ac.png
  Packs/InfoArmor_VigilanteATI/doc_files/49703803-7a85cc80-fc12-11e8-8dd2-96feb2ab4a44.png
  Packs/InfoArmor_VigilanteATI/doc_files/49703847-fc75f580-fc12-11e8-8b0b-34754ee045c7.png
  Packs/InfoArmor_VigilanteATI/doc_files/49703860-1e6f7800-fc13-11e8-8480-45fe81652b7f.png
  Packs/InfoArmor_VigilanteATI/doc_files/49703867-3941ec80-fc13-11e8-9d11-26c1dc86e815.png
  Packs/InfoArmor_VigilanteATI/doc_files/49703874-4c54bc80-fc13-11e8-9cb5-688e59fecdc6.png
  Packs/InfoArmor_VigilanteATI/doc_files/vigilante_query_ecrime_db.png
  Packs/LinuxEventsCollection/README.md
  Packs/LogsignSiem/Integrations/LogsignSiem/README.md
  Packs/LogsignSiem/doc_files/logsign-fetch-inc-HR.jpg
  Packs/MITRECoA/README.md
  Packs/MailSenderNew/Integrations/MailSenderNew/README.md
  Packs/MailSenderNew/doc_files/58482464-14ace300-8167-11e9-86c5-fa389b49a99c.png
  Packs/MalwareInvestigationAndResponse/README.md
  Packs/MaxMind_GeoIP2/Integrations/MaxMind_GeoIP2/README.md
  Packs/MaxMind_GeoIP2/doc_files/51251659-864b7800-19a2-11e9-9273-6508d2db872e.png
  Packs/McAfeeNSM/README.md
  Packs/MicrosoftExchangeOnPremise/Playbooks/playbook-Process_Email_-_EWS_README.md
  Packs/MicrosoftExchangeOnPremise/Playbooks/playbook-Search_And_Delete_Emails_-_EWS_README.md
  Packs/MicrosoftExchangeOnPremise/doc_files/Process_Email_-_EWS.png
  Packs/MicrosoftExchangeOnPremise/doc_files/Search_And_Delete_Emails_-_EWS.png
  Packs/MicrosoftExchangeOnline/Playbooks/playbook-Office_365_Search_and_Delete_README.md
  Packs/MicrosoftIISWebServer/README.md
  Packs/MicrosoftWSUS/README.md
Labels: docs-approved, bypass.url

#37898 Ciac 10837/content path
  .pre-commit-config_template.yaml
  Packs/Active_Directory_Query/Scripts/UserEnrichAD/README.md
  Packs/AgariPhishingDefense/Integrations/AgariPhishingDefense/CHANGELOG.md
  Packs/Base/Scripts/DBotPreprocessTextData/DBotPreprocessTextData_test.py
  Packs/Base/Scripts/DBotSuggestClassifierMapping/DBotSuggestClassifierMapping_test.py
  Packs/Base/Scripts/DBotTrainClustering/DBotTrainClustering_test.py
  Packs/Base/Scripts/WordTokenizerV2/WordTokenizerV2_test.py
  Packs/BmcITSM/Classifiers/classifier-BMC_ITSM_Classifier.json
  Packs/BmcITSM/Classifiers/classifier-BMC_ITSM_Incoming_Mapper.json
  Packs/BmcITSM/Classifiers/classifier-BMC_ITSM_Outgoing_Mapper.json
  Packs/Bonusly/Integrations/Bonusly/CHANGELOG.md
  Packs/Bonusly/Scripts/IncOwnerToBonuslyUser/CHANGELOG.md
  Packs/Campaign/Scripts/GetCampaignIncidentsInfo/GetCampaignIncidentsInfo_test.py
  Packs/CaseManagement-Generic/Scripts/TimersOnOwnerChange/CHANGELOG.md
  Packs/CiscoSMA/Classifiers/classifier-CiscoSMA-Incoming-Mapper.json
  Packs/CommonScripts/.secrets-ignore
  Packs/CommonScripts/Scripts/AssignToMeButton/CHANGELOG.md
  Packs/CommonScripts/Scripts/DBotUpdateLogoURLPhishing/DBotUpdateLogoURLPhishing_test.py
  Packs/CommonScripts/Scripts/FileToBase64List/FileToBase64List_test.py
  Packs/CommonScripts/Scripts/FindSimilarIncidentsV2/FindSimilarIncidentsV2_test.py
  Packs/CommonScripts/Scripts/FormatURL/.secrets-ignore
  Packs/CommonScripts/Scripts/GenerateSummaryReportButton/CHANGELOG.md
  Packs/CommonScripts/Scripts/IPNetwork/.secrets-ignore
  Packs/CommonScripts/Scripts/LinkIncidentsButton/CHANGELOG.md
  Packs/CommonScripts/Scripts/LookupCSV/.secrets-ignore
  Packs/CommunityCommonScripts/Scripts/isArrayItemInList/isArrayItemInList.py
  Packs/CommunityCommonScripts/Scripts/isArrayItemInList/isArrayItemInList.yml
  Packs/DigitalShadows/Scripts/DsSearchQueryArray/DsSearchQueryArray_test.py
  Packs/DigitalShadows/Scripts/DsSearchQueryArray/DsSearchQueryTestData.py
  Packs/FeedCrowdstrikeFalconIntel/Integrations/FeedCrowdstrikeFalconIntel/CHANGELOG.md
  Packs/FeedMitreAttack/.pack-ignore
  Packs/FiltersAndTransformers/.secrets-ignore
  Packs/FiltersAndTransformers/Scripts/GreaterCidrNumAddresses/.secrets-ignore
  Packs/FiltersAndTransformers/Scripts/LowerCidrNumAddresses/.secrets-ignore
  Packs/HYASInsight/Integrations/HYASInsight/Pipfile
  Packs/HelloIAMWorld/Integrations/HelloIAMWorld/README.md
  Packs/HelloIAMWorld/Integrations/HelloIAMWorld/README_example.md
  Packs/HelloWorld/.secrets-ignore
  Packs/HelloWorld/Integrations/FeedHelloWorld/.secrets-ignore
  Packs/IronPort/Classifiers/classifier-CiscoESA-Incoming-Mapper.json
  Packs/ML/Scripts/HashIncidentsFields/HashIncidentsFields_test.py
  Packs/MandiantAdvantageThreatIntelligence/.secrets-ignore
  Packs/MandiantAdvantageThreatIntelligence/Integrations/Mandiant/.secrets-ignore
  Packs/MicrosoftExchangeOnline/Scripts/GetEWSFolder/GetEWSFolder_test.py
  Packs/PhishingURL/Scripts/DBotPredictURLPhishing/DBotPredictURLPhishing_test.py
  Packs/QualysFIM/Integrations/QualysFIM/QualysFIM.yml
  Packs/QualysFIM/TestPlaybooks/QualysFIM-Playbook.yml
  Packs/QutteraWebsiteMalwareScanner/.secrets-ignore
  Packs/QutteraWebsiteMalwareScanner/Integrations/QutteraWebsiteMalwareScanner/.secrets-ignore
  Packs/Reco/Classifiers/classifier-Reco_Incident_Mapper.json
  Packs/StarterPack/Integrations/BaseIntegration/README_example.md
  Packs/StarterPack/Scripts/BaseScript/README_example.md
  Packs/Symantec_Messaging_Gateway/Playbooks/playbook-Block_Domain_-_Symantec_Messaging_Gateway_README.md
  Packs/Symantec_Messaging_Gateway/Playbooks/playbook-Symantec_block_Email_README.md
  Packs/Symantec_Messaging_Gateway/docs_files/Block_Domain_-_Symantec_Messaging_Gateway.png
  Packs/Symantec_Messaging_Gateway/docs_files/Symantec_block_Email.png
  Packs/TAXIIServer/.secrets-ignore
  Packs/TAXIIServer/Integrations/TAXII2Server/.secrets-ignore
  Tests/conf.json
Labels: bypass.url

#38109 XSUP-45578
  Packs/CommonScripts/ReleaseNotes/1_19_10.md
  Packs/CommonScripts/Scripts/HttpV2/HttpV2.py
  Packs/CommonScripts/Scripts/HttpV2/HttpV2.yml
  Packs/CommonScripts/pack_metadata.json
Labels: docs-approved

#38051 A small fix in CSP, FireEye, O365 for supporting python 3.12
  Packs/Base/ReleaseNotes/1_39_14.md
  Packs/Base/Scripts/CommonServerPython/CommonServerPython.py
  Packs/Base/pack_metadata.json
  Packs/FireEyeHX/Integrations/FireEyeHXv2/FireEyeHXv2.py
  Packs/FireEyeHX/ReleaseNotes/2_3_18.md
  Packs/FireEyeHX/pack_metadata.json
  Packs/MicrosoftExchangeOnline/Integrations/EWSO365/EWSO365.py
  Packs/MicrosoftExchangeOnline/ReleaseNotes/1_5_25.md
  Packs/MicrosoftExchangeOnline/pack_metadata.json
Labels: docs-approved

#38077 Fix Pylint errors in R packs
  Packs/Reco/Integrations/Reco/Reco.py
  Packs/Reco/Integrations/Reco/Reco.yml
  Packs/Reco/ReleaseNotes/1_5_4.md
  Packs/Reco/pack_metadata.json
  Packs/ReversingLabs_TitaniumScale/Integrations/ReversingLabsTitaniumScale/ReversingLabsTitaniumScale.py
  Packs/ReversingLabs_TitaniumScale/Integrations/ReversingLabsTitaniumScale/ReversingLabsTitaniumScale.yml
  Packs/ReversingLabs_TitaniumScale/ReleaseNotes/1_2_1.md
  Packs/ReversingLabs_TitaniumScale/pack_metadata.json
  Packs/ReversingLabs_Titanium_Cloud/Integrations/ReversingLabsTitaniumCloudv2/ReversingLabsTitaniumCloudv2.py
  Packs/ReversingLabs_Titanium_Cloud/Integrations/ReversingLabsTitaniumCloudv2/ReversingLabsTitaniumCloudv2.yml
  Packs/ReversingLabs_Titanium_Cloud/ReleaseNotes/2_6_1.md
  Packs/ReversingLabs_Titanium_Cloud/pack_metadata.json
  Packs/Rundeck/Integrations/Rundeck/Rundeck.py
  Packs/Rundeck/Integrations/Rundeck/Rundeck.yml
  Packs/Rundeck/Integrations/Rundeck/Rundeck_test.py
  Packs/Rundeck/ReleaseNotes/1_0_18.md
  Packs/Rundeck/TestPlaybooks/Rundeck_test.yml
  Packs/Rundeck/pack_metadata.json
  Tests/conf.json
Labels: docs-approved, sync-gsm

#38052 AUD-demisto/auto_update_docker_staging_branch_88
  Packs/Base/ReleaseNotes/1_39_15.md
  Packs/Base/Scripts/ValidateContent/ValidateContent.yml
  Packs/Base/pack_metadata.json
  Packs/CommonScripts/Scripts/ContentPackInstaller/ContentPackInstaller.yml
  Packs/ContentManagement/ReleaseNotes/1_2_28.md
  Packs/ContentManagement/Scripts/CommitFiles/CommitFiles.yml
  Packs/ContentManagement/Scripts/ConfigurationSetup/ConfigurationSetup.yml
  Packs/ContentManagement/Scripts/CustomPackInstaller/CustomPackInstaller.yml
  Packs/ContentManagement/Scripts/GetIdsFromCustomContent/GetIdsFromCustomContent.yml
  Packs/ContentManagement/Scripts/JobCreator/JobCreator.yml
  Packs/ContentManagement/Scripts/ListCreator/ListCreator.yml
  Packs/ContentManagement/pack_metadata.json
  Packs/CovalenceForSecurityProviders/Integrations/CovalenceForSecurityProviders/CovalenceForSecurityProviders.yml
  Packs/CovalenceForSecurityProviders/ReleaseNotes/1_1_5.md
  Packs/CovalenceForSecurityProviders/pack_metadata.json
Labels: docs-approved, ForceMerge

#37930 Update ruff version to 0.8.0
  .pre-commit-config_template.yaml
  nightly_ruff.toml
  pyproject.toml
Labels: docs-approved

#38133 [BoxV2] MyPy In Docker
  Packs/Box/Integrations/BoxV2/BoxV2.py
  Packs/Box/Integrations/BoxV2/BoxV2.yml
  Packs/Box/ReleaseNotes/3_2_9.md
  Packs/Box/pack_metadata.json
Labels: docs-approved, ForceMerge

#38137 [SymantecEmailSecurity] MyPy In Docker
  Packs/SymantecEmailSecurity/Integrations/SymantecEmailSecurity/SymantecEmailSecurity.py
  Packs/SymantecEmailSecurity/Integrations/SymantecEmailSecurity/SymantecEmailSecurity.yml
  Packs/SymantecEmailSecurity/ReleaseNotes/1_0_1.md
  Packs/SymantecEmailSecurity/pack_metadata.json
Labels: docs-approved, ForceMerge

#37483 Add ErrorReasons to 'core-action-status-get' Command
  Packs/ApiModules/Scripts/CoreIRApiModule/CoreIRApiModule.py
  Packs/ApiModules/Scripts/CoreIRApiModule/CoreIRApiModule_test.py
  Packs/ApiModules/Scripts/CoreIRApiModule/test_data/action_status_get.json
  Packs/Core/Integrations/CortexCoreIR/CortexCoreIR.yml
  Packs/Core/Integrations/CortexCoreIR/README.md
  Packs/Core/ReleaseNotes/3_2_20.md
  Packs/Core/pack_metadata.json
  Packs/CortexXDR/Integrations/CortexXDRIR/CortexXDRIR.yml
  Packs/CortexXDR/Integrations/CortexXDRIR/README.md
  Packs/CortexXDR/ReleaseNotes/6_2_7.md
  Packs/CortexXDR/pack_metadata.json
  Packs/ctf01/ReleaseNotes/1_0_36.md
  Packs/ctf01/pack_metadata.json
Labels: docs-approved

#38138 Revert "Update ruff version to 0.8.0"
  .pre-commit-config_template.yaml
  nightly_ruff.toml
  pyproject.toml
Labels: docs-approved

#38148 Fix-cs-t1059-playbook
  Packs/CrowdStrikeFalcon/Layouts/layoutscontainer-CrowdStrike_Falcon_Layout.json
  Packs/CrowdStrikeFalcon/Playbooks/playbook-Command_and_Scripting_Interpreter.yml
  Packs/CrowdStrikeFalcon/ReleaseNotes/2_1_6.md
  Packs/CrowdStrikeFalcon/pack_metadata.json
Labels: docs-approved

#37730 New 1Password XSIAM Integration
  Packs/OnePassword/.pack-ignore
  Packs/OnePassword/.secrets-ignore
  Packs/OnePassword/Author_image.png
  Packs/OnePassword/Integrations/OnePassword/OnePassword.py
  Packs/OnePassword/Integrations/OnePassword/OnePassword.yml
  Packs/OnePassword/Integrations/OnePassword/OnePassword_description.md
  Packs/OnePassword/Integrations/OnePassword/OnePassword_image.png
  Packs/OnePassword/Integrations/OnePassword/OnePassword_test.py
  Packs/OnePassword/Integrations/OnePassword/README.md
  Packs/OnePassword/Integrations/OnePassword/command_examples
  Packs/OnePassword/Integrations/OnePassword/test_data/auditevents_expected_events.json
  Packs/OnePassword/Integrations/OnePassword/test_data/auditevents_response_1.json
  Packs/OnePassword/Integrations/OnePassword/test_data/auditevents_response_2.json
  Packs/OnePassword/Integrations/OnePassword/test_data/signinattempts_response.json
  Packs/OnePassword/README.md
  Packs/OnePassword/pack_metadata.json
  Tests/docker_native_image_config.json
Labels: docs-approved, python

#38144 Fix additional ruff errors
  Packs/Troubleshoot/ReleaseNotes/2_1_7.md
  Packs/Troubleshoot/Scripts/TroubleshootExecutePlaybookByAlertQuery/TroubleshootExecutePlaybookByAlertQuery.py
  Packs/Troubleshoot/pack_metadata.json
Labels: docs-approved

#38150 10611 finshes part 3 1
  Packs/NIST/README.md
Labels: docs-approved, bypass.url

#38139 [MongoDBAtlasEventCollector] MyPy In Docker
  Packs/MongoDBAtlas/Integrations/MongoDBAtlasEventCollector/MongoDBAtlasEventCollector.py
  Packs/MongoDBAtlas/Integrations/MongoDBAtlasEventCollector/MongoDBAtlasEventCollector.yml
  Packs/MongoDBAtlas/ReleaseNotes/1_0_2.md
  Packs/MongoDBAtlas/pack_metadata.json
Labels: docs-approved

#38140 [FindEmailCampaign] MyPy In Docker
  Packs/Campaign/ReleaseNotes/3_4_16.md
  Packs/Campaign/Scripts/FindEmailCampaign/FindEmailCampaign.py
  Packs/Campaign/pack_metadata.json
Labels: docs-approved, ForceMerge

#38136 [Alibaba] MyPy In Docker
  Packs/AlibabaActionTrail/Integrations/AlibabaActionTrailEventCollector/AlibabaActionTrailEventCollector.py
  Packs/AlibabaActionTrail/Integrations/AlibabaActionTrailEventCollector/AlibabaActionTrailEventCollector.yml
  Packs/AlibabaActionTrail/ReleaseNotes/1_1_3.md
  Packs/AlibabaActionTrail/pack_metadata.json
Labels: ForceMerge

#38154 unfreeze autoupdate flow cyberark
  Packs/cyberark_AIM/Integrations/CyberArkAIM_v2/CyberArkAIM_v2.yml
Labels: ForceMerge

#38161 10611 finshes part 3_3
  Packs/OnboardingIntegration/Playbooks/playbook-PhishingDemo-Onboarding_README.md
  Packs/OpenCTI/Playbooks/OpenCTI_-_Create_Indicator_README.md
Labels: docs-approved, bypass.url

#38112 ReversingLabs A1000 v2.4.4
  Packs/ReversingLabs_A1000/CONTRIBUTORS.json
  Packs/ReversingLabs_A1000/Integrations/ReversingLabsA1000v2/README.md
  Packs/ReversingLabs_A1000/Integrations/ReversingLabsA1000v2/ReversingLabsA1000v2.py
  Packs/ReversingLabs_A1000/Integrations/ReversingLabsA1000v2/ReversingLabsA1000v2.yml
  Packs/ReversingLabs_A1000/ReleaseNotes/2_4_4.md
  Packs/ReversingLabs_A1000/pack_metadata.json
Labels: Contribution, docs-approved, Partner, Contribution Form Filled, Partner Support Level, External PR, Partner-Approved

#38157 Fix protectwise uploaded file README image
  Packs/ProtectWise/Integrations/ProtectWise/README.md
Labels: docs-approved

#38155 Fix Microsoft Defender incoming mapper / XSUP-45575
  Packs/Microsoft365Defender/Classifiers/classifier-Microsoft_365_Defender_-_Incoming_Mapper.json
  Packs/Microsoft365Defender/ReleaseNotes/4_5_40.json
  Packs/Microsoft365Defender/ReleaseNotes/4_5_40.md
  Packs/Microsoft365Defender/pack_metadata.json
Labels: docs-approved

#38087 Fix CS Falcon outgoing mapper
  Packs/CrowdStrikeFalcon/Classifiers/classifier-mapper-outgoing-CrowdStrike_Falcon.json
  Packs/CrowdStrikeFalcon/Integrations/CrowdStrikeFalcon/CrowdStrikeFalcon.py
  Packs/CrowdStrikeFalcon/Integrations/CrowdStrikeFalcon/CrowdStrikeFalcon_test.py
  Packs/CrowdStrikeFalcon/ReleaseNotes/2_1_7.md
  Packs/CrowdStrikeFalcon/pack_metadata.json
Labels: docs-approved

#38069 Fix Pylint errors in P packs
  Packs/PAN-OS/Integrations/Panorama/Panorama.py
  Packs/PAN-OS/ReleaseNotes/2_3_3.md
  Packs/PAN-OS/pack_metadata.json
  Packs/PaloAltoNetworks_SecurityAdvisories/ReleaseNotes/1_0_9.md
  Packs/PaloAltoNetworks_SecurityAdvisories/Scripts/CheckPanosVersionAffected/CheckPanosVersionAffected.py
  Packs/PaloAltoNetworks_SecurityAdvisories/Scripts/CheckPanosVersionAffected/CheckPanosVersionAffected.yml
  Packs/PaloAltoNetworks_SecurityAdvisories/pack_metadata.json
  Packs/PaloAltoNetworks_Threat_Vault/Integrations/ThreatVaultv2/ThreatVaultv2.py
  Packs/PaloAltoNetworks_Threat_Vault/Integrations/ThreatVaultv2/ThreatVaultv2.yml
  Packs/PaloAltoNetworks_Threat_Vault/ReleaseNotes/2_0_17.md
  Packs/PaloAltoNetworks_Threat_Vault/pack_metadata.json
  Packs/Palo_Alto_Networks_Enterprise_DLP/ReleaseNotes/2_0_15.md
  Packs/Palo_Alto_Networks_Enterprise_DLP/Scripts/DlpAskFeedback/DlpAskFeedback.py
  Packs/Palo_Alto_Networks_Enterprise_DLP/Scripts/DlpAskFeedback/DlpAskFeedback.yml
  Packs/Palo_Alto_Networks_Enterprise_DLP/pack_metadata.json
  Packs/PicusAutomation/Integrations/Picus/Picus.py
  Packs/PicusAutomation/Integrations/Picus/Picus.yml
  Packs/PicusAutomation/ReleaseNotes/1_1_4.md
  Packs/PicusAutomation/pack_metadata.json
  Packs/PolySwarm/Integrations/PolySwarmV2/PolySwarmV2.py
  Packs/PolySwarm/Integrations/PolySwarmV2/PolySwarmV2.yml
  Packs/PolySwarm/ReleaseNotes/2_0_7.md
  Packs/PolySwarm/pack_metadata.json
  Packs/PrismaAccess/Integrations/PrismaAccess/PrismaAccess.py
  Packs/PrismaAccess/Integrations/PrismaAccess/PrismaAccess.yml
  Packs/PrismaAccess/ReleaseNotes/2_1_13.md
  Packs/PrismaAccess/pack_metadata.json
  Packs/PrismaCloudCompute/Integrations/PaloAltoNetworks_PrismaCloudCompute/PaloAltoNetworks_PrismaCloudCompute.py
  Packs/PrismaCloudCompute/Integrations/PaloAltoNetworks_PrismaCloudCompute/PaloAltoNetworks_PrismaCloudCompute.yml
  Packs/PrismaCloudCompute/ReleaseNotes/1_7_11.md
  Packs/PrismaCloudCompute/pack_metadata.json
  Packs/ProofpointThreatResponse/Integrations/ProofpointThreatResponse/ProofpointThreatResponse.py
  Packs/ProofpointThreatResponse/Integrations/ProofpointThreatResponse/ProofpointThreatResponse.yml
  Packs/ProofpointThreatResponse/ReleaseNotes/2_0_21.md
  Packs/ProofpointThreatResponse/pack_metadata.json
  Tests/conf.json
Labels: docs-approved, ForceMerge

#38162 10611 finshes part 3_4
  Packs/OpenCVE/README.md
  Packs/PhishUp/Playbooks/PhishUp_Mail_Scanner_README.md
  Packs/RiskIQDigitalFootprint/README.md
Labels: docs-approved, bypass.url

#38160 10611 finshes part 3_2
  Packs/Office365/README.md
Labels: docs-approved, bypass.url

#38143 Update ruff config
  .pre-commit-config_template.yaml
  nightly_ruff.toml
  pyproject.toml
Labels: docs-approved

#38169 revert docker
  Packs/Campaign/ReleaseNotes/3_4_17.md
  Packs/Campaign/Scripts/FindEmailCampaign/FindEmailCampaign.yml
  Packs/Campaign/pack_metadata.json
  Packs/Phishing/ReleaseNotes/3_6_32.md
  Packs/Phishing/Scripts/FindDuplicateEmailIncidents/FindDuplicateEmailIncidents.yml
  Packs/Phishing/pack_metadata.json
Labels: docs-approved, ForceMerge

#38135 GetFailedTasks script to handle playbook type.
  Packs/IntegrationsAndIncidentsHealthCheck/ReleaseNotes/1_3_28.md
  Packs/IntegrationsAndIncidentsHealthCheck/Scripts/GetFailedTasks/GetFailedTasks.py
  Packs/IntegrationsAndIncidentsHealthCheck/Scripts/GetFailedTasks/GetFailedTasks_test.py
  Packs/IntegrationsAndIncidentsHealthCheck/pack_metadata.json
Labels: docs-approved

#38186 Fix a ruff error
  Packs/CofenseTriage/Integrations/CofenseTriagev2/CofenseTriagev2_test.py
  Packs/IntegrationsAndIncidentsHealthCheck/ReleaseNotes/1_3_29.md
  Packs/IntegrationsAndIncidentsHealthCheck/Scripts/GetFailedTasks/GetFailedTasks.py
  Packs/IntegrationsAndIncidentsHealthCheck/pack_metadata.json
Labels: docs-approved

#38184 Increased the memory threshold for CrowdStrike_FalconX TPB
  Tests/conf.json
Labels: docs-approved

#38132 Update EWSO365 to 3.12
  Packs/MicrosoftExchangeOnline/Integrations/EWSO365/EWSO365.yml
  Packs/MicrosoftExchangeOnline/ReleaseNotes/1_5_26.md
  Packs/MicrosoftExchangeOnline/pack_metadata.json
Labels: ForceMerge

#38118 Unusual process accessed web browser credentials
  Packs/CortexResponseAndRemediation/Playbooks/playbook-Unusual_process_accessed_web_browser_credentials_and_executed_by_a_terminal_process.yml
  Packs/CortexResponseAndRemediation/Playbooks/playbook-Unusual_process_accessed_web_browser_credentials_and_executed_by_a_terminal_process_README.md
  Packs/CortexResponseAndRemediation/ReleaseNotes/1_0_7.md
  Packs/CortexResponseAndRemediation/Triggers/Trigger_-_Unusual_process_accessed_web_browser_credentials_and_executed_by_a_terminal_process.json
  Packs/CortexResponseAndRemediation/doc_files/Unusual_process_accessed_web_browser_credentials_and_executed_by_a_terminal_process.png
  Packs/CortexResponseAndRemediation/pack_metadata.json
Labels: docs-approved

#38100 Improve Microsoft Oproxy Apps docs
  Packs/AzureLogAnalytics/Integrations/AzureLogAnalytics/AzureLogAnalytics_description.md
  Packs/AzureLogAnalytics/Integrations/AzureLogAnalytics/README.md
  Packs/AzureLogAnalytics/ReleaseNotes/1_1_43.md
  Packs/AzureLogAnalytics/pack_metadata.json
  Packs/MicrosoftGraphMail/Integrations/MicrosoftGraphListener/MicrosoftGraphListener_description.md
  Packs/MicrosoftGraphMail/Integrations/MicrosoftGraphListener/README.md
  Packs/MicrosoftGraphMail/ReleaseNotes/1_6_23.md
  Packs/MicrosoftGraphMail/pack_metadata.json
  Packs/MicrosoftManagementActivity/Integrations/MicrosoftManagementActivity/MicrosoftManagementActivity_description.md
  Packs/MicrosoftManagementActivity/Integrations/MicrosoftManagementActivity/README.md
  Packs/MicrosoftManagementActivity/ReleaseNotes/1_3_52.md
  Packs/MicrosoftManagementActivity/pack_metadata.json
Labels: docs-approved

#38191 Fix for sso password
  Packs/CortexResponseAndRemediation/Playbooks/playbook-SSO_Password_Spray.yml
  Packs/CortexResponseAndRemediation/Playbooks/playbook-SSO_Password_Spray_README.md
  Packs/CortexResponseAndRemediation/ReleaseNotes/1_0_8.md
  Packs/CortexResponseAndRemediation/pack_metadata.json
Labels: docs-approved

#37761 Turn akamai into long running
  Packs/Akamai_SIEM/Integrations/Akamai_SIEM/Akamai_SIEM.py
  Packs/Akamai_SIEM/Integrations/Akamai_SIEM/Akamai_SIEM.yml
  Packs/Akamai_SIEM/Integrations/Akamai_SIEM/Akamai_SIEM_test.py
  Packs/Akamai_SIEM/Integrations/Akamai_SIEM/README.md
  Packs/Akamai_SIEM/ParsingRules/Akamai_WAF_ParsingRules/Akamai_WAF_ParsingRules.xif
  Packs/Akamai_SIEM/ParsingRules/Akamai_WAF_ParsingRules/Akamai_WAF_ParsingRules.yml
  Packs/Akamai_SIEM/ReleaseNotes/1_2_0.md
  Packs/Akamai_SIEM/pack_metadata.json
Labels: docs-approved

#38115 Remove the disable of PyLint E0601 and E0606
  .pre-commit-config_template.yaml
  Packs/CommunityCommonScripts/ReleaseNotes/1_3_12.md
  Packs/CommunityCommonScripts/Scripts/DeleteIndicators/DeleteIndicators.py
  Packs/CommunityCommonScripts/pack_metadata.json
  Packs/Synapse/Integrations/Synapse/Synapse.py
  Packs/Synapse/ReleaseNotes/1_0_10.md
  Packs/Synapse/pack_metadata.json
Labels: docs-approved

#38200 Axonius image update
  Packs/Axonius/Integrations/Axonius/Axonius.yml
  Packs/Axonius/ReleaseNotes/1_2_6.md
  Packs/Axonius/pack_metadata.json
Labels: docs-approved

#37610 [EWS V2] Update docker
  Packs/MicrosoftExchangeOnPremise/Integrations/EWSv2/EWSv2.yml
  Packs/MicrosoftExchangeOnPremise/ReleaseNotes/2_1_23.md
  Packs/MicrosoftExchangeOnPremise/pack_metadata.json
Labels: docs-approved, ForceMerge

#38149 External Login Password Spray - continue on error for missing ITDR licenses
  Packs/CortexResponseAndRemediation/Playbooks/playbook-External_Login_Password_Spray.yml
  Packs/CortexResponseAndRemediation/ReleaseNotes/1_0_9.md
  Packs/CortexResponseAndRemediation/pack_metadata.json
Labels: docs-approved, release-notes-only

#38178 CS Falcon - Improved docs related to the Fetch Types parameter
  Packs/CrowdStrikeFalcon/Integrations/CrowdStrikeFalcon/CrowdStrikeFalcon.yml
  Packs/CrowdStrikeFalcon/Integrations/CrowdStrikeFalcon/CrowdStrikeFalcon_description.md
  Packs/CrowdStrikeFalcon/Integrations/CrowdStrikeFalcon/README.md
  Packs/CrowdStrikeFalcon/ReleaseNotes/2_1_8.md
  Packs/CrowdStrikeFalcon/pack_metadata.json
Labels: docs-approved, ForceMerge

#38216 Fix akamai time var
  Packs/Akamai_SIEM/Integrations/Akamai_SIEM/Akamai_SIEM.py
  Packs/Akamai_SIEM/Integrations/Akamai_SIEM/Akamai_SIEM_test.py
  Packs/Akamai_SIEM/ReleaseNotes/1_2_0.md
  Packs/Akamai_SIEM/ReleaseNotes/1_2_1.md
  Packs/Akamai_SIEM/pack_metadata.json
Labels: docs-approved

#38208 Add limitation to 1 log entry in send_events_to_xsioam
  Packs/Base/ReleaseNotes/1_39_17.md
  Packs/Base/Scripts/CommonServerPython/CommonServerPython.py
  Packs/Base/pack_metadata.json
Labels: docs-approved

#38177 Show QDS value and QDS contributing factors in Qualys VMDR
  Packs/qualys/Integrations/Qualysv2/Qualysv2.py
  Packs/qualys/Integrations/Qualysv2/Qualysv2.yml
  Packs/qualys/Integrations/Qualysv2/Qualysv2_test.py
  Packs/qualys/Integrations/Qualysv2/README.md
  Packs/qualys/ReleaseNotes/3_1_5.md
  Packs/qualys/pack_metadata.json
Labels: enhancement, docs-approved, python

#38237 Reduce_testpb_timeout
  Tests/conf.json
Labels: docs-approved

#38195 AppleScript executed with a rare command line
  Packs/CortexResponseAndRemediation/Playbooks/playbook-AppleScript_Process_Executed_With_Rare_Command_Line.yml
  Packs/CortexResponseAndRemediation/Playbooks/playbook-AppleScript_Process_Executed_With_Rare_Command_Line_README.md
  Packs/CortexResponseAndRemediation/ReleaseNotes/1_0_10.md
  Packs/CortexResponseAndRemediation/Triggers/Trigger_-_AppleScript_Process_Executed_With_Rare_Command_Line.json
  Packs/CortexResponseAndRemediation/doc_files/AppleScript_Process_Executed_With_Rare_Command_Line.png
  Packs/CortexResponseAndRemediation/pack_metadata.json
Labels: docs-approved

#38218 [EmailAskUserResponse] Add Prefix arg
  Packs/CommonScripts/ReleaseNotes/1_19_11.md
  Packs/CommonScripts/Scripts/EmailAskUserResponse/EmailAskUserResponse.js
  Packs/CommonScripts/Scripts/EmailAskUserResponse/EmailAskUserResponse.yml
  Packs/CommonScripts/Scripts/EmailAskUserResponse/README.md
  Packs/CommonScripts/pack_metadata.json
Labels: docs-approved

#37864 [Pre Commit] MyPy In Docker
  .pre-commit-config_template.yaml
Labels: docs-approved

#38236 added interval param
  Packs/DemistoLocking/Integrations/DemistoLock/DemistoLock.js
  Packs/DemistoLocking/Integrations/DemistoLock/DemistoLock.yml
  Packs/DemistoLocking/Integrations/DemistoLock/README.md
  Packs/DemistoLocking/ReleaseNotes/1_1_5.md
  Packs/DemistoLocking/pack_metadata.json
Labels: docs-approved

#38245 Revert "remove the lazy guy from the team"
  .github/content_roles.json
Labels: docs-approved
