Repository demisto/content, pull requests merged in 2025-06, with the labels that each got.

#39535 XSUP-42246/fix-google-vault
  Packs/GoogleVault/Integrations/GoogleVault/GoogleVault.py
  Packs/GoogleVault/Integrations/GoogleVault/GoogleVault.yml
  Packs/GoogleVault/Integrations/GoogleVault/README.md
  Packs/GoogleVault/ReleaseNotes/1_0_18.md
  Packs/GoogleVault/pack_metadata.json
Labels: docs-approved, ready-for-pipeline-running

#40057 Jsontotable clickable links
  Packs/FiltersAndTransformers/CONTRIBUTORS.json
  Packs/FiltersAndTransformers/ReleaseNotes/1_2_96.md
  Packs/FiltersAndTransformers/Scripts/JsonToTable/JsonToTable.py
  Packs/FiltersAndTransformers/Scripts/JsonToTable/JsonToTable.yml
  Packs/FiltersAndTransformers/pack_metadata.json
Labels: Contribution, docs-approved, post-demo, Contribution Form Filled, Community, Xsoar Support Level, External PR

#40160 Adminconsentfix
  Packs/CortexResponseAndRemediation/Playbooks/silent-playbook-First_seen_Azure_admin_consent_to_an_application.yml
  Packs/CortexResponseAndRemediation/ReleaseNotes/1_1_57.md
  Packs/CortexResponseAndRemediation/pack_metadata.json
Labels: docs-approved, ready-for-pipeline-running

#40169 XSUP 51539 Microsoft Windows Update
  Packs/MicrosoftWindowsEvents/ModelingRules/MicrosoftWindowsEvents_1_3/MicrosoftWindowsEvents_1_3.xif
  Packs/MicrosoftWindowsEvents/ReleaseNotes/1_1_17.md
  Packs/MicrosoftWindowsEvents/pack_metadata.json
Labels: docs-approved, bypass.url, ready-for-pipeline-running

#40178 Fix xsoar only supporting scripts
  Packs/Base/ReleaseNotes/1_39_34.md
  Packs/Base/Scripts/DBotFindSimilarIncidents/DBotFindSimilarIncidents.py
  Packs/Base/Scripts/DBotFindSimilarIncidents/DBotFindSimilarIncidents.yml
  Packs/Base/Scripts/DBotFindSimilarIncidents/DBotFindSimilarIncidents_test.py
  Packs/Base/pack_metadata.json
  Packs/DemistoRESTAPI/ReleaseNotes/1_3_74.md
  Packs/DemistoRESTAPI/Scripts/UploadFile/UploadFile.py
  Packs/DemistoRESTAPI/Scripts/UploadFile/UploadFile_test.py
  Packs/DemistoRESTAPI/pack_metadata.json
Labels: docs-approved, ready-for-pipeline-running

#40145 CyCognito Release 1.0.29
  Packs/CyCognito/.pack-ignore
  Packs/CyCognito/.secrets-ignore
  Packs/CyCognito/Integrations/CyCognito/CyCognito.py
  Packs/CyCognito/Integrations/CyCognito/CyCognito.yml
  Packs/CyCognito/Integrations/CyCognito/CyCognito_test.py
  Packs/CyCognito/Integrations/CyCognito/README.md
  Packs/CyCognito/Integrations/CyCognito/test_data/get_issue_success_hr.md
  Packs/CyCognito/Integrations/CyCognito/test_data/list_assets_empty_request_body_hr.md
  Packs/CyCognito/Integrations/CyCognito/test_data/list_assets_hr.md
  Packs/CyCognito/ReleaseNotes/1_0_30.md
  Packs/CyCognito/pack_metadata.json
Labels: Contribution, docs-approved, Partner, Contribution Form Filled, Partner Support Level, External PR, Partner-Approved

#40147 CyCognito Feed Release 1.0.28
  Packs/FeedCyCognito/.pack-ignore
  Packs/FeedCyCognito/.secrets-ignore
  Packs/FeedCyCognito/Integrations/FeedCyCognito/FeedCyCognito.py
  Packs/FeedCyCognito/Integrations/FeedCyCognito/FeedCyCognito.yml
  Packs/FeedCyCognito/Integrations/FeedCyCognito/FeedCyCognito_test.py
  Packs/FeedCyCognito/Integrations/FeedCyCognito/README.md
  Packs/FeedCyCognito/Integrations/FeedCyCognito/test_data/get_indicators_success_hr_cert.md
  Packs/FeedCyCognito/Integrations/FeedCyCognito/test_data/get_indicators_success_hr_domain.md
  Packs/FeedCyCognito/Integrations/FeedCyCognito/test_data/get_indicators_success_hr_ip.md
  Packs/FeedCyCognito/Integrations/FeedCyCognito/test_data/get_indicators_success_hr_iprange.md
  Packs/FeedCyCognito/ReleaseNotes/1_0_28.md
  Packs/FeedCyCognito/pack_metadata.json
Labels: Contribution, docs-approved, Partner, Contribution Form Filled, Partner Support Level, External PR, Partner-Approved, TIM Review

#40193 [XSUP-50324] Add audit-comment option to pan-os-edit-rule documentation
  Packs/PAN-OS/Integrations/Panorama/README.md
Labels: docs-approved, ready-for-pipeline-running

#40089 Add custom styling and table attributes option
  Packs/CommunityCommonScripts/ReleaseNotes/1_3_18.md
  Packs/CommunityCommonScripts/Scripts/Json2HtmlTable/Json2HtmlTable.py
  Packs/CommunityCommonScripts/Scripts/Json2HtmlTable/Json2HtmlTable.yml
  Packs/CommunityCommonScripts/Scripts/Json2HtmlTable/Json2HtmlTable_test.py
  Packs/CommunityCommonScripts/pack_metadata.json
Labels: Contribution, docs-approved, Contribution Form Filled, Community, Community Support Level, External PR

#40148 Securonix Release 2.0.25
  Packs/Securonix/Integrations/Securonix/README.md
  Packs/Securonix/Integrations/Securonix/Securonix.py
  Packs/Securonix/Integrations/Securonix/Securonix.yml
  Packs/Securonix/Integrations/Securonix/Securonix_test.py
  Packs/Securonix/ReleaseNotes/2_0_25.md
  Packs/Securonix/pack_metadata.json
Labels: Contribution, docs-approved, Partner, Contribution Form Filled, Partner Support Level, External PR, Partner-Approved

#40186 SanePdfReports: update docker tag
  Packs/Base/ReleaseNotes/1_39_35.md
  Packs/Base/Scripts/SanePdfReport/SanePdfReport.yml
  Packs/Base/pack_metadata.json
Labels: docs-approved, ready-for-pipeline-running

#40163 Rundll32.exe executes a rare unsigned module playbook - Silent
  Packs/CortexResponseAndRemediation/Playbooks/silent-playbook-Rundll32.exe_executes_a_rare_unsigned_module.yml
  Packs/CortexResponseAndRemediation/ReleaseNotes/1_1_58.md
  Packs/CortexResponseAndRemediation/Triggers/silent-Trigger_-_Rundll32.exe_executes_a_rare_unsigned_module.json
  Packs/CortexResponseAndRemediation/pack_metadata.json
Labels: docs-approved, ready-for-pipeline-running

#40202 Fix typo in templates readme
  Templates/README.md
Labels: docs-approved, ready-for-pipeline-running

#40135 XSUP-51336/AzureFeed
  Packs/FeedAzure/Integrations/FeedAzure/FeedAzure.py
  Packs/FeedAzure/Integrations/FeedAzure/FeedAzure.yml
  Packs/FeedAzure/Integrations/FeedAzure/FeedAzure_test.py
  Packs/FeedAzure/Integrations/FeedAzure/test_data/response_mock_test_regex.txt
  Packs/FeedAzure/ReleaseNotes/1_0_35.md
  Packs/FeedAzure/pack_metadata.json
Labels: docs-approved, ready-for-pipeline-running

#40092 sendemailreply handling error
  Packs/EmailCommunication/ReleaseNotes/2_0_40.md
  Packs/EmailCommunication/Scripts/SendEmailReply/SendEmailReply.py
  Packs/EmailCommunication/Scripts/SendEmailReply/SendEmailReply.yml
  Packs/EmailCommunication/Scripts/SendEmailReply/SendEmailReply_test.py
  Packs/EmailCommunication/pack_metadata.json
Labels: docs-approved, ready-for-pipeline-running

#40213 Rewrite Proofpoint Threat Protection unit tests
  Packs/ProofpointThreatProtection/Integrations/ProofpointThreatProtection/ProofpointThreatProtection.yml
  Packs/ProofpointThreatProtection/Integrations/ProofpointThreatProtection/ProofpointThreatProtection_test.py
  Packs/ProofpointThreatProtection/ReleaseNotes/1_0_3.md
  Packs/ProofpointThreatProtection/pack_metadata.json
Labels: docs-approved, ready-for-pipeline-running

#39971 PanOS get system info dataclass update
  Packs/PAN-OS/Integrations/Panorama/Panorama.py
  Packs/PAN-OS/Integrations/Panorama/Panorama.yml
  Packs/PAN-OS/Integrations/Panorama/README.md
  Packs/PAN-OS/Integrations/Panorama/test_data/show_system_info.xml
  Packs/PAN-OS/ReleaseNotes/2_3_15.md
  Packs/PAN-OS/pack_metadata.json
Labels: Contribution, docs-approved, pending-demo, Contribution Form Filled, Community, Xsoar Support Level, External PR

#38644 Renew Phishing Classifier
  Packs/Base/ReleaseNotes/1_39_36.json
  Packs/Base/ReleaseNotes/1_39_36.md
  Packs/Base/Scripts/DBotFindSimilarIncidents/DBotFindSimilarIncidents.yml
  Packs/Base/Scripts/DBotFindSimilarIncidentsByIndicators/DBotFindSimilarIncidentsByIndicators.yml
  Packs/Base/Scripts/DBotPredictPhishingWords/DBotPredictPhishingWords.py
  Packs/Base/Scripts/DBotPredictPhishingWords/DBotPredictPhishingWords.yml
  Packs/Base/Scripts/DBotPreprocessTextData/DBotPreprocessTextData.yml
  Packs/Base/Scripts/DBotPreprocessTextData/TestData/input_pickle_file_test
  Packs/Base/Scripts/DBotPreprocessTextData/TestData/test.csv
  Packs/Base/Scripts/DBotTrainTextClassifierV2/DBotTrainTextClassifierV2.py
  Packs/Base/Scripts/DBotTrainTextClassifierV2/DBotTrainTextClassifierV2.yml
  Packs/Base/Scripts/GetMLModelEvaluation/GetMLModelEvaluation.yml
  Packs/Base/pack_metadata.json
  Packs/ML/ReleaseNotes/1_4_21.json
  Packs/ML/ReleaseNotes/1_4_21.md
  Packs/ML/Scripts/DBotPredictIncidentsBatch/DBotPredictIncidentsBatch.py
  Packs/ML/Scripts/DBotPredictIncidentsBatch/DBotPredictIncidentsBatch.yml
  Packs/ML/Scripts/DBotPredictOutOfTheBoxV2/DBotPredictOutOfTheBoxV2.py
  Packs/ML/Scripts/DBotPredictOutOfTheBoxV2/DBotPredictOutOfTheBoxV2.yml
  Packs/ML/TestPlaybooks/playbook-Create_Phishing_Classifier_V2_ML_Test.yml
  Packs/ML/TestPlaybooks/playbook-DBotPredictOutOfTheBoxV2-test.yml
  Packs/ML/pack_metadata.json
  Tests/conf.json
Labels: docs-approved, ready-for-pipeline-running

#40211 Bugfix/Fix-kpi-breaches-v1.1.45-prod
  Packs/Core/Playbooks/playbook-Netcat_Makes_or_Gets_Connections.yml
  Packs/Core/ReleaseNotes/3_3_5.md
  Packs/Core/pack_metadata.json
Labels: docs-approved, ready-for-pipeline-running

#40158 Update README.md
  Packs/CiscoCatalyst/README.md
Labels: docs-approved, ready-for-pipeline-running

#40222 Script_file_added_to_startup-related_Registry_keys-fix-kpi-breaches
  Packs/CortexResponseAndRemediation/Playbooks/silent-playbook-Script_file_added_to_startup-related_Registry_keys.yml
  Packs/CortexResponseAndRemediation/ReleaseNotes/1_1_59.md
  Packs/CortexResponseAndRemediation/pack_metadata.json
Labels: docs-approved, ready-for-pipeline-running

#40050 Split core get asset details
  Packs/Core/Integrations/CortexCoreIR/CortexCoreIR.yml
  Packs/Core/Integrations/CortexPlatformCore/CortexPlatformCore.py
  Packs/Core/Integrations/CortexPlatformCore/CortexPlatformCore.yml
  Packs/Core/Integrations/CortexPlatformCore/CortexPlatformCore_description.md
  Packs/Core/Integrations/CortexPlatformCore/CortexPlatformCore_image.png
  Packs/Core/Integrations/CortexPlatformCore/CortexPlatformCore_test.py
  Packs/Core/Integrations/CortexPlatformCore/README.md
  Packs/Core/Integrations/CortexPlatformCore/command_examples.txt
  Packs/Core/ReleaseNotes/3_4_0.md
  Packs/Core/pack_metadata.json
Labels: docs-approved, bypass.url, ready-for-pipeline-running

#40137 CRTX 158623 Azure Flowlogs
  Packs/AzureFlowLogs/.pack-ignore
  Packs/AzureFlowLogs/.secrets-ignore
  Packs/AzureFlowLogs/ModelingRules/AzureFlowLogs/AzureFlowLogs.xif
  Packs/AzureFlowLogs/ModelingRules/AzureFlowLogs/AzureFlowLogs.yml
  Packs/AzureFlowLogs/ModelingRules/AzureFlowLogs/AzureFlowLogs_schema.json
  Packs/AzureFlowLogs/ParsingRules/AzureFlowLogs.xif
  Packs/AzureFlowLogs/ParsingRules/AzureFlowLogs.yml
  Packs/AzureFlowLogs/README.md
  Packs/AzureFlowLogs/pack_metadata.json
  Packs/MicrosoftEntraID/ParsingRules/MicrosoftEntraID/MicrosoftEntraID.xif
  Packs/MicrosoftEntraID/README.md
  Packs/MicrosoftEntraID/pack_metadata.json
Labels: docs-approved, bypass.url, ready-for-pipeline-running

#40194 Bugfix/XSUP-51673/missing-input-extract-indicators-generic-from-pdf-files
  Packs/CommonPlaybooks/Playbooks/playbook-Extract_Indicators_From_File_-_Generic_v2_4_5.yml
  Packs/CommonPlaybooks/ReleaseNotes/2_7_3.md
  Packs/CommonPlaybooks/pack_metadata.json
Labels: docs-approved, ready-for-pipeline-running

#40232 XSUP-51986 - Cisco Meraki regex update
  Packs/cisco-meraki/ModelingRules/CiscoMerakiModelingRules_1_3/CiscoMerakiModelingRules_1_3.xif
  Packs/cisco-meraki/ReleaseNotes/2_0_3.md
  Packs/cisco-meraki/pack_metadata.json
Labels: docs-approved, bypass.url, ready-for-pipeline-running

#39984 Addd new simple TPB
  Packs/CrowdStrikeFalcon/Integrations/CrowdStrikeFalcon/CrowdStrikeFalcon.yml
  Packs/CrowdStrikeFalcon/ReleaseNotes/2_1_27.md
  Packs/CrowdStrikeFalcon/TestPlaybooks/CrowdStrike Falcon Basic Test.yml
  Packs/CrowdStrikeFalcon/pack_metadata.json
  Packs/PrismaCloud/Integrations/PrismaCloudV2/PrismaCloudV2.yml
  Packs/PrismaCloud/ReleaseNotes/4_4_5.md
  Packs/PrismaCloud/TestPlaybooks/Prisma_Cloud_V2_Basic_Test.yml
  Packs/PrismaCloud/pack_metadata.json
  Tests/conf.json
Labels: docs-approved, ready-for-pipeline-running

#40156 MalwareBazaar add API key
  Packs/FeedMalwareBazaar/.secrets-ignore
  Packs/FeedMalwareBazaar/Integrations/MalwareBazaarFeed/MalwareBazaarFeed.py
  Packs/FeedMalwareBazaar/Integrations/MalwareBazaarFeed/MalwareBazaarFeed.yml
  Packs/FeedMalwareBazaar/Integrations/MalwareBazaarFeed/MalwareBazaarFeed_test.py
  Packs/FeedMalwareBazaar/Integrations/MalwareBazaarFeed/README.md
  Packs/FeedMalwareBazaar/ReleaseNotes/1_0_47.json
  Packs/FeedMalwareBazaar/ReleaseNotes/1_0_47.md
  Packs/FeedMalwareBazaar/pack_metadata.json
  Packs/MalwareBazaar/.secrets-ignore
  Packs/MalwareBazaar/Integrations/MalwareBazaar/MalwareBazaar.py
  Packs/MalwareBazaar/Integrations/MalwareBazaar/MalwareBazaar.yml
  Packs/MalwareBazaar/Integrations/MalwareBazaar/README.md
  Packs/MalwareBazaar/ReleaseNotes/1_0_19.json
  Packs/MalwareBazaar/ReleaseNotes/1_0_19.md
  Packs/MalwareBazaar/pack_metadata.json
Labels: docs-approved, sync-gsm, ready-for-pipeline-running

#40234 Test - CrowdStrike Falcon increase timeout
  Tests/conf.json
Labels: docs-approved, ready-for-pipeline-running

#40243 fix modules
  Packs/Core/Integrations/CortexCoreIR/CortexCoreIR.yml
  Packs/Core/Integrations/CortexPlatformCore/CortexPlatformCore.yml
  Packs/Core/ReleaseNotes/3_4_1.md
  Packs/Core/pack_metadata.json
Labels: docs-approved, ready-for-pipeline-running

#40225 XSUP-51950/GoogleBigQuery
  Packs/GoogleBigQuery/Integrations/GoogleBigQuery/GoogleBigQuery.yml
  Packs/GoogleBigQuery/ReleaseNotes/1_1_13.md
  Packs/GoogleBigQuery/pack_metadata.json
Labels: docs-approved, ready-for-pipeline-running

#40245 add support for unified platform version.
  Packs/CommonScripts/ReleaseNotes/1_19_68.md
  Packs/CommonScripts/Scripts/SearchIncidentsV2/SearchIncidentsV2.py
  Packs/CommonScripts/Scripts/SearchIncidentsV2/SearchIncidentsV2.yml
  Packs/CommonScripts/Scripts/SearchIncidentsV2/SearchIncidentsV2_test.py
  Packs/CommonScripts/pack_metadata.json
Labels: docs-approved, ready-for-pipeline-running

#40200 Enhancements for Panorama integration commands
  Packs/PAN-OS/Integrations/Panorama/Panorama.py
  Packs/PAN-OS/Integrations/Panorama/Panorama.yml
  Packs/PAN-OS/Integrations/Panorama/Panorama_test.py
  Packs/PAN-OS/Integrations/Panorama/README.md
  Packs/PAN-OS/ReleaseNotes/2_4_0.json
  Packs/PAN-OS/ReleaseNotes/2_4_0.md
  Packs/PAN-OS/pack_metadata.json
Labels: Contribution, docs-approved, Contribution Form Filled, Community, Xsoar Support Level, External PR

#40183 XSUP-50931: FindEmailCampaign improvements
  Packs/Campaign/ReleaseNotes/3_4_23.md
  Packs/Campaign/Scripts/FindEmailCampaign/FindEmailCampaign.py
  Packs/Campaign/Scripts/FindEmailCampaign/FindEmailCampaign.yml
  Packs/Campaign/Scripts/FindEmailCampaign/FindEmailCampaign_test.py
  Packs/Campaign/pack_metadata.json
Labels: docs-approved, ready-for-pipeline-running

#40257 New trigger
  Packs/CortexResponseAndRemediation/ReleaseNotes/1_1_63.md
  Packs/CortexResponseAndRemediation/Triggers/silent-Trigger_-_Suspicious_Hidden_User_Created.json
  Packs/CortexResponseAndRemediation/pack_metadata.json
Labels: docs-approved, bypass.url, ready-for-pipeline-running

#40259 XSUP 51891 symantec_bluecoatproxysg mapping update
  Packs/SymantecBlueCoatProxySG/ModelingRules/SymantecBlueCoatProxySG/SymantecBlueCoatProxySG.xif
  Packs/SymantecBlueCoatProxySG/ReleaseNotes/1_0_6.md
  Packs/SymantecBlueCoatProxySG/pack_metadata.json
Labels: docs-approved, bypass.url, ready-for-pipeline-running

#40265 CRTX-178569
  Packs/Microsoft365Defender/Integrations/Microsoft365Defender/Microsoft365Defender.py
  Packs/Microsoft365Defender/Integrations/Microsoft365Defender/Microsoft365Defender.yml
  Packs/Microsoft365Defender/ReleaseNotes/4_6_5.md
  Packs/Microsoft365Defender/pack_metadata.json
Labels: docs-approved, ready-for-pipeline-running

#39773 Optimize Nightly Test-Playbook CIAC-12857
  Tests/conf.json
Labels: docs-approved, ready-for-pipeline-running

#40273 [Preference Center/Automation Exclusions] Add `Quarantine File` policy content support
  Config/compliant_policies.json
  Packs/Core/Integrations/CortexCoreIR/CortexCoreIR.yml
  Packs/Core/ReleaseNotes/3_4_3.md
  Packs/Core/pack_metadata.json
  Packs/MicrosoftDefenderAdvancedThreatProtection/Integrations/MicrosoftDefenderAdvancedThreatProtection/MicrosoftDefenderAdvancedThreatProtection.yml
  Packs/MicrosoftDefenderAdvancedThreatProtection/ReleaseNotes/1_18_9.md
  Packs/MicrosoftDefenderAdvancedThreatProtection/pack_metadata.json
Labels: docs-approved, ForceMerge, ready-for-pipeline-running

#40185 HyperActive - External Login Password Spray
  Packs/CortexResponseAndRemediation/Playbooks/silent-playbook-External_Login_Password_Spray_Test.yml
  Packs/CortexResponseAndRemediation/ReleaseNotes/1_1_64.md
  Packs/CortexResponseAndRemediation/Triggers/Trigger_-_External_Login_Password_Spray.json
  Packs/CortexResponseAndRemediation/Triggers/silent-Trigger_-_External_Login_Password_Spray_Test.json
  Packs/CortexResponseAndRemediation/pack_metadata.json
Labels: docs-approved, ready-for-pipeline-running

#40297 XSUP 52276 Fortigate fix
  Packs/FortiGate/ModelingRules/FortiGate_1_3/FortiGate_1_3.xif
  Packs/FortiGate/ReleaseNotes/2_0_11.md
  Packs/FortiGate/pack_metadata.json
Labels: docs-approved, bypass.url, ready-for-pipeline-running

#40296 Changed the user-code to Authorization code in the Azure WAF
  Packs/AzureWAF/Integrations/AzureWAF/AzureWAF.py
  Packs/AzureWAF/Integrations/AzureWAF/AzureWAF.yml
  Packs/AzureWAF/Integrations/AzureWAF/AzureWAF_description.md
  Packs/AzureWAF/Integrations/AzureWAF/AzureWAF_test.py
  Packs/AzureWAF/Integrations/AzureWAF/README.md
  Packs/AzureWAF/ReleaseNotes/1_2_15.md
  Packs/AzureWAF/pack_metadata.json
Labels: docs-approved, ready-for-pipeline-running

#40281 skipped DbotPredictOufOfTheBoxTest and testing v2 of the same tpb
  Tests/conf.json
Labels: docs-approved, ready-for-pipeline-running

#40240 [CortexXpanse] - Feed: Select Indicator Types
  Packs/CortexXpanse/Integrations/FeedXpanse/FeedXpanse.py
  Packs/CortexXpanse/Integrations/FeedXpanse/FeedXpanse.yml
  Packs/CortexXpanse/Integrations/FeedXpanse/README.md
  Packs/CortexXpanse/ReleaseNotes/1_2_10.md
  Packs/CortexXpanse/pack_metadata.json
Labels: Contribution, docs-approved, Contribution Form Filled, Community, Xsoar Support Level, External PR

#40129 Reliaquest takedown integration
  Packs/DigitalShadows/.secrets-ignore
  Packs/DigitalShadows/Classifiers/classifier-Reliaquest_Takedown_Classifier.json
  Packs/DigitalShadows/Classifiers/classifier-Reliaquest_Takedown_Mapper.json
  Packs/DigitalShadows/IncidentFields/incidentfield-DS_Takedown_Attachments.json
  Packs/DigitalShadows/IncidentFields/incidentfield-DS_Takedown_Comments.json
  Packs/DigitalShadows/IncidentFields/incidentfield-DS_Takedown_Targets.json
  Packs/DigitalShadows/IncidentTypes/incidenttype-Reliaquest_Takedown_Incident.json
  Packs/DigitalShadows/Integrations/ReliaquestTakedown/README.md
  Packs/DigitalShadows/Integrations/ReliaquestTakedown/ReliaquestTakedown.py
  Packs/DigitalShadows/Integrations/ReliaquestTakedown/ReliaquestTakedown.yml
  Packs/DigitalShadows/Integrations/ReliaquestTakedown/ReliaquestTakedown_description.md
  Packs/DigitalShadows/Integrations/ReliaquestTakedown/ReliaquestTakedown_image.png
  Packs/DigitalShadows/Integrations/ReliaquestTakedown/ReliaquestTakedown_test.py
  Packs/DigitalShadows/Integrations/ReliaquestTakedown/test_data/file-sample.pdf
  Packs/DigitalShadows/Integrations/ReliaquestTakedown/test_data/get_events.json
  Packs/DigitalShadows/Integrations/ReliaquestTakedown/test_data/test.txt
  Packs/DigitalShadows/Layouts/layoutscontainer-Reliaquest_Takedown_Layout.json
  Packs/DigitalShadows/ReleaseNotes/3_0_0.md
  Packs/DigitalShadows/pack_metadata.json
Labels: Contribution, docs-approved, Partner, Contribution Form Filled, Partner Support Level, External PR, Security Review, Partner-Approved, Security Approved

#40303 Xsup 52319 add md support
  Packs/EmailCommunication/ReleaseNotes/2_0_41.md
  Packs/EmailCommunication/Scripts/SendEmailReply/SendEmailReply.py
  Packs/EmailCommunication/Scripts/SendEmailReply/SendEmailReply.yml
  Packs/EmailCommunication/Scripts/SendEmailReply/SendEmailReply_test.py
  Packs/EmailCommunication/pack_metadata.json
Labels: docs-approved, ready-for-pipeline-running

#40271 Revert "CIAC-12314: Add Array Support to Rasterize"
  Packs/rasterize/.secrets-ignore
  Packs/rasterize/Integrations/rasterize/README.md
  Packs/rasterize/Integrations/rasterize/rasterize.py
  Packs/rasterize/ReleaseNotes/2_1_7.json
  Packs/rasterize/ReleaseNotes/2_1_7.md
  Packs/rasterize/pack_metadata.json
Labels: docs-approved, ForceMerge, ready-for-pipeline-running

#40315 changes to the readme file
  Packs/Cisco-umbrella-cloud-security/README.md
Labels: docs-approved, bypass.url, ready-for-pipeline-running

#40278 [CIAC-8537] Fix credential's priority - new over deprecated
  Packs/AzureLogAnalytics/Integrations/AzureLogAnalytics/AzureLogAnalytics.py
  Packs/AzureLogAnalytics/Integrations/AzureLogAnalytics/AzureLogAnalytics.yml
  Packs/AzureLogAnalytics/ReleaseNotes/1_1_49.md
  Packs/AzureLogAnalytics/pack_metadata.json
  Packs/Cymulate/Integrations/Cymulate_v2/Cymulate_v2.py
  Packs/Cymulate/Integrations/Cymulate_v2/Cymulate_v2.yml
  Packs/Cymulate/ReleaseNotes/2_0_30.md
  Packs/Cymulate/pack_metadata.json
  Packs/GitHub/Integrations/GitHub/GitHub.py
  Packs/GitHub/Integrations/GitHub/GitHub.yml
  Packs/GitHub/ReleaseNotes/2_1_8.md
  Packs/GitHub/pack_metadata.json
  Packs/Lastline/Integrations/Lastline_v2/Lastline_v2.py
  Packs/Lastline/Integrations/Lastline_v2/Lastline_v2.yml
  Packs/Lastline/ReleaseNotes/1_0_22.md
  Packs/Lastline/pack_metadata.json
  Packs/Microsoft365Defender/Integrations/Microsoft365Defender/Microsoft365Defender.py
  Packs/Microsoft365Defender/ReleaseNotes/4_6_6.md
  Packs/Microsoft365Defender/pack_metadata.json
  Packs/MicrosoftGraphGroups/Integrations/MicrosoftGraphGroups/MicrosoftGraphGroups.py
  Packs/MicrosoftGraphGroups/Integrations/MicrosoftGraphGroups/MicrosoftGraphGroups.yml
  Packs/MicrosoftGraphGroups/ReleaseNotes/1_1_56.md
  Packs/MicrosoftGraphGroups/pack_metadata.json
  Packs/PrismaAccess/Integrations/PrismaAccessEgressIPFeed/PrismaAccessEgressIPFeed.py
  Packs/PrismaAccess/Integrations/PrismaAccessEgressIPFeed/PrismaAccessEgressIPFeed.yml
  Packs/PrismaAccess/ReleaseNotes/2_1_17.md
  Packs/PrismaAccess/pack_metadata.json
  Packs/SentinelOne/Integrations/SentinelOne-V2/SentinelOne-V2.py
  Packs/SentinelOne/Integrations/SentinelOne-V2/SentinelOne-V2.yml
  Packs/SentinelOne/ReleaseNotes/3_2_42.md
  Packs/SentinelOne/pack_metadata.json
  Packs/UrlScan/Integrations/UrlScan/UrlScan.py
  Packs/UrlScan/Integrations/UrlScan/UrlScan.yml
  Packs/UrlScan/ReleaseNotes/1_2_19.md
  Packs/UrlScan/pack_metadata.json
Labels: docs-approved, ForceMerge, ready-for-pipeline-running

#40329 External login password spray DT fix
  Packs/CortexResponseAndRemediation/Playbooks/silent-playbook-External_Login_Password_Spray_Test.yml
  Packs/CortexResponseAndRemediation/ReleaseNotes/1_1_66.md
  Packs/CortexResponseAndRemediation/pack_metadata.json
Labels: docs-approved, ready-for-pipeline-running

#40319 [VirusTotal] fix(file): One invalid hash
  Packs/VirusTotal/Integrations/VirusTotalV3/VirusTotalV3.py
  Packs/VirusTotal/Integrations/VirusTotalV3/VirusTotalV3.yml
  Packs/VirusTotal/ReleaseNotes/2_7_2.md
  Packs/VirusTotal/pack_metadata.json
Labels: Contribution, docs-approved, Partner, Contribution Form Filled, Partner Support Level, External PR, Partner-Approved

#40229 [Code42EventCollector] Fix alerts lag
  Packs/Code42/Integrations/Code42EventCollector/Code42EventCollector.py
  Packs/Code42/Integrations/Code42EventCollector/Code42EventCollector_test.py
  Packs/Code42/ReleaseNotes/6_0_9.md
  Packs/Code42/pack_metadata.json
Labels: docs-approved, ready-for-pipeline-running

#40332 update ms graph identity access permissions
  Packs/MicrosoftGraphIdentityandAccess/Integrations/MicrosoftGraphIdentityandAccess/MicrosoftGraphIdentityandAccess.py
  Packs/MicrosoftGraphIdentityandAccess/Integrations/MicrosoftGraphIdentityandAccess/README.md
  Packs/MicrosoftGraphIdentityandAccess/ReleaseNotes/1_3_2.md
  Packs/MicrosoftGraphIdentityandAccess/pack_metadata.json
Labels: docs-approved, sync-gsm, ready-for-pipeline-running

#39610 Fixes for mirror-in
  Packs/SplunkPy/Integrations/SplunkPy/SplunkPy.py
  Packs/SplunkPy/ReleaseNotes/3_2_16.md
  Packs/SplunkPy/pack_metadata.json
Labels: docs-approved, ready-for-pipeline-running

#40344 XSUP 52384 Azure App Service Fix
  Packs/AzureAppService/ModelingRules/AzureAppService/AzureAppService.xif
  Packs/AzureAppService/ReleaseNotes/1_0_3.md
  Packs/AzureAppService/pack_metadata.json
Labels: docs-approved, bypass.url, ready-for-pipeline-running

#40321 Format MSISAC Error Handling
  Packs/MS-ISAC/Integrations/MSISAC/MSISAC.py
  Packs/MS-ISAC/ReleaseNotes/1_0_6.md
  Packs/MS-ISAC/pack_metadata.json
Labels: Contribution, docs-approved, Contribution Form Filled, Community, Community Support Level, External PR

#40335 tableToMarkdown: json_transform_mapping on list integers
  Packs/Base/ReleaseNotes/1_39_40.md
  Packs/Base/Scripts/CommonServerPython/CommonServerPython.py
  Packs/Base/Scripts/CommonServerPython/CommonServerPython_test.py
  Packs/Base/pack_metadata.json
Labels: docs-approved, ready-for-pipeline-running

#38794 Command analysis update
  Packs/CommonScripts/ReleaseNotes/1_19_73.md
  Packs/CommonScripts/Scripts/CommandLineAnalysis/CommandLineAnalysis.py
  Packs/CommonScripts/Scripts/CommandLineAnalysis/CommandLineAnalysis.yml
  Packs/CommonScripts/Scripts/CommandLineAnalysis/CommandLineAnalysis_test.py
  Packs/CommonScripts/pack_metadata.json
Labels: docs-approved, ready-for-pipeline-running

#40336 Ciac 14073 add auth header abuse.ch
  Packs/FeedFeodoTracker/.secrets-ignore
  Packs/FeedFeodoTracker/Integrations/FeedFeodoTrackerIPBlocklist/FeedFeodoTrackerIPBlocklist.py
  Packs/FeedFeodoTracker/Integrations/FeedFeodoTrackerIPBlocklist/FeedFeodoTrackerIPBlocklist.yml
  Packs/FeedFeodoTracker/Integrations/FeedFeodoTrackerIPBlocklist/FeedFeodoTrackerIPBlocklist_description.md
  Packs/FeedFeodoTracker/Integrations/FeedFeodoTrackerIPBlocklist/README.md
  Packs/FeedFeodoTracker/ReleaseNotes/1_1_37.json
  Packs/FeedFeodoTracker/ReleaseNotes/1_1_37.md
  Packs/FeedFeodoTracker/pack_metadata.json
  Packs/FeedMalwareBazaar/Integrations/MalwareBazaarFeed/README.md
  Packs/FeedThreatFox/.secrets-ignore
  Packs/FeedThreatFox/Integrations/FeedThreatFox/FeedThreatFox.py
  Packs/FeedThreatFox/Integrations/FeedThreatFox/FeedThreatFox.yml
  Packs/FeedThreatFox/Integrations/FeedThreatFox/FeedThreatFox_description.md
  Packs/FeedThreatFox/Integrations/FeedThreatFox/README.md
  Packs/FeedThreatFox/ReleaseNotes/1_0_4.json
  Packs/FeedThreatFox/ReleaseNotes/1_0_4.md
  Packs/FeedThreatFox/pack_metadata.json
  Packs/FeedURLhaus/.secrets-ignore
  Packs/FeedURLhaus/Integrations/FeedURLhaus/FeedURLhaus.py
  Packs/FeedURLhaus/Integrations/FeedURLhaus/FeedURLhaus.yml
  Packs/FeedURLhaus/Integrations/FeedURLhaus/FeedURLhaus_description.md
  Packs/FeedURLhaus/Integrations/FeedURLhaus/README.md
  Packs/FeedURLhaus/ReleaseNotes/1_0_17.json
  Packs/FeedURLhaus/ReleaseNotes/1_0_17.md
  Packs/FeedURLhaus/pack_metadata.json
  Packs/Feedsslabusech/.secrets-ignore
  Packs/Feedsslabusech/Integrations/Feedsslabusech/Feedsslabusech.py
  Packs/Feedsslabusech/Integrations/Feedsslabusech/Feedsslabusech.yml
  Packs/Feedsslabusech/Integrations/Feedsslabusech/Feedsslabusech_description.md
  Packs/Feedsslabusech/Integrations/Feedsslabusech/README.md
  Packs/Feedsslabusech/ReleaseNotes/1_1_32.json
  Packs/Feedsslabusech/ReleaseNotes/1_1_32.md
  Packs/Feedsslabusech/pack_metadata.json
  Packs/URLHaus/.secrets-ignore
  Packs/URLHaus/Integrations/URLHaus/README.md
  Packs/URLHaus/Integrations/URLHaus/URLHaus.py
  Packs/URLHaus/Integrations/URLHaus/URLHaus.yml
  Packs/URLHaus/Integrations/URLHaus/URLHaus_description.md
  Packs/URLHaus/ReleaseNotes/1_0_36.json
  Packs/URLHaus/ReleaseNotes/1_0_36.md
  Packs/URLHaus/pack_metadata.json
Labels: docs-approved, sync-gsm, ready-for-pipeline-running

#40304 New script to analyze pfx file
  Packs/CommonScripts/ReleaseNotes/1_19_74.md
  Packs/CommonScripts/Scripts/PFXAnalyzer/PFXAnalyzer.py
  Packs/CommonScripts/Scripts/PFXAnalyzer/PFXAnalyzer.yml
  Packs/CommonScripts/Scripts/PFXAnalyzer/PFXAnalyzer_test.py
  Packs/CommonScripts/Scripts/PFXAnalyzer/README.md
  Packs/CommonScripts/pack_metadata.json
Labels: docs-approved, ready-for-pipeline-running

#40280 [FeedGoogleIPRanges] Fix inconsistent response
  Packs/AccentureCTI_Feed/ReleaseNotes/1_1_44.md
  Packs/AccentureCTI_Feed/pack_metadata.json
  Packs/ApiModules/Scripts/JSONFeedApiModule/JSONFeedApiModule.py
  Packs/FeedAWS/ReleaseNotes/1_1_58.md
  Packs/FeedAWS/pack_metadata.json
  Packs/FeedFastly/ReleaseNotes/1_1_35.md
  Packs/FeedFastly/pack_metadata.json
  Packs/FeedGCPWhitelist/Integrations/FeedGoogleIPRanges/FeedGoogleIPRanges.yml
  Packs/FeedGCPWhitelist/Integrations/FeedGoogleIPRanges/FeedGoogleIPRanges_test.py
  Packs/FeedGCPWhitelist/ReleaseNotes/2_0_45.md
  Packs/FeedGCPWhitelist/pack_metadata.json
  Packs/FeedIntel471/ReleaseNotes/2_1_11.md
  Packs/FeedIntel471/pack_metadata.json
  Packs/FeedJSON/ReleaseNotes/1_1_37.md
  Packs/FeedJSON/pack_metadata.json
  Packs/FeedMalwareBazaar/ReleaseNotes/1_0_48.md
  Packs/FeedMalwareBazaar/pack_metadata.json
  Packs/iDefense/ReleaseNotes/3_2_15.md
  Packs/iDefense/pack_metadata.json
Labels: docs-approved, ready-for-pipeline-running

#40285 Replace field name mapping
  Packs/AzureSecurityCenter/Integrations/AzureSecurityCenter_v2/AzureSecurityCenter_v2.py
  Packs/AzureSecurityCenter/Integrations/AzureSecurityCenter_v2/AzureSecurityCenter_v2.yml
  Packs/AzureSecurityCenter/Integrations/AzureSecurityCenter_v2/AzureSecurityCenter_v2_test.py
  Packs/AzureSecurityCenter/Integrations/AzureSecurityCenter_v2/README.md
  Packs/AzureSecurityCenter/Integrations/AzureSecurityCenter_v2/test_data/integration_test_data.json
  Packs/AzureSecurityCenter/ReleaseNotes/2_0_41.md
  Packs/AzureSecurityCenter/pack_metadata.json
Labels: docs-approved, ForceMerge, ready-for-pipeline-running

#40375 Revert markdown autofixable rules
  .markdownlint-cli2.jsonc
Labels: docs-approved, ForceMerge, ready-for-pipeline-running

#40150 [New Pack] Google Gemini Content Pack
  Packs/GoogleGemini/.pack-ignore
  Packs/GoogleGemini/.secrets-ignore
  Packs/GoogleGemini/CONTRIBUTORS.json
  Packs/GoogleGemini/Integrations/GoogleGemini/GoogleGemini.py
  Packs/GoogleGemini/Integrations/GoogleGemini/GoogleGemini.yml
  Packs/GoogleGemini/Integrations/GoogleGemini/GoogleGemini_description.md
  Packs/GoogleGemini/Integrations/GoogleGemini/GoogleGemini_image.png
  Packs/GoogleGemini/Integrations/GoogleGemini/GoogleGemini_test.py
  Packs/GoogleGemini/Integrations/GoogleGemini/README.md
  Packs/GoogleGemini/README.md
  Packs/GoogleGemini/TestPlaybooks/playbook-GoogleGemini_Test.yml
  Packs/GoogleGemini/pack_metadata.json
Labels: Contribution, docs-approved, pending-demo, Contribution Form Filled, Community, Community Support Level, External PR

#40374 Intense sso failures with suspicious characteristics prod
  Packs/CortexResponseAndRemediation/Playbooks/playbook-Intense_SSO_failures_with_suspicious_characteristics.yml
  Packs/CortexResponseAndRemediation/Playbooks/playbook-Intense_SSO_failures_with_suspicious_characteristics_README.md
  Packs/CortexResponseAndRemediation/ReleaseNotes/1_1_68.md
  Packs/CortexResponseAndRemediation/Triggers/Trigger_-_Intense_SSO_failures_with_suspicious_characteristics.json
  Packs/CortexResponseAndRemediation/doc_files/Intense_SSO_failures_with_suspicious_characteristics.png
  Packs/CortexResponseAndRemediation/pack_metadata.json
Labels: docs-approved, ready-for-pipeline-running

#40357 Added Documentation For Rasterize Timeout Configuration Instructions
  Packs/rasterize/Integrations/rasterize/README.md
  Packs/rasterize/Integrations/rasterize/rasterize.py
  Packs/rasterize/ReleaseNotes/2_1_8.md
  Packs/rasterize/pack_metadata.json
  Tests/conf.json
Labels: docs-approved, ready-for-pipeline-running

#40380 Ruff fixes
  Packs/AzureSecurityCenter/Integrations/AzureSecurityCenter_v2/AzureSecurityCenter_v2_test.py
Labels: docs-approved, ForceMerge, ready-for-pipeline-running

#40384 fix alert.severity
  Packs/TrendMicroVisionOne/ModelingRules/TrendMicroVisionOneModelingRules/TrendMicroVisionOneModelingRules.xif
  Packs/TrendMicroVisionOne/ReleaseNotes/4_2_6.md
  Packs/TrendMicroVisionOne/pack_metadata.json
Labels: docs-approved, bypass.url, ready-for-pipeline-running

#40356 Add Windows 11 and byteam privacy option support
  Packs/ANYRUN/Integrations/ANYRUN/ANYRUN.py
  Packs/ANYRUN/Integrations/ANYRUN/ANYRUN.yml
  Packs/ANYRUN/Integrations/ANYRUN/README.md
  Packs/ANYRUN/ReleaseNotes/1_0_25.md
  Packs/ANYRUN/pack_metadata.json
Labels: Contribution, docs-approved, Contribution Form Filled, Community, Xsoar Support Level, External PR

#40342 Active Directory - Added the *Error on empty arguments* parameter
  Packs/Active_Directory_Query/Integrations/Active_Directory_Query/Active_Directory_Query.py
  Packs/Active_Directory_Query/Integrations/Active_Directory_Query/Active_Directory_Query.yml
  Packs/Active_Directory_Query/ReleaseNotes/1_6_52.md
  Packs/Active_Directory_Query/pack_metadata.json
Labels: docs-approved, ForceMerge, ready-for-pipeline-running

#40398 Add 60-second timeout for Rasterize screenshot capture operations
  Packs/rasterize/Integrations/rasterize/rasterize.py
  Packs/rasterize/Integrations/rasterize/rasterize_test.py
  Packs/rasterize/ReleaseNotes/2_1_9.md
  Packs/rasterize/pack_metadata.json
Labels: docs-approved, ready-for-pipeline-running

#40308 New pan-os-get-certificate-info command
  Packs/PAN-OS/Integrations/Panorama/Panorama.py
  Packs/PAN-OS/Integrations/Panorama/Panorama.yml
  Packs/PAN-OS/Integrations/Panorama/Panorama_test.py
  Packs/PAN-OS/Integrations/Panorama/README.md
  Packs/PAN-OS/Integrations/Panorama/test_data/config_predefined_certificate.txt
  Packs/PAN-OS/Integrations/Panorama/test_data/get_certificate_info_command.json
  Packs/PAN-OS/Integrations/Panorama/test_data/request_certificate_show.xml
  Packs/PAN-OS/Integrations/Panorama/test_data/show_running_config.xml
  Packs/PAN-OS/ReleaseNotes/2_5_1.md
  Packs/PAN-OS/pack_metadata.json
Labels: docs-approved, ready-for-pipeline-running
