Repository demisto/content, pull requests merged in 2025-05, with the labels that each got.

#39761 microsoftTeams - microsoft-teams-message-send-to-chat message_type ar…
  Packs/MicrosoftTeams/Integrations/MicrosoftTeams/MicrosoftTeams.py
  Packs/MicrosoftTeams/Integrations/MicrosoftTeams/MicrosoftTeams.yml
  Packs/MicrosoftTeams/Integrations/MicrosoftTeams/README.md
  Packs/MicrosoftTeams/ReleaseNotes/1_5_26.json
  Packs/MicrosoftTeams/ReleaseNotes/1_5_26.md
  Packs/MicrosoftTeams/pack_metadata.json
Labels: ForceMerge, ready-for-pipeline-running

#39511 New pack - Cortex CloudSec
  Packs/AWS/.pack-ignore
  Packs/AWS/.secrets-ignore
  Packs/AWS/CONTRIBUTORS.json
  Packs/AWS/Integrations/AWS/AWS.py
  Packs/AWS/Integrations/AWS/AWS.yml
  Packs/AWS/Integrations/AWS/AWS_description.md
  Packs/AWS/Integrations/AWS/AWS_image.png
  Packs/AWS/Integrations/AWS/AWS_test.py
  Packs/AWS/Integrations/AWS/README.md
  Packs/AWS/Integrations/AWS/command_examples.txt
  Packs/AWS/README.md
  Packs/AWS/pack_metadata.json
Labels: Contribution, docs-approved, Contribution Form Filled, Community, Xsoar Support Level, External PR

#39750 CIAC 13610: GitHub actions updates
  .github/content_roles.json
  .github/github_workflow_scripts/create_internal_pr.py
  .github/github_workflow_scripts/handle_external_pr.py
  .github/github_workflow_scripts/utils_test.py
Labels: docs-approved, ready-for-pipeline-running

#39796 Added a task to check if job id exists
  Packs/PAN-OS/Playbooks/PAN-OS_Commit_Configuration_v2.yml
  Packs/PAN-OS/Playbooks/PAN-OS_Commit_Configuration_v2_README.md
  Packs/PAN-OS/ReleaseNotes/2_3_12.md
  Packs/PAN-OS/doc_files/PAN-OS_Commit_Configuration_v2.png
  Packs/PAN-OS/pack_metadata.json
Labels: docs-approved, ready-for-pipeline-running

#39691 Splunkpy splunk-search UnicodeDecodeError fix
  Packs/SplunkPy/Integrations/SplunkPy/SplunkPy.py
  Packs/SplunkPy/Integrations/SplunkPy/SplunkPy_test.py
  Packs/SplunkPy/ReleaseNotes/3_2_10.md
  Packs/SplunkPy/pack_metadata.json
Labels: docs-approved, ready-for-pipeline-running

#39754 Ewso365 get attachment output parsing fix
  Packs/MicrosoftExchangeOnline/Integrations/EWSO365/EWSO365.py
  Packs/MicrosoftExchangeOnline/Integrations/EWSO365/EWSO365.yml
  Packs/MicrosoftExchangeOnline/Integrations/EWSO365/EWSO365_test.py
  Packs/MicrosoftExchangeOnline/ReleaseNotes/1_6_6.md
  Packs/MicrosoftExchangeOnline/pack_metadata.json
Labels: docs-approved, ready-for-pipeline-running

#39753 Extract indicators from file generic v2 - Multiple PDF fixes
  Packs/CommonPlaybooks/.pack-ignore
  Packs/CommonPlaybooks/Playbooks/playbook-Extract_Indicators_From_File_-_Generic_v2_4_5.yml
  Packs/CommonPlaybooks/Playbooks/playbook-Extract_Indicators_From_File_-_Generic_v2_4_5_README.md
  Packs/CommonPlaybooks/ReleaseNotes/2_7_0.md
  Packs/CommonPlaybooks/doc_files/Extract_Indicators_From_File_-_Generic_v2.png
  Packs/CommonPlaybooks/pack_metadata.json
  Packs/CommonScripts/ReleaseNotes/1_19_51.md
  Packs/CommonScripts/Scripts/CheckPDFEncryptionAndValidity/CheckPDFEncryptionAndValidity.yml
  Packs/CommonScripts/pack_metadata.json
Labels: docs-approved, release-notes-only, ready-for-pipeline-running

#39770 version bump
  Packs/CybleEventsV2/Integrations/CybleEventsV2/CybleEventsV2.yml
  Packs/CybleEventsV2/Layouts/layoutscontainer-Cyble_Vision_Alert_V2.json
  Packs/CybleEventsV2/ReleaseNotes/1_0_8.md
  Packs/CybleEventsV2/pack_metadata.json
Labels: docs-approved, ForceMerge, ready-for-pipeline-running

#39332 run-with-output aggregation command
  Packs/ApiModules/ReleaseNotes/2_2_45.md
  Packs/ApiModules/Scripts/CoreIRApiModule/CoreIRApiModule.py
  Packs/ApiModules/pack_metadata.json
  Packs/Core/.secrets-ignore
  Packs/Core/Integrations/CortexCoreIR/CortexCoreIR.py
  Packs/Core/Integrations/CortexCoreIR/CortexCoreIR.yml
  Packs/Core/Integrations/CortexCoreIR/CortexCoreIR_test.py
  Packs/Core/Integrations/CortexCoreIR/README.md
  Packs/Core/Integrations/CortexCoreIR/command_examples.txt
  Packs/Core/Integrations/CortexCoreIR/test_data/execute_command_response.json
  Packs/Core/ReleaseNotes/3_2_40.md
  Packs/Core/pack_metadata.json
  Packs/CortexXDR/ReleaseNotes/6_2_21.md
  Packs/CortexXDR/pack_metadata.json
  Packs/ctf01/ReleaseNotes/1_0_42.md
  Packs/ctf01/pack_metadata.json
Labels: docs-approved, ForceMerge, ready-for-pipeline-running

#39798 split the rawjson data handling to fetch-events and fetch-incidents
  Packs/CrowdStrikeFalcon/Integrations/CrowdStrikeFalcon/CrowdStrikeFalcon.py
  Packs/CrowdStrikeFalcon/ReleaseNotes/2_1_20.md
  Packs/CrowdStrikeFalcon/pack_metadata.json
Labels: docs-approved, ready-for-pipeline-running

#39640 Ys docs approved github action
  .github/github_workflow_scripts/check_if_docs_approved_label_exists.py
  .github/workflows/check-docs-approved-label.yml
Labels: docs-approved, ready-for-pipeline-running

#39551 Darktrace email 1
  Packs/Darktrace/.secrets-ignore
  Packs/Darktrace/Classifiers/classifier-Darktrace_Email.json
  Packs/Darktrace/IncidentFields/incidentfield-Darktrace_Email_Action_Status.json
  Packs/Darktrace/IncidentFields/incidentfield-Darktrace_Email_Actions.json
  Packs/Darktrace/IncidentFields/incidentfield-Darktrace_Email_Actions_Taken.json
  Packs/Darktrace/IncidentFields/incidentfield-Darktrace_Email_Anomaly_Score.json
  Packs/Darktrace/IncidentFields/incidentfield-Darktrace_Email_Attachments.json
  Packs/Darktrace/IncidentFields/incidentfield-Darktrace_Email_Critical_Tags.json
  Packs/Darktrace/IncidentFields/incidentfield-Darktrace_Email_Direction.json
  Packs/Darktrace/IncidentFields/incidentfield-Darktrace_Email_Group_Status.json
  Packs/Darktrace/IncidentFields/incidentfield-Darktrace_Email_Informational_Tags.json
  Packs/Darktrace/IncidentFields/incidentfield-Darktrace_Email_Links.json
  Packs/Darktrace/IncidentFields/incidentfield-Darktrace_Email_Read_Status.json
  Packs/Darktrace/IncidentFields/incidentfield-Darktrace_Email_Receipt_Status.json
  Packs/Darktrace/IncidentFields/incidentfield-Darktrace_Email_Recipient.json
  Packs/Darktrace/IncidentFields/incidentfield-Darktrace_Email_Release_Requested.json
  Packs/Darktrace/IncidentFields/incidentfield-Darktrace_Email_Sender.json
  Packs/Darktrace/IncidentFields/incidentfield-Darktrace_Email_Subject.json
  Packs/Darktrace/IncidentFields/incidentfield-Darktrace_Email_Summary.json
  Packs/Darktrace/IncidentFields/incidentfield-Darktrace_Email_Tags.json
  Packs/Darktrace/IncidentFields/incidentfield-Darktrace_Email_Time.json
  Packs/Darktrace/IncidentFields/incidentfield-Darktrace_Email_UI_Link.json
  Packs/Darktrace/IncidentFields/incidentfield-Darktrace_Email_UUID.json
  Packs/Darktrace/IncidentFields/incidentfield-Darktrace_Email_Warning_Tags.json
  Packs/Darktrace/IncidentTypes/incidenttype-Darktrace_Email.json
  Packs/Darktrace/Integrations/DarktraceEmail/DarktraceEmail.py
  Packs/Darktrace/Integrations/DarktraceEmail/DarktraceEmail.yml
  Packs/Darktrace/Integrations/DarktraceEmail/DarktraceEmail_description.md
  Packs/Darktrace/Integrations/DarktraceEmail/DarktraceEmail_image.png
  Packs/Darktrace/Integrations/DarktraceEmail/DarktraceEmail_test.py
  Packs/Darktrace/Integrations/DarktraceEmail/README.md
  Packs/Darktrace/Integrations/DarktraceEmail/test_data/fetch_incidents.json
  Packs/Darktrace/Integrations/DarktraceEmail/test_data/formatted_fetch_incidents.json
  Packs/Darktrace/Integrations/DarktraceEmail/test_data/formatted_get_email.json
  Packs/Darktrace/Integrations/DarktraceEmail/test_data/formatted_hold_email.json
  Packs/Darktrace/Integrations/DarktraceEmail/test_data/formatted_release_email.json
  Packs/Darktrace/Integrations/DarktraceEmail/test_data/get_email.json
  Packs/Darktrace/Integrations/DarktraceEmail/test_data/get_tags.json
  Packs/Darktrace/Integrations/DarktraceEmail/test_data/hold_email.json
  Packs/Darktrace/Integrations/DarktraceEmail/test_data/incident_01.json
  Packs/Darktrace/Integrations/DarktraceEmail/test_data/incident_02.json
  Packs/Darktrace/Integrations/DarktraceEmail/test_data/release_email.json
  Packs/Darktrace/Layouts/layoutscontainer-Darktrace_Email_Layout.json
  Packs/Darktrace/Playbooks/playbook-Darktrace_Email_Basic_Email_Handler.yml
  Packs/Darktrace/Playbooks/playbook-Darktrace_Email_Basic_Email_Handler_README.md
  Packs/Darktrace/Playbooks/playbook-Darktrace_Email_Update_Incident_Fields.yml
  Packs/Darktrace/Playbooks/playbook-Darktrace_Email_Update_Incident_Fields_README.md
  Packs/Darktrace/ReleaseNotes/4_0_0.md
  Packs/Darktrace/doc_files/Darktrace_Email_Basic_Email_Handler.png
  Packs/Darktrace/doc_files/Darktrace_Email_Update_Incident_Fields.png
  Packs/Darktrace/pack_metadata.json
Labels: Contribution, docs-approved, Partner, pending-demo, Contribution Form Filled, pending-contributor, Partner Support Level, External PR, Security Review, Partner-Approved, Security Approved

#39786 Updating the pack to add 2 more signatures
  Packs/PaloAltoNetworksPQCHunting_Community/Playbooks/PAN-OS_Search_for_Post_Quantum_Crypto_Vuln_Sigs.yml
  Packs/PaloAltoNetworksPQCHunting_Community/ReleaseNotes/1_0_1.md
  Packs/PaloAltoNetworksPQCHunting_Community/pack_metadata.json
Labels: Contribution, docs-approved, Contribution Form Filled, Community, Community Support Level, External PR, Security Review

#39723 ServerLogs script fix
  Packs/CommonScripts/ReleaseNotes/1_19_52.md
  Packs/CommonScripts/Scripts/ServerLogs/README.md
  Packs/CommonScripts/Scripts/ServerLogs/ServerLogs.py
  Packs/CommonScripts/Scripts/ServerLogs/ServerLogs.yml
  Packs/CommonScripts/Scripts/ServerLogsDocker/README.md
  Packs/CommonScripts/Scripts/ServerLogsDocker/ServerLogsDocker.yml
  Packs/CommonScripts/pack_metadata.json
Labels: docs-approved, ForceMerge, ready-for-pipeline-running

#39710 [HTTPFeedApiModule] Fixed a syntax issue in the feeds
  Packs/ApiModules/Scripts/HTTPFeedApiModule/HTTPFeedApiModule.py
  Packs/FeedBlocklist_de/ReleaseNotes/1_1_35.md
  Packs/FeedBlocklist_de/pack_metadata.json
  Packs/FeedBruteForceBlocker/ReleaseNotes/1_1_33.md
  Packs/FeedBruteForceBlocker/pack_metadata.json
  Packs/FeedCloudflare/ReleaseNotes/1_1_33.md
  Packs/FeedCloudflare/pack_metadata.json
  Packs/FeedDShield/ReleaseNotes/1_1_38.md
  Packs/FeedDShield/pack_metadata.json
  Packs/FeedFeodoTracker/ReleaseNotes/1_1_35.md
  Packs/FeedFeodoTracker/pack_metadata.json
  Packs/FeedMalwareDomainList/ReleaseNotes/1_1_13.md
  Packs/FeedMalwareDomainList/pack_metadata.json
  Packs/FeedPlainText/ReleaseNotes/1_1_34.md
  Packs/FeedPlainText/pack_metadata.json
  Packs/FeedSpamhaus/ReleaseNotes/1_1_32.md
  Packs/FeedSpamhaus/pack_metadata.json
Labels: docs-approved, ForceMerge, ready-for-pipeline-running

#39758 CRTX-168369: remove platform
  Config/core_packs_platform_list.json
  Packs/CortexAttackSurfaceManagement/pack_metadata.json
Labels: docs-approved, ForceMerge, bypass.url, ready-for-pipeline-running

#38952 Updates to Sigma Pack
  Packs/Sigma/ReleaseNotes/1_0_4.md
  Packs/Sigma/Scripts/CreateSigmaRuleIndicator/CreateSigmaRuleIndicator.py
  Packs/Sigma/Scripts/CreateSigmaRuleIndicator/CreateSigmaRuleIndicator.yml
  Packs/Sigma/Scripts/CreateSigmaRuleIndicator/CreateSigmaRuleIndicator_test.py
  Packs/Sigma/Scripts/ImportSigmaRulesFromZIP/ImportSigmaRulesFromZIP.py
  Packs/Sigma/Scripts/ImportSigmaRulesFromZIP/ImportSigmaRulesFromZIP.yml
  Packs/Sigma/Scripts/ImportSigmaRulesFromZIP/README.md
  Packs/Sigma/pack_metadata.json
Labels: docs-approved, ready-for-pipeline-running

#39803 Google Apigee Integration - Error in API call
  Packs/GoogleApigee/Integrations/GoogleApigeeEventCollector/GoogleApigeeEventCollector.py
  Packs/GoogleApigee/Integrations/GoogleApigeeEventCollector/GoogleApigeeEventCollector.yml
  Packs/GoogleApigee/Integrations/GoogleApigeeEventCollector/GoogleApigeeEventCollector_test.py
  Packs/GoogleApigee/ReleaseNotes/1_0_2.md
  Packs/GoogleApigee/pack_metadata.json
Labels: docs-approved, ready-for-pipeline-running

#39791 Abnormal Security - Filter bug Fixes
  Packs/AbnormalSecurity/Integrations/AbnormalSecurity/AbnormalSecurity.py
  Packs/AbnormalSecurity/Integrations/AbnormalSecurity/AbnormalSecurity.yml
  Packs/AbnormalSecurity/Integrations/AbnormalSecurity/AbnormalSecurity_test.py
  Packs/AbnormalSecurity/Integrations/AbnormalSecurity/README.md
  Packs/AbnormalSecurity/ReleaseNotes/2_3_2.md
  Packs/AbnormalSecurity/pack_metadata.json
Labels: Contribution, docs-approved, Partner, Contribution Form Filled, Partner Support Level, External PR, Partner-Approved

#39784 Ti cloud v2.7.1
  Packs/ReversingLabs_Titanium_Cloud/.secrets-ignore
  Packs/ReversingLabs_Titanium_Cloud/Integrations/ReversingLabsTitaniumCloudv2/ReversingLabsTitaniumCloudv2.py
  Packs/ReversingLabs_Titanium_Cloud/Integrations/ReversingLabsTitaniumCloudv2/ReversingLabsTitaniumCloudv2_test.py
  Packs/ReversingLabs_Titanium_Cloud/Integrations/ReversingLabsTitaniumCloudv2/test_data/url_report_context.json
  Packs/ReversingLabs_Titanium_Cloud/Integrations/ReversingLabsTitaniumCloudv2/test_data/url_report_report.json
  Packs/ReversingLabs_Titanium_Cloud/ReleaseNotes/2_7_1.md
  Packs/ReversingLabs_Titanium_Cloud/pack_metadata.json
Labels: Contribution, docs-approved, Partner, Contribution Form Filled, Partner Support Level, External PR, Partner-Approved

#39802 RecordedFuture Remove RawJson
  Packs/FeedRecordedFuture/Integrations/FeedRecordedFuture/FeedRecordedFuture.py
  Packs/FeedRecordedFuture/Integrations/FeedRecordedFuture/FeedRecordedFuture.yml
  Packs/FeedRecordedFuture/ReleaseNotes/1_1_8.json
  Packs/FeedRecordedFuture/ReleaseNotes/1_1_8.md
  Packs/FeedRecordedFuture/pack_metadata.json
Labels: docs-approved, ready-for-pipeline-running

#39813 fix for REST playbook - First Azure AD PowerShell operation for a user
  Packs/CortexResponseAndRemediation/Playbooks/silent-playbook-First_Azure_AD_PowerShell_operation_for_a_user.yml
  Packs/CortexResponseAndRemediation/ReleaseNotes/1_1_41.md
  Packs/CortexResponseAndRemediation/pack_metadata.json
Labels: docs-approved, ready-for-pipeline-running

#39744 added a fix to the containment plan isolate device
  Packs/CommonPlaybooks/Playbooks/playbook-Containment_Plan_-_Isolate_Device.yml
  Packs/CommonPlaybooks/ReleaseNotes/2_7_1.md
  Packs/CommonPlaybooks/pack_metadata.json
Labels: docs-approved, bypass.url, ready-for-pipeline-running

#39814 rest playbooks - fix - added continue on error to enrichment tasks
  Packs/CortexResponseAndRemediation/Playbooks/playbook-Suspicious_process_execution_by_scheduled_task_on_a_sensitive_server.yml
  Packs/CortexResponseAndRemediation/Playbooks/playbook-Uncommon_remote_scheduled_task_created.yml
  Packs/CortexResponseAndRemediation/Playbooks/silent-playbook-Execution_of_an_uncommon_process_at_an_early_startup_stage.yml
  Packs/CortexResponseAndRemediation/Playbooks/silent-playbook-Suspicious_process_execution_by_scheduled_task_on_a_sensitive_server_Test.yml
  Packs/CortexResponseAndRemediation/Playbooks/silent-playbook-Uncommon_remote_scheduled_task_created_Test.yml
  Packs/CortexResponseAndRemediation/ReleaseNotes/1_1_42.md
  Packs/CortexResponseAndRemediation/pack_metadata.json
Labels: docs-approved, ready-for-pipeline-running

#39821 skipped mail listener tpb as its being blocked by CRTX-171878
  Tests/conf.json
Labels: docs-approved, ready-for-pipeline-running

#39827 Fix-containment-plan-isolate-device
  Packs/CommonPlaybooks/Playbooks/playbook-Containment_Plan_-_Isolate_Device.yml
  Packs/CommonPlaybooks/ReleaseNotes/2_7_2.md
  Packs/CommonPlaybooks/pack_metadata.json
Labels: docs-approved, ready-for-pipeline-running

#39506 [Zerofox] Key Incidents Integration
  Packs/ZeroFox/Classifiers/classifier-ZeroFox_Key_Incident_Incoming_Mapper.json
  Packs/ZeroFox/IncidentFields/ZeroFoxKeyIncidents_Analysis.json
  Packs/ZeroFox/IncidentFields/ZeroFoxKeyIncidents_Headline.json
  Packs/ZeroFox/IncidentTypes/ZeroFox_Key_Incident.json
  Packs/ZeroFox/Integrations/ZeroFox/ZeroFox_test.py
  Packs/ZeroFox/Integrations/ZeroFoxKeyIncidents/README.md
  Packs/ZeroFox/Integrations/ZeroFoxKeyIncidents/ZeroFoxKeyIncidents.py
  Packs/ZeroFox/Integrations/ZeroFoxKeyIncidents/ZeroFoxKeyIncidents.yml
  Packs/ZeroFox/Integrations/ZeroFoxKeyIncidents/ZeroFoxKeyIncidents_dark.svg
  Packs/ZeroFox/Integrations/ZeroFoxKeyIncidents/ZeroFoxKeyIncidents_description.md
  Packs/ZeroFox/Integrations/ZeroFoxKeyIncidents/ZeroFoxKeyIncidents_image.png
  Packs/ZeroFox/Integrations/ZeroFoxKeyIncidents/ZeroFoxKeyIncidents_light.svg
  Packs/ZeroFox/Integrations/ZeroFoxKeyIncidents/ZeroFoxKeyIncidents_test.py
  Packs/ZeroFox/Integrations/ZeroFoxKeyIncidents/test_data/key_incident_attachments/ki_attachment.json
  Packs/ZeroFox/Integrations/ZeroFoxKeyIncidents/test_data/key_incident_attachments/parsed_ki_attachment.json
  Packs/ZeroFox/Integrations/ZeroFoxKeyIncidents/test_data/key_incidents/key_incidents_response_first_page.json
  Packs/ZeroFox/Integrations/ZeroFoxKeyIncidents/test_data/key_incidents/key_incidents_response_second_page.json
  Packs/ZeroFox/Integrations/ZeroFoxKeyIncidents/test_data/key_incidents/parsed_key_incidents.json
  Packs/ZeroFox/Layouts/layoutscontainer-ZeroFoxKeyIncidents_layout.json
  Packs/ZeroFox/README.md
  Packs/ZeroFox/ReleaseNotes/1_4_0.md
  Packs/ZeroFox/pack_metadata.json
Labels: Contribution, docs-approved, Partner, pending-demo, Contribution Form Filled, pending-contributor, Partner Support Level, External PR, Security Review, Partner-Approved, Pending-Partner, Security Approved

#39711 Cs falcon intel: cs-indicators command - single quote.
  Packs/CrowdStrikeIntel/Integrations/CrowdStrikeFalconIntel_v2/CrowdStrikeFalconIntel_v2.py
  Packs/CrowdStrikeIntel/Integrations/CrowdStrikeFalconIntel_v2/CrowdStrikeFalconIntel_v2.yml
  Packs/CrowdStrikeIntel/ReleaseNotes/2_0_41.md
  Packs/CrowdStrikeIntel/pack_metadata.json
Labels: docs-approved, ready-for-pipeline-running

#39830 Parse email 0.1.36
  Packs/CommonScripts/ReleaseNotes/1_19_53.md
  Packs/CommonScripts/Scripts/ParseEmailFilesV2/ParseEmailFilesV2.yml
  Packs/CommonScripts/pack_metadata.json
Labels: docs-approved, ready-for-pipeline-running

#39833 Alignment tags, keywords and categories packs (chunk9)
  Packs/CloakedUrsaPhishingCampaign/pack_metadata.json
  Packs/CloudIncidentResponse/pack_metadata.json
  Packs/Code42/pack_metadata.json
  Packs/CofenseIntelligenceV2/pack_metadata.json
  Packs/CofenseTriage/pack_metadata.json
  Packs/CofenseVision/pack_metadata.json
  Packs/CohesityHelios/pack_metadata.json
Labels: docs-approved, ready-for-pipeline-running

#39799 Ciac 13612 fix absolute endpoints
  Packs/Absolute/Integrations/Absolute/Absolute.py
  Packs/Absolute/Integrations/Absolute/Absolute.yml
  Packs/Absolute/Integrations/Absolute/Absolute_test.py
  Packs/Absolute/ReleaseNotes/2_0_2.md
  Packs/Absolute/pack_metadata.json
  Tests/conf.json
Labels: docs-approved, ready-for-pipeline-running

#39591 Xsup 49180 abnormal fix fetch exceed limit
  Packs/AbnormalSecurity/Integrations/AbnormalSecurityEventCollector/AbnormalSecurityEventCollector.py
  Packs/AbnormalSecurity/Integrations/AbnormalSecurityEventCollector/AbnormalSecurityEventCollector.yml
  Packs/AbnormalSecurity/Integrations/AbnormalSecurityEventCollector/AbnormalSecurityEventCollector_test.py
  Packs/AbnormalSecurity/ReleaseNotes/2_3_3.md
  Packs/AbnormalSecurity/pack_metadata.json
Labels: docs-approved, ready-for-pipeline-running

#39825 added ruff-format hook to pre-commit
  .pre-commit-config_template.yaml
Labels: docs-approved, ready-for-pipeline-running

#39864 Added git-blame-ignore-revs file
  .git-blame-ignore-revs
Labels: docs-approved, ready-for-pipeline-running

#39870 Update Author_image.png file
  Packs/Reco/Author_image.png
Labels: Contribution, docs-approved, Partner, Contribution Form Filled, Partner Support Level, External PR, Partner-Approved

#39831 Symantec BlueCoat ProxySG CRTX-164849
  Packs/SymantecBlueCoatProxySG/ModelingRules/SymantecBlueCoatProxySG/SymantecBlueCoatProxySG.xif
  Packs/SymantecBlueCoatProxySG/README.md
  Packs/SymantecBlueCoatProxySG/ReleaseNotes/1_0_5.md
  Packs/SymantecBlueCoatProxySG/doc_files/SymantecBlueCoatProxySG_image3.png
  Packs/SymantecBlueCoatProxySG/pack_metadata.json
Labels: docs-approved, bypass.url, ready-for-pipeline-running

#39874 Fix an unformatted file
  Packs/QRadar/Integrations/QRadar_v3/QRadar_v3.py
  Packs/QRadar/Integrations/QRadar_v3/QRadar_v3.yml
  Packs/QRadar/Integrations/QRadar_v3/QRadar_v3_test.py
  Packs/QRadar/ReleaseNotes/2_5_17.md
  Packs/QRadar/pack_metadata.json
Labels: docs-approved, ready-for-pipeline-running

#39828 A User Executed Multiple LDAP Enumeration Queries - action_id fix
  Packs/CortexResponseAndRemediation/Playbooks/playbook-A_user_executed_multiple_LDAP_enumeration_queries.yml
  Packs/CortexResponseAndRemediation/Playbooks/silent-playbook-A_user_executed_multiple_LDAP_enumeration_queries_Test.yml
  Packs/CortexResponseAndRemediation/ReleaseNotes/1_1_43.md
  Packs/CortexResponseAndRemediation/doc_files/A_user_executed_multiple_LDAP_enumeration_queries.png
  Packs/CortexResponseAndRemediation/pack_metadata.json
Labels: docs-approved, release-notes-only, ready-for-pipeline-running

#39869 add AWS pack to platform core packs list
  Config/core_packs_platform_list.json
Labels: docs-approved, ready-for-pipeline-running

#39839 CiscoThreat un-clickable URL
  Packs/ThreatGrid/.secrets-ignore
  Packs/ThreatGrid/Integrations/ThreatGridv2/ThreatGridv2.py
  Packs/ThreatGrid/Integrations/ThreatGridv2/ThreatGridv2.yml
  Packs/ThreatGrid/Integrations/ThreatGridv2/ThreatGridv2_test.py
  Packs/ThreatGrid/ReleaseNotes/2_0_26.md
  Packs/ThreatGrid/pack_metadata.json
Labels: docs-approved, ready-for-pipeline-running

#39236 CIAC-12409: Block External IP
  Packs/CommonScripts/.secrets-ignore
  Packs/CommonScripts/ReleaseNotes/1_19_54.md
  Packs/CommonScripts/Scripts/BlockExternalIp/BlockExternalIp.py
  Packs/CommonScripts/Scripts/BlockExternalIp/BlockExternalIp.yml
  Packs/CommonScripts/Scripts/BlockExternalIp/BlockExternalIp_test.py
  Packs/CommonScripts/Scripts/BlockExternalIp/README.md
  Packs/CommonScripts/Scripts/BlockExternalIp/test_data/cisco_asa_responses.json
  Packs/CommonScripts/Scripts/BlockExternalIp/test_data/pan_os_responses.json
  Packs/CommonScripts/Scripts/BlockExternalIp/test_data/prisma_sase_responses.json
  Packs/CommonScripts/pack_metadata.json
Labels: docs-approved, ready-for-pipeline-running

#39660 SIGNL4 Mobile Alerting for Cortex XSOAR
  .gitignore
  Packs/SIGNL4/.pack-ignore
  Packs/SIGNL4/.secrets-ignore
  Packs/SIGNL4/Integrations/SIGNL4/README.md
  Packs/SIGNL4/Integrations/SIGNL4/SIGNL4.py
  Packs/SIGNL4/Integrations/SIGNL4/SIGNL4.yml
  Packs/SIGNL4/Integrations/SIGNL4/SIGNL4_description.md
  Packs/SIGNL4/Integrations/SIGNL4/SIGNL4_image.png
  Packs/SIGNL4/Integrations/SIGNL4/SIGNL4_test.py
  Packs/SIGNL4/Integrations/SIGNL4/test_data/signl4-alert.json
  Packs/SIGNL4/Integrations/SIGNL4/test_data/signl4-close.json
  Packs/SIGNL4/README.md
  Packs/SIGNL4/doc_files/signl4-xsoar.png
  Packs/SIGNL4/pack_metadata.json
  Packs/Whois/Integrations/Whois/test_data/microsocks
  s4_test/uploadable_packs/SIGNL4.zip
Labels: Contribution, docs-approved, Partner, Contribution Form Filled, Partner Support Level, External PR, Partner-Approved, bypass.url

#39856 Add escape_misc argument to htmltomd script
  Packs/CommonScripts/ReleaseNotes/1_19_55.md
  Packs/CommonScripts/Scripts/HTMLtoMD/HTMLtoMD.py
  Packs/CommonScripts/Scripts/HTMLtoMD/HTMLtoMD.yml
  Packs/CommonScripts/Scripts/HTMLtoMD/HTMLtoMD_test.py
  Packs/CommonScripts/Scripts/HTMLtoMD/README.md
  Packs/CommonScripts/pack_metadata.json
Labels: docs-approved, ready-for-pipeline-running

#39642 CRTX-158630-GCP-flow-logs
  Packs/GoogleCloudLogging/ModelingRules/GoogleCloudLogging/GoogleCloudLogging.xif
  Packs/GoogleCloudLogging/README.md
  Packs/GoogleCloudLogging/ReleaseNotes/1_0_21.md
  Packs/GoogleCloudLogging/pack_metadata.json
Labels: docs-approved, bypass.url, ready-for-pipeline-running

#39729 Ms atp typo
  Packs/MicrosoftDefenderAdvancedThreatProtection/Integrations/MicrosoftDefenderAdvancedThreatProtection/MicrosoftDefenderAdvancedThreatProtection.py
  Packs/MicrosoftDefenderAdvancedThreatProtection/Integrations/MicrosoftDefenderAdvancedThreatProtection/test_data/expected_hunting_queries.json
  Packs/MicrosoftDefenderAdvancedThreatProtection/ReleaseNotes/1_18_5.md
  Packs/MicrosoftDefenderAdvancedThreatProtection/pack_metadata.json
Labels: docs-approved, ready-for-pipeline-running

#39884 XSUP-50415-msft-azure
  Packs/MicrosoftEntraID/ParsingRules/MicrosoftEntraID/MicrosoftEntraID.xif
  Packs/MicrosoftEntraID/ReleaseNotes/1_0_15.md
  Packs/MicrosoftEntraID/pack_metadata.json
Labels: docs-approved, bypass.url, ready-for-pipeline-running

#39886 XSUP-48818 Windows Parsing Update
  Packs/MicrosoftWindowsEvents/ParsingRules/MicrosoftWindowsEvents/MicrosoftWindowsEvents.xif
  Packs/MicrosoftWindowsEvents/ReleaseNotes/1_1_13.md
  Packs/MicrosoftWindowsEvents/pack_metadata.json
Labels: docs-approved, bypass.url, ready-for-pipeline-running

#39887 removed mp from yml
  Packs/LookoutMobileEndpointSecurity/Integrations/LookoutMobileEndpointSecurity/LookoutMobileEndpointSecurity.yml
Labels: docs-approved, ForceMerge, ready-for-pipeline-running

#39714 UnskipPaloAltoNetworksAIOps
  Tests/conf.json
Labels: docs-approved, ready-for-pipeline-running

#39353 Add CRUD operations for Azure
  Packs/MicrosoftGraphUser/Integrations/MicrosoftGraphUser/MicrosoftGraphUser.py
  Packs/MicrosoftGraphUser/Integrations/MicrosoftGraphUser/MicrosoftGraphUser.yml
  Packs/MicrosoftGraphUser/Integrations/MicrosoftGraphUser/MicrosoftGraphUser_test.py
  Packs/MicrosoftGraphUser/Integrations/MicrosoftGraphUser/README.md
  Packs/MicrosoftGraphUser/Integrations/MicrosoftGraphUser/command_examples.txt
  Packs/MicrosoftGraphUser/ReleaseNotes/1_5_46.md
  Packs/MicrosoftGraphUser/TestPlaybooks/Microsoft_Graph_User_test.yml
  Packs/MicrosoftGraphUser/pack_metadata.json
Labels: docs-approved, ready-for-pipeline-running

#39891 Red canary domain context
  Packs/RedCanary/Integrations/RedCanary/RedCanary.py
  Packs/RedCanary/Integrations/RedCanary/RedCanary.yml
  Packs/RedCanary/Integrations/RedCanary/RedCanary_description.md
  Packs/RedCanary/Integrations/RedCanary/RedCanary_test.py
  Packs/RedCanary/Integrations/RedCanary/TestData/detection.json
  Packs/RedCanary/Integrations/RedCanary/TestData/detection_timeline.json
  Packs/RedCanary/ReleaseNotes/1_1_25.md
  Packs/RedCanary/pack_metadata.json
Labels: docs-approved, ready-for-pipeline-running

#39846 XSUP-50225 OracleCloudInfrastructureEventCollector
  Packs/OracleCloudInfrastructure/Integrations/OracleCloudInfrastructureEventCollector/OracleCloudInfrastructureEventCollector.py
  Packs/OracleCloudInfrastructure/Integrations/OracleCloudInfrastructureEventCollector/OracleCloudInfrastructureEventCollector.yml
  Packs/OracleCloudInfrastructure/Integrations/OracleCloudInfrastructureEventCollector/OracleCloudInfrastructureEventCollector_test.py
  Packs/OracleCloudInfrastructure/ReleaseNotes/1_0_29.md
  Packs/OracleCloudInfrastructure/pack_metadata.json
Labels: docs-approved, ready-for-pipeline-running

#39781 CRTX-164053-Proofpoint-Email-Security
  Packs/ProofpointEmailSecurity/ModelingRules/ProofpointEmailSecurity/ProofpointEmailSecurity.xif
  Packs/ProofpointEmailSecurity/ReleaseNotes/1_0_13.md
  Packs/ProofpointEmailSecurity/pack_metadata.json
Labels: docs-approved, bypass.url, ready-for-pipeline-running

#39896 XSUP 48818 Backend issue bypass
  Packs/MicrosoftWindowsEvents/ParsingRules/MicrosoftWindowsEvents/MicrosoftWindowsEvents.xif
  Packs/MicrosoftWindowsEvents/ReleaseNotes/1_1_14.md
  Packs/MicrosoftWindowsEvents/pack_metadata.json
Labels: docs-approved, bypass.url, ready-for-pipeline-running

#39883 Ciac 13359 cs event collector in xsaim last run
  Packs/CrowdStrikeFalcon/Integrations/CrowdStrikeFalcon/CrowdStrikeFalcon.py
  Packs/CrowdStrikeFalcon/Integrations/CrowdStrikeFalcon/CrowdStrikeFalcon_test.py
  Packs/CrowdStrikeFalcon/ReleaseNotes/2_1_21.md
  Packs/CrowdStrikeFalcon/pack_metadata.json
Labels: docs-approved, ready-for-pipeline-running

#38918 Mandiant - is time sensitive related changes
  Packs/MandiantAdvantageThreatIntelligence/Integrations/Mandiant/Mandiant.py
  Packs/MandiantAdvantageThreatIntelligence/Integrations/Mandiant/Mandiant.yml
  Packs/MandiantAdvantageThreatIntelligence/Integrations/MandiantAdvantageThreatIntelligence/MandiantAdvantageThreatIntelligence.py
  Packs/MandiantAdvantageThreatIntelligence/Integrations/MandiantAdvantageThreatIntelligence/MandiantAdvantageThreatIntelligence.yml
  Packs/MandiantAdvantageThreatIntelligence/ReleaseNotes/1_1_7.md
  Packs/MandiantAdvantageThreatIntelligence/pack_metadata.json
Labels: docs-approved, ForceMerge, ready-for-pipeline-running

#39908 Rtir reply action fix
  Packs/RTIR/Integrations/RTIR/RTIR.py
  Packs/RTIR/Integrations/RTIR/RTIR.yml
  Packs/RTIR/ReleaseNotes/1_0_26.md
  Packs/RTIR/pack_metadata.json
Labels: docs-approved, ready-for-pipeline-running

#39824 Caplaybookfix
  Packs/CortexResponseAndRemediation/Playbooks/silent-playbook-Suspicious_Conditional_Access_operation_for_an_identity.yml
  Packs/CortexResponseAndRemediation/ReleaseNotes/1_1_44.md
  Packs/CortexResponseAndRemediation/pack_metadata.json
Labels: docs-approved, ready-for-pipeline-running

#39755 Edit readme file to support Urls with a comma
  Packs/Zscaler/Integrations/Zscaler/README.md
  Packs/Zscaler/Integrations/Zscaler/Zscaler.yml
  Packs/Zscaler/Integrations/Zscaler/Zscaler_test.py
  Packs/Zscaler/ReleaseNotes/1_3_31.md
  Packs/Zscaler/pack_metadata.json
Labels: docs-approved, ready-for-pipeline-running

#39921 XSUP-48818 Backend issue bypass2
  Packs/MicrosoftWindowsEvents/ParsingRules/MicrosoftWindowsEvents/MicrosoftWindowsEvents.xif
  Packs/MicrosoftWindowsEvents/ReleaseNotes/1_1_15.md
  Packs/MicrosoftWindowsEvents/pack_metadata.json
Labels: docs-approved, bypass.url, ready-for-pipeline-running

#39915 CIAC-10832: Deleting duplicate scripts used by contributors
  Utils/download_packs_and_docker_images.py
Labels: docs-approved, ready-for-pipeline-running

#39881 XSUP-49013 Email Communication Fix
  Packs/EmailCommunication/ReleaseNotes/2_0_39.md
  Packs/EmailCommunication/Scripts/DisplayEmailHtml/DisplayEmailHtml.py
  Packs/EmailCommunication/Scripts/DisplayEmailHtml/DisplayEmailHtml.yml
  Packs/EmailCommunication/Scripts/DisplayEmailHtml/DisplayEmailHtml_test.py
  Packs/EmailCommunication/Scripts/PreprocessEmail/PreprocessEmail.py
  Packs/EmailCommunication/Scripts/PreprocessEmail/PreprocessEmail.yml
  Packs/EmailCommunication/Scripts/PreprocessEmail/PreprocessEmail_test.py
  Packs/EmailCommunication/pack_metadata.json
Labels: docs-approved, ready-for-pipeline-running

#39922 XSUP-50532: SlackAsk documentation update
  Packs/Slack/ReleaseNotes/3_5_15.md
  Packs/Slack/Scripts/SlackAskV2/README.md
  Packs/Slack/Scripts/SlackAskV2/SlackAskV2.yml
  Packs/Slack/pack_metadata.json
Labels: docs-approved, ready-for-pipeline-running

#39872 MailListenerV2 update docker image
  Packs/MailListener/Integrations/MailListenerV2/MailListenerV2.yml
  Packs/MailListener/Integrations/MailListenerV2/MailListenerV2_test.py
  Packs/MailListener/ReleaseNotes/1_0_62.md
  Packs/MailListener/pack_metadata.json
Labels: docs-approved, ready-for-pipeline-running

#39737 xdr retrieve data script
  Packs/Core/ReleaseNotes/3_3_0.md
  Packs/Core/Scripts/SearchIndicatorInEvents/README.md
  Packs/Core/Scripts/SearchIndicatorInEvents/SearchIndicatorInEvents.py
  Packs/Core/Scripts/SearchIndicatorInEvents/SearchIndicatorInEvents.yml
  Packs/Core/Scripts/SearchIndicatorInEvents/SearchIndicatorInEvents_test.py
  Packs/Core/pack_metadata.json
Labels: docs-approved, ready-for-pipeline-running

#39850 Get data collection script remove distutils from python 3.12
  Packs/CommonScripts/ReleaseNotes/1_19_57.md
  Packs/CommonScripts/Scripts/GetDataCollectionLink/GetDataCollectionLink.py
  Packs/CommonScripts/Scripts/GetDataCollectionLink/GetDataCollectionLink.yml
  Packs/CommonScripts/Scripts/GetDataCollectionLink/GetDataCollectionLink_test.py
  Packs/CommonScripts/pack_metadata.json
Labels: docs-approved, ready-for-pipeline-running

#39924 XSUP-50590 Azure AKS Fix
  Packs/AzureKubernetesServices/ModelingRules/AzureKubernetesServices/AzureKubernetesServices.xif
  Packs/AzureKubernetesServices/ModelingRules/AzureKubernetesServices/AzureKubernetesServices_schema.json
  Packs/AzureKubernetesServices/ParsingRules/AzureKubernetesServices/AzureKubernetesServices.xif
  Packs/AzureKubernetesServices/ReleaseNotes/1_2_8.md
  Packs/AzureKubernetesServices/pack_metadata.json
  Packs/MicrosoftEntraID/ParsingRules/MicrosoftEntraID/MicrosoftEntraID.xif
  Packs/MicrosoftEntraID/ReleaseNotes/1_0_16.md
  Packs/MicrosoftEntraID/pack_metadata.json
Labels: docs-approved, bypass.url, ready-for-pipeline-running

#39829 Added a check if version is XSIAM for the marketplace url in CoreRestAPI
  Packs/CommonScripts/ReleaseNotes/1_19_58.md
  Packs/CommonScripts/Scripts/ContentPackInstaller/ContentPackInstaller.py
  Packs/CommonScripts/Scripts/ContentPackInstaller/ContentPackInstaller_test.py
  Packs/CommonScripts/Scripts/ContentPackInstaller/README.md
  Packs/CommonScripts/pack_metadata.json
  Packs/DemistoRESTAPI/Integrations/CoreRESTAPI/README.md
Labels: docs-approved, ready-for-pipeline-running

#39910 New Playbook to address the CVE-2025-31324 and a trigger
  Packs/CortexResponseAndRemediation/.pack-ignore
  Packs/CortexResponseAndRemediation/.secrets-ignore
  Packs/CortexResponseAndRemediation/Playbooks/playbook-CVE-2025-31324_-_SAP_NetWeaver_Visual_Composer.yml
  Packs/CortexResponseAndRemediation/Playbooks/playbook-CVE-2025-31324_-_SAP_NetWeaver_Visual_Composer_README.md
  Packs/CortexResponseAndRemediation/ReleaseNotes/1_1_45.md
  Packs/CortexResponseAndRemediation/Triggers/Trigger_-_CVE-2025-31324_-_SAP_NetWeaver_Visual_Composer.json
  Packs/CortexResponseAndRemediation/doc_files/CVE-2025-31324_-_SAP_NetWeaver_Visual_Composer.png
  Packs/CortexResponseAndRemediation/pack_metadata.json
Labels: docs-approved, bypass.url, ready-for-pipeline-running

#39926 MicrosoftTeamsAsk playbook documentation update
  Packs/MicrosoftTeams/ReleaseNotes/1_5_27.md
  Packs/MicrosoftTeams/Scripts/MicrosoftTeamsAsk/MicrosoftTeamsAsk.yml
  Packs/MicrosoftTeams/Scripts/MicrosoftTeamsAsk/README.md
  Packs/MicrosoftTeams/pack_metadata.json
Labels: docs-approved, ready-for-pipeline-running

#39849 Slack remove distutils from python 3.12
  Packs/Slack/Integrations/SlackV3/SlackV3.py
  Packs/Slack/Integrations/SlackV3/SlackV3.yml
  Packs/Slack/Integrations/SlackV3/SlackV3_test.py
  Packs/Slack/ReleaseNotes/3_5_16.md
  Packs/Slack/pack_metadata.json
Labels: docs-approved, ready-for-pipeline-running

#39847 Fix parse html indicators invalid escape error
  Packs/CommonScripts/ReleaseNotes/1_19_59.md
  Packs/CommonScripts/Scripts/ParseHTMLIndicators/ParseHTMLIndicators.py
  Packs/CommonScripts/Scripts/ParseHTMLIndicators/ParseHTMLIndicators.yml
  Packs/CommonScripts/pack_metadata.json
Labels: docs-approved, ready-for-pipeline-running

#39851 STIX parser ignore MyPy errors
  Packs/Base/ReleaseNotes/1_39_26.md
  Packs/Base/Scripts/StixParser/StixParser.py
  Packs/Base/Scripts/StixParser/StixParser.yml
  Packs/Base/pack_metadata.json
Labels: docs-approved, ready-for-pipeline-running

#39923 Update Cado Response pack_metadata.json
  Packs/CadoResponse/pack_metadata.json
Labels: Contribution, docs-approved, Partner, Contribution Form Filled, External PR, Partner-Approved

#39879 Proofpoint Threat Response update modeling rules
  Packs/ProofpointThreatResponse/ModelingRules/ProofpointThreatResponseModelingRules_1_3/ProofpointThreatResponseModelingRules_1_3.xif
  Packs/ProofpointThreatResponse/README.md
  Packs/ProofpointThreatResponse/ReleaseNotes/2_0_26.md
  Packs/ProofpointThreatResponse/pack_metadata.json
Labels: docs-approved, bypass.url, ready-for-pipeline-running

#39842 Azure WAF Enhancement - AGW
  Packs/AzureWAF/.secrets-ignore
  Packs/AzureWAF/ModelingRules/AzureWAF/AzureWAF.xif
  Packs/AzureWAF/ModelingRules/AzureWAF/AzureWAF_schema.json
  Packs/AzureWAF/ParsingRules/AzureWAF/AzureWAF.xif
  Packs/AzureWAF/README.md
  Packs/AzureWAF/ReleaseNotes/1_2_11.md
  Packs/AzureWAF/pack_metadata.json
Labels: docs-approved, bypass.url, ready-for-pipeline-running

#39945 Schedule generic polling update docker image
  Packs/CommonScripts/ReleaseNotes/1_19_60.md
  Packs/CommonScripts/Scripts/ScheduleGenericPolling/ScheduleGenericPolling.py
  Packs/CommonScripts/Scripts/ScheduleGenericPolling/ScheduleGenericPolling.yml
  Packs/CommonScripts/pack_metadata.json
Labels: docs-approved, ready-for-pipeline-running

#39913 Add pagination
  Packs/SekoiaXDR/Integrations/SekoiaXDR/SekoiaXDR.py
  Packs/SekoiaXDR/Integrations/SekoiaXDR/SekoiaXDR.yml
  Packs/SekoiaXDR/Integrations/SekoiaXDR/SekoiaXDR_test.py
  Packs/SekoiaXDR/Integrations/SekoiaXDR/test_data/SekoiaXDR_get_alerts_first_offset_call.json
  Packs/SekoiaXDR/Integrations/SekoiaXDR/test_data/SekoiaXDR_get_alerts_same_time.json
  Packs/SekoiaXDR/Integrations/SekoiaXDR/test_data/SekoiaXDR_get_alerts_second_offset_call.json
  Packs/SekoiaXDR/ReleaseNotes/1_1_3.md
  Packs/SekoiaXDR/Scripts/SekoiaXDRAddComment/SekoiaXDRAddComment.yml
  Packs/SekoiaXDR/Scripts/SekoiaXDRChangeStatus/SekoiaXDRChangeStatus.yml
  Packs/SekoiaXDR/Scripts/SekoiaXDRCloseAlert/SekoiaXDRCloseAlert.yml
  Packs/SekoiaXDR/Scripts/SekoiaXDRPrintAssets/SekoiaXDRPrintAssets.yml
  Packs/SekoiaXDR/Scripts/SekoiaXDRPrintCase/SekoiaXDRPrintCase.yml
  Packs/SekoiaXDR/Scripts/SekoiaXDRPrintComments/SekoiaXDRPrintComments.yml
  Packs/SekoiaXDR/pack_metadata.json
Labels: Contribution, docs-approved, Partner, Contribution Form Filled, Partner Support Level, External PR, Partner-Approved

#39951 Bump-rn-for-cortex-reponse-and-remediation
  Packs/CortexResponseAndRemediation/Playbooks/playbook-CVE-2025-31324_-_SAP_NetWeaver_Visual_Composer.yml
  Packs/CortexResponseAndRemediation/ReleaseNotes/1_1_46.md
  Packs/CortexResponseAndRemediation/pack_metadata.json
Labels: docs-approved, bypass.url, ready-for-pipeline-running

#39947 Update content_roles.json
  .github/content_roles.json
Labels: docs-approved, ready-for-pipeline-running

#39852 Extract html tables script ignore MyPy errors
  Packs/CommonScripts/ReleaseNotes/1_19_61.md
  Packs/CommonScripts/Scripts/ExtractHTMLTables/ExtractHTMLTables.py
  Packs/CommonScripts/Scripts/ExtractHTMLTables/ExtractHTMLTables.yml
  Packs/CommonScripts/pack_metadata.json
Labels: docs-approved, ready-for-pipeline-running

#39901 Add Quick Action Remote Data Preview to Jira
  Packs/Jira/.pack-ignore
  Packs/Jira/Integrations/JiraV3/JiraV3.py
  Packs/Jira/Integrations/JiraV3/JiraV3.yml
  Packs/Jira/Integrations/JiraV3/JiraV3_test.py
  Packs/Jira/Integrations/JiraV3/test_data/get_remote_data_preview/raw_response.json
  Packs/Jira/ReleaseNotes/3_2_21.md
  Packs/Jira/pack_metadata.json
Labels: docs-approved, ready-for-pipeline-running

#39854 GenericSQL update docker image
  Packs/GenericSQL/Integrations/GenericSQL/GenericSQL.yml
  Packs/GenericSQL/Integrations/GenericSQL/GenericSQL_test.py
  Packs/GenericSQL/ReleaseNotes/1_3_10.md
  Packs/GenericSQL/pack_metadata.json
Labels: docs-approved, ForceMerge, ready-for-pipeline-running

#39817 Unsigned and unpopular process performed an injection - Fixing missing Unique transformer
  Packs/CortexResponseAndRemediation/Playbooks/playbook-Unsigned_and_unpopular_process_performed_an_injection.yml
  Packs/CortexResponseAndRemediation/Playbooks/silent-playbook-Unsigned_and_unpopular_process_performed_an_injection_Test.yml
  Packs/CortexResponseAndRemediation/ReleaseNotes/1_1_47.md
  Packs/CortexResponseAndRemediation/pack_metadata.json
Labels: docs-approved, ready-for-pipeline-running

#39861 Add mirroring type to quick action arguments
  Packs/Jira/Integrations/JiraV3/JiraV3.yml
  Packs/Jira/ReleaseNotes/3_2_21.md
Labels: docs-approved, ready-for-pipeline-running

#39593 Elasticsearch_v2 - Allow raw_query to handle all Query DSL parameters and options
  Packs/Elasticsearch/Integrations/Elasticsearch_v2/Elasticsearch_v2.py
  Packs/Elasticsearch/Integrations/Elasticsearch_v2/Elasticsearch_v2.yml
  Packs/Elasticsearch/Integrations/Elasticsearch_v2/Elasticsearch_v2_test.py
  Packs/Elasticsearch/ReleaseNotes/1_3_32.md
  Packs/Elasticsearch/pack_metadata.json
Labels: Contribution, docs-approved, pending-demo, Contribution Form Filled, Community, pending-contributor, Xsoar Support Level, External PR, bypass.url

#39838 Add risky user fetching
  Packs/MicrosoftGraphIdentityandAccess/CONTRIBUTORS.json
  Packs/MicrosoftGraphIdentityandAccess/Integrations/MicrosoftGraphIdentityandAccess/MicrosoftGraphIdentityandAccess.py
  Packs/MicrosoftGraphIdentityandAccess/Integrations/MicrosoftGraphIdentityandAccess/MicrosoftGraphIdentityandAccess.yml
  Packs/MicrosoftGraphIdentityandAccess/Integrations/MicrosoftGraphIdentityandAccess/MicrosoftGraphIdentityandAccess_test.py
  Packs/MicrosoftGraphIdentityandAccess/ReleaseNotes/1_2_60.md
  Packs/MicrosoftGraphIdentityandAccess/pack_metadata.json
Labels: Contribution, docs-approved, Contribution Form Filled, Community, Xsoar Support Level, External PR

#39865 Nbensalmon/ciac 13169/collection admin by request
  Packs/AdminByRequest/.pack-ignore
  Packs/AdminByRequest/.secrets-ignore
  Packs/AdminByRequest/Integrations/AdminByRequestEventCollector/AdminByRequestEventCollector.py
  Packs/AdminByRequest/Integrations/AdminByRequestEventCollector/AdminByRequestEventCollector.yml
  Packs/AdminByRequest/Integrations/AdminByRequestEventCollector/AdminByRequestEventCollector_description.md
  Packs/AdminByRequest/Integrations/AdminByRequestEventCollector/AdminByRequestEventCollector_image.png
  Packs/AdminByRequest/Integrations/AdminByRequestEventCollector/AdminByRequestEventCollector_test.py
  Packs/AdminByRequest/Integrations/AdminByRequestEventCollector/README.md
  Packs/AdminByRequest/Integrations/AdminByRequestEventCollector/command_examples.txt
  Packs/AdminByRequest/Integrations/AdminByRequestEventCollector/test_data/auditlogs_response.json
  Packs/AdminByRequest/Integrations/AdminByRequestEventCollector/test_data/events_response.json
  Packs/AdminByRequest/Integrations/AdminByRequestEventCollector/test_data/requests_response.json
  Packs/AdminByRequest/README.md
  Packs/AdminByRequest/pack_metadata.json
Labels: docs-approved, ready-for-pipeline-running

#39925 Fix-suspicious-ldap-query-playbook
  Packs/CortexResponseAndRemediation/Playbooks/playbook-Suspicious_LDAP_search_query.yml
  Packs/CortexResponseAndRemediation/Playbooks/silent-playbook-Suspicious_LDAP_search_query_Test.yml
  Packs/CortexResponseAndRemediation/ReleaseNotes/1_1_48.md
  Packs/CortexResponseAndRemediation/doc_files/Suspicious_LDAP_search_query.png
  Packs/CortexResponseAndRemediation/pack_metadata.json
Labels: docs-approved, ready-for-pipeline-running

#39888 [GetIncidentsApiModule] add datetime import
  Packs/ApiModules/Scripts/GetIncidentsApiModule/GetIncidentsApiModule.py
  Packs/Base/ReleaseNotes/1_39_27.md
  Packs/Base/pack_metadata.json
  Packs/Campaign/ReleaseNotes/3_4_20.md
  Packs/Campaign/pack_metadata.json
  Packs/Troubleshoot/ReleaseNotes/2_1_11.md
  Packs/Troubleshoot/pack_metadata.json
Labels: docs-approved, ready-for-pipeline-running

#39826 Jira add MirrorObject to jira-create-ticket
  Packs/Jira/Integrations/JiraV3/JiraV3.py
  Packs/Jira/Integrations/JiraV3/JiraV3_test.py
  Packs/Jira/ReleaseNotes/3_2_21.md
Labels: docs-approved, ready-for-pipeline-running

#39794 Confluence PDF Download
  Packs/Confluence/Integrations/Confluence/Confluence.py
  Packs/Confluence/Integrations/Confluence/Confluence.yml
  Packs/Confluence/Integrations/Confluence/Confluence_description.md
  Packs/Confluence/Integrations/Confluence/README.md
  Packs/Confluence/Integrations/Confluence/command_examples.txt
  Packs/Confluence/ReleaseNotes/1_0_24.md
  Packs/Confluence/pack_metadata.json
Labels: Contribution, docs-approved, Contribution Form Filled, Community, Xsoar Support Level, External PR

#39944 Fixed an issue where non-empty data was returned for an empty value on FirstArrayElement and LastArrayElement.
  Packs/FiltersAndTransformers/ReleaseNotes/1_2_94.md
  Packs/FiltersAndTransformers/Scripts/FirstArrayElement/FirstArrayElement.js
  Packs/FiltersAndTransformers/Scripts/LastArrayElement/LastArrayElement.js
  Packs/FiltersAndTransformers/pack_metadata.json
Labels: Contribution, docs-approved, Contribution Form Filled, Community, Xsoar Support Level, External PR

#39955 Fix-cve-2025-31324-pb-and-md
  Packs/CortexResponseAndRemediation/Playbooks/playbook-CVE-2025-31324_-_SAP_NetWeaver_Visual_Composer.yml
  Packs/CortexResponseAndRemediation/Playbooks/playbook-CVE-2025-31324_-_SAP_NetWeaver_Visual_Composer_README.md
  Packs/CortexResponseAndRemediation/ReleaseNotes/1_1_49.md
  Packs/CortexResponseAndRemediation/doc_files/CVE-2025-31324_-_SAP_NetWeaver_Visual_Composer.png
  Packs/CortexResponseAndRemediation/pack_metadata.json
Labels: docs-approved, ready-for-pipeline-running

#39739 Nbensalmon/ciac 13300/http feed api module add param convert cidr ip
  Packs/ApiModules/Scripts/HTTPFeedApiModule/HTTPFeedApiModule.py
  Packs/ApiModules/Scripts/HTTPFeedApiModule/HTTPFeedApiModule_test.py
  Packs/FeedBlocklist_de/Integrations/FeedBlocklist_de/FeedBlocklist_de.yml
  Packs/FeedBlocklist_de/ReleaseNotes/1_1_36.md
  Packs/FeedBlocklist_de/pack_metadata.json
  Packs/FeedBruteForceBlocker/Integrations/FeedBruteForceBlocker/FeedBruteForceBlocker.yml
  Packs/FeedBruteForceBlocker/ReleaseNotes/1_1_34.md
  Packs/FeedBruteForceBlocker/pack_metadata.json
  Packs/FeedCloudflare/Integrations/FeedCloudflare/FeedCloudflare.yml
  Packs/FeedCloudflare/ReleaseNotes/1_1_34.md
  Packs/FeedCloudflare/pack_metadata.json
  Packs/FeedDShield/Integrations/FeedDShield/FeedDShield.yml
  Packs/FeedDShield/ReleaseNotes/1_1_39.md
  Packs/FeedDShield/pack_metadata.json
  Packs/FeedFeodoTracker/Integrations/FeedFeodoTrackerIPBlocklist/FeedFeodoTrackerIPBlocklist.yml
  Packs/FeedFeodoTracker/ReleaseNotes/1_1_36.md
  Packs/FeedFeodoTracker/TestPlaybooks/playbook-feodotrackeripblock_test.yml
  Packs/FeedFeodoTracker/pack_metadata.json
  Packs/FeedMalwareDomainList/Integrations/FeedMalwareDomainList/FeedMalwareDomainList.yml
  Packs/FeedMalwareDomainList/ReleaseNotes/1_1_14.md
  Packs/FeedMalwareDomainList/pack_metadata.json
  Packs/FeedPlainText/Integrations/FeedPlainText/FeedPlainText.yml
  Packs/FeedPlainText/ReleaseNotes/1_1_35.md
  Packs/FeedPlainText/pack_metadata.json
  Packs/FeedSpamhaus/Integrations/FeedSpamhaus/FeedSpamhaus.yml
  Packs/FeedSpamhaus/ReleaseNotes/1_1_33.md
  Packs/FeedSpamhaus/pack_metadata.json
Labels: docs-approved, ready-for-pipeline-running

#39113 [Code42 Event Collector] Use "event.inserted" instead of "timestamp" for file events
  Packs/Code42/Integrations/Code42EventCollector/Code42EventCollector.py
  Packs/Code42/Integrations/Code42EventCollector/Code42EventCollector.yml
  Packs/Code42/Integrations/Code42EventCollector/Code42EventCollector_test.py
  Packs/Code42/ReleaseNotes/6_0_5.md
  Packs/Code42/pack_metadata.json
Labels: docs-approved, ready-for-pipeline-running

#39970 Parse email 0.1.37
  Packs/CommonScripts/ReleaseNotes/1_19_62.md
  Packs/CommonScripts/Scripts/ParseEmailFilesV2/ParseEmailFilesV2.yml
  Packs/CommonScripts/pack_metadata.json
Labels: docs-approved, ready-for-pipeline-running

#39974 CRTX-173814-microsoft-grapth-security
  Packs/MicrosoftGraphSecurity/ModelingRules/MicrosoftGraphSecurity/MicrosoftGraphSecurity.xif
  Packs/MicrosoftGraphSecurity/ReleaseNotes/2_2_28.md
  Packs/MicrosoftGraphSecurity/pack_metadata.json
Labels: docs-approved, bypass.url, ready-for-pipeline-running

#39969 Update on-call personal
  .github/content_roles.json
Labels: docs-approved, ready-for-pipeline-running

#39957 Increase MT for a few TPB
  Tests/conf.json
Labels: docs-approved, ready-for-pipeline-running

#39903 added limit param to list vms
  Packs/AzureCompute/Integrations/AzureCompute_v2/AzureCompute_v2.py
  Packs/AzureCompute/Integrations/AzureCompute_v2/AzureCompute_v2.yml
  Packs/AzureCompute/Integrations/AzureCompute_v2/AzureCompute_v2_test.py
  Packs/AzureCompute/Integrations/AzureCompute_v2/test_data/list_vms_command_with_pagination.json
  Packs/AzureCompute/ReleaseNotes/1_2_35.md
  Packs/AzureCompute/pack_metadata.json
Labels: docs-approved, ready-for-pipeline-running

#39976 Build EWS query update docker image
  Packs/MicrosoftExchangeOnPremise/ReleaseNotes/2_2_4.md
  Packs/MicrosoftExchangeOnPremise/Scripts/BuildEWSQuery/BuildEWSQuery.py
  Packs/MicrosoftExchangeOnPremise/Scripts/BuildEWSQuery/BuildEWSQuery.yml
  Packs/MicrosoftExchangeOnPremise/pack_metadata.json
Labels: docs-approved, ready-for-pipeline-running

#39876 fix absolute pagination issue
  Packs/Absolute/.secrets-ignore
  Packs/Absolute/Integrations/Absolute/Absolute.py
  Packs/Absolute/Integrations/Absolute/Absolute.yml
  Packs/Absolute/Integrations/Absolute/Absolute_test.py
  Packs/Absolute/Integrations/Absolute/README.md
  Packs/Absolute/ReleaseNotes/2_0_3.md
  Packs/Absolute/pack_metadata.json
Labels: docs-approved, ready-for-pipeline-running

#39364 RadwareCloudDDoSProtectionServices
  Packs/RadwareCloudDDoSProtectionServices/.pack-ignore
  Packs/RadwareCloudDDoSProtectionServices/.secrets-ignore
  Packs/RadwareCloudDDoSProtectionServices/Integrations/RadwareCloudDDoSProtectionServices/README.md
  Packs/RadwareCloudDDoSProtectionServices/Integrations/RadwareCloudDDoSProtectionServices/RadwareCloudDDoSProtectionServices.py
  Packs/RadwareCloudDDoSProtectionServices/Integrations/RadwareCloudDDoSProtectionServices/RadwareCloudDDoSProtectionServices.yml
  Packs/RadwareCloudDDoSProtectionServices/Integrations/RadwareCloudDDoSProtectionServices/RadwareCloudDDoSProtectionServices_description.md
  Packs/RadwareCloudDDoSProtectionServices/Integrations/RadwareCloudDDoSProtectionServices/RadwareCloudDDoSProtectionServices_image.png
  Packs/RadwareCloudDDoSProtectionServices/Integrations/RadwareCloudDDoSProtectionServices/RadwareCloudDDoSProtectionServices_test.py
  Packs/RadwareCloudDDoSProtectionServices/README.md
  Packs/RadwareCloudDDoSProtectionServices/pack_metadata.json
Labels: docs-approved, ready-for-pipeline-running

#39542 CIAC-12228 - Add Support for JWT and API Key Authentication in ServiceNow v2 Integration
  Packs/ApiModules/Scripts/ServiceNowApiModule/ServiceNowApiModule.py
  Packs/ApiModules/Scripts/ServiceNowApiModule/ServiceNowApiModule.yml
  Packs/ServiceNow/Integrations/ServiceNowv2/README.md
  Packs/ServiceNow/Integrations/ServiceNowv2/ServiceNowv2.py
  Packs/ServiceNow/Integrations/ServiceNowv2/ServiceNowv2.yml
  Packs/ServiceNow/Integrations/ServiceNowv2/ServiceNowv2_description.md
  Packs/ServiceNow/Integrations/ServiceNowv2/ServiceNowv2_test.py
  Packs/ServiceNow/Integrations/ServiceNowv2/test_data/response_constants.py
  Packs/ServiceNow/ReleaseNotes/2_7_15.md
  Packs/ServiceNow/pack_metadata.json
Labels: docs-approved, ready-for-pipeline-running

#39981 CRTX-158630-gcp_flow_logs_keywords
  Packs/GoogleCloudLogging/pack_metadata.json
Labels: docs-approved, bypass.url, ready-for-pipeline-running

#39897 XSUP-50451/azure-sentinel-list-incidents
  Packs/AzureSentinel/Integrations/AzureSentinel/AzureSentinel.py
  Packs/AzureSentinel/Integrations/AzureSentinel/AzureSentinel.yml
  Packs/AzureSentinel/Integrations/AzureSentinel/AzureSentinel_test.py
  Packs/AzureSentinel/ReleaseNotes/1_5_62.md
  Packs/AzureSentinel/pack_metadata.json
Labels: docs-approved, ready-for-pipeline-running

#39979 Slack v3 py3.12 syntax error
  Packs/Slack/Integrations/SlackV3/SlackV3.py
  Packs/Slack/ReleaseNotes/3_5_17.md
  Packs/Slack/pack_metadata.json
Labels: docs-approved, ready-for-pipeline-running

#39985 Test Playbook - Cortex XDR - Endpoint Investigation increase MT
  Tests/conf.json
Labels: docs-approved, ready-for-pipeline-running

#39964 Xsup 50462 carbon black
  Packs/CarbonBlackEnterpriseEDR/Integrations/CarbonBlackEnterpriseEDR/CarbonBlackEnterpriseEDR.py
  Packs/CarbonBlackEnterpriseEDR/Integrations/CarbonBlackEnterpriseEDR/CarbonBlackEnterpriseEDR.yml
  Packs/CarbonBlackEnterpriseEDR/Integrations/CarbonBlackEnterpriseEDR/CarbonBlackEnterpriseEDR_test.py
  Packs/CarbonBlackEnterpriseEDR/ReleaseNotes/1_1_42.md
  Packs/CarbonBlackEnterpriseEDR/pack_metadata.json
Labels: docs-approved, ready-for-pipeline-running

#39994 Documentation improvements for appendContext function in CSP
  Packs/Base/ReleaseNotes/1_39_28.md
  Packs/Base/Scripts/CommonServerPython/CommonServerPython.py
  Packs/Base/pack_metadata.json
Labels: docs-approved, ready-for-pipeline-running

#39911 Add headers for xql
  Packs/ApiModules/Scripts/CoreXQLApiModule/CoreXQLApiModule.py
  Packs/ApiModules/Scripts/CoreXQLApiModule/CoreXQLApiModule_test.py
  Packs/ApiModules/Scripts/CoreXQLApiModule/test_data/ctx_output.json
  Packs/Core/Integrations/CortexCoreXQLQueryEngine/CortexCoreXQLQueryEngine.yml
  Packs/Core/Integrations/CortexCoreXQLQueryEngine/test_data/ctx_output.json
  Packs/Core/ReleaseNotes/3_3_2.md
  Packs/Core/pack_metadata.json
  Packs/CortexXDR/Integrations/XQLQueryingEngine/XQLQueryingEngine.yml
  Packs/CortexXDR/ReleaseNotes/6_2_22.md
  Packs/CortexXDR/pack_metadata.json
  Packs/DemistoRESTAPI/Integrations/CoreRESTAPI/CoreRESTAPI.js
  Packs/DemistoRESTAPI/ReleaseNotes/1_3_72.md
  Packs/DemistoRESTAPI/pack_metadata.json
Labels: docs-approved, ready-for-pipeline-running

#39999 [set_last_mirror_run] Fix issue with the log
  Packs/Base/ReleaseNotes/1_39_29.md
  Packs/Base/Scripts/CommonServerPython/CommonServerPython.py
  Packs/Base/pack_metadata.json
Labels: docs-approved, ready-for-pipeline-running

#39769 Fix race condition in rasterize integration's tab event handling for improved stability
  Packs/rasterize/Integrations/rasterize/rasterize.py
  Packs/rasterize/Integrations/rasterize/rasterize.yml
  Packs/rasterize/Integrations/rasterize/rasterize_test.py
  Packs/rasterize/ReleaseNotes/2_1_5.md
  Packs/rasterize/pack_metadata.json
Labels: docs-approved, ready-for-pipeline-running

#39939 [EWSv2 & EWS O365] Added handle_inline_image Argument to "reply-mail" Command
  Packs/ApiModules/Scripts/EWSApiModule/EWSApiModule.py
  Packs/ApiModules/Scripts/EWSApiModule/EWSApiModule_test.py
  Packs/MicrosoftExchangeOnPremise/Integrations/EWSv2/EWSv2.py
  Packs/MicrosoftExchangeOnPremise/Integrations/EWSv2/EWSv2.yml
  Packs/MicrosoftExchangeOnPremise/Integrations/EWSv2/README.md
  Packs/MicrosoftExchangeOnPremise/ReleaseNotes/2_2_5.md
  Packs/MicrosoftExchangeOnPremise/pack_metadata.json
  Packs/MicrosoftExchangeOnline/Integrations/EWSO365/EWSO365.py
  Packs/MicrosoftExchangeOnline/Integrations/EWSO365/EWSO365.yml
  Packs/MicrosoftExchangeOnline/Integrations/EWSO365/EWSO365_test.py
  Packs/MicrosoftExchangeOnline/Integrations/EWSO365/README.md
  Packs/MicrosoftExchangeOnline/ReleaseNotes/1_6_7.md
  Packs/MicrosoftExchangeOnline/pack_metadata.json
Labels: docs-approved, ready-for-pipeline-running

#40006 Fix for office shctask playbook
  Packs/CortexResponseAndRemediation/Playbooks/playbook-Office_process_creates_a_scheduled_task_via_file_access.yml
  Packs/CortexResponseAndRemediation/Playbooks/silent-playbook-Office_process_creates_a_scheduled_task_via_file_access_Test.yml
  Packs/CortexResponseAndRemediation/ReleaseNotes/1_1_52.md
  Packs/CortexResponseAndRemediation/pack_metadata.json
Labels: docs-approved, ready-for-pipeline-running

#39986 Update GetValuesOfMultipleFields README.md
  Packs/FiltersAndTransformers/ReleaseNotes/1_2_95.md
  Packs/FiltersAndTransformers/Scripts/GetValuesOfMultipleFIelds/GetValuesOfMultipleFIelds.yml
  Packs/FiltersAndTransformers/Scripts/GetValuesOfMultipleFIelds/README.md
  Packs/FiltersAndTransformers/pack_metadata.json
Labels: docs-approved, ready-for-pipeline-running

#39627 CIAC-12314: Add Array Support to Rasterize
  Packs/rasterize/.secrets-ignore
  Packs/rasterize/Integrations/rasterize/README.md
  Packs/rasterize/Integrations/rasterize/rasterize.py
  Packs/rasterize/ReleaseNotes/2_1_6.md
  Packs/rasterize/pack_metadata.json
Labels: docs-approved, ready-for-pipeline-running

#39995 Silent_Script_file_added_to_startup_related_Registry_keys
  Packs/CortexResponseAndRemediation/Playbooks/silent-playbook-Script_file_added_to_startup-related_Registry_keys.yml
  Packs/CortexResponseAndRemediation/ReleaseNotes/1_1_53.md
  Packs/CortexResponseAndRemediation/Triggers/silent-Trigger_-_Script_file_added_to_startup-related_Registry_keys.json
  Packs/CortexResponseAndRemediation/doc_files/Script_file_added_to_startup-related_Registry_keys.png
  Packs/CortexResponseAndRemediation/pack_metadata.json
Labels: docs-approved, ready-for-pipeline-running

#39991 Return the code / CIAC-12721
  .github/CODEOWNERS
  Packs/ApiModules/Scripts/GSuiteApiModule/GSuiteApiModule.py
  Packs/Base/ReleaseNotes/1_39_30.md
  Packs/Base/Scripts/CommonServerPython/CommonServerPython.py
  Packs/Base/Scripts/CommonServerPython/CommonServerPython_test.py
  Packs/Base/pack_metadata.json
  Packs/GSuiteAdmin/ReleaseNotes/1_2_10.md
  Packs/GSuiteAdmin/TestPlaybooks/playbook-GSuiteAdmin-MobileDevices-Test.yml
  Packs/GSuiteAdmin/pack_metadata.json
  Packs/GSuiteSecurityAlertCenter/ReleaseNotes/1_1_51.md
  Packs/GSuiteSecurityAlertCenter/pack_metadata.json
  Packs/GoogleCalendar/ReleaseNotes/1_1_53.md
  Packs/GoogleCalendar/pack_metadata.json
  Packs/GoogleCloudLogging/ReleaseNotes/1_0_22.md
  Packs/GoogleCloudLogging/pack_metadata.json
  Packs/GoogleDrive/ReleaseNotes/1_3_16.md
  Packs/GoogleDrive/pack_metadata.json
  Packs/GsuiteAuditor/ReleaseNotes/1_0_30.md
  Packs/GsuiteAuditor/pack_metadata.json
Labels: docs-approved, sync-gsm, ready-for-pipeline-running

#39664 Improve logs and timeout handling in Qualys VMDR
  Packs/qualys/Integrations/Qualysv2/Qualysv2.py
  Packs/qualys/Integrations/Qualysv2/Qualysv2.yml
  Packs/qualys/Integrations/Qualysv2/Qualysv2_test.py
  Packs/qualys/ReleaseNotes/3_2_8.md
  Packs/qualys/pack_metadata.json
Labels: bug, docs-approved, python, ready-for-pipeline-running

#39917 SNOW add get-remote-data-preview command
  Packs/ServiceNow/.pack-ignore
  Packs/ServiceNow/Integrations/ServiceNowv2/ServiceNowv2.py
  Packs/ServiceNow/Integrations/ServiceNowv2/ServiceNowv2.yml
  Packs/ServiceNow/Integrations/ServiceNowv2/ServiceNowv2_test.py
  Packs/ServiceNow/ReleaseNotes/2_7_15.md
  Packs/ServiceNow/pack_metadata.json
Labels: docs-approved, ready-for-pipeline-running

#40009 Ciac 13561 refactoring crowd strike falcon integration
  Packs/CrowdStrikeFalcon/Integrations/CrowdStrikeFalcon/CrowdStrikeFalcon.py
  Packs/CrowdStrikeFalcon/Integrations/CrowdStrikeFalcon/CrowdStrikeFalcon_test.py
  Packs/CrowdStrikeFalcon/ReleaseNotes/2_1_22.md
  Packs/CrowdStrikeFalcon/pack_metadata.json
Labels: docs-approved, ready-for-pipeline-running

#40002 Edl add reduce logs
  Packs/EDL/Integrations/EDL/EDL.py
  Packs/EDL/Integrations/EDL/EDL.yml
  Packs/EDL/Integrations/EDL/EDL_test.py
  Packs/EDL/ReleaseNotes/3_3_13.md
  Packs/EDL/pack_metadata.json
Labels: docs-approved, ready-for-pipeline-running

#39942 Add ruff rules to Content nightly flow
  .github/github_workflow_scripts/autobump_rn.py
  .github/github_workflow_scripts/github_workflow_scripts_tests/autobump_rn_test.py
  .github/github_workflow_scripts/github_workflow_scripts_tests/check_if_partner_approved_label_test.py
  .github/github_workflow_scripts/github_workflow_scripts_tests/handle_external_pr_test.py
  .github/github_workflow_scripts/github_workflow_scripts_tests/link_pr_to_jira_issue_test.py
  .github/github_workflow_scripts/purge_branch_protection_rules_test.py
  .github/github_workflow_scripts/request_contributor_review.py
  .github/github_workflow_scripts/run_secrets_detection.py
  .github/github_workflow_scripts/run_secrets_detection_get_playbook_status.py
  .github/github_workflow_scripts/send_slack_message.py
  .github/github_workflow_scripts/sync_contrib_base.py
  .github/github_workflow_scripts/utils.py
  .github/github_workflow_scripts/utils_test.py
  Documentation/extract_common_server_js.py
  Packs/AbnormalSecurity/Integrations/AbnormalSecurity/test_data/mock_paginated_response.py
  Packs/ApiModules/ReleaseNotes/2_2_46.md
  Packs/ApiModules/Scripts/AnsibleApiModule/AnsibleApiModule.py
  Packs/ApiModules/Scripts/CoreIRApiModule/CoreIRApiModule.py
  Packs/ApiModules/Scripts/CoreXQLApiModule/CoreXQLApiModule.py
  Packs/ApiModules/Scripts/GSuiteApiModule/GSuiteApiModule.py
  Packs/ApiModules/Scripts/HTTPFeedApiModule/HTTPFeedApiModule.py
  Packs/ApiModules/Scripts/SiemApiModule/SiemApiModule.py
  Packs/ApiModules/Scripts/TAXII2ApiModule/TAXII2ApiModule.py
  Packs/ApiModules/pack_metadata.json
  Packs/CommonScripts/Scripts/GenerateAsBuiltConfiguration/test_data/execute_command.py
  Packs/Core/Integrations/CortexCoreIR/CortexCoreIR.py
  Packs/Core/Integrations/CortexCoreIR/CortexCoreIR_test.py
  Packs/Core/ReleaseNotes/3_3_3.md
  Packs/Core/pack_metadata.json
  Packs/DSPM/ReleaseNotes/1_0_5.md
  Packs/DSPM/Scripts/DSPMIncidentList/DSPMIncidentList.py
  Packs/DSPM/Scripts/DSPMRerunIncidents/DSPMRerunIncidents.py
  Packs/DSPM/pack_metadata.json
  Packs/Doppel/Integrations/Doppel/Doppel.py
  Packs/Doppel/Integrations/Doppel/Doppel_test.py
  Packs/Doppel/ReleaseNotes/1_0_1.md
  Packs/Doppel/pack_metadata.json
  Packs/DuoAuth/Integrations/DuoAuth/DuoAuth.py
  Packs/DuoAuth/ReleaseNotes/1_0_1.md
  Packs/DuoAuth/pack_metadata.json
  Packs/EmailCommunication/Scripts/DisplayEmailHtml/DisplayEmailHtml_test.py
  Packs/EmailCommunication/Scripts/PreprocessEmail/PreprocessEmail_test.py
  Packs/FeedTAXII/Integrations/FeedTAXII2/FeedTAXII2_test.py
  Packs/Reco/Integrations/Reco/test_data/structs.py
  Templates/Integrations/AnalyticsAndSIEM/AnalyticsAndSIEM.py
  Templates/Integrations/AnalyticsAndSIEM/AnalyticsAndSIEM_test.py
  Templates/Integrations/Authentication/Authentication.py
  Templates/Integrations/Authentication/Authentication_test.py
  Templates/Integrations/CaseManagement/CaseManagement.py
  Templates/Integrations/CaseManagement/CaseManagement_test.py
  Templates/Integrations/DataEnrichmentThreatIntelligence/DataEnrichmentThreatIntelligence.py
  Templates/Integrations/DataEnrichmentThreatIntelligence/DataEnrichmentThreatIntelligence_test.py
  Templates/Integrations/Database/Database.py
  Templates/Integrations/Database/Database_test.py
  Tests/demistomock/demistomock.py
  Tests/scripts/dev_envs/pytest/conftest.py
  Tests/scripts/script_runner.py
  contribution/utils/download_packs_and_docker_images.py
  nightly_ruff.toml
  pyproject.toml
Labels: docs-approved, ForceMerge, ready-for-pipeline-running

#38862 Flashpoint ignite - is_time_sensitive() related changes
  Packs/Flashpoint/Integrations/Ignite/Ignite.py
  Packs/Flashpoint/Integrations/Ignite/Ignite.yml
  Packs/Flashpoint/ReleaseNotes/2_0_6.md
  Packs/Flashpoint/pack_metadata.json
Labels: docs-approved, ForceMerge, ready-for-pipeline-running

#40035 Increase MT CrowdStrike_FalconX_Test
  Tests/conf.json
Labels: docs-approved, ready-for-pipeline-running

#38360 CSP - Added the "LOG" prefix to the censor function
  Packs/Base/ReleaseNotes/1_39_31.md
  Packs/Base/Scripts/CommonServerPython/CommonServerPython.py
  Packs/Base/Scripts/CommonServerPython/CommonServerPython_test.py
  Packs/Base/pack_metadata.json
Labels: docs-approved, ready-for-pipeline-running

#40034 Adding specific supported modules.
  Packs/CybleEventsV2/Integrations/CybleEventsV2/CybleEventsV2.yml
  Packs/CybleEventsV2/ReleaseNotes/1_0_9.md
  Packs/CybleEventsV2/pack_metadata.json
  Packs/Jira/Integrations/JiraV2/JiraV2.yml
  Packs/Jira/ReleaseNotes/3_2_21.md
  Packs/Jira/pack_metadata.json
  Packs/ServiceNow/Integrations/ServiceNow/ServiceNow.yml
  Packs/ServiceNow/ReleaseNotes/2_7_16.md
  Packs/ServiceNow/pack_metadata.json
Labels: docs-approved, ready-for-pipeline-running

#40026 Azure WAF - Updating Modeling Rules
  Packs/AzureWAF/ModelingRules/AzureWAF/AzureWAF.xif
  Packs/AzureWAF/ReleaseNotes/1_2_13.md
  Packs/AzureWAF/pack_metadata.json
Labels: docs-approved, bypass.url, ready-for-pipeline-running

#39983 rename: Radware cloud services
  Packs/RadwareCloudDDoSProtectionServices/Integrations/RadwareCloudDDoSProtectionServices/README.md
  Packs/RadwareCloudServices/README.md
  Packs/RadwareCloudServices/ReleaseNotes/1_0_2.md
  Packs/RadwareCloudServices/pack_metadata.json
Labels: docs-approved, ready-for-pipeline-running

#40044 handle None keys in context
  Packs/ApiModules/Scripts/CoreXQLApiModule/CoreXQLApiModule.py
  Packs/ApiModules/Scripts/CoreXQLApiModule/CoreXQLApiModule_test.py
  Packs/Core/ReleaseNotes/3_3_4.md
  Packs/Core/pack_metadata.json
  Packs/CortexXDR/ReleaseNotes/6_2_23.md
  Packs/CortexXDR/pack_metadata.json
Labels: docs-approved, ready-for-pipeline-running

#40008 bump incydr_python version to 2.3.1
  Packs/Code42/Integrations/Code42/Code42.py
  Packs/Code42/Integrations/Code42/Code42.yml
  Packs/Code42/Integrations/Code42/test_data/session_response.json
  Packs/Code42/Integrations/Code42/test_data/session_response_2.json
  Packs/Code42/Integrations/Code42/test_data/session_response_3.json
  Packs/Code42/ReleaseNotes/6_0_6.md
  Packs/Code42/pack_metadata.json
Labels: Contribution, docs-approved, Partner, Contribution Form Filled, Partner Support Level, External PR, Partner-Approved

#40032 CRTX-162633 - BeyondTrust EPM
  Packs/BeyondTrustEPM/.pack-ignore
  Packs/BeyondTrustEPM/.secrets-ignore
  Packs/BeyondTrustEPM/ModelingRules/BeyondTrustEPM/BeyondTrustEPM.xif
  Packs/BeyondTrustEPM/ModelingRules/BeyondTrustEPM/BeyondTrustEPM.yml
  Packs/BeyondTrustEPM/ModelingRules/BeyondTrustEPM/BeyondTrustEPM_schema.json
  Packs/BeyondTrustEPM/README.md
  Packs/BeyondTrustEPM/pack_metadata.json
Labels: docs-approved, bypass.url, ready-for-pipeline-running

#40047 abnormal extended documentation
  Packs/AbnormalSecurity/Integrations/AbnormalSecurity/README.md
  Packs/AbnormalSecurity/Integrations/AbnormalSecurityEventCollector/README.md
Labels: docs-approved, ready-for-pipeline-running

#40060 Skip mdx-validation
  .pre-commit-config_template.yaml
Labels: ForceMerge, ready-for-pipeline-running

#39844 Add MirrorObject to servicenow-create-ticket command outputs
  Packs/ServiceNow/Integrations/ServiceNowv2/ServiceNowv2.py
  Packs/ServiceNow/Integrations/ServiceNowv2/ServiceNowv2.yml
  Packs/ServiceNow/Integrations/ServiceNowv2/ServiceNowv2_test.py
  Packs/ServiceNow/Integrations/ServiceNowv2/test_data/result_constants.py
  Packs/ServiceNow/ReleaseNotes/2_7_15.md
Labels: docs-approved, ready-for-pipeline-running

#40062 Increase timeout playbook-SearchIncidentsV2InsideGenericPollng-Test
  Tests/conf.json
Labels: docs-approved, ready-for-pipeline-running

#40065 Fix code owners - remove @altmannyarden and @bakatzir
  .github/CODEOWNERS
Labels: docs-approved, ready-for-pipeline-running

#40029 bug - headers are malformed - mail listener
  Packs/MailListener/Integrations/MailListenerV2/MailListenerV2.py
  Packs/MailListener/Integrations/MailListenerV2/MailListenerV2_test.py
  Packs/MailListener/ReleaseNotes/1_0_63.md
  Packs/MailListener/pack_metadata.json
Labels: docs-approved, ready-for-pipeline-running

#40069 Fix BeyondTrustEPM README
  Packs/BeyondTrustEPM/README.md
Labels: docs-approved, ready-for-pipeline-running

#40033 VMWare NSX Mapping
  Packs/VMWareNSX/.pack-ignore
  Packs/VMWareNSX/.secrets-ignore
  Packs/VMWareNSX/ModelingRules/VMWareNSX/VMWareNSX.xif
  Packs/VMWareNSX/ModelingRules/VMWareNSX/VMWareNSX.yml
  Packs/VMWareNSX/ModelingRules/VMWareNSX/VMWareNSX_schema.json
  Packs/VMWareNSX/ParsingRules/VMWareNSX/VMWareNSX.xif
  Packs/VMWareNSX/ParsingRules/VMWareNSX/VMWareNSX.yml
  Packs/VMWareNSX/README.md
  Packs/VMWareNSX/pack_metadata.json
Labels: docs-approved, bypass.url, ready-for-pipeline-running

#39860 [SplunkPy] New param notable_time_source
  Packs/SplunkPy/Integrations/SplunkPy/README.md
  Packs/SplunkPy/Integrations/SplunkPy/SplunkPy.py
  Packs/SplunkPy/Integrations/SplunkPy/SplunkPy.yml
  Packs/SplunkPy/Integrations/SplunkPy/SplunkPy_test.py
  Packs/SplunkPy/ReleaseNotes/3_2_12.md
  Packs/SplunkPy/pack_metadata.json
Labels: docs-approved, ready-for-pipeline-running

#40064 Add merit-maita as code owner
  .github/CODEOWNERS
Labels: docs-approved, ready-for-pipeline-running

#40070 Get detections fix
  Packs/RedCanary/.secrets-ignore
  Packs/RedCanary/Integrations/RedCanary/RedCanary.py
  Packs/RedCanary/Integrations/RedCanary/RedCanary_test.py
  Packs/RedCanary/Integrations/RedCanary/TestData/detection2.json
  Packs/RedCanary/Integrations/RedCanary/TestData/detection_timeline2.json
  Packs/RedCanary/ReleaseNotes/1_1_26.md
  Packs/RedCanary/pack_metadata.json
Labels: docs-approved, ready-for-pipeline-running

#39902 Fixed a proxy issue
  Packs/SymantecEmailSecurity/Integrations/SymantecEmailSecurity/SymantecEmailSecurity.py
  Packs/SymantecEmailSecurity/Integrations/SymantecEmailSecurity/SymantecEmailSecurity.yml
  Packs/SymantecEmailSecurity/Integrations/SymantecEmailSecurity/SymantecEmailSecurity_test.py
  Packs/SymantecEmailSecurity/ReleaseNotes/1_0_3.md
  Packs/SymantecEmailSecurity/pack_metadata.json
Labels: docs-approved, ready-for-pipeline-running

#40071 Fix add support for get data collection link in XSIAM
  Packs/CommonScripts/ReleaseNotes/1_19_64.md
  Packs/CommonScripts/Scripts/GetDataCollectionLink/GetDataCollectionLink.py
  Packs/CommonScripts/Scripts/GetDataCollectionLink/GetDataCollectionLink_test.py
  Packs/CommonScripts/pack_metadata.json
Labels: docs-approved, ready-for-pipeline-running

#40068 Edited docs for timeout var
  Tests/conf.json
Labels: docs-approved, ready-for-pipeline-running

#40056 [PAN-OS] fix pan-os-edit-address-group
  Packs/PAN-OS/Integrations/Panorama/Panorama.py
  Packs/PAN-OS/Integrations/Panorama/Panorama.yml
  Packs/PAN-OS/Integrations/Panorama/Panorama_test.py
  Packs/PAN-OS/ReleaseNotes/2_3_14.md
  Packs/PAN-OS/pack_metadata.json
Labels: docs-approved, ready-for-pipeline-running

#40076 Documentation improvement
  Packs/Core/Integrations/CortexCoreXQLQueryEngine/README.md
Labels: docs-approved, ready-for-pipeline-running
