Repository demisto/content, pull requests merged in 2025-02, with the labels that each got.

#38415 fixed parsing error in readme
  Packs/AnythingLLM/README.md
Labels: docs-approved

#37904 SplunkPy: update the mirror-in mechanism
  Packs/SplunkPy/Integrations/SplunkPy/SplunkPy.py
  Packs/SplunkPy/Integrations/SplunkPy/SplunkPy.yml
  Packs/SplunkPy/Integrations/SplunkPy/SplunkPy_test.py
  Packs/SplunkPy/ReleaseNotes/3_2_0.md
  Packs/SplunkPy/pack_metadata.json
Labels: docs-approved

#38393 XQLDSHelper : Improved round_time settings
  Packs/XQLDSHelper/ReleaseNotes/1_0_1.md
  Packs/XQLDSHelper/Scripts/XQLDSHelper/README.md
  Packs/XQLDSHelper/Scripts/XQLDSHelper/XQLDSHelper.py
  Packs/XQLDSHelper/Scripts/XQLDSHelper/XQLDSHelper.yml
  Packs/XQLDSHelper/Scripts/XQLDSHelper/XQLDSHelper_test.py
  Packs/XQLDSHelper/Scripts/XQLDSHelper/test_data/test-others.json
  Packs/XQLDSHelper/pack_metadata.json
Labels: Contribution, docs-approved, Contribution Form Filled, Community, Community Support Level, External PR

#38384 Suspicious certutil command line
  Packs/CortexResponseAndRemediation/Playbooks/playbook-Suspicious_certutil_command_line.yml
  Packs/CortexResponseAndRemediation/Playbooks/playbook-Suspicious_certutil_command_line_README.md
  Packs/CortexResponseAndRemediation/ReleaseNotes/1_1_4.md
  Packs/CortexResponseAndRemediation/Triggers/Trigger_-_Suspicious_certutil_command_line.json
  Packs/CortexResponseAndRemediation/doc_files/Suspicious_certutil_command_line.png
  Packs/CortexResponseAndRemediation/pack_metadata.json
Labels: docs-approved

#38437 [validation_config.toml] Remove PB130 and PB131
  validation_config.toml
Labels: docs-approved

#38399 Ciac 11856 ServiceNow script
  Packs/ServiceNow/ReleaseNotes/2_7_6.md
  Packs/ServiceNow/Scripts/ServiceNowTroubleshoot/README.md
  Packs/ServiceNow/Scripts/ServiceNowTroubleshoot/ServiceNowTroubleshoot.py
  Packs/ServiceNow/Scripts/ServiceNowTroubleshoot/ServiceNowTroubleshoot.yml
  Packs/ServiceNow/Scripts/ServiceNowTroubleshoot/ServiceNowTroubleshoot_test.py
  Packs/ServiceNow/Scripts/ServiceNowTroubleshoot/test_data/filtering_instances_data.json
  Packs/ServiceNow/Scripts/ServiceNowTroubleshoot/test_data/incidents_search_http_response.json
  Packs/ServiceNow/Scripts/ServiceNowTroubleshoot/test_data/setting_integration_search_http_response.json
  Packs/ServiceNow/doc_files/ServiceNowTroubleshotScript.png
  Packs/ServiceNow/pack_metadata.json
Labels: docs-approved

#38385 EWSO365 fix send-mail with inline images
  Packs/MicrosoftExchangeOnline/Integrations/EWSO365/EWSO365.py
  Packs/MicrosoftExchangeOnline/ReleaseNotes/1_6_1.md
  Packs/MicrosoftExchangeOnline/pack_metadata.json
Labels: docs-approved

#38129 Use unique userId instead of userName (display name) for ZoomAsk output entry
  Packs/Zoom/Integrations/Zoom/Zoom.py
  Packs/Zoom/Integrations/Zoom/Zoom_test.py
  Packs/Zoom/ReleaseNotes/1_6_23.md
  Packs/Zoom/pack_metadata.json
Labels: Contribution, docs-approved, Contribution Form Filled, Community, pending-contributor, Xsoar Support Level, External PR

#38444 AWS EC2 Docs
  Packs/AWS-EC2/Scripts/AwsEC2SyncAccounts/README.md
  Packs/AWS-Organizations/Integrations/AWSOrganizations/README.md
  Packs/CrowdStrikeFalcon/Integrations/CrowdStrikeFalcon/test_data/input_data.py
  Packs/CrowdStrikeFalcon/Integrations/CrowdStrikeFalcon/test_data/test_list_identity_entities_command.json
Labels: docs-approved

#38124 Add advanced filter to allow fetching of vulnerabilities by host detection QIDs in Qualys VMDR
  Packs/qualys/Integrations/Qualysv2/Qualysv2.py
  Packs/qualys/Integrations/Qualysv2/Qualysv2.yml
  Packs/qualys/Integrations/Qualysv2/Qualysv2_description.md
  Packs/qualys/Integrations/Qualysv2/Qualysv2_test.py
  Packs/qualys/Integrations/Qualysv2/README.md
  Packs/qualys/Integrations/Qualysv2/test_data/fetched_assets.json
  Packs/qualys/Integrations/Qualysv2/test_data/fetched_vulnerabilities.json
  Packs/qualys/ReleaseNotes/3_2_0.md
  Packs/qualys/pack_metadata.json
Labels: enhancement, docs-approved, python

#38407 [VM] Pull Emails from CSP Tags
  Packs/CortexVulnerabilityManagement/Playbooks/Cortex_VM_-_Vulnerability_Issue.yml
  Packs/CortexVulnerabilityManagement/Playbooks/Cortex_VM_-_Vulnerability_Issue_README.md
  Packs/CortexVulnerabilityManagement/ReleaseNotes/1_0_1.md
  Packs/CortexVulnerabilityManagement/doc_files/Cortex_VM_-_ServiceNow_CMDB.png
  Packs/CortexVulnerabilityManagement/doc_files/Cortex_VM_-_Vulnerability_Issue.png
  Packs/CortexVulnerabilityManagement/pack_metadata.json
Labels: Contribution, docs-approved, Contribution Form Filled, Community, Xsoar Support Level, External PR, Security Review, Security Approved

#38453 Remove pack.zip
  pack.zip
Labels: docs-approved

#38388 CRTX-147014-Azure-Logs
  Packs/MicrosoftEntraID/ModelingRules/MicrosoftEntraID/MicrosoftEntraID.xif
  Packs/MicrosoftEntraID/ParsingRules/MicrosoftEntraID/MicrosoftEntraID.xif
  Packs/MicrosoftEntraID/ReleaseNotes/1_0_7.md
  Packs/MicrosoftEntraID/pack_metadata.json
Labels: docs-approved

#38456 update validation config.toml
  validation_config.toml
Labels: docs-approved

#38431 Run Modeling/Parsing Rules YMLs Alignment last chunk
  Packs/Squid/ModelingRules/Squid/Squid.yml
  Packs/Squid/ParsingRules/Squid/Squid.yml
  Packs/Squid/ReleaseNotes/1_0_4.md
  Packs/Squid/pack_metadata.json
  Packs/SymantecBlueCoatProxySG/ModelingRules/SymantecBlueCoatProxySG/SymantecBlueCoatProxySG.yml
  Packs/SymantecBlueCoatProxySG/ParsingRules/SymantecBlueCoatProxySG/SymantecBlueCoatProxySG.yml
  Packs/SymantecBlueCoatProxySG/ReleaseNotes/1_0_4.md
  Packs/SymantecBlueCoatProxySG/pack_metadata.json
  Packs/Tableau/ModelingRules/Tableau/Tableau.yml
  Packs/Tableau/ParsingRules/Tableau/Tableau.yml
  Packs/Tableau/ReleaseNotes/1_0_12.md
  Packs/Tableau/pack_metadata.json
  Packs/TeamViewer/ModelingRules/TeamViewer/TeamViewer.yml
  Packs/TeamViewer/ReleaseNotes/1_0_11.md
  Packs/TeamViewer/pack_metadata.json
  Packs/ThinkstCanary/ModelingRules/ThinkstCanary/ThinkstCanary.yml
  Packs/ThinkstCanary/ReleaseNotes/1_0_24.md
  Packs/ThinkstCanary/pack_metadata.json
  Packs/TrendMicroDeepSecurity/ModelingRules/TrendMicroDeepSecurity/TrendMicroDeepSecurity.yml
  Packs/TrendMicroDeepSecurity/ReleaseNotes/1_1_2.md
  Packs/TrendMicroDeepSecurity/pack_metadata.json
  Packs/TrendMicroTippingPoint/ModelingRules/TrendMicroTippingPoint/TrendMicroTippingPoint.yml
  Packs/TrendMicroTippingPoint/ReleaseNotes/1_0_1.md
  Packs/TrendMicroTippingPoint/pack_metadata.json
  Packs/WithSecure/ModelingRules/WithSecure/WithSecure.yml
  Packs/WithSecure/ReleaseNotes/1_0_6.md
  Packs/WithSecure/pack_metadata.json
  Packs/Zoom/ModelingRules/Zoom/Zoom.yml
  Packs/Zoom/ReleaseNotes/1_6_24.md
  Packs/Zoom/pack_metadata.json
  Packs/ZscalerZPA/ModelingRules/ZscalerZPA/ZscalerZPA.yml
  Packs/ZscalerZPA/ReleaseNotes/1_0_8.md
  Packs/ZscalerZPA/pack_metadata.json
  Packs/jamf/ModelingRules/Jamf/Jamf.yml
  Packs/jamf/ReleaseNotes/2_2_5.md
  Packs/jamf/pack_metadata.json
Labels: docs-approved, ForceMerge, bypass.url

#38449 CIAC-12379_2
  Packs/Zoom/Integrations/Zoom/README.md
  Packs/Zoom/Scripts/ZoomAsk/README.md
Labels: docs-approved, bypass.url

#38467 YML Correction PR
  Packs/Squid/ModelingRules/Squid/Squid.yml
  Packs/Squid/ParsingRules/Squid/Squid.yml
  Packs/Squid/ReleaseNotes/1_0_5.md
  Packs/Squid/pack_metadata.json
Labels: docs-approved, ForceMerge, bypass.url

#38428 Patch multitenant issue + alternative command
  Packs/XSOARFileManagement/Integrations/XSOARFileManagement/README.md
  Packs/XSOARFileManagement/Integrations/XSOARFileManagement/XSOARFileManagement.py
  Packs/XSOARFileManagement/Integrations/XSOARFileManagement/XSOARFileManagement.yml
  Packs/XSOARFileManagement/ReleaseNotes/1_1_4.md
  Packs/XSOARFileManagement/pack_metadata.json
Labels: Contribution, docs-approved, Contribution Form Filled, Community, Community Support Level, External PR

#38471 revert rm108
  validation_config.toml
Labels: docs-approved

#38406 CIAC-11873/XSIAM-PB-Suspicious-execution-from-tmp-folder
  Packs/CortexResponseAndRemediation/Playbooks/playbook-Suspicious_execution_from_tmp_folder.yml
  Packs/CortexResponseAndRemediation/Playbooks/playbook-Suspicious_execution_from_tmp_folder_README.md
  Packs/CortexResponseAndRemediation/ReleaseNotes/1_1_5.md
  Packs/CortexResponseAndRemediation/Triggers/Trigger_-_Suspicious_execution_from_tmp_folder.json
  Packs/CortexResponseAndRemediation/doc_files/Suspicious_execution_from_tmp_folder.png
  Packs/CortexResponseAndRemediation/pack_metadata.json
Labels: docs-approved

#38339 Freshservice: add description fetch
  Packs/FreshworksFreshservice/Integrations/FreshworksFreshservice/FreshworksFreshservice.yml
  Packs/FreshworksFreshservice/Integrations/FreshworksFreshservice/README.md
  Packs/FreshworksFreshservice/ReleaseNotes/1_0_29.md
  Packs/FreshworksFreshservice/pack_metadata.json
Labels: docs-approved

#38422 Nozomi improve app description and README for Vantage
  Packs/NozomiNetworks/Integrations/NozomiNetworks/NozomiNetworks.yml
  Packs/NozomiNetworks/README.md
  Packs/NozomiNetworks/ReleaseNotes/1_0_16.md
  Packs/NozomiNetworks/pack_metadata.json
Labels: Contribution, docs-approved, Partner, Contribution Form Filled, Partner Support Level, External PR, Partner-Approved

#38480 Chronicle Release 4.1.3
  Packs/GoogleChronicleBackstory/Integrations/GoogleChronicleBackstory/GoogleChronicleBackstory.yml
  Packs/GoogleChronicleBackstory/Integrations/GoogleChronicleBackstory/README.md
  Packs/GoogleChronicleBackstory/ReleaseNotes/4_1_3.md
  Packs/GoogleChronicleBackstory/pack_metadata.json
Labels: Contribution, docs-approved, Partner, Contribution Form Filled, Partner Support Level, External PR, Partner-Approved

#38465 Adding a new tag under permitted_notifications
  Packs/Slack/Integrations/SlackV3/SlackV3.yml
  Packs/Slack/ReleaseNotes/3_5_10.md
  Packs/Slack/pack_metadata.json
Labels: docs-approved

#38478 Bugfix/ciac 12810/fix dynamic section script suspicious domain playbook
  Packs/CloudIncidentResponse/Layouts/layoutscontainer-CLOUD_Token_Theft.json
  Packs/CloudIncidentResponse/ReleaseNotes/1_0_23.md
  Packs/CloudIncidentResponse/pack_metadata.json
  Packs/SuspiciousDomainHunting/Layouts/layoutscontainer-Suspicious_Domain_Hunting_Incident_Layout.json
  Packs/SuspiciousDomainHunting/ReleaseNotes/1_0_11.md
  Packs/SuspiciousDomainHunting/Scripts/RasterizeImageOriginal/RasterizeImageOriginal.py
  Packs/SuspiciousDomainHunting/pack_metadata.json
Labels: docs-approved

#38492 XSUP-46487 - Linux Parsing Rule Update
  Packs/LinuxEventsCollection/ParsingRules/LinuxEventsCollectionParsingRules/LinuxEventsCollectionParsingRules.xif
  Packs/LinuxEventsCollection/ReleaseNotes/1_0_15.md
  Packs/LinuxEventsCollection/pack_metadata.json
Labels: docs-approved, bypass.url

#38452 Fixed an issue where cache data could not be set properly.
  Packs/XQLDSHelper/ReleaseNotes/1_0_2.md
  Packs/XQLDSHelper/Scripts/XQLDSHelper/README.md
  Packs/XQLDSHelper/Scripts/XQLDSHelper/XQLDSHelper.py
  Packs/XQLDSHelper/Scripts/XQLDSHelper/XQLDSHelper.yml
  Packs/XQLDSHelper/Scripts/XQLDSHelper/test_data/test-others.json
  Packs/XQLDSHelper/pack_metadata.json
Labels: Contribution, docs-approved, Contribution Form Filled, Community, Community Support Level, External PR

#38509 [EmailsAskUserReponse] Fix arg.suffix
  Packs/CommonScripts/ReleaseNotes/1_19_19.md
  Packs/CommonScripts/Scripts/EmailAskUserResponse/EmailAskUserResponse.js
  Packs/CommonScripts/pack_metadata.json
Labels: docs-approved

#37778 CIAC-11415
  Packs/Absolute/Integrations/Absolute/Absolute.py
  Packs/Absolute/Integrations/Absolute/Absolute.yml
  Packs/Absolute/Integrations/Absolute/Absolute_test.py
  Packs/Absolute/Integrations/Absolute/README.md
  Packs/Absolute/Integrations/Absolute/command_examples.txt
  Packs/Absolute/Integrations/Absolute/test_data/siem_events.json
  Packs/Absolute/Integrations/Absolute/test_data/siem_events_test_fetch_limit.json
  Packs/Absolute/ReleaseNotes/1_0_26.md
  Packs/Absolute/TestPlaybooks/playbook-Absolute.yml
  Packs/Absolute/pack_metadata.json
  Tests/conf.json
Labels: docs-approved, sync-gsm

#38486 Fix 1Password pack Author image
  Packs/OnePassword/Author_image.png
  Packs/OnePassword/README.md
  Packs/OnePassword/ReleaseNotes/1_0_1.md
  Packs/OnePassword/pack_metadata.json
Labels: bug, docs-approved

#38463 Update README.md
  Packs/CortexXDR/Integrations/XDR_iocs/README.md
Labels: Contribution, docs-approved, Contribution Form Filled, Community, Xsoar Support Level, External PR

#38498 Alibaba Cloud Trail Event Collector - Added debug log in case of an error
  Packs/AlibabaActionTrail/Integrations/AlibabaActionTrailEventCollector/AlibabaActionTrailEventCollector.py
  Packs/AlibabaActionTrail/ReleaseNotes/1_1_4.md
  Packs/AlibabaActionTrail/pack_metadata.json
Labels: docs-approved, ForceMerge

#38489 [UVM] Update playbook to use xdmremediationowner normalized field
  Packs/CortexVulnerabilityManagement/Playbooks/Cortex_VM_-_Vulnerability_Issue.yml
  Packs/CortexVulnerabilityManagement/Playbooks/Cortex_VM_-_Vulnerability_Issue_README.md
  Packs/CortexVulnerabilityManagement/ReleaseNotes/1_0_2.md
  Packs/CortexVulnerabilityManagement/doc_files/Cortex_VM_-_Vulnerability_Issue.png
  Packs/CortexVulnerabilityManagement/pack_metadata.json
Labels: Contribution, docs-approved, Contribution Form Filled, Community, Xsoar Support Level, External PR, Security Review

#38320 [EWSv2 & EWS O365] Added support for `handle_inline_image`
  Packs/MicrosoftExchangeOnPremise/Integrations/EWSv2/EWSv2.py
  Packs/MicrosoftExchangeOnPremise/Integrations/EWSv2/EWSv2.yml
  Packs/MicrosoftExchangeOnPremise/Integrations/EWSv2/EWSv2_test.py
  Packs/MicrosoftExchangeOnPremise/Integrations/EWSv2/README.md
  Packs/MicrosoftExchangeOnPremise/ReleaseNotes/2_1_24.md
  Packs/MicrosoftExchangeOnPremise/pack_metadata.json
  Packs/MicrosoftExchangeOnline/Integrations/EWSO365/EWSO365.py
  Packs/MicrosoftExchangeOnline/Integrations/EWSO365/EWSO365.yml
  Packs/MicrosoftExchangeOnline/Integrations/EWSO365/EWSO365_test.py
  Packs/MicrosoftExchangeOnline/Integrations/EWSO365/README.md
  Packs/MicrosoftExchangeOnline/ReleaseNotes/1_6_2.md
  Packs/MicrosoftExchangeOnline/pack_metadata.json
Labels: docs-approved, ForceMerge

#38201 IBM MaaS360 Security - Fixed type error in fetch
  Packs/IBMMaaS360Security/Integrations/IBMMaaS360SecurityEventCollector/IBMMaaS360SecurityEventCollector.py
  Packs/IBMMaaS360Security/Integrations/IBMMaaS360SecurityEventCollector/IBMMaaS360SecurityEventCollector.yml
  Packs/IBMMaaS360Security/ReleaseNotes/1_0_1.md
  Packs/IBMMaaS360Security/pack_metadata.json
Labels: docs-approved

#37871 Improve Digital Guardian ARC Event Collector configuration parameters and documentation
  Packs/DigitalGuardian/Integrations/DigitalGuardianARCEventCollector/DigitalGuardianARCEventCollector.py
  Packs/DigitalGuardian/Integrations/DigitalGuardianARCEventCollector/DigitalGuardianARCEventCollector.yml
  Packs/DigitalGuardian/Integrations/DigitalGuardianARCEventCollector/DigitalGuardianARCEventCollector_description.md
  Packs/DigitalGuardian/Integrations/DigitalGuardianARCEventCollector/DigitalGuardianARCEventCollector_test.py
  Packs/DigitalGuardian/Integrations/DigitalGuardianARCEventCollector/README.md
  Packs/DigitalGuardian/ReleaseNotes/2_0_2.md
  Packs/DigitalGuardian/doc_files/edit_export_profile.png
  Packs/DigitalGuardian/pack_metadata.json
Labels: bug, docs-approved

#38513 Fix mypy error
  Packs/DataBee/Integrations/DataBee/DataBee.py
  Packs/VectraXDR/Integrations/VectraXDR/VectraXDR.py
  Packs/Vectra_AI/Integrations/VectraDetect/VectraDetect.py
Labels: ForceMerge

#38156 Add support for personal access tokens in JiraV3
  Packs/Jira/Integrations/JiraV3/JiraV3.py
  Packs/Jira/Integrations/JiraV3/JiraV3.yml
  Packs/Jira/Integrations/JiraV3/JiraV3_test.py
  Packs/Jira/Integrations/JiraV3/README.md
  Packs/Jira/ReleaseNotes/3_2_13.md
  Packs/Jira/pack_metadata.json
Labels: Contribution, docs-approved, Contribution Form Filled, Community, ForceMerge, Xsoar Support Level, External PR

#38429 fix: in some cases CreateNewIndicatorsOnly was unable to associate in…
  Packs/CommonScripts/CONTRIBUTORS.json
  Packs/CommonScripts/ReleaseNotes/1_19_21.md
  Packs/CommonScripts/Scripts/CreateNewIndicatorsOnly/CreateNewIndicatorsOnly.py
  Packs/CommonScripts/Scripts/CreateNewIndicatorsOnly/CreateNewIndicatorsOnly.yml
  Packs/CommonScripts/pack_metadata.json
Labels: Contribution, docs-approved, Contribution Form Filled, Community, Xsoar Support Level, External PR

#38217 XSUP-45555: Fix TAXII Server in XSIAM
  Packs/TAXIIServer/Integrations/TAXIIServer/TAXIIServer.py
  Packs/TAXIIServer/ReleaseNotes/2_1_2.md
  Packs/TAXIIServer/pack_metadata.json
Labels: docs-approved, ForceMerge

#38522 CloseInvestigationAsDuplicate - add an option for error when the incident was not closed
  Packs/CommonScripts/ReleaseNotes/1_19_21.md
  Packs/CommonScripts/Scripts/CloseInvestigationAsDuplicate/CloseInvestigationAsDuplicate.py
  Packs/CommonScripts/Scripts/CloseInvestigationAsDuplicate/CloseInvestigationAsDuplicate.yml
  Packs/CommonScripts/Scripts/CloseInvestigationAsDuplicate/README.md
  Packs/CommonScripts/pack_metadata.json
Labels: ForceMerge

#38464 Add new command securityscorecard-alert-rules-list
  Packs/SecurityScorecard/Integrations/SecurityScorecard/README.md
  Packs/SecurityScorecard/Integrations/SecurityScorecard/SecurityScorecard.py
  Packs/SecurityScorecard/Integrations/SecurityScorecard/SecurityScorecard.yml
  Packs/SecurityScorecard/Integrations/SecurityScorecard/SecurityScorecard_test.py
  Packs/SecurityScorecard/Integrations/SecurityScorecard/command_examples.txt
  Packs/SecurityScorecard/Integrations/SecurityScorecard/test_data/data.json
  Packs/SecurityScorecard/ReleaseNotes/1_0_11.md
  Packs/SecurityScorecard/pack_metadata.json
Labels: Contribution, docs-approved, Partner, Contribution Form Filled, Partner Support Level, External PR, Partner-Approved

#38531 NetskopeAPIv2 integration update README.md
  Packs/Netskope/Integrations/NetskopeAPIv2/NetskopeAPIv2.yml
  Packs/Netskope/Integrations/NetskopeAPIv2/README.md
  Packs/Netskope/ReleaseNotes/4_0_6.md
  Packs/Netskope/pack_metadata.json
Labels: docs-approved

#38541 move PB130 and PB131 to warning
  validation_config.toml
Labels: ForceMerge

#38517 [SolarWinds] Add `Port` parameter
  Packs/SolarWinds/Integrations/SolarWinds/SolarWinds.py
  Packs/SolarWinds/Integrations/SolarWinds/SolarWinds.yml
  Packs/SolarWinds/Integrations/SolarWinds/SolarWinds_test.py
  Packs/SolarWinds/ReleaseNotes/1_0_18.md
  Packs/SolarWinds/pack_metadata.json
Labels: docs-approved

#38508 [Pack][RecordedFuture][v1.8.3] Fix bug related to 'Trust any certificate (not secure)' setting.
  Packs/RecordedFuture/Integrations/RecordedFuturePlaybookAlerts/RecordedFuturePlaybookAlerts.py
  Packs/RecordedFuture/Integrations/RecordedFuturePlaybookAlerts/RecordedFuturePlaybookAlerts.yml
  Packs/RecordedFuture/Integrations/RecordedFuturePlaybookAlerts/RecordedFuturePlaybookAlerts_test.py
  Packs/RecordedFuture/ReleaseNotes/1_8_3.md
  Packs/RecordedFuture/pack_metadata.json
Labels: Contribution, docs-approved, Partner, Contribution Form Filled, Partner Support Level, External PR, Partner-Approved

#37615 Archer V2 search records and fetch incidents raw XML filtering
  Packs/ArcherRSA/Integrations/ArcherV2/ArcherV2.py
  Packs/ArcherRSA/Integrations/ArcherV2/ArcherV2.yml
  Packs/ArcherRSA/Integrations/ArcherV2/ArcherV2_test.py
  Packs/ArcherRSA/Integrations/ArcherV2/README.md
  Packs/ArcherRSA/Integrations/ArcherV2/command_examples.txt
  Packs/ArcherRSA/ReleaseNotes/1_3_0.md
  Packs/ArcherRSA/pack_metadata.json
Labels: enhancement, docs-approved, python, ignore-auto-bump-version

#38447 Update Ruff 0.0.264 -> 0.8.0
  poetry.lock
Labels: docs-approved

#38523 Direct message handler
  Packs/MicrosoftTeams/Integrations/MicrosoftTeams/MicrosoftTeams.py
  Packs/MicrosoftTeams/Integrations/MicrosoftTeams/MicrosoftTeams_test.py
  Packs/MicrosoftTeams/ReleaseNotes/1_5_14.md
  Packs/MicrosoftTeams/pack_metadata.json
Labels: docs-approved

#38375 XSUP-45903: SplunkPy
  Packs/SplunkPy/Integrations/SplunkPy/SplunkPy.py
  Packs/SplunkPy/ReleaseNotes/3_2_1.md
  Packs/SplunkPy/pack_metadata.json
Labels: docs-approved

#38549 XSUP 46676/fixed error message 400
  Packs/PrismaSaasSecurity/Integrations/SaasSecurityEventCollector/SaasSecurityEventCollector.py
  Packs/PrismaSaasSecurity/Integrations/SaasSecurityEventCollector/SaasSecurityEventCollector.yml
  Packs/PrismaSaasSecurity/Integrations/SaasSecurityEventCollector/SaasSecurityEventCollector_test.py
  Packs/PrismaSaasSecurity/ReleaseNotes/2_0_37.md
  Packs/PrismaSaasSecurity/pack_metadata.json
Labels: docs-approved

#38199 Update Integration: CTM360
  Packs/CTM360-CyberBlindspot/.pack-ignore
  Packs/CTM360-CyberBlindspot/.secrets-ignore
  Packs/CTM360-CyberBlindspot/CONTRIBUTORS.json
  Packs/CTM360-CyberBlindspot/Classifiers/classifier-mapper-incoming-CTM360-CyberBlindspot.json
  Packs/CTM360-CyberBlindspot/Dashboards/dashboard-CyberBlindspot.json
  Packs/CTM360-CyberBlindspot/IncidentFields/incidentfields-Module.json
  Packs/CTM360-CyberBlindspot/IncidentTypes/CyberBlindspot_Incident.json
  Packs/CTM360-CyberBlindspot/Integrations/CyberBlindspot/CyberBlindspot.py
  Packs/CTM360-CyberBlindspot/Integrations/CyberBlindspot/CyberBlindspot.yml
  Packs/CTM360-CyberBlindspot/Integrations/CyberBlindspot/CyberBlindspot_test.py
  Packs/CTM360-CyberBlindspot/Integrations/CyberBlindspot/README.md
  Packs/CTM360-CyberBlindspot/Integrations/CyberBlindspot/test_data/card_details_response_valid.json
  Packs/CTM360-CyberBlindspot/Integrations/CyberBlindspot/test_data/card_list_cmd_result_valid.json
  Packs/CTM360-CyberBlindspot/Integrations/CyberBlindspot/test_data/cred_details_response_valid.json
  Packs/CTM360-CyberBlindspot/Integrations/CyberBlindspot/test_data/cred_list_cmd_result_valid.json
  Packs/CTM360-CyberBlindspot/Integrations/CyberBlindspot/test_data/domain_details_response_valid.json
  Packs/CTM360-CyberBlindspot/Integrations/CyberBlindspot/test_data/domain_list_cmd_result_valid.json
  Packs/CTM360-CyberBlindspot/Integrations/CyberBlindspot/test_data/fetch_cards_response_valid.json
  Packs/CTM360-CyberBlindspot/Integrations/CyberBlindspot/test_data/fetch_creds_response_valid.json
  Packs/CTM360-CyberBlindspot/Integrations/CyberBlindspot/test_data/fetch_domains_response_valid.json
  Packs/CTM360-CyberBlindspot/Integrations/CyberBlindspot/test_data/fetch_incidents_response_valid.json
  Packs/CTM360-CyberBlindspot/Integrations/CyberBlindspot/test_data/fetch_subdomains_response_valid.json
  Packs/CTM360-CyberBlindspot/Integrations/CyberBlindspot/test_data/incident_details_response_valid.json
  Packs/CTM360-CyberBlindspot/Integrations/CyberBlindspot/test_data/incident_list_cmd_result_valid.json
  Packs/CTM360-CyberBlindspot/Integrations/CyberBlindspot/test_data/subdomain_details_response_valid.json
  Packs/CTM360-CyberBlindspot/Integrations/CyberBlindspot/test_data/subdomain_list_cmd_result_valid.json
  Packs/CTM360-CyberBlindspot/Playbooks/playbook-CyberBlindspot_Incident_Management_V2.yml
  Packs/CTM360-CyberBlindspot/Playbooks/playbook-CyberBlindspot_Incident_Management_V2_README.md
  Packs/CTM360-CyberBlindspot/README.md
  Packs/CTM360-CyberBlindspot/ReleaseNotes/2_1_0.md
  Packs/CTM360-CyberBlindspot/doc_files/CyberBlindspot_Incident_Management_V2.png
  Packs/CTM360-CyberBlindspot/pack_metadata.json
Labels: Contribution, docs-approved, Partner, pending-demo, Contribution Form Filled, Partner Support Level, External PR, Security Review, Partner-Approved, Security Approved

#38499 Update README.md
  Packs/Slack/Integrations/SlackV3/README.md
Labels: docs-approved

#38336 Jamf computer fetch assets and refactored
  Packs/JamfProtect/Integrations/JamfProtectEventCollector/JamfProtectEventCollector.py
  Packs/JamfProtect/Integrations/JamfProtectEventCollector/JamfProtectEventCollector.yml
  Packs/JamfProtect/Integrations/JamfProtectEventCollector/JamfProtectEventCollector_description.md
  Packs/JamfProtect/Integrations/JamfProtectEventCollector/JamfProtectEventCollector_test.py
  Packs/JamfProtect/Integrations/JamfProtectEventCollector/README.md
  Packs/JamfProtect/ReleaseNotes/1_2_0.json
  Packs/JamfProtect/ReleaseNotes/1_2_0.md
  Packs/JamfProtect/pack_metadata.json
Labels: docs-approved, ForceMerge

#38538 XDR port scan alert handling fix
  Packs/CortexXDR/Playbooks/Cortex_XDR_Alerts_Handling_v2.yml
  Packs/CortexXDR/ReleaseNotes/6_2_12.md
  Packs/CortexXDR/pack_metadata.json
Labels: docs-approved

#38561 remove RN116
  validation_config.toml
Labels: docs-approved

#38563 fix tpb Retrieve File from Endpoint - Generic V3 Test
  Packs/CommonPlaybooks/TestPlaybooks/playbook-Retrieve_File_from_Endpoint_-_Generic_V3_Test.yml
Labels: docs-approved

#38334 Added new playbook uncommon execution of odbcconf
  Packs/CortexResponseAndRemediation/Playbooks/playbook-Uncommon_execution_of_ODBCConf.yml
  Packs/CortexResponseAndRemediation/Playbooks/playbook-Uncommon_execution_of_ODBCConf_README.md
  Packs/CortexResponseAndRemediation/ReleaseNotes/1_1_7.md
  Packs/CortexResponseAndRemediation/Triggers/Trigger_-_Uncommon_execution_of_ODBCconf.json
  Packs/CortexResponseAndRemediation/doc_files/Uncommon_execution_of_ODBCConf.png
  Packs/CortexResponseAndRemediation/pack_metadata.json
Labels: docs-approved

#38532 Change onePassword logo
  Packs/OnePassword/Integrations/OnePassword/OnePassword.yml
  Packs/OnePassword/Integrations/OnePassword/OnePassword_image.png
  Packs/OnePassword/Integrations/OnePassword/OnePassword_test.py
  Packs/OnePassword/ReleaseNotes/1_0_2.md
  Packs/OnePassword/pack_metadata.json
Labels: docs-approved

#38493 [ZeroFox] Remove api-token-auth/ call to avoid rate-limits
  Packs/ZeroFox/Integrations/ZeroFox/ZeroFox.py
  Packs/ZeroFox/Integrations/ZeroFox/ZeroFox.yml
  Packs/ZeroFox/Integrations/ZeroFox/ZeroFox_test.py
  Packs/ZeroFox/ReleaseNotes/1_3_6.md
  Packs/ZeroFox/ReleaseNotes/1_3_7.json
  Packs/ZeroFox/ReleaseNotes/1_3_7.md
  Packs/ZeroFox/pack_metadata.json
Labels: Contribution, docs-approved, Partner, pending-demo, Contribution Form Filled, Partner Support Level, External PR, Partner-Approved, Pending-Partner

#38587 CISCO ISR Parsing Update
  Packs/CiscoISR/ParsingRules/CiscoISR/CiscoISR.xif
  Packs/CiscoISR/ReleaseNotes/1_0_6.md
  Packs/CiscoISR/pack_metadata.json
Labels: docs-approved

#38542 bug - incorrect usage of the 'Maximum CIDR network prefix bits size' …
  Packs/EDL/Integrations/EDL/EDL.py
  Packs/EDL/Integrations/EDL/EDL.yml
  Packs/EDL/Integrations/EDL/README.md
  Packs/EDL/ReleaseNotes/3_3_8.md
  Packs/EDL/pack_metadata.json
Labels: docs-approved

#38555 SaaS Security added a limit validation due to API limitations
  Packs/PrismaSaasSecurity/Integrations/SaasSecurity/SaasSecurity.py
  Packs/PrismaSaasSecurity/Integrations/SaasSecurity/SaasSecurity_test.py
  Packs/PrismaSaasSecurity/ReleaseNotes/2_0_38.md
  Packs/PrismaSaasSecurity/pack_metadata.json
Labels: docs-approved, release-notes-only

#38536 External Login Password Spray - added close reason
  Packs/CortexResponseAndRemediation/Playbooks/playbook-External_Login_Password_Spray.yml
  Packs/CortexResponseAndRemediation/ReleaseNotes/1_1_8.md
  Packs/CortexResponseAndRemediation/pack_metadata.json
Labels: docs-approved, release-notes-only

#38594 Improve the example used in test data
  Packs/CohesityHelios/Integrations/CohesityHeliosEventCollector/test_data/CohesityHeliosEventCollector-AuditLogList.json
Labels: docs-approved

#38597 XSUP-46574-Checkpoint-Firewall
  Packs/CheckpointFirewall/ModelingRules/CheckpointFirewall_1_3/CheckpointFirewall_1_3.xif
  Packs/CheckpointFirewall/ModelingRules/CheckpointFirewall_1_3/CheckpointFirewall_1_3_schema.json
  Packs/CheckpointFirewall/ReleaseNotes/2_3_27.md
  Packs/CheckpointFirewall/pack_metadata.json
Labels: docs-approved

#38397 CIAC-12722: taxiifeed- fixed an issue in which not all domain type indicator are retrieved
  Packs/FeedTAXII/Integrations/FeedTAXII/FeedTAXII.py
  Packs/FeedTAXII/Integrations/FeedTAXII/FeedTAXII_test.py
  Packs/FeedTAXII/ReleaseNotes/1_2_30.md
  Packs/FeedTAXII/TestPlaybooks/playbook-TAXII_Feed_Test.yml
  Packs/FeedTAXII/pack_metadata.json
Labels: docs-approved, ForceMerge

#38589 Fixing parsing rule for Cisco ASR
  Packs/CiscoASR/ParsingRules/CiscoASR/CiscoASR.xif
  Packs/CiscoASR/ReleaseNotes/1_0_4.md
  Packs/CiscoASR/pack_metadata.json
Labels: docs-approved

#38349 XSUP-45994: TAXII2 Server
  Packs/ApiModules/ReleaseNotes/2_2_40.md
  Packs/ApiModules/Scripts/TAXII2ApiModule/TAXII2ApiModule.py
  Packs/ApiModules/Scripts/TAXII2ApiModule/TAXII2ApiModule_test.py
  Packs/ApiModules/Scripts/TAXII2ApiModule/test_data/create_indicators_test_results.json
  Packs/ApiModules/pack_metadata.json
  Packs/CommonScripts/ReleaseNotes/1_19_25.md
  Packs/CommonScripts/pack_metadata.json
  Packs/FeedDHS/ReleaseNotes/2_0_48.md
  Packs/FeedDHS/pack_metadata.json
  Packs/FeedGitHub/ReleaseNotes/1_0_16.md
  Packs/FeedGitHub/pack_metadata.json
  Packs/FeedMitreAttackv2/ReleaseNotes/1_2_1.md
  Packs/FeedMitreAttackv2/pack_metadata.json
  Packs/FeedTAXII/ReleaseNotes/1_2_31.md
  Packs/FeedTAXII/pack_metadata.json
  Packs/FeedUnit42v2/ReleaseNotes/1_0_62.md
  Packs/FeedUnit42v2/pack_metadata.json
  Packs/TAXIIServer/Integrations/TAXII2Server/TAXII2Server.py
  Packs/TAXIIServer/Integrations/TAXII2Server/TAXII2Server.yml
  Packs/TAXIIServer/Integrations/TAXII2Server/test_data/manifest20.json
  Packs/TAXIIServer/Integrations/TAXII2Server/test_data/manifest21.json
  Packs/TAXIIServer/Integrations/TAXII2Server/test_data/objects20-indicators.json
  Packs/TAXIIServer/Integrations/TAXII2Server/test_data/objects20.json
  Packs/TAXIIServer/Integrations/TAXII2Server/test_data/objects21_domain.json
  Packs/TAXIIServer/Integrations/TAXII2Server/test_data/objects21_file.json
  Packs/TAXIIServer/Integrations/TAXII2Server/test_data/objects21_ip_with_relationships.json
  Packs/TAXIIServer/Integrations/TAXII2Server/test_data/objects21_malware.json
  Packs/TAXIIServer/Integrations/TAXII2Server/test_data/objects21_no_extention_file.json
  Packs/TAXIIServer/Integrations/TAXII2Server/test_data/objects21_spec_fields_file.json
  Packs/TAXIIServer/ReleaseNotes/2_1_3.md
  Packs/TAXIIServer/pack_metadata.json
Labels: docs-approved

#38457 [Google Threat Intelligence] Private url scanning
  Packs/GoogleThreatIntelligence/Integrations/GoogleThreatIntelligence/GoogleThreatIntelligence.py
  Packs/GoogleThreatIntelligence/Integrations/GoogleThreatIntelligence/GoogleThreatIntelligence.yml
  Packs/GoogleThreatIntelligence/Integrations/GoogleThreatIntelligence/GoogleThreatIntelligence_test.py
  Packs/GoogleThreatIntelligence/Integrations/GoogleThreatIntelligence/README.md
  Packs/GoogleThreatIntelligence/Integrations/GoogleThreatIntelligence/test_data/private_url.json
  Packs/GoogleThreatIntelligence/Integrations/GoogleThreatIntelligence/test_data/private_url_results.json
  Packs/GoogleThreatIntelligence/ReleaseNotes/1_2_0.md
  Packs/GoogleThreatIntelligence/pack_metadata.json
Labels: Contribution, Partner, Contribution Form Filled, Partner Support Level, External PR, Partner-Approved

#38588 Fixed an issue with a wrong link to a Varonis Alert page on VaronisSaaS Web Application.
  Packs/VaronisSaaS/Integrations/VaronisSaaS/VaronisSaaS.py
  Packs/VaronisSaaS/Integrations/VaronisSaaS/VaronisSaaS.yml
  Packs/VaronisSaaS/Integrations/VaronisSaaS/VaronisSaaS_test.py
  Packs/VaronisSaaS/Integrations/VaronisSaaS/test_data/fetch_incidents_output.json
  Packs/VaronisSaaS/Integrations/VaronisSaaS/test_data/varonis_fetch_incidents_output.json
  Packs/VaronisSaaS/Integrations/VaronisSaaS/test_data/varonis_get_alerts_command_output.json
  Packs/VaronisSaaS/ReleaseNotes/1_0_10.md
  Packs/VaronisSaaS/Scripts/varonisalertpostprocessing/varonisalertpostprocessing.yml
  Packs/VaronisSaaS/pack_metadata.json
Labels: Contribution, docs-approved, Partner, Contribution Form Filled, Partner Support Level, External PR, Partner-Approved

#38622 Fix poetry install
  .hooks/bootstrap
  .hooks/install.python-poetry.py
  Tests/secrets_white_list.json
Labels: ForceMerge

#38376 Take on - Microsoft Graph API_Test contribution
  Packs/MicrosoftGraphAPI/Integrations/MicrosoftGraphAPI/MicrosoftGraphAPI.py
  Packs/MicrosoftGraphAPI/Integrations/MicrosoftGraphAPI/MicrosoftGraphAPI.yml
  Packs/MicrosoftGraphAPI/Integrations/MicrosoftGraphAPI/MicrosoftGraphAPI_test.py
  Packs/MicrosoftGraphAPI/Integrations/MicrosoftGraphAPI/README.md
  Packs/MicrosoftGraphAPI/ReleaseNotes/1_1_53.md
  Packs/MicrosoftGraphAPI/pack_metadata.json
Labels: docs-approved, sync-gsm

#38559 cs-falcon-search-device improve filter description
  Packs/CrowdStrikeFalcon/Integrations/CrowdStrikeFalcon/CrowdStrikeFalcon.yml
  Packs/CrowdStrikeFalcon/Integrations/CrowdStrikeFalcon/README.md
  Packs/CrowdStrikeFalcon/ReleaseNotes/2_1_13.md
  Packs/CrowdStrikeFalcon/pack_metadata.json
Labels: docs-approved

#38525 JiraV3 Add The Raw Description To The Incident Context
  Packs/Jira/Integrations/JiraV3/JiraV3.py
  Packs/Jira/Integrations/JiraV3/JiraV3.yml
  Packs/Jira/Integrations/JiraV3/JiraV3_description.md
  Packs/Jira/Integrations/JiraV3/JiraV3_test.py
  Packs/Jira/Integrations/JiraV3/README.md
  Packs/Jira/Integrations/JiraV3/test_data/get_epic_issues_test/parsed_result.json
  Packs/Jira/Integrations/JiraV3/test_data/get_epic_issues_test/raw_response.json
  Packs/Jira/Integrations/JiraV3/test_data/get_issue_query_test/parsed_result.json
  Packs/Jira/Integrations/JiraV3/test_data/get_issue_query_test/raw_response.json
  Packs/Jira/Integrations/JiraV3/test_data/get_issue_test/parsed_result.json
  Packs/Jira/Integrations/JiraV3/test_data/get_issue_test/raw_response.json
  Packs/Jira/Integrations/JiraV3/test_data/get_issue_test/raw_response_extended_issues.json
  Packs/Jira/Integrations/JiraV3/test_data/get_issues_from_backlog_test/parsed_result.json
  Packs/Jira/Integrations/JiraV3/test_data/get_issues_from_backlog_test/raw_response.json
  Packs/Jira/Integrations/JiraV3/test_data/get_issues_from_board_test/parsed_result.json
  Packs/Jira/Integrations/JiraV3/test_data/get_issues_from_board_test/raw_response.json
  Packs/Jira/Integrations/JiraV3/test_data/get_specific_field_test/parsed_result.json
  Packs/Jira/Integrations/JiraV3/test_data/get_specific_field_test/raw_response.json
  Packs/Jira/Integrations/JiraV3/test_data/get_sprint_issues_test/parsed_result.json
  Packs/Jira/Integrations/JiraV3/test_data/get_sprint_issues_test/raw_response.json
  Packs/Jira/Integrations/JiraV3/test_data/parsed_issue_custom_fields.json
  Packs/Jira/ReleaseNotes/3_2_14.md
  Packs/Jira/pack_metadata.json
Labels: docs-approved

#38606 MS Teams - Improved the HR of the 'microsoft-teams-token-permissions-list' command
  Packs/MicrosoftTeams/Integrations/MicrosoftTeams/MicrosoftTeams.py
  Packs/MicrosoftTeams/ReleaseNotes/1_5_15.md
  Packs/MicrosoftTeams/pack_metadata.json
Labels: docs-approved

#38512 Panoaram get-jobs command
  Packs/PAN-OS/Integrations/Panorama/Panorama.py
  Packs/PAN-OS/Integrations/Panorama/Panorama_test.py
  Packs/PAN-OS/ReleaseNotes/2_3_4.md
  Packs/PAN-OS/pack_metadata.json
Labels: ForceMerge

#38616 Add docs for limit param
  Packs/PrismaSaasSecurity/Integrations/SaasSecurity/README.md
  Packs/PrismaSaasSecurity/Integrations/SaasSecurity/SaasSecurity.yml
  Packs/PrismaSaasSecurity/ReleaseNotes/2_0_39.md
  Packs/PrismaSaasSecurity/pack_metadata.json
Labels: docs-approved

#38180 Ewsv2 to api module
  Packs/ApiModules/Scripts/EWSApiModule/EWSApiModule.py
  Packs/MicrosoftExchangeOnPremise/Integrations/EWSv2/EWSv2.py
  Packs/MicrosoftExchangeOnPremise/Integrations/EWSv2/EWSv2_test.py
  Packs/MicrosoftExchangeOnPremise/ReleaseNotes/2_2_0.md
  Packs/MicrosoftExchangeOnPremise/TestPlaybooks/playbook-pyEWS_Test.yml
  Packs/MicrosoftExchangeOnPremise/pack_metadata.json
  Packs/MicrosoftExchangeOnline/Integrations/EWSO365/EWSO365.py
  Packs/MicrosoftExchangeOnline/ReleaseNotes/1_6_1.md
  Packs/MicrosoftExchangeOnline/ReleaseNotes/1_6_3.md
  Packs/MicrosoftExchangeOnline/pack_metadata.json
  Tests/conf.json
Labels: docs-approved

#38521 SPNs cleared from a machine account [Silent]
  Packs/CortexResponseAndRemediation/.pack-ignore
  Packs/CortexResponseAndRemediation/Playbooks/silent-SPNs_cleared_from_a_machine_account.yml
  Packs/CortexResponseAndRemediation/ReleaseNotes/1_1_9.md
  Packs/CortexResponseAndRemediation/Triggers/silent-Trigger-_-SPNs_cleared_from_a_machine_account.json
  Packs/CortexResponseAndRemediation/pack_metadata.json
Labels: docs-approved

#38626 Contrib assignees
  .github/content_roles.json
Labels: docs-approved

#38240 XSUP-45837-proofpoint-tr-verify-quarantine
  Packs/ProofpointThreatResponse/Integrations/ProofpointThreatResponse/ProofpointThreatResponse.py
  Packs/ProofpointThreatResponse/Integrations/ProofpointThreatResponse/ProofpointThreatResponse.yml
  Packs/ProofpointThreatResponse/Integrations/ProofpointThreatResponse/ProofpointThreatResponse_test.py
  Packs/ProofpointThreatResponse/Integrations/ProofpointThreatResponse/README.md
  Packs/ProofpointThreatResponse/Integrations/ProofpointThreatResponse/test_data/incident_email_manually_quarantined.json
  Packs/ProofpointThreatResponse/ReleaseNotes/2_0_22.md
  Packs/ProofpointThreatResponse/pack_metadata.json
Labels: docs-approved

#38614 remove non existing error codes from validation_config.toml
  validation_config.toml
Labels: docs-approved

#38596 Improve MITRE ID indicator query logic
  Packs/CommonScripts/ReleaseNotes/1_19_26.md
  Packs/CommonScripts/Scripts/MITRENameByIDFormatter/MITRENameByIDFormatter.py
  Packs/CommonScripts/Scripts/MITRENameByIDFormatter/MITRENameByIDFormatter.yml
  Packs/CommonScripts/pack_metadata.json
Labels: Contribution, docs-approved, Contribution Form Filled, Community, Xsoar Support Level, External PR

#38209 Teams Replies and Message Updates
  Packs/MicrosoftTeams/Integrations/MicrosoftTeams/MicrosoftTeams.py
  Packs/MicrosoftTeams/Integrations/MicrosoftTeams/MicrosoftTeams.yml
  Packs/MicrosoftTeams/Integrations/MicrosoftTeams/MicrosoftTeams_test.py
  Packs/MicrosoftTeams/Integrations/MicrosoftTeams/README.md
  Packs/MicrosoftTeams/Integrations/MicrosoftTeams/test_data/send_message/expected_generic.json
  Packs/MicrosoftTeams/Integrations/MicrosoftTeams/test_data/send_message/raw_generic.json
  Packs/MicrosoftTeams/ReleaseNotes/1_5_16.md
  Packs/MicrosoftTeams/Scripts/MicrosoftTeamsAsk/MicrosoftTeamsAsk.py
  Packs/MicrosoftTeams/Scripts/MicrosoftTeamsAsk/MicrosoftTeamsAsk.yml
  Packs/MicrosoftTeams/pack_metadata.json
Labels: Contribution, Contribution Form Filled, Community, Xsoar Support Level, External PR

#37296 Added new command cybereason-update-malop-investigation-status to Cybereason integration
  Packs/Cybereason/CONTRIBUTORS.json
  Packs/Cybereason/Integrations/Cybereason/Cybereason.py
  Packs/Cybereason/Integrations/Cybereason/Cybereason.yml
  Packs/Cybereason/Integrations/Cybereason/Cybereason_test.py
  Packs/Cybereason/Integrations/Cybereason/README.md
  Packs/Cybereason/Integrations/Cybereason/command_examples.txt
  Packs/Cybereason/README.md
  Packs/Cybereason/ReleaseNotes/2_1_21.md
  Packs/Cybereason/pack_metadata.json
Labels: Contribution, docs-approved, post-demo, Contribution Form Filled, Community, Partner Support Level, External PR, Partner-Approved

#38627 Fix ServiceNow Create Ticket Playbook
  Packs/ServiceNow/Playbooks/playbook-Create_ServiceNow_Ticket.yml
  Packs/ServiceNow/ReleaseNotes/2_7_7.md
  Packs/ServiceNow/doc_files/Create_ServiceNow_Ticket.png
  Packs/ServiceNow/pack_metadata.json
Labels: docs-approved

#38427 Integration - Add support for Absolute API V3
  Packs/Absolute/Integrations/Absolute/Absolute.py
  Packs/Absolute/Integrations/Absolute/Absolute.yml
  Packs/Absolute/Integrations/Absolute/Absolute_test.py
  Packs/Absolute/Integrations/Absolute/README.md
  Packs/Absolute/Integrations/Absolute/command_examples.txt
  Packs/Absolute/Integrations/Absolute/test_data/custom_device_field_list_response.json
  Packs/Absolute/Integrations/Absolute/test_data/custom_get_device_freeze_request_response.json
  Packs/Absolute/Integrations/Absolute/test_data/device_freeze_message_list_response.json
  Packs/Absolute/Integrations/Absolute/test_data/device_location_get.json
  Packs/Absolute/Integrations/Absolute/test_data/unenroll_device_response.json
  Packs/Absolute/ReleaseNotes/2_0_0.json
  Packs/Absolute/ReleaseNotes/2_0_0.md
  Packs/Absolute/TestPlaybooks/playbook-Absolute.yml
  Packs/Absolute/pack_metadata.json
Labels: docs-approved, ForceMerge

#38585 [Microsoft Graph User] Update Docs For The msgraph-user-session-revoke Command
  Packs/MicrosoftGraphUser/Integrations/MicrosoftGraphUser/MicrosoftGraphUser.yml
  Packs/MicrosoftGraphUser/Integrations/MicrosoftGraphUser/README.md
  Packs/MicrosoftGraphUser/ReleaseNotes/1_5_43.md
  Packs/MicrosoftGraphUser/pack_metadata.json
Labels: docs-approved

#38603 New playbook for authentication method added
  Packs/CortexResponseAndRemediation/.pack-ignore
  Packs/CortexResponseAndRemediation/Playbooks/silent-playbook-Authentication_method_added_to_an_Azure_account.yml
  Packs/CortexResponseAndRemediation/ReleaseNotes/1_1_10.md
  Packs/CortexResponseAndRemediation/Triggers/silent-Trigger_-_Authentication_method_added_to_an_Azure_account.json
  Packs/CortexResponseAndRemediation/pack_metadata.json
Labels: docs-approved, bypass.url

#38615 Fix script email field triggered
  Packs/CommonScripts/ReleaseNotes/1_19_27.md
  Packs/CommonScripts/Scripts/EmailFieldTriggered/EmailFieldTriggered.js
  Packs/CommonScripts/pack_metadata.json
Labels: docs-approved, ForceMerge

#38537 CRTX-146131-Microsoft-Defender-for-Cloud
  Packs/AzureSecurityCenter/ModelingRules/MicrosoftDefenderForCloudModelingRules/MicrosoftDefenderForCloudModelingRules.xif
  Packs/AzureSecurityCenter/ModelingRules/MicrosoftDefenderForCloudModelingRules/MicrosoftDefenderForCloudModelingRules_schema.json
  Packs/AzureSecurityCenter/ReleaseNotes/2_0_36.md
  Packs/AzureSecurityCenter/pack_metadata.json
Labels: docs-approved, bypass.url

#38628 bug - TAXII server errors are spamming the fetch history
  Packs/TAXIIServer/Integrations/TAXIIServer/TAXIIServer.py
  Packs/TAXIIServer/ReleaseNotes/2_1_4.md
  Packs/TAXIIServer/pack_metadata.json
Labels: docs-approved, ForceMerge

#38625 xsup-46792: add support for **Return Error** parameter.
  Packs/URLHaus/Integrations/URLHaus/URLHaus.py
  Packs/URLHaus/Integrations/URLHaus/URLHaus.yml
  Packs/URLHaus/Integrations/URLHaus/URLHaus_test.py
  Packs/URLHaus/ReleaseNotes/1_0_33.md
  Packs/URLHaus/pack_metadata.json
Labels: docs-approved

#38264 Fixed fireeye-nx-get-artifacts-by-alert command - ContentType
  Packs/FireEyeNX/Integrations/FireEyeNX/FireEyeNX.py
  Packs/FireEyeNX/Integrations/FireEyeNX/FireEyeNX.yml
  Packs/FireEyeNX/ReleaseNotes/1_1_39.md
  Packs/FireEyeNX/pack_metadata.json
Labels: docs-approved

#38642 Okta ciac 12686
  Packs/Okta/Integrations/Okta_v2/Okta_v2.py
  Packs/Okta/Integrations/Okta_v2/Okta_v2.yml
  Packs/Okta/Integrations/Okta_v2/Okta_v2_description.md
  Packs/Okta/Integrations/Okta_v2/Okta_v2_test.py
  Packs/Okta/Integrations/Okta_v2/README.md
  Packs/Okta/ReleaseNotes/3_3_11.md
  Packs/Okta/pack_metadata.json
Labels: docs-approved

#38530 Added URL output field to FeedLOLBAS integration
  Packs/FeedLOLBAS/CONTRIBUTORS.json
  Packs/FeedLOLBAS/Integrations/FeedLOLBAS/FeedLOLBAS.py
  Packs/FeedLOLBAS/Integrations/FeedLOLBAS/FeedLOLBAS.yml
  Packs/FeedLOLBAS/Integrations/FeedLOLBAS/README.md
  Packs/FeedLOLBAS/Integrations/FeedLOLBAS/test_data/expected_build_indicators.json
  Packs/FeedLOLBAS/Integrations/FeedLOLBAS/test_data/expected_fetch_indicators.json
  Packs/FeedLOLBAS/Integrations/FeedLOLBAS/test_data/expected_get_indicators_outputs.json
  Packs/FeedLOLBAS/ReleaseNotes/1_0_21.md
  Packs/FeedLOLBAS/pack_metadata.json
Labels: Contribution, docs-approved, Contribution Form Filled, Community, Xsoar Support Level, External PR

#37480 [Enhancement] - Incident mirroring and Incident Structure update for Microsoft 365 Defender
  Packs/Microsoft365Defender/.pack-ignore
  Packs/Microsoft365Defender/.secrets-ignore
  Packs/Microsoft365Defender/Classifiers/classifier-Microsoft_365_Defender_-_Incoming_Mapper.json
  Packs/Microsoft365Defender/Classifiers/classifier-Microsoft_365_Defender_-_Outgoing_Mapper.json
  Packs/Microsoft365Defender/IncidentFields/incidentfield-Microsoft_365_Defender_Categories_count.json
  Packs/Microsoft365Defender/IncidentFields/incidentfield-Microsoft_365_Defender_Classification.json
  Packs/Microsoft365Defender/IncidentFields/incidentfield-Microsoft_365_Defender_Comments.json
  Packs/Microsoft365Defender/IncidentFields/incidentfield-Microsoft_365_Defender_Mailboxes.json
  Packs/Microsoft365Defender/IncidentFields/incidentfield-Microsoft_365_Defender_Status.json
  Packs/Microsoft365Defender/Integrations/Microsoft365Defender/Microsoft365Defender.py
  Packs/Microsoft365Defender/Integrations/Microsoft365Defender/Microsoft365Defender.yml
  Packs/Microsoft365Defender/Integrations/Microsoft365Defender/Microsoft365Defender_test.py
  Packs/Microsoft365Defender/Integrations/Microsoft365Defender/README.md
  Packs/Microsoft365Defender/Integrations/Microsoft365Defender/test_data/converted_incident.json
  Packs/Microsoft365Defender/Integrations/Microsoft365Defender/test_data/empty_incident.json
  Packs/Microsoft365Defender/Integrations/Microsoft365Defender/test_data/fetch_response.json
  Packs/Microsoft365Defender/Integrations/Microsoft365Defender/test_data/fetch_results.json
  Packs/Microsoft365Defender/Integrations/Microsoft365Defender/test_data/incident_get_results.json
  Packs/Microsoft365Defender/Integrations/Microsoft365Defender/test_data/incident_update_results.json
  Packs/Microsoft365Defender/Integrations/Microsoft365Defender/test_data/incidents_empty_list_response.json
  Packs/Microsoft365Defender/Integrations/Microsoft365Defender/test_data/incidents_list_results.json
  Packs/Microsoft365Defender/Layouts/layoutscontainer-Microsoft_365_Defender_-_Layout.json
  Packs/Microsoft365Defender/ReleaseNotes/4_6_0.json
  Packs/Microsoft365Defender/ReleaseNotes/4_6_0.md
  Packs/Microsoft365Defender/Scripts/MS365DefenderAddComment/MS365DefenderAddComment.py
  Packs/Microsoft365Defender/Scripts/MS365DefenderAddComment/MS365DefenderAddComment.yml
  Packs/Microsoft365Defender/Scripts/MS365DefenderAddComment/MS365DefenderAddComment_test.py
  Packs/Microsoft365Defender/Scripts/MS365DefenderAddComment/README.md
  Packs/Microsoft365Defender/Scripts/MS365DefenderCountIncidentCategories/MS365DefenderCountIncidentCategories.py
  Packs/Microsoft365Defender/Scripts/MS365DefenderCountIncidentCategories/MS365DefenderCountIncidentCategories.yml
  Packs/Microsoft365Defender/Scripts/MS365DefenderCountIncidentCategories/MS365DefenderCountIncidentCategories_test.py
  Packs/Microsoft365Defender/Scripts/MS365DefenderCountIncidentCategories/README.md
  Packs/Microsoft365Defender/pack_metadata.json
Labels: docs-approved, ForceMerge

#38649 Add script is pdf encrypted
  Packs/CommonPlaybooks/Playbooks/playbook-Extract_Indicators_From_File_-_Generic_v2_4_5.yml
  Packs/CommonPlaybooks/Playbooks/playbook-Extract_Indicators_From_File_-_Generic_v2_4_5_README.md
  Packs/CommonPlaybooks/ReleaseNotes/2_6_51.md
  Packs/CommonPlaybooks/doc_files/Extract_Indicators_From_File_-_Generic_v2.png
  Packs/CommonPlaybooks/pack_metadata.json
  Packs/CommonScripts/ReleaseNotes/1_19_28.md
  Packs/CommonScripts/Scripts/IsPDFFileEncrypted/IsPDFFileEncrypted.py
  Packs/CommonScripts/Scripts/IsPDFFileEncrypted/IsPDFFileEncrypted.yml
  Packs/CommonScripts/Scripts/IsPDFFileEncrypted/IsPDFFileEncrypted_test.py
  Packs/CommonScripts/Scripts/IsPDFFileEncrypted/README.md
  Packs/CommonScripts/Scripts/IsPDFFileEncrypted/test_data/encrypted.pdf
  Packs/CommonScripts/Scripts/IsPDFFileEncrypted/test_data/text-only.pdf
  Packs/CommonScripts/pack_metadata.json
Labels: docs-approved, ForceMerge

#38500 Modified modeling rule and parsing rule - Proofpoint Tap - CRTX-149389
  Packs/ProofpointTAP/ModelingRules/ProofpointTAPModelingRules_1_3/ProofpointTAPModelingRules_1_3.xif
  Packs/ProofpointTAP/ModelingRules/ProofpointTAPModelingRules_1_3/ProofpointTAPModelingRules_1_3.yml
  Packs/ProofpointTAP/ModelingRules/ProofpointTAPModelingRules_1_3/ProofpointTAPModelingRules_1_3_schema.json
  Packs/ProofpointTAP/ParsingRules/ProofpointTAP/ProofpointTAP.xif
  Packs/ProofpointTAP/ParsingRules/ProofpointTAP/ProofpointTAP.yml
  Packs/ProofpointTAP/ReleaseNotes/1_2_16.md
  Packs/ProofpointTAP/pack_metadata.json
Labels: docs-approved

#38681 added continue on error
  Packs/CortexResponseAndRemediation/Playbooks/playbook-SSO_Password_Spray.yml
  Packs/CortexResponseAndRemediation/ReleaseNotes/1_1_11.md
  Packs/CortexResponseAndRemediation/pack_metadata.json
Labels: docs-approved

#38504 Celonis Event Collector
  Packs/Celonis/.pack-ignore
  Packs/Celonis/.secrets-ignore
  Packs/Celonis/Integrations/CelonisEventCollector/CelonisEventCollector.py
  Packs/Celonis/Integrations/CelonisEventCollector/CelonisEventCollector.yml
  Packs/Celonis/Integrations/CelonisEventCollector/CelonisEventCollector_description.md
  Packs/Celonis/Integrations/CelonisEventCollector/CelonisEventCollector_image.png
  Packs/Celonis/Integrations/CelonisEventCollector/CelonisEventCollector_test.py
  Packs/Celonis/Integrations/CelonisEventCollector/README.md
  Packs/Celonis/Integrations/CelonisEventCollector/command_examples.txt
  Packs/Celonis/Integrations/CelonisEventCollector/test_data/raw_response_audit_logs.json
  Packs/Celonis/README.md
  Packs/Celonis/pack_metadata.json
Labels: docs-approved

#38643 DBot Predict Url Phishing handle no urls
  Packs/PhishingURL/ReleaseNotes/1_1_23.md
  Packs/PhishingURL/Scripts/DBotPredictURLPhishing/DBotPredictURLPhishing.py
  Packs/PhishingURL/Scripts/DBotPredictURLPhishing/DBotPredictURLPhishing_test.py
  Packs/PhishingURL/pack_metadata.json
Labels: ForceMerge

#38620 feat: add issue_details_get_command
  Packs/SecurityScorecard/Integrations/SecurityScorecard/README.md
  Packs/SecurityScorecard/Integrations/SecurityScorecard/SecurityScorecard.py
  Packs/SecurityScorecard/Integrations/SecurityScorecard/SecurityScorecard.yml
  Packs/SecurityScorecard/Integrations/SecurityScorecard/SecurityScorecard_test.py
  Packs/SecurityScorecard/Integrations/SecurityScorecard/command_examples.txt
  Packs/SecurityScorecard/ReleaseNotes/1_0_12.md
  Packs/SecurityScorecard/pack_metadata.json
Labels: Contribution, docs-approved, Partner, Contribution Form Filled, Partner Support Level, External PR, Partner-Approved

#38648 XSUP-46522 Adding support for new timestamp format
  Packs/Cisco_Wireless_LAN_Controller/ParsingRules/Cisco_Wireless_LAN_Controller/Cisco_Wireless_LAN_Controller.xif
  Packs/Cisco_Wireless_LAN_Controller/README.md
  Packs/Cisco_Wireless_LAN_Controller/ReleaseNotes/1_0_1.md
  Packs/Cisco_Wireless_LAN_Controller/pack_metadata.json
Labels: docs-approved, bypass.url

#38669 Show anuthorized forbidden error in test results
  Packs/NozomiNetworks/Integrations/NozomiNetworks/NozomiNetworks.py
  Packs/NozomiNetworks/Integrations/NozomiNetworks/NozomiNetworks_test.py
  Packs/NozomiNetworks/ReleaseNotes/1_0_17.md
  Packs/NozomiNetworks/pack_metadata.json
Labels: Contribution, docs-approved, Partner, Contribution Form Filled, pending-contributor, Partner Support Level, External PR, Partner-Approved

#38694 added continue on error
  Packs/CortexResponseAndRemediation/Playbooks/silent-playbook-SSO_Password_Spray_Test.yml
  Packs/CortexResponseAndRemediation/ReleaseNotes/1_1_12.md
  Packs/CortexResponseAndRemediation/pack_metadata.json
Labels: docs-approved

#38691 Improved performance of fetching alerts in the **proofpoint-tr-verify-quarantine** command.
  Packs/ProofpointThreatResponse/Integrations/ProofpointThreatResponse/ProofpointThreatResponse.py
  Packs/ProofpointThreatResponse/ReleaseNotes/2_0_23.md
  Packs/ProofpointThreatResponse/pack_metadata.json
Labels: docs-approved

#38703 Improve symantec ses event collector
  Packs/SymantecEndpointSecurity/Integrations/SymantecEndpointSecurity/SymantecEndpointSecurity.py
  Packs/SymantecEndpointSecurity/ReleaseNotes/1_0_2.md
  Packs/SymantecEndpointSecurity/pack_metadata.json
Labels: docs-approved

#38664 Fix Rasterize issue CIAC-12704
  Packs/rasterize/Integrations/rasterize/rasterize.py
  Packs/rasterize/Integrations/rasterize/rasterize.yml
  Packs/rasterize/Integrations/rasterize/rasterize_test.py
  Packs/rasterize/ReleaseNotes/2_0_37.md
  Packs/rasterize/pack_metadata.json
Labels: docs-approved

#38646 [ASM] - XSUP - Expander - Deprecate Reputation Commands
  Packs/CortexXpanse/Integrations/CortexXpanse/CortexXpanse.py
  Packs/CortexXpanse/Integrations/CortexXpanse/CortexXpanse.yml
  Packs/CortexXpanse/Integrations/CortexXpanse/CortexXpanse_test.py
  Packs/CortexXpanse/Integrations/CortexXpanse/README.md
  Packs/CortexXpanse/Integrations/CortexXpanse/test_data/expected_results.py
  Packs/CortexXpanse/Integrations/CortexXpanse/test_data/raw_response.py
  Packs/CortexXpanse/ReleaseNotes/1_2_7.json
  Packs/CortexXpanse/ReleaseNotes/1_2_7.md
  Packs/CortexXpanse/pack_metadata.json
Labels: Contribution, docs-approved, Contribution Form Filled, Community, pending-contributor, Xsoar Support Level, External PR

#38661 Elasticsearch v2 - Support the query_dsl parameter and proxy for client type elastic v8
  Packs/Elasticsearch/Integrations/Elasticsearch_v2/Elasticsearch_v2.py
  Packs/Elasticsearch/ReleaseNotes/1_3_28.md
  Packs/Elasticsearch/pack_metadata.json
Labels: docs-approved, ForceMerge

#38693 Fix UnboundLocalError when updating module health in Qualys VMDR 'fetch-assets' command
  Packs/qualys/Integrations/Qualysv2/Qualysv2.py
  Packs/qualys/Integrations/Qualysv2/Qualysv2_test.py
  Packs/qualys/ReleaseNotes/3_2_1.md
  Packs/qualys/pack_metadata.json
Labels: bug, docs-approved, python, ForceMerge

#38697 Update documentation for Pwsh Remoting
  Packs/PowershellRemoting/Integrations/PowerShellRemoting/PowerShellRemoting.yml
  Packs/PowershellRemoting/Integrations/PowerShellRemoting/README.md
  Packs/PowershellRemoting/ReleaseNotes/1_0_7.md
  Packs/PowershellRemoting/pack_metadata.json
Labels: docs-approved

#38609 'core-delete-incidents' return relevant data.
  Packs/DemistoRESTAPI/Integrations/CoreRESTAPI/CoreRESTAPI.js
  Packs/DemistoRESTAPI/Integrations/CoreRESTAPI/CoreRESTAPI.yml
  Packs/DemistoRESTAPI/Integrations/CoreRESTAPI/README.md
  Packs/DemistoRESTAPI/ReleaseNotes/1_3_66.json
  Packs/DemistoRESTAPI/ReleaseNotes/1_3_66.md
  Packs/DemistoRESTAPI/pack_metadata.json
Labels: ForceMerge

#38718 Add FiltersAndTransformers to platform corepacks list
  Config/core_packs_platform_list.json
Labels: docs-approved

#38714 bug - problem with parsing the timeout value in the script .yml
  Packs/Sigma/ReleaseNotes/1_0_2.md
  Packs/Sigma/Scripts/ImportSigmaRulesFromZIP/ImportSigmaRulesFromZIP.py
  Packs/Sigma/Scripts/ImportSigmaRulesFromZIP/ImportSigmaRulesFromZIP.yml
  Packs/Sigma/pack_metadata.json
Labels: docs-approved

#38502 Fix aiohttp auth
  Packs/Akamai_SIEM/Integrations/Akamai_SIEM/Akamai_SIEM.py
  Packs/Akamai_SIEM/Integrations/Akamai_SIEM/Akamai_SIEM_test.py
  Packs/Akamai_SIEM/ReleaseNotes/1_2_2.md
  Packs/Akamai_SIEM/pack_metadata.json
Labels: docs-approved

#38719 Fix panorama get jobs command
  Packs/PAN-OS/Integrations/Panorama/Panorama.py
  Packs/PAN-OS/Integrations/Panorama/Panorama.yml
  Packs/PAN-OS/Integrations/Panorama/Panorama_test.py
  Packs/PAN-OS/ReleaseNotes/2_3_5.md
  Packs/PAN-OS/pack_metadata.json
Labels: ForceMerge

#38733 Update onePassword logo
  Packs/OnePassword/Integrations/OnePassword/OnePassword_image.png
  Packs/OnePassword/ReleaseNotes/1_0_3.md
  Packs/OnePassword/pack_metadata.json
Labels: docs-approved

#38744 Ys proof remove test
  Packs/ProofpointEmailSecurity/Integrations/ProofpointEmailSecurityEventCollector/ProofpointEmailSecurityEventCollector.py
  Packs/ProofpointEmailSecurity/Integrations/ProofpointEmailSecurityEventCollector/ProofpointEmailSecurityEventCollector.yml
  Packs/ProofpointEmailSecurity/Integrations/ProofpointEmailSecurityEventCollector/README.md
  Packs/ProofpointEmailSecurity/ReleaseNotes/1_0_8.md
  Packs/ProofpointEmailSecurity/pack_metadata.json
Labels: docs-approved

#38204 Mandiant Enrich 1.1.5 RC
  Packs/MandiantAdvantageThreatIntelligence/Integrations/FeedMandiantThreatIntelligence/FeedMandiantThreatIntelligence.yml
  Packs/MandiantAdvantageThreatIntelligence/Integrations/Mandiant/Mandiant.py
  Packs/MandiantAdvantageThreatIntelligence/Integrations/Mandiant/Mandiant.yml
  Packs/MandiantAdvantageThreatIntelligence/Integrations/Mandiant/Mandiant_test.py
  Packs/MandiantAdvantageThreatIntelligence/ReleaseNotes/1_1_5.md
  Packs/MandiantAdvantageThreatIntelligence/pack_metadata.json
Labels: Contribution, docs-approved, Partner, Contribution Form Filled, pending-contributor, Partner Support Level, External PR, Partner-Approved

#38652 MISPFeed- Skipping indicator which have unsuitable tag_name
  Packs/FeedMISP/Integrations/FeedMISP/FeedMISP.py
  Packs/FeedMISP/Integrations/FeedMISP/FeedMISP.yml
  Packs/FeedMISP/Integrations/FeedMISP/FeedMISP_test.py
  Packs/FeedMISP/ReleaseNotes/1_0_39.md
  Packs/FeedMISP/pack_metadata.json
Labels: docs-approved

#38699 Updated the Attack Pattern indicator to save the pattern name in context under "Value" and not "value"
  Packs/CommonTypes/IndicatorTypes/reputation-Attack_PatternV2.json
  Packs/CommonTypes/ReleaseNotes/3_8_4.md
  Packs/CommonTypes/pack_metadata.json
  Packs/MalwareInvestigationAndResponse/ReleaseNotes/2_0_15.md
  Packs/MalwareInvestigationAndResponse/Scripts/InvestigationDetailedSummaryParse/InvestigationDetailedSummaryParse.py
  Packs/MalwareInvestigationAndResponse/Scripts/InvestigationDetailedSummaryParse/InvestigationDetailedSummaryParse.yml
  Packs/MalwareInvestigationAndResponse/pack_metadata.json
Labels: docs-approved

#38732 xsup-47233-Fixed an issue where ***splunk-job-create*** command added an 'search' string when not needed
  Packs/SplunkPy/Integrations/SplunkPy/SplunkPy.py
  Packs/SplunkPy/Integrations/SplunkPy/SplunkPy.yml
  Packs/SplunkPy/Integrations/SplunkPy/SplunkPy_test.py
  Packs/SplunkPy/ReleaseNotes/3_2_2.md
  Packs/SplunkPy/pack_metadata.json
Labels: docs-approved

#38458 Updated triggers to exclude correlation alerts
  Packs/CortexResponseAndRemediation/ReleaseNotes/1_1_13.md
  Packs/CortexResponseAndRemediation/Triggers/Suspicious_SaaS_Access_From_a_TOR_Exit_Node.json
  Packs/CortexResponseAndRemediation/Triggers/Trigger-_-A_user_executed_multiple_LDAP_enumeration_queries.json
  Packs/CortexResponseAndRemediation/Triggers/Trigger_-_A_mail_forwarding_rule_was_configured_in_Google_Workspace.json
  Packs/CortexResponseAndRemediation/Triggers/Trigger_-_A_successful_SSO_sign_in_from_TOR.json
  Packs/CortexResponseAndRemediation/Triggers/Trigger_-_A_successful_login_from_TOR.json
  Packs/CortexResponseAndRemediation/Triggers/Trigger_-_AppleScript_Process_Executed_With_Rare_Command_Line.json
  Packs/CortexResponseAndRemediation/Triggers/Trigger_-_Azure_AD_account_unlock_or_password_reset.json
  Packs/CortexResponseAndRemediation/Triggers/Trigger_-_Compromise_Accounts_-_User_rejected_numerous_SSO_MFA_attempts.json
  Packs/CortexResponseAndRemediation/Triggers/Trigger_-_Credential_Dumping_using_a_known_tool.json
  Packs/CortexResponseAndRemediation/Triggers/Trigger_-_Endpoint_initiated_uncommon_remote_scheduled_task_creation.json
  Packs/CortexResponseAndRemediation/Triggers/Trigger_-_Event_Log_Was_Cleared.json
  Packs/CortexResponseAndRemediation/Triggers/Trigger_-_Excessive_User_Account_Lockkouts.json
  Packs/CortexResponseAndRemediation/Triggers/Trigger_-_Exchange_User_Mailbox_Forwarding.json
  Packs/CortexResponseAndRemediation/Triggers/Trigger_-_Exchange_forwarding_rule_configured.json
  Packs/CortexResponseAndRemediation/Triggers/Trigger_-_External_Login_Password_Spray.json
  Packs/CortexResponseAndRemediation/Triggers/Trigger_-_Msiexec_execution_of_an_executable_from_an_uncommon_remote_location.json
  Packs/CortexResponseAndRemediation/Triggers/Trigger_-_Office_process_creates_a_scheduled_task_via_file_access.json
  Packs/CortexResponseAndRemediation/Triggers/Trigger_-_Remote_WMI_Process_Execution.json
  Packs/CortexResponseAndRemediation/Triggers/Trigger_-_SSO_Authentication_With_Suspicious_Characteristics.json
  Packs/CortexResponseAndRemediation/Triggers/Trigger_-_SSO_Brute_Force.json
  Packs/CortexResponseAndRemediation/Triggers/Trigger_-_SSO_Brute_Force_Activity.json
  Packs/CortexResponseAndRemediation/Triggers/Trigger_-_SSO_Password_Spray.json
  Packs/CortexResponseAndRemediation/Triggers/Trigger_-_Scheduled_task_created_with_HTTP_or_FTP_reference.json
  Packs/CortexResponseAndRemediation/Triggers/Trigger_-_Successful_guest_user_invitation.json
  Packs/CortexResponseAndRemediation/Triggers/Trigger_-_Suspicious_Hidden_User_Created.json
  Packs/CortexResponseAndRemediation/Triggers/Trigger_-_Suspicious_LDAP_search_query.json
  Packs/CortexResponseAndRemediation/Triggers/Trigger_-_Suspicious_Local_Administrator_Login.json
  Packs/CortexResponseAndRemediation/Triggers/Trigger_-_Suspicious_access_to_shadow_file.json
  Packs/CortexResponseAndRemediation/Triggers/Trigger_-_Suspicious_certutil_command_line.json
  Packs/CortexResponseAndRemediation/Triggers/Trigger_-_Suspicious_process_execution_by_scheduled_task_on_a_sensitive_server.json
  Packs/CortexResponseAndRemediation/Triggers/Trigger_-_Uncommon_remote_scheduled_task_created.json
  Packs/CortexResponseAndRemediation/Triggers/Trigger_-_Unprivileged_process_opened_a_registry_hive.json
  Packs/CortexResponseAndRemediation/Triggers/Trigger_-_Unsigned_and_unpopular_process_performed_an_injection.json
  Packs/CortexResponseAndRemediation/Triggers/Trigger_-_Unusual_process_accessed_web_browser_credentials_and_executed_by_a_terminal_process.json
  Packs/CortexResponseAndRemediation/Triggers/Trigger_-_User_added_to_local_administrator_group_using_a_PowerShell_command.json
  Packs/CortexResponseAndRemediation/pack_metadata.json
Labels: docs-approved

#38728 Add silent playbook - Intense SSO Failures
  Packs/CortexResponseAndRemediation/.pack-ignore
  Packs/CortexResponseAndRemediation/Playbooks/silent-playbook_Intense_SSO_failures_with_suspicious_characteristics.yml
  Packs/CortexResponseAndRemediation/ReleaseNotes/1_1_14.md
  Packs/CortexResponseAndRemediation/Triggers/silent-Trigger_-_Intense_SSO_failures_with_suspicious_characteristics.json
  Packs/CortexResponseAndRemediation/pack_metadata.json
Labels: docs-approved

#38662 Whois ***domain*** command throws an error
  Packs/Whois/Integrations/Whois/Whois.py
  Packs/Whois/Integrations/Whois/Whois.yml
  Packs/Whois/Integrations/Whois/Whois_test.py
  Packs/Whois/ReleaseNotes/1_5_24.md
  Packs/Whois/pack_metadata.json
Labels: docs-approved, ForceMerge

#38723 CreateIndicatorRelationship fixed by batching requests
  Packs/Base/ReleaseNotes/1_39_21.md
  Packs/Base/Scripts/CreateIndicatorRelationship/CreateIndicatorRelationship.py
  Packs/Base/Scripts/CreateIndicatorRelationship/CreateIndicatorRelationship.yml
  Packs/Base/pack_metadata.json
Labels: ForceMerge

#38698 Fix:Remove tags from indicator
  Packs/CTIX/Integrations/CTIXv3/CTIXv3.py
  Packs/CTIX/Integrations/CTIXv3/CTIXv3.yml
  Packs/CTIX/Integrations/CTIXv3/CTIXv3_test.py
  Packs/CTIX/ReleaseNotes/2_2_18.md
  Packs/CTIX/pack_metadata.json
Labels: Contribution, docs-approved, Partner, Contribution Form Filled, Partner Support Level, External PR, Partner-Approved

#38759 Fix_uncommon_odbcconf_playbook
  Packs/CortexResponseAndRemediation/Playbooks/playbook-Uncommon_execution_of_ODBCConf.yml
  Packs/CortexResponseAndRemediation/ReleaseNotes/1_1_15.md
  Packs/CortexResponseAndRemediation/doc_files/Uncommon_execution_of_ODBCConf.png
  Packs/CortexResponseAndRemediation/pack_metadata.json
Labels: docs-approved

#38758 Fix setting new last assets run with halved limit in Qualys VMDR
  Packs/qualys/Integrations/Qualysv2/Qualysv2.py
  Packs/qualys/Integrations/Qualysv2/Qualysv2_test.py
  Packs/qualys/ReleaseNotes/3_2_2.md
  Packs/qualys/pack_metadata.json
Labels: bug, docs-approved, python

#38774 Fix:Remove tags from indicator (#38698)
  Packs/CTIX/Integrations/CTIXv3/CTIXv3.py
  Packs/CTIX/Integrations/CTIXv3/CTIXv3.yml
  Packs/CTIX/Integrations/CTIXv3/CTIXv3_test.py
  Packs/CTIX/ReleaseNotes/2_2_18.md
  Packs/CTIX/pack_metadata.json
Labels: docs-approved

#38708 [VirusTotal] Private URL scanning
  Packs/VirusTotal/Integrations/VirusTotalV3/README.md
  Packs/VirusTotal/Integrations/VirusTotalV3/VirusTotalV3.py
  Packs/VirusTotal/Integrations/VirusTotalV3/VirusTotalV3.yml
  Packs/VirusTotal/Integrations/VirusTotalV3/VirusTotalV3_test.py
  Packs/VirusTotal/Integrations/VirusTotalV3/test_data/private_url.json
  Packs/VirusTotal/Integrations/VirusTotalV3/test_data/private_url_results.json
  Packs/VirusTotal/ReleaseNotes/2_7_0.md
  Packs/VirusTotal/pack_metadata.json
Labels: Contribution, Partner, pending-demo, post-demo, Contribution Form Filled, pending-contributor, Partner Support Level, External PR, Partner-Approved

#38776 fixed an issue where auto offset reset didnt work for Akamai_SIEM
  Packs/Akamai_SIEM/Integrations/Akamai_SIEM/Akamai_SIEM.py
  Packs/Akamai_SIEM/ReleaseNotes/1_2_3.md
  Packs/Akamai_SIEM/pack_metadata.json
Labels: docs-approved

#38550 Ciac 11100 test use case
  Packs/CommonPlaybooks/Playbooks/playbook-Containment_Plan.yml
  Packs/CommonPlaybooks/ReleaseNotes/2_6_52.md
  Packs/CommonPlaybooks/pack_metadata.json
Labels: docs-approved

#38424 Feature: KafkaV3 Schema Registry and AVRO support
  Packs/Kafka/CONTRIBUTORS.json
  Packs/Kafka/Integrations/KafkaV3/KafkaV3.py
  Packs/Kafka/Integrations/KafkaV3/KafkaV3.yml
  Packs/Kafka/Integrations/KafkaV3/KafkaV3_description.md
  Packs/Kafka/Integrations/KafkaV3/KafkaV3_test.py
  Packs/Kafka/Integrations/KafkaV3/README.md
  Packs/Kafka/Integrations/Kafka_V2/Kafka_V2.yml
  Packs/Kafka/README.md
  Packs/Kafka/ReleaseNotes/2_1_0.md
  Packs/Kafka/pack_metadata.json
Labels: Contribution, docs-approved, Contribution Form Filled, Community, Xsoar Support Level, External PR

#38780 Add tag info to Feed RSS playbook docs
  Packs/FeedRSS/.pack-ignore
  Packs/FeedRSS/Playbooks/RSS_Create_Indicators_From_Report_README.md
  Packs/FeedRSS/ReleaseNotes/1_0_17.md
  Packs/FeedRSS/pack_metadata.json
Labels: docs-approved

#38647 Feature: add additional_filters to searchable commands
  Packs/OpenCTI/Integrations/OpenCTI/OpenCTI.py
  Packs/OpenCTI/Integrations/OpenCTI/OpenCTI.yml
  Packs/OpenCTI/Integrations/OpenCTI/OpenCTI_test.py
  Packs/OpenCTI/Integrations/OpenCTI/README.md
  Packs/OpenCTI/ReleaseNotes/2_0_1.md
  Packs/OpenCTI/pack_metadata.json
Labels: Contribution, docs-approved, Contribution Form Filled, Community, Xsoar Support Level, External PR

#38675 Add error handling method to GetFailedTasks output
  Packs/IntegrationsAndIncidentsHealthCheck/CONTRIBUTORS.json
  Packs/IntegrationsAndIncidentsHealthCheck/ReleaseNotes/1_3_30.md
  Packs/IntegrationsAndIncidentsHealthCheck/Scripts/GetFailedTasks/GetFailedTasks.py
  Packs/IntegrationsAndIncidentsHealthCheck/Scripts/GetFailedTasks/GetFailedTasks.yml
  Packs/IntegrationsAndIncidentsHealthCheck/Scripts/GetFailedTasks/GetFailedTasks_test.py
  Packs/IntegrationsAndIncidentsHealthCheck/Scripts/GetFailedTasks/test_data/constants.py
  Packs/IntegrationsAndIncidentsHealthCheck/pack_metadata.json
Labels: Contribution, docs-approved, Contribution Form Filled, Community, Xsoar Support Level, External PR

#38787 Guest playbook close reason fix
  Packs/CortexResponseAndRemediation/Playbooks/playbook-Successful_guest_user_invitation.yml
  Packs/CortexResponseAndRemediation/ReleaseNotes/1_1_16.md
  Packs/CortexResponseAndRemediation/pack_metadata.json
Labels: docs-approved

#38796 SplunkPy - Fixed a Mirror In issue (XSUP-43248)
  Packs/SplunkPy/Integrations/SplunkPy/SplunkPy.py
  Packs/SplunkPy/ReleaseNotes/3_2_3.md
  Packs/SplunkPy/pack_metadata.json
Labels: docs-approved

#38710 Cisco nexus parsing modification
  Packs/CiscoNexus/ParsingRules/CiscoNexus_1_3/CiscoNexus_1_3.xif
  Packs/CiscoNexus/README.md
  Packs/CiscoNexus/ReleaseNotes/1_0_2.md
  Packs/CiscoNexus/pack_metadata.json
Labels: docs-approved, bypass.url
