Repository demisto/content, pull requests merged in 2025-04, with the labels that each got.

#39345 Fix akamai offset url encode issue
  Packs/Akamai_SIEM/Integrations/Akamai_SIEM/Akamai_SIEM.py
  Packs/Akamai_SIEM/Integrations/Akamai_SIEM/Akamai_SIEM_test.py
  Packs/Akamai_SIEM/ReleaseNotes/1_2_7.md
  Packs/Akamai_SIEM/pack_metadata.json
Labels: docs-approved

#38871 Restored XSIAM part reverted on previous version (1.0.2).
  Packs/Veeam/README.md
  Packs/Veeam/ReleaseNotes/1_0_9.md
  Packs/Veeam/XSIAMDashboards/Veeam_Data_Platform_Monitoring_Dashboard.json
  Packs/Veeam/XSIAMDashboards/Veeam_Data_Platform_Monitoring_Dashboard_image.png
  Packs/Veeam/XSIAMDashboards/Veeam_Security_Activities_Dashboard.json
  Packs/Veeam/XSIAMDashboards/Veeam_Security_Activities_Dashboard_image.png
  Packs/Veeam/XSIAMReports/Veeam_All_Veeam_failed_multi-factor_authentication_events_for_the_last_24h.json
  Packs/Veeam/XSIAMReports/Veeam_All_Veeam_failed_multi-factor_authentication_events_for_the_last_24h_image.png
  Packs/Veeam/XSIAMReports/Veeam_All_Veeam_finished_jobs_for_the_last_24h.json
  Packs/Veeam/XSIAMReports/Veeam_All_Veeam_finished_jobs_for_the_last_24h_image.png
  Packs/Veeam/XSIAMReports/Veeam_All_Veeam_four-eyes_authorization_events_for_the_last_24h.json
  Packs/Veeam/XSIAMReports/Veeam_All_Veeam_four-eyes_authorization_events_for_the_last_24h_image.png
  Packs/Veeam/XSIAMReports/Veeam_All_Veeam_malware_detection_events_for_the_last_24h.json
  Packs/Veeam/XSIAMReports/Veeam_All_Veeam_malware_detection_events_for_the_last_24h_image.png
  Packs/Veeam/XSIAMReports/Veeam_All_Veeam_security_events_for_the_last_7_days.json
  Packs/Veeam/XSIAMReports/Veeam_All_Veeam_security_events_for_the_last_7_days_image.png
  Packs/Veeam/XSIAMReports/Veeam_All_Veeam_security_events_with_Critical_and_High_severity_for_the_last_24h.json
  Packs/Veeam/XSIAMReports/Veeam_All_Veeam_security_events_with_Critical_and_High_severity_for_the_last_24h_image.png
  Packs/Veeam/XSIAMReports/Veeam_All_Veeam_triggered_alarms_for_the_last_7_days.json
  Packs/Veeam/XSIAMReports/Veeam_All_Veeam_triggered_alarms_for_the_last_7_days_image.png
  Packs/Veeam/pack_metadata.json
Labels: Contribution, docs-approved, Partner, Contribution Form Filled, pending-contributor, Partner Support Level, External PR, Partner-Approved, chosen-machine-xsiam-eyal_test

#39375 [on-call] Update on-call developers
  .github/content_roles.json
Labels: docs-approved, docker

#38629 xsup-46835: Updated the ***fetch-incidents*** command to not take in count the default *limit* argument.
  Packs/Mimecast/Integrations/MimecastV2/MimecastV2.py
  Packs/Mimecast/Integrations/MimecastV2/MimecastV2.yml
  Packs/Mimecast/Integrations/MimecastV2/MimecastV2_test.py
  Packs/Mimecast/ReleaseNotes/2_5_7.json
  Packs/Mimecast/ReleaseNotes/2_5_7.md
  Packs/Mimecast/pack_metadata.json
Labels: docs-approved

#38940 Malop API change
  Packs/Cybereason/Integrations/Cybereason/Cybereason.py
  Packs/Cybereason/Integrations/Cybereason/Cybereason.yml
  Packs/Cybereason/Integrations/Cybereason/Cybereason_test.py
  Packs/Cybereason/Integrations/Cybereason/README.md
  Packs/Cybereason/ReleaseNotes/2_1_23.md
  Packs/Cybereason/Scripts/CybereasonPreProcessingExample/CybereasonPreProcessingExample.py
  Packs/Cybereason/Scripts/CybereasonPreProcessingExample/CybereasonPreProcessingExample.yml
  Packs/Cybereason/pack_metadata.json
Labels: Contribution, docs-approved, Partner, Contribution Form Filled, Partner Support Level, External PR, Partner-Approved

#39318 Added a sorting setting and performance improvement settings.
  Packs/XQLDSHelper/ReleaseNotes/1_0_4.md
  Packs/XQLDSHelper/Scripts/XQLDSHelper/README.md
  Packs/XQLDSHelper/Scripts/XQLDSHelper/XQLDSHelper.py
  Packs/XQLDSHelper/Scripts/XQLDSHelper/XQLDSHelper_test.py
  Packs/XQLDSHelper/Scripts/XQLDSHelper/test_data/qr_endpoint_alert_count_by_device.json
  Packs/XQLDSHelper/Scripts/XQLDSHelper/test_data/test-entry-types.json
  Packs/XQLDSHelper/Scripts/XQLDSHelper/test_data/test-others.json
  Packs/XQLDSHelper/pack_metadata.json
Labels: Contribution, docs-approved, Contribution Form Filled, Community, Community Support Level, External PR

#39266 Ms teams remove chat list write permission requirement
  Packs/MicrosoftTeams/Integrations/MicrosoftTeams/MicrosoftTeams.py
  Packs/MicrosoftTeams/Integrations/MicrosoftTeams/MicrosoftTeams.yml
  Packs/MicrosoftTeams/Integrations/MicrosoftTeams/MicrosoftTeams_test.py
  Packs/MicrosoftTeams/Integrations/MicrosoftTeams/README.md
  Packs/MicrosoftTeams/Integrations/MicrosoftTeams/test_data/chats_test_data.json
  Packs/MicrosoftTeams/ReleaseNotes/1_5_21.json
  Packs/MicrosoftTeams/ReleaseNotes/1_5_21.md
  Packs/MicrosoftTeams/pack_metadata.json
Labels: docs-approved

#39380 Revert hash function changes
  Packs/Darktrace/Integrations/DarktraceEventCollector/DarktraceEventCollector.py
  Packs/Darktrace/Integrations/DarktraceMBs/DarktraceMBs.py
  Packs/Darktrace/Integrations/DarktraceMBs/DarktraceMBs.yml
  Packs/Darktrace/ReleaseNotes/3_0_17.md
  Packs/Darktrace/pack_metadata.json
  Packs/Troubleshoot/ReleaseNotes/2_1_9.md
  Packs/Troubleshoot/Scripts/CertificatesTroubleshoot/CertificatesTroubleshoot.py
  Packs/Troubleshoot/Scripts/CertificatesTroubleshoot/CertificatesTroubleshoot.yml
  Packs/Troubleshoot/pack_metadata.json
  Packs/remedy_SR/Integrations/remedy_SR/remedy_SR.py
  Packs/remedy_SR/Integrations/remedy_SR/remedy_SR.yml
  Packs/remedy_SR/ReleaseNotes/1_0_17.md
  Packs/remedy_SR/pack_metadata.json
Labels: docs-approved

#39271 Enhancement/cloudflare waf ciac 10062
  Packs/CloudflareWAF/Integrations/CloudflareWAF/CloudflareWAF.py
  Packs/CloudflareWAF/Integrations/CloudflareWAF/CloudflareWAF.yml
  Packs/CloudflareWAF/Integrations/CloudflareWAF/CloudflareWAF_description.md
  Packs/CloudflareWAF/Integrations/CloudflareWAF/CloudflareWAF_test.py
  Packs/CloudflareWAF/Integrations/CloudflareWAF/README.md
  Packs/CloudflareWAF/ReleaseNotes/1_0_27.md
  Packs/CloudflareWAF/pack_metadata.json
Labels: docs-approved

#39349 SanePdfReport - update the docker
  Packs/Base/ReleaseNotes/1_39_24.md
  Packs/Base/Scripts/SanePdfReport/SanePdfReport.yml
  Packs/Base/pack_metadata.json
Labels: docs-approved

#39340 Crtx 149612 srx
  Packs/JuniperSRX/ModelingRules/JuniperSRX_1_3/JuniperSRX_1_3.xif
  Packs/JuniperSRX/ParsingRules/JuniperSRX/JuniperSRX.xif
  Packs/JuniperSRX/README.md
  Packs/JuniperSRX/ReleaseNotes/1_0_13.md
  Packs/JuniperSRX/pack_metadata.json
Labels: docs-approved, bypass.url

#39101 Silent - Azure AD PIM role settings change
  Packs/CortexResponseAndRemediation/Playbooks/silent-playbook-Azure_AD_PIM_role_settings_change.yml
  Packs/CortexResponseAndRemediation/ReleaseNotes/1_1_30.md
  Packs/CortexResponseAndRemediation/Triggers/silent-Trigger-_-Azure_AD_PIM_role_settings_change.json
  Packs/CortexResponseAndRemediation/pack_metadata.json
Labels: docs-approved

#39376 OpenCTI revert docker due to bug
  Packs/OpenCTI/Integrations/OpenCTI/OpenCTI.yml
  Packs/OpenCTI/Integrations/OpenCTI/command_examples.txt
  Packs/OpenCTI/ReleaseNotes/2_0_4.md
  Packs/OpenCTI/pack_metadata.json
Labels: ForceMerge

#38876 Add command to query GP logs to SLS integration
  Packs/CortexDataLake/Integrations/CortexDataLake/CortexDataLake.py
  Packs/CortexDataLake/Integrations/CortexDataLake/CortexDataLake.yml
  Packs/CortexDataLake/Integrations/CortexDataLake/CortexDataLake_test.py
  Packs/CortexDataLake/Integrations/CortexDataLake/README.md
  Packs/CortexDataLake/Integrations/CortexDataLake/command_examples.txt
  Packs/CortexDataLake/Integrations/CortexDataLake/test_data/test_query_logs_command_transform_results_gp_logs.json
  Packs/CortexDataLake/Integrations/CortexDataLake/test_data/test_query_logs_command_transform_results_gp_logs_xformed.json
  Packs/CortexDataLake/ReleaseNotes/1_4_18.md
  Packs/CortexDataLake/pack_metadata.json
Labels: Contribution, docs-approved, Contribution Form Filled, Community, Xsoar Support Level, External PR

#39408 Feature: MongoDB add auth source connection param
  Packs/MongoDB/CONTRIBUTORS.json
  Packs/MongoDB/Integrations/MongoDB/MongoDB.py
  Packs/MongoDB/Integrations/MongoDB/MongoDB.yml
  Packs/MongoDB/ReleaseNotes/1_4_0.md
  Packs/MongoDB/pack_metadata.json
Labels: Contribution, Contribution Form Filled, Community, Xsoar Support Level, External PR

#39358 Fix Qualys issue XSUP-48766
  Packs/qualys/Integrations/Qualysv2/Qualysv2.py
  Packs/qualys/ReleaseNotes/3_2_7.md
  Packs/qualys/pack_metadata.json
Labels: docs-approved

#38548 Github Actions: update to use py 3.10
  .github/workflows/autobump_rn.yml
  .github/workflows/check-contribution-form-filled.yml
  .github/workflows/check-contributor-pack.yml
  .github/workflows/check-partner-approved-label.yml
  .github/workflows/close_jira_issue_by_pr_merge.yml
  .github/workflows/create-internal-pr-from-external.yml
  .github/workflows/handle-new-external-pr.yml
  .github/workflows/link_edited_pr_to_jira_issue.yml
  .github/workflows/review-release-notes.yml
  .github/workflows/run-secrets-detection.yml
  .github/workflows/sync-contribution-base-branch-on-change.yml
  .github/workflows/sync-contribution-base-branch.yml
  .github/workflows/update-demisto-sdk-version.yml
  poetry.lock
  pyproject.toml
Labels: docs-approved

#39427 Bump Base,DemistoRESTAPI,FiltersAndTransformers packs
  Packs/Base/ReleaseNotes/1_39_25.md
  Packs/Base/pack_metadata.json
  Packs/DemistoRESTAPI/ReleaseNotes/1_3_70.md
  Packs/DemistoRESTAPI/pack_metadata.json
  Packs/FiltersAndTransformers/ReleaseNotes/1_2_92.md
  Packs/FiltersAndTransformers/pack_metadata.json
Labels: docs-approved, ForceMerge, bypass.url

#39361 Azure Devops
  Packs/AzureDevOps/ModelingRules/AzureDevOps/AzureDevOps.xif
  Packs/AzureDevOps/ModelingRules/AzureDevOps/AzureDevOps.yml
  Packs/AzureDevOps/ModelingRules/AzureDevOps/AzureDevOps_schema.json
  Packs/AzureDevOps/ParsingRules/AzureDevOps/AzureDevOps.xif
  Packs/AzureDevOps/ParsingRules/AzureDevOps/AzureDevOps.yml
  Packs/AzureDevOps/README.md
  Packs/AzureDevOps/ReleaseNotes/1_4_8.md
  Packs/AzureDevOps/pack_metadata.json
  Packs/MicrosoftEntraID/ModelingRules/MicrosoftEntraID/MicrosoftEntraID_schema.json
  Packs/MicrosoftEntraID/ParsingRules/MicrosoftEntraID/MicrosoftEntraID.xif
  Packs/MicrosoftEntraID/ReleaseNotes/1_0_11.md
  Packs/MicrosoftEntraID/pack_metadata.json
Labels: docs-approved, bypass.url

#39429 Bump Image OCR
  Packs/ImageOCR/ReleaseNotes/1_1_38.md
  Packs/ImageOCR/pack_metadata.json
Labels: docs-approved, ForceMerge, bypass.url

#39410 Update Rasterize Integration to Exclude 0.0.0.0/8 and 127.0.0.0/8 CIDR Ranges
  Packs/rasterize/Integrations/rasterize/rasterize.py
  Packs/rasterize/Integrations/rasterize/rasterize_test.py
  Packs/rasterize/ReleaseNotes/2_1_0.md
  Packs/rasterize/pack_metadata.json
Labels: docs-approved

#39343 Crtx 122165 lenel s2 net box
  Packs/LenelS2NetBox/.pack-ignore
  Packs/LenelS2NetBox/.secrets-ignore
  Packs/LenelS2NetBox/ModelingRules/LenelS2NetBox/LenelS2NetBox.xif
  Packs/LenelS2NetBox/ModelingRules/LenelS2NetBox/LenelS2NetBox.yml
  Packs/LenelS2NetBox/ModelingRules/LenelS2NetBox/LenelS2NetBox_schema.json
  Packs/LenelS2NetBox/ParsingRules/LenelS2NetBox/LenelS2NetBox.xif
  Packs/LenelS2NetBox/ParsingRules/LenelS2NetBox/LenelS2NetBox.yml
  Packs/LenelS2NetBox/README.md
  Packs/LenelS2NetBox/pack_metadata.json
Labels: docs-approved, bypass.url

#39321 Rasterize: Add Retry Mechanism For Chrome Errors During Rasterization
  Packs/rasterize/Integrations/rasterize/rasterize.py
  Packs/rasterize/Integrations/rasterize/rasterize_test.py
  Packs/rasterize/ReleaseNotes/2_1_1.md
  Packs/rasterize/pack_metadata.json
  Tests/conf.json
Labels: docs-approved

#39033 TIM - Extracting URLs with complex numerical IPs
  Packs/ApiModules/Scripts/FormatURLApiModule/FormatURLApiModule.py
  Packs/ApiModules/Scripts/FormatURLApiModule/FormatURLApiModule_test.py
  Packs/Base/.secrets-ignore
  Packs/Base/TestPlaybooks/playbook-URLextraction-Test.yml
  Packs/CommonScripts/ReleaseNotes/1_19_39.md
  Packs/CommonScripts/pack_metadata.json
  Packs/CommonTypes/IndicatorTypes/reputation-url.json
  Packs/CommonTypes/ReleaseNotes/3_8_7.md
  Packs/CommonTypes/pack_metadata.json
  Packs/Phishing/ReleaseNotes/3_7_2.md
  Packs/Phishing/pack_metadata.json
Labels: docs-approved

#39441 Bump Zoom version
  Packs/Zoom/ReleaseNotes/1_6_27.md
  Packs/Zoom/pack_metadata.json
Labels: docs-approved

#39315 Fix handling of special characters when updating and creating records in RSA Archer V2
  Packs/ArcherRSA/Integrations/ArcherV2/ArcherV2.py
  Packs/ArcherRSA/Integrations/ArcherV2/ArcherV2.yml
  Packs/ArcherRSA/Integrations/ArcherV2/ArcherV2_test.py
  Packs/ArcherRSA/Integrations/ArcherV2/README.md
  Packs/ArcherRSA/ReleaseNotes/1_3_2.md
  Packs/ArcherRSA/pack_metadata.json
Labels: bug, docs-approved, python

#39302 Conditional_Access_Playbook
  Packs/CommonScripts/ReleaseNotes/1_19_40.md
  Packs/CommonScripts/Scripts/JSONDiff/JSONDiff.py
  Packs/CommonScripts/Scripts/JSONDiff/JSONDiff.yml
  Packs/CommonScripts/Scripts/JSONDiff/JSONDiff_test.py
  Packs/CommonScripts/Scripts/JSONDiff/README.md
  Packs/CommonScripts/pack_metadata.json
  Packs/CortexResponseAndRemediation/Playbooks/silent-playbook-Suspicious_Conditional_Access_operation_for_an_identity.yml
  Packs/CortexResponseAndRemediation/ReleaseNotes/1_1_31.md
  Packs/CortexResponseAndRemediation/Triggers/silent-Trigger_-_Suspicious_Conditional_Access_operation_for_an_identity.json
  Packs/CortexResponseAndRemediation/pack_metadata.json
Labels: docs-approved

#39415 Fix boolean arguments sent as false when not provided in the command line
  Packs/CheckPointHEC/Integrations/CheckPointHEC/CheckPointHEC.py
  Packs/CheckPointHEC/Integrations/CheckPointHEC/CheckPointHEC.yml
  Packs/CheckPointHEC/Integrations/CheckPointHEC/README.md
  Packs/CheckPointHEC/ReleaseNotes/1_1_9.md
  Packs/CheckPointHEC/pack_metadata.json
Labels: Contribution, Partner, Contribution Form Filled, Partner Support Level, External PR, Partner-Approved

#38960 Enhanced the behavior of the *Should Error When Not Found* parameter to handle errors with status code 504 and 502
  Packs/AlienVault_OTX/Integrations/AlienVault_OTX_v2/AlienVault_OTX_v2.py
  Packs/AlienVault_OTX/Integrations/AlienVault_OTX_v2/AlienVault_OTX_v2_test.py
  Packs/AlienVault_OTX/ReleaseNotes/1_1_46.md
  Packs/AlienVault_OTX/pack_metadata.json
Labels: docs-approved

#39432 XQLDSHelper - Added extended variables to help create URL links for the XQL builder.
  Packs/XQLDSHelper/ReleaseNotes/1_0_5.md
  Packs/XQLDSHelper/Scripts/XQLDSHelper/README.md
  Packs/XQLDSHelper/Scripts/XQLDSHelper/XQLDSHelper.py
  Packs/XQLDSHelper/Scripts/XQLDSHelper/test_data/test-others.json
  Packs/XQLDSHelper/pack_metadata.json
Labels: Contribution, Contribution Form Filled, Community, Community Support Level, External PR

#39336 ExportAuditLogsToFile-Fix-pagination
  Packs/CommonScripts/ReleaseNotes/1_19_41.md
  Packs/CommonScripts/Scripts/ExportAuditLogsToFile/ExportAuditLogsToFile.py
  Packs/CommonScripts/Scripts/ExportAuditLogsToFile/ExportAuditLogsToFile.yml
  Packs/CommonScripts/pack_metadata.json
Labels: docs-approved

#39392 Ms teams ring user in authcode
  Packs/MicrosoftTeams/Integrations/MicrosoftTeams/MicrosoftTeams.py
  Packs/MicrosoftTeams/Integrations/MicrosoftTeams/MicrosoftTeams_description.md
  Packs/MicrosoftTeams/Integrations/MicrosoftTeams/MicrosoftTeams_test.py
  Packs/MicrosoftTeams/Integrations/MicrosoftTeams/README.md
  Packs/MicrosoftTeams/ReleaseNotes/1_5_22.md
  Packs/MicrosoftTeams/pack_metadata.json
Labels: docs-approved

#39443 CRTX-157287-nasuni-file-services
  Packs/NasuniFileServices/.pack-ignore
  Packs/NasuniFileServices/.secrets-ignore
  Packs/NasuniFileServices/ModelingRules/NasuniFileServices/NasuniFileServices.xif
  Packs/NasuniFileServices/ModelingRules/NasuniFileServices/NasuniFileServices.yml
  Packs/NasuniFileServices/ModelingRules/NasuniFileServices/NasuniFileServices_schema.json
  Packs/NasuniFileServices/ParsingRules/NasuniFileServices/NasuniFileServices.xif
  Packs/NasuniFileServices/ParsingRules/NasuniFileServices/NasuniFileServices.yml
  Packs/NasuniFileServices/README.md
  Packs/NasuniFileServices/pack_metadata.json
Labels: docs-approved, bypass.url

#39482 HW event collector - adding logs
  Packs/HelloWorld/Integrations/HelloWorldEventCollector/HelloWorldEventCollector.py
  Packs/HelloWorld/ReleaseNotes/3_0_19.md
  Packs/HelloWorld/pack_metadata.json
Labels: docs-approved

#39460 CRTX-166108-Kiteworks
  Packs/Kiteworks/ModelingRules/Kiteworks/Kiteworks.xif
  Packs/Kiteworks/ReleaseNotes/1_0_2.md
  Packs/Kiteworks/pack_metadata.json
Labels: docs-approved, bypass.url

#39498 [on-call] bump packs
  Packs/CommonReports/ReleaseNotes/1_0_10.md
  Packs/CommonReports/pack_metadata.json
  Packs/DefaultPlaybook/ReleaseNotes/2_0_13.md
  Packs/DefaultPlaybook/pack_metadata.json
  Packs/TIM_Processing/ReleaseNotes/1_1_28.md
  Packs/TIM_Processing/pack_metadata.json
  Packs/TIM_SIEM/ReleaseNotes/1_1_7.md
  Packs/TIM_SIEM/pack_metadata.json
Labels: docs-approved, ForceMerge, bypass.url

#38761 Fixed an issue where mirror-out took precedence over mirror-in, resulting in the removal of values in SNOW.
  Packs/ServiceNow/Integrations/ServiceNowv2/ServiceNowv2.py
  Packs/ServiceNow/Integrations/ServiceNowv2/ServiceNowv2_test.py
  Packs/ServiceNow/ReleaseNotes/2_7_12.md
  Packs/ServiceNow/pack_metadata.json
Labels: docs-approved

#39395 Add to secret ignore
  Packs/GroupIB_ThreatIntelligenceAttribution/.secrets-ignore
Labels: docs-approved

#39385 Suspicious user access to multiple resources
  Packs/CortexResponseAndRemediation/.pack-ignore
  Packs/CortexResponseAndRemediation/Playbooks/silent-playbook-Suspicious_user_access_to_multiple_resources_via_SSO.yml
  Packs/CortexResponseAndRemediation/ReleaseNotes/1_1_32.md
  Packs/CortexResponseAndRemediation/pack_metadata.json
Labels: docs-approved

#39501 Fix secret ignore
  Packs/GroupIB_ThreatIntelligenceAttribution/.secrets-ignore
Labels: docs-approved

#39407 MS Teams - Fixed an issue in the add_bot_to_chat function
  Packs/MicrosoftTeams/Integrations/MicrosoftTeams/MicrosoftTeams.py
  Packs/MicrosoftTeams/Integrations/MicrosoftTeams/MicrosoftTeams.yml
  Packs/MicrosoftTeams/Integrations/MicrosoftTeams/README.md
  Packs/MicrosoftTeams/ReleaseNotes/1_5_23.md
  Packs/MicrosoftTeams/pack_metadata.json
Labels: docs-approved

#39445 New playbook: A user deleted multiple users for the first time
  Packs/CortexResponseAndRemediation/Playbooks/silent-playbook-A_user_deleted_multiple_users_for_the_first_time.yml
  Packs/CortexResponseAndRemediation/ReleaseNotes/1_1_33.md
  Packs/CortexResponseAndRemediation/Triggers/silent-Trigger-_-A_user_deleted_multiple_users_for_the_first_time.json
  Packs/CortexResponseAndRemediation/pack_metadata.json
Labels: docs-approved

#39344 Azure WAF Enhancement
  Packs/AzureWAF/ModelingRules/AzureWAF/AzureWAF.xif
  Packs/AzureWAF/ModelingRules/AzureWAF/AzureWAF_schema.json
  Packs/AzureWAF/ParsingRules/AzureWAF/AzureWAF.xif
  Packs/AzureWAF/README.md
  Packs/AzureWAF/ReleaseNotes/1_2_8.md
  Packs/AzureWAF/pack_metadata.json
  Packs/MicrosoftEntraID/ParsingRules/MicrosoftEntraID/MicrosoftEntraID.xif
  Packs/MicrosoftEntraID/ReleaseNotes/1_0_12.md
  Packs/MicrosoftEntraID/pack_metadata.json
Labels: docs-approved, bypass.url

#39496 Google apigee modeling rules - CRTX 159730
  Packs/GoogleApigee/ModelingRules/GoogleApigee/GoogleApigee.xif
  Packs/GoogleApigee/ModelingRules/GoogleApigee/GoogleApigee.yml
  Packs/GoogleApigee/ModelingRules/GoogleApigee/GoogleApigee_schema.json
  Packs/GoogleApigee/README.md
  Packs/GoogleApigee/ReleaseNotes/1_0_1.md
  Packs/GoogleApigee/pack_metadata.json
Labels: docs-approved

#39331 Nozomi fix potential incidents loss when max page number reached
  Packs/NozomiNetworks/Integrations/NozomiNetworks/NozomiNetworks.py
  Packs/NozomiNetworks/Integrations/NozomiNetworks/NozomiNetworks.yml
  Packs/NozomiNetworks/Integrations/NozomiNetworks/NozomiNetworks_test.py
  Packs/NozomiNetworks/ReleaseNotes/1_0_19.md
  Packs/NozomiNetworks/pack_metadata.json
Labels: Contribution, docs-approved, Partner, Contribution Form Filled, Partner Support Level, External PR, Partner-Approved

#39507 ServiceNow integration - add support for new timestamp format
  Packs/ServiceNow/Integrations/ServiceNowv2/ServiceNowv2.py
  Packs/ServiceNow/Integrations/ServiceNowv2/ServiceNowv2.yml
  Packs/ServiceNow/ReleaseNotes/2_7_13.md
  Packs/ServiceNow/pack_metadata.json
Labels: Contribution, docs-approved, Contribution Form Filled, Community, Xsoar Support Level, External PR

#39503 MSFT O365 Email Enh.
  Packs/Office365/ModelingRules/Office365/Office365.xif
  Packs/Office365/ModelingRules/Office365/Office365_schema.json
  Packs/Office365/ReleaseNotes/1_0_12.md
  Packs/Office365/pack_metadata.json
Labels: docs-approved

#39239 Update URL Phishing
  Packs/PhishingURL/.secrets-ignore
  Packs/PhishingURL/ReleaseNotes/1_2_2.md
  Packs/PhishingURL/Scripts/DBotPredictURLPhishing/DBotPredictURLPhishing.py
  Packs/PhishingURL/Scripts/DBotPredictURLPhishing/DBotPredictURLPhishing.yml
  Packs/PhishingURL/Scripts/DBotPredictURLPhishing/DBotPredictURLPhishing_test.py
  Packs/PhishingURL/Scripts/DBotPredictURLPhishing/test_data/model_predictions.py
  Packs/PhishingURL/Scripts/DBotUpdateLogoURLPhishing/DBotUpdateLogoURLPhishing.py
  Packs/PhishingURL/Scripts/DBotUpdateLogoURLPhishing/DBotUpdateLogoURLPhishing.yml
  Packs/PhishingURL/Scripts/DBotUpdateLogoURLPhishing/DBotUpdateLogoURLPhishing_test.py
  Packs/PhishingURL/Scripts/DBotUpdateLogoURLPhishing/README.md
  Packs/PhishingURL/pack_metadata.json
Labels: docs-approved

#39499 Add a holiday message
  .github/github_workflow_scripts/handle_external_pr.py
Labels: docs-approved

#39399 [HTTPFeedApiModule] Convert IP ranges to CIDRs
  Packs/ApiModules/Scripts/HTTPFeedApiModule/HTTPFeedApiModule.py
  Packs/ApiModules/Scripts/HTTPFeedApiModule/HTTPFeedApiModule_test.py
  Packs/ApiModules/Scripts/HTTPFeedApiModule/test_data/expected_cidr_result.json
  Packs/FeedBlocklist_de/ReleaseNotes/1_1_34.md
  Packs/FeedBlocklist_de/pack_metadata.json
  Packs/FeedBruteForceBlocker/ReleaseNotes/1_1_32.md
  Packs/FeedBruteForceBlocker/pack_metadata.json
  Packs/FeedCloudflare/ReleaseNotes/1_1_32.md
  Packs/FeedCloudflare/pack_metadata.json
  Packs/FeedDShield/ReleaseNotes/1_1_36.md
  Packs/FeedDShield/pack_metadata.json
  Packs/FeedFeodoTracker/ReleaseNotes/1_1_34.md
  Packs/FeedFeodoTracker/pack_metadata.json
  Packs/FeedMalwareDomainList/ReleaseNotes/1_1_12.md
  Packs/FeedMalwareDomainList/pack_metadata.json
  Packs/FeedPlainText/ReleaseNotes/1_1_33.md
  Packs/FeedPlainText/pack_metadata.json
  Packs/FeedSpamhaus/ReleaseNotes/1_1_30.md
  Packs/FeedSpamhaus/pack_metadata.json
Labels: docs-approved

#39528 CheckPoint Firewall - add-host small fix
  Packs/CheckpointFirewall/Integrations/CheckPointFirewallV2/CheckPointFirewallV2.py
  Packs/CheckpointFirewall/Integrations/CheckPointFirewallV2/CheckPointFirewallV2.yml
  Packs/CheckpointFirewall/Integrations/CheckPointFirewallV2/CheckPointFirewallV2_test.py
  Packs/CheckpointFirewall/ReleaseNotes/2_3_30.md
  Packs/CheckpointFirewall/pack_metadata.json
Labels: docs-approved

#39534 Msft azure fix
  Packs/MicrosoftEntraID/ParsingRules/MicrosoftEntraID/MicrosoftEntraID.xif
  Packs/MicrosoftEntraID/ReleaseNotes/1_0_13.md
  Packs/MicrosoftEntraID/pack_metadata.json
Labels: docs-approved, bypass.url

#39536 Add to secret ignore
  Packs/PhishingURL/.secrets-ignore
Labels: docs-approved

#39412 Fix get-valuelist cache bug in RSA Archer V2
  Packs/ArcherRSA/Integrations/ArcherV2/ArcherV2.py
  Packs/ArcherRSA/Integrations/ArcherV2/ArcherV2.yml
  Packs/ArcherRSA/Integrations/ArcherV2/ArcherV2_test.py
  Packs/ArcherRSA/Integrations/ArcherV2/README.md
  Packs/ArcherRSA/ReleaseNotes/1_3_3.md
  Packs/ArcherRSA/pack_metadata.json
Labels: bug, docs-approved, python

#39422 Fix malformed time arguments in qradar list offenses
  Packs/QRadar/Integrations/QRadar_v3/QRadar_v3.py
  Packs/QRadar/Integrations/QRadar_v3/QRadar_v3_test.py
  Packs/QRadar/ReleaseNotes/2_5_16.md
  Packs/QRadar/pack_metadata.json
Labels: docs-approved

#39546 EDL - remove excessive logs
  Packs/EDL/Integrations/EDL/EDL.py
  Packs/EDL/Integrations/EDL/EDL.yml
  Packs/EDL/ReleaseNotes/3_3_12.md
  Packs/EDL/pack_metadata.json
Labels: docs-approved, ready-for-pipeline-running

#39549 Xsup 49272
  Packs/ArcherRSA/Integrations/ArcherV2/ArcherV2.yml
  Packs/ArcherRSA/ReleaseNotes/1_3_4.md
  Packs/ArcherRSA/pack_metadata.json
Labels: docs-approved, ready-for-pipeline-running

#39544 Trend Micro Vision One - Documentation update
  Packs/TrendMicroVisionOne/Integrations/TrendMicroVisionOneEventCollector/README.md
  Packs/TrendMicroVisionOne/Integrations/TrendMicroVisionOneEventCollector/TrendMicroVisionOneEventCollector.yml
  Packs/TrendMicroVisionOne/ReleaseNotes/4_2_3.md
  Packs/TrendMicroVisionOne/pack_metadata.json
Labels: docs-approved

#39557 fix default platform layout ID
  Packs/Core/Layouts/layoutscontainer-Default_platform_issues.json
  Packs/Core/ReleaseNotes/3_2_32.md
  Packs/Core/pack_metadata.json
Labels: docs-approved, ForceMerge, ready-for-pipeline-running

#39523 handle no incidents
  Packs/CommonScripts/ReleaseNotes/1_19_43.md
  Packs/CommonScripts/Scripts/ExportIncidentsToCSV/ExportIncidentsToCSV.py
  Packs/CommonScripts/Scripts/ExportIncidentsToCSV/ExportIncidentsToCSV.yml
  Packs/CommonScripts/Scripts/ExportIncidentsToCSV/ExportIncidentsToCSV_test.py
  Packs/CommonScripts/pack_metadata.json
Labels: docs-approved, ready-for-pipeline-running

#39234 Fix Jira V3 fetch incidents timezone issue
  Packs/Jira/Integrations/JiraV3/JiraV3.py
  Packs/Jira/Integrations/JiraV3/JiraV3.yml
  Packs/Jira/Integrations/JiraV3/JiraV3_test.py
  Packs/Jira/Integrations/JiraV3/README.md
  Packs/Jira/Integrations/JiraV3/command_examples.txt
  Packs/Jira/ReleaseNotes/3_2_20.md
  Packs/Jira/pack_metadata.json
Labels: bug, docs-approved, python, ready-for-pipeline-running

#39397 Common script clear user session update
  Packs/CommonScripts/ReleaseNotes/1_19_44.json
  Packs/CommonScripts/ReleaseNotes/1_19_44.md
  Packs/CommonScripts/Scripts/ClearUserSession/ClearUserSession.py
  Packs/CommonScripts/Scripts/ClearUserSession/ClearUserSession.yml
  Packs/CommonScripts/Scripts/ClearUserSession/ClearUserSession_test.py
  Packs/CommonScripts/Scripts/ClearUserSession/README.md
  Packs/CommonScripts/pack_metadata.json
Labels: docs-approved, ready-for-pipeline-running

#39252 Adapt CirclCVESearch integration to CVE 5.1 structure
  Packs/CIRCL/Integrations/CirclCVESearch/CirclCVESearch.py
  Packs/CIRCL/Integrations/CirclCVESearch/CirclCVESearch.yml
  Packs/CIRCL/Integrations/CirclCVESearch/CirclCVESearch_test.py
  Packs/CIRCL/Integrations/CirclCVESearch/README.md
  Packs/CIRCL/Integrations/CirclCVESearch/test_data/5_1.json
  Packs/CIRCL/ReleaseNotes/1_0_27.md
  Packs/CIRCL/TestPlaybooks/playbook-CIRCL_CVE_Search_Test.yml
  Packs/CIRCL/pack_metadata.json
Labels: docs-approved, bypass.url, ready-for-pipeline-running

#39558 XSUP-49293: Core Rest API - debug logs updating
  Packs/DemistoRESTAPI/Integrations/CoreRESTAPI/CoreRESTAPI.js
  Packs/DemistoRESTAPI/ReleaseNotes/1_3_71.md
  Packs/DemistoRESTAPI/pack_metadata.json
  Tests/conf.json
Labels: docs-approved, ready-for-pipeline-running

#39559 Alignment tags, keywords and categories packs (chunk1)
  Packs/3CXDesktopApp_Supply_Chain_Attack/pack_metadata.json
  Packs/APIVoid/pack_metadata.json
  Packs/AWS-AccessAnalyzer/pack_metadata.json
  Packs/AWS-EKS/pack_metadata.json
  Packs/AWS-SNS-Listener/pack_metadata.json
  Packs/AWS-SQS/pack_metadata.json
  Packs/AWS-SecurityHub/pack_metadata.json
Labels: docs-approved

#38884 Mattermost groups and role and send multiple
  Packs/Mattermost/CONTRIBUTORS.json
  Packs/Mattermost/Integrations/MattermostV2/MattermostV2.py
  Packs/Mattermost/Integrations/MattermostV2/MattermostV2.yml
  Packs/Mattermost/Integrations/MattermostV2/MattermostV2_test.py
  Packs/Mattermost/Integrations/MattermostV2/README.md
  Packs/Mattermost/Integrations/MattermostV2/command_examples.txt
  Packs/Mattermost/Integrations/MattermostV2/test_data/list_channel_memberships_for_user.json
  Packs/Mattermost/Integrations/MattermostV2/test_data/list_group_members_response.json
  Packs/Mattermost/Integrations/MattermostV2/test_data/list_groups_response.json
  Packs/Mattermost/Integrations/MattermostV2/test_data/list_users_response.json
  Packs/Mattermost/ReleaseNotes/2_1_0.md
  Packs/Mattermost/TestPlaybooks/Mattermost_V2_-_testplaybook.yml
  Packs/Mattermost/pack_metadata.json
Labels: Contribution, docs-approved, pending-demo, Contribution Form Filled, Community, pending-contributor, Xsoar Support Level, External PR

#39567 Skip prisma cloud compute test
  Tests/conf.json
Labels: docs-approved, ready-for-pipeline-running

#39404 XSIAM-PB-Recurring-rare-domain-access-from-an-unsigned-process
  Packs/CortexResponseAndRemediation/Playbooks/silent-playbook-Recurring_rare_domain_access_from_an_unsigned_process.yml
  Packs/CortexResponseAndRemediation/ReleaseNotes/1_1_35.md
  Packs/CortexResponseAndRemediation/Triggers/silent-Trigger_-_Recurring_rare_domain_access_from_an_unsigned_process.json
  Packs/CortexResponseAndRemediation/pack_metadata.json
Labels: docs-approved, ready-for-pipeline-running

#39563 MS Teams add missing permission requirement to docs
  Packs/MicrosoftTeams/Integrations/MicrosoftTeams/MicrosoftTeams.py
  Packs/MicrosoftTeams/Integrations/MicrosoftTeams/MicrosoftTeams_test.py
  Packs/MicrosoftTeams/Integrations/MicrosoftTeams/README.md
  Packs/MicrosoftTeams/ReleaseNotes/1_5_24.md
  Packs/MicrosoftTeams/pack_metadata.json
Labels: docs-approved, ready-for-pipeline-running

#39588 Alignment tags, keywords and categories packs (chunk6)
  Packs/Brandefense/pack_metadata.json
  Packs/BreachNotification-US/pack_metadata.json
  Packs/BreachRx/pack_metadata.json
  Packs/BruteForce/pack_metadata.json
  Packs/CTM360-CyberBlindspot/pack_metadata.json
  Packs/CVE_2021_40444/pack_metadata.json
  Packs/CVE_2021_44228/pack_metadata.json
Labels: docs-approved, ready-for-pipeline-running

#39570 Alignment tags, keywords and categories packs (chunk2)
  Packs/AWS_ELB/pack_metadata.json
  Packs/AWS_SystemManager/pack_metadata.json
  Packs/AbnormalSecurity/pack_metadata.json
  Packs/AbuseDB/pack_metadata.json
  Packs/AcalvioShadowplex/pack_metadata.json
  Packs/AccentureCTI_Feed/pack_metadata.json
  Packs/ActiveMQ/pack_metadata.json
  Packs/Active_Directory_Query/pack_metadata.json
  Packs/AgariPhishingDefense/pack_metadata.json
Labels: docs-approved, ready-for-pipeline-running

#39508 Panorama Fix message when getting 403 error
  Packs/PAN-OS/Integrations/Panorama/Panorama.py
  Packs/PAN-OS/ReleaseNotes/2_3_9.md
  Packs/PAN-OS/pack_metadata.json
Labels: docs-approved, ForceMerge, ready-for-pipeline-running

#39571 Alignment tags, keywords and categories packs (chunk3)
  Packs/AlienVault_OTX/pack_metadata.json
  Packs/AlphaVantage/pack_metadata.json
  Packs/AnsibleAlibabaCloud/pack_metadata.json
  Packs/AnsibleAzure/pack_metadata.json
  Packs/AnsibleCiscoIOS/pack_metadata.json
  Packs/AnsibleCiscoNXOS/pack_metadata.json
  Packs/AnsibleHetznerCloud/pack_metadata.json
  Packs/AnsibleKubernetes/pack_metadata.json
  Packs/AnsibleLinux/pack_metadata.json
  Packs/AnsibleMicrosoftWindows/pack_metadata.json
Labels: docs-approved, ready-for-pipeline-running

#39527 CRTX-162928-Linux
  Packs/LinuxEventsCollection/ModelingRules/LinuxEventsCollection_1_3/LinuxEventsCollection_1_3.xif
  Packs/LinuxEventsCollection/ReleaseNotes/1_0_16.md
  Packs/LinuxEventsCollection/pack_metadata.json
Labels: docs-approved, bypass.url, ready-for-pipeline-running

#39594 Removed the holiday message from newly created PRs
  .github/github_workflow_scripts/handle_external_pr.py
Labels: docs-approved, ready-for-pipeline-running

#39533 Url ssl verification v2
  Packs/CommonScripts/.secrets-ignore
  Packs/CommonScripts/ReleaseNotes/1_19_45.md
  Packs/CommonScripts/Scripts/URLSSLVerification/README.md
  Packs/CommonScripts/Scripts/URLSSLVerification/URLSSLVerification.py
  Packs/CommonScripts/Scripts/URLSSLVerification/URLSSLVerification.yml
  Packs/CommonScripts/Scripts/URLSSLVerification/URLSSLVerification_test.py
  Packs/CommonScripts/pack_metadata.json
Labels: docs-approved, ready-for-pipeline-running

#39545 Nbensalmon/ciac 13043/collection extrahop reveal x
  Packs/ExtraHop/Integrations/ExtrahopRevealXEventCollector/ExtrahopRevealXEventCollector.py
  Packs/ExtraHop/Integrations/ExtrahopRevealXEventCollector/ExtrahopRevealXEventCollector.yml
  Packs/ExtraHop/Integrations/ExtrahopRevealXEventCollector/ExtrahopRevealXEventCollector_description.md
  Packs/ExtraHop/Integrations/ExtrahopRevealXEventCollector/ExtrahopRevealXEventCollector_image.png
  Packs/ExtraHop/Integrations/ExtrahopRevealXEventCollector/ExtrahopRevealXEventCollector_test.py
  Packs/ExtraHop/Integrations/ExtrahopRevealXEventCollector/README.md
  Packs/ExtraHop/Integrations/ExtrahopRevealXEventCollector/command_examples.txt
  Packs/ExtraHop/Integrations/ExtrahopRevealXEventCollector/test_data/detections-dummy.json
  Packs/ExtraHop/ReleaseNotes/2_3_0.md
  Packs/ExtraHop/pack_metadata.json
Labels: docs-approved, ready-for-pipeline-running

#39581 Enable modifying timeout of `xql-generic-query` command
  Packs/ApiModules/Scripts/CoreXQLApiModule/CoreXQLApiModule.py
  Packs/Core/Integrations/CortexCoreXQLQueryEngine/CortexCoreXQLQueryEngine.yml
  Packs/Core/ReleaseNotes/3_2_33.md
  Packs/Core/pack_metadata.json
  Packs/CortexXDR/Integrations/XQLQueryingEngine/XQLQueryingEngine.yml
  Packs/CortexXDR/ReleaseNotes/6_2_18.md
  Packs/CortexXDR/pack_metadata.json
Labels: docs-approved, ready-for-pipeline-running

#39556 URL - Numerical IP in URL
  Packs/CommonTypes/IndicatorTypes/reputation-url.json
  Packs/CommonTypes/ReleaseNotes/3_8_9.md
  Packs/CommonTypes/pack_metadata.json
Labels: docs-approved, ready-for-pipeline-running

#39543 Crtx 122154 microsoft graph security
  Packs/MicrosoftGraphSecurity/ModelingRules/MicrosoftGraphSecurity/MicrosoftGraphSecurity.xif
  Packs/MicrosoftGraphSecurity/ReleaseNotes/2_2_26.md
  Packs/MicrosoftGraphSecurity/pack_metadata.json
Labels: docs-approved, bypass.url, ready-for-pipeline-running

#39595 Cisco ISR - Updating modeling rules
  Packs/CiscoISR/ModelingRules/CiscoISR/CiscoISR.xif
  Packs/CiscoISR/ParsingRules/CiscoISR/CiscoISR.xif
  Packs/CiscoISR/README.md
  Packs/CiscoISR/ReleaseNotes/1_0_7.md
  Packs/CiscoISR/pack_metadata.json
Labels: docs-approved, bypass.url, ready-for-pipeline-running

#39592 Crtx-149545-apache
  Packs/ApacheWebServer/ModelingRules/ApacheWebServerModelingRules_1_3/ApacheWebServerModelingRules_1_3.xif
  Packs/ApacheWebServer/README.md
  Packs/ApacheWebServer/ReleaseNotes/1_0_9.md
  Packs/ApacheWebServer/pack_metadata.json
Labels: docs-approved, bypass.url, ready-for-pipeline-running

#39102 Update README.md for Webhook
  Packs/GenericWebhook/Integrations/GenericWebhook/README.md
Labels: docs-approved, ready-for-pipeline-running

#39615 fixed wrong url in unzip file tpb
  Packs/CommonScripts/TestPlaybooks/playbook-UnzipFile-Test.yml
Labels: docs-approved, ready-for-pipeline-running

#39585 fix slack pack description
  Packs/Slack/README.md
Labels: docs-approved, bypass.url, ready-for-pipeline-running

#39590 bug - incomplete categories whe running the command get_url_category
  Packs/PAN-OS/Integrations/Panorama/Panorama.py
  Packs/PAN-OS/Integrations/Panorama/Panorama_test.py
  Packs/PAN-OS/ReleaseNotes/2_3_10.md
  Packs/PAN-OS/pack_metadata.json
Labels: docs-approved, ForceMerge, ready-for-pipeline-running

#39553 Update README.md
  Packs/PAN-OS/Integrations/Panorama/README.md
Labels: Contribution, Contribution Form Filled, Community, Xsoar Support Level, External PR

#39573 Indicators malicious script
  Packs/CommonScripts/ReleaseNotes/1_19_46.md
  Packs/CommonScripts/Scripts/IndicatorMaliciousRatioCalculation/IndicatorMaliciousRatioCalculation.py
  Packs/CommonScripts/Scripts/IndicatorMaliciousRatioCalculation/IndicatorMaliciousRatioCalculation.yml
  Packs/CommonScripts/pack_metadata.json
Labels: docs-approved, ready-for-pipeline-running

#39586 Update Incydr SDK version
  Packs/Code42/Integrations/Code42/Code42.yml
  Packs/Code42/ReleaseNotes/6_0_4.md
  Packs/Code42/pack_metadata.json
Labels: Contribution, Partner, Contribution Form Filled, Partner Support Level, External PR, Partner-Approved

#39625 Add TLS limitation
  Packs/Forcepoint/.pack-ignore
  Packs/Forcepoint/Integrations/Forcepoint/Forcepoint.yml
  Packs/Forcepoint/Integrations/Forcepoint/Forcepoint_description.md
  Packs/Forcepoint/Integrations/Forcepoint/README.md
  Packs/Forcepoint/ReleaseNotes/1_0_16.md
  Packs/Forcepoint/pack_metadata.json
Labels: docs-approved, ready-for-pipeline-running

#39631 Core quick actions
  Packs/Core/Integrations/CortexCoreIR/CortexCoreIR.yml
  Packs/Core/ReleaseNotes/3_2_34.md
  Packs/Core/pack_metadata.json
Labels: docs-approved, bypass.url, ready-for-pipeline-running

#39626 Azure app service modeling modification - CRTX 169140
  Packs/AzureAppService/ModelingRules/AzureAppService/AzureAppService.xif
  Packs/AzureAppService/ModelingRules/AzureAppService/AzureAppService_schema.json
  Packs/AzureAppService/ReleaseNotes/1_0_2.md
  Packs/AzureAppService/pack_metadata.json
Labels: docs-approved, ready-for-pipeline-running

#39639 Skip integration and script README from check large files hook
  .pre-commit-config_template.yaml
Labels: docs-approved, ready-for-pipeline-running

#39347 Feed taxii2 exception handling
  Packs/FeedTAXII/Integrations/FeedTAXII2/FeedTAXII2.py
  Packs/FeedTAXII/Integrations/FeedTAXII2/FeedTAXII2.yml
  Packs/FeedTAXII/Integrations/FeedTAXII2/FeedTAXII2_test.py
  Packs/FeedTAXII/ReleaseNotes/1_2_34.md
  Packs/FeedTAXII/pack_metadata.json
Labels: ready-for-pipeline-running

#39653 Alignment tags, keywords and categories packs (chunk8)
  Packs/CertStream/pack_metadata.json
  Packs/CheckPointDome9/pack_metadata.json
  Packs/CheckPointNDR/pack_metadata.json
  Packs/CheckPointSandBlast/pack_metadata.json
  Packs/CheckpointFirewall/pack_metadata.json
  Packs/CiscoCatalyst/pack_metadata.json
  Packs/CiscoSpark/pack_metadata.json
  Packs/Claroty/pack_metadata.json
  Packs/ClarotyXDome/pack_metadata.json
Labels: docs-approved, ready-for-pipeline-running

#39572 Alignment tags, keywords and categories packs (chunk5)
  Packs/AutoFocus/pack_metadata.json
  Packs/Automox/pack_metadata.json
  Packs/AzureSecurityCenter/pack_metadata.json
  Packs/AzureStorageQueue/pack_metadata.json
  Packs/BeyondTrustPrivilegedRemoteAccess/pack_metadata.json
  Packs/BeyondTrustRemoteSupport/pack_metadata.json
  Packs/BeyondTrust_Password_Safe/pack_metadata.json
  Packs/Binalyze/pack_metadata.json
Labels: docs-approved, ready-for-pipeline-running

#39629 Coreir fix exception parsing
  Packs/ApiModules/Scripts/CoreIRApiModule/CoreIRApiModule.py
  Packs/Core/ReleaseNotes/3_2_35.md
  Packs/Core/pack_metadata.json
  Packs/CortexXDR/ReleaseNotes/6_2_19.md
  Packs/CortexXDR/pack_metadata.json
  Packs/ctf01/ReleaseNotes/1_0_41.md
  Packs/ctf01/pack_metadata.json
Labels: docs-approved, ForceMerge, ready-for-pipeline-running

#39519 Platform: add missing new packs
  Packs/AnthropicClaude/pack_metadata.json
  Packs/LenelS2NetBox/pack_metadata.json
  Packs/LookoutMobileEndpointSecurity/pack_metadata.json
  Packs/NasuniFileServices/pack_metadata.json
  Packs/SymantecICDM/pack_metadata.json
Labels: docs-approved, ForceMerge

#39295 Fix TAXII Server integration failing as indicator volume increases
  Packs/TAXIIServer/Integrations/TAXIIServer/TAXIIServer.py
  Packs/TAXIIServer/Integrations/TAXIIServer/TAXIIServer.yml
  Packs/TAXIIServer/ReleaseNotes/2_1_7.md
  Packs/TAXIIServer/pack_metadata.json
Labels: bug, docs-approved, python, ForceMerge, ready-for-pipeline-running

#39608 Fixing adding special characters in audit comments of security policies
  Packs/PAN-OS/CONTRIBUTORS.json
  Packs/PAN-OS/Integrations/Panorama/Panorama.py
  Packs/PAN-OS/ReleaseNotes/2_3_11.md
  Packs/PAN-OS/pack_metadata.json
Labels: Contribution, Contribution Form Filled, Community, Xsoar Support Level, External PR

#39645 A new pack - Tavily
  Packs/Tavily/.pack-ignore
  Packs/Tavily/.secrets-ignore
  Packs/Tavily/Integrations/Tavily/README.md
  Packs/Tavily/Integrations/Tavily/Tavily.py
  Packs/Tavily/Integrations/Tavily/Tavily.yml
  Packs/Tavily/Integrations/Tavily/Tavily_description.md
  Packs/Tavily/Integrations/Tavily/Tavily_image.png
  Packs/Tavily/Integrations/Tavily/Tavily_test.py
  Packs/Tavily/Integrations/Tavily/command_examples.txt
  Packs/Tavily/README.md
  Packs/Tavily/pack_metadata.json
Labels: ready-for-pipeline-running

#39663 Playbook description fix get original email
  Packs/Phishing/Playbooks/Get_Original_Email_-_EWS.yml
  Packs/Phishing/ReleaseNotes/3_7_3.md
  Packs/Phishing/pack_metadata.json
Labels: docs-approved, ready-for-pipeline-running

#39566 GoogleChatViaWebhook: fix potential `AttributeError` on sender information in output
  Packs/GoogleChatViaWebhook/CONTRIBUTORS.json
  Packs/GoogleChatViaWebhook/Integrations/GoogleChatViaWebhook/GoogleChatViaWebhook.py
  Packs/GoogleChatViaWebhook/Integrations/GoogleChatViaWebhook/README.md
  Packs/GoogleChatViaWebhook/ReleaseNotes/1_0_3.md
  Packs/GoogleChatViaWebhook/pack_metadata.json
Labels: Contribution, Partner, Contribution Form Filled, Community Support Level, External PR

#39638 Fix xdr malware incident enrichment tpb
  Packs/CortexXDR/TestPlaybooks/Test_Playbook_-_Cortex_XDR_Malware_-_Incident_Enrichment.yml
Labels: docs-approved, ready-for-pipeline-running

#39687 skipped tpbs due to expired creds
  Tests/conf.json
Labels: docs-approved, ready-for-pipeline-running

#39597 XSUP-49452: OTRS a small fix
  Packs/OTRS/Integrations/OTRS/OTRS.py
  Packs/OTRS/Integrations/OTRS/OTRS.yml
  Packs/OTRS/Integrations/OTRS/OTRS_test.py
  Packs/OTRS/ReleaseNotes/1_1_4.md
  Packs/OTRS/pack_metadata.json
Labels: docs-approved, ready-for-pipeline-running

#39611 Improve ConvertFile script and new checkPDFEncryptionAndValidity script
  Packs/CommonScripts/ReleaseNotes/1_19_47.md
  Packs/CommonScripts/Scripts/CheckPDFEncryptionAndValidity/CheckPDFEncryptionAndValidity.py
  Packs/CommonScripts/Scripts/CheckPDFEncryptionAndValidity/CheckPDFEncryptionAndValidity.yml
  Packs/CommonScripts/Scripts/CheckPDFEncryptionAndValidity/CheckPDFEncryptionAndValidity_test.py
  Packs/CommonScripts/Scripts/CheckPDFEncryptionAndValidity/README.md
  Packs/CommonScripts/Scripts/ConvertFile/ConvertFile.py
  Packs/CommonScripts/Scripts/ConvertFile/ConvertFile_test.py
  Packs/CommonScripts/Scripts/IsPDFFileEncrypted/IsPDFFileEncrypted.yml
  Packs/CommonScripts/pack_metadata.json
Labels: docs-approved, ready-for-pipeline-running

#39682 Revert #39330 PR
  Packs/GmailSingleUser/Integrations/GmailSingleUser/GmailSingleUser.py
  Packs/GmailSingleUser/Integrations/GmailSingleUser/GmailSingleUser_test.py
  Packs/GmailSingleUser/ReleaseNotes/1_4_12.md
  Packs/GmailSingleUser/pack_metadata.json
Labels: ForceMerge, ready-for-pipeline-running

#39684 Azure WAF Fix 230425
  Packs/AzureWAF/ParsingRules/AzureWAF/AzureWAF.xif
  Packs/AzureWAF/ReleaseNotes/1_2_9.md
  Packs/AzureWAF/pack_metadata.json
  Packs/MicrosoftEntraID/ParsingRules/MicrosoftEntraID/MicrosoftEntraID.xif
  Packs/MicrosoftEntraID/ReleaseNotes/1_0_14.md
  Packs/MicrosoftEntraID/pack_metadata.json
Labels: docs-approved, bypass.url, ready-for-pipeline-running

#39384 Unskip Mail Sender and Mail-Listener
  Tests/conf.json
Labels: docs-approved, ready-for-pipeline-running

#39689 Exabeam Advanced Analytics troubleshoot section
  Packs/Exabeam/Integrations/Exabeam/Exabeam.yml
  Packs/Exabeam/Integrations/Exabeam/README.md
  Packs/Exabeam/ReleaseNotes/2_4_4.md
  Packs/Exabeam/pack_metadata.json
Labels: docs-approved, ready-for-pipeline-running

#39683 processing-image-file: update docker tag
  Packs/CommonScripts/ReleaseNotes/1_19_48.md
  Packs/CommonScripts/Scripts/PreProcessImage/PreProcessImage.yml
  Packs/CommonScripts/pack_metadata.json
  Packs/SuspiciousDomainHunting/ReleaseNotes/1_0_13.md
  Packs/SuspiciousDomainHunting/Scripts/Imagecompare/Imagecompare.yml
  Packs/SuspiciousDomainHunting/Scripts/RasterizeImageOriginal/RasterizeImageOriginal.yml
  Packs/SuspiciousDomainHunting/Scripts/RasterizeImageSuspicious/RasterizeImageSuspicious.yml
  Packs/SuspiciousDomainHunting/pack_metadata.json
Labels: docs-approved, ready-for-pipeline-running

#39525 Shodan Search Command Enhancement [CIAC-11976]
  Packs/Shodan/Integrations/Shodan_v2/README.md
  Packs/Shodan/Integrations/Shodan_v2/Shodan_v2.py
  Packs/Shodan/Integrations/Shodan_v2/Shodan_v2.yml
  Packs/Shodan/Integrations/Shodan_v2/Shodan_v2_description.md
  Packs/Shodan/Integrations/Shodan_v2/Shodan_v2_test.py
  Packs/Shodan/Integrations/Shodan_v2/command_examples.txt
  Packs/Shodan/Integrations/Shodan_v2/test_data/expected_return_results_NoSSL.json
  Packs/Shodan/Integrations/Shodan_v2/test_data/expected_return_results_SSL_NoNTLM.json
  Packs/Shodan/Integrations/Shodan_v2/test_data/expected_return_results_SSL_WithNTLM.json
  Packs/Shodan/Integrations/Shodan_v2/test_data/searchresults_NoSSL.json
  Packs/Shodan/Integrations/Shodan_v2/test_data/searchresults_SSL_NoNTLM.json
  Packs/Shodan/Integrations/Shodan_v2/test_data/searchresults_SSL_WithNTLM.json
  Packs/Shodan/README.md
  Packs/Shodan/ReleaseNotes/1_2_4.md
  Packs/Shodan/TestPlaybooks/playbook-Test_shodan_v2.yml
  Packs/Shodan/pack_metadata.json
Labels: Contribution, docs-approved, pending-demo, post-demo, Contribution Form Filled, Community, Xsoar Support Level, External PR

#39561 Armis Release 1.2.0
  Packs/Armis/.secrets-ignore
  Packs/Armis/Integrations/Armis/Armis.py
  Packs/Armis/Integrations/Armis/Armis.yml
  Packs/Armis/Integrations/Armis/Armis_test.py
  Packs/Armis/Integrations/Armis/README.md
  Packs/Armis/ReleaseNotes/1_2_0.md
  Packs/Armis/pack_metadata.json
Labels: Contribution, Partner, pending-demo, Contribution Form Filled, pending-contributor, Partner Support Level, External PR, Partner-Approved

#39599 Add rawJSON to fetched indicator object in Feed MISP Threat Actors
  Packs/FeedMISPThreatActors/CONTRIBUTORS.json
  Packs/FeedMISPThreatActors/Integrations/FeedMISPThreatActors/FeedMISPThreatActors.py
  Packs/FeedMISPThreatActors/ReleaseNotes/1_0_2.md
  Packs/FeedMISPThreatActors/pack_metadata.json
Labels: Contribution, Contribution Form Filled, Community, Xsoar Support Level, External PR, TIM Review

#39698 Move GR107 to Warning
  validation_config.toml
Labels: docs-approved, ForceMerge, ready-for-pipeline-running, on-call

#39693 CiscoUmbrellaReporting bugfix category filter
  Packs/CiscoUmbrellaReporting/Integrations/CiscoUmbrellaReporting/CiscoUmbrellaReporting.py
  Packs/CiscoUmbrellaReporting/Integrations/CiscoUmbrellaReporting/CiscoUmbrellaReporting.yml
  Packs/CiscoUmbrellaReporting/ReleaseNotes/1_1_6.md
  Packs/CiscoUmbrellaReporting/pack_metadata.json
Labels: Contribution, Contribution Form Filled, Community, Xsoar Support Level, External PR

#39685 Support list input for `splunk-job-status` command
  Packs/SplunkPy/Integrations/SplunkPy/README.md
  Packs/SplunkPy/Integrations/SplunkPy/SplunkPy.py
  Packs/SplunkPy/Integrations/SplunkPy/SplunkPy.yml
  Packs/SplunkPy/Integrations/SplunkPy/SplunkPy_test.py
  Packs/SplunkPy/ReleaseNotes/3_2_9.md
  Packs/SplunkPy/pack_metadata.json
Labels: docs-approved, ready-for-pipeline-running

#39702 Add proxy support to Nessus integration
  Packs/nessus/Integrations/Nessus/Nessus.js
  Packs/nessus/Integrations/Nessus/Nessus.yml
  Packs/nessus/Integrations/Nessus/Nessus_description.md
  Packs/nessus/ReleaseNotes/1_0_5.md
  Packs/nessus/pack_metadata.json
Labels: docs-approved, ready-for-pipeline-running

#39703 Failed instances fix
  Packs/CommonScripts/ReleaseNotes/1_19_49.md
  Packs/CommonScripts/Scripts/FailedInstances/FailedInstances.js
  Packs/CommonScripts/pack_metadata.json
Labels: docs-approved, ready-for-pipeline-running

#39574 XSUP-49241/OktaASA
  Packs/OktaASA/Integrations/OktaASA/OktaASA.py
  Packs/OktaASA/Integrations/OktaASA/OktaASA_test.py
  Packs/OktaASA/Integrations/OktaASA/test_data/response_10_items_descending_default.json
  Packs/OktaASA/Integrations/OktaASA/test_data/response_10_items_descending_true.json
  Packs/OktaASA/ReleaseNotes/1_0_3.md
  Packs/OktaASA/pack_metadata.json
Labels: docs-approved, ready-for-pipeline-running

#39532 add handling to long_running_execution_command for exceptions
  Packs/ProofpointEmailSecurity/Integrations/ProofpointEmailSecurityEventCollector/ProofpointEmailSecurityEventCollector.py
  Packs/ProofpointEmailSecurity/Integrations/ProofpointEmailSecurityEventCollector/ProofpointEmailSecurityEventCollector.yml
  Packs/ProofpointEmailSecurity/Integrations/ProofpointEmailSecurityEventCollector/ProofpointEmailSecurityEventCollector_test.py
  Packs/ProofpointEmailSecurity/Integrations/ProofpointEmailSecurityEventCollector/README.md
  Packs/ProofpointEmailSecurity/ReleaseNotes/1_0_12.md
  Packs/ProofpointEmailSecurity/pack_metadata.json
Labels: docs-approved, ready-for-pipeline-running

#39709 CoreIR: fix quick action arg path
  Packs/Core/Integrations/CortexCoreIR/CortexCoreIR.yml
  Packs/Core/ReleaseNotes/3_2_37.md
  Packs/Core/pack_metadata.json
Labels: docs-approved, ForceMerge, ready-for-pipeline-running

#39641 Rasterize - Add logs
  Packs/rasterize/Integrations/rasterize/rasterize.py
  Packs/rasterize/Integrations/rasterize/rasterize_test.py
  Packs/rasterize/ReleaseNotes/2_1_4.md
  Packs/rasterize/pack_metadata.json
Labels: docs-approved, ready-for-pipeline-running

#39661 Add skip casting sign to Cortex RNR incidents
  Packs/CortexResponseAndRemediation/Playbooks/playbook-A_user_executed_multiple_LDAP_enumeration_queries.yml
  Packs/CortexResponseAndRemediation/Playbooks/playbook-Excessive_User_Account_Lockouts.yml
  Packs/CortexResponseAndRemediation/Playbooks/playbook-Suspicious_Hidden_User_Created.yml
  Packs/CortexResponseAndRemediation/Playbooks/playbook-Suspicious_Local_Administrator_Login.yml
  Packs/CortexResponseAndRemediation/ReleaseNotes/1_1_37.md
  Packs/CortexResponseAndRemediation/pack_metadata.json
Labels: docs-approved, ready-for-pipeline-running

#39724 skipped tpbs due to api change
  Tests/conf.json
Labels: docs-approved, ready-for-pipeline-running

#39726 CoreIR: remove default from `Retrieve File` Quick Action
  Packs/Core/Integrations/CortexCoreIR/CortexCoreIR.yml
  Packs/Core/ReleaseNotes/3_2_38.md
  Packs/Core/pack_metadata.json
Labels: docs-approved, ForceMerge, ready-for-pipeline-running

#39727 Fix for playbooks that alert will not close automatically
  Packs/CortexResponseAndRemediation/Playbooks/playbook-Azure_AD_account_unlock_or_password_reset.yml
  Packs/CortexResponseAndRemediation/Playbooks/playbook-Exchange_forwarding_rule_configured.yml
  Packs/CortexResponseAndRemediation/ReleaseNotes/1_1_38.md
  Packs/CortexResponseAndRemediation/doc_files/Azure_AD_account_unlock_or_password_reset.png
  Packs/CortexResponseAndRemediation/doc_files/Exchange_forwarding_rule_configured.png
  Packs/CortexResponseAndRemediation/pack_metadata.json
Labels: docs-approved, ready-for-pipeline-running

#39715 ExtraHop Release 2.3.1
  Packs/ExtraHop/Integrations/ExtraHop_v2/ExtraHop_v2.py
  Packs/ExtraHop/Integrations/ExtraHop_v2/ExtraHop_v2.yml
  Packs/ExtraHop/Integrations/ExtraHop_v2/ExtraHop_v2_test.py
  Packs/ExtraHop/Integrations/ExtraHop_v2/README.md
  Packs/ExtraHop/ReleaseNotes/2_3_1.md
  Packs/ExtraHop/pack_metadata.json
Labels: Contribution, docs-approved, Partner, Contribution Form Filled, Partner Support Level, External PR, Partner-Approved

#39651 Active Directory Query v2: Fixed ad-add-to-group command
  Packs/Active_Directory_Query/Integrations/Active_Directory_Query/Active_Directory_Query.py
  Packs/Active_Directory_Query/ReleaseNotes/1_6_49.md
  Packs/Active_Directory_Query/pack_metadata.json
Labels: docs-approved, ForceMerge, ready-for-pipeline-running

#39722 ansible-runner: update docker tag
  Packs/AnsibleAlibabaCloud/Integrations/AnsibleAlibabaCloud/AnsibleAlibabaCloud.yml
  Packs/AnsibleAlibabaCloud/ReleaseNotes/1_0_12.md
  Packs/AnsibleAlibabaCloud/pack_metadata.json
  Packs/AnsibleAzure/Integrations/AnsibleAzure/AnsibleAzure.yml
  Packs/AnsibleAzure/ReleaseNotes/1_0_14.md
  Packs/AnsibleAzure/pack_metadata.json
  Packs/AnsibleCiscoIOS/Integrations/AnsibleCiscoIOS/AnsibleCiscoIOS.yml
  Packs/AnsibleCiscoIOS/ReleaseNotes/1_0_14.md
  Packs/AnsibleCiscoIOS/pack_metadata.json
  Packs/AnsibleCiscoNXOS/Integrations/AnsibleCiscoNXOS/AnsibleCiscoNXOS.yml
  Packs/AnsibleCiscoNXOS/ReleaseNotes/1_0_12.md
  Packs/AnsibleCiscoNXOS/pack_metadata.json
  Packs/AnsibleHetznerCloud/Integrations/AnsibleHCloud/AnsibleHCloud.yml
  Packs/AnsibleHetznerCloud/ReleaseNotes/1_0_12.md
  Packs/AnsibleHetznerCloud/pack_metadata.json
  Packs/AnsibleKubernetes/Integrations/AnsibleKubernetes/AnsibleKubernetes.yml
  Packs/AnsibleKubernetes/ReleaseNotes/1_0_13.md
  Packs/AnsibleKubernetes/pack_metadata.json
  Packs/AnsibleLinux/Integrations/AnsibleACME/AnsibleACME.yml
  Packs/AnsibleLinux/Integrations/AnsibleDNS/AnsibleDNS.yml
  Packs/AnsibleLinux/Integrations/AnsibleLinux/AnsibleLinux.yml
  Packs/AnsibleLinux/Integrations/AnsibleOpenSSL/AnsibleOpenSSL.yml
  Packs/AnsibleLinux/ReleaseNotes/1_0_15.md
  Packs/AnsibleLinux/pack_metadata.json
  Packs/AnsibleMicrosoftWindows/Integrations/AnsibleMicrosoftWindows/AnsibleMicrosoftWindows.yml
  Packs/AnsibleMicrosoftWindows/ReleaseNotes/1_0_15.md
  Packs/AnsibleMicrosoftWindows/pack_metadata.json
  Packs/AnsibleVMware/Integrations/AnsibleVMware/AnsibleVMware.yml
  Packs/AnsibleVMware/ReleaseNotes/1_0_12.md
  Packs/AnsibleVMware/pack_metadata.json
  Packs/SSLCertificates/ReleaseNotes/1_0_8.md
  Packs/SSLCertificates/Scripts/GenerateCSR/GenerateCSR.yml
  Packs/SSLCertificates/Scripts/SSLVerifierV2/SSLVerifierV2.yml
  Packs/SSLCertificates/Scripts/SSLVerifierV2GenerateEmailBody/SSLVerifierV2GenerateEmailBody.yml
  Packs/SSLCertificates/pack_metadata.json
Labels: docs-approved, ForceMerge, ready-for-pipeline-running

#39604 Dataminr Release 1.0.14
  Packs/DataminrPulse/.pack-ignore
  Packs/DataminrPulse/Integrations/DataminrPulse/DataminrPulse.py
  Packs/DataminrPulse/Integrations/DataminrPulse/DataminrPulse.yml
  Packs/DataminrPulse/Integrations/DataminrPulse/README.md
  Packs/DataminrPulse/Integrations/DataminrPulse/test_data/fetch_incident_incidents.json
  Packs/DataminrPulse/Layouts/layoutscontainer-Dataminr_Pulse_Alert.json
  Packs/DataminrPulse/Playbooks/playbook-Retrieve_Related_Alerts_-_Dataminr_Pulse.yml
  Packs/DataminrPulse/Playbooks/playbook-Retrieve_Related_Alerts_-_Dataminr_Pulse_README.md
  Packs/DataminrPulse/ReleaseNotes/1_0_14.md
  Packs/DataminrPulse/doc_files/Retrieve_Related_Alerts_-_Dataminr_Pulse.png
  Packs/DataminrPulse/pack_metadata.json
Labels: Contribution, docs-approved, Partner, pending-demo, Contribution Form Filled, Partner Support Level, External PR, Security Review, Partner-Approved, Security Approved

#39728 CrowdStrike Indicator Feed - 401 error code bug
  Packs/FeedCrowdstrikeFalconIntel/Integrations/CrowdStrikeIndicatorFeed/CrowdStrikeIndicatorFeed.py
  Packs/FeedCrowdstrikeFalconIntel/Integrations/CrowdStrikeIndicatorFeed/CrowdStrikeIndicatorFeed.yml
  Packs/FeedCrowdstrikeFalconIntel/Integrations/CrowdStrikeIndicatorFeed/CrowdStrikeIndicatorFeed_test.py
  Packs/FeedCrowdstrikeFalconIntel/ReleaseNotes/2_1_21.md
  Packs/FeedCrowdstrikeFalconIntel/pack_metadata.json
Labels: docs-approved, ready-for-pipeline-running

#39742 Lansweeper Release 1.0.12
  Packs/Lansweeper/.pack-ignore
  Packs/Lansweeper/Integrations/Lansweeper/Lansweeper.py
  Packs/Lansweeper/Integrations/Lansweeper/Lansweeper.yml
  Packs/Lansweeper/Integrations/Lansweeper/test_data/ip_hunt_command_response.json
  Packs/Lansweeper/ReleaseNotes/1_0_12.md
  Packs/Lansweeper/pack_metadata.json
Labels: Contribution, docs-approved, Partner, pending-demo, Contribution Form Filled, Partner Support Level, External PR, Partner-Approved

#39550 CTM360 Pack Update - Fetch Evidence
  Packs/CTM360-CyberBlindspot/.pack-ignore
  Packs/CTM360-CyberBlindspot/IncidentTypes/CyberBlindspot_Incident.json
  Packs/CTM360-CyberBlindspot/Integrations/CyberBlindspot/CyberBlindspot.py
  Packs/CTM360-CyberBlindspot/Integrations/CyberBlindspot/CyberBlindspot.yml
  Packs/CTM360-CyberBlindspot/Integrations/CyberBlindspot/CyberBlindspot_test.py
  Packs/CTM360-CyberBlindspot/Integrations/CyberBlindspot/README.md
  Packs/CTM360-CyberBlindspot/Integrations/CyberBlindspot/test_data/fetch_incidents_response_valid.json
  Packs/CTM360-CyberBlindspot/Integrations/CyberBlindspot/test_data/incident_details_response_valid.json
  Packs/CTM360-CyberBlindspot/Playbooks/playbook-CyberBlindspot_Incident_Management_V3.yml
  Packs/CTM360-CyberBlindspot/Playbooks/playbook-CyberBlindspot_Incident_Management_V3_README.md
  Packs/CTM360-CyberBlindspot/Playbooks/playbook-CyberBlindspot_Retrieve_Incident_Screenshots.yml
  Packs/CTM360-CyberBlindspot/Playbooks/playbook-CyberBlindspot_Retrieve_Incident_Screenshots_README.md
  Packs/CTM360-CyberBlindspot/ReleaseNotes/2_2_0.md
  Packs/CTM360-CyberBlindspot/doc_files/CyberBlindspot_Incident_Management_V3.png
  Packs/CTM360-CyberBlindspot/doc_files/CyberBlindspot_Retrieve_Incident_Screenshots.png
  Packs/CTM360-CyberBlindspot/pack_metadata.json
Labels: Contribution, Partner, Contribution Form Filled, pending-contributor, Partner Support Level, External PR, Security Review, Partner-Approved, Security Approved

#39515 update netutil docker
  Packs/CertStream/Integrations/CertStream/CertStream.yml
  Packs/CertStream/ReleaseNotes/1_0_5.md
  Packs/CertStream/pack_metadata.json
  Packs/CommonScripts/ReleaseNotes/1_19_50.md
  Packs/CommonScripts/Scripts/Dig/Dig.yml
  Packs/CommonScripts/Scripts/GetDomainDNSDetails/GetDomainDNSDetails.yml
  Packs/CommonScripts/Scripts/Ping/Ping.yml
  Packs/CommonScripts/pack_metadata.json
  Packs/DeveloperTools/ReleaseNotes/1_3_31.md
  Packs/DeveloperTools/Scripts/CompareIndicators/CompareIndicators.yml
  Packs/DeveloperTools/pack_metadata.json
  Packs/FeedGCPWhitelist/Integrations/FeedGCPWhitelist/FeedGCPWhitelist.yml
  Packs/FeedGCPWhitelist/ReleaseNotes/2_0_44.md
  Packs/FeedGCPWhitelist/pack_metadata.json
  Packs/FeedPublicDNS/Integrations/FeedPublicDNS/FeedPublicDNS.yml
  Packs/FeedPublicDNS/ReleaseNotes/1_0_20.md
  Packs/FeedPublicDNS/pack_metadata.json
  Packs/FiltersAndTransformers/ReleaseNotes/1_2_93.md
  Packs/FiltersAndTransformers/Scripts/IPv4Blacklist/IPv4Blacklist.yml
  Packs/FiltersAndTransformers/Scripts/IPv4Whitelist/IPv4Whitelist.yml
  Packs/FiltersAndTransformers/Scripts/IsRFC1918Address/IsRFC1918Address.yml
  Packs/FiltersAndTransformers/pack_metadata.json
  Packs/Mattermost/Integrations/MattermostV2/MattermostV2.yml
  Packs/Mattermost/ReleaseNotes/2_1_1.md
  Packs/Mattermost/pack_metadata.json
  Packs/Nmap/Integrations/Nmap/Nmap.yml
  Packs/Nmap/ReleaseNotes/1_2_9.md
  Packs/Nmap/pack_metadata.json
  Packs/RetarusSecureEmailGateway/Integrations/RetarusSecureEmailGateway/RetarusSecureEmailGateway.yml
  Packs/RetarusSecureEmailGateway/ReleaseNotes/1_0_2.md
  Packs/RetarusSecureEmailGateway/pack_metadata.json
  Packs/Tufin/Integrations/Tufin/Tufin.yml
  Packs/Tufin/ReleaseNotes/1_2_8.md
  Packs/Tufin/pack_metadata.json
Labels: docs-approved, ForceMerge, ready-for-pipeline-running

#39725 vendors-sdk: update docker tag
  Packs/DomainTools_Iris/Integrations/DomainTools_Iris/DomainTools_Iris.yml
  Packs/DomainTools_Iris/ReleaseNotes/2_2_2.md
  Packs/DomainTools_Iris/pack_metadata.json
  Packs/DuoAdminApi/Integrations/DuoAdminApi/DuoAdminApi.yml
  Packs/DuoAdminApi/Integrations/DuoEventCollector/DuoEventCollector.yml
  Packs/DuoAdminApi/ReleaseNotes/4_0_26.md
  Packs/DuoAdminApi/pack_metadata.json
  Packs/FeedDomainTools/Integrations/FeedDomainTools/FeedDomainTools.yml
  Packs/FeedDomainTools/ReleaseNotes/1_0_2.md
  Packs/FeedDomainTools/pack_metadata.json
  Packs/GroupIB_ThreatIntelligenceAttribution/Integrations/GroupIBTIA/GroupIBTIA.yml
  Packs/GroupIB_ThreatIntelligenceAttribution/Integrations/GroupIB_TIA_Feed/GroupIB_TIA_Feed.yml
  Packs/GroupIB_ThreatIntelligenceAttribution/ReleaseNotes/2_0_1.md
  Packs/GroupIB_ThreatIntelligenceAttribution/pack_metadata.json
  Packs/HashiCorp-Vault/Integrations/HashiCorpVault/HashiCorpVault.yml
  Packs/HashiCorp-Vault/ReleaseNotes/1_1_30.md
  Packs/HashiCorp-Vault/pack_metadata.json
  Packs/JoeSecurity/Integrations/JoeSecurityV2/JoeSecurityV2.yml
  Packs/JoeSecurity/ReleaseNotes/1_1_27.md
  Packs/JoeSecurity/pack_metadata.json
  Packs/Kafka/Integrations/KafkaV3/KafkaV3.yml
  Packs/Kafka/ReleaseNotes/2_1_2.md
  Packs/Kafka/pack_metadata.json
  Packs/TeamCymru/Integrations/TeamCymru/TeamCymru.yml
  Packs/TeamCymru/ReleaseNotes/2_0_5.md
  Packs/TeamCymru/pack_metadata.json
Labels: docs-approved, ForceMerge, ready-for-pipeline-running

#39733 update `fastapi` tag
  Packs/AWS-SNS-Listener/Integrations/AWSSNSListener/AWSSNSListener.yml
  Packs/AWS-SNS-Listener/ReleaseNotes/1_0_10.md
  Packs/AWS-SNS-Listener/pack_metadata.json
  Packs/GenericWebhook/Integrations/GenericWebhook/GenericWebhook.yml
  Packs/GenericWebhook/ReleaseNotes/1_1_9.md
  Packs/GenericWebhook/pack_metadata.json
  Packs/GenericWebhook_FormData/Integrations/GenericWebhookFormData/GenericWebhookFormData.yml
  Packs/GenericWebhook_FormData/ReleaseNotes/1_0_3.md
  Packs/GenericWebhook_FormData/pack_metadata.json
  Packs/GitLab/Integrations/GitLabEventCollector/GitLabEventCollector.yml
  Packs/GitLab/ReleaseNotes/2_2_29.md
  Packs/GitLab/pack_metadata.json
  Packs/Okta/Integrations/OktaEventCollector/OktaEventCollector.yml
  Packs/Okta/ReleaseNotes/3_3_15.md
  Packs/Okta/pack_metadata.json
  Packs/PublishList/Integrations/PublishList/PublishList.yml
  Packs/PublishList/ReleaseNotes/1_1_8.md
  Packs/PublishList/pack_metadata.json
  Packs/SimpleAPIProxy/Integrations/SimpleAPIProxy/SimpleAPIProxy.yml
  Packs/SimpleAPIProxy/ReleaseNotes/1_0_8.md
  Packs/SimpleAPIProxy/pack_metadata.json
  Packs/Zoom/Integrations/Zoom/Zoom.yml
  Packs/Zoom/ReleaseNotes/1_6_28.md
  Packs/Zoom/Scripts/ZoomAsk/ZoomAsk.yml
  Packs/Zoom/pack_metadata.json
Labels: ForceMerge, ready-for-pipeline-running

#39749 Fix sso with suspicious characterisitcs
  Packs/CortexResponseAndRemediation/Playbooks/playbook-SSO_Authentication_With_Suspicious_Characteristics.yml
  Packs/CortexResponseAndRemediation/Playbooks/silent-playbook-SSO_Authentication_With_Suspicious_Characteristics_Test.yml
  Packs/CortexResponseAndRemediation/Playbooks/silent-playbook-Suspicious_user_access_to_multiple_resources_via_SSO.yml
  Packs/CortexResponseAndRemediation/ReleaseNotes/1_1_39.md
  Packs/CortexResponseAndRemediation/pack_metadata.json
Labels: ready-for-pipeline-running

#39734 Nbensalmon/ciac 13492/updato to newest cvss versions
  Packs/FeedNVDv2/.pack-ignore
  Packs/FeedNVDv2/Integrations/FeedNVDv2/FeedNVDv2.py
  Packs/FeedNVDv2/Integrations/FeedNVDv2/FeedNVDv2.yml
  Packs/FeedNVDv2/Integrations/FeedNVDv2/FeedNVDv2_description.md
  Packs/FeedNVDv2/Integrations/FeedNVDv2/FeedNVDv2_test.py
  Packs/FeedNVDv2/Integrations/FeedNVDv2/README.md
  Packs/FeedNVDv2/Integrations/FeedNVDv2/test_data/indicator.json
  Packs/FeedNVDv2/Integrations/FeedNVDv2/test_data/nist_response.json
  Packs/FeedNVDv2/Integrations/FeedNVDv2/test_data/war_room_entry.json
  Packs/FeedNVDv2/ReleaseNotes/1_0_8.md
  Packs/FeedNVDv2/pack_metadata.json
Labels: docs-approved, ready-for-pipeline-running

#39569 Rubrik Release 1.5.0
  Packs/RubrikPolaris/.pack-ignore
  Packs/RubrikPolaris/.secrets-ignore
  Packs/RubrikPolaris/Classifiers/classifier-Rubrik_Polaris_Radar_-_Mapping.json
  Packs/RubrikPolaris/IncidentFields/incidentfield-Rubrik_Polaris_Activity_Type.json
  Packs/RubrikPolaris/Integrations/RubrikPolaris/README.md
  Packs/RubrikPolaris/Integrations/RubrikPolaris/RubrikPolaris.py
  Packs/RubrikPolaris/Integrations/RubrikPolaris/RubrikPolaris.yml
  Packs/RubrikPolaris/Integrations/RubrikPolaris/RubrikPolaris_test.py
  Packs/RubrikPolaris/Integrations/RubrikPolaris/test_data/enum_values.json
  Packs/RubrikPolaris/Integrations/RubrikPolaris/test_data/radar_anomaly_status_update_false_positive_hr.md
  Packs/RubrikPolaris/Integrations/RubrikPolaris/test_data/radar_anomaly_status_update_false_positive_response.json
  Packs/RubrikPolaris/Integrations/RubrikPolaris/test_data/radar_anomaly_status_update_hr.md
  Packs/RubrikPolaris/Integrations/RubrikPolaris/test_data/radar_anomaly_status_update_response.json
  Packs/RubrikPolaris/Integrations/RubrikPolaris/test_data/radar_suspicious_file_list_hr.md
  Packs/RubrikPolaris/Integrations/RubrikPolaris/test_data/radar_suspicious_file_list_response.json
  Packs/RubrikPolaris/Layouts/layoutscontainer-Rubrik_Polaris_Radar.json
  Packs/RubrikPolaris/Playbooks/playbook-Rubrik_Retrieve_Anomaly_Result_-_Rubrik_Security_Cloud.yml
  Packs/RubrikPolaris/Playbooks/playbook-Rubrik_Retrieve_Anomaly_Result_-_Rubrik_Security_Cloud_README.md
  Packs/RubrikPolaris/Playbooks/playbook-Rubrik_Update_Anomaly_Status_-_Rubrik_Security_Cloud.yml
  Packs/RubrikPolaris/Playbooks/playbook-Rubrik_Update_Anomaly_Status_-_Rubrik_Security_Cloud_README.md
  Packs/RubrikPolaris/Playbooks/playbook-Rubrik_Workload_Analysis_-_Rubrik_Security_Cloud.yml
  Packs/RubrikPolaris/Playbooks/playbook-Rubrik_Workload_Analysis_-_Rubrik_Security_Cloud_README.md
  Packs/RubrikPolaris/ReleaseNotes/1_5_0.md
  Packs/RubrikPolaris/Scripts/RubrikSetIncidentSeverityUsingWorkLoadRiskLevel/RubrikSetIncidentSeverityUsingWorkLoadRiskLevel.py
  Packs/RubrikPolaris/Scripts/RubrikSetIncidentSeverityUsingWorkLoadRiskLevel/RubrikSetIncidentSeverityUsingWorkLoadRiskLevel.yml
  Packs/RubrikPolaris/doc_files/Rubrik_Retrieve_Anomaly_Result_-_Rubrik_Security_Cloud.png
  Packs/RubrikPolaris/doc_files/Rubrik_Update_Anomaly_Status_-_Rubrik_Security_Cloud.png
  Packs/RubrikPolaris/doc_files/Rubrik_Workload_Analysis_-_Rubrik_Security_Cloud.png
  Packs/RubrikPolaris/pack_metadata.json
Labels: Contribution, docs-approved, Partner, pending-demo, Contribution Form Filled, pending-contributor, Partner Support Level, External PR, Security Review, Partner-Approved, Security Approved

#39607 XQLDSHelper - Fixed an issue where caching was not working when using context filters.
  Packs/XQLDSHelper/ReleaseNotes/1_0_6.md
  Packs/XQLDSHelper/Scripts/XQLDSHelper/XQLDSHelper.py
  Packs/XQLDSHelper/Scripts/XQLDSHelper/XQLDSHelper.yml
  Packs/XQLDSHelper/Scripts/XQLDSHelper/test_data/test-others.json
  Packs/XQLDSHelper/pack_metadata.json
Labels: Contribution, docs-approved, pending-demo, Contribution Form Filled, Community, pending-contributor, Community Support Level, External PR

#39741 Add Lookback
  Packs/GmailSingleUser/Integrations/GmailSingleUser/GmailSingleUser.py
  Packs/GmailSingleUser/Integrations/GmailSingleUser/GmailSingleUser_test.py
  Packs/GmailSingleUser/ReleaseNotes/1_4_13.md
  Packs/GmailSingleUser/pack_metadata.json
Labels: ForceMerge, ready-for-pipeline-running

#39704 AdminConsent
  Packs/CortexResponseAndRemediation/Playbooks/silent-playbook-First_seen_Azure_admin_consent_to_an_application.yml
  Packs/CortexResponseAndRemediation/ReleaseNotes/1_1_40.md
  Packs/CortexResponseAndRemediation/Triggers/silent-Trigger_-_First_seen_Azure_admin_consent_to_an_application.json
  Packs/CortexResponseAndRemediation/pack_metadata.json
Labels: docs-approved, ready-for-pipeline-running

#39766 skipped saas security tpb as its being blocked by SCA-8028
  Tests/conf.json
Labels: docs-approved, ready-for-pipeline-running

#39767 Ys profpoint non beta
  Packs/ProofpointThreatResponse/Integrations/ProofpointThreatResponse/ProofpointThreatResponse.yml
  Packs/ProofpointThreatResponse/ReleaseNotes/2_0_25.md
  Packs/ProofpointThreatResponse/pack_metadata.json
Labels: docs-approved, ready-for-pipeline-running

#39771 ansible-runner: update tocker tag in content items
  Packs/AnsibleAlibabaCloud/Integrations/AnsibleAlibabaCloud/AnsibleAlibabaCloud.yml
  Packs/AnsibleAlibabaCloud/ReleaseNotes/1_0_13.md
  Packs/AnsibleAlibabaCloud/pack_metadata.json
  Packs/AnsibleAzure/Integrations/AnsibleAzure/AnsibleAzure.yml
  Packs/AnsibleAzure/ReleaseNotes/1_0_16.md
  Packs/AnsibleAzure/pack_metadata.json
  Packs/AnsibleCiscoIOS/Integrations/AnsibleCiscoIOS/AnsibleCiscoIOS.yml
  Packs/AnsibleCiscoIOS/ReleaseNotes/1_0_15.md
  Packs/AnsibleCiscoIOS/pack_metadata.json
  Packs/AnsibleCiscoNXOS/Integrations/AnsibleCiscoNXOS/AnsibleCiscoNXOS.yml
  Packs/AnsibleCiscoNXOS/ReleaseNotes/1_0_13.md
  Packs/AnsibleCiscoNXOS/pack_metadata.json
  Packs/AnsibleHetznerCloud/Integrations/AnsibleHCloud/AnsibleHCloud.yml
  Packs/AnsibleHetznerCloud/ReleaseNotes/1_0_13.md
  Packs/AnsibleHetznerCloud/pack_metadata.json
  Packs/AnsibleKubernetes/Integrations/AnsibleKubernetes/AnsibleKubernetes.yml
  Packs/AnsibleKubernetes/ReleaseNotes/1_0_14.md
  Packs/AnsibleKubernetes/pack_metadata.json
  Packs/AnsibleLinux/Integrations/AnsibleACME/AnsibleACME.yml
  Packs/AnsibleLinux/Integrations/AnsibleDNS/AnsibleDNS.yml
  Packs/AnsibleLinux/Integrations/AnsibleLinux/AnsibleLinux.yml
  Packs/AnsibleLinux/Integrations/AnsibleOpenSSL/AnsibleOpenSSL.yml
  Packs/AnsibleLinux/ReleaseNotes/1_0_16.md
  Packs/AnsibleLinux/pack_metadata.json
  Packs/AnsibleMicrosoftWindows/Integrations/AnsibleMicrosoftWindows/AnsibleMicrosoftWindows.yml
  Packs/AnsibleMicrosoftWindows/ReleaseNotes/1_0_16.md
  Packs/AnsibleMicrosoftWindows/pack_metadata.json
  Packs/AnsibleVMware/Integrations/AnsibleVMware/AnsibleVMware.yml
  Packs/AnsibleVMware/ReleaseNotes/1_0_13.md
  Packs/AnsibleVMware/pack_metadata.json
  Packs/SSLCertificates/ReleaseNotes/1_0_9.md
  Packs/SSLCertificates/Scripts/GenerateCSR/GenerateCSR.yml
  Packs/SSLCertificates/Scripts/SSLVerifierV2/SSLVerifierV2.yml
  Packs/SSLCertificates/Scripts/SSLVerifierV2GenerateEmailBody/SSLVerifierV2GenerateEmailBody.yml
  Packs/SSLCertificates/pack_metadata.json
Labels: ForceMerge, ready-for-pipeline-running

#39763 FeedDomainTools Release v1.0.3
  Packs/FeedDomainTools/Integrations/FeedDomainTools/FeedDomainTools.py
  Packs/FeedDomainTools/Integrations/FeedDomainTools/FeedDomainTools.yml
  Packs/FeedDomainTools/Integrations/FeedDomainTools/FeedDomainTools_test.py
  Packs/FeedDomainTools/Integrations/FeedDomainTools/README.md
  Packs/FeedDomainTools/Integrations/FeedDomainTools/test_data/feed_mock_response.py
  Packs/FeedDomainTools/README.md
  Packs/FeedDomainTools/ReleaseNotes/1_0_2.md
  Packs/FeedDomainTools/ReleaseNotes/1_0_3.md
  Packs/FeedDomainTools/pack_metadata.json
Labels: Contribution, docs-approved, Partner, Contribution Form Filled, Partner Support Level, External PR, Partner-Approved, TIM Review

#39578 added logs to snowflake
  Packs/Snowflake/Integrations/Snowflake/Snowflake.py
  Packs/Snowflake/Integrations/Snowflake/Snowflake.yml
  Packs/Snowflake/Integrations/Snowflake/Snowflake_test.py
  Packs/Snowflake/ReleaseNotes/1_0_9.md
  Packs/Snowflake/pack_metadata.json
Labels: docs-approved, ready-for-pipeline-running

#39775 Jb_XSUP-48017_date_mismatch
  Packs/ProofpointTAP/Integrations/ProofpointTAP_v2/ProofpointTAP_v2.py
  Packs/ProofpointTAP/Integrations/ProofpointTAP_v2/ProofpointTAP_v2.yml
  Packs/ProofpointTAP/ReleaseNotes/1_2_19.md
  Packs/ProofpointTAP/pack_metadata.json
Labels: docs-approved, ready-for-pipeline-running
