Repository demisto/content, pull requests merged in 2025-03, with the labels that each got.

#38772 Strata Cloud Enhancement
  Packs/PrismaAccess/Integrations/PrismaSASE/PrismaSASE.py
  Packs/PrismaAccess/Integrations/PrismaSASE/PrismaSASE.yml
  Packs/PrismaAccess/Integrations/PrismaSASE/PrismaSASE_description.md
  Packs/PrismaAccess/Integrations/PrismaSASE/PrismaSASE_test.py
  Packs/PrismaAccess/Integrations/PrismaSASE/README.md
  Packs/PrismaAccess/Integrations/PrismaSASE/command_examples.txt
  Packs/PrismaAccess/Integrations/PrismaSASE/test_data/cie_get_user.json
  Packs/PrismaAccess/ReleaseNotes/2_1_14.md
  Packs/PrismaAccess/TestPlaybooks/playbook-PrismaSASE_Test.yml
  Packs/PrismaAccess/pack_metadata.json
Labels: docs-approved

#38811 Fix for missing CVE data in PAN SA
  Packs/PaloAltoNetworks_SecurityAdvisories/Integrations/PaloAltoNetworksSecurityAdvisories/PaloAltoNetworksSecurityAdvisories.py
  Packs/PaloAltoNetworks_SecurityAdvisories/Integrations/PaloAltoNetworksSecurityAdvisories/PaloAltoNetworksSecurityAdvisories.yml
  Packs/PaloAltoNetworks_SecurityAdvisories/Integrations/PaloAltoNetworksSecurityAdvisories/PaloAltoNetworksSecurityAdvisories_test.py
  Packs/PaloAltoNetworks_SecurityAdvisories/ReleaseNotes/1_0_10.md
  Packs/PaloAltoNetworks_SecurityAdvisories/pack_metadata.json
Labels: docs-approved

#38797 Fix docs
  Packs/CiscoSpark/Integrations/CiscoWebexEventCollector/CiscoWebexEventCollector.yml
  Packs/CiscoSpark/Integrations/CiscoWebexEventCollector/CiscoWebexEventCollector_description.md
  Packs/CiscoSpark/Integrations/CiscoWebexEventCollector/README.md
  Packs/CiscoSpark/ReleaseNotes/1_0_12.md
  Packs/CiscoSpark/pack_metadata.json
Labels: docs-approved

#38651 Uploading the Jira pack and the Common Scripts pack
  Packs/CommonScripts/ReleaseNotes/1_19_29.md
  Packs/CommonScripts/Scripts/DeleteContext/DeleteContext.yml
  Packs/CommonScripts/pack_metadata.json
  Packs/Jira/Integrations/JiraV3/JiraV3.py
  Packs/Jira/Integrations/JiraV3/JiraV3.yml
  Packs/Jira/ReleaseNotes/3_2_15.md
  Packs/Jira/pack_metadata.json
Labels: docs-approved

#38632 Move EWS commands logic to EWS API module
  Packs/ApiModules/Scripts/EWSApiModule/EWSApiModule.py
  Packs/ApiModules/Scripts/EWSApiModule/EWSApiModule_test.py
  Packs/MicrosoftExchangeOnPremise/Integrations/EWSv2/EWSv2.py
  Packs/MicrosoftExchangeOnPremise/Integrations/EWSv2/EWSv2_test.py
  Packs/MicrosoftExchangeOnPremise/ReleaseNotes/2_2_1.md
  Packs/MicrosoftExchangeOnPremise/pack_metadata.json
  Packs/MicrosoftExchangeOnline/Integrations/EWSO365/EWSO365.py
  Packs/MicrosoftExchangeOnline/Integrations/EWSO365/EWSO365_test.py
  Packs/MicrosoftExchangeOnline/ReleaseNotes/1_6_4.md
  Packs/MicrosoftExchangeOnline/pack_metadata.json
Labels: docs-approved

#38818 only convert to bigint when too high
  Packs/CommonScripts/ReleaseNotes/1_19_30.md
  Packs/CommonScripts/Scripts/Set/Set.js
  Packs/CommonScripts/pack_metadata.json
Labels: docs-approved

#38841 Azure ad audit parsing error CRTX_159264
  Packs/MicrosoftEntraID/ParsingRules/MicrosoftEntraID/MicrosoftEntraID.xif
  Packs/MicrosoftEntraID/README.md
  Packs/MicrosoftEntraID/ReleaseNotes/1_0_8.md
  Packs/MicrosoftEntraID/pack_metadata.json
Labels: docs-approved

#38775 Crtx 146119 bitwarden pm
  Packs/BitwardenPasswordManager/ModelingRules/BitwardenPasswordManager/BitwardenPasswordManager.xif
  Packs/BitwardenPasswordManager/ModelingRules/BitwardenPasswordManager/BitwardenPasswordManager.yml
  Packs/BitwardenPasswordManager/ModelingRules/BitwardenPasswordManager/BitwardenPasswordManager_schema.json
  Packs/BitwardenPasswordManager/README.md
  Packs/BitwardenPasswordManager/ReleaseNotes/1_0_3.md
  Packs/BitwardenPasswordManager/pack_metadata.json
Labels: docs-approved, bypass.url

#38842 fix for filter in SSO password spray playbook
  Packs/CortexResponseAndRemediation/Playbooks/playbook-SSO_Password_Spray.yml
  Packs/CortexResponseAndRemediation/Playbooks/silent-playbook-SSO_Password_Spray_Test.yml
  Packs/CortexResponseAndRemediation/ReleaseNotes/1_1_18.md
  Packs/CortexResponseAndRemediation/pack_metadata.json
Labels: docs-approved

#38840 Yc/unit42 502 error
  Packs/FeedUnit42v2/Integrations/FeedUnit42v2/FeedUnit42v2.py
  Packs/FeedUnit42v2/Integrations/FeedUnit42v2/FeedUnit42v2.yml
  Packs/FeedUnit42v2/ReleaseNotes/1_0_63.md
  Packs/FeedUnit42v2/pack_metadata.json
Labels: ForceMerge

#37806 Generic event collector
  Packs/GenericAPIEventCollector/.pack-ignore
  Packs/GenericAPIEventCollector/.secrets-ignore
  Packs/GenericAPIEventCollector/Integrations/GenericAPIEventCollector/GenericAPIEventCollector.py
  Packs/GenericAPIEventCollector/Integrations/GenericAPIEventCollector/GenericAPIEventCollector.yml
  Packs/GenericAPIEventCollector/Integrations/GenericAPIEventCollector/GenericAPIEventCollector_description.md
  Packs/GenericAPIEventCollector/Integrations/GenericAPIEventCollector/GenericAPIEventCollector_image.png
  Packs/GenericAPIEventCollector/Integrations/GenericAPIEventCollector/GenericAPIEventCollector_test.py
  Packs/GenericAPIEventCollector/Integrations/GenericAPIEventCollector/README.md
  Packs/GenericAPIEventCollector/Integrations/GenericAPIEventCollector/command_examples.txt
  Packs/GenericAPIEventCollector/README.md
  Packs/GenericAPIEventCollector/pack_metadata.json
Labels: docs-approved

#38869 Crowdstrike sandbox Env ID 300 -> 310
  Packs/CrowdStrikeFalconSandbox/Integrations/CrowdStrikeFalconSandboxV2/CrowdStrikeFalconSandboxV2.yml
  Packs/CrowdStrikeFalconSandbox/Integrations/CrowdStrikeFalconSandboxV2/README.md
  Packs/CrowdStrikeFalconSandbox/ReleaseNotes/2_0_24.md
  Packs/CrowdStrikeFalconSandbox/pack_metadata.json
Labels: docs-approved

#38872 Fixed Prisma Access README pack
  Packs/PrismaAccess/README.md
Labels: docs-approved

#38747 CRTX-151833-Proofpoint-Pps
  Packs/ProofpointServerProtection/Integrations/ProofpointServerProtection/ProofpointServerProtection.yml
  Packs/ProofpointServerProtection/ModelingRules/ProofpointServerProtection/ProofpointServerProtection.xif
  Packs/ProofpointServerProtection/ModelingRules/ProofpointServerProtection/ProofpointServerProtection.yml
  Packs/ProofpointServerProtection/ModelingRules/ProofpointServerProtection/ProofpointServerProtection_schema.json
  Packs/ProofpointServerProtection/ParsingRules/ProofpointServerProtection/ProofpointServerProtection.xif
  Packs/ProofpointServerProtection/ParsingRules/ProofpointServerProtection/ProofpointServerProtection.yml
  Packs/ProofpointServerProtection/README.md
  Packs/ProofpointServerProtection/ReleaseNotes/2_1_9.md
  Packs/ProofpointServerProtection/pack_metadata.json
Labels: docs-approved, bypass.url

#38673 Freshservice add pagination to fetch
  Packs/FreshworksFreshservice/Integrations/FreshworksFreshservice/FreshworksFreshservice.py
  Packs/FreshworksFreshservice/Integrations/FreshworksFreshservice/FreshworksFreshservice.yml
  Packs/FreshworksFreshservice/Integrations/FreshworksFreshservice/README.md
  Packs/FreshworksFreshservice/ReleaseNotes/1_1_0.md
  Packs/FreshworksFreshservice/pack_metadata.json
Labels: docs-approved

#38785 AlienVault OTX v2 - Catch timeout error due to indicator not found
  Packs/AlienVault_OTX/Integrations/AlienVault_OTX_v2/AlienVault_OTX_v2.py
  Packs/AlienVault_OTX/Integrations/AlienVault_OTX_v2/AlienVault_OTX_v2.yml
  Packs/AlienVault_OTX/Integrations/AlienVault_OTX_v2/AlienVault_OTX_v2_test.py
  Packs/AlienVault_OTX/ReleaseNotes/1_1_44.md
  Packs/AlienVault_OTX/pack_metadata.json
Labels: docs-approved

#38725 Deprecate DomainTools Enterprise Integrations
  Packs/DomainTools/Integrations/DomainTools/DomainTools.yml
  Packs/DomainTools/ReleaseNotes/1_1_7.md
  Packs/DomainTools/pack_metadata.json
  Tests/conf.json
Labels: Contribution, docs-approved, Partner, Contribution Form Filled, ForceMerge, Partner Support Level, External PR, Partner-Approved

#38847 fix get-last-run-results command
  Packs/ProofpointEmailSecurity/Integrations/ProofpointEmailSecurityEventCollector/ProofpointEmailSecurityEventCollector.py
  Packs/ProofpointEmailSecurity/Integrations/ProofpointEmailSecurityEventCollector/ProofpointEmailSecurityEventCollector_test.py
  Packs/ProofpointEmailSecurity/ReleaseNotes/1_0_9.md
  Packs/ProofpointEmailSecurity/pack_metadata.json
Labels: docs-approved

#38771 Azure app service enhancement ya
  Packs/AzureAppService/ModelingRules/AzureAppService/AzureAppService.xif
  Packs/AzureAppService/ModelingRules/AzureAppService/AzureAppService_schema.json
  Packs/AzureAppService/ParsingRules/AzureAppService/AzureAppService.xif
  Packs/AzureAppService/ReleaseNotes/1_0_1.md
  Packs/AzureAppService/pack_metadata.json
Labels: docs-approved

#38882 Remove Deprecated Env ID from CS FalconX
  Packs/CrowdStrikeFalconX/Integrations/CrowdStrikeFalconX/CrowdStrikeFalconX.py
  Packs/CrowdStrikeFalconX/Integrations/CrowdStrikeFalconX/CrowdStrikeFalconX.yml
  Packs/CrowdStrikeFalconX/Integrations/CrowdStrikeFalconX/README.md
  Packs/CrowdStrikeFalconX/ReleaseNotes/1_2_40.md
  Packs/CrowdStrikeFalconX/pack_metadata.json
  Tests/conf.json
Labels: docs-approved

#38900 Azure AD Audit - 'parsed_fields' enhancement
  Packs/MicrosoftEntraID/ParsingRules/MicrosoftEntraID/MicrosoftEntraID.xif
  Packs/MicrosoftEntraID/ReleaseNotes/1_0_9.md
  Packs/MicrosoftEntraID/pack_metadata.json
Labels: docs-approved, bypass.url

#38722 SentinelOne V2 - 3.2.37
  Packs/SentinelOne/Integrations/SentinelOne-V2/README.md
  Packs/SentinelOne/Integrations/SentinelOne-V2/SentinelOne-V2.py
  Packs/SentinelOne/Integrations/SentinelOne-V2/SentinelOne-V2.yml
  Packs/SentinelOne/Integrations/SentinelOne-V2/SentinelOne-V2_test.py
  Packs/SentinelOne/Integrations/SentinelOne-V2/test_data/get_service_users_page_1_response.json
  Packs/SentinelOne/Integrations/SentinelOne-V2/test_data/get_service_users_page_2_response.json
  Packs/SentinelOne/Integrations/SentinelOne-V2/test_data/get_service_users_response.json
  Packs/SentinelOne/Integrations/SentinelOne-V2/test_data/get_singularity_marketplace_apps_page_1_response.json
  Packs/SentinelOne/Integrations/SentinelOne-V2/test_data/get_singularity_marketplace_apps_page_2_response.json
  Packs/SentinelOne/ReleaseNotes/3_2_37.md
  Packs/SentinelOne/pack_metadata.json
Labels: Contribution, docs-approved, Partner, pending-demo, post-demo, Contribution Form Filled, pending-contributor, Partner Support Level, External PR, Partner-Approved

#38907 changed the actions/cache from deprecated version to v4
  .github/workflows/close_jira_issue_by_pr_merge.yml
  .github/workflows/link_edited_pr_to_jira_issue.yml
Labels: docs-approved

#38810 Add command for creating incident to the AzureSentinel integration
  Packs/AzureSentinel/CONTRIBUTORS.json
  Packs/AzureSentinel/Integrations/AzureSentinel/AzureSentinel.py
  Packs/AzureSentinel/Integrations/AzureSentinel/AzureSentinel.yml
  Packs/AzureSentinel/Integrations/AzureSentinel/AzureSentinel_test.py
  Packs/AzureSentinel/Integrations/AzureSentinel/README.md
  Packs/AzureSentinel/README.md
  Packs/AzureSentinel/ReleaseNotes/1_5_58.md
  Packs/AzureSentinel/pack_metadata.json
Labels: Contribution, docs-approved, Contribution Form Filled, Community, Xsoar Support Level, External PR

#38754 bug - Incorrect .yml file type 9 hidden field
  Packs/Rapid7AppSec/Integrations/Rapid7AppSec/Rapid7AppSec.py
  Packs/Rapid7AppSec/Integrations/Rapid7AppSec/Rapid7AppSec.yml
  Packs/Rapid7AppSec/ReleaseNotes/1_0_6.md
  Packs/Rapid7AppSec/pack_metadata.json
Labels: docs-approved

#38897 Splunkpy - improved the description of the timezone parameter
  Packs/SplunkPy/Integrations/SplunkPy/SplunkPy.yml
  Packs/SplunkPy/ReleaseNotes/3_2_4.md
  Packs/SplunkPy/pack_metadata.json
Labels: docs-approved

#38901 Unrestricted urlib3
  poetry.lock
  pyproject.toml
Labels: docs-approved

#38742 [ArcSight ESM v2] Fix JSON parsing for responses with quoted string values
  Packs/ArcSightESM/Integrations/ArcSightESMv2/ArcSightESMv2.py
  Packs/ArcSightESM/Integrations/ArcSightESMv2/ArcSightESMv2.yml
  Packs/ArcSightESM/Integrations/ArcSightESMv2/ArcSightESMv2_test.py
  Packs/ArcSightESM/ReleaseNotes/1_2_5.md
  Packs/ArcSightESM/pack_metadata.json
Labels: docs-approved

#38858 Fix focepoint dlp dataset
  Packs/ForcepointDLP/ParsingRules/ForcepointDLP/ForcepointDLP.xif
  Packs/ForcepointDLP/ReleaseNotes/1_0_11.json
  Packs/ForcepointDLP/ReleaseNotes/1_0_11.md
  Packs/ForcepointDLP/pack_metadata.json
Labels: docs-approved

#38892 [Google Threat Intelligence] Feed Threat Lists Integration
  Packs/GoogleThreatIntelligence/Integrations/FeedThreatLists/FeedThreatLists.py
  Packs/GoogleThreatIntelligence/Integrations/FeedThreatLists/FeedThreatLists.yml
  Packs/GoogleThreatIntelligence/Integrations/FeedThreatLists/FeedThreatLists_description.md
  Packs/GoogleThreatIntelligence/Integrations/FeedThreatLists/FeedThreatLists_image.png
  Packs/GoogleThreatIntelligence/Integrations/FeedThreatLists/FeedThreatLists_test.py
  Packs/GoogleThreatIntelligence/Integrations/FeedThreatLists/README.md
  Packs/GoogleThreatIntelligence/Integrations/FeedThreatLists/test_data/domain.json
  Packs/GoogleThreatIntelligence/Integrations/FeedThreatLists/test_data/file.json
  Packs/GoogleThreatIntelligence/Integrations/FeedThreatLists/test_data/ip.json
  Packs/GoogleThreatIntelligence/Integrations/FeedThreatLists/test_data/url.json
  Packs/GoogleThreatIntelligence/ReleaseNotes/1_3_0.md
  Packs/GoogleThreatIntelligence/pack_metadata.json
Labels: Contribution, docs-approved, Partner, Contribution Form Filled, Partner Support Level, External PR, Partner-Approved, TIM Review

#38696 Cybel angel commands
  Packs/CybelAngel/.secrets-ignore
  Packs/CybelAngel/Integrations/CybelAngelEventCollector/CybelAngelEventCollector.py
  Packs/CybelAngel/Integrations/CybelAngelEventCollector/CybelAngelEventCollector.yml
  Packs/CybelAngel/Integrations/CybelAngelEventCollector/CybelAngelEventCollector_description.md
  Packs/CybelAngel/Integrations/CybelAngelEventCollector/CybelAngelEventCollector_test.py
  Packs/CybelAngel/Integrations/CybelAngelEventCollector/README.md
  Packs/CybelAngel/Integrations/CybelAngelEventCollector/command_examples.txt
  Packs/CybelAngel/Integrations/CybelAngelEventCollector/test_data/create_comment_result.json
  Packs/CybelAngel/Integrations/CybelAngelEventCollector/test_data/get_comments_res.json
  Packs/CybelAngel/Integrations/CybelAngelEventCollector/test_data/mirror-report.json
  Packs/CybelAngel/Integrations/CybelAngelEventCollector/test_data/report_list.json
  Packs/CybelAngel/ReleaseNotes/1_0_3.md
  Packs/CybelAngel/TestPlaybooks/CybelAngel_Test_Playbook.yml
  Packs/CybelAngel/pack_metadata.json
  Tests/conf.json
Labels: docs-approved, sync-gsm

#38690 Download eml
  Packs/CheckPointHEC/.pack-ignore
  Packs/CheckPointHEC/Integrations/CheckPointHEC/CheckPointHEC.py
  Packs/CheckPointHEC/Integrations/CheckPointHEC/CheckPointHEC.yml
  Packs/CheckPointHEC/Integrations/CheckPointHEC/CheckPointHEC_test.py
  Packs/CheckPointHEC/Integrations/CheckPointHEC/README.md
  Packs/CheckPointHEC/ReleaseNotes/1_1_7.md
  Packs/CheckPointHEC/Scripts/RunCPPhishingCampaign/RunCPPhishingCampaign.yml
  Packs/CheckPointHEC/Scripts/SendCPAction/SendCPAction.yml
  Packs/CheckPointHEC/Scripts/ShowCPEmailInfo/ShowCPEmailInfo.yml
  Packs/CheckPointHEC/Scripts/ShowCPScanInfo/ShowCPScanInfo.yml
  Packs/CheckPointHEC/pack_metadata.json
Labels: Contribution, docs-approved, Partner, pending-demo, post-demo, Contribution Form Filled, pending-contributor, Partner Support Level, External PR, Partner-Approved

#38936 Exchange user forwarding + guest user invite fix
  Packs/CortexResponseAndRemediation/Playbooks/playbook-Exchange_User_Mailbox_Forwarding.yml
  Packs/CortexResponseAndRemediation/Playbooks/playbook-Successful_guest_user_invitation.yml
  Packs/CortexResponseAndRemediation/Playbooks/silent-playbook-Exchange_User_Mailbox_Forwarding_Test.yml
  Packs/CortexResponseAndRemediation/Playbooks/silent-playbook-Successful_guest_user_invitation_Test.yml
  Packs/CortexResponseAndRemediation/ReleaseNotes/1_1_21.md
  Packs/CortexResponseAndRemediation/pack_metadata.json
Labels: docs-approved

#38836 Whois - Lower request attempts number when is_time_sensitive() is True
  Packs/Whois/Integrations/Whois/Whois.py
  Packs/Whois/ReleaseNotes/1_5_25.md
  Packs/Whois/pack_metadata.json
Labels: docs-approved

#38899 bug fix xsup 47542
  Packs/PrismaCloudCompute/Integrations/PaloAltoNetworks_PrismaCloudCompute/PaloAltoNetworks_PrismaCloudCompute.py
  Packs/PrismaCloudCompute/Integrations/PaloAltoNetworks_PrismaCloudCompute/PaloAltoNetworks_PrismaCloudCompute.yml
  Packs/PrismaCloudCompute/Integrations/PaloAltoNetworks_PrismaCloudCompute/PaloAltoNetworks_PrismaCloudCompute_test.py
  Packs/PrismaCloudCompute/ReleaseNotes/1_7_12.md
  Packs/PrismaCloudCompute/pack_metadata.json
Labels: docs-approved

#38937 [CRTX-155709] Change canvas tab in threat intel layouts to hidden
  Packs/ThreatIntelReports/Layouts/layoutscontainer-ThreatIntelReport-CampaignReport.json
  Packs/ThreatIntelReports/Layouts/layoutscontainer-ThreatIntelReport-ExecutiveBriefReport.json
  Packs/ThreatIntelReports/Layouts/layoutscontainer-ThreatIntelReport-MalwareReport.json
  Packs/ThreatIntelReports/Layouts/layoutscontainer-ThreatIntelReport-ThreatActorReport.json
  Packs/ThreatIntelReports/Layouts/layoutscontainer-ThreatIntelReport-VulnerabilityReport.json
  Packs/ThreatIntelReports/ReleaseNotes/1_0_22.md
  Packs/ThreatIntelReports/pack_metadata.json
Labels: docs-approved

#38919 Fix duplicate alerts issue
  Packs/PrismaCloud/Integrations/PrismaCloudV2/PrismaCloudV2.py
  Packs/PrismaCloud/Integrations/PrismaCloudV2/PrismaCloudV2.yml
  Packs/PrismaCloud/Integrations/PrismaCloudV2/PrismaCloudV2_test.py
  Packs/PrismaCloud/Integrations/PrismaCloudV2/test_data/input_data.py
  Packs/PrismaCloud/ReleaseNotes/4_4_1.md
  Packs/PrismaCloud/pack_metadata.json
Labels: docs-approved

#38898 Fix the Microsoft Graph Security documentation
  Packs/MicrosoftGraphSecurity/Integrations/MicrosoftGraphSecurity/MicrosoftGraphSecurity.yml
  Packs/MicrosoftGraphSecurity/Integrations/MicrosoftGraphSecurity/MicrosoftGraphSecurity_description.md
  Packs/MicrosoftGraphSecurity/Integrations/MicrosoftGraphSecurity/README.md
  Packs/MicrosoftGraphSecurity/ReleaseNotes/2_2_23.md
  Packs/MicrosoftGraphSecurity/TestPlaybooks/Microsoft_Graph_security_test_ediscovery.yml
  Packs/MicrosoftGraphSecurity/pack_metadata.json
Labels: docs-approved, sync-gsm

#38908 Proofpoint heartbeat updates
  Packs/ProofpointEmailSecurity/Integrations/ProofpointEmailSecurityEventCollector/ProofpointEmailSecurityEventCollector.py
  Packs/ProofpointEmailSecurity/Integrations/ProofpointEmailSecurityEventCollector/ProofpointEmailSecurityEventCollector_test.py
  Packs/ProofpointEmailSecurity/ReleaseNotes/1_0_10.md
  Packs/ProofpointEmailSecurity/pack_metadata.json
Labels: docs-approved

#38950 [MalwareBazaar Feed] Add 503 Error To Retry Logic
  Packs/FeedMalwareBazaar/Integrations/MalwareBazaarFeed/MalwareBazaarFeed.py
  Packs/FeedMalwareBazaar/Integrations/MalwareBazaarFeed/MalwareBazaarFeed.yml
  Packs/FeedMalwareBazaar/Integrations/MalwareBazaarFeed/MalwareBazaarFeed_test.py
  Packs/FeedMalwareBazaar/ReleaseNotes/1_0_43.md
  Packs/FeedMalwareBazaar/pack_metadata.json
Labels: docs-approved

#38923 Update URL indicatro regex and foramtter to handle numerical IPs in URLs
  Packs/ApiModules/Scripts/FormatURLApiModule/FormatURLApiModule.py
  Packs/ApiModules/Scripts/FormatURLApiModule/FormatURLApiModule_test.py
  Packs/CommonScripts/ReleaseNotes/1_19_31.md
  Packs/CommonScripts/pack_metadata.json
  Packs/CommonTypes/IndicatorTypes/reputation-url.json
  Packs/CommonTypes/ReleaseNotes/3_8_5.md
  Packs/CommonTypes/pack_metadata.json
  Packs/Phishing/ReleaseNotes/3_6_37.md
  Packs/Phishing/Scripts/FindDuplicateEmailIncidents/FindDuplicateEmailIncidents.py
  Packs/Phishing/Scripts/FindDuplicateEmailIncidents/FindDuplicateEmailIncidents_test.py
  Packs/Phishing/pack_metadata.json
Labels: docs-approved

#38534 CIAC-12763: Add a timeout header and debug logs
  Packs/DemistoRESTAPI/Integrations/CoreRESTAPI/CoreRESTAPI.js
  Packs/DemistoRESTAPI/Integrations/CoreRESTAPI/CoreRESTAPI.yml
  Packs/DemistoRESTAPI/ReleaseNotes/1_3_67.md
  Packs/DemistoRESTAPI/pack_metadata.json
  Tests/conf.json
Labels: docs-approved, ForceMerge

#38845 QRadar Playbook - Get Offense Logs
  Packs/QRadar/Playbooks/playbook-QRadar_-_Get_Offense_Logs.yml
  Packs/QRadar/ReleaseNotes/2_5_12.md
  Packs/QRadar/pack_metadata.json
Labels: docs-approved

#38961 Fix XDR TPB
  Packs/CortexXDR/.secrets-ignore
  Packs/CortexXDR/TestPlaybooks/Test_XDR_Playbook_general_commands.yml
Labels: docs-approved

#38958 Improve symantec ses collector
  Packs/SymantecEndpointSecurity/Integrations/SymantecEndpointSecurity/README.md
  Packs/SymantecEndpointSecurity/Integrations/SymantecEndpointSecurity/SymantecEndpointSecurity.py
  Packs/SymantecEndpointSecurity/Integrations/SymantecEndpointSecurity/SymantecEndpointSecurity.yml
  Packs/SymantecEndpointSecurity/Integrations/SymantecEndpointSecurity/SymantecEndpointSecurity_test.py
  Packs/SymantecEndpointSecurity/ReleaseNotes/1_0_4.md
  Packs/SymantecEndpointSecurity/pack_metadata.json
Labels: docs-approved

#38975 Jamf - Fixed audit duplicate entries
  Packs/JamfProtect/Integrations/JamfProtectEventCollector/JamfProtectEventCollector.py
  Packs/JamfProtect/Integrations/JamfProtectEventCollector/JamfProtectEventCollector.yml
  Packs/JamfProtect/ReleaseNotes/1_2_1.md
  Packs/JamfProtect/pack_metadata.json
Labels: docs-approved

#38765 Partner FeedOpenCTI adoption
  Packs/FeedOpenCTI/README.md
  Packs/FeedOpenCTI/ReleaseNotes/2_1_5.md
  Packs/FeedOpenCTI/pack_metadata.json
Labels: Contribution, docs-approved, Contribution Form Filled, Community, Xsoar Support Level, External PR

#38941 Fix for internal mapping of Env ID CSX Sandbox
  Packs/CrowdStrikeFalconX/Integrations/CrowdStrikeFalconX/CrowdStrikeFalconX.py
  Packs/CrowdStrikeFalconX/ReleaseNotes/1_2_41.md
  Packs/CrowdStrikeFalconX/pack_metadata.json
Labels: docs-approved

#38938 created xif,schema.json ,yml and updated pack_metadata and readme files
  Packs/IBMMaaS360Security/ModelingRules/IBMMaaS360Security/IBMMaaS360Security.xif
  Packs/IBMMaaS360Security/ModelingRules/IBMMaaS360Security/IBMMaaS360Security.yml
  Packs/IBMMaaS360Security/ModelingRules/IBMMaaS360Security/IBMMaaS360Security_schema.json
  Packs/IBMMaaS360Security/README.md
  Packs/IBMMaaS360Security/ReleaseNotes/1_0_2.md
  Packs/IBMMaaS360Security/pack_metadata.json
Labels: docs-approved, bypass.url

#38977 improve error for create-issue command
  Packs/Jira/Integrations/JiraV3/JiraV3.py
  Packs/Jira/Integrations/JiraV3/JiraV3_test.py
  Packs/Jira/ReleaseNotes/3_2_16.md
  Packs/Jira/pack_metadata.json
Labels: docs-approved

#38993 XSUP-47874-Microsoft-NPS
  Packs/MicrosoftNPS/ModelingRules/MicrosoftNPS_1_3/MicrosoftNPS_1_3.xif
  Packs/MicrosoftNPS/ModelingRules/MicrosoftNPS_1_3/MicrosoftNPS_1_3_schema.json
  Packs/MicrosoftNPS/ParsingRules/MicrosoftNPSParsingRules/MicrosoftNPSParsingRules.xif
  Packs/MicrosoftNPS/ReleaseNotes/1_0_7.json
  Packs/MicrosoftNPS/ReleaseNotes/1_0_7.md
  Packs/MicrosoftNPS/pack_metadata.json
Labels: docs-approved

#38344 Update `url_phishing` Model
  Packs/CommonScripts/ReleaseNotes/1_19_32.json
  Packs/CommonScripts/ReleaseNotes/1_19_32.md
  Packs/CommonScripts/Scripts/DBotUpdateLogoURLPhishing/DBotUpdateLogoURLPhishing.py
  Packs/CommonScripts/Scripts/DBotUpdateLogoURLPhishing/DBotUpdateLogoURLPhishing_test.py
  Packs/CommonScripts/pack_metadata.json
  Packs/PhishingURL/.secrets-ignore
  Packs/PhishingURL/ReleaseNotes/1_1_24.md
  Packs/PhishingURL/Scripts/DBotPredictURLPhishing/DBotPredictURLPhishing.py
  Packs/PhishingURL/Scripts/DBotPredictURLPhishing/DBotPredictURLPhishing.yml
  Packs/PhishingURL/Scripts/DBotPredictURLPhishing/DBotPredictURLPhishing_test.py
  Packs/PhishingURL/Scripts/DBotPredictURLPhishing/test_data/model_predictions.py
  Packs/PhishingURL/Scripts/DBotUpdateLogoURLPhishing/DBotUpdateLogoURLPhishing.py
  Packs/PhishingURL/Scripts/DBotUpdateLogoURLPhishing/DBotUpdateLogoURLPhishing.yml
  Packs/PhishingURL/Scripts/DBotUpdateLogoURLPhishing/DBotUpdateLogoURLPhishing_test.py
  Packs/PhishingURL/Scripts/DBotUpdateLogoURLPhishing/README.md
  Packs/PhishingURL/Scripts/DBotUpdateLogoURLPhishing/test_data/image.png
  Packs/PhishingURL/Scripts/DBotUpdateLogoURLPhishing/test_data/logo.png
  Packs/PhishingURL/TestPlaybooks/DBotUpdateLogoURLPhishing_test.yml
  Packs/PhishingURL/pack_metadata.json
Labels: ForceMerge

#38760 CTM360-CBS bug fix expecting `list` but getting `dict`
  Packs/CTM360-CyberBlindspot/Integrations/CyberBlindspot/CyberBlindspot.py
  Packs/CTM360-CyberBlindspot/Integrations/CyberBlindspot/CyberBlindspot.yml
  Packs/CTM360-CyberBlindspot/Integrations/CyberBlindspot/CyberBlindspot_test.py
  Packs/CTM360-CyberBlindspot/ReleaseNotes/2_1_1.md
  Packs/CTM360-CyberBlindspot/pack_metadata.json
Labels: Contribution, Partner, pending-demo, post-demo, Contribution Form Filled, pending-contributor, Partner Support Level, External PR, Partner-Approved

#38724 FeedDomainTools Release v1.0.0
  Packs/FeedDomainTools/.pack-ignore
  Packs/FeedDomainTools/.secrets-ignore
  Packs/FeedDomainTools/Author_image.png
  Packs/FeedDomainTools/Integrations/FeedDomainTools/FeedDomainTools.py
  Packs/FeedDomainTools/Integrations/FeedDomainTools/FeedDomainTools.yml
  Packs/FeedDomainTools/Integrations/FeedDomainTools/FeedDomainTools_description.md
  Packs/FeedDomainTools/Integrations/FeedDomainTools/FeedDomainTools_image.png
  Packs/FeedDomainTools/Integrations/FeedDomainTools/FeedDomainTools_test.py
  Packs/FeedDomainTools/Integrations/FeedDomainTools/README.md
  Packs/FeedDomainTools/Integrations/FeedDomainTools/command_examples.txt
  Packs/FeedDomainTools/Integrations/FeedDomainTools/test_data/feed_mock_response.py
  Packs/FeedDomainTools/README.md
  Packs/FeedDomainTools/pack_metadata.json
Labels: Contribution, docs-approved, Partner, Contribution Form Filled, Partner Support Level, External PR, Partner-Approved, TIM Review

#38717 Remove gr103 ignore
  Packs/Core/.pack-ignore
  Packs/CortexResponseAndRemediation/.pack-ignore
Labels: docs-approved

#39006 Update Invetigation URL
  .github/github_workflow_scripts/run_secrets_detection_get_playbook_status.py
Labels: docs-approved

#38924 Elasticsearch V8 transport bug fix
  Packs/Elasticsearch/Integrations/Elasticsearch_v2/Elasticsearch_v2.py
  Packs/Elasticsearch/Integrations/Elasticsearch_v2/Elasticsearch_v2.yml
  Packs/Elasticsearch/ReleaseNotes/1_3_29.md
  Packs/Elasticsearch/pack_metadata.json
Labels: docs-approved

#38839 Google Apigee Event Collector
  Packs/GoogleApigee/.pack-ignore
  Packs/GoogleApigee/.secrets-ignore
  Packs/GoogleApigee/Integrations/GoogleApigeeEventCollector/GoogleApigeeEventCollector.py
  Packs/GoogleApigee/Integrations/GoogleApigeeEventCollector/GoogleApigeeEventCollector.yml
  Packs/GoogleApigee/Integrations/GoogleApigeeEventCollector/GoogleApigeeEventCollector_description.md
  Packs/GoogleApigee/Integrations/GoogleApigeeEventCollector/GoogleApigeeEventCollector_image.png
  Packs/GoogleApigee/Integrations/GoogleApigeeEventCollector/GoogleApigeeEventCollector_test.py
  Packs/GoogleApigee/Integrations/GoogleApigeeEventCollector/README.md
  Packs/GoogleApigee/Integrations/GoogleApigeeEventCollector/command_examples.txt
  Packs/GoogleApigee/README.md
  Packs/GoogleApigee/pack_metadata.json
Labels: docs-approved

#38989 Partner OpenCTI adoption
  Packs/OpenCTI/README.md
  Packs/OpenCTI/ReleaseNotes/2_0_2.md
  Packs/OpenCTI/pack_metadata.json
Labels: Contribution, docs-approved, Contribution Form Filled, Community, Xsoar Support Level, External PR

#38838 Add reviewer for AUD PRs
  .github/content_roles.json
Labels: docs-approved

#39022 Fix importance arg description
  Packs/MicrosoftGraphMail/Integrations/MicrosoftGraphMail/MicrosoftGraphMail.yml
  Packs/MicrosoftGraphMail/ReleaseNotes/1_6_24.md
  Packs/MicrosoftGraphMail/pack_metadata.json
Labels: docs-approved

#39019 docker hub username/password fix
  .github/workflows/pre-commit.yml
Labels: docs-approved

#38769 Refactor/date limit soc feedback command
  Packs/Hoxhunt/Integrations/HoxhuntV2/HoxhuntV2.py
  Packs/Hoxhunt/Integrations/HoxhuntV2/HoxhuntV2.yml
  Packs/Hoxhunt/Integrations/HoxhuntV2/HoxhuntV2_test.py
  Packs/Hoxhunt/Integrations/HoxhuntV2/README.md
  Packs/Hoxhunt/ReleaseNotes/2_0_2.md
  Packs/Hoxhunt/pack_metadata.json
Labels: Contribution, docs-approved, Partner, pending-demo, Contribution Form Filled, pending-contributor, Partner Support Level, External PR, Partner-Approved

#38289 Update for Pack: Gatewatcher AionIQ
  Packs/Gatewatcher-AionIQ/CONTRIBUTORS.json
  Packs/Gatewatcher-AionIQ/Classifiers/classifier-Gatewatcher_Incidents_Classifier.json
  Packs/Gatewatcher-AionIQ/Classifiers/classifier-Gatewatcher_Mapper_Incoming.json
  Packs/Gatewatcher-AionIQ/Integrations/GCenter103/GCenter103.py
  Packs/Gatewatcher-AionIQ/Integrations/GCenter103/GCenter103.yml
  Packs/Gatewatcher-AionIQ/Integrations/GCenter103/GCenter103_test.py
  Packs/Gatewatcher-AionIQ/Integrations/GCenter103/README.md
  Packs/Gatewatcher-AionIQ/Integrations/GCenter103/command_examples.txt
  Packs/Gatewatcher-AionIQ/Integrations/GCenter103/test/test.txt
  Packs/Gatewatcher-AionIQ/Integrations/GCenter103/test_data/test_commands_data.dat
  Packs/Gatewatcher-AionIQ/Layouts/layoutscontainer-Gatewatcher_Alert_Incident_Layout.json
  Packs/Gatewatcher-AionIQ/Layouts/layoutscontainer-Gatewatcher_Incident_Layout.json
  Packs/Gatewatcher-AionIQ/Playbooks/playbook-Malcore_alert_related_file.yml
  Packs/Gatewatcher-AionIQ/Playbooks/playbook-Malcore_alert_related_file_README.md
  Packs/Gatewatcher-AionIQ/ReleaseNotes/1_3_0.md
  Packs/Gatewatcher-AionIQ/Scripts/GatewatcherAlertEngine/GatewatcherAlertEngine.py
  Packs/Gatewatcher-AionIQ/Scripts/GatewatcherAlertEngine/GatewatcherAlertEngine_test.py
  Packs/Gatewatcher-AionIQ/Scripts/GatewatcherAlertEngine/README.md
  Packs/Gatewatcher-AionIQ/doc_files/Malcore_alert_related_file.png
  Packs/Gatewatcher-AionIQ/pack_metadata.json
Labels: Contribution, docs-approved, Partner, Contribution Form Filled, pending-contributor, Partner Support Level, External PR, Security Review, Partner-Approved, Security Approved

#39046 tj-actions/changed-files@v46.0.1
  .github/workflows/protect-files.yml
  .github/workflows/protect-infra-directories-contributions.yml
  .github/workflows/review-release-notes.yml
Labels: docs-approved

#39014 Feature Introducing three new commands
  Packs/CovalenceManagedSecurity/Integrations/CovalenceManagedSecurity/CovalenceManagedSecurity.py
  Packs/CovalenceManagedSecurity/Integrations/CovalenceManagedSecurity/CovalenceManagedSecurity.yml
  Packs/CovalenceManagedSecurity/Integrations/CovalenceManagedSecurity/CovalenceManagedSecurity_test.py
  Packs/CovalenceManagedSecurity/Integrations/CovalenceManagedSecurity/README.md
  Packs/CovalenceManagedSecurity/Integrations/CovalenceManagedSecurity/command_examples.txt
  Packs/CovalenceManagedSecurity/Integrations/CovalenceManagedSecurity/test_data/list_escalation_contacts.json
  Packs/CovalenceManagedSecurity/Integrations/CovalenceManagedSecurity/test_data/list_organization.json
  Packs/CovalenceManagedSecurity/ReleaseNotes/1_4_0.md
  Packs/CovalenceManagedSecurity/pack_metadata.json
Labels: Contribution, docs-approved, Partner, Contribution Form Filled, Partner Support Level, External PR, Partner-Approved

#39049 Update contrib team
  .github/content_roles.json
Labels: docs-approved

#39020 [ASM] - expandr 12794
  Packs/CortexVulnerabilityManagement/README.md
  Packs/CortexVulnerabilityManagement/ReleaseNotes/1_0_3.md
  Packs/CortexVulnerabilityManagement/Triggers/Trigger_-_Cortex_VM_-_Vulnerability_Issue.json
  Packs/CortexVulnerabilityManagement/pack_metadata.json
Labels: Contribution, docs-approved, Contribution Form Filled, Community, Xsoar Support Level, External PR, Security Review, Security Approved

#39032 Bugfix/Prisma-Deployment-Wizard-requires-deprecated-JiraV2
  Packs/PrismaCloudCompute/ReleaseNotes/1_7_13.md
  Packs/PrismaCloudCompute/Wizards/wizard-Prisma_Cloud_Compute_Compliance.json
  Packs/PrismaCloudCompute/pack_metadata.json
Labels: docker, bypass.url

#39031 fix parse date symantec ses
  Packs/SymantecEndpointSecurity/Integrations/SymantecEndpointSecurity/SymantecEndpointSecurity.py
  Packs/SymantecEndpointSecurity/Integrations/SymantecEndpointSecurity/SymantecEndpointSecurity_test.py
  Packs/SymantecEndpointSecurity/ReleaseNotes/1_0_5.md
  Packs/SymantecEndpointSecurity/pack_metadata.json
Labels: docs-approved

#39071 Crtx 146125 BloodHound Enterprise Mapping
  Packs/BloodHoundEnterprise/ModelingRules/BloodHoundEnterprise/BloodHoundEnterprise.xif
  Packs/BloodHoundEnterprise/ModelingRules/BloodHoundEnterprise/BloodHoundEnterprise.yml
  Packs/BloodHoundEnterprise/ModelingRules/BloodHoundEnterprise/BloodHoundEnterprise_schema.json
  Packs/BloodHoundEnterprise/README.md
  Packs/BloodHoundEnterprise/ReleaseNotes/1_0_1.md
  Packs/BloodHoundEnterprise/pack_metadata.json
Labels: docs-approved, bypass.url

#39084 Error handling wmi playbooks
  Packs/CortexResponseAndRemediation/Playbooks/playbook-Remote_WMI_Process_Execution.yml
  Packs/CortexResponseAndRemediation/Playbooks/silent-playbook-WmiPrvSe.exe_Rare_Child_Command_Line.yml
  Packs/CortexResponseAndRemediation/ReleaseNotes/1_1_23.md
  Packs/CortexResponseAndRemediation/pack_metadata.json
Labels: docs-approved

#38912 Azure AKS Mapping
  Packs/AzureKubernetesServices/ModelingRules/AzureKubernetesServices/AzureKubernetesServices.xif
  Packs/AzureKubernetesServices/ModelingRules/AzureKubernetesServices/AzureKubernetesServices.yml
  Packs/AzureKubernetesServices/ModelingRules/AzureKubernetesServices/AzureKubernetesServices_schema.json
  Packs/AzureKubernetesServices/ParsingRules/AzureKubernetesServices/AzureKubernetesServices.xif
  Packs/AzureKubernetesServices/ParsingRules/AzureKubernetesServices/AzureKubernetesServices.yml
  Packs/AzureKubernetesServices/README.md
  Packs/AzureKubernetesServices/ReleaseNotes/1_2_5.md
  Packs/AzureKubernetesServices/pack_metadata.json
  Packs/MicrosoftEntraID/ParsingRules/MicrosoftEntraID/MicrosoftEntraID.xif
  Packs/MicrosoftEntraID/README.md
  Packs/MicrosoftEntraID/ReleaseNotes/1_0_10.md
  Packs/MicrosoftEntraID/pack_metadata.json
Labels: docs-approved, bypass.url

#39052 IsPDFFileEncrypted improve error
  Packs/CommonScripts/ReleaseNotes/1_19_33.md
  Packs/CommonScripts/Scripts/IsPDFFileEncrypted/IsPDFFileEncrypted.py
  Packs/CommonScripts/pack_metadata.json
Labels: docs-approved

#38996 fix akamai docker outputs collision
  Packs/Akamai_SIEM/Integrations/Akamai_SIEM/Akamai_SIEM.py
  Packs/Akamai_SIEM/ReleaseNotes/1_2_4.md
  Packs/Akamai_SIEM/pack_metadata.json
Labels: docs-approved

#38995 FEEDMISPFEED parse host bug
  Packs/FeedMISP/Integrations/FeedMISP/FeedMISP.py
  Packs/FeedMISP/Integrations/FeedMISP/FeedMISP_test.py
  Packs/FeedMISP/ReleaseNotes/1_0_41.json
  Packs/FeedMISP/ReleaseNotes/1_0_41.md
  Packs/FeedMISP/pack_metadata.json
Labels: docs-approved

#38867 updated last run to latest incident time and allowed more than 1 day…
  Packs/Netskope/Integrations/NetskopeAPIv2/NetskopeAPIv2.py
  Packs/Netskope/Integrations/NetskopeAPIv2/NetskopeAPIv2.yml
  Packs/Netskope/ReleaseNotes/4_0_8.md
  Packs/Netskope/pack_metadata.json
Labels: Contribution, docs-approved, Contribution Form Filled, Community, Xsoar Support Level, External PR

#38931 Handling error of xdr-list-risky-users and xdr-list-risky-hosts
  Packs/ApiModules/ReleaseNotes/2_2_42.md
  Packs/ApiModules/Scripts/CoreIRApiModule/CoreIRApiModule.py
  Packs/ApiModules/Scripts/CoreIRApiModule/CoreIRApiModule_test.py
  Packs/ApiModules/pack_metadata.json
  Packs/Core/ReleaseNotes/3_2_27.md
  Packs/Core/pack_metadata.json
  Packs/CortexXDR/ReleaseNotes/6_2_15.md
  Packs/CortexXDR/pack_metadata.json
  Packs/ctf01/ReleaseNotes/1_0_39.md
  Packs/ctf01/pack_metadata.json
Labels: docs-approved

#39037 ANY.RUN adoption start
  Packs/ANYRUN/README.md
  Packs/ANYRUN/ReleaseNotes/1_0_23.md
  Packs/ANYRUN/pack_metadata.json
Labels: Contribution, docs-approved, Partner, Contribution Form Filled, pending-contributor, Partner Support Level, External PR, Partner-Approved

#39124 Ignore AIOps TPB
  Tests/conf.json
Labels: docs-approved

#39087 Added logs and timeout to Proofpoint Isolation
  Packs/ProofpointIsolation/Integrations/ProofpointIsolationEventCollector/ProofpointIsolationEventCollector.py
  Packs/ProofpointIsolation/Integrations/ProofpointIsolationEventCollector/ProofpointIsolationEventCollector.yml
  Packs/ProofpointIsolation/ReleaseNotes/1_0_2.md
  Packs/ProofpointIsolation/pack_metadata.json
Labels: docs-approved

#39091 [ASM] Update CVM Pack to Make it usable by EV3 issues - Part 2
  Packs/CortexVulnerabilityManagement/Playbooks/Cortex_VM_-_Vulnerability_Issue.yml
  Packs/CortexVulnerabilityManagement/Playbooks/Cortex_VM_-_Vulnerability_Issue_README.md
  Packs/CortexVulnerabilityManagement/ReleaseNotes/1_0_4.md
  Packs/CortexVulnerabilityManagement/doc_files/Cortex_VM_-_Vulnerability_Issue.png
  Packs/CortexVulnerabilityManagement/pack_metadata.json
Labels: Contribution, docs-approved, Contribution Form Filled, Community, Xsoar Support Level, External PR, Security Review, Security Approved

#39128 Modified readme of CiscoSMA
  Packs/CiscoSMA/README.md
Labels: docs-approved

#38959 Add api_version param to support multiple tenant versions in Workday Signon Event Collector
  Packs/Workday/Integrations/WorkdaySignOnEventCollector/README.md
  Packs/Workday/Integrations/WorkdaySignOnEventCollector/WorkdaySignOnEventCollector.py
  Packs/Workday/Integrations/WorkdaySignOnEventCollector/WorkdaySignOnEventCollector.yml
  Packs/Workday/Integrations/WorkdaySignOnEventCollector/WorkdaySignOnEventCollector_test.py
  Packs/Workday/ReleaseNotes/1_5_0.md
  Packs/Workday/pack_metadata.json
Labels: docs-approved

#38945 encoded the session_id in aruba
  Packs/HPEArubaClearPass/Integrations/HPEArubaClearPass/HPEArubaClearPass.py
  Packs/HPEArubaClearPass/Integrations/HPEArubaClearPass/HPEArubaClearPass.yml
  Packs/HPEArubaClearPass/Integrations/HPEArubaClearPass/HPEArubaClearPass_test.py
  Packs/HPEArubaClearPass/ReleaseNotes/1_0_29.md
  Packs/HPEArubaClearPass/pack_metadata.json
  Tests/conf.json
Labels: docs-approved

#39121 add use legacy API parameter to XSIAM
  Packs/CrowdStrikeFalcon/Integrations/CrowdStrikeFalcon/CrowdStrikeFalcon.yml
  Packs/CrowdStrikeFalcon/ReleaseNotes/2_1_16.md
  Packs/CrowdStrikeFalcon/pack_metadata.json
Labels: ForceMerge

#39148 Citrix ADC Update
  Packs/CitrixADC/ModelingRules/CitrixADC_1_3/CitrixADC_1_3.xif
  Packs/CitrixADC/ReleaseNotes/1_0_5.md
  Packs/CitrixADC/pack_metadata.json
Labels: docs-approved

#39231 Fix Typo HelloWorld integration
  Packs/HelloWorld/Integrations/HelloWorld/HelloWorld.py
  Packs/HelloWorld/Integrations/HelloWorld/HelloWorld.yml
  Packs/HelloWorld/Integrations/HelloWorldEventCollector/HelloWorldEventCollector.yml
  Packs/HelloWorld/ReleaseNotes/3_0_17.md
  Packs/HelloWorld/pack_metadata.json
Labels: docs-approved

#39129 Execution of an uncommon process at an early startup stage
  Packs/CommonPlaybooks/Playbooks/playbook-Containment_Plan_-_Quarantine_File.yml
  Packs/CommonPlaybooks/Playbooks/playbook-Containment_Plan_-_Quarantine_File_README.md
  Packs/CommonPlaybooks/ReleaseNotes/2_6_54.md
  Packs/CommonPlaybooks/doc_files/Containment_Plan_-_Quarantine_File.png
  Packs/CommonPlaybooks/pack_metadata.json
  Packs/CortexResponseAndRemediation/Playbooks/playbook-Execution_of_an_uncommon_process_at_an_early_startup_stage_README.md
  Packs/CortexResponseAndRemediation/Playbooks/silent-playbook-Execution_of_an_uncommon_process_at_an_early_startup_stage.yml
  Packs/CortexResponseAndRemediation/ReleaseNotes/1_1_24.md
  Packs/CortexResponseAndRemediation/Triggers/silent-Trigger_-_Execution_of_an_uncommon_process_at_an_early_startup_stage.json
  Packs/CortexResponseAndRemediation/doc_files/Execution_of_an_uncommon_process_at_an_early_startup_stage.png
  Packs/CortexResponseAndRemediation/pack_metadata.json
Labels: docs-approved

#39233 XSUP-48471/OktaASA - fix bug label description
  Packs/OktaASA/Integrations/OktaASA/OktaASA.yml
  Packs/OktaASA/ReleaseNotes/1_0_1.md
  Packs/OktaASA/pack_metadata.json
Labels: docs-approved

#39054 [XSUP-48037] PAN-OS fetch-incidents documentation improvements
  Packs/PAN-OS/.secrets-ignore
  Packs/PAN-OS/Integrations/Panorama/Panorama.py
  Packs/PAN-OS/Integrations/Panorama/Panorama.yml
  Packs/PAN-OS/Integrations/Panorama/Panorama_description.md
  Packs/PAN-OS/Integrations/Panorama/README.md
  Packs/PAN-OS/ReleaseNotes/2_3_7.md
  Packs/PAN-OS/pack_metadata.json
Labels: docs-approved, ForceMerge

#39155 Ip-fix_symantec_ses_missing_schema
  Packs/SymantecEndpointSecurity/Integrations/SymantecEndpointSecurity/SymantecEndpointSecurity.py
  Packs/SymantecEndpointSecurity/Integrations/SymantecEndpointSecurity/SymantecEndpointSecurity_test.py
  Packs/SymantecEndpointSecurity/ReleaseNotes/1_0_6.md
  Packs/SymantecEndpointSecurity/pack_metadata.json
Labels: docs-approved

#38852 Ms teams minimize permissions
  Packs/MicrosoftTeams/Integrations/MicrosoftTeams/MicrosoftTeams.py
  Packs/MicrosoftTeams/Integrations/MicrosoftTeams/MicrosoftTeams_test.py
  Packs/MicrosoftTeams/Integrations/MicrosoftTeams/README.md
  Packs/MicrosoftTeams/ReleaseNotes/1_5_17.md
  Packs/MicrosoftTeams/pack_metadata.json
Labels: docs-approved

#39108 update the Platform core packs list
  Config/core_packs_platform_list.json
Labels: docs-approved

#39160 Cortex XSIAM - Data Ingestion Issue Via Webhook
  Packs/GenericWebhook/.secrets-ignore
  Packs/GenericWebhook/Integrations/GenericWebhook/GenericWebhook.yml
  Packs/GenericWebhook/Integrations/GenericWebhook/GenericWebhook_description.md
  Packs/GenericWebhook/Integrations/GenericWebhook/README.md
  Packs/GenericWebhook/ReleaseNotes/1_1_7.md
  Packs/GenericWebhook/doc_files/mapping.png
  Packs/GenericWebhook/pack_metadata.json
Labels: docs-approved

#39243 MicrosoftTeamsAsk script - Improved docs
  Packs/MicrosoftTeams/Scripts/MicrosoftTeamsAsk/README.md
Labels: docs-approved

#38786 fix: get mapping fields function does not except any arguments
  Packs/SentinelOne/CONTRIBUTORS.json
  Packs/SentinelOne/Integrations/SentinelOne-V2/SentinelOne-V2.py
  Packs/SentinelOne/ReleaseNotes/3_2_40.md
  Packs/SentinelOne/pack_metadata.json
Labels: Contribution, docs-approved, Contribution Form Filled, Community, Partner Support Level, External PR, Partner-Approved

#39248 CRTX-133204-Trellix_ePO-fix
  Packs/Trellix_ePO/ReleaseNotes/1_0_1.md
  Packs/Trellix_ePO/pack_metadata.json
Labels: docs-approved, ForceMerge, bypass.url

#39103 Modeling rules modification - CRTX-151278
  Packs/qualys/ModelingRules/QualysModelingRules/QualysModelingRules.xif
  Packs/qualys/ModelingRules/QualysModelingRules/QualysModelingRules_schema.json
  Packs/qualys/ReleaseNotes/3_2_5.md
  Packs/qualys/pack_metadata.json
Labels: docs-approved

#39249 Update Pan-OS playbook for supporting version 11
  Packs/PAN-OS/Integrations/Panorama/README.md
  Packs/PAN-OS/TestPlaybooks/playbook-palo_alto_panorama_test_pb.yml
  Tests/conf.json
Labels: docs-approved, sync-gsm

#39159 new playbook - First Azure AD PowerShell operation for a user
  Packs/CortexResponseAndRemediation/.pack-ignore
  Packs/CortexResponseAndRemediation/Playbooks/silent-playbook-First_Azure_AD_PowerShell_operation_for_a_user.yml
  Packs/CortexResponseAndRemediation/ReleaseNotes/1_1_25.md
  Packs/CortexResponseAndRemediation/Triggers/silent-Trigger_-_First_Azure_AD_PowerShell_operation_for_a_user.json
  Packs/CortexResponseAndRemediation/pack_metadata.json
Labels: docs-approved

#39265 added itamar
  .github/content_roles.json
Labels: docs-approved

#39260 Added the validate-validation-config-file hook to content
  .pre-commit-config_template.yaml
  validation_config.toml
Labels: docs-approved

#39270 Automation research releases
  Packs/CortexResponseAndRemediation/.pack-ignore
  Packs/CortexResponseAndRemediation/Playbooks/silent-playbook-First_Azure_AD_PowerShell_operation_for_a_user.yml
  Packs/CortexResponseAndRemediation/ReleaseNotes/1_1_25.md
  Packs/CortexResponseAndRemediation/Triggers/silent-Trigger_-_First_Azure_AD_PowerShell_operation_for_a_user.json
  Packs/CortexResponseAndRemediation/pack_metadata.json
Labels: docs-approved

#39272 add codeowner
  .github/CODEOWNERS
Labels: docs-approved

#38982 Add ICDM Integration
  Packs/SymantecICDM/.pack-ignore
  Packs/SymantecICDM/.secrets-ignore
  Packs/SymantecICDM/Integrations/SymantecICDM/README.md
  Packs/SymantecICDM/Integrations/SymantecICDM/SymantecICDM.py
  Packs/SymantecICDM/Integrations/SymantecICDM/SymantecICDM.yml
  Packs/SymantecICDM/Integrations/SymantecICDM/SymantecICDM_description.md
  Packs/SymantecICDM/Integrations/SymantecICDM/SymantecICDM_image.png
  Packs/SymantecICDM/Integrations/SymantecICDM/SymantecICDM_test.py
  Packs/SymantecICDM/Integrations/SymantecICDM/test_data/cve_protection_response.json
  Packs/SymantecICDM/Integrations/SymantecICDM/test_data/domain_insight_reputation_response.json
  Packs/SymantecICDM/Integrations/SymantecICDM/test_data/file_insight_reputation_response.json
  Packs/SymantecICDM/Integrations/SymantecICDM/test_data/file_protection_response.json
  Packs/SymantecICDM/Integrations/SymantecICDM/test_data/icdm_incidents_with_events.json
  Packs/SymantecICDM/Integrations/SymantecICDM/test_data/icdm_incidents_without_events.json
  Packs/SymantecICDM/Integrations/SymantecICDM/test_data/ip_insight_reputation_response.json
  Packs/SymantecICDM/Integrations/SymantecICDM/test_data/network_protection_response.json
  Packs/SymantecICDM/Integrations/SymantecICDM/test_data/outputs/icdm_incidents_output.json
  Packs/SymantecICDM/Integrations/SymantecICDM/test_data/url_insight_reputation_response.json
  Packs/SymantecICDM/README.md
  Packs/SymantecICDM/pack_metadata.json
Labels: Contribution, docs-approved, Contribution Form Filled, Community, Community Support Level, External PR

#39196 edit readme file
  Packs/SplunkPy/Integrations/SplunkPy/README.md
  Packs/SplunkPy/ReleaseNotes/3_2_6.md
  Packs/SplunkPy/doc_files/edit-role-non-admin-capabilities.png
  Packs/SplunkPy/doc_files/edit-role-non-admin-indexes.png
  Packs/SplunkPy/pack_metadata.json
Labels: docs-approved

#38701 Microsoft Defender for Endpoint - Command additions (get-machine-software, get-machine-missing-kbs)
  Packs/MicrosoftDefenderAdvancedThreatProtection/CONTRIBUTORS.json
  Packs/MicrosoftDefenderAdvancedThreatProtection/Integrations/MicrosoftDefenderAdvancedThreatProtection/MicrosoftDefenderAdvancedThreatProtection.py
  Packs/MicrosoftDefenderAdvancedThreatProtection/Integrations/MicrosoftDefenderAdvancedThreatProtection/MicrosoftDefenderAdvancedThreatProtection.yml
  Packs/MicrosoftDefenderAdvancedThreatProtection/Integrations/MicrosoftDefenderAdvancedThreatProtection/MicrosoftDefenderAdvancedThreatProtection_test.py
  Packs/MicrosoftDefenderAdvancedThreatProtection/Integrations/MicrosoftDefenderAdvancedThreatProtection/README.md
  Packs/MicrosoftDefenderAdvancedThreatProtection/Integrations/MicrosoftDefenderAdvancedThreatProtection/command_examples.txt
  Packs/MicrosoftDefenderAdvancedThreatProtection/ReleaseNotes/1_18_3.md
  Packs/MicrosoftDefenderAdvancedThreatProtection/pack_metadata.json
Labels: Contribution, docs-approved, Contribution Form Filled, Community, Xsoar Support Level, External PR

#39284 [Code owners] Update ContentManagement with talzich
  .github/CODEOWNERS
Labels: docs-approved

#39267 Box Quick Update
  Packs/Box/README.md
  Packs/Box/pack_metadata.json
Labels: docs-approved

#39290 [EM] Hide Pack
  Packs/CortexVulnerabilityManagement/pack_metadata.json
Labels: Contribution, docs-approved, Contribution Form Filled, Community, Xsoar Support Level, External PR

#38663 CortexCoreIR: added `quick actions` commands
  Packs/Core/Integrations/CortexCoreIR/CortexCoreIR.py
  Packs/Core/Integrations/CortexCoreIR/CortexCoreIR.yml
  Packs/Core/ReleaseNotes/3_2_29.md
  Packs/Core/pack_metadata.json
Labels: docs-approved

#39299 drop CortexVulnerabilityManagement from platform
  Packs/CortexVulnerabilityManagement/pack_metadata.json
Labels: docs-approved, ForceMerge

#38979 Nivbs/ciac 13013 quick actions
  Packs/Jira/Integrations/JiraV3/JiraV3.py
  Packs/Jira/Integrations/JiraV3/JiraV3.yml
  Packs/Jira/ReleaseNotes/3_2_17.md
  Packs/Jira/pack_metadata.json
  Packs/MicrosoftTeams/Integrations/MicrosoftTeams/MicrosoftTeams.py
  Packs/MicrosoftTeams/Integrations/MicrosoftTeams/MicrosoftTeams.yml
  Packs/MicrosoftTeams/ReleaseNotes/1_5_18.md
  Packs/MicrosoftTeams/pack_metadata.json
  Packs/ServiceNow/Integrations/ServiceNowv2/ServiceNowv2.py
  Packs/ServiceNow/Integrations/ServiceNowv2/ServiceNowv2.yml
  Packs/ServiceNow/ReleaseNotes/2_7_9.md
  Packs/ServiceNow/pack_metadata.json
  Packs/Slack/Integrations/SlackV3/SlackV3.py
  Packs/Slack/Integrations/SlackV3/SlackV3.yml
  Packs/Slack/ReleaseNotes/3_5_12.md
  Packs/Slack/pack_metadata.json
Labels: docs-approved, ForceMerge

#39297 Fix validate content tpb
  Packs/Base/TestPlaybooks/ValidateContent_-_Test.yml
  Tests/conf.json
Labels: docs-approved

#39086 FormatURL does not correctly extract URLs from URLs of type ProofPoint URLDefense v3
  Packs/ApiModules/ReleaseNotes/2_2_43.md
  Packs/ApiModules/Scripts/FormatURLApiModule/FormatURLApiModule.py
  Packs/ApiModules/Scripts/FormatURLApiModule/FormatURLApiModule_test.py
  Packs/ApiModules/pack_metadata.json
  Packs/CommonScripts/ReleaseNotes/1_19_35.md
  Packs/CommonScripts/Scripts/FormatURL/FormatURL.yml
  Packs/CommonScripts/Scripts/FormatURL/FormatURL_test.py
  Packs/CommonScripts/TestPlaybooks/FormatURL-Test.yml
  Packs/CommonScripts/pack_metadata.json
  Packs/Phishing/ReleaseNotes/3_7_0.md
  Packs/Phishing/pack_metadata.json
Labels: docs-approved

#39289 Modified readme file - Proofpoint TAP
  Packs/ProofpointTAP/README.md
Labels: docs-approved

#39074 Improve handling of command execution timeout using timed thread in QualysV2
  Packs/qualys/Integrations/Qualysv2/Qualysv2.py
  Packs/qualys/Integrations/Qualysv2/Qualysv2_test.py
  Packs/qualys/ReleaseNotes/3_2_6.md
  Packs/qualys/pack_metadata.json
Labels: bug, docs-approved, python

#38764 Updated Silverfort Pack README
  Packs/Silverfort/.secrets-ignore
  Packs/Silverfort/Integrations/Silverfort/README.md
  Packs/Silverfort/Integrations/Silverfort/Silverfort.yml
  Packs/Silverfort/ReleaseNotes/2_0_30.md
  Packs/Silverfort/pack_metadata.json
Labels: Contribution, docs-approved, Partner, Contribution Form Filled, pending-contributor, Partner Support Level, External PR, Partner-Approved

#39291 Fix for list of techniques in InvestigationDetailedSummaryToTable
  Packs/MalwareInvestigationAndResponse/ReleaseNotes/2_0_17.md
  Packs/MalwareInvestigationAndResponse/Scripts/InvestigationDetailedSummaryToTable/InvestigationDetailedSummaryToTable.py
  Packs/MalwareInvestigationAndResponse/Scripts/InvestigationDetailedSummaryToTable/InvestigationDetailedSummaryToTable.yml
  Packs/MalwareInvestigationAndResponse/Scripts/InvestigationDetailedSummaryToTable/InvestigationDetailedSummaryToTable_test.py
  Packs/MalwareInvestigationAndResponse/Scripts/InvestigationDetailedSummaryToTable/test_data/table_command.json
  Packs/MalwareInvestigationAndResponse/pack_metadata.json
Labels: docs-approved

#39263 CRTX-157746 - Celonis
  Packs/Celonis/ModelingRules/Celonis/Celonis.xif
  Packs/Celonis/ModelingRules/Celonis/Celonis.yml
  Packs/Celonis/ModelingRules/Celonis/Celonis_schema.json
  Packs/Celonis/README.md
  Packs/Celonis/ReleaseNotes/1_0_1.md
  Packs/Celonis/pack_metadata.json
Labels: docs-approved, bypass.url

#39316 fix corepacks for some packs
  Packs/EDL/ReleaseNotes/3_3_10.md
  Packs/EDL/pack_metadata.json
  Packs/FeedMitreAttackv2/ReleaseNotes/1_2_2.md
  Packs/FeedMitreAttackv2/pack_metadata.json
  Packs/GCP-Enrichment-Remediation/ReleaseNotes/1_1_22.md
  Packs/GCP-Enrichment-Remediation/pack_metadata.json
  Packs/GCP-IAM/ReleaseNotes/1_0_31.md
  Packs/GCP-IAM/pack_metadata.json
  Packs/GoogleCloudCompute/ReleaseNotes/1_1_17.md
  Packs/GoogleCloudCompute/pack_metadata.json
  Packs/HelloWorld/ReleaseNotes/3_0_18.md
  Packs/HelloWorld/pack_metadata.json
  Packs/Identity/ReleaseNotes/1_0_6.md
  Packs/Identity/pack_metadata.json
  Packs/Jira/ReleaseNotes/3_2_18.md
  Packs/Jira/pack_metadata.json
Labels: ForceMerge

#39307 Malwarebazaarfeed - Increase number of retries to 3 in total
  Packs/FeedMalwareBazaar/Integrations/MalwareBazaarFeed/MalwareBazaarFeed.py
  Packs/FeedMalwareBazaar/Integrations/MalwareBazaarFeed/MalwareBazaarFeed_test.py
  Packs/FeedMalwareBazaar/ReleaseNotes/1_0_45.md
  Packs/FeedMalwareBazaar/pack_metadata.json
Labels: docs-approved, ForceMerge

#39298 Update README.md
  Packs/ServiceNow/README.md
Labels: Contribution, docs-approved, Contribution Form Filled, Community, Xsoar Support Level, External PR, bypass.url

#39313 Domaintools Iris Pack Release v2.2.0
  Packs/DomainTools_Iris/.secrets-ignore
  Packs/DomainTools_Iris/Integrations/DomainTools_Iris/DomainTools_Iris.py
  Packs/DomainTools_Iris/Integrations/DomainTools_Iris/DomainTools_Iris.yml
  Packs/DomainTools_Iris/Integrations/DomainTools_Iris/DomainTools_Iris_test.py
  Packs/DomainTools_Iris/Integrations/DomainTools_Iris/README.md
  Packs/DomainTools_Iris/Integrations/DomainTools_Iris/test_data/expected.py
  Packs/DomainTools_Iris/Integrations/DomainTools_Iris/test_data/mock_response.py
  Packs/DomainTools_Iris/ReleaseNotes/2_2_0.md
  Packs/DomainTools_Iris/pack_metadata.json
Labels: Contribution, docs-approved, Partner, Contribution Form Filled, Partner Support Level, External PR, Partner-Approved

#38319 Enhance Google Workspace playbook
  Packs/CortexResponseAndRemediation/Playbooks/playbook-A_mail_forwarding_rule_was_configured_in_Google_Workspace.yml
  Packs/CortexResponseAndRemediation/Playbooks/playbook-A_mail_forwarding_rule_was_configured_in_Google_Workspace_README.md
  Packs/CortexResponseAndRemediation/Playbooks/silent-playbook-A_mail_forwarding_rule_was_configured_in_Google_Workspace_Test.yml
  Packs/CortexResponseAndRemediation/Playbooks/silent-playbook-MFA_was_disabled_for_an_Azure_identity.yml
  Packs/CortexResponseAndRemediation/ReleaseNotes/1_1_27.md
  Packs/CortexResponseAndRemediation/doc_files/A_mail_forwarding_rule_was_configured_in_Google_Workspace.png
  Packs/CortexResponseAndRemediation/pack_metadata.json
Labels: docs-approved

#39323 nmap: typo
  Packs/Nmap/Integrations/Nmap/Nmap.py
  Packs/Nmap/Integrations/Nmap/Nmap.yml
  Packs/Nmap/Integrations/Nmap/README.md
  Packs/Nmap/ReleaseNotes/1_2_7.md
  Packs/Nmap/pack_metadata.json
Labels: docs-approved

#39327 VMware typo
  Packs/VMware/Integrations/VMware/README.md
  Packs/VMware/Integrations/VMware/VMware.py
  Packs/VMware/Integrations/VMware/VMware.yml
  Packs/VMware/Integrations/VMware/VMware_description.md
  Packs/VMware/ReleaseNotes/1_2_14.md
  Packs/VMware/pack_metadata.json
Labels: docs-approved

#39310 Microsoft Teams: Fix newline rendering in webhook messages
  Packs/MicrosoftTeams/Integrations/MicrosoftTeamsWebhook/MicrosoftTeamsWebhook.py
  Packs/MicrosoftTeams/Integrations/MicrosoftTeamsWebhook/MicrosoftTeamsWebhook.yml
  Packs/MicrosoftTeams/Integrations/MicrosoftTeamsWebhook/MicrosoftTeamsWebhook_test.py
  Packs/MicrosoftTeams/Integrations/MicrosoftTeamsWebhook/README.md
  Packs/MicrosoftTeams/ReleaseNotes/1_5_19.md
  Packs/MicrosoftTeams/pack_metadata.json
Labels: docs-approved

#39244 Update-odbcconf-playbook
  Packs/CortexResponseAndRemediation/Playbooks/playbook-Uncommon_execution_of_ODBCConf.yml
  Packs/CortexResponseAndRemediation/Playbooks/playbook-Uncommon_execution_of_ODBCConf_README.md
  Packs/CortexResponseAndRemediation/ReleaseNotes/1_1_26.md
  Packs/CortexResponseAndRemediation/ReleaseNotes/1_1_28.md
  Packs/CortexResponseAndRemediation/doc_files/Uncommon_execution_of_ODBCConf.png
  Packs/CortexResponseAndRemediation/pack_metadata.json
Labels: docs-approved

#39311 GetTime
  Packs/CommonScripts/ReleaseNotes/1_19_36.md
  Packs/CommonScripts/Scripts/GetTime/GetTime.yml
  Packs/CommonScripts/Scripts/GetTime/README.md
  Packs/CommonScripts/pack_metadata.json
Labels: docs-approved

#39328 fix for silent-First Azure AD PowerShell operation for a user
  Packs/CortexResponseAndRemediation/Playbooks/silent-playbook-First_Azure_AD_PowerShell_operation_for_a_user.yml
  Packs/CortexResponseAndRemediation/ReleaseNotes/1_1_29.md
  Packs/CortexResponseAndRemediation/pack_metadata.json
Labels: docs-approved

#39292 Update the Interval In Seconds for polling mechanism default value to 30.
  Packs/ApiModules/Scripts/CoreXQLApiModule/CoreXQLApiModule.py
  Packs/Core/ReleaseNotes/3_2_30.md
  Packs/Core/pack_metadata.json
  Packs/CortexXDR/ReleaseNotes/6_2_16.md
  Packs/CortexXDR/pack_metadata.json
Labels: docs-approved

#39166 [Google Threat Intelligence] IoCStream cursor
  Packs/GoogleThreatIntelligence/Integrations/FeedIoCStream/FeedIoCStream.py
  Packs/GoogleThreatIntelligence/Integrations/FeedIoCStream/FeedIoCStream.yml
  Packs/GoogleThreatIntelligence/Integrations/FeedIoCStream/FeedIoCStream_test.py
  Packs/GoogleThreatIntelligence/Integrations/FeedIoCStream/README.md
  Packs/GoogleThreatIntelligence/ReleaseNotes/1_3_1.md
  Packs/GoogleThreatIntelligence/pack_metadata.json
Labels: Contribution, docs-approved, Partner, pending-demo, post-demo, Contribution Form Filled, Partner Support Level, External PR, Partner-Approved

#38795 [ServiceNowV2] Improve Retry Mechanism For Status Code 401
  Packs/ServiceNow/Integrations/ServiceNowv2/README.md
  Packs/ServiceNow/Integrations/ServiceNowv2/ServiceNowv2.py
  Packs/ServiceNow/Integrations/ServiceNowv2/ServiceNowv2.yml
  Packs/ServiceNow/Integrations/ServiceNowv2/ServiceNowv2_test.py
  Packs/ServiceNow/ReleaseNotes/2_7_10.md
  Packs/ServiceNow/pack_metadata.json
Labels: docs-approved, ForceMerge

#39320 Update Salesforce integration API Version to 63.0
  Packs/Salesforce/Integrations/Salesforce/README.md
  Packs/Salesforce/Integrations/Salesforce/Salesforce.js
  Packs/Salesforce/Integrations/Salesforce/Salesforce.yml
  Packs/Salesforce/ReleaseNotes/2_1_4.md
  Packs/Salesforce/TestPlaybooks/playbook-SalesforceTestPlaybook.yml
  Packs/Salesforce/pack_metadata.json
Labels: docs-approved

#39326 removed autopep8 hook, as part of adding ruff_format hook effort
  .pre-commit-config_template.yaml
Labels: docs-approved

#39015 Collector - Lookout Mobile Endpoint Security
  Packs/LookoutMobileEndpointSecurity/.pack-ignore
  Packs/LookoutMobileEndpointSecurity/.secrets-ignore
  Packs/LookoutMobileEndpointSecurity/Integrations/LookoutMobileEndpointSecurity/LookoutMobileEndpointSecurity.py
  Packs/LookoutMobileEndpointSecurity/Integrations/LookoutMobileEndpointSecurity/LookoutMobileEndpointSecurity.yml
  Packs/LookoutMobileEndpointSecurity/Integrations/LookoutMobileEndpointSecurity/LookoutMobileEndpointSecurity_description.md
  Packs/LookoutMobileEndpointSecurity/Integrations/LookoutMobileEndpointSecurity/LookoutMobileEndpointSecurity_image.png
  Packs/LookoutMobileEndpointSecurity/Integrations/LookoutMobileEndpointSecurity/LookoutMobileEndpointSecurity_test.py
  Packs/LookoutMobileEndpointSecurity/Integrations/LookoutMobileEndpointSecurity/README.md
  Packs/LookoutMobileEndpointSecurity/Integrations/LookoutMobileEndpointSecurity/command_examples.txt
  Packs/LookoutMobileEndpointSecurity/README.md
  Packs/LookoutMobileEndpointSecurity/pack_metadata.json
Labels: docs-approved

#39350 Added a note to the Cortex XDR pack
  Packs/CortexXDR/README.md
Labels: docs-approved

#39072 Implement workaround to escape placeholders
  Packs/ContentManagement/IncidentFields/incidentfield-KeepPlaceholdersInFiles.json
  Packs/ContentManagement/Layouts/layoutscontainer-Pull_Request_Creation.json
  Packs/ContentManagement/Playbooks/playbook-Pull_Request_Creation_-_Generic.yml
  Packs/ContentManagement/Playbooks/playbook-Pull_Request_Creation_-_Github.yml
  Packs/ContentManagement/ReleaseNotes/1_2_30.md
  Packs/ContentManagement/Scripts/CommitFiles/CommitFiles.py
  Packs/ContentManagement/Scripts/CommitFiles/CommitFiles.yml
  Packs/ContentManagement/Scripts/CommitFiles/CommitFiles_test.py
  Packs/ContentManagement/doc_files/Pull_Request_Creation_-_Generic.png
  Packs/ContentManagement/doc_files/Pull_Request_Creation_-_Github.png
  Packs/ContentManagement/pack_metadata.json
  Packs/GitHub/Integrations/GitHub/GitHub.py
  Packs/GitHub/Integrations/GitHub/GitHub.yml
  Packs/GitHub/ReleaseNotes/2_1_5.md
  Packs/GitHub/pack_metadata.json
Labels: docs-approved

#39112 CRTX-147053-Microsoft-Windows
  Packs/MicrosoftWindowsEvents/ModelingRules/MicrosoftWindowsEvents_1_3/MicrosoftWindowsEvents_1_3.xif
  Packs/MicrosoftWindowsEvents/ModelingRules/MicrosoftWindowsEvents_1_3/MicrosoftWindowsEvents_1_3_schema.json
  Packs/MicrosoftWindowsEvents/ReleaseNotes/1_1_12.md
  Packs/MicrosoftWindowsEvents/XSIAMDashboards/MicrosoftWindowsEvents_Dashboard.json
  Packs/MicrosoftWindowsEvents/pack_metadata.json
Labels: docs-approved, bypass.url
