Repository demisto/content, pull requests merged in 2025-08, with the labels that each got.

#40403 CODEOWNERS Validation
  .github/github_workflow_scripts/autobump_rn.py
  .github/github_workflow_scripts/codeowners_file_validation.py
  .github/github_workflow_scripts/request_contributor_review.py
  .github/github_workflow_scripts/send_slack_message.py
  .github/github_workflow_scripts/sync_contrib_base.py
  .github/github_workflow_scripts/utils.py
  .github/workflows/codeowners_file_validation.yml
Labels: docs-approved, ready-for-pipeline-running

#40809 Schedule generic polling - fail if a playbookId was not provided.
  Packs/CommonScripts/ReleaseNotes/1_19_94.md
  Packs/CommonScripts/Scripts/ScheduleGenericPolling/ScheduleGenericPolling.py
  Packs/CommonScripts/Scripts/ScheduleGenericPolling/ScheduleGenericPolling_test.py
  Packs/CommonScripts/pack_metadata.json
Labels: Contribution, docs-approved, Contribution Form Filled, Community, Xsoar Support Level, External PR

#40773 New Filters And Transformers Scripts: RemoveNullBytes
  Packs/FiltersAndTransformers/CONTRIBUTORS.json
  Packs/FiltersAndTransformers/ReleaseNotes/1_3_7.md
  Packs/FiltersAndTransformers/Scripts/RemoveNullBytes/README.md
  Packs/FiltersAndTransformers/Scripts/RemoveNullBytes/RemoveNullBytes.py
  Packs/FiltersAndTransformers/Scripts/RemoveNullBytes/RemoveNullBytes.yml
  Packs/FiltersAndTransformers/Scripts/RemoveNullBytes/RemoveNullBytes_test.py
  Packs/FiltersAndTransformers/pack_metadata.json
Labels: Contribution, docs-approved, Contribution Form Filled, Community, pending-contributor, Xsoar Support Level, External PR

#40811 Update Azure Network Security Group README
  Packs/AzureNetworkSecurityGroups/Integrations/AzureNetworkSecurityGroups/README.md
Labels: docs-approved, ready-for-pipeline-running

#40819 Improve Opswat file upload
  Packs/opswat-metadefender/Integrations/OPSWATMetadefenderV2/OPSWATMetadefenderV2.py
  Packs/opswat-metadefender/Integrations/OPSWATMetadefenderV2/OPSWATMetadefenderV2.yml
  Packs/opswat-metadefender/Integrations/OPSWATMetadefenderV2/OPSWATMetadefenderV2_description.md
  Packs/opswat-metadefender/Integrations/OPSWATMetadefenderV2/OPSWATMetadefenderV2_test.py
  Packs/opswat-metadefender/ReleaseNotes/1_0_16.md
  Packs/opswat-metadefender/pack_metadata.json
Labels: docs-approved, ready-for-pipeline-running

#40777 Fix email signature not being added in SendEmailReply script
  Packs/EmailCommunication/ReleaseNotes/2_0_44.md
  Packs/EmailCommunication/Scripts/SendEmailReply/SendEmailReply.py
  Packs/EmailCommunication/Scripts/SendEmailReply/SendEmailReply_test.py
  Packs/EmailCommunication/pack_metadata.json
Labels: bug, docs-approved, python, ready-for-pipeline-running

#40822 Bugfix/anyrun_update
  Packs/CommonPlaybooks/Playbooks/playbook-Detonate_URL_-_Generic_v1.5.yml
  Packs/CommonPlaybooks/ReleaseNotes/2_7_14.md
  Packs/CommonPlaybooks/pack_metadata.json
Labels: docs-approved, ready-for-pipeline-running

#40786 Rasterize - Add logs to provide additional info
  Packs/rasterize/Integrations/rasterize/rasterize.py
  Packs/rasterize/ReleaseNotes/2_1_14.md
  Packs/rasterize/pack_metadata.json
Labels: docs-approved, ForceMerge, ready-for-pipeline-running

#40817 Add cloud posture supported module
  Config/core_packs_platform_list.json
  Packs/AWS/ReleaseNotes/2_0_3.md
  Packs/AWS/pack_metadata.json
  Packs/Azure/ReleaseNotes/1_0_4.md
  Packs/Azure/pack_metadata.json
  Packs/GCP/ReleaseNotes/1_0_2.md
  Packs/GCP/pack_metadata.json
Labels: docs-approved, bypass.url, ready-for-pipeline-running

#40833 TIM/FeedProofPoint/XSUP-54294/Fixed fetch indicators for invalid category
  Packs/FeedProofpoint/Integrations/FeedProofpoint/FeedProofpoint.py
  Packs/FeedProofpoint/Integrations/FeedProofpoint/FeedProofpoint.yml
  Packs/FeedProofpoint/Integrations/FeedProofpoint/FeedProofpoint_test.py
  Packs/FeedProofpoint/Integrations/FeedProofpoint/TestData/domain-with-invalid-category.txt
  Packs/FeedProofpoint/ReleaseNotes/1_0_18.md
  Packs/FeedProofpoint/pack_metadata.json
Labels: docs-approved, ready-for-pipeline-running

#40552 [greynoise-266] Updating to support new SDK and APIs
  Packs/GreyNoise/.secrets-ignore
  Packs/GreyNoise/Integrations/GreyNoise/GreyNoise.py
  Packs/GreyNoise/Integrations/GreyNoise/GreyNoise.yml
  Packs/GreyNoise/Integrations/GreyNoise/GreyNoise_test.py
  Packs/GreyNoise/Integrations/GreyNoise/README.md
  Packs/GreyNoise/Integrations/GreyNoise/test_data/input_data.py
  Packs/GreyNoise/Integrations/GreyNoise/test_data/quick_check.txt
  Packs/GreyNoise/Integrations/GreyNoise_Community/GreyNoise_Community.py
  Packs/GreyNoise/Integrations/GreyNoise_Community/GreyNoise_Community.yml
  Packs/GreyNoise/Integrations/GreyNoise_Community/GreyNoise_Community_test.py
  Packs/GreyNoise/Integrations/GreyNoise_Community/README.md
  Packs/GreyNoise/Integrations/GreyNoise_Community/test_data/input_data.py
  Packs/GreyNoise/ReleaseNotes/2_0_0.md
  Packs/GreyNoise/pack_metadata.json
Labels: Contribution, docs-approved, Partner, Contribution Form Filled, Partner Support Level, External PR, Partner-Approved

#40771 XSUP-53329
  Packs/CrowdStrikeFalconSandbox/Integrations/CrowdStrikeFalconSandboxV2/CrowdStrikeFalconSandboxV2.py
  Packs/CrowdStrikeFalconSandbox/Integrations/CrowdStrikeFalconSandboxV2/CrowdStrikeFalconSandboxV2.yml
  Packs/CrowdStrikeFalconSandbox/Integrations/CrowdStrikeFalconSandboxV2/CrowdStrikeFalconSandboxV2_test.py
  Packs/CrowdStrikeFalconSandbox/Integrations/CrowdStrikeFalconSandboxV2/README.md
  Packs/CrowdStrikeFalconSandbox/Integrations/CrowdStrikeFalconSandboxV2/test_data/scan_response.json
  Packs/CrowdStrikeFalconSandbox/ReleaseNotes/2_0_27.md
  Packs/CrowdStrikeFalconSandbox/pack_metadata.json
Labels: docs-approved, ready-for-pipeline-running

#40837 SNOW bump version
  Packs/ServiceNow/ReleaseNotes/2_8_6.md
  Packs/ServiceNow/pack_metadata.json
Labels: docs-approved, ready-for-pipeline-running

#40758 XDM Mapping for Jira Data Center
  Packs/Jira/ParsingRules/JiraParsingRules/JiraParsingRules.xif
  Packs/Jira/ReleaseNotes/3_3_5.md
  Packs/Jira/pack_metadata.json
  Packs/JiraDataCenter/.pack-ignore
  Packs/JiraDataCenter/.secrets-ignore
  Packs/JiraDataCenter/ModelingRules/JiraDataCenter/JiraDataCenter.xif
  Packs/JiraDataCenter/ModelingRules/JiraDataCenter/JiraDataCenter.yml
  Packs/JiraDataCenter/ModelingRules/JiraDataCenter/JiraDataCenter_schema.json
  Packs/JiraDataCenter/ParsingRules/JiraDataCenter/JiraDataCenter.xif
  Packs/JiraDataCenter/ParsingRules/JiraDataCenter/JiraDataCenter.yml
  Packs/JiraDataCenter/README.md
  Packs/JiraDataCenter/pack_metadata.json
Labels: docs-approved, bypass.url, ready-for-pipeline-running

#40858 Updating contrib team
  .github/content_roles.json
Labels: docs-approved, ready-for-pipeline-running

#40785 Command Line Analysis - Lateral Movement Bug Fix
  Packs/CommonScripts/ReleaseNotes/1_19_96.md
  Packs/CommonScripts/Scripts/CommandLineAnalysis/CommandLineAnalysis.py
  Packs/CommonScripts/Scripts/CommandLineAnalysis/CommandLineAnalysis.yml
  Packs/CommonScripts/pack_metadata.json
Labels: docs-approved, ready-for-pipeline-running

#40826 Adding modeling rule for lookout mes pack
  Packs/FortinetFortiwebVM/.secrets-ignore
  Packs/LookoutMobileEndpointSecurity/.pack-ignore
  Packs/LookoutMobileEndpointSecurity/ModelingRules/LookoutMobileEndpointSecurity/LookoutMobileEndpointSecurity.xif
  Packs/LookoutMobileEndpointSecurity/ModelingRules/LookoutMobileEndpointSecurity/LookoutMobileEndpointSecurity.yml
  Packs/LookoutMobileEndpointSecurity/ModelingRules/LookoutMobileEndpointSecurity/LookoutMobileEndpointSecurity_schema.json
  Packs/LookoutMobileEndpointSecurity/README.md
  Packs/LookoutMobileEndpointSecurity/ReleaseNotes/1_0_2.md
  Packs/LookoutMobileEndpointSecurity/pack_metadata.json
Labels: docs-approved, bypass.url, ready-for-pipeline-running

#40878 Tim/add description of how the indicator relationship is extracted
  Packs/FeedTAXII/Integrations/FeedTAXII2/FeedTAXII2_description.md
  Packs/FeedTAXII/ReleaseNotes/1_2_37.md
  Packs/FeedTAXII/pack_metadata.json
Labels: docs-approved, ready-for-pipeline-running

#40682 [Armis Event Collector] Update pagination handling in fetch-events
  Packs/Armis/Integrations/ArmisEventCollector/ArmisEventCollector.py
  Packs/Armis/Integrations/ArmisEventCollector/ArmisEventCollector.yml
  Packs/Armis/Integrations/ArmisEventCollector/ArmisEventCollector_test.py
  Packs/Armis/ReleaseNotes/1_2_2.md
  Packs/Armis/pack_metadata.json
Labels: docs-approved, ready-for-pipeline-running

#40787 Fix: Assign default value for confidence_score when NA to ensure DBot compatibility
  Packs/CTIX/Integrations/CTIXv3/CTIXv3.py
  Packs/CTIX/Integrations/CTIXv3/CTIXv3.yml
  Packs/CTIX/Integrations/CTIXv3/test_data/get_threat_data.json
  Packs/CTIX/ReleaseNotes/2_2_20.md
  Packs/CTIX/pack_metadata.json
Labels: Contribution, docs-approved, Partner, Contribution Form Filled, Partner Support Level, External PR, Partner-Approved

#40887 Rn for demisto-sdk-release 1.38.9
  Packs/SentinelOne/ReleaseNotes/3_2_44.md
  Packs/SentinelOne/pack_metadata.json
Labels: docs-approved, ready-for-pipeline-running

#40417 XDRIR - Allow multiple files data in received alert
  Packs/CortexXDR/Integrations/CortexXDRIR/CortexXDRIR.py
  Packs/CortexXDR/Integrations/CortexXDRIR/CortexXDRIR.yml
  Packs/CortexXDR/Integrations/CortexXDRIR/CortexXDRIR_test.py
  Packs/CortexXDR/ReleaseNotes/6_2_33.json
  Packs/CortexXDR/ReleaseNotes/6_2_33.md
  Packs/CortexXDR/pack_metadata.json
  Packs/CortexXpanse/Integrations/CortexXpanse/CortexXpanse.py
  Packs/CortexXpanse/Integrations/CortexXpanse/CortexXpanse.yml
  Packs/CortexXpanse/ReleaseNotes/1_2_13.md
  Packs/CortexXpanse/pack_metadata.json
  Packs/ctf01/Integrations/CortexXDRIRCTF/CortexXDRIRCTF.py
  Packs/ctf01/Integrations/CortexXDRIRCTF/CortexXDRIRCTF.yml
  Packs/ctf01/ReleaseNotes/1_0_48.md
  Packs/ctf01/pack_metadata.json
Labels: docs-approved, ready-for-pipeline-running

#40522 Add triggers to hide the port field
  Packs/AWS-SNS-Listener/Integrations/AWSSNSListener/AWSSNSListener.yml
  Packs/AWS-SNS-Listener/ReleaseNotes/1_0_12.md
  Packs/AWS-SNS-Listener/pack_metadata.json
  Packs/EDL/Integrations/EDL/EDL.yml
  Packs/EDL/ReleaseNotes/3_3_18.md
  Packs/EDL/pack_metadata.json
  Packs/ExportIndicators/Integrations/ExportIndicators/ExportIndicators.yml
  Packs/ExportIndicators/ReleaseNotes/1_0_21.md
  Packs/ExportIndicators/pack_metadata.json
  Packs/MicrosoftTeams/Integrations/MicrosoftTeams/MicrosoftTeams.yml
  Packs/MicrosoftTeams/ReleaseNotes/1_5_42.md
  Packs/MicrosoftTeams/pack_metadata.json
  Packs/PingCastle/Integrations/PingCastle/PingCastle.py
  Packs/PingCastle/Integrations/PingCastle/PingCastle.yml
  Packs/PingCastle/ReleaseNotes/1_0_14.md
  Packs/PingCastle/pack_metadata.json
  Packs/PublishList/Integrations/PublishList/PublishList.yml
  Packs/PublishList/ReleaseNotes/1_1_9.md
  Packs/PublishList/pack_metadata.json
  Packs/SimpleAPIProxy/Integrations/SimpleAPIProxy/SimpleAPIProxy.yml
  Packs/SimpleAPIProxy/ReleaseNotes/1_0_9.md
  Packs/SimpleAPIProxy/pack_metadata.json
  Packs/Syslog/Integrations/Syslogv2/Syslogv2.yml
  Packs/Syslog/ReleaseNotes/2_0_24.md
  Packs/Syslog/pack_metadata.json
  Packs/TAXIIServer/Integrations/TAXII2Server/TAXII2Server.yml
  Packs/TAXIIServer/Integrations/TAXIIServer/TAXIIServer.yml
  Packs/TAXIIServer/ReleaseNotes/2_1_10.md
  Packs/TAXIIServer/pack_metadata.json
  Packs/WebFileRepository/Integrations/WebFileRepository/WebFileRepository.yml
  Packs/WebFileRepository/ReleaseNotes/1_0_32.md
  Packs/WebFileRepository/pack_metadata.json
  Packs/Workday/Integrations/WorkdayIAMEventsGenerator/WorkdayIAMEventsGenerator.yml
  Packs/Workday/ReleaseNotes/1_5_4.md
  Packs/Workday/pack_metadata.json
  Packs/XsoarWebserver/Integrations/XSOARWebServer/XSOARWebServer.yml
  Packs/XsoarWebserver/ReleaseNotes/1_0_9.md
  Packs/XsoarWebserver/pack_metadata.json
Labels: ForceMerge, ready-for-pipeline-running

#40893 Fixed XSIAM tag in Generic Web hook RN
  Packs/GenericWebhook/ReleaseNotes/1_1_10.md
Labels: docs-approved, ready-for-pipeline-running

#40839 [Pack][RecordedFutureV3] Update integration readme: add link to migration guide.
  Packs/RecordedFutureV3/Integrations/RecordedFutureAlerts/README.md
Labels: Contribution, docs-approved, Partner, Contribution Form Filled, Partner Support Level, External PR, Partner-Approved

#40889 fix: add input validation
  Packs/CommonScripts/ReleaseNotes/1_19_98.md
  Packs/CommonScripts/Scripts/MapValues/MapValues.js
  Packs/CommonScripts/Scripts/MapValues/MapValues.yml
  Packs/CommonScripts/pack_metadata.json
Labels: docs-approved, ready-for-pipeline-running

#40880 XSUP-54350 getServerURL extend context does not work with return_outputs()
  Packs/CommonScripts/ReleaseNotes/1_19_99.md
  Packs/CommonScripts/Scripts/GetServerURL/GetServerURL.py
  Packs/CommonScripts/Scripts/GetServerURL/GetServerURL.yml
  Packs/CommonScripts/Scripts/GetServerURL/GetServerURL_test.py
  Packs/CommonScripts/pack_metadata.json
Labels: docs-approved, ready-for-pipeline-running

#40466 Fix PolySwarmV2 integration
  Packs/PolySwarm/Integrations/PolySwarmV2/PolySwarmV2.py
  Packs/PolySwarm/Integrations/PolySwarmV2/PolySwarmV2.yml
  Packs/PolySwarm/Integrations/PolySwarmV2/PolySwarmV2_test.py
  Packs/PolySwarm/Integrations/PolySwarmV2/test_data/fixtures/vcr/test_file.tape
  Packs/PolySwarm/Integrations/PolySwarmV2/test_data/fixtures/vcr/test_file_rescan.tape
  Packs/PolySwarm/Integrations/PolySwarmV2/test_data/fixtures/vcr/test_file_scan.tape
  Packs/PolySwarm/Integrations/PolySwarmV2/test_data/fixtures/vcr/test_get_file.tape
  Packs/PolySwarm/Integrations/PolySwarmV2/test_data/fixtures/vcr/test_polyswarm_get_report.tape
  Packs/PolySwarm/Integrations/PolySwarmV2/test_data/fixtures/vcr/test_reputation[domain].tape
  Packs/PolySwarm/Integrations/PolySwarmV2/test_data/fixtures/vcr/test_reputation[ip].tape
  Packs/PolySwarm/Integrations/PolySwarmV2/test_data/fixtures/vcr/test_reputation[url].tape
  Packs/PolySwarm/Integrations/PolySwarmV2/test_data/vendored_pytest_vcr.py
  Packs/PolySwarm/ReleaseNotes/2_0_9.md
  Packs/PolySwarm/pack_metadata.json
Labels: Contribution, docs-approved, Partner, Contribution Form Filled, External PR, Partner-Approved

#40862 Move ExecutionTimeout to CommonServerPython
  Packs/Base/ReleaseNotes/1_41_14.md
  Packs/Base/Scripts/CommonServerPython/CommonServerPython.py
  Packs/Base/Scripts/CommonServerPython/CommonServerPython_test.py
  Packs/Base/pack_metadata.json
  Packs/qualys/Integrations/Qualysv2/Qualysv2.py
  Packs/qualys/Integrations/Qualysv2/Qualysv2.yml
  Packs/qualys/Integrations/Qualysv2/Qualysv2_test.py
  Packs/qualys/ReleaseNotes/3_3_6.md
  Packs/qualys/pack_metadata.json
Labels: docs-approved, python, ForceMerge, ready-for-pipeline-running

#40908 Sap C4C pack metadata fixes
  Packs/SAPCloudForCustomerC4C/ReleaseNotes/1_0_1.md
  Packs/SAPCloudForCustomerC4C/pack_metadata.json
Labels: docs-approved, ready-for-pipeline-running

#40921 deleted images
  Packs/MicrosoftEntraID/ModelingRules/MicrosoftEntraID/MicrosoftEntraID_dark.svg
  Packs/MicrosoftEntraID/ParsingRules/MicrosoftEntraID/MicrosoftEntraID_dark.svg
  Packs/Office365/ModelingRules/Office365/Office365_dark.svg
  Packs/Office365/ParsingRules/Office365/Office365_dark.svg
Labels: ForceMerge, bypass.url, ready-for-pipeline-running

#40717 Netskope Event Collector V2 /CIAC-14266
  Packs/Netskope/.pack-ignore
  Packs/Netskope/Integrations/NetskopeEventCollector_v2/NetskopeEventCollector_v2.py
  Packs/Netskope/Integrations/NetskopeEventCollector_v2/NetskopeEventCollector_v2.yml
  Packs/Netskope/Integrations/NetskopeEventCollector_v2/NetskopeEventCollector_v2_dark.svg
  Packs/Netskope/Integrations/NetskopeEventCollector_v2/NetskopeEventCollector_v2_description.md
  Packs/Netskope/Integrations/NetskopeEventCollector_v2/NetskopeEventCollector_v2_image.png
  Packs/Netskope/Integrations/NetskopeEventCollector_v2/NetskopeEventCollector_v2_light.svg
  Packs/Netskope/Integrations/NetskopeEventCollector_v2/NetskopeEventCollector_v2_test.py
  Packs/Netskope/Integrations/NetskopeEventCollector_v2/README.md
  Packs/Netskope/ReleaseNotes/4_1_0.md
  Packs/Netskope/pack_metadata.json
Labels: docs-approved, ready-for-pipeline-running

#40841 Fix for domain name mapping issue
  Packs/QRadar/Integrations/QRadar_v3/QRadar_v3.py
  Packs/QRadar/ReleaseNotes/2_5_25.md
  Packs/QRadar/pack_metadata.json
Labels: docs-approved, ready-for-pipeline-running

#40849 Add commands list requests request approve request deny
  Packs/AdminByRequest/Integrations/AdminByRequestEventCollector/AdminByRequestEventCollector.py
  Packs/AdminByRequest/Integrations/AdminByRequestEventCollector/AdminByRequestEventCollector.yml
  Packs/AdminByRequest/Integrations/AdminByRequestEventCollector/AdminByRequestEventCollector_test.py
  Packs/AdminByRequest/Integrations/AdminByRequestEventCollector/README.md
  Packs/AdminByRequest/ReleaseNotes/1_0_3.md
  Packs/AdminByRequest/pack_metadata.json
Labels: docs-approved, post-demo, ready-for-pipeline-running

#40930 Refactoring_Unprivileged_process_opened_a_registry_hive
  Packs/CortexResponseAndRemediation/Playbooks/playbook-Unprivileged_process_opened_a_registry_hive.yml
  Packs/CortexResponseAndRemediation/Playbooks/silent-playbook-Unprivileged_process_opened_a_registry_hive_Test.yml
  Packs/CortexResponseAndRemediation/ReleaseNotes/1_1_98.md
  Packs/CortexResponseAndRemediation/pack_metadata.json
Labels: docs-approved, ready-for-pipeline-running

#40940 Fix CRTX-191703
  Packs/SentinelOne/ReleaseNotes/3_2_46.md
  Packs/SentinelOne/pack_metadata.json
Labels: docs-approved, ready-for-pipeline-running

#40949 [uptycs] Fix Import
  Packs/Uptycs/Integrations/Uptycs/Uptycs.py
  Packs/Uptycs/Integrations/Uptycs/Uptycs.yml
  Packs/Uptycs/ReleaseNotes/1_0_20.md
  Packs/Uptycs/pack_metadata.json
Labels: docs-approved, ready-for-pipeline-running

#40954 Fix getendpointdata enum issue
  Packs/AggregatedScripts/ReleaseNotes/1_0_16.md
  Packs/AggregatedScripts/Scripts/GetEndpointData/GetEndpointData.py
  Packs/AggregatedScripts/pack_metadata.json
Labels: docs-approved, ready-for-pipeline-running

#40955 Fix error handling when loading signature in sendEmailReply script
  Packs/EmailCommunication/ReleaseNotes/2_0_46.md
  Packs/EmailCommunication/Scripts/SendEmailReply/SendEmailReply.py
  Packs/EmailCommunication/Scripts/SendEmailReply/SendEmailReply_test.py
  Packs/EmailCommunication/pack_metadata.json
Labels: bug, docs-approved, python, ready-for-pipeline-running

#40950 AWS Lambda: fix readme
  Packs/AWS-Lambda/Integrations/AWS_Lambda/AWS_Lambda.yml
  Packs/AWS-Lambda/Integrations/AWS_Lambda/README.md
  Packs/AWS-Lambda/ReleaseNotes/1_3_14.md
  Packs/AWS-Lambda/pack_metadata.json
Labels: docs-approved, ready-for-pipeline-running

#40958 [GetUserData] fix manger not appearing for MS Graph
  Packs/AggregatedScripts/ReleaseNotes/1_0_17.md
  Packs/AggregatedScripts/Scripts/GetUserData/GetUserData.py
  Packs/AggregatedScripts/Scripts/GetUserData/GetUserData_test.py
  Packs/AggregatedScripts/pack_metadata.json
Labels: docs-approved, ready-for-pipeline-running

#40759 Fix Python 3.12 compatibility by replacing deprecated distutils.util.strtobool
  Packs/Base/ReleaseNotes/1_41_15.md
  Packs/Base/Scripts/CommonServerPython/CommonServerPython.py
  Packs/Base/Scripts/CommonServerPython/CommonServerPython_test.py
  Packs/Base/pack_metadata.json
  Packs/Claroty/Integrations/Claroty/Claroty.py
  Packs/Claroty/Integrations/Claroty/Claroty.yml
  Packs/Claroty/ReleaseNotes/1_0_30.md
  Packs/Claroty/pack_metadata.json
  Packs/Gmail/Integrations/Gmail/Gmail.py
  Packs/Gmail/Integrations/Gmail/Gmail.yml
  Packs/Gmail/ReleaseNotes/1_3_36.md
  Packs/Gmail/pack_metadata.json
  Packs/PhishLabs/ReleaseNotes/1_1_28.md
  Packs/PhishLabs/Scripts/PhishLabsPopulateIndicators/PhishLabsPopulateIndicators.py
  Packs/PhishLabs/Scripts/PhishLabsPopulateIndicators/PhishLabsPopulateIndicators.yml
  Packs/PhishLabs/Scripts/PhishLabsPopulateIndicators/README.md
  Packs/PhishLabs/pack_metadata.json
  Packs/SymantecManagementCenter/Integrations/SymantecManagementCenter/SymantecManagementCenter.py
  Packs/SymantecManagementCenter/Integrations/SymantecManagementCenter/SymantecManagementCenter.yml
  Packs/SymantecManagementCenter/ReleaseNotes/1_0_14.md
  Packs/SymantecManagementCenter/pack_metadata.json
  Packs/Syslog/Integrations/SyslogSender/SyslogSender.py
  Packs/Syslog/Integrations/SyslogSender/SyslogSender.yml
  Packs/Syslog/ReleaseNotes/2_0_25.md
  Packs/Syslog/pack_metadata.json
Labels: docs-approved, ForceMerge, ready-for-pipeline-running

#40960 Recorded Future fixed an issue with the performance parameter
  Packs/FeedRecordedFuture/Integrations/FeedRecordedFuture/FeedRecordedFuture.py
  Packs/FeedRecordedFuture/Integrations/FeedRecordedFuture/FeedRecordedFuture.yml
  Packs/FeedRecordedFuture/Integrations/FeedRecordedFuture/FeedRecordedFuture_test.py
  Packs/FeedRecordedFuture/ReleaseNotes/1_2_2.md
  Packs/FeedRecordedFuture/pack_metadata.json
Labels: docs-approved, ready-for-pipeline-running

#40936 [CRTX-183528] Microsoft Windows Events Enhancement
  Packs/MicrosoftWindowsEvents/ModelingRules/MicrosoftWindowsEvents_1_3/MicrosoftWindowsEvents_1_3.xif
  Packs/MicrosoftWindowsEvents/ReleaseNotes/1_1_19.md
  Packs/MicrosoftWindowsEvents/pack_metadata.json
Labels: docs-approved, bypass.url, ready-for-pipeline-running

#40965 Azure App Service - Parsing Rule Enhancement 2 - CRTX-190014
  Packs/AzureAppService/ParsingRules/AzureAppService/AzureAppService.xif
  Packs/AzureAppService/ReleaseNotes/1_0_5.md
  Packs/AzureAppService/pack_metadata.json
Labels: docs-approved, bypass.url, ready-for-pipeline-running

#40288 Update README.md
  Packs/FeedThreatFox/Integrations/FeedThreatFox/README.md
Labels: docs-approved, ready-for-pipeline-running

#40720 improve common scripts
  Packs/Base/ReleaseNotes/1_41_17.md
  Packs/Base/Scripts/CommonServer/CommonServer.js
  Packs/Base/pack_metadata.json
  Packs/CommonScripts/ReleaseNotes/1_20_2.md
  Packs/CommonScripts/Scripts/CalculateTimeDifference/CalculateTimeDifference.js
  Packs/CommonScripts/Scripts/CalculateTimeDifference/CalculateTimeDifference.py
  Packs/CommonScripts/Scripts/CalculateTimeDifference/CalculateTimeDifference.yml
  Packs/CommonScripts/Scripts/CalculateTimeDifference/README.md
  Packs/CommonScripts/Scripts/GetIndicatorDBotScoreFromCache/GetIndicatorDBotScoreFromCache.js
  Packs/CommonScripts/Scripts/GetIndicatorDBotScoreFromCache/GetIndicatorDBotScoreFromCache.py
  Packs/CommonScripts/Scripts/GetIndicatorDBotScoreFromCache/GetIndicatorDBotScoreFromCache.yml
  Packs/CommonScripts/Scripts/GetIndicatorDBotScoreFromCache/GetIndicatorDBotScoreFromCache_test.py
  Packs/CommonScripts/Scripts/GetIndicatorDBotScoreFromCache/README.md
  Packs/CommonScripts/Scripts/GetServerURL/GetServerURL.js
  Packs/CommonScripts/Scripts/GetServerURL/GetServerURL.py
  Packs/CommonScripts/Scripts/GetServerURL/GetServerURL.yml
  Packs/CommonScripts/Scripts/GetServerURL/GetServerURL_test.py
  Packs/CommonScripts/Scripts/GetServerURL/README.md
  Packs/CommonScripts/Scripts/SearchIndicator/README.md
  Packs/CommonScripts/Scripts/SearchIndicator/SearchIndicator.js
  Packs/CommonScripts/Scripts/SearchIndicator/SearchIndicator.py
  Packs/CommonScripts/Scripts/SearchIndicator/SearchIndicator.yml
  Packs/CommonScripts/Scripts/SearchIndicator/SearchIndicator_test.py
  Packs/CommonScripts/pack_metadata.json
  Packs/DemistoRESTAPI/ReleaseNotes/1_3_81.md
  Packs/DemistoRESTAPI/Scripts/GetIncidentTasks/GetIncidentTasks.js
  Packs/DemistoRESTAPI/Scripts/GetIncidentTasks/GetIncidentTasks.py
  Packs/DemistoRESTAPI/Scripts/GetIncidentTasks/GetIncidentTasks.yml
  Packs/DemistoRESTAPI/Scripts/GetIncidentTasks/README.md
  Packs/DemistoRESTAPI/pack_metadata.json
Labels: docs-approved, release-notes-only, ForceMerge, ready-for-pipeline-running

#40974 Fix externalIp handling
  Packs/SentinelOne/ReleaseNotes/3_2_47.md
  Packs/SentinelOne/Scripts/SentinelOneListAgents/SentinelOneListAgents.py
  Packs/SentinelOne/Scripts/SentinelOneListAgents/SentinelOneListAgents.yml
  Packs/SentinelOne/Scripts/SentinelOneListAgents/SentinelOneListAgents_test.py
  Packs/SentinelOne/pack_metadata.json
Labels: docs-approved, ForceMerge, ready-for-pipeline-running

#40780 Added/unshorten me integration
  Packs/Unshorten_Me/.pack-ignore
  Packs/Unshorten_Me/.secrets-ignore
  Packs/Unshorten_Me/Integrations/unshortenMe/README.md
  Packs/Unshorten_Me/Integrations/unshortenMe/test_data/failure_response.json
  Packs/Unshorten_Me/Integrations/unshortenMe/test_data/success_response.json
  Packs/Unshorten_Me/Integrations/unshortenMe/unshortenMe.py
  Packs/Unshorten_Me/Integrations/unshortenMe/unshortenMe.yml
  Packs/Unshorten_Me/Integrations/unshortenMe/unshortenMe_description.md
  Packs/Unshorten_Me/Integrations/unshortenMe/unshortenMe_image.png
  Packs/Unshorten_Me/Integrations/unshortenMe/unshortenMe_test.py
  Packs/Unshorten_Me/README.md
  Packs/Unshorten_Me/pack_metadata.json
Labels: Contribution, docs-approved, Contribution Form Filled, Community, pending-contributor, Community Support Level, External PR

#40989 [XSUP-54205] dell emc unity parinsg rule
  Packs/DellEMCUnity/ParsingRules/DellEMCUnity/DellEMCUnity.xif
  Packs/DellEMCUnity/ReleaseNotes/1_0_2.md
  Packs/DellEMCUnity/pack_metadata.json
Labels: docs-approved, ready-for-pipeline-running

#40852 Nbensalmon/ciac 14320 aggregated command file enrichment internal sources fix
  Packs/AggregatedScripts/ReleaseNotes/1_0_18.json
  Packs/AggregatedScripts/ReleaseNotes/1_0_18.md
  Packs/AggregatedScripts/Scripts/FileEnrichment/FileEnrichment.py
  Packs/AggregatedScripts/Scripts/FileEnrichment/FileEnrichment.yml
  Packs/AggregatedScripts/Scripts/FileEnrichment/FileEnrichment_test.py
  Packs/AggregatedScripts/Scripts/FileEnrichment/README.md
  Packs/AggregatedScripts/pack_metadata.json
Labels: docs-approved, ForceMerge, ready-for-pipeline-running

#40882 CIAC-14385
  Packs/AWS/ReleaseNotes/2_0_4.md
  Packs/AWS/pack_metadata.json
  Packs/ApiModules/ReleaseNotes/2_2_51.md
  Packs/ApiModules/Scripts/COOCApiModule/COOCApiModule.py
  Packs/ApiModules/Scripts/COOCApiModule/COOCApiModule_test.py
  Packs/ApiModules/pack_metadata.json
  Packs/Azure/ReleaseNotes/1_0_7.md
  Packs/Azure/pack_metadata.json
  Packs/GCP/ReleaseNotes/1_0_3.md
  Packs/GCP/pack_metadata.json
Labels: docs-approved, bypass.url, ready-for-pipeline-running

#40910 Remove references to Core's secrets
  Packs/Core/Integrations/CoreIOCs/CoreIOCs.py
  Packs/Core/Integrations/CoreIOCs/CoreIOCs.yml
  Packs/Core/Integrations/CoreIOCs/CoreIOCs_test.py
  Packs/Core/Integrations/CortexCoreIR/CortexCoreIR.py
  Packs/Core/ReleaseNotes/3_4_13.md
  Packs/Core/pack_metadata.json
Labels: docs-approved, ready-for-pipeline-running

#40590 Check point xdr new
  Packs/CheckPointXDR/.pack-ignore
  Packs/CheckPointXDR/.secrets-ignore
  Packs/CheckPointXDR/Author_image.png
  Packs/CheckPointXDR/CONTRIBUTORS.json
  Packs/CheckPointXDR/Classifiers/classifier-XDR_-_Incoming_Mapper.json
  Packs/CheckPointXDR/Classifiers/classifier-XDR_-_Outgoing_Mapper.json
  Packs/CheckPointXDR/IncidentTypes/incidenttype-CheckPoint_XDR_Incident.json
  Packs/CheckPointXDR/Integrations/CheckPointXDR/CheckPointXDR.py
  Packs/CheckPointXDR/Integrations/CheckPointXDR/CheckPointXDR.yml
  Packs/CheckPointXDR/Integrations/CheckPointXDR/CheckPointXDR_description.md
  Packs/CheckPointXDR/Integrations/CheckPointXDR/CheckPointXDR_image.png
  Packs/CheckPointXDR/Integrations/CheckPointXDR/CheckPointXDR_test.py
  Packs/CheckPointXDR/Integrations/CheckPointXDR/README.md
  Packs/CheckPointXDR/Integrations/CheckPointXDR/test_data/checkpointxdr-get_incidents.json
  Packs/CheckPointXDR/Integrations/CheckPointXDR/test_data/checkpointxdr-login-response.json
  Packs/CheckPointXDR/Integrations/CheckPointXDR/test_data/checkpointxdr-parse_incident-output.json
  Packs/CheckPointXDR/Integrations/CheckPointXDR/test_data/checkpointxdr-update-incident-response.json
  Packs/CheckPointXDR/Layouts/layoutscontainer-CheckPointXDR_Incident_Layout.json
  Packs/CheckPointXDR/PreProcessRules/preprocessingrule-eliminate-duplicates.json
  Packs/CheckPointXDR/README.md
  Packs/CheckPointXDR/pack_metadata.json
Labels: Contribution, docs-approved, Partner, Contribution Form Filled, pending-contributor, Partner Support Level, External PR, Security Review, Partner-Approved, Security Approved

#40959 Huawei FW - Mapping
  Packs/HuaweiFW/.pack-ignore
  Packs/HuaweiFW/.secrets-ignore
  Packs/HuaweiFW/ModelingRules/HuaweiFW/HuaweiFW.xif
  Packs/HuaweiFW/ModelingRules/HuaweiFW/HuaweiFW.yml
  Packs/HuaweiFW/ModelingRules/HuaweiFW/HuaweiFW_schema.json
  Packs/HuaweiFW/ParsingRules/HuaweiFW/HuaweiFW.xif
  Packs/HuaweiFW/ParsingRules/HuaweiFW/HuaweiFW.yml
  Packs/HuaweiFW/README.md
  Packs/HuaweiFW/pack_metadata.json
Labels: docs-approved, bypass.url, ready-for-pipeline-running

#40695 Cyberwatch integration 1.0.4
  Packs/Cyberwatch/Integrations/Cyberwatch/Cyberwatch.py
  Packs/Cyberwatch/Integrations/Cyberwatch/Cyberwatch.yml
  Packs/Cyberwatch/Integrations/Cyberwatch/Cyberwatch_test.py
  Packs/Cyberwatch/Integrations/Cyberwatch/README.md
  Packs/Cyberwatch/Integrations/Cyberwatch/test_data/test_fetch_compliance_asset.json
  Packs/Cyberwatch/Integrations/Cyberwatch/test_data/test_fetch_sysadmin_server.json
  Packs/Cyberwatch/Integrations/Cyberwatch/test_data/test_list_compliance_assets.json
  Packs/Cyberwatch/Integrations/Cyberwatch/test_data/test_list_compliance_assets_page.json
  Packs/Cyberwatch/Integrations/Cyberwatch/test_data/test_list_sysadmin_servers.json
  Packs/Cyberwatch/Integrations/Cyberwatch/test_data/test_list_sysadmin_servers_page.json
  Packs/Cyberwatch/README.md
  Packs/Cyberwatch/ReleaseNotes/1_0_4.md
  Packs/Cyberwatch/pack_metadata.json
Labels: Contribution, docs-approved, Partner, pending-demo, Contribution Form Filled, pending-contributor, Partner Support Level, External PR, Partner-Approved

#40919 Removed query arg from PANOSQueryLogs wrapper polling script
  Packs/PAN-OS/ReleaseNotes/2_6_5.md
  Packs/PAN-OS/Scripts/PANOSQueryLogs/PANOSQueryLogs.py
  Packs/PAN-OS/Scripts/PANOSQueryLogs/PANOSQueryLogs.yml
  Packs/PAN-OS/Scripts/PANOSQueryLogs/PANOSQueryLogs_test.py
  Packs/PAN-OS/Scripts/PANOSQueryLogs/README.md
  Packs/PAN-OS/pack_metadata.json
Labels: docs-approved, ForceMerge, ready-for-pipeline-running

#40993 create a validation for se packs
  .github/github_workflow_scripts/check_if_se_packs_approved_label_exists.py
  .github/workflows/check-se-approved-label.yml
Labels: docs-approved, ready-for-pipeline-running

#40986 CarbonBlackLiveResponseCloud fix UT
  Packs/CarbonBlackDefense/Integrations/CarbonBlackLiveResponseCloud/CarbonBlackLiveResponseCloud.yml
  Packs/CarbonBlackDefense/Integrations/CarbonBlackLiveResponseCloud/CarbonBlackLiveResponseCloud_test.py
  Packs/CarbonBlackDefense/ReleaseNotes/4_0_10.md
  Packs/CarbonBlackDefense/pack_metadata.json
Labels: docs-approved, ready-for-pipeline-running

#40795 Improve Trend Micro Vision One Event Collector configurability and error handling
  Packs/TrendMicroVisionOne/Integrations/TrendMicroVisionOneEventCollector/README.md
  Packs/TrendMicroVisionOne/Integrations/TrendMicroVisionOneEventCollector/TrendMicroVisionOneEventCollector.py
  Packs/TrendMicroVisionOne/Integrations/TrendMicroVisionOneEventCollector/TrendMicroVisionOneEventCollector.yml
  Packs/TrendMicroVisionOne/Integrations/TrendMicroVisionOneEventCollector/TrendMicroVisionOneEventCollector_test.py
  Packs/TrendMicroVisionOne/ReleaseNotes/4_3_0.md
  Packs/TrendMicroVisionOne/pack_metadata.json
Labels: bug, inprogress, docs-approved, python, ready-for-pipeline-running

#41016 HashiCorp Vault update
  Packs/HashiCorp-Vault/Integrations/HashiCorpVault/HashiCorpVault.py
  Packs/HashiCorp-Vault/Integrations/HashiCorpVault/HashiCorpVault.yml
  Packs/HashiCorp-Vault/Integrations/HashiCorpVault/README.md
  Packs/HashiCorp-Vault/ReleaseNotes/1_1_31.md
  Packs/HashiCorp-Vault/pack_metadata.json
Labels: Contribution, docs-approved, Contribution Form Filled, Community, Xsoar Support Level, External PR

#41042 Slack V3: adding logs for the mirror-investigation command
  Packs/Slack/Integrations/SlackV3/SlackV3.py
  Packs/Slack/ReleaseNotes/3_5_28.md
  Packs/Slack/pack_metadata.json
Labels: docs-approved, ready-for-pipeline-running

#41044 CofenseTriagev3 fix UT
  Packs/CofenseTriage/Integrations/CofenseTriagev3/test_data/input_data.py
Labels: docs-approved, ready-for-pipeline-running

#41013 Exclude internal ip
  Packs/Anomali_ThreatStream/.pack-ignore
  Packs/Anomali_ThreatStream/Integrations/AnomaliThreatStreamv3/AnomaliThreatStreamv3.py
  Packs/Anomali_ThreatStream/Integrations/AnomaliThreatStreamv3/AnomaliThreatStreamv3.yml
  Packs/Anomali_ThreatStream/Integrations/Anomali_ThreatStream_v2/Anomali_ThreatStream_v2.py
  Packs/Anomali_ThreatStream/ReleaseNotes/2_2_31.md
  Packs/Anomali_ThreatStream/pack_metadata.json
  Packs/Base/ReleaseNotes/1_41_18.md
  Packs/Base/Scripts/CommonServerPython/CommonServerPython.py
  Packs/Base/Scripts/CommonServerPython/CommonServerPython_test.py
  Packs/Base/pack_metadata.json
  Packs/Flashpoint/Integrations/Ignite/Ignite.py
  Packs/Flashpoint/Integrations/Ignite/Ignite.yml
  Packs/Flashpoint/Integrations/Ignite/Ignite_test.py
  Packs/Flashpoint/ReleaseNotes/2_1_2.md
  Packs/Flashpoint/pack_metadata.json
  Packs/VirusTotal/Integrations/VirusTotalV3/VirusTotalV3.py
  Packs/VirusTotal/Integrations/VirusTotalV3/VirusTotalV3_test.py
  Packs/VirusTotal/ReleaseNotes/2_7_5.md
  Packs/VirusTotal/pack_metadata.json
Labels: docs-approved, ready-for-pipeline-running

#41055 Rename is_ip_internal function
  Packs/Anomali_ThreatStream/Integrations/AnomaliThreatStreamv3/AnomaliThreatStreamv3.py
  Packs/Anomali_ThreatStream/Integrations/Anomali_ThreatStream_v2/Anomali_ThreatStream_v2.py
  Packs/Anomali_ThreatStream/ReleaseNotes/2_2_32.md
  Packs/Anomali_ThreatStream/pack_metadata.json
  Packs/Base/ReleaseNotes/1_41_19.md
  Packs/Base/Scripts/CommonServerPython/CommonServerPython.py
  Packs/Base/Scripts/CommonServerPython/CommonServerPython_test.py
  Packs/Base/pack_metadata.json
  Packs/Flashpoint/Integrations/Ignite/Ignite.py
  Packs/Flashpoint/Integrations/Ignite/Ignite_test.py
  Packs/Flashpoint/ReleaseNotes/2_1_3.md
  Packs/Flashpoint/pack_metadata.json
  Packs/VirusTotal/Integrations/VirusTotalV3/VirusTotalV3.py
  Packs/VirusTotal/Integrations/VirusTotalV3/VirusTotalV3_test.py
  Packs/VirusTotal/ReleaseNotes/2_7_6.md
  Packs/VirusTotal/pack_metadata.json
Labels: docs-approved, ready-for-pipeline-running

#41057 [Red Canary] Handle null file paths in detection timeline processing
  Packs/RedCanary/Integrations/RedCanary/RedCanary.py
  Packs/RedCanary/Integrations/RedCanary/RedCanary.yml
  Packs/RedCanary/Integrations/RedCanary/RedCanary_test.py
  Packs/RedCanary/ReleaseNotes/1_1_28.md
  Packs/RedCanary/pack_metadata.json
Labels: docs-approved, ready-for-pipeline-running

#40953 added core actions
  Config/core_packs_platform_list.json
  Packs/Core/Scripts/CoreIsolateEndpoint/CoreIsolateEndpoint.py
  Packs/Core/Scripts/CoreIsolateEndpoint/CoreIsolateEndpoint.yml
  Packs/Core/Scripts/CoreIsolateEndpoint/CoreIsolateEndpoint_test.py
  Packs/Core/Scripts/CoreQuarantineFiles/CoreQuarantineFiles.py
  Packs/Core/Scripts/CoreQuarantineFiles/CoreQuarantineFiles.yml
  Packs/Core/Scripts/CoreQuarantineFiles/CoreQuarantineFiles_test.py
  Packs/Core/Scripts/CoreTerminateCausality/CoreTerminateCausality.py
  Packs/Core/Scripts/CoreTerminateCausality/CoreTerminateCausality.yml
  Packs/Core/Scripts/CoreTerminateCausality/CoreTerminateCausality_test.py
  Packs/Core/Scripts/CoreTerminateProcess/CoreTerminateProcess.py
  Packs/Core/Scripts/CoreTerminateProcess/CoreTerminateProcess.yml
  Packs/Core/Scripts/CoreTerminateProcess/CoreTerminateProcess_test.py
  Packs/Core/Scripts/CoreUnisolateEndpoint/CoreUnisolateEndpoint.py
  Packs/Core/Scripts/CoreUnisolateEndpoint/CoreUnisolateEndpoint.yml
  Packs/Core/Scripts/CoreUnisolateEndpoint/CoreUnisolateEndpoint_test.py
  Packs/Core/Scripts/SearchIndicatorInEventsAgentix/SearchIndicatorInEventsAgentix.py
  Packs/Core/Scripts/SearchIndicatorInEventsAgentix/SearchIndicatorInEventsAgentix.yml
  Packs/Core/Scripts/SearchIndicatorInEventsAgentix/SearchIndicatorInEventsAgentix_test.py
Labels: ready-for-pipeline-running

#40792 Created a new aggregated command Isolate Endpoint
  Packs/AggregatedScripts/.pack-ignore
  Packs/AggregatedScripts/ReleaseNotes/1_1_0.md
  Packs/AggregatedScripts/Scripts/IsolateEndpoint/IsolateEndpoint.py
  Packs/AggregatedScripts/Scripts/IsolateEndpoint/IsolateEndpoint.yml
  Packs/AggregatedScripts/Scripts/IsolateEndpoint/IsolateEndpoint_test.py
  Packs/AggregatedScripts/Scripts/IsolateEndpoint/README.md
  Packs/AggregatedScripts/TestPlaybooks/IsolateEndpoint_-_Testplaybook.yml
  Packs/AggregatedScripts/pack_metadata.json
  Tests/conf.json
Labels: docs-approved, ready-for-pipeline-running

#41085 update sane-pdf-reports docker
  Packs/Base/ReleaseNotes/1_41_21.md
  Packs/Base/Scripts/SanePdfReport/SanePdfReport.yml
  Packs/Base/pack_metadata.json
Labels: docs-approved, ready-for-pipeline-running

#41048 Add tpbs to aggregated scripts
  Packs/AggregatedScripts/ReleaseNotes/1_1_2.md
  Packs/AggregatedScripts/Scripts/ClearUserSession/ClearUserSession.yml
  Packs/AggregatedScripts/Scripts/DisableUser/DisableUser.yml
  Packs/AggregatedScripts/Scripts/GetUserData/GetUserData.yml
  Packs/AggregatedScripts/TestPlaybooks/ClearUserSession-Test.yml
  Packs/AggregatedScripts/TestPlaybooks/DisableUser-Test.yml
  Packs/AggregatedScripts/TestPlaybooks/GetUserData-Test.yml
  Packs/AggregatedScripts/pack_metadata.json
  Tests/conf.json
Labels: docs-approved, ForceMerge, sync-gsm, ready-for-pipeline-running

#41091 [Cortex XDR - IR] Remove from Platform marketplace
  Packs/CortexXDR/ReleaseNotes/6_2_35.md
  Packs/CortexXDR/pack_metadata.json
Labels: docs-approved, ForceMerge, ready-for-pipeline-running

#41047 AWSErrorHandler
  Packs/AWS/Integrations/AWS/AWS.py
  Packs/AWS/Integrations/AWS/AWS_test.py
  Packs/AWS/ReleaseNotes/2_0_5.md
  Packs/AWS/pack_metadata.json
Labels: docs-approved, ready-for-pipeline-running

#40952 update codeowners - platform automation
  .github/CODEOWNERS
Labels: docs-approved, ready-for-pipeline-running

#41025 Fix JiraV3 Issues Query using deprecated endpoint
  Packs/Jira/.secrets-ignore
  Packs/Jira/Integrations/JiraV3/JiraV3.py
  Packs/Jira/Integrations/JiraV3/JiraV3.yml
  Packs/Jira/Integrations/JiraV3/JiraV3_test.py
  Packs/Jira/Integrations/JiraV3/README.md
  Packs/Jira/ReleaseNotes/3_3_7.json
  Packs/Jira/ReleaseNotes/3_3_7.md
  Packs/Jira/pack_metadata.json
Labels: docs-approved, ready-for-pipeline-running

#40999 Raise Pack Version for Agentix Action Creation
  Packs/PrismaAccess/ReleaseNotes/2_1_21.md
  Packs/PrismaAccess/pack_metadata.json
Labels: docs-approved, ready-for-pipeline-running

#40947 Updated Relationship names in Mandiant Enrich and Feed Mandiant Integ…
  Packs/MandiantAdvantageThreatIntelligence/Integrations/FeedMandiantThreatIntelligence/FeedMandiantThreatIntelligence.py
  Packs/MandiantAdvantageThreatIntelligence/Integrations/FeedMandiantThreatIntelligence/FeedMandiantThreatIntelligence.yml
  Packs/MandiantAdvantageThreatIntelligence/Integrations/FeedMandiantThreatIntelligence/FeedMandiantThreatIntelligence_test.py
  Packs/MandiantAdvantageThreatIntelligence/Integrations/Mandiant/Mandiant.py
  Packs/MandiantAdvantageThreatIntelligence/Integrations/Mandiant/Mandiant.yml
  Packs/MandiantAdvantageThreatIntelligence/Integrations/Mandiant/Mandiant_test.py
  Packs/MandiantAdvantageThreatIntelligence/ReleaseNotes/1_1_8.md
  Packs/MandiantAdvantageThreatIntelligence/pack_metadata.json
Labels: Contribution, docs-approved, Partner, pending-demo, Contribution Form Filled, pending-contributor, Partner Support Level, External PR, Partner-Approved, TIM Review

#39982 Nbensalmon/ciac 10618/collection app sentinels.ai
  Packs/AppSentinelsAi/.pack-ignore
  Packs/AppSentinelsAi/.secrets-ignore
  Packs/AppSentinelsAi/Integrations/AppSentinelsAi/AppSentinelsAi.py
  Packs/AppSentinelsAi/Integrations/AppSentinelsAi/AppSentinelsAi.yml
  Packs/AppSentinelsAi/Integrations/AppSentinelsAi/AppSentinelsAi_description.md
  Packs/AppSentinelsAi/Integrations/AppSentinelsAi/AppSentinelsAi_image.png
  Packs/AppSentinelsAi/Integrations/AppSentinelsAi/AppSentinelsAi_test.py
  Packs/AppSentinelsAi/Integrations/AppSentinelsAi/README.md
  Packs/AppSentinelsAi/Integrations/AppSentinelsAi/command_examples.txt
  Packs/AppSentinelsAi/Integrations/AppSentinelsAi/test_data/events-dummy-data.json
  Packs/AppSentinelsAi/README.md
  Packs/AppSentinelsAi/pack_metadata.json
Labels: docs-approved, ready-for-pipeline-running

#40991 XSUP-54313
  Packs/CrowdStrikeFalcon/Integrations/CrowdStrikeFalcon/CrowdStrikeFalcon.py
  Packs/CrowdStrikeFalcon/Integrations/CrowdStrikeFalcon/CrowdStrikeFalcon_test.py
  Packs/CrowdStrikeFalcon/ReleaseNotes/2_3_8.md
  Packs/CrowdStrikeFalcon/pack_metadata.json
Labels: docs-approved, ready-for-pipeline-running

#41083 Mark remaining internal scripts with isInternal
  Packs/CrowdStrikeFalcon/ReleaseNotes/2_3_9.md
  Packs/CrowdStrikeFalcon/Scripts/CsFalconLiftHostContainment/CsFalconLiftHostContainment.yml
  Packs/CrowdStrikeFalcon/pack_metadata.json
  Packs/MicrosoftDefenderAdvancedThreatProtection/ReleaseNotes/1_20_8.md
  Packs/MicrosoftDefenderAdvancedThreatProtection/Scripts/MicrosoftAtpEndpoint/MicrosoftAtpEndpoint.yml
  Packs/MicrosoftDefenderAdvancedThreatProtection/Scripts/MicrosoftAtpIsolateMachine/MicrosoftAtpIsolateMachine.yml
  Packs/MicrosoftDefenderAdvancedThreatProtection/Scripts/MicrosoftAtpScIndicatorCreate/MicrosoftAtpScIndicatorCreate.yml
  Packs/MicrosoftDefenderAdvancedThreatProtection/Scripts/MicrosoftAtpStopAndQuarantineFile/MicrosoftAtpStopAndQuarantineFile.yml
  Packs/MicrosoftDefenderAdvancedThreatProtection/Scripts/MicrosoftAtpUnisolateMachine/MicrosoftAtpUnisolateMachine.yml
  Packs/MicrosoftDefenderAdvancedThreatProtection/pack_metadata.json
  Packs/MicrosoftGraphMail/ReleaseNotes/1_7_9.md
  Packs/MicrosoftGraphMail/Scripts/MsGraphMailDeleteEmail/MsGraphMailDeleteEmail.yml
  Packs/MicrosoftGraphMail/pack_metadata.json
  Packs/PAN-OS/ReleaseNotes/2_6_7.md
  Packs/PAN-OS/Scripts/PANOSQueryLogs/PANOSQueryLogs.yml
  Packs/PAN-OS/pack_metadata.json
  Packs/SentinelOne/ReleaseNotes/3_2_48.md
  Packs/SentinelOne/Scripts/SentinelOneListAgents/SentinelOneListAgents.yml
  Packs/SentinelOne/pack_metadata.json
Labels: docs-approved, ready-for-pipeline-running
