Repository demisto/content, pull requests merged in 2025-09, with the labels that each got.

#40925 CRTX-165828 - Mapping Tigera Calico Secure
  Packs/TigeraCalico/.pack-ignore
  Packs/TigeraCalico/.secrets-ignore
  Packs/TigeraCalico/ModelingRules/TigeraCalico/TigeraCalico.xif
  Packs/TigeraCalico/ModelingRules/TigeraCalico/TigeraCalico.yml
  Packs/TigeraCalico/ModelingRules/TigeraCalico/TigeraCalico_schema.json
  Packs/TigeraCalico/ParsingRules/TigeraCalico/TigeraCalico.xif
  Packs/TigeraCalico/ParsingRules/TigeraCalico/TigeraCalico.yml
  Packs/TigeraCalico/README.md
  Packs/TigeraCalico/pack_metadata.json
Labels: docs-approved, bypass.url, ready-for-pipeline-running

#41049 Asavenok/logos added
  Packs/AnsibleAlibabaCloud/Integrations/AnsibleAlibabaCloud/AnsibleAlibabaCloud_dark.svg
  Packs/AnsibleAlibabaCloud/Integrations/AnsibleAlibabaCloud/AnsibleAlibabaCloud_light.svg
  Packs/Ansible_Powered_Integrations/Integrations/AlibabaCloud/AlibabaCloud_dark.svg
  Packs/Ansible_Powered_Integrations/Integrations/AlibabaCloud/AlibabaCloud_light.svg
  Packs/CyberArkEPM/Integrations/CyberArkEPMEventCollector/CyberArkEPMEventCollector_dark.svg
  Packs/CyberArkEPM/Integrations/CyberArkEPMEventCollector/CyberArkEPMEventCollector_light.svg
  Packs/FeedFireEye/Integrations/FeedFireEye/FeedFireEye_dark.svg
  Packs/FireEye-Detection-on-Demand/Integrations/FireEye-Detection-on-Demand/FireEye-Detection-on-Demand_dark.svg
  Packs/FireEyeCM/Integrations/FireEyeCM/FireEyeCM_dark.svg
  Packs/FireEyeETP/Integrations/FireEyeETP/FireEyeETP_dark.svg
  Packs/FireEyeETP/Integrations/FireEyeETPEventCollector/FireEyeETPEventCollector_dark.svg
  Packs/FireEyeEX/Integrations/FireEyeEX/FireEyeEX_dark.svg
  Packs/FireEyeHX/Integrations/FireEyeHX/FireEyeHX_dark.svg
  Packs/FireEyeHX/Integrations/FireEyeHXEventCollector/FireEyeHXEventCollector_dark.svg
  Packs/FireEyeHX/Integrations/FireEyeHXv2/FireEyeHXv2_dark.svg
  Packs/FireEyeNX/Integrations/FireEyeNX/FireEyeNX_dark.svg
  Packs/cyberark_AIM/Integrations/CyberArkAIM/CyberArkAIM_dark.svg
  Packs/cyberark_AIM/Integrations/CyberArkAIM/CyberArkAIM_light.svg
  Packs/cyberark_AIM/Integrations/CyberArkAIM_v2/CyberArkAIM_v2_dark.svg
  Packs/cyberark_AIM/Integrations/CyberArkAIM_v2/CyberArkAIM_v2_light.svg
  Packs/fireeye/Integrations/Fireeye/Fireeye_dark.svg
  Packs/isight/Integrations/FireEyeISIGHT/FireEyeISIGHT_dark.svg
Labels: Contribution, docs-approved, Contribution Form Filled, Xsoar Support Level, External PR, TIM Review

#41094 New Scripts: MissingElements
  Packs/CommunityCommonScripts/ReleaseNotes/1_3_20.md
  Packs/CommunityCommonScripts/Scripts/MissingElements/MissingElements.py
  Packs/CommunityCommonScripts/Scripts/MissingElements/MissingElements.yml
  Packs/CommunityCommonScripts/Scripts/MissingElements/MissingElements_test.py
  Packs/CommunityCommonScripts/Scripts/MissingElements/README.md
  Packs/CommunityCommonScripts/pack_metadata.json
Labels: Contribution, docs-approved, Contribution Form Filled, Community, Community Support Level, External PR

#41075 TIM/Improve the removal of trailing characters in the format URL script
  Packs/ApiModules/Scripts/FormatURLApiModule/FormatURLApiModule.py
  Packs/ApiModules/Scripts/FormatURLApiModule/FormatURLApiModule_test.py
  Packs/CommonScripts/ReleaseNotes/1_20_10.md
  Packs/CommonScripts/pack_metadata.json
  Packs/Phishing/ReleaseNotes/3_7_10.md
  Packs/Phishing/pack_metadata.json
Labels: docs-approved, ready-for-pipeline-running

#41134 Tigera Calico fix the README file
  Packs/TigeraCalico/README.md
Labels: docs-approved, ready-for-pipeline-running

#41131 XQLDSHelper - Fixed an issue where it wasn't working on the unified platform.
  Packs/XQLDSHelper/ReleaseNotes/1_0_10.md
  Packs/XQLDSHelper/Scripts/XQLDSHelper/XQLDSHelper.py
  Packs/XQLDSHelper/Scripts/XQLDSHelper/XQLDSHelper.yml
  Packs/XQLDSHelper/pack_metadata.json
Labels: Contribution, docs-approved, Contribution Form Filled, Community, Community Support Level, External PR

#41058 Aruba Collector new command 'aruba-auth-test' alternatively to 'test-module'
  Packs/HPEArubaCentral/Integrations/HPEArubaCentralEventCollector/HPEArubaCentralEventCollector.py
  Packs/HPEArubaCentral/Integrations/HPEArubaCentralEventCollector/HPEArubaCentralEventCollector.yml
  Packs/HPEArubaCentral/Integrations/HPEArubaCentralEventCollector/HPEArubaCentralEventCollector_test.py
  Packs/HPEArubaCentral/Integrations/HPEArubaCentralEventCollector/README.md
  Packs/HPEArubaCentral/ReleaseNotes/1_1_0.json
  Packs/HPEArubaCentral/ReleaseNotes/1_1_0.md
  Packs/HPEArubaCentral/pack_metadata.json
Labels: docs-approved, ready-for-pipeline-running

#41052 Bitsight-Event-Collector/CIAC-12152
  Packs/BitSight/Integrations/BitSightEventCollector/BitSightEventCollector.py
  Packs/BitSight/Integrations/BitSightEventCollector/BitSightEventCollector.yml
  Packs/BitSight/Integrations/BitSightEventCollector/BitSightEventCollector_dark.svg
  Packs/BitSight/Integrations/BitSightEventCollector/BitSightEventCollector_description.md
  Packs/BitSight/Integrations/BitSightEventCollector/BitSightEventCollector_image.png
  Packs/BitSight/Integrations/BitSightEventCollector/BitSightEventCollector_light.svg
  Packs/BitSight/Integrations/BitSightEventCollector/BitSightEventCollector_test.py
  Packs/BitSight/Integrations/BitSightEventCollector/README.md
  Packs/BitSight/Integrations/BitSightEventCollector/command_examples.txt
  Packs/BitSight/ReleaseNotes/1_2_0.md
  Packs/BitSight/pack_metadata.json
Labels: docs-approved, ready-for-pipeline-running

#40684 CIAC-9227 - 'Monday' [collection] new pack
  Packs/Monday/.pack-ignore
  Packs/Monday/.secrets-ignore
  Packs/Monday/Integrations/MondayEventCollector/MondayEventCollector.py
  Packs/Monday/Integrations/MondayEventCollector/MondayEventCollector.yml
  Packs/Monday/Integrations/MondayEventCollector/MondayEventCollector_description.md
  Packs/Monday/Integrations/MondayEventCollector/MondayEventCollector_image.png
  Packs/Monday/Integrations/MondayEventCollector/MondayEventCollector_test.py
  Packs/Monday/Integrations/MondayEventCollector/README.md
  Packs/Monday/Integrations/MondayEventCollector/command_examples.txt
  Packs/Monday/README.md
  Packs/Monday/pack_metadata.json
Labels: docs-approved, ready-for-pipeline-running

#41115 MergeDictArray - fixed an issue where an error occurred when an empty array was passed to the "merge_with" parameter.
  Packs/FiltersAndTransformers/ReleaseNotes/1_3_10.md
  Packs/FiltersAndTransformers/Scripts/MergeDictArray/MergeDictArray.js
  Packs/FiltersAndTransformers/Scripts/MergeDictArray/MergeDictArray.yml
  Packs/FiltersAndTransformers/TestPlaybooks/playbook-MergeDictArray_Test.yml
  Packs/FiltersAndTransformers/pack_metadata.json
Labels: Contribution, docs-approved, Contribution Form Filled, Community, Xsoar Support Level, External PR

#41095 Add new integration parameter to support alt api endpoint
  Packs/Cisco-umbrella-cloud-security/CONTRIBUTORS.json
  Packs/Cisco-umbrella-cloud-security/Integrations/Cisco-umbrella-cloud-security/Cisco-umbrella-cloud-security.yml
  Packs/Cisco-umbrella-cloud-security/Integrations/CiscoUmbrellaCloudSecurityv2/CiscoUmbrellaCloudSecurityv2.py
  Packs/Cisco-umbrella-cloud-security/Integrations/CiscoUmbrellaCloudSecurityv2/CiscoUmbrellaCloudSecurityv2.yml
  Packs/Cisco-umbrella-cloud-security/Integrations/CiscoUmbrellaCloudSecurityv2/CiscoUmbrellaCloudSecurityv2_description.md
  Packs/Cisco-umbrella-cloud-security/Integrations/CiscoUmbrellaCloudSecurityv2/CiscoUmbrellaCloudSecurityv2_test.py
  Packs/Cisco-umbrella-cloud-security/Integrations/CiscoUmbrellaCloudSecurityv2/README.md
  Packs/Cisco-umbrella-cloud-security/ReleaseNotes/2_0_13.md
  Packs/Cisco-umbrella-cloud-security/pack_metadata.json
Labels: Contribution, docs-approved, Contribution Form Filled, Community, Xsoar Support Level, External PR

#41175 Add block external ip tpb fix v2
  Packs/AggregatedScripts/ReleaseNotes/1_1_7.md
  Packs/AggregatedScripts/Scripts/BlockExternalIp/BlockExternalIp.py
  Packs/AggregatedScripts/Scripts/BlockExternalIp/BlockExternalIp.yml
  Packs/AggregatedScripts/Scripts/BlockExternalIp/BlockExternalIp_test.py
  Packs/AggregatedScripts/Scripts/ClearUserSession/ClearUserSession.yml
  Packs/AggregatedScripts/Scripts/DisableUser/DisableUser.py
  Packs/AggregatedScripts/Scripts/DisableUser/DisableUser.yml
  Packs/AggregatedScripts/Scripts/IsolateEndpoint/IsolateEndpoint.yml
  Packs/AggregatedScripts/Scripts/QuarantineFile/QuarantineFile.yml
  Packs/AggregatedScripts/TestPlaybooks/BlockExternalIP-Test.yml
  Packs/AggregatedScripts/TestPlaybooks/DisableUser-Test.yml
  Packs/AggregatedScripts/pack_metadata.json
  Tests/conf.json
Labels: docs-approved, sync-gsm, ready-for-pipeline-running

#41141 Jira run query fix endpoint selection
  Packs/Jira/Integrations/JiraV3/JiraV3.py
  Packs/Jira/Integrations/JiraV3/JiraV3.yml
  Packs/Jira/Integrations/JiraV3/JiraV3_test.py
  Packs/Jira/ReleaseNotes/3_3_8.md
  Packs/Jira/pack_metadata.json
Labels: docs-approved, ready-for-pipeline-running

#41178 ListUsedDockerImages - fixing the automation's condition
  Packs/CommonScripts/ReleaseNotes/1_20_11.md
  Packs/CommonScripts/Scripts/ListUsedDockerImages/ListUsedDockerImages.py
  Packs/CommonScripts/Scripts/ListUsedDockerImages/ListUsedDockerImages.yml
  Packs/CommonScripts/Scripts/ListUsedDockerImages/ListUsedDockerImages_test.py
  Packs/CommonScripts/pack_metadata.json
Labels: docs-approved, ready-for-pipeline-running

#41154 Core platform fix test module
  Packs/Core/Integrations/CortexPlatformCore/CortexPlatformCore.py
  Packs/Core/ReleaseNotes/3_4_17.md
  Packs/Core/pack_metadata.json
Labels: docs-approved, ready-for-pipeline-running

#41196 Bump version base
  Packs/Base/ReleaseNotes/1_41_22.md
  Packs/Base/pack_metadata.json
Labels: docs-approved, ready-for-pipeline-running

#41185 Decrease default limit netskope collectors
  Packs/Netskope/Integrations/NetskopeEventCollector/NetskopeEventCollector.py
  Packs/Netskope/Integrations/NetskopeEventCollector/NetskopeEventCollector.yml
  Packs/Netskope/Integrations/NetskopeEventCollector/README.md
  Packs/Netskope/Integrations/NetskopeEventCollector_v2/NetskopeEventCollector_v2.py
  Packs/Netskope/Integrations/NetskopeEventCollector_v2/NetskopeEventCollector_v2.yml
  Packs/Netskope/Integrations/NetskopeEventCollector_v2/README.md
  Packs/Netskope/ReleaseNotes/4_1_1.md
  Packs/Netskope/pack_metadata.json
Labels: docs-approved, ready-for-pipeline-running

#41203 XSUP-55817 Azure AKS Update
  Packs/AzureKubernetesServices/ParsingRules/AzureKubernetesServices/AzureKubernetesServices.xif
  Packs/AzureKubernetesServices/ReleaseNotes/1_2_14.md
  Packs/AzureKubernetesServices/pack_metadata.json
Labels: docs-approved, bypass.url, ready-for-pipeline-running

#41209 Add Prometheus integration
  Packs/Prometheus/.pack-ignore
  Packs/Prometheus/.secrets-ignore
  Packs/Prometheus/Author_image.png
  Packs/Prometheus/CONTRIBUTORS.json
  Packs/Prometheus/Integrations/Prometheus/Prometheus.py
  Packs/Prometheus/Integrations/Prometheus/Prometheus.yml
  Packs/Prometheus/Integrations/Prometheus/Prometheus_description.md
  Packs/Prometheus/Integrations/Prometheus/Prometheus_image.png
  Packs/Prometheus/Integrations/Prometheus/Prometheus_test.py
  Packs/Prometheus/Integrations/Prometheus/README.md
  Packs/Prometheus/Integrations/Prometheus/command_examples.txt
  Packs/Prometheus/README.md
  Packs/Prometheus/pack_metadata.json
Labels: Contribution, docs-approved, Contribution Form Filled, Community, pending-contributor, External PR

#41200 TIM/Updated Domain REGEX to not include numbers in TLD
  Packs/Base/TestPlaybooks/playbook-Domain_extraction_test.yml
  Packs/CommonScripts/ReleaseNotes/1_20_12.md
  Packs/CommonScripts/Scripts/ExtractDomainAndFQDNFromUrlAndEmail/ExtractDomainAndFQDNFromUrlAndEmail.py
  Packs/CommonScripts/Scripts/ExtractDomainAndFQDNFromUrlAndEmail/ExtractDomainAndFQDNFromUrlAndEmail.yml
  Packs/CommonScripts/Scripts/ExtractDomainAndFQDNFromUrlAndEmail/ExtractDomainAndFQDNFromUrlAndEmail_test.py
  Packs/CommonScripts/pack_metadata.json
  Packs/CommonTypes/IndicatorTypes/reputation-domain.json
  Packs/CommonTypes/ReleaseNotes/3_9_3.md
  Packs/CommonTypes/pack_metadata.json
Labels: docs-approved, release-notes-only, ready-for-pipeline-running

#41030 Silentpush commands enhancement
  Packs/SilentPush/Integrations/SilentPush/README.md
  Packs/SilentPush/Integrations/SilentPush/SilentPush.py
  Packs/SilentPush/Integrations/SilentPush/SilentPush.yml
  Packs/SilentPush/Integrations/SilentPush/SilentPush_test.py
  Packs/SilentPush/ReleaseNotes/1_2_0.md
  Packs/SilentPush/pack_metadata.json
Labels: Contribution, docs-approved, Partner, Contribution Form Filled, pending-contributor, Partner Support Level, External PR, Partner-Approved

#41226 Ciac 14767 fix alreay isolated message
  Packs/AggregatedScripts/ReleaseNotes/1_1_11.md
  Packs/AggregatedScripts/Scripts/IsolateEndpoint/IsolateEndpoint.py
  Packs/AggregatedScripts/pack_metadata.json
Labels: docs-approved, ready-for-pipeline-running

#41106 Vectra XDR Release 1.1.0
  Packs/VectraXDR/.pack-ignore
  Packs/VectraXDR/.secrets-ignore
  Packs/VectraXDR/Integrations/VectraXDR/README.md
  Packs/VectraXDR/Integrations/VectraXDR/VectraXDR.py
  Packs/VectraXDR/Integrations/VectraXDR/VectraXDR.yml
  Packs/VectraXDR/Integrations/VectraXDR/VectraXDR_description.md
  Packs/VectraXDR/Integrations/VectraXDR/VectraXDR_test.py
  Packs/VectraXDR/Playbooks/playbook-Detections_Assessment_-_Vectra_XDR.yml
  Packs/VectraXDR/Playbooks/playbook-Detections_Assessment_-_Vectra_XDR_README.md
  Packs/VectraXDR/Playbooks/playbook-MDR_Escalation_Process_-_Vectra_XDR.yml
  Packs/VectraXDR/Playbooks/playbook-MDR_Escalation_Process_-_Vectra_XDR_README.md
  Packs/VectraXDR/ReleaseNotes/1_1_0.md
  Packs/VectraXDR/Scripts/VectraXDRDisplayEntityDetections/VectraXDRDisplayEntityDetections.yml
  Packs/VectraXDR/Scripts/VectraXDRDisplayEntityDetections/VectraXDRDisplayEntityDetections_test.py
  Packs/VectraXDR/Scripts/VectraXDRGenerateMailBody/README.md
  Packs/VectraXDR/Scripts/VectraXDRGenerateMailBody/VectraXDRGenerateMailBody.py
  Packs/VectraXDR/Scripts/VectraXDRGenerateMailBody/VectraXDRGenerateMailBody.yml
  Packs/VectraXDR/Scripts/VectraXDRGenerateMailBody/VectraXDRGenerateMailBody_test.py
  Packs/VectraXDR/doc_files/Detections_Assessment_-_Vectra_XDR.png
  Packs/VectraXDR/doc_files/MDR_Escalation_Process_-_Vectra_XDR.png
  Packs/VectraXDR/pack_metadata.json
Labels: Contribution, docs-approved, Partner, pending-demo, Contribution Form Filled, pending-contributor, Partner Support Level, External PR, Security Review, Partner-Approved, Security Approved

#40900 Fix event log was cleared
  Packs/CortexResponseAndRemediation/ReleaseNotes/1_2_2.md
  Packs/CortexResponseAndRemediation/pack_metadata.json
Labels: docs-approved, ready-for-pipeline-running

#41217 Generic SQL - adding another check in the test
  Packs/GenericSQL/Integrations/GenericSQL/GenericSQL.py
  Packs/GenericSQL/Integrations/GenericSQL/GenericSQL.yml
  Packs/GenericSQL/ReleaseNotes/1_3_13.md
  Packs/GenericSQL/pack_metadata.json
Labels: docs-approved, ForceMerge, ready-for-pipeline-running

#41103 Ss_fix_rundll32_playbook_refactor_effort
  Packs/CortexResponseAndRemediation/ReleaseNotes/1_2_3.md
  Packs/CortexResponseAndRemediation/pack_metadata.json
Labels: docs-approved, bypass.url, ready-for-pipeline-running

#41228 feat: add Cloud Incident Response as optional dependency for Office36…
  Packs/CloudIncidentResponse/README.md
  Packs/Office365/pack_metadata.json
Labels: docs-approved, bypass.url, ready-for-pipeline-running

#41243 Revert 41091
  Packs/CortexXDR/ReleaseNotes/6_2_36.md
  Packs/CortexXDR/pack_metadata.json
Labels: docs-approved, ready-for-pipeline-running

#41252 XSUP 55817 Azure AKS Update2
  Packs/AzureKubernetesServices/ParsingRules/AzureKubernetesServices/AzureKubernetesServices.xif
  Packs/AzureKubernetesServices/README.md
  Packs/AzureKubernetesServices/ReleaseNotes/1_2_15.md
  Packs/AzureKubernetesServices/pack_metadata.json
Labels: docs-approved, bypass.url, ready-for-pipeline-running

#41229 XSUP-55768 Executing the ResolveShortenedURL script results in Server Error (500)
  Packs/CommonScripts/.secrets-ignore
  Packs/CommonScripts/ReleaseNotes/1_20_14.json
  Packs/CommonScripts/ReleaseNotes/1_20_14.md
  Packs/CommonScripts/Scripts/ResolveShortenedURL/README.md
  Packs/CommonScripts/Scripts/ResolveShortenedURL/ResolveShortenedURL.py
  Packs/CommonScripts/Scripts/ResolveShortenedURL/ResolveShortenedURL.yml
  Packs/CommonScripts/Scripts/ResolveShortenedURL/ResolveShortenedURL_test.py
  Packs/CommonScripts/Scripts/ResolveShortenedURL/test_data/built-in/no_https_unshorten_expected_output.json
  Packs/CommonScripts/Scripts/ResolveShortenedURL/test_data/built-in/redirect_exception_expected_output.json
  Packs/CommonScripts/Scripts/ResolveShortenedURL/test_data/longurl.in/invalid_url.json
  Packs/CommonScripts/Scripts/ResolveShortenedURL/test_data/longurl.in/invalid_url_expected_output.json
  Packs/CommonScripts/Scripts/ResolveShortenedURL/test_data/longurl.in/limited_unshorten_expected_output.json
  Packs/CommonScripts/Scripts/ResolveShortenedURL/test_data/longurl.in/nested_unshorten_0.json
  Packs/CommonScripts/Scripts/ResolveShortenedURL/test_data/longurl.in/nested_unshorten_1.json
  Packs/CommonScripts/Scripts/ResolveShortenedURL/test_data/longurl.in/nested_unshorten_2.json
  Packs/CommonScripts/Scripts/ResolveShortenedURL/test_data/unshorten.me/invalid_url.json
  Packs/CommonScripts/Scripts/ResolveShortenedURL/test_data/unshorten.me/invalid_url_expected_output.json
  Packs/CommonScripts/Scripts/ResolveShortenedURL/test_data/unshorten.me/limited_unshorten_expected_output.json
  Packs/CommonScripts/Scripts/ResolveShortenedURL/test_data/unshorten.me/nested_unshorten_0.json
  Packs/CommonScripts/Scripts/ResolveShortenedURL/test_data/unshorten.me/nested_unshorten_1.json
  Packs/CommonScripts/Scripts/ResolveShortenedURL/test_data/unshorten.me/nested_unshorten_2.json
  Packs/CommonScripts/Scripts/ResolveShortenedURL/test_data/unshorten.me/nested_unshorten_expected_output.json
  Packs/CommonScripts/pack_metadata.json
Labels: docs-approved, ForceMerge, ready-for-pipeline-running

#41009 Rubrik Release 1.6.0
  Packs/RubrikPolaris/.pack-ignore
  Packs/RubrikPolaris/Classifiers/classifier-Rubrik_Polaris_Radar_-_Classification.json
  Packs/RubrikPolaris/Classifiers/classifier-Rubrik_Polaris_Radar_-_Mapping.json
  Packs/RubrikPolaris/IncidentFields/incidentfield-RubrikPolaris_Object_ID.json
  Packs/RubrikPolaris/IncidentFields/incidentfield-RubrikPolaris_Object_Name.json
  Packs/RubrikPolaris/IncidentFields/incidentfield-RubrikPolaris_Object_Type.json
  Packs/RubrikPolaris/IncidentFields/incidentfield-Rubrik_CDM_Cluster_ID.json
  Packs/RubrikPolaris/IncidentFields/incidentfield-Rubrik_CDM_Cluster_Name.json
  Packs/RubrikPolaris/IncidentFields/incidentfield-Rubrik_File_Match_Count.json
  Packs/RubrikPolaris/IncidentFields/incidentfield-Rubrik_Last_Detected.json
  Packs/RubrikPolaris/IncidentFields/incidentfield-Rubrik_Match_Types.json
  Packs/RubrikPolaris/IncidentTypes/incidenttype-Rubrik_Threat_Monitoring_Object.json
  Packs/RubrikPolaris/Integrations/RubrikPolaris/README.md
  Packs/RubrikPolaris/Integrations/RubrikPolaris/RubrikPolaris.py
  Packs/RubrikPolaris/Integrations/RubrikPolaris/RubrikPolaris.yml
  Packs/RubrikPolaris/Integrations/RubrikPolaris/RubrikPolaris_test.py
  Packs/RubrikPolaris/Integrations/RubrikPolaris/test_data/advance_ioc_scan_response.json
  Packs/RubrikPolaris/Integrations/RubrikPolaris/test_data/fetch_events_and_threat_monitoring_objects_incidents.json
  Packs/RubrikPolaris/Integrations/RubrikPolaris/test_data/fetch_incidents_success_incidents.json
  Packs/RubrikPolaris/Integrations/RubrikPolaris/test_data/fetch_incidents_success_response.json
  Packs/RubrikPolaris/Integrations/RubrikPolaris/test_data/fetch_threat_monitoring_objects_response.json
  Packs/RubrikPolaris/Integrations/RubrikPolaris/test_data/ioc_scan_list_v2_empty_response.json
  Packs/RubrikPolaris/Integrations/RubrikPolaris/test_data/ioc_scan_list_v2_response.json
  Packs/RubrikPolaris/Integrations/RubrikPolaris/test_data/ioc_scan_list_v2_response_hr.md
  Packs/RubrikPolaris/Integrations/RubrikPolaris/test_data/ioc_scan_results_v2_response.json
  Packs/RubrikPolaris/Integrations/RubrikPolaris/test_data/ioc_scan_results_v2_response_hr.md
  Packs/RubrikPolaris/Integrations/RubrikPolaris/test_data/threat_monitoring_file_get_response.json
  Packs/RubrikPolaris/Integrations/RubrikPolaris/test_data/threat_monitoring_file_get_response_hr.md
  Packs/RubrikPolaris/Integrations/RubrikPolaris/test_data/threat_monitoring_file_list_empty_response.json
  Packs/RubrikPolaris/Integrations/RubrikPolaris/test_data/threat_monitoring_file_list_response.json
  Packs/RubrikPolaris/Integrations/RubrikPolaris/test_data/threat_monitoring_file_list_response_hr.md
  Packs/RubrikPolaris/Integrations/RubrikPolaris/test_data/threat_monitoring_get_hr.md
  Packs/RubrikPolaris/Integrations/RubrikPolaris/test_data/threat_monitoring_get_response.json
  Packs/RubrikPolaris/Integrations/RubrikPolaris/test_data/threat_monitoring_list_empty_response.json
  Packs/RubrikPolaris/Integrations/RubrikPolaris/test_data/threat_monitoring_list_response.json
  Packs/RubrikPolaris/Integrations/RubrikPolaris/test_data/threat_monitoring_list_response_hr.md
  Packs/RubrikPolaris/Integrations/RubrikPolaris/test_data/turbo_ioc_scan_response.json
  Packs/RubrikPolaris/Layouts/layoutscontainer-Rubrik_Polaris_Radar.json
  Packs/RubrikPolaris/Layouts/layoutscontainer-Rubrik_Threat_Monitoring_Object.json
  Packs/RubrikPolaris/Playbooks/playbook-Rubrik_Anomaly_Incident_Response_-_Rubrik_Polaris.yml
  Packs/RubrikPolaris/Playbooks/playbook-Rubrik_Anomaly_Incident_Response_-_Rubrik_Polaris_README.md
  Packs/RubrikPolaris/Playbooks/playbook-Rubrik_Data_Object_Discovery_-_Rubrik_Polaris.yml
  Packs/RubrikPolaris/Playbooks/playbook-Rubrik_Data_Object_Discovery_-_Rubrik_Polaris_README.md
  Packs/RubrikPolaris/Playbooks/playbook-Rubrik_IOC_Scan_v2_-_Rubrik_Polaris.yml
  Packs/RubrikPolaris/Playbooks/playbook-Rubrik_IOC_Scan_v2_-_Rubrik_Polaris_README.md
  Packs/RubrikPolaris/Playbooks/playbook-Rubrik_Turbo_IOC_Scan_-_Rubrik_Polaris.yml
  Packs/RubrikPolaris/Playbooks/playbook-Rubrik_Turbo_IOC_Scan_-_Rubrik_Polaris_README.md
  Packs/RubrikPolaris/ReleaseNotes/1_6_0.md
  Packs/RubrikPolaris/doc_files/Rubrik_Anomaly_Incident_Response_-_Rubrik_Polaris.png
  Packs/RubrikPolaris/doc_files/Rubrik_IOC_Scan_v2_-_Rubrik_Polaris.png
  Packs/RubrikPolaris/doc_files/Rubrik_Turbo_IOC_Scan_-_Rubrik_Polaris.png
  Packs/RubrikPolaris/pack_metadata.json
Labels: Contribution, docs-approved, Partner, Contribution Form Filled, pending-contributor, Partner Support Level, External PR, Security Review, Partner-Approved, Security Approved

#41284 Fix Akamai waf README
  Packs/Akamai_SIEM/README.md
Labels: docs-approved, ready-for-pipeline-running

#41189 Microsoft graph Mail fix for big attachments
  Packs/ApiModules/Scripts/MicrosoftGraphMailApiModule/MicrosoftGraphMailApiModule.py
  Packs/MicrosoftGraphMail/ReleaseNotes/1_7_10.md
  Packs/MicrosoftGraphMail/pack_metadata.json
Labels: docs-approved, ready-for-pipeline-running

#41214 Nbensalmon/ciac 14500 tpb file enrichment
  Packs/AggregatedScripts/ReleaseNotes/1_1_13.md
  Packs/AggregatedScripts/Scripts/FileEnrichment/FileEnrichment.yml
  Packs/AggregatedScripts/TestPlaybooks/FileEnrichment-Test.yml
  Packs/AggregatedScripts/pack_metadata.json
  Tests/conf.json
Labels: docs-approved, ready-for-pipeline-running

#40764 [EWS v2] Fix formatted messages in bytes
  Packs/MicrosoftExchangeOnPremise/Integrations/EWSv2/EWSv2.py
  Packs/MicrosoftExchangeOnPremise/Integrations/EWSv2/EWSv2_test.py
  Packs/MicrosoftExchangeOnPremise/ReleaseNotes/2_2_14.md
  Packs/MicrosoftExchangeOnPremise/pack_metadata.json
  Packs/Phishing/TestPlaybooks/Phishing_v3_-_DomainSquatting+EML+MaliciousIndicators_-_Test.yml
Labels: docs-approved, Stale, ready-for-pipeline-running

#40587 IBM Storage Scale
  Packs/IBMStorageScale/.pack-ignore
  Packs/IBMStorageScale/.secrets-ignore
  Packs/IBMStorageScale/Integrations/IBMStorageScale/IBMStorageScale.py
  Packs/IBMStorageScale/Integrations/IBMStorageScale/IBMStorageScale.yml
  Packs/IBMStorageScale/Integrations/IBMStorageScale/IBMStorageScale_description.md
  Packs/IBMStorageScale/Integrations/IBMStorageScale/IBMStorageScale_image.png
  Packs/IBMStorageScale/Integrations/IBMStorageScale/IBMStorageScale_test.py
  Packs/IBMStorageScale/Integrations/IBMStorageScale/README.md
  Packs/IBMStorageScale/Integrations/IBMStorageScale/command_examples.txt
  Packs/IBMStorageScale/README.md
  Packs/IBMStorageScale/pack_metadata.json
Labels: docs-approved, ready-for-pipeline-running

#41289 Open aigpt params
  Packs/OpenAI/Integrations/OpenAiChatGPTV3/OpenAiChatGPTV3.py
  Packs/OpenAI/Integrations/OpenAiChatGPTV3/OpenAiChatGPTV3.yml
  Packs/OpenAI/Integrations/OpenAiChatGPTV3/OpenAiChatGPTV3_test.py
  Packs/OpenAI/ReleaseNotes/2_0_4.md
  Packs/OpenAI/pack_metadata.json
Labels: docs-approved, ready-for-pipeline-running

#41272 Refactoring_Script_file_added_to_startup-related_Registry_keys
  Packs/CortexResponseAndRemediation/Playbooks/playbook-Script_file_added_to_startup-related_Registry_keys_README.md
  Packs/CortexResponseAndRemediation/ReleaseNotes/1_2_12.md
  Packs/CortexResponseAndRemediation/doc_files/Script_file_added_to_startup-related_Registry_keys.png
  Packs/CortexResponseAndRemediation/pack_metadata.json
Labels: docs-approved, ready-for-pipeline-running

#41213 Get user data ciac 14680
  Packs/AggregatedScripts/ReleaseNotes/1_1_14.md
  Packs/AggregatedScripts/Scripts/GetUserData/GetUserData.py
  Packs/AggregatedScripts/Scripts/GetUserData/GetUserData_test.py
  Packs/AggregatedScripts/pack_metadata.json
Labels: docs-approved, ready-for-pipeline-running

#41299 CRTX-166115-Cisco-UCM
  Packs/CiscoUCM/.pack-ignore
  Packs/CiscoUCM/.secrets-ignore
  Packs/CiscoUCM/ModelingRules/CiscoUCM/CiscoUCM.xif
  Packs/CiscoUCM/ModelingRules/CiscoUCM/CiscoUCM.yml
  Packs/CiscoUCM/ModelingRules/CiscoUCM/CiscoUCM_schema.json
  Packs/CiscoUCM/ParsingRules/CiscoUCM/CiscoUCM.xif
  Packs/CiscoUCM/ParsingRules/CiscoUCM/CiscoUCM.yml
  Packs/CiscoUCM/README.md
  Packs/CiscoUCM/pack_metadata.json
Labels: docs-approved, bypass.url, ready-for-pipeline-running

#41258 QRadar fix parse log
  Packs/QRadar/Integrations/QRadar_v3/QRadar_v3.py
  Packs/QRadar/Integrations/QRadar_v3/QRadar_v3_test.py
  Packs/QRadar/ReleaseNotes/2_5_27.md
  Packs/QRadar/pack_metadata.json
Labels: docs-approved, ready-for-pipeline-running

#41101 feat: add AWS EKS, EC2 snapshot and ECS cluster management commands
  Packs/AWS/Integrations/AWS/AWS.py
  Packs/AWS/Integrations/AWS/AWS.yml
  Packs/AWS/Integrations/AWS/AWS_test.py
  Packs/AWS/Integrations/AWS/README.md
  Packs/AWS/ReleaseNotes/2_1_5.md
Labels: docs-approved, ready-for-pipeline-running

#41277 Change CreatePlbkDoc Docker
  Packs/CommunityCommonScripts/ReleaseNotes/1_3_23.md
  Packs/CommunityCommonScripts/Scripts/CreatePlbkDoc/CreatePlbkDoc.yml
  Packs/CommunityCommonScripts/pack_metadata.json
Labels: docs-approved, ready-for-pipeline-running

#41311 [XSUP-55140] Fix `Proofpoint Email Security Event Collector` fetch error handling
  Packs/ProofpointEmailSecurity/Integrations/ProofpointEmailSecurityEventCollector/ProofpointEmailSecurityEventCollector.py
  Packs/ProofpointEmailSecurity/Integrations/ProofpointEmailSecurityEventCollector/ProofpointEmailSecurityEventCollector.yml
  Packs/ProofpointEmailSecurity/ReleaseNotes/1_0_16.md
  Packs/ProofpointEmailSecurity/pack_metadata.json
Labels: docs-approved, ready-for-pipeline-running

#41291 FireEye ETP generic fix for duplicate events
  Packs/FireEyeETP/Integrations/FireEyeETPEventCollector/FireEyeETPEventCollector.py
  Packs/FireEyeETP/Integrations/FireEyeETPEventCollector/FireEyeETPEventCollector_test.py
  Packs/FireEyeETP/Integrations/FireEyeETPEventCollector/README.md
  Packs/FireEyeETP/ReleaseNotes/2_0_10.md
  Packs/FireEyeETP/pack_metadata.json
Labels: docs-approved, ready-for-pipeline-running

#41332 fix to AWS WAF parsing rule
  Packs/AWS_WAF/ParsingRules/AWS_WAF/AWS_WAF.xif
  Packs/AWS_WAF/ReleaseNotes/1_0_16.md
  Packs/AWS_WAF/pack_metadata.json
Labels: docs-approved, bypass.url, ready-for-pipeline-running

#40962 SPNs Cleared From a Machine Account - Refactor
  Packs/CortexResponseAndRemediation/Playbooks/playbook-SPNs_cleared_from_a_machine_account_README.md
  Packs/CortexResponseAndRemediation/ReleaseNotes/1_2_19.md
  Packs/CortexResponseAndRemediation/doc_files/SPNs_cleared_from_a_machine_account.png
  Packs/CortexResponseAndRemediation/pack_metadata.json
Labels: docs-approved, ready-for-pipeline-running

#41127 Adopt Splunk ES 8
  Packs/SplunkPy/Integrations/SplunkPy/README.md
  Packs/SplunkPy/Integrations/SplunkPy/SplunkPy.py
  Packs/SplunkPy/Integrations/SplunkPy/SplunkPy_test.py
  Packs/SplunkPy/ReleaseNotes/3_3_0.md
  Packs/SplunkPy/pack_metadata.json
Labels: docs-approved, ready-for-pipeline-running

#41318 Refactoring_Suspicious_Port_Scan
  Packs/CortexResponseAndRemediation/ReleaseNotes/1_2_20.md
  Packs/CortexResponseAndRemediation/doc_files/Suspicious_Port_Scan.png
  Packs/CortexResponseAndRemediation/pack_metadata.json
Labels: docs-approved, ready-for-pipeline-running

#41336 Whois - remove flakily failing UT
  Packs/Whois/Integrations/Whois/Whois_test.py
Labels: docs-approved, ready-for-pipeline-running

#41248 bug fix - set Microsoft Sentinel Classification Reason to empty if missing
  Packs/AzureSentinel/IncidentFields/incidentfield-Microsoft_Sentinel_Classification_Reason.json
  Packs/AzureSentinel/ReleaseNotes/1_5_71.md
  Packs/AzureSentinel/pack_metadata.json
Labels: docs-approved, ready-for-pipeline-running

#41344 Remediation information for xsoar dve enrichment
  Packs/Cybersixgill-DVE/Integrations/CybersixgillDVEEnrichment/CybersixgillDVEEnrichment.py
  Packs/Cybersixgill-DVE/Integrations/CybersixgillDVEEnrichment/CybersixgillDVEEnrichment.yml
  Packs/Cybersixgill-DVE/Integrations/CybersixgillDVEEnrichment/CybersixgillDVEEnrichment_test.py
  Packs/Cybersixgill-DVE/Integrations/CybersixgillDVEEnrichment/README.md
  Packs/Cybersixgill-DVE/ReleaseNotes/1_0_12.md
  Packs/Cybersixgill-DVE/pack_metadata.json
Labels: Contribution, docs-approved, Partner, Contribution Form Filled, Partner Support Level, External PR, Partner-Approved

#41309 Playbook Refactoring | Suspicious Hidden User Created
  Packs/CortexResponseAndRemediation/Playbooks/playbook-Suspicious_Hidden_User_Created_README.md
  Packs/CortexResponseAndRemediation/ReleaseNotes/1_2_21.md
  Packs/CortexResponseAndRemediation/doc_files/Suspicious_Hidden_User_Created.png
  Packs/CortexResponseAndRemediation/pack_metadata.json
Labels: docs-approved, ready-for-pipeline-running

#41172 Suspicious Local User Account Creation - PB Refactoring
  Packs/CortexResponseAndRemediation/ReleaseNotes/1_2_22.md
  Packs/CortexResponseAndRemediation/pack_metadata.json
Labels: docs-approved, ready-for-pipeline-running

#41306 [Collection] Saviynt Enterprise Identity Cloud
  Packs/SaviyntEIC/.pack-ignore
  Packs/SaviyntEIC/.secrets-ignore
  Packs/SaviyntEIC/Integrations/SaviyntEICEventCollector/README.md
  Packs/SaviyntEIC/Integrations/SaviyntEICEventCollector/SaviyntEICEventCollector.py
  Packs/SaviyntEIC/Integrations/SaviyntEICEventCollector/SaviyntEICEventCollector.yml
  Packs/SaviyntEIC/Integrations/SaviyntEICEventCollector/SaviyntEICEventCollector_description.md
  Packs/SaviyntEIC/Integrations/SaviyntEICEventCollector/SaviyntEICEventCollector_image.png
  Packs/SaviyntEIC/Integrations/SaviyntEICEventCollector/SaviyntEICEventCollector_test.py
  Packs/SaviyntEIC/README.md
  Packs/SaviyntEIC/pack_metadata.json
Labels: docs-approved, ready-for-pipeline-running

#41364 XSUP-55372 - microsoft_windows_raw - enhance regex extraction
  Packs/MicrosoftWindowsEvents/ModelingRules/MicrosoftWindowsEvents_1_3/MicrosoftWindowsEvents_1_3.xif
  Packs/MicrosoftWindowsEvents/ReleaseNotes/1_1_20.md
  Packs/MicrosoftWindowsEvents/pack_metadata.json
Labels: docs-approved, bypass.url, ready-for-pipeline-running, se-approved

#41363 CRTX 197958 add platform support
  Packs/CommonPlaybooks/Playbooks/playbook-File_Reputation.yml
  Packs/CommonPlaybooks/ReleaseNotes/2_7_17.md
  Packs/CommonPlaybooks/pack_metadata.json
Labels: docs-approved, ready-for-pipeline-running

#41327 Improve Generic Webhook docs
  Packs/GenericWebhook/Integrations/GenericWebhook/GenericWebhook_description.md
  Packs/GenericWebhook/Integrations/GenericWebhook/README.md
  Packs/GenericWebhook/ReleaseNotes/1_1_11.md
  Packs/GenericWebhook/pack_metadata.json
Labels: docs-approved, ready-for-pipeline-running

#41314 Xsup 55634 panorama fixes
  Packs/PAN-OS/Integrations/Panorama/Panorama.py
  Packs/PAN-OS/Integrations/Panorama/Panorama.yml
  Packs/PAN-OS/Integrations/Panorama/Panorama_test.py
  Packs/PAN-OS/Integrations/Panorama/README.md
  Packs/PAN-OS/Integrations/Panorama/test_data/pan-os-check-latest-dynamic-update-status_expected-returned-outputs-no-gp-license.json
  Packs/PAN-OS/ReleaseNotes/2_6_9.md
  Packs/PAN-OS/pack_metadata.json
Labels: docs-approved, ready-for-pipeline-running

#41143 Added Domain Search To SpyCloud Enterprise Feed App Configuration
  Packs/HarfangLabEDR/ReleaseNotes/1_2_4.md
  Packs/SpyCloudEnterpriseProtection/Integrations/SpyCloudEnterpriseProtectionFeed/README.md
  Packs/SpyCloudEnterpriseProtection/Integrations/SpyCloudEnterpriseProtectionFeed/SpyCloudEnterpriseProtectionFeed.py
  Packs/SpyCloudEnterpriseProtection/Integrations/SpyCloudEnterpriseProtectionFeed/SpyCloudEnterpriseProtectionFeed.yml
  Packs/SpyCloudEnterpriseProtection/Integrations/SpyCloudEnterpriseProtectionFeed/SpyCloudEnterpriseProtectionFeed_test.py
  Packs/SpyCloudEnterpriseProtection/Integrations/SpyCloudEnterpriseProtectionFeed/test_data/domain_data.json
  Packs/SpyCloudEnterpriseProtection/ReleaseNotes/1_0_5.md
  Packs/SpyCloudEnterpriseProtection/ReleaseNotes/1_0_6.md
  Packs/SpyCloudEnterpriseProtection/pack_metadata.json
  package-lock.json
Labels: Contribution, docs-approved, Partner, Contribution Form Filled, pending-contributor, Partner Support Level, External PR, Partner-Approved

#41302 CRTX-187328: GCP commands
  Packs/GCP/Integrations/GCP/GCP.py
  Packs/GCP/Integrations/GCP/GCP.yml
  Packs/GCP/Integrations/GCP/GCP_test.py
  Packs/GCP/Integrations/GCP/README.md
  Packs/GCP/Integrations/GCP/command_examples.txt
  Packs/GCP/Integrations/GCP/test_data/list_instances_response.json
  Packs/GCP/ReleaseNotes/1_1_0.md
  Packs/GCP/pack_metadata.json
Labels: docs-approved

#41269 Update Sigma Docker Tag
  Packs/Sigma/ReleaseNotes/1_1_0.md
  Packs/Sigma/Scripts/CreateSigmaRuleIndicator/CreateSigmaRuleIndicator.py
  Packs/Sigma/Scripts/CreateSigmaRuleIndicator/CreateSigmaRuleIndicator.yml
  Packs/Sigma/Scripts/CreateSigmaRuleIndicator/CreateSigmaRuleIndicator_test.py
  Packs/Sigma/Scripts/SigmaButtonConvert/SigmaButtonConvert.py
  Packs/Sigma/Scripts/SigmaButtonConvert/SigmaButtonConvert.yml
  Packs/Sigma/Scripts/SigmaButtonConvert/SigmaButtonConvert_test.py
  Packs/Sigma/Scripts/SigmaButtonConvert/test_data/xql_query.txt
  Packs/Sigma/Scripts/SigmaConverttoQuery/SigmaConverttoQuery.py
  Packs/Sigma/Scripts/SigmaConverttoQuery/SigmaConverttoQuery.yml
  Packs/Sigma/pack_metadata.json
Labels: docs-approved, ready-for-pipeline-running

#41282 RN
  Packs/Base/ReleaseNotes/1_41_23.md
  Packs/Base/pack_metadata.json
Labels: docs-approved, ready-for-pipeline-running

#41096 Add commands from Azure NSG to Azure integration
  Packs/Azure/Integrations/Azure/Azure.py
  Packs/Azure/Integrations/Azure/Azure.yml
  Packs/Azure/Integrations/Azure/Azure_test.py
  Packs/Azure/Integrations/Azure/README.md
  Packs/Azure/Integrations/Azure/command_examples.txt
  Packs/Azure/Integrations/Azure/test_data/create_or_update_rule_response.json
  Packs/Azure/Integrations/Azure/test_data/get_rule_response.json
  Packs/Azure/Integrations/Azure/test_data/list_network_security_groups_response.json
  Packs/Azure/Integrations/Azure/test_data/list_networks_interfaces_response.json
  Packs/Azure/Integrations/Azure/test_data/list_public_ip_addresses_response.json
  Packs/Azure/Integrations/Azure/test_data/list_resource_groups_response.json
  Packs/Azure/ReleaseNotes/1_1_0.md
  Packs/Azure/pack_metadata.json
Labels: docs-approved, ready-for-pipeline-running

#41382 Un deprecate forcepoint
  Packs/Forcepoint/Integrations/Forcepoint/Forcepoint.yml
  Packs/Forcepoint/Integrations/Forcepoint/README.md
  Packs/Forcepoint/README.md
  Packs/Forcepoint/ReleaseNotes/1_1_0.md
  Packs/Forcepoint/Scripts/FPDeleteRule/FPDeleteRule.yml
  Packs/Forcepoint/Scripts/FPSetRule/FPSetRule.yml
  Packs/Forcepoint/TestPlaybooks/playbook-Forcepoint_test.yml
  Packs/Forcepoint/pack_metadata.json
Labels: docs-approved, ready-for-pipeline-running

#41157 Set Indicator Agentix
  Packs/CommonScripts/ReleaseNotes/1_20_16.md
  Packs/CommonScripts/Scripts/SetIndicatorAgentix/SetIndicatorAgentix.py
  Packs/CommonScripts/Scripts/SetIndicatorAgentix/SetIndicatorAgentix.yml
  Packs/CommonScripts/Scripts/SetIndicatorAgentix/SetIndicatorAgentix_test.py
  Packs/CommonScripts/pack_metadata.json
Labels: docs-approved, ready-for-pipeline-running

#39843 Added Cortex Cloud Remediation Playbook
  Packs/CloudSecurityPostureManagement/.pack-ignore
  Packs/CloudSecurityPostureManagement/.secrets-ignore
  Packs/CloudSecurityPostureManagement/Playbooks/AWS_EC2_Instance_Misconfiguration_-_Remediate_and_Notify.yml
  Packs/CloudSecurityPostureManagement/Playbooks/AWS_EC2_Instance_Misconfiguration_-_Remediate_and_Notify_README.md
  Packs/CloudSecurityPostureManagement/Playbooks/AWS_IAM_Password_Policies_Misconfiguration_-_Remediate_and_Notify.yml
  Packs/CloudSecurityPostureManagement/Playbooks/AWS_IAM_Password_Policies_Misconfiguration_-_Remediate_and_Notify_README.md
  Packs/CloudSecurityPostureManagement/Playbooks/AWS_S3_Bucket_Publicly_Accessible_-_Remediate_and_Notify.yml
  Packs/CloudSecurityPostureManagement/Playbooks/AWS_S3_Bucket_Publicly_Accessible_-_Remediate_and_Notify_README.md
  Packs/CloudSecurityPostureManagement/Playbooks/Create_Ticket_and_Notify.yml
  Packs/CloudSecurityPostureManagement/Playbooks/Create_Ticket_and_Notify_README.md
  Packs/CloudSecurityPostureManagement/README.md
  Packs/CloudSecurityPostureManagement/Triggers/Remediation_playbook_for_AWS_EC2_misconfigurations.json
  Packs/CloudSecurityPostureManagement/Triggers/Remediation_playbook_for_AWS_IAM_password_policy_misconfiguration.json
  Packs/CloudSecurityPostureManagement/Triggers/Remediation_playbook_for_AWS_S3_bucket_publicly_accessible.json
  Packs/CloudSecurityPostureManagement/doc_files/AWS_EC2_Instance_Misconfiguration_-_Remediate_and_Notify.png
  Packs/CloudSecurityPostureManagement/doc_files/AWS_IAM_Password_Policies_Misconfiguration_-_Remediate_and_Notify.png
  Packs/CloudSecurityPostureManagement/doc_files/AWS_S3_Bucket_Publicly_Accessible_-_Remediate_and_Notify.png
  Packs/CloudSecurityPostureManagement/doc_files/Create_Ticket_and_Notify.png
  Packs/CloudSecurityPostureManagement/pack_metadata.json
Labels: Contribution, docs-approved, Contribution Form Filled, Community, Xsoar Support Level, External PR, Security Review, Security Approved, ready-for-pipeline-running

#41396 CTM360 Pack Update - Correct usage of fields
  Packs/CTM360-CyberBlindspot/Integrations/CyberBlindspot/CyberBlindspot.py
  Packs/CTM360-CyberBlindspot/Integrations/CyberBlindspot/CyberBlindspot_test.py
  Packs/CTM360-CyberBlindspot/Integrations/CyberBlindspot/test_data/card_details_response_valid.json
  Packs/CTM360-CyberBlindspot/Integrations/CyberBlindspot/test_data/card_list_cmd_result_valid.json
  Packs/CTM360-CyberBlindspot/Integrations/CyberBlindspot/test_data/cred_list_cmd_result_valid.json
  Packs/CTM360-CyberBlindspot/Integrations/CyberBlindspot/test_data/domain_list_cmd_result_valid.json
  Packs/CTM360-CyberBlindspot/Integrations/CyberBlindspot/test_data/fetch_cards_response_valid.json
  Packs/CTM360-CyberBlindspot/Integrations/CyberBlindspot/test_data/fetch_incidents_response_valid.json
  Packs/CTM360-CyberBlindspot/Integrations/CyberBlindspot/test_data/incident_details_response_valid.json
  Packs/CTM360-CyberBlindspot/Integrations/CyberBlindspot/test_data/incident_list_cmd_result_valid.json
  Packs/CTM360-CyberBlindspot/Integrations/CyberBlindspot/test_data/malware_logs_list_cmd_result_valid.json
  Packs/CTM360-CyberBlindspot/Integrations/CyberBlindspot/test_data/subdomain_list_cmd_result_valid.json
  Packs/CTM360-CyberBlindspot/ReleaseNotes/2_3_2.md
  Packs/CTM360-CyberBlindspot/pack_metadata.json
Labels: Contribution, docs-approved, Partner, Contribution Form Filled, Partner Support Level, External PR, Partner-Approved

#41261 delete and update
  Packs/ServiceNow/Integrations/ServiceNowv2/README.md
  Packs/ServiceNow/Integrations/ServiceNowv2/ServiceNowv2.py
  Packs/ServiceNow/Integrations/ServiceNowv2/ServiceNowv2.yml
  Packs/ServiceNow/Integrations/ServiceNowv2/ServiceNowv2_test.py
  Packs/ServiceNow/ReleaseNotes/2_8_12.md
  Packs/ServiceNow/pack_metadata.json
Labels: docs-approved, ready-for-pipeline-running

#41390 Disable network for Whois UT
  .pre-commit-config_template.yaml
Labels: docs-approved, ready-for-pipeline-running

#41375 XSUP-52796 - Fixed null timestamp handling
  Packs/CortexXpanse/Playbooks/Xpanse_-_Alert_Self-Enrichment.yml
  Packs/CortexXpanse/ReleaseNotes/1_2_14.md
  Packs/CortexXpanse/pack_metadata.json
Labels: docs-approved, ready-for-pipeline-running

#40683 SpecterOps Pack Adoption - BloodHoundEnterprise
  Packs/BloodHoundEnterprise/README.md
  Packs/BloodHoundEnterprise/pack_metadata.json
Labels: Contribution, docs-approved, Partner, Contribution Form Filled, pending-contributor, Xsoar Support Level, External PR, Partner-Approved

#41381 Nbensalmon/xsup 56190 falcon fetch bug
  Packs/CrowdStrikeFalcon/Integrations/CrowdStrikeFalcon/CrowdStrikeFalcon.py
  Packs/CrowdStrikeFalcon/Integrations/CrowdStrikeFalcon/CrowdStrikeFalcon_test.py
  Packs/CrowdStrikeFalcon/Integrations/CrowdStrikeFalcon/test_data/mock_detections_id_list.json
  Packs/CrowdStrikeFalcon/ReleaseNotes/2_3_11.md
  Packs/CrowdStrikeFalcon/pack_metadata.json
Labels: docs-approved, ready-for-pipeline-running

#41366 Playbook Refactoring | A user deleted multiple users for the first time
  Packs/CortexResponseAndRemediation/Playbooks/playbook-A_user_deleted_multiple_users_for_the_first_time_README.md
  Packs/CortexResponseAndRemediation/ReleaseNotes/1_2_23.md
  Packs/CortexResponseAndRemediation/doc_files/A_user_deleted_multiple_users_for_the_first_time.png
  Packs/CortexResponseAndRemediation/pack_metadata.json
Labels: docs-approved, ready-for-pipeline-running

#41422 added missing supportlevelheader key to the integration
  Packs/BloodHoundEnterprise/Integrations/BloodHoundEnterprise/BloodHoundEnterprise.yml
  Packs/BloodHoundEnterprise/Integrations/BloodHoundEnterprise/BloodHoundEnterprise_test.py
  Packs/BloodHoundEnterprise/ReleaseNotes/1_0_5.md
  Packs/BloodHoundEnterprise/pack_metadata.json
Labels: docs-approved, ready-for-pipeline-running

#41352 deprecated jq
  Packs/CommunityCommonScripts/ReleaseNotes/1_4_0.md
  Packs/CommunityCommonScripts/Scripts/Jq/Jq.yml
  Packs/CommunityCommonScripts/pack_metadata.json
Labels: docs-approved, ready-for-pipeline-running

#41399 Add command gcs-delete-file
  Packs/GoogleCloudStorage/Integrations/GoogleCloudStorage/GoogleCloudStorage.py
  Packs/GoogleCloudStorage/Integrations/GoogleCloudStorage/GoogleCloudStorage.yml
  Packs/GoogleCloudStorage/Integrations/GoogleCloudStorage/README.md
  Packs/GoogleCloudStorage/ReleaseNotes/1_0_17.md
  Packs/GoogleCloudStorage/pack_metadata.json
Labels: Contribution, docs-approved, Contribution Form Filled, Community, Xsoar Support Level, External PR

#41398 HashiCorp Vault cache token
  Packs/HashiCorp-Vault/CONTRIBUTORS.json
  Packs/HashiCorp-Vault/Integrations/HashiCorpVault/HashiCorpVault.py
  Packs/HashiCorp-Vault/Integrations/HashiCorpVault/HashiCorpVault.yml
  Packs/HashiCorp-Vault/Integrations/HashiCorpVault/README.md
  Packs/HashiCorp-Vault/ReleaseNotes/1_1_32.md
  Packs/HashiCorp-Vault/pack_metadata.json
Labels: Contribution, docs-approved, Contribution Form Filled, Community, Xsoar Support Level, External PR

#41434 SearchIndicatorAgentix - updated score to verdict
  Packs/CommonScripts/ReleaseNotes/1_20_19.md
  Packs/CommonScripts/Scripts/SearchIndicatorAgentix/SearchIndicatorAgentix.py
  Packs/CommonScripts/Scripts/SearchIndicatorAgentix/SearchIndicatorAgentix_test.py
  Packs/CommonScripts/pack_metadata.json
Labels: docs-approved, ready-for-pipeline-running

#41451 feat: add Web Link field to ThreatConnect group list output
  Packs/ThreatConnect/Integrations/ThreatConnectV3/ThreatConnectV3.py
  Packs/ThreatConnect/Integrations/ThreatConnectV3/ThreatConnectV3.yml
  Packs/ThreatConnect/ReleaseNotes/3_1_16.md
  Packs/ThreatConnect/pack_metadata.json
Labels: docs-approved, ready-for-pipeline-running

#41293 Aggregated Command Module
  Packs/AggregatedScripts/.pack-ignore
  Packs/AggregatedScripts/.secrets-ignore
  Packs/AggregatedScripts/ReleaseNotes/1_2_0.md
  Packs/AggregatedScripts/Scripts/DomainEnrichment/DomainEnrichment.py
  Packs/AggregatedScripts/Scripts/DomainEnrichment/DomainEnrichment.yml
  Packs/AggregatedScripts/Scripts/DomainEnrichment/DomainEnrichment_test.py
  Packs/AggregatedScripts/Scripts/DomainEnrichment/README.md
  Packs/AggregatedScripts/Scripts/DomainEnrichment/test_data/mock_domain_batch_results.json
  Packs/AggregatedScripts/Scripts/DomainEnrichment/test_data/mock_domain_tim_results.json
  Packs/AggregatedScripts/Scripts/IPEnrichment/IPEnrichment.py
  Packs/AggregatedScripts/Scripts/IPEnrichment/IPEnrichment.yml
  Packs/AggregatedScripts/Scripts/IPEnrichment/IPEnrichment_test.py
  Packs/AggregatedScripts/Scripts/IPEnrichment/README.md
  Packs/AggregatedScripts/Scripts/IPEnrichment/test_data/mock_ip_batch_results.json
  Packs/AggregatedScripts/Scripts/IPEnrichment/test_data/mock_ip_tim_results.json
  Packs/AggregatedScripts/Scripts/URLEnrichment/README.md
  Packs/AggregatedScripts/Scripts/URLEnrichment/URLEnrichment.py
  Packs/AggregatedScripts/Scripts/URLEnrichment/URLEnrichment.yml
  Packs/AggregatedScripts/Scripts/URLEnrichment/URLEnrichment_test.py
  Packs/AggregatedScripts/Scripts/URLEnrichment/test_data/mock_batch_results.json
  Packs/AggregatedScripts/Scripts/URLEnrichment/test_data/mock_tim_results.json
  Packs/AggregatedScripts/TestPlaybooks/DomainEnrichment-Test.yml
  Packs/AggregatedScripts/TestPlaybooks/IPEnrichment-Test.yml
  Packs/AggregatedScripts/TestPlaybooks/URLEnrichment-Test.yml
  Packs/AggregatedScripts/pack_metadata.json
  Packs/ApiModules/.secrets-ignore
  Packs/ApiModules/ReleaseNotes/2_3_0.md
  Packs/ApiModules/Scripts/AggregatedCommandApiModule/AggregatedCommandApiModule.py
  Packs/ApiModules/Scripts/AggregatedCommandApiModule/AggregatedCommandApiModule.yml
  Packs/ApiModules/Scripts/AggregatedCommandApiModule/AggregatedCommandApiModule_test.py
  Packs/ApiModules/Scripts/AggregatedCommandApiModule/README.md
  Packs/ApiModules/pack_metadata.json
  Tests/conf.json
  Tests/demistomock/demistomock.py
Labels: docs-approved, ready-for-pipeline-running

#41452 move ag104 to warning
  validation_config.toml
Labels: docs-approved, ready-for-pipeline-running

#41333 Refactoring_WmiPrvSe.exe_Rare_Child_Command_Line
  Packs/CortexResponseAndRemediation/Playbooks/playbook-WmiPrvSe.exe_Rare_Child_Command_Line_README.md
  Packs/CortexResponseAndRemediation/ReleaseNotes/1_2_28.md
  Packs/CortexResponseAndRemediation/doc_files/WmiPrvSe_exe_Rare_Child_Command_Line.png
  Packs/CortexResponseAndRemediation/pack_metadata.json
Labels: docs-approved, ready-for-pipeline-running

#41462 TIM / Update the threat actor layout and more feed improvements
  Packs/Base/ReleaseNotes/1_41_25.md
  Packs/Base/Scripts/CommonServerPython/CommonServerPython.py
  Packs/Base/pack_metadata.json
  Packs/CommonTypes/IndicatorFields/indicatorfield-primary_motivation.json
  Packs/CommonTypes/IndicatorTypes/reputation-file.json
  Packs/CommonTypes/Layouts/layoutscontainer-Threat_ActorV2.json
  Packs/CommonTypes/ReleaseNotes/3_9_5.md
  Packs/CommonTypes/pack_metadata.json
Labels: docs-approved, release-notes-only, ready-for-pipeline-running
